### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Log in - Keyboard is not consistent in safari and pressing enter does not submit a form

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28569] opened 2023-10-01 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to sign in page
2. Enter any email
3. Notice that keyboard in native ios app and safari web is not the same

## Expected Result:
 Both keyboard should be the same, or at least pressing "Go" should submit a form

## Actual Result:
Keyboards are not consistent.
a) In safari instead of "Return" sign it says "Go"
b) And pressing it won't submit the form unlike the native app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Safari

https://github.com/Expensify/App/assets/78819774/b7c6dc15-1322-4fe9-9b28-800664d280cb

IOS app

https://github.com/Expensify/App/assets/78819774/ed88e01a-8af7-4aed-a4c0-cb0516abc14d

https://github.com/Expensify/App/assets/78819774/2cfe7d44-a94b-4849-82ef-3c93e9b373b4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @alitoshmatov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696083514018509

n+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d106743c23a6474e</li>
        <li>Upwork Job ID: 1708590752340430848</li>
        <li>Last Price Increase: 2023-10-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27213706</li>
<li>ZhenjaHorbach | Contributor | 27213707</li>
<li>alitoshmatov | Reporter | 27213710</li>
</ul></li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-10-02 07:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Enter key press not submitting form in iOS Safari

### What is the root cause of that problem?
Root cause of the problem is simply there is onKeyPress handler in 
https://github.com/Expensify/App/blob/2160babec48a63cb93c660df4365bc4dc483ccb9/src/pages/signin/LoginForm/BaseLoginForm.js#L200

### What changes do you think we should make in order to solve the problem?
Adding following code in above file will ensure key press will be handled on pressing enter key.
`onKeyPress={({nativeEvent}) => nativeEvent.code === "Enter" && validateAndSubmitForm()}`

enterKeyHint/returnKeyType will simply set text label of return button, it will not submit form unless we have keypress handler attached to the textinput over which soft keyboard is being shown.

It should work on all platforms but it still needs to be cross verified if C+ picks this proposal.

Result

https://github.com/Expensify/App/assets/767439/234acab8-81a4-4ff4-8592-de3f908b7a05


### What alternative solutions did you explore? (Optional)
N/A

**Comment by flaviadefaria** [comment] 2023-10-03 10:35
@Ollyws any thoughts on the proposals above?

**Comment by ayazalavi** [comment] 2023-10-04 07:53
@Ollyws yes it is fixed.

**Comment by alitoshmatov** [comment] 2023-10-04 08:30
@Ollyws One note that this is not just signin page, this issue come up on https://github.com/Expensify/App/pull/28409 which  also has one input and submit was not working. I assume this happens in other places too

**Comment by ayazalavi** [comment] 2023-10-04 09:03
@alitoshmatov @Ollyws I think this can be fixed in all places if we implement onKeyPress handler in TextInput component and pass it a prop submitOnEnter which should handle submitting form. Can be generic solution.

**Comment by MonilBhavsar** [comment] 2023-10-06 09:52
I agree we should resolve the root cause and for all the forms.
@Ollyws could you please take a look at the above comment.

**Comment by flaviadefaria** [comment] 2023-10-12 10:43
@stephanieelliott  I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by MonilBhavsar** [comment] 2023-10-16 05:41
Thanks for clarifying! 🙌

**Comment by stephanieelliott** [comment] 2023-10-30 17:30
Summarizing payment on this issue: 

 - Issue reporter: @alitoshmatov $50 Upwork - PAID 
 - Contributor: @ZhenjaHorbach $500 Upwork - PAID 
 - Contributor+: @Ollyws $500 Upwork - PAID 
 
 Upwork job is [here](https://www.upwork.com/jobs/~01d106743c23a6474e), no bonus is included on payout

**Closed by stephanieelliott** 2023-10-30 17:30 UTC
Labels: External, Daily, Awaiting Payment, Bug
