### ISSUE TITLE
[HOLD for payment 2024-07-24] [$125] [Payment Card / Subscription] Update the payment card icon in the Subscription tab

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#45123] opened 2024-07-09 22:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.5-10
**Reproducible in staging?:** Staging
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):**
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** mitch@expebsify.com 
**Slack conversation:** Internal: https://expensify.slack.com/archives/C036QM0SLJK/p1720560965872139?thread_ts=1720544914.651789&cid=C036QM0SLJK

## Action Performed:
1. Open new.expensify.com/settings/subscription

## Expected Result:
New Feature, the card icon in the Payment section look like this:

![image](https://github.com/Expensify/App/assets/36425901/4bd0b8c4-2bb4-415c-92bf-cfe2818de2da)

## Actual Result:
The card icon is darker than expected:
![image](https://github.com/Expensify/App/assets/36425901/ba05b8c4-7ff3-4fd2-b90a-0994dda98850)

## Workaround:
Ignore it 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Added above

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01131af4be64782018</li>
        <li>Upwork Job ID: 1810980051927666414</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103066408</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by trjExpensify** [comment] 2024-07-10 10:11
Going to export this at $125 as it's a simple icon change.

**Comment by trjExpensify** [comment] 2024-07-10 10:15
This icon is too dark: 

<img width="493" alt="image" src="https://github.com/Expensify/App/assets/16232057/c166f0bb-4395-4b32-879a-a4b89566de58">

**Comment by Christinadobrzyn** [comment] 2024-07-16 23:12
PR in staging - getting close! https://github.com/Expensify/App/pull/45219

**Comment by Christinadobrzyn** [comment] 2024-07-23 19:06
Preparing for payment 

Payouts due:

- [ ] Contributor: $125 @Krishna2323 (offer in Upwork - https://www.upwork.com/nx/wm/workroom/37781500/overview)
- [ ] Contributor+: $125 @parasharrajat (paid through New Dot)

@parasharrajat do we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2024-07-24 19:17
Payment day - 

- Regression test - https://github.com/Expensify/Expensify/issues/415142
- Payment summary - https://github.com/Expensify/App/issues/45123#issuecomment-2246066127

Closing this out since @parasharrajat will be paid through NewDot.

**Closed by Christinadobrzyn** 2024-07-24 19:17 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-03 19:13
$125 approved for @parasharrajat
