### ISSUE TITLE
[$500] Web - It's possible to create a tag name "0", the app will crash when it's deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45016] opened 2024-07-08 21:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/44391
## Action Performed:
1. Go to www.staging.chat.expensify.com
2. Create a new workspace and enable Tags
3. Create tag with "0" name
4. Try to delete this Tag

## Expected Result:
Not possible to create tag with "0" name, when it fails, verify the tag name reverts to the previous name
Verify the error is cleared if close button is pressed

## Actual Result:
It's possible to create a tag name "0", no error appears.
The app will crash when it's deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7c070905-2542-4b15-82b7-5afc7fd53354

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c39ad7db952ea6b</li>
        <li>Upwork Job ID: 1811206201231781305</li>
        <li>Last Price Increase: 2024-09-09</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 103558323</li>
<li>Krishna2323 | Contributor | 103558324</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by lanitochka17** [comment] 2024-07-08 21:50
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 21:51
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-07-09 03:52
BE issue, the API response returns the tags as an array of `null`.

<img width="316" alt="Screenshot 2024-07-09 at 11 43 47" src="https://github.com/Expensify/App/assets/50919443/5a851695-3f94-469e-afd2-eaa066b77d7d">

cc: @danieldoglas

**Comment by danieldoglas** [comment] 2024-07-09 09:07
hm, I think the backend changes didn't go out yet, so we might need to retest this after we deploy the beckend

**Comment by isabelastisser** [comment] 2024-07-11 01:08
It's not overdue; waiting to retest this!

**Comment by ahmedGaber93** [comment] 2024-07-16 05:46
@danieldoglas I don't know if backend deployed or not, but I test this today and I see backend return incorrect data.

API `CreatePolicyTag` response for tag '0' (tags type is `array`).

![Screenshot 2024-07-16 at 8 35 49 AM](https://github.com/user-attachments/assets/9038a0b5-27a2-4ec3-9155-7ab7d4860e3d)

API `CreatePolicyTag` response for tag '2' (tags type is `object`).


![Screenshot 2024-07-16 at 8 35 28 AM](https://github.com/user-attachments/assets/34bad22a-8905-45fb-9400-e9f4f7c0e779)

**Comment by isabelastisser** [comment] 2024-07-18 17:06
Hey @danieldoglas, can you please look at the comment above? Thanks!

**Comment by isabelastisser** [comment] 2024-07-18 17:07
I will be OOO tomorrow and next week, reassigning this until I'm back on July 29. Thanks, @lschurr!

**Comment by ahmedGaber93** [comment] 2024-07-22 10:00
Still waiting for backend opinion here https://github.com/Expensify/App/issues/45016#issuecomment-2230073182

**Comment by ahmedGaber93** [comment] 2024-07-25 09:48
@danieldoglas could you please take a look here https://github.com/Expensify/App/issues/45016#issuecomment-2230073182 when you have a chance?

**Comment by danieldoglas** [comment] 2024-07-26 15:24
Hi,

Yes, there's still a backend issue there. I'll need to investigate it. Sorry for the long wait, I was OOO.

**Comment by isabelastisser** [comment] 2024-07-29 18:19
I'm back, taking this! Thanks, @lschurr!

**Comment by ahmedGaber93** [comment] 2024-08-01 16:15
Not overdue, still investigated on BE side https://github.com/Expensify/App/issues/45016#issuecomment-2252996250

**Comment by ahmedGaber93** [comment] 2024-08-05 18:09
Waiting to backend fix here https://github.com/Expensify/App/issues/45016#issuecomment-2252996250, then retest.

**Comment by danieldoglas** [comment] 2024-08-08 16:22
This is a problem in the backend now - trying to work out what to do with the automatic parsers that are transforming the object with "0" to an array

**Comment by ahmedGaber93** [comment] 2024-08-08 20:51
Not overdue, BE fix in progress.

**Comment by mvtglobally** [comment] 2024-08-09 04:33
Issue is reproducible during KI retests.

https://github.com/user-attachments/assets/eea4f88c-47da-4909-96f4-9321c9e8100c

**Comment by ahmedGaber93** [comment] 2024-08-12 19:07
Not overdue, BE fix in progress.

**Comment by isabelastisser** [comment] 2024-08-15 17:56
Not overdue.

**Comment by ahmedGaber93** [comment] 2024-08-15 19:44
Not overdue, BE fix in progress.

**Comment by danieldoglas** [comment] 2024-08-16 18:29
I've had some discussions internally - we might actually remove "0" as a possible name for the tags.

**Comment by danieldoglas** [comment] 2024-08-16 18:30
@Krishna2323 are you interested in working in this? You had the first proposal

**Comment by danieldoglas** [comment] 2024-08-16 18:36
assined you to it!

**Comment by danieldoglas** [comment] 2024-08-20 16:00
That's good enough for the message.

**Comment by trjExpensify** [comment] 2024-09-05 12:09
@danieldoglas @isabelastisser can we consolidate all of these "tag 0" issues into here? it seems crazy we have so many issues for this edge case that I highly doubt any real world customer will actually configure. Namely, these: 

- https://github.com/Expensify/App/issues/48394
- https://github.com/Expensify/App/issues/48300

**Comment by danieldoglas** [comment] 2024-09-05 14:19
Yes, let's add them all here.

@Krishna2323 can you also add that validation for custom tags?

**Comment by VictoriaExpensify** [comment] 2024-09-09 06:02
Here's another one - https://github.com/Expensify/App/issues/48584

I'm going to go ahead and close that one out

**Comment by danieldoglas** [comment] 2024-09-09 18:18
bump @Krishna2323, let me know when you have a PR for those.

also, I understand that this is a different situation than what was initially proposed and (correctly) fixed, so I'll raise this to $500.

**Comment by danieldoglas** [comment] 2024-09-20 13:59
hmm that's strange. I think it was, since it was part of the checklist as well. @ahmedGaber93 can you test if it's working in production as it should? If yes I'll add the awaiting for payment label.

**Comment by ahmedGaber93** [comment] 2024-09-20 14:03
@danieldoglas, yes it works on production.

**Comment by danieldoglas** [comment] 2024-09-20 14:07
@isabelastisser all yours for payment!

**Comment by isabelastisser** [comment] 2024-09-20 14:44
Paid in Upwork. All set!

**Closed by isabelastisser** 2024-09-20 14:44 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by ahmedGaber93** [comment] 2024-09-20 15:27
@isabelastisser This issue is $500 price not $250

**Comment by isabelastisser** [comment] 2024-09-20 16:23
Hi @ahmedGaber93, I'm sorry for the confusion! I thought that the price increase was only applied to the C+ review. I will adjust the offer price in Upwork now.
