### ISSUE TITLE
iOS Expense - App crashes when unselecting category after disabling all categories

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48195] opened 2024-08-28 16:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-11
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4897807
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit at least two expenses with category
4. Go to workspace settings > Categories
5. Disable all the categories
6. Go back to workspace chat
7. Go to transaction thread (any expense in Step 3)
8. Click Category
9. Tap on the selected category

## Expected Result:
App will not crash

## Actual Result:
App crashes when unselecting category in transaction thread after disabling all categories

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/76c8610b-e828-48a0-ac85-759cde3cebf7

[logs (2).txt](https://github.com/user-attachments/files/16786570/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-08-28 16:51
We think that this bug might be related to #wave-collect - Release 1

**Comment by Gonals** [comment] 2024-08-29 12:36
Tested a few times and I haven't been able to reproduce the crash. @cristipaval also gave it a shot and it worked for him in an actual device, so closing for now

**Comment by IuliiaHerets** [comment] 2024-08-29 20:16
The issue is still reproducible, build - v9.0.26-3

Uploading RPReplay_Final1724962422.MP4…

**Comment by Gonals** [comment] 2024-08-30 08:06
I still can't reproduce it. Is it a specific device?

**Comment by IuliiaHerets** [comment] 2024-08-30 09:21
No, as a minimum 2 testers can repro this issue in the different devices

**Comment by Gonals** [comment] 2024-09-02 10:56
Was this tested on physical devices or on the simulator? In either case, which models were used?

**Comment by Gonals** [comment] 2024-09-05 07:48
Tried to reproduce again if a few different simulated devices to no avail. Closing.

**Closed by Gonals** 2024-09-05 07:48 UTC
Labels: Engineering, Daily, Overdue
