### ISSUE TITLE
Total request money wrong after delete a request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24241] opened 2023-08-08 00:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat with a user have chatted together before
2. Click + in compose and create 2 requests money
3. Click request money view
4. Delete one of requests, Observe that total remains the same after being deleted
## Expected Result: 
Total update after delete a request money
## Actual Result: 
Total not update after delete a request money

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b06df16e-0b90-408c-9fa5-bf1f82e1534c

https://github.com/Expensify/App/assets/43996225/9da506b4-22c8-4578-bb1d-7a4f0dc5478d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691235556837429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-08-08 06:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The total amount of money requested does not decrease when canceling other requests and does not show the request total to the assigned user 

### What is the root cause of that problem?
If cancel the money request, the money request report's `total` is decreased.
But `MoneyReqeustView` will not be refreshed, because `ReportActionItem` does not check if the `total` field is changed or not.
https://github.com/Expensify/App/blob/012d604753e6ed2f97736d47b28486f813995165/src/pages/home/report/ReportActionItem.js#L601-L625
So the total amount of money request does not decrease.

### What changes do you think we should make in order to solve the problem?
We should add checking if `report.total` is changed or not in `ReportActionItem`.
```js
    memo(
        ReportActionItem,
        (prevProps, nextProps) =>
            ...
            lodashGet(prevProps.report, 'total') === lodashGet(nextProps.report, 'total'),
    ),
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by srikarparsi** [comment] 2023-08-08 16:47
We can close this out as it's being taken care of in this [deploy blocker](https://github.com/Expensify/App/issues/24267).

**Comment by StevenKKC** [comment] 2023-08-08 16:53
@srikarparsi Should I raise PR in this issue? https://github.com/Expensify/App/issues/24267 is already closed.

**Comment by Julesssss** [comment] 2023-08-14 15:27
> We can close this out as it's being taken care of in this https://github.com/Expensify/App/issues/24267.

I think it might not be handled still.

**Comment by mallenexpensify** [comment] 2023-09-05 02:24
Removing `Reviewing` so this'll go overdue so we can see if an action is needed. 
@Julesssss any current thoughts?

**Comment by Julesssss** [comment] 2023-09-05 08:13
I think this is done. The linked [PR](https://github.com/Expensify/App/issues/24267) was closed and I can't reproduce it anymore. 

<img width="550" alt="Screenshot 2023-09-05 at 09 13 11" src="https://github.com/Expensify/App/assets/10736861/9d0c35c4-e215-49bc-9817-52cb133c7b6f">

**Closed by Julesssss** 2023-09-05 08:13 UTC
Labels: Weekly, Bug
