### ISSUE TITLE
[HOLD for payment 2024-06-13] [$250] Android - Receipt - Receipt view is inconsistent in mweb&Android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40788] opened 2024-04-23 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4504759
**Issue reported by:**Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
/ launch app
2. Tap on Workspace chat
3. Tap plus icon -- submit expense
4. Submit an expense with below receipt attached
5. Open the expense and tap on the receipt

## Expected Result:
Receipt view must not be inconsistent in mweb and Android

## Actual Result:
Receipt is shown smaller in mweb and bigger in Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/35c95315-1fee-43ff-935d-bb9d2849ac7f

![Bug6458565_1713864324852!w_6918299a5fd0b2469173078141943060da451901-2024-04-23_08_13_13 352](https://github.com/Expensify/App/assets/78819774/87899251-fb79-4ad6-888f-ae5310aa2f3e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a54a18910078b715</li>
        <li>Upwork Job ID: 1783190710289416192</li>
        <li>Last Price Increase: 2024-05-08</li>
<li>Automatic offers: </li>
<ul>
<li>samilabud | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by lanitochka17** [comment] 2024-04-23 12:45
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by samilabud** [comment] 2024-04-26 19:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android receipts are displayed as the same size of the canvas size

### What is the root cause of that problem?
We we open a receipt in android native we are using the [Lightbox componet](https://github.com/Expensify/App/blob/main/src/components/ImageView/index.native.tsx) unlike other platform we are using [ImageView component](https://github.com/Expensify/App/blob/7b6ce9856624f3b4d053de522db453890d291cfd/src/components/ImageView/index.tsx). The issue here is when we show the image in the Lightbox we are using an [Image component](https://github.com/Expensify/App/blob/7727e0ead9d856fcc00ac75c37de58bfa019aa86/src/components/Lightbox/index.tsx#L217) with the same size that the container [MultigestureCanvas](https://github.com/Expensify/App/blob/7727e0ead9d856fcc00ac75c37de58bfa019aa86/src/components/Lightbox/index.tsx#L206), this make the image adapt the size to the full screen.

### What changes do you think we should make in order to solve the problem?
We should specify the content size of the container [MultigestureCanvas](https://github.com/Expensify/App/blob/7727e0ead9d856fcc00ac75c37de58bfa019aa86/src/components/Lightbox/index.tsx#L206) to the canvasSize like:
```
<MultiGestureCanvas
                                isActive={isActive}
                                canvasSize={canvasSize}
                                **contentSize={canvasSize}**
                                zoomRange={zoomRange}
                                pagerRef={pagerRef}
                                shouldDisableTransformationGestures={isPagerScrolling}
                                onTap={onTap}
                                onScaleChanged={scaleChange}
                                onSwipeDown={onSwipeDown}
                            >
```

Testing the change:

https://github.com/Expensify/App/assets/5216036/36abb95d-9e9f-4633-a1b8-5d879fe83fb0


https://github.com/Expensify/App/blob/main/src/components/Lightbox/index.tsx

**Comment by CortneyOfstad** [comment] 2024-04-29 14:59
@eVoloshchak any thoughts on the proposal above?

**Comment by eVoloshchak** [comment] 2024-05-01 12:25
@samilabud, thank you for the [proposal](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532)!
Unfortunately, it breaks the layout of bigger images (i.e. if the image resolution is bigger than the screen resolution, it isn't resized to fit)

https://github.com/Expensify/App/assets/9059945/cde04716-e4ae-47f3-ba3b-ad7b201e1062

**Comment by samilabud** [comment] 2024-05-01 14:14
> @samilabud, thank you for the [proposal](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532)! Unfortunately, it breaks the layout of bigger images (i.e. if the image resolution is bigger than the screen resolution, it isn't resized to fit)
> 
>  Screen.Recording.2024-05-01.at.14.22.45.mov

Oh you were right, I have updated my [proposal](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532) with a new video and added a function to determinate if we should resize the image to fit the canvas size, please let me know if it looks good to you 🙏🏼

**Comment by CortneyOfstad** [comment] 2024-05-01 16:08
Thanks @samilabud! 

CC @eVoloshchak 👍

**Comment by eVoloshchak** [comment] 2024-05-06 15:27
@samilabud, I still think this is more of a workaround than an actual fix of the root cause, let's try to dig a bit deeper.
Why is passing correct content size as `contentSize` results in image being displayed incorrectly? Is this something that could be fixed inside of the `MultiGestureCanvas` itself?

**Comment by samilabud** [comment] 2024-05-07 13:37
> Is this something that could be fixed inside of the `MultiGestureCanvas` itself?
Hi @eVoloshchak, please see my alternative proposal, and thanks for the suggestions it makes more sense!

## Proposal
[Updated](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532)

**Comment by CortneyOfstad** [comment] 2024-05-08 17:46
@eVoloshchak it looks like we have an updated proposal [here](https://github.com/Expensify/App/issues/40788#issuecomment-2098431874). Can you take a look when you have a chance? Thanks!

**Comment by CortneyOfstad** [comment] 2024-05-10 15:12
@eVoloshchak just bumping for feedback on the proposal above — thanks!

**Comment by CortneyOfstad** [comment] 2024-05-13 14:07
@eVoloshchak bump again — please have the feedback provided by EOD. Thanks!

**Comment by eVoloshchak** [comment] 2024-05-13 15:18
@samilabud, I think I'm missing the updated proposal, GH says the proposal was last updated on May 1st
<img width="631" alt="Screenshot 2024-05-13 at 17 12 07" src="https://github.com/Expensify/App/assets/9059945/14a978b8-5096-428a-b3de-096342efc10a">

> Why is passing correct content size as contentSize results in image being displayed incorrectly?

We need to know the answer to this question. We pass the correct `contentSize`, correct `canvasSize`, but if the content is smaller than the canvas, it is displayed incorrectly. 
Could this be a problem with `MultiGestureCanvas` itself?

**Comment by samilabud** [comment] 2024-05-13 17:21
Now I have updated it, sorry for the inconvenience, any suggestions I am at your service.

## Proposal
[Updated](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532)

**Comment by eVoloshchak** [comment] 2024-05-14 16:50
@samilabud, awesome!
I don't think we even need the `shouldResizeToFit` function, we could simply cap the scale at 1. If the scale is above 1, it means the canvas is bigger than the image and we should just set the scale to 1

I think we should proceed with @samilabud's [proposal](https://github.com/Expensify/App/issues/40788#issuecomment-2080002532)
🎀👀🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment] 2024-05-15 18:10
@eVoloshchak any update on the PR review? Thanks!

**Comment by CortneyOfstad** [comment] 2024-05-20 14:55
Merge freeze until Wednesday so PR will be addressed then!

**Comment by CortneyOfstad** [comment] 2024-05-22 14:27
Merge freeze is planned to end today 🤞

**Comment by CortneyOfstad** [comment] 2024-06-07 15:43
@eVoloshchak can you have the checklist as soon as you have a chance? Just want to make sure there is no delays in issuing payments. Thank you!

**Comment by eVoloshchak** [comment] 2024-06-11 19:37
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/31308
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/31308/files#r1635384531
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think a discussion is needed
- Determine if we should create a regression test for this bug.
_Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No_


Regression Test Proposal

1. Open any chat
2. Tap Composer plus icon -> submit expense
3. Submit an expense with [this](https://private-user-images.githubusercontent.com/5216036/331600673-48345ecb-9f37-4f48-af2e-17203671c55c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzQ3MjYsIm5iZiI6MTcxODEzNDQyNiwicGF0aCI6Ii81MjE2MDM2LzMzMTYwMDY3My00ODM0NWVjYi05ZjM3LTRmNDgtYWYyZS0xNzIwMzY3MWM1NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTkzMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIwNDRkNmQ1MDU2YjhhZjEzNTgwODBhMmRiNjE5NDlhZjdhMjdjNmQxOWU0ZjBmNjVkNTZkZDQ0MmIwZjkzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KQYMu40Vg4LfIqWSOfHa6kniXoZrC_N3aznTOGucw8s) receipt image attached
4. Open the expense and tap on the receipt
5. Verify the image is displayed correctly, zoom-in/out and pagination work correctly

Do we agree 👍 or 👎

**Comment by CortneyOfstad** [comment] 2024-06-13 15:47
## Regression Test Link 

https://github.com/Expensify/Expensify/issues/404585

**Comment by CortneyOfstad** [comment] 2024-06-13 15:48
## Payment Summary

@samilabud — paid $250 via Upwork
@eVoloshchak — to be paid $250 via NewDot

**Closed by CortneyOfstad** 2024-06-13 15:48 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-27 22:00
$250 approved for @eVoloshchak
