### ISSUE TITLE
[HOLD for payment 2024-12-20] [$250] iOS - Report - Conversation does not scroll down after deleting an attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52861] opened 2024-11-21 01:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5241542
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app Hybrid
2. Go to the conversation with the history of the message
3. Send an image to the conversation
4. Delete the sent image

## Expected Result:
The conversation should scroll down after deleting the attachment

## Actual Result:
Conversation does not scroll down after deleting an attachment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a4b7bd7e-da1c-479a-8ed3-a8d85f179637

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859628438339074230</li>
        <li>Upwork Job ID: 1859628438339074230</li>
        <li>Last Price Increase: 2024-12-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by bernhardoj** [comment] 2024-11-21 02:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat doesn't scroll after deleting an attachment.

### What is the root cause of that problem?
This happens because `hasNewestReportAction` is false.
https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsView.tsx#L471

`hasNewestReportAction` compares the last action `created` with the report `lastVisibleActionCreated`.
https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsView.tsx#L288

When we delete the attachment, `lastVisibleActionCreated` is updated to the previous action `created`. However, the last action is still the deleted attachment.

### What changes do you think we should make in order to solve the problem?

Currently, we have 2 places of `hasNewestReportAction` logic. If we look at the one in `ReportActionsList`, we can see that the report actions are filtered, so only visible actions will be considered the last action.

https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsList.tsx#L185-L197
https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsList.tsx#L360

So, the `hasNewestReportAction` in `ReportActionList` works correctly, but not in `ReportActionsView`. To fix this, we need to filter out the actions in ReportActionsView too. We can move the filtered actions from ReportActionsList
https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsList.tsx#L185-L197

to ReportActionsView. Then, use it for `hasNewestReportAction`.
https://github.com/Expensify/App/blob/c18812ae3cac59025da0f6c8657750dfcb779a65/src/pages/home/report/ReportActionsView.tsx#L288

```
const visibleReportActions = useMemo(
    () => reportActions.filter(...),
    [reportActions, isOffline],
);

const hasNewestReportAction = visibleReportActions.at(0)?.created === report.lastVisibleActionCreated || visibleReportActions.at(0)?.created === transactionThreadReport?.lastVisibleActionCreated;
```

Then, pass the filtered actions to ReportActionsList.

```
<ReportActionsList
    sortedVisibleReportActions={visibleReportActions}
```

_we can consider moving the hasNewestReportAction from ReportActionsList to ReportActionsView too, so we only have 1 logic for it_

**Comment by Pujan92** [comment] 2024-11-22 09:48
@puneetlath we can close this issue due to a similar [issue](https://github.com/Expensify/App/issues/52471) has been created earlier and @bernhardoj can transfer their proposal there.

**Comment by bernhardoj** [comment] 2024-11-22 11:17
Based on the proposal there, looks like the root cause and solution is different.

**Comment by Pujan92** [comment] 2024-11-22 12:29
RCA of both issues looks similar to me where the issue remains in deriving the `hasNewestReportAction` due to the different values of last report action created and report lastVisibleActionCreated.

**Comment by bernhardoj** [comment] 2024-11-22 16:00
Yes, both issues are because of the wrong value of hasNewestReportAction, but the root cause and solution are still different. I tested my solution and the other issue still persists, so I can't transfer my proposal there because it won't fix that issue.

**Comment by puneetlath** [comment] 2024-11-25 22:04
Do you agree @Pujan92?

**Comment by Pujan92** [comment] 2024-11-27 06:40
@bernhardoj Why the issue appears only for ios and not for android? Bcoz if it is caused by `hasNewestReportAction` then it should have the same effect on other platforms too.

**Comment by bernhardoj** [comment] 2024-11-27 08:18
I think the first issue of this blank space started to happen in https://github.com/Expensify/App/issues/30726 which they fixed in https://github.com/Expensify/App/pull/31670.

This is how the logic looks now which requires `hasNewestReportAction`.
https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/pages/home/report/ReportActionsList.tsx#L372-L381

**Comment by Pujan92** [comment] 2024-12-02 13:02
We can proceed with @bernhardoj's proposal to filter actions to consider visible actions only to derive hasNewestReportAction.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-12-09 05:28
PR is ready

cc: @Pujan92

**Comment by joekaufmanexpensify** [comment] 2024-12-20 15:25
[Asked in slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1734708292130579) so we can get checklist done today.

**Comment by joekaufmanexpensify** [comment] 2024-12-20 17:53
TY! I shared the regression test issue above, so checklist is all set.

**Comment by joekaufmanexpensify** [comment] 2024-12-20 17:54
Good to issue payment. We need to pay: 

- @bernhardoj - $250 for PR via NewDot. 
- @Pujan92 - $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-12-20 17:54
@Pujan92 / @bernhardoj please request payment at your earliest convenience. Closing as this is otherwise all set!

**Closed by joekaufmanexpensify** 2024-12-20 17:54 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-12-21 02:53
Requested in ND.

**Comment by garrettmknight** [comment] 2024-12-21 14:01
$250 approved for @Pujan92

**Comment by JmillsExpensify** [comment] 2024-12-23 12:18
$250 approved for @bernhardoj
