### ISSUE TITLE
[HOLD for payment 2023-12-12] [$500] Start Chat - Invalid red dot briefly appears by closing 'room' tab when there's no prior action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30618] opened 2023-10-30 23:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com and log in to an Expensifail account
2. Click the green plus button.
3. Select "Start chat"
4. Choose ''Room'' tab
5. Click outside the panel, to close it
6. Repeat steps 2-5

## Expected Result:
No red dots should be seen when closing the Room tab

## Actual Result:
An invalid red dot appears briefly when closing the 'room' tab when there is no prior action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/996de290-0055-479e-9cb2-b427f3ea9138

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cccde7c0776bc3a8</li>
        <li>Upwork Job ID: 1719141449851113472</li>
        <li>Last Price Increase: 2023-11-06</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27647427</li>
<li>dukenv0307 | Contributor | 27647429</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-31 07:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Red dot briefly appears when closing create-room page by tapping outside the RHN even when there is no prior action

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/components/Form.js#L356-L359
As you can see above, we set touched state to true and run validator when focused element gets blurred.
When the room tab gets active, the room name input gets focused. When closing the RHN, the name input gets blurred and so the validator runs by the above code.

This is the root cause

### What changes do you think we should make in order to solve the problem?

This issue is related to the current form validation logic. We need to change this.
I suggest not to validate the input entries with no changes. That is, only dirty inputs would be validated.
We are setting touched state below
https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/components/Form.js#L356
https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/components/Form.js#L367-L369
https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/components/Form.js#L373-L375

1. Remove the first 2 code segments
2. We don't need to track the previous focused element. Update the third code to
```
    setTouchedInput(inputKey);
```

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/eb331e18-5feb-4974-9956-cde5b7f806e6


</details>

### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment] 2023-10-31 16:12
@jjcoffee whoo! already a couple proposals! Can you review when you have a moment?

**Comment by yh-0218** [comment] 2023-11-01 12:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Red dot briefly appears when closing create-room page by tapping outside the RHN even when there is no prior action
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/components/Form.js#L358
When `onBlur()`, we do validate.
So when click tab, or during click outside of Modal, we will see error text.
### What changes do you think we should make in order to solve the problem?
We can set `shouldValidateOnBlur=false` for web and desktop.
### What alternative solutions did you explore? (Optional)
We can catch event of click of outside of modal and then disable validate.
https://github.com/Expensify/App/blob/a31933a049b9a9aa4222a4d3edab19b54a4555b7/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.js#L26

**Comment by jjcoffee** [comment] 2023-11-03 15:52
Sorry this one slipped through the cracks, will review on Monday!

**Comment by jjcoffee** [comment] 2023-11-06 16:03
Apologies, will have to be tomorrow that I review this one!

**Comment by jjcoffee** [comment] 2023-11-07 15:45
@yh-0218 We don't want to set `shouldValidateOnBlur` to false for web and desktop; it is deliberate to validate on blur, see [here](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#form-validation-and-error-handling).

@s-alves10 Correct me if I'm wrong but I think your proposal would briefly show the error in the same situation, as long as some text was entered. I don't think this is what we want here.

@Krishna2323 I'm unsure why the event listeners get added in the cleanup of the `useEffect` in your [proposal](https://github.com/Expensify/App/issues/30618#issuecomment-1786439980)?

@dukenv0307 I like the general approach in your [proposal](https://github.com/Expensify/App/issues/30618#issuecomment-1786377878), but I'm not sure how generic a solution it will be since it requires modifying specific inputs to pass through the `event`.

**Comment by s-alves10** [comment] 2023-11-07 18:11
## Proposal
[Updated](https://github.com/Expensify/App/issues/30618#issuecomment-1786612280)

**Comment by jjcoffee** [comment] 2023-11-10 16:31
Sorry wasn't able to get to this today, will review on Monday!

**Comment by jjcoffee** [comment] 2023-11-13 14:34
Reviewing today!

**Comment by jjcoffee** [comment] 2023-11-13 15:46
@dukenv0307's [proposal](https://github.com/Expensify/App/issues/30618#issuecomment-1786377878) LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by situchan** [comment] 2023-11-20 11:29
The [PR](https://github.com/Expensify/App/pull/30679) caused regression

![crash](https://github.com/Expensify/App/assets/108292595/159775c7-7643-444b-aaab-1221222228c8)

**Comment by Julesssss** [comment] 2023-11-20 14:20
PR was reverted [here](https://github.com/Expensify/App/pull/31547), so we'll need an updated PR at some point.

**Comment by Julesssss** [comment] 2023-11-21 13:43
Agree its very minor, but if there's a simple solution I think we should resolve it.

**Comment by abekkala** [comment] 2023-11-22 21:38
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning. 
If something pops up that needs urgent attention please reapply label or ask in slack.

**Comment by abekkala** [comment] 2023-11-30 21:27
### PAYMENTS FOR DEC 04

- Reporter: Applause [no payment]
- Contributor who fixed: @dukenv0307 [$500] [offer](https://www.upwork.com/nx/wm/offer/27647429)
- PR Review: @jjcoffee [$500] [offer](https://www.upwork.com/nx/wm/offer/27647427)

**Comment by jjcoffee** [comment] 2023-12-06 09:55
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this was always the behaviour as far as I can see**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open the app and click the green plus button.
2. Select "Start chat"
3. Choose ''Room'' tab
4. Click outside the panel or the back button and hold
5. Verify that no Red dot appears

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-12-06 09:56
@abekkala Checklist complete! Also note that there was a [regression](https://github.com/Expensify/App/issues/30618#issuecomment-1818874856).

**Comment by abekkala** [comment] 2023-12-06 20:24
Contributor who fixed: @dukenv0307 [$250] [offer](https://www.upwork.com/nx/wm/offer/27647429)
PR Review: @jjcoffee [$250] [offer](https://www.upwork.com/nx/wm/offer/27647427)

50% penalty for regression

**Comment by abekkala** [comment] 2023-12-11 16:55
payments will be sent Tue Dec 12

**Comment by abekkala** [comment] 2023-12-12 15:26
@dukenv0307 &  @jjcoffee - payments sent and contract ended - thank you! 🎉

**Closed by abekkala** 2023-12-12 15:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
