### ISSUE TITLE
BUG: Members showing as "Hidden" when invited to workspace chat

### ISSUE THREAD

**Issue by jamesdeanexpensify** [Expensify/App#52931] opened 2024-11-21 20:54 UTC
## Background
Coming from [this conversation](https://expensify.slack.com/archives/C07HPDRELLD/p1732144487408449), there's **at least** one bug when a member invites other members to their workspace chat. 

## Details
- Expected outcome: When members are invited to a workspace chat, they should not show as `Hidden` in any case (whether they're on the same domain as the inviter or not).
- Actual outcome: I've seen a couple different cases as part of [this thread](https://expensify.slack.com/archives/C07HPDRELLD/p1732144487408449):
  - Members of the same domain invited to a workspace chat show as `Hidden`. This happened to a Fullstory user. I'm not sure what I can share from the clip dude to sensitive customer info, but let me know what you need!
  - Members of a different domain invited to a workspace chat show as `Hidden`. @trjExpensify repro'd this: 
<img width="1462" alt="image" src="https://github.com/user-attachments/assets/f1a77dfc-3c49-4972-a550-46785dfad917">

**Comment by greg-schroeder** [comment] 2024-11-21 23:05
I think this is a `Internal` cause it's Auth

**Comment by arosiclair** [comment] 2024-11-25 21:20
I'll take a look at this. 

@jamesdeanexpensify do you have repro steps? It's not super clear if the hidden problem shows for the inviter/invitee. Also you should use the standard issue template to make these easier to pick up.

**Comment by jamesdeanexpensify** [comment] 2024-11-25 23:50
Hey @arosiclair thanks for picking this up! I've only seen this happen from the **inviter** perspective, I haven't looked at the **invitee** perspective.

So I think the repro steps are:

1. Create a workspace
2. Go to the workspace chat 
3. Click into the title of the workspace chat (where the dropdown arrow is), it should open the RHP
4. Click into `Members`
5. To test both ways: invite a member from the same domain, and then invite a member from a different domain
6. Look at the system messages that generate in the workspace chat
7. One or both system messages should say `invited @Hidden` in them

**Comment by arosiclair** [comment] 2024-11-26 16:54
Okay I only see `Hidden` from the perspective of the member. Also I see that only the admin can invite users to a workspace chat. So repro steps are

1. Log in as a domain admin
2. Create a workspace
3. Invite a domain member
4. Open the workspace chat as both the admin and member in separate windows
5. As the admin, invite a domain member and non-domain members to the workspace chat

Result:

| Member | Admin |
|--------|--------|
| <img width="1197" alt="Screenshot 2024-11-26 at 11 47 48 AM" src="https://github.com/user-attachments/assets/3bd428f3-1b1c-4458-b1bf-73fa67bcadfe"> | <img width="1132" alt="Screenshot 2024-11-26 at 11 47 42 AM" src="https://github.com/user-attachments/assets/15abf8a9-ab1f-4731-89af-4e7467a5ca7b"> | 

After re-opening the chat as the member, the `@mentions` finally display properly.

**Comment by jamesdeanexpensify** [comment] 2024-11-26 17:08
@arosiclair funny enough, I just saw this happen again from the admin perspective while reviewing a Fullstory session. What info do you need that would be most helpful?

**Comment by jamesdeanexpensify** [comment] 2024-11-26 17:15
This scenario was (admin) `balaji.cs@2hearing.com` in their workspace chat `Members` pane inviting `info@2hearing.com`.

**Comment by arosiclair** [comment] 2024-11-26 17:39
It looks like the root of the problem is that the user does not have personal details for the mentioned member so it displays as `@hidden`. We can start pushing personal details with `@mentions`, but I'm not sure that's always correct since not every user is "known" to each other. I'll see if we can just push public details to fix it instead.

**Comment by jamesdeanexpensify** [comment] 2024-11-26 18:38
I think generally if you're typing in someone's email or phone number, you obviously know it and we could at least show that in the system message, right?

**Comment by arosiclair** [comment] 2024-11-27 15:32
I have a fix but it only works for existing users that have a display name. So if you invite a user that doesn't exist yet or a user that doesn't have a display name, it will still display a `@hidden` to the member. I'm looking into a better solution.

**Comment by arosiclair** [comment] 2024-11-27 21:01
Alright I've got a better fix that should push personal details to everyone in private workspace rooms. Tagged Puneet on the PR to get a second look.

**Comment by greg-schroeder** [comment] 2024-12-06 16:28
Work on linked PR continues

**Comment by greg-schroeder** [comment] 2024-12-09 10:17
Same as above

**Comment by trjExpensify** [comment] 2024-12-16 11:44
Just confirming this was the last PR for the issue? https://github.com/Expensify/Auth/pull/13345

**Comment by arosiclair** [comment] 2024-12-16 16:31
Yeah it was this should be fixed now. Closing this out, but reopen in case something else is needed.

**Closed by arosiclair** 2024-12-16 16:31 UTC
Labels: Weekly, Internal, Bug
