### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Workspace -  Selected members unselect on switch from offline to online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28551] opened 2023-09-30 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings > Workspaces > Members
2. Go offline
3. Click on invite button
4. Enter email which is not in list and invite that user
5. From Members screen select that user
6. Go online

## Expected Result:
 Selected should not unselect automatically

## Actual Result:
Selected members unselect automatically

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5e070950-f994-4812-8a24-9f7addecf979

https://github.com/Expensify/App/assets/78819774/b1f5afd5-132e-45a0-8cb7-db97a88bb0cb

https://github.com/Expensify/App/assets/78819774/a405d366-f3fb-4034-ac8e-d4232f3e166c

https://github.com/Expensify/App/assets/78819774/587f6b82-3ffa-4650-a235-08ad0d95f875

https://github.com/Expensify/App/assets/78819774/a763b69d-c153-4f85-ae3f-79072a22fa7e

https://github.com/Expensify/App/assets/78819774/0187c766-9f9d-41e1-9b6b-132b997450ce

https://github.com/Expensify/App/assets/78819774/5ee1675b-d7fa-42ce-99b7-ad96202f521a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695976528390539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment] 2023-10-01 00:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reconnecting to the network removes selected newly added members from the members list

### What is the root cause of that problem?

The newly added members have temporary id that are used to handle the selection in the members list, except that when coming back online that will trigger `command=AddMembersToWorkspace` which will retrieve the correct user IDs 

### What changes do you think we should make in order to solve the problem?
We can start by finding the members with a pending add action using this utility 


```
    const findMembersWithPreviouslyPendingActions = useCallback(() => {

        const membersWithPendingAddActionIds = _.pick(props.policyMembers, (member) => member.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);
        const personalDetailsWithPendingAddActionIds = _.pick(props.personalDetails, (personalDetail, accountID) => membersWithPendingAddActionIds[accountID])
    
    
        return _.map(personalDetailsWithPendingAddActionIds, (personalDetail) => personalDetail.login);
    
    }, [props.personalDetails, props.policyMembers])
```

And then when coming back online, we will try to guess the newly added member real ID using their login which will not change after coming back online, it could be somethinglike this 

```
    useEffect(() => {
        const isReconnecting = prevIsOffline && !props.network.isOffline;

        if(!isReconnecting) {
            return 
        }
        const previouslySelectedEmailsWithPendingActions = findMembersWithPreviouslyPendingActions();

        setMembersWithPreviouslySelectedEmails(_.pick(props.personalDetails, (personalDetail) => _.contains(previouslySelectedEmailsWithPendingActions, personalDetail.login)))
        
    }, [findMembersWithPreviouslyPendingActions, prevIsOffline, props.network.isOffline, props.personalDetails])


    useEffect(() => {
        const emailsOfPreviouslySelectedMembers = _.map(memberWithPreviouslySelectedEmails, (member) => member.login);

        setSelectedEmployees((prevSelected) => {
            const membersToSelect = _.pick(props.personalDetails, (personalDetail) => emailsOfPreviouslySelectedMembers.includes(personalDetail.login) )

            return [...prevSelected, ..._.map(membersToSelect, (member) => Number(member.accountID))]
        })
    }, [memberWithPreviouslySelectedEmails, props.personalDetail, props.personalDetails])
```



### What alternative solutions did you explore? (Optional)

N/A

**Comment by mollfpr** [comment] 2023-10-03 13:44
@abdel-h66 I'm not sure using `personalDetails` to change the selected option is the correct way while we definitely use `policyMembers` to show the members. What is the reason for that?

**Comment by mollfpr** [comment] 2023-10-03 14:27
>t's true that we are using the ids from policyMembers to handle the selection, and that's where the issues lies, basically the ID on the policyMembers collection will change once we go online, making us lose the selection.

I don't understand why using `policyMembers` is the issue, isn't the `accountID` on `personalDetails` changed to when back online?

Also, the `personalDetails` will not change if we remove a member from another device, so that's why listen to `policyMembers` change from the pusher and update the selection accordingly.

---

@ZhenjaHorbach Your solution seems simple enough to solve the issue, but can we map through the previously selected list only if we have members from offline? It seems unnecessary if we add members from existing `personalDetails`.

**Comment by abdel-h66** [comment] 2023-10-03 14:43
The issue with the `policyMembers` collection is that it does not contain enough information, the `personalDetails` contains the `.login` property that I needed to perform the logic :)

**Comment by mollfpr** [comment] 2023-10-04 15:16
We still need to stick with `policyMembers` to update the selection. So the [proposal](https://github.com/Expensify/App/issues/28551#issuecomment-1741883667) from @ZhenjaHorbach is simple enough to solve this issue.

🎀 👀 🎀 C+ reviewed!

**Comment by stephanieelliott** [comment] 2023-10-06 05:17
Hey @Li357 are you working on a PR for this issue?

**Comment by stephanieelliott** [comment] 2023-10-11 05:15
Unassigned and reassigned, @ZhenjaHorbach! Let me know if you still don't get an offer and I can extend one manually.

**Comment by stephanieelliott** [comment] 2023-10-17 01:34
Hi @ZhenjaHorbach I've extended the offer to you manually, the job is [here](https://www.upwork.com/jobs/~0100a927d9b515117f)!

**Comment by mollfpr** [comment] 2023-10-25 14:06
> The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/issues/17166

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18934/files#r1371829488

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
  If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Go to Settings > Workspaces > Members
2. Go offline
3. Click on the invite button
4. Enter an email that is not in the list and invite that user
5. From the Members screen, select that user
6. Go online
7. Verify the selection is remains
8. 👍 or 👎

**Comment by mollfpr** [comment] 2023-10-27 07:28
@stephanieelliott Could you give us the payment summary? Thank you!

**Comment by stephanieelliott** [comment] 2023-10-30 17:15
Summarizing payment on this issue: 

 - Issue reporter: @gadhiyamanan $50, to pay via Upwork (Please accept Upwork offer)
 - Contributor: @ZhenjaHorbach $750 ($500+$750 bonus), to pay via Upwork - PAID 
 - Contributor+: @mollfpr $750 ($500+$750 bonus), please request via NewDot 
 
 Upwork job is [here](https://www.upwork.com/jobs/~0100a927d9b515117f), 50% bonus is included on final payout

**Comment by gadhiyamanan** [comment] 2023-10-30 17:26
@stephanieelliott offer accepted, thanks!

**Comment by stephanieelliott** [comment] 2023-10-30 17:44
All Upwork payments completed!

**Closed** 2023-10-31 21:58 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-01 20:13
$750 payment approved for @mollfpr based on summary above.
