### ISSUE TITLE
[HOLD for payment 2024-08-29] [$250] Composer box- position cursor jumps to begining of message when copying as link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46095] opened 2024-07-24 09:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** negasofonias+7241@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Login to staging new dot
2. Go to any chat with history and type anything in the composer
3. While still in edit mode long press any message from chat and select copy as link
4. observe that the position cursor in composer box jumps to the begining of the content in the composer box

## Expected Result:
Position cursor should stay at the end of the message being typed

## Actual Result:
Position cursor jumps to the front of the content being typed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d146dd79-0741-42ac-a816-123a03a46158

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc75491f30967e9c</li>
        <li>Upwork Job ID: 1816958403568861454</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103552362</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by izarutskaya** [comment] 2024-07-24 09:39
We think this issue might be related to the  #vip-vsb

**Comment by bernhardoj** [comment] 2024-07-24 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor position of the composer go to the start after selecting option from the context menu.

### What is the root cause of that problem?
When we select an option from the context menu such as copy link, we will refocus to the composer.
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L459

`ReportActionComposeFocusManager.focus` will trigger `ReportActionComposeFocusManager.onComposerFocus` callback that is set up in `ComposerWithSuggestions` and `Composer/index.tsx`.
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L589-L595
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/components/Composer/index.tsx#L376-L386

I don't have the context on why we have 2 `onComposerFocus`, but the 2nd `onComposerFocus` is only set-up when the composer is focused and also being used for both main and edit composer.

When the composer (live markdown input) is focused, it will trigger `onFocus` of the live markdown div element (which triggers `handleFocus`) then set the cursor position based on the selection value.
https://github.com/Expensify/react-native-live-markdown/blob/ff55579f673c049a6eb6cdf38ffc223315309b07/src/MarkdownTextInput.web.tsx#L502-L516

However, in our case, focusing after closing the context menu doesn't trigger the `onFocus` event so the cursor position is never set. I found that it's caused by the focus trap. When we try to focus the composer (from onModalHide callback), the modal isn't completely hidden and the focus trap isn't completely deactivated yet.

### What changes do you think we should make in order to solve the problem?

We need to wait for the modal to completely hidden before focusing the composer. If the modal is completely hidden, the children will be unmounted including the focus trap too, so it's guaranteed the focus trap is gone. To do that, we need to focus to the composer using `focusComposerWithDelay` and enable the "delay". The "delay" is not a timeout but rather a promise indicating whether it's ready to focus on the composer or not. (note: the old implementation rely on timeout)
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/libs/focusComposerWithDelay/index.ts#L30-L34

```
ReportActionComposeFocusManager.onComposerFocus(() => {
    ...
    focusComposerWithDelay(textInput.current)(true);
});
```

`isWindowReadyToFocus` is android only, so we can ignore it. The `ComposerFocusManager.isReadyToFocus()` is resolved when the modal is completely hidden. It's resolved from the `onDismiss` callback here.
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/components/Modal/BaseModal.tsx#L232
https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/components/Modal/BaseModal.tsx#L145-L147

This will fix the issue when we previously focus on the composer, open the context menu, and select copy link. However, it's still broken if we open the chat without focusing on the composer, open the context menu, and select copy link. As I mentioned in my proposal, the cursor position is set based on the selection value. The main composer initial selection value is 0, so without ever focusing on the composer, selecting copy link from the context menu will still put the cursor at the start. To fix it, we need to set the initial selection to the value length.

https://github.com/Expensify/App/blob/bf69d5d8bf08ccc741baf8f91fc765b593d2f6b0/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L301

```
const [selection, setSelection] = useState(() => ({start: value.length, end: value.length, positionX: 0, positionY: 0}));
```

**Comment by mallenexpensify** [comment] 2024-07-26 22:07
@c3024 , can you attempt reproduction? I just tried on Safari, iOS, with no luck.

**Comment by mallenexpensify** [comment] 2024-07-26 22:09
Added to #vip-vsb, this is a small bug and a bit of an edge case.  @bernhardoj , do you know if this bug exists elsewhere? Or if this fix would help other instances?

**Comment by bernhardoj** [comment] 2024-07-27 01:30
@mallenexpensify there are 2 fixes in my proposal. The first fix is specific to refocusing logic after selecting an item from the context menu (copy link, mark as unread, etc.). The second one fixes the composer initial selection value which is a broader fix, but I'm not aware of any issue that needs the same fix.

**Comment by c3024** [comment] 2024-07-29 14:20
>can you attempt reproduction?

I could reproduce this. I will update on the proposal.

**Comment by c3024** [comment] 2024-07-30 15:28
@bernhardoj 

>When we try to focus the composer (from onModalHide callback), the modal isn't completely hidden and the focus trap isn't completely deactivated yet.

Is this an issue with `react-native-modal`? The `onModalHide` callback should be called after the modal is completely hidden, right?

**Comment by bernhardoj** [comment] 2024-07-30 15:36
Yes, it's a problem we are facing in https://github.com/Expensify/App/issues/23959 too and in my [proposal there](https://github.com/Expensify/App/issues/23959#issuecomment-1659988961), I already [fix it on the rn-web](https://github.com/necolas/react-native-web/pull/2558), but [stuck on native](https://github.com/Expensify/App/issues/23959#issuecomment-2136669338).

**Comment by mallenexpensify** [comment] 2024-07-31 21:35
@bernhardoj @c3024 , what do you propose is the best next step here? I added `Help Wanted`.

**Comment by bernhardoj** [comment] 2024-08-01 02:20
I think we are waiting for @c3024 review

**Comment by c3024** [comment] 2024-08-01 15:05
>so without ever focusing on the composer, selecting copy link from the context menu will still put the cursor at the start.

How can we select copy link from a comment without ever focusing on the composer? When we open a report the composer gets automatically focused, right?

**Comment by bernhardoj** [comment] 2024-08-02 01:55
> When we open a report the composer gets automatically focused, right?

This only happens if the chat is empty.

**Comment by c3024** [comment] 2024-08-03 07:31
On Desktop Web, even for smaller screens, I see composer gets focused for all cases including the case when there is a comment in the report. Here, focusing composer with delay fix is enough.


https://github.com/user-attachments/assets/945ea5ae-732f-4cb5-9b42-7768d2647272


But for mWeb Safari, I see this 

>This only happens if the chat is empty (on small screen).

but this is not fixed even after making both the changes.


https://github.com/user-attachments/assets/1ce4a069-b3ee-4fb9-a4c6-d9b73f1b00f5

**Comment by bernhardoj** [comment] 2024-08-06 14:20
> On Desktop Web, even for smaller screens, I see composer gets focused for all cases 

By small screen, I mean the mobile device.

> But for mWeb Safari, I see this
> but this is not fixed even after making both the changes.

I just tested and you're right. When I turned off the strict mode, then it works. From my finding, because of the strict mode, when the modal becomes visible, the `onDismiss` is triggered because the `useEffect` is mounted and remounted.
https://github.com/Expensify/App/blob/41e27c99285d21fd3a3e02d9770dfdbab2a96f8f/src/components/Modal/BaseModal.tsx#L258
https://github.com/Expensify/App/blob/41e27c99285d21fd3a3e02d9770dfdbab2a96f8f/src/components/Modal/ModalContent.tsx#L16-L19
https://github.com/Expensify/App/blob/41e27c99285d21fd3a3e02d9770dfdbab2a96f8f/src/components/Modal/BaseModal.tsx#L145-L148

Because of that, `ComposerFocusManager.isReadyToFocus()` is already resolved. I have updated my proposal to fix that.

**Comment by c3024** [comment] 2024-08-07 12:46
Will check and update. Thanks!

**Comment by c3024** [comment] 2024-08-08 06:25
>When I turned off the strict mode, then it works.

I had strict mode off the whole time. 😆 But it did not work for me. 🤷‍♂️ 

I tried with the new changes also but I could not make it work for Safari on my iOS emulator.

Could you share a branch with the changes?

**Comment by bernhardoj** [comment] 2024-08-08 07:30
Here is the test branch: https://github.com/bernhardoj/Expensify/tree/fix/46095-composer-selection-is-at-start

**Comment by c3024** [comment] 2024-08-14 06:29
@bernhardoj 's [proposal here](https://github.com/Expensify/App/issues/46095#issuecomment-2248239994) looks good to me!

🎀 👀 🎀 C+ Reviewed

**Comment by mallenexpensify** [comment] 2024-08-15 23:15
@MariaHCD , 👀 on [the above proposal](https://github.com/Expensify/App/issues/46095#issuecomment-2248239994) plz. 
Thx

**Comment by MariaHCD** [comment] 2024-08-16 12:58
@bernhardoj 's proposal looks good to me 👍🏼

**Comment by bernhardoj** [comment] 2024-08-16 15:14
There is another case I found in which the issue is still happening and the focus doesn't wait until the modal is closed (even with setTimeout). I'll continue the investigation and open the PR tomorrow.

**Comment by bernhardoj** [comment] 2024-08-17 14:00
PR is ready

cc: @c3024

**Comment by mallenexpensify** [comment] 2024-08-30 23:52
Contributor: @bernhardoj due $250 via NewDot   
Contributor+: @c3024 paid $250 via Upwork

@c3024 plz complete the BZ checklist. thx

**Comment by bernhardoj** [comment] 2024-08-31 01:35
Requested in ND.

**Comment by c3024** [comment] 2024-08-31 13:26
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #40128 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/e572f6dff82408ce0bfb0571bc8d8bba9f2c4642#r146059726
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have been identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal
1. Open a chat with existing messages.
2. Type any text in the composer.
3. (This step is for mWeb only) Go back and reopen the chat again. The composer shouldn't be auto-focused.
4. Long-press/right-click on any existing message.
5. Select "Copy link".
6. Verify the composer is focused with the cursor at the end of the text in the composer.

**Comment by JmillsExpensify** [comment] 2024-09-02 20:17
$250 approved for @bernhardoj

**Comment by mallenexpensify** [comment] 2024-09-03 00:29
Thanks @c3024 , test case created
- https://github.com/Expensify/Expensify/issues/425308

**Closed by mallenexpensify** 2024-09-03 00:29 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
