### ISSUE TITLE
[$500]  Invite members - blank row is displayed when removing user in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37235] opened 2024-02-26 22:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to 'Invite members' page of a workspace
2. Invite a user
3. Apply offline mode
4. Removed the user

## Expected Result:
There shouldn't be any blank rows

## Actual Result:
There is a blank row after removing the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3a19f2de-45e6-4fb6-a0fd-3cd7e441594a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b21db9a428272553</li>
        <li>Upwork Job ID: 1762247192499994624</li>
        <li>Last Price Increase: 2024-02-26</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-26 22:45
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by luacmartins** [comment] 2024-02-26 23:01
This is a dupe of https://github.com/Expensify/App/issues/37109. Gonna close since it's known and we're working on fixing it when we implement the remove functionality in Simplified Collect.

**Closed by luacmartins** 2024-02-26 23:01 UTC
Labels: External, Engineering, Hourly, Help Wanted
