### ISSUE TITLE
[HOLD for payment 2022-12-20] While resizing, a white window background is shown

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#13085] opened 2022-11-28 12:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Resize the web browser window while in dark mode

## Expected Result:
- No obvious white background colour should be displayed

## Actual Result:
- An obvious white background colour is displayed

https://user-images.githubusercontent.com/10736861/203777318-e21cb0bf-acef-4c3b-bc91-b6346e8fd7fd.mov

## Platform:

Where is this issue occurring?

- Web ✅ 

**Version Number:** 
**Reproducible in staging?:** True
**Reproducible in production?:** True soon
**Email or phone of affected tester (no customers):** all

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019db029d99d78265b</li>
        <li>Upwork Job ID: 1606391966285721600</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by s77rt** [comment] 2022-11-28 12:58
I think @shawnborton suggestion will fix this bug.
However if the theme can be dynamically changed an event listener will be required to update the body CSS

**Comment by adelekennedy** [comment] 2022-12-02 00:51
@Julesssss this looks like a dupe of this issue [here](https://github.com/Expensify/App/issues/13219) from [this comment ](https://github.com/Expensify/App/issues/13219#issuecomment-1334253924) it sounds like @grgia is already working on this - should we close this issue?

**Comment by Julesssss** [comment] 2022-12-02 10:49
Good spot, but based I think they might be separate issues. Let's keep them separate until the solutions come in

**Comment by grgia** [comment] 2022-12-02 17:56
Are you working on this one @Julesssss ? I have a somewhat hacky fix that I'm looking for a better solution for https://github.com/Expensify/App/pull/13278

**Comment by Julesssss** [comment] 2022-12-05 10:38
Hey @grgia, nah I kept myself assigned in case this was made external, but feel free to  take it over if you're working on a fix.

**Comment by grgia** [comment] 2022-12-08 18:29
Whoops, in review!

**Comment by Santhosh-Sellavel** [comment] 2022-12-08 19:26
Please assign me this issue to track payment for this [PR](https://github.com/Expensify/App/pull/13278) Review Thanks!

**Comment by adelekennedy** [comment] 2022-12-08 23:51
assigned @Santhosh-Sellavel for [PR review payment!](https://github.com/Expensify/App/pull/13278#issuecomment-1341538508)

**Comment by francoisl** [comment] 2022-12-09 18:27
The QA team sent this video, seems like the desktop app still shows a white background. Might be specific to Windows though. Any ideas or thoughts if we should make this a blocker?

https://user-images.githubusercontent.com/43995119/206763022-e411fbf7-301c-4f46-941b-bd91c9d3e798.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-12-09 18:54
@francoisl 
On Mac, I don't get a white screen when I try to resize the browser or dragging, but I get to try to adjust the screen size in inspect mode. I am not sure we might be able to fix this. 

### On Staging
https://user-images.githubusercontent.com/85645967/206771849-c6d055b5-9958-41a4-abee-1fcd6b3ab7c5.mov

### On Local, unable to reproduce at all
https://user-images.githubusercontent.com/85645967/206773992-e8b69fd0-dd4f-41df-b653-f324e28325c5.mov

cc: @grgia

**Comment by francoisl** [comment] 2022-12-09 19:11
Yeah same here, which makes me think it's somehow specific to Windows. Anyway, we can look into this later, let's not block the deploy for this.

**Comment by Julesssss** [comment] 2022-12-14 10:46
No need for regression test, this was not a regression but an improvement.

**Comment by Santhosh-Sellavel** [comment] 2022-12-21 23:03
@grgia or @Julesssss can you add a bz here

**Comment by grgia** [comment] 2022-12-22 00:42
Dragging you back @adelekennedy !!

**Comment by Santhosh-Sellavel** [comment] 2022-12-23 16:43
@grgia seems @adelekennedy is on OOO can you assign someone else, thanks!

**Comment by mallenexpensify** [comment] 2022-12-23 20:56
@Santhosh-Sellavel , can you accept plz https://www.upwork.com/jobs/~019db029d99d78265b

**Comment by Santhosh-Sellavel** [comment] 2022-12-26 18:28
@mallenexpensify Done!

**Comment by mallenexpensify** [comment] 2022-12-27 01:40
Paid @Santhosh-Sellavel $1000.  Closing cuz I don't think we need regression test steps adds per @Julesssss 👎 above

**Closed by mallenexpensify** 2022-12-27 01:40 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
