### ISSUE TITLE
[$500] Chat – Unable to choose Start/Finish points in Distance request when navigate via change

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33056] opened 2023-12-14 11:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. On an account that is an employee of a workspace (not the admin)
2. Click on FAB
3. Select "Request Money"
4. Click on the "Distance" tab
5. Change the URL to https://staging.new.expensify.com/request/new/participants
6. Verify that you're redirected back to the "Distance" tab
7. Click on "Start"
8. Enter a destination - E,g "45n N Beach Rd, FL"

## Expected Result:
The mini map adjusts the location to show the start point.

## Actual Result:
Nothing happenes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8ccbe1c3-06ad-48fc-b673-9e9e51a73cfd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c43a52e8ac1910a9</li>
        <li>Upwork Job ID: 1735266958280769536</li>
        <li>Last Price Increase: 2023-12-28</li>
    </ul>
</details>

**Comment by LahiruAriyasinghe** [comment] 2023-12-14 15:04
### **Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
The mini map not adjusts the location to show the start point.

**What is the root cause of that problem?**
Because the selected location details not add and update the mini map.



**What changes do you think we should make in order to solve the problem?**
We should update the mini-map with the following location details. 
"location" : {
   "lat" : 37.2089572,
   "lng" : -93.29229889999999
}

And then we can add a pin to the start and end points. 
// Add a marker to the map
new mapboxgl.Marker()
    .setLngLat([-93.29229889999999, 37.2089572])
    .addTo(map);

Also like that, we can pin the end point and get the distance.


**What alternative solutions did you explore? (Optional)**
N/A

**Comment by LahiruAriyasinghe** [comment] 2023-12-14 15:08
Contributor details
Your Expensify account email: lahiru.ariyasinghe69@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d88cb6c66f4d9e09

**Comment by akinwale** [comment] 2023-12-19 04:04
> We can close this as per [#33132 (comment)](https://github.com/Expensify/App/issues/33132#issuecomment-1858058720)

@anmurali Based on the comment in the thread, this issue can be closed, since it involves a URL that will be deprecated as part of the Request Money flow refactor.

**Comment by anmurali** [comment] 2024-01-02 23:09
Closing per https://github.com/Expensify/App/issues/33056#issuecomment-1862082296

**Closed by anmurali** 2024-01-02 23:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
