### ISSUE TITLE
[$250] Public room - Deleted messages aren't actually removed from the room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39350] opened 2024-04-01 11:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466218&group_by=cases:section_id&group_id=229066&group_order=asc
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in and navigate to https://staging.new.expensify.com/r/2652281908731856
2. Open https://staging.new.expensify.com/r/2652281908731856
in different device without logging in
3. Logged in account: Write a few messages in the room
4. Logged in account: Delete some of the messages
5. Refresh the page (both accounts)

## Expected Result:
Deleted messages should be removed.

## Actual Result:
Deleted messages aren't actually removed from the room. The messages re-appear if you reload the page or log out and log in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a4f5e90f-9dc0-41a8-b382-950e708054e2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01653ed9b332f192f1</li>
        <li>Upwork Job ID: 1776237445145571328</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-01 11:49
We think this issue might be related to the #vip-vsb.

**Comment by sonialiap** [comment] 2024-04-05 13:16
Adding external

**Comment by jdumont0201** [comment] 2024-04-05 20:38
Happens as well in your space with self dm

**Comment by kaushiktd** [comment] 2024-04-08 08:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Public room - Deleted messages aren't actually removed from the room

### What is the root cause of that problem?

When trying to remove existing message from report, It will check it's parent thred. If Parent is not existing, will always call for below actions on [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Report.ts#L1262). This will cause the error.

### What changes do you think we should make in order to solve the problem?

Implement a new variable to check report has a child report exist or not.
This variable will be set to true if childReportID is not null or undefined.

Add a new const variable [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Report.ts#L1252):

```
const hasChildReport = reportAction.childReportID !== null && reportAction.childReportID !== undefined;
```

also check the condition along with isDeletedParentAction [here](https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/libs/actions/Report.ts#L1260):

```
(!hasChildReport || isDeletedParentAction)
```
 
### Video:

https://drive.google.com/file/d/1zN7Rbi_UKSYR5007fFLKkKq5EMq3cdtN/view?usp=sharing

**Comment by sonialiap** [comment] 2024-04-18 10:16
Still waiting for https://github.com/Expensify/App/pull/40059 to be merged

**Comment by mvtglobally** [comment] 2024-04-18 15:56
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment] 2024-04-22 10:05
Thanks Shubham, closing

**Closed by sonialiap** 2024-04-22 10:05 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
