### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Chat -  No details tooltip for assignee name on task title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29175] opened 2023-10-10 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Krishna2323 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696778672195119

## Action Performed:
1. Open any task report
2. Hover on assignee name in title section
3. Observe there is no user details

## Expected Result:
There should be a user details tooltip when we hover on task title

## Actual Result:
There is no user details tooltip when we hover on task title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/427e29d0-95fc-4960-a12d-b33cf53cb775

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/29b51b45-a426-4934-931b-45c0c01e1023

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e82f506a63979657</li>
        <li>Upwork Job ID: 1711714321879621632</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27226207</li>
<li>Krishna2323 | Contributor | 27226211</li>
<li>Krishna2323 | Reporter | 27226213</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-10 12:05
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
No details tooltip for assignee name on task title.

### What is the root cause of that problem?
We are not wrapping title text with `UserDetailsTooltip`.

### What changes do you think we should make in order to solve the problem?

### Option 1
We should add one more prop to `MenuItem` called `shouldShowTitleTooltip` or something like that and also pass data for it and based on that we will wrap title with `UserDetailsTooltip`.

### Option 2
We can also use data passed in the avatar icon and show the `UserDetailsTooltip` on title based on that but I don't think that is the best way to do that.

### Result

**Comment by jjcoffee** [comment] 2023-10-11 09:59
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/29175#issuecomment-1755237546) LGTM - I think option 1 makes the most sense. 

I think we may want to avoid showing the tooltip when hovering over the assignee's name whilst we're on the `Confirm Task` screen, and only show it in the task detail view. cc @Expensify/design for thoughts.

**Comment by jjcoffee** [comment] 2023-10-11 10:00
Forgot to add... :smile: 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by shawnborton** [comment] 2023-10-11 12:56
Curious why we are treating this like a bug? This seems like polish that either @thienlnam or @jasperhuangg forgot to add to their PRs when they worked on this feature, so perhaps we just have one of them follow up? 

Either way, I think we'd show the tooltip everywhere (including confirm screen) to stay consistent with what we do elsewhere?

**Comment by thienlnam** [comment] 2023-10-12 17:10
Yeah this just looks like an improvement we can add to be consistent everywhere - and agree with showing the tooltip everywhere

**Comment by peterdbarkerUK** [comment] 2023-10-13 13:26
Alrighty, @thienlnam @jasperhuangg do either of you want to pick this up?

**Comment by thienlnam** [comment] 2023-10-13 23:28
I think it's best if we continue with this externally since my main focus is on the wave stuff (and it's not really a bug created by a previous PR) - I'll manage this as a CME but think we should keep this as external

**Comment by jjcoffee** [comment] 2023-10-16 08:23
@thienlnam Makes sense to me! I think we're then good to hire @Krishna2323 (option 1 in his [proposal](https://github.com/Expensify/App/issues/29175#issuecomment-1755237546)).

**Comment by thienlnam** [comment] 2023-10-16 18:22
I can't seem to assign external people who haven't participated in the convo - @Krishna2323 can you comment in this issue?

**Comment by jjcoffee** [comment] 2023-10-20 13:29
PR is in active review, we're nearly there!

**Comment by jjcoffee** [comment] 2023-10-24 08:44
Just a quick update - PR is C+ approved, just waiting for @thienlnam's approval and then we're good!

**Comment by jjcoffee** [comment] 2023-11-06 16:10
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this was never implemented**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes - easy enough to test**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to FAB -> Assign Task
2. Enter any title and tap Next
3. Assign to any user and verify that the user tooltip appears when you hover over the name
4. Confirm the task and verify that in the task report page the user tooltip also shows when you hover over the assignee

Do we agree 👍 or 👎

**Comment by peterdbarkerUK** [comment] 2023-11-07 17:14
Payment Summary:

@jjcoffee $500 (Reviewer)
@Krishna2323 $500 (Contributor)
@Krishna2323 $50 (Reporter)

**Comment by peterdbarkerUK** [comment] 2023-11-07 21:07
[TR Request](https://github.com/Expensify/Expensify/issues/334250) is up

**Closed by peterdbarkerUK** 2023-11-07 21:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
