### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Web - Split Scan - Console error shows up when clicking Split on empty split action menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32809] opened 2023-12-11 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace chat > + > Split bill > Scan.
3. Create a split scan request.
4. Click on the spit preview.
5. Click Split.

## Expected Result:
No console error shows up.

## Actual Result:
Console error shows up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c4dba984-a2bc-4358-aca2-8419fd815f0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fa32ba034ba77de</li>
        <li>Upwork Job ID: 1734211176724713472</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28035520</li>
<li>bernhardoj | Contributor | 28035524</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-12-11 14:08
Most likely related to the refactor https://github.com/Expensify/App/pull/28618

**Comment by abzokhattab** [comment] 2023-12-11 14:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Err occur when clicking on empty split action menu
### What is the root cause of that problem?
we are not safely accessting the trasnactionID:
https://github.com/Expensify/App/blob/243f932043089c625b0f6be4dea43925177b96c2/src/libs/actions/IOU.js#L1690
### What changes do you think we should make in order to solve the problem?

use lodash get 
```
_get(updatedTransaction,"trasnactionID")
```

**Comment by mountiny** [comment] 2023-12-11 14:29
@abzokhattab that solution is not enough as there are other properties required which cause console error

**Comment by shubham1206agra** [comment] 2023-12-11 14:30
@mountiny Please remove `Help wanted` label here

**Comment by mountiny** [comment] 2023-12-11 14:31
We should show error on the form if the Amount and merchant have not been updated

**Comment by shubham1206agra** [comment] 2023-12-11 14:31
I think disabling the button will be more correct

**Comment by mountiny** [comment] 2023-12-11 14:33
ah yeah, whatever our `Forms.md` dictate

**Comment by shubham1206agra** [comment] 2023-12-11 14:38
Sorry, we should show error according to `Forms.md`

**Comment by tgolen** [comment] 2023-12-11 14:56
Thank you @bernhardoj, that looks like a correct fix. Would you mind putting that into proposal form?

**Comment by tgolen** [comment] 2023-12-11 15:28
Thanks, that looks great. Assigning to you now.

**Comment by puneetlath** [comment] 2023-12-19 20:27
@shubham1206agra friendly reminder on the checklist so that we can pay this out tomorrow.

**Comment by shubham1206agra** [comment] 2023-12-20 14:56
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1432819995
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as we have already caught this in deploy testing
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@puneetlath] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by shubham1206agra** [comment] 2023-12-20 16:14
Done

**Comment by puneetlath** [comment] 2023-12-21 17:29
All paid. Thanks everyone!

**Closed by puneetlath** 2023-12-21 17:29 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
