### ISSUE TITLE
[$250] IOS - Build against iOS 15 in ~1 month or the app will be auto-rejected cc

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8460] opened 2022-04-04 04:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Check IOS app SDK Version 

## Expected Result:
IOS 15+ SDK should be used for the Expensify app 

## Actual Result:
IOS 14.5 SDK is used for the Expensify app 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.44-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="667" alt="Screen Shot 2022-03-24 at 9 46 46 AM" src="https://user-images.githubusercontent.com/43995119/161472375-1924737e-5479-4f65-b25f-cd8f1fd4d877.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648137460915479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-04-07 19:39
Moved this to external.

**Comment by jliexpensify** [comment] 2022-04-08 04:26
Posted:

- Internal: https://www.upwork.com/ab/applicants/1512285496911982592/job-details
- External: https://www.upwork.com/jobs/~01fe244a40dd2dfb79

**Comment by Julesssss** [comment] 2022-04-08 09:36
Awaiting proposals.

**Comment by dharmik** [comment] 2022-04-08 10:30
Proposal & Information @Julesssss 
Main context we have to release iOS application with iOS 15 SDKs

**Official Information**
[App Store submission requirement starts April 25
](https://developer.apple.com/news/?id=2t1chhp3)

- From who ever's machine we are releasing iOS application we need to verify is Xcode version is 13 or later.
  ==> open xcode ==> Top menu item click on xcode ==> Click on About Xcode 

- Version must be 13 or later as I attached in screenshot.

<img width="532" alt="Screen Shot 2022-04-08 at 3 31 08 PM" src="https://user-images.githubusercontent.com/1510175/162413787-5e8b1bc3-f3d1-4b08-8b8c-8115e06a0d54.png">

- If after updating Xcode and if we want to check iOS SDK version open terminal and write command `xcodebuild -showsdks `

<img width="567" alt="Screen Shot 2022-04-08 at 3 52 25 PM" src="https://user-images.githubusercontent.com/1510175/162417511-925c6626-c399-4ba9-9e3e-491a8226a433.png">

**Outcome:**
If we generate release ios ipa file will above configuratation this email/message **ITMS-90725: SDK Version Issue** will not come.

I have Xcode version is 13 or later with latest SDK so let me know if we want to upload ipa file from my machine.

**Comment by parasharrajat** [comment] 2022-04-08 10:34
@dharmik I think you misunderstood the issue. Here we wants someone to update the target SDK version on the plist file and corresponding configurations and set up the project so that it will successfully built. 

Let's me your proposal for doing that. The deployment will be taken care internally.

**Comment by dharmik** [comment] 2022-04-08 10:57
@parasharrajat Are areyou talking about to change iOS Deployment Target?
<img width="867" alt="Screen Shot 2022-04-08 at 4 27 05 PM" src="https://user-images.githubusercontent.com/1510175/162422521-675207cb-dd26-4548-967b-6a61cee09203.png">

If you need someone to do, I will do that.

**Comment by parasharrajat** [comment] 2022-04-08 11:01
Yup, I think that is the one. I don't much about iOS but that should be it.

**Comment by dharmik** [comment] 2022-04-08 11:10
@parasharrajat 
https://user-images.githubusercontent.com/43995119/161472375-1924737e-5479-4f65-b25f-cd8f1fd4d877.png

We are planning to resolve above information message which came in email while recently we release application for that as per my proposal we have to stay updated or build application with minimum SDK which is iOS 15 and iOS 15 will be support in Xcode 13 or later so if we generate a build from this configuration it will not give us that email again.

CC @Julesssss

**Comment by parasharrajat** [comment] 2022-04-08 11:16
Sounds good. Let's go with that. We have to inform everyone to upgrade their Xcode version. For some of them, it will be hard to do as it may require an OS upgrade. 

cc: @Julesssss 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by jliexpensify** [comment] 2022-04-14 21:55
Bump @Julesssss for approval! 

I'll be re-assigning this as I am OOO until the 30th.

**Comment by jliexpensify** [comment] 2022-04-14 21:58
Kadie is also OOO for the next week, so re-assigning again.

Job created here:

Internal: https://www.upwork.com/ab/applicants/1512285496911982592/job-details
External: https://www.upwork.com/jobs/~01fe244a40dd2dfb79

Just awaiting confirmation from Jules.

**Comment by dharmik** [comment] 2022-04-16 04:48
@jliexpensify I shared one [proposal](https://github.com/Expensify/App/issues/8460#issuecomment-1092718039) and it looks fine as per comment [issuecomment](https://github.com/Expensify/App/issues/8460#issuecomment-1092754905)

Let me know something more information need from my side.

**Comment by parasharrajat** [comment] 2022-04-18 07:33
cc: @Julesssss :arrow_up:

**Comment by Julesssss** [comment] 2022-04-19 10:36
Sorry, I was stuck in the hospital. Back now.

**Comment by arielgreen** [comment] 2022-04-19 18:45
Hired via Upwork

**Comment by dharmik** [comment] 2022-04-19 19:02
@arielgreen Accepted. The proposal it self a solution.
CC @Julesssss @parasharrajat

**Comment by parasharrajat** [comment] 2022-04-19 20:39
Ok. Awaiting your PR.

**Comment by dharmik** [comment] 2022-04-19 20:41
@parasharrajat there is no code change so how to share PR?

**Comment by parasharrajat** [comment] 2022-04-19 20:44
Oh. Dah... I was hoping that changing the config will change the config files which need to be committed to the repo.

**Comment by dharmik** [comment] 2022-04-19 20:47
@parasharrajat no changes in code , need to follow proposal and it will resolved with updated xcode. I face this 2 weeks ago after updation it resolved.

**Comment by AndrewGable** [comment] 2022-04-19 20:50
I thought there should be a code change?

**Comment by parasharrajat** [comment] 2022-04-19 20:50
You mentioned something [here](https://github.com/Expensify/App/issues/8460#issuecomment-1092739486). What were you proposing to do if there is nothing to be changed from you?

**Comment by dharmik** [comment] 2022-04-19 20:54
No, update the xcode.

https://github.com/Expensify/App/issues/8460#issuecomment-1092718039

**Comment by AndrewGable** [comment] 2022-04-19 20:57
You can update the XCode version here: https://github.com/Expensify/App/blob/main/.github/workflows/platformDeploy.yml#L13

We do not release the app manually via XCode. So please update your proposal with a code change.

**Comment by parasharrajat** [comment] 2022-04-19 21:04
Yup. Also, in the PR attach videos for successful build on Xcode 13.

**Comment by dharmik** [comment] 2022-04-20 18:58
> Yup. Also, in the PR attach videos for successful build on Xcode 13.

Do you want me to generate successful build from pipeline or from Xcode?

**Comment by dharmik** [comment] 2022-04-20 19:02
> You can update the XCode version here: https://github.com/Expensify/App/blob/main/.github/workflows/platformDeploy.yml#L13
> 
> We do not release the app manually via XCode. So please update your proposal with a code change.

Proposal Updated.

**Comment by parasharrajat** [comment] 2022-04-20 19:41
> Do you want me to generate a successful build from the pipeline or from Xcode?

From Xcode.

**Comment by AndrewGable** [comment] 2022-04-20 20:06
Yes, version of XCode built locally must match the code change.

**Comment by dharmik** [comment] 2022-04-20 21:25
@AndrewGable @parasharrajat Is it what we are expecting in video?

https://user-images.githubusercontent.com/1510175/164325382-25a0ad7a-73d6-456f-8774-ab23eaa51db8.mov

Mine current xcode version:
<img width="543" alt="Screen Shot 2022-04-21 at 2 54 31 AM" src="https://user-images.githubusercontent.com/1510175/164325469-b06d4c9b-6219-4ec3-948f-b435634eb8d2.png">

**Comment by AndrewGable** [comment] 2022-04-20 22:27
You are going to have to show in video that your changes did not introduce any regressions to the iOS app.

**Comment by dharmik** [comment] 2022-04-21 19:36
@parasharrajat PR created.
https://github.com/Expensify/App/pull/8738

**Comment by AndrewGable** [comment] 2022-04-21 20:48
FYI - Once this is deployed to staging, I can verify that the email is or is not sent via apple.

**Comment by dharmik** [comment] 2022-04-21 21:02
@AndrewGable Yes.

**Comment by Julesssss** [comment] 2022-04-22 09:36
Okay, thanks for the PR. 

I can't believe I'm saying this, but compiling the app from the newer XCode/iOS sdk worked first time, I was expecting this to be a nightmare to test with all sorts of local compile issues 😆

**Comment by dharmik** [comment] 2022-04-22 09:42
@Julesssss If all well can we merge that PR?

**Comment by Julesssss** [comment] 2022-04-22 09:44
Yep, just running a few more tests. I used to have two XCode installations (one for the old app, one for the new one), so I'm just confirming all is good after switching to a single app.

**Comment by Julesssss** [comment] 2022-04-22 11:00
Merged.

**Comment by Julesssss** [comment] 2022-05-03 09:23
Awaiting deploy

**Comment by dharmik** [comment] 2022-05-03 09:41
@Julesssss Is there anything pending to test for this issue?

**Comment by Julesssss** [comment] 2022-05-03 09:44
For now we're awaiting deployment to production

**Comment by dharmik** [comment] 2022-05-03 09:53
@Julesssss I am new so after this only we have to completed project from upwork?

**Comment by Julesssss** [comment] 2022-05-03 13:11
Oh, sorry. Yes, once the issue is deployed to production there will be an automated message here in the issue to let us know you should be paid.

**Comment by arielgreen** [comment] 2022-05-11 21:00
Still awaiting deploy

**Comment by arielgreen** [comment] 2022-05-19 00:25
@dharmik paid
@parasharrajat hired for PR review in Upwork, once you accept I'll remit payment

**Comment by arielgreen** [comment] 2022-05-27 01:27
Paid.

**Closed by arielgreen** 2022-05-27 01:27 UTC
Labels: Exported, External, Engineering, Weekly, Improvement
