### ISSUE TITLE
[Xero] Import page error message RBR isn't always displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42268] opened 2024-05-16 10:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #41917
**Version Number:** 1.4.74-1
**Reproducible in staging?:** yes
**Reproducible in production?:** new feature 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Preconditions: 

1. Log in with an expensifail account
2. Have a Collect workspace with accounting enabled and Xero connected. 
3. Simulate failing network requests is tuned on in the troubleshoot tab.
4. Navigate to workspace settings - Accounting - Import turn on or off "Tracking categories" "Re-bill customers" and "Taxes"
## Expected Result:
RBR should always show.
## Actual Result:
Xero Import page error message RBR isn't always displayed. I was only able to get the RBR on iOS but only for one of the three import options.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/4e0c3310-0e31-4db6-8939-1d5477ff1f0e

![Bug6482451_1715843808811!IMG_0456](https://github.com/Expensify/App/assets/38435837/d0aa5daf-e2a3-4db9-8c90-f58e713d3bc4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-05-16 10:58
@Julesssss FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Julesssss** [comment] 2024-05-16 10:59
My initial thought is that this shouldn't block the deploy: 
- It is a new feature, which wasn't working prior to the changes being merged
- It is an edge case that is unlikely to be triggered by any user

**Comment by muttmuure** [comment] 2024-05-16 11:01
agreed

**Comment by Julesssss** [comment] 2024-05-16 11:01
Removing the label. This was only. just [implemented](https://github.com/Expensify/App/pull/41917) and isn't a regression

**Comment by trjExpensify** [comment] 2024-05-16 11:10
Yep, Xero is behind a beta as well. 👍

**Comment by SzymczakJ** [comment] 2024-05-16 14:06
I suppose this is not a bug and it is caused by the way "Simulate failing network requests" tool is working. When having this "failing requests" on, the app is retrying requests multiple times in random time intervals. That means we need to wait for every request to give us an error message(and sometimes it can last few minutes), **so probably RBR indicator isn't always displaying because the user hasn't waited enough time.**
@m-natarajan can you test it once more? Turn on or off "Tracking categories" "Re-bill customers" and "Taxes" and wait for about 3-5 minutes, then all RBR indicators should be there.
To support my theory I post picture of import page all in RBR indicators, it took me 5 minutes for all of them to appear 😃 
<img width="427" alt="Screenshot 2024-05-16 at 15 39 19" src="https://github.com/Expensify/App/assets/88395093/b598b5ac-2e4c-4e48-a51d-ae1facea2708">

**Comment by Julesssss** [comment] 2024-05-20 13:14
Hmm, yeah, it isn't clear whether simulate failing requests are the bug or just a way to reproduce... if the the former we can close

**Comment by trjExpensify** [comment] 2024-05-20 14:16
If we want @m-natarajan / Applause to retest, let's make sure the label gets added.

**Comment by muttmuure** [comment] 2024-05-22 19:14
Waiiting for applause to retest

**Comment by Julesssss** [comment] 2024-05-29 15:53
Same as above

**Comment by Julesssss** [comment] 2024-05-30 12:58
Awaiting the weekly retest

**Comment by trjExpensify** [comment] 2024-06-10 09:20
@m-natarajan did you get to retesting this?

**Comment by Julesssss** [comment] 2024-06-10 09:58
Shared in QA [here](https://expensify.slack.com/archives/C9YU7BX5M/p1718013451561309) asking for a test

**Comment by muttmuure** [comment] 2024-06-19 13:24
Waiting for retest

**Comment by Julesssss** [comment] 2024-06-28 13:48
I [asked](https://expensify.slack.com/archives/C9YU7BX5M/p1719582513705619) for a retest today in #qa

**Comment by kbecciv** [comment] 2024-07-01 15:31
Issue is reproducible

https://github.com/Expensify/App/assets/93399543/a70d2f65-545d-4160-8d0a-ac2441ba86e7

**Comment by Julesssss** [comment] 2024-07-01 15:44
> **Actual Result**
> I was only able to get the RBR on iOS but only for one of the three import options.

After re-reading @SzymczakJ's [comment](https://github.com/Expensify/App/issues/42268#issuecomment-2115349203) here I realise that this isn't a bug and we needed to retest with a 5 minute delay, instead of following the original steps.

Rather than doing that again though, I say we just close. Reopen if you disagree.

**Closed by Julesssss** 2024-07-01 15:44 UTC
Labels: Engineering, Weekly, Bug, retest-weekly
