### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Update Task Report System Messages and LHN Display for Consistency

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#24601] opened 2023-08-15 20:21 UTC
From https://expensify.slack.com/archives/C01GTK53T8Q/p1691602405412179

Currently in group chats the LHN preview when a task is created looks like:

![image](https://github.com/Expensify/App/assets/5487802/48cbd5d0-c89f-4b25-8f49-ab898fc1c234)

which is confusing with the double colon. We should remove the one before the task title.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01240ad1a87681ff41</li>
        <li>Upwork Job ID: 1692247492479631360</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 26769074</li>
</ul></li>
    </ul>
</details>

**Comment by dangrous** [comment] 2023-08-15 20:43
@kevinksullivan I'm gonna handle this internally, it's very quick (and also requires some backend stuff)

**Comment by dangrous** [comment] 2023-08-16 21:22
[Confirming expected behavior](https://expensify.slack.com/archives/C01GTK53T8Q/p1692220769074059?thread_ts=1691602405.412179&cid=C01GTK53T8Q) for the additional task messages (cancelled, completed, reopened). Will go from there.

(also note to self, changes have to be made in the App as well as in Auth)

**Comment by dangrous** [comment] 2023-08-18 16:38
Holding since discussion continues in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692220769074059?thread_ts=1691602405.412179&cid=C01GTK53T8Q) on where we should fix/adjust things

**Comment by dangrous** [comment] 2023-08-21 19:08
Discussion continues, I'll bump

**Comment by dangrous** [comment] 2023-08-28 16:47
Bumping the discussion

**Comment by dangrous** [comment] 2023-08-30 19:20
Still figuring out a direction in Slack.

**Comment by JmillsExpensify** [comment] 2023-08-30 20:41
Alright summarizing the long discussion in Slack, this ended up turning into a bit of spring cleaning for task reports. Here's where we landed. 

In the task itself, the possible system messages are:
 - `marked as complete`
 - `marked as incomplete`
 - `assigned to %displayName%`

There is no `created this task` system message, as no reports in NewDot use that.  Similarly for the assigned task case, we don’t use `you` anywhere in NewDot history. We use `%displayName%` or `primaryLogin` instead.

Parent report (DM, room, etc.) in LHN:
 - First line: `%parentReportName%`
 - Second line: `%displayName%: task for %taskTitle%`

Task report in LHN:
 - First line: `%taskTitle%`
 - Second line: `No history yet`

Similarly the task report buttons in English should be:
 - `Mark as complete`
 - `Mark as incomplete`

No changes needed for Spanish. These already use the equivalent language.

**Comment by dangrous** [comment] 2023-09-05 16:33
I have not been prioritizing this, since more important stuff abounds. We've got the direction [here](https://github.com/Expensify/App/issues/24601#issuecomment-1699809924). This issue will require both front and backend changes (i.e. optimistic data and then data from the actual server), maybe we can take proposals for the front end and I can handle the back end? What do you think, @eVoloshchak?

**Comment by eVoloshchak** [comment] 2023-09-10 14:51
>  maybe we can take proposals for the front end and I can handle the back end? What do you think, @eVoloshchak?

@dangrous, this approach looks good to me 
We deviated quite a bit from the initial issue, I think the title and the description could be changed so the contributors aren't confused

**Comment by eVoloshchak** [comment] 2023-09-10 14:51
Accepting proposals!

**Comment by dangrous** [comment] 2023-09-12 19:14
@rayane-djouah let us know when your proposal is ready for review given the updated information!

**Comment by dangrous** [comment] 2023-09-13 16:20
great! @eVoloshchak can you take a look at the latest proposal and let us know what you think? Thank you!

**Comment by dangrous** [comment] 2023-09-19 04:30
Added `External` though it's actually both (I'll have to grab the internal side after the external stuff is done)

**Comment by dangrous** [comment] 2023-09-20 03:28
Oops so sorry, I thought I did! Doing so now.

**Comment by dangrous** [comment] 2023-09-28 06:55
PR has been merged! I will see if I can knock out the matching backend changes quickly, though it may be tomorrow.

**Comment by dangrous** [comment] 2023-09-29 13:01
Backend PR is up for review!

One question, I think for @JmillsExpensify - We previously had a (I guess not surfaced in the front end) system message for deleting a task, of `"deleted task: " + taskTitle;`. I updated that to just `deleted`, to match `marked as complete` and `marked as incomplete`. Does that feel right to you?

**Comment by eVoloshchak** [comment] 2023-10-11 09:41
- The PR that introduced the bug has been identified. Link to the PR: this isn't a regression per se, just an update to system messages for tasks
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. N/A

**Comment by JmillsExpensify** [comment] 2023-10-11 15:05
> Backend PR is up for review!
> 
> One question, I think for @JmillsExpensify - We previously had a (I guess not surfaced in the front end) system message for deleting a task, of `"deleted task: " + taskTitle;`. I updated that to just `deleted`, to match `marked as complete` and `marked as incomplete`. Does that feel right to you?

Missed this, but yeah that feels right.

**Comment by JmillsExpensify** [comment] 2023-10-11 15:05
Will get NewDot payments processed as soon as I have a payment summary.

**Comment by kevinksullivan** [comment] 2023-10-11 15:07
Payment summary

Contributor: @rayane-djouah $500
C+: @eVoloshchak $500 (in NewDot)

**Comment by JmillsExpensify** [comment] 2023-10-11 15:08
$500 payment approved for @eVoloshchak based on BZ symmary.

**Comment by kevinksullivan** [comment] 2023-10-13 23:18
all set

**Comment by thienlnam** [comment] 2023-10-16 17:57
Since we're updating these system messages we'll need to update the existing regression tests so QA doesn't create issues from these changes - could we make sure that happens before closing this out please? cc @kevinksullivan

**Closed** 2023-10-17 16:21 UTC
Labels: External, Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
