### ISSUE TITLE
[$500] Profile - The page shakes before opening the help page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33809] opened 2023-12-31 09:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Navigate to profile - help

## Expected Result:
There shouldn't be any shaking or flashing.

## Actual Result:
The page shakes before opening the help page on Android mWeb. There is a white flash before opening on web.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows 10/ Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/55cd7e34-6bfa-48ff-a38c-ea90412da0c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141d01c5abeec6c5e</li>
        <li>Upwork Job ID: 1741391006869880832</li>
        <li>Last Price Increase: 2024-01-07</li>
    </ul>
</details>

**Comment by FlorianWueest** [comment] 2023-12-31 09:59
Not reproducible on my side. Tested with Android & Win/Chrome.

**Comment by bilalsahid929** [comment] 2023-12-31 10:46
I have checked the issue the issue can be observed when browsing on web browser on android.
The issue is persisted not only when "help" link is clicked but also when we click on "Go to Expensify Classic" link. I have cloned the repo and checked the code for sidebar links. The issue is regarding memoisation.  The issue is with those links which are open in to a new tab.
To my understanding the issue is persisted on all devices but we are able to observe only on slow devices. 
issue:-> when we click on the link that is supposed to be open on a new tab. This is when the issue occur. The action method we are using is asyncOpenURL.
"getDefaultMenuItems" menu funtion i s memoised and in the dependency array we have passed the "waitForNavigate" method as dependency. when we click on the link  this triggers the rerender in the "getDefaultMenuItems" that is we see a screen shaking.

**Comment by bilalsahid929** [comment] 2023-12-31 11:26
Contributor details
Expensify account email: bilalshahid929@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01caff8deb28ca2f53

**Comment by bilalsahid929** [comment] 2023-12-31 12:33
Proposal

Issue:-> The page shakes when we click on the link that is supposed to be open on a new tab. The issue persists not only when the "help" link is clicked but also when we click on the "Go to Expensify Classic" link.

cause:-> The sidebar links are memoised. while the action is performed in the background regarding opening a new tab there is no wrapper around the action method. like below 
other action methods
  action: waitForNavigate(() => {
                    Navigation.navigate(ROUTES.SETTINGS_PROFILE);
                }),
method for help link
   action: () => {
                    Link.openExternalLink(CONST.NEWHELP_URL);
                },            
                
Solution:-> Write a custom wrapper to await the render update till the new tab is opened.

**Comment by brunovjk** [comment] 2024-01-02 20:20
Hi @bilalsahid929 👋
Just a quick heads-up – when submitting proposals, could you please ensure they follow the proposal template?
You can find it [here](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md).

**Comment by sakluger** [comment] 2024-01-04 23:10
@bilalsahid929 could you please update your proposal to use the correct format? Seems like you're one of the only people who can reproduce the bug so far!

**Comment by sakluger** [comment] 2024-01-08 20:21
This is a pretty minor bug, barely noticeable, and most people can't reproduce it, so I'm going to close the issue for focus.

**Closed by sakluger** 2024-01-08 20:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
