### ISSUE TITLE
 Help - Concierge icon in the LHN of help.expensify.com page links to localhost

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29033] opened 2023-10-06 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to help.expensify.com
2. Click on the Concierge icon at the bottom of the page

## Expected Result:
User is redirected to Concierge chat on New Dot

## Actual Result:
User is redirected to http://localhost:8082/concierge

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.79-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a6d865a2-df3f-40a0-ac53-10ca7ccc90dc

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-10-09 14:25
Reproducible

**Comment by jayeshmangwani** [comment] 2023-10-09 14:30
This seems to be an internal issue, the wrong Jekyll environment passed at the time of the release build

**Comment by sonialiap** [comment] 2023-10-10 06:14
Closing in favor of https://github.com/Expensify/App/issues/29154

**Closed by sonialiap** 2023-10-10 06:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
