### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Remove NewRequestAmountPage.js and copy any changes since Nov 27 into IOURequestStepAmount.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34614] opened 2024-01-16 20:54 UTC
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `NewRequestAmountPage`
**New Component** `IOURequestStepAmount`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01400d372c60004a9e</li>
        <li>Upwork Job ID: 1747632925329993728</li>
        <li>Last Price Increase: 2024-01-24</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28128915</li>
<li>dukenv0307 | Contributor | 28135067</li>
</ul></li>
    </ul>
</details>

**Comment by njmulsqb** [comment] 2024-01-17 01:40
I would love to take this!

**Comment by MahmudjonToraqulov** [comment] 2024-01-17 14:54
I would love to take this!

**Comment by FitseTLT** [comment] 2024-01-17 14:59
Would love to clean up this

**Comment by lschurr** [comment] 2024-01-18 16:07
@sobitneupane could you review this one?

**Comment by lschurr** [comment] 2024-01-22 17:11
Bump @sobitneupane

**Comment by sobitneupane** [comment] 2024-01-24 02:50
@lschurr I won't be able to review proposals before weekend. Please feel free to reassign the issue if it is urgent.

**Comment by brunovjk** [comment] 2024-01-24 22:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
This belongs to [Wave 5 cleanup](https://github.com/Expensify/App/issues/29107)
Phase 2 is all about removing the original components and any of the duplicated efforts.

### What is the root cause of that problem?
Replace `MoneyRequestAmountPage` and `EditRequestAmountPage` to `IOURequestStepAmount`. **This new component will handle both the create and edit flow based on `action` param**.

### What changes do you think we should make in order to solve the problem?

> Look at the history of the Old Component
> If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes

1. Checked and [there is no commits](https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestAmountPage.js?since=2023-11-27&until=2024-01-23) made to the `MoneyRequestAmountPage` component since 27-Nov. `IOURequestStepAmount` is already updated with those changes. This way there will be **no need to arrange any changes** from `MoneyRequestAmountPage` to be transferred to `IOURequestStepAmount`

> Replace all uses of the Old Component with the New Component
> Remove all traces of Old Component

2. There is no use of the component other than `ModalStackNavigators`. `MoneyRequestAmountPage` is already removed from `main`, we need only to remove from Navigators:
https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L94

3. The new component uses `STEP_AMOUNT` and has it own [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L395), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L125) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L316-L320) already configured, we must **remove** `AMOUNT` from [`linkingConfig`](https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L425), [`SCREENS`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/SCREENS.ts#L139) and [`ROUTES`](https://github.com/Expensify/App/blob/f56f1809846822f35d3bca8762a302086df1b774/src/ROUTES.ts#L257-L260)

> Be sure to update all routes and navigation to use the new :action param (instead of being hard-coded with "create")

4. Update [Type navigation](https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/libs/Navigation/types.ts#L183)  according to new `route and getRoute`.
to
    ```
        [SCREENS.MONEY_REQUEST.STEP_AMOUNT]: {
            iouType: string;
            transactionID: string;
            reportID: string;
            backTo: string;
        };
    ```
5. Update [route and getRoute](https://github.com/Expensify/App/blob/0706c8c1a8914fa5ef4a7a05630e793ff691fd0a/src/ROUTES.ts#L316-L320) to use the new :action param.
    ```
        MONEY_REQUEST_STEP_AMOUNT: {
            route: ':action/:iouType/amount/:transactionID/:reportID?',
            getRoute: (action: ValueOf<typeof CONST.IOU.ACTION>, iouType: ValueOf<typeof CONST.IOU.TYPE>, transactionID: string, reportID: string, backTo = '') =>
                getUrlWithBackToParam(`${action}/${iouType}/amount/${transactionID}/${reportID}`, backTo),
        }, 
    ```
6.  Add `CONST.IOU.ACTION.CREATE` at [MoneyTemporaryForRefactorRequestConfirmationList](https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L679)  to follow `ROUTES.MONEY_REQUEST_STEP_AMOUNT` changes.
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_AMOUNT.getRoute(CONST.IOU.ACTION.CREATE, iouType, transaction.transactionID, reportID, Navigation.getActiveRouteWithoutParams()));

    ```
> Update any logic like isEditing to use the new action param from the route

7. Update [MoneyRequestView](https://github.com/Expensify/App/blob/872eb17903f18f9a99d69abe6e45d6e736c70c77/src/components/ReportActionItem/MoneyRequestView.js#L275) to follow `ROUTES.MONEY_REQUEST_STEP_AMOUNT` changes.
    ```
    Navigation.navigate(ROUTES.MONEY_REQUEST_STEP_AMOUNT.getRoute(CONST.IOU.ACTION.EDIT, CONST.IOU.TYPE.REQUEST, transaction.transactionID, report.reportID, Navigation.getActiveRouteWithoutParams()))
    ```
8. Add an `isDraft` variable to control if we are CREATing or EDITing. Update [IOURequestStepAmount.js](https://github.com/Expensify/App/blob/main/src/pages/iou/request/step/IOURequestStepAmount.js) to accommoamount the CREATE and EDIT of the Category field. We need to use `IOU.updateMoneyRequestAmount` as was done in [`EditRequestPage`](https://github.com/Expensify/App/blob/6cfdd6f47fe5f932b70f440104accffea586ef60/src/pages/EditRequestPage.js#L123)
    ```
        route: {
            params: {iouType, action, reportID, transactionID, backTo, currency: selectedCurrency},
        },
    ...
    const isDraft = action === CONST.IOU.ACTION.CREATE;
    ...
        Navigation.goBack(isDraft && backTo || ROUTES.HOME);
    ...
    const navigateToNextPage = ({amount}) => {
        IOU.setMoneyRequestAmount_temporaryForRefactor(transactionID, amountInSmallestCurrencyUnits, currency || CONST.CURRENCY.USD, isDraft);
        if(!isDraft && amountInSmallestCurrencyUnits !== transaction.amount){
            IOU.updateMoneyRequestAmountAndCurrency(transactionID, reportID, currency || CONST.CURRENCY.USD, amountInSmallestCurrencyUnits);
        }
        navigateBack();
    };
    ```

9. Update [setMoneyRequestAmount_temporaryForRefactor](https://github.com/Expensify/App/blob/0efabc2b40fe845b13faa94ec508a6693167ede9/src/libs/actions/IOU.js#L181-L183)  to use `isDraft` :
    ```
    ...
     * @param {Boolean} isDraft - Indicates whether it's a draft or not
     */
    function setMoneyRequestAmount_temporaryForRefactor(transactionID, created, isDraft) {
        const key = isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION;
        Onyx.merge(`${key}${transactionID}`, {amount, currency});
    }
    ```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2024-01-25 10:26
I have context in this epic, I can take over this issue as C+ contributor

**Comment by lschurr** [comment] 2024-01-29 16:02
Just assigned to you @DylanDylann - are we still waiting for proposals?

**Comment by DylanDylann** [comment] 2024-01-29 16:03
We have some porposals, I will review soon

**Comment by DylanDylann** [comment] 2024-01-30 06:10
In creating flow, we use `IOURequestStepAmount` as a child of `IOURequestStartPage` so we need to update the route for this case. I don't see any proposal cover this case

**Comment by DylanDylann** [comment] 2024-01-30 07:19
As discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1705999852089949), we need to use IOURequestStepAmount in the create/edit flow for both request money and split bill flow

@dukenv0307's proposal is the first one that covers all cases. Let's go with his proposal

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-02-05 15:44
@dukenv0307 How about the PR process?

**Comment by DylanDylann** [comment] 2024-02-23 03:05
Hold https://github.com/Expensify/App/pull/35455

**Comment by DylanDylann** [comment] 2024-03-18 09:59
@lschurr Let's remove hold label

@dukenv0307 Please update PR

**Comment by DylanDylann** [comment] 2024-04-02 01:49
@lschurr The PR is merged, please help to add weekly label

**Comment by lschurr** [comment] 2024-04-12 16:13
@dukenv0307 @DylanDylann - Do we need a regression test here?

**Comment by DylanDylann** [comment] 2024-04-15 01:58
@lschurr This is a refactoring task, we don't need regression here.

**Comment by lschurr** [comment] 2024-04-15 15:36
Payment summary:

- Contributor: @dukenv0307 $250 (paid in Upwork)
- Contributor+: @DylanDylann $250 (paid in Upwork)

**Closed by lschurr** 2024-04-15 15:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
