### ISSUE TITLE
[LOW] [Groups] [$500] Room - Inconsistency in behaviour while adding VOIP number as contact via start chat&room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33932] opened 2024-01-04 09:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[tl,dr from below](https://github.com/Expensify/App/issues/33932#issuecomment-1951973609): Expensify, users shouldn't be allowed to use VoIP phone numbers. In one part of the app, we (inconsistently) allow that. We classified it as a backend issue, and it's waiting to be picked up by an internal engineer.

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap on header---members----Invite
4. Paste the VOIP number (+18183305299)
5. Tap invite
6. Note user can add VOIP number as contact
7. Navigate to LHN
8. Tap fab---Start chat
9. Paste the VOIP number (+18183305299)
10. Select the VOIP number (+18183305299) from the list
11. Note error message is displayed

## Expected Result:
User must be not be allowed to add a landline or VOIP contact to a room or other places in the app.  The error message that should be returned is the same as if you try to invite them to a chat via steps 7-11 above. "The provided phone number belongs to a landline or VoIP, please use your email address instead."

## Actual Result:
In room, Voip number allowed to add as contact but in start chat adding voip number showing error.Inconsistency in behaviour displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dc656da1-24d7-4059-8131-3d6f460edbaa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01907badd5c1783209</li>
        <li>Upwork Job ID: 1742844313960140800</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-01-09 00:21
Updated the Expected behaviour in the OP

## Expected Result:
> User must be not be allowed to add a landline or VOIP contact to a room or other places in the app.  The error message that should be returned is the same as if you try to invite them to a chat via steps 7-11 above. "The provided phone number belongs to a landline or VoIP, please use your email address instead."

@brunovjk @eVoloshchak and others, let's make sure we're testing any other ways/places a user can be added to ensure we surface the "The provided phone number belongs to a landline or VoIP, please use your email address instead." error everywhere.  I want to fix all instances at once and not manage multiple GH issues.

**Comment by brunovjk** [comment] 2024-01-12 10:14
@mallenexpensify Sorry for the delay, I will update my proposal soon.

**Comment by mallenexpensify** [comment] 2024-01-15 22:58
d'oh, tagged wrong person and not you @0xmiroslav , can you please review my comment above and the proposals? Thx

**Comment by brunovjk** [comment] 2024-01-16 11:19
## Proposal
Updating

> error everywhere. I want to fix all instances at once and not manage multiple GH issues.

Investigating. I have a Updated proposal in few hours.

**Comment by brunovjk** [comment] 2024-01-17 17:09
## Proposal
Updated

**Comment by brunovjk** [comment] 2024-01-17 17:11
## Proposal
[Updated](https://github.com/Expensify/App/issues/33932#issuecomment-1877625053)

**Comment by brunovjk** [comment] 2024-01-18 19:10
> Can you add some context behind it?

Although, '_I think on top of the proposal, they should implement some sort of check in the front-end for whether the provided phone number is valid before creating an_' report https://github.com/Expensify/App/issues/24519#issuecomment-1686742822
I understood that '_these validations are meant to happen on the backend since we can't easily verify if a phone number is VOIP (from its format, we can check but it's not dependable)_' https://github.com/Expensify/App/issues/24519#issuecomment-1687078956

This is what I found on **Github**+**Slack**, maybe there is a better discussion on the subject internally, I don't know, but I understand the difficulty of trusting these validators on the frontend, and I wonder about the feasibility of standardizing responses when validation for an **invalid number is true**.

**Comment by mallenexpensify** [comment] 2024-01-24 03:33
@cubuspl42 reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by cubuspl42** [comment] 2024-01-24 10:16
@brunovjk Do I understand correctly that you're suggesting no frontend changes, but to handle this on the backend instead?

**Comment by brunovjk** [comment] 2024-01-24 11:27
@cubuspl42 Yes :) Does that make sense? I'm new here, still trying to understand how it all works.

**Comment by cubuspl42** [comment] 2024-01-24 11:47
It makes sense. Unfortunately, in such a case, the issue might have to be fixed internally without external compensation.

🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-01-24 11:47
@danieldoglas Would you take a look?

**Comment by brunovjk** [comment] 2024-01-24 11:53
Very good, thank you @cubuspl42 :D

**Comment by danieldoglas** [comment] 2024-01-24 18:32
I agree with you. @mallenexpensify can you please turn this into an internal issue? I think this could probably be a part of vip-split.

**Comment by mallenexpensify** [comment] 2024-01-27 17:02
Moved to `Internal`, @danieldoglas what's your reasoning for #vip-split? I want to post in that room and could use some 'ammo'/words to _sell_ it.  Thx

**Comment by mallenexpensify** [comment] 2024-01-31 01:54
@danieldoglas can you comment on the above when you have a min?
> what's your reasoning for #vip-split? I want to post in that room and could use some 'ammo'/words to sell it. Thx

**Comment by danieldoglas** [comment] 2024-01-31 19:42
Oh my bad, didn't see that comment before.

#vip-split is where I'm seeing the focus on 1:1 and group chats being created, as well as universal chat. So I think that's a good place where we should focus on limiting voip numbers.

**Comment by mallenexpensify** [comment] 2024-02-02 02:14
Thanks @danieldoglas , checking in #vip-split 

https://expensify.slack.com/archives/C05RECHFBEW/p1706839984516219

**Comment by mallenexpensify** [comment] 2024-02-07 00:12
Added to VIP Split project, bumping to weekly.

**Comment by lanitochka17** [comment] 2024-02-15 21:41
Is this the same  issue or need a new one?
Using Voip number invited contact to WS, the contact disappears but red dot shown near members


https://github.com/Expensify/App/assets/78819774/7b6b4b46-9b35-4309-863d-7b462e71f885

**Comment by mallenexpensify** [comment] 2024-02-18 19:46
Thx @lanitochka17 I'm unsure. @cubuspl42 what do you think?  My hunch is... 
1. If it's related, if we fix this issue, then the one above wouldn't/shouldn't happen, right. 
2. If yes to #1, then we can either remember to double check the flow once done here or create a new issue and put it on hold, pending this one.

**Comment by cubuspl42** [comment] 2024-02-19 08:51
Summing up the issue, as the post history is long:

In Expensify, users shouldn't be allowed to use VoIP phone numbers. In one part of the app, we (inconsistently) allow that. We classified it as a backend issue, and it's waiting to be picked up by an internal engineer.

**Comment by cubuspl42** [comment] 2024-02-19 08:53
About the concern raised by @lanitochka17:

I say let's create a new issue and put it on hold on this one. There are multiple differing aspects (different routes, different user-observable symptoms), and I think this will be less prone to being forgotten this way.

**Comment by lanitochka17** [comment] 2024-02-19 16:19
@cubuspl42 Hello
https://github.com/Expensify/App/issues/36806

**Comment by mallenexpensify** [comment] 2024-02-20 23:58
Thanks @lanitochka17 and @cubuspl42

**Comment by mallenexpensify** [comment] 2024-03-04 18:47
[Posted in #vip-split](https://expensify.slack.com/archives/C05RECHFBEW/p1709578000501549)

[and #engineering 
](https://expensify.slack.com/archives/C03SSAQ7P/p1709577994173929)

**Comment by tgolen** [comment] 2024-03-04 21:10
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41129) has been created
- It covers both the room invite and the task assignee flows

### Next Steps
- Wait for reviews
- Respond to reviews
- Merge and deploy

#### ETA
- Merged tomorrow Mar 5
- Deployed to production Mar 7

**Comment by tgolen** [comment] 2024-03-06 15:57
# Daily Update
- The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/41129) failed QA and still wasn't working as expected

### Next Steps
- I'll create a new PR to fix the feature and get it to pass QA this time

#### ETA
- PR created today Mar 6
- PR merged tomorrow Mar 7
- PR deployed to staging Mar 8

**Comment by tgolen** [comment] 2024-03-08 17:31
# Daily Update
- The [second PR attempt](https://github.com/Expensify/Web-Expensify/pull/41156) was merged to production and passed QA

### Next Steps
- Close this issue

**Closed by tgolen** 2024-03-08 17:31 UTC
Labels: Reviewing, Weekly, Internal, Bug
