### ISSUE TITLE
[$500] Android-Thread-User B never received thread messages from User A& deleting parent not reflected

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27515] opened 2023-09-15 11:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
User B - mweb, User A- Android in 2 devices
1. Go to http://staging.new.expensify.com/
2. Tap Fab
3. Tap assign task
4. Tap enter title
5. Tap next
6. Tap share somewhere and share it to user A (you will need to already messaged them one in order to see them for assignment)
7. Tap confirm task
8. Open User A Android account
9. Tap on bold task share by user B above
10. Tap side arrow next to task name
11. Tap assignee
12. Assign task to yourself, note it is reflected in User B task page
13. Complete the task by checking tick, note it is reflected in User B task page
14. Re-open the task by unchecking tick, note it is reflected in User B task page
15. Complete the task by checking tick, note it is reflected in User B task page
16. Send a message, note it is reflected in User B task page
17. Long press the sent message, and select reply in thread
18. In thread page, send 2 messages and note it is not reflected in User B task page
19. Tap on header to navigate task page
20. Tap 2 replies
21. Long press the parent message and select delete and confirm delete it.
22. Tap on header
23. Like in thread page, [deleted message]plus 2 replies shown
24. Verify user B task page whether displays the same

## Expected Result:
In user B task page, thread messages must be shown/delivered. When user A deleted parent message, complete conversation [deleted message]plus 2 replies must be shown in User B task page.

## Actual Result:
In user B task page, thread messages are not shown/delivered. When user A deleted parent message, complete conversation disappeared in User B task page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c9b3ed2c-701a-45f2-921d-13cc8834b360

https://github.com/Expensify/App/assets/115492554/703d0ada-530e-4c05-8f4f-eb99ad5aa049

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01033f439f718010d9</li>
        <li>Upwork Job ID: 1702714716621684736</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-09-15 16:05
I don't have a method to test this with two users on Android - @situchan would you be able to test this to see if it's still happening? 

Sorry to ask, I'm just not sure how else to test through [Browserstack](https://app-live.browserstack.com/#os=android&os_version=12.0&device=Samsung+Galaxy+S22+Ultra&zoom_to_fit=true&full_screen=true&speed=1) with two devices (incognito mode isn't working).

**Comment by Christinadobrzyn** [comment] 2023-09-18 21:26
Okay, I found another Android to test on. 

I can reproduce these steps but I have no idea what is the issue. I think the issue is that when the parent message is deleted, it should delete the thread as well?

**Comment by Christinadobrzyn** [comment] 2023-09-19 21:59
bumping https://expensify.slack.com/archives/C9YU7BX5M/p1695072837008099

**Comment by izarutskaya** [comment] 2023-09-20 10:29
Hello @Christinadobrzyn ! 
I can reproduce this issue on one device - SG M 52/Android 13/Chrome
Build v1.3.72-5
For me messages will appear if you return to the main chat with the user and then return to this task.

https://github.com/Expensify/App/assets/115492554/62bbfbc4-7f25-42b6-9aad-929518b1bc9e

**Comment by Christinadobrzyn** [comment] 2023-09-20 19:55
Thanks @izarutskaya - to confirm have the steps in the original post been updated with the steps to reproduce this?

**Comment by Christinadobrzyn** [comment] 2023-09-25 15:44
I can reproduce what we see but the issue is that the threaded messages are going to a chat thread and not the IOU. So I think making this change would be a feature request and not a bug. Going to close this for now and we can reopen it if needed.

**Closed by Christinadobrzyn** 2023-09-25 15:44 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Overdue, Bug
