### ISSUE TITLE
Admin Room - An error message appears after assigning a task as an Auditor

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51253] opened 2024-10-22 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** aatweq+22222223@gmail.com
**Issue reported by:**Applause - Internal Team

## Action Performed:
Preconditions: You need two accounts to perform this scenario
1. Loggin on macOS app
2. Create a workspace as an admin
3. Invite a member and give the Auditor role
4. Loggin with the Auditor role account
6. Go to Admin room
7. Assign Task, create it

## Expected Result:
After the user Assign Task he/she is able to create the task

## Actual Result:
After the user Assign Task and creates it an error message is shown making access to the task impossible

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/3e0b96a0-b085-4549-9dcf-9bf6f5dfc2b7

<img width="1728" alt="Bug6636128_1729268843431!creating_a_task_throws_anerror_message_as_an_auditor" src="https://github.com/user-attachments/assets/e496c12b-a4eb-46d2-acb6-3ef9c4299454">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-22 13:40
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-10-22 14:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin Room - An error message appears after assigning a task as an Auditor

### What is the root cause of that problem?
We don't return false if it is an auditor and the report is policyAdmin room here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1334

### What changes do you think we should make in order to solve the problem?

We should add the code 
```
if (isAdminRoom(report) && PolicyUtils.isPolicyAuditor(getPolicy(report?.policyID))) {
        return false;
    }
    
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-10-22 14:26
Edited by **proposal-police**: This proposal was **edited** at 2024-10-22 14:17:15 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin Room - An error message appears after assigning a task as an Auditor
 I also see that in announce room auditor can't even comment let alone create a task

### What is the root cause of that problem?
1.
We don't return false if it is an auditor and the report is policyAdmin room here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1334
2. 
We are allowing an exception for auditor permissions to permit writing in report here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1488
### What changes do you think we should make in order to solve the problem?

1.
We should add the code 
```

    if (isAdminRoom(report) && isAuditor(report)) {
        return false;
    }

    
```
We don't have a code to bypass creation of tasks from markdown here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/pages/home/report/ReportFooter.tsx#L174-L178
We need to add a check that the user can create a task and if it can't handle it as a normal message 
```
if (ReportUtils.canCreateTaskInReport(report)) {
                const isTaskCreated = handleCreateTask(text);
                if (isTaskCreated) {
                    return;
                }
            }
            Report.addComment(report.reportID, text);
```
2. We need to make sure that the report is not announce room for the auditor exception we have, so change it to 
```
    if (Array.isArray(report?.permissions) && report?.permissions.length > 0 && (!report?.permissions?.includes(CONST.REPORT.PERMISSIONS.AUDITOR) || isAnnounceRoom(report))) {

```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-10-22 16:09
Edited by **proposal-police**: This proposal was **edited** at 2024-10-22 14:17:15 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin Room - An error message appears after assigning a task as an Auditor
 I also see that in announce room auditor can't even comment let alone create a task

### What is the root cause of that problem?
1.
We don't return false if it is an auditor and the report is policyAdmin room here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1334
2. 
We are allowing an exception for auditor permissions to permit writing in report here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1488
### What changes do you think we should make in order to solve the problem?

1.
We should add the code 
```

    if (isAdminRoom(report) && isAuditor(report)) {
        return false;
    }

    
```
We don't have a code to bypass creation of tasks from markdown here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/pages/home/report/ReportFooter.tsx#L174-L178
We need to add a check that the user can create a task and if it can't handle it as a normal message 
```
if (ReportUtils.canCreateTaskInReport(report)) {
                const isTaskCreated = handleCreateTask(text);
                if (isTaskCreated) {
                    return;
                }
            }
            Report.addComment(report.reportID, text);
```
2. We need to make sure that the report is not announce room for the auditor exception we have, so change it to 
```
    if (Array.isArray(report?.permissions) && report?.permissions.length > 0 && (!report?.permissions?.includes(CONST.REPORT.PERMISSIONS.AUDITOR) || isAnnounceRoom(report))) {

```
and change
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1495
``` 
   if (isAuditor(report) && !isAnnounceRoom(report)) {
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-10-22 16:53
Edited by **proposal-police**: This proposal was **edited** at 2024-10-22 14:17:15 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin Room - An error message appears after assigning a task as an Auditor
 I also see that in announce room auditor can't even comment let alone create a task

### What is the root cause of that problem?
1.
We don't return false if it is an auditor and the report is policyAdmin room here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1334
2. we are returning true for auditor in isAllowedToComment here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1494-L1496
### What changes do you think we should make in order to solve the problem?

1.
We should add the code 
```

    if (isAdminRoom(report) && isAuditor(report)) {
        return false;
    }

    
```
We don't have a code to bypass creation of tasks from markdown here
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/pages/home/report/ReportFooter.tsx#L174-L178
We need to add a check that the user can create a task and if it can't handle it as a normal message 
```
if (ReportUtils.canCreateTaskInReport(report)) {
                const isTaskCreated = handleCreateTask(text);
                if (isTaskCreated) {
                    return;
                }
            }
            Report.addComment(report.reportID, text);
```
2. We need to make sure that the report is not announce room for the auditor exception we have, so change it to 
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1494-L1496

change
https://github.com/Expensify/App/blob/ca942cad72f5b310087a6778832ffcf0181b8c01/src/libs/ReportUtils.ts#L1495
``` 
function isAllowedToComment(report: OnyxEntry<Report>): boolean {
    if (isAuditor(report) && !isAnnounceRoom(report)) {
        return true;
```
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-10-22 21:41
As a auditor, creating a task in admin room will throw an error. I think it is BE bug.

**Comment by VictoriaExpensify** [comment] 2024-10-28 02:04
Hey @truph01 - can you please help me (a non-tech person) out with a bit more context about why this is a BE issue?

**Comment by FitseTLT** [comment] 2024-10-28 10:16
@VictoriaExpensify You have to ask internally if an auditor is allowed to create tasks in admin room. I personally interpreted the fact that the BE is returning error as it is not allowed so proposed to remove that option from front-end. Still, we have to have a confirmation from BE engineer. 👍

**Comment by VictoriaExpensify** [comment] 2024-11-01 00:28
Ohh I'm so sorry, I misunderstood this issue to be that the auditor couldn't be assigned a task.

Hmm I agree @FitseTLT , I don't think an auditor should be able to create or assign a task. But we probably want the error about this to be a lot more clear. Or, better yet, remove the option to create one completely. 

Let me raise with the team

**Comment by VictoriaExpensify** [comment] 2024-11-04 09:02
Still discussing ^^

**Comment by VictoriaExpensify** [comment] 2024-11-04 10:56
Since we are not focussing on Tasks at the moment, we will close this out unless reported as a genuine customer issue

**Closed by VictoriaExpensify** 2024-11-04 10:56 UTC
Labels: Daily, Bug
