### ISSUE TITLE
[$500] Emoji - When a reaction of one tone is removed, all reactions are removed simultaneously

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33533] opened 2023-12-23 02:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in with any account
3. Navigate to any conversation with the correspondence history
4. Add a :+1: reaction to any message
5. Change to a different default skin tone emoji
6. Add a :+1: reaction to the same message from step 4
7. Repeat steps 5-6 several times with non-repeating skin tones
8. Click on the added reactions

## Expected Result:
If it is possible to add the same reactions with different skin tones, then they should also be removed one at a time, not all at once

## Actual Result:
When a reaction of one tone is removed, all reactions are removed simultaneously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/15c20f48-fe1f-4939-8c88-7ac385b75658

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01788099114fae5336</li>
        <li>Upwork Job ID: 1738391263511302144</li>
        <li>Last Price Increase: 2023-12-30</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-23 03:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
All skin tone reactions are removed at once

### What is the root cause of that problem?
We do not handle removal by a certain skin tone, but remove all the reactions of one emoji at once here:

https://github.com/Expensify/App/blob/85a5206a020d1d35beae4b9b262f6561e9d0ee9c/src/libs/actions/Report.ts#L1988

### What changes do you think we should make in order to solve the problem?

We should add param `skinTone` to the `removeEmojiReaction` function and remove the certain skinTone reaction by using a merge operation similar to the one we use when adding the reaction in `addEmojiReaction`.



### What alternative solutions did you explore? (Optional)

**Comment by dragnoir** [comment] 2023-12-25 07:30
> This behavior is the same in Slack: we can add multiple skintone reactions, but they are removed all at once.

On Slack you can remove the emoji by skin, not all at once.

BE should support removing emoji by skin.

**Comment by sonialiap** [comment] 2024-01-04 17:34
Stites confirmed that this is by design. Closing as 🚫 🐛

**Closed by sonialiap** 2024-01-04 17:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
