### ISSUE TITLE
[$1000] Web - Emoji picker search is not focused while adding emoji reaction on attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21964] opened 2023-06-30 17:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send any image
4. Right click on side of image and click on Add reaction, observe that search is focused on emoji picker
5. Close that and right click on the image and click on Add reaction, observe that search is not focused on emoji picker

## Expected Result:
App should keep the focus on search whenever emoji picker is opened

## Actual Result:
App does not focus on search if we right click on image area and open emoji picker using Add reaction button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6a28e868-ee0e-493f-8470-2c560b09aa11

https://github.com/Expensify/App/assets/93399543/dd102d49-653b-475b-a6a6-74cbd166cfd7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688052193786259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0cac382a00f2086</li>
        <li>Upwork Job ID: 1676164421591789568</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 25946639</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-04 09:41
reviewed, not overdue

**Comment by alitoshmatov** [comment] 2023-07-04 10:51
I think https://github.com/Expensify/App/issues/21833 will fix this as well

**Comment by laurenreidexpensify** [comment] 2023-07-06 07:16
@eVoloshchak do you agree we should hold on https://github.com/Expensify/App/issues/21833 and close if this is no longer reproducible when that hits prod?

**Comment by eVoloshchak** [comment] 2023-07-06 16:22
@laurenreidexpensify, yes, agree with @alitoshmatov's [comment](https://github.com/Expensify/App/issues/21964#issuecomment-1620018813), let's put this on hold

**Comment by laurenreidexpensify** [comment] 2023-07-10 09:27
Updated - we're holding on #21833

**Comment by laurenreidexpensify** [comment] 2023-07-11 09:01
There's a hold chain, we're unlikely to see this off hold til late July

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:38
#21833 has been resolved, the issue is only open because of a payment issue. 

@applausebot can you please confirm this is reproducible?

**Comment by laurenreidexpensify** [comment] 2023-08-04 11:27
oh i think the automation did a few things I didn't expect here - we are waiting for confirmation from @applausebot if this is still reproducible so I added them as an assignee

**Comment by laurenreidexpensify** [comment] 2023-08-07 12:17
bumped in Slack - https://expensify.slack.com/archives/C049HHMV9SM/p1691410625667899?thread_ts=1688052193.786259&cid=C049HHMV9SM

**Comment by mvtglobally** [comment] 2023-08-08 04:00
@laurenreidexpensify Not repro on few devices 

https://github.com/Expensify/App/assets/43995119/2817f765-df21-4fe5-8444-7a72f9bc4ffe


https://github.com/Expensify/App/assets/43995119/43c45f9f-ac74-40c5-b988-0e8aadc542f4


https://github.com/Expensify/App/assets/43995119/87d9a703-5cc2-46d9-99c3-bb521b1de852

**Comment by laurenreidexpensify** [comment] 2023-08-08 07:07
Okay I am going to close this. Thanks everyone.

**Closed by laurenreidexpensify** 2023-08-08 07:07 UTC
Labels: External, Daily, Bug

**Comment by dhanashree-sawant** [comment] 2023-08-08 07:58
Hi @laurenreidexpensify, I already have accepted offer for the issue sent by service account, can you have a look once into it?
