### ISSUE TITLE
[$500] [HOLD for payment 2023-09-21] Web - allStates.Greater London.stateName appears on select United state as Country

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27325] opened 2023-09-13 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings >Profile > Personal details > Home address
2. Click on Country and select  United state
3. Check the state

## Expected Result:
should not show allStates.Greater London.stateName

## Actual Result:
allStates.Greater London.stateName appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/972ddb5d-f4f4-4dbe-88c2-e126a41621e6

https://github.com/Expensify/App/assets/93399543/d69b7463-780c-448f-ad51-feae51beed67

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694597057219419
Original reporter:
 https://expensify.slack.com/archives/C049HHMV9SM/p1694597349412869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4437f3cf84845b7</li>
        <li>Upwork Job ID: 1706865721848041472</li>
        <li>Last Price Increase: 2023-09-27</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-13 11:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
In `AddressPage`, the `StatePicker` component has the `defaultValue` set to the initially selected state. It does not change with the state change, since the defaultValue is already persisted the moment the `StatePicker` is rendered.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/544661b6df46a0bb60575c4e89478e8e62079674/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L187-L191

```diff
                            <StatePicker
                                inputID="state"
-                               defaultValue={state}
+                               value={state}
                                onValueChange={handleAddressChange}
                            />
```



### What alternative solutions did you explore? (Optional)

**Comment by madmax330** [comment] 2023-09-13 12:14
@paultsimura I think someone already has the fix, we're just waiting for them to put up the PR

**Comment by paultsimura** [comment] 2023-09-13 16:01
> @paultsimura I think someone already has the fix, we're just waiting for them to put up the PR

I see this issue was referenced in a PR, but I doubt that PR fixes this issue - it doesn't look like a regression from the translations flattening.

Anyway, let's wait and see what the result would be.

**Comment by madmax330** [comment] 2023-09-13 16:18
@paultsimura if you look at the testing videos in the PR description, it is fixed.

**Comment by paultsimura** [comment] 2023-09-13 18:58
> @paultsimura if you look at the testing videos in the PR description, it is fixed.

You're right, my apologies.

**Comment by madmax330** [comment] 2023-09-26 11:59
I think we can close this. It was a deploy blocker, but it was fixed already

**Comment by madmax330** [comment] 2023-09-27 02:01
Ah, sorry

**Comment by madmax330** [comment] 2023-09-27 02:04
@kevinksullivan can you just handle the C+ payment? Then we can close the issue

**Comment by greg-schroeder** [comment] 2023-09-27 02:43
I'll take care of this @kevinksullivan since I happen to be in Upwork already

**Comment by greg-schroeder** [comment] 2023-09-27 02:58
Just applying external to create an upwork job

**Comment by madmax330** [comment] 2023-09-27 03:30
@greg-schroeder I think @parasharrajat gets paid in newDot, do we still need an upwork job for that?

**Comment by greg-schroeder** [comment] 2023-09-27 04:56
@madmax330 are we not paying the issue reporter?

**Comment by dhanashree-sawant** [comment] 2023-09-27 04:57
Yes my payment too is left 😅

**Comment by madmax330** [comment] 2023-09-27 04:57
> are we not paying the issue reporter?

Ah yes, forgot about that, sorry :ohnothing:

**Comment by greg-schroeder** [comment] 2023-09-27 05:05
Issue Participants:

Issue reported by: @dhanashree-sawant hanashree-sawant 
C+: @parasharrajat 

Reporter: $50
C+: $500 (+$250 speed bonus)

offer sent to reporter, Rajat you can make a manual request in newdot

**Closed by greg-schroeder** 2023-09-27 05:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug

**Comment by dhanashree-sawant** [comment] 2023-09-27 05:26
Thanks @greg-schroeder, I have accepted the offer

**Comment by JmillsExpensify** [comment] 2023-10-09 17:00
$750 payment approved for @parasharrajat based on BZ summary.
