### ISSUE TITLE
[Search v2.1] Web - Search filters - Search result becomes empty after changing sorting order

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48483] opened 2024-09-03 14:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit an expense with a category
4. Go to Search
5. Click Filters
6. Click Category
7. Select the category used in Step 3
8. Also select another category that has not been used in any transaction
9. Click Save
10. Click View results
11. Click on the sorting (Merchant, To, From etc)

## Expected Result:
App will display the valid results

## Actual Result:
Search result becomes empty after changing sorting order
This issue happens when two categories are selected in filters and one of the categories does not return results

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6a709b25-affc-4965-b13c-2178422b5355

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @289Adam289</details>

**Comment by FitseTLT** [comment] 2024-09-03 16:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Search filters - Search result becomes empty after changing sorting order

### What is the root cause of that problem?
In building the search filter string here
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/libs/SearchUtils.ts#L557
we are concatenating the filter values with space which means `AND` so it will be searching for expenses which has two categories at the same time which will return empty
### What changes do you think we should make in order to solve the problem?

We should change it to `,` instead
```
            filterValueString += `,${sanitizeString(queryFilter.value.toString())}`;

```
### What alternative solutions did you explore? (Optional)

**Comment by 289Adam289** [comment] 2024-09-04 13:32
Hi! I am from SWM, an expert agency and I'd like to work on this issue. I am working right now on Search Header Page cleanup and i can fix this bug in the same pr.

**Comment by trjExpensify** [comment] 2024-09-04 20:18
Go ahead and link it! CC: @luacmartins

**Comment by luacmartins** [comment] 2024-09-04 23:42
Linked here https://github.com/Expensify/App/pull/48538

**Comment by trjExpensify** [comment] 2024-09-10 10:49
PR in active review, Melv.

**Comment by luacmartins** [comment] 2024-09-19 00:11
PR was deployed to prod last week. This is solved, closing.

**Closed by luacmartins** 2024-09-19 00:11 UTC
Labels: Reviewing, Weekly, Bug
