### ISSUE TITLE
 IOU - RHP does not disappear after sending a request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27724] opened 2023-09-18 23:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with any account
3. Click on FAB
4. Select "Request money."
5. Complete the creation of an IOU with a user with whom there is no history of conversation
6. Go to the conversation with the user to whom you sent the IOU
7. Click Action menu
8. Select "Request money" and complete it with any amount of money

## Expected Result:
The RHP should close and the user should get into a conversation with the user to whom the IOU was sent

## Actual Result:
RHP does not close after the IOU is completed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/db3e751d-a9ee-4d1b-b065-da0e55e6648b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-09-19 00:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- On Requesting Money the page is navigating back to Manual Request page instead of report page.

### What is the root cause of that problem?
- Here in MoneyRequestConfirmPage.js the conditions 
    - `_.isEmpty(props.iou.participants)`  
    - `props.iou.amount === 0 && !props.iou.receiptPath && !isDistanceRequest`
are getting true which in turn is calling goBack() function which is navigating back to Manual Request page instead of report page.

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/iou/steps/MoneyRequestConfirmPage.js#L105-L107

### What changes do you think we should make in order to solve the problem?
- We can add a ref `navigatingBack` and set it true when we call `requestMoney` function.

https://github.com/Expensify/App/blob/e23c1817486465c0266905d9e1d425bb6ad16ef1/src/pages/iou/steps/MoneyRequestConfirmPage.js#L129

- And we can add a check if (!navigatingBack.current) in the conditions.

```js
if (!navigatingBack.current && (_.isEmpty(props.iou.participants) || (props.iou.amount === 0 && !props.iou.receiptPath && !isDistanceRequest) || shouldReset)) {
    Navigation.goBack(ROUTES.getMoneyRequestRoute(iouType.current, reportID.current), true);
}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by DylanDylann** [comment] 2023-09-19 05:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHP does not disappear after sending a request money

### What is the root cause of that problem?

Let's see here
https://github.com/Expensify/App/blob/5150f86801b2eed2ee0e4b06664444f44094017f/src/libs/actions/IOU.js#L650-L652
When requesting money, we clear the field on ONYX before dismissing the modal.

And in here

https://github.com/Expensify/App/blob/5150f86801b2eed2ee0e4b06664444f44094017f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L105

Because we clear the field before dismissing the modal, this logic will be triggered. It causes wrong navigation.
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/5150f86801b2eed2ee0e4b06664444f44094017f/src/libs/actions/IOU.js#L650-L652

In here, we should dismiss modal before clear iou field

https://github.com/Expensify/App/blob/5150f86801b2eed2ee0e4b06664444f44094017f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L105

And in here we should check if modal.isVisible === false we will return that useEffect like that
```
useEffect(() => {
        const initialModalState = getModalState();
        if (!initialModalState.isVisible) {
            return;
        }

```



### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-19 05:56
@laurenreidexpensify This issue is blocking other issues that relate to IOU. Could you take a look on this?

**Comment by laurenreidexpensify** [comment] 2023-09-19 07:06
The automation failed to assign an engineer here so have re-added.

**Comment by AndrewGable** [comment] 2023-09-19 07:41
@jeet-dhandha and @DylanDylann - Trying to figure out which PR introduced this recently, if you have any leads that would be helpful!

**Comment by AndrewGable** [comment] 2023-09-19 08:15
I can reproduce on staging, I cannot reproduce on production so this does seem like something we introduced recently.

**Comment by AndrewGable** [comment] 2023-09-19 08:22
Interestingly, I cannot reproduce on `main`, so I do wonder if this has already been fixed..?

**Comment by AndrewGable** [comment] 2023-09-19 08:31
I can't tell if `main` is actually not triggering the bug or not as I cannot reproduce locally on the `staging` branch

**Comment by jeet-dhandha** [comment] 2023-09-19 12:01
@AndrewGable 
- https://github.com/Expensify/App/pull/17964 

The code for navigation was added in this PR.

**Comment by DylanDylann** [comment] 2023-09-19 16:21
Can't reproduce now

**Comment by AndrewGable** [comment] 2023-09-20 02:42
https://github.com/Expensify/App/pull/26854 introduced and this was fixed by @aimane-chnaif in https://github.com/Expensify/App/pull/27793

**Closed by AndrewGable** 2023-09-20 02:42 UTC
Labels: Reviewing, Engineering, Weekly, Bug
