### ISSUE TITLE
[Hold for #35004][$500] Android - LNH - Chat stays unread after opening notification

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34698] opened 2024-01-18 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the mobile app and log into account1
2. Navigate to LHN
3. Log onto second device with a different account (account2)
4. Send a message from account2 to account1
5. Open the mobile notification
6. Return to LHN
7. Leave the app in the background
8. Send another message from account2 to account1
9. Return to the LHN

## Expected Result:
The chat becomes read in the LHN after opening a notification

## Actual Result:
The chat stays unread after returning to the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/571ff9a0-bb00-4866-be9d-5112b4a8d292

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd046308a530dc22</li>
        <li>Upwork Job ID: 1747794833626546176</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-18 01:36
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by sonialiap** [comment] 2024-01-22 15:14
Reproducible. I'm updating the instructions to clarify which device the action is taken on

**Comment by sonialiap** [comment] 2024-01-22 15:23
Checking if this is related to #33771

**Comment by sonialiap** [comment] 2024-01-26 15:30
Engineering says that most likely separate from https://github.com/Expensify/App/issues/33771.

**Comment by sonialiap** [comment] 2024-01-26 15:30
Looking for proposals!

**Comment by sonialiap** [comment] 2024-01-30 13:19
Might be fixed by https://github.com/Expensify/App/pull/35004, putting on hold

**Comment by jeremy-croff** [comment] 2024-01-31 04:50
> Might be fixed by #35004, putting on hold

At the moment im unable to confirm if my branch addresses this because it seems I can only test notifications on a phyisical device.

**Comment by jeremy-croff** [comment] 2024-02-02 23:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The LHN does not unbold after opening it up from a notification, when the chat is already open. Even when minimized.

### What is the root cause of that problem?
While this might seem like an android notification issue,
The root cause is that we do mark the messages as read using Report.readNewestAction, that are already open at the moment and receive a message. This is reproducable on all platforms, by minimizing the browser, or app with the chat that is already selected, and sending a message to that chat from another device.

This is because we have a visibility check that decides whether or not to bold the LHN or mark it as read when we receive the messages. https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsList.js#L212
This will run each time we receive the message. Because it's not visible, we wont mark it as read. And the LHN will bold.
Two condition that re render this logic at the moment are: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsList.js#L227
So if we send another message while the window is visibile, it will unmark the LHN. Or if we renavigate to this reportId it will unmark the LHN.


### What changes do you think we should make in order to solve the problem?
I implemented a working solution for this in a past commit:
https://github.com/Expensify/App/pull/35004/commits/20020502033da43bbb17145b13c4c3f1899c0363
We removed it from the PR because it was out of scope.

The solution is to listen to focus change events, as they indicate to us the user is viewing it. And mark the latest message as read. We have an existing hook for it here that we can reuse: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/hooks/useAppFocusEvent/index.ts#L9
That way when we reopen from android, or web the window with the chat, it will mark the message in the current view as read and unbold the opened chat.

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-02-08 15:53
Holding [PR](https://github.com/Expensify/App/pull/35004) is still not merged yet

**Comment by sonialiap** [comment] 2024-03-06 14:55
Still on hold for the PR merge https://github.com/Expensify/App/pull/35004

**Comment by jeremy-croff** [comment] 2024-03-14 01:39
No need to hold! A similar solution got merged earlier with https://github.com/Expensify/App/pull/34537, and if you update the latest native app, it's not reproducible anymore.

**Comment by sonialiap** [comment] 2024-03-15 11:07
Thanks Jeremy 👍

**Closed by sonialiap** 2024-03-15 11:07 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
