### ISSUE TITLE
[C+ Checklist needs completion] [$1000] Web -  App allows user to open request money link of other user and displays amount page twice

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23755] opened 2023-07-27 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open user C report, click on plus, click on request money, enter  any amount, click next and copy the URL
3. Send the URL to user B
4. Open the app in any other eligible device and login with user B
5. Open user A report and open link sent by user A
6. Observe that app allows to open link of request money between 2 different users, enter amount and click next
7. Observe that it again displays amount page of request money

## Expected Result:
App should not allow you to open request money confirmation page for other users

## Actual Result:
App allows you to open request money confirmation page for other users

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bb70f199-4d8e-48d4-b1ff-407beb1ca778

https://github.com/Expensify/App/assets/93399543/5a5ebc7b-3dc4-4a0e-be13-1aa9fd5a2e22

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690396372826599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017939880358ebbb25</li>
        <li>Upwork Job ID: 1684841055911837696</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by neonbhai** [comment] 2023-07-28 04:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App allows user to open request money link of other user and displays amount page twice

### What is the root cause of that problem?
This happens because the props.iou.id is not equal to moneyRequestID (constructed from) reportID of the component, which comes from the url, since the url that initiated the component was from a different account, component resets while editing by checking the value in the variable shouldReset here:
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/iou/steps/MoneyRequestAmountPage.js#L263

Having it reset while editing dirupts the UX of the app. A refresh should ideally not be triggered *while* editing 

### What changes do you think we should make in order to solve the problem?
We should show `FullPageNotFoundView` when accessing a url meant for a different account.

To do this we need to add a check similar to `shouldReset` logic here in the `shouldShow` prop of the component: https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/iou/steps/MoneyRequestAmountPage.js#L425
	

### What alternative solutions did you explore? (Optional)
Instantly have the component reset as it appears
	+ For this we will move the shouldReset logic [here](https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/iou/steps/MoneyRequestAmountPage.js#L392-L400) to a function and call it in a `useEffect` hook that is meant to be triggered onMount

**Comment by greg-schroeder** [comment] 2023-07-28 08:19
>app should switch URL back to request money to ensure that amount page is not repeated

I definitely don't think this makes sense. I'm pretty sure this link just shouldn't be accessible

**Comment by greg-schroeder** [comment] 2023-07-31 14:54
Awaiting proposal review from @sobitneupane

**Comment by greg-schroeder** [comment] 2023-08-02 10:39
Same as above

**Comment by sobitneupane** [comment] 2023-08-03 11:11
Thanks for the proposal @neonbhai.

Can you please extend your proposal to include other pages in request money and split bill flow.

**Comment by sobitneupane** [comment] 2023-08-03 11:14
Thanks for the proposal @dukenv0307.

I think there are easier ways to deal with the issue. Can't we go with some simpler solution like the one proposed by @neonbhai [here](https://github.com/Expensify/App/issues/23755#issuecomment-1655009113)?

**Comment by neonbhai** [comment] 2023-08-03 11:22
@sobitneupane okay! will extend proposal to other pages shortly

**Comment by sobitneupane** [comment] 2023-08-05 04:20
Any update on [this](https://github.com/Expensify/App/issues/23755#issuecomment-1663796589) @neonbhai?

**Comment by greg-schroeder** [comment] 2023-08-07 15:12
bump @neonbhai were you able to update your proposal?

**Comment by sobitneupane** [comment] 2023-08-09 03:23
Have not received any update from @neonbhai. Going to review other proposals.

**Comment by neonbhai** [comment] 2023-08-09 10:19
@sobitneupane @greg-schroeder 

I sincerely apologize for being offline. I lost my laptop while travelling. Reached home today morning. I understand that time is valuable here, and I apologise for any inconvenience my delay may have caused.

I have updated the [proposal](https://github.com/Expensify/App/issues/23755#issuecomment-1655009113), but looks like the money request flows went through two refactors this week, so some of the code has moved and the file names changed, hence updated the logic accordingly

Once again, I hope you can forgive me for not being able to update proposal.

**Comment by neonbhai** [comment] 2023-08-09 10:23
## Proposal
[Updated](https://github.com/Expensify/App/issues/23755#issuecomment-1655009113)

**Comment by greg-schroeder** [comment] 2023-08-14 08:51
Can you check updated proposal here @sobitneupane?

**Comment by sobitneupane** [comment] 2023-08-14 12:18
> When we open a deeplink of confirm page with an exist reportID we should reset it to the amount page to enter an amount before going to confirm page.

@dukenv0307 I don't think that is the case now. We can directly request money from confirm page.

**Comment by sobitneupane** [comment] 2023-08-14 12:33
> If we display not found page using shouldReset condition in confirm page, the page also display not found page with an exist reportID when we go to this page by deeplink.

I got your point. It is definitely not expected scenario. 

@neonbhai Your thoughts?

**Comment by sobitneupane** [comment] 2023-08-16 15:36
@bernhardoj Will the alternative solution solution work for other pages like confirmation page?

**Comment by sobitneupane** [comment] 2023-08-17 11:17
Looks like we don't have any simple way of solving the issue. Still, I am rooting for some simple solution. @dukenv0307 Is there any way to simplify [your solution](https://github.com/Expensify/App/issues/23755#issuecomment-1655489223)? I am not very much sold by the idea of duplicating the pages.

**Comment by sobitneupane** [comment] 2023-08-17 11:23
Yup @bernhardoj. I think we should simply show not found page if the user don't have access to the report as suggested [here](https://github.com/Expensify/App/issues/23755#issuecomment-1655254962).

**Comment by sobitneupane** [comment] 2023-08-18 10:34
@bernhardoj I don't think I get you completely. So, If user access confirmation page for a inaccessible reportID, then user will be redirected to amount page with not found message. Is that the case? I am not sure how it will look like.

**Comment by greg-schroeder** [comment] 2023-08-21 17:44
Proposal review underway

**Comment by sobitneupane** [comment] 2023-08-22 08:03
@bernhardoj Thanks for the update.

I think it's fine to redirect to money request page before showing Not Found Page. 
If it works for split bill flow from FAB, request money flow from FAB, request money flow from report Action, split bill flow from FAB, Money Selector Page for user having (not having) access to the report, Confirmation Page, Description Page, etc, we can go with your proposal.

@bernhardoj Can you please confirm it works in all above cases? We need to include all above instances in test as well..

**Comment by sobitneupane** [comment] 2023-08-22 09:11
@dukenv0307 If the case (also control the loading when we go the page by deeplink before login) can be handled with minimum change, let's not go for HOC if it doesn't have many use cases.

**Comment by sobitneupane** [comment] 2023-08-23 07:11
@bernhardoj Will it work for the case where user is logout and login with the url of money request page with valid reportID? It should open money request page in that case instead of Not Found Page.

**Comment by sobitneupane** [comment] 2023-08-25 09:36
Thanks for the update @dukenv0307 and @bernhardoj.

As we have use case for HOC in task flow as well, let's create HOC as suggested by @dukenv0307 [here](https://github.com/Expensify/App/issues/23755#issuecomment-1655489223).

[Proposal](https://github.com/Expensify/App/issues/23755#issuecomment-1655489223) from @dukenv0307 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment] 2023-08-25 17:40
Hi! Lots of stuff to read through here. To clarify, @sobitneupane are you suggesting we go with @dukenv0307's alternative solution in that proposal, not the main one?

If so, is there any way we could modify the existing  `WithReportOrNotFound` HOC to cover this case as well, maybe do something like pass a `checkRoute` prop to it (with a default false) and if that's true, check for the reportID in the route instead? Just an idea, I have not tested or thought more about it other than writing this haha.

**Comment by sobitneupane** [comment] 2023-08-28 08:54
> Hi! Lots of stuff to read through here. To clarify, @sobitneupane are you suggesting we go with @dukenv0307's alternative solution in that proposal, not the main one?

Yes. I am suggesting to go with alternative solution.

> If so, is there any way we could modify the existing WithReportOrNotFound HOC to cover this case as well, maybe do something like pass a checkRoute prop to it (with a default false) and if that's true, check for the reportID in the route instead? Just an idea, I have not tested or thought more about it other than writing this haha.

I agree. @dukenv0307 Can we do something as suggested here?

**Comment by dangrous** [comment] 2023-08-28 16:50
Great! @dukenv0307 do you mind updating your proposal with that approach, and we can go from there? Thank you!

**Comment by dangrous** [comment] 2023-08-30 19:27
Sorry for the delay! So I think that wasn't quite what I was thinking, I was thinking putting something like this above [this line](https://github.com/Expensify/App/blob/c7bdc81a3e30bd380a942c980e16f0891d0db4a6/src/pages/home/report/withReportOrNotFound.js#L51)
```
if (_.isEmpty(props.report) && checkRoute) {
	// see if there is a reportID in the route
	// if so, get that report and replace all references to props.report with that
}
```
Does that make sense? If there's a strong argument to doing what you put in the updated proposal, happy to hear it! Also @sobitneupane let us know what you think!

**Comment by sobitneupane** [comment] 2023-09-04 08:59
@dukenv0307 Can you please elaborate your proposal? Where are you proposing to make those changes?

**Comment by dangrous** [comment] 2023-09-07 14:21
@sobitneupane can you do a final review of [the updated proposal](https://github.com/Expensify/App/issues/23755#issuecomment-1704896105) today? I can take a look probably tomorrow but am working on some higher priority stuff so would love your eyes beforehand. Thank you!

**Comment by sobitneupane** [comment] 2023-09-11 09:40
Sorry for the delay here.

@dukenv0307 I am not getting you.

```diff
- export default function (WrappedComponent) {
+ export default function (isRequireReportId = true) {

```

Won't it affect other components as well? I don't understand how it works. Don't we need to pass `WrappedComponent`? On my test, other components using `withReportOrNotFound` were impacted (App crashed on opening those components). If you have any reference or documentation about the method, it will be helpful.

**Comment by dangrous** [comment] 2023-09-12 16:28
Hi! Sorry, it's been a bit of time and I'm trying to get caught up.

It looks like this bug has changed slightly since the new receipt scanning features were added. For me, it opens the link, e.g. `http://localhost:8082/request/new/confirmation/116490262023639` but immediately redirects back to the regular report url - `http://localhost:8082/r/5289380645032640`. However, the request money pane is still open, and once you enter an amount, it still shows the amount again.

Am I wrong that this is slightly different, and may require a different solution? All we'd need to do in this case is make sure we close the pane when we redirect. I think?

**Comment by dangrous** [comment] 2023-09-13 16:36
weird! That's not what im getting, and I double checked im on the latest.

https://github.com/Expensify/App/assets/5487802/205e9fbe-bffa-46f6-8383-a2fb3eb66a0d

It shouldn't be an issue with the server, I don't think, so I don't know why pointing to local vs. pointing to staging should make any difference...

**Comment by dangrous** [comment] 2023-09-13 18:18
ah yep, nice catch. Now seeing the same behavior you are.

Okay, so back to @dukenv0307's proposal. Taking a step back, do you think you could write out quickly what the updates to `withReportOrNotFound` do in pseudocode? so like this, basically:

```
if (_.isEmpty(props.report) && checkRoute) {
	// see if there is a reportID in the route
	// if so, get that report and replace all references to props.report with that
}
```

Particularly since we're putting a lot of the existing code in that `if` statement, I want to make sure I understand how this is supposed to work. Thank you!

**Comment by dangrous** [comment] 2023-09-13 20:10
Okay great, so we're moving forward with using checkRoute = false as default vs. the requireReportID = true? That makes sense to me! Either way I think we can move forward with the PR and get that reviewed and merged

**Comment by greg-schroeder** [comment] 2023-09-25 07:03
Do you mind updating on us on where we stand here @dukenv0307 @sobitneupane?

**Comment by greg-schroeder** [comment] 2023-10-18 23:16
Looks like https://github.com/Expensify/App/pull/26149 is being reviewed by @dangrous now!

**Comment by greg-schroeder** [comment] 2023-10-23 22:57
It seems there was a regression here: https://github.com/Expensify/App/issues/30148

**Comment by dangrous** [comment] 2023-10-30 17:41
Oh am I supposed to do the checklist now? I thought it was still C+s (i.e. @sobitneupane )

**Comment by dangrous** [comment] 2023-10-31 14:50
@sobitneupane and @dukenv0307 do you think you can get that checklist done shortly? Then we can get this paid and closed out. Thanks!

**Comment by greg-schroeder** [comment] 2023-10-31 15:16
sorry was OOO yesterday, processing today

**Comment by greg-schroeder** [comment] 2023-11-01 03:27
Offers sent to @dhanashree-sawant and @dukenv0307

**Comment by dangrous** [comment] 2023-11-02 18:28
Bumping on the checklist @dukenv0307 and @sobitneupane - do you think you can finish that out this week? Thanks! I can help with the first parts if needed.

**Comment by dangrous** [comment] 2023-11-07 04:41
Tests look good to me!

**Comment by greg-schroeder** [comment] 2023-11-09 11:04
Thanks! Filing regression test

**Comment by greg-schroeder** [comment] 2023-11-09 11:12
paid, regression test filed

**Closed by greg-schroeder** 2023-11-09 11:12 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2023-12-15 09:30
> @greg-schroeder Can we get payment summary so I can request payment.

Bump on this @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-12-15 12:00
Oh, sorry @sobitneupane

**Comment by greg-schroeder** [comment] 2023-12-15 12:02
Went back through the offers from a couple months ago ... $1k issue but there was a regression. Final payments were:

C: $500
C+: $500

So you can make a manual request for this one!

**Comment by sobitneupane** [comment] 2023-12-15 12:16
Thanks @greg-schroeder 

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-12-15 23:18
$500 payment approved for @sobitneupane based on comment above.
