### ISSUE TITLE
[$500] Attached videos are not supported on iOS native/mWeb platform but are supported on Android/Web platforms.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41444] opened 2024-05-01 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rojiphil 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1714556057956819

## Action Performed:
Video link 1: `.webm` => https://drive.google.com/file/d/1gmvKcXcmB8QWfpBOLMEiPQ2dDpZgp-vC/view?usp=drive_link
Video link 2: `.mp4` => https://drive.google.com/file/d/11My7dbL-mLhBOCrAIv_onNVxSVqKQilJ/view?usp=drive_link
Steps:
1. Click Report FAB -> Add Attachment -> Select the video (This step must be performed on desktop/web platforms so that it uploads. Verify that it can be played)
2. Go to iOS native/Safari and try to play the attachment video added in step 1

## Expected Result:
The video player should play the video
## Actual Result:
Infinite loading icon is shown and the video player does not play the video
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/2bb87ee2-f2ac-452f-9ae0-d52230f81dcf

https://github.com/Expensify/App/assets/38435837/88ca5a5e-513b-42ae-9e44-8f5843c03524

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f605aa41bdffbe9e</li>
        <li>Upwork Job ID: 1786377175820685312</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by laurenreidexpensify** [comment] 2024-05-07 07:19
checking internally for replication

**Comment by laurenreidexpensify** [comment] 2024-05-13 09:43
Still waiting on proposals

**Comment by laurenreidexpensify** [comment] 2024-05-16 09:20
Still waiting on proposals - confirmed reproducible by @dylanexpensify

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:16
Increased bounty

**Comment by b4s36t4** [comment] 2024-05-21 20:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attached videos are not supported on iOS native/mWeb platform but are supported on Android/Web platforms.

### What is the root cause of that problem?

We're using `expo-av` to play videos for the native devices which underlying using `AVPlayer` for `iOS`.

But `AVPlayer` doesn't support playing `webm` files.

More on that here https://github.com/TheWidlarzGroup/react-native-video/issues/3155

### What changes do you think we should make in order to solve the problem?

While we can't restrict sending `.webm` files we should not allow the preview/playing for webm files inside our app.

https://github.com/Expensify/App/blob/959d6d0271169536ae46e15d482049d8a2468234/src/components/Attachments/AttachmentView/index.tsx#L98 in this line we're checking weather the attachment is `video` or not which contains logic to check for extension with `.webm`.

Which is using function from `expensify-common` package from `Str` module, we just need to write a condition to `.webm` file and the device which file is going to open and if the device is `iOS` let's not mark the value as true.

```jsx

// to check weather we're opening webm from ios device.
    const isWebmFromIOS = file?.name && Str.getExtension(file.name) === 'webm' && Platform.OS === 'ios';
```

Then we need to update the rendering logic for the video.

```jsx
    if ((isVideo ?? (file?.name && Str.isVideo(file.name))) && typeof source === 'string' && !isWebmFromIOS) {
```



### What alternative solutions did you explore? (Optional)
NA

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:03
Hi will review the proposal in my morning

**Comment by laurenreidexpensify** [comment] 2024-05-24 11:22
@abdulrahuman5196 bump for review thanks

**Comment by laurenreidexpensify** [comment] 2024-05-28 08:51
@abdulrahuman5196 bump

**Comment by abdulrahuman5196** [comment] 2024-05-28 18:30
checking now

**Comment by abdulrahuman5196** [comment] 2024-05-28 18:40
@b4s36t4 You have mentioned the issue for `.webm`, but the issue is also mentioning `.mp4` which is supported by AVPlayer.

**Comment by b4s36t4** [comment] 2024-05-28 18:44
@abdulrahuman5196 Sorry, I might've missed `.mp4`. I'll check and update my proposal, Thanks for checking!.

**Comment by b4s36t4** [comment] 2024-05-29 20:07
@abdulrahuman5196 I have tested using `.mp4` to play inside `iOS` and I don't have any problem playing as same as `webm` file.

I have used custom `.mp4` file form my computer, the link mentioned in OP is not working because the file is greater than 24mb i.e 67mb.

Please check from you side as well!

<img width="442" alt="Screenshot 2024-05-30 at 1 37 44 AM" src="https://github.com/Expensify/App/assets/59088937/a6f7b001-b57f-4306-bf09-c64cfbf6ed48">

**Comment by b4s36t4** [comment] 2024-05-30 08:42
I have verified `.webm` on real device safari and it's working fine. In simulator it's not working so I think we can discard issue for safari browser on simulator.

**Comment by laurenreidexpensify** [comment] 2024-05-31 12:02
@abdulrahuman5196 thoughts on the above?

**Comment by laurenreidexpensify** [comment] 2024-06-04 11:16
@abdulrahuman5196 can you please review latest comments thanks

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:50
> I have verified `.webm` on real device safari and it's working fine. In simulator it's not working so I think we can discard issue for safari browser on simulator.

Seems weird. let me check in both devices and update within in my morning

**Comment by abdulrahuman5196** [comment] 2024-06-07 10:23
Hi, checking again today

**Comment by laurenreidexpensify** [comment] 2024-06-07 11:55
Still waiting to to confirm proposals

**Comment by laurenreidexpensify** [comment] 2024-06-13 12:34
I think this isn't reliably reproducible, am going to close it. If we have further reports of customers running into this please reopen.

**Closed by laurenreidexpensify** 2024-06-13 12:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by b4s36t4** [comment] 2024-06-13 12:57
@laurenreidexpensify this issue is produceable in iOS device with webm videos. I can share the re-production demo with you if you need.

**Comment by b4s36t4** [comment] 2024-06-19 14:54
@abdulrahuman5196 @laurenreidexpensify gentle bump for re-review on this bug which is constantly reproducible in all ios devices.
