### ISSUE TITLE
BUG - Updating  last name with comma will save and then default back to an old saved last name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11963] opened 2022-10-18 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. Go to profile and change last name with a comma
3. Name is changed and reflected in the profile and in the chats
4. Close the app and reopen

## Expected Result:
Name should reflect as it has been saved

## Actual Result:
Comma disappears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @flaviadefaria 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666032512376389

https://user-images.githubusercontent.com/43996225/196480698-58f7c460-79ba-4341-a56e-73c600cffb0c.mp4

![image (1)](https://user-images.githubusercontent.com/43996225/196480781-fc59b32e-639a-498a-a19c-a39caac0a61b.png)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2022-10-19 16:28
Able to reproduce, passing to engineering.

**Comment by grgia** [comment] 2022-10-19 18:34
I don't think this is a bug, it's a result of sanitizing inputs for the DB. I'm going to go ahead and close this out since commas aren't allowed in legal names anyways

**Closed by grgia** 2022-10-19 18:34 UTC
Labels: AutoAssignerTriage, Engineering, Daily

**Comment by JmillsExpensify** [comment] 2022-10-21 22:10
This is interesting. It effectively means that we can't reliably use the last name as a status update. I think that's fine for now, though it does mean we're baking it some unpolished experiences in the app.

**Comment by grgia** [comment] 2022-10-24 15:39
@JmillsExpensify I think with the n7 push to page changes for profile/settings changes, we would be able to catch/handle this exception with immediate feedback to the user (i.e. error text)
