### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Taxes - App allows deleted tax rate to be selected as currency default in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41066] opened 2024-04-26 08:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- Workspace and Foreign currency default share the same tax rate.
- There are Tax rate A and B.

1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces > any workspace.
3. Go to Taxes.
4. Go offline.
5. Delete one of the tax rate which is not the default tax rate.
6. Go to Settings > Workspace currency default.
7. Select the deleted tax rate.
8. Now delete the remaining tax rate.

## Expected Result:
In Step 7, user should not be able to select the deleted tax rate.

## Actual Result:
In Step 7, user is able to select the deleted tax rate, which results in all the tax rate being able to be deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9dc59a19-84c5-4b95-a29e-d751893ef442

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120c22699693bf475</li>
        <li>Upwork Job ID: 1785526833780477952</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by izarutskaya** [comment] 2024-04-26 08:12
We think this issue might be related to the #collect project.

**Comment by JmillsExpensify** [comment] 2024-05-01 04:28
Adding as polish for wave-collect and opening up to the community.

**Comment by sobitneupane** [comment] 2024-05-03 10:11
Thanks for the [proposal](https://github.com/Expensify/App/issues/41066#issuecomment-2079243609) @Krishna2323 

I tested Categories and the issue is reproducible. I am pretty sure the issue lies in other similar functionality as well.

@JmillsExpensify Should we completely hide the deleted tax, or simply disable it in the list?

**Comment by sobitneupane** [comment] 2024-05-09 03:39
@JmillsExpensify Any thoughts on https://github.com/Expensify/App/issues/41066#issuecomment-2092706341?

**Comment by JmillsExpensify** [comment] 2024-05-15 03:14
Good question. I tend to think that we should hide it in those other lists shown in the OP, especially given that we already use the pending pattern where the actual deletion occurred. cc @trjExpensify in case you disagree.

**Comment by trjExpensify** [comment] 2024-05-16 15:42
Yeah, makes sense to not let you set a deleted tax rate as the default when it's pending to be deleted. Removing it from the select list seems okay, but  it would probably be more consistent with the pattern to show it in the list still but greyed out with strikethrough as it's pending to be deleted.

>I tested Categories and the issue is reproducible. I am pretty sure the issue lies in other similar functionality as well.

What feature on the categories page in this regard? 

I can imagine there's one on `Distance rates` with setting a default category for distance expenses. If you've deleted the category when offline, similarly it should show as pending delete in the select list there.

**Comment by sobitneupane** [comment] 2024-05-19 09:31
> What feature on the categories page in this regard?

@trjExpensify Even after deleting categories, they can still be selected when submitting an expense. The same is likely to happen with tags and distance rates.

https://github.com/Expensify/App/assets/25876548/d813c74d-b07f-40d5-80ac-cab5f3991964

**Comment by sobitneupane** [comment] 2024-05-19 09:43
@Krishna2323 Can you please identify in which other places (probably Categories, Tags, and Distance Rates) changes will be required and what sort of changes will be needed? Also, can you please confirm if the second option in [your proposal](https://github.com/Expensify/App/issues/41066#issuecomment-2079243609) complies with [this expected output](https://github.com/Expensify/App/issues/41066#issuecomment-2115588062)?

**Comment by sobitneupane** [comment] 2024-05-21 03:18
Thanks for the update @Krishna2323 

Alternative Solution 1 in @Krishna2323's [proposal](https://github.com/Expensify/App/issues/41066#issuecomment-2079243609) looks good.

🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2024-06-19 04:35
@sobitneupane mind filling out the BZ checklist? In the meantime, payment summary as follows:

 - Contributor: $250 @Krishna2323 
 - Contributor+: $250 @sobitneupane

**Comment by JmillsExpensify** [comment] 2024-06-19 04:39
Contributor paid out and C+ is paid through New Expensify, so I'm going to close this issue and we can circle back on checklist during payment approvals.

**Comment by sobitneupane** [comment] 2024-06-20 09:18
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

The issue was already present in Section List. It was resurfaced in the app with the introduction of fields like Category, Tag and Tax fields

**Comment by sobitneupane** [comment] 2024-06-20 09:20
**Regression Test Proposal:**

1. Go to Account settings > Workspaces > any workspace.
2. Go to Taxes.
3. Go offline.
4. Delete one of the tax rate which is not the default tax rate.
5. Go to Settings > Workspace currency default.
6. Verify deleted tax rate can't be selected and is styled correctly with strike-through

Do we agree 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-06-22 16:48
Need someone else to confirm my payment summary. I've added the regression test in the meantime.

**Comment by mallenexpensify** [comment] 2024-06-24 15:23
Contributor: $250 @Krishna2323 paid via Upwork
Contributor+: $250 @sobitneupane due via NewDot.

**Comment by JmillsExpensify** [comment] 2024-06-24 16:26
$250 approved for @sobitneupane

**Comment by JmillsExpensify** [comment] 2024-06-26 19:46
Everyone paid out and regression test created, so I'm closing this one.

**Closed by JmillsExpensify** 2024-06-26 19:46 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
