### ISSUE TITLE
[HOLD for payment 2024-07-10] [Search v1] - Scanning expense displays 0.00 in Total column and the Merchant column is blank

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43474] opened 2024-06-11 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-8
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a scan expense.
4. While the receipt is scanning, go to Search.

## Expected Result:
The scanning expense will display "Scanning" in Merchant and Total column, similar to transaction thread.

## Actual Result:
The scanning expense displays 0.00 in Total column, and the Merchant column is blank.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/60340ad0-ad1b-42c9-8dd3-7736fc948361

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by m-natarajan** [comment] 2024-06-11 13:12
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-11 13:12
We think that this bug might be related to #wave-collect - Release 1

**Comment by etCoderDysto** [comment] 2024-06-11 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scanning expenses display 0.00 in the Total column, and the Merchant column is blank.
### What is the root cause of that problem?
`transactionItem.formattedMerchant`and `transactionItem.formattedMerchant` are displayed without checking if the request is a scan and if the scan state is "SCANNING."

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L121

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L108

### What changes do you think we should make in order to solve the problem?
Since there is no state property on `transactionItem.receipt`, we can't determine if the transaction is a scan and if the transaction state is "SCANNING." As an option, we can display the amount if `transactionItem.formattedTotal` is truthy, or display 'Scanning...' if it is not. Similarly, we can display the merchant if `transactionItem.formattedMerchant` is truthy, or display 'Scanning...' if it is not.

```
const formatedTransationAmount = transactionItem.formattedTotal ? CurrencyUtils.convertToDisplayString(transactionItem.formattedTotal, currency) : translate('iou.receiptStatusTitle');
```

```
const formattedMerchant = transactionItem.formattedMerchant ? transactionItem.formattedMerchant : translate('iou.receiptStatusTitle');
```
### What alternative solutions did you explore? (Optional)

If we could get to fetch a transactionItem object that has `transactionItem.receipt.state` property we can follow the same scan receipt state checking method implemented on `MoneyRequestView` page

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/ReportActionItem/MoneyRequestView.tsx#L195-L197

**Comment by carlosmiceli** [comment] 2024-06-11 13:30
Looking at the checklist, I don't think this is a deploy blocker, but it does look like a bug that could be External.

**Comment by mollfpr** [comment] 2024-06-11 13:33
Checking 👀

**Comment by carlosmiceli** [comment] 2024-06-11 13:33
@garrettmknight question, why does it say "Unable to auto-create job on Upwork. The BZ team member should create it manually for this issue." when adding the External label?

**Comment by luacmartins** [comment] 2024-06-11 14:07
@JmillsExpensify @trjExpensify what's the expected behavior here?

**Comment by Tony-MK** [comment] 2024-06-11 14:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scanning expense displays 0.00 in Total column and the Merchant column is blank

### What is the root cause of that problem?

The root cause of the problem is that the `MerchantCell`, `TotalCell`, and the `TaxCell` in the `TransactionListItemRow` does not check if the receipt is being scanned.

Therefore, the `TransactionListItemRow` will show the `transactionItem.formattedMerchant` which is an empty string.

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L108

Also, both the `TotalCell` and the `TaxCell` rows will show zero.

https://github.com/Expensify/App/blob/4f2901f5b72a90ad56ff17150c93476fb1166886/src/components/SelectionList/Search/TransactionListItemRow.tsx#L121

### What changes do you think we should make in order to solve the problem?


Hence, we should check if the transaction has a receipt and is being scanned so we should show `scanning` in those cells.

We check with the following condition illustrated below.

```
transactionItem.hasEReceipt && TransactionUtils.isReceiptBeingScanned(transactionItem) 
```

For the `MerchantCell`, we can change the text prop to something like the one below.

```
text={transactionItem.shouldShowMerchant ? (transactionItem.hasEReceipt && TransactionUtils.isReceiptBeingScanned(transactionItem) ? transactionItem.formattedMerchant : translate('iou.receiptStatusTitle')) : description}
```

For the `TotalCell` and the `TaxCell`, we can change the text prop to something like the one below.

```
text={transactionItem.hasEReceipt && TransactionUtils.isReceiptBeingScanned(transactionItem) ? translate('iou.receiptStatusTitle') : CurrencyUtils.convertToDisplayString(transactionItem.formattedTotal, currency)}
```

### What alternative solutions did you explore? (Optional)

We can change the `TransactionUtils.getDescription` function to return `scanning` if the receipt is scanning and `transactionItem.shouldShowMerchant` is `false`.

**Comment by trjExpensify** [comment] 2024-06-11 16:39
> @JmillsExpensify @trjExpensify what's the expected behavior here?

Great question! I don't think we really considered this initially. We could go with the `Scanning...` in the `merchant` and `amount` fields, or we could do something more visual on the row to signal that it's in the scanning state perhaps? 

CC: @Expensify/design for thoughts!

**Comment by shawnborton** [comment] 2024-06-11 16:55
I am down with that as an easy place to start.

**Comment by dannymcclain** [comment] 2024-06-11 17:10
>I am down with that as an easy place to start.

Agree. This seems like the most straight forward approach to fix this quickly. I'm not against trying to improve it, but I like starting here.

**Comment by etCoderDysto** [comment] 2024-06-12 15:04
[Updated my proposal](https://github.com/Expensify/App/issues/43474#issuecomment-2160774600) expounding my alternative solution and discarding my main solution.

**Comment by garrettmknight** [comment] 2024-06-12 18:16
>@garrettmknight question, why does it say "Unable to auto-create job on Upwork. The BZ team member should create it manually for this issue." when adding the External label?

@carlosmiceli sometimes the automation fails so the BZ team member has to create the Upwork job manually.

**Comment by mollfpr** [comment] 2024-06-13 17:33
@Tony-MK The merchant field shows Scanning even though the expense is scanned.

![Screenshot 2024-06-14 at 00 15 00](https://github.com/Expensify/App/assets/25520267/595df512-dd45-4c41-9b70-b7a150990a7c)

---

The [proposal](https://github.com/Expensify/App/issues/43474#issuecomment-2160774600) from @etCoderDysto looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by etCoderDysto** [comment] 2024-06-13 18:21
Thank you! I will raise a pr ASAP.

**Comment by luacmartins** [comment] 2024-06-13 19:19
It looks like the selected [proposal](https://github.com/Expensify/App/issues/43474#issuecomment-2160774600) relies on backend changes. @carlosmiceli are you available to work on that?

**Comment by carlosmiceli** [comment] 2024-06-13 19:21
Yes! I'll wait for that PR and then do the BE part.

**Comment by luacmartins** [comment] 2024-06-13 19:24
Hmm I think the App PR depends on the backend providing this data, no?

**Comment by carlosmiceli** [comment] 2024-06-13 20:53
Ah, good point, I skimmed it quickly and didn't think of the best order. I'll work on it as soon as I can 🙏

**Comment by etCoderDysto** [comment] 2024-06-14 09:27
I will raise a pr once the BE PR is merged.

**Comment by etCoderDysto** [comment] 2024-06-16 14:05
Hi @mollfpr this is my first PR, and I want to check if it is alright to apply on other issues until BE pr is merged? 
> [New contributors are limited to working on one job at a time](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=New%20contributors%20are%20limited%20to%20working%20on%20one%20job%20at%20a%20time)
I have seen the above guidline but I wanted to make sure if it is alright to apply on other issues until the BE pr is merged.

**Comment by garrettmknight** [comment] 2024-06-17 12:47
Hey @etCoderDysto - since this one is held on raising the BE, you can apply to other issues. Feel free to link this comment as proof of approval.

**Comment by etCoderDysto** [comment] 2024-06-17 12:53
> Hey @etCoderDysto - since this one is held on raising the BE, you can apply to other issues. Feel free to link this comment as proof of approval.

Thank you, Garrett🙇‍♂️

**Comment by luacmartins** [comment] 2024-06-17 17:31
@etCoderDysto I think you could get started on your PR too and assume that the API response would include the receipt state. We'd have to wait on the backend changes to test it properly though.

**Comment by mollfpr** [comment] 2024-06-19 17:59
Not overdue Melv!

**Comment by garrettmknight** [comment] 2024-06-19 19:00
Not overdue, just waiting on BE progress so we can unlock everything.

**Comment by carlosmiceli** [comment] 2024-06-19 19:26
Came back today from OOO, trying to catch up some things and ideally I should be able to start this tomorrow.

**Comment by carlosmiceli** [comment] 2024-06-20 20:19
@luacmartins added you as reviewer for the Auth fix.

**Comment by luacmartins** [comment] 2024-06-20 20:55
Approved & merged

**Comment by etCoderDysto** [comment] 2024-06-23 20:51
@mollfpr [PR](https://github.com/Expensify/App/pull/44190) is ready for review.

**Comment by garrettmknight** [comment] 2024-07-10 19:30
**Payment Summary:**
- Contributor: @etCoderDysto $250
- Reviewer: @mollfpr $250

@etCoderDysto offer out to you in Upwork

**Comment by etCoderDysto** [comment] 2024-07-10 19:39
I have accepted the offer. Thank you!

**Comment by garrettmknight** [comment] 2024-07-11 09:25
Contributor paid, dropping to weekly for reveiwer to request.

**Comment by mollfpr** [comment] 2024-07-11 17:51
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR was found.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Go to workspace chat.
2. Submit a scan expense.
3. While the receipt is scanning, go to Search.
4. Verify that the 'Scanning...' message is displayed on the Merchant and Total fields
5. After the receipt finishes scanning return back to the Search page
6. Verify that the scan result is displayed on the Merchant and Total fields instead of the 'Scanning...' message
7. 👍 or 👎

**Comment by JmillsExpensify** [comment] 2024-07-11 17:53
$250 approved for @mollfpr

**Comment by luacmartins** [comment] 2024-07-11 17:56
We'll add tests as part of the project wrap up, so no need to do that now.

**Closed** 2024-07-12 17:28 UTC
Labels: External, Engineering, Weekly, Internal, Awaiting Payment, Bug
