### ISSUE TITLE
[$500] IOU Distance -  App displays 'Hmm its not here' for default waypoint links for first time after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27571] opened 2023-09-15 23:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open plus and click request money
3. Click on distance and click on start/finish
4. Copy the URL and send to any chat
5. Select any addresses for start and finish and click next
6. Copy the the URL and send to same chat as step 4
7. logout and login again with same user
8. Open chat open in step 4
9. Click on waypoint link and observe that app doesn't handle that link properly and displays 'Hmm its not here' page
10. Click on participant page and observe that app redirects to request money page which is correct way of handling such links

## Expected Result:
 App should redirect back to request money page if we try to open waypoint link first time after login as it does for other similar links like participant link

## Actual Result:
 App displays 'Hmm its not here' for default waypoint links for first time after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/fc3858f2-5b21-491f-81ab-8454b2f7f428

https://github.com/Expensify/App/assets/78819774/7f3fc234-b112-4939-ba5b-6c599e196289

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694588501046099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0150a4f024ff40d29f</li>
        <li>Upwork Job ID: 1702824671417270272</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 01:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays 'Hmm... it's not here' for default waypoint links for the first time after login.

### What is the root cause of that problem?
At the point when the link is clicked immediately after login, the waypointCount is 0, and the FullPageNotFoundView is displayed when this condition is met.

### What changes do you think we should make in order to solve the problem?
Similar to the participants page, add a useEffect hook to navigate back to the distance request page in this situation.

### What alternative solutions did you explore? (Optional)
None.

**Comment by jeet-dhandha** [comment] 2023-09-16 09:06
Wrong slack link. 

Please update the link or close this one out, as there’s an issue with correct link https://github.com/Expensify/App/issues/27572

**Closed** 2023-09-16 17:03 UTC
Labels: External, Daily, Help Wanted, Bug
