### ISSUE TITLE
[$250] Pay someone - Payment is not created when use Pay someone via QAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45200] opened 2024-07-10 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4706795&group_by=cases:section_id&group_id=309127&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a597@gmail.com gocemate+a598@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.chat.expensify.com
2. Click on FAB> Pay someone> Complete the flow
3. Click on FAB> Pay individual via Quick action> Complete the flow

## Expected Result:
Newly created expense should be added to report

## Actual Result:
No update when use Pay someone via QAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8642705f-6e0b-4385-9da8-2b957815ccd3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01265dc1307134818e</li>
        <li>Upwork Job ID: 1812446832412524679</li>
        <li>Last Price Increase: 2024-08-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-07-10 19:04
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by tsa321** [comment] 2024-07-15 06:09
Same root cause as https://github.com/Expensify/App/issues/45093 
Cross posting my [proposal](https://github.com/Expensify/App/issues/45093#issuecomment-2219758931) from the issue.

**Comment by tsa321** [comment] 2024-07-22 00:47
@parasharrajat, it is because:

Here:

https://github.com/Expensify/App/blob/c973e622ac7bf94a537b01e75408aff782123db3/src/pages/home/report/ReportActionsView.tsx#L146-L157

`isFirstLinkedActionRender.current` will always be true whenever the `route` changes. The route changes whenever `report.lastVisibleActionCreated` changes:

https://github.com/Expensify/App/blob/4c235a733928b43ddc9e3a2bb5d96e170d2e0545/src/pages/home/report/ReportActionsList.tsx#L269-L271

<br />

If `isFirstLinkedActionRender.current` is true, it causes the reportActions in here:

https://github.com/Expensify/App/blob/4c235a733928b43ddc9e3a2bb5d96e170d2e0545/src/pages/home/report/ReportActionsView.tsx#L251-L253

to be sliced starting from `reportActionID` of the route, up to the older messages. Consequently, the newer messages are not displayed.

My PR has already been merged, and I am no longer able to reproduce this issue. Could you try reproducing it?

**Closed** 2024-08-08 12:16 UTC
Labels: External, Daily, Help Wanted, Bug
