### ISSUE TITLE
[$250] Split Scan-After several splits new WS split is not visible when created, user needs to scroll

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41842] opened 2024-05-08 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4536973
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the App
2. Navigate to the workspace chat
3. Click on the + button > Split expense
4. On the scan option, upload a digital receipt
5. Create the expense
6. Repeat several times

## Expected Result:
Every time a new split is created, the split preview is displayed at the bottom of the page

## Actual Result:
After several splits are created, the user has to scroll down in order to see the new split preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/393bbeb0-3473-44ca-a99e-64283cb91a0b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ca59a4491705d3c2</li>
        <li>Upwork Job ID: 1789018534325469184</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-05-08 12:53
We think that this bug might be related to #vip-split

**Comment by bfitzexpensify** [comment] 2024-05-17 18:59
This sounds related to https://github.com/Expensify/App/issues/40724. 

Putting a HOLD here until that's fixed, then we can re-test again to confirm this is still an issue.

**Comment by bfitzexpensify** [comment] 2024-05-17 19:27
Commenting to remove overdue label, update is above ^

**Comment by bfitzexpensify** [comment] 2024-05-20 14:36
Still held.

**Comment by bfitzexpensify** [comment] 2024-05-23 15:07
Remains held.

**Comment by bfitzexpensify** [comment] 2024-05-27 14:32
https://github.com/Expensify/App/issues/40724 is progressing, but it's not yet complete, and we're still held on that.

**Comment by bfitzexpensify** [comment] 2024-05-30 13:22
Same update, still held on https://github.com/Expensify/App/issues/40724. 

Adding another BZ team member to this one while I'm OOO. 

@stephanieelliott, these are the next steps: 

- keep checking for progress on https://github.com/Expensify/App/issues/40724
- once that's deployed, ask in #qa for this to be re-tested
- if it's resolved, close it out. If not, we can re-open this to contributors to work on

**Comment by stephanieelliott** [comment] 2024-06-01 02:53
Cool, thanks for the clear steps @bfitzexpensify!

**Comment by stephanieelliott** [comment] 2024-06-11 20:58
Hey @bfitzexpensify looks like the PR for https://github.com/Expensify/App/issues/40724 should be deployed to staging on the next release. Removing my assignment here!

**Comment by bfitzexpensify** [comment] 2024-07-16 15:49
Getting this retested via #qa

**Comment by kavimuru** [comment] 2024-07-16 20:20
Issue is still reproducible

https://github.com/user-attachments/assets/aab5ea5a-f76b-4ed4-b64b-f44b7c5f0101

**Comment by bfitzexpensify** [comment] 2024-07-17 09:29
Okay, I'll take this off hold and switch to Daily. @akinwale, would you mind re-reviewing @jainilparikh's proposal from May?

**Comment by akinwale** [comment] 2024-07-19 04:19
@jainilparikh After reviewing your proposal, why do we have to scroll to the end every time? What exactly is the root cause for the list not scrolling to the end? I think we should try to identify and fix the main cause, instead of implementing a workaround.

**Comment by bfitzexpensify** [comment] 2024-07-23 09:21
Bump @jainilparikh. 

Awaiting other proposals, too.

**Comment by bfitzexpensify** [comment] 2024-07-26 10:36
Still awaiting proposals. We're paused on split, so I don't know that we need to up the $$ bounty here

**Comment by bfitzexpensify** [comment] 2024-07-30 17:39
I'm going to go ahead and close this for the moment as a non-priority that can be revisited in the future.

**Closed by bfitzexpensify** 2024-07-30 17:39 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
