### ISSUE TITLE
mWeb/Safari - Chat - Empty space appears above header after editing comment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40600] opened 2024-04-19 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to 1:1 Chat or WS or group chat
2. Send a series of messages
3. Long press on any previous message
4. Select Edit comment
5. Make some changes to message & tap on send button

## Expected Result:
No blank space appears above chat header after editing comment

## Actual Result:
Empty space appears above header after editing comment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/242ae5bd-9b82-4813-a6ae-9cc63799b8ee

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-19 17:52
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 17:52
We think that this bug might be related to #vip-vsp

**Comment by adelekennedy** [comment] 2024-04-19 21:04
just tested with ios safari staging v1.4.63-11 and couldn't reproduce - closing!

**Closed by adelekennedy** 2024-04-19 21:04 UTC
Labels: Daily, Bug
