### ISSUE TITLE
Expensify card - Success screen shown instead of list accounts and no One more step screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51819] opened 2024-10-31 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** https://github.com/Expensify/App/pull/51407
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51407
## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in
2. Create a workspace if there is no any
3. Navigate to workspace settings and enable Expensify card in More features
4. Open Expensify card and click on the Issue a new card button and add the bank account
5.After the BA is added, close the RHP and click on the Issue a new card button
6. Select the bank account and wait until you get the success screen
7. Create a new workspace and enable the Expensify card option in More features
8. Open Expensify card and click on the Issue a new card
9. Select the bank account and wait until you get the success screen
10. Repeat steps 7-8

## Expected Result:
The lists of account is displayed, and One more screen is displayed after selecting the account

## Actual Result:
The success screen is displayed when selecting Issue a new card in the 3rd workspace, and there is no One more screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/c1edbf51-f7df-437b-8910-726f740159e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-31 17:02
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-31 17:03
Production:

https://github.com/user-attachments/assets/b03bf438-816a-4286-ae6c-557ecf41e092

**Comment by lanitochka17** [comment] 2024-10-31 17:03
We think that this bug might be related to #wave-collect - Release 2

**Comment by tgolen** [comment] 2024-10-31 17:08
@DylanDylann Could you please check if this is a regression related to the changes in https://github.com/Expensify/App/pull/51315?

**Comment by DylanDylann** [comment] 2024-11-01 03:02
@tgolen Dupe https://github.com/Expensify/App/issues/51801

**Comment by tgolen** [comment] 2024-11-01 15:59
OK, thanks! I'll just close this one then.

**Closed by tgolen** 2024-11-01 15:59 UTC
Labels: DeployBlockerCash, Engineering, Hourly
