### ISSUE TITLE
Hybrid Android/iOS - Copilot - Email missing on Let's make sure it's you step

### ISSUE THREAD

**Issue by dangrous** [Expensify/App#52499] opened 2024-11-13 19:30 UTC
**Original GH:** https://github.com/Expensify/App/issues/51284

## Action Performed:
1. Open the app and log in
2. Navigate to the account settings > Security > Add copilot
3. Select an account
4. Select the access level and proceed to the next step
5. Confirm to add copilot

## Expected Result:
The email to which one the magic code was sent is displayed

## Actual Result:
The email to which one the magic code was sent is missing

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
https://github.com/user-attachments/assets/4415e142-c336-4afb-a016-835dd9db51b9

</details>

**Comment by tgolen** [comment] 2024-11-13 21:24
@dangrous thanks for creating this, but it's written from the viewpoint of the UI. Can you please update it to explain the bug in terms of API calls and responses and what exactly needs to be fixed on the backend?

**Comment by MarioExpensify** [comment] 2024-11-15 13:13
@dangrous sorry, I don't think I got it, is this a Mobile-Expensify bug? I think the issue is in the wrong repo then? Not sure how it should work for Mobile-Expensify issues.

I can take a look at it anyways. Just making sure.

**Comment by dangrous** [comment] 2024-11-15 18:23
Yeah I guess I'm a little confused too haha. I was following @tgolen's reco to create a separate internal issue, but maybe we should have this in Expensify/Expensify instead?

**Comment by MarioExpensify** [comment] 2024-11-15 18:39
@dangrous I think so 😅 @tgolen if you can hop in

**Comment by MarioExpensify** [comment] 2024-11-18 20:08
Whoops, it seems this had both daily and weekly tags. Removing daily.

**Comment by dangrous** [comment] 2024-11-21 16:11
Okay cool, so what is the next step on this? @MarioExpensify are you up for investigating this internally? Or @tgolen would you prefer to take over?

**Comment by MarioExpensify** [comment] 2024-11-21 16:46
Hey @dangrous, yes, I will work on this.

**Comment by dangrous** [comment] 2024-11-26 19:11
So I think ND was always working. Let me see if I can replicate on Hybrid, maybe it got fixed by something else? And you were using Hybrid Android, right?

**Comment by dangrous** [comment] 2024-11-26 19:45
oh i guess it happened on iOS too. I can't get android hybrid working with my local server, so im trying ios now

**Comment by dangrous** [comment] 2024-11-26 20:57
IOS looks good! I am truly failing to run android locally in a way that works, do you think we can just close without testing? I don't love it but hopefully it is not different...

**Comment by MarioExpensify** [comment] 2024-11-26 21:57
@dangrous my test was done in Hybrid App Android, it looked good, but I'm sending this ticket to qa in Slack and requesting a retest just to be sure!!

**Comment by MarioExpensify** [comment] 2024-11-28 17:08
@dangrous we got the [QA results](https://expensify.slack.com/archives/C9YU7BX5M/p1732806632646799?thread_ts=1732658292.103259&cid=C9YU7BX5M) back and it seems it is Ok now. I'm closing the ticket but feel free to reopen if this ever comes back!! Thank you

**Closed by MarioExpensify** 2024-11-28 17:08 UTC
Labels: Weekly, Internal, Hot Pick, AutoAssignerNewDotQuality
