### ISSUE TITLE
[$500] Dev: Web - Private notes -  Delay in displaying the "Notes" field and "Save" button when refreshing the Private

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27601] opened 2023-09-16 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the "+" button.
2. Select "Send message" > "Room"
3. Enter a room name and create it.
4. Go to the room "Details" > "Private notes" > "My note"
5. Refresh the page.
6. Notice the "Notes" field and the "Save" button are not displayed instantly when the page loads.

## Expected Result:
The "Notes" field and the "Save" button should be displayed instantly when the Private Notes page is refreshed

## Actual Result:
There is a delay in displaying the "Notes" field and "Save" button after refreshing the Private Notes page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/213aa28d-840d-4a15-85a8-804282b5d9db

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694804254609799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db92551146ef6d80</li>
        <li>Upwork Job ID: 1703134563331903488</li>
        <li>Last Price Increase: 2023-09-23</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-09-17 19:19
I didn't understand @neonbhai's proposal. Generally I would recommend not to copy the title itself in the `Please re-state the problem`.

> The TextInput element [here](https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/PrivateNotes/PrivateNotesEditPage.js#L118-L131) is not configured to save drafts.

Neither does the line, explain the root cause properly.

**Comment by paultsimura** [comment] 2023-09-19 06:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On "Edit private note" page reload, the form is not loaded instantly

### What is the root cause of that problem?
On page refresh, the report is loading into onyx via OpenReport API call. So the form is in loading state until the report is fetched, and therefore it's `null`:

https://github.com/Expensify/react-native-onyx/blob/d6824308f7afa7299502f500d60e9d12b9e119f7/lib/withOnyx.js#L200-L202

### What changes do you think we should make in order to solve the problem?
All the changes should be made in `PrivateNotesEditPage`:

1. Add the following property sync to withOnyx:

```js
        isLoadingReportData: {
            key: ONYXKEYS.IS_LOADING_REPORT_DATA,
        },
```

2. While rendering, early return the loading screen if the report is not ready yet:

```diff
+    if (isLoadingReportData && _.isEmpty(report.reportID)) {
+       return <FullScreenLoadingIndicator />;
+   }

    return (
        <ScreenWrapper
            includeSafeAreaPaddingBottom={false}
            onEntryTransitionEnd={() => focusAndUpdateMultilineInputRange(privateNotesInput.current)}
        >
        ...
```

We are setting the initial value of the form input from the report anyway, so there's no sense showing the form before the report is fetched, that's why the loading screen makes sense here.

Result:

https://github.com/Expensify/App/assets/12595293/09940bec-1b46-47f7-820b-4f01b9115cc0



### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-09-22 00:59
Is this actually a bug? cc @techievivek since I think you implemented this feature. I personally think we can just close this.

**Comment by techievivek** [comment] 2023-09-22 03:47
@tienifr 

> Currently, we have to wait for all data are loaded before showing the component, I don't think it's a good idea because when we register a lot of data to Onyx, we can't use the loaded data until all of them are loaded

This is only true for the `openReport` command data, right? And if I understand correctly the RCA is that when we refresh the page we have to wait for the `OpenReport` command to finish?

**Comment by jliexpensify** [comment] 2023-09-25 08:05
Bumping @techievivek for a review of this [comment](https://github.com/Expensify/App/issues/27601#issuecomment-1730766283).

**Comment by techievivek** [comment] 2023-09-25 09:19
@mananjadhav Can you please review the proposal above? I added myself to the GH to speed up reviews since I wrote the original code.

**Comment by mananjadhav** [comment] 2023-09-25 09:47
Thanks for clarifying @techievivek.

@tienifr's proposal is good [here](https://github.com/Expensify/App/issues/27601#issuecomment-1723244179).

🎀 👀 🎀 C+ reviewed.

**Comment by techievivek** [comment] 2023-09-27 02:47
@tienifr Quick question, is this a common practice to add the loading indicator when waiting for onyx updates to be done in our App? Or is there something fundamental wrong about this and should we instead try to fix that? Maybe we can check to see if we can use selector to only get the required data?

**Comment by techievivek** [comment] 2023-09-27 02:49
I agree that this is something we can definitely improve but I want to first figure out what would be the best way to do that? And how we handled such situations for other pages/components.

**Comment by techievivek** [comment] 2023-09-27 03:53
But we don't need to wait for all the states, right? As long as the required keys are not loaded we cannot move forward and that's what this piece of code is doing.

```
// All state keys should exist and at least have a value of null
if (_.some(requiredKeysForInit, key => _.isUndefined(this.tempState[key]))) {
    return;
}
```

Also, looking at your proposal

<blockquote>
In withOnyx lib, we wait the data is loaded before returning the WrappedComponent

https://github.com/Expensify/react-native-onyx/blob/d6824308f7afa7299502f500d60e9d12b9e119f7/lib/withOnyx.js#L200-L202


</blockquote>

So in this case we are loading for form-related data to load but these are not even fetched from the network so why is it taking it a long time to get those data? Or is it the onyx keys in the `PrivateNotesEditPage` that is causing the delay as we have refreshed the page?

```
withOnyx({
    report: {
        key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${route.params.reportID.toString()}`,
    },
    session: {
        key: ONYXKEYS.SESSION,
    },
    personalDetailsList: {
        key: ONYXKEYS.PERSONAL_DETAILS_LIST,
    },
}),
```

**Comment by techievivek** [comment] 2023-09-27 03:55
> So I believe isLoading:false does not mean all states are loaded -> using isLoading in [this place](https://github.com/Expensify/react-native-onyx/blob/d6824308f7afa7299502f500d60e9d12b9e119f7/lib/withOnyx.js#L200-L202) can be meaningless

It does mean that all the states(i.e. required keys are loaded), that's why I am not sure if we can get rid of it tho we are later omitting the null values.

**Comment by techievivek** [comment] 2023-09-27 03:57
I think @paultsimura proposal over here https://github.com/Expensify/App/issues/27601#issuecomment-1724904070 makes more sense. @mananjadhav Can you please share your thoughts on the above discussion.

**Comment by techievivek** [comment] 2023-10-02 11:12
For now, we will close this as we do not consider it a high-priority bug. However, if you are interested, please feel free to create an RCA with some profiling so we can understand the seriousness of the issue and look for a fix.

**Closed by techievivek** 2023-10-02 11:12 UTC
Labels: External, Daily, Help Wanted, Overdue
