### ISSUE TITLE
Web - App keeps reloading after rejoining a public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22471] opened 2023-07-08 11:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
CASE 1:
1. Login to an account
2. Join a public room, eg: SNH - https://staging.new.expensify.com/r/5303403427249671
3. Leave the room
4. Access the room’s link again >> It will re-join the room
5. Wait and see how the app behaves
-------------
CASE 2:
1. Login to an account
2. Join a public room, eg: SNH - https://staging.new.expensify.com/r/5303403427249671
3. Leave the room
4. Press back on the browser >> “Hm.. it’s not here” display
5. Reload the browser >> It will re-join the room
6. Wait and see how the app behaves

## Expected Result:
The app shouldn’t auto-reload

## Actual Result:
The app keeps reloading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-6
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c19dbdfb-a87b-4e84-b2a8-1c1960320c04

https://github.com/Expensify/App/assets/93399543/d9fa89e7-821b-49d9-a783-ac33404dfbd5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1688701562983339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Ahmed-Abdella** [comment] 2023-07-08 14:20
Hey @kevinksullivan 
I sent at contributors@expensify.com asking for Slack Channel Invites, and I provide my upwork profile link, but I didn't get the Invites yet.
is there a problem or anything should I add ?
Thanks.

**Comment by kevinksullivan** [comment] 2023-07-10 17:32
can't reproduce. Closing and asking in slack

https://recordit.co/bwH719b7Cq

**Closed by kevinksullivan** 2023-07-10 17:32 UTC
Labels: Daily, Needs Reproduction, Bug
