### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] Android - Quickly pressing different menu items in WS Options opens them one by one

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27384] opened 2023-09-13 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open RHS, click on workspaces open any workspace.
2. Quickly press  different menu items.

## Expected Result:
Only first option should be open other click ignores (same as settings page and LHN)

## Actual Result:
The app opens all the clicked options

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/37d12c1b-2cd8-44f9-80fc-aa3d626339e6

https://github.com/Expensify/App/assets/93399543/086512d6-8239-4a8f-a8bb-d72c0f9b51b3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694431310368759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013563910034c3c70d</li>
        <li>Upwork Job ID: 1702024671852146688</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 27096906</li>
<li>ishpaul777 | Reporter | 27096909</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-13 18:30
### Proposal 

### Problem 
Quickly pressing different menu items in WS Options opens them one by one

### Root Cause 
We are allowing other action when a action is already in progress in workspace.

### Changes
We can use `useSingleExecution` hook along with `useWaitForNavigation` to ignore the other action when navigation in progress, similar to what we have done in [InitialSettingsPage](https://github.com/ishpaul777/App/blob/62e2a0c5609f575bd8a770acbccef6485406456e/src/pages/settings/InitialSettingsPage.js)

**Comment by CortneyOfstad** [comment] 2023-09-14 19:02
@michaelhaxhiu There is a known issue (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)) with duplicate assignees. Unassigning you 👍

**Comment by CortneyOfstad** [comment] 2023-09-18 13:25
@robertKozik Any thoughts on the proposal above? TIA!

**Comment by robertKozik** [comment] 2023-09-20 08:21
Hi @ishpaul777, thank you for your proposal, I think it should solve issue completely as we are using `useSingleExecution` in other places for similar use cases. 
🎀 👀 🎀 C+ reviewed

**Comment by CortneyOfstad** [comment] 2023-09-22 12:30
No update 👍

**Comment by MonilBhavsar** [comment] 2023-09-25 06:21
Reviewing this now...

**Comment by MonilBhavsar** [comment] 2023-09-25 06:40
Looks good to me, thanks!
A thought - Should we check and implement `useSingleExecution` for every other page, and not just Workspace settings?

**Comment by robertKozik** [comment] 2023-09-25 07:12
Yeah, that's a possibility. We could create a wrapper for rendering multiple menu items and implement the `useSingleExecution` logic there. This way, we can avoid code repetition. We might encounter similar mapping for rendering in files like `FeatureList.js`, `AppDownloadLinks.js`, `AboutPage.js`, `FeatureList.js`, `SecuritySettingsPage.js` so they can suffer for simmilar problems

**Comment by MonilBhavsar** [comment] 2023-09-26 04:54
I agree with that and love the idea of wrapping multiple similar items and avoiding code deduplication 👍 
@ishpaul777 we would love to have a wrapper instead of duplicating code.

**Comment by ishpaul777** [comment] 2023-09-26 08:19
HI @MonilBhavsar @robertKozik, I haven't tried it yet but What if we use singleExecution on root MenuItem Component?

**Comment by MonilBhavsar** [comment] 2023-09-27 06:19
Sounds good. But worth testing it as it is a base component. Would love to hear what @robertKozik thinks

**Comment by robertKozik** [comment] 2023-09-27 12:49
I believe it won't work unless I'm missing something. We need to share the same useSingleExecution hook across all menuItem components as we need to have the same isExecuting state. Calling the hook on every instance of the menuItem separately won't achieve the desired outcome. Additionally, I've checked that we have a similar wrapper-like component, MenuItemList.js, which we can use for this purpose.

**Comment by ishpaul777** [comment] 2023-09-27 18:12
Yes, you are right! I have raised draft PR implementing changes for workspace Options, let me know if I am in right direction, and what other pages I need to make the change.

**Comment by MonilBhavsar** [comment] 2023-09-29 05:50
@ishpaul777 do you mind sharing the proposal first

**Comment by MonilBhavsar** [comment] 2023-10-02 15:53
> Also can I get a list for all the pages where we want this change to be implemented?

Here are some pages mentioned above
WorkspaeInitalPage, FeatureList.js, AppDownloadLinks.js, AboutPage.js, FeatureList.js, SecuritySettingsPage.js

**Comment by MonilBhavsar** [comment] 2023-10-02 15:53
@robertKozik could you please take look at the plan above, thanks!

**Comment by robertKozik** [comment] 2023-10-04 11:26
> Sorry for delay, So basically we are going to use the MenuItemList component and pass a extra prop `shouldUseSingleExecutionOnPress` and implement `onPress` and other props for each MenuItem like below
> 
> ```
>                  <MenuItem
>                     // other props
>                     {...menuItemProps}
>                     disabled={menuItemProps.disabled || isExecuting}
>                     onPress={props.shouldUseSingleExecution ? singleExecution(waitForNavigate(menuItemProps.onPress)) : 
>                     menuItemProps.onPress}
>                  />
> ```
> 
> Also can I get a list for all the pages where we want this change to be implemented?

I like the plan, but I'm not the fan of inserting `waitForNavigate` here as well. I can imagine that not all MenuItem would lead to navigation action. I would opt for let `shouldUseSingleExecution` and `singleExecution` combo stay, and let decide on `waitForNavigate` on the higher component level

**Comment by MonilBhavsar** [comment] 2023-10-04 18:45
@ishpaul777 if you want to share the more detailed proposal

**Comment by CortneyOfstad** [comment] 2023-10-05 17:41
@MonilBhavsar @robertKozik thoughts on the proposal above^^^ thanks!

**Comment by MonilBhavsar** [comment] 2023-10-09 08:20
@robertKozik could you please take a look at the proposal, thanks!

**Comment by robertKozik** [comment] 2023-10-09 08:37
@MonilBhavsar I'm OK with the proposal provided by @ishpaul777. I think we can go with it, and test it in action

**Comment by MonilBhavsar** [comment] 2023-10-09 08:46
Thanks! Looks good to me too 👍

**Comment by CortneyOfstad** [comment] 2023-10-18 20:04
Heading OoO until Oct. 25, so reassigning BZ to keep an eye on things while I am gone 👍

**Comment by CortneyOfstad** [comment] 2023-10-25 17:24
I'm back @zanyrenney, so I can take this back over — thanks for holding down the fort while I was gone!

**Comment by robertKozik** [comment] 2023-10-31 03:51
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **N/A**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think we need to create the regression test for this one. No crucial user flow was affected by this bug**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by zanyrenney** [comment] 2023-11-02 16:53
unassigning as @CortneyOfstad is back.

**Comment by CortneyOfstad** [comment] 2023-11-02 20:41
Payments made and checklist completed — closing!

**Closed by CortneyOfstad** 2023-11-02 20:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
