### ISSUE TITLE
 [HOLD for Payment 2024-08-22][$250] Task – Hmm page opens if delete task as assignee (external group user)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45474] opened 2024-07-16 12:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4723403
**Email or phone of affected tester (no customers):** applausetester+jpcategory_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in as user A
3. Open group chat where user B is not a member
4. Create a task and assign to user B
5. Log in as user B and open task details
6. Click on header and delete the task

## Expected Result:
Hmm page... should not be displayed

## Actual Result:
Hmm… page opens if delete task as assignee who is an external group user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d5b5cdf5-b44a-4c58-8a93-f0549b94f18a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b06031bca998734c</li>
        <li>Upwork Job ID: 1813239283855139404</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103430949</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-07-16 12:51
@lschurr  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-16 12:54
We think that this bug might be related to #vip-vsp

**Comment by amunim** [comment] 2024-07-16 14:05
Updated [proposal](https://github.com/Expensify/App/issues/45474#issuecomment-2230856232) @abzokhattab

**Comment by bernhardoj** [comment] 2024-07-16 14:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page shows when deleting a task report that is shared in a group chat that the user is not a member.

### What is the root cause of that problem?
If we are deleting a task, we will navigate back to the parent report.
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/libs/actions/Task.ts#L1058-L1060

However, when we are not part of the parent report members, the parent report will be undefined and the reportID will be default to -1, thus the user is navigated to a report with ID of -1 and the not found page is shown.

### What changes do you think we should make in order to solve the problem?

Only navigate to the parent report if the reportID exists, otherwise, we can navigate to concierge or the most recent report.
```
if (shouldDeleteTaskReport) {
    if (parentReport?.reportID) {
        Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReport.reportID));
        return;
    }
    Report.navigateToMostRecentReport(report);
}
```

OR

A more complex solution is to navigate back to the assignee report by taking the `report.managerID` and search the report using `ReportUtils.getChatByParticipants` and if it's still empty, then we go to the most recent report.

**Comment by FitseTLT** [comment] 2024-07-16 14:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page shows when deleting a task report that is shared in a group chat that the user is not a member.


### What is the root cause of that problem?
We are navigating to the parent report after deleting task here
https://github.com/Expensify/App/blob/1465a9294f5ff357fb30f55c1e90df791c73cd29/src/libs/actions/Task.ts#L1059-L1060 
but `parentReport` doesn't exist as the user doesn't belong to the group 
### What changes do you think we should make in order to solve the problem?

We need to just `goBack` for cases where `parentReport` does not exist
```
        Navigation.goBack(parentReport?.reportID ? ROUTES.REPORT_WITH_ID.getRoute(parentReport?.reportID) : undefined);

```

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-07-16 15:49
I will review the proposals in a moment.

**Comment by brunovjk** [comment] 2024-07-16 21:13
Thank you @amunim and @bernhardoj for the proposals, your RCA looks similar. I tested both solutions and I preferred @amunim's [proposal](https://github.com/Expensify/App/issues/45474#issuecomment-2230856232): adding a fallback to `report?.reportID` if `parentReport?.reportID` is not available worked better here.
I will trigger an internal to verify and also check this [comment](https://github.com/Expensify/App/issues/45474#issuecomment-2230972691)

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-07-16 21:14
@MonilBhavsar, Do you confirm this [comment](https://github.com/Expensify/App/issues/45474#issuecomment-2230972691)?

**Comment by MonilBhavsar** [comment] 2024-07-18 07:30
I'll check and confirm here. Thank you!

**Comment by brunovjk** [comment] 2024-07-19 13:14
Thank you @MonilBhavsar

**Comment by brunovjk** [comment] 2024-07-22 11:00
Not overdue, working on an internal solution.

**Comment by brunovjk** [comment] 2024-07-22 11:03
Not overdue, working [internally](https://github.com/Expensify/App/issues/45474#issuecomment-2239096744).

**Comment by MonilBhavsar** [comment] 2024-07-22 11:12
I'm working on it. Should have PR up by today, I believe

**Comment by lschurr** [comment] 2024-07-25 19:54
Just a bump on this one @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-07-26 05:55
Yeah, on it. Just got a bit distracted by critical fast-api's issue

**Comment by MonilBhavsar** [comment] 2024-07-26 05:58
Yeah, on it. Just got a bit distracted by critical fast-api's issue

**Comment by MonilBhavsar** [comment] 2024-07-29 11:00
Working on this. I think updating the parentReportID for task reports in this case is not a good idea. It broke some automated tests. I think it will be better to fix this in client side since it's not a major use case. I'll update here soon - the best path ahead

**Comment by MonilBhavsar** [comment] 2024-08-05 12:17
Same^

**Comment by MonilBhavsar** [comment] 2024-08-07 07:39
Hey all!
We have discussed internally and decided to fix this issue on client side.

@bernhardoj in your proposal to redirect to last visited report. Is it the chat report report between task creator and assignee?
If possible can you share the POC please?

**Comment by bernhardoj** [comment] 2024-08-07 09:05
> Is it the chat report report between task creator and assignee?

If the chat report (DM) is the last visited report, then yes. Here is the comparison of the solution:

1. Open the chat report where the task is shared
2. Open the task report
3. Delete the task
4. Navigated back to the chat report

https://github.com/user-attachments/assets/f061fd8c-dc5b-4b6d-93e6-c404ea968bc3


1. Open another report that doesn't have the task shared
2. Open the task report
3. Delete the task
4. Navigated back to the report in step 1

https://github.com/user-attachments/assets/69bc29dc-da77-4bcc-b70f-a3b43242a6a9

Here is the test branch: https://github.com/bernhardoj/Expensify/tree/fix/45474-delete-task-show-not-found

I've also updated my [proposal](https://github.com/Expensify/App/issues/45474#issuecomment-2230990214) since there is a change to the current codebase.

**Comment by MonilBhavsar** [comment] 2024-08-07 09:24
Thank you for sharing!

I know this is a close call and only difference in the proposals is the report we're redirecting to, after deleting a task.
In this case, redirecting to recently visited report makes sense, as it would be a chat report where task was shared, in most cases, except visiting through link.

Thanks all for the proposals!

**Comment by brunovjk** [comment] 2024-08-21 12:40
> [!NOTE]  
> The production deploy automation failed: This should be on **[HOLD for Payment 2024-08-22]** according to https://github.com/Expensify/App/issues/47356 prod deploy checklist, confirmed in https://github.com/Expensify/App/pull/46950#issuecomment-2294136303.

cc: @lschurr

**Comment by brunovjk** [comment] 2024-08-26 11:21
Hey @lschurr, just a heads up that the payment for this issue is still pending. When you have a moment, could you help process it so we can close this out? Appreciate it!

**Comment by lschurr** [comment] 2024-08-26 18:02
Thanks for the bump @brunovjk!

Payment summary:

- Contributor: $250 @bernhardoj (please request via NewDot)
- Reviewer: $250 @brunovjk ([Paid in Upwork](https://www.upwork.com/nx/wm/workroom/38031713/overview?nav_dir=pop))

**Closed** 2024-08-26 18:04 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-08-27 02:30
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-28 17:26
$250 approved for @bernhardoj
