### ISSUE TITLE
[HOLD for payment][$1000] Chat -  "Report no longer exists" message upon removing image that has deleted thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19559] opened 2023-05-24 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Send an image to a chat
3. Make a thread on that message using Reply in thread
4. From the thread chat, leave the thread by Details > Leave thread
5. Delete the image

## Expected Result:
Image removed successfully without any error

## Actual Result:
 Empty image returned with the error "Report no longer exists" after deletion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/63911b09-8869-4dbc-a129-70e0be560e92

https://github.com/Expensify/App/assets/93399543/6ad7a660-4b0e-40fc-b81e-6948839dec79

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684468035059069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170002ec496e4cb5d</li>
        <li>Upwork Job ID: 1661664481181433856</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-05-25 09:24
Nice, all reproduced

<img width="666" alt="image" src="https://github.com/Expensify/App/assets/5802477/95768da6-1dd5-4e16-9f55-18df64d9500c">

**Comment by conorpendergrast** [comment] 2023-05-25 09:25
Reproduced on Staging **and** Production, by the way

**Comment by JavSFDev** [comment] 2023-05-25 11:49
I think rendering doesn't seem to work reliably.
Leave this problem to me and I will fix it.

**Comment by DanutGavrus** [comment] 2023-05-25 12:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty image returned with the error "Report no longer exists" after deletion.

### What is the root cause of that problem?
After creating & leaving the thread, then deleting the attachment
<details>
<summary>the back-end responds with:</summary>
<img src="https://github.com/Expensify/App/assets/56603839/a55c25be-025d-401c-82cb-894a00453783">
<img src="https://github.com/Expensify/App/assets/56603839/91124de3-1ead-4346-a8aa-805632b3385f">
</details>  

So, we update Onyx with the `failure data`.  

* We still see the message _after refreshing the page_.  
* We __don't__ see the message _after deleting the data in the Onyx database, and then refresh the page_.

It looks like even though the back-end responds with this data, the attachment is actually deleted, so after deleting the data in the local database & refreshing the page, the message dissapears.

### What changes do you think we should make in order to solve the problem?
Have someone from back-end investigate step by step the call for this case in order to see where the problem occurs.

**Comment by cristipaval** [comment] 2023-05-29 16:38
I think this issue might have the same root cause as [this one](https://github.com/Expensify/App/issues/19078). Maybe we could put it on hold and test it again when the other one gets fixed? What do you think @mananjadhav ?

**Comment by mananjadhav** [comment] 2023-05-29 23:14
Yeah I agree, we should put this one on Hold.

**Comment by conorpendergrast** [comment] 2023-05-30 08:45
On hold for https://github.com/Expensify/App/issues/19078!

**Comment by Christinadobrzyn** [comment] 2023-05-30 16:11
Similar issue reported here - https://github.com/Expensify/App/issues/19707 - do you think we could combine these into one job? cc @mananjadhav @cristipaval

**Comment by cristipaval** [comment] 2023-05-30 19:44
The issues are different, but they might have the same root cause. My recommendation is to also put yours on hold for [this one](https://github.com/Expensify/App/issues/19078). What do you @mananjadhav think?

**Comment by cristipaval** [comment] 2023-06-02 10:38
Still on hold.

**Comment by conorpendergrast** [comment] 2023-06-02 11:42
Moving to Weekly given that this is on hold

**Comment by cristipaval** [comment] 2023-06-12 09:29
No more on hold, and still reproducible.

**Comment by cristipaval** [comment] 2023-06-12 09:33
This one should be fixed internally.

**Comment by DanutGavrus** [comment] 2023-06-12 10:20
@cristipaval If it's going to be fixed _internally_ and the fix will be related to this [Proposal](https://github.com/Expensify/App/issues/19559#issuecomment-1562848511), will it matter?
Asking out of curiosity, thank you!

**Comment by conorpendergrast** [comment] 2023-06-15 11:34
https://github.com/Expensify/App/issues/19078 is on production, so we can move forward with this!

**Comment by cristipaval** [comment] 2023-06-15 21:56
@chiragsalian I need your inpout here.

I did some investigation and it happens as following:
1. The user leaves the thread, which means that their authToken is not authorized anymore to access the `childReport`
2. The user then deletes the `reportAction`, this operation succeeds, but then in Web-E [here](https://github.com/Expensify/Web-Expensify/blob/4a8263138e8ee60ff5f2b8b17aa7cb2e8279c7b9/lib/ReportAPI.php#L674), we want to send updates to the participants of the `childReport`, updates with the change on the parent `reportAction`
3. Because the `authToken` can't access the `childReport` (due to step 1) for getting the `getNotifiableParticipantAccountIDs`, Pusher sends updates with the error thrown, because the `childReport` couldn't be accessed by the user `authToken`

**Comment by chiragsalian** [comment] 2023-06-15 23:13
Interesting, the most straightforward way I can think of solving this is by moving `getNotifiableParticipantAccountIDs` to auth. It would be so much cleaner this way versus wondering if the user has access to report or not.

**Comment by cristipaval** [comment] 2023-06-16 08:22
I thought about something similar. I thought that we might want to return the `notifiableParticipantAccoundIDs` in the response to the `UpdateReportComment` auth command.

**Comment by cristipaval** [comment] 2023-06-16 08:23
I'll work on this today.

**Comment by cristipaval** [comment] 2023-06-16 15:19
I don't think we'll need App changes for this one, so I don't think we need @mananjadhav to review. I'll keep you posted.

(fix might be ready for review early next week because today I jumped to help on the super urgent SNH tasks)

**Comment by conorpendergrast** [comment] 2023-06-16 15:34
Ok, thanks Cristi! Let me know, and then unassign and I'll retract the contract 👍

**Comment by conorpendergrast** [comment] 2023-06-19 12:01
Cristi is getting to work on this, this week!

**Comment by cristipaval** [comment] 2023-06-19 22:56
Alright, 2 draft PRs created, [one for Auth](https://github.com/Expensify/Auth/pull/8145) and [one for Web-E](https://github.com/Expensify/Web-Expensify/pull/37878). I'll make them ready tomorrow after testing a bit more.

**Comment by cristipaval** [comment] 2023-06-21 22:12
oh, ok... I'll make the PRs ready asap.

**Comment by cristipaval** [comment] 2023-06-21 22:17
Ok, PRs are ready for review.

**Comment by conorpendergrast** [comment] 2023-06-23 09:16
Adding Reviewing as the auth PR is under review and the /App PR is on hold until that's done!

**Comment by cristipaval** [comment] 2023-06-23 09:59
Removing @mananjadhav because the fix is implemented in [Auth](https://github.com/Expensify/Auth/pull/8145) and [Web-E](https://github.com/Expensify/Web-Expensify/pull/37878)

**Comment by conorpendergrast** [comment] 2023-06-27 09:45
Thanks! In Upwork, I've ended the contract for @mananjadhav without payment

**Comment by cristipaval** [comment] 2023-06-27 14:41
FYI @conorpendergrast: The PRs are still in review because @chiragsalian pointed out that my solution is not complete.
I will continue on this one tomorrow as I am trying to finish my work on wave3 today.

**Comment by cristipaval** [comment] 2023-07-05 10:25
I am working today on the requested changes on the PR.

**Comment by conorpendergrast** [comment] 2023-07-11 14:49
How's this going @cristipaval ?

**Comment by conorpendergrast** [comment] 2023-07-11 16:10
Nice, thanks for that @cristipaval!

**Comment by cristipaval** [comment] 2023-07-24 18:15
No update on this one, I was ooo last week.

**Comment by johncschuster** [comment] 2023-07-30 17:42
@cristipaval can we get a little update on this one? I have [an issue](https://github.com/Expensify/App/issues/19707) that seems to be dependent on the fix for this issue.

**Comment by cristipaval** [comment] 2023-08-01 22:54
[Auth PR](https://github.com/Expensify/Auth/pull/8145) is ready for review again.

**Comment by conorpendergrast** [comment] 2023-08-03 12:10
I see the auth PR is waiting for review from Bobby

**Comment by conorpendergrast** [comment] 2023-08-08 10:08
PR review is ongoing!

**Comment by cristipaval** [comment] 2023-08-22 20:37
I knoooooow Melvin! I'm heads-down on SmartScan at Saastr these days. I really wish I could continue pushing this a bit this week.

**Comment by conorpendergrast** [comment] 2023-09-05 11:05
Cristi is still focused on Saastr, and I'm sure he'll get to this after that :)

**Comment by conorpendergrast** [comment] 2023-09-11 11:36
@anmurali I'm on parental leave; re-assigning! This has been triaged and Cristi is working on it as an internal fix

**Comment by cristipaval** [comment] 2023-09-21 00:20
Both Auth and Web-E PRs for this are ready for review again (finally, I know 😢 )

**Comment by cristipaval** [comment] 2023-10-03 19:59
The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/37878) is in production now, so this should be closed after we pay the reporting bonus to @kerupuksambel. It's the old amount, 250$, @anmurali.

**Comment by cristipaval** [comment] 2023-10-06 21:01
friendly bump, @anmurali

**Comment by cristipaval** [comment] 2023-10-09 21:32
👀

**Comment by cristipaval** [comment] 2023-10-16 14:28
I'll ping @anmurali internally. She was ooo last Friday that's why I think this one got delayed.

**Comment by cristipaval** [comment] 2023-10-23 11:03
@conorpendergrast, could you please handle the payment here? 🙏  I discussed with @anmurali on NewDot and she is swamped these days.

**Comment by cristipaval** [comment] 2023-10-23 11:03
> The [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/37878) is in production now, so this should be closed after we pay the reporting bonus to @kerupuksambel. It's the old amount, 250$, @anmurali.

This is the only payment due here, @conorpendergrast.

**Comment by conorpendergrast** [comment] 2023-10-23 11:29
Absolutely!

**Comment by conorpendergrast** [comment] 2023-10-23 11:30
Paid and contract ended. Good to close @cristipaval ?

**Closed** 2023-10-23 11:59 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
