### ISSUE TITLE
[$500] Web - Persistence of Tax Selection When Navigating to Other Pages and Returning

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39492] opened 2024-04-03 13:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.59-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
, Go to Settings > Profile > Workspace.
2, Open workspace and access "More Features" to enable taxes.
3, Select taxes from the list.
4, Navigate to another section.
5, Return to the previous section.

## Expected Result:
Taxes should be deselected automatically upon navigating away and back.

## Actual Result:
Selected taxes persist even after navigating to another section and returning, causing inconsistency between sections

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/42d40df6-c7a7-412a-bd0b-0686cc170073

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167f336d9308b4e85</li>
        <li>Upwork Job ID: 1775671638527598592</li>
        <li>Last Price Increase: 2024-04-03</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-03 13:07
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-03 13:08
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by s77rt** [comment] 2024-04-04 01:43
@Krishna2323 Thanks for the proposal. Your RCA is correct. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/39492#issuecomment-2034659328)

**Comment by s77rt** [comment] 2024-04-04 01:46
@GandalfGwaihir Thanks for the proposal. Your RCA is not correct. Calling the API has no effect on the selected options and the bug affects the categories page as well 


https://github.com/Expensify/App/assets/16493223/4a02e1f6-89ee-4d0c-ba50-e91a43a3b266

**Comment by mountiny** [comment] 2024-04-05 13:10
I agree with Tom, this was not designed this way and I dont think we want to build logic to support this. The selection should remain if you navigate to the RHP on the table list page, but not if you go to different page in the central pane.

We should close this

**Comment by trjExpensify** [comment] 2024-04-05 14:16
Okay, agreed, so I think we can use this issue to do this: 

- If you bulk select values in the table and navigate away from the page, deselect them all
- If you bulk select values in the table, and then click an individual value on the page to open the RHP, deselect them all 

On that second one @mountiny, I think we should deselect them because the user has taken an action on the page to do something else at that point. 👍

**Comment by mountiny** [comment] 2024-04-05 14:17
I agree, I forgot we had this on purpose 👍

**Comment by hayata-suenaga** [comment] 2024-04-05 16:53
There appears to have been some confusion about the original bug.

The initial issue is that multiple selections are NOT cleared when the user navigates away from the screen.

Just to clarify, is my understanding correct that we still want to address the original issue as described? In other words, are we looking to clear the multiple-selection when the user navigates away from the screen?

**Comment by trjExpensify** [comment] 2024-04-05 18:43
Yep, we want to do this consistently on all the workspace settings pages with bulk select on a table: 

> - If you bulk select values in the table and navigate away from the page, deselect them all
> - If you bulk select values in the table, and then click an individual value on the page to open the RHP, deselect them all

**Comment by hayata-suenaga** [comment] 2024-04-08 16:28
okay let's fix all workspace settings pages where we have tables with your solution @Krishna2323

**Comment by jayeshmangwani** [comment] 2024-05-08 12:10
@Krishna2323 Changes caused a regression,

1. Go to Workspaces > Go to any collect workspace
2. Go to Categories > Select a Few Categories
3. Now Press on any of the category
4. Previously Selected Categories are unselected

https://github.com/Expensify/App/assets/35371050/1ec1f7df-b2dc-4512-b748-837ce1f5140b

**Comment by s77rt** [comment] 2024-05-08 12:25
@jayeshmangwani That's the expected behaviour

**Comment by jayeshmangwani** [comment] 2024-05-08 12:29
Oh, sorry for the confusion; I thought it was a bug that previously selected categories were gone; please ignore it if thats expected behaviour.

**Comment by strepanier03** [comment] 2024-05-10 16:16
Sorry for missing this, the failed automation caused this to fall through the cracks.

**Comment by strepanier03** [comment] 2024-05-10 18:08
@Krishna2323 @s77rt - The job in Upwork had expired so I needed to make a new one and hire you both again. I just sent offers and will check again in a few hours.

**Comment by strepanier03** [comment] 2024-05-10 21:08
Great, thank you both, finishing up now.

In the future, since you can't update the labels or the title, feel free to ping me earlier for payment issues that fail automation. Failed automation = black hole for issues, sorry about that.

**Comment by strepanier03** [comment] 2024-05-10 21:15
Contracts paid and closed. Thanks again, and apologies for the long delay.

**Closed by strepanier03** 2024-05-10 21:15 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by uzairusman1425** [comment] 2024-05-10 23:40
Cause of the issue:

The issue you are facing is because the default behaviour of stack navigation, when you select certain checkboxes on your “Taxes” screen it is stored in the state of the component and when you move to a different screen the stack navigation pushes the “Taxes” screen on to the navigation stack and the newer screen gets mounted and displayed, and what happens to the “Taxes” screen is that in never gets unmounted and is saved with it’s current state in the navigation stack. And when you move back to your “Taxes” screen it pops the “Taxes” screen back from the navigation stack and as it never got unmounted it displays again with it’s previous state and same checkboxes will still be selected. That’s just the default behaviour to the stack navigation.

Ideal solution of the issue:

The best solution in my opinion is that we should use “useIsFocused” hook from “react-navigation” what it does is that when the screen is in focus(being displayed) it returns a value of “true” which you can use in “useEffect” hook from “react” to check when the screen is popped from the navigation stack and comes into the focus and we can then update the state of the checkboxes to their initial state.

**Comment by s77rt** [comment] 2024-05-11 11:44
@uzairusman1425 Thanks for your interest! This issue is not open for proposals as it's already fixed. Please checkout [issues with Help Wanted label](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22) where you can post a proposal. You should also check the contributing guide (linked in the comment above)

**Comment by mariapeever** [comment] 2024-05-11 16:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected taxes remain selected after navigating to other pages from the tax selection page.

### What is the root cause of that problem?
The selected tax ids state variable is not reset on navigating away from the tax selection page.

### What changes do you think we should make in order to solve the problem?

#### Solution 1 (local)
Use a reset state variable (useState) set to true when navigating away from the tax selection page. Call a reset function to reset the selected Tax IDs if reset is set to true in a useEffect hook with the reset state as a dependency (WorkspaceTaxesPage).

#### Solution 2 (global)
Add a callback function to the navigate method of Navigate (if a callback is required for other components/pages too) to reset the required state variables on navigate.

**Comment by mariapeever** [comment] 2024-05-11 17:14
Contributor details
Your Expensify account email: hello@mariapeever.com
Upwork Profile Link: https://www.upwork.com/freelancers/mariapeever

**Comment by s77rt** [comment] 2024-05-12 04:39
@mariapeever Please check my comment above
