### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Xero - Last sync time is incorrect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48709] opened 2024-09-06 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4933416&group_by=cases:section_id&group_id=309134&group_order=asc&group_by=cases:section_id&group_id=309134&group_order=asc
**Email or phone of affected tester (no customers):** applausetester+gm103086@applause.expensifail.com
**Issue reported by:**Applause - Internal Team

## Action Performed:
1. Navigate to Accounting
2. Click on the connect button next to Xero> Complete the flow
3. Take a look at "Last sync" section
4. Click on 3-Dot menu over Xero> Sync now
5. Take a look at "Last sync" section

## Expected Result:
Last sync should reflect the correct syncing time

## Actual Result:
Last sync time is incorrect and can not be updated

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/802fc6d1-e0f1-4475-b9c6-7d8b3cd89639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021832154630449428811</li>
        <li>Upwork Job ID: 1832154630449428811</li>
        <li>Last Price Increase: 2024-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 104005047</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment] 2024-09-06 13:03
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-09-06 13:03
We think that this bug might be related to #wave-collect - Release 2

**Comment by puneetlath** [comment] 2024-09-06 20:31
Maybe a timezone issue? (just a guess)

**Comment by trjExpensify** [comment] 2024-09-10 01:27
CC: @hungvu193 @mananjadhav for eyes. 👀

**Comment by hungvu193** [comment] 2024-09-10 05:12
Looks like a BE issue but I'll take a look later today

**Comment by hungvu193** [comment] 2024-09-10 06:56
Its fixed I believe @trjExpensify 

https://github.com/user-attachments/assets/bf1a2a3d-38a3-44cb-838f-d39fb4ab5465

**Comment by trjExpensify** [comment] 2024-09-10 10:03
Interesting okay, so let's close this then.

**Comment by IuliiaHerets** [comment] 2024-09-17 07:49
QA team still can repro this issue for NetSuite and Xero connection, build - v9.0.36-1
![image (238)](https://github.com/user-attachments/assets/748c2a07-ad41-4e97-b191-76de59120a79)
![image (237)](https://github.com/user-attachments/assets/879a2b46-8a48-4ca0-a001-791ec1b6d50e)

https://github.com/user-attachments/assets/bb490a20-9f0d-48c1-acc3-55abe0faa85d

**Comment by zfurtak** [comment] 2024-09-17 16:50
Hello, I am Zuza from swm agency and I'd like to work on this issue 😊

**Comment by zfurtak** [comment] 2024-09-18 15:57
@IuliiaHerets @lanitochka17 
If you see the bug, could you check in your profile settings if the timezone is set correctly?

**Comment by IuliiaHerets** [comment] 2024-09-19 06:32
@zfurtak Issue is still repro, the tester's automatically timezone is Europe/Warsaw, but he is located in Macedonia
![image (239)](https://github.com/user-attachments/assets/96fb660d-f96b-48aa-a3bd-8fa212f77bec)

https://github.com/user-attachments/assets/954ee0b2-a4dc-4a9e-8cd5-c99a91118891

**Comment by zfurtak** [comment] 2024-09-19 11:55
I could't reproduce this bug, even with faked location (in Macedonia). 

However I noticed that when Expensify timezone is not compatible with timezone on a computer it can result with situations like this: (just synced but timezones differ one hour)
<img width="500" alt="image" src="https://github.com/user-attachments/assets/f4522d28-b8bf-4002-aa6e-548f4fa5ecf3">
I think that is because function `getLocalDateFromDatetime` returns the correct hour for the selected timezone, but timezone itself is wrong (in this case it should be CEST) 
results: `Thu Sep 19 2024 13:35:31 GMT+0100 (Western European Summer Time)`
Is this behaviour expected?
cc: @puneetlath

**Comment by puneetlath** [comment] 2024-09-21 22:50
>However I noticed that when Expensify timezone is not compatible with timezone on a computer it can result with situations like this: (just synced but timezones differ one hour)

What does it mean for a timezone not to be compatible with the timezone on a computer?

**Comment by zfurtak** [comment] 2024-09-23 10:26
What I meant is when the timezone is set manually in the Expensify App and it is different from computer's timezone, then we have situation like I described above

**Comment by puneetlath** [comment] 2024-09-23 13:03
Ahh interesting. So when it says "synced 1 hour ago" that is true for the timezone that has been set in the Expensify App? If so, that doesn't sound like a bug to me.

**Comment by zfurtak** [comment] 2024-09-24 11:46
In my timezone (this one set on my computer) it's 10AM, and for the Expensify's timezone it's 11AM, when I do the sync instead of `Synced just now` it appears `Synced in 1 hour`, so I think it uses my computer's timezone and then relates it to Expensify's one

**Comment by puneetlath** [comment] 2024-09-24 19:25
So should we update it to just use the timezone in Expensify for determining how long ago it was synced?

**Comment by zfurtak** [comment] 2024-10-01 10:35
> So should we update it to just use the timezone in Expensify for determining how long ago it was synced?

I would say so, as the current situation causes information like `Last synced in an hour`, however it's not connected to this bug I guess

**Comment by puneetlath** [comment] 2024-10-09 15:58
Ok, what do you think @dukenv0307?

**Comment by puneetlath** [comment] 2024-10-10 14:31
Ok sounds good. @zfurtak do you have everything you need to raise a PR?

**Comment by zfurtak** [comment] 2024-10-11 09:28
I'm looking into it 👍

**Comment by zfurtak** [comment] 2024-10-12 10:02
The PR is ready for a review 😊

**Comment by puneetlath** [comment] 2024-10-30 22:32
Regression test: https://github.com/Expensify/Expensify/issues/440304

All paid. Thanks y'all!

**Closed by puneetlath** 2024-10-30 22:32 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
