### ISSUE TITLE
[$500] On distance update, if amount is same as before, changed merchant message is displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30043] opened 2023-10-20 01:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697731583309229

## Action Performed:
1. Open the app
2. Open any distance request report or raise one and open
3. Note down current amount and current start finish
4. Click on Distance and change start or finish address OR invert start finish addresses
5. It will change amount and add new changed the distance message which is correct
6. Open amount and change it to amount which was noted in step 3
7. Open distance and change start finish again to addresses which were noted in step 3
8. Observe that since now, there was no change in amount after change in addreses, app displays changed merchant message instead of changed distance message
## Expected Result: 
App should display changed distance message whenever we change distance in distance request report
## Actual Result: 
App displays changed merchant message instead of changed distance message when even after changing distance, amount remains same

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/396b33a6-b874-40b1-87ff-ffc5779ea381

</details>

<details>
<summar

https://github.com/Expensify/App/assets/38435837/a783b4af-a74b-4d46-8a5a-3e2f4beceb1c

y>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/9dd83152-b559-4281-aa59-b1418e609faf

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/12a23174-5741-4640-8bcb-00d4743795fd

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/30267ac8-64d4-4580-a793-0ce1f004c595

https://github.com/Expensify/App/assets/38435837/1ef81ec6-b2b5-4ba2-b1f5-0428769e477d

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/f21e800e-a23d-4549-95e9-1f827200669d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c6b74407df4721a</li>
        <li>Upwork Job ID: 1715177403214991360</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-10-20 02:24
I think this is a backend issue .. as in the case of `waypoints` we send the request to the backend containing the `waypoint0` and `waypoint1` and the backend sends back the modified fields .. so in the current issue, the backend doesnt send the modifiedAmount in the response


  https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L779-L786

**Comment by barros001** [comment] 2023-10-20 02:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When editing a distance request and updating the address but which will result in the exact same amount, the message displayed is:

```
changed the merchant to "11.03 mi @ $0.655 / mi" (previously "12.8 mi @ $0.655 / mi")
```

instead of:

```
changed the distance to 11.03 mi @ $0.655 / mi (previously 12.8 mi @ $0.655 / mi)
```

### What is the root cause of that problem?

Method `getModifiedExpenseMessage` is responsible for generating the message after a request is edited. The only time it would generate a `changed distance` message is when the amount also changes, as can be seen here:

```js
    if (hasModifiedAmount) {
        const oldCurrency = reportActionOriginalMessage.oldCurrency;
        const oldAmount = CurrencyUtils.convertToDisplayString(reportActionOriginalMessage.oldAmount, oldCurrency);

        const currency = reportActionOriginalMessage.currency;
        const amount = CurrencyUtils.convertToDisplayString(reportActionOriginalMessage.amount, currency);

        // Only Distance edits should modify amount and merchant (which stores distance) in a single transaction.
        // We check the merchant is in distance format (includes @) as a sanity check
        if (hasModifiedMerchant && reportActionOriginalMessage.merchant.includes('@')) {
            return getProperSchemaForModifiedDistanceMessage(reportActionOriginalMessage.merchant, reportActionOriginalMessage.oldMerchant, amount, oldAmount);
        }

        return getProperSchemaForModifiedExpenseMessage(amount, oldAmount, Localize.translateLocal('iou.amount'), false);
    }
```

When only distance is changed, the flag `hasModifiedMerchant` is set to true which calls the following:

```js
    if (hasModifiedMerchant) {
        return getProperSchemaForModifiedExpenseMessage(reportActionOriginalMessage.merchant, reportActionOriginalMessage.oldMerchant, Localize.translateLocal('common.merchant'), true);
    }
```

The `MofifiedExpenseMessage` reads as follow:

```js
        updatedTheRequest: ({valueName, newValueToDisplay, oldValueToDisplay}: UpdatedTheRequestParams) =>
            `changed the ${valueName} to ${newValueToDisplay} (previously ${oldValueToDisplay})`,
```

where `valueName` is `merchant`.

Distance is stored in the `merchant` field, which causes this problem. The system thinks the `merchant` changed and not the distance as it can't really tell at that point what the `merchant` field is storing.

### What changes do you think we should make in order to solve the problem?

`getModifiedExpenseMessage` method needs to know what the `merchant` attribute actually holds: merchant or distance. 

`merchant` field will either have to be split in two (merchant and distance) or `getModifiedExpenseMessage ` will have to be given context as to what type `merchant` holds. This will either have to be fixed on the backend, adding the type (Distance, or something else) to `reportAction` or by passing it around everywhere `getModifiedExpenseMessage` is called.

The ideal solution would be to update the back end but this is a much bigger problem. A third option would be to check for a pattern in the `merchant` field, if it matches `[0-9.]+ mi @ $[0-9]+ / m` and if so, then we know `merchant` holds distance. 



### What alternative solutions did you explore? (Optional)


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by paultsimura** [comment] 2023-10-20 09:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After the distance request had amount changed manually, the waypoints modification do not change the amount.

### What is the root cause of that problem?
The issue is actually deeper than just "not updating the amount" – it's reverting the waypoints to the previous state.

When executing the `UpdateDistanceRequest` API call, we build the Onyx data with waypoints of the updated transaction here:

https://github.com/Expensify/App/blob/b1ae0c20bd6926cf03ebd7d011beb2ee61c1814a/src/libs/TransactionUtils.ts#L148-L151

Let's take a look at what happens when we remove one waypoint.
The simple merge operation for the following object:

```js
{
    "comment": {
        "type": "customUnit",
        "customUnit": {
            "name": "Distance"
        },
        "waypoints": {
            "waypoint0": { wp-0 },
            "waypoint1": { wp-1 },
            "waypoint2": { wp-2 }
        }
    }
}
```

To the following object:
```js
{
    "comment": {
        "type": "customUnit",
        "customUnit": {
            "name": "Distance"
        },
        "waypoints": {
            "waypoint0": { wp-0 },
            "waypoint1": { wp-1 },
        }
    }
}
```

...will result in the same as pre-merge:
```js
{
    "comment": {
        "type": "customUnit",
        "customUnit": {
            "name": "Distance"
        },
        "waypoints": {
            "waypoint0": { wp-0 },
            "waypoint1": { wp-1 },
            "waypoint2": { wp-2 }
        }
    }
}
```

This is because the `waypoint2` merge key was not passed to Onyx, so it's ignored, as Onyx replaces values key-by-key to the latest nested object. So this merge operation modifies only `waypoint0` and `waypoint1`, leaving the `waypoint2` untouched.

### What changes do you think we should make in order to solve the problem?

We should now explicitly mark the deleted waypoints as null when passing them to Onyx.

**First**, create a new function in `TransactionUtils`:

```ts
function getReplacementWaypoints(transaction: Transaction, updatedWaypoints: WaypointCollection): WaypointCollection {
    const existingWaypoints = getWaypoints(transaction) ?? {};

    if (Object.keys(updatedWaypoints).length >= Object.keys(existingWaypoints).length) {
        return updatedWaypoints;
    }

    return lodashReduce(existingWaypoints, (result, value, key) => ({
        ...result,
        // Explicitly set the non-existing waypoints to null so that Onyx can remove them
        [key]: updatedWaypoints[key] ?? null,
    }), {});
}
```

**Second**, use it here when building the updated transaction:
```diff
    if (Object.hasOwn(transactionChanges, 'waypoints')) {
-       updatedTransaction.modifiedWaypoints = transactionChanges.waypoints;
+       updatedTransaction.modifiedWaypoints = getReplacementWaypoints(transaction, transactionChanges.waypoints!!);
        shouldStopSmartscan = true;
    }
```

**Third**, we are also passing these waypoints to MapBox on the API call. We pass them as a stringified JSON, and there we should remove the null-ish waypoints:

https://github.com/Expensify/App/blob/3b86da6dc1ec2ca15033bbdc09702892966c2580/src/libs/actions/IOU.js#L697

We should use the following:

```js
waypoints: JSON.stringify(TransactionUtils.getValidWaypoints(transactionDetails.waypoints)),
```

Similar to what we do on the `createDistanceRequest`:

https://github.com/Expensify/App/blob/3b86da6dc1ec2ca15033bbdc09702892966c2580/src/libs/actions/IOU.js#L649


### What alternative solutions did you explore? (Optional)

**Comment by robertKozik** [comment] 2023-10-23 19:01
@paultsimura Can we be sure that after the BE would be fixed to return the missing `merge` operation, distance message will be properly set?

**Comment by paultsimura** [comment] 2023-10-24 09:59
> @paultsimura Can we be sure that after the BE would be fixed to return the missing `merge` operation, distance message will be properly set?

Yes, it should fix the message, but with one remark: actually, there are 3 Onyx operations missing on waypoints swap:

1. Operation with added waypoint:
<img width="681" alt="image" src="https://github.com/Expensify/App/assets/12595293/7799f80f-b312-4cf1-96fc-86e34f05c352">

2. Operation with swapped waypoints:
<img width="681" alt="image" src="https://github.com/Expensify/App/assets/12595293/ac34f16c-47af-42ef-a264-27d3deffb3a8">

I believe, there is some check on the BE side that, if the amount doesn't change, doesn't fire these 3 events. We should consider, for distance requests, checking not just if the amount has changed, but whether the route has changed.

These operations will provide the necessary updates that will be used here to calculate the new message:

https://github.com/Expensify/App/blob/7d6e94be0f124c07c6563aa09b1baac272dfd662/src/libs/ReportUtils.js#L1741-L1745

We just need to decide what is the expected behavior here: do we want to get any kind of message if the waypoints are swapped? If this is the case, we might end up getting messages like this (because technically the distance and amount did not change):

> changed the distance to 10 mi @ zł0.655 / mi (previously 10 mi @ zł0.655 / mi), which updated the amount to PLN 6.5 (previously PLN 6.5)

**Comment by barros001** [comment] 2023-10-24 14:41
I'll chime in here. I'm brand new to the codebase and could be missing something here, so please keep that in mind.

I believe @paultsimura is onto something here, but it does look like it's a different problem, and solving it would not really solve the message problem the current issue is trying to address. 

My understanding is that this issue is about the message that's displayed when the _distance_ changes but the amount remains the same. When this happens, the message displayed says the _Merchant_ have been updated instead of saying the _Distance_. 

There reason for this is because `getModifiedExpenseMessage` (which is the method responsible for generating the message) cannot tell whether the modified value was a distance or a merchant, because the same attribute (`merchant`) is used to store both values:

```js
    const hasModifiedAmount =
        _.has(reportActionOriginalMessage, 'oldAmount') &&
        _.has(reportActionOriginalMessage, 'oldCurrency') &&
        _.has(reportActionOriginalMessage, 'amount') &&
        _.has(reportActionOriginalMessage, 'currency');

    console.debug({reportActionOriginalMessage, reportAction});

    const hasModifiedMerchant = _.has(reportActionOriginalMessage, 'oldMerchant') && _.has(reportActionOriginalMessage, 'merchant');
```


When `merchant` only has changed, `hasModifiedAmount` will be `false` and `hasModifiedMerchant` will be `true`.

Later one we have this:

```js
    if (hasModifiedMerchant) {
        return getProperSchemaForModifiedExpenseMessage(reportActionOriginalMessage.merchant, reportActionOriginalMessage.oldMerchant, Localize.translateLocal('common.merchant'), true);
    }
```


Note the hardcoded `Localize.translateLocal('common.merchant') `. `getProperSchemaForModifiedExpenseMessage` will eventually render the following message:

```ts
        updatedTheRequest: ({valueName, newValueToDisplay, oldValueToDisplay}: UpdatedTheRequestParams) =>
            `changed the ${valueName} to ${newValueToDisplay} (previously ${oldValueToDisplay})`,
```


`valueName` will be **always** set to `merchant` in this scenario because there's simply not enough information to determine whether the changed value represents a merchant or a distance. As I mentioned on my [proposal](https://github.com/Expensify/App/issues/30043#issuecomment-1771998425), I don't think there's a clean way (other than doing a pattern match against the `merchant` attribute, which on itself is not really very clean) without making BE changes.

Would it make sense to raise a new issue to handle the issues with the waypoints that @paultsimura uncovered, which appears to be a new issue?

**Comment by paultsimura** [comment] 2023-10-24 20:06
> Would it make sense to raise a new issue to handle the issues with the waypoints that @paultsimura uncovered, which appears to be a new issue?

I'd agree with @barros001 here – I misinterpreted this issue from the beginning. Reported that one separately.

**Comment by paultsimura** [comment] 2023-10-29 12:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After the distance request had amount changed manually, the waypoints modification show incorrect system message (if the amount was the same).

### What is the root cause of that problem?
The issue is that we use kind of a hack to determine whether the distance was changed: we check the merchant change and use RegExp:

https://github.com/Expensify/App/blob/a59d56f00a67607a1dbae1b422807f76f548f1f0/src/libs/ReportUtils.js#L1861-L1865

### What changes do you think we should make in order to solve the problem?

**First,** I suggest re-thinking the "Update Route" approach, starting from BE.

The way all the other money requests updates are handled now is the following (let's take the example of a manual money request):

The `transaction.amount` field remains unchanged – it reflects the initially requested amount.
Instead, the `transaction.modifiedAmount` is updated on every modification.

With the distance requests, we currently do it differently – we update the original `transaction.comment.waypoints`.

We should implement the same approach for the distance requests modifications. Update the transaction.modifiedWaypoints, and keep the original `transaction.comment.waypoints` untouched.

We already build the `updatedTransaction.modifiedWaypoints` here:
https://github.com/Expensify/App/blob/86094548d6d97939da8e589ad89a169c0bf683e6/src/libs/TransactionUtils.ts#L148-L151

But it's not updated in the BE, and is not returned from the API call (all the other `modified*` fields are returned):

```json
{
  "onyxMethod": "merge",
  "key": "transactions_8849286097733348684",
  "value": {
    "amount": -11234,
    "billable": false,
    "cardID": 18550310,
    "category": "Car",
    "comment": {
      "comment": "",
      "customUnit": {
        "attributes": [],
        "customUnitID": "C4FC57BEA2908",
        "customUnitRateID": "2C52D2B1A4916",
        "name": "Distance",
        "quantity": 387.54,
        "subRates": []
      },
      "type": "customUnit",
      "waypoints": {
        "waypoint0": {
          "address": "Kraków, Poland",
          "lat": 50.06465009999999,
          "lng": 19.9449799,
          "name": "Kraków"
        },
        "waypoint1": {
          "address": "Wrocław, Poland",
          "lat": 51.1078852,
          "lng": 17.0385376,
          "name": "Wrocław"
        },
        "waypoint2": {
          "address": "Warsaw, Poland",
          "lat": 52.2296756,
          "lng": 21.0122287,
          "name": "Warsaw"
        }
      }
    },
    "created": "2023-10-29",
    "currency": "PLN",
    "filename": "w_9c6814e87c3ca9e256322b24606a3975e0fa57a6.png",
    "merchant": "171.51 mi @ zł0.655 / mi",
    "modifiedAmount": -25384,
    "modifiedCreated": "2023-10-29",
    "modifiedCurrency": "PLN",
    "modifiedMerchant": "387.54 mi @ zł0.655 / mi",
    "originalAmount": 0,
    "originalCurrency": "",
    "parentTransactionID": "",
    "receipt": {
      "receiptID": 669153517,
      "state": "OPEN",
      "source": "https://www.expensify.com/receipts/w_9c6814e87c3ca9e256322b24606a3975e0fa57a6.png"
    },
    "reimbursable": true,
    "reportID": "8023553457850147",
    "status": "Posted",
    "tag": "",
    "transactionID": "8849286097733348684",
    "hasEReceipt": false
  }
}
```

**Second,** after the BE changes are done, we should change the logic for building the distance messages in this function: 

https://github.com/Expensify/App/blob/a59d56f00a67607a1dbae1b422807f76f548f1f0/src/libs/ReportUtils.js#L1832-L1901

We should check for `hasModifiedWaypoints` similar to the other checks, and build the distance message if the waypoints have changed.

### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment] 2023-11-02 11:23
@robertKozik some proposals above for you to take a look at

**Comment by muttmuure** [comment] 2023-11-09 11:27
Bump @robertKozik

**Comment by muttmuure** [comment] 2023-11-13 14:26
Unable to test this again, I'm not sure it's a big priority tbh

**Comment by DylanDylann** [comment] 2023-11-17 11:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On distance update, if amount is same as before, changed merchant message is displayed

### What is the root cause of that problem?
The BE is only return oldMerchant and merchant in the reportAction.originalMessage. So that the App only trigger this condition
https://github.com/Expensify/App/blob/f08baad07d44bdbccaf2ebc31e72e82f6dfb40b1/src/libs/ReportUtils.js#L1990-L1992

### What changes do you think we should make in order to solve the problem?
I think we should remove this condition 
https://github.com/Expensify/App/blob/f08baad07d44bdbccaf2ebc31e72e82f6dfb40b1/src/libs/ReportUtils.js#L1970-L1972

and create another one in the before of
https://github.com/Expensify/App/blob/f08baad07d44bdbccaf2ebc31e72e82f6dfb40b1/src/libs/ReportUtils.js#L1961

like this

```
if (TransactionUtils.isDistanceRequest(transaction) && hasModifiedMerchant && reportActionOriginalMessage.merchant.includes('@')) {
            if (hasModifiedAmount) {

                return getProperSchemaForModifiedDistanceMessage(reportActionOriginalMessage.merchant, reportActionOriginalMessage.oldMerchant, displayAmountChange: true ,amount, oldAmount);
            } else {

                return getProperSchemaForModifiedDistanceMessage(reportActionOriginalMessage.merchant, reportActionOriginalMessage.oldMerchant, displayAmountChange: false);
            }

        }
```
we also need to create new param displayAmountChange in the getProperSchemaForModifiedDistanceMessage function
### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment] 2023-11-22 11:13
Still seems like low priority but @robertKozik if you could take a look at some of the proposals that would be helpful

**Comment by muttmuure** [comment] 2023-11-24 15:56
Still lower priority

**Comment by muttmuure** [comment] 2023-12-08 11:27
I can't actually reproduce this now.

**Closed by muttmuure** 2023-12-08 11:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by paultsimura** [comment] 2023-12-08 11:38
@muttmuure I've just reproduced on latest app version:

![image](https://github.com/Expensify/App/assets/12595293/3f8e111f-7073-4be3-a0aa-1db55784fa71)

**Comment by cubuspl42** [comment] 2023-12-11 13:32
@muttmuure Would you confront your findings with what @paultsimura found? Do we need to share each other's more precise reproduction steps?
