### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Text cut-off text in request money page on iPhone 12

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31785] opened 2023-11-23 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700681836783659

## Action Performed:
1. Open app 
2. Tap "Request money" 
## Expected Result:
Text at the top are not cut off
## Actual Result:
Text are cutoff at the bottom
## Workaround:
Visual issue
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![IMG_6913 (1)](https://github.com/Expensify/App/assets/38435837/032eb470-5654-4283-b911-e5ea17551f98)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da1b18c747161655</li>
        <li>Upwork Job ID: 1737790764645019648</li>
        <li>Last Price Increase: 2024-01-02</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28081902</li>
<li>aswin-s | Contributor | 28081903</li>
</ul></li>
    </ul>
</details>

**Comment by peterdbarkerUK** [comment] 2023-11-28 18:53
I don't have an iPhone, seeing if someone else can pick this up

**Comment by peterdbarkerUK** [comment] 2023-11-28 21:06
nevermind I can use browsserstack. Will sort that tomorrow!

**Comment by peterdbarkerUK** [comment] 2023-11-29 15:43
@blimpich 'ello mate - I'm unable to reproduce this, are you still getting it? 

1.4.5:
![image](https://github.com/Expensify/App/assets/16888060/1bab8b1c-8020-4647-8296-7b7731d83f93)

1.4.1:
![image](https://github.com/Expensify/App/assets/16888060/ba331167-ebef-4d14-8788-2e9f45a6d9ea)

**Comment by blimpich** [comment] 2023-11-29 17:27
As of this morning, yup, still cut off. iPhone 12, Expensify v1.4.3-11

![cut off text](https://github.com/Expensify/App/assets/17171674/48b87857-4bc1-4918-90ca-8272496d9f7e)
![version](https://github.com/Expensify/App/assets/17171674/effea17a-01ad-4eb5-8738-20fb56f06bc8)

**Comment by peterdbarkerUK** [comment] 2023-11-29 19:54
I see your screenshot and raise you a video:
https://github.com/Expensify/App/assets/16888060/0be668a5-99f4-4cf3-9c29-eca577aba7b1

Hmmm. It looks like it might be clipping the text in line with the animations on your phone. There are a couple of [examples](https://github.com/Expensify/App/issues/28772) of similar things around when people use min/max font/line size - does changing the font size affect things at all?

**Comment by blimpich** [comment] 2023-11-29 20:13
@peterdbarkerUK Ah yes you are definitely correct. I forgot that long ago I made my font sizes larger than average for my less than average quality 👀's. This is a font size accessibility issue not a general css issue. Not sure if this a priority or not.

**Comment by peterdbarkerUK** [comment] 2023-12-12 20:42
Shoot, this one slipped off my radar amidst the A! Integration Error trigger tsunami last week. Sorry @blimpich. 

I think accessibility issues are extremely important, but I don't know how this fits into our focus on bug/waves. Reached out to you in DM to clarify a few things!

**Comment by peterdbarkerUK** [comment] 2023-12-27 13:03
Chatted with @blimpich, [shared in slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1703682183525779) here!

**Comment by peterdbarkerUK** [comment] 2024-01-02 21:11
Agreed to add to VIP-Split and mark as external

**Comment by peterdbarkerUK** [comment] 2024-01-02 21:12
hu, I wonder why overdue got re-added, I didn't click it. Not overdue.

**Comment by akinwale** [comment] 2024-01-02 21:27
@peterdbarkerUK I am able to reproduce this on a simulator running iOS 17.2. The font size can be increased by navigating to Settings > Accessibility > Display & Text Size > Larger Font Sizes on the device and dragging the slider. This text only seems to be cut off in the tab labels specifically as everything else looks fine on first glance.

![Screenshot 2024-01-02 at 22 24 45](https://github.com/Expensify/App/assets/4160319/49881901-eb80-4b58-a6ba-0e2fceff0c79)

**Comment by samilabud** [comment] 2024-01-02 22:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text cut-off text in request money page on iPhone 12

### What is the root cause of that problem?
This happens because the text increases more than its container when we use larger accessibility sizes and we are not handling these scenarios.

### What changes do you think we should make in order to solve the problem?
We can modify the text label component [here](https://github.com/Expensify/App/blob/main/src/components/TabSelector/TabLabel.tsx) using allowFontScaling prop, to avoid accessibility text increasing the text in this case, e.g:

```
function TabLabel({title = '', activeOpacity = 0, inactiveOpacity = 1}: TabLabelProps) {
    const styles = useThemeStyles();
    return (
        <View>
            <Animated.View style={[{opacity: activeOpacity}]}>
                <Text
                    style={styles.tabText(true)}
                    allowFontScaling={false}
                >
                    {title}
                </Text>
            </Animated.View>
            <Animated.View style={[StyleSheet.absoluteFill, {opacity: inactiveOpacity}]}>
                <Text
                    style={styles.tabText(false)}
                    allowFontScaling={false}
                >
                    {title}
                </Text>
            </Animated.View>
        </View>
    );
}

```

Result:

https://github.com/Expensify/App/assets/5216036/25a4b4b8-796e-47b9-b2d0-904d30b2874b

**Comment by aswin-s** [comment] 2024-01-03 05:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text in TabHeader on RequestMoney page is clipped when font size is set to large in device accessibility settings.

### What is the root cause of that problem?

The Tab label component inside TabSelectorItem is not using `Text` component from '@components/Text'. It imports Text component from 'react-native' library. Font scaling is disabled in Text component under '@components'. That's the reason why other screens are not affected even when larger font sizes are set from system accessibility settings.

https://github.com/Expensify/App/blob/a83eecc32171045b1484614e55a9f208ae2fc9d0/src/components/TabSelector/TabLabel.tsx#L2

### What changes do you think we should make in order to solve the problem?

Replace Text import from 'react-native' with '@component/Text'

```tsx
import Text from '@components/Text'
``` 

### What alternative solutions did you explore? (Optional)

None

**Comment by akinwale** [comment] 2024-01-03 06:54
@samilabud I don't think disabling font scaling is the appropriate solution here. The user chooses the option of larger text for a reason.

@aswin-s Did you test your proposed solution? The text is still cut off with just the import.

**Comment by aswin-s** [comment] 2024-01-03 08:44
@akinwale Sorry about that. I jumped the gun. Didn't reload the app after increasing font scaling. I've [updated the proposal ](https://github.com/Expensify/App/issues/31785#issuecomment-1874854896)now to use pixel ratio adjusted font size.

**Comment by akinwale** [comment] 2024-01-03 12:48
We can move forward with @aswin-s's proposal here.

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment] 2024-01-03 12:52
It looks like the horizontal padding for the tab is not prominent with the larger font size. This is especially obvious with the Distance tab as observed in the screenshot below. Since this is a special case with the user having to explicitly increase their device's font size, do we want to leave this as is or truncate (ellipsize) the text? Pinging @Expensify/design for thoughts on this.

![image](https://private-user-images.githubusercontent.com/6880914/293867064-122b83d5-76d9-4572-a80f-a960ca35088c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODYzMTAsIm5iZiI6MTcwNDI4NjAxMCwicGF0aCI6Ii82ODgwOTE0LzI5Mzg2NzA2NC0xMjJiODNkNS03NmQ5LTQ1NzItYTgwZi1hOTYwY2EzNTA4OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMTI0NjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWU5ODhlNTMwMWRhOTQxOTAwNzkzNzI5YjQyNDg2ZDIyYzEwOWQ1MDJlMzQ4ODU2MjFmOTNiZTNiZGY5MGU4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w10INPrCBd4PmndNibd_a9ofOhb6IkrWgRL26X5Qk_o)

**Comment by dannymcclain** [comment] 2024-01-03 14:01
🤔 Hmmm ideally our app would be able to adjust to support users who need to increase their text size. I'm kinda worried truncating the option is worse than the super tight padding (I mean with the tight padding at least you can see the whole label). So I'm tempted to say let's leave it. But I want to hear @shawnborton and @dubielzyk-expensify's thoughts too.

Had an insanely wild idea to try to set those tabs up so they stack the icon over the text in situations like this, but that seems not super doable and probably opens up many cans of worms. 🪱

**Comment by shawnborton** [comment] 2024-01-03 16:39
Hmm I think ideally we'd just make it so that these tabs get a min-width (aka respect the inner padding of each tab button) and then if the sum of the width of the three tabs are bigger than the available container, we would just use a horizontal scroll. Thoughts on something like that?

That being said... I don't know that we've prioritized really any font size/accessibility issues, so I wonder if we just close this out for now?

**Comment by akinwale** [comment] 2024-01-03 17:45
> That being said... I don't know that we've prioritized really any font size/accessibility issues, so I wonder if we just close this out for now?

We still need to fix the issue with the text being cut off vertically, so I suppose it makes sense to just leave the padding as is with the enlarged text and then come up with design patterns for accessibility later?

**Comment by dubielzyk-expensify** [comment] 2024-01-03 23:38
Yeah I'd agree to leave it as well though like you said @akinwale fix the vertical cutoff

**Comment by akinwale** [comment] 2024-01-04 19:59
@aswin-s Please go ahead and create a PR whenever it's ready. Thanks.

**Comment by GabiHExpensify** [comment] 2024-01-05 05:05
I think this is important to fix, and it sounds like there's already been a fix outlined, so seems good to go... but I don't think this belongs on the #vip-split project. Is there a different project this would fit into better @peterdbarkerUK?

**Comment by akinwale** [comment] 2024-01-17 10:38
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. There was no styling added to properly handle larger font sizes which happens when a user increases the font size on their respective device.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression test steps**
* Close the native Expensify app on iOS and Android if already launched.
* Increase the font size on the device. On iOS: Settings > Accessibility > Display & Text Size > Larger Text. On Android: Settings > Display > Display size and text (note that this may vary across various device manufacturers).
* Launch the native Expensify app.
* Open the global create menu.
* Select Request money.
* Verify that the text labels for the "Manual", "Scan" and "Distance" tabs are completely visible.

Do we agree 👍 or 👎?

**Comment by peterdbarkerUK** [comment] 2024-01-22 21:33
TR Case up, and payouts made:

@akinwale $500 for review
@aswin-s $500 for contribution

Thanks for reporting @blimpich, 1 melvincoin!

**Closed by peterdbarkerUK** 2024-01-22 21:33 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
