### ISSUE TITLE
[$750] Desktop - "Hmm... it's not here" is displayed when a profile deeplink is opened two or more times

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29372] opened 2023-10-11 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when executing PR : https://github.com/Expensify/App/pull/29277

**Version Number:** v1.3.81-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
Precondition: User A and User B should have no prior chat history

As User A:
1. Open a tab and sign in as User A
2. Click on 'Profile avatar' > Share code > Copy URL to clipboard

As User B:

1. Open staging.new.expensify.com and sign in as User B
2. Paste the URL into the address bar
3. Press enter
4. In the ''Open New Expensify'' modal, click on the CTA button to open the app
5. Close the profile page
6. Go back to the web page and paste the profile link for a second time
7. Repeat step 4

## Expected Result:
There should be no errors when opening the deeplink from the same profile page multiple times.

## Actual Result:
The user encounters a "page not found" error when attempting to open the profile page deeplink two or more times in Desktop app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/115492554/33adb5ef-b628-45da-88fa-fc417dbd4d73

[utest-dl.s3.amazonaws.com_12102_26469_432782_6233436_bugAttachment_Bug6233436_1697049112244%21Profile_page_-_Desktop.log_X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231011T195222Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz.txt](https://github.com/Expensify/App/files/12874038/utest-dl.s3.amazonaws.com_12102_26469_432782_6233436_bugAttachment_Bug6233436_1697049112244.21Profile_page_-_Desktop.log_X-Amz-Algorithm.AWS4-HMAC-SHA256.X-Amz-Date.20231011T195222Z.X-Amz-SignedHeaders.host.X-Amz-Expires.86400.X-Amz.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019231ee47ef138a05</li>
        <li>Upwork Job ID: 1712194879740461056</li>
        <li>Last Price Increase: 2023-10-27</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27546164</li>
</ul></li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-10-13 13:55
Not reproducible.

**Comment by NicMendonca** [comment] 2023-10-13 19:08
@izarutskaya can you still reproduce?

**Comment by izarutskaya** [comment] 2023-10-14 06:08
Yes, @NicMendonca, we can reproduce this still on Version 1.3.83-10 (1.3.83-10)

https://github.com/Expensify/App/assets/115492554/b6764432-08be-428d-8034-015ef62abca9

https://github.com/Expensify/App/assets/115492554/0f3d231f-babb-4398-bc83-a8a9e47c4b6d

**Comment by NicMendonca** [comment] 2023-10-18 20:35
@eVoloshchak should we adjust bounty?

**Comment by eVoloshchak** [comment] 2023-10-20 08:47
@NicMendonca, i think we should, since there aren't any proposals

**Comment by barttom** [comment] 2023-10-23 08:56
Hey! I'm Bartek from Callstack - an expert contributor group. I’d like to work on this issue. I'm gonna investigate that and prepare proposal

**Comment by NicMendonca** [comment] 2023-10-24 13:40
Thank you @barttom 🥳

**Comment by barttom** [comment] 2023-10-24 15:51
@izarutskaya Are YOu still able to reproduce that? I've tried a few times and works fine for me.
I used staging on the browsers and current main branch for desktop

https://github.com/Expensify/App/assets/7682108/a7c27a3f-16ac-41d5-99eb-96d08fc4f78c

**Comment by ikevin127** [comment] 2023-10-25 01:31
I can still reproduce this on latest staging release of the desktop app **Version 1.3.90-2 (1.3.90-2)** downloaded via: https://staging.new.expensify.com/NewExpensify.dmg

The thing is that it can be reproduced but not always exactly as stated in the steps of the OP, the interval of when the error occurs differs. Sometimes it happens on 2nd - 3rd try of deep link, sometimes you have to open the link 6-7 times.

I noticed it occurs more often if the left side drawer which the shared link opens, is dismissed (closed) on the desktop app, when re-opening the deep link from web again it's more likely to get the not found page (more context below on debugging).

The equivalent to the not found page from staging that I get on local development of the desktop app is the video shown above with the infinite loading indicator. So instead of the not found page we see the infinite loading indicator on local development with latest main branch.

**Debugging**:
From what I've been able to research so far, my guess is that it's somewhat related to the fact that **before** the drawer opened by the shared link is triggered, the `ReportScreenWrapper`'s navigator does not have the reportID prop initially but it does get set by `ReportScreenIDSetter` eventually which in the case of this issue **might** cause the not found page seen on staging or the infinite loading indicator seen on local dev.

This is just a pointer I wanted to share which might help with debugging. Good luck!

**Comment by barttom** [comment] 2023-10-25 11:54
@ikevin127 thanks for the tip, I'll keep debugging it then.

**Comment by ikevin127** [comment] 2023-10-25 14:22
Another detail which can be observed on the staging desktop app when the not found page occurs:

<details>
<summary>Screenshots / Debug staging desktop app</summary>

- open inspect on desktop staging app:
<img width="680" alt="Screenshot 2023-10-25 at 16 10 11" src="https://github.com/Expensify/App/assets/56457735/394fe65d-bcf8-4d05-bc9e-5517bd74e075">

- verbose logs when not found page is displayed:
<img width="1242" alt="Screenshot 2023-10-25 at 16 18 02" src="https://github.com/Expensify/App/assets/56457735/b5913c14-02b8-4d51-a3ad-47e77951a8fc">

</details>

`[info] Navigating to route - {"path":"/not-found?email=kevin.bader96+7@gmail.com&exitTo=/a/15938988&shortLivedAuthToken={token}"}`

By the way the above-mentioned log looks, what happens is that randomly the navigation sends the user to the not found page with the path set to `exitTo=/a/15938988`, meaning when going back from the not found page - you will actually be redirected to the shared profile which the deep link should've routed to, but for some reason sometime the not found page is shown.

```diff
NavigationRoot - handleStateChange state object: 
{
    "stale": false,
    "type": "stack",
    "key": "stack-W8Xyr5KQakVU3NK-KUfoy",
    "index": 3,
    "routeNames": [...routes],
    "routes": [
        {
            "name": "Home",
            "key": "Home-uoEF2tQ6YEf4PBlFBYXDe"
        },
        {
            "name": "CentralPaneNavigator",
            "state": {
                "stale": false,
                "type": "stack",
                "key": "stack-3VBNDiaBlDGj53noQDQ8f",
                "index": 0,
                "routeNames": [
                    "Report"
                ],
                "routes": [
                    {
                        "name": "Report",
                        "params": {
                            "reportID": ""
                        },
                        "key": "Report-w-Ftn9Pbc89mSDBxj8Gwg"
                    }
                ]
            },
            "key": "CentralPaneNavigator-S30S4AFDe_pz8RS2Akhwy"
        },
        {
+           "key": "RightModalNavigator-Azan1LKa0mxhvhjo6geVu",
            "name": "RightModalNavigator",
            "params": {
                "initial": true,
                "screen": "Profile",
                "params": {
                    "initial": true,
                    "screen": "Profile_Root",
                    "params": {
                        "accountID": "15938988"
                    },
                    "path": "/a/15938988"
                }
            },
            "state": {
                "stale": false,
                "type": "stack",
                "key": "stack-OuLGBfEXJNRVVrayvfuW6",
                "index": 0,
                "routeNames": [...routes],
                "routes": [
                    {
                        "key": "Profile-0FRSNPU5uQejy70ybN3JQ",
                        "name": "Profile",
                        "params": {
                            "initial": true,
                            "screen": "Profile_Root",
                            "params": {
                                "accountID": "15938988"
                            },
                            "path": "/a/15938988"
                        },
                        "state": {
                            "stale": false,
                            "type": "stack",
                            "key": "stack-3wQuUw4BrtC_-5qkmiJw6",
                            "index": 0,
                            "routeNames": [
                                "Profile_Root"
                            ],
                            "routes": [
                                {
                                    "key": "Profile_Root-iS3cPk4vKnauWjeBm4Zra",
                                    "name": "Profile_Root",
                                    "params": {
                                        "accountID": "15938988"
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        },
        {
+           "key": "TransitionBetweenApps-q-YJxR48NZuuaVXQmAee8",
            "name": "TransitionBetweenApps",
            "path": "/transition?exitTo=%2Fa%2F15938988&email=kevin.bader96%2B7%40gmail.com&shortLivedAuthToken=token",
            "params": {
                "email": "kevin.bader96+7@gmail.com",
                "exitTo": "/a/15938988",
                "shortLivedAuthToken": "token"
            }
        }
    ]
}
```

Also the object above has the last route `TransitionBetweenApps` when the error happens and the last route `RightModalNavigator` when the error doesn't happen.

Because of this I'm thinking that the `TransitionBetweenApps` route might throw the not found page occasionally.

**Comment by studentofcoding** [comment] 2023-10-26 10:21
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Desktop - "Hmm... it's not here" is displayed when a profile deeplink is opened two or more times

## What is the root cause of that problem?

The root cause of the problem is that the Desktop App deeplink is not correctly handling the routing for profile pages on [desktop/main.js](https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/desktop/main.js#L238C15-L249C8)
```
    app.on('will-finish-launching', () => {
        app.on('open-url', (event, url) => {
            event.preventDefault();
            const urlObject = new URL(url);
            deeplinkUrl = `${APP_DOMAIN}${urlObject.pathname}${urlObject.search}${urlObject.hash}`;


            if (browserWindow) {
                browserWindow.loadURL(deeplinkUrl);
                browserWindow.show();
            }
        });
    });
```

## What changes do you think we should make in order to solve the problem?

In the desktop/main.js file, we need to modify the app.on('open-url', ...) event handler to specifically handle profile page URLs if user open it

Here's the updated code:
```
app.on('will-finish-launching', () => {
    app.on('open-url', (event, url) => {
        event.preventDefault();
        const urlObject = new URL(url);
        // Check if the URL is a profile page URL
        if (urlObject.pathname.startsWith('/a/')) {
            // If it is, load the profile page URL directly
            deeplinkUrl = url;
        } else {
            // Otherwise, use the existing logic
            deeplinkUrl = `${APP_DOMAIN}${urlObject.pathname}${urlObject.search}${urlObject.hash}`;
        }

        if (browserWindow) {
            browserWindow.loadURL(deeplinkUrl);
            browserWindow.show();
        }
    });
});
```
This code checks if the URL is a profile page URL (i.e., it starts with /a/). If it is, it loads the profile page URL directly. Otherwise, it uses the existing logic to load the URL.

## What alternative solutions did you explore? (Optional)

None

@ikevin127 @eVoloshchak @NicMendonca

**Comment by ikevin127** [comment] 2023-10-26 11:57
@studentofcoding Your solution does not solve the problem, it doesn't do anything actually.
I tested it both on a staging and local development  builds and for staging we still get the not found page while on local we still get the infinite loop loading indicator:

<details>
<summary>MacOS: Desktop</summary>

- staging build:

https://github.com/Expensify/App/assets/56457735/3ac2ac55-bfc4-49c2-95d9-3ee070f381e6

- development build:

https://github.com/Expensify/App/assets/56457735/cbea76a8-752a-41ab-881c-06f0ef3b2a45

</details>

You're close to the root but not quite there, the issue's root is not coming from the electron `main.js` file nor it can be fixed from there.

The issue is  much more complex, hence why the bounty for this issue was raised and why it takes longer than usual to solve it, not to talk about the different behaviour between staging build vs local development, I think a solution is needed which would handle both staging / local issues.

I'm still debugging this and if I'll figure it out will come up with a proposal soon.

**Comment by ikevin127** [comment] 2023-10-26 15:00
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The user encounters a "page not found" error when attempting to open the profile page deeplink two or more times in Desktop app.

## What is the root cause of that problem?

The reason why we get the **page not found error on staging desktop** and **infinite loading spinner on local development desktop** is because the desktop app is calling navigate with transition route **when this action is not needed** because **the user is already authenticated** within the desktop app **after the first time** the desktop app is opened from web.

The way the flow was designed to work for the desktop app:
- assuming user is not yet authenticated
- user visits a shared profile URL in web app
- web app prompts user to open said URL in desktop app
- upon opening, desktop app sends transition route to react navigation with `exitTo`, `email` and `shortLivedAuthToken` to authenticate the user automatically then redirect to `exitTo` route after auth is completed

**Important**: transition route is used to authenticate the user when the user is not authenticated within the desktop app.

This flow does not account for when the user is already authenticated within the desktop app:
- user is authenticated on desktop app (step 4 of action performed was completed)
- close the profile page (step 5)
- go back to the web page and paste the profile link for a second time (step 6, then repeat from 4)
- desktop app sends transntion route to react navigation
- authenticated react navigation stack cannot match transition route and shows page not found on staging and infinite loading spinner on local development

1. #### On the electron app `main.js` side:
```
93     const APP_DOMAIN = __DEV__ ? `http://localhost:${port}` : 'app://-';
```
https://github.com/Expensify/App/blob/4760f761a0645bdcc250f319be019941c8ccb811/desktop/main.js#L242

The main electron process will send different transition route to react navigation, depending on dev environment. This is why on local development we don't get not found page because the route `http://localhost:${port}/transition...` is parsed by navigator and pushed as `TransitionBetweenApps` while on staging the `app://-/transition...` format just throws not found because it cannot be matched.

2. #### On the react native side:
https://github.com/Expensify/App/blob/4760f761a0645bdcc250f319be019941c8ccb811/src/Expensify.js#L169-L173

Main electron process sends the custom formatted deeplink to react native navigation where `Linking.getInitialURL()` attempts opening it via `Report.openReportFromDeepLink(url, isAuthenticated)`.

We have multiple async operations before the actual `Navigation.navigate(route, type)` is actually called:
- `InteractionManager.runAfterInteractions()` - which does not guarantee that the callback will be invoked at any specific time, only that it will not run until after interaction work has completed
- `Session.waitForUserSignIn()` - awaits transition route to authenticate user via `shortLivedAuthToken` 
- `canNavigate('navigate', {route})` - checks if navigation is ready, and if not sends route in pendingRoutes to be called as soon as navigation is ready all which cause the volatile situation of the navigation to sometimes throw page not found and to sometimes work

## What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/414d5913999f69d83ab08b6ae6e03325c9ede549/src/libs/actions/Report.js#L1935-L1943

We have to make sure that the transition route passed from the main electron process is **NOT** called if the following conditions are met:
- the platform is desktop
- route is `transition` type
- user `isAuthenticated`
- authenticated user email is equal to transition route email query param

if these conditions are met then we **return** meaning we not call the react navigation with the transition route.

```diff
             if (route === ROUTES.CONCIERGE) { 
                 navigateToConciergeChat(true); 
                 return; 
             }

+            const match = route.match(/email=([^&]*)/);
+            const currentEmail = NetworkStore.getCurrentUserEmail();
+            const transitionEmail = match ? decodeURIComponent(match[1]) : '';

             // If the platform is desktop, user is authenticated, route is `transition`
             // and the current user email equals transition route email we don't want to navigate
             // to the route because it will throw page not found on staging and
             // infinite loading indicator on local development.
             // issue: https://github.com/Expensify/App/issues/29372
+            if ([CONST.PLATFORM.DESKTOP].includes(getPlatform()) && route.includes(ROUTES.TRANSITION_BETWEEN_APPS) && isAuthenticated && _.isEqual(currentEmail, transitionEmail)) {
+                return;
+            }

             Navigation.navigate(route, CONST.NAVIGATION.TYPE.PUSH);
```

This way we make sure the transition route won't be called when not necessary, will only be called when:
- desktop app is not logged in and web calls transition to desktop for the first time
- desktop is logged in with **x** email and on web user re-login with **y** email and calls transition to desktop
- all other cases in which platform desktop is not involved (just like before changes)

In the videos below you can see that the transition route is called whenever the user is logged out of the desktop app in order to perform authentication, but `NOT_CALLED` subsequently.

 ### Videos

<details>
<summary>MacOS: Desktop</summary>

- staging

https://github.com/Expensify/App/assets/56457735/946dc7dc-a089-477b-b6bb-74b8f955dc54

- local development

https://github.com/Expensify/App/assets/56457735/6b40a237-b3bb-41cc-86a1-d1bc979f345f

</details>

**Comment by NicMendonca** [comment] 2023-10-26 20:55
@eVoloshchak proposals for you ^

**Comment by mvtglobally** [comment] 2023-10-27 00:43
Issue not reproducible during KI retests. (First week)

**Comment by barttom** [comment] 2023-10-30 09:04
I think we can go with @ikevin127 solution, can't figure out anything else now :) 
After testing I've had the same results as on videos.

**Comment by eVoloshchak** [comment] 2023-10-30 09:55
@ikevin127, could you check if this is still reproducible?
I'm unable to reproduce the issue in both dev and prod versions of the Desktop app

https://github.com/Expensify/App/assets/9059945/e47336fa-a167-4cd3-af26-6680c6c12e3d

**Comment by ikevin127** [comment] 2023-10-30 13:35
@eVoloshchak Yes, this is still reproducible. Just checked with the latest main, both locally (loading indicator loop) and also with a staging build (not found page).

It just doesn't happen right away (like in action performed), sometimes it can take a few tries as I mentioned in my proposal, it depends on a few factors.

For example in videos below:
- for staging it happened after repeating the action 7 times (console shows navigation /not-found with transition)
- for local dev it happened after 5 times (console show navigation OldDot transition)

<details>
<summary>MacOS: Desktop (staging / local)</summary>

- staging

https://github.com/Expensify/App/assets/56457735/b30aefb1-94fe-4963-a68e-278790a31005

- local dev

https://github.com/Expensify/App/assets/56457735/c51f270a-eddc-4d47-8a50-3341288e013b

</details>

**Comment by ikevin127** [comment] 2023-11-01 14:22
@barttom I noticed you've been assigned to this. Are you handling this issue based on my proposal or are you working on your own proposal for this ?

**Comment by barttom** [comment] 2023-11-01 17:01
@ikevin127 I think Your solution is great, didn't find any better. Based on that proposal is Yours, shouldn't Youb implement it?
If You want me to handle that, just say a word, it's not a problem for me at all :)

**Comment by ikevin127** [comment] 2023-11-01 17:20
@barttom Sure, the reason I made the proposal is because I want to handle this issue. I was asking because I seen you've been assigned by @NicMendonca and did not know why or whether or not you will be taking on this.

**Comment by eVoloshchak** [comment] 2023-11-02 17:32
Still can't reproduce this even after trying for 10 minutes straight. Throttling the network speed also doesn't do anything. 
I think this might be related to performance, @ikevin127, which machine are you using to reproduce the issue?

**Comment by ikevin127** [comment] 2023-11-02 17:59
@eVoloshchak I used a MacBook Air - M1 2020, 8GB RAM on Sonoma 14.0 to reproduce this.

What are you using ?

@izarutskaya and @barttom were also able to reproduce this, maybe they can help with info about their machines.

**Comment by barttom** [comment] 2023-11-02 18:07
so mine is Apple M1 Pro 32GB RAM and macOS 13.5.1 and I reproduced that a few times.
It's tricky; when it starts working - never breaks again for me. I was able to reproduce that by creating a new pair of users.

**Comment by eVoloshchak** [comment] 2023-11-06 19:11
My setup is similar (M1 pro, but I'm using macOS14), but still cannot reproduce this one even when creating new accounts
Asked on Slack for this to be reassigned, maybe others would be able to reproduce the issue

**Comment by situchan** [comment] 2023-11-10 14:15
updating today

**Comment by situchan** [comment] 2023-11-10 15:27
After some random testing, I reproduced this on web rather than desktop. I think the issue is not limited to desktop app. And it seems related to navigation logic.

<img width="1174" alt="not found" src="https://github.com/Expensify/App/assets/108292595/8950ae0a-1d61-4a2f-92ff-b3a1c4a84ee2">

**Comment by ikevin127** [comment] 2023-11-10 15:48
What are the parameters of reproducing this issue on web, what were the actions performed exactly ?

I'd argue that the reported not found page on web has nothing to do with the RCA of this web to desktop deep-linking issue. If it can be determined precisely that both have the same root cause then I'll update my proposal if needed, otherwise I'd keep the 2 issues separated.

**Comment by situchan** [comment] 2023-11-16 14:31
still we're trying to have constant repro step

**Comment by situchan** [comment] 2023-11-27 17:41
I am able to reproduce report screen infinite loading bug constantly. Should we fix it here?

**Comment by situchan** [comment] 2023-12-05 00:08
Same

**Comment by barttom** [comment] 2023-12-05 08:05
@situchan  can we go with this solution https://github.com/Expensify/App/issues/29372#issuecomment-1781304603
by @ikevin127 ?

**Comment by ikevin127** [comment] 2023-12-05 10:41
Even though we've had a fix for more than 1 month, unfortunately none of the C+ assigned so far were able to reproduce the issue.

I can still reproduce the issue as of today.

**Note**: as a matter of fact it's even worse - currently on latest staging desktop the not found page seems to show everytime a deeplink of shared profile is opened from web, no matter if user is already authenticated or not on the desktop app. Same with local dev app, the infinite loading happens everytime.

<details>
<summary>MacOS: Desktop (staging / local)</summary>

- staging

https://github.com/Expensify/App/assets/56457735/45b8bf29-b20d-40eb-a70d-13d0f11014d3

- local dev

https://github.com/Expensify/App/assets/56457735/62539823-384f-4ae5-99f8-e0a2c203817e

</details>

To fix the issue accounting for the new developments I:
### Updated my proposal https://github.com/Expensify/App/issues/29372#issuecomment-1781304603
#### ___

Unless @barttom which was able reproduce the issue in the past can act as a proxy for @situchan to help with reviewing proposals / testing solutions OR can be assigned as C+ in case **situchan** is willing to pass the issue, I don't think this issue will progress.

Recent slack conversation: https://expensify.slack.com/archives/C01GTK53T8Q/p1701106810664189

**Comment by situchan** [comment] 2023-12-05 10:45
@ikevin127 I am not ignoring this issue but keep tracking.
can you check if this is still reproducible on main after applying https://github.com/Expensify/App/pull/32158

**Comment by situchan** [comment] 2023-12-05 10:49
Also I was holding based on https://github.com/Expensify/App/issues/29372#issuecomment-1828517580.
If we wanna fix infinite loading here (I can reliably reproduce), we can go ahead.
@NicMendonca seems like https://github.com/Expensify/App/issues/31195 is being fixed internally and different from this one.

**Comment by NicMendonca** [comment] 2023-12-11 15:33
@situchan bump ^^

**Comment by situchan** [comment] 2023-12-14 21:02
@NicMendonca do you agree https://github.com/Expensify/App/issues/29372#issuecomment-1840500266?

**Comment by NicMendonca** [comment] 2023-12-14 22:11
Looks like https://github.com/Expensify/App/issues/31195 is being closed

**Comment by NicMendonca** [comment] 2023-12-14 22:18
Based on this post [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859), I am going to close this

@situchan feel free to start a brand new discussion around infinite loading

**Closed by NicMendonca** 2023-12-14 22:18 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by ikevin127** [comment] 2023-12-15 16:30
I will handle it here https://github.com/Expensify/App/issues/33149, all good !
