### ISSUE TITLE
[HOLD for payment 2023-11-03] [$500] [Scan/Receipt] User is able to enable flash while permission is not granted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27568] opened 2023-09-15 22:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click plus button => Request Money => Scan
2. While permission is not granted, click Flash button
3. Notice that Flash button is enable while permission is not granted

## Expected Result:
 Flash button should disable if there's no permission granted

## Actual Result:
User is able to enable flash while permission is not granted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/430eee1e-ff5c-4662-86f1-d5b6e742dc23

https://github.com/Expensify/App/assets/78819774/ab8ca03d-a3cc-4aed-9d78-ba82a7a574ec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hungvu193

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694579188856809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013af8889a83bae302</li>
        <li>Upwork Job ID: 1702811588960399360</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26982626</li>
<li>hungvu193 | Contributor | 26982628</li>
<li>hungvu193 | Reporter | 26982633</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-09-18 17:23
@abdulrahuman5196 what do you think about these proposals?

**Comment by abdulrahuman5196** [comment] 2023-09-27 05:18
TAL now

**Comment by laurenreidexpensify** [comment] 2023-09-28 03:14
@jjcoffee reaasigning, can you please take a look at the proposals above? thanks

**Comment by jjcoffee** [comment] 2023-09-28 13:43
@hungvu193's [proposal](https://github.com/Expensify/App/issues/27568#issuecomment-1722092521) LGTM! I think my preference is for an error message, as disabling the button may not be that obvious visually (or we could do both!). I don't know if we might need to seek some broader feedback on the expected behaviour here? @laurenreidexpensify 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by puneetlath** [comment] 2023-10-02 10:57
Chatted with @dylanexpensify and we agreed that we should just disable the button without throwing any error message. Does that change your choice of proposal @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2023-10-02 11:10
It seems @jjcoffee  has been re-assigned this issue to review.

**Comment by jjcoffee** [comment] 2023-10-02 16:02
@puneetlath We're good to stick with @hungvu193's [proposal](https://github.com/Expensify/App/issues/27568#issuecomment-1722092521) (they proposed first via Slack as the issue reporter).

**Comment by jjcoffee** [comment] 2023-10-26 13:19
Damn looks like the automation failed here!

**Comment by jjcoffee** [comment] 2023-10-26 13:23
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour was always there**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - just required more thorough testing**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. Go to FAB -> Request Money -> Scan
2. Deny permissions request
3. Verify that the flash button is disabled and pressing it does not do anything
Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2023-10-26 13:24
@puneetlath The PR for this [hit production](https://github.com/Expensify/App/pull/28680#issuecomment-1754049519) a couple weeks ago so this is ready for payment (the automation just failed). Thanks!

**Comment by puneetlath** [comment] 2023-10-27 13:43
Ah cool. @laurenreidexpensify mind handling that? Thanks!

**Comment by jjcoffee** [comment] 2023-11-01 11:53
@laurenreidexpensify Gentle bump on payment for this :bow:

**Comment by laurenreidexpensify** [comment] 2023-11-06 16:44
Sorry everyone I completely missed this when the automation failed. Looking now

**Comment by laurenreidexpensify** [comment] 2023-11-06 16:47
Payment Summary

- Bug reporter @hungvu193 $50 - payment issued in Upwork
- Contributor - @hungvu193 $500 - payment issued in Upwork
- C+ @jjcoffee $500 - payment issue in Upwork

**Closed** 2023-11-06 16:55 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by hungvu193** [comment] 2023-11-07 07:10
@laurenreidexpensify I think this issue is eligible for urgency bonus, It was approved and merged within 3 days. cc @jjcoffee

**Comment by jjcoffee** [comment] 2023-11-14 17:53
@hungvu193 If you post timestamps it helps to verify - IIRC this one was right on the edge.

**Comment by hungvu193** [comment] 2023-11-15 02:40
Yeah, I was assigned on Oct 2, 11:05 PM and the PR was approved on Oct 5, 1:18 AM. So I believe this is still within 3 days.
<img width="849" alt="Screenshot 2023-11-15 at 09 28 37" src="https://github.com/Expensify/App/assets/16502320/01e93698-7f43-4856-a6af-bda8f2597072">
<img width="989" alt="Screenshot 2023-11-15 at 09 28 54" src="https://github.com/Expensify/App/assets/16502320/8f33a7f7-07b6-4487-bb0f-a3298e4c43a9">

**Comment by jjcoffee** [comment] 2023-11-15 09:30
@hungvu193 The bonus usually applies for time to merge rather than to C+ approval. The merge happened 52 minutes too late - sometimes this is taken into account, but it's up to the BZ. cc @laurenreidexpensify :sweat_smile:

**Comment by hungvu193** [comment] 2023-11-15 09:33
> @hungvu193 The bonus usually applies for time to merge rather than to C+ approval. The merge happened 52 minutes too late - sometimes this is taken into account, but it's up to the BZ. cc @laurenreidexpensify :sweat_smile: 

I remembered we talked about this cassette before and the bonus will be applied for C+ approval time if there was no requested change after that, which is this cassette 😄
