### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] Android - IOU-App crashes on request money with new user on deleting request.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33800] opened 2023-12-30 19:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap fab---request money---manual
3. Enter an amount
4. Tap next
5. Select a new user
6. Tap request
7. Tap on IOU created to open IOU details page
8. Tap 3 dots on top right and note header is greyed out
9. Tap delete request and confirm delete

## Expected Result:
App must not crash on request money with new user on deleting request.

## Actual Result:
App crashes on request money with new user on deleting request.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4802741f-1276-4d0d-8e4a-e3766a367204

[log crash.txt](https://github.com/Expensify/App/files/13798975/log.crash.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ebef5d4acfc8b7d</li>
        <li>Upwork Job ID: 1741172356572065792</li>
        <li>Last Price Increase: 2023-12-30</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 28101997</li>
<li>abzokhattab | Contributor | 28101998</li>
</ul></li>
    </ul>
</details>

**Comment by rashidkarim11** [comment] 2023-12-30 22:14
a

**Comment by rashidkarim11** [comment] 2023-12-30 22:15
aa

**Comment by rashidkarim11** [comment] 2023-12-30 22:17
aa

**Comment by rashidkarim11** [comment] 2023-12-30 22:26
a

**Comment by rashidkarim11** [comment] 2023-12-30 22:29
Contributor details
Your Expensify account email: rashidkarim35.76@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0150aa8a8cbde87533

**Comment by sakluger** [comment] 2024-01-02 21:41
This looks like a duplicate of https://github.com/Expensify/App/issues/33295 so I am going to close in favor of that one. The only difference is the platform, but the behavior is exactly the same.

@abzokhattab if you think your proposal will solve the other issue, could you please repost your proposal on https://github.com/Expensify/App/issues/33295? Thanks!

**Comment by abzokhattab** [comment] 2024-01-10 16:39
@sakluger  gentle bump

**Comment by abzokhattab** [comment] 2024-01-15 10:44
@sakluger kindly reminder!

**Comment by cristipaval** [comment] 2024-01-15 14:44
Thanks @aimane-chnaif for flagging the other crash as well!

**Comment by sakluger** [comment] 2024-01-30 17:34
Hey @aimane-chnaif, can you please complete the BZ checklist so I can close the issue out after payment tomorrow? Thanks!

**Comment by sakluger** [comment] 2024-01-31 20:53
All paid out, thanks everyone!

**Closed by sakluger** 2024-01-31 20:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
