### ISSUE TITLE
[$500] Android/mWeb/Safari - Setting - The save button doesn't get disabled when the profile photo is removed without uploading  @adeel0202

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9727] opened 2022-07-06 00:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account in NewDot
2. Go to Settings
3. Go to Profile
4. Click on the Edit Photo icon
5. Select any photo
6. Click on the photo
8. Click on the Remove Photo option
9. Click on the Save button

## Expected Result:
The button is disabled after saving the profile

## Actual Result:
The button is not disabled after saving the profile

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Android
- Mobile Web/Safari

**Version Number:** 1.1.79.17

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/177440248-e6cb2396-cffc-4a27-9003-f46a9174a751.mov

https://user-images.githubusercontent.com/93399543/177564633-149f8c27-fb12-4a86-893e-e8a80f588f04.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @adeel0202

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654609173650399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sobitneupane** [comment] 2022-07-06 06:29
**Proposal:**
The reason is `isAvatarChanged` remains true in the condition mentioned in this issue. To solve this issue, we can either move `this.setState({isAvatarChanged: false});` out of the if statement.
https://github.com/Expensify/App/blob/95d831d67e5d44a0b1fec5b6e1ad560242d4b914/src/pages/settings/Profile/ProfilePage.js#L179
Or do following changes in `updateAvatar()` function 
https://github.com/Expensify/App/blob/95d831d67e5d44a0b1fec5b6e1ad560242d4b914/src/pages/settings/Profile/ProfilePage.js#L157-L159
```
   updateAvatar(avatar) {
        this.setState({avatar: _.isUndefined(avatar) ? {uri: ReportUtils.getDefaultAvatar(this.props.myPersonalDetails.login)} : avatar},
        ()=>{
            if(this.state.avatar.uri === this.props.myPersonalDetails.avatar){
                this.setState({isAvatarChanged: false});
            } else {
                this.setState({isAvatarChanged: true});
            }
        });
        
    }
```

**Comment by MitchExpensify** [comment] 2022-07-06 21:43
[Upwork Job](https://www.upwork.com/jobs/~01f638130daf2f58c9)

**Comment by Santhosh-Sellavel** [comment] 2022-07-07 02:03
This is duplicate of #8037

**Comment by adeel0202** [comment] 2022-07-07 06:15
How is this duplicate? The other issue is about the save button getting disabled/unclickable after removing the profile picture and uploading again. This one is about the save button NOT getting disabled/unclickable after uploading a picture and then removing it.
Both have completely different steps and different issues so doesn't look like a duplicate to me.

**Comment by adeel0202** [comment] 2022-07-07 06:18
Also, the other issue was closed because it was not reproducible anymore. This issue is still reproducible.

**Comment by phuongpt** [comment] 2022-07-07 08:51
My proposal:
![Screen Shot 2022-07-07 at 15 49 12](https://user-images.githubusercontent.com/4443583/177732812-f44788e5-5ad0-4e07-abea-8fa8b3cc40b9.png)

Results
![Simulator Screen Shot - iPhone 12 - 2022-07-07 at 15 28 23](https://user-images.githubusercontent.com/4443583/177728916-3499cd0f-caf1-4c48-b4b5-c6270409a292.png)

**Comment by Santhosh-Sellavel** [comment] 2022-07-10 20:33
Ya @adeel0202 this is not a duplicate but similar to that one. 
Let's hold on to this issue, this needs to be discussed before accepting any proposals.

cc: @thienlnam

**Comment by MitchExpensify** [comment] 2022-07-19 21:24
Doubled the price! 

Please submit a proposal for eventual reporting bonus @adeel0202

**Comment by thienlnam** [comment] 2022-07-19 22:02
Just want to make sure my understanding of this issue is correct

1. Select a new profile picture (Don't hit save)
2. Remove the profile picture
3. Hit Save
4. The save button should have been disabled in 3 because the profile picture did not change?

**Comment by thienlnam** [comment] 2022-07-19 22:04
I think this is a valid issue, feel free to review proposals @Santhosh-Sellavel

**Comment by dhairyasenjaliya** [comment] 2022-07-20 11:04
**Proposal**

- Here for this issue, currently, we don't have any validation regarding the latest selected profile vs the old saved profile what actually need to do is to compare both profiles and check if we have changed "isAvatarChanged" and also to check latest vs previously saved profile is same or not 

**Solution** 

- Here my suggestion is to add one more logical condition to check whether the user has changed picture in the current state and compare both previous saved profile vs the latest local upload (yet to save as latest)

https://github.com/Expensify/App/blob/95d831d67e5d44a0b1fec5b6e1ad560242d4b914/src/pages/settings/Profile/ProfilePage.js#L213-L218

Change to below condition for very last logic line number 218

     && (!this.state.isAvatarChanged || this.props.currentUserPersonalDetails.avatarUploading || this.state.isAvatarChanged && this.state.avatar.uri === this.props.currentUserPersonalDetails.avatar);

- this.state.isAvatarChanged && this.state.avatar.uri === this.props.currentUserPersonalDetails.avatar
- condition is simple to check very first if user has upload new picture (isAvatarChanged) + compare new photo (this.state.avatar.uri) with old profile pic (this.props.currentUserPersonalDetails.avatar)

**Result** 

iPhone

https://user-images.githubusercontent.com/47522946/179966699-ac5aba74-7d54-4951-8116-ec6542bb21f4.mp4

Web


https://user-images.githubusercontent.com/47522946/179967020-93e4d939-e63d-4e58-ac97-3f2afad585a4.mov





cc @Santhosh-Sellavel

**Comment by Puneet-here** [comment] 2022-07-20 19:43
Hey @thienlnam, I saw that there were some similar issues about button being disabled/enabled and the consensus was according to design (it is some internal design doc, was mentioned by @roryabraham) we should keep the button always enabled and we should only disable it when there is some process going on (e.g. user saves profile now we should disable the button until the profile gets updated) we does the same at some places e.g. workspace general settings

**Comment by thienlnam** [comment] 2022-07-20 22:12
> What about the cause, where a user who had a Picture A set as an avatar a long time back, now decided to change it to Picture B but before hitting Save the user would like to stick to Picture A itself. What should the user do now?

They can just exit out without saving and it won't change their profile picture

@roryabraham Is there a preference here? I'm along the lines of we should only enable the button if there is a change that would be made.  On the profile picture currently if you change your name the 'Save' button is enabled, but if you change it back to what it was, the 'Save' button gets disabled

**Comment by roryabraham** [comment] 2022-07-20 23:37
> @roryabraham Is there a preference here? I'm along the lines of we should only enable the button if there is a change that would be made. On the profile currently if you change your name the 'Save' button is enabled, but if you change it back to what it was, the 'Save' button gets disabled

Yeah @Puneet-here is correct. See the [New Expensify Forms](https://docs.google.com/document/d/1DI4jQ0nyfi2JczhPT440orwlXsTP_O-aGvg-HLmcbwI/edit#bookmark=id.820d3lub0uma) doc:

> Submit buttons shall not be disabled or blocked from being pressed in most cases. We will allow the user to submit a form and point them in the right direction if anything needs their attention.
>
> The only time we won’t allow a user to press the submit button is when we have submitted the form and are waiting for a response (e.g. from the API). In this case we will show a loading indicator and additional taps on the submit button will have no effect. This will also ensure that a form cannot be submitted multiple times.

For now we should try to keep consistent with these guidelines.

**Comment by thienlnam** [comment] 2022-07-21 00:47
Okay sweet, in that case we don't need this issue - works as expected

**Closed by thienlnam** 2022-07-21 00:47 UTC
Labels: Exported, External, Engineering, Monthly, Improvement, Help Wanted

**Comment by adeel0202** [comment] 2022-07-21 06:21
@roryabraham I still think this is a bug. @Puneet-here would be correct if this issue was happening in the workspace-settings screen, where the save button is always enabled. This issue is in the profile-settings screen where the save button is always disabled and only gets enabled when there are some unsaved changes. In this case, there are no unsaved changes, and still save button is enabled.

Also on this screen, when there are unsaved changes and the button is enabled then after pressing the button, the changes get saved and the button is disabled again indicating that the changes are saved and there are no unsaved changes now. However, in this scenario, the save button gets enabled and never gets disabled even after pressing the button multiple times.

This is inconsistent behavior on the same screen and looks like a bug to me. If you still think this is not an issue, you can ignore it.

**Comment by thienlnam** [comment] 2022-07-21 17:39
> This issue is in the profile-settings screen where the save button is always disabled and only gets enabled when there are some unsaved changes. In this case, there are no unsaved changes, and still save button is enabled.

cc @luacmartins I think we're still in the process of implementing these new form changes right? Seems like we can ignore for now until your issues come out?

**Comment by luacmartins** [comment] 2022-07-21 19:15
Yes! We can ignore this. We are currently refactoring the Profile Page to use Form as part of [this issue](https://github.com/Expensify/App/pull/9441).

**Comment by MitchExpensify** [comment] 2022-07-21 21:03
Upwork post removed
