### ISSUE TITLE
[$250] Back button doesn't work on desktop web 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10770] opened 2022-09-02 03:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on a convo
2. Hit CMD + K and switch to a different convo
3. Hit CMD + [ and notice you don't go back to the previous convo

## Expected Result:
User should navigate to previous conversation 

## Actual Result:
User doesnt navigate back 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/188050313-0a6ae3bb-0a20-432c-bfa9-b5f140ebb093.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660764803591309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-09-02 15:22
Posted in Upwork!

Internal job - https://www.upwork.com/ab/applicants/1565721583926935552/job-details
External job - https://www.upwork.com/jobs/~0112912de9b0fc283d

**Comment by amierhasan** [comment] 2022-09-02 21:05
Hello there,

I have reviewed your job post on Upwork. I have analyzed the issue in detail and the solution of the issue will be the following:
I will replace the current back functionality with its alternate function in the shortcuts.

Thanks.

**Comment by Santhosh-Sellavel** [comment] 2022-09-02 21:10
This seems issue related to #4612 or clearly navigation issue show should be put on hold.

cc: @pecanoro @marcaaron

**Comment by Santhosh-Sellavel** [comment] 2022-09-02 21:12
@amierhasan check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) to understand our process. Please submit your proposals here on the relevant issue to get it reviewed thanks!

**Comment by bdmostafa** [comment] 2022-09-04 12:05
This problem is related to `react-navigation` settings. May be its previous state does not have in navigation state properly or `navigation.goBack()` is not working.

If there is `navigation.goBack()` issue in the project, I have to find out that whether `goBack()` function is fetched properly or from wrong path. Otherwise, if `navigation state` is not saved on this screen, I can use `reset` function passing to the specific route that you need.

**Comment by pecanoro** [comment] 2022-09-05 09:24
@Santhosh-Sellavel So we close this one then? It seems like a duplicate of https://github.com/Expensify/App/issues/4612 since it's referring to the same functionality.

**Comment by Santhosh-Sellavel** [comment] 2022-09-06 02:16
Yes @pecanoro

**Comment by Christinadobrzyn** [comment] 2022-09-06 08:46
Sounds good - closed the job in Upwork and closing this GH as a dupe of https://github.com/Expensify/App/issues/4612

**Closed by Christinadobrzyn** 2022-09-06 08:46 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
