### ISSUE TITLE
Web - User unable to select Delete button after click on copy to clipboard action of popover

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13293] opened 2022-12-02 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12917

## Action Performed:
1. Go to staging.new.expensify.com and log in
2. Open the context menu for any message
3. Click on copy to clipboard action of popover
4. On the same opened popover click Delete comment

## Expected Result:
User able to select Delete button after click on copy to clipboard action of popover.

## Actual Result:
User unable to select Delete button after click on copy to clipboard action of popover. Context menu is dismissing very quick. 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205397020-049f89d2-a91c-4356-985c-541177348f12.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2022-12-03 05:27
@kbecciv I think by the time you are clicking the delete option the timeout gets over and the popover gets closed. I am able to delete it when I quickly select the option and attach the video for both.

[3e902e73-b178-47bc-9094-9580546fcd06.webm](https://user-images.githubusercontent.com/14358475/205425454-8aa079ec-b9fe-44e9-b39b-e37247feb138.webm)

**Comment by tienifr** [comment] 2022-12-03 07:33
# Proposal:

## Problem
The problem is from the `onPress()` function in ContextMenuActions. It only leaves the mini-menu open after the user press on the item, but not the popup menu.

In my opinion, it is an expected behavior on small devices, but maybe not for the web version. The user should not be required to press one more time to close the popup after copying the text, and the popup should only be closed when the user try to delete the message. Maybe it is the intention of the developer, but in case it is not, here is my solution proposal.

## Solution

First, modify the behaviour of the delete button so that the menu would disappear and the confirmation box can display
In https://github.com/Expensify/App/blob/82139c8e8d72d3e781ff6dd183991fc5ffb9ca7b/src/pages/home/report/ContextMenu/ContextMenuActions.js#L193-L205

Change
```
     onPress: (closePopover, {reportID, reportAction}) => {
            if (closePopover) {
                // Hide popover, then call showDeleteConfirmModal
                hideContextMenu(
                    false,
                    () => showDeleteModal(reportID, reportAction),
                );
                return;
            }

            // No popover to hide, call showDeleteConfirmModal immediately
            showDeleteModal(reportID, reportAction);
        },
```

to

```
     onPress: (closePopover, {reportID, reportAction}) => {
           // Hide popover, then call showDeleteConfirmModal
           hideContextMenu(
               false,
               () => showDeleteModal(reportID, reportAction),
           );
        },
```

### Solution 1: In `BaseReportActionContextMenu.js`, change the behavior of the copy button on large screen (web) only

In https://github.com/Expensify/App/blob/82139c8e8d72d3e781ff6dd183991fc5ffb9ca7b/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L70

Change

```
contextAction.onPress(!this.props.isMini, ...
```

to

```
contextAction.onPress(this.props.isSmallScreenWidth, ...
```

### Solution 2: In `BaseReportActionContextMenu.js`, change the behaviour of the copy button on all device
In https://github.com/Expensify/App/blob/82139c8e8d72d3e781ff6dd183991fc5ffb9ca7b/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L70

Change

```
contextAction.onPress(!this.props.isMini, ...
```

to

```
contextAction.onPress(false, ...
```

### Solution 3: In `BaseReportActionContextMenu.js`, change the behaviour of the copy button on all device
In https://github.com/Expensify/App/blob/82139c8e8d72d3e781ff6dd183991fc5ffb9ca7b/src/pages/home/report/ContextMenu/ContextMenuActions.js#L119-L121

Change

```
if (closePopover) {
     hideContextMenu(true, ReportActionComposeFocusManager.focus);
}
```

to

```
hideContextMenu(true, ReportActionComposeFocusManager.focus);
```


## Result
### Web
https://user-images.githubusercontent.com/113963320/205430096-3dc6454b-fb8b-4c64-8439-c603d8d0624c.mp4



### Mobile
https://user-images.githubusercontent.com/113963320/205430101-1023851d-78a3-4786-884b-73107257a032.mp4

**Comment by s77rt** [comment] 2022-12-04 11:08
Isn't this actually intended?
It's a feature not a bug I suppose

**Comment by JmillsExpensify** [comment] 2022-12-05 13:56
Oh great catch! What's odd is that this issue was reported a couple of days ago, and that linked issue/PR would have long already been on staging and production.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:58
As for @s77rt's comment, I agree that this is intended behavior. A user shouldn't be able to click options on the comment action menu twice, so I'm going to close this issue regardless.

**Closed by JmillsExpensify** 2022-12-05 13:58 UTC
Labels: Daily, Bug
