### ISSUE TITLE
[$500] IOU - "Waiting for you to approve..." shows up for the admin while there is an approver setup

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39199] opened 2024-03-28 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4455456
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisites:
- Have a collect WS on OD
- Enable chat for ND
- Invite an Employee to the WS
- Invite another admin and make that user an approver

1. [Employee] Sign into OD and create a report and add an expense to it
2. [Admin] Sign into ND and Open the workspace chat
3. [Admin] Click on the preview component to open the report conversation
4. [Admin] Click on Submit on the header
5. [Admin] Observe the next steps on the header
6. [Admin] Go back to the workspace chat and click on the IOU preview to open the report conversation again and observe the next steps header again

## Expected Result:
"Waiting for [approver email] to approve ..." should show up right after admin clicks on the submit button.

## Actual Result:
"Waiting for you to approve ..." message appears as the next steps for the admin after admin clicks on submit and the message doesn't update to the right one unless admin goes back to workspace chat and returns back to report conversation.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8f5d3ec0-4a05-48f5-8bf1-d8ba2ccea757

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd32e3a37f04cf21</li>
        <li>Upwork Job ID: 1773451082653679616</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-28 17:24
We think this issue might be related to the #collect project.

**Comment by abzokhattab** [comment] 2024-03-28 22:49
Hi @GandalfGwaihir have you tried to run your solution? I think the changes will not change anything in the behavior.

**Comment by abzokhattab** [comment] 2024-03-28 23:02
I believe the code is identical to what we currently have; it has just been rewritten. (talking about the `message` array)

**Comment by nkdengineer** [comment] 2024-03-29 07:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Waiting for you to approve ..." message appears as the next steps for the admin after admin clicks on submit and the message doesn't update to the right one unless admin goes back to workspace chat and returns back to report conversation.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L208) we're hardcoding `you` in all cases, while there could be cases that the current user (Admin) is viewing an Expense of an Employee, and Admin should see message like `Employee is waiting for Approver to approve these these expenses.`

### What changes do you think we should make in order to solve the problem?

Change [this](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L208) to 
```
text: managerDisplayName,
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-03-29 07:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Waiting for you to approve ..." message appears as the next steps for the admin after admin clicks on submit and the message doesn't update to the right one unless admin goes back to workspace chat and returns back to report conversation.

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L208) we're hardcoding `you` in all cases, while there could be cases that the current user (Admin) is viewing an Expense of an Employee, and Admin should see message like `[Submitter] is waiting for [Approver] to approve these these expenses.`

To clarify, there're 2 types of next step messages based on who is currently viewing the next step message:
1. The current logged in user is the person waiting for the next step (eg. Employee/Admin waiting for Approver to approve)

In this case the message will look like
```
Waiting for [Approver] to approve these expenses.
```
Which is covered by [this optimistic next step logic](https://github.com/Expensify/App/blob/main/src/libs/NextStepUtils.ts#L225-L243)

2. The current logged in user is **not** the person waiting for the next step

In this case the message will look like
```
[Submitter] is waiting for [Approver] to approve these these expenses.
```
This is covered by [this optimistic next step logic](https://github.com/Expensify/App/blob/main/src/libs/NextStepUtils.ts#L196-L222)

The bug here is in the 1st case, where the `[Approver]` is hardcoded as `you`, which is wrong in case the viewing user is not the approver.

### What changes do you think we should make in order to solve the problem?

Change [this](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L208) to 
```
text: managerDisplayName,
```

The `managerDisplayName` will show `you` or `manager login` based on whether the current user is the approver ([reference](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L81))

### What alternative solutions did you explore? (Optional)
We should double check other optimistic next step messages to make sure they don't have similar bugs.

**Comment by cubuspl42** [comment] 2024-03-29 09:32
@GandalfGwaihir @nkdengineer 

Would you help me figure out the differences between your proposals? (I'm talking about the [updated version](https://github.com/Expensify/App/issues/39199#issuecomment-2026331633) of @GandalfGwaihir's proposal)

**Comment by cubuspl42** [comment] 2024-03-29 09:41
🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-03-29 09:45
@rlinoz

@GandalfGwaihir noticed that this optimistic message...

https://github.com/Expensify/App/blob/cb71f33e529eac374b76478c9e6a2d9147beebf5/src/libs/NextStepUtils.ts#L199-L221

...is not in sync with the backend. If I understood this correctly, the backend doesn't seem to support it. @GandalfGwaihir suggests completely removing it from the frontend.

Do you know whether this is the right course, or maybe it's the backend which should be adjusted?

**Comment by rlinoz** [comment] 2024-03-29 18:09
I don't think we want to remove the first block because that is how we display to the approver himself.

<img width="636" alt="image" src="https://github.com/Expensify/App/assets/5201282/9f26c26c-be8d-4310-a179-84487865f34e">

I think we might just need to change the if to something like `if (isOwner || !isManager)`, then we would show the same way the backend is sending.

<img width="637" alt="image" src="https://github.com/Expensify/App/assets/5201282/d7e561fd-7ff7-43ec-bba7-357cf261504c">

**Comment by rlinoz** [comment] 2024-03-29 18:09
Also I see that `SubmitReport` is not sending the nextStep back, maybe it should?

**Comment by rlinoz** [comment] 2024-03-29 18:36
Huum, @GandalfGwaihir are the images reversed? 

The first image should be the approver case.

**Comment by rlinoz** [comment] 2024-03-29 18:46
Yeah, but who is the approver? Only the approver should get the `is waiting for you to review...`.

If you didn't change anything it should be the policy owner, and the prints are correct now, but just making sure.

**Comment by rlinoz** [comment] 2024-03-29 18:54
Cool, if @cubuspl42 is ok with this changes we can proceed 😄

**Comment by nkdengineer** [comment] 2024-03-30 05:55
> Cool, if @cubuspl42 is ok with this changes we can proceed 😄

@rlinoz @cubuspl42  [My proposal](https://github.com/Expensify/App/issues/39199#issuecomment-2026831327) already contains this solution in the alternative solution part (well before @rlinoz [suggested similar solution](https://github.com/Expensify/App/issues/39199#issuecomment-2027562577) and @GandalfGwaihir updated [the proposal](https://github.com/Expensify/App/issues/39199#issuecomment-2027580364)). Please see the quoted part below:

> If we want the 1st scenario to show not only in case the submitter is current user, but also the case where another person (which is not the approver) views the report, we can update [this](https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L225) to

**Comment by nkdengineer** [comment] 2024-03-30 07:51
> isSelfApproval checks whom the report has been submitted to rather than who the approver of the report is :)

@GandalfGwaihir I don't think so, if you look at [this](https://github.com/Expensify/App/blob/14ff9445d22bd92d0645abd456ac805cedc06c28/src/libs/NextStepUtils.ts#L81), the approver that we'll be showing as the one to take action here, is the one in `submitsTo`, not the `managerId`

If you indeed found there's a regression, could you clarify the steps to reproduce?

**Comment by nkdengineer** [comment] 2024-04-02 06:08
> @cubuspl42 is OOO today, and I couldn't check if the isSelfApproval solution yields the same result, will get to that tomorrow.

@rlinoz I've tested many scenarios from different account roles and all are correct according to [the expectation](https://github.com/Expensify/App/issues/39199#issuecomment-2027598338). Let me know if you want to clarify anything before moving forward.

**Comment by cubuspl42** [comment] 2024-04-03 12:33
I'm catching up! Thanks, Rodrigo, for all the input; I tagged you because I was under the impression that we'll need some backend insights.

I'm catching up

**Comment by cubuspl42** [comment] 2024-04-03 12:42
Okey, so summing up:

@nkdengineer was the first one to suggest changing the condition of this block:

https://github.com/Expensify/App/blob/5a8cb7fb94eeb16cfad5407dd9495be1f0a921b9/src/libs/NextStepUtils.ts#L224-L225

They suggested changing it to...

```ts
if (!isSelfApproval) {
  // ...
}
```

After the discussion, @GandalfGwaihir agreed with Rodrigo to change the mentioned condition to...

```ts
if (isOwner || !isManager) {
  // ...
}
```

As I understand it, these conditions **might** be equivalent in practice.

> If you indeed found there's a regression, could you clarify the steps to reproduce, and a video of the same?

@GandalfGwaihir Would you agree to provide this info? I'd like to know whether there is an observably different case between these two conditions.

**Comment by rlinoz** [comment] 2024-04-04 14:21
@GandalfGwaihir can you help us with the comment above?

**Comment by nkdengineer** [comment] 2024-04-04 14:34
> And the other one is obviously for Control Policies, there we can have multiple submitters and multiple approveres, also:

@GandalfGwaihir Please help clarify clear reproducible steps if you found a regression, thanks!

**Comment by nkdengineer** [comment] 2024-04-04 14:47
> Well we need to create control policy on OD and create multiple approvers for a request and set who approves to whom, No clear regression steps that i can think of but control policies are more complex in terms of approval settings ;)

@GandalfGwaihir In this case the `submitsTo` will also reflect the approver that will need to approve the report at each step, so `!isSelfApproval` approach will still work well. Let us know if you indeed found a specific case that proves otherwise.

**Comment by mountiny** [comment] 2024-04-04 23:11
I agree with @nkdengineer that the fact we do not set the submitsTo optimistically can cause some of these issues, I had similar conclussions when working on this PR https://github.com/Expensify/App/pull/39563/files (that mainly focuses on the offline case of creating a new workspace and then submitting a report there)

**Comment by cubuspl42** [comment] 2024-04-05 08:01
Okay, everyone, thanks for the polite discussion!

I appreciate your input, @GandalfGwaihir, but your updated proposal was mostly inspired by Rodrigo's words, while @nkdengineer suggested something likely equivalent (no limitation has been proved), but independently.

In my opinion, it's fair to let @nkdengineer handle this one

C+ reviewed 🎀 👀 🎀

**Comment by rlinoz** [comment] 2024-04-05 13:47
Thanks all, assigning @nkdengineer

**Comment by rlinoz** [comment] 2024-04-08 13:11
Moving to weekly, but when can we expect a PR @nkdengineer ?

**Comment by mountiny** [comment] 2024-04-08 13:43
@nkdengineer a friendly reminder, I have seen you post proposals for other issues, please prioritize assigned issues and opened PRs over making new proposals. Thank you!

**Comment by nkdengineer** [comment] 2024-04-09 01:40
@mountiny Noted, thanks!

**Comment by rlinoz** [comment] 2024-04-22 19:54
Deployed to prod

**Comment by slafortune** [comment] 2024-04-30 15:42
Deployed to production 4/22 - 4/29 should have been paid day!  Automated system didn't update

**Comment by slafortune** [comment] 2024-04-30 18:57
@nkdengineer offer sent here - https://www.upwork.com/nx/wm/offer/102103500
@cubuspl42  - Paid ✅

**Comment by slafortune** [comment] 2024-05-02 19:49
@nkdengineer Paid ✅

**Closed by slafortune** 2024-05-02 19:49 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
