### ISSUE TITLE
[$500] Android - The toggle attribution button is not placed on the right position

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27111] opened 2023-09-10 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. Change the tab to distance
3. Notice the toggle attribution button

## Expected Result:
The toggle attribution button should be on the bottom right corner of the map

## Actual Result:
The toggle attribution button is next to mapbox button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_20230910-183405_New Expensify](https://github.com/Expensify/App/assets/93399543/b39b2a6a-bb5b-4ec0-9ce2-b44ea798be4f)

![Screenshot_20230910_113828_New Expensify](https://github.com/Expensify/App/assets/93399543/e49122d8-88d2-479e-9843-d5bcabdf6eed)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693920729499719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01635cf17e44f76483</li>
        <li>Upwork Job ID: 1700897704277868544</li>
        <li>Last Price Increase: 2023-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26641403</li>
<li>ZhenjaHorbach | Contributor | 26641406</li>
<li>jo-ui | Reporter | 26641407</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-10 16:42
### Proposal
### Please re-state the problem that we are trying to solve in this issue.

The toggle attribution button is not placed on the right position
### What is the root cause of that problem?
This is Mapbox issue  by default in Android `bottom left`

https://docs.mapbox.com/help/getting-started/attribution/#mapbox-maps-sdk-for-android
```javascript
  /**
   * Adds attribution offset, e.g. `{top: 8, left: 8}` will put attribution button in top-left corner of the map. By default on Android, the attribution with information icon (i) will be on the bottom left, while on iOS the mapbox logo will be on bottom left with information icon (i) on bottom right. Read more about mapbox attribution [here](https://docs.mapbox.com/help/getting-started/attribution/)
   */
  attributionPosition?: OrnamentPositonProp;

``` 

### What changes do you think we should make in order to solve the problem?
we can pass `attributionPosition` `{ right : 8, bottom : 8 }`

if we need hide this attribution
attributionEnabled false on native
attributionControl false on web

**Comment by PiyushChandra17** [comment] 2023-09-11 05:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The toggle attribution information(i) button is placed in wrong position

### What is the root cause of that problem?
By default, the position of toggle attribution information(i) button is bottom left on android, we are missing the `attributionPosition` props in MapView component (attributionPosition: `OrnamentPositonProp`). Hence this is the root cause.

### What changes do you think we should make in order to solve the problem?
[In MapView](https://github.com/Expensify/App/blob/main/src/components/MapView/MapView.tsx#L62), We should apply the following changes:

1. import `Platform` module from react-native
2. Add the `attributionPosition` prop and set it to `{bottom: 8, right: 8}` in `<Mapbox.MapView />` component.

```
<Mapbox.MapView
    style={{flex: 1}}
    styleURL={styleURL}
    onMapIdle={setMapIdle}
    pitchEnabled={pitchEnabled}
    attributionPosition={Platform.OS === "android" ? {bottom: 8, right: 8} : {bottom: 8, right: 8}}
    // eslint-disable-next-line
    {...responder.panHandlers}           
>
```

### What alternative solutions did you explore? (Optional)
NA

### Result:
![Screenshot_1694410787](https://github.com/Expensify/App/assets/47579287/9fc8522d-43b7-45b5-9118-abf48b434b88)

**Comment by jjcoffee** [comment] 2023-09-11 14:21
All the proposals here are essentially the same, identifying the correct RCA that the default on Android is to display the attribution toggle on the left with the logo (pretty strange inconsistency on Mapbox's part! :smile:). 

@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/27111#issuecomment-1712848831) was first, so happy to go with them! It also makes sense to me to explicitly set the positions of both logo and toggle now, in case Mapbox ever change their mind in the future and we end up with a new "bug" to fix!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by CortneyOfstad** [comment] 2023-09-15 13:37
@Christinadobrzyn there is a known issue with double-assignments when the `external` label is applied (more info [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1694513579526909)). Unassigning myself as the second assignee 👍

**Comment by jjcoffee** [comment] 2023-10-09 14:13
Hmm looks like the automation failed here. This was [deployed](https://github.com/Expensify/App/pull/27302#issuecomment-1723112483) to production Sept 18, so should be ready for payment @Christinadobrzyn.

**Comment by jjcoffee** [comment] 2023-10-13 11:04
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - this has existed since the beginning of the implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **No - pretty low impact**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by jjcoffee** [comment] 2023-10-13 11:04
@Christinadobrzyn I realised there was no checklist either, so I've added that. Also, friendly bump on payment!

**Comment by Christinadobrzyn** [comment] 2023-10-13 14:36
well that's annoying that this didn't become daily to remind me! Sorry for the delay here. 

Payouts due:

Issue Reporter: $50 @jo-ui (Paid in Upwork)
Contributor: $500 + $250 bonus @ZhenjaHorbach (Paid in Upwork)
Contributor+: $500 + $250 bonus @jjcoffee (Paid in Upwork)

Eligible for 50% #urgency bonus? Y - https://github.com/Expensify/App/issues/27111#issuecomment-1717864790

Upwork job is [here](https://www.upwork.com/jobs/~01635cf17e44f76483) (job is closed so I think that means it can't be viewed externally). 

Closing!

**Closed by Christinadobrzyn** 2023-10-13 14:36 UTC
Labels: Reviewing, External, Monthly, Bug
