### ISSUE TITLE
[HOLD for payment 2024-08-20] Bank account - Unable to proceed after website step when website is auto populated

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47227] opened 2024-08-12 12:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- User is logged in with Expensifail account.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows
3. Click Connect bank account > Connect manually
4. Proceed to Step 4 - Enter Company's Tax ID page
5. Enter Tax ID > Next
6. Note that the website field is auto populated with https://www.applause.expensifail.com./
7. Without editing the field, click Next.

## Expected Result:
The setup will proceed to the next step.

## Actual Result:
The setup is stuck on the same website step until user adds some edit to it.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/70e8bf3d-5929-41a3-8ab6-8e9bf3c81496

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by hannojg** [comment] 2024-08-12 13:07
> Looks related to #46796 (Not 100% sure).
> 
> @hannojg Can you look into this?

Hmm, on the first look it doesn't appear to me as related. The PR only changed the composer of the report page.

**Comment by hannojg** [comment] 2024-08-12 13:08
Yeah, none of the components used on the respective page with the bug was touched by the mentioned PR. I don't think the PR is related.

**Comment by NikkiWines** [comment] 2024-08-12 15:45
Repro'd locally - reverted [this](https://github.com/Expensify/App/pull/46940
) locally and it resolved the issue if while I was still on the add website page. But, of course, re-introduced the bug of skipping the website form if I restarted adding a bank account


cc: @bernhardoj @neil-marcellini

**Comment by NikkiWines** [comment] 2024-08-13 09:48
@suneox I'm still able to reproduce the issue 

https://github.com/user-attachments/assets/14a20bb5-fe03-4713-a9ec-d4d0f48754c4

**Comment by bernhardoj** [comment] 2024-08-13 11:18
I found the issue. This happens specifically after [removing this code](https://github.com/Expensify/App/pull/46940/files#diff-6f569e6096d8c880ae5d48d80854be64b0d3c1bd5454e5dac9819079e0049aaaL62-L64). 

What happen in this issue is that, when we press Next, the website draft Onyx data is still empty. It's only filled once we type into the text input. The linked code purpose is to save the generated website to the website draft Onyx.

But if we re-add that, then the website step gonna be skipped again because when we are at the tax ID step (step before the website step) and press next, the website step is mounted, the generated website is saved to the draft, then, a loading view is shown and then the step is remounted which will skip the website step because it's now contains a valid website. 

We need to wait for https://github.com/Expensify/App/issues/45278 before we can re-add the above logic back. Every time a step (not sub-step) view is mounted, the initial sub-step will be evaluated and https://github.com/Expensify/App/issues/45278 will prevent the step to be re-mounted every time we save a sub-step.

**Comment by bernhardoj** [comment] 2024-08-13 12:33
That works. I'll prepare a PR for that.

**Comment by bernhardoj** [comment] 2024-08-13 12:45
@suneox @NikkiWines The PR is here: https://github.com/Expensify/App/pull/47314

**Comment by Beamanator** [comment] 2024-08-13 18:00
Fix is being CP'd 👍

**Comment by Beamanator** [comment] 2024-08-13 18:44
@IuliiaHerets can you please retest this on staging? 🙏

**Comment by Beamanator** [comment] 2024-08-13 19:33
Confirmed this is fixed in staging!

**Comment by IuliiaHerets** [comment] 2024-08-13 19:44
@Beamanator sorry for delay. Website field is not auto populated now, but when enter it manually, `Next` button works 

https://github.com/user-attachments/assets/548b92aa-86ac-4a8b-a039-ca7be92b87c5

**Comment by bernhardoj** [comment] 2024-08-14 01:32
I was offline. Thanks for handling the PR!

**Comment by NikkiWines** [comment] 2024-08-15 08:40
This should be on prod now cc: @RachCHopkins

**Comment by RachCHopkins** [comment] 2024-08-20 07:28
@NikkiWines sorry I'm a little new to this, is this the standard $250? I believe @bernhardoj is paid via newdot manual requests, so we don't need an upwork job. And does anyone else need to be paid here?

**Comment by RachCHopkins** [comment] 2024-08-20 07:52
I am confused. It says hold for payment and I am being tagged. Do I simply... close the issue?

**Closed** 2024-08-20 21:22 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
