### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500] Chat - "Start a chat, get 250$" popup blocks recent contacts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32499] opened 2023-12-05 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.8.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Disable network on your phone
4. Tap on the FAB button
5. Tap on the Start chat button
6. Type in any email address

## Expected Result:
I should be albe to see at least one recent contact fully

EDITED:
This is expected - thanks @dannymcclain Here's a quick mock showing the x icon instead of the i icon.
![image](https://github.com/Expensify/App/assets/11725910/c4a51f71-ad30-4db0-beac-402500d777f4)

## Actual Result:
"Start a chat, get 250$" popup blocks recent contacts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8c5afb59-fa8f-4401-8431-fde32422dcc4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb186a7b7dd5933b</li>
        <li>Upwork Job ID: 1732096883915866112</li>
        <li>Last Price Increase: 2023-12-26</li>
    </ul>
</details>

**Comment by chiItepin** [comment] 2023-12-05 18:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "start a chart" referral overlaps a good size of the screen while keyboard is focused on mobile

### What is the root cause of that problem?
The "start a chart" referral component is designed to be sticky/fixed positioned, thus, it remains visible at all times regardless of input being focused

### What changes do you think we should make in order to solve the problem?

If the field is being focused, the The "start a chart" referral component would not behave as being sticky/fixed

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by yh-0218** [comment] 2023-12-05 19:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "start a chart" referral overlaps a good size of the screen while keyboard is focused on mobile

### What is the root cause of that problem?
The "start a chart" referral component is designed to be sticky/fixed positioned, thus, it remains visible at all times regardless of input being focused

### What changes do you think we should make in order to solve the problem?
1. we can reduce height for mobile version
2. we can update design (user can hide that when user click x button)

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-12-07 15:48
reviewing now

**Comment by DylanDylann** [comment] 2023-12-08 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Chat - "Start a chat, get 250$" popup blocks recent contacts
### What is the root cause of that problem?
- This issue occurs in a few mobile devices that have small height: The sticky button overlays the search results.

### What changes do you think we should make in order to solve the problem?
- Once the keyboard is opened, that means that the user want to search any contact rather than they want to click on the "Start a chat, get 250$".
- So I think, we can hide the "Start a chat, get 250$" if it is smallWithDevice and keyboard is opening. Do it by updating:
https://github.com/Expensify/App/blob/6129c679904e8569a24928f1963df03be0355748/src/pages/NewChatPage.js#L255
to:
```
                            shouldShowReferralCTA={!isMobileDevice || (isMobileDevice && !isKeyboardShown)}
```
- With:
```
    const {isKeyboardShown} = useKeyboardState();
    const isMobileDevice = !canFocusInputOnScreenFocus();
```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by slafortune** [comment] 2023-12-11 20:33
I'm not sure @abdulrahuman5196 , let's get their 2 cents on [this](https://github.com/Expensify/App/issues/32499#issuecomment-1845660276)!  Do you have some direction for us on how popup should act?

**Comment by dannymcclain** [comment] 2023-12-11 20:41
Hmm this is a tricky one. @dubielzyk-expensify since you worked on this (I think?) do you have any strong feelings about it? I'm tempted to say we should hide the promo banner when the keyboard is open, but I'm keen on Jon and the @Expensify/design team's thoughts.

**Comment by dubielzyk-expensify** [comment] 2023-12-11 22:26
Oh yeah, this isn't great. I like the idea of hiding the banner when the keyboard is open or reduce the spacing/padding (though there might not be much to gain from this). 

The problem though with hiding it on `input focus` is that I think we trigger that by default. So there's a world where users just never see the promo banner. 

I think we'll have to adjust the size. Looping in @jamesdeanexpensify

**Comment by shawnborton** [comment] 2023-12-12 13:47
I agree about hiding the banner when the keyboard is open. Have we also considered making this dismissible? Right now it permanently occupies this real estate, even after you've seen it for the 10th time. Not sure how I feel about that as it does start to feel a bit spammy.

**Comment by dannymcclain** [comment] 2023-12-12 13:52
Hmm good point Shawn. I'd be up for it being dismissible if you can get to the referral program somewhere else, too. Based on James' comment, I believe that you can. 👇 

> There are other ways to find the referral program in NewDot right now

I think if we _do_ end up making it dismissible, I would do nothing else in this situation. If it's in the way for a user, they can dismiss it. Boom. Donezo. No other hacking around necessary.

**Comment by DylanDylann** [comment] 2023-12-12 14:14
@dannymcclain @shawnborton 
- In my opinion, once the keyboard is opened, that means that the user wants to search for any contact rather than they want to click on the "Start a chat, get 250$". So we just need to hide it when the keyboard is opening rather than still displaying it and then user needs to click to do more action to dissmiss it.
- Also if we decide to make it dismissible, then when do we display it again?

**Comment by dannymcclain** [comment] 2023-12-12 14:35
- I think I disagree with your first point. When I go through the new chat flow, that input is automatically focused, which opens up my keyboard before I've even had a chance to look at the list of options. I never made an intentional choice to open the keyboard, it just happened immediately. So if we hide it while the keyboard is open, I actually don't think I would ever see that banner at all.
- I think if we made it dismissible, once the user dismissed it, we would not show it again. @Expensify/design does that sounds like what y'all were thinking?

**Comment by shawnborton** [comment] 2023-12-12 14:38
> So if we hide it while the keyboard is open, I actually don't think I would ever see that banner at all.

This is a great point Danny! And an argument to **always** show the banner but make it dismissible. 

> I think if we made it dismissible, once the user dismissed it, we would not show it again. @Expensify/design does that sounds like what y'all were thinking?

That's what I was thinking personally. Curious what @jamesdeanexpensify thinks about that.

**Comment by DylanDylann** [comment] 2023-12-12 15:01
@dannymcclain 

> So if we hide it while the keyboard is open, I actually don't think I would ever see that banner at all.

With this point, my suggestion is to hide the keyboard once the keyboard is opened and text search is not empty

**Comment by jamesdeanexpensify** [comment] 2023-12-12 18:02
- Just FYI, a version of this banner is also visible in other flows (in addition to the "Start chat" flow, it's also included in: the "Request money" flow, the "Send money" flow, and when you click into the general search tool/magnifying glass ), so whatever we decide here should be extended to those 
- I think most of us (including me) agree on the **very** next step being to make this banner dismissible. If we can at least move forward there, I think we're making progress. So perhaps we could just replace the circled "i" with an "x" to make the banner dismissible? 

Maybe we just start there and see if things are still annoying after that.

**Comment by dannymcclain** [comment] 2023-12-12 18:29
I think that's a solid plan James. Here's a quick mock showing the `x` icon instead of the `i` icon.
(Happy to explore alternate treatments for the close button, I just went with this because it's so straightforward.)

![image](https://github.com/Expensify/App/assets/7516624/6bc8796d-1404-4c87-85e8-0c45a07dee41)

**Comment by jamesdeanexpensify** [comment] 2023-12-12 18:51
That's what I was thinking. My gut feeling is that people know enough to click right on the banner for more info, and won't be confused if there's no other visible "next step" like the circle "i" offered. So I'm good with this.

**Comment by DylanDylann** [comment] 2023-12-12 19:15
@jamesdeanexpensify Can contributor post proposal here based on the above discussion or it will be handled by internal?

**Comment by jamesdeanexpensify** [comment] 2023-12-12 20:43
Spoke with @slafortune and it sounds like this is still an external job!

**Comment by dubielzyk-expensify** [comment] 2023-12-13 00:13
I like what sir @dannymcclain mocked up. Definitely also think that it becomes tedious to see this every single time, so I think it'd be real nice if we have limit on how many times this shows

**Comment by jamesdeanexpensify** [comment] 2023-12-13 20:25
How about this:

- Let's move ahead now with replacing the circled "i" with an "x" to make the banner dismissible, as discussed.
- And then I'll start an internal convo in Slack about either limiting the number of times the banner shows OR (what I'm thinking) showing it regularly but only once every X days/weeks/months.

Does that sound good?

**Comment by dubielzyk-expensify** [comment] 2023-12-14 00:54
Sounds good to me

**Comment by abdulrahuman5196** [comment] 2023-12-14 12:48
Hi, Just checking back, I missed couple of messages. Are we still in design phase or have solid requirement on the issue?

**Comment by jamesdeanexpensify** [comment] 2023-12-14 15:56
For now, I think we're OK to move forward with making the banner dismissible in [this way](https://github.com/Expensify/App/issues/32499#issuecomment-1852587395). Do you need anything else from me?

**Comment by abdulrahuman5196** [comment] 2023-12-14 17:36
Thank you @jamesdeanexpensify . 

Kindly add this comment(https://github.com/Expensify/App/issues/32499#issuecomment-1852587395) as requirement to the issue description.


For contributors, kindly if possible do update your older proposals to reflect on the new requirement.

**Comment by DylanDylann** [comment] 2023-12-14 17:38
@abdulrahuman5196 I just updated my [proposal](https://github.com/Expensify/App/issues/32499#issuecomment-1846907595)

**Comment by yh-0218** [comment] 2023-12-14 18:29
@abdulrahuman5196 I just update my [proposal](https://github.com/Expensify/App/issues/32499#issuecomment-1841502854)

**Comment by jamesdeanexpensify** [comment] 2023-12-15 17:52
Is it possible as part of making the banner dismissible with an "x" to make it not show up again once dismissed? Thanks!

**Comment by jamesdeanexpensify** [comment] 2023-12-15 18:35
ah, ok - so this would have to be worked on as a separate backend issue (assuming that's what "BE" means)? Thanks!

**Comment by abdulrahuman5196** [comment] 2023-12-18 08:02
@jamesdeanexpensify 

>Is it possible as part of making the banner dismissible with an "x" to make it not show up again once dismissed? Thanks!

Do you mean, even it shouldn't show even after we re-login? 
For this current issue, I thought we were just to dismiss the popup in the screen and we come back to the screen again the popup would come up.
Kindly let me know if i am wrong.

**Comment by jamesdeanexpensify** [comment] 2023-12-18 17:45
> For this current issue, I thought we were just to dismiss the popup in the screen and we come back to the screen again the popup would come up.
> Kindly let me know if i am wrong.

@abdulrahuman5196 nope, you're right! Keep moving forward on this, I'll bring the other conversation somewhere else. Thanks!

**Comment by yh-0218** [comment] 2023-12-18 17:52
@abdulrahuman5196 Could you check my [proposal](https://github.com/Expensify/App/issues/32499#issuecomment-1841502854)

**Comment by DylanDylann** [comment] 2023-12-18 18:00
@abdulrahuman5196 Update the [alternative solution](https://github.com/Expensify/App/issues/32499#issuecomment-1846907595)

**Comment by slafortune** [comment] 2023-12-19 20:34
@abdulrahuman5196 do you have thoughts on the current proposals?

**Comment by abdulrahuman5196** [comment] 2023-12-20 19:01
Hi, Will take a another look in my morning.

**Comment by DylanDylann** [comment] 2023-12-21 04:49
@jamesdeanexpensify Once the popup is dismissed, when do we show it again? When we re-open the search page, or when user signs out and signs in again?

**Comment by jamesdeanexpensify** [comment] 2023-12-21 16:54
We were talking about making it dismissible forever, but I think that needs to be another conversation later. For now, can we do when the user signs out and signs in again? That seems at least a little less aggressive than _every_ time they try to search.

**Comment by DylanDylann** [comment] 2023-12-21 17:06
@jamesdeanexpensify 

> For now, can we do when the user signs out and signs in again?

Yes. We can do it. But, my question is, currently, we have many referral popup, for example, "Request money, get $250", "Invite a friend, get $250", "Send money, get $250", .... So, should we handle these separately?

**Comment by jamesdeanexpensify** [comment] 2023-12-21 17:34
@DylanDylann I think we should just treat all the referral popups the same in terms of how often they appear. 

@gijoe0295 yes that's true, we agreed on that earlier! for now, whatever takes the least amount of work is fine, so if that's just "dismiss the popup in the screen and we come back to the screen again the popup would come up" then that's fine with me.

**Comment by abdulrahuman5196** [comment] 2023-12-25 12:18
Will work on closing out review before tomorrow.

**Comment by slafortune** [comment] 2023-12-28 15:10
@abdulrahuman5196 checking to see when you might get to this?

**Comment by abdulrahuman5196** [comment] 2024-01-01 13:51
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-01 14:31
@gijoe0295 's proposal here https://github.com/Expensify/App/issues/32499#issuecomment-1841355500 looks good and works well. It was first to propose state variable to control the popup. As discussed for this issue, we can just stop showing the popup when the user press the 'x' mark in the popup, but the popup will come back again if the user visits the screen again.

🎀 👀 🎀
C+ Reviewed

**Comment by joelbettner** [comment] 2024-01-02 21:46
Looks good. I assigned @gijoe0295 to this issue. Feel free to start working on the PR.

**Comment by slafortune** [comment] 2024-02-05 17:26
@abdulrahuman5196 can you please complete the checklist?

Offers sent - 

ROLE: @abdulrahuman5196 paid $500 via Upwork ([LINK](https://www.upwork.com/nx/wm/offer/100774024))
ROLE: @gijoe0295 paid $500 via Upwork ([LINK](https://www.upwork.com/nx/wm/offer/100774101))

**Comment by abdulrahuman5196** [comment] 2024-02-05 17:59
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Feature update.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Press FAB >> Start chat
2) Press close referral banner
3) Verify the banner is closed
4) Verify the text input remains focused
5) Close the RHP
6) Repeat step 1
7) Verify the banner appears again
8) Repeat those steps with Request money and Search page

@slafortune  Completed the checklist and accepted the offer.

**Comment by slafortune** [comment] 2024-02-08 21:25
👍 Paid Paid and testrail done!

**Closed by slafortune** 2024-02-08 21:25 UTC
Labels: Engineering, Daily, Internal, Design, Overdue, Awaiting Payment, Bug
