### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Wallet - Back button returns to the same page after adding a bank account in Wallet page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38558] opened 2024-03-19 08:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Profile > Wallet.
3. Tap Add bank account > Personal bank account.
4. Add a bank account.
5. After returning to Wallet page, tap back button on the top left.

## Expected Result:
App will return to Profile page.

## Actual Result:
App returns to the same Wallet page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d92ae0f0-80b4-44f5-8175-abc9be65958e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172f19f6c44056361</li>
        <li>Upwork Job ID: 1773070619325939712</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-19 08:46
We think that this bug might be related to the #collect project.

**Comment by bernhardoj** [comment] 2024-03-19 09:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing back button from wallet page returns to the add personal bank account page again.

### What is the root cause of that problem?
When we press the continue button after successfully add the bank account, it will call `exitFlow` which will call `goBack` with fallback route of wallet page.
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/AddPersonalBankAccountPage.tsx#L44-L55

Because the add bank account is the only page in the route, it will use the fallback route and push it to the nav stack.
[wallet page, add personal bank account page, wallet page]

So, when we press back, we will arrive at add personal bank account page again.

### What changes do you think we should make in order to solve the problem?

Remove the fallback route from `goBack`.
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/AddPersonalBankAccountPage.tsx#L54

**Comment by godofoutcasts94** [comment] 2024-03-19 11:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet - Back button returns to the same page after adding a bank account in Wallet page
### What is the root cause of that problem?
The root cause is here : 
https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/settings/Wallet/WalletPage/WalletPage.tsx#L359
we are just defining `Navigation.goBack()`
### What changes do you think we should make in order to solve the problem?

To move back to `Workspace Initial` page. We need to modify this route to by adding this : 
```
Navigation.goBack(ROUTES.SETTINGS)
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-19 11:49
Updated [Proposal](https://github.com/Expensify/App/issues/38558#issuecomment-2006972762)

**Comment by alexpensify** [comment] 2024-03-20 23:57
I'll try to test this one tomorrow.

**Comment by alexpensify** [comment] 2024-03-22 19:31
No update yet

**Comment by alexpensify** [comment] 2024-03-26 00:25
On my testing list

**Comment by alexpensify** [comment] 2024-03-27 19:30
I tested this one on Android and see a double click on the back button is required to get to the Profile page.

**Comment by alexpensify** [comment] 2024-03-27 19:33
@eVoloshchak - can you please review if these proposals will resolve this issue? Thanks!

**Comment by alexpensify** [comment] 2024-03-29 17:23
No update yet, this one needs a proposal review.

**Comment by eVoloshchak** [comment] 2024-03-29 17:24
Looking at this right now

**Comment by eVoloshchak** [comment] 2024-03-29 17:55
I think we should proceed with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/38558#issuecomment-2006422052), as it's the most universal one (we don't rely on setting `ROUTES.SETTINGS` as a fallback route, which would need to be changed in case we move wallet page outside settings)

🎀👀🎀 C+ reviewed!

**Comment by bernhardoj** [comment] 2024-04-01 12:23
PR is ready

cc: @eVoloshchak

**Comment by alexpensify** [comment] 2024-04-03 22:14
Awesome, the PR is moving forward.

**Comment by alexpensify** [comment] 2024-04-12 19:50
I confirmed there is an Upwork job here and will continue with the payment process on Monday.

**Comment by alexpensify** [comment] 2024-04-15 21:39
Payouts due:

- [ ] Contributor: $500 @bernhardoj -- paid via Upwork
- [ ] Contributor+: $500 @eVoloshchak -- please submit a request 

Upwork job is [here](https://www.upwork.com/jobs/~0172f19f6c44056361).

**Comment by eVoloshchak** [comment] 2024-04-25 14:08
1. The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20821
2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20821/files#r1579541672
3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a very simple bug, additional discussion isn't needed

**Regression Test Proposal**

1. Go to Settings > Wallet.
2. Tap Add bank account > Personal bank account.
3. Add a bank account and complete the process until you see the success screen.
4. Press continue, it will bring you back to wallet page.
5. After returning to the Wallet page, tap the back button on the top left.
6. Verify the wallet page is closed


**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2024-04-29 17:05
$500 approved for @eVoloshchak though re-opening for Al to handle the regression test.

**Comment by alexpensify** [comment] 2024-04-29 22:48
I'll work on the regression test.

**Comment by alexpensify** [comment] 2024-04-30 23:07
Closing - the test request has been created

**Closed by alexpensify** 2024-04-30 23:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
