### ISSUE TITLE
Workspace - Incorrect left padding for the button which has a left icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29967] opened 2023-10-19 12:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Pujan92
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697713080450809
 
## Action Performed:
1. Open any screen which has a large button with left icon
2. Go to workspaces -> select any workspace -> Cards
3. Observe the left icon alignment for the button "Connect bank account"

## Expected Result:
 Left icon should not be much closer to the left border

## Actual Result:
Left icon is closer to the left border

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Screenshot_1697713163](https://github.com/Expensify/App/assets/93399543/f654e475-b087-4350-87f2-adc7e078e260)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![Screenshot_1697717911](https://github.com/Expensify/App/assets/93399543/c33c0541-43c3-4329-880f-11faa548ea60)

</details>

<details>
<summary>iOS: Native</summary>

 
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-19 at 16 28 43](https://github.com/Expensify/App/assets/93399543/e1b590f5-db4b-4b08-b641-ab47a5cd8adb)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-19 at 17 45 56](https://github.com/Expensify/App/assets/93399543/514c284c-08d9-43c0-a0cf-11b595023776)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![Screenshot 2023-10-19 at 16 27 41](https://github.com/Expensify/App/assets/93399543/6d97f94d-c76b-465d-a220-5ed857ae5401)

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![Screenshot 2023-10-19 at 17 41 56](https://github.com/Expensify/App/assets/93399543/3178b0d9-d194-41b7-893e-a98fea22ba52)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yh-0218** [comment] 2023-10-19 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect left padding for the button which has a left icon
### What is the root cause of that problem?
We don’t have any additional left padding for left-icon of button.
https://github.com/Expensify/App/blob/ad9544b37288ce9c58eecfe10e5293cbb1e87055/src/components/Button/index.js#L236
### What changes do you think we should make in order to solve the problem?
We can add additional left padding
```
<View style={[styles.mr1, this.props.large && styles.ml2, ...this.props.iconStyles]}>
```
https://github.com/Expensify/App/blob/ad9544b37288ce9c58eecfe10e5293cbb1e87055/src/components/Button/index.js#L236
### What alternative solutions did you explore? (Optional)

**Comment by narefyev91** [comment] 2023-10-19 13:07
@yh-0218 go ahead and create a PR - let's resolve this quick

**Comment by amyevans** [comment] 2023-10-19 13:21
The blocker is stemming from https://github.com/Expensify/App/issues/29759 so I'll assign the original authors/reviewers

**Comment by yh-0218** [comment] 2023-10-19 13:23
Hi, @narefyev91 PR is ready for review. Please check.

**Comment by cristipaval** [comment] 2023-10-19 15:54
Removed the `DeployBlockerCash` label as this is a minor visual bug.

**Comment by cristipaval** [comment] 2023-10-27 14:49
Given that the fix for this is production and it was a regression and no payment is due, I'm going to close this one.

**Closed by cristipaval** 2023-10-27 14:49 UTC
Labels: Engineering, Weekly
