### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - #admin is highlighted in LHN but shows Concierge report screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21408] opened 2023-06-23 14:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new account
2. Click on + icon and select New workspace option
3. Check the LHN and report screen

## Expected Result:
Concierge should be highlighted in LHN

## Actual Result:
#admin is highlighted in LHN but shows Concierge report screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-5

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ffb99e73-e1af-4b26-be20-425fe8deea3d

https://github.com/Expensify/App/assets/93399543/3f575014-fd69-4a04-964d-3d4d7a9723bb

**Expensify/Expensify Issue URL:**

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686910566735839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01975cb777161dce5e</li>
        <li>Upwork Job ID: 1673275742488936448</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-06-23 14:05
# Proposal

## Please re-state the problem
#admin is highlighted in LHN but shows Concierge report screen on newly created account.

## What is the root cause of that problem?
The root cause is that when the `Workspace` is created, we have to navigate to two screens:
1. #admin chat in Report Screen
2. Workspace details page in `RHP`

https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/libs/actions/Policy.js#L1045-L1049

Here we just set the route params to the `reportID` of the admins chat and only navigate to the `RHP` details page because this code was written before the navigation refactor and I think we couldn't navigate to both at once at that time.

But since we are only updating the `route` params, it is not causing the `ReportScreenWrapper` to update because that is set to update only if the `reportID` becomes `null` and therefore, the `URL` changes to the `adminReportID` but the actual `ReportScreen` doesn't change.

## What changes do you think we should make to solve this problem?
We can just navigate to both the routes using `Navigation.navigate` for both routes so that it looks something like this:
```js
if (shouldNavigateToAdminChat) {
            Navigation.navigate(ROUTES.getReportRoute(adminsChatReportID));
}

Navigation.navigate(ROUTES.getWorkspaceInitialRoute(policyID));
 ```
 Notice that I'm also adding a parameter to the `createWorkspace` method called `shouldNavigateToAdminChat` which can be set to false on small screens because navigating to `admin` on small screen pushes the workspace before and after the admin chat. This prop can be passed in `FloatingActionButtonAndPopover.js` as `!this.props.isSmallScreenWidth`.
 
 **Result**
 

https://github.com/Expensify/App/assets/77237602/af41960a-b815-40fb-aa49-f3a2b9331adc


## What other approach did you explore?
I also tried having the `ReportScreenWrapper` to update on route change but that exceeds the maximum depth of updates react is capable of.

**Comment by twisterdotcom** [comment] 2023-06-26 10:24
@abdulrahuman5196 - I _think_ @esh-g's proposal looks good. At least the outcome video seems correct anyway. Wonder if we could get this one assigned quickly!

**Comment by abdulrahuman5196** [comment] 2023-06-26 19:05
@esh-g I am not sure if i am aligned to make 2 navigations to solve this issue. Consider small screen devices it will add 2 navigations on the navigation stack, how will it behave there?

**Comment by esh-g** [comment] 2023-06-26 19:12
>Notice that I'm also adding a parameter to the createWorkspace method called shouldNavigateToAdminChat which can be set to false on small screens because navigating to admin on small screen pushes the workspace before and after the admin chat. This prop can be passed in FloatingActionButtonAndPopover.js as !this.props.isSmallScreenWidth.

@abdulrahuman5196 That is why I have added these lines to the proposal. I know that it will push unexpected screens for small screen devices, that is why I'm proposing to only navigate to admins chat on full screen devices as small screen devices can navigate to only one screen at a time.

**Comment by esh-g** [comment] 2023-06-27 02:37
@abdulrahuman5196 Should I provide a branch from my fork to test with for these changes?

**Comment by twisterdotcom** [comment] 2023-06-28 09:17
I am OOO! Adding another BZ for the week.

**Comment by esh-g** [comment] 2023-06-28 16:23
@abdulrahuman5196 This is how it looks on small screens:

https://github.com/Expensify/App/assets/77237602/d8a106a9-060b-4ecf-961b-2e5bffe176d3

And this is the change I was mentioning in my proposal of passing a `navigateToAdminChat` as `false` for small screens:
From this:
https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L239
To this:
```js
onSelected: () => this.interceptAnonymousUser(() => Policy.createWorkspace('', false, '', false, !this.props.isSmallScreenWidth)),
```

**Comment by dylanexpensify** [comment] 2023-07-03 08:47
reviewing today and posting next steps!

**Comment by abdulrahuman5196** [comment] 2023-07-03 14:34
@esh-g The proposal of navigating to 2 routes one after another seems to be workaround solution in my opinion. I would suggest to go after the root cause and fix it.

**Comment by abdulrahuman5196** [comment] 2023-07-04 14:25
@mountiny what is the expectation from navigation refractor perspective on the case?
Like we need to open the details page of a report. 
Do we need to call navigate twice? First call report and then details to solve this? 

Or is there any recommended approach we have now?

**Comment by mountiny** [comment] 2023-07-04 19:40
I would say that sounds correct to me, we first navigate to the report and then to the workspace settings.

**Comment by twisterdotcom** [comment] 2023-07-07 17:04
Can we assign anybody now?

**Comment by esh-g** [comment] 2023-07-07 17:30
Just waiting on @abdulrahuman5196 to review this comment: https://github.com/Expensify/App/issues/21408#issuecomment-1620654876

**Comment by abdulrahuman5196** [comment] 2023-07-07 19:28
The proposal sounds good given the confirmation. I will retest the proposal again and approve if no issues tomorrow morning.

**Comment by abdulrahuman5196** [comment] 2023-07-08 07:45
Given the expectation here https://github.com/Expensify/App/issues/21408#issuecomment-1620654876, @esh-g 's proposal here https://github.com/Expensify/App/issues/21408#issuecomment-1604334247 looks good and works well.

🎀 👀 🎀
C+ Reviewed

cc: @twisterdotcom

**Comment by esh-g** [comment] 2023-07-08 09:19
@abdulrahuman5196 I have a question as to which of these would you prefer:

**1. Navigates to admin chat on small screen but behind the workspace page**

https://github.com/Expensify/App/assets/77237602/1980f795-316f-44ea-8407-cb26fa288792

**2. Does not navigate to admin chat on small screen**

https://github.com/Expensify/App/assets/77237602/1250fbec-1ba8-4595-8213-0051cfa08c58

**Comment by abdulrahuman5196** [comment] 2023-07-08 09:30
@esh-g Option 2 is the current behaviour on small screen devices. So I am fine with that itself since in workspace page itself we can click triple dot and go to admin page.
Correct me if wrong @aldo-expensify / @mountiny

**Comment by mountiny** [comment] 2023-07-08 23:57
I think current behaviour is fine and if we want to change it in future we can explore that

**Comment by esh-g** [comment] 2023-07-09 01:49
@mountiny Option 1 is not current behaviour. Currently we are calling `Navigation.setParams` to change the reportID to admin report.
This changes the url bar but doesn't navigate.

**Comment by aldo-expensify** [comment] 2023-07-10 22:46
Thanks all, assigning @esh-g to implement [proposal](https://github.com/Expensify/App/issues/21408#issuecomment-1604334247)

**Comment by esh-g** [comment] 2023-07-11 06:30
Thanks for assigning me!
PR is here: https://github.com/Expensify/App/pull/22619
cc @abdulrahuman5196

**Comment by aldo-expensify** [comment] 2023-07-18 21:36
@esh-g the [PR](https://github.com/Expensify/App/pull/22619) is running into conflicts now. What is the current state?

**Comment by esh-g** [comment] 2023-07-19 01:12
@aldo-expensify I was waiting for @abdulrahuman5196 to test a comment I left 4 days ago... I'm sorry for not bumping sooner.
I will resolve all the conflicts today

**Comment by aldo-expensify** [comment] 2023-07-21 22:15
PR merged

**Comment by twisterdotcom** [comment] 2023-08-02 14:12
Payment summary:

@abdulrahuman5196 paid $1000 here: https://www.upwork.com/nx/wm/workroom/34164769/overview
@esh-g paid $1000 here: https://www.upwork.com/nx/wm/workroom/34162339/overview
@gadhiyamanan paid $250 here: https://www.upwork.com/nx/wm/workroom/34347173/overview

Internal TestRail issue: https://github.com/Expensify/Expensify/issues/304920

**Closed by twisterdotcom** 2023-08-02 14:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
