### ISSUE TITLE
[$500] Scan - Error shows up when tapping on capture button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31328] opened 2023-11-15 00:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Tap + > Request money > Scan.
3. Tap Continue.
4. Allow camera access.
5. Tap capture button.

## Expected Result:
User is able to take a photo.

## Actual Result:
Error shows up when tapping on capture button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9283d53f-c1e8-40e1-84bf-648b12e7eace

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016c56226964146dd4</li>
        <li>Upwork Job ID: 1724589749726212096</li>
        <li>Last Price Increase: 2023-11-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by strepanier03** [comment] 2023-11-15 23:25
Able to repro on 1.3.99.0. Looks like we had a [fix](https://github.com/Expensify/App/issues/30373) for this that produced a regression.

**Comment by strepanier03** [comment] 2023-11-21 01:11
Gentle bump @eVoloshchak for the proposal [here](https://github.com/Expensify/App/issues/31328#issuecomment-1811661350).

**Comment by eVoloshchak** [comment] 2023-11-27 15:36
I cannot reproduce the issue on both iOS and Android, looks like this has been resolved
@tienifr, could you double-check if this is still reproducible for you?

**Comment by strepanier03** [comment] 2023-11-30 00:10
Going to close this out, we can reopen if needed.

**Closed by strepanier03** 2023-11-30 00:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
