### ISSUE TITLE
[$250] WS Categories - A space gap is displayed for a moment on the list after category deletion

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39324] opened 2024-03-30 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4466254
**Email or phone of affected tester (no customers):**  applausetester+vd_ios032924@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-requisite: the user must be logged in and have created a collect workspace
1. Go to Workspace > Categories
2. Select a category (check the box)
3. Delete the category
4. Verify that after deletion, there is a space gap displayed for a moment where the category was

## Expected Result:
There should be no space gap displayed after category deletion

## Actual Result:
A space gap is displayed for a moment after category deletion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ceed34b6-fea8-4ebe-ab1b-f9f2c42cce44

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140f5a4dbf368b480</li>
        <li>Upwork Job ID: 1778050729524305920</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-30 17:57
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-30 17:58
We think that this bug might be related to #vip-vsp

**Comment by JmillsExpensify** [comment] 2024-04-10 13:21
Visual but worth fixing. Adding to #wave-collect

**Comment by godofoutcasts94** [comment] 2024-04-10 13:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS Categories - A space gap is displayed for a moment on the list after category deletion
### What is the root cause of that problem?
In the file, `WorkspaceCategoriesPage.tsx`, I think when we delete a category list then it takes time to get updated. 

### What changes do you think we should make in order to solve the problem?

I think we can add this code,
```
const updatedList = categoryList.filter(c => c.name !== deletedCategoryName)
setCategoryList(updatedList)
```
what it will do is - When deleting a category, immediately update the `categoryList` state by filtering out the deleted category. This will remove it from the list optimistically before the API request finishes.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by solar-dev23** [comment] 2024-04-10 17:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS Categories - A space gap is displayed for a moment on the list after category deletion

### What is the root cause of that problem?
In `TableListItem.tsx`, `containerStyle` of `BaseListItem` has been added with `styles.mb3` 3 weeks ago.
It's happening this bug that shows a gap space of `mb3` while deleting a category.

### What changes do you think we should make in order to solve the problem?
We can move this `mb3` style to `pressableStyle` instead of `containerStyle`

### What alternative solutions did you explore? (Optional)
n/a

**Comment by solar-dev23** [comment] 2024-04-10 17:13
Contributor details
Your Expensify account email: solar.dev023@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018b3dcfc2c45fda08

**Comment by alitoshmatov** [comment] 2024-04-12 18:02
Not reproducible, probably fixed by https://github.com/Expensify/App/pull/39226

https://github.com/Expensify/App/assets/59907218/3cdfbc18-414b-49be-8162-b5c483d5116c

**Comment by alitoshmatov** [comment] 2024-04-13 18:03
We can close this issue

**Comment by JmillsExpensify** [comment] 2024-04-17 20:30
Thanks, closing.

**Closed by JmillsExpensify** 2024-04-17 20:30 UTC
Labels: External, Daily, Help Wanted, Bug
