### ISSUE TITLE
Payment - User can't continue after reaching "Save & Continue"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9085] opened 2022-05-19 02:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-Condition: Have a workspace created
1. Open the Expensify iOS app
2. Log in to a applause.expensifail.com account
3. Tap on "Profile" icon > "Payments" > "Add payment method" > "Bank Account"
4. Proceed with the flow until the "Account type & Password" page
5. Tap "Save & Continue"

## Expected Result:
The user expects to be able to add a deposit bank account through this flow

## Actual Result:
The user wont be able to proceed beyond this "Save & continue' page, the button will "Load" and return to its initial state

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:**  1.1.63-2

**Reproducible in staging?:**  Y

**Reproducible in production?:** No (Not able to check in production)

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/169194427-f51cd1ba-077b-46d9-a232-befe38415b52.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-05-19 07:03
I looked into the issue and can see that it throws the error and the reason being the account that you are trying to add is already previously added.
```
bankaccount? [hmmm] [mobile] API threw ExpError Expensify\Libs\Error\ExpError - 15fc249e-1f89-49be-aa78-1d87132bf9c5 ~~ exceptionJsonCode: '666' exceptionUserMessage: 'Bank account can't be created, it looks like a bank account with the same information already exists in your account.' exceptionMessage: 'Bank account can't be created, it looks like a bank account with the same information already exists in your account.' exceptionFile: '/vagrant/Web-Secure/lib/BankAccountAPI.php' exceptionLine: '883' exceptionCode: '666'
```
I also tested this with a new account where no bank accounts are added and it worked without any errors.
So a solution would be to show the error message to the user in the app.

**Comment by techievivek** [comment] 2022-05-19 07:16
@kavimuru Can you confirm if you had already added this bank account before?

**Comment by techievivek** [comment] 2022-05-19 07:33
@AndrewGable Can you please cross-check this. Thanks

**Comment by parasharrajat** [comment] 2022-05-19 07:57
I have already fixing this here https://github.com/Expensify/App/pull/9023. As part of https://github.com/Expensify/App/issues/7185 

But I think https://github.com/Expensify/App/issues/9085#issuecomment-1131306339 is the best solution due to the [reason](https://github.com/Expensify/App/issues/7185#issuecomment-1127516268).

**Comment by techievivek** [comment] 2022-05-19 08:31
So I think we can close this one then and yeah https://github.com/Expensify/App/issues/9085#issuecomment-1131306339 would be the best solution here.

**Comment by parasharrajat** [comment] 2022-05-19 08:35
Sorry, I meant to say that  https://github.com/Expensify/App/issues/9085#issuecomment-1131306339 is **not** the best solution. Mistyping...

**Comment by techievivek** [comment] 2022-05-19 08:45
Did you request a `copy` for your fix? I think we can just go with whatever they suggest.
And about the other concern while trying to reproduce this locally I saw an inconsistency when I added the same saving account by going through `Profile -> Payment -> Add payment method` it did filter out the already added account when I reattempted to add a new bank account. But when I added the same bank account by going into the workspace and left it incomplete and then came back to the previous flow `Profile -> Payment -> Add payment method` it got stuck at `Save & Continue`.

**Comment by parasharrajat** [comment] 2022-05-19 08:55
Thanks. I am also concerned about the filtering of existing accounts. It is clearly an issue with that filtration. Code is designed to hide existing accounts from the dropdown so we should improve this logic to successfully filter all existing accounts. But if there is a possibility of an edge case where we are getting this error, then we can go with showing the error on the UI. 

At last, we can keep this open for tracking and I can add this to my PR in the fixed issues list.

**Comment by techievivek** [comment] 2022-05-19 09:57
It indeed is related to filtration logic, I think the current logic only hides the bank accounts which has been successfully added but for bank accounts that are in process of being added(You can mimic this by trying to add a bank account under one of the workspaces but leave it incomplete) are shown in the dropdown.

This is what the progress of adding a bank account in my workspace looks like.
<img width="353" alt="Screenshot 2022-05-19 at 3 25 23 PM" src="https://user-images.githubusercontent.com/35863227/169266656-415e06b5-2e8d-48cb-8b24-4d6864f5a522.png">

Anyway making this a Daily for now.

**Comment by AndrewGable** [comment] 2022-05-19 16:54
Since this issue sounds like it's on production as part of https://github.com/Expensify/App/issues/7185 - Going to remove deploy blocker label.

**Comment by techievivek** [comment] 2022-05-23 08:09
Not overdue.

**Comment by techievivek** [comment] 2022-05-26 17:07
Not overdue

**Comment by techievivek** [comment] 2022-05-29 18:52
@parasharrajat Hi 👋 Is this getting fixed in your PR?

**Comment by parasharrajat** [comment] 2022-05-30 15:05
@techievivek No yet. I am waiting on update from @chiragsalian https://github.com/Expensify/App/issues/7185#issuecomment-1127517594.

**Comment by techievivek** [comment] 2022-06-01 03:55
Not overdue.

**Comment by techievivek** [comment] 2022-06-04 13:34
Not overdue. Work is in progress.

**Comment by techievivek** [comment] 2022-06-07 04:22
Not overdue. Updating this to Weekly.

**Comment by techievivek** [comment] 2022-06-16 05:23
Not overdue.

**Comment by techievivek** [comment] 2022-06-27 08:32
Not overdue.

**Comment by techievivek** [comment] 2022-07-06 07:01
Not overdue, @parasharrajat Can you give an update for this one 🙌 .

**Comment by parasharrajat** [comment] 2022-07-06 07:05
The other PR is is about to be deployed on production and then I will complete my changes.

**Comment by mvtglobally** [comment] 2022-07-12 04:35
Issue not reproducible during KI retests. (First week)

**Comment by techievivek** [comment] 2022-07-15 04:35
Not overdue.

**Comment by mvtglobally** [comment] 2022-07-19 03:24
Issue not reproducible during KI retests. (Second week)

**Comment by AndrewGable** [comment] 2022-07-20 15:52
If it's not reproducible 2x let's close

**Closed by AndrewGable** 2022-07-20 15:52 UTC
Labels: Engineering, Weekly

**Comment by parasharrajat** [comment] 2022-07-20 16:09
Yes, we fixed it from the backend https://github.com/Expensify/App/issues/7185#issuecomment-1127517594
