### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web - Incorrect timezone with new account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23479] opened 2023-07-24 12:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-conditon: Your time zone must different PDT
1. Go login page
2. Login with new account
3. Chat any message
4. Click your avatar in a message, observe that the timezone displayed on the profile page and the timezone of the device are different

## Expected Result:
The timezone on the profile page must be the same as the device's timezone

## Actual Result:
Timezone displayed on the profile page show time PDT

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/efceddfe-dd96-4938-905a-58cb7a733a88

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690109502862679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01044ba0c87324c5d3</li>
        <li>Upwork Job ID: 1683851349929447424</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25759115</li>
<li>namhihi237 | Contributor | 25759119</li>
<li>namhihi237 | Reporter | 25759120</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-24 12:27
QA team is not allow to chat with Concierge

**Comment by kbecciv** [comment] 2023-07-24 12:27
## Proposal
by @namhihi237
### Please re-state the problem that we are trying to solve in this issue.
The timezone on the profile page must be the same as the device's timezone
### What is the root cause of that problem?
We have 2 things here:
1. Since we migrated to using accountID, we missed [here](https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L38C1-L70C1):
So here it will be undefined
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L59
This leads to not updating the timezone when the default login will be `PDT` from the backend returned.
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L64-L68
2. In the case the user logout and login with a new account, the timezone [here](https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L51C1-L52C1) stored value previous, so when login the backend return timezone is PDT so it not update because here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L51-L57
### What changes do you think we should make in order to solve the problem?
1. Use accountID
2. Clear timezone when logout [here](https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/libs/Navigation/AppNavigator/AuthScreens.js#L39C1-L46C1)
```
let currentAccountID;
let timezone;
Onyx.connect({
    key: ONYXKEYS.SESSION,
    callback: (val) => {
        // When signed out, val  hasn't accountID
        if (!_.has(val, 'accountID' )) {
            timezone = null;
            return;
        }
        currentAccountID = val.accountID;
    },
});
Onyx.connect({
       ...
        timezone = lodashGet(val, [currentAccountID, 'timezone'], {});
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2023-07-25 15:04
@AnshuAgarwal24 I guess you can if you think the above proposal is not the correct solution and we haven't received the internal engineer's review.

**Comment by gulxarahmad** [comment] 2023-07-25 18:32
Hello Expensify Team,

I have reviewed the GitHub issue (#23479) regarding the incorrect timezone with new accounts in the Expensify React Native app. I'm confident that I can help resolve this issue efficiently and effectively.

Technical Explanation:

After analyzing the issue, I have identified that the incorrect timezone is likely due to a misconfiguration in the client-side handling of timezones. To fix this problem, I propose the following steps:

Identify the Source of the Problem: I will thoroughly investigate the codebase to pinpoint the areas where timezone data is being handled. This will allow me to understand the root cause of the incorrect timezone issue.

Implement Timezone Management: I will integrate a reliable and robust timezone management library for React Native to ensure consistent handling of timezones across different platforms. The library will accurately determine the user's timezone and handle any conversions necessary to display time correctly.

Data Consistency Checks: I will implement data consistency checks on the server-side to ensure that the correct timezone data is being received and processed from the client-side. This step will help in verifying that the issue is resolved and prevent future occurrences.

Comprehensive Testing: Before submitting the code for review, I will conduct extensive testing on all relevant platforms (iOS, Android, and Web) to ensure that the fix works seamlessly without introducing any regressions. I will provide screenshots as proof of testing and validation.

Timeline and Payment:

I fully understand and agree to the payment timelines based on the day my proposal is accepted and I am assigned to the GitHub issue:

Merged PR within 3 business days: I will aim to deliver a swift resolution and receive a 50% bonus for meeting the quick turnaround time.
Contributor Guidelines:

I have reviewed the Expensify Contributor Guidelines and will adhere to them throughout the development process. I am committed to maintaining code quality, following best practices, and engaging in effective communication with the team.

About Me:

I am an experienced React Native developer with a strong background in building cross-platform applications. I have successfully resolved similar issues in other projects and have a deep understanding of time handling in JavaScript and React Native.

Conclusion:

I'm excited to contribute my skills and expertise to solve the incorrect timezone issue in the Expensify React Native app. Please feel free to reach out to me if you have any questions or need further clarification on my proposal.

Looking forward to the opportunity to work together.

Best regards,

**Comment by gulxarahmad** [comment] 2023-07-25 19:00
Contributor details
Your Expensify account email: gulloahmads@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/gulzara12

**Comment by Beamanator** [comment] 2023-07-26 07:43
@namhihi237 can you please post in this issue so that I can assign this job to you? Your proposal looks great, but I can't assign you until you post here (GH restrictions)

**Comment by Beamanator** [comment] 2023-07-26 07:45
@gulxarahmad thanks for your proposal and welcome to the expensify open source community! :) IT looks like you haven't yet thoroughly read our guidelines for proposing solutions to bugs. Please do that, and if you have any questions about the process, feel free to ask in our slack channels (#expensify-open-source or #expensify-bugs) 👍

**Comment by garrettmknight** [comment] 2023-08-07 12:45
@mollfpr can you work through the checklist? I'll pay out the rest of the issue now and when you're done with the list I'll tee your payment up.

**Comment by mollfpr** [comment] 2023-08-07 17:13
The PR is eligible for bonus speed 🚀
Assignment: Jul 26 GMT+7
PR merged: Jul 27 GMT+7


> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR. This issue appears due to the migration on `accountID`.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a one-time bug, so the regression test should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the App
2. Login with a new account
3. Open a new chat and send any message
4. Click your avatar in a message
5. **Verify** that the timezone displayed on the profile page and the timezone of the device are the same
6. 👍 or 👎

**Comment by garrettmknight** [comment] 2023-08-08 11:29
**Summarizing payments for this issue:**
- #urgency bonus? Yes
- Reporter: @namhihi237 $250 paid via Upwork
- Contributor: @namhihi237 $1500 paid via Upwork
- Contributor+: @mollfpr $1500

Upwork job is here: https://www.upwork.com/jobs/~01044ba0c87324c5d3

**Comment by garrettmknight** [comment] 2023-08-14 10:40
@JmillsExpensify can you pay this one?

**Comment by mollfpr** [comment] 2023-08-18 05:36
@garrettmknight I'm still not in the beta to receive payment in ND. So, we can stick with the Upwork for now.

**Comment by garrettmknight** [comment] 2023-08-18 21:53
Ah, cool. You've been paid and I've updated the comment.

**Closed by garrettmknight** 2023-08-18 21:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
