### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Upon writing an invalid emoji in input field, "No result found" appears in the middle when it appears straight underneath when using main search so is inconsistent.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22180] opened 2023-07-04 14:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open any chats and click on “emoji” in message composer.
2.	Click on "search."
3.	Write an invalid emoji.
4.	Now go back to chats section.
5.	Click on "search" at top
6.	Write an invalid term same as in item 3.
7.	Notice “no result found” error is displayed exactly below in chats but in add reaction section it is displayed in the center of that popup section.
## Expected Result: 
Error should be displayed exactly below the placeholder to keep consistency.
## Actual Result: 
Error is displayed in the center of free space.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/da6fae41-9282-483e-82e8-e143d05e4d72

<img width="957" alt="1" src="https://github.com/Expensify/App/assets/43996225/81d58f85-adb2-414e-bd4b-98ed83c4197f">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688364552695939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108fe6e3afff6fa48</li>
        <li>Upwork Job ID: 1676609008965808128</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-07-04 14:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are providing custom component for empty list
https://github.com/Expensify/App/blob/fdfeb0368db05606f5974928bbda99143c8c3ef0/src/components/EmojiPicker/EmojiPickerMenu/index.js#L527-L530
### What changes do you think we should make in order to solve the problem?
We should set `headerMessage` to `No results found` when list is empty

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-07-05 15:08
Able to repro but my video is too big 🙃

**Comment by zanyrenney** [comment] 2023-07-05 15:08
Assigning external!

**Comment by IrfanAli17899** [comment] 2023-07-05 18:01
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
Search result "No result found" is not aligned to the search text input in the emoji picker as it is at other places.

**What is the root cause of that problem?**
There is a parent component for Text, which aligns the text in the center of the empty space.
![image](https://github.com/Expensify/App/assets/42341411/ce2ad22c-7853-40bc-9e03-d8d2f96c8b5d)

**What changes do you think we should make in order to solve the problem?**
Solution is to either remove the styling of parent component or remove the parent component in 

`style={[styles.alignItemsCenter, styles.justifyContentCenter, styles.flex1]}`
![image](https://github.com/Expensify/App/assets/42341411/95f767a8-29b5-4213-b48e-d9a8ed7f6350)

**Results**
![image](https://github.com/Expensify/App/assets/42341411/dcf092ab-b206-4778-be51-91e5f1ff7196)

**Comment by IrfanAli17899** [comment] 2023-07-05 18:02
Contributor details
Your Expensify account email: irfanali.17899@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e8e9ef24c8fc7419

**Comment by shawnborton** [comment] 2023-07-05 21:35
@stitesExpensify thoughts on this one? Could have sworn we already discussed this at some point.

**Comment by shawnborton** [comment] 2023-07-05 21:36
Either way though, the vertically centered "not found" message looks fine and fills up the space nicely, so I'd be fine with keeping things as-is even though it is slightly inconsistent.

**Comment by stitesExpensify** [comment] 2023-07-05 22:02
I agree, I think that we can keep everything as-is

**Comment by shawnborton** [comment] 2023-07-06 12:39
Oh interesting, that's fair. But then we shouldn't be rewarding any bug bounties or anything because that was an issue that I personally raised.

**Comment by shawnborton** [comment] 2023-07-06 13:02
What are all other places?

**Comment by shawnborton** [comment] 2023-07-06 13:08
Oh, right. Yeah, apologies for flip-flopping here but I do think we should fix it.

**Comment by shawnborton** [comment] 2023-07-06 14:55
Expected behavior is that the "no results found" message appears below the search input

**Comment by zanyrenney** [comment] 2023-07-24 15:14
Coming from @shawnborton comment [here](https://github.com/Expensify/App/issues/22180#issuecomment-1623610554) - we are not paying out the reporting bonus here. So the invites in upwork have been sent to @ChengDzun @parasharrajat only.

**Comment by zanyrenney** [comment] 2023-07-25 11:01
That looks great to me @parasharrajat

**Comment by zanyrenney** [comment] 2023-07-25 11:04
Upwork is breaking: 
<img width="1035" alt="2023-07-25_12-04-34" src="https://github.com/Expensify/App/assets/56830058/88dc8025-1612-48d7-a13f-dfed6a77ef6a">

**Comment by zanyrenney** [comment] 2023-07-25 15:05
Yes it is!

**Comment by zanyrenney** [comment] 2023-07-25 15:05
I will add that when I do the payment.

**Comment by zanyrenney** [comment] 2023-07-26 10:19
Paid @ChengDzun + bonus.

**Comment by zanyrenney** [comment] 2023-07-31 10:02
Awesome! we should be good to close this then right? I have paid @ChengDzun 

External issue reporter NONE. raised y @shawnborton 
Contributor that fixed the issue @ChengDzun  $1500 (basic + urgency)
Contributor+ that helped on the issue and/orPR @parasharrajat   $1500 (to be paid on ND)

**Closed by zanyrenney** 2023-07-31 10:02 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-01 19:15
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
