### ISSUE TITLE
[$500] Web-No error message if press Save&Continue without fill anything in 2 & next idology question

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32104] opened 2023-11-28 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when executing PR:** https://github.com/Expensify/App/pull/31401

**Version Number:** v1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any expensifail account
3. Go to Settings -> Wallet -> Enable Wallet
4. Follow the flow until your reach the "Additional details" page
5. Fill the form with following data: First name: Alberta, Last name: Bobbeth, SSN: 1234, Any other information for the rest of the fields
6. Tap on "Save & continue"
7. Change the SSN for 123456789 -> Tap on "Save & continue"
8. Idology questions should appear
9. Don't fill anything and press Save & continue -> Errors should appear
10. Select any response -> Tap on "Save & continue"
11. Don't fill anything for second question and press Save & continue

## Expected Result:
Errors should appear when pressing Save&Continue without filling anything in all idology questions

## Actual Result:
No error message when press Save&Continue without filling anything in 2 and next idology question

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/17fc7993-9fd1-4818-b8c9-9a5f63e3ff42

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01645371315accf60d</li>
        <li>Upwork Job ID: 1729462498357043200</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-11-28 12:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
From 2nd idology questions the error isn't shown

### What is the root cause of that problem?
Seems the problem comes after this [PR](https://github.com/Expensify/App/pull/31401) where the `key` has been removed [here](https://github.com/Expensify/App/pull/31401/files#diff-a37607e54a07c90ae300378c3a08bbb9bb28aa8d928c0b6ca67833693fcb5b06L137)

Reason: FormProvider isn't rerendering in the dom and persisted the old state, so it contains `values` which the user selected in the previous question and pass the values condition in the `validate` function.

### What changes do you think we should make in order to solve the problem?

We need to assign `key` to the `FormProvider` to rerender the form entirely in the dom with the new state.

`key={currentQuestion.type}`

https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/pages/EnablePayments/IdologyQuestions.js#L134-L136

**Comment by aoneahsan** [comment] 2023-11-28 14:44
i clicked the "Enable Wallet" and it redirected me here,
trying to re-create the issue looking before submitting a proposal,

if i try to add a bank manually it does not allow for a address from pakistan, so any idea how i get to the step where it's showing this error?

<img width="918" alt="Screenshot 2023-11-28 at 7 42 46 PM" src="https://github.com/Expensify/App/assets/37369204/d4615a33-f97c-4635-8206-62c4e1d3d1cc">

**Comment by situchan** [comment] 2023-11-28 14:49
cc: @kowczarz @s77rt

**Comment by s77rt** [comment] 2023-11-28 14:53
@kowczarz Can you please raise a PR fixing this since it's still within the regression period

**Comment by kowczarz** [comment] 2023-11-28 15:23
Sure I will handle this tomorrow morning

**Comment by luacmartins** [comment] 2023-11-28 16:43
We might just revert the original PR since it seems like there's another blocker associated with it. We can then work on reintroducing the refactor and fix all the known issues.

**Comment by luacmartins** [comment] 2023-11-28 19:15
We CPed a revert. Closing.

**Closed by luacmartins** 2023-11-28 19:15 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Help Wanted, Bug

**Comment by s77rt** [comment] 2023-11-29 13:42
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/31401

The rest of the checklist does not apply here. The PR got reverted and we should merge a new one that covers this regression as well

**Comment by kowczarz** [comment] 2023-11-29 16:34
I've just introduced a PR with a fix of the issue.
