### ISSUE TITLE
iOS - Chat - CMD+V is not working when text field is not in focus on a thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28143] opened 2023-09-25 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Copy any message
3. Go out of the thread and go back so composer is not in focus
4. Press CMD+V or CTRL+V from a Bluetooth

## Expected Result:
After pressing CMD+V or CTRL from the keyboard the composer becomes focused and text is pasted correctly

## Actual Result:
Nothing happens when pressing CMD+V or CTRL on a thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c9679a34-4584-48ac-be2e-35198fc9b161

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open

**Comment by peterdbarkerUK** [comment] 2023-10-03 22:20
Bit of a pain to test as iOS and external keyboards, taking a look tomorrow

**Comment by peterdbarkerUK** [comment] 2023-10-09 12:30
dupe of https://github.com/Expensify/App/issues/27540

**Closed by peterdbarkerUK** 2023-10-09 12:30 UTC
Labels: Daily, Overdue, Bug
