### ISSUE TITLE
[$500] Android - Contact Method - Keyboard opens when Cancel the deletion of Contact Method

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33458] opened 2023-12-21 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings> Profile> Contact Method
3. Add new contact method
4. Tap on Delete button
5. Tap Cancel on confirmation modal

## Expected Result:
Keyboard should not open when user cancel the deletion of Contact method

## Actual Result:
Keyboard opens when Cancel the deletion of Contact Method

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0db10906-5244-468f-867c-e3d868d62e71

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d480958d3c517026</li>
        <li>Upwork Job ID: 1737944101067325440</li>
        <li>Last Price Increase: 2023-12-21</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-12-22 09:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android - Contact Method - Keyboard opens when Cancel the deletion of Contact Method
### What is the root cause of that problem?
- We have the logic that will auto-focus on the text input once the modal is hidden.
https://github.com/Expensify/App/blob/f7efad376755d8d5f321186dd96f55c7e9882c32/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L285-L292

### What changes do you think we should make in order to solve the problem?
- Just auto-focus on the text input if the user was focusing on it before. Do it by creating a state ```prevIsFocused``` in [here](https://github.com/Expensify/App/blob/main/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js) .
- Then, once we open the modal, store the previous focus state, by updating:
https://github.com/Expensify/App/blob/f7efad376755d8d5f321186dd96f55c7e9882c32/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L357
to:
```
                                onPress={() => {
                                    this.state.prevIsFocused = this.validateCodeFormRef.current.isFocused();
                                    this.toggleDeleteModal(true);
                                }}
```
- Finally, when hiding the modal, only auto-focus on the input if the prevIsFocused is true, by updating:
https://github.com/Expensify/App/blob/f7efad376755d8d5f321186dd96f55c7e9882c32/src/pages/settings/Profile/Contacts/ContactMethodDetailsPage.js#L290
to:
```
                                if (this.state.prevIsFocused) {
                                    this.validateCodeFormRef.current.focusLastSelected();
                                }
``` 
- Also, we can apply this logic when we come back to this screen from other screens, for example, come back to this screen from search screen, shortcut screen, ... Do it by using the 'onBlur' (blur screen) event

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by CortneyOfstad** [comment] 2023-12-22 17:34
I'm on the fence on this one. It makes sense that the keyboard opens when it's still on entering the magic code section. Going to loop in the team to get a second pair of eyes on this.

**Comment by mountiny** [comment] 2023-12-26 00:31
Thanks @CortneyOfstad! I do think this is very minor and we can close this issue. I can see how some people can say this is unexpected but at the end of the day this does not influence major user flow so we can close given the focus on new features

**Closed by mountiny** 2023-12-26 00:31 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
