### ISSUE TITLE
[HOLD for payment 2024-03-26] [$250] Remove MoneyRequestSelectorPage.js and copy any changes since Nov 27 into IOURequestStartPage.js

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#34613] opened 2024-01-16 20:53 UTC
This is a part of https://github.com/Expensify/App/issues/29107. You can look at that issue for more context behind the cleanup process.

# Problem
The app has two redundant components:

**Old Component**: `MoneyRequestSelectorPage`
**New Component** `IOURequestStartPage`

# Solution
Following the examples ([example 1](https://github.com/Expensify/App/pull/33646), [example 2](https://github.com/Expensify/App/pull/32764)), the Old Component needs to be completely removed from the codebase

1. Look at the history of the Old Component
1. If there are any changes since Nov 27, 2023 which have not been added to the New Component, copy those changes
1. Replace all uses of the Old Component with the New Component
2. Remove all traces of Old Component
3. Be sure to update all routes and navigation to use the new `:action` param (instead of being hard-coded with `"create"`)
4. Update any logic like `isEditing` to use the new action param from the route
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011477b63464907ecf</li>
        <li>Upwork Job ID: 1747632909135507456</li>
        <li>Last Price Increase: 2024-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28117811</li>
<li>Krishna2323 | Contributor | 28117812</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by njmulsqb** [comment] 2024-01-17 01:35
I would love to take this!

**Comment by DylanDylann** [comment] 2024-01-17 03:46
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
Remove MoneyRequestSelectorPage.js and copy any changes since Nov 27 into IOURequestStartPage.js 

### What is the root cause of that problem?
Remove deprecated component 

### What changes do you think we should make in order to solve the problem?
1. Remove MoneyRequestSelectorPage component and all traces 
https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/AppNavigator/ModalStackNavigators.tsx#L93

https://github.com/Expensify/App/blob/278d04e0689d6f012354d89ec19c640a1cd9dc54/src/libs/Navigation/linkingConfig.ts#L407

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L249


2. For new component IOURequestStartPage

In here
https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L304-L307
We need to use the new :action param (instead of being hard-coded with "create") like we did here

https://github.com/Expensify/App/blob/a2f5bd5898eafc53801807c37929afaae8a23666/src/ROUTES.ts#L362-L366

3. Copy changes since 27 Nov to new components based on list commit here: https://github.com/Expensify/App/commits/main/src/pages/iou/MoneyRequestSelectorPage.js

### What alternative solutions did you explore? (Optional)

**Comment by MahmudjonToraqulov** [comment] 2024-01-17 14:53
I would love to take this!

**Comment by Tony-MK** [comment] 2024-01-17 19:52
Love to work on this.

**Comment by michaelhaxhiu** [comment] 2024-01-19 22:41
@hoangzinh how do you feel about the proposal above? 

Others on the GH issue need to suggest a proposal as well to be considered here, btw.

**Comment by DylanDylann** [comment] 2024-01-22 14:27
@hoangzinh could you help to check edit history? @Krishna2323 updated proposal after i posted proposal

**Comment by tgolen** [comment] 2024-01-22 18:41
The proposal from @Krishna2323 is the most complete right now, but it is missing:

- How the new action param will be used inside the component. This should lead to a change in an action file to insure an `isDraft` parameter is used properly, or added if there isn't already one.

**Comment by tgolen** [comment] 2024-01-23 16:24
OK, thanks for checking on that!

**Comment by DylanDylann** [comment] 2024-01-23 16:36
@tgolen as you confirmed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1706027650824079?thread_ts=1705999852.089949&cid=C01GTK53T8Q). I think @Krishna2323's proposal seem incorrect

**Comment by DylanDylann** [comment] 2024-01-30 04:12
@Krishna2323 Please pull the latest main and try again. It seems this bug is fixed.

**Comment by DylanDylann** [comment] 2024-01-30 09:56
@Krishna2323 Could you help to spin up PR? This issue is blocking https://github.com/Expensify/App/issues/34614 and https://github.com/Expensify/App/issues/34610

**Comment by garrettmknight** [comment] 2024-02-09 15:56
Still working through the PR.

**Comment by garrettmknight** [comment] 2024-02-14 19:07
@trjExpensify just reassigning in case this needs help while I'm OOO this week - will be back 2/21 to pick it back up.

**Comment by garrettmknight** [comment] 2024-02-21 18:25
Back - PR is still in progress.

**Comment by garrettmknight** [comment] 2024-03-05 20:00
Final final discussion 😆

**Comment by garrettmknight** [comment] 2024-03-19 19:00
This has been reviewed/merged and deployed to staging.

**Comment by garrettmknight** [comment] 2024-03-19 19:03
This has been reviewed, merged and deployed to staging.

**Comment by garrettmknight** [comment] 2024-03-28 18:47
@Krishna2323 just paid you.

@hoangzinh sent a new offer to you since the old one expired.

**Comment by garrettmknight** [comment] 2024-04-02 18:52
All paid up, closing.

**Closed by garrettmknight** 2024-04-02 18:52 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
