### ISSUE TITLE
PR26501 - Category IOU - The recently selected categories do not appear under Recent section

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27391] opened 2023-09-13 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to the workspace chat as the invited member.
3. Go to + > Request money.
4. Enter an amount > Next.
5. Select any category.
7. Click Category.
8. Select different category multiple times.

## Expected Result:
The recenly selected categories will appear under Recent section.

## Actual Result:
The recently selected categories do not appear under Recent section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/014ab5b9-6c54-4fec-b6f8-1e5df11f9fc9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2023-09-13 21:15
I believe categories are under a beta so I don't think we should block the deploy on those, however @rezkiy37 @yuwenmemon @puneetlath - Could you look into this as it seems related to #26501 and Wave 8? Thank you!

**Comment by rezkiy37** [comment] 2023-09-13 21:28
Actually, it is not a bug, it is a feature. A category is being set to recently array only after a money request has been submitted. So, please verify this 🙂

**Comment by yuwenmemon** [comment] 2023-09-13 22:26
Correct. We can close this!

**Closed by yuwenmemon** 2023-09-13 22:26 UTC
Labels: Engineering, Daily, Bug
