### ISSUE TITLE
[HOLD for payment 2023-11-06] [$500] [Form Provider Refactor] LegalNamePage

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#28873] opened 2023-10-04 22:58 UTC
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/settings/Profile/PersonalDetails/LegalNamePage.js`

cc @kowczarz
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188894b16b3fbda4b</li>
        <li>Upwork Job ID: 1709704697533472768</li>
        <li>Last Price Increase: 2023-10-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27243373</li>
</ul></li>
    </ul>
</details>

**Comment by kowczarz** [comment] 2023-10-05 08:45
Hello! I'm Kamil Owczarz from Software Mansion, the expert agency and I would like to work on this task.

**Comment by luacmartins** [comment] 2023-10-10 16:37
@kowczarz is working on refactoring other pages, but will get to this one soon!

**Comment by luacmartins** [comment] 2023-10-13 18:32
@kowczarz is working on other related PRs, we'll get to this soon.

**Comment by luacmartins** [comment] 2023-10-16 17:02
We're still working on other forms. Will get to this one soon!

**Comment by cdOut** [comment] 2023-10-17 08:39
Hello, I'm Tymotesz Kałuzieński from Software Mansion, the expert agency, and I would like to work on this task. Kamil reassigned it to me.

**Comment by kowczarz** [comment] 2023-10-17 08:47
Hey @luacmartins! Do you know who can add @cdOut to Upwork whitelist? And as we discussed yesterday, could you please assign him to this task?

**Comment by luacmartins** [comment] 2023-10-17 16:07
@kowczarz I believe the [automated message](https://github.com/Expensify/App/issues/28873#issuecomment-1765944899) above describes what's necessary! Sure, I'll reassign this to @cdOut! Welcome to the team!

**Comment by luacmartins** [comment] 2023-11-08 00:50
Pending BZ checklist and payment

**Comment by jjcoffee** [comment] 2023-11-08 08:35
I guess no checklist is required here since it's not a bug?

**Comment by luacmartins** [comment] 2023-11-08 17:03
Ah yea, sorry no checklist needed here

**Comment by tjferriss** [comment] 2023-11-08 22:18
@jjcoffee payment has been made via Upworks.

**Closed by tjferriss** 2023-11-08 22:18 UTC
Labels: External, Daily, Awaiting Payment, Bug
