### ISSUE TITLE
[$250] Pasting a dollar amount  a dollar symbol does not work in IOU flow manual 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#47270] opened 2024-08-12 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1723332467625059

## Action Performed:
Precondition: Copy an amount (eg: $90.28)
1. Click FAB > Submit expense
2. In the BNP press CTRL+V
## Expected Result:
90.28 should be pasted in, stripping/ignoring the $
## Actual Result:
Nothing happens
Note: Trying again with 90.28  works fine
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/33437013-3015-4880-ae6c-84a6c686adb6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb35c100257d5f4c</li>
        <li>Upwork Job ID: 1824206181504759627</li>
        <li>Last Price Increase: 2024-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103599426</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2024-08-15 22:07
@s77rt - when you get a chance, can you please review whether one of these proposals will fix this issue? Thanks!

**Comment by s77rt** [comment] 2024-08-16 00:29
@nyomanjyotisa @Krishna2323 Thank you for the proposals. When pasting an amount with currency, we should change the selected currency to the one we pasted. Can you please update your proposals to account for that?

**Comment by nkdengineer** [comment] 2024-08-16 04:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens
Note: Trying again with 90.28  works fine

### What is the root cause of that problem?
We get the validated amount without detecting the case `newAmount` has a currency symbol prefix.


https://github.com/Expensify/App/blob/5e5bff3630958264c22a34f083879792ff8ee6ab/src/components/MoneyRequestAmountInput.tsx#L156-L170
### What changes do you think we should make in order to solve the problem?
The test branch here: https://github.com/nkdengineer/App/tree/fix/47270

1. We should create a function to exact the currency and amount from the new amount like this

```
function validateAmountWithCurrency(amountWithCurreny: string): ExactAmountWithCurrency | undefined {
    const regex = /^(\p{Sc})?(\d+)$/u;

    const match = amountWithCurreny.match(regex);

    if (match) {
        const currencySymbol = match[1];
        const amount = match[2];
        const currency = getCurrencyCode(currencySymbol);
        if (!currency) {
            return undefined;
        }
        return {currency, amount};
    }

    return undefined;
}
```

2. Then in `setAmount` function here if we get the amount with currency, we will update both currency and amount. To update the currency we will need to pass `onPasteAmountWithCurrency` from `IOURequestStepAmount` to `MoneyRequestAmountInput`

```
let finalAmount: string;
const exactAmountWithCurrency = MoneyRequestUtils.validateAmountWithCurrency(newAmount);
if (exactAmountWithCurrency) {
    const {currency: updateCurrency, amount: updateAmount} = exactAmountWithCurrency;
    const updateDecimals = CurrencyUtils.getCurrencyDecimals(updateCurrency);
    finalAmount = updateAmount.includes('.') ? MoneyRequestUtils.stripCommaFromAmount(updateAmount) : MoneyRequestUtils.replaceCommasWithPeriod(updateAmount);
    // Use a shallow copy of selection to trigger setSelection
    // More info: https://github.com/Expensify/App/issues/16385
    if (!MoneyRequestUtils.validateAmount(finalAmount, updateDecimals)) {
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
    onPasteAmountWithCurrency?.(updateCurrency);
} else {
    finalAmount = newAmountWithoutSpaces.includes('.')
        ? MoneyRequestUtils.stripCommaFromAmount(newAmountWithoutSpaces)
        : MoneyRequestUtils.replaceCommasWithPeriod(newAmountWithoutSpaces);
    // Use a shallow copy of selection to trigger setSelection
    // More info: https://github.com/Expensify/App/issues/16385
    if (!MoneyRequestUtils.validateAmount(finalAmount, decimals)) {
        setSelection((prevSelection) => ({...prevSelection}));
        return;
    }
}
```
https://github.com/Expensify/App/blob/5e5bff3630958264c22a34f083879792ff8ee6ab/src/components/MoneyRequestAmountInput.tsx#L156-L170
### What alternative solutions did you explore? (Optional)

### Result


https://github.com/user-attachments/assets/5f631dd6-70f3-46d1-a970-d9decac7c4e8

**Comment by s77rt** [comment] 2024-08-16 22:44
@nkdengineer Thanks for the proposal. Can you please explain in English the process of updating the currency? (after extracting it from pasted text)

**Comment by nkdengineer** [comment] 2024-08-17 01:38
@s77rt I updated my [proposal](https://github.com/Expensify/App/issues/47270#issuecomment-2292798433) with English explain.

**Comment by s77rt** [comment] 2024-08-18 09:47
@nkdengineer Why do we need a callback to set the currency? Can't we just update it inside `MoneyRequestAmountInput` (the same way the amount is handled)

**Comment by nkdengineer** [comment] 2024-08-19 04:08
> Can't we just update it inside MoneyRequestAmountInput (the same way the amount is handled)

@s77rt Yeah checked again and we can do this.

**Comment by nkdengineer** [comment] 2024-08-19 04:08
Updated my [proposal](https://github.com/Expensify/App/issues/47270#issuecomment-2292798433).

- add alternative solution.

**Comment by nkdengineer** [comment] 2024-08-19 14:44
@s77rt Updated [alternative solution](https://github.com/Expensify/App/issues/47270#issuecomment-2292798433) to cover the submit button case. And also updated the test branch for testing.

**Comment by s77rt** [comment] 2024-08-19 17:41
@nkdengineer Still not using the new currency


https://github.com/user-attachments/assets/6d93c7ea-0b23-4b98-b45b-f5b6bfbec788

**Comment by nkdengineer** [comment] 2024-08-19 17:57
I tested and it works well. Did you get the current currency in `submitAndNavigateToNextPage` function via `moneyRequestAmountInputRef`

https://github.com/user-attachments/assets/d765069d-051e-4bba-b849-128cbccb23d6

**Comment by s77rt** [comment] 2024-08-19 18:00
@nkdengineer Yes, it's already logged in the recorded video

**Comment by s77rt** [comment] 2024-08-19 18:10
@nkdengineer Ah that what I was missing. Another problem is that I can't change the currency using the currency selector


https://github.com/user-attachments/assets/b3a6e532-9518-4291-9f53-ca8c1f1f567f

**Comment by nkdengineer** [comment] 2024-08-19 18:13
@s77rt Follow the same way we do for amount we need to add a `useEffect` in `MoneyRequestAmountInput` to update currecy state when currency prop is changed. I already add this logic in the test branch of my proposal before.

**Comment by s77rt** [comment] 2024-08-19 18:23
@nkdengineer Overall looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/47270#issuecomment-2292798433)
PS: Please do not add code-diff, branches, PRs.

**Comment by nkdengineer** [comment] 2024-08-19 18:25
> PS: Please do not add code-diff, branches, PRs

Thanks, I noted.

**Comment by alexpensify** [comment] 2024-08-26 15:06
## Next Steps

This PR is going through the review process. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-09-03 23:02
Catching up from being OOO, I see the PR is moving along.

**Comment by alexpensify** [comment] 2024-09-03 23:04
Catching up from being OOO, I see the PR is moving along.

**Comment by alexpensify** [comment] 2024-09-11 23:03
PR is still going through the review process.

**Comment by s77rt** [comment] 2024-09-18 13:47
After working on this for about a month we think it's best to close the PR. Reasoning: the needed work turned out to be more complex than initially evaluated. The initial plan was to make the currency prop stateful the same way as the amount. However the currency is used in other places (namely the currency selection page) and it needs to be in sync e.g. if you change currency via paste, you should see that new currency in the currency page and vice-versa. But we kept running into bugs and decided not to continue with that approach.

Next steps: I think we can either:
1. Reopen for more proposals and look for a different approach
2. Close the issue (since it's a feature request, not a bug)


cc @Gonals thoughts on this one?

**Comment by Gonals** [comment] 2024-09-18 14:23
Makes sense to me. @alexpensify, thoughts on this? Do we give it another try to find a different approach or do we call it a day?

**Comment by alexpensify** [comment] 2024-09-18 19:34
I agree, let's close. Thanks!

**Closed by alexpensify** 2024-09-18 19:34 UTC
Labels: Reviewing, External, Weekly, Bug
