### ISSUE TITLE
Android - Attachment - Long images are not displaying correctly in the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37725] opened 2024-03-05 10:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.47-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** shussain@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. On a conversation, click on the + button in the compose box
2. Upload this long image to a conversation
3. Notice image zoom in and out fast automatically

## Expected Result:
Image should display correctly in the chat and don't flash.

## Actual Result:
Long image are not displaying correctly in the chat and flashes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f0768d8f-a491-45f4-94ba-25f93a9ac17c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-05 10:28
Production video

https://github.com/Expensify/App/assets/115492554/18a71438-0023-4978-8cb6-08c3c04fa08c

**Comment by izarutskaya** [comment] 2024-03-05 10:29
@youssef-lr I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by youssef-lr** [comment] 2024-03-05 10:29
Thanks @izarutskaya. I'm looking at the checklist now to see if I can find any PRs that might have caused this.

**Comment by youssef-lr** [comment] 2024-03-05 10:31
could you please upload the image you used for testing?

**Comment by youssef-lr** [comment] 2024-03-05 10:35
That works, thanks!

**Comment by youssef-lr** [comment] 2024-03-05 12:02
I'm unable to reproduce this one.

https://github.com/Expensify/App/assets/9680864/0cb6d89b-e852-4918-9d2a-c9c39f3d2eea

**Comment by youssef-lr** [comment] 2024-03-06 21:26
No update yet, we need reproduction. Will ask again tomorrow as I'm about to sign off.

**Comment by trjExpensify** [comment] 2024-03-07 11:37
Let us know how you get on! Also, doesn't [that look wrong](https://github.com/Expensify/App/issues/37725#issuecomment-1978605674) as it's super skinny?

**Comment by trjExpensify** [comment] 2024-03-11 11:09
@youssef-lr any luck?

**Comment by youssef-lr** [comment] 2024-03-13 20:15
I think we can just close this. We haven't got any real world reports from this and I wasn't able to reproduce.

**Comment by youssef-lr** [comment] 2024-03-13 20:16
>Also, doesn't https://github.com/Expensify/App/issues/37725#issuecomment-1978605674 as it's super skinny?

I don't think there's a way around it, the image has weird dimensions and is super super long.

**Closed by youssef-lr** 2024-03-13 20:15 UTC
Labels: Engineering, Daily, Needs Reproduction, Overdue, Bug
