### ISSUE TITLE
Held expense shows no indication that it’s held in the header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40832] opened 2024-04-23 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713889940519339

## Action Performed:
1. Go to any report with submitted expenses
2. Click on an individual expense
3. In the three dot overflow menu (top right), choose Hold request

## Expected Result:
Held expenses should indicate that they are held in the header
## Actual Result:
No indication in the header. I’m only able to tell by the comment
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Snip - (17) New Expensify](https://github.com/Expensify/App/assets/38435837/c2266bda-3a08-4cc2-9081-681811802481)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by godofoutcasts94** [comment] 2024-04-24 06:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Held expense shows no indication that it’s held in the header
### What is the root cause of that problem?
For the Hold Request Header here :

<img width="1469" alt="Screenshot 2024-04-24 at 11 36 08 AM copy" src="https://github.com/Expensify/App/assets/158435970/9fd71388-4d6b-42d2-b92d-ef5daf4fa385">

the header doesn't indicate if the request is `Held` or `Unheld`.

### What changes do you think we should make in order to solve the problem?

I think we can edit the Hold Request Header Text i.e. after this text - `This expense was put on hold. Review the comments for next steps.`, we can add something like `(Held this expense)`
### What alternative solutions did you explore? (Optional)
Alternatively, here : 
<img width="1469" alt="Screenshot 2024-04-24 at 11 36 08 AM copy" src="https://github.com/Expensify/App/assets/158435970/7e24310f-98c3-4dde-b3da-ddfada8d9fea">
in place of `Hold`, we can add `Held` or `Unheld` depending upon the request is **Held** or **Unheld**

**Comment by godofoutcasts94** [comment] 2024-04-24 06:19
@shawnborton, Please let me know what design ideas do you have ?

**Comment by shawnborton** [comment] 2024-04-24 12:15
I think this is a dupe... let me find it. cc @NikkiWines

**Comment by shawnborton** [comment] 2024-04-24 12:16
I think this is the existing issue: https://github.com/Expensify/App/issues/39989

cc @trjExpensify @dragnoir

Let's try to get that issue's PR merged soon. Thanks!

**Closed by shawnborton** 2024-04-24 12:16 UTC
Labels: Daily, Bug
