### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500] Web - Task - @__fake__ shows up in the task when navigating back from threaded chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28055] opened 2023-09-23 07:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a new workspace.
3. Go to the workspace chat.
4. Send a message and also send a reply to the message.
5. Return to workspace chat.
6. Create a task from + in the composer.
7. Return to the workspace chat.
8. Go to the thread message.
9. Return to workspace chat.
10. If __fake__ does not show up in the task, go to the thread message and return to workspace chat again.

## Expected Result:
@__fake__ will not show up in the task.

## Actual Result:
@__fake__ shows up in the task.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d3590a5f-f043-4f07-a420-3fe34394526e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e09249224a2eba3e</li>
        <li>Upwork Job ID: 1706218574200713216</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26976069</li>
<li>tienifr | Contributor | 26976071</li>
</ul></li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-09-25 08:06
not overdue. looking for proposals

**Comment by zukilover** [comment] 2023-09-25 08:26
The attached screen record doesn't seem to relate to the reproduction steps.

**Comment by abdulrahuman5196** [comment] 2023-09-27 11:18
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-09-28 17:31
@tienifr I am able to repro the issue in staging but not in main. Is this fixed in main somehow?

**Comment by abekkala** [comment] 2023-09-29 01:29
> The attached screen record doesn't seem to relate to the reproduction steps.


I agree and meant to note that as well. @izarutskaya

**Comment by abdulrahuman5196** [comment] 2023-09-29 15:44
@tienifr 's proposal (solution 1) here https://github.com/Expensify/App/issues/28055#issuecomment-1733170008 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by abdulrahuman5196** [comment] 2023-10-02 09:16
Not overdue melvin. We just approved a proposal

**Comment by Julesssss** [comment] 2023-10-02 09:20
I think Melvin ignores messages from himself. Not sure if it's worth fixing though

**Comment by abdulrahuman5196** [comment] 2023-10-02 13:13
> I think Melvin ignores messages from himself. Not sure if it's worth fixing though as this is desired for most messages.

Yeah. I also think its fine. Because it mentions that week over messages as well.

**Comment by Julesssss** [comment] 2023-10-02 15:54
A similar [issue](https://github.com/Expensify/App/issues/28626) was raised here, I wonder if our proposal will also fix that issue.

**Comment by abdulrahuman5196** [comment] 2023-10-03 08:42
> A similar [issue](https://github.com/Expensify/App/issues/28626) was raised here, I wonder if our proposal will also fix that issue.

I dont think so. This PR is specifically to avoid the @__fake__ showing up, so wouldn't fix the other.

**Comment by abekkala** [comment] 2023-10-10 14:10
### PAYMENTS FOR OCT 12

- Applause (Reporter) - [no payment]
- @tienifr (Contributor) - [$500 + $250 bonus, if no regression]
- @abdulrahuman5196 (Reviewer) - [$500 + $250 bonus, if no regression - please complete the checklist prior to payments

**Comment by abekkala** [comment] 2023-10-12 14:20
@tienifr  and @abdulrahuman5196 payments made and contracts ended - thank you! 🎉

**Closed** 2023-10-12 14:26 UTC
Labels: External, Daily, Awaiting Payment, Bug
