### ISSUE TITLE
Web - Chat - Top of the highlight is not even when highlight emojis

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39261] opened 2024-03-29 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58.0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:** 

## Action Performed:
1.Go to staging.new.expensify.com/

2.Go to any chat

3.Inset multiple emojis

4.Highlight all the emojis

## Expected Result:
The top of the highlight will be even

## Actual Result:
The top of the highlight is not even

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![317920620-f03fe9dc-8116-4fa1-9e66-86303a56d401](https://github.com/Expensify/App/assets/38435837/c6e72831-79a4-4769-8017-a558ac22ace2)

https://github.com/Expensify/App/assets/38435837/d93b2987-eafe-4bc5-9d48-1f305b8bfc9a

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-03-29 17:05
We think this bug might be related to #vip-vsb

**Comment by m-natarajan** [comment] 2024-03-29 17:07
@kevinksullivan FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by MahmudjonToraqulov** [comment] 2024-03-29 18:15
### Please re-state the problem that we are trying to solve in this issue.
Web - Chat - Top of the highlight is not even when highlight emojis

### What is the root cause of that problem?
Extra`fontSize: 20px` is added for emoji so we're getting this issue. 

![14](https://github.com/Expensify/App/assets/91727683/776bab0b-c4a3-4dc5-8b96-fb7730c046f2)



### What changes do you think we should make in order to solve the problem? 
We should remove this`fontSize: 20px` and it's solved. 

![11](https://github.com/Expensify/App/assets/91727683/5476684c-cb8c-4358-9088-55a678fba29c)



  
### What alternative solutions did you explore? (Optional)
N/A

### Result
![13](https://github.com/Expensify/App/assets/91727683/7aa2c9a5-1f0f-480e-b4bf-ef78fe07ce28)

**Comment by thienlnam** [comment] 2024-03-29 18:19
Not a blocker - added to the main tracking issue

**Comment by tomekzaw** [comment] 2024-03-29 21:37
I believe this is the correct behavior as there is a space between each pair of emojis.

Here's how it looks on Firefox with some text added in between one pair of emojis:

<img width="249" alt="Screenshot 2024-03-29 at 22 37 24" src="https://github.com/Expensify/App/assets/20516055/d58f57a1-dd6d-4dbe-b06a-06d8e4f305bb">

**Comment by kevinksullivan** [comment] 2024-04-05 23:19
@thienlnam think tis fits into VSB as a very, very low bug?

**Comment by thienlnam** [comment] 2024-04-08 16:58
Ah okay, so tested it and I think the problem here is with the emoji size in the composer. Emojis when sent without text are larger than if you send them with text
![Screenshot 2024-04-08 at 9 55 59 AM](https://github.com/Expensify/App/assets/30609178/b9bdad8b-dbce-4c3a-9e39-f46d00992f64)

But the size of the emoji with text in the composer is larger than the text, so it ends up creating the odd highlighting. But when you highlight the sent text, it doesn't have a problem because the emojis are smaller
![Screenshot 2024-04-08 at 9 57 33 AM](https://github.com/Expensify/App/assets/30609178/484a4d96-ddc8-43b0-8cc6-ffaae00193b0)

![Screenshot 2024-04-08 at 9 52 59 AM](https://github.com/Expensify/App/assets/30609178/de087384-e201-4c93-a61e-4a0e72b905de)

**Comment by tomekzaw** [comment] 2024-04-08 21:13
> I think the problem here is with the emoji size in the composer.

Here's the full story:

1. Currently (both on main and prod), the font size of any emoji in the composer is always set to 20pt. That's because 20pt is the default value of `emoji.fontSize` in Live Markdown library and I forgot to override it in E/App.

2. There's already a PR from @Skalakid that sets the correct font size from `variables.emojiSize`:
* https://github.com/Expensify/App/pull/39597

3. Once the above PR gets merged, the font size of any emoji in the composer will be always set to `variables.emojiSize`. Is this the expected behavior? Correct me if I'm wrong but based on this discussion, I assume that the `emoji.fontSize` should depend on the current message &ndash; if it contains only emojis, the font size should be larger.

cc @thienlnam

**Comment by thienlnam** [comment] 2024-04-08 21:16
Ah yup that's correct - okay sweet in that case this should be "fixed" when that PR is merged so I'll go ahead and close

**Comment by tomekzaw** [comment] 2024-04-08 21:24
@thienlnam What about point 3? Do we want to increase/decrease the font size of emojis in the composer depending on whether the current message contains any text or only emojis?

**Comment by thienlnam** [comment] 2024-04-08 21:28
Oh my bad, but emoji.fontSize should depend on the current message
![Screenshot 2024-04-08 at 2 27 53 PM](https://github.com/Expensify/App/assets/30609178/8caeda05-072d-462a-86e6-83c1bbe028ea)

For example the first size is larger since there are only emojis, and then the second message with text is smaller

**Comment by tomekzaw** [comment] 2024-04-08 21:44
No problem, I think we can easily achieve that. We can set `emoji.fontSize` in `markdownStyle` based on the current message directly in React code.

Currently, we have a `useMarkdownStyle` hook that returns the `markdownStyle` object &ndash; we can pass the current text as an argument and calculate `emoji.fontSize` based on whether it contains only emojis or not.

The only problem is that the font size will be calculated on the JS thread but the formatting needs to be applied on the UI thread while typing &ndash; there's a possibility of a "font size jump" when the result of the predicate changes. I believe this is not a huge problem for now (please let me know what you think @thienlnam).

There are two options how we can improve that in the future:
1. We can extend Live Markdown so that we can pass two different `fontSize` values and `MarkdownTextInput` will use the appropriate value based on its contents. (I don't like this option as it introduces some confusion)
2. We can extend the JS parser so that it does not apply `emoji` style to the emojis if the current text includes characters (glyphs?) other than emojis. This way, we can set `emoji.fontSize` once and this setting will be used only for emoji-only messages.

**Comment by thienlnam** [comment] 2024-04-08 21:48
Yeah that sounds good, the font size jump doesn't sound like a problem right now - so let's just try that first and improve it later if there are any concerns

**Comment by tomekzaw** [comment] 2024-04-08 21:50
Do you want to merge #39597 first and then come up with another PR or should we implement this directly in #39597?

**Comment by thienlnam** [comment] 2024-04-08 21:54
If we could implement it directly that would be great

**Comment by tomekzaw** [comment] 2024-04-08 22:02
Sure thing, I'll leave it up for @Skalakid since he's the author of the PR.

**Comment by tomekzaw** [comment] 2024-04-12 18:33
https://github.com/Expensify/App/pull/39597 has been merged.

**Comment by kevinksullivan** [comment] 2024-05-08 19:13
Think this is all set @thienlnam ?

**Closed by kevinksullivan** 2024-05-08 19:13 UTC
Labels: Reviewing, Engineering, Monthly, Bug
