### ISSUE TITLE
[$250] Android & iOS - #announce room title is left aligned in room details page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48964] opened 2024-09-11 08:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to #announce room.
3. Tap on the room header.

## Expected Result:
#announce room title will be centered.

## Actual Result:
#announce room title is left aligned, while the workspace name below it is centered.
The same issue also happens in thread.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ceb61f7d-fdaa-47a3-ba6c-932f448582c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833780466930093925</li>
        <li>Upwork Job ID: 1833780466930093925</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 08:06
Prod
![IMG_6763](https://github.com/user-attachments/assets/5ae9f024-4423-4ebd-b520-9cbda63abec1)

**Comment by nihatuzlaci** [comment] 2024-09-11 08:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we visit the announce room or a workspace, the room title is left aligned.

### What is the root cause of that problem?
Title style doesn't include `textAlign:center` style so which causes a problem
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/ReportDetailsPage.tsx#L631

### What changes do you think we should make in order to solve the problem?
We should use `textAlign:center` to fix this problem.


### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-09-11 08:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
#announce room title is left aligned, while the workspace name below it is centered.
The same issue also happens in thread.

### What is the root cause of that problem?

Offending PR: https://github.com/Expensify/App/pull/48456

This happens to all `MenuItem`s because we use `flex: 1` for title text:

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/components/MenuItem.tsx#L452

I think this is a problem with `react-native` when it left align the text when using `flex: 1` on native. Check it out in this demo: https://snack.expo.dev/nhqDVHwr73Pk3FbA-9X9K.

### What changes do you think we should make in order to solve the problem?


Add `textAlign: center` to the title styles of the `MenuItem`:

https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/ReportDetailsPage.tsx#L678

We should check all the places where we use `MenuItem` but want to center align the text to do the same.

**Comment by ChavdaSachin** [comment] 2024-09-11 08:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- #announce room title aligned left
  
### What is the root cause of that problem?
- `titleContainerStyle` is not applied to  `nameSectionTitleField` here
 https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/ReportDetailsPage.tsx#L674-L683 

### What changes do you think we should make in order to solve the problem?
- same as what `nameSectionGroupWorkspace` apply `titleContainerStyle={styles.alignItemsCenter}` to `nameSectionTitleField` here
https://github.com/Expensify/App/blob/762bffcfad4ca7c4553eabedde5a2ba47871bdb5/src/pages/ReportDetailsPage.tsx#L674-L683 

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Guccio163** [comment] 2024-09-11 10:01
I believe that `flex: 1` isn't a problem per se, just that `titleStyle` wasn't directly centered previously since whole shrunken Text component was. In my opinion we should add `textAlign: 'center'` directly to `textStyles` both in `nameSectionGroupWorkspace` (line 631) and `nameSectionTitleField` (line 678) like that: 

`titleStyle={{textAlign: 'center', ...styles.newKansasLarge}}`

Like @rayane-djouah just stated this comes directly from the PR that we were working on, moreover I'm Wiktor Gut from SWM agency so I can fix it for you right away. If you agree with me, please assign me this issue.

**Comment by Guccio163** [comment] 2024-09-11 11:45
PR above solves this issue once it's merged, because it reverts previous interference on `MenuItem` and hence this section, result is right:
<img width="311" alt="Screenshot 2024-09-11 at 13 43 52" src="https://github.com/user-attachments/assets/415dfd44-4da4-4159-917d-494350291f20">

**Comment by Guccio163** [comment] 2024-09-11 15:31
PR is merged, this issue can be closed

**Comment by luacmartins** [comment] 2024-09-11 16:23
The CP is still ongoing. I'll verify the fix in staging and then close the issue

**Comment by luacmartins** [comment] 2024-09-11 16:34
This is fixed on staging. Closing.

**Closed by luacmartins** 2024-09-11 16:34 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Weekly, Bug
