### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Search - The cursor is displayed on different sides in the search text box

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52382] opened 2024-11-12 11:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5200040
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign in to the STG website with a Gmail account.
2. Tap on the search icon in the top right corner.

## Expected Result:
The cursor must always appear at the beginning of the search text box.

## Actual Result:
The cursor is displayed inconsistently on several sides of the search box each time the function is opened.
Issue happens only on iOS mWeb/Chrome.
## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/54739e87-540f-4143-be12-36344542fc1b

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856557909155722434</li>
        <li>Upwork Job ID: 1856557909155722434</li>
        <li>Last Price Increase: 2024-11-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by jliexpensify** [comment] 2024-11-13 02:41
ios <> Android swap

**Comment by s77rt** [comment] 2024-11-13 10:08
@bernhardoj Thanks for the proposal. The RCA makes sense to me. Is there any reason we shouldn't go with `useAutoFocusInput` approach?

**Comment by bernhardoj** [comment] 2024-11-13 12:10
If we delay the focus, the keyboard won't show in mWeb Safari.

**Comment by s77rt** [comment] 2024-11-13 13:18
Isn't that problem already in main for the rest of the inputs? e.g. Workspace switcher, Workspace members list; etc.

**Comment by bernhardoj** [comment] 2024-11-13 13:28
Yes, but the search router currently doesn't have that problem.

**Comment by s77rt** [comment] 2024-11-13 16:28
I think we should still use `useAutoFocusInput` for consistency. The problem with iOS if fixed it should be fixed at the `useAutoFocusInput` hook level.

**Comment by bernhardoj** [comment] 2024-11-13 16:58
If we use `useAutoFocusInput` and don't delay inside it for iOS Safari, we will still need the caret hidden solution.

**Comment by bernhardoj** [comment] 2024-11-14 03:22
If we are fine with that, then let's go with it. I have added it to my alternative solution.

**Comment by s77rt** [comment] 2024-11-14 12:10
@bernhardoj Thank you!

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/52382#issuecomment-2470753231)

**Comment by pecanoro** [comment] 2024-11-14 15:55
Sounds good! Assigning @bernhardoj

**Comment by bernhardoj** [comment] 2024-11-15 09:08
PR is ready

cc: @s77rt

**Comment by kadiealexander** [comment] 2024-11-29 00:06
Payouts due:

- [ ] Contributor: $250 @bernhardoj via manual request
- [ ] Reviewer: $250 @s77rt via manual request

**Closed by kadiealexander** 2024-11-29 00:06 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-11-29 09:58
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-11-29 12:00
$250 approved for @s77rt

**Comment by tgolen** [comment] 2024-12-02 21:54
@s77rt Thanks for classifying the bug!

For this one:
![image](https://github.com/user-attachments/assets/de127309-7b79-4679-abf1-bed404a20bdd)

It really should have been marked as staging (or at least staging+prod, but that option might be going away soon).

You can see from the original description it was reproduced on both environments, and the screenshots show it was found on staging.

**Comment by s77rt** [comment] 2024-12-02 21:57
@tgolen If it's reproducible on production, it's reproducible on staging. Otherwise we'd close the issue.

**Comment by tgolen** [comment] 2024-12-02 22:00
True, I think what I'm trying to capture though is... was the bug found as part of the regression testing during a deploy, or was the bug released to production and then someone found it in production?

**Comment by tgolen** [comment] 2024-12-02 22:02
Maybe the prompts should be reworded?

**Comment by s77rt** [comment] 2024-12-02 22:05
Ah totally my bad. I just realised it said **reported**. I have been reading this as reproduced for a while 😅

**Comment by s77rt** [comment] 2024-12-02 22:06
> Maybe the prompts should be reworded?

i think it's fine but maybe remove the `(deploy blocker)` suffix because it's a little misleading as in this case it was reported on staging but not a deploy blocker since it was found testing another flow

**Comment by JmillsExpensify** [comment] 2024-12-05 13:58
$250 approved for @bernhardoj
