### ISSUE TITLE
[HOLD for payment 2023-11-02] [$125] Member list - Tooltip show phone number include "@expensify.sms"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29645] opened 2023-10-15 21:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697284170153569

## Action Performed:
1. Create a workspace
2. Go to member and click invite
3. Input invite account phone number "eg: +84989493033"
4. Click next => Invite
5. Hover onto the newly invited member's avatar, Observe that the phone number contains "@expensify.sms""
## Expected Result: 
Tooltip show does not include "@expensify.sms"
## Actual Result: 
Tooltip show phone number include "@expensify.sms"

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/60dae977-a27d-47cc-beb1-1896989502ca

![Snip - (8) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/1258aadf-2ff8-4ee3-990f-b23c817a0103)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://github.com/Expensify/App/assets/38435837/665bfdaa-eeb1-4d99-8c56-548b0ef829e4

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015beae79e8b315fdb</li>
        <li>Upwork Job ID: 1713671640416272384</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-10-15 21:43
## Proposal by @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
The tooltip shown does not include "@expensify.sms" on the member page, it should not include '@expensify.sms'
### What is the root cause of that problem?
We have the logic to get the name to show the tooltip here:
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/workspace/WorkspaceMembersPage.js#L331-L337
But we don't format if the login is a phone number because it has the format "xxxxxx@expensify.sms"
In addition, I also found the same error in TaskPreview, we previously fixed it but since we switched to using accountid here, the error has returned.
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/ReportActionItem/TaskPreview.js#L79-L82
But we haven't formatted the phone here:
https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L43
### What changes do you think we should make in order to solve the problem?
We should use `formatPhoneNumber` to format the name
1. In [here](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/pages/workspace/WorkspaceMembersPage.js#L331-L337)
```js
name: props.formatPhoneNumber(details.login),
```
2. And [MentionUserRenderer](https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L43)
```js
displayNameOrLogin = LocalePhoneNumber.formatPhoneNumber(lodashGet(user, 'login', '')) || lodashGet(user, 'displayName', '') || translate('common.hidden');
```
### What alternative solutions did you explore? (Optional)
N/Axqx

**Comment by saad995** [comment] 2023-10-16 04:28
Please re-state the problem that we are trying to solve in this issue.
The tooltip shows "@expensify.sms" on the member page icon, it should not include '@expensify.sms'.

What is the root cause of that problem?
For the icon tooltip, we are not formatting the login name,
![image](https://github.com/Expensify/App/assets/24203380/b7d16d53-3e83-47a8-9843-9d3a2aa6d388)

What changes do you think we should make in order to solve the problem?
We can make use of the already defined function for formatting phone number, the change would look like this,
![image](https://github.com/Expensify/App/assets/24203380/f53aed10-a3dd-4cba-b8b2-e94f93f41fdf)

**Comment by miljakljajic** [comment] 2023-10-19 13:38
@eVoloshchak what are your thoughts on the above? Seems like a simple fix but something we definitely want to remove.

**Comment by eVoloshchak** [comment] 2023-10-20 09:07
@namhihi237's [proposal](https://github.com/Expensify/App/issues/29645#issuecomment-1763512100) looks good to me!
Both proposals are essentially the same, the fix is quite straightforward, so let's proceed with the first proposal

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2023-10-23 11:24
Not overdue, awaiting @youssef-lr's review of https://github.com/Expensify/App/issues/29645#issuecomment-1772361270

**Comment by youssef-lr** [comment] 2023-10-23 11:32
Assigned @namhihi237, and also adjusted the price based on the priority of this bug being low and is a simple fix.

**Comment by miljakljajic** [comment] 2023-11-02 15:05
Sent @namhihi237 contract for reporting bonus, contributor payment + urgency bonus.

**Comment by miljakljajic** [comment] 2023-11-02 16:25
Paid, closing.

**Closed by miljakljajic** 2023-11-02 16:25 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by eVoloshchak** [comment] 2023-11-02 18:13
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/15280
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/15280/files#r1380605892
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a simple visual bug, I don't think an additional discussion is needed here

**Comment by eVoloshchak** [comment] 2023-11-02 18:17
**Regression Test Proposal**

1. Go to any workspace' settings ar create a new workspace
2. Go to `Members` and click on `Invite`
3. Paste a phone number "eg: +84989493033" and select it
4. Click next => Invite
5. Hover on the newly invited member's avatar, verify that the phone number does not contain "@expensify.sms"

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-11-02 18:17
@miljakljajic, could you post a payment summary for this so I can request the payment on NewDot? Thanks

**Comment by eVoloshchak** [comment] 2023-11-06 14:20
@miljakljajic, gentle bump on the above

**Comment by miljakljajic** [comment] 2023-11-07 12:33
@eVoloshchak is eligible for manual payments, listing the payment summary here:

C+ role: 125 USD + 50% urgency bonus:

187.5 USD owed

**Comment by JmillsExpensify** [comment] 2023-11-13 18:41
$187.50 payment approved for @eVoloshchak based on comment above.
