### ISSUE TITLE
[$1000] First thread message is focused instead of latest edit message in reply in thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22676] opened 2023-07-11 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send multiple messages
4. Hover and click on edit message on any 2 messages, keep them in edit mode
5. Hover over non edited message and click on reply in thread
6. Send multiple messages
7. Edit first message and any other message, keep them in edit mode
8. Revisit report open in step 2 and observe that latest edit message is in focus
9. Visit reply in thread post and observe that first thread message is in focus instead of lastest edit message
## Expected Result: 
App should keep latest edit message in focus in reply in thread too
## Actual Result: 
App does not keep latest edit message in focus in reply in thread if one of the message is first message of thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/841c9671-2838-440a-8410-353da020845c

https://github.com/Expensify/App/assets/43996225/f2e55269-e854-4f0a-84c4-2e9a68a93577

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689097475165729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116bc1eacbff51013</li>
        <li>Upwork Job ID: 1679117614909104128</li>
        <li>Last Price Increase: 2023-08-02</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-07-14 14:10
Will review this in my morning

**Comment by abdulrahuman5196** [comment] 2023-07-15 10:09
I looked in the proposal above and there should some more edge cases to this issue itself. Will check more and update.

**Comment by s-alves10** [comment] 2023-07-17 04:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

First thread message is focused instead of latest edit message in reply in thread

### What is the root cause of that problem?

Let's take a look at the `withOnyx` HOC.
https://github.com/Expensify/react-native-onyx/blob/main/lib/withOnyx.js

We set the initial state to {loading: true} in the contructor and return null if state.loading is true in render function. The component state is set after component is mounted(in componentDidMount). That is, the original component(not wrapped) is rendered at the next rendering cycle.

Now let's take a look at the `ReportActionList` component. The first thread message is rendered in `ReportActionItemParentAction` component.
https://github.com/Expensify/App/blob/f54c4f3a02ea993b28431d7960d45f75fa7613a9/src/pages/home/report/ReportActionsList.js#L132-L139

As you can see below, the `ReportActionItemParentAction` component is wrapped with `withOnyx` HOC.
https://github.com/Expensify/App/blob/f54c4f3a02ea993b28431d7960d45f75fa7613a9/src/pages/home/report/ReportActionItemParentAction.js#L83-L95

So the `ReportActionItem` component inside the `ReportActionItemParentAction` component will be rendered at the next rendering cycle. In a nutshell, the first thread message is rendered at the next rendering cycle, that is, is rendered at the last among the items in the list.

The focus will be set to the lastly rendered `ReportActionItem`, that is, the first thread message will be focused
https://github.com/Expensify/App/blob/f54c4f3a02ea993b28431d7960d45f75fa7613a9/src/pages/home/report/ReportActionItem.js#L136-L142

This is the root cause

### What changes do you think we should make in order to solve the problem?

We have getParentReportAction for getting the parent report action
https://github.com/Expensify/App/blob/f54c4f3a02ea993b28431d7960d45f75fa7613a9/src/libs/ReportActionsUtils.js#L102

We can use this to remove the withOnyx wrapper from the `ReportActionItemParentAction` component.

1. Remove the reportID and parentReportID props and add the action(actually the parent action) props.
2. Remove the withOnyx wrapper from the `ReportActionItemParentAction` component.
3. In `ReportActionList`, remove the `reportID` and `parentReportID`, and add the `action` props to the `ReportActionItemParentAction` component with value `ReportActionsUtils.getParentReportAction(report)`

This works as expected and fixes the root cause.

The complete source can be found here
https://github.com/s-alves10/App/tree/fix/issue-22676

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/a591691d-d125-4c80-b771-3bf94e4bf5a2

</details>

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:52
@abdulrahuman5196 any thoughts on the proposal above?

**Comment by abdulrahuman5196** [comment] 2023-07-21 16:07
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-07-21 16:08
We are having a tracking issue for composer focus issues - https://github.com/Expensify/App/issues/15992

Maybe we could handle part of that issue itself. @laurenreidexpensify 

Will add a comment there

**Comment by s-alves10** [comment] 2023-07-21 16:11
@abdulrahuman5196 
The RCA of this specific issue is something different and I think this should be handled separately

**Comment by laurenreidexpensify** [comment] 2023-07-24 10:39
@abdulrahuman5196 did we conclude that this issue is under the scope of https://github.com/Expensify/App/issues/15992 or should be fixed here?

**Comment by abdulrahuman5196** [comment] 2023-07-26 16:07
No reply yet. Will also review proposals here meanwhile

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:00
@abdulrahuman5196 bump ^^ thanks

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:55
Reviewing today

**Comment by abdulrahuman5196** [comment] 2023-08-01 15:45
@laurenreidexpensify For me its focusing the last edit message always


https://github.com/Expensify/App/assets/46707890/4d36e768-c249-4a0e-b8bb-dc7230a863c5

**Comment by s-alves10** [comment] 2023-08-02 12:20
@abdulrahuman5196 

This is still reproducible in staging, production, and dev

**Comment by laurenreidexpensify** [comment] 2023-08-02 12:44
@s-alves10 can you please drop a screen recording of the latest reproducible attempt on your side? Thanks

**Comment by s-alves10** [comment] 2023-08-02 13:45
@laurenreidexpensify 


<details>
    <summary>Staging</summary>


https://github.com/Expensify/App/assets/126839717/e1663661-5881-4810-8cfb-237ccbdc5779


</details>

**Comment by laurenreidexpensify** [comment] 2023-08-07 12:29
I also can't reproduce this, and keep seeing the correct message in the preview pane. I am closing.

**Closed by laurenreidexpensify** 2023-08-07 12:29 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
