### ISSUE TITLE
PropType error when opening Payments page. (dev only)

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9825] opened 2022-07-11 04:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/docs/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login 
2. Navigate to Settings > Payments

## Expected Result:
Page should open without any error

## Actual Result:
PropType error when opening Payments page. (dev only)

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.79-0
**Reproducible in staging?:** N
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="685" alt="image - 2022-07-11T001515 991" src="https://user-images.githubusercontent.com/43995119/178187435-d6dff6ee-944d-469b-8811-8d8093d7b635.png">

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1657052974042869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-07-11 17:26
Interesting. This looks like a bug on importing `withLocalizePropTypes`. Trying to find what could be happening

**Comment by parasharrajat** [comment] 2022-07-12 14:11
I looked into this and the issue is that https://github.com/Expensify/App/blob/046a8b68eed762d8dc2550e0658c02e51ab339df/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L329 throws a warning only when the page is opened for the first time after login. 

This happens as `formattedSelectedPaymentMethod` state is initialized with empty object and `formattedSelectedPaymentMethod.title` is undefined until user selects a payment method from the UI. 

To fix this: 
1. Initialize the state `formattedSelectedPaymentMethod` with ``` {title: ''}```

**Comment by danieldoglas** [comment] 2022-07-13 00:07
@parasharrajat should be assigned to this job.

**Comment by danieldoglas** [comment] 2022-07-13 17:15
@mallenexpensify is OOO, I'll remove him and add the tag again.

**Comment by kevinksullivan** [comment] 2022-07-16 00:00
Job posted and sent an offer to @parasharrajat 

https://www.upwork.com/jobs/~014153e33fdc8f9306

**Closed** 2022-07-27 18:49 UTC
Labels: External, Engineering, Weekly, Overdue
