### ISSUE TITLE
Sign in -  Error message displayed right after login 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8642] opened 2022-04-14 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)

2. Log in with your any account

## Expected Result:
No error message displayed when logged in

## Actual Result:
Concierge chat opens up and see the error message after sign in

It occurs occasionally

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Android
- Mobile Web

**Version Number:** v1.1.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):**  Iheretsutest+0102@gmail.com / Yulia1986Gerets
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/163396594-ed2032c3-7d7c-496c-a4b1-723882a88674.mp4

https://user-images.githubusercontent.com/43996225/163396595-3d10f4b7-ca91-49b8-9b34-a01802e5cc38.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-04-14 18:38
I looked at this and this is probably due to changing testing accounts often since the report that is supposed to be missing belongs to another user. I think we cache it or something so when we open the app we go back to the same one. I tried to reproduce it but I couldn't, so I am going to close this.

**Closed by pecanoro** 2022-04-14 18:38 UTC
Labels: Engineering, Daily
