### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Update "X selected" button above table views to be a dropdown button instead of a split button

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#39832] opened 2024-04-08 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856 N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** @dannymcclain 
**Slack conversation:** [Link](https://expensify.slack.com/archives/C05RECHFBEW/p1712587293427759?thread_ts=1712371681.666529&cid=C05RECHFBEW)

## Action Performed:
1. Go to any part of the new workspace editor for collect policies that has a table view. For example: tags, taxes, categories, members, or distance rates.
2. Select rows of data using the checkboxes on the left side of the row 

## Expected Result:
1. Rather than using a split button, we should be using a dropdown button. A dropdown button just has a small arrow right after the label text and does not have two distinct "zones" in the button:

![image](https://github.com/Expensify/App/assets/2319350/2fa6ec24-dfc8-4396-8858-7e9348b6b9c5)

## Actual Result:
1. We're currently using a split button, which doesn't make sense for this UI interaction and also prevents the user from using the larger part of the button. 

## Workaround:
The smaller arrow part of the split button still works just fine. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![CleanShot 2024-04-08 at 17 37 36@2x](https://github.com/Expensify/App/assets/2319350/6b968056-ca1c-4e88-91cc-7c2f73a2457d)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

cc @Expensify/design @mountiny @luacmartins @trjExpensify 

Per Slack, let's start this one at $250. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b3c66ee08aa3e77</li>
        <li>Upwork Job ID: 1777360525265432576</li>
        <li>Last Price Increase: 2024-04-08</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by nkdengineer** [comment] 2024-04-08 15:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We're currently using a split button, which doesn't make sense for this UI interaction and also prevents the user from using the larger part of the button.

### What is the root cause of that problem?
This is new feature change

### What changes do you think we should make in order to solve the problem?

We should update `ButtonWithDropdownMenu` to:
- Remove the divider in between
- Make the full button width clickable
- Center align both the text in the icon
These are all straight forward style changes

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-08 16:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We're currently using a split button, which doesn't make sense for this UI interaction and also prevents the user from using the larger part of the button.

### What is the root cause of that problem?
This is new feature change

### What changes do you think we should make in order to solve the problem?

We create a new component `ButtonWithDropdown`, which is similar to `ButtonWithDropdownMenu` but has the following differences:
- Remove the divider in between, by removing the whole Caret button [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/ButtonWithDropdownMenu/index.tsx#L88-L111)
- Make the full button width clickable, by using this `Button` and make the caret the `iconRight`
```
iconRight={() => <Icon
    medium={isButtonSizeLarge}
    small={!isButtonSizeLarge}
    src={Expensicons.DownArrow}
    fill={success ? theme.buttonSuccessText : theme.icon}
/>}
shouldShowRightIcon
```
And remove the `customText !== undefined && styles.cursorDefault, customText !== undefined && styles.pointerEventsNone` [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/ButtonWithDropdownMenu/index.tsx#L84)
- Add some padding horizontal to look like design. In [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/ButtonWithDropdownMenu/index.tsx#L84)
```
innerStyles={[innerStyleDropButton, styles.pr9, styles.pl9]}
```
- Make sure the `PopoverMenu` [here](https://github.com/Expensify/App/blob/ec41a4bee85afe0cf666fe178e90a8b5b92f3c33/src/components/ButtonWithDropdownMenu/index.tsx#L135) has the main Button above as the anchor, by setting the `caretButton` to the main button ref.

These are all straight forward style changes

And use the `ButtonWithDropdown` anywhere we need the `ButtonWithDropdown` with the above style.

Instead of having a separate `ButtonWithDropdown` component, we can add a prop to `ButtonWithDropdownMenu` to control this button style.

I'm happy to provide test branch for the above change (to produce the below result) if the C+ needs it.

### What alternative solutions did you explore? (Optional)
NA

### Result
<img width="653" alt="Screenshot 2024-04-08 at 11 08 22 PM" src="https://github.com/Expensify/App/assets/161821005/c5452030-8352-465f-8e5a-fedb150c70f7">

**Comment by dannymcclain** [comment] 2024-04-08 17:12
Just a quick note that the updated button doesn't need to be a fixed width. It can just can just follow the standard button padding.

Reference here for medium buttons with a right icon (since I think this is a medium button?):
![image](https://github.com/Expensify/App/assets/7516624/70902e09-809d-4dc4-9851-d16aadf7b454)

cc @Expensify/design for any dissenting opinions.

**Comment by shawnborton** [comment] 2024-04-08 18:26
I think it's a medium button, yup. And good shout Danny, I agree it doesn't need to be fixed.

**Comment by nkdengineer** [comment] 2024-04-09 14:12
[Proposal updated](https://github.com/Expensify/App/issues/39832#issuecomment-2043170656) to remove the additional padding, based on [design team's confirmation](https://github.com/Expensify/App/issues/39832#issuecomment-2043265797)

**Comment by dylanexpensify** [comment] 2024-04-11 11:17
Bump @abdulrahuman5196 to review

**Comment by abdulrahuman5196** [comment] 2024-04-12 13:49
Checking now

**Comment by abdulrahuman5196** [comment] 2024-04-12 18:15
This is a straightforward feature request. So choosing the first proposal with adequate information to work on the implementation.

@nkdengineer 's proposal here https://github.com/Expensify/App/issues/39832#issuecomment-2043170656 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by dylanexpensify** [comment] 2024-04-12 19:46
@luacmartins or @arosiclair to confirm proposal req from Abdul!

**Comment by abdulrahuman5196** [comment] 2024-04-13 05:14
Hi @ShridharGoel , This issue is a feature request. The expectation would be to provide a solution to address the core issue by providing adequate information on how you would be solving the problem in PR. We don't expect code perfect sample in proposal, which would instead be done in the PR. Minor issues or changes would be handled as part of the PR process. 
So here the proposal which came first was suggested by me.

**Comment by nkdengineer** [comment] 2024-04-13 08:32
> This would lead to performance issues because of unnecessary re-renders.

@ShridharGoel This is a trivial issue and can be easily avoided with the use of memoization (like `useCallback`). I noticed already when proposing because it's even producing a `react/no-unstable-nested-components` lint issue. So there's no chance we'll miss it in the PR phase.

I didn't elaborate more on memoization when proposing because that was meant as a pseudo-code, not full fledged PR ready to merge as @abdulrahuman5196 mentioned
> We don't expect code perfect sample in proposal, which would instead be done in the PR. Minor issues or changes would be handled as part of the PR process.

@arosiclair I think we can [move forward](https://github.com/Expensify/App/issues/39832#issuecomment-2052244813) here 👍

**Comment by dylanexpensify** [comment] 2024-04-15 10:14
bump @arosiclair

**Comment by arosiclair** [comment] 2024-04-15 14:01
@nkdengineer's proposal LGTM

> Instead of having a separate ButtonWithDropdown component, we can add a prop to ButtonWithDropdownMenu to control this button style.

Yeah I think we should do this with an optional `isSplit` prop (`true` by default). That way we don't have to maintain 2 dropdown buttons separately.

**Comment by arosiclair** [comment] 2024-04-15 14:02
Oh I see @luacmartins self assigned. Lemme know if you still want to manage otherwise I can handle it 👍

**Comment by dylanexpensify** [comment] 2024-04-29 10:59
@abdulrahuman5196 @luacmartins mind giving an update?

**Comment by abdulrahuman5196** [comment] 2024-04-29 11:50
Hi, I am going through PR review.

**Comment by luacmartins** [comment] 2024-04-29 16:24
PR is merged

**Comment by luacmartins** [comment] 2024-04-29 16:53
@Expensify/design could you please review the new split button styles on main? We merged the PR above with the logic for the new button, we'll address any style tweaks in a follow up if needed.

**Comment by shawnborton** [comment] 2024-04-29 16:58
Is it deployed, or what is the best way to test it?

**Comment by shawnborton** [comment] 2024-04-29 17:32
Right on, will dust off the ol' dev environment 🤣

**Comment by shawnborton** [comment] 2024-04-29 17:42
Looks good to me too!
![CleanShot 2024-04-29 at 13 41 17@2x](https://github.com/Expensify/App/assets/2319350/a69c9cd1-78d8-4dc5-8ab0-39cee015cb72)

![CleanShot 2024-04-29 at 13 42 08@2x](https://github.com/Expensify/App/assets/2319350/c8085d73-dafb-4af1-ad7a-952e7f264854)

**Comment by dylanexpensify** [comment] 2024-05-01 07:44
payment coming up!

**Comment by dylanexpensify** [comment] 2024-05-07 08:31
Payment summary:
- Contributor: @nkdengineer $250
- Contributor+: @abdulrahuman5196 $250

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-05-13 18:59
bump @abdulrahuman5196 on checklist

**Comment by dylanexpensify** [comment] 2024-05-14 12:24
bump @nkdengineer

**Comment by nkdengineer** [comment] 2024-05-16 17:31
Hi @dylanexpensify my Upwork account doesn't have any Connects left so I'm unable to apply. Could you directly send an offer to [my Upwork profile](https://www.upwork.com/freelancers/~0134d0b74faef1a5ac)? 

Thanks 🙇

**Comment by dylanexpensify** [comment] 2024-05-21 19:12
sent invite @nkdengineer!

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:19
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. New feature.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1.     Go to workspace setting
2.     Enable all features: distance rates, categories, tags, taxes
3.     Select rows of data using the checkboxes on the left side of the row
4.     Verify that: A dropdown button with no split is displayed in top right
5.     Click to this button
6.     Verify that: A dropdown is working fine


@dylanexpensify

**Comment by nkdengineer** [comment] 2024-05-23 17:07
> sent invite @nkdengineer!

@dylanexpensify I applied to the job!

**Comment by dylanexpensify** [comment] 2024-05-29 06:39
@nkdengineer offer sent!

**Comment by nkdengineer** [comment] 2024-05-31 15:54
@dylanexpensify Thank you 🙇 I accepted the offer

**Comment by luacmartins** [comment] 2024-06-03 23:50
Are we good to close this one?

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:49
> Are we good to close this one?

I got paid. If @nkdengineer  is also paid we can close this? @dylanexpensify

**Comment by nkdengineer** [comment] 2024-07-01 11:49
Sorry @dylanexpensify I wasn't paid here, could you reopen the issue to help with this?

TIA

**Comment by dylanexpensify** [comment] 2024-07-08 17:32
Yes!

**Comment by dylanexpensify** [comment] 2024-07-08 17:33
Done!

**Closed by dylanexpensify** 2024-07-08 17:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
