### ISSUE TITLE
[HOLD for payment 2022-11-24] [$250] Bug: Safari-  RHN leaves empty space at the bottom after closing the 2nd tab reported by @Tushu17 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12005] opened 2022-10-19 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open new.expensify.com in safari browser
2. Open another tab
3. Open settings page in NewDot
4. Close the other tab

## Expected Result:
No changes appear in the NewDot tab

## Actual Result:
RHN doesn't resize itself & leave empty space below.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Safari - version 16.1

**Version Number:** 1.2.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196799240-07bdab14-2928-4df7-815e-056bc8ffc408.mp4

https://user-images.githubusercontent.com/43996225/196797761-d3b1e15b-8551-44cf-a9b2-96d96a74f83f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666127526070089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment] 2022-10-20 18:23
@sakluger Yes, It's still reproducible for me in both staging and production. You can also repro this by:-
 1. Opening safari browser and decrease its window size.
 2. Now go to Expensify website.
 3. Open Settings page 
 4. Full screen safari window. 

https://user-images.githubusercontent.com/89839952/197027697-e6111387-bbf8-4cf1-ab1b-b4800c9ce56f.mov

**Comment by sakluger** [comment] 2022-10-24 21:27
I'm still unable to reproduce, so I've asked for others to help in Slack.

**Comment by sakluger** [comment] 2022-10-24 21:28
@Tushu17 what version of Safari are you using? I'm on Safari Version 16.0.

**Comment by Tushu17** [comment] 2022-10-25 11:38
> @Tushu17 what version of Safari are you using? 

@sakluger I'm using version 16.1 of Safari.

**Comment by sakluger** [comment] 2022-11-02 05:19
Sorry for the delay! I upgraded to Safari 16.1 and was able to reproduce the behavior. I think this can be handled by a contributor.

**Comment by sakluger** [comment] 2022-11-02 05:24
Internal Upwork job post: https://www.upwork.com/ab/applicants/1587676826820882432/job-details
External Upwork job post: https://www.upwork.com/jobs/~01b84397fcb25f5ce2

**Comment by VikalpP** [comment] 2022-11-02 06:57
Explanation about the issue - 

I see this Sidebar is actually rendered in "Modal", and Modal has a height "100%". **(NB)**

As the Safari browser itself is skeptical about re-painting the UI for these types of browser-relevant changes (eg, closing tab, on iPhone bottom search bar, etc) - it doesn't update the UI if height is simply set to percentage 100%. 

Possible Solution - 

Replacing the height "100%" with "100vh", would have absolute value instead of relative, which seems to be triggering Safari to re-paint the layout. 

Since I'm coming from the Upwork thread - I'm just submitting my proposal (as above), waiting for approval so I can raise a PR.

**Comment by VikalpP** [comment] 2022-11-04 02:24
Hi @sakluger, can you please review the above proposal 👆?

**Comment by chiragsalian** [comment] 2022-11-04 18:11
Nice I like the proposal. Feel free to create the PR @VikalpP.

**Comment by VikalpP** [comment] 2022-11-04 20:00
Thanks, 🎉

@rushatgabhane / @chiragsalian 
Is there any format to follow while applying for this on Upwork?

**Comment by VikalpP** [comment] 2022-11-04 20:17
Applied on Upwork. ✅
I'll raise a fix PR for this max by 7 Nov. 

_Please communicate if anything else that I need to know. (this would be my first time contributing to Expensify)_

**Comment by VikalpP** [comment] 2022-11-05 13:32
@chiragsalian / @rushatgabhane 

Slight correction in my proposal, I mistakenly posted wrong the wrong line reference. 
I meant to change the height for the below line - 
https://github.com/Expensify/App/blob/0724337138a4d80f6603074cc9af5c186cb524ec/src/styles/StyleUtils.js#L100

Also, to fix any regression on Mobile iOS, we would use `height: 'calc(100vh - 100%)'`.

**Comment by VikalpP** [comment] 2022-11-05 13:33
I have changes ready to be pushed, just waiting on someone to accept my proposal on Upwork & initiate the contract.

**Comment by VikalpP** [comment] 2022-11-07 09:33
@rushatgabhane I'm waiting for someone on Upwork to accept my proposal and initiate the Contract. 
Do you think you have access or know someone who can initiate the Contract? 🙂

I have the branch with the fix ready to push.

**Comment by VikalpP** [comment] 2022-11-07 18:11
Thanks @chiragsalian for a quick heads-up here. 🙂

**Comment by sakluger** [comment] 2022-11-22 00:51
Hi @VikalpP I've accepted your proposal on Upwork.

**Comment by sakluger** [comment] 2022-11-28 17:12
Apologies for the delay, I just returned from the long Thanksgiving holiday weekend. I will review and pay out today as long as everything looks good.

**Comment by sakluger** [comment] 2022-11-28 17:18
Hi all, I just noticed that in [this PR comment](https://github.com/Expensify/App/pull/12366#issuecomment-1319529184), @aimane-chnaif suggested we revert the PR for this GH issue, but it was never reverted. Was that suggestion to revert incorrect? Before paying out, I want to make sure that the fix for this issue didn't cause any regressions.

**Comment by chiragsalian** [comment] 2022-11-28 23:50
Yeah, I don't see any revert. I see vikalp's code on our main branch. There is no mention that this caused a regression anywhere so I can only assume it's been stable since it's been live. Feel free to go ahead and process the payment.

**Comment by sakluger** [comment] 2022-11-28 23:58
Thanks for checking @chiragsalian! I went ahead and paid out everyone for this job and closed the Upwork post. Finishing up the checklist before closing the issue here.

**Closed** 2022-11-29 00:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
