### ISSUE TITLE
[$250] Workspace - WS invite message briefly shows code when the WS description has native emojis

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44002] opened 2024-06-19 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4646131&group_by=cases:section_id&group_id=229065&group_order=asc
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Have a workspace where it's description contains one or more native Android emojis
1. Open the app
2. Navigate to the workspace members page
3. Tap on the "Invite" button
4. Select any account
5. Tap on the "Next" button
6. Navigate back
7. Select the account again
8. Tap on the "Next" button

## Expected Result:
Only the emoji should be shown

## Actual Result:
The workspace invite message briefly shows code when the workspace description has native Android emojis. Sometimes it appears after navigating back and to the invite message page again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9232d62c-3463-4785-8f0b-f952b47ff1d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf332ff1f1f26822</li>
        <li>Upwork Job ID: 1803436573122955546</li>
        <li>Last Price Increase: 2024-06-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by lanitochka17** [comment] 2024-06-19 14:20
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Sparth19** [comment] 2024-06-19 18:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
WS invite message flickers `<emoji> </emoji>` code when description has native emoji symbols



### What is the root cause of that problem?
inviteMessage input field's default value is passed without parseHtmlToMarkdown. so its briefly showing Html code.

https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L204

after that we are updating with parseHtmlToMarkdown then it works fine

https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L99

### What changes do you think we should make in order to solve the problem?
we need to use parseHtmlToMarkdown in defaultValue

```
<InputWrapper
...
defaultValue = {parseHtmlToMarkdown(getDefaultWelcomeNote())}
/>
```

or, we can combine the `getDefaultWelcomeNote` function with the `parseHtmlToMarkdown` function to streamline the process and eliminate the brief display of the raw tags

https://github.com/Expensify/App/blob/de66757deda02a556923a991bd7715134d94c47e/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L84-L95

**Comment by bernhardoj** [comment] 2024-06-20 03:21
Same root cause as https://github.com/Expensify/App/issues/42668

**Comment by abdulrahuman5196** [comment] 2024-06-20 16:11
> Same root cause as #42668

@sonialiap seems to be a dupe

**Comment by sonialiap** [comment] 2024-06-21 12:38
Closing as dupe

**Closed by sonialiap** 2024-06-21 12:38 UTC
Labels: External, Daily, Help Wanted, Bug
