### ISSUE TITLE
[$1000]  Invite new members - Users is highlighted after selecting

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14781] opened 2023-02-03 01:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Users is not highlighted after selecting

## Expected Result:
Users is highlighted after selecting

## Actual Result:
Unknown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.64.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/216487654-33052cab-265d-498b-a32d-aa047c1d1f74.mp4

https://user-images.githubusercontent.com/93399543/216487656-258f7e85-4ac5-4c50-908e-cc58f366cf55.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162271ebdb95d5f22</li>
        <li>Upwork Job ID: 1621583687820718080</li>
        <li>Last Price Increase: 2023-02-03</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-02-03 01:16
Issue is not reproduced in production


https://user-images.githubusercontent.com/93399543/216487755-b150a92b-a710-42bd-930b-75284651a2b3.mp4

**Comment by kbecciv** [comment] 2023-02-03 01:18
Windows/Chrome is broken with different behavior

https://user-images.githubusercontent.com/93399543/216487954-516dda11-8aa4-4435-802c-b9074f0fdfe0.mp4

**Comment by deetergp** [comment] 2023-02-03 21:02
@kbecciv Can you please clarify what the problem is here? You've got videos illustrating three different behaviors and it's unclear which is the incorrect behavior and which, if any, is the desired behavior. I just tested Staging & Prod in macOS Chrome and both seem behave the same.

**Comment by kbecciv** [comment] 2023-02-03 21:20
@deetergp This is correct behavior posted in here https://github.com/Expensify/App/issues/14781#issuecomment-1414581430, but staging is broken

**Comment by thienlnam** [comment] 2023-02-03 23:27
Reverting the PR doesn't seem to fix it, going to remove the blocker on this and we can continue investigating

**Comment by thienlnam** [comment] 2023-02-04 01:45
Actually this is resolved now, no longer reproducible after the deploy

**Comment by Tushu17** [comment] 2023-02-04 05:11
Hey @thienlnam, I've reported this deploy blocker here :-
https://expensify.slack.com/archives/C049HHMV9SM/p1675358449465149

Is this eligible for reporting bonus?

**Comment by thienlnam** [comment] 2023-02-06 19:06
Honestly, not sure - the order of events was pretty weird

1. Was reproducible on staging
2. Reverted https://github.com/Expensify/App/pull/14826 and was not able to reproduce anymore on that branch
3. Before merging the revert, it was no longer reproducible on staging
4. Was able to reproduce in the revert branch
5. Merged the revert
6. Still no longer reproducible in staging / prod

There must have been something CPed to staging at that time after I created my branch but doesn't explain why I couldn't reproduce it when I made my branch the first time (unless I was actually on main or something... was late on a friday).  I think the contributor who added the PR I reverte, can re-add the changes and in testing verify that it doesn't create a regression of this

**Comment by jliexpensify** [comment] 2023-02-06 23:08
Invited @Tushu17

**Comment by Tushu17** [comment] 2023-02-07 05:01
@jliexpensify Okay, I've applied for the job. Thank you.

**Comment by jliexpensify** [comment] 2023-02-07 05:15
Offer sent @Tushu17

**Comment by Tushu17** [comment] 2023-02-07 05:23
@jliexpensify Offer accepted, Thanks.

**Comment by jliexpensify** [comment] 2023-02-07 05:30
Paid Tushar, @rushatgabhane and @thienlnam do you want to keep this issue open for now?

**Comment by thienlnam** [comment] 2023-02-07 18:25
This is no longer reproducible in prod, so we can close. 

@rushatgabhane No worries if you don't have the time for [this](https://github.com/Expensify/App/issues/14781#issuecomment-1419603878) - that can be part of the original issue https://github.com/Expensify/App/issues/14314

**Closed by thienlnam** 2023-02-07 18:25 UTC
Labels: Engineering, Daily, Bug

**Comment by tienifr** [comment] 2023-02-09 04:21
# Regression Test Proposal

**Bug**: Invite new members - Users is highlighted after selecting

**Proposed Test Steps**:

- Open the app
- Open Workspace and go to the invite member page
- Select some members
- Verify that selected members aren't highlighted

Do we :+1: or :-1: 

Video (Regression Test):
https://user-images.githubusercontent.com/113963320/217418140-3cb8ccba-cdf6-4c41-b674-cd51628590af.mov
