### ISSUE TITLE
[$1000] When completing a task, the LHN subtitle of the parent report changes

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19098] opened 2023-05-17 06:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task
2. Complete the task
3. Reopen the task
4. Sign in / sign back out
5. Check the LHN

## Expected Result:
Describe what you think should've happened
6. That the LHN subtitle shows the last action

## Actual Result:
Describe what actually happened
It shows this is the beginning of your chat with ...
<img width="370" alt="Screenshot 2023-05-16 at 11 09 00 PM" src="https://github.com/Expensify/App/assets/30609178/59258f97-2dd6-4cb9-a860-f9a878cdfb85">

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01284c4048b8695825</li>
        <li>Upwork Job ID: 1658808664995713024</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-05-17 17:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When completing a task, the LHN subtitle of the parent report changes after fresh sign in or when a new comment is added and deleted after it. The order of chat is also wrong.

### What is the root cause of that problem?
When a task is completed, the `completeTask` method calls `buildOptimisticTaskReportAction` to get the `completedTaskReportAction` which is used in `optimisticData`.
https://github.com/Expensify/App/blob/3559764900377c21d343c0498d2f901ab50ba2d4/src/libs/actions/Task.js#L155-L157

In `buildOptimisticTaskReportAction` method, in the message field, `html`is not set. 
https://github.com/Expensify/App/blob/3559764900377c21d343c0498d2f901ab50ba2d4/src/libs/ReportUtils.js#L1453-L1473

In the `deleteReportComment`, to update the LHN with the last visible message, `getLastVisibleMessageText` is used and if `lastMessageText` is empty ('') then `optimisticReport` contains empty string in the `lastMessageText` and `lastVisibleActionCreated` fields due to which LHN shows wrong message (This is the beginning of your chat with ...) and the order of chat is also wrong in LHN.
https://github.com/Expensify/App/blob/3559764900377c21d343c0498d2f901ab50ba2d4/src/libs/actions/Report.js#L836-L849

The `lastMessageText` returned from `getLastVisibleMessageText` is empty because `html` was not set in the `buildOptimisticTaskReportAction` in `ReportUtils.js` due to which `htmlText` is empty in line 233 which results in `messageText` being empty and ultimately returning empty string.
https://github.com/Expensify/App/blob/3559764900377c21d343c0498d2f901ab50ba2d4/src/libs/ReportActionsUtils.js#L225-L237

### What changes do you think we should make in order to solve the problem?
To fix this issue, we should set `html` field in `buildOptimisticTaskReportAction` in `ReportUtils.js`, the new code should look like this -
```javascript
message: [
    {
        text: message,
        html: htmlMessage,
        taskReportID,
        type: CONST.REPORT.MESSAGE.TYPE.TEXT,
    },
]
```

This would lead to `getLastVisibleMessageText` in `ReportActionUtils.js` returning valid message which would then show the correct message in LHN in the correct order.

Optional additional check:
If `message[0].html` is empty in `getLastVisibleMessageText` then we should use `message[0].text` and return it after preprocessing it like we do with html (truncating message for showing in LHN).

### What alternative solutions did you explore? (Optional)
NA

**Comment by s77rt** [comment] 2023-05-18 11:31
@Nikhil-Vats Thanks for the proposal. Your RCA is correct but you are talking about another problem that is very similar to this one. The root cause of stale subtitle after message deletion (the one you are talking about) and the root cause of stale subtitle after re-login (the one that the issue is originally opened for) are different.

### Stale subtitle after message deletion
Your RCA here is correct. You are suggesting to add `html` to `message`. This makes sense but I'm not totally sure this is mandatory so I asking on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684409421718929). Regarding the suggested `getLastVisibleMessageText` fix this is will handled here https://github.com/Expensify/App/issues/17658.

### Stale subtitle after re-login
I think this is coming from the backend. Calling `OpenReport` returns outdated `lastMessageHtml` and `lastMessageText` values. @PauloGasparSv Can you please check if the task related commands (CreateTask, ReopenTask, etc.) update those values accordingly?

**Comment by Nikhil-Vats** [comment] 2023-05-18 15:03
@s77rt So based on the discussion on Slack, we won't add the `html` to `message`, right? Shouldn't we add it for consistency?

I want to test the stale subtitle after re-login on staging, who should I reach out to for enabling the assign task permission on my account?

**Comment by s77rt** [comment] 2023-05-18 15:06
@Nikhil-Vats Please ask on slack.

**Comment by s77rt** [comment] 2023-05-19 21:11
@hoangzinh Thanks for the proposal. Your RCA seems correct. However if this is indeed coming from the backend then it will probably get fixed internally.

**Comment by bfitzexpensify** [comment] 2023-05-22 08:44
@PauloGasparSv were you able to determine if this is coming from the back-end?

**Comment by PauloGasparSv** [comment] 2023-05-22 22:04
> @PauloGasparSv I assume that other logic like AddComment update those, right? (just to be sure we are making the change in the right place)

Yes they do : )
I think this should only be happening to Tasks for now since it's new logic!

**Comment by PauloGasparSv** [comment] 2023-05-23 20:32
Changing this to `weekly`, I'll get back to this by EOW

**Comment by thienlnam** [comment] 2023-05-23 20:43
Putting on hold, we might be changing where the completed item goes https://expensify.slack.com/archives/C04QEB4MJEQ/p1684777285023769

**Comment by PauloGasparSv** [comment] 2023-05-29 18:44
> Changing this to weekly, I'll get back to this by EOW

Will get back to this tomorrow!

**Comment by PauloGasparSv** [comment] 2023-05-30 22:06
> Will get back to this tomorrow!

Could find the time so pushing this to tomorrow again.

**Comment by PauloGasparSv** [comment] 2023-06-02 23:01
Still haven't implemented a fix for this. I'm prioritizing a Manual Requests issue and this fix on Monday.

**Comment by PauloGasparSv** [comment] 2023-06-05 12:39
> Still haven't implemented a fix for this. I'm prioritizing a Manual Requests issue and this fix on Monday.

Working on this later today, not overdue.

**Comment by PauloGasparSv** [comment] 2023-06-06 00:10
Started working on this right now!

**Comment by PauloGasparSv** [comment] 2023-06-06 22:35
Right now I'm investigating why `OpenReport` doesn't fix this issue. That logic should return a last message text and HTML but I think no `html` field is being returned for the Task actions in this [line](https://github.com/Expensify/Web-Expensify/blob/0fb27f4055e6c6a4fd85576db8f60fe473ef6e0c/lib/ReportUtils.php#L2614).

Still investigating here!

**Comment by PauloGasparSv** [comment] 2023-06-07 16:08
Created a P.R. for App and Web-e! I'm still fixing bugs and posted my latest updates [here](https://github.com/Expensify/Web-Expensify/pull/37748#issuecomment-1581116261).

**Comment by PauloGasparSv** [comment] 2023-06-08 23:49
Didn't make any progress here today but I'll focus back on this tomorrow!

**Comment by PauloGasparSv** [comment] 2023-06-09 21:01
I finished the last bugs in the App P.R. and will make it ready for review later today! Just need to add test steps and fill the checklist first.

@thienlnam already reviewed the Web-E logic and suggested changes! I mentioned I would try to fix that today but I'll have to push it to Monday (so the Web-E P.R. should be ready by then).

**Comment by PauloGasparSv** [comment] 2023-06-12 22:24
Fixed the Web-E P.R. logic and asked for a re-review.

**Comment by PauloGasparSv** [comment] 2023-06-21 23:05
Quick update, I addressed comments in the App P.R. and asked for a re-review today.

While doing that I found a couple of problems related to the Task's complete/reopen/cancel flow that can be fixed in another P.R. but I'm not 100% sure where to implement the fix so I sent a message to the team asking for help and describing the problems [here](https://expensify.slack.com/archives/C04QEB4MJEQ/p1687385149610769)

**Comment by PauloGasparSv** [comment] 2023-06-22 23:25
I addressed the new comments in the App P.R. and asked for another re-review. I need to re-add evidences there and I'll do it tomorrow morning.

I also created https://github.com/Expensify/Web-Expensify/pull/37929 to fix the bug I mentioned [here](https://github.com/Expensify/App/issues/19098#issuecomment-1601803010).

I think we can get everything merged by tomorrow maybe : )

**Comment by PauloGasparSv** [comment] 2023-06-23 19:29
The app P.R. https://github.com/Expensify/App/pull/20373 was approved but there are a couple of comments on improving performance using hooks that I'll take a look at. I also need to add evidences to it before merging. Will try to do that today.

The Web-E P.R. https://github.com/Expensify/Web-Expensify/pull/37929 received a round of reviews! I addressed all comments there and we decided to move some logic to Auth. Asked for re-reviews there!

Since we decided to move some logic to Auth I created https://github.com/Expensify/Auth/pull/8175 which is in review too.

**Comment by PauloGasparSv** [comment] 2023-07-04 20:14
This is not overdue! The P.R. received a couple of rounds of reviews and there are some comments to address. Will address them ASAP

**Comment by PauloGasparSv** [comment] 2023-07-15 12:32
I'm going OOO for 2 weeks (starting on July 17th, back on July 31st) so I won't be updating this issue until then!

**Comment by bfitzexpensify** [comment] 2023-07-25 14:16
Not overdue. Paulo will be back next week.

**Comment by PauloGasparSv** [comment] 2023-08-01 22:30
I'm back from OOO, will try to focus on this tomorrow!

**Comment by PauloGasparSv** [comment] 2023-08-02 21:40
I addressed comments in the Web-E P.R. by adding a test! 

I'm thinking of starting the App P.R. over from scratch, there are way to many conflicts and changes since I left.

**Comment by thienlnam** [comment] 2023-08-02 21:45
Just leaving a note here - I have this App PR that does a refactor of a lot of the task code, on your new App PR could you please wait until https://github.com/Expensify/App/pull/22778 is merged? It's almost there but will prevent major conflicts

**Comment by PauloGasparSv** [comment] 2023-08-02 21:47
> Just leaving a note here - I have this App PR that does a refactor of a lot of the task code, on your new App PR could you please wait until https://github.com/Expensify/App/pull/22778 is merged? It's almost there but will prevent major conflicts

Yes I can, thanks so much for the heads up!

**Comment by PauloGasparSv** [comment] 2023-08-18 23:04
This was merged so I can back to working at this!

**Comment by s77rt** [comment] 2023-09-01 11:26
@PauloGasparSv Any updates here?

**Comment by thienlnam** [comment] 2023-09-05 22:23
Someone else internal will have to pick up where Paulo left off - I'm going to assign it to myself for the time being but am going to adjust the priority on this since it's low priority and I'm focused on waves for the time being

**Closed** 2023-11-02 13:23 UTC
Labels: Reviewing, Monthly, Internal, Bug
