### ISSUE TITLE
[HOLD for regression test] [$1000] Auto link does not work in edit mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13221] opened 2022-12-01 03:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. Send some message
3. Edit message
4. Enter a link url (eg. [googel.com](http://googel.com/))

## Expected Result:
The link should be auto linked

## Actual Result:
The link is not auto linked instead rendered as plain text.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.34-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204959737-491614fb-c2e0-4c1d-a5a7-fc84f7b15c00.mp4

https://user-images.githubusercontent.com/43996225/204959747-6be76b6b-7c6e-4cf7-96e1-6ae269c037c9.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659087408740329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01717a9143b77d9a7d</li>
        <li>Upwork Job ID: 1598491457766490112</li>
        <li>Last Price Increase: 2022-12-08</li>
    </ul>
</details>

**Comment by markarmanus** [comment] 2022-12-01 06:27
Proposal 

Issue: 
When we edit a comment we and parse the comment. we purposely dont parse links due to this issue https://github.com/Expensify/App/issues/9090
Basically if a user send a link. but then edits the link from

``` [www.google.com](https://www.google.com)```
To
```[www.google.com] or www.google.com``` 

It should not regenrate the link. 

Now we can either keep this behaviour. 

Or delete it and generate links again on edit.  (diff below)

```diff
diff --git a/src/libs/actions/Report.js b/src/libs/actions/Report.js
index 164d0e60b..05d079f0e 100644
--- a/src/libs/actions/Report.js
+++ b/src/libs/actions/Report.js
@@ -899,8 +899,7 @@ function editReportComment(reportID, originalReportAction, textForNewComment) {
 
     // Do not autolink if someone explicitly tries to remove a link from comment.
     // https://github.com/Expensify/App/issues/9090
-    const htmlForNewComment = parser.replace(textForNewComment, {filterRules: _.filter(_.pluck(parser.rules, 'name'), name => name !== 'autolink')});
-
+    const htmlForNewComment = parser.replace(textForNewComment);
     //  Delete the comment if it's empty
     if (_.isEmpty(htmlForNewComment)) {
         deleteReportComment(reportID, originalReportAction);
```

Or as a solution we can keep both and implement some sort of diff tool to check if the user deleted a specefic link we would not introduce it again. 

The way we can achieve this is the following:

1. get a list of links in the original comment through a regexp that captures [](?<link>)
2. for each link from step 1 compare to check if link still in new comment. 
      3. a. if its not in the new comment then add to a list of removedLinks
      3. b if its still in the new comment then do nothing
4. parse the new comment with all the links in it
5. loop thorugh all the removedLinks and remove them again from the new parsed comment. 


This would depend on the desired behaviour.

**Comment by strepanier03** [comment] 2022-12-02 01:30
Working through triaging this now:

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you’re unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by strepanier03** [comment] 2022-12-02 01:40
I am OoO for jury duty tomorrow. If immediate action is needed on this GH please post in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) for assistance, thank you.

**Comment by nhinq2** [comment] 2022-12-02 05:35
My solution for this issue:
- Preg_match check if has urls
- Insert href tag into message
- Display url via <span dangerouslySetInnerHTML={{__html: }} />

**Comment by sandipanghos** [comment] 2022-12-02 19:01
@kavimuru  Looking for new proposal or already fixed?

**Comment by nishancx** [comment] 2022-12-03 20:06
Proposal:
Cause: 
Due to this issue [#9090](https://github.com/Expensify/App/issues/9090), auto linking was disabled on edited comments as:
https://github.com/Expensify/App/blob/2e8d90736a19de0bf0332fb36afc42bab074434f/src/libs/actions/Report.js#L901

Solution:
- Auto linking is explicitly disabled, it needs to be re-enabled and to negate the problem.
- And to stop the [#9090](https://github.com/Expensify/App/issues/9090) problem, when user edits a comment, instead of showing the link in []() form, it needs to be parsed to plain text then the user will simply edit or remove the link.

**Comment by nishancx** [comment] 2022-12-04 07:19
Proposal:
Cause: 
Due to this issue [#9090](https://github.com/Expensify/App/issues/9090), auto linking was disabled on edited comments as:
https://github.com/Expensify/App/blob/2e8d90736a19de0bf0332fb36afc42bab074434f/src/libs/actions/Report.js#L901

Solution:
- Auto linking is explicitly disabled, it needs to be re-enabled to negate the problem as:
```diff
- const htmlForNewComment = parser.replace(textForNewComment, {filterRules: _.filter(_.pluck(parser.rules, 'name'), name => name !== 'autolink')});
+ const htmlForNewComment = parser.replace(textForNewComment);
```

**Comment by eVoloshchak** [comment] 2022-12-05 13:05
@markarmanus, thanks for looking into this, your [proposal](https://github.com/Expensify/App/issues/13221#issuecomment-1333274534) seems to correctly identify the root cause. 

Ideally, we want to have this fixed without breaking https://github.com/Expensify/App/issues/9090. I think the approach with `removedLinks` list is worth investigating, could you elaborate on it a bit more, with code snippets?

**Comment by markarmanus** [comment] 2022-12-05 20:35
@eVoloshchak 

```diff
diff --git a/src/libs/actions/Report.js b/src/libs/actions/Report.
js
index 164d0e60b..3d6799d26 100644
--- a/src/libs/actions/Report.js
+++ b/src/libs/actions/Report.js
@@ -887,6 +887,63 @@ function deleteReportComment(reportID, report
Action) {
     API.write('DeleteComment', parameters, {optimisticData, succe
ssData, failureData});
 }
 
+/**
+ * Extract all links in a markdown comment and returns them in a 
list.
+ *
+ * @param {String} comment
+ * @returns {Array}
+ */
+const extractLinksInComment = (comment) => {
+    const reg = /\[[^\[\]]*\]\(([^\(\)]*)\)/gm;
+    const links = [];
+    let link = reg.exec(comment);
+    while (link != null && link[1]) {
+        links.push(link[1]);
+        link = reg.exec(comment);
+    }
+    return links;
+};
+
+/**
+ * compares two markdown comments and return a list of the links 
removed in new comment.
+ *
+ * @param {String} oldComment
+ * @param {String} newComment
+ * @returns {Array}
+ */
+const getRemovedLinks = (oldComment, newComment) => {
+    const linksInOldComment = extractLinksInComment(oldComment);
+    const removedLinks = [];
+    linksInOldComment.forEach((link) => {
+        const markdownLink = `(${link})`;
+        if (oldComment.includes(markdownLink) && !newComment.incl
udes(markdownLink)) {
+            removedLinks.push(markdownLink);
+        }
+    });
+    return removedLinks;
+};
+
+/**
+ * removes links in a markdown comment.
+ * example: comment="test [link](https://www.google.com) test", l
ink=["(https://www.google.com)"]
+ * returns: "test link test"
+ * @param {String} comment
+ * @param {Array} links
+ * @returns {String}
+ */
+const removeLinks = (comment, links) => {
+    let commentCopy = comment.slice();
+    links.forEach((link) => {
+        const reg = new RegExp(`\\[([^\\[\\]]*)\\]\\(${link}\\)`,
 'gm');
+        const linkText = reg.exec(comment);
+        commentCopy = commentCopy.replace(link, '');
+        if (linkText && linkText[1]) {
+            commentCopy = commentCopy.replace(`[${linkText[1]}]`,
 linkText[1]);
+        }
+    });
+    return commentCopy;
+};
+
 /**
  * Saves a new message for a comment. Marks the comment as edited
, which will be reflected in the UI.
  *
@@ -896,10 +953,20 @@ function deleteReportComment(reportID, repor
tAction) {
  */
 function editReportComment(reportID, originalReportAction, textFo
rNewComment) {
     const parser = new ExpensiMark();
-
     // Do not autolink if someone explicitly tries to remove a li
nk from message.
     // https://github.com/Expensify/App/issues/9090
-    const htmlForNewComment = parser.replace(textForNewComment, {
filterRules: _.filter(_.pluck(parser.rules, 'name'), name => name 
!== 'autolink')});
+    
+    const htmlForNewCommentWithLinks = parser.replace(textForNewC
omment); // Will generate html and generate all links in comment.
+
+    // If user purposely removed a link while editing message. th
en remove it again.
+    const markdownForNewComment = parser.htmlToMarkdown(htmlForNe
wCommentWithLinks);
+    const markdownForOriginalComment = parser.htmlToMarkdown(orig
inalReportAction.message[0].html);
+
+    const linksRemovedInComment = getRemovedLinks(markdownForOrig
inalComment, textForNewComment);
+
+    const markdownAfterRemovingLinks = removeLinks(markdownForNew
Comment, linksRemovedInComment);
+
+    const htmlForNewComment = parser.replace(markdownAfterRemovin
gLinks, {filterRules: _.filter(_.pluck(parser.rules, 'name'), name
 => name !== 'autolink')});
 
     //  Delete the comment if it's empty
     if (_.isEmpty(htmlForNewComment)) {
@@ -920,7 +987,7 @@ function editReportComment(reportID, originalR
eportAction, textForNewComment) {
             message: [{
                 isEdited: true,
                 html: htmlForNewComment,
-                text: textForNewComment,
+                text: markdownAfterRemovingLinks,
                 type: originalReportAction.message[0].type,
             }],
         },
```

Result


https://user-images.githubusercontent.com/33489215/205737821-f637406a-8185-48f2-a775-cb99d75a132a.mp4

**Comment by cead22** [comment] 2022-12-06 21:49
This proposal looks very good. At first I thought this would be a magnet for edge cases we won't be able to anticipate, but when trying to find those edge cases and break this proposal, I wasn't very successful.

I found 2 odd behaviors
- Typing something like `[fb.com](fb.com)` has a different effect if you're editing the first time, or the second ![](http://g.recordit.co/xp9JkHPJhx.gif)
- If you have `fb.com google.com fb.com` and edit the comment to be `[google.com](https://google.com) [fb.com](https://fb.com) fb.com`, all urls are rendered as links ![](http://g.recordit.co/ijDwpOBXbD.gif)

**Comment by markarmanus** [comment] 2022-12-06 22:57
@cead22 I agree on the testing here as we should test very many edge cases. And yeah i definitely like extracting all logic relating to removing the links into its own function. we should just make sure we write enough comments to explain what is happening. So agreement on what you are saying there. 

lets wait on someone else to weight in but thank you for the feedback !

**Comment by cead22** [comment] 2022-12-06 23:02
I guess we can start getting thoughts from @eVoloshchak !

**Comment by eVoloshchak** [comment] 2022-12-07 20:44
@markarmanus, awesome!
It looks good and works well (at least during my initial testing), but I'll review this fully tomorrow (the change is quite big, don't want to miss something)

**Comment by strepanier03** [comment] 2022-12-09 18:35
@eVoloshchak - Any update here?

**Comment by eVoloshchak** [comment] 2022-12-09 18:37
@markarmanus's [proposal](https://github.com/Expensify/App/issues/13221#issuecomment-1338132072) looks good to me!
I've tested it and couldn't break it
The new functions can be simplified a bit, we should also use `_.forEach` from `underscore`, but the general idea is awesome
> Typing something like [fb.com](fb.com) has a different effect if you're editing the first time, or the second

That seems to be the expected result as far as I understand
If that is the case,
🎀👀🎀 C+ reviewed!

**Comment by markarmanus** [comment] 2022-12-09 19:23
@sandipanghos @eVoloshchak Thank you guys ! :D Just submited the proosal. let me know when i have the go ahead to create the PR !

**Comment by strepanier03** [comment] 2022-12-10 01:25
@cead22 @eVoloshchak - Just confirming we should hire @markarmanus, correct? It looks like it but I've jumped the gun before 😬

**Comment by cead22** [comment] 2022-12-12 18:23
@strepanier03 yes let's do it!

**Comment by strepanier03** [comment] 2022-12-13 01:50
Hired @markarmanus in Upwork as well. Feel free to apply @eVoloshchak - https://www.upwork.com/jobs/~01717a9143b77d9a7d

**Comment by markarmanus** [comment] 2022-12-13 04:03
PR is created @cead22 @eVoloshchak

**Comment by strepanier03** [comment] 2022-12-13 21:35
Confirmed on PR that discussion is happening and progress is being made. Will check again when I'm online tomorrow.

**Comment by eVoloshchak** [comment] 2022-12-15 09:35
The PR will probably be delayed due to an [issue](https://expensify.slack.com/archives/C01GTK53T8Q/p1670943366932199) with not being able to sign in on Web and mWeb

**Comment by strepanier03** [comment] 2022-12-16 01:03
Thank you for the update @eVoloshchak. I'll follow along.

**Comment by strepanier03** [comment] 2022-12-16 21:40
**Head's up**

I am out of the office starting December 17th and will return on January 3rd. During this time, if this GH needs action from a BugZero team member, please post in #expensify-open-source with a link to the GH to ask for some help.

Cheers! ☃️

**Comment by JmillsExpensify** [comment] 2022-12-23 17:21
I just noticed that the GH automation failed on this issue, as the linked PR hit production yesterday. I updated the issue as a result. I'll also assign myself to help out while @strepanier03 is OOO.

**Comment by eVoloshchak** [comment] 2022-12-26 18:30
Not overdue, PR hit production 4 days ago

**Comment by JmillsExpensify** [comment] 2022-12-27 02:08
Agreed. This isn't overdue. We'll circle back on regression steps and payment later this week.

**Comment by JmillsExpensify** [comment] 2022-12-31 18:10
Circling back for payment, it looks like we need to decide the following:

 - Does @markarmanus qualify for the three day bonus? All in all it took 4 days between putting the PR up for review and getting it merged, but I'd be curious to hear from @cead22 and @eVoloshchak whether some of that extra day was on our side or not.

**Comment by eVoloshchak** [comment] 2023-01-01 11:39
@JmillsExpensify, there was/is an [issue](https://expensify.slack.com/archives/C01GTK53T8Q/p1670943366932199) with not being able to log in on `Web` and `mWeb`, which has delayed @markarmanus as per their [comment](https://github.com/Expensify/App/pull/13551#issuecomment-1353418016):

> I cant seem to run the local web due to the issue you mentioend. are you aware of any work aroundts at this point ?

I've left a note about it [here](https://github.com/Expensify/App/issues/13221#issuecomment-1352787438)

**Comment by mallenexpensify** [comment] 2023-01-02 16:39
@markarmanus and @eVoloshchak both qualify for the bonus.  Thoughts/timeline below. 

@markarmanus - Paid $1500 
@eVoloshchak please accept job - https://www.upwork.com/jobs/~01717a9143b77d9a7d
@mdneyazahmad can you please accept the job and reply here once you have so I can pay you the reporting bonus - https://www.upwork.com/jobs/~01717a9143b77d9a7d 

- Hired on Dec 12th
- Merged on Dec 16th. 
- ALL kinds of IP issues going on during then, @eVoloshchak commented on Dec 15th, linking to the @here post in #expensify-open-source on Dec 13th.  
- > The PR will probably be delayed due to an [issue](https://expensify.slack.com/archives/C01GTK53T8Q/p1670943366932199) with not being able to sign in on Web and mWeb

**Comment by mdneyazahmad** [comment] 2023-01-02 17:03
@mallenexpensify applied.

**Comment by mallenexpensify** [comment] 2023-01-02 17:12
Hired @mdneyazahmad .  Once you and @eVoloshchak have accepted I'll pay both.

**Comment by markarmanus** [comment] 2023-01-03 13:00
Thank you guys for everything, pleasure doing work together.

**Comment by mallenexpensify** [comment] 2023-01-03 21:39
@eVoloshchak paid $1500 for C+ and timeliness bonus
@mdneyazahmad paid $250 for reporting

For the regression test steps update I'm thinking:
Update `Message Action menu - Edit Message (Online/Offline)` in Testral [here](https://expensify.testrail.io/index.php?/cases/view/1971024)

Online - add
7. Send a message with a link
8. Edit the message with the link
9. Verify the link is still hyperlinked. 

No updated needed for Offline cuz you can't edit nor delete a messaged.   Added [a feature request for delete in #expensify-open-source ](https://expensify.slack.com/archives/C01GTK53T8Q/p1672781242891829)

**Comment by JmillsExpensify** [comment] 2023-01-04 22:58
@mallenexpensify That test looks good. I'd create an issue for this one and assign it to Applause. Thanks for helping with payment!

**Comment by strepanier03** [comment] 2023-01-05 00:46
Thank you for helping while I was out of the office @JmillsExpensify and @mallenexpensify!

When it comes to the GH for the TR, would you like me to take that back over and make the GH @mallenexpensify?

**Comment by JmillsExpensify** [comment] 2023-01-11 05:29
Yes, I would take the regression test back over. Thank you! Let's get this one wrapped up.

**Comment by mallenexpensify** [comment] 2023-01-11 17:36
Sorry @strepanier03 , I somehow missed this. I've already got most of it done, finishing up meow

**Comment by mallenexpensify** [comment] 2023-01-11 17:41
Here's the checklist with the last item checked off @cead22 @eVoloshchak can you check off the top three? 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [x] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here: https://github.com/Expensify/Expensify/issues/254459

**Comment by strepanier03** [comment] 2023-01-13 21:40
@cead22 @eVoloshchak - Friendly bump on the checklist above. There are three items in the list that need your input. Thank you!

**Comment by cead22** [comment] 2023-01-13 23:26
Done, SO is down atm and it's my first time filling this out, so I welcome any feedback

**Comment by mallenexpensify** [comment] 2023-01-17 00:06
I think we're all good, thanks @cead22

**Closed by mallenexpensify** 2023-01-17 00:06 UTC
Labels: Reviewing, External, Daily, Bug
