### ISSUE TITLE
[$250]  IOS Hybrid - No image preview is shown in composer

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50839] opened 2024-10-15 21:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+en@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/50047
## Action Performed:
1. Open the Expenisfy Hybrid app
2. Sign into a valid account and access the ND features within the app
3. Open any chat room / page with Live Markdown input
4, Enter inline image markdown. For example: *test* ![demo image](https://picsum.photos/id/1067/200/300
)_test_

## Expected Result:
User expects to see an image preview in the composer

## Actual Result:
No image preview is seen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

![preview_in_composer_](https://github.com/user-attachments/assets/76020f53-f279-42a6-aefc-880499a24680)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847324912015488495</li>
        <li>Upwork Job ID: 1847324912015488495</li>
        <li>Last Price Increase: 2024-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dukenv0307</details>

**Comment by lanitochka17** [comment] 2024-10-15 21:28
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VickyStash** [comment] 2024-10-21 14:32
@isabelastisser It looks like the inline images preview was implemented on the web platforms only, it's mentioned in the [PR](https://github.com/Expensify/App/pull/50047).
This ticket reports a problem on iOS native, where this functionality is not supported I believe. So I'm not sure if it's a bug.
cc @Skalakid since he is the author of the initial PR.

**Comment by isabelastisser** [comment] 2024-10-22 18:17
Bump @dukenv0307. I DM'd you for visibility. Thanks!

**Comment by Skalakid** [comment] 2024-10-23 07:37
Sorry, I missed the notification about this issue. As @VickyStash said, the inline image features are implemented for the web only for now. So it's not a bug. We are still working on adding this feature to native platforms

**Comment by isabelastisser** [comment] 2024-10-25 18:22
Thanks for clarifying, @Skalakid1 Closing.

**Closed by isabelastisser** 2024-10-25 18:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
