### ISSUE TITLE
App crashes when attempting to open an #admins room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44583] opened 2024-06-28 00:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @francoisl 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719528213578329

## Action Performed:
1. Create a workspace
2. Open the workspace's settings page and change anything that would cause a system message in the admins room
For example, create, delete, rename or disable a category ; add tags, etc.
3. Try to open the admins room for that workspace
## Expected Result:
Workspace Admin room opens
## Actual Result:
App crashes when opening admin room

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e07e4060-8a43-4293-988a-72735763cca0

https://github.com/Expensify/App/assets/38435837/7746a3c8-93b2-4316-8299-0e0d6fd7e39a

https://github.com/Expensify/App/assets/38435837/88cd1457-3005-4f91-ac8e-f0e05d286507

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neonbhai** [comment] 2024-06-28 00:22
Fixed on latest main:

https://github.com/Expensify/App/assets/64629613/ff8fdf09-cb8e-426f-9a40-16c3a0b8b983

**Comment by robertjchen** [comment] 2024-06-28 03:58
got it, thanks!

**Comment by mountiny** [comment] 2024-06-28 08:23
@neonbhai Sorry to confirm, you mentioned its fixed on main, but is it fixed on staging?

**Comment by neonbhai** [comment] 2024-06-28 09:04
@mountiny hi, cannot reproduce on staging:

https://github.com/Expensify/App/assets/64629613/2f0fd0b0-60d4-4aa9-954e-7831e2347461

**Comment by m-natarajan** [comment] 2024-06-28 09:45
@mountiny we are still able to reproduce this bug and clicking on the WS right after creating the WS also crashes the app.

https://github.com/Expensify/App/assets/38435837/0671c6e8-7101-41fa-9c96-d5037a9352b7

**Comment by mountiny** [comment] 2024-06-28 11:16
@neonbhai can you try in offline? maybe its issue with optimistic data

**Comment by neonbhai** [comment] 2024-06-28 11:56
I can reproduce the crash when creating a workspace -> changing name -> switching to it from workspace switcher:


https://github.com/Expensify/App/assets/64629613/69acc422-ea5a-4f21-a6e7-20232304fc67


The console error is for maximum update depth exceeded. [Ref link](https://react.dev/errors/185?invariant=185)

<img width="552" alt="Screenshot 2024-06-28 at 5 25 48 PM" src="https://github.com/Expensify/App/assets/64629613/4abc0118-c2b4-46ad-a7b3-ca9b73e349f8">



Crash doesn't reproduce for me for the system message steps (both online and offline):

<Details><Summary>Attempt 1 (offline)</Summary>

https://github.com/Expensify/App/assets/64629613/ba77f7b9-f30b-473a-8afe-a0f12aebb245

Aside: We don't set an optimistic system message for toggling of category/tags
</Details>



<Details><Summary>Attempt 2 (online)</Summary>

https://github.com/Expensify/App/assets/64629613/846f4b8b-ea9d-4929-bb88-6cae8dabd56c


</Details>

cc: @mountiny

**Comment by robertjchen** [comment] 2024-07-01 09:12
Was this a regression from a recent change? 👀

**Comment by neonbhai** [comment] 2024-07-01 20:35
Looks like its coming from the [ReportScreen](https://github.com/Expensify/App/blob/81abfeca6697ee1f2cda38f960a0d913ee62856b/src/pages/home/ReportScreen.tsx) component:
<img width="1680" alt="Screenshot 2024-07-02 at 2 02 22 AM" src="https://github.com/Expensify/App/assets/64629613/7c02802c-699a-4ddb-956f-11cb3dd86697">

**Comment by jasperhuangg** [comment] 2024-07-01 20:47
At first glance this seems suspicious: https://github.com/Expensify/App/pull/44412

**Comment by jasperhuangg** [comment] 2024-07-01 21:23
https://github.com/Expensify/App/pull/44412 is not the cause :/

**Comment by jasperhuangg** [comment] 2024-07-01 21:37
The issue has either something to do with:
the optimistic data set when we call UpdateWorkspaceGeneralSettings
Something about how the workspace switcher works
Something about how the ReportScreen works

**Comment by jasperhuangg** [comment] 2024-07-01 22:27
I can't seem to reproduce this on desktop

**Comment by jasperhuangg** [comment] 2024-07-01 22:32
> I can reproduce the crash when creating a workspace -> changing name -> switching to it from workspace switcher:
> 
>  Screen.Recording.2024-06-28.at.5.01.28.PM.mov 
> The console error is for maximum update depth exceeded. [Ref link](https://react.dev/errors/185?invariant=185)
> 
> <img alt="Screenshot 2024-06-28 at 5 25 48 PM" width="552" src="https://private-user-images.githubusercontent.com/64629613/344152008-4abc0118-c2b4-46ad-a7b3-ca9b73e349f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzIxNDUsIm5iZiI6MTcxOTg3MTg0NSwicGF0aCI6Ii82NDYyOTYxMy8zNDQxNTIwMDgtNGFiYzAxMTgtYzJiNC00NmFkLWE3YjMtY2E5YjczZTM0OWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIyMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNTg4NTFmNjc3YzM3OGFjNDIyYTg3NTc3MzgyOWRiNmIxZjg3ZGMyZjc1ZmNlZjUxN2FkODIzYWMxYzYwM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5THfekIsSCm4hEiXerB301Iu7y9UvuFOi0DukgxXWQ8">
> Crash doesn't reproduce for me for the system message steps (both online and offline):
> 
> Attempt 1 (offline)
> Attempt 2 (online)
> cc: @mountiny

@neonbhai I can't seem to reproduce this at all anymore when following these steps 🤔

**Comment by jasperhuangg** [comment] 2024-07-01 23:12
I think this is the cause https://github.com/Expensify/App/pull/44559

Namely the code that calls `getSnapshot` [here](https://github.com/Expensify/App/pull/44559/files#diff-2246ab765bae28627206ca058e4698a59ce2a1cf52c31ce04a45c7a8e8081548R131-R143) cc @roryabraham 

Can reproduce this consistently with my account on staging with the following steps:
1. Sign into any account
2. Create a new workspace.
3. Rename that workspace.
4. In the workspace list, click the three dots and click "Go to #admins room".

**Comment by robertjchen** [comment] 2024-07-01 23:17
@jasperhuangg Awesome investigation! 🙇

**Comment by jasperhuangg** [comment] 2024-07-01 23:18
@robertjchen @roryabraham Still looking into this, it's either caused by https://github.com/Expensify/App/pull/44412 or https://github.com/Expensify/App/pull/44559, or a combination of the two 😆 I'm trying every possible combination now.

**Comment by jasperhuangg** [comment] 2024-07-01 23:20
Okay yep confirmed it's caused by https://github.com/Expensify/App/pull/44412, reverting that fixes things for me locally

**Comment by jasperhuangg** [comment] 2024-07-01 23:20
Looks like @roryabraham is OOO today so in the interest of pushing deploy forward I'm gonna go ahead and revert that PR

**Comment by jasperhuangg** [comment] 2024-07-01 23:21
<img width="538" alt="Screenshot 2024-07-01 at 4 21 24 PM" src="https://github.com/Expensify/App/assets/31285285/1788c6e5-d767-494e-b7e3-230a25e9a334">


btw @roryabraham here's the error

**Comment by roryabraham** [comment] 2024-07-01 23:24
Reverting that PR will cause another regression @jasperhuangg

**Comment by roryabraham** [comment] 2024-07-01 23:28
@jasperhuangg can you try this PR and see if it solves the problem?

https://github.com/Expensify/App/pull/44681

**Comment by roryabraham** [comment] 2024-07-01 23:31
If it does, you could actually take it a step further and just remove the `useLastAccessedReportID` hook and put `findLastAccessedReport` in a `useEffect` directly

**Comment by neonbhai** [comment] 2024-07-01 23:34
Came across very similar warning to https://github.com/Expensify/App/issues/44583#issuecomment-2201379355  on native device, asking to memoize getSnapshot call in [useOnyx](https://github.com/Expensify/react-native-onyx/blob/55a2b69f13ab26399a52cda160325ca31ef0aedf/lib/useOnyx.ts)

<Details><Summary>Image</Summary>
<img width="427" alt="Screenshot 2024-07-01 at 1 44 12 AM" src="https://github.com/Expensify/App/assets/64629613/58944004-3e42-4ac0-a3cd-eadd4107b838">


</Details>

**Comment by jasperhuangg** [comment] 2024-07-01 23:48
Ah shoot @roryabraham jumped the gun and missed your messages, my bad! The CP is already under way and it looks like that PR you linked is still an early draft–do you mind if we try to get it out in tomorrow's deploy?

**Comment by jasperhuangg** [comment] 2024-07-02 00:21
Can't reproduce this anymore on staging

**Closed by jasperhuangg** 2024-07-02 00:21 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
