### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] Chat - App crashes when edit comment clicked for mark down message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20847] opened 2023-06-15 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20336
## Action Performed:
1. Login with any account
2. Open a report
3. Send a markdown message e.g google.com
4. Clicking on reply in thread of this message
5. Verify that thread title display as the text of the message
6. Edit the message

## Expected Result:
Verify that thread title still display as the text of the message instead of the markdown of the message

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/d4abc7cb-2977-4e6b-823b-268c7bf41f43

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115b4eacb891784a9</li>
        <li>Upwork Job ID: 1669642999913762816</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-06-16 10:43
@dukenv0307 ere you bale to find the PR which introduced this?

**Comment by mountiny** [comment] 2023-06-16 12:25
@fedirjh let us know what you think of the proposasl, thanks

**Comment by mountiny** [comment] 2023-06-16 13:21
Thanks, what about the proposal of @dukenv0307 then?

**Comment by bernhardoj** [comment] 2023-06-16 13:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Crash when edit a message after coming back from another chat

### What is the root cause of that problem?
It has the same root cause with this issue https://github.com/Expensify/App/issues/20513 I worked on previously (here is the [proposal](https://github.com/Expensify/App/issues/20513#issuecomment-1585557736)).

So, we have a global ref for the message list. 
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/ReportScrollManager/index.js#L3-L5
and is set in ReportActionsList
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/home/report/ReportActionsList.js#L152-L155

When we close a chat, that ref will become null. It's not a regression from https://github.com/Expensify/App/pull/20296 but from the new navigation. This doesn't happen before because report screen is always mounted.

### What changes do you think we should make in order to solve the problem?

I would suggest to use the same solution. 
1. Use a context to share the ref. In https://github.com/Expensify/App/issues/20513, we added a context specifically for reaction list only, but I think we can start to move the context to ReportScreen. The context will contains for both reaction list ref and flat list ref.
2. Modify ReportScrollManager. Remove the global ref and modify the function to accept a ref instead.
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/ReportScrollManager/index.js#L14
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/ReportScrollManager/index.js#L26

ReportScrollManager is also being used in MoneyRequestModal too which is a separate page from ReportScreen.
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/iou/MoneyRequestModal.js#L398-L405

It will scroll to bottom when we do a money request. As we are removing the global ref, we need a way to have the same behavior with the local ref. To achieve this, we can use the same approach of scrolling to bottom when we add a new message. In ReportActionsView, we have a listener that will scroll to bottom when a new action is added from the current user:
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/home/report/ReportActionsView.js#L102-L111

When we add a new action, we will trigger the listener here
https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/libs/actions/Report.js#L299-L305

So, here is what we need to do:
1. Move the logic to a function (`notifyNewAction`) and export it
2. Use the new function in IOU `requestMoney`, `sendMoneyElsewhere`, etc.

This issue could potentially happens to all global ref.

**Comment by mountiny** [comment] 2023-06-16 13:48
that would be a separate issue

**Comment by bernhardoj** [comment] 2023-06-16 14:13
@fedirjh sorry, which part exactly do you wondering whether it's possible to use hooks or not?

**Comment by bernhardoj** [comment] 2023-06-16 14:39
I guess that would work, we will create 2 useReportScrollManager, index.js and index.native.js.

**Comment by bernhardoj** [comment] 2023-06-16 14:47
The first chat is never unmounted, so the ref stays null when going back to the first chat.

**Comment by bernhardoj** [comment] 2023-06-16 15:39
> So for first chat it should be re-rendered for the ref to be reset

I don't think ref will re-reset when the component is re-rendered, except when we use a callback ref with inline function.
https://legacy.reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs

> We should handle all cases of ReportScrollManager
I mean the other global ref like emoji picker

**Comment by bernhardoj** [comment] 2023-06-17 04:01
Yes, tested on all platforms.

Btw, there are still some components that still in a class component, so I don't think we can use hooks for now?

**Comment by dylanexpensify** [comment] 2023-06-19 08:35
@fedirjh curious for your thoughts on this ^ when you get a chance today! 🙇‍♂️

**Comment by bernhardoj** [comment] 2023-06-20 03:07
Hmm, I honestly don't like leaving a comment reminding people to migrate it to hook 😅.

**Comment by bernhardoj** [comment] 2023-06-20 14:24
Sooo, what should we do here? 😄. I guess we need another vote to push this forward? My previous comment is just a personal preference, so I'm up to any decision.

**Comment by amyevans** [comment] 2023-06-21 14:31
> there are still some class components that need the changes

Can you list out which components these are? Is it just `<ReportActionsView />`? Perhaps we can comment on the migration GH tracking issue(s) for added reminder/visibility.

+1 to preferring hooks over HOC though.

**Comment by bernhardoj** [comment] 2023-06-21 16:54
PR is ready for review.

> Perhaps we can comment on the migration GH tracking issue(s) for added reminder/visibility.

Should I add a comment there now or after the PR is merged?

**Comment by bernhardoj** [comment] 2023-06-27 05:00
> After the PR is merged sounds best

Added the hook migration comment here https://github.com/Expensify/App/issues/16267#issuecomment-1608797896

**Comment by dylanexpensify** [comment] 2023-07-07 08:39
Nice! Will get payments today, @fedirjh will you work on list?

**Comment by dylanexpensify** [comment] 2023-07-17 09:14
ty @bernhardoj! Will pay out today!

**Comment by dylanexpensify** [comment] 2023-07-20 08:31
@bernhardoj offer sent!

**Comment by dylanexpensify** [comment] 2023-07-20 08:48
@fedirjh you're paid via ND, right?

**Comment by dylanexpensify** [comment] 2023-07-24 08:50
Sorry y'all missed the window before job closed, @fedirjh mind applying [here](https://www.upwork.com/jobs/~0151f241203c753027)

**Comment by dylanexpensify** [comment] 2023-07-24 09:32
Offfer sent!

**Comment by dylanexpensify** [comment] 2023-07-24 10:17
payment sent, thanks @fedirjh!!

**Comment by dylanexpensify** [comment] 2023-07-24 10:52
done!

**Closed by dylanexpensify** 2023-07-24 10:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
