### ISSUE TITLE
OpenApp fail/partially fails for Jason's heavy approver account on a throttled connection

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#47093] opened 2024-08-08 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1723132613137659?thread_ts=1722970682.900369&cid=C05LX9D6E07

## Action Performed:
Break down in numbered steps

Use an account that approves a lot of reports (@JmillsExpensify's account)
Go to new.expensify.com
Open the Network console and enable 3G throttling
Log in

## Expected Result:
Describe what you think should've happened

OpenApp completes successfully and all data is visible in Jason's account

## Actual Result:
Describe what actually happened

The app shows a partially loaded state, or nothing is loaded at all

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Using clear cache and restart in the Troubleshoot menu loads the data on a second try

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johncschuster** [comment] 2024-08-08 21:45
Oh! This is new! Thanks for the SO, Matt! I'll dig into this proper in the AM.

**Comment by johncschuster** [comment] 2024-08-12 21:51
Sorry I haven't gotten to dive into this yet. I've got it on my plate first thing tomorrow.

**Comment by francoisl** [comment] 2024-08-14 17:51
Matt's last update in Slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1723455337826899) mentioned that Eduardo from Callstack started investigating this one, should we co-assign?

**Comment by muttmuure** [comment] 2024-08-14 19:57
@gedu please could you comment so we can assign you?

**Comment by johncschuster** [comment] 2024-08-16 20:40
Bumped in Slack 👍

**Comment by gedu** [comment] 2024-08-17 08:47
Hi, I’m Edu from  Callstack, I can take a look at this issue

**Comment by johncschuster** [comment] 2024-08-19 21:43
Not overdue. This was just assigned.

**Comment by johncschuster** [comment] 2024-08-22 21:43
@gedu how's this going?

**Comment by gedu** [comment] 2024-08-23 08:07
Hey, I found later yesterday, using a slow 4G (on 3G it takes at least 7 - 10 min to "load" the app and then crash), seems like the server didn't sent me reports:
```
31: key: "report_"onyxMethod: "mergecollection"value: [] 
```
That was the from the ReconnectApp, so my user ended up with no reports, still looking into this, but seems that could be an issue on the server (?)

**Comment by gedu** [comment] 2024-08-26 12:59
Discussing about [`StrictMode`](https://react.dev/reference/react/StrictMode) on slack

**Comment by johncschuster** [comment] 2024-08-28 19:35
Discussion is ongoing in Slack (I've updated the links above to link to both Callstack and Expensify's instances of Slack)

**Comment by johncschuster** [comment] 2024-09-03 21:12
Discussion in Slack is ongoing (looks like we might be nearing the end 🤞)

**Comment by johncschuster** [comment] 2024-09-06 21:11
Ok! It looks like the conversation has come to a conclusion and @gedu should be back to this at the start of next week 🙌

**Comment by johncschuster** [comment] 2024-09-09 22:14
Bumping for Melv

**Comment by muttmuure** [comment] 2024-09-17 18:09
PR is where the action is happeninghttps://github.com/Expensify/App/pull/47913

**Comment by johncschuster** [comment] 2024-09-17 21:09
Awesome. Thanks, @muttmuure! I'll keep my eyes peeled there for updates

**Comment by johncschuster** [comment] 2024-09-20 22:37
@gedu is still working on this. Not overdue!

**Comment by johncschuster** [comment] 2024-09-24 21:45
Not overdue. @gedu is regularly working on this (updates in the PR)

**Comment by francoisl** [comment] 2024-09-30 18:03
Not overdue, the PR is still being actively worked on.

**Comment by johncschuster** [comment] 2024-10-02 20:52
Still not overdue. Steady progress is being made in the PR

**Comment by mountiny** [comment] 2024-10-07 13:04
Not on hold anymore the dedupe PR was merged

**Comment by johncschuster** [comment] 2024-10-07 21:35
Thanks, @mountiny!

**Comment by mountiny** [comment] 2024-10-08 12:56
@gedu what are the next steps on this one, do we need to de-dupe the OpenApp?

**Comment by johncschuster** [comment] 2024-10-11 20:49
@gedu bump on the above!

**Comment by mountiny** [comment] 2024-10-14 04:43
We actually merged this PR https://github.com/Expensify/App/pull/50258 which dedupes the OpenApp so we should be better to test this one again soon

**Comment by gedu** [comment] 2024-10-14 06:27
Hey, sorry, I don't think there's a specific fix for this one. There were multiple requests failing and some internal errors. Is it still reproducible? Can we get some steps?

**Closed** 2024-10-14 11:52 UTC
Labels: Daily, Bug, AutoAssignerNewDotQuality

**Comment by JmillsExpensify** [comment] 2024-10-14 22:07
Sounds good to me!
