### ISSUE TITLE
[HOLD for payment 2024-02-07] [$125] Teachers Unite - The character input is limited

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35144] opened 2024-01-25 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #34502 
**Version Number:** 1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Log in as a new expensifail user
2. Tap on FAB - Save the world - I am a teacher
3. Type in "Ádám" in the name field
## Expected Result:
I should be able to input characters that the profile display name accepts.

## Actual Result:
The character input is limited, it only accepts Latin characters. I can input the same text as my profile display name without problems.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/bfd8b0cb-d332-4f9f-8d36-84fbc7d912d0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149b1c044231d033c</li>
        <li>Upwork Job ID: 1750500293635174400</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 28122476</li>
<li>paultsimura | Contributor | 28122477</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-25 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Teacher's name doesn't allow accented chard.

### What is the root cause of that problem?
We use the `isValidLegalName` validation that doesn't allow accented symbols:

https://github.com/Expensify/App/blob/eb988f3b47f921fdf464bc137d897b46a92c3582/src/pages/TeachersUnite/IntroSchoolPrincipalPage.tsx#L57-L66

### What changes do you think we should make in order to solve the problem?
We should use either `isValidDisplayName`, or build a new validation to check only for:

```js
CONST.REGEX.ALPHABETIC_AND_LATIN_CHARS.test(name)
```



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-26 09:54
Thanks. The PR is ready for review: https://github.com/Expensify/App/pull/35229

I've added a grammatical correction to the copies in this PR. Requested confirmation [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1706260058994859).

**Comment by greg-schroeder** [comment] 2024-01-26 19:00
Merged, awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2024-02-06 22:29
All right, looks like we're ready to go for payment tomorrow, 2/7. Offers are accepted.

**Closed** 2024-02-07 18:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
