### ISSUE TITLE
[HOLD for payment 2023-10-24] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] Smart scanning header is broken

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29626] opened 2023-10-14 19:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Click the `+` action button and request money
2. Select Scan
3. Upload receipt as part of the Scan flow and complete the process
4. Open the uploaded receipt

## Expected Result:
Smart scanning header is visible

## Actual Result:
Smart scanning header is broken

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/459fac93-c89c-4655-893f-e5d98ba8cd08

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment] 2023-10-14 19:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split details receipt scan header is broken

### What is the root cause of that problem?
In the SplitDetailsPage.js <MoneyRequestHeaderStatusBar is called without any arguments 

```js
{isScanning && <MoneyRequestHeaderStatusBar />}
```


### What changes do you think we should make in order to solve the problem?
Update the SplitDetailsPage.js to call with the required arguments `<MoneyRequestHeaderStatusBar />` similar to what's being done in `MoneyRequestHeader.js`

```js
                    {isScanning && <MoneyRequestHeaderStatusBar 
                     title={translate('iou.receiptStatusTitle')}
                     description={translate('iou.receiptStatusText')}
                     shouldShowBorderBottom
                    />}
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by shubham1206agra** [comment] 2023-10-15 06:06
Offending PR https://github.com/Expensify/App/pull/29201

**Comment by mountiny** [comment] 2023-10-15 21:05
cc @grgia

**Comment by mountiny** [comment] 2023-10-16 12:47
<img width="1124" alt="image" src="https://github.com/Expensify/App/assets/36083550/a1235421-3ffc-4e8d-af0e-e6a2306d397a">
fixed

**Comment by mountiny** [comment] 2023-10-16 12:47
@rushatgabhane will get $500 for internal review

**Comment by kbecciv** [comment] 2023-10-16 16:14
@mountiny Issue is reproducible for me on Windows/Chrome, build 1.3.84.7

https://github.com/Expensify/App/assets/93399543/50fc6361-4ee7-403f-a03a-e80e8c8cf04a

**Comment by mountiny** [comment] 2023-10-16 21:07
Ah that is different place, we only fixed it in the request header, looking

**Comment by mountiny** [comment] 2023-10-16 21:17
I believe this is fixed now by https://github.com/Expensify/App/pull/29568/files

**Comment by joekaufmanexpensify** [comment] 2023-10-23 13:27
I see @rushatgabhane was [actually already paid](https://github.com/Expensify/App/pull/29659#issuecomment-1769178315) for this one on the PR.

**Comment by joekaufmanexpensify** [comment] 2023-10-23 13:28
@rushatgabhane please complete your portion of the BZ checklist when you have a sec, and then we'll be all set to close this out!

**Comment by joekaufmanexpensify** [comment] 2023-10-24 20:20
Pending completion of checklist

**Comment by joekaufmanexpensify** [comment] 2023-10-25 14:10
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1698243016206069)

**Comment by joekaufmanexpensify** [comment] 2023-10-26 14:28
Still pending completion

**Comment by joekaufmanexpensify** [comment] 2023-10-30 13:49
Not overdue. @rushatgabhane is anything needed for BZ checklist here?

**Comment by joekaufmanexpensify** [comment] 2023-10-31 17:30
Bumped in Slack

**Comment by joekaufmanexpensify** [comment] 2023-11-03 13:52
Sweet, TY! BZ checklist is all set. Payment was already issued on the PR, so closing as this one is good to go.

**Closed by joekaufmanexpensify** 2023-11-03 13:52 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
