### ISSUE TITLE
[HOLD for payment 2024-01-05] [HOLD for payment 2024-01-04] [$250] LHN chat row has large spacing

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#33647] opened 2023-12-27 16:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.18-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Open App
2. Have most recent mode activated

## Expected Result:
Describe what you think should've happened

The LHN chat preview spacing is as in production

## Actual Result:
Describe what actually happened

There is more spacing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

staging
<img width="366" alt="image" src="https://github.com/Expensify/App/assets/36083550/9883e335-9c4b-402e-9943-52289390c2a4">

prod
<img width="385" alt="image" src="https://github.com/Expensify/App/assets/36083550/b623774e-0189-4dd2-8551-419912cc9641">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191d08fb26ea68646</li>
        <li>Upwork Job ID: 1740045553562488832</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 28070977</li>
<li>abzokhattab | Contributor | 28070978</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-12-27 16:26
@mountiny Is this only reproducible for desktop? The spacing on web looks correct:

![image](https://github.com/Expensify/App/assets/1228807/4bd363e0-86cd-4cc5-8040-0cec8d54abf7)

**Comment by mountiny** [comment] 2023-12-27 16:26
@tgolen Ah must be most recent mode

**Comment by tgolen** [comment] 2023-12-27 16:27
Ah yes, I see it now in most recent mode.

**Comment by situchan** [comment] 2023-12-27 16:35
confirmed regression from #32818

**Comment by tgolen** [comment] 2023-12-27 16:49
[The proposal](https://github.com/Expensify/App/issues/33647#issuecomment-1870465517) looks correct to me and I tested it out. Assigning to @abzokhattab to create a PR to fix it.

**Comment by situchan** [comment] 2023-12-27 16:52
Let's make sure that reverting changes doesn't cause regression of https://github.com/Expensify/App/issues/26044.

**Comment by tgolen** [comment] 2023-12-27 17:01
Yeah, I tested that out as well and it doesn't look like it causes any regression.

**Comment by tgolen** [comment] 2023-12-27 20:09
@abzokhattab are you working on a PR? Since this is a deploy blocker, it is extremely urgent. If you cannot get to a PR, I will create one in about an hour.

**Comment by mountiny** [comment] 2023-12-28 18:34
Fixed, thanks everyone

**Comment by bfitzexpensify** [comment] 2024-01-05 17:13
Payments complete, @getusha please complete the BZ checklist - thanks!

**Comment by getusha** [comment] 2024-01-05 20:34
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x]  [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32818
- [x]  [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32818/files#r1443344823
- [x] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
- [x] [@getusha] Determine if we should create a regression test for this bug. **No, this is a minor visual bug which will not affect any user flow.**
- [x] [@getusha] If we decide to create a [regression test] (https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by bfitzexpensify** [comment] 2024-01-08 13:05
Thanks @getusha - looks like we're all done here and can close this one out.

**Closed by bfitzexpensify** 2024-01-08 13:05 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
