### ISSUE TITLE
 Send invoice - Workspace avatar and name are incorrect after paying invoice as a business

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44806] opened 2024-07-04 05:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #43036
**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User A and User B have their own workspaces.

1. Go to staging.new.expensify.com
2. [User A] Send invoice to User B.
3. [User B] Go to invoice chat.
4. [User B] Click on the pay button > Pay as a business > Pay elsewhere.
5. [User B] After invoice chat avatar is changed, click on the chat header.
6. [User B] Click on User B's workspace avatar.

## Expected Result:
User B's workspace avatar will be displayed with the correct workspace name.

## Actual Result:
User B's workspace avatar is displayed as User A's workspace avatar together with User A's workspace name

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/452de192-b994-4f75-a086-fc9a8342256b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-04 05:04
@Beamanator FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-04 05:04
We think that this bug might be related to  #vip-vsb

**Comment by Beamanator** [comment] 2024-07-04 09:00
cc @cristipaval since you're the "Invoices in NewDot" guy!

**Comment by Beamanator** [comment] 2024-07-04 09:04
Marking NAB b/c of @cristipaval 's comment in the PR [here](https://github.com/Expensify/App/pull/43036#issuecomment-2206014678). Keeping this open till we determine if it's needed or if we're going to handle this case in the issue linked to that PR

**Comment by Beamanator** [comment] 2024-07-04 09:05
Also commented in #vip-billpay [here](https://expensify.slack.com/archives/CSL3XBCCR/p1719883066251329)

**Comment by VickyStash** [comment] 2024-07-08 14:32
I was able to reproduce this issue, and I'm going to fix it in the [upcoming PR ](https://github.com/Expensify/App/pull/44970) related to Pay as business functionality.
cc @cristipaval

**Comment by JmillsExpensify** [comment] 2024-07-10 04:29
Ah perfect, we'll keep an eye on that one.

**Comment by cristipaval** [comment] 2024-07-12 21:10
This is held.

**Comment by cristipaval** [comment] 2024-07-12 21:11
Actually, I think we can close this one, given that it was reproducible due to a PR that was reverted.

**Closed by cristipaval** 2024-07-12 21:11 UTC
Labels: Engineering, Daily, Bug
