### ISSUE TITLE
[$1000] Web - Error message  "Uh-oh, something went wrong!" when trying to access a workspace member's URL while logged into a different account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23814] opened 2023-07-28 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Connect with user A
2. Create a workspace
3. Copy the members' URL of the workspace
4. Connect with user B
5. Past the URL
6. Observe "Uh-oh, something went wrong!"

## Expected Result:
"Hmm... it's not here" screen should appear

## Actual Result:
"Uh-oh, something went wrong!"  screen appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[member-url.webm](https://github.com/Expensify/App/assets/93399543/8e8535c4-1b71-4c67-87ce-92b2126e6718)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690540270820769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c0477dc8cdb9db7</li>
        <li>Upwork Job ID: 1686459517550612480</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Contributor | 26055047</li>
</ul></li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-07-28 18:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message "Uh-oh, something went wrong!" when trying to access a workspace member's URL while logged into a different account

### What is the root cause of that problem?
In case of user not having access to policy.  As we can see in screenshot below, we are getting policy as `null`.
<img width="768" alt="Screenshot 2023-07-29 at 12 00 28 AM" src="https://github.com/Expensify/App/assets/27822551/221d5cdd-c71f-4f55-b455-8413ad8c863e">

Because the user is not member of workspace/policy.
And as policy is being passed as empty object/null and we are trying to apply function on undefined .
<img width="450" alt="Screenshot 2023-07-28 at 11 57 11 PM" src="https://github.com/Expensify/App/assets/27822551/85bcb949-ead0-4a1c-a2e8-8f227c288e5d">


### What changes do you think we should make in order to solve the problem?
We shall render the `FullPageNotFoundView` in `withPolicyAndFullscreenLoading`
The condition will be - 
```
        if(!props.isLoadingReportData && _.isEmpty(props.policy)){
            return <FullPageNotFoundView shouldShow/>
        }
```

- with `!props.isLoadingReportData` we are making sure the request has completed
- with `_.isEmpty(props.policy)` we check if policy is empty/null

And based on that we are showing `<FullPageNotFoundView/>`

Result - 

https://github.com/Expensify/App/assets/27822551/1bab116b-07e5-4266-b419-ea9ce4b3ee47



### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-07-28 19:20
@kbecciv I was able to reproduce this issue.

**Comment by kbecciv** [comment] 2023-07-28 20:43
Great, thank you!

**Comment by kevinksullivan** [comment] 2023-08-01 19:30
Also reproduced

**Comment by kevinksullivan** [comment] 2023-08-01 19:56
Not overdue

**Comment by rushatgabhane** [comment] 2023-08-02 04:22
>  if(!props.isLoadingReportData && _.isEmpty(props.policy)){

@BhuvaneshPatil i don't think we need this condition because we already handled it here - 

https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/pages/workspace/WorkspaceMembersPage.js#L407-L408

How about we take care of `null` values of `policy` in all related function, so that crash doesn't happen?

**Comment by BhuvaneshPatil** [comment] 2023-08-02 05:35
@rushatgabhane

I tried adding that check to validateSelection function (in the useCallback), and it handled the error.

**Comment by Pujan92** [comment] 2023-08-02 07:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when new user directly access any policy members page

### What is the root cause of that problem?
Here for the finding the `ownerAccountID` we are passing the `undefined` as that policy details won't be existed for that user. That leads to the error because within the `getAccountIDsByLogins` function, we are applying `toLowerCase` to generate AccountID for the passed text which fails to execute on `undefined`.

https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/pages/workspace/WorkspaceMembersPage.js#L96

https://github.com/Expensify/App/blob/6a383413758030d687a728f66b19b00eadab7f3c/src/libs/UserUtils.js#L214-L216

<img width="1440" alt="Screenshot 2023-08-02 at 12 37 05 PM" src="https://github.com/Expensify/App/assets/14358475/e04dad08-6172-4a6b-bd27-1e8e4ab9985b">

### What changes do you think we should make in order to solve the problem?
We need to pass an empty string when the policy or policy owner is not available.
```
const ownerAccountID = _.first(PersonalDetailsUtils.getAccountIDsByLogins([props.policy.owner || '']));
```

**Comment by rushatgabhane** [comment] 2023-08-02 08:17
https://github.com/Expensify/App/issues/23814#issuecomment-1661627752

@Pujan92 's proposal looks good to me 
🎀 👀 🎀

**Comment by kevinksullivan** [comment] 2023-08-04 21:27
Hey @alexpensify I am going OOO for a week, so tapping you in to help out in the interim. Thanks!

**Comment by alexpensify** [comment] 2023-08-05 00:29
Ok, it looks like we need @joelbettner to approve here.

**Comment by alexpensify** [comment] 2023-08-06 16:56
Still waiting for approval here.

**Comment by alexpensify** [comment] 2023-08-08 23:18
I reached out to Joel for an update.

**Comment by alexpensify** [comment] 2023-08-10 16:57
@thienlnam - Joel is OOO, I'm reassigning to approve the proposal below and we can get this one assigned out. Thanks! 

https://github.com/Expensify/App/issues/23814#issuecomment-1661726753

**Comment by hichamcc** [comment] 2023-08-10 19:18
Done

**Comment by Pujan92** [comment] 2023-08-11 19:26
@rushatgabhane [PR](https://github.com/Expensify/App/pull/24457) is ready for review!

**Comment by alexpensify** [comment] 2023-08-12 16:20
@Pujan92 thank you for the update!

**Comment by alexpensify** [comment] 2023-08-16 23:52
It looks like the PR is still under review

**Comment by alexpensify** [comment] 2023-08-18 21:39
The PR is still moving along.

**Comment by kevinksullivan** [comment] 2023-08-21 21:56
@alexpensify thanks for stepping in! I am back so I can manage the payouts, but will keep you assigned for credit.

**Comment by Pujan92** [comment] 2023-08-23 12:09
@kevinksullivan @alexpensify Seems some other [PR](https://github.com/Expensify/App/pull/24457) resolved the issue before my PR got merged. In this case, I need to close my PR based on https://github.com/Expensify/App/pull/24457#issuecomment-1689260787

**Comment by kevinksullivan** [comment] 2023-08-24 22:41
Thanks @Pujan92 . Checking on our process for these in [slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1692916841973759)

**Comment by kevinksullivan** [comment] 2023-08-24 23:05
Payment made to @Pujan92

**Comment by kevinksullivan** [comment] 2023-08-24 23:07
Offer sent to @hichamcc for reporting. Let me know when you've accepted!

**Comment by hichamcc** [comment] 2023-08-24 23:12
@kevinksullivan  accepted

**Comment by kevinksullivan** [comment] 2023-08-25 19:39
All set here

**Closed by kevinksullivan** 2023-08-25 19:39 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:42
Can I get a payment summary on this issue?

**Comment by kevinksullivan** [comment] 2023-10-09 14:11
@JmillsExpensify 

Reporter: @hichamcc $250
Contributor: @Pujan92 $1,000
C+: @rushatgabhane $1,000

**Comment by JmillsExpensify** [comment] 2023-10-09 17:21
$1,000 payment approved for @rushatgabhane based on BZ summary.
