### ISSUE TITLE
[$1000] Web - Clicking the back button will directly lead to chat after reloading the page on the Add message section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23400] opened 2023-07-22 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Workspace
2. Click any workspace > Members > Invite > Invite new member> click 'Next'
3. 'Add message' page will appear
4. Reload the web and click the Back button

## Expected Result:
The page should only go to the previous page which was Invite new member page

## Actual Result:
The page directly goes to the Chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/36b8bab8-aa37-4043-9d23-2f7d9ba867a1

https://github.com/Expensify/App/assets/93399543/be6eb246-d9b6-4695-b953-ee5b0b73b73e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689896164334469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc5f114f4d444a2a</li>
        <li>Upwork Job ID: 1683962882873065472</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by alphaboss1104** [comment] 2023-07-24 16:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Clicking the back button leads directly to the report after reloading the page in the add message section of inviting a member to a workspace.
### What is the root cause of that problem?
In `onBackButtonPress` callback function the `specific route` isn't defined.
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/pages/workspace/WorkspaceInviteMessagePage.js#L168-L176
### What changes do you think we should make in order to solve the problem?

1. Get the policyID : `const policyID = lodashGet(this.props.route, 'params.policyID');`
2. Set the specific route to the `onBackButtonPress` callback function:
    `onBackButtonPress={() => Navigation.goBack(ROUTES.getWorkspaceInviteRoute(policyID))}`

### What alternative solutions did you explore? (Optional)
None.

**Comment by adelekennedy** [comment] 2023-07-25 22:10
I'm able reproduce and I can't find an _exact_ dupe

**Comment by adelekennedy** [comment] 2023-07-25 22:11
reproducible and I can't find an _exact_ dupe

**Comment by s77rt** [comment] 2023-07-26 11:09
@adelekennedy I think we can close this, this is a dupe of https://github.com/Expensify/App/issues/22041 (same root cause)

**Comment by adelekennedy** [comment] 2023-07-26 14:31
Thank you @s77rt!

**Closed by adelekennedy** 2023-07-26 14:31 UTC
Labels: External, Daily, Help Wanted, Bug
