### ISSUE TITLE
Hold request - Not here page shows up when attempting to hold request by requestee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38345] opened 2024-03-14 19:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Requets money from User B
3. [User B] Open IOU request details from User A
4. [User B] Click 3-dot menu > Hold request

## Expected Result:
Hold request RHP opens without issue

## Actual Result:
Not here page shows up after selecting Hold request.
This issue only occurs for requestee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/88d9d190-3d37-47de-bed9-12300cdb0ffe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-14 19:12
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by godofoutcasts94** [comment] 2024-03-14 19:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold request - Not here page shows up when attempting to hold request by requestee
### What is the root cause of that problem?
This is the issue with routing i.e. in here : 
https://github.com/Expensify/App/blob/d4eaf4e2deabb6c07736b1eaefaa203cc9cf5850/src/ROUTES.ts#L301-L304
we are having issue i.e. it getting to `request` route but not `requestee` route and throwing an error on console i.e. the below error.

<img width="1101" alt="Screenshot 2024-03-15 at 1 15 33 AM" src="https://github.com/Expensify/App/assets/158435970/3a676053-0530-461f-a51b-3b1cda9dffe5">

### What changes do you think we should make in order to solve the problem?

We need to modify the route like this : 
```
            `${CONST.IOU.TYPE.SEND}/edit/reason/${transactionID}?backTo=${backTo}&reportID=${reportID}` as const,
    },
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-14 19:55
Updated [Proposal](https://github.com/Expensify/App/issues/38345#issuecomment-1998307986)

**Comment by sobitneupane** [comment] 2024-03-18 08:41
We can merge this issue with https://github.com/Expensify/App/issues/37554 issue.

**Comment by greg-schroeder** [comment] 2024-03-25 11:18
Okay merging into https://github.com/Expensify/App/issues/37554 per Sobit's comment, so closing this one

**Closed by greg-schroeder** 2024-03-25 11:18 UTC
Labels: Daily, Overdue, Bug
