### ISSUE TITLE
[HOLD for payment 2024-08-07] [$500] Unable to add Apple's standard emojis

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42588] opened 2024-05-24 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716485230886559

## Action Performed:
1. open a chat
2. Type the syntax :troll: and send
3. Open the Mac's emoji picker and add troll and send 
4. Hover on the emoji sent 
## Expected Result:
Describe what you think should've happened
Emoji is sent in the step 2
When hovering the emoji should show the added emoji in step 4

## Actual Result:
Emoji is sent as syntax in step 2
Only `::` shows in step 4

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screenshot 2024-05-23 at 10 25 27 AM](https://github.com/Expensify/App/assets/38435837/cb751cc1-ebf6-47d2-aaec-b36697027e14)

https://github.com/Expensify/App/assets/38435837/c78406fa-232e-4c5a-80e4-974eb6c99fff

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e356e9d1262d3053</li>
        <li>Upwork Job ID: 1798110457114009600</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 102712206</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by nkdengineer** [comment] 2024-05-26 15:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji is sent as syntax in step 2
Only :: shows in step 4

### What is the root cause of that problem?
We are missing 🧌  icon in the list of emojis in [here](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/assets/emojis/common.ts#L39)

### What changes do you think we should make in order to solve the problem?


We add all the missing icons to the list [here](https://github.com/Expensify/App/blob/525ad6ffede2f0127c0759855f020e54fc704403/assets/emojis/common.ts#L39)

### What alternative solutions did you explore? (Optional)
NA

**Comment by kevinksullivan** [comment] 2024-06-04 21:51
Low priority VSB bug.

**Comment by kevinksullivan** [comment] 2024-06-07 20:47
Not overdue, looking for proposals.

**Comment by mananjadhav** [comment] 2024-06-10 05:48
Taking this over ([thread](https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1717998375380519)).

**Comment by mananjadhav** [comment] 2024-06-10 06:40
I think @Krishna2323 proposal makes sense. We should focus on adding all the missing emojis as a part of the scope. 

In the long term we should improve on keeping these in sync. But I feel in the current issue we should only look at adding them manually. 

🎀 👀 🎀 C+ reviewed.

**Comment by rafecolton** [comment] 2024-06-10 16:07
I got this one :)

**Comment by rafecolton** [comment] 2024-06-10 16:12
@kevinksullivan that proposal looks good to me, I agree with backfilling other emoji as part of this change as well.

@Krishna2323 I like your original suggestions to add the relevant keywords, so let's do that too

**Comment by mananjadhav** [comment] 2024-06-10 16:30
Quick note @Krishna2323 @rafecolton, we'll have to take care of the skin tones too wherever applicable.

**Comment by rafecolton** [comment] 2024-06-25 16:42
Thank you for the update! We will discuss the price internally and get back to you. When it comes time to assign an Expensify engineer to review the PR, please tag me and I will review it. (I am not currently in the group that gets auto-assigned, so by default it will pick somebody new.)

**Comment by rafecolton** [comment] 2024-06-26 19:25
@Krishna2323 we discussed internally and agreed that $500 is a fair price for the change. I updated the issue title to reflect that, and @kevinksullivan will ensure you get paid the correct amount once this is deployed.

**Comment by rafecolton** [comment] 2024-06-26 19:26
Cool to see we automated that part 😄

**Comment by mallenexpensify** [comment] 2024-07-03 23:44
@Krishna2323 , can we focus on the original scope of this issue, where we add the missing emoji for $500? Then, once the PR has hit production, we can discuss potential future improvements? **If** we decide to proceed there, you'd get first dibs on the job.

**Comment by mallenexpensify** [comment] 2024-07-05 22:30
> missing emoji

@Krishna2323, for that I mean all the emoji that are missing (apparently the plural of emoji is... emoji).
 
> I will create a function that will do everything at once and return the expected emoji list. 

Wonderful! 

> In the future, if any version releases, we just need to use that function and pass the latest emojis list from EmojiBase, then simply copy and paste to update our emoji list.

This is the part I don't want to get too caught up in. Can we consider a nice-to-have to maybe use in the future? If so, I'd be OK with trying to allow you dibs to work on the next emoji update. (my only concern is that it might be a while til there's another update, which means it might be tough to ensure you're tagged and offered the update to test/use your formula).   

Either way... thanks for taking this on and for investing the time.

**Comment by mananjadhav** [comment] 2024-07-07 22:44
I agree with @mallenexpensify here. @Krishna2323 Adding these emoji automation is good to have. Understand the scenario that adding manually for the ones we already know missing (~80) has crossed 3 weeks. If we go for an automation (which is a value-add) can take equally more amount of time to test thoroughly and ensure it's working. 

Sorry I couldn't respond to your DM, but when I asked for formal proposal I meant add some beef to the technical details. Which again I am fine if you add that when we do prioritize the automation issue. I still feel the solution proposed in the slack thread needs a decent amount of grooming. (Personally I don't mind you using that automation to add these 80 emoji :P but I think we should look for closing this issue, as it's already more than a few weeks).

And about the emoji issues that you linked, @mallenexpensify we could just put them on Hold and if we see several instances we can work on it.

**Comment by mananjadhav** [comment] 2024-07-10 00:30
@Krishna2323 What's the ETA on the PR for this issue?

**Comment by mananjadhav** [comment] 2024-07-10 18:00
Quick bump @Krishna2323

**Comment by mananjadhav** [comment] 2024-07-16 20:13
@Krishna2323 I am a little confused, didn't we decide to just add the emojis here? cc - @mallenexpensify did we change the stance?

**Comment by mallenexpensify** [comment] 2024-07-19 00:02
Without knowing some of the particulars of the code and proposal, let's approach this as a v1 to get the emojis added then we can improve/streamline things after.

**Comment by mananjadhav** [comment] 2024-07-22 18:41
@Krishna2323 Still waiting for an update on this one.

**Comment by deetergp** [comment] 2024-07-29 21:55
@Krishna2323 @mananjadhav is it possible that we caused [this blocker](https://github.com/Expensify/App/issues/46453)?

**Comment by kevinksullivan** [comment] 2024-08-09 23:10
@mananjadhav can you complete the steps above?

**Comment by kevinksullivan** [comment] 2024-08-09 23:12
Payment summary:
- @mananjadhav : $500 (NewDot)
- @Krishna2323 $500

**Comment by kevinksullivan** [comment] 2024-08-09 23:14
@Krishna2323 job expired so I created a new one. Lmk when you accept! 

https://www.upwork.com/ab/applicants/1822048410581815910/job-details

**Comment by mananjadhav** [comment] 2024-08-14 17:12
Raised request on NewDot.

**Comment by JmillsExpensify** [comment] 2024-08-14 18:10
$500 approved for @mananjadhav

**Comment by kevinksullivan** [comment] 2024-08-20 20:51
all set!

**Closed by kevinksullivan** 2024-08-20 20:51 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
