### ISSUE TITLE
[Awaiting Payment 26th August] [$250] [Payment card / Subscription] Make change billing card currency form wait until request has finished before closing

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#45645] opened 2024-07-17 23:33 UTC
# Problem

When changing the billing currency on the subscription page, the panel closes immediately after clicking "save". This is a problem because if the request has an error we should show that error in the panel, but the panel will have already closed. 

https://github.com/user-attachments/assets/9873aed7-d637-4240-9f34-edfc72a77b8f

# Solution

We should have this panel behave the same way that the add payment card panel behaves. It should wait for the request to finish and show a loading indicator while we wait.

cc: @dominictb 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcbde08595f89c2b</li>
        <li>Upwork Job ID: 1818075810728864794</li>
        <li>Last Price Increase: 2024-07-30</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103346635</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by blimpich** [comment] 2024-07-17 23:33
Holding and not adding the external label until necessary backend changes are done

**Comment by blimpich** [comment] 2024-07-23 20:41
Almost there, backend changes are still in review.

**Comment by nkdengineer** [comment] 2024-07-30 01:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to make change billing card currency form wait until request has finished before closing

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/pages/settings/Subscription/PaymentCard/ChangeBillingCurrency/index.tsx#L26, we go back immediately after calling the API, we don't wait for the API to be successful.

### What changes do you think we should make in order to solve the problem?

- Remove the `goBack` [here](https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/pages/settings/Subscription/PaymentCard/ChangeBillingCurrency/index.tsx#L26)
- Add an `useEffect` that will only call `goBack` if the `isLoading` of the `ONYXKEYS.FORMS.CHANGE_BILLING_CURRENCY_FORM` changes from `true` to `false`, and there's no `errors` in the form (so it's not the failure case). This is same approach with adding debit card page https://github.com/Expensify/App/blob/df69c80229acdc510064d2671e2fdde8095a93a7/src/pages/settings/Wallet/AddDebitCardPage.tsx#L35

### What alternative solutions did you explore? (Optional)

**Comment by blimpich** [comment] 2024-07-31 16:38
@dominictb I'm treating this the same as any other external issue. Please feel free to give a proposal and we'll go through the normal proposal proposal review process.

**Comment by rushatgabhane** [comment] 2024-07-31 18:13
Alright so this command should not be optimistic. We have to wait for the action to complete

**Comment by rushatgabhane** [comment] 2024-07-31 18:14
I like @nkdengineer's **alternative** [proposal](https://github.com/Expensify/App/issues/45645#issuecomment-2257266199) to use `API.makeRequestWithSideEffects()` and navigate back only if the promise is resolved

🎀 👀 🎀

**Comment by blimpich** [comment] 2024-07-31 19:05
@rushatgabhane we want to avoid using `makeRequestWithSideEffects` unless absolutely necessary, as per [this comment](https://github.com/Expensify/App/blob/d2ac23bb138dcb6f40717f3b2d440355367231f4/src/libs/API/index.ts#L130). Can you reconsider the existing proposals given that we want to avoid using `makeRequestWithSideEffects`?

**Comment by rushatgabhane** [comment] 2024-07-31 19:21
Okay then we will have to use some variation of `useEffect` to re-render and go back.

> Add an useEffect that will only call goBack if the isLoading of the ONYXKEYS.FORMS.CHANGE_BILLING_CURRENCY_FORM changes from true to false, and there's no errors in the form (so it's not the failure case). This is same approach with adding debit card page

@nkdengineer's proposal looks good

**Comment by blimpich** [comment] 2024-07-31 19:51
Assigning @nkdengineer since they have the C+ chosen solution and posted their proposal first. Sorry @dominictb, but even though you had a solution for the issue on the other issue I'm going to treat this as a normal issue and consider proposals in the order they were posted to this issue and this issue only.

@nkdengineer please feel free to raise a PR.

**Comment by nkdengineer** [comment] 2024-08-05 03:43
@blimpich we have open PR [here](https://github.com/Expensify/App/pull/46635)
But there are some errors occurring. As far as I know, we need to add some special steps [here](https://github.com/Expensify/App/issues/44904#issuecomment-2223326082).
Please help me.

**Comment by blimpich** [comment] 2024-08-05 22:01
@nkdengineer the special steps were just to use my local backend via ngrok. I've DM'ed you those credentials so you should be able to use [Stripe's test cards](https://docs.stripe.com/testing#cards), if I'm online. I generally work 9am-5pm PST hours.

**Comment by blimpich** [comment] 2024-08-14 16:50
@rushatgabhane from [this comment](https://github.com/Expensify/App/pull/46635#discussion_r1713141545) it looks like we're waiting on you to re-review. Are you still able to review this PR?

**Comment by rushatgabhane** [comment] 2024-08-14 16:55
@blimpich thanks for the bump. I'll be reviewing it tonight

**Comment by garrettmknight** [comment] 2024-08-20 13:36
@isabelastisser looks like the PR is on prod btw.

**Comment by trjExpensify** [comment] 2024-08-26 10:14
PR hit prod on the 19th August. https://github.com/Expensify/App/pull/46635

**Comment by isabelastisser** [comment] 2024-08-27 00:23
Payment summary:

@rushatgabhane $250 / C+ review / NewDot payment `PENDING`
@nkdengineer $250 / Contributor / Paid in Upwork

**Closed by isabelastisser** 2024-08-27 00:23 UTC
Labels: External, Engineering, Daily, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-08-27 11:52
$250 approved for @rushatgabhane
