### ISSUE TITLE
[$500] Android - IOU - In WS, opening paid IOU details page shows hhm not here

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37255] opened 2024-02-27 02:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a workspace report
3. Tap plus icon--- request money
4. Enter amount and tap next
5. Enter merchant
6. Tap 3 dot on top right and add receipt
7. Tap request
8. Tap pay elsewhere
9. Tap IOU paid to open details page

## Expected Result:
WS request money created with receipt and paid elsewhere on opening details page must show iou details and not hhm not here page

## Actual Result:
WS request money created with receipt and paid elsewhere on opening details page shows hhm page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c0abdcc2-7a96-4beb-821a-1fea1b2ad3af

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e960630f13d2f58a</li>
        <li>Upwork Job ID: 1762306014371397632</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2024-02-27 12:11
I am not able to reproduce on simulator. @akinwale could you please help to double check?

**Comment by muttmuure** [comment] 2024-02-27 18:52
Also can't reproduce this

**Comment by puneetlath** [comment] 2024-02-27 18:53
Closing as non-reproducible. Thanks y'all.

**Closed by puneetlath** 2024-02-27 18:53 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted
