### ISSUE TITLE
Web - App works with delay, when reinvite the member to WS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33291] opened 2023-12-19 14:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch the app
2. Log in with any account
3. Go to WS and invite phone number
4. Reinvite the same phone number

## Expected Result:
App should work without delay, when reinvite the member to WS

## Actual Result:
App works with delay, when reinvite the member to WS

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5e67d575-8533-4a95-b41a-7735af0b2304

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-12-19 14:41
Issue is not reproducible in production 

https://github.com/Expensify/App/assets/93399543/f34edcf5-1c40-4162-b98b-673cd1593ca9

**Comment by amyevans** [comment] 2023-12-19 16:40
I believe this is a regression https://github.com/Expensify/App/pull/32962, trying to verify locally now. Although it looks like it's already being reverted so I can also retest on staging after that

**Comment by amyevans** [comment] 2023-12-19 20:32
Retested on staging, I think we're good to close:

https://github.com/Expensify/App/assets/7277067/c128ebbd-db08-4375-a7fb-36720b123b01

**Comment by TMisiukiewicz** [comment] 2023-12-20 11:27
This still happens for me on `main` with High Traffic account. Looks like it was not a regression from #32962.

https://github.com/Expensify/App/assets/13985840/12307183-97ef-4762-9aea-248dfc080c91

**Comment by mountiny** [comment] 2023-12-20 12:36
Lets reopen while we can confirm this was fixed on staging, seems like this is not necessarily linked to the PR which got reverted

**Comment by jasperhuangg** [comment] 2023-12-22 03:16
This happens on prod as well, so I don't think this needs to block deploy

**Comment by amyevans** [comment] 2024-01-02 23:31
Coming back from OOO and I can't reproduce on staging or prod. Going to close again but if someone is still able to reproduce lmk!

**Closed by amyevans** 2024-01-02 23:31 UTC
Labels: Engineering, Daily, Overdue
