### ISSUE TITLE
[$1000] Chat - Focus is lost and keyboard is hidden when 'Edit comment' is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19968] opened 2023-06-01 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
__

**Issue found when executing PR** https://github.com/Expensify/App/pull/19511
## Action Performed:
1. Login with any account
2. Go to any chat
3. Click the pencil icon to edit a comment

## Expected Result:
Edit box gains auto focus and key board opens

## Actual Result:
Focus is lost and keyboard is hidden when 'Edit comment' is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/b8870634-95f3-457f-8580-9227d64ac967

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0134f83491b2f5ca11</li>
        <li>Upwork Job ID: 1664382213939425280</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-06-01 19:21
Asking for a gut-check on this one here: https://expensify.slack.com/archives/C049HHMV9SM/p1685647273833609

**Comment by strepanier03** [comment] 2023-06-01 21:22
I cannot recreate this on Android Chrome on my Pixel 6 Pro. 

I can recreate this using Browserstack on the newest staging release on an iPhone 14 Pro. 

https://github.com/Expensify/App/assets/10925636/a64d7903-3a4c-4475-8e4d-1223907bf5ca

**Comment by amyevans** [comment] 2023-06-02 00:53
I reproduced on my iPhone and modified the OP to clarify the reproduction steps a bit. They were implying using the text `[block]` was crucial, but it's happening when editing any comment.

**Comment by eh2077** [comment] 2023-06-02 13:40
Hmm, I remembered it's intended not to open keyword on mobile web for better UX but I can't find relevant GH issues easily.

**Comment by C25Ronaldo** [comment] 2023-06-02 16:08
One solution you can try is to use a package like React Native Modal, which will allow you to display a modal or pop-up view on top of your existing view. This will prevent the keyboard from hiding when the "Edit comment" option is selected.

**Comment by Victor-Nyagudi** [comment] 2023-06-03 17:14
A similar [issue involving the keyboard not opening when editing a message](https://github.com/Expensify/App/issues/19641) was recently closed. 

The [consensus](https://github.com/Expensify/App/issues/19641#issuecomment-1574061309) was that the keyboard not showing up is the desired behavior. 

I'm curious what you have to say about this one, @jliexpensify.

cc: @PauloGasparSv

**Comment by lschurr** [comment] 2023-06-05 14:11
@amyevans @eVoloshchak what do you think? Is this intended and we should close?

**Comment by PauloGasparSv** [comment] 2023-06-05 14:38
> The https://github.com/Expensify/App/issues/19641#issuecomment-1574061309 was that the keyboard not showing up is the desired behavior.

I think the consensus was that **we couldn't replicate the issue on [mWeb](https://github.com/Expensify/App/issues/19641#issuecomment-1566295670) or [mobile native](https://github.com/Expensify/App/issues/19641#issuecomment-1573044816)** so we [closed it](https://github.com/Expensify/App/issues/19641#issuecomment-1574061309)

> @amyevans @eVoloshchak what do you think? Is this intended and we should close?

I see the bug on the Simulator now (I also tested an older version of the Simulator to make sure and it also shows there). I don't think that's the intended behavior and IMO we should fix this.

**Comment by amyevans** [comment] 2023-06-06 22:48
I'm honestly not sure what expected behavior here is. My first reaction was that the keyboard should open, but I'm sure there's nuance and context that I don't have and it wouldn't be the first time I was wrong 😄 

> I remembered it's intended not to open keyword on mobile web for better UX but I can't find relevant GH issues easily

I tried searching Slack and came upon https://github.com/Expensify/App/issues/12199. To me the title and repro steps of that GH match ours here, but the screenshot in that GH is kind of throwing me (since the keyboard is present in the screenshot). cc @zanyrenney maybe you can weigh in here?

**Comment by eVoloshchak** [comment] 2023-06-13 12:07
I think this is a bug. 
The keyboard doesn't open only on mobile Safari, while it opens on Android, iOS, and mobile Chrome.
This most definitely is caused by https://github.com/Expensify/App/issues/10414, fixing that should resolve this issue in mWeb Safari



https://github.com/Expensify/App/assets/9059945/7933dfa9-1707-4460-9b19-c4fb1d14b757




https://github.com/Expensify/App/assets/9059945/6108eefc-0120-41b1-932c-c1353cd00d5e

**Comment by mvtglobally** [comment] 2023-06-13 19:02
Issue not reproducible during KI retests. (First week)

**Comment by amyevans** [comment] 2023-06-13 20:50
> This most definitely is caused by https://github.com/Expensify/App/issues/10414, fixing that should resolve this issue in 
mWeb Safari

Ah right, _that_ elusive bug (our 2nd oldest not on hold IIRC). Looks like it's getting some momentum again as of late, should we place this issue on hold for 10414? Or just close outright as a dupe? (I can't say I've read all 300+ comments there)

> Issue not reproducible during KI retests. (First week)

@mvtglobally what platform were you testing on?

**Comment by eVoloshchak** [comment] 2023-06-15 16:24
>  should we place this issue on hold for 10414? Or just close outright as a dupe?

@amyevans, the issue description states that this issue occurs on iOS/Safari and Android/Chrome. During my testing I could reproduce this only in Safari. 
If this occurs in Safari only, we should close this as duplicate
Is this also occurs in Chrome, this won't be fixed by https://github.com/Expensify/App/issues/10414 alone and we should keep this open

**Comment by amyevans** [comment] 2023-06-16 14:10
Alright, @strepanier03 and @eVoloshchak were unable to reproduce on Android Chrome, and I just confirmed the same as well:

https://github.com/Expensify/App/assets/7277067/dfe155d2-434f-4f8c-9311-309c5788df52

So I think the original bug report was in error and this only affects iOS Safari, which makes it a dupe of #10414. Going to close.

**Closed by amyevans** 2023-06-16 14:10 UTC
Labels: External, Daily, Help Wanted, Bug
