### ISSUE TITLE
[$250] Composer addes a space after adding every 2 emojis from the keyboard

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51056] opened 2024-10-17 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729119915223329

## Action Performed:
1. Open any chat
2. Add 2 emojis from the keyboard

## Expected Result:
No space added after adding 2 emojis
## Actual Result:
A space is added automatically after 2 emojis
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/5bebc572-d37f-4f0a-91dd-8de0bfb65640

https://github.com/user-attachments/assets/c060b649-03fb-4cdf-a031-077539d80363

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849498424863638708</li>
        <li>Upwork Job ID: 1849498424863638708</li>
        <li>Last Price Increase: 2024-10-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by bernhardoj** [comment] 2024-10-18 08:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A space is added after adding emoji only for the 2nd emoji.

### What is the root cause of that problem?
When only emoji is inserted, we will add a space to it.
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L411-L416

But in this issue, it only works for the first emoji then only after the 2nd emoji the space is added afterward. It first find the string diff between the prev and current text. For example, if the prev text is  "👍 " and the current text is "👍 👍", the diff should be "👍", but in reality, it's " 👍". The space from the prev text is included.

The diff is the substring of the current text from startIndex and endIndex.
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L402

startIndex is from the currentIndex which is from the first index of the mismatch character or if the currentIndex is smaller then the selection start.
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L384-L387
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L390

`|` = cursor
The issue we have here is that, the selection start value is wrong. The prev text is "👍 |" but the selection start is 2 (the emoji has 2 length) instead of 3. So, the currentIndex/startIndex is 2.

Why the selection start value is wrong?

When we add the emoji from the device keyboard, we will manually update the selection to 3 (include the space). But it also trigger the `onSelectionChange` with a value of 2 (doesn't include space) which override the manual update. This only happen on iOS. On iOS, if we add the text (the space) from the state, `onSelectionChange` won't be triggered.

Another example is when you add the emoji from emoji picker, `onSelectionChange` won't be triggered.

### What changes do you think we should make in order to solve the problem?

The idea is to ignore the `onSelectionChange` when we manually update the selection.
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L528-L536
```
const ignoreSelectionChangeEvent = useRef(false);

if (ignoreSelectionChangeEvent.current) {
    ignoreSelectionChangeEvent.current = false;
    return;
}
```

We will only ignore it if emoji is inserted through keyboard (fromOnChangeText is true) and only on iOS.

```
const updateComment = useCallback(
    (commentValue: string, shouldDebounceSaveComment?: boolean, fromOnChangeText = false) => {
        raiseIsScrollLikelyLayoutTriggered();
        const {startIndex, endIndex, diff} = findNewlyAddedChars(lastTextRef.current, commentValue);
        const isEmojiInserted = !!diff.length && endIndex > startIndex && diff.trim() === diff && EmojiUtils.containsOnlyEmojis(diff);
        ignoreSelectionChangeEvent.current = isIOSNative && isEmojiInserted && fromOnChangeText;
```

We will pass `fromOnChangeText` as true here.
https://github.com/Expensify/App/blob/e4fe4c4fe126db86cd3ecb8d918d81d14ac09942/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L509-L511

**Comment by jayeshmangwani** [comment] 2024-10-18 08:20
> I reported the bug on slack and have context, can i be the C+ for the issue ?

@allgandalf There’s no rule stating that if C+ reports a bug, they must be assigned as the C+ on the issue. This is a straightforward issue with no prior context needed, and we’ve had the same issue reported and closed in the past https://github.com/Expensify/App/issues/41455.

@JmillsExpensify Let's stick to the auto-assignment process here, as discussed in this Slack conversation https://expensify.slack.com/archives/C02NK2DQWUX/p1725898105408529?thread_ts=1725778908.343539&cid=C02NK2DQWUX.

cc: @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-10-18 23:45
@jayeshmangwani is correct, that's our current process. 
That said, I _might_ be addressing a potential change to this soon, will share in #contributor-plus if/when there's an update.

**Comment by mallenexpensify** [comment] 2024-10-18 23:55
While looking at this
> Expected Result:
No space added after adding 2 emojis

I think the expected result might be to add a space after each emoji.  That's how it works in Slack, I'm guessing the logic would be that most people add 1 emoji then send text after, which is why we surface the keyboard after an emoji is added vs continuing to show the emoji selection modal.

**Comment by JmillsExpensify** [comment] 2024-10-24 17:10
I remember a super long comment on this, though I'm cool making it consistent with other chat platforms to reduce any confusion. Opened up to the community.

**Comment by s77rt** [comment] 2024-10-24 22:05
@bernhardoj Thanks for the proposal. It seems that this bug is on RN and if it's the case we should fix it upstream.

> But it also trigger the onSelectionChange with a value of 2 (doesn't include space) which override the manual update. This only happen on iOS.

This seems to happen on Android too but we get another event that corrects the selection

https://github.com/user-attachments/assets/e8d0cba2-7794-4f5d-a48b-1a1070678af4

**Comment by bernhardoj** [comment] 2024-10-25 03:03
> On iOS, if we add the text (the space) from the state, onSelectionChange won't be triggered.

Ah yes, I mean this one only happens on iOS. It doesn't trigger onSelectinChange if we add the text from the state.

> It seems that this bug is on RN and if it's the case we should fix it upstream.

Yeah, I think that's the most ideal way.

**Comment by s77rt** [comment] 2024-10-28 19:54
Still looking for proposals

**Comment by mallenexpensify** [comment] 2024-10-29 23:49
Gonna close this one for focus as I don't think it falls under the #quality project.  Comment or reopen if you disagree.

**Closed by mallenexpensify** 2024-10-29 23:49 UTC
Labels: External, Daily, Help Wanted, Bug
