### ISSUE TITLE
[$500] [HOLD for payment 2024-03-29] [HOLD for payment 2024-03-26] Profile - Avatar is blank when viewed in full screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38516] opened 2024-03-18 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Concierge chat.
3. Tap on the header.
4. Tap on the avatar.

## Expected Result:
Avatar shows up without issue.

## Actual Result:
Blank page is seen in avatar view.
This issue is only reproducible with default avatar.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/533babd7-39bc-450d-909a-21bcf587b28a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a2a95133386223a</li>
        <li>Upwork Job ID: 1778002346278477824</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-18 20:31
We think that this bug might be related to #wave-control

**Comment by hayata-suenaga** [comment] 2024-03-18 20:44
Although this issue ha alreay been escribed on the OP happens only on mobile native platforms, another e observed when the Concierge avatar.

**Comment by ahmedGaber93** [comment] 2024-03-19 02:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - Avatar is blank when viewed in full screen

### What is the root cause of that problem?
the root cause is react native image not support svg.
and we pass source = svg default avtar for concerige  here in ProfileAvatar.tsx
https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/settings/Profile/ProfileAvatar.tsx#L41
follow getFullSizeAvatar > getAvatar > getDefaultAvatar. it return svg file `ConciergeAvatar`

https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/libs/UserUtils.ts#L85-L94


and when we display in ProfileAvatar.jsx we use react native image.
follow ProfileAvatar > AttachmentModal > AttachmentView > AttachmentViewImage

### What changes do you think we should make in order to solve the problem?
pass prop `maybeIcon` [here](https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/pages/settings/Profile/ProfileAvatar.tsx#L38) to check if svg and use [Icon](https://github.com/Expensify/App/blob/22bd9eb633f0d378158bc3b8674682fbc39a56ea/src/components/Attachments/AttachmentView/index.js#L135) instead of image

we can pass it when platform is native only 
```javascript
 const platform = getPlatform();
  const isNative = platform === CONST.PLATFORM.IOS || platform === CONST.PLATFORM.ANDROID;
 maybeIcon={isNative}
```

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-03-19 07:03
regression from #36560
It's weird to have `source.uri` as number but we should still keep this original logic until refactor.

```diff
-   if (typeof source === 'object' && 'uri' in source && typeof source.uri === 'number') {
-       imageSource = source.uri;
-   }
```

Here's fix: https://github.com/Expensify/App/pull/38554
cc: @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-03-19 18:15
@situchan do we have to cherry pick the linked PR?

**Comment by situchan** [comment] 2024-03-24 14:30
Please assign me here

**Comment by hayata-suenaga** [comment] 2024-03-25 16:59
@aimane-chnaif

**Comment by hayata-suenaga** [comment] 2024-03-25 17:01
### Payment Summary

@situchan for a contributor role (not C+ role) for authoring [the PR](https://github.com/Expensify/App/pull/38554) that fixes this regression from [the PR](https://github.com/Expensify/App/pull/38554).

@aimane-chnaif reviewed @situchan's PR but because @aimane-chnaif was the C+ for the PR that caused the regression, no payment for @aimane-chnaif here 🙇

**Comment by hayata-suenaga** [comment] 2024-04-08 21:58
@laurenreidexpensify, please handle payment according to [this summary](https://github.com/Expensify/App/issues/38516#issuecomment-2018480438) when you have time 🙇

**Comment by laurenreidexpensify** [comment] 2024-04-10 10:11
Payment Summary: 

- Contributor -  @situchan for a contributor role (not C+ role) for authoring https://github.com/Expensify/App/pull/38554 that fixes this regression from https://github.com/Expensify/App/pull/38554. - Please apply in Upwork https://www.upwork.com/jobs/~015a2a95133386223a

- C+ no payment as per https://github.com/Expensify/App/issues/38516#issuecomment-2018480438: @aimane-chnaif reviewed @situchan's PR but because @aimane-chnaif was the C+ for the PR that caused the regression, no payment for @aimane-chnaif here 🙇

**Comment by laurenreidexpensify** [comment] 2024-04-11 10:15
@situchan is OOO for April - will come back to this in May when he's back to close out payment

**Comment by hayata-suenaga** [comment] 2024-05-14 05:50
I think @situchan is back from OOO. Moving the priority of this issue to daily again

**Comment by laurenreidexpensify** [comment] 2024-05-14 08:29
@situchan offer sent in Upwork pls accept

**Comment by laurenreidexpensify** [comment] 2024-05-16 08:46
Payment issued in Upwork to @situchan - closing

**Closed by laurenreidexpensify** 2024-05-16 08:46 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
