### ISSUE TITLE
[$1000] Web - Incorrect Paid or Owed amount information between the Report and the Report's details header

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21687] opened 2023-06-27 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: The currency may need to be set other than USD. (My currency was VNĐ)
1. Send IOU request between users (assume that User = X and Amount = Y)
2. Check the label "X owed Y" or "X paid Y" on the Report
3. Click to a report to view request details
4. Check the amount information on Report details' header

## Expected Result:
 The amount Owed or Paid should be same

## Actual Result:
 The amount displayed on the Report detail's header is `x100 bigger` than on the Report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![From LHN (1)](https://github.com/Expensify/App/assets/93399543/bcb99013-6107-44f6-8b0f-41328d894281)
![From Report list (1)](https://github.com/Expensify/App/assets/93399543/6e86bf5a-0d01-4925-87ee-44179e69ef49)
![image - 2023-06-27T102322 870](https://github.com/Expensify/App/assets/93399543/636a7243-48c5-4ad6-abe6-5ca8ce1f3059)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687516866357409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b8ccb7814796c5f</li>
        <li>Upwork Job ID: 1676172896159289344</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-06-28 12:48
@tranvantoan-qn can you confirm whether you can reproduce this in another currency other than VND? Can you try in Euros and see if it persists too, so we can identify if this is a currency specific error or all non-US currencies. Thanks

**Comment by tranvantoan-qn** [comment] 2023-06-28 13:37
@laurenreidexpensify 
I tried with Euro and Cad, and the issue is the same, `00` is added at the end making the total amount it x100 bigger

<img width="1065" alt="EURO" src="https://github.com/Expensify/App/assets/10254571/e0db5ee0-7852-4482-81ee-94a6d63391ed">
<img width="1044" alt="CAD" src="https://github.com/Expensify/App/assets/10254571/98e029db-8d74-4d36-9ba3-71ea2c4f68c6">

**Comment by laurenreidexpensify** [comment] 2023-07-04 10:15
Not overdue, reviewing

**Comment by alitoshmatov** [comment] 2023-07-04 10:23
Duplicate of - https://github.com/Expensify/App/issues/19792

**Comment by mollfpr** [comment] 2023-07-05 04:39
Thanks, @alitoshmatov. Yeah, it seems this is a dupe. @laurenreidexpensify we can close this in favor of #19792.

**Closed** 2023-07-05 07:49 UTC
Labels: External, Daily, Help Wanted, Bug
