### ISSUE TITLE
[$1000] Chat - Certain characters are considered as 6 characters within the message box

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26051] opened 2023-08-28 01:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Insert a text with a length exceeding 15,000 characters
2.  Type characters such as: " , ç , à , & , é
3.  The total increments by 6 for each occurrence

## Expected Result:
The overall count should increase by 1

## Actual Result:
The overall count increased by 6

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cc330d46-8792-4aa2-8747-0826d58acbf4

https://github.com/Expensify/App/assets/78819774/c3269a3a-ac53-4493-bf81-def5bdd63868

**Expensify/Expensify Issue URL:**

**Issue reported by:** @hichamcc

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692470777922139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef4e9f58ef6fe5dd</li>
        <li>Upwork Job ID: 1696338819616731136</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-28 04:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When calculating the total comment length, characters with diacritics are being counted as Unicode characters (6 chars in length).

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by redstar504** [comment] 2023-08-29 02:17
This was intentional due to the bug https://github.com/Expensify/App/issues/13988 which was fixed by PR https://github.com/Expensify/App/pull/14752.

**Comment by akinwale** [comment] 2023-08-29 02:26
> This was intentional due to the bug #13988 which was fixed by PR #14752.

Ah, this makes a lot of sense. I was really curious as to why the length was being calculated this way in the first place. Thanks for the context.

**Comment by MitchExpensify** [comment] 2023-08-29 04:40
Ah got it thanks @redstar504 ! Closing in that case

**Closed by MitchExpensify** 2023-08-29 04:40 UTC
Labels: External, Daily, Help Wanted, Bug
