### ISSUE TITLE
Text in the composer is very small when device font size is minimum

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35787] opened 2024-02-04 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Device font size is set to minimum
1. Launch New Expensify app
2. Open any chat
3. Type in the composer
4. Send it

## Expected Result:
The text in the composer has the same size as the text in the chat
![image](https://github.com/Expensify/App/assets/30609178/0bfb11d5-c1ae-4f54-9110-1dd417028510)

## Actual Result:
The text in the composer is smaller than the text in the chat
![image](https://github.com/Expensify/App/assets/30609178/e0ff273b-94b0-4f00-b299-018fb856a8e9)
## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

<img width="433" alt="Bug6366898_1707065880365!Screenshot_2024-02-05_at_00 55 51" src="https://github.com/Expensify/App/assets/78819774/5b905e68-da16-4e38-9d43-5015221a58a2">

https://github.com/Expensify/App/assets/78819774/194ea0ad-be52-4b59-8fe8-cfde19aef673

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-04 18:16
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by mountiny** [comment] 2024-02-05 14:38
Not a blocker. @lanitochka17 how does this behave in production?

**Comment by kavimuru** [comment] 2024-02-05 14:58
@mountiny this is the video from production

https://github.com/Expensify/App/assets/43996225/82604f28-c30c-4178-a287-37fda86cb647

**Comment by thienlnam** [comment] 2024-02-07 18:07
Looks like this is applicable to iOS as well https://expensify.slack.com/archives/C049HHMV9SM/p1707328995049399

I'll go ahead and take this over

**Comment by thienlnam** [comment] 2024-02-07 18:08
@tomekzaw Are we able to scale back the font size from the setting a bit? It seems to be much smaller than iMessage 

Here's iOS at the smallest font size from @AndrewGable 
![image](https://github.com/Expensify/App/assets/30609178/0bfb11d5-c1ae-4f54-9110-1dd417028510)

**Comment by tomekzaw** [comment] 2024-02-07 20:48
Thanks for reporting this issue. I think we use original `fontSize` passed via styles but obviously this needs investigation since it changes the behavior of the composer.

**Comment by tomekzaw** [comment] 2024-02-12 09:46
Should be fixed with https://github.com/Expensify/App/pull/35973.

The root cause of the issue was missing `allowFontScaling={false}` property.

Expensify app uses its own logic for font scaling so it disables operating system scaling.

Previously, composer would use `RNTextInput` which is a thin wrapper over built-in `TextInput` but with `allowFontScaling={false}` and some other properties already set.

In https://github.com/Expensify/App/pull/34292, I replaced `RNTextInput` with `MarkdownTextInput` directly without any wrappers so `allowFontScaling={false}` property is not set. PR #35973 restores the wrapper.

cc @thienlnam

**Comment by thienlnam** [comment] 2024-02-14 18:23
PR in review

**Comment by tomekzaw** [comment] 2024-02-20 15:33
Fixed in https://github.com/Expensify/App/pull/35973.

**Closed** 2024-02-20 16:42 UTC
Labels: Engineering, Daily
