### ISSUE TITLE
[HOLD for payment 2024-02-07][$500] Page refresh causes manual request with a receipt to be stuck

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30884] opened 2023-11-04 13:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @abdel-h66 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698081033316989

## Action Performed:
1. Open a chat
2. Create a manual request thought the chat plus icon (not the FAB)
3. Enter an amount and Next
4. Click the three dots on the top, and attach a receipt
5. Refresh the page in this step
6. The page will go back to the first step, autofilled with the previous amount.
7. Click next

## Expected Result:
We should be able to continue to the request information page

## Actual Result:
The page is stuck and keeps coming back whenever Next is clicked

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1211a422-d622-4c8c-bb6d-2db37c7f8027

https://github.com/Expensify/App/assets/38435837/62a173e0-cf6c-442d-9c3d-d51361245d84

https://github.com/Expensify/App/assets/38435837/22b132d1-5440-40a4-8277-5eb177d2bbed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b422f44a99747ac7</li>
        <li>Upwork Job ID: 1720802592517115904</li>
        <li>Last Price Increase: 2023-12-21</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 28067917</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-04 14:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Page refresh causes manual request with a receipt to be stuck
### What is the root cause of that problem?
When reloading page the browser will remove the upload file. Let's see this logic
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L106
When the upload file is lost, the App will redirect to the Tab Selector Page 
### What changes do you think we should make in order to solve the problem?
In here
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L106
We should add a check if It is manual request and , we will redirect to EditRequestReceiptPage

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-04 14:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After adding a receipt to the manual request, page refresh causes manual request to be stuck

### What is the root cause of that problem?

When we adding a receipt to the manual request, we create blob URL and set it to the iou
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/ReceiptSelector/index.js#L135-L136
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/ReceiptSelector/index.js#L154-L155

But this object URL is only valid for the current session and will be revoked once the page is refreshed. So when navigating to the confirmation page, file would be null and it'll be redirected to the manual request page or previous page.
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L106-L109

This is the root cause

### What changes do you think we should make in order to solve the problem?

I don't think we need to go back to the manual request page when object URL is not valid.
I suggest to reset the receipt in this case

Update the above code to
```
        FileUtils.readFileAsync(props.iou.receiptPath, props.iou.receiptFilename).then((file) => {
            if (!file) {
                IOU.setMoneyRequestReceipt('', '');
            } else {
```


<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/a530ef22-a62e-4c72-95b2-dd63bb0ba697


</details>

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-11-04 14:39
@s-alves10 Your proposal is the same as my alternative solution 😄  (same interesting idea)

**Comment by abdel-h66** [comment] 2023-11-04 19:33
I actually reported this one and worked on a solution that I shared on Slack. Not sure why @m-natarajan didn't include it :) could you double-check again please :)

**Comment by m-natarajan** [comment] 2023-11-05 21:32
Proposal by @abdel-h66 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a receipt is added to a Manual request, refreshing the page will cause the manual request process to be stuck.
### What is the root cause of that problem?
- When a receipt is added to a Manual request, we save it in a local file `(blob)`
- This allows the user to move back and fort between the `MoneyRequestAmountForm` and `MoneyRequestConfirmPage` and keep the receipt attached to the IOU request to be viewed.
- When the page is refreshed, the `IOU` will still have the local file data as receipt, but this file is no longer readable.
- When we try to read this file [here](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/iou/steps/MoneyRequestConfirmPage.js#L102)
https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/iou/steps/MoneyRequestConfirmPage.js#L102
- We will get an error and the Navigation will instantly take us back to the `MONEY_REQUEST` page.
- The issue will persist as long as there is an unreadable file in the `IOU` object
### What changes do you think we should make in order to solve the problem?
→ In the `useEffect` here that checks for the existence of the receipt (this logic was added to fix this [issue](https://github.com/Expensify/App/issues/28347))
→ we check If the receipt is a local file using
```js
const isLocalReceiptFile = receiptPath.startsWith('file://') || receiptPath.startsWith('blob:');
```
→ if this file could not be read, then we reset the money request receipt with
```js
IOU.setMoneyRequestReceipt('', '')
```
→  the final solution will be something like this
```js
            if (!file) {
                if(isLocalReceiptFile) {
                    IOU.setMoneyRequestReceipt('', '')
                    return;
                }
                Navigation.goBack(ROUTES.MONEY_REQUEST.getRoute(iouType.current, reportID.current));
            } else {
                const receipt = file;
                receipt.state = file && isManualRequestDM ? CONST.IOU.RECEIPT_STATE.OPEN : CONST.IOU.RECEIPT_STATE.SCANREADY;
                setReceiptFile(receipt);
            }
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by lschurr** [comment] 2023-11-06 16:44
@eVoloshchak could you take a look at the discussion on this GH?

**Comment by lschurr** [comment] 2023-11-09 16:49
Bump @eVoloshchak

**Comment by lschurr** [comment] 2023-11-11 21:36
Bumped in Slack as well - https://expensify.slack.com/archives/C01GTK53T8Q/p1699738567654619

**Comment by eVoloshchak** [comment] 2023-11-12 18:52
This has been resolved in https://github.com/Expensify/App/pull/30832

**Comment by lschurr** [comment] 2023-11-13 06:26
Ok, great! Closing this one out.

**Comment by DylanDylann** [comment] 2023-11-22 16:26
@lschurr We should reopen this one and close https://github.com/Expensify/App/issues/30984 and https://github.com/Expensify/App/issues/31721

**Comment by DylanDylann** [comment] 2023-11-23 13:45
Because @lschurr is OOO, @anmurali @zanyrenney Could you help to check [this comment](https://github.com/Expensify/App/issues/30884#issuecomment-1823091300) Ping you here because you are assigned to related issue

**Comment by DylanDylann** [comment] 2023-11-29 04:35
@eVoloshchak Could you check this issue? It happened for a long time and cause stuck in our App

**Comment by lschurr** [comment] 2023-12-01 06:56
Bump @eVoloshchak

**Comment by situchan** [comment] 2023-12-02 23:43
We should hold this for [money request route refactor](https://github.com/Expensify/App/issues/26538)

**Comment by DylanDylann** [comment] 2023-12-13 08:28
@lschurr This PR https://github.com/Expensify/App/pull/28618 is merged. Let's remove the hold label

**Comment by lschurr** [comment] 2023-12-13 16:16
I've removed the hold and opened for proposals again. Could you take a look at this one @eVoloshchak?

**Comment by DylanDylann** [comment] 2023-12-14 09:55
@0xmiroslav Because we have a big update on the request money flow, I updated the [proposal](https://github.com/Expensify/App/issues/30884#issuecomment-1793453231)

**Comment by lschurr** [comment] 2023-12-18 15:48
@eVoloshchak could you review?

**Comment by eVoloshchak** [comment] 2023-12-22 14:49
Can also reproduce the issue, thanks
@DylanDylann's [proposal](https://github.com/Expensify/App/issues/30884#issuecomment-1793453231) looks good to me, I think we should proceed with it. We should redirect user to the "Upload receipt" page in case the receipt file isn't available, which is @DylanDylann's alternative solution

🎀👀🎀 C+ reviewed!

**Comment by DylanDylann** [comment] 2023-12-25 09:37
@eVoloshchak The PR is ready for review: https://github.com/Expensify/App/pull/33562

**Comment by situchan** [comment] 2024-01-12 19:58
There's [regression](https://github.com/Expensify/App/pull/33562#issuecomment-1889399641)

<img width="327" alt="regression" src="https://github.com/Expensify/App/assets/108292595/0e20c195-5c1c-4c1b-9b96-9b87059f1252">

**Comment by eVoloshchak** [comment] 2024-01-16 14:31
cc: @DylanDylann, could you look into this please?

**Comment by lschurr** [comment] 2024-01-17 20:41
Has the regression been fixed @DylanDylann @eVoloshchak?

**Comment by DylanDylann** [comment] 2024-01-18 03:39
I will create PR to fix it

**Comment by DylanDylann** [comment] 2024-01-18 09:48
@eVoloshchak  To fix this dependency cycle, I think we should move navigateToStartStepIfScanFileCannotBeRead to IOU.js file. What do you think about it?

**Comment by lschurr** [comment] 2024-01-19 23:26
Could you weigh in here @eVoloshchak?

**Comment by lschurr** [comment] 2024-01-22 17:11
Any update on the regression here @DylanDylann @eVoloshchak?

**Comment by eVoloshchak** [comment] 2024-01-23 19:41
@DylanDylann, let's proceed with the first option here, the second would require duplicating the `onFailure` logic
Could you spin-up the PR?

**Comment by eVoloshchak** [comment] 2024-01-24 21:05
@DylanDylann, let's just revert the function back to vanilla JS. Hold on https://github.com/Expensify/App/issues/24926 will be removed on Jan 26, but it's a huge file, and a migration to TS will take time. Let's get rid of this warning, the function is pretty small, it won't be hard to convert it to TS again

**Comment by DylanDylann** [comment] 2024-01-25 06:09
@eVoloshchak The PR is ready for review: https://github.com/Expensify/App/pull/35127

**Comment by lschurr** [comment] 2024-02-04 19:20
@eVoloshchak @DylanDylann - could you work through the new checklist for this one?

**Comment by eVoloshchak** [comment] 2024-02-06 14:36
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that has caused this, this is an edge case that was missed during the initial implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: we already have the necessary item in the reviewer checklist: " I added steps to cover failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)"
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? It's an edge case, but it's an edge case that completely crashes the app, I'd call that impactful

**Regression Test Proposal**

1. Open a chat
2. Create a manual request thought the chat plus icon (not the FAB)
3. Enter an amount and click Next
4. Click the three dots on the top, and attach a receipt
5. Refresh the page
6. The page should go back to the first step, autofilled with the previous amount.
7. Click next
8. Verify that you're able to continue to the request information page

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2024-02-07 14:17
This is ready for payment, @lschurr, could you post the payment summary please?
Noting this has caused a regression, the amount should be $250

**Comment by lschurr** [comment] 2024-02-07 16:42
Yep, I will review and post payment summary today.

**Comment by lschurr** [comment] 2024-02-07 17:07
Payment summary:

- Bug reporter: @abdel-h66 $50 to be paid in Upwork
- Contributor: @DylanDylann $250 to be paid in Upwork
- Contributor+: @eVoloshchak $250 to be paid in Newdot

**Comment by lschurr** [comment] 2024-02-07 17:15
Added new QA test request: https://github.com/Expensify/Expensify/issues/367651

Closing out this issue.

**Closed by lschurr** 2024-02-07 17:15 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-02-09 16:24
$250 approved for @eVoloshchak based on summary above.
