### ISSUE TITLE
Hybrid - Android - Room - Keyboard is not opened when creating a new room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53188] opened 2024-11-27 07:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5267320&group_by=cases:section_id&group_order=asc&group_id=229067
**Email or phone of affected tester (no customers):** ibellicotest+43@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on the FAB and select "Start Chat"
3. Tap on "Room"
4. Add a name for the room and tap on "Create Room"
5. Verify you land on the new created room and the keyboard is opened.

## Expected Result:
After creating a new room and landing on chat, the keyboard should be opened.

## Actual Result:
Keyboard is not opened after creating a new room and landing on chat.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e4fbbfc7-6945-4b64-8287-7284cc04ebe6

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mjasikowski** [comment] 2024-11-27 09:05
trying to reproduce locally

**Comment by mountiny** [comment] 2024-11-27 11:13
Discussing in the slack thread https://expensify.slack.com/archives/C01GTK53T8Q/p1732693067945429, I think we can demote this one and keep looking into it as not a blocker

**Comment by mjasikowski** [comment] 2024-11-27 15:34
Can't reproduce this on HybridApp dev, the keyboard pops up normally.

**Comment by garrettmknight** [comment] 2024-11-27 18:56
I also can't repro on the latest version. Closing.

**Closed by garrettmknight** 2024-11-27 18:56 UTC
Labels: Engineering, Daily, Bug
