### ISSUE TITLE
[$250] mWeb/Safari - Navigation - After inviting a member navigating back takes you back to members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44035] opened 2024-06-19 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to Workspace > Members
2. Invite a member
3. On the members page click the back button on top
4. Notice you are navigated to the workspace page
5. Now click the back button found on the workspace page
Notice you are returned to the members page again

## Expected Result:
Clicking back takes you to the Workspace list page

## Actual Result:
Clicking the back button returns you to the members page again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2167582e-951d-414d-aa9d-e7f8f45523c9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d265064621c334d0</li>
        <li>Upwork Job ID: 1805278189475123074</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 102913998</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by truph01** [comment] 2024-06-20 03:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking the back button returns you to the members page again

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
- After clicking on "Invite" button in WorkspaceInviteMessagePage, we call:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L117-L118
leads to there are two ```CentralPaneNavigator``` in the route stacks.

- So when we navigate back, it takes we back to member page.

### What alternative solutions did you explore? (Optional)
- We can remove:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L118

**Comment by truph01** [comment] 2024-06-20 03:39
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
Clicking the back button returns you to the members page again

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
- After clicking on "Invite" button in WorkspaceInviteMessagePage, we call:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L117-L118
leads to there are two ```CentralPaneNavigator``` in the route stacks.

- So when we navigate back, it takes we back to member page.

### What alternative solutions did you explore? (Optional)
- We can update:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L117-L118
to:
```
        Navigation.dismissModal()
```

**Comment by zanyrenney** [comment] 2024-06-24 16:33
tried on web, can't repro but i think this is just on safari. mobile web as per the desc.

**Comment by zanyrenney** [comment] 2024-06-24 16:33
Adding external to investigate!

**Comment by zanyrenney** [comment] 2024-06-24 16:34
hey @Pujan92 please explore the proposal above from @truph01 !

**Comment by Pujan92** [comment] 2024-06-26 11:17
Thanks @zanyrenney, I will review the proposal max by tomorrow.

**Comment by Pujan92** [comment] 2024-06-27 11:44
> leads to there are two CentralPaneNavigator in the route stacks.

@truph01 Can you plz explain again to help me understand your RCA

**Comment by truph01** [comment] 2024-06-27 12:04
- When we call ```Navigation.navigate(ROUTES.WORKSPACE_MEMBERS.getRoute(route.params.policyID))``` in:
https://github.com/Expensify/App/blob/29e4c5488d3feafae3bdc20a424628b21831dc88/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L117-L118, the ```action``` in this:
https://github.com/Expensify/App/blob/5e464eaa3e7614e6f17007e05203e184c275faf2/src/libs/Navigation/linkTo/index.ts#L216 will be:
```
{
    "type": "PUSH",
    "payload": {
        "name": "FullScreenNavigator",
        "params": {
            "initial": true,
            "screen": "Workspace_Members",
            "params": {
                "policyID": "66A1FB0AB335B7F2"
            },
            "path": "/settings/workspaces/66A1FB0AB335B7F2/members"
        }
    }
}

```

- As you can see, the new ```FullScreenNavigator``` is added to the stacks.

- Note that, in my proposal, I wrote (my bad):

> leads to there are two CentralPaneNavigator in the route stacks.

but it should be:

> leads to there are two FullScreenNavigator in the route stacks.

**Comment by Pujan92** [comment] 2024-06-28 10:41
Thanks @truph01, I think we can proceed with @truph01's [proposal](https://github.com/Expensify/App/issues/44035#issuecomment-2179747116) to dismiss the modal instead of navigating to the members page which leads to pushing the second FullScreenNavigator.

🎀👀🎀 C+ reviewed

**Comment by truph01** [comment] 2024-07-01 08:28
@Pujan92 PR https://github.com/Expensify/App/pull/44668 is ready

**Comment by Pujan92** [comment] 2024-07-03 09:22
@zanyrenney can we assign a new internal engineer to review [PR](https://github.com/Expensify/App/pull/44668) as I think @thienlnam is OOO until 8th July?

**Comment by thienlnam** [comment] 2024-07-11 21:06
Merged

**Comment by Pujan92** [comment] 2024-07-29 17:20
### Regression Test Steps

1. Go to Workspace > Members and invite a member
2. After inviting, you will be landed on the members page
3. Click back button and it will navigate to the workspace details page
4. Now again click the back button
5. Verify that you are navigated to Workspace list page and it doesn't take you to the members page

**Comment by Pujan92** [comment] 2024-07-29 18:24
@zanyrenney Bump for the payment

**Comment by zanyrenney** [comment] 2024-08-01 12:30
Thanks @Pujan92

**Comment by zanyrenney** [comment] 2024-08-01 12:33
**payment summary**

paid $250 to @truph01 via Upwork. 
@Pujan92 is owed $250 (paid via ND) - please request.

**Closed by zanyrenney** 2024-08-01 12:33 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-08-01 20:15
$250 approved for @Pujan92
