### ISSUE TITLE
[$500] Assign Task - Cancelled task displays in 1:1 DM preview but disappears when open the 1:1 DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26701] opened 2023-09-04 18:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Tap on any conversation with other user
3. Tap on plus bottom next to compose box
4. Tap on "Assign Task"
5. Write any title and tap on Next button
6. Select "Assign to me"
7. Tap on Confirm task button
8. Navigate back to LHN
9. Tap on created task DM in LHN
10. Tap on 3 dots button in header
11. Tap on Cancel
12. Navigate back to LHN
13. Observe the preview message in conversation from step 2
14. Tap on this conversation and observe last message in chat

## Expected Result:
Cancelled task should be displayed in 1:1 DM chat

## Actual Result:
Cancelled task displays in 1:1 DM preview but disappears when open the 1:1 DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/23c34f9d-b41f-4137-8ada-c72bfe370083

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ba780f7ccfd3ada</li>
        <li>Upwork Job ID: 1698966116744380416</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-09-04 19:44
## Proposal

### Please state again the problem we are trying to solve in this issue.
Cancelled task displays in 1:1 DM preview but disappears when open the 1:1 DM.

### What is the cause of this issue?
When cancel task, we does not set parent report action.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/libs/actions/Task.js#L764-L827
So `ReportActionsUtils.isDeletedParentAction` returns `false`, since report action in DM chat does not have `childVisibleActionCount` field.
https://github.com/Expensify/App/blob/cb98bec57e43cdfbeb356b342054a53e47e59758/src/libs/ReportActionsUtils.js#L67-L69
Therefore cancelled task disappear when open the 1:1 DM.

### What changes do you think we should make to solve the problem?
When complete or reopen task, we are setting parent report action.
We can do same when cancel task.
```js
    // Update optimistic data for parent report action
    const optimisticDataForParentReportAction = ReportUtils.getOptimisticDataForParentReportAction(taskReportID, optimisticCancelReportAction.created, CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD);
    if (!_.isEmpty(optimisticDataForParentReportAction)) {
        optimisticData.push(optimisticDataForParentReportAction);
    }

    // Multiple report actions can link to the same child. Both share destination (task parent) and assignee report link to the same report action.
    // We need to find and update the other parent report action (in assignee report). More info https://github.com/Expensify/App/issues/23920#issuecomment-1663092717
    const assigneeReportAction = ReportUtils.getTaskParentReportActionIDInAssigneeReport(ReportUtils.getReport(taskReportID));
    if (!_.isEmpty(assigneeReportAction)) {
        const optimisticDataForClonedParentReportAction = ReportUtils.getOptimisticDataForParentReportAction(
            taskReportID,
            optimisticCancelReportAction.created,
            CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
            assigneeReportAction.reportID,
            assigneeReportAction.reportActionID,
        );
        if (!_.isEmpty(optimisticDataForClonedParentReportAction)) {
            optimisticData.push(optimisticDataForClonedParentReportAction);
        }
    }
```
### What alternative solutions have you investigated? (Optional)
None.

**Comment by s77rt** [comment] 2023-09-05 17:49
I'm not sure about the expected behaviour, whether we should show the cancelled task or keep it hidden and update the last message of the task parent.

I have asked on Slack https://expensify.slack.com/archives/C01GTK53T8Q/p1693936063368119. cc @laurenreidexpensify

**Comment by thienlnam** [comment] 2023-09-05 17:50
Adding a note here - but all cancel task bugs should be closed for https://github.com/Expensify/App/issues/19504 at this time 

https://expensify.slack.com/archives/C049HHMV9SM/p1692812499109599

**Comment by thienlnam** [comment] 2023-09-05 17:50
Actually, this is slightly different so going to put this on hold instead of closing it

**Comment by laurenreidexpensify** [comment] 2023-09-15 16:50
still held on #19504 right @thienlnam ?

**Comment by thienlnam** [comment] 2023-09-18 07:16
Yup correct - last PR for that is in review and close to being merged!

**Comment by laurenreidexpensify** [comment] 2023-09-20 15:04
still held on https://github.com/Expensify/App/issues/19504

**Comment by thienlnam** [comment] 2023-09-25 03:24
Held PR is merged! Let's see if this is still reproducible

**Comment by s77rt** [comment] 2023-09-25 15:37
This seems to be fixed. I noticed that the parent last message is not updated though. Should this be fixed here?
<img width="1840" alt="Screenshot 2023-09-25 at 4 26 19 PM" src="https://github.com/Expensify/App/assets/16493223/22132f25-7131-4b4d-90c7-426db3092d11">

**Comment by laurenreidexpensify** [comment] 2023-09-26 05:03
@thienlnam what do you think - https://github.com/Expensify/App/issues/26701#issuecomment-1733971814?

**Comment by thienlnam** [comment] 2023-09-26 08:49
That looks like a different bug than the one reported here - let's close this as I believe there might be another bug reported for that specific issue

**Closed by thienlnam** 2023-09-26 08:49 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
