### ISSUE TITLE
Web - App crashes if splitted money with invalid email user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21675] opened 2023-06-27 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Click on + icon and click on split bill
3. Enter any amount and enter any invalid email user
4. Split the bill and notice the app crashes

## Expected Result:
 App should not crash if splitted money with invalid email user
 
## Actual Result:
App crashes if splitted money with invalid email user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a08771f9-a8f8-4768-8085-64a922c748bc

https://github.com/Expensify/App/assets/93399543/d6e3bb67-17ec-43f2-883a-80523dc8b682

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687508140699739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-27 13:56
This is a dupe of https://github.com/Expensify/App/issues/20105

**Comment by JmillsExpensify** [comment] 2023-07-05 12:44
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:03
Woah, nice bug report. I can reproduce, opening up to the community.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:04
Ooops, by which I mean, it's a duplicate linked above. Closing.

**Closed by JmillsExpensify** 2023-07-12 13:04 UTC
Labels: Daily, Bug
