### ISSUE TITLE
[$500] Split - Contact method of the participants is shown in Merchant instead of display name

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29858] opened 2023-10-18 11:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR:** https://github.com/Expensify/App/pull/29449

**Version Number:** v1.3.86-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Manual.
3. Select Split with a few participants with display name.
4. Create the bill split.
5. Click on the bill split preview > Show more.

## Expected Result:
Display name of the participants will be displayed in the Merchant.

## Actual Result:
Contact method of the participants is displayed in the Merchant.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/3cd10f75-d226-4752-9e43-0076d61c9712

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d28ed12ed77a99a</li>
        <li>Upwork Job ID: 1714607183948734464</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-10-18 12:24
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Split - Contact method of the participants is shown in Merchant instead of display name

### What is the root cause of that problem?

In 

https://github.com/Expensify/App/blob/a24e6a09b86f703f8ccf2e8f4bb29a4aabd6c761/src/libs/actions/IOU.js#L910-L912

We are using `participant.login` instead of `participant.text`, which is displaying contact method.

### What changes do you think we should make in order to solve the problem?

Use `participant.text` instead of `participant.text` in the given line.
And maybe somehow use current user display name instead of currentUserLogin.

### What alternative solutions did you explore? (Optional)

**Comment by ayazalavi** [comment] 2023-10-18 12:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When adding a money request manually and selecting participants, the report details show the participants' email addresses in the merchant field.

### What is the root cause of that problem?
Root cause is that when adding transaction for split bill then following line of code uses user's login for generating Bill Split with string.

https://github.com/Expensify/App/blob/a24e6a09b86f703f8ccf2e8f4bb29a4aabd6c761/src/libs/actions/IOU.js#L910-L912

### What changes do you think we should make in order to solve the problem?
Use [getDisplayName](https://github.com/Expensify/App/blob/a24e6a09b86f703f8ccf2e8f4bb29a4aabd6c761/src/libs/actions/PersonalDetails.js#L42)`

so instead of `currentUserLogin` we need to use `getDisplayName(currentUserLogin, currentUserPersonalDetails)`

and instead of `participant.login` we need to use `getDisplayName(participant.login, participant)`

```
    const formattedParticipants = isOwnPolicyExpenseChat
        ? [currentUserLogin, ReportUtils.getReportName(splitChatReport)]
        : Localize.arrayToString([getDisplayName(currentUserLogin, currentUserPersonalDetails), ..._.map(participants, (participant) => getDisplayName(participant.login, participant) || '')]);
```

### What alternative solutions did you explore? (Optional)
We also need to ensure that if a user updates their display name from their profile, the transaction gets updated with the new display name. To achieve this, we should generate the formatted string as mentioned above before displaying the data, other than storing it in Onyx as follows:

https://github.com/Expensify/App/blob/a24e6a09b86f703f8ccf2e8f4bb29a4aabd6c761/src/libs/actions/IOU.js#L914-L927

**Comment by shubham1206agra** [comment] 2023-10-20 12:39
@zanyrenney This is still reproducible
You have to complete the split request first
Then we have to check in preview

<img width="376" alt="Screenshot 2023-10-20 at 6 08 28 PM" src="https://github.com/Expensify/App/assets/58412969/7aedd2da-b381-4ad5-a33e-9c7e8dba75de">

**Comment by lanitochka17** [comment] 2023-10-21 16:51
Issue is still reproducible on build 1.3.88-3


https://github.com/Expensify/App/assets/78819774/db3397f3-8c18-4341-a44d-3c2b72857b22

**Comment by zanyrenney** [comment] 2023-10-24 13:20
Thanks for the additional step @shubham1206agra

**Comment by zanyrenney** [comment] 2023-10-24 13:21
@ntdiary please can you review the initial proposals we have received?

**Comment by zanyrenney** [comment] 2023-10-27 13:15
Thanks @ntdiary I will ask for a second opinion here!

**Comment by zanyrenney** [comment] 2023-10-30 18:51
Checking here - https://expensify.slack.com/archives/C01GTK53T8Q/p1698691907199119

**Comment by situchan** [comment] 2023-10-30 19:18
We had same discussion - https://github.com/Expensify/App/issues/25885#issuecomment-1699762925
Maybe related to https://github.com/Expensify/Expensify/issues/301281

**Comment by DylanDylann** [comment] 2023-10-31 05:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- There are 3 issues that I found related to this split bill:
1. The behavior that is  mentioned by @ntdiary  above: 
> when I reopen the split report and detail page, the Merchant field always shows Request, even if I enter demo when creating it
2. The displayed merchant data and the actual merchant data sent are different, that can make user confuse
3. It is the issue that mentioned in this thread: Split - Contact method of the participants is shown in Merchant instead of display name
### What is the root cause of that problem?
1. When calling API 'SplitBill', we are just creating the optimisticData.merchant, but does not pass this merchant data to API, 

2. Suppose the 1st issue is fixed (just to reduce the complexity): When going to [MoneyRequestConfirmPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestConfirmPage.js), we are always displaying the merchant field as "Request", but then the user clicks on the submit button, the actual data is passed to API 'SplitBill' is https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/libs/actions/IOU.js#L927

3. We are using the below logic to generate merchant with string, that uses participant.login:
https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/libs/actions/IOU.js#L915-L917
### What changes do you think we should make in order to solve the problem? 

1. We should pass the merchant data to 'SplitBill' API, this one is straightforward to implement.
2. When clicking on "Add to split" button to navigate to [MoneyRequestConfirmPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestConfirmPage.js), we need to update the iou data by updating the below logic:
https://github.com/Expensify/App/blob/5b5d465f9d39e01468db731ad5d278b026a8a565/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L77-L80
to
```
   const navigateToConfirmationStep = (moneyRequestType) => {
        IOU.setMoneyRequestMerchant(getSplitBillMerchant(props.iou.participants))
        ...
    };
```
- ```getSplitBillMerchant``` is util function that we use to get the merchant and based on what we did to get the LHNRow and Report`s header in case of group chat. It can be something like:
```
  const getSplitBillMerchant = (participants, currentUserLogin, isOwnPolicyExpenseChat) => {
        if (isOwnPolicyExpenseChat) return [currentUserLogin, ReportUtils.getReportName(splitChatReport)];
        const participantPersonalDetails = OptionsListUtils.getPersonalDetailsForAccountIDs(participants, allPersonalDetails);
        const displayNamesWithTooltips = getDisplayNamesWithTooltips(participantPersonalDetails, true);
        return getDisplayNamesStringFromTooltips(displayNamesWithTooltips);
    };
```
3. Using the above ```getSplitBillMerchant``` fixed this issue as well

### What alternative solutions did you explore? (Optional)
- NA

**Comment by shubham1206agra** [comment] 2023-10-31 13:33
@aimane-chnaif I just checked
This is not a dupe

**Comment by DylanDylann** [comment] 2023-10-31 13:41
@aimane-chnaif My proposal mention 3 related issue https://github.com/Expensify/App/issues/29858#issuecomment-1786463262 So should we need to fix each issue in separate PR or wrap these into one?

**Comment by zanyrenney** [comment] 2023-11-02 14:41
Hmm, I think this is a dupe of https://github.com/Expensify/App/issues/29691

I see the comment above, but closing on these grounds.

**Closed by zanyrenney** 2023-11-02 14:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by DylanDylann** [comment] 2023-11-02 14:46
@zanyrenney it's not a dupe. Please help check my proposal for more detail.
- The https://github.com/Expensify/App/issues/29691 is: When calling API 'SplitBill', we are just creating the optimisticData.merchant, but does not pass this merchant data to API.
- The https://github.com/Expensify/App/issues/29858 is: Split - Contact method of the participants is shown in Merchant instead of display name

**Comment by situchan** [comment] 2023-11-02 14:47
@DylanDylann please check https://github.com/Expensify/App/issues/29858#issuecomment-1785886524.
This will be handled internally.
cc: @youssef-lr

**Comment by DylanDylann** [comment] 2023-11-02 14:50
@situchan My proposal mentioned 3 related issues. What issue that you mentioned in "This will be handled internally"?

**Comment by DylanDylann** [comment] 2023-11-02 14:53
@situchan Yeah. Many thanks. But I have a minor question that, In the [link](https://github.com/Expensify/App/issues/29858#issuecomment-1785886524) you mentioned, i just can access the https://github.com/Expensify/App/issues/25885, and the issue mentioned in that does not appear and does not relate to this issue.

**Comment by youssef-lr** [comment] 2023-11-03 00:49
@DylanDylann this is getting fixed here https://github.com/Expensify/App/pull/30721

**Comment by ayazalavi** [comment] 2023-11-03 02:57
@ntdiary My proposal also mentioned an issue that if user updates his account details then merchant field does not gets updated with his new email address or display name what ever we need to show there.
