### ISSUE TITLE
[$500] Details page - User navigates to previously opened report when refresh the user details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28484] opened 2023-09-29 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
Workspace have few members
1. Navigate to staging.new.expensify.com
2. Open #announce room
3. Click on the header of the conversation
4. Click on one of the members to open Detail page
5. Refresh the page

## Expected Result:
After refreshing the page User should remain on #announce room

## Actual Result:
User navigates to previously opened report when refresh the user Details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6aae5bde-6e50-4c09-afda-4bba3896754e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3385ef547c9c076</li>
        <li>Upwork Job ID: 1709565695783854080</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-29 18:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User navigates to previously opened report when refresh the user details page

### What is the root cause of that problem?

When the route does not have a report ID set, we try to find the latest read report. 
The problem is that when a report has no actions (beside the creation action) the last read value is never updated. which means in the case of creating a workspace. 

We will have the report `#admin` and `#announce` created prettty much around the same time, so when the user navigate to a link that does not contain a report ID, they will be redirected to the latest created report and not the latest report they have viewed, and that's due to the value of the lastTimeRead never being updated after the creation of a report. 

### What changes do you think we should make in order to solve the problem?

My suggestion would be updating the value of lastRzeadTime whenever we view an empty report. By checking that it only has one action and that action is the creation action. 

The action reading logic is handled is this useEffect

https://github.com/Expensify/App/blob/5fd69da1cf05fef1a39fb64937ef15b0e8f163e2/src/pages/home/report/ReportActionsList.js#L152-L172

We can do something like this 

```
        const reportHasCreatedActionOnly = isCreatedAction(sortedReportActions[0]);

        if (ReportUtils.isUnread(report) || reportHasCreatedActionOnly) {
            if (scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD) {
                console.log({readNewestAction: report.reportID})
                Report.readNewestAction(report.reportID);
            } else {
                readActionSkipped.current = true;
            }
        }
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by zanyrenney** [comment] 2023-10-02 16:25
I don't understand this bug report and I am unable to reproduce this. I think this is the expected behaviour.

**Comment by abdel-h66** [comment] 2023-10-02 16:30
It usually happens on new accounts, where all the reports have empty messages. 

there are different ways to replicate, but the easiest would be trying the steps on a newly created account with a fresh workspace.

**Comment by zanyrenney** [comment] 2023-10-04 13:46
Thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-10-04 18:38
Root Cause & fix doesn't seem to be right, I can reproduce on a old account too. Recording from the bug description is not a new account either!

**Comment by abdel-h66** [comment] 2023-10-04 18:50
Yes it can be reproduced on old accounts as well, if you look closely at the report recording, you will notice that the `#announce` report does not have any messages, however the `#admin` does have one.  And since the `lastReadTime` for is the time the report was created, compared to the admin page. 

Given that the redirect logic is based on the `lastReadTime` of a report when the `reportID` is not present in the route. And the `#announce` report `lastReadTime` is older than the `#admins` report (it's older because the `#admin` report has a new message.)

My suggestion was to update the `lastReadTime` every time we open an empty report, instead of leaving it at the default, which is the creation time.

**Comment by zanyrenney** [comment] 2023-10-10 12:18
@Santhosh-Sellavel please can you review the proposals?

**Comment by Santhosh-Sellavel** [comment] 2023-10-10 18:27
Maybe this is something we should discuss on Expensify open source to weigh in.

@abdel-h66 
> I think we should update the lastReportTime even when the report has all the messages read.

This is not the ideal case, maybe lets weigh in from the community

@dukenv0307 / @abdel-h66 

Anyone of you Please start a thread in P/S Format? Post the Slack link here and tag me. Let us all discuss to get a consensus

**Comment by zanyrenney** [comment] 2023-10-13 13:56
After re-reviewing this, I think it is an abnormal workflow and not a user-reported bug so we will close this out. Thank you!

**Closed by zanyrenney** 2023-10-13 13:56 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
