### ISSUE TITLE
[HOLD for payment 2024-09-06] [$250] iOS - Wallet - Wallet page freezes after deleting bank account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48298] opened 2024-08-29 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+ck829@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app & create a new account
2. Naviagate to Settings >> Wallet >> Add bank account
3. Go through the Plaid flow (Choose Chase bank)
4. Once user navigate back to ND app, select Plaid Saving account option
5. Tap on continue button on Personal bank account added modal & go back to wallet page
6. Tap on 3 dot menu >> delete option >> confirm delete bank account (Note: bank account gets dfeleted)
7. Tap on + add bank account or enable wallet or try clicking the back button

## Expected Result:
Wallet page should not freeze on deleting the bank account
Tapping on either add bank account, enable wallet should open plaid flow & clicking back button navigate to settings page

## Actual Result:
Wallet page freezes after deleting bank account. Nothing happens on tapping add bank account or enable wallet or the back button

Note: User has force kill app for the options to work in Wallet page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f014f3c7-26a7-4495-9033-a4152d444f2c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01390fdf36b89f8f00</li>
        <li>Upwork Job ID: 1829450116473018676</li>
        <li>Last Price Increase: 2024-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103754230</li>
<li>allgandalf | Contributor | 103754233</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by Beamanator** [comment] 2024-08-29 22:18
Looks front-end only b/c it's not reproducible in web & it freezes iOS even when deleting offline

**Comment by Beamanator** [comment] 2024-08-29 22:47
This is reproducible in multiple workflows - the point is that you have to open the 3-dot menu, then click "Delete" to open the "Are you sure" modal -> after that, if you cancel or delete or press away, the app "freezes"

I believe the problem is that the first modal hasn't been closed somehow

**Comment by mountiny** [comment] 2024-08-30 09:24
@daledah lets CP the fix now and let that PR go through the normal process. Can you raise a PR please?

**Comment by Beamanator** [comment] 2024-08-30 18:04
PR was CP'd, testing on staging now

**Comment by Beamanator** [comment] 2024-08-30 18:08
Fixed on staging -  just tested iOS native & web 👍

**Comment by CortneyOfstad** [comment] 2024-09-06 18:09
Hello! Just getting confirmation on payment as I have not had two PRs tied to the same bug/issue with two different creators. Will follow up and get payment out ASAP once this is confirmed by the team. Thanks for your patience!

**Comment by CortneyOfstad** [comment] 2024-09-06 18:49
Thanks for your patience! So it was decided to award the following amounts:

@daledah — $125 for creating a PR that laid the ground work for the solution to be implemented via another PR
@allgandalf — $250 for creating the PR that solved the issue
@eh2077 — $250 for reviewing (to be paid via NewDot)

I am going to send out the manual requests now via Upwork for the two PRs 👍

**Comment by CortneyOfstad** [comment] 2024-09-06 18:51
@eh2077 — looks like a contract was created for you in Upwork automatically by mistake, but I have cancelled that in favor of you being paid via NewDot. Thanks!

**Comment by JmillsExpensify** [comment] 2024-09-09 16:59
$250 approved for @eh2077

**Comment by CortneyOfstad** [comment] 2024-09-09 20:15
## Updated Payment Summary

@allgandalf — paid $250 via Upwork
@daledah — paid $125 via Upwork
@eh2077 — paid $250 via NewDot

**Closed by CortneyOfstad** 2024-09-09 20:15 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
