### ISSUE TITLE
[$500]  Request money - Text input isn't auto focused after screen transition ends

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27450] opened 2023-09-14 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27294
## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Press FAB >> Request money >> Distance
Choose Start & End locations >> Next

## Expected Result:
Verify that the text input is auto focused after screen transition ends

## Actual Result:
Text input isn't auto focused after screen transition ends

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5f5d42d8-cf57-4eb8-99ce-d75c0882f788

![Bug6200485_focus_2](https://github.com/Expensify/App/assets/78819774/9a41c8c3-93b4-4a9d-b525-dff77c7ccbb8)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bfadaee4d9a59119</li>
        <li>Upwork Job ID: 1702347116753686528</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-14 15:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text input isn't auto focused after screen transition ends when creating / editing a waypoint in the distance request waypoint editor

### What is the root cause of that problem?
The screen transition end doesn't always fire except at the top level of the stack.

### What changes do you think we should make in order to solve the problem?
We are now using a new approach to autofocus text inputs according to https://expensify.slack.com/archives/C01GTK53T8Q/p1694660990479979

Implement these changes in AddressSearch.

### What alternative solutions did you explore? (Optional)
None.

**Comment by dev3606** [comment] 2023-09-14 16:21
This works well in my end.
What's wrong with you?
Thanks.

**Comment by PiyushChandra17** [comment] 2023-09-14 16:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text input isn't auto focused after screen transition ends

### What is the root cause of that problem?
We are using `onEntryTransitionEnd` on ScreenWrapper component.

https://github.com/Expensify/App/blob/95c9e4743f44ca42ece2c6ac56259b911d5feafc/src/pages/iou/WaypointEditor.js#L163

`onEntryTransitionEnd` is only fired for the top card in the stack, and therefore does not fire on the new top card when popping a card off the stack.

### What changes do you think we should make in order to solve the problem?
We need to add useFocusEffect hook and remove `onEntryTransitionEnd` from `ScreenWrapper` in `WaypointEditor` component.

```
const focusTimeoutRef = useRef(null);
useFocusEffect(useCallback(() => {
    focusTimeoutRef.current = setTimeout(textInputRef.current.focus, CONST.ANIMATED_TRANSITION);
    return () => {
        if (!focusTimeoutRef.current) {
            return;
        }
        clearTimeout(focusTimeoutRef.current);
    };
}, []));
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by dev3606** [comment] 2023-09-14 16:53
Based on the provided code, it seems that the problem is related to the use
of the useFocusEffect hook and the onEntryTransitionEnd function in the
ScreenWrapper component of the WaypointEditor component. To solve this
problem, the following changes should be made:
Remove the onEntryTransitionEnd function from the ScreenWrapper component.
This function is no longer needed if we're using the useFocusEffect hook.

Import the useFocusEffect hook from the appropriate library or module.

Add the useFocusEffect hook inside the WaypointEditor component and wrap it
around the code that involves focusing on the textInputRef.current element.

Thanks.
Kevin

**Comment by dev3606** [comment] 2023-09-14 16:54
But I don't want get pay via a upwork.
So sorry.
Kevin

**Comment by sakluger** [comment] 2023-09-14 17:22
This is a duplicate of https://github.com/Expensify/App/issues/27202.

**Closed by sakluger** 2023-09-14 17:22 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by dev3606** [comment] 2023-09-14 17:24
Thanks a lot.

**Comment by akinwale** [comment] 2023-09-14 17:32
> This is a duplicate of #27202.

@sakluger This deals with the screens for picking the waypoints, while #27202 deals with the screen for picking the target workspace, so I'd say they're different.
