### ISSUE TITLE
[HOLD #12046] Feature Request : not hide Keyboard  when click on chat with your specialist reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11953] opened 2022-10-18 02:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem: 
Keyboard hides click on chat with your specialist

## Solution:
We should not hides Keyboard  click on chat with your specialist

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196322185-8c9f1fbf-c017-4012-8ea1-a6edddaa34c5.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665637839530719?thread_ts=1665033893.404679&cid=C01GTK53T8Q

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-10-18 17:01
Checking on internally here https://expensify.slack.com/archives/C07F03W66/p1666112472276209?thread_ts=1665510343.387969&cid=C07F03W66

**Comment by mallenexpensify** [comment] 2022-10-24 16:37
Gonna close this for now as I'm unable to reproduce, please comment and/or reopen if anyone is able to repro with 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/22508304/197579025-c471d94c-565b-4eeb-8e92-38b25d941515.png">

**Comment by mallenexpensify** [comment] 2022-10-24 16:54
My mistake, I thought a Guide was sending the "Chat with your specialist" link but it's coming from Concierge.   And.. when I get the message, I'm unable to click the link, when I try to click it, nothing happens.  @gadhiyamanan @kavimuru can you try to reproduce and let me know what you're finding?  I've asked here too
https://expensify.slack.com/archives/C01GTK53T8Q/p1666630199231519?thread_ts=1666270549.878679&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2022-10-26 21:37
Thanks @kavimuru ,  this flow is particularly janky.  If you click a link in the app to a chat in the app, you shouldn't be taken OUT of the app.  Also... the title of this GH is a different problem :( 
Chatting more about in the #expensify-open-source https://expensify.slack.com/archives/C01GTK53T8Q/p1666818969906699?thread_ts=1666270549.878679&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2022-10-27 16:25
OK... so the other problem should be being handled in this issue https://github.com/Expensify/App/issues/12046
I'm going to put this issue on hold, pending the above because, when I click "chat with your specialist" I'm being sent to a different platform or tab.  Once we're not doing that we'll check to see if the keyboard shows or not. (I think that makes sense, comment here if not)

**Comment by mallenexpensify** [comment] 2022-11-07 17:11
Holding on #12046

**Comment by mallenexpensify** [comment] 2022-11-09 02:18
Reassigning as I'm heading OOO for a month. bumping back to weekly cuz it's on hold.

**Comment by abekkala** [comment] 2022-11-17 16:06
oh hold not overdue

**Comment by abekkala** [comment] 2022-11-29 18:48
@ctkochan22 I left a comment on [this GH ](https://github.com/Expensify/App/issues/12046)
As I believe this one was placed on HOLD for that one. But when I test it's still behaving in a way that I don't think it should. 

Does this one need to be taken off hold as the fix for that one did not resolve this one?

**Comment by ctkochan22** [comment] 2022-11-30 05:06
Ah okay, let me take a look. I'm a bit all over the place htis week bc of covid, but I'll get to this as soon as i can. Otherwise you can drop in engineering chat to recuirt someone else in the meantime

**Comment by abekkala** [comment] 2022-12-08 20:24
@ctkochan22 have you had a chance to take a peak at this.

I just tried recreating again and while I'm not receiving the same outcome above (keyboard being hidden) I'm being routed to an archived room that I can't start a conversation in.

**Comment by abekkala** [comment] 2022-12-20 13:04
@ctkochan22 I'm going to close this one as I'm not receiving the same outcome as before.
When I do it the keyboard is not hidden and I'm brought to the room to chat as normal

**Closed by abekkala** 2022-12-20 13:04 UTC
Labels: AutoAssignerTriage, Weekly, Planning, NewFeature, Overdue, Bug

**Comment by ctkochan22** [comment] 2022-12-27 17:15
Sorry, trying to catch up with being OOO for a while. Sounds like this is okay? 

If there is an issue, lets create a new GH and I'll take it
