### ISSUE TITLE
[$500] All - IOU - Receipt scanning does not work under the employee account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29536] opened 2023-10-13 08:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:**

## Action Performed:
Prerequisites:
For scanning, you can use a personal receipt file or download a test file here https://drive.google.com/file/d/1ggU-OEqJM7mCZpB4G1eYWZ_9Scqy2ThA/view?usp=drive_link

Steps:
1. Open New Expensify app
2. Log in with the employee's login
3. Click on the FAB button
4. Click on 'Request Money'
5. Choose 'Scan' and add a receipt
6. Choose a workspace
7. Save money request
8. Wait for the scan to complete

## Expected Result:
Receipt scanning should work under any account with access to this functionality.

## Actual Result:
Receipt scanning does not work under the employee account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/696e099b-a583-4038-ab61-bb4bf386cb9f

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb1118c0cf3e0984</li>
        <li>Upwork Job ID: 1712748797192491008</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by benomatis** [comment] 2023-10-15 13:31
@izarutskaya I tried this with a normal test account (not an employee), and while I did not measure it, it eventually finished, but took a very long time (several minutes). Is the scanning never finishing for you even if you leave it there processing?

**Comment by kevinksullivan** [comment] 2023-10-17 16:11
Waiting for proposals

**Comment by arthurmfgtab** [comment] 2023-10-18 21:25
Hey @kevinksullivan , I'm Arthur from Callstack and I'd like to work on this :)

**Comment by rezkiy37** [comment] 2023-10-23 14:18
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue.

**Comment by rezkiy37** [comment] 2023-10-25 12:55
Posting a conclusion after investigation...

**Comment by rezkiy37** [comment] 2023-10-25 13:31
@akinwale, @kevinksullivan. Guys, I've prepared the conclusion.

So, after the investigation, we actually have a problem, when users are **employee** of a workspace and upload a receipt. The bug is not replicable with the other roles: **admin** nor **auditor**, nor a money request with a regular user.

The app shows an error message for each required field (`amount`, `merchant` and `date`), if it is empty. The error message is a static on the app side. 

The root cause that the backend returns a scanned transaction details with a completed state (`SCANCOMPLETE`), and the same time `amount` equals `0`, `merchant` equals `(none)`.


<img width="1114" alt="backend response" src="https://github.com/Expensify/App/assets/57314631/349ce0fb-ad3a-4ed7-8d17-3ddaab6ade31">


Moreover, I found a case when the backend returns a report action (`message`) with a small description what happened. However, it looks strange that a sender is "__fake__".

<img width="1728" alt="Screenshot 2023-10-25 at 15 22 03" src="https://github.com/Expensify/App/assets/57314631/70f70a55-cfef-4c2e-9009-3677a71a2f1e">

<img width="635" alt="Screenshot 2023-10-25 at 15 28 55" src="https://github.com/Expensify/App/assets/57314631/2910c008-bff7-4ff3-8a3b-4a8f6ed3efec">

IMO, we should fix the bug from the backend side, because it is not a frontend bug.

**Comment by kevinksullivan** [comment] 2023-10-27 02:31
@akinwale what're your thoughts?

**Comment by akinwale** [comment] 2023-10-27 04:04
@kevinksullivan I think we can close this since this requires modifications to be made in the backend, and we don't need to change anything in the app to fix it based on @rezkiy37's findings.

**Comment by rezkiy37** [comment] 2023-10-30 10:17
So, guys, what's the final decision on this issue?

**Comment by kevinksullivan** [comment] 2023-10-31 14:33
Closing

**Closed by kevinksullivan** 2023-10-31 14:33 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
