### ISSUE TITLE
[$500] LHN - 1:1 conversation isn't appearing until you click on a direct link to it

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31384] opened 2023-11-15 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Prerequirements: Use accounts that never interacted before
1. Device A: Navigate to https://staging.new.expensify.com/
and log in
2. Device B: Navigate to https://staging.new.expensify.com/
and log in with a different account
3. Device B: Create a new group chat with "Device A" and a few other participants
4. Device B: Navigate to the group chat
5. Device B: Do a split bill with all of the members
6. Device A: Navigate to the LHN

## Expected Result:
The 1:1 conversation only appears if you navigate to it through search or a direct link.

## Actual Result:
An 1:1 conversation should appear on Device A as soon as Device B requests the split.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/cb8e8b82-0b6b-48cf-ad64-8fe223f9d7c3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01905b0dea2ec3236f</li>
        <li>Upwork Job ID: 1724826305483014144</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-11-20 12:23
Looks like a BE issue as the 1:1 Chat Report has not yet come to FE

**Comment by jjcoffee** [comment] 2023-11-20 14:34
@rojiphil is partially correct, in the pusher event there are no `reportActions` for the 1:1 report. When you start searching for the 1:1 user, interestingly the chat pops up in the LHN! cc @NicMendonca - let's make this one internal!

**Comment by lakchote** [comment] 2023-11-24 15:38
@NicMendonca I'm currently focusing on critical tasks could you assign it to someone else who have more bandwith please?

**Comment by MonilBhavsar** [comment] 2023-11-24 18:06
I am not able to reproduce this issue. @izarutskaya could you please retest and confirm

**Comment by MonilBhavsar** [comment] 2023-11-27 09:11
Same ^ Waiting for QA team to confirm

**Comment by rojiphil** [comment] 2023-11-29 17:30
> I am not able to reproduce this issue

@MonilBhavsar 
I could reproduce this. 
It looks like the actual result and the expected result in OP test steps are incorrect. They need to be swapped to make sense.
Do you think this is causing the confusion here?

**Comment by MonilBhavsar** [comment] 2023-12-04 11:57
Same ^ 
Or QA team cc @izarutskaya

**Comment by jjcoffee** [comment] 2023-12-06 12:50
@MonilBhavsar Sorry for the delayed response! I can still reproduce on latest staging (v1.4.8-1). The first step (Device A) should include to log in as a user that Device B's user has never interacted with before (easiest to just use a new user).

**Comment by NicMendonca** [comment] 2023-12-11 15:34
@jjcoffee @MonilBhavsar just to confirm - are we waiting on proposals for this one?

**Comment by MonilBhavsar** [comment] 2023-12-14 16:36
I'll try again today and see If I can reproduce

**Comment by NicMendonca** [comment] 2023-12-18 15:09
@MonilBhavsar any update?

**Comment by NicMendonca** [comment] 2023-12-21 14:13
bump @MonilBhavsar

**Comment by NicMendonca** [comment] 2023-12-22 17:16
@MonilBhavsar going to close since this hasn't been reproducible. Please reopen if you end up being able to.

**Comment by lanitochka17** [comment] 2023-12-28 01:47
Issue reproducible on the latest build 1.4.18-3


https://github.com/Expensify/App/assets/78819774/89e2214c-aa47-4f27-99f7-721dcc88207f

**Comment by MonilBhavsar** [comment] 2023-12-28 06:53
Will look

**Comment by MonilBhavsar** [comment] 2024-01-03 11:18
I am still not able to reproduce. I also dry ran through the code and confirmed that we're sending chat report in Onyx updates. https://github.com/Expensify/Web-Expensify/blob/2cb1b34034c3e44c156376e4421b4534c19015c7/lib/ReportAPI.php#L4764
Not sure what I am missing here.

**Comment by NicMendonca** [comment] 2024-01-04 15:42
Ok, lets close for now!

**Comment by kbecciv** [comment] 2024-01-05 15:19
Issue is reproducible for QA team, build 1.4.22.0

https://github.com/Expensify/App/assets/93399543/1276256f-bb61-4f22-b78b-218c2d4b4968

**Comment by kbecciv** [comment] 2024-01-09 12:45
@MonilBhavsar Np, it's "Most recent"

https://github.com/Expensify/App/assets/93399543/e38c2d51-5c36-444c-bef5-c4dc8f0a52ad

**Comment by MonilBhavsar** [comment] 2024-01-11 05:46
Thanks!
I'm dealing with waves issue. I'll circle back

**Comment by NicMendonca** [comment] 2024-01-16 13:21
@MonilBhavsar if this doesn't fall into a specific wave, then we can just close this for now, yeah?

**Comment by MonilBhavsar** [comment] 2024-01-19 05:48
I'm pretty sure I'm missing some detail because Applause is able to reproduce and I am not.
I tried again and it worked as expected

<img width="372" alt="Screenshot 2024-01-19 at 11 15 25 AM" src="https://github.com/Expensify/App/assets/32012005/4042e472-f972-4051-8aa6-3603194da559">

The first unread is for Money Request
The second unread is for Group chat

Applause team, if you're consistently able to reproduce, could you please mention detailed steps. Seems like I'm missing something.

My steps are:

1. As a user A start a new group chat with user B and user C
2. Split bill in the group chat
3. As a user B logged into another device ensure they get both group chat and money request updates.

**Closed by MonilBhavsar** 2024-01-19 05:48 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
