### ISSUE TITLE
[$500] IOS - Next Button is flickered on invite member page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28944] opened 2023-10-05 18:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to Settings > Workspaces > Members > Invite
2. Select some option and go to invite message page
3. Back to invite page

## Expected Result:
Next button should not be flickered

## Actual Result:
 Next button is flickered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.77.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68c2c275-0917-434d-bc82-5a5a468a36b3

https://github.com/Expensify/App/assets/93399543/91307237-ae26-40b9-8de9-212a06f8fd48

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696313832898399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a06c703a9f52813f</li>
        <li>Upwork Job ID: 1709998768268832768</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by jaymerut** [comment] 2023-10-05 21:00
I'd recommend unfocusing the text field once 'Next' is selected to prevent the keyboard from displaying once navigating backwards to the Invite Member page.

**Comment by jaymerut** [comment] 2023-10-05 21:04
Contributor details
Your Expensify account email: jaymerut@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/jaymer

**Comment by jliexpensify** [comment] 2023-10-09 05:34
I asked a colleague with an iPhone to repro this, as the original report is from 2 versions ago, and she couldn't so it might be fixed. @dukenv0307 and @kbecciv can you try on the newest version?

**Comment by jliexpensify** [comment] 2023-10-09 23:05
@ishpaul777 thanks! Although I feel like the `Next` button looks pretty stable in your video? I don't know if I'm misunderstanding, but don't see any flickering like the initial videos. @fedirjh what do you think?

**Comment by jliexpensify** [comment] 2023-10-09 23:17
Hmm @dukenv0307 can you weigh in here, since you're the reporter? Any chance you can outline specifically what the issue is?

**Comment by jaymerut** [comment] 2023-10-09 23:19
From what I understand it's the toggling of the keyboard that's the issue, which causes the Next button to "jump".

**Comment by jliexpensify** [comment] 2023-10-11 04:42
Thanks @kbecciv - that jump is clearer in your video!

**Comment by jliexpensify** [comment] 2023-10-11 04:42
@fedirjh - can you review the previously posted proposals?

**Comment by jliexpensify** [comment] 2023-10-16 00:16
Bump @fedirjh to review the proposals

**Comment by jliexpensify** [comment] 2023-10-23 22:18
@ishpaul777 did you mean to upload a video? I don't see a ink attached to your comment.

**Comment by jliexpensify** [comment] 2023-10-24 00:14
Thanks! I personally can barely see the `Next` button at 0:22 in the video and I don't think this is an issue. @fedirjh thoughts?

**Comment by jliexpensify** [comment] 2023-10-25 02:55
>@dukenv0307 Can you clarify if this is what you are refering to flickering?

I would also like to know, because I don't see any "flickering." Watching the newest video, I'd say the behaviour might be better described as an "inconsistent delay" or "juttering" but I really think this is a minor issue.

I'll let @dukenv0307 weigh in one final time, but I feel like we'll go down a rabbit hole here. I'm very much leaning towards closing this.

**Comment by jliexpensify** [comment] 2023-10-26 05:00
Bump @dukenv0307 - if we don't hear back from you, I'll close this issue tomorrow ;)

**Comment by jliexpensify** [comment] 2023-10-27 05:02
@dukenv0307 it would be helpful to link the original video ([I assume this one?](https://expensify.slack.com/archives/C049HHMV9SM/p1696313911476529?thread_ts=1696313832.898399&cid=C049HHMV9SM)) that you're referring to.

With your description, I understand the bug now - transparently, I think this is a much better explanation of the problem and expected outcome than what is in the original issue:

> The expectation here is that when coming back, the button on "Invite members" screen will start at the bottom and go up as the keyboard is opened. Not start at the top -> go to the bottom -> go to the top again.

To me, as a non-Engineer, this indicates that there's an issue with how we're surfacing the `Next` button in the Invite Members flow.

@fedirjh I think it's still a minor bug that would probably go unnoticed by the majority, but it's probably good to fix this right?

**Comment by jliexpensify** [comment] 2023-10-30 22:41
Thanks for the explanation @fedirjh , it's useful for me (as a non-engineer)!

Couple of final thoughts from me:

> To solve the problem, we need to reconsider how the Button behaves throughout the App. 

This sounds like a feature request, since we're changing button behaviour.
 
> The Button's position is dependent on the Keyboard, rather than the screen.

This makes sense, and I'm assuming would be the cause of the inconsistency?

Anyway, I'm going to close this off now - I think we have to bring this up as a feature request if we want to explore "fixing" this. Thanks everyone!

**Closed by jliexpensify** 2023-10-30 22:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
