### ISSUE TITLE
Room - No audit trail when removing members from a custom room (not #admin/#announce) 

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29979] opened 2023-10-19 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No, new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room with a few members
3. Click on the room header > Members
4. Remove a few members

## Expected Result:
There will be a system message for member removal, just like the behavior in #admin room when inviting user to the workspace

## Actual Result:
There is system message for member invitation but not for member removal

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/ab022e5c-3eff-4842-9e33-225448e77758

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-10-19 19:08
I can reproduce this and I do think this would be helpful for our audit logs. I'm going to reach out in expensify-open-source to see if someone might want to take this.

**Comment by Christinadobrzyn** [comment] 2023-10-19 20:50
https://expensify.slack.com/archives/C01GTK53T8Q/p1697748638516129

**Comment by Julesssss** [comment] 2023-10-20 07:43
I wouldn't be surprised if this was a backend task, unfortunately. Which is a problem, because I won't be able to work on it for at least a month

**Comment by Christinadobrzyn** [comment] 2023-10-20 18:09
yeah sounds like we've already [discussed](https://expensify.slack.com/archives/C01GTK53T8Q/p1697762259650349?thread_ts=1697748638.516129&cid=C01GTK53T8Q) adding this (and other details) in the audit trail but have decided to table it for now. So going to close this as a feature request that we'll consider later.

**Closed by Christinadobrzyn** 2023-10-20 18:09 UTC
Labels: Engineering, Weekly, NewFeature, Bug
