### ISSUE TITLE
mweb/Desktop - Growl - User does not receive a growl when offline in workspace options

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10547] opened 2022-08-24 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com on mweb (Or desktop app)
2. Sign into a valid account
3. Tap on Profile icon > Workspace > Reimburse Expenses (Can be any workspace option that should display a growl)
4. Turn off internet connection
5. Tap on "View all receipts" while offline

## Expected Result:
User expects to receive a growl when offline

## Actual Result:
The button does not seem to be responsive, as no growl is received even though it is being pressed.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App
- Mobile Web

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186505018-9bb67eb8-5145-4cf6-9dfb-6e926065eadc.mp4

https://user-images.githubusercontent.com/93399543/186505020-1d6b787f-001e-46be-b527-3382d5516325.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sketchydroide** [comment] 2022-08-25 07:38
I cannot replicate this one, and there was another similar to this one that could not be replicated

**Comment by sketchydroide** [comment] 2022-08-25 07:43
Seems like @luacmartins can't replicate either I'm leaning on not a blocker

**Comment by bondydaa** [comment] 2022-08-25 17:08
> User expects to receive a growl when offline

I think since we're moving toward Brick Road error handling we are getting rid of growls, right? 

cc @iwiznia

**Comment by bondydaa** [comment] 2022-08-25 17:09
once we figure out if this should be Brick Road or Growl we can probably make it external, will leave as daily until we get more insight.

**Comment by dylanexpensify** [comment] 2022-08-30 09:07
reviewing today :)

**Comment by dylanexpensify** [comment] 2022-08-30 09:19
So it seems this isn't reproducible. Do we still want to export cc @bondydaa @sketchydroide ?

**Comment by sketchydroide** [comment] 2022-08-30 09:33
I think this is not always reproducible, maybe we can ask QA to try again, and see if this is still an issue
@kbecciv can you guys check if this still happens for your guys?

**Comment by kbecciv** [comment] 2022-08-30 12:13
@sketchydroide Checking with team, will update you shortly.

**Comment by kbecciv** [comment] 2022-08-30 13:46
@sketchydroide Unable to reproduce it for all environments.

**Comment by sketchydroide** [comment] 2022-08-30 14:26
thanks, I think we can close for now, if it's an issue we will reopen, it might be that a PR that was needed did not go toghether with another one, or a Web PR was not in Staging at the time of testing, and it was soon after.

**Closed by sketchydroide** 2022-08-30 14:26 UTC
Labels: External, Engineering, Daily, Improvement
