### ISSUE TITLE
[Wave 6: Tags][$500][HOLD https://github.com/Expensify/App/issues/32735] Tag - Two tags are highlighted when one sub-tag is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32521] opened 2023-12-05 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Y
**Reproducible in staging?:** N
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is a member of workspace that has some tags in `Parent: Child` format. There has to be at **least** 9 tags in the policy.

1. Go to the workspace chat
2. Click + > Request money > Manual
3. Enter amount > Next
4. Click Show more > Tag
5. Select a subcategory
6. Click Tag

## Expected Result:
Only the selected tag is highlighted

## Actual Result:
Two tags are highlighted when a sub-tag is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/f6fefd51-6014-4bac-9e17-d8cde0baef52

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da048e9d51f0937c</li>
        <li>Upwork Job ID: 1732341978058440704</li>
        <li>Last Price Increase: 2023-12-13</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2023-12-05 20:35
@lanitochka17 what was the account used to reproduce this? Otherwise, can we have clearer steps on the tags setup? I tried creating a workspace with multilevel tags in OldDot and I don't see what you see in the video. I don't see multiple levels.

**Comment by aldo-expensify** [comment] 2023-12-05 20:45
I'm only seeing one level in NewDot:

<img width="399" alt="image" src="https://github.com/Expensify/App/assets/87341702/b900b52a-9dfc-42ea-bca0-ef82cc7ee6dc">

I setup up "dependent" multilevel tags in OldDot.

**Comment by lanitochka17** [comment] 2023-12-05 20:48
@aldo-expensify Hello
Follow the instructions in the file, but as for tags:
https://expensify.testrail.io/index.php?/runs/view/19265&group_by=cases:section_id&group_order=asc&group_id=296764

![image](https://github.com/Expensify/App/assets/78819774/bd2ae9d6-fe85-4eb1-b80d-056fc6cd9e85)

![image](https://github.com/Expensify/App/assets/78819774/bdbf0ff6-07b2-4bf4-945b-318c209cf7f6)

**Comment by aldo-expensify** [comment] 2023-12-05 20:57
Thanks, I got the tags working now!

**Comment by aldo-expensify** [comment] 2023-12-05 21:35
I'm failing to reproduce this in staging:

1. I select a nested tag
2. I click again the tag to open the selection menu
3. The only highlighted tag is the selected one


https://github.com/Expensify/App/assets/87341702/265a2c03-1c02-4c60-8d78-52e819486e88

**Comment by aldo-expensify** [comment] 2023-12-05 21:36
@lanitochka17 what is the account email used in the test?

**Comment by aldo-expensify** [comment] 2023-12-05 23:43
Removing deploy blocker since I can't reproduce and doesn't look very important to hold the deploy on it

**Comment by lanitochka17** [comment] 2023-12-06 00:12
@aldo-expensify tags must be more than 9

**Comment by aldo-expensify** [comment] 2023-12-06 00:48
I'll try that

**Comment by aldo-expensify** [comment] 2023-12-06 01:37
@lanitochka17 thanks, I managed to reproduce now:

<img width="389" alt="image" src="https://github.com/Expensify/App/assets/87341702/2fec0338-01f2-4f97-8256-74c95dd6d84d">

Considering that nested tags is not handled in production yet (it is a new feature), I think it is fine we don't block the deploy on it and we fix improve it as a follow up

**Comment by lanitochka17** [comment] 2023-12-06 01:39
@aldo-expensify thanks

**Comment by aldo-expensify** [comment] 2023-12-08 23:04
@Santhosh-Sellavel thoughts on the proposal: https://github.com/Expensify/App/issues/32521#issuecomment-1842597409 ?

**Comment by Santhosh-Sellavel** [comment] 2023-12-10 19:12
I haven't tested it out yet, the [proposal](https://github.com/Expensify/App/issues/32521#issuecomment-1842597409) sounds good to me. 

Can I get a CSV file for multilevel tags?

**Comment by dylanexpensify** [comment] 2023-12-11 10:17
@Santhosh-Sellavel to review!

**Comment by aldo-expensify** [comment] 2023-12-12 16:06
> Can I get a CSV file for multilevel tags?

@Santhosh-Sellavel you don't need the "Do you want to use multiple levels of" option, you have to create normal tags using the format `parent: child`. These [instructions](https://github.com/Expensify/App/issues/32521#issuecomment-1841588773) are for categories, but they also apply for tags and I reproduced using them.

**Comment by Santhosh-Sellavel** [comment] 2023-12-12 18:01
> > Can I get a CSV file for multilevel tags?
> 
> @Santhosh-Sellavel you don't need the "Do you want to use multiple levels of" option, you have to create normal tags using the format `parent: child`. These [instructions](https://github.com/Expensify/App/issues/32521#issuecomment-1841588773) are for categories, but they also apply for tags and I reproduced using them.
> 
> Note: you also need to create at least 9 tags

For Categories worked fine, but for Tags it didn't work for me. Will try again though.

**Comment by Santhosh-Sellavel** [comment] 2023-12-12 18:05
@aldo-expensify Are you taking over this as CME, lets go with @dukenv0307 proposal here

**Comment by aldo-expensify** [comment] 2023-12-12 18:24
oh, so the expected results in the GH description is wrong? Tags are not expected to behave as categories when in form `Parent: child`? I understand that @dukenv0307 's [proposal](https://github.com/Expensify/App/issues/32521#issuecomment-1842597409) will disable the nesting.

@dylanexpensify can you help me confirm what is the expected behaviour here? Should tags in form `Parent: child` show nested? or is that only for categories?

**Comment by dylanexpensify** [comment] 2023-12-13 08:49
Hmmm @puneetlath @greg-schroeder any ideas?

**Comment by aldo-expensify** [comment] 2023-12-13 15:25
> @aldo-expensify Tags in form of Parent: child will still show nested in the tag list (like the Accounting > Child 2 below), my proposal is only so that the selected one will not show nested, so it will look like this (which is consistent with the categories)

Oh, I understand now, for a moment I thought it was going to remove all nesting, but it only does for the selected item. That looks good to me then, specially if it is consistent with categories.

**Comment by aldo-expensify** [comment] 2023-12-13 20:17
@dylanexpensify I'll proceed with hiring @dukenv0307 since I think the path is clear enough

**Comment by puneetlath** [comment] 2023-12-13 20:18
Tags are not supposed to be nested. That was implemented by mistake and is being reverted.

**Comment by aldo-expensify** [comment] 2023-12-13 20:20
ohh, so the expectation is wrong. Do we have an issue where the revert is being handled? If we do, we should HOLD on that or just close this.

**Comment by aldo-expensify** [comment] 2023-12-13 20:20
Sorry @dukenv0307 for the confusion, I'll remove you while we figure out the way forward.

**Comment by puneetlath** [comment] 2023-12-13 20:34
Yep! https://github.com/Expensify/App/issues/32735

**Comment by aldo-expensify** [comment] 2023-12-13 20:54
Thanks @puneetlath !

Added HOLD so we can check once https://github.com/Expensify/App/issues/32735 is implemented, most likely this won't be an issue anymore.

**Comment by greg-schroeder** [comment] 2023-12-19 23:10
Closing this following the revert

**Closed by greg-schroeder** 2023-12-19 23:10 UTC
Labels: External, Engineering, Weekly, NewFeature
