### ISSUE TITLE
[HOLD on 40768] [$250] Task - Background overlaps task details after deleting task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41825] opened 2024-05-08 07:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4545775
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-internal team

## Action Performed:
1. Open the app and log in
2. Open any chat
3. Assign a task
4. Open the created task and send a message
5. Delete the task

## Expected Result:
The task details are fully visible

## Actual Result:
The background overlaps the task details. The background overlaps briefly thread messages when opening threads in accounts with multiple reports

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fe8d5f0f-e482-4423-9948-290f91f7d8c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9e215e05231b823</li>
        <li>Upwork Job ID: 1788319637053231104</li>
        <li>Last Price Increase: 2024-05-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by izarutskaya** [comment] 2024-05-08 07:38
We think this issue might be related to the  #vip-vsb

**Comment by izarutskaya** [comment] 2024-05-08 07:39
Production
![Screenshot_20240508_145937_New Expensify](https://github.com/Expensify/App/assets/115492554/cf595d8d-5551-441d-8d0a-e9043741c898)

**Comment by marcaaron** [comment] 2024-05-08 21:26
Gonna demote this one as deleting a task doesn't feel like a super common thing. 

This feels similar to another issue [here](https://github.com/Expensify/App/issues/40768). I'm curious to see if this will be fixed once that goes to staging.

**Comment by stephanieelliott** [comment] 2024-05-21 23:49
Still on hold for https://github.com/Expensify/App/issues/40768

**Comment by ahmedGaber93** [comment] 2024-05-22 01:11
@stephanieelliott the PR https://github.com/Expensify/App/pull/41482 was deployed to production 2 weeks ago. And this issue still reproduced on latest main.

It seems has the same root cause as https://github.com/Expensify/App/issues/40078, so I think we can colse/hold this on 40078.

**Comment by stephanieelliott** [comment] 2024-05-29 07:31
Ah thanks @ahmedGaber93 -- let's hold this on https://github.com/Expensify/App/issues/40078 and retest to see if that fixes it.

**Comment by stephanieelliott** [comment] 2024-06-07 07:08
Still holding on https://github.com/Expensify/App/issues/40078

**Comment by madmax330** [comment] 2024-06-07 09:20
not overdue

**Comment by ahmedGaber93** [comment] 2024-06-07 12:20
PR https://github.com/Expensify/App/pull/42629 is now in staging

**Comment by stephanieelliott** [comment] 2024-06-11 20:56
^^ Not on staging yet, should be deployed to staging on the next release though!

**Comment by ahmedGaber93** [comment] 2024-06-21 12:01
I think we can close this now. https://github.com/Expensify/App/issues/40078 is closed.

**Closed** 2024-06-25 00:36 UTC
Labels: External, Engineering, Weekly, Bug
