### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web – Profile – Inconsistency of padding above “No result found” error in “Pronouns” section.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22560] opened 2023-07-10 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the "Settings" page.
2. Navigate to the "Profile" section.
3. Access the "Pronouns" subsection.
4. Enter an invalid pronoun and observe that the "No result found" error is displayed below the input field with a padding of 20px, while on all other pages the padding does not exceed 12px.

## Expected Result:
 The padding above the "No result found" error should be consistent with other pages, set to 12px

## Actual Result:
The padding above the "No result found" error is 20px.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3cbf1d05-21e0-4103-8464-3759b972101d

![Screenshot 2023-07-10 at 21 48 43](https://github.com/Expensify/App/assets/93399543/9c205988-ea10-4a41-86df-b241a5fc51ea)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688976013859439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01258e7c1b59f26cff</li>
        <li>Upwork Job ID: 1682352401511223296</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li> |  | 0</li>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by DanutGavrus** [comment] 2023-07-10 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Profile – Inconsistency of padding above “No result found” error in “Pronouns” section.

### What is the root cause of that problem?
In some places, we are using `SelectionListRadio` and in others, we are using the `OptionsSelector`.
1. `SelectionListRadio` uses `BaseSelectionListRadio` which has `styles.ph5, styles.pv5`(20px padding up down left & right):
2. https://github.com/Expensify/App/blob/4f398dbfaac950fe4b6f29bd2d67af9501fd7b50/src/components/SelectionListRadio/BaseSelectionListRadio.js#L219-L232
3. 2. `OptionsSelector` uses `BaseOptionsSelector` which has both `styles.ph5, styles.pv5`(same as above) and `styles.ph5, styles.pb3`(20px left & right, 12px bottom, 0px top):
4. https://github.com/Expensify/App/blob/4f398dbfaac950fe4b6f29bd2d67af9501fd7b50/src/components/OptionsSelector/BaseOptionsSelector.js#L350-L368
Inconsistency comes from using both `View style={this.props.shouldUseStyleForChildren ? [styles.ph5, styles.pv5...` at line 354 & `<View style={this.props.shouldUseStyleForChildren ? [styles.ph5, styles.pb3...` at line 361.

### What changes do you think we should make in order to solve the problem?
1. Decide if we want to keep `styles.ph5, styles.pv5` or `styles.ph5, styles.pb3` in all 3 places, but I think `styles.ph5, styles.pv5` should be the one as it appears in 2 out of 3 places;
2. 2. If we keep first option, we'll update line 361 to also use `styles.ph5, styles.pv5`;
3. 3. Quickly check all 9 `OptionsSelector` appearances before & after to make sure it still looks good.
If we decide to keep the other one, we'll update the other 2 places accordingly.

**Comment by Pujan92** [comment] 2023-07-10 14:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Padding inconsistency for search input and list between `SelectionListRadio` & `OptionsSelector`.

### What is the root cause of that problem?
In the `SelectionListRadio` we are giving the padding of 20px for each side of text input `View` whereas for `OptionsSelector` giving 20px horizontally and 12px from bottom.
https://github.com/Expensify/App/blob/6a7c1b2bb3d938b0b2c6388370a818f31e58b93f/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220

### What changes do you think we should make in order to solve the problem?
We can provide the same padding for `SelectionListRadio` like `OptionsSelector` with `[styles.ph5, styles.pb3]` here.
https://github.com/Expensify/App/blob/6a7c1b2bb3d938b0b2c6388370a818f31e58b93f/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220

**Comment by ahmedGaber93** [comment] 2023-07-10 14:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Profile – Inconsistency of padding above “No result found” error in “Pronouns” section.
### What is the root cause of that problem?
search screen use `BaseOptionsSelector` and has search box with padding bottom 12 px, while Pronouns use `SelectionListRadio` and has search box with padding bottom 20 px.

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/OptionsSelector/BaseOptionsSelector.js#L361

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220


### What changes do you think we should make in order to solve the problem?
we need to make consistent padding bottom for both 12 px or 20 px (or what ever we agree to do with internal developer).
i perfer 12 px for both it seem more suitable.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ahmedGaber93** [comment] 2023-07-10 14:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Profile – Inconsistency of padding above “No result found” error in “Pronouns” section.
### What is the root cause of that problem?
search screen use `BaseOptionsSelector` and has search box with padding bottom 12 px, while Pronouns use `SelectionListRadio` and has search box with padding bottom 20 px.

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/OptionsSelector/BaseOptionsSelector.js#L361

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220


### What changes do you think we should make in order to solve the problem?
we need to make consistent padding bottom for both 12 px or 20 px (or what ever we agree to do with internal developer).
i perfer 12 px for both it seem more suitable.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ahmedGaber93** [comment] 2023-07-10 15:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Profile – Inconsistency of padding above “No result found” error in “Pronouns” section.
### What is the root cause of that problem?
search screen use `BaseOptionsSelector` and has search box with padding bottom 12 px, while Pronouns use `SelectionListRadio` and has search box with padding bottom 20 px.

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/OptionsSelector/BaseOptionsSelector.js#L361

https://github.com/Expensify/App/blob/2e3f8c2ee20bfad255f3cc4c6d918a0d7a453ff1/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220


### What changes do you think we should make in order to solve the problem?
we need to make consistent padding bottom for both 12 px or 20 px (or what ever we agree to do with internal developer).
i perfer 12 px for both it seem more suitable.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by slafortune** [comment] 2023-07-12 20:56
How do we know if 12 or 20px are correct?  I would think all comparable box types would be the same regardless of which page they are on.

**Comment by slafortune** [comment] 2023-07-13 20:41
Let's get some design eyes to make sure!

**Comment by slafortune** [comment] 2023-07-18 17:23
@shawnborton is there a rule of thumb for consistent padding 

- Enter an invalid pronoun and observe that the "No result found" error is displayed below the input field with a padding of 20px, while on all other pages, the padding does not exceed 12px.

- Although padding for the invite member page is 20px.

**Comment by slafortune** [comment] 2023-07-20 20:35
Still checking on this - https://expensify.slack.com/archives/C049HHMV9SM/p1689885290833409?thread_ts=1688976013.859439&cid=C049HHMV9SM

**Comment by slafortune** [comment] 2023-07-21 11:30
12px should be the norm everywhere

**Comment by shuja-hasan** [comment] 2023-07-21 18:04
The fix for this issue would be as follows
- PronounsPage is using SelectionListRadio, while the Search page is using OptionsSelector, both of them have slightly different padding attached.
- The fix is to align the padding of SelectionListRadio with the other component.
- Please see the screenshot attached for a look after it is fixed.

<img width="1280" alt="Screenshot 2023-07-21 at 11 02 41 PM" src="https://github.com/Expensify/App/assets/6966694/78dd60de-cfac-41a8-bd16-9b9d7addd43f">

I can fix this right away If I'm assigned this issue.
Regards.

**Comment by shuja-hasan** [comment] 2023-07-21 18:08
Contributor details
Your Expensify account email: shuja971@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0121a0daf3347d820b?viewMode=1

**Comment by shuja-hasan** [comment] 2023-07-22 12:00
## Proposal
[Updated]https://github.com/Expensify/App/issues/22560#issuecomment-1646065111

**Comment by Santhosh-Sellavel** [comment] 2023-07-23 21:14
@DanutGavrus [Proposal](https://github.com/Expensify/App/issues/22560#issuecomment-1629141315) looks good to me, we have to change in one place here. 

https://github.com/Expensify/App/blob/4f398dbfaac950fe4b6f29bd2d67af9501fd7b50/src/components/SelectionListRadio/BaseSelectionListRadio.js#L220

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-07-23 21:18
This is straight forward one, Other proposals also address the issue and are similar.

But as the first proposal has everything needed, so went with the first proposal, thanks, everyone!

**Comment by DanutGavrus** [comment] 2023-07-24 12:26
@Santhosh-Sellavel Should I create the PR? Thank you!

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 13:33
Please wait for assignment from @cead22

**Comment by DanutGavrus** [comment] 2023-07-25 10:47
@Santhosh-Sellavel
PR ready for review: [PR23538](https://github.com/Expensify/App/pull/23538)

**Comment by slafortune** [comment] 2023-08-07 19:51
The pull request got merged within 3 working days of assignment, so this job is eligible for a 50% #urgency bonus 🎉

when @DanutGavrus got assigned: 2023-07-24 22:59:59 Z
when the PR got merged: 2023-07-26 17:05:17 UTC

-  External issue reporter: @usmantariq96/$250 - offer sent
-  Contributor that fixed the issue: @DanutGavrus/$1500 - offer sent
-  Contributor+ that helped on the issue and/or PR: @Santhosh-Sellavel does not require payment (Eligable for Manual Requests)/$1500

**Comment by DanutGavrus** [comment] 2023-08-07 20:03
@slafortune Offer accepted on Upwork!

**Comment by usmantariq96** [comment] 2023-08-08 03:17
@slafortune offer accepted
Thanks

**Comment by Santhosh-Sellavel** [comment] 2023-08-08 19:36
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21048
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21048/files#r1287575033
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:  https://expensify.slack.com/archives/C049HHMV9SM/p1691523226087939
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A (We will have this covered already, it's been reported multiple times already)
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [x]  [@slafortune] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-08-08 20:29 UTC
Labels: External, Daily, Design, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2023-08-10 03:01
Requested on ND

**Comment by JmillsExpensify** [comment] 2023-08-15 16:35
Reviewed the details for @Santhosh-Sellavel. Approved for payment in NewDot based on BZ summary above.
