### ISSUE TITLE
 [HOLD for payment 2023-10-20] [$500] [$1,000] Android - App freezes after killed app is called via concierge deep-link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26867] opened 2023-09-06 12:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Kill app
3. Tap concierge deep-link from another mobile application (https://staging.new.expensify.com/concierge)

## Expected Result:
App is opened, concierge chat is displayed

## Actual Result:
App freezes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/fe336b81-6be7-455a-be1c-d495d4b82ec9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb7f1ef5548a9cf1</li>
        <li>Upwork Job ID: 1699456046868582400</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by imranaalam** [comment] 2023-09-06 18:56
**Problem Statement**:
When tapping on a deep link to the Concierge chat from another mobile application, the Expensify app freezes instead of displaying the Concierge chat.

**Root Cause**:
The root cause could be a combination of factors:

1. Delay or failure in resolving the `Welcome.serverDataIsReadyPromise()` which waits for server data.
2. The variable `isNetworkOffline` might not be representing the true network state, causing unintended logic paths to be executed.
3. Complex navigation logic in the `navigateToConciergeChat` and `openReportFromDeepLink` functions may not always result in a navigation action, causing the app to hang.
4. Potential conflicts in report routing, especially in cases of optimistically created reports that are later found to be preexisting.
5. Issues with the initialization of deep links in the `DeepLinkWrapper`.

**Proposed Solution**:
1. Ensure that the `Welcome.serverDataIsReadyPromise()` resolves correctly. Implement a timeout to handle scenarios where it might take too long or not resolve at all.
2. Improve the accuracy of the `isNetworkOffline` check, possibly by using a more robust method or library to check network connectivity.
3. Refactor navigation logic to ensure there's always a definitive navigation action for every possible state. Add proper error handling and fallbacks.
4. Handle report rerouting more gracefully, ensuring that the user experience isn't disrupted.
5. Thoroughly test and debug the deep link initialization process to ensure it works seamlessly.

**Alternative Solution**:
1. Bypass the server data check if it's causing significant delays, especially for operations that don't strictly require the most recent server data.
2. Use service workers or background tasks to pre-fetch or update necessary data, reducing the reliance on real-time network checks.
3. Simplify navigation logic by having a default route or chat that the app can fall back to in ambiguous situations.
4. Implement a more user-friendly error or loading screen that informs users when there's a delay, providing options to retry or navigate elsewhere.
5. Reevaluate the deep link structure or implementation method to ensure it's optimized for the app's architecture.

**Comment by robertKozik** [comment] 2023-09-11 07:57
Thank you, @imranaalam, for your thoughtful analysis. Your insights are indeed valuable. However, it seems that we might need to dig a bit deeper to pinpoint the exact root cause of the issue. While you've highlighted several potential scenarios and solutions, finding the specific factor would be immensely helpful.

**Comment by NicMendonca** [comment] 2023-09-13 15:02
@robertKozik any update here?

**Comment by robertKozik** [comment] 2023-09-13 17:45
@NicMendonca, I'm still waiting for proposals. The one that's already here doesn't pinpoint exactly what's causing it or how to tackle it. It just lists potential root causes and general solutions.

**Comment by NicMendonca** [comment] 2023-09-18 22:55
Doubled the price

**Comment by NicMendonca** [comment] 2023-09-21 20:53
^ doubled the price this week

**Comment by NicMendonca** [comment] 2023-09-25 13:23
Still waiting for proposals

**Comment by robertKozik** [comment] 2023-09-29 14:17
Still no proposals for this issue 🙅🏼

**Comment by NicMendonca** [comment] 2023-10-02 14:46
@izarutskaya can you please confirm this issue is still reproducible?

**Comment by NicMendonca** [comment] 2023-10-05 20:49
@izarutskaya is this still reproducible?

**Comment by robertKozik** [comment] 2023-10-09 21:20
Thanks for proposal @HezekielT. The root cause you found seems to be more general and the issue should be encountered on every platform. How can you explain that app freezes only on android (per issue reporter)?

**Comment by robertKozik** [comment] 2023-10-10 13:52
Thank you for the thorough explanation, @HezekielT. I've reviewed your solution, and it does indeed resolve the issue. The root cause is clear, and your solution addresses it directly. Without any hesitation, I'll recommend bringing you on board for this task.

🎀 👀 🎀 C+ reviewed

**Comment by NicMendonca** [comment] 2023-10-20 20:15
@HezekielT can you please apply to the job here? Thanks -- https://www.upwork.com/jobs/~01fb7f1ef5548a9cf1

**Comment by NicMendonca** [comment] 2023-10-20 20:15
@robertKozik bump on BZ checklist: https://github.com/Expensify/App/issues/26867#issuecomment-1765325902

**Comment by robertKozik** [comment] 2023-10-23 19:18
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **In my opinion this issue was an adge-case which was not handled before, so no any particular PR introduced it**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I **don't think the regression test is needed here**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by NicMendonca** [comment] 2023-10-24 15:36
@HezekielT - sent offer!

**Comment by NicMendonca** [comment] 2023-10-24 17:07
@HezekielT yep - we apply that in the form of bonuses.

**Closed** 2023-10-24 17:10 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
