### ISSUE TITLE
[$500] Login - Text in the login field is clipped when device font size is set to minimum

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30361] opened 2023-10-25 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to login page
3. Type glpGLPyThe content in the input field is clipped

## Expected Result:
The content in the input field is not clipped.

## Actual Result:
The content in the input field is clipped
This issue also happens in the many input fields across the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/9f3b22d5-b01d-44a4-b7f5-0044dc679cf6

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01549a10dd76321155</li>
        <li>Upwork Job ID: 1717214187673346048</li>
        <li>Last Price Increase: 2023-11-15</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-10-26 00:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Text in the all the input fields are clipped when device font size is set to minimum
### What is the root cause of that problem?
We're using `getFontScale` to calculate the height of input. When the fontScale is too small, now it will smaller than the height of the font, which caused this issue.
https://github.com/Expensify/App/blob/4760f761a0645bdcc250f319be019941c8ccb811/src/styles/variables.ts#L10-L12
### What changes do you think we should make in order to solve the problem?

Define a `maxFontSizeMultiplier` props to prevent our `PixelRatio.getFontScale()` get too small value, let say that it should be 0.9. 
OR we can add more logic to `getValueUsingPixelRatio`, define a new variable called `fontScale`, this value will have 0.9 as minimum value.

```javascript
const fontScale = PixelRatio.getFontScale() > 0.9 ? PixelRatio.getFontScale() : 0.9
```

### What alternative solutions did you explore? (Optional)
We can also slightly increase the height of the text input to 54:
```javascript
inputHeight: getValueUsingPixelRatio(54, 72),
```

**Comment by iiredalert** [comment] 2023-10-26 01:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we adjust the text size on iPhone to small, some of the letters in the login phone or email textfield get cut off.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/d4d9f78be5d54e18d71b9a6c1881734dea3e7780/src/styles/variables.ts#L11

Uses PixelRatio.getFontScale() which is only implemented on android according to their comment.  In iOS it always returns the default pixel ratio.

Here is a snippet from the react native code:
```
    /*
        Returns the scaling factor for font sizes. This is the ratio that is
        used to calculate the absolute font size, so any elements that
        heavily depend on that should use this to do calculations.

        If a font scale is not set, this returns the device pixel ratio.

        Currently this is only implemented on Android and reflects the user
        preference set in Settings > Display > Font size,
        on iOS it will always return the default pixel ratio.
        */
    getFontScale(): number;
```

### What changes do you think we should make in order to solve the problem?

Write code specific for IOS that would get the appropriate font scale.  We could use the react-native-dynamic-fonts library, or write some native code to get the value we are looking for and properly size the components.

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-10-30 13:53
@Santhosh-Sellavel what do you think of the proposals we have so far?

**Comment by sonialiap** [comment] 2023-11-03 12:12
Santhosh is [partially OOO](https://expensify.slack.com/archives/C02NK2DQWUX/p1698333756531649) and I expect hasn't had the opportunity to review this yet. This is not a super urgent issue so I'm going to keep him assigned

**Comment by sonialiap** [comment] 2023-11-06 11:07
Asked in slack if Santhosh is back

**Comment by Santhosh-Sellavel** [comment] 2023-11-06 17:05
I'm still 50% so can you please unassign and reassign a new C+ as it has proposal already, thanks!

**Comment by sonialiap** [comment] 2023-11-10 17:54
Assigning new C+ 🙏

**Comment by alitoshmatov** [comment] 2023-11-13 09:36
Reviewing today

**Comment by alitoshmatov** [comment] 2023-11-13 16:47
As far as I understand this issue is only reproducible when you change text size of your phone from settings. I reproduced it by going to  Settings > Display & brightness > text size and setting it to smallest measure. 

@sonialiap is this case supported by our app and should it be fixed?

**Comment by fabriziobertoglio1987** [comment] 2023-11-16 09:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The text of the input field is clipped when the device font size is set to minimum.

### What is the root cause of that problem?

The TextInput height and fontSize are scaled based on PixelRatio.getFontScale(), but the paddingTop and paddingBottom properties are not scaled, which causes the text to have the wrong vertical alignment and get cut. The paddingTop and paddingBottom properties are responsible for the vertical position of the text in the TextInput. 

The below example reproduces the issue outside of Expensify/App project:

```javascript
import {
  StyleSheet,
  TextInput,
  PixelRatio,
} from 'react-native';

function getValueUsingPixelRatio(defaultValue, maxValue) {
  const scaledSize = PixelRatio.getFontScale() * defaultValue;
  return scaledSize > maxValue ? maxValue : scaledSize;
}

const fontSize = getValueUsingPixelRatio(15, 21);
const inputHeight = getValueUsingPixelRatio(52, 72);
const paddingBottom = getValueUsingPixelRatio(8, 10)
const paddingTop = getValueUsingPixelRatio(23, 23)

// DOES NOT WORK
const inputStyles = {height: inputHeight, fontSize, paddingBottom: 8};

// WORKS
// const inputStyles = {height: inputHeight, fontSize, paddingBottom, paddingTop};

function TextInputExample() {
  return (
    <TextInput
      allowFontScaling={false}
      style={[styles.input, inputStyles]}
    />
  );
}

const styles = StyleSheet.create({
  input: {
    paddingTop: 23,
    paddingLeft: 0,
    lineHeight: undefined,
  }
});
```

Font size set to Maximum:

| Before  scaling Padding  | After scaling Padding |
| ----------- | ----------- |
| <img src="https://user-images.githubusercontent.com/24992535/283369985-6e14599a-6d1f-41f2-8059-8fa1c405738c.png" width="350" />      | <img src="https://user-images.githubusercontent.com/24992535/283370307-5a3e230f-3955-4421-88a1-c2345890a6fd.png" width="350" />       |






Font size set to Minimum:

<image src="https://user-images.githubusercontent.com/24992535/283367291-6fec8b48-729a-4253-92d1-6d58a6c2fd0d.png" width="250" />

| Before scaling Padding   | After scaling Padding |
| ----------- | ----------- |
| <img src="https://user-images.githubusercontent.com/24992535/283369455-de948f73-9c68-4c96-9e16-ef6754b54305.png" width="350" />      | <img src="https://user-images.githubusercontent.com/24992535/283368662-99043341-ef90-4375-ba6b-644f739d50a3.png" width="350" />   |

### What changes do you think we should make in order to solve the problem?

The issue is fixed by scaling the padding top and bottom based on the PixelRatio.getFontScale(). The properties paddingTop and paddingBottom determine the vertical position of the text, they need to be scaled with the height and fontSize to correctly position the Text in the TextInput.

| Small Font    | Big Font |
| ----------- | ----------- |
| <img src="https://user-images.githubusercontent.com/24992535/283371532-4e71ae4d-5c95-4943-bcf0-b2df6b61bd71.png" width="350" />      | <img src="https://user-images.githubusercontent.com/24992535/283371576-8ab2e502-90a1-4259-8110-7ef5324333c8.png" width="350" />       |

### What alternative solutions did you explore? (Optional)

I investigated the react-native iOS implementation of allowFontScaling which modifies the lineHeight and fontSize of the TextInput to correctly scale them to the new font size:
- Updates the [lineHeight](https://github.com/facebook/react-native/blob/01729919d141299a5f84dca1d24124e3833755ef/packages/react-native/Libraries/Text/RCTTextAttributes.mm#L132) based on the new multiplier
- Changes the fontSize ([effectiveFontSize](https://github.com/facebook/react-native/blob/01729919d141299a5f84dca1d24124e3833755ef/packages/react-native/Libraries/Text/RCTTextAttributes.mm#L217) and [updateFontSize](https://github.com/facebook/react-native/blob/255fef5263afdf9933ba2f8a3dbcbca39ea9928a/packages/react-native/React/Views/RCTFont.mm#L416)) based on the new multiplier

These are my observation of the react-native implementation: 
 
- The react-native implementation does not update the baseline of the Text after changing the lineHeight/fontSize, there is no need to change ascent/descent when changing lineHeight.
- RCTFont has thread-safety issues and must be rewritten.
- The effectiveFontSizeMultiplier is calculated based on the FontMetrics using [scaledValueForValue](https://developer.apple.com/documentation/uikit/uifontmetrics/2877387-scaledvalueforvalue?language=objc)

**Comment by sonialiap** [comment] 2023-11-17 09:18
I cannot reproduce it on android with my phone's text set to largest or smallest options. Since I cannot reproduce and Ali can only with the smallest text size possible, I agree that this seems like an edge case. I'm going to close this so that we can fry some bigger fish.

**Closed by sonialiap** 2023-11-17 09:18 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
