### ISSUE TITLE
[$500] Assign task - Task has no a threaded like link the number of Replies

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26404] opened 2023-08-31 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account
3. On LHN, click on the FAB button
4. Select Assign Task
5. Enter a title or description
6. Assign the task to yourself
7. On Share Somewhere, select a conversation with another user you have access to
8. Press Confirm Task button
9. Log out
10. Log in as the user that the task was shared with
11. Go to the 1:1 conversation

## Expected Result:
The task has a threaded like link with the number of replies

## Actual Result:
The task has no a threaded like link with the number of replies. When mark the task as done in task checkbox "Replies" link in the task appears and disappears. The total amount of "Replies" is not specified correctly

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e71d5171-335c-454d-86c3-d9b5f9bce2ba

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f9222d92647cf0f</li>
        <li>Upwork Job ID: 1698791761209364480</li>
        <li>Last Price Increase: 2023-09-25</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-09-04 20:14
Reproduced on staging

**Comment by naveedbasharat06** [comment] 2023-09-04 20:50
Hi 
I'm creating a test account in order to do chat with it but it is not showing my test account inside searching
I'm using + in order to create a test account.
Should I create account on different gmail ?

**Comment by naveedbasharat06** [comment] 2023-09-04 20:54
Contributor details
Your Expensify account email: naveed.basharat06@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/freelancers/naveedbasharat)

**Comment by naveedbasharat06** [comment] 2023-09-04 22:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
want to show the reply link with count beneath the Task Name.
### What is the root cause of that problem?
I've seen that this only happens when we do the following Steps
- Create Task and Assign to the other person
- Now IF we didn't does any chat in the group/ or if we did chat in the group it only counts the replies we are doing. Our chat is not including count of "Completed" and "reopened" statuses inside messages
- So the root cause right now is that it should not show the reply link if there are no replies from each person. So we should hide it.
### What changes do you think we should make in order to solve the problem?

For this First of all we need to think 
- wether we want to add "Completed" and "Reopened" in our Replies Count
- If yes then we count them as a message
- If not than we have to stop this blinking of replies link
Also in terms of Coding
We have to play with these two components
- ReportActionItem
- ReportActionItemSingle
### What alternative solutions did you explore? (Optional)
N/A

**Comment by naveedbasharat06** [comment] 2023-09-05 22:43
Should I work on it @ntdiary

**Comment by anmurali** [comment] 2023-09-25 16:58
Closing per https://expensify.slack.com/archives/C02NK2DQWUX/p1695654817536769

**Closed by anmurali** 2023-09-25 16:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
