### ISSUE TITLE
Report - App crashes when trying to open unloaded paid distance expenses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52889] opened 2024-11-21 11:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**9.0.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5250645
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisites:
Create a WS, invite an employee

Steps:
1. Open New Expensify app Hybrid
2. Under the employee account, send 2 or more distance charges to the WS room
3. Under the administrator account, pay the distance charges received from the employee
4. Re-login to the application under the employee account
5. Go to the WS room
6. Open paid distance expenses

## Expected Result:
App should not crash when trying to open unloaded paid distance expenses

## Actual Result:
App crashes when trying to open unloaded paid distance expenses

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[2111_3.txt](https://github.com/user-attachments/files/17845212/2111_3.txt)

https://github.com/user-attachments/assets/1ffe302f-a556-4b3b-b5e2-ef9ea5780b06

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @carlosmiceli</details>

**Comment by IuliiaHerets** [comment] 2024-11-21 11:58
Same problem happens with the thread. Do we need to log a new issue for it?

https://github.com/user-attachments/assets/70a21759-9fe9-4387-b00d-7b7f445b0655

**Comment by carlosmiceli** [comment] 2024-11-21 14:50
@Krishna2323 Understood! @IuliiaHerets seems that the PR is already merged, can we check if the issue is indeed gone?

**Comment by carlosmiceli** [comment] 2024-11-25 13:54
Not opverdue.

**Comment by carlosmiceli** [comment] 2024-11-28 16:09
since this is merged in prod, seems like we can close this: https://github.com/Expensify/App/issues/52889#issuecomment-2491436717

**Closed by carlosmiceli** 2024-11-28 16:09 UTC
Labels: Engineering, Daily, Overdue, Bug
