### ISSUE TITLE
[$250] Web - Console error shows up when creating room and opening room chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25717] opened 2023-08-22 20:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24643
## Action Performed:
1. Go to staging.new.expensify,com
2. Create a new account
3. Create a new workspace
4. Create a public room

## Expected Result:
No console error

## Actual Result:
Console error shows up when room chat is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/57af92a8-0584-4dba-8eff-c2e7a46263e9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b3473e5d9167fdde</li>
        <li>Upwork Job ID: 1717965957525639168</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-22 21:14
We are trying to parse the URL and relative href can't be parsed and that's why it jumps to the catch block where we are consoling the error. I think we can just remove console line.
https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/libs/Url.js#L25

**Comment by cead22** [comment] 2023-08-22 23:35
I don't think this is a bug or a blocker as this console.log seems to have been added for debugging purposes. We can decide to remove it if we want, and do so in any of the PRs submitted for this repo, but I suggest we close this

**Comment by cead22** [comment] 2023-08-22 23:37
It looks like this is failing in the constructor, and maybe instead of deleting that log line, we should update it to also log the `url` we're passing to the method

**Comment by roryabraham** [comment] 2023-08-23 00:02
Agreed that this doesn't seem like a bug, and certainly not a deploy blocker. It makes sense to me to remove the `console.error` there.

**Comment by shubham1206agra** [comment] 2023-08-23 07:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue

Web - Console error shows up when creating room and opening room chat

### What is the root cause of that problem?

This is due to console.error being present in the places
https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/libs/Url.js#L25
and 
https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/libs/Url.js#L45

#### Why did `new URL(url)` fails?

It is because we are trying to parse links such as `/settings/profile/display-name`, which causes `URL` to fail as it requires a proper format (i.e., including origin).

### What changes do you think we should make in order to solve the problem?

We should use `tryResolveUrlFromApiRoot` to append the correct origin to the url if needed here
https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L26

to

```js
const attrHref = tryResolveUrlFromApiRoot(htmlAttribs.href || '');
```

And remove `console.error` OR change to `console.warn`

Maybe Optional
In `CONFIG.js`
https://github.com/Expensify/App/blob/44eb88a7b6643b6b75978927adc83715e6c06824/src/CONFIG.js#L23
can be changed to get no problem with link rendering in the DEV server.
```js
const expensifyComWithProxy = getPlatform() === 'web' && useWebProxy ? Url.addTrailingForwardSlash(window.location.origin) : expensifyURL;
```

### What alternative solutions did you explore? (Optional)

**Comment by cead22** [comment] 2023-09-07 19:17
Switching to monthly since this isn't a priority

**Comment by cead22** [comment] 2023-09-19 06:46
No update. Focused on W9 and this is not a priority

**Comment by cead22** [comment] 2023-09-28 01:54
No update, focused on detailed design for Wave 9: Violations

**Comment by cead22** [comment] 2023-10-27 18:09
> It is because we are trying to parse links such as `/settings/profile/display-name`, which causes `URL` to fail as it requires a proper format (i.e., including origin).
> 
> ### What changes do you think we should make in order to solve the problem?
> We should use `tryResolveUrlFromApiRoot` to append the correct origin to the url if needed here

@Ollyws can you please review @shubham1206agra 's proposal? I think it looks good but I think we should fix the URL with tryResolveUrlFromApiRoot and **not** remove the console.error since that's what surfaced this issue. What do you think? cc @roryabraham

**Comment by cead22** [comment] 2023-11-06 19:24
@lanitochka17 can you re-test and see if you can still reproduce please?

**Comment by lanitochka17** [comment] 2023-11-07 21:25
Issue is not reproduced on latest build 1.3.96-5
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/eae61f3f-89db-43fa-985f-958ae3bcbd08

**Closed** 2023-11-08 17:05 UTC
Labels: External, Engineering, Daily, Help Wanted
