### ISSUE TITLE
[PAID] [$500] Update getIOUReportActionDisplayMessage() to accept the transaction as a parameter

### ISSUE THREAD

**Issue by tgolen** [Expensify/App#38355] opened 2024-03-14 20:14 UTC
This is coming from https://github.com/Expensify/App/issues/27262. You can read the issue description there to get context behind the problem being solved and the mess being cleaned up.

# Problem
`ReportUtils.getIOUReportActionDisplayMessage()` is called from a view component. It contains logic which calls `const transaction = TransactionUtils.getTransaction(originalMessage.IOUTransactionID ?? '');` (a deprecated method).

## Why this is important to fix
It maintains more pure and exact flow of data through the react application. If the view is using transaction data, then it needs to subscribe to the transaction in Onyx so that it's assured that the transaction object will never be stale or out-of-date.

# Solution
- Pass `transaction` as a parameter to `getIOUReportActionDisplayMessage()` and get the parameter from `withOnyx()` in the view component.
- Remove the deprecated method completely
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cae110240999840b</li>
        <li>Upwork Job ID: 1768370164615811072</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by FitseTLT** [comment] 2024-03-14 20:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update getIOUReportActionDisplayMessage() to accept the transaction as a parameter

### What is the root cause of that problem?
Enhancement
### What changes do you think we should make in order to solve the problem?

Update `getIOUReportActionDisplayMessage` to accept transaction and pass it in every instance we call it

### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2024-03-14 20:37
@Krishna2323 Why do you suggest using `Onyx.connect()` in `ContextMenuActions.tsx` instead of `withOnyx`?

**Comment by FitseTLT** [comment] 2024-03-14 20:42
In context menu action the funtion is called when the user press copy to clipboard and the transaction we get with `getTransaction` is the uptodated one why do we even need connect don't get it we should make the `transaction` parameter optional and whenever we access it from components we pass it from withOnyx and for others like context menu action we just fetch the transaction as we are using it currently @tgolen

**Comment by tgolen** [comment] 2024-03-14 20:47
@FitseTLT I think it's better to connect the context menu to onyx to get the data it needs:

1. This is how data is supposed to flow through a react application (from the top-down, passed via components), so it is following standard practices
2. It presents a good pattern in our code for others to follow (engineers will ironically only choose bad patterns to follow. eg. `ReportUtils.getPolicy()` is the next one to clean up).
3. Even if the `transacation` is technically up-to-date in that instance, it's still not promoting proper patterns, so I'd rather do it correctly

All of this results in higher-quality, easier to maintain, easier to debug code across the app.

**Comment by FitseTLT** [comment] 2024-03-14 21:00
[Update](https://github.com/Expensify/App/issues/38355#issuecomment-1998383323) based on https://github.com/Expensify/App/issues/38355#issuecomment-1998458191

**Comment by nkdengineer** [comment] 2024-03-15 05:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update getIOUReportActionDisplayMessage to accept the transaction as a parameter

### What is the root cause of that problem?
We should pass `transacation` as parameter and get it via `withOnyx` to the component re-render when the `transaction` is changed

### What changes do you think we should make in order to solve the problem?
1. In `getIOUReportActionDisplayMessage` function, add an extra param `transaction`

```
function getIOUReportActionDisplayMessage(reportAction: OnyxEntry<ReportAction>, transaction: OnyxEntry<Transaction>): string {

```

and then we can remove this line 

https://github.com/Expensify/App/blob/4e599b2cd6061b52d3964dc69e7575e210f0581d/src/libs/ReportUtils.ts#L4983

2. Get `transaction` via `withOnyx` in `ReportActionItemMessage`

```
export default withOnyx<ReportActionItemMessageProps, ReportActionItemMessageOnyxProps>({
    transaction: {
        key: ({action}) => `${ONYXKEYS.COLLECTION.TRANSACTION}${(action.originalMessage as IOUMessage).IOUTransactionID ?? '0'}`,
    },
})(ReportActionItemMessage);
```

3. Add `transaction` in `ContextMenuActionPayload` type 

```
transaction?: OnyxEntry<Transaction>;

```
https://github.com/Expensify/App/blob/4e599b2cd6061b52d3964dc69e7575e210f0581d/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L66


4. Get `transaction` via `withOnyx` in `BaseReportActionContextMenu`

```
withOnyx<BaseReportActionContextMenuProps, BaseReportActionContextMenuTransactionOnyxProps>({
    transaction: {
        key: ({reportActions, reportActionID}) => {
            const reportAction = reportActions?.[reportActionID];
            return `${ONYXKEYS.COLLECTION.TRANSACTION}${(reportAction?.originalMessage as IOUMessage)?.IOUTransactionID}`;
        },
    },
})(
```

And then add `transaction` into `payload` here

https://github.com/Expensify/App/blob/4e599b2cd6061b52d3964dc69e7575e210f0581d/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L230
### What alternative solutions did you explore? (Optional)
NA

**Comment by FitseTLT** [comment] 2024-03-15 11:29
>But the way you pass transactions in BaseReportActionContextMenu doesn't look good to me. I prefer passing it in the context action payload as described in @nkdengineer https://github.com/Expensify/App/issues/38355#issuecomment-1998983450

Really don't get it @hoangzinh I think you misunderstood me I am proposing same as the selected proposal and I haven proposed to pass the transaction in the payload of `onPress` callback here is the a text from my proposal
>pass the transaction to onPress in the payload when the context menu item is copy to clipboard ( textTranslateKey=='reportActionContextMenu.copyToClipboard') here

I really think you should give my proposal a second look. I have stated what should be done in detail same as the selected proposal and giving code snippet is not a must when a contributor provides what should be done in detail as I did 
This what I said 
>we will pass reportActions and reportActionID to the key and we will subscribe to transaction with transactionID we get from the report action's originalMessage.IOUTransactionID and pass the transaction to onPress in the payload when the context menu item is copy to clipboard ( textTranslateKey=='reportActionContextMenu.copyToClipboard') here

cc: @tgolen

**Comment by FitseTLT** [comment] 2024-03-15 15:00
> Hi @FitseTLT just wanna confirm that, in your proposal, you mentioned that you would pass `transaction` in this line
> 
> https://github.com/Expensify/App/blob/02e802540e74fe2781a49a6f0cf6ccbfcf0b652f/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.tsx#L264
> 
> And only pass `transaction` if it's a `copyToClipboard`, isn't it?

Yes. `filteredContextMenuActions` contains the different menu items in the context menu and we only need transaction parameter for `onPress` (payload) for copy to clipboard ( textTranslateKey=='reportActionContextMenu.copyToClipboard') 
https://github.com/Expensify/App/blob/e9c112a2b89217401dfef3e248fa8e93d4c4e418/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L332-L333
That's why I said 👍

**Comment by tgolen** [comment] 2024-03-15 16:36
I discussed this with @hoangzinh and we agreed to go with the proposal from @FitseTLT.

**Comment by FitseTLT** [comment] 2024-03-18 19:41
PR will be up in 3days

**Comment by davidcardoza** [comment] 2024-03-21 01:10
@strepanier03 Why was this added to the [#whatsnext] #vip-billpay-invoice](https://github.com/orgs/Expensify/projects/114) project board yesterday?

**Comment by strepanier03** [comment] 2024-03-21 20:10
@davidcardoza - Because it seemed like the best fit based on this [doc](https://docs.google.com/document/d/1pghDdrUVhINJH4jFWNbT2w-ecFqYwTvoGxx4EoYA1U8/edit). 

I originally thought VSB but it says anything related to IOU and bills are "elsewhere". 

Then under VIP-bills it says "Anything related to bills and invoicing as part of an IOU request".

**Comment by davidcardoza** [comment] 2024-04-02 14:31
That makes sense, thanks for explaining.

**Comment by strepanier03** [comment] 2024-04-16 21:58
@hoangzinh - Please complete the checklist as soon as you can and then I'll handle your payment. 

@FitseTLT - I've paid your contract and closed it in Upwork, thanks!

**Comment by tgolen** [comment] 2024-04-17 14:35
Yeah, I've got that follow-up issue assigned to me:
https://github.com/Expensify/App/issues/39408

I'll take a look at the logs today and see what I find.

**Comment by strepanier03** [comment] 2024-04-17 21:12
Thanks @hoangzinh for clarification 🙌.

**Closed** 2024-04-17 21:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
