### ISSUE TITLE
Room- Only visible to you not displayed after login for user don't have access

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19713] opened 2023-05-27 00:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #18662

## Action Performed:
1. Launch the app and login
2. Create a public room
3. Go to the room settings, you should see a new item to add a welcome message:
4. Enter a message with markdown and save it
5. Save the URL of the room, you will need it for other users to join.
6. Now log in with a new account that is not part of the room and access the URL of the room.
## Expected Result:
You should have been invited to the room and a welcome message you saved should show up. It should say that is only visible to you.

## Actual Result:
Only visible to you message not displayed after login

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.19-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b6992820-77c8-4c5e-a12e-2908c54f4a29

![Bug6069890_Screen_Shot_2023-05-26_at_4 43 39_PM](https://github.com/Expensify/App/assets/43996225/2543efe5-6d49-48e1-a0ac-c84477354d43)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-05-29 16:17
@kavimuru is this still an issue? I can't reproduce 

https://github.com/Expensify/App/assets/17131195/fe68a3c1-9811-41b8-bde2-5b3c31644a55

**Comment by sonialiap** [comment] 2023-05-29 16:25
Message appears for me

HOWEVER - I also see a bunch of rooms I should not be seeing 😬 

https://github.com/Expensify/App/assets/17131195/0507d741-dd6e-4050-8fdc-da9610b28679

**Comment by sonialiap** [comment] 2023-05-29 16:26
In my tests on prod the extra rooms did not get added 


https://github.com/Expensify/App/assets/17131195/2e2d171c-6b2c-4407-a985-a714c105a5df

**Comment by sonialiap** [comment] 2023-05-29 16:32
Reported https://expensify.slack.com/archives/C049HHMV9SM/p1685377898341889

**Comment by sonialiap** [comment] 2023-06-01 15:37
I can no longer reproduce. Looks like the issue was resolved in https://github.com/Expensify/App/issues/19657

**Closed by sonialiap** 2023-06-01 15:37 UTC
Labels: Daily, Overdue, Bug
