### ISSUE TITLE
Hold #28997 [$500] Mweb/Chrome - Thread - Tapping leave thread, displays "U" for a second instead of Room name in header

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31220] opened 2023-11-10 22:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room with a thread reply message
3. Tap on reply
4. Tap 3 dots on top
5. Select Leave thread

## Expected Result:
Tapping leave thread, must not display unavailable "U" for a second instead of Room name in header

## Actual Result:
Tapping leave thread, displays unavailable "U" for a second instead of Room name in header.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/26f258f8-177e-49f8-aed7-f543b9bd446a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014350424b71769cdf</li>
        <li>Upwork Job ID: 1723110772857241600</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-11 03:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Mweb/Chrome - Thread - Tapping leave thread, displays "U" for a second instead of Room name in header
### What is the root cause of that problem?
- After clicking on "Leave thread", we set the optimistic data for this thread as below:
https://github.com/Expensify/App/blob/f285c9cf3294697e1cb1f9c797641876b38d5829/src/libs/actions/Report.js#L2051-L2057
-   Then we do not navigate the user to the parent report, so it will display the optimistic report for a while before back to the parent report.
### What changes do you think we should make in order to solve the problem?
- We need to navigate the user to the parent report after API call, the same as what we did in case we left the room. Can do it by updating
https://github.com/Expensify/App/blob/f285c9cf3294697e1cb1f9c797641876b38d5829/src/libs/actions/Report.js#L2087-L2091
to



### What alternative solutions did you explore? (Optional)
- NA

**Comment by laurenreidexpensify** [comment] 2023-11-14 10:44
@eVoloshchak do you agree this will be covered in https://github.com/Expensify/App/issues/28997 and we can close?

**Comment by laurenreidexpensify** [comment] 2023-11-20 11:04
@eVoloshchak bump

**Comment by DylanDylann** [comment] 2023-11-20 11:23
@eVoloshchak I think the RCA of this issue (31220) is that we do not navigate user to the parent thread after leaving thread. The 28997 is about the behavior when we re-join the leaved thread. Both of them are not the same

**Comment by eVoloshchak** [comment] 2023-11-21 21:56
https://github.com/Expensify/App/issues/28997 and this issue do have different causes, but depending on which approach will be taken to fix  https://github.com/Expensify/App/issues/28997 this one might be resolved too (https://github.com/Expensify/App/issues/28997#issuecomment-1821624057)
 
@laurenreidexpensify, let's put this on HOLD for https://github.com/Expensify/App/issues/28997

**Comment by laurenreidexpensify** [comment] 2023-11-30 10:55
Still on hold on #28997

**Comment by laurenreidexpensify** [comment] 2023-12-05 15:49
Still on hold on https://github.com/Expensify/App/issues/28997

**Comment by laurenreidexpensify** [comment] 2023-12-14 12:17
Still on hold on https://github.com/Expensify/App/issues/28997 but that has payment due on 15 Dec - so should be off hold v soon

**Comment by laurenreidexpensify** [comment] 2023-12-20 10:26
@eVoloshchak #28997 has been on prod for a solid 12 days now, can we lift the hold?

**Comment by eVoloshchak** [comment] 2023-12-22 14:53
@laurenreidexpensify, according to my tests, this was resolved by a fix for https://github.com/Expensify/App/issues/28997. 
Would like for someone from QA to double check that

**Comment by laurenreidexpensify** [comment] 2023-12-29 10:10
@Expensify/applauseleads please confirm if this is still reproducible in KI tests

**Comment by laurenreidexpensify** [comment] 2024-01-15 15:11
I am closing based on @eVoloshchak's comment that this is resolved

**Closed by laurenreidexpensify** 2024-01-15 15:11 UTC
Labels: External, Weekly, Help Wanted, Overdue
