### ISSUE TITLE
[HOLD Waiting on contributor] [$250] Playing video is not paused when opening attachment modal.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40735] opened 2024-04-22 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @blimpich / @KMichel1030 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713565853756499

## Action Performed:

1. upload a video
2. start playing the video
3. while the first video is playing, upload another video
4. now try to download the first video that is still playing
5. click the pause button once on the playing video

## Expected Result:
1st video should be downloaded and clicking pause should pause the video.

## Actual Result:
video is not downloaded and clicking pause does nothing - Reproduced by @KMichel1030 and @blimpich 
NOTE : I can download the video but pause button does nothing
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ae26bbcb-4796-4e80-b72c-3923dcd00ffe

https://github.com/Expensify/App/assets/38435837/03e110b5-0abb-472b-ac43-32e5d4166ac1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dfbe7a8e20d88932</li>
        <li>Upwork Job ID: 1782544477695893504</li>
        <li>Last Price Increase: 2024-05-20</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by blimpich** [comment] 2024-04-22 22:59
Lowered price since I consider this a low-priority bug.

**Comment by KMichel1030** [comment] 2024-04-22 23:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Playing video is not paused when opening attachment modal.

### What is the root cause of that problem?
Currently, previous playing video is paused when playing new video.
When playing new video, below two functions are called in order and playing video is paused.

- pause video
https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/components/VideoPlayerContexts/PlaybackContext.tsx#L41-L49
- update current ref
https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/components/VideoPlayerContexts/PlaybackContext.tsx#L51-L62

But when uploading, `updateCurrentlyPlayingURL` is called after current ref is updated because we set it below.
https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/components/VideoPlayer/BaseVideoPlayer.tsx#L180-L181
And previous video is not paused.

### What changes do you think we should make in order to solve the problem?
We have to pause video before setting `currentVideoPlayerRef` in below part.
https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/components/VideoPlayer/BaseVideoPlayer.tsx#L180-L181

### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/161328186/51d4547b-2a1a-409e-b95e-3f7e6c087c73

**Comment by Pujan92** [comment] 2024-04-24 16:52
@KMichel1030 Thanks for the proposal but I think the issue isn't pausing the running video on opening the attachment modal. The issue we need to solve is when a user plays the first video and then uploads another video, now user should be able to pause the first playing video by clicking on the pause button. Also download should be worked for the first video.

@blimpich Plz confirm the above issue description

**Comment by KMichel1030** [comment] 2024-04-24 23:45
@blimpich @Pujan92 
Thank you for your check.
I'm apologize for not reading the issue description carefully.

---------------------------------------------------------------------

> 1. upload a video
> 2. start playing the video
> 3. while the first video is playing, upload another video
> 4. click the pause button once on the playing video

When we click the pause button once on the playing video after upload video, [`updateCurrentlyPlayingURL()`](https://github.com/Expensify/App/blob/9a727de1e67013a8baf2dff018063af03d963ada/src/components/VideoPlayer/BaseVideoPlayer.tsx#L86) is called and then [`shareVideoPlayerElements()`](https://github.com/Expensify/App/blob/9a727de1e67013a8baf2dff018063af03d963ada/src/components/VideoPlayer/BaseVideoPlayer.tsx#L236) is called because `updateCurrentlyPlayingURL()` updates [`currentlyPlayingURL`](https://github.com/Expensify/App/blob/9a727de1e67013a8baf2dff018063af03d963ada/src/components/VideoPlayer/BaseVideoPlayer.tsx#L237C9-L237C28).

Then in `shareVideoPlayerElements()`, video is [played](https://github.com/Expensify/App/blob/9a727de1e67013a8baf2dff018063af03d963ada/src/components/VideoPlayerContexts/PlaybackContext.tsx#L60).
So actually current playing video is updated but video is not paused. You can pause video by clicking again.

To resolve this problem, we have to delete auto play in `shareVideoPlayerElements()` and manage them separately in used parts.
And I think it will cause so many problems here and there.
And regarding current status, I mean, now previously playing video is paused when we play another video so I think it's better to pause video when opening attachment modal from generalization standpoint.

Please let me know your suggestions.

**Comment by Pujan92** [comment] 2024-04-30 13:21
@KMichel1030 We don't need to upload another video to face this issue, it can be reproducible with a single video by expanding and collapsing it.

https://github.com/Expensify/App/assets/14358475/ce262644-eb6c-4f19-bfff-bb3fa4240b6f

**Comment by KMichel1030** [comment] 2024-05-02 19:07
@Pujan92 

> @KMichel1030 We don't need to upload another video to face this issue, it can be reproducible with a single video by expanding and collapsing it.

Thank you for your check.
This bug is not related with this issue and also has different root cause.
I've updated [proposal](https://github.com/Expensify/App/issues/40735#issuecomment-2071096530) covering above issue.

cc: @blimpich 
I'm wondering if we have to handle above issue as separate one. Please let me know your suggestion.

**Comment by blimpich** [comment] 2024-05-02 19:30
We don't have to handle it separately if we don't want to. They seem like very similar bugs to me, so I'd be curious to know how much their individual root causes differ from one another. If possible I'd like to fix both in this issue, depending on how different the root cause is.

**Comment by KMichel1030** [comment] 2024-05-02 19:32
@blimpich 
Thank you. I got your point.
BTW, could you please let me know your suggestion about [this](https://github.com/Expensify/App/issues/40735#issuecomment-2076055622)?

**Comment by blimpich** [comment] 2024-05-02 20:00
Unsure, I don't think I entirely understand the technical explanation but from what I do understand I agree that i think its better to pause video when opening the attachment modal if that avoids causing a bunch of other bugs.

**Comment by KMichel1030** [comment] 2024-05-03 14:28
@blimpich 

> Unsure, I don't think I entirely understand the technical explanation but from what I do understand I agree that i think its better to pause video when opening the attachment modal if that avoids causing a bunch of other bugs.

I'm sorry for not writing technical problems clearly.
Currently, video is played automatically when currently playing video is changed(that is when `currentlyPlayingURL` and `currentVideoPlayerRef` changing). And everything related with video is designed and coded assuming auto play.
If we want to fix this error as it is mentioned in issue description, we need to stop auto play and I think there are so many things to consider(will cause some errors as I mentioned before).
Please let me know if you have any other suggestions so that we can proceed further.
Thank you.

**Comment by KMichel1030** [comment] 2024-05-05 14:58
@blimpich       cc: @Pujan92 
Currently, we are facing 2 different errors in this issue.
One is mentioned in issue description and another one is found by @Pujan92 .
> @KMichel1030 We don't need to upload another video to face this issue, it can be reproducible with a single video by expanding and collapsing it.

At first glance, it seems similar but they have different root cause.
To fix first issue, it will cause some errors as I mentioned before. But there's no problem in fixing second issue(issue found by @Pujan92).

In first issue, if we pause video when opening attachment modal there's no problem as well.
Let me explain again why we have to pause video when opening attachment modal instead of following issue description.

Let's assume this test case.
1. Play `Video1`
2. Upload a video
3. Play `Video2`

If we omit step 2, `Video1` is paused when playing `Video2`.
But if we follow above 3 steps, `Video1` is not paused.
So I think it's better to pause video.

It's true that it's very minor issue but I think we should fix it as it is reproducible in multiple test cases.
I always respect your decisions. Sorry for having to raise this again.

**Comment by mvtglobally** [comment] 2024-05-06 20:02
Issue not reproducible during KI retests. (First week)

**Comment by KMichel1030** [comment] 2024-05-06 22:38
Download issue is fixed in [this PR](https://github.com/Expensify/App/pull/41054), but video is not still paused.

**Comment by blimpich** [comment] 2024-05-07 16:55
Sounds good. I just re-read through this whole issue to try and grasp all the details of this. Lets fix the 2nd issue that @KMichel1030 describes as we have a good solution for it, and see if we can fix the 1st issue too in the PR phase. If it ends up being too much trouble then we can pivot and just solve the 2nd issue, but lets give it a try. 🙂

**Comment by Pujan92** [comment] 2024-05-10 12:33
Waiting for @KMichel1030 to raise a PR

**Comment by KMichel1030** [comment] 2024-05-12 00:17
@Pujan92 
Sorry for delay. I have some problem now.
I will create PR in 2 or 3 days. Thank you for your understanding.

**Comment by KMichel1030** [comment] 2024-05-14 06:41
@Pujan92 
I'm sorry but I still have some problem in dev env now.
So it will be a little bit delayed again. I will create PR asap.

**Comment by Pujan92** [comment] 2024-05-14 06:42
You can share the problem which you are facing, maybe I can help in that.

**Comment by KMichel1030** [comment] 2024-05-14 06:47
Currently, I'm upgrading macOS and xcode version. It will take some time.
Could you please let me know your current version of macos and xcode? It will be helpful for me.
I was using macos 13 and xcode 14.2. But I wasn't able to build ios version. So I'm upgrading version.

**Comment by Pujan92** [comment] 2024-05-14 06:52
I am using macos 14.4 and xcode 15.4.

As the issue only persists for iOS, you can raise a PR at least by confirming that it is working on other platforms. So I can start review.

**Comment by KMichel1030** [comment] 2024-05-14 06:56
@Pujan92 
Thank you. Now I'm in progress so I will raise PR tomorrow.

**Comment by KMichel1030** [comment] 2024-05-14 14:20
@Pujan92 
I've  created PR. Please check. Thank you.

**Comment by KMichel1030** [comment] 2024-05-20 21:10
@blimpich  cc: @Pujan92 
I'm very sorry for asking but I think we can expect price increase as we addressed two problems (although they are minor issues)
Please let me know if it's possible. Thank you.

**Comment by blimpich** [comment] 2024-05-20 21:13
We can make this a normal issue price I think considering the work done on it.

**Comment by JmillsExpensify** [comment] 2024-06-07 05:09
@Pujan92 Mind completing the BZ checklist above?

**Comment by JmillsExpensify** [comment] 2024-06-07 16:07
Thanks! Payment summary:

 - Contributor: @KMichel1030 $250
 - Contributor+: @Pujan92 $250

@Pujan92 Can you confirm you are still being paid via Upwork vs New Expensify?

**Comment by JmillsExpensify** [comment] 2024-06-07 16:26
Ok thanks for confirming! 

> 📣 @KMichel1030 You have been assigned to this job! Please apply to the [Upwork job](https://www.upwork.com/jobs/~01dfbe7a8e20d88932) and leave a comment on the Github issue letting us know when we can expect a PR to be ready for review 🧑‍💻 Once you apply to this job, your Upwork ID will be stored and you will be automatically hired for future jobs! Keep in mind: [Code of Conduct](https://github.com/Expensify/App/blob/main/CODE_OF_CONDUCT.md) | [Contributing](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) 📖

@KMichel1030 Please apply to the Upwork job when you have a moment.

**Comment by JmillsExpensify** [comment] 2024-06-07 16:27
@Pujan92 I've paid your contract in Upwork

**Comment by JmillsExpensify** [comment] 2024-06-10 16:48
@KMichel1030 friendly reminder to apply for the Upwork job.

**Comment by JmillsExpensify** [comment] 2024-06-19 04:21
Still waiting on contributor.

**Comment by JmillsExpensify** [comment] 2024-06-25 03:31
Still waiting on contributor.

**Comment by KMichel1030** [comment] 2024-06-25 15:59
@JmillsExpensify 
Sorry for late resposne.
Could you please send offer?

Contributor details
Your Expensify account email: kmichel1030@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01275086f4193c6d86

**Comment by JmillsExpensify** [comment] 2024-06-25 19:18
No worries. Offer sent!

**Comment by JmillsExpensify** [comment] 2024-06-26 16:40
All paid out. Thanks!

**Closed by JmillsExpensify** 2024-06-26 16:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
