### ISSUE TITLE
[$500] Workspace - Selected contact with green tick is not scrolled up &shown while inviting members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30517] opened 2023-10-27 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3.  Tap Workspaces
4. Tap on a Workspace
5. Tap Members
6. Tap on invite
7. Scroll down little bit and select a member

## Expected Result:
In workspace, while inviting members, when user scrolls down and selects a contact, the selected contact with green tick must be scrolled up &shown

## Actual Result:
In workspace, while inviting members, when user scrolls down and selects a contact, the selected contact with green tick is not scrolled up &shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/46765fa3-05ae-4fbe-b955-bb761079b015

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01adbd2c2b60d2a242</li>
        <li>Upwork Job ID: 1717912996294365184</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-10-27 15:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The members list does not scroll to the top to show the selected member immediately after selection.

### What is the root cause of that problem?
This seems to simply not have been implemented.

### What changes do you think we should make in order to solve the problem?
Honestly, I think this needs more product design consideration. Scrolling up on select can be jarring, especially in a multi-select field where the user is trying to select multiple options. They have to scroll back down to where they were after each selection.

If you want to maintain visibility of the selected options, I'd make the top section sticky to remain visible, but don't adjust scroll position so the user keeps their place.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by strepanier03** [comment] 2023-10-31 03:40
Since https://github.com/Expensify/App/pull/29848 is deployed to staging, I think we should hold on this until we can test again.

**Comment by strepanier03** [comment] 2023-11-02 18:13
Deployed to prod 8 hours ago but I'm out sick today so I'll test tomorrow.

**Comment by strepanier03** [comment] 2023-11-06 20:51
Forgot about this, testing now.

**Comment by strepanier03** [comment] 2023-11-06 20:54
I can confirm that this is working now, I am no longer able to reproduce the behavior this GH was created for.

**Comment by strepanier03** [comment] 2023-11-06 20:54
@sobitneupane - I believe we can just close this now as it was an internal report and we didn't hire a contributor to fix this. 

If you have no objections I'm going to close this out at the end of the day or tomorrow morning.

**Comment by sobitneupane** [comment] 2023-11-07 06:15
Yup. Good to close.

**Comment by mvtglobally** [comment] 2023-11-09 21:00
Issue not reproducible during KI retests. (First week)

**Comment by strepanier03** [comment] 2023-11-10 02:25
Closing, thanks all!

**Closed by strepanier03** 2023-11-10 02:25 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
