### ISSUE TITLE
"Missing translation" error appears on the receipt

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34903] opened 2024-01-22 16:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705799023291499

## Action Performed:
1. Scan 3 or 4 receipts

## Expected Result:
Able to create expense without any issues

## Actual Result:
2nd last receipt seems to be "stuck" and has surfaced a missing translation error. Also, the most recent receipt (from today) initially didn't let me scan/make a request (no receipt showed up the first time)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot_20240121-115549](https://github.com/Expensify/App/assets/43996225/24a46b4c-c5d1-4af8-bc2e-897d17655d98)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by stephanieelliott** [comment] 2024-02-04 18:01
Adding the retest label to see if we can repro this, moved to weekly in the meantime.

**Comment by stephanieelliott** [comment] 2024-02-04 18:02
Oh actually never mind this is a dupe of #34903

**Closed by stephanieelliott** 2024-02-04 18:02 UTC
Labels: Weekly, Needs Reproduction, Bug, retest-weekly
