### ISSUE TITLE
[HOLD for payment 2024-04-15] [HOLD for payment 2024-04-09] Split Scan - Group created from split scan does not use the same avatar style as manual split

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39254] opened 2024-03-29 15:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Note that the group chat avatar follows the new group avatar style
5. Go to FAB > Request money > Manual
6. Create a manual split request with two users with no chat history
7. Note that the group chat avatar follows the new group avatar style
8. Repeat Step 5 and 6 with scan split request

## Expected Result:
The group chat avatar from the group with split scan will follow the same style as group from manual split

## Actual Result:
The group chat avatar from the group with split scan does not follow the same style as group from manual split

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e9bec5e-8955-49c0-955b-5da10f3020a6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-29 15:57
@stitesExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-29 15:58
We think that this bug might be related to [#vip-split](https://expensify.enterprise.slack.com/archives/C05RECHFBEW)

**Comment by marcaaron** [comment] 2024-03-29 16:20
Thanks! This is expected behavior now. Since creating a Split will create a new Group Chat and not a Group DM (as we have deprecated creation of those).

**Comment by stitesExpensify** [comment] 2024-03-29 16:25
@marcaaron should this just be treated as a normal external issue then?

**Comment by stitesExpensify** [comment] 2024-03-29 16:29
Oh I didn't see that you re-assigned this to yourself. Thanks!

**Comment by marcaaron** [comment] 2024-03-29 16:43
I guess this doesn't _have to_ be a blocker. However, I'd like to try to fix it. It's be great to close the loop on newly created Group DMs with this next release. It unblocks us to start completely migrating off of them in the backend.

**Comment by kavimuru** [comment] 2024-04-01 21:08
Bug is fixed

https://github.com/Expensify/App/assets/43996225/af02d2b2-d945-4000-adad-15c780f32929

**Comment by marcaaron** [comment] 2024-04-16 00:48
Gonna close this as it was a regression on the first Group Chats PR. @s77rt let me know if we need to reopen.

**Closed by marcaaron** 2024-04-16 00:48 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
