### ISSUE TITLE
Compose box - ZIP files can now be dragged and dropped into the compose box in chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21547] opened 2023-06-26 01:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website https://staging.new.expensify.com/
2. Start a chat with another account
3. Upload ZIP file by dragging and dropping files in the conversation

## Expected Result:
Drag and drop is not supported for ZIP files. Therefore, the user should see the error message "Attachment is of the wrong type"

## Actual Result:
Drag-and-drop is not supported for ZIP files, but drag-and-drop is possible without an error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/13b3d2b7-8321-4591-8880-8d931933908d

![Bug6103492_Issue-1](https://github.com/Expensify/App/assets/78819774/a4b35414-12e4-4800-bf14-d403ba457210)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-06-26 20:04
Agreed. I'm not sure why we wouldn't support zip files. Further, you can upload them into NewDot today, and download them with no issues. This is working as expected. This feels like expected behavior to me, not a bug. Closing as no action is needed here.

**Closed by joekaufmanexpensify** 2023-06-26 20:04 UTC
Labels: Daily, Bug
