### ISSUE TITLE
[HOLD for payment 2024-11-29] [$250] Room - Create room whisper reappears when interacting with it after workspace is deleted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49940] opened 2024-09-30 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Send a mention of a non-existing room
4. Delete the workspace
5. Go to workspace chat
5. Click Yes on the whisper

## Expected Result:
The whisper should be removed once the workspace is deleted

## Actual Result:
The whisper is not removed after the workspace is deleted
When user selects Yes or No, the whisper disappears and reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d432c71d-ccb6-4fe9-b122-b69711a7eb9c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021840941316454719982</li>
        <li>Upwork Job ID: 1840941316454719982</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104326547</li>
<li>Krishna2323 | Contributor | 104326549</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by Nomanahmeda789** [comment] 2024-09-30 16:18
### **Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Room - Create room whisper reappears when interacting with it after workspace is deleted

**What is the root cause of that problem?**
We still displaying the whisper action although the workspace is deleted or the report is archived

**What changes do you think we should make in order to solve the problem?**
Need to implement logic that can conditionally render the "Create room whisper" based on the workspace's existence. A simple check is need to added before rendering the whisper to check that the workspace is still valid like this:

`if (!workspaceExists) return null;`

**Comment by huult** [comment] 2024-09-30 17:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Create room whisper reappears when interacting with it after workspace is deleted

### What is the root cause of that problem?

Currently, we are still showing whispers even when the workspace is deleted.
https://github.com/Expensify/App/blob/1d0fa649cef8726d406ab685475ac975da0f93bd/src/pages/home/report/ReportActionsList.tsx#L193-L197

### What changes do you think we should make in order to solve the problem?
We should add logic to check if it's a whisper, and if the workspace is deleted, then it should not be shown. Some thing like that:
```diff
// .src/pages/home/report/ReportActionsList.tsx#L188
+    const isArchivedRoom = ReportUtils.isArchivedRoom(report, reportNameValuePairs);

// .src/pages/home/report/ReportActionsList.tsx#L197
reportAction.errors) && 
- ReportActionsUtils.shouldReportActionBeVisible(reportAction, reportAction.reportActionID)
+ ReportActionsUtils.shouldReportActionBeVisible(reportAction, reportAction.reportActionID) &&
+                    (reportAction.actionName !== 'ACTIONABLEREPORTMENTIONWHISPER' || !isArchivedRoom)
```

<summary>
<details>POC

https://github.com/user-attachments/assets/86e52298-8fca-4531-8155-c19f0bc9b63c

</details>
</summary>

**Comment by greg-schroeder** [comment] 2024-10-01 19:01
Discussing [this](https://github.com/Expensify/App/issues/49940#issuecomment-2384766075) with the team

**Comment by greg-schroeder** [comment] 2024-10-02 00:37
@daledah I think in this case, it makes the most sense to me to just hide the whisper.

Reasoning: The whisper is there to help  the user take action that we think they might want to take. Since the chat is no longer active, and no action can be taken, we probably don't need to show you a message that is trying to help you take an action that's no longer possible

**Comment by greg-schroeder** [comment] 2024-10-14 21:49
PR is up an under review 👍

**Comment by greg-schroeder** [comment] 2024-10-24 20:41
PR review continues

**Comment by greg-schroeder** [comment] 2024-11-01 20:34
Same as above

**Comment by greg-schroeder** [comment] 2024-11-11 20:23
Work on PR continues

**Comment by greg-schroeder** [comment] 2024-11-20 21:48
Merged. Awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2024-12-01 20:38
Paid contracts via Upwork, filed regression issue

**Closed by greg-schroeder** 2024-12-01 20:38 UTC
Labels: External, Daily, Awaiting Payment, Bug
