### ISSUE TITLE
[HOLD for payment 2024-04-25] iOS - Thread - Unable to send a message after returning from thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40057] opened 2024-04-11 00:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found around PR** https://github.com/Expensify/App/pull/39454
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to chat
3. Send a message
4. Send a reply to the message in thread
5. Click on the header subtitle
6. Send a message
7. Note that user can send a message
8. Swipe right twice to return to the main chat but without highlight on the parent message
9. Send a message

## Expected Result:
User should be able to send a message

## Actual Result:
User is unable to send a message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4dec4fbe-ef37-45cf-8e31-1da6e2561695

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-11 00:21
@marcaaron  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by marcaaron** [comment] 2024-04-11 01:50
@jasperhuangg looks like there are a few issues linked to https://github.com/Expensify/App/pull/39454

Created a revert branch to help identify if any of the deploy blockers are related.

**Comment by roryabraham** [comment] 2024-04-15 23:26
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1713223601389679

**Comment by kavimuru** [comment] 2024-04-16 13:31
Issue not fixed in the build 1.4.62-10.


https://github.com/Expensify/App/assets/43996225/7682fe0c-4775-40df-a9d8-68f0477ea2f2

**Comment by mountiny** [comment] 2024-04-17 12:33
QA confirmed they [could not repro](https://expensify.slack.com/archives/C9YU7BX5M/p1713353586298109) this bug anymore in staging

**Closed** 2024-04-18 22:51 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
