### ISSUE TITLE
[PAYMENT DUE 2024-10-08][$500] Update Mozilla/pdf.js and remove patch

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#48124] opened 2024-08-27 21:05 UTC
Tracking issue to remove the patches we've added for mozila/pdf.js

- https://github.com/Expensify/App/issues/31209
- https://github.com/Expensify/App/issues/47810

We'll need an upstream PR to fix this issue https://github.com/wojtekmaj/react-pdf/issues/1062
And then verify the new version fixes this old issue we had from [here](https://github.com/Expensify/App/issues/31209), then to upgrade the version and remove the patches
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d46938f37bc659b7</li>
        <li>Upwork Job ID: 1828539622745768358</li>
        <li>Last Price Increase: 2024-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>CyberAndrii | Contributor | 103986598</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by thienlnam** [comment] 2024-08-27 22:31
We're looking for someone to make the upstream fix here

**Comment by sudomf** [comment] 2024-08-28 12:06
Hey @thienlnam. Can I get this as my first contribution to Expensify?

**Comment by sudomf** [comment] 2024-08-28 12:12
Contributor details
Your Expensify account email: mayke.sargento@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0117f5b3f18d3179e9

**Comment by thienlnam** [comment] 2024-08-28 16:49
@sudomf If you're interested, please read through the [contributing guide](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) - you'll need to submit a proposal and get selected by the C+ if you're interested in taking this on

**Comment by CyberAndrii** [comment] 2024-08-28 17:45
I looked into this, and the `loadingTask._worker.destroy();` workaround no longer works on the main branch. I think something might have changed in the pdf.js library. My changes so far: https://github.com/wojtekmaj/react-pdf/commit/b4c95947d9322e21032a11fca3815fae19b14db7

**Comment by jayeshmangwani** [comment] 2024-09-03 06:05
Not Overdue, we’re still awaiting proposals.

bumped on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1725343459234609)

**Comment by thienlnam** [comment] 2024-09-04 16:53
@CyberAndrii Are you still looking into this?

**Comment by CyberAndrii** [comment] 2024-09-04 17:26
No, I didn’t find a solution.

**Comment by thienlnam** [comment] 2024-09-09 21:48
Pending proposals

**Comment by jayeshmangwani** [comment] 2024-09-10 04:46
Awaiting proposals

**Comment by CyberAndrii** [comment] 2024-09-13 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Fix the “Worker was terminated” error in the upstream [`wojtekmaj/react-pdf`](https://github.com/wojtekmaj/react-pdf/tree/main) repo and upgrade our app to the fixed version.

### What is the root cause of that problem?

Pdf.js worker is being destroyed before pdf finishes loading.

### What changes do you think we should make in order to solve the problem?

#### Step 1: `wojtekmaj/react-pdf` PR

Wait until loading has finished before destroying the worker. All changes: https://github.com/wojtekmaj/react-pdf/commit/dc5cb45457dc80c24180146e6a55de00d42d955b

#### Step 2: `Expensify/react-fast-pdf` PR

Bump `react-pdf` to the latest version. Then update [this line](https://github.com/Expensify/react-fast-pdf/blob/caca9995681c18c54043c414996e1d8c94dd6a01/src/PDFPreviewer.tsx#L3) to `pdfjs-dist/build/pdf.worker.mjs` or `pdfjs-dist/legacy/build/pdf.worker.mjs`.

Possibly other changes (I haven't tested this yet).

#### Step 3:`Expensify/App` PR

Bump `react-fast-pdf` to the latest version and remove the patches. Then update [this line](https://github.com/Expensify/App/blob/d14b48bb23efe589e0c73eeeff9e8478a8e6b60b/src/types/modules/pdf.worker.d.ts#L1) to `pdfjs-dist/build/pdf.worker.mjs` or `pdfjs-dist/legacy/build/pdf.worker.mjs`.

**Comment by jayeshmangwani** [comment] 2024-09-14 09:30
@CyberAndrii Have you submitted the upstream PR?

**Comment by CyberAndrii** [comment] 2024-09-14 09:35
Not yet

**Comment by jayeshmangwani** [comment] 2024-09-14 09:43
You need to fix the issue upstream first (https://github.com/wojtekmaj/react-pdf/issues/1062). Once it's approved and merged upstream, Then we can test [this issue](https://github.com/Expensify/App/issues/31209) on the latest react-pdf and if its resolved then we can proceed with the PR on the our repo.

**Comment by jayeshmangwani** [comment] 2024-09-16 16:03
It looks like an upstream PR has been raised by @CyberAndrii https://github.com/wojtekmaj/react-pdf/pull/1877.

cc: @thienlnam

**Comment by jayeshmangwani** [comment] 2024-09-18 10:01
@CyberAndrii PR merged upstream 🥳 , Thanks.

**Comment by jayeshmangwani** [comment] 2024-09-18 10:33
> ...and released as react-pdf v9.1.1.

Thanks Wojciech, for promptly releasing the version.

**Comment by jayeshmangwani** [comment] 2024-09-18 10:38
@CyberAndrii Now we can remove the patch and update the react-pdf version. Please feel free to raise a PR.

**Comment by thienlnam** [comment] 2024-09-18 20:50
Woo awesome! Nice work 🎉

**Comment by CyberAndrii** [comment] 2024-09-21 10:28
`react-fast-pdf` [PR](https://github.com/Expensify/react-fast-pdf/pull/32) is ready in case you missed it.

@thienlnam please you run the workflows

**Comment by jayeshmangwani** [comment] 2024-09-23 06:24
Thanks for the ping, @CyberAndrii . I’m checking the react-fast-pdf PR now.

**Comment by jayeshmangwani** [comment] 2024-09-26 08:46
@CyberAndrii We're good to move the PR out of draft.

**Comment by CyberAndrii** [comment] 2024-10-07 19:11
Payment is due **2024-10-08** 

https://github.com/Expensify/App/pull/49527#issuecomment-2387307078

**Comment by thienlnam** [comment] 2024-10-08 18:02
Payment also due here cc @trjExpensify

**Comment by trjExpensify** [comment] 2024-10-08 22:12
Confirming payments as follows: 

- $500 to @CyberAndrii for the fix
- $500 to @jayeshmangwani for the C+ review

Is that right?

**Comment by trjExpensify** [comment] 2024-10-08 22:53
@CyberAndrii paid, @jayeshmangwani feel free to request. Closing!

**Closed by trjExpensify** 2024-10-08 22:53 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by garrettmknight** [comment] 2024-10-15 01:20
$250 approved for @jayeshmangwani

**Comment by QichenZhu** [comment] 2026-04-13 04:43
FYI, [the previous fix](https://github.com/wojtekmaj/react-pdf/pull/1877) for this issue caused [a crash](https://github.com/Expensify/App/issues/76303#issuecomment-3642821395). It's now fixed with PRs https://github.com/mozilla/pdf.js/pull/20503, https://github.com/Expensify/react-fast-pdf/pull/51, https://github.com/Expensify/react-fast-pdf/pull/52, and https://github.com/Expensify/App/pull/80160.
