### ISSUE TITLE
[HOLD on #39144] [$500] [MEDIUM] Distance - Blank fields when editing distance and returning online with distance editor open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34441] opened 2024-01-12 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Create a distance request.
3. Navigate to distance request details page.
4. Go offline.
5. Click Distance and edit distance.
6. Click Distance.
7. Go online with distance editor open.

## Expected Result:
The distance editor will not close and the details update accordingly.

## Actual Result:
After returning online, the distance editor closes automatically and all the fields become blank.
On web, mweb and desktop app, the fields remain blank until the page is revisited.
On Android and iOS app, the details are blank for a while but still receive update on its own.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/97919a16-130d-43b9-8a02-39d9ff4f7e11

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1e98db2d0a90542</li>
        <li>Upwork Job ID: 1745795410999205888</li>
        <li>Last Price Increase: 2024-01-26</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-12 13:56
# Proposal

## Please re-state the problem that we are trying to solve in this issue

After returning online, the distance editor closes automatically and all the fields become blank.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/964548a2adb3ed9e2572ad33456759176a01b76c/src/libs/actions/IOU.js#L962-L965

As mentioned above, there's no optimisticData for when changing waypoints while offline since the MapBox API calculations happen on the server and we only get a response from the server while online.

## What changes do you think we should make in order to solve the problem?

Add optimisticData that will show `TBD` in the missing data fields, following the model of other instances in the app where we await the server's response / calculations.

**Comment by stephanieelliott** [comment] 2024-01-16 22:30
Hey @situchan can you review [this proposal ](https://github.com/Expensify/App/issues/34441#issuecomment-1889569807)when you get a chance?

**Comment by situchan** [comment] 2024-01-19 16:35
reviewing proposal

**Comment by kmbcook** [comment] 2024-01-21 09:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Blank fields when editing distance and returning online with distance editor open.

### What is the root cause of that problem?
The component pages/EditRequestDistancePage sends components/DistanceRequest the id of the transaction, which is a problem since components/DistanceRequest actually modifies that transaction before the user presses Save, which ideally should never happen.

There is a completely separate cause for the problem of the distance editor closing automatically which might be resolved in a separate issue.

### What changes do you think we should make in order to solve the problem?
Only allow changes to be made to the transaction after the user presses Save. Change pages/EditRequestDistancePage so that it does not send the id of the current transaction to components/DistanceRequest. All that DistanceRequest actually needs are the current waypoints, and all that it actually returns to EditRequestDistancePage are the new waypoints, as parameters to the onSubmit function when the user presses Save. So to solve the problem, essentially only send waypoints to DistanceRequest, which can be done by creating a temporary transaction which only contains the current waypoints.

**Comment by kmbcook** [comment] 2024-01-23 03:34
@situchan I'll do my best. The expected result is that the field are not blank, and the actual result is that they are blank. My proposal addresses that problem, not the problem of the distance editor closing automatically. The blank fields occur because components/DistanceRequest sets the transaction to null. The reason it sets the transaction to null is because it is trying to undo any changes it may possibly have made, using a backup of the original transaction, which in this case doesn't work because the backup has been erased. In this case there is no longer a backup transaction. Yes, there is no backup transaction, but is a backup transaction necessary? No, not if DistanceRequest never changes the original transaction. When the user presses Save, DistanceRequest returns new waypoints to pages/EditRequestDistancePage, and EditRequestDistancePage uses those waypoints to modify the transaction. All that EditRequestDistancePage needs from DistanceRequest is new waypoints, and only if the user presses Save. There is no need for DistanceRequest to modify the transaction. DistanceRequest should not be allowed to make changes to the original transaction. Right now it is designed to make changes, and then undo those changes if the user does not press save. It is in the process of undoing, in this case, that the original transaction is accidentally set to null. A cause of the fields becoming blank is that DistanceRequest is permitted to make any changes at all to the original transaction. Why would we want to change the original transaction before the user presses Save? Doing so invites bugs, and does not provide any value.

**Comment by situchan** [comment] 2024-01-25 14:37
@bernhardoj thanks for the proposal. The root cause is correct. Do you mind sharing test branch to verify your solution?

**Comment by bernhardoj** [comment] 2024-01-26 08:11
@situchan So, I planned to use my main solution to fix the blank field issue (by using TRANSACTION_DRAFT when editing so we don't need backup) and my alternative solution for the auto-close distance page issue. Currently, we use `EditRequestDistancePage` which uses `DistanceRequest` component to do the distance edit, but I just remembered that we have a new component (from the money request refactor) called `IOURequestStepDistance` that already uses TRANSACTION_DRAFT when updating the waypoint and we have an ongoing [issue](https://github.com/Expensify/App/issues/34610) that will replace `EditRequestDistancePage` with `IOURequestStepDistance`.

It should solve the blank field issue, but not the auto-close issue. To avoid double work, I think we can hold for that cleanup issue and come back here once done.

For the auto-close issue, here is the diff:

<details>

<summary>diff</summary>

```diff
diff --git a/src/pages/EditRequestDistancePage.js b/src/pages/EditRequestDistancePage.js
index f3ea76a339..bb1cdc27bc 100644
--- a/src/pages/EditRequestDistancePage.js
+++ b/src/pages/EditRequestDistancePage.js
@@ -1,6 +1,6 @@
 import lodashGet from 'lodash/get';
 import PropTypes from 'prop-types';
-import React, {useEffect, useRef} from 'react';
+import React, {useEffect, useState, useRef} from 'react';
 import {withOnyx} from 'react-native-onyx';
 import _ from 'underscore';
 import DistanceRequest from '@components/DistanceRequest';
@@ -52,17 +52,25 @@ function EditRequestDistancePage({report, route, transaction, transactionBackup}
     const {isOffline} = useNetwork();
     const {translate} = useLocalize();
     const hasWaypointError = useRef(false);
-    const prevIsLoading = usePrevious(transaction.isLoading);
+    const [isLoading, setIsLoading] = useState(false);
+    const prevIsLoading = usePrevious(isLoading);
+
+    useEffect(() => {
+        if (transaction.isLoading) {
+            return;
+        }
+        setIsLoading(false);
+    }, [transaction.isLoading]);
 
     useEffect(() => {
         hasWaypointError.current = Boolean(lodashGet(transaction, 'errorFields.route') || lodashGet(transaction, 'errorFields.waypoints'));
 
         // When the loading goes from true to false, then we know the transaction has just been
         // saved to the server. Check for errors. If there are no errors, then the modal can be closed.
-        if (prevIsLoading && !transaction.isLoading && !hasWaypointError.current) {
+        if (prevIsLoading && !isLoading && !hasWaypointError.current) {
             Navigation.dismissModal(report.reportID);
         }
-    }, [transaction, prevIsLoading, report]);
+    }, [transaction, prevIsLoading, isLoading, report]);
 
     /**
      * Save the changes to the original transaction object
@@ -79,6 +87,7 @@ function EditRequestDistancePage({report, route, transaction, transactionBackup}
             return;
         }
 
+        setIsLoading(true);
         IOU.updateMoneyRequestDistance(transaction.transactionID, report.reportID, waypoints);
 
         // If the client is offline, then the modal can be closed as well (because there are no errors or other feedback to show them

```

</details>

**Comment by situchan** [comment] 2024-01-26 16:08
ok, thanks.
Holding for https://github.com/Expensify/App/issues/34610 makes sense

**Comment by situchan** [comment] 2024-01-29 14:43
Still holding

**Comment by stephanieelliott** [comment] 2024-01-30 04:46
Just noting that https://github.com/Expensify/App/issues/34610 is held on https://github.com/Expensify/App/issues/34613. Adjusting this issue to show HOLD status in the meantime.

**Comment by kmbcook** [comment] 2024-01-31 20:00
I thought I would make a comment to try to be helpful. It is a great idea to use a draft transaction to make any changes which have not yet been confirmed by the user pressing Save.

However, currently we are using a draft transaction as a backup. Using a draft transaction as a backup directly opposes the meaning of the word draft, which can cause problems. In fact, it already has. For example, I just noticed that in version 1.4.34-0, if you delete a waypoint from an existing distance request, it doesn't get deleted, BECAUSE the user presses Save to confirm waypoint deletion! If the user doesn't press Save, and instead dismisses the modal, the waypoint IS deleted! This strange behaviour which is the exact opposite of what you would expect is partially due to the fact that we are using a draft transaction as a backup. I suggest that we never use a draft transaction as a backup, as is done in `TransactionUtils.createBackupTransaction`.

**Comment by situchan** [comment] 2024-02-08 21:18
Still holding

**Comment by stephanieelliott** [comment] 2024-02-14 07:37
Still held on both https://github.com/Expensify/App/issues/34610 and https://github.com/Expensify/App/issues/34613.

**Comment by stephanieelliott** [comment] 2024-02-27 02:38
Still on hold for https://github.com/Expensify/App/issues/34610 (which is also still on hold)

**Comment by stephanieelliott** [comment] 2024-03-05 01:24
Still on hold, https://github.com/Expensify/App/issues/34610 also on hold

**Comment by stephanieelliott** [comment] 2024-03-11 23:02
Still on hold for https://github.com/Expensify/App/issues/34610 (which is also still on hold)

**Comment by stephanieelliott** [comment] 2024-03-19 01:51
Still held

**Comment by bernhardoj** [comment] 2024-03-23 06:34
The PR is merged but looks like there are a couple of regressions, let's keep holding until it's stable.

**Comment by bernhardoj** [comment] 2024-03-26 05:12
So, I just retested and both issues don't happen anymore. The blank field bug is fixed because we removed the backup logic (but I see they are reintroducing it [here](https://www.github.com/Expensify/App/pull/38911)) and the auto close bug is gone because we removed the loading logic when editing the distance. I'm not sure though whether it's intentional to remove the loading when editing the request.

Previously, when you edit a distance, the save button will show a loading indicator and the page will close only when the request is successful.

Now, pressing the Save button will immediately close the page.

**Comment by stephanieelliott** [comment] 2024-03-28 22:41
Yeah maybe https://github.com/Expensify/App/issues/37850 changed the loading behavior? Either way I think that is the intended behavior based on [OFFLINE_UX.md](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#a---optimistic-without-feedback-pattern. ). I also can't repro so it does seem like this is fixed, I suppose we can close?

**Comment by bernhardoj** [comment] 2024-03-29 09:58
> Yeah maybe https://github.com/Expensify/App/issues/37850 changed the loading behavior?

Oh, it's not that one. We are holding on to this [PR](https://github.com/Expensify/App/pull/35302) and that PR removes the behavior where users will see a loading when updating a distance routes/waypoints while online. I don't see any discussion from them about removing that behavior, so I'm confused whether it's expected or not.

If it's expected, then we can skip the auto-close issue. If not, then we need to reintroduce it and fix the auto-close page issue. Can you confirm this one, please?

> I suppose we can close?

I think we should hold longer. The reason we hold for https://github.com/Expensify/App/pull/35302 PR is because they are removing a logic that causes this GH bug, but I see they are [reintroducing](https://www.github.com/Expensify/App/pull/39144) that again because that causes another bug. So, if that's merged, then we may need to proceed with my initial solution.

**Comment by stephanieelliott** [comment] 2024-04-04 23:04
> Now, pressing the Save button will immediately close the page.

This is the intended behavior, so it seems like we are good on this piece! 

> I think we should hold longer. The reason we hold for https://github.com/Expensify/App/pull/35302 PR is because they are removing a logic that causes this GH bug, but I see they are [reintroducing](https://www.github.com/Expensify/App/pull/39144) that again because that causes another bug. So, if that's merged, then we may need to proceed with my initial solution.

Ok, so are you saying that we should now hold on PR https://github.com/Expensify/App/pull/39144, then try testing again to see if it causes us to get the blank fields again?

**Comment by bernhardoj** [comment] 2024-04-05 03:23
Correct.

**Comment by stephanieelliott** [comment] 2024-04-08 21:42
Ok great makes sense, let's do that!

**Comment by stephanieelliott** [comment] 2024-04-15 22:06
https://github.com/Expensify/App/pull/39144 is undergoing QA, we'll take this off hold soon once that hits staging

**Comment by stephanieelliott** [comment] 2024-05-02 23:16
https://github.com/Expensify/App/pull/39144 was merged, just retested and the behavior is no longer happening -- that is, when coming back online the fields have updated and are not blank

**Closed by stephanieelliott** 2024-05-02 23:16 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
