### ISSUE TITLE
[Hold for payment 2024-08-27][$250] Expense - Composer in expense report disappears on Auditor's end after employee submits report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46364] opened 2024-07-27 16:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/46057
## Action Performed:
Precondition:
- Workspace is under Control plan with Advanced Approval workflow (set up on Old Dot)
- There are three members - Admin, Auditor and Employee
- Configure the Advanced Approval workflow so that the employee submits to the approver, who forwards to the owner, who finally approves the reports
1. Go to staging.new.expensify.com
2. [Employee] Go to workspace chat
3. [Employee] Submit two expenses
4. [Employee] Click Submit button to submit the report
5. [Auditor] Go to workspace chat with employee on ND
6. [Auditor] Click on the expense preview to go to the expense report

## Expected Result:
The composer in the expense report will not disappear

## Actual Result:
The composer in the expense report disappears on Auditor's end after employee submits the report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/80cc9c17-f026-4538-ae9f-13b2ac6331f0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8c40d850bdd6097</li>
        <li>Upwork Job ID: 1818262246842390946</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>HezekielT | Contributor | 103493084</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @HezekielT</details>

**Comment by lanitochka17** [comment] 2024-07-27 16:21
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-07-27 16:21
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by HezekielT** [comment] 2024-08-07 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Composer is hidden when auditor opens an expense report.

### What is root cause of that problem?

We show the composer if the user has `WRITE` permission among other checks.

https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/pages/home/report/ReportFooter.tsx#L206

https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/pages/home/report/ReportFooter.tsx#L114

https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/libs/ReportUtils.ts#L6416-L6426

Here we check the permission and if it is `WRITE` we return true otherwise false.

https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/libs/ReportUtils.ts#L1387-L1393

But an auditor has only `auditor` permission which is why the composer is hidden.

<img width="605" alt="Screenshot 2024-08-07 at 11 30 19 at night" src="https://github.com/user-attachments/assets/a98286f2-b1ae-4bdc-a1ed-5f85bcb435bb">

This is the root cause.

### What Changes do you think we should make in order to solve the problem?

Update the check to also check for auditor permission in addition to write permission so that the auditor can still have access to the composer.

https://github.com/Expensify/App/blob/6a6c242e79bb930b58146cb3e31f74d4e1fa0840/src/libs/ReportUtils.ts#L1388-L1390


```
if (Array.isArray(report?.permissions) && report?.permissions.length > 0) {
        return report?.permissions?.includes(CONST.REPORT.PERMISSIONS.WRITE) || report?.permissions?.includes(CONST.REPORT.PERMISSIONS.AUDITOR);
}
```


### What alternative solutions did you explore? (Optional)

Fix it from the backend by including write permission in addition to auditor.

**Comment by trjExpensify** [comment] 2024-08-09 21:56
>Workspace is under Control plan with Advanced Approval workflow (set up on Old Dot)

Moving to control.

**Comment by sonialiap** [comment] 2024-08-16 13:12
@lschurr I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for build

**Comment by bondydaa** [comment] 2024-08-26 22:20
hmm PR https://github.com/Expensify/App/pull/47408 was deployed to production last week, did some automation fail?

**Comment by lschurr** [comment] 2024-08-26 22:31
Seems like it @bondydaa! Payment date should be tomorrow. Updated.

**Comment by lschurr** [comment] 2024-08-29 05:34
Payment summary:

- Contributor: $250 @HezekielT ([paid in Upwork](https://www.upwork.com/nx/wm/workroom/38205843/overview))
- Reviewer: $250 @fedirjh (please request in NewDot)

**Closed by lschurr** 2024-08-29 05:34 UTC
Labels: Reviewing, External, Daily, Bug
