### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] Settings - On clear after never, status save does not work

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33168] opened 2023-12-15 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. If status already set then open the status by clicking besides settings OR set status from settings->profile->status and reopen status page
3. Set 'clear after' to never and save
4. Again open status and make any changes to message or emoji
5. Click on save and observe that now app does nothing

## Expected Result:
App should save the status on click on save on status page

## Actual Result:
App does nothing on click on save when clear after is set to Never on last save

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/33c66ad4-197a-4caf-afae-ae629c612de9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c57d019eaab2d964</li>
        <li>Upwork Job ID: 1736919348213882880</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28105137</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-12-17 14:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Once we set a status with clear never option, updating status again isn't working

### What is the root cause of that problem?
For a clear after `Never` option we are setting an empty string here.
https://github.com/Expensify/App/blob/990815f84567f39d4b84c45bf1952b306d0c4bfe/src/pages/settings/Profile/CustomStatus/StatusPage.js#L82-L86

But on mount while setting the draft status we are not using an empty string as `Never` here.
https://github.com/Expensify/App/blob/990815f84567f39d4b84c45bf1952b306d0c4bfe/src/pages/settings/Profile/CustomStatus/StatusPage.js#L108-L113

### What changes do you think we should make in order to solve the problem?
On mount logic consider an empty string as a value `Never` for draft custom status bcoz the else block will executes when we have existing status details.

```
User.updateDraftCustomStatus({clearAfter: currentUserClearAfter || CONST.CUSTOM_STATUS_TYPES.NEVER});
```

https://github.com/Expensify/App/blob/990815f84567f39d4b84c45bf1952b306d0c4bfe/src/pages/settings/Profile/CustomStatus/StatusPage.js#L112

**Comment by jasperhuangg** [comment] 2023-12-19 01:19
We discussed [here](https://expensify.slack.com/archives/C07J32337/p1702930893664949?thread_ts=1702886675.081259&cid=C07J32337) and decided this isn't a deploy blocker since it's a back-end issue

**Comment by Pujan92** [comment] 2023-12-19 19:34
@jasperhuangg isn't this a front-end issue where we are not setting the correct value for draft status `clearAfter`?

**Comment by jasperhuangg** [comment] 2024-01-02 03:15
@Pujan92 I've clarified with @stitesExpensify since he's been in charge of the back-end fix for this.

**Comment by johnmlee101** [comment] 2024-01-02 21:19
Waiting on the above &

**Comment by stitesExpensify** [comment] 2024-01-10 20:36
@thesahindia can you please evaluate the proposals? After coming back and looking at this again, I believe this is a front end issue 😅

**Comment by DylanDylann** [comment] 2024-01-15 08:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does nothing on click on save when clear after is set to Never on last save

### What is the root cause of that problem?
We have inconsistency between FE and BE when we set `clear after: never`
- In FE, we save `clear after: never` as draft
<img width="501" alt="Screenshot 2024-01-15 at 14 45 21" 
src="https://github.com/Expensify/App/assets/141406735/80f948a2-4097-4b5b-b2e5-0b602fa6dde7">

- But when calling API we pass `clear after:''` as a parameter and the BE also returns `clear after:''`

So that we should accept both values: 'never' and empty string for this case

https://github.com/Expensify/App/blob/f268c39c331305c49dbb80a0d0e59984289ecb25/src/pages/settings/Profile/CustomStatus/StatusPage.js#L78

But here we don't check if  clearAfterTime isn't empty string
 
### What changes do you think we should make in order to solve the problem?
I think we only should make it consistent and only use one value: "never" or empty string for both FE and BE
1. If using empty string, we don't need to update from BE. We only need to update draft value in the FE to empty string instead of "never" and replace the condition to empty string instead of "never"
2. If using "never" value (I think it will be more clear), we need to update from BE side to return `clear after: never` in FE we also replace some places to use "never" value instead of empty string
### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2024-01-17 07:41
PR is ready

cc: @thesahindia

**Comment by johnmlee101** [comment] 2024-01-30 20:52
Holding on payment still

**Comment by adelekennedy** [comment] 2024-01-31 16:36
Payouts due:

Contributor: $500 @bernhardoj (Upwork)
Contributor+: $500 @thesahindia (NewDot)

Upwork job is [here](https://www.upwork.com/ab/feedbacks/c/1328455843768528896/contract/36042490).

**Closed** 2024-01-31 19:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-04-10 18:10
$500 approved for @thesahindia
