### ISSUE TITLE
[$250] QBO - Sending message with Enter key shows QBO export warning pop-up

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48170] opened 2024-08-28 12:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-10
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4896447
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense to the workspace chat.
4. In the main chat, pay elsewhere the report.
5. Click Mark as manually entered on the expense preview in the main chat.
6. Click Mark as manually entered button again.
7. Click Yes, export again.
8. Type anything on the composer.
9. Send the message by hitting Enter.

## Expected Result:
Message is sent without QBO export warning pop-up.

## Actual Result:
Message is sent with QBO export warning pop-up when sending message with Enter key.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/91d6d13a-4792-43f5-8b14-1447d65a5ea0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011edb5fb3e9d5b97a</li>
        <li>Upwork Job ID: 1828778510854892649</li>
        <li>Last Price Increase: 2024-09-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-08-28 12:48
We think that this bug might be related to #wave-collect - Release 1

**Comment by mountiny** [comment] 2024-08-28 12:56
This seems like a super specific flow so demoting and marking as external, seems like some focus trap issue

**Comment by NJ-2020** [comment] 2024-08-28 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
QBO - Sending message with Enter key shows QBO export warning pop-up
### What is the root cause of that problem?
Inside the ExportDropdownMenu we listen if the user press the enter button
https://github.com/Expensify/App/blob/5356ff8df5dc82eb071e1660ef8c6bfe55326931/src/components/ReportActionItem/ExportWithDropdownMenu.tsx#L101-L106
Even we refresh the page the bug will still show because we listen to the user whenever the user press the enter button
### What changes do you think we should make in order to solve the problem?
We will enable the `pressOnEnter` if the user focus on the button i.e we can use `onKeyDown` to the button 
Or we can check if the button is not focus by using `useRef`
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-08-28 16:19
@NJ-2020 Thanks for the proposal. Can you please elaborate your RCA? The `pressOnEnter` is not the only factor that's taken when capturing the enter key press. https://github.com/Expensify/App/blob/2ff9f65007b1016fe357b65ff0f6a224c96c63ed/src/components/Button/index.tsx#L160

**Comment by s77rt** [comment] 2024-08-28 16:20
cc @Krishna2323 https://github.com/Expensify/App/pull/47705 seems related

**Comment by s77rt** [comment] 2024-09-02 21:08
Not overdue. Waiting on https://github.com/Expensify/App/pull/48128

**Comment by s77rt** [comment] 2024-09-06 23:41
This should be fixed already. @Krishna2323 can you please confirm the same?

**Comment by s77rt** [comment] 2024-09-11 19:15
^

**Comment by trjExpensify** [comment] 2024-09-12 00:04
>@anmurali or @nkuoch Let's close this

Closing.

**Closed by trjExpensify** 2024-09-12 00:04 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
