### ISSUE TITLE
 In “Track Distance” error not shown for invalid number but after saving highlights on writing each number.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19793] opened 2023-05-30 02:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Go to "Settings."
2.	Click on " Workspaces."
3.	Click on “Reimbursements”.
4.	Click on “Track Distances”.
5.	Write an invalid rate beyond three decimal place and press save
6.	Notice on clicking “Save” error message will appear
7.	Delete all and write same numbers again, observe that it will now become number sensitive and will throw error after three decimal place
## Expected Result: 
Error should reflect after 3 decimal place from the start.
## Actual Result:
 Error is not reflecting after 3 decimal place at first.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bb309c0a-672b-410a-afc4-6c5d7d189636

https://github.com/Expensify/App/assets/43996225/71f54a80-3005-4302-9421-916824d801f2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685135583192019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-05-30 02:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In “Track Distance” error is not reflected at first for an invalid number but after saving highlights on writing each number.
### What is the root cause of that problem?
The error display behavior is expected, but we have an issue in "rate" value.
we round "Rate" value before saving here toFixed(3), that is mean we allow user to type decimal value more than 3.
https://github.com/Expensify/App/blob/37163b099b57cc996657a62a4afc1110dff3ed65/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L62
but in "rate" validate we only accept decimal with max 3 numbers `\d{0,3}`
https://github.com/Expensify/App/blob/37163b099b57cc996657a62a4afc1110dff3ed65/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L96

### What changes do you think we should make in order to solve the problem?
We need to remove the limit `{0,3}` on decimal value here `\d{0,3}` from validation because we already round it before saving.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sethraj14** [comment] 2023-05-30 06:03
@kavimuru @dukenv0307 
This issue looks similar to [this](https://github.com/Expensify/App/issues/19779), both are due to no validation in the rate input. It can also be fixed using the same solution (If this needs to be fixed).

**Comment by strepanier03** [comment] 2023-05-30 22:46
Hmmm, I think I'll raise this and the other GH internally to see if we want to make a change.

**Comment by strepanier03** [comment] 2023-05-30 22:54
Raised for discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1685487184419559).

**Comment by strepanier03** [comment] 2023-05-31 19:51
Consensus in the discussion is this isn't a bug and intended. We aren't going to make a change now and the other related GH was also closed. Closing this one as well!

**Closed by strepanier03** 2023-05-31 19:51 UTC
Labels: Daily, Bug
