### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000] Web - Multi word zones do not work while searching for Timezones

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23543] opened 2023-07-25 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Profile -> Timezone;
2. Uncheck the "Automatically determine your location." checkbox;
3. Click on "Timezone";
4. Input a multi word zone such as "New York", "Isle of Man", "East Indiana" in the search text;
5. Verify that no results appear.

## Expected Result:
Multi word Timezones should appear in the results.

## Actual Result:
Multi word Timezones do not appear in the results.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/41eb48e1-4bd9-4b4b-84db-93f81c5dbc25

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DanutGavrus
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1690204863367949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183d12241aacbaee9</li>
        <li>Upwork Job ID: 1687242846389854208</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26186832</li>
<li>DanutGavrus | Contributor | 26186835</li>
<li>DanutGavrus | Reporter | 26186836</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-25 12:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Multi word zones do not work while searching for Timezones
### What is the root cause of that problem?
When searching for a timezone, we do not replace existing "_" and "-" with " ", so 2 or more words zones will not appear when searched for:
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/settings/Profile/TimezoneSelectPage.js#L105-L110
### What changes do you think we should make in order to solve the problem?
We should replace "_" & "-" with " " when filtering timezones:
```js
timezoneOptions: _.filter(this.allTimezones, (tz) => tz.text.replace('_', ' ').replace('-', ' ').toLowerCase().includes(searchText.trim().toLowerCase())),
``` (edited)

**Comment by alexpensify** [comment] 2023-07-27 21:49
I've run out of time and will test soon.

**Comment by alexpensify** [comment] 2023-07-28 20:53
I'm OOO today. I'll try to review it over the weekend.

**Comment by alexpensify** [comment] 2023-07-31 22:54
Not overdue - still on my testing lists

**Comment by alexpensify** [comment] 2023-08-02 17:52
Closing - I am unable to replicate this experience while using Google Chrome: 


![2023-08-02_10-45-50](https://github.com/Expensify/App/assets/8107070/7f233e81-5c10-4991-8445-218cf30d978a)

**Comment by DanutGavrus** [comment] 2023-08-03 07:58
@alexpensify I think that the [Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1690204863367949) also has some context which may help for better understanding of the bug.

**Comment by alexpensify** [comment] 2023-08-03 23:23
Ok, I see the issue now. I misunderstood this: 

>Input a multi word zone such as "New York", "Isle of Man", "East Indiana" in the search text;

You have to input two-word cities to generate this error.

**Comment by alexpensify** [comment] 2023-08-03 23:24
@fedirjh when you get a chance, can you please review the proposals? Thank you!

**Comment by bhs324** [comment] 2023-08-04 04:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Multi word zones do not work while searching for Timezones

### What is the root cause of that problem?

Multi-word timezones are entered with the '_' character instead of a space. It cannot be searched with spaces, as it simply compares only those that contain the same string.

### What changes do you think we should make in order to solve the problem?

Currently, timezone is entered with '_', but we don't know what other characters will be entered in the future.
To add flexibility to the search, we need to use a regular expression.
Jetbrains, a popular IDE, provides a very handy search feature called [Search Everywhere](https://www.jetbrains.com/help/idea/searching-everywhere.html).
![image](https://github.com/Expensify/App/assets/22151180/fdc0f72a-4e1b-4856-a54b-28f22552b2f0)

We can create a similar "Search Everywhere" feature using the following code.

[TimezoneSelectPage.js:105](src/pages/settings/Profile/TimezoneSelectPage.js)
```javascript
filterShownTimezones(searchText) {
  this.setState({
    timezoneInputText: searchText,
    timezoneOptions: _.filter(this.allTimezones, (tz) => new RegExp(searchText.trim().replace(/\s+/, '.*'), 'i').test(tz.text)),
  });
}
```

![image](https://github.com/Expensify/App/assets/22151180/a4d715ef-5f9c-4129-99d5-642c279158e7)

### What alternative solutions did you explore? (Optional)

N/A

**Comment by bhs324** [comment] 2023-08-04 04:20
Contributor details
Your Expensify account email: bhs.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e6efc57c0fbf82a1

**Comment by Chirayu31** [comment] 2023-08-04 06:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The current time zone search functionality is hindered by the presence of underscores in time zone names, which affects the effectiveness of the search. For instance, "New York" is represented as "New_York," causing the search to yield inaccurate results. This issue impacts the user experience and diminishes the efficiency of the search feature.

### What is the root cause of that problem?

The root cause of this problem lies in the way the search functionality treats underscores in time zone names. The current implementation does not account for underscores, leading to mismatches during the search.

### What changes do you think we should make in order to solve the problem?

To enhance the timezone search functionality and address the underscore issue, I propose the following changes:

1. **Normalize Search Text**: Modify the search process by normalizing the search text before performing the match. The normalization process involves the following steps:

      - Trim the search text to remove leading and trailing spaces.
      - Convert the search text to lowercase.
      - Replace multiple consecutive spaces with a single space.

2. **Updated Filtering with Underscore Handling:** Utilize the normalized search text to filter the available timezones. Perform the filtering using the includes method after replacing underscores with spaces in both the search text and timezone names.

By implementing these changes, we ensure that the search functionality accurately captures timezone names, even when they contain underscores. The normalization process and underscore handling in the filtering process work together to provide a more reliable and user-friendly search experience.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Chirayu31** [comment] 2023-08-04 06:57
Contributor details
Your Expensify account email: chirayu.work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d0a4568198c0ceb4

**Comment by Chirayu31** [comment] 2023-08-04 07:00
Contributor details
Your Expensify account email: [chirayu.work@gmail.com](mailto:chirayu.work@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d0a4568198c0ceb4

**Comment by Chirayu31** [comment] 2023-08-04 07:01
Contributor details
Your Expensify account email: chirayu.work@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d0a4568198c0ceb4

**Comment by alexpensify** [comment] 2023-08-06 16:57
Update: Under proposal review

**Comment by DanutGavrus** [comment] 2023-08-08 22:20
Just a small note: [this Proposal](https://github.com/Expensify/App/issues/23543#issuecomment-1649775795) comes before [this Proposal](https://github.com/Expensify/App/issues/23543#issuecomment-1649774773) as it's from the original Slack thread.

**Comment by bhs324** [comment] 2023-08-09 00:58
@fedirjh Thank you for the feedback. I updated my proposal. `replace(/\s+/, '.*')` -> `replaceAll(/\s+/g, '.*')`

**Comment by alexpensify** [comment] 2023-08-10 16:58
@fedirjh when you get a chance, can you review the recent comments? Thanks!

**Comment by DanutGavrus** [comment] 2023-08-11 20:57
@fedirjh 
> Your proposal doesn’t cover the multi-whitespace search, e.g `South      Georgia`

Didn't know we should cover this case as well. If anything, I've updated my Proposal too. (Can't actually update is as it's posted by kbecciv, so I'll leave the updated Proposal under here). I've tested, and see the `Europe/Isle_of_Man` result, with what I though a user may use for search: `"Isle of Man", "Isleof", "Isl o M", "Eur Isl", "isleof man", "IsleOfMan", "man of isle", "   Isle   Man   "`.  

From here, you may choose whichever is more functional/was first with same functionality. Thanks!

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Multi word zones do not work while searching for Timezones
### What is the root cause of that problem?
When searching for a timezone, we only *trim* and make the search *case insensitive* with no other processing:
https://github.com/Expensify/App/blob/f0a6977223c3f2a82b9ff53ea899b5076e3de372/src/pages/settings/Profile/TimezoneSelectPage.js#L63-L66

### What changes do you think we should make in order to solve the problem?
We should improve the search functionality as follows:
```js
const filterShownTimezones = (searchText) => {
    setTimezoneInputText(searchText);
    setTimezoneOptions(_.filter(allTimezones.current, (tz) => {
        let shouldShow = true;
        searchText.toLowerCase().split(" ").forEach((word) => {
            if (tz.text.toLowerCase().replace(/[^a-z0-9\+\-]/g, '').indexOf(word) < 0) shouldShow = false;
        })
        return shouldShow;
    }));
};
```

**Comment by alexpensify** [comment] 2023-08-14 21:33
@fedirjh when you get a chance, can you review the updated proposal? Thanks!

**Comment by DanutGavrus** [comment] 2023-08-16 17:19
@samh-nl @fedirjh Forgot about `/`, sorry. Updated proposal as to use `.replace(/[^a-z0-9\+\-\/]/g, '')` instead of `.replace(/[^a-z0-9\+\-]/g, '')`. All the searches previously mentioned in the Proposal work as before, and now `Europe/Isl` also works. I could also make any other fine tuning in the PR(if the idea of the Proposal gets chosen, of course). Thanks!

**Comment by DanutGavrus** [comment] 2023-08-16 17:21
@samh-nl This would be the search results after the update
![image](https://github.com/Expensify/App/assets/56603839/17bc56a8-69f0-48e1-ad80-a3a6688e9d3c)

**Comment by alexpensify** [comment] 2023-08-18 21:39
Awesome, we will continue to follow along with the process.

**Comment by DanutGavrus** [comment] 2023-08-21 10:39
@fedirjh
PR ready for review: https://github.com/Expensify/App/pull/25569

**Comment by alexpensify** [comment] 2023-09-06 22:35
@bondydaa to prepare for payment day, can you review and approve the regression test? Thanks!

**Comment by alexpensify** [comment] 2023-09-07 23:35
Here is the payment summary: 

-  External issue reporter @DanutGavrus $250 
-  Contributor that fixed the issue @DanutGavrus $1000
-  Contributor+ that helped on the issue and/or PR @fedirjh $1000

Upwork Job: https://www.upwork.com/jobs/~0183d12241aacbaee9

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is no bonus here and I'm going to use the C+ approval date since there was a delay because of the US Bank Holiday. In saying that, it was 5 business days-- no bonus and no penalties.

**Comment by alexpensify** [comment] 2023-09-07 23:45
Everyone has been paid in Upwork!

**Comment by alexpensify** [comment] 2023-09-08 23:17
@bondydaa - let me know if you agree with the regression test and I can create that GH.

**Comment by bondydaa** [comment] 2023-09-11 23:03
👍 to the suggested steps.

Though I'm wondering if we could somehow create an automated unit test for this component https://github.com/Expensify/App/tree/main/tests/unit? 

my brain is dead today so not sure what that all would entail but if we can I'd prefer automate tests over manual ones.

**Comment by alexpensify** [comment] 2023-09-12 22:36
Thanks, I'm OOO until Thursday and will create the regression test then.

**Comment by alexpensify** [comment] 2023-09-15 19:10
The regression test request has been created, so I'm going to close now.

**Closed by alexpensify** 2023-09-15 19:10 UTC
Labels: External, Weekly, Awaiting Payment, Bug
