### ISSUE TITLE
iOS - App crashes after adding workspace avatar in new account offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13277] opened 2022-12-02 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with a new account
2. Navigate to a Workspace settings
3. Disable the internet connection in the device
4. Upload new avatar, Verify you see the avatar grayed out a bit
5. Go back online, Verify the avatar is not grayed out anymore & that it updates in all pages and chats

## Expected Result:
App is not crashed after adding a workspace avatar in a new account offline

## Actual Result:
App is crashed after adding a workspace avatar in a new account offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.35.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205352838-f70815a3-69d7-4bfd-984d-792f4f36ed88.mp4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-12-02 21:43
Took a couple stabs at reproducing this both locally on a simulator and on my physical iOS and haven't been able to. Here's one pass through:

https://user-images.githubusercontent.com/7277067/205395041-0501c236-08c9-42b3-a864-ca59eb1a8b33.MP4

The avatar does toggle back to the default when coming back online for a bit, but the app doesn't crash. Curious to hear how @jliexpensify fares attempting to repro though!

**Comment by jliexpensify** [comment] 2022-12-04 22:37
@amyevans I tried on my end, and am seeing the same behaviour as you: there isn't a crash but I am seeing the default avatar.

I'm on v1.2.36-1 (Android). @kbecciv are you seeing the same thing when you update your app?

**Comment by kbecciv** [comment] 2022-12-07 20:30
@jliexpensify Checking with team, update you shortly

**Comment by kbecciv** [comment] 2022-12-07 20:58
@jliexpensify Tester is able to reproduced in IOS app with build 1.2.36.2, please attached a new video.

https://user-images.githubusercontent.com/93399543/206294268-a63eb26a-b04d-4411-b692-649aacc5b987.mp4

**Comment by kbecciv** [comment] 2022-12-07 21:06
@jliexpensify Let me know if we need to re-test in Android app.

**Comment by jliexpensify** [comment] 2022-12-07 21:22
Around halfway through the video, the tester seems to be copying the link into a different app to test on Staging: 

![image](https://user-images.githubusercontent.com/30815269/206298923-0a2893a9-4f6a-4e18-87c7-16bf03e97b20.png)

@amyevans - did you also test on staging?

**Comment by amyevans** [comment] 2022-12-08 23:13
Yeah I was testing on staging, although the bug report says that it's reproducible on production, too.

I found logs for the 12/7 recording from andreylazutkinutest+071222@gmail.com above though.

I also tried reproducing a few more times on a dev build on my iPhone and reproduced it once. It's not reproducible every time which is just the funnest type of bug 😬.

It's an error from the API though, so this is definitely `Internal`.

**Comment by amyevans** [comment] 2022-12-08 23:29
[Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2277600f9f7e61301c-LAX%22)+AND+timestamp:[2022-12-07T19:37:45.678Z+TO+2022-12-07T21:37:45.678Z]&index=logs_expensify-019879) from the error.

![Screenshot 2022-12-08 at 6 28 16 PM](https://user-images.githubusercontent.com/7277067/206588355-5f8c63e3-31e1-4142-a872-45d6d03333f0.png)

We're getting a reportID collision.

**Comment by jliexpensify** [comment] 2022-12-08 23:39
@amyevans - awesome, thanks for the context. Given it's internal, would you be taking this one (i.e. no need for Upworks)?

**Comment by amyevans** [comment] 2022-12-08 23:41
Yeah no need for Upwork! You can unassign yourself if you want 😄

**Comment by amyevans** [comment] 2022-12-12 22:10
Continuing to work on, I've still only been able to reproduce once locally so not much to go on. I've been reviewing the code of the commands involved both on the App side and Web side but nothing sticking out to me as blatantly wrong.

**Comment by JmillsExpensify** [comment] 2022-12-26 22:04
This bug will hit the 30 day mark next week, so we need to start ironing out next steps. The reportID collision is pretty weird, as I'm not clear why we'd get that for updating a workspace avatar? Is that collision due to a workspace chat? Again though, let's create a Slack thread on this issue and start pushing it forward so that it's not blocking us from WAQ next week.

**Comment by JmillsExpensify** [comment] 2022-12-29 19:32
We need to retain a daily on this issue given my comment above.

**Comment by AndrewGable** [comment] 2023-01-02 22:26
Not sure if it helps but I tried reproducing this one a few times and was unable to get it to 💥

**Comment by AndrewGable** [comment] 2023-01-02 22:28
This might be similar according to the LogSearch @amyevans shared: https://github.com/Expensify/App/issues/13738

**Comment by JmillsExpensify** [comment] 2023-01-03 01:20
I got the crash on this. Details shared in Slack.

**Comment by amyevans** [comment] 2023-01-03 18:04
Discussing in Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1672681095936359

Logs from Jason's crash: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227837e5cc7c5824e2-SJC%22)+AND+timestamp:[2023-01-03T00:17:56.615Z+TO+2023-01-03T02:17:56.615Z]&index=logs_expensify-020256

**Comment by JmillsExpensify** [comment] 2023-01-03 22:29
Closing this issue in favor of the [new issue](https://github.com/Expensify/App/issues/13907#issuecomment-1368779185) that details the root cause. Thank you @amyevans!

**Closed by JmillsExpensify** 2023-01-03 22:29 UTC
Labels: Daily, Internal, Bug
