### ISSUE TITLE
[Hold for #29080] [$500]  Chat - The first option in Notifications preference is always highlighted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31087] opened 2023-11-09 00:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30694
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Click on the chat header
4. Click Notification preference

## Expected Result:
The selected option is highlighted

## Actual Result:
The first option is always highlighted
On iOS, the selected option is highlighted. The first option becomes highlighted when returning to app from the background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/fc184fab-d871-4f99-b056-e4e05407b5c6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8a2b72f459ff260</li>
        <li>Upwork Job ID: 1722404757021065216</li>
        <li>Last Price Increase: 2023-11-09</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-11-09 00:16
Related to https://github.com/Expensify/App/issues/29080#issuecomment-1800896596

**Comment by wlegolas** [comment] 2023-11-09 01:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Chat - The first option in Notifications preference is always highlighted

### What is the root cause of that problem?

The problem is the `BaseSelectionList` component, there is an `useEffect` that resets the focus and scrolls to the first section when there is at least one section in the `section` array.

https://github.com/Expensify/App/blob/dee9b3110a7ebe0aa250c3f966d6a69925d916f4/src/components/SelectionList/BaseSelectionList.js#L340-L351

### What changes do you think we should make in order to solve the problem?

We should change this `useEffect` to only resets the focus and scroll to the first section when there is at least one section in the `section` array **and** there are no sections selected.

For example,

```
function shouldUpdateFocusedSection(sections) {
    const availableSections = lodashGet(sections, '[0].data', []);

    return _.all(availableSections, (section) => !section.isSelected);
}

function BaseSelectionList({
  ...

    useEffect(() => {
        // do not change focus on the first render, as it should focus on the selected item
        if (firstLayoutRef.current) {
            return;
        }

        // set the focus on the first item when the sections list is changed
        if (shouldUpdateFocusedSection(0)) {
            updateAndScrollToFocusedIndex(0);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [sections]);

    ...
});

```

### What alternative solutions did you explore? (Optional)

In the `main` branch there is the code with the solution from the issue above https://github.com/Expensify/App/issues/29080, but the problem still occurring. That's why I put this proposal.

**POC**

https://github.com/Expensify/App/assets/698363/b9d77922-2549-4be1-94ca-4453e62e469f

**Comment by sourcecodedeveloper** [comment] 2023-11-09 09:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The first option in the notification is highlighted instead of the selected option.

### What is the root cause of that problem?

The selected option is not being focused.

https://github.com/Expensify/App/blob/5df95a115bbc943a7149eee6eeb5ea7e5a64a32d/src/components/SelectionList/BaseSelectionList.js#L349

updateAndScrollToFocusedIndex is passing 0 as the focus index.

### What changes do you think we should make in order to solve the problem?
The focus index can be obtained from sections array.

const index = _.findIndex(sections[0].data, (section)=> section.isSelected === true);
updateAndScrollToFocusedIndex(index);

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:54
Hi, Will review again today, just back from weekend

**Comment by abdulrahuman5196** [comment] 2023-11-13 18:48
Seems there is multiple regressions from https://github.com/Expensify/App/issues/29080 and this could be a regression as well as pointed out by contributors.

@greg-schroeder Could you kindly put this issue on hold for https://github.com/Expensify/App/issues/29080?

**Comment by greg-schroeder** [comment] 2023-11-14 16:49
Putting this on hold!

**Comment by greg-schroeder** [comment] 2023-11-26 20:13
Still holding

**Comment by greg-schroeder** [comment] 2023-12-05 19:45
same

**Comment by greg-schroeder** [comment] 2023-12-19 03:10
Same

**Comment by greg-schroeder** [comment] 2023-12-31 10:31
Same

**Comment by greg-schroeder** [comment] 2024-01-08 20:25
""

**Comment by greg-schroeder** [comment] 2024-01-26 19:09
Same

**Comment by greg-schroeder** [comment] 2024-02-06 01:29
#29080 is still open

**Comment by greg-schroeder** [comment] 2024-02-27 03:48
29080 is deployed

**Comment by greg-schroeder** [comment] 2024-02-27 03:48
@abdulrahuman5196 what do you think about this issue given that the hold issue is deployed? It's been a while - do we need to retest, or can we proceed?

**Comment by abdulrahuman5196** [comment] 2024-02-27 07:36
@greg-schroeder I don't see this issue in staging. I think we can close this issue.


https://github.com/Expensify/App/assets/46707890/9722a8a4-1687-45d4-ab50-77858f19c86e

**Comment by greg-schroeder** [comment] 2024-03-02 00:09
I can't see it either, seems to be resolved. Closing!

**Closed by greg-schroeder** 2024-03-02 00:09 UTC
Labels: External, Weekly, Bug
