### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] Web - Details - Tooltip not present on split bill details side panel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20052] opened 2023-06-02 13:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Split a bill with multiple accounts
2. Open the split bill group
3. Click on the header to open the details side panel showing the group members
4. Hover over the accounts and the avatars and observe there is a tooltip
5. Go back and click on the split bill IOU card to open the details side panel
6. Hover over the accounts and their avatars

## Expected Result:
Tooltip should show up with their emails

## Actual Result:
Tooltip not present on split bill details side panel

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/896c10f0-52e0-49b5-9cb5-3e5fd401cf9e

https://github.com/Expensify/App/assets/93399543/b20c580c-b334-4d28-8dd0-487f95ad4d10

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685513538554379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017795e0b76d1faee5</li>
        <li>Upwork Job ID: 1665798844286881792</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-02 22:50
I think this is the same as - https://github.com/Expensify/App/issues/20086 - asking

**Comment by Christinadobrzyn** [comment] 2023-06-05 19:12
@esh-g you're right - these are different! Thanks for clarifying!

**Comment by Christinadobrzyn** [comment] 2023-06-07 20:45
waiting on proposals

**Comment by esh-g** [comment] 2023-06-10 01:52
https://github.com/Expensify/App/issues/20052#issuecomment-1573716590

@eVoloshchak @Christinadobrzyn bump on proposal review 😇

**Comment by jeet-dhandha** [comment] 2023-06-10 08:47
# Proposal
## Please re-state the problem that we are trying to solve
There are no tooltips in `SplitBillDetailsPage`

## What is the root cause of that problem?
1. Tooltips are not enabled. So have to fix that.
2. There is inconsistency in the return details of participants. 
3. Numbers show `@expensify.sms` at the end. 

## What changes do you think we should make in order to solve the problem?
Solution:
1. Add `showTitleTooltip` prop to `OptionsSelector` in `MoneyRequestConformationList.js`.
2. We will make few updates in `OptionsListUtils.js`.
    - This updates make sures that code has same common params.

```js
import * as PersonalDetails from './actions/PersonalDetails'; // + Added

... rest code

/**
 * Get the participant options for a report.
 * @param {Object} report
 * @param {Array<Object>} personalDetails
 * @returns {Array}
 */
function getParticipantsOptions(report, personalDetails) {
    const participants = lodashGet(report, 'participants', []);
    return _.map(getPersonalDetailsForLogins(participants, personalDetails), (details) => ({
        keyForList: details.login,
        login: details.login,
        text: details.displayName,
        firstName: lodashGet(details, 'firstName', ''),
        lastName: lodashGet(details, 'lastName', ''),
        alternateText: Str.isSMSLogin(details.login || '') ? LocalePhoneNumber.formatPhoneNumber(details.login) : details.login,
        icons: [UserUtils.getUserAvatarIconObject(details.avatar, details.login)], // + Changed to a common function getUserAvatarIconObject
        payPalMeAddress: lodashGet(details, 'payPalMeAddress', ''),
        phoneNumber: lodashGet(details, 'phoneNumber', ''),
    }));
}

...rest code

// + Added Function
/**
 * @param {Object} personalDetail - personalDetail of the user
 * @return {Object} commonParams - amount of the IOU
 */
function getCommonPersonalDetails(personalDetail) {
    const displayName = PersonalDetails.getDisplayName(personalDetail.login, personalDetail);
    return {
        text: displayName,
        login: personalDetail.login,
        displayName,
        participantsList: [{login: personalDetail.login, displayName}],
        icons: [UserUtils.getUserAvatarIconObject(personalDetail.avatar, personalDetail.login)], // Used a common function getUserAvatarIconObject
    }
}

/**
 * Build the IOUConfirmation options for showing the payee personalDetail
 *
 * @param {Object} personalDetail
 * @param {String} amountText
 * @returns {Object}
 */
function getIOUConfirmationOptionsFromPayeePersonalDetail(personalDetail, amountText) {
    return {
        alternateText: personalDetail.login,
        descriptiveText: amountText,
        ...getCommonPersonalDetails(personalDetail)
    };
}

/**
 * Build the IOUConfirmationOptions for showing participants
 *
 * @param {Array} participants
 * @param {String} amountText
 * @returns {Array}
 */
function getIOUConfirmationOptionsFromParticipants(participants, amountText) {
    return _.map(participants, (participant) => ({
        ...participant,
        ...getCommonPersonalDetails(participant),
        descriptiveText: amountText,
    }));
}

...rest code

```

3. We will update `UserUtils.js` to make sure that we have a common function to get the avatar icon object.

```js
import * as LocalePhoneNumber from './LocalePhoneNumber'; // + Added

...rest code

/**
 * Provided a source URL, if source is a default avatar, return the associated SVG.
 * Otherwise, return the URL pointing to a user-uploaded avatar.
 *
 * @param {String} avatarURL - the avatar source from user's personalDetails
 * @param {String} login - the email of the user
 * @returns {String|Function}
 */
function getUserAvatarIconObject(avatarURL, login) {
    return {
        source: getAvatar(avatarURL, login),
        name: LocalePhoneNumber.formatPhoneNumber(login),
        type: CONST.ICON_TYPE_AVATAR,
    };
}

...rest code

export {

    ...rest code

    getUserAvatarIconObject, // + Added
};
```

4. Updating `ReportParticipantsPage.js`  to fix the `@expensify.sms` displaying for numbers.

```js
// import CONST from '../CONST'; - Removed as not used

... rest code

/**
 * Returns all the participants in the active report
 *
 * @param {Object} report The active report object
 * @param {Object} personalDetails The personal details of the users
 * @return {Array}
 */
const getAllParticipants = (report, personalDetails) => {
    const {participants} = report;

    return _.chain(participants)
        .map((login) => {
            const userLogin = Str.removeSMSDomain(login);
            const userPersonalDetail = lodashGet(personalDetails, login, {displayName: userLogin, avatar: ''});

            return {
                alternateText: userLogin,
                displayName: userPersonalDetail.displayName,
                accountID: userPersonalDetail.accountID,
                icons: [UserUtils.getUserAvatarIconObject(userPersonalDetail.avatar, login)], // + Used a common function getUserAvatarIconObject
                keyForList: userLogin,
                login,
                text: userPersonalDetail.displayName,
                tooltipText: userLogin,
                participantsList: [{login, displayName: userPersonalDetail.displayName}],
            };
        })
        .sortBy((participant) => participant.displayName.toLowerCase())
        .value();
};

...rest code

```


# Before Fix:

https://github.com/Expensify/App/assets/78416198/4ed9c46f-445b-496e-8a3c-a6f02e95d38b

# After Fix:

https://github.com/Expensify/App/assets/78416198/4785ae10-0d69-4341-9d51-785ee74421b9



### What alternative solutions did you explore? (Optional)
N/A

**Comment by cristipaval** [comment] 2023-06-12 08:38
@eVoloshchak has to review the proposals

**Comment by eVoloshchak** [comment] 2023-06-13 13:13
@esh-g's [proposal](https://github.com/Expensify/App/issues/20052#issuecomment-1573716590) looks good to me!

`MoneyRequestConfirmationList.js` was recently refactored, so exact prop names in proposal are outdated, but I agree with the general approach

🎀👀🎀 C+ reviewed!
cc: @cristipaval

**Comment by esh-g** [comment] 2023-06-14 11:34
@cristipaval @eVoloshchak PR is here: https://github.com/Expensify/App/pull/20742

**Comment by jeet-dhandha** [comment] 2023-06-14 17:41
@eVoloshchak https://github.com/Expensify/App/issues/20052#issuecomment-1585568107 - Please review and comment on my proposal as where the code is going wrong or right. So that i know how to give my proposals better.

**Comment by eVoloshchak** [comment] 2023-06-16 15:35
@jeet-dhandha, your proposal is quite similar to @esh-g's proposal, with the exception of different changes to OptionsListUtils. Generally, the first proposal to correctly identify a root cause and to propose a fix for it - is a winning proposal. In this case time was the deciding factor, since both proposals are similar and both do resolve the issue

Nonetheless, thank you for the proposal, and excited to work with you on other issues in the future!

**Comment by Christinadobrzyn** [comment] 2023-06-16 17:45
moving to weekly while PR is reviewed

**Comment by eVoloshchak** [comment] 2023-06-16 17:47
PR was merged yesterday, will be deployed to staging soon

**Comment by eVoloshchak** [comment] 2023-06-28 17:44
I don't think the BZ checklist is applicable here, this was a feature request, not a bug

**Comment by esh-g** [comment] 2023-06-29 03:28
@Christinadobrzyn I have sent a proposal on upwork. Here is my profile link: https://www.upwork.com/freelancers/~0186b1d7cc69656f22

**Comment by Christinadobrzyn** [comment] 2023-06-30 19:04
So sorry for the delay on this, i don't know how I missed this payment. 

Paid @esh-g for contributor + 50% speed bonus
Paid @Nathan-Mulugeta $250 as reporter

Pending hire for @eVoloshchak - you'll also have the speed bonus. 

Internal job posting - https://www.upwork.com/ab/applicants/1665798844286881792/job-details
External job posting - https://www.upwork.com/ab/applicants/1665798844286881792/job-details

@eVoloshchak feel free to accept the offer when you can and I'll pay this out! Sorry again for the delay

**Comment by eVoloshchak** [comment] 2023-07-02 18:05
@Christinadobrzyn, no worries, thanks!
I'll request the payment via NewDot instead, in a day or two

**Comment by Christinadobrzyn** [comment] 2023-07-03 17:39
hey @eVoloshchak I don't think I have the ability to pay you with a company card via NewDot... is that a new thing?

**Comment by Christinadobrzyn** [comment] 2023-07-03 22:05
Ah, found this - https://expensify.slack.com/archives/C02NK2DQWUX/p1686871517189609 - let me know when you reach out for payment @eVoloshchak

**Comment by eVoloshchak** [comment] 2023-07-06 17:16
Requested the payment via NewDot

**Comment by Christinadobrzyn** [comment] 2023-07-06 20:15
Awesome @eVoloshchak! I think this GH can be closed because I think the payment happens outside my control and through our accounting team. Do you want to confirm when you get paid and I'll keep tracking this?

**Comment by eVoloshchak** [comment] 2023-07-06 21:03
> I think this GH can be closed because I think the payment happens outside my control and through our accounting team

Yeah, this can be closed, payment has been released, we can always open if there's a problem

**Closed** 2023-07-06 22:33 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-07 11:56
Paid @eVoloshchak
