### ISSUE TITLE
[HOLD for payment 2023-11-13] [$125] Android - Distance - Amount in the Distance e-receipt is cut off when device font size is minimum

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29616] opened 2023-10-14 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: Device font size is set to minimum (on Samsung)
1. Launch New Expensify app
2. Open a Distance expense page
3. Tap on the receipt

## Expected Result:
The amount in the Distance e-receipt is not cut off

## Actual Result:
The amount in the Distance e-receipt is cut off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/73e87890-7bc0-495c-9318-0b3470e9bf60

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01705b24e4119f4226</li>
        <li>Upwork Job ID: 1713629774323441664</li>
        <li>Last Price Increase: 2023-10-22</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27362909</li>
<li>ZhenjaHorbach | Contributor | 27362910</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-15 18:56
I dont think this is a blocker, but we should fix it cc @neil-marcellini

**Comment by mountiny** [comment] 2023-10-15 18:56
Setting the price to $125 because this is super specific design issue with most likely easy fix

**Comment by deetergp** [comment] 2023-10-18 15:28
Still waiting on more proposals?

**Comment by mvtglobally** [comment] 2023-10-27 00:44
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2023-11-13 17:57
Payments finalised, please complete the BZ checklist when you get a chance @fedirjh

**Comment by bfitzexpensify** [comment] 2023-11-15 18:18
Great, thanks @fedirjh. We're all done here, closing this one out.

**Closed by bfitzexpensify** 2023-11-15 18:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
