### ISSUE TITLE
Chat- Unexpected error when requesting money in Workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19035] opened 2023-05-16 16:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18783

## Action Performed:
1. Open [www.staging.new.expensify.com.](http://www.staging.new.expensify.com./)
2. Sign into a valid account.
3. Create a new Workspace.
4. Invite any user.
5. Request money through Workspace

## Expected Result:
There is NO unexpected error when requesting money in Workspace chat

## Actual Result:
Unexpected error when requesting money in Workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/29d095e1-7fc5-40e2-8672-3e826afba97b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2023-05-16 17:24
The error I get is `"404 Account not found, possible bad authToken?"`
<img width="1571" alt="Screenshot 2023-05-16 at 10 23 29 AM" src="https://github.com/Expensify/App/assets/4741899/ade2151d-3ef9-42ce-bd99-dfc4e37f8f72">

**Comment by yuwenmemon** [comment] 2023-05-16 17:28
@luacmartins Can you take a look at this? I believe it's happening because a workspace doesn't have an email... so what should happen [here](https://github.com/Expensify/Web-Expensify/blob/146cfd8286aa18096cac46a166400e08d3a86dae/lib/TransactionAPI.php#L898)?

**Comment by luacmartins** [comment] 2023-05-16 17:38
@marcaaron is already addressing it [here](https://github.com/Expensify/Auth/pull/7934)

**Comment by yuwenmemon** [comment] 2023-05-16 17:44
Talked here: https://expensify.slack.com/archives/C07J32337/p1684258261571739 NAB for the NewDot deploy.

**Comment by tjferriss** [comment] 2023-05-18 12:40
I'm not able to reproduce this issue. I also see the related PR has been merged to production. So are we OK to close this or does it warrant further investigation?

**Comment by trjExpensify** [comment] 2023-05-18 12:57
Pretty sure Marc got to this one. 👍

**Closed by trjExpensify** 2023-05-18 12:57 UTC
Labels: Reviewing, Daily, Bug
