### ISSUE TITLE
Web - Workspace - No notification is received from the #Admin Room when creating workspace in OD

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49383] opened 2024-09-18 11:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4975714
**Email or phone of affected tester (no customers):** applausetester+shsbnotf@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Make sure that notifications is enabled in the device

1. Create a new Expensifail account in New Dot
2. Navigate to another tab and leave the New Expensify tab in the background
3. In the other tab navigate to OldDot (Log in with the same account that you signed in New Dot )
4. Create a Control or Collect policy - this will assign a Guide to the account for policy setup
5. Wait for a notification to be received from the #Admin Room

## Expected Result:
A notification is received in the device from the #Admin Room

## Actual Result:
A notification is not received in the device from the #Admin Room

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/57c265a2-9473-4822-89c6-35ef85241758

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2024-09-18 14:02
@IuliiaHerets could you clarify if the #admins room was actually created?

**Comment by MariaHCD** [comment] 2024-09-18 14:27
So I think we need to clarify what the expected behavior on ND when a workspace is created from OD cc: @mallenexpensify 

But I don't think this should block the App deploy. The behavior is the same on prod, there is no #admins room created.

**Comment by IuliiaHerets** [comment] 2024-09-18 19:47
@MariaHCD Tester can no longer repro the issue, it was fixed, build - v9.0.37-3

https://github.com/user-attachments/assets/0297caf5-3bf2-4962-b933-a71df7e17f2d

**Comment by mallenexpensify** [comment] 2024-09-18 21:10
> there is no #admins room created.

I have an admin room created in NewDot for both staging and production tests. I **don't** see this message though
<img width="716" alt="image" src="https://github.com/user-attachments/assets/cda08367-1702-4948-9aab-7cd1e306a63a">

This is what I see
<img width="705" alt="image" src="https://github.com/user-attachments/assets/5cda5f35-99c4-4c68-a4ef-e4c77dea160d">

Because I'm not receiving the chat, I'm therefore not receiving the browser notification.

**Comment by MariaHCD** [comment] 2024-09-19 12:52
Looks like the welcome messages that are sent in the SendAssignedGuideMessaging job wasn't received during @mallenexpensify's test.

I don't see a failed SendAssignedGuideMessaging job for that policyID.

@MonilBhavsar would you know why the SendAssignedGuideMessaging seemingly either wasn't queued or failed (and I can't find it) for the test above?

**Comment by MariaHCD** [comment] 2024-09-23 08:39
@IuliiaHerets can we retest this so we can ensure it has been fixed?

**Comment by IuliiaHerets** [comment] 2024-09-23 13:37
@MariaHCD Issue was fixed, not reproduced now

https://github.com/user-attachments/assets/2ffa7b27-595d-404a-a263-3962a99797a5

**Comment by mallenexpensify** [comment] 2024-09-23 19:16
Thanks @IuliiaHerets before closing, I'd like to get @MonilBhavsar 's 👀 
> @MonilBhavsar would you know why the SendAssignedGuideMessaging seemingly either wasn't queued or failed (and I can't find it) for the test above?

**Comment by MonilBhavsar** [comment] 2024-09-24 07:50
Sorry missed it!

This is known and feature and not a bug.

In case of applause, we always assign QA guide. And since guide is assigned we queue SendAssignedGuideMessaging job.

In case of @mallenexpensify's case, since it was alias email, we didn't assign guide and hence no SendAssignedGuideMessaging job.

Code reference
https://github.com/Expensify/Web-Expensify/blob/445bdea689684e1d6842ec3ba435624f34b08017/lib/Policy/Utils.php#L1138-L1141

**Closed** 2024-09-24 08:47 UTC
Labels: Engineering, Daily, Bug

**Comment by mallenexpensify** [comment] 2024-09-24 21:34
Thanks @MonilBhavsar !!
