### ISSUE TITLE
[$250] Chat - New message line marker shown in the wrong position

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49525] opened 2024-09-20 11:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Receive multiple messages from another account
3. Open another report and open the chat again to remove the unread marker
4. Reply in thread on one of the sent messages
5. Send a reply and go back by using the from link

## Expected Result:
No new line marker gets shown

## Actual Result:
New line marker shown under the message which has a reply

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ea4af4d2-d0ff-4b2d-8e02-c9117c53f66d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021838488357896477944</li>
        <li>Upwork Job ID: 1838488357896477944</li>
        <li>Last Price Increase: 2024-09-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 11:09
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by klajdipaja** [comment] 2024-09-24 08:28
We have a PR that addresses a different bug in the mark as unread functionality from [issue#47817](https://github.com/Expensify/App/issues/47817) that I worked on. The result of that PR is that the marker line does not show on the main chat when a message in a thread is marked unread.
If it is expected that the thread itself also shows as unread than I can work on this issue after the initial one is merged. 

FYI @mollfpr

**Comment by bernhardoj** [comment] 2024-09-24 13:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New message marker is shown after coming back from a thread.

### What is the root cause of that problem?
When we coming back from a thread, only part of the report actions are shown in the list. Let say we have message 1-5, go to thread 2 and come back, only message 1-2 are initially visible becuase of comment linking. There is a `useEffect` that updates the `unreadMarkerTime` to the last action `created` time. In our case, the `unreadMarkerTime` is updated to message 2 `created` time.
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/pages/home/report/ReportActionsList.tsx#L276-L286

When all report actions are rendered, the `unreadMarkerReportActionID` will return the 3rd message ID because the `created` value is bigger than `unreadMarkerTime`.
https://github.com/Expensify/App/blob/accea60e318386b02971baab3a563160ce8259b5/src/pages/home/report/ReportActionsList.tsx#L223-L246

This happens after https://github.com/Expensify/App/pull/48445. Previously, we only update `unreadMarkerTime` when receiving new message, that is if the last action `created` value is bigger than the current report `lastReadTime`. But it's not complete because it doesn't update the `unreadMarkerTime` when the last action is deleted, which is what https://github.com/Expensify/App/pull/48445 is fixing.

### What changes do you think we should make in order to solve the problem?

Since the `useEffect` purpose is updating the `unreadMarkerTime` when adding/deleting message, then we can ignore effect when on mount.
```
useEffect(() => {
    if (firstRenderRef.current) {
        firstRenderRef.current = false;
        return;
    }
    ...

    setUnreadMarkerTime(mostRecentReportActionCreated);
    setMessageManuallyMarkedUnread(0);
}, [sortedVisibleReportActions]);
```

**Comment by s77rt** [comment] 2024-09-25 02:08
@bernhardoj Thanks for the proposal.

> There is a useEffect that updates the unreadMarkerTime to the last action created time. In our case, the unreadMarkerTime is updated to message 2 created time.

This seems to be where things take a wrong turn. The previous logic makes more sense because the unread marker should not be less than the report last read time. i think it's best to revert the recent change and find another solution to https://github.com/Expensify/App/issues/47735

**Comment by bernhardoj** [comment] 2024-09-26 02:56
So, looks like https://github.com/Expensify/App/pull/49367 causes this issue, but reverting https://github.com/Expensify/App/pull/48445 will solve this.

**Comment by klajdipaja** [comment] 2024-09-26 05:03
@bernhardoj this issue was opened before #49367 was merged so I don't think it caused it

**Comment by s77rt** [comment] 2024-09-26 10:38
@bernhardoj After discussion we will just have the assigned C+ on the linked issue revert the PR

**Comment by s77rt** [comment] 2024-09-26 10:44
🎀 👀 🎀 For engineer PR revert review

**Comment by dangrous** [comment] 2024-09-26 15:04
Left one comment on the linked PR.

Do I need to assign anyone here or are we all set/

**Comment by s77rt** [comment] 2024-09-26 17:18
All set

**Closed** 2024-09-26 18:32 UTC
Labels: Reviewing, External, Weekly, Help Wanted, Bug

**Comment by s77rt** [comment] 2024-09-28 14:14
No checklist needed. We just reverted the offending PR.
