### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] App loses focus from compose box on clicking same chat in LHN for the 2nd time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20865] opened 2023-06-15 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any chat and start typing to select an emoji (e.g. :hea) and observe that App opens the compose box
3. Reclick on same chat in LHN and observe that focus is lost from compose box (i.e. you don't see the list of emojis)

## Expected Result: 
App should keep the focus on compose box whenever we click on chat in LHN

## Actual Result: 
App loses focus from compose box on reclicking on same chat in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.29.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1b27368e-353a-4845-baf5-52e6359438c8

https://github.com/Expensify/App/assets/43996225/28aa7f3a-357d-4fff-a797-78df04515da6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686293905214069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fc6dbe666a661d7</li>
        <li>Upwork Job ID: 1670574342491840512</li>
        <li>Last Price Increase: 2023-06-18</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-16 07:03
I'm on Staging (v1.3.28-5) and I don't think this is anb issue anymore?

https://github.com/Expensify/App/assets/30815269/c021840f-8f60-401d-a206-bd334d39c12d

Please re-test on the newest version and re-open with a video + repro steps if it is an issue, thanks!

**Comment by dhanashree-sawant** [comment] 2023-06-17 03:38
Hi @jliexpensify, you will need to click twice i.e. reclick on same chat in LHN to reproduce it. 

https://github.com/Expensify/App/assets/87513216/27ec58c8-bbb0-4125-80de-9db299d3175e

**Comment by jliexpensify** [comment] 2023-06-18 23:20
@dhanashree-sawant I notice that you've found the issue by selecting the mode from "All" to "Focus", which wasn't in the original GH. I'll re-test now.

**Comment by jliexpensify** [comment] 2023-06-18 23:26
On v1.3.29-0, can reproduce - thanks @dhanashree-sawant

**Comment by jliexpensify** [comment] 2023-06-21 21:59
Bump @Santhosh-Sellavel as we have a proposal

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 18:25
@tienifr 
Why we need to `e.preventDefault()` ?

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 18:25
Sorry for the delay somehow I missed this!

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 19:18
@tienifr your proposal is not working for me!

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 19:48
> open the setting page and close it

I tried but didn't works though

https://github.com/Expensify/App/assets/85645967/30acbc71-6da1-4ec6-9707-564d058f46f5

Thanks for reminding https://github.com/Expensify/App/issues/16098!
If this is dependent on that then we should wait here as this issue is not super urgent. When it comes off hold, if the issue exists(It may get fixed there) your proposal will be prioritized. Thanks @tienifr!

@jliexpensify Please add HOLD to title thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 20:10
Yeah, I did add that. I messed up the other condition. 🤦 I used && instead of || earlier Sorry @tienifr!

```js
showReportPage(option) {
        if (this.props.isCreateMenuOpen || this.props.currentReportId === option.reportID) {
            // Prevent opening Report page when click LHN row quickly after clicking FAB icon
            return;
        }
        Navigation.navigate(ROUTES.getReportRoute(option.reportID));
        this.props.onLinkClick();
    }

```

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 20:12
@tienifr's [proposal](https://github.com/Expensify/App/issues/20865#issuecomment-1596492042) looks good to me. We are good to hire @tienifr for this one!

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 16:03
Bump @MonilBhavsar for Proposal review!

**Comment by MonilBhavsar** [comment] 2023-06-28 10:19
Sorry, I was ooo. Just catching up. Looking soon...

**Comment by MonilBhavsar** [comment] 2023-06-28 11:03
> If users click on the different chat, the ReportActionCompose will be unmounted and mounted again so the input is focused, but if they click on the same chat, the ReportActionCompose is not unmounted, that why we can see the text input is blurred.

Looks good to me. But, would like to clarify solution to root cause If I am getting it correctly.
We return early in SideBarLink.js, prevent navigating to another report, and that in turn fixes the unmounting of 
ReportActionCompose component?

Could be addressed in a PR, but let's return early

```
if(this.props.currentReportId === option.reportID) {
    return;
}
```

**Comment by Santhosh-Sellavel** [comment] 2023-06-28 11:40
Yeah that's what we should do in as in comment  https://github.com/Expensify/App/issues/20865#issuecomment-1604887532 we can group or add separately, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 21:03
@tienifr Can you answer this?

> We return early in SideBarLink.js, prevent navigating to another report, and that in turn fixes the unmounting of
ReportActionCompose component?

**Comment by MonilBhavsar** [comment] 2023-07-06 11:32
Thanks for clarifying! That makes sense now. Sorry, it took some time. I would say let's add comment that why we're doing fixes at both places

**Comment by jliexpensify** [comment] 2023-07-10 00:44
Hired @dhanashree-sawant . @Santhosh-Sellavel are you being paid via New.Dot?

**Comment by Santhosh-Sellavel** [comment] 2023-07-11 21:34
@jliexpensify Yes will be via Newdot, please cancel offer thanks!

**Comment by jliexpensify** [comment] 2023-07-11 21:57
Weird, no offer to cancel!

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:47
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: N/A
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not sure about this?
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. Yes
> * [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> * [ ]  [@jliexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2023-07-26 01:48
### Regression Steps

**Test on Desktop App & Desktop Web only**

1. Login with any account
2. Open any chat
3. Verify that the composer is focused
4. Click on the same chat in LHN
5. Verify that the composer does not lose focus

👍  or  👎

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 23:59
@jliexpensify Can you leave a comment confirm amount to be paid for C & C+ So I can proceed with Request on ND, thanks!

**Comment by jliexpensify** [comment] 2023-07-31 01:22
Payments:

- Bug Reporter: @dhanashree-sawant $250
- Contributor: @tienifr $1000
- @C+: @Santhosh-Sellavel $1000

@MonilBhavsar - [are you good with this as the Regression Test](https://github.com/Expensify/App/issues/20865#issuecomment-1650849514) before I pay out?

**Comment by MonilBhavsar** [comment] 2023-07-31 06:02
Yes, looks good to me

**Comment by jliexpensify** [comment] 2023-07-31 06:10
Paid out, job closed. @Santhosh-Sellavel please request payment via New.Dot.

**Closed by jliexpensify** 2023-07-31 06:10 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-04 04:04
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
