### ISSUE TITLE
[HOLD for payment 2024-09-24] [$250] Advanced approval - RHP turns to not here page while dismissing after deleting the workflow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48089] opened 2024-08-27 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Workflows.
3. Click Add approval workflow.
4. Select user for "Expenses from" and "Approval".
5. Click Add workflow on confirmation page.
6. Click on the added workflow.
7. Click Delete.
8. Delete the worfklow.

## Expected Result:
RHP will close without turning to not here page after deleting the workflow.

## Actual Result:
RHP closes while briefly displaying the not here page after deleting the workflow.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1146" alt="Bug6583988_1724749616436!Screenshot_2024-08-27_at_17 03 38" src="https://github.com/user-attachments/assets/7227b9be-5d4e-414a-b7d4-68b90f78a4c8">

https://github.com/user-attachments/assets/91e8399a-4fb9-4128-8b57-eeff830180ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b0021bbcd2e0b55</li>
        <li>Upwork Job ID: 1828575300443505062</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 103807249</li>
</ul></li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-27 13:59
We think that this bug might be related to #wave-control

**Comment by nkdengineer** [comment] 2024-08-27 15:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
RHP turns to not here page while dismissing after deleting the workflow.

### What is the root cause of that problem?
This comes from https://github.com/Expensify/App/pull/47845

Let's see the condition to show the not found page here. When we confirm delete, the `currentApprovalWorkflow` can be updated before we close the RHP then the not found page display briefly

https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L88-L90

### What changes do you think we should make in order to solve the problem?
We should check if the `currentApprovalWorkflow` just changed to empty we will not show not found page. We can use `usePrevious` hook for `currentApprovalWorkflow` then only show not found page if both `currentApprovalWorkflow` and `prevCurrentApprovalWorkflow` is empty

```
const prevCurrentApprovalWorkflow = usePrevious(currentApprovalWorkflow);
    // eslint-disable-next-line rulesdir/no-negated-variables
    const shouldShowNotFoundView =
        (isEmptyObject(policy) && !isLoadingReportData) ||
        !PolicyUtils.isPolicyAdmin(policy) ||
        PolicyUtils.isPendingDeletePolicy(policy) ||
        (!currentApprovalWorkflow && !prevCurrentApprovalWorkflow);

```
https://github.com/Expensify/App/blob/6ca91cddfbb4bbcd0ca24c9f10549057b6fd7332/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L88-L90

### What alternative solutions did you explore? (Optional)

**Comment by srikarparsi** [comment] 2024-08-27 15:57
Hi @dylanexpensify, do you think you could help confirm what the expected behavior is here? I believe the RHP should close, it's just that the Not here page briefly shows while the RHP closes. Is that expected? Also ccing @tgolen and @muttmuure based on this [thread](https://github.com/Expensify/App/issues/47697).

**Comment by srikarparsi** [comment] 2024-08-27 16:00
Also demoting this as it is very minute and the feature is currently behind a beta - https://github.com/Expensify/App/blob/80f7d1eb08680f1e4994b782d5fd002a99c34b49/src/libs/Permissions.ts#L24

**Comment by blazejkustra** [comment] 2024-08-27 19:45
> I believe the RHP should close, it's just that the Not here page briefly shows while the RHP closes. Is that expected?

That's exactly it, we don't want to show `NotFoundPage` for a brief moment.

**Comment by srikarparsi** [comment] 2024-08-27 23:28
Cool thanks, updated the issue description and making this external

**Comment by srikarparsi** [comment] 2024-09-04 04:38
Cool, assigning @Krishna2323

**Comment by blazejkustra** [comment] 2024-09-05 05:28
@Krishna2323 When can we expect a PR for this? 👀

**Comment by greg-schroeder** [comment] 2024-09-09 06:32
PR still in review

**Comment by greg-schroeder** [comment] 2024-09-11 09:37
Same as above

**Comment by greg-schroeder** [comment] 2024-09-17 00:59
PR merged and deployed to staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2024-09-19 01:15
Deployed to prod 9/17

**Comment by greg-schroeder** [comment] 2024-09-19 01:15
Not overdue

**Comment by greg-schroeder** [comment] 2024-09-19 01:16
Updated title and payment date to account for failed automation

**Comment by greg-schroeder** [comment] 2024-09-23 02:55
Payment summary:

Contributor: @Krishna2323 - $250 - will be paid via Upwork on 9/24
C+: @Ollyws - $250 - Can make a manual request via ND on 9/24

**Comment by greg-schroeder** [comment] 2024-09-25 02:34
Upwork contracts paid

**Closed by greg-schroeder** 2024-09-25 02:34 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-26 15:41
$250 approved for @Ollyws
