### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] LHN - Extra spaces between text is not displayed on LHN (works fine on android app)

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27586] opened 2023-09-16 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send text with more then 1 space in between
4. Observe LHN
5. Send text with lots of space between text too trigger 3 dots in LHN
6. Edit the text and observe that it displays the full text for sometime before removing some to display 3 dots

## Expected Result:
App should display all extra space between text in LHN and app should directly display 3 dots in LHN if text is big

## Actual Result:
 Extra spaces between text is not displayed on LHN and on edit, app displays full text for sometime before changing some to 3 dots

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bf287ee3-6314-4ae9-8482-2c2fc29133eb

https://github.com/Expensify/App/assets/78819774/9ee29531-b7f0-40ed-974b-dba8145bd570

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694605928056549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014293d43d0d5d8fcf</li>
        <li>Upwork Job ID: 1703106405263683584</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26848353</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-16 17:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Extra spaces between text is not displayed on LHN (works fine on android app)

### What is the root cause of that problem?
- Because of using whiteSpace: noWrap for the LHN subtitle, all the extra spaces between text is not displayed
https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/components/LHNOptionsList/OptionRowLHN.js#L86-L91
 - To fix the issue:  [LHN alternativeText is also multilined](https://github.com/Expensify/App/pull/21664#issuecomment-1690209715), we have used the whiteSpace: noWrap style https://github.com/Expensify/App/pull/21664#discussion_r1306308035. 
 - But here https://github.com/Expensify/App/pull/25629, we have already changed the way to get the LHN subtitle, so the above bug is not appeared  


### What changes do you think we should make in order to solve the problem?
- As I mentioned in the RCA, now we can using whilteSpace: pre style with the LHN subtitle

### Result
![image](https://github.com/Expensify/App/assets/141406735/91bc529a-8ea2-4260-93ed-e24f04f032a0)

**Comment by MitchExpensify** [comment] 2023-09-19 16:44
How does @DylanDylann 's proposal look to you @robertKozik ?

**Comment by MitchExpensify** [comment] 2023-09-24 03:00
Assigning @DylanDylann looks like the next step here @danieldoglas

**Comment by DylanDylann** [comment] 2023-09-25 01:59
@robertKozik PR https://github.com/Expensify/App/pull/27822 is ready for review

**Comment by DylanDylann** [comment] 2023-09-28 03:23
The PR lasted a little longer than 3 days because of the timezone difference like [this issue](https://github.com/Expensify/App/issues/20765#issuecomment-1613171536). Are we eligible for a bonus here?

**Comment by MitchExpensify** [comment] 2023-10-03 22:33
**Payment summary:**

$250 @dhanashree-sawant Reporting (Please accept offer on the Upwok job here - https://www.upwork.com/jobs/~014293d43d0d5d8fcf) 
$750 @DylanDylann requires payment [offer](https://www.upwork.com/nx/wm/offer/26848353) (Contributor)

**Comment by MitchExpensify** [comment] 2023-10-03 22:33
Added a reminder to pay out on the 9th

**Comment by dhanashree-sawant** [comment] 2023-10-04 04:31
Hi @MitchExpensify, the following issue reporting bonus should had been 50$ but I have accepted the 250$ offer without cross checking 😅. Let me know what we can do to solve this issue.

**Comment by robertKozik** [comment] 2023-10-04 08:55
**BugZero Checklist:**
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21664
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21664#discussion_r1345447151
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **It was visual bug which didn't influence any user flow, so I don't think the regression test is needed here**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by MitchExpensify** [comment] 2023-10-05 20:50
> Hi @MitchExpensify, the following issue reporting bonus should had been 50$ but I have accepted the 250$ offer without cross checking 😅. Let me know what we can do to solve this issue.

No worries! I'll just reduce the payment accordingly when the 9th comes around 👍

**Comment by MitchExpensify** [comment] 2023-10-09 23:47
Paid @dhanashree-sawant 

@DylanDylann I requested a refund because I paid too much via the bonus, sorry about that!

Once the refund is issued I'll close this out and end your contract @DylanDylann 

Thanks, everyone!

**Comment by DylanDylann** [comment] 2023-10-16 14:09
@MitchExpensify I've refunded, thank you!

**Comment by MitchExpensify** [comment] 2023-10-18 15:28
Thanks @DylanDylann !

**Closed by MitchExpensify** 2023-10-18 15:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
