### ISSUE TITLE
[$1000] The search icon in issuing country field is not centered

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14226] opened 2023-01-11 21:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any workspace
 2. Go to connect bank account
 3. Select connect manually option
 4. Fill routing and account number fields
 5. Complete company information section
 6. (In personal information section) Notice that in the issuing country field the search icon is not aligned in the center position

## Expected Result:
The search icon should be centered

## Actual Result:
The search icon in the issuing field is not aligned properly

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y
**Reproducible in production?:** Can't check
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1323" alt="Screenshot 2023-01-10 at 10 41 46 PM (1)" src="https://user-images.githubusercontent.com/43996225/211924999-029a16e6-db58-4eb6-86fb-d5c1595c167b.png">
<img width="1066" alt="Screenshot 2023-01-10 at 11 08 34 PM (1)" src="https://user-images.githubusercontent.com/43996225/211925002-e48bae85-6665-4642-9e01-88f81b817419.png">
<img width="960" alt="Screenshot (144)" src="https://user-images.githubusercontent.com/43996225/211925039-9a979c15-159f-4c6c-83ed-bbfa3544eee1.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673371540146299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01703082a52944e4fe</li>
        <li>Upwork Job ID: 1654542840972722176</li>
        <li>Last Price Increase: 2023-05-05</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-01-12 00:03
I can reproduce this but when we https://github.com/Expensify/Expensify/issues/233363 we will take another look at this flow. So putting this bug on hold to be tested again when this is done.

**Comment by JmillsExpensify** [comment] 2023-01-12 04:51
Haha, are you snagging issues from me???

**Comment by anmurali** [comment] 2023-02-14 06:05
Haha, are you complaining @JmillsExpensify!

Not overdue but on hold for OnFido

**Comment by JmillsExpensify** [comment] 2023-02-15 20:12
Haha no way. I have plenty of issues, all good!

**Comment by anmurali** [comment] 2023-03-28 19:52
Since we are punting on Onfido for the moment, should I be taking these off hold? @JmillsExpensify thoughts?

**Comment by ashimsharma10** [comment] 2023-04-23 01:31
bump @anmurali . Its been on hold for long.  other onfindo SDK bugs are getting resolved. I guess we look at this one too.

**Comment by anmurali** [comment] 2023-05-05 17:44
Yep, makes sense!

**Comment by Pujan92** [comment] 2023-05-05 17:53
I think now we are skipping this issuing country screen for onfido flow here.

https://github.com/Expensify/App/blob/2ca1465b8f8ac73c4238534939decb5133edd792/src/components/Onfido/BaseOnfidoWeb.js#L67-L68

**Comment by Vishrut19** [comment] 2023-05-05 20:09
Applied on Upwork. Please give me a chance.

**Comment by Vishrut19** [comment] 2023-05-05 20:27
I am extremely sorry! I didn't want to spam or do something of that sort

**Comment by christoph-pflueger** [comment] 2023-05-05 21:34
I just attempted to reproduce based on your Upwork project. It appears that this issue is no longer valid as the search input field does no longer exist. Please advice, if I'm mistaken.

**Comment by luacmartins** [comment] 2023-05-06 17:27
I couldn't get the `Issuing country` field to show up either.

**Comment by sinisam92** [comment] 2023-05-08 08:35
@christoph-pflueger @luacmartins You can not find it because as @Pujan92 wrote that part of adding bank account manually is hidden/disabled and default country is USA. If you go to `BaseOnfidoWeb.js` and change `hideCountrySelection` to `false` you will be able to see that input field. 
> I think now we are skipping this issuing country screen for onfido flow here.
> 
> https://github.com/Expensify/App/blob/2ca1465b8f8ac73c4238534939decb5133edd792/src/components/Onfido/BaseOnfidoWeb.js#L67-L68
> 
> cc @nkuoch [278c1fe](https://github.com/Expensify/App/commit/278c1feb03e137cd61817f249b809619a03c88a5)

**But it seems that that icon alignment has been fixed.**
 
![Screenshot 2023-05-08 102728](https://user-images.githubusercontent.com/42521448/236776423-5d6d7b84-829a-49d9-983a-2fcbc19e789a.png)

**Comment by luacmartins** [comment] 2023-05-08 08:46
Cool, this is no longer an issue then. Closing!

**Closed by luacmartins** 2023-05-08 08:46 UTC
Labels: External, Daily, Help Wanted, Bug
