### ISSUE TITLE
[$500] IOU - The last member is focused when I remove members

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30851] opened 2023-11-03 14:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/r/8468866637847294
2. Log in
3. Click on the "2FAB" button
4. Click on the "Start chat" button
5. Add 4 different members to the group
6. Click on the "Create chat" button
7. Click on the "+" button in the Composer
8. Click on the "Split bill" button
9. Type any amount
10. Click on the "Next" button
11. De-select members

## Expected Result:
The first member should be focused.

## Actual Result:
The last member is focused when I remove members.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/6dea1e19-748f-4bca-ba24-c66fee444b23

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3bc058e2dff750b</li>
        <li>Upwork Job ID: 1720450358180958208</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-11-03 14:40
The issue was found during the execution of TR on step 10 https://expensify.testrail.io/index.php?/tests/view/3936772&group_by=cases:section_id&group_id=229063&group_order=asc

**Comment by DylanDylann** [comment] 2023-11-03 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOU - The last member is focused when I remove members

### What is the root cause of that problem?
We always set newFocusedIndex = props.selectedOptions.length
### What changes do you think we should make in order to solve the problem?
We should add condition to check like this
```
        const newFocusedIndex = prevProps.selectedOptions.length < this.props.selectedOptions.length ?  this.props.selectedOptions.length : 0;
```

### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2023-11-03 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last member is focused when removing members in multiselect


### What is the root cause of that problem?
we set the newFocusedIndex to the last selected item: 
https://github.com/Expensify/App/blob/bc9cb8f8ca149c1f90dd09de9f19ae97bcaf07f0/src/components/OptionsSelector/BaseOptionsSelector.js#L116


### What changes do you think we should make in order to solve the problem?

in case of unselect we need to check  if the new sections list lenght is smaller than the pre selection,

if this is the case then we can use the `initialFocusedIndex` prop as the list in the splitWith is a special case where the first selected item is at index `1` not `0`

additionally we need to adjust the default value of the `initialFocusedIndex` to `0` so that it is fixed with all other components that use optionsSelector


```js
        const newFocusedIndex = prevProps.selectedOptions.length < this.props.selectedOptions.length ? this.props.selectedOptions.length : this.props.initialFocusedIndex;
        const isNewFocusedIndex = newFocusedIndex !== this.state.focusedIndex;

        // eslint-disable-next-line react/no-did-update-set-state
        this.setState(
            {
                allOptions: newOptions,
                focusedIndex: newFocusedIndex,
```

adjust this default value to `0`: 
https://github.com/Expensify/App/blob/ebfc96a76f3d6e45c2c1ab954300547cb59f3715/src/components/OptionsSelector/optionsSelectorPropTypes.js#L177


and finally in the [splitwith](https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/MoneyRequestConfirmationList.js#L554-L573) selector add 

```js
            initialFocusedIndex={1}
```

this way in the case of unselect it will focus always on the initially focus index and in the case of select it will focus on the first unselected item.

**Comment by DylanDylann** [comment] 2023-11-03 17:29
@bernhardoj Could you help to link the discussion about it?

**Comment by s77rt** [comment] 2023-11-03 21:34
@DylanDylann Thanks for the proposal. Your RCA makes sense however the solution would break other cases where it's intended to focus the first unselected option e.g. when creating a new group from FAB.



https://github.com/Expensify/App/assets/16493223/93705f8b-10b5-41af-8f17-cd4e492c1ed9

**Comment by s77rt** [comment] 2023-11-03 21:35
@abzokhattab Thanks for the proposal but it's seems to be a dupe.

**Comment by anzokhattab** [comment] 2023-11-03 21:40
@s77rt not duplicate … i have used the initiallyfocusedindex to set the focus .. where in the first proposal the index 1 is always focused … there is a problem with this approach it only works with the “split with” … it doesn’t work with search/add to group  selection

**Comment by abzokhattab** [comment] 2023-11-03 21:41
@s77rt not duplicate … i have used the initiallyfocusedindex to set the focus .. where in the first proposal the index 1 is always focused … there is a problem with this approach it only works with the “split with” … it doesn’t work with search/add to group selection

**Comment by DylanDylann** [comment] 2023-11-04 03:22
@s77rt 
[Updated proposal](https://github.com/Expensify/App/issues/30851#issuecomment-1792598024)

**Comment by s77rt** [comment] 2023-11-04 10:32
@abzokhattab The behavior on the group chat creation should not change. i.e. the focus should be on the first unselected option (and not the first option).

**Comment by s77rt** [comment] 2023-11-04 10:34
@DylanDylann Same not as above ^

**Comment by DylanDylann** [comment] 2023-11-04 10:43
@s77rt Oh got it. [Updated proposal](https://github.com/Expensify/App/issues/30851#issuecomment-1792598024)

**Comment by s77rt** [comment] 2023-11-05 09:10
@DylanDylann Thanks for the update. Introducing a new prop would probably open many ways to fix this bug but the fix would be done per instance basis. Can't we instead detect the change in the component itself e.g. use the number of sections. Or maybe have the focus always set to the first option of the second section.

**Comment by DylanDylann** [comment] 2023-11-05 09:35
@s77rt Could you help to confirm the expected first?
1. In the split bill participant
- Unselect the member will move focus to the first selected option (except disable option)
- Select the member will move focus to the first unselected option
2. In the Other Page (Like creating group page,...)
- Unselect the member will move focus to the first unselected option 
- Select the member will move focus to the first unselected option

**Comment by s77rt** [comment] 2023-11-05 11:31
@DylanDylann I'm not totally sure here. I think we should first recheck whether this is a bug

**Comment by s77rt** [comment] 2023-11-05 11:31
Slack discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1699183749228599

**Comment by s77rt** [comment] 2023-11-05 17:00
Based on the slack discussion, this is the expected behavior. Let's just update the [TR](https://expensify.testrail.io/index.php?/cases/view/1971036):

10. Verify that when deselecting a member the focus is moved to the first unselected option in the list

cc @miljakljajic

**Comment by s77rt** [comment] 2023-11-07 22:56
Not overdue. @miljakljajic ^

**Comment by s77rt** [comment] 2023-11-13 09:01
Not overdue. @miljakljajic https://github.com/Expensify/App/issues/30851#issuecomment-1793791157

**Comment by s77rt** [comment] 2023-11-18 13:31
Not overdue. @miljakljajic https://github.com/Expensify/App/issues/30851#issuecomment-1793791157

**Comment by s77rt** [comment] 2023-11-20 17:39
@miljakljajic ^

**Comment by s77rt** [comment] 2023-11-24 17:49
Not looking for proposals. Just need to update TR. @miljakljajic https://github.com/Expensify/App/issues/30851#issuecomment-1793791157

**Comment by s77rt** [comment] 2023-12-01 15:22
@miljakljajic https://github.com/Expensify/App/issues/30851#issuecomment-1793791157

**Closed** 2023-12-04 10:53 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
