### ISSUE TITLE
[$250] [UX Reliability] Chat loading even if it was opened before

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#50484] opened 2024-10-08 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** 
**Slack conversation:** Discussed in here https://expensify.slack.com/archives/C05LX9D6E07/p1728414645672739?thread_ts=1727304948.791309&cid=C05LX9D6E07

## Action Performed:
Break down in numbered steps

On iOS app
1. Open the app
2. Open some chat report
3. Verify the messages loaded correctly
4. Force quit the app
5. Open the App again
6. Open the same chat

## Expected Result:
Describe what you think should've happened

The report action should be cached locally in Onyx already so even if we are making another OpenReport call, we should not be showing a skeleton

## Actual Result:
Describe what actually happened

A skeleton is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6e114e73-f7e2-4f8c-8806-d621f6e80ff1

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843774456282966290</li>
        <li>Upwork Job ID: 1843774456282966290</li>
        <li>Last Price Increase: 2024-10-08</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104337904</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by mallenexpensify** [comment] 2024-10-08 22:18
@mountiny @puneetlath , should the `External` and `Help Wanted` labels be removed since Puneet's assigned? Based on [this SO](https://stackoverflowteams.com/c/expensify/questions/19512) it sounds like it.    Let me know if I can help, it takes ~30 seconds for the app to load on iOS for me

**Comment by mountiny** [comment] 2024-10-08 22:24
> Give support to the agency engineer who is working on the #newdot-quality bug. Giving support looks like: explaining how the code should work, retrieving data only available on the back-end, helping them with testing, reviewing their changes and keeping the urgency up.

I think it can be external; it's never been a problem to get contributors to fix it. But for what it's worth, I have asked here for expert contributor [volunteers](https://expensify.slack.com/archives/C05LX9D6E07/p1728425143883699), so that sounds like it's in line with what the SO says, too.

> Let me know if I can help, it takes ~30 seconds for the app to load on iOS for me

I am not sure if this is exactly the same bug @mallenexpensify Lets talk in slack

**Comment by mallenexpensify** [comment] 2024-10-09 00:31
> I am not sure if this is exactly the same bug

I agree, I think my bug is different (similar problems with slow load)

**Comment by kacper-mikolajczak** [comment] 2024-10-09 06:26
Hi @mountiny I would like to investigate the issue!

**Comment by mallenexpensify** [comment] 2024-10-11 20:10
Posted Android logs here https://expensify.slack.com/archives/C05LX9D6E07/p1728677097096519?thread_ts=1728425143.883699&cid=C05LX9D6E07 

@mountiny for the ~30 second load time on iOS, what do you think the next best step is there? I can post in #expensify-bugs or another room with deets and logs

**Comment by mountiny** [comment] 2024-10-14 04:34
@mallenexpensify In the long load case; I would maybe post in fast-API to see if there are some active efforts now that should speed up the OpenApp. I feel like it's quite slow for you, even compared with Jason and others, which I am not sure why is the case. Do you use the focus mode? Well I would bring the discussion there as it was 17s api time

**Comment by kacper-mikolajczak** [comment] 2024-10-14 08:02
@mountiny how does long load case correlates to current issue?

Is redundant loading of a chat happens only when long load issue exists?

**Comment by mountiny** [comment] 2024-10-14 14:10
It does not correlate, its a different issue, it will be moved somewhere else

**Comment by mallenexpensify** [comment] 2024-10-14 23:44
I'll stop _buggin_ y'all about my unrelated slowness, [posted in #stability](https://expensify.slack.com/archives/C05CBC62HGW/p1728949362931109)

**Comment by puneetlath** [comment] 2024-10-18 20:08
@mallenexpensify I believe @kacper-mikolajczak is no longer working on our project, so we'll need to get someone else.

**Comment by mallenexpensify** [comment] 2024-10-19 00:47
Posted in the callstack room https://expensify.slack.com/archives/C03UK30EA1Z/p1729298823156999

**Comment by muttmuure** [comment] 2024-10-21 13:33
Dupe of https://github.com/Expensify/App/issues/49964 

@kirillzyusko has pushed a fix that we are testing. We can reopen if you think this issue is different or unfixed by Kiryl's PR

**Comment by mallenexpensify** [comment] 2024-10-24 23:00
Please take this over @rinej @muttmuure said [they're still seeing this issue](https://expensify.slack.com/archives/C03UK30EA1Z/p1729760603200309?thread_ts=1729298823.156999&cid=C03UK30EA1Z)

**Comment by rinej** [comment] 2024-10-28 14:34
@muttmuure do we have some more details on when this issue occurs? 
Does this happen with only one particular report, or with any of them?

I tried reproducing it on iOS, and it seems to work fine. I don't have access to the thread above, so I can't check the details.

**Comment by muttmuure** [comment] 2024-10-31 11:47
@rinej the steps to reproduce are to: 

1. Open a chat, which should store the chat history in your cache
2. Kill the app and from another account, send a message to the chat from step 1
3. [Optional] wait some time - it's not clear if there is another command flushing the cache
4. Reopen the app and the chat from step 1 

See that the most recent message is displayed and the rest of the chat history shows a skeleton loader

**Comment by muttmuure** [comment] 2024-11-05 10:26
Did you find anything @rinej ?

**Comment by rinej** [comment] 2024-11-05 10:46
Not yet, I haven't been able to reproduce it. I sent messages in both directions—from iOS to web and from web to iOS—but didn't encounter the issue. I will also test on Android.

It might be that the cache is cleared after a while when the mobile device runs out of memory. So, when we open it again, we only see the messages that were loaded when generating the report list.

**Comment by rinej** [comment] 2024-11-06 17:13
@muttmuure  Isn't it similar scenario as from that thread -> https://callstack-hq.slack.com/archives/C05LX9D6E07/p1730901975051029?thread_ts=1727449830.031979&cid=C05LX9D6E07

That it happens only on Hybrid?

**Comment by mallenexpensify** [comment] 2024-11-07 00:16
@MitchExpensify I'm off the next week, can you please keep an eye on this issue til I'm back? Thx

**Comment by rinej** [comment] 2024-11-19 14:30
according to the linked conversation the PRs with the potential fixes were created. Both for OldDon and NewDot.

Conversation -> https://callstack-hq.slack.com/archives/C05LX9D6E07/p1731931310352729?thread_ts=1727449830.031979&cid=C05LX9D6E07

**Comment by rinej** [comment] 2024-11-20 14:47
From the above conversation:
NewDot -> https://github.com/Expensify/App/pull/52694
OldDot -> https://github.com/Expensify/Mobile-Expensify/pull/13285

**Comment by muttmuure** [comment] 2024-11-25 17:53
Yes looks like it. Let's close

**Closed by muttmuure** 2024-11-25 17:53 UTC
Labels: External, Daily, Bug, AutoAssignerNewDotQuality
