### ISSUE TITLE
[$1000] User get error message about non-USD currency when clicking Pay with Expensify

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21461] opened 2023-06-23 21:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Account A:
1. Login to staging.new.expensify.com with account as user A
2. Go to Payments and connect bank account
3. Create workspace and select USD as default currency in General settings

Account B:
4. Login to staging.new.expensify.com with account as user B
5. User B has connected Bank account in Payments
6. Send request money to the user A

Account A:
7. Go to the money request
8. Tap to button 'Pay with Expensify'
## Expected Result:
User able to proceed with payment as bank account already added

## Actual Result:
User A goes to the page 'Connect bank account' with message 'Oops! It appears that your workspace currency is set to a different currency that USD. ... '
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/79142f6b-1b7d-4253-a3ae-f1c7815e6966

**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687475426113199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e43f59a41542129c</li>
        <li>Upwork Job ID: 1682482647909076992</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-06-26 21:38
Checking slack on this one

https://expensify.slack.com/archives/C049HHMV9SM/p1687815482920719?thread_ts=1687475426.113199&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-06-30 22:33
can't request money right now for some other unknown reason

<img width="782" alt="image" src="https://github.com/Expensify/App/assets/22508290/b450a46b-2d0c-48a3-a536-c82d33a94df0">

Will try again Monday.

**Comment by kevinksullivan** [comment] 2023-07-06 16:23
trying to get another expensifail account to use

https://expensify.slack.com/archives/C049HHMV9SM/p1688660585140809?thread_ts=1687475426.113199&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-07-10 18:04
Removing expensifail account requirement as that is N/A

**Comment by ygshbht** [comment] 2023-07-11 14:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Users are experiencing an error message about non-USD currency when attempting to 'Pay with Expensify'

### What is the root cause of that problem?

The error seems to originate from the action performed when the **Pay with Expensify** button is pressed. When the button is pressed in the `SettlementButton` (src\components\SettlementButton.js) component,

```
onPress={(event, iouPaymentType) => {
if (iouPaymentType === CONST.IOU.PAYMENT_TYPE.EXPENSIFY || iouPaymentType === CONST.IOU.PAYMENT_TYPE.VBBA) {
triggerKYCFlow(event, iouPaymentType);
return;
}
this.props.onPress(iouPaymentType);
}}
```
the triggerKYCFlow function is called as the payment type is `EXPENSIFY`. The other function ` props.onPress` is the `IOU.payMoneyRequest` function passed by the `MoneyRequestHeader` component (src\components\MoneyRequestHeader.js)

Coming back to the `triggerKYCFlow` funciton, this is defined as a funciton named `continue `in `BaseKYCWall `component (src\components\KYCWall\BaseKYCWall.js)

```
continue(event, iouPaymentType) {
this.setState({transferBalanceButton: event.nativeEvent.target});
const isExpenseReport = ReportUtils.isExpenseReport(this.props.iouReport);

        // Check to see if user has a valid payment method on file and display the add payment popover if they don't
        if (
            (isExpenseReport && lodashGet(this.props.reimbursementAccount, 'achData.state', '') !== CONST.BANK_ACCOUNT.STATE.OPEN) ||
            (!isExpenseReport && !PaymentUtils.hasExpensifyPaymentMethod(this.props.cardList, this.props.bankAccountList))
        ) {
            Log.info('[KYC Wallet] User does not have valid payment method');
            const clickedElementLocation = getClickedTargetLocation(event.nativeEvent.target);
            const position = this.getAnchorPosition(clickedElementLocation);
            this.setPositionAddPaymentMenu(position);
            this.setState({
                shouldShowAddPaymentMenu: true,
            });
            return;
        }

        if (!isExpenseReport) {
            // Ask the user to upgrade to a gold wallet as this means they have not yet gone through our Know Your Customer (KYC) checks
            const hasGoldWallet = this.props.userWallet.tierName && this.props.userWallet.tierName === CONST.WALLET.TIER_NAME.GOLD;
            if (!hasGoldWallet) {
                    Log.info('[KYC Wallet] User does not have gold wallet');

                Navigation.navigate(this.props.enablePaymentsRoute);
                return;
            }
        }

        Log.info('[KYC Wallet] User has valid payment method and passed KYC checks or did not need them');
        this.props.onSuccessfulKYC(iouPaymentType);
    }
```

Within this function, the first condition checks if the user's action pertains to an expense report, which in this case, it doesn't because the user is dealing with an IOU. Hence, the first condition of the first 'if' block returns false. Similarly, the second condition in the first 'if' block checks whether the user has a valid bank account added. As/ When the user does indeed have a valid bank account, this condition also evaluates to false.

The function then proceeds to the second 'if' block since it is not an expense report. Here, it checks for the existence of a **gold wallet**, which is not defined in the current context. The role of a **gold wallet** is not clearly delineated in the flow. According to the prevailing flow, it appears that the user must go through a **Know Your Customer (KYC)** check within a workspace. However, no workspace is involved in this interaction between **User A** and **User B**. In this scenario, **User B** merely requests money, and **User A** attempts to fulfill that request. If a workspace were required, it would be curious to necessitate a **KYC** process, especially if a bank account has already been added.

The flow of the program then leads to the `enablePaymentsRoute `due to the absence of a **gold Wallet**. This navigation results in the display of an error message regarding non-USD currency. The discrepancy arises because the `enablePaymentsRoute` page is supposed to be a workspace page with a valid `policyID` embedded in the URL (like http://localhost:8080/bank-account/new?policyID=13FD42950499E18B). However, in the current scenario, the `props.enablePaymentsRoute `returns the value http://localhost:8080/bank-account/new because the property appears as `enablePaymentsRoute={ROUTES.BANK_ACCOUNT_NEW}`.

Due to this, the page src\pages\ReimbursementAccount\ReimbursementAccountPage.js does not receive the expected policy data. Therefore, the **hasUnsupportedCurrency** results in **true**, causing in the error:

```
const hasUnsupportedCurrency = lodashGet(this.props.policy, 'outputCurrency', '') !== CONST.CURRENCY.USD;

if (userHasPhonePrimaryEmail) {
    errorText = this.props.translate('bankAccount.hasPhoneLoginError');
} else if (throttledDate) {
    errorText = this.props.translate('bankAccount.hasBeenThrottledError');
} else if (hasUnsupportedCurrency) {
    errorText = this.props.translate('bankAccount.hasCurrencyError');
}
```


### What changes do you think we should make in order to solve the problem?

The modifications to solve this problem depend on the intended payment flow. If the goal is to redirect the user to the workspace page, the policyID needs to be included in the redirection URL. If an alternate function needs to be called, adjustments to the 'if' statements and calling the correct function will be required. The solution will largely depend on the desired flow and the appropriate changes required in the relevant functions. This approach should maintain the integrity of other code sections while resolving the current issue.

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:44
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're understanding the issue and reviewing proposals.

**Comment by kevinksullivan** [comment] 2023-07-19 12:55
Are they USD test bank accounts @parasharrajat ?

**Comment by ygshbht** [comment] 2023-07-31 19:38
> @ygshbht It is really important to reproduce this issue. Theory aside were you able to do that?

Yes obviously, though the erorr has changed now. 

Basically what happens is the `SettlementButton` `triggersKYCFlow` as you are paying with expensify. The only logic here for making payment `this.props.onPress` is hence is not triggered. 

The KYC flow redirects to Add Bank Account page for workspace but since there is no policyId/ workspaceId in the URL, it shows the page now found view.

https://github.com/Expensify/App/blob/1a1e4c5e703e930bc927c72639dfff7188e082e2/src/components/SettlementButton.js#L167-L181

https://github.com/Expensify/App/assets/65986357/786a6031-f39c-454e-a75c-35140b6bdbd2

**Comment by ygshbht** [comment] 2023-07-31 19:43
> Also, can you please convert your proposal into bullet points? It is really hard to read.

I have added some points, however, it may not be important for you to read them as they just describe what the code block above does. 

[Proposal](https://github.com/Expensify/App/issues/21461#issuecomment-1630936281)

![image](https://github.com/Expensify/App/assets/65986357/4148ae6c-f6b6-42ac-b872-33e44ed1dcee)

**Comment by ygshbht** [comment] 2023-07-31 19:51
Sure. If you are trying to reproduce, I'm using VPN and selecting USA as location to have $USD as currency (you might not have to do this if you find what code to change). And here I'm just setting `canUseWallet `to `true`. Apart form this I've set staging server `on` in Preferences which lets me add a test Plaid bank account.

https://github.com/Expensify/App/blob/1a1e4c5e703e930bc927c72639dfff7188e082e2/src/components/SettlementButton.js#L105-L108

```
 const canUseWallet = true;

// const canUseWallet =
//     !isExpenseReport && this.props.currency === CONST.CURRENCY.USD && Permissions.canUsePayWithExpensify(this.props.betas) && Permissions.canUseWallet(this.props.betas);
```

**Comment by kevinksullivan** [comment] 2023-08-04 22:28
hey @bfitzexpensify I am going OOO for the week so tapping you in the interim. Thanks!

**Comment by bfitzexpensify** [comment] 2023-08-07 12:52
Yep, gotchu. @parasharrajat were you able to test this via a VPN?

**Comment by bfitzexpensify** [comment] 2023-08-10 14:04
Bump @parasharrajat

**Comment by bfitzexpensify** [comment] 2023-08-11 12:10
Sure @parasharrajat — @marcaaron, context for assigning this to you is in https://github.com/Expensify/App/issues/21461#issuecomment-1674612709

**Comment by marcaaron** [comment] 2023-08-11 18:17
I think we can close this for now. "Pay with Expensify" is a P2P feature that is behind a beta so this isn't something that customers will run into any time soon.

**Closed by marcaaron** 2023-08-11 18:17 UTC
Labels: Engineering, Daily, Internal, Bug
