### ISSUE TITLE
[HOLD for payment 2023-12-08] [$500] Improvements to private notes

### ISSUE THREAD

**Issue by techievivek** [Expensify/App#27634] opened 2023-09-18 05:19 UTC
Adding a few improvements that we can do to the private notes feature on newDot.

- Fix the navigation flow for private notes.

Coming from this convo on slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1696267952975749?thread_ts=1696266142.168929&cid=C01GTK53T8Q, we want to update the navigation flow for the private notes feature. This is how the updated navigation would look like.

![image](https://github.com/Expensify/App/assets/16232057/3ce1b7e3-e77f-4ccb-af14-b59072682942)
![image](https://github.com/Expensify/App/assets/16232057/d91fb21f-db04-4fdb-8a4d-730eaa9c53fd)

- In the [implementation](https://github.com/Expensify/App/pull/25761) PR, we used an existing style for the multi-line input text area. However, since private notes tend to be longer in content, it would be better to increase the height of the editor area to make it more user-friendly.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d84b43e3b811080f</li>
        <li>Upwork Job ID: 1703639971803459584</li>
        <li>Last Price Increase: 2023-11-08</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27643291</li>
</ul></li>
    </ul>
</details>

**Comment by techievivek** [comment] 2023-09-18 05:20
I worked on the original implementation issue so I will work on the improvements as well.

**Comment by techievivek** [comment] 2023-10-13 06:13
Sorry, I will keep this on HOLD for just a few more days due to some other higher priority works in the pipeline.

**Comment by trjExpensify** [comment] 2023-10-16 17:49
👋 Coming from the slack convo with @shawnborton the other day, here's where I believe we landed: 

![image](https://github.com/Expensify/App/assets/16232057/3ce1b7e3-e77f-4ccb-af14-b59072682942)
![image](https://github.com/Expensify/App/assets/16232057/cf8379da-5e7f-4845-8d11-da95abb3d1f4)

**Comment by shawnborton** [comment] 2023-10-16 19:41
Looks right to me.

**Comment by techievivek** [comment] 2023-10-25 05:22
Going to pass it to a contributor.

**Comment by techievivek** [comment] 2023-10-25 05:27
For anyone going to work on this let us know if you have any questions, I have updated the GH OP to list down the improvements we are aiming to implement. Thanks

**Comment by hungvu193** [comment] 2023-10-25 05:30
I can work on this one. Should I posted a proposal?

**Comment by DylanDylann** [comment] 2023-10-25 06:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
-  We need to fix the navigation flow for private notes.

### What is the root cause of that problem?
- Currently, we always navigate the user to "private notes list page" once they click on "private note"
https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/pages/ReportDetailsPage.js#L142

### What changes do you think we should make in order to solve the problem?
- Firstly, in [ReportDetailsPage](https://github.com/Expensify/App/blob/main/src/pages/ReportDetailsPage.js)  we need to add the condition to cover the below case:
1. ```report.privateNotes``` is empty, if true, navigate user to [PrivateNotesEditPage](https://github.com/Expensify/App/blob/main/src/pages/PrivateNotes/PrivateNotesEditPage.js)
2. ```report.privateNotes``` is not empty, navigate user to [PrivateNotesListPage](```report.privateNotes``` is empty)
We can do it by adding the below condition
```
   action: () => {
                    if (isEmpty(props.report.privateNotes)) {
                        Report.getReportPrivateNote(props.report.reportID);
                        Navigation.navigate(ROUTES.PRIVATE_NOTES_EDIT.getRoute(props.report.reportID, props.session.accountID));
                        return;
                    }
                    Navigation.navigate(ROUTES.PRIVATE_NOTES_LIST.getRoute(props.report.reportID));
                },
```
To
https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/pages/ReportDetailsPage.js#L142
 (The **isEmpty** is ```if (isEmpty(props.report.privateNotes))``` just a Pseudocode, we can discuss it when implementing the PR)
- Secondly, the original logic when clicking on private note item in PrivateNotesListPage is that: It will redirect user to PriateNotesViewPage, but with the new expectation, we need to navigate user to PrivateNoteEditPage. We can do this by:
Update https://github.com/Expensify/App/blob/1c85ebeb55ffe81bf0cfa64665b4dc6625b94683/src/pages/PrivateNotes/PrivateNotesListPage.js#L116
To
```
action: () => Navigation.navigate(ROUTES.PRIVATE_NOTES_EDIT.getRoute(report.reportID, accountID))
```
### What alternative solutions did you explore? (Optional)
 - NA
### Result

[Screencast from 25-10-2023 13:55:43.webm](https://github.com/Expensify/App/assets/141406735/1c5dc078-327b-43ef-81cb-92dd353654f4)

**Comment by ArekChr** [comment] 2023-10-25 08:50
@techievivek Am I understood correctly will not use anymore this screen? 

<img width="1182" alt="image" src="https://github.com/Expensify/App/assets/24796318/9dfb01f8-f625-4d02-93c5-b7f6481bc423">

**Comment by techievivek** [comment] 2023-10-25 09:13
For context, if you have access to the report the backend will always return a private note entry for you even tho if it's empty.
There are 3 pages related to private notes.
1. PrivateNotesListPage: Where we list down notes you have access to.
2. PrivateNotesViewPage: Renders the HTML-rich private notes with a push-to-page action.
3. PrivateNotesEditPage: Renders a text area that allows you to update the private note.

Here is how we will handle the different cases:

1. If there is an entry in the `privateNotes` key and the note content is empty, we will immediately take you to the edit page. After you add content and click "back," we will redirect you to the Private Notes view page.

2. If the note content is not empty, we will take you to the view page. If you click the ">" icon, it will lead you to the edit page.

3. When you have access to multiple notes, the backend will return a list of these notes. Clicking on the "private notes" page will take you to the private notes list page. Based on the content of these private notes, we will handle them differently:
  3.1. If you click on your own note, and it's empty, it will take you to the edit page.
  3.2. Clicking on your own note that's not empty will take you to the view page. If you click the ">", it will redirect you to the edit page.
  3.3. For other people's notes, you will always be directed to the view page, as you cannot edit their notes.
  
CC @trjExpensify for cross-check. 🙏

**Comment by techievivek** [comment] 2023-10-25 09:19
@ArekChr 

> Am I understood correctly will not use anymore this screen?

I will wait for @trjExpensify to confirm the above design, but if that is what we are going with, then yes, we will deprecate the list page and update the view page to render all the accessible notes.

**Comment by techievivek** [comment] 2023-10-30 12:03
@trjExpensify Can you please have a look at the above comments(from here: https://github.com/Expensify/App/issues/27634#issuecomment-1778805676) so we can move forward with the proposal review?

**Comment by trjExpensify** [comment] 2023-10-30 16:29
Hey hey! I've been OoO for a few days, catching up now. 

I don't think we need to optimise for having multiple notes accessible really, given that it's a limited feature for internal use only. Any customers using this will only ever see one note. So with that, I would suggest we just start with show the note in full and then the next note starts beneath wherever it ends with the appropriate header.

**Comment by techievivek** [comment] 2023-11-01 09:06
Okay, great!!, that makes sense and simplifies the navigation a lot. 
Do you have everything necessary to review the proposal and move forward now, @ArekChr? Let us know if you have any further questions, thanks.

**Comment by techievivek** [comment] 2023-11-06 07:05
Gentle bump @ArekChr, can you please review the above proposals.

**Comment by techievivek** [comment] 2023-11-09 10:27
Gentle bump @ArekChr 🙏

**Comment by ArekChr** [comment] 2023-11-09 11:24
@DylanDylann, when navigating to notes (empty), it should navigate to the edit page. In your proposal, there is no found page shown briefly. Could you update your proposal to fix this issue?

**Comment by ArekChr** [comment] 2023-11-09 11:28
I'm aware there are two ways to do that:
1. Prefetch private notes.
2. Show loader instead on the not found page.

The first approach might be more complex because we can't fetch notes of other workspaces/users, just current user notes and user's workspaces.

cc: @techievivek

**Comment by DylanDylann** [comment] 2023-11-09 11:28
@ArekChr Sure. My proposal is just an idea, not handle all the edge cases. But if you want, I will update it to fix "no found page shown briefly"

**Comment by ArekChr** [comment] 2023-11-09 11:34
@DylanDylann, Does your proposal handle the third edge case? 

> 3.3. For other people's notes, you will always be directed to the view page, as you cannot edit their notes.

Looks like this is missing

**Comment by DylanDylann** [comment] 2023-11-09 11:45
@ArekChr Based on this comment https://github.com/Expensify/App/issues/27634#issuecomment-1785589110, I think we just need to disable the user from clicking on other people`s notes.

**Comment by DylanDylann** [comment] 2023-11-09 11:48
@ArekChr Just updated proposal for the case 

>3.3. For other people's notes, you will always be directed to the view page, as you cannot edit their notes.

**Comment by ArekChr** [comment] 2023-11-09 12:01
@DylanDylann, overall, your [proposal](https://github.com/Expensify/App/issues/27634#issuecomment-1778634010) looks good to me. Some minor edge cases need verifying, like opening notes from the deep link when private notes are empty. Whether a user is logged in or out, they should be redirected to the edit page post-login, and encounter a loader, rather than a 'not found' page. We might find more issues to tackle during testing.

I'm all for moving ahead and addressing these points in the PR review.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by DylanDylann** [comment] 2023-11-15 05:36
How can i test with the case multiple notes? @techievivek  @ArekChr 

![image](https://github.com/Expensify/App/assets/141406735/4046380d-a733-4d6a-b45d-a6bc8254b84d)

**Comment by techievivek** [comment] 2023-11-15 07:49
@DylanDylann You won't be able to test it since this requires either an expensify email account or a team.expensify.com email account.

**Comment by techievivek** [comment] 2023-11-15 07:49
I can test that part for you.

**Comment by DylanDylann** [comment] 2023-11-15 07:51
Yeah, thanks @techievivek

**Comment by DylanDylann** [comment] 2023-11-15 11:14
@ArekChr PR https://github.com/Expensify/App/pull/31344 is ready to review

**Comment by techievivek** [comment] 2023-12-11 12:13
Adding a BZ member to help us with the payment here.

**Comment by techievivek** [comment] 2023-12-11 12:14
@michaelhaxhiu Added you to GH to help us with the payments here, thanks. 🙇

**Comment by techievivek** [comment] 2023-12-13 13:02
Not overdue, gentle bump @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-12-13 17:32
working on it

**Comment by michaelhaxhiu** [comment] 2023-12-13 17:43
Paid, closing.

**Closed by michaelhaxhiu** 2023-12-13 17:43 UTC
Labels: External, Daily, Improvement, Awaiting Payment, Bug
