### ISSUE TITLE
[$500]  IOU - Preview not shown as Paid if paid while user offline and attempted to delete it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36049] opened 2024-02-07 17:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. [User A] Request money from User B
2. [User A] Go to IOU report
3. [User A] Go offline
4. [User B] Pay the request
5. [User A] Delete the request while offline and stay in the main chat
6. [User A] Go online
7. [User A] Verify the preview updates
## Expected Result:
IOU preview in 1:1 chat should be updated and shown as paid with green checkmark.

## Actual Result:
IOU preview is shown as unpaid, does not update until you tap on it.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/25c34934-ac7d-4b4e-b8c2-522f274f2373

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131dfe6b91030d1b0</li>
        <li>Upwork Job ID: 1755277772775849984</li>
        <li>Last Price Increase: 2024-02-07</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-07 17:10
We think that this bug might be related #vip-bills
CC @davidcardoza

**Comment by MitchExpensify** [comment] 2024-02-11 20:12
Reproduced, seems also potentially wave 5 worthy as a bug in the core request flow

**Comment by rezkiy37** [comment] 2024-02-12 14:54
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-02-13 10:01
So, I've investigated the problem. Actually, looks like there is a small miscommunication between the backend and the app. For this logic to notify the app and send the latest changes, we use the **Pusher**. It works properly all the time, except one scenario. When the app goes offline, then back online, there is a period for reconnection. Once the app has connected again successfully and even received other kind of messages, this update for a money request preview is missed. Looks like the **Pusher** sent it before, but the app was offline. As I understand there is no logic to sync data one more time. Anyway, we need to ask a backend developer, to clarify this. 

https://github.com/Expensify/App/assets/57314631/eb2213d5-e880-4154-8130-40f840b456f2

**Comment by MitchExpensify** [comment] 2024-02-16 22:31
@thienlnam what is your take on @rezkiy37 's backend related observation ?

**Comment by thienlnam** [comment] 2024-02-16 22:37
That's a problem we're solving with our own onyx update events - where each separate device's updates are stored and delivered once the device is online. I imagine this scenario is one that would be fixed once we eventually migrate it over to our own onyx updates.

What API command is being called here?

**Comment by rezkiy37** [comment] 2024-02-20 10:11
> What API command is being called here?

The app calls a "RequestMoney" command to request an IOU.

**Comment by thienlnam** [comment] 2024-02-21 19:35
I looked at the video, and it seems like this will likely get handled once we eventually migrate RequestMoney to send pusher updates via Auth.

Additionally, considering how specific this bug is - I don't think we need to address it right now. It does inform the user correctly that they were unable to delete the request

cc @MitchExpensify Thoughts on closing this?

**Closed** 2024-02-23 20:50 UTC
Labels: External, Daily, Bug
