### ISSUE TITLE
[HOLD for payment 2023-08-21] [HOLD for payment 2023-07-26] [$2000] mWeb  - Thread - Chat header jumps if swipe away from thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21843] opened 2023-06-28 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App on mWeb safari
2. Open a chat
3. Long press a message in chat that doesn't have a thread
4. Tap "Reply in thread" (make sure that the keyboard is visible if you are using simulator, cmd + K)
5. Swipe thread screen to the right to close it and land in chat

## Expected Result:
The layout should be consistent

## Actual Result:
The layout glitches , Chat header jumps to middles of screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/82b6c754-cc41-4f15-b76b-7365540fc1f0

https://github.com/Expensify/App/assets/93399543/fa9082c1-08f9-4b21-99f5-d869c60e4a13

**Expensify/Expensify Issue URL:**
**Issue reported by:** @fedirjh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687902430669059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ac36e87f5779232</li>
        <li>Upwork Job ID: 1674609086791106560</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-06-29 22:37
Reassigning another bug team member, I'm going OOO until Monday, July 10, and will take it back if it's still open by my return date.

Required action from the 🐛 team: I've run out of time and haven't tested this one yet. This needs testing to confirm if it's a bug, check if it's a dupe, and then assign the applicable labels. Thank you!

**Comment by sophiepintoraetz** [comment] 2023-06-30 02:41
I'm able to replicate this!
https://github.com/Expensify/App/assets/42940078/4969dff5-8f6a-4d4b-b996-5c359f83c077

**Comment by sophiepintoraetz** [comment] 2023-07-03 03:02
@fedirjh - did @amyevans and @adamgrzybowski work on the PR that caused this (regression)?

**Comment by sophiepintoraetz** [comment] 2023-07-04 22:52
Still waiting on proposals - @adamgrzybowski, did you have an idea here?

**Comment by adamgrzybowski** [comment] 2023-07-05 09:57
I am currently working on other tasks so I haven't thought about this too much

**Comment by sophiepintoraetz** [comment] 2023-07-06 03:45
All right - I'll doubling the price to get more traction - otherwise dropping it into an external agency.

**Comment by sophiepintoraetz** [comment] 2023-07-10 10:22
Hey @alexpensify! I think you're back in office today so I'll hand this one back over to you. In short, I've been able to replicate it but haven't found a contributor, so dropped it into [software mansion](https://expensify.slack.com/archives/C04878MDF34/p1688984491575699). If that comes up with nothing, next step was to go to call stack!

**Comment by robertKozik** [comment] 2023-07-10 11:22
Hey I’m Robert from Software Mansion, an expert agency, and I will help close this issue out.

**Comment by sophiepintoraetz** [comment] 2023-07-10 12:03
Thanks @WikusKriek - I'll get @allroundexperts to review your proposal. Additionally, @robertKozik you can submit a proposal as well if you want the chance to work on this.

**Comment by adamgrzybowski** [comment] 2023-07-10 13:29
@WikusKriek Does that mean that every time when the user has opened the keyboard it would be dismissed on starting any gesture?

**Comment by alexpensify** [comment] 2023-07-10 21:16
I'm back online and see that this is our current state: 

Wait for @allroundexperts review 

--- 

Thank you @sophiepintoraetz for moving this one forward!

**Comment by alexpensify** [comment] 2023-07-14 18:39
Update: the PR is moving forward

**Comment by alexpensify** [comment] 2023-07-16 17:27
PR is under review

**Comment by aldo-expensify** [comment] 2023-07-18 17:37
Thanks @Julesssss !

**Comment by robertKozik** [comment] 2023-07-18 21:23
I've checked this issue, and how to prevent the chrome problem. I've found two solutions:
1) We can directly target the mWeb with the pan responder changes, so changes from this issue would not be applicable for desktop browsers.
2) It looks like checking the visibility status of the Keyboard before dismissing it is enough to prevent the regression introduced before.

Personally I'll go with the later, as is more straightforward. Let me know If I can go forward with the fix 😄

**Comment by aldo-expensify** [comment] 2023-07-18 21:31
> Can we not add both checks to be bullet proof?

hmm if the point 1 requires us to duplicate [ScreenWrapper/index.js](https://github.com/Expensify/App/blob/main/src/components/ScreenWrapper/index.js) into `ScreenWrapper/index.native.js`, I would prefer to avoid that if possible. Having the two files makes the project harder to maintain.

**Comment by robertKozik** [comment] 2023-07-19 18:38
@aldo-expensify @allroundexperts I've created the PR. I keep it as draft, as i want to test it one more tomorrow.

**Comment by aldo-expensify** [comment] 2023-07-19 19:18
Sounds good, thank you!

**Comment by robertKozik** [comment] 2023-07-20 15:01
https://github.com/Expensify/App/pull/23186 PR marked as ready for review

**Comment by alexpensify** [comment] 2023-07-25 21:15
@allroundexperts when you get a chance can you please complete the checklist? Thank you!

**Comment by alexpensify** [comment] 2023-07-25 21:17
Got it! Thanks for flagging to hold on the payment process.

**Comment by alexpensify** [comment] 2023-07-27 16:36
@allroundexperts - can you please clarify if this PR is related to regression or something else found in the review process?

**Comment by alexpensify** [comment] 2023-07-28 20:42
Ok, thank you for this update @allroundexperts!

**Comment by alexpensify** [comment] 2023-07-31 22:48
The PR for regression is still under review

**Comment by alexpensify** [comment] 2023-08-02 23:11
No update, the PR is still under review

**Comment by alexpensify** [comment] 2023-08-05 00:11
The regression PR is still under review

**Comment by alexpensify** [comment] 2023-08-06 16:48
No update

**Comment by alexpensify** [comment] 2023-08-08 21:52
Ok, it looks like the PR merged. We will give it a week to confirm no new issues. Let me know if there are any questions about that plan.

**Comment by alexpensify** [comment] 2023-08-14 22:14
@allroundexperts when you get a chance can you please fill out the checklist? Thanks!

**Comment by alexpensify** [comment] 2023-08-18 17:35
@aldo-expensify - is everything completed here (no more PRs or regressions) and I can prepare for the August 21 payment date? Thanks!

**Comment by aldo-expensify** [comment] 2023-08-21 17:20
> @aldo-expensify - is everything completed here (no more PRs or regressions) and I can prepare for the August 21 payment date? Thanks!

I think that is correct, I didn't find mentions of the PR causing a regression.

**Comment by aldo-expensify** [comment] 2023-08-21 17:21
@allroundexperts friendly bump on the checklist: https://github.com/Expensify/App/issues/21843#issuecomment-1677939527

**Comment by alexpensify** [comment] 2023-08-21 23:41
Thank you for these updates, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2023-08-22 20:57
Here is the payment summary: 

-  External issue reporter @fedirjh $250 
-  Contributor that fixed the issue @robertKozik payment handled via SM 
-  Contributor+ that helped on the issue and/or PR @allroundexperts $1000

Upwork Job: https://www.upwork.com/jobs/~015ac36e87f5779232

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: From [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md), each regression reduces the pay amount for C and C+ by 50%. For this GH, the base rate was $2000, so the payment amount here will be $1000 since there will be no urgency bonus.

**Comment by alexpensify** [comment] 2023-08-22 20:59
@fedirjh - please confirm you received the payment. Thanks!

**Comment by alexpensify** [comment] 2023-08-23 14:42
I've completed the payments in Upwork and closed the job. 

Closing this GH

**Closed by alexpensify** 2023-08-23 14:42 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:16
Reviewed the details for @allroundexperts. $1,000 approved for payment in NewDot based on the BZ summary above.
