### ISSUE TITLE
[$1000] Workspace - "Auth DeletePolicy returned an error" when trying to delete workspace for applausetester+0109pronin@applause.expensifail.com

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20061] opened 2023-06-02 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to Settings > Workspaces
2. click on New workspace button
3. click on + icon and choose new room option
4. enter room name and choose visibility as Restricted
5. click on create room button
6. go to room and click on header
7. click on leave room option
8. try to delete workspace

## Expected Result:
Workspace can be deleted

## Actual Result:
Workspace cannot be deleted. Error message:
""Auth DeletePolicy returned an error" on NewDot
"404 Report not found" on OldDot"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ec2b2c77-e718-4c8d-b905-2f0262f05276

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107ada3be50638e6f</li>
        <li>Upwork Job ID: 1664696003048407040</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-04 16:16
I'm OOO next week so I added another BZ team member to monitor while I'm out.

**Comment by techievivek** [comment] 2023-06-06 13:26
Unfortunately, I can't reproduce this locally. Upon further investigation, it appears that we have encountered similar issues in the past(https://github.com/Expensify/Expensify/issues/270983, https://github.com/Expensify/App/issues/16595), and we decided to close them because we could not reproduce it locally. Furthermore, this seems to happen only with random QA emails.

**Comment by kbecciv** [comment] 2023-06-23 13:47
@techievivek Posting reproduction steps:

https://github.com/Expensify/App/assets/93399543/8ff52f29-5102-4897-9046-808ee6f01e36


1. go to Settings > Workspaces
2. click on New workspace button
3. click on + icon and choose new room option
4. enter room name and choose visibility as Restricted
5. click on create room button
6. go to room and click on header
7. click on leave room option
8. try to delete workspace

**Comment by flaviadefaria** [comment] 2023-06-23 20:40
@sakluger unassigning myself now that you're back and this isn't done yet.

**Comment by techievivek** [comment] 2023-06-26 11:25
Thanks for the reproduction step above I will take a look at it shortly.

**Comment by sakluger** [comment] 2023-06-28 20:32
@techievivek I was able to reproduce using the new reproduction steps:

<img width="383" alt="image" src="https://github.com/Expensify/App/assets/5997400/0c6313ef-d922-44ed-813a-1588d7ee72b3">

**Comment by sakluger** [comment] 2023-06-28 20:33
I updated the reproduction steps in the main issue description as well.

**Comment by sakluger** [comment] 2023-06-29 23:29
Given that we have consistent reproduction steps, I'm going to remove @techievivek's assignment and add the external label.

**Comment by techievivek** [comment] 2023-06-30 03:59
@sakluger I just tested this locally, and it requires some backend changes, so I have un-assigned @s77rt and will look into it myself. Thanks.

**Comment by techievivek** [comment] 2023-06-30 04:33
It looks like when we try to archive the policy chat report here https://github.com/Expensify/Auth/blob/0a7040e4ce100236b93a8422c47c02174a048314/auth/lib/Policy.cpp#L1048 we encounter an error as the user making the request to delete the report doesn't have a [permission](https://github.com/Expensify/Auth/blob/0a7040e4ce100236b93a8422c47c02174a048314/auth/lib/Report.cpp#L411) to newly created restricted room.

**Comment by techievivek** [comment] 2023-07-03 08:25
Sending a PR today, un-assigning @thesahindia as this would require access to the backend code for testing.

**Comment by techievivek** [comment] 2023-07-03 10:09
Started a convo in the slack #eng-chat channel to discuss a solution for bug as I am a bit confused on what would a good solution look like in this case https://expensify.slack.com/archives/C03TQ48KC/p1688378653148229

**Comment by sakluger** [comment] 2023-07-10 18:45
@techievivek looks like the linked PR was merged and deployed. Are we still waiting for anything here, or can I close the issue?

**Comment by techievivek** [comment] 2023-07-11 05:05
Ohh yes, we are good to close this one now.

**Closed by techievivek** 2023-07-11 05:05 UTC
Labels: Reviewing, Daily, Internal, Bug
