### ISSUE TITLE
[$500] Money Request grouped message jumping after adding one more Money Request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37245] opened 2024-02-27 01:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @VickyStash 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708959155001449

## Action Performed:

1. Open a chat with any user
2. Create a Money Request for that user
3. Send several text messages
4. Create one more Money Request
5. The grouped message will be shown at the end of the chat for a couple of seconds and then jump back to the old position

## Expected Result: 
Grouped Money Request message should be displayed in the order of last money request was created

## Actual Result: 
Grouped Money Request message jump back to the old position in the chat, though a newer money request was created

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/cd567517-501a-4238-b1d0-881c368b9729

https://github.com/Expensify/App/assets/38435837/8753f305-8726-4b43-8615-1fbf101ca0ef

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017edbff2437b3b0b7</li>
        <li>Upwork Job ID: 1762291292036972544</li>
        <li>Last Price Increase: 2024-03-05</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-02-28 01:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Money Request grouped messages jump after adding another Money Request and not displayed in the order of last money request was created

### What is the root cause of that problem?

When money is requested, if there is an active request, it will use the existing request instead of creating a new one.
https://github.com/Expensify/App/blob/a0e444ed80c1642b78e973ec179568b2a785f66c/src/libs/actions/IOU.ts#L898-L901

We sort the report action by created property to ensure that the preview position of the money request remains unchanged.
https://github.com/Expensify/App/blob/a0e444ed80c1642b78e973ec179568b2a785f66c/src/libs/ReportActionsUtils.ts#L220-L225

### What changes do you think we should make in order to solve the problem?

This solution will require a backend fix to update the 'lastModified' property.

We can make modifications to the 'lastModified' here:
https://github.com/Expensify/App/blob/a0e444ed80c1642b78e973ec179568b2a785f66c/src/libs/ReportUtils.ts#L3305-L3307

To

```
    const message = getReportPreviewMessage(iouReport, reportPreviewAction);
    return {
        ...reportPreviewAction,
        lastModified: DateUtils.getDBTime(),
        message: [
            {

```

And modify the sorting algorithm to utilize the lastModified property value (if available) for 

Modify the following code:
https://github.com/Expensify/App/blob/a0e444ed80c1642b78e973ec179568b2a785f66c/src/libs/ReportActionsUtils.ts#L220-L225

To
```
    const getTimestamp = (reportAction: ReportAction) =>
        reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.REPORTPREVIEW && reportAction.lastModified
            ? reportAction.lastModified
            : reportAction.created;

    const sortedActions = reportActions?.filter(Boolean).sort((first, second) => {
        const firstTimestamp = getTimestamp(first);
        const secondTimestamp = getTimestamp(second);
        if (firstTimestamp !== secondTimestamp) {
            return (firstTimestamp < secondTimestamp ? -1 : 1) * invertedMultiplier;
        }

```

We can also filter by 'childType' if needed.
[Branch to test](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/37245-grouped-chat-last-update?expand=1)

### What alternative solutions did you explore? (Optional)

**Comment by wildan-m** [comment] 2024-02-28 01:38
@mkhutornyi, @miljakljajic [Proposal updated](https://github.com/Expensify/App/issues/37245#issuecomment-1968021399) with alternative solution.

**Comment by brunovjk** [comment] 2024-02-28 12:21
Is this the same https://github.com/Expensify/App/issues/30147?

**Comment by wildan-m** [comment] 2024-03-07 02:32
@mkhutornyi @yuwenmemon 

> 🎀 👀 🎀

What does that mean? Does it signify the acceptance of my proposal? If so, who will assist with the backend part?

**Comment by Tony-MK** [comment] 2024-03-08 00:21
@mkhutornyi, I think this is solved based on this https://github.com/Expensify/App/issues/36501#issuecomment-1979948679.

**Comment by wildan-m** [comment] 2024-03-08 00:40
@Tony-MK depending on which expected behavior we choose

This post expected behavior is:

> Grouped Money Request message should be displayed in the order of last money request was created

I'd suggest updating the position using the `lastModified` prop for easier navigation. For instance, if we have a pending money request followed by hundreds of subsequent chats, the user would need to scroll up until they find the grouped report preview.

The current behavior will also lead to [this new problem](https://github.com/Expensify/App/issues/37775).

**Comment by wildan-m** [comment] 2024-03-08 00:43
> Clarifying the expected behavior in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1709550340393469?thread_ts=1708959155.001449&cid=C049HHMV9SM)

@mkhutornyi, please also consider referring to https://github.com/Expensify/App/issues/37775 in the discussion as they share the same root cause.

**Comment by Tony-MK** [comment] 2024-03-08 20:56
@wildan-m, I think the correct OP for positioning the report preview was stated in https://github.com/Expensify/App/issues/36501#issuecomment-1975475047.

This issue should not be reproducible because of this video https://github.com/Expensify/App/issues/36501#issuecomment-1979913579 by kavimuru.

**Comment by miljakljajic** [comment] 2024-03-19 13:33
Closing!

**Comment by wildan-m** [comment] 2024-03-22 14:15
@miljakljajic It would be greatly beneficial if issues are concluded with a comprehensive explanation. This approach ensures that time and energy are conserved, and it provides clarity should similar challenges arise in the future.

**Comment by miljakljajic** [comment] 2024-04-02 09:50
Apologies - I've reopened the issue, I misunderstood this https://github.com/Expensify/App/issues/37245#issuecomment-1985354506 as consensus that the issue should be closed!

**Comment by wildan-m** [comment] 2024-04-05 00:53
@mkhutornyi @yuwenmemon Is there any possibility of re-evaluating the expected behavior? Or what are the design/technical constraints preventing the re-arrangement of the report preview order?

**Comment by yuwenmemon** [comment] 2024-04-05 23:37
Heads up I'm going OOO through next week so @miljakljajic we might want to ping someone else to answer the question above.

**Comment by miljakljajic** [comment] 2024-04-09 14:28
Raising the question in VIP split

**Comment by mvtglobally** [comment] 2024-04-12 05:34
Issue not reproducible during KI retests. (First week)

**Comment by miljakljajic** [comment] 2024-04-15 10:22
@m-natarajan can you try to reproduce this and see if its still an issue?

**Comment by wildan-m** [comment] 2024-04-17 09:04
Yes, it still has not met the expected outcome.

> Grouped Money Request message should be displayed in the order of last money request was created

https://github.com/Expensify/App/assets/11847279/96058b8b-7735-4e04-b34e-e4a74ed7b41b

@miljakljajic any response from the [VIP split](https://github.com/Expensify/App/issues/37245#issuecomment-2045319976)?

**Comment by miljakljajic** [comment] 2024-04-23 13:50
No response: https://expensify.slack.com/archives/C05RECHFBEW/p1712673042136469

bumping

**Comment by mvtglobally** [comment] 2024-04-29 03:12
Issue not reproducible during KI retests. (Second week)

**Comment by wildan-m** [comment] 2024-04-30 04:01
@miljakljajic still no response? Perhaps you should tag engineers who are familiar with the issue.

**Comment by miljakljajic** [comment] 2024-04-30 07:55
I think we can close this out - it hasn't been reproducible for a while and it doesn't seem like its a high priority for split right now.

**Closed by miljakljajic** 2024-04-30 07:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
