### ISSUE TITLE
[HOLD for payment 2023-08-02] [$1000] Web - Infinite loop on timezone page after reload on timezone selection page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22813] opened 2023-07-13 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open timezone
5. Unselect automatic timezone selection and click on Timezone
6. Reload the page
7. Select any other timezone
8. Use browser back, observe it takes us again to timezone selection page instead of profile page (Also observe that it highlights older value instead of new value)
9. Again select any timezone
10. Again click back and observe that it will continue in infinite loop if we keep on making selection change

## Expected Result:
After timezone selection, app should take us to profile page on click of back

## Actual Result:
After timezone selection, app again takes us to timezone selection and continuing the same in infinite loop

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8bbfef71-f803-4296-ae8f-fce2cc7d4c1b

https://github.com/Expensify/App/assets/93399543/e3865217-5528-44b9-9473-9d40c2ef1878

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689174580648689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ecf8bf99ba14428</li>
        <li>Upwork Job ID: 1681660189481119744</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>hoangzinh | Contributor | 25680384</li>
<li>dhanashree-sawant | Reporter | 25680386</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-13 15:25
I have not been able to recreate this, as whatever option I select seems to stick
[2023-07-13_10-22-18 (1).gif.zip](https://github.com/Expensify/App/files/12041038/2023-07-13_10-22-18.1.gif.zip)

Are they still able to experience this @kbecciv?

**Comment by CortneyOfstad** [comment] 2023-07-17 14:43
Bump @kbecciv ^^^

**Comment by kbecciv** [comment] 2023-07-19 11:09
Hello @CortneyOfstad Checking in latest build

**Comment by kbecciv** [comment] 2023-07-19 11:13
Issue is still reproduced on v1.3.42-26

https://github.com/Expensify/App/assets/93399543/407ac299-1d12-4125-9b8d-281e13a853fa

**Comment by yh-0218** [comment] 2023-07-19 14:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Infinite loop on timezone page after reload on timezone selection page

### What is the root cause of that problem?
Because of `Navigation.navigate` after select timezone https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/libs/actions/PersonalDetails.js#L321

When refreshing on the `select timezone page`, this will be upper routes than the `Setting timezone page`.
So when clicking `Back Button` on the `select timezone page`, `Setting timezone page` is shown.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/libs/actions/PersonalDetails.js#L321
we can replace with this.
```Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);```

**Comment by Pujan92** [comment] 2023-07-19 14:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Infinite loop for back click when we access direct timezone selection page

### What is the root cause of that problem?
Currently, we are just going back here on back click.
https://github.com/Expensify/App/blob/16a83ac373c2103add1e416d2b33b2365ab1b87f/src/pages/settings/Profile/TimezoneInitialPage.js#L48

### What changes do you think we should make in order to solve the problem?
We can pass `shouldEnforceFallback` to true here within `goBack` call to land on `SETTINGS_PROFILE` page on back.
 `onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_PROFILE, true)}`

**Comment by b4s36t4** [comment] 2023-07-19 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Infinite loop on timezone page after reload on timezone selection page
### What is the root cause of that problem?

RCA for this issue is here 
https://github.com/Expensify/App/blob/6d1f1f59f00cd12b305c4d579f90eae2eb5c387e/src/libs/actions/PersonalDetails.js#L321

Basically we're doing navigation wrongly. 

When we're in `TimezoneInitial` Page and clicking on Timezone MenuItem we're navigating user to `TimezoneSelectPage` which is correct flow.

But if we observe https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/settings/Profile/TimezoneSelectPage.js#L98 and https://github.com/Expensify/App/blob/6d1f1f59f00cd12b305c4d579f90eae2eb5c387e/src/libs/actions/PersonalDetails.js#L321 here.

After selecting the timezone we're navigating to the back screen `TimezoneInitialPage` but it should be going back because it's a previous screen.

Cause of this navigation whole navigation state is getting broken.

This expected flow works well in case of no redirection, but if it's a redirection we get lost of the previous navigation state and navigating to the previous screen there is a PUSH event happens to navigation.

And https://github.com/Expensify/App/blob/4e7c9e04127d6fd20b2b81f7afa87c0f7633f8c2/src/pages/settings/Profile/TimezoneSelectPage.js#L117 because of this line we're going back to the screen which we started `TimezoneSelectPage` because `TimezoneInitialPage` is navigated instead of going back.

### What changes do you think we should make in order to solve the problem?

Replacing this line
https://github.com/Expensify/App/blob/6d1f1f59f00cd12b305c4d579f90eae2eb5c387e/src/libs/actions/PersonalDetails.js#L321
with

```jsx
    Navigation.goBack(ROUTES.SETTINGS_TIMEZONE);
```



### What alternative solutions did you explore? (Optional)
NA

# Result
[yy.webm](https://github.com/Expensify/App/assets/59088937/ab25f009-2ec6-4c0d-b0da-bf174b1215e7)

**Comment by CortneyOfstad** [comment] 2023-07-20 11:46
@allroundexperts Any thoughts on the proposals above?

**Comment by CortneyOfstad** [comment] 2023-08-01 19:38
I am heading OoO until 8/14 and since this needs payment — reassigning BZ to get that handled. 

@dhanashree-sawant and @hoangzinh have both been offered contracts in Upwork, so that is set there. 

Assignment took place on July 20 and PR was accepted on July 23rd so should qualify for the 50% bonus for @hoangzinh.

**Comment by sonialiap** [comment] 2023-08-08 12:17
@dhanashree-sawant report $250 - paid ✔️ 
@hoangzinh fix + bonus $1500 - paid ✔️ 
@allroundexperts review + bonus $1500 - if you haven't already, please request via NewDot

**Closed** 2023-08-08 12:23 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-15 16:18
Reviewed the details for @allroundexperts. Approved for payment in NewDot based on the BZ payment summary above.
