### ISSUE TITLE
[hold for payment 2024-03-06] [$500] Distance - Distance request preview in the main chat is grayed out offline when created online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34910] opened 2024-01-22 19:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace chat
2. Go to workspace chat
3. Create two distance requests
4. Click into one of the distance requests so you can see the request details. 
5. Navigate back to the workspace chat. 
6. Go offline.
7. Open expense report

## Expected Result:
The distance requests will not appear grayed out in offline mode since they are created online

## Actual Result:
The distance requests appear grayed out in offlne mode when they are created online. However, the requests are not grayed out in the expense report. This indicates that it is not network connection issue as the expense preview will appear grayed out in both the main chat and expense report if it is network issue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/25f6de32-f4df-40af-8f5e-7d326ec64f81

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010290c226a17cdffb</li>
        <li>Upwork Job ID: 1749510686242873344</li>
        <li>Last Price Increase: 2024-02-05</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-22 19:14
We think that this bug might be related to #wave. 
CC @DylanDylann

**Comment by paultsimura** [comment] 2024-01-22 19:18
Wrong tag @lanitochka17 🙂

**Comment by Tony-MK** [comment] 2024-01-22 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance - Distance request preview in the main chat is grayed out offline when created online

### What is the root cause of that problem?

We not clearing the `pendingFields` on success.

### What changes do you think we should make in order to solve the problem?


Clear the `pendingFields` over here.

https://github.com/Expensify/App/blob/b68abb4778dbade44278b28b4b36e29c8a5ad826/src/libs/actions/IOU.js#L1017

**Comment by joekaufmanexpensify** [comment] 2024-01-23 16:15
I can't reproduce this on my end following the above steps. Is this consistently reproducible for others?

https://github.com/Expensify/App/assets/54866469/64f9981b-0106-47d1-b4e4-05824701be78

**Comment by joekaufmanexpensify** [comment] 2024-01-23 22:08
I just tried again, and still can't reproduce this. Closing as this doesn't seem to be consistently reproducible.

**Comment by joekaufmanexpensify** [comment] 2024-01-26 20:25
Thanks for flagging. I am taking another look.

**Comment by joekaufmanexpensify** [comment] 2024-01-26 20:44
I tried to reproduce again, and I can now. The key is after creating the two distance requests, you need to click into the request details for one of them, navigate back to the workspace chat, and then go offline to reproduce this.

If you don't click into the request details for one of the requests, there is no issue when going offline (as shown by my reproduction attempt [here](https://github.com/Expensify/App/issues/34910#issuecomment-1906408118).)

I added this to the reproduction steps in OP, as it was not clear before.

**Comment by joekaufmanexpensify** [comment] 2024-01-26 20:44
@fedirjh all yours to review proposals

**Comment by joekaufmanexpensify** [comment] 2024-01-29 14:36
Pending review from @fedirjh

**Comment by joekaufmanexpensify** [comment] 2024-01-30 14:28
@fedirjh could you please take a look at the proposals here when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2024-02-01 21:03
TY!

**Comment by joekaufmanexpensify** [comment] 2024-02-05 14:33
Not overdue. Pending further input from @tienifr

**Comment by joekaufmanexpensify** [comment] 2024-02-06 14:42
Still discussing proposals

**Comment by joekaufmanexpensify** [comment] 2024-02-07 14:12
Pending proposal approval

**Comment by joekaufmanexpensify** [comment] 2024-02-09 16:05
@iwiznia mind signing off on the proposal here when you have a sec?

**Comment by mvtglobally** [comment] 2024-02-13 04:56
Issue not reproducible during KI retests. (First week)

**Comment by joekaufmanexpensify** [comment] 2024-02-13 15:11
@iwiznia could you sign off on [this proposal](https://github.com/Expensify/App/issues/34910#issuecomment-1930066527) when you have a sec?

**Comment by joekaufmanexpensify** [comment] 2024-02-14 13:55
Still pending engineering sign off

**Comment by joekaufmanexpensify** [comment] 2024-02-15 14:13
Bumped 1:1

**Comment by iwiznia** [comment] 2024-02-15 14:57
So sorry for the radio silence, I had a bad filter in my emails and this one got caught in it, so I was not seeing any of the messages or pings 😬 

Proposal looks good to me.

**Comment by joekaufmanexpensify** [comment] 2024-02-16 14:14
@tienifr is there an ETA for the PR here?

**Comment by joekaufmanexpensify** [comment] 2024-03-04 15:29
done!

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:22
Payment due today. We need to make the following payments: 

- @tienifr $500 for PR. Paid via Upwork. 
- @fedirjh $500 for C+. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:23
@fedirjh $500 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:24
@tienifr $500 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:24
All set!

**Closed by joekaufmanexpensify** 2024-03-06 22:24 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
