### ISSUE TITLE
[$1000] Web - Group Chat - Email address not displayed when hover over the user who has long Display name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23082] opened 2023-07-18 12:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a group with the user with very long Display name & other users
3. Go to the group chat
4. Go to details
5. Hover over the user who has long Display name

## Expected Result:
When hover over the user who has long name also email address should be showing

## Actual Result:
Email address not displayed when hover over the user who has very long Display name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome
- [ ] MacOS / Desktop

**Version Number:** 1.3.42.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e645e169-1eae-41fe-a5c4-679ab37d2f51

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013107871e59432037</li>
        <li>Upwork Job ID: 1681956359393382401</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by Free-devloper** [comment] 2023-07-20 12:51
# Proposal
Name field not being passed from BE until the user with lo0ng name send a message

**Comment by Free-devloper** [comment] 2023-07-20 12:52
k

**Comment by Free-devloper** [comment] 2023-07-20 12:54
Contributor details
Your Expensify account email: rehansohail37@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/rehanghafoor

**Comment by Talha345** [comment] 2023-07-20 13:02
This is a BE issue since the login is not passed from the backend for a user whom the current user has not chatted before.

Try these steps:

1.Create a new user with a very long name.
2.Go to some other user and create a group with the long name user and some other users using their emails.
3.We will get the problem as mentioned in this issue.
4.Go to new chat and create a new chat with the long name user using his email.
5.Chat opens and still the same error.

If the current user is creating a group or a simple chat with a user using his email, the email should be shown because the current user already knows his email.

https://github.com/Expensify/App/assets/36226639/7956f425-1f1b-4af2-b78d-d90312c7b01c

**Comment by ArekChr** [comment] 2023-07-20 13:16
> @ArekChr mind reviewing [this](https://github.com/Expensify/App/issues/23082#issuecomment-1643714241) proposal today? 🙇‍♂️ 

Hey @dylanexpensify, I'm not able today, tomorrow I'm OOO, I will be back on Monday

**Comment by dylanexpensify** [comment] 2023-07-24 08:25
@ArekChr sounds good! Looking forward to the recap today!

**Comment by ArekChr** [comment] 2023-07-24 09:34
@dylanexpensify When trying to reproduce this error, I see no issue on staging. All users with long display names have displayed email as well.

https://github.com/Expensify/App/assets/24796318/24f7fec2-a0eb-4d65-b090-f9babe2e11e3

**Comment by ArekChr** [comment] 2023-07-24 09:57
> @ArekChr I'm still able to reproduce in staging. Pre-condition: the user that you hovered hasn't sent any message before and isn't a member of any workspace that you are a member.
> 
>  Screencast.from.24-07-2023.16.53.36.webm

@dukenv0307 Could you test the profiles with long display names?

**Comment by ArekChr** [comment] 2023-07-24 10:14
I have created some fresh accounts with no messages sent, still can't reproduce that error. 

Are there any specific reproduction steps different from the issue description? 

https://github.com/Expensify/App/assets/24796318/71809270-9b2a-457a-84a3-383e3ff29e8c

**Comment by ArekChr** [comment] 2023-07-24 10:51
I see now for the same organization, address email is always displayed. Tested with another email and the bug is reproducible

**Comment by ArekChr** [comment] 2023-07-24 10:53
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Web - Group Chat - Email address not displayed when hover over the user who doesn't chat with the current user before.
> 
> ### What is the root cause of that problem?
> It's expected not to send login from backend as this is just new chat and user hasn't sent any message yet. That makes email is hidden when hovering the avatar of this user
> 
> https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/components/UserDetailsTooltip/index.web.js#L38
> 
> ### What changes do you think we should make in order to solve the problem?
> We can set `subtitle` as `Hidden` if `login` field isn't already in personal detail of this user. That is similar subtitle when we click on avatar to see participants of the group chat
> 
> ```
> const subtitle = (userLogin || '').trim() && !_.isEqual(LocalePhoneNumber.formatPhoneNumber(userLogin || ''), userDisplayName) ? Str.removeSMSDomain(userLogin) : 'Hidden';
> ```
> 
> https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/components/UserDetailsTooltip/index.web.js#L38
> 
> ![image](https://user-images.githubusercontent.com/129500732/254862781-b4479293-a82a-4f93-80f5-98f112d1a3ac.png)
> 
> ### What alternative solutions did you explore? (Optional)
> NA
> 
> ### Result
> ![image](https://user-images.githubusercontent.com/129500732/254863043-453e29a3-6d12-4b6c-8eb1-6c9fcd641b93.png)

@dukenv0307 Different label is needed based on localization

**Comment by ArekChr** [comment] 2023-07-24 11:21
> > Different label is needed based on localization
> 
> @ArekChr Sorry, I don't understand

I mean this sentence:

> We can set subtitle as Hidden if login field isn't already in personal detail of this user. That is similar subtitle when we click > on avatar to see participants of the group chat

The hidden label can not be set because when the app language is Espanol needs to be different. Localize is needed

**Comment by ArekChr** [comment] 2023-07-24 12:19
> @ArekChr When we change the language and open participant page, subtitle is still `Hidden`. So I think we shouldn't translate this label to consistent with other page.

@dukenv0307 I think this is another bug then. @dylanexpensify could you confirm?

**Comment by dylanexpensify** [comment] 2023-07-26 12:32
reviewing shortly!

**Comment by dylanexpensify** [comment] 2023-07-26 13:34
agree - that is another bug!

**Comment by ArekChr** [comment] 2023-07-27 11:57
@dukenv0307 Looks good to me 👌
:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by amyevans** [comment] 2023-07-27 14:54
I confirmed with @puneetlath but the lack of subtitle text in this case is by design, so going to close this out.

**Closed by amyevans** 2023-07-27 14:54 UTC
Labels: External, Daily, Help Wanted, Bug
