### ISSUE TITLE
[HOLD for payment 2024-02-19] [$500] IOU -Deleting submitted report shows unexpected error with amount crossed out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34538] opened 2024-01-15 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Login employee account
3. Tap on employee workspace chat
4. Tap plus icon near compose-- request money manual
5. Enter an amount and tap next
6. Enter merchant field
7. Tap request
8. Tap submit
9. Open submitted IOU to open IOU detail page
10. Tap 3 dots on top right and tap delete and confirm delete request

## Expected Result:
User must not be shown option/allowed to delete submitted report & error should not be displayed with amount crossed out

## Actual Result:
In employee WS, create manual request and submit it. User shown option/allowed to delete submitted report and deleted report shows unexpected error with amount crossed out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3771ee2b-3526-4ad8-99a9-3fc7be393673

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165e8908305facf78</li>
        <li>Upwork Job ID: 1747014776873512960</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28134406</li>
<li>bernhardoj | Contributor | 28134407</li>
</ul></li>
    </ul>
</details>

**Comment by sakluger** [comment] 2024-01-23 23:24
I'm checking on correct expected behavior in Slack: https://expensify.slack.com/archives/C02MW39LT9N/p1706052284329559

**Comment by mallenexpensify** [comment] 2024-01-24 03:33
@s77rt reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by sakluger** [comment] 2024-01-24 16:31
It's not clear from the reproduction steps, but if Instant Submit is enabled on the workspace, then a submitter should be able to delete an expense on a processing report, but there should be no errors (currently we see the error `Unexpected error deleting the money request, please try again later`).

**Comment by s77rt** [comment] 2024-01-24 19:16
@sakluger I think instant submit is only enabled on free policies. Asked for confirmation here https://expensify.slack.com/archives/C01GTK53T8Q/p1706122924561169

**Comment by s77rt** [comment] 2024-01-24 19:22
@Gonals Please check the two linked slack threads above ^ Thanks!

**Comment by s77rt** [comment] 2024-01-29 18:05
@Gonals ^

**Comment by Gonals** [comment] 2024-02-01 11:07
I agree with the proposal. I can test with paid policies if needed

**Comment by bernhardoj** [comment] 2024-02-01 11:28
Just retested and now I can delete the submitted request.

https://github.com/Expensify/App/assets/50919443/85204d32-ddb1-498b-92a8-5bc38336b63c


It's weird though seeing the submitted amount as 0. Do we still want to disable the delete button?

@Gonals @s77rt

**Comment by s77rt** [comment] 2024-02-01 22:53
@bernhardoj I'm still seeing an error. Maybe you are viewing the optimistic onyx values?


https://github.com/Expensify/App/assets/16493223/6615d790-d4db-4748-95e4-2443482ac292

**Comment by bernhardoj** [comment] 2024-02-02 04:53
@s77rt ah, I think I know why now. If I were an admin of the collect workspace, then I could delete the submitted expense report. But if I were a member/employee, then I can't.

The question is, do we want to disable the delete of submitted expenses for both admin and member?

**Comment by s77rt** [comment] 2024-02-02 18:15
In this case we should disable the button only for members. We should match the BE behaviour.

**Comment by bernhardoj** [comment] 2024-02-03 08:31
PR is ready

cc: @s77rt

**Comment by s77rt** [comment] 2024-02-13 20:18
- The PR that introduced the bug has been identified: This seems to be a bug since day one, https://github.com/Expensify/App/pull/19095
- The offending PR has been commented on: https://github.com/Expensify/App/pull/19095#discussion_r1488520185
- A discussion in #expensify-bugs has been started: Not needed. More like a onetime bug
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

Requires a paid workspace e.g. collect workspace

1. Login as an employee
2. Create a new money request
3. Submit the expense report
4. Go to the money request and Verify you cannot delete it
5. Login as an admin
6. Go to the money request and Verify you can delete it

**Comment by sakluger** [comment] 2024-02-20 18:09
Thanks @s77rt for completing the BZ checklist ahead of time!

Everyone has been paid out. 🙇

**Closed by sakluger** 2024-02-20 18:09 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
