### ISSUE TITLE
[$1000] Share code - Unable to go to the chat with a user whose email address has "+"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19039] opened 2023-05-16 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18636

## Action Performed:
1. Log into an account that has a `+` in the email, ex: `example.user+test@applause.expensifail.com`
2. Go to URL https://staging.new.expensify.com/
3. Go to Settings > Share code
4. Using another phone, scan the QR code on the page and verify that it takes you to New Dot to view the profile page of the user
5. Tap `Massage example.user+test@applause.expensifail.com`

## Expected Result:
User can jump to a conversation with another user using a QR code.

## Actual Result:
The user sees an error in the chat and is not able to send messages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aa3087c4-bea4-4347-89fb-d7fd2f045427

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team @nathan-mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684165146584739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efcc2d2440f70193</li>
        <li>Upwork Job ID: 1660658319748927488</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-16 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The `+` sign in the email address disappears when opening from a deep link provided by the QR code.

### What is the root cause of that problem?

The reason for this is because the string is not encoded before converting it into a QR code.

### What changes do you think we should make in order to solve the problem?


To solve this, we first encode the string and then convert it into a QR code.

### What alternative solutions did you explore? (Optional)
None.

**Comment by therealsujitk** [comment] 2023-05-18 22:03
@sonialiap the email address should contain a `+` in it. Also the same issue should happen for the copy to clipboard button.

**Comment by sonialiap** [comment] 2023-05-22 14:27
Whops, I didn't notice the `+` requirement, thanks for the correction, trying it now with an email address that has a +

**Comment by sonialiap** [comment] 2023-05-22 14:42
Oh yeah, when testing with an email address that has a `+`, I can reproduce the error. I will update the steps to specify this

https://github.com/Expensify/App/assets/17131195/223d848e-6b60-4f9a-b0ea-a16782ec2dc0

**Comment by francoisl** [comment] 2023-05-23 21:46
This was already fixed in https://github.com/Expensify/App/pull/19249, this was a duplicate issue we didn't realize.

**Comment by therealsujitk** [comment] 2023-05-23 22:10
Oh, I didn't realise.

**Comment by therealsujitk** [comment] 2023-05-23 22:12
This wasn't the duplicate issue, the other one was.

**Comment by francoisl** [comment] 2023-05-24 19:31
Reopening this so we can pay @Nathan-Mulugeta for reporting the issue once https://github.com/Expensify/App/pull/19249 is deployed (as discussed starting [here](https://github.com/Expensify/App/issues/19076#issuecomment-1560182780)).
(cc @michaelhaxhiu)

**Comment by mvtglobally** [comment] 2023-05-31 04:09
Issue not reproducible during KI retests. (First week)

**Comment by francoisl** [comment] 2023-06-05 14:25
Looks like payment for reporting the issue is complete (https://github.com/Expensify/App/issues/19076#issuecomment-1575139663), closing.

**Closed by francoisl** 2023-06-05 14:25 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
