### ISSUE TITLE
[$250] Markdown - Cursor position moves to start when inserting a new break in a hyperlink

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43922] opened 2024-06-18 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4641558
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open any conversation
3. Send any hyperlink using []() format
4. Get into editing mode on the hyperlink sent on step 3
5. Position the cursor to be at the end of the text content right before the last "]" and insert a line break

## Expected Result:
The cursor positions itself in the beginning of the new line

## Actual Result:
The cursor positions itself in the beginning of the first line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cc18120f-4901-4eed-ac49-6e799206d62d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e1861b7a8f9e8fd</li>
        <li>Upwork Job ID: 1803124326197693470</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ikevin127</details>

**Comment by lanitochka17** [comment] 2024-06-18 15:32
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-18 15:32
We think that this bug might be related to #vip-vsp

**Comment by huult** [comment] 2024-06-18 21:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor position moves to start when inserting a new break in a hyperlink
### What is the root cause of that problem?
When the user inputs a newline character at the end of a Markdown string, it disappears after parsing. Therefore, when comparing conditions, this discrepancy can lead to incorrect evaluations

### What changes do you think we should make in order to solve the problem?
Trim the Markdown input prior to condition checks to mitigate whitespace discrepancies.

In parseExpensiMarkToRanges at [parser](https://github.com/Expensify/react-native-live-markdown/blob/main/parser/index.ts#L246), should add .trim() like in the code snippet below:

```diff
function parseExpensiMarkToRanges(markdown: string): Range[] {
  try {
    const html = parseMarkdownToHTML(markdown);
    const tokens = parseHTMLToTokens(html);
    const tree = parseTokensToTree(tokens);
    const [text, ranges] = parseTreeToTextAndRanges(tree);

-   if (text !== markdown) {
+   if (text !== markdown.trim()) { 
```

<details>
<summary>POC</summary>

https://github.com/Expensify/App/assets/20178761/d86a0431-49e0-4e9d-88f4-3093f7dd1bbd


</details>

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-06-19 03:12
@huult Thanks for your proposal. A few clarifications before I can reach a point where I can verify your proposal:
1. The **root cause** of your proposal is not clear enough. Can you expand on the **why** of the following statements ?
    - `When the user inputs a newline character at the end of a Markdown string, it disappears after parsing`
    - `when comparing conditions, this discrepancy can lead to incorrect evaluations`
2. I wasn't able to fix the issue applying the suggested solution. Can you detail how you implemented your solution in the Expensify app ?

**Note:** I applied the suggested changes in the react-native-live-markdown repo, compiled and used the compiled `react-native-live-markdown-parser.js` to replace in Expensify/node_modules/@expensify/react-native-live-markdown both `parser` and `lib/parser` folders -> my Expensify web app reloaded but I can still reproduce the issue.

**Comment by badeggg** [comment] 2024-06-19 09:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor move to beginning when insert trailing `\n` to a link text.

### What is the root cause of that problem?
There are two error thrown out actually.  
![image](https://github.com/Expensify/App/assets/10908996/50f6a43d-a110-4778-871f-8f45da83a001)
**The first error** is because [`g1.trim()`](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L261) (we should care [this trim](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L255) too) has trimmed link text which cause it's impossible to recover to original comment-text from parsed html with [code here](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L242-L245), which cause condition [`text !== markdown`](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L246) to false.

The first error can somehow trigger this condition [`if (nextChar !== '\n')`](https://github.com/Expensify/react-native-live-markdown/blob/aa5cbefa5e248159f81393b7a2dd8adfcc807e1c/src/web/cursorUtils.ts#L69-L70), which lead to **the second error**, which finally cause cursor moving unexpectedly.

### What changes do you think we should make in order to solve the problem?
**Fix the first error**
To fix the first error, we can either change [`g1.trim()`](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L261) to `g1`:
from
```
                    return `<a href="${Str.sanitizeURL(g2)}" data-raw-href="${g2}" data-link-variant="labeled" target="_blank" rel="noreferrer noopener">${g1.trim()}</a>`;
```
to
```
                    return `<a href="${Str.sanitizeURL(g2)}" data-raw-href="${g2}" data-link-variant="labeled" target="_blank" rel="noreferrer noopener">${g1}</a>`;
```
Similar change apply to [this line](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L255)

Or we can change this condition [`if (text !== markdown)`](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L246) to `if (text !== markdown.trim()) `. I personally do not like this solution, since it's making a relative big change.

**Fix the second error**
The second error is actually a duplicate of [this][https://github.com/Expensify/App/issues/43239#issuecomment-2174928079]. And if the first error is fixed, the second error will not be triggered in this issue case. So I do not fix the second error here.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by badeggg** [comment] 2024-06-19 10:06
@Amoralchik Hi, gently remind, your suggesting code change is trying to fix the second error mentioned in my proposal, which is a duplication of [this](https://github.com/Expensify/App/issues/43239#issuecomment-2174928079). And I personally do not recommend change `if (nextChar !== '\n') {` to `if (nextChar !== '\n' && textNodes.length > 1) {`.

**Comment by Amoralchik** [comment] 2024-06-19 10:26
@badeggg 
Thank you for noticing. I have tested my code using actions from #43239, and everything is working fine, I haven't encountered any errors in my console. 
I also see a message from the 'react-native-live-markdown' team, so let's wait for their response.

**Comment by huult** [comment] 2024-06-19 15:44
Hi @ikevin127 ,

Firstly, I would like to thank you for reviewing my proposal.

When the user wants to enter a line where the value is text, a newline character (\n) is added to the value. This value is then sent to the parseExpensiMarkToRanges function of react-native-live-markdown. Like the image below:

<img width="1017" alt="Screenshot 2024-06-19 at 22 22 49" src="https://github.com/Expensify/App/assets/20178761/b2a56881-7461-4bfe-9c15-a6377ed7bc89">


So I trimmed the markdown to remove \n from it, but that was incorrect. Accidentally, this issue was resolved because the selection did not reset to {start: 0, end: 0}

Thanks,

**Comment by ikevin127** [comment] 2024-06-20 02:02
🙏 Thanks everybody for your interest in fixing this issue!

Currently @Amoralchik's [solution](https://github.com/Expensify/App/issues/43922#issuecomment-2178274462) is the **only** one that fixes the issue. Performing the action still throws the [match related error ](https://i.epvpimg.com/7s4Vaab.png)(for obvious reasons), but the cursor position is not being reset anymore -> which fulfils our issue's **expected result**:

https://github.com/Expensify/App/assets/56457735/28037d94-055b-463c-9dec-6b3ebb61b9b8

## What's Next ?

Regarding the proposed solution:

```diff
-    if (nextChar !== '\n') {
+    if (nextChar !== '\n' && textNodes.length > 1) {
        range.setStart(textNodes[i], 0);
    } 
```

I'm afraid that the change **might** cause regressions even though all `react-native-live-markdown` tests are still passing with the change. Given this, before moving on with hiring somebody here, I'd appreciate if @BartoszGrajdek could chime in regarding the proposed solution (as they suggested [here](https://github.com/Expensify/App/issues/43239#issuecomment-2175798675)).

**Comment by badeggg** [comment] 2024-06-20 02:13
@ikevin127 Hi, have you checked my proposal?

**Comment by ikevin127** [comment] 2024-06-20 02:20
Yes, I did check all proposals and the issue was still reproducible in all of them except **Amoralchik**'s.

Keep in mind that we're not looking to get rid of the first error since:
1. In our case, it's inevitable for the error to show up because the original vs processed input is different once we add the newline `\n`.
2. The first error is not what causes cursor reset (what this issue is about).

**Comment by badeggg** [comment] 2024-06-20 02:23
Then the second error has same root cause of this issue: https://github.com/Expensify/App/issues/43239, and I do posted [my proposal](https://github.com/Expensify/App/issues/43239#issuecomment-2174928079) there, and have linked it in my proposal for this issue.

**Comment by ikevin127** [comment] 2024-06-20 02:30
Different issues, (slightly) different solutions. Additionally **mallenexpensify** notified you in the other issue to:
> hang tight for now plz while we get a better handle on managing markdown improvements more holistically.

So don't worry, I also tagged **BartoszGrajdek** in https://github.com/Expensify/App/issues/43922#issuecomment-2179680396 for this issue and I mentioned that:

> before moving on with hiring somebody here, I'd appreciate if **BartoszGrajdek** could chime in regarding the proposed solution

Whenever we get feedback, if they think that the other issue's solution would fix this one as well -> then nobody will get hired for this one, otherwise they might decide that we want to fix them separately.

**Comment by badeggg** [comment] 2024-06-20 04:22
@ikevin127 Code changes in my proposal actually can fix this issue. Fix the first error indeed lead the second error disappears for this issue. 

I kind don't agree that:
> The first error is not what causes cursor reset (what this issue is about).

To confirm code changes in my proposal can fix this issue:
1. From root folder of react-native-live-markdown
2. `yarn install`
3. `cd parser/node_modules/expensify-common/dist/`
4. Edit file "ExpensiMark.js"(get rid of the two `trim()` in rule for 'link')
5. From root folder of react-native-live-markdown
6. `cd parser`
7. `npm run build` to build new `react-native-live-markdown-parser.js` which is in current `parser` folder
8. From root folder of expensify-app
9. `cd node_modules/@expensify/react-native-live-markdown`
10. Copy the built `react-native-live-markdown-parser.js` to `parser/react-native-live-markdown-parser.js`
11. Copy the built `react-native-live-markdown-parser.js` to `lib/parser/react-native-live-markdown-parser.js`
12. From root folder of expensify-app
13. `cd node_modules/expensify-common/dist`
14. Edit file "ExpensiMark.js"(get rid of the two `trim()` in rule for 'link')
15. Start expensify-app and verify

@ikevin127 Maybe you don't replace all `react-native-live-markdown-parser.js` files?

**Comment by BartoszGrajdek** [comment] 2024-06-20 13:52
Hi! Thank you for tagging me here 🙌🏻 

So I've looked through quite a few issues in recent days. I think this one is related to:
1. https://github.com/Expensify/App/issues/43386
2. https://github.com/Expensify/App/issues/43239 (just like you've said @ikevin127)

What @badeggg solution is trying to fix is actually the 1st issue linked. I agree that this is something we should aim to resolve, but I'm not sure if it's the best way to do it. This is a matter of preference that I would rather discuss with the Expensify Team. IMO there are 3 solutions to this problem:
1. Keep trimming the text content of a link and fix the bug directly in `react-native-live-markdown` (not a preferred option)
2. Stop trimming text content in `expensify-common`
3. Ignore any links that contain line-breaks (I think this one makes the most sense)

What I'm going to do next is talk with the `react-native-live-markdown` team @ SWM to ask if there was a reason for multiline links to even be considered and confirm which of these options are valid (considering our current setup).

 Next, we'll discuss it with the Expensify team to have a clear picture of how we want it to behave. 🔜 
 
 I'll keep you guys updated 🙏🏻

**Comment by badeggg** [comment] 2024-06-20 14:24
@BartoszGrajdek Hi, about the 3rd solution:
> Ignore any links that contain line-breaks

Be cautious, links that have leading or trailing spaces are causing same error, we can not recover to original comment text after trimming from parsed html.

**Comment by ikevin127** [comment] 2024-06-20 21:01
> Code changes in my proposal actually can fix this issue.

No, it doesn't fix our issue.

> Maybe you don't replace all react-native-live-markdown-parser.js files?

Yes, I did.

##

Not sure if your solution works on any of the other issues, the only thing that I'm certain of is that it's not fixing **this issue**. 

Checkout the video below where I'm demonstrating applying your solution and the **result** proving that it doesn't change / fix our issue (cursor position reset), nor the [match related error](https://i.epvpimg.com/7s4Vaab.png) which you stated that your solution will fix even though I stated in https://github.com/Expensify/App/issues/43922#issuecomment-2179692540 that:

> The first error is not what causes cursor reset (what this issue is about).

which you said you disagree with, without actually providing any reasoning as to why 🤔 

## Getting back to your solution

1. I removed both `.trim()` from this `expensify-common/ExpensiMark.ts` block [line 255](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L255) and [line 261](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L261).

2. I added `.trim()` to the `markdown` variable from this `react-native-live-markdown/parser/index.ts` block [line 246](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L246).

**Note:** I did this from E/App `node_modules` **only** for the files in the directory which actually impact the web app, this is proven by seeing the app reload whenever saving both file changes.

<details>
<summary>Watch video</summary>

https://github.com/Expensify/App/assets/56457735/3957e168-8448-4c26-ac20-c52e980e3eb7

</details>

cc @badeggg 

## Conclusion

Regardless of your solution working or not **for this issue** (which it doesn't, as proven above), I would still have massive reservations in selecting it simply because those 2 `.trim()` were added there **for a reason**, which I wouldn't want to mess with.

The reason why I'm leaning towards **Amoralchik**'s solution is because:
1. It actually works, fixing our issue according to the issue's **expected result**.
2. The proposed change is quite **narrow in scope** and primarily affects the treatment of newlines within the text, therefore is **less likely to cause regressions** compared to removing 2 instances of `.trim()` from the ExpensiMark function which handles all types of links (**broader scope**).

Even if we decide to proceed with their solution, I still have some reservations when it comes to the change potentially causing regressions as mentioned in https://github.com/Expensify/App/issues/43922#issuecomment-2179680396, reason for which I decided to include **BartoszGrajdek** in the discussion for this issue as well since they are part of the team which created and maintain the `react-native-live-markdown` library, meaning they have more context on the piece of code we're looking at changing.

**Comment by badeggg** [comment] 2024-06-21 01:24
@ikevin127 The video you provided, from 42sec to 48sec, that's not the change I suggested. My suggested change is only delete two `trim()`([this one](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L255) and [this one](https://github.com/Expensify/expensify-common/blob/b543a8276aee21652ce35eeb7970d680b59a61da/lib/ExpensiMark.ts#L261)) of expensify-common, **no change with** [`if (text !== markdown) {`](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L246). In my original comment, I did suggest change to `if (text !== markdown) {`, but I delete that change right away(less than 5 minutes).

To change `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js` file, you need goto react-native-live-markdown source code and change expensify-common dependency and run command to build it, then copy to expensify-app. Details in my [this comment](https://github.com/Expensify/App/issues/43922#issuecomment-2179778289), step 1 to step 11.

**Comment by badeggg** [comment] 2024-06-21 01:33
About this:
> which you said you disagree with, without actually providing any reasoning as to why 🤔

I believe the error trigger path is this:
1. Since that two `trim()`, we can not recover to original comment from parsed html
2. So condition [`if (text !== markdown)`](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L246) met
3. Error `[react-native-live-markdown] Parsing error: the processed text does not match the original Markdown input...` thrown.
4. Program not process as expected to [following codes](https://github.com/Expensify/react-native-live-markdown/blob/49ddcc29b40dd864645f611521e19dee2fcb4d48/parser/index.ts#L253-L255)
5. Error 2 appears.
6. Cursor move unexpectedly

**Trigger path is linear.** You can't say the first error is not the root cause.

**Comment by badeggg** [comment] 2024-06-21 01:40
Just in case, I have to say, file `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js` rely on markdown parser from 'expensify-common'. Deleting two `trim()` needs reflect to it. That's why we need rebuild it.

**Comment by ikevin127** [comment] 2024-06-21 01:58
Hey, did you know that you can **edit your previous comment** instead of posting a new one everytime you have something else to add to the discussion ?

<img width="150" alt="Screenshot 2024-06-20 at 18 49 38" src="https://github.com/Expensify/App/assets/56457735/10a87ab2-34d2-49af-9cf1-5fd6df502bfa">


##

There's clearly a language barrier since I wasn't able to figure out from your proposal that when you say "remove the 2 `.trim()` from expensify-common" you actually mean:
- apply these changes to the package within `node_modules` of the `react-native-live-markdown` library, then rebuild `react-native-live-markdown` and pass the generated .js script to the **Expensify/App** `node_modules/@expensify/react-native-live-markdown`.

But regardless, I stand by what I said here:

> I would still have massive reservations in selecting it simply because those 2 .trim() were added there for a reason, which I wouldn't want to mess with.

Even if that solution works, I'd still pick the other one because removing 2 instances of `.trim()` from the ExpensiMark function handles all types of links, therefore having a **broader scope** -> more prone to regressions.

**Comment by badeggg** [comment] 2024-06-21 02:19
> did you know that you can edit your previous comment

I know this, I will amend my previous comment if adding one more comment is disturbing others.

> language barrier ... "remove the 2 .trim() from expensify-common" you actually mean ...

I thought you know react-native-live-markdown relying on expensify-common. My mistake.

> I would still have massive reservations in selecting it simply because those 2 .trim() were added there for a reason, which I wouldn't want to mess with.

If you say so.

Just try to clarify that code changes in my proposal can work. 🤝

**Comment by sakluger** [comment] 2024-06-21 23:17
I've temporarily removed the `Help Wanted` label while we wait for @BartoszGrajdek to come back with the results of speaking with SWM. @BartoszGrajdek - is there a Slack link where I can we that discussion, or are you discussing offline?

**Comment by ikevin127** [comment] 2024-06-21 23:37
> I know this, I will amend my previous comment if adding one more comment is disturbing others.

Wouldn't call it **disturbing** but it's good to know that most of us that are participating to this issue (7 currently) are getting notified everytime somebody posts a new comment - you posted 3 in a row and that's why I mentioned the alternative 👍 

> I thought you know react-native-live-markdown relying on expensify-common. My mistake.

You are forgiven! For your convenience, here are some of the [raw proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1) recommendations:

**For Contributors**

> **Reminder:** Please use **plain English**, be brief and **avoid jargon**. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text.

**For Reviewers**

> You are the first line of defense in making sure every proposal has a **clear and easily understood problem with a "root cause"**. Do not approve any proposals that **lack a satisfying explanation to the first two prompts**. It is CRITICALLY important that we **understand the root cause at a minimum** even if the solution doesn't directly address it. When we avoid this step, we can end up **solving the wrong problems** entirely or just writing hacks and workarounds.

I want to **highlight** that it's paramount, if you want your proposals to be considered, that you are **very** specific with both the root cause of the issue, the proposed solution and where / how should this solution be implemented because:
1. Shows that you have a decent understanding of the codebase and what the issue is about ✅ 
2. Avoids assuming things, which can lead to miscomunication and time wasted ❌ 

##

> If you say so.

Here's an example of regression your proposed solution will cause by removing only one `.trim()` from ExpensiMark:
- Issue: https://github.com/Expensify/App/issues/12511 check the issue's **actual result** and **screenshots**
- PR which fixed the issue (added the `.trim()`): https://github.com/Expensify/expensify-common/pull/471 proves that implementing your solution would basically revert this PR and reintroduce the issue
    
Again, regardless of whether your solution `can work` -> that doesn't mean much if it's going to revert already-fixed issues as our goal here is to **improve** the functionality with every PR.

##

> [!tip]
> 1. If you feel that your proposals are not being understood / misconstrued, I suggest using tools like ChatGPT in order to format your final proposals when you are ready to post them in order to make it easier to understand for everybody that's going to review.
> 2. Before proposing a solution which removes some existing code / methods which `can work` and seems to be working, I'd suggest learning to use [github blame](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#viewing-the-line-by-line-revision-history-for-a-file) which means you can **view the line-by-line revision history for a file / piece of code**.  **Note:** This is how I found the above example of regression that your solution code change would revert back to if implemented.
> 3. If still interested -> I suggest taking on issues with **less cognitive complexity** in order to gradually get a deeper understanding of the codebase and the libraries we use as part of it.

cc @badeggg

**Comment by ikevin127** [comment] 2024-06-24 18:44
Will get back on this soon!

**Comment by BartoszGrajdek** [comment] 2024-06-25 09:52
@thienlnam this is also an issue related to live markdown, could we add it to the project? 🙏🏻

**Comment by ikevin127** [comment] 2024-06-28 18:42
♻️ Reviewing the latest discussions.

**Comment by ikevin127** [comment] 2024-06-28 19:35
> ### Cursor positioning problem
> This has been fixed. If you go onto staging the cursor should be positioned correctly when creating a multiline link. That's due to https://github.com/Expensify/App/pull/44168, which is patching react-native-live-markdown. These changes will be also added to the react-native-live-markdown lib later this week.

@sakluger I can confirm that this issue is not reproducible anymore:

<details>
<summary>Video</summary>

https://github.com/Expensify/App/assets/56457735/d8a3f597-21da-440d-ba91-b0eeacd8ba36

https://github.com/Expensify/App/assets/56457735/d8a3f597-21da-440d-ba91-b0eeacd8ba36

</details>

Given that this issue's **expected result** was fulfilled (IMO), I think the other `react-native-live-markdown` related issues are out of scope here and will most likely handled by SWM as they continue working on and improving the library.

**Note:** I think this can be closed as fixed if no objections are raised.

##

> There are currently 2 issues that are related to problems with multiline hyperlinks. This one and https://github.com/Expensify/App/issues/43386 I've linked previously. Both of them are different but could conflict with one another in terms of solutions, so I'll let you decide if we want to keep both of them or maybe merge them @ikevin127 🙌🏻

As mentioned above, I think we should keep them separate as this one was already fixed while the other one is still reproducible. This being said, I'd be good to keep this one in mind when testing the fix for the other one to make sure the regression (this issue) is not reintroduced.

**Comment by sakluger** [comment] 2024-06-28 20:35
Hey @ikevin127, thanks so much for retesting and confirming that it's no longer reproducible. I agree that we can close out this issue.

Thanks everyone!

**Closed by sakluger** 2024-06-28 20:35 UTC
Labels: External, Daily, Bug
