### ISSUE TITLE
[HOLD for payment 2024-12-16] [$75] Tag - In tag details page, no spacing between Go "to and more" features

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53358] opened 2024-12-01 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.69-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Go to workspace settings
3. Tap more features - enable tags
4. Add a tag
5. Open the tag
6. Enter GL code and complete flow
7. Go to workspace settings - more features - enable rules
8. Tap tags
9. Open a tag
10. Note text under approver field
11. Note no spacing between Go "to and more" features
12. Navigate to workspace settings - category
13. Open a category
14. Note text under approver field
15. Note there is spacing between Go "to and more" features

## Expected Result:
In tag details page, there must spacing between Go "to and more" features.

## Actual Result:
In tag details page, no spacing between Go "to and more" features but spacing in category details page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/95ebf900-3b6f-485b-91b9-6d96f26d8d3b

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863808426275105630</li>
        <li>Upwork Job ID: 1863808426275105630</li>
        <li>Last Price Increase: 2024-12-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by prakashbask** [comment] 2024-12-02 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In tag details page, there must spacing between Go "to and more" features.

### What is the root cause of that problem?
There is a space missing after the Text component to render "Go to" in 
https://github.com/Expensify/App/blob/7d15aaccdafc6dca0bc60ed309a3e138b60dd2a0/src/pages/workspace/tags/TagSettingsPage.tsx#L193

### What changes do you think we should make in order to solve the problem?
Add a space {' '} after the Text component that is used to render "Go to" in 
https://github.com/Expensify/App/blob/7d15aaccdafc6dca0bc60ed309a3e138b60dd2a0/src/pages/workspace/tags/TagSettingsPage.tsx#L193

This solution is similar to the space added in src/pages/workspace/categories/CategorySettingsPage.tsx

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
None

### What alternative solutions did you explore? (Optional)

**Comment by VictoriaExpensify** [comment] 2024-12-03 04:51
Yeah we should fix this, but it seems like a super simple copy fix so I'm going to drop the bounty to $75

**Comment by suneox** [comment] 2024-12-03 09:23
Let's go with @prakashbask [proposal](https://github.com/Expensify/App/issues/53358#issuecomment-2510985928)

🎀 👀 🎀 C+ reviewed

**Comment by grgia** [comment] 2024-12-03 10:30
All yours @prakashbask, thank you @suneox

**Comment by prakashbask** [comment] 2024-12-03 11:58
Thanks @grgia . I will have the PR ready by 4-Dec

**Comment by prakashbask** [comment] 2024-12-04 08:49
PR is https://github.com/Expensify/App/pull/53525

**Comment by grgia** [comment] 2024-12-06 10:54
PR was merged

**Comment by suneox** [comment] 2024-12-15 16:17
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/49937/files#r1885753605

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: *N/A*

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again. *N/A: Due to it isn't an impactful bug*

**Comment by VictoriaExpensify** [comment] 2024-12-16 22:20
@prakashbask and @suneox I've sent you both offers in Upwork. Let me know when you have accepted them and I'll orgnaise payment

**Comment by prakashbask** [comment] 2024-12-17 03:43
> @prakashbask and @suneox I've sent you both offers in Upwork. Let me know when you have accepted them and I'll orgnaise payment

@VictoriaExpensify Thanks. I have accepted the offer in Upwork

**Comment by suneox** [comment] 2024-12-17 03:45
Thank you! I've accepted the offer

**Comment by VictoriaExpensify** [comment] 2024-12-22 22:15
Payment Summary:
C: @prakashbask paid $75 via Upwork
C+: @suneox paid $75 via Upwork

**Closed by VictoriaExpensify** 2024-12-22 22:15 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
