### ISSUE TITLE
[HOLD for payment 2023-10-27] [WAITING ON #28899][$500] [ANDROID] Chat - Closing phone menu, opens keypad with focus on compose

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26763] opened 2023-09-05 11:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Tap on pin
4. Tap unpin
5. Tap phone icon and note phone options opened
6. Tap phone icon again

## Expected Result:
When user taps pin and again unpin, no effect on keypad. Similarly , when user taps phone icon, it must open.When user taps phone icon again, it must get closed and keypad must not get opened and focus on compose must not be shown

## Actual Result:
When user taps pin and again unpin, no effect on keypad. Similarly, user taps phone icon, it gets open.When user taps phone icon again, the phone option closed and along with it, keypad got opened and focus on compose is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/97e2fa01-4a51-4ab0-b0c5-f902400d29b2

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ishpaul777 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d03561e10ecc1b6d</li>
        <li>Upwork Job ID: 1699319143390973952</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>ginsuma | Contributor | 26850988</li>
<li>ishpaul777 | Reporter | 26850990</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-05 16:47
I reported this while ago but it was not filed - https://expensify.slack.com/archives/C049HHMV9SM/p1692371426492029

**Comment by jliexpensify** [comment] 2023-09-06 01:31
Thanks @ishpaul777 - if this is a bug, then you'll get credit as the Bug Reporter.

**Comment by jliexpensify** [comment] 2023-09-06 01:37
@ishpaul777 and @lanitochka17 I cannot reproduce this on Android (v63). Can you please try reproducing and share a video?

**Comment by ishpaul777** [comment] 2023-09-06 04:19
Reproduced

production-
https://github.com/Expensify/App/assets/104348397/d2185be7-25e8-41c7-8d33-ab5bfe09a563

Staging- 
https://github.com/Expensify/App/assets/104348397/d5e15cc6-a73c-4d03-82b9-4b7b400e2ec1

**Comment by jliexpensify** [comment] 2023-09-06 07:10
Oh my mistake - I was trying to repro on the aopp, not Chrome. I can definitely see the issue on Chrome now. Thanks @ishpaul777 !

**Comment by jliexpensify** [comment] 2023-09-06 22:02
Looks like this might be an Android only issue - a colleague could not repro on iOS.

**Comment by ArekChr** [comment] 2023-09-11 09:58
@ginsuma After this change, Onyx will store the isVisible value to true of the modal, which is not true, it may introduce regression

**Comment by ArekChr** [comment] 2023-09-12 11:37
@ginsuma I mean this code,

```js
    const hideModal = useCallback(
        (callHideCallback = true) => {
            if (shouldSetModalVisibility) {
                Modal.setModalVisibility(false);
            }
            if (callHideCallback) {
                onModalHide();
            }
            Modal.onModalDidClose();
            if (!fullscreen) {
                ComposerFocusManager.setReadyToFocus();
            }
        },
        [shouldSetModalVisibility, onModalHide, fullscreen],
    );
```

The issue is that when `shouldSetModalVisibility` is false, the `isModalVisible` remains true. If I'm not mistaken this behaviour is intended for scenarios where modals shouldn't interfere with the composer's ability to blur. This is particularly relevant for modals like EmojiPicker, ReportActionContextMenu, or ReactionList, especially when we're not dealing with a full-overlay modal. In this scenario `BaseVideoChatButtonAndMenu` is a full-overlay modal.

**Comment by jliexpensify** [comment] 2023-09-18 00:40
Still waiting proposals. Bumping @ginsuma to check out the above comment.

**Comment by jliexpensify** [comment] 2023-09-20 01:45
Still awaiting proposals, also bumping @ginsuma for this [comment](https://github.com/Expensify/App/issues/26763#issuecomment-1715559051)

**Comment by ArekChr** [comment] 2023-09-21 12:16
@ginsuma Thanks for the deeper investigation. You are right about the modal state. Both solutions work for me. Also, I'm thinking about setting `willBlurTextInputOnTapOutside` to `false` for mobile browsers, but it requires to ensure that nothing will be broken.

**Comment by ArekChr** [comment] 2023-09-22 08:32
@ginsuma Let's go with the first solution then, the [proposal](https://github.com/Expensify/App/issues/26763#issuecomment-1706590194) approved

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by pecanoro** [comment] 2023-09-25 06:43
Sounds good! Assigning @ginsuma

**Comment by jliexpensify** [comment] 2023-10-12 04:59
Payment Summary:

- Bug Reporter: @ishpaul777 $50
- Contributor: @ginsuma $500
- C+: @ArekChr (invoiced payment)

[Upwork job](https://www.upwork.com/jobs/~01d03561e10ecc1b6d)

@ArekChr bump to complete the checklist please!

**Comment by jliexpensify** [comment] 2023-10-12 05:35
Thanks, have adjusted this GH!

**Comment by jliexpensify** [comment] 2023-10-16 00:12
No payment date yet

**Comment by ArekChr** [comment] 2023-10-23 12:37
- [x] Link to the PR: No bug identified.
- [x] Link to comment: n/a
- [x] Link to discussion: n/a
- [x] Determine if we should create a regression test for this bug: We can create regression test.

Regression test proposal:

1. Open any report.
2. Check the status of the composer box to ensure it is not currently active. If it is active, click elsewhere on the screen to remove focus from the composer box.
3. Tap on three-dot icon in upper right corner.
4. Hide options modal.
5. Verify once again that the composer box remains unfocused.

Do we agree :+1: or :-1:

**Comment by jliexpensify** [comment] 2023-10-24 00:11
@pecanoro it looks like this PR was merged in [17 days](https://github.com/Expensify/App/issues/26763#issuecomment-1769004798). Normally, we'd cancel the contract and not issue payment for this length of time, but it looks like there was quite a bit of discussion in the PR. Should we penalise anyone or keep it at $500?

**Comment by pecanoro** [comment] 2023-10-24 18:09
Yes, the PR took a bit since there was a bit of back and forth, but we should do the 50% penalty as those are our rules.

**Comment by jliexpensify** [comment] 2023-10-25 01:32
@ginsuma I think @pecanoro has taken into account https://github.com/Expensify/App/pull/28899 - I just checked the dates and there's ~14 days between you being assigned the PR and it being merged by Rocio.

So essentially, the Contributor and C+ payout would be halved here.

**Comment by jliexpensify** [comment] 2023-10-30 04:10
Paid and job closed.

**Closed** 2023-10-30 04:14 UTC
Labels: External, Weekly, Awaiting Payment, Bug
