### ISSUE TITLE
[$250] Last message in the LHN shows differently when mentioning someone in the chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44735] opened 2024-07-02 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719477397021209

## Action Performed:
1. Go to staging.new.expensify.com
2. In DM send a message mentioning someone

## Expected Result:
The report view and LHN should be same

## Actual Result:
It shows display name in the LHN and email in the chat report
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (38)](https://github.com/Expensify/App/assets/38435837/4db23d3c-358e-4549-9093-ba061584599e)
![image (39)](https://github.com/Expensify/App/assets/38435837/45383581-82f7-4e4b-b2e5-803fc760d1ba)

![Snip - New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/6c2a1829-90cf-48ae-b822-34474df7bc6a)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf0d533815a1b85f</li>
        <li>Upwork Job ID: 1808459900002362145</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 103081860</li>
<li>nkdengineer | Contributor | 103081863</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by flodnv** [comment] 2024-07-03 11:18
>In the report chat, the mentioned user is displayed as HTML using the value from reportAction.OriginalMessage. This approach displays the user's email.

@devguest07 in the very first screenshot, it's not an email that we see.

**Comment by nkdengineer** [comment] 2024-07-03 12:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It shows display name in the LHN and email in the chat report

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/8e2831c4c9cc3844c5ac9933787ad5a01bda82f1/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62, there's a problem that if `user?.login` exists, it will be used when rendering user mention, not the display name taken from `PersonalDetailsUtils.getDisplayNameOrDefault`

It's not right as we want to show the user display name if possible.

### What changes do you think we should make in order to solve the problem?

Update https://github.com/Expensify/App/blob/8e2831c4c9cc3844c5ac9933787ad5a01bda82f1/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.tsx#L62 to prioritize showing the display name
```
mentionDisplayText = PersonalDetailsUtils.getDisplayNameOrDefault(user) || LocalePhoneNumber.formatPhoneNumber(user?.login ?? '');
```
Or can remove LocalePhoneNumber.formatPhoneNumber(user?.login ?? '') altogether and only use display name

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-03 12:19
[Proposal updated](https://github.com/Expensify/App/issues/44735#issuecomment-2205926099) to add alternative solution

**Comment by flodnv** [comment] 2024-07-04 09:29
I'm not too sure actually, maybe @puneetlath knows?

**Comment by puneetlath** [comment] 2024-07-08 19:54
I would think it'd be the same as what we see in the chat. So if in the chat we see `hi @test2 how's it going?` then I think the LHN should ideally show the same.

**Comment by nkdengineer** [comment] 2024-07-10 11:59
> @puneetlath So we prioritize the short mention over the display name, right?

I also agree with this, this is covered in [my alternative solution](https://github.com/Expensify/App/issues/44735#issuecomment-2205926099).

**Comment by puneetlath** [comment] 2024-07-10 13:53
Yes, that's correct. If you are on the same private domain, you'd see the short mention.

**Comment by marcochavezf** [comment] 2024-07-11 17:14
Cool, thanks for the review @dukenv0307! assigning @nkdengineer 🚀

**Comment by nkdengineer** [comment] 2024-07-15 15:52
I'll raise PR soon

**Comment by nkdengineer** [comment] 2024-07-30 03:10
@dukenv0307  @marcochavezf @puneetlath   Currently, when a user adds a new comment and mentions another user, the backend returns the mentioned user in the form of an email. Is this expected?


https://github.com/user-attachments/assets/4b4a9bb9-a64a-4c44-8d68-577d2daea2de

![Screenshot 2024-07-25 at 16 05 12](https://github.com/user-attachments/assets/b4fbfa74-0dce-43d2-92fb-880df7bfdf48)

**Comment by nkdengineer** [comment] 2024-08-06 02:38
@dukenv0307 updated

**Comment by puneetlath** [comment] 2024-08-08 17:39
It's not something I'm working on. Looks like @marcochavezf is assigned here.

**Comment by marcochavezf** [comment] 2024-08-08 17:58
Sorry, I've been focused on other high-priority stuff, I will come back to this one soon (hopefully today)

**Comment by nkdengineer** [comment] 2024-08-21 02:30
@marcochavezf friendly bump

**Comment by nkdengineer** [comment] 2024-08-27 03:21
@marcochavezf any update here?

**Comment by marcochavezf** [comment] 2024-08-28 19:09
I've been focused on other priorities, I will move it again to daily to tackle it soon

**Comment by marcochavezf** [comment] 2024-08-30 19:38
No update

**Comment by marcochavezf** [comment] 2024-09-03 21:03
No update

**Comment by marcochavezf** [comment] 2024-09-09 18:26
Not a priority, unassigning myself for now

**Comment by kevinksullivan** [comment] 2024-09-12 19:25
Looping in a BZ member to handle payment as I'm going OOO

**Comment by sonialiap** [comment] 2024-09-13 10:44
Summary: 
- PR for this issue is on hold https://github.com/Expensify/App/pull/45502 for a BE change
- We need an internal engineer to update lastMessageText https://github.com/Expensify/App/issues/44735#issuecomment-2259595786

@dukenv0307 (I'm catching up) We want lastMessageText to be updated on the BE to show the short mention, where the short mention is the mentioned person's name. Is this correct?

**Comment by sonialiap** [comment] 2024-09-16 10:12
Got it, thanks for the clarification :)

Posted in [slack](https://expensify.slack.com/archives/C066HJM2CAZ/p1726481434994929) for an internal engineer for the BE change

Just a heads up, VSB is on hold so we may not get traction on this quickly

**Comment by sonialiap** [comment] 2024-09-20 08:02
No reactions from the internal engineering team

**Comment by sonialiap** [comment] 2024-09-23 10:49
@kevinksullivan handing back since you're back from OOO. We need an internal engineer ([summary](https://github.com/Expensify/App/issues/44735#issuecomment-2348634973)) but VSB is on hold

**Comment by CortneyOfstad** [comment] 2024-10-01 15:08
Bumped this again in `#newdot-quality` in Slack [here](https://expensify.enterprise.slack.com/archives/C05LX9D6E07/p1727795268792099)

**Comment by tgolen** [comment] 2024-10-01 15:15
I can take this and begin looking into it today.

**Comment by tgolen** [comment] 2024-10-01 17:45
I was talking with @iwiznia about this [on Slack](https://expensify.slack.com/archives/C03TQ48KC/p1727802051172819) and I don't think we want to make the backend change necessary for this. The problem is that the `lastMessageText` should be the same for everyone in the report (this helps us to make the report data efficient for everyone to load and get updates about). 

If we were to introduce this shortened name, the `lastMessageText` could be different for different report participants (sometimes it would be the full display name, and sometimes it would be only the first name depending on if the user was "known" or not).

For this reason, I think this issue should be closed as "won't fix" for now.

**Comment by nkdengineer** [comment] 2024-10-02 03:51
@CortneyOfstad should we process payment here?

**Comment by CortneyOfstad** [comment] 2024-10-09 13:52
## Payment Summary

@nkdengineer — paid $250 via Upwork
@dukenv0307 — paid $250 via Upwork

**Closed by CortneyOfstad** 2024-10-09 13:52 UTC
Labels: Daily, Internal, Bug, Hot Pick
