### ISSUE TITLE
[HOLD for payment 2024-03-19] [HOLD for payment 2024-03-14] [$500] IOU - An employee can access in a paid IOU the tag selection menu via a URL request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36264] opened 2024-02-09 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4292715
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
Set up an OldDot admin account, enable and add multiple tags, invite an employee to the policy https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0
1. Open https://staging.new.expensify.com/
2. Log in with the account of the employee added to the policy
3. Navigate to the group policy chat room
4. Create a manual request and send it to the WS room
5. Open https://staging.new.expensify.com/
in incognito mode
6. Log in to the policy administrator account
7. Pay the money request from the employee
8. Go to the details of the paid IOU
9. Click on the Tag field to display a list of available tags
10. Copy the URL address
11. Paste and send the copied URL in the IOU details
12. On behalf of the employee, go to the details of the paid IOU
13. Click on the link sent by the administrator

## Expected Result:
An employee should not access in a paid IOU the tag selection menu via a URL request

## Actual Result:
An employee can access in a paid IOU the tag selection menu via a URL request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e410781-7143-4805-9c77-6f7a0a2d815c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b368611226d91a30</li>
        <li>Upwork Job ID: 1755992751668711424</li>
        <li>Last Price Increase: 2024-02-09</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>FitseTLT | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-09 16:33
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by FitseTLT** [comment] 2024-02-09 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 An employee can access in a paid IOU the tag selection menu via a URL request

### What is the root cause of that problem?
We are display the tag picker whether the user canEdit or not
### What changes do you think we should make in order to solve the problem?

In `IOURequestStepTag` when cannot edit we should return not found page 
https://github.com/Expensify/App/blob/b9aada861c4e740a422a44c4c13c245382b1f082/src/components/ReportActionItem/MoneyRequestView.tsx#L119-L120
### What alternative solutions did you explore? (Optional)

**Comment by jeremy-croff** [comment] 2024-02-09 18:57
Is there any info on how to get access to https://sites.google.com/applausemail.com/applause-expensifyproject/wiki-guides/newdot-categories?authuser=0?

At the current depth I can only observe from without reproducing, It seems we want to protect the endpoint that is returning the tags initially, and have the UI handle the authorization at that level.

**Comment by FitseTLT** [comment] 2024-02-12 19:41
@ishpaul777 Here is how it looks when you make `FullPageNotFoundView` the top-most parent component in `IOURequestStepTag`
![image](https://github.com/Expensify/App/assets/38649957/3974db04-c9a0-4017-ac79-2462372dd994)

**Comment by FitseTLT** [comment] 2024-02-12 19:46
Updated

**Comment by neil-marcellini** [comment] 2024-02-13 18:47
> @FitseTLT [Proposal](https://github.com/Expensify/App/issues/36264#issuecomment-1936242597) looks good to me 🚀
> 
> 🎀 👀 🎀 C+ reviewed

I agree, the proposal to show the not found page if the user can't edit is the right approach.

**Comment by FitseTLT** [comment] 2024-02-21 19:38
Pr will be created in 2 days

**Comment by DylanDylann** [comment] 2024-03-07 08:11
## Regression: Can't edit tag in split bill flow 

Note: we need to create a split bill request by scanning an image 

https://github.com/Expensify/App/assets/141406735/26638de1-481d-456c-9184-cfb97a84f028

**Comment by JmillsExpensify** [comment] 2024-03-19 19:56
Payment summary while we wait on the BZ checklist:

 - Contributor: @FitseTLT $500
 - Contributor+: @ishpaul777 $500

**Comment by JmillsExpensify** [comment] 2024-03-19 21:42
Thank you! Mind filling out the BZ checklist when you get a chance? Then we can issue payments. 🙌🏼

**Comment by JmillsExpensify** [comment] 2024-03-24 02:39
All contributors paid via Upwork and regression test created, so I'm closing the issue.

**Closed by JmillsExpensify** 2024-03-24 02:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
