### ISSUE TITLE
[$1000] DEV Env - App performance on Android is extremely slow - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10345] opened 2022-08-11 04:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Upgrade Android app build in Dev to latest version
2. Navigate to chats 
3. Create group chat
4. try other typical user actions 

## Expected Result:
App should load and respond quickly 

## Actual Result:
Button clicks takes about 2-3 second to react.
List rendering is very slow.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 
**Reproducible in staging?:** N
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43995119/184063549-eb3176a8-23b2-494a-9265-ca3d982caedd.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660159264911759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-08-11 14:11
Double checking if the [ReactNative version upgrade](https://github.com/Expensify/App/pull/9841) done lately has affected the performance as it was mentioned in the slack thread multiple times

**Comment by PauloGasparSv** [comment] 2022-08-11 14:45
Problem was replicated successfully locally on `main` and goes to back to normal if tested on a commit before the RN version upgrade. Solving the issue requires a bigger investigation, since this can be worked by internal and external people I'm adding the external label.
cc @roryabraham and @AndrewGable 

### Useful links
https://reactnative.dev/blog/2022/06/21/version-069
https://reactnative.dev/docs/next/react-18-and-react-native
https://github.com/facebook/react-native/blob/main/CHANGELOG.md

**Comment by adelekennedy** [comment] 2022-08-11 21:50
[internal](https://www.upwork.com/ab/applicants/1557846877608652800/job-details)
[external](https://www.upwork.com/jobs/~01d9b42815de8e3b6b)

**Comment by marcaaron** [comment] 2022-08-15 23:23
Just curious if there is a more specific deliverable for this issue. In the past, when we have issues like "make x faster" the discussion tends not to land anywhere or a variety of solutions are provided. How much faster is fast enough? Are people using Android Emulator or actual devices when they experience the slowness? Am I reading this correctly and the slowness doesn't affect the release build only the dev build?

**Comment by dhairyasenjaliya** [comment] 2022-08-16 09:33
Until any permanent fix, the current workaround is to disable Hermes from the android build.gradle 

- I suspect the latest react version includes Hermes by default at an early stage than it was intended in the 0.70 version  now making 0.69 an unnecessary mess into android 

0.70 - https://reactnative.dev/blog/2022/07/08/hermes-as-the-default
0.69 - https://reactnative.dev/architecture/bundled-hermes#android-users-on-new-architecture-building-on-windows

https://github.com/Expensify/App/blob/3faeca0e3f7f8cebb7f8509f89106573be99a44e/android/app/build.gradle#L82-L84

 `enableHermes: false,`
 
 **Result after disabling Hermes on android** 

https://user-images.githubusercontent.com/47522946/184847124-6376bf10-69ed-4fd7-8653-d0b92cb09c9b.mp4

**Comment by dhairyasenjaliya** [comment] 2022-08-16 09:41
hm @parasharrajat this is not any proposal this is just temp fix for those who need to test android until the permanent fix

**Comment by dhairyasenjaliya** [comment] 2022-08-16 09:47
yes, Hermes was working fine, but in the latest 0.69 they include by default as an engine previously it was external so I believe something goes wrong with android

**Comment by ntdiary** [comment] 2022-08-19 11:10
# Proposal
## Solution
OMG, I noticed this issue eight days ago, it is so hard to investigate. 😅
Some progress now: 

1. please try to build `react-native` with NDK 21
2. use this version of hermes-engine in the project
3. and then app will work fine.

<img width="900" alt="0" src="https://user-images.githubusercontent.com/8579651/185596174-82bccb8e-2f4a-4556-b6e3-456ce5055798.png">

https://user-images.githubusercontent.com/8579651/185593273-30e64958-af8b-4324-ac84-f194cd956b5a.mp4

## Extra
This is the content of `libhermes.so` in the `react-native` and `@expensify/react-native`

<img width="800" alt="1" src="https://user-images.githubusercontent.com/8579651/185596272-bd4e8118-1d9f-47b1-99d6-908183225ddd.png">

**Comment by ntdiary** [comment] 2022-08-22 12:02
![image](https://user-images.githubusercontent.com/8579651/185913186-bc9d805b-5f75-4ca9-b040-417d709541af.png)

Hi @marcochavezf , NDK 21 is default version for [AGP 7.1.1](https://developer.android.com/studio/releases/gradle-plugin#7-1-0)

[react-native-0.69.4](https://registry.npmjs.com/react-native/-/react-native-0.69.4.tgz) is from facebook repo, it is built with NDK 21, and there is no problem with its performance.

https://github.com/Expensify/App/blob/128ea378f2e1418140325c02f0b894ee60a8e53f/package.json#L85

`@expensify/react-native@0.69.4` is built with NDK 24, `hermes-engine-0.69.4-debug.aar` in this version has performance problem.
Do we need to use NDK 24 to build `@expensify/react-native` ?

**Comment by AndrewGable** [comment] 2022-08-22 13:06
I think @roryabraham said he confirmed that using JSC engine (instead of hermes) for app development fixed this. Are you going to send a PR for that @roryabraham ?

**Comment by ntdiary** [comment] 2022-08-23 06:25
@parasharrajat Are you looking for this?
https://github.com/Expensify/react-native

**Comment by marcochavezf** [comment] 2022-08-23 17:54
I noticed we're using NDK 24 [here](https://github.com/Expensify/App/blob/617ad44203dfc879882c7f320b05ec5fcfad0d32/android/build.gradle#L12-L18) for M1, so not sure if that change is related to this problem.

**Comment by ntdiary** [comment] 2022-08-24 02:14
I built the Android App with `npm:@expensify/react-native@0.69.4` on Intel Mac, it had this problem.
And then I built `@expensify/react-native` with NDK21, used it in this project and the app worked well

**Comment by roryabraham** [comment] 2022-08-29 15:15
@marcochavezf I am going to steal this from you to investigate @ntdiary's proposed solution and see if it fixes the problem, just because I've got a fair deal of experience building RN from source and publishing the fork. It's a pain, but just let me know if you want to take this issue back. I know it's a pain point right now that's going to effect local testing, and by extension the stability of the app.

**Comment by roryabraham** [comment] 2022-08-30 13:58
Tried to do this but ran into issues updating our fork: https://expensify.slack.com/archives/C03TQ48KC/p1661867760213829

**Comment by roryabraham** [comment] 2022-09-05 10:28
Sorry, have had other priorities and also issues updating our fork. Will follow-up soon.

**Comment by Santhosh-Sellavel** [comment] 2022-09-08 21:31
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2022-09-14 10:13
Not overdue

**Comment by adelekennedy** [comment] 2022-09-19 16:30
are we still researching this one @roryabraham? Do we need to put this on hold?

**Comment by marcaaron** [comment] 2022-09-19 16:35
I don't think we can put this on HOLD. The Android dev build is unusable. Since one of our main focuses at the moment is improving performance and Android performance is the worst out of all the platforms we would benefit greatly from being able to debug and profile the Android app without workarounds.

**Comment by roryabraham** [comment] 2022-09-22 00:24
I am currently republishing our React Native fork (and using ndk 21 instead of 24) – hopefully that will fix this issue once we upgrade E/App. We shall see... I used

**Comment by roryabraham** [comment] 2022-09-23 21:41
This seems to have been resolved by https://github.com/Expensify/App/pull/10860

**Comment by roryabraham** [comment] 2022-09-23 21:41
Reopening to pay @ntdiary a bounty for figuring out the NDK issue

**Comment by roryabraham** [comment] 2022-09-23 21:43
@ntdiary Please apply to the [upwork job](https://www.upwork.com/jobs/~01d9b42815de8e3b6b) so that @adelekennedy can pay you the bounty. No C+ bounty on this one

**Comment by ntdiary** [comment] 2022-09-26 13:55
Hi @roryabraham, thanks for reminding 🙂
Just curious if it is possible to re-evaluate this bounty or if this issue is difficult in your opinion.
I encountered this issue after testing the image file size issue, and then it took me a week to finally figure out the NDK version was the cause of this issue, as I thought it seemed to be more urgent at the time. 😂

Actually, it's a pity I didn't do more work with you because of other stuffs.
And I really like the atmosphere here. So even if the bounty won't increase, I'm also happy to pick up more issue here. 😄

**Comment by roryabraham** [comment] 2022-09-26 21:51
Yes, I think it's fair to bump this up to $1000. This issue was urgent and I'm not sure how you even figured out the NDK issue 😂 Were you building your own fork of React Native locally?

Anyways, it's possible I might have _accidentally_ fixed this issue while working on something unrelated, but:

1. I might not have realized that the NDK version was important
1. We might not have quickly realized what PR made the difference and fixed this issue
1. We'll also never know because you had already figured out the NDK issue before I republished our fork

**Comment by ntdiary** [comment] 2022-09-27 04:46
Thanks for your affirmation. 😄
I don't have my own fork of `react-native`. I have also tried to find the cause of this issue from many aspects, but all failed. As a last attempt, I had to carefully compare some differences of `hermes engine`. At that time, I noticed the huge difference in file size. Then I checked the contents of binary file and found the NDK issue. Finally I submitted the proposal above after rebuilding the `@expensify/react-native` and verifying it locally. 😂

Could I apply this upwork job with $1000 now? Or need to wait for some other confirmation?

**Comment by adelekennedy** [comment] 2022-09-27 22:44
Upped the pay in Upwork and here - @ntdiary do you mind applying [here](https://www.upwork.com/jobs/~0123e5d47c48136d3e)?

**Comment by ntdiary** [comment] 2022-09-27 23:28
@adelekennedy, Thanks, I have applied. 😄

**Comment by adelekennedy** [comment] 2022-09-29 23:21
@parasharrajat please do!

**Comment by adelekennedy** [comment] 2022-10-04 20:24
@parasharrajat did you apply for the bonus?

**Comment by parasharrajat** [comment] 2022-10-04 20:26
@adelekennedy Done.

**Comment by roryabraham** [comment] 2022-10-06 21:26
@adelekennedy Let's pay this out and close it

**Closed** 2022-10-10 16:04 UTC
Labels: Engineering, Daily, Overdue
