### ISSUE TITLE
[$500] [Distance] - Automatic Saving of Start or End Point and Redirection to Distance Page Renders Save Button Useless

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27108] opened 2023-09-10 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the plus sign and select "Request Money."
2. Go to the Distance page and input a start or end point. Observe that the app saves the location automatically without requiring the user to click Save. Furthermore, selecting a start point redirects the user to the Distance page instead of staying on the current page until saved.

## Expected Result:
 The Save button should either work correctly or be removed. When a start or end point is selected, the location should be chosen but not saved until the user clicks Save. The app should remain on the current page until the user decides to save and then redirect to the Distance page.

## Actual Result:
Selecting a start or end point automatically saves the location and redirects to the Distance page, making the Save button unnecessary.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-09-05T045157.755.webm](https://github.com/Expensify/App/assets/93399543/5a885a02-46ae-4325-ba54-b5a4a3546104)

https://github.com/Expensify/App/assets/93399543/986956ef-dbf7-4560-86a3-a375ab16e34c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693914355944309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0110ac5e7e0555b43d</li>
        <li>Upwork Job ID: 1700877906162176000</li>
        <li>Last Price Increase: 2023-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26660141</li>
<li>tewodrosGirmaA | Reporter | 26660142</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-10 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[Distance]Automatic Saving of Start or End Point and Redirection to Distance Page Renders Save Button Useless
### What is the root cause of that problem?
When selecting the address, the App will redirect to Distance request Page by this logic
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/pages/iou/WaypointEditor.js#L157
### What changes do you think we should make in order to solve the problem?
We should hide the save button in the WaypointEditor Page
To do that
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/pages/iou/WaypointEditor.js#L193
Here, we add 
```
isSubmitButtonVisible={false}
```

and remove redundant props like submitButtonText, onSubmit...
### What alternative solutions did you explore? (Optional)
when selecting option, we don't navigate back by removing this line

https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/pages/iou/WaypointEditor.js#L157

**Comment by iamsid47** [comment] 2023-09-10 15:31
Wanted to contribute on this one... but I guess it's taken :(

**Comment by iamsid47** [comment] 2023-09-10 15:34
Contributor details
Your Expensify account email: siddheshkulthe43@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01436626654ff57e2c

**Comment by MbuguaGeorge** [comment] 2023-09-10 16:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 [Distance] - Automatic Saving of Start or End Point and Redirection to Distance Page Renders Save Button Useless

### What is the root cause of that problem?
[/App/src/pages/iou/WaypointEditor.js
![Screenshot from 2023-09-10 19-26-05](https://github.com/Expensify/App/assets/53429649/0561b536-9eda-4b8e-bfc0-0ac332d7aad5)
](/App/src/pages/iou/WaypointEditor.js#L157)


### What changes do you think we should make in order to solve the problem?
To address the problem, we should consider removing this line. Instead, we should implement the redirection behavior exclusively when the save button is clicked. This approach maintains consistency, especially since the save button is currently designed to function offline.

### What alternative solutions did you explore? (Optional)
N/A

[Result](https://github.com/Expensify/App/assets/53429649/5be5b890-3428-45b1-99c7-44f536bb5f03)

**Comment by MbuguaGeorge** [comment] 2023-09-10 16:46
Contributor details
Your Expensify account email: mbuguageorge026@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b5c31c1a719ec270

**Comment by tewodrosGirmaA** [comment] 2023-09-10 21:01
> I think it will be fixed #27021 

Not the same bug ,it is different

**Comment by robertKozik** [comment] 2023-09-13 18:47
@abekkala I'm also a C+ on #27021. Chosen proposal does not contain removing the save button, as it should only address saving waypoints in offline mode. That's why I think we should fix this issue individually, but as this would contain only removing the submit button or removing redirect function, we can consider reducing the bounty due to simplicity of this issue

**Comment by robertKozik** [comment] 2023-09-13 18:52
Thank you all for your proposals! 🙇🏼 
Both proposals here correctly pinpointed the root cause and proposed the same solutions. As @DylanDylann proposal was the quickest I think you should be assigned to this issue.

Moreover as in issue #27021 we will probably remove the possibility of typing random waypoint in offline mode, the save button will become obsolete in every scenario as choosing waypoint from the list will trigger the redirect, so we should go with your main proposed solution - removing the submit button

Selected Proposal: [Proposal](https://github.com/Expensify/App/issues/27108#issuecomment-1712828406)
Contributor: @DylanDylann 

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2023-09-14 09:01
@robertKozik The PR is ready for review

**Comment by robertKozik** [comment] 2023-09-18 07:38
Hello!

I'm following up on issue #27021. It seems that saving from the autocomplete dropdown should be an option for offline flows. Since I don't have access to the Slack conversation mentioned in [this comment](https://github.com/Expensify/App/issues/27021#issuecomment-1722721836), could we please double-check whether this behavior is indeed a bug or if it's intended?
CC. @tgolen @abekkala

**Comment by DylanDylann** [comment] 2023-09-20 04:24
@thienlnam I see that you implement offline flow in distance request. So could you help to check [this comment](https://github.com/Expensify/App/issues/27108#issuecomment-1722893031) ?

**Comment by tgolen** [comment] 2023-09-21 05:07
@robertKozik I think everything is fine here. This issue is only about removing the save button because it functionally has no purpose since everything is automatically saved when you select a waypoint.

https://github.com/Expensify/App/issues/27021 Is about being able to select an invalid waypoint when you are offline.

Maybe I'm not quite understanding your question, but I don't see how these are directly related.

> could we please double-check whether this behavior is indeed a bug or if it's intended?

Could you please clarify what "this behavior" is that you are asking about? I'm not sure what it's referring to.

**Comment by thienlnam** [comment] 2023-09-21 05:21
Yeah, it's possible to enter in a waypoint offline - so I don't think this is a bug and we can close.

We _could_ remove the save button while you're online? But I don't really see the need to update that flow

**Comment by DylanDylann** [comment] 2023-09-22 07:22
@tgolen @robertKozik Could you take a look at [this comment](https://github.com/Expensify/App/issues/27108#issuecomment-1728868471) ?

**Comment by tgolen** [comment] 2023-09-22 11:24
It's just so weird to leave a button there when it has zero functionality. I'd remove it.

**Comment by DylanDylann** [comment] 2023-09-22 11:39
@tgolen when offline, there are no suggestion address for user. So user only can enter address manually and click save button

**Comment by thienlnam** [comment] 2023-09-25 02:05
> It's just so weird to leave a button there when it has zero functionality. I'd remove it.

It is not required for the online flow, but is required for the offline flow. Are you suggesting removing it for just the online flow?

**Comment by tgolen** [comment] 2023-09-25 03:16
OK, I understand now. If it's needed for one of the flows, let's leave it
there for both flows and we can just close this.

**Closed** 2023-10-10 14:37 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by tewodrosGirmaA** [comment] 2023-10-10 14:55
hello @abekkala , i get an offer but payment is not settled

**Comment by DylanDylann** [comment] 2023-10-12 16:20
@abekkala  Are we eligible for compensation? Contributors are already assigned and started on the PR. It's just due to the expectation changes and the solution becomes outdated.

**Comment by abekkala** [comment] 2023-10-19 13:33
based on this https://github.com/Expensify/App/issues/18664#issuecomment-1565898728

Sending payment offers to 

- @tewodrosGirmaA [$50]

- @DylanDylann  [$500] 
- @robertKozik [$500]
