### ISSUE TITLE
[HOLD for payment 2024-03-29] Bank account - "Continue with setup" is less indented than "Start over"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38482] opened 2024-03-18 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has quit bank account setup while in the middle of it.
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > any workspace.
3. Go to Bank account.

## Expected Result:
"Continue with setup" will have the same level of indentation as "Start over".

## Actual Result:
"Continue with setup" is less indented than "Start over".

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/6a2ee5cd-2779-4910-8ef7-7439f916562e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2b89887e68785d4</li>
        <li>Upwork Job ID: 1775720355254845440</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-18 15:31
We think that this bug might be related to #wave-collect - Release 1

**Comment by godofoutcasts94** [comment] 2024-03-18 15:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - "Continue with setup" is less indented than "Start over"
### What is the root cause of that problem?
The root cause of the problem is here : 
https://github.com/Expensify/App/blob/7742bec5c32e4118963fcdc67d3c15b7412f3838/src/styles/index.ts#L3492-L3498
we have more margin to the left for "Start Over" text in comparison to "Continue"

### What changes do you think we should make in order to solve the problem?

We need to reduce it from `8` to `7`. This should fix it 
### What alternative solutions did you explore? (Optional)
N/A

### Result 

<img width="1248" alt="Screenshot 2024-03-18 at 9 25 55 PM" src="https://github.com/Expensify/App/assets/158435970/82003a5c-0c69-4a4d-99f5-1b26496dd8e1">

**Comment by shahinyan11** [comment] 2024-03-18 16:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - "Continue with setup" is less indented than "Start over"
### What is the root cause of that problem?
There is not set `iconStyles` prop on [Button](https://github.com/Expensify/App/blob/7742bec5c32e4118963fcdc67d3c15b7412f3838/src/pages/ReimbursementAccount/ContinueBankAccountSetup.js#L67C26-L67C32) component
### What changes do you think we should make in order to solve the problem?
Add `iconStyles={[styles.customMarginButtonWithMenuItem]}` prop on Button component .

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-03-18 16:17
## Proposal
[Updated](https://github.com/Expensify/App/issues/38482#issuecomment-2004326375). Added a link to a similar implementation like mine in another place

**Comment by mallenexpensify** [comment] 2024-03-18 20:36
@dannymcclain , 👀 on the screenshot in the OP.   Do you think it's _worth_ fixing? If so, I'll start the price at $250 since it seems like a relatively easy bug.

**Comment by dannymcclain** [comment] 2024-03-18 20:52
@mallenexpensify I do think it's worth fixing. But @shawnborton, didn't we just run into this issue on another PR? Was it the one about button styles? Maybe this should just be a follow up to that if it's the same problem.

**Comment by godofoutcasts94** [comment] 2024-03-18 20:56
@dannymcclain This is similar issue like this https://github.com/Expensify/App/issues/38291

**Comment by dannymcclain** [comment] 2024-03-18 21:13
That's the one! Thank you @godofoutcasts94

**Comment by shawnborton** [comment] 2024-03-19 12:39
Actually yeah, I think @narefyev91 already had a fix for this? Can you confirm?

**Comment by shawnborton** [comment] 2024-03-19 12:45
Okay great, that would be good. Just flagging @luacmartins @mountiny for visibility as this would be another #ideal-nav follow up.

**Comment by dannymcclain** [comment] 2024-04-02 13:31
Any news here?

**Comment by mallenexpensify** [comment] 2024-04-03 00:20
@Pujan92 , you reviewed [ the PR](https://github.com/Expensify/App/pull/38608) so you're due compensation here, right? 

Assuming so, can you complete the above BZ checklist? I imagine we either don't need a testrail GH or it'd be one we just check everyone month as part of the design and edge case test run.

**Comment by Pujan92** [comment] 2024-04-03 10:01
> @Pujan92 , you reviewed [ the PR](https://github.com/Expensify/App/pull/38608) so you're due compensation here, right?

Yes @mallenexpensify 

> Assuming so, can you complete the above BZ checklist?

It is already completed by @jasperhuangg.

**Comment by mallenexpensify** [comment] 2024-04-04 03:02
@Pujan92 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01c2b89887e68785d4

**Comment by Pujan92** [comment] 2024-04-04 03:13
> @Pujan92 can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~01c2b89887e68785d4

Done..

**Comment by mallenexpensify** [comment] 2024-04-05 23:33
Contributor+: @Pujan92 paid $500 via Upwork.  

Thanks

**Closed by mallenexpensify** 2024-04-05 23:33 UTC
Labels: Weekly, Internal, Design, Awaiting Payment, Bug
