### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Web - Chat - Edit message box blink on escape from keyboard shortcut popup

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26527] opened 2023-09-01 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Edit any message
4. Click CTRL+J to open keyboard shortcut
5. Click ESC to close popup and observe that edit message box blinks before changing focus to main compose box

## Expected Result:
Edit message box should not glitch out on change of focus to main compose box as it works currently on ESC from CTRL+K or CTRL+SHIFT+K shortcuts

## Actual Result:
Edit message box blinks on change of focus to main compose box when keyboard shortcut is open using CTRL+J and closed by ESC

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.61-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** Y

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e8d1267d-0194-487d-9a25-4a8c28f533c9

https://github.com/Expensify/App/assets/115492554/3bdb18ff-1e90-4538-b630-415b3fab1887

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692944783305439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad8834baac53effd</li>
        <li>Upwork Job ID: 1698788846930915328</li>
        <li>Last Price Increase: 2023-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>Dhanashree-Sawant | Reporter | 27049742</li>
</ul></li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-09-04 20:03
Can reproduce and is not a dupe

**Comment by joh42** [comment] 2023-09-05 13:26
What is the expected behavior here @anmurali? Should the edit message box be focused?

**Comment by ayazalavi** [comment] 2023-09-06 09:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After selecting any chat from the sidebar and editing any comment within it, the focus shifts to the main compose input once you close the modal.

### What is the root cause of that problem?
Problem exists in code where we are programmatically setting focus to the main composer. It happens in following code 
<img width="683" alt="Screenshot 2023-09-06 at 2 49 21 PM" src="https://github.com/Expensify/App/assets/767439/c0b6cdca-e2d2-401d-b4ff-4d431bd2390c">
File is [ComposerWithSuggestions](https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L433)

### What changes do you think we should make in order to solve the problem?
commenting focus() in [Line 433](https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L433) solves the problem without breaking the code.

### What alternative solutions did you explore? (Optional)
Rewrite focus handler for all inputs in order to manage it within a hook

**Comment by narefyev91** [comment] 2023-09-06 10:57
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> After selecting any chat from the sidebar and editing any comment within it, the focus shifts to the main compose input once you close the modal.
> 
> ### What is the root cause of that problem?
> Problem exists in code where we are programmatically setting focus to the main composer. It happens in following code <img alt="Screenshot 2023-09-06 at 2 49 21 PM" width="683" src="https://user-images.githubusercontent.com/767439/265968013-c0b6cdca-e2d2-401d-b4ff-4d431bd2390c.png"> File is [ComposerWithSuggestions](https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L433)
> 
> ### What changes do you think we should make in order to solve the problem?
> commenting focus() in [Line 433](https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L433) solves the problem without breaking the code.
> 
> ### What alternative solutions did you explore? (Optional)
> Rewrite focus handler for all inputs in order to manage it within a hook

Hey @ayazalavi ! Removing focus will fully break this logic:
`// We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused.`

**Comment by narefyev91** [comment] 2023-09-06 12:27
@ayazalavi your fix will break all modal closing re-focus input logic:
With your fix:

https://github.com/Expensify/App/assets/28352309/a7172392-9e50-4c53-9edd-9fb45a900098

Without your fix:

https://github.com/Expensify/App/assets/28352309/6bf5c17e-e530-4561-a910-6535c8fbdf01

**Comment by narefyev91** [comment] 2023-09-06 20:30
@ayazalavi can you please explain why those lines of code will fix issues - and did you test your code? Will it introduce any regression? Just the same as i mentioned above with focusing composer - after closing right panel

**Comment by ayazalavi** [comment] 2023-09-06 20:55
Please check working solution in a video here:
https://www.dropbox.com/scl/fi/icay0eqj8sal3o2s2926r/480-Screen-Recording-2023-09-07-at-1.45.40-AM.mov?rlkey=3sf9886yprju8l0jhla35d8cr&dl=0

yes I tested code and made 2 changes as explained. `Onblur` in Edit Message making sure that compose box focus is not set to true and also using `shouldAutoFocus` that calculates whether compose field should be focused or not and add that in dependency array where we are calling focus method.

**Comment by ayazalavi** [comment] 2023-09-07 14:28
@narefyev91 have you checked above video?

**Comment by narefyev91** [comment] 2023-09-11 09:10
@ayazalavi thank you for your updated proposal - but your code still introduce regressions
Example - how it should be:

https://github.com/Expensify/App/assets/28352309/2d06a7ed-8bf8-48bb-a534-3fd5a07f95c6

How it's after your code:

https://github.com/Expensify/App/assets/28352309/9206d9ca-714f-4c27-8995-58f52a4f21b1

**Comment by narefyev91** [comment] 2023-09-11 09:22
Also some issues with Android web as well
Before:

https://github.com/Expensify/App/assets/28352309/8182cf40-91b9-4680-a814-3cad7fce61e5

After:

https://github.com/Expensify/App/assets/28352309/0d7e36d6-ee2e-4ba0-b4e9-735f04ee59ce

We should be sure that any new changes regarding autofocus will not introduce any regression on each platform

**Comment by ayazalavi** [comment] 2023-09-11 10:59
@narefyev91 thanks for such detailed review. Let me fix my proposal. Thanks again for the feedback as well.

**Comment by ayazalavi** [comment] 2023-09-12 20:56
@narefyev91 please look at my comment here https://github.com/Expensify/App/issues/26527#issuecomment-1715214959

**Comment by ayazalavi** [comment] 2023-09-13 18:51
### Proposal

[Updated](https://github.com/Expensify/App/issues/26527#issuecomment-1715214959)

**Comment by narefyev91** [comment] 2023-09-15 07:58
Mervin not overdue - waiting for proposals

**Comment by ayazalavi** [comment] 2023-09-15 12:13
@narefyev91 let me check and get back to you.

**Comment by ayazalavi** [comment] 2023-09-18 07:12
### Proposal
[Updated](https://github.com/Expensify/App/issues/26527#issuecomment-1708380347)

**Comment by ayazalavi** [comment] 2023-09-18 07:14
@narefyev91 kindly take a look at my updated proposal. I can add utility method where necessary and convert code into generic hook but see if you think it will work for this specific use case first.

**Comment by narefyev91** [comment] 2023-09-19 08:21
last idea in proposal https://github.com/Expensify/App/issues/26527#issuecomment-1708380347 - looks good to me - to prevent shifting focus we should exactly know that currently on the screen we have 2 active inputs - like edit one and main composer - and we should not re-focusing edit one during modal closing
Let's start working on this idea
🎀 👀 🎀 C+ reviewed

**Comment by amyevans** [comment] 2023-09-20 05:52
Our contributing guidelines state:

https://github.com/Expensify/App/blob/3e73b40d8f5b58b400d892025353b68564e7cee3/contributingGuides/CONTRIBUTING.md?plain=1#L54

So we cannot hire @ayazalavi until their [first GitHub issue](https://github.com/Expensify/App/issues/26735) has been successfully closed.

Some other feedback about the proposal:
* I'm weary of using a setTimeout, it's a bit of a code smell.
* We try to avoid posting so much code in a proposal
* That said, I applied the code changes and I don't think it actually solves the issue (I could be wrong)

Let's leave this open to additional proposals. Overall it's an edge case though so we don't need to be in a rush to fix this one.

**Comment by narefyev91** [comment] 2023-09-20 06:42
> Our contributing guidelines state:
> 
> https://github.com/Expensify/App/blob/3e73b40d8f5b58b400d892025353b68564e7cee3/contributingGuides/CONTRIBUTING.md?plain=1#L54
> 
> So we cannot hire @ayazalavi until their [first GitHub issue](https://github.com/Expensify/App/issues/26735) has been successfully closed.
> 
> Some other feedback about the proposal:
> 
> * I'm weary of using a setTimeout, it's a bit of a code smell.
> * We try to avoid posting so much code in a proposal
> * That said, I applied the code changes and I don't think it actually solves the issue (I could be wrong)
> 
> Let's leave this open to additional proposals. Overall it's an edge case though so we don't need to be in a rush to fix this one.

For sure - during all this code changes - we get the correct idea (maybe a way) how to generally fix this - and all code changes should be discussed in PR. I also will not approve PR with setTimeout - because we have some solution how to avoid it. I'm open for any proposal - we not in a rush state here

**Comment by ayazalavi** [comment] 2023-09-20 08:32
@amyevans i am about to close my PR hopefully today. Also I'll make PR free of settimeout. Will this be alright with you?

**Comment by amyevans** [comment] 2023-09-25 12:52
Not overdue

**Comment by ayazalavi** [comment] 2023-09-26 07:19
@amyevans @narefyev91 my PR is merge. We can go ahead with this issue now. Let me know your thoughts both.

**Comment by narefyev91** [comment] 2023-09-26 15:32
@ayazalavi i think we need to move away from timeouts - because we should not really use them in the app. Can you please work on your proposal a bit deeper - to make solution closely to code guidance expectation. Thanks!

**Comment by narefyev91** [comment] 2023-09-26 15:35
> Yes sure I'll make PR free of timeouts. You can check code then?

I think the blocking point for now is comment from @amyevans https://github.com/Expensify/App/issues/26527#issuecomment-1727013892 - can you please address all changes for your proposal. You can raise PR only after approval

**Comment by ayazalavi** [comment] 2023-09-27 13:10
@amyevans any updates?

**Comment by amyevans** [comment] 2023-09-28 04:40
No updates for the moment, please be patient, thanks!

<hr>

Internal ref: https://expensify.slack.com/archives/C01SKUP7QR0/p1695611158522559

**Comment by ayazalavi** [comment] 2023-09-28 12:20
Sure no issues. Let me know when you are ready to fix it.

**Comment by amyevans** [comment] 2023-10-03 23:58
Still holding for the moment, I will come back to this Friday or Monday

**Comment by ayazalavi** [comment] 2023-10-04 15:10
@amyevans are you guys considering my proposal?

**Comment by amyevans** [comment] 2023-10-06 02:34
Okay, let's move forward here, @ayazalavi please let @narefyev91 know when you have a PR available for review. Please ensure it is fully tested and not using setTimeout. Thanks!

**Comment by ayazalavi** [comment] 2023-10-06 02:37
@amyevans I am getting error on upwork. 

<img width="1173" alt="Screenshot 2023-10-06 at 7 37 40 AM" src="https://github.com/Expensify/App/assets/767439/2891f0c1-cf17-4ef1-85c7-b8cdad2b165e">

**Comment by amyevans** [comment] 2023-10-06 02:39
Hmm @anmurali can you take a look at ^?

**Comment by ayazalavi** [comment] 2023-10-09 10:03
PR ready: https://github.com/Expensify/App/pull/29073

@narefyev91

**Comment by amyevans** [comment] 2023-10-25 13:27
@narefyev91 could you complete the checklist please?

**Comment by narefyev91** [comment] 2023-10-25 13:29
- The PR that introduced the bug has been identified. Link to the PR - fully new implementation - not coming from any regression
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - N/A
- Determine if we should create a regression test for this bug - N/A

**Comment by ayazalavi** [comment] 2023-10-26 02:27
@flaviadefaria https://www.upwork.com/fl/~01a53213c1c66acb2d?s=996364627857502209

**Comment by flaviadefaria** [comment] 2023-10-26 10:55
Payment Summary:

>@ayazalavi requires payment
@narefyev91 does not require payment (Contractor)
@dhanashree-sawant requires payment [offer](https://www.upwork.com/nx/wm/offer/27049742) (Reporter)


@dhanashree-sawant = $50
@ayazalavi = $500 no bonus = $500

**Comment by flaviadefaria** [comment] 2023-10-26 10:58
@dhanashree-sawant = paid
@ayazalavi = offer sent

**Comment by flaviadefaria** [comment] 2023-10-26 11:38
Everyone has been paid so closing this.

**Closed by flaviadefaria** 2023-10-26 11:38 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
