### ISSUE TITLE
[$1000] Web-Console error displayed when connect to bank account clicked on reimbursements

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23172] opened 2023-07-19 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found executing #23033
## Action Performed:
1. Go to Reimbursement page and click on first section, you will get a popup page.
2. Check by changing the data in the second section (Track Distance) for the rate and unit, so that it gets reflected after saving on the reimbursement page.
3. Open the 3rd section (Unlock next-day reimbursements), and check see if its opening correctly.
## EXPECTED RESULT
No error displayed in console and connect to bank account option displayed
## ACTUAL RESULT
Console error displayed

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/698d938e-eb00-48a3-a9c6-1ba937504a44

![Bug6133832_Screen_Shot_2023-07-18_at_8 38 04_PM](https://github.com/Expensify/App/assets/43996225/30f28b57-a036-40d5-a398-ea878006bf4e)

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01031ab68477aeef6a</li>
        <li>Upwork Job ID: 1681712940167335936</li>
        <li>Last Price Increase: 2023-07-19</li>
    </ul>
</details>

**Comment by flodnv** [comment] 2023-07-20 10:46
This is a bit vague... what are we failing to load? Do you know @allroundexperts @sobitneupane ? 😕

**Comment by sobitneupane** [comment] 2023-07-21 07:30
@flodnv Not sure.

But I am getting similar error(Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval') even for homepage.

<img height="500" alt="Screenshot 2023-07-21 at 13 13 22" src="https://github.com/Expensify/App/assets/25876548/d9ef588f-8dba-4d26-aa41-cb12aecbd559">

**Comment by sobitneupane** [comment] 2023-08-02 04:27
@flodnv I was also unable to reproduce the issue.

**Comment by flodnv** [comment] 2023-08-02 07:55
Thanks for checking! Closing.

**Closed by flodnv** 2023-08-02 07:55 UTC
Labels: Engineering, Daily, Internal, Bug
