### ISSUE TITLE
Message seems to be DELETED but displays again when go back to OFFLINE mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21624] opened 2023-06-26 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Delete a message in OFFLINE mode >> the message will be grayed and crossed out
2. Reload page >> The page now is completely OFFLINE
3. Go back ONLINE >> The message seems to be DELETED (that's Good)
4. Go OFFLINE again
## Expected Result: 
Message should be deleted completely and not appearing again
## Actual Result: 
The deleted message displays again
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d7ef390a-6fd7-4044-81c8-d4b75bcad08c

https://github.com/Expensify/App/assets/43996225/e205a858-a6ad-495a-9d48-386347660ef3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687358434329519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-07-05 12:45
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:09
I actually wasn't able to reproduce this issue just using the force offline option.

**Comment by JmillsExpensify** [comment] 2023-07-19 13:37
Still not able to reproduce. Closing.

**Closed by JmillsExpensify** 2023-07-19 13:37 UTC
Labels: Engineering, Daily, Overdue, Bug
