### ISSUE TITLE
App update - Without prompt the build gets updated

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8551] opened 2022-04-08 00:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue was found when executing the PR #8350**
## Action Performed:
1. Have App opened and foregrounded before an update is released
2. Wait for update to be released and then background App - open a new tab
3. Wait for update to be released and then foreground App

## Expected Result:
You should see a prompt to update

## Actual Result:
I don't see the prompt but it gets updated.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.1.51-0 to be updated to v1.1.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  New feature
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/162340585-6fca6139-6ff1-48e1-b7f0-25f7ec2cfbbc.mp4

![Bug5521232_Screen_Shot_2022-04-05_at_3 20 22_PM](https://user-images.githubusercontent.com/43996225/162340587-0800cdb7-88b8-419c-af46-4338d89e242a.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-04-08 00:41
Hmm I don't really understand these reproduction steps, sorry. How can we test this without having an open tab exist before a release goes out?

>Reproducible in production?: New feature

What does this mean? Did we add a new feature?

Not sure what we want to do about this one @roryabraham or if there's a way to test this.

**Comment by roryabraham** [comment] 2022-04-08 07:21
I'm not sure what the video is supposed to show, but according to the description, this is the intended behavior. The web app is _supposed_ to refresh and update itself if you background it. It's a feature, not a bug 😄 In fact, it seems that maybe that behavior has just been broken since its inception and was just fixed by https://github.com/Expensify/App/pull/8350.

**Closed by roryabraham** 2022-04-08 07:21 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by marcaaron** [comment] 2022-04-08 18:56
Awesome, thanks!
