### ISSUE TITLE
[$1000] Report preview action does not have a body if an error occurs or if offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21119] opened 2023-06-20 13:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with the same account in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
In the secondary device Split a bill with 2 users, this should create a new group and 2 new 1:1 conversations
3. In the main testing device (should be offline) create the SAME split bill with the 2 users
4. Navigate to any 1:1 report
5. Enable the internet connection in the main testing device. The split bill request will be sent and you will get an error in the main device only.

## Expected Result:
The report preview action should still show "[me@example.com](mailto:me@example.com) owes $500"

## Actual Result:
The report preview action shows no body

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26-4

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (72)](https://github.com/Expensify/App/assets/93399543/72289986-f582-46c9-b198-821af07bac7b)

![image (71)](https://github.com/Expensify/App/assets/93399543/6c2e8733-997d-4426-be2e-bdb0a8f841a6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @therealsujitk

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686655622360139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f148a3614fc6378</li>
        <li>Upwork Job ID: 1672274061316292608</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-06-20 14:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Report Preview Action has no body when offline or if the report action failed.

### What is the root cause of that problem?

This is because the `html` field is set to an empty string when the action is being created.

https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/libs/ReportUtils.js#L1445

And `lodashGet()` takes that value to be rendered.

https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/components/ReportActionItem/ReportPreview.js#L121

### What changes do you think we should make in order to solve the problem?


One way to fix this is to set the value for `html` to `null`. This will force `lodashGet()` to display a message from it's default parameter until the field gets updated from Pusher.

### What alternative solutions did you explore? (Optional)
None.

**Comment by therealsujitk** [comment] 2023-06-20 14:32
### Simpler way to reproduce

1. Disable internet on your device or in preferences.
2. Create a split with new members.
3. Navigate to any 1:1 chat report created by this split.

**Comment by anmurali** [comment] 2023-06-23 16:03
I get the 1:1 reports with an error (red dot) but there is no error message in the reports

**Comment by therealsujitk** [comment] 2023-06-23 16:04
@anmurali Can you share a screenshot?

**Comment by mananjadhav** [comment] 2023-06-26 05:56
I am not able to reproduce this. The steps that I followed:

1. In a group chat, I went offline.
2. Go to Actions menu -> Click on Split Bill
3. Follow the Split bill process
4. Go to individual chats and check the IOU.

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/3069065/4fd43a25-9704-4040-aae2-41382b9910ba">

**Comment by therealsujitk** [comment] 2023-06-26 06:07
@mananjadhav you're supposed to go the the one-one report, not the IOU report. When you create a split with multiple people, you get a group chat, individual chat reports (one-one report) with each user and individual IOU reports with each user.

<img width="1512" alt="248676946-4fd43a25-9704-4040-aae2-41382b9910ba" src="https://github.com/Expensify/App/assets/60378235/12ba8227-3d87-4642-a10d-3407637cf675">

**Comment by mananjadhav** [comment] 2023-06-26 06:32
@therealsujitk I checked both. For a new group chat I am unable to split bill at all.


https://github.com/Expensify/App/assets/3069065/3b993325-a181-4ec0-8b63-63c41901a9df

**Comment by therealsujitk** [comment] 2023-06-26 07:56
@mananjadhav this looks like I new bug that needs to be reported, it's different from this issue thought. Here's a video on how to reproduce it.

https://github.com/Expensify/App/assets/60378235/20dfdb01-2d68-46ca-b580-a8ffe1d6699b

**Comment by therealsujitk** [comment] 2023-06-26 07:59
@mananjadhav I was able to reproduce the issue in your recording, it will have to be added to **#expensify-bugs**.

**Comment by anmurali** [comment] 2023-07-03 17:05
@mananjadhav do we have any viable proposals for this issue that you favor?

**Comment by mananjadhav** [comment] 2023-07-03 17:50
@anmurali I wasn't able to reproduce [this](https://github.com/Expensify/App/issues/21119#issuecomment-1606699406) earlier last week.  I'll check this once again tomorrow and comment if the above proposal works.

**Comment by therealsujitk** [comment] 2023-07-03 18:15
@mananjadhav when you're free can you try the steps from the video in this comment - https://github.com/Expensify/App/issues/21119#issuecomment-1606911128

**Comment by mananjadhav** [comment] 2023-07-04 19:47
Thanks for the patience here @therealsujitk. I am sorry buddy but I followed the steps and I still can't reproduce. @kbecciv Are you able to reproduce?

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/3069065/43759b60-fd53-4b60-b4c6-4c41efe3ad94">

**Comment by therealsujitk** [comment] 2023-07-04 19:49
@mananjadhav this might have been fixed recently, in your earlier screenshot (https://github.com/Expensify/App/issues/21119#issuecomment-1606711876) this was reproducible. I'll check this again tomorrow.

**Comment by therealsujitk** [comment] 2023-07-04 20:42
The PR #20446 seems to have resolved this issue, but this issue isn't a duplicate of the linked issue (#19301).

**Comment by mananjadhav** [comment] 2023-07-06 20:40
I am not sure about the reporting bonus @therealsujitk. I'll let @anmurali take care of that. But as I said this isn't reproducible anymore. We should close this one out.

**Comment by anmurali** [comment] 2023-07-10 12:48
Why not! Here is [your offer](https://www.upwork.com/nx/wm/offer/25453399) and I will pay when you accept but closing this issue

**Closed by anmurali** 2023-07-10 12:48 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug

**Comment by therealsujitk** [comment] 2023-07-19 01:29
Hi @anmurali, just reminding you about this one.
