### ISSUE TITLE
[$1000] Dev: Web - Console error on report page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22023] opened 2023-07-01 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Refresh Report page
2. Many error shows

## Expected Result:
Errors shouldn't be visible.

## Actual Result:
Console error on report page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** Dev 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (9)](https://github.com/Expensify/App/assets/93399543/413fbc15-3179-4e9e-84cf-0e129be3ddc6)
![image (8)](https://github.com/Expensify/App/assets/93399543/5e6479f2-6d95-47a8-9b2e-c467452c5664)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aliammar1995
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688205314450479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019f8b708de9de6ef3</li>
        <li>Upwork Job ID: 1675889547991613440</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2023-07-03 15:28
I don't get all those exceptions on that screenshot. I do get one consistently
>Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://polyfill.io https://cdn.plaid.com https://www.woopra.com https://assets.onfido.com https://sentry.io https://*.sardine.ai/". Either the 'unsafe-inline' keyword, a hash ('sha256-7g/6t4yA8tsc/QVgz7I0fmfal7nwZsJpx+iM/VqSxYs='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by situchan** [comment] 2023-07-03 15:45
This has 2 console warnings and already dupe of https://github.com/Expensify/App/issues/21840 and https://github.com/Expensify/App/issues/21496

**Comment by bondydaa** [comment] 2023-07-03 17:34
if console errors were added then the original PRs should be found and commented on and fixed by those authors. we shouldn't spin up new issues for these.

**Comment by bondydaa** [comment] 2023-07-05 20:26
okay i'm closing this out as it seems https://github.com/Expensify/App/issues/21840 and https://github.com/Expensify/App/issues/21496 both have PRs in review to fix the console errors.

**Closed by bondydaa** 2023-07-05 20:26 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
