### ISSUE TITLE
[$500] BNP - Changing currency is not showing cursor at the same digit where it is placed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36259] opened 2024-02-09 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab --- request money
3. In BNP, enter 8 digit number with decimal numbers. Eg: 12345678.80
4. Now place cursor after 6
5. Change currency to JMD, note the cursor is in same place
6. Change currency to JPY, note the cursor is shown after 3 

## Expected Result:
In BNP, changing currency must show cursor at the same digit where it is placed

## Actual Result:
In BNP, changing currency is not showing cursor at the same digit where it is placed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/40ef792a-5721-40d1-ab81-24453aad7bf5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c5d302cf7d3d450</li>
        <li>Upwork Job ID: 1755990011912187904</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-02-09 17:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After changing the currency to a currency that doesn't have decimal, the selection moves to the left.

### What is the root cause of that problem?
The selection is calculated by taking the currency selection and adding the difference between previous amount with the new amount.
https://github.com/Expensify/App/blob/4f9d415df4f638e45f5b0d6d1e3f95c9ed5276bf/src/pages/iou/steps/MoneyRequestAmountForm.js#L65-L68

Because the new amount without decimal is smaller, the value is negative, thus reducing the selection.

### What changes do you think we should make in order to solve the problem?

We have an existing solution to keep the selection for forward delete case here by passing the prev and new amount value the same.
https://github.com/Expensify/App/blob/4f9d415df4f638e45f5b0d6d1e3f95c9ed5276bf/src/pages/iou/steps/MoneyRequestAmountForm.js#L163-L166

We can do the same for our case here when the decimal is changed. To do that, we can add a second param to `setNewAmount` called `isDecimalChanged`. If it's true, then we pass the same value for both prev and new amount.

```
(isForwardDelete || isDecimalChanged) ? strippedAmount.length : prevAmount.length
```

Then, we pass true for `isDecimalChanged` here.
https://github.com/Expensify/App/blob/4f9d415df4f638e45f5b0d6d1e3f95c9ed5276bf/src/pages/iou/steps/MoneyRequestAmountForm.js#L181-L182

**Comment by jeremy-croff** [comment] 2024-02-09 19:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cursor position is lost when switching between different currencies. Observed is one with a decimal to non decimal.

### What is the root cause of that problem?
The length between currencies can vary, if it's smaller the cursor adjusts accordingly. 

### What changes do you think we should make in order to solve the problem?
I don't love this logic, as the decimal between currencies is almost irrelevant. I think on currency change the cursor should default to the end.

### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2024-02-10 06:26
Thanks for the other suggestion @jeremy-croff. I'll make sure to keep the expected result as-is for consistency.

I like the proposal from @bernhardoj it indeed maintains the cursor position. Let's go with their proposal!

🎀 👀 🎀 C+ reviewed!

**Comment by isabelastisser** [comment] 2024-02-13 14:15
Hey @iwiznia, can you please review the proposal? Thanks!

**Comment by iwiznia** [comment] 2024-02-14 16:28
I don't think this bug is worth our time and we should close it... @isabelastisser can you provide some context into why you think fixing this is worth it?

**Closed** 2024-02-14 16:45 UTC
Labels: External, Daily, Help Wanted, Bug
