### ISSUE TITLE
[$500] Android - WS - After loading WS avatar, incorrect part of the original image is saved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37888] opened 2024-03-07 12:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4399127
**Email or phone of affected tester (no customers):** applausetester+030624dr05@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open Android App
2. Login with any account
3. Go to existing workspace or create new one
4. Go to WS Settings > Profile
5. Tap to WS avatar
6. Add image from gallery or take a picture
7. Select any part of the picture as WS avatar
8. Tap "Save"
9. Tap "View photo"

## Expected Result:
The part of the image selected during upload is saved as an avatar

## Actual Result:
After loading WS avatar, incorrect part of the original image is saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/992536e0-9031-4c7b-8454-158f74561787

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da4b171ab76cb003</li>
        <li>Upwork Job ID: 1767201754332852224</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-07 12:19
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-03-07 12:20
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by isabelastisser** [comment] 2024-03-07 21:52
Reassigning the issue, I will be OOO until Monday. Thanks!

**Comment by zanyrenney** [comment] 2024-03-11 14:47
I think this can be external. adding the labe - looks like polish for Wave-Collect.

**Comment by zanyrenney** [comment] 2024-03-11 14:50
Hey, @isabelastisser, the process is to keep yourself assigned unless OOO for long periods, right? https://stackoverflowteams.com/c/expensify/questions/8836?rq=1

**Comment by zanyrenney** [comment] 2024-03-11 14:50
reassigning to @isabelastisser who is back today.

**Comment by situchan** [comment] 2024-03-13 22:38
No proposals yet

**Comment by isabelastisser** [comment] 2024-03-18 18:30
waiting for proposals!

**Comment by Piotrfj** [comment] 2024-03-18 19:36
Hi, Im Piotr from Callstack, I will start investigating this issue

**Comment by isabelastisser** [comment] 2024-03-18 20:32
Great! Thanks, @Piotrfj !

**Comment by mvtglobally** [comment] 2024-03-20 03:42
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-03-25 16:05
@lanitochka17 @situchan @mvtglobally, can this issue still be reproduced? If not, let's close this.

**Comment by situchan** [comment] 2024-03-25 16:07
Just retested and not reproduced. Seems like fixed in any recent PR.
@isabelastisser let's close this

**Comment by isabelastisser** [comment] 2024-03-25 16:11
Thanks, @situchan ! Closing this.

**Closed by isabelastisser** 2024-03-25 16:11 UTC
Labels: External, Daily, Help Wanted, Bug
