### ISSUE TITLE
[$500] Assigning Task to myself surfaces random users in the photo/name fields

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#35013] opened 2024-01-23 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0 
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jliexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705294865729399

## Action Performed:
1. Tap on Global Create
2. Tap on `Create Task`
3. Assign Task to myself
4. Notice that my photo and name have been randomly replaced by another user's photo

## Expected Result:
I should see my own name and photo

## Actual Result:
I see John S and Cortney instead

Users affected by this include: @jliexpensify @CortneyOfstad @RachCHopkins 

## Workaround:
N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<img src="https://github.com/Expensify/App/assets/44479856/bc4409e8-11d2-4a5b-9a8a-d133dad2cf8d" width="40%">

![image](https://github.com/Expensify/App/assets/44479856/aadbaaff-1efb-49fc-a752-f6d9cd79426b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bf52b41dccdc2de</li>
        <li>Upwork Job ID: 1749927763553869824</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2024-01-23 23:00
More details and reproductions have been posted in the Slack thread here: https://expensify.slack.com/archives/C049HHMV9SM/p1705294865729399

**Comment by cjoshi-zeals** [comment] 2024-01-24 01:27
Not able to reproduce the bug i think it is working fine on main branch 
<img width="389" alt="Screenshot 2024-01-24 at 6 45 18 AM" src="https://github.com/Expensify/App/assets/91712307/c3a687c4-66e6-445a-86eb-b36bfe9b2e1a">

**Comment by jliexpensify** [comment] 2024-01-25 03:32
@cjoshi-zeals @fedirjh sorry, just to clarify: you're assigning the Task to yourselves right? Not me.

**Comment by cjoshi-zeals** [comment] 2024-01-25 03:56
@jliexpensify I am assigning the task to you, if possible can you please share the screen recording so I can reproduce and fix the bug .

**Comment by jliexpensify** [comment] 2024-01-25 04:18
@cjoshi-zeals sorry, that's not the reproduction step, I've edited this in the issue:

>1. Tap on Global Create
>2. Tap on Create Task
>3. Assign Task to myself
>4. Notice that my photo and name have been randomly replaced by another user's photo

So essentially, create a task and assign it to yourself, and check if your image has been replaced by someone else's. Thanks!

**Comment by mallenexpensify** [comment] 2024-01-27 17:10
It happened to me, reported here (only for @jliexpensify to point out I'm assigned here, ha)
https://expensify.slack.com/archives/C049HHMV9SM/p1706294243717869

Can you try versions of the below @fedirjh ? 

- In DM chat click :heavy_plus_sign: next to compose box then Assign Task
- Enter title then click Next
- Click Assignee
- See Assign to me at top with an avatar of a different user.

Feel free to test with my account too, mallen@expensify.com (which is generally not _best practice_ per CONTRIBUTING.md but it might be helpful here, espec since it's happening to me)

**Comment by mallenexpensify** [comment] 2024-01-29 16:17
Thanks @fedirjh , can you upload a custom avatar and test again?  Thx

**Comment by mallenexpensify** [comment] 2024-01-30 23:55
Still unable to reproduce so bumping to weekly and added `Needs Reproduction` label.

**Comment by mallenexpensify** [comment] 2024-01-31 23:16
Happened again
1. Went into DM 
2. Click + next to compose box
3. Assign task
4. enter title, no description, click next
5. Observe wrong avatar. 

<img width="408" alt="image" src="https://github.com/Expensify/App/assets/22508304/fdf27433-17d9-4238-a38a-e3dfccaa7b35">


That said... after being able to reproduce ~3 times, I'm unable to reproduce after that, for some reason I took other actions which then lead to my avatar showing correctly

**Comment by mallenexpensify** [comment] 2024-02-06 20:13
Was unable to reproduce today with two quick tests on my main and mallen@expensifail.com accts, .

**Comment by jliexpensify** [comment] 2024-02-07 01:58
Also unable to repro - we could probably close this right @mallenexpensify ?

**Comment by mallenexpensify** [comment] 2024-02-07 16:40
It's happened to me multiple times, inc. last week, so I 'd like to keep this open for a lil while longer.

**Comment by mvtglobally** [comment] 2024-02-13 04:51
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-02-13 23:13
Having trouble updating desktop app to try to reproduce, posted about in #expensify-bugs trying to fix.

**Comment by mallenexpensify** [comment] 2024-02-20 19:14
Unable to repro the past weekish, tried multiple times, so closing

**Comment by m-natarajan** [comment] 2024-04-02 19:59
Reopening this issue as @puneetlath also experiencing this [issue](https://expensify.slack.com/archives/C049HHMV9SM/p1712007497407409)

**Comment by mallenexpensify** [comment] 2024-04-03 00:40
Thanks @m-natarajan , checking with Puneet in [the slack thread ](https://expensify.slack.com/archives/C049HHMV9SM/p1712104786768439?thread_ts=1712007497.407409&cid=C049HHMV9SM)on repro steps, I wan't able to

**Comment by mallenexpensify** [comment] 2024-04-10 01:42
Added `retest-weekly` to see if QA is able to reproduce

**Comment by mallenexpensify** [comment] 2024-04-17 02:41
Waiting on retest, leaving daily cuz this is a weird one

**Comment by mvtglobally** [comment] 2024-04-18 16:05
Issue not reproducible during KI retests. (Second week)

**Comment by mallenexpensify** [comment] 2024-04-18 22:09
This one might take a lil while.

**Comment by mvtglobally** [comment] 2024-04-29 03:13
Issue not reproducible during KI retests. (Third week)

**Comment by mallenexpensify** [comment] 2024-05-01 00:06
Also unable to repro on web and desktop. 
@jliexpensify can you see if you can reproduce? Thx

**Comment by jliexpensify** [comment] 2024-05-01 00:23
@mallenexpensify nope, I can't repro either. This is a super weird issue and it seems to occur very randomly. I guess we can close this, it's looking stable now!

**Comment by mallenexpensify** [comment] 2024-05-03 01:17
Let's def reopen if it happens again.  We can throw $125 on it to document reproducible steps.

**Closed by mallenexpensify** 2024-05-03 01:17 UTC
Labels: Engineering, Weekly, Internal, Needs Reproduction, Bug, retest-weekly
