### ISSUE TITLE
[$1000] Web - Thread - Thread chat is not seen in LHN for other user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20135] opened 2023-06-03 23:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to A and send a message to B
2. Send a message in the thread from A
3. Log in to B

## Expected Result:
Both thread and parental chats should be seen in LHN

## Actual Result:
Thread chat is missing in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/f5c5a3ea-c77d-4192-885a-18843504cffe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192dbb9f218a37a75</li>
        <li>Upwork Job ID: 1665659900121341952</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-06-07 08:54
Please allow me a day to review. I am unwell and would be offline most of the day.

**Comment by laurenreidexpensify** [comment] 2023-06-07 11:32
@kevinksullivan  I am going OOO til 19 June so adding you as a buddy to watch over this while I am out. Thanks!

**Comment by mananjadhav** [comment] 2023-06-08 18:01
@thienlnam are we looking to solve the group messages also in this issue? I think we would have multiple scenarios to consider when we look at groups and mentions. 


Both the proposals have the correct RCA, 
@tienifr’s proposal covers both the aspects and @c3024’s proposal solves the current issue.  I think we should focus on resolving the DMs here and discuss further on how do we want to treat group messages and mentions. Hence I think @c3024’s proposal is good to work with. 

@thienlnam what do you think ?

**Comment by thienlnam** [comment] 2023-06-08 18:50
Does the thread chat show in the LHN for the other user once they open the thread?

Otherwise this is working as intended, you only 'join' a report once you click to open the thread. Otherwise any thread in the report would just show up in your LHN which is not ideal

**Comment by thienlnam** [comment] 2023-06-09 16:15
> Message in DM
a. In this case I think B should see all threads when either A or B open a thread.
Message in groups
a. B sends the parent report action, someone replies to it in a thread: B should see the thread
b. A mentions B in a report action, and someone replies to the report action in a thread: B should see the thread
c. B is not involved at all in the parent report action: B should not see the thread, otherwise everyone in the group will be flooded with threads from other people.


Yeah this seems correct - basically you should see the thread if you are a participant in that thread (created the reportAction or are mentioned), or by commenting in the reportAction

**Comment by thienlnam** [comment] 2023-06-09 16:23
So I believe this is expected functionality, but to double check I asked here https://expensify.slack.com/archives/C01GTK53T8Q/p1686327720959599

**Comment by thienlnam** [comment] 2023-06-09 18:10
Okay confirmed this is expected - closing

**Closed by thienlnam** 2023-06-09 18:10 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by thienlnam** [comment] 2023-06-12 16:21
Let's report it separately, this bug report is focused on the DM case
