### ISSUE TITLE
"free trial ended" is missing from the report after running the given commands

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45516] opened 2024-07-16 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating https://github.com/Expensify/App/pull/44483
**Version Number:**  9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** unable to run the scripts
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/

2. Log in with a new Gmail account
3. Open Chrome console
4. Paste and run "Onyx.log("session")"
5. From the LHN, open Expensify if "accountID" in the console ends with an odd number. Open Concierge if it ends with an even number
6. Run all three of the attached codes from https://github.com/Expensify/App/pull/44483
QA step 4 in Chrome console
7. Refresh the page

## Expected Result:
"free trial ended" message and "Add payment card" button should be available.

## Actual Result:
"free trial ended" message and "Add payment card" button are missing from the report after running the given commands.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/a19f6733-1c2f-4cd3-b516-6c5291bf288a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by chiragsalian** [comment] 2024-07-16 21:17
Not a blocker, its a new feature that we'll test shortly. Removing blocker label and closing issue.

**Comment by aldo-expensify** [comment] 2024-07-16 22:26
Thanks @chiragsalian

**Comment by lanitochka17** [comment] 2024-08-27 12:21
Issue is still reproducible

TC https://expensify.testrail.io/index.php?/tests/view/4893792

https://github.com/user-attachments/assets/daac08b6-1a77-40c0-9f07-48f216a017bc

**Comment by jliexpensify** [comment] 2024-08-28 00:46
@chiragsalian does this need to be re-opened?

**Comment by chiragsalian** [comment] 2024-08-28 00:54
Nope, it doesn't need to be reopened. Looking at the video and issue again there are few things wrong.
Testing to receiving a free trial end message is a bit more complicated and not something easy for QA to test.
Just setting the onyx lastDayFreeTrial won't suffice.

The steps would be more like,
1. Ask ring1 to run a custom query to expire this NVP for the user in the database.
2. Find the bedrock job `SendFreeTrialEndMessage` for the user and retry it to run now. This job once run will send the message to the user.

Is this part of the scripts? Can someone share it with me so i can go over it and correct it as necessary.

**Comment by jliexpensify** [comment] 2024-08-28 03:47
Sorry @chiragsalian I have no idea about any of this...I got assigned as Bug 0. I can assign `Ring 1` if you like?

**Comment by chiragsalian** [comment] 2024-08-28 18:59
Reassignment is not needed, i can help out here. Sorry i just noticed this is marked as hourly. It doesn't need to be. Demoting to weekly.

**Comment by chiragsalian** [comment] 2024-08-28 19:00
For now lets wait for @lanitochka17 to reply to my post [here](https://github.com/Expensify/App/issues/45516#issuecomment-2313876591) and then we'll take it from there.

I feel like nothing needs be actioned here and we can just close this out since we've already tested it internally. But lets wait to confirm what QA says.

**Comment by jliexpensify** [comment] 2024-09-03 22:55
Bump @lanitochka17 !

**Comment by jliexpensify** [comment] 2024-09-06 03:48
@chiragsalian can we close this one?

**Comment by chiragsalian** [comment] 2024-09-09 18:01
Yup lets close this out. @lanitochka17, if there is anything pending from our end or you have additional questions for us then feel free to reopen this issue.

**Closed by chiragsalian** 2024-09-09 18:01 UTC
Labels: Engineering, Weekly, Bug
