### ISSUE TITLE
[$250] Search - No delete or hold option for expense while offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46890] opened 2024-08-06 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/46128
## Action Performed:
Break down in numbered steps

## Expected Result:
Describe what you think should've happened

## Actual Result:
Describe what actually happened

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/2a26d15a-3833-4e60-832e-8fbb4bafd9b9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bae1b9190f8db09f</li>
        <li>Upwork Job ID: 1821707990411207161</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by FitseTLT** [comment] 2024-08-06 14:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No delete or hold option for expense while offline

### What is the root cause of that problem?
We are displaying them with the condition not offline
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/components/Search/SearchPageHeader.tsx#L188-L189
https://github.com/Expensify/App/blob/0e46257f3295243e5ef306b723288cb1673ed6f1/src/components/Search/SearchPageHeader.tsx#L166-L167
### What changes do you think we should make in order to solve the problem?

We need to remove !isOffline from the conditions
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-06 14:18
[Updated](https://github.com/Expensify/App/issues/46890#issuecomment-2271405391) to add the changes to be made on the `onSelected` callbacks

**Comment by trjExpensify** [comment] 2024-08-09 01:03
I think we might not allow these actions on the Search page offline for the time being. CC: @luacmartins for a second opinion.

**Comment by luacmartins** [comment] 2024-08-09 08:05
Correct, this is expected since Search actions can only be taken online.

**Comment by trjExpensify** [comment] 2024-08-09 16:33
Cool, closing!

**Closed by trjExpensify** 2024-08-09 16:33 UTC
Labels: External, Daily, Help Wanted, Bug
