### ISSUE TITLE
[HOLD for payment 2023-06-19] [$1000] Assigning an unassigned chat to someone in the DM will re-create the task

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#19126] opened 2023-05-17 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Will need a front-end and back-end fix

## Action Performed:
1. Create an unassigned task in the DM
2. In the task, assign the other person in the DM to it
3. Go back to the DM

## Expected Result:
4. You should only see the original task because it is being assigned to the user in the parent reportID

## Actual Result:
5. You see a duplicate task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c381e7748b2b20a2</li>
        <li>Upwork Job ID: 1658877887639298048</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-05-19 00:15
The back-end PR will disable this functionality so that it's not possible but we still need to disable this on the front-end as well. 

We're still optimistically storing that a reportAction in onyx even if we're reassigning the chat to someone in the DM. What we need to do here is just add a check [here](https://github.com/Expensify/App/blob/3559764900377c21d343c0498d2f901ab50ba2d4/src/libs/actions/Task.js#L294-L294) to check that we're not assigning it to the person from the DM

**Comment by tienifr** [comment] 2023-05-19 11:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
See a duplicate DM when creating a task in the DM without assignee, then assign to the other user in the DM.

### What is the root cause of that problem?
As correctly suggested by @thienlnam, in here https://github.com/Expensify/App/blob/40d992f6d6145ff3fdd6049b3dc31dc252cf0f82/src/libs/actions/Task.js#L294-L294 we're adding a comment to the assignee chat whenever we change the assignee.

### What changes do you think we should make in order to solve the problem?

In here https://github.com/Expensify/App/blob/40d992f6d6145ff3fdd6049b3dc31dc252cf0f82/src/libs/actions/Task.js#L294-L294, we need to check the reportActions of the report with `assigneeChatReportID`, if there's any reportAction that is the task comment (we can check the reportAction that has `childReportID` equals to the `taskReportID`). If yes then we'll not post another comment to the DM.  

### What alternative solutions did you explore? (Optional)
If we only want to avoid resending the task comment if the most recent reportAction is the task comment (to avoid duplicate), we can also do that by modifying the above condition a bit.

**Comment by amyevans** [comment] 2023-05-19 20:39
> Do we mean that I see two actions here?

Yes exactly, the issue is that there are duplicate _tasks_, not duplicate _DMs_. I updated the OP to reflect that.

**Comment by thienlnam** [comment] 2023-05-19 21:22
Yup! And to add to that - the task isn't actually duplicated (it will still link to the original task), but it's showing an additional task preview

**Comment by tienifr** [comment] 2023-05-23 04:33
@parasharrajat  There's a few scenarios here:
1. User A created task 1, share to the DM with user B, but doesn't assign anyone. Then user A assigns to user B.
2. User A created task 1, share to the DM with user B, assign user B initially. Then user A reassigns to user C.

> we can check if the parent report is not DM because if a Task was created in DM then it is already posted on the DM as Created

If we do this, in scenario 2, user C will not receive any assignment report action, because the parent report is indeed the DM between user A and user B.

**Comment by tienifr** [comment] 2023-05-23 04:56
> @tienifr I didn't understand your proposal completely. You haven't explained the complete root cause as well.

@parasharrajat sorry for the confusion, I updated the root cause a bit, hope it's clearer now.

**Comment by thienlnam** [comment] 2023-05-23 18:20
> If we do this, in scenario 2, user C will not receive any assignment report action, because the parent report is indeed the DM between user A and user B.

I am not following this - I would expect in scenario 2 that user C WILL receive the assignment reportAction because the parent report is the NOT the DM between user A and C

**Comment by tienifr** [comment] 2023-05-24 03:56
@thienlnam yes I'd expect that as well, I'm just highlighting a scenario in which @parasharrajat 's suggestion might not work, while [checking the reportAction](https://github.com/Expensify/App/issues/19126#issuecomment-1554461516) will work

> Instead of checking if a reportAction exists, we can check if the parent report is not DM because if a Task was created in DM then it is already posted on the DM as Created

**Comment by tienifr** [comment] 2023-05-24 12:14
> If we only want to avoid resending the task comment if the most recent reportAction is the task comment (to avoid duplicate), we can also do that by modifying the above condition a bit.

@parasharrajat @thienlnam we can consider this as well, since if the task report action for "Assigned a task to you:" was from a long time ago, I think it's ok to see a new "Assigned a task to you:" comment when the user is reassigned to the task, so that they know.

**Comment by thienlnam** [comment] 2023-05-24 17:27
@tienifr Yeah, I'm noting that this scenario should work even if we check that the parent report is not the same report as the DM

https://github.com/Expensify/App/issues/19126#issuecomment-1559931181

**Comment by thienlnam** [comment] 2023-05-24 17:34
I don't think we should traverse reportActions to check this - in the back-end we're just doing the same check that the parent report is not the same report as the DM and so we can do it again here.

Like you mention, the only thing is the situation where - you create a task not in the DM, assign someone, change the assignee, and then re-assign it to the same person.  That person will still get two reportActions in the DM which is fine because in a real use case, someone might be OOO and need to be re-assigned in which case they would get the latest notification that they were assigned to a task

**Comment by MitchExpensify** [comment] 2023-05-25 21:00
Invite sent in Upwork for eventual C+ payment 👍

**Comment by amyevans** [comment] 2023-05-25 23:25
Heads up, I'll be OOO tomorrow and Monday.

**Comment by MitchExpensify** [comment] 2023-05-29 21:20
@parasharrajat what are your thoughts on @tienifr's [proposal here](https://github.com/Expensify/App/issues/19126#issuecomment-1562422689)?

**Comment by amyevans** [comment] 2023-06-01 19:15
Looks good to me, let's go for it @tienifr

**Comment by MitchExpensify** [comment] 2023-06-09 11:13
Hows the testing going @parasharrajat ?

**Comment by MitchExpensify** [comment] 2023-06-13 20:08
Payment reminder set in my cal 👍

**Comment by MitchExpensify** [comment] 2023-06-19 16:49
Bump on [the final steps](https://github.com/Expensify/App/issues/19126#issuecomment-1588264116) @parasharrajat 👍

**Comment by MitchExpensify** [comment] 2023-06-19 16:54
C+ & C have been paid. Just waiting on [these](https://github.com/Expensify/App/issues/19126#issuecomment-1588264116)  steps to close this out 👍

**Comment by MitchExpensify** [comment] 2023-06-19 22:45
Thanks @parasharrajat !

**Comment by amyevans** [comment] 2023-06-21 20:12
@MitchExpensify are we all set to close this GH?

**Comment by MitchExpensify** [comment] 2023-06-22 01:11
Yes!

**Closed by MitchExpensify** 2023-06-22 01:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
