### ISSUE TITLE
Task – Hidden appears as task assignee for user B when user A create a task without assignee

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43833] opened 2024-06-17 14:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.84-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4639594
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Log in as user A
3. Open group chat with user B
4. Click on + and create a task without assignee
5. Log in as user B (relogin if you are login already)
6. Open group chat from step 3 and find the task from step 4

## Expected Result:
Task without assignee is present in group chat after relogin

## Actual Result:
Hidden appears as task assignee for user B in group chat after relogin when user A create a task without assignee. When open task details assignee is not selected. The same for task in room.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/841284ca-b04c-48e4-b0fa-f60a6987c2b5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e57b014edbaa898b</li>
        <li>Upwork Job ID: 1802723824654043156</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by kavimuru** [comment] 2024-06-17 14:14
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-06-17 14:14
We think this bug might be related to #vip-vsb

**Comment by grgia** [comment] 2024-06-17 15:19
What's the expected result here? @kavimuru

**Comment by grgia** [comment] 2024-06-17 15:23
regardless, I don't think should be a deploy blocker. Demoting

**Comment by grgia** [comment] 2024-06-17 15:24
Making external for now, but looks like there's a chance it could be an internal issue

**Comment by nkdengineer** [comment] 2024-06-18 04:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hidden appears as task assignee for user B in group chat after relogin when user A create a task without assignee. When open task details assignee is not selected. The same for task in room.

### What is the root cause of that problem?
When user B login or user A re-login, the `taskReport.managerID` and `action?.childManagerAccountID` are `undefined` so `taskAssigneeAccountID` fallbacks to `-1` and then `Hidden` appears. In the past, we fallback the `taskAssigneeAccountID ` as an empty string, and when user A creates the task the optimistic `assignAccountID` is `0`  so this bug doesn't happen.

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/components/ReportActionItem/TaskPreview.tsx#L75-L77

### What changes do you think we should make in order to solve the problem?
Remove the fallback `-1` here so we will not show the task assignee if it doesn't exist

```
const taskAssigneeAccountID = Task.getTaskAssigneeAccountID(taskReport) ?? action?.childManagerAccountID;

```

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/components/ReportActionItem/TaskPreview.tsx#L75

OPTIONAL: We can also set the default value of `assigneeAccountID` here as `undefined` to be consistent with back-end

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/libs/actions/Task.ts#L119
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-06-18 04:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hidden appears as task assignee for user B in group chat after relogin when user A create a task without assignee. When open task details assignee is not selected. The same for task in room.

### What is the root cause of that problem?
When user B login or user A re-login, the `taskReport.managerID` and `action?.childManagerAccountID` are `undefined` so `taskAssigneeAccountID` fallbacks to `-1` and then `Hidden` appears. In the past, we fallback the `taskAssigneeAccountID ` as an empty string, and when user A creates the task the optimistic `assignAccountID` is `0`  so this bug doesn't happen.

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/components/ReportActionItem/TaskPreview.tsx#L75-L77

### What changes do you think we should make in order to solve the problem?
Remove the fallback `-1` here so we will not show the task assignee if it doesn't exist

```
const taskAssigneeAccountID = Task.getTaskAssigneeAccountID(taskReport) ?? action?.childManagerAccountID;
const htmlForTaskPreview =
    taskAssigneeAccountID ? `<comment><mention-user accountid="${taskAssigneeAccountID}"></mention-user> ${taskTitle}</comment>` : `<comment>${taskTitle}</comment>`;
```

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/components/ReportActionItem/TaskPreview.tsx#L75

Or we can update this condition to not show the task assign if `taskAssigneeAccountID` is `-1` or `0`


```
const taskAssigneeAccountID = Task.getTaskAssigneeAccountID(taskReport) ?? action?.childManagerAccountID ?? -1;
taskAssigneeAccountID !== 0 && taskAssigneeAccountID !== '-1'  ? `<comment><mention-user accountid="${taskAssigneeAccountID}"></mention-user> ${taskTitle}</comment>` : `<comment>${taskTitle}</comment>`;

```

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/components/ReportActionItem/TaskPreview.tsx#L75-77


OPTIONAL: We can also set the default value of `assigneeAccountID` here as `undefined` to be consistent with back-end

https://github.com/Expensify/App/blob/b33542383ac2cb8ea1e922aa12dd2265efccd0ab/src/libs/actions/Task.ts#L119
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-06-18 05:36
This is going to be fixed in https://github.com/Expensify/App/pull/43646

**Comment by grgia** [comment] 2024-06-18 11:14
@bernhardoj in that case, can you please add these steps to the test steps/QA steps for your PR https://github.com/Expensify/App/pull/43646

**Comment by bernhardoj** [comment] 2024-06-19 03:42
PR is merged, I think we can ask QA to retest this issue.

**Comment by grgia** [comment] 2024-06-21 10:52
@kavimuru could you please retest this on staging?

**Comment by kavimuru** [comment] 2024-06-21 13:41
@grgia Retested and not able to reproduce by the tester.


https://github.com/Expensify/App/assets/43996225/b2f11218-ab92-40ae-a107-1093a580f748

**Comment by grgia** [comment] 2024-06-21 15:36
Thank you @kavimuru , closing!

**Closed by grgia** 2024-06-21 15:36 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
