### ISSUE TITLE
[$500] Workspace - Renaming workspaces does not get reflected dynamically on employee side

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38847] opened 2024-03-22 22:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: Account A and account B should have prior interaction in a DM
1. As account A create a workspace and invite account B as a member
2. On account B open the workspace picker LHP
3. On account A rename the workspace created on step 1 and observe the change on account B

## Expected Result:
Workspace name should dynamically update to the newly changed name (Prod behavior)

## Actual Result:
Workspace name does not dynamically get updated unless user manually opens the workspace or refreshes the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c4625a8d-6845-4b22-b77b-856dd12319be

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcf21b188aeee4d2</li>
        <li>Upwork Job ID: 1772897808904761344</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-22 22:33
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-22 22:34
We think that this bug might be related to #wave-collect - Release 1

**Comment by miljakljajic** [comment] 2024-03-27 08:06
Thank you - I think this can be handled externally! Added to Collect

**Comment by mmmbytes** [comment] 2024-03-29 06:08
I tested this with macOS Ventura 13.5.1 on both Chrome and Safari. I was not able to reproduce the bug. The workspace name updates dynamically, although it does have some latency. I'd be happy to help with reducing the latency. Just let me know if you'd like me to look into it. 

Are there any other conditions for reproducing the bug, or could it be that it's already fixed?

**Comment by mmmbytes** [comment] 2024-03-29 06:13
Contributor details
Your Expensify account email: mia.marleni.tapia@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012a9a83e40177579f

**Comment by mollfpr** [comment] 2024-03-29 07:43
I can't reproduce the issue on DEV, staging, or production.

https://github.com/Expensify/App/assets/25520267/960e8eef-08ff-439b-9c9d-5f0236de467c

**Comment by mollfpr** [comment] 2024-04-01 19:30
@miljakljajic Could you help confirm if the issue is not reproducible?

**Comment by miljakljajic** [comment] 2024-04-15 11:32
asked for re-testing, will bump here

**Comment by kavimuru** [comment] 2024-04-15 13:09
@miljakljajic issue is still reproducible. 

https://github.com/Expensify/App/assets/43996225/8264fa83-e5b0-4516-8f84-c07fd16f8ca6

**Comment by trjExpensify** [comment] 2024-04-16 12:46
@miljakljajic as a bug that doesn't block the release, I'm moving this into `Polish` on the project board.

**Comment by mollfpr** [comment] 2024-04-16 19:28
I can't reproduce the issue in the latest `main`.



https://github.com/Expensify/App/assets/25520267/20a9afb5-1597-4f5c-a694-bb381cf232e8

**Comment by miljakljajic** [comment] 2024-04-23 14:17
This is pretty low priority and given that it's not being reproduced reliably, shall we close?

**Closed** 2024-04-30 12:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
