### ISSUE TITLE
[HOLD for payment 2024-08-09] [HybridApp] - Redirected Hybrid app users missing Push Notifications

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42379] opened 2024-05-20 09:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @muttmuure 
**Slack conversation:** https://expensify.enterprise.slack.com/archives/C05LX9D6E07/p1715102667514389

## Action Performed:
Break down in numbered steps

- Create a new public domain account
    - or apply the ClassicRedirect NVP to your account in Expensify Classic
- Sign into the Hybrid app, you should see the NewDot experience 
- Enable notifications for under OS app settings
- From a different account, Send a message to yourself
- Kill the app
- From a different account, Send a message to yourself

## Expected Result:
- You should receive a push notificaion

## Actual Result:
- You do not receive a notification

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

None

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b96cd2222bc21292</li>
        <li>Upwork Job ID: 1792637809065209856</li>
        <li>Last Price Increase: 2024-05-27</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad / @bfitzexpensify</details>

**Comment by CortneyOfstad** [comment] 2024-05-20 19:25
Was able to recreate so going to get eyes on this!

**Comment by drantis** [comment] 2024-05-20 22:47
Cannot view logs. SSO required

**Comment by Julesssss** [comment] 2024-05-21 10:42
Unable to reproduce: 

![IMG_4DFA58EED59F-1](https://github.com/Expensify/App/assets/10736861/b48b0886-54d4-44a3-a245-ff03e6d93f09)
![IMG_AC08FC6D2D0D-1](https://github.com/Expensify/App/assets/10736861/078d00dc-7786-4614-a88e-3a249537d443)

**Comment by Julesssss** [comment] 2024-05-21 10:43
The OS only lets a certain amount of push notifications to reach the app and this depends on many things like Battery, Amount of push notifications we have recently sent, ect

**Comment by CortneyOfstad** [comment] 2024-05-22 19:30
Was not able to reproduce (details [here](https://expensify.slack.com/archives/C05LX9D6E07/p1716406147893489?thread_ts=1715102667.514389&cid=C05LX9D6E07))

**Comment by CortneyOfstad** [comment] 2024-05-23 14:27
Talking to @Julesssss and @muttmuure in Slack, I'm going to need to create a new Expensify account under a public domain email. Testing this now 👍

**Comment by CortneyOfstad** [comment] 2024-05-23 15:01
Alright I was able to recreate! I ran the snippet for [cort2007@gmail.com](mailto:cort2007@gmail.com) and signed in via the mobile app. Enabled notifications, quit the app.
From [cortney@expensify.com](mailto:cortney@expensify.com), I attempted to send a test message and it never notified me on iOS
![IMG_0868](https://github.com/Expensify/App/assets/10926327/e7d8ab3d-8027-4230-bb7f-2414fa72e652)

**Comment by sobitneupane** [comment] 2024-05-24 04:09
Unable to reproduce on latest staging:

<img src="https://github.com/Expensify/App/assets/25876548/4dbf341f-eb61-4e0c-8cb8-e1d56bf9eada" width="140"/>

**Comment by muttmuure** [comment] 2024-05-27 20:39
The reproduction steps here are to dismiss the redirect (using Switch to Expensify Classic) and then you don't receive notifications anymore.

**Comment by muttmuure** [comment] 2024-05-27 20:41
So sign up on a public domain which will set the redirect, then navigate back to Classic. This disables notifications for you on the back end and you no longer receive them

**Comment by sobitneupane** [comment] 2024-05-28 09:43
@Julesssss are we expecting proposals on this, or will you be working on the fix?

**Comment by Julesssss** [comment] 2024-05-28 09:54
Hey @sobitneupane, I'm pretty sure this is a backend issue. So you can unassign and unsubscribe

**Comment by Julesssss** [comment] 2024-05-31 10:41
I'm finding it hard to verify currently. I see no difference in NVPs between users. I believe re-authenticating could work, but I'd like to confirm Matt and Cortney's NVP data before we confirm that fix.

- The Airship push notificationID is set to the users accountID
- On App sign-in, we enable/disable push notifications depending on the `notificationID` being present in Onyx
- NVP is set from Web-E when [we redirect](https://github.com/Expensify/Web-Expensify/blob/149e1bb559cab826de1a786c1a2f3539143071bb/lib/UserAPI.php#L3314-L3316)

_____________

It looks like the NVP data is identical for both 'unsubscribed' users and regular users:

**Unsbscribed**
```
"private_pushNotificationID": "ptetgDGrF0KHB2ev",

"pushNotificationsEnabled": {
        "iPhone8,4_C5A88FFA-C9E0-4D6C-8969-96DABCA6D1CE": [
            {
                "isEnabled": true,
                "timestamp": "2024-05-31 10:24:25"
            }
        ]
    },

**Subscribed**
// ID
"private_pushNotificationID": "cKWxpD68HHuwAtHx",

"EnablePushNotifications": { // This doesn't seem to be used anywhere...
            "completed": {
                "data": {
                    "value": "allow"
                },
                "time": 1638377726
            },
            "dismissed": {
                "data": [],
                "time": 1701962990
            }
        },

"pushNotificationsEnabled": {
        "bluejay002ce64b-2937-13c3-6a13-a80b5c37ef1f": [
            {
                "isEnabled": true,
                "timestamp": "2023-03-16 10:30:51"
            }
        ],
        ...

**Comment by CortneyOfstad** [comment] 2024-06-03 14:29
Not overdue!

**Comment by Julesssss** [comment] 2024-06-03 15:30
Busy with other chores today. Will carry on when I'm back on Wednesday

**Comment by Julesssss** [comment] 2024-06-05 15:42
I'm still working on chores, reviews, ect and didn't have time to pickup today. I'll have time for this tomorrow.

**Comment by mvtglobally** [comment] 2024-06-05 21:15
Issue not reproducible during KI retests. (First week)

**Comment by Julesssss** [comment] 2024-06-07 13:34
I can now reproduce on Android too. This only works for hybrid app. Signing into `expensify.com` and being redirected doesn't work as far as I can tell, I see the same log that Matt reported [here](https://expensify.slack.com/archives/C05LX9D6E07/p1715102667514389): 

```
[App] 2024-06-07T13:24:01.533Z - [info] [PushNotification] Unsubscribing from push notifications. ~~ parameters: '' userAgent: 'okhttp/4.9.2'
```

**Comment by muttmuure** [comment] 2024-06-07 15:42
👍

**Comment by CortneyOfstad** [comment] 2024-06-10 15:13
Not overdue!

**Comment by Julesssss** [comment] 2024-06-10 15:45
The `UserAPI::createTemporaryLogin` function attempts to retrieve the `private_pushNotificationID` NVP, [here](https://github.com/Expensify/Web-Expensify/blob/149e1bb559cab826de1a786c1a2f3539143071bb/lib/UserAPI.php#L3276). But this is being retrieved as `null` or `''`. This seems to be reproducible 100% of the time in prod.

But reproducing locally is tricky because the unsubscription only occurs on mobile. When debugging web I do in fact see the NVP being set 😕

- A recent change wraps the fault NVP retrieval behind an `isValidatedUser` [condition](https://github.com/Expensify/Web-Expensify/blob/ab659d3b2757753a0cf3860e5e9a1f9351897487/lib/UserAPI.php#L2992-L2997), so I need to figure out how this will continue to be testable
- Could this be due to SSO auth options?.. I need to verify that the bug occurs for the SSO, but first I need apply [this](https://stackoverflowteams.com/c/expensify/q/18777/297) local configuration

**Comment by Julesssss** [comment] 2024-06-12 12:54
Once again I have been pulled away to finish some other things. And new instances of a previous fire... 

For now, I think the eventual solutions will be:
- A) Register for push notifications on app start instead of sign in/out. This is not dangerous and will allow past and future users to have the issue auto-resolved on the next app open
- B) Figure out why the NVP is not being retrieved within `createTemporaryLogin` (secondary improvement)

**Comment by Julesssss** [comment] 2024-06-13 14:49
I continued investigating today. A lot of my time is being spent building the Hybrid app locally for debugging... 

[Here](https://github.com/Expensify/App/blob/f6de195ffee0c145926dfe529d2fa819dafb346e/src/libs/Notification/PushNotification/subscribePushNotification/index.ts#L120) is the specific line of code causes us to de-register from Airship. I don't yet know why, but the app behaves differently when being run within hybrid app: 
- **NewDot app:** `nvp_private_pushNotificationID` exists, so we register for push notifications
- **Hybrid app:** `nvp_private_pushNotificationID` is null, so we deregister for push notifications 

I think this is because a a unique flow is used for the Hybrid app flow, where the user's accountID is returned (via `createTemporaryLogin`). This function [gets the users accountID](https://github.com/Expensify/Web-Expensify/blob/b517ce01f9478979299209e1ab5d9a3e428843db/lib/UserAPI.php#L3962) and returns it as Onyx data. Perhaps this is called too early for it to work within Hybrid app...

**Next steps:** 
- Hardcode the accountID to empty and see if this reproduces the issue in NewDot
- Debug Web-E and monitor the onyx data -- compare NewDot to Hybrid app if possible  
- Try and mount PushNotifications on app open
- Share ideas in Slack and see if anyone else has a suggestion

**Comment by Julesssss** [comment] 2024-06-13 15:32
I think Mariusz will eventually hit this issue when resolving Hybrid notifications as **this** problem seems to be that we deregister from Airship due to the missing Onyx data.

My best guess so far is that the mounting of `PushNotification` is happening too early, or in the wrong order when NewDot is running within Hybrid. 

I'll remain subscribed.

**Comment by AndrewGable** [comment] 2024-06-13 15:43
cc @staszekscp

**Comment by staszekscp** [comment] 2024-06-14 13:10
I had a bit of time to have a look at the issue 🙂  If the issue is indeed related to calling `PushNotification.deregister()` I think the key would be to change the callback for `ONYXKEYS.NVP_PRIVATE_PUSH_NOTIFICATION_ID` key. Currently we register to push notifications, even though we do it already by calling `registerOnStartup` on the native OldDot side - therefore the user is already registered whenever we enter NewDot. 

It means that theoretically we could skip registration/deregistration of PushNotifications on NewDot side. Especially if we're [not going to let users to logout on NewDot](https://github.com/Expensify/App/issues/43336). It would require some testing, but after some testing it seems that it would work.

FYI: I'm going to be out of office for the next two weeks, but I hope that it'll help you debug this issue 😄

**Comment by CortneyOfstad** [comment] 2024-06-19 13:30
@Julesssss any update? Last one I can see is from Slack [here](https://expensify.slack.com/archives/C05LX9D6E07/p1718197808616079?thread_ts=1715102667.514389&cid=C05LX9D6E07) — thanks!

**Comment by Julesssss** [comment] 2024-06-19 13:55
Hey @CortneyOfstad, this is held on wider Hybrid notification changes. Which I believe will be investigated by @staszekscp when he is back.

@AndrewGable I looked for a Hybrid notification issues in the board and tracker but can't see anything. Are we missing a wider issue for this?

**Comment by CortneyOfstad** [comment] 2024-06-25 14:04
Thanks @Julesssss!

@staszekscp — if you have any questions, or need anything — just let me know!

**Comment by Julesssss** [comment] 2024-07-02 15:48
Today I re-verified that unsubscription is occuring only for Hybrid app redirection. During today's testing it wasn't consistently null though 😕 

![Screenshot 2024-07-02 at 15 09 45](https://github.com/Expensify/App/assets/10736861/fcad9708-98bd-4731-a3a9-5231a1af068b)
![Screenshot 2024-07-02 at 15 36 53](https://github.com/Expensify/App/assets/10736861/dd10a5d8-88f9-4f9a-b315-6aea1ccfdce5)

Testing this is difficult for a variety of reasons, so before I can try Mariusz's suggestion, I have to set up my environment so that push notifications are received on a release build when Airship registration does take place. This requires release signed builds which I have been configuring today. I'm off tomorrow and will continue on Thursday.

**Comment by CortneyOfstad** [comment] 2024-07-03 14:32
Sounds good @Julesssss! I am off until Tuesday, but if anything pops up in the meantime, feel free to just reapply the **bug** label so nothing is delayed. Thank you!

**Comment by Julesssss** [comment] 2024-07-04 13:54
Currently I am still trying to generate a build in which regular push notifications are received from Airship. One thing to note is that my issues may be due to this recent Firebase [configuration change](https://docs.airship.com/platform/mobile/setup/configure-channels/#android-channel-configuration): 

<img width="489" alt="Screenshot 2024-07-04 at 14 52 48" src="https://github.com/Expensify/App/assets/10736861/7ed8493c-7465-42b5-a2f6-5abebb51b30f">

**Comment by Julesssss** [comment] 2024-07-04 14:44
I think the final blocker for my notification testing is that we currently hardcode accounts to enable NewDot > Hybrid notification routing. I am working on this task[ here](https://github.com/Expensify/App/issues/44839).

**Comment by Julesssss** [comment] 2024-07-08 09:18
The [PR](https://github.com/Expensify/Web-Expensify/pull/42622) enabling me to test Hybrid notifications is merged and awaiting deployment. I can restart on this in probably 2 days when the Beta is on production.

**Comment by Julesssss** [comment] 2024-07-10 15:34
- Moved SWM test accounts over to the Hybrid beta that replaced hardcoded code, to close the issue
- Further Hybrid prod notifications testing:
     - Non-concierge notifications don't appear to be working... 😕 
     - Verify local prod build notifications work ✅ 
- Test out changes where we don't make NewDot Airship registration 
    - Do OldDot notifications work when switching experiences?
    - Do NewDot notifications work when switching experiences?

**Comment by Julesssss** [comment] 2024-07-10 15:43
**Testing Results:**

- [x] Notifications received when user lands in OldApp experience
- [x] Notifications received when user switches into NewDot experience
- [x] Notifications received when user switches back to OldDot experience
- [ ] Notifications NOT received when user closes app, then opens and lands in NewDot experience

Also, they seem to not be sent when the users interacts with Concierge in NewDot...

**Comment by Julesssss** [comment] 2024-07-16 09:58
Hey @staszekscp. Could you help us by taking over the front end changes here?

I think your earlier suggestion to strip out the duplicate Airship registration in the NewDot experience is the best path forward here. [Here](https://github.com/Expensify/App/issues/42379#issuecomment-2220869108) is what I found during my testing -- the main problem is determining whether to register with Airship when NewDot app opens (different for Hybrid / NewDot)

I believe we'll need to do something like this on the front-end: 
- In NewDot standalone app, continue to register Airship
- In Hybrid, stop Airship registration in Hybrid NewDot experience
    - This is tricky as we'd need a flag to determine whether Airship registration should take place, but we might be able to use the value of the TryNewDot classicRedirect NVP?
    - An alternative might be to detect redirection from the Hyrbid NewDot experience

**Comment by staszekscp** [comment] 2024-07-17 11:52
Hey @Julesssss! Thanks for sharing the findings! Currently we use a check for existance of `HybridAppModule` whenever we execute some HybridApp-specific code. Have you considered that solution?

**Comment by Julesssss** [comment] 2024-07-17 14:49
> Thanks for sharing the findings! Currently we use a check for existance of HybridAppModule whenever we execute some HybridApp-specific code. Have you considered that solution?

Nope, so does that detect the user being in the NewDot app, or the Hybrid app? So I assume you would then check for the module existence within NewDot, and use that bool to register NewDot for notifications with the existing code (or not).

Something like this?
- NewDot app open: Register in react native
- Hybrid app open (NewDot): register in react native
- Hybrid app open (OldDot): register in native code
- Hybrid app switching to NewDot: do not register
- Hybrid app switching to OldDot: do not register

**Comment by staszekscp** [comment] 2024-07-17 19:40
Yes, it does. In this case it will be a simple code change - I think it should work. I will need some assistance with iOS provisioning profile for testing tomorrow, and in the meantime I'll play with android :)

**Comment by staszekscp** [comment] 2024-07-18 06:03
> - NewDot app open: Register in react native
> - Hybrid app open (NewDot): register in react native
> - Hybrid app open (OldDot): register in native code
> - Hybrid app switching to NewDot: do not register
> - Hybrid app switching to OldDot: do not register

Hey! Just to clear that up: I'm wondering do we have to do anything more than just preventing deregistration, which happens switching to NewDot in the HybridApp experience? I don't have access to the backend to look that up, but my understanding is that it has some kind of way to determine which push notification should be sent on the basis of `TryNewDot classicRedirect NVP`? Therefore whenever the `classicRedirect` is set to open NewDot we will get only ND notifications sent by the backend. Am I right, or do I miss something? 😄

**Comment by Julesssss** [comment] 2024-07-18 09:35
>  I'm wondering do we have to do anything more than just preventing deregistration, which happens switching to NewDot in the HybridApp experience?

No, and if i understand you correctly you are asking if we can stop the sending of incorrect app experience notifications?

> my understanding is that it has some kind of way to determine which push notification should be sent on the basis of TryNewDot classicRedirect NVP? Therefore whenever the classicRedirect is set to open NewDot we will get only ND notifications sent by the backend.

Pretty much. Right now we simply duplicate the NewDot notification and resend it to Hybrid with the same data (if the user is in the beta). I assume we might want to start routing to one or the other, instead of duplicating. In both cases this depends purely on the state of the TryNewDot `classicRedirect.dismissed` value.

**Comment by staszekscp** [comment] 2024-07-18 09:40
Ok, thanks for answering!

**Comment by staszekscp** [comment] 2024-07-18 10:11
Currently when I send a message in NewDot report I get a double notification on Android - that's why I'm asking, because I think a better solution would be to handle it on the backend, and send only one notification depending on the `classicRedirect.dismissed` value, because as far as I understand there are some notifications that are Old- or NewDot specific, but some of them may be sent to both experiences (like `reportComment` which is currently doubled)

**Comment by staszekscp** [comment] 2024-07-18 11:12
Ok, thanks! Yeah, theoretically that should work - I will test it to see if everything looks fine, and prepare a PR

**Comment by staszekscp** [comment] 2024-07-19 07:30
Hey! Just a quick update:

- I've noticed a problem on Android with reliability of navigation on NewDot after opening HybridApp from push notifications, and I'm currently focusing on that
- I am unfortunately unable to get any push notifications on iOS (neither OldDot nor NewDot). I struggled with it before, and @AndrewGable helped me by setting up some ngrok server I could hit to get notifications reach my account. Nevertheless my account could never get "real" notifications on iOS, even though I run it on a physical device. It seems that I am registered in Airship, I also received a `deviceToken` but the `onNotificationReceived` callback is never triggered. @Julesssss, could you confirm that you receive OldDot push notifications correctly on HybridApp, and the problem is only with NewDot notifications?

**Comment by staszekscp** [comment] 2024-07-19 12:50
Hello! I was focusing on the Android navigation, and I'm getting closer to the desired result. However I noticed that push notification changes in NewDot logic will require some tweaks in the integration of HybridApp to make the transitioning between screens reliable. I will keep you updated next week how the things are going! 😄

**Comment by Julesssss** [comment] 2024-07-19 14:22
> could you confirm that you receive OldDot push notifications correctly on HybridApp, and the problem is only with NewDot notifications?

Yeah, I am able to receive notifications when building an Android production flavour build (and with my account opted into the beta). I haven't been successful with iOS though. IIRC you were connecting to Andrew's VM via Ngrok which we can reproduce next week. I recall seeing that Slack thread recently.

> However I noticed that push notification changes in NewDot logic will require some tweaks in the integration of HybridApp to make the transitioning between screens reliable.

Thanks for the update 👍

**Comment by staszekscp** [comment] 2024-07-22 14:36
Hey! Today I was trying to understand what happens whenever we enter the app from a push notification. I still have to figure out how to solve two small problems: 
1. Removing `Transition` screen from the navigation hierarchy - for some reason it gets "sandwiched" between Home and target screens and stucks there
2. Sometimes the target screen gets removed right after navigating to it.

As per iOS do you know if the VM solution would be the only way to test push notifications? I wonder why I cannot get notifications for testing purposes. 😢 I suppose it could be related to some  backend or Airship development setup, because  It seems that on my TestFlight everything works fine - on iOS I get both: OldDot and NewDot notifications correctly. Nevertheless navigation state is messed up 😢 Without a way to test it I think it'll be very difficult to fix 😞

**Comment by CortneyOfstad** [comment] 2024-07-22 19:06
@Julesssss any input or ideas on the above ^^^? I'm leaning onto your expertise here 😂

**Comment by Julesssss** [comment] 2024-07-23 15:04
> As per iOS do you know if the VM solution would be the only way to test push notifications? I wonder why I cannot get notifications for testing purposes. 

Hey, sorry for the delay. I was trying to help figure this out today but ran into issues of my own. I'll try again tomorrow. 

Some starting points for my testing are:
- Do we need to reproduce the VM notification testing that Andrew previously tried?
- Are test Airship notifications received?
- Are Android notifications received with a similarly configured prod environment?
- Are the Airship keys set correctly for the build config?

You likely have all of this configured correctly, but it will helpful for me, and to help others debug in the future.

**Comment by staszekscp** [comment] 2024-07-23 15:20
Hey! Addressing your questions:

> Do we need to [reproduce](https://expensify.slack.com/archives/C036QM0SLJK/p1719352482329279?thread_ts=1719313822.267299&cid=C036QM0SLJK) the VM notification testing that Andrew previously tried?

That was unfortunately the only way to test the notifications. 😢 Unfortunately even though it is not the most reliable, it's the best we had

> Are test Airship notifications received?

While I was testing I could get both - OldDot and NewDot notifications just fine. I think that the most important thing is to send only one notification from the backend depending on the `tryNewDot` NVP. I noticed that I get double notifications on both - locally built Android and iOS TestFlight version

> Are Android notifications received with a similarly configured prod environment?
I used both `debug` and `release` keys, and both worked just fine

> Are the Airship keys set correctly for the build config?
Yes, I think they're correctly configured

For a local iOS built I tested different airship keys, and checked if the device token is received. Everything seems to be just fine, however I don't get any notifications. There is a chance that a local, release iOS build _could_ work, but I don't have entitlements to do that. I think only devs with distribution certificate are allowed to build such version locally

**Comment by Julesssss** [comment] 2024-07-23 15:26
> There is a chance that a local, release iOS build could work, but I don't have entitlements to do that. I think only devs with distribution certificate are allowed to build such version locally

Yeah that sounds familiar. And no developer has been given an iOS distribution  certificate. @AndrewGable given how important it is to test iOS notifications I wonder if we might reconsider this? 

Regarding the notification dupe, I'll be on that soon. Helping you to receive push notifications seems a bit more important in the meantime though, so tomorrow I will try to setup my environment to match what Andrew [did](https://expensify.slack.com/archives/C036QM0SLJK/p1719352482329279?thread_ts=1719313822.267299&cid=C036QM0SLJK) in the past.

**Comment by Julesssss** [comment] 2024-07-24 09:57
Android PRs are in review. 

But we still need a solution for testing iOS Hybrid. Right now I think our only options are: 
- Grant deployment certs for a brief period of time
- Test on a TestFlight build
- Test with a dev environment, with SWM pointing to one of our vms...?

**Comment by trjExpensify** [comment] 2024-07-25 15:06
Pretty sure we need to keep this open for this PR and then iOS: https://github.com/Expensify/App/pull/46090

**Comment by trjExpensify** [comment] 2024-07-31 11:19
Reopening this for now until confirmed to make sure we don't lose it: https://expensify.slack.com/archives/C036QM0SLJK/p1722339280598909?thread_ts=1722276993.634759&cid=C036QM0SLJK

**Comment by Julesssss** [comment] 2024-07-31 12:09
@staszekscp would you mind confirming the state of this original issue?

I believe we are good to ship Hybrid, but after the recent PRs it's not clear to me what still needs to be worked on to support Hybrid NewDot. I have split out the backend notification routing work [here](https://github.com/Expensify/App/issues/46485).

Thanks

**Comment by CortneyOfstad** [comment] 2024-07-31 12:29
Hey @bfitzexpensify! I am heading OoO so reassigned so someone could keep an eye on this in the meantime — thanks!

**Comment by staszekscp** [comment] 2024-07-31 13:08
@Julesssss I have done some changes to improve routing in NewDot part of HybridApp. 
- Android: I've fixed navigation and transitions. The app should handle the incoming notifications well. However we still get double notifications.
- iOS: I've created an `.apns` file in order to test the notifications routing with it. The routing seems to be working fine. Nevertheless it was not 1:1 experience, so I am not fully confident that everything is correct, but on TestFlight it looks quite well:

https://github.com/user-attachments/assets/3737e6ff-afc8-4ff8-a167-3523c2777f19

**Comment by Julesssss** [comment] 2024-07-31 13:53
> The app should handle the incoming notifications well. However we still get double notifications.

Cool, I'm not too worried about dupe notifications, as it just applies to `@expensify.com` and `swmansion.com` accounts. The beta will be removed and replaced soon.

Great to hear about the improvements. When I have a moment I will take test these builds. I think at this point the original issue should be resolved, right? (Hybrid user switches to NewDot)

**Comment by CortneyOfstad** [comment] 2024-08-14 21:21
Sorry for the delay here! @Julesssss @staszekscp do you think we need regression test for this?

**Comment by Julesssss** [comment] 2024-08-19 13:50
No I don't think so. We're still improving this flow

**Comment by CortneyOfstad** [comment] 2024-08-19 14:11
Okay, so no regression test is needed and payment is through vendor contracts, going to close this! Thanks all!

**Closed by CortneyOfstad** 2024-08-19 14:11 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
