### ISSUE TITLE
Expense - Hourglass message and report header title is not displayed in Spanish

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51167] opened 2024-10-21 10:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition:
1. Set app language to spanish
2. Have a workspace created
3. Open workspace chat
4. Create an expense

Steps:
1. Go to https://staging.new.expensify.com/home
2. Open the workspace chat
3. Open the expense
4. Note the hourglass message and report header title

## Expected Result:
Hourglass message and report header title must be displayed in Spanish.

## Actual Result:
Hourglass message and report header title is not displayed in Spanish.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6640789_1729501044962!Screenshot_2024-10-21-14-16-27-027_com android chrome-edit](https://github.com/user-attachments/assets/0ffd0c6b-bf6e-418a-8376-8432e1027549)

https://github.com/user-attachments/assets/03c0bc09-d41e-4d4b-a0f0-86fcb389a6c5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-21 10:25
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by ChavdaSachin** [comment] 2024-10-21 10:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hourglass message and report header title is not displayed in Spanish

### What is the root cause of that problem?
It is handled from here
https://github.com/Expensify/App/blob/da68c0ba9d2c859714038f487aca8a1c73dbc10d/src/libs/NextStepUtils.ts#L110-L136

The whole [NextStepUtils](https://github.com/Expensify/App/blob/da68c0ba9d2c859714038f487aca8a1c73dbc10d/src/libs/NextStepUtils.ts#L110-L136) file is hard coded in English.
### What changes do you think we should make in order to solve the problem?
Make use of translate function for the whole [NextStepUtils](https://github.com/Expensify/App/blob/da68c0ba9d2c859714038f487aca8a1c73dbc10d/src/libs/NextStepUtils.ts#L110-L136) file to tackle current and all the future similar issues.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by FitseTLT** [comment] 2024-10-21 12:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense - Hourglass message and report header title is not displayed in Spanish

### What is the root cause of that problem?
1. Header title:
We are displaying the `reportName` of the report directly which lacks translation 
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/libs/ReportUtils.ts#L2939
2. Next Steps: 
We are directly displaying (without translation) the next steps here
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/components/MoneyReportHeaderStatusBar.tsx#L47 
### What changes do you think we should make in order to solve the problem?

We should add the necessary copys for these cases and display them 
1. Here
https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/libs/ReportUtils.ts#L2939
We can translate the `reportName` we can do that in the general case for both invoice and money request report we can separate the `Expense` (`Invoice`) part of the text and pass the type expense or invoice and also the id of the report to a translateLocal as params and translate it accordingly
2. For next steps we will need to create a copy for the different types of next step messages we have got, and we can get the m from [here](https://github.com/Expensify/App/blob/b2fc5c9627821ed4647d7fa656ba9d2b0a5d6d58/src/libs/NextStepUtils.ts#L83) (and also from BE in case there are next steps for which we are not creating an optimistic data)
but we will need to first identify the type of next message we have got from the `nextStep.message` array so that we can translate meaningfully as a sentence. Then we will pass the type of next step and the necessary params like the email  and then translate Local will return us the next step HTML in text just similar to what `NextStepUtils.parseMessage` is doing now.
### What alternative solutions did you explore? (Optional)

**Comment by OfstadC** [comment] 2024-10-22 18:16
Will hopefully get to this today

**Comment by OfstadC** [comment] 2024-10-25 12:46
Posting in Slack

**Comment by OfstadC** [comment] 2024-10-25 17:51
This[ isn't supported](https://expensify.slack.com/archives/C05LX9D6E07/p1729877262223119?thread_ts=1729860541.820099&cid=C05LX9D6E07) currently and we don't have immediate plans to change this - closing

**Closed by OfstadC** 2024-10-25 17:51 UTC
Labels: Daily, Bug
