### ISSUE TITLE
[hold for payment 2023-01-30] Profile picture on profile page should have 0 px padding or margin from top navigation

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14182] opened 2023-01-10 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings and check the padding from top navigation for profile image
3. Open Workspaces
4. Open any Workspace and check the margin from top navigation for Workspace profile
5. Open general settings and check the margin from top navigation for Workspace profile
6. Open any report
7. Click on any user name and check the padding from top navigation for user profile
8. Open settings
9. Open profile and check the padding or margin from top navigation for profile image

## Expected Result:
All instances where the Profile image appears in the app should have a consistent amount of top padding.

## Actual Result:
Profile image has no margin or padding on the top.
Note: (Other pages with profile maintains 20 px margin or padding from navigation)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.51-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (2)](https://user-images.githubusercontent.com/43996225/211596288-d12c5b1a-994e-48f1-b14f-a7a594e856ea.png)
![image (3)](https://user-images.githubusercontent.com/43996225/211596291-46659cc0-ff65-40c3-a7f4-6068b81735b8.png)
![image](https://user-images.githubusercontent.com/43996225/211596295-c08e2d55-8fce-480c-9fb1-ab271c66b7f3.png)
<img width="960" alt="3" src="https://user-images.githubusercontent.com/43996225/211596318-63b4f9fb-dc3e-4875-8a09-7cd590a0fca7.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/43996225/211596320-705353cc-54a6-44a8-bf07-cd525f21d9f2.png">
<img width="960" alt="1" src="https://user-images.githubusercontent.com/43996225/211596322-bbf4c851-bd73-4728-a36a-ac9303707a9d.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673281072815909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b073cc0e3a5005d6</li>
        <li>Upwork Job ID: 1613974508062380032</li>
        <li>Last Price Increase: 2023-01-13</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-01-10 21:00
Discussing [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1673384375788379?thread_ts=1673281072.815909&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2023-01-11 22:04
Working on triaging this: 

From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you're unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it's better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by joekaufmanexpensify** [comment] 2023-01-11 22:04
@arosiclair once this is triaged, I'm thinking you want to take this one and keep it internal?

**Comment by arosiclair** [comment] 2023-01-12 16:15
> @arosiclair once this is triaged, I'm thinking you want to take this one and keep it internal?

Yup that's correct!

**Comment by joekaufmanexpensify** [comment] 2023-01-12 19:10
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-01-12 20:55
Reproduced on web: 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54866469/212178665-05cd8eda-96ae-4950-8841-fa621fba38a7.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/54866469/212178676-d77815eb-196c-4292-b1bc-b5a116bf5925.png">

**Comment by joekaufmanexpensify** [comment] 2023-01-12 20:56
Okay, this is reproduced. Before we proceed, discussing what the actual fix looks like here in the slack thread. Let's hold off on proceeding until we're crisp on that.

**Comment by joekaufmanexpensify** [comment] 2023-01-13 18:59
Discussed in the [slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1673600527127509?thread_ts=1673281072.815909&cid=C049HHMV9SM), and the solution we want for fixing this bug is leaving no top padding on the profile page, and removing the top padding for the profile image on the Settings page, the workspace page, the workspace general settings page, and the details page accessed when clicking another user's profile image. 

Updating the OP of the issue to make this clear, and then making this internal.

**Comment by joekaufmanexpensify** [comment] 2023-01-13 19:01
All yours @arosiclair !

**Comment by joekaufmanexpensify** [comment] 2023-01-16 14:44
Not overdue.

**Comment by joekaufmanexpensify** [comment] 2023-01-16 16:05
Hm, not sure why the label is still there?

**Comment by joekaufmanexpensify** [comment] 2023-01-17 18:31
Next step here is to begin the PR

**Comment by arosiclair** [comment] 2023-01-18 19:52
Working on this today

**Comment by joekaufmanexpensify** [comment] 2023-01-26 15:51
Okay, no C+ review done here, so no payment to them is needed. We implemented this internally, so no C payment as well. So the only payment we need to make here is the $250 reporting bonus to @dhanashree-sawant

**Comment by joekaufmanexpensify** [comment] 2023-01-26 15:53
@eVoloshchak un-assigning as you didn't review the PR here.

**Comment by joekaufmanexpensify** [comment] 2023-01-26 15:56
@dhanashree-sawant, contract sent for $250! We'll issue payment after the 7 day regression waiting period, on 2023-01-30.

**Comment by joekaufmanexpensify** [comment] 2023-01-26 15:58
Besides that, only other step here is the BZ checklist. Not sure why it didn't get automatically created, so will add it manually!

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@arosiclair ] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@arosiclair] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@arosiclair ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@joekaufmanexpensify] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by arosiclair** [comment] 2023-01-30 19:35
Finding it very hard to find when exactly the spacing on top of the profile page was removed. It definitely had some spacing originally, but the profile page history is long with a lot of layout changes. Since this is a low impact bug and we had a big redesign, I'll skip that part and just post a thread on how to possibly keep this from occurring again.

**Comment by joekaufmanexpensify** [comment] 2023-01-30 19:43
Switching to daily as payment is due today.

**Comment by joekaufmanexpensify** [comment] 2023-01-30 19:49
@dhanashree-sawant $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-01-30 19:49
Closed upwork job.

**Comment by joekaufmanexpensify** [comment] 2023-01-30 20:21
Proposed new regression test [here. ](https://expensify.slack.com/archives/C01SKUP7QR0/p1675110054489099)

**Comment by joekaufmanexpensify** [comment] 2023-01-31 17:02
Okay, ended up not creating a new regression test here. Since this is more design focused, I instead added it to the new design testing guidelines we're creating for applause.

**Comment by joekaufmanexpensify** [comment] 2023-01-31 17:03
Closing as this is all set!

**Closed by joekaufmanexpensify** 2023-01-31 17:03 UTC
Labels: Reviewing, Daily, Internal, Bug
