### ISSUE TITLE
[HOLD for payment 2024-04-25] Android  - IOU - Unable to send money with user having no prior conversation

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40055] opened 2024-04-10 23:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tab fab-- send money
3. Enter an amount and tap next
4. In search enter an email id with no prior conversation and select it
5. Tap pay elsewhere

## Expected Result:
For users without prior conversation history, tapping "Pay Elsewhere" should still allow them to send money seamlessly

## Actual Result:
Unable to send money with user having no prior conversation

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/51c612a7-1a90-43e4-a2aa-11524b745777

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014443720b96ea2053</li>
        <li>Upwork Job ID: 1778366995464167424</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-10 23:57
We think that this bug might be related to #vip-vsb

**Comment by nkdengineer** [comment] 2024-04-11 04:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Android - IOU - Unable to send money with user having no prior conversation
### What is the root cause of that problem?
- In case of new user, this [condition](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L436) will return ```true```, leads to the function ```IOU.sendMoneyElsewhere``` is not called.
### What changes do you think we should make in order to solve the problem?
 - We can remove ```!report``` from the above condition.
 - Then, update [this](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L441) to:
```
               IOU.sendMoneyElsewhere(report ?? {}, transaction.amount, currency, trimmedComment, currentUserPersonalDetails.accountID, participant);
```
- We should fix other logics that are similar to ```IOU.sendMoneyElsewhere```, such as ```IOU.sendMoneyWithWallet```
### What alternative solutions did you explore? (Optional)
- NA

**Comment by Gonals** [comment] 2024-04-11 09:06
This issue also exists for the `Request Money - Distance` flow

**Comment by Gonals** [comment] 2024-04-11 10:18
Marking as internal to fix asap

**Comment by Julesssss** [comment] 2024-04-11 14:06
CP [build in progress](https://github.com/Expensify/App/actions/runs/8648039811)

**Comment by Julesssss** [comment] 2024-04-11 15:19
@Gonals could you please confirm on staging then check it off? thanks

**Comment by Gonals** [comment] 2024-04-11 15:31
Working on Staging!

**Comment by lschurr** [comment] 2024-04-25 18:25
Sent offer to @jjcoffee in Upwork - https://www.upwork.com/nx/wm/offer/102032170

**Comment by jjcoffee** [comment] 2024-04-26 07:49
@lschurr Accepted, thanks!

**Comment by lschurr** [comment] 2024-04-26 16:09
All set!

**Closed by lschurr** 2024-04-26 16:09 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment
