### ISSUE TITLE
Multi tags - App freezes when clicking checkbox in subtag list

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48675] opened 2024-09-06 04:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace is connected to QBO, or have multi tags set up.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Click on any main tag.
4. Click Select all checkbox.

## Expected Result:
App will not freeze.

## Actual Result:
App freezes when clicking checkbox in subtag list.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/76ba7188-5107-4f18-a22d-de6a6eb4d942

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-06 04:24
We think that this bug might be related to #wave-collect - Release 1

**Comment by techievivek** [comment] 2024-09-09 01:49
Closing this since it was a regression and is fixed and CPed.

**Closed by techievivek** 2024-09-09 01:49 UTC
Labels: Reviewing, Engineering, Daily, Bug
