### ISSUE TITLE
[HOLD for payment 2024-10-22] Expense - "auto paid with Expensify" system message has <a href="link"> and </a> when pasted

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50090] opened 2024-10-02 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Workspace has set up bank account.
- Employee does not have personal bank account.

1. Go to staging.new.expensify.com
2. [Employee] Submit an expense in the workspace chat.
3. [Admin] Pay the expense via Expensify.
4. [Employee] Click on the expense preview.
5. [Employee] Click Add bank account button.
6. [Employee] Add a bank account.
7. [Employee] Right click on the system message "automatically paid $123.00 with Expensify via workspace rules" > Copy to clipboard.
8. [Employee] Paste the content in the composer.

## Expected Result:
The content will be pasted correctly.

## Actual Result:
The pasted content has `<a href="link"> and </a>`.
The system message also shows `<a href="link"> and </a>` when the report is opened for the first time (after relogin).

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/751df924-d0ae-4af5-97d4-dc9d8a0a0662

https://github.com/user-attachments/assets/3514897f-6044-4fed-a71b-29af3f1a762d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by IuliiaHerets** [comment] 2024-10-02 17:31
We think that this bug might be related to #wave-collect - Release 1

**Comment by sakluger** [comment] 2024-10-02 18:14
I don't know if this needs to be a deploy blocker, it's not really blocking users from completing actions in Expensify. @luacmartins what do you think?

**Comment by jasperhuangg** [comment] 2024-10-02 20:20
@sakluger I think we should still try to fix the issue rather than letting the problem go out to production. @luacmartins were you able to look into this yet?

**Comment by luacmartins** [comment] 2024-10-02 20:28
Not yet, but as pointed out by @gijoe0295 this seems to be a backend issue, so maybe a `DeployBlocker` for web-e, not App.

**Comment by Gonals** [comment] 2024-10-02 20:56
Do we know which PR caused this? At this point, we should revert it or we won't deploy today

**Comment by Beamanator** [comment] 2024-10-02 21:53
Hmm honestly i wouldn't call this a blocker - the copy / paste including the href part - i did that on purpose... If we want to change that so it doesn't have the link, i'm fine with that but doesn't need to be blocker-priority

I don't understand the other point - The system message also shows <a href="link"> and </a> when the report is opened for the first time (after relogin). - I don't see that in the videos

**Comment by luacmartins** [comment] 2024-10-02 21:58
Demoting to NAB given Alex's comment

**Comment by Beamanator** [comment] 2024-10-02 22:00
Assigning so i can also get some thoughts in - this is related to https://github.com/Expensify/App/issues/35091 btw

@trjExpensify do you think the "workspace rules" link should be copied with the html when a user copies the text of that auto-reimbursed report action?

**Comment by Beamanator** [comment] 2024-10-02 22:11
Hmm @ishpaul777 so it looks like you left the HTML link in the message when copied, right?

**Comment by trjExpensify** [comment] 2024-10-03 00:06
>yeah! actualy link copying was handled with setClipboardMessage

and does it convert it to markdown when copied then?

**Comment by Beamanator** [comment] 2024-10-03 01:56
aah markdown when copied! I like that plan, that sounds better than the HTML 👍

**Comment by Beamanator** [comment] 2024-10-03 17:45
Thanks @ishpaul777 - before we got external I think we need to nail down all the things we need to get updated / fixed in this issue 👍  want to help with that? Then, yes I'm quite sure we can get this going external for the fix(es)

**Comment by Beamanator** [comment] 2024-10-03 22:53
Nice, yep i def think that's a first thing to update 👍 👍 

Do you have any ideas for fixing the "oh first loading a report w/ HTML in the report action, after logging in & loading the report, the HTML is displayed as text instead of rendered HTML" - does that make sense?

**Comment by Beamanator** [comment] 2024-10-04 17:32
By the way I have a backend PR up to fix the "first load of the auto-paid message" - I found the bug & hopefully fixed it

**Comment by Beamanator** [comment] 2024-10-07 14:59
Backend PR merged, once deployed the "first load" part should be fixed

**Comment by Beamanator** [comment] 2024-10-07 18:55
Nahhh, #50181 is just about copying / pasting that system message, which is lower priority IMO so i haven't had time to prioritize yettt

**Comment by sakluger** [comment] 2024-10-07 23:51
Got it. So where is the other PR? I don't see any others linked to this GH issue.

**Comment by Beamanator** [comment] 2024-10-08 14:37
Aah the other one is https://github.com/Expensify/Auth/pull/12691! Which is on prod as of last night so hopefully we can see it's fixed now! 🙏

**Comment by sakluger** [comment] 2024-10-17 20:52
Upwork offer: https://www.upwork.com/nx/wm/offer/104438278

I sent it from [[$250] Payment issue for E/App PR#50059](https://github.com/Expensify/App/issues/50742#top)

**Comment by sakluger** [comment] 2024-10-22 16:45
@ishpaul777 do we need any regression new tests for this one?

**Comment by sakluger** [comment] 2024-10-23 17:04
This has already been paid in https://github.com/Expensify/App/issues/50742.

@ishpaul777 let us know if we need any regression tests before we close the issue.

**Comment by sakluger** [comment] 2024-10-24 17:36
Oh wow, you're right - I misread the issue number on that one. My mistake!

Here's an offer for this one: https://www.upwork.com/nx/wm/offer/104577466

**Comment by sakluger** [comment] 2024-10-24 23:24
Paid! Thanks again for staying on top of this @ishpaul777.

**Closed by sakluger** 2024-10-24 23:24 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
