### ISSUE TITLE
[Hold #12917] [$1000] IOU - copy to clipboard appears before closing the context menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13004] opened 2022-11-24 15:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat 
2. Send a request 
3. Long press on the IOU preview to bring up the context menu 
4. Tap outside of the context menu to close it

## Expected Result:
The context menu closes without an additional screen displayed

## Actual Result:
The `copy to clipboard` menu appears quickly before the context menu is closed

## Workaround:
None

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.35-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

Original report:
https://user-images.githubusercontent.com/43996225/203825089-02357973-ef8d-4bf5-b09d-2a8a77af0b46.mov

TRJ reproduction:
https://user-images.githubusercontent.com/16232057/205189920-13befcd3-cef1-4332-9492-ceb3e4a862f9.MP4

_Tip: knock the playback speed down a bit to see it more clearly._ 

**Expensify Issue URL:** 
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669224900283549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01f143785cdc3e8069
- Upwork Job ID: 1598483124909977600

**Comment by trjExpensify** [comment] 2022-12-02 01:03
👋 Happened across this one hanging out here. I can reproduce it on a physical device (iOS 16, iPhone 13 Pro) on the latest staging app: `v1.2.35-0`. 

**Action Performed:**

1. Open any chat 
2. Send a request 
3. Long press on the IOU preview to bring up the context menu 
4. Tap outside of the context menu to close it

**Actual Result**
The `copy to clipboard` menu appears quickly before the context menu is closed

**Expected Result** 
The context menu closes without this added step

https://user-images.githubusercontent.com/16232057/205189920-13befcd3-cef1-4332-9492-ceb3e4a862f9.MP4

_Pro-tip: knock the playback speed down a bit to see it more clearly._ 

Adding the `Bug` and `External` labels.

**Comment by trjExpensify** [comment] 2022-12-02 01:09
@b1tjoy I noticed [this PR](https://github.com/Expensify/App/pull/12987) where you're working on something in this area, I don't think it addresses this problem on IOU previews does it?

**Comment by trjExpensify** [comment] 2022-12-02 12:48
Nice! Any luck?

**Comment by PauloGasparSv** [comment] 2022-12-02 14:49
@railway17 were you on the very latest version of `main`?

Asking this because **I just tested** and reproduced the bug on my first try but then I pulled from main and the bug was gone. I can'r reproduce this here.

**Comment by railway17** [comment] 2022-12-02 14:52
> @railway17 were you on the very latest version of `main`?
> 
> Asking this because **I just tested** and reproduced the bug on my first try but then I pulled from main and the bug was gone. I can'r reproduce this here.

Let me check with latest code.
But this issue has a very clear reason, so it should appear as long as there were not any changes in `hideContextMenu` method.

**Comment by railway17** [comment] 2022-12-02 15:02
Ah.. 
It was updated in latest `main` 🥲 and reportAction is updated inside `runAndResetOnPopoverHide`

**Comment by trjExpensify** [comment] 2022-12-02 15:12
Okay, niceee! I'm going to pop a hold in the title for [#12917](https://github.com/Expensify/App/pull/12917). I'll retest once it hits staging and then close it out.

**Comment by PauloGasparSv** [comment] 2022-12-08 19:12
Cannot reproduce the issue here! Let's close this off : )

**Closed by PauloGasparSv** 2022-12-08 19:12 UTC
Labels: External, Daily, Help Wanted, Bug
