### ISSUE TITLE
[$250]   IOUs - Error thrown when paying a cancled expense again

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46312] opened 2024-07-26 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** negasofonias+72460@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a workspace, click on + and select submit an expense
2. Select distance and fill out start and stop locations and click next
3. Click on submit expense
4. open the expense by clicking on the IOU message
5. Click on drop down menu on pay with expensify button and select pay elsewhere
6. Click on pay elsewhere and observe the ✓Finished no further action required
7. Click on the expense headed to open details and select cancel payment
8. Go back to expense report and click on the pay elsewhere button
9. Observe that an error occurs

## Expected Result:
Error should not be thrown

## Actual Result:
An unexpected error occured error is thrown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/35734fb4-21de-4b0b-872c-e46ca9090d00

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012ef1105a2c193943</li>
        <li>Upwork Job ID: 1822887378516922982</li>
        <li>Last Price Increase: 2024-09-02</li>
    </ul>
</details>

**Comment by RachCHopkins** [comment] 2024-07-29 04:29
Works fine for me on NewDot mobile web and iOS app. 

![IMG_D02C7BB17F48-1](https://github.com/user-attachments/assets/f9375622-27d4-461e-bae3-fc5900a06d06)

Please retest.

**Comment by RachCHopkins** [comment] 2024-08-02 02:11
Waiting on retest

**Comment by RachCHopkins** [comment] 2024-08-06 00:07
@lanitochka17 was your team able to retest this?

**Comment by mvtglobally** [comment] 2024-08-09 04:29
Issue is reproducible during KI retests.

https://github.com/user-attachments/assets/bd3ddfef-83c8-4663-9787-fbf94bae42f8

**Comment by RachCHopkins** [comment] 2024-08-12 06:43
Ok, welp, as long as you can reproduce!

**Comment by RachCHopkins** [comment] 2024-08-22 07:08
TBH I don't see this as needing more incentive.

**Comment by burczu** [comment] 2024-09-03 09:30
Hi, I’m Bartek from Callstack and I would like to work on this issue.

**Comment by rushatgabhane** [comment] 2024-09-04 02:36
🎀 👀 🎀 @burczu

**Comment by burczu** [comment] 2024-09-04 13:32
Thanks for assignment - I've started investigation but nothing to share yet. I just need to let you know, that due to the React Native Conf + my personal holiday I'll be OOO 5 - 9 September, so I'll be back working on this on Tuesday.

**Comment by RachCHopkins** [comment] 2024-09-10 00:24
Changing to weekly until it starts moving again!

**Comment by burczu** [comment] 2024-09-11 08:47
I investigated the issue and in my opinion it seems to be on the backend side. When we pay the expense for the first time (the `PayMoneyRequest` action), we receive the response containing correct update to the report action:

![Screenshot 2024-09-11 at 10 39 27](https://github.com/user-attachments/assets/543e8b0e-e471-4430-8dd4-ea7b43186a12)

Next, we call the `CancelPayment` action and the report is marked as `isCancelledIOU: true` along with the new report action with the message that the expense is cancelled:

![Screenshot 2024-09-11 at 10 43 22](https://github.com/user-attachments/assets/82dd4b7a-d710-4ee0-bc92-2e5fef34ae65)

I think at this point the expense is not brought back to the unpaid state correctly on the BE side, because once we call the `PayMoneyRequest` again, we get the response containing an error:

![Screenshot 2024-09-11 at 10 46 33](https://github.com/user-attachments/assets/fefd5722-83c8-4a81-b411-93976fb80be8)

I think we should ask someone from the backend team to review this.

**Comment by RachCHopkins** [comment] 2024-09-18 00:05
Have asked for an Internal engineer to take a look and confirm if this should be internal.

**Comment by trjExpensify** [comment] 2024-09-18 15:39
Linking the thread for following the breadcrumbs: https://expensify.slack.com/archives/C036QM0SLJK/p1726617915209259

**Comment by lakchote** [comment] 2024-09-19 06:33
> Have asked for an Internal engineer to take a look and confirm if this should be internal.

Thank you! @mountiny asked QA [here](https://expensify.slack.com/archives/C9YU7BX5M/p1726690731220209) if the issue is only reproducible on android mWeb (which is _weird_).

**Comment by m-natarajan** [comment] 2024-09-19 12:30
Issue reproducible in other platforms as well, Updated title and platforms.

https://github.com/user-attachments/assets/b221df26-2fc9-4f35-8fa8-86ff5ebbbac7


https://github.com/user-attachments/assets/075ec95a-5620-4f30-b004-1de48128dcd7

**Comment by RachCHopkins** [comment] 2024-09-20 04:29
@lakchote what do you reckon? Internal or External?

**Comment by lakchote** [comment] 2024-09-20 08:55
> @lakchote what do you reckon? Internal or External?

I'd say this is internal, given the [investigation](https://github.com/Expensify/App/issues/46312#issuecomment-2343032493) from @burczu

**Comment by RachCHopkins** [comment] 2024-09-24 04:30
Adding Hot Picks label.

**Comment by RachCHopkins** [comment] 2024-09-24 04:31
Melvin, stop.

**Comment by trjExpensify** [comment] 2024-09-30 11:05
@lakchote are you taking this one as it's `internal`?

**Comment by lakchote** [comment] 2024-09-30 14:26
> @lakchote are you taking this one as it's `internal`?

Short answer: yes, I'll provide updates for this issue here.

Haven't been able to focus on it yet, as my focus was on raising backend PRs for QBD to make sure everything is ready and contributors can work on it.

**Comment by lakchote** [comment] 2024-09-30 15:08
Issue not reproducible on staging @trjExpensify (`v9.0.41-4`):

https://github.com/user-attachments/assets/97fe022c-7dc6-497e-be0b-d60e7226c8d6

cc @lanitochka17 could you please retest?

**Comment by m-natarajan** [comment] 2024-09-30 18:08
Unable to reproduce this

https://github.com/user-attachments/assets/d9a87e84-66ed-4fd5-9bcb-0baa2ac4a5be

**Comment by trjExpensify** [comment] 2024-10-01 01:04
Nice, thanks! Let's close this then. :)

**Closed by trjExpensify** 2024-10-01 01:04 UTC
Labels: Daily, Internal, Bug, Hot Pick
