### ISSUE TITLE
Tag - Not here page shows up when opening Tag from split details RHP

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37886] opened 2024-03-07 12:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has tags.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Go to FAB > Split bill > Scan.
4. Create a split scan request.
5. Click on the split preview to open split details RHP.
6. Click Tag.

## Expected Result:
Tag list opens without issue.

## Actual Result:
Not here page shows up when opening Tag from split details RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/93afc90c-0c48-4739-ab5c-d9dc7102ba69

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-03-07 12:08
We have already figured out this before it was created and working on it. PR fixing the regression on review stage
@puneetlath

**Comment by izarutskaya** [comment] 2024-03-07 12:08
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by FitseTLT** [comment] 2024-03-07 13:12
https://github.com/Expensify/App/pull/37879 👍

**Comment by roryabraham** [comment] 2024-03-07 18:56
again I suspect this is NAB because tags are a collect feature and thus need to be enabled with a JS snippet in OldDot, no?

**Comment by roryabraham** [comment] 2024-03-07 18:56
anyways, looks like we may have a WIP fix?

**Comment by puneetlath** [comment] 2024-03-07 20:41
>again I suspect this is NAB because tags are a collect feature and thus need to be enabled with a JS snippet in OldDot, no?

I agree with this. Removing it as a deploy blocker.

**Comment by puneetlath** [comment] 2024-03-10 17:53
PR was merged. It's a regression from another PR so no payment is needed here. Closing.

**Closed by puneetlath** 2024-03-10 17:53 UTC
Labels: Engineering, Daily, Bug
