### ISSUE TITLE
HIGH: [Live Markdown] [$500] Android - Chat - User unable to select complete sentence

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40890] opened 2024-04-24 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter a sentence
4. Try to select complete sentence

## Expected Result:
User must be able to select complete sentence

## Actual Result:
User unable to select complete sentence

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/29ff8a2e-c60a-4853-95fc-23a1fc8c440c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bd806a6be2ddbfd</li>
        <li>Upwork Job ID: 1783137020323028992</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-24 13:46
We think that this bug might be related to #vip-vsb

**Comment by mountiny** [comment] 2024-04-24 16:41
I do not have android device to reproduce this unfortuntely

**Comment by kbecciv** [comment] 2024-04-24 17:27
Issue is still reproducible on build 1.4.65.3

https://github.com/Expensify/App/assets/93399543/434ed363-c4b0-4634-8cb5-90a8942a9308

**Comment by KirtirajM** [comment] 2024-04-25 12:52
I want to solve this issue but I am unable to run the project on my mac , because of I don't have MapBox token

**Comment by KirtirajM** [comment] 2024-04-25 12:52
Contributor details
Your Expensify account email: kirtiraj.malkhede@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~017ac6dbe6c552ee4c

**Comment by mountiny** [comment] 2024-04-25 13:04
@Skalakid is going to investigate this one

I am going to demote the blocker label as there is no clear offending PR for this one and it looks like it might be device specific issue too. There is a workaround for the user to use the long press and copy to clipboard

**Comment by Skalakid** [comment] 2024-04-25 13:31
Hi, I'm Michał from Software-Mansion and I will investigate this issue

**Comment by Skalakid** [comment] 2024-04-29 07:30
After investigation, I found that the problem with text selection on Android had a root cause in the `react-native-live-markdown` library only after enabling the new architecture. I reported this bug and asked for help from our SWM team that worked on that. @j-piasecki came up with the fix in the live markdown library - [PR](https://github.com/Expensify/react-native-live-markdown/pull/335) and @WoLewicki prepared the [PR](https://github.com/Expensify/App/pull/41103) that bumps the live markdown version in E/App

**Comment by Skalakid** [comment] 2024-05-06 09:08
@hayata-suenaga The issue has been fixed inside the `react-native-live-markdown` library and [this PR](https://github.com/Expensify/App/pull/41103) contained version bump inside it. However, I can see that the library version has been already updated on main, so the issue should be fixed for now

**Comment by hayata-suenaga** [comment] 2024-05-06 21:38
@mountiny, it seems like we can close this issue 😄

**Comment by mountiny** [comment] 2024-05-08 19:19
@kavimuru @isagoico Could you please retest this issue on latest Android version?

**Comment by quinthar** [comment] 2024-05-09 23:03
@kavimuru @isagoico - Can you give an ETA on retesting on Android?

**Comment by isagoico** [comment] 2024-05-09 23:18
Apologies that we missed this yesterday. Checking with the team as I don't have my Android charged up and will post the results shortly.

**Comment by isagoico** [comment] 2024-05-09 23:33
Tester was unable to reproduce this on the latest version 1.4.72-1

https://github.com/Expensify/App/assets/44479856/ea5f764e-1ed9-4772-9859-a14283c84b53

**Closed** 2024-05-10 14:39 UTC
Labels: External, Engineering, Weekly
