### ISSUE TITLE
[HOLD for payment 2022-11-22] [$250] Payment option doesn't update unless refresh or reopen IOU details page reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12291] opened 2022-10-31 01:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with account A
2. Search for account B and request money
3. Open another browser > Login with account B
4. Go to chat with account A
5. Tap on pay button
6. Verify that you don't see the option Pay with PayPal.me at the button in iou details page
7. Close the modal
8. Go to account A
9. Go to settings > Payments > Add payment method
10. Click on PayPal.me > Add Paypal account
11. Go to account B again and click on pay button
12. Verify that you still don't see the option to Pay with PayPal.me
13. Refresh the page/ close and reopen the IOU details modal
14. Check if you see it now

## Expected Result:
You payment options should update at the step 12

## Actual Result:
The payment options doesn't update without refreshing or closing and re-opening the iou details page

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198913299-f0272dd6-1db6-46a1-b7e7-22788a1d73ea.mp4
https://user-images.githubusercontent.com/43996225/198913319-4a89ce03-5f83-4957-83d3-72598f9cb85e.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667080453236989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by daraksha-dk** [comment] 2022-10-31 08:53
**Proposal**

The payment options are set at the state and when the option paypal is removed the old value is being used

https://github.com/Expensify/App/blob/62ff507162d7712c2aa76b5eb96141f83ec2dd91/src/components/SettlementButton.js#L43-L71

`key` can be used to fix this. Now it will re render if the paypal address changes
`key={lodashGet(this.props, 'iouReport.submitterPayPalMeAddress')}`
https://github.com/Expensify/App/blob/62ff507162d7712c2aa76b5eb96141f83ec2dd91/src/pages/iou/IOUDetailsModal.js#L140

**Comment by sakluger** [comment] 2022-11-02 05:58
I confirmed that the Paypal payment option does not show up until I refresh the page. Adding the external label.

**Comment by sakluger** [comment] 2022-11-02 06:06
Internal Upwork post: https://www.upwork.com/ab/applicants/1587687358672089088/job-details
External Upwork post: https://www.upwork.com/jobs/~016bc1d3a553815351

**Comment by jasperhuangg** [comment] 2022-11-04 18:28
looks like we're still waiting for proposals on this one, not overdue

**Comment by jasperhuangg** [comment] 2022-11-04 18:30
This seems to be relatively edge-casey, gonna mark it as a `Weekly` while we wait for proposals.

**Comment by mallenexpensify** [comment] 2022-11-05 15:20
Bumped back to daily per our new BugZero process, [internal Slack thread with deets](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109)

**Comment by mananjadhav** [comment] 2022-11-05 19:26
Thanks for the proposal @daraksha-dk. I am not sure I follow your proposal. I don't see why/where would we need to add a `key`?

Also why do e need to update it with `submitterPayPalMeAddress` ? How does it handle refresh problem?


---

Still open for proposals.

**Comment by Delgee** [comment] 2022-11-07 20:35
### Proposal:

It looks like the issue is creating "buttonOptions" on the construction. So "buttonOptions" not changed on prop change.
https://github.com/Expensify/App/blob/dc0bb5db6dd835279dfb916e8b7b3ebd0703404f/src/components/SettlementButton.js#L43-L73

### Solution:

Making a method to create "buttonOptions" so it will be changed if the prop changes.

```diff
-    constructor(props) {
-        super(props);
-
-        const buttonOptions = [];
-
-        if (props.currency === CONST.CURRENCY.USD && Permissions.canUsePayWithExpensify(props.betas) && Permissions.canUseWallet(props.betas)) {
-            buttonOptions.push({
-                text: props.translate('iou.settleExpensify'),
-                icon: Expensicons.Wallet,
-                value: CONST.IOU.PAYMENT_TYPE.EXPENSIFY,
-            });
-        }
-
-        if (props.shouldShowPaypal) {
-            buttonOptions.push({
-                text: props.translate('iou.settlePaypalMe'),
-                icon: Expensicons.PayPal,
-                value: CONST.IOU.PAYMENT_TYPE.PAYPAL_ME,
-            });
-        }
-
-        buttonOptions.push({
-            text: props.translate('iou.settleElsewhere'),
-            icon: Expensicons.Cash,
-            value: CONST.IOU.PAYMENT_TYPE.ELSEWHERE,
-        });
-
-        this.state = {
-            buttonOptions,
-        };
-    }
-
+getButtonOptionsFromProps() {
+  const buttonOptions = [];
+
+  if (this.props.currency === CONST.CURRENCY.USD && Permissions.canUsePayWithExpensify(this.props.betas) && Permissions.canUseWallet(this.props.betas)) {
+      buttonOptions.push({
+          text: this.props.translate('iou.settleExpensify'),
+          icon: Expensicons.Wallet,
+          value: CONST.IOU.PAYMENT_TYPE.EXPENSIFY,
+      });
+  }

+  if (this.props.shouldShowPaypal) {
+      buttonOptions.push({
+          text: this.props.translate('iou.settlePaypalMe'),
+          icon: Expensicons.PayPal,
+          value: CONST.IOU.PAYMENT_TYPE.PAYPAL_ME,
+      });
+  }

+  buttonOptions.push({
+      text: this.props.translate('iou.settleElsewhere'),
+      icon: Expensicons.Cash,
+      value: CONST.IOU.PAYMENT_TYPE.ELSEWHERE,
+  });

+  return buttonOptions;
+}
```

```diff
                             this.props.onPress(iouPaymentType);
                         }}
-                        options={this.state.buttonOptions}
+                        options={this.getButtonOptionsFromProps()}
```

**Comment by daraksha-dk** [comment] 2022-11-07 20:59
The button is not updating because we are showing the previous options we need to re-render when the prop (PayPalMe address) changes

On passing `key={lodashGet(this.props, 'iouReport.submitterPayPalMeAddress')}` at `SettlementButton` the button will re-render with the latest option
https://github.com/Expensify/App/blob/62ff507162d7712c2aa76b5eb96141f83ec2dd91/src/pages/iou/IOUDetailsModal.js#L140

**Comment by jasperhuangg** [comment] 2022-11-07 21:17
I like @daraksha-dk proposal, simple and takes advantage of the existing React component lifecycle.

Can you try your solution and post a screen recording of it working since it's so simple? Once that happens I'll accept the proposal.

**Comment by jasperhuangg** [comment] 2022-11-07 21:22
@Delgee I like your proposal and I think it should work, let's go with it!

> External Upwork post: https://www.upwork.com/jobs/~016bc1d3a553815351

**Comment by jasperhuangg** [comment] 2022-11-07 21:22
@daraksha-dk thank you for your proposal, but I don't think your solution would work, because the `SettlementButton` sets its button styles in the constructor, and the constructor isn't invoked when props change.

**Comment by daraksha-dk** [comment] 2022-11-08 08:56
> @daraksha-dk thank you for your proposal, but I don't think your solution would work, because the `SettlementButton` sets its button styles in the constructor, and the constructor isn't invoked when props change.

My solution is to use key which will re-render the `SettlementButton` if the key value( submitterPayPalMeAddress ) changes so constructor will be invoked. You can see this article https://medium.com/@albertogasparin/forcing-state-reset-on-a-react-component-by-using-the-key-prop-14b36cd7448e

**Comment by Delgee** [comment] 2022-11-08 10:15
@jasperhuangg PR is ready for review. And created a proposal for Upwork.

**Comment by mananjadhav** [comment] 2022-11-10 21:27
@jasperhuangg @sakluger The last I could trace the changes was creation of `SettlementButton` in this [PR](https://github.com/Expensify/App/pull/6651). We've set `buttonOptions` in the constructor since the beginning and hence it wouldn't have refreshed the code. Now I am not sure if we had this code in some other component before this.

@jasperhuangg do you have the information on this?

**Comment by jasperhuangg** [comment] 2022-11-11 17:56
Hmm it looks like that PR creates the settlement button using the constructor, it didn't necessarily introduce the bug, we just weren't aware of the bug when that PR went out and didn't know that was something we needed to test for. That being said, since that's the only PR that's related let's use that one. @mananjadhav

**Comment by jasperhuangg** [comment] 2022-11-11 17:58
@sakluger If you comment on the PR, just make sure you mention something about how we should sure that all reusable components react accordingly to any prop updates.

**Comment by mananjadhav** [comment] 2022-11-11 17:59
> it didn't necessarily introduce the bug, we just weren't aware of the bug when that PR went out 

Honestly, this has been my dilemma for a few issues. Thanks for helping out here.

**Comment by mananjadhav** [comment] 2022-11-15 17:07
This PR was deployed to production 5 days ago, but it's payment date wasn't updated. @sakluger This due in 2 days.

**Comment by sakluger** [comment] 2022-11-22 00:36
@mananjadhav which PR were you talking about in [this comment](https://github.com/Expensify/App/issues/12291#issuecomment-1315617426)? It looks like the linked PR was deployed to production 6 days ago and should be paid out tomorrow.

**Comment by mananjadhav** [comment] 2022-11-22 03:32
@sakluger My bad, I am not sure why I saw 5 days ago! Thanks for clarifying.

**Comment by mananjadhav** [comment] 2022-11-22 10:17
@sakluger Quick note this is eligible for 50% bonus as it was merged within 3 business days.

**Comment by marcaaron** [comment] 2022-11-22 21:35
>Hmm it looks like that PR creates the settlement button using the constructor, it didn't necessarily introduce the bug

Thanks everyone! Just saw the comment, but I am not sure we should post on PRs unless the PR caused a regression (especially if they are a year old).

**thought/feedback:** Let's go the extra mile and try help the PR authors and reviewers learn from some apparent mistake. If we can't do that in a way that is clear and useful then we should just "do nothing" and check the box. 

>we should be sure that all reusable components react accordingly to any prop updates

Could be more useful if it was actionable. e.g. How do we make sure that this happens? What kinds of prop updates are we talking about? Is it something we can bake into the checklist?

**Comment by jasperhuangg** [comment] 2022-11-22 22:13
@marcaaron honestly that's my bad, [here](https://github.com/Expensify/App/issues/12291#issuecomment-1312002197) I commented "let's go with that PR" but didn't say not to comment or give too much context. I mainly just wanted to link it in [this comment](https://github.com/Expensify/App/issues/12291#issuecomment-1309551962) for posterity.

**Comment by jasperhuangg** [comment] 2022-11-22 22:19
An [example](https://github.com/Expensify/App/issues/12291#issuecomment-1312002197) of "some context", this could definitely be helpful in helping the PR author understand what's going on 

Next time I'll be sure to mention to include any relevant comments as context. 

cc @sakluger

**Comment by jasperhuangg** [comment] 2022-11-22 22:24
> we should sure that all reusable components react accordingly to any prop updates.

Also, when I said this I meant we should go through our current App repo and see if there are any other reusable components that don't update to props like this one. Better to fix them all in one go vs. letting them become discovered as bugs and go through triage.

**Comment by marcaaron** [comment] 2022-11-22 23:16
>see if there are any other reusable components that don't update to props like this one. Better to fix them all in one go vs. letting them become discovered down the road as bugs and go through triage

Cool thanks for the explanation, but just to confirm, are you suggesting we should do an audit of all of our components and fix something about them?

**Comment by jasperhuangg** [comment] 2022-11-23 00:00
@marcaaron yep, or at least do a quick search to see if there are any other components that are written in the same way. I haven't really had the chance to see if there are any that are like this, I was more just thinking off the top of my head. The more I think about it now it's an easy fix, so we don't really need to do anything here.

**Comment by marcaaron** [comment] 2022-11-23 00:30
>do a quick search to see if there are any other components that are written in the same way

Sorry, what way is that? What is it that you think we need to fix about the components?

**Comment by jasperhuangg** [comment] 2022-11-23 21:08
> Honestly, the more I think about it now it's an easy fix, so we don't really need to do anything here.

No need, I was just saying we could maybe go to see if other components are written by accessing props in the constructor. But let's just do nothing for now.

**Comment by mananjadhav** [comment] 2022-11-27 06:44
@jasperhuangg @sakluger Quick bump on the payout here.

**Comment by sakluger** [comment] 2022-11-28 16:56
Hi all, just got back from a long weekend for Thanksgiving holiday and am paying out today.

**Comment by mananjadhav** [comment] 2022-11-28 16:57
Thanks @sakluger. Hope you enjoyed the holidays!

**Comment by sakluger** [comment] 2022-11-28 17:11
Thanks @mananjadhav!

Everyone has now been paid, the contract has been completed, and the Upwork post has been closed.

**Closed by sakluger** 2022-11-28 17:11 UTC
Labels: External, Daily, Improvement, Awaiting Payment, Bug
