### ISSUE TITLE
[HOLD for payment 2023-09-29] [$1000]  Android - Sign in background image is missing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26069] opened 2023-08-28 11:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Sign out if you are signed in
## Expected Result: 
There is a background image
## Actual Result: 
No background image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot_1692336848](https://github.com/Expensify/App/assets/43996225/1d2fe311-6d09-4dab-9dcd-fb4e6c0c5a5d)

https://github.com/Expensify/App/assets/43996225/3e8fcb0a-1a44-4e62-8f69-31d657e62de6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692337365083379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad21987d10429685</li>
        <li>Upwork Job ID: 1696343238604079104</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 26515059</li>
<li>bernhardoj | Reporter | 26515062</li>
</ul></li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-08-29 02:01
Also, on the Android app, you can scroll down - this definitely looks off. Not sure what's happening here, I've never seen this before:

![Screenshot_20230829-115954](https://github.com/Expensify/App/assets/30815269/c2f58820-e6b4-4d7e-ac90-47213c31dadc)

**Comment by jliexpensify** [comment] 2023-08-29 02:06
Wow sorry, huge delays from GH! Removed Miroslav, sorry!

**Comment by mananjadhav** [comment] 2023-08-29 05:01
I am afk, but I'll have these reviewed later today.

**Comment by mananjadhav** [comment] 2023-08-29 07:21
@hoangzinh's proposal looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by jliexpensify** [comment] 2023-08-31 22:41
Not overdue, waiting on @roryabraham 's approval for [this](https://github.com/Expensify/App/issues/26069#issuecomment-1696905449)

**Comment by jliexpensify** [comment] 2023-09-05 00:10
Bump @roryabraham [for C+ review](https://github.com/Expensify/App/issues/26069#issuecomment-1696905449)

**Comment by roryabraham** [comment] 2023-09-05 20:55
Going to reduce the bounty here to the new standard because this is a very simple / relatively low-value issue. I think we can still honor the original reporting bonus but since nobody has been hired here I think it's fair to reduce the bounty.

**Comment by roryabraham** [comment] 2023-09-05 21:06
Actually, I changed my mind. When we made the announcement we said it wouldn't affect existing jobs so I'll set this back to $1000

**Comment by jliexpensify** [comment] 2023-09-07 04:41
@hoangzinh - I'll handle payments and will do a payment summary before any payouts, so this will be manually adjusted later.

**Comment by mananjadhav** [comment] 2023-09-07 20:19
PR Reviewed and approved. I am not sure if we want to merge this within the merge freeze.

**Comment by jliexpensify** [comment] 2023-09-07 23:08
It's probably up to the discretion of @roryabraham as the Engineer, but I would imagine not, as it's not related to SmartScan or distance requests.

**Comment by jliexpensify** [comment] 2023-09-25 04:17
Payment Summary:

- Bug Reporter: @bernhardoj $250
- Contributor: @hoangzinh $1000 
- C+: @mananjadhav $1000

[Upwork job](https://www.upwork.com/jobs/~01ad21987d10429685)

@roryabraham - we're not penalising anyone due to the merge freeze right?

**Comment by roryabraham** [comment] 2023-09-26 05:05
Correct, no penalties here

**Comment by jliexpensify** [comment] 2023-10-02 06:31
Sorry everyone! I was OOO, paying now.

**Comment by jliexpensify** [comment] 2023-10-02 06:34
Paid out in Upworks and closed the job.

@mananjadhav still awaiting for you to complete the checklist, thanks!

**Comment by mananjadhav** [comment] 2023-10-02 14:28
We added the component in this [PR](https://github.com/Expensify/App/pull/21745). I've added a comment [here](https://github.com/Expensify/App/commit/d28b63ceccc2041f86d6135a0023161d98aecc7b#r128911124).

But I don't think we need a regression test here.

**Comment by jliexpensify** [comment] 2023-10-03 03:33
Cool, closing this one - @mananjadhav [here is the payment summary](https://github.com/Expensify/App/issues/26069#issuecomment-1732880470)

**Closed by jliexpensify** 2023-10-03 03:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:57
$1,000 payment approved for @mananjadhav based on BZ summary.
