### ISSUE TITLE
[HOLD #32800] [$500] Compose Box - User is able to access compose box while side panel is open

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34139] opened 2024-01-09 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a workspace with an IOU
2. Click on the IOU preview component
3. Click on the tab button on keyboard multiple times until it reaches the compose box
4. Type anything and send

## Expected Result:
User should not be able to access compose box while side panel is open

## Actual Result:
User is able to type and send messages while side panel is open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/777033a4-c4d4-40a0-97d6-b517d6d0fc31

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f05f042b5d4262d</li>
        <li>Upwork Job ID: 1744720652723343360</li>
        <li>Last Price Increase: 2024-03-26</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-01-09 14:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Compose Box - User is able to access compose box while side panel is open

### What is the root cause of that problem?
We do not block disable compose when sidebar is open
### What changes do you think we should make in order to solve the problem?
We should make compose disabled when sidebar is open

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-09 16:31
I think we should hold this for https://github.com/Expensify/App/pull/32800

**Comment by situchan** [comment] 2024-01-30 16:15
still on hold

**Comment by isabelastisser** [comment] 2024-02-07 16:10
On hold, Melvin!

**Comment by isabelastisser** [comment] 2024-03-06 15:31
Still on hold!

**Comment by isabelastisser** [comment] 2024-03-18 17:50
On hold.

**Comment by isabelastisser** [comment] 2024-04-02 01:14
I reviewed this issue again and decided to close it because this is not a high enough priority. Allowing users to type in the compose box while the side panel is open shouldn't be considered a bug. Why do we need to prevent users from accessing the compose box while looking into other users' emails?

**Closed by isabelastisser** 2024-04-02 01:14 UTC
Labels: External, Monthly, Help Wanted, Bug
