### ISSUE TITLE
[$250] Pay someone - Chat shows green dot in LHN after sending money (Pay someone)

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41082] opened 2024-04-26 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Pay someone.
3. Enter amount and select someone.
4. Pay the money.

## Expected Result:
The chat will not show green dot in LHN.

## Actual Result:
Chat shows green dot in LHN after sending money (Pay someone).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/79d2783e-e485-4ad4-ae81-595ce752f0d9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d69b7e111b56a4ad</li>
        <li>Upwork Job ID: 1783871512964751360</li>
        <li>Last Price Increase: 2024-05-10</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-26 10:50
We think this issue might be related to the #collect project.

**Comment by twisterdotcom** [comment] 2024-04-26 14:52
May be related to https://github.com/Expensify/App/issues/39447. cc @roryabraham

**Comment by twisterdotcom** [comment] 2024-04-29 20:10
Still awaiting proposals. @Ollyws or @roryabraham or @abdulrahuman5196 - do we think this is a dupe of https://github.com/Expensify/App/issues/39447?

**Comment by twisterdotcom** [comment] 2024-05-03 12:12
Okay, well, still waiting on proposals anyway.

**Comment by twisterdotcom** [comment] 2024-05-14 12:58
I can't recreate this anymore.

**Closed by twisterdotcom** 2024-05-14 12:58 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
