### ISSUE TITLE
[$500] Deleted IOU on Empoyee's Workspace chat shows "Currency 0.00" on IOU Card

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36260] opened 2024-02-09 16:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. As employee navigate to Workspace chat
2. Tap on +> Request money> Scan> Finish the flow
3. Navigate to Scan request while still scanning> Long press> Delete request
## Expected Result:
There should be Deleted card displayed on Employee's Workspace chat

## Actual Result:
Deleted IOU on Employee's Workspace chat does not disappear. It shows "Currency 0.00" on IOU Card

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2d660222-d6dd-4b99-95e2-6ee2137df23e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3fccfc31b6291f5</li>
        <li>Upwork Job ID: 1755990221489430528</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by deetergp** [comment] 2024-02-09 20:28
I am not able to reproduce this in `main`

**Comment by deetergp** [comment] 2024-02-09 21:42
I wasn't able to reproduce it on `1.4.39-0` either.

**Comment by deetergp** [comment] 2024-02-09 23:05
Three testers and I were not able to reproduce this so I'm going to close it. https://expensify.slack.com/archives/C9YU7BX5M/p1707514998641789

**Closed by deetergp** 2024-02-09 23:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
