### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] IOU-In distance request, after selecting start waypoint finish section disappears

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29748] opened 2023-10-17 10:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team and by @rakshitjain13 [via Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1697268905255679)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697268905255679

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money --- Distance
4. Note "Start" and "Finish" section are displayed
5. Tap start and select a start waypoint

## Expected Result:
In distance request, after selecting start waypoint finish section must not disappear.

## Actual Result:
In distance request, after selecting start waypoint finish section disappears.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/2e49c7a8-6857-4bbe-9b20-6ccf1266f834

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e50d142f42c98aba</li>
        <li>Upwork Job ID: 1714227569034670080</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 27245087</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-17 10:32
Not reproducible on production

https://github.com/Expensify/App/assets/115492554/dabd2479-7b42-4170-972a-44e7770dead3

**Comment by conorpendergrast** [comment] 2023-10-17 10:56
I have reproduced this on Staging (not on Production) which makes this a deploy blocker 👍

**Comment by conorpendergrast** [comment] 2023-10-17 11:00
Just noting that this was also [reported via Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1697521330802799), before this issue, by @ tewodrosGirmaA.

**Comment by ayazalavi** [comment] 2023-10-17 11:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Only start waypoint exists once we select start location in request money->distance

### What is the root cause of that problem?
The root cause exists when we add a new waypoint. By default, there are 2 waypoints: waypoint0 = {} and waypoint1 = {}. Therefore, both the start and finish points are displayed. However, once we add a real waypoint, only waypoint0 exists, causing this bug.

### What changes do you think we should make in order to solve the problem?
Update this line of code 

https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/components/DistanceRequest/index.js#L76

with 

```
 const waypointsTransaction = useMemo(() => optimisticWaypoints || lodashGet(transaction, 'comment.waypoints', { waypoint0: {}, waypoint1: {} }), [optimisticWaypoints, transaction]);
    const waypoints = useMemo(() => _.keys(waypointsTransaction).length > 1 ? waypointsTransaction : { ...waypointsTransaction, waypoint1: {} } , [waypointsTransaction]);
```
  
### What alternative solutions did you explore? (Optional)
N/A

**Comment by alitoshmatov** [comment] 2023-10-17 11:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU-In distance request, after selecting start waypoint finish section disappears

### What is the root cause of that problem?
This issue is happening because we are setting default waypoint values as `null` here: 
https://github.com/Expensify/App/blob/c22638482bb12ccfa9237f09e8fabf9680c2d965/src/libs/actions/Transaction.ts#L35-L36
Initially onyx is storing this values without a problem. But when `start` waypoint is selected, we are updating onyx with new `waypoint0`:
https://github.com/Expensify/App/blob/c22638482bb12ccfa9237f09e8fabf9680c2d965/src/libs/actions/Transaction.ts#L65-L67

But after this update onyx is removing any keys with `null` value. Resulting in single waypoint. As stated here, any keys with `null` values are removed:
https://github.com/Expensify/react-native-onyx/blob/e7639af31b5f09629579ed906fecd3d779dc79ee/lib/Onyx.js#L1205-L1208


### What changes do you think we should make in order to solve the problem?
I think we should provide default empty values in waypoints as `{}`(empty object) rather than `null` value in here:
https://github.com/Expensify/App/blob/c22638482bb12ccfa9237f09e8fabf9680c2d965/src/libs/actions/Transaction.ts#L35-L36
Also here
https://github.com/Expensify/App/blob/835ecf78b486b313061842076007c0f764891d9f/src/components/DistanceRequest/index.js#L173

### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-10-17 13:46
Noting that there was [an earlier report of this via Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1697268905255679), by @rakshitjain13, for the bug bounty.

**Comment by Pujan92** [comment] 2023-10-17 14:15
Seems a regression from https://github.com/Expensify/App/pull/26307 where null has been assigned in the `createInitialWaypoints`, earlier it was `{}` cc: @kosmydel 
 
https://github.com/Expensify/App/blob/12d366931012b0092b924b688924726930398ac4/src/components/DistanceRequest/index.js#L76

Initially as `optimisticWaypoints` is null it will consider and assign an empty object based on 2nd condition. Once any waypoint updates the `optimisticWaypoints` gets updated and then the issue persists because null values prop will be removed in onyx.

**Comment by neil-marcellini** [comment] 2023-10-17 17:12
@alitoshmatov thank you for your [proposal](https://github.com/Expensify/App/issues/29748#issuecomment-1766237652), I think it explains the root cause very well. The initial empty waypoints shouldn't be set to null, so I think @Pujan92 correctly identified one source of the regression in [this comment](https://github.com/Expensify/App/issues/29748#issuecomment-1766511326). However, I also think a change in Onyx might be an additional and more true source of the regression, because I think it was working for a while after the draggable list PR.

If a nested object is merged in Onyx will all fields as null, then it should not be set at all.

**Comment by neil-marcellini** [comment] 2023-10-17 17:17
I'm checking to see if @alitoshmatov is around to implement his proposal. If he doesn't get back to me in 30 minutes I'll implement the fix myself.

**Comment by alitoshmatov** [comment] 2023-10-17 17:25
@neil-marcellini Yes, I am available right now

**Comment by ayazalavi** [comment] 2023-10-17 17:27
You can respond to the reviewer with the following explanation:

@neil-marcellini,

Thank you for your feedback and question regarding the root cause for the current state of my proposal. I appreciate your engagement in this matter. 

The issue you raised is related to the "saveWaypoint" callback, which is responsible for saving new waypoints. As it stands, this callback is overwriting the previous data with the new waypoint. Consequently, only "waypoint0" is left in the dataset, and previous waypoints, such as "waypoint1," are being wiped out.

https://github.com/Expensify/App/blob/332ddc49d2ed62a08ceadaceb6a056c24c06de71/src/libs/actions/Transaction.ts#L59

To address this issue, we need to implement a solution that ensures waypoints are kept in the dataset until we have less than two waypoints. This way, we won't unintentionally overwrite existing waypoints, and we can maintain a history of waypoints in the dataset.

I will work on implementing this change to ensure that all waypoints are preserved.

**Comment by Pujan92** [comment] 2023-10-17 17:29
I am seeing onyx version upgradation PR [here](https://github.com/Expensify/App/pull/28894) recently

**Comment by alitoshmatov** [comment] 2023-10-17 18:08
PR is ready - https://github.com/Expensify/App/pull/29811

**Comment by rakshitjain13** [comment] 2023-10-17 18:43
@conorpendergrast I think, I should be eligible for Reporter Role https://expensify.slack.com/archives/C049HHMV9SM/p1697268905255679

**Comment by conorpendergrast** [comment] 2023-10-17 18:48
@rakshitjain13 To make sure I get your Upwork account correctly, can you apply directly for [the job](https://www.upwork.com/jobs/~01e50d142f42c98aba)?

**Comment by rakshitjain13** [comment] 2023-10-17 19:01
@conorpendergrast Applied

**Comment by conorpendergrast** [comment] 2023-10-17 19:08
[Contract](https://www.upwork.com/nx/wm/workroom/35167161/overview) sent for the reporter role, thanks!

**Comment by neil-marcellini** [comment] 2023-10-17 22:12
Cherry pick requested [here](https://expensify.slack.com/archives/C07J32337/p1697580708051749)

**Comment by neil-marcellini** [comment] 2023-10-24 17:30
Bump @Santhosh-Sellavel please fill out the checklist

**Comment by alitoshmatov** [comment] 2023-10-25 09:32
Looks like this one is ready for payment

**Comment by conorpendergrast** [comment] 2023-10-25 13:45
Payouts due:

- [x] Issue Reporter: $50 @rakshitjain13
- [x] Contributor: $500 + 50% urgency bonus = $750 @alitoshmatov 
Contributor+: $500 + 50% urgency bonus = @Santhosh-Sellavel (via Manual Request)

Eligible for 50% #urgency bonus? Yes

Upwork job is [here](https://www.upwork.com/ab/applicants/1714227569034670080/job-details).

**Comment by conorpendergrast** [comment] 2023-10-25 13:46
Just waiting for [the checklist](https://github.com/Expensify/App/issues/29748#issuecomment-1769590619) by @Santhosh-Sellavel

**Comment by conorpendergrast** [comment] 2023-10-27 15:14
Bump for the checklist please @Santhosh-Sellavel !

**Comment by alitoshmatov** [comment] 2023-10-27 17:04
@conorpendergrast If I remember correctly @Santhosh-Sellavel said he wouldn't be online for couple of days in C+ channel. Could not verify it since I lost access to the channel

**Comment by Santhosh-Sellavel** [comment] 2023-10-29 13:03
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/26307
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/26307/files#r1375432954
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A should be caught will testing.
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. As it's also reported by applause we should have this covered internally tests
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [x]  [@conorpendergrast] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-10-30 13:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:14
$750 payment approved for @Santhosh-Sellavel based on [this comment](https://github.com/Expensify/App/issues/29748#issuecomment-1779313812).
