### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] iOS - BA - Confirm button on double check pages is closer to the bottom than other pages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37339] opened 2024-02-27 18:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37025

## Action Performed:
Pre-requisite: the user must be logged in and have created a workspace.
1. Go to Workspace > Bank account.
2. Initiate the add bank account flow until you reach a double check page (for account selection, personal information, company information)
3. Verify the Confirm button is displayed closer to the button than the other pages.

## Expected Result:
The Confirm button should be displayed on the same place as the other pages.

## Actual Result:
The Confirm button is displayed closer to the button than the other pages.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/cb7ea3ac-024a-4ea3-9adc-2553bcb66c38)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9093a007c21da81</li>
        <li>Upwork Job ID: 1764463270160367616</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 18:58
@bfitzexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-03-03 17:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The bank info confirmation button is too close at the button compared to other page.

### What is the root cause of that problem?
The bank info page is wrapped with a screen wrapper that disables `includeSafeAreaPaddingBottom` because it contains a form which already has it,
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L134-L137

except for confirmation sub step because it just uses a plain scroll view.
https://github.com/Expensify/App/blob/22cb01c968a53407f7a9d864bfba30f41366f6a0/src/pages/ReimbursementAccount/BankInfo/substeps/Confirmation.tsx#L49-L51

This also happens to other bank account confirmation sub step (personal info confirmation, business info confirmation, etc.).

### What changes do you think we should make in order to solve the problem?

We should enable `includeSafeAreaPaddingBottom` when the page requires it, that is the confirmation page. There are many ways to do it, but some examples are:
- wrap each page with `SafeAreaConsumer` to get the `safeAreaPaddingBottomStyle` and apply it to the root view.
```js
<SafeAreaConsumer>
    {({safeAreaPaddingBottomStyle}) => (
        <ScrollView ... contentContainerStyle={[..., safeAreaPaddingBottomStyle]}>
```
- in the parent step component, enable `includeSafeAreaPaddingBottom` if the sub step is the confirmation step 
```js
includeSafeAreaPaddingBottom={SubStep === Confirmation}
```
- assuming the confirmation page is always at the last page, we can enable `includeSafeAreaPaddingBottom` if the sub step index is the last item
```js
includeSafeAreaPaddingBottom={screenIndex === manualSubsteps.length - 1}
```
- enrich the sub step component array by adding `includeSafeAreaPaddingBottom` property to it.
```js
const manualSubsteps = [{component: Manual}, {component: Confirmation, includeSafeAreaPaddingBottom: true}];
...
includeSafeAreaPaddingBottom={!!SubStep.includeSafeAreaPaddingBottom}
...
<SubStep.Component
```

**Comment by bfitzexpensify** [comment] 2024-03-04 01:30
Yes, definitely something we want to fix. @Ollyws, looks like we have a couple of proposals already ready for review

**Comment by scriptprojectsdev** [comment] 2024-03-04 05:57
## Proposal

### Problem:
The "Confirm" button at the bottom of the screen  is not at the same height as other buttons for other sub steps

### Cause of the problem:
The issue is that this confirmation page is missing the `SafeAreaConsumer` that provides the proper padding for the bottom. Since the other steps are forms the `SafeAreaConsumer` is included in that making the other screens behave correctly.

### Solution:
Add the `SafeAreaConsumer` to this screen to make it behave the same as other screens. There may be other screens that also don't have a form and display the bottom button in the wrong place. The solution should be applied to those screens as well.

**Comment by scriptprojectsdev** [comment] 2024-03-05 01:16
Contributor details
Your Expensify account email: erick@scriptprojects.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c16575c840ed0ce7

**Comment by arosiclair** [comment] 2024-03-06 14:51
> I think it's best we go with the `SafeAreaConsumer` solution.

This sounds good to me too

**Comment by arosiclair** [comment] 2024-03-06 14:55
Weird those failed. You know anything about it @bfitzexpensify? Maybe ask in `#bug-zero`?

**Comment by bernhardoj** [comment] 2024-03-07 08:43
PR is ready

cc: @Ollyws

**Comment by bfitzexpensify** [comment] 2024-03-21 11:13
@Ollyws & @bernhardoj - in Upwork, I'm seeing that the offer for this job has been sent to both of you and is awaiting acceptance, but given [this comment](https://github.com/Expensify/App/issues/37339#issuecomment-1981043700), I suspect that that might not be correct. 

Job name is [$500] iOS - BA - Confirm button on double check pages is closer to the bottom than other pages #37339 - do you both have an Upwork offer tied to that?

**Comment by bernhardoj** [comment] 2024-03-21 11:15
We received the offer but can't accept it.
<img width="715" alt="image" src="https://github.com/Expensify/App/assets/50919443/a320f9f3-600c-4d30-b1df-09b2ae4324e7">

**Comment by bfitzexpensify** [comment] 2024-03-21 12:09
Gotcha. I've re-sent the offers, let me know if they're working or not. I might need to recreate the job fully if they aren't.

**Comment by bernhardoj** [comment] 2024-03-21 12:16
It works, accepted

**Comment by bfitzexpensify** [comment] 2024-03-22 17:20
Cool, payments complete, regression steps proposed in https://github.com/Expensify/Expensify/issues/381507, closing this out - thanks everyone.

**Closed by bfitzexpensify** 2024-03-22 17:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
