### ISSUE TITLE
[HOLD for payment 2024-01-31] [$500] Mention - Only 3 user are scrollable when use keyboard to pick user to mention

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33613] opened 2023-12-26 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal
**Slack conversation:**

## Action Performed:
Precondition:
Connect the pc keyboard to mobile device
Steps:
1. Navigate to staging.new.expensify.com
2. Go to any chat
3. Start texting until chat is expanded
4. Type @ to open mention member list
5. Use keyboard arrows to scroll through the list

## Expected Result:
User should be able to navigate to all members in the list

## Actual Result:
When using keyboard arrows user is able to scroll only 3 members from the list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/899f29ce-d7ac-4f84-a735-4cf813ff5d99

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017bdddeb3dc37e5c7</li>
        <li>Upwork Job ID: 1739721691952898048</li>
        <li>Last Price Increase: 2024-01-09</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 28095701</li>
</ul></li>
    </ul>
</details>

**Comment by rrrshtt** [comment] 2023-12-26 20:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Suggestions stacked in 3 items with keyboard control.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2b58e1cbef63c4fdce8a6e8fb3ee52089009a8d8/src/libs/SuggestionUtils.js#L9
https://github.com/Expensify/App/blob/2b58e1cbef63c4fdce8a6e8fb3ee52089009a8d8/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L62C9-L62C17
The entire `function getMaxArrowIndex()` is incorrect for this purpose since it's a keyboard controller.

### What changes do you think we should make in order to solve the problem?
We can simply use the length of suggested mentions in the keyboard controller because we only need the total number of items in the hook.

**Comment by rrrshtt** [comment] 2023-12-26 20:44
Contributor details
Your Expensify account email: mrishat03@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012f657c01285b6cf0

**Comment by bfitzexpensify** [comment] 2023-12-28 15:53
Couple of proposals ready for review, thanks @eVoloshchak

**Comment by bfitzexpensify** [comment] 2024-01-02 16:30
Assuming @eVoloshchak was off for the holidays, this isn't an urgent issue

**Comment by bfitzexpensify** [comment] 2024-01-08 12:54
@eVoloshchak this one is ready for proposal review - thank you

**Comment by bfitzexpensify** [comment] 2024-01-10 19:08
Bump here @eVoloshchak

**Comment by bfitzexpensify** [comment] 2024-01-11 16:59
I'm going to be mostly ooo until Jan 29, assigning a second BZ team member to keep an eye on this.

- waiting for proposal review
- I've tagged @eVoloshchak in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1704992337387639) - we might need to find another C+

**Comment by eVoloshchak** [comment] 2024-01-11 19:11
> So replace this line with maxIndex: suggestionValues.suggestedMentions.index - 1

@mkhutornyi, using `suggestionValues.suggestedMentions.index` looks like a typo, I think you meant `.length`, is that correct?
There's no index key in an Array and using `.index` disables keyboard navigation, while using `.length` is the correct approach
I think we should proceed with @mkhutornyi's [proposal](https://github.com/Expensify/App/issues/33613#issuecomment-1869728452) (assuming we use .length)

🎀👀🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment] 2024-01-15 16:07
@mkhutornyi Any updates? Thanks!

**Comment by CortneyOfstad** [comment] 2024-01-22 14:36
@eVoloshchak any update on the PR above^^^ thanks!

**Comment by eVoloshchak** [comment] 2024-01-23 21:17
PR has been merged

**Comment by CortneyOfstad** [comment] 2024-01-31 18:16
## Payment Summary

@mkhutornyi (Contributor) — paid $500 via Upwork
@eVoloshchak (C+) — to be paid $500 via New Dot

**Comment by CortneyOfstad** [comment] 2024-01-31 18:17
@eVoloshchak any update on the checklist above? Thanks!

**Comment by CortneyOfstad** [comment] 2024-02-01 19:45
@eVoloshchak just bumping on the checklist so we can get this closed. Thanks!

**Comment by eVoloshchak** [comment] 2024-02-03 16:44
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25758
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25758/files#r1477093662
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this is a very minor bug
- Determine if we should create a regression test for this bug.
Is it easy to test for this bug? No, this requires an Android device with a physical keyboard connected to test
Is the bug related to an important user flow? No
Is it an impactful bug? No
We don't need a regression test here, the bug is rare and isn't impactful, and it might be hard for QA to test

**Comment by eVoloshchak** [comment] 2024-02-03 17:19
Requested the payment

**Comment by JmillsExpensify** [comment] 2024-02-03 18:29
$500 approved for @eVoloshchak based on summary above.

**Comment by CortneyOfstad** [comment] 2024-02-05 14:05
Thanks all!

**Closed by CortneyOfstad** 2024-02-05 14:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
