### ISSUE TITLE
[HOLD for payment 2024-10-16] [$75] Migrate withReportAndReportActionOrNotFound from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49107] opened 2024-09-12 17:33 UTC
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/home/report/withReportAndReportActionOrNotFound.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834284196116549816</li>
        <li>Upwork Job ID: 1834284196116549816</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103949139</li>
<li>BhuvaneshPatil | Contributor | 103949140</li>
<li>etCoderDysto | Contributor | 103949404</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by BhuvaneshPatil** [comment] 2024-09-12 17:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migration of `withOnyx` to `useOnyx`

### What is the root cause of that problem?
Migration

### What changes do you think we should make in order to solve the problem?
Remove this lines and corresponding prop types.

https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportAndPrivateNotesOrNotFound.tsx#L93-L99

We shall convert it to `useOnyx` hook.
```
const [session] = useOnyx(ONYXKEYS.SESSION)
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-09-12 17:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate withReportAndReportActionOrNotFound from withOnyx to useOny
### What is the root cause of that problem?
Migration 
### What changes do you think we should make in order to solve the problem?
replace the following props with useOnyx
https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportAndReportActionOrNotFound.tsx#L105-L128

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2024-09-12 18:57
Does it need to be attached to a project?

I'd say this isn't strictly related to the TypeScript Migration

**Comment by slafortune** [comment] 2024-09-12 19:45
@roryabraham yes, a project/wave/VIP needs to be applied - so the one that suits it best should be selected

**Comment by BhuvaneshPatil** [comment] 2024-09-13 03:07
@hoangzinh Do we need proposal here? Like we did for typescript migration, who ever comments first is assigned to issue.
Because there is no bug or new addition that's being done.

**Comment by etCoderDysto** [comment] 2024-09-13 16:34
Hi @roryabraham my propsoal was selected here https://github.com/Expensify/App/issues/49107#issuecomment-2347894736

**Comment by roryabraham** [comment] 2024-09-13 16:42
reassigning to @etCoderDysto since @BhuvaneshPatil is the only person who was assigned to two migrations. Now everyone just has one

**Comment by etCoderDysto** [comment] 2024-09-13 16:43
> reassigning to @etCoderDysto since @BhuvaneshPatil is the only person who was assigned to two migrations. Now everyone just has one

Thank you!

**Comment by etCoderDysto** [comment] 2024-09-13 16:47
PR will ready for review soon.

**Comment by etCoderDysto** [comment] 2024-09-16 18:32
I am working on the PR

**Comment by etCoderDysto** [comment] 2024-09-19 08:11
> @etCoderDysto How is it going with the PR?

It is almost finished. I am working on fixing some type errors.

**Comment by etCoderDysto** [comment] 2024-09-19 15:10
[PR](https://github.com/Expensify/App/pull/49460) is ready for review

**Comment by roryabraham** [comment] 2024-10-04 23:24
@thienlnam is going to help out here while I'm on parental leave

**Comment by slafortune** [comment] 2024-10-17 18:55
@hoangzinh can you please complete the checklist?

**Comment by slafortune** [comment] 2024-10-18 17:56
@hoangzinh Role C+ paid $75 via Upwork
@etCoderDysto Role Contributor paid $75 via Upwork

**Closed by slafortune** 2024-10-18 17:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
