### ISSUE TITLE
[$250] [Guided Setup] Fix subject lines in emails sent upon onboarding modal completion 

### ISSUE THREAD

**Issue by MitchExpensify** [Expensify/App#39966] opened 2024-04-09 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-13
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** na
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** mitch@expensify.com
**Slack conversation:** Internal: https://expensify.slack.com/archives/C036QM0SLJK/p1712608278412419

## Action Performed:
1. Sign up to staging.new.expensify.com
2. Go to staging.new.expensify.com/onboarding
3. Enter first name and last name go, click "Continue" on the onboarding modal
4. Click any of these options:
- Manage my team’s expenses
- Track business spend for taxes
- Track and budget personal spend
5. Click Continue 
6. Check your email 

## Expected Result:

The custom subject line should not contain "&#x27;" wherever a "'" should be.

e.g:

- Track business spend for taxes: "Welcome to Expensify, let&#x27;s start tracking your expenses!"
- Manage my team’s expenses: "Welcome to Expensify, let&#x27;s start managing your team&#x27;s expenses!"
- Track and budget personal spend: "Welcome to Expensify, let&#x27;s start tracking your expenses!"

## Actual Result:

Custom subject lines contain erroneous characters wherever a "'" should be:

- Track business spend for taxes: "Welcome to Expensify, let&#x27;s start tracking your expenses!"
- Manage my team’s expenses: "Welcome to Expensify, let&#x27;s start managing your team&#x27;s expenses!"
- Track and budget personal spend: "Welcome to Expensify, let&#x27;s start tracking your expenses!"

## Workaround:
Ignore 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img width="1091" alt="Screenshot 2024-04-08 at 1 25 25 PM" src="https://github.com/Expensify/App/assets/36425901/07a7dac4-d198-4ba9-8924-5d2a1a207b9a">

<img width="1112" alt="Screenshot 2024-04-08 at 1 30 29 PM" src="https://github.com/Expensify/App/assets/36425901/1b8f79f7-0f40-46dd-af38-b92e84825d78">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01697f68b79fde14d3</li>
        <li>Upwork Job ID: 1778159532698587136</li>
        <li>Last Price Increase: 2024-04-10</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by filip-solecki** [comment] 2024-04-09 20:42
Hi! I am Filip from SWM an expert agency and I'd like to work on this issue!

**Comment by brkdavis** [comment] 2024-04-10 03:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Single quotes and some special characters are not escaped from report comment text (which goes in the email)

### What is the root cause of that problem?
`reportComment ` is escaped and fetched in function. However this escaping used `ExpensiMark` from `expensify-common` lib. 


```
function completeEngagementModal(text: string, choice: ValueOf<typeof CONST.ONBOARDING_CHOICES>) {
    . . . 
    const reportComment = ReportUtils.buildOptimisticAddCommentReportAction(text, undefined, conciergeAccountID);
    const reportCommentAction: OptimisticAddCommentReportAction = reportComment.reportAction;
    const lastComment = reportCommentAction?.message?.[0];
    const lastCommentText = ReportUtils.formatReportLastMessageText(lastComment?.text ?? '');
```

Object `optimisticReport` is filled with `lastCommentText` for both text as well as formatted html.
```
        lastMessageText: lastCommentText,
        lastMessageHtml: lastCommentText,
```

`ReportUtils.formatReportLastMessageText()` uses `ExpensiMark` parser from `expensify-common` lib, which uses underscore package to escape html content and does not take into consideration escaping of single quote. This results in single quote in JSON body being replaced with its equivalent escape string while sending email. 

### What changes do you think we should make in order to solve the problem?
`ReportUtils.getParsedComment()` function to escape single quote using `lodash` irrespective of length of the string.
```
    return text.length <= CONST.MAX_MARKUP_LENGTH ? lodashEscape(parser.replace(textWithMention, {shouldEscapeText: !shouldAllowRawHTMLMessages()})) : lodashEscape(text);
```

### What alternative solutions did you explore? (Optional)
Another alternative is to update `ExpensiMark` lib in `expensify-common` to use a package like lodash to escape special characters.

**Comment by brkdavis** [comment] 2024-04-10 03:09
Contributor details
Your Expensify account email: [brkdavis890@gmail.com](mailto:brkdavis890@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01063aad97ce0e22c6

**Comment by brkdavis** [comment] 2024-04-10 03:10
Contributor details
Your Expensify account email: brkdavis890@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01063aad97ce0e22c6

**Comment by jliexpensify** [comment] 2024-04-10 03:11
Hi @brkdavis - I believe that this issue is now assigned to @filip-solecki to work on!

**Comment by brkdavis** [comment] 2024-04-10 03:14
@jliexpensify : Sorry. I didnt see a proposal on this. Out of curiosity investigated and submitted my findings in the proposal. 
@filip-solecki : If you don't mind, I can pick this work, if my proposal is accepted.

**Comment by brkdavis** [comment] 2024-04-10 03:23
Contributor details
Your Expensify account email: brkdavis890@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cef163ba3c7ed327

**Comment by mountiny** [comment] 2024-04-10 20:04
No update yet

**Comment by mountiny** [comment] 2024-04-10 20:36
Looking for a quicker movement on this one as the onboarding flow is nearing completion

**Comment by brkdavis** [comment] 2024-04-11 06:22
## Proposal
    [Updated](https://github.com/Expensify/App/issues/39966#issuecomment-2046466019)

**Comment by brkdavis** [comment] 2024-04-11 06:23
> ## Proposal
> [Updated](https://github.com/Expensify/App/issues/39966#issuecomment-2046466019)

@rayane-djouah : can you please confirm the changes?

**Comment by filip-solecki** [comment] 2024-04-11 11:19
In my opinion it should be handled on BE

**Comment by brkdavis** [comment] 2024-04-11 13:26
## Proposal
[Updated](https://github.com/Expensify/App/issues/39966#issuecomment-2046466019)

**Comment by brkdavis** [comment] 2024-04-11 13:29
> ## Proposal
> [Updated](https://github.com/Expensify/App/issues/39966#issuecomment-2046466019)

@rayane-djouah : thank you for detailed look into this. I have updated the proposal. 
I believe frontend definitely needs this fix. 
Attached screenshot from Concierge chat with bolded subject and well escaped text content.
 
In case backend is not handling these correctly, might need a fix there as well.

**Comment by sumitskj** [comment] 2024-04-11 19:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Subject lines of emails after onboarding  modal completion show HTML escaped characters like &#x27;

### What is the root cause of that problem?

The root cause of the problem is that we are using ```ExpensiMark()``` to parse our content to HTML that we want to send in emails. In our current scenario, our message length is less than 10000 characters so it uses  ```ExpensiMark()``` to parse to HTML with the property ```shouldEscapeText``` as ```true```. Due to this, we are converting our message string to HTML something like this.
```
<h1>Welcome to Expensify, let&#x27;s start tracking your expenses!</h1>Hi there, I&#x27;m Concierge. Chat with me here for anything you need.<br /><br />To track your expenses, create a workspace to keep everything in one place. Here&#x27;s how:<br />1. From the home screen, click the green + button &gt; New Workspace<br />2. Give your workspace a name (e.g. &quot;My business expenses”).<br /><br />Then, add expenses to your workspace:<br />1. Find your workspace using the search field.<br />2. Click the gray + button next to the message field.<br />3. Click Request money, then add your expense type.<br /><br />We&#x27;ll store all expenses in your new workspace for easy access. Let me know if you have any questions!

```
Now this message is passed to the API to send mail and I guess there you are just copying the text inside HTML tags as it is without trying to unescape the HTML converted h1 string.

### What changes do you think we should make in order to solve the problem?
Inside the method ```getParsedComment(string)``` of ```ReportUtils.ts``` at the last line when we are returning the our HTML escaped message string, we can substring our message in 2 parts one for the h1 subject content and other for the rest of the message. And for the header we will escape the string with ```ExpensiMark()``` parser with property ```shouldEscapeText``` set to ```false``` and for the rest of the message we will escape the string with ```ExpensiMark()``` parser with property ```shouldEscapeText``` set to ```true```.


Code Changes:

Before :
```
return text.length <= CONST.MAX_MARKUP_LENGTH ? parser.replace(textWithMention, {shouldEscapeText: !shouldAllowRawHTMLMessages()}) : lodashEscape(text);
```
After : 
```
const contentSubject  = textWithMention.substring(text.indexOf('#'), textWithMention.indexOf('\n'));
    const messageData = textWithMention.substring(textWithMention.indexOf('\n'));
    return text.length <= CONST.MAX_MARKUP_LENGTH ? parser.replace(contentSubject, {shouldEscapeText: shouldAllowRawHTMLMessages()}) + parser.replace(messageData, {shouldEscapeText: !shouldAllowRawHTMLMessages()}) : lodashEscape(text);
```
Doing these changes will fix the issue.

Screenshots:
Mail:
<img width="864" alt="image" src="https://github.com/Expensify/App/assets/31140181/18affc61-c590-4a8e-8ac6-171dfe643a36">
Concierge message:
<img width="1113" alt="image" src="https://github.com/Expensify/App/assets/31140181/b61100c1-7d96-4a1a-a524-89c5d04134a3">



### What alternative solutions did you explore? (Optional)

We can also fix this where the code for sending the mail is present i.e. backend. There as well we can have the same logic of fetching the subject and than unescaping the characters that we don't want.

**Comment by sumitskj** [comment] 2024-04-11 19:23
Contributor details
Your Expensify account email: sumitjangirdss.1@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01de4e6fe70d63b1fb

**Comment by sumitskj** [comment] 2024-04-12 07:49
@rayane-djouah You are correct that it might affect other app functionalities as ```buildOptimisticAddCommentReportAction``` is used in many places. 

To handle this we can add an extra parameter ```onboardingFlow``` to ```buildOptimisticAddCommentReportAction(text?: string, file?: FileObject, actorAccountID?: number, onboardingFlow: boolean)``` and also to ```getParsedComment(text: string)```, based on this new parameter we can decide whether we want to use our new logic or not.

Another option can be to create a new method similar to ```buildOptimisticAddCommentReportAction``` just for handling the onboarding flow, and call it from ```completeEngagementModal```, since ```completeEngagementModal``` handles all the onboarding modals.

To make email subjects reusable, we can create a common method which will take the message text as input and can return the messageSubject and messageBody. Something like this

```
function getCommentHeaderAndBody(comment: string) {
    let header = '';
    let body = '';
    if(comment.startsWith('#')){
        header = comment.substring(comment.indexOf('#'), comment.indexOf('\n'));
        body = comment.substring(comment.indexOf('\n'));
        return {header, body}
    }
    return {header, comment};
}
```

**Comment by Gonals** [comment] 2024-04-12 12:11
Looking at this, this is an existing issue for all flows that may have `'` on the subject. I think the way to go is to add a fix on the backend.

**Comment by Gonals** [comment] 2024-04-15 12:27
The PR hasn't deployed yet, so let's wait for a bit

**Comment by danielrvidal** [comment] 2024-04-17 20:51
It looks like the PR was deployed so can we close this one now?

**Comment by Gonals** [comment] 2024-04-18 11:53
Yep!

**Closed by Gonals** 2024-04-18 11:53 UTC
Labels: Daily, Internal, Overdue, Bug
