### ISSUE TITLE
[HOLD for payment 2024-11-20] [Workspace Feeds] Transaction start date in card details page is one day prior to the selected date when assigning a card

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51915] opened 2024-11-01 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation** (hyperlinked to channel name): [quality](https://applause-ts.slack.com/archives/C05LX9D6E07/p1730403046683459)

## Action Performed:
Prerequisite:
Members and company cards added in workspace , 8+ export options for card

1. Go to staging.new.expensify.com
2. Choose the workspace from settings
3. Click company cards >Card Details

## Expected Result:
Transaction start date should be same as entered when assigning the card
## Actual Result:
 Transaction start date in card details page is one day prior to the selected date when assigning a card
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>
![image - 2024-10-31T153107 487](https://github.com/user-attachments/assets/710fa817-5448-4ce5-94ea-fd9e22472f35)
![image - 2024-10-31T153058 517](https://github.com/user-attachments/assets/6500a64c-2b8f-4d69-a82f-7f8cfc613a40)

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by m-natarajan** [comment] 2024-11-01 22:00
BZ team member, Callstack will work on this issue, please wait for them to comment before moving the issue forward.

**Comment by mountiny** [comment] 2024-11-01 22:46
Handling this as part of the project I have worked on

**Comment by waterim** [comment] 2024-11-05 10:10
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by DylanDylann** [comment] 2024-11-05 10:18
I would love to help on this issue with @waterim

**Comment by waterim** [comment] 2024-11-06 21:46
Still investigating, couldnt reproduce

**Comment by DylanDylann** [comment] 2024-11-07 09:07
I also can't reproduce

**Comment by mountiny** [comment] 2024-11-07 09:42
Joe is in nee york timezone

**Comment by waterim** [comment] 2024-11-07 13:08
@mountiny probably should work with removing new Date converting all the time, cant reproduce
@joekaufmanexpensify feel free to reproduce!

**Comment by joekaufmanexpensify** [comment] 2024-11-07 13:36
I can still reproduce. Added [here. ](https://expensify.slack.com/archives/C05LX9D6E07/p1730986236078299?thread_ts=1728966082.429659&cid=C05LX9D6E07)

**Comment by DylanDylann** [comment] 2024-11-07 14:40
@waterim This issue only can be reproduced when we set Local time is 8:30 am and EST timezone (GMT -5). The problem comes from the format function

<img width="1135" alt="Screenshot 2024-11-07 at 08 39 01" src="https://github.com/user-attachments/assets/3d349146-bed0-4948-a271-1a56ab7b386c">

**Comment by DylanDylann** [comment] 2024-11-07 14:54
I suggest updating 

https://github.com/Expensify/App/blob/b7a9c9b19f81e344e13267882cf8d0b30d98199c/src/pages/workspace/companyCards/WorkspaceCompanyCardDetailsPage.tsx#L162

```
title={card?.scrapeMinDate ? format(parseISO(card.scrapeMinDate), CONST.DATE.FNS_FORMAT_STRING) : ''}

```

**Comment by waterim** [comment] 2024-11-08 00:53
Thank you, will try tomorrow morning, maybe format from date-fns-tz

**Comment by MitchExpensify** [comment] 2024-11-12 23:55
@waterim Have you had a chance to come back to this?

**Comment by DylanDylann** [comment] 2024-11-19 02:33
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by mountiny** [comment] 2024-11-20 10:14
Checklist done, regression test for this specific scenario is not needed I think, it will be covered with the tests for the feature we will add with Joe. Payments are handled separately for the project so closing this one for now

**Closed by mountiny** 2024-11-20 10:14 UTC
Labels: Daily, Needs Reproduction, Awaiting Payment, Bug, AutoAssignerNewDotQuality
