### ISSUE TITLE
Chat - Flagging thread root message results in "This page cannot be found"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23264] opened 2023-07-20 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22831
## Action Performed:
1. Open Desktop app
2. Open chat
3. Hover over a message that was sent by a different user
4. Click on "Reply in thread"
5. Hover over the same root message from step 3
6. Click on "Flag as offensive"

## Expected Result:
User is presented with different options to flag the message as offensive

## Actual Result:
User is presented with an error - "Hmm... it's not here Oops, this page cannot be found".
Issue is not reproducible for thread root message if flag the message from chat view or if flag message other than root in thread view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ce92cd09-2c66-4717-9310-aefc79929d7b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by s-alves10** [comment] 2023-07-20 13:02
Not reproducible. I can see the header [Deleted message] in the video. What does that mean?

**Comment by srikarparsi** [comment] 2023-07-20 17:05
Not able to reproduce either, closing this one out

https://github.com/Expensify/App/assets/48188732/f45dc7fe-2fee-4263-8fd5-2aa7942c57e7

**Closed by srikarparsi** 2023-07-20 17:05 UTC
Labels: DeployBlockerCash, Engineering, Hourly
