### ISSUE TITLE
[HOLD for payment 2024-10-17] [$250] Plural Remove Members on the workspace members page even when we only have one member selected

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49961] opened 2024-09-30 22:38 UTC
`If` you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727729303045069

## Action Performed:
1. Go to staging.new.expensify.com
2. Select any workspace from settings which have members
3. Click Members > select any added member
4. Click the dropdown in the `1 selected` pill
## Expected Result:
Remove member displayed as only one member selected 
## Actual Result:
Remove members displayed even if only one member selected
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot 2024-10-01 at 2 17 22 AM](https://github.com/user-attachments/assets/b8b7ec85-5239-43ee-9391-266a9f9c4a04)

![Snip - (53) New Expensify - Google Chrome](https://github.com/user-attachments/assets/ab571a55-66db-4824-9c98-d15461d771ba)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841413637223772836</li>
        <li>Upwork Job ID: 1841413637223772836</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 104321898</li>
<li>nkdengineer | Contributor | 104321900</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment] 2024-10-02 09:42
Sure!

**Comment by nkdengineer** [comment] 2024-10-02 10:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove members displayed even if only one member selected

### What is the root cause of that problem?

We're always using `workspace.people.removeMembersTitle` without checking whether the selected employee is one or many

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/workspace/WorkspaceMembersPage.tsx#L480

### What changes do you think we should make in order to solve the problem?
Following the same pattern of this translation we can update `removeMembersTitle` translation like this

```
removeMembersTitle: () => ({
    one: 'Remove member',
    other: 'Remove members',
}),
removeMembersTitle: () => ({
    one: 'Eliminar miembro',
    other: 'Eliminar miembros',
}),
```

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/languages/en.ts#L883

Then for each place below, we only need to pass the `count` param as the length of the selected member to this translation to display the translation accordingly with the length of the selected member


https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/ReportParticipantsPage.tsx#L269

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/ReportParticipantsPage.tsx#L393

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/workspace/WorkspaceMembersPage.tsx#L480

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/workspace/WorkspaceMembersPage.tsx#L640

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/ReportParticipantsPage.tsx#L269

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/RoomMembersPage.tsx#L276

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/pages/RoomMembersPage.tsx#L371

OPTIONAL: We can make the same approach for `removeMembersPrompt` translation. And update all places that we're using `removeMembersPrompt` without checking the length of the selected member

```
removeMembersPrompt: ({memberName}: {memberName: string}) => ({
    one: `Are you sure you want to remove ${memberName}?`,
    other: 'Are you sure you want to remove these members?',
}),
```

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/languages/en.ts#L3352

With this approach we can remove `removeMemberTitle` and `removeMemberPrompt` translation and use `removeMembersTitle`/`removeMembersPrompt` with `count` param as `1`
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-10-02 10:44
Updated [proposal](https://github.com/Expensify/App/issues/49961#issuecomment-2388303991)

- Fix another case.

**Comment by trjExpensify** [comment] 2024-10-07 23:55
@allgandalf did you review?

**Comment by nkdengineer** [comment] 2024-10-08 07:49
> In particular I feel @nkdengineer 's https://github.com/Expensify/App/issues/49961#issuecomment-2388303991 is a bit of over-engineering

@allgandalf I don't think so.

1. We already have a translation like this here

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/languages/en.ts#L883-L885

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/components/Search/SearchPageHeader.tsx#L284

https://github.com/Expensify/App/blob/487816184680744a2ad53a03460cbbdec363c432/src/components/Search/SearchPageHeader.tsx#L146-L148

2. With this approach, we can get the translation cleaner everywhere we use this. We only need to pass to count param to this translation instead of has an if else in all places to get the title.

**Comment by rlinoz** [comment] 2024-10-08 14:24
From [the readme](https://github.com/Expensify/App/#internationalization) of the project it looks like we prefer to implement plurals with the count option, also checked internally and that is the general feel as well, so let's go with @nkdengineer's proposal

**Comment by trjExpensify** [comment] 2024-10-17 19:13
It's a pretty minor language thang this, so I think we can skip the regression test. 

Payment summary as follows: 

- $250 to @allgandalf for the C+ reveiw
- $250 to @nkdengineer for the fix

Paid, closing!

**Closed by trjExpensify** 2024-10-17 19:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
