### ISSUE TITLE
[Awaiting payment] [$1000] After deleting an attachment, the LHN shows '[Attachment]' instead of 'No activity yet' until you delete one more message

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24246] opened 2023-08-08 02:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to userA's account.
2. Go to Settings > Workspace > New Workspace.
3. Go to Member > Invite > Select user B.
4. Go to the 'announce' chat of the created workspace.
5. Pin the 'announce' chat to view the LHN properly.
6. Open another browser and login with userB’s account.
7. Go to the 'announce' page of userA's workspace.
8. Send an image to the announce chat.
9. Go back to userA’s account.
10. Send a message and delete it.
11. Now go to the userB’s account and delete the attachment.
12. Notice userA’s LHN displays '[Attachment]' instead of 'No activity yet'.

## Expected Result:
After deleting an attachment, 'No activity yet' should be displayed in the LHN for userA

## Actual Result:
After deleting a file, '[Attachment]' is shown in the LHN instead of 'No activity yet' until you delete one more message

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/b7b2fd41-facd-4f11-82c6-e06725fa4d3b

https://github.com/Expensify/App/assets/43995119/0295e196-9856-4183-9326-04188acf3d77

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690838025775809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188933d8c36eb686a</li>
        <li>Upwork Job ID: 1688791645877243904</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>pradeepmdk | Contributor | 26490195</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-08-08 05:55
![image](https://github.com/Expensify/App/assets/59587260/17a881be-7d40-4213-b846-76afec87a110)

**Comment by msapple0338** [comment] 2023-08-08 07:39
I can solve this  issue.

**Comment by kaushiktd** [comment] 2023-08-08 07:56
### Please re-state the problem that we are trying to solve in this issue.

After deleting an attachment, the LHN shows '[Attachment]' instead of 'No activity yet' until you delete one more message

### What is the root cause of that problem?

There is an issue with `isReportMessageAttachment` condition on the below file:
https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js#L385
```
if (ReportUtils.isReportMessageAttachment({ text: report.lastMessageText, html: report.lastMessageHtml, translationKey: report.lastMessageTranslationKey })) {
   lastMessageTextFromReport = `[${Localize.translateLocal(report.lastMessageTranslationKey || 'common.attachment')}]`;
}
```
If we reset the value of lastMessageTranslationKey, still it will return the last value as [Attachment] because of the fixed return value in above mention condition
 

### What changes do you think we should make in order to solve the problem?

You need to adjust `isReportMessageAttachment` condition, you need to pass only the last message to this function and return the last message like below:
```
if (ReportUtils.isReportMessageAttachment(report.lastMessageText)) {
    lastMessageTextFromReport = report.lastMessageText;
}
```

### Video:

https://drive.google.com/file/d/1ebi89ipx5JJg10Ju-8XyTt8bU4G7gL47/view?usp=sharing

**Comment by msapple0338** [comment] 2023-08-08 08:56
Did you solve this issue? done?

**Comment by kaushiktd** [comment] 2023-08-08 08:58
@msapple0338 you talking to me?

**Comment by msapple0338** [comment] 2023-08-08 09:25
You`re working in the issue part?

**Comment by msapple0338** [comment] 2023-08-08 09:46
Hello I got the reason of the issue.

**Comment by msapple0338** [comment] 2023-08-08 10:07
Hey!!! kaushiktd
Your focusing is a mistake.

**Comment by pradeepmdk** [comment] 2023-08-08 13:37
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
After deleting an attachment, the LHN shows '[Attachment]' instead of 'No activity yet' until you delete one more message 
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/main/src/libs/OptionsListUtils.js?#L385
![Screenshot 2023-08-08 at 7 04 36 PM](https://github.com/Expensify/App/assets/16595846/5aecfc23-a83a-4f58-92b3-8c560f8085d2)
in the backend whenever last message have attachement  `lastMessageTranslationKey` this key will come with value.

### What changes do you think we should make in order to solve the problem?

need to fix the backend side 
lastMessageTranslationKey should be null when last has been attachement

**Comment by pradeepmdk** [comment] 2023-08-11 10:56
@kadiealexander there is no c+ member can you assign for review

**Comment by kadiealexander** [comment] 2023-08-13 21:46
@eVoloshchak thank you for picking this one up off @thesahindia!

**Comment by eVoloshchak** [comment] 2023-08-14 18:46
Huh, this is an interesting bug. I'll need a bit more time to go over all of the proposals, will post a review tomorrow

**Comment by kadiealexander** [comment] 2023-08-22 01:17
@eVoloshchak any thoughts after going through the proposals?

**Comment by eVoloshchak** [comment] 2023-08-22 18:17
I agree with @dukenv0307 on [this](https://github.com/Expensify/App/issues/24246#issuecomment-1669006968) one

> It seems this issue relate to lastMessageTranslationKey that we haven't done from BE side

`lastMessageTranslationKey` is "common.attachment", but it has to be an empty string. This needs to be fixed on the back end it

cc: @kadiealexander

**Comment by kadiealexander** [comment] 2023-08-28 06:32
Noted @eVoloshchak

**Comment by Li357** [comment] 2023-08-28 16:31
Agree the most elegant solution here is to fix the backend instead of a workaround on the frontend.

**Comment by s-alves10** [comment] 2023-08-29 15:29
@Li357 

I agree with that `lastMessageTranslationKey` is a pure frontend property. But optimistically setting it to an empty string won't work because when user A deletes the attachment, user B only receives the pusher updates. Unless the pusher updates have this property, user B can't know about it. 

That's why [my solution](https://github.com/Expensify/App/issues/24246#issuecomment-1669822606) suggests to check if the message is a deleted message before checking the `lastMessageTranslationKey`

**Comment by Li357** [comment] 2023-08-30 13:31
Put a PR to reset `lastMessageTranslationKey` from the backend.

**Comment by pradeepmdk** [comment] 2023-08-30 13:44
@Li357  wen can fix in the front end side. we have two scenarios for this root cause  https://github.com/Expensify/App/issues/24246#issuecomment-1669637160

the fix from BC
> lastMessageTranslationKey should have the value when text : '[Attachment]'  has value. otherwise should be empty.

the fix from ClientSide

https://github.com/Expensify/App/blob/d7966ec272c9c07880f4234a82347bec0a0dac77/src/libs/isReportMessageAttachment.js
```
 if (translationKey && text ==  CONST.ATTACHMENT_MESSAGE_TEXT) {
        return translationKey === CONST.TRANSLATION_KEYS.ATTACHMENT;
    }
```

**Comment by Li357** [comment] 2023-08-31 15:44
Ah, I see. So the problem is the translation key is not set/reset when we change from a message *with* a translation key to one *without*, or vice-versa.

**Comment by kaushiktd** [comment] 2023-09-01 04:04
@Li357 I guess my proposal is overlooked may be?

Because we do not need to reset `lastMessageTranslationKey` key, you just need to modify your condition. Can you review the proposal?
https://github.com/Expensify/App/issues/24246#issuecomment-1669106873

**Comment by Li357** [comment] 2023-09-01 15:11
@kaushiktd I reviewed all the proposals. I still think it makes sense to keep `lastMessageTranslationKey` in sync than to change other conditions. The root problem here is that `lastMessageTranslationKey` isn't actually the last message's translation key, so we should fix that.

**Comment by eVoloshchak** [comment] 2023-09-03 21:01
@Li357, a huge thank you for digging into this!
@pradeepmdk's [proposal](https://github.com/Expensify/App/issues/24246#issuecomment-1669637160) looks good to me too, verified it working 

I've encountered a similar issue when trying to reproduce this one, it will also be resolved by this proposal since the root cause is the same

>1. Open a conversation (User A)
>2. Open another browser and login with userB’s account.
>3. Go to the conversation with user A
>4. Send an image to user A
>5. Go back to userA’s account.
>6. Send a text message to user B
>7. Go back to userB’s account.
>8. Notice LHN still displays '[Attachment]' instead of the text message

🎀👀🎀 C+ reviewed!

**Comment by Li357** [comment] 2023-09-04 14:24
All yours @pradeepmdk

**Comment by pradeepmdk** [comment] 2023-09-04 14:35
@Li357 looks like mapping worked correctly. I got the offer

**Comment by pradeepmdk** [comment] 2023-09-06 22:59
@eVoloshchak Pr is ready

**Comment by eVoloshchak** [comment] 2023-09-26 11:13
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

-  The PR that introduced the bug has been identified. Link to the PR: the logic was added in https://github.com/Expensify/App/pull/21780, but I wouldn't say the bug was introduced by this PR, this was mainly a BE issue we resolved on FE. Still leaving a comment on the PR to myself and others to test more complex test cases

-  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21780/files#r1337040240

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Don't think an additional discussion is needed, this isn't a new type of bug, just something we should test more thoroughly for

**Comment by eVoloshchak** [comment] 2023-09-26 11:15
**Regression Test Proposal**

1. Log in to userA's account.
2. Go to Settings > Workspace > New Workspace.
3. Go to Member > Invite > Select user B.
4. Go to the 'announce' chat of the created workspace.
5. Open another browser and login with userB’s account.
6. Go to the 'announce' page of userA's workspace.
7. Send an image to the announce chat.
8. Go back to userA’s account.
9. Send a message and delete it.
10. Now go to the userB’s account and delete the attachment.
11. Verify userA’s LHN displays 'No activity yet'.

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-09-26 11:17
The automation for this failed for some reason, instead creating a payment issue: https://github.com/Expensify/App/issues/27374, so posting a BugZero Checklist manually here

cc: @kadiealexander

**Comment by pradeepmdk** [comment] 2023-09-30 00:26
i think bot is not triggered for payment.
cc: @kadiealexander

**Comment by kadiealexander** [comment] 2023-10-05 05:56
Payouts due:

- [ ] Issue Reporter: $250 @ayazhussain79
- [ ] Contributor: $1000 @pradeepmdk
- [ ] Contributor+: $1000 @eVoloshchak

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/ab/applicants/1688791645877243904/suggested).

**Comment by JmillsExpensify** [comment] 2023-10-05 20:51
$1,000 payment approved for @eVoloshchak based on BZ summary.

**Comment by eVoloshchak** [comment] 2023-10-26 13:32
@kadiealexander, this one can be closed I think

**Comment by ayazhussain79** [comment] 2023-11-03 10:44
@kadiealexander could you please approve the payment on upwork

**Comment by kadiealexander** [comment] 2023-11-05 23:59
@ayazhussain79

**Comment by ayazhussain79** [comment] 2023-11-06 07:31
@kadiealexander offer already accepted, sent you message on upwork

**Closed** 2023-11-06 21:59 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
