### ISSUE TITLE
[HOLD for payment 2023-08-10] [$250] Migrate index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16261] opened 2023-03-20 15:34 UTC
### Filenames
- [ ] [src/pages/home/report/FloatingMessageCounter/index.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/FloatingMessageCounter/index.js)
    - **type:** `React.PureComponent`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidUpdate`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec8cbcbca092abc3</li>
        <li>Upwork Job ID: 1679302094357667840</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 05:52
I'd like to work on this issue

**Comment by vdem0115** [comment] 2023-07-05 12:09
I would like to work on this.

**Comment by olexyt** [comment] 2023-07-07 14:52
I can work on this issue.

**Comment by to-ai** [comment] 2023-07-11 21:24
I am able to work on this task.

**Comment by AGarciaNY** [comment] 2023-07-13 00:24
I would like to work on this issue.

**Comment by devofficer** [comment] 2023-07-13 03:14
I have this steps for migration.
- Replace the class FloatingMessageCounter with a functional component const FloatingMessageCounter = ({ isActive, onClick, translate }) => { ... }.
- Remove the constructor and created a useRef hook to initialize the translateY animated value.
- Converte componentDidUpdate to an effect hook by wrapping the code inside useEffect(() => { ... }, [isActive]).
- Replace this.translateY with translateY inside the show and hide functions.
- Replace this.props.translate with translate directly in the accessibilityHint and Text component.
- Remove render() method and returned the JSX directly from the functional component.

Would you love to assign this issue to me?

**Comment by krishgb** [comment] 2023-07-13 03:26
Hello 👋, I have seen your GitHub issue.
It states that class components have to be converted to functional component.
In the FloatingMesaageCounter/index.js file, it can be converted by using useEffect for lifecycle methods instead of componentDidUpdate method. And also constructor method can also be removed with useEffect with isActive prop as a dependency. 
This component doesn't need any state management because the TRANSLATE_Y for active and inactive props are static.

**Comment by krishgb** [comment] 2023-07-13 03:32
Contributor details
Your Expensify account email: codeflancers@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f3ee9acb7e1feb82

**Comment by nampham7394** [comment] 2023-07-13 03:36
Hi,
We change FloatingMessageCounter to function like const FloatingMessageCounter = ({ default value isActive, onClick, .. ).
In function, ew define translate with Animated value and add this into useRef function to make animation tracking on it.
We also make isActive into dependency in UseEffect function to track state and decide action show hide floating
Expensify account email: phamcaonam.94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018b9f89626052eb90

**Comment by nampham7394** [comment] 2023-07-13 03:40
Hi,
We change FloatingMessageCounter to function like const FloatingMessageCounter = ({ default value isActive, onClick, .. ).
In function, ew define translate with Animated value and add this into useRef function to make animation tracking on it.
We also make isActive into dependency in UseEffect function to track state and decide action show hide floating
Contributor details
Expensify account email: [phamcaonam.94@gmail.com](mailto:phamcaonam.94@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018b9f89626052eb90

**Comment by nampham7394** [comment] 2023-07-13 03:41
Hi,
We change FloatingMessageCounter to function like const FloatingMessageCounter = ({ default value isActive, onClick, .. ).
In function, ew define translate with Animated value and add this into useRef function to make animation tracking on it.
We also make isActive into dependency in UseEffect function to track state and decide action show hide floating

Expensify account email: [phamcaonam.94@gmail.com](mailto:phamcaonam.94@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018b9f89626052eb90

**Comment by batcodegen** [comment] 2023-07-13 04:05
1. Change class FloatingMessageCounter to const FloatingMessageCounter = ({ isActive, onClick, ...props }) => { ... }.
2. Constructor variables can be replaced with useRef hook.
3. componentDidUpdate needs to be replaced with useEffect hooks as ->  useEffect(() => { ... }, [isActive]).
4. Change all 'this' variables with local values directly like 'translateY' and 'props.translate'.
5. Remove the render() method and directly return JSX from the component.

Contributor details
Expensify account email: prakh20@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ba09b120cec7429d

**Comment by rushatgabhane** [comment] 2023-07-13 04:30
looks like @muxriddinmuqimov77 is [first](https://github.com/Expensify/App/issues/16261#issuecomment-1577956952) (and no other issue assigned)

🎀 👀 🎀

**Comment by gadhiyamanan** [comment] 2023-07-13 04:39
@rushatgabhane according to [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119), The first to leave a comment after the issue is taken off HOLD will be assigned

I think @muxriddinmuqimov77 commented before the issue is taken off HOLD

**Comment by rushatgabhane** [comment] 2023-07-13 05:26
oh thanks! @devofficer gets this one then!

**Comment by puneetlath** [comment] 2023-07-13 13:30
Ah, sorry for the confusion. I've already assigned this issue to @AGarciaNY because we'd been discussed it outside of GH already. Thanks for your interest everyone!

**Comment by puneetlath** [comment] 2023-07-13 13:31
Ah, sorry for the confusion. I've already assigned this issue to @AGarciaNY because we'd been discussed it outside of GH already. Thanks for your interest everyone!

**Comment by johnmlee101** [comment] 2023-07-13 16:14
Sticking around to assist with the PR review, I'd imagine then 😄

**Comment by puneetlath** [comment] 2023-07-13 16:26
Yeah, I'm happy to handle the CME role on this one if you want to bow out @johnmlee101

**Comment by johnmlee101** [comment] 2023-07-13 17:15
I'm happy to do the CME role for this 😄

**Comment by rushatgabhane** [comment] 2023-07-25 10:45
Umm is there a PR for this? I can't find it

**Comment by AGarciaNY** [comment] 2023-07-25 22:02
Yes. It's right [here](https://github.com/Expensify/App/pull/22912)

**Comment by rushatgabhane** [comment] 2023-07-25 22:05
Thank you for linking the PR@AGarciaNY  
Your PR is on my review list. Please ping me if I don't review it within 24 hrs 🙇

**Comment by puneetlath** [comment] 2023-08-02 21:45
The PR is on staging.

**Comment by puneetlath** [comment] 2023-08-10 15:31
Payment summary: 
- Bug reporter: n/a
- Contributor: @AGarciaNY (paid via Upwork)
- C+: @rushatgabhane (to be paid via NewDot)

@rushatgabhane please go ahead and make the payment request via NewDot and comment here once you have.

**Comment by rushatgabhane** [comment] 2023-08-14 19:36
thanks, created a manual request here - https://staging.new.expensify.com/r/3936760144211997

this issue can be closed

**Comment by puneetlath** [comment] 2023-08-15 15:33
Assigning @anmurali for payment.

**Comment by JmillsExpensify** [comment] 2023-08-16 03:38
Reviewed the details above. Given that this is a standard component upgrade, I'll approve the payment, though in the future @puneetlath please provide the amounts in that summary. Thank ya!

**Comment by puneetlath** [comment] 2023-08-16 14:26
Ah, my apologies! Will make sure to do next time.

**Comment by puneetlath** [comment] 2023-08-16 16:21
Closing out, thanks everyone!

**Closed by puneetlath** 2023-08-16 16:21 UTC
Labels: External, Engineering, Weekly, Improvement, Awaiting Payment
