### ISSUE TITLE
[$1000] Web- Public Room - App crashes on removing the user from room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20122] opened 2023-06-03 15:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A which needs to be a phone number and create a new workspace and invite User B
2. Create a room from User A and include the workspace that you created earlier.
3. Select public room and create a room
4. Now click on the room header and click on share code. Copy the URL.
5. Go to the normal chat with User B and send the link
6. From user B, login in another web chrome which also needs to be a phone number and click on the link that was received so that the room gets accessible
7. Now from User A, send a message and from user B also send a message on that room. Next From user A account, remove the user from the workspace.
8. Result: See that on User B account, app crashed.

## Expected Result:
App should not crash on removing the user from room

## Actual Result:
App crashes on removing the user from room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/93693887-46ab-4ff3-bfdc-40445777313d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685521307987259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01930f1bcb8d849f34</li>
        <li>Upwork Job ID: 1666031687363350528</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2023-06-06 10:34
I was able to reproduce this exactly as described: 
https://github.com/Expensify/App/assets/28715117/16242194-c326-465a-be0c-338012a51718

**Comment by miljakljajic** [comment] 2023-06-06 10:37
Going to apply the external label and also assign a new BZ member to manage the ongoing proposals as I'm taking part in the 'Guide Experiment' over the next couple of months, so will be focused on our outsourced sales team and not participating in this team.

**Comment by StevenKKC** [comment] 2023-06-06 21:02
Duplicate of https://github.com/Expensify/App/issues/19360

**Comment by avi-shek-jha** [comment] 2023-06-07 04:25
Seems like the app crash issue has been solved. But still there's a second error that has arisen. When removed the user from the workspace, the chat page still remains and a removed User B is able to reply through the chat composer. The chat page should have been disappeared in a normal scenario like how announce channel gets disappeared if a user has been removed.
![Screenshot from 2023-06-07 10-08-11](https://github.com/Expensify/App/assets/123831727/369112e4-2f8a-4d6a-ad6d-eee2c6a46658)

**Comment by cead22** [comment] 2023-06-08 23:16
I posted in the other issue so we can confirm if this was something that should've been fixed there but wasn't (or if it was caused by that PR)

**Comment by cead22** [comment] 2023-06-14 01:31
@avi-shek-jha I'm going to close this issue since what was originally reported here with the reproduction steps is no longer happening.

If you can reproduce what you described in [the comment above](https://github.com/Expensify/App/issues/20122#issuecomment-1579863117), can you please create a new issue to report this as a new bug?

Feel free to reopen if you disagree

**Closed by cead22** 2023-06-14 01:31 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
