### ISSUE TITLE
[HOLD for payment 2024-11-21] [$250] Pay someone - User is signed out after verifying account during pay someone flow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50284] opened 2024-10-05 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50169
**Email or phone of affected tester (no customers):** yonghongkok2+sddwe23@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new Gmail account.
3. Complete the onboarding.
4. Open DM with any user.
5. Click + > Pay someone.
6. Select currency in USD, enter amount and click Next.
7. Click Pay with Expensify.
8. Enter the correct magic code.

## Expected Result:
User will not be signed out after verifying account during pay someone flow.

## Actual Result:
User is signed out after verifying account during pay someone flow.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/07ce4b74-bdbb-456e-80f3-604cc36cb631

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843360929752935358</li>
        <li>Upwork Job ID: 1843360929752935358</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by arosiclair** [comment] 2024-10-07 15:46
I reproduced on staging **v9.0.45-2** and not on prod **v9.0.44-12** (the original bug from https://github.com/Expensify/App/issues/49523 is still present).

**Comment by arosiclair** [comment] 2024-10-07 16:35
This is actually _not_ reproducible in dev with the latest changes on `main`.

**Comment by ikevin127** [comment] 2024-10-07 17:48
We discussed this issue here in https://github.com/Expensify/App/issues/48041#issuecomment-2394985903 since that was the issue which introduced the new validation route logic.

Looks like the cause of the logout is/was that when we input the magic code, one of the API endpoints is called with the old / outdated `authToken` from when the account was not validated.

The issue seems unrelated to the PR I reviewed and more related to the PR that introduced the new validation route logic.

If we were to follow-up with a fix and pinpoint the offending PR, that would be https://github.com/Expensify/App/pull/49230 even if the logout issue did not pop-up while testing issue https://github.com/Expensify/App/issues/48041.

The fix for this should be something along the lines of making sure that once the magic code was provided in the new route, we make sure to clear the old `authToken` before making any API calls post-validation.

This can be done either on FE or BE.

Please, correct me if any of my above statements are wrong!

##

> This is actually not reproducible in dev with the latest changes on `main`.

I'll have to double check, but if the issue is indeed not reproducible anymore, can we assume that this was fixed from the BE side ? 🤔

**Comment by arosiclair** [comment] 2024-10-07 18:23
I can't verify locally, but reverting https://github.com/Expensify/App/pull/50169 would probably restore the behavior on prod (the not found page). However, I'm not sure that's really "better" than what we have now (forced logout but working after logging back in). I think the best path forward is to not block on this and use this issue to investigate and fix the problem.

**Comment by ikevin127** [comment] 2024-10-07 18:47
That's right, unfortunately I only tested the actual validation post-merge :trollface:

**Comment by jestinjoshi** [comment] 2024-10-08 02:52
@ikevin127 based on my investigation, this appears to be a backend issue. It seems that the Onyx key `credentials` isn’t being populated with the `autoGeneratedLogin` and `autoGeneratedPassword` values during the sign-up process.

**Comment by ikevin127** [comment] 2024-10-08 20:12
As I mentioned in offending issue https://github.com/Expensify/App/issues/49523#issuecomment-2400732507:

> @isabelastisser Yes, we had the following regression:
> - https://github.com/Expensify/App/issues/50284
> 
> which was caused by lack of testing on both PR reviewer and author sides. The issue mentioned above is open for proposals, unless the author wants to fix the issue given that we're still within the regression period.
> 
> **Note**: The issue was that we relied on the other PRs implementation of the new route without actually testing if the implementation works, ignoring this issue's **Expected result** which states `Add bank account page should open` as we stopped the testing at "seeing the magic code input showing up in RHP".

So unless the author wants to fix this, we're **open for proposals**. Peace out ✌️

**Comment by arosiclair** [comment] 2024-10-14 17:11
Okay the credentials (partnerUserID and secret) are cleared by the `SignUpUser` command since we added the unvalidated sign up flow in [this PR](https://github.com/Expensify/Web-Expensify/pull/42216).

I'm not sure what's the correct way to handle this in product validation flow. I'm going to start a discussion about it.

**Comment by zanyrenney** [comment] 2024-10-14 17:29
Thanks @arosiclair please link the discussion here so it's clear what the status is for us following along.

**Comment by arosiclair** [comment] 2024-10-14 17:41
Started the discussion [here](https://expensify.slack.com/archives/C03TQ48KC/p1728927479742449)

**Comment by zanyrenney** [comment] 2024-10-14 17:41
Thanks!

**Comment by sobitneupane** [comment] 2024-10-15 05:45
https://github.com/Expensify/App/issues/50284#issuecomment-2411871878

**Comment by arosiclair** [comment] 2024-10-30 15:22
No more updates for this yet. Focusing on the analytics project.

**Comment by zanyrenney** [comment] 2024-10-30 15:48
Should we put this on hold then @arosiclair / update the priority to weekly?

**Comment by arosiclair** [comment] 2024-11-01 21:41
Made some more progress today. Everything's working now I just need to finalize the [Web](https://github.com/Expensify/Web-Expensify/pull/44052) and [App](https://github.com/Expensify/App/pull/50835) PRs.

**Comment by arosiclair** [comment] 2024-11-04 22:03
Web PR is out for review.

**Closed** 2024-11-21 10:43 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 10:56
$250 approved for @sobitneupane
