### ISSUE TITLE
Error appears  when create and delete workspaces offline and back to online reported by  @Santhosh-Sellavel

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12359] opened 2022-11-02 00:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create two workspaces A & B
2. Now go offline
3. Create another workspace B
4. Now Delete workspace A
5. Go online

## Expected Result:
The operations should be completed without errors.

## Actual Result:
Stuck with deleted workspaces, need to log

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop
- mWeb

**Version Number:** 1.2.22-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199365652-eff0cb12-7872-4751-90aa-aede6bbe9e9c.mov

https://user-images.githubusercontent.com/43996225/199365771-7ea2bc48-7de7-4c72-9543-d9016efcdbe7.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667248075862129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Santhosh-Sellavel** [comment] 2022-11-02 20:21
@kavimuru it happens on all platforms!

**Comment by trjExpensify** [comment] 2022-11-07 19:12
@aldo-expensify is this related to the bug you're working on fixing with the error message?

**Comment by aldo-expensify** [comment] 2022-11-07 23:14
I'll have a look

**Comment by aldo-expensify** [comment] 2022-11-09 08:02
@Santhosh-Sellavel does this require having more than one device? I'm a bit confused with the step "3. Create another workspace B", does this third workspace has any relation with the second workspace (both named "B")?

**Comment by aldo-expensify** [comment] 2022-11-11 18:38
Waiting for some clarifications

**Comment by Santhosh-Sellavel** [comment] 2022-11-12 01:13
> @Santhosh-Sellavel does this require having more than one device? 

We know this might occur for multiple devices, but I can't recall whether I've used two devices or not! I'll try to reproduce it now!

**Comment by aldo-expensify** [comment] 2022-11-12 01:21
Thanks @Santhosh-Sellavel , what about the other part?

> I'm a bit confused with the step "3. Create another workspace B", does this third workspace has any relation with the second workspace (both named "B")?

🙏

**Comment by Santhosh-Sellavel** [comment] 2022-11-12 01:22
Might be a typo it should be C, not B!

**Comment by Santhosh-Sellavel** [comment] 2022-11-12 01:22
I'm unable to reproduce this now, so we can close this!

**Comment by aldo-expensify** [comment] 2022-11-12 01:35
> I'm unable to reproduce this now, so we can close this! If I am able to reproduce I'll ping you here!

Cool, thank you very much for trying to reproduce again :)!

**Closed by aldo-expensify** 2022-11-12 01:35 UTC
Labels: Daily, Needs Reproduction
