### ISSUE TITLE
[$1000] Web- Chat - The background opacity becomes darker when opening each page, specifically incase of thread only.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20008] opened 2023-06-01 21:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
on Performed:
1. Go to any "thread."
2. Click on "Settings."
3. Click on "Welcome message."
4. Notice that when opening each page, the background becomes progressively darker, incase of threads, other than that the opacity remains the same throughout.

## Expected Result:
The background opacity should remain the same throughout.

## Actual Result:
The background opacity becomes darker when opening each page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/abbe4740-ff08-475a-80b9-47dd9a49f318

https://github.com/Expensify/App/assets/93399543/d7c9ed12-b865-4838-a12a-7598968a8406

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685509854226419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a83e84ece19a3c9b</li>
        <li>Upwork Job ID: 1664707978044399616</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-06-02 18:57
reproducible, and I don't see a dupe - moving to external

**Comment by danieldoglas** [comment] 2023-06-05 12:40
Agreed this is a dupe for https://github.com/Expensify/App/issues/19073

Closing this issue.

**Closed by danieldoglas** 2023-06-05 12:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
