### ISSUE TITLE
Category-Saving GL & payroll code directed to category list instead of specific category

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47399] opened 2024-08-14 10:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4856835
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile icon -- workspaces-- workspace
3. Tap more features -- enable report field
4. Tap category
5. Tap on a category
6. Rename the category android save it
7. Note user directed to specfic category page
8. Enter GL code & payroll code and save it
9. Note user directed to category list instead of specific category page
10. Edit GL code & payroll code and save it
11. Note user directed to category list instead of specific category page

## Expected Result:
Saving GL & payroll code must be directed to specific category page.

## Actual Result:
Saving GL & payroll code directed to category list instead of specific category page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/52abc66b-ea59-447c-9ab7-d89c9df6e3f1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-08-14 10:59
We think this issue might be related to the  #vip-vsb

**Comment by BhuvaneshPatil** [comment] 2024-08-14 11:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upon saving GL and payroll code, we are directed to category list instead of specific category

### What is the root cause of that problem?
We are using `dismissModal()`

https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/pages/workspace/categories/CategoryGLCodePage.tsx#L35-L44



### What changes do you think we should make in order to solve the problem?
We should use `goBack()` with appropriate fallback route

### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-08-14 11:37
@allroundexperts In PR it was converted from `goBack()` to `dismissModal()`. We can consider for upgrade pages but places pages where we change values. I am not getting that. Can you please explain. Thanks

**Comment by allroundexperts** [comment] 2024-08-15 00:27
@BhuvaneshPatil I think it will be safe to change it on the pages where we change values. We can give it a try.

**Comment by allroundexperts** [comment] 2024-08-15 00:28
Btw this is really an minor issue when compared with the host of issues that https://github.com/Expensify/App/pull/46617 solves. I think we can demote this to be not a blocker.

**Comment by youssef-lr** [comment] 2024-08-15 12:30
@allroundexperts would would you like to submit a quick fix?

**Comment by allroundexperts** [comment] 2024-08-15 22:08
Sure, please assign this to me and I will raise a PR tomorrow.

**Comment by allroundexperts** [comment] 2024-08-16 23:33
PR: https://github.com/Expensify/App/pull/47593

**Comment by abdulrahuman5196** [comment] 2024-08-25 19:30
@youssef-lr / @isabelastisser  Could you kindly add me as a C+ here for working on the PR review?

**Comment by isabelastisser** [comment] 2024-09-11 20:39
@abdulrahuman5196 @allroundexperts I see PR is merged; when is payment due?

**Comment by abdulrahuman5196** [comment] 2024-09-14 19:56
It shows 3 weeks ago this PR was pushed to staging. But no production comment. I think automation didn't comment here.

@youssef-lr I am assuming this is already pushed to production. Correct me if wrong? And when was that?

**Comment by abdulrahuman5196** [comment] 2024-09-14 19:59
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://github.com/Expensify/App/pull/46617

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Go to https://staging.new.expensify.com/
2) Tap profile icon -- workspaces-- workspace
3) Tap more features -- enable report field
4) Tap category
5) Tap on a category
6) Rename the category android save it
7) Note user directed to specfic category page
8) Enter GL code & payroll code and save it
9) Note user directed to category list instead of specific category page
10) Edit GL code & payroll code and save it
11) Verify that saving GL & payroll code must be directed to specific category page.

**Comment by abdulrahuman5196** [comment] 2024-09-23 15:28
> It shows 3 weeks ago this PR was pushed to staging. But no production comment. I think automation didn't comment here.
> 
> @youssef-lr I am assuming this is already pushed to production. Correct me if wrong? And when was that?

@youssef-lr / @isabelastisser Could you kindly confirm here?

**Comment by youssef-lr** [comment] 2024-10-03 18:31
Yes, looks like automation failed. That PR is in production.

**Comment by isabelastisser** [comment] 2024-10-04 12:31
Sorry for the delay here! The payment automation failed and I missed the notification about it. I sent the offers in Upwork now.

All set!

**Closed by isabelastisser** 2024-10-04 12:31 UTC
Labels: Reviewing, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-12-30 11:46
$250 approved for @allroundexperts
