### ISSUE TITLE
[$250] Background in `Search` page RHP is duplicated and has unnecessary empty space

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#43247] opened 2024-06-07 05:20 UTC
cc @Expensify/design for further details. This is what I'm seeing. 

![CleanShot 2024-06-06 at 22 58 59@2x](https://github.com/Expensify/App/assets/1127863/2587f707-fe92-4ef1-99dc-b73fc8e69f32)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b71ca0f90384f8a8</li>
        <li>Upwork Job ID: 1800112433179548260</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2024-06-07 05:21
Also notice how the background is super-imposed on the receipt verified message as well.

**Comment by shawnborton** [comment] 2024-06-07 06:25
@rayane-djouah @yuwenmemon  can you please check this one out? This seems like another regression from [this PR](https://github.com/Expensify/App/pull/38449)

**Comment by trjExpensify** [comment] 2024-06-10 10:26
Sending this external so it gets eyes. I don't think @rayane-djouah is around right now.

**Comment by luacmartins** [comment] 2024-06-17 22:48
I'm also unable to reproduce this

**Comment by johncschuster** [comment] 2024-06-21 21:10
@JmillsExpensify it seems like no one has been able to reproduce this so far. Are you still experiencing it?

**Comment by johncschuster** [comment] 2024-06-21 21:11
@JmillsExpensify it seems like no one has been able to reproduce this so far. Are you still experiencing it?

**Comment by johncschuster** [comment] 2024-06-24 16:25
@JmillsExpensify bump! 

@shawnborton called out that the behavior Neil has seen [here](https://expensify.slack.com/archives/C05LX9D6E07/p1718939503378739) looks similar to what you've described in this issue. Can you take a look at that thread and let me know if the reproduction steps are close to the steps you've taken?

**Comment by johncschuster** [comment] 2024-06-24 16:26
I realize this issue is related to manual requests, but there's gotta be some overlap here 🤔

**Comment by luacmartins** [comment] 2024-06-24 19:07
hmm seems like this is not related to Search then. I'll remove this issue from the project since the root cause and issue happen outside the scope of the project too

**Comment by johncschuster** [comment] 2024-06-25 15:30
I'm having a hard time finding Manual Requests on the Quarterly release grid. Would this fit into `#vip-billpay`?

**Comment by luacmartins** [comment] 2024-06-25 16:31
@johncschuster we released manual requests ~1y ago, so it won't be on the current release grid. Not sure where this issue would fit since it seems like a generic UI issue (we'll find out once we figure out the root cause)

**Comment by luacmartins** [comment] 2024-06-27 15:29
I'm gonna go ahead and close this issue since nobody has been able to reproduce this yet. We can reopen if it's surfaced again.

**Closed by luacmartins** 2024-06-27 15:29 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
