### ISSUE TITLE
[$500] Wallet - An error in console then navigated to enable payments page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26207] opened 2023-08-29 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**issue found when executing PR** https://github.com/Expensify/App/pull/25458
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Open enable payments page http://staging.new.expensify.com/enable-payments

## Expected Result:
No any error in console

## Actual Result:
Error in console appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Widows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.58-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/295cf060-fe66-4c7e-b3d3-658bb12cfd06

![image](https://github.com/Expensify/App/assets/78819774/1d85159f-44e6-46c6-ada4-6798ac66c605)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b278b7230ab63f1</li>
        <li>Upwork Job ID: 1701552628230569984</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-08-29 13:52
Hmm, I don't get the error that you're seeing:

<img width="1351" alt="Screenshot 2023-08-29 at 8 51 38 AM" src="https://github.com/Expensify/App/assets/10926327/7b64ca83-5b81-49cc-aaa1-a2d04ecfaf79">

Can we confirm that this is not just a local issue @lanitochka17?

**Comment by b4s36t4** [comment] 2023-08-29 13:56
I don't see any error with attached video, is this an issue?

**Comment by CortneyOfstad** [comment] 2023-08-29 15:07
Same — I don't see the error in the video, only the screenshot

**Comment by CortneyOfstad** [comment] 2023-08-31 15:47
@lanitochka17 bump on the comments above ^^^

**Comment by lanitochka17** [comment] 2023-09-02 15:04
Issue reproducible on Build 1.3.62-1
Console error displayed
Windows10/Chrome

https://github.com/Expensify/App/assets/78819774/c9b9ada8-0609-410f-810c-13248a34ad88

**Comment by b4s36t4** [comment] 2023-09-02 15:06
@lanitochka17 I think those errors are way before, it's issue with how browser and HTTP works. @CortneyOfstad We can ask in the slack weather to continue or not. I saw quite a few related to same issue.

**Comment by CortneyOfstad** [comment] 2023-09-05 14:02
Going to get some internal eyes on this as well 👍

**Comment by CortneyOfstad** [comment] 2023-09-08 15:42
@youssef-lr bump on this — thanks!

**Comment by CortneyOfstad** [comment] 2023-09-11 15:06
@youssef-lr bump on the above. Thanks!

**Comment by youssef-lr** [comment] 2023-09-12 11:05
I'm guessing this is coming from a library we use. I think we can make this external to look into it further.

**Comment by zukilover** [comment] 2023-09-12 11:22
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Error in console appears in enable payments page

### What is the root cause of that problem?
Some content origins are not whitelisted using the Content-Security-Policy HTTP header.

### What changes do you think we should make in order to solve the problem?
Add a whitelist for some external resources that we deem safe, e.g.:
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://polyfill.io 'unsafe-inline' 'unsafe-eval';** ">

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment] 2023-09-15 18:29
@ArekChr any thoughts on the proposal?

**Comment by ArekChr** [comment] 2023-09-18 07:48
I could not reproduce the issue on macOS using Chrome, and I don't have access to a Windows machine for testing. @CortneyOfstad Could you please reassign me, as I won't be able to complete the review for this checklist?

**Comment by situchan** [comment] 2023-09-18 07:50
I can be assigned (discussed with @ArekChr on slack) but to me, this happens on mac chrome as well.

**Comment by ArekChr** [comment] 2023-09-18 08:58
@situchan This console error shows randomly?

**Comment by CortneyOfstad** [comment] 2023-09-20 12:51
Bump @ArekChr on @situchan's comment above

**Comment by mvtglobally** [comment] 2023-09-21 03:35
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2023-09-22 16:02
Alright, @youssef-lr any thoughts on this? We can consistently seem to recreate this. Any ideas?

**Comment by CortneyOfstad** [comment] 2023-09-25 13:45
Bump @youssef-lr

**Comment by youssef-lr** [comment] 2023-09-26 09:38
Can't reproduce either, closing!

**Closed by youssef-lr** 2023-09-26 09:38 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
