### ISSUE TITLE
[HOLD for payment 2024-10-24] Tags - Long pressing North+east not showing settings option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50555] opened 2024-10-10 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.47-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. In old dot, upload dependent tags
3. In new dot, open workspace settings
4. Open tags
5. Tap region
6. Long press North+east

## Expected Result:
Pressing "select" after long pressing the North+east tag triggers selection mode.

## Actual Result:
Pressing "select" after long pressing the North+east tag doesn't trigger selection mode.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6630271_1728534159671!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/user-attachments/files/17326858/Bug6630271_1728534159671.Dependent_-_Multi_Level_tags_NEW.csv)

https://github.com/user-attachments/assets/3e4a4640-a54e-4db2-955a-0ee80bec4b74

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by mjasikowski** [comment] 2024-10-10 12:37
Checking this one out right now

**Comment by mjasikowski** [comment] 2024-10-10 13:06
@IuliiaHerets I've edited the description, as it took me a while to understand what should be happening and what's not happening.

**Comment by mjasikowski** [comment] 2024-10-10 14:09
The issue is caused by https://github.com/Expensify/App/pull/49510

**Comment by mjasikowski** [comment] 2024-10-10 18:35
Revert cherry picked to staging

**Comment by mjasikowski** [comment] 2024-10-17 06:44
@daledah since you have more information, can you comment in the original PR letting us know what exactly caused the issue in question?

**Comment by greg-schroeder** [comment] 2024-10-24 19:12
Processing

**Comment by greg-schroeder** [comment] 2024-10-24 19:17
This was a regression fixed by the original contributor of the offending PR

**Closed by greg-schroeder** 2024-10-24 19:17 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
