### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] Tag rules - Tag rules are available for multi tags when the rules are not present on Old Dot

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49543] opened 2024-09-20 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.39-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Rules are enabled
- Dependent multi tags are set up on OD.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags.
3. Click on any main tag.
4. Click on any sub tag.

## Expected Result:
Tag rules should not be available for multi tags (because the rules are not present on Old Dot).

## Actual Result:
Tag rules are available for multi tags when the rules are not present on Old Dot.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[Bug6610082_1726848355301!Dependent_-_Multi_Level_tags_NEW.csv](https://github.com/user-attachments/files/17078076/Bug6610082_1726848355301.Dependent_-_Multi_Level_tags_NEW.csv)

https://github.com/user-attachments/assets/33cf5eb8-a1a9-462a-a5dc-9bbe3f92a798

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843317478267181555</li>
        <li>Upwork Job ID: 1843317478267181555</li>
        <li>Last Price Increase: 2024-10-14</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 104469276</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-20 16:30
We think that this bug might be related to #wave-control

**Comment by deetergp** [comment] 2024-09-20 18:57
This is behind a beta so it's not a blocker.

cc @marcaaron

**Comment by marcaaron** [comment] 2024-09-20 19:00
I'm also slightly confused about why we don't allow approvers on multi-level tags. Maybe there's just not much overlap or it would be strange to potentially have multiple approvers? @JmillsExpensify what do you think about this one?

**Comment by marcaaron** [comment] 2024-09-20 19:18
I'm not able to reproduce this on `main` fwiw. @yuwenmemon is working on tags related features for NewDot, maybe we can ask him to keep an eye on this.

**Comment by marcaaron** [comment] 2024-09-20 19:20
![2024-09-20_09-19-09](https://github.com/user-attachments/assets/d3c1c585-69c3-4e5f-8841-0a34143d64e2)

maybe this has something to do with multiple policy set up with different configurations?

**Comment by IuliiaHerets** [comment] 2024-09-20 19:56
@marcaaron Policy should be Control, you can enable Rules in More features to upgrade it

**Comment by marcaaron** [comment] 2024-09-20 19:59
Yes. Tested with a Control policy. The provided steps do not lead to a reproduction.

**Comment by IuliiaHerets** [comment] 2024-09-20 20:10
Issue is still reproducible, tested just now

https://github.com/user-attachments/assets/40aece8b-8e6a-4bcb-aec5-592bb74de452

**Comment by strepanier03** [comment] 2024-09-21 00:54
@bfitzexpensify - I am going OoO until the 3rd of October and I didn't get to this before I headed out. Thanks for taking over 🙌

**Comment by deetergp** [comment] 2024-09-23 18:34
I was able to reproduce this. 

@marcaaron Do you think this is something we can make external?

**Comment by marcaaron** [comment] 2024-09-24 00:06
Maybe? I'd kinda still like to hear from @JmillsExpensify and @yuwenmemon on this. I'm not sure if this is something we should fix as a "bug" or scope into a future project. There's also the question "Tag rules" still being behind a beta. So, I'd wonder if this is a blocker or not for removing that beta.

**Comment by deetergp** [comment] 2024-09-25 17:41
@JmillsExpensify @yuwenmemon Any thoughts to add here regarding Marc's [comment](https://github.com/Expensify/App/issues/49543#issuecomment-2369813468)?

**Comment by bfitzexpensify** [comment] 2024-10-01 10:23
Bump @JmillsExpensify @yuwenmemon re [this comment](https://github.com/Expensify/App/issues/49543#issuecomment-2369813468)

**Comment by yuwenmemon** [comment] 2024-10-02 18:47
Seems like a bug to me. cc @dylanexpensify 

I would say we should fix this independently because the multi-tags project won't touch this part of the tag editor anyway.

**Comment by deetergp** [comment] 2024-10-07 15:48
Okay, I am going to make this external and handle it here.

**Comment by rezkiy37** [comment] 2024-10-16 10:10
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-10-16 14:17
I can confirm that the problem is replicable. However, it requires a couple of betas: `categoryAndTagApprovers` and `workspaceRules`. I am preparing a proposal.

<details><summary>Details</summary>

<img width="1897" alt="Screenshot 2024-10-16 at 16 16 44" src="https://github.com/user-attachments/assets/998457eb-1273-46e6-ae75-040ed580e01c">

</details>

**Comment by rezkiy37** [comment] 2024-10-16 14:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tag rules settings are available for multi-tags when the rules are not present on Old Dot.

### What is the root cause of that problem?
There are no conditions to restrict the tag rule settings for multi-tags now. 

### What changes do you think we should make in order to solve the problem?
I am proposing to add one more condition to the tag settings page (`TagSettingsPage.tsx`) - `!isMultiLevelTags` (_not multi-level tags_).

https://github.com/Expensify/App/blob/2c211a03948ebc1dfb20ee2f836d9669051acf2f/src/pages/workspace/tags/TagSettingsPage.tsx#L157-L161

The file already has this variable here.

https://github.com/Expensify/App/blob/2c211a03948ebc1dfb20ee2f836d9669051acf2f/src/pages/workspace/tags/TagSettingsPage.tsx#L87

### What alternative solutions did you explore? (Optional) 
N/A

**Comment by situchan** [comment] 2024-10-16 18:13
I can take this as C+ while @parasharrajat is [OOO until Oct 25](https://expensify.slack.com/archives/C02NK2DQWUX/p1729054287998729)

**Comment by deetergp** [comment] 2024-10-17 17:52
Swapped out @parasharrajat for @situchan. Thanks for stepping up, Situ!

**Comment by situchan** [comment] 2024-10-17 19:22
> restrict the tag rule settings for multi-tags for now

So this is what we landed!

The [proposal](https://github.com/Expensify/App/issues/49543#issuecomment-2417038997) looks good. I think we can continue PR.
🎀👀🎀 C+ reviewed

**Comment by deetergp** [comment] 2024-10-18 17:31
@rezkiy37 Proposal looks good. Adding them now.

**Comment by rezkiy37** [comment] 2024-10-21 09:02
I've opened a PR (https://github.com/Expensify/App/pull/50917) for review 🙂

**Comment by situchan** [comment] 2024-11-04 07:57
There was no regression.

### Regression Test Proposal

Precondition:
The rules are enabled.
Dependent multi-tags are set up on OD.

1. Go to workspace settings > Tags.
2. Click on any main tag.
3. Click on any sub tag.
4. Verify that the tag rules should not be available for multi-tags.

**Closed** 2024-11-04 17:08 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
