### ISSUE TITLE
Members list blinking when user goes from offline to online - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11084] opened 2022-09-19 04:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. turn off Internet Connection
 2. Go to settings > Workspace >Manage Members
 3. turn on Internet Connection
 4. check members list

## Expected Result:
Members list should not blink

## Actual Result:
Members list should  blinking

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190949938-62dc9b37-da1c-450e-90be-a73988b05f41.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661604591133289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-09-19 05:58
oh interesting, I'm not sure if this will be part of the bigger offline project. I can't find any other GHs related to this but going to get a second opinion from eng about this fix happening now or later.

**Comment by stitesExpensify** [comment] 2022-09-19 21:43
cc @vitHoracek do you know if this is already being worked on in the policy refactor?

**Comment by mountiny** [comment] 2022-09-20 08:17
@stitesExpensify I havent worked on this one specifically so I am not sure. I think it was @neil-marcellini who worked on policy related refactorings. 

However, I have seen this blinking on unstable wifi in multiple components, so this actually might be related to the offline indicator.

**Comment by stitesExpensify** [comment] 2022-09-20 16:16
So it looks like we will be doing some work on the members list page then, should we just put this on hold until those are done?

**Comment by stitesExpensify** [comment] 2022-09-26 16:33
bump @neil-marcellini any thoughts on :that: ?

**Comment by neil-marcellini** [comment] 2022-09-27 15:39
Hmm I'm really not sure. I don't think we should hold on this, it seems unrelated to any refactors we are doing. cc @arosiclair and @chiragsalian.

**Comment by arosiclair** [comment] 2022-09-27 16:09
Yeah I'm not sure what could be causing this either. FWIW I can't repro this on Android v1.2.5-2

**Comment by stitesExpensify** [comment] 2022-09-29 18:50
hmm do you know if this is still happening @mvtglobally ?

**Comment by stitesExpensify** [comment] 2022-10-03 17:40
Waiting to see if this is still reproducible

**Comment by stitesExpensify** [comment] 2022-10-06 14:50
Still waiting for confirmation that this is broken

**Comment by mountiny** [comment] 2022-10-10 08:56
I think it does not need to be daily now as we wait to see what are the reproduction steps

**Comment by stitesExpensify** [comment] 2022-10-20 21:50
@mvtglobally is this still on the list of issues we're testing?

**Comment by stitesExpensify** [comment] 2022-10-31 22:04
bump @mvtglobally

**Comment by mvtglobally** [comment] 2022-10-31 22:31
@stitesExpensify 
Team checked on recent build and issue is not repro https://user-images.githubusercontent.com/43995119/199122285-b888b733-40df-4986-ab3a-b77967363a88.MOV
https://user-images.githubusercontent.com/43995119/199122306-66d77a80-bc5b-408f-b4b5-dc1fbabd1f83.MOV

**Comment by stitesExpensify** [comment] 2022-10-31 22:50
Great, thanks!

**Closed by stitesExpensify** 2022-10-31 22:50 UTC
Labels: Engineering, Weekly, Bug
