### ISSUE TITLE
Split Bill - Page Freezes After Hitting the Split bill Button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22945] opened 2023-07-15 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot on mweb or web.
2. Go to any chat and click the "+" FAB.
3. Click on split bill and type amount.
4. Click on Next button and click on split button.

## Expected Result:
Split bill amount and continue without freezing.

## Actual Result:
Hitting the split bill button causes the page to freeze.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/61641581-93a5-4735-a97b-cc05dfa0ec99

https://github.com/Expensify/App/assets/93399543/34a26ee3-d385-4ad2-82e8-620fbbb78df0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jo-ui
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689354587381659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-07-19 13:25
I'm not able to reproduce this one.

**Comment by jo-ui** [comment] 2023-07-19 14:02
When splitting bill among many users this issue occurs, try it in large group with many users.

**Comment by jo-ui** [comment] 2023-07-19 14:07
Contributor details
Your Expensify account email: jhon.benex@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fe71dd923c718f93

**Comment by JmillsExpensify** [comment] 2023-07-24 22:26
Still not able to reproduce this. Most recently tried on iOS / Safari.

**Comment by jo-ui** [comment] 2023-07-27 19:33
@JmillsExpensify I saw a dupe issue with mine that has been posted on upwork #23470  after I issued this bug.

**Comment by JmillsExpensify** [comment] 2023-08-02 04:24
Testing again. Wasn't reproducible in Mac OS / Safari. Closing.

**Closed by JmillsExpensify** 2023-08-02 04:24 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by BhuvaneshPatil** [comment] 2023-08-13 03:18
This is reproducible

**Comment by BhuvaneshPatil** [comment] 2023-08-13 03:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill - App crashing when make a split bill in a group chat with a new users

### What is the root cause of that problem?
In the method - `createSplitsAndOnyxData` in `IOU.js` we are using `participant.login` value at few places.

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L476

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L598

https://github.com/Expensify/App/blob/ed2c287daf6a1d59f4f43a9bfc84128597575730/src/libs/actions/IOU.js#L667

When we create a new user using email while creating group, the value for `login` property is undefined.
<img width="303" alt="Screenshot 2023-08-13 at 12 38 26 AM" src="https://github.com/Expensify/App/assets/27822551/903fd59c-4ceb-4253-b177-e22a844acf27">

And the error is saying that we can't have undefined as a value for that.
<img width="436" alt="Screenshot 2023-08-13 at 12 39 16 AM" src="https://github.com/Expensify/App/assets/27822551/ae5c6544-e5be-4c87-aea7-1ee2780a0bf7">

### What changes do you think we should make in order to solve the problem?
When we create a new user, the value for `text` in `participants` (in `createSplitsAndOnyxData` method) has same value as the email/phone that was used to create the account.
<img width="303" alt="Screenshot 2023-08-13 at 12 38 26 AM" src="https://github.com/Expensify/App/assets/27822551/8f6d2e7c-fc2e-4499-aed5-dc3fc4b30426">


We can use that on the places mentioned above - 
```js
participant.login || participant.text
```

In this way we will always prefer the login value and in case new user (where login is undefined) we will take `text` as a value.
### What alternative solutions did you explore? (Optional)

**Comment by jo-ui** [comment] 2023-08-13 11:22
@JmillsExpensify This issue is still reproducible. Please consider it.
