### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] [Distance] -  App does not refocus on address field on delete and cancel

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27182] opened 2023-09-11 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click plus and open request money
3. Click on distance
4. Click on Add stop
5. Open newly created stop
6. Click on 3 dots and click on delete waypoint
7. Click cancel in confirmation popup
8. Observe that address field is not focused

## Expected Result:
App should focus back on address field on delete and cancel as we do for normal report messages

## Actual Result:
App does not focus back on address field on delete and cancel

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bedf1738-25c7-413e-859b-ea4e03190148

https://github.com/Expensify/App/assets/93399543/5e48dee5-1c5a-4b7b-88fe-92c060c4a885

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694111463191149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0115c7c503e332eb0f</li>
        <li>Upwork Job ID: 1701291764562169856</li>
        <li>Last Price Increase: 2023-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 26724773</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-09-11 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App does not refocus on address field on delete and cancel.
### What is the root cause of that problem?
We are not focusing on input when modal is closed.
### What changes do you think we should make in order to solve the problem?
We can call this function when close modal.
```
    const onModalHide = useCallback(() => {
        setIsDeleteStopModalOpen(false)
        if (textInput === null || textInput.current === null) {
            return;
        }
        const timeout = _.delay(() => {
            textInput.current.focus();
        }, 500);
        return () => clearTimeout(timeout);
    }, [textInput]);
```
https://github.com/Expensify/App/blob/9d8518a531eea368f855af4406b1aa5a8c3a7fa9/src/pages/iou/WaypointEditor.js#L183-L191

### What alternative solutions did you explore? (Optional)

**Comment by CortneyOfstad** [comment] 2023-09-14 18:46
@mananjadhav Any thoughts on the proposals above? TIA!

**Comment by mananjadhav** [comment] 2023-09-17 18:14
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/27182#issuecomment-1714342982) looks like will work.

🎀 👀 🎀 C+ reviewed.

**Comment by sobitneupane** [comment] 2023-09-27 09:28
@mananjadhav Looks like we have a regression related to this issue.

**Comment by amyevans** [comment] 2023-09-28 04:37
Okay so it sounds like we should just revert https://github.com/Expensify/App/pull/27653 and close this issue as expected behavior, is that your understanding @mananjadhav @tienifr?

**Comment by mananjadhav** [comment] 2023-10-02 15:03
@amyevans Apologies I was OOO. I think we should revert? I don't see that done here. I also I think we should add an item to the checklist so that this doesn't come up again.

**Comment by amyevans** [comment] 2023-10-03 02:20
Agreed on adding a checklist item.

I've opened the revert PR if you could review: https://github.com/Expensify/App/pull/28677

Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-03 15:40
Sorry friends, was OoO so trying to catch up here — we can close this out?

**Comment by amyevans** [comment] 2023-10-03 23:26
@CortneyOfstad No, we're going to revert the PR actually, since the original behavior was decided deliberately previously and we should keep it 🙃

**Comment by CortneyOfstad** [comment] 2023-10-04 14:56
No worries! Thanks for the clarification @amyevans!

**Comment by Beamanator** [comment] 2023-10-06 06:15
Seems the PR for this got reverted here: https://github.com/Expensify/App/pull/28677

Should we add this focus issue to this focus issue tracker? https://github.com/Expensify/App/issues/15992

Also it seems like this bug was created when testing the revert PR: https://github.com/Expensify/App/issues/28921, I assume the revert didn't cause the bug, but maybe we can fix both focus bugs at the same time?

**Comment by Beamanator** [comment] 2023-10-12 14:59
Quick bump, can we fix https://github.com/Expensify/App/issues/28921 as part of this one, or should it be separate?

**Comment by amyevans** [comment] 2023-10-13 13:52
@Beamanator sorry, I totally missed your question the first time. The summary of this GH is that we've introduced no changes to the app and the GH will be closed as expected behavior. I see you've added them both to the tracking issue, thanks! I think that's the best course of action - we can come back to these GHs at a later date and approach more holistically, because honestly it's not efficient trying to address them each separately with a different group of individuals.

**Comment by CortneyOfstad** [comment] 2023-10-13 14:08
After an internal discussion with the team, it was decided that this is expected behavior, so this GH will be closed. 

However, due to the work by @mananjadhav and @Krishna2323 as C+ and contributor on working on the PR, it was decided to offer a 50% payment. 

@dhanashree-sawant also offering you 50% for the reporting — this has been paid in Upwork 👍 

@mananjadhav if you would like to request that in NewDot, I will get a payment summary posted below. 

@Krishna2323 I've paid you via Upwork, so you are all set 👍

**Comment by CortneyOfstad** [comment] 2023-10-13 14:09
## Payment Breakdown

Breakdown found here — https://github.com/Expensify/App/issues/27182#issuecomment-1750132780

**Comment by mananjadhav** [comment] 2023-10-13 14:10
Thanks @CortneyOfstad, yes would need payment summary.

**Comment by CortneyOfstad** [comment] 2023-10-16 18:55
@amyevans Does that sound fair to you for compensating @tienifr as well? Just want a second pair of eyes — thanks!

**Comment by amyevans** [comment] 2023-10-17 14:10
👍

**Comment by CortneyOfstad** [comment] 2023-10-17 14:17
Alright @tienifr, after an internal discussion it was decided to offer $50 as a "bug reporter" for this issue in regards to expected behavior. 

If possible, can you send over your Upwork profile so I can make sure that I am sending the proposal to the correct individual? Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-17 17:15
Perfect! Just sent the proposal @tienifr 👍

**Comment by CortneyOfstad** [comment] 2023-10-17 17:57
@tienifr you have been paid 👍 

## Payment Summary

External issue reporter – @dhanashree-sawant paid $25 (50%) in Upwork
Contributor that fixed the issue — @Krishna2323 paid $250 (50%) in Upwork
Contributor+ that helped on the issue and/or PR — @mananjadhav **to be paid $250 (50%) in NewDot** 
Additional payment — @tienifr paid $50 in Upwork for helping to find that it was expected behavior, not a bug

**Closed** 2023-10-17 17:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-17 21:13
@250 payment approved for @mananjadhav based on summary above.
