### ISSUE TITLE
[HOLD for payment 2023-12-08] [HOLD for payment 2023-12-06] [$125] [Form Provider Refactor] IdologyQuestions

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#30313] opened 2023-10-24 23:41 UTC
Coming from https://github.com/Expensify/App/issues/25397#issuecomment-1743272245, we created a new Form provider that works with functional components and we need to refactor all usages of the old Form component.

This issue is specific to refactoring `src/pages/EnablePayments/IdologyQuestions.js`

cc @kowczarz @cdOut
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e0b2b5e81ad4761</li>
        <li>Upwork Job ID: 1716963167990067200</li>
        <li>Last Price Increase: 2023-10-26</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-10-25 18:17
@cdOut will you be working on this issue too?

**Comment by cdOut** [comment] 2023-10-26 09:57
@luacmartins yes, I will be working on this issue.

**Comment by s77rt** [comment] 2023-10-30 09:01
Not overdue. @cdOut Will work on this

**Comment by sonialiap** [comment] 2023-11-01 13:47
@cdOut any updates? :)

**Comment by cdOut** [comment] 2023-11-02 13:19
I will put up a draft PR soon, was working on the form refactor with Kamil but since he's OOO now I took all of the task so the work might be a little slower

**Comment by s77rt** [comment] 2023-11-06 09:24
Not overdue. @cdOut is still working on this

**Comment by luacmartins** [comment] 2023-11-08 19:25
We're still working on this

**Comment by kowczarz** [comment] 2023-11-09 13:40
Hello, I'm back from OOO and I will help @cdOut with that task

**Comment by s77rt** [comment] 2023-11-13 09:03
@kowczarz Any updates?

**Comment by s77rt** [comment] 2023-11-14 15:19
Still working on it

**Comment by s77rt** [comment] 2023-11-21 12:21
Ignore above message ^ The linked PR is not merged yet. It's fixing the deploy blocker not causing it.

**Comment by s77rt** [comment] 2023-11-29 13:32
Checklist ^ not due yet. PR is reverted.

**Comment by s77rt** [comment] 2023-12-01 17:07
- The PR that introduced the bug has been identified: n/a Not a bug but a code refactor
- The offending PR has been commented on: n/a
- A discussion in #expensify-bugs has been started: n/a
- Determine if we should create a regression test for this bug: n/a

**Comment by sonialiap** [comment] 2023-12-08 10:26
@s77rt $125 - offer sent

[New upwork post](https://www.upwork.com/jobs/~012dcaf1a673eaac6a)

**Comment by s77rt** [comment] 2023-12-08 17:31
Accepted! Please note that the payment due here is $62.5 (since there was a regression)

**Comment by sonialiap** [comment] 2023-12-11 13:10
@s77rt thanks for the correction. $62.50 has been paid out to you

**Closed by sonialiap** 2023-12-11 13:10 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
