### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] IOU - Losing focus on the amount input field when switching between apps

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26505] opened 2023-09-01 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app in fullscreen view
2. Tap on FAB
3. Tap on Request money or Split bill
4. Switch to other app by swiping with 3 fingers gesture (do not use comant +tab)
5. Open back the New Expensify app by swiping with 3 fingers gesture (do not use comant +tab)
6. Press any number keys on the keyboard

## Expected Result:
Amount input label should be focused when user switched back to the app

## Actual Result:
Losing focus on the amount input field for Request Money/Split bills when switching between apps by 3 fingers swipe gesture when app in fullscreen view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/f9dbcacb-48f4-4245-b378-d52632fe76d9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f419594d979a6b3d</li>
        <li>Upwork Job ID: 1700176267856764928</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26746042</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-09-02 09:52
### Proposal 
##  Problem
IOU - Losing focus on the amount input field when switching between apps

### Root Cause
When user is switch window the focus is lost from text input and when user is back to app input is not focussed

### Chnages
we can use visibility listner to focus back on textInput
```
useEffect(() => {
        const unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            // focus the text input when the app is back in the foreground
            if (Visibility.isVisible() && textInput.current) {
                textInput.current.focus();
            }
        });
```
        return () => {
            unsubscribeVisibilityListener();
        };
    }, []);

**Comment by ishpaul777** [comment] 2023-09-07 19:49
@lanitochka17 No one is assigned to the issue, looks like automation failed.

**Comment by CortneyOfstad** [comment] 2023-09-08 15:56
Getting eyes on this 👍

**Comment by pradeepmdk** [comment] 2023-09-08 17:27
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Losing focus on the amount of input field when switching between apps

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/153ab36f8d9392e83b46b4b57df7a4dfe7dcef60/src/components/TextInput/index.js#L25

here two is issues First we allow only mobile chrome and `DomUtils.getActiveElement()` when the app is switched between apps focused on the body.

### What changes do you think we should make in order to solve the problem?

we can use new props `isVisibleFoucs` on `TextInput` we will pass in the param from `MoneyRequestAmountForm` (these props pass all child components) If isVisibleFoucs props are true means we set the focus.

**Comment by CortneyOfstad** [comment] 2023-09-11 15:41
@eVoloshchak any thoughts on the proposals above?

**Comment by CortneyOfstad** [comment] 2023-09-14 18:10
@eVoloshchak Bump ^^^

**Comment by eVoloshchak** [comment] 2023-09-14 20:03
Oh wow, thank you for linking that discussion @tienifr 
I think that's the approach we should take, there's only one issue I could foresee

> That is ok because in Android/iOS, the user can already immediately type the numbers in our own defined keyboard, so there's no need for the input to regain focus.

It's kind of an edge case, but would that work if the user has an external keyboard connected?

**Comment by CortneyOfstad** [comment] 2023-09-18 15:13
Bump @eVoloshchak on the comment above ^^^ — TIA!

**Comment by eVoloshchak** [comment] 2023-09-18 16:34
@tienifr's [proposal](https://github.com/Expensify/App/issues/26505#issuecomment-1712818332) looks good to me!

> Because the input is not focused, so they can not use external keyboard. They can use it when users focus on the input

This is also the behavior we currently have, it won't be altered with the fix

🎀👀🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment] 2023-10-03 15:24
## Payment Breakdown

- Reporter — Applause, so no payment
- Contributor — @tienifr, paid $500 as it did not qualify for bonus
- C+ — @eVoloshchak to be paid in NewDot ($500)

**Comment by eVoloshchak** [comment] 2023-10-04 13:04
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/6811
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/6811/files#r1345751207
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this type of bug is easy to catch when testing, the only complication here is that it's specific to only a single platform (Desktop)
- Determine if we should create a regression test for this bug. While the bug doesn't impact user experience, there is a probability of it re-appearing with a RN/Electron/MacOS update, all of which are outside of our control. I think we might want to implement a regression test

**Comment by eVoloshchak** [comment] 2023-10-04 13:06
**Regression Test Proposal**
web/mweb/desktop

1. Open the app in fullscreen view
2. Tap on FAB
3. Tap on Request money or Split bill
4. Switch to another app by swiping with 3 fingers gesture (do not use command+tab)
5. Open back the New Expensify app by swiping with 3 fingers gesture (do not use command+tab)
7. Verify that the amount input is focused when you switched back to the app

**Do we agree 👍 or 👎**

**Comment by eVoloshchak** [comment] 2023-10-04 13:08
> when @tienifr got assigned: 2023-09-19 04:05:42 Z
when the PR got merged: 2023-09-22 08:08:07 UTC
the pull request did not get merged within 3 working days of assignment.

I don't think that's correct, the PR was merged on 22th, which isn't a working day, so it was merged in 2 business days I think

@CortneyOfstad, could you double-check that please?

**Comment by CortneyOfstad** [comment] 2023-10-09 13:49
@thienlnam Does that sound correct to you ^^^

Just want a second pair of eyes on this

**Comment by thienlnam** [comment] 2023-10-09 19:28
Why isn't the 22nd a working day? Granted the PR was approved and required no updates from me on the 21st, so we can give the bonus here

**Comment by eVoloshchak** [comment] 2023-10-09 19:39
> Why isn't the 22nd a working day?

Oh my bad, I was looking at the calendar for October by mistake
Sorry for the confusion😅

**Comment by CortneyOfstad** [comment] 2023-10-11 13:21
No worries @eVoloshchak! I sent you a proposal in Upwork for the additional $250 bonus amount. Please let me know once you approve it!

Creating the regression test GH now 👍

**Comment by eVoloshchak** [comment] 2023-10-11 13:37
No need for Upwork, I'll just send the payment request via NewDot

**Comment by CortneyOfstad** [comment] 2023-10-11 13:55
Sounds good! Closing!

**Comment by CortneyOfstad** [comment] 2023-10-11 13:56
## Payment Breakdown:

 External issue reporter — Applause, so does not require payment
 Contributor that fixed the issue — @tienifr paid **$500 (**does not qualify to the bonus based)
 Contributor+ that helped on the issue and/or PR — @eVoloshchak paid via NewDot ($500) — **additional $250 to be paid via NewDot**

**Closed by CortneyOfstad** 2023-10-11 13:55 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-11 15:06
$750 payment approved for @eVoloshchak based on summary immediately above.
