### ISSUE TITLE
[$2000] HIGH: Implement Comment Linking

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#20282] opened 2023-06-06 16:34 UTC
This is a public issue to track implementation of [the Comment Linking feature](https://github.com/Expensify/Expensify/issues/147480) (internal link).

Margelo will work on the App implementation of this project

[Design doc can be found here - also internal](https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#heading=h.ns12dr1f35rx)

# Roll out plan

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116b1ab0be62d4242</li>
        <li>Upwork Job ID: 1777848479203676160</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by perunt** [comment] 2023-06-06 16:40
I would like to do this

**Comment by puneetlath** [comment] 2023-06-12 13:42
@chiragsalian I don't think you need me here so going to un-assign. But feel free to re-assign me if I missed something.

**Comment by perunt** [comment] 2023-06-19 07:22
@chiragsalian could you apply the `Review` label to this doc?

**Comment by mountiny** [comment] 2023-06-19 08:11
[Design doc link](https://docs.google.com/document/d/1v-ZaIRTZL5LIsyPWB0IopBNNgCajf5WC1OA8cVKtd8I/edit#heading=h.ns12dr1f35rx) here.

**Comment by sarajojacobson** [comment] 2023-06-19 13:10
I have read and reviewed this Design Doc.

**Comment by flodnv** [comment] 2023-06-23 18:22
I have read and reviewed this Design Doc!

**Comment by StefStavri** [comment] 2023-06-28 11:51
I have read and reviewed this Design Doc!

**Comment by chiragsalian** [comment] 2023-07-05 18:19
In progress, looks like we got most of the review comments. @robertjchen would you also be able to review the comment linking design doc soon (asking cause you are the only product manager reviewer pending before we can move to the technical section review)

**Comment by robertjchen** [comment] 2023-07-06 10:30
I have read and reviewed this Design Doc!

**Comment by chiragsalian** [comment] 2023-07-10 17:33
Alright looks like we got the required number of high-level reviews. Let's move ahead to the technical review.
@perunt when you get a chance remember to go over all high-level comments and address them.

**Comment by cead22** [comment] 2023-07-10 18:04
I have read and reviewed this Design Doc!

**Comment by CortneyOfstad** [comment] 2023-07-10 18:44
I have read and reviewed this Design Doc!

**Comment by johnmlee101** [comment] 2023-07-10 20:49
I have read and reviewed this Design Doc!

**Comment by laurenreidexpensify** [comment] 2023-07-11 09:22
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment] 2023-07-12 21:44
I'm going help shepherd this initiative while @chiragsalian's away.

**Comment by roryabraham** [comment] 2023-07-12 21:46
Still need 3 non-engineering product managers / generalists to review the detailed, and 2 project managers.

**Comment by joelbettner** [comment] 2023-07-13 00:01
I have read and reviewed this Design Doc!

**Comment by robertjchen** [comment] 2023-07-13 11:04
I have read and reviewed this Design Doc!

**Comment by stephanieelliott** [comment] 2023-07-17 06:32
I have read and reviewed this Design Doc!

**Comment by StefStavri** [comment] 2023-07-17 10:23
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment] 2023-07-17 17:06
I just updated the rollout plan to include a bit more detail.

At this point, this doc has gone through many reviews and revisions, and we are only short 2 non-engineering generalists, so I'm doing a _last call_ here. This project will go into the implementation phase tomorrow.

**Comment by anmurali** [comment] 2023-07-17 22:45
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment] 2023-07-19 22:04
Going to move this forward into the implementation phase and start creating issues now.

**Comment by roryabraham** [comment] 2023-07-19 22:09
Created a project board to start tracking implementation: https://github.com/orgs/Expensify/projects/62/views/1, also created an internal issue to make that project board publicly visible

**Comment by roryabraham** [comment] 2023-07-20 00:30
Alright, all the issues have been created. Feel free to follow the implementation in the [GitHub Project](https://github.com/orgs/Expensify/projects/62/views/1)

**Comment by JmillsExpensify** [comment] 2023-07-24 12:50
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment] 2023-07-26 17:51
Posted project update in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1690393798476199

**Comment by HaleyJacobson** [comment] 2023-08-04 17:30
I have read and reviewed this Design Doc!

**Comment by roryabraham** [comment] 2023-08-08 21:45
Weekly update:

- We have a [PR in review](https://github.com/Expensify/Auth/pull/8412) for `GetOlderActions` and `GetNewerActions`
- `previousReportActionID` Onyx migration PR was just merged
- Front-end FlatList bugs are fixed (we still need to finish upgrading react-native-web, which just came off hold)
- I am still working on adding `previousReportActionID` to all reportActions in Auth. It's taken longer than it should have, but should be ready for review by EOD

**Comment by chiragsalian** [comment] 2023-08-25 16:57
Not overdue, still in progress.

**Comment by roryabraham** [comment] 2023-09-04 14:21
Hey, sorry my updates here have been lackluster on this issue, but I did drop an update in slack last week [here](https://expensify.slack.com/archives/C035J5C9FAP/p1693329936355999)

**Comment by roryabraham** [comment] 2023-09-13 09:25
@aldo-expensify raised his hand on https://github.com/Expensify/App/issues/23218, thanks @aldo-expensify! I'm still working on https://github.com/Expensify/Web-Expensify/pull/38662

Also, I'm making this issue a daily since we're shooting to finish this by end-of-offshore

**Comment by roryabraham** [comment] 2023-09-19 05:48
We had a number of PRs merged for this last week. Still working on the [last backend piece](https://github.com/Expensify/Web-Expensify/pull/38662) then this should be prettymuch all front-end.

**Comment by roryabraham** [comment] 2023-09-22 03:38
Actively implementing :working:

**Comment by roryabraham** [comment] 2023-09-25 07:30
`previousReportActionID` isn't really working due to old reportActions being cached in PHP. Created https://github.com/Expensify/Auth/pull/8764 to fix it

**Comment by roryabraham** [comment] 2023-09-29 10:16
Quick EOW update:

- I still need to re-review https://github.com/Expensify/App/pull/26166, but haven't been urgently prioritizing because there's still an issue with the back-end logic for `previousReportActionID`, which will be needed for the next step which actually enables comment linking
- The [back-end PR](https://github.com/Expensify/Auth/pull/8764) has been ready and approved for 3 days, but has been held up by failing tests in Web-Expensify – some which needed to be temporarily disabled and others which are unrelated and failing on main.

**Comment by roryabraham** [comment] 2023-10-12 03:42
Has been delayed by my OOO but I just commented on the PR to hopefully help unblock it

**Comment by cristipaval** [comment] 2023-10-19 20:52
Did Melvin assign me by mistake or I'm missing something

**Comment by roryabraham** [comment] 2023-12-07 04:44
Going to remove the reviewing label here so it's not greyed out in my K2

**Comment by roryabraham** [comment] 2023-12-15 20:02
Here's a summary of all the work I'm tracking related to this project:

- https://github.com/Expensify/App/pull/32098
    - Pinged people in slack to try to push to get this ready for review: https://expensify.slack.com/archives/C035J5C9FAP/p1702669706129149 https://expensify.slack.com/archives/C02NK2DQWUX/p1702669521713009
- https://github.com/Expensify/App/pull/32843 (on HOLD for https://github.com/Expensify/App/pull/32098)
- https://github.com/Expensify/App/pull/30269 (on HOLD for both previous issues)
- https://github.com/Expensify/App/issues/23231 (on HOLD for https://github.com/Expensify/App/pull/30269)

Other work which has been discussed but which I'm not actively tracking:

- adding automated UI tests around the comment linking / bidirectional pagination features
- ReportScreen performance audit

**Comment by roryabraham** [comment] 2023-12-27 22:47
Latest update [here](https://expensify.slack.com/archives/C035J5C9FAP/p1703174259992289), awaiting an update in https://github.com/Expensify/App/pull/32098

**Comment by roryabraham** [comment] 2024-01-09 05:25
Ok, so @0xmiroslav still hasn't approved https://github.com/Expensify/App/pull/32098 but at this point I think I'm going to just do some thorough review and testing myself

**Comment by roryabraham** [comment] 2024-01-09 06:05
https://github.com/Expensify/App/pull/32098 has been merged

**Comment by quinthar** [comment] 2024-02-01 04:46
Closing this for https://github.com/Expensify/App/pull/30269

**Comment by roryabraham** [comment] 2024-04-10 00:00
@puneetlath I reopened this so that @ishpaul777 can get paid for his role as a C+ for comment linking. I suggest a payment of $1000 with no regression penalties because:

- this was a big, challenging PR
- @ishpaul777 was very diligent in going above-and-beyond to help us resolve any regressions created by the feature

**Comment by roryabraham** [comment] 2024-04-10 22:47
Hi @ishpaul777, I chatted with @puneetlath and given the difficulty and scope of work, along with all the extra time you spent going above-and-beyond to help deliver the feature, we're willing to authorize $2000 for this issue 👍🏼

**Comment by puneetlath** [comment] 2024-04-11 15:00
Sent you an offer @ishpaul777: https://www.upwork.com/nx/wm/offer/101826333

Please ping me here when you've accepted.

**Comment by puneetlath** [comment] 2024-04-11 15:10
Great, paid. Thanks everyone. Exciting to have comment linking out in the wild!

**Closed by puneetlath** 2024-04-11 15:10 UTC
Labels: Reviewing, External, Engineering, Daily, NewFeature
