### ISSUE TITLE
[HOLD for payment 2023-09-08] [$1000] Web - The title of the details page for threads created in workspace rooms is not truncated.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25801] opened 2023-08-23 21:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Open any workspace room ( #announce or #admin ).
3. Send a long message
4. Open this message in a thread and open this thread.
5. Click in the header of the thread room to open the details page.

## Expected Result:
The title of the details page for threads created in workspace rooms should be truncated for the long message, like other threads in other rooms.

## Actual Result:
The title of the details page for threads created in workspace rooms is not truncated for the long message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.56-21

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1c89e29c-45e8-480f-b12f-ad0a4262a1ce

https://github.com/Expensify/App/assets/115492554/73a5de3b-cba1-44a5-bd08-bd991ed40468

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691720994996269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a07cbaf1626f8e4</li>
        <li>Upwork Job ID: 1695146256735473664</li>
        <li>Last Price Increase: 2023-08-25</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26413756</li>
<li>Ahmed-Abdella | Reporter | 26413758</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-08-23 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The title of the details page for threads created in workspace rooms is not truncated.
### What is the root cause of that problem?
in this PR https://github.com/Expensify/App/pull/23357 we don't truncate long room names in room details page.
https://github.com/Expensify/App/blob/9418b870515102631ea2156b5ea253ee05a98ff1/src/pages/ReportDetailsPage.js#L157
so all threads in chat room don't truncate also

### What changes do you think we should make in order to solve the problem?
we need to check if it not thread `(isChatRoom && !isThread)` instead of `isChatRoom`
```javascript
// numberOfLines={isChatRoom ? 0 : 1}
// textStyles={[styles.textHeadline, styles.textAlignCenter, isChatRoom ? undefined : styles.pre]}

numberOfLines={(isChatRoom && !isThread) ? 0 : 1}
textStyles={[styles.textHeadline, styles.textAlignCenter, (isChatRoom && !isThread) ? undefined : styles.pre]}

```

### What alternative solutions did you explore? (Optional)

**Comment by studentofcoding** [comment] 2023-08-26 07:08
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
The title of the details page for threads created in workspace rooms is not truncated.

## What is the root cause of that problem?
We didn't include the condition to handle the thread of the chat room as it's also a chat room. So if the title of the Threads detail page is Very Long, is not truncated.

## What changes do you think we should make in order to solve the problem?

- On [ReportDetailsPage.js](https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/pages/ReportDetailsPage.js)

1. We need to create a new variable called isAlsoChatRoom `const isAlsoChatRoom = isChatRoom && !isThread;` to manage Long Thread Title that's also a part of Chat Room (This way it'll be better for keeping the logic in one variable also)  
2. Called `isAlsoChatRoom` into these props of `DisplayNames` component (`numberOfLines`, `textStyles` & `isEllipsisActive`) like the below code (see that we called this inside isEllipsisActive so that we have an ellipsis at the end of the Long Title)
```
<DisplayNames
        fullTitle={ReportUtils.getReportName(props.report)}
        displayNamesWithTooltips={displayNamesWithTooltips}
        tooltipEnabled
        numberOfLines={isAlsoChatRoom ? 0 : 1} // Called isAlsoChatRoom here 
        textStyles={[styles.textHeadline, styles.textAlignCenter, isAlsoChatRoom ? undefined : styles.pre]} // here
        shouldUseFullTitle={shouldUseFullTitle}
        isEllipsisActive={isAlsoChatRoom} // and here
/>
```
@burczu @isabelastisser 
## Result

This way The Long title is always truncated & ellipsis like the example below 

<img width="1440" alt="Long Title Truncated and Ellipsis" src="https://github.com/Expensify/App/assets/20473526/e139635d-0dec-46d7-8e0e-5a5f309eec55">


https://github.com/Expensify/App/assets/20473526/9c10e335-1b69-4583-9a04-f0ddca501701

## What alternative solutions did you explore? (Optional)

None

**Comment by burczu** [comment] 2023-08-28 12:55
All the proposals are pretty much the same and do the trick - @dukenv0307 was the first with [his one](https://github.com/Expensify/App/issues/25801#issuecomment-1690660568), and I think we should proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-09-05 12:10
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR:
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
* [ ]  [@burczu] Determine if we should create a regression test for this bug.
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by isabelastisser** [comment] 2023-09-12 20:32
Payment summary:

@burczu does not require payment (Contractor)
@dukenv0307 (Contributor) $1000 review, $500 urgency bonus
@Ahmed-Abdella  (Reporter) $250

**Comment by isabelastisser** [comment] 2023-09-12 20:34
all set!

**Closed by isabelastisser** 2023-09-12 20:34 UTC
Labels: External, Weekly, Awaiting Payment, Bug
