### ISSUE TITLE
[HOLD #29199] [$500]  iOS - Composer field loses focus & keypad dismissed when creating thread conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35778] opened 2024-02-04 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exploratory around https://expensify.testrail.io/index.php?/tests/view/4280661&group_by=cases:section_id&group_order=asc&group_id=291937
**Email or phone of affected tester (no customers):** applausetester+cknov@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify
2. Navigate to any conversation
3. Send message
4. Long press on message to open action menu
5. Select "Reply in thread" option
6. User redirected to new conversation page

## Expected Result:
On step 6 - When user redirected to thread conversation, compose field should get focus & keypad to be triggered

## Actual Result:
On step 6 - Composer field loses focus & keypad dismissed when creating thread conversation
Note: When navigated to thread conversation, keypad appears for a moment, but collapses immediately

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/248a5bd3-4a65-4ae3-a23c-f4b951ea3b1a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2a90f0a9fc124c8</li>
        <li>Upwork Job ID: 1754199374010019840</li>
        <li>Last Price Increase: 2024-02-11</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-04 17:45
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by dhruv-dhola** [comment] 2024-02-05 01:43
Step 1 Identify the Root Cause: Review the existing codebase related to the navigation and focus management.
Check for asynchronous operations or race conditions that may cause the loss of focus.

Step2:-Ensure that the navigation to the new conversation page triggers the expected focus behavior on the compose field.
Evaluate the sequence of events during the navigation process and make necessary adjustments.

Step3:-Implement a mechanism to explicitly manage the visibility of the keypad during the transition.
Verify the timing of the keypad appearance and make sure it remains visible when creating a thread conversation.

**Comment by ikevin127** [comment] 2024-02-05 12:17
# Proposal

### Please re-state the problem that we are trying to solve in this issue

On step 6 - Composer field loses focus & keypad dismissed when navigating to Reply in thread conversation.
Note: When navigated to thread conversation, keypad appears for a moment, but collapses immediately.

### What is the root cause of that problem?

Within `ComposerWithSuggestions`, by default on native platforms we disable composer autofocus when navigating to a screen where composer is present as per this comment:

> // We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused.
> // We avoid doing this on native platforms since the software keyboard popping
> // open creates a jarring and broken UX.

Therefore when we navigate to the report thread `shouldAutoFocus` is false.
The keyboard that we see closing is the one opened from the parent report before opening the thread.

There's an additional issue related to the navigation which can be observed when pressing the header Back button while on a thread:
- instead of going back to the parent report, the user is havigated to home

### What changes do you think we should make in order to solve the problem?

Change the current `shouldAutoFocus` variable logic to account for when we navigated to a report thread, using:
- `ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)`

this will set `shouldAutoFocus` to true when we navigate to a report thread.

Important in order to have this logic work well: we have to change the navigation goBack logic within the `ReportScreen` page like so:

```js
    const goBack = useCallback(() => {
        if (ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)) {
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID));
            return;
        }

        Navigation.goBack(ROUTES.HOME, false, true);
    }, [lastReportAction, reportID, report.parentReportID]);
```

by adding the if that checks whether we're in a thread and if so when goBack is called -> navigate back to the parent report instead of navigating to home as it currently happens.

**Comment by ikevin127** [comment] 2024-02-05 12:33
# Proposal

### Please re-state the problem that we are trying to solve in this issue

On step 6 - Composer field loses focus & keypad dismissed when navigating to Reply in thread conversation.
Note: When navigated to thread conversation, keypad appears for a moment, but collapses immediately.

### What is the root cause of that problem?

Within `ComposerWithSuggestions`, by default on native platforms we disable composer autofocus when navigating to a screen where composer is present as per this comment:

> // We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused.
> // We avoid doing this on native platforms since the software keyboard popping
> // open creates a jarring and broken UX.

Therefore when we navigate to the report thread `shouldAutoFocus` is false.
The keyboard that we see closing is the one opened from the parent report before opening the thread. The reason why this drags from parent to thread when navigating is because of this code block:

https://github.com/Expensify/App/blob/d765c37676c79f87a80d42932284f4e3ed176632/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L192-L195

which handles the closing of the context menu after tapping Reply in thread -> the close callback is calling composer focus after the context menu is closed.

Finally, there's an additional issue related to the navigation which can be observed when pressing the header Back button while on a thread:
- instead of going back to the parent report, the user is havigated to home

### What changes do you think we should make in order to solve the problem?

First we need to change the current `shouldAutoFocus` variable logic to account for when we navigated to a report thread, using:
- `ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)`

this will set `shouldAutoFocus` to true when we navigate to a report thread.

This is not enough as below in the `ComposerWithSuggestions` we have a useEffect that includes the comment quoted in the RCA where we have the condition which actually returns when we're on native platforms preventing the focus from being called. So we need to skip the return by adding:
- `!ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)`

which means that the return still applies, except when we're navigating to a thread.

**Important in order to have this logic work well**: we have to change the navigation goBack logic within the `ReportScreen` page like so:

```js
    const goBack = useCallback(() => {
        if (ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)) {
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID));
            return;
        }

        Navigation.goBack(ROUTES.HOME, false, true);
    }, [lastReportAction, reportID, report.parentReportID]);
```

by adding the if that checks whether we're in a thread and if so when goBack is called -> navigate back to the parent report instead of navigating to home as it currently happens.

### Videos

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/7821d0ef-f024-4402-adcb-e33f13a431d0"> | <video src="https://github.com/Expensify/App/assets/56457735/8f66e541-fe15-4e04-9b04-c3ae81ffd0db"> |

</details>

**Comment by ikevin127** [comment] 2024-02-05 13:06
# Proposal

### Please re-state the problem that we are trying to solve in this issue

On step 6 - Composer field loses focus & keypad dismissed when navigating to Reply in thread conversation.
Note: When navigated to thread conversation, keypad appears for a moment, but collapses immediately.

### What is the root cause of that problem?

Within `ComposerWithSuggestions`, by default on native platforms we disable composer autofocus when navigating to a screen where composer is present as per this comment:

> // We want to focus or refocus the input when a modal has been closed or the underlying screen is refocused.
> // We avoid doing this on native platforms since the software keyboard popping
> // open creates a jarring and broken UX.

Therefore when we navigate to the report thread `shouldAutoFocus` is false.
The keyboard that we see closing is the one opened from the parent report before opening the thread. The reason why this drags from parent to thread when navigating is because of this code block:

https://github.com/Expensify/App/blob/d765c37676c79f87a80d42932284f4e3ed176632/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L192-L195

which handles the closing of the context menu after tapping Reply in thread -> the close callback is calling composer focus after the context menu is closed.

Finally, there's an additional issue related to the navigation which can be observed when pressing the header Back button while on a thread:
- instead of going back to the parent report, the user is havigated to home

### What changes do you think we should make in order to solve the problem?

First we need to change the current `shouldAutoFocus` variable logic to account for when we navigated to a report thread, using:
- `ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)`

this will set `shouldAutoFocus` to true when we navigate to a report thread.

Second, as below in the `ComposerWithSuggestions` we have a useEffect that includes the comment quoted in the RCA where we have the condition which actually returns when we're on native platforms preventing the focus from being called. So we need to skip the return by adding:
- `!ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)`

which means that the return still applies, except when we're navigating to a thread.

Finally, in the same useEffect we need to add another if - return to prevent focus(true) from being called in order to avoid another keyboard popup when returning to the parent report from a thread, like so: 

```js
        if (prevIsFocused && !isFocused) {
            return;
        }
        focus(true); // <- finally call focus
```



**Important in order to have this logic work well**: we have to change the navigation goBack logic within the `ReportScreen` page like so:

```js
    const goBack = useCallback(() => {
        if (ReportActionsUtils.isThreadParentMessage(lastReportAction, reportID)) {
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.parentReportID));
            return;
        }

        Navigation.goBack(ROUTES.HOME, false, true);
    }, [lastReportAction, reportID, report.parentReportID]);
```

by adding the if that checks whether we're in a thread and if so when goBack is called -> navigate back to the parent report instead of navigating to home as it currently happens.

### Videos

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/7821d0ef-f024-4402-adcb-e33f13a431d0"> | <video src="https://github.com/Expensify/App/assets/56457735/0c5e5582-d587-41a6-842d-6cde18305fa6"> |

</details>

**Comment by dhruv-dhola** [comment] 2024-02-05 16:10
so in the above video i see there if you open keypad in conversation screen and goes to reply thread then first it close that keypad and again open it. so may be when user navigate to reply thread screen it may be triggered old reference of the keypad first and the process of navigation to one screen to another and keypad focus process happens at same time so i suggest that write code for this block in simultaneously way but there is slightly difference in timing which is minor 2to3 sec.

**Comment by mollfpr** [comment] 2024-02-05 17:04
@dhruv-dhola Please post a proposal using the [PROPOSAL_TEMPLATE](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md), thanks!

---

>instead of going back to the parent report, the user is havigated to home

@ikevin127 We can ignore the above issue, it might be related to the big app structure changes lately.

---

https://github.com/Expensify/App/blob/a1b33ef57861c5b35090c786bfce581f72843d38/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L528-L531

I think this is not a bug. The comment stated that autofocus on the native is creating a UX problem.

**Comment by ikevin127** [comment] 2024-02-05 23:02
@mollfpr If I understand correctly - what we want here is **to not** see the parent report keyboard collapse after we're navigated to the thread, but before that.

> When navigated to thread conversation, keypad appears for a moment, but collapses immediately

Meaning we just fix this part of the **actual result** instead of actually doing what the expected result states ?

## Updated [proposal](https://github.com/Expensify/App/issues/35778#issuecomment-1926959311)
- changed RCA and solution + videos according to different expected result

My updated solution would be a temporary workaround - as there are lots of similar keyboard / focus related issues that will be solved once this PR will be merged https://github.com/Expensify/App/pull/29199.

I don't think it's worth extracting logic from that PR and adding it here as a targeted solution for our specific case.

**Comment by mollfpr** [comment] 2024-02-08 18:30
I would say we can hold for the sake of https://github.com/Expensify/App/pull/29199 and I don't think we can accept a workaround for now.

**Comment by mollfpr** [comment] 2024-02-12 16:20
Not overdue.

**Comment by ikevin127** [comment] 2024-02-21 15:03
More context regarding a possible resolve for the mentioned hold, in this Slack thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1708525183773549

**Comment by puneetlath** [comment] 2024-02-28 14:51
Still on hold.

**Comment by puneetlath** [comment] 2024-03-12 22:04
Still on hold.

**Comment by puneetlath** [comment] 2024-03-25 15:15
I don't think this is a bug anymore. I just tested it and the keyboard doesn't show at all, even momentarily. But I think that's fine. So I'm going to close the issue. Let me know if I've misunderstood or if you disagree!

**Closed by puneetlath** 2024-03-25 15:15 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
