### ISSUE TITLE
[$250] Taxes - "Default" label changes to "Workspace currency default" after changing tax code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48088] opened 2024-08-27 13:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes.
3. Click on the default tax code.
4. Click Tax code.
5. Edit tax code and save it.
6. Note that "Default" label in the default tax code in the background changes to "Workspace currency default" briefly.

## Expected Result:
"Default" label in the default tax code in the background will not change after changing tax code.

## Actual Result:
"Default" label in the default tax code in the background changes to "Workspace currency default" briefly.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f915175d-0c36-4b38-9717-d9dec3518008

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e55f0f655d87efe9</li>
        <li>Upwork Job ID: 1828439699555129867</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 103702547</li>
<li>shubham1206agra | Contributor | 103702642</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by IuliiaHerets** [comment] 2024-08-27 13:45
We think that this bug might be related to #wave-control

**Comment by etCoderDysto** [comment] 2024-08-27 13:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Default" label changes to "Workspace currency default" after changing tax code
### What is the root cause of that problem?
Here were are not setting `foreignTaxDefault` to the `newTaxCode` when editing tax code
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/libs/actions/TaxRate.ts#L486-L496
And here default badge is only displayed when t`axID === defaultExternalID && taxID === foreignTaxDefault` condition holds to be true. And it is not being true, since we are not updating `foreignTaxDefault`
https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/pages/workspace/taxes/WorkspaceTaxesPage.tsx#L87-L91
### What changes do you think we should make in order to solve the problem?
We should update `foreignTaxDefault` with the new tax code in optimistic data [here](https://github.com/Expensify/App/blob/d5cfecfc53a2abf926a1dd9be8bc72c0b373ff81/src/libs/actions/TaxRate.ts#L486-L496)
```
foreignTaxDefault: oldTaxCode === policy?.taxRates?.foreignTaxDefault ? newTaxCode : policy?.taxRates?.foreignTaxDefault,
``` 
And set `foreignTaxDefault` to the existing `foreignTaxDefault` in failure data
```
foreignTaxDefault: policy?.taxRates?.foreignTaxDefault,
```
Also we shouldn't update `defaultExternalID` in successData since BE returns the updated value
### What alternative solutions did you explore? (Optional)

**Comment by MariaHCD** [comment] 2024-08-27 14:37
Assigning @shubham1206agra for C+ review

**Comment by MariaHCD** [comment] 2024-08-27 15:07
Reassigned the C+ since this was a regression:

https://expensify.slack.com/archives/C02NK2DQWUX/p1724769162552359

**Comment by MariaHCD** [comment] 2024-08-27 15:52
@etCoderDysto any updates on the PR just yet?

**Comment by etCoderDysto** [comment] 2024-08-27 15:58
> @etCoderDysto any updates on the PR just yet?

Sorry, I was on a road. I am working on the PR now. It will be ready for review under 30 minutes.

**Comment by OfstadC** [comment] 2024-09-10 18:07
I think we are just waiting for this to be deployed to production in order to issue payment, but please correct me if I'm wrong.

**Comment by etCoderDysto** [comment] 2024-09-10 18:15
@OfstadC this PR was [cped on Aug 28](https://github.com/Expensify/App/pull/48105#issuecomment-2315378472). I think the automation is failing. It should be ready for payment.

**Comment by OfstadC** [comment] 2024-09-10 18:29
Thanks for clarifying @etCoderDysto ! Sorry for the confusion here 😅 

## Payment Summary
- @etCoderDysto paid $250 in Upwork
- @shubham1206agra Could you please accept your [Upwork offer ](https://www.upwork.com/nx/wm/offer/103702642)so I can issue payment.

**Comment by rushatgabhane** [comment] 2024-09-10 18:34
no c+ pay due here 😄

**Comment by OfstadC** [comment] 2024-09-11 17:56
Ah okay perfect! Thanks for letting me know @shubham1206agra!

**Closed** 2024-09-11 17:58 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
