### ISSUE TITLE
[HOLD for payment 2023-07-14] Up button does not redirect to LHN when other chats are opened previously and window was resized to mobile

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20370] opened 2023-06-07 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/19263

## Action Performed:
Scenario 1:
1. Go to https://staging.new.expensify.com/
2. Make sure that user lands on Chat A (other than Concierge).
3. Go to Concierge chat.
4. Resize the window to half the size to trigger mobile interface.
5. Click Back icon on the page.

Scenario 2:
1. Go to https://staging.new.expensify.com/
2. Make sure that user lands on Chat A (other than Concierge).
3. Go to Chat B, C and D.
4. Go to Concierge chat.
5. Resize the window to half the size to trigger mobile interface.
6. Click Back icon on the page.

## Expected Result:
User is redirected to LHN.

## Actual Result:
Scenario 1: User is redirected to Chat A. User needs to click on the back button again to return to LHN.

Scenario 2: User is redirected to chats that are opened previously (Chat D, C, B and A). User needs to click on the back button several times to return to LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.25.2

**Reproducible in staging?:**  Yes 

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7f191ba5-98f0-4764-889a-4e3151f365b1

https://github.com/Expensify/App/assets/78819774/c6897530-740c-42b9-a6dc-5491ddb1b6a1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebf41decd730ce26</li>
        <li>Upwork Job ID: 1679926062239186944</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2023-06-07 19:11
I'm actually unsure if this is expected behavior or not

**Comment by roryabraham** [comment] 2023-06-07 19:15
I think in any event we should not block deploys on this, so I'm going to demote it.

**Comment by roryabraham** [comment] 2023-06-07 19:16
It's actually unclear to me that this is even a bug, so I'm going to assign this to @mountiny who will have better context on how to address this issue, even if it's just to close it.

**Comment by mountiny** [comment] 2023-06-13 06:57
Making it Daily again to be worked on by SWM

**Comment by esh-g** [comment] 2023-06-14 20:12
### Hey, I just wanted to drop in some information if it would be useful in this case: 
It is possible to use the logic from  `subscribeToReportCommetPushNotifications`
https://github.com/Expensify/App/blob/8bd25c75b72a12ffcf8c27f97e610a220c3ce31f/src/libs/Notification/PushNotification/subscribeToReportCommentPushNotifications.js#L22-L25

And use it in `SidebarLinks.js`
https://github.com/Expensify/App/blob/2a1c36d5bea964ee92ebfad11f92d8a22bbb7e4c/src/pages/home/sidebar/SidebarLinks.js#L140-L147

This will make sure that if we click on another report, the previous one is popped off the stack and only then the new one opens. I'm not sure if this is the intended approach that we should choose but I'll let you be the judge...

**Comment by mountiny** [comment] 2023-06-14 20:14
Thanks, still waiting for swm to find time for this one

**Comment by mountiny** [comment] 2023-06-19 09:31
Not overdue.

**Comment by WoLewicki** [comment] 2023-06-20 14:36
I'd like more information of how it should work. The scenario I want to know is:
- Start with wide screen and do some navigation between the reports
- Resize to small screen and go through e.g. some deeplinks to go to other reports.
- Click back button in header

What should happen then? Should we still go to LHN or go back to the previous report? If so, should we go back till we get back to the report at which we resized and then go to LHN when pressing back button in it? Or should we still be popping the reports from before the resize? 

I think it gets unnecessary complicated really fast. Simplest solution would be to just always go back to LHN when pressing back button in the report. Then we would have browser back/forward buttons for navigation between reports and back button for popping the whole stack. WDYT @mountiny @roryabraham @parasharrajat ?

**Comment by mountiny** [comment] 2023-06-20 19:17
> I think it gets unnecessary complicated really fast. Simplest solution would be to just always go back to LHN when pressing back button in the report. Then we would have browser back/forward buttons for navigation between reports and back button for popping the whole stack. WDYT @mountiny @roryabraham @parasharrajat ?

I think we can start with going to the LHN everytime after the resize. So even if you had threads/ deeplinks to other reports, lets navigate to LHN as you can find the reports from there. 

Lets make sure the navigation does not break once you resize back to the wide screen after going to LHN in mobile view.

I believe we will have a dedicated link to parent report so even after resize you should be bale to click on that and go to the parent report and its safer to go to LHN. As mentioned, the main thing is to ensure that the navigation state does not get screwed so the back button behaves as expected even after resizing to small view, taking some actions and resizing back to the wide layout.

**Comment by mountiny** [comment] 2023-06-22 12:41
@WoLewicki is handling this one

**Comment by s77rt** [comment] 2023-06-29 23:43
Weird how Melvin didn't ~annoy me~ tag me in the above comment. BTW @mountiny this is just waiting for your approval

**Comment by mountiny** [comment] 2023-07-06 03:32
This was merged

**Comment by s77rt** [comment] 2023-07-08 01:22
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18350
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18350#discussion_r1256691042
- A discussion in #expensify-bugs has been started: This is an edge case, I doubt it could have been caught during PR testing and there is pretty much nothing to discuss here.
- Determine if we should create a regression test for this bug: Given this is an edge case (unlikely to be reproduced by a real user) I'm leaning towards a No.

**Comment by s77rt** [comment] 2023-07-08 01:26
@mountiny Can you please remove/add `Bug` label to auto-assign a BZ member here.

**Comment by mountiny** [comment] 2023-07-10 20:26
Payment is due at the end of the week

**Comment by alexpensify** [comment] 2023-07-10 21:19
I'm catching up from being OOO, it looks like payment is due on July 14.

**Comment by alexpensify** [comment] 2023-07-12 22:40
Since this is a payment, I've updated it to Weekly.

**Comment by alexpensify** [comment] 2023-07-13 21:29
@mountiny - can you please share what the payment structure should be here? Also, is there an Upwork job to send over and assign to @s77rt? Thanks!

**Comment by mountiny** [comment] 2023-07-13 21:39
$1000 to @s77rt for internal PR review

**Comment by s77rt** [comment] 2023-07-14 19:12
@alexpensify Accepted! Thanks!

**Comment by alexpensify** [comment] 2023-07-14 20:50
@s77rt has been paid via Upwork and I closed the job there. I'm going to close this GH too.

**Closed by alexpensify** 2023-07-14 20:50 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
