### ISSUE TITLE
[HOLD for payment 2023-08-21] [$1000] `errors` props are incorrectly accessed in `IOUCurrencySelection`

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#23373] opened 2023-07-21 21:00 UTC
Coming from: https://github.com/Expensify/App/pull/22198#discussion_r1267432256

> I noticed that in 3 out of 4 occurrences where shouldHideComposer is used. We are using props.errors when there is no prop errors. Here is a list -
> 
> ReportScreen - for hiding EmojiPickers
> 
> [App/src/pages/home/ReportScreen.js](https://github.com/Expensify/App/blob/058978e356bd266ee803a92467c3592565ad0c0c/src/pages/home/ReportScreen.js#L164)
> 
> Line 164 in [058978e](https://github.com/Expensify/App/commit/058978e356bd266ee803a92467c3592565ad0c0c)
> 
>  if (ReportUtils.shouldHideComposer(this.props.report, this.props.errors)) { 
> MoneyRequestAmountPage - for dismissing modal
> [App/src/pages/iou/steps/MoneyRequestAmountPage.js](https://github.com/Expensify/App/blob/058978e356bd266ee803a92467c3592565ad0c0c/src/pages/iou/steps/MoneyRequestAmountPage.js#L213)
> 
> Line 213 in [058978e](https://github.com/Expensify/App/commit/058978e356bd266ee803a92467c3592565ad0c0c)
> 
>  if (!ReportUtils.shouldHideComposer(props.report, props.errors)) { 
> This one.
> 
> The only correct occurrence where errors are actually populated is in ReportFooter to hide the composer. The errors used there are -
> 
> lodashGet(report, 'errorFields.addWorkspaceRoom') || lodashGet(report, 'errorFields.createChat');

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174717ad8fbbd1e71</li>
        <li>Upwork Job ID: 1682495893949411328</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25682904</li>
<li>Nikhil-Vats | Contributor | 25682906</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-07-21 21:01
@Nikhil-Vats can you make a proposal here. First dibs are yours.

**Comment by Nikhil-Vats** [comment] 2023-07-21 21:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`errors` props are incorrectly accessed in IOUCurrencySelection, ReportScreen, and MoneyRequestAmountPage.

### What is the root cause of that problem?
There is no prop named `errors` passed down to any of these 3 components.

https://github.com/Expensify/App/blob/c9e7f19113e3615cc1d35c4cfbf296d4522547e5/src/pages/iou/IOUCurrencySelection.js#L74

https://github.com/Expensify/App/blob/058978e356bd266ee803a92467c3592565ad0c0c/src/pages/home/ReportScreen.js#L164

https://github.com/Expensify/App/blob/058978e356bd266ee803a92467c3592565ad0c0c/src/pages/iou/steps/MoneyRequestAmountPage.js#L213

### What changes do you think we should make in order to solve the problem?
We need to get the `errors` from `report` using the same way we are doing for `ReportFooter` -

https://github.com/Expensify/App/blob/c9e7f19113e3615cc1d35c4cfbf296d4522547e5/src/libs/ReportUtils.js#L2574

These are the `errors` passed down from `ReportScreen` to `ReportFooter` to hide the composer if the `errors` object is not empty.

We can create a function for this in `ReportUtils` which takes `report` as a parameter and returns the errors which when populated should hide composer/emoji picker/split bill/other IOU/task flows.

### What alternative solutions did you explore? (Optional)
NA

**Comment by alexpensify** [comment] 2023-07-24 21:30
@marcaaron - when you get a chance can you review @dukenv0307's question? Thank you!

**Comment by marcaaron** [comment] 2023-07-25 22:22
>@marcaaron shouldn't this issue go through the regular proposal evaluation process?

In short, no? Internal engineers can assign whoever they want whenever they want for whatever reason. WRT the linked PR perhaps review the [contributing guidelines section on payments](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions). This issue was not "accidentally" assigned.

**Comment by alexpensify** [comment] 2023-07-27 21:51
The PR is under review and moving forward

**Comment by alexpensify** [comment] 2023-07-28 20:54
No update today

**Comment by alexpensify** [comment] 2023-08-01 00:43
The PR is moving along.

**Comment by marcaaron** [comment] 2023-08-01 20:48
@Nikhil-Vats That's great. However, I would advise against fixing it in the same PR as it will complicate the QA steps and generally make it hard to discover regressions, test, and review.

If there is a bug. Report it in Slack. Thanks!

**Comment by alexpensify** [comment] 2023-08-02 16:34
The PR is still under review.

**Comment by marcaaron** [comment] 2023-08-02 21:18
Sorry, I'm not quite understanding why this should be on hold or why all these other issues are being surfaced. The issue we are fixing is relatively simple. We are incorrectly accessing props that don't exist. Let's just access the correct ones? 

I appreciate that you are finding other bugs, but this is not the correct issue to add this context. Let's get this done! Thanks!

**Comment by marcaaron** [comment] 2023-08-03 02:06
uh yes, sorry, I don't think we care about these things (in the context of this issue at least). 

In general, if there is a bug that's unrelated to the changes but interfering with test results - then just call it out as a "known issue" and it does not need to block the testing.

**Comment by alexpensify** [comment] 2023-08-09 19:48
The original PR is waiting for one review.

**Comment by alexpensify** [comment] 2023-08-17 23:08
@mollfpr when you get a chance, please complete the checklist. Thanks!

**Comment by alexpensify** [comment] 2023-08-21 16:41
I've started the payment process in Upwork. Please confirm that you received it. Thanks!

**Comment by mollfpr** [comment] 2023-08-21 17:54
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/22198

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/22198/files#r1300448097

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The PR does not just clean up the unused declared property but also improves the chat page to show the invalid email error instead of showing the not found page immediately on some occurrence. So the regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Open the app in two tabs.
2. On the first tab, open settings and click on force offline.
3. On the second tab, go to search and enter a long email like a@_.cd or 2f34d2be9bce77da59b2e91f1a2bd25e0b85f2142f34d2be9bce77da59b2e91f1a2bd25e0b85f2142f34d2be9bce77da59b2e91f1a2bd25e0b85f214@gmail.com.
4. Now, send some messages in the chat and open the emoji picker from the composer.
5. Go to the first tab and toggle force offline to return online.
6. Verify that both composer and emoji picker automatically hide in the second tab and chat shows the error that the email address is invalid.

Since we can't open multiple tabs in apps (android/ios/desktop), we can test the same by switching off wifi in our device in step 2 and then switching on wifi in step 5 again.

**Comment by alexpensify** [comment] 2023-08-21 23:42
@marcaaron can you review and confirm if you agree with the regression test? Thanks!

**Comment by marcaaron** [comment] 2023-08-22 03:54
Those steps seem good to me. 


@mollfpr @Nikhil-Vats I appreciate the clean up. But in the future, I'd recommend that we try to not do anything more than the ticket is asking for. If you identify a bug or other issue then raise it separately. This keeps the trail of bugs much more clean and easy to follow. This really should have been a quick refactor and any other bugs should have been addressed separately. Thanks!

**Comment by alexpensify** [comment] 2023-08-24 04:12
@mollfpr can you share if the PR from here triggered a regression? If no, I'm going to carry on to create the regression test and close this GH. Thanks!

**Comment by mollfpr** [comment] 2023-08-24 10:12
@alexpensify I think it's not; the issue https://github.com/Expensify/App/issues/25698 might be related to the revert of https://github.com/Expensify/App/pull/22787.

**Comment by alexpensify** [comment] 2023-08-28 14:44
Sorry for the delay here, I was OOO last week. I'll create the regression test and close this GH. Thanks, @mollfpr for the update.

**Comment by alexpensify** [comment] 2023-08-30 21:19
Regression test, I'm hoping to get to it later today

**Comment by alexpensify** [comment] 2023-08-30 21:50
Closing - The test has been created

**Closed by alexpensify** 2023-08-30 21:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
