### ISSUE TITLE
Concierge - Concierge not displayed for new Employees added to collect policy

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#51262] opened 2024-10-22 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Can't log in in new account
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5109947&group_by=cases:section_id&group_order=asc&group_id=296773
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Setup - NewDot
1. Navigate to the collect workspace settings
2. Navigate to more features
3. Enable workflows
4. Navigate to workflows
4. Enable Approvals
5. Enable delay submissions and set it to Manually
6. Invite a new user as an employee (must be Gmail)
7. Login as the employee account in NewDot in Incognito 

## Expected Result:
New Employees that are added to a collect policy should initially display the Concierge chat after login in for the first time.

## Actual Result:
Concierge not displayed for new Employees added to collect policy after login in for the first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/1e45c28a-336b-4e62-aa79-5efcb6677081

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-10-22 15:28
In stg opened WS chat, in Production opened # announce room
https://github.com/user-attachments/assets/63bb74b4-eb1e-407d-affd-477054568fae

I add 2 labels `Deploy` because I can't check it with stg server 

https://github.com/user-attachments/assets/082b498b-5cbd-489d-b7f2-3d5b88ab9510

**Comment by yuwenmemon** [comment] 2024-10-22 23:22
Discussed here: https://expensify.slack.com/archives/C07J32337/p1729633880305189

Closing. This isn't a bug but rather than the intended behavior for a workspace with less than 3 employees: https://github.com/Expensify/App/issues/34929

**Closed by yuwenmemon** 2024-10-22 23:22 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug, DeployBlocker
