### ISSUE TITLE
[PAID] [$250] [Payment card / Subscription] limit input field to 16 digits in `add-payment-card` screen field for card number

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#44111] opened 2024-06-20 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue reported by:** @blimpich

## Action Performed:
Break down in numbered steps
1. create a new account
2. create a workspace on that account
3. go to `https://staging.new.expensify.com/settings/subscription/add-payment-card`
4. look at the card number field and type `"abcdef01234567891234567"`

## Expected Result:
Describe what you think should've happened

Alphabet characters should not be allowed into the input field and the input field should be limited to 16 digits

## Actual Result:
Describe what actually happened

`"abcdef01234567891234567"` shows up in the input field as typed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117d7a6e5f63d9c2e</li>
        <li>Upwork Job ID: 1803868245221381580</li>
        <li>Last Price Increase: 2024-06-20</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 102858281</li>
<li>nkdengineer | Contributor | 102858284</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by nkdengineer** [comment] 2024-06-21 04:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
limit input field to 16 digits in add-payment-card screen field for card number

### What is the root cause of that problem?
This is a new requirement

### What changes do you think we should make in order to solve the problem?

We need to transform the card number entered by the user such that the whitespaces will be removed and any digits that are beyond 16 digits allowed for the card, will be removed

So first [here](https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/AddPaymentCard/PaymentCardForm.tsx#L183) define a new state `cardNumber` and a method `onChangeCardNumber` to transform the `cardNumber` correctly
```
const [cardNumber, setCardNumber] = useState('');
    
const onChangeCardNumber = useCallback((newValue: string) => {
    // replace all characters that are not spaces or digits
    let validCardNumber = newValue.replace(/[^\d ]/g, '');

    // gets only the first 16 digits if the inputted number have more digits than that
    validCardNumber = validCardNumber.match(/(?:\d *){1,16}/)?.[0] ?? '';

    setCardNumber(validCardNumber);
}, []);
```

We need to replace the card redundant digits in here, we cannot set `maxLength={16}` as others suggested above because the input by the user could have arbitrary format. For example it could be "1234 1234 1234 1234" that has 19 digits (very commonly used), or "1234   1234  1234  1234", or "Payment card: 1234 1234 1234 1234". If we set maxLength, the digits at the end will be stripped. So "1234 1234 1234 1234" will become "1234 1234 1234 1" which is not good from user perspecive.

That's why in my solution we'll be finding the first 16 digits of the inputted card number, and stripped anything beyond that. 

Next, in https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/components/AddPaymentCard/PaymentCardForm.tsx#L206 we need to update the input to use the above defined `cardNumber`
```
onChangeText={onChangeCardNumber}
value={cardNumber}
```
We can optionally use `keyboardType={CONST.KEYBOARD_TYPE.NUMBER_PAD}` for this form.

IMO the current behavior where we preserve the spaces entered by the user is fine because we want to allow users to format the card number however they want. But if we'd like to always format it with spaces every 4 digits like "1234 1234 1234 1234", we can add a simple Regex and transform it in the `onChangeCardNumber`.

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-06-21 04:15
[Proposal updated](https://github.com/Expensify/App/issues/44111#issuecomment-2181960002)

**Comment by nkdengineer** [comment] 2024-06-25 17:41
@fedirjh this [PR](https://github.com/Expensify/App/pull/44400) is ready for review

**Comment by blimpich** [comment] 2024-06-27 19:17
**Problem:** this PR changes the value that is being sent to the api call. We use to be sending `4242424242424242` and now we are sending `4242 4242 4242 4242`. This breaks the add payment card flow. Can we make a follow up PR to make it so that it strips the spaces away before sending it to the api call?

Sorry I didn't catch this till now, I should have more thoroughly tested this or provided my ngrok for you to test against.

**Comment by nkdengineer** [comment] 2024-06-28 02:58
@blimpich  i'll raise PR soon

**Comment by nkdengineer** [comment] 2024-06-28 03:27
@blimpich we have a follow up PR [here](https://github.com/Expensify/App/pull/44592)

**Comment by strepanier03** [comment] 2024-07-17 23:17
@nkdengineer - I've paid and closed the contract in Upwork. 

@fedirjh - I'll check tomorrow for the checklist and reg test steps above, then pay when that's completed. 

Thank you both!

**Comment by JmillsExpensify** [comment] 2024-07-22 20:52
@strepanier03 payment summary when you get a chance

**Comment by strepanier03** [comment] 2024-07-23 21:11
### Payment Summary

- @fedirjh - $250 - Will request via New Expensify (I will cancel the Upwork contract)
- @nkdengineer - $250 paid via Upwork [automatic offer](https://www.upwork.com/nx/wm/offer/102858284)

@JmillsExpensify - Request incoming.

**Comment by JmillsExpensify** [comment] 2024-07-23 22:39
$250 approved for @fedirjh

**Comment by strepanier03** [comment] 2024-07-24 17:43
Looks great, thanks for confirming. Closing this now.

**Closed by strepanier03** 2024-07-24 17:43 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
