### ISSUE TITLE
Log In - Unable to log into account - Skeleton stuck at loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18457] opened 2023-05-04 22:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensifail.com
2. Login to [applausetester+disabledpolicy@applause.expensifail.com](mailto:applausetester+disabledpolicy@applause.expensifail.com)

## Expected Result:
User is successfully logged into the account

## Actual Result:
User gets endless skeleton page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.10.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2023-05-04 at 4 33 12 PM](https://user-images.githubusercontent.com/93399543/236347679-40e01df3-f145-4016-8952-7fb3bd465ca7.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-05-04 23:02
Issue is not reproductible in production.

![image](https://user-images.githubusercontent.com/93399543/236348038-d37eb080-6410-485a-9bb2-e0cb57a7eaf3.png)

**Comment by marcaaron** [comment] 2023-05-04 23:56
Unsure how to resolve this blocker without being able to test this account. I can look at logs but it would be better to be able to log in with this account. I can log in fine on staging so it might be something unique to this account.

**Comment by marcaaron** [comment] 2023-05-05 00:07
Are there any logs in the JS console or anything you can give us?

**Comment by mvtglobally** [comment] 2023-05-05 12:17
@marcaaron you can login to this account. Pinged you in SLack

**Comment by mvtglobally** [comment] 2023-05-05 12:19
Another user facing login issue [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)

**Comment by Beamanator** [comment] 2023-05-05 16:32
@marcaaron this looks similar to what i've been experiencing and posting some details about here: https://expensify.slack.com/archives/C049HHMV9SM/p1683295710267669

**Comment by bondydaa** [comment] 2023-05-05 16:37
fire room created here https://expensify.slack.com/archives/C0575MDAVLG/p1683304589499229

**Comment by marcaaron** [comment] 2023-05-05 23:18
This can be closed once https://github.com/Expensify/Web-Expensify/pull/37306 is deployed to prod. I'll keep my eye on it for now.

**Comment by aldo-expensify** [comment] 2023-05-09 19:20
@isagoico the fix is not in production yet it seems

**Comment by aldo-expensify** [comment] 2023-05-09 19:21
hmm seems like we didn't CP'ed https://github.com/Expensify/Web-Expensify/pull/37306 to staging , and I think we should have.

**Comment by bondydaa** [comment] 2023-05-09 19:54
🤔 i'm pretty sure it's on staging unless it got reverted or something?
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/4073354/e4dfb84f-cc37-4bb2-bf6b-43948d1d2b55">

**Comment by bondydaa** [comment] 2023-05-09 19:59
it doesn't seem to be on production as best I can tell though

**Comment by aldo-expensify** [comment] 2023-05-09 20:06
> 🤔 i'm pretty sure it's on staging unless it got reverted or something?

Yes, eventually it reached staging by the normal deploy process, but that allowed the deploy blocker caused by https://github.com/Expensify/Web-Expensify/pull/37134/files to reach production without this [fix](https://github.com/Expensify/Web-Expensify/pull/37306)

**Comment by bondydaa** [comment] 2023-05-09 20:13
oh sorry I see what you were saying, it was deployed but not CP'd. 

Is there an error that is thrown on the backend that we could look for to see if it's affecting non testing accounts? We are very close to the earnings call and I'd rather avoid CP'ing anything if we can but if this in any way affects non-testing accounts then we should consider CP'ing it.

**Comment by aldo-expensify** [comment] 2023-05-09 20:22
I think this log search can help answer that: https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%20%22%2Flib%2FReport%2FAction%2FChangePolicy.php%22%20AND%20timestamp%3A%5B2023-05-09T00%3A00%20TO%202023-05-10T23%3A59%5D

Then, running:


```js
Object.keys(
    [...document.querySelectorAll("td")]
       .filter(a => a.textContent.indexOf("@") != -1)
       .map(a => a.textContent)
       .filter(email => email)
       .reduce((accum, email) => {accum[email] = 1; return accum;}, {})
)


```

The only emails having this problem today are:

```
[
    "edwin.laiton@team.expensify.com",
    "applausetester+ihchat4@applause.expensifail.com",
    "applausetester@applause.expensifail.com",
    "applausetester+disabledpolicy@applause.expensifail.com"
]
```

**Comment by bondydaa** [comment] 2023-05-09 20:53
okay cool that is probably a guide or something right? earnings call is in like 7 minutes so I think we can :donothing: for now

**Comment by marcaaron** [comment] 2023-05-15 18:29
The code that is supposed to fix this is on production web now so I'm going to close this. If it's still happening feel free to reopen @kbecciv.

**Closed by marcaaron** 2023-05-15 18:29 UTC
Labels: Engineering, Weekly, Overdue
