### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] Profile - Entering country without a diacritic for Côte D'ivoire returns no suggestions

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24344] opened 2023-08-09 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24140

## Action Performed:
1. Open the app
2. Go to Settings > Profile > Personal details > Home address > Country
3. Start entering "cote" or "cote d'Ivoire" without a diacritic

## Expected Result:
The suggested country name "Côte d'Ivoire" is displayed

## Actual Result:
The suggested country is not displayed, and "no results found" is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0308fc16-f876-4eb9-a196-c0d60487e523

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01788d0f20c53c4622</li>
        <li>Upwork Job ID: 1689673663122317312</li>
        <li>Last Price Increase: 2023-08-10</li>
<li>Automatic offers: </li>
<ul>
<li>Pluto0104 | Contributor | 26073309</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-09 21:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Without diatric characters, it is difficult to search for `Côte d'Ivoire` in the `country` field.

### What is the root cause of that problem?
- The root cause is that the `country` field does not normalize diatric characters.

### What changes do you think we should make in order to solve the problem?
- We can use the below code to normalize diatric characters in the `country` field.

```js
function normalizeDiacritics(str) {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}
```

- Now we will need to update:
    - `searchCountryOptions.js` to use above function to normalize diatric characters.
    - We can further use above function in searching for Chats, Rooms, and Users.
        - By adding it to `isSearchStringMatch` of `OptionsListUtils.js`.

### What alternative solutions did you explore? (Optional)
- There are no alternative solutions. As this is a simple problem, the above solution should be sufficient.

**Comment by Pluto0104** [comment] 2023-08-09 22:00
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The country name is not displayed when you start entering "cote" or "cote d'Ivoire" without a diacritic, and instead you see "no results found".

### What is the root cause of that problem?
The app does not handle diacritics or special characters properly when searching or matching country names.

### What changes do you think we should make in order to solve the problem?
We can use `_.deburr` instead of `simplifyWordFromDiacritics` to remove diacritics from a string. This is a built-in function from `lodash`, which is a library that we already use in our app. This will make your code more concise and readable.

For example:
```
const trimmedSearchValue =_.chain(searchValue).deburr().toLower().value().replaceAll(CONST.REGEX.NON_ALPHABETIC_AND_NON_LATIN_CHARS, '');
/* ... */
const filteredData = _.filter(countriesData, (country) => _.deburr(country.searchValue).includes(trimmedSearchValue));
/* ... */
```

### What alternative solutions did you explore? (Optional)
```
function simplifyWordFromDiacritics(country) {
    return country.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}
```
![Screenshot 2023-08-09 164717](https://github.com/Expensify/App/assets/136573674/253b81b1-dd43-4ef5-84a2-f0c5d18ef950)

**Comment by mananjadhav** [comment] 2023-08-10 16:52
Thanks for the proposals folks, all the proposals have the correct RCA, but I think @Pluto0104's [proposal](https://github.com/Expensify/App/issues/24344#issuecomment-1672217314) is good. Using `lodash.deburr` would be more reliable.

🎀 👀 🎀  C+ reviewed.

**Comment by jeet-dhandha** [comment] 2023-08-10 16:56
Missed by lodash didn't knew they already had a function. Cheers to @Pluto0104 🥂 🎉

**Comment by mananjadhav** [comment] 2023-08-10 17:00
Yeah and I experience with regex `NFD` is it anyway supports limited characters. I've used it quite a few times, and we've always had to patch with few additional cases, until we started using lodash.

**Comment by Pluto0104** [comment] 2023-08-10 17:02
Umm, so is this proposal accepted? @mananjadhav, Can I make a proposal in Upwork?

**Comment by mananjadhav** [comment] 2023-08-10 17:30
@Pluto0104 We now wait for @aldo-expensify to review and officially assign you the job here in Github. You can then start the work on the PR, and in parallel get yourself hired on Upwork.

**Comment by Pluto0104** [comment] 2023-08-10 17:37
@mananjadhav, Thank you for your comment. I'm new to contributing Expensify app.

**Comment by Pluto0104** [comment] 2023-08-11 16:28
@aldo-expensify Could you please review my proposal?

**Comment by aldo-expensify** [comment] 2023-08-11 17:30
I think this should also include that if you put a diacritic in the search when you type, you should find results with and without the diacritic, right?

Just mentioning that because I'm not 100% the proposal is handling this case. Does it?

**Comment by aldo-expensify** [comment] 2023-08-11 17:33
Agree with preferring the implementation using lodash.

**Comment by Pluto0104** [comment] 2023-08-12 00:50
Contributor details
Your Expensify account email: fed.dev.pluto@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0111689310c69ddae7

**Comment by mananjadhav** [comment] 2023-08-23 17:18
I would treat this as a feature request instead of a bug fix. We never intended to consider diacritic characters when we originally created the feature.

**Comment by mananjadhav** [comment] 2023-08-28 09:44
@bfitzexpensify Can you post the payout summary here?

**Comment by Pluto0104** [comment] 2023-08-30 00:28
How can I receive a bonus? When I was new to contributing to Expensify, I submitted my work on Upwork, and then Upwork released $1000 from escrow today. It appears that the submission wasn't approved by Expensify, but due to the 14-day period since my submission, Upwork went ahead and released the funds. While I acknowledge that submitting the work was my oversight, I believe I am still eligible for a bonus related to this issue.

**Comment by JmillsExpensify** [comment] 2023-09-01 02:57
Waiting for the payment summary for NewDot payment.

**Comment by bfitzexpensify** [comment] 2023-09-01 11:09
Payout summary:

Contributor: @Pluto0104 - $1500 for contributor work and #urgency bonus. $1000 has been paid via Upwork, remaining $500 to be paid via Upwork - @Pluto0104, please apply to this job - https://www.upwork.com/jobs/~01aa7f6d4d09c3e0de
C+: $1500 to be paid to @mananjadhav for C+ work and #urgency bonus via manual request

**Comment by Pluto0104** [comment] 2023-09-01 14:27
@bfitzexpensify I have applied the job on Upwork.

**Comment by JmillsExpensify** [comment] 2023-09-01 18:06
Reviewed the details for @mananjadhav. $1,500 approved for payment based on BZ summary.

**Comment by Pluto0104** [comment] 2023-09-01 18:11
@JmillsExpensify I have applied the job from [here](https://github.com/Expensify/App/issues/24344#issuecomment-1702579742).
But my proposal is not accepted and the contract for [original issue](https://github.com/Expensify/App/issues/24344) is not completed. how can I do?

**Comment by Pluto0104** [comment] 2023-09-04 11:31
@mananjadhav @bfitzexpensify @JmillsExpensify could you please take a look [here](https://github.com/Expensify/App/issues/24344#issuecomment-1703150274)?

**Comment by mananjadhav** [comment] 2023-09-04 16:26
@JmillsExpensify @bfitzexpensify Can one of you help here?

**Comment by bfitzexpensify** [comment] 2023-09-05 09:39
@Pluto0104 offer sent - please let me know when you accept it and I will get it paid out.

**Comment by bfitzexpensify** [comment] 2023-09-05 14:42
OK, that's now been paid out. I agree with this reasoning, @mananjadhav:

>I would treat this as a feature request instead of a bug fix. We never intended to consider diacritic characters when we originally created the feature.

I think we're all done here now — thanks for the contributions everyone!

**Comment by Pluto0104** [comment] 2023-09-05 14:59
Hi @bfitzexpensify, I wanted to let you know that I've received payment for the work, but it seems that the contract for https://github.com/Expensify/App/issues/24344 is still open. Could you please confirm the completion of this contract? Thank you!

**Comment by bfitzexpensify** [comment] 2023-09-05 15:00
Hey @Pluto0104 - that's now been closed, thanks for the heads up.

**Comment by Pluto0104** [comment] 2023-09-05 15:04
@bfitzexpensify, thank you for the incredibly fast response. It appears that this issue may have been reopened, but I believe we can proceed to close it now. 🙇

**Closed** 2023-09-05 15:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
