### ISSUE TITLE
[HOLD 296932][$1000] Web - Member from `Share Somewhere` in assign task (creating from group) can choose assignee, results in error

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21580] opened 2023-06-26 15:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a group
2. Using User A create a task, don't assign it to anybody and leave the default options as it's
3. Log in using User B (member of same group in which task was created)
4. Navigate to task page.
5. Try assigning the user to task ( as User B )
6. Note that a selected user is assigned to task ( but in the network tab shows error error [shown in the recording])
7. Note the assignee is there even we are getting error
8. If we check from User A, assignee is not there

## Expected Result:
User B should not be able to assign the task to someone, if they are not a policy admin, the task creator, or a current task assignee. 

User B should be able to assign the task to someone if they are a policy admin, the task creator, or the current assignee. 

## Actual Result:
User B can assign the task to someone when they are not a policy admin, the task creator or current task assignee. However, the assignee only appears in their account and does not appear in user A's (who is the task creator). 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cb9fd452-5309-45b4-913a-63ebf298ceb3

https://github.com/Expensify/App/assets/93399543/66429a01-6926-45e9-ba5e-1fa65c77efb7

![image (99)](https://github.com/Expensify/App/assets/93399543/01bd2bda-91d2-487c-b3b8-eb8b1846dd07)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687434560850899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2d2c3fd882a94d6</li>
        <li>Upwork Job ID: 1674164051273023488</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-06-26 16:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Member from Share Somewhere in assign task (creating from group) can choose assignee, results in error

### What is the root cause of that problem?
The root cause for this problem is that we are not checking if current user has permission to assign this task to someone.
https://github.com/Expensify/App/blob/c261901687c3dd47e83e6a2c649a1590b2f8db6d/src/components/TaskHeader.js#L66-L117

Currently we are only checking if the task is open or not.

### What changes do you think we should make in order to solve the problem?
- We shall add a condition if the user who is viewing the task page has permission to add the assignee. My guess is that only the creator can assign the task to someone. And disable the `PressableFeedback` in `TaskHeader` component.
- We shall add appropriate `successData`, `optimisticData` and `failureData` in `setAssigneeValue()` 
- While disabling the `PressableFeedback` will do most of work, there may be a case when user directly pastes the url - `http://localhost:8080/r/7730858533875691/assignee` - This will open `TaskAssigneeSelectorModal`. To handle this case we shall add condition to the `TaskAssigneeSelectorModal` to only display if current user has enough permissions.

### What alternative solutions did you explore? (Optional)
None

**Comment by joekaufmanexpensify** [comment] 2023-06-27 21:15
I can reproduce this. Based on [the design doc](https://docs.google.com/document/d/1uFj0Oh9qtFJ-EH-lg00oMflo8uhkV2yXUT8Tbg6cKws/edit#bookmark=id.5c2m1jyrlnu6), it's not clear to me whether it's expected that anyone in the parent chat can edit a task's assignee. 

cc @thienlnam curious if you could share the expected behavior here? Should anyone in the chat be able to edit a task's assignee, or just the task creator/assignee (if there is one).

**Comment by thienlnam** [comment] 2023-06-28 20:55
Yes, only the creator, assignee, and policy admins are able to edit a task assignee

**Comment by joekaufmanexpensify** [comment] 2023-06-28 21:01
Got it, ty!

**Comment by joekaufmanexpensify** [comment] 2023-06-28 21:13
Updated OP to clarify expected behavior.

**Comment by abdulrahuman5196** [comment] 2023-06-29 08:23
@BhuvaneshPatil 

>While disabling the PressableFeedback will do most of work, there may be a case when user directly pastes the url - http://localhost:8080/r/7730858533875691/assignee - This will open TaskAssigneeSelectorModal. To handle this case we shall add condition to the TaskAssigneeSelectorModal to only display if current user has enough permissions.

What do you suggest to do when user doesn't have enough permissions? Like disable navigate user back or show some errors or disable the selection?

**Comment by abdulrahuman5196** [comment] 2023-06-29 09:14
>My suggestion would be disable the Options and show error message on the top in red color, that You don't have enough permissions

@BhuvaneshPatil Could you kindly share any other cases in the app where you have referenced this? Because it would be better if we reuse any existing exception handling behaviour similar to this case?

**Comment by BhuvaneshPatil** [comment] 2023-06-29 09:15
@abdulrahuman5196 I will try and find the places where same behavior is being handled.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 18:38
Proposals under review

**Comment by abdulrahuman5196** [comment] 2023-06-30 16:40
Thanks for the research @BhuvaneshPatil.

I agree with @BhuvaneshPatil 's root cause and solution mentioned here - https://github.com/Expensify/App/issues/21580#issuecomment-1607810113

The addons we should do part of this is,

1) Not just the assign task, title and description fields are also affected, we can add the same check there.
2) Show FullPageNotFoundView if the user tries to directly access the url as mentioned here - https://github.com/Expensify/App/issues/21580#issuecomment-1613582348 (I am also fine with any other exception handling, if we have something already related to tasks but AFAIK currently there is none)

And the condition would be `only the creator, assignee, and policy admins are able to edit a task assignee` as mentioned here https://github.com/Expensify/App/issues/21580#issuecomment-1612093608

Lets go with the proposal - https://github.com/Expensify/App/issues/21580#issuecomment-1607810113

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

**Comment by abdulrahuman5196** [comment] 2023-06-30 16:41
@namhihi237 Thank you for the proposal. But it is almost similar to the accepted proposal.

**Comment by abdulrahuman5196** [comment] 2023-06-30 16:41
@stitesExpensify The C+ approved comment is here https://github.com/Expensify/App/issues/21580#issuecomment-1614907480

**Comment by stitesExpensify** [comment] 2023-06-30 19:57
I'm happy to add that in for the front end, but I'm going to tag @thienlnam to make sure that we have this fixed on the backend as well

**Comment by abdulrahuman5196** [comment] 2023-06-30 20:06
> I'm happy to add that in for the front end, but I'm going to tag @thienlnam to make sure that we have this fixed on the backend as well

AFAIK, The API call fails it is only updating the local data.

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:10
Not overdue.

**Comment by abdulrahuman5196** [comment] 2023-07-03 17:51
I think we move forward on this @stitesExpensify ? Kindly correct me if anything else is blocking?

**Comment by BhuvaneshPatil** [comment] 2023-07-03 18:03
https://github.com/Expensify/App/issues/21579

This is the same issue and I have submitted proposal for both of these. we can handle them in this PR itself

**Comment by stitesExpensify** [comment] 2023-07-03 18:56
@BhuvaneshPatil to clarify, you're saying this issue can be closed, because the PR for the other issue will fix this as well?

**Comment by abdulrahuman5196** [comment] 2023-07-03 19:01
The other issue is not even C+ approved yet and there is no PR 🤔? Am I missing something @BhuvaneshPatil 

Shouldn't we close the other it it's a dupe(not sure if it's dupe have to check)?

**Comment by BhuvaneshPatil** [comment] 2023-07-04 01:06
@abdulrahuman5196 , As you have mentioned in this comment - https://github.com/Expensify/App/issues/21580#issuecomment-1614907480, that we should also add the `title` and `description` part to this solution. By adding that - https://github.com/Expensify/App/issues/21579 can be resolved. 
Please verify on your end as well.

**Comment by BhuvaneshPatil** [comment] 2023-07-04 01:11
@stitesExpensify what I meant to say that, if we add the title and description part to PR of this issue. The mentioned issue (#21579), can be solved. Let's wait for the @abdulrahuman5196's comment about the same.

**Comment by abdulrahuman5196** [comment] 2023-07-04 15:44
@BhuvaneshPatil  We can handle here itself. Since during C+ approval itself I requested to include fix for name and description here itself.

>to clarify, you're saying this issue can be closed, because the PR for the other issue will fix this as well?

@stitesExpensify It is the opposite, if we do the fix here for name and description field also as requested on C+ approval comment, it will most likely solve the other issue. I think we can move forward on this issue, if nothing else is blocking.

**Comment by abdulrahuman5196** [comment] 2023-07-04 16:22
@BhuvaneshPatil Could you kindly check on this? https://github.com/Expensify/App/issues/21579#issuecomment-1620506081

Could you provide reference for how we would check if the user has permission to edit the task since they are policy owners? I knew we have way to if user is assignee or creator.

**Comment by BhuvaneshPatil** [comment] 2023-07-04 17:14
Sure @abdulrahuman5196 

by adding `policies` to props of `TaskHeader`, and getting them from onyx. We can apply following logic
```
const policy = useMemo(() => props.policies[`${ONYXKEYS.COLLECTION.POLICY}${props.report.policyID}`], [props.policies, props.report.policyID]);
const isPolicyAdmin = policy && PolicyUtils.isPolicyAdmin(policy);
```

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:22
Still discussing next steps for the proposal here.

**Comment by thienlnam** [comment] 2023-07-05 18:38
Adding a note here since it's relevant - we've been discussing changing the access paradigm for tasks. We're planning on moving towards anyone that has access to view the task can modify it

**Comment by stitesExpensify** [comment] 2023-07-05 22:23
Hmm okay @thienlnam so should this just be closed for now then?

**Comment by thienlnam** [comment] 2023-07-06 00:07
Let's just keep it open so we can keep track of this bug - but then should be resolved once we finish the other issue

**Comment by BhuvaneshPatil** [comment] 2023-07-08 18:00
@thienlnam @abdulrahuman5196 
Just to confirm, will this issue be worked on in the frontend or not. Or will this be resolved by backend or other issue?

**Comment by joekaufmanexpensify** [comment] 2023-07-10 14:01
On hold

**Comment by thienlnam** [comment] 2023-07-10 17:22
> Just to confirm, will this issue be worked on in the frontend or not. Or will this be resolved by backend or other issue?

We're resolving this in the back-end

**Comment by BhuvaneshPatil** [comment] 2023-07-10 17:26
@thienlnam Thank you for updating

**Comment by joekaufmanexpensify** [comment] 2023-07-17 13:09
On hold!

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:14
Moving back to weekly as this is on hold.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:43
Still held on https://github.com/Expensify/expensify/issues/296932

**Comment by BhuvaneshPatil** [comment] 2023-07-26 05:14
There are other issues coming in about accessing the pages - https://github.com/Expensify/App/issues/22451

We can handle them here as part of this issue on frontend.
@thienlnam @abdulrahuman5196

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:33
Still on hold

**Comment by BhuvaneshPatil** [comment] 2023-08-01 01:48
@thienlnam @abdulrahuman5196 Suggested proposal doesn't affects backend changes and with very small change solves the new issues as well. If it's fine we can open this issue (make external) and make the changes. Please share your views.

**Comment by thienlnam** [comment] 2023-08-01 02:37
I took a look at your [proposal](https://github.com/Expensify/App/issues/21580#issuecomment-1607810113) and it addresses some cases regarding directly accessing the link. I like your solution, but I'm updating the permission of who can modify a task in this [PR](https://github.com/Expensify/App/pull/23971), so let's wait until that is done and then we can go with your other changes

**Comment by BhuvaneshPatil** [comment] 2023-08-01 02:40
Thanks @thienlnam , similar changes are mentioned in this issue as well - https://github.com/Expensify/App/issues/22451

Please have a look the issue and provide your feedback on the issue because the changes mentioned here are approved on that issue.

**Comment by joekaufmanexpensify** [comment] 2023-08-07 13:15
Held

**Comment by thienlnam** [comment] 2023-08-07 17:49
Held issue should be deployed - we can start looking at solutions for this now https://github.com/Expensify/App/issues/21580#issuecomment-1659476640

**Comment by BhuvaneshPatil** [comment] 2023-08-07 18:37
As permissions have changed we will follow the approach that we use for disabling `MenuItem` in `TaskPreview` for hiding (showing `FullPageNotFoundView`) to following pages - 
- `TaskDescriptionPage`
- `TaskTitlePage`
- `TaskAssigneeSelectorModal`

For disabling edits in `TaskPreview` - we use 

https://github.com/Expensify/App/blob/ab4dc4b7a2d13d723802f8a38a7a15a1a2e03b4d/src/components/ReportActionItem/TaskView.js#L50-L53

We can use similar logic in `FullPageNotFoundView` for setting the value for `shouldShow` attribute.

cc - @abdulrahuman5196

**Comment by joekaufmanexpensify** [comment] 2023-08-14 13:33
@thienlnam @BhuvaneshPatil for my own understanding, if anyone that can view a task can now change the task's assignee, what changes do we still need to make in this issue?

**Comment by thienlnam** [comment] 2023-08-14 14:22
Yeah good question, the proposal listed is more about better handling edge cases where you aren't able to update task details - a task is cancelled or completed and you try to access the update assignee page directly

**Comment by joekaufmanexpensify** [comment] 2023-08-14 14:31
Got it. Is that related to the original bug about a non-assignee being able to update the task assignee? If not, I wonder if it could make sense to open a new bug/new feature issue (depending on which it is), to handle that.

**Comment by thienlnam** [comment] 2023-08-14 14:39
Yeah, we can close this - seems like we have a seperate bug for that here https://github.com/Expensify/App/issues/22451

So we can address this specific [flow](https://github.com/Expensify/App/issues/21580#issuecomment-1677416070) over there

**Comment by thienlnam** [comment] 2023-08-14 15:17
It looks like the changes you mentioned here are actually covered in the selected proposal message https://github.com/Expensify/App/issues/22451#issuecomment-1638973855 regarding use of the FullPageNotFoundView.

So there doesn't seem to be a need to duplicate the changes here

**Comment by BhuvaneshPatil** [comment] 2023-08-14 15:44
The proposal selected for that proposal mentions the changes for this issue and these changes were considered for selecting. and this issue was created way earlier, so I want to point out that if the changes are not needed then should not be considered for selection. Amd if we decide to add those changes, they should not be criteria for deciding.
I have mentioned same there as well but got no response.

**Comment by BhuvaneshPatil** [comment] 2023-08-14 17:45
@thienlnam @joekaufmanexpensify 

I have found a new bug similar to this one, shall I add them here or wait till they are reported by QA?

**Comment by joekaufmanexpensify** [comment] 2023-08-14 17:50
If it's a new bug, it should be handled in a new issue.

**Comment by joekaufmanexpensify** [comment] 2023-08-14 17:52
Closing this one for now, since the bug that was specifically covered by this issue was fixed by https://github.com/Expensify/Expensify/issues/296932 !

**Closed by joekaufmanexpensify** 2023-08-14 17:52 UTC
Labels: Weekly, Internal, Bug

**Comment by BhuvaneshPatil** [comment] 2023-08-14 17:57
Will there be compensation for reporting the bug?

**Comment by joekaufmanexpensify** [comment] 2023-08-14 18:00
I would say no, since the need to fix this bug was obviated by internal changes we made in https://github.com/Expensify/Expensify/issues/296932 .
