### ISSUE TITLE
[HOLD for payment 2024-11-18] [HOLD for payment 2024-11-11] [$250] The setting "Mute all sounds from Expensify" keeps turning back off despite turning it on every day.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49087] opened 2024-09-12 13:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1726129231306989

## Action Performed:
1. Go to Account settings > Preferences
2. Toggle "Mute all sounds from Expensify" to "ON"
3. Signout and Singnin

## Expected Result:
Preference settings are saved for each platform and remain intact after the user signs out and signs back in.  

## Actual Result:
Preference settings not saved and toggles back to "OFF"
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4b4147f8-c7ee-4305-ae1e-a54a3b96c22e

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834238152691021896</li>
        <li>Upwork Job ID: 1834238152691021896</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104324316</li>
<li>c3024 | Contributor | 104324317</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by eyramtitiati** [comment] 2024-09-12 15:04
Problem Statement:

The setting “Mute all sounds from Expensify” keeps turning off, even after being enabled by the user.

Root Cause:

The current implementation merges the `isMutedAllSounds` only into Onyx (local storage) without making an API call to persist the preference in the backend, causing the setting to reset daily.

Proposed Solution:

We will add an API call in User.ts for the` setMuteAllSounds` function, similar to how `updateNewsletterSubscription` operates. This ensures the setting is stored in the backend, maintaining persistence across app sessions.

Alternative Solutions Explored:

1. Persist Locally with AsyncStorage: Instead of adding a backend call, we could utilize React Native’s AsyncStorage to persist the mute setting locally across sessions. This would reduce dependency on the backend, making it quicker but potentially less reliable across different devices.
2. Onyx Sync with Backend at App Load: Another approach is to sync Onyx with the backend on app load to ensure that any changes made to settings (like isMutedAllSounds) are reflected in the backend at regular intervals, reducing the number of API calls but maintaining sync reliability.

**Comment by eyramtitiati** [comment] 2024-09-12 15:08
Contributor details
Your Expensify account email:eyramtitiati@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0182773c2654eddb1f?mp_source=share

**Comment by NaveedShaikh78** [comment] 2024-09-12 19:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The setting "Mute all sounds from Expensify" keeps turning back off despite turning it on every day. 

### What is the root cause of that problem?
API to update "Mute all sounds from Expensify" is not implemented

### What changes do you think we should make in order to solve the problem?
Need to implement the API and other related changes to respective files
[ app\src\libs\actions\User.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/User.ts)
```js
function updateIsMutedAllSounds(isMutedAllSounds: boolean) {
    const optimisticData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.USER,
            value: {isMutedAllSounds: isMutedAllSounds},
        },
    ];
    const failureData: OnyxUpdate[] = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.USER,
            value: {isMutedAllSounds: !isMutedAllSounds},
        },
    ];
                     
    const parameters: UpdateIsMutedAllSoundsParams = {isMutedAllSounds};

    API.write(WRITE_COMMANDS.UPDATE_IS_MUTED_ALL_SOUNDS, parameters, {
        optimisticData,
        failureData,
    });
}
```
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2024-09-13 07:52
Coming from the Slack discussion, the repro steps for this issue are wrong. The current thinking is that it happens when **the app is updated**, not when signing in/out (though it would also happen there, but that's expected since the setting isn't stored at the account-level).

**Comment by jjcoffee** [comment] 2024-09-16 08:22
Bumped [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1726474934563679).

**Comment by c3024** [comment] 2024-09-16 10:23
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Muted setting resets on updating app.
### What is the root cause of that problem?
After updating the app, I think backend sends `ONYXKEYS.RESET_REQUIRED` as `true`. So, this here 
https://github.com/Expensify/App/blob/b00b9bc8afaa0c359ff7526f4990e81866e8499d/src/libs/actions/App.ts#L80-L102
retains information only those in the keys to preserve and resets the rest.

As muting preference is within `ONYXKEYS.USER` it gets reset.
### What changes do you think we should make in order to solve the problem?
I tried the following. Then this muting setting does not get reset.
1. We can move the muting preference to `ONYXKEYS.ACCOUNT` because it is already one of the keys in the keys to be preserved. 
(or)
2. We can add `ONYXKEYS.USER` to the keys to preserve because it has some other local preferences like clearing focus mode notification etc. so they are not lost when updated,
(or)
3. Extract muting sounds to a separate Onyx key.
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2024-09-16 11:38
> After updating the app, I think backend sends ONYXKEYS.RESET_REQUIRED as true. 

@c3024 Thanks for the [proposal](https://github.com/Expensify/App/issues/49087#issuecomment-2352529437)! It does sound like a plausible RCA, but I'm wondering if this is true. Based on the comment here it sounds more like this should be triggered fairly rarely (the reports are of it happening "2 or 3 times a week"/"every day"):

https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/ONYXKEYS.ts#L364-L365

Of course it's possible that an "emergency" reset is being triggered more often that we'd think, or even that it's being triggered by mistake on every update. 

@johnmlee101 Are you able to check on the BE to see what/if any Onyx keys get set (e.g. `RESET_REQUIRED`) to require/trigger an update?

**Comment by jjcoffee** [comment] 2024-09-16 11:41
Also [asking](https://github.com/Expensify/App/pull/38196/files#r1760990042) on the PR that introduced `RESET_REQUIRED` if we'd be safe to add `ONYXKEYS_USER` to the list as @c3024 suggests.

**Comment by jjcoffee** [comment] 2024-09-20 07:36
Got [confirmation](https://github.com/Expensify/App/pull/35306#discussion_r1762994003) from the actual original source of those `KEYS_TO_PRESERVE` that it's most likely okay to add `ONYXKEYS.USER` there. 

I think we can just try out the [proposal](https://github.com/Expensify/App/issues/49087#issuecomment-2352529437) and see if it helps. It's a bit hard to judge since we don't have reliable repro steps, but it sounds plausible enough! 

:ribbon::eyes::ribbon: C+ reviewed

**Comment by tgolen** [comment] 2024-09-20 15:36
I think that we should be adding any more keys to `KEYS_TO_PRESERVE`. That feels like it's only working around the problem and there is not really any current guidance for what keys should be put into `KEYS_TO_PRESERVE`. What is to stop us from ending up with every single Onyx key listed there eventually?

Isn't the real problem that the backend is not sending the correct setting to the frontend after updating?

**Comment by marcaaron** [comment] 2024-09-23 18:38
AFAICT that is unimplemented in the backend. It seems possible we've jumped to a wrong conclusion. Neither Auth nor Web-Expensify mention anything about this key.

**Comment by dangrous** [comment] 2024-09-23 19:11
Mute settings is fully frontend right now, there's no backend saved setting. So it's fine if it's per device, etc. but the goal would be a way to keep it in there on the same device with no log out.

Alternately we could add it into the backend, but I'm assuming (?) there's a reason we didn't build it that way in the first place?

**Comment by tgolen** [comment] 2024-09-23 19:14
Thanks, Marc. I would agree. @jjcoffee for now, I'd like to avoid accepting any proposal without a clear and detailed root cause. It can't be `resetRequired` that's causing this (since the backend is not doing anything with that), so maybe we should look more closely at trying to figure out how it's reproducible. The original description says it can be reproduced via signout/signin, which seems like the best place to start. I think we should also be looking at this as a parallel to the setting for using the staging sever. Is the staging server setting stored on the backend and is why it persists between signins (I don't think so because I don't see any network requests when I toggle the setting)?

**Comment by marcaaron** [comment] 2024-09-23 20:04
>Also, what is your opinion on the proposal here to add the user key to KEYS_TO_PRESERVE so some of the flags there are not reset?

To quickly respond to this question. I _think_ it seems fine. [Here's all the stuff we use it for](https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/types/onyx/User.ts#L3C1-L37C34). So, we can look at the situations where the `KEYS_TO_PRESERVE` are used and decide if any of the things in the `user` key would be bad to persist (took a quick look and nothing stood out).

- `signUpUser` -> https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/libs/actions/Session/index.ts#L499C1-L500C69

- `validateTwoFactorAuth` -> https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/libs/actions/Session/index.ts#L1028C1-L1033C10

- `TroubleshootPage` -> https://github.com/Expensify/App/blob/b0ce2068ee57c252ec47aa1f09319eee8b4f673c/src/pages/settings/Troubleshoot/TroubleshootPage.tsx#L160C1-L162C40

However, not sure that's the right direction for this issue yet.

**Comment by jjcoffee** [comment] 2024-09-24 09:28
> The original description says it can be reproduced via signout/signin, which seems like the best place to start.

The [reports](https://expensify.slack.com/archives/C05LX9D6E07/p1726129231306989) are of it happening whilst remaining signed in; signout/signin would only repro the issue since the setting is not persisted via the BE.

We had some discussion on Slack previously and [agreed](https://expensify.slack.com/archives/C05LX9D6E07/p1726214003393939?thread_ts=1726129231.306989&cid=C05LX9D6E07) to keep this issue focused on the behaviour whilst signed in, leaving the question of whether or not to persist the preference for future discussion (if any!).

**Comment by isabelastisser** [comment] 2024-09-26 20:21
@jjcoffee, are we waiting for an updated proposal to address what has been decided [here](https://github.com/Expensify/App/issues/49087#issuecomment-2370756325)?

**Comment by jjcoffee** [comment] 2024-09-27 07:39
@isabelastisser Yes that's right! I've bumped on Slack now.

**Comment by mallenexpensify** [comment] 2024-10-01 00:20
@rushatgabhane @MonilBhavsar I created another dupe issue I'm closing.  👀 here in case you have feedback and/or ideas.  Thx

**Comment by jjcoffee** [comment] 2024-10-01 08:02
@mallenexpensify If we decide that we want the setting to persist across sign out/sign in it would also fix this issue, but the actual bug reported here is without signing in (i.e. the setting just seems to randomly reset).

**Comment by MonilBhavsar** [comment] 2024-10-01 10:45
I think Matt faces the similar issue - the mute setting is reset after signout/signin. Agree with the root cause being discussed. I see we store deviceID in the Onyx DB. Have we considered of saving the mute setting at the server side and returning to the device making request via API response?

**Comment by coleaeason** [comment] 2024-10-01 14:14
>Have we considered of saving the mute setting at the server side and returning to the device making request via API response?

+1000, I've said this for months. The current implementation leads to the toggle being turned back on randomly all the time. I don't see why we would not persist this.

**Comment by tgolen** [comment] 2024-10-01 16:35
Yes, I think we should do this right and save it to the server. I think the only thing we need to decide is if we want to allow the setting to be set for a specific device/platform or across all devices or platforms. I think I would prefer doing it for each specific platform.

**Comment by mallenexpensify** [comment] 2024-10-01 22:37
>  I think I would prefer doing it for each specific platform.

I think this is the _correct_ way to do it.  Since it's def possible that people want sounds on some platforms and not others.

**Comment by MonilBhavsar** [comment] 2024-10-02 04:24
Platforms specific sounds good too

**Comment by tgolen** [comment] 2024-10-02 15:40
Great, what's the plan to move it to a server setting then and who wants to do it?

**Comment by mallenexpensify** [comment] 2024-10-03 22:53
I updated the Expected behaviour to inc. the bold text below
> Preference settings are saved **for each platform** and remain intact after the user signs out and signs back in.  

Do we expect to only need one PR to fix the bug or will it be multiple? Asking cuz we might want to increase the price of the job.

**Comment by c3024** [comment] 2024-10-04 14:03
I think one PR should be enough for the frontend part. We can change `isMutedAllSounds` from a boolean to an object with fields, using each platform name as the key and a mute setting boolean as its value.

We can create a WRITE_COMMAND for updating this setting.

**Comment by tgolen** [comment] 2024-10-07 14:40
I'll work on the backend part of this, and I think yes, I do want a contributor to work on the frontend part of it.

I need to get caught up on a few things this morning, then do a little research on how this will work exactly, then I'll come back here and try to post a plan for how best to move forward and what all the specifics will be (name of API command, Onyx keys, platform values, etc.).

**Comment by tgolen** [comment] 2024-10-07 18:15
# Proposal

## New Command for Muting a Platform
- Create a new API command called `MutePlatform`
- Parameters will be:
  - `authToken` String
  - `platform` String, one of `web|desktop|ios|android`
- This will be stored in an NVP called `mutedPlatforms` and automatically synced to Onyx just like other NVPs that automatically sync

## New Command for Unmuting a Platform
- Create a new API command called `UnmutePlatform`
- Parameters will be:
  - `authToken` String
  - `platform` String, one of `web|desktop|ios|android`

How does that look to everyone? Is that all you need to do a frontend implementation?

**Comment by tgolen** [comment] 2024-10-07 19:35
Hm, should we also consider the platform `mobileweb`? I think, maybe yes?

**Comment by tgolen** [comment] 2024-10-07 22:12
# Daily Update
- I've created [a draft Auth PR](https://github.com/Expensify/Auth/pull/12702) with the proposal above (including the `mobileweb` platform inclusion)

### Next Steps
- @tgolen Finish the PR by adding some more robust unit tests and test that the NVP is properly sent to the frontend
- @jjcoffee we can start getting frontend proposals to implement the solution so they can be worked on in parallel

#### ETA
- Backend: Deployed by Thursday, Oct 10
- Frontend: TBD

**Comment by c3024** [comment] 2024-10-08 00:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
New feature: Have platform specific mute setting.
### What is the root cause of that problem?
Mute settings get reset sometimes. We can sync them if they ever reset if we write them to backend for each platform.
### What changes do you think we should make in order to solve the problem?
1. Add the WRITE_COMMANDS, MUTE_PLATFORM and UNMUTE_PLATFORM to API/types.ts and the key NVP_MUTED_PLATFORMS to ONYXKEYS
2. Have two functions `mutePlatform` and `unmutePlatform` in place of existing `setMuteAllSounds` function in User.ts.
3. Get the authToken from the existing session connection in User.ts and platform from getPlatform (and browser from getBrowser specifically for mWeb) and pass these to the functions above.
4. Prepare optimistic, success and failure datas similar to other NVPs in the User file for sending from these functions to API.
5. Get this NVP from PreferencesPage with useOnyx.
### What alternative solutions did you explore? (Optional)

**Comment by MonilBhavsar** [comment] 2024-10-08 07:06
> Hm, should we also consider the platform mobileweb? I think, maybe yes?

🤔 I think we should just treat mobileWeb under android/iOS i.e. the OS on which the browser operates

**Comment by jjcoffee** [comment] 2024-10-08 14:58
@c3024's [proposal](https://github.com/Expensify/App/issues/49087#issuecomment-2398351987) sounds good to me!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by coleaeason** [comment] 2024-10-08 16:46
@tgolen why not 1 command, `TogglePlatformMute` since the code is going to be 99% the same in both commands? The only difference is enabled/disabled for a given platform

**Comment by tgolen** [comment] 2024-10-08 17:47
Sure, that would work too. It was not the first thing I thought of and there is no reason not to do it that way. Either works.

**Comment by tgolen** [comment] 2024-10-08 18:57
@c3024 Are you OK with me changing this to be a single `TogglePlatformMute` command? The params will remain the same.

**Comment by c3024** [comment] 2024-10-09 07:39
Yes, that is fine. I too [had](https://github.com/Expensify/App/issues/49087#issuecomment-2393790688) only one command in my mind for updating this setting.

**Comment by c3024** [comment] 2024-10-10 04:02
I raised a [PR](https://github.com/Expensify/App/pull/50493) assuming the onyx data for mutedPlatforms as an array with platform keys.

**Comment by jjcoffee** [comment] 2024-10-14 07:51
Not overdue, we're waiting for the BE PR, I think.

**Comment by tgolen** [comment] 2024-10-14 15:52
Yep, those should be available by mid-week. I'm just wrapping up the second BE PR for them now.

**Comment by isabelastisser** [comment] 2024-10-18 17:09
Not overdue!

**Comment by isabelastisser** [comment] 2024-10-22 17:25
@jjcoffee, can you please provide an update? Thanks!

**Comment by jjcoffee** [comment] 2024-10-23 08:08
I think we're still waiting for @tgolen - or is the BE PR shipped now?

**Comment by c3024** [comment] 2024-10-23 08:10
It's shipped but there is an [issue here](https://github.com/Expensify/App/pull/50493#issuecomment-2418660943).

cc: @tgolen

**Comment by tgolen** [comment] 2024-10-25 14:16
# Weekly Update
- I've submitted a [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/44123) to fix [the reported issue](https://github.com/Expensify/App/pull/50493#issuecomment-2418660943) which should be deployed to staging either today or Monday.
- Once that is done, the [FE PR](https://github.com/Expensify/App/pull/50493) should be ready to be finalized and merged

### Next Steps
- @c3024 will test this on Monday with the new fix deployed
- @jjcoffee and @tgolen give a final review and merge the FE PR

#### ETA
- FE PR merged on Monday Oct. 28

**Comment by mallenexpensify** [comment] 2024-11-06 01:05
QQ, I see the PR hit staging last week. I'm on latest staging, desktop and.. 
1. Had sounds muted. 
2. Signed out/in
3. Sounds weren't muted anymore. 

That's the bug I was hoping would be fixed. 

I then signed out/in **again** and had the same results. Any idea why this isn't working?

**Comment by mallenexpensify** [comment] 2024-11-06 01:11
Somethings way broken here.  
After the above, when I muted sounds again

- Went to chat with Deeter
- Sent him message
- Sound happened. 

Turned mute back on again, followed the above steps and sounds happen on ALL the messages I send 😨

**Comment by jjcoffee** [comment] 2024-11-06 13:09
> 3. Sounds weren't muted anymore.

@mallenexpensify Was the mute all sounds setting turned off or just that you heard sounds? 

@c3024 found a couple of areas we missed where the loading of the new setting needed updating, but the toggle itself should have been displaying correctly. The only other thing I can think of is that you will have needed to re-enable the setting once the PR hit staging.

**Comment by mallenexpensify** [comment] 2024-11-06 18:36
This is how I have my settings and it's  playing sounds when I send a message, it doesn't appear to be when I receive one though. 
<img width="703" alt="image" src="https://github.com/user-attachments/assets/029813d5-0ddd-484a-9203-6e4e1208edf6">


and.. check this weirdness around the 6 second mark.  When I got into preferences, you can see the toggle move to the right. 


https://github.com/user-attachments/assets/e31c3659-5c18-4a21-bef5-55c1e574d4d6

**Comment by c3024** [comment] 2024-11-07 04:02
I think that appearance of toggling action happening on visiting the page is not related to the issue sounds playing even after muting.

PR #52088 fixes the sounds problem.

**Comment by isabelastisser** [comment] 2024-11-11 16:05
The payments were processed in Upwork now.

@jjcoffee, do we need a regression test for this?

**Comment by jjcoffee** [comment] 2024-11-12 10:38
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by isabelastisser** [comment] 2024-11-12 18:35
All set!

**Closed by isabelastisser** 2024-11-12 18:35 UTC
Labels: External, Weekly, Awaiting Payment, Bug, AutoAssignerNewDotQuality
