### ISSUE TITLE
[PAY PRIYA] Android - Not able to receive notifications for request/send/split money

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19726] opened 2023-05-28 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to mweb chrome and login with User A
2. Go to the chat with User B (Make sure to login with UserB on android - latest version- 1.3.17-5)
3. From User A account on mweb chrome , try to send text messages and notice that notification is well received in User B side on android
4. But now try to send/request money and notice that on the receiver side of User B, notification is not received

## Expected Result:
Notification should be received for request/send money as well in a similar how it is received with messages

## Actual Result:
Notification is not received for request/send money on android but works well with messages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6f7c48cd-d334-4fdb-8ee0-e4ec952b7a24

https://github.com/Expensify/App/assets/93399543/a4f8117f-cb02-4657-9a96-4a423ebbaf07

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684991900955059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bb5a28ad3690437</li>
        <li>Upwork Job ID: 1663708277029507072</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by priya-zha** [comment] 2023-05-29 03:44
@kbecciv I think by mistake you have kept someone else's GH handle on the initial reporter. My GH handle is @priya-zha. Thanks.

**Comment by kbecciv** [comment] 2023-05-29 14:34
@priya-zha Corrected

**Comment by kadiealexander** [comment] 2023-05-30 04:39
@priya-zha does User A have to be using android mWeb or can they message User B from any platform to reproduce this bug?

**Comment by priya-zha** [comment] 2023-05-30 04:45
@kadiealexander I tried using User A on Web chrome and mweb chrome and the bug was reproducible. I haven't tried on ioS/ mac or on android.

**Comment by kadiealexander** [comment] 2023-05-30 05:13
Thanks @priya-zha! I tested this with myself on mac web chrome as user A and @jliexpensify on Android native app as user B, and @jliexpensify got both notification types:

![Screenshot_20230530-145718](https://github.com/Expensify/App/assets/59587260/4762dba0-d0ec-4d79-90f2-89e4043481cf)

![Screenshot_20230530-145335](https://github.com/Expensify/App/assets/59587260/18b3ae4a-f014-4581-8e22-9e68ee316494)

**Comment by priya-zha** [comment] 2023-05-30 05:48
Sure.Let me check

**Comment by priya-zha** [comment] 2023-05-30 06:01
Are you testing it on a real device or emulator ? I updated the app from the playstore and it shows the latest version as 1.3.19-7 and in this version, I'm still able to reproduce the bug. Also, the users doesn't need to be in the same device. because I logged in with User A on web chrome (laptop) and User B on android.  I am unable to see the version 1.3.20-1.

**Comment by jliexpensify** [comment] 2023-05-30 06:21
Real device (Pixel 3a) - I just updated on the Google store for the 2nd round of testing with Kadie.

**Comment by kadiealexander** [comment] 2023-05-31 00:45
Assigning @jliexpensify as this is an android issue. We were able to determine that the notifications above are from our old app, so no newdot notifications came through.

**Comment by roryabraham** [comment] 2023-06-03 00:12
This may actually be a feature request, I'm not sure if we've ever sent push notifications for IOU activity

**Comment by roryabraham** [comment] 2023-06-03 00:19
This will need to be internal and is not testable by external contributors.

**Comment by roryabraham** [comment] 2023-06-03 00:29
Brought conversation to slack: https://expensify.slack.com/archives/C02HWMSMZEC/p1685751895005119, proposed updated notification logic [here](https://expensify.slack.com/archives/C02HWMSMZEC/p1685752117853619?thread_ts=1685751921.007729&cid=C02HWMSMZEC)

**Comment by roryabraham** [comment] 2023-06-06 00:11
Created PR: https://github.com/Expensify/Web-Expensify/pull/37725

**Comment by roryabraham** [comment] 2023-06-09 21:14
PR merged ~12 hours ago

**Comment by jliexpensify** [comment] 2023-06-19 00:11
@roryabraham good to close this one? Looks like it's deployed to Prod already.

**Comment by roryabraham** [comment] 2023-06-22 16:40
Yep

**Comment by priya-zha** [comment] 2023-06-22 17:02
@roryabraham I'm the external reporter for this bug.

**Comment by roryabraham** [comment] 2023-06-22 20:53
Oh, my mistake. @jliexpensify let's pay the bug reporting bonus for this, then close it out.

**Comment by jliexpensify** [comment] 2023-06-23 05:03
Had to make a new listing (I swear Upworks is so frustrating these days!) - https://www.upwork.com/jobs/~0161fd70cf89389a56

Invited you @priya-zha

**Comment by priya-zha** [comment] 2023-06-23 05:07
Accepted. Thanks.

**Comment by jliexpensify** [comment] 2023-06-23 05:39
Paid and closed job!

**Closed by jliexpensify** 2023-06-23 05:39 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
