### ISSUE TITLE
[HOLD for payment 2024-11-26] [$250] Company cards - Error appears after tapping the explanation link for the first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52144] opened 2024-11-06 21:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.58-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51575
## Action Performed:
1. Open New Expensify staging hybrid app.
2. Create a workspace and enable Company cards feature.
3. Go to Company cards page.
4. Tap Add company cards button to start add feed flow.
5. Select Amex provider (or Visa/Mastercard providers in Others). Tap Next 3 times.
6. On the details screen, below input field tap the explanation link.

## Expected Result:
After tapping the explanation link under the input field user is redirected to the relevant web page

## Actual Result:
Error appears under the input field "This field is required" after tapping the explanation link for the first time. User is successfully redirected to the relevant page after tapping the link second time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/22c6421c-d96b-425b-b40f-02158eedcf4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856152080745182402</li>
        <li>Upwork Job ID: 1856152080745182402</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104860234</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by bernhardoj** [comment] 2024-11-07 03:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Validation error appears when pressing the link in company card step.

### What is the root cause of that problem?
The validation shows every time the input is blurred. When we press the text link, the text input blurs. This doesn't happen in web because by default, we preventDefault it.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/TextLink.tsx#L35

In native, pressing a button normally doesn't blur the active input. But in our case, the page is wrapped with a ScrollView with no `keyboardShouldPersistTaps`. So, if we tap inside the scroll view, then it will close the keyboard.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/pages/workspace/companyCards/addNew/DetailsStep.tsx#L175-L208

### What changes do you think we should make in order to solve the problem?

We can add `keyboardShouldPersistTaps='handled'` to the ScrollView.

OR

We can just remove the ScrollView and move the Text inside FormProvider because FormProvider already uses a ScrollView which already has `keyboardShouldPersistTaps="handled"`.
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/pages/workspace/companyCards/addNew/DetailsStep.tsx#L175-L190
https://github.com/Expensify/App/blob/afa7b33107747d0242acfd01d032d5339be390d9/src/components/Form/FormWrapper.tsx#L163-L177

(we need to remove the padding from text because FormProvider already has the horizontal margin.)

**Comment by trjExpensify** [comment] 2024-11-12 01:17
Let's get eyes from @mountiny @allgandalf @DylanDylann on the approach here. What technical approach do we take on native for other links in forms, like a terms link in a RHP form?

**Comment by mountiny** [comment] 2024-11-12 01:19
Nice one QA. @allgandalf @DylanDylann which one of you wants to take this one and review the proposals so its in line with how we handle it elsewhere in the app?

**Comment by DylanDylann** [comment] 2024-11-12 01:43
I can help on this issue

**Comment by trjExpensify** [comment] 2024-11-12 01:48
Assigned! Sending `External` then.

**Comment by DylanDylann** [comment] 2024-11-12 02:28
I can't reproduce this bug. @bernhardoj Could you reproduce this bug?

https://github.com/user-attachments/assets/f24297ab-d355-4550-94a6-152658c79d6e

**Comment by DylanDylann** [comment] 2024-11-12 02:41
Ahh I missed this step 

> Select Amex provider (or Visa/Mastercard providers in Others). Tap Next 3 times.

**Comment by DylanDylann** [comment] 2024-11-12 03:35
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/52144#issuecomment-2461261409) looks good to me. I prefer the second solution

🎀 👀 🎀 C+ Reviewed

**Comment by bernhardoj** [comment] 2024-11-12 15:21
PR is ready

cc: @DylanDylann

**Comment by mountiny** [comment] 2024-11-20 10:33
$250 to @bernhardoj and $125 to @DylanDylann 

For Dylan the payment is less as he is working on this as a project and we agreed for lower base price

**Comment by trjExpensify** [comment] 2024-11-26 19:12
Cool, sounds good! Payment summary as follows: 

- $125 to @DylanDylann for the C+ review (paid!)
- $250 to @bernhardoj for the fix (go ahead and request!)

@DylanDylann can we get the checklist, please? I believe regression tests will be added centrally for the project, but it would be good to identify where this error was missed to give the author(s) a heads up.

**Comment by DylanDylann** [comment] 2024-11-27 01:22
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by bernhardoj** [comment] 2024-11-27 03:06
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-11-27 12:40
$250 approved for @bernhardoj

**Comment by trjExpensify** [comment] 2024-11-27 17:39
Great, thanks. Closing!

**Closed by trjExpensify** 2024-11-27 17:39 UTC
Labels: External, Daily, Awaiting Payment, Bug
