### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Temporary thread message disappearance when deleting a thread message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23139] opened 2023-07-18 22:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send a message in the chat
3. Click on "Reply in thread" to create a thread message
4. Delete the threaded message
## Expected Result: 
The thread message should remain visible without any disappearance upon deletion
## Actual Result: 
When deleting a thread message, it momentarily disappears for a second before reappearing

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/dd910f75-71ab-4898-bc53-84ebe2c4eea7

https://github.com/Expensify/App/assets/43996225/74f241bb-6207-496d-a8b7-cd2e64c06ffe

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689603772547949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed092abd8ef6cd10</li>
        <li>Upwork Job ID: 1681482271492681728</li>
        <li>Last Price Increase: 2023-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26432430</li>
<li>Nodebrute | Contributor | 26432431</li>
</ul></li>
    </ul>
</details>

**Comment by jeffmchang** [comment] 2023-07-19 00:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It looks like the bug here is directed to the chat system where a new 'chat tab' is created when you reply in a thread. When that new tab is created, it allows a new conversation to take place.:

![image](https://github.com/Expensify/App/assets/109321774/4e90d3e2-c82c-4987-9161-03d4462e54f8)

The first message of this new 'thread' will refer to the comment being replied to:

![image](https://github.com/Expensify/App/assets/109321774/0058fcf0-4a86-41f2-b1bd-fc4467471d24)

The problem here is when you have messages being sent post-thread creation, they act as normal messages and can be deleted without issues. But when you attempt to delete the first message (comment being replied to), it results in a standard disappearance of the message, but then the message comes back with [Deleted message]. Once the first message in the new thread has been deleted, that results in the original message in the main conversation being deleted as well.

**Normal Delete:**
![image](https://github.com/Expensify/App/assets/109321774/90f43d9b-7ecc-4ec8-ae96-774e7072b00f)

**Bugged Delete:**
![image](https://github.com/Expensify/App/assets/109321774/1f983259-14ba-4244-a5af-3d039e0b2055)

**This also leads to a bugged/empty thread:**
![image](https://github.com/Expensify/App/assets/109321774/95065cf7-c0ea-4128-9efc-0b54895b745c)

**If the message is deleted but the in-thread messages are still there, the [Deleted message] remains and keeps the thread open:**
![image](https://github.com/Expensify/App/assets/109321774/a1c97a2b-991f-4ef1-8cbd-b8e66802b978)


### What is the root cause of that problem?
From a surface-level standpoint, it looks like the [Deleted message] is showing up because the component is not updating and removing the thread altogether.
I'm having trouble finding the exact location of the bug, if someone is able to provide me with a time-efficient way to locate the file that this bug is occurring on, that would be much appreciated. 

### What changes do you think we should make in order to solve the problem?
I think we should change the action of deleting the messages. If the main thread comment is deleted, it confirms deletion and prompts that deleting the main thread comment will result in the entire thread being deleted. Upon deletion, it will automatically remove the thread as a conversation tab in the left column.

**Comment by MitchExpensify** [comment] 2023-07-19 01:51
I see some discussion related to this here https://expensify.slack.com/archives/C049HHMV9SM/p1685965494942699?thread_ts=1684354260.051229&cid=C049HHMV9SM

**Comment by MitchExpensify** [comment] 2023-07-19 01:52
Also related to the first thread message and deletion but not quite this issue https://github.com/Expensify/App/issues/19363

**Comment by MitchExpensify** [comment] 2023-07-19 01:52
Not a dupe from what I can tell

**Comment by aditya-ragi** [comment] 2023-07-19 02:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we delete a Thread parent, It disappears for a moment, and then the [Deleted message] message appears.

### What is the root cause of that problem?

We are push in `optimisticData` :

`{
    "onyxMethod": "merge",
    "key": "reportActions_3529565171134454",
    "value": {
        "6902849697016981155": {
            "childVisibleActionCount": 0,
            "childCommenterCount": 0,
            "childLastVisibleActionCreated": "",
            "childOldestFourAccountIDs": ""
        }
    }
}`

These empty values are the root cause for disappearing of Thread message before getting updated to [Deleted message].

### What changes do you think we should make in order to solve the problem?

Removing the following act of pushing this object with empty values solves the issue.

` if (parentReportAction && parentReportAction.reportActionID) {
            optimisticData.push({
                onyxMethod: Onyx.METHOD.MERGE,
                key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportID}`,
                value: {
                    [parentReportAction.reportActionID]: ReportUtils.updateOptimisticParentReportAction(
                        parentReportAction,
                        optimisticReport.lastVisibleActionCreated,
                        CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE,
                    ),
                },
            });
        }`

### What alternative solutions did you explore? (Optional)
Exploring

**Comment by aditya-ragi** [comment] 2023-07-19 02:40
Contributor details
Your Expensify account email: hireadityaragi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f8498acbc5e8f6e4

**Comment by aditya-ragi** [comment] 2023-07-19 03:27
just added alternate solution to the proposal now.

**Comment by jigartankhupp** [comment] 2023-07-19 13:43
### **Proposal**


### **Please re-state the problem that we are trying to solve in this issue.**
The thread message should remain visible without any disappearance upon deletion

### **What is the root cause of that problem?**
I've found the old commit code where the thread message delete functionality working fine. #22690 
<img width="1380" alt="Screen Shot 2023-07-19 at 7 05 42 PM" src="https://github.com/Expensify/App/assets/38810839/a545687c-8824-41fa-b6a6-75eedad8568c">

If you revert the code with this:
```
function hasCommentThread(reportAction) {
    return lodashGet(reportAction, 'childType', '') === CONST.REPORT.TYPE.CHAT;
}
```
Then it's working fine.
I've attached the video here that things are working fine.
https://github.com/Expensify/App/assets/38810839/6d5ee745-3606-4b70-90f7-2375a03cfc62

I hope this will solve the problem.

Thanks

**Comment by mehvash-Khan** [comment] 2023-07-19 22:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In a thread of a message, when we try to delete the message when thread has no other replies/messages, it disappears before showing `[Deleted Message]`

### What is the root cause of that problem?
The root cause of this issue is the fact that the `shouldHideOnDelete` prop passed to `OfflineWithFeedback` in `ReportActionItem` is set to `true` when the root message of the thread is deleted while not having any replies/messages on it.  This is because of the recently added condition to `hasCommentThread` function by #22690 .

### What changes do you think we should make in order to solve the problem?
In order to solve this I think this code should be mindful of the report page/main chat room that is currently open. For example, this works well when the thread with no replies to it is deleted in the main chatroom. While this does not work when the thread is being deleted in its own report page/chatroom where it is expected to display `[Deleted Message]` instead of hiding it entirely.

To tackle this we can the following condition to prop `shouldHideOnDelete`

```js
 shouldHideOnDelete={!(ReportActionsUtils.hasCommentThread(props.action) || props.action.reportActionID === props.report.parentReportActionID)}
```

When a report action/message is being rendered in its own chat room/thread room, the action passed to `ReportActionItem` is actually the parent report action but the report is the current report as can be seen [here](https://github.com/Expensify/App/blob/3e3a5238923df705ef4ab5d8cda039a1a1e3fcec/src/pages/home/report/ReportActionsList.js#L132-L153) and [here](https://github.com/Expensify/App/blob/3e3a5238923df705ef4ab5d8cda039a1a1e3fcec/src/pages/home/report/ReportActionItemParentAction.js#L64-L71).  Basically the 2nd part of the condition checks that the message/report action being deleted is in a thread room of its own having a parentReportActionID equal to the id of the report action/message. 

This change will prevent the message that is deleted from disappearing momentarily but there would still be a problem where the initial message will continue to be displayed until the Api request is complete after which `[Deleted Message]` is displayed.

To avoid this, we can add a similar condition [here](https://github.com/Expensify/App/blob/3e3a5238923df705ef4ab5d8cda039a1a1e3fcec/src/pages/home/report/ReportActionItemFragment.js#L107-L109). I would propose we rename the `hasCommentThread` prop to the component `ReportActionItemFragment` to `shouldDisplayDeletedWhenPending`(or some better name) and pass to it the following:

```js
  shouldDisplayDeletedWhenPending={ReportActionsUtils.hasCommentThread(props.action) || props.action.reportActionID === props.report.parentReportActionID}
```

Please node that we would also need to pass `report` as a prop from `ReportActionItem` to `ReportActionItemMessage`.

**Comment by jigartankhupp** [comment] 2023-07-20 04:05
Contributor details
Your Expensify account email: [jigarjs@hupp.in](mailto:jigarjs@hupp.in)
Upwork Profile Link: https://www.upwork.com/freelancers/~012a5ed1b4a78d3b2c

**Comment by jigartankhupp** [comment] 2023-07-20 04:09
I've just created my email jigarjs@hupp.in in Expensify

**Comment by jigartankhupp** [comment] 2023-07-20 04:44
Contributor details
Your Expensify account email: jigarjs@hupp.in
Upwork Profile Link: https://www.upwork.com/freelancers/~012a5ed1b4a78d3b2c

**Comment by mehvash-Khan** [comment] 2023-07-25 11:46
Hey @fedirjh,

I have updated the root cause of my [proposed solution](https://github.com/Expensify/App/issues/23139#issuecomment-1642862572). Could you please review it again?

Also from the PRs you mentioned
* #22864 was merged after this issue/bug was reported so it may not be the cause for this. 
* In #20762, changes are related to updating `childVisibleActionCount` when a comment to thread is added/deleted. In our case of deletion, it will be a no-op as `childVisibleActionCount` is 0 (since there are no replies/comments to the thread)and according to the change if `childVisibleActionCount` is 0, this variable is not updated.

**Comment by adityaaa-r** [comment] 2023-07-27 11:29
@fedirjh I have updated my [Proposal](https://github.com/Expensify/App/issues/23139#issuecomment-1641295345) with a better explanation of Root cause. Have a look!

**Comment by mehvash-Khan** [comment] 2023-07-29 08:26
I believe what @Nodebrute is saying is correct. Deleted message should be checked if it is a parent message while decrementing the childcount.

What my solution proposes is that it deletes the parent message irrespective of its child count. This means if deleted message is a parent message, it will not decrement the child count at all.  Please check video below.

https://github.com/Expensify/App/assets/127308250/69b8ba58-3653-400a-9074-38a7a1bc974c

. Attaching a recording here.

**Comment by MitchExpensify** [comment] 2023-08-01 17:39
Friendly reminder to review the proposals @fedirjh to keep Melvin off our backs 👍

**Comment by mehvash-Khan** [comment] 2023-08-04 11:35
Hey @fedirjh ,

Yes you are right. We can use `ReportUtils.isThreadFirstChat` instead of the condition I have mentioned. I did not notice this function in the code. 

> This doesn’t look like a wise pattern, It will have a negative effect on performance,any changes to the report object will trigger re-render for all child comments at the same time.

Yes, since now we are planning to use `ReportUtils.isThreadFirstChat`, we just need to pass the report id and not the entire report object in the props of `ReportActionItemMessage`. I don't believe this should introduce any performance issues as the report id will not change unless we're visiting a different thread/chat room. 

So updating below my suggestion for adding the condition in `ReportActionItemMessage`

```js
 shouldHideOnDelete={!(ReportActionsUtils.hasCommentThread(props.action) ||  ReportActionsUtils.hasCommentThread(props.action,props.report.reportID)}
```

@fedirjh 

Regarding:
>  I think fixing ReportActionsUtils.hasCommentThread makes the most sense to me

I don't believe this would be wise as `hasCommentThread` is currently meant to identify if a message has it's thread of it's own, which we may want to check in the main chat room as well. The issue we need to fix here is very specific to when a message is opened in it's own thread/chat room.

**Comment by mehvash-Khan** [comment] 2023-08-04 11:37
@Nodebrute @fedirjh 

If we update `hasCommentThread` directly, I believe we might introduce a similar bug when deleting a thread message in main chat room.

**Comment by mehvash-Khan** [comment] 2023-08-04 12:02
>Here, we can also use ReportUtils.isThreadFirstChat instead of the last check I added. Notice that I am passing an additional parameter, reportID. This parameter can be easily passed wherever we are using hasCommentThread.

@Nodebrute If we do this change, this will only be true if a message is in its own thread. This will always be false in the main chat room.

**Comment by mehvash-Khan** [comment] 2023-08-04 12:08
@fedirjh ,

Adding this condition to our props below will work in both our cases, i.e message is deleted in main chat room and when message is deleted in its own thread.

```js
   shouldDisplayDeletedWhenPending={ReportActionsUtils.hasCommentThread(props.action)|| ReportActionsUtils.isThreadFirstChat(props.action,props.report.reportID)}
```

**Comment by mehvash-Khan** [comment] 2023-08-04 12:53
@fedirjh ,

Adding below condition to our props for `ReportActionItemFragment` below will work in both our cases, i.e message is deleted in main chat room and when message is deleted in its own thread.

`ReportActionItemMessage.js`
```js
  shouldDisplayDeletedWhenPending={ReportActionsUtils.hasCommentThread(props.action)|| ReportUtils.isThreadFirstChat(props.action,props.reportID)}
```

`ReportActionItem.js`
```js
  shouldHideOnDelete={!(ReportActionsUtils.hasCommentThread(props.action)|| ReportUtils.isThreadFirstChat(props.action,props.report.reportID))}
```

I have tried these changes and they are working perfectly without introducing any new bug in our existing code or our main chat room. I believe if we try and update `hasCommentThread`, it won't solve the issue where message is being deleted in main chat room with children.

**Comment by MitchExpensify** [comment] 2023-08-07 12:50
A few proposals/updates ready for you @fedirjh 👍

**Comment by MitchExpensify** [comment] 2023-08-09 19:50
> A few proposals/updates ready for you @fedirjh 👍

@fedirjh another lil bump here 👍

**Comment by mehvash-Khan** [comment] 2023-08-10 15:20
@fedirjh , Sure. I will share detailed proposal to you by tonight.

**Comment by mehvash-Khan** [comment] 2023-08-10 18:52
@fedirjh Presenting my changes below.

## Proposal

This proposal has been tested and works fine in all scenarios which also includes deletion of message when offline even with multiple children in its own thread. Also this method does not require making updates in our `hasCommentThread` function which seems to be fair as changing any functionality in this method will make it specific to this scenario and bug which won't be a good practice.

1. Make below change in `ReportActionItem.js`

We will pass an extra condition in `shouldHideOnDelete` to check if message is in its thread of its own. Also we will pass report ID as prop to `ReportActionItemMessage`

```diff
+++ b/src/pages/home/report/ReportActionItem.js
@@ -329,6 +329,7 @@ function ReportActionItem(props) {
                         <View style={props.displayAsGroup && hasBeenFlagged ? styles.blockquote : {}}>
                             <ReportActionItemMessage
                                 action={props.action}
+                                reportID={props.report.reportID}
                                 isHidden={isHidden}
                                 style={[
                                     !props.displayAsGroup && isAttachment ? styles.mt2 : undefined,
@@ -539,7 +540,7 @@ function ReportActionItem(props) {
                             <OfflineWithFeedback
                                 onClose={() => ReportActions.clearReportActionErrors(props.report.reportID, props.action)}
                                 pendingAction={props.draftMessage ? null : props.action.pendingAction}
-                                shouldHideOnDelete={!ReportActionsUtils.hasCommentThread(props.action)}
+                                shouldHideOnDelete={!(ReportActionsUtils.hasCommentThread(props.action)|| ReportUtils.isThreadFirstChat(props.action,props.report.reportID))}
                                 errors={props.action.errors}
                                 errorRowStyles={[styles.ml10, styles.mr2]}
                                 needsOffscreenAlphaCompositing={ReportActionsUtils.isMoneyRequestAction(props.action)}
```


2. Make changes in `ReportActionItemMessage.js`

```diff
+++ b/src/pages/home/report/ReportActionItemMessage.js
@@ -8,10 +8,12 @@ import ReportActionItemFragment from './ReportActionItemFragment';
 import * as ReportActionsUtils from '../../../libs/ReportActionsUtils';
 import reportActionPropTypes from './reportActionPropTypes';
 import withLocalize, {withLocalizePropTypes} from '../../../components/withLocalize';
+import * as ReportUtils from '../../../libs/ReportUtils';

 const propTypes = {
     /** The report action */
     action: PropTypes.shape(reportActionPropTypes).isRequired,
+    reportID: PropTypes.string,

     /** Additional styles to add after local styles. */
     style: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.object), PropTypes.object]),
@@ -26,6 +28,7 @@ const propTypes = {
 const defaultProps = {
     style: [],
     isHidden: false,
+    reportID:'',
 };

 function ReportActionItemMessage(props) {
@@ -37,7 +40,7 @@ function ReportActionItemMessage(props) {
                         key={`actionFragment-${props.action.reportActionID}-${index}`}
                         fragment={fragment}
                         isAttachment={props.action.isAttachment}
-                        hasCommentThread={ReportActionsUtils.hasCommentThread(props.action)}
+                        shouldDisplayDeletedWhenPending={ReportActionsUtils.hasCommentThread(props.action) || ReportUtils.isThreadFirstChat(props.action,props.reportID)}
                         attachmentInfo={props.action.attachmentInfo}
                         pendingAction={props.action.pendingAction}
                         source={lodashGet(props.action, 'originalMessage.source')}
```



3. Make changes in `ReportActionItemFragment.js`

```diff
+++ b/src/pages/home/report/ReportActionItemFragment.js
@@ -21,6 +21,7 @@ import editedLabelStyles from '../../../styles/editedLabelStyles';
 import UserDetailsTooltip from '../../../components/UserDetailsTooltip';
 import avatarPropTypes from '../../../components/avatarPropTypes';

+
 const propTypes = {
     /** Users accountID */
     accountID: PropTypes.number.isRequired,
@@ -64,6 +65,8 @@ const propTypes = {
     /** icon */
     actorIcon: avatarPropTypes,

+    shouldDisplayDeletedWhenPending: PropTypes.bool,
+
     ...windowDimensionsPropTypes,

     /** localization props */
@@ -109,7 +112,7 @@ function ReportActionItemFragment(props) {
             // While offline we display the previous message with a strikethrough style. Once online we want to
             // immediately display "[Deleted message]" while the delete action is pending.

-            if ((!props.network.isOffline && props.hasCommentThread && props.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) || props.fragment.isDeletedParentAction) {
+            if ((!props.network.isOffline && props.shouldDisplayDeletedWhenPending && props.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) || props.fragment.isDeletedParentAction) {
                 return <RenderHTML html={`<comment>${props.translate('parentReportAction.deletedMessage')}</comment>`} />;
             }
```

And that's all. This has minimal changes in just 3 files and is working as expected without any regression.

**Comment by mehvash-Khan** [comment] 2023-08-14 13:52
@fedirjh Thanks for selecting my proposal.

>also the selected proposal can easily cause regression.

 @Nodebrute It seems this is not a regression as I was able to reproduce this issue in production. Our change and issue has nothing to do with delay during slow internet as in the proposed solution we are only dealing with data points which are present in Onyx and are not dependent on network response.

**Comment by MitchExpensify** [comment] 2023-08-21 22:20
@fedirjh whats the status on the progress of this issue? Thanks!

**Comment by MitchExpensify** [comment] 2023-08-29 04:45
Carlos is ooo for until Sep 4th so looking for some help in the meantime @Beamanator 🙇

**Comment by Beamanator** [comment] 2023-08-31 13:19
Wow, well done sticking with this one for many weeks @fedirjh 🙏  I like your suggestion, let's go with @Nodebrute 👍

**Comment by MitchExpensify** [comment] 2023-09-14 21:14
**Payment summary**:

$1000 - @fedirjh requires payment [offer](https://www.upwork.com/nx/wm/offer/26432430) (Reviewer)
$1000 - @Nodebrute requires payment [offer](https://www.upwork.com/nx/wm/offer/26432431) (Contributor)
$250 - @ayazhussain79 requires payment

**Comment by MitchExpensify** [comment] 2023-09-21 15:05
Friendly bump on the BZ steps @fedirjh

**Comment by MitchExpensify** [comment] 2023-09-21 15:12
Paid:
$1000 - @fedirjh requires payment [offer](https://www.upwork.com/nx/wm/offer/26432430) (Reviewer)
$1000 - @Nodebrute requires payment [offer](https://www.upwork.com/nx/wm/offer/26432431) (Contributor)

Pending:
$250 - @ayazhussain79 requires payment - I've resent an offer, please let me know once you accept https://www.upwork.com/nx/wm/offer/26799902

**Comment by MitchExpensify** [comment] 2023-09-21 17:12
Paid! Thanks @ayazhussain79 

Waiting on BZ steps before closing this out cc @fedirjh

**Comment by MitchExpensify** [comment] 2023-09-25 07:41
Awesome added a request to add this! https://github.com/Expensify/Expensify/issues/319505

**Closed by MitchExpensify** 2023-09-25 07:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
