### ISSUE TITLE
[HOLD for payment 2022-12-05] Empty chat screen appears with welcome message after login

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13000] opened 2022-11-24 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > Sign out
2. Sign in with the same account

## Expected Result:
Page opens with chat loaded on the RHN where it was left before logout

## Actual Result:
Empty chat screen with welcome message appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.31-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Screenshot 2022-11-24 at 6 54 23 PM" src="https://user-images.githubusercontent.com/43996225/203819941-30c8b2cb-e766-4a11-b337-b1954bbe0d94.png">

https://user-images.githubusercontent.com/43996225/203819943-08a02127-bc40-404f-aab4-4cb5b1f6aabd.mp4

![image (1)](https://user-images.githubusercontent.com/43996225/203819948-3bbd19d3-0c12-4277-8fe1-b485392bbd4b.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia / Applause internal team
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669298063601539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-24 17:24
I'm unable to reproduce this

**Comment by luacmartins** [comment] 2022-11-24 17:45
@mvtglobally the team can't reproduce it. Would you mind checking again?

**Comment by luacmartins** [comment] 2022-11-24 18:28
I was just able to reproduce this 
![Screenshot 2022-11-24 at 11 26 26 AM](https://user-images.githubusercontent.com/22219519/203847744-00336c2d-974b-4d2c-9b01-f87ff6dbb617.png)

I see this console error `An error occurred while applying merge for key: report_3473132785054582, Error: TypeError: Cannot convert undefined or null to object` and the response from `OpenApp` is:

```
jsonCode: 407
message: "Your session has expired. Please sign in again."
requestID: "76f430588efc4214-SJC"
title: "Session expired"
```

**Comment by luacmartins** [comment] 2022-11-24 18:32
Tried again and this time I got `An error occurred while applying merge for key: report_3473132785054582, Error: TypeError: Cannot convert undefined or null to object` and `OpenApp` response is 
![Screenshot 2022-11-24 at 11 31 42 AM](https://user-images.githubusercontent.com/22219519/203848262-306dbdf7-034f-4af8-8bec-48c7e2075e67.png)

I wonder if it's related to the IOUReport key refactor @Gonals

**Comment by luacmartins** [comment] 2022-11-24 20:56
This seems to be an API issue, investigating

**Comment by luacmartins** [comment] 2022-11-24 22:55
Fix up here https://github.com/Expensify/App/pull/13028

**Comment by sophiepintoraetz** [comment] 2022-11-24 23:19
Speedy work, thanks Carlos! Let me know if you need me at all here

**Comment by luacmartins** [comment] 2022-11-24 23:31
Nope this is all done! The PR is merged and we are CPing the fix at this moment, so I'll close this issue.

**Comment by thesahindia** [comment] 2022-11-25 14:57
@sophiepintoraetz, this is eligible for the reporting compensation.

**Comment by luacmartins** [comment] 2022-11-25 18:27
@thesahindia sorry, I missed that. Reopening!

**Comment by luacmartins** [comment] 2022-11-25 18:27
@sophiepintoraetz could you please pay the reporting bonus to @thesahindia?

**Comment by luacmartins** [comment] 2022-11-26 06:05
Removing deploy blocker label since this was fixed and I just reopened to pay the bonus!

**Comment by mvtglobally** [comment] 2022-11-30 05:06
Issue not reproducible during KI retests. (First week)

**Comment by thesahindia** [comment] 2022-11-30 11:51
> @sophiepintoraetz could you please pay the reporting bonus to @thesahindia?

Bump @sophiepintoraetz

**Comment by thesahindia** [comment] 2022-12-01 14:13
Accepted, thanks!

**Comment by luacmartins** [comment] 2022-12-01 16:09
@thesahindia @sophiepintoraetz are we good to close this issue?

**Comment by thesahindia** [comment] 2022-12-01 23:01
@luacmartins, payment is pending.

cc: @sophiepintoraetz

**Comment by sophiepintoraetz** [comment] 2022-12-01 23:08
@thesahindia - paid!

Also @luacmartins - we've got[ this](https://github.com/Expensify/App/issues/13000#issuecomment-1329712037) to do before we can close out the issue

**Comment by luacmartins** [comment] 2022-12-02 00:38
@sophiepintoraetz checklist done!

**Comment by sophiepintoraetz** [comment] 2022-12-02 00:42
Coolio - looks like we're sorted here! I don't think we need to add a regression test given that we had a fix planned!

**Closed by sophiepintoraetz** 2022-12-02 00:42 UTC
Labels: Reviewing, Engineering, Weekly, Awaiting Payment, Bug
