### ISSUE TITLE
[$1000] Dev:  iOS - App crashes when clicking 'fix all errors'

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21686] opened 2023-06-27 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Go to settings.
2. Go to your workspace.
3. Navigate to 'Travel' and connect bank account manually.
4. Add Routing number (074000078) and Account number (1234), then try to continue without accepting the terms.
5. Click on the "Fix errors" link.

## Expected Result:
App does not crash

## Actual Result:
 App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ac169a3d-0cad-4d09-9cc4-092b708d113d

**Expensify/Expensify Issue URL:**
**Issue reported by:** Sibtain Ali
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687522491184139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b709d4daea7a4b8f</li>
        <li>Upwork Job ID: 1674286707422703616</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-06-27 16:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the first invalid form input is a checkbox, an exception is thrown in the app.

### What is the root cause of that problem?

On iOS, `Pressable` (and `View`) have a `focus` method, but calling it throws an exception. `Checkbox` forwards its reference to `Pressable`.

`Form` calls `focus` on the first invalid form input when the "Fix the errors" button is pressed. 

### What changes do you think we should make in order to solve the problem?

On Native, our `Checkbox` class does not support any kind of focus, so there's no need to expose a `focus` method.

Instead, it's enough to expose `measureLayout`, which is called by `Form` when determining where to scroll to. 

As the `Checkbox` component is a Functional Component, exposing methods is done with the `useImperativeHandle` API.

```jsx
function Checkbox(props) {
    const pressableRef = useRef();

    useImperativeHandle(
        props.forwardedRef,
        () => ({
            /**
             * Like measure(), but measures the view relative to an ancestor
             *
             * This method is used by Form when scrolling to the input
             *
             * @param {Object} relativeToNativeComponentRef - reference to an ancestor
             * @param {function(x: number, y: number, width: number, height: number): void} onSuccess - callback called on success
             * @param {function(): void} onFail - callback called on failure
             */
            measureLayout(relativeToNativeComponentRef, onSuccess, onFail) {
                if (!pressableRef.current) {
                    return;
                }

                pressableRef.current.measureLayout(relativeToNativeComponentRef, onSuccess, onFail);
            }
        }),
    );

    // ...

    return (
        <Pressable
            ref={pressableRef}
            // ...
        >
            // ...
        </Pressable>
    );
}
```

**Comment by kadiealexander** [comment] 2023-06-28 05:55
@allroundexperts could you please test this on the latest app version (1.3.33.3)? I was not able to reproduce using the steps you shared:

https://github.com/Expensify/App/assets/59587260/f2e7f398-b874-400d-b336-118c72855b98

**Comment by cubuspl42** [comment] 2023-06-28 11:33
@kadiealexander While the exception is thrown on all builds, the full-screen drawer with the exception description (the "crash" experience) is visible only on the developer (non-release) build.

**Comment by kadiealexander** [comment] 2023-06-29 05:20
Ah sorry for missing that! I was able to repro this in my dev environment:

![image](https://github.com/Expensify/App/assets/59587260/9faa73a3-1549-4add-aa35-1552b037f7e0)

**Comment by eVoloshchak** [comment] 2023-07-02 20:54
@cubuspl42, thanks for the [proposal](https://github.com/Expensify/App/issues/21686#issuecomment-1609827125)!
The approach looks good to me, but the scrolling isn't working. You can test this by adding `marginBottom: 800` to [these styles](https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/ReimbursementAccount/RequestorStep.js#L186).
When checkbox is the first element with the error, screen isn't scrolled to checkbox when pressing "fix all errors"


https://github.com/Expensify/App/assets/9059945/ecb55be8-5059-450c-bf09-59e3cf43a4a9

**Comment by cubuspl42** [comment] 2023-07-03 11:27
@eVoloshchak It seems to work for me... This is [my branch](https://github.com/cubuspl42/App/tree/fix-checkbox-focus-1). Could you try to test it there?

https://github.com/Expensify/App/assets/2590174/7f8005f8-5491-4356-9591-3282115cb053

**Comment by kadiealexander** [comment] 2023-07-06 04:55
@eVoloshchak could you please take a look here?

**Comment by eVoloshchak** [comment] 2023-07-06 16:55
> t seems to work for me... This is [my branch](https://github.com/cubuspl42/App/tree/fix-checkbox-focus-1). Could you try to test it there?

@cubuspl42, huh, weird, doesn't work for me when using your branch too
Which device/OS version you're using? Is it a physical device or an emulator?

**Comment by cubuspl42** [comment] 2023-07-06 17:14
@eVoloshchak Emulator, iPhone 14, iOS 16.2. How about you?

I just check on exactly the same page you were testing (as I chose another one with a checkbox before) and it didn't change a thing... Still works.

**Comment by eVoloshchak** [comment] 2023-07-10 22:02
Huh, weird, this didn't work for me in simulator, but works fine on a real device

@cubuspl42's [proposal](https://github.com/Expensify/App/issues/21686#issuecomment-1609827125) looks good to me
🎀👀🎀 C+ reviewed!
cc: @kadiealexander

**Comment by kadiealexander** [comment] 2023-07-11 01:29
@amyevans could you please review [this](https://github.com/Expensify/App/issues/21686#issuecomment-1629791718), and also investigate why @eVoloshchak's message didn't auto-assign an engineer?

**Comment by amyevans** [comment] 2023-07-11 20:22
Just to note, this isn't a crash, it's only a warning. I see we previously chose not to fix it in https://github.com/Expensify/App/issues/12508 and I think that's still a valid and perhaps better choice given this is dev-only on a single platform.

The proposal sounds like a workaround to me, so I don't _love_ it. Wouldn't it be better to not call `.focus()` in the first place?

<hr>

> also investigate why @eVoloshchak's message didn't auto-assign an engineer?

Logs are [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227e4c1759b9f7073f-IAD%22)+AND+timestamp:[2023-07-10T21:02:29.275Z+TO+2023-07-10T23:02:29.275Z]&index=logs_expensify-023240), it's not clear why it didn't work though, we don't log the payload so it's hard to know. cc @flodnv if you have any thoughts/guesses

**Comment by cubuspl42** [comment] 2023-07-11 21:10
@amyevans 

> Just to note, this isn't a crash, it's only a warning.

This is an unhandled exception, both on dev and on production. Unhandled exceptions are bugs, at least I haven't been involved in a project with a different perspective on this matter.

> I think that's still a valid and perhaps better choice given this is dev-only on a single platform.

I cannot see how ignoring an unhandled exception is better than writing the code in a way that doesn't trigger the erroneous path.

> The proposal sounds like a workaround to me, so I don't love it.

Could you elaborate on why you think that the proposal is a workaround? I cannot see a reason for Checkbox to expose methods it actually doesn't support.

> Wouldn't it be better to not call .focus() in the first place?

Well, then the functionality which depends on it wouldn't work.

We're calling the `focus` method on `focusInput` if it exists, following the reasoning that if it exists, it implements [this contract](https://reactnative.dev/docs/direct-manipulation#focus) (which is, probably, intuitive). I find this assumption reasonable.

https://github.com/Expensify/App/blob/032006b241f14711d96630151624d2535824bfa1/src/components/Form.js#L361-L363

This is a polymorphic call. `formInput` can be one of many `Form`-compatible input components. I cannot see anything wrong with this logic, I don't think there's a valid reason for changing it.

`Checkbox` doesn't support focusing, so from my perspective exposing a `focus` method is misleading from the beginning. The fact that it throws an exception is just the final argument to fix this.

**Comment by kadiealexander** [comment] 2023-07-12 01:07
@amyevans I missed the previous GH where we chose not to fix this, thanks for linking that! If the logic [here](https://github.com/Expensify/App/issues/12508#issuecomment-1312550084) that this is iOS related (not due to our code) is still true then I think it's best that we continue to do nothing, and close this.

**Comment by cubuspl42** [comment] 2023-07-12 05:52
> @amyevans I missed the previous GH where we chose not to fix this, thanks for linking that! If the logic [here](https://github.com/Expensify/App/issues/12508#issuecomment-1312550084) that this is iOS related (not due to our code) is still true then I think it's best that we continue to do nothing, and close this.

As I understand it, that's not the logic. The logic is that...

- "We calling focus on `Pressable` which we shouldn't"
- "there is no direct way to prevent that from `Form`"

And I agree with both points.

**Comment by cubuspl42** [comment] 2023-07-12 05:59
@amyevans 

> The proposal sounds like a workaround to me, so I don't _love_ it.

What do you think about an alternative way of controlling method forwarding more precisely?

We could implement a small utility...

```js
function useForwardingHandle(ref, methodTargets) {
    const obj = Object.entries(methodTargets).reduce(
        (acc, [methodName, targetRef]) => ({
            ...acc,
            [methodName]: (...args) => {
                if (!targetRef.current) {
                    return;
                }

                return targetRef.current[methodName](...args);
            }
        }),
    );

    useImperativeHandle(ref, () => obj);
}

```

...used like...

```js
function Checkbox(props) {
    const pressableRef = useRef();

    useForwardingHandle(
        props.forwardedRef,
        {
            measureLayout: pressableRef,
        },
    );

    // ...   
}
```

Maybe this would express the intention more clearly? I think such utility could become handy at times in other places, too.

**Comment by kadiealexander** [comment] 2023-07-12 21:17
Speedy fix! Thanks Flo :)

**Comment by amyevans** [comment] 2023-07-12 22:58
Okay, given this does not affect a customer's experience of the product (no change in UI, they are able to advance through the form as expected, etc), let's stay consistent with the outcome of the previous GH and close this as well.

Definitely appreciate your engagement though @cubuspl42! We have hundreds of other bugs open with higher impact on customers that are seeking help, so hope to see you around in the future

**Closed by amyevans** 2023-07-12 22:58 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
