### ISSUE TITLE
[HOLD for payment 2023-09-13] [HOLD for payment 2023-09-12] [$500] BUG: [distance] request next button is hidden on small height screens

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26541] opened 2023-09-01 23:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run App on latest main branch (for now)
2. Sign in with an account on the distance requests beta (or enable all betas)
3. Click green plus, request money, distance
4. Enter start and finish addresses
5. Open dev tools and set the responsive device dimensions to 400x400

## Expected Result:
Let's hide the map and show the request button, unless anyone else had better ideas.

## Actual Result:
The request button is hidden and you can't scroll down to it

## Workaround:
Use a reasonably sized device / orientation. The only real scenario here is mobile web in landscape view.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
Idk let's check
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** unreleased
**Reproducible in staging?:** Not yet
**Reproducible in production?:** Not yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Originally reported by Hayata in a [PR review here](https://github.com/Expensify/App/pull/25707#issuecomment-1701581536)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693611241072219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131f651439d571fb4</li>
        <li>Upwork Job ID: 1697755507566587904</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by RPSanchez** [comment] 2023-09-02 02:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
[distance] request next button is hidden on small height screens
### What is the root cause of that problem?
The code initially renders both the map and the "Request Next" button without considering the available screen height.
### What changes do you think we should make in order to solve the problem?

1. Dimensions should be imported via React Native for screen dimensions.
`[distance] request next button is hidden on small height screens`
2. Screen height should then be calculated.
`const windowHeight = Dimensions.get('window').height;`
3. Conditionally render the map and "Request Next" button depending on the size of the screen. If it's smaller than 400px - for example - hide the map and adjust the size of the button to fit the screen.
<View style={[styles.flexRow, styles.justifyContentCenter, styles.pt1]}>
4. The button size itself can further be edited via innerStyles.

### What alternative solutions did you explore? (Optional)
Rendering exclusively the map at a certain size, with user interaction then making the "Request Next" button available.

**Comment by RPSanchez** [comment] 2023-09-02 02:02
Contributor details
Your Expensify account email: raymondpaulsanchez@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01537b3cc571627ce8

**Comment by ZhenjaHorbach** [comment] 2023-09-02 09:07
# Please re-state the problem that we are trying to solve in this issue.

On small screens, the button is hidden under the map.

## What is the root cause of that problem?

Since the map has a fixed height and the screen does not support scrolling, there is no place for the button

## What changes do you think we should make in order to solve the problem?

We can add a ScrollView that will be disabled on large screens by scrollEnabled вместо <></>
https://github.com/Expensify/App/blob/9701fbe5ec24bf5031da390075b2a9fb125b3ce3/src/components/DistanceRequest.js#L164

But on small screens, the scroll will be available, which will allow to enjoy all the content.

https://github.com/Expensify/App/assets/68128028/909bb30b-408e-4984-a83e-0fd44ca79a96

What alternative solutions did you explore? (Optional)

NA

**Comment by rizalalfandi123** [comment] 2023-09-03 04:11
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
request next button is hidden on small height screens

## What is the root cause of that problem?
The screen below the distance tab is not scrollable, so when on a small screen it cannot fit all the content.

## What changes do you think we should make in order to solve the problem?
The best solution is to make the screen scrollable, so that all the content inside can be accessed by the user.
We can turn the React Fragment (<></>) into a ScrollView Component (<ScrollView></ScrollView>).

https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L164C11-L164C11

[Screencast from 2023-09-03 11-06-18.webm](https://github.com/Expensify/App/assets/90819361/59934e10-554b-489f-99f7-800708f38a38)
Note: scroll is only visible when the screen cannot fit all the content.

## What alternative solutions did you explore? (Optional)
None

**Comment by rizalalfandi123** [comment] 2023-09-03 04:13
Contributor details
Your Expensify account email: rizalalfandi123456789@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184b429844e7f9abd

**Comment by mananjadhav** [comment] 2023-09-04 16:37
@hayata-suenaga @neil-marcellini @CortneyOfstad what are your thoughts on adding a ScrollView?

**Comment by hayata-suenaga** [comment] 2023-09-04 21:14
@allroundexperts I gonna assign you please make a PR quickly 🙇

**Comment by jeet-dhandha** [comment] 2023-09-04 21:16
@hayata-suenaga 

https://github.com/Expensify/App/issues/26712#issuecomment-1705701081

**Comment by hayata-suenaga** [comment] 2023-09-04 21:17
@jeet-dhandha @ZhenjaHorbach @rizalalfandi123 

I know we're going to your solution but @allroundexperts was available right away to fix this, so I decided to assign them 🙇 

This is against a normal procedure, but as stated in the contributor guideline, we sometimes prioritize bug fixes and speed 🙇

**Comment by jeet-dhandha** [comment] 2023-09-04 21:17
Cool 👍

**Comment by hayata-suenaga** [comment] 2023-09-04 21:31
@allroundexperts please ping me on slack once the PR is up

**Comment by sakluger** [comment] 2023-09-14 17:24
Weird, I don't know why I was assigned to this one when @CortneyOfstad is already assigned. I'll remove myself and let Cortney finish payments.

**Comment by CortneyOfstad** [comment] 2023-09-15 12:55
So the issue was reported by @hayata-suenaga and the Contributor and C+ are both paid outside of Upwork, so no payments are needed at this time from me 👍 

@mananjadhav / @allroundexperts any updates on the checklist above? Thanks!

**Comment by mananjadhav** [comment] 2023-09-17 17:47
@CortneyOfstad I would like to request for a partial comp for C+ here. I did review the proposals, but due to urgency it was assigned on slack.

I am unsure at which point we should've added the Scroll behavior?

- Was it when the component was created [here](https://github.com/Expensify/App/blame/c928bfd65e56028d771a299d36d0362413778c42/src/components/DistanceRequest.js)
- or [this PR](https://github.com/Expensify/App/pull/26610), where we added multiple waypoint handling for smaller screen.

I also don't think we need any regression steps here.

**Comment by CortneyOfstad** [comment] 2023-09-18 15:15
@hayata-suenaga does that ^^^ sound good to you?

**Comment by CortneyOfstad** [comment] 2023-09-20 12:56
Bump @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2023-09-21 08:01
ah sorry I missed this one.

@mananjadhav and @ntdiary both reviewed the PR. They both should get some amount of payments.

**Comment by mananjadhav** [comment] 2023-09-21 09:20
@hayata-suenaga @CortneyOfstad Can you please update the payment summary so that I can raise a payment request.

**Comment by mananjadhav** [comment] 2023-09-21 17:55
Thanks @ntdiary. @CortneyOfstad Can you please update the payment summary here?

**Comment by hayata-suenaga** [comment] 2023-09-22 01:31
no I don't think we have to think that PR? as a regression

**Comment by mananjadhav** [comment] 2023-09-24 15:01
Thanks for confirming @hayata-suenaga.

@CortneyOfstad considering this was assigned and merged within 3 days this is eligible for the speed bonus.

That being said, I think the payout summary would be:

@allroundexperts - 750$
@ntdiary  - 500$  (full speed bonus to them as they reviewed the PR)
@mananjadhav - 250$

**Comment by hayata-suenaga** [comment] 2023-09-27 03:16
discussing the payment prices internally. thank you for your patience everyone 🙇

**Comment by CortneyOfstad** [comment] 2023-09-27 15:39
To confirm @mananjadhav, the amounts you put include the bonuses, correct? Or does a bonus need to be added to the total you listed? Thanks!

**Comment by mananjadhav** [comment] 2023-09-27 15:47
Yes @CortneyOfstad it includes the bonus.

**Comment by CortneyOfstad** [comment] 2023-09-27 19:32
Thanks!

@mananjadhav @ntdiary and @allroundexperts — I've sent job offers to each of you in Upwork. Please accept them as soon as you can so I can get those paid out. Thanks for your patience with this, and always – if you have any questions, just let me know!

**Comment by CortneyOfstad** [comment] 2023-09-27 19:35
No worries! I've withdrawn the offer in Upwork! Feel free to make the request in the app, and let me know if any additional info is needed on my part to get that paid!

**Comment by CortneyOfstad** [comment] 2023-09-29 11:22
@ntdiary Contract has been paid, so you should be all set!

@mananjadhav It shows that the proposal in Upwork is still waiting for you to accept — please let me know as soon as you complete this. Thank you!

**Comment by mananjadhav** [comment] 2023-10-02 14:41
@CortneyOfstad I will raise the request on NewDot. No upwork needed.

**Comment by CortneyOfstad** [comment] 2023-10-03 15:29
@mananjadhav Sounds good!

The payment breakdown is shared below:

@allroundexperts - 750$ — TO BE PAID IN NEWDOT
@ntdiary - 500$ (they reviewed the PR) — ALREADY PAID IN UPWORK
@mananjadhav - 250$ — TO BE PAID IN NEWDOT

**Comment by CortneyOfstad** [comment] 2023-10-03 15:30
@mananjadhav @allroundexperts once you are both paid in NewDot, please let me know here so I can then close this out. Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-05 13:15
$750 payment approved for @allroundexperts based on BZ summary.

**Closed** 2023-10-05 17:26 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:59
$250 payment approved for @mananjadhav based on BZ summary.
