### ISSUE TITLE
[HOLD for payment 2024-03-11] Distance - App refreshes when hitting Enter on empty waypoint editor

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36363] opened 2024-02-12 19:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Distance.
3. Click Start.
4. Hit Enter on keyboard.
Note that the page refreshes.

## Expected Result:
App returns to the distance request page.

## Actual Result:
App refreshes.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1f953281-2ab1-422e-a408-6b4f2c8e11f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c78c122e47f0026b</li>
        <li>Upwork Job ID: 1757134919273578496</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-12 19:47
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by blimpich** [comment] 2024-02-12 20:06
Not a blocker.

**Comment by paultsimura** [comment] 2024-02-12 20:30
This looks like a regression from https://github.com/Expensify/App/pull/34471 - it's not only on empty inputs but on non-empty ones when offline.
cc: @shubham1206agra @cubuspl42

**Comment by zoilorys** [comment] 2024-02-13 03:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 App refreshes when hitting Enter in waypoint editor while Address input is focused, it may be not empty and it will still reload the app. 

### What is the root cause of that problem?

After investigating the code, I found out that the issue was caused by the fact that pressing Enter while Address input is focused was triggering browser submit on the parent form element, instead of triggering programmatic submit. And since there is no action specified on the form element, it triggers submit on current route. This can be easily checked by adding `submit` event listener via console in browser. After analysing PR attached to the issue as potential cause of regression, I noticed that one of the changes in the PR was replacement of FormSubmit component, consequent removal of the component with FormElement component. Web code for FormSubmit contained `evt.preventDefault()` for this event and were removed in that PR.

### What changes do you think we should make in order to solve the problem?

In order to solve this issue you need to restore FormSubmit component and replace FormElement component in FormWrapper component with it and add onSubmit handler to it.

### What alternative solutions did you explore? (Optional)

Before discovering that the regression was caused by replacement of FormSubmit component with FormElement, I did alternative solution, where I just added `submit` event listener on the form reference to `preventDefault()` it. Since this code is present only in desktop code, this has no effect on mobile builds.

**Comment by zoilorys** [comment] 2024-02-13 03:25
Contributor details
Your Expensify account email: zoilorys+1@gmail.com
Upwork Profile Link:  https://www.upwork.com/freelancers/~0118575350e02b8b5e

**Comment by cubuspl42** [comment] 2024-02-14 09:20
PR https://github.com/Expensify/App/pull/36401 is in review

**Comment by blimpich** [comment] 2024-02-14 20:52
Ugh, I am terrible at using these dang labels. This is a regression so I shouldn't have marked it as external and needing help to begin with. No bug zero member is assigned here so this should just be handled as part of the original issue [here](https://github.com/Expensify/App/issues/31433).

**Comment by cubuspl42** [comment] 2024-03-05 09:49
No payment for me, we handled this as a regression

**Comment by abekkala** [comment] 2024-03-11 20:04
Hi @blimpich based on this comment: 
<img width="772" alt="Screenshot 2024-03-11 at 3 03 44 PM" src="https://github.com/Expensify/App/assets/11966460/e2042d4e-696f-4543-b786-72cadbc53077">

Does this particular issue need payment? It seems like payments are being handed via https://github.com/Expensify/App/issues/31433 correct? 

can this one just be closed? or do I need to even be assigned?

**Comment by blimpich** [comment] 2024-03-11 20:29
👍 Correct yes this one can just be closed. I'll close it now.

**Closed by blimpich** 2024-03-11 20:29 UTC
Labels: External, Engineering, Daily, Awaiting Payment
