### ISSUE TITLE
[$500] [LOW] Tags: Recently selected tag not displayed in recents list after editing an IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35506] opened 2024-01-31 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
User is employee of Collect workspace
Steps:
1. Employee navigate to Workspace chat
2. Go to +> Request money> Manual> Select tag 1> Complete the flow
3. Navigate to created IOU> Edit tag> Select tag 2> Save
4. Navigate to workspace chat
5. Go to +> Request money> Manual> Tag

## Expected Result:
Tag 2 should be present in recent tags list

## Actual Result:
Tag 2 is not present in recent tags lis

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/58abade8-e9fe-4c88-8b55-0092ce41af45

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ee0fe0e10710c59</li>
        <li>Upwork Job ID: 1752771933542309888</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-31 19:13
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by FitseTLT** [comment] 2024-01-31 19:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tag is not displayed in recents list when change it on created IOU

### What is the root cause of that problem?
Currently we are only updating `POLICY_RECENTLY_USED_TAGS` only on request creation flow
### What changes do you think we should make in order to solve the problem?

We should update `POLICY_RECENTLY_USED_TAGS` on edit of tag too.
### What alternative solutions did you explore? (Optional)

**Comment by vishrutagarwal97** [comment] 2024-01-31 20:24
Can someone help me to understand that how to make Collect Workspace ?

**Comment by greg-schroeder** [comment] 2024-01-31 21:50
Hmm, is this the behavior for categories that a category selected via edit is added to Recents? I'm not sure if that actually is the expected behavior

**Comment by greg-schroeder** [comment] 2024-01-31 21:52
I suppose that makes sense though, it _was_ actually used for the expense in the end. I'll add it to the project board, low prio though

**Comment by vishrutagarwal97** [comment] 2024-01-31 21:54
how to make a collect workspace? and also how to connect to OD? Any articles or place where I can refer and do it?

**Comment by DylanDylann** [comment] 2024-02-01 05:57
I think we should hold this issue until https://github.com/Expensify/App/issues/34612 is done

**Comment by trjExpensify** [comment] 2024-02-02 10:21
>I think we should hold this issue until https://github.com/Expensify/App/issues/34612 is done

It probably makes sense @DylanDylann, but mind including your reasoning when making a suggestion to put something on hold? Thanks!

**Comment by DylanDylann** [comment] 2024-02-02 12:17
In https://github.com/Expensify/App/issues/34612, we will migrate to use IOURequestStepTags for all Tag pages so I think the logic update recant tag will be updated for all flows

**Comment by trjExpensify** [comment] 2024-02-02 12:40
Thanks, helpful. Popping it on hold :)

**Comment by trjExpensify** [comment] 2024-02-12 15:23
@DylanDylann, looks like the PR associated with https://github.com/Expensify/App/issues/34612 was deployed to prod, right? Is that it or is there more to do?

**Comment by DylanDylann** [comment] 2024-02-14 17:46
Will check on Feb 15

**Comment by DylanDylann** [comment] 2024-02-15 05:18
Still can reproduce


https://github.com/Expensify/App/assets/141406735/72c606af-59d8-4e8c-9229-4abab40439e5

The RCA is that `OpenDraftWorkspaceRequest` API return wrong data 

<img width="470" alt="Screenshot 2024-02-15 at 12 18 39" src="https://github.com/Expensify/App/assets/141406735/a5a76a3a-f535-4576-b105-aff06a185db5">

After turning off the Internet, everything works well in all flows (create/edit request money, split bill). So I think it is a BE bug.


cc @mollfpr

**Comment by trjExpensify** [comment] 2024-02-21 00:59
Okay cool, I'll take this off-hold. @amyevans over to you then if this is BE related, I guess!

**Comment by amyevans** [comment] 2024-02-23 22:46
PRs up: https://github.com/Expensify/Auth/pull/10019, https://github.com/Expensify/Web-Expensify/pull/41005. Also just a heads up I'll be OOO next week!

**Comment by amyevans** [comment] 2024-03-06 16:47
Everything has deployed, closing!

**Closed by amyevans** 2024-03-06 16:47 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
