### ISSUE TITLE
[$500] Android - LHN - 1:1 Conversation displays as "Hidden" in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32736] opened 2023-12-08 18:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: user signed in with google account B
1. Write a few messages to account A
2. Sign Out
3. Open email from account A and reply to the new messages notification with any message
4. Sign In back to google account B

## Expected Result:
1:1 Conversation should be properly displayed in LHN

## Actual Result:
1:1 Conversation displays as "Hidden" in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/05243964-829e-4734-9922-e2a643d2a238

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e87f3881833cf634</li>
        <li>Upwork Job ID: 1733190088431796224</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by abeebridwan** [comment] 2023-12-10 00:21
@lanitochka17 
isn't this a backend issue?

**Comment by Victor-Nyagudi** [comment] 2023-12-11 08:18
I can't reproduce this. The other user's display name always shows up for me after they reply via email even after signing out then signing in again.

Can you still reproduce, @lanitochka17?

**Comment by michaelhaxhiu** [comment] 2023-12-15 17:06
This feels really small/specific and I don't see much value in fixing. Thanks for reporting but I'm closing.

**Closed by michaelhaxhiu** 2023-12-15 17:06 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
