### ISSUE TITLE
Web - App crashes after opening image sent by Concierge

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23453] opened 2023-07-23 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request a test image from Concierge (or send yourself one if you’re an internal employee)
2. Open the image in your chat with Concierge
3. Observe the app crashes

## Expected Result:
 The app doesn’t crash initially, it should if you close the attachment and re-open it again.

## Actual Result:
 App crashes after opening image sent by Concierge

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
n/a
**Expensify/Expensify Issue URL:**
**Issue reported by:** @jasperhuangg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689974078303009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2023-07-25 15:10
I can't reproduce this at all. I think we should close this!

**Closed by zanyrenney** 2023-07-25 15:10 UTC
Labels: Daily, Needs Reproduction, Bug
