### ISSUE TITLE
Unable to request money after settling existing ious

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#18718] opened 2023-05-10 15:59 UTC
cc @mountiny @luacmartins 

### Problem

Some IOURequests are failing. This is a new regression. 

You need to settle a few requests before the bug occurs. It might also be related to workspaces. In my case it is happenening to the workspace admin. 

- As userA, Request money
- As userB, pay it
- As userB, Request money
- As userA, pay it
- As userA, request money
- At some point we start. reusing the iouReportID which is a major regression. Theory is listed below
  

![Screenshot 2023-05-10 at 16 53 50](https://github.com/Expensify/App/assets/10736861/52d1f01b-88d3-4db7-bfd9-237bed9921d8)

This appears to be occurring because we no longer clear the `chatReport.iouReportID` property when an IOU is paid. Because of this,[ this line](https://github.com/Expensify/App/blob/4e13073505205805c24cf52efb9449870fe8c400/src/libs/actions/IOU.js#L76) is reusing an iouReportID instead of generating a new one optimistically. 

![Screenshot 2023-05-10 at 16 51 38 (2)](https://github.com/Expensify/App/assets/10736861/63bc56c4-df22-4261-8cae-d3b4e0a38173)

![Screenshot 2023-05-10 at 17 04 25](https://github.com/Expensify/App/assets/10736861/35210fa6-54e5-4ca6-bffa-930ed4296638)

### Solution

Figure out why we aren't clearing the `iouReport.iouReportID`, or update the mentioned logic so that we don't pass OLD iouReportIDs to the requestMoney API. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b510aa28fd9747e</li>
        <li>Upwork Job ID: 1656328070402617344</li>
        <li>Last Price Increase: 2023-05-10</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-05-10 16:15
This might be related to missing optimistic data being persisted to Onyx.

**Comment by trjExpensify** [comment] 2023-05-10 20:08
Asked @roryabraham in the [slack thread](https://expensify.slack.com/archives/C02HWMSMZEC/p1683735619136279) if he can take a look at it, as he worked on this optimistic stuff recently.

**Comment by roryabraham** [comment] 2023-05-10 21:43
Let me see what I can find out

**Comment by roryabraham** [comment] 2023-05-10 21:50
I'm so far unable to reproduce this while using the `Settle up elsewhere` payment method. Going to try provisioning bank accounts and see if it's related to the `PayWithExpensify` flow

**Comment by roryabraham** [comment] 2023-05-10 22:02
Ok, was able to reproduce using the `PayWithExpensify` flow:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/47436092/e3ece3c5-18b4-452e-9e17-0a9834fb0aa4">

Here's the failed IOU reportAction:

<img width="623" alt="image" src="https://github.com/Expensify/App/assets/47436092/1f0aa420-1ff3-4f0b-8906-0f2b1cf47995">

**Comment by roryabraham** [comment] 2023-05-10 22:04
Maybe a red herring, but AFAICT this is the only IOU `reportAction` where `originalMessage.IOUReportID` is a string instead of a number. Also, I see that @Julesssss is correct that it's the only one that re-used an existing `IOUReportID`.

**Comment by roryabraham** [comment] 2023-05-10 22:05
So I think it's probable that this is related to the `PayMoneyRequest` flows somewhere.

**Comment by roryabraham** [comment] 2023-05-10 22:25
Documenting my testing/investigation:

1. I have two accounts A and C, both with bank accounts added, and wallets upgraded to Gold. These accounts had never chatted before.
1. A uses global create to request money from C. Looking at the IOUReportAction on their newly created chat report:

    <img width="1243" alt="image" src="https://github.com/Expensify/App/assets/47436092/8bb93d3f-fc71-4c70-bfd5-d2592594b587">

    Then also at the IOU report:
    
    <img width="1244" alt="image" src="https://github.com/Expensify/App/assets/47436092/4c2c862d-ba14-4eb6-aaf3-f35985b66e0e">

1. Then, as C, I paid the IOU report via my Expensify wallet:

    There's a new IOU pay action:
    
    <img width="598" alt="image" src="https://github.com/Expensify/App/assets/47436092/2ef60389-e10e-4714-a3b2-631992f4f28c">
    
    As user A, I see the same pay action:
    
    <img width="641" alt="image" src="https://github.com/Expensify/App/assets/47436092/b341807c-21a1-415b-97cb-18e665f835ed">

    The IOU report is MANUALREIMBURSED:
    
    <img width="1243" alt="image" src="https://github.com/Expensify/App/assets/47436092/4d29ebbe-f253-42bd-9aba-886a2885c98a">
    
    User A sees the same thing:
    
    <img width="659" alt="image" src="https://github.com/Expensify/App/assets/47436092/44dedc2e-eb91-47ae-a2be-a7468cfe3571">
    
    I do see a stacktrace in server logs, not sure if these are a red herring:
    
    ```
    2023-05-10T22:14:37.363137+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] StackTrace start
    2023-05-10T22:14:37.363141+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] 0/4. file '/vagrant/Web-Expensify/lib/Push/API.php' function 'traceFunctionCall' line '253'
    2023-05-10T22:14:37.363145+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] 1/4. file '/vagrant/Web-Expensify/lib/Push/API.php' function 'send' line '159'
    2023-05-10T22:14:37.363149+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] 2/4. file '/vagrant/Web-Expensify/lib/ReportUtils.php' function 'sendToUserChannelByAccountID' line '1990'
    2023-05-10T22:14:37.363156+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] 3/4. file '/vagrant/Web-Expensify/lib/ReportAPI.php' function 'notifyParticipants' line '4004'
    2023-05-10T22:14:37.363160+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] 4/4. file '/vagrant/Web-Expensify/api.php' function 'payWithWallet' line '2866'
    2023-05-10T22:14:37.363164+00:00 expensidev2004 php-fpm: Wtdoxt /api.php rory+c@gmail.com !ecash1.3.12-1! ?api? [info] [trace] StackTrace end
    ```
    
1.

**Comment by roryabraham** [comment] 2023-05-11 01:46
Opened a PR to fix this issue: https://github.com/Expensify/Web-Expensify/pull/37386

**Comment by roryabraham** [comment] 2023-05-11 18:40
Thanks @Julesssss for helping take the PR over the finish line here. It was a back-end fix so no C+ payment here. Closing this out.

**Closed by roryabraham** 2023-05-11 18:40 UTC
Labels: Engineering, Improvement, Hourly, Internal

**Comment by trjExpensify** [comment] 2023-05-11 21:36
Nice one, guys!
