### ISSUE TITLE
Task - Assignee list opens after some delay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33282] opened 2023-12-19 12:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.14-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Click + > Assign task.
3. Create a task with no assignee.
4. Open task report.
5. Click Assignee.

## Expected Result:
Assignee list opens without delay.

## Actual Result:
Assignee list opens after some delay.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d5425c5b-6564-464c-90ba-e6b85b4f392d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2023-12-19 14:13
It seems to be working just fine for me

**Comment by pecanoro** [comment] 2023-12-19 14:14
hmm, maybe there is a super small delay now that you mentioned

**Comment by pecanoro** [comment] 2023-12-19 14:15
Either way, not a deploy blocker since functionality is still intact, it's just a one second delay (but we should still fix it if something is broken).

**Comment by pecanoro** [comment] 2023-12-19 14:16
Ohh the delay is much worse in my expensify account comparing to my expensifail one

**Comment by pecanoro** [comment] 2023-12-19 14:19
Bringing back the label for the blocker until I identify where the problem is coming from

**Comment by pecanoro** [comment] 2023-12-19 14:25
I think I found the PR that caused it but I would need to test it: https://github.com/Expensify/App/pull/32962

**Comment by s77rt** [comment] 2023-12-19 17:26
@TMisiukiewicz This effect https://github.com/callstack-internal/Expensify-App/blob/aa1d87caddb6831061f3750bd78f77b42603e5e3/src/pages/tasks/TaskAssigneeSelectorModal.js#L121-L123 run more than it should (3 instead of 1) due to the dependency on `updateOptions`. The PR is reverted so let's not remove the debounce function on this page (or prevent the effect from running this many times)

**Comment by pecanoro** [comment] 2023-12-19 20:14
PR was reverted so we can close this one.

**Closed by pecanoro** 2023-12-19 20:14 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
