### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] Android native - Default Scrollbar is visible when scrolling in a chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27931] opened 2023-09-21 10:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Scroll the page up and down

## Expected Result:
Open any report in LHN, a white line must not appear on left side while scrolling the page up and down.

## Actual Result:
Open any report in LHN, User can see a white line appears on left side while scrolling the page up and down.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/23b95552-34b1-43eb-a1cb-ac385b949ab2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7fb1a538e34bc1d</li>
        <li>Upwork Job ID: 1705059508445011968</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 26938079</li>
<li>situchan | Contributor | 26938083</li>
<li>bernhardoj | Contributor | 27130414</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-21 14:07
I can see this issue on production as well

**Comment by cristipaval** [comment] 2023-09-21 15:18
@s-alves10 This is reproducible to me with the latest Staging version but it isn't reproducible with the latest production (1.3.69-2). Could you please check what is your production version where you can reproduce?

**Comment by cristipaval** [comment] 2023-09-21 17:14
@hurali97 Could you please a look at this one? 
I lean more towards fixing this instead of reverting [the PR](https://github.com/Expensify/App/pull/27236) that caused this regression. If we can't fix it before the next deploy, I'd also remove the DeployBlockerCash label since this is a minor style issue that occurs on Android native devices only 
cc @mountiny

**Comment by hurali97** [comment] 2023-09-21 18:03
@cristipaval This is not related to the mentioned PR. The hover effect is handled explicitly in the platform specific files for web and desktop.

**Comment by mountiny** [comment] 2023-09-22 03:20
I dont think this has to be a deploy blocker, we can just let this be fixed through the normal process

**Comment by mountiny** [comment] 2023-09-22 03:21
@thienlnam updated but if you think this should be a blocker, feel free to handle it that way

**Comment by thienlnam** [comment] 2023-09-22 04:08
Yeah agreed, looks pretty minor but we should fix

**Comment by abdel-h66** [comment] 2023-09-24 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scroll bar appears on the left on Android

### What is the root cause of that problem?

As opssoed to the LHN for example we are not setting `showsVerticalScrollIndicator={false}` to the FlatList. 

### What changes do you think we should make in order to solve the problem?
Adding the prop `showsVerticalScrollIndicator` and setting it to `false` fixes the issue. 

https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/home/report/ReportActionsList.js#L324

### What alternative solutions did you explore? (Optional)

N/A

**Comment by cristipaval** [comment] 2023-09-24 21:13
Thank you all for the input. SO this is on @abdulrahuman5196 now, he'll review the proposals.

**Comment by lschurr** [comment] 2023-09-27 06:51
Bump @abdulrahuman5196

**Comment by lschurr** [comment] 2023-09-29 08:53
Asking for a volunteer to reassign - https://expensify.slack.com/archives/C02NK2DQWUX/p1695977590341369

**Comment by abdulrahuman5196** [comment] 2023-09-29 08:53
I am starting to review

**Comment by lschurr** [comment] 2023-09-29 08:54
Thanks @situchan!

**Comment by abdulrahuman5196** [comment] 2023-09-29 09:32
@bernhardoj Thank you for the detailed proposal here https://github.com/Expensify/App/issues/27931#issuecomment-1736816305. I did play around the suggestions and the issue was fixed(scroll bar was coming on the right side).

But I am a bit skeptical about removing the patch. Not sure if we can remove it totally tough since I found the related issue still open - https://github.com/facebook/react-native/issues/35350

Tagging the original owner of the change @hannojg to confirm if we can proceed with the proposal.

**Comment by abdulrahuman5196** [comment] 2023-10-02 09:15
Not overdue melvin. People should be just back from weekend. Anyways another gentle ping @hannojg

**Comment by cristipaval** [comment] 2023-10-04 11:40
friendly bump @hannojg

**Comment by lschurr** [comment] 2023-10-06 16:10
Hi @abdulrahuman5196 @cristipaval - are we still waiting on @hannojg here?

**Comment by abdulrahuman5196** [comment] 2023-10-06 16:11
@lschurr  yes

**Comment by lschurr** [comment] 2023-10-09 16:53
Bumped here: https://expensify.slack.com/archives/C01GTK53T8Q/p1696614435952189

**Comment by hannojg** [comment] 2023-10-09 18:15
Hey, the performance fix is already part of react native, so any patch that was originally created can be removed!
So I totally agree here with @bernhardoj proposal 😊

**Comment by abdulrahuman5196** [comment] 2023-10-10 14:26
Thank you for the confirmation @hannojg 

@bernhardoj 's proposal here https://github.com/Expensify/App/issues/27931#issuecomment-1736816305 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by lschurr** [comment] 2023-10-23 15:52
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: @bernhardoj $750
- Contributor+: @abdulrahuman5196 $750

**Comment by lschurr** [comment] 2023-10-23 15:55
Payments have been made in Upwork.

**Comment by abdulrahuman5196** [comment] 2023-10-23 18:23
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression per say, since we had a patch and the patch is not working after the update.

>Determine if we should create a regression test for this bug.

Yes. If not already present.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Open any chat with enough messages to scroll
2) Verify the scrollbar is on the right side of the screen
3) Verify the chat list is inverted, i.e. you need to scroll from bottom to top

@lschurr

**Comment by lschurr** [comment] 2023-10-23 20:34
Great! This is complete.

**Closed by lschurr** 2023-10-23 20:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
