### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Update all enable/disable workspace editor menu items to use more appropriate icons.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51361] opened 2024-10-23 20:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.52-5
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dannymcclain 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1729696426720769

## Action Performed:
1. Go to staging.new.expensify.com
2. Settings > Workspace
3. Enable and disable distance rates, categories, tags, taxes, etc in the workspace editor
## Expected Result:
Update all of these options to use our checkmark icon for enabling and our close icon for disabling
## Actual Result:
For enabling and disabling distance rates, categories, tags, taxes, etc in the workspace editor, we use the document slash and document icons
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

![Full Screen #16](https://github.com/user-attachments/assets/27c541ca-a8e5-4c2e-804e-809e403842b0)
  

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021850952147214906851</li>
        <li>Upwork Job ID: 1850952147214906851</li>
        <li>Last Price Increase: 2024-10-28</li>
<li>Automatic offers: </li>
<ul>
<li>klajdipaja | Contributor | 104664755</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by jayeshmangwani** [comment] 2024-10-23 20:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We need to update all enabled/disabled workspace editor menu items to use more appropriate icons.

### What is the root cause of that problem?
Its just a UI Enhancement

### What changes do you think we should make in order to solve the problem?
This is a straightforward change, and if we decide to address it externally, here’s my proposal:

On the pages listed below, we're currently using `Expensicons.Document` and `Expensicons.DocumentSlash`. These should be replaced with `Expensicons.Checkmark` and `Expensicons.Close` respectively.


1. **WorkspaceCategoriesPage**
2. **PolicyDistanceRatesPage**
3. **ReportFieldsListValuesPage**
4. **WorkspaceTagsPage**
5. **WorkspaceViewTagsPage**
6. **WorkspaceTaxesPage**

### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2024-10-28 17:25
Nice, good thinking here!

**Comment by jayeshmangwani** [comment] 2024-10-28 17:45
Hey @klajdipaja ! I submitted a proposal before being assigned here as C+. Issue is still open for proposals, so feel free to add one if you have any ideas. I'll Hide my comment

**Comment by klajdipaja** [comment] 2024-10-28 17:58
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
We need to update all enabled/disabled workspace editor menu items to use more appropriate icons.

### What is the root cause of that problem?
It's just a UI Enhancement

### What changes do you think we should make in order to solve the problem?
This is a straightforward change, and if we decide to address it externally, here’s my proposal:

On the pages listed below, we're currently using `Expensicons.Document` and `Expensicons.DocumentSlash`. These should be replaced with `Expensicons.Checkmark` and `Expensicons.Close` respectively.

`WorkspaceCategoriesPage`
`PolicyDistanceRatesPage`
`ReportFieldsListValuesPage`
`WorkspaceTagsPage`
`WorkspaceViewTagsPage`
`WorkspaceTaxesPage`

### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2024-10-28 18:07
It's a straightforward icons update. We can assign this issue to @klajdipaja with the selected proposal https://github.com/Expensify/App/issues/51361#issuecomment-2442265355.

🎀 👀 🎀 C+ reviewed

**Comment by zanyrenney** [comment] 2024-10-30 15:46
Assigning @klajdipaja

**Comment by jayeshmangwani** [comment] 2024-11-11 19:32
@zanyrenney, this issue is an improvement, so IMO the checklist isn't needed. We've just updated the icons here.

**Comment by jayeshmangwani** [comment] 2024-11-14 06:19
@zanyrenney , I’ve completed the [checklist](https://github.com/Expensify/App/issues/51361#issuecomment-2475504043). Thanks!

**Comment by zanyrenney** [comment] 2024-11-18 15:23
### Payment summary 
@klajdipaja requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/104664755) (Contributor) - paid $250 via Upwork
@jayeshmangwani requires payment through NewDot Manual Requests -due $250 via ND requests

**Closed by zanyrenney** 2024-11-18 15:23 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-26 14:26
[arrettmknight](https://github.com/garrettmknight) commented [18 minutes ago](https://github.com/Expensify/App/issues/51355#issuecomment-2500898415)
$250 approved for @jayeshmangwani
