### ISSUE TITLE
[$500] [Dev] - Getting a console error when add message page is reloaded

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29039] opened 2023-10-06 20:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. navigate to workspace list, select any workspace.
2. go to members page, invite any user
3. click next, and reload page
## Expected Result: 
no console error
## Actual Result: 
console error appears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Happening in Dev main latest
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-10-07 at 1 03 22 AM](https://github.com/Expensify/App/assets/38435837/67b88b73-fc8b-4124-82ad-be77294789ac)

![Screenshot 2023-10-07 at 12 55 08 AM](https://github.com/Expensify/App/assets/38435837/bd21845c-a256-4726-acfd-14519df2277a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696620833746119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f681baa53bf002b</li>
        <li>Upwork Job ID: 1710396790871732224</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by maxconnectAbhi** [comment] 2023-10-07 06:11
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Getting a console error when add message page is reloaded

## What is the root cause of that problem?
testID prop is required for `<ScreenWrapper/>` component but its value get undefined i.e
`WorkspaceInviteMessagePage.displayName`

## What changes do you think we should make in order to solve the problem?
We need to define the value in testID 

```
WorkspaceInviteMessagePage.propTypes = propTypes;
WorkspaceInviteMessagePage.defaultProps = defaultProps;
WorkspaceInviteMessagePage.displayName="WorkspaceInviteMessagePage"
```

## What alternative solutions did you explore? (Optional)
I also found that displayName is not defined in many screens, which may cause same issue. Such as

AddersonalBankAccountPage
SearchPage 
ShareCodePage 
ReimbursementAccountPage
RequestorOnfidoStep
ValidationStep
ContactMethodDetailsPage

**Comment by maxconnectAbhi** [comment] 2023-10-07 06:13
@Santhosh-Sellavel
If I got the proposal, I will fix all other screens as well   🙂

**Comment by situchan** [comment] 2023-10-08 07:21
Dupe of #28334

**Comment by Santhosh-Sellavel** [comment] 2023-10-10 17:02
Yes, it's a dupe, @sobitneupane please verify this one as well!

**Comment by sobitneupane** [comment] 2023-10-11 04:37
> Yes, it's a dupe, @sobitneupane please verify this one as well!

Sure @Santhosh-Sellavel. We can close this issue.

**Comment by Santhosh-Sellavel** [comment] 2023-10-16 16:19
Not overdue

**Comment by situchan** [comment] 2023-10-27 16:03
The bug is fixed. 🎀 👀 🎀 for engineer to close this issue

**Comment by puneetlath** [comment] 2023-10-30 15:02
Closing!

**Closed by puneetlath** 2023-10-30 15:02 UTC
Labels: External, Daily, Help Wanted, Overdue
