### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] Web - RHN briefly displayed with the sign-in modal before closing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28610] opened 2023-10-02 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the "New room" section.
2. Enter a name for the room and select the workspace.
3. Set the visibility of the room to "Public"
4. Click on the "Create room" button.
5. Go to "Share code" > "Copy URL to clipboard"
6. Open another browser where you are not signed in.
7. Paste the copied URL.
8. Open the room details.
9. Click on "Settings" or "Private notes"
10. Observe that the RHN briefly shows with the sign-in modal before closing.

## Expected Result:
RHN should close properly without displaying with sign-in modal

## Actual Result:
 RHN is displayed for a second with the sign-in modal before closing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.75.8
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68d83e0a-152e-4c3e-ac6c-c1b9a34c8bac

https://github.com/Expensify/App/assets/93399543/59fa620c-e928-4735-af76-e07275e0a24c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694979234773059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5970e379d770333</li>
        <li>Upwork Job ID: 1708821330818027520</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27102453</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-10-02 14:02
@NicMendonca Do we need to show Settings or Private Notes if we have to close them for anonymous users?

**Comment by lcsvcn** [comment] 2023-10-02 15:27
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Web - RHN briefly displayed with the sign-in modal before closing
## What is the root cause of that problem?
The issue arises from the fact the SignInModal is being show even before the hideContextMenu finishes hiding the menu.

## What changes do you think we should make in order to solve the problem?
We can use the onHideCallback to call the Session.signOutAndRedirectToSignIn().


Currently, we have this:
https://github.com/Expensify/App/blob/5c9171a4be1662b41b25957b23df8df6482972b5/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L99-L109


## What alternative solutions did you explore? (Optional)
N/A

**Comment by ayazalavi** [comment] 2023-10-03 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App redirects to sign in modal for anonymous user trying to view and access room menu items.

### What is the root cause of that problem?
The root cause exists because the MenuItem component checks if an action is allowed in the code below, which takes 'isAnonymousAction' as the second parameter. If 'isAnonymousAction' is false, the app redirects to the login page.

You can find the relevant code here:
- MenuItem.js: https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/components/MenuItem.js#L137-L148
- Session/index.js: https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/libs/actions/Session/index.js#L105-L108

Now, in the ReportDetailsPage, we have hardcoded 'isAnonymousAction' to false, which is being passed to the MenuItem component for the 'members,' 'settings,' 'private notes,' and 'leave room' menu items.

You can find the relevant code here:
- ReportDetailsPage.js (lines 91-100): https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L91-L100
- ReportDetailsPage.js (lines 104-112): https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L104-L112
- ReportDetailsPage.js (lines 117-124): https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L117-L124
- ReportDetailsPage.js (lines 128-134): https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L128-L134
- ReportDetailsPage.js https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L194-L203

This issue exists throughout the app where ever MenuItem component is being used.

### What changes do you think we should make in order to solve the problem?
We need to ensure that the 'isAnonymousAction' prop in the MenuItem rendering code checks if the user is anonymous instead of hardcoding the prop value from menuitems array.

https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L194-L203

https://github.com/Expensify/App/blob/a355bf8c9b22a348eb4f8e7d432e0fa0f56d0f59/src/pages/ReportDetailsPage.js#L75

Also hides the menu item if it is not accessible to anonymous users prior to rendering it.

Result:

https://github.com/Expensify/App/assets/767439/093dc472-be51-4aa9-8da1-2c660fae0427

### What alternative solutions did you explore? (Optional)
We need to ensure that the back button is functioning correctly since it's currently causing the app to crash. Additionally, we should review the usage of the menu item throughout the app and consider the needs of anonymous users. This way, we can develop a utility method to determine whether an action is accessible to anonymous users and use that method within the MenuItem component, eliminating the need for the 'isAnonymousAction' prop. For instance, if 'feature 1' is accessible to anonymous users, it should be displayed; otherwise, we can return 'null' within the MenuItem component code for anonymous users.

**Comment by ayazalavi** [comment] 2023-10-05 07:48
@allroundexperts any update about above proposals?

**Comment by NicMendonca** [comment] 2023-10-05 20:59
@allroundexperts proposals for you here!

**Comment by NicMendonca** [comment] 2023-10-20 20:25
@ayazalavi can you please apply to the job: https://www.upwork.com/jobs/~01f5970e379d770333

**Comment by ayazalavi** [comment] 2023-10-21 06:55
@ayazhussain79

**Comment by ayazhussain79** [comment] 2023-10-21 07:34
@NicMendonca applied on upwork
@ayazalavi thanks for reminding me

**Comment by JmillsExpensify** [comment] 2023-10-23 16:38
Can I please get a payment summary for this issue?

**Comment by NicMendonca** [comment] 2023-10-24 13:29
- reporter: @ayazhussain79 - $50
- contributor: @bernhardoj - $750
- c+: @allroundexperts - $750

**Comment by NicMendonca** [comment] 2023-10-24 13:33
@ayazhussain79 @bernhardoj - you've been paid via Upwork

@allroundexperts please don't forget to request payment via Expensify

Thanks!

**Closed** 2023-10-24 13:33 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-24 17:05
$750 payment approved for @allroundexperts based on BZ symmary.
