### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000]  Assign task show error when creating within a report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21361] opened 2023-06-22 22:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat with any user
2. Click + in compose
3. Assign task
4. Input the title
5. Next => Observe the error appearing: "There was an error assigning this task, please try another assignee."
## Expected Result: 
Error message doesn't appear
and there should not be an empty avatar in the task assignee view
## Actual Result: 
Observe the error appearing: "There was an error assigning this task, please try another assignee."

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e95a270c-fdc6-46d3-90af-2e51520a8334

<img width="960" alt="Screenshot (373)" src="https://github.com/Expensify/App/assets/43996225/357fac05-b88c-41c1-a7f5-4324ab0b6d1f">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687320876332399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152a7fadbf2438272</li>
        <li>Upwork Job ID: 1672104067929206784</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-23 04:47
Reproduced, cc @thienlnam in case you want to work on this one.

**Comment by thienlnam** [comment] 2023-06-23 16:53
I actually can't seem to reproduce this on main - it might have been resolved already

**Comment by thienlnam** [comment] 2023-06-23 21:52
Ah I see, these reproduction steps are inaccurate

It only happens when you try to assign a task within a report

**Comment by thienlnam** [comment] 2023-06-26 17:26
Hmm, when we create a task within a report - we don't want to automatically set an assignee. It should either be

Create a task
- Select an assignee, and by default it will share in the DM between you two

or 

Create a task within a report
- It will default share in the room, but will not set an assignee by default

**Comment by thienlnam** [comment] 2023-06-26 20:02
Can you also show the video verifying when the task is created with no assignee it doesn't show an empty avatar?

**Comment by thienlnam** [comment] 2023-06-26 23:51
Cool, looks good to me!

**Comment by sakluger** [comment] 2023-06-27 01:31
@namhihi237 could you please apply to the Upwork job when you have a chance? Thanks! https://www.upwork.com/jobs/~0152a7fadbf2438272

**Comment by sakluger** [comment] 2023-06-27 01:31
I've sent offers to @Victor-Nyagudi and @thesahindia.

**Comment by thienlnam** [comment] 2023-06-29 21:03
Hmm, my bad - I didn't see that conversation and assumed this was a bug on the original design. Going to comment there

**Comment by sakluger** [comment] 2023-07-01 00:23
Sorry, I'm not following. Do we need to change anything here on this issue?

**Comment by sakluger** [comment] 2023-07-07 22:35
@thesahindia could you please complete the BZ checklist when you have a chance? That way I can pay out on Monday. Thanks!

**Comment by thienlnam** [comment] 2023-07-07 23:55
> Sorry, I'm not following. Do we need to change anything here on this issue?

No, we're good to go - I added my thoughts on that original thread but what we ended up doing here was correct

**Comment by sakluger** [comment] 2023-07-10 18:43
Paid @Victor-Nyagudi and @namhihi237 (with efficiency bonus). Just waiting on the BZ checklist, then I can pay @thesahindia and close out the issue!

**Comment by sakluger** [comment] 2023-07-10 23:45
@thesahindia got it - I closed the contract in Upwork. I'll check back in tomorrow for the BZ checklist 👍

**Comment by sakluger** [comment] 2023-07-11 15:53
Hey @thesahindia checking in again since I'd love to close out this issue. Thanks!

**Comment by sakluger** [comment] 2023-07-11 21:02
Thank you!

**Comment by JmillsExpensify** [comment] 2023-09-22 08:49
@sakluger Do you mind providing a payment summary on this issue so that I can pay @thesahindia?

**Comment by sakluger** [comment] 2023-09-25 15:37
Sure thing @JmillsExpensify.

**Summarizing payouts for this issue:**

Bug reporter: @Victor-Nyagudi $250 (hired and paid via Upwork)
Contributor: @namhihi237 $1500 (hired and paid via Upwork)
Contributor+: @thesahindia $1500 (payable via Manual Request)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~0152a7fadbf2438272

**Comment by sakluger** [comment] 2023-09-28 06:49
@JmillsExpensify are we good to close this one out again, or do you want to leave it open until you've paid it out?

**Comment by sakluger** [comment] 2023-10-02 17:44
Okay I'm going to close this one again.

**Closed by sakluger** 2023-10-02 17:44 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:35
$1,500 payment approved for @thesahindia based on BZ summary.
