### ISSUE TITLE
[$1000] Web - Not Allowed sign when hovering through the reaction list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21354] opened 2023-06-22 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to chat with previous messages.
2. go to any message hover over the reaction list and notice that there is no 'Not Allowed' sign showing up.
3. Now click the message body and hover over the reaction list again. notice there is a 'Not Allowed' sign showing up.

## Expected Result:
No 'Not Allowed' sign showing up.

## Actual Result:
 The 'Not Allowed' sign showing up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8b161719-3799-4b19-81bf-705ea2dcb176

https://github.com/Expensify/App/assets/93399543/c684befc-ec75-4f6b-bbb2-17ca05a7d591

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687467815718419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e36cd61ebc57ae7</li>
        <li>Upwork Job ID: 1672048109219315712</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-06-22 23:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a message in the chat is clicked, its reaction modal starts triggering the "not allowed" cursor when the space between reactions is hovered.

### What is the root cause of that problem?

A recent change uncovered a bug in `PressableWithFeedback`.

`onPress` is not a required property, but it was treated like it was. If a `PressableWithFeedback` instance was pressed (clicked) but `onPressed` was `undefined`, an exception was thrown. Consequently, the logic to re-enable the component (meant for the case when `props.onPressed` returns a promise) wasn't fired and it was left in the disabled state.

A disabled pressable has the `not-allowed` cursor.

`ReportActionItem` isn't providing `onPress` to `PressableWithSecondaryInteraction` (which forwards it to `PressableWithFeedback`). `ReportActionItem`'s `PressableWithSecondaryInteraction` is an ancestor to the reaction picker, so the space between the reaction entries inherits the cursor style.

### What changes do you think we should make in order to solve the problem?

We should refactor the [`onPress` callback passed to `GenericPressable`](https://github.com/Expensify/App/blob/a6792a0e2e283904e76d4de65c62c60aa0888947/src/components/Pressable/PressableWithFeedback.js#L77) in `PressableWithFeedback` so it works correctly in all cases:
- when `props.onPress` is not provided (it's `undefined`)
- when `props.onPress` is provided and it's async (it returns a `Promise`)
- when `props.onPress` is provided and it's not async (it returns something else, presumably `undefined`)

A simple implementation that satisfies these requirements could look like this:

```js
onPress={(e) => {
    if (!props.onPress) return;

    const onPressResult = props.onPress(e);
    if (onPressResult instanceof Promise) {
        setDisabled(true);
        InteractionManager.runAfterInteractions(() => {
            onPressResult.finally(() => {
                setDisabled(props.disabled);
            });
        });
    }
}}
```

**Comment by jasperhuangg** [comment] 2023-06-23 01:05
Removing deploy blocker label since I don't think we need to block deploy on such a minor issue. It seems you can still react to comments so it doesn't actual break any existing behavior.

**Comment by situchan** [comment] 2023-06-23 04:40
I think this was already fixed in https://github.com/Expensify/App/pull/21341

**Comment by cubuspl42** [comment] 2023-06-23 07:00
@situchan
Oh, thanks for spotting that

I would argue that the bug I described in my root cause analysis is still there in some form. If `props.onPress` throws, the component would again lock itself in the disabled state. The implementation is also unnecessarily complex and bug-prone, firing `runAfterInteractions` for simple cases when `onPress` is not async.

**Comment by jasperhuangg** [comment] 2023-06-23 17:21
Hmmm after retesting I agree that it was fixed in that other PR. This is a pretty minor flow that doesn't affect behavior so I'm gonna close it out. Thanks for your understanding @cubuspl42

**Closed** 2023-06-23 17:21 UTC
Labels: External, Engineering, Daily
