### ISSUE TITLE
Two "Expensify" chats are visible in the LHN after logging from a public room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46099] opened 2024-07-24 10:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with a new Gmail account
3. Validate the account and log out
4. Open Chrome in incognito
5. Navigate to https://staging.new.expensify.com/r/2091104345528462
6. Click on the "Sign in" button at the bottom right corner
7. Log in with the created Gmail account

## Expected Result:
Only one of the chats should bi visible.

## Actual Result:
Two "Expensify" chats are visible in the LHN after logging from a public room.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2adab80e-e848-4533-b0ee-cac1ab377d63

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a90186f2c95b5379</li>
        <li>Upwork Job ID: 1816290368283248140</li>
        <li>Last Price Increase: 2024-07-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tgolen</details>

**Comment by izarutskaya** [comment] 2024-07-24 10:40
We think this issue might be related to the #collect project.

**Comment by RachCHopkins** [comment] 2024-07-25 01:52
I don't think I have access to replicate this, so I'm assuming that it's replicatable.

**Comment by raza-ak** [comment] 2024-07-26 09:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Two "Expensify" chats are visible in the LHN after logging from a public room
### What is the root cause of that problem?
We were filtered duplicate expensify chats and embedding last one in the final list.
### What changes do you think we should make in order to solve the problem?

`In src/libs/SidebarUtils.ts`
```
let systemChat: any = null;
    const filteredReports = reportsToDisplay.filter(report => {
        if (report.chatType === 'system') {
                systemChat = report;
            return false;
        }
        return true;
    });
    if (systemChat) {
        filteredReports.push(systemChat);
        reportsToDisplay = filteredReports;
    }
```
### What alternative solutions did you explore? (Optional)
**Result:**

https://github.com/user-attachments/assets/d78ae43f-e6e1-439c-83e7-96282ea13511

**Comment by raza-ak** [comment] 2024-07-26 09:51
Contributor details
Your Expensify account email: raza.aslam29@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cae2f7c8d5d16802

**Comment by s77rt** [comment] 2024-07-26 15:46
@raza-ak Your RCA is not clear. Can you explain why we have 2 chats in the first place?

**Comment by raza-ak** [comment] 2024-07-30 07:53
@s77rt 
## Proposal
[Updated](https://github.com/Expensify/App/issues/46099#issuecomment-2252377353)

**Comment by s77rt** [comment] 2024-07-30 15:49
@raza-ak Thanks for the update. This seems `Internal`.

🎀 👀 🎀 Internal
Please check the response of the `OpenApp` request, multiple `system` chats are returned
<img width="1315" alt="353369239-773255ad-0909-49fd-b152-f103f928bb59" src="https://github.com/user-attachments/assets/d1162b2b-1199-435a-bf80-2b16012112fb">

**Comment by tgolen** [comment] 2024-07-31 16:02
OK, I looked into this today with @NikkiWines and @marcochavezf and we think we found what caused this and we have a solution to fix this on the backend. I'm taking the issue internally and will take it from here.

**Comment by tgolen** [comment] 2024-08-01 15:56
# Daily Update
- I created an [Auth PR](https://github.com/Expensify/Auth/pull/11859) and it merged yesterday

### Next Steps
- Wait for it to deploy (which should happen today)
- @izarutskaya assist us in re-testing this to verify the issues is solved

#### ETA
- We should be able to wrap this up today, Aug 1.

**Comment by tgolen** [comment] 2024-08-02 13:21
# Daily Update
- The [Auth PR](https://github.com/Expensify/Auth/pull/11859) has been deployed to production

### Next Steps
- @izarutskaya Can you please verify if this issue is resolved now?

#### ETA
- Closed today, Aug 2

**Comment by tgolen** [comment] 2024-08-05 14:29
I tested this... and now, there are no system chats at all. I'm not sure if that's expected or not, but the duplicates are gone, so I will close this.

**Closed by tgolen** 2024-08-05 14:29 UTC
Labels: Reviewing, Engineering, Daily, Internal
