### ISSUE TITLE
[$250] Bank Account - User goes to 'Connect manually' flow after 'Start Over' offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51479] opened 2024-10-25 15:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open App, create/open workspace and start to add bank account in workspace
2. Exits in the middle of the flow (after page 'Company Information' or 'Personal Information')
3. Return to the flow again > Settings > Workspaces > Connect bank account
4. Go offline
5. Select Start Over on the page 'Almost done!'
6. User get page page 'You appear to be offline'
7. Go Online

## Expected Result:
The flow of adding bank Account is reset. User is on the start 'Connect bank account' page

## Actual Result:
The flow of adding Bank Account is reset. User goes to goes to 'Connect manually' flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/cbbcc5da-41d6-4359-9eac-5c8a2e3ed3a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021851291554750781233</li>
        <li>Upwork Job ID: 1851291554750781233</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 104897217</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by ranli** [comment] 2024-10-30 04:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User goes to 'Connect manually' flow after 'Start Over'. The description said this will happen when user go offline and then go back online. But during my reproduction, no matter user go offline then online or user stays online, when a user click the "Start Over" and select "Yes, Start Over", user always goes to 'Connect manually', not "Connect bank account" page

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/6cd5c645c4e3ad6e0fff934457d1c42a1b5b209e/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L20

When user clicks on "Yes, Start Over ", `resetFreePlanBankAccount` is called, but did not navigate user back to 'Connect bank account' page.

### What changes do you think we should make in order to solve the problem?
Add `Navigation.goBack();` after API.write call https://github.com/Expensify/App/blob/6cd5c645c4e3ad6e0fff934457d1c42a1b5b209e/src/libs/actions/ReimbursementAccount/resetFreePlanBankAccount.ts#L30


### What alternative solutions did you explore? (Optional)
N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2024-11-03 09:40
Reviewing on Monday

**Comment by DylanDylann** [comment] 2024-11-04 09:07
@bfitzexpensify It seems the video on OP already matched to the expected and I can't reproduce this issue. Could you please check again? Thanks

**Comment by mvtglobally** [comment] 2024-11-08 15:28
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2024-11-09 08:42
@koko57 Would you like to work on this issue?

**Comment by koko57** [comment] 2024-11-09 08:48
@DylanDylann yes, thanks! I'll be working on this step from the next week so I will take care of this issue too

**Comment by bfitzexpensify** [comment] 2024-11-14 13:47
Cool cool! I will close this out then, @mountiny let me know if it should be re-opened and treated separately, though.

**Comment by DylanDylann** [comment] 2024-12-01 03:30
@bfitzexpensify @koko57  I believe that we need to reopen this issue because https://github.com/Expensify/App/issues/51799 is closed without PR

**Comment by koko57** [comment] 2024-12-01 03:38
@DylanDylann I will check if the issue is still reproducible on  Monday- maybe it's not reproducible anymore like in case of 51799

**Comment by koko57** [comment] 2024-12-02 11:17
I'm not sure if I'm doing it right, but I can't reproduce it. May I ask the QA team to retest? cc @lanitochka17 @mountiny

**Comment by DylanDylann** [comment] 2024-12-02 17:45
@kavimuru can your team please retest this issue?

**Comment by mountiny** [comment] 2024-12-03 12:33
Asked

**Comment by mountiny** [comment] 2024-12-09 09:54
A confirmed this is not repro so I think we can close

**Closed by mountiny** 2024-12-09 09:54 UTC
Labels: External, Daily, Overdue, Bug
