### ISSUE TITLE
[Payment 2024-11-29] [Search v2.5] - Category field is still present after deleting all the categories

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52362] opened 2024-11-12 09:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/52102
**Email or phone of affected tester (no customers):** applausetester+290324@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with a new account.
3. Create a new workspace.
4. Go to workspace settings > More features.
5. Enable Tags.
6. Go to Tags and add some tags.
7. Go to Search > Filters.
8. Note that Category and Tag fields are present.
9. Go back to workspace settings.
10. Delete all categories and tags.
11. Go to Search > Filters.

## Expected Result:
Both Category and Tag fields will not be present because there are no categories and tags.

## Actual Result:
Category field is still present after deleting all the categories, while Tag field is not present which is expected.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b502db54-f355-431c-be27-f9f7ef16a0df

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by MariaHCD** [comment] 2024-11-12 11:20
Since this is a bug from https://github.com/Expensify/App/pull/52102 and we're still in the regression period, the original PR author will be handling the fix for this.

cc: @Kicu @fedirjh @luacmartins

**Comment by luacmartins** [comment] 2024-11-12 15:54
Yea, this is not a blocker. Assigning it to you @Kicu

**Comment by SzymczakJ** [comment] 2024-11-14 14:44
@Kicu asked me to take a look at it, I think that solution that @NJ-2020 proposed is good(also tested it) and we should let him open a PR with it 😄 
WDYT @luacmartins

**Comment by luacmartins** [comment] 2024-11-14 18:08
That works for me

**Comment by Kicu** [comment] 2024-11-15 09:19
FYI keep in mind that @sumo-slonik is also working on other filters misbehaving here: https://github.com/Expensify/App/pull/52462

**Comment by sumo-slonik** [comment] 2024-11-15 14:20
> FYI keep in mind that @sumo-slonik is also working on other filters misbehaving here: #52462

all related bugs for :
CategoryFilter
TagFilter
CardFilter
have been solved by this PR which was linked by Mateusz

**Comment by strepanier03** [comment] 2024-12-03 17:49
Working on this now, the "HOLD" in the title had it hidden from me yesterday and I didn't see it. Sorry for the delay.

**Comment by strepanier03** [comment] 2024-12-03 18:31
@NJ-2020 - Can you please share a link to your profile in Upwork? I'm unable to find it to send you an offer. Thanks!

**Comment by strepanier03** [comment] 2024-12-03 18:35
@Kicu - I think you're responsible for the [checklist](https://github.com/Expensify/App/issues/52362#issuecomment-2494688637), can you take care of that as well?

**Comment by strepanier03** [comment] 2024-12-04 23:36
Hmmm, I thought you were the reviewer here; sorry about that, @Kicu. This [comment](https://github.com/Expensify/App/issues/52362#issuecomment-2494688637) had me a bit turned around I think. I'll figure out who is responsible for it.

**Comment by strepanier03** [comment] 2024-12-04 23:36
Hmmm, looks like @Ollyws reviewed the PR.

**Comment by strepanier03** [comment] 2024-12-05 21:25
### Payment summary

- [ ] $250 - @NJ-2020 via Upwork ([offer](https://www.upwork.com/nx/wm/offer/105213683))
- [ ] $250 - @Ollyws via New Expensify manual offer

**Comment by strepanier03** [comment] 2024-12-05 21:27
updated payment summary above @Ollyws, feel free to request. @NJ-2020 I sent you the offer, I'll check it in a few hours to see if I can pay it out.

**Comment by strepanier03** [comment] 2024-12-06 18:53
I paid and closed the contract for @NJ-2020 and I see that @Ollyws has requested payment. 

Closing this now.

**Closed by strepanier03** 2024-12-06 18:53 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-12 11:42
$250 approved for @Ollyws
