### ISSUE TITLE
Dev: Web - App crash when editing comment by pressing arrow up key

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21484] opened 2023-06-24 11:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Write a message to concierge
2. Edit it by pressing up arrow key

## Expected Result:
App is not crashed when editing comment by pressing arrow up key

## Actual Result:
App crash when editing comment by pressing arrow up key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6b84374d-7757-4fea-82cd-5d0097a370a7

**Expensify/Expensify Issue URL:**

**Issue reported by:** requested

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686949778901619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dan1d** [comment] 2023-06-25 04:25
Cannot reproduce anymore on DEV env

**Comment by jeet-dhandha** [comment] 2023-06-25 11:55
Its basically crashing at this error:
```
[alrt] NewExpensify crash caught by error boundary - Cannot read properties of undefined (reading 'decode') - {"errorInfo":"{\"componentStack\":\"\
    at ReportActionItemMessageEdit (webpack-internal:///./src/pages/home/report/ReportActionItemMessageEdit.js:118:85)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at ReportActionItemDraft (webpack-internal:///./src/pages/home/report/ReportActionItemDraft.js:24:12)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at OfflineWithFeedback (webpack-internal:///./src/components/OfflineWithFeedback.js:108:85)\
    at withNetwork(OfflineWithFeedback)\
    at withLocalize(withNetwork(OfflineWithFeedback))\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at Hoverable (webpack-internal:///./src/components/Hoverable/index.js:35:86)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at Pressable (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/Pressable/index.js:40:24)\
    at eval (webpack-internal:///./src/components/Pressable/GenericPressable/BaseGenericPressable.js:56:24)\
    at eval (webpack-internal:///./src/components/Pressable/GenericPressable/index.js:21:22)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at AnimatedComponent (webpack-internal:///./node_modules/react-native-reanimated/lib/module/createAnimatedComponent.js:273:88)\
    at OpacityView (webpack-internal:///./src/components/OpacityView.js:53:88)\
    at eval (webpack-internal:///./src/components/Pressable/PressableWithFeedback.js:58:73)\
    at PressableWithSecondaryInteraction (webpack-internal:///./src/components/PressableWithSecondaryInteraction/index.js:45:86)\
    at ReportActionItem (webpack-internal:///./src/pages/home/report/ReportActionItem.js:167:161)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withReportActionsDrafts_(Component)\
    at withPrivate_blockedFromConcierge(withReportActionsDrafts_(Component))\
    at withPersonalDetailsList(withPrivate_blockedFromConcierge(withReportActionsDrafts_(Component)))\
    at withNetwork(withPersonalDetailsList(withPrivate_blockedFromConcierge(withReportActionsDrafts_(Component))))\
    at withLocalize(withNetwork(withPersonalDetailsList(withPrivate_blockedFromConcierge(withReportActionsDrafts_(Component)))))\
    at withWindowDimensions(withLocalize(withNetwork(withPersonalDetailsList(withPrivate_blockedFromConcierge(withReportActionsDrafts_(Component))))))\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at VirtualizedListCellContextProvider (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/VirtualizedListContext.js:73:23)\
    at CellRenderer (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/index.js:1488:86)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/ScrollView/ScrollViewBase.js:68:24)\
    at eval (webpack-internal:///./node_modules/create-react-class/factory.js:897:37)\
    at ScrollView\
    at VirtualizedListContextProvider (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/VirtualizedListContext.js:44:24)\
    at VirtualizedList (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/VirtualizedList/index.js:171:86)\
    at FlatList (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/FlatList/index.js:181:86)\
    at BaseInvertedFlatList (webpack-internal:///./src/components/InvertedFlatList/BaseInvertedFlatList.js:60:86)\
    at InvertedFlatList (webpack-internal:///./src/components/InvertedFlatList/index.js:52:86)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at AnimatedComponent (webpack-internal:///./node_modules/react-native-reanimated/lib/module/createAnimatedComponent.js:273:88)\
    at ReportActionsList (webpack-internal:///./src/pages/home/report/ReportActionsList.js:108:89)\
    at WithCurrentUserPersonalDetails (webpack-internal:///./src/components/withCurrentUserPersonalDetails.js:54:27)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withNetwork(Component)\
    at withPersonalDetailsList(withNetwork(Component))\
    at withLocalize(withPersonalDetailsList(withNetwork(Component)))\
    at withWindowDimensions(withLocalize(withPersonalDetailsList(withNetwork(Component))))\
    at ReportActionsView (webpack-internal:///./src/pages/home/report/ReportActionsView.js:104:86)\
    at withNetwork(ReportActionsView)\
    at withLocalize(withNetwork(ReportActionsView))\
    at WithNavigationFocus (webpack-internal:///./src/components/withNavigationFocus.js:23:91)\
    at withWindowDimensions(Component)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at FullPageNotFoundView (webpack-internal:///./src/components/BlockingViews/FullPageNotFoundView.js:64:13)\
    at withLocalize(FullPageNotFoundView)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at PickerAvoidingView (webpack-internal:///./node_modules/react-native-picker-select/src/PickerAvoidingView/index.js:22:23)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at KeyboardAvoidingView\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at SafeAreaConsumer\
    at ScreenWrapper (webpack-internal:///./src/components/ScreenWrapper/index.js:74:86)\
    at withNetwork(ScreenWrapper)\
    at withKeyboardState(withNetwork(ScreenWrapper))\
    at withWindowDimensions(withKeyboardState(withNetwork(ScreenWrapper)))\
    at WithEnvironment (webpack-internal:///./src/components/withEnvironment.js:44:88)\
    at WithNavigation (webpack-internal:///./src/components/withNavigation.js:23:93)\
    at ReportScreen (webpack-internal:///./src/pages/home/ReportScreen.js:175:86)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withNetwork(Component)\
    at WithNavigation (webpack-internal:///./src/components/withNavigation.js:23:93)\
    at WithNavigationFocus (webpack-internal:///./src/components/withNavigationFocus.js:23:91)\
    at withWindowDimensions(Component)\
    at withLocalize(withWindowDimensions(Component))\
    at WithViewportOffsetTop (webpack-internal:///./src/components/withViewportOffsetTop.js:47:88)\
    at ReportScreenWrapper (webpack-internal:///./src/libs/Navigation/AppNavigator/ReportScreenWrapper.js:101:86)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at StaticContainer (webpack-internal:///./node_modules/@react-navigation/core/lib/module/StaticContainer.js:13:16)\
    at EnsureSingleNavigator (webpack-internal:///./node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js:17:5)\
    at SceneView (webpack-internal:///./node_modules/@react-navigation/core/lib/module/SceneView.js:22:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at CardSheet (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Stack/CardSheet.js:18:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at AnimatedComponent (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js:59:88)\
    at AnimatedComponentWrapper\
    at Dummy (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/GestureHandler.js:14:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at AnimatedComponent (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js:59:88)\
    at AnimatedComponentWrapper\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at Card (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js:52:1)\
    at CardContainer (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Stack/CardContainer.js:27:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at NativeScreen (webpack-internal:///./node_modules/react-native-screens/lib/module/index.js:58:1)\
    at AnimatedComponent (webpack-internal:///./node_modules/@expensify/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js:59:88)\
    at AnimatedComponentWrapper\
    at MaybeScreen (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Screens.js:32:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at MaybeScreenContainer (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Screens.js:20:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at Background (webpack-internal:///./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/Background.js:15:5)\
    at CardStack (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Stack/CardStack.js:189:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at SafeAreaProviderCompat (webpack-internal:///./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/SafeAreaProviderCompat.js:40:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at StackView (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/views/Stack/StackView.js:34:1)\
    at PreventRemoveProvider (webpack-internal:///./node_modules/@react-navigation/core/lib/module/PreventRemoveProvider.js:43:5)\
    at NavigationContent (webpack-internal:///./node_modules/@react-navigation/core/lib/module/useComponent.js:10:5)\
    at eval (webpack-internal:///./node_modules/@react-navigation/core/lib/module/useComponent.js:27:7)\
    at StackNavigator (webpack-internal:///./node_modules/@react-navigation/stack/lib/module/navigators/createStackNavigator.js:18:5)\
    at Suspender (webpack-internal:///./node_modules/react-freeze/dist/index.modern.js:10:21)\
    at Suspense\
    at Freeze (webpack-internal:///./node_modules/react-freeze/dist/index.modern.js:30:22)\
    at FreezeWrapper (webpack-internal:///./src/libs/Navigation/FreezeWrapper.js:30:66)\
    at CentralPaneNavigator\
    at StaticContainer (webpack-internal:///./node_modules/@react-navigation/core/lib/module/StaticContainer.js:13:16)\
    at EnsureSingleNavigator (webpack-internal:///./node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js:17:5)\
    at SceneView (webpack-internal:///./node_modules/@react-navigation/core/lib/module/SceneView.js:22:5)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at ThreePaneView (webpack-internal:///./src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/ThreePaneView.js:44:101)\
    at PreventRemoveProvider (webpack-internal:///./node_modules/@react-navigation/core/lib/module/PreventRemoveProvider.js:43:5)\
    at NavigationContent (webpack-internal:///./node_modules/@react-navigation/core/lib/module/useComponent.js:10:5)\
    at eval (webpack-internal:///./node_modules/@react-navigation/core/lib/module/useComponent.js:27:7)\
    at ResponsiveStackNavigator (webpack-internal:///./src/libs/Navigation/AppNavigator/createResponsiveStackNavigator/index.js:38:23)\
    at AuthScreens (webpack-internal:///./src/libs/Navigation/AppNavigator/AuthScreens.js:156:86)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withWindowDimensions(Component)\
    at AppNavigator (webpack-internal:///./src/libs/Navigation/AppNavigator/index.js:16:13)\
    at EnsureSingleNavigator (webpack-internal:///./node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js:17:5)\
    at BaseNavigationContainer (webpack-internal:///./node_modules/@react-navigation/core/lib/module/BaseNavigationContainer.js:89:5)\
    at ThemeProvider (webpack-internal:///./node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js:12:5)\
    at NavigationContainerInner (webpack-internal:///./node_modules/@react-navigation/native/lib/module/NavigationContainer.js:42:5)\
    at NavigationRoot (webpack-internal:///./src/libs/Navigation/NavigationRoot.js:72:74)\
    at withCurrentReportId(NavigationRoot)\
    at withWindowDimensions(withCurrentReportId(NavigationRoot))\
    at DeeplinkWrapper (webpack-internal:///./src/components/DeeplinkWrapper/index.website.js:68:86)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Expensify (webpack-internal:///./src/Expensify.js:127:77)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withLocalize(Component)\
    at BaseErrorBoundary (webpack-internal:///./src/components/ErrorBoundary/BaseErrorBoundary.js:51:86)\
    at PickerStateProvider (webpack-internal:///./node_modules/react-native-picker-select/src/PickerStateProvider.js:44:86)\
    at CurrentReportIdContextProvider (webpack-internal:///./src/components/withCurrentReportId.js:29:66)\
    at KeyboardStateProvider (webpack-internal:///./src/components/withKeyboardState.js:47:86)\
    at WindowDimensionsProvider (webpack-internal:///./src/components/withWindowDimensions.js:63:86)\
    at RenderersPropsProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/context/RenderersPropsProvider.js:46:44)\
    at ListStyleSpecsProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/context/ListStyleSpecsProvider.js:70:3)\
    at SharedPropsProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/context/SharedPropsProvider.js:82:48)\
    at RenderRegistryProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/context/RenderRegistryProvider.js:41:3)\
    at RenderHTMLConfigProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/RenderHTMLConfigProvider.js:72:5)\
    at TRenderEngineProvider (webpack-internal:///./node_modules/react-native-render-html/lib/commonjs/TRenderEngineProvider.js:121:3)\
    at BaseHTMLEngineProvider (webpack-internal:///./src/components/HTMLEngineProvider/BaseHTMLEngineProvider.js:91:13)\
    at HTMLEngineProvider (webpack-internal:///./src/components/HTMLEngineProvider/index.js:18:18)\
    at withWindowDimensions(HTMLEngineProvider)\
    at LocaleContextProvider (webpack-internal:///./src/components/withLocalize.js:94:86)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at WithCurrentUserPersonalDetails (webpack-internal:///./src/components/withCurrentUserPersonalDetails.js:54:27)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at withOnyx(LocaleContextProvider)\
    at __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///./src/components/SafeArea/index.js:6:23)\
    at PortalProviderComponent (webpack-internal:///./node_modules/@gorhom/portal/lib/module/components/portalProvider/PortalProvider.js:18:3)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at NativeSafeAreaProvider (webpack-internal:///./node_modules/react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web.js:28:5)\
    at SafeAreaProvider (webpack-internal:///./node_modules/react-native-safe-area-context/lib/module/SafeAreaContext.js:38:5)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at Provider (webpack-internal:///./src/components/createOnyxContext.js:32:19)\
    at withOnyx (webpack-internal:///./node_modules/react-native-onyx/dist/web.development.js:2270:9)\
    at ComposeProviders (webpack-internal:///./src/components/ComposeProviders.js:20:214)\
    at OnyxProvider (webpack-internal:///./src/components/OnyxProvider.js:61:12)\
    at ComposeProviders (webpack-internal:///./src/components/ComposeProviders.js:20:214)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at GestureHandlerRootView\
    at App\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at div\
    at eval (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/View/index.js:52:25)\
    at AppContainer (webpack-internal:///./node_modules/@expensify/react-native-web/dist/exports/AppRegistry/AppContainer.js:23:24)\"}"}```

**Comment by jeet-dhandha** [comment] 2023-06-25 11:58
@kbecciv Anyone who's is getting this issue, ask them:
1. Take a pull from `upstream/main` branch.
2. Then run `npm i` which should update all the packages regarding `expensify-common`. 
This should fix the issue.

**Comment by laurenreidexpensify** [comment] 2023-06-26 12:26
@jeet-dhandha can you confirm if you are able to reproduce still, as @dan1d says it's no longer an issue?

**Comment by jeet-dhandha** [comment] 2023-06-27 19:25
@laurenreidexpensify Its no longer reproducible, but i added steps for fix if anyone is having this issue.

**Comment by laurenreidexpensify** [comment] 2023-06-28 12:06
As no longer reproducible am closing

**Closed by laurenreidexpensify** 2023-06-28 12:06 UTC
Labels: Daily, Needs Reproduction, Bug
