### ISSUE TITLE
[$1000] [HOLD for payment 2023-08-08] Dev: Web - Console error on create new workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23638] opened 2023-07-26 12:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon
2. Create a new workspace and check the console

## Expected Result:
 Should not show any console error

## Actual Result:
Console error appears (Invalid prop `reports.report_5370990936798009.writeCapability` of value `daily` supplied to `ReportScreenWrapper`, expected one of ["all","admins"].
)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45-8
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/29f5fa5f-9777-45a2-b1cd-3a9d0b5fd3ae

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690356298944369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01db31db71b4efd7d9</li>
        <li>Upwork Job ID: 1688916131373895680</li>
        <li>Last Price Increase: 2023-08-08</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-07-26 13:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error for new workspace or request money action

### What is the root cause of that problem?
It is a regression from PR https://github.com/Expensify/App/pull/21950 where we have added an extra param `writeCapability` for the function `buildOptimisticChatReport` but not passed from all required `buildOptimisticChatReport` called occurrences.

https://github.com/Expensify/App/pull/21950/files#diff-65c096044d5f69b35bcdec14c99c4fda4580759df9b1a7c36650d58eea276f1dR1763

https://github.com/Expensify/App/blob/1fac96bba4f60e5258c43953817b1f31f6b3d3c7/src/libs/ReportUtils.js#L2002-L2014

https://github.com/Expensify/App/blob/1fac96bba4f60e5258c43953817b1f31f6b3d3c7/src/components/ReportActionItem/MoneyRequestAction.js#L100-L115

### What changes do you think we should make in order to solve the problem?
We need to pass `writeCapability` param with the correct value in both places.

**Comment by rezkiy37** [comment] 2023-07-28 13:33
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work in this issue, because I am the author of the [broken PR](https://github.com/Expensify/App/pull/21950).

**Comment by amyevans** [comment] 2023-07-28 14:00
Self-assigning since this is a regression from https://github.com/Expensify/App/issues/21456

**Comment by laurenreidexpensify** [comment] 2023-07-28 15:06
@amyevans can we remove `needs reproduction` label then, as am assuming you can repro?

**Comment by amyevans** [comment] 2023-07-28 15:18
Good call, done!

**Comment by ayazhussain79** [comment] 2023-07-28 16:02
@amyevans can you please check that I have reported this https://github.com/Expensify/App/issues/23647 bug before this https://github.com/Expensify/App/issues/23638 one
@Pujan92  mentioned they have same RCA

**Comment by ayazhussain79** [comment] 2023-07-31 13:22
@amyevans @rezkiy37  please check that here is the root case of this issue  https://github.com/Expensify/App/issues/23647 that i have reported before PR deployed on staging and i have reported before this bug https://github.com/Expensify/App/issues/23638

**Comment by rezkiy37** [comment] 2023-07-31 13:39
> @amyevans @rezkiy37 please check that here is the root case of this issue #23647 that i have reported before PR deployed on staging and i have reported before this bug #23638

The root case is same. I fixed it here - https://github.com/Expensify/App/pull/23815.

**Comment by ayazhussain79** [comment] 2023-07-31 13:46
@rezkiy37  yes it's fixed but i have reported this bug https://github.com/Expensify/App/issues/23647 before this one https://github.com/Expensify/App/issues/23638

**Comment by rezkiy37** [comment] 2023-07-31 13:48
> @rezkiy37 yes it's fixed but i have reported this bug #23647 before this one #23638

Sorry, but I am a person who process such kind of questions. I am not an Expensify employee, I work at Callstack.

**Comment by ayazhussain79** [comment] 2023-08-08 14:24
@laurenreidexpensify offer accepted, Thank you

**Comment by mananjadhav** [comment] 2023-08-08 14:27
@laurenreidexpensify there is no payment for me, this was a regression. Payment will be handled in the policy-admin issue.

**Comment by laurenreidexpensify** [comment] 2023-08-08 14:28
Payment Summary:

- Bug reporter: @gadhiyamanan - $250, offer sent in Upwork AND @ayazhussain79 - $250, offer sent in Upwork
- Contributor: @rezkiy37 - no payment, CallStack employee
- C+: @mananjadhav -no payment as this was a regression

**Comment by laurenreidexpensify** [comment] 2023-08-08 14:28
Closing out as the regression testing will be handled in the original issue

**Closed by laurenreidexpensify** 2023-08-08 14:28 UTC
Labels: Daily, Awaiting Payment, Bug
