### ISSUE TITLE
[HOLD for #21910][$1000] Web - Bot recommendation message is shown on the placeholder of production app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22178] opened 2023-07-04 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Go to production new expensify on web chrome (Happens on prod only) and login with User A
2. Create a new room in PUBLIC mode
3. Go to header of the room , copy the share code URL
4. On another web chrome login with User B and paste the URL so that User B can get access to the room
5. From User A, notice the chat composer placeholder. Instead of showing 'Write something', it shows concierge bot recommendation. Refreshing the page then solves the problem.

## Expected Result:
'Write something' message should be shown on the placeholder of production app

## Actual Result:
Bot recommendation message is shown on the placeholder of production app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/047b034d-9939-472c-8ce9-cd8ffc9759cb

https://github.com/Expensify/App/assets/93399543/d00227c7-77f0-4810-8a7b-893f29388794

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688452510141429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01190afe684784e3f0</li>
        <li>Upwork Job ID: 1676423042899935232</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-05 02:32
Hey @priya-zha, I'm a little confused about what the bug is here. All of the behaviour in your videos seems to be expected behaviour. Could you please provide a bit more detail about what the issue is?

**Comment by kadiealexander** [comment] 2023-07-05 02:49
Reproduced:

https://github.com/Expensify/App/assets/59587260/fb543dc6-93bd-441d-8227-403b3e21e1b9

**Comment by alitoshmatov** [comment] 2023-07-05 07:53
Looks like this issue is related to this - https://github.com/Expensify/App/issues/21910. In mentioned issue, concierge is added to public rooms, when adding new user. 
That is why we see `Ask me anything!` placeholder, because in the code there is a logic where if one of the members is concierge that we will show this placeholder:

https://github.com/Expensify/App/blob/ecfcd8325d73851499f00399b14b8ae8e7f55f90/src/pages/home/report/ReportActionCompose.js#L354-L364

To conclude we can hold this for https://github.com/Expensify/App/issues/21910 .

We can also change the logic if it is not expected behavior to have this placeholder in public rooms which include concierge

**Comment by s77rt** [comment] 2023-07-05 18:37
@alitoshmatov Thanks! That makes sense!

@kadiealexander Can you please put this on hold for https://github.com/Expensify/App/issues/21910

**Comment by s77rt** [comment] 2023-07-18 23:28
Still on hold

**Comment by s77rt** [comment] 2023-07-27 23:21
Still on hold

**Comment by s77rt** [comment] 2023-08-07 16:36
Same ^

**Comment by kadiealexander** [comment] 2023-08-22 06:18
Same

**Comment by s77rt** [comment] 2023-08-30 14:14
Still on hold

**Comment by s77rt** [comment] 2023-09-11 11:14
Still on hold

**Comment by s77rt** [comment] 2023-09-20 20:50
Same ^

**Comment by s77rt** [comment] 2023-09-30 14:45
Same ^

**Comment by kadiealexander** [comment] 2023-10-10 06:36
Same.

**Comment by s77rt** [comment] 2023-10-19 05:08
Still on hold

**Comment by s77rt** [comment] 2023-10-27 17:51
Same ^

**Comment by s77rt** [comment] 2023-11-06 09:25
Same ^

**Comment by s77rt** [comment] 2023-11-16 00:52
Still on hold

**Comment by s77rt** [comment] 2023-11-24 18:50
Same ^

**Comment by s77rt** [comment] 2023-12-04 18:43
Same ^

**Comment by s77rt** [comment] 2023-12-13 16:02
Still on hold

**Comment by kadiealexander** [comment] 2023-12-20 03:32
Closing as no longer reproducible. Feel free to reopen if you disagree.

**Closed by kadiealexander** 2023-12-20 03:32 UTC
Labels: External, Weekly, Bug
