### ISSUE TITLE
[HOLD for payment 2024-05-06] App lags and every actions happen with delay

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39864] opened 2024-04-08 20:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in
2. Go to different areas (start a chat, request money, open an expense report, switch from one workspace to another, go to profile setting and back to the chat view etc)

## Expected Result:
There is no significant delay when navigating to different areas of the app

## Actual Result:
The app lags and almost every action happens with a delay

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/3ed5691f-b49e-4412-b07f-f3070de09ef4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-08 20:52
We think that this bug might be related to #vip-vsb

**Comment by Julesssss** [comment] 2024-04-09 14:44
I'm not seeing the same performance issue on Android native. As the issue is also a generic performance issue I'm demoting it from a blocker.

**Comment by roryabraham** [comment] 2024-04-09 16:11
I think this is too generic to be useful as an issue, but I'll bring it up in #newdot-performance

**Comment by Julesssss** [comment] 2024-04-10 10:28
Continuing [discussion](https://expensify.slack.com/archives/C05LX9D6E07/p1712744924249089?thread_ts=1712679212.179729&cid=C05LX9D6E07) in Slack, as there is data showing an increase in render time for app switching.

**Comment by Julesssss** [comment] 2024-04-10 13:41
I have some more information from QA: 

Issue still occurs. Reproduced in android only and not in iOS. It is affecting mostly the chats and LHN.

**Devices reproduced**
- Samsung Galaxy A52s 5G / Android 14
- iPhone 12 pro / iOS 17.4
- Xiaomi Redmi Note 10 (4/128) / Android 12

**Videos:**
 

https://github.com/Expensify/App/assets/10736861/35b6ae15-15be-4f27-b2ad-04c9f40aa6f6


https://github.com/Expensify/App/assets/10736861/5f740eac-284c-4920-b588-82b2a5a25281


https://github.com/Expensify/App/assets/10736861/d1c94ea3-6141-47c3-b61e-e0b5e6c74485

**Comment by Julesssss** [comment] 2024-04-10 15:43
Applause have provided further logs and reproduction steps [here](https://expensify.slack.com/archives/C05LX9D6E07/p1712763013050639)

**Comment by Julesssss** [comment] 2024-04-10 15:46
Applause user accounts:
applausetester+0111pm@applause.expensifail.com, applausetester+0403rbandroid@applause.expensifail.com applausetester+bpcategory@applause.expensifail.com - Android
applausetester+110523pm@applause.expensifail.com - iOS

[Logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22processing%22%20AND%20blob%3A%22SendPerformanceTiming%22%20AND%20blob%3A%22staging.new.expensify.switch_report.warm%22%20AND%20blob%3A%2F%5B0-9%5D%7B4%2C10%7D%2F%20AND%20blob%3A%22android%22%20AND%20timestamp%3A%5B2024-04-03T00%3A00%20TO%202024-04-11T23%3A59%5D) for all Android timing events this week 


**iPhone Logs**
- Tap the workspace switcher
- Select a workspace
- Open the workspace switcher
- Select another workspace
- Navigate to the workspace switcher
- Tap Expensify to show all chats
- Tap FAB > Request money > Manual
- Enter amount
- Select workspace
- Enter description, merchant and request money
- Open the expense report

[App_Info_1.4.61-6 (3).json](https://github.com/Expensify/App/files/14934477/App_Info_1.4.61-6.3.json)
[Profile_trace_for_1.4.61-6 (3).cpuprofile](https://github.com/Expensify/App/files/14934478/Profile_trace_for_1.4.61-6.3.cpuprofile)

**Comment by adhorodyski** [comment] 2024-04-10 17:09
Investigated to be the bottleneck on `getSearchText()` processing for a lot of personalDetails on an account (string concat).

Linked by @danieldoglas to https://github.com/Expensify/App/pull/38887 - reverted in https://github.com/Expensify/App/pull/40019. The initial bug needs a new solution to the problem.
 
 
<img width="1227" alt="Screenshot 2024-04-10 at 08 34 05" src="https://github.com/Expensify/App/assets/42047036/1601f9b2-64ec-40fe-b640-1a90c469ee40">

**Comment by roryabraham** [comment] 2024-04-12 21:11
ok, looks like this has probably been fixed but we'll double-check before shipping the checklist

**Comment by roryabraham** [comment] 2024-04-15 16:53
requested retest: https://expensify.slack.com/archives/C9YU7BX5M/p1713199986484979

**Comment by kavimuru** [comment] 2024-04-15 17:09
Issue fixed now. 

https://github.com/Expensify/App/assets/43996225/318a36f5-08be-4a18-a77c-7e35c7b6a797

**Comment by roryabraham** [comment] 2024-04-15 17:34
kk, closing this out

**Comment by mallenexpensify** [comment] 2024-06-05 23:13
@jayeshmangwani , can you please accept the job and reply here once you have? 
https://www.upwork.com/nx/job-post/custom/preview?uid=1798493059688799274
 (price was dropped to $250 on 4/4 and you were assigned on 4/15 to do the review)

**Comment by jayeshmangwani** [comment] 2024-06-05 23:18
Thanks for the quick help 🙏 @mallenexpensify , you sent the upwork offer, but now I am getting paid via NewDot payments, though i have no issues with the Upwork offer for this issue

**Comment by jayeshmangwani** [comment] 2024-06-06 05:47
> can you please accept the job and reply here once you have?

@mallenexpensify Offer accepted

**Comment by mallenexpensify** [comment] 2024-06-07 21:34
Contributor+: @jayeshmangwani paid $250 via Upwork.  

d'oh, sorry about that, you'd think that I would know, having invited you to NewDot payments.  More of a knee-jerk habit. I paid via Upwork cuz I already clicked the button before I saw your comment abovve, sorry.

**Closed by mallenexpensify** 2024-06-07 21:34 UTC
Labels: Engineering, Daily, Improvement, Internal, Bug
