### ISSUE TITLE
[HOLD for payment 2024-02-19] [HOLD for #19642][$1000] mWeb - Non-Responsive view in legal name screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26401] opened 2023-08-31 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings-> Click Profile
2. Click personal details -> Click legal name
3. Focus on any text field -> Swipe up to scroll

## Expected Result:
This screen should be responsive

## Actual Result:
Non-responsive view on Legal name screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5d791c02-a6f0-450c-93dc-3f5ee359fdbf

https://github.com/Expensify/App/assets/93399543/7dc551e1-bc47-473a-8c86-ec53d5877b29

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692911380405329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ea2797105a3c164</li>
        <li>Upwork Job ID: 1701114239326281728</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28119719</li>
<li>suneox | Contributor | 28119720</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-08-31 15:41
same issue is happening contact method verifucation I reported this a while ago i believe should be added as reporter @kbecciv -
https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/thread/C049HHMV9SM-1692911380.405329

**Comment by adelekennedy** [comment] 2023-09-04 00:51
@ishpaul777 can you point to where you reported this? The link above redirects me to this issues thread.

**Comment by ishpaul777** [comment] 2023-09-04 05:31
https://expensify.slack.com/archives/C049HHMV9SM/p1691507520738229

I reported the behaviour, it was not a well formatted bug report.

**Comment by adelekennedy** [comment] 2023-09-04 23:07
ah - so it looks like you asked about the bug but were told not to report it because it may have been related to an upcoming PR.

**Comment by ishpaul777** [comment] 2023-09-08 05:40
@adelekennedy any update?

**Comment by adelekennedy** [comment] 2023-09-08 15:14
Yeah - this won't count for the reporting bonus as it wasn't made into an actual issue

**Comment by ishpaul777** [comment] 2023-09-08 15:20
Ok, thanks for clarification

**Comment by adelekennedy** [comment] 2023-09-11 06:04
wow - missed making this external

**Comment by PiyushChandra17** [comment] 2023-09-11 18:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Legal Name screen is not responsive

### What is the root cause of that problem?
In order for the screen to be responsive, media queries are required, there's no media queries set.

### What changes do you think we should make in order to solve the problem?
Since the problem occurs in mWeb, we should add the following media queries [here](https://github.com/Expensify/App/blob/main/web/index.html#L110)

```
@media screen and (max-width: 479px) { 
    .css-view-175oi2r {
        overflow: hidden;
    }
}
```

This style will override the original style and should fix the problem.

### What alternative solutions did you explore? (Optional)
NA

### Result:

https://github.com/Expensify/App/assets/47579287/e38109ad-7870-48a8-abae-a09908544280

**Comment by adelekennedy** [comment] 2023-09-13 10:17
@0xmiroslav to review

**Comment by adelekennedy** [comment] 2023-09-18 08:56
@0xmiroslav I think this bug is actually an issue for performance, should we increase bounty for more proposals?

**Comment by adelekennedy** [comment] 2023-09-18 09:01
I'm using performance in the non-engineering way 😂

**Comment by desirekaleba** [comment] 2023-09-18 12:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Legal name form screen scrolls all the way up on TextInput focus

### What is the root cause of that problem?
The root cause of this problem is that the `ScreenWrapper` component is passed `shouldEnableMaxHeight` prop without a realistic `windowHeight`

### What changes do you think we should make in order to solve the problem?

To solve this problem, I propose the removal of the `shouldEnableMaxHeight`. This not only solves the problem but makes it like its sibling component(`AddressPage`)

### What alternative solutions did you explore? (Optional)

N/A

**Comment by desirekaleba** [comment] 2023-09-18 12:46
@0xmiroslav Can I propose another solution?

**Comment by desirekaleba** [comment] 2023-09-18 13:29
## Proposal
[Updated](https://github.com/Expensify/App/issues/26401#issuecomment-1723317496)

**Comment by desirekaleba** [comment] 2023-09-18 14:49
## Proposal
[Updated](https://github.com/Expensify/App/issues/26401#issuecomment-1723317496)

**Comment by desirekaleba** [comment] 2023-09-18 14:59
@0xmiroslav, FYI, the same issues is seen on:
1. Go to settings-> Click Profile -> Click Display name
2. Focus on any text field -> Swipe up to scroll

**Comment by adelekennedy** [comment] 2023-09-21 10:17
@0xmiroslav can you review the updated proposal above?

**Comment by desirekaleba** [comment] 2023-09-21 10:58
@0xmiroslav, I believe a solid solution is what fixes the issue without introducing any regression. 

I have looked into the git history and [here](https://github.com/desirekaleba/App/commit/60ed83348f3f0483a5981fe7f7a8f0f120aa2f07) is the commit that changed it.

Including `shouldEnableMaxHeight` was not relevant to what the issue was. [Here](https://github.com/Expensify/App/issues/22606#issuecomment-1633894261) is the issue that was being fixed. I also reviewed the entire PR and its comments and realized nothing was really about adding `shouldEnableMaxHeight`. You can look into the PR [here](https://github.com/Expensify/App/pull/22906/files).

I will say that that irrelevant change is what introduced this issue

PS: Both `AddressPage` and `LegalNamePage` share the same behaviors. If you still doubt my solution, I would like to know why `AddressPage` omitted `shouldEnableMaxHeight` on purpose.

**Comment by desirekaleba** [comment] 2023-09-21 11:18
@0xmiroslav, I you check the `ScreenWrapper` component on line 92. You will see 

```js
const maxHeight = this.props.shouldEnableMaxHeight ? this.props.windowHeight : undefined;
```

It does not make sense to enable `shouldEnableMaxHeight` without specifying the `windowHeight` because I will fall to `undefined`

**Comment by ishpaul777** [comment] 2023-09-21 11:34
@desirekaleba windowHeight is passed as prop, we are using HOC `withWindowDimensions` to get the windowHeight reference - https://github.com/Expensify/App/blob/main/src/components/ScreenWrapper/index.js#L155C65-L155C65

removing shouldEnableMaxHeight is not a solution as removing it will not dock the green button along with keyboard. Hope that's understandable

https://github.com/Expensify/App/assets/104348397/1dbf124f-4dab-44d5-9b3b-0d7b6174ce54

**Comment by desirekaleba** [comment] 2023-09-21 12:06
@ishpaul777, Thanks for that. I'm looking into another solution

**Comment by adelekennedy** [comment] 2023-09-25 07:55
pending a solution still

**Comment by desirekaleba** [comment] 2023-09-25 07:58
I'm looking into a better solution still @adelekennedy

**Comment by adelekennedy** [comment] 2023-09-28 08:59
@0xmiroslav any feedback here? We've seen some updates above

**Comment by adelekennedy** [comment] 2023-10-02 09:45
I don't think we need to increase price just yet

**Comment by desirekaleba** [comment] 2023-10-02 09:57
The help wanted badge was removed. Is this still external @adelekennedy

**Comment by adelekennedy** [comment] 2023-10-09 15:23
Not intentionally - It looks like Melvin moved this internal due to no updates:

<img width="857" alt="Screenshot 2023-10-09 at 8 23 13 AM" src="https://github.com/Expensify/App/assets/60450566/5468ec09-3507-4761-93bd-859fc9f1ded6">

**Comment by adelekennedy** [comment] 2023-10-09 15:28
@desirekaleba do you have an eta on your solution? Otherwise @0xmiroslav I'm stuck on what to do - we can move this back to external to see if that will drum up more proposals? (this is still reproducible and a real bug)

**Comment by graylewis** [comment] 2023-10-09 15:51
### Proposal
Please re-state the problem that we are trying to solve in this issue.
A weird scrollable area shows up when the inputs on the LegalNamePage are in focus

### What is the root cause of that problem?
iOS has a weird feature in Safari that causes pages to be scrollable when inputs are in focus
(see reference: https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d)

This is evidenced by the fact that I don't experience this bug on Android web (chrome)

### What changes do you think we should make in order to solve the problem?
As verified by the experiences of other people trying to solve this difficulty on stackoverflow (https://stackoverflow.com/questions/56351216/ios-safari-unwanted-scroll-when-keyboard-is-opened-and-body-scroll-is-disabled) the only way to solve this is by using a JavaScript workaround. There are two primary approaches, either of which should be selectively applied to mobile iOS devices:
1. Disable scrolling when the field is in focus on the page.
2. A hacky solution that one user discovered; by changing the field's opacity for 1 frame it circumvents Apple's weird handling of the page size (https://gist.github.com/kiding/72721a0553fa93198ae2bb6eefaa3299)

I would favor the latter solution. Despite it's hackiness, it's more performant (solution 1 would require a useLayoutEffect call) and more succinct. 

### What alternative solutions did you explore? (Optional)
NA

**Comment by adelekennedy** [comment] 2023-10-16 16:11
Still pending better proposals

**Comment by adelekennedy** [comment] 2023-10-18 17:53
@0xmiroslav to review the above!

**Comment by adelekennedy** [comment] 2023-10-26 16:10
@suneox are you planning to update your proposal based on @0xmiroslav feedback?

**Comment by adelekennedy** [comment] 2023-10-30 17:20
@suneox have you updated your proposal for @0xmiroslav to review?

**Comment by adelekennedy** [comment] 2023-11-07 18:51
@0xmiroslav any updates on the proposal above?

**Comment by adelekennedy** [comment] 2023-11-09 20:54
@0xmiroslav bump to review

**Comment by adelekennedy** [comment] 2023-11-14 01:44
not overdue @0xmiroslav will provide feedback shortly

**Comment by adelekennedy** [comment] 2023-11-20 22:57
@0xmiroslav do yo have feedback for this one?

**Comment by adelekennedy** [comment] 2023-11-26 19:49
bumped in Slack

**Comment by adelekennedy** [comment] 2023-12-01 20:36
@0xmiroslav for your thoughts on the above!

**Comment by adelekennedy** [comment] 2023-12-01 20:41
Let's deprioritize for now? I'm thinking we can degrade this to weekly or monthly - it's still something we should fix but it's preventing core functionality imo

**Comment by adelekennedy** [comment] 2024-01-05 20:54
@0xmiroslav bump on the question above

**Comment by mallenexpensify** [comment] 2024-01-24 03:51
@fedirjh reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by DinalJivani** [comment] 2024-01-27 09:03
Hello @fedirjh 
I haven't received Upwork offer automatically. Please send me offer manually when you are around.
Thanks

**Comment by mallenexpensify** [comment] 2024-01-27 17:31
@adelekennedy is the BugZero team member who will be managing. 
@DinalJivani can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0154c21d13eb0e8dfe

**Comment by DinalJivani** [comment] 2024-01-27 18:21
@mallenexpensify  cc: @adelekennedy 
I haven’t received any upwork invite yet!

Did you meant “apply to the Upwork job you sent?”

**Comment by mallenexpensify** [comment] 2024-01-30 01:05
Invited now @DinalJivani , can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~0154c21d13eb0e8dfe

**Comment by adelekennedy** [comment] 2024-02-20 16:32
sorry all - was ooo yesterday, @fedirjh to close this out do we need a [regression test](https://github.com/Expensify/App/issues/26401#:~:text=%5B%40fedirjh%5D%20Determine%20if%20we%20should%20create%20a%20regression%20test%20for%20this%20bug.) for this one?

**Closed** 2024-02-20 17:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by mallenexpensify** [comment] 2024-02-21 01:58
Confirming @suneox has been paid
<img width="623" alt="image" src="https://github.com/Expensify/App/assets/22508304/4ceeabd7-895d-4847-80ec-36d6c720ea25">
