### ISSUE TITLE
Hybrid - Troubleshooting - Tools are limited

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#52200] opened 2024-11-07 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** Applause - Internal team
**Slack conversation** (hyperlinked to channel name): #[qa](https://expensify.slack.com/archives/C9YU7BX5M/p1730911447849089)

## Action Performed:
1. Navigate to troubleshoot

## Expected Result:
Troubleshooting tools should be the same as in the ND app. 

## Actual Result:
Troubleshooting tools are limited and not the same as in the ND app. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
ND app: 
<img src="https://github.com/user-attachments/assets/54ec0f93-9ae4-4351-8a3a-121193d3a8df" width="40%">

Hybrid app: 
<img src="https://github.com/user-attachments/assets/8f7fb71f-ea15-4841-9af6-a5122d80003d" width="40%">

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by muttmuure** [comment] 2024-11-10 12:38
I'm not sure what the plan is to add the testing suite to Hybrid

**Comment by muttmuure** [comment] 2024-11-10 12:38
We can track in the quality channel

**Comment by muttmuure** [comment] 2024-11-14 13:30
Asked about this in a quality thread

**Comment by AndrewGable** [comment] 2024-11-14 19:26
This is a dupe of https://github.com/Expensify/App/issues/50843 and possibly https://github.com/Expensify/App/issues/51421, so I think we can close. We have the four finger tap on HybridApp and will eventually align the apps to be the same, but that's held on https://github.com/Expensify/App/pull/52283 and some other smaller issues that are in the works.

**Closed by AndrewGable** 2024-11-14 19:26 UTC
Labels: Daily, Bug
