### ISSUE TITLE
[$250] BUG: After refreshing the page,  clicking on a chatroom, immediately collapses the listing of viewable chatrooms in the LHN reported by @george-hayakawa

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12145] opened 2022-10-26 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into staging.new.expensify
2. At any point in time, while using staging.new.expensify, I refresh staging.new.expensify. (tested on both Chrome and Firefox on two computers.)
3. Click on any chatroom listed in the LHN

## Expected Result:
The list of visible chatrooms in LHN should stay unaffected.

## Actual Result:
The list of visible chatrooms in LHN shrinks, and many previous chatrooms that were visible - are now hidden. (From a review of expensify-open-source, I see that other guides are reporting the same issue of disappearing chatrooms.)

## Workaround:
unknown
## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.2.18-7
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198064780-8e0d1e64-5873-41d0-b4b8-2808c0d434ba.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @george-hayakawa
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666460388819689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-10-26 20:41
Let me know if you need a hand here @arielgreen ! This one is impacting a few Guides I believe

**Comment by arielgreen** [comment] 2022-10-27 03:34
I am unable to reproduce this. @mitchexpensify can you give it a try?
![2022-10-26_23-31-26 (1)](https://user-images.githubusercontent.com/37308300/198185171-33319ebe-6e2a-46fa-86b2-92a430ee20b6.gif)

**Comment by MitchExpensify** [comment] 2022-10-27 19:39
I bet it is only reproducible when you have "a lot" of #admins rooms.

Here's a better video of the issue https://drive.google.com/file/d/1n-0qzCs4muAyWe51NqmewKiboJfz3Azo/view

**Comment by MitchExpensify** [comment] 2022-10-27 19:40
@kavimuru Is that video in the main issue body related to the issue described?

**Comment by arielgreen** [comment] 2022-10-28 01:05
https://www.upwork.com/jobs/~01b00fc4b6f17b312d

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 07:44
Can we bump this to weekly @arielgreen @Gonals

**Comment by arielgreen** [comment] 2022-11-01 15:59
@Santhosh-Sellavel we are now keeping E/App issues as daily

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 18:27
From issue creation, we keep daily until the only external job is set up. Then it would be bumped to weekly until there is a proposal. If the proposal is added melvin adds it daily to prioritize reviewing. If no proposals over a week we would double on overdue, right?
 If that's changed please post any changes like this in the #contributor-plus channel thanks!

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:57
Hey @arielgreen just dropping a note as a reminder to keep the pressure on to find a contributor and get this one closed out! I noticed this has `needs reproduction` for 8 days and so I bumped the related slack [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1667512652852389?thread_ts=1666460388.819689&cid=C01GTK53T8Q) in #expensify-open-source

**Comment by Gonals** [comment] 2022-11-04 12:09
Still waiting for a proposal

**Comment by Gonals** [comment] 2022-11-07 11:57
Still waiting

**Comment by arielgreen** [comment] 2022-11-08 21:45
No longer reproducible; closing.

**Closed by arielgreen** 2022-11-08 21:45 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
