### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] Web – On hover options in “flag a message” is not completely highlighted.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21505] opened 2023-06-24 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any report
2. Click on “Flag a message as offensive”
3. Flag options will appear
4. Notice that on hovering the options, unlike bottom line, top line is not merged with the highlighted hover background.

## Expected Result:
There should be no gap on left or right of the line, once the option is hovered it should be highlighted completely.

## Actual Result:
The padding is visible in top line on left and right

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (88)](https://github.com/Expensify/App/assets/93399543/4e4c48cf-a29c-480c-a2db-6de0adbad845)

https://github.com/Expensify/App/assets/93399543/57fbc61b-3085-45ec-b5e7-039b09b3f231

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:**https://expensify.slack.com/archives/C049HHMV9SM/p1687153180539119

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ecbe13e4d569798f</li>
        <li>Upwork Job ID: 1673735496011276288</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-24 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On hover option in “flag a message” is not completely highlighted or border bottom for an option is not shown with full width.

### What is the root cause of that problem?
We are providing the horizontal margin here and that is causing below 2 issues.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/FlagCommentPage.js#L134
1) Option gets highlight fully when the mouse hover only on the content(means excluding the margin part, but on hover we show highlight for margin part too)
2) Border bottom isn't shown for full width

**Issue**

https://github.com/Expensify/App/assets/14358475/4b159d12-07a0-4a06-bc4b-288b173add28


### What changes do you think we should make in order to solve the problem?
Instead of a margin, we should provide horizontal padding(`styles.ph5`) so that space will be part of the option element only. This will highlight the option on hover for the entire width and also full border will look clean on the hover highlight.

<details>
<summary>Result</summary>

https://github.com/Expensify/App/assets/14358475/06ab6c19-cfef-40d2-b996-117b4b56f699

</details>

**Comment by thiagobrez** [comment] 2023-06-26 13:47
@shawnborton Actually this one was not initially planned, because it's not using one of the components we're refactoring (`OptionsSelector`, `OptionsList`, `OptionRow`) and it's a static list. Maybe this one can continue, and we look back at it after the refactor?

**Comment by shawnborton** [comment] 2023-06-26 13:50
Got it. 

And to be clear, I would not consider this a bug since we knew this is how this worked when we implemented it cc @dangrous 

Maybe we can just do a quick follow up to get rid of the separator for this one? What do you think @dangrous?

**Comment by dangrous** [comment] 2023-06-26 15:31
Definitely known (trade off we decided on when creating it).

@shawnborton are you saying we're generally getting rid of the separators in similar situations? If so, yeah, we can drop it here, it'll be pretty easy

**Comment by shawnborton** [comment] 2023-06-26 15:32
Yup, I think we recently decided to just try to get rid of all of these line separators between list items.

**Comment by Pujan92** [comment] 2023-06-26 15:40
Isn't the entire option should be hoverable which I mentioned [here](https://github.com/Expensify/App/issues/21505#issuecomment-1605734732)?

**Comment by dangrous** [comment] 2023-06-27 15:46
@trjExpensify Since what @shawnborton suggested [here](https://github.com/Expensify/App/issues/21505#issuecomment-1607516243) is definitely something someone external could take on (removing the separators and updating the hover/padding stuff), do you think we should repurpose this issue into an ask for that? It's a pretty easy adjustment to make (though not really a bug anymore)

Alternately I'm happy to do it, but it might take a couple days to have time.

**Comment by trjExpensify** [comment] 2023-06-27 15:57
Yeah, we can still send a `new feature` external, especially something small like this. @Pujan92 you seem up for it as well yeah?

**Comment by Pujan92** [comment] 2023-06-27 16:01
Yes @trjExpensify

**Comment by trjExpensify** [comment] 2023-06-27 16:51
Cool, @aimane-chnaif can you review the proposal please?

**Comment by shawnborton** [comment] 2023-06-27 17:42
That works for me. Perhaps we could just slightly reduce the gap between the icon and the text above it? Maybe reduce it by 4px so the icon + text feels closer to the description above it?

**Comment by shawnborton** [comment] 2023-06-27 17:52
Nice, I think that helps make each row feel connected.

**Comment by Pujan92** [comment] 2023-06-27 18:16
As it is already assigned, I just raised a [PR](https://github.com/Expensify/App/pull/21721).

**Comment by Pujan92** [comment] 2023-06-27 18:18
> Ah I see you assigned [here](https://github.com/Expensify/App/issues/21505#event-9654797630)

Yes.

**Comment by trjExpensify** [comment] 2023-07-07 12:02
@Pujan92 & @aimane-chnaif, I've sent you both offers!

**Comment by trjExpensify** [comment] 2023-07-07 17:10
@Pujan92, paid!

**Comment by trjExpensify** [comment] 2023-07-10 10:04
@aimane-chnaif can you accept the offer?

**Comment by trjExpensify** [comment] 2023-07-11 15:52
Paid!

**Closed by trjExpensify** 2023-07-11 15:52 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
