### ISSUE TITLE
[Hold for payment][$500] mWeb - Login - Sometimes I can't reach the bottom of the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36515] opened 2024-02-14 15:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35509

## Action Performed:
1. On the log in screen, tap on the email field so the keyboards opens
2. Swipe to the bottom of the page
3. Swipe to the top of the page
4. Repeat steps 2 and 3 until the issue appears

## Expected Result:
User should be able to swipe without problems.

## Actual Result:
Sometimes I can't reach the bottom of the page while I have the keyboard on.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cce34a41-8c3d-4e75-9a85-a3d553c5ee12

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143dd11e70fd777fb</li>
        <li>Upwork Job ID: 1757793927154425856</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment] 2024-02-15 14:20
Thanks for the proposal @suneox! I'd appreciate some further detail on why this only (seems to) affect iOS/mWeb and not other platforms. I also feel your proposal isn't clear on why the solution works and how it relates to the root cause.

**Comment by jjcoffee** [comment] 2024-02-16 13:23
Gotcha, thanks for providing the extra details! Happy to go with @suneox's [proposal](https://github.com/Expensify/App/issues/36515#issuecomment-1945293654) here.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by kadiealexander** [comment] 2024-02-19 00:03
Not overdue.

**Comment by jjcoffee** [comment] 2024-02-19 14:47
@suneox Don't forget to let us know when we can expect the PR :bow:

**Comment by kadiealexander** [comment] 2024-03-12 03:43
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@jjcoffee] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@jjcoffee] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@jjcoffee] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@jjcoffee] Determine if we should create a regression test for this bug.
- [ ] [@jjcoffee] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-03-12 03:50
Payouts due:

- [x] Contributor: $500 @suneox
- [ ] Contributor+: $500 @jjcoffee

Upwork job is [here]().

**Comment by jjcoffee** [comment] 2024-03-12 10:40
- The PR that introduced the bug has been identified. Link to the PR: **N/A** this has always been the behaviour as far as I can tell
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. On the log in screen, tap on the email field so the keyboards opens
2. Swipe to the bottom of the page
3. Swipe again further down
4. Verify user can swipe to the very bottom of the page without problems

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-03-12 10:40
@kadiealexander Checklist complete!

**Comment by jjcoffee** [comment] 2024-03-15 10:14
@kadiealexander Friendly bump for payment :bow:

**Closed** 2024-03-20 05:57 UTC
Labels: Reviewing, External, Daily, Bug
