### ISSUE TITLE
HIGH: [Public] [$500] Allow anonymous users to mark comments as unread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35740] opened 2024-02-02 23:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4278704
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log out
3. Navigate to a public #room with a task as anon user (link https://staging.new.expensify.com/r/8661824749067368
)
4. Navigate to the task report and observe the behavior on LHN

## Expected Result:
Task report marks as read in LHN when navigate to public room with a task as Anon user and open the task

## Actual Result:
Task report marks bold in LHN when navigate to public room with a task as Anon user and open the task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/95a274f2-1a67-400c-823d-8e4dd68e8b74

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by lanitochka17** [comment] 2024-02-02 23:20
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-02-03 00:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An opened chat should not have it also be bolded in the LHN

### What is the root cause of that problem?
Since we are offline, we don't have any lastReadTime on the report. And it comes back as null.
When we initially open the report, we use this timestamp to determine if we should mark something as read,  and that flow will unbold the LHN. It's here: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionsList.js#L211

Because the timestamp is null, it will never mark it as unread because it fails the downstream check here: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/ReportUtils.ts#L3577 and not trigger the unbolding flow as mentioned before.

data for this use case confirming null:
![Screenshot 2024-02-02 at 6 07 10 PM](https://github.com/Expensify/App/assets/157416545/114513d1-6c23-4681-ad29-22a66c978c08)


### What changes do you think we should make in order to solve the problem?
We can shortcircuit the logic here: https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/ReportUtils.ts#L3577
To instruct it to return as unread, when lastReadTime is null. As we assume they have never read it. This will trigger the flow to mark it as read, and unbold the LHN.

### What alternative solutions did you explore? (Optional)

**Comment by sahilnagpal26** [comment] 2024-02-03 00:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task marks as unread in LHN when navigate to public room with task as Anon user & open it

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/de633acf4c6b4d91d1c1b6c6801184b43bbe050a/src/libs/SidebarUtils.ts#L306

https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/ReportUtils.ts#L3569-L3578

In the `SidebarUtils.getOptionData()` we get the optionData. The method uses `ReportUtils.isUnread(report)` method to figure out a report is read or unread. In case of the Anonymous user, the `report.lastTime` is undefined (evalautes to `''`) and hence,  `ReportUtils.isUnread(report)` always returns true. The option data's `isUnread` field is set to true making the display as bold. 

### What changes do you think we should make in order to solve the problem?

We can add a check for Anonymous user and set mark options data's isUnread field to `true` instead of false in this case. We could use `Session.isAnonymousUser()` for the same. 

### What alternative solutions did you explore? (Optional)

**Comment by sahilnagpal26** [comment] 2024-02-03 00:26
Contributor details
Your Expensify account email: nagpal.sahil01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/sahilnagpal

**Comment by nyomanjyotisa** [comment] 2024-02-03 02:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task report marked bold in LHN when navigate to public room with a task as Anonymous user

### What is the root cause of that problem?

The root cause of the problem is report.lastReadTime variable is empty because the user is Anonymous User. And because the lastReadTime value is empty, the isUnread function in ReportsUtils.js file will return true.

![Screenshot 2024-02-03 at 10 06 51](https://github.com/Expensify/App/assets/73281575/bad87e9b-06cb-4a7b-82e4-762c4c3061c1)

### What changes do you think we should make in order to solve the problem?

Add a condition to check if the lastReadTime is empty and isAnonymousUser, then return false in isUnread function.

can use the existing isAnonymousUser variable

![Screenshot 2024-02-03 at 10 02 47](https://github.com/Expensify/App/assets/73281575/9b101420-42e4-4730-a987-0feb6bdecdc6) 

### What alternative solutions did you explore? (Optional)

**Comment by nyomanjyotisa** [comment] 2024-02-03 02:10
Contributor details
Your Expensify account email: [jyotisa1616@gmail.com](mailto:jyotisa1616@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0153bd482cfbf9ad36

**Comment by nyomanjyotisa** [comment] 2024-02-03 02:12
Contributor details
Your Expensify account email: [jyotisa1616@gmail.com](mailto:jyotisa1616@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/~0153bd482cfbf9ad36](https://www.upwork.com/freelancers/~0153bd482cfbf9ad36)

**Comment by nyomanjyotisa** [comment] 2024-02-03 02:14
Contributor details
Your Expensify account email: [jyotisa1616@gmail.com](mailto:jyotisa1616@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/~0153bd482cfbf9ad36](https://www.upwork.com/freelancers/~0153bd482cfbf9ad36)

**Comment by nyomanjyotisa** [comment] 2024-02-03 02:15
Contributor details
Your Expensify account email: jyotisa1616@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0153bd482cfbf9ad36

**Comment by muttmuure** [comment] 2024-02-06 15:41
@shubham1206agra there are a few proposals [here](https://github.com/Expensify/App/issues/35740#issuecomment-1924936555) and [here](https://github.com/Expensify/App/issues/35740#issuecomment-1925020532) that require your review. Thank you!

**Comment by shubham1206agra** [comment] 2024-02-06 15:45
@muttmuure Actually, I need to confirm whether the Anonymous user should see any chat as unread or not. Can you post this internally to confirm?

**Comment by shubham1206agra** [comment] 2024-02-09 04:22
@muttmuure Bump on the question.

**Comment by muttmuure** [comment] 2024-02-13 15:21
Finding out

**Comment by situchan** [comment] 2024-02-14 05:47
to help @shubham1206agra 
🎀 👀 🎀

**Comment by rlinoz** [comment] 2024-02-14 12:16
Sounds good, thanks!

Going with @jeremy-croff's proposal.

**Comment by jeremy-croff** [comment] 2024-02-15 00:40
Awaiting upwork asssignment before I start. Thanks.

**Comment by rlinoz** [comment] 2024-02-15 13:36
huum weird, that should have been triggered.

@muttmuure would you mind helping us here, please?
https://www.upwork.com/jobs/~01e78aa240ed0c8960

**Comment by jeremy-croff** [comment] 2024-02-15 14:28
Thanks, expecting to start work in approx 12 hrs

**Comment by jeremy-croff** [comment] 2024-02-16 02:12
I'm used to automatically being sent an offer. I sent a proposal to the job invite from @muttmuure, but it was an invite for an interview.

**Comment by MonilBhavsar** [comment] 2024-02-16 06:14
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1708062205069949
Looks like we're never updating report's lastReadTime for anonymous accounts. So I believe this issue should be internal cc @rlinoz 
Here are the logs for one request https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%22856393270ef08b03-BOM%22%20AND%20timestamp%3A%5B2024-02-16T00%3A00%20TO%202024-02-17T23%3A59%5D

The fix would be to add anon token to this list if we agree we should be marking reports are read for anonymous users.
https://github.com/Expensify/Web-Expensify/blob/9f6d2e455fc5da24abb251aaa2004f8dda5d092e/lib/ReportAPI.php#L3984
I wonder if we should do it because every time we create a new anonymous user and and we're not going to reuse the read reports data outside of the session.


And for the client side, API commands are called in the order - `ReadNewestAction` and `OpenReport` while the correct order is opposite - `OpenReport` and `ReadNewestAction`. I don't think it matters in this case but still we should look into it.

**Comment by jeremy-croff** [comment] 2024-02-16 14:19
> Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1708062205069949 Looks like we're never updating report's lastReadTime for anonymous accounts. So I believe this issue should be internal cc @rlinoz Here are the logs for one request https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%22856393270ef08b03-BOM%22%20AND%20timestamp%3A%5B2024-02-16T00%3A00%20TO%202024-02-17T23%3A59%5D
> 
> The fix would be to add anon token to this list if we agree we should be marking reports are read for anonymous users. https://github.com/Expensify/Web-Expensify/blob/9f6d2e455fc5da24abb251aaa2004f8dda5d092e/lib/ReportAPI.php#L3984 I wonder if we should do it because every time we create a new anonymous user and and we're not going to reuse the read reports data outside of the session.
> 
> And for the client side, API commands are called in the order - `ReadNewestAction` and `OpenReport` while the correct order is opposite - `OpenReport` and `ReadNewestAction`. I don't think it matters in this case but still we should look into it.

Acknowledged, thanks for confirming this information. Putting PR on hold.

**Comment by rlinoz** [comment] 2024-02-16 18:36
Sorry about the delay here, I will take a look.

**Comment by rlinoz** [comment] 2024-02-16 19:00
Ok, I agree with Monil that it would be a waste to mark a report as read for an anon user in the backend, but we can still fix this I think.

I believe the backend should never clear the `lastReadTime` of a report for the frontend, so the `OpenReport` command should omit the field and the FE would work with whatever comes back from `ReadNewestAction` in this case.

It would still be a backend fix though.

Anyway, I will take this to slack.

**Comment by rlinoz** [comment] 2024-03-05 13:14
The PR is in production, so we should be good here.

**Comment by rlinoz** [comment] 2024-03-05 14:26
Hmmm this is the order I am seeing here
<img width="345" alt="image" src="https://github.com/Expensify/App/assets/5201282/dce95ed0-0ea0-4ec0-b1e5-9171ad9f7377">

So for anon accounts `OpenReport` is called before and after `ReadNewestAction`

And for logged accounts I see `ReadNewestAction` before `OpenReport`.

Anyway, I think we should investigate that in another issue.

**Comment by jeremy-croff** [comment] 2024-03-13 02:23
Closed https://github.com/Expensify/App/pull/36654 due to resolving it on back end. Thanks!

**Comment by quinthar** [comment] 2024-03-26 05:40
Can we close this?

**Comment by muttmuure** [comment] 2024-04-04 14:24
Handling

**Comment by muttmuure** [comment] 2024-04-04 14:26
25% reward

$125 - @jeremy-croff 
$125 - @shubham1206agra

**Comment by muttmuure** [comment] 2024-04-04 14:29
Done

**Comment by jeremy-croff** [comment] 2024-04-04 14:32
> Actually waiting for @jeremy-croff to accept

Accepted, thanks so much for the partial reward considering the circumstance!

**Comment by muttmuure** [comment] 2024-04-04 14:47
No worries! Paid. Payment summary for @shubham1206agra above is still accurate and their bounty is still unpaid.

**Closed by muttmuure** 2024-04-04 14:47 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by muttmuure** [comment] 2024-04-23 11:55
Looking

**Comment by muttmuure** [comment] 2024-04-23 11:59
Offer is here: https://www.upwork.com/nx/wm/offer/101989533

**Comment by muttmuure** [comment] 2024-04-23 13:16
Paid
