### ISSUE TITLE
[$500] Request money - Merchant field is cleared after changing receipt in confirmation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32123] opened 2023-11-28 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount > choose a participant > proceed to confirmation page.
4. On the confirmation page, click three-dot menu > Add a receipt.
5. Click Merchant and enter a merchant.
6. Click three-dot menu > Add a receipt.

## Expected Result:
The entered Merchant is preserved.

## Actual Result:
The entered Merchant is cleared.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/385c0e53-ce1c-4f70-a568-3d8f9d97d80b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcba32334ea8b85b</li>
        <li>Upwork Job ID: 1729502580706914304</li>
        <li>Last Price Increase: 2023-12-19</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-11-28 14:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money - Merchant field is cleared after changing receipt in confirmation page
### What is the root cause of that problem?
We are resetting the merchant here
https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/libs/actions/IOU.js#L2901-L2902
### What changes do you think we should make in order to solve the problem?

We shouldn't reset merchant the merchant here
https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/libs/actions/IOU.js#L2901-L2902

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-11-30 07:30
Updated [proposal](https://github.com/Expensify/App/issues/32123#issuecomment-1829930741)

**Comment by mollfpr** [comment] 2023-11-30 11:16
I don't have any context regarding the reason we reset the merchant value, but it seems important according to the PR https://github.com/Expensify/App/pull/25924.

Adding a new param for `setMoneyRequestReceipt` gives more flexibility to determine whether we need to reset the merchant value, but for now, I don't think it's necessary.

@Gonals @mountiny Tagging you guys here from https://github.com/Expensify/App/pull/25924. Could you guys help give more context on the reason we reset the `merchant` field for receipt requests?

**Comment by mountiny** [comment] 2023-11-30 14:01
Asking in Slack, its probably because the smartscaning feature expects no merchant provided

**Comment by mountiny** [comment] 2023-11-30 14:30
@mollfpr no reason I think then, lets make sure the merchant is not cleared when receipt is added

**Comment by mollfpr** [comment] 2023-11-30 18:53
@mountiny Is there a problem with intelligent scanning with the merchant having a value?

> lets make sure the merchant is not cleared when receipt is added

Can we safely revert the removed merchant here?

https://github.com/Expensify/App/blob/56a368b07233a78d0a3603b652798d1d86821885/src/libs/actions/IOU.js#L2939-L2941

I notice that from #25924 there's a comment _"For the SmartScan to run successfully, we need to pass the merchant field empty to the API"_, but it's not there anymore.

**Comment by mountiny** [comment] 2023-12-06 11:34
@mollfpr @peterdbarkerUK to confirm, the merchant should not change when receipt is changed

**Comment by mollfpr** [comment] 2023-12-06 15:13
> to confirm, the merchant should not change when receipt is changed

@mountiny Does this mean the SmartScanning will work fine with merchant field fill?

**Comment by mountiny** [comment] 2023-12-10 21:35
We are working on making the merchant field required for group policies/ requests in workspace https://github.com/Expensify/App/pull/32486 so it would not be set to Request thats

cc @trjExpensify to help with the expected behaviour here. 

If the merchant is passed we would not smartscan

If the user inputs some merchant, then we assume they dont want smartscan, if they upload different receipt at the confirmation page though, it should not reset automatically the merchant previously inserted. If the receipt is different and the merchant should be too, they can update it again.

**Comment by mollfpr** [comment] 2023-12-11 15:12
Not overdue

**Comment by mollfpr** [comment] 2023-12-19 13:35
@tienifr Do you need to update your proposal based on the https://github.com/Expensify/App/issues/32123#issuecomment-1849092288?

**Comment by FitseTLT** [comment] 2023-12-19 13:59
@mollfpr It is not reproducible anymore after the recent money request refactor.

**Comment by mollfpr** [comment] 2023-12-20 12:10
Thanks @FitseTLT. I just tested on the latest main, and the issue is fixed.

https://github.com/Expensify/App/assets/25520267/a4369183-a712-4308-a251-20dce6ab8b85

**Comment by trjExpensify** [comment] 2023-12-20 16:02
Same, I can't reproduce this anymore either.

**Comment by mvtglobally** [comment] 2023-12-21 16:15
Issue not reproducible during KI retests. (First week)

**Comment by mollfpr** [comment] 2023-12-23 12:13
@peterdbarkerUK We can close this issue.

**Comment by mountiny** [comment] 2023-12-26 11:34
Sorry for this but happy this got resolved!

**Closed by mountiny** 2023-12-26 11:34 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
