### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Dev: Web - focus lose on click ctrl+shift+k again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27860] opened 2023-09-20 13:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press ctrl+shift+k to open Send message
2. Again click  press ctrl+shift+k

## Expected Result:
Input field should be focused

## Actual Result:
Input field not focused

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.72.4
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8760c6c3-7cc6-44f3-aec0-bc51a759da4b

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694785511995319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ec26b7124d8b07f</li>
        <li>Upwork Job ID: 1704481362907553792</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27118476</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-20 13:04
Linking a recent issue https://github.com/Expensify/App/issues/17482

**Comment by Pluto0104** [comment] 2023-09-20 13:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue is the loss of focus on the web application when pressing Ctrl+Shift+K.
### What is the root cause of that problem?
The root cause of this problem lies in the utilization of `ROUTES.NEW` in our code snippet. When the beta feature is in use, this approach encounters difficulties. Instead, `ROUTES.NEW_CHAT` and `ROUTES.NEW_ROOM` should be employed. This mismatch leads to errors and subsequently results in a loss of focus.
https://github.com/Expensify/App/blob/9533031c7795567392cca0b295212b342c9acdfe/src/libs/Navigation/AppNavigator/AuthScreens.js#L200-L203
### What changes do you think we should make in order to solve the problem?
To resolve this issue, we need to modify the above line of code to appropriately handle scenarios where the beta feature is in use or not.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by garrettmknight** [comment] 2023-09-25 10:41
@sobitneupane either of these proposals look good?

**Comment by sobitneupane** [comment] 2023-09-27 04:43
@gadhiyamanan @garrettmknight I was unable to replicate the issue. Is it still reproducible?

**Comment by Pluto0104** [comment] 2023-09-27 04:47
@sobitneupane this issue is still reproducible under the beta feature. if you don't enable the beta feature, it may be not reproducible.

**Comment by sobitneupane** [comment] 2023-10-03 14:53
> this issue is still reproducible under the beta feature. if you don't enable the beta feature, it may be not reproducible.

Which beta feature are we talking about?

**Comment by Pluto0104** [comment] 2023-10-03 14:55
If you enabled beta feature, RHP might look like this:

![image](https://github.com/Expensify/App/assets/136573674/a3fe411c-06e1-4d55-88ce-9ea9526f62ce)

**Comment by sobitneupane** [comment] 2023-10-04 07:14
> This code was previously removed in this [PR](https://github.com/Expensify/App/pull/16052/files#diff-6a0c8230fa9dade61240f12f0a3d8bb51296cf8eb3a5ff08657c82c8b3f6531b) but looks like there is some bad merge that reintroduced it (most likely from this https://github.com/Expensify/App/pull/16581).

@bernhardoj Why was the code removed in [the linked PR](https://github.com/Expensify/App/pull/16052)?

The code was introduced to tackle https://github.com/Expensify/App/issues/13146 issue. Won't removing the code cause the regression?

**Comment by garrettmknight** [comment] 2023-10-06 17:01
@sobitneupane what do you think?

**Comment by sobitneupane** [comment] 2023-10-09 11:43
Sorry for the delay.

I will try to review the proposals before EOD tomorrow (NPT).

**Comment by it-education-md** [comment] 2023-10-09 11:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue is the loss of focus on the web application when pressing Ctrl+Shift+K.
### What is the root cause of that problem?
The root cause of this problem lies in the utilization of `ROUTES.NEW` in our code snippet. When the beta feature is in use, this approach encounters difficulties. Instead, `ROUTES.NEW_CHAT` and `ROUTES.NEW_ROOM` should be employed. This mismatch leads to errors and subsequently results in a loss of focus.
https://github.com/Expensify/App/blob/9533031c7795567392cca0b295212b342c9acdfe/src/libs/Navigation/AppNavigator/AuthScreens.js#L200-L203

**The regression is caused by https://github.com/Expensify/App/pull/27719.**

**P.S.**
Why is the focus being lost? In this code snippet, we are blurring active elements while navigating, and there is no error before invoking `getMinimalAction`.
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/libs/Navigation/Navigation.js#L90
However, when we invoke the `getMinimalAction` function, an error occurs, preventing us from regaining focus.
https://github.com/Expensify/App/blob/71db96d8a77068220fac73ca0dc984796ff862f9/src/libs/Navigation/linkTo.js#L34

### What changes do you think we should make in order to solve the problem?
To resolve this issue, we need to modify the above line of code to appropriately handle scenarios where the beta feature is in use or not.
```js
const newChatScreenName = Permissions.canUsePolicyRooms(this.props.betas) ? ROUTES.NEW_CHAT : ROUTES.NEW;
if (Navigation.isActiveRoute(newChatScreenName)) {
  return;
}
Navigation.navigate(newChatScreenName);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by sobitneupane** [comment] 2023-10-10 11:42
Thanks for the update @bernhardoj.

Let's go with [your proposal](https://github.com/Expensify/App/issues/27860#issuecomment-1731293883). But we should make sure to include test steps of [the issue](https://github.com/Expensify/App/issues/13146) for which the code was introduced.

[Proposal](https://github.com/Expensify/App/issues/27860#issuecomment-1731293883) from @bernhardoj looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by garrettmknight** [comment] 2023-10-23 19:27
**Summary of payments for this issue:**
- Urgency bonus: Yes
- Reporter: @gadhiyamanan - $50
- Contributor: @bernhardoj  - $750 paid via Upwork
- Reviewer: @sobitneupane - $750

Upwork job: https://www.upwork.com/jobs/~019ec26b7124d8b07f

**Comment by garrettmknight** [comment] 2023-10-23 19:27
@gadhiyamanan offer out to you - accept and I'll pay.

**Comment by gadhiyamanan** [comment] 2023-10-24 05:17
@garrettmknight offer accepted, thanks!

**Comment by garrettmknight** [comment] 2023-10-24 08:53
@sobitneupane please complete the checklist and request payment.

**Comment by sobitneupane** [comment] 2023-10-30 10:36
> BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]   [@sobitneupane ] The PR that introduced the bug has been identified. Link to the PR:

The change resulting this issue was introduced by https://github.com/Expensify/App/pull/14048 PR which was later removed by https://github.com/Expensify/App/pull/16052 PR. But was later reintroduced probably due to some merge conflicts.

> * [ ]   [@sobitneupane ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

> * [ ]   [@sobitneupane ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

There are multiple PRs involved. As this feature was newly introduced, probably shortcuts were not tested.
> * [ ]   [@sobitneupane ] Determine if we should create a regression test for this bug.

Yes.
> * [ ]   [@sobitneupane ] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 10:37
**Regression Test Proposal**

- Press CTRL+K
- Verify a new chat opens with the search input focused
- Press CTRL+K once again
- Verify the search input is still focused

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-30 14:02
https://github.com/Expensify/App/issues/27860#issuecomment-1775883874

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-11-03 22:23
$750 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/27860#issuecomment-1775883874).

**Comment by garrettmknight** [comment] 2023-11-06 21:26
All set, closing.

**Closed by garrettmknight** 2023-11-06 21:26 UTC
Labels: External, Weekly, Awaiting Payment
