### ISSUE TITLE
[HOLD for payment 2023-07-03] [HOLD for payment 2023-06-30] props.onPress is not a function

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#21339] opened 2023-06-22 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open your browser console
2. Click on a blank part of a message
3. Notice the following error:

![Screenshot 2023-06-22 at 12 41 28 PM](https://github.com/Expensify/App/assets/22219519/4352a1c6-1da1-45bf-befa-fc3535f20757)

## Expected Result:
No errors

## Actual Result:
There's an error and a non-fatal crash on mobile

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ff5c50cd9371bae</li>
        <li>Upwork Job ID: 1671955628124135424</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-06-22 19:03
PR up

**Comment by abdulrahuman5196** [comment] 2023-06-22 19:06
Thank you. Taking a look

**Comment by abdulrahuman5196** [comment] 2023-06-29 10:26
BZ checklist:

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I don't think we can say one PR causing this, the causes are that the `onPress` had undefined as default value as part of the Pressable migration and the component using this didn't provide onPress props and the component was also not click disabled, causing this issue.

>A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

https://expensify.slack.com/archives/C049HHMV9SM/p1688034234824719

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. This is a minor issue and a regression test won't be benifical for this case.


@laurenreidexpensify  just to note. The end of regression date is 30/6 not 3/7, this change must have deployed twice to cause wrong issue title.

**Comment by laurenreidexpensify** [comment] 2023-07-03 11:33
Thanks @abdulrahuman5196 - offer is ready in Upwork, will issue payment once you accept and we can close this out

**Comment by abdulrahuman5196** [comment] 2023-07-03 11:38
Thank you @laurenreidexpensify accepted the offer.

**Comment by laurenreidexpensify** [comment] 2023-07-04 07:59
Payment has been issued :)

**Closed by laurenreidexpensify** 2023-07-04 07:59 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
