### ISSUE TITLE
[Awaiting Payment 4th Sept] NetSuite - "Custom segment" text is displayed for an added custom record

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46540] opened 2024-07-30 20:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segment/record" button
10. Add a Custom record with any random data

## Expected Result:
The text should be "Custom record"

## Actual Result:
"Custom segment" text is displayed for an added custom record.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8432506e-6163-4280-b841-d3e4eaac6a5f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-30 20:30
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by rushatgabhane** [comment] 2024-07-31 18:47
cc @shubham1206agra ?

**Comment by trjExpensify** [comment] 2024-08-01 00:21
Can we get this assigned to who implemented it to fix it? CC: @zsgreenwald

**Comment by trjExpensify** [comment] 2024-08-01 22:28
Cool, so the push row should take the same approach we have with the page title and description. 

E.g 

```
Custom segment / record
1234                                >
```

CC: @jamesdeanexpensify this is what it looks like now:

<img width="466" alt="image" src="https://github.com/user-attachments/assets/0ac0595a-3938-4a47-b046-29a9b4d264ba">

**Comment by jamesdeanexpensify** [comment] 2024-08-01 22:39
sounds good!

**Comment by trjExpensify** [comment] 2024-08-02 14:54
Cool, @shubham1206agra want to take it?

**Comment by trjExpensify** [comment] 2024-08-08 13:17
Any movement?

**Comment by trjExpensify** [comment] 2024-09-03 16:32
Automation failed, due for payment tomorrow. Updated the labels/titles, and added @Ollyws as the C+ reviewer.

**Comment by trjExpensify** [comment] 2024-09-05 00:24
Payment summary as follows: 

- $125 to @shubham1206agra for the fix 
- $125 to @Ollyws for the C+ review 

(dropped the price for some copy changes)

**Comment by trjExpensify** [comment] 2024-09-05 00:26
@Ollyws go ahead and request on ND, @shubham1206agra can you confirm if you've been paid for the NS implementation elsewhere?

**Comment by trjExpensify** [comment] 2024-09-05 01:15
Care to expand a touch on why? Fixing the copy of a label during implementation of the project I'd have thought is just par for the course. 😕

**Comment by yuwenmemon** [comment] 2024-09-05 05:33
@shubham1206agra Yeah, I'd consider this a regression from your implementation as opposed to, say, your work in https://github.com/Expensify/App/issues/47493, which would be adding additional improvements to the NetSuite integration project. Plenty of NetSuite and integrations work still to be done though and you're one of the best suited C+ for it 🙂

**Comment by trjExpensify** [comment] 2024-09-05 12:03
Great, I'm going to close this then. Thanks!

**Closed by trjExpensify** 2024-09-05 12:03 UTC
Labels: Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-11 19:17
$125 approved for @Ollyws
