### ISSUE TITLE
[Payment due Sept 6] [$250] Search - Expense page composer loses bottom margin when going offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#46404] opened 2024-07-29 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** bezawitgebremichael+11221122@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team
*

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create an expense
3. Go to search
4. Click on an expense from the expense list
5. Go offline

## Expected Result:
There will be an offline indicator under the composer and the composer will have a bottom margin

## Actual Result:
The composer does not have a bottom margin and there is no offline indicator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/88c9f63f-9e93-40f1-835a-1f67370b3b37

![Bug6554985_1722117881426!Screenshot_1](https://github.com/user-attachments/assets/2bfebfa1-97b9-4688-8caa-aae049a9d0f6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a491780ac50be9ec</li>
        <li>Upwork Job ID: 1817922651827967932</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by izarutskaya** [comment] 2024-07-29 11:30
Production

https://github.com/user-attachments/assets/41d6347a-5f00-4f5a-9979-9c423e5965ad

**Comment by bernhardoj** [comment] 2024-07-29 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Composer bottom spacing is gone when turn offline in report RHP page.

### What is the root cause of that problem?
This happens after we replace `isSmallScreenWidth` usage with `shouldUseNarrowLayout`.
https://github.com/Expensify/App/blob/3722b22302e5d89f2916d5e8958b2cf17ecb6285/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L496-L504

The `chatItemComposeSecondaryRow` style contains the spacing. `shouldUseNarrowLayout` is true in RHP and when we go offline, both of the conditions become false, so the spacing is gone.


### What changes do you think we should make in order to solve the problem?

Use the previous condition by relying on `isSmallScreenWidth`.
```
(!isSmallScreenWidth || (isSmallScreenWidth && !isOffline)) && styles.chatItemComposeSecondaryRow,
```

The reason we have this style in composer is that in ScreenWrapper, we have an offline indicator that is shown only on a small screen. However, we still want to show the offline indicator for the report screen, whether large or small screen, because it's the central screen.

`!isSmallScreenWidth` makes sure the spacing is always available on the large screen. `(isSmallScreenWidth && !isOffline)` allows the spacing to show on the small screen, but only when online (if we show it while offline too, then there will be extra space from the ScreenWrapper offline indicator).

**Comment by Siraj01576** [comment] 2024-07-29 16:10
# Proposal

## Problem Description
There is an issue in the project where the container intended to display the online/offline status is not showing correctly. Specifically, instead of indicating the offline status, the container is being displayed as `none`.

## Issue
There is no margin defined.
Instead of showing the status as offline, the container is being displayed as none.

## Solution
The issue can be resolved by ensuring the container correctly shows the online/offline status.

## Current Implementation
The relevant `div` element in the `ReportActionCompose.tsx` file is structured as follows:

```html
<div data-element="View" data-source-file="ReportActionCompose.tsx" class="css-175oi2r" style="flex-direction: row; justify-content: space-between; align-items: center; height: 15px; margin-bottom: 5px; margin-top: 5px;"></div>

**Comment by Siraj01576** [comment] 2024-07-29 16:13
# Proposal

## Problem Description
There is an issue in the project where the container intended to display the online/offline status is not showing correctly. Specifically, instead of indicating the offline status, the container is being displayed as `none`.

## Issue
There is no margin defined.
Instead of showing the status as offline, the container is being displayed as none.

## Solution
The issue can be resolved by ensuring the container correctly shows the online/offline status.

## Current Implementation
The relevant `div` element in the `ReportActionCompose.tsx` file is structured as follows:

```html
<div data-element="View" data-source-file="ReportActionCompose.tsx" class="css-175oi2r" style="flex-direction: row; justify-content: space-between; align-items: center; height: 15px; margin-bottom: 5px; margin-top: 5px;"></div>

**Comment by Siraj01576** [comment] 2024-07-29 16:14
# Proposal

## Problem Description
There is an issue in the project where the container intended to display the online/offline status is not showing correctly. Specifically, instead of indicating the offline status, the container is being displayed as `none`.

## Issue
There is no margin defined.
Instead of showing the status as offline, the container is being displayed as none.

## Solution
The issue can be resolved by ensuring the container correctly shows the online/offline status.

## Current Implementation
The relevant `div` element in the `ReportActionCompose.tsx` file is structured as follows:

```html
<div data-element="View" data-source-file="ReportActionCompose.tsx" class="css-175oi2r" style="flex-direction: row; justify-content: space-between; align-items: center; height: 15px; margin-bottom: 5px; margin-top: 5px;"></div>

**Comment by Siraj01576** [comment] 2024-07-29 16:47
Contributor details
Your Expensify account email: sirajkhatti14@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018a3960cdaa518f4e

**Comment by mananjadhav** [comment] 2024-07-30 18:30
Hmm I tried reviewing the proposals but if this isn't reproducible on production, we should treat this as a regression right? @carlosmiceli I don't see any comment on why this isn't a deploy blocker? If not alteast we should solve with the original issue?

@bernhardoj Are you aware which PR must've called this.

**Comment by bernhardoj** [comment] 2024-07-31 01:20
It's from https://github.com/Expensify/App/pull/43961/

**Comment by mananjadhav** [comment] 2024-08-01 19:17
Still checking between both the proposals. I am not sure if we should introduce `isSmallScreenWidth` again. Will review and update by tomorrow.

**Comment by bernhardoj** [comment] 2024-08-02 02:26
The ScreenWrapper uses `isSmallScreenWidth`, so we need to match the condition.

https://github.com/Expensify/App/blob/157afbf7720049e3b0a92836b440c35f17725c10/src/components/ScreenWrapper.tsx#L282

`isSmallScreenWidth` isn't 100% replaceable with `shouldUseNarrowLayout`. We use `isSmallScreenWidth` in this [commit](https://github.com/Expensify/App/commit/29178725d6f119d8fe7fbcb84305fddea09d6c90) too.

**Comment by mananjadhav** [comment] 2024-08-03 19:19
Both the proposals solutions work. 

Based on what I see in the linked PR and the changes related to useResponsiveLayout, I feel we should stick to using `isSmallScreenWidth`.  This is because the `ScreenWrapper` still uses isSmallScreenWidth and I don't see this being changed. 

But before we confirm I'd like to do a quick buddy check with @rayane-djouah as they worked on the previous PR.

🎀 👀 🎀 C+ reviewed.

**Comment by carlosmiceli** [comment] 2024-08-07 21:41
Which proposal are we going with then?

**Comment by isabelastisser** [comment] 2024-08-08 14:44
@mananjadhav @rayane-djouah, please share an update. Thanks!

**Comment by mananjadhav** [comment] 2024-08-08 15:08
> In my opinion, since we don't display the offline indicator in RHP/LHP anywhere in the app—because there is already one in the central pane—we should not show the offline indicator in the composer when in RHP.

@Expensify/design Do you have any feedback on this comment?

**Comment by shawnborton** [comment] 2024-08-08 15:10
I don't feel too strongly because that offline indicator is faded out in the BG. So I don't think it would be a bad thing if the RHP composer had the offline message below it either.

**Comment by dannymcclain** [comment] 2024-08-08 15:13
>I don't feel too strongly because that offline indicator is faded out in the BG. So I don't think it would be a bad thing if the RHP composer had the offline message below it either.

I feel pretty similarly to Shawn. Could go either way here. I can definitely see a case for displaying the offline indicator underneath _any_ composer, whether it shows up in the RHP or the central pane.

**Comment by isabelastisser** [comment] 2024-08-12 20:01
@mananjadhav, what's next here? Thanks!

**Comment by carlosmiceli** [comment] 2024-08-12 20:01
Let's see if @mananjadhav has all the info he needs 💪

**Comment by isabelastisser** [comment] 2024-08-14 14:30
@mananjadhav, I DM'd you for visibility.

**Comment by mananjadhav** [comment] 2024-08-14 17:18
I was OOO, I'll review this today.

**Comment by carlosmiceli** [comment] 2024-08-19 18:56
How are we looking here @mananjadhav ?

**Comment by mananjadhav** [comment] 2024-08-20 14:51
Based on the [comment](https://github.com/Expensify/App/issues/46404#issuecomment-2267168279) here and the review of the proposals I still feel we should use `isSmallScreenWidth`. Hence @bernhardoj's [proposal](https://github.com/Expensify/App/issues/46404#issuecomment-2255896564) looks good to me.

But @bernhardoj as mentioned please import it from `useResponsiveLayout` and not `useWindowDimensions`.

**Comment by carlosmiceli** [comment] 2024-08-20 15:06
Let's wait for @bernhardoj to confirm and I'll assign, thanks @mananjadhav :)

**Comment by bernhardoj** [comment] 2024-08-20 15:24
> please import it from useResponsiveLayout and not useWindowDimensions.

useResponsiveLayout is already imported into the file, so we will use it.

**Comment by carlosmiceli** [comment] 2024-08-24 01:02
Should I assign you @bernhardoj ?

**Comment by bernhardoj** [comment] 2024-08-24 02:07
Yes, please

**Comment by bernhardoj** [comment] 2024-08-24 04:25
PR is ready

cc: @mananjadhav

**Comment by isabelastisser** [comment] 2024-08-27 00:26
It looks like PR is still open. Waiting!

**Comment by mananjadhav** [comment] 2024-09-04 17:12
This was deployed to production 5 days ago. This should be ready for payout by 09/06.

**Comment by isabelastisser** [comment] 2024-09-04 17:27
Thanks for the update!

**Comment by mananjadhav** [comment] 2024-09-08 20:46
We linked the offending PR [here](https://github.com/Expensify/App/issues/46404#issuecomment-2259453814) but this is more of an edge case. We still use the `isSmallScreenWidth`.

Also I think we don't need a regression test for this one. @carlosmiceli wdyt?

@isabelastisser This is ready for payout. Can you please post a payout summary for this one?

**Comment by carlosmiceli** [comment] 2024-09-09 16:01
@mananjadhav Yeah, no need for regression test here!

**Comment by isabelastisser** [comment] 2024-09-09 18:41
Payment summary:

@mananjadhav, $250 for C+ review. Payment via NewDot
@bernhardoj, $250 for Contributor proposal - offer sent via Upwork. Pending payment.

**Comment by isabelastisser** [comment] 2024-09-09 19:52
All set!

**Closed by isabelastisser** 2024-09-09 19:52 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by bernhardoj** [comment] 2024-09-10 03:13
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-10 09:30
$250 approved for @bernhardoj

**Comment by garrettmknight** [comment] 2024-09-11 19:19
$250 approved for @mananjadhav
