### ISSUE TITLE
[$500] IOU Distance - App displays 'Hmm its not here' for default waypoint links for first time after login

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27572] opened 2023-09-15 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open plus and click request money
3. Click on distance and click on start/finish
4. Copy the URL and send to any chat
5. Select any addresses for start and finish and click next
6. Copy the the URL and send to same chat as step 4
7. logout and login again with same user
8. Open chat open in step 4
9. Click on waypoint link and observe that app doesn't handle that link properly and displays 'Hmm its not here' page
10. Click on participant page and observe that app redirects to request money page which is correct way of handling such links

## Expected Result:
App should redirect back to request money page if we try to open waypoint link first time after login as it does for other similar links like participant link

## Actual Result:
App displays 'Hmm its not here' for default waypoint links for first time after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5f9bded7-e2f0-4117-a800-b462c698767f

https://github.com/Expensify/App/assets/78819774/5c10f0d5-b6d3-42da-abf6-9eba09c88ab4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694595781503769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0165405184ecd0395e</li>
        <li>Upwork Job ID: 1702826813110902784</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 00:46
Looks like this issue was created twice: https://github.com/Expensify/App/issues/27571

**Comment by dhanashree-sawant** [comment] 2023-09-16 05:09
Actually if you see #27571 slack link, it was a different issue, ideally, that can closed leaving this open

**Comment by akinwale** [comment] 2023-09-16 05:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App displays 'Hmm... it's not here' for default waypoint links for the first time after login.

### What is the root cause of that problem?
At the point when the link is clicked immediately after login, the `waypointCount` is 0, and the `FullPageNotFoundView` is displayed when this condition is met.

https://github.com/Expensify/App/blob/76c1559fb3fbee1d07c8f210b522b63edd03920e/src/pages/iou/WaypointEditor.js#L166

### What changes do you think we should make in order to solve the problem?
Similar to the participants page, add a `useEffect` hook in the WaypointEditor to navigate back to the distance request page when `waypointCount` is 0. We can optionally set the force fallback parameter to true.

```
useEffect(() => {
    if (waypointCount === 0) {
        Navigation.goBack(ROUTES.getMoneyRequestDistanceTabRoute(iouType), true /* optional */);
    }
}, [waypointCount]);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment] 2023-09-16 05:20
> Actually if you see #27571 slack link, it was a different issue, ideally, that can closed leaving this open

Copying my proposal here just in case.

**Comment by akinwale** [comment] 2023-09-16 10:01
> @akinwale The Root cause is very unclear. Can you explain it? Also, the
> 
> > Please re-state the problem that we are trying to solve in this issue.
> 
> Expects your understanding of the issue, not the title to be reposted.

@parasharrajat I posted my proposal at 1am in the morning running on very little sleep. I've updated it to be more detailed.

**Comment by jeet-dhandha** [comment] 2023-09-16 10:36
@parasharrajat please give a quick look to my proposal if possible.

**Comment by poonam286** [comment] 2023-09-16 12:33
Hi i want help with this

**Comment by codesmith922** [comment] 2023-09-16 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Actual: App displays 'Hmm its not here' for default waypoint links for first time after login.
Expected: We expect the waypoint page to be opened where the user can select address. 
My understanding: I think we should keep it simple and not complicate the user flow or code logic. We should navigate to the  distance request page whenever we have some data missing in any of the user flows inside distance request. So, we should navigate to distance request page whether waypoint link or participants link is shared. 

### What is the root cause of that problem?

Transaction is not initialized when the waypoint link is opened directly from link on first login. As a result, we fallback to FullPageNotFoundView component. The logic is as below - 

` <FullPageNotFoundView shouldShow={(Number.isNaN(parsedWaypointIndex) || parsedWaypointIndex < 0 || parsedWaypointIndex > waypointCount - 1) && isFocused}> `

### What changes do you think we should make in order to solve the problem?
We should navigate back to distance request page if transaction is not initialized and waypoint link is opened.

### What alternative solutions did you explore? (Optional)
An alternative option is to create an empty transaction in case the transaction is missing and the user has opened waypoints link directly. But, I feel this will be an over-engineered solution. 
Also, in terms of user flow, if the user is taken back to base page in case of opening a /participants link, then we should do the same for /waypoints link to keep it consistent.

**Comment by codesmith922** [comment] 2023-09-16 13:17
Contributor details
Your Expensify account email: codesmith922@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01570752db7999b850

**Comment by poonam286** [comment] 2023-09-16 14:06
Hi Can i work on this task now ?

**Comment by imranaalam** [comment] 2023-09-16 14:13
---

**Problem Statement:**  
Upon logging in and navigating to the `/request/new/waypoint/0` path in Expensify's app, the user encounters the "Hmm...its not here" page. Ideally, they should be directed to the waypoint page to select an address.

**Root Cause:**  
Within the Expensify app, the transaction isn't initialized when the user accesses the waypoint link right after logging in. This results in no available waypoints, which triggers the error display condition in the `FullPageNotFoundView` component.

**Proposed Solution:**

**Just-In-Time Initialization with Redirect (JITIR)**:
1. Upon user's attempt to access a waypoint link directly after login within Expensify's app, check the transaction state.
2. If uninitialized, employ a "Just-In-Time" strategy to initialize the transaction and redirect the user to the 'request money' page.
3. This approach ensures that users, while navigating Expensify, will always find the necessary transaction and waypoints ready when they access the waypoint editor from the 'request money' page.

**Implementation**:
```javascript
// Within the Expensify app, when a user tries to navigate to the waypoint page
if (path === '/request/new/waypoint/0') {
    
    // Check the transaction's initialization state
    if (!transactionInitialized) {
        IOU.createEmptyTransaction();
        Transaction.createInitialWaypoints(transactionID);
        
        // Guide the user to the 'request money' page within Expensify
        Navigation.navigate(ROUTES.REQUEST_MONEY);
    }
}
```

**Pros**:  
- **Resource Efficiency**: Only initializes resources when demanded, optimizing performance within Expensify.
- **User Experience**: Offers a consistent navigation experience across the app.

**Cons**:  
- **Possible Redirection**: Users might find the redirection unexpected if they aim to land directly on the waypoint page.

---

**Alternative Solution:**

**Dynamic Resource Allocation with User Feedback (DRAUF)**:
1. If a user, post-login, tries to access the waypoint link in Expensify and the transaction isn't initialized, show a feedback message or loader: "Setting things up for you..."
2. Behind the scenes, dynamically allocate resources to initialize the transaction and waypoints.
3. Once the resources are set, automatically guide the user to the waypoint editor, ensuring a fluid navigation experience.

```javascript
// In the context of Expensify, when a user tries accessing the waypoint page
if (path === '/request/new/waypoint/0' && !transactionInitialized) {
    
    // Display a user-friendly feedback
    DisplayMessageOrLoader("Setting things up for you...");

    // Initialize the transaction and waypoints dynamically
    IOU.createEmptyTransaction();
    Transaction.createInitialWaypoints(transactionID);

    // Once ready, redirect to the waypoint editor within the app
    Navigation.navigate(ROUTES.WAYPOINT_EDITOR);
}
```

**Pros**:  
- **User Feedback**: Keeps users informed about background processes, enhancing user experience in Expensify.
- **Fluid Experience**: Creates resources on-the-go, providing a seamless experience.

**Cons**:  
- **Implementation Complexity**: Introducing dynamic resource allocation with feedback might add complexity to the app's codebase.
- **Dependency**: Relies heavily on a responsive feedback system.

---

the concepts of "Just-In-Time Initialization" (JIT) and "Dynamic Resource Allocation" (DRA) describe strategies for on-demand resource allocation or initialization, enhancing performance and user experience. Such strategies can be particularly beneficial for apps like Expensify to maintain fluidity and responsiveness.

**Comment by Pujan92** [comment] 2023-09-16 14:19
Isn't this expected behaviour bcoz when a user comes out of the Distance flow we are clearing the waypoints data, so when user tries to access the direct waypoint editor page we should show the NotFound page?

**Comment by imranaalam** [comment] 2023-09-16 14:26
> Isn't this expected behaviour bcoz when a user comes out of the Distance flow we are clearing the waypoints data, so when user tries to access the direct waypoint editor page we should show the NotFound page?

@dhanashree-sawant @parasharrajat would you agree with following?


---

Yes, you're right. Based on the current design and logic of the application, if the waypoints data is cleared when a user exits the Distance flow, then attempting to access the waypoint editor page directly afterwards would naturally result in missing data. Therefore, showing the "NotFound" page in this scenario makes sense as a way to handle unexpected or incorrect navigation.

However, from a user experience perspective, it might be more intuitive if the application provides a clearer message or redirects the user back to the start of the Distance flow. This way, users can understand the context of why they are seeing the "NotFound" page and can take appropriate actions rather than being left confused.

**Comment by NimaC** [comment] 2023-09-16 16:22
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Deeplink to `/request/new/waypoint/0` Tab causes `FullPageNotFoundView` to be rendered after fresh login

## What is the root cause of that problem?
transactionID and other props are not set, because deeplinking to the WaypointEditor View was not intended.

## What changes do you think we should make in order to solve the problem?
Redirect to Distance Tab Route if transactionID is not set

## What alternative solutions did you explore? (Optional)
None

**Comment by NimaC** [comment] 2023-09-16 16:24
Contributor details
Your Expensify account email: nima.chizari@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01812ef38a798441d4

**Comment by dhanashree-sawant** [comment] 2023-09-18 04:23
Agree with @imranaalam, users can actually visit other pages like confirmation and we redirect them to step 1 of request money, ideally if any user tries to access further step pages, its ideal to redirect them back to step 1 rather then providing 'Hmm its not here' page.

**Comment by NicMendonca** [comment] 2023-09-21 20:54
@parasharrajat what do you think we should do next here?

**Comment by imranaalam** [comment] 2023-09-22 11:19
@parasharrajat @NicMendonca

As always, diving deep into such issues has revealed the complexity and nuances that need to be addressed for a more generic solution. Crafting a truly comprehensive remedy, especially one that is generic and applicable across the platform, would demand significantly more effort and resources.

While I've taken the time to propose a viable solution, I'd like to notify you that I won't be available to implement this solution personally. Given the depth of the work and the intricacies involved, I believe the bounty should be reconsidered and possibly increased to attract the right talent that can deliver a robust fix.

Alternatively, if increasing the bounty isn't feasible, this issue might be better suited for internal handling. After all, it touches on core functionalities and navigation flows which are fundamental to the user experience.

Lastly, if resource constraints are pressing, a temporary fix might be applied to address the immediate concern. However, I'd advocate for not "hiding it under the bed" for too long as it might lead to more complex issues in the future.

It's also worth noting that contributors who invest time and effort to steer the project in the right direction should perhaps be acknowledged in some policy or system. This ensures that valuable insights and solutions aren't lost simply because the original contributor couldn't see the solution through to implementation.

Given the feedback, it's clear that a more holistic approach is required to handle direct accesses to pages nested within a specific flow. Here's a proposed approach:

---

**Problem Statement:**  
Direct access to pages nested within a specific flow leads to missing context and data. The result is non-intuitive user experiences, such as the "Hmm its not here" page.

**Root Cause:**  
Pages within specific flows, like the waypoint editor, expect certain contextual data to be present (like waypoints). Directly accessing these pages without going through the preceding steps of the flow can lead to this data being absent.

**Proposed Solution:**

**Flow-Based Redirect System (FBRS)**:

1. **Flow Metadata**: Attach metadata to each page or route that indicates its position within a specific flow. For example, the waypoint editor might have metadata indicating it's the 3rd step in the Distance flow.
2. **Context Checker**: Before rendering a page, check if the required context and data for that page are present. This is determined based on its metadata and the expected state of the app.
3. **Redirect Logic**: If the required context and data are missing, redirect the user to the beginning of the flow. For example, if someone directly accesses the waypoint editor (3rd step), but the required waypoints data isn't present, redirect them to the 1st step of the Distance flow.

**Implementation**:
```javascript
// For each route or page in the app
if (currentRoute.hasFlowMetadata && !currentRoute.hasRequiredContext()) {
    Navigation.navigate(currentRoute.flowStart);
}
```

**Pros**:  
- **Generality**: This approach isn't tied to a specific flow or page but can be applied across the app.
- **User Experience**: Ensures users always start flows from the beginning, reducing confusion and errors.
- **Flexibility**: Easily adaptable to add new flows or modify existing ones.

**Cons**:  
- **Implementation Overhead**: Initial setup requires adding metadata to routes and defining the required context for each.
- **Performance**: The context checker runs every time a page is accessed, potentially adding a slight delay.

**Alternative Solution:**

**Flow State Management (FSM)**:
1. **Flow States**: Define distinct states for each flow in the app. Each state encompasses the necessary data and context required for a specific step in the flow.
2. **State Restoration**: If a user tries to access a step directly, the app attempts to restore the state for the preceding steps. If it can't, it redirects the user to the beginning of the flow.
3. **Persistent Storage**: Store the state of each flow in a persistent storage (like local storage). This ensures even if a user exits and returns, the context is maintained.

**Pros**:  
- **Data Persistence**: Maintains user progress within flows, enhancing user experience.
- **Direct Access**: Allows for direct access to nested pages while ensuring the necessary context is available.

**Cons**:  
- **Complexity**: Requires a sophisticated state management system.
- **Storage Overhead**: Storing flow states persistently can increase the storage demands of the app.

---

Given the feedback, the Flow-Based Redirect System (FBRS) offers a more generic solution suitable for Expensify. It ensures that any direct accesses to nested pages are handled gracefully by redirecting users to the beginning of the respective flow.

---

I'd like to take a moment to extend our heartfelt thanks to @dhanashree-sawant for uncovering this critical bug. Her keen observation and diligence in identifying the issue have been instrumental in bringing it to the forefront.

It's evident that @dhanashree-sawant is not just a bug finder but a pro at it. Her expertise and commitment to ensuring the quality of the application shine through her contributions. It's always a privilege to have contributors like her who consistently push for excellence and make the platform better for all users.

Thanks again, @dhanashree-sawant! Your efforts are greatly appreciated.

**Comment by NicMendonca** [comment] 2023-09-26 14:21
@parasharrajat do I need to adjust price here?

**Comment by NicMendonca** [comment] 2023-10-02 14:59
Waiting for Wednesday when @parasharrajat is back!

**Comment by mvtglobally** [comment] 2023-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment] 2023-10-05 20:49
ohhhh ^

**Comment by jeet-dhandha** [comment] 2023-10-08 14:39
https://expensify.slack.com/archives/C01GTK53T8Q/p1695209109095579 - Seems like this one

**Comment by NicMendonca** [comment] 2023-10-12 19:28
@parasharrajat bump ^^

**Comment by NicMendonca** [comment] 2023-10-16 14:35
@parasharrajat any update on next steps here?

**Comment by NicMendonca** [comment] 2023-10-20 19:57
bumped: https://expensify.slack.com/archives/C02NK2DQWUX/p1697831843955809

**Comment by NicMendonca** [comment] 2023-10-26 20:51
@lanitochka17 is this still reproducible?

**Comment by NicMendonca** [comment] 2023-10-31 21:49
@parasharrajat bumped you again!

**Comment by NicMendonca** [comment] 2023-11-02 19:15
bumped here: https://expensify.slack.com/archives/C02NK2DQWUX/p1698952519248639?thread_ts=1697831843.955809&cid=C02NK2DQWUX

**Comment by NicMendonca** [comment] 2023-11-13 13:54
@parasharrajat update please

**Comment by NicMendonca** [comment] 2023-11-20 23:21
@parasharrajat does that mean we should hold for https://github.com/Expensify/App/issues/26538?

**Comment by NicMendonca** [comment] 2023-11-24 14:43
I am going to close this in favour of seeing what happens here: https://github.com/Expensify/App/issues/26538

We'll reopen later/ once ^^ is completed.

**Closed by NicMendonca** 2023-11-24 14:43 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
