### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] An overlapped skeleton UI in the payment details section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19442] opened 2023-05-23 13:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on FAB icon
2. Click on 'Send money'
3. Enter amount & click on 'Next' button
4. Search user
5. Select user
6. Click on 'I will settle up elsewhere' button
7. Click on settled up message
8. Click on the sent money preview component

## Expected Result: 
The rows of the skeleton UI shouldn't be overlapped
## Actual Result: 
The rows of the skeleton UI are overlapped
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
  
**Version Number:** 1.3.17
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Annotation 2023-05-19 152438](https://github.com/Expensify/App/assets/43996225/65fda98d-9157-48ae-a203-6b3a82eed62b)

https://github.com/Expensify/App/assets/43996225/1be061cc-385a-46b8-bdd4-343ac95b8496

https://github.com/Expensify/App/assets/43996225/8aecee92-80a5-4e5a-9fcd-d332370fdd5f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684499328591959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faa2727c8013d2a4</li>
        <li>Upwork Job ID: 1661352382463225856</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-23 14:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An overlapped skeleton UI in the payment details section
### What is the root cause of that problem?
The problem came from here:
https://github.com/Expensify/App/blob/b424edcbe7cea7ed5fe36bc5602f6eb4ed1d78bf/src/components/ReportActionsSkeletonView/index.js#L20
When the header view of request money takes a lot of space, Math.celi return a greater number, which make the remaining space couldn't be enough for all the skeleton.
### What changes do you think we should make in order to solve the problem?
Instead of using Math.celi, we should use Math.floor to calculate the number of skeleton lines.

### What alternative solutions did you explore? (Optional)
N/A.

**Comment by bernhardoj** [comment] 2023-05-24 13:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The skeleton is overlapping in chat page. This is easily noticeable when the height of the chat is small.

### What is the root cause of that problem?
I have encountered the same issue while creating a skeleton loader for LHN [here](https://github.com/Expensify/App/pull/14456#issuecomment-1451145326). There is an explanation why that happen, but in short, the problem happens because the total height of all skeleton item is bigger than the height of it's container and we are using flex 1 in the container. (Removing the flex 1 will solve the overlap, but will push down the footer)

### What changes do you think we should make in order to solve the problem?

We can use the same solution [here](https://github.com/Expensify/App/pull/14456/commits/4abf178e4cc5b10889195ed29d69a33cf975d7e1) which is to wrap the skeleton with a plain `View` here.
https://github.com/Expensify/App/blob/5cb2b745c52cedb0fd7ae64c0c438953a7d952b0/src/components/ReportActionsSkeletonView/index.js#L53

This will allow the skeleton to overflow.

**Comment by s77rt** [comment] 2023-05-24 20:55
@hungvu193 Thanks for the proposal. Your RCA makes sense but I think it's intended to use ceil and round up to the closest integer. Otherwise we will see empty space.

**Comment by s77rt** [comment] 2023-05-24 21:07
@bernhardoj Thanks for the proposal. Your RCA makes sense as well. Wrapping the skeletonview with a View looks good to me. However I have a question, I can reproduce the bug just for a brief period (or when offline) where the scrollbar is not visible. Then once getting back online the scrollbar is visible and no overlap is seen in this case. Any idea what is that about?

Even if we wrap the skeletonview within a View you will still notice that the scrollbar is missing.


| Offline | Online |
|--------|-------|
|  <img src="https://github.com/Expensify/App/assets/16493223/7b37a5b0-e334-40c4-9868-f5c2a45f8283" />    |  <img src="https://github.com/Expensify/App/assets/16493223/37775833-5ea0-4985-95b2-a9d21c7cf6d2" />     |

**Comment by bernhardoj** [comment] 2023-05-25 04:13
That's weird. The skeleton shouldn't be scrollable because the overflow is hidden. I'm guessing the skeleton you see when back online is from the footer of `ReportActionsList`. https://github.com/Expensify/App/blob/7a42755a79737314edf702ce17bf0647dd8c41fb/src/pages/home/report/ReportActionsList.js#L159-L178

**Comment by hungvu193** [comment] 2023-05-25 07:06
> @hungvu193 Thanks for the proposal. Your RCA makes sense but I think it's intended to use ceil and round up to the closest integer. Otherwise we will see empty space.

We can wrap the skeleton with View and use justify content center, we can reduce the space and it looks just ok.

https://github.com/Expensify/App/assets/16502320/8f8b19ce-e606-4c61-ab9c-5e269c9918c7

**Comment by s77rt** [comment] 2023-05-25 10:35
@bernhardoj Thanks for the quick follow up. That seems unrelated to this issue. Let's go with your solution :rocket:.

:ribbon: :eyes: :ribbon: C+ reviewed

cc @dangrous

**Comment by dangrous** [comment] 2023-05-25 15:24
Yep this looks good to me!

**Comment by conorpendergrast** [comment] 2023-05-25 16:23
Hired everyone via Upwork 👍

**Comment by conorpendergrast** [comment] 2023-05-26 13:49
PR is reviewed, merged and on Staging

**Comment by s77rt** [comment] 2023-05-30 00:45
- The PR that introduced the bug has been identified: This seems to be an issue that existed since day one https://github.com/Expensify/App/pull/8042
- The offending PR has been commented on: https://github.com/Expensify/App/pull/8042#discussion_r1209606444
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1685407519069379
- Determine if we should create a regression test for this bug: No

**Comment by dangrous** [comment] 2023-06-02 18:28
Hm @shawnborton what do you think? For payment details chats, should the skeleton UI be aligned to the bottom (like the chats actually show up) or to the top (like other chats)? Could sort of go either way.

**Comment by shawnborton** [comment] 2023-06-05 07:09
I don't feel strongly either, I would say let's just be consistent with what we do with other chats.

**Closed** 2023-06-07 12:30 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by dangrous** [comment] 2023-08-15 20:58
Oops, I never actually made the issue. To confirm the plan - @shawnborton - Should I create an issue to make the payment details skeleton UI aligned to the top to match how we see other chats?

**Comment by shawnborton** [comment] 2023-08-16 00:24
I guess at this point a payment details view is just a thread, and a thread is just another kind of chat. So yeah, whatever we do with other chats, we should be consistent with the payment details. Let me know if that's helpful!

**Comment by dangrous** [comment] 2023-08-16 20:38
See linked issue!
