### ISSUE TITLE
[$250] BUG: Sage Intacct subsidiary is not shown on Connections card under Sage Intacct logo

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#45935] opened 2024-07-22 19:24 UTC
Testing doc: [here](https://docs.google.com/document/d/1AdHIz229Ze3BovRRR5YLW7nx8I2slf7greYkpV0SifI/edit?usp=sharing) (request, will share)

Pre-testing steps

- Make sure the email address does not already have existing workspaces/policies
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)
- Create a new collect policy on OldDot and; 
- Set the approval mode to “submit and approve”
- Enable scheduled submit with a frequency of `Daily` or “slower”
- Invite an additional user to the policy to play the member role in these testing flows
- Run the script stated [here](https://stackoverflowteams.com/c/expensify/questions/17518) to enable workspace chat creation for a paid plan.

Pre-testing steps

- Make sure that your test account is on the intacctOnNewExpensify beta
- Make sure you have Sage Intacct web services user ID, password and Company ID to initiate a connection
- Make sure you create a new workspace/policy for each test run
- Make sure emails sent to the testing email addresses go to an inbox you can access to validate your account(s)

Steps:
1. Head to Workspace settings
2. Head to Accounting
3. Under Sage Intacct Connection click `Connect`
4. Enter valid credentials 

Expected result: Once connected, the Sage Intacct subsidiary is shown on Connections card under Sage Intacct logo + Last synced message
Actual result: The Sage Intacct subsidiary is not shown on Connections card under Sage Intacct logo + Last synced message

Screenshot:
<img width="1010" alt="Screenshot 2024-07-22 at 8 28 51 PM" src="https://github.com/user-attachments/assets/85f22c79-01b7-4f39-b974-993d7924c25c">

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015bae9383e2075bb8</li>
        <li>Upwork Job ID: 1815835932579772267</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103311605</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by kabeer95** [comment] 2024-07-23 23:17
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
 The problem we are trying to solve is that the Sage Intacct subsidiary is not shown on the Connections card under the Sage Intacct logo after connecting to Sage Intacct from the Workspace settings.

## What is the root cause of that problem? 
The root cause of this problem is likely due to an incorrect implementation of the Sage Intacct API or a misconfiguration of the connection settings, which prevents the subsidiary information from being retrieved and displayed on the Connections card.

## What changes do you think we should make in order to solve the problem? 
To solve this problem, we need to review and adjust the Sage Intacct API implementation to ensure that it correctly retrieves and displays the subsidiary information on the Connections card. Specifically, we should verify that the Sage Intacct web services user ID, password, and Company ID are correct and properly configured, check the XML API calls to ensure that they are correctly formatted and include the necessary fields to retrieve the subsidiary information, and review the code that handles the connection to Sage Intacct and the display of the Connections card to ensure that it is correctly parsing and displaying the subsidiary information.
```
// Verify Sage Intacct credentials and connection settings
const sageIntacctCredentials = {
  userId: 'your_user_id',
  password: 'your_password',
  companyId: 'your_company_id'
};

// Set API endpoint and headers
const endpoint = 'https://api.intacct.com/ia/xml/xmlgw.aspx';
const headers = {
  'Content-Type': 'application/xml',
  'Authorization': `Basic ${sageIntacctCredentials.userId}:${sageIntacctCredentials.password}`
};

// Set XML payload to retrieve subsidiary information
const payload = `
<?xml version="1.0" encoding="UTF-8"?>
<request>
  <control>
    <senderid>${sageIntacctCredentials.companyId}</senderid>
    <password>${sageIntacctCredentials.password}</password>
    <controlid>string</controlid>
    <uniqueid>false</uniqueid>
    <dtdversion>3.0</dtdversion>
  </control>
  <operation>
    <authentication>${sageIntacctCredentials.companyId}</authentication>
    <get>
      <object>subsidiary</object>
    </get>
  </operation>
</request>
`;

// Send request to Sage Intacct API
const response = await fetch(endpoint, {
  method: 'POST',
  headers,
  body: payload
});

// Parse response to retrieve subsidiary information
const subsidiaryInfo = await response.xml();
if (subsidiaryInfo) {
  // Display subsidiary information on Connections card
  console.log('Subsidiary information:', subsidiaryInfo.text);
} else {
  console.error('Failed to retrieve subsidiary information');
}
```

**Comment by greg-schroeder** [comment] 2024-07-25 11:25
Proposal review underway

**Comment by greg-schroeder** [comment] 2024-07-25 11:45
Word, thanks @paultsimura

**Comment by SzymczakJ** [comment] 2024-07-29 09:43
Hello, I was implementing this feature,  so you can assign me to this 😄. I though that having no entity chosen is a viable option and means "syncing at a top level" [as mentioned in design doc](https://docs.google.com/document/d/1k3ZFw8KB55yPUSCG6KYZlwpwEtmRt3eUshwxs7bZq5I/edit#bookmark=id.txdvx2v6e1ud).
But now when I think of it, we don't give the user an option to come back to Top Level sync, so we surely need to address it.
How should Entities work in Sage Intacct @yuwenmemon? When we connect to Intacct, should entity be chosen arbitrarily? How to show that user is syncing at a top level(I think that showing no entity chosen is a bac way to indicate this)?

**Comment by yuwenmemon** [comment] 2024-07-29 15:22
> How to show that user is syncing at a top level(I think that showing no entity chosen is a bac way to indicate this)?

So based on the above, we should show an explicit "Top Level" option.

**Comment by yuwenmemon** [comment] 2024-07-29 15:22
cc @ryanldonato

**Comment by SzymczakJ** [comment] 2024-07-29 16:04
So basically we should translate missing entity field or entity set to `""` to a Top level option, right?

**Comment by yuwenmemon** [comment] 2024-07-29 16:09
Yep!

**Comment by tgolen** [comment] 2024-08-09 17:06
I don't think we need to treat this as a regression. As pointed out above, this was just something missed during implementation.

**Comment by isagoico** [comment] 2024-08-09 18:10
Related to this regression suite update - https://github.com/Expensify/Expensify/issues/414754#issuecomment-2278409936

@SzymczakJ I'm still able to reproduce that the Intacct Entity is not displayed on the latest staging build: 
![image](https://github.com/user-attachments/assets/b4c733ab-fb07-4584-822d-cfd0418532e8)

**Comment by SzymczakJ** [comment] 2024-08-12 07:55
I've also stumbled upon such bug once, it comes from Sage Intacct connection object not being connected properly causing entity object to be empty. Did it fix after reconnecting/relogging @isagoico? I noticed sometimes connection action fails and we get such "not complete" objects in connections

**Comment by isagoico** [comment] 2024-08-12 20:52
I'm not able to see the option even after disconnect > reconnect or refreshing the page. 
![image](https://github.com/user-attachments/assets/99d2029f-781b-408f-b7ad-754acb784eed)

**Comment by greg-schroeder** [comment] 2024-08-14 10:25
There aren't any payments due here from my end. Should we close this is or the above discussion still unresolved?

**Comment by SzymczakJ** [comment] 2024-08-14 13:39
@greg-schroeder let's keep this discussion for a moment.
Cannot reproduce on my end but I've checked frond-end code and it seems like it might be related to BE.

> it comes from Sage Intacct connection object not being connected properly causing entity object to be empty. 

@NikkiWines @yuwenmemon are there any BE issues related to connecting to Sage intacct?

**Comment by SzymczakJ** [comment] 2024-08-14 13:42
I'll OOO the whole next week but feel free to ask @war-in, as he has a lot of context.

**Comment by dylanexpensify** [comment] 2024-08-15 20:09
@greg-schroeder let's get @war-in assigned here to keep it moving? @yuwenmemon @NikkiWines can you confirm @SzymczakJ's query [here](https://github.com/Expensify/App/issues/45935#issuecomment-2288783027)?

**Comment by yuwenmemon** [comment] 2024-08-15 20:27
> @NikkiWines @yuwenmemon are there any BE issues related to connecting to Sage intacct?

There could be a multitude of errors. However, I, too, am unable to reproduce it on my end. @isagoico would you be able to spin up an issue with reproduction steps?

And then I think we can close this issue out.

**Comment by yuwenmemon** [comment] 2024-08-15 20:35
Oooooh wait I know what's happening. @isagoico You're using the QA account right? That one doesn't use subsidiaries/entities. You can confirm this by looking at the same connection in OldDot, there is no entity selector there:
![Screenshot 2024-08-15 at 1 34 28 PM](https://github.com/user-attachments/assets/aea851f9-1a84-443c-85ff-53607ea5f6b0)

**Comment by isagoico** [comment] 2024-08-16 00:14
Ah! My apologies for this then 🫠 I think we can close this one out if it's a expected configuration on the QA account

**Closed** 2024-08-16 01:05 UTC
Labels: External, Weekly, Bug
