### ISSUE TITLE
Android - Distance - Enable location prompt displayed twice when location is off

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49353] opened 2024-09-17 19:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3.6.1
**Reproducible in staging?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
precondition: location is turned off on the device
1. Open the app and log in
2. Navigate to a workspace chat
3. Start creating a distance expense
4. Select "No thanks" on the turn on location prompt
5. Complete submitting the distance expense
6. Create another distance expense (it may take 2-3 more times creating distance expenses)

## Expected Result:
Only one prompt to enable location is displayed

## Actual Result:
Two prompts to enable location are displayed with a green background

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/464e9087-94c8-47f0-b1eb-f3a108db5502

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-17 19:26
We think that this bug might be related to #wave-collect - Release 1

**Comment by joekaufmanexpensify** [comment] 2024-09-18 15:18
Not reproducible for me 

https://github.com/user-attachments/assets/4d4b5e09-1598-46b3-9f77-d411760e12ae

**Comment by joekaufmanexpensify** [comment] 2024-09-18 15:19
Even if this was reproducible, I don't think this really has much customer impact. But closing for now since I cannot reproduce.

**Closed by joekaufmanexpensify** 2024-09-18 15:19 UTC
Labels: Daily, Bug
