### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] Pay someone - Missing paid system message for paying someone

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45203] opened 2024-07-10 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Click + > Pay <user>
4. Enter amount and pay the user
5. Click on the expense preview

## Expected Result:
There will be a paid system message for paying someone (according to PR 43742)

## Actual Result:
There is no paid system message for paying someone

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/15219ced-0bb0-4ac6-8c44-ad61f4ecf8d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010ff4cba2e4566fca</li>
        <li>Upwork Job ID: 1813273027515516872</li>
        <li>Last Price Increase: 2024-07-16</li>
<li>Automatic offers: </li>
<ul>
<li>tsa321 | Contributor | 103348532</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-10 19:19
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-10 19:19
We think that this bug might be related to #wave-collect - Release 1

**Comment by tsa321** [comment] 2024-07-11 04:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Missing paid system message for paying someone

### What is the root cause of that problem?
Here:

https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/libs/ReportActionsUtils.ts#L362-L364

The sent money/paid IOU report actions is getting filtered and won't show up:

https://github.com/Expensify/App/blob/a91b7f8526dd3798deb247922be88cbff503f16a/src/pages/home/report/ReportActionsView.tsx#L164

in `reportActionsToDisplay`. So it won't be displayed

### What changes do you think we should make in order to solve the problem?

If the expected result is to show the message, we can remove this filter and the message will be displayed.

**Comment by MitchExpensify** [comment] 2024-07-16 18:02
Reassigning as I'm heading on leave 🙇

**Comment by joekaufmanexpensify** [comment] 2024-07-17 14:26
@parasharrajat thoughts on the proposal here?

**Comment by tsa321** [comment] 2024-07-18 00:29
@parasharrajat I have updated the permalink of the code, but the code is still the same.

**Comment by joekaufmanexpensify** [comment] 2024-07-19 12:42
Still pending further discussion on proposal

**Comment by mountiny** [comment] 2024-07-22 22:44
Discussing this in there too https://github.com/Expensify/App/issues/44590#issuecomment-2243936559

**Comment by joekaufmanexpensify** [comment] 2024-07-23 12:40
Sounds good, subscribed there!

**Comment by joekaufmanexpensify** [comment] 2024-07-24 13:35
Still pending further confirmation on the other issue of whether this was intentional.

**Comment by joekaufmanexpensify** [comment] 2024-07-25 13:39
Bumped Puneet 1:1 for the other issue to confirm

**Comment by joekaufmanexpensify** [comment] 2024-07-25 13:51
Confirmed we should go ahead with this one. @parasharrajat mind confirming if this [updated proposal](https://github.com/Expensify/App/issues/45203#issuecomment-2234897719) is good?

**Comment by joekaufmanexpensify** [comment] 2024-07-26 13:36
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-07-30 12:52
@parasharrajat did you have a chance to check the proposal here?

**Comment by joekaufmanexpensify** [comment] 2024-07-31 13:03
Got it. TY!

**Comment by joekaufmanexpensify** [comment] 2024-08-05 13:27
PR merged

**Comment by joekaufmanexpensify** [comment] 2024-08-12 13:26
Looks good to me! I will complete checklist.

**Comment by joekaufmanexpensify** [comment] 2024-08-13 14:07
Checklist is complete! All set to issue payment soon. We need to pay: 

- @tsa321 - $250 for PR via upwork. 
- @parasharrajat - $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:53
All set to issue payment.

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:55
@tsa321 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:55
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:56
Closing as all that's left is for @parasharrajat to request payment via NewDot. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-08-14 12:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 11:56
$250 approved for @parasharrajat
