### ISSUE TITLE
[$1000] Timezone does not updates on switch back to Automatically determine your location

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21058] opened 2023-06-19 17:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. from userA, send a message to userB
2. on userB, go to Settings > Profile > Timezone
3. off Automatically determine your location
4. change Timezone
5. check the Timezone in userA which will be changed
6. in userB, on Automatically determine your location
 7.  check the Timezone in userA
## Expected Result: 
timezone should be updated
## Actual Result: 
timezone updates after reload

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/47fe5fcd-381b-4510-a920-7f3a79894784

https://github.com/Expensify/App/assets/43996225/96177761-7d93-4407-ba6f-dec904ff0e98

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1686554268488389
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195a437d395cddd78</li>
        <li>Upwork Job ID: 1674007270196244480</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-06-19 22:33
Checking on why we feel this is unexpected here https://expensify.slack.com/archives/C049HHMV9SM/p1687214006179199?thread_ts=1686554268.488389&cid=C049HHMV9SM

> I would think that having "Automatically determine your location" turned on would override any manually set timezone. As such, this seems expected to me in that we're showing the time to User A that is based of us automatically determining your location - Am I missing something?

**Comment by gadhiyamanan** [comment] 2023-06-20 07:14
@MitchExpensify if userB turns on "Automatically determine your location" , the timezone is not updates in report screen of userA

https://github.com/Expensify/App/assets/54790231/0337b1da-4418-42f1-86c8-37313e668d05

**Comment by MitchExpensify** [comment] 2023-06-21 21:09
I'm going OOO until Tuesday so reassigning and keeping myself on here to take over when back!

**Comment by dylanexpensify** [comment] 2023-06-26 17:47
Didn't get to today, but will tackle tomorrow!

**Comment by Shivam7-1** [comment] 2023-06-28 11:03
## Proposal

### Timezone does not getting updated

## Please re-state the problem that we are trying to solve in this issue.
What is the root cause of that problem?
 the issue lies in the `TimezoneSelectPage.js` file component. 
The `componentDidUpdate` method is responsible for updating the timezone options when the automatic timezone selection is toggled on/off. 
However, it doesn't properly update the state and re-render the component.
.

### What changes do you think we should make in order to solve the problem?
In Solution of this issue The code can modify as follows:


To fix the issue, you can modify the `componentDidUpdate` method as follows:

`
componentDidUpdate(prevProps) {
  const prevTimezone = this.getUserTimezone(prevProps.currentUserPersonalDetails);
  const currentTimezone = this.getUserTimezone(this.props.currentUserPersonalDetails);

  if (!_.isEqual(prevTimezone, currentTimezone)) {
    this.timezone = currentTimezone;
    this.allTimezones = _.map(this.allTimezones, (timezone) => {
      const text = timezone.text.split('-')[0];
      return this.getTimezoneOption(text);
    });

    this.setState({
      timezoneInputText: this.timezone.selected,
      timezoneOptions: this.allTimezones,
    });
  }
}
`


The updated code compares the previous and current timezone values and triggers the update of the component's state and re-rendering when a change is detected.

By making this change, the `TimezoneSelectPage` component will update the timezone options correctly when the automatic timezone selection is toggled on/off, and the selected timezone should be reflected in both `userA` and `userB` as expected

**Comment by Pujan92** [comment] 2023-06-28 11:35
I think currently pusher event only applied to the `UpdateSelectedTimezone` api which also needs to apply for `UpdateAutomaticTimezone` api in the backend.
@madmax330 https://github.com/Expensify/App/issues/16871?

**Comment by madmax330** [comment] 2023-06-28 16:53
Yes that seems correct @Pujan92 this should be internal

**Comment by dylanexpensify** [comment] 2023-06-29 07:03
Moving to internal, thanks!

**Comment by dylanexpensify** [comment] 2023-06-29 07:14
@madmax330 should I post for volunteers on this you think?

**Comment by MitchExpensify** [comment] 2023-06-30 23:22
Taking this back over after returning from OOO, Thanks @dylanexpensify !

**Comment by MitchExpensify** [comment] 2023-07-03 21:24
@madmax330 when do you think you might be able to get to this? 🚀

**Comment by madmax330** [comment] 2023-07-04 07:56
I can do it this week

**Comment by MitchExpensify** [comment] 2023-07-10 19:29
Just trying to keep Melvin off our backs and checking in on this issue as a result of the label @madmax330 👍

**Comment by MitchExpensify** [comment] 2023-07-12 21:09
Just checking in @madmax330

**Comment by MitchExpensify** [comment] 2023-07-18 21:21
Friendly bump @madmax330

**Comment by madmax330** [comment] 2023-07-20 12:14
Wait, I was never assigned to this issue 😬 
Sorry, it didn't show up in my k2. I'll do this today

**Comment by MitchExpensify** [comment] 2023-08-01 18:02
Sure thang!

**Payments due**:

- Reporting @gadhiyamanan: $250 
- C: Not due, internal
- C+ @sobitneupane: $1000 to be issue via NewDot 

Upwork is acting up for me right now so I'll try issue the reporting bonus again soon. Upwork can just be hit or miss in my experience 😅

**Comment by sobitneupane** [comment] 2023-08-09 03:52
@MitchExpensify I didn't review the internal PR. So, we should only pay reporter of the issue.

**Comment by MitchExpensify** [comment] 2023-08-09 22:10
Got it! Thanks for the correction @sobitneupane

**Comment by MitchExpensify** [comment] 2023-08-09 22:12
Inviting you here for reporting bonus https://www.upwork.com/jobs/~015919af3a455f9196 @gadhiyamanan

**Comment by webioatom** [comment] 2023-08-09 22:23
Fix is still needed or bug already fixed?

**Comment by gadhiyamanan** [comment] 2023-08-10 03:29
@MitchExpensify offer accepted, thanks!

**Comment by MitchExpensify** [comment] 2023-08-10 21:54
Paid and contract ended! Thanks everyone

**Comment by MitchExpensify** [comment] 2023-08-10 22:15
Do we need any BZ steps here before closing @sobitneupane ? (I.e. Do we need a new regression test?)

**Comment by madmax330** [comment] 2023-08-11 11:30
I don't think we need a regression for this tbh

**Closed by madmax330** 2023-08-11 11:30 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
