### ISSUE TITLE
[$1000] Request Money: The name doesn’t update dynamically on a new workspace chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19847] opened 2023-05-30 19:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to dev on web chrome
2. Create a new workspace
3. Request money
4. First notice the workspace name on header, workspace message and the request money report
5. Now change the workspace name and notice that on the LHN and header, the workspace name gets updated dynamically. But if you see on the workspace welcome message and the request money report, the workspace name has not been updated dynamically (within the live chat)
6. Optional : Even if you refresh the page , the workplace welcome message will update the name, but still the request money report has not updated the workspace name

## Expected Result:
 In a new workspace chat, the changed workspace name should be updated on the welcome workspace chat message as well as on the request money report dynamically

## Actual Result:
 In a new workspace chat, the changed workspace name doesn't update on the welcome message as well as on the request money report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.20.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bfa53cae-0d61-4b9c-9b40-b424a4775757

https://github.com/Expensify/App/assets/93399543/b18942c2-cff6-40de-b05e-7a6ce0220a4d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685177191168879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01402004259896cf6a</li>
        <li>Upwork Job ID: 1663811839421620224</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by mananjadhav** [comment] 2023-05-31 12:44
I agree with @hungvu193's RCA and I think it is good to go.

But I would just like to clarify  with @MonilBhavsar @laurenreidexpensify  if we should just watch for name or any other info?

**Comment by mananjadhav** [comment] 2023-05-31 13:03
I agree. It's a duplicate. Hence I asked for other props. @MonilBhavsar we should close this one out.

**Comment by priya-zha** [comment] 2023-05-31 13:05
@mananjadhav how's this a duplicate ? It's related to not updating workspace name on welcome message and request money. Whereas the other issue is related to images.

**Comment by priya-zha** [comment] 2023-05-31 13:10
Okay if closed, I wanted to ask will I also be one of the reporters for this bug. Since if this issue wasn't reported, then it wouldn't have been solved on the same PR. Let me know your thoughts on this.😃😃

**Comment by MonilBhavsar** [comment] 2023-05-31 13:13
I also personally agree 👍

**Comment by mananjadhav** [comment] 2023-05-31 13:14
Yeah I agree too about the reporting bonus.

**Comment by laurenreidexpensify** [comment] 2023-06-05 09:46
@mananjadhav @MonilBhavsar sounds like we're good to move forward with @hungvu193's proposal here?

**Comment by MonilBhavsar** [comment] 2023-06-05 10:05
This issue will be fixed in the PR - https://github.com/Expensify/App/pull/19750. As root causes for this issue and the PR's issue is similar.
@hungvu193 could you please add `$ https://github.com/Expensify/App/issues/19847` to that PR so this issue is closed when the PR is merged.
Adding reviewing label here.

**Comment by laurenreidexpensify** [comment] 2023-06-07 11:29
@alexpensify I am OOO til 19 June so am adding you as my BZ buddy to watch over this issue while I am out. thanks!

**Comment by mananjadhav** [comment] 2023-06-07 15:20
Yeah, I would also like to confirm if it is really needed?

**Comment by MonilBhavsar** [comment] 2023-06-08 12:11
Good point, the server also actually constructs the message, and it doesn't happen until we refresh the page. So we have two options here - 
1. As per the proposal, don't use `message.html` [here](https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/components/ReportActionItem/ReportPreview.js#L118-L121) and construct the message client side using details from iou report object. 
2. Load reportActions again when name is updated.
3. Do nothing. `message.html` is updated when user refreshes the page and they see updated workspace name.

@luacmartins @mountiny would like to have your thoughts as you worked on this part of the feature.

**Comment by mountiny** [comment] 2023-06-08 12:26
Hmm To some extent I feel like if this is fixed after refresh, renaming a workspace is such rare event we should be fine with do nothing

**Comment by alexpensify** [comment] 2023-06-09 21:53
Are we thinking to close this GH or update the problem? Thanks!

**Comment by alexpensify** [comment] 2023-06-13 17:47
@mananjadhav and @MonilBhavsar - can I get feedback here, thanks!: 

https://github.com/Expensify/App/issues/19847#issuecomment-1585166900

**Comment by twisterdotcom** [comment] 2023-06-14 11:12
@hungvu193 are you saying here that this issue is resolved by https://github.com/Expensify/App/issues/19847? If so, @laurenreidexpensify or @alexpensify - could we just pay out @hungvu193 again for this issue?

**Comment by alexpensify** [comment] 2023-06-15 23:19
I edited the name of this GH based on this conversation: 

https://expensify.slack.com/archives/C049HHMV9SM/p1686848305171109?thread_ts=1686741676.850389&cid=C049HHMV9SM

We still need to decide if we will remove usage of message.html or do nothing (backend will fix that issue).

**Comment by alexpensify** [comment] 2023-06-18 15:48
Still in discussion

**Comment by alexpensify** [comment] 2023-06-20 21:40
@laurenreidexpensify - I think you are back online again. We updated the title and had a discussion that this is not a dupe. We still need to decide whether to close or not. Could you let me know when you are taking over again and I can exit this party? Thanks!

**Comment by laurenreidexpensify** [comment] 2023-06-21 12:09
@MonilBhavsar just circling back here = https://github.com/Expensify/App/issues/19847#issuecomment-1576504320 - was this fixed in that issue you mentioned?

**Comment by laurenreidexpensify** [comment] 2023-06-22 09:53
@MonilBhavsar Bump ^^ thanks

**Comment by laurenreidexpensify** [comment] 2023-06-26 09:26
Seeking an expert contributor to help - asking in slack

**Comment by lukemorawski** [comment] 2023-06-26 09:50
Hey. This Lucas from Callstack. I'm looking into this issue.

**Comment by lukemorawski** [comment] 2023-06-28 08:33
i'm will be presenting a proposal in our internal CS slack today

**Comment by laurenreidexpensify** [comment] 2023-06-28 11:23
Thanks @lukemorawski 👍

**Comment by laurenreidexpensify** [comment] 2023-06-28 11:25
@mananjadhav have sent C+ offer in Upwork

**Comment by laurenreidexpensify** [comment] 2023-06-30 06:55
@lukemorawski is there a draft PR up for this one yet?

**Comment by lukemorawski** [comment] 2023-06-30 08:40
we are discussing it internally. Should have a draft today.

**Comment by lukemorawski** [comment] 2023-06-30 13:19
# Proposal

## Problem

When a user in the workspace creates a new money request and then changes the name of that workspace, name is updated in the header and in the workspace top notice, but it's not updated in the message that is the money request preview.

## What is the root cause?

The problem is that messages are not automatically updated on device. The message that contains the name of the workspace and doesn't update is just a hardcoded string in the `reportAction.message[number].text` and `reportAction.message[number].html`. 

## What changes do you think we should make in order to solve the problem?

We can update it on the f/e (ways to do it in alternative solutions) but it won't update data on the be and this change won't be reflected on other devices.
The best way would be to update relevant messages on the BE when workspace (policy) name is updated. That should trigger changes on all connected devices and `reportActions` would update automatically.


## What alternative solutions did you explore?

1. We could utilize ReportScreen's `componentDidMount` method to check if the policy name changed. If yes, then this could trigger an action, that would look for action reports based on current `reportId`, replace all occurrences of the old name with new name. Then merge the updated report action with the old ones.
The make sure we are only updating the right action messages, the updates would only be narrowed to `reportActions` with `actionName` set to `REPORTPREVIEW`. This won't work if the current screen is not the ReportScreen.

2. Better solution then the above but requiring more effort from the app is replacing the workspace name in messages when `updateGeneralSettings` from `lib/actions/Policy` fires. The problem is that in that case we don't know what is the id of the `reportAction` where those messages are. There are two ways of dealing with this problem.
Currently available one is just going through all `reportActions` and finding the occurrences of the old workspace name and changing it. 
Another one, that would probably require changes on the BE, is to add `policyID` to `reportAction` object. That way we could quickly find the report where the messages are and update them.

**Comment by laurenreidexpensify** [comment] 2023-07-03 10:53
@mananjadhav can you review ^^ the proposal above? thanks!

**Comment by rezkiy37** [comment] 2023-07-04 12:27
Hi, I am Michael (Mykhailo) from Callstack. I will take it over during Lucas is OOO.

**Comment by laurenreidexpensify** [comment] 2023-07-06 07:06
Waiting for @mananjadhav to review proposal above

**Comment by mananjadhav** [comment] 2023-07-06 20:02
I don't see this being handled on App in an efficient way. @lukemorawski's proposal also suggest we do this on the backend. 
Ideally the way I would've done is having policyId as @lukemorawski in the `reportAction` and not have the name stored in the message. I've also recommended then we close this one out if we don't prefer to handle this on the backend.

@MonilBhavsar wdyt?

**Comment by rezkiy37** [comment] 2023-07-07 11:57
> I don't see this being handled on App in an efficient way. @lukemorawski's proposal also suggest we do this on the backend. Ideally the way I would've done is having policyId as @lukemorawski in the `reportAction` and not have the name stored in the message. I've also recommended then we close this one out if we don't prefer to handle this on the backend.
> 
> @MonilBhavsar wdyt?

Hi! As far as I understand you don't like the idea with the backend improvements, you do? 
Is your favourite the second alternative solution with: _Another one, that would probably require changes on the BE, is to add policyID to reportAction object..._?

**Comment by mananjadhav** [comment] 2023-07-07 12:00
> Another one, that would probably require changes on the BE, is to add policyID to reportAction object...?

I agree with the backend improvements and yes you're right this is better in the long run. What are thoughts @rezkiy37 ?

**Comment by rezkiy37** [comment] 2023-07-07 12:27
> > Another one, that would probably require changes on the BE, is to add policyID to reportAction object...?
> 
> I agree with the backend improvements and yes you're right this is better in the long run. What are thoughts @rezkiy37 ?

So, to sum up:
- The backend adds `policyID` to a `reportAction`.
- The app replaces the workspace name in messages when updateGeneralSettings from lib/actions/Policy fires.

Correct me if I am wrong 🙂

**Comment by rezkiy37** [comment] 2023-07-10 10:23
@mananjadhav Hi! What's your decision on [this](https://github.com/Expensify/App/issues/19847#issuecomment-1625342578)?

**Comment by laurenreidexpensify** [comment] 2023-07-11 07:53
@MonilBhavsar can you review today pls :)

**Comment by MonilBhavsar** [comment] 2023-07-11 12:16
> 1. The backend adds policyID to a reportAction.
> 2. The app replaces the workspace name in messages when updateGeneralSettings from lib/actions/Policy fires.

Thanks, this makes sense. I'm curious how step 2 works. Will the component be remounted and all messages gets updated. Also, this is very different from how it works currently. So, I'll also raise it internally

**Comment by rezkiy37** [comment] 2023-07-11 13:06
> > 1. The backend adds policyID to a reportAction.
> > 2. The app replaces the workspace name in messages when updateGeneralSettings from lib/actions/Policy fires.
> 
> Thanks, this makes sense. I'm curious how step 2 works. Will the component be remounted and all messages gets updated. Also, this is very different from how it works currently. So, I'll also raise it internally

@MonilBhavsar Do you need some help from me here?

**Comment by MonilBhavsar** [comment] 2023-07-11 13:18
Yes please. I would like to know more about how we plan to use the policyID to generate the message. We'll also need a translation key or action indicator that says what message needs to be generated, correct?

**Comment by rezkiy37** [comment] 2023-07-11 16:10
> We're also discussing here internally https://expensify.slack.com/archives/C03TQ48KC/p1689080689362209

Sorry, but this link does not work for me. Could you tag me there please: @Michael Kravchenko.
<img width="590" alt="Screenshot 2023-07-11 at 18 09 16" src="https://github.com/Expensify/App/assets/57314631/ea4207d0-0fff-42e6-bada-978a65fd7a34">

**Comment by rezkiy37** [comment] 2023-07-11 16:44
> Yes please. I would like to know more about how we plan to use the policyID to generate the message. We'll also need a translation key or action indicator that says what message needs to be generated, correct?

AFAIK, we are not going to generate the new message. There are already existed messages. We just need to use an updated workspace name there.

**Comment by MonilBhavsar** [comment] 2023-07-12 05:44
Sorry my bad, that is in an internal channel 😓

**Comment by MonilBhavsar** [comment] 2023-07-12 06:04
> AFAIK, we are not going to generate the new message. There are already existed messages. We just need to use an updated workspace name there.

sorry, I think I am not getting it. Currently, we display the message stored in report action object completely. And as per the proposal, we are thinking to pass policyID in reportAction object. We utilize that policyID, generate the message by getting corresponding policy(workspace name) and render the message. Is that correct?

**Comment by MonilBhavsar** [comment] 2023-07-13 10:26
Yes, this seems to have been fixed. I am curious, how? 😄

**Comment by rezkiy37** [comment] 2023-07-13 11:25
> There's a PR that remove usage of message.html as I mentioned 🤦, I think we can close, can't reproduce anymore.
> 
> https://github.com/Expensify/App/blob/451096b4828cf9a9bc1b5b7be95a6d52e79c392d/src/components/ReportActionItem/ReportPreview.js#L109

Yes, you are right!

**Comment by MonilBhavsar** [comment] 2023-07-17 08:59
Awaiting payment here cc @laurenreidexpensify

**Comment by mananjadhav** [comment] 2023-07-17 09:07
@MonilBhavsar @laurenreidexpensify I would like to request a partial payment here. I spent time in reviewing and testing the proposals/bug. We went from merging from one issue to even exploring backend changes.

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:05
@mananjadhav that seems fair. As you are on the C+ payment beta can you work with @anmurali for payment of $500 for this job? Thanks

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:06
@priya-zha offer sent in upwork

**Comment by mananjadhav** [comment] 2023-07-18 09:14
@laurenreidexpensify I'll do that. Thanks. Appreciate it.

**Comment by priya-zha** [comment] 2023-07-18 09:54
@laurenreidexpensify thanks, accepted.

**Comment by mananjadhav** [comment] 2023-07-18 14:37
@laurenreidexpensify @anmurali I've raised a request on NewDot for $500.

**Comment by anmurali** [comment] 2023-07-18 17:53
Approved $500 on New Dot for Manan

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:11
payment for @priya-zha actioned in upwork. Closing as all payments completed

**Closed by laurenreidexpensify** 2023-07-19 12:11 UTC
Labels: Daily, Improvement, Internal, Awaiting Payment, Bug

**Comment by anmurali** [comment] 2023-07-21 16:41
Approved $500 to Manan based on https://github.com/Expensify/App/issues/19847#issuecomment-1639830229
