### ISSUE TITLE
[$250] Move the Group Chat "Group name" field out of Settings and into Report Details

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#40262] opened 2024-04-16 01:38 UTC
cc @shawnborton @JmillsExpensify 

Coming from [this Slack conversation](https://expensify.slack.com/archives/C05RECHFBEW/p1712957551989569)

We have decided to move the "Name" edit field out of the "Details > Settings > Name" page and into the Report Details page itself with a much more stylized look.

**Deliverables:**

- Update the design to this style

![Image](https://github.com/Expensify/App/assets/32969087/1a76e51c-58b6-4406-99d1-2fa39dcddc7a)

- Ensure that updating the name works as expected
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f69965c8e23061b7</li>
        <li>Upwork Job ID: 1780048626647789568</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102713460</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2024-04-16 01:39
@shawnborton do we want to go ahead and update this for Workspace Rooms too while we're in here?

We've got this right now...

![Image](https://github.com/Expensify/App/assets/32969087/368acd50-2392-49f1-8074-beb7195de6a3)

**Comment by nkdengineer** [comment] 2024-04-16 01:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Move the Group Chat "Group name" field out of Settings and into Report Details

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

1. Move the room name input [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/settings/Report/ReportSettingsPage.tsx#L74) to the report details page
2. Update the style to match the new design

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-16 02:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Move the Group Chat "Group name" field out of Settings and into Report Details

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

1. Move the room name input [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/settings/Report/ReportSettingsPage.tsx#L74) to the report details page [here](https://github.com/Expensify/App/blob/76ca7814304e143c86d4a2031c69af8aba8e17a9/src/pages/ReportDetailsPage.tsx#L322)
2. Update the style to match the new design
    - Change input title from `Name` to `Group name`
    - Allow the input to have custom fonts + font size
    - Add padding bottom so the room name will have spaces compared to the Group chat quick buttons below it
3. We might need to update the navigation structure for the group name edit field so that it will be a sub route of the report details page instead of the report settings page. So navigating to it and go back will go to the correct report details page.
    - Move [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L120) to [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L114)
    - Move [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/linkingConfig/config.ts#L446-L448) to [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/linkingConfig/config.ts#L435)
    - Update [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/GroupChatNameEditPage.tsx#L69) and [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/GroupChatNameEditPage.tsx#L88) so it goes back to the correct `REPORT_WITH_ID_DETAILS` on clicking back.
    
I believe this will apply to the room name as well (so similar changes for workspace room name will be needed), if not, we can apply the above change only to the group name

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nodebrute** [comment] 2024-04-16 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Move the "Name" edit field out of the "Details > Settings > Name" page 
### What is the root cause of that problem?
Feature Request
### What changes do you think we should make in order to solve the problem?

1. Move [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/settings/Report/ReportSettingsPage.tsx#L74) to report details page [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/ReportDetailsPage.tsx#L309)

2. In ReportDetailsPage add
```
import * as ReportActions from '@userActions/Report';
import Text from '@components/Text';
```
```
const shouldShowRoomName = !ReportUtils.isPolicyExpenseChat(report) && !ReportUtils.isChatThread(report);
const linkedWorkspace = useMemo(() => Object.values(policies ?? {}).find((policy) => policy && policy.id === report?.policyID) ?? null, [policies, report?.policyID]);
const shouldDisableRename = useMemo(() => ReportUtils.shouldDisableRename(report, linkedWorkspace), [report, linkedWorkspace]);
  const roomNameLabel = translate(isMoneyRequestReport ? 'workspace.editor.nameInputLabel' : 'newRoomPage.roomName');
```
3. We can change below code to show Group Name
 ``description={isGroupChat ? translate('common.name') : translate('newRoomPage.roomName')}``
to
``
description={isGroupChat ? translate('groupConfirmPage.groupName') : translate('newRoomPage.roomName')}
``
3. We can also add another variable to fix reportID issue
```
 const reportID = report?.reportID ?? '';
```
5. Change Font size/style according to design. We also need to change style for disable room name. The quick action buttons in the group are not center-aligned. We should align them in the center as well, creating a gap between the group name and the quick action buttons.

6. **Navigation**

- In [Screen.ts](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/SCREENS.ts) Add this [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/SCREENS.ts#L200)
```
     ROOM_NAME: 'Report_Details_Room_Name',
     GROUP_NAME: 'Report_Details_Group_Name',
```
and remove this
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/SCREENS.ts#L174-L175

- In [Routes.ts](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/ROUTES.ts) Change this [code](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/ROUTES.ts#L250-L257) to 
```
   REPORT_DETAILS_ROOM_NAME: {
        route: 'r/:reportID/details/room-name',
        getRoute: (reportID: string) => `r/${reportID}/details/room-name` as const,
    },
    REPORT_DETAILS_GROUP_NAME: {
        route: 'r/:reportID/details/group-name',
        getRoute: (reportID: string) => `r/${reportID}/details/group-name` as const,
    },
```

- In [config.ts](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/linkingConfig/config.ts) remove [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/linkingConfig/config.ts#L443-L448) and add below code [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/linkingConfig/config.ts#L435)
```
   [SCREENS.REPORT_DETAILS.ROOM_NAME]: {
     path: ROUTES.REPORT_DETAILS_ROOM_NAME.route,
       },
       [SCREENS.REPORT_DETAILS.GROUP_NAME]: {
           path: ROUTES.REPORT_DETAILS_GROUP_NAME.route,
          },
```

- In [ModalStackNavigators](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx) remove [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L119-L120) and add below code [here](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/Navigation/AppNavigator/ModalStackNavigators/index.tsx#L114)
```
[SCREENS.REPORT_DETAILS.ROOM_NAME]: () => require('../../../../pages/settings/Report/RoomNamePage').default as React.ComponentType,
    [SCREENS.REPORT_DETAILS.GROUP_NAME]: () => require('../../../../pages/GroupChatNameEditPage').default as React.ComponentType,
```
7.**BackNavigation**
Change [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/GroupChatNameEditPage.tsx#L69) to
```
                Navigation.goBack(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(reportID));
```
also Change [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/GroupChatNameEditPage.tsx#L88) to
```
 onBackButtonPress={() => Navigation.goBack(isUpdatingExistingReport ? ROUTES.REPORT_WITH_ID_DETAILS.getRoute(reportID) : ROUTES.NEW_CHAT_CONFIRM)}
```
In updatePolicyRoomNameAndNavigate [here](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.ts#L2004) and [here](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.ts#L2070) change these to 
```
    Navigation.goBack(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(reportID));
```
Also change [this](https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/pages/settings/Report/RoomNamePage.tsx#L87) to 
```
onBackButtonPress={() => Navigation.goBack(ROUTES.REPORT_WITH_ID_DETAILS.getRoute(report?.reportID ?? ''))}
```

Note:If we opt to apply this solely to group names, we can bypass the steps that involve changes with room names. Don't forget to clean up the ReportSettingsPage for unused variables.Changes can be made to the above code as needed.

**RESULT**

https://github.com/Expensify/App/assets/93134676/5521d24c-160f-437f-8be3-e6e78cd9de25


### What alternative solutions did you explore? (Optional)

**Comment by karam122** [comment] 2024-04-16 06:45
i am willing to start this task immediately if you people allow me

**Comment by karam122** [comment] 2024-04-16 07:08
Contributor details
Your Expensify account email: karam.pucit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015bd108906659a6b4?viewMode=1

**Comment by karam122** [comment] 2024-04-16 07:11
I have applied as you mentioned, now what should I do?

**Comment by shawnborton** [comment] 2024-04-16 08:17
> @shawnborton do we want to go ahead and update this for Workspace Rooms too while we're in here?

> We've got this right now... ![image](https://github.com/Expensify/App/assets/2319350/20ac362f-cd94-4e86-a83c-68176e6a91da)

Hmm yeah, I guess it would make sense to be consistent between groups and rooms. I could get down with that then, cc @Expensify/design for thoughts too.

**Comment by dubielzyk-expensify** [comment] 2024-04-16 10:50
Yeah would be nice to do it for both at the same time 😄

**Comment by marcaaron** [comment] 2024-04-16 19:35
Proposals look pretty 👍 so far. 

I think we'd want to have a single route/screen though for both the Room and Group Chat page if possible. The underlying flows are slightly different i.e. different validation and different API calls. But ideally should be consolidated if possible.

@dragnoir great observations - will let @shawnborton respond before we proceed here.

**Comment by shawnborton** [comment] 2024-04-17 10:03
Maybe we should take an approach like this to harmonize rooms and groups? cc @JmillsExpensify @Expensify/design 

![CleanShot 2024-04-17 at 06 02 45@2x](https://github.com/Expensify/App/assets/2319350/c0a16e39-8d0f-4b5c-b882-de82ce451185)

**Comment by shawnborton** [comment] 2024-04-17 13:26
Ooo I quite like that! That's a great improvement

**Comment by dannymcclain** [comment] 2024-04-18 17:48
@dragnoir sorry! Missed your earlier comment. Here's the final mock—happy to post it on that other issue too.

[Figma link](https://www.figma.com/file/NDPg7ag0bcWW7QjBeSphmf/vip-split%3A-group-chats?type=design&node-id=4037-10516&mode=design&t=5Ofea5c6tqZzk3uz-11)

![image](https://github.com/Expensify/App/assets/7516624/e8ce31b1-573e-4da5-9c22-70a7e429bcdd)

**Comment by marcaaron** [comment] 2024-04-23 03:08
Just a quick heads up for the thread that I'm gonna go ahead and assign @dragnoir here as they have continued to be involved in the conversation. I've already got the other contributors working on issues related to this project (there are plenty more to help with).

**Comment by karam122** [comment] 2024-04-23 03:10
I didn't understand why i am here??? If nothing to do ???
Just I'm watching people comments and nothing else

**Comment by Nodebrute** [comment] 2024-04-23 03:19
Hey @marcaaron, @dragnoir posted some pictures with red lines showing where we could make cuts. Since this is a feature request, I wrote a detailed proposal based on the initial requirements. While there have been a few changes in the design requirements, my proposal is still more comprehensive than the one that was chosen.

> Also we need to remove the top part to fit the design here [#40262 (comment)](https://github.com/Expensify/App/issues/40262#issuecomment-2060892788) ![image](https://private-user-images.githubusercontent.com/12425932/323178592-0e1f024c-3afa-49ba-91be-e73321d328f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDIzMTIsIm5iZiI6MTcxMzg0MjAxMiwicGF0aCI6Ii8xMjQyNTkzMi8zMjMxNzg1OTItMGUxZjAyNGMtM2FmYS00OWJhLTkxYmUtZTczMzIxZDMyOGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAzMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3N2MxOGI2ZjYyZTg5ZjUyNzUxODhhMTIxYmMyM2JmYTBiNjRjOTVlYTk3NTI0NWMwZjM3NzdmNTRhMGI4NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tY58a0f9kkl5HzmzlHJiyaalDkIDTUSFM610Pml-yjg)
> 
> and here for groups ![image](https://private-user-images.githubusercontent.com/12425932/323181647-6704b412-d175-4502-9911-799a92ffe037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDIzMTIsIm5iZiI6MTcxMzg0MjAxMiwicGF0aCI6Ii8xMjQyNTkzMi8zMjMxODE2NDctNjcwNGI0MTItZDE3NS00NTAyLTk5MTEtNzk5YTkyZmZlMDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAzMTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2Yjc5ODNkNmZkZTEwNjMzNmM4MDcxMmEyMmU0ZTAyOTczYjAwYzUzYzM2OTNjMWMxZTI5ZTJkOTQ0NmI3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uyQY1HfvH7EHB2m4O0q5EB2V71SyiGer0qp8ccX0x34)

**Comment by muttmuure** [comment] 2024-05-08 07:15
PR in progress

**Comment by mallenexpensify** [comment] 2024-06-13 00:37
PR is here https://github.com/Expensify/App/pull/40858

**Comment by c3024** [comment] 2024-06-13 00:54
Commenting for taking over as contributor. (Context)[https://expensify.enterprise.slack.com/archives/C02NK2DQWUX/p1718239157243779?thread_ts=1718239157.243779&cid=C02NK2DQWUX]

**Comment by mallenexpensify** [comment] 2024-07-09 23:08
Closing, [the PR](https://github.com/Expensify/App/pull/43636) was closed as well because "This has been implemented in the Details Revamp flow during the refactor of ReportDetailsPage"  

 @c3024 if you believe you're due compensation because you raised the PR, please comment and I'll reopen. Thx

**Closed** 2024-07-09 23:09 UTC
Labels: Reviewing, External, Monthly, NewFeature
