### ISSUE TITLE
iOS Rules - Text cursor moves to front after entering the third digit in Percentage field

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48869] opened 2024-09-10 09:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to Workspace settings > Rules.
3. Enable Auto-approve compliant reports
4. Tap Random report audit.
5. Try enter three digits in the input field.

## Expected Result:
The text cursor will not move to the front after entering the third digit.

## Actual Result:
The text cursor moves to the front after entering the third digit.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c351e89e-7096-49d3-aba3-71c9d60c5edb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by iwiznia** [comment] 2024-09-10 15:32
Since this is only happening in one platform and when you try to enter 3 numbers (which is not really valid), going to remove the blocker.

I _think_ this was added in https://github.com/Expensify/App/pull/47083 which is part of https://github.com/Expensify/App/issues/46935 so maybe @WojtekBoman you want to take a look?

**Comment by huult** [comment] 2024-09-10 16:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Text cursor moves to front after entering the third digit in Percentage field

### What is the root cause of that problem?

this issue seems to stem from React Native’s handling of inputs on mobile, [http://facebook/react-native#36494](https://github.com/facebook/react-native/issues/36494)

### What changes do you think we should make in order to solve the problem?

We can use a workaround (maxLength) to prevent this.

```diff
// src/components/PercentageForm.tsx#L71

+    const getMaxLength = useCallback(() => {
+        const numValue = parseInt(currentAmount || "0", 10);
    
+        if ((numValue >= 0 && numValue <= 9) || (numValue >= 11 && numValue <= 99)) {
+           return 2;
+        }
    
+        return 3;
+    }, [currentAmount]);

// src/components/PercentageForm.tsx#L73
      <TextInput
            ...
+         maxLength={getMaxLength()}
```

<summary>
<details>POC

https://github.com/user-attachments/assets/3e67c3ef-1a1c-46ee-9cc3-49377492a9fd

<details>
</summary>

**Comment by iwiznia** [comment] 2024-09-13 10:58
@WojtekBoman bump on https://github.com/Expensify/App/issues/48869#issuecomment-2341271076

**Comment by WojtekBoman** [comment] 2024-09-13 12:19
Sure I'll take a look, sorry for the delay, I didn't notice the message

**Comment by miljakljajic** [comment] 2024-09-20 15:01
Heading out on my parental leave - it seems like this is being handled by @WojtekBoman from software mansion so I will not re-assign another BZ team member. Please add someone else on if I am wrong.

**Comment by Christinadobrzyn** [comment] 2024-10-17 05:26
Hi @WojtekBoman can you tell me if this issue might fix this other report? https://github.com/Expensify/App/issues/50886

**Comment by WojtekBoman** [comment] 2024-10-18 09:19
This issue should be closed, [the PR](https://github.com/Expensify/App/pull/49180) fixing it has already been merged

**Closed** 2024-10-28 15:36 UTC
Labels: Reviewing, Engineering, Monthly, Bug
