### ISSUE TITLE
[$250] Thread – DM chat beginning appears briefly when open thread after leaving it

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46186] opened 2024-07-25 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4765377
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Send a message
5. Right click and select Reply in thread
6. Send a comment in the thread
7. Click on header
8. Click on Leave thread
9. Click on reply to open thread again

## Expected Result:
Thread opens

## Actual Result:
DM chat beginning with Avatar and “This is the beginning of you chat” appears briefly then thread opens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/3a4e65e7-a76c-44ee-8a32-2f104b41e842

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01719e64e7c5faf605</li>
        <li>Upwork Job ID: 1818438947380985483</li>
        <li>Last Price Increase: 2024-07-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ahmedGaber93</details>

**Comment by lanitochka17** [comment] 2024-07-25 13:02
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-07-25 13:02
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mallenexpensify** [comment] 2024-07-31 00:12
@ahmedGaber93 I was able to reproduce, any thoughts here on why it might be happening? 
Unsure if this is worth fixing , cuz the flash is so quick. 


https://github.com/user-attachments/assets/62ef356f-c614-48b3-af5b-515846e279bd

**Comment by ahmedGaber93** [comment] 2024-07-31 08:22
@mallenexpensify the flash takes more time with me, about 2~3 seconds. I will check why this happened today.



https://github.com/user-attachments/assets/5e75ac66-429a-401f-8b23-4aacde389c21

**Comment by ahmedGaber93** [comment] 2024-07-31 11:39
1. After we click Leave button, the `api/LeaveRoom` return with error "Your session has expired". This error cause there is no response with onyx `"onyxData": []` data related to the Leave action that set them to null (I believe it should return if request success). So the thread report and reportActions still on onyx and not removed so when opened after leaving, it opens correctly from onyx then it flash.

```
{
    "jsonCode": 407,
    "title": "Session expired",
    "message": "Your session has expired. Please sign in again.",
    "requestID": "8abd47afe9205368-CAI",
    "onyxData": []
}
```

<details>
<summary>video</summary>


https://github.com/user-attachments/assets/d133fb48-d216-4254-ae2e-2dad88191322



</details>

2. The flashing come from after we open the thread again, we send two APIs
 - API `GetMissingOnyxMessages` get the missed onyx data, which set the thread report and reportActions to null (this is what I think it should return if `api/LeaveRoom` success) which remove the thread report.
 - API `openReport` that display welcome message and loading while get the thread report and reportActions again
 
 
I am not sure if this is the main root cause or not yet, but we need to fix `api/LeaveRoom` error from BE, then retest.

@mallenexpensify I think we need to fix the above backend issue then retest.

**Comment by mallenexpensify** [comment] 2024-07-31 23:02
Thanks for all the context and details @ahmedGaber93 .   I've made it internal and a weekly.  Aded to #vip-vsb too.  i wonder if the flash/delay is happening elsewhere.

**Comment by ahmedGaber93** [comment] 2024-08-01 17:54
>  i wonder if the flash/delay is happening elsewhere.

I didn't see it in any place else, but there is another issue take about the same response `407 Session expired` here https://github.com/Expensify/App/issues/45926

**Comment by mallenexpensify** [comment] 2024-08-06 23:35
@ahmedGaber93 can you add 🎀 to assign and engineer to review to discuss next steps?

**Comment by ahmedGaber93** [comment] 2024-08-07 10:03
Adding 🎀 to assign and engineer to review to discuss next steps? more context here https://github.com/Expensify/App/issues/46186#issuecomment-2260318749

**Comment by ahmedGaber93** [comment] 2024-08-07 10:07
Adding 🎀 👀 🎀 to assign and engineer to review to discuss next steps? More context https://github.com/Expensify/App/issues/46186#issuecomment-2260318749

**Comment by mallenexpensify** [comment] 2024-08-07 22:31
@aldo-expensify , when you get a min, can you review the above? Need to figure out:

1. Do we want to fix this?
2. If so, does it need to be internal ?

**Comment by aldo-expensify** [comment] 2024-08-07 22:42
> Do we want to fix this?

It is something visible to the user which makes the UI not look great. I bet that on slower connections, the "This is the beginning of you chat" will appear for longer. Having said that, I think we can investigate and work on it with a LOW priority? maybe `Weekly` is fine?

> If so, does it need to be internal ?

From @ahmedGaber93 investigation, it does look like an `internal` (part of it at least).

**Comment by mallenexpensify** [comment] 2024-08-07 23:13
Thanks @aldo-expensify , will treat it with low priority.

**Comment by ahmedGaber93** [comment] 2024-08-26 08:51
@mallenexpensify The BE issue looks fixed, and I am not able to reproduce this on staging


https://github.com/user-attachments/assets/668078c1-0f52-43cc-a17f-4f11c71187f5

**Comment by mallenexpensify** [comment] 2024-08-26 16:48
Thanks @ahmedGaber93 !! Also tested on staging, Chrome, and confirmed that I'm unable to reproduce.  Closing.

**Closed by mallenexpensify** 2024-08-26 16:48 UTC
Labels: Weekly, Internal, Bug
