### ISSUE TITLE
[HOLD for payment 2023-01-19] [$250] Web - Chat - Additional lines appear when pasting as plain text message with links

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12769] opened 2022-11-16 14:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/ and login
2. Open any chat
3. Copy any message with links and paste it as plain text to the chat

## Expected Result:
Message should be pasted without any additional lines appearing

## Actual Result:
Message is pasted with additional lines appearing. Looks like only Web issue as Android, iOS and mWeb do not have "past as plain text" option

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.28.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202210854-d83fd989-09e3-43a5-bca8-51615c5c556e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013410363a72ffb4cd</li>
        <li>Upwork Job ID: 1605172678767808512</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2022-11-17 00:08
Job posting: https://www.upwork.com/jobs/~01e9a396b1713a3765

**Comment by Kellie-Brighty** [comment] 2022-11-17 00:36
Hello. I am Kelly Owoju. I see that you have an issue with your project. Issue concerning pasting plain text with links, but having a new line being added, I believe I got the issue correctly..?

One thing I need to understand is the practical aspect of this issue, I have tried replicating it on my end by following the link you posted... But I couldn't quite figure out the issue. Please I propose that you send me a message on upwork and tell me more about this issue, I believe I can be of help when I understand the issue more.

**Comment by Kellie-Brighty** [comment] 2022-11-17 01:12
Now I have checked to reproduce the issue here on my end.

And I know exactly why that is happening, and I can tell you what to do to make that experience go away.

I see what you posted on the job description on upwork, the fix will not be needing a new code base of some sort, the fix is nothing related to coding.

I have prepared some resources for you in line with the fix. Send me a chat please.

**Comment by wildan-m** [comment] 2022-11-17 08:00
# Proposal

## Root Cause
This issue can only be found in `Windows` OS. It's related to a [different line end of line character across platforms](https://confluence.qps.nl/fledermaus7/questions-answers/other/differences-in-end-of-line-characters-mac-windows-and-linux). 

Windows - Lines end with both a <CR> followed by a <LF> character
Linux  - Lines end with only a <LF> character
Macintosh (Mac OSX) - Lines end with only a <LF> character
Macintosh (old) - Lines end with only a <CR> character

If the user access from the window and the API server is Linux, then it can cause unexpected result.

## Solution

For this case, it's better to use `\n` as the universal end of the line for all operating systems.

```diff
diff --git a/src/components/Composer/index.js b/src/components/Composer/index.js
index 6ae3ae6cbe..3c997dfd27 100755
--- a/src/components/Composer/index.js
+++ b/src/components/Composer/index.js
@@ -328,7 +328,7 @@ class Composer extends React.Component {
             return;
         }
 
-        const plainText = event.clipboardData.getData('text/plain');
+        const plainText = event.clipboardData.getData('text/plain').replace(/\r\n|\r|\n/g, "\n");
         this.paste(Str.htmlDecode(plainText));
     }
```

## Result
OS: Windows 10
1st Attempt: Use Expensify's `Copy to Clipboard` menu
2nd Attempt: Use Ctrl+C

https://user-images.githubusercontent.com/11847279/202388847-a882a4b8-b89d-420a-8edf-0a57ac6dffd5.mp4

**Comment by wildan-m** [comment] 2022-11-17 21:05
@rushatgabhane In `Composer` ExpensiMark used for HTML paste, not plain text
```
handlePastedHTML(html) {
        const parser = new ExpensiMark();
        this.paste(parser.htmlToMarkdown(html));
    }
```

Did you mean we should also use ExpensiMark for this plain text?

**Comment by NicMendonca** [comment] 2022-11-21 13:14
@tylerkaraszewski just to confirm, should I be closing the upwork job?

**Comment by tylerkaraszewski** [comment] 2022-11-21 20:29
@NicMendonca I believe yes. We will come back and pay any contributors on these issues if their proposed solutions end up being used.

**Comment by mvtglobally** [comment] 2022-11-22 21:20
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment] 2022-11-24 15:03
OK, closed the job for now!

**Comment by tylerkaraszewski** [comment] 2022-11-30 16:56
Doing this after sequence numbers.

**Comment by tylerkaraszewski** [comment] 2022-12-15 19:51
I have to finish my sequenceNumbers bug before this.

**Comment by tgolen** [comment] 2022-12-19 18:23
@mvtglobally Can you please see if this is still reproducible? I see a comment from a few weeks ago that it was not, but there hasn't been an update since then.

**Comment by laurenreidexpensify** [comment] 2022-12-20 12:05
I can replicate this in Chrome on Mac.

**Comment by laurenreidexpensify** [comment] 2022-12-20 12:06
@tgolen I added `external` by reflex here, but lmk if you wanted to pick it up.

**Comment by trjExpensify** [comment] 2022-12-20 12:12
Yep, it's over 4 weeks old already, so should stay internal as it's preventing us from hitting WAQ ([discussed here yesterday](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463674591089)).

**Comment by tgolen** [comment] 2022-12-20 20:05
I was able to reproduce it! Then I started to work on a fix and I could no longer reproduce it either locally or on staging 😡 It's a little frustrating, but I'll keep at it.

**Comment by JmillsExpensify** [comment] 2022-12-21 20:57
Likes like @sobitneupane has found out has to consistently reproduce in the linked PR! You have something up for review in any case, so that's a great start and next step.

**Comment by laurenreidexpensify** [comment] 2022-12-22 14:55
Tim is now OOO til Wed 28 Dec, so we should expect this to go overdue and remain that way til he's back :)

**Comment by JmillsExpensify** [comment] 2022-12-22 19:30
I think this is a good candidate to try and get someone to step in while Tim is OOO. We're super close to getting on top of WAQ – only 5 issues away at the moment – so I don't really want to let off the gas right now if we can move this forward over the coming business days. What about seeing if we can get any volunteers in the linked [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463674591089)?

**Comment by tgolen** [comment] 2022-12-28 16:09
OK, @sobitneupane found a regression in my fix which is unfortunate. There are two ways to copy text to the clipboard:

1. From the popup context-menu of the comment 
2. Highlighting the text and pressing CTRL+c

It seems that the extra newlines are only added with `2`, so stripping the extra newlines when pasting will break `1`.

I need to dig into the code more to understand what all is happening before I can come up with a better solution

**Comment by tgolen** [comment] 2022-12-28 16:26
OK, the best solution I can come up with is to add extra newlines when copying a comment from the context-menu.

I know that's not SUPER ideal, because if you paste it outside of NewDot, it'll have the extra newlines. However, that's consistent behavior with highlighting the text and pressing CTRL+c, so I think it's acceptable.

I'm going to move forward with that unless anyone has any objections.

**Comment by JmillsExpensify** [comment] 2022-12-28 20:36
Thanks for jumping back in now that you're back and getting this moving! Sounds like a plan, can't think of any concerns.

**Comment by tgolen** [comment] 2023-01-02 16:05
We're still running into a few consistency issues (on messages that contain links vs. having no links) so I am going to do a little bit deeper of investigation to see why links would be causing issues.

**Comment by tgolen** [comment] 2023-01-10 00:39
We are close! PR is approved and just waiting for merge

**Comment by tgolen** [comment] 2023-01-12 16:42
@sobitneupane What are your thoughts with this one? Do you think it was a regression, or just something that's always been broken and this was really just making the behavior consistent everywhere? I really don't know that I would be able to find a specific regression which lead to this.

**Comment by sobitneupane** [comment] 2023-01-12 18:45
I think it was a regression. I will dive in and try to find the culprit if it's a regression.

**Comment by laurenreidexpensify** [comment] 2023-01-19 10:44
@sobitneupane can you accept job in Upwork? Thanks!

**Comment by sobitneupane** [comment] 2023-01-19 11:46
@laurenreidexpensify Accepted the offer. Since it is internal PR, payment amount should be $1000.

**Comment by laurenreidexpensify** [comment] 2023-01-20 09:00
Paid correct amount @sobitneupane ✔️

@tgolen @sobitneupane  I am closing this one now, if you think there is still a path to finding the regression please reopen for follow up. Thanks

**Closed by laurenreidexpensify** 2023-01-20 09:00 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
