### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Change language also trigger submit Sign in validation form when magic codes are fullfilled

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22037] opened 2023-07-02 01:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Sign in page
2. Enter any Expensify account
3. Fill-in incorrect magic codes
3. Verify that the form show "Incorrect magic code"
4. Scroll to bottom, change to another language
## Expected Result:
 The Sign in validation form should not be auto submitted
## Actual Result: 
The Sign in validation form is auto submitted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/542eddcb-90f6-4623-8358-153227224570

https://github.com/Expensify/App/assets/43996225/c84c4b06-ecac-40d8-945d-4960e09989d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688119742990839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3cba7e2b4d05772</li>
        <li>Upwork Job ID: 1678889176475852800</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-02 01:55
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Change language also trigger submit Sign in validation form when magic codes are fullfilled
### What is the root cause of that problem?
- In `MagicCodeInput` component, we have a `useEffect` that will be triggered when `props.onFulfill` be changed
https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/components/MagicCodeInput.js#L147-L152
- When we make the callback `onFulfill` to pass as a props to `MagicCodeInput` component in the `BaseValidateCodeForm` component, this callback will be updated whenever the `props.preferredLocale` is changed
https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js#L220
=> That means when the `preferredLocale` is changed => It changes how `onFulfill` callback should be => also trigger this MagicCodeInput [useEffect](https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/components/MagicCodeInput.js#L147) to call `validateAndSubmit`
### What changes do you think we should make in order to solve the problem?
I think the purpose of this this MagicCodeInput [useEffect](https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/components/MagicCodeInput.js#L147) is auto validate form if the magic codes are fulfilled. So we don't really need to trigger it when `props.onFulfill` is updated => I suggest we should remove `props.onFulfill` from [dependency list here ](https://github.com/Expensify/App/blob/340411170911867fbea149f2f34dfa89671068ed/src/components/MagicCodeInput.js#L152)

**Comment by michaelhaxhiu** [comment] 2023-07-11 21:50
Sorry for the delay folks.

**Comment by michaelhaxhiu** [comment] 2023-07-11 22:14
Weird bug. Thanks for the early proposal. I'll leave it to @mananjadhav to start the review process

**Comment by mananjadhav** [comment] 2023-07-12 16:44
I think @hoangzinh's [proposal](https://github.com/Expensify/App/issues/22037#issuecomment-1616422655) looks good here. I can see we're already using `// eslint-disable-next-line react-hooks/exhaustive-deps`, so it won't throw an error.

🎀 👀 🎀 C+ Reviewed.

**Comment by mountiny** [comment] 2023-07-12 20:49
Thanks!

**Comment by mountiny** [comment] 2023-07-14 20:36
merged

**Comment by mananjadhav** [comment] 2023-07-25 18:50
@michaelhaxhiu here's the items for the checklist.

1. We migrated the `MagicCodeInput` to functional component in this [PR](https://github.com/Expensify/App/pull/18398/files). This is where we added the `onFulFill` dependency.
2. I've commented [here](https://github.com/hoangzinh/Expensify-App/commit/307e02a212de32c481fec5920c4e0c2a675036e1#r122661718). 
3. I don't think we should have any activity here, because this is very edge case and could've been covered.
4. I also don't think we need a regression test, we've added our change related comment in the code.


@michaelhaxhiu This is ready for payout on Jul 26, and also eligible for the timeline bonus. I'll raise my request on NewDot for this one. Can you payout the reporting bonus and contributor fees for @hoangzinh?

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:02
Payment summary:
- [ ] @hoangzinh External issue reporter $250
- [ ] @hoangzinh Contributor that fixed the issue $1500 
- [ ] @mananjadhav Contributor+ that helped on the issue and/or PR $1500

**Comment by michaelhaxhiu** [comment] 2023-07-26 19:10
All set, just need manan to ensure he requests payment in new dot. Closing.

**Closed by michaelhaxhiu** 2023-07-26 19:10 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-07-27 04:48
Reviewed details for @mananjadhav. This is accurate and approved for payment in NewDot.
