### ISSUE TITLE
#announce - Not here page opens when #announce room is accessed via 3 dot menu

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48371] opened 2024-08-30 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+ck7830@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch ND app & create a new account
2. Create new workspace
3. Go to Workspace listing page
4. Tap on 3 dot menu
5. tap on Go to #announce room

## Expected Result:
#announce room conversation page should open

## Actual Result:
Not here page opens when #announce room is accessed via 3 dot menu

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/34a29d49-b6f2-42dd-a667-e0b0f5dba555

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-30 21:06
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-30 21:06
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-30 21:14
BE is returning errorFields: `not found`

**Comment by kpadmanabhan** [comment] 2024-08-31 08:05
This is a backend issue. `OpenReport` API returns no reports, instead returns `not found` error.

**Comment by Shahidullah-Muffakir** [comment] 2024-09-01 18:46
The same error occurs when a user  open the **#announce room**  through **Inbox**
The error occurs in the **AuthenticatePusher** endpoint.


https://github.com/user-attachments/assets/461c2ed5-3778-47ee-8f9c-ee6928e6ae1d

**Comment by Shahidullah-Muffakir** [comment] 2024-09-01 18:48
The same error occurs when a user  open the **#announce room**  through **Inbox**
The error occurs in the **AuthenticatePusher** endpoint.


https://github.com/user-attachments/assets/461c2ed5-3778-47ee-8f9c-ee6928e6ae1d

**Comment by CortneyOfstad** [comment] 2024-09-04 20:48
Sorry for the delay here! This was assigned after I went OoO, but reviewing everything now!

**Comment by CortneyOfstad** [comment] 2024-09-04 20:49
Thanks @FitseTLT and @kpadmanabhan for confirming it is a BE issue and @Shahidullah-Muffakir for testing this further! Going to do some testing and see if I can recreate and get some eyes on this!

**Comment by CortneyOfstad** [comment] 2024-09-04 20:53
I was not able to recreate this as it brought me right to the announce room. @FitseTLT @kpadmanabhan or @Shahidullah-Muffakir — are any of you consistently able to recreate?

**Comment by FitseTLT** [comment] 2024-09-04 21:04
> I was not able to recreate this as it brought me right to the announce room. @FitseTLT @kpadmanabhan or @Shahidullah-Muffakir — are any of you consistently able to recreate?

Yep but you should try to open it before adding members to freshly created workspace and it will open the announce room  but after a while it will change to not here page. This should definitely be fixed @CortneyOfstad 

https://github.com/user-attachments/assets/186706ad-93db-4ed5-9091-7c7991c9f487

**Comment by CortneyOfstad** [comment] 2024-09-10 17:34
Thank you for the confirmation here! Getting eyes on this ASAP!

**Comment by FitseTLT** [comment] 2024-09-10 20:52
> Thank you for the confirmation here! Getting eyes on this ASAP!

@CortneyOfstad BTW on a second thought I suspect `#announce` room might not suppose to be created before you add a member to a new workspace (I think I have seen that somewhere). Because `#admin` room works perfect now and also doesn't make sense to have `#announce` room while you are the only member of the workspace. Let's ask an internal engineer  if this is intentional.

**Comment by FitseTLT** [comment] 2024-09-10 22:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
#announce - Not here page opens when #announce room is accessed via 3 dot menu

### What is the root cause of that problem?
Because it doesn't make sense to have announce room before you add a member in a new workspace the BE doesn't create an announce room for a workspace but we create an announce room optimistically here
https://github.com/Expensify/App/blob/e4b1e5af73329b79359cdc2ca04ebe2cb5eda1e0/src/libs/ReportUtils.ts#L5496-L5506
### What changes do you think we should make in order to solve the problem?

1. We should stop creating announce chat report optimistically when we create workspace here
https://github.com/Expensify/App/blob/e4b1e5af73329b79359cdc2ca04ebe2cb5eda1e0/src/libs/ReportUtils.ts#L5496-L5506
we should similarly remove `announceCreatedAction` and `announceReportActionData` there
2. We should remove all announce related report and report actions in [buildPolicyData](https://github.com/Expensify/App/blob/e4b1e5af73329b79359cdc2ca04ebe2cb5eda1e0/src/libs/actions/Policy/Policy.ts#L1608), createDraftWorkspace and createWorkspaceFromIOUPayment

Note: we can think of creating the announce room optimistically when the user adds the first member (when can know that if `policy.chatReportIDAnnounce` is not set or when announceReport doesn't exist as we check [here](https://github.com/Expensify/App/blob/e4b1e5af73329b79359cdc2ca04ebe2cb5eda1e0/src/libs/actions/Policy/Member.ts#L136)) but that would need BE change as we need to pass the announceChatReportID to `ADD_MEMBERS_TO_WORKSPACE` API

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-09-10 22:26
@CortneyOfstad Let's get an engineering 👀 here because I am feeling more confident that the BE is intentionally not creating announceRoom until you add the first member for a new workspace as it doesn't make sense to have one when the only member of the workspace is the creator and the policy `chatReportIDAnnounce` is also `0` in this case.

**Comment by CortneyOfstad** [comment] 2024-09-16 17:39
Thanks @FitseTLT and sorry for the delay here as I was OoO part of last week. I've pinged the team directly and will update as soon as I hear back. Thanks!

**Comment by CortneyOfstad** [comment] 2024-09-18 18:29
Unfortunately, no takers yet [here](https://expensify.enterprise.slack.com/archives/CC7NECV4L/p1726508321526119). Will continue to monitor

**Comment by blimpich** [comment] 2024-09-23 20:37
I can look into this. Investigating what the intended behavior should be.

**Comment by blimpich** [comment] 2024-09-23 20:48
We delay creating the announce room until the policy has 3 members. Code where this happens in the backend [here](https://github.com/Expensify/Auth/blob/b92c6867076a9ef0629612c3ffae693a206eee21/auth/lib/Report.cpp#L7402). PR that introduced this behavior 7 months ago [here](https://github.com/Expensify/Auth/pull/9990). Seems like a reasonable thing to me, though it did cause this bug.

This issue is essentially a duplicate of https://github.com/Expensify/App/issues/34929, which already has [a PR](https://github.com/Expensify/App/pull/48660) out to fix this.

Closing.

**Closed by blimpich** 2024-09-23 20:48 UTC
Labels: Daily, Internal, Bug

**Comment by GeometryDashAPKs** [comment] 2025-06-20 12:28
Interesting bug—navigation issues like this can really disrupt user experience. Reminds me of when users try to Descargar Geometry Dash APK https://geometrydash-apk.com.mx/descargar-geometry-dash-apk/ and end up on the wrong download page.
