### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Expense avatar and Report avatar in LHN look incorrect

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32413] opened 2023-12-03 15:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701439047370489

## Action Performed:
Create an expense on a workspace, submit it

## Expected Result:
 In the LHN (not in #focus mode), the avatar for an expense should have the user's avatar at 40x40 with the small workspace avatar to the bottom right.
For the report, we should have the diagonal avatar pattern where both the workspace avatar and user avatar are the same height/width, but are diagonal from each other

## Actual Result: 
The avatars are incorrect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2023-12-01 at 08 54 52@2x](https://github.com/Expensify/App/assets/38435837/a051e351-1e95-4dc9-bed2-9ed5dd18b3d0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197708be36886dd46</li>
        <li>Upwork Job ID: 1731331203476029440</li>
        <li>Last Price Increase: 2023-12-10</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28036548</li>
<li>shubham1206agra | Contributor | 28036550</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-12-03 17:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense avatar and Report avatar in LHN look incorrect
### What is the root cause of that problem?
Because we use `CONST.AVATAR_SIZE.SMALL_NORMAL` when `isExpenseRequest = true`
### What changes do you think we should make in order to solve the problem?
We need to use only `props.size` or` CONST.AVATAR_SIZE.DEFAULT`  [here](https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/components/LHNOptionsList/OptionRowLHN.js#L119), [here](https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/components/OptionRow.js#L143) and [here](https://github.com/Expensify/App/blob/48b5a29f33ca4cfa8a0b75361f68f6df83455613/src/components/AvatarWithDisplayName.js#L103)
### What alternative solutions did you explore? (Optional)
<img width="394" alt="Screenshot 2023-12-03 at 7 40 19 PM" src="https://github.com/Expensify/App/assets/65789015/1f5d78d0-0cbf-4da0-9147-0e2d17e53148">

**Comment by shubham1206agra** [comment] 2023-12-03 18:30
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Expense avatar and Report avatar in LHN look incorrect

### What is the root cause of that problem?

The diagonal avatar pattern was missing from the Expense report and IOU report because there is a bug in `isWorkspaceThread` function which also gives true for the thread which is not a chat (i.e., IOU or expense).

For design pattern reference
https://github.com/Expensify/App/pull/20512#issue-1749820683

For Avatar size, this looks intentional in the design when `isExpenseRequest` is true.

### What changes do you think we should make in order to solve the problem?

Use the following implementation instead cause the workspace thread will be always of type `chat`
```js
function isWorkspaceThread(report: OnyxEntry<Report>): boolean {
    return isThread(report) && isChatReport(report) && !isDM(report);
}
```
OR
```js
function isWorkspaceThread(report: OnyxEntry<Report>): boolean {
    return isThread(report) && isChatReport(report) && Boolean(getChatType(report));
}
```

We can adjust the size as per the design requirement.

https://github.com/Expensify/App/assets/58412969/9584da73-0454-451b-9b4c-654c71df8265

### What alternative solutions did you explore? (Optional)
NA

**Comment by shubham1206agra** [comment] 2023-12-03 18:33
@shawnborton Can you see the video uploaded here about the diagonal avatar, and see if the cases are correct? I have not adjusted size yet, but will do it later.

**Comment by situchan** [comment] 2023-12-04 04:25
We should hold this until [discussion](https://expensify.slack.com/archives/C049HHMV9SM/p1701439047370489) about expected behavior is concluded

<img width="911" alt="discussion" src="https://github.com/Expensify/App/assets/108292595/79a8fb53-43b7-4512-938d-ddd14f9d13c4">

**Comment by shawnborton** [comment] 2023-12-04 14:26
While I do think that converation has a ways to go, we should at least fix what's currently there before waiting for that convo to finish.

**Comment by shubham1206agra** [comment] 2023-12-05 18:16
@Ollyws I updated my [proposal](https://github.com/Expensify/App/issues/32413#issuecomment-1837561113)

**Comment by shubham1206agra** [comment] 2023-12-11 16:54
@Ollyws I have my designs approved by the design team already

**Comment by rlinoz** [comment] 2023-12-11 17:19
Great!

I think `!isDM(report);` is better than `Boolean(getChatType(report)`.

Hired @shubham1206agra!

**Comment by shubham1206agra** [comment] 2023-12-12 12:13
> @Ollyws Would you mind providing some feedback on my proposal [here](https://github.com/Expensify/App/issues/32413#issuecomment-1837816758)? 🙏
> 
> There's this concern on the selected proposal
> 
> > We have to check that the parentReport is a workspace chat [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/libs/ReportUtils.ts#L703C15-L703C15) (similar to what we did for the workspace task report here)) because chat threads can be created inside the Expense report and money request as well, and they shouldn't be counted as workspace chat thread.

I have already evaluated your comment. This will not matter here. I will post reasoning a little later

**Comment by shubham1206agra** [comment] 2023-12-18 04:13
> @Ollyws Would you mind providing some feedback on my proposal [here](https://github.com/Expensify/App/issues/32413#issuecomment-1837816758)? 🙏
> 
> There's this concern on the selected proposal
> 
> > We have to check that the parentReport is a workspace chat [here](https://github.com/Expensify/App/blob/cc4add5ba055b1d88ef246bf6289092a1344afc5/src/libs/ReportUtils.ts#L703C15-L703C15) (similar to what we did for the workspace task report here)) because chat threads can be created inside the Expense report and money request as well, and they shouldn't be counted as workspace chat thread.

Actually threads created inside the Expense report will be counted as Workspace threads. Similar to workspace task

**Comment by peterdbarkerUK** [comment] 2023-12-29 15:41
Offer links are a bit squiffy, here are some updated links:

@Ollyws could you accept [this one?](https://www.upwork.com/nx/wm/offer/28036548)
@shubham1206agra could you accept [this one](https://www.upwork.com/nx/wm/offer/28036550)?

**Comment by shubham1206agra** [comment] 2023-12-29 15:55
Done

**Comment by peterdbarkerUK** [comment] 2024-01-02 21:09
Sweet, thanks guys:

$500 paid to @shubham1206agra 
$500 paid to @Ollyws 

Could you spin through the regression checklist?

**Comment by rlinoz** [comment] 2024-01-08 13:08
I am not familiar with how we add/remove things from the regression test, do you think it is worth adding this one @peterdbarkerUK ? Thinking that we will need to remove/change this test when we change how we represent each kind of chat.

**Comment by rlinoz** [comment] 2024-01-17 11:26
So I guess we can close this one?

**Comment by peterdbarkerUK** [comment] 2024-01-22 13:36
I agree that we don't need to add regression tests, Olly is right this doesn't need much of a check closing!

**Closed by peterdbarkerUK** 2024-01-22 13:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
