### ISSUE TITLE
[HOLD for payment 2024-06-06] [$250] Tags - Opening tag with certain text shows hhm not here while opening for the first time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41083] opened 2024-04-26 11:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile -- Workspaces-- Workspace
3. Tap more features
4. Enable tags
5. Tap tags
6. Tap add tags
7. Enter ![https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg]
(https://hatrabbits.com/wp-content/uploads/2017/01/random.jpg)
8. Tap save
9. Immediately open the tag created

## Expected Result:
Opening tag with certain text must not show hhm not here while opening for the first time

## Actual Result:
Opening tag with certain text shows hhm not here while opening for the first time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/7e373714-4143-49db-930f-bc953e79951b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178b10f7b05e6e2ba</li>
        <li>Upwork Job ID: 1785427210570833921</li>
        <li>Last Price Increase: 2024-04-30</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by izarutskaya** [comment] 2024-04-26 11:00
We think this issue might be related to the #collect project.

**Comment by bernhardoj** [comment] 2024-04-29 10:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Creating a new tag with a specific text and then open it quickly will show a not found page after a few seconds.

### What is the root cause of that problem?
The issue can be reproduced if the text name contains a colon (:). When we create a tag with a name with a colon, the BE response will give us a different tag name. All the colon is replaced with `\:`, so if we set the name as `a:b`, the BE will return the name as `a\:b`. Based on this comment of a function that cleans it up before showing the name, it's for multi-level tag.
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/PolicyUtils.ts#L236-L241

The policy tag is accessed by its name,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/pages/workspace/tags/TagSettingsPage.tsx#L49-L53

and because the name from the FE doesn't match the new name from the BE, the data is now not found, thus the not found page is shown.

### What changes do you think we should make in order to solve the problem?

We should match the optimistic data with the BE data by replacing the colon with `\:` when creating a new tag or editing an existing tag.

For example,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/actions/Policy.ts#L3242-L3253

```
const newTagName = tagName.replaceAll(CONST.COLON, '\\:');

// then replace all tagName with newTagName
```

_do the same for renaming in [renamePolicyTag](https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/actions/Policy.ts#L3175) for the old and new tag name_

**Comment by johncschuster** [comment] 2024-04-30 21:53
I don't think this is a blocker, but I wonder if entering a URL as the tag name is part of the reason for this behavior.

**Comment by DylanDylann** [comment] 2024-05-02 07:45
@bernhardoj Your proposal looks promising. But we need to understand why the BE changed `:` to `\:` and whether are there any rules on the BE side to change tag names.

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-05-02 07:47
> But we need to understand why the BE changed `:` to `\:` and whether are there any rules on the BE side to change tag names.

@techievivek Before moving forward with this issue, could you help to check the logic in BE and give an answer to the above question

**Comment by johncschuster** [comment] 2024-05-07 22:02
@techievivek bump on the above question!

**Comment by johncschuster** [comment] 2024-05-10 21:01
Bumped in ND!

**Comment by johncschuster** [comment] 2024-05-13 20:41
Bumped in Slack as well!

**Comment by techievivek** [comment] 2024-05-14 09:39
@bernhardoj I am unable to reproduce this issue on my end, can you still reproduce this?

**Comment by bernhardoj** [comment] 2024-05-14 12:24
Yes, I can still reproduce it.

https://github.com/Expensify/App/assets/50919443/c6f3a96d-ff69-4317-936b-8dbaa46ac2cc

**Comment by techievivek** [comment] 2024-05-14 13:02
Ok, thanks, I was able to reproduce this as well on my end.

https://github.com/Expensify/App/assets/35863227/8af55afe-be07-4d35-a41d-f55aef36f4fb

**Comment by techievivek** [comment] 2024-05-14 13:04
We utilize colons (:) in our tags to establish multi-level tag hierarchy. However, it appears that newdot does not currently support multi-level tags. Therefore, I'm uncertain about the expected behavior regarding whether we should allow tag names with colons `:` at this time.

**Comment by techievivek** [comment] 2024-05-14 13:05
@trjExpensify This seems related to wave-collect, do you have any thoughts on this?

**Comment by trjExpensify** [comment] 2024-05-14 20:47
>We utilize colons (:) in our tags to establish multi-level tag hierarchy.

Hm, do we? I thought we utilise the colon to establish a "sub" category only. For example with categories if you add these:

```
Meals
Travel:Airfare
Travel:Taxi
Office supplies
```

When you go to create an expense you see:

```
- Meals
- Travel
  - Airfare 
  - Taxi
- Office supplies
```

So it's still one level, but the `:` operator nests the sub-categories. 

That said, the `:` operator does not apply to tag lists, even on OldDot. I added this list of tags, and got this result on an expense:

<img width="1121" alt="image" src="https://github.com/Expensify/App/assets/16232057/68ee1933-b16e-4315-a84c-79d777a93a47">

<img width="557" alt="image" src="https://github.com/Expensify/App/assets/16232057/39614239-31c8-4032-a274-7284f1e9e402">

Compare that to categories, and you see the colon operator nests the sub-category:

<img width="960" alt="image" src="https://github.com/Expensify/App/assets/16232057/4bcc333e-4895-4cc4-987c-f36da6ce4d1d">

<img width="666" alt="image" src="https://github.com/Expensify/App/assets/16232057/59379418-68e1-40b0-bfb3-4fbcefc20e6c">

**Comment by DylanDylann** [comment] 2024-05-15 08:44
@trjExpensify  Currently, I see that we allow a colon in the category name (there are no subcategory is created)

https://github.com/Expensify/App/assets/141406735/b745eee2-7328-4001-ad49-6e97f2a14c7f

**Comment by DylanDylann** [comment] 2024-05-15 08:46
@trjExpensify @techievivek Could you help to confirm this question: Should we allow a colon in the tag name?

**Comment by trjExpensify** [comment] 2024-05-15 13:28
Yes, we allow colon in category name in NewDot and that achieves the sub-category nesting I highlighted above.

For tags, I think you should be able to use a colon in the name, it just doesn't do anything special - and it certainly doesn't create a multiTag list when you do. (Just like OldDot).

**Comment by nkdengineer** [comment] 2024-05-16 08:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As confirmed [here](https://github.com/Expensify/App/issues/41083#issuecomment-2112534066), we will allow user use a colon in the name

### What is the root cause of that problem?


Currently if the tag name include a colon the BE will replace it to \: . In the FE, we have a function to convert again \: to :

https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/PolicyUtils.ts#L236-L241



### What changes do you think we should make in order to solve the problem?
With the new confirmation, we need a change from BE to avoid replacing the tag name with a colon. In the FE we also don't need [this function](https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/libs/PolicyUtils.ts#L236-L241) to convert the tag name back 

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by DylanDylann** [comment] 2024-05-17 08:29
As [this comment](https://github.com/Expensify/App/issues/41083#issuecomment-2112534066), @nkdengineer's [proposal](https://github.com/Expensify/App/issues/41083#issuecomment-2114393999) looks promising. We don't need to convert anything in the tag name anymore. 

@techievivek What do you think about their proposal?

**Comment by bernhardoj** [comment] 2024-05-17 08:39
I don't think we can fix it from the BE based on this [comment](https://github.com/Expensify/App/issues/32203#issuecomment-1847630109). As @amyevans mentioned from that comment, we need to escape the colon when sending it to the BE which is what this issue is about.

**Comment by DylanDylann** [comment] 2024-05-17 08:50
I see we have some conflicts in decisions. @amyevans @techievivek Could you help to confirm the final expectation for this issue? Should we convert the colon in the tag name?

**Comment by amyevans** [comment] 2024-05-17 20:12
We should match the optimistic data to what is returned from the server as @bernhardoj suggested. I think going down the road of a backend fix is inadvisable because under the hood the OldDot and NewDot API commands for creating a tag are calling the same functions, so the logic needs to be fully compatible and not create bugs on OldDot.

Multi-level tags are sent to/received from the server as a string separated by unescaped colons. So if I have tag lists `Department`, `Location`, and `Project` set up on a workspace, and I create an expense with
Department: Accounting
Location: Africa
Project: Project 1
that is sent/received as `Accounting:Africa:Project 1`

If we want to create a tag with a colon in its name, the colon needs to be escaped.

AFAIK, independent multi-level tags _are_ implemented in NewDot (https://github.com/Expensify/App/issues/32828), it is only _dependent_ multi-level tags at this point that are not.

**Comment by DylanDylann** [comment] 2024-05-20 07:41
Thanks for your comment. As [this comment](https://github.com/Expensify/App/issues/41083#issuecomment-2089822924), @techievivek Let's go with @bernhardoj's proposal

**Comment by DylanDylann** [comment] 2024-05-20 07:41
As [this comment](https://github.com/Expensify/App/issues/41083#issuecomment-2089822924), @techievivek Let's go with @bernhardoj's proposal

**Comment by bernhardoj** [comment] 2024-05-20 09:53
PR is ready

cc: @DylanDylann

**Comment by DylanDylann** [comment] 2024-05-20 10:05
Thanks for the quick PR

**Comment by johncschuster** [comment] 2024-05-31 14:25
Sweet! I'll issue payment for this next Thursday.

@DylanDylann, can you complete the BZ Checklist before then? Thank you!

**Comment by DylanDylann** [comment] 2024-06-06 10:02
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: We change the requirement 
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

Go to workspace page
Enable tag in More features if not enabled yet
Create a new tag with a colon in the name
Open the tag quickly after creating it
Wait for a few seconds for the request to complete
Verify the not found page doesn't show show
Edit the tag name
Verify the tag name is updated
Repeat step 5-6


Do we agree 👍 or 👎

**Comment by johncschuster** [comment] 2024-06-06 12:24
Payment has been issued! Thanks for your contributions! 🎉

**Closed by johncschuster** 2024-06-06 12:24 UTC
Labels: External, Weekly, Awaiting Payment, Bug
