### ISSUE TITLE
[HOLD for payment 2023-06-28] [$1000] FAB menu is displayed abracadabra page when creating a new account

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20609] opened 2023-06-12 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new account
2. Validate by using magic link on another tab

## Expected Result:
Abracadabra page should be displayed in the new tab and the user is logged in in the original tab. 

## Actual Result:
FAB menu is displayed in the abracadabra page. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.26-3

**Reproducible in staging?:** Yes 
**Reproducible in production?:** No, the abracadabra page is not working in Prod. 

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/44479856/9691ead1-f394-432d-a495-23960dc689b7)

https://github.com/Expensify/App/assets/44479856/55b9e872-bc4e-48d2-bf9a-e284c7505789

**Expensify/Expensify Issue URL:** N/A

**Issue reported by:** Applause - Internal team
**Slack conversation:** https://expensify.slack.com/archives/C9YU7BX5M/p1686591327115609?thread_ts=1686084086.585489&cid=C9YU7BX5M

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194703ccd31bf3c81</li>
        <li>Upwork Job ID: 1668685660170141696</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by dangrous** [comment] 2023-06-12 18:50
@cristipaval I haven't been able to pin it down yet but I know you made some changes to the Abacradabra page recently, do you have any thoughts on why this might be happening?

**Comment by dangrous** [comment] 2023-06-12 19:13
I think this might have something to do with https://github.com/Expensify/App/pull/20216 but I'm not certain - it doesn't help that I've only been able to successfully get through the abracadabra page once on staging...

**Comment by dangrous** [comment] 2023-06-12 19:36
fair enough - I still can't replicate so it's making diagnosing very hard. Will look at your proposal in a sec!

**Comment by dangrous** [comment] 2023-06-12 21:43
Hey @isagoico - you mentioned "No, the abracadabra page is not working in Prod." - can you confirm that you're not able to ever load the abracadabra page on production? Thanks!

**Comment by mountiny** [comment] 2023-06-12 22:00
I think the proposal from @allroundexperts sounds good, but I would confirm if this is indeed a deploy blocker and if not I would wait for SWM review of the solution

**Comment by isagoico** [comment] 2023-06-13 00:02
> you mentioned "No, the abracadabra page is not working in Prod." - can you confirm that you're not able to ever load the abracadabra page on production? Thanks!

Yes, this flow was broken on the a previous deployment, here's the bug https://github.com/Expensify/App/issues/20136. The abracadabra page has worked on previous builds on Staging and Prod.

**Comment by dangrous** [comment] 2023-06-13 00:34
That's very helpful, thank you!

**Comment by adamgrzybowski** [comment] 2023-06-13 09:35
I discussed solutions with @WoLewicki and this solution looks good to us! 🚀

**Comment by mountiny** [comment] 2023-06-13 10:02
Jumping in to speed up the process @allroundexperts please go ahead and create a PR

**Comment by dangrous** [comment] 2023-06-13 18:23
Thanks for taking a look! I'm going to add the External label so we get the automations all set - but fire when ready, @allroundexperts

**Comment by mollfpr** [comment] 2023-06-17 15:14
@muttmuure Could you assign me to this issue since I got the PR review done? Thanks!

**Comment by dangrous** [comment] 2023-06-20 21:34
Hm, not sure why Melvin posted that. Not overdue

**Comment by mollfpr** [comment] 2023-06-29 02:42
> [@mollfpr / @allroundexperts] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/12369

> [@mollfpr / @allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/12369/files#r1246026718

> [@mollfpr / @allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be cover this up.

> [@mollfpr / @allroundexperts] Determine if we should create a regression test for this bug.

Yes!

> [@mollfpr / @allroundexperts] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Regression step:
1. Open the App and create a new account
2. Validate by using a magic link on another tab
3. **Verify** that the welcome menu appears in the original tab while the new tab shows the Abracadabra page without the welcome menu.
4. 👍 or 👎

**Comment by muttmuure** [comment] 2023-07-03 13:47
@allroundexperts and @mollfpr invited to apply

**Comment by muttmuure** [comment] 2023-07-06 09:34
Offers sent

**Comment by muttmuure** [comment] 2023-07-11 10:38
Everyone has been paid - closing out

**Closed by muttmuure** 2023-07-11 10:38 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
