### ISSUE TITLE
[$250] Web - Scan-"Description" and "Category" fields are disabled after dismissing "Allow location" modal

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48865] opened 2024-09-10 07:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.31-7
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48620
**Email or phone of affected tester (no customers):** applausetester+shsb22ertt@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite
Make sure the location permission is denied on the browser settings

1. Log in to the new dot app
2. Create a new workspace
3. Go to the workspace chat and click on "+" > Submit expense
4. Go to the scan tab > Choose file
5. Upload a receipt to scan and click on submit
6. After the "Allow location" modal opens up click somewhere else outside the modal
7. After the modal is dismissed observe the "Description" and "Category" fields

## Expected Result:
The "Description" and "Category" fields are clickable and can be edited

## Actual Result:
The "Description" and "Category" fields are disabled and can not be clicked

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4a96570f-fa0d-477d-a677-91abb779bfbd

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833442936289826320</li>
        <li>Upwork Job ID: 1833442936289826320</li>
        <li>Last Price Increase: 2024-09-10</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103895037</li>
<li>Krishna2323 | Contributor | 103896856</li>
<li>ikevin127 | Contributor | 103896860</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by IuliiaHerets** [comment] 2024-09-10 07:17
We think that this bug might be related to #wave-collect - Release 1

**Comment by mkzie2** [comment] 2024-09-10 07:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Description" and "Category" fields are disabled and can not be clicked

### What is the root cause of that problem?

When we press `Confirm`, we first set `didConfirm` then call `onConfirm`:

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/components/MoneyRequestConfirmationList.tsx#L779-L780

`didConfirm` disables the `MenuItem`s for Category and Description:

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/components/MoneyRequestConfirmationListFooter.tsx#L437

At this moment, the location permission modal appears and we close the modal without explicitly deny or grant the permission, at this step, we simply close the modal but `didConfirm` state set above is still `true`:

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/components/LocationPermissionModal/index.tsx#L80-L83

https://github.com/Expensify/App/blob/172504115675f5c6aad87fe4e96e8166b2183b14/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L619

So the root cause is that when we close the permision modal, we simply close it without reseting the states inside `MoneyRequestConfirmationList` states including `didConfirm` which disabled the IOU's menu items previously.

### What changes do you think we should make in order to solve the problem?


Introduce an effect inside `MoneyRequestConfirmationList` which reset `didConfirm` to false when we `startLocationPermissionFlow` changes from `true` to `false`. Of course we need to pass `startLocationPermissionFlow` to `MoneyRequestConfirmationList` as well.

```javascript
useEffect(() => {
   setDidConfirm(!startLocationPermissionFlow);
), [startLocationPermissionFlow]);
```

**Comment by flodnv** [comment] 2024-09-10 09:50
> Optionally, we can reset other states that we already changed in onConfirm before like formError or didConfirmSplit:

Let's do that yes

Can you identify the PR which caused this?

**Comment by mkzie2** [comment] 2024-09-10 09:52
@flodnv The one mentioned in OP: https://github.com/Expensify/App/pull/48620

**Comment by mkzie2** [comment] 2024-09-10 09:52
Am I assigned to this job?

**Comment by akinwale** [comment] 2024-09-10 09:56
@flodnv @ikevin127 should be assigned as C+ here since this is a regression from the mentioned [PR](https://github.com/Expensify/App/pull/48620), but I am available to review if it's an urgent deploy blocker.

**Comment by akinwale** [comment] 2024-09-10 09:58
> Am I assigned to this job?

Usually, for regressions, the original contributor and C+ should be assigned to the issue unless it's urgent and they're unavailable at the time. Please wait for feedback from @flodnv on this.

cc @Krishna2323 @ikevin127 @Julesssss

**Comment by mkzie2** [comment] 2024-09-10 09:59
Thanks @akinwale.

**Comment by flodnv** [comment] 2024-09-10 10:05
Ah, my appologies. I'm confused though: https://github.com/Expensify/App/pull/48620 is not on staging 😕

**Comment by akinwale** [comment] 2024-09-10 10:13
> Ah, my appologies. I'm confused though: #48620 is not on staging 😕

It's included in the [2024-09-09 deploy checklist](https://github.com/Expensify/App/issues/48791).

**Comment by Julesssss** [comment] 2024-09-10 13:31
Thanks @Krishna2323, please feel free to request a review from me.

**Comment by luacmartins** [comment] 2024-09-10 21:24
This is fixed on staging. This is a regression so closing since no payment is due

**Closed** 2024-09-11 08:41 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
