### ISSUE TITLE
[$250] Inviting a secondary login to a workspace appears as `Hidden` in the members table. 

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#52517] opened 2024-11-14 02:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.61-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation** (hyperlinked to channel name): [#convert](https://expensify.slack.com/archives/C07HPDRELLD/p1731548997966639?thread_ts=1731537294.677189&cid=C07HPDRELLD) 

## Action Performed:
1. Invite two users to a workspace
2. Make sure one of the users you invite is a secondary login to an existing account.

## Expected Result:
The user with a secondary login should only appear once in the table, and their primaryLogin should be displayed. 

## Actual Result:
The secondary login invitee appears as `Hidden` in the members table, and there appears to be two entries in the workspace's employeeList. 

## Workaround:
Not that I'm aware of. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/44b56073-0082-4670-88de-75e22bd0f3a4

<img width="464" alt="image" src="https://github.com/user-attachments/assets/a608456e-19c6-49c4-bdf4-366e593110df">

Other example: 

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/bbcbda53-664e-4192-a6da-720b120e607b">

<img width="986" alt="image" src="https://github.com/user-attachments/assets/59ca6f49-cd18-49de-b726-985951947bc3">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866191811810677468</li>
        <li>Upwork Job ID: 1866191811810677468</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

**Comment by truph01** [comment] 2024-11-14 04:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The secondary login invitee appears as Hidden in the members table, and there appears to be two entries in the workspace's employeeList.

### What is the root cause of that problem?
- In:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L328

we don't return if the accountID is 0
### What changes do you think we should make in order to solve the problem?
- Should udpate:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L328

```
            const accountID = Number(policyMemberEmailsToAccountIDs[email] ?? '');
            if(!accountID){
                return
            }
```

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-11-14 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The secondary login invitee appears as Hidden in the members table, and there appears to be two entries in the workspace's employeeList.

### What is the root cause of that problem?
- When we invite an account that is a secondary login to an existing account, BE returns the ```policy.employeeList``` containing both primary and secondary email. But only the primary email has detail data in personalDetailsList.

- The data in here:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L69

only contains the accountID for primary email.

- But in:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L328

in case of secondary email, its ```policyMemberEmailsToAccountIDs[email]``` is ```undefined``` and ```Number(policyMemberEmailsToAccountIDs[email] ?? '')``` is ```0```. And in personalDetailsList data, we has 0 as valid key and its data is not empty so the condition:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L335

is false.
### What changes do you think we should make in order to solve the problem?
- Should update:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L328

```
            const accountID = Number(policyMemberEmailsToAccountIDs[email] ?? '');
            if(!accountID){
                return
            }
```

### What alternative solutions did you explore? (Optional)
- Should update:

https://github.com/Expensify/App/blob/04402e9f47a77f10b3c2c47fefe0931fbf62e4d4/src/pages/workspace/WorkspaceMembersPage.tsx#L328
```
            if (policyMemberEmailsToAccountIDs[email] === undefined) {
                return;
            }
            const accountID = Number(policyMemberEmailsToAccountIDs[email] ?? '');
```

**Comment by twisterdotcom** [comment] 2024-11-18 17:00
Relabelling as Lauren is OOO now.

**Comment by mallenexpensify** [comment] 2024-11-19 00:44
@allgandalf 👀 on the proposal above plz.  
Also... I feel like I have always, semi-frequently, seen `Hidden` for usernames.  Looks like there are `[10 open issues](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+%22hidden%22)` with `hidden` in the title.  Any chance any of these are related and/or could be worked on more _holistically_?

**Comment by NikkiWines** [comment] 2024-11-20 22:31
Yep, agreed that proposal looks good 👍

**Comment by truph01** [comment] 2024-11-24 03:23
[PR](https://github.com/Expensify/App/pull/53038) is ready

**Comment by NikkiWines** [comment] 2024-12-09 10:45
@mallenexpensify, I raised this [here](https://expensify.slack.com/archives/C07HPDRELLD/p1733741041383239?thread_ts=1733178791.716789&cid=C07HPDRELLD) for discussion on closing this issue out.

**Comment by mallenexpensify** [comment] 2024-12-09 18:46
We want to close this issue because the PRs not needed anymore, right? Cuz we hired @truph01 , full compensation is due to both the contributor and C+, per [internal SO](https://stackoverflowteams.com/c/expensify/questions/7582/7583#7583) 
> 100% due if contributor drafted a PR and requested a review.
100% due to C+ if they reviewed the PR.

@truph01 @allgandalf can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021866191811810677468

**Comment by truph01** [comment] 2024-12-10 17:50
@mallenexpensify I accepted the job. Appreciate it 🙏

**Comment by mallenexpensify** [comment] 2024-12-10 22:22
Contributor: @truph01 paid $250 via Upwork
Contributor+: @allgandalf paid $250 via Upwork

**Closed by mallenexpensify** 2024-12-10 22:22 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
