### ISSUE TITLE
[$250] Chat-On adding spade symbol, link is changed to text.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44835] opened 2024-07-04 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a report
3. Enter govinda.com
4. Long tap message and select edit comment
5. Enter °•●●□■ along with link name and save it
6. Note link can be seen
7. Long tap message and select edit comment
8. Now include ♤ along with link name and save it
9. Note link is shown as text
10. Long tap message and select edit comment
11. Remove spade symbol and save it
12. Note now shown as link

## Expected Result:
On adding spade symbol, link must not be changed to text.

## Actual Result:
On adding spade symbol, link is changed to text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2dba183f-730a-4746-a514-af90d78bebba

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1dba0f8a6c08731</li>
        <li>Upwork Job ID: 1808902546673127823</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 103069056</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by izarutskaya** [comment] 2024-07-04 14:12
We think this issue might be related to the  #vip-vsb

**Comment by twisterdotcom** [comment] 2024-07-04 16:35
Okay... this is super niche. I'm going to make it `Monthly` because this is super niche.

**Comment by nkdengineer** [comment] 2024-07-05 11:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On adding spade symbol, link is changed to text.

### What is the root cause of that problem?
In https://github.com/Expensify/expensify-common/blob/2610f15e7fb8d98d19b3841146c693df7be0a5c9/lib/ExpensiMark.ts#L252, we don't match link text that has any emojis.

This was an oversight from this PR https://github.com/Expensify/expensify-common/pull/536, we should not allow link text with only emojis because it will not look good (described in the [issue description](https://github.com/Expensify/App/issues/18386#issue-1695113599)), but if emojis are with other texts, we should still allow it. That will be the behavior consistent with Slack.

### What changes do you think we should make in order to solve the problem?

Put the method [containsOnlyEmojis](https://github.com/Expensify/App/blob/7f9859400ced18e082d27dc81956d0e66b438df4/src/libs/EmojiUtils.ts#L138) inside `expensify-common` (as a method of `Str`)

In https://github.com/Expensify/expensify-common/blob/2610f15e7fb8d98d19b3841146c693df7be0a5c9/lib/ExpensiMark.ts#L252, remove `g1.match(Constants.CONST.REG_EXP.EMOJIS)` and use `containsOnlyEmojis` to check if `g1` contains only emojis.

### What alternative solutions did you explore? (Optional)
In addition to that that check, we could check that length of `g1` is 1, so if the link text contains only 1 emoji, it will not be matched as link text.

**Comment by gawandeabhishek** [comment] 2024-07-07 07:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are trying to resolve the issue where special characters, such as the spade symbol (♤), in comments are being displayed as plain text instead of clickable links on Expensify's staging site.

### What is the root cause of that problem?
The root cause of the problem is that the special characters are not being properly encoded and sanitized, leading to issues in rendering them correctly in HTML comments. This results in the characters being displayed as plain text instead of clickable links.

### What changes do you think we should make in order to solve the problem?
To solve this issue, we utilized the `he`, `dompurify`, and `jsdom` libraries. These libraries help ensure that special characters are correctly encoded and sanitized before being rendered. Here is the updated code that solves the issue:

In `RenderCommentHTML.tsx`:
```typescript
const sanitizedHtml = sanitizeHTML(html);
const decodedHtml = he.decode(sanitizedHtml);

const commentHtml = source === 'email' ? `<email-comment>${decodedHtml}</email-comment>` : `<comment>${decodedHtml}</comment>`;

return <RenderHTML html={commentHtml} />;
```

In `ReportActionItemMessageEdit.tsx`:
```typescript
const [draft, setDraft] = useState(() => {
    if (draftMessage) {
        emojisPresentBefore.current = EmojiUtils.extractEmojis(draftMessage);
    }
    return he.decode(draftMessage);
});

const updateDraft = useCallback(
    (newDraftInput: string) => {
        const { text: newDraft, emojis, cursorPosition } = EmojiUtils.replaceAndExtractEmojis(newDraftInput, preferredSkinTone, preferredLocale);

        if (emojis?.length > 0) {
            const newEmojis = EmojiUtils.getAddedEmojis(emojis, emojisPresentBefore.current);
            if (newEmojis?.length > 0) {
                insertedEmojis.current = [...insertedEmojis.current, ...newEmojis];
                debouncedUpdateFrequentlyUsedEmojis();
            }
        }
        emojisPresentBefore.current = emojis;
        const safeDraft = sanitizeHTML(he.encode(newDraft));
        setDraft(he.decode(safeDraft));
    }
);
```

In `sanitizeHTML.ts`:
```typescript
import { JSDOM } from 'jsdom';
import DOMPurify from 'dompurify';
import he from 'he';

// Initialize DOMPurify with JSDOM
const window = new JSDOM('').window;
const purify = DOMPurify(window);

export default function sanitizeHTML(input: string): string {
    // Encode HTML entities
    const encodedHTML = he.encode(input);

    // Sanitize the encoded HTML
    const sanitizedHTML = purify.sanitize(encodedHTML, {
        USE_PROFILES: { html: true }
    });

    // Decode HTML entities
    const decodedHTML = he.decode(sanitizedHTML);

    return decodedHTML;
}
```

### Why we used this solution:
- **`he` library**: This library is used to encode and decode HTML entities. It ensures that special characters are properly converted to their HTML entity equivalents and back, preventing issues with character rendering.
- **`dompurify` library**: This library is used to sanitize HTML content. It removes any potentially malicious content and ensures that the HTML is safe to be rendered.
- **`jsdom` library**: This library provides a JavaScript implementation of the DOM, enabling server-side manipulation of HTML content. It helps in parsing and sanitizing the HTML content correctly.

By using these libraries, we ensure that special characters are correctly handled and rendered, fixing the issue of them being displayed as plain text instead of clickable links.

### What alternative solutions did you explore? (Optional)
Alternative solutions considered included manually encoding and sanitizing the HTML content. However, this approach was prone to errors and did not provide the comprehensive security and reliability offered by the `he`, `dompurify`, and `jsdom` libraries.

**Comment by gawandeabhishek** [comment] 2024-07-07 07:15
Contributor details
Your Expensify account email: abhishekgawande1667@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d738f432141b6ec7?viewMode=1

**Comment by gawandeabhishek** [comment] 2024-07-07 11:23
## Proposal
[Updated](https://github.com/Expensify/App/issues/44835#issuecomment-2212349512)

**Comment by nkdengineer** [comment] 2024-07-10 12:08
@rayane-djouah I think it still doesn't look good which is why we fixed it earlier in https://github.com/Expensify/App/issues/44835#issue-2390971055

> Actual Result:
Emoji only is accepted as an anchor text and it doesn't look pleasing to the eye

Also it's inconsistent with Slack, in Slack, single-emoji will not be accepted as anchor text.
<img width="161" alt="Screenshot 2024-07-10 at 7 07 14 PM" src="https://github.com/Expensify/App/assets/161821005/90666013-1b06-471d-93d9-3799379e896a">

As you can see in the screenshot, emoji-only (the one above) in Slack will not be accepted as anchor text. Meanwhile emoji-with-text (the one below) will be accepted.

Looking forward to here what @francoisl thinks what should be expected here

**Comment by francoisl** [comment] 2024-07-10 20:09
The original argument that it doesn't look good when there is an emoji in a link is subjective, and so different people will naturally have different opinions on whether they should be accepted or not. 

I believe we try to stay as close as possible to "standard" markdown when possible for our parser, and from a quick look at [this RFC](https://datatracker.ietf.org/doc/html/rfc7763.html), which points to [this site](https://daringfireball.net/projects/markdown/syntax#link) for the syntax, I don't see anything mentioned about restricting specific characters or emojis in links.

Let's go with @bernhardoj's proposal 👍

**Comment by bernhardoj** [comment] 2024-07-11 04:23
expensi-common PR is [here](https://github.com/Expensify/expensify-common/pull/749)

cc: @rayane-djouah

**Comment by bernhardoj** [comment] 2024-07-11 17:53
App PR is ready

cc: @rayane-djouah

**Comment by francoisl** [comment] 2024-07-22 23:17
Hm in that case I think we can just close this and issue payments, what do you think @twisterdotcom?

**Comment by twisterdotcom** [comment] 2024-07-23 12:41
We can close yes. Given the work done, I'm okay with still paying out, even though we'll need to just do away with it.

**Comment by bernhardoj** [comment] 2024-07-23 12:55
I think we are still eligible for full payment. The App PR is just updating the `expensify-common` library version. Most of the work done is in the `expensify-common` repo.

https://github.com/Expensify/App/pull/45556 updates the `expensify-common` update the version to a higher one which includes our fix.

**Comment by twisterdotcom** [comment] 2024-07-24 15:44
Ah okay great, if this is the central issue for payments for all of them, then cool. I agree. Let's go with the full amount of $250 each. Payment Summary coming.

**Comment by twisterdotcom** [comment] 2024-07-25 16:48
Payment Summary:

- @bernhardoj paid $250 via newDot Requests (Contributor)
- @rayane-djouah paid $250 via Upwork [here](https://www.upwork.com/nx/wm/workroom/37782689/overview?nav_dir=pop) (C+)

**Closed** 2024-07-25 16:48 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-07-26 03:10
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-26 18:39
$250 approved for @bernhardoj
