### ISSUE TITLE
user details for new user displays details page similar to group for few seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20978] opened 2023-06-18 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open search
3. Search for any new user
4. Open the user and directly click on user email/phone in header to open details page
5. Observe that it displays details page similar to group, after few seconds reload and observe that now it displays details page properly
## Expected Result: 
App should display new user details page like general individual details page
## Actual Result: 
App displays new user details page like group details page for few seconds
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5c60d857-3fe7-448a-a7cd-b59b69465f05

https://github.com/Expensify/App/assets/43996225/ddaee5bf-8c44-4e54-b4d6-a4a8fc8a8552

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686300608119649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-06-18 12:33
This is dupe of https://github.com/Expensify/App/issues/20567

**Comment by dhanashree-sawant** [comment] 2023-06-18 13:20
Hi @gadhiyamanan, If you check slack reporting date, this issue was reported 1 day before of that issue.

**Comment by michaelhaxhiu** [comment] 2023-06-21 14:22
Closing this and using the other GH since we already started there. @dhanashree-sawant is assigned as bug reporter.

**Closed** 2023-06-21 14:21 UTC
Labels: Daily, Overdue, Bug
