### ISSUE TITLE
Custom units are broken

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#10978] opened 2022-09-13 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open or create any workspace.
2. Attempt to update the custom unit rates.
3. Notice how it just doesn't work.

https://user-images.githubusercontent.com/31285285/190010127-eab7c109-e68a-4afd-a7fa-14c3177a8030.mov

## Expected Result:
Updates to the custom unit rate should be persisted.

## Actual Result:
Updates to the custom unit rate aren't persisted. The policy.customUnits is `null`.

## Workaround:
Reverting changes from https://github.com/Expensify/App/pull/10873 fixes things locally

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** v1.2.0-0
**Reproducible in staging?:** yes
**Reproducible in production?:** no
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jasperhuangg** [comment] 2022-09-13 21:19
@francoisl It's kinda hard to say what specifically is causing the issue since https://github.com/Expensify/App/pull/10873 completely rewrites `withFullPolicy`,but the biggest thing I'm noticing is that we're not calling `Policy.loadFullPolicy` anymore. This means that we'll only have loaded the policy from `AppInit`, which [sets customUnits to be `null`](https://github.com/Expensify/Web-Expensify/blob/f5c0ad778d991a19e5eb97f17fcb7fd5d2a23a20/lib/AppInit.php#L105-L106).

**Comment by jasperhuangg** [comment] 2022-09-13 21:28
@francoisl After reading [the design doc](https://docs.google.com/document/d/1xcqVR5IyH1Olhjww41dvhHoNNUm4lua9zD-2EOSA3Ec/edit) it looks like not calling `Policy.loadFullPolicy` was an intentional design choice to prevent additional chaining, it seems this was an unintended consequence that wasn't considered previously.

I say we revert https://github.com/Expensify/App/pull/10873 for now to avoid blocking the deploy.

**Comment by arosiclair** [comment] 2022-09-13 21:31
For the refactor we moved syncing customUnits to the new [OpenWorkspaceReimburseView command here](https://github.com/Expensify/Web-Expensify/pull/34676). I'm curious how reverting that PR fixes this issue, because I've noticed that changing the custom unit was already very wonky the last time I tried it.

**Comment by jasperhuangg** [comment] 2022-09-13 21:34
@arosiclair The custom unit was fixed recently, but I just compared staging and prod and found it was broken. I also reverted the changes from your PR locally and it fixed the issue.

**Comment by francoisl** [comment] 2022-09-13 22:54
Yeah from my tests, the root of the issue is that on [this line](https://github.com/Expensify/App/blob/1c78eb83004e76d77afde68186410d3118293b65/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L65), `props.policy.customUnits` is `null`, so we don't find the right `customUnitRate`. In turn, when we call the API, [this error](https://github.com/Expensify/Web-Expensify/blob/f5c0ad778d991a19e5eb97f17fcb7fd5d2a23a20/lib/PolicyAPI.php#L3211-L3215) is thrown because we can't find the right custom rate to update.

I'm still looking if there's an easy fix for a bit.

**Comment by francoisl** [comment] 2022-09-13 23:14
https://github.com/Expensify/App/pull/10873 was also the last place we called `Policy.loadFullPolicy()`, so there might also be additional places in the code where we rely on the whole policy being loaded that would now be broken and that we haven't seen yet.

Let's revert the PR to unblock the deploy so that we can look into a proper long-term fix.

**Comment by mallenexpensify** [comment] 2022-09-13 23:19
@jasperhuangg , if you can confirm that this worked properly on production in the past, can you add details to [the RCA sheet ](https://docs.google.com/spreadsheets/d/1u73RE8J1DdX3mDohV1RXgulF6_cke3N_a15Sk-UUdQo/edit#gid=0)so we can track the regression?  Thx

**Comment by arosiclair** [comment] 2022-09-14 14:30
So it looks like `OpenWorkspaceReimburseView` is syncing the policy's customUnit correctly and this is getting passed along to the WorkspaceReimburseView without issue. 

![Screen Shot 2022-09-14 at 10 16 03 AM](https://user-images.githubusercontent.com/6833644/190180471-47715cc4-2640-409f-91d0-ef33789f9a55.png)


However this format is not what the page is expecting. The page is expecting the rates to be set under `onyxRates` not `rates`. Since this is undefined, the field displays as 0.000 and if you try to change it, we send mostly empty data to `UpdateWorkspaceCustomUnitRate` which causes the failure.

@jasperhuangg @yuwenmemon did the customUnits format change recently? And which way is the right way? Should the rates be set under `rates` or `onyxRates`?

**Comment by arosiclair** [comment] 2022-09-14 14:58
When creating a new workspace, the `CreateWorkspace` command actually sets the custom unit rates under both properties and the reimburse view works with this data.

![Screen Shot 2022-09-14 at 10 50 35 AM](https://user-images.githubusercontent.com/6833644/190188443-a1029d0d-58fb-4427-8817-320d287e356c.png)

**Comment by jasperhuangg** [comment] 2022-09-15 16:29
@arosiclair 

Ah that was my doing, sorry if this wasn't made clear! We had to move the rates into `onxyRates` temporarily to ensure that my new custom unit rate changes weren't breaking older clients, which were still accessing from `rates`. 

Notice how in the screenshot `onyxRates` is keyed by ID, while `rates` is just an array of rates. We need the rates to be keyed by ID for them to work with any Onyx updates.

This will actually be removed in https://github.com/Expensify/App/pull/10974, so things should just work afterwards?

**Comment by arosiclair** [comment] 2022-09-15 17:31
> Notice how in the screenshot `onyxRates` is keyed by ID, while `rates` is just an array of rates. We need the rates to be keyed by ID for them to work with any Onyx updates.
> 
> This will actually be removed in #10974, so things should just work afterwards?

Yeah that sounds about right. https://github.com/Expensify/Web-Expensify/pull/34862 should get the rates keyed by ID and then our form should be working correctly again. I'll re-test the withFullPolicy refactor after that stuff gets merged in

**Comment by jasperhuangg** [comment] 2022-09-15 17:32
@arosiclair Sounds like a plan, thanks for waiting on this!

**Comment by francoisl** [comment] 2022-09-15 23:38
The fix was tested on staging https://github.com/Expensify/App/pull/10974#issuecomment-1248425415, closing.

**Closed by francoisl** 2022-09-15 23:38 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Improvement, Hourly
