### ISSUE TITLE
Android/Desktop - Chat - Image is not greyed out after Turn off WiFi

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11149] opened 2022-09-20 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR** https://github.com/Expensify/App/pull/10706

## Action Performed:
1. Launch the app
2. Log in with the HT expensifail account
3. Go to Profile - Settings
4. Click on the avatar picker and upload an avatar.
5. Turn off your device wifi very quickly

## Expected Result:
Image is greyed out after Turn off WiFi

## Actual Result:
Image is not greyed out after Turn off WiFi

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android
- Desktop App

**Version Number:** 1.2.3.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191336502-d8f8104a-78b9-4bae-bfe0-725da083b342.mp4

https://user-images.githubusercontent.com/93399543/191336505-8cbdbbc1-0a74-472d-99e9-fcc503a77e88.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by amyevans** [comment] 2022-09-21 16:50
Based on what I'm seeing in the screen recording, this is expected behavior. The avatar was uploaded, there was enough time elapsed that it finished uploading, and then the wifi was turned off. It's expected that the avatar does not grey out, because it finished uploading. Closing based on that analysis, but if anyone feels differently feel free to reopen.

**Comment by luacmartins** [comment] 2022-09-21 16:51
Came here to say the same thing that @amyevans said above!

**Closed by amyevans** 2022-09-21 16:50 UTC
Labels: Engineering, Daily
