### ISSUE TITLE
[$1000] Offline - Workspace details are still clickable after deleting workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24189] opened 2023-08-06 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace
2. Copy link workspace and open on new tab
3. Force offline
4. Delete above workspace
5. From tab 1, Observe that the options are crossed out but still clickable
## Expected Result: 
Options are crossed and can't still clickable
## Actual Result: 
Options are crossed out but still clickable

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.50-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/02120159-ee1a-402c-8eb2-032afd05215c

https://github.com/Expensify/App/assets/43996225/a2b7796d-3291-489f-96a9-01fe29c6a641

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690889739154479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01552660bbde134ee7</li>
        <li>Upwork Job ID: 1688645526671638528</li>
        <li>Last Price Increase: 2023-08-07</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-06 17:24
## Proposal from @namhihi237 
### Please re-state the problem that we are trying to solve in this issue.
Options are crossed and can't still be clickable after WS was deleted with offline mode
### What is the root cause of that problem?
We have not disabled in WorkspaceInitialPage when workspace has pendingAction = delete here.
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/workspace/WorkspaceInitialPage.js#L71
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/workspace/WorkspaceInitialPage.js#L250
And in `threeDotsMenuItems` we have not disabled the delete option.
And [WorkspaceSettingsPage](https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/workspace/WorkspaceSettingsPage.js#L92C1-L101C43) as the same with Form and `AvatarWithImagePicker`
The same disable button invite in `WorkspaceMembersPage`
### What changes do you think we should make in order to solve the problem?
1. in WorkspaceInitialPage
Here we will add a condition to check the workspace with pendingAction == 'delete' to disable MenuItems and add property to disable the delete action at threeDotsMenuItems
2. In WorkspaceSettingsPage
Same as above, here we add disable condition for Form and AvatarWithImagePicker
3. WorkspaceInviteMessagePage
Here they disable the `invite` button button
4. Optionally we can disable the `invite` button in `WorkspaceMembersPage` and next at `WorkspaceInvitePage`, because we have disabled step invite in (3).
### What alternative solutions did you explore? (Optional)
N/A

**Comment by jeet-dhandha** [comment] 2023-08-07 21:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- In offline mode, after deleting the workspace if we open the workspace through URL then it is showing the workspace page with sections.

### What is the root cause of that problem?
1. The issue is that we are not checking the workspace is deleted or not in below give files.

- Files
    - ReimbursementAccountPage
    - WorkspaceInitialPage
    - WorkspaceInviteMessagePage
    - WorkspaceInvitePage
    - WorkspaceMembersPage
    - WorkspacePageWithSections

2. Below code is not checking the workspace has pendingAction as deleted or not.

```js
shouldShow={_.isEmpty(policy) || !Policy.isPolicyOwner(policy)}
```

### What changes do you think we should make in order to solve the problem?
- We should check the workspace has pendingAction as deleted or not in below given files. 
- We can create a function in Policy.js file to check the workspace has pendingAction as deleted or not.
- But just checking the workspace has pendingAction as deleted or not is not enough, we will also need to update the descriptions.
- So based on `deleted` or `if not permitted` we will update the description.
    - `if not permitted` - `You do not have access to this page. Are you trying to join the workspace? Please reach out to the owner of this workspace so they can add you as a member! Something else? Reach out to ${CONST.EMAIL.CONCIERGE}`
    - `deleted` - `Workspace has been deleted. Please reach out to the owner or ${CONST.EMAIL.CONCIERGE} for more information.`

```js
const workspaceDescription = Policy.hasDeletedPendingAction(policy) ? 'workspace.common.deleted' : 'workspace.common.notAuthorized';
shouldShow={_.isEmpty(policy) || !Policy.isPolicyOwner(policy) || Policy.hasDeletedPendingAction(policy)}
subtitleKey={_.isEmpty(policy) ? undefined :  workspaceDescription}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by grafaleg** [comment] 2023-08-07 22:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The issue at hand is that in our application, when a workspace is deleted and the user is offline, the options for the workspace are crossed out indicating that they are not available. However, these options are still clickable, which is not the expected behavior. The options should be crossed out and unclickable.


### What is the root cause of that problem?

The root cause of the problem is that while the visual representation of the options being unavailable (crossed out) is implemented, the functionality to disable clicking on these options is not. The options' clickable property is not being set to false when they are crossed out.

### What changes do you think we should make in order to solve the problem?

To solve this problem, we need to modify the applyStrikeThrough function in the OfflineWithFeedback component. This function currently applies a strikethrough style to the children elements when needed. We should extend this function to also disable the clickable property of these elements. This can be done by adding a disabled: true property to the props object in the applyStrikeThrough function.

We should also modify the routing logic of our application. When a workspace is deleted, we should remove or disable the corresponding route. 

### What alternative solutions did you explore? (Optional)

An alternative solution could be to handle the disabling of the options at a higher level in the component hierarchy, but this would likely involve more extensive changes and could potentially impact other parts of the application. The proposed solution is more localized and less likely to have unintended side effects.

**Comment by allstarsmen** [comment] 2023-08-09 08:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In offline mode, on the workspace details page, after the workspace was deleted:
- The disabled options are still clickable.
- In the three-dot menu, you can use the Delete button.

### What is the root cause of that problem?

We did not check the `policy.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE` to:
- Disable options completely and block users to access subpages of the workspace details page.
- Remove the Delete button in the three-dot menu

### What changes do you think we should make in order to solve the problem?
1. Add two lines of code as the picture below into [WorkspaceMembersPage.js (https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceMembersPage.js) to block users to access the `Members` page by using URL.

    ![Screenshot 2023-08-09 at 14 51 22](https://github.com/Expensify/App/assets/497313/9a5ec15a-a851-44fb-a94f-e29e1377e896)

2. Add three lines of code as the picture below into [WorkspacePageWithSections.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspacePageWithSections.js) to block users access these pages `Settings`, `Cards`, `Reimbursements`, `Bills`, `Invoices`, `Travel`  by using URL.

    ![Screenshot 2023-08-09 at 14 56 03](https://github.com/Expensify/App/assets/497313/cefbbabd-93bf-41b9-8d4d-db129c5c5258)

3. In [WorkspaceInitialPage.js](https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceInitialPage.js), make some changes like the below to not allow users to click on the options and remove the `Delete` button in the `threeDotsMenuItems`:
  - Create `isWorkspaceDeleted` and `disableClickAction` const as lines 72 and 73 in the picture below
     
     ![Screenshot 2023-08-09 at 15 02 24](https://github.com/Expensify/App/assets/497313/b47b8913-2321-4adc-a9d3-ef5892d94865)

  - Only add the `Delete` button to the `threeDotsMenuItems` if the workspace is not deleted.
  
     ![Screenshot 2023-08-09 at 15 05 48](https://github.com/Expensify/App/assets/497313/026315f8-740b-4216-876c-cd2141f466c6)

  - Replace all `hasPolicyCreationError` with `disableClickAction` from line 212 to line 267
  
     ![Screenshot 2023-08-09 at 15 08 09](https://github.com/Expensify/App/assets/497313/2688cc34-54a5-4eb2-bffd-ea9e08309852)

### Result

https://github.com/Expensify/App/assets/497313/5e22ec96-67ab-482b-a949-ff21d7040a7a

https://github.com/Expensify/App/assets/497313/95873982-764b-4db3-9f59-bdc7ad3f6f65

https://github.com/Expensify/App/assets/497313/0c186b17-84ec-4038-9dc6-948ae434999f

### What alternative solutions did you explore? (Optional)
Not allow users to access all sub-pages of a deleted workspace such as the workspace details page and its sub-pages.

**Comment by NicMendonca** [comment] 2023-08-09 16:48
@parasharrajat yes, sorry that was an oversight. I was able to repro

**Comment by sourcecodedeveloper** [comment] 2023-08-09 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tab synchronization issue in workspace. Create a workspace and open the link of that workspace in a new tab and the force offline from settings. Delete the workspace, notice the tab navigates out of the workspace details page to workspace settings page and the link unclickable but in the first tab, the app stays in workspace details page and the links become crossed out yet clickable. 

### What is the root cause of that problem?
The root cause of the problem is tab synchronization is not correctly happening in both the tabs. After deleting workspace in tab2, tab1 state should also match that of tab2. The user should be navigated out of workspace details page.

### What changes do you think we should make in order to solve the problem?

The solution here is to make use of useEffect and then checking if policy.pendingAction matches CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE

like below

        if(policy.pendingAction == CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)
        {
            Navigation.goBack(ROUTES.SETTINGS_WORKSPACES);
        }

After deleting the workspace in tab 2, tab 1 correctly navigates the user to workspace settings page matching state of tab2. 

Attached below is a functional solution, 

https://github.com/Expensify/App/assets/141340971/90bcc2b9-bcc6-4ef7-89c9-268f86969332

**Comment by sourcecodedeveloper** [comment] 2023-08-09 17:44
@parasharrajat please review proposal

**Comment by sourcecodedeveloper** [comment] 2023-08-10 17:14
@parasharrajat any feedback on the above proposal would be much appreciated.

**Comment by NicMendonca** [comment] 2023-08-11 12:38
upon reflection, I agree this isn’t a problem. Going to close this.

**Closed by NicMendonca** 2023-08-11 12:38 UTC
Labels: External, Daily, Help Wanted, Bug
