### ISSUE TITLE
[HOLD for payment 2024-09-10] [$250] IOU - Message and Notification Swapping in IOU When Transitioning from Offline to Online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46393] opened 2024-07-28 23:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** betlihemasfaw14@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Workspace Chat > Plus Sign > Submit Expense
2. Add amount and merchant, then confirm
3. Go to IOU, switch to offline mode, and generate a notification by changing the date
4. Write a message, then switch back to online mode. Notice the message and notification swap

## Expected Result:
Messages and notifications should remain in place

## Actual Result:
Messages and notifications swap in IOU when translated from offline to online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/94716cba-2baf-4928-b738-f1aa03d54c9f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fdfd49bd9346b4c</li>
        <li>Upwork Job ID: 1818663278050494650</li>
        <li>Last Price Increase: 2024-08-14</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103525574</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by lanitochka17** [comment] 2024-07-28 23:41
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-07-29 10:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Messages and notifications swap in IOU when translated from offline to online

### What is the root cause of that problem?
After we update the money request, we call `saveUpdateInformation` here making the queue paused [here](https://github.com/Expensify/App/blob/00d2c42b4a1d53696e4cb0808ba31fc10028ffcd/src/libs/actions/OnyxUpdates.ts#L144)

https://github.com/Expensify/App/blob/00d2c42b4a1d53696e4cb0808ba31fc10028ffcd/src/libs/Middleware/SaveResponseInOnyx.ts#L38

Then when the queue is unpaused, we merge the pending Onyx data from the response API to Onyx meanwhile other write APIs are not complete. `created` from BE is larger than other report actions makes the order change. 
https://github.com/Expensify/App/blob/00d2c42b4a1d53696e4cb0808ba31fc10028ffcd/src/libs/Network/SequentialQueue.ts#L179
### What changes do you think we should make in order to solve the problem?
We should check if the `numberOfPersistedRequests` is not `0` we will not merge the Onyx update to Onyx DB when the queue is unpaused

```
if (numberOfPersistedRequests === 0) {
    flushOnyxUpdatesQueue();
}
```
https://github.com/Expensify/App/blob/00d2c42b4a1d53696e4cb0808ba31fc10028ffcd/src/libs/Network/SequentialQueue.ts#L179


### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-01 13:20
> Hmm won't this have the effect of no Onyx updates being applied until ALL of the API requests are finished?

@Ollyws Yes, currently if the queue isn't unpause, we still wait until ALL of write API are finished to merge the Onyx update here.

https://github.com/Expensify/App/blob/207365c57858701f397c5aa334c175113a5b8da2/src/libs/Network/SequentialQueue.ts#L161

**Comment by nkdengineer** [comment] 2024-08-02 17:41
@Ollyws it will be called here after all write APIs  are complete.

https://github.com/Expensify/App/blob/207365c57858701f397c5aa334c175113a5b8da2/src/libs/Network/SequentialQueue.ts#L161

**Comment by nkdengineer** [comment] 2024-08-02 17:56
@Ollyws Yeah, I think it's the same.

**Comment by nkdengineer** [comment] 2024-08-02 18:05
Let me check this again.

**Comment by nkdengineer** [comment] 2024-08-05 17:01
@Ollyws Confirmed in Slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1722876261418889?thread_ts=1722832748.084109&cid=C01GTK53T8Q). We can move forward with this solution.

**Comment by nkdengineer** [comment] 2024-08-08 10:24
@Ollyws You're right. The problem is when the queue is paused, the `process` promise is also resolved immediately

https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/libs/Network/SequentialQueue.ts#L66-L68

Then the onyx data is updated here while other write API areas remain in the queue. We should update to only update onyx data if the queue is empty. I tested locally with this change and it works well now. Correct me if I missed something.


```
if (PersistedRequests.getAll().length === 0) {
    flushOnyxUpdatesQueue();
}
```
https://github.com/Expensify/App/blob/9c7c4a1cb9405f64c31c03c4f1fa33c0c041dac0/src/libs/Network/SequentialQueue.ts#L161

**Comment by nkdengineer** [comment] 2024-08-08 10:24
I updated my [proposal](https://github.com/Expensify/App/issues/46393#issuecomment-2255598546)

**Comment by trjExpensify** [comment] 2024-08-09 00:21
From @tgolen's response here, I think we should close this issue. We have many instances of the replay effect in the app, and I'm hesitant of proceeding without a holistic solution to solve them all.

**Comment by tgolen** [comment] 2024-08-09 15:43
I talked with Tom about this one, and I think we'd both like to have the UX flashing solved, but we are definitely both concerned that this is a low-level change that carries a lot of risk. I would like to propose that in order to move forward with @nkdengineer's proposal, that we create an ad-hoc build for the PR and have QA do a full regression test on it to help ensure that everything is still working how it's expected to.

What do you think @nkdengineer and @Ollyws ?

**Comment by nkdengineer** [comment] 2024-08-09 16:18
@tgolen Yeah, look good to me.

**Comment by nkdengineer** [comment] 2024-08-11 14:19
@Ollyws Yes, this is my solution. Can you please share the video about this case?

**Comment by nkdengineer** [comment] 2024-08-12 04:37
@Ollyws I tested and it works well. Am I missing something?

https://github.com/user-attachments/assets/4025cdc1-9a37-4432-b8f7-aa805c94b38b

**Comment by nkdengineer** [comment] 2024-08-12 07:24
> it's only occuring for me on a money request with a very large amount of messages, on a new request it works fine.

@Ollyws Can you please enter `@nkdengineer+s31@outlook.com` in this report and then invite this account to the report then I can test with this, thanks.

**Comment by Beamanator** [comment] 2024-08-13 00:01
Huh, @tgolen since you added some comments and concerns about the proposal in this issue, did you want to be assigned to review as well? 🤷  I'm happy to, just checking before I move forward here

**Comment by tgolen** [comment] 2024-08-13 20:40
Sure, I wouldn't mind keeping an eye on this one. I'll swap you out

**Comment by greg-schroeder** [comment] 2024-08-14 10:43
Okay, thanks @tgolen! Are you able to confirm the contributor assignment? https://github.com/Expensify/App/issues/46393#issuecomment-2283330210

**Comment by tgolen** [comment] 2024-08-14 16:19
OK, yeah. Getting it assigned now. Let's not forget to test this with an ad-hoc build.

**Comment by CyberAndrii** [comment] 2024-08-20 13:12
Accidentally came across this issue and believe it has the same root cause as https://github.com/Expensify/App/issues/46668, where the response from the API is missing the `previousUpdateID` property, resulting in changes being applied in an incorrect order.

In this case, `previousUpdateID` is missing on the `AddComment` request.

![image](https://github.com/user-attachments/assets/6279672f-e78a-499d-9ca1-ee933610c87b)

**Comment by greg-schroeder** [comment] 2024-08-27 05:36
PR is still in review - seems QA identified several issues that'll need to be addressed

**Comment by tgolen** [comment] 2024-09-06 15:39
It looks like the PR has been merged and deployed to production, so I think this is just waiting on the regression period and payments @greg-schroeder.

**Comment by greg-schroeder** [comment] 2024-09-09 06:27
Ah, I guess it didn't get picked up by the automation. 🤔

**Comment by greg-schroeder** [comment] 2024-09-09 06:28
Regression period end 2024-09-10

**Comment by greg-schroeder** [comment] 2024-09-11 09:30
Payment summary:

Contributor: @nkdengineer - $250 - Paid via Upwork
C+: @Ollyws - $250 - You can make a manual request via ND for the reviewer role

**Closed by greg-schroeder** 2024-09-11 09:30 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-11 19:18
$250 approved for @Ollyws
