### ISSUE TITLE
[$500] IOS - Request Money - Requesting money crashes on iPhone 15

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28341] opened 2023-09-27 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Click on green plus icon (FAB)
3. Select Request money 

## Expected Result:
App should not crash

## Actual Result:
App crashes. 

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/abcf953f-1ac8-46ec-bf7d-102e3eef2602

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragsalian 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695755437407139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016bdde1afa8d36ace</li>
        <li>Upwork Job ID: 1709591605958340608</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Contributor | 27246252</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-10-03 20:58
I'll test this with an iPhone 15 tomorrow.

**Comment by mountiny** [comment] 2023-10-04 15:31
Possibly related to [this crash report](https://console.firebase.google.com/u/0/project/expensify-chat/crashlytics/app/ios:com.chat.expensify.chat/issues/ceb8921b6169b346150312efd1882fb2?time=last-seven-days&types=crash&versions=1.3.77%20(1.3.77.3);1.3.77%20(1.3.77.0)&deviceCategories=Mobile:iPhone16,1%E2%87%92iPhone%2015%20Pro&sessionEventKey=e1d3040f900944c6984c9eb95fbb2589_1864524547792132860). Happening on iphone 15 and 15 Pro and here are the crash logs:

[com.chat.expensify.chat_issue_ceb8921b6169b346150312efd1882fb2_crash_session_e1d3040f900944c6984c9eb95fbb2589_DNE_0_v2_stacktrace.txt](https://github.com/Expensify/App/files/12805240/com.chat.expensify.chat_issue_ceb8921b6169b346150312efd1882fb2_crash_session_e1d3040f900944c6984c9eb95fbb2589_DNE_0_v2_stacktrace.txt)

```
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x3886c _assertionFailure(_:_:file:line:flags:) + 264
1  New Expensify                  0x678f30 AVCaptureDeviceFormat.toDictionary() + 437528 (AVCaptureDevice.Format+toDictionary.swift:437528)
2  New Expensify                  0x68c4d8 closure #2 in closure #1 in CameraViewManager.getAvailableCameraDevices(_:reject:) + 136 (CameraViewManager.swift:136)
3  New Expensify                  0x68bc34 closure #1 in CameraViewManager.getAvailableCameraDevices(_:reject:) + 114 (CameraViewManager.swift:114)
4  New Expensify                  0x691408 specialized withPromise(_:_:) + 52 (Promise.swift:52)
5  New Expensify                  0x68c74c @objc CameraViewManager.getAvailableCameraDevices(_:reject:) + 19 (Promise.swift:19)
6  CoreFoundation                 0x32134 __invoking___ + 148
7  CoreFoundation                 0x31bcc -[NSInvocation invoke] + 428
8  CoreFoundation                 0x319f4 -[NSInvocation invokeWithTarget:] + 64
9  New Expensify                  0x539eec -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
10 New Expensify                  0x53c0d0 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 197 (RCTNativeModule.mm:197)
11 New Expensify                  0x53bd58 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 226 (optional:226)
12 libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
14 libdispatch.dylib              0x12998 _dispatch_main_queue_drain + 984
15 libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
16 CoreFoundation                 0x379bc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
17 CoreFoundation                 0x346c8 __CFRunLoopRun + 1996
18 CoreFoundation                 0x33e18 CFRunLoopRunSpecific + 608
19 GraphicsServices               0x35ec GSEventRunModal + 164
20 UIKitCore                      0x22f350 -[UIApplication _run] + 888
21 UIKitCore                      0x22e98c UIApplicationMain + 340
22 New Expensify                  0x7b90 main + 7 (main.m:7)
23 ???                            0x1b0a53d44 (Missing)
```

**Comment by shubham1206agra** [comment] 2023-10-04 17:27
## Proposal
### Please re-state the problem that we are trying to solve in this issue

IOS - Request Money - Requesting money crashes on iPhone 15

### What is the root cause of that problem?

This is due to a bug in the `react-native-vision-camera` in the `getAvailableCameraDevices` function. This should be fixed with https://github.com/mrousavy/react-native-vision-camera/pull/1784

### What changes do you think we should make in order to solve the problem?

Upgrade `react-native-vision-camera` to v3.

### What alternative solutions did you explore? (Optional)
NA

**Comment by shubham1206agra** [comment] 2023-10-04 17:28
I need to test the upgrade. I will make a test branch for testing the upgrade

**Comment by puneetlath** [comment] 2023-10-04 17:29
@shubham1206agra before you do too much work, we might already have someone working on upgrading this internally. I'll check if this is in-process already or not.

**Comment by shubham1206agra** [comment] 2023-10-04 17:34
@puneetlath Let's hold this up for https://github.com/Expensify/App/pull/27820

**Comment by puneetlath** [comment] 2023-10-04 17:36
Ah yep, Andrew just messaged me the same PR 😄

**Comment by shubham1206agra** [comment] 2023-10-04 17:39
But that's v2. Is the wait worth it in this case?
But let us wait for this PR

**Comment by mrousavy** [comment] 2023-10-05 09:48
Let's just (carefully) try upgrading VisionCamera to V3, V2 will soon be deprecated.

**Comment by puneetlath** [comment] 2023-10-13 14:04
So we successfully upgraded to a version of v3 where we don't have the iPhone 15 crash anymore. But we should still work towards upgrading to v3 (though less pressure now).

**Comment by mountiny** [comment] 2023-10-15 14:13
* typo, we are on v2 still but with a crash fix included

**Comment by puneetlath** [comment] 2023-10-15 20:43
Whoops, that's right.

**Comment by mvtglobally** [comment] 2023-10-17 15:16
Issue not reproducible during KI retests. (First week)

**Comment by mountiny** [comment] 2023-10-17 18:38
Yep this should be fixed I think @ntdiary was c+ on the PR

**Closed** 2023-11-01 19:15 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by mrousavy** [comment] 2023-11-01 19:22
Hey @puneetlath - just wondering if I'm also eligible for the bounty here for doing the fix in the VisionCamera repo?
No worries if not! 👍

**Comment by puneetlath** [comment] 2023-11-01 20:52
@mrousavy I just chatted with Andrew and since it was merged before Oct 13, you can bill us for the bounty on that one!

**Comment by johnmlee101** [comment] 2024-03-29 15:02
Not sure how this was tied, ignore that message above :/

**Comment by puneetlath** [comment] 2024-05-04 16:47
Looks like @mananjadhav is due payment here. 

Payment summary: 
- C+ - @mananjadhav - $500 - to be paid via NewDot

@mananjadhav please request on NewDot.

**Comment by JmillsExpensify** [comment] 2024-05-04 17:11
$500 approved for @mananjadhav
