### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Android - LHN is displayed instead Expensify uses Plaid to connect your account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30617] opened 2023-10-30 23:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.2.93.0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to account settings >> Workspace
2. Click on the workspace to view its settings
3. Click on Cards or Reimbursements settings
4. Select "Connect bank account" >> "Connect online with Plaid
5. Put app on background
6. Open app again

## Expected Result:
Expensify uses Plaid to connect your account is displayed instead LHN after putting the app in the background

## Actual Result:
LHN is displayed instead Expensify uses Plaid to connect your account after putting the app in the background

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/90e415ba-7c42-46c1-807c-fa2be04005ed

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f99be3ed1dcad788</li>
        <li>Upwork Job ID: 1719140445807620096</li>
        <li>Last Price Increase: 2023-11-13</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27755311</li>
</ul></li>
    </ul>
</details>

**Comment by nimishdubey2** [comment] 2023-11-01 06:19
s

**Comment by shahinyan11** [comment] 2023-11-01 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - LHN is displayed instead Expensify uses Plaid to connect your account

### What is the root cause of that problem?
This is because iOS and Android handle activity lifecycles differently. For Android we need to reinitialize Plaid Link when the app comes back to the foreground 

### What changes do you think we should make in order to solve the problem?
I suggest to change this part of code [
](https://github.com/Expensify/App/blob/26c27528ae5dec4fe5117440e7e131cd7a28fc28/src/components/PlaidLink/index.native.js#L13C1-L34C12)
like below 
```
    useEffect(() => {
        initializePlaidLink()

        return () => {
            dismissLink();
        };
        // We generally do not need to include the token as a dependency here as it is only provided once via props and should not change
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);


   const  initializePlaidLink = () => {
       props.onEvent(CONST.BANK_ACCOUNT.PLAID.EVENTS_NAME.OPEN, {});
       openLink({
           tokenConfig: {
               token: props.token,
           },
           onSuccess: ({publicToken, metadata}) => {
               props.onSuccess({publicToken, metadata});
           },
           onExit: (exitError, metadata) => {
               Log.info('[PlaidLink] Exit: ', false, {exitError, metadata});
               props.onExit();
           },
       });
    };

    AppState.addEventListener('change', (nextAppState)=>{
        if (!nextAppState.match(/inactive|background/)) {
            initializePlaidLink();
        }
    });
```
### What alternative solutions did you explore? (Optional)
NO

**Comment by s77rt** [comment] 2023-11-01 10:52
@shahinyan11 Thanks for the proposal. Can you please elaborate on your RCA? How is the lifecycle different?

After reopening the App I'm seeing an error which seems pretty much related to this bug

```
 ERROR  Looks like you have configured linking in multiple places. This is likely an error since deep links should only be handled in one place to avoid conflicts. Make sure that:
- You don't have multiple NavigationContainers in the app each with 'linking' enabled
- Only a single instance of the root component is rendered
- You have set 'android:launchMode=singleTask' in the '<activity />' section of the 'AndroidManifest.xml' file to avoid launching multiple instances
```

**Comment by shahinyan11** [comment] 2023-11-01 12:10
@s77rt  Sorry but there was a problem in my proposal and it didn't work completely. I'm currently working on this to fix the problem and create new proposal.

**Comment by shahinyan11** [comment] 2023-11-01 17:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
This is because iOS and Android handle activity lifecycles differently. When the Plaid Link window opens, the Android application goes into background mode, and then when we further change the application state to background and go back, even the `App` and `Expensify` components are mounted again . And because of that the app navigates to initial route

### What changes do you think we should make in order to solve the problem?
I suggest to add new `lastRoute` key in Onyx data and set it  in [useEffect](https://github.com/Expensify/App/blob/f9d11c5c6509245b28570d53440f4fa341ced202/src/components/PlaidLink/index.native.js#L13C1-L34C12) hook of `PlaidLink` component and remove it in function `onExit` . Below you can see modified `useEffect` hook where I added 2 new lines with comment `// New code`

```
  useEffect(() => {
        Onyx.set(ONYXKEYS.LAST_ROUTE, Navigation.getActiveRoute()) 

        props.onEvent(CONST.BANK_ACCOUNT.PLAID.EVENTS_NAME.OPEN, {});
        openLink({
            tokenConfig: {
                token: props.token,
            },
            onSuccess: ({publicToken, metadata}) => {
                props.onSuccess({publicToken, metadata});
            },
            onExit: (exitError, metadata) => {
                Onyx.set(ONYXKEYS.LAST_ROUTE, '') // New code
                Log.info('[PlaidLink] Exit: ', false, {exitError, metadata});
                props.onExit();
            },
        });

        return () => {
            dismissLink();
        };

        // We generally do not need to include the token as a dependency here as it is only provided once via 
         props and should not change
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
```
    
After that,  when the application becomes active ( actually re-renders App.js ) we need to check if "lastRout" exists in the "Onyx" data and go to that route after the navigation is ready.  For this I added `Onyx.connect` in `Navigation.js` file and the function `openLastRoute`  which called in [setNavigationReady](https://github.com/Expensify/App/blob/f9d11c5c6509245b28570d53440f4fa341ced202/src/Expensify.js#L119C1-L124C12) function .

```
let lastRoute;

Onyx.connect({
    key: ONYXKEYS.LAST_ROUTE,
    callback: (val) => {
        lastRoute = val
    },
});

...

function openLastRoute(){
    navigate(lastRoute)
}
```

https://github.com/Expensify/App/assets/46921547/e283064b-1e7e-4708-b764-46499765d5d5

### What alternative solutions did you explore? (Optional)
We can discus about modifying `Navigation.js` to handling if existence of `lastRoute`  with another way

**Comment by s77rt** [comment] 2023-11-02 08:34
@shahinyan11 Thanks for the update. Regarding your RCA:
> When the Plaid Link window opens, the Android application goes into background mode

Any specific reason why this happens on Android only? Is this coming from `react-native-plaid-link-sdk`? 

___

Note: For future proposals please do not post new comments instead just edit the old one

**Comment by shahinyan11** [comment] 2023-11-02 08:52
@s77rt  Yes it is coming from react-native-plaid-link-sdk .  It's possible that this behavior can be changed using `Java` or `Kotlin` at the package level, but I'm not sure because I don't have enough knowledge with those.

**Comment by s77rt** [comment] 2023-11-02 08:57
@shahinyan11 If the bug is coming from react-native-plaid-link-sdk we should probably fix the bug upsteam.

**Comment by shahinyan11** [comment] 2023-11-02 09:01
@s77rt  But on the package side it's not a bug, it's just behavior for android. 
I also noticed that `Plaid` has different integration methods, and there is a way with `Webview`, but I haven't explored it deeply.

**Comment by shahinyan11** [comment] 2023-11-02 09:04
> @shahinyan11 If the bug is coming from react-native-plaid-link-sdk we should probably fix the bug upsteam.
And if so. what should I do next ?

**Comment by shahinyan11** [comment] 2023-11-02 11:16
> @shahinyan11 If the bug is coming from react-native-plaid-link-sdk we should probably fix the bug upsteam.

and if so what should I do

**Comment by shahinyan11** [comment] 2023-11-02 17:44
@s77rt is not the handling on the react native side an option ?

**Comment by s77rt** [comment] 2023-11-02 18:01
It's an option as long as the fix is on react-native-plaid-link-sdk (assuming the bug is on react-native-plaid-link-sdk)

**Comment by shahinyan11** [comment] 2023-11-02 18:28
@s77rt Ok . I will continue to explore the react-native-plaid-link-sdk package until I get a response from you, maybe there will be another option

**Comment by dylanexpensify** [comment] 2023-11-06 09:39
Sounds good, thanks @s77rt! ❤️

**Comment by shahinyan11** [comment] 2023-11-06 11:50
@s77rt @dylanexpensify  I have looked for other ways, but it is not possible to change this behavior in Android. There is only one way which we can try. This is the way to use Webview but Plaid does not recommend using WebViews for new integrations for several reasons:

User Experience: The Plaid Link SDKs for Android, iOS, and React Native are designed to provide a seamless and native experience for users. They are optimized for mobile devices and provide a better user experience than a WebView.

Security: The SDKs are more secure than a WebView integration. They are regularly updated to include the latest security enhancements and to meet evolving industry standards.

Maintenance and Support: Plaid actively maintains and supports the SDKs, ensuring they are up-to-date with the latest features and improvements. On the other hand, support for WebView-based integrations is being phased out.

Future Compatibility: Starting from September 30, 2023, all WebView-based integrations will need to extend the WebView handler for redirects to support certain institutions. This adds an additional layer of complexity to your integration.

For these reasons, Plaid recommends using the native SDKs for new integrations instead of a WebView.

**Comment by s77rt** [comment] 2023-11-06 15:43
@shahinyan11 Thanks for your time but we are not looking for solutions yet. Let's try to have a deeper understanding of the root cause first. As far as I can tell we only assumed that the bug is on `react-native-plaid-link-sdk`. Did you find out what part of code causes the underlaying app to get into background mode?

**Comment by dylanexpensify** [comment] 2023-11-07 09:46
@shahinyan11 any updates?

**Comment by shahinyan11** [comment] 2023-11-07 13:20
> @shahinyan11 Thanks for your time but we are not looking for solutions yet. Let's try to have a deeper understanding of the root cause first. As far as I can tell we only assumed that the bug is on `react-native-plaid-link-sdk`. Did you find out what part of code causes the underlaying app to get into background mode?

It is wrong to call this a bug. This is not a bug at all, this is standard android OS behavior. we should to integrate with Webview or handle it on the application side ?

**Comment by shahinyan11** [comment] 2023-11-07 13:44
@s77rt , @dylanexpensify  To be honest, I don’t understand what you. Why do we call it a bug? This can be called a bug for the business logic of our application, but it is not a bug at the package level. The Android SDK behaves like this.

**Comment by s77rt** [comment] 2023-11-07 16:19
@shahinyan11 If the bug is upstream it should be fixed upstream. Applying a app-level solution to fix something in the plaid sdk is a workaround.

I'm not really totally sure how react-native-plaid-link-sdk invokes its activity causing the Expensify App to get into background mode. If this is something that is enforced by Android then we would probably have nothing to do here. Regardless we still need to confirm the root cause.

**Comment by shahinyan11** [comment] 2023-11-08 17:34
@s77rt The react-native-plaid-link-sdk works by invoking the Plaid Link flow, which is a
separate activity from our main application. 
there isn't a way to keep our app's Activity in the foreground at the same time
as the Plaid Link window. This is due to how Android manages Activities.
In Android, only one Activity can be in the foreground at a time (i.e., interacting with
the user). When we start a new Activity (like the Plaid Link flow), it becomes the
foreground Activity and our current Activity goes into the background.
This is standard Android behavior and is not something that can be changed from
within the Plaid SDK or our app. The Android operating system manages the
transition between Activities to ensure a consistent user experience across all apps .

You can see the function where written the logic of starting new activity  [here](https://github.com/plaid/react-native-plaid-link-sdk/blob/4e07b0ba75a1b3f7b26aac1ead7a037cb96b2b61/android/src/main/java/com/plaid/PlaidModule.kt#L229C1-L283C4) and the file where calls this function [here](https://github.com/plaid/react-native-plaid-link-sdk/blob/4e07b0ba75a1b3f7b26aac1ead7a037cb96b2b61/src/PlaidLink.tsx#L48C1-L64C7)

**Comment by s77rt** [comment] 2023-11-08 17:55
@shahinyan11 Thanks for the update. That was helpful! Since we cannot prevent the App from going into background mode. Can we figure out why having the app running in background after Plaid messes up the rest of the flow?
1. Open App (App in foregroung)
2. Launch Plaid (App in background)
3. Open App again
4. App is reinitialised

In step 4, what is causing the re-initialization?

**Comment by shahinyan11** [comment] 2023-11-10 10:44
@s77rt  This behavior could be due to how Android manages its activity lifecycle. When we leave the app, Android might be destroying the activity hosting our app to free up resources,  such as memory, for other apps that are in the foreground and actively being used by the user and when we click the app icon, a new activity is created, causing our app to restart. Android manages its resources very carefully to ensure smooth performance and a good user experience. 

But I found a solution to stop this behavior . The solution is update [this line](https://github.com/Expensify/App/blob/358e4b123e14a27050edc7b59443bf0102c9e487/android/app/src/main/AndroidManifest.xml#L31) to  `android:launchMode="singleInstance"` .

And after that, we need to open the Plaid link window again because it closes after going back.  For this I made below changes .

1. The [onExit](https://github.com/Expensify/App/blob/358e4b123e14a27050edc7b59443bf0102c9e487/src/components/PlaidLink/index.native.js#L22) function to below
```
  onExit: ({metadata}) => {
      Log.info('[PlaidLink] Exit: ', false, {metadata});
      props.onExit(metadata.status);
  },
```

2.  The [onExitPlaid](https://github.com/Expensify/App/blob/358e4b123e14a27050edc7b59443bf0102c9e487/src/pages/ReimbursementAccount/BankAccountPlaidStep.js#L116C1-L116C81) prop to below
```
onExitPlaid={(status) => {
    BankAccounts.setBankAccountSubStep(null)

    if(!status){
        BankAccounts.openPlaidView();
    }
}}
```

**Comment by shahinyan11** [comment] 2023-11-10 13:32
## Proposal
[Updated](https://github.com/Expensify/App/issues/30617#issuecomment-1789383290)

**Comment by s77rt** [comment] 2023-11-10 17:20
@shahinyan11 Thanks for the update. Can you please explain why using `singleInstance` mode works over `singleTask`? Per the [docs](https://developer.android.com/guide/components/activities/tasks-and-back-stack) the singleTask mode won't create a duplicate instance of the root activity (App in this case).

> The system creates the activity at the root of a new task or locates the activity on an existing task with the same affinity. **If an instance of the activity already exists, the system routes the intent to the existing instance through a call to its [onNewIntent()](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)) method, rather than creating a new instance.** Meanwhile all of the other activities on top of it are destroyed.

**Comment by shahinyan11** [comment] 2023-11-10 17:46
> @shahinyan11 Thanks for the update. Can you please explain why using `singleInstance` mode works over `singleTask`? Per the [docs](https://developer.android.com/guide/components/activities/tasks-and-back-stack) the singleTask mode won't create a duplicate instance of the root activity (App in this case).
> 
> > The system creates the activity at the root of a new task or locates the activity on an existing task with the same affinity. **If an instance of the activity already exists, the system routes the intent to the existing instance through a call to its [onNewIntent()](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)) method, rather than creating a new instance.** Meanwhile all of the other activities on top of it are destroyed.

`SingleTask` 
- If an activity instance already exists at the top of a task's stack (in the same task), the system will send an intent to that instance by calling its `onNewIntent()` method, instead of creating a new instance.
- If the activity is not at the top of the task stack, a new instance will be created and pushed to the top of the stack. `( This case is our. The plaid link activity becomes top  activity and after it when we press app icon our main activity creates again )`

`SingleTask`
- When a new activity is started with `singleInstance` mode, if the activity already exists in another task, a new task will be created for that instance. This means that only one instance of an activity is allowed in the entire system, and it is isolated in its own task.
- This mode is typically used for activities that need to be isolated from the rest of the application, such as a standalone application or a component that should not be part of the normal flow of activities.

**Comment by shahinyan11** [comment] 2023-11-10 19:30
> @shahinyan11 Thanks for the update. Can you please explain why using `singleInstance` mode works over `singleTask`? Per the [docs](https://developer.android.com/guide/components/activities/tasks-and-back-stack) the singleTask mode won't create a duplicate instance of the root activity (App in this case).
> 
> > The system creates the activity at the root of a new task or locates the activity on an existing task with the same affinity. **If an instance of the activity already exists, the system routes the intent to the existing instance through a call to its [onNewIntent()](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)) method, rather than creating a new instance.** Meanwhile all of the other activities on top of it are destroyed.

`SingleTask` 
- If an activity instance already exists at the top of a task's stack (in the same task), the system will send an intent to that instance by calling its `onNewIntent()` method, instead of creating a new instance.
- If the activity is not at the top of the task stack, a new instance will be created and pushed to the top of the stack. `( I think this is our case. The PlaidLink activity becomes at the top and after it, when we click on the application icon, our main activity is created again. )`

`SingleInstance`
- When a new activity is started with `singleInstance` mode, if the activity already exists in another task, a new task will be created for that instance. This means that only one instance of an activity is allowed in the entire system, and it is isolated in its own task.
- This mode is typically used for activities that need to be isolated from the rest of the application, such as a standalone application or a component that should not be part of the normal flow of activities.

**Comment by s77rt** [comment] 2023-11-11 11:03
@shahinyan11 But plaid is not started in `singleTask` mode, is it? The default is `standard`

**Comment by shahinyan11** [comment] 2023-11-11 11:17
> @shahinyan11 But plaid is not started in `singleTask` mode, is it? The default is `standard`

Yes

**Comment by s77rt** [comment] 2023-11-11 20:49
@shahinyan11 I don't see how is plaid launched with `singleTask` mode. No mode is specified so it should be launched with `standard`.

**Comment by s77rt** [comment] 2023-11-13 17:08
@shahinyan11 Although the use of `singleInstance` seems to fix the reinitialization issue I'm not sure if it is fixing the root cause.

I think we still need to better understand the root cause

**Comment by s77rt** [comment] 2023-11-13 19:14
A new release of `react-native-plaid-link-sdk` is available. It mentions a change in the activity.

> Change LinkActivity to SingleInstance to fix issue with OAuth Redirects on Android 14.

https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v11.0.1

Perhaps this would fix our issue?

**Comment by dylanexpensify** [comment] 2023-11-14 09:51
Interesting, @s77rt what would this entail?

**Comment by s77rt** [comment] 2023-11-14 18:34
Tested with [v10.9.1](https://github.com/plaid/react-native-plaid-link-sdk/releases/tag/v10.9.1) (which also includes the activity launch mode change) but didn't help

**Comment by s77rt** [comment] 2023-11-14 18:40
@bernhardoj Thanks for the confirmation. `singleInstance` is the only mode that looks promising so far but it may not be the right mode

**Comment by shahinyan11** [comment] 2023-11-14 19:07
> I can confirm that this issue is caused by the `singleTask` of `launchMode`. Here is a video of the "issue" on a native Android project.
> 
>  Screen.Recording.2023-11-14.at.19.41.42.mov 
> When we press the app icon from the app launcher, it will launch the activity that has this intent-filter <img alt="image" width="547" src="https://user-images.githubusercontent.com/50919443/282824994-3cba5d74-4b72-4277-b2df-6f9fab65a90b.png">
> 
> Because our app main activity has a `launchMode` set to `singleTask`, it will clear the plaid activity from the stack.
> 
> React native project set the `launcMode` to `singleTask` by default though (maybe because RN is designed as a single activity app), so I don't know which launchMode we should use.

@s77rt @bernhardoj Our problem is not that the plaid link window does not stay open after returning to the foreground. this behavior works absolutely correct. We need reinitialize plaid link after coming back . 
Our main problem is that the application does not save the current state and does not stay on the last screen. It starts from scratch and goes to the main screen.

**Comment by s77rt** [comment] 2023-11-15 14:28
I agree that it may be best to keep the App `launchMode` untouched and fix this on Plaid SDK level especially that we know Onfido is doing it correctly.

**Comment by shahinyan11** [comment] 2023-11-16 00:34
@s77rt  After a lot of research I found the problem . Turns out the plaid link adds several different activities . And there is an activity with `lunchMode="singleInstance" `. I downloaded plaid link example from gitHub and check this. It works correct and I saw that there is not activity with `lunchMode="singleInstance" `.  After it  I tried to use the same package version in our app which was in example project  and it works .

**Comment by shahinyan11** [comment] 2023-11-16 00:49
## Proposal
[Updated](https://github.com/Expensify/App/issues/30617#issuecomment-1789383290)

**Comment by s77rt** [comment] 2023-11-16 17:24
@shahinyan11 Thanks for the update. Upgrading to 10.8.0 seems to work fine. That should be enough to fix the reinitialization problem. I don't see the need to reopen plaid especially since it's going to be a hack and all the process you went through will be lost already. Also the final outcome so far is going to be similar to that of Onfido which is fine.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/30617#issuecomment-1789383290)

**Comment by s77rt** [comment] 2023-11-20 13:29
@robertjchen https://github.com/Expensify/App/issues/30617#issuecomment-1814904843

**Comment by robertjchen** [comment] 2023-11-20 18:11
Reviewed! Agreed with the proposal 👍

**Comment by shahinyan11** [comment] 2023-11-21 06:31
I expect my review request to be ready for review by the end of today.

**Comment by dylanexpensify** [comment] 2023-11-22 09:36
Nice! @s77rt to review!

**Comment by dylanexpensify** [comment] 2023-12-05 19:16
Payment upcoming!

**Comment by shahinyan11** [comment] 2023-12-08 08:00
@dylanexpensify the marked day has passed, but I have not yet received payment ? Is there any problems ?

**Comment by shahinyan11** [comment] 2023-12-11 07:52
@dylanexpensify

**Comment by dylanexpensify** [comment] 2023-12-11 08:43
Apologies! Processing now @shahinyan11!

**Comment by dylanexpensify** [comment] 2023-12-11 08:44
Payment summary:
- Contributor: @shahinyan11 $500
- Contributor+: @s77rt $500

Please apply!

**Comment by dylanexpensify** [comment] 2023-12-11 08:46
@shahinyan11 offer sent!

**Comment by shahinyan11** [comment] 2023-12-11 09:01
@dylanexpensify  applied

**Comment by dylanexpensify** [comment] 2023-12-11 09:05
paid!

**Closed by dylanexpensify** 2023-12-11 09:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by shahinyan11** [comment] 2023-12-11 09:20
@dylanexpensify Are not you leaving reviews at all? )
