### ISSUE TITLE
[$125] Split bill - Split Bill description on Details page is empty in Group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29496] opened 2023-10-12 21:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Click the + icon in a Group conversation > Split Bill
3. Select Split on any user > Next
4. Enter description, date and merchant
5. Create the bill split
6. Click on the bill split preview

## Expected Result:
Description should be saved and visible

## Actual Result:
Description field is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/88e2164e-1796-4391-b846-a69023f4eee4

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2dd27f3e4c1c58d</li>
        <li>Upwork Job ID: 1712586612101890048</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-12 21:50
discussed [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1697146466937949?thread_ts=1697145018.472599&cid=C01GTK53T8Q), removing the blocker and exporting this

**Comment by trjExpensify** [comment] 2023-10-13 09:42
@jeet-dhandha can you look into this regression from your PR please?

**Comment by jeet-dhandha** [comment] 2023-10-13 10:25
@bernhardoj Please share a video with the PR’s code and a video after reverting the code. As then only i can be sure its a regression from my PR. And also do check that the bugs fixed in the PR are also not coming back.if they are then the regression loop will go on forever.

Thanks in advance.

**Comment by bondydaa** [comment] 2023-10-17 19:09
@bernhardoj @jeet-dhandha what's the status here?

**Comment by jeet-dhandha** [comment] 2023-10-18 04:08
I am OOO this and next week due to health reasons.

**Comment by maddylewis** [comment] 2023-10-23 02:45
@situchan - have you been able to reproduce this bug recently?

**Comment by situchan** [comment] 2023-10-24 11:20
I am not able to reproduce on latest main

**Comment by trjExpensify** [comment] 2023-10-24 13:15
Confirming you tested on Android native?

**Comment by situchan** [comment] 2023-10-24 13:30
Tested android as well.

**Comment by bondydaa** [comment] 2023-10-24 21:24
going to close this out then

**Closed by bondydaa** 2023-10-24 21:24 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
