### ISSUE TITLE
Can't create workspace after deleting workspace (multiple tabs with new dot)

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#11349] opened 2022-09-27 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create expensifail account in NewDot
2. Create workspace
3. Open New dot in a second tab (keeping the first one open)
4. Delete the workspace
5. Try to create the workspace again -> Fail

## Expected Result:
Describe what you think should've happened

## Actual Result:
Workspace is not created, nothing happens in the UI and we get a console error:

![image](https://user-images.githubusercontent.com/87341702/192602574-2137b242-87f1-4a35-8724-0976aa27bc72.png)
![image](https://user-images.githubusercontent.com/87341702/192602624-b1196477-24da-4d2e-bf8f-d5d810cf9150.png)

## Workaround:
None that I know of

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 
**Reproducible in staging?:**  YES
**Reproducible in production?:**  YES
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Found while QA'ing this: https://github.com/Expensify/Web-Expensify/pull/34943

**Comment by aldo-expensify** [comment] 2022-09-27 18:12
The bug could be related to this PR: https://github.com/Expensify/App/pull/10563

![image](https://user-images.githubusercontent.com/87341702/192604297-0cd88049-928d-4a4e-9ebc-b458394dd9e5.png)

**Comment by aldo-expensify** [comment] 2022-09-27 18:13
cc @Justicea83

**Comment by Justicea83** [comment] 2022-09-27 19:50
Oops!, I think the solution should be straight forward

**Comment by Justicea83** [comment] 2022-09-27 20:03
Am not able to reproduce this.
<img width="614" alt="Screenshot 2022-09-27 at 20 02 47" src="https://user-images.githubusercontent.com/26106822/192624247-28ddbe18-c38c-4a43-850b-d32bd0e72d5e.png">

Deleting and creating the workspaces just work

**Comment by aldo-expensify** [comment] 2022-09-27 20:04
hum, are you testing in dev? I reproduced it in staging and production

**Comment by Justicea83** [comment] 2022-09-27 20:05
@aldo-expensify can you please add a video recording on how you reproduce this?

**Comment by aldo-expensify** [comment] 2022-09-27 20:05
can you try signing out and signing in with that account and then trying to create the workspace?

**Comment by aldo-expensify** [comment] 2022-09-27 20:22
Hmm I see now that the wonkyness comes from having two tabs with new expensify open:

https://user-images.githubusercontent.com/87341702/192627094-67e1189d-82af-413e-a029-c1596a46cbc1.mov

Steps:

1. Login in New Dot
2. Open a second tab, both should have the same account logged
3. Create a workspace... it will show up in the LHN and disappear and show up and disappear... refresh until it looks fine
4. Delete the workspace
5. Can't create the workspace again

I'm not sure about how to proceed here. This can happen in a normal use case because:

1. You open New Expensify in tab 1, create an account
2. In a different tab, you go to your email and click the magic link... this will open a new tab with new Expensify
3. You set your password in the second New Expensify tab... 
4. You have two tabs with New Expensify logged in => wonky behaviour when creating/deleting workspaces

**Comment by aldo-expensify** [comment] 2022-09-27 20:32
Update steps to mention to open multiple tabs

**Comment by Justicea83** [comment] 2022-09-27 21:09
I tested in production

**Comment by Justicea83** [comment] 2022-09-27 21:19
I can reproduce now(in prod), after opening 3 tabs, testing in dev to see if I can reproduce as well

**Comment by Justicea83** [comment] 2022-09-27 21:25
I think the bug actually has to do with the deletion of the workspace(policy), I can confirm that the onyx keys aren't properly cleared as you can see clearly in the screenshot below.
<img width="421" alt="Screenshot 2022-09-27 at 21 23 28" src="https://user-images.githubusercontent.com/26106822/192638491-f2d4a067-693c-4afa-8c54-b0527c7b868f.png">
Instead of removing them all together, I'm seeing undefined as the value to the keys

**Comment by aldo-expensify** [comment] 2022-09-27 22:03
@Justicea83 I'll have a look on those keys with undefined values once I start woking on the workspace delete stuff

I asked about the problem with multiple tabs here: https://expensify.slack.com/archives/C02HWMSMZEC/p1664310475053539

**Comment by Justicea83** [comment] 2022-09-28 07:44
Since this issue is being looked into [here](https://github.com/Expensify/Expensify/issues/229633), I'll close it out and see if the solution fixes this.

**Closed by Justicea83** 2022-09-28 07:44 UTC
Labels: Engineering, Daily
