### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] [$250] Tags - Console error when disabling tag when created offline on web, app crashes on iOS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42885] opened 2024-05-31 02:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** exp around https://expensify.testrail.io/index.php?/tests/view/4587396&group_by=cases:section_id&group_order=asc&group_id=296081
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Create a new workspace.
4. Go to workspace settings > More features.
5. Enable Tags.
6. Go to Tags.
7. Add a tag.
8. Click on the tag.
9. Disable the tag.

## Expected Result:
Tag can be disabled.

## Actual Result:
Tag cannot disabled. Console error shows up on web. App crashes on iOS.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop 

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/4f6e204d-b6bf-4e32-8528-10874c4bb3c4

https://github.com/Expensify/App/assets/43996225/365e8eac-0cd5-42d4-b6ca-c08d3545fba8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01788b9ab12b2eb04a</li>
        <li>Upwork Job ID: 1797634804417064960</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 102575766</li>
<li>tienifr | Contributor | 102577178</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by kavimuru** [comment] 2024-05-31 02:10
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by kavimuru** [comment] 2024-05-31 02:10
We think this bug might be related to #wave-collect - Release 1

**Comment by hayata-suenaga** [comment] 2024-06-03 16:51
@GandalfGwaihir,

thank you for reviewing the PR. Exactly which line is throwing an error?

I'm trying to understand which change from [the PR](https://github.com/Expensify/App/pull/42315) caused the regression

**Comment by hayata-suenaga** [comment] 2024-06-03 16:52
I'll assign @tienifr for the fix meantime. Let's discuss more details in the PR if necessary 😄

**Comment by roryabraham** [comment] 2024-06-04 00:57
I think this failure is also a sign that something's incorrectly typed.

**Comment by mountiny** [comment] 2024-06-04 13:36
A different PR ended up fixing this. I suggest a payment of $75 to @tienifr @Nodebrute @allgandalf for their help driving this ahead, but I am afraid we cannot offer more

**Comment by hayata-suenaga** [comment] 2024-06-05 07:15
payment summary -> https://github.com/Expensify/App/issues/42885#issuecomment-2147557414

**Comment by sakluger** [comment] 2024-06-10 20:24
Hey @hayata-suenaga or @allgandalf, could you please confirm if this is a regression from https://github.com/Expensify/App/issues/42314? If so, I'll need to adjust the payment for that bug accordingly.

**Comment by sakluger** [comment] 2024-06-11 14:07
Hey @allgandalf, @mountiny's commentdoesn't totally answer my question. I'm asking if this is a regression of https://github.com/Expensify/App/issues/42314 because I need to know if it will affect payment of that other issue.

**Comment by mountiny** [comment] 2024-06-12 12:42
@sakluger yes it was a regression from https://github.com/Expensify/App/pull/42315

**Comment by sakluger** [comment] 2024-06-12 15:48
@mountiny thanks! I'll adjust the payout accordingly.

**Comment by bfitzexpensify** [comment] 2024-06-18 14:26
@allgandalf no then, we are all good. Closing this out.

**Comment by bfitzexpensify** [comment] 2024-06-26 09:07
All paid out here, closing this out

**Closed by bfitzexpensify** 2024-06-26 09:07 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
