### ISSUE TITLE
[$500] Web - SmartScanning - Request details page is blank if another scanning in progress

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38474] opened 2024-03-18 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2730084
**Email or phone of affected tester (no customers):** [applausetester+bpcategory@applause.expensifail.com](mailto:applausetester+bpcategory@applause.expensifail.com)
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User is logged in NewDot.
1. Open any chat and make 'Request money'
2. Choose Scan > upload receipt
3. Make another 'Request money' with another receipt
4. Open Report conversation
5. Click on request preview of request that finished SmartScanning.

Receipts:
![walmart receipt](https://github.com/Expensify/App/assets/93399543/08aed88c-27b6-4136-83dd-07c169a07af4)
![Receipt Example](https://github.com/Expensify/App/assets/93399543/fabf9834-d1ec-4cb6-8581-185b563baf95)

## Expected Result:
Expect to see request details page.

## Actual Result:
Request details page is blank. On LHN chan name is Hidden with 'No activity yet' preview.
On report conversation page, request that finished SmartScanning has a whisper 'Only visible to you'.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/25b49bd5-2664-4050-9503-692d58243f22

![image](https://github.com/Expensify/App/assets/93399543/e2629fc5-9b6f-47d9-9e8f-f6eacdaa11c4)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e944ecedfe59496</li>
        <li>Upwork Job ID: 1769751723698761728</li>
        <li>Last Price Increase: 2024-03-25</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-18 15:04
@anmurali I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-18 15:07
We think that this bug might be related to #wave-collect RELEASE 1

**Comment by mountiny** [comment] 2024-03-18 15:12
It reminds me of the bug where the transaction thread report has not been created using the optimistic data sent from client.  Dont have the link right now

**Comment by mountiny** [comment] 2024-03-18 15:44
Seems like carlos confirmed that problem should be fixed. I think we can go ahead and make this external, maybe we are passing wrong ids with the second request

**Comment by Pranav2612000** [comment] 2024-03-19 14:20
Inspecting it further, but it seems like a backend issue, the `openReport` api returns the report data containing `parentReportId` as 0 causing it to behave this way.

<img width="1344" alt="image" src="https://github.com/Expensify/App/assets/20909078/01346f7a-9040-4184-a364-c84491931a2f">

**Comment by mollfpr** [comment] 2024-03-21 18:22
No proposal is due for a review.

**Comment by anmurali** [comment] 2024-03-25 14:55
@mollfpr do you agree it is a BE issue though because if it is we should take it internal

**Comment by anmurali** [comment] 2024-03-28 20:17
@mollfpr I just need confirmation on whether or not it is a BE issue though as that impacts how we move forward with assignments

**Comment by mollfpr** [comment] 2024-03-29 07:25
After further digging and testing again on the latest DEV, I can reproduce the issue but instead, get the blank page, it's shows the transaction detail page for a moment then replaces it with the regular report.


https://github.com/Expensify/App/assets/25520267/ffcb22ef-6054-4493-8b6e-a704cd946dd2

The issue only happens after the scan is complete, and the `report` data we get from the API differs between scanning and scan complete.



<details>
<summary>Report data while scanning</summary>

```
{
    "avatarUrl": null,
    "chatReportID": "5750474469840668",
    "chatType": "",
    "currency": "USD",
    "description": "",
    "fieldList": null,
    "hasOutstandingChildRequest": false,
    "hasParentAccess": true,
    "iouReportID": null,
    "isCancelledIOU": false,
    "isDeletedParentAction": null,
    "isOwnPolicyExpenseChat": false,
    "isPinned": false,
    "isWaitingOnBankAccount": false,
    "lastActorAccountID": "",
    "lastMentionedTime": null,
    "lastMessageHtml": "",
    "lastMessageText": "",
    "lastReadSequenceNumber": 0,
    "lastReadTime": null,
    "lastVisibleActionCreated": "2024-03-29 07:13:25.517",
    "lastVisibleActionLastModified": "2024-03-29 07:13:25.517",
    "managerID": 0,
    "nonReimbursableTotal": 0,
    "notificationPreference": "hidden",
    "oldPolicyName": "",
    "ownerAccountID": 0,
    "parentReportActionID": "7247140607705689420",
    "parentReportID": "5750474469840668",
    "participantAccountIDs": [
        11457442
    ],
    "participants": {
        "11457442": {
            "hidden": true
        }
    },
    "policyAvatar": null,
    "policyID": "DD963943E5C51CBE",
    "policyName": null,
    "reportID": "1282394367591426",
    "reportName": "Chat Report",
    "stateNum": 0,
    "statusNum": 0,
    "submitterPayPalMeAddress": "",
    "total": 0,
    "type": "chat",
    "unheldTotal": 0,
    "visibility": null,
    "visibleChatMemberAccountIDs": [],
    "welcomeMessage": "",
    "writeCapability": "all"
}
```

</details>


<details>
<summary>Report data on scan complete</summary>

```
{
  "avatarUrl": null,
  "chatReportID": null,
  "chatType": "",
  "currency": "USD",
  "description": "",
  "fieldList": null,
  "hasOutstandingChildRequest": false,
  "hasParentAccess": false,
  "iouReportID": null,
  "isCancelledIOU": false,
  "isDeletedParentAction": null,
  "isOwnPolicyExpenseChat": false,
  "isPinned": false,
  "isWaitingOnBankAccount": false,
  "lastActorAccountID": "",
  "lastMentionedTime": null,
  "lastMessageHtml": "",
  "lastMessageText": "",
  "lastReadSequenceNumber": 0,
  "lastReadTime": "2024-03-29 07:13:33.914",
  "lastVisibleActionCreated": "2024-03-29 07:13:25.517",
  "lastVisibleActionLastModified": "2024-03-29 07:13:25.517",
  "managerID": 0,
  "nonReimbursableTotal": 0,
  "notificationPreference": "hidden",
  "oldPolicyName": "",
  "ownerAccountID": 0,
  "parentReportActionID": "7247140607705689420",
  "parentReportID": null,
  "participantAccountIDs": [
    11457442
  ],
  "participants": {
    "11457442": {
      "hidden": true
    }
  },
  "policyAvatar": null,
  "policyID": "DD963943E5C51CBE",
  "policyName": null,
  "reportID": "1282394367591426",
  "reportName": "Chat Report",
  "stateNum": 0,
  "statusNum": 0,
  "submitterPayPalMeAddress": "",
  "total": 0,
  "type": "chat",
  "unheldTotal": 0,
  "visibility": null,
  "visibleChatMemberAccountIDs": [],
  "welcomeMessage": "",
  "writeCapability": "all"
}
```

</details>

On scan complete the `parentReportID` is null, and it fails to get the parent report and check whether the report is transaction view or not.

---

>On report conversation page, request that finished SmartScanning has a whisper 'Only visible to you'.

![Screenshot 2024-03-29 at 13 59 14](https://github.com/Expensify/App/assets/25520267/ce38749c-765d-4848-8591-b79e650d28e5)

I also can reproduce this now, I think the root cause is I don't see we sent a pusher to update the action and empty the field `whisperedToAccountIDs`.

---

So my summary both of the issues are BE issues, and I agree to take this internally.

cc @anmurali

**Comment by anmurali** [comment] 2024-04-01 13:42
@trjExpensify - we need to get this assigned internally. Can you curate your magic and find us a volunteer to take it?

**Comment by trjExpensify** [comment] 2024-04-02 12:06
Yup, moving into `Hot Picks` section and calling it out today in the update. :)

**Comment by MonilBhavsar** [comment] 2024-04-03 04:56
I'll be working on this issue

**Comment by trjExpensify** [comment] 2024-04-03 09:10
Wahoo! Thanks, Monil!

**Comment by MonilBhavsar** [comment] 2024-04-04 10:41
I am unable to reproduce the issue mentioned in the op where blank page appears

Recordings: 
Requesting Money: 

https://github.com/Expensify/App/assets/32012005/ae5a48f2-88c2-4420-8e4e-37e7304c77e7


After smart scanned: 

https://github.com/Expensify/App/assets/32012005/4e25c6b0-6c9d-4ec3-a616-f4eab16be54d






The only issue I found in this flow is that whisper is not cleared as mentioned by @mollfpr 

> On report conversation page, request that finished SmartScanning has a whisper 'Only visible to you'.

I'll request a retest and see if applause is able to reproduce. Also, @mollfpr if you can retry too 🙏

**Comment by mollfpr** [comment] 2024-04-08 18:59
I can't reproduce the issue with the new account.

https://github.com/Expensify/App/assets/25520267/2455980b-d7d1-4395-8443-51a9c3bd13d5

**Comment by MonilBhavsar** [comment] 2024-04-09 14:33
Cool! Let's close this after fixing a whisper bug

**Comment by mvtglobally** [comment] 2024-04-12 05:27
Issue not reproducible during KI retests. (First week)

**Comment by MonilBhavsar** [comment] 2024-04-17 06:21
Auth and Web-E PR's are deployed, and QA is done.
So we can close this now. No payment required here

**Closed by MonilBhavsar** 2024-04-17 06:21 UTC
Labels: Reviewing, Daily, Internal, Bug, retest-weekly
