### ISSUE TITLE
[HOLD for payment 2024-06-11] [$250] Scan - Scan expense preview created with PDF file is shown larger than with images

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40751] opened 2024-04-23 07:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.64-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4503776
**Email or phone of affected tester (no customers):** [applausetester+vd_ios042224@applause.expensifail.com,](mailto:applausetester+vd_ios042224@applause.expensifail.com,)
[applausetester+vd_web042224@applause.expensifail.com](mailto:applausetester+vd_web042224@applause.expensifail.com)
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: the user must be an employee of a Workspace.

1. Go to Workspace chat.
2. Create 2 money request with the "Scan" option, select any 2 images.
3. Create a 3rd money request with the "Scan" option, but using a PDF file.
4. Verify that the report preview image of the PDF file is shown larger than those with image format.

## Expected Result:
The preview of the PDF file should be the same as the image formats.

## Actual Result:
The preview of the PDF file is larger than the image formats.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6458164_1713831667557!IMG_E4007](https://github.com/Expensify/App/assets/115492554/29227d73-4617-4bd4-be4a-c13e56e0a4eb)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017d201aaa419b0fee</li>
        <li>Upwork Job ID: 1782700594939478016</li>
        <li>Last Price Increase: 2024-05-14</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment] 2024-04-23 07:05
@strepanier03 I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-23 07:05
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-23 07:05
Production 

![IMG_3226](https://github.com/Expensify/App/assets/115492554/f3b49db3-7007-4c4c-bf60-389d81029dc0)

**Comment by mountiny** [comment] 2024-04-23 09:19
Making this external and removing a blocker, this is not blocking users from using the app

**Comment by jjcoffee** [comment] 2024-04-23 11:55
@ZhenjaHorbach Thanks, but it seems unlikely given that PR was deployed to production a month ago.

**Comment by madmax330** [comment] 2024-04-26 12:16
waiting on proposals

**Comment by strepanier03** [comment] 2024-04-30 05:03
Waiting for proposals at this time. I'll get it tied to a project now as well.

**Comment by strepanier03** [comment] 2024-05-02 20:42
Waiting for proposals. Accidentally applied a status to this, sorry about that.

**Comment by jjcoffee** [comment] 2024-05-03 11:25
Just a heads up I'll be OOO next week, 6th-13th (I may have some time on the 6th). Feel free to reassign based on urgency and/or if proposals start rolling in!

**Comment by dominictb** [comment] 2024-05-04 04:51
Proposal
Please re-state the problem that we are trying to solve in this issue.
The preview of the PDF file is larger than the image formats.

What is the root cause of that problem?
The preview is a flex-row container with 3 items, so each item container will have width = preview-container.width/3, and height = preview-container.height

![image](https://github.com/Expensify/App/assets/165644294/112b06fc-0597-4b9a-bf98-7c56766b9c9f)


By default, we are scale the image on the width only (and let the height be auto)

if (width > height) {
    setAspectRatio(1);
    return;
}

setAspectRatio(height ? width / height : 'auto');

return (
  <BaseImage
      // eslint-disable-next-line react/jsx-props-no-spreading
      {...forwardedProps}
      onLoad={handleLoad}
      style={[style, aspectRatio ? {aspectRatio, height: 'auto'} : {}, isObjectPositionTop && !aspectRatio && {opacity: 0}]}
      source={source}
  />
)
So the max height for all images of type width > height will be item-container.width, and of type height > width will be item-container.height. Therefore, if item-container.width is significantly smaller than item-container.height => there are some images appeared to be larger than the other

What changes do you think we should make in order to solve the problem?


We should add another behavior to the image component, allowing it to stretch by height as well

type ImageProps = ImageOnyxProps & ImageOwnProps & {
  stretchDimension?: 'vertical' | 'horizontal' = 'horizontal'
} // by default, stretch dimension will be horizontal
// the prop name and prop definition is subject to change
In the ReportActionItemImages component, we can pass down the props to make sure all image will have the stretchDimension: 'vertical' (stretched by height).

The result would be like this

![image](https://github.com/Expensify/App/assets/165644294/950dda37-88cb-44d4-8fec-d3437b2ee768)


What alternative solutions did you explore? (Optional)
Other possible solution is to scale down the height of the preview container based on screen size instead of fixing that at 110px, but I think the main solution of this proposal is more flexible

**Comment by dominictb** [comment] 2024-05-07 09:55
Are we gonna assign this issue? Thanks!

**Comment by strepanier03** [comment] 2024-05-08 23:17
@madmax330 - When you have some time can you please review the proposal approved by @jjcoffee [here](https://github.com/Expensify/App/issues/40751#issuecomment-2095925850)? Thanks so much!

**Comment by mvtglobally** [comment] 2024-05-13 14:13
Issue not reproducible during KI retests. (First week)

**Comment by jjcoffee** [comment] 2024-05-15 09:19
@dominictb Can you confirm if you're able to still reproduce the issue on latest main?

**Comment by jjcoffee** [comment] 2024-05-16 14:08
@dominictb Hmm I think cropping to a fixed might be the better option here, as if someone added an image that was say 10x10000, we'd get some crazy results :smile:

**Comment by madmax330** [comment] 2024-05-20 12:33
Not overdue

**Comment by mvtglobally** [comment] 2024-05-22 04:38
Issue not reproducible during KI retests. (Second week)

**Comment by strepanier03** [comment] 2024-06-11 21:42
@dominictb - can you link me your upwork profile so I can hire you to the job?

@jjcoffee - Feel free to do the checklist when you can and I'll move this forward then. 

Thanks all!

**Comment by jjcoffee** [comment] 2024-06-12 08:59
- The PR that introduced the bug has been identified. Link to the PR: N/A - I couldn't find any specific point where the behaviour was introduced
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create 2 money requests with the "Scan" option, using any image.
2. Create a 3rd money request with the "Scan" option, but using an A4 PDF file.
4. Verify that the report preview thumbnails are all of the same size, especially the preview of the PDF file.

Do we agree 👍 or 👎

**Comment by strepanier03** [comment] 2024-06-14 04:16
@dominictb - I've hired you to a job [here](https://www.upwork.com/nx/wm/offer/102730084), I'll check tomorrow to pay it out.

@jjcoffee - I've paid your contract in Upwork and closed it. 

Thank you both!

**Comment by strepanier03** [comment] 2024-06-19 02:18
Okay, job paid and contract closed. Closing this out thanks all!

**Closed by strepanier03** 2024-06-19 02:18 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
