### ISSUE TITLE
Profile - New avatar is not saved if changing right after profile name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21967] opened 2023-06-30 17:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Change profile name
3. Upload new avatar
4. Logout
5. Login

## Expected Result:
New avatar should be displayed

## Actual Result:
Previous avatar is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/79fe6b06-043c-444a-81a1-83dbf4183f79

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-06-30 22:14
Not reproduce in Production. Adding Deploy Blocker label

https://github.com/Expensify/App/assets/78819774/148d396f-401e-415f-bee0-f42b455c8675

**Comment by PauloGasparSv** [comment] 2023-06-30 23:01
[Taking this over](https://expensify.slack.com/archives/C03TQ48KC/p1688165392009279) from @aldo-expensify!

**Comment by PauloGasparSv** [comment] 2023-06-30 23:10
Can't replicate in staging using my `paulogaspar404@gmail.com` account

**Comment by PauloGasparSv** [comment] 2023-06-30 23:16
Checking [the logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22UpdateDisplayName%22%20AND%20email%3A%22applausetester%2B0409pronin%40applause.expensifail.com%22%20AND%20timestamp%3A%5B2023-06-30T00%3A00%20TO%202023-07-01T23%3A59%5D) from the Requests made for the GH Body evidence

**Comment by PauloGasparSv** [comment] 2023-06-30 23:24
I think this is happening because of Pusher and that's why I couldn't replicate in my first tests.

Some times the first request to `UpdateDisplayName ` drags on (examples [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227df5fa9939ee3150-SJC%22)+AND+timestamp:[2023-06-30T10:13:15.828Z+TO+2023-06-30T12:13:15.828Z]&index=logs_expensify-023057) and [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227dfa172a2bcd4ee3-LAX%22)+AND+timestamp:[2023-06-30T22:11:48.928Z+TO+2023-07-01T00:11:48.928Z]&index=logs_expensify-023070)) so I think the request for uploading the avatar is not even made since I can only see successful calls to `UpdateUserAvatar`

In logs I see there is a bunch of `Push_Service - Sending chunked event` attempts for the same event

**Comment by PauloGasparSv** [comment] 2023-06-30 23:38
Can't think of any other reason than the mentioned above, I asked for [help here](https://expensify.slack.com/archives/C03TQ48KC/p1688168247618149?thread_ts=1688165392.009279&cid=C03TQ48KC)!

**Comment by aldo-expensify** [comment] 2023-06-30 23:53
ah, good finding, maybe this is not a deploy blocker and it is just the server timing out because we send a ton of pusher events, something like this: https://github.com/Expensify/Expensify/issues/295672

Could that be the case?
Can we reproduce this in staging in an account that doesn't have a ton of contacts?

**Comment by PauloGasparSv** [comment] 2023-06-30 23:56
> Can we reproduce this in staging in an account that doesn't have a ton of contacts?

Will create a new test account and retry here

**Comment by PauloGasparSv** [comment] 2023-06-30 23:58
Worked fine in staging with a new account!

https://github.com/Expensify/App/assets/6564265/525a8fdf-d239-4c4c-97b9-69c7543935a2

(stopped filming bc I had to sign-in again and open my email, after signing in the profile pic was still there):
![image](https://github.com/Expensify/App/assets/6564265/4f7f62b0-f993-4733-ad28-ed0d2423e2d3)

**Comment by PauloGasparSv** [comment] 2023-06-30 23:59
Since I can't reproduce this reliably in new accounts and logs point to Pusher being the problem I'll remove the deploy blocker label from here.

Will re-test this on Monday

**Comment by PauloGasparSv** [comment] 2023-07-03 14:56
I just tested with my Expensify account in staging (which has a bunch of chats going on) and everything is working fine!

I compared the logs from [today's attempt](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%227e0ff0f74ffb51c0-GRU%22%20AND%20timestamp%3A%5B2023-07-03T00%3A00%20TO%202023-07-04T23%3A59%5D) with the [logs of the GH body evidence attempt](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227df5fa9939ee3150-SJC%22)+AND+timestamp:[2023-06-30T10:13:15.828Z+TO+2023-06-30T12:13:15.828Z]&index=logs_expensify-023057) and now there are waaaaaay less logs related to `Push_Service - Sending event` (today's log has `229` instances of that but Friday's logs have `7717`)

Since it looks like Pusher caused this I'm closing this issue, let's re-open if more people report this problem

**Closed by PauloGasparSv** 2023-07-03 14:56 UTC
Labels: Engineering, Daily, Overdue
