### ISSUE TITLE
[$500] Group - All recents users selected when clicking on "Add to group"

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35701] opened 2024-02-02 18:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.36-0
**Reproducible in staging?:** y
**Reproducible in production?:** yn
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on "+"
2. Go to the "Start chat"
3. Click on "Add to group" of recents users

## Expected Result:
Only one user should be selected when clicking on "Add to group"

## Actual Result:
All recents users selected when clicking on "Add to group"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e4e7ddbf-aeca-402b-9fcb-2ce6f9eb4d73

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016be032c785f4143f</li>
        <li>Upwork Job ID: 1754458637091528704</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-02 18:55
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by shubham1206agra** [comment] 2024-02-02 19:09
Offending PR: https://github.com/Expensify/App/pull/34847
cc @Krishna2323

**Comment by marcaaron** [comment] 2024-02-03 01:00
I believe it is caused by [this very large PR](https://github.com/Expensify/App/pull/33280)

Debugging locally and there seems to be some issue with [this commit](https://github.com/Expensify/App/commit/f5a0d7b04aa56d3ac7541f277258016e03d7c4d9)

**Comment by s77rt** [comment] 2024-02-03 01:41
The option selector `isSelected` logic compares multiple fields and some of these fields are not unique depending on the supplied list, e.g.:
- List of policies, we should compare policy id
- List of reports, we should compare report id
- List of accounts, we should compare account id

The problem is that the option selector does not know the type of list so even if we are supplying a list of account it still compares the policy id field (which is not unique among accounts).

I think the best to do here is to compare `keyForList` as it's the only field that's guaranteed to be unique.

**Comment by rojiphil** [comment] 2024-02-03 16:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In `Add to group` scenario, when a user is selected into a group, all the recent users also get selected. This is the problem we are solving here.

### What is the root cause of that problem?

Offending PR is #33280 and offending code is [here](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/OptionsList/BaseOptionsList.tsx#L186)

[Here](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/OptionsList/BaseOptionsList.tsx#L186), we check if the `policy` matches for `option` and `item`. However, since the policy ID report may contain a fake value `_FAKE_`, this would return `isSelected` true thereby causing the recent list items to be selected. This is the root cause of the problem here.

### What changes do you think we should make in order to solve the problem?

To fix this, we should also additionally check if it contains a `_FAKE_` value [here](https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/components/OptionsList/BaseOptionsList.tsx#L186) like this:

            if (option.policyID && option.policyID !== CONST.POLICY.ID_FAKE && option.policyID === item.policyID) {

### What alternative solutions did you explore? (Optional)

**Comment by hayata-suenaga** [comment] 2024-02-04 05:23
@s77rt I feel like your solution works the best. Since you review the PR, could you raise a PR to fix this please?

**Comment by s77rt** [comment] 2024-02-04 11:20
@hayata-suenaga https://github.com/Expensify/App/pull/35770

**Comment by s77rt** [comment] 2024-02-05 14:04
This can be closed. No payment is due here since it's part of the ideal nav.

**Comment by luacmartins** [comment] 2024-02-05 14:54
Closing as per the comment above

**Closed by luacmartins** 2024-02-05 14:54 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Daily, Bug

**Comment by MitchExpensify** [comment] 2024-02-08 23:55
*Payment summary:*

$500 - @s77rt (NewDot)

**Comment by s77rt** [comment] 2024-02-09 01:30
@MitchExpensify No payment is required here.

**Comment by hayata-suenaga** [comment] 2024-02-09 16:27
yep this is an issue for a regression stemmed from the Ideal Nav PR

sorry about that I should have specified that
