### ISSUE TITLE
Distance - Inconsistency between "Request money" and "Distance" page maps

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26937] opened 2023-09-07 09:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the "+" icon
2. Select "Request money" and choose "distance"
3. Select the starting and finishing points and check the map
4. Proceed by clicking the "Next" button
5. Now check the map on the "Distance" page

## Expected Result:
The map on both the "Request money" and "Distance" pages should display the same, ensuring there is no inconsistency between them

## Actual Result:
An inconsistency is observed between the maps on the "Request money" and "Distance" pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.65-3

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-09-03 at 4 24 45 AM](https://github.com/Expensify/App/assets/115492554/43b21e18-e210-4ed4-9018-8d910cae3d0c)

![Screenshot 2023-09-03 at 4 25 02 AM](https://github.com/Expensify/App/assets/115492554/6e77a62e-3e93-4453-9cc0-6147e17fa1b2)

https://github.com/Expensify/App/assets/115492554/6275af39-225a-443f-a1f1-911314d81f58

![Screenshot 2023-09-07 121547](https://github.com/Expensify/App/assets/115492554/9b3cf617-a9e2-4f2e-a39e-d0d975e019e7)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:**  v1.3.65-3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment] 2023-09-08 16:06
It seems like when you have two requests in the same chats, the view sums them up in a single bill.

**Comment by mallenexpensify** [comment] 2023-09-14 07:43
Sorry for the delay, was off last week and playing catchup this week. 
 @ayazhussain79 I'm unable to reproduce, anything you can think of I might be doing wrong?
<img width="391" alt="image" src="https://github.com/Expensify/App/assets/22508304/9dbe565d-1866-4290-b640-5339f97c465f">

<img width="370" alt="image" src="https://github.com/Expensify/App/assets/22508304/5aa74904-7df7-466a-baa8-ba6aaaf31876">

**Comment by ayazhussain79** [comment] 2023-09-14 14:04
@mallenexpensify select long distance 



<img width="978" alt="Screenshot 2023-09-14 at 7 00 11 PM" src="https://github.com/Expensify/App/assets/56740856/631b6518-ffcf-4a7f-95d9-692e9273a058">

**Comment by mallenexpensify** [comment] 2023-09-19 03:47
Thanks @ayazhussain79 

Tested again, it appears to happen starting at a distance between 420 miles and 491 miles. 
I'm going to assume that 99.9% of mile expenses are less than 420 miles  ( 675km) so I don't think it's _worth_ fixing the bug where 100% of the map doesn't show for long-distance maps.  

Before closing I'll hang tight for a few days to see if anyone has feedback.

**Closed** 2023-09-26 07:03 UTC
Labels: Daily, Overdue, Bug

**Comment by mallenexpensify** [comment] 2023-09-26 07:04
Recent changes have been made and this isn't a bug anymore
