### ISSUE TITLE
Search - Remove search label 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#4677] opened 2021-08-16 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to NewDot
2. Click on the search icon
3. Type anything in the search box

## Expected Result:
When there are no results there should be a message informing the user there are no results found or to search via email format. 

## Actual Result:
There's a unnecessary label below the text input that shows the same text as the user typed in the search input. 
 
## Workaround:
N/A visual issue. 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.0.85-0

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://user-images.githubusercontent.com/44479856/129605586-3362ccdc-78a9-4ab7-9166-4d0946a5aafa.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

___ 
From @Julesssss https://expensify.slack.com/archives/C01GTK53T8Q/p1629112548387500
> This label is redundant, it is only shown when no results are found — and simply duplicates the search query that is shown in the input above…

**Comment by Santhosh-Sellavel** [comment] 2021-08-16 17:52
Return search value is the problem here
<img width="893" alt="Screenshot 2021-08-16 at 11 21 00 PM" src="https://user-images.githubusercontent.com/85645967/129607529-961c882e-5b55-496d-9f4c-6f898c4da2d9.png">

**Comment by aman-atg** [comment] 2021-08-16 17:58
Dupe of https://github.com/Expensify/App/issues/4163

**Comment by Beamanator** [comment] 2021-08-17 08:32
As @aman-atg mentioned this was originally reported in #4163 so I think we can close this one and continue investigating there

**Comment by Julesssss** [comment] 2021-08-17 10:04
Sounds good @Beamanator

**Closed by Julesssss** 2021-08-17 10:04 UTC
Labels: Engineering, Weekly, Improvement
