### ISSUE TITLE
[$1000] Room member not displayed immediately when a user joins the room, requires refreshing the room member page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21931] opened 2023-06-30 03:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the “New room” section
2. Enter room name and select userA workspace
3. Select visibility to “Public” and click on “Create room”
4. Go to the room Details
5. Share code > Copy URL to clipboard
6. Leave the room settings page open (can be any part of it, like share code, or room members, etc.)
7. Open other browser and login with userB account
8. Join the room by pasting URL
10. Now go back to the userA and navigate to room member page (if not already there). 

## Expected Result:
When a user joins a room, all room members should be shown without the need to manually refresh the room member page
## Actual Result:
All room members are not shown immediately when a user joins the room. The room member page needs to be manually refreshed to all room members (if the room settings page was open at the time the new user joined the room). 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/1f37b6c3-deb3-45b3-b5cd-1468161b177c

https://github.com/Expensify/App/assets/43996225/f16b65a9-2da9-415f-ba66-32f6502a5cff

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687811735971269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147f130dbed56e1ba</li>
        <li>Upwork Job ID: 1676668389329010688</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-30 20:59
I can't reproduce this on my end. 

https://github.com/Expensify/App/assets/54866469/ca5d0192-324f-4931-924d-427fcb901ae2

**Comment by joekaufmanexpensify** [comment] 2023-06-30 21:01
Discussing [here. ](https://expensify.slack.com/archives/C049HHMV9SM/p1688158879354409?thread_ts=1687811735.971269&cid=C049HHMV9SM)

**Comment by ayazhussain79** [comment] 2023-06-30 21:28
@joekaufmanexpensify Now member displayed without refreshing page but userA who created room removed from the member page
steps:

1. Create a new workspace
2. Then go to the “New room” section
3. Enter room name and select userA workspace
4. Select visibility to “Public” and click on “Create room”
5. Go to the room Details
6. Share code > Copy URL to clipboard
7. Go to the Details > Members
8. Open other browser and login with userB account
9. Join the room by pasting URL
10. Now go back to the userA room member page



https://github.com/Expensify/App/assets/56740856/b69419ca-eac6-41a4-a5d7-a66a21fa32c3

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:06
Not overdue.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 19:04
Okay, I can reproduce now, and updated OP. This bug is reproducible when the room settings (any part of like, like share code, room members, etc.) is left open in userA, when userB joins. If the room settings is not open in userA's account when userB joins, the bug does not occur. This is fairly niche, but we should still fix it. 


https://github.com/Expensify/App/assets/54866469/4f30a41f-1779-44c9-8cfd-1272ad9e0b92

**Comment by joekaufmanexpensify** [comment] 2023-07-06 17:52
Ah cool. I agree this does look like a dupe, and am thinking we should close. Does that sound good @mananjadhav ?

**Comment by joekaufmanexpensify** [comment] 2023-07-06 18:03
Cool cool. Closing as a dupe of the above issue!

**Closed by joekaufmanexpensify** 2023-07-06 18:03 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by ayazhussain79** [comment] 2023-07-24 09:25
@joekaufmanexpensify @mananjadhav  this https://github.com/Expensify/App/issues/21931#issuecomment-1615210962 bug still reproducible even this bug is closed https://github.com/Expensify/App/issues/20761

**Comment by joekaufmanexpensify** [comment] 2023-07-24 16:50
Thanks for raising! I commented about this in[ the slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1690217381478419?thread_ts=1687811735.971269&cid=C049HHMV9SM), but I think the correct course of action is still to leave this as closed, as we recently decided not to treat these "dynamically updated" issues as bugs.
