### ISSUE TITLE
Task – Unable to edit description with a long link in existing task, error appears

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46447] opened 2024-07-29 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4783737
**Email or phone of affected tester (no customers):** applausetester+jpcategory_2@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open chat with user B
4. Create a task assigned to another user with such description: https://staging.new.expensify.com/r/5730461601013640https://staging.new.expensify.com/r/5730461601013640
5. Open task detail
6. Click on description and edit it with a 2-3 characters

## Expected Result:
Able to edit description

## Actual Result:
Character limit exceeded (632/500) error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/10a64ca1-e506-4c2f-b748-47b28b2d3276

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @carlosmiceli</details>

**Comment by chiragsalian** [comment] 2024-07-29 21:36
Doesn't look web-e related. Removing deployblocker label.

**Comment by bondydaa** [comment] 2024-07-29 22:03
so this looks like we did it on purpose https://github.com/Expensify/App/pull/43084

cc @carlosmiceli @abdulrahuman5196

**Comment by bondydaa** [comment] 2024-07-30 14:43
I'm removing the blocker here, i think it was an intended behavior change from https://github.com/Expensify/App/issues/42660.

**Comment by carlosmiceli** [comment] 2024-08-01 23:39
@bondydaa to confirm, since we just implemented [this](https://github.com/Expensify/App/issues/42660) behavior, we can assign this to `External` to fix the error message, right?

**Comment by bondydaa** [comment] 2024-08-02 14:24
seems fine if that's whats needed but what is wrong with the error message?

**Comment by carlosmiceli** [comment] 2024-08-02 22:38
No, my bad, got this one mixed up with the issue where there was an unintended error message shown to the user.

**Closed by carlosmiceli** 2024-08-02 22:38 UTC
Labels: Engineering, Weekly
