### ISSUE TITLE
[HOLD E/E#296903] [Secure Logins] Hidden pronouns becomes visible on updating preferred pronoun

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#21550] opened 2023-06-26 08:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account A & account B shouldn't have an existing chat
1. From a tab where account A is signed in send a message to account B
2. Click on the chat header > verify that account B's pronoun is not displayed
3. Switch to a tab where account B is signed in & update your preferred pronouns
4. Switch to the tab where account A is signed in> open message > click on the chat header

## Expected Result:
User B's pronouns shouldn't be revealed to user A till user B replied to the message

## Actual Result:
User B's pronouns is revealed before user b replied to user A

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.31-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Notes/Photos/Videos:** (See slack post)
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687542046707599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01788124088e003ced</li>
        <li>Upwork Job ID: 1673244992513429504</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2023-06-26 08:22
@tjferriss @parasharrajat I already marked this `Internal` b/c this is a problem in our backend - I believe this is happening because we don't check who is known / not known in Auth [here](https://github.com/Expensify/Auth/blob/57bfc0c712587e31360cccce9ccc4eae212a530f/auth/lib/Account.cpp#L2246-L2265) - this is where we collect the accountIDs a user's pronoun-update should be sent to

**Comment by Beamanator** [comment] 2023-06-26 08:23
So @parasharrajat i'm going to unassign you since this doesn't require a front-end fix

**Comment by tjferriss** [comment] 2023-06-28 05:00
@Beamanator should this stay as daily?

**Comment by Beamanator** [comment] 2023-06-28 09:26
@tjferriss good call, @puneetlath and I believe it isn't super critical so dropping to weekly 👍

**Comment by Beamanator** [comment] 2023-07-04 08:12
Putting on hold for https://github.com/Expensify/Expensify/issues/296903 since we're planning to handle this there

**Comment by tjferriss** [comment] 2023-07-12 20:49
Still on hold, MelvinBot.

**Comment by tjferriss** [comment] 2023-07-19 05:53
Looks like we're still on hold

**Comment by tjferriss** [comment] 2023-07-25 23:29
Still on hold, Melvin.

**Comment by tjferriss** [comment] 2023-08-02 04:01
Still on hold, Melvin.

**Comment by tjferriss** [comment] 2023-08-09 05:07
Still on hold, Melvin.

**Comment by tjferriss** [comment] 2023-08-15 19:50
Looks like we're still on hold with this https://github.com/Expensify/Expensify/issues/296903

**Comment by tjferriss** [comment] 2023-08-28 22:12
Still on hold https://github.com/Expensify/Expensify/issues/296903

**Comment by tjferriss** [comment] 2023-09-11 23:02
Still on hold for https://github.com/Expensify/Expensify/issues/296903. I'm going to move this to Monthly given the urgency of the related issue.

**Comment by Beamanator** [comment] 2023-10-18 15:50
still technically on hold

**Comment by tjferriss** [comment] 2023-10-30 04:32
I'm going to close this. The issue is still reproducible, but I no longer view this as a bug.

**Closed by tjferriss** 2023-10-30 04:32 UTC
Labels: Monthly, Internal, Bug
