### ISSUE TITLE
[HOLD for payment 2023-01-03] Requires two arrow presses to navigate emoji’s via keyboard

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13417] opened 2022-12-07 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed:

1. open emoji selector
2. search (first result is auto selected)
3. press right arrow key once (input box seems to unselect but selected emoji doesn’t change)
4. press right arrow key again (selected emoji moves right)

## Expected result:
Selected emoji would move on first right arrow press.

## Actual Result:
Requires 2 presses to navigate to next one

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/206308153-9f2896d8-b52d-4cf2-b242-af866cb45370.mov

https://user-images.githubusercontent.com/43996225/206308194-22ce9241-4798-4ca0-86fd-27b7f34aaf16.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670424688719619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a426d984f01623e</li>
        <li>Upwork Job ID: 1612894342292516864</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-07 23:13
**Proposal**

We can set `highlightedIndex : -1` so that onSearch first emoji doesn't get highlighted automatically.

```diff 
diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.js b/src/components/EmojiPicker/EmojiPickerMenu/index.js
index 2d97a2443..38e699a4b 100755
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.js
@@ -386,7 +386,7 @@ class EmojiPickerMenu extends Component {
         ));
 
         // Remove sticky header indices. There are no headers while searching and we don't want to make emojis sticky
-        this.setState({filteredEmojis: newFilteredEmojiList, headerIndices: [], highlightedIndex: 0});
+        this.setState({filteredEmojis: newFilteredEmojiList, headerIndices: [], highlightedIndex: -1});
         this.setFirstNonHeaderIndex(newFilteredEmojiList);
     }
```

**Comment by stitesExpensify** [comment] 2022-12-07 23:47
Hi @syedsaroshfarrukhdot thank you for your proposal, however this issue has not been marked as `external` because I intend to fix it myself. To avoid spending time in the future on issues that are not being opened for contributors to work on, I would recommend not researching issues that don't have the `external` and `help wanted` labels.

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-09 00:56
>  To avoid spending time in the future on issues that are not being opened for contributors to work on, I would recommend not researching issues that don't have the `external` and `help wanted` labels.

I understand that and I also used to wait before till `external` label used to apply before starting to work on solution. Recently, Many issues get `proposal` before `external` label is applied and get even hired for that proposal external label is then applied only to hire them on the job. So, I thought it is the way to move forward to be the first one to propose correct solution on the issues. 😅

**Comment by stitesExpensify** [comment] 2022-12-09 15:52
I apologize for any confusion we may have caused you in the past regarding the "correct" process for getting chosen on an issue. We have been having some internal discussion to make the rules more clear, consistent, and fair for contributors, and will soon start [locking issues](https://github.com/Expensify/App/issues/13395) until the external label is applied. 

Thank you for your eagerness to help out, it is much appreciated!

**Comment by stitesExpensify** [comment] 2022-12-14 17:52
Okay so here's where we landed:
- We don't want to set the index to -1 because then when you hit enter the emoji you typed in won't get added to the composer
- The problem isn't that it takes 2 presses, but that your first press _feels_ like it didn't do anything. 
- The first press gets rid of focus and now lets you move your highlight around, and the second press actually moves it.

To show this to the user, we will show the highlight currently in the code on no presses press, and then show a different highlight on the first press to show that now you can move the emoji around

**Comment by stitesExpensify** [comment] 2022-12-16 22:57
Newest version 

https://user-images.githubusercontent.com/42391420/208202111-e4552ea9-c59a-4d32-abf6-45b3dc07fea2.mp4

**Comment by miljakljajic** [comment] 2023-01-09 14:21
Sorry for the hold up whilst I was OOO. I will make this payment and review the regression test steps today.

**Comment by miljakljajic** [comment] 2023-01-09 14:33
Ah - I thought this was reported by a contributor, but I was wrong. No payment required. [There is an existing regression test for this.](https://expensify.testrail.io/index.php?/tests/view/3053160)

**Comment by mallenexpensify** [comment] 2023-01-11 00:44
@aimane-chnaif paid!  thanks.
@miljakljajic I checked off the BZ box and added the link to testrail, closing!

**Closed by mallenexpensify** 2023-01-11 00:44 UTC
Labels: Reviewing, Daily, Internal, Awaiting Payment, Bug
