### ISSUE TITLE
[HOLD for payment 2024-01-17] [$250] Action menu - Double-clicking the "Add Reaction" icon highlights the text of the message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33547] opened 2023-12-23 13:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Interna Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Log in with any account
3. Navigate to any conversation with the correspondence history
4. Move the cursor over any text message
5. Double-click on the "Add Reaction" icon in the action menu

## Expected Result:
Double-clicking the "Add Reaction" icon in the action menu should not cause the text in the message to be highlighted.

## Actual Result:
Double-clicking the "Add reaction" icon in the Action menu highlights the text in the message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/f19042b9-b984-412b-b188-00f56394bfaa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6ecd7244e8df2c0</li>
        <li>Upwork Job ID: 1738559790251122688</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 28081103</li>
<li>bernhardoj | Contributor | 28081105</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by aldo-expensify** [comment] 2024-01-02 16:56
Tried to reproduce in the public room https://staging.new.expensify.com/r/5593084223054221 in staging, but couldn't . Can anyone help confirm that this is still reproducible?

**Comment by aldo-expensify** [comment] 2024-01-02 16:58
I see that the context menu for me closes when I click the second time, meanwhile in the video shown in this GH issue body this doesn't happen. I guess this difference made the problem go away 🤷

**Comment by aldo-expensify** [comment] 2024-01-02 23:06
> @aldo-expensify this issue could be reproduced easier when double-clicking the "Copy to clipboard" icon.

Thanks, now I reproduced

**Comment by aldo-expensify** [comment] 2024-01-02 23:44
Hmm... I think we should do @bernhardoj 's change because a button makes more sense than a div there (semantically) and it also produces the effect we want.

Regarding @dukenv0307 proposal of adding `styles.userSelectNone` to the whole context menu, I also think it makes sense to do that and I don't think we will ever put selectable text there considering the little space available. If we don't do this, we may later get a bug report about it and waste a bunch of time again on it.

what about doing both and sharing the reward?

**Comment by mvtglobally** [comment] 2024-01-03 05:52
Issue not reproducible during KI retests. (First week)

**Comment by bernhardoj** [comment] 2024-01-03 06:10
Ok for me, but I can't reproduce by double-clicking the copy to clipboard.

> I see that the context menu for me closes when I click the second time,

This is a regression from https://github.com/Expensify/App/pull/32551 and they already put a new [PR](https://github.com/Expensify/App/pull/33835) to fix it, so I guess we can wait for that so I can test it.

**Comment by Christinadobrzyn** [comment] 2024-01-03 19:57
Maybe this is still happening? It looks like this might be happening with the last message sent?

https://github.com/Expensify/App/assets/51066321/a0e1cec6-235b-43ff-9542-cf4d4c1c4d37

**Comment by Christinadobrzyn** [comment] 2024-01-03 21:53
Ah okay, well maybe that's a different issue - we can just see what the KI test continue to show

**Comment by aldo-expensify** [comment] 2024-01-04 15:06
I also can reproduce, I just have to first double click in the context menu first (outside of an icon), and then I can reproduce with the copy to clipboard. I used to be able to reproduce with the quick emoji icons, but not anymore seems like.

> @aldo-expensify @hoangzinh should we move forward with this?

Yes, I think we should. Who wants to put up the PR?

**Comment by aldo-expensify** [comment] 2024-01-04 15:13
@Christinadobrzyn I think we may need to correct the amount in those Upwork jobs to split half/half.

**Comment by aldo-expensify** [comment] 2024-01-04 15:14
Hmm, maybe that did it.

**Comment by bernhardoj** [comment] 2024-01-04 16:22
I can do it.

**Comment by aldo-expensify** [comment] 2024-01-04 16:24
> I can do it.

ok!

**Comment by bernhardoj** [comment] 2024-01-04 16:31
PR is ready

cc: @hoangzinh

**Comment by aldo-expensify** [comment] 2024-01-22 13:20
Bump @hoangzinh  on completing the [list](https://github.com/Expensify/App/issues/33547#issuecomment-1884239235)

**Comment by Christinadobrzyn** [comment] 2024-01-22 17:21
Hi can you confirm this is correct for payouts due?

Issue Reporter: NA
Contributor: $250 @bernhardoj & $250 @dukenv0307 
Contributor+: $500 @hoangzinh 

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~01a6ecd7244e8df2c0).

Also, if everyone is getting paid through Upwork, @hoangzinh can you accept our offer so I can pay you through Upwork?

**Comment by aldo-expensify** [comment] 2024-01-22 17:24
That looks good to me

**Comment by Christinadobrzyn** [comment] 2024-01-22 19:25
Thanks @aldo-expensify! Paid @bernhardoj and @dukenv0307 - waiting on @hoangzinh to accept the Upwork offer

**Comment by Christinadobrzyn** [comment] 2024-01-23 16:24
Thanks @hoangzinh! I paid you in Upwork based on this payment [summary](https://github.com/Expensify/App/issues/33547#issuecomment-1904463889). So this is all done. Closing.

**Closed by Christinadobrzyn** 2024-01-23 16:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
