### ISSUE TITLE
[HOLD for payment 2023-11-09] [$500] Settings - Long email address appears differently on the Android & mWeb

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30023] opened 2023-10-19 20:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Pre-condition: Use Long email address account
1. Launch app
2. Tap profile icon
3. Note the way display name is truncated
4. Go to https://staging.new.expensify.com/
5. Tap profile icon
6. Note the way display name is truncated

## Expected Result:
An account with a long email address must appear in similar way in both Android & mWeb settings page

## Actual Result:
An account with a long email address appears differently on the Android & mWeb settings page. The email address is truncated differently in mweb and Android

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Bug6243491_1697744147669!Screenshot_2023-10-19-18-56-24-885_com expensify chat-edit](https://github.com/Expensify/App/assets/78819774/2d835d30-6427-4d4e-8f5d-ab204bd6a580)

![Bug6243491_1697744147656!Screenshot_2023-10-19-18-56-56-838_com android chrome-edit](https://github.com/Expensify/App/assets/78819774/b417a27b-2d10-4c03-826a-77914906e8d1)

https://github.com/Expensify/App/assets/78819774/5a465001-678a-4643-8e50-25e16a0f2864

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af2e4c9502542f72</li>
        <li>Upwork Job ID: 1715099845001293824</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27326758</li>
<li>akinwale | Contributor | 27326759</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-10-19 20:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Long email address does not fill up the available width on the profile page on Android native as opposed to mWeb.

### What is the root cause of that problem?
The Text component does not automatically fill up the available width of the container.

### What changes do you think we should make in order to solve the problem?
Add `styles.w100` to the Text component in ProfilePage.

### What alternative solutions did you explore? (Optional)
None.

**Comment by jjcoffee** [comment] 2023-10-20 08:43
@akinwale Thanks for the proposal! LGTM but wondering if you have any insight as to why the behaviour is different on mWeb vs native?

**Comment by akinwale** [comment] 2023-10-20 09:15
> @akinwale Thanks for the proposal! LGTM but wondering if you have any insight as to why the behaviour is different on mWeb vs native?

I'm not quite sure why it's happening on Android. There seems to be some sort of aggressive wrapping going on after the + sign in the text on native Android in order to display the ellipsis at the end.

On Web, a `div` is used to display the text, which defaults to block display, resulting in the `div` taking up the full width of its container.

**Comment by situchan** [comment] 2023-10-20 09:19
Same root cause - #24339

**Comment by jjcoffee** [comment] 2023-10-20 09:27
@situchan Hmm I don't think the issues are really linked though, since the fix here is much more straightforward since we don't have to worry about causing any [regressions](https://github.com/Expensify/App/issues/21215) from setting the header to 100% width.

**Comment by situchan** [comment] 2023-10-20 09:29
@jjcoffee you were asking about inconsistency so I explained why it's truncated in android native only.

**Comment by situchan** [comment] 2023-10-20 09:33
So it's related to `ellipsizeMode` property in android

**Comment by jjcoffee** [comment] 2023-10-20 09:40
@situchan Ah okay gotcha, thanks! I couldn't find the root cause in the issue you linked since that thread is so long :sweat_smile:  I think setting the width to 100% works fine for us here.

**Comment by conorpendergrast** [comment] 2023-10-23 09:13
Waiting for @grgia to review (this was assigned on her Friday morning!)

**Comment by grgia** [comment] 2023-10-23 10:43
@akinwale thank you for your proposal, assigning!

**Comment by akinwale** [comment] 2023-10-23 12:44
@jjcoffee My [PR](https://github.com/Expensify/App/pull/30173) is ready for review. Thanks.

**Comment by jjcoffee** [comment] 2023-11-02 10:28
- The PR that introduced the bug has been identified. Link to the PR: **N/A - looks like this style was always missing**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. Sign in to an account with a very long email address (e.g. applausetester+areallylongemailsuffix@gmail.com).
2. Tap the profile icon and verify that the display name is not truncated half-way on Android native.
3. Open the profile page of any account with the same email address format as in step 1.
4. Verify that the display name is not truncated half-way on Android native.
Do we agree 👍 or 👎

**Comment by conorpendergrast** [comment] 2023-11-09 14:20
QA test created: https://github.com/Expensify/Expensify/issues/334908

**Comment by conorpendergrast** [comment] 2023-11-09 14:24
Payouts due:

Issue Reporter: N/A - Applause

- [x] Contributor: $500 @akinwale - [Contract paid and ended](https://www.upwork.com/nx/wm/workroom/35221814/overview)
- [ ] Contributor+: $500 @jjcoffee - [Contract paid and ended](https://www.upwork.com/nx/wm/workroom/35221527/overview) 

Eligible for 50% #urgency bonus? No (PR created before [the announcement](https://expensify.slack.com/archives/C01GTK53T8Q/p1698191269281379), but not merged within the urgency period)

Upwork job is [here](https://www.upwork.com/jobs/~01af2e4c9502542f72).

**Comment by conorpendergrast** [comment] 2023-11-09 14:25
All done, thanks everyone

**Closed by conorpendergrast** 2023-11-09 14:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
