### ISSUE TITLE
[WAITING ON SOBIT TO COMPLETE CHECKLIST] [$500] Changing Currency in IOU Causes Account Email to Replace Request Email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26392] opened 2023-08-31 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money".
2. Enter the desired amount and email address for the money request.
3. Double-click on the requested money in IOU and change the currency by clicking on the amount.
4. Go back twice and observe that the requested email has been replaced by the account email.
## Expected Result: 
Changing the currency in IOU should not cause the account email to replace the requested email.
## Actual Result: 
Changing the currency in IOU causes the account email to replace the requested email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/565bb036-322a-439b-b116-53fe78e13195

https://github.com/Expensify/App/assets/43996225/169e6a2e-9968-4d90-b6ec-90271a0b17b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @TewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692596411940539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ab47794feaee80</li>
        <li>Upwork Job ID: 1699385618357227520</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>TewodrosGirmaA | Reporter | 26851433</li>
</ul></li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-09-06 11:34
Added the external label

**Comment by flaviadefaria** [comment] 2023-09-11 13:09
Seems like we're still waiting for proposals.

**Comment by Tony-MK** [comment] 2023-09-11 17:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Changing Currency in IOU Causes Account Email to Replace Request Email

### What is the root cause of that problem?

The `ReportActionItemSingle` component displays the primary and secondary user details in the `ReportActionItemFragment` component. The primary user's account ID is fetched from the `report.action.actorAccountID` and it is the `displayName` varibale below.

https://github.com/Expensify/App/blob/f5b7d5c0cef7ac0dc53af69a04cda4e3b9049014/src/pages/home/report/ReportActionItemSingle.js#L90-L92

The root cause of the problem is that when a user changes the currency, the `actorAccountID` is modified to the user who is changing it. This modification happens in the `ReportUtils.js` file.

https://github.com/Expensify/App/blob/f5b7d5c0cef7ac0dc53af69a04cda4e3b9049014/src/libs/ReportUtils.js#L2237


### What changes do you think we should make in order to solve the problem?


Instead of using the `actorAccountID` from `props.action.actorAccountID`, we should using it from in `props.iouReport.managerID` because the `managerID`'s value doesn't change when the currency has been changed and is the same value as the first `actorAccountID`

From this :

https://github.com/Expensify/App/blob/f5b7d5c0cef7ac0dc53af69a04cda4e3b9049014/src/pages/home/report/ReportActionItemSingle.js#L91

To something like this:

`const actorAccountID = props.iouReport.managerID;`

**Comment by sobitneupane** [comment] 2023-09-14 10:09
Thanks for the proposal @Tony-MK 

I don't think we can do the change that you are suggesting. `ReportActionItemSingle` is used in every chat whether it has iouReport or not. And we cannot be sure that iouReport is always present.

**Comment by Tony-MK** [comment] 2023-09-15 04:31
Thanks for reviewing my proposal @sobitneupane . 

Kindly have a look at my updated [proposal](https://github.com/Expensify/App/issues/26392#issuecomment-1714331524), as I considered your concerns in comment https://github.com/Expensify/App/issues/26392#issuecomment-1719161970

**Comment by flaviadefaria** [comment] 2023-09-15 10:46
@jliexpensify  I'm going OoO for a week so assigning this to you so that you can move it forward in the meantime. I'll take it back from you once I'm online again. Thanks!

**Comment by jliexpensify** [comment] 2023-09-19 00:00
Bump @sobitneupane [for this comment](https://github.com/Expensify/App/issues/26392#issuecomment-1720593406)

**Comment by jliexpensify** [comment] 2023-09-20 23:24
Bumping @sobitneupane again to address [this](https://github.com/Expensify/App/issues/26392#issuecomment-1720593406)

**Comment by sobitneupane** [comment] 2023-09-21 06:48
Thanks for the update @Tony-MK 

[Proposal](https://github.com/Expensify/App/issues/26392#issuecomment-1714331524) from @Tony-MK looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by jliexpensify** [comment] 2023-09-22 00:41
Not overdue, @deetergp should be online to approve this soon!

**Comment by deetergp** [comment] 2023-09-25 07:14
I agree with @sobitneupane, @Tony-MK's is straight forward and should take care of the problem. Assigning it now…

**Comment by Tony-MK** [comment] 2023-09-25 16:03
I have to solve some issues with testing on IOS and MacOS but the PR should be ready for review within 48 hours.

**Comment by Tony-MK** [comment] 2023-09-27 20:21
@sobitneupane, Sorry the delay but the PR #28350 is ready for review. Thanks

**Comment by flaviadefaria** [comment] 2023-10-04 07:03
Oh sorry @jliexpensify I missed this one as I only re-assign daily issues when going OoO and this was switched to weekly. Up to you, if I can get to it today I'll make the payment, if not and you have some time to sort it out that works too. Thanks!

**Comment by jliexpensify** [comment] 2023-10-04 07:05
All good - payment isn't due for a while yet! Up to you, if you've got a lot on atm, feel free to leave this with me.

**Comment by sobitneupane** [comment] 2023-10-05 14:21
Yes, I was unavailable for a few days, and I had notified about it on [Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1695878025111499).

**Comment by jliexpensify** [comment] 2023-10-16 06:40
Whoops apologies - I was out sick at the end of last week. Bump @sobitneupane to complete the checklist so I can sort out payment.

**Comment by jliexpensify** [comment] 2023-10-16 06:42
Payment Summary:

- Bug Reporter: @tewodrosGirmaA $50
- Contributor: @Tony-MK $500 + $250 [based off this comment](https://github.com/Expensify/App/issues/26392#issuecomment-1745418810)
- C+: @sobitneupane $500 + $250 (New.Dot payment)

[Upwork job](https://www.upwork.com/jobs/~0164ab47794feaee80)

**Comment by jliexpensify** [comment] 2023-10-17 00:18
Bumping @sobitneupane to complete the checklist please!

**Comment by Tony-MK** [comment] 2023-10-17 05:30
@jliexpensify, Sobit stated last week that he will be OOO until next week in this [comment](https://github.com/Expensify/App/issues/28334#issuecomment-1761967117)

**Comment by jliexpensify** [comment] 2023-10-17 05:41
Oh ok, apologies - was not aware. I'll pay out now and Dobit can sort out the list when he's back!

**Comment by jliexpensify** [comment] 2023-10-17 05:42
@Tony-MK I think you need to accept the offer before I can pay you?

**Comment by Tony-MK** [comment] 2023-10-17 05:59
@jliexpensify Apologies about that. Offer accepted.

**Comment by jliexpensify** [comment] 2023-10-17 06:02
Paid and job closed. @sobitneupane when you're back, please request ND payment and complete the checklist.

**Comment by deetergp** [comment] 2023-10-25 15:20
Still waiting on Sobit?

**Comment by jliexpensify** [comment] 2023-10-26 00:31
Yep to complete the checklist. I was told @sobitneupane would be back this week!

**Comment by jliexpensify** [comment] 2023-10-26 23:54
Pinged Sobit in Slack

**Comment by sobitneupane** [comment] 2023-10-27 13:08
Sorry for the delay. I was on leave. I will try to get to it in the weekend.

**Comment by jliexpensify** [comment] 2023-10-30 04:00
Thanks @sobitneupane and welcome back!

**Comment by sobitneupane** [comment] 2023-10-30 09:01
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/23703

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/23703/files#r1375876861
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not Required.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-30 09:03
**Regression Test Proposal**

1. Click on a report.
2. Verify the request header is displaying the correct email addresses.
3. Go to request details.
4. Change the request change currency.
5. Go back to the report.
6. Verify the request header has not changed.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-30 13:56
https://github.com/Expensify/App/issues/26392#issuecomment-1763829038

Requested payment on newDot.

**Comment by jliexpensify** [comment] 2023-10-30 22:12
Closing, thanks Sobit!

**Closed by jliexpensify** 2023-10-30 22:12 UTC
Labels: External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:18
$750 payment approved for @sobitneupane based on [this comment](https://github.com/Expensify/App/issues/26392#issuecomment-1763829038).
