### ISSUE TITLE
[$250] Hybrid Android - Emoji picker for status page overlap with save button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51138] opened 2024-10-20 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** testpayment935+468@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to Expensify hybrid android app
2. Go to setting - profile - status
3. Click drop down button to choose emoji

## Expected Result:
Emoji picker pop up without any overlap

## Actual Result:
Emoji picker overlap with save button when the first status was empty

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b9478a6e-672a-478f-bb31-3477ca40de50

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848448347625250199</li>
        <li>Upwork Job ID: 1848448347625250199</li>
        <li>Last Price Increase: 2024-11-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment] 2024-10-20 17:54
I marked the issue as a deploy because this issue is not repro on Hybrid prod app 
![Screenshot_20241020-203825](https://github.com/user-attachments/assets/0b75e533-3943-45e5-b68c-6ea8355bb6e3)

**Comment by IuliiaHerets** [comment] 2024-10-20 17:56
Issue reproducible on both stg and prod Android App

**Comment by yuwenmemon** [comment] 2024-10-21 19:33
Since this is reproducible on production as well, I'm removing the deploy blocker and taking this external.

**Comment by photoday0914** [comment] 2024-10-22 00:13
Implement a mechanism to detect the available screen space when the emoji picker is activated. This could involve calculating the distance from the bottom of the screen to the save button and positioning the emoji picker above or below it, depending on the available space.

**Comment by photoday0914** [comment] 2024-10-22 00:30
Contributor details
Your Expensify account email: nikoladev86@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/nikolad54

Implement a mechanism to detect the available screen space when the emoji picker is activated. This could involve calculating the distance from the bottom of the screen to the save button and positioning the emoji picker above or below it, depending on the available space. The calculation should be based on screen size. It may use function below.
```
export const vhToPx = (value, isNum) => {
  var w = window,
    d = document,
    e = d.documentElement,
    g = d.getElementsByTagName('body')[0],
    y = w.innerHeight || e.clientHeight || g.clientHeight

  var result = (y * value) / 100
  if (isNum) {
    return result
  } else {
    return result + 'px'
  }
}

export const responsiveDimension = val => {
  return IsMobile
    ? window.innerWidth / window.innerHeight <= 0.68
      ? mobileScale(val)
      : vhToPx(val)
    : vhToPx(val)
}
```

**Comment by QichenZhu** [comment] 2024-11-04 01:16
This seems similar to https://github.com/Expensify/App/issues/48100 and should have been fixed by https://github.com/Expensify/App/pull/51307.

**Closed** 2024-11-12 01:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
