### ISSUE TITLE
DEV: Console warning when typing an emoji - iOS

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23329] opened 2023-07-21 03:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run the iOS app in DEV mode i.e. run `npm run ios`.
2. Log into an account if you haven't already.
3. Open a 1-on-1 or group chat report.
4. Start typing an emoji e.g. ":smile:".
## Expected Result: 
There are no console warnings.
## Actual Result: 
You'll receive the following console warnings after the emoji suggestions' modal opens.
```
Overriding previous layout animation with new one before the first began.
```

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7fd54071-2526-4ec1-8ba8-83bfd5a247b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689775134244319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-07-21 14:23
I agree that this is a dupe of https://github.com/Expensify/App/issues/20552, which also mentions emojis specifically. Closing, thanks @tienifr

**Closed by conorpendergrast** 2023-07-21 14:23 UTC
Labels: Daily, Needs Reproduction, Bug
