### ISSUE TITLE
[HOLD for payment 2024-04-25] [$500] [LOW] Request money - When amount is highlighted, clicking on the page does not deselect the text

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36862] opened 2024-02-20 10:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Found when validating PR :** https://github.com/Expensify/App/pull/36463

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user should be logged in.

1. Initiate a manual money request.
2. Enter the amount.
3. Do a text selection.
4. Click on any part of the request page.
5. Verify the text is not deselected.

## Expected Result:
The text should be deselected after clicking on the page.

## Actual Result:
The text is not deselected, remains highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/99b42a5b-3369-4a23-9b00-a16a3c763c78

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01626cde7ff61398d1</li>
        <li>Upwork Job ID: 1760234439347433472</li>
        <li>Last Price Increase: 2024-03-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by izarutskaya** [comment] 2024-02-20 10:50
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.


We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by davidcardoza** [comment] 2024-02-20 22:29
Adding to the vip bill pay project board as a `LOW` issue

**Comment by situchan** [comment] 2024-02-21 16:42
I can take over.

I am not able to select text on main so stuck on Step 3. Looks like another regression

https://github.com/Expensify/App/assets/108292595/160dc05e-0efa-45d1-a259-145b3d34e75d

**Comment by laurenreidexpensify** [comment] 2024-02-22 10:12
@situchan assigned 👍

**Comment by situchan** [comment] 2024-02-26 16:47
ok so we can continue this issue

**Comment by situchan** [comment] 2024-02-28 13:52
This was deploy blocker.
@Krishna2323 @dukenv0307 are you able to find offending PR?

**Comment by situchan** [comment] 2024-02-28 14:03
Self-note: `onMouseDown` custom logic with `preventDefault` was intentionally added in https://github.com/Expensify/App/pull/16673 to fix https://github.com/Expensify/App/issues/16511

**Comment by laurenreidexpensify** [comment] 2024-03-04 05:36
@situchan proposal above ready for review thanks

**Comment by situchan** [comment] 2024-03-05 15:12
@brandonhenry thanks for the proposal. But I think your solution will cause regression - https://github.com/Expensify/App/issues/16511

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:47
Still waiting on proposals

**Comment by laurenreidexpensify** [comment] 2024-03-14 10:53
Still waiting on proposals and this is no longer on the roadmp

**Comment by situchan** [comment] 2024-03-18 21:22
Not overdue

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:40
@davidcardoza just reviewing again - can you confirm why you removed this from #vip-billpay-invoice? Thanks

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:40
*feel free to unassign once you've confirmed, thanks!

**Comment by davidcardoza** [comment] 2024-03-21 17:53
Yeah, I think that was just a mistake as I was going through posting an update in the VIP room. I readded it to the board.

**Comment by situchan** [comment] 2024-03-22 09:32
We intentionally prevented losing focus on https://github.com/Expensify/App/issues/16511.
So the expected behavior is only to deselect text while keeping input focus.
That being said, I am fine with the solution to clear selection.
I think we should keep the end of selection as cursor position. Otherwise it will cause regression:


https://github.com/Expensify/App/assets/108292595/7b9a68ab-9897-4992-a796-3e931442f6a8

**Comment by situchan** [comment] 2024-03-23 20:39
Please update proposals to cover the case above.

**Comment by situchan** [comment] 2024-03-24 01:51
@Expensify/design please confirm if this behavior is fine:


https://github.com/Expensify/App/assets/108292595/c0808508-86da-4db6-973b-bf574da6cfb7

**Comment by dubielzyk-expensify** [comment] 2024-03-24 23:45
Can you still double click the amount to select the the whole amount?

**Comment by situchan** [comment] 2024-03-24 23:47
> Can you still double click the amount to select the the whole amount?

yes, ofc. This doesn't affect text selection inside input.

**Comment by situchan** [comment] 2024-03-26 12:13
@Krishna2323's [alternative 2](https://github.com/Expensify/App/issues/36862#issuecomment-1954812083) solution looks good to me.
Demo video: https://github.com/Expensify/App/issues/36862#issuecomment-2016662419
🎀 👀 🎀 C+ reviewed

**Comment by hayata-suenaga** [comment] 2024-03-26 16:19
thank you for your proposal @Krishna2323 and for you review @situchan 🙇 

before approving the proposal, I have one question. Do we know why there is `event.preventDefault(); ` in the first place inside the mouse-down event listener?

**Comment by situchan** [comment] 2024-03-26 16:21
> before approving the proposal, I have one question. Do we know why there is `event.preventDefault(); ` in the first place inside the mouse-down event listener?

https://github.com/Expensify/App/issues/36862#issuecomment-1969051706

**Comment by hayata-suenaga** [comment] 2024-03-26 16:28
Thank you @situchan for the link 🙇 

[asking a question in the linked issue](https://github.com/Expensify/App/issues/16511#issuecomment-2020910798)

**Comment by situchan** [comment] 2024-03-28 02:01
@hayata-suenaga I am not sure they will answer to your question as issue was closed. How about bumping on slack or can we just go ahead?
Upon checking through all related issues / PRs, here's context:
-https://github.com/Expensify/App/issues/15855 is the original bug
-https://github.com/Expensify/App/pull/16394 was merged to fix https://github.com/Expensify/App/issues/15855
-While testing https://github.com/Expensify/App/pull/16394, QA found https://github.com/Expensify/App/issues/16511 so bug not fully fixed yet. It's the same symptom as https://github.com/Expensify/App/issues/15855 but just different platform
-They fixed that "regression" in https://github.com/Expensify/App/pull/16673

**Comment by hayata-suenaga** [comment] 2024-03-28 03:48
thank you for sharing the history of the changes made

let's go with @Krishna2323's fix

**Comment by laurenreidexpensify** [comment] 2024-04-17 11:00
https://www.upwork.com/jobs/~0116f3f562c4e1c59c

@situchan @Krishna2323 please apply in upwork

**Comment by hayata-suenaga** [comment] 2024-04-18 17:17
> [@hayata-suenaga] The PR that introduced the bug has been identified. Link to the PR:
>  [@hayata-suenaga] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
https://github.com/Expensify/App/pull/16394#issuecomment-2064623285
>  [@hayata-suenaga] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
No need for this

**Comment by laurenreidexpensify** [comment] 2024-04-25 10:24
@Krishna2323 pls accept offer in Upwork thanks! 

@situchan still offline this month

**Comment by laurenreidexpensify** [comment] 2024-04-26 08:24
Payment Summary:

Contributor: $500 @Krishna2323 paid in upwork
C+: $500 @situchan to be paid in Upwork

steps to complete when @situchan is back from OOO in May: 

- payment
- regression steps

**Comment by situchan** [comment] 2024-05-17 00:48
@laurenreidexpensify Sorry for late. Can you please send new offer?

**Comment by laurenreidexpensify** [comment] 2024-05-20 12:43
@situchan offer sent in upwork 👍

**Comment by laurenreidexpensify** [comment] 2024-05-21 08:13
Payment Summary:

Contributor: $500 @Krishna2323 paid in upwork
C+: $500 @situchan paid in upwork

**Comment by laurenreidexpensify** [comment] 2024-05-21 08:13
@situchan can you confirm regression testing steps so we can close out thanks

**Comment by situchan** [comment] 2024-05-21 08:19
### Regression Test Proposal

1. Initiate a manual money request
2. Enter the amount
3. Do a text selection
4. Click on any part of the request page
5. Verify the text is deselected

**Closed** 2024-05-22 10:38 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
