### ISSUE TITLE
IOU - All currencies in the list are bolded

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34644] opened 2024-01-17 14:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Request money > Manual.
2. Click on the currency.

## Expected Result:
Only the selected currency is bolded.

## Actual Result:
All the currencies in the list are bolded. This issue also occurs in Theme and Language selection page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/e9190a20-9c18-4b22-a83b-39bd6983196e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2024-01-17 14:26
This is a regression of this PR https://github.com/Expensify/App/pull/34357

**Comment by situchan** [comment] 2024-01-17 14:28
cc: @s77rt

**Comment by s77rt** [comment] 2024-01-17 14:32
Not a bug. This is done on purpose

**Comment by s77rt** [comment] 2024-01-17 14:33
cc @shawnborton for confirming in case I missed something here.

**Comment by shawnborton** [comment] 2024-01-17 14:46
Correct, this is intended behavior. cc @Expensify/design 

Closing!

**Closed by shawnborton** 2024-01-17 14:46 UTC
Labels: DeployBlockerCash, Engineering, Hourly

**Comment by amyevans** [comment] 2024-01-17 14:47
Thanks for confirming!
