### ISSUE TITLE
[$500]  Sign In - Unable to Sign In with apple account when user just signed out with google account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37429] opened 2024-02-28 14:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4344769&group_by=cases:section_id&group_order=asc&group_id=229043
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: the apple and google emails should be different
1. Open app
2. Sign In with google
3. Sign Out
4. Sign in with apple

## Expected Result:
User should be successfully signed in with apple account

## Actual Result:
When user clicked on apple icon user signed in back to the google account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0b1597ec-17a9-49d7-8471-0f8532dd2d22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f51417f38fb8ba4d</li>
        <li>Upwork Job ID: 1763208444232679424</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2024-02-29 14:21
I am having trouble recreating this (don't have an Apple account), so going to put "needs reproduction" on this

**Comment by CortneyOfstad** [comment] 2024-02-29 14:23
Think this may fall under Wave-9, so asked [here](https://expensify.enterprise.slack.com/archives/C05NJ4SLBMF/p1709216549247229).

**Comment by omarnagy91** [comment] 2024-03-03 20:09
## Proposal  :

### Problem:

A  user  cannot  successfully  sign  in  with  their  Apple  account  after  having  just  signed  out  of  their  Google  account.  Instead,  they  are  signed  back  into  their  Google  account.  This  issue  occurs  when  the  user  has  different  email  addresses  associated  with  their  Apple  and  Google  accounts.

### Root  Cause:

The  root  cause  appears  to  be  improper  handling  of  session  data  when  transitioning  between  different  sign-in  flows.  Remnants  of  the  previous  Google  account  session  might  not  be  fully  cleared  out,  interfering  with  the  subsequent  Apple  sign-in  attempt.

### Proposed  Changes:

1.  **Thorough  session  cleanup  on  sign-out:**
    
    -   Modify  Session.signOutAndRedirectToSignIn  to  explicitly  clear  out  all  session-related  data  in  Onyx,  including  ONYXKEYS.SESSION  and  ONYXKEYS.CREDENTIALS.
        
2.  **Handle  new  user  sign-in  appropriately:**
    
    -   In  App.setUpPoliciesAndNavigate,  check  if  the  user  is  signing  in  as  a  new  user.  If  so,  clear  any  existing  policy  and  report  data  in  Onyx  before  setting  up  the  new  user's  policies.
        
3.  **Manage  navigation  transitions  between  sign-in  flows:**
    
    -   Update  Navigation.navigate  and  Navigation.dismissModal  to  clear  any  existing  sign-in  state  when  navigating  to  or  dismissing  a  sign-in  screen.
        
4.  **Address  potential  race  conditions:**
    
    -   Review  the  sign-in/sign-out  flow  to  identify  and  address  any  potential  race  conditions.
        
5.  **Verify  backend  handling  of  multiple  sign-in  accounts:**
    
    -   Ensure  the  backend  correctly  handles  the  scenario  where  a  user  signs  in  with  a  different  account  after  signing  out  of  another.
        

### Replacement  Code:

**1.  Session.signOutAndRedirectToSignIn:**

```
function signOutAndRedirectToSignIn() {
    // Clear all session-related data in Onyx
    Onyx.set(ONYXKEYS.SESSION, null);
    Onyx.set(ONYXKEYS.CREDENTIALS, null);

    // Redirect the user to the sign-in page
    Navigation.navigate(ROUTES.SIGN_IN);
}
```

**2.  App.setUpPoliciesAndNavigate:**

```
function setUpPoliciesAndNavigate(session) {
    const currentUrl = getCurrentUrl();
    const isLoggingInAsNewUser = !!session?.email && SessionUtils.isLoggingInAsNewUser(currentUrl, session.email);

    if (isLoggingInAsNewUser) {
        // Clear any existing policy and report data in Onyx
        Onyx.set(ONYXKEYS.COLLECTION.POLICY, null);
        Onyx.set(ONYXKEYS.COLLECTION.REPORT, null);
    }

    // ... rest of the function logic ...
}
```



**3.  Navigation.navigate  and  Navigation.dismissModal:**

```
function navigate(route = ROUTES.HOME, type) {
    if (!canNavigate('navigate', {route})) {
        return;
    }

    // Clear any existing sign-in state if we're navigating to a sign-in screen
    if (route === ROUTES.SIGN_IN || route === ROUTES.SIGN_IN_MODAL) {
        Onyx.set(ONYXKEYS.SESSION, null);
        Onyx.set(ONYXKEYS.CREDENTIALS, null);
    }

    linkTo(navigationRef.current, route, type, isActiveRoute(route));
}

function dismissModal(reportID, ref = navigationRef) {
    if (!canNavigate('dismissModal')) {
        return;
    }

    // Clear any existing sign-in state if we're dismissing a sign-in modal
    const state = ref.getState();
    const lastRoute = state.routes.at(-1);
    if (lastRoute?.name === SCREENS.RIGHT_MODAL.SIGN_IN) {
        Onyx.set(ONYXKEYS.SESSION, null);
        Onyx.set(ONYXKEYS.CREDENTIALS, null);
    }

    // ... rest of the dismissModal logic ...
}
```



This  proposal  provides  a  comprehensive  solution  to  the  issue,  addressing  the  potential  root  causes  and  offering  specific  code  changes  to  implement  the  fix.  I  believe  this  solution  will  effectively  resolve  the  problem  and  improve  the  user  experience.

**Comment by omarnagy91** [comment] 2024-03-04 12:40
@parasharrajat 
Yes, I reproduced the issue and isolated the root cause. I think I  have a solution. Would you like to discuss the details?

**Comment by CortneyOfstad** [comment] 2024-03-11 18:33
@parasharrajat can you provide an update on @omarnagy91's proposal [here](https://github.com/Expensify/App/issues/37429#issuecomment-1975282452)? Are we good to move forward or does this need feedback/adjustment?

**Comment by CortneyOfstad** [comment] 2024-03-14 12:06
@parasharrajat can you please provide an update here by EOD? Otherwise, let me know if we need to assign another C+ — thanks!

**Comment by CortneyOfstad** [comment] 2024-03-14 19:48
I just attempted this as well and wasn't able to reproduce. Going to close this — @lanitochka17 if this issue pops up again, feel free to reopen!

**Closed by CortneyOfstad** 2024-03-14 19:48 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
