### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Workspace - Opening rate unit workspace page on login displays '0.000' and changing value does not work

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26131] opened 2023-08-28 21:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->reimbursements->Rate
3. Copy the URL
4. Logout and paste the URL
5. Login and observe that rate is displayed as '0.000'
6. Change the rate to any value and click save
7. Observe that app still displays old value and new value is not saved

## Expected Result:
App should display correct value on rate unit workspace page on login and save the value if value is changed

## Actual Result:
App displays '0.000' as rate on rate unit workspace page on login and on changing and saving the value, it does not change the value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-6

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/561a61f8-0d3d-49b3-b34f-a7bd7631f40c

https://github.com/Expensify/App/assets/115492554/86a2a194-8cef-4dd3-9a13-a48bde0ae1d5

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692551644917109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ad1f796cb41f15e</li>
        <li>Upwork Job ID: 1696988525560631296</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 26784715</li>
<li>dhanashree-sawant | Reporter | 26784718</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-08-29 07:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Opening rate unit workspace page on login displays '0.000' and changing value does not work
### What is the root cause of that problem?
The rate data is fetched using `Policy.openWorkspaceReimburseView` [action](https://github.com/Expensify/App/blob/fd755ee94ee9aed354e528abc0b62d19a90802c2/src/libs/actions/Policy.js#L1092). This action is triggered when we access Reimbursements [page](https://github.com/Expensify/App/blob/fd755ee94ee9aed354e528abc0b62d19a90802c2/src/pages/workspace/reimburse/WorkspaceReimburseView.js#L113). 

When we access rates page with link itself bypassing reimbursement page, this action is not triggered, thus making rate data not available for us.

Also another problem is that if you access it in offline mode or slow internet connection, the data won't be loaded and it shows 0, even if data is loaded if you are in rates page, it won't be updated in TextInput
### What changes do you think we should make in order to solve the problem?

To fetch data when rates page is directly accessed, we can apply something like this, which checks if we have rates data and if not it will try to fetch it:
```javascript
 componentDidMount() {
        if (lodashGet(this.props, 'policy.customUnits', []).length === 0) {
            BankAccounts.setReimbursementAccountLoading(true);
            Policy.openWorkspaceReimburseView(this.props.policy.id);
        }
    }
```

 We should update inputs when rate data is fetched. I couldn't find any way of modifying input's value, since inputs are using `inputID` and not `value` and `onValueChange`. But I hope there is a way, or we can just use `value` and `onValueChange` props.

The another problem with this approach is that when user is modifying inputs and data is fetched it will interrupt user and set input value itself confusing user. 
I think we should show some type of loading indicator since user should be aware of that the input data is not available yet but they can change it if they want.

We can maybe utilize pendingActions here by passing `reimbursementAccount.isLoading` state
https://github.com/Expensify/App/blob/a997962e5b67740b3b07f05b09b5a08e5fc1fd0d/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage.js#L129

### What alternative solutions did you explore? (Optional)

**Comment by cristipaval** [comment] 2023-09-11 20:34
friendly bump @neil-marcellini

**Comment by cristipaval** [comment] 2023-09-15 19:24
I'll get back on Monday to this one.

**Comment by cristipaval** [comment] 2023-09-20 20:22
@alitoshmatov, you're all set.

**Comment by neil-marcellini** [comment] 2023-09-21 03:17
> I wonder if this is because the offline behaviour is not yet implemented for Distance requests. If I recall correctly, we postponed this due to the tight deadline. @neil-marcellini could you please confirm?

I don't think this is related to distance requests because this page was built long before then.

**Comment by dhanashree-sawant** [comment] 2023-09-21 04:52
Hi @kevinksullivan, the following issue was raised on 29 August but melvin bot has provided me with 50$ offer, can you have a look once you are available?

**Comment by alitoshmatov** [comment] 2023-09-22 10:46
PR is ready - https://github.com/Expensify/App/pull/28004

**Comment by alitoshmatov** [comment] 2023-10-12 09:15
This is one ready for payment

**Comment by cristipaval** [comment] 2023-10-16 14:31
@rushatgabhane Could you please take care of the checklist? 🙏

**Comment by kevinksullivan** [comment] 2023-10-19 14:53
Payment summary

Reporter: @dhanashree-sawant $250
Contributor: @alitoshmatov $500
C+: @rushatgabhane $500

**Comment by JmillsExpensify** [comment] 2023-10-19 14:57
$500 payment approved for @rushatgabhane based on summary above.

**Comment by alitoshmatov** [comment] 2023-10-21 11:30
@kevinksullivan  Friendly bump, I am also waiting for payment on upwork.

**Comment by cristipaval** [comment] 2023-10-23 20:35
@kevinksullivan is ooo until 26th. @alitoshmatov are you ok to wait or you want me to reassign someone able to pay?

**Comment by alitoshmatov** [comment] 2023-10-24 04:48
That's fine, I will wait till @kevinksullivan is back

**Comment by kevinksullivan** [comment] 2023-10-27 02:58
@alitoshmatov paid out. @dhanashree-sawant let me know when you accept this offer.

**Comment by cristipaval** [comment] 2023-10-30 15:06
Are we good to close this one?

**Comment by cristipaval** [comment] 2023-11-02 14:35
friendly bump @kevinksullivan 
Is @dhanashree-sawant paid alreayd? Can we close this one?

**Comment by dhanashree-sawant** [comment] 2023-11-03 05:21
@kevinksullivan has sent me the offer but milestone approval is left.

**Comment by cristipaval** [comment] 2023-11-06 12:28
@kevinksullivan has been OOO, I think he'll be back today. I pinged him internally.

**Comment by kevinksullivan** [comment] 2023-11-07 00:11
I'm confused... @dhanashree-sawant can you link the job where it says I need to pay? For whatever reason I don't see you assigned to the original job and it's closed now

https://www.upwork.com/jobs/~014ad1f796cb41f15e

I am not seeing a separate one either. If you can link me to it that would be great. Otherwise I can create a new one.

**Comment by dhanashree-sawant** [comment] 2023-11-07 05:18
This is the message room for that job, not sure if this link will work for you or not but I have sent 'Hi' on upwork in that room
https://www.upwork.com/ab/messages/rooms/room_9b3ffa8158877d7ec9f9b8c997f4fa36?sidebar=true

**Comment by kevinksullivan** [comment] 2023-11-07 22:24
all set

**Closed by kevinksullivan** 2023-11-07 22:24 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
