### ISSUE TITLE
[HOLD #33315][VIP-VSP][$500] Chat - Unpinned deleted tasks assigned by another user are shown above other pinned messages

### ISSUE THREAD

**Issue by Christinadobrzyn** [Expensify/App#33477] opened 2023-12-22 01:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login with Account A on new Expensify and assign a task to Account B (example: Tester login credential: [gatantm+82@gmail.com](mailto:gatantm+82@gmail.com,)    [gatantm+112@gmail.com](mailto:gatantm+112@gmail.com))
2. Click on the checkbox of the Task > deselect > Click the three dots
3. Cancel the task
4. Login with Account B > find the Deleted task in the LHN
5. You shouldn't see the GBR and deleted task

Note: If you don't see it above the pinned messages, click on the [Deleted task] message again and eventually it displays above the pinned chats

Expected Result:
The deleted task report should not appear between GRB reports

Actual Result:
The task report still appears between GRB reports and GRB appear in the deleted task report

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/141406735/f0729f1b-6153-4cc0-b68e-d1b5fe0b6cc4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df61cddd3904c57f</li>
        <li>Upwork Job ID: 1738278949092667392</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-12-22 01:06
Related to https://github.com/Expensify/App/issues/30798

**Comment by DylanDylann** [comment] 2023-12-22 02:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After canceling the task the GRB still displays on LHN

### What is the root cause of that problem?
After canceling the task the GRB still displays on LHN, The pusher return taskReport.isDeletedParentAction === true . But we don't add this field in this function
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/libs/SidebarUtils.ts#L232

### What changes do you think we should make in order to solve the problem?
in this function
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/libs/SidebarUtils.ts#L232

we should return  `isDeletedParentAction`
```
    result.isDeletedParentAction = report.isDeletedParentAction;

```

We also need to do the same thing in the chat report selector here
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/pages/home/sidebar/SidebarLinksData.js#L170
should add
```
        isDeletedParentAction: report.isDeletedParentAction

```

### What alternative solutions did you explore? (Optional)
NA

### Result

https://github.com/Expensify/App/assets/141406735/ea023fd8-2a72-46ca-a9e8-8afa750bd81d

**Comment by Christinadobrzyn** [comment] 2023-12-22 18:21
I think this should get fixed, I think it can be part of the VIP-VSB - asking for a review.

**Comment by Christinadobrzyn** [comment] 2023-12-22 19:22
Added this to VIP-VSP. We can accept proposals for this!

**Comment by FitseTLT** [comment] 2023-12-26 16:12
Can't reproduce it. Neither do I see the GRB nor see the deleted task above pinned chats after logging in Account B.

**Comment by DylanDylann** [comment] 2023-12-28 11:51
I still can reproduce on the latest main, @FitseTLT Could you attach your video ?

**Comment by alitoshmatov** [comment] 2023-12-29 18:34
Looks like this issue and https://github.com/Expensify/App/issues/33315 might have the same root cause. I suggest we hold this issue in favor of https://github.com/Expensify/App/issues/33315#issuecomment-1872267037.

**Comment by Christinadobrzyn** [comment] 2024-01-03 01:02
adding a HOLD to this in favour of https://github.com/Expensify/App/issues/33477#issuecomment-1872267861

**Comment by mvtglobally** [comment] 2024-01-03 05:54
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-01-03 20:28
monitoring

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:20
I'm going to be ooo for a week so adding a buddy to monitor this while I'm gone. 

Status - this is on hold for https://github.com/Expensify/App/issues/33477#issuecomment-1872267861 & KI retests aren't showing this (so we might be able to just close this).

**Comment by garrettmknight** [comment] 2024-01-09 20:04
Still holding

**Comment by garrettmknight** [comment] 2024-01-12 18:47
Still holding!

**Comment by garrettmknight** [comment] 2024-01-15 16:22
Couldn't reproduce! Closing!

**Closed by garrettmknight** 2024-01-15 16:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
