### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250]  Netsuite - App crashes when submitting an expense after disconnecting from NetSuite

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46508] opened 2024-07-30 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
. Log in with a new expensifail account
2. Create a new workspace
3. Go to more features > Enable Accounting
4. Go to Accounting > Connect to NetSuite
5. Upgrade the workspace to Control > Navigate back to Accounting > Finish the connection to NetSuite
6. Go to Accounting > Click on the 3 dot menu next to NetSuite
7. Click on "Disconnect" > Confirm the disconnection > Check that the integration is removed from the workspace
8. Navigate back from workspace page and go to FAB
9 Click on FAB > Submit Expense > Manual > Enter an amount
10. Select the control workspace you disconnected NetSuite from

## Expected Result:
The expense is submitted to the workspace

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] #46558
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/43e8344d-9d28-4f0e-bbe9-1130ed71a8e5

[logs (2).txt](https://github.com/user-attachments/files/16430106/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7f4450015473810</li>
        <li>Upwork Job ID: 1819341847955308171</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>ShridharGoel | Contributor | 103438151</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by luacmartins** [comment] 2024-07-30 16:19
I think that'd be @yuwenmemon

**Comment by bfitzexpensify** [comment] 2024-08-02 11:58
Setting this as external for the moment - @yuwenmemon is ooo until August 13th.

**Comment by eVoloshchak** [comment] 2024-08-07 15:33
Both proposals are fairly similar (different implementation, but same root cause and effectively the same fix, just in different place), I think we can proceed with @ShridharGoel's [proposal](https://github.com/Expensify/App/issues/46508#issuecomment-2258631532)

🎀👀🎀 C+ reviewed!

**Comment by bfitzexpensify** [comment] 2024-08-12 11:32
@ShridharGoel when will you be able to raise a PR here?

**Comment by eVoloshchak** [comment] 2024-11-04 20:03
This shouldn't be closed, [PR](https://github.com/Expensify/App/pull/47232) fixing this is still open and close to being merged

**Comment by bfitzexpensify** [comment] 2024-11-21 13:03
Payment complete to @ShridharGoel 

@eVoloshchak - please complete the BZ checklist and I'll finalise the payment summary for your C+ work - thanks!

**Comment by bfitzexpensify** [comment] 2024-12-03 22:02
Bump here @eVoloshchak

**Comment by eVoloshchak** [comment] 2024-12-04 18:12
- The PR that introduced the bug has been identified. Link to the PR: No PR that has introduced this, this is an error in the original implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not needed, this is a rare edge case


**Regression Test Proposal**

1. Create a new workspace
2. Go to More Features > Enable Accounting
3. Go to Accounting > Connect to NetSuite
4. Upgrade the workspace to Control > Navigate back to Accounting > Finish the connection to NetSuite
5. Go to Accounting > Click on the 3 dot menu next to NetSuite
6. Click on "Disconnect" > Confirm the disconnection > Check that the integration is removed from the workspace
7. Navigate back from workspace page and go to FAB
8. Click on FAB > Submit Expense > Manual > Enter an amount
9. Select the control workspace you disconnected NetSuite from.
10. Verify the app doesn't crash and the expense is submitted.

**Do we agree 👍 or 👎**

**Comment by bfitzexpensify** [comment] 2024-12-04 18:31
Works for me!

Payment summary: @eVoloshchak to be paid $250 for C+ work via manual request

**Closed by bfitzexpensify** 2024-12-04 18:31 UTC
Labels: External, Daily, Awaiting Payment, Not a priority, Bug

**Comment by JmillsExpensify** [comment] 2025-01-14 11:06
$250 approved for @eVoloshchak
