### ISSUE TITLE
Web- Tooltip isn't showing for continuous carousel unlike Slack

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19725] opened 2023-05-28 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any chat and send 4 images
3. Click on the first image to preview and click on next arrow button continuously and see that the tooltip doesn't show for continuous movement
4. Follow the same steps on slack and see that on continuous navigation tooltip is shown. Since we follow the similar slack functionality , tooltip should be shown

## Expected Result:
Tooltip should be shown on continuous carousel movement

## Actual Result:
Tooltip is not shown on continuous carousel movement unlike Slack

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c582faa8-01af-4cfd-8bf0-b79993cd6c31

https://github.com/Expensify/App/assets/93399543/a0feddc8-7944-4e62-8de9-72d3dbd324ae

**Expensify/Expensify Issue URL:**

**Issue reported by:** @avi-shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684988066381189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by avi-shek-jha** [comment] 2023-05-29 03:37
@kbecciv I have reported this issue and seems like you've assigned someone else with the same name. My GH handle is : @avi-shek-jha. It would be great if you could update the initial reporter name. Thanks

**Comment by MrJithil** [comment] 2023-05-29 14:17
Seems a duplicate of #19693

**Comment by JmillsExpensify** [comment] 2023-05-31 01:56
Based on a review of that issue, I agree. Closing, but comment if you disagree with @MrJithil's latest post.

**Closed by JmillsExpensify** 2023-05-31 01:56 UTC
Labels: Daily, Overdue, Bug

**Comment by priya-zha** [comment] 2023-05-31 02:49
@JmillsExpensify [This](https://github.com/Expensify/App/issues/19725) bug was already a duplicate of the bug [here](https://github.com/Expensify/App/issues/17307) which was created earlier on April. According to you and @MrJithil , if this [bug](https://github.com/Expensify/App/issues/19725) is a duplicate of [19693](https://github.com/Expensify/App/issues/19693) bug, then I think [19693](https://github.com/Expensify/App/issues/19693) should also be the duplicate of [17307](https://github.com/Expensify/App/issues/17307). Please let me know your thoughts on this.
