### ISSUE TITLE
Distance - Distance rate with 4 decimal values are not shown correctly in expense report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52342] opened 2024-11-11 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/50783
## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Go to workspace settings- more features
3. Enable distance rates
4. Add rate with 4 decimal values eg: 0.9876
5. Go to LHN
6. Open workspace chat
7. Submit a distance expense selecting 4 digit decimal value distance rate
8.Open the expense report and note the distance rate

## Expected Result:
Distance rate with 4 decimal values must be shown correctly in expense report

## Actual Result:
Distance rate with 4 decimal values are not shown correctly in expense report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/fdc94d87-cd34-4a20-a2ec-7c5c3fef7692

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-11-11 20:27
Production:

https://github.com/user-attachments/assets/3135ca18-34ba-4bcc-8b3e-ab83c4434320

**Comment by luacmartins** [comment] 2024-11-11 21:01
Left a comment https://github.com/Expensify/App/issues/52342. I think that PR might be the cause.

**Comment by luacmartins** [comment] 2024-11-11 21:30
I can't reproduce the issue in staging 🤔

**Comment by luacmartins** [comment] 2024-11-11 21:41
Just managed to reproduce with the exact amount from the video

**Comment by luacmartins** [comment] 2024-11-11 21:43
Confirmed that reverting https://github.com/Expensify/App/pull/50783 fixes the issue

**Comment by luacmartins** [comment] 2024-11-11 21:43
Looking into a fix

**Comment by luacmartins** [comment] 2024-11-12 16:12
We're reverting the offending PR.

**Comment by luacmartins** [comment] 2024-11-12 16:34
Confirmed this is fixed in staging. Closing.

**Closed by luacmartins** 2024-11-12 16:34 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly
