### ISSUE TITLE
Web - Asign task - Task checkbox remains unchecked briefly after being marked as done

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25411] opened 2023-08-17 15:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Assign task" section.
3. Enter a title and create the task.
4. Once created, mark the task as done by checking the task checkbox.
5. Switch to the userB account and check the task checkbox.
6. Observe that the checkbox doesn't immediately appear checked for userB.

## Expected Result:
The checkbox should display as checked right after being marked as done for userB

## Actual Result:
The task checkbox remains unchecked for a brief period after being marked as done

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/3bbca620-5f94-44d9-9792-e920510c0f58

https://github.com/Expensify/App/assets/115492554/01fe6805-d2ca-4d19-a530-9e91219ff9fd

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691434585315249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fe58f557accb575</li>
        <li>Upwork Job ID: 1692495663048761344</li>
        <li>Last Price Increase: 2023-08-18</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-17 17:01
I think it is BE bug, pusher doesn't return fully data for task report action

**Comment by flaviadefaria** [comment] 2023-08-18 11:16
Seems like this is an internal bug so adding the internal label to confirm.

**Comment by flaviadefaria** [comment] 2023-08-18 11:17
@JmillsExpensify I'm heading OoO for a week so assigning you this issue in the meantime.

**Comment by abdulrahuman5196** [comment] 2023-08-21 11:47
@JmillsExpensify It seems the issue is in Internal state. What are the next steps here? Will an internal engineer look into this?

**Comment by abdulrahuman5196** [comment] 2023-08-25 14:17
Bump @JmillsExpensify

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:14
Bumped @JmillsExpensify in slack. He mentioned to check on this tomorrow.

**Comment by JmillsExpensify** [comment] 2023-08-29 03:25
Thanks for the bump. We actually seem to get a lot of these "bugs" where something doesn't "update immediately" for the other person, but I'm pretty wary that we should be treating these as such. Minimally if we want to do something, we should put all these reports on one tracking issue for every time they come up, and then take a look at them holistically. That would allow us to more definitely set an expectation around what "immediate" means, and just as importantly, tackle these all together instead of separately.

**Comment by flaviadefaria** [comment] 2023-08-30 13:41
@JmillsExpensify I'm back from OoO and can take this over again. Based on your previous comment would you say we can close this or what would you suggest as next steps?

**Comment by flaviadefaria** [comment] 2023-09-04 10:21
DM'ed @JmillsExpensify about this GH to make sure we're aligned on the next steps.

**Comment by flaviadefaria** [comment] 2023-09-11 11:04
I'll close this for now.

**Closed by flaviadefaria** 2023-09-11 11:04 UTC
Labels: Daily, Internal, Overdue, Bug
