### ISSUE TITLE
Chat - Skeleton appears for a moment when swiping from open chat to LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19536] opened 2023-05-24 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with any account
3. Go to any chat
4. Swipe to navigate back to the LHN

## Expected Result:
User navigate back to the LHN without skeleton

## Actual Result:
Skeleton appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/fc9c53f4f9f3913ffe8e217ae1d121ddbc3fd9631574cedcd1ec27f3c9f5850e

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e983b069e6c2cf3</li>
        <li>Upwork Job ID: 1671611443028774912</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2023-06-13 19:50
Issue reproduce with Build 1.3.27.4

https://github.com/Expensify/App/assets/78819774/59dd8ddd-688f-4df7-9280-70368450d61f

**Comment by kbecciv** [comment] 2023-06-21 20:21
@joekaufmanexpensify Issue is reproductible https://github.com/Expensify/App/issues/19536#issuecomment-1589925407

**Comment by joekaufmanexpensify** [comment] 2023-06-21 22:10
Got it, thanks! I will take another look now.

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 12:35
I believe this intentional. Not a bug.

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 19:24
@joekaufmanexpensify https://github.com/Expensify/App/issues/12635

**Comment by joekaufmanexpensify** [comment] 2023-06-22 19:36
I agree. I also am not seeing what is described in OP of the issue in [the video ](https://github.com/Expensify/App/issues/19536#issuecomment-1589925407). The skeleton UI appears momentarily when the chat is opened (which is expected from time to time). But when swiping back from the chat to LHN. I am not seeing any skeleton UI. Nor can I reproduce any skeleton UI when swiping back from chat to LHN. 

Closing as it doesn't seem like there is a bug here.

**Closed by joekaufmanexpensify** 2023-06-22 19:36 UTC
Labels: Daily, Internal, Bug
