### ISSUE TITLE
website preview needs screen adjustments to show up

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21403] opened 2023-06-23 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. open a chat and send google.com

## Expected Result: 
should show preview automatically

## Actual Result: 
preview disappears on changing screen size
we require to make the screen size smaller, and then bigger, or sometimes a reload is required to get the preview

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction (works fine at my end)
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a082ec3c-94d8-42c9-b36f-00ca74963cb3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686987629884009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2023-06-26 16:39
asked follow up q in slack thread

**Comment by sonialiap** [comment] 2023-06-29 16:27
I'm not able to reproduce, neither is Kavi. Closing this while waiting for response from Chirag in slack.

**Closed by sonialiap** 2023-06-29 16:27 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
