### ISSUE TITLE
[HOLD for payment 2024-02-15] [$500]  IOU - Dismissing IOU deletion error also dismisses IOU preview when the preview should stay

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35434] opened 2024-01-30 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. [User A] Request money from User B
2. [User A] Go to IOU report
3. [User A] Go offline
4. [User B] Pay the request
5. [User A] Delete the request while offline and stay in the main chat
6. [User A] Go online
7. [User A] Dismiss the error message in the main chat

## Expected Result:
Since the deleted IOU request fails, the IOU preview should appear in the main chat

## Actual Result:
After dismissing the deletion error, the IOU preview is also dimissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6438c80e-10d1-44ed-96ea-bed61be8c8bf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117ee863b24012323</li>
        <li>Upwork Job ID: 1752426712396840960</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28142911</li>
<li>bernhardoj | Contributor | 28142912</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-30 20:22
We think that this bug might be related to #vip-bills. 
CC @davidcardoza

**Comment by Tony-MK** [comment] 2024-01-30 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Dismissing IOU deletion error also dismisses IOU preview when the preview should stay

### What is the root cause of that problem?

We are not passing the `pendingAction` prop, hence it can not delete itself when dismissing the error

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/components/ReportActionItem/MoneyRequestPreview.js#L259-L266

### What changes do you think we should make in order to solve the problem?


Pass the `pendingAction` prop.

```
pendingAction={lodashGet(props.action, 'pendingAction', null)}
```

We can use `shouldDisableOpacity` to prevent the component from dimming itself.

**Comment by Tony-MK** [comment] 2024-01-30 22:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Dismissing IOU deletion error also dismisses IOU preview when the preview should stay

### What is the root cause of that problem?

In the `ReportActionItem` file, we are not passing the `shouldHideOnDelete` prop as `false` in this situation.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L733-L736

Hence, the `ReportPreview` won't be displayed when the error is dismissed.

### What changes do you think we should make in order to solve the problem?


We can use the `Report.isSettled(props.report)` output to check if the report was already settled.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L736

Combine the prior condition to create a condition that will look something close to this.

```
shouldHideOnDelete={
  !ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID) ||
  Report.isSettled(props.report)
}
```

**Comment by Tony-MK** [comment] 2024-01-31 01:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Dismissing IOU deletion error also dismisses IOU preview when the preview should stay

### What is the root cause of that problem?

While [`ReportActionItem`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L736) creating the `ReportPreview` component, the `shouldHideOnDelete` prop as `false` in this situation.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L733-L736

Hence, if the IOU was settled, the `ReportPreview`'s `OfflineWithFeedback` parent component will hide the `ReportPreview` once the error is dismissed.

### What changes do you think we should make in order to solve the problem?

We will mainly use the `Report.isSettled` function to check if it was settled and combine this with the current condition to create a condition that will handle this situation and should look something close to this.

```
const shouldHideOnDelete = !(
   ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID) ||  
   ReportUtils.isSettled(props.iouReport ? props.iouReport.reportID : props.report.reportID)
);
```

For the `ReportPreview` components check for the presence of [`props.iouReport`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L799-L803).

When [`props.iouReport`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L799-L803) is not available, use `props.report.reportID` to handle `MoneyRequestPreview` components.

***A More precise condition***

```
const shouldHideOnDelete = ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID) || 
(ReportActionsUtils.isReportPreviewAction(props.action) && !ReportUtils.isSettled(props.iouReport.reportID)) || 
(ReportActionsUtils.isMoneyRequestAction(props.action) && !ReportUtils.isSettled(props.report.reportID)) ;
```

Finally, use `shouldHideOnDelete` as the prop for the parent `OfflineWithFeedback` component shown below.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L736

**Question**  
Since the same error also appears on the `MoneyRequestPreview` component, even if it was dismissed earlier on the `ReportPreview` component, should we also use `Report.clearIOUError` in the `OfflineWithFeedback`'s `onClose` function to clear the IOU error and vice-versa?

**Comment by Tony-MK** [comment] 2024-01-31 01:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - Dismissing IOU deletion error also dismisses IOU preview when the preview should stay

### What is the root cause of that problem?

While [`ReportActionItem`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L736) creating the `ReportPreview` component, the `shouldHideOnDelete` prop as `false` in this situation.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L733-L736

Hence, if the IOU was settled, the `ReportPreview`'s `OfflineWithFeedback` parent component will hide the `ReportPreview` once the error is dismissed.

### What changes do you think we should make in order to solve the problem?

We will mainly use the `Report.isSettled` function to check if it was settled and combine this with the current condition to create a condition that will handle this situation and should look something close to this.

```
const shouldHideOnDelete = !(
   ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID) ||  
   ReportUtils.isSettled(props.iouReport ? props.iouReport.reportID : props.report.reportID)
);
```

For the `ReportPreview` components check for the presence of [`props.iouReport`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L799-L803).

When [`props.iouReport`](https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L799-L803) is not available, use `props.report.reportID` to handle `MoneyRequestPreview` components.

***A More precise condition***

```
const shouldHideOnDelete = !(
  ReportActionsUtils.isThreadParentMessage(props.action, props.report.reportID) || 
  (ReportActionsUtils.isReportPreviewAction(props.action) && ReportUtils.isSettled(props.iouReport.reportID)) || 
  (ReportActionsUtils.isMoneyRequestAction(props.action) && ReportUtils.isSettled(props.report.reportID))
);
```

Finally, use `shouldHideOnDelete` as the prop for the parent `OfflineWithFeedback` component shown below.

https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/pages/home/report/ReportActionItem.js#L736

**Question**  
Since the same error also appears on the `MoneyRequestPreview` component, even if it was dismissed earlier on the `ReportPreview` component, should we also use `Report.clearIOUError` in the `OfflineWithFeedback`'s `onClose` function to clear the IOU error and vice-versa?

**Comment by bernhardoj** [comment] 2024-01-31 04:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we close the request preview error message, the report preview also disappears, but it should stay visible.

### What is the root cause of that problem?
When we delete the request, we optimistically set the `pendingAction` to DELETE.
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/libs/actions/IOU.js#L2629

If we pay the request from the requested user, the delete action will fail when we come back online. If fails, the error message will show with a close button, but the DELETE `pendingAction` still exists.

If the `pendingAction` is DELETE while online, the view should be hidden, but because we have an error message, the view is displayed.
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/components/OfflineWithFeedback.tsx#L85
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/components/OfflineWithFeedback.tsx#L94

So, once we press the close error message, the request view is hidden.
### What changes do you think we should make in order to solve the problem?

We should clear the `pendingAction` when the delete fails.
https://github.com/Expensify/App/blob/4e88eea26a79c7d69e3bf9fac28a515586c3855b/src/libs/actions/IOU.js#L2813-L2816

_this is very similar to https://github.com/Expensify/App/issues/33158, but on a different component and under a different condition which I didn't expect it would have the same issue_

**Comment by situchan** [comment] 2024-02-05 15:46
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/35434#issuecomment-1918342632) looks good to me.
Agree this is separate issue. Btw the regression period of https://github.com/Expensify/App/issues/33158 is already over.
🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-02-06 07:36
PR is ready

cc: @situchan

**Comment by garrettmknight** [comment] 2024-02-14 19:12
@isabelastisser reassigning for payment since I'll be OOO when the date comes. Thanks!

**Comment by isabelastisser** [comment] 2024-02-16 03:31
Hey @situchan, can you please complete the checklist? Thanks!

**Comment by isabelastisser** [comment] 2024-02-16 03:35
Payment summary:

@situchan Reviewier $500 - paid in Upwork
@bernhardoj Contributor $500 - paid in Upwork

**Comment by isabelastisser** [comment] 2024-02-16 15:38
bump @situchan to complete the list so we can close this. Thanks!

**Comment by situchan** [comment] 2024-02-18 12:39
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33697
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33697/files#r1493756666
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No need another regression test as caught by QA team

**Comment by isabelastisser** [comment] 2024-02-20 02:24
Thanks @situchan! All set.

**Closed by isabelastisser** 2024-02-20 02:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
