### ISSUE TITLE
[$500] Web - User can still access attachment thread after left the thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27427] opened 2023-09-14 10:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app on chrome, reply on someone by sending an attachment and click on "reply on thread" on the attachment
2. Reply by sending messages
3. Open the [Attachment] message and click on "Leave thread".
4. "Hm... it's not here You don't have access to this chat" message will be shown but then you'll be redirected to the attachment you have left and supposed to have no access anymore (based on what the previous description showed).

## Expected Result:
It should be showing a skeleton after user left the tread

## Actual Result:
User can still access attachment thread after left the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c2e47be4-8e67-4ba7-92d5-b3f8664c3029

https://github.com/Expensify/App/assets/93399543/6bbaeb2c-6531-476a-a960-c3646b33eab3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niatania102
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694446243712749

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137f77b386e8c8eb4</li>
        <li>Upwork Job ID: 1702274114805768192</li>
        <li>Last Price Increase: 2023-09-21</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-09-18 09:08
@eVoloshchak please review the above

**Comment by adelekennedy** [comment] 2023-09-21 07:52
@eVoloshchak review on the above please

**Comment by eVoloshchak** [comment] 2023-09-21 12:52
Is this bug still present?
I can't reproduce using the steps from the description, it already works exactly as it should, showing the skeleton while loading

https://github.com/Expensify/App/assets/9059945/948ad390-4363-409b-ae0c-630942f04f7c

**Comment by eVoloshchak** [comment] 2023-09-21 16:01
@adelekennedy, could you close this one, please? It was resolved by another PR

**Comment by adelekennedy** [comment] 2023-09-21 23:58
I think just the reporting bonus is due in that case

**Comment by adelekennedy** [comment] 2023-09-25 07:34
asked in Slack

**Closed** 2023-09-28 09:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
