### ISSUE TITLE
[$500] Desktop - The back button doesn't work properly on a small screen (IOU report / Settings )

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27807] opened 2023-09-19 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Prerequisites: Must be performed on a small screen.
Scenario 1:
1. Open the desktop app and log in with any account
2. Open a standard report
3. Click on the back button to return to the reports list
4. Open an IOU report
5. Click on the back button

Scenario 2:
1. Open the desktop app and log in with any account
2. Open a standard report
3. Click on the back button to return to the reports list
4. Click on profile icon to navigate to ''Settings''
5. Click on any options under Settings tab
6. Click on the back button

## Expected Result:
By clicking the "Back" button we can return to LHN.

## Actual Result:
The back button doesn't work properly on a small screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**  1.3.71-7 

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/86463b6f-7cd4-4d5c-840c-50c40708faba

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01331d95a55317cf6a</li>
        <li>Upwork Job ID: 1704511936979427328</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-09-22 12:37
@lanitochka17 bump on @parasharrajat comment above.

**Comment by lanitochka17** [comment] 2023-09-24 00:43
This is correct when by pressing the “Back” button we can return to LHN.

**Comment by CortneyOfstad** [comment] 2023-09-25 13:58
No update yet 👍

**Comment by CortneyOfstad** [comment] 2023-09-26 14:26
Going to get engineering eyes on this internally first and then we can pull in CallStack if needed 👍

**Comment by Li357** [comment] 2023-09-29 05:30
Reproduced this with 1.3.73-1. Looking into it

**Comment by Li357** [comment] 2023-09-29 06:11
This is really bizarre. For some reason the onPress handler is not attached when we change screen size for just MoneyReportHeader. I don't think I have bandwidth to look into this further (some Wave 8 commits), @CortneyOfstad can we get CallStack on this?

**Comment by Li357** [comment] 2023-10-02 19:29
Bump @CortneyOfstad can we get CallStack assigned here?

**Comment by eVoloshchak** [comment] 2023-10-09 09:48
Not overdue, waiting for proposals

**Comment by MrMuzyk** [comment] 2023-10-09 11:29
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2023-10-09 11:31
@lanitochka17 

Hey, I've tried reproducing it on latest main and wasn't able to do that. It seems like the layout changed recently and issue is no longer present.

https://github.com/Expensify/App/assets/23487612/28ab2f2a-d05b-425b-9f21-7254178ca63d

**Comment by CortneyOfstad** [comment] 2023-10-09 12:08
Thanks @MrMuzyk! 

@eVoloshchak @lanitochka17 can you try and see if you can recreate the issue or if it is resolved?

**Comment by eVoloshchak** [comment] 2023-10-09 13:49
Can confirm it is resolved now, unable to reproduce this anymore

**Comment by lanitochka17** [comment] 2023-10-10 11:18
Hello Still repro on version 1.3.79-3

https://github.com/Expensify/App/assets/78819774/41888e54-2023-4013-9cb2-6b8a7e943fc0

**Comment by lanitochka17** [comment] 2023-10-10 20:02
Issue is not reproducible on the latest build 1.3.80-1

https://github.com/Expensify/App/assets/78819774/b0e68df9-7686-4ef1-8de7-db1fd7d950cf

**Comment by Li357** [comment] 2023-10-11 19:32
@lanitochka17 Interesting, are we good to close this out then?

**Comment by Li357** [comment] 2023-10-16 13:44
Closing this out since this isn't reproducible with new hybrid app nav

**Closed** 2023-10-16 13:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
