### ISSUE TITLE
[HOLD for payment 2023-11-2] Web - Chat - The 'Pay elsewhere' button goes to a wrong user

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24553] opened 2023-08-14 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with User A and User B.
2. User A requests $1 to User B. (Click on Request money in LHN > Type $1 > Click on Next button > Select User B and Click on Request button)
3. User B requests $2 to User A. (Click on Request money in LHN > Type $2 > Click on Next button > Select User A and Click on Request button)

## Expected Result:
The 'Pay elsewhere' button should be on User A. Because User A owes $1.

## Actual Result:
The 'Pay elsewhere' button is on User B.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856 

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/5cf48ad3-81e1-4e78-b8bd-ec60f940f0aa

https://github.com/Expensify/App/assets/115492554/24f16276-1df8-4c57-9b33-99cd952a5cea

https://github.com/Expensify/App/assets/115492554/22456974-d327-4795-a3a6-d22f86d14816

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @oleksandr-pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691167212288069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c1aabccf3e4cb7c</li>
        <li>Upwork Job ID: 1692299811733925888</li>
        <li>Last Price Increase: 2023-08-31</li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-08-15 18:07
I'm not able to reproduce it. The payment options, including Pay Elsewhere, show up on User A's account as expected. There are no payment options on User B's account.

<img width="1038" alt="Screenshot 2023-08-15 at 11 06 24" src="https://github.com/Expensify/App/assets/8292562/70e14c83-81ab-4756-895b-d6f48e683618">

**Comment by manancodes** [comment] 2023-08-17 09:57
> Hi @tjferriss The issue does not come with USD. Could you please check with another currency? I used it with UAH.

I used it with ₹ (INR) currency and I'm also able to reproduce this issue.

1. Log in with User A (Left Side) and User B (Right Side)
2. User A requests ₹100 to User B. 
3. User B requests ₹200 to User A. 

**Result :** ₹200 is added as -200, which should not happen. (See attached Image)

<img width="1680" alt="Screenshot 2023-08-17 at 3 22 56 PM" src="https://github.com/Expensify/App/assets/54790263/e5bcffbf-dbac-455d-bc22-603c9021fd49">

4. User B requests ₹200 again to User A. 

**Result :** ₹200 is added as 200, as Expected (See attached Image)

<img width="1680" alt="Screenshot 2023-08-17 at 3 26 45 PM" src="https://github.com/Expensify/App/assets/54790263/7ff86f15-2b5a-4336-a96a-5733d0652bca">

**Comment by manancodes** [comment] 2023-08-17 10:08
Contributor details
Your Expensify account email: manancodes.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014b1cb6b77f51931a

**Comment by tjferriss** [comment] 2023-08-17 22:18
Got it. I used a non-USD currency and I was able to reproduce.

**Comment by situchan** [comment] 2023-08-18 03:03
@tjferriss I think you forgot to re-open the issue

**Comment by tjferriss** [comment] 2023-08-18 20:28
@srikarparsi can you take a look at this one and help us determine whether it's something we'll need to fix in the backend?

**Comment by srikarparsi** [comment] 2023-08-22 03:45
sorry got swamped today but will prioritize tomorrow

**Comment by tjferriss** [comment] 2023-08-24 16:40
@Skalakid have you been able to take a look at this one?

**Comment by Skalakid** [comment] 2023-08-28 08:20
@tjferriss I'm not sure if you didn't mean to tag @srikarparsi instead of me 😅

**Comment by Skalakid** [comment] 2023-08-28 09:02
However, I agree with @b4s36t4 that there can be a problem with updating `managerID`

**Comment by mountiny** [comment] 2023-08-31 11:22
Yeah i can take this issue on if you prefer.

Basically there is more to be done with transactions too, it is designed weirdly, the manager should change and all the signs of the amounts of transactions should swap.

Thats how it is in backend

**Comment by srikarparsi** [comment] 2023-09-01 04:24
Hey yeah that would be great @mountiny, reassigning to you.

**Comment by mountiny** [comment] 2023-09-01 17:31
Making this internal

**Comment by mountiny** [comment] 2023-09-04 10:36
Stil lhavent got around to this

**Comment by mountiny** [comment] 2023-09-07 17:12
This should help with it but we still need ot be updating the manager optimistically when editing https://github.com/Expensify/App/pull/25498

**Comment by mountiny** [comment] 2023-09-11 08:49
Will be fixed soonish

**Comment by mountiny** [comment] 2023-09-14 06:06
still waiting, I think we can make this one weekly

**Comment by mountiny** [comment] 2023-09-21 03:06
focusing on wave 6

**Comment by mountiny** [comment] 2023-10-03 23:22
@oleksandr-pantsyr @situchan Could you please retest on latest main? I think this should be fixed

**Comment by mountiny** [comment] 2023-10-16 14:13
I cannot reproduce this, I think we have fixed it @oleksandr-pantsyr @izarutskaya @kavimuru @situchan 

https://github.com/Expensify/App/assets/36083550/32d98247-a56b-4e17-975d-412d8f35e4b6

**Comment by mountiny** [comment] 2023-10-16 14:14
Can you confirm. @tjferriss could you retest too?

**Comment by mountiny** [comment] 2023-10-17 14:13
Ok so it has to be with different currencies, I think I found the bug and raising a pr with a fix

**Comment by tjferriss** [comment] 2023-10-30 04:46
PR is under review

**Comment by mountiny** [comment] 2023-10-30 09:38
This has been resolved @oleksandrpantsyr could you please retest and if its fixed we can pay out the reporting bonus, thanks!

**Comment by mountiny** [comment] 2023-11-01 12:13
@tjferriss Perfect, could we please pay out @oleksandrpantsyr for reporting this bug? This was before teh changes I believe so $250 thanks!

**Comment by tjferriss** [comment] 2023-11-08 22:16
Sorry for the delay. The offer has been sent via Upworks https://www.upwork.com/nx/wm/offer/27583868

**Comment by tjferriss** [comment] 2023-11-13 22:19
The payment has been made to @oleksandr-pantsyr via Upworks.

**Closed by tjferriss** 2023-11-13 22:19 UTC
Labels: Engineering, Daily, Internal, Overdue, Awaiting Payment, Bug
