### ISSUE TITLE
[$500] Infinite loading when accessing a non-existing workspace

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36442] opened 2024-02-13 22:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707848696684749

## Action Performed:

1. Log out
2. Go to some WS link, e.g. https://staging.new.expensify.com/workspace/adsasddssad/rateandunit (doesn't matter if policy exist or not)
3. Log in

## Expected Result:
Shouldn't be infinite loading
## Actual Result:
Infinite loading appears
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-02-13 at 5 07 35 PM](https://github.com/Expensify/App/assets/38435837/afcc62ae-f99e-4855-be19-163d681fbf40)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019c756122ca1f4027</li>
        <li>Upwork Job ID: 1757527427083399168</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @fedirjh</details>

**Comment by jeremy-croff** [comment] 2024-02-13 22:39
Able to reproduce on staging, but not latest main branch

**Comment by kosmydel** [comment] 2024-02-14 11:59
> the issue is not reproducible on the latest main.

I can still reproduce it.

**Comment by hayata-suenaga** [comment] 2024-02-14 17:14
I can also still reproduce this

**Comment by bernhardoj** [comment] 2024-02-14 18:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we open a nonexistent workspace page after login, the app will load indefinitely.

### What is the root cause of that problem?
When we open a nonexistent workspace page after login, the OpenApp request is never called. It will only be called if `isReadyToOpenApp` promise is resolved.
https://github.com/Expensify/App/blob/574157eb23a0c5f8ffbc101091848e3c35a88015/src/libs/actions/App.ts#L151

`App.confirmReadyToOpenApp` is used to resolve the promise and it currently is called in both ReportScreenIDSetter and SidebarLinks. When we open the workspace page after login, the report screen isn't added to the navigation stack, so `App.confirmReadyToOpenApp` is never called in ReportScreenIDSetter.

In SidebarLinks, `App.confirmReadyToOpenApp` is called only on small screen.
https://github.com/Expensify/App/blob/b0b651b4184230aa6b29af21af1430c5741aed95/src/pages/home/sidebar/SidebarLinks.js#L54-L59

Because the promise isn't resolved, the app shows the loading indicator infinitely.

### What changes do you think we should make in order to solve the problem?

SidebarLinks is placed inside the bottom tab navigator which is always exist in the nav stack, so I think we can just have one place to call `App.confirmReadyToOpenApp` inside SidebarLinks. So, we can just remove the small screen condition.
https://github.com/Expensify/App/blob/b0b651b4184230aa6b29af21af1430c5741aed95/src/pages/home/sidebar/SidebarLinks.js#L54-L59

**Comment by bernhardoj** [comment] 2024-02-15 03:58
`ReportScreenIDSetter` will be mounted alongside `ReportScreen`.
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/libs/Navigation/AppNavigator/ReportScreenWrapper.tsx#L13-L25

If you are aware, before the ideal nav, in CustomRouter, we have a logic to make sure the report screen (specifically CentralPaneNavigator) is always added to the nav stack on large screen. (old code below)
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.js#L71-L72

CentralPaneNavigator now includes workspace screen (overview, reimburse, etc.).
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/libs/Navigation/AppNavigator/Navigators/CentralPaneNavigator/BaseCentralPaneNavigator.tsx#L36-L53

The new CustomRouter logic now making sure to add a full screen or central pane navigator to the nav stack
https://github.com/Expensify/App/blob/634f7666b049aced9f6ac2ae5565508ec07d813e/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L54-L84

In this case, visiting `/workspace/{policyID}/rateandunit` adds WorkspaceReimburse (belongs to CentralPaneNavigator) to the stack

**Comment by bernhardoj** [comment] 2024-02-20 09:48
PR is ready

cc: @fedirjh

**Comment by slafortune** [comment] 2024-02-29 21:30
@fedirjh can you review this?

**Comment by slafortune** [comment] 2024-02-29 21:32
Looks like the automated system didn't update.  Deployed to production on Feb 28 - 7 holding day means payment would be due on March 6th

**Comment by blimpich** [comment] 2024-03-15 21:55
@slafortune can you handle payment here?

**Comment by slafortune** [comment] 2024-03-18 16:31
Sorry I lost sight of this one!  PAID!

@fedirjh can you please complete the checklist?

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@fedirjh] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@fedirjh] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@fedirjh] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@fedirjh] Determine if we should create a regression test for this bug.
- [ ] [@fedirjh] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@slafortune] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by slafortune** [comment] 2024-03-22 13:08
Thanks @fedirjh !

**Closed by slafortune** 2024-03-22 13:08 UTC
Labels: External, Daily, Overdue, Bug
