### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] mWeb Safari - When go from Get Assistance Page to Settings Workspace 'Save' button glitches 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28020] opened 2023-09-22 14:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On [https://staging.new.expensify.com,](https://staging.new.expensify.com%2C/) Go to specific workspace
2. Go to Settings and Click '?' icon
3. On Get assistance page, click back to go to Workspace Settings page again
## Expected Result:
Save button should not change its position and no glitches
## Actual Result:
Save button glitches and jumps from the position
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5e1110d2-8919-4fa8-baa0-0f3de2519cee

**Expensify/Expensify Issue URL:**
**Issue reported by:** @studentofcoding
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695017796209329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e33d6085e621ef7</li>
        <li>Upwork Job ID: 1705229752570806272</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26873219</li>
<li>studentofcoding | Contributor | 26873221</li>
<li>studentofcoding | Reporter | 26873222</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-09-22 14:37
# Proposal from @studentofcoding
## Please re-state the problem that we are trying to solve in this issue
When go from Get Assistance Page to Settings Workspace ‘Save’ button are going up and down
## What is the root cause of that problem?
We still haven’t managed/get-assistance/* URL structure into our apple-app-site-association file, therefore the Smart App Banner on Workspace Settings Page are make the ‘Save’ Button going up and down
## What changes do you think we should make in order to solve the problem?
Add /get-assistance/* into apple-app-site-association like below:
{
    "applinks": {
        "details": [
            {
                "appIDs": ["368M544MTT.com.chat.expensify.chat"],
                "components": [
                    //...
                    {
                        "/": "/get-assistance/*",
                        "comment": "Get Assistance Pages"
                    }
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": ["368M544MTT.com.chat.expensify.chat"]
    }
}
## What alternative solutions did you explore? (Optional)
None
## Result

**Comment by studentofcoding** [comment] 2023-09-23 08:20
# Proposal

Reformated the [Above Proposal](https://github.com/Expensify/App/issues/28020#issuecomment-1731536168) that sended by myself [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695018189375659?thread_ts=1695017796.209329&cid=C049HHMV9SM)

## Please re-state the problem that we are trying to solve in this issue
When go from Get Assistance Page to Settings Workspace ‘Save’ button glitches

## What is the root cause of that problem?
We still haven’t managed `/get-assistance/*`  URL structure into our apple-app-site-association file, therefore the Smart App Banner on Workspace Settings Page makes the ‘Save’ Button glitches

## What changes do you think we should make in order to solve the problem?
Add `/get-assistance/*` into `apple-app-site-association` like below:
```
{
    "applinks": {
        "details": [
            {
                "appIDs": ["368M544MTT.com.chat.expensify.chat"],
                "components": [
                    //...
                    {
                        "/": "/get-assistance/*",
                        "comment": "Get Assistance Pages"
                    }
                ]
            }
        ]
    },
    "webcredentials": {
        "apps": ["368M544MTT.com.chat.expensify.chat"]
    }
}
```

## What alternative solutions did you explore? (Optional)
None

@mallenexpensify @jjcoffee @lschurr

**Comment by lschurr** [comment] 2023-09-25 04:03
@jjcoffee - could you review these proposals?

**Comment by jjcoffee** [comment] 2023-09-25 14:30
@studentofcoding's proposal LGTM! The RCA seems correct (although I'd be curious to know why the button jiggles in the first place, I assume this may just be a limitation of the way the smart app banner is inserted though) and the solution is fine (we just missed a case - I also see a similar issue was [fixed](https://github.com/Expensify/App/pull/26172) the same way a few weeks ago).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by studentofcoding** [comment] 2023-09-25 21:48
> @studentofcoding's proposal LGTM! The RCA seems correct (although I'd be curious to know why the button jiggles in the first place, I assume this may just be a limitation of the way the smart app banner is inserted though) and the solution is fine (we just missed a case - I also see a similar issue was [fixed](https://github.com/Expensify/App/pull/26172) the same way a few weeks ago).
> 
> 
> 
> :ribbon::eyes::ribbon: C+ reviewed

Thanks @jjcoffee!, I've added the details on why the button jiggles, and yes the solution are similar to recent fix

**Comment by studentofcoding** [comment] 2023-09-26 05:53
The PR is opened @jjcoffee @tgolen!

For some context on testing, the Smart App Banner is only shown after the updated `well-known/apple-app-site-association` is deployed to the Staging/Production like we have [here on staging](https://staging.new.expensify.com/apple-app-site-association) or [here on production](https://new.expensify.com/apple-app-site-association)

**Comment by studentofcoding** [comment] 2023-10-03 01:43
It's working on both Staging and Production

https://github.com/Expensify/App/assets/20473526/fc65142d-4fa7-4f23-a6aa-f7424cb7eacb

Note: don't forget to update the New Dot App and remove cache on safari

**Comment by studentofcoding** [comment] 2023-10-09 15:22
Please kindly proceed the payment @lschurr @jjcoffee, thanks!

**Comment by lschurr** [comment] 2023-10-09 17:17
Payment summary:

- Bug reporter: @studentofcoding $50
- Contributor: @studentofcoding $750
- Contributor+: @jjcoffee $750

**Comment by lschurr** [comment] 2023-10-09 17:20
All payments made in Upwork. Closing!

**Closed by lschurr** 2023-10-09 17:20 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by studentofcoding** [comment] 2023-10-09 17:25
> All payments made in Upwork. Closing!

Thanks @lschurr!
