### ISSUE TITLE
iOS - Conversation - If the last message is deleted, the previous one becomes partially hidden

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10765] opened 2022-09-01 22:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App and login with any account
2. Go to any conversation
3. Send 2 or more messages
4. Delete the latest message

## Expected Result:
The previous message should not be hidden

## Actual Result:
The previous message becomes partially hidden

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188025493-15d3a984-ccec-4e20-8706-7deae4c33626.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-09-05 09:07
@JmillsExpensify let me know when you post the job. Description is clear and it is reproducible

**Comment by JmillsExpensify** [comment] 2022-09-05 09:23
Upwork job is here: https://www.upwork.com/jobs/~012e25f97da880eedd. We're open for proposals.

**Comment by JmillsExpensify** [comment] 2022-09-07 10:18
Still open for proposals.

**Comment by JmillsExpensify** [comment] 2022-09-12 19:03
Bumping this to $500 to encourage proposals.

**Comment by ctkochan22** [comment] 2022-09-21 06:50
Not overdue, waiting proposals

**Comment by Santhosh-Sellavel** [comment] 2022-09-21 19:25
@kbecciv is this reproducible now? 

I am unable to reproduce this issue

**Comment by advaitasol9** [comment] 2022-09-22 05:24
**Proposal:**

Changing "contentContainerStyle" of InvertedFlatList in [ReportActionsList.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.js) as follows fixes the issue.
<img width="786" alt="Screenshot 2022-09-22 at 9 57 37 AM" src="https://user-images.githubusercontent.com/93445984/191658483-6b617319-b6bb-48b0-ae59-14f759c34e25.png">

The issue arrived because the padding between InvertedFlatList and TextInputContainer was reduced to 0 (as visible in above image) to accommodate Recipient's Local Time. Which wasn't the correct change as the padding in absence of Recipient's Local Time is 16,
https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/styles/styles.js#L1268-L1272
so counting marginTop = 5 of  Recipient's Local Time's View Container,
https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/pages/home/report/ParticipantLocalTime.js#L63
https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/styles/styles.js#L643-L647
the correct padding should be 11 and pt3 is the closest to that.

Before:
https://user-images.githubusercontent.com/93445984/191662026-7189564b-380d-462e-b55e-bc6661aabc7b.mp4

After:
https://user-images.githubusercontent.com/93445984/191663285-2d90fb36-4129-4bcb-97e2-ab56956aadc6.mp4

**Comment by advaitasol9** [comment] 2022-09-22 05:26
Hey @Santhosh-Sellavel you can reproduce the issue by following the steps below:
1. Send multiple messages.
2. Keep the textinput focused, so that keyboard stays open.
3. Delete the last message.

**Comment by kbecciv** [comment] 2022-09-22 15:02
@Santhosh-Sellavel Checking with team, will update you shortly

**Comment by kbecciv** [comment] 2022-09-22 15:22
@Santhosh-Sellavel Issue is still reproducible.

https://user-images.githubusercontent.com/93399543/191787415-178d6a23-1583-412f-be6e-31300d04a8a4.MP4

**Comment by Santhosh-Sellavel** [comment] 2022-09-22 15:53
> @Santhosh-Sellavel Issue is still reproducible.
> 
>  RPReplay_Final1663859877.MP4

@kbecciv this looks likely from an simulator is this reproducible on any real device

**Comment by kbecciv** [comment] 2022-09-22 15:57
No, this is real device.

**Comment by advaitasol9** [comment] 2022-09-26 15:28
Hi, @JmillsExpensify @ctkochan22 @Santhosh-Sellavel @kbecciv can you take a look at my proposal?

**Comment by Santhosh-Sellavel** [comment] 2022-09-26 16:04
Will have a look @advaitasol9, thanks for the bump!

**Comment by mvtglobally** [comment] 2022-09-27 05:13
Issue not reproducible during KI retests. (First week)

**Comment by Santhosh-Sellavel** [comment] 2022-09-27 11:59
@advaitasol9 is this issue reproducible for you on staging/ latest main.

**Comment by advaitasol9** [comment] 2022-09-27 12:09
> Hey @Santhosh-Sellavel you can reproduce the issue by following the steps below:
> 
> 1. Send multiple messages.
> 2. Keep the textinput focused, so that keyboard stays open.
> 3. Delete the last message.

Yes @Santhosh-Sellavel, below is a video from few days ago while I was testing on main branch. In my testing I found the issue is only happening when we delete the message while the keyboard is open.

https://user-images.githubusercontent.com/93445984/192520952-a0c19e92-d477-4de2-8cb5-38bb3c5c1625.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-09-27 12:13
> Yes @Santhosh-Sellavel, below is a video from few days ago while I was testing on main branch. In my testing I found the issue is only happening when we delete the message while the keyboard is open.

@advaitasol9 Can you check now on staging build or latest main

**Comment by advaitasol9** [comment] 2022-09-27 12:14
Sure @Santhosh-Sellavel , will get back to you.

**Comment by advaitasol9** [comment] 2022-09-27 19:41
@Santhosh-Sellavel I am able to reproduce on latest main.

**Comment by ctkochan22** [comment] 2022-09-29 19:39
@JmillsExpensify @advaitasol9 's proposal looks good.

**Comment by Santhosh-Sellavel** [comment] 2022-09-29 19:48
> @JmillsExpensify @advaitasol9 's proposal looks good.

@ctkochan22 for the quick review, if possible can you wait one more day?
I'm investigating this & other related issues.

Thanks!

**Comment by Santhosh-Sellavel** [comment] 2022-09-30 18:12
@advaitasol9 

> The issue arrived because the padding between InvertedFlatList and TextInputContainer was reduced to 0 (as visible in the above image) 

Do you think this was a regression, when was it reduced?

**Comment by advaitasol9** [comment] 2022-10-03 04:46
Sorry @Santhosh-Sellavel , I meant to say the padding right now is set to 0 which needs to be 12.

**Comment by ctkochan22** [comment] 2022-10-03 07:08
@Santhosh-Sellavel Sorry hat other related issues are you investigating?

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 17:02
@ctkochan22 Yeah, I'm C+ there too this might be related to this [issue](https://github.com/Expensify/App/issues/10283) as the scroll position is not correct for the last item in both issues but on different use cases.

**Comment by JmillsExpensify** [comment] 2022-10-03 17:34
I like trying to fix the scroll position issues more holistically, though perhaps for clarity, is it only happening for the delete case and pay?

**Comment by Santhosh-Sellavel** [comment] 2022-10-03 17:39
> I like trying to fix the scroll position issues more holistically

Yeah, exactly

**Comment by neil-marcellini** [comment] 2022-10-04 00:27
I don't think #10283 is related to this since I believe the root cause there is about the content changing size and here the chats do not change size. I think @advaitasol9 might be on the right track.

**Comment by JmillsExpensify** [comment] 2022-10-04 23:00
Ok cool. Thanks for your patience @advaitasol9. For the sake of clarity, what is the formal proposal?

**Comment by advaitasol9** [comment] 2022-10-05 13:23
> **Proposal:**
> 
> Changing "contentContainerStyle" of InvertedFlatList in [ReportActionsList.js](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsList.js) as follows fixes the issue. <img alt="Screenshot 2022-09-22 at 9 57 37 AM" width="786" src="https://user-images.githubusercontent.com/93445984/191658483-6b617319-b6bb-48b0-ae59-14f759c34e25.png">
> 
> The issue arrived because the padding between InvertedFlatList and TextInputContainer was reduced to 0 (as visible in above image) to accommodate Recipient's Local Time. Which wasn't the correct change as the padding in absence of Recipient's Local Time is 16,
> 
> https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/styles/styles.js#L1268-L1272
> 
> 
> so counting marginTop = 5 of Recipient's Local Time's View Container,
> https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/pages/home/report/ParticipantLocalTime.js#L63
> 
> 
> https://github.com/Expensify/App/blob/a24de554bd2e70575f4389942d6132d7ca9ea082/src/styles/styles.js#L643-L647
> 
> 
> the correct padding should be 11 and pt3 is the closest to that.
> Before: https://user-images.githubusercontent.com/93445984/191662026-7189564b-380d-462e-b55e-bc6661aabc7b.mp4
> 
> After: https://user-images.githubusercontent.com/93445984/191663285-2d90fb36-4129-4bcb-97e2-ab56956aadc6.mp4

here's the proposal @JmillsExpensify.

**Comment by JmillsExpensify** [comment] 2022-10-05 13:38
@neil-marcellini @Santhosh-Sellavel Are both of you cool with this proposal? I'd love to keep things moving forward! 🙌🏼

**Comment by neil-marcellini** [comment] 2022-10-05 16:17
I'll leave it up to CME @ctkochan22, I was commenting from another linked issue.

**Comment by JmillsExpensify** [comment] 2022-10-05 23:05
Oh shoot. Good catch. @ctkochan22 can you chime in here so that we can keep this one moving?

**Comment by ctkochan22** [comment] 2022-10-07 04:38
I agree with @neil-marcellini here. I don't think the two are not related. I'm good with the proposal, lets move forward

**Comment by JmillsExpensify** [comment] 2022-10-10 03:57
Cool. I'll add @advaitasol9 to the issue. Can you also make sure to the [Upwork job](https://www.upwork.com/jobs/~012e25f97da880eedd) as well please? cc @Santhosh-Sellavel

**Comment by advaitasol9** [comment] 2022-10-10 07:41
Hi @JmillsExpensify , i've applied on upwork. I'll create a PR by 12 october.

**Comment by JmillsExpensify** [comment] 2022-10-14 03:22
Awesome, thank you! @Santhosh-Sellavel just waiting on you to apply.

**Comment by JmillsExpensify** [comment] 2022-10-17 14:56
@Santhosh-Sellavel Reminder to apply to the Upwork job when you have a chance.

**Comment by Santhosh-Sellavel** [comment] 2022-10-17 18:03
Done thanks @JmillsExpensify

**Comment by mvtglobally** [comment] 2022-10-24 18:31
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2022-10-26 17:00
Asked for an update in the linked PR.

**Comment by JmillsExpensify** [comment] 2022-11-01 18:23
@Santhosh-Sellavel When you have a second, do you mind circling back and reviewing the linked PR? @ctkochan22 this one is ready for you as well!

**Comment by mvtglobally** [comment] 2022-11-03 03:01
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2022-11-06 20:26
@ctkochan22 Can you please jump in to review the linked PR? @Santhosh-Sellavel and @advaitasol9 have a question there so this PR can get merged.

**Comment by JmillsExpensify** [comment] 2022-11-08 19:53
Still awaiting @ctkochan22's review in the linked PR.

**Comment by mvtglobally** [comment] 2022-11-09 03:28
Issue not reproducible during KI retests. (Third week)

**Comment by ctkochan22** [comment] 2022-11-09 04:22
Yikes, sorry. Slipped through the cracks looking now

**Comment by JmillsExpensify** [comment] 2022-11-10 04:53
Thanks! Also let's get real. I just tested this issue, and like Applause, I can't reproduce any longer. @Santhosh-Sellavel @advaitasol9 can either of you?

**Comment by Santhosh-Sellavel** [comment] 2022-11-12 01:39
@advaitasol9 bump!

**Comment by advaitasol9** [comment] 2022-11-12 11:45
let me check @Santhosh-Sellavel.

**Comment by advaitasol9** [comment] 2022-11-13 13:52
@JmillsExpensify @ctkochan22 @Santhosh-Sellavel 
I am still able to reproduce this issue, attaching a video [here](https://drive.google.com/file/d/1jjmrzCzrgIRHJ7PBG2cEnjkyyaNRBet7/view?usp=share_link) (with latest main branch). 
Important: steps to reproduce.
1. Open a chat where recipient is from a different timezone (so that recipient timezone is visible just above chat input).
2. Use an ios simulator with mac's 'Connect Hardware Keyboard' disabled, so that keyboard is visible.
3. Keep keyboard open while deleting messages as seen in video.
4. The issue occurs randomly, i was unable to detect any pattern. So best way to reproduce is to send multiple messages (5-6) and keep deleting the last message until you observe the issue.

I hope this helps you to reproduce the issue.

**Comment by Santhosh-Sellavel** [comment] 2022-11-13 15:17
I'm trying the same but am unable to reproduce it.

@kbecciv Can you check with the above steps?

**Comment by Santhosh-Sellavel** [comment] 2022-11-14 15:20
@kbecciv Please check on regular devices that would be enough, if it occurs only simulator we can ignore that!

**Comment by JmillsExpensify** [comment] 2022-11-14 18:36
I agree with that. While I do think it's helpful to find and fix issues in the simulator, I think for now we have so many bugs in production we should be focused on fixing those.

**Comment by kbecciv** [comment] 2022-11-15 14:53
Issue is no longer reproduced with build 1.2.27.4

https://user-images.githubusercontent.com/93399543/201950211-3022a20d-a004-4d6c-a5d3-20baf9ab47d7.MP4

**Comment by JmillsExpensify** [comment] 2022-11-15 17:26
Ok with that in mind, I think we should close this issue and pay out C and C+ for their time/work.

**Comment by JmillsExpensify** [comment] 2022-11-15 17:27
That said, an additional consideration is this: What do we want to do with @advaitasol9's PR? Do nothing? cc @Santhosh-Sellavel @ctkochan22 let's make sure we're on the same page for next steps.

**Comment by ctkochan22** [comment] 2022-11-16 03:37
@advaitasol9 Bump to my question in the PR https://github.com/Expensify/App/pull/11752#issuecomment-1308201478

If you can help us reproduce it, it'll get the PR moving forward. Otherwise, I think we should close the issue and the PR

**Comment by Santhosh-Sellavel** [comment] 2022-11-16 03:52
@ctkochan22 Please follow the thread from [here](https://github.com/Expensify/App/issues/10765#issuecomment-1309772523), we are unable to reproduce. [Here](https://github.com/Expensify/App/issues/10765#issuecomment-1312736271) are the steps given by @advaitasol9, but still no luck for us, please give it a try, thanks!

**Comment by ctkochan22** [comment] 2022-11-16 05:04
@Santhosh-Sellavel thanks for clarifying. I'm still unable to reproduce. I'm not sure why. 

Even so, the padding normal 4 out of 5 times. Why is it not normal the 5th time? [This PR](https://github.com/Expensify/App/pull/11752/files) is not a fix. It just covers up the actual bug.

**Comment by JmillsExpensify** [comment] 2022-11-17 05:43
@ctkochan22 Thoughts on that last comment?

**Comment by ctkochan22** [comment] 2022-11-21 07:06
Okay so this only happens to users when the recipient time is visible?

What causes the message to be hidden? And why doesn't it do it every time?

**Comment by advaitasol9** [comment] 2022-11-21 16:27
@ctkochan22 the way it happens only on ios when keyboard is open, my guess is it should be an issue internally with Flatlist.

**Comment by ctkochan22** [comment] 2022-11-22 06:50
Okay, so it sounds like we should bring this internal and fix it at the root. I'll try and take a look this week

**Comment by JmillsExpensify** [comment] 2022-11-22 07:20
Thanks so much! Heads up @ctkochan22, we may be deprecating FlatList for WishList in the near future, though it's still probably too early with the later to definitely say we should close this issue.

**Comment by mvtglobally** [comment] 2022-11-22 20:44
Issue not reproducible during KI retests. (Fifth week)

**Comment by advaitasol9** [comment] 2022-11-25 04:54
Hi @JmillsExpensify, what'd be the next steps for me. If anything is required I'm here to help. If not, can we move forward to payment?

**Comment by ctkochan22** [comment] 2022-11-25 20:49
@advaitasol9 I believe you need to be hired and your proposal to be accepted and merged.

**Comment by advaitasol9** [comment] 2022-11-26 04:04
I know @ctkochan22, I was hired and my proposal was accepted. Based on my pr I feel this issue is being taken internal.
This is a unusual situation, that's why I am asking what would be next steps.

**Comment by JmillsExpensify** [comment] 2022-11-26 15:36
@advaitasol9 To clarify my earlier comment, I was saying that we should still resolve this issue despite us looking into FlatList alternatives longer-term. Further, I wanted to re-assure you that if we do take this internal, you will be compensated for whatever work you've done to date.

@ctkochan22 If we are taking this issue internal, as [you mention here](https://github.com/Expensify/App/issues/10765#issuecomment-1323193556), are you leading this up? It'd be good to get clarify on next steps.

**Comment by ctkochan22** [comment] 2022-11-28 23:25
It was accepted, but after reviewing the PR, I think we agreed that the root issue is not being fixed. 

We need to address _why_ its making that jump. So I think the PR and previously accepted proposal is no longer valid

**Comment by JmillsExpensify** [comment] 2022-11-29 06:43
Ok gotcha. I think that's on us then and we owe the contributor for making that mistake. We probably need to take the discussion about the detailed solution to slack. Can you take that on?

**Comment by ctkochan22** [comment] 2022-11-29 06:49
Ah, thats good to know, sorry about the confusion @advaitasol9 !

Yeah I can take this on

**Comment by JmillsExpensify** [comment] 2022-11-29 16:48
Ok cool. @advaitasol9 I've unassigned you from this issue and issued payment via Upwork. @Santhosh-Sellavel I think in your case you'll be needed still on the PR review, so I've hired you as is in the Upwork job and we can settle up after this PR gets merged.

**Comment by Santhosh-Sellavel** [comment] 2022-11-29 16:57
@ctkochan22 Let me know when PR is up, thanks!

**Comment by JmillsExpensify** [comment] 2022-12-01 06:19
@ctkochan22 I think you're out for a personal issue, though please update us on the PR when you return. Thanks!

**Comment by JmillsExpensify** [comment] 2022-12-05 14:14
@ctkochan22 Can you circle back today and update us on the PR status?

**Comment by JmillsExpensify** [comment] 2022-12-07 21:48
Discussing [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1670448763112419) as well.

**Comment by JmillsExpensify** [comment] 2022-12-08 18:03
I'm going to unassign Chris, as he's OOO. Going to work on finding a volunteer!

**Comment by JmillsExpensify** [comment] 2022-12-08 19:00
Posted [in Slack](https://expensify.slack.com/archives/CC7NECV4L/p1670525972569329?thread_ts=1670372833.921059&cid=CC7NECV4L)!

**Comment by bondydaa** [comment] 2022-12-08 23:53
I'm a little confused, it seems like this wasn't reproducible anymore? Or was it that it isn't consistently reproducible? 

looks like https://github.com/Expensify/App/pull/11752 was closed and looks like we paid out the PR author. 

I'll run some tests to see if I can reproduce it at all but if I can't we should just close right?

**Comment by JmillsExpensify** [comment] 2022-12-09 03:47
Actually that's interesting! I can't reproduce this either anymore. Awesome to have a fresh set of eyes. Let's go ahead and close this one out.

**Closed by JmillsExpensify** 2022-12-09 03:47 UTC
Labels: Engineering, Weekly, Improvement, Internal, Bug

**Comment by JmillsExpensify** [comment] 2022-12-09 03:50
Also @Santhosh-Sellavel you are settled up. 🙌🏼
