### ISSUE TITLE
Android - Payments - app crashed after make default payment  

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11497] opened 2022-10-01 03:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Add payments into your account
1. Launch the app
2. Log in with your account
3. Go to Setting - Payments
4. Select on of your bank account
5. Tap Make default payment method
6. Put your password
7. Tap Make default payment method

## Expected Result:
Selected account added as Default payment

## Actual Result:
App crashed when making default payment

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.11.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

https://user-images.githubusercontent.com/93399543/193384145-608785c0-f940-46f7-8a0c-2c65499c535c.mp4

[log1.txt](https://github.com/Expensify/App/files/9689418/log1.txt)

**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-10-03 22:08
I'm not able to reproduce the crash in staging, but I can see an error in the console that may be related:

![image](https://user-images.githubusercontent.com/87341702/193694698-e71d43e2-4466-403a-a0f7-7dd18bfccdee.png)

**Comment by aldo-expensify** [comment] 2022-10-03 22:10
Tested with aldo@expensifail.com and with [applausetester+0901abb@applause.expensifail.com](mailto:applausetester+0901abb@applause.expensifail.com)/Feya86Katya and got the same results... no crash, but the error in the console. There is also no feedback on if the change was applied or not

**Comment by aldo-expensify** [comment] 2022-10-03 22:11
The error is happening around here:

![image](https://user-images.githubusercontent.com/87341702/193695191-d1cf1516-6842-4e60-89da-7928b281535e.png)

**Comment by aldo-expensify** [comment] 2022-10-03 22:16
cc @Justicea83 as this may have happen because of this change: https://github.com/Expensify/App/pull/10447

**Comment by Justicea83** [comment] 2022-10-04 07:05
Closing this issue in favor of [this](https://github.com/Expensify/App/issues/11454).

**Closed by Justicea83** 2022-10-04 07:05 UTC
Labels: Engineering, Daily

**Comment by aldo-expensify** [comment] 2022-10-06 18:21
@Justicea83 it is not obvious to me how this issue is connected/related/similar to https://github.com/Expensify/App/issues/11454, can you explain :)? otherwise I think we should reopen this.

**Comment by Justicea83** [comment] 2022-10-06 18:57
I think I linked the wrong issue. [This](https://github.com/Expensify/App/issues/11496) is it.
