### ISSUE TITLE
 IOU - No action trigger when press enter when tab index focusing a original conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44548] opened 2024-06-27 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** crowdtest.expensify+test002@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Access any IOU
2. Click on the header
3. Press `Tab` key twice to Tab index focusing on the original conversation title
4. Press `Enter` key

## Expected Result:
Action trigger when press enter when tab index focusing a original conversation

## Actual Result:
No action triggers when the user presses enter when a tab index focusing the original conversation title, When the user clicks on any element of the title, such as the word "from" that isn't a link, it also navigates to the origin chat, so when I focus on the original chat title, Otherwise, other index locations, for example, "Pin", "Share" are trigger event when pressing enter when it has focus.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d6fe5e95-4886-4ad9-aa7c-80c71566b6a1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-06-27 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing enter on a parent navigation subtitle doesn't do anything.

### What is the root cause of that problem?
The parent navigation subtitle is a pressable with a role of link.
https://github.com/Expensify/App/blob/9d88c63c6a7adcc73a6ec242aeb47505109f45d5/src/components/ParentNavigationSubtitle.tsx#L39-L51

Based on this [rn-web issue](https://github.com/necolas/react-native-web/issues/2270#issuecomment-1093575195), if we use "link" as a role, we also need to pass the `href`.

### What changes do you think we should make in order to solve the problem?

There are a few usages of role link on the apps, we need to either pass the href for each one or remove the link role if needed, but in the specific case of parent navigation, we can remove the role because we want to rely on the onPress logic instead of the href (we don't want to render it as <a>).

**Comment by OfstadC** [comment] 2024-06-28 18:26
I'm not super sure what's happening here. So having trouble reproducing.

**Comment by OfstadC** [comment] 2024-07-01 16:08
Digging into this more today

**Comment by OfstadC** [comment] 2024-07-02 21:03
Chatted with Anu - Closing this out as it's not a priority

**Closed by OfstadC** 2024-07-02 21:03 UTC
Labels: Daily, Bug
