### ISSUE TITLE
[$1000] removed member is not shown on the invite list in offline mode

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18808] opened 2023-05-12 02:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to web chrome
2. Go to any workspace
3. Go to invite members
4. Select any member, invite them and remove them from the list
5. Click on invite again and notice that after you've removed the member , it shows the removed member on the list that can be added again (works fine)
6. But now turn off your wifi
7. Again follow the same steps as above, invite a member and remove it from the list
8. Click on invite button and notice that the removed member is not shown on the list even when it was deleted (This causes a problem in case if we accidentally delete a member in offline mode, we won't be able to add them again in offline)

## Expected Result:
The removed member should be shown on the invite list in offline mode in a similar way how it works online
## Actual Result:
The removed member is not shown on the invite list in offline mode (works well if added and removed the member online)
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a838a47c-89f1-4e41-b984-89e5118a954b

https://github.com/Expensify/App/assets/43996225/7cb66e9a-4630-4215-a2a7-08e6b7a9a8f5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683778783773059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019db1d178d1140752</li>
        <li>Upwork Job ID: 1658036119202902016</li>
        <li>Last Price Increase: 2023-05-15</li>
    </ul>
</details>

**Comment by dukenv0307** [comment] 2023-05-13 03:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
removed member is not shown on the invite list in offline mode

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspaceInvitePage.js#L110-L120

If the user is offline, all policy member lists will be excluded in WorkspaceInvitePage
### What changes do you think we should make in order to solve the problem?
We should remove this condition: 
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/workspace/WorkspaceInvitePage.js#L115

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2023-05-15 09:04
@dukenv0307 please see https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job

**Comment by dukenv0307** [comment] 2023-05-15 09:11
Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

**Comment by laurenreidexpensify** [comment] 2023-05-17 08:59
@Santhosh-Sellavel bump for review ^^

**Comment by Santhosh-Sellavel** [comment] 2023-05-17 13:24
Sorry this missed out on the list. Will check today!

**Comment by Santhosh-Sellavel** [comment] 2023-05-17 20:14
@AndrewGable Not sure this is something worth addressing, it makes sense not to show it in the invite list as we can see the user delete pending on the manage members page. Let me know your thoughts, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-05-19 20:42
bump @AndrewGable

**Comment by AndrewGable** [comment] 2023-05-19 20:46
@laurenreidexpensify - Can you double check this [idea](https://github.com/Expensify/App/issues/18808#issuecomment-1551999549)? Is it worth solving?

**Comment by laurenreidexpensify** [comment] 2023-05-22 14:03
I agree with @Santhosh-Sellavel that we don't need to address this because "we can see the user delete pending on the manage members page". Closing. Thanks

**Closed by laurenreidexpensify** 2023-05-22 14:03 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
