### ISSUE TITLE
[HOLD for payment 2024-06-20] [Payment card / Subscription] Subscription size "Save" button has no margin

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43075] opened 2024-06-04 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating #[42683](https://github.com/Expensify/App/pull/42683)
**Version Number:** 1.4.79-2
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open the New Expensify App
2. Go to /settings/subscription/subscription-size and send in any chat
3. Deeplink it by tapping on the link
4. Input any value and click on "Next"
5. Observe the bottom "Save button"

## Expected Result:
User expects a bottom margin

## Actual Result:
There is no Bottom Margin

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/669e38c1-a51a-4333-afab-0f67b41aa4c0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by m-natarajan** [comment] 2024-06-04 21:40
@chiragsalian FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment] 2024-06-04 21:47
Taking over since it's coming from https://github.com/Expensify/App/pull/42683. Not a deploy blocker since this is a new feature and can't be reached without a direct URL, but we should clean it up @MrMuzyk

**Comment by MrMuzyk** [comment] 2024-06-05 08:05
@amyevans I thought that this feature should only be accessible on web platform. How do we want to handle this? Should we also block access to these screens via direct link? Or should we leave it accessible and fix the margin issue?

cc @JKobrynski

**Comment by amyevans** [comment] 2024-06-06 21:46
@MrMuzyk sorry I missed this earlier. We should just block access via direct link for native

**Comment by greg-schroeder** [comment] 2024-06-06 22:54
Adding to #wave-collect

**Comment by MrMuzyk** [comment] 2024-06-10 07:36
@amyevans I will handle this the same we've handled DisableAutoRenewSurveyPage - will display FullPageNotFoundView component

**Comment by greg-schroeder** [comment] 2024-06-11 01:53
PR is up/in review

**Comment by amyevans** [comment] 2024-06-14 21:51
No payment required here, and regression tests will be added once the feature is fully rolled out, so I'm going to close this out.

**Closed by amyevans** 2024-06-14 21:51 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
