### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] mweb v web inconsistency when you delete a workspace 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13276] opened 2022-12-02 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with the same account on 2 different devices (Web and mWeb) and open the Workspace tab on each
2. On the second device (Web) open the Workspace
3. On the main device (mWeb) delete Workspace
4. After receiving an error message press the back key on the second device (Web)

## Expected Result:
The back key must return to the list of workspace

## Actual Result:
The back key closes the sidebar, but does not return to the list of workspace

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.35.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205353700-938af9e8-e779-47e0-9797-007eb3cda5b1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01e316b667f840dcf7
- Upwork Job ID: 1599759280513908736

**Comment by Puneet-here** [comment] 2022-12-02 17:43
### Proposal

We need to pass `onBackButtonPress={Navigation.goBack}` below

https://github.com/Expensify/App/blob/c34e64c100c34e2daa9d783d75a4f3be023d103f/src/pages/workspace/WorkspaceInitialPage.js#L151

**Comment by situchan** [comment] 2022-12-02 17:53
### **Proposal**

Root cause:
`onBackButtonPress` prop not set here so [default value](https://github.com/Expensify/App/blob/c34e64c100c34e2daa9d783d75a4f3be023d103f/src/components/BlockingViews/FullPageNotFoundView.js#L45) is applied
https://github.com/Expensify/App/blob/c34e64c100c34e2daa9d783d75a4f3be023d103f/src/pages/workspace/WorkspaceInitialPage.js#L151

**Solution:**
```diff
-               <FullPageNotFoundView shouldShow={_.isEmpty(this.props.policy)}>
+               <FullPageNotFoundView onBackButtonPress={() => Navigation.navigate(ROUTES.SETTINGS_WORKSPACES)} shouldShow={_.isEmpty(this.props.policy)}>
````

We need to apply this fix to all pages using FullPageNotFoundView:
WorkspaceInvitePage
WorkspaceMembersPage
WorkspaceSettingsPage

(While I am finding all similar issues throughout the app, @Puneet-here posted proposal)

**Comment by s77rt** [comment] 2022-12-02 20:12
### Proposal
```diff
diff --git a/src/components/BlockingViews/FullPageNotFoundView.js b/src/components/BlockingViews/FullPageNotFoundView.js
index 84014c43d1..3fe080b0f4 100644
--- a/src/components/BlockingViews/FullPageNotFoundView.js
+++ b/src/components/BlockingViews/FullPageNotFoundView.js
@@ -42,7 +42,7 @@ const defaultProps = {
     subtitleKey: 'notFound.pageNotFound',
     shouldShowBackButton: true,
     shouldShowCloseButton: true,
-    onBackButtonPress: () => Navigation.dismissModal(),
+    onBackButtonPress: () => Navigation.goBack(),
 };
 
 // eslint-disable-next-line rulesdir/no-negated-variables
```

### Details
Changed the default behaviour of the back button on `FullPageNotFoundView` to `Navigation.goBack()`

**Comment by arosiclair** [comment] 2022-12-02 22:43
Familiar with this so I can help manage if this passes BZ checks

**Comment by laurenreidexpensify** [comment] 2022-12-05 13:34
- can reproduce ✔️
- this is a bug ✔️
- not a dupe ✔️
- write up instructions are good ✔️
- renamed to make title more clear ✔️

**Comment by thesahindia** [comment] 2022-12-05 14:40
I like @Puneet-here's [proposal](https://github.com/Expensify/App/issues/13276#issuecomment-1335583147) since it deals with all the instances.

C+ reviewed 🎀👀🎀

cc: @arosiclair

**Comment by situchan** [comment] 2022-12-05 14:56
@Puneet-here updated their proposal based on my proposal which handles all instances
![image](https://user-images.githubusercontent.com/108292595/205668051-a43e3aac-c366-4c43-8fe1-8d9155c4f957.png)
At the time I submit proposal, they proposed only for WorkspaceInitialPage

cc: @thesahindia

**Comment by thesahindia** [comment] 2022-12-05 14:59
I have checked it and I am suggesting their proposal because it is handling all cases. Your proposal doesn't address pages that use `WorkspacePageWithSections`. Hope that makes sense.

**Comment by s77rt** [comment] 2022-12-05 15:56
@thesahindia Can you check my proposals as well? https://github.com/Expensify/App/issues/13276#issuecomment-1335794319
would like to get a feedback here

**Comment by laurenreidexpensify** [comment] 2022-12-07 10:38
@Puneet-here @thesahindia offers sent in Upwork

**Comment by Puneet-here** [comment] 2022-12-07 19:58
Accepted the offer and raised the PR, thanks!

**Comment by laurenreidexpensify** [comment] 2022-12-20 11:44
Everyone has been paid ✔️

**Comment by laurenreidexpensify** [comment] 2022-12-20 11:52
We can probably add a line here in this test https://expensify.testrail.io/index.php?/cases/view/1971146&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=229065 will ask in Slack when more people are online

**Comment by thesahindia** [comment] 2022-12-20 11:52
> Merged PR within 3 business days of assignment - 50% bonus

@laurenreidexpensify, it is also eligible for the 50% bonus (it was merged at dec 8th)

**Comment by thesahindia** [comment] 2022-12-20 11:54
> The PR that introduced the bug has been identified. Link to the PR:

I am not sure if we should call this a regression, it was implemented like this.

**Comment by arosiclair** [comment] 2022-12-20 20:55
Yeah I agree that this isn't a straight forward regression. When the workspaces list was added, the scenario for a deleted/invalid workspace was just overlooked. I'll add a comment to that PR to point out that scenario was missed.

**Comment by laurenreidexpensify** [comment] 2022-12-21 12:52
Bonus issued in Upwork 👍🏽

**Closed** 2022-12-21 12:57 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by Puneet-here** [comment] 2022-12-21 13:02
@laurenreidexpensify, bonus is pending for me as well.

**Comment by Puneet-here** [comment] 2022-12-21 14:44
NVM the above comment I didn't receive the message but I have received the bonus.
