### ISSUE TITLE
[Awaiting payment 2023-12-21][$500]  LHN - Green dot is shown after deleting the Money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31730] opened 2023-11-22 17:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Go to FAB > Request Money
3. Switch to Distance
4. FIll the start and finish > Next
5. Choose the newly created workspace > Request money
Notice the green dot will appear on LHN to indicate money to be settled
6. On the main chat in the workspace go to the IOU report
7. Send a message (Important step)
8. Delete the money requested.
Notice the green dot does not disappear and there is no settle button

## Expected Result:
No green dot on the LHN if there is no settle button

## Actual Result:
Green dot on the LHN when there is no settle button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e2524960-85cc-4456-98d9-0fb66a153d17

![Bug6287143_1700658228994!image](https://github.com/Expensify/App/assets/78819774/3096fd2a-6c0c-49c1-b785-87a9fdac21a0)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141106cdac1f59107</li>
        <li>Upwork Job ID: 1727382476023721984</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27989105</li>
<li>DylanDylann | Contributor | 27989107</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-22 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - Green dot is shown after deleting the Money request

### What is the root cause of that problem?
When we send a message in IOU report and then deleting the request. shouldDeleteIOUReport will be false. It caused hasOutstandingChildRequest is not updated to false. So the green dot still display

### What changes do you think we should make in order to solve the problem?
We should reset hasOutstandingChildRequest to false when 
```
updatedReportPreviewAction.childMoneyRequestCount === 0
```

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-11-28 06:03
@aimane-chnaif any thoughts on the proposal above?

**Comment by kadiealexander** [comment] 2023-12-04 00:32
@aimane-chnaif any updates from your review?

**Comment by kadiealexander** [comment] 2023-12-20 03:53
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@aimane-chnaif] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@aimane-chnaif] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@aimane-chnaif] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
- [ ] [@aimane-chnaif] Determine if we should create a regression test for this bug.
- [ ] [@aimane-chnaif] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2023-12-20 03:53
Payouts due:

- [ ] Contributor: $500 @DylanDylann
- [ ] Contributor+: $500 @aimane-chnaif


Upwork job is [here](https://www.upwork.com/jobs/~017cd9958133b7f343).

**Closed** 2023-12-21 02:12 UTC
Labels: Reviewing, External, Daily, Bug
