### ISSUE TITLE
Split bill - App crashed when try to split bill via group

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22975] opened 2023-07-16 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22643
## Action Performed:
1. Create a brand new account that isn't on a domain with a subscription ([xyz@expensify](mailto:xyz@expensify)
❌ // [xyz@gmail.com](mailto:xyz@gmail.com)
✅ )
2. Create a group chat with multiple participants
3. 'Split Bill' for group

## Expected Result:
You should be able to split a bill from someone successfully

## Actual Result:
App crashed on iOS. Android App, Button "Split" not active for Mac/Chrome, Desktop App, mweb

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.41.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dd9ff7a7-acba-4aba-b5fc-e9958f3f4d6f

https://github.com/Expensify/App/assets/78819774/e170cde5-92d7-4e0b-a56d-0c19f35f2bce

https://github.com/Expensify/App/assets/78819774/7001dfc3-9db0-45b2-8148-ad37ef01fcd8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by s-alves10** [comment] 2023-07-17 11:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App crashes when try to split bill with new users

### What is the root cause of that problem?

The backend returns personalDetail info with login = 'undefined' for new users as I mentioned https://github.com/Expensify/App/issues/22588#issuecomment-1631609348.
So the parameters of `Localize.arrayToString` includes `undefined` for newly created accounts.
https://github.com/Expensify/App/blob/25c8ae5212f433ea7679ba4bd040c79f151a282a/src/libs/actions/IOU.js#L462


This is the root cause

### What changes do you think we should make in order to solve the problem?

`login` field for new users are `undefined`. Instead they have alternateText(email) and text(display name) fields. We can use this

```
    const formattedParticipants = Localize.arrayToString([currentUserLogin, ..._.map(participants, (participant) => participant.login || participant.alternateText)]);
```

This works as expected.


### What alternative solutions did you explore? (Optional)
This can be fixed in the backend

**Comment by johncschuster** [comment] 2023-07-18 21:32
Closing since this is a duplicate of https://github.com/Expensify/App/issues/21268. Please take all proposals to that issue instead.

**Closed by johncschuster** 2023-07-18 21:32 UTC
Labels: Daily, Bug
