### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] Zooming out using the slider bar in edit photo does not properly display the image reported by @Tushu17 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12723] opened 2022-11-14 20:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:-

1. Go to settings > Profile > Edit photo
2. Upload a photo
3. Zoom and drag image to its edge
4. Zoom out image through slider bar.

## Expected Result: 
Image shouldn't go outside the frame.

## Actual Result: 
Zooming out using the slider bar in edit photo does not properly display the image.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.27-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201758513-0e44a428-9d29-46a8-93d3-3c3fd7b47fa6.mp4

https://user-images.githubusercontent.com/43996225/201758548-f2e6cdf5-f38a-4ce0-947f-3d87f0d2262f.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668449545797069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01d78e582268fc0f31
- Upwork Job ID: 1597171240948350976

**Comment by johncschuster** [comment] 2022-11-23 18:03
I have reproduced this behavior using the steps above. It seems that zooming in and out works fine, but when you specifically follow the "drag image to its edge" part of the repro steps, the result matches what you captured.

https://user-images.githubusercontent.com/5579997/203617496-5996b534-932f-4f6a-b8a7-56ab1b5e97ce.mp4

**Comment by MariaHCD** [comment] 2022-11-28 10:12
Not overdue

**Comment by thesahindia** [comment] 2022-11-28 21:56
@Ollyws's [proposal](https://github.com/Expensify/App/issues/12723#issuecomment-1328871467) looks good to me!

C+ reviewed 🎀👀🎀

cc: @MariaHCD

**Comment by MariaHCD** [comment] 2022-12-02 10:21
I'm currently reviewing the proposal and will update here shortly.

**Comment by MariaHCD** [comment] 2022-12-03 10:51
@Ollyws's proposal looks good to me as well.

**Comment by MariaHCD** [comment] 2022-12-05 14:41
> During testing I discovered an issue so I've had to make a couple of amendments.
> 
> Intermittently on iOS and Android clicking on the slider will result in this

@Ollyws Could you post videos demonstrating this issue? Thanks!

**Comment by thesahindia** [comment] 2022-12-05 19:39
Sorry for the delay. I am not at 100% (sick right now🤒)
I have tested and yeah it's reproducible for me. Looking into it....

**Comment by thesahindia** [comment] 2022-12-05 20:51
The updated solution looks good to me and will resolve the issue. Let's wait for @MariaHCD's approval.

**Comment by MariaHCD** [comment] 2022-12-06 14:54
The only thing I'd say is to ensure we add comments explaining why we need to use a worklet but otherwise updated proposal looks good to me too 👍🏼

**Comment by thesahindia** [comment] 2022-12-08 13:30
Applied, thanks!

**Comment by johncschuster** [comment] 2022-12-09 20:39
You're both hired! 🎉

**Comment by Tushu17** [comment] 2022-12-09 21:34
Hey @johncschuster, I think I'm also eligible for reporting bonus.

**Comment by MariaHCD** [comment] 2022-12-14 09:15
Thinking about the above BugZero checklist, it looks like this bug wasn't so much introduced by https://github.com/Expensify/App/pull/11717 but the zoom behavior perhaps wasn't tested completely in that PR i.e. testing the behavior once you zoom and drag the image and then click on the slider bar. 

Maybe something like the following in the PR author checklist might be helpful? 

```
I completely tested the feature(s) that can be impacted by my changes (eg. if the PR alters or fixes the slider bar in the AvatarCropModal, I tested zooming into the image, dragging the image, clicking the slider bar, etc.)
```

Let me know what you think @thesahindia and @johncschuster

**Comment by mallenexpensify** [comment] 2022-12-22 20:17
**Paid** 
$1000 - @thesahindia for C+
$1000 - @Ollyws for Contributor
@Tushu17 , can you apply at https://www.upwork.com/jobs/~0166a2d7b61c9c817a and comment here when you have?

It looks like the time between hire and the PR being merged is 4 days so no bonus.  Thanks for getting it done quickly @thesahindia, @Ollyws and @MariaHCD

**Comment by mallenexpensify** [comment] 2022-12-22 20:19
@johncschuster , leaving the regression test steps to you :)

**Comment by thesahindia** [comment] 2022-12-22 20:22
> It looks like the time between hire and the PR being merged is 4 days so no bonus.

I think it is eligible because in the 4 days there was Saturday and Sunday

**Comment by mallenexpensify** [comment] 2022-12-22 20:51
:d'oh:  Thanks for letting me know @thesahindia 
**Bonussed $500** for @thesahindia and @Ollyws

**Comment by Tushu17** [comment] 2022-12-22 21:11
> @Tushu17 , can you apply at https://www.upwork.com/jobs/~0166a2d7b61c9c817a and comment here when you have?

Offer accepted, Thanks.

**Comment by mallenexpensify** [comment] 2022-12-23 23:37
Paid @Tushu17 , closing 🎉

**Closed by mallenexpensify** 2022-12-23 23:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
