### ISSUE TITLE
[HOLD for payment 2024-01-26] [$500] Split - Split scan with existing group members is created in both existing and new group chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34060] opened 2024-01-05 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click FAB > Request money > Manual
2. Split bill with two users
3.  Click FAB > Request money > Scan
4. Create a split scan request with the same two users in Step 2
Note that the split scan creates two same groups, one with the history and another new group. The new group becomes skeleton placeholder after a while

## Expected Result:
The split scan request will be created in the existing group chat which is created in Step 2

## Actual Result:
The split scan request is created in both existing and new group chat. The request disappears and leaves skeleton placeholder after a while in the new group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/423af0fc-ef01-4dc2-8bf1-a3e4d47a8e06

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0147a95509543e3f60</li>
        <li>Upwork Job ID: 1743366914858815488</li>
        <li>Last Price Increase: 2024-01-12</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28104489</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @stitesExpensify</details>

**Comment by unicorndev-727** [comment] 2024-01-05 20:40
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Workspace - In Workspace, trying to add a number contact & selecting it, contact disappears
### What is the root cause of that problem?
The root cause is that we are using random reportId here.
 https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/iou/request/step/IOURequestStepConfirmation.js#L220
### What changes do you think we should make in order to solve the problem?
We should send empty reportId so that we can find reportId from participants here
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/libs/actions/IOU.js#L1700
### What alternative solutions did you explore?
N/A

**Comment by bernhardoj** [comment] 2024-01-05 21:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Every time we create a new scan split bill, it will create the request on a new group chat.

### What is the root cause of that problem?
If we create a scan split bill, it will call `startSplitBill`. In this function, we check if there is an existing group chat for the split bill, if it doesn't exist, we create a new one.
https://github.com/Expensify/App/blob/1752b979b7d0fab987f7b2129c5298bbab2c6ef1/src/libs/actions/IOU.js#L1700-L1704

The way we get the existing group chat is by checking either `existingSplitChatReportID` and `participants[0]?.reportID` (for policy expense chat). If it exists, we will get it from the report Onyx object. If not, we will get the report with `getChatByParticipants`.

However, after the big money request refactor, `existingSplitChatReportID` always exists because every time we open the money request page, we generate a new random report ID. So, we always trying to get the non-existing report because `existingSplitChatReportID` is not empty.

### What changes do you think we should make in order to solve the problem?

Because `existingSplitChatReportID` always exists, we can update the condition to,

```
const existingSplitChatReport = allReports[`${ONYXKEYS.COLLECTION.REPORT}${existingSplitChatReportID || participants[0]?.reportID}`] || ReportUtils.getChatByParticipants(participantAccountIDs);
```

### What alternative solutions did you explore? (Optional)
The `existingSplitChatReportID` same logic also exists on normal `splitBill`, but if we look at the `splitBill` calls, we pass `report.reportID` to the `existingSplitChatReportID` params, so we can do the same.

**Comment by isabelastisser** [comment] 2024-01-08 17:59
@Santhosh-Sellavel please review the proposals above. Thanks!

**Comment by isabelastisser** [comment] 2024-01-09 18:03
Bump @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2024-01-10 18:28
Both proposals are pretty much similar, will discuss them internally and update them here.

**Comment by isabelastisser** [comment] 2024-01-12 18:18
@Santhosh-Sellavel any updates? Thanks!

**Comment by Santhosh-Sellavel** [comment] 2024-01-12 18:46
Adding to get a CME here
C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2024-01-12 19:09
After looking again seems I missed @bernhardoj's alternate [proposal](https://github.com/Expensify/App/issues/34060#issuecomment-1879274077), straightforward one. So let's go with them here, thanks!

C+ Reviewed
🎀 👀 🎀 
cc: @stitesExpensify

**Comment by bernhardoj** [comment] 2024-01-17 07:46
PR is ready

cc: @Santhosh-Sellavel

**Comment by isabelastisser** [comment] 2024-01-29 12:47
Hey @Santhosh-Sellavel, can you please complete the checklist above? Thanks!

**Comment by isabelastisser** [comment] 2024-01-29 12:52
Payment summary:

@Pujan92 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/26508156) (Contributor) $500 paid in Upwork.
@s77rt requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/26508154) (Reviewer) - $500 PENDING PAYMENT IN NEWDOT.

**Comment by isabelastisser** [comment] 2024-01-29 12:56
Waiting for @Santhosh-Sellavel to complete the BZ list.

**Comment by isabelastisser** [comment] 2024-01-31 19:19
waiting for @Santhosh-Sellavel.

**Comment by isabelastisser** [comment] 2024-02-01 21:39
Bump @Santhosh-Sellavel, please let me know if I need to reassign this issue.

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:25
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1476574472
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This should be found while testing
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. Yes
* [ ]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Santhosh-Sellavel** [comment] 2024-02-02 19:26
**Bug:** 
Split scan with existing group members is created in both existing and new group chat

### Regression Steps

1. Create a new group chat with any user (if you don't have one)
2. Create a split scan request from FAB with the participants from the group chat above
3. Verify the request is added to the group chat above and not create a duplicate group chat
4. Create a split scan request from the group chat composer add (+) button
5. Verify the request is added to the group chat above and not create a duplicate group chat

**Comment by isabelastisser** [comment] 2024-02-05 17:09
Issue for regression test is created.

**PENDING**

@Santhosh-Sellavel requires payment through NewDot Manual Requests $500 PENDING PAYMENT IN NEWDOT.

**Closed by isabelastisser** 2024-02-05 17:09 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2024-02-10 20:37
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-02-11 13:05
$500 approved for @Santhosh-Sellavel based on summary above.
