### ISSUE TITLE
[$500] [MEDIUM] Arrow keys don’t seem to work for selecting from the suggested addresses when creating mileage expenses.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34350] opened 2024-01-11 13:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704905717100919

## Action Performed:
1. Open app
2. Go to a workspace chat
3. Create a distance expense
4. Enter start address to show some results
5. Use arrow key to navigate through the results

## Expected Result:
Should be able to select the results

## Actual Result:
Nothing happens

## Workaround:
unknwon

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/50d61c09-c9e3-43dc-9e24-96bf789d337d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5038cd4b1b9a605</li>
        <li>Upwork Job ID: 1745436353934499840</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 28143223</li>
<li>sourcecodedeveloper | Contributor | 28143224</li>
</ul></li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2024-01-15 16:48
@sobitneupane looks like one proposal to review!

**Comment by adelekennedy** [comment] 2024-01-17 23:16
bump on this @sobitneupane (and clearing the overdue tag)

**Comment by sourcecodedeveloper** [comment] 2024-01-18 09:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Create distance expense, enter start address and try to navigate the search results using arrow keys. The user is not able to navigate search results using arrow keys.

### What is the root cause of that problem?
The AddressSearch component need to implement arrow key navigation for search results.
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/components/AddressSearch/index.tsx#L31

### What changes do you think we should make in order to solve the problem?
I would use the hook useArrowKeyFocusManager for functional component instead of ArrowKeyFocusManager and AddressSearch is functional component.

For handling arrow key navigation, add useRefs
```
const maxIndexRef = useRef(0);
const resultRef = useRef(null);
```

Add definition for useArrowKeyFocusManager hook
```
const [focusedIndex, setFocusedIndex] = useArrowKeyFocusManager({
initialFocusedIndex: 0,
maxIndex: maxIndexRef.current,
isActive: true
})
```

The onLayout event holds data for searchResults and the number of search result
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/components/AddressSearch/index.tsx#L423
```
resultRef.current = event.nativeEvent?.target.getScrollResponder().props.data;
maxIndexRef.current = event.nativeEvent?.target.getScrollResponder().props.data.length;
```

The renderRow method can provide index value.
https://github.com/Expensify/App/blob/4da7fdab30857d0934d8a8035f9e1c773385d950/src/components/AddressSearch/index.tsx#L346
Add index to renderRow
```
renderRow={(data, index) 
```

Then the focusedIndex prop of useArrowKeyFocusManager hook can be used to check against the index to set focused row background style.

```
<View style={[StyleUtils.getBackgroundAndBorderStyle(focusedIndex === index ? theme.border : theme.appBG)]}>
    {title && <Text style={[styles.googleSearchText]}>{title}</Text>}
    <Text style={[styles.textLabelSupporting]}>{subtitle}</Text>
</View>
```

The onKeyPress event can be added for handling selecting row of the search results. The selectedRow can be obtained from resultRef holding search results.

```
onKeyPress: (e) => {
    const data = resultRef.current[focusedIndex];
    if(e.code === "Enter")
    {
        saveLocationDetails(data, details);
    }
}
```

### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-01-22 16:30
@sobitneupane two proposals - will you be able to look at these this week?

**Comment by sobitneupane** [comment] 2024-01-24 02:40
@adelekennedy I will be able to review the proposals only in weekend or early next week. Please feel free to re-assign the issue in case of urgerncy.

**Comment by adelekennedy** [comment] 2024-01-26 02:12
@abdulrahuman5196 can you review the proposals above?

**Comment by abdulrahuman5196** [comment] 2024-01-31 11:59
Still working on review. Will try to close out today.

**Comment by abdulrahuman5196** [comment] 2024-01-31 15:00
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-31 15:53
Seems to be a straightforward implementation requirement. We should also address any other place having similar issue.
Seems `UseArrowKeyFocusManager` is the new way to implement arrow keys functionality.
@sourcecodedeveloper proposal here https://github.com/Expensify/App/issues/34350#issuecomment-1898112442 looks good.

🎀 👀 🎀
C+ Reviewed

**Comment by sourcecodedeveloper** [comment] 2024-01-31 21:20
@abdulrahuman5196 Thanks for reviewing the proposal.

**Comment by adelekennedy** [comment] 2024-02-01 16:40
@roryabraham will you review the selected proposal above?

**Comment by sourcecodedeveloper** [comment] 2024-02-01 16:49
@roryabraham I understand I need to wait for assignment before preparing PR. Thanks

**Comment by adelekennedy** [comment] 2024-02-05 17:15
pending proposal approval

**Comment by roryabraham** [comment] 2024-02-05 17:38
This is a new feature, and as such it should be tied to a GitHub Project for the sake of tracking CAP SW time for external contributors. Trying to figure out what project it should be associated with. cc @puneetlath since this was your feature request.

**Comment by roryabraham** [comment] 2024-02-05 17:40
Oh, duh. it's in the title. Wave5

**Comment by roryabraham** [comment] 2024-02-05 17:45
Thanks for your patience @sourcecodedeveloper. I think your proposal looks good, so I'm assigning this to you for implementation.

The only question I had was about this:

> The onKeyPress event can be added for handling selecting row of the search results

_Where_ will the `onKeyPress` event handler be added? Should we leverage the `useKeyboardShortcut` hook?

**Comment by sourcecodedeveloper** [comment] 2024-02-06 11:39
@roryabraham Thanks for the assignment. I did some testing and was able to leverage the useKeyboardShortcut hook for row selection. I have revised the proposal to include useKeyboardShortcut.

**Comment by roryabraham** [comment] 2024-02-13 19:34
Awaiting C+ review from @abdulrahuman5196. @abdulrahuman5196 do you have an estimate when you'll be able to review this PR?

**Comment by abdulrahuman5196** [comment] 2024-02-13 19:36
Hi @roryabraham , I am closing out some TS migration PR. I will take this priority in my morning.

**Comment by roryabraham** [comment] 2024-02-23 00:43
PR currently awaiting further reviews from @abdulrahuman5196

**Comment by jsdev2547** [comment] 2024-02-28 13:54
@abdulrahuman5196 The account for sourcecodedeveloper was mistakenly suspended by Github automation, please wait while GitHub restores account, comments and PR etc.

**Comment by jsdev2547** [comment] 2024-02-29 19:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Go to workspace chat and create distance expense. enter start address, use arrow key to navigate through results. The arrow keys cannot be used to focus on search results.

### What is the root cause of that problem?
Need to implement arrow key focus navigation. I would use arrowkeyfocusmanager hook to implement arrow selection on search results.
https://github.com/Expensify/App/blob/a1a6a746ae53b62a44b7c0c0d58a002aa30d07ca/src/hooks/useArrowKeyFocusManager.ts#L34

### What changes do you think we should make in order to solve the problem?
To store the search results, declare resultRef and maxIndex for arrowKeyFocusManager.

```
const resultRef = useRef();
const [maxIndex, setMaxIndex] = useState(0);
```

In the onLayout event for GooglePlacesAutocomplete component, 
https://github.com/Expensify/App/blob/a1a6a746ae53b62a44b7c0c0d58a002aa30d07ca/src/components/AddressSearch/index.tsx#L427
The nativeEvent object holds data for search results. 

```
	const nativeEvent = event.nativeEvent as unknown as BaseSyntheticEvent<ScrollView>;
	const target = nativeEvent.target.getScrollResponder() as VirtualizedList<HTMLElement>;
```

To implement arrow keys to select current location button, need to leverage onKeyPress event
```
    onKeyPress: (e: KeyboardEvent) => {
        if (!e) {
            return;
        }
        if (e.code === 'ArrowUp') {
            if (shouldShowCurrentLocationButton && (focusedIndex === maxIndex - 1 || maxIndex === 0)) {
                if (!currentLocationButtonRef?.current?.isFocused()) {
                    setFocusedIndex(-1);
                    currentLocationButtonRef?.current?.focus();
                } else {
                    currentLocationButtonRef?.current?.blur();
                }
            }
        }
    },
```

The renderRow event needs to be passed index param to get the index of the search result.

```
renderRow={(data, index) => {
}
```

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-02-29 19:14
@abdulrahuman5196 @roryabraham I have requested to be assigned to the issue on slack (https://expensify.slack.com/archives/C01GTK53T8Q/p1709224954675389). The PR(https://github.com/Expensify/App/pull/37558) is ready review.

**Comment by roryabraham** [comment] 2024-03-01 19:18
@jsdev2547 we've already hired a contributor to fix this issue. You should only post proposals on issues with the `Help Wanted` label. Thanks!

**Comment by roryabraham** [comment] 2024-03-01 19:18
> The account for sourcecodedeveloper was mistakenly suspended by Github automation, please wait while GitHub restores account, comments and PR etc.

Wait, what do you mean by this?

**Comment by abdulrahuman5196** [comment] 2024-03-04 09:52
> > The account for sourcecodedeveloper was mistakenly suspended by Github automation, please wait while GitHub restores account, comments and PR etc.
> 
> Wait, what do you mean by this?

I think that contributor account was blocked and they have created a new account. That's what I assume. 

@sourcecodedeveloper is removed seems. @jsdev2547

**Comment by abdulrahuman5196** [comment] 2024-03-05 10:43
> > > The account for sourcecodedeveloper was mistakenly suspended by Github automation, please wait while GitHub restores account, comments and PR etc.
> > 
> > 
> > Wait, what do you mean by this?
> 
> I think that contributor account was blocked and they have created a new account. That's what I assume.
> 
> @sourcecodedeveloper is removed seems. @jsdev2547

@roryabraham Do we do any checks on this case? Or should i go ahead with reviewing the new PR from @jsdev2547

**Comment by roryabraham** [comment] 2024-03-06 06:32
I suppose we can continue with the review of the new PR from @jsdev2547

**Comment by jsdev2547** [comment] 2024-03-06 08:32
@adelekennedy I already accepted the previous offer so no need to send another offer.

**Comment by abdulrahuman5196** [comment] 2024-03-07 14:29
Got it. Will have a look into it.

**Comment by jsdev2547** [comment] 2024-03-13 09:46
@roryabraham @abdulrahuman5196 PR is awaiting review.

**Comment by abdulrahuman5196** [comment] 2024-04-09 20:09
Hi, We are discussing on potential updates to the arrow manager component.

**Closed** 2024-07-17 18:13 UTC
Labels: Reviewing, External, Engineering, Monthly, NewFeature
