### ISSUE TITLE
[HOLD for payment 2024-10-16] [$250] Dupe detect - App crashes when leaving Review duplicates page after viewing other expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50111] opened 2024-10-02 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+zm29@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat
3. Submit two same expenses
4. Go to transaction thread of any expenses
5. Tap Review duplicates
6. Tap on the second expense preview
7. Swipe right to go back
8. Swipe right again

## Expected Result:
App will not crash

## Actual Result:
App crashes when leaving Review duplicates page after viewing one of the duplicates

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/65590ba3-0ebb-4c30-a3b1-9e828816a362

[logs (2).txt](https://github.com/user-attachments/files/17235471/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841675705747272356</li>
        <li>Upwork Job ID: 1841675705747272356</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 104265027</li>
<li>Nodebrute | Contributor | 104265029</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by lanitochka17** [comment] 2024-10-02 20:14
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-10-02 20:14
We think that this bug might be related to #wave-control

**Comment by RachCHopkins** [comment] 2024-10-03 03:04
I don't have this button in the TestFlight iOS app which is 41-2. I will just have to assume it's reproducible since we have a proposal already!

**Comment by jjcoffee** [comment] 2024-10-03 09:41
@Nodebrute Thanks for the proposal! I'm wondering why `beforeRemoveReportOpenedFromSearchRHP` is running at all here, since we don't have the search RHP open in this case.

> In the case of error we fell in to loop of goBack and beforeRemove

I'm also not sure I understand this. What error are we talking about that's causing the loop?

**Comment by jjcoffee** [comment] 2024-10-03 12:11
@Nodebrute Thanks for clarifying! My only concern is how much we can rely on `state.routes.at(-3)?.name === SCREENS.SEARCH.CENTRAL_PANE`, i.e. is it guaranteed that it will always be at that position?

**Comment by mjasikowski** [comment] 2024-10-04 13:48
@Nodebrute's proposal looks good, indeed, assigning

**Comment by WojtekBoman** [comment] 2024-10-04 14:24
Hey @jjcoffee, I've checked [this proposal](https://github.com/Expensify/App/issues/50111#issuecomment-2390241823) and it's fine :) `shouldPopHome` should verify if RHP is opened from `SearchPage`

**Comment by RachCHopkins** [comment] 2024-10-16 04:31
Payment Summary:

- Contributor: @Nodebrute to be paid $250 via Upwork
- Contributor+: @jjcoffee to be paid $250 via Upwork

Upwork job [here](https://www.upwork.com/jobs/~021841675705747272356)

@jjcoffee can you do the checklist above, please?

**Comment by RachCHopkins** [comment] 2024-10-16 04:33
Contributors have been paid, the contracts have been completed, and the Upwork post has been closed.

**Comment by jjcoffee** [comment] 2024-10-16 08:37
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48990
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/48990/files#r1802620716
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**
Mobile-only.

1. Go to any workspace chat
2. Submit two identical expenses
3. Go to the transaction thread of one of the expenses
4. Tap Review duplicates
5. Tap on the second expense preview
6. Swipe right to go back
7. Swipe right again

Do we agree 👍 or 👎

**Comment by RachCHopkins** [comment] 2024-10-16 21:37
Thanks @jjcoffee, regression test requested! Closing.

**Closed by RachCHopkins** 2024-10-16 21:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
