### ISSUE TITLE
[HOLD for payment 2023-10-09] [$1000] Sign in- Language preference doesn't persist when user Signs in with google

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26133] opened 2023-08-28 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign in page
2. Change the browsers language preference to Spanish
3. Refresh Sign up page
4. Click on 'Sign in with Google icon'
5. Select your account & proceed to sign in

## Expected Result:
Language preference should persist to the app

## Actual Result:
Language preference reverts back to English

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/105856e4-8d33-4641-94ef-edb80b6d8fef

https://github.com/Expensify/App/assets/115492554/5315afea-fa45-4551-95e2-8c23662b2ebe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692679468017399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5f71b81bcb185b1</li>
        <li>Upwork Job ID: 1696624990261616640</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26496302</li>
<li>hoangzinh | Contributor | 26496303</li>
<li>Natnael-guchima | Reporter | 26496305</li>
</ul></li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2023-09-04 22:10
Coolio yep nice work though yikes following this code on the back end was a headache 😂 .

I think we can make these changes in new dot now so that we're passing these things along to the API but until we update the back end it won't be fully fixed but I think that is okay.

I'm going to spin up an internal issue to get the back end changes done. 

Though note since we're in a slight feature freeze we probably won't merge your PR until next week.

**Comment by bondydaa** [comment] 2023-09-04 22:30
okay internal issue here https://github.com/Expensify/Expensify/issues/313959 to get this updated on the back end. Going to see if any other engineers want to pick it up who don't have much experience with our API but if the front end changes are done and no on has picked it up I can probably get it done as well.

**Comment by isabelastisser** [comment] 2023-09-11 17:05
Not sure how to move this forward, can you please clarify @bondydaa @aimane-chnaif @hoangzinh? Thanks!

**Comment by bondydaa** [comment] 2023-09-13 22:14
I don't think we need to hold https://github.com/Expensify/App/pull/26948, the API will basically just ignore the new parameters until the backend is updated. 

There hasn't been any progress on the backend updates and I don't think there will be for a few weeks as we've got a lot of other priorities to focus on.

**Comment by bondydaa** [comment] 2023-09-13 22:22
I think it's fine to merge as long as it is isn't breaking the google / apple sign in. 

sure we can't confirm it sets the NVP properly but that's fine, it will be confirmed when the backend fixes are merged.

**Comment by bondydaa** [comment] 2023-09-14 16:05
oh actually @lakchote has taken on the backend issue for this ❤️ 

1 PR is up right now and we'll review it today. We'll need 1 more PR for the API after that is finished. 

@lakchote you should be able to test the full flow once https://github.com/Expensify/App/pull/26948 is merged (or check it out locally if you are in a big hurry).

**Comment by isabelastisser** [comment] 2023-10-18 16:28
Sorry for the delay, I was OOO. I will take care of this soon!

**Comment by isabelastisser** [comment] 2023-10-19 15:50
The payments were made in Upwork now.

**Comment by isabelastisser** [comment] 2023-10-19 15:55
>  [@isabelastisser] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

https://github.com/Expensify/Expensify/issues/327872

All set!

**Closed by isabelastisser** 2023-10-19 15:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
