### ISSUE TITLE
[$1000] Desktop - error message should show in Spanish 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#19651] opened 2023-05-26 02:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click Profile > Preference
2. Click Force Offline
3. Change the language to Spanish
4. Click on new chat with invalid number, example +15005550111
5. Send messages
6. Go back to Preference, change the language to English > toggle off Force Online

## Expected Result:
Error should be in English now that the account language is English

## Actual Result:
The error messages is shown in Spanish when the language was already changed to English.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [X] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** v1.3.18-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A the toggle is not present in PROD app
**If this was caught during regression testing, add the test name, ID and link from TestRail:** 
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
Found when executing PR https://github.com/Expensify/App/pull/19324 

https://github.com/Expensify/App/assets/43995119/60b1a2d1-5839-48a7-97e5-164b2b2e4523

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdc96c68b8a156b6</li>
        <li>Upwork Job ID: 1662146078155325440</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-05-26 07:44
@mvtglobally I have checked your recorded video.

When user change the language preference, the following code will be executed.

https://github.com/Expensify/App/blob/0f1188de4d7b69ecb2b16485e9f03d92f54afe84/src/libs/actions/App.js#L85-L112

But, in the offline mode (or the user have already changed the force offline mode to online, but the app is still in the offline status, as you can see in your video), API.write only change the local Onyx data, and the request API that update the language preference does not send to the server.

![screenshot](https://github.com/Expensify/App/assets/131836113/96eaadd7-daa8-47de-be6b-3d7f6778189a)

After send the comment, the server will send the response error message and the Onyx data that is stored in the server to the app, and these data will contain the original language preference, as you can see in the below screenshot.

![screenshot1](https://github.com/Expensify/App/assets/131836113/55fa3fc6-8a69-4014-8a68-da7b1b01455d)

So, after app receive the server response and merge the server's Onyx data, the language preference will be changed to the previous state, that is Spanish, and the error message is shown in Spanish.

That is, this issue is not a bug, or at least is not produced by this PR(https://github.com/Expensify/App/pull/19324).

**Comment by s-alves10** [comment] 2023-05-26 15:14
The root cause of this issue is as follows.
When switched from offline mode to online mode, queued requests are sent. If user changes the locale from English to Spanish and again from Spanish to English, then 2 updatePreferredLocale APIs are called with `en` and then `es`.

This works fine, but the push notification arrives sometimes in reverse order and sometimes a bit later by my observation.
![image](https://github.com/Expensify/App/assets/126839717/f31ebfdb-0e29-4d06-bdf7-7f346346de26)

That's the main reason.

I think the push notification shouldn't be sent to the author(who sent the request). Or at least add user ID info not to update onyx store.

This should be handled in backend side

**Comment by sakluger** [comment] 2023-05-26 15:38
Not sure if it's related, but this bug seems similar to this other one: [LHN Attachment taking some to to translate into Spanish](https://github.com/Expensify/App/issues/19449#top)

**Comment by StevenKKC** [comment] 2023-05-26 22:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error messages are shown in Spanish when the language was already changed to English.

### What is the root cause of that problem?

When the user changes from offline mode to online mode, the queued requests are sent to the server.

If user changes the language from English to Spanish, then one UpdatePreferredLocale API are sent to the server. In this case, the app's language is set to Spanish.
If user changes the language from English to Spanish and again from Spanish to English, then 2 UpdatePreferredLocale APIs are sent with en and then es language value. And the responses from the server are processed in reverse order, so the app's language is set to Spanish.
After that, though user changes the language, only 2 APIs are sent to the server, because the same request is removed by following code.
https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/libs/actions/PersistedRequests.js#L34-L37
![1](https://github.com/Expensify/App/assets/131836113/e64103af-68d2-42ac-8b1e-a6d828c918e3)

That is, send multiple UpdatePreferredLocale API causes the app language is set different with the user set.

### What changes do you think we should make in order to solve the problem?

We should send only the last UpdatePreferredLocale API to the server once.
For this, we can remove previous API requests and add the last UpdatePreferredLocale API request by changing the save function(https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/libs/actions/PersistedRequests.js) as below.

```
function save(requestsToPersist) {
    HttpUtils.cancelPendingReconnectAppRequest();
    persistedRequests = _.chain(persistedRequests)
        .concat(requestsToPersist)
        .partition((request) => request.command !== CONST.NETWORK.COMMAND.RECONNECT_APP)
        .flatten()
        .value();
    if (requestsToPersist[0].command === 'UpdatePreferredLocale') {
        persistedRequests =  _.filter(persistedRequests, (persistedRequest) => (persistedRequest.command !== 'UpdatePreferredLocale'));
        persistedRequests = _.chain(persistedRequests)
            .concat(requestsToPersist)
            .value();
    }
        
    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
}
```
Now we can send the last one API to the server, so the app language is set correctly when changes from offline mode to online mode.

### What alternative solutions did you explore? (Optional)
None.

**Comment by abdulrahuman5196** [comment] 2023-05-27 17:08
@fedirjh  Thank you for pointing out.

@Christinadobrzyn Could you check this https://github.com/Expensify/App/issues/19651#issuecomment-1564929913
I am also not sure of the issue here, the error message is in sync with the app's language.

Are we thinking that,
"app language should directly change to the last choosen language, instead of switching through the previous selections?" If so I think that's a different issue and this issue's information has to be updated,

And the proposals here is also trying to fix the issue of "app language should directly change to the last choosen language, instead of switching through the previous selections"

**Comment by abdulrahuman5196** [comment] 2023-05-27 17:10
@s-alves10 Not sure if this https://github.com/Expensify/App/issues/19651#issuecomment-1564544250 is a proposal or general rootcause comment. If it is a proposal, kindly update the proposal as per our guidelines. https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md

**Comment by c3024** [comment] 2023-05-28 07:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After forcing offline, changing language to Spanish, sending messages to an invalid number, then again changing language to English, then going online shows errors for the messages in Spanish.

### What is the root cause of that problem?
[Lines 39 to 71 of App/src/libs/API.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/API.js#LL39C1-L71C2)

```
function write(command, apiCommandParameters = {}, onyxData = {}) {
    ....

    // Write commands can be saved and retried, so push it to the SequentialQueue
    SequentialQueue.push(request);
}

```
`API.js` pushes requests to `SequentialQueue`

These requests are pushed to `persistedRequests` and they would be processed right away through `flush` if network is online. If `NetworkStore.isOffline())`, `push` returns and requests stay in `persistedRequests`.

[Lines 105 to 121 of App/src/libs/Network/SequentialQueue.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/Network/SequentialQueue.js#LL105C1-L121C2)

```
function push(request) {
    // Add request to Persisted Requests so that it can be retried if it fails
    PersistedRequests.save([request]);

    // If we are offline we don't need to trigger the queue to empty as it will happen when we come back online
    if (NetworkStore.isOffline()) {
        return;
    }
    ...
    flush();
}
```
Once network is online `SequentialQueue` all requests in `persistedRequests` are processed one by one.

[Line 32 to 57 of App/src/libs/Network/SequentialQueue.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/Network/SequentialQueue.js#LL32C1-L57C2)
```
function process() {
    const persistedRequests = PersistedRequests.getAll();
    ...
    currentRequest = Request.processWithMiddleware(requestToProcess, true)
        .then(() => {
            PersistedRequests.remove(requestToProcess);
            RequestThrottle.clear();
            return process();
        })
       ...
    return currentRequest;
}
```
Language change, and adding comments after forcing offline get added to `persistentRequests` and they are processed one by one after network is online and it appears slow.

In this case `[UpdatePreferenceLocale, AddComment, AddComment, UpdatePreferenceLocale]` are processed one after another. So, first language is changed to Spanish, then comments added and the errors would be displayed in Spanish, then language is changed to English and page changes to English.

### What changes do you think we should make in order to solve the problem?
Remove the pushed`UpdatePreferredLocale` from `persistentRequests`when network is offline. When language is changed, the page changes to that language irrespective of the network connectivity. I think keeping it for running after getting online is unnecessary.
For this, the following change should be made.
[Lines 105 to 107 of App/src/libs/Network/SequentialQueue.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/Network/SequentialQueue.js#LL105C1-L107C39) 

```
function push(request) {
    // Don't retry UpdatePreferredLocale requests so don't add to persistedRequests
     if (request.command !== 'UpdatePreferredLocale') {
        PersistedRequests.save(request);
    }
  ...
}
```

### What alternative solutions did you explore? (Optional)
Only keep the latest `UpdatePreferredLocale` in `peristedRequests` and push it to the top of `persistedRequests`. So after coming to online only the last selected preference would be there and it will update first.
For this, retain the `SequentialQueue.js` as it is but following change is required in `PersistedRequests.js`
[Line 21 to 29 of App/src/libs/action/PersistedRequests.js](https://github.com/Expensify/App/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/libs/actions/PersistedRequests.js#LL21C1-L29C2) 

```
function save(requestsToPersist) {
    HttpUtils.cancelPendingReconnectAppRequest();
   if (requestsToPersist[0].command === "UpdatePreferredLocale") {
       persistedRequests = _.filter(persistedRequests, persistedRequest => persistedRequest.command !== "UpdatePreferredLocale";
        persistedRequests = _.chain(requestsToPersist)
          .concat(persistedRequests)
         .partition((request) => request.command !== CONST.NETWORK.COMMAND.RECONNECT_APP)
          .flatten()
          .value();
  }
  else {
     persistedRequests = _.chain(persistedRequests)
          .concat(requestsToPersist);
         .partition((request) => request.command !== CONST.NETWORK.COMMAND.RECONNECT_APP)
          .flatten()
          .value();
   }
      
    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
}
```

**Comment by Christinadobrzyn** [comment] 2023-05-30 19:29
@abdulrahuman5196 - great question 

> "Are we thinking that "app language should directly change to the last choosen language, instead of switching through the previous selections?" If so I think that's a different issue and this issue's information has to be updated,
> 
> And the proposals here is also trying to fix the issue of "app language should directly change to the last choosen language, instead of switching through the previous selections"

The issue was that the error message was in Spanish after you changed the language to English (and enabled online). So "app language should directly change to the last choosen language, instead of switching through the previous selections" is what I would expect to happen here. 

But I'm not able to reproduce this Spanish error anymore - going to reach out to QA to see if they can test again.

**Comment by StevenKKC** [comment] 2023-05-31 07:22
@Christinadobrzyn I'm able to reproduce this error. Please change the language an even number of times, and change to online mode.

**Comment by Christinadobrzyn** [comment] 2023-06-01 00:02
Okay, apparently this is still happening and I can reproduce this. Updated the steps in the OP on how I was able to do this. 

what is expected: When switching the language, all messages (included errors) should display in the selected language.

**Comment by Christinadobrzyn** [comment] 2023-06-02 19:53
@abdulrahuman5196 can you please let us know if any of the submitted proposals will work? Otherwise, let us know if you'd like to see more proposals. Thanks!

**Comment by Christinadobrzyn** [comment] 2023-06-02 19:54
Ah sorry, didn't mean to close this!

**Comment by abdulrahuman5196** [comment] 2023-06-02 20:55
I couldn't review due to the churns in repro steps. Will try to repro from my end and review the proposals.

Meanwhile will also check if the above linked tracking issue would solve this.

**Comment by Christinadobrzyn** [comment] 2023-06-02 22:26
Asking here - https://github.com/Expensify/App/issues/12775#issuecomment-1574385102

**Comment by abdulrahuman5196** [comment] 2023-06-05 17:53
@Christinadobrzyn  I think it is not error message alone, but the whole app would have changed if we check in the preferences. Like the below video, correct me if not.


https://github.com/Expensify/App/assets/46707890/503e7454-054d-4110-bac3-54c89571c9bb



@cead22 
If the above is confirmed by @Christinadobrzyn, I think the app is basically updating to last succeeded locale update API. 
Not sure if we should consider this as an issue. 
Even if we try to solve it by removing existing API's from persisted requests during offline and make sure only one API is send when user becomes online, it will not solve the total issue.
Like assume you have 2 devices in offline state and make some locale updates and then when both devices comes online, the account will still be set to the last succeeded locale update API response.

**Comment by Christinadobrzyn** [comment] 2023-06-05 19:22
I'm not sure what would be best for your questions [here](https://github.com/Expensify/App/issues/19651#issuecomment-1577224981) @abdulrahuman5196 related to the last succeeded locale update API.

@cead22 - would you be able to help? Maybe this isn't something we should change at this time?

**Comment by abdulrahuman5196** [comment] 2023-06-07 18:06
@cead22 Waiting on you for the above question - https://github.com/Expensify/App/issues/19651#issuecomment-1577224981

**Comment by Christinadobrzyn** [comment] 2023-06-09 23:14
Sorry, I'm not 100% confident I understand [this](https://github.com/Expensify/App/issues/19651#issuecomment-1577224981). I'll ping in slack to see if we can get some help!

**Comment by cead22** [comment] 2023-06-12 16:59
@StevenKKC my bad, your proposal was the first I saw and I meant to comment on it, and forgot by the time I got to the end. I have a couple of questions

> If user changes the language from English to Spanish and again from Spanish to English, then 2 UpdatePreferredLocale APIs are pushed to the queue and will be sent with en and then es language value. And the responses from the server are processed in reverse order, so finally the app process the first API's response, and language is set to Spanish.

Why are responses from the server processed in reverse order, and does this happen 100% of the time?

> For this, in offline mode when the new API is pushed to the queue, we would remove previous API requests and push the last API request by changing the [save](https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/libs/actions/PersistedRequests.js) function as below.

> if (NetworkStore.isOffline() && requestsToPersist[0].command === 'UpdatePreferredLocale') {
>         persistedRequests = _.reject(persistedRequests, (persistedRequest) => (persistedRequest.command === 'UpdatePreferredLocale' && persistedRequest !== requestsToPersist[0]));
>     }

You say we should only send the last request, but this seems to be keeping the first one in requestsToPersist. Shouldn't we keep the last one `.chain(persistedRequests).concat(requestsToPersist)`?

---

@abdulrahuman5196 @c3024 @s-alves10 @fedirjh @StevenKKC is it possible that the actual issue is that we're storing the translated message in Onyx, eg, "Report no longer exists", instead of saving the translation key, and that's why we see a Spanish message "Error inesperado al..." along with "Report no longer exists"?

**Comment by StevenKKC** [comment] 2023-06-12 17:41
@cead22 
> Why are responses from the server processed in reverse order, and does this happen 100% of the time?

Please check this comment(https://github.com/Expensify/App/issues/19157#issuecomment-1555046815), and I tested several times closely, and responses are definitely processed in reverse order. But I think it's hard to say that this happens 100% of the time.
Even if responses are not processed in reverse order, there is no guarantee that they will be processed in the correct order. So I think send the last UpdatePreferredLocale request is the best solution.

> You say we should only send the last request, but this seems to be keeping the first one in requestsToPersist. Shouldn't we keep the last one `.chain(persistedRequests).concat(requestsToPersist)`?

As you can see in the below code, first concatenate requests, and then remove all UpdatePreferredLocale request except the one in requestsToPersist, so will keep the last one.

```
function save(requestsToPersist) {
    HttpUtils.cancelPendingReconnectAppRequest();
    persistedRequests = _.chain(persistedRequests)
        .concat(requestsToPersist)
        .partition((request) => request.command !== CONST.NETWORK.COMMAND.RECONNECT_APP)
        .flatten()
        .value();

    if (NetworkStore.isOffline() && requestsToPersist[0].command === 'UpdatePreferredLocale') {
        persistedRequests = _.reject(persistedRequests, (persistedRequest) => (persistedRequest.command === 'UpdatePreferredLocale' && persistedRequest !== requestsToPersist[0]));
    }

    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
}
```

**Comment by abdulrahuman5196** [comment] 2023-06-12 17:55
@cead22 
**"Report no longer exists"** is not translated and shown always in english regardless of the language. I think that should be a different issue. Correct me if wrong @Christinadobrzyn 

Title and OP says a different issue
```
Desktop - Error messages is shown in Spanish when the language was already changed to English

**Expected Result:**
Error should be in English now that the account language is English
**Actual Result:**
The error messages is shown in Spanish when the language was already changed to English.
```

I am trying to repro the issue this way
1) Create invalid chat and send a message
2) Switch Language multiple times offline(5-10 UpdatePreferredLocale API in queue) and go online. 
3) switch the language again while online(eg. english) and the language changes to spanish after a while(propably from the response of a UpdatePreferredLocale API from queue)
4) And all the errors change to spanish. 

Didn't have much luck in reproduction, that's why questioned here - https://github.com/Expensify/App/issues/19651#issuecomment-1577224981 following this repro comment https://github.com/Expensify/App/issues/19651#issuecomment-1571113461. Kindly check back the question with the context I am testing out, it would provide clear information. If not do let me know I can explain(But even I haven't been able to repro the exact output issue and that's why I am checking with @Christinadobrzyn)

But if **"Report no longer exists" is not translated**, is the real issue then the issue title and OP is wrong.

**Comment by Christinadobrzyn** [comment] 2023-06-12 23:38
Testing this again. I can no longer reproduce what is in the OP. 

When I change the language to Spanish while offline > send a message > change the language and come back online > the error is in the correct language. 

Asking QA to test again - https://expensify.slack.com/archives/C9YU7BX5M/p1686613044188359

**Comment by StevenKKC** [comment] 2023-06-13 03:59
@Christinadobrzyn I'm still able to reproduce this error. Please change the language an even number of times, and change to online mode.

**Comment by Christinadobrzyn** [comment] 2023-06-13 15:34
Hey @abdulrahuman5196 can you review the above ^ to see what is happening and let me know if you still need me to change the title in the OP based on https://github.com/Expensify/App/issues/19651#issuecomment-1587807537

**Comment by abdulrahuman5196** [comment] 2023-06-13 15:46
@kavimuru 

Even in you video, not only the error message the whole app language and account language is changed to english.
If you go to the Settings -> Preferences, it would show english as selected language now.
It is not matching the Expected OP mentioned, correct me if wrong.

>Error should be in English now that the account language is English

<img width="951" alt="Screenshot 2023-06-13 at 9 11 00 PM" src="https://github.com/Expensify/App/assets/46707890/c6c62218-3046-46ef-9c73-4a623efcadc4">



Sorry @Christinadobrzyn, It's like we are going in circles due to not clear OP. @mvtglobally  Could you kindly clear out the issue since you where the issue creator?

**Comment by abdulrahuman5196** [comment] 2023-06-14 19:03
@mvtglobally  I have been testing with "Force Offline" in the app. Could you kindly check this comment and let us know?

https://github.com/Expensify/App/issues/19651#issuecomment-1589578362

cc: @kavimuru @Christinadobrzyn

**Comment by cead22** [comment] 2023-06-15 17:18
> As you can see in the below code, first concatenate requests, and then remove all UpdatePreferredLocale request except the one in requestsToPersist, so will keep the last one.

@StevenKKC we're keeping the first requests in `requestsToPersist`, ie `requestsToPersist[0]`, but there could be more than one request to update the language right? Shouldn't we keep the last one from `requestsToPersist`?

**Comment by StevenKKC** [comment] 2023-06-15 17:51
@cead22 As you can see below, request is converted to an array. So `requestsToPersist` has only one request.
https://github.com/Expensify/App/blob/f15e6dc98d2c5853ed3456c5c6c648a25c66823f/src/libs/Network/SequentialQueue.js#L105-L107

There is no call to `PersistedRequests.save` anywhere else.

**Comment by abdulrahuman5196** [comment] 2023-06-15 18:09
Hey folks, Could we kindly park the discussions on proposals for now? And confirm on the issue and expected output first? as requested here https://github.com/Expensify/App/issues/19651#issuecomment-1589578362

cc: @cead22 @Christinadobrzyn @mvtglobally Kindly confirm on the issue

@StevenKKC  if you are able to reproduce kindly post the video for the same.

**Comment by Christinadobrzyn** [comment] 2023-06-15 21:10
I can't reproduce this anymore, i don't know if it's because I've tested too many times with (500) 555-0111 and now it's not working (I've tried other numbers too but they don't work either)

- I'm not sure what to do here
- @abdulrahuman5196 and I can't reproduce this but others can. And I can't find other steps that will reproduce this. 
- The videos provided [here](https://github.com/Expensify/App/issues/19651#issuecomment-1589530586) match what the steps in the OP. 

Maybe I'll assign another teammate to this GH to see if they can reproduce it.

**Comment by cead22** [comment] 2023-06-15 22:41
My understanding of the issue is shown in the video in the issue description (the OP). 
- Language is set to English
- Force offline is turned off
- 🐛 User sees **Error inesperado...** 🇪🇸  (this shouldn't happen, imo)
- Error changes to English **Unexpected Error...** 🇺🇸

**Comment by abdulrahuman5196** [comment] 2023-06-16 15:39
> My understanding of the issue is shown in the video in the issue description (the OP).
> 
>     * Language is set to English
> 
>     * Force offline is turned off
> 
>     * 🐛 User sees **Error inesperado...** 🇪🇸  (this shouldn't happen, imo)
> 
>     * Error changes to English **Unexpected Error...** 🇺🇸


@cead22  Yes. Exactly, but the point missed I think by the reporter here is `Its not just the errors but the whole app changes`. But still I wasn't able to reproduce this from start, Only way i was able to reproduce is like switching the language multiple times and coming back online like this https://github.com/Expensify/App/issues/19651#issuecomment-1593541566. Kindly do let me know if i am doing something wrong.



<br/>
<br/>
<br/>
<br/>

I will just frame questions in a way it will be easy to get us out. Let me see if this works out before we go to external contributors.

**Q1) The OP expectation here is `The error messages is shown in Spanish when the language was already changed to English.`**
As per the OP videos provided by reporter, I don't think only the errors are changed, the language through out the app is changed similar to how its pointed out here - https://github.com/Expensify/App/issues/19651#issuecomment-1564929913 and here - https://github.com/Expensify/App/issues/19651#issuecomment-1589578362

**Q2) Do reporter(@mvtglobally) or BZ (@Christinadobrzyn ) agree on the above answer?**

**option 1)** If we agree, then the expected OP should change to `App language is changed to Spanish even though the last selected language is english`, we can proceed to next questions. 

**option 2)** if we don't agree, then the OP video is wrong as per the OP expectation and we should try to repro `a scenario where only the error message is in spanish whereas the account language is in english(header and LHN)`, and we should stop here and the reporter/BZ should come back with the repro video or updated steps.


**Q3) (If option1 from Q2) How much is it reproducible if we only switch back to english once as per OP steps?**
option 1) Not reproducible (For me never reproducible and contributor also did repro it only by switching back and forth multiple times)
option 2) Rarely 
option 3) always

**Comment by cead22** [comment] 2023-06-16 23:50
> Kindly do let me know if i am doing something wrong.

I don't see anything wrong here. We know what the wrong behavior looks like, and we know what we want it to be

- Q1: Agreed
- Q2: option 1) I agree, @abdulrahuman5196 can you update?
- Q3: I'm not sure, but it looks like we have steps to reliably reproduce, right? If so, why does this matter? just curious, I'm happy with us updating the repro steps to make them reliable, but I'd love to continue moving this forward

**Comment by abdulrahuman5196** [comment] 2023-06-19 17:39
@cead22 

>Q3: I'm not sure, but it looks like we have steps to reliably reproduce, right? If so, why does this matter? just curious, I'm happy with us updating the repro steps to make them reliable, but I'd love to continue moving this forward


I was asking this question because to understand if this issue is worth solving separately in the path of `Only one UpdatePreferredLocale call should be present in case of the user making multiple language switches during offline case`. Or should we knock on some other tree,

**Might be a big para, kindly bare with me**

There are actually 2 sub-issue paths here

**Issue 1) Reply effect** 
The steps in the video
**During offline**
1) User changes language from english to spanish(UpdatePreferredLocale API 1)
2) User changes the language from spanish to english(UpdatePreferredLocale API 2)
User has done 2 language switches during offline case.

**During online**
1) App language changes to spanish while successful UpdatePreferredLocale API 1
2) App language changes to english while successful UpdatePreferredLocale API 2

This is a proper reply effect bug same as here - https://github.com/Expensify/App/issues/12775
Initially @Christinadobrzyn  tried to see if this will be solved by the reply effect fixes, but the answer was `no`. But I doubt they would have also be confused with the issue description and thought this as a different issue. We can reach out again on clear context and take it in the path of reply effect fixes. 

But as far as the issue 1 goes, it will ultimately return to the proper language after swaps if there were just 1 or 2 time switching of languages happened offline. 

**Issue 2) Multiple UpdatePreferredLocale API's in the queue**

I agree this is a issue and we should solve. But I don't agree with the fact that we should just check if the `command` is `UpdatePreferredLocale` on the persistant requests and remove previous requests on the same.
We should put more thought on this,
1) If we want to remove previous requests we should create a generic param in the network requests and remove previous requests if required. For ex, in `API.write` we can add a param `removePreviousRequests` and it should remove previous requests.
2) We should also consider how we should propagate `successData` and `failureData` in case of removing a request.(Currently UpdatePreferredLocale API doesn't add any success or failure data but good to investigate as a general implementation). 

But still even if we solve this case and have only one API sent when the user goes online, this will not solve multiple device cases.
Like assume you have 2 devices in offline state and make some locale updates and then when both devices comes online, the account will still be set to the last succeeded locale update API response from one device.


**@cead22 I am ok to solve this issue in the path of `Only one UpdatePreferredLocale call should be present in case of the user making multiple language switches during offline case` if we are fine with the thoughts on issue 2 mentioned here.**



Bonus issue 3: 🤕 Different than current one.
While I was testing this I noticed. When you make a odd number of language switches offline. Like 
1) english -> spanish 
2) spanish -> english 
3) english  -> spanish
For some reason the account language is set to english after sometime, not sure if this is related though, but anyways would be solved by this fix.

**Comment by cead22** [comment] 2023-06-20 01:31
> I agree this is a issue and we should solve. But I don't agree with the fact that we should just check if the `command` is `UpdatePreferredLocale` on the persistant requests and remove previous requests on the same.
> We should put more thought on this,

Happy to discuss and brainstorm, but we don't need to build a general solution for all requests right now, we need to build a solution for this particular case, and if/when there's another case like this, we can generalize. 

> 1. For ex, in `API.write` we can add a param `removePreviousRequests` and it should remove previous requests.

Specifically, I think we can avoid doing this until we have more than one case than can leverage it, and we can build a simpler solution for `UpdatePreferredLocale`

> 2\. We should also consider how we should propagate `successData` and `failureData` in case of removing a request.(Currently UpdatePreferredLocale API doesn't add any success or failure data but good to investigate as a general implementation).

Again, let's solve the problem we have today and not problem we may have tomorrow

> Like assume you have 2 devices in offline state and make some locale updates and then when both devices comes online, the account will still be set to the last succeeded locale update API response from one device.

This is interesting, but I think it's fine. Maybe a good solution for this would be to make the locale per-device, and not per-account, but I don't think we need to worry about this now.

@abdulrahuman5196 can we move forward with this approach?

**Comment by cead22** [comment] 2023-06-21 05:03
On second thought, it looks like we may already have other places to apply this solution to, so the general solution might be the right way to go now, see https://github.com/Expensify/App/issues/19640

**Comment by abdulrahuman5196** [comment] 2023-06-21 09:33
@cead22 Yes. I think even all other notification/settings kind of flow would have been affected by this kind of issue, where like multiple requests are queued.

we should go for a general solution. But the solution would become complex obviously. 
tagging contributors who had already proposed @StevenKKC @c3024

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:31
Just following up - @abdulrahuman5196 @StevenKKC @c3024 any update on a proposal for this fix?

**Comment by abdulrahuman5196** [comment] 2023-06-24 18:16
Currently we don't have a proposal satisfying of our generic requirement. If any contributors already proposed could update their solution it would be great. If not we have to look other options of increasing bounty or going internal

**Comment by cead22** [comment] 2023-06-26 20:06
I started a discussion about how to move this forward here https://expensify.slack.com/archives/C01GTK53T8Q/p1687808610323569. We're leaning towards closing this issue

**Comment by Christinadobrzyn** [comment] 2023-06-28 20:59
I'll check on that thread, not sure if we got to a conclusion.

**Comment by Christinadobrzyn** [comment] 2023-06-30 18:54
I think we're moving forward with this, right @cead22?

**Comment by StevenKKC** [comment] 2023-07-01 01:54
I agree that my proposal is for a special case, not a general one.
Add `removePreviousRequests` to `API.write` function's `apiCommandParameters` parameter and change code as below maybe more acceptable.

```js
    API.write(
        'UpdatePreferredLocale',
        {
            value: locale,
            removePreviousRequests: NetworkStore.isOffline(),
        },
        {optimisticData},
    );
```

```js
function save(requestsToPersist) {
    HttpUtils.cancelPendingReconnectAppRequest();
    persistedRequests = _.chain(persistedRequests)
        .concat(requestsToPersist)
        .partition((request) => request.command !== CONST.NETWORK.COMMAND.RECONNECT_APP)
        .flatten()
        .value();
    if (requestsToPersist[0].data.removePreviousRequests && requestsToPersist[0].data.removePreviousRequests === true) {
        persistedRequests = _.reject(persistedRequests, (persistedRequest) => (persistedRequest.command === requestsToPersist[0].command && persistedRequest !== requestsToPersist[0]));
    }
    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
}
```

For the general solution, there are not enough cases to consider, and I think the above solution is sufficient for some preference settings in offline mode.
It would be better if we discuss general solution when we have more cases in the future.

**Comment by abdulrahuman5196** [comment] 2023-07-03 17:48
Not overdue.

>I think we're moving forward with this, right @cead22?

I doubt that. Could you kindly provide us what is the path forward we are looking on this issue? @cead22

**Comment by cead22** [comment] 2023-07-05 23:15
In [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1687991749604079?thread_ts=1687808610.323569&cid=C01GTK53T8Q) we identified the following two situations, and agreed that the first one isn't a bug, and that we'll use this issue to fix the second one, does that make sense?

1. If you switch languages multiple times while offline, when you come online, the language will switch multiple times as the requests queued while you were offline are dequeued and sent to the server
2. We have an error message that is always shown in English

**Comment by abdulrahuman5196** [comment] 2023-07-06 13:27
Yes. @cead22 Fine by me

**Comment by cead22** [comment] 2023-07-06 18:55
Correct me if I'm wrong but now that we're switching gears to solve only problem number 2 above, I don't think we have any proposals for that specifically right now.

If that's the case, @StevenKKC @c3024 @s-alves10 would you like to submit a proposal for this? Thanks

**Comment by cead22** [comment] 2023-07-10 16:34
Still waiting for proposals

**Comment by abdulrahuman5196** [comment] 2023-07-10 16:41
@cead22 / @Christinadobrzyn  The bug is still marked internal? Could we change it to external and update the bug title and description as per the new requirement from here - https://github.com/Expensify/App/issues/19651#issuecomment-1624166437

**Comment by Christinadobrzyn** [comment] 2023-07-10 23:26
@abdulrahuman5196 should I raise the bounty to get more proposals?

**Comment by pecanoro** [comment] 2023-07-10 23:28
That error is a back-end error, it cannot be fixed as we don't support handling translations for back-end errors yet. I would say that we can close this issue as we have done with many other instances when this was brought up.

**Comment by Christinadobrzyn** [comment] 2023-07-11 23:44
@cead22 @abdulrahuman5196 should we close based on https://github.com/Expensify/App/issues/19651#issuecomment-1629867862?

**Comment by cead22** [comment] 2023-07-14 17:17
Agree with Rocío, let's close

**Closed by cead22** 2023-07-14 17:17 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
