### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Android -  State gets cleared when selecting the same country

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28034] opened 2023-09-22 16:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open settings > profile > personal-details > address
2. Click on country & select India, enter any state name manually and save.
3. Now click on country and select the India again.
4. Observe the saved state gets cleared

## Expected Result:
The state should not get cleared.

## Actual Result:
The state gets cleared.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/df21ac5b-4786-4723-8fda-98c6f2efdbb4

https://github.com/Expensify/App/assets/93399543/4dc68aa3-f1aa-45b9-9c8a-151563177cca

**Expensify/Expensify Issue URL:**
**Issue reported by:** krishna2323
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695225387907579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0182f7137fd1deb9ae</li>
        <li>Upwork Job ID: 1705259279037448192</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 26875340</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-22 16:34
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
App clears state even if the selected country is not changed.

### What is the root cause of that problem?
We are not checking if the selected country is the changed or not before updating state to empty string.

https://github.com/Expensify/App/blob/778f7636c9b59f592193ffad892c0d2904bc84da/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L119-L129

### What changes do you think we should make in order to solve the problem?
We should return from the function if the `key` is `country` and `value` is same as the `currentCountry`.

`if (key === 'country' && currentCountry === value) return;`

### Result

**Comment by devharp** [comment] 2023-09-23 13:45
# Proposal for Addressing TextInput State Clearance Issue
### Problem Statement
The issue at hand is related to the inadvertent clearing of the 'state' when selecting the same country in the CountryPicker.

### Root Cause
The root cause of this issue can be attributed to the CountryPicker component. Specifically, the `onInputChange` function in the `CountryPicker` is triggered even when the same country is selected, inadvertently triggering the address update and causing the state to be cleared.

### Proposed Solution
To resolve this issue, we propose a modification to the `CountryPicker` component. The proposed changes involve verifying if the new country is selected `onInputChange`.

### Reasons for Modifying CountryPicker
**Preserving Form State Integrity**: By invoking `onInputChange` selectively, only when the value changes, we can maintain the correct form states, preventing unintended side effects and preserving form state integrity.

**Consistency and Efficiency**: This adjustment ensures consistency with other form elements, following the principle of triggering change events only when necessary and avoiding redundant state updates in the form.

**Enhanced Reusability**: Modifying CountryPicker ensures the resolution of this issue across the application, promoting reusability without encountering similar problems elsewhere.

**Comment by devharp** [comment] 2023-09-23 13:50
Contributor details
Your Expensify account email: hsingh.161297@gmail.com
Upwork Profile Link: [Upwork Account](https://www.upwork.com/freelancers/~01ae4662188c69bef7)

# Proposal for Addressing TextInput State Clearance Issue
### Problem Statement
The issue at hand is related to the inadvertent clearing of the 'state' when selecting the same country in the CountryPicker.

### Root Cause
The root cause of this issue can be attributed to the CountryPicker component. Specifically, the `onInputChange` function in the `CountryPicker` is triggered even when the same country is selected, inadvertently triggering the address update and causing the state to be cleared.

### Proposed Solution
To resolve this issue, we propose a modification to the `CountryPicker` component. The proposed changes involve verifying if the new country is selected `onInputChange`.

### Reasons for Modifying CountryPicker
**Preserving Form State Integrity**: By invoking `onInputChange` selectively, only when the value changes, we can maintain the correct form states, preventing unintended side effects and preserving form state integrity.

**Consistency and Efficiency**: This adjustment ensures consistency with other form elements, following the principle of triggering change events only when necessary and avoiding redundant state updates in the form.

**Enhanced Reusability**: Modifying CountryPicker ensures the resolution of this issue across the application, promoting reusability without encountering similar problems elsewhere.

**Comment by devharp** [comment] 2023-09-23 14:07
Contributor details
Your Expensify account email: hsingh.161297@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ae4662188c69bef7

# Proposal for Addressing TextInput State Clearance Issue
### Problem Statement
The issue at hand is related to the inadvertent clearing of the 'state' when selecting the same country in the CountryPicker.

### Root Cause
The root cause of this issue can be attributed to the CountryPicker component. Specifically, the `onInputChange` function in the `CountryPicker` is triggered even when the same country is selected, inadvertently triggering the address update and causing the state to be cleared.

### Proposed Solution
To resolve this issue, we propose a modification to the `CountryPicker` component. The proposed changes involve verifying if the new country is selected `onInputChange`.

### Reasons for Modifying CountryPicker
**Preserving Form State Integrity**: By invoking `onInputChange` selectively, only when the value changes, we can maintain the correct form states, preventing unintended side effects and preserving form state integrity.

**Consistency and Efficiency**: This adjustment ensures consistency with other form elements, following the principle of triggering change events only when necessary and avoiding redundant state updates in the form.

**Enhanced Reusability**: Modifying CountryPicker ensures the resolution of this issue across the application, promoting reusability without encountering similar problems elsewhere.

**Comment by trjExpensify** [comment] 2023-09-25 07:59
Is this perhaps linked? https://github.com/Expensify/App/issues/27814

**Comment by eVoloshchak** [comment] 2023-09-25 11:22
@trjExpensify, the root cause for this is different, but the issues are similar
This was actually proposed as an enhancement in one of the proposals for https://github.com/Expensify/App/issues/27814#issuecomment-1727249608, before this issue was even created

> I think the city field also should be clear after changing country like state field. This is BUG 2

I [assumed](https://github.com/Expensify/App/issues/27814#issuecomment-1729744730) this was by design, but clearly it's not.
> I see where you're coming from, but I believe this is by design. We don't clear anything besides state when changing a country, it's not necessarily linear, you can populate all of the fields in any order

In my opinion, we should keep the issues separate, those are two different bugs that happen on the same page

**Comment by burczu** [comment] 2023-09-25 11:43
I've just reviewed all the proposals and I think we should proceed with [the one](https://github.com/Expensify/App/issues/28034#issuecomment-1731819123) from @dukenv0307 - while [the solution](https://github.com/Expensify/App/issues/28034#issuecomment-1731716791) from @Krishna2323 would also fix the issue I agree with @dukenv0307's reasoning why it's better to fix it inside the `CountryPicker` component.

The proposal from @devharp is actually the same as the one from @dukenv0307 but it was posted later.

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2023-10-10 23:17
👋 Can we get this checklist filled out to proceed with payment please?

**Comment by trjExpensify** [comment] 2023-10-13 17:20
Bump!

**Comment by trjExpensify** [comment] 2023-10-16 13:33
Same as Friday, Melv!

**Comment by burczu** [comment] 2023-10-17 06:17
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: No regression - it worked this way from the beginning.
* [x]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: n/a
* [x]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: n/a
* [x]  [@burczu] Determine if we should create a regression test for this bug.
* [x]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@trjExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by trjExpensify** [comment] 2023-10-17 15:34
👋 Mind adding a bit of reasoning on the justification for these, please? 

>@burczu] Determine if we should create a regression test for this bug.
> [@burczu] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by arosiclair** [comment] 2023-10-20 19:09
Bump @burczu ^

**Comment by burczu** [comment] 2023-10-30 09:47
@trjExpensify In terms of justification to not adding regression tests - I think this bug wasn't impactful and does not brake important flow of the application. It was just slightly inconvenient for the end user that they had to re-enter the state after selecting the same country from the country selector. What do you think?

**Comment by trjExpensify** [comment] 2023-10-30 11:47
Cool, thanks for expanding. I can see that argument because it's reselecting the same country which is probably not that likely to happen. 

Alright, so with that out of the way, moving on to payments: 

- @dukenv0307 $750 for the bug fix & #urgency bonus (paid!)
- @krishna2323 $50 for the bug report (offer sent)

Urgency bonus applied [as per here](https://github.com/Expensify/App/issues/28034#issuecomment-1734955533) and the PR pre-dating the change.

**Comment by trjExpensify** [comment] 2023-10-30 12:25
Settled up with @Krishna2323. Closing!

**Closed by trjExpensify** 2023-10-30 12:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
