### ISSUE TITLE
[HOLD for payment 2023-10-23][$1000] Settings - Cursor is not consistent on input in help page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26169] opened 2023-08-29 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to expensify help page [help.expensify.com](http://help.expensify.com/)
2. Click on search icon to open search
3. Hover over input field
4. Notice weird behavior in cursor

## Expected Result:
Cursor should show text format everywhere on input field.  Also, when search is opened, the flashing `|` should automatically show to denote someone can immediately start typing their search request without having to click in the `Search for something` field.  

## Actual Result:
Cursor is showing text format only in bottom part of input field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9c8db6fc-82ff-4d65-a713-855f32185d31

https://github.com/Expensify/App/assets/115492554/35aa641e-1909-4e57-80b1-54c0288c8232

**Expensify/Expensify Issue URL:**

**Issue reported by:** @alitoshmatov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692689166866949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016cf3b91c7facc3ff</li>
        <li>Upwork Job ID: 1698529155399421952</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27106249</li>
<li>getusha | Contributor | 27106251</li>
<li>alitoshmatov | Reporter | 27106253</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-08-29 10:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Cursor is not consistent on input in help page
### What is the root cause of that problem?
Label is on top of the input field and cursor text is only applied to input field, that is why cursor text is only shown on the bottom part of the input field where label is not on top of input element
### What changes do you think we should make in order to solve the problem?
Not only clicking on input but outside also is focusing the input field, that is why I think we should apply `cursor: text` to the element higher in element tree.
I found this element's whole area is clickable and focuses input element
<img width="345" alt="Screenshot 2023-08-22 at 14 39 14" src="https://github.com/Expensify/App/assets/59907218/f3f7e04d-c8a9-4f91-94ae-a4ddda047319">
So we can create selector to this element and apply `cursor: text` in https://github.com/Expensify/App/blob/main/docs/_sass/_search-bar.scss
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2023-09-04 02:51
This isn't specifically a NewDot bug but... it's a bug and the help page is accessible via NewDot so I think we should fix it (and, do so via a Contributor if possible).  I updated the OP to include this too, since both these seems like quick fixes. 
> Also, when search is opened, the flashing `|` should automatically show to denote someone can immediately start typing their search request without having to click in the `Search for something` field.

**Comment by mallenexpensify** [comment] 2023-09-04 02:52
@trjExpensify , not sure why you got auto-assigned but.. it's convenient cuz I'm off this week, can you keep 👀 on this til I'm back on Monday please?  

@aimane-chnaif can you confirm that you think this issue can be worked on by an external contributor, since it's related to the help site?

**Comment by Escanor202695** [comment] 2023-09-04 04:06
Explanation: The search input is inside a <td> tag. There are two tag labels and the input, the cursor shows | when hovered over the input field but switches back to a POINTER when hovered over the Label. To make it consistent we need to fix CSS for the <td> that contains both label and input, we can explicitly set the type of cursor for the label to "AUTO" to solve this issue.

My Upwork profile: https://www.upwork.com/freelancers/~015e5e0080cf84c27a

<img width="1440" alt="Screenshot 2023-09-04 at 9 58 26 AM" src="https://github.com/Expensify/App/assets/56990221/d6b95854-d871-478d-8176-6872c9815c97">

**Comment by Escanor202695** [comment] 2023-09-04 04:11
Contributor details
Your Expensify account email: [sakibchow202695@gmail.com](mailto:sakibchow202695@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~015e5e0080cf84c27a

Solution: The search input is inside a tag. There are two tags, the label and the input field, the AUTO cursor shows when hovered over the input field but switches back to a POINTER when hovered over the Label. To make it consistent we need to fix CSS for the that contains both label and input, we can explicitly set the type of cursor for the label to "AUTO" to solve this issue.

<img width="1440" alt="Screenshot 2023-09-04 at 9 58 26 AM" src="https://github.com/Expensify/App/assets/56990221/256674ac-eace-4f89-ab2a-588549b6d4d0">

**Comment by jeffmcgwn** [comment] 2023-09-04 04:11
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
The cursor is not consistent on the search input for the help page, furthermore it is requested that the flashing `|` should happen automatically when the search is first clicked.
**What is the root cause of that problem?**
The label for the input doesn't have a cursor specified in css and there's nothing triggering the `|` state.
**What changes do you think we should make in order to solve the problem?**
Add `cursor: text` here: https://github.com/Expensify/App/blob/44721d2035642266b43d1bad36b30d7a3c5e239d/docs/_sass/_search-bar.scss#L132

And also add `searchInput.focus()` here: https://github.com/Expensify/App/blob/44721d2035642266b43d1bad36b30d7a3c5e239d/docs/assets/js/main.js#L158

**Comment by jeffmcgwn** [comment] 2023-09-04 04:18
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
The cursor in the search input on the main help page is not 'text', furthermore it was requested that the `|` be flashing upon clicking the search button
**What is the root cause of that problem?**
There is no css indicating a cursor style
**What changes do you think we should make in order to solve the problem?**
Add `cursor: text` here: https://github.com/Expensify/App/blob/f85e7aef90748317644afd9a02a9b32f166d6180/docs/_sass/_search-bar.scss#L133
And add `searchInput.focus()` here: https://github.com/Expensify/App/blob/44721d2035642266b43d1bad36b30d7a3c5e239d/docs/assets/js/main.js#L158

**Comment by Escanor202695** [comment] 2023-09-04 04:19
> ⚠️ Missing/invalid email or upwork profile link. Please make sure you add both your Expensify email and Upwork profile link in the format specified.

my both informations are correct

**Comment by jeffmcgwn** [comment] 2023-09-04 04:21
Contributor details
Your Expensify account email: jeffmcgwn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01921c0610c798d976

**Comment by Escanor202695** [comment] 2023-09-04 04:28
Contributor details
Your Expensify account email: [sakibchow202695@gmail.com](mailto:sakibchow202695@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~015e5e0080cf84c27a

**Comment by Escanor202695** [comment] 2023-09-04 04:34
Contributor details
Your Expensify account email: [sakibchow202695@gmail.com](mailto:sakibchow202695@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~015e5e0080cf84c27a

**Comment by Escanor202695** [comment] 2023-09-04 04:37
Contributor details
Your Expensify account email: sakibchow202695@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015e5e0080cf84c27a

**Comment by mallenexpensify** [comment] 2023-09-11 05:38
Thanks @aimane-chnaif. Thanks @trjExpensify for 👀, unassigned ya. 
@aimane-chnaif can you review @jeffmcgwn 's proposal above plz?

**Comment by mallenexpensify** [comment] 2023-09-14 06:59
@aimane-chnaif please review @jeffmcgwn 's proposal above and provide feedback

**Comment by alitoshmatov** [comment] 2023-09-14 09:24
Originally posted in slack: https://expensify.slack.com/archives/C049HHMV9SM/p1692697320540559?thread_ts=1692689166.866949&cid=C049HHMV9SM
 ## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor is not consistent on input in help page
### What is the root cause of that problem?
Label is on top of the input field and cursor text is only applied to input field, that is why cursor text is only shown on the bottom part of the input field where label is not on top of input element
### What changes do you think we should make in order to solve the problem?
Not only clicking on input but outside also is focusing the input field, that is why I think we should apply `cursor: text` to the element higher in element tree.
I found this element's whole area is clickable and focuses input element
<img width="345" alt="Screenshot 2023-08-22 at 14 39 14" src="https://github.com/Expensify/App/assets/59907218/f3f7e04d-c8a9-4f91-94ae-a4ddda047319">
So we can create selector to this element and apply `cursor: text` in https://github.com/Expensify/App/blob/main/docs/_sass/_search-bar.scss
### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2023-09-19 09:24
@aimane-chnaif please review the proposals above, thx

**Comment by mallenexpensify** [comment] 2023-09-21 09:38
@aimane-chnaif can you please review the above proposals and provide an update

**Comment by jeffmcgwn** [comment] 2023-09-26 12:11
> Current assignee @aimane-chnaif is eligible for the Internal assigner, not assigning anyone new.

@aimane-chnaif What does this mean for me?

**Comment by mallenexpensify** [comment] 2023-09-27 05:53
Bumping back to External cuz I think/hope we're close here. 
@aimane-chnaif can you please provide feedback on the above proposals? Are they 👍 but you'd just like the glitch fixed in addition to?

**Comment by getusha** [comment] 2023-09-27 08:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

The label is outside the input element coverage which makes the cursor to change when the mouse is moved to the label.

![Screenshot 2023-09-27 at 11 10 08 AM](https://github.com/Expensify/App/assets/75031127/ecab4f41-7bf0-463a-b2f7-5153bd5d3345)

### What changes do you think we should make in order to solve the problem?


We should add a padding here to make the input element contain the label element like newDot

https://github.com/Expensify/App/blob/d61f55ac16b797f831e4cb1b9669ba326ac7b8f9/docs/_sass/_search-bar.scss#L94-L98

```diff
+ padding: 15px 0px 0px !important;
```

and set pointer-events to none here, since the focus will be handled on the input element

https://github.com/Expensify/App/blob/d61f55ac16b797f831e4cb1b9669ba326ac7b8f9/docs/_sass/_search-bar.scss#L143

```diff
+ pointer-events: none;
```

there will also be small changes to make the layout match the previous one.

result: 

<details><summary>Details</summary>

Uploading Screen Recording 2023-09-27 at 11.27.40 AM.mov…

</details> 

cc: @aimane-chnaif

**Comment by mallenexpensify** [comment] 2023-10-02 16:59
@aimane-chnaif can you review @getusha 's proposal above plz? https://github.com/Expensify/App/issues/26169#issuecomment-1736945282

**Comment by jasperhuangg** [comment] 2023-10-09 18:45
@getusha has been assigned! Thanks for your proposal, it makes sense to me.

**Comment by getusha** [comment] 2023-10-09 20:57
@aimane-chnaif @jasperhuangg [PR](https://github.com/Expensify/App/pull/29121) is ready!

**Comment by mallenexpensify** [comment] 2023-10-25 13:47
Lil confused here, @aimane-chnaif can you help? 
I see the issue was [deployed to Staging 2 weeks ago](https://github.com/Expensify/App/pull/29121#issuecomment-1758906578) but production, do you know why? 

From the OP, the issue was reproducible on staging and production
<img width="261" alt="image" src="https://github.com/Expensify/App/assets/22508304/d5f1b3d9-a6ed-41d4-be66-8cc806c2c59b">

Need to figure out when payment's due

**Comment by mallenexpensify** [comment] 2023-10-26 16:30
Issue reporter: @alitoshmatov paid $50 via Upwork
Contributor: @getusha paid $1500 via Upwork inc. urgency bonus
Contributor+: @aimane-chnaif paid $1500 via Upwork inc. urgency bonus 

Thanks all.

**Closed by mallenexpensify** 2023-10-26 16:30 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
