### ISSUE TITLE
[$500] Expense - No error when saving an empty merchant in created workspace request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36574] opened 2024-02-15 12:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to workspace chat.
3. Go to + > Request money > Manual.
4. Create a manual request with a merchant name
5. Save
6. Navigate to the request details
7. Click Merchant.
8. Empty the merchant field and save it.

## Expected Result:
A merchant name is required on a money request > there should be an error "Enter a Merchant Name" if the merchant is blank. The user should not be able to save the IOU without adding a merchant

## Actual Result:
User can save empty merchant when editing created request and no error shows up.
The same issue also occurs when the scan request fails. There is no error on Merchant row.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/eb41e430-ea46-4362-8936-785749ef49c1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1421b286665858e</li>
        <li>Upwork Job ID: 1758111511563407360</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>DylanDylann | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-15 12:52
We think that this bug might be related to #wave5-free-submitters
CC @dylanexpensify

**Comment by DylanDylann** [comment] 2024-02-15 15:31
@jayeshmangwani 
> note - before we were using the [EditRequestMerchantPage](https://github.com/Expensify/App/blob/main/src/pages/EditRequestMerchantPage.js) page to display the edit merchant, thats why this issue happening after we are using the common MONEY_REQUEST_STEP_MERCHANT pages for the edit merchant

The logic is migrated totally from EditRequestMerchantPage to IOURequestStepMerchant. Thus, the logic should be the same in the EditRequestMerchantPage and IOURequestStepMerchant. Is there any difference here?

**Comment by jayeshmangwani** [comment] 2024-02-15 16:25
@DylanDylann yes there is a difference,

in this [PR](https://github.com/Expensify/App/pull/35641/files), you have removed below code from src/pages/EditRequestPage.js page


```javascript
    if (fieldToEdit === CONST.EDIT_REQUEST_FIELD.MERCHANT) {
        return (
            <EditRequestMerchantPage
                defaultMerchant={transactionMerchant}
                isPolicyExpenseChat={isPolicyExpenseChat}
                onSubmit={saveMerchant}
            />
        );
    }
``` 

and isPolicyExpenseChat defined like this, on the EditRequestPage page, and that was being passed to EditRequestMerchantPage, and on the EditRequestMerchantPage we were checking if isPolicyExpenseChat is true then show the error for empty merchant value
https://github.com/Expensify/App/blob/50e07e8604d40b278c1ede2fc5c6fb78c97f1c1f/src/pages/EditRequestPage.js#L86-L87

and on IOURequestStepMerchant page we are using below code to determine if we have to show the error for empty merchant

https://github.com/Expensify/App/blob/d55757ffe7dc7c8eb801fcc359d7ebb7e5cd338b/src/pages/iou/request/step/IOURequestStepMerchant.js#L78
https://github.com/DylanDylann/App/blob/d55757ffe7dc7c8eb801fcc359d7ebb7e5cd338b/src/pages/iou/request/step/IOURequestStepMerchant.js#L91-L93

now did you get why it was working for EditRequestMerchantPage and not for the IOURequestStepMerchant ?

**Comment by Christinadobrzyn** [comment] 2024-02-16 15:31
I just tested this again and I don't think it's happening anymore. I'll ask QA to test again.

**Comment by Christinadobrzyn** [comment] 2024-02-16 21:32
Okay sorry, it sounds like this might be a regression from https://github.com/Expensify/App/issues/36574#issuecomment-1946486859 as @jayeshmangwani already noted here https://github.com/Expensify/App/issues/36574#issuecomment-1946486859 (sorry for mixing up everything)

**Comment by DylanDylann** [comment] 2024-02-19 03:04
As @dukenv0307's [proposal](https://github.com/Expensify/App/issues/36574#issuecomment-1947956025) mentioned

> Thus, I don't think this issue is a regression from https://github.com/Expensify/App/pull/35641 because this logic was created before that

I agree with him at this point. But this issue happened after that PR was merged and this issue also be resolved If we revert that PR

@hoangzinh Should we handle this issue as a regression of https://github.com/Expensify/App/pull/35641? Ping you here because you are the reviewer of https://github.com/Expensify/App/pull/35641

cc @Ollyws

**Comment by lakchote** [comment] 2024-02-19 07:53
> As @dukenv0307's [proposal](https://github.com/Expensify/App/issues/36574#issuecomment-1947956025) mentioned
> 
> > Thus, I don't think this issue is a regression from #35641 because this logic was created before that
> 
> I agree with him at this point. But this issue happened after that PR was merged and this issue also be resolved If we revert that PR
> 
> @hoangzinh Should we handle this issue as a regression of #35641? Ping you here because you are the reviewer of #35641
> 
> cc @Ollyws

Since the issue would be gone if your PR was reverted:
Yes, you should handle this issue as regression of https://github.com/Expensify/App/pull/35641.
cc @hoangzinh

**Comment by Beamanator** [comment] 2024-02-19 13:17
What exactly is the plan here? It looks like we didn't assign a contributor, right @lakchote ? Or is @DylanDylann planning to handle it as it's a regression from their PR?

**Comment by DylanDylann** [comment] 2024-02-19 13:52
I will raise a PR to fix soon

**Comment by DylanDylann** [comment] 2024-02-19 18:23
I have the same idea as @dukenv0307's proposal and I am creating a PR. @hoangzinh What do you think about it?

**Comment by lakchote** [comment] 2024-02-20 07:36
> What exactly is the plan here? It looks like we didn't assign a contributor, right @lakchote ? Or is @DylanDylann planning to handle it as it's a regression from their PR?

As said previously in my message, the plan since it's a regression, is for @DylanDylann to handle it.

**Comment by Christinadobrzyn** [comment] 2024-02-22 15:02
Hi! For payment, can someone help me understand who helped with creating the solution and PR?

Was it both @lakchote and @dukenv0307? If yes, what amount of compensation seems fair for the work you did? Let me know and I can discuss with @Ollyws

Also, can we move this to Daily?

**Comment by Christinadobrzyn** [comment] 2024-02-23 20:42
Thanks @hoangzinh - okay if I have this right, then we pay C+ and the contributor with our 50% regression penalty. 

@dukenv0307 & @DylanDylann what amount do you think is fair for the work you did?

**Comment by DylanDylann** [comment] 2024-02-24 03:29
@Christinadobrzyn My PR causes this regression, I am not eligible for payment here. Let's pay for @dukenv0307 only

**Comment by lakchote** [comment] 2024-02-26 13:44
@Christinadobrzyn as noted above, it should be @dukenv0307 that should be paid.

As @DylanDylann produced the regression with his PR, he's not eligible for payment.

**Comment by Christinadobrzyn** [comment] 2024-02-26 18:59
Thanks @lakchote and @DylanDylann!

@dukenv0307 what payment do you think is okay for the work you did? $250? 

Can you accept this upwork job [here](https://www.upwork.com/jobs/~01b1421b286665858e) so I can pay you?

**Comment by Christinadobrzyn** [comment] 2024-02-27 18:34
Awesome! thanks @dukenv0307! I paid you $250 in Upwork. I also ended the other contracts with @Ollyws and @DylanDylann - let me know if we need a new contract for any reason. 

Otherwise, I think this can be closed!

**Closed by Christinadobrzyn** 2024-02-27 18:34 UTC
Labels: External, Engineering, Daily, Bug
