### ISSUE TITLE
[HOLD for payment 2024-10-22] [$250] Workflow - Tapping add approval workflow or tapping back shows diff. behavior in mweb&android

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50094] opened 2024-10-02 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch both mweb and Android
2. Tap profile icon -- workspaces -- new workspace
3. Tap more features -- enable workflow
4. Tap workflow -- enable add approvals
5. Tap add approval workflow
6. Tap app back button

## Expected Result:
While tapping add approval workflow or on tapping app back button "No members to display " page must not be shown

## Actual Result:
In Android, tapping add approval workflow " No members to display " shown briefly but in mweb while tapping back button No members to display " page is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/116d6380-9b59-46f2-907f-f5f120126219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841560364430821283</li>
        <li>Upwork Job ID: 1841560364430821283</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 104312293</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by lanitochka17** [comment] 2024-10-02 18:06
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-02 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Android, tapping add approval workflow " No members to display " shown briefly but in mweb while tapping back button No members to display " page is shown

### What is the root cause of that problem?
1. For mweb, the approval flow is cleared before we complete navigating back to the previous screen then the empty screen appears briefly

https://github.com/Expensify/App/blob/f325244648646bff8fcba62e60979a530f14d2d3/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsExpensesFromPage.tsx#L149-L156

2. For Android, we merge the approval workflow data to Onyx here and then navigate to the approval screen but the data is merged after we navigate to the approval screen. So the empty screen appears briefly based on this condition [here](https://github.com/Expensify/App/blob/f325244648646bff8fcba62e60979a530f14d2d3/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsExpensesFromPage.tsx#L63)

https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L103-L109
### What changes do you think we should make in order to solve the problem?
1. For mweb bug, we should navigate back first and wrap the logic to clear approval workflow in `InteractionManager.runAfterInteractions` or use `Modal.close`

```
const goBack = useCallback(() => {
    Navigation.goBack();
    InteractionManager.runAfterInteractions(() => {
        if (!isInitialCreationFlow) {
            return;
        }
        Workflow.clearApprovalWorkflow();
    });
}, [isInitialCreationFlow]);
```
https://github.com/Expensify/App/blob/f325244648646bff8fcba62e60979a530f14d2d3/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsExpensesFromPage.tsx#L149-L156

2. For Android bug, we should navigate to the approval screen after the data is merged to Onyx completely. 

https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L103-L109

To do that we can use `set` method here which is faster because I see that we always pass full approval workflow data to this function.

https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/libs/actions/Workflow.ts#L337

Or we can return the `Onyx.merge` promise in this function then move the navigate logic to `.then` of the promise returned by `setApprovalWorkflow` function.

https://github.com/Expensify/App/blob/19a137d26fee56f913eaec7c9b896915ddb002a9/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L103-L109

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-10-03 05:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An empty state view is shown when opening/closing the approval workflow page.

### What is the root cause of that problem?
When we open the page, we will set the approval data first and then navigate to the page.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L103-L108

However, the onyx data is not immediately available which is noticeable in slower devices like Android.

And when we close the page, we clear the approval data.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsExpensesFromPage.tsx#L149-L154

### What changes do you think we should make in order to solve the problem?

For the first problem, we can use `Navigation.setNavigationActionToMicrotaskQueue` to delay the navigation.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/libs/Navigation/setNavigationActionToMicrotaskQueue.ts#L1-L5
```
Navigation.setNavigationActionToMicrotaskQueue(() => Navigation.navigate(ROUTES.WORKSPACE_WORKFLOWS_APPROVALS_EXPENSES_FROM.getRoute(route.params.policyID)));
```

For the second problem, we can delay the clearing of data using InteractionManager, just like we did here.
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/workspace/workflows/approvals/WorkspaceWorkflowsApprovalsEditPage.tsx#L63-L67

**Comment by s77rt** [comment] 2024-10-03 18:10
@cretadn22, @nkdengineer, @Nodebrute and @bernhardoj  Thank you for the proposals. The RCA makes sense in general but the not found view should only be shown if the `approvalWorkflow` data is available and we have no members.

**Comment by s77rt** [comment] 2024-10-03 18:10
@abzokhattab Thanks for the proposal. The RCA makes sense. I find your solution the easiest to implement even though it will cause blank space to appear on animation instead of the not found view but I don't think thats something that we should optimize for. Overall looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/50094#issuecomment-2389619221)

**Comment by s77rt** [comment] 2024-10-03 18:14
@abzokhattab Actually I found that the solution is not enough. We get a weird view after selecting some users and going back


https://github.com/user-attachments/assets/f1e724ae-33bc-49e1-b035-d724a9d58692

**Comment by nkdengineer** [comment] 2024-10-03 18:21
@s77rt The selected proposal is not enough because we still need to fix the approval workflow will be cleared briefly before we go back to the workflow page.

**Comment by s77rt** [comment] 2024-10-03 19:18
Since we need another "complementary" solution, I'm giving this another review:

- @cretadn22 Proposal is not complete (only handles the mWeb cause)
- @nkdengineer Let's avoid delays i.e. `InteractionManager.runAfterInteractions`
- @Nodebrute Looks good to me
- @bernhardoj both `setNavigationActionToMicrotaskQueue` and `InteractionManager.runAfterInteractions` add delays and should be avoided

**Comment by s77rt** [comment] 2024-10-03 19:21
@abzokhattab The new changes making this more complex and it feels like band-aid solution

**Comment by s77rt** [comment] 2024-10-03 19:22
@Nodebrute's proposal looks good to me

cc @stitesExpensify

**Comment by nkdengineer** [comment] 2024-10-03 20:35
> To do that we can use set method here which is faster because I see that we always pass full approval workflow data to this function.

@s77rt For the selected proposal, with the main or alternative we also need to use `set` method in `setApprovalWorkflow` function which is the key to fixing the Android native bug and I'm the first one who suggested this. For the mweb bug,  I think moving `clearApprovalWorkflow` or delaying the call of this function is fine because we don't call any API.

**Comment by s77rt** [comment] 2024-10-03 22:01
@nkdengineer I believe the key in @Nodebrute's proposal is to not call `Workflow.clearApprovalWorkflow` on going back. Using `Onyx.set` is not mandatory.

**Comment by nkdengineer** [comment] 2024-10-03 22:11
@s77rt Using Using `Onyx.set` in `setApprovalWorkflow` is mandatory to fix the Android bug.

**Comment by s77rt** [comment] 2024-10-04 14:38
@nkdengineer
> Using Onyx.set in setApprovalWorkflow is mandatory to fix the Android native bug.

Not sure that's the case based on my testings. Can you double check?

**Comment by s77rt** [comment] 2024-10-07 20:05
@stitesExpensify I think we can go ahead and assign @Nodebrute ([proposal](https://github.com/Expensify/App/issues/50094#issuecomment-2389637169))

**Comment by s77rt** [comment] 2024-10-16 17:05
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/46484
- The offending PR has been commented on: https://github.com/Expensify/App/pull/46484#discussion_r1803498236
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: No

**Comment by garrettmknight** [comment] 2024-10-23 19:19
**Payment summary:**
- Contributor: @Nodebrute $250 via NewDot
- Contributor+: @s77rt $250

**Comment by garrettmknight** [comment] 2024-10-23 19:21
Paid out in Upwork. @s77rt request when you're ready.

**Comment by tgolen** [comment] 2024-10-23 21:51
Reopening for @s77rt and @garrettmknight to complete the regression checklist.

**Comment by s77rt** [comment] 2024-10-23 22:00
@tgolen Completed here https://github.com/Expensify/App/issues/50094#issuecomment-2417422875

**Comment by tgolen** [comment] 2024-10-24 14:31
Thanks @s77rt, and apologies that I missed it. @garrettmknight can you please be sure to copy those answers into the actual checklist and then complete it out?

@s77rt Can you give a little more context behind the regression? Would you say it was caused by one of these?

- Initial design was incorrect or incomplete
- Bug introduced during implementation
- Bug caused by some unrelated change
- Other (please specify)

**Comment by s77rt** [comment] 2024-10-24 18:35
I would say it's a bug that is introduced during implementation but it could also be that the design was incorrect if it was specific about the area where the bug occurred (I don't have access to [the doc](https://docs.google.com/document/d/12X-hsNo9BBRcG5NSS1JzyjWD1w-iM0uciQJSD1i5mZc/edit) to confirm).

**Closed** 2024-11-18 10:08 UTC
Labels: External, Monthly, Awaiting Payment, Bug
