### ISSUE TITLE
Avatar - Invalid avatar format error does not disappear after switching account

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48252] opened 2024-08-29 10:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in as a copilot.
3. Go to Account settings > Profile.
4. Upload a large image that will trigger error.
5. Click on the account switcher.
6. Select another account.

## Expected Result:
The invalid avatar format error will disappear after switching account.

## Actual Result:
The invalid avatar format error does not disappear after switching account.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/95b5bc0c-f749-4ce4-b084-cb3c95b2d551

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by etCoderDysto** [comment] 2024-08-29 11:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Invalid avatar format error does not disappear after switching account
### What is the root cause of that problem?
We are only reseting error message on blur here
https://github.com/Expensify/App/blob/8c69c58dfa7f6a9ab079e560ff026c1aed12be8e/src/components/AvatarWithImagePicker.tsx#L187-L194
And when the user changes current user (`currentUserPersonalDetails`) we don't reset error message 
### What changes do you think we should make in order to solve the problem?
We should also reset error message when `source` (`currentUserPersonalDetails?.avatar`) for `Avatar` component changes. 

```
 useEffect(() => {
        setError(null, {});
    }, [source]);
```

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2024-08-29 14:18
demoting since copilot is under beta cc @rushatgabhane

**Comment by madmax330** [comment] 2024-09-02 12:55
@puneetlath @rushatgabhane should I make this external? Or is this part of a project?

**Comment by puneetlath** [comment] 2024-09-03 17:47
It looks like it's part of the copilot project that is being worked on in #wave-control. I'm not sure who his working on that, but you should be able to ask there.

**Comment by rushatgabhane** [comment] 2024-09-03 17:49
@puneetlath please assign it to me there is s mega PR on the way

**Comment by VictoriaExpensify** [comment] 2024-09-06 01:23
Hey @puneetlath - is this a deploy blocker? Just trying to figure out what actions I need to take here.

**Comment by puneetlath** [comment] 2024-09-06 17:35
No, I think copilot is still under beta, so not a blocker.

**Closed** 2024-12-11 09:20 UTC
Labels: Reviewing, Engineering, Monthly, Bug
