### ISSUE TITLE
[HOLD for payment 2024-05-03] [$250] Room - Description Error Message is overlapped by highlight

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#40519] opened 2024-04-18 23:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** No, new feature to show the error message
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Go to "Start Chat" > Room
4. Input a very long room description like:

```
# we can close this to focus on more urgent issue this is just a minor viewing discrepancy

~we can close this to focus on more urgent issue this is just a minor viewing discrepancy~

we can close this to focus on more urgent issue this is just a minor viewing discrepancy

> *we can close this to focus on more urgent issue this is just a minor viewing discrepancy*

> *we can close this to focus on more urgent issue this is just a minor viewing discrepancy*"
```

5. Highlight the workspace name section on Web or Desktop
## Expected Result:
User expects the highlight to NOT interfere with the error message

## Actual Result:
The highlight is overlapping the error message

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img width="1440" alt="Bug6454141_1713466575372!Highlight_overlapping_error_message_" src="https://github.com/Expensify/App/assets/43996225/056671d9-5f13-4314-ab44-495f8c3d9b7e">

https://github.com/Expensify/App/assets/43996225/fa06905f-045a-457f-b043-af6564b9c2ee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016751dd795b5647cd</li>
        <li>Upwork Job ID: 1782572739401596928</li>
        <li>Last Price Increase: 2024-04-23</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-04-18 23:04
We think this bug might be related to #vip-vsb

**Comment by kavimuru** [comment] 2024-04-18 23:04
@trjExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by neonbhai** [comment] 2024-04-18 23:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room - Description Error Message is overlapped by highlight 

### What is the root cause of that problem?
We need space for the error message to render without overlapping in the view here:
https://github.com/Expensify/App/blob/f33a5a43fd1b5afe7f0a5153fea36f3ba1ee0939/src/pages/workspace/WorkspaceNewRoomPage.tsx#L286-L299


### What changes do you think we should make in order to solve the problem?
We will increase the margin here to make more space between the elements:

https://github.com/Expensify/App/blob/f33a5a43fd1b5afe7f0a5153fea36f3ba1ee0939/src/pages/workspace/WorkspaceNewRoomPage.tsx#L286

**Comment by thienlnam** [comment] 2024-04-18 23:11
Doesn't seem like this needs to be a blocker since it only happens if you max out the description

**Comment by bernhardoj** [comment] 2024-04-19 09:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room description error message is overlapped with the workspace field highlight.

### What is the root cause of that problem?
We set the containerStyle of the description field with a maxHeight of 115.
https://github.com/Expensify/App/blob/bec1c8ebfe8ca80716b2909049026219149877ce/src/pages/workspace/WorkspaceNewRoomPage.tsx#L296

The containerStyle is applied to this View which contains the text input and the error message
https://github.com/Expensify/App/blob/bec1c8ebfe8ca80716b2909049026219149877ce/src/components/TextInput/BaseTextInput/index.tsx#L287-L290

```
<View>
    <Input>
    <ErrorMessage>
</View>
```

The maxHeight from containerStyle is also being used to set the max height for the input height itself. So, when the input reaches its max height and the error shows, the error message will overlap with the element below it.

### What changes do you think we should make in order to solve the problem?

I think we shouldn't pass the max height of the auto grow height to the containerStyle as they are being used differently. So, I propose to have a new props called `maxAutoGrowHeight` and we start passing the max height to the new props.

`maxAutoGrowHeight={115}`

Then, we can replace all usages of `maxHeight` with `maxAutoGrowHeight` in BaseTextInput component.

**Comment by trjExpensify** [comment] 2024-04-23 00:54
CC: @jasperhuangg for vis, looks like your PR was being previewed in the OP on this.

**Comment by Pujan92** [comment] 2024-04-23 16:43
Thanks for the proposals.

@Krishna2323 and @tienifr proposed adjusting margin-bottom/max-height by considering an error message to be of a single line. But the error message can be longer so their proposals aren't solving the issue at the root level. Though @tienifr mentioned calculating error text height dynamically, I don't think it is the best approach here.

According to me, we should not restrict the container height as it is also responsible for rendering the error message which is correctly pointed out in @bernhardoj's [proposal](https://github.com/Expensify/App/issues/40519#issuecomment-2066160811). We can move here with @bernhardoj's proposal where they suggested passing a new prop `maxAutoGrowHeight` which will be responsible for controlling height excluding the container View.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-04-24 04:33
PR is ready

cc: @Pujan92

**Comment by Pujan92** [comment] 2024-05-05 12:09
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28453
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28453/files#r1590294940
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. Yes
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
 
 ### Regression Test Steps
 
1. Open a new room page
2. Enter a long description until it exceeds the max characters limitation
3. Verify the error shown doesn't overlap with the other bottom content

**Comment by trjExpensify** [comment] 2024-05-07 09:53
It's a pretty niche bug to get to the max character limit with a description input, so I'm going to forgo the regression test for this. 

Payment summary as follows: 

- $250 to @bernhardoj for the fix
- $250 to @Pujan92 for the C+ review

Paid, closing.. thanks ya'll!

**Closed by trjExpensify** 2024-05-07 09:53 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
