### ISSUE TITLE
[$500] MEDIUM: Web - Request money is not displayed in recent messages it was included in a previous request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36501] opened 2024-02-14 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.41-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34956

## Action Performed:
1. Go to the Request money and complete the flow
2. Send some messages
3. Again go to the Request money and complete the flow

## Expected Result:
The money request should stay in it's original position, rather than move to be the latest message and then 'jupm back' to the original request. 

## Actual Result:
The updated request is posted as the latest message, but then jumps back

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/730afd81-f593-40c4-bda9-2dc3bc2abbef

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c538fb94ad8a386f</li>
        <li>Upwork Job ID: 1757780741151125504</li>
        <li>Last Price Increase: 2024-02-28</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 14:56
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by bfitzexpensify** [comment] 2024-02-15 06:01
Hey @SzymczakJ - this was discovered while reviewing your PR (https://github.com/Expensify/App/pull/34956) - do you think it's related?

**Comment by allroundexperts** [comment] 2024-02-17 03:45
Looking for proposals.

**Comment by bfitzexpensify** [comment] 2024-02-19 08:26
Still waiting on proposals

**Comment by bfitzexpensify** [comment] 2024-02-21 06:00
Still awaiting proposals

**Comment by bfitzexpensify** [comment] 2024-02-22 05:30
Discussing in [this](https://expensify.slack.com/archives/C05RECHFBEW/p1708495216982349) thread - looks like it's linked to https://github.com/Expensify/Expensify/issues/361539

**Comment by s101d1** [comment] 2024-02-25 01:06
I am not really clear about the Expected Result ("Newly requested money should not include in a previous request message"). Does it mean the updated `"<user> owes <amount>..."` message should be repositioned as the latest/recent message?

Let's say the current chats/messages is like this initially:

```
* lorem ipsum
* "<user> owes $1000..."
* hello world
* asdf
```
So the "asdf" text is currently the last/recent message.

And then the user adds a new `Request Money` with amount $500 (which should update the amount value in the previous `"<user> owes <amount>..."` message).

In that case, should the messages ordering change into like this?

```
* lorem ipsum
* hello world
* asdf
* "<user> owes $1500..."
```

Or should the new `Request Money` with $500 be added as a new/last message instead? (so the amount in the previous `"<user> owes <amount>..."` message is unchanged, which means each `Request Money` message are shown separately instead of being merged)

```
* lorem ipsum
* "<user> owes $1000..."
* hello world
* asdf
* "<user> owes $500..."
```

**Comment by bfitzexpensify** [comment] 2024-02-27 01:11
@s101d1 this is correct:

Let's say the current chats/messages is like this initially:

```
* lorem ipsum
* "<user> owes $1000..."
* hello world
* asdf
```
So the "asdf" text is currently the last/recent message.

And then the user adds a new `Request Money` with amount $500 (which should update the amount value in the previous `"<user> owes <amount>..."` message).

In that case, should the messages ordering change into like this?

```
* lorem ipsum
* hello world
* asdf
* "<user> owes $1500..."
```

Updating the OP to make that clearer, too

**Comment by s101d1** [comment] 2024-02-28 14:12
From my finding, this seems like a backend/API issue. The chats/messages are sorted by `created` field, and when the new Request Money is sent, the backend/API will return `response.onyxData` that contains updated chat/message records (or `reportActions` Onyx data in coding terms I guess) and the front-end will apply/write that `response.onyxData` to the local database.

Looks like the Request Money API (`/api?command=RequestMoney`) doesn't update the `"<user> owes $$$..."` message's `created` field correctly to current datetime value when the Request Money is executed, so the `created` field will still point to the original created date value, that's why the updated `"<user> owes $$$..."` message will still be in the original position instead of being moved to last/recent position.

**Comment by bfitzexpensify** [comment] 2024-03-01 02:28
@allroundexperts do you agree with @s101d1's [comment](https://github.com/Expensify/App/issues/36501#issuecomment-1969070508) that this is a BE issue?

**Comment by Tony-MK** [comment] 2024-03-01 03:06
The backend response for `created`

![Screenshot 2024-03-01 at 06 03 37](https://github.com/Expensify/App/assets/22982173/3e0b60df-0f7a-4147-84a5-2cd362062fd1)

**Comment by Tony-MK** [comment] 2024-03-01 03:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Request money is not displayed in recent messages it was included in a previous request.

### What is the root cause of that problem?

The frontend and backend response for `requestMoney` does not alter the [`created`](https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L223) attribute for the `REPORTPREVIEW` action according to the creation of the last IOU action. 

**Note:** The `api?command=splitBill` has the same issue for the `REPORTPREVIEW` action but not for the `IOU` split bill action.

**`requestMoney` Response**

![](https://github.com/Expensify/App/assets/22982173/3e0b60df-0f7a-4147-84a5-2cd362062fd1)

Since [`created`](https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L223) will not change the [`getSortedReportActions`](ht,tps://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L213C10-L213C32) function will not change the position of the `REPORTPREVIEW` action in the [`sortedActions`](https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L220C11-L220C24) array.

https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L222-L224

### What changes do you think we should make in order to solve the problem?

If we decide to fix this issue from the backend, it is crucial that we *optimistically* set `created` for the `REPORTPREVIEW` action from the frontend.

The reason is that the user will end up still experiencing this issue offline or for a couple of seconds before the backend responds to the `requestMoney` request. 

In the [`ReportUtils.updateReportPreview`](https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportUtils.ts#L3328) function, we should use the [`DateUtils.getDBTime`](https://github.com/Tony-MK/Expensify-App/blob/8392eeee67f22e8f861dd81da872711b4a59b893/src/libs/DateUtils.ts#L372) function to get the correct time offline to set `created` before this [line of code](https://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportUtils.ts#L3328
).

### What alternative solutions did you explore? (Optional)

In the [`getSortedReportActions`](ht,tps://github.com/Expensify/App/blob/48657b48505e40fecc7c6f43da903aadb12d549a/src/libs/ReportActionsUtils.ts#L213C10-L213C32), we can create an expectation for `REPORTPREVIEW` action ton instead consider the `lastIOUAction` rather than using the outdated `created` value.

Frankly, I do not think `created` should be altered.

Hence, we can use the `lastIOUAction` or `REPORTPREVIEW` action to give more accurate date and time of the last IOU-created action.

**`requestMoney` response for `lastIOUAction`**

![](https://github.com/Expensify/App/assets/22982173/a79a11db-2b62-4aed-ab98-1544e9566460)

**Comment by allroundexperts** [comment] 2024-03-01 08:38
This is expected and not a bug. We recently changed the logic such that the request money message remained at its original position. https://github.com/Expensify/App/issues/36582#issuecomment-1951629701

**Comment by bfitzexpensify** [comment] 2024-03-04 01:05
Thanks for that context @allroundexperts. I still think there is a bug here, as the request money doesn't remain at its original position - rather, it is added at the bottom of the chat and then jumps back, rather than remaining where it was. Updated the OP. 

Little more context from Slack that might be helpful:

>Yeah I think this is because we did not implement the changes to stop report preview moving in front end yet. so optimistically we still moved the report preview but then server response has corrected it and move it back to the original place.

**Comment by s101d1** [comment] 2024-03-04 16:59
The `"<user> owes $$$..."` message went to last position briefly because the optimistic data in the API call contains the `"<user> owes $$$..."` message's `created` field that's set to current date (when the Request Money is submitted). The optimistic data will be applied to local data before eventually the `response.onyxData` (which the message's `created` value contains the correct original date) from the API will overwrite that data, thus causing the visual appearance of brief message jumping.

There are multiple places in the code that sets the `created` to current date for the Request Money operation, and from my finding, this is the last place where the `created` is set to current date for optimistic data:

https://github.com/Expensify/App/blob/1.4.41-3/src/libs/ReportUtils.ts#L3239

However, in `staging` and `main` branch, this line of code had been removed:

https://github.com/Expensify/App/blob/staging/src/libs/ReportUtils.ts#L3319

So you may want to re-test this issue, perhaps it had been fixed by someone else.

**Comment by s101d1** [comment] 2024-03-04 17:21
I didn't see any brief message jump anymore in the `staging` branch app, perhaps this issue had been fixed by someone else?

**Comment by bfitzexpensify** [comment] 2024-03-06 00:37
Asking QA to retest via https://expensify.slack.com/archives/C9YU7BX5M/p1709685428204289

**Comment by kavimuru** [comment] 2024-03-06 01:25
I don't see any jumping of the request sent after the messages, but the total IOU request appears above the messages sent. 

https://github.com/Expensify/App/assets/43996225/e3333fa8-ae07-4f52-a952-168684ce3759

**Comment by bfitzexpensify** [comment] 2024-03-06 02:06
Thanks @kavimuru! 

@allroundexperts clarified in https://github.com/Expensify/App/issues/36501#issuecomment-1972751124 that the request remaining above the most recent messages is intentional. 

The jumping around was the only remaining bug, so this is now resolved and we can close this out.

**Closed by bfitzexpensify** 2024-03-06 02:06 UTC
Labels: External, Daily, Help Wanted, Bug
