### ISSUE TITLE
[$500] Profile - WS avatar is removed & default avatar displayed in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33555] opened 2023-12-23 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition : User has already uploaded WS avatar
1. Navigate to staging.new.expensify.com
2. Log in with gmail account
3. Tap settings icon
4. Select Workspaces >> select any WS >> Settings option
5. Disable the internet connection in the device

## Expected Result:
Uploaded WS avatar should be retained in WS settings when device go offline mode

## Actual Result:
WS avatar is removed & default avatar displayed when device go offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a131db80-2856-4dbc-84e0-cc3a6ad4948b

![Bug6325080_1703357825848!IMG_1224](https://github.com/Expensify/App/assets/78819774/c234ee0e-f2fb-4952-bc8a-ab9566f74b0a)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01593851a4111a6fd5</li>
        <li>Upwork Job ID: 1738682083833532416</li>
        <li>Last Price Increase: 2023-12-23</li>
    </ul>
</details>

**Comment by MrOttimista** [comment] 2023-12-24 02:37
## Proposal:

**What is the problem:** 
When the application goes offline, the whole component gets rendered...  Why? becauseof the `src/components/OfflineWithFeedback.tsx` component. it makes its children rerender if there when we toggle the network. 

 Why the image is hidden when the component is rendered? 
it tries to get the image but there is no internet so it displays the default icon. 
as we can see in the image below => it tries to get the image after it goes offline but it fails 
![image](https://github.com/Expensify/App/assets/40366999/aaa382e5-ff97-4452-b8c8-1bfc6ef40750)


---
Solution: 

There are 3 solutions: 

Solution 1 : 
- cache the image request, so when it tries to fetch it again => it will be there. 

Solution 2: 
- memoize the avatar and make it re-render only if there is a change in the props `image source`

Solution 3: 
- don't let the `OfflineWithFeedback` component re-render its children when it is not necessary 


I prefer to do 1 and 3 together

**Comment by MrOttimista** [comment] 2023-12-24 02:40
## Proposal:

**What is the problem:** 
When the application goes offline, the whole component gets rendered...  Why? becauseof the `src/components/OfflineWithFeedback.tsx` component. it makes its children rerender if there when we toggle the network. 

 Why the image is hidden when the component is rendered? 
it tries to get the image but there is no internet so it displays the default icon. 
as we can see in the image below => it tries to get the image after it goes offline but it fails 
![image](https://github.com/Expensify/App/assets/40366999/aaa382e5-ff97-4452-b8c8-1bfc6ef40750)


---
Solution: 

There are 3 solutions: 

Solution 1 : 
- cache the image request, so when it tries to fetch it again => it will be there. 

Solution 2: 
- memoize the avatar and make it re-render only if there is a change in the props `image source`

Solution 3: 
- don't let the `OfflineWithFeedback` component re-render its children when it is not necessary 


I prefer to do 1 and 3 together 

---

Your Expensify account email: adel.mohamed855@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/adelemad3

**Comment by MrOttimista** [comment] 2023-12-24 02:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile - WS avatar is removed & default avatar displayed in offline mode

### What is the root cause of that problem?

When the application goes offline, the whole component gets rendered...  Why? because of the `src/components/OfflineWithFeedback.tsx` component. it makes its children rerender if there when we toggle the network. 

Why the image is hidden when the component is rendered? 
it tries to get the image but there is no internet so it displays the default icon. 
as we can see in the image below => it tries to get the image after it goes offline but it fails 
![image](https://github.com/Expensify/App/assets/40366999/aaa382e5-ff97-4452-b8c8-1bfc6ef40750)

### What changes do you think we should make in order to solve the problem?


There are 3 solutions: 

Solution 1 : 
- cache the image request, so when it tries to fetch it again => it will be there. 

Solution 2: 
- memoize the avatar and make it re-render only if there is a change in the props `image source`

Solution 3: 
- don't let the `OfflineWithFeedback` component re-render its children when it is not necessary 


I prefer to do 1 and 3 together 


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.



---

Your Expensify account email: adel.mohamed855@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/adelemad3

**Comment by shahinyan11** [comment] 2023-12-24 08:50
It is not a bug. It is a new feature . Because we use live url to display images. To achieve the desired behavior, we need to add functionality to download images and save them locally.

**Comment by bfitzexpensify** [comment] 2023-12-25 19:02
Yes, this doesn't feel buggy - if I were to go offline, I don't think it's unexpected that the avatar wouldn't be accessible. Going to close this out.

**Closed by bfitzexpensify** 2023-12-25 19:02 UTC
Labels: External, Daily, Help Wanted, Bug
