### ISSUE TITLE
[$500] Connect Bank - Back button doesn't work while moving from step 2 to 3 in connect bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28082] opened 2023-09-23 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace-> bank account
3. If previous setup is present then start over
4. Click on connect manually
5. Fill in details in step 1 and step 2 and continue
6. While step 3 is loading, click on back
7. Observe that it still takes us to step 3

## Expected Result:
While loading step 3 and click on back, app should take us back to step 2 in connect bank account

## Actual Result:
 Back button doesn't work while moving from step 2 to 3 in connect bank account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4e12db1a-4d3f-4f94-9709-374ed902bbfc

https://github.com/Expensify/App/assets/93399543/2c528c4d-2015-49ff-a288-ab3f875fd592

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695372245139449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018a0cfcc7d3a55c4b</li>
        <li>Upwork Job ID: 1705673191298117632</li>
        <li>Last Price Increase: 2023-09-23</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-23 19:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Back button doesn't work while moving from step 2 to 3 in connect bank account

### What is the root cause of that problem?
- Currently, when user is in **CompanyStep**, then clicking on submit "Save & Continue" button, and while the loading indicator screen is displayed, clicking on back button, there are main steps:
1. Call the API to submit data that is inputted in **CompanyStep**
2. Set the isLoading to true and waiting for the API done
3. Because isLoading is true, it will display the loading indicator screen ```<ReimbursementAccountLoadingIndicator />```
4. After API done, set isLoading to false, and API `s response contains what is the next step, and in this case, it is **CompanyStep**. Below is the data returned by this API:
```
 {
        "onyxMethod": "merge",
        "key": "reimbursementAccount",
        "value": {
            "achData": {
                "currentStep": "RequestorStep",
                "bankAccountID": 2100319
            },
            "errors": null
        }
    }
```
5. Set the current step to **CompanyStep** based on the API `s response and render the **RequestorStep** screen 

- So we can see that in step 5, It always displays the **RequestorStep** regardless user has clicked on back button or not

### What changes do you think we should make in order to solve the problem?
- When user clicks on back button while the loading indicator screen is displaying, we should cancel the current API call, clear state (if necessary) end then navigate to the previous step like below:
```
goBack() {
            ...
            case CONST.BANK_ACCOUNT.STEP.COMPANY:
                if (!isLoadingIndicatorOpen) {
                    BankAccounts.goToWithdrawalAccountSetupStep(CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT, {subStep: CONST.BANK_ACCOUNT.SUBSTEP.MANUAL});
                } else {
                    Onyx.merge(ONYXKEYS.REIMBURSEMENT_ACCOUNT, {
                        isLoading: false,
                        errors: null,
                    });
                    BankAccounts.clearOnfidoToken();
                    HttpUtils.cancelPendingRequests();
                }

                break;
```
- In the above, isLoadingIndicatorOpen used to check whether the loading indicator is played or not. We cancel the API by ``` HttpUtils.cancelPendingRequests()``` and clear a few states like isLoading, onfidoToken, ...
- This bug appear with others steps as well, so we should apply the above solution for these steps 
### What alternative solutions did you explore? (Optional)
- We can just disable the back button when the loading indicator screen is displayed

### Result
[Screencast from 23-09-2023 12:42:18.webm](https://github.com/Expensify/App/assets/141406735/db745cd8-fd8e-4e39-a4a2-f449ae8048e3)

**Comment by akinwale** [comment] 2023-09-24 00:43
This is a duplicate of https://github.com/Expensify/App/issues/24635.

**Closed** 2023-09-27 03:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
