### ISSUE TITLE
Distance - Distance field does not show "Pending" after changing distance offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46952] opened 2024-08-07 10:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4827863
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a distance expense with three waypoints.
4. Go to transaction thread.
5. Go offline.
6. Click Distance.
7. Remove one waypoint and save it.

## Expected Result:
The Distance row will show "Pending".

## Actual Result:
The Distance row still shows the previous distance instead of "Pending".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f283467a-28b2-446e-94b6-e3e588206330

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-07 10:07
We think that this bug might be related to #wave-collect - Release 1

**Comment by trjExpensify** [comment] 2024-08-07 11:27
Discussing with @paultsimura [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1723029611586059).

**Comment by trjExpensify** [comment] 2024-08-07 11:57
Thanks! Under the regression period, assigning back to @parasharrajat and @bernhardoj, though Bernhard I need you to comment please. :)

**Comment by trjExpensify** [comment] 2024-08-07 11:59
@paultsimura confirming this is a bug only on the `p2pDistanceRequests` beta, so it shouldn't be a deploy blocker, right?

**Comment by trjExpensify** [comment] 2024-08-07 12:28
Thanks, demoting. @bernhardoj please follow up and fix this!

**Comment by bernhardoj** [comment] 2024-08-07 12:51
The root cause of the issue is actually not directly related to the PR. We already have a logic here to show Pending... if the distance is 0 or doesn't exist.
https://github.com/Expensify/App/blob/f9306d578f42140729646bbe94417266a0e1a3c4/src/libs/DistanceRequestUtils.ts#L164-L167

The distance comes from either `customUnit.quantity` or `routes.route0.distance`. However, when we remove the waypoint, we don't clear the `customUnit.quantity`.

https://github.com/Expensify/App/blob/f9306d578f42140729646bbe94417266a0e1a3c4/src/libs/actions/Transaction.ts#L161-L191

But we did remove it when adding waypoints.
https://github.com/Expensify/App/blob/f9306d578f42140729646bbe94417266a0e1a3c4/src/libs/actions/Transaction.ts#L85-L113

That's why the issue doesn't happen when adding waypoint while offline. This issue just became apparent after my PR. Previously, we shows Pending when updating the waypoint even if the distance value is already updated. Now, Pending will only show if the distance value is not available yet.

I have open a new PR to address this issue without breaking https://github.com/Expensify/App/issues/43569

**Comment by bernhardoj** [comment] 2024-08-31 01:30
We can close this one

**Closed** 2024-10-29 18:24 UTC
Labels: Reviewing, Engineering, Monthly, Bug
