### ISSUE TITLE
[$500]  IOU - New green line appears when delete second IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35211] opened 2024-01-25 23:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.32-2
**Reproducible in staging?:**Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34011
## Action Performed:
1. Go to FAB> Request money>
2. Request money from a user that has no existing chat
3. Click on + button> Request Money> Complete the IOU flow
4. Delete the last created IOU
5. Navigate back to the conversation

## Expected Result:
Green line should not appears since there is no new message

## Actual Result:
New green line appears when delete second IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fd6caafc-e53b-415f-a496-afbcb174122c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa6428b2af1b32c9</li>
        <li>Upwork Job ID: 1750655802310635520</li>
        <li>Last Price Increase: 2024-01-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-25 23:04
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by cjoshi-zeals** [comment] 2024-01-26 05:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new green line appears when deleting second IOU

### What is the root cause of that problem?
For displaying the new line marker we have a prop  `shouldDisplayNewMarker` which is a combination of a lot of conditions.

To not display the green line we need to remove , i have tested and it wont impact any other things in the App and it will fix the issue as well

` _.isEqual(prevProps.report.isDeletedParentAction, nextProps.report.isDeletedParentAction) `


### What changes do you think we should make in order to solve the problem?

Need to  remove the condition i have specified above to make sure it is fixed

### What alternative solutions did you explore? (Optional)
NA

**Comment by twisterdotcom** [comment] 2024-01-26 10:38
Gonna put this in #vip-vsp then. @jjcoffee, @dukenv0307 and @cjoshi-zeals - are sure this shouldn't be a BE change like https://github.com/Expensify/App/issues/34190 as well?

**Comment by cjoshi-zeals** [comment] 2024-01-26 14:58
> Gonna put this in #vip-vsp then. @jjcoffee, @dukenv0307 and @cjoshi-zeals - are sure this shouldn't be a BE change like https://github.com/Expensify/App/issues/34190 as well?

@twisterdotcom 
Yes i am pretty sure it wont require any BE changes.

**Comment by jjcoffee** [comment] 2024-01-29 15:38
This appears to be mostly a BE issue as @dukenv0307 points out in their [proposal](https://github.com/Expensify/App/issues/35211#issuecomment-1911490753) (the unread indicator also doesn't show if performing the same action offline).

> the back-end will send back a created field that is of current timestamp, as if the REPORTPREVIEW was recently created. That timestamp is larger than the last read time of the chat report, so the new green line shows.

I'd say it's also worth fixing the adjacent issue mentioned in the proposal, where ideally the reportPreview should move back up in the chat to its original location.

@cjoshi-zeals Thanks for the proposal, though it could use more detail (see the proposal above for a better example, note that there are links to relevant portions of code that are being referred to). I'm not convinced that removing the condition you mention fixes this issue without causing any regressions.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by lakchote** [comment] 2024-01-30 10:56
I do agree with @jjcoffee, it's mostly a BE issue and should not be handled only in frontend.

We should definitely update the `created` field to reflect the correct timestamp of the last IOU request before deletion.

I'll handle the backend changes and the frontend changes it'll be easier for me to handle both. 
@dukenv0307 thanks for your proposal, you should have 25% of the reward (cc @twisterdotcom).

**Comment by twisterdotcom** [comment] 2024-01-30 12:24
Cool, so @lakchote will push the BE and FE PRs. We'll pay @dukenv0307 $125 for their solution assuming no regression.

**Comment by lakchote** [comment] 2024-01-31 09:55
It was easier for me to already make the couple lines frontend changes to confirm the backend fix works as expected.



> > Cool, so @lakchote will push the BE and FE PRs. We'll pay @dukenv0307 $125 for their solution assuming no regression.
> 
> @twisterdotcom Sorry I believe in this case usually the contributor will be raising the front-end PR and gets the full reward 😄
> 
> I see @lakchote already raised [the PR](https://github.com/Expensify/App/pull/35405) so maybe we can just stick with that, but I think 50% reward is more fair since both the back-end and front-end use my suggested solutions, just that I was not the one (given the chance to) raising the PR...

It was easier for me to already make the couple lines frontend changes to confirm the backend fix works as expected.
Also the majority of the changes are backend related. They are not just one line changes and they also include tests as well.

For these reasons and after gathering external feedback on the matter, I still think 25% of the amount is fair.

**Comment by marcaaron** [comment] 2024-02-06 00:55
>ideally the reportPreview should move back up in the chat to its original location

How did we determine that this is the expected behavior? @JmillsExpensify @mountiny what do you guys think? Should we be moving the report preview component backwards when they are deleted? Or would it move to the bottom because it was "updated"?

**Comment by mountiny** [comment] 2024-02-06 13:38
>  what do you guys think? Should we be moving the report preview component backwards when they are deleted? Or would it move to the bottom because it was "updated"?

Nope I dont think we should move it backwards, quite contrary the deletion is "latest" action done to the expense report so the total changes and attention of the user might be desired so moving it to latest makes more sense than backwards. 

But I think not moving it in this case is also fine (if that is what happens now)

**Comment by twisterdotcom** [comment] 2024-02-28 12:46
How is this going @dukenv0307?

**Comment by twisterdotcom** [comment] 2024-02-29 14:20
Of course! I forgot about this issue. Okay, yeah I see we discussed this here: https://github.com/Expensify/App/issues/35211#issuecomment-1916732326. Sorry for the bump. Now... @lakchote! How we doing??

**Comment by lakchote** [comment] 2024-03-04 15:08
> Of course! I forgot about this issue. Okay, yeah I see we discussed this here: [#35211 (comment)](https://github.com/Expensify/App/issues/35211#issuecomment-1916732326). Sorry for the bump. Now... @lakchote! How we doing??

The solution suggested by @dukenv0307 did not fit as I had to revert the PR. See @mountiny  comment [here](https://github.com/Expensify/App/issues/35211#issuecomment-1929646300), we don't want to revert the `created` action timestamp (further internal discussion ).

It has been handled internally in wave 5 with a different solution (see [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1707229461365709).
So for this reason, I don't think you should be eligible for payment on this one @dukenv0307? I let @twisterdotcom handle this.

**Comment by twisterdotcom** [comment] 2024-03-06 16:45
@lakchote okay, given the solution we were going to pay for wasn't the solution anyway, I think we should just close. I hope you understand this too @dukenv0307!

**Closed by twisterdotcom** 2024-03-06 16:45 UTC
Labels: Reviewing, Weekly, Internal, Bug
