### ISSUE TITLE
Expense Details - Header of conversation does not display `[Amount] for [Merchant`

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50018] opened 2024-10-01 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5023024
**Email or phone of affected tester (no customers):** biruknew45+1294@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace.
3. Navigate to the workspace chat.
4. Submit an expense, add a merchant, and complete the flow.
5. Click on the expense preview.

## Expected Result:
The header should display the format "[Amount] for [Merchant]."

## Actual Result:
The header only shows a generic report title, such as "Expense Report #4367516057538636," without displaying the amount or merchant.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d174b1cb-7a0a-4cf2-9c39-096e8d0890e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment] 2024-10-02 04:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header of conversation does not display [Amount] for [Merchant]
### What is the root cause of that problem?
When we create a new workspace, the title field is always enabled then the `report.reportName` is returned here.

https://github.com/Expensify/App/blob/7dde09e01e77ba55a79d043847b7ff86c5c1d1fd/src/libs/ReportUtils.ts#L2898-L2900
### What changes do you think we should make in order to solve the problem?
We should add the check not to return `report.reportName` if the report field feature is not enabled

```
if (titleReportField && report?.reportName && isPaidGroupPolicyExpenseReport(report) && policy?.areReportFieldsEnabled) { 
   return report.reportName; 
} 
```

https://github.com/Expensify/App/blob/7dde09e01e77ba55a79d043847b7ff86c5c1d1fd/src/libs/ReportUtils.ts#L2898-L2900

We can check for other places that we use the report field data and it has the same problem.

OPTIONAL: We can create a util to check the report field is enabled or not then we can use this in other places.
### What alternative solutions did you explore? (Optional)

**Comment by Siraj01576** [comment] 2024-10-02 09:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The conversation header does not display the correct [Amount] for [Merchant].

### What is the root cause of that problem?
The problem occurs because when a new workspace is created, the title field is always enabled, causing `report.reportName` to be returned. This happens regardless of whether report fields are enabled or not.

In the following code (Lines 2898 to 2900) from [ReportUtils.ts](https://github.com/Expensify/App/blob/7dde09e01e77ba55a79d043847b7ff86c5c1d1fd/src/libs/ReportUtils.ts):

```javascript
if (titleReportField && report?.reportName && isPaidGroupPolicyExpenseReport(report)) { 
    return report.reportName; 
}
```

This results in the report name being returned, even when the report fields feature is disabled.

### What changes do you think we should make in order to solve the problem?
To fix this, we should update the condition to ensure report.reportName is not returned if the report fields feature is disabled.

#### Here’s the revised condition:

```javascript
if (titleReportField && report?.reportName && isPaidGroupPolicyExpenseReport(report) && policy?.areReportFieldsEnabled) { 
    return report.reportName; 
}
```

This change ensures that report.reportName is only returned when both the titleReportField is enabled and the policy.areReportFieldsEnabled condition is met.

### Additional Considerations

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:54
Moving this back to daily and evaluating today. The PR above was incorrectly opened. So we still need to triage this, and then review proposals (if we decide to fix it).

**Comment by joekaufmanexpensify** [comment] 2024-10-07 21:54
[Discussing ](https://expensify.slack.com/archives/C03U7DCU4/p1728338086929649)

**Comment by joekaufmanexpensify** [comment] 2024-10-08 13:43
Thinking might be related to the above issue. Discussing there.

**Comment by joekaufmanexpensify** [comment] 2024-10-09 17:49
We decided this is a dupe of the above. Closing!

**Closed by joekaufmanexpensify** 2024-10-09 17:49 UTC
Labels: Daily, Bug
