### ISSUE TITLE
Android - Chat - App crashed after send a emoji

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10759] opened 2022-09-01 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Select any user
4. Tap on emoji face
5 Pick one and send it
6. Select another one and send it

## Expected Result:
Able to send emoji

## Actual Result:
App crashed after send a emoji

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.1.96.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/187987519-541a6702-f174-4dba-a164-b822da27a07e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-09-01 19:34
Got this error in dev:

```
 ERROR  Warning: Encountered two children with the same key, `undefined`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in RCTView (at View.js:32)
    in View (at ScrollView.js:1681)
    in RCTScrollView (at ScrollView.js:1799)
    in ScrollView (at ScrollView.js:1825)
    in ScrollView (at VirtualizedList.js:1348)
    in VirtualizedListContextProvider (at VirtualizedList.js:1179)
    in VirtualizedList (at FlatList.js:659)
    in FlatList (at BaseInvertedFlatList.js:143)
    in BaseInvertedFlatList (at BaseInvertedFlatList.js:169)
    in _c (at InvertedFlatList/index.android.js:5)
    in _c (at ReportActionsList.js:181)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at ReportActionsList.js:180)
    in ReportActionsList (at createOnyxContext.js:39)
    in withPersonalDetails(ReportActionsList) (at withWindowDimensions.js:92)
    in withWindowDimensions(withPersonalDetails(ReportActionsList)) (at withWindowDimensions.js:110)
    in Unknown (at withDrawerState.js:15)
    in withDrawerState(Component) (at withDrawerState.js:36)
    in Unknown (at ReportActionsView.js:358)
    in ReportActionsView (at createOnyxContext.js:39)
    in withNetwork(ReportActionsView) (at withLocalize.js:167)
    in withLocalize(withNetwork(ReportActionsView)) (at withDrawerState.js:15)
    in withDrawerState(withLocalize(withNetwork(ReportActionsView))) (at withDrawerState.js:36)
    in Unknown (at withWindowDimensions.js:92)
    in withWindowDimensions(Component) (at withWindowDimensions.js:110)
    in Unknown (at ReportScreen.js:248)
    in RCTView (at View.js:32)
    in View (at ReportScreen.js:236)
    in RCTView (at View.js:32)
    in View (at KeyboardAvoidingView.js:220)
    in LoginKeyboardAvoidingView (at BaseScreenWrapper.js:80)
    in RCTView (at View.js:32)
    in View (at BaseScreenWrapper.js:73)
    in BaseScreenWrapper (at createOnyxContext.js:39)
    in withNetwork(BaseScreenWrapper) (at withOnyx.js:173)
    in withOnyx(withNetwork(BaseScreenWrapper)) (at withOnyx.js:197)
    in Unknown (at withWindowDimensions.js:92)
    in withWindowDimensions(Component) (at withWindowDimensions.js:110)
    in Unknown (at withNavigation.js:14)
    in withNavigation(Component) (at withNavigation.js:35)
    in Unknown (at ScreenWrapper/index.android.js:6)
    in ScreenWrapper (at ReportScreen.js:227)
    in ReportScreen (at withOnyx.js:173)
    in withOnyx(ReportScreen) (at withOnyx.js:197)
    in Unknown (at createOnyxContext.js:39)
    in withNetwork(Component) (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
    in View (at Screen.tsx:63)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at Screen.tsx:58)
    in Screen (at DrawerView.tsx:247)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:257)
    in MaybeFreeze (at src/index.native.tsx:256)
    in Screen (at ScreenFallback.tsx:38)
    in MaybeScreen (at DrawerView.tsx:241)
    in RNSScreenContainer (at src/index.native.tsx:330)
    in ScreenContainer (at ScreenFallback.tsx:29)
    in MaybeScreenContainer (at DrawerView.tsx:206)
    in RCTView (at View.js:32)
    in View (at Drawer.tsx:566)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.tsx:682)
    in AnimatedComponent(View) (at createAnimatedComponent.tsx:693)
    in Unknown (at Drawer.tsx:553)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.tsx:682)
    in AnimatedComponent(View) (at createAnimatedComponent.tsx:693)
    in Unknown (at Drawer.tsx:541)
    in PanGestureHandler (at GestureHandlerNative.tsx:14)
    in PanGestureHandler (at Drawer.tsx:532)
    in DrawerView (at DrawerView.tsx:274)
    in DrawerViewBase (at DrawerView.tsx:318)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at DrawerView.tsx:317)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at DrawerView.tsx:316)
    in DrawerView (at createDrawerNavigator.tsx:126)
    in Unknown (at createDrawerNavigator.tsx:125)
    in DrawerNavigator (at BaseDrawerNavigator.js:65)
    in BaseDrawerNavigator (at withWindowDimensions.js:92)
    in withWindowDimensions(BaseDrawerNavigator) (at withWindowDimensions.js:110)
    in Unknown (at MainDrawerNavigator.js:70)
    in MainDrawerNavigator (at withOnyx.js:173)
    in withOnyx(MainDrawerNavigator) (at withOnyx.js:197)
    in Unknown (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:281)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:279)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:557)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at Card.tsx:536)
    in PanGestureHandler (at GestureHandlerNative.tsx:14)
    in PanGestureHandler (at Card.tsx:530)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at Card.tsx:526)
    in RCTView (at View.js:32)
    in View (at Card.tsx:520)
    in Card (at CardContainer.tsx:219)
    in CardContainer (at CardStack.tsx:661)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:257)
    in MaybeFreeze (at src/index.native.tsx:256)
    in Screen (at Screens.tsx:37)
    in MaybeScreen (at CardStack.tsx:654)
    in RNSScreenContainer (at src/index.native.tsx:332)
    in ScreenContainer (at Screens.tsx:20)
    in MaybeScreenContainer (at CardStack.tsx:566)
    in RCTView (at View.js:32)
    in View (at Background.tsx:13)
    in Background (at CardStack.tsx:564)
    in CardStack (at StackView.tsx:437)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:430)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at StackView.tsx:429)
    in StackView (at createCustomModalStackNavigator.js:26)
    in CustomRootStackNavigator (at AuthScreens.js:179)
    in AuthScreens (at withOnyx.js:173)
    in withOnyx(AuthScreens) (at withOnyx.js:197)
    in Unknown (at withWindowDimensions.js:92)
    in withWindowDimensions(Component) (at withWindowDimensions.js:110)
    in Unknown (at AppNavigator/index.js:19)
    in AppNavigator (at NavigationRoot.js:79)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at NavigationRoot.js:63)
    in NavigationRoot (at Expensify.js:204)
    in Expensify (at withOnyx.js:173)
    in withOnyx(Expensify) (at withOnyx.js:197)
    in Unknown (at withLocalize.js:167)
    in withLocalize(Component) (at App.js:44)
    in BaseErrorBoundary (at App.js:43)
    in RenderersPropsProvider (at RenderHTMLConfigProvider.tsx:76)
    in ListStyleSpecsProvider (at RenderHTMLConfigProvider.tsx:75)
    in SharedPropsProvider (at RenderHTMLConfigProvider.tsx:74)
    in RenderRegistryProvider (at RenderHTMLConfigProvider.tsx:71)
    in RenderHTMLConfigProvider (at BaseHTMLEngineProvider.js:68)
    in TRenderEngineProvider (at BaseHTMLEngineProvider.js:60)
    in BaseHTMLEngineProvider (at HTMLEngineProvider/index.native.js:6)
    in HTMLEngineProvider (at ComposeProviders.js:16)
    in LocaleContextProvider (at withOnyx.js:173)
    in withOnyx(LocaleContextProvider) (at withOnyx.js:197)
    in withOnyx(LocaleContextProvider) (at ComposeProviders.js:16)
    in _default (at ComposeProviders.js:16)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at ComposeProviders.js:16)
    in CurrentDateProvider (at withOnyx.js:173)
    in withOnyx(CurrentDateProvider) (at withOnyx.js:197)
    in Unknown (at ComposeProviders.js:16)
    in ReportActionsDrafts_Provider (at withOnyx.js:173)
    in withOnyx(ReportActionsDrafts_Provider) (at withOnyx.js:197)
    in Unknown (at ComposeProviders.js:16)
    in PersonalDetailsProvider (at withOnyx.js:173)
    in withOnyx(PersonalDetailsProvider) (at withOnyx.js:197)
    in Unknown (at ComposeProviders.js:16)
    in NetworkProvider (at withOnyx.js:173)
    in withOnyx(NetworkProvider) (at withOnyx.js:197)
    in Unknown (at ComposeProviders.js:16)
    in ComposeProviders (at OnyxProvider.js:23)
    in OnyxProvider (at ComposeProviders.js:16)
    in ComposeProviders (at App.js:33)
    in RNGestureHandlerRootView (at GestureHandlerRootView.android.tsx:23)
    in GestureHandlerRootView (at App.js:32)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in NewExpensify(RootComponent) (at renderApplication.js:60)
```

**Comment by luacmartins** [comment] 2022-09-01 20:02
Hmm I also reproduced the crash without the error above. So now I'm not sure what actually causes it.

**Comment by chiragsalian** [comment] 2022-09-02 00:16
I havent been able to get android simulator working on my dev so i've requested for someone else to investigate the issue on slack #engg-chat.

**Comment by Beamanator** [comment] 2022-09-02 10:17
Just tested on android simulator, wasn't able to reproduce - will try on android device in staging

**Comment by Beamanator** [comment] 2022-09-02 10:19
Also couldn't reproduce on an actual device, android v1.1.96-3

**Comment by luacmartins** [comment] 2022-09-02 12:05
I was able to reproduce this last night, but this is not the case anymore 🤔

**Comment by kbecciv** [comment] 2022-09-02 13:04
@luacmartins Issue is not reproduced with build 1.1.96.5

https://user-images.githubusercontent.com/93399543/188151953-8c75dc16-bcbf-408f-bd50-03d44c61aab1.mp4

**Comment by luacmartins** [comment] 2022-09-02 13:07
Thanks for confirming @kbecciv! Closing issue!

**Closed by luacmartins** 2022-09-02 13:07 UTC
Labels: DeployBlockerCash, Engineering, Hourly
