### ISSUE TITLE
[$250] Clicking on currency in currency selector also scrolls the list.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42355] opened 2024-05-17 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ishpaul777 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1715978251152609

## Action Performed:
1. Login to https://staging.new.expensify.com/
2. Navigate to settings and select any workspace
3. Click on any other currency to select
## Expected Result:
Selects the currency and close the modal.
## Actual Result:
It always scrolls the list
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/7f4fff17-bef5-4b25-a858-09265d190849

https://github.com/Expensify/App/assets/38435837/2103d4d3-df0a-4717-bf80-cd438f7fd3e5

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195391e75124d68ce</li>
        <li>Upwork Job ID: 1792684016054362112</li>
        <li>Last Price Increase: 2024-05-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by nkdengineer** [comment] 2024-05-18 02:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It always scrolls the list

### What is the root cause of that problem?
- We do not use ```shouldPreventDefaultFocusOnSelectRow: true``` in this case
### What changes do you think we should make in order to solve the problem?
- We should use ```shouldPreventDefaultFocusOnSelectRow: true``` in this case
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-18 02:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It always scrolls the list

### What is the root cause of that problem?
- We do not use ```shouldPreventDefaultFocusOnSelectRow: true``` in this case
### What changes do you think we should make in order to solve the problem?
- We should use ```shouldPreventDefaultFocusOnSelectRow: false``` in this case

### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-05-18 02:54
## Proposal
    
### Please re-state the problem that we are trying to solve in this issue.
It always scrolls the list

### What is the root cause of that problem?

- When clicking on a button, three events occur sequentially: onMouseDown, onMouseUp, and onClick.

- In this particular bug scenario, when we initiate a "mouse down" action on option A, it focuses on option A and then scrolls to it. The onMouseDown event's target is option A.

- Since the mouse pointer remains stationary, after the list is scrolled, the pointer ends up over another option, B.

- Subsequently, when we release the mouse button ("mouse up"), the onMouseUp event's target is option B.
### What changes do you think we should make in order to solve the problem?
- In [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/CurrencySelectionList/index.tsx#L44), we should use ```shouldPreventDefaultFocusOnSelectRow: true```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by nkdengineer** [comment] 2024-05-18 02:56
## Proposal
      
### Please re-state the problem that we are trying to solve in this issue.
It always scrolls the list

### What is the root cause of that problem?

- When clicking on a button, three events occur sequentially: onMouseDown, onMouseUp, and onClick.

- In this particular bug scenario, when we initiate a "mouse down" action on option A, it focuses on option A and then scrolls to it. The onMouseDown event's target is option A.

- Since the mouse pointer remains stationary, after the list is scrolled, the pointer ends up over another option, B.

- Subsequently, when we release the mouse button ("mouse up"), the onMouseUp event's target is option B.
### What changes do you think we should make in order to solve the problem?
- In [here](https://github.com/Expensify/App/blob/e8ae3c5acedf0e6788dc574c7b6f3043ca37092a/src/components/CurrencySelectionList/index.tsx#L44), we should use ```shouldPreventDefaultFocusOnSelectRow: true``` or ```shouldPreventDefaultFocusOnSelectRow={!DeviceCapabilities.canUseTouchScreen()}```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by MitchExpensify** [comment] 2024-05-20 22:29
Let's fix this!

**Comment by tsa321** [comment] 2024-05-20 23:32
Same as https://github.com/Expensify/App/issues/41922

**Comment by MitchExpensify** [comment] 2024-05-22 19:49
Ah good catch @tsa321 , closing this dupe

**Closed by MitchExpensify** 2024-05-22 19:49 UTC
Labels: External, Daily, Help Wanted, Bug
