### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD for payment 2023-10-27] IOU - Tapping delete request, user is directed to "hmm...it's not here" page.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30020] opened 2023-10-19 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap on a 1:1 report
3. Tap plus icon near compose box
4. Tap request money
5. Enter an amount
6. Tap next
7. Tap request amount
8. Tap on IOU transaction
9. Tap on IOU to open IOU detail page
10. Tap on 3dots and tap delete request and confirm delete

## Expected Result:
When user tap delete request, IOU must be deleted and user must not be shown hhm it's not here page

## Actual Result:
When user tap delete request, he is directed to "hmm...it's not here" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/f582e5b6-782a-4ddb-b853-112d4ba75cf3

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2023-10-19 19:57
@lanitochka17 Can you share the URL that `Hmm... it's not here` is presenting on `iOS: mWeb Safari`?

**Comment by johnmlee101** [comment] 2023-10-19 21:10
Okay have my own example
https://staging.new.expensify.com/r/64913349

the route seems fine since that was the base chat that originated my IOU, so it doesn't seem related to the route in the URL at least

**Comment by johnmlee101** [comment] 2023-10-19 21:11
Oh interesting but refreshing takes me to https://staging.new.expensify.com/r/18863252980177 so let me see what that is. I bet its the IOU report that contains the IOU itself, so we're not properly back-pacing

**Comment by francoisl** [comment] 2023-10-20 00:26
Discussion in the open source Slack channel [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1697750060469009), we're closing in on a solution.

**Comment by sophiepintoraetz** [comment] 2023-10-29 22:19
@francoisl @jasperhuangg - what was the regression that caused this?

**Comment by francoisl** [comment] 2023-10-31 02:20
I linked the PR in the checklist above, it was an internal PR. The issue was found by Applause and the fix was handled internally, so I don't think we need payments here?

**Comment by sophiepintoraetz** [comment] 2023-10-31 02:30
No, no payments! A regression test though - so I'll loop in the author @jasperhuangg @fedirjh @Li357 - bumping here as well, please can you write up a regression test for this regression that came out of y'alls PR?
https://github.com/Expensify/App/pull/27966#issuecomment-1786339086

**Comment by s77rt** [comment] 2023-10-31 10:10
**Regression Test Proposal**

1. Open a chat report with someone you have not chatted with before
2. Request money (using the plus + button in the composer)
3. Click on the IOU preview then on the transaction report action
5. Click on the 3 dots > Delete request
6. Verify you are redirected to the chat report

**Comment by sophiepintoraetz** [comment] 2023-10-31 21:23
Thanks @s77rt!

**Closed by sophiepintoraetz** 2023-10-31 21:23 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
