### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] The new emoji search field focus inconsistent between mweb chrome and web chrome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20979] opened 2023-06-18 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and go to any chat. Select emoji picker and notice that the search field is focused by default
2. Follow the same process on mweb chrome and notice that the search field doesn't have focus while opening the emoji picker
## Expected Result: 
The new emoji search field focus should be consistent between mweb chrome and web chrome
## Actual Result: 
The new emoji search field focus is inconsistent between mweb chrome and web chrome

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/52036563-3219-4e01-a578-66d9e0bf738e

https://github.com/Expensify/App/assets/43996225/98d16818-7735-428d-8373-1397c61f5001

https://github.com/Expensify/App/assets/43996225/afcba919-eefa-43e7-8d17-9804f8cffe9e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686304700678499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011663a64195fe4bdf</li>
        <li>Upwork Job ID: 1671324047938600960</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-19 11:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Emoji search field isn't focused when open emoji picker on mobile web

### What is the root cause of that problem?

We prevent focusing on modal show event for mobile devices here
https://github.com/Expensify/App/blob/ffd9672efcd6c6bb001b902805e308fe996277c6/src/components/EmojiPicker/EmojiPicker.js#L148

### What changes do you think we should make in order to solve the problem?

Remove the `this.props.isSmallScreenWidth` checking

```
        if (!this.emojiSearchInput || this.props.isSmallScreenWidth) {
            return;
        }
```

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-06-21 01:07
Can reproduce. Assigning an external label.

**Comment by kamaljitSharma21** [comment] 2023-06-21 05:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The new emoji search field focus inconsistent between mweb chrome and web chrome

### What is the root cause of that problem?
We have disabled the autofocus on search input of emojipicker when smallscreen is detected thats why the autofocus in web chrome is not same as mweb chrome.

### What changes do you think we should make in order to solve the problem?
[Here](https://github.com/Expensify/App/blob/342d4fd84f3dda933c44a71b9e4d666d26b270c9/src/components/EmojiPicker/EmojiPickerMenu/index.js#L501) on this line we need to remove condition of `autoFocus`

updated code : 

```
<TextInput
  label={this.props.translate('common.search')}
  onChangeText={this.filterEmojis}
  defaultValue=""
  ref={(el) => (this.searchInput = el)}
  autoFocus
  selectTextOnFocus={this.state.selectTextOnFocus}
  onSelectionChange={this.onSelectionChange}
  onFocus={() => this.setState({isFocused: true, highlightedIndex: -1, isUsingKeyboardMovement: false})}
  onBlur={() => this.setState({isFocused: false})}
  autoCorrect={false}
/>

```

### What alternative solutions did you explore? (Optional)

NA

**Comment by anmurali** [comment] 2023-06-26 17:07
@aimane-chnaif can you please review the proposal above?

**Comment by kamaljitSharma21** [comment] 2023-06-29 13:40
@aimane-chnaif any updates on the proposal review ?

**Comment by anmurali** [comment] 2023-07-03 17:55
Going to bump in the slack thread

**Comment by situchan** [comment] 2023-07-04 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Autofocus not working on web resized window

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/900b3288d8e97769f23605cdff44d248d559fbfc/src/components/EmojiPicker/EmojiPickerMenu/index.js#L501
We prevent autofocus on all small devices but this is wrong logic. No need to prevent autofocus on no-keyboard devices

### What changes do you think we should make in order to solve the problem?
Similar to composer autofocus logic which was done in #18699, use `canFocusInputOnScreenFocus()` condition

https://github.com/Expensify/App/blob/900b3288d8e97769f23605cdff44d248d559fbfc/src/pages/home/report/ReportActionCompose.js#L193-L195

**Comment by anmurali** [comment] 2023-07-07 17:18
@aimane-chnaif - so are we going to assign this job to @situchan ?

**Comment by madmax330** [comment] 2023-07-10 10:28
Thanks @aimane-chnaif I agree, assigned @situchan

**Comment by madmax330** [comment] 2023-07-26 06:47
awaiting payment

**Comment by madmax330** [comment] 2023-08-02 20:58
Not overdue

**Comment by madmax330** [comment] 2023-08-07 10:59
Not overdue

**Comment by madmax330** [comment] 2023-08-10 11:17
Bump @anmurali

**Comment by anmurali** [comment] 2023-08-15 14:13
Payments
- [ ] Reporting bonus $250 @priya-zha - Offer [here](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/26133286), pending acceptance
- [ ] Contributor and Contributor + payment $1,000 @aimane-chnaif - Paid
- [ ] Contributor and Contributor + payment $1,000 @situchan - Offer [here](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/26133245), pending acceptance

**Comment by madmax330** [comment] 2023-08-21 11:09
@aimane-chnaif so we still need to pay out the bonuses here?

**Comment by anmurali** [comment] 2023-08-24 17:57
<img width="971" alt="image" src="https://github.com/Expensify/App/assets/14225673/644eeb81-7d3a-445a-9f7a-cab5ad5c1837">
No it is done!

**Closed** 2023-08-24 17:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
