### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Tag - Custom name for tag in tag edit message reverts to "tag" after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33493] opened 2023-12-22 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of a Collect workspace on OD
- The Collect workspace has custom name for Tag
1. Go to the workspace chat
2. Create a manual request with an assigned tag
3. Open request details page
4. Click on tag
5. Select a different tag
6. Log out and log in again
7. Navigate to the same request details page in Step 3

## Expected Result:
The custom name for tag in tag edit message remains as the custom name after relogin

## Actual Result:
The custom name for tag in tag edit message reverts to "Tag" after relogin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/edf1c27a-2a97-4e23-8b89-daf06a76c542

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012b6267e4a0f872d1</li>
        <li>Upwork Job ID: 1738202853693796352</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28094836</li>
<li>hoangzinh | Contributor | 28094837</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by jjcoffee** [comment] 2024-01-02 16:22
Sorry I was OOO, will review tomorrow!

**Comment by jjcoffee** [comment] 2024-01-04 13:48
@hoangzinh's [proposal](https://github.com/Expensify/App/issues/33493#issuecomment-1867829021) LGTM! @dukenv0307's proposal is more or less the same, but I agree that we should probably remove the `reportID` from the optimistic data to keep things consistent.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by tgolen** [comment] 2024-01-04 15:48
Hm, while I think both proposals would work, does this seem like it should be fixed from the BE? I'm just thinking that the BE should return the same data that was set in the optimistic data. If there is a discrepancy between the two, I can see how it would lead to bugs like this. I think it would be better to try and make sure the optimisticData and the server response are in sync. I would propose either one of these:

1. Remove the `reportID` from the optimisticData and always pass `reportID` to `getForReportAction()` (this would be a full FE fix)
2. Add `reportID` to the MODIFIEDEXPENSE action that the server is returning (this would be a full BE fix)

I think I'd actually lean towards `1` because I think having the `reportID` stored in the MODIFIEDEXPENSE action is redundant. @hoangzinh could you please update your proposal to also remove the `reportID` from the optimistic data and verify that will work?

**Comment by miljakljajic** [comment] 2024-01-08 14:35
@tgolen thoughts on the above when you get in today?

**Comment by tgolen** [comment] 2024-01-08 16:09
>  is it possible for you to confirm that BE doesn't return reportID prop for all the report actions now?

That's not a very simple operation 😓 I looked in several places and it looks like when the `MODIFIEDCREATED` action is stored in the database, it includes the `reportID`. However, when we return the actions to the frontend in `OpenApp`, `OpenReport` and `ReconnectApp`, it looks like it does not include it. I see that in TS, the `reportID` is marked as optional, so it might be that it sometimes exists and it sometimes doesn't. 

You can always confirm the same by looking at the API responses.

**Comment by tgolen** [comment] 2024-01-10 16:57
That's great, thank you! @jjcoffee are you OK with accepting the proposal from @hoangzinh?

**Comment by jjcoffee** [comment] 2024-01-11 09:31
@tgolen Yup, looks good to me!

**Comment by miljakljajic** [comment] 2024-01-15 17:18
not overdue!

**Comment by jjcoffee** [comment] 2024-01-25 15:26
PR is in review, just waiting for @hoangzinh to answer a question.

**Comment by jjcoffee** [comment] 2024-02-05 14:49
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30603
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30603/files#r1478371558
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to the workspace chat
2. Create a manual request with an assigned tag
3. Open request details page
4. Select a different tag
6. Verify that the modified expense message shows with a custom name for Tag (I.e "changed the CTag to...")
7. Log out and log in again
8. Verify that the modified expense message shows with a custom name for Tag (I.e "changed the CTag to...")

Do we agree 👍 or 👎

**Comment by tgolen** [comment] 2024-02-06 16:09
Sounds good to me 👍

**Comment by miljakljajic** [comment] 2024-02-07 09:22
Test rail issue submitted, contributors paid, contracts closed.  Closing!

**Closed by miljakljajic** 2024-02-07 09:22 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
