### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Submit expense - "Hold" option is not present in report details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44470] opened 2024-06-26 15:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to a workspace chat with no prior expense submissions and click the plus sign
2. Submit an expense by adding the amount, merchant, and confirming it
3. Go to IOU, click the headers, and notice that the 'Hold' option is not available

## Expected Result:
The "Hold" option should be present on the report details page

## Actual Result:
After submitting a single expense in the workspace chat, the 'Hold' option appears in IOU when clicking the three dots. However, the "Hold" option is not present on the report details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/76ef2ac6-b8fa-4278-a98b-f7f96a5f9b4e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166273ab3240af3ae</li>
        <li>Upwork Job ID: 1806101011812532362</li>
        <li>Last Price Increase: 2024-07-03</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Contributor | 102893192</li>
<li>nkdengineer | Contributor | 102991523</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by lanitochka17** [comment] 2024-06-26 15:03
@aldo-expensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by aldo-expensify** [comment] 2024-06-26 19:51
From looking at the code: https://github.com/Expensify/App/blob/64c6624d8324b5cb78c75c4d4a8bbc16e4ca0b33/src/pages/ReportDetailsPage.tsx#L628-L639

I don't think this was ever implemented and it doesn't seem to be part of the initial designs.

@robertjchen do you think we want to add this hold button in the report details?

<img width="1338" alt="image" src="https://github.com/Expensify/App/assets/87341702/55a4ce88-9896-4382-bee1-83571eb61072">


Or should we just close this?

**Comment by aldo-expensify** [comment] 2024-06-26 19:52
I tested [this proposal](https://github.com/Expensify/App/issues/44470#issuecomment-2192199319) and it doesn't seem to help... the HOLD button doesn't appear in the report details because the code is completely missing from there I think

**Comment by dannymcclain** [comment] 2024-06-26 19:56
I think the `Hold` button should show up in the row of buttons near the top. This looks like another gotcha of the one-expense report. cc @JmillsExpensify 

Here's a mock for the _expense_ details showing the hold button:
![CleanShot 2024-06-26 at 14 54 11@2x](https://github.com/Expensify/App/assets/7516624/1700aeb9-0c02-4f5e-bc0a-2f64b5ed16da)

**Comment by aldo-expensify** [comment] 2024-06-26 23:00
Ahh! I had missed that the code trying to add the button was there: https://github.com/Expensify/App/blob/e24cf4d78e7b4dee5a8028e180a75c98bd87e868/src/pages/ReportDetailsPage.tsx#L447-L448

Thanks for pointing that out.. so I guess this isn't a new feature then and it is just a bug.

**Comment by aldo-expensify** [comment] 2024-06-26 23:00
@dannymcclain I'll remove your assignment since I missed that this was already designed and was not working because of a bug.

**Comment by aldo-expensify** [comment] 2024-06-26 23:04
> 📣 @brunovjk 🎉 An offer has been automatically sent to your Upwork account for the Contributor role 🎉 Thanks for contributing to the Expensify app!

Messed up the assignments. @brunovjk is in the role of C+

**Comment by nkdengineer** [comment] 2024-06-27 04:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After submitting a single expense in the workspace chat, the 'Hold' option appears in IOU when clicking the three dots. However, the "Hold" option is not present on the report details page

### What is the root cause of that problem?
The condition to show the hold option is wrong for the iou report.

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L447-L448

1. `caseID !== CASES.MONEY_REPORT` this check will not accept show the hold action if the report is the expense report

2. If the report is the iou report, the `parentReportAction` will be the report preview action and then `ReportUtils.canHoldUnholdReportAction` function will return `{canHoldRequest: false, canUnholdRequest: false}` because `parentReportAction` is not money request action.

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L446
### What changes do you think we should make in order to solve the problem?
1. We should change the check `caseID` to `caseID !== CASES.DEFAULT` because for both `MONEY_REPORT` and `MONEY_REQUEST` cases we can show the hold option.

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L447-L448

2. If the iou report is the combine report, we should pass `requestParentReportAction` that is the correct money request action to `canHoldUnholdReportAction` function here 

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L446

and also use `requestParentReportAction` here instead of `parentReportAction`
https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L460




- To simple we can create a new variable like `moneyRequestAction`

```
const moneyRequestAction = transactionThreadReportID ? requestParentReportAction : parentReportAction
```

and use this when we check the hold condition and push the hold option to prompt

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L446

https://github.com/Expensify/App/blob/d4e82acc137179c9d84db10ba639a5c3d6c55d33/src/pages/ReportDetailsPage.tsx#L460
### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-06-27 12:22
Reviewing now 🔁

**Comment by brunovjk** [comment] 2024-06-27 22:56
Reviewing now 🔁

**Comment by brunovjk** [comment] 2024-06-28 13:14
Thank you all for the proposals. All three identify the root cause related to **the necessary updates for `canHoldRequest` on a `REPORTPREVIEW`**, but only @nkdengineer's solution worked. I tested both @ShridharGoel and @nyomanjyotisa's solutions, I couldn't get them to solve the issue, so we can go with nkdengineer's [proposal](https://github.com/Expensify/App/issues/44470#issuecomment-2193697910).

🎀👀🎀 C+ reviewed

**Comment by brunovjk** [comment] 2024-06-28 17:58
@ShridharGoel Thank you for clarifying. I tested your solution/branch and it works well, I believe I was missing something. Your solution is quite similar to @nkdengineer's; however, theirs looks slightly better to me, but yours was posted first. I'll let @aldo-expensify decide. Sorry about that.

**Comment by nkdengineer** [comment] 2024-06-28 18:05
We only want to display the hold action in iou report if we only have one transaction in this report and this proposal doesn't work as this expected behavior (in the case the iou report has many transaction).

**Comment by aldo-expensify** [comment] 2024-06-28 21:52
@brunovjk the 3 proposals look similar to me. Did you review this one? https://github.com/Expensify/App/issues/44470#issuecomment-2192199319 for me it is almost the same but getting less into details, but still enough details

> I tested [this proposal](https://github.com/Expensify/App/issues/44470#issuecomment-2192199319) and it doesn't seem to help... the HOLD button doesn't appear in the report details because the code is completely missing from there I think

I posted this regarding that proposal, but looking back, I missed some pieces of the code when testing so I may have tested it poorly.

**Comment by brunovjk** [comment] 2024-06-29 13:38
> @brunovjk the 3 proposals look similar to me. Did you review this one? [#44470 (comment)](https://github.com/Expensify/App/issues/44470#issuecomment-2192199319) for me it is almost the same but getting less into details, but still enough details
 
Yes, RCA seems ok with everything, but imo @nyomanjyotisa's solution is not complete.

> We only want to display the hold action in iou report if we only have one transaction in this report and this proposal doesn't work as this expected behavior (in the case the iou report has many transaction).

@aldo-expensify Do you confirm this?

**Comment by MitchExpensify** [comment] 2024-07-02 20:28
Friendly bump on this question @aldo-expensify https://github.com/Expensify/App/issues/44470#issuecomment-2198197432

**Comment by marcochavezf** [comment] 2024-07-03 18:31
> We only want to display the hold action in iou report if we only have one transaction in this report and this proposal doesn't work as this expected behavior (in the case the iou report has many transaction).

Yes, this is correct since we can only hold one request (transaction) at a time and not the entire report if it contains more than one transaction

**Comment by brunovjk** [comment] 2024-07-03 19:17
I believe we still can go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/44470#issuecomment-2193697910). Ensuring the correct `'reportID'` is passed before calling the `canHoldUnholdReportAction` function is a cleaner approach to me. It keeps the `canHold..` function unchanged, reduces the risk of bugs, and maintains clear logic. Also ensures we can only hold one request (transaction) at a time.

**Comment by brunovjk** [comment] 2024-07-03 19:19
With this @aldo-expensify, I believe we can still go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/44470#issuecomment-2193697910). Ensuring the correct `reportID` is passed before calling the `canHoldUnholdReportAction` function is a cleaner approach. It keeps the `canHold...` function unchanged, reduces the risk of bugs, and maintains clear logic. It also ensures we can only hold one request (transaction) at a time.

**Comment by marcochavezf** [comment] 2024-07-04 17:35
Sounds good! Thanks for the review @brunovjk, assigning @nkdengineer 🚀

**Comment by nkdengineer** [comment] 2024-07-05 04:15
@brunovjk The PR is [here](https://github.com/Expensify/App/pull/44880).

**Comment by MitchExpensify** [comment] 2024-07-16 19:57
Reassigning while I'm leave (PR is on staging) 🙇

**Comment by brunovjk** [comment] 2024-07-22 11:57
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **No**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by sakluger** [comment] 2024-07-23 23:08
@brunovjk you don't think that we should add a regression test for this one?

**Comment by brunovjk** [comment] 2024-07-23 23:17
@sakluger I thought no, but what do you think?

**Comment by sakluger** [comment] 2024-07-24 15:20
Yeah, I think we want to include this in our regression tests. Those steps look good!

**Comment by sakluger** [comment] 2024-07-24 15:23
Summarizing payment on this issue:

Contributor: @nkdengineer $250, paid via Upwork
Contributor+: @brunovjk $250, paid via Upwork

**Closed by sakluger** 2024-07-24 15:23 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
