### ISSUE TITLE
[$1000] First cell of magic code input is marked green when authenticating with expired magic code

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21291] opened 2023-06-22 02:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign in page
2. Enter email and click on continue
3. Copy an expired magic code from email
4. Open new tab on the same window you opened the app
5. Paste the magic sign-in link > prefix the link with 'staging' > press enter key
6. Open the tab where you originally singed in
## Expected Result: 
All magic code input cells should be marked with red
## Actual Result: 
First cell of the magic input field is marked green

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6e660fc9-31b2-4e70-872e-90f9d0496bcf

https://github.com/Expensify/App/assets/43996225/63eea045-846f-483b-8286-6a6925b732b2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686833554570519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01332d1940a5b27892</li>
        <li>Upwork Job ID: 1673919430133280768</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-06-22 14:18
Hey, I am heading OOO shortly, so assigning another bug0 team member to help watch over this issue whilst I am OOO. thank you!

**Comment by kameshwarnayak** [comment] 2023-06-23 10:51
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
First cell of magic code input is marked green when authenticating with expired magic code 

### What is the root cause of that problem?
There are two main issues here. 
1. The "Focus styling" is added after "Error styling"

https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/components/MagicCodeInput.js#L316-L317

2. The default behaviour when users enter the Magic Code, the code is displayed. When the users click the expired magic code URL, the code is not carried on to the screen

The root cause is because `validateCode` is not passed in `ONYXKEYS.CREDENTIALS` in src/libs/actions/Session/index.js on failure in the function `signInWithValidateCode`

https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/libs/actions/Session/index.js#L431-L445

### What changes do you think we should make in order to solve the problem?
To solve the first issue we need to move the "Focus styling" before "Error styling"

```
focusedIndex === index ? styles.borderColorFocus : {},
props.hasError || props.errorText ? styles.borderColorDanger : {},
```

To copy the magic code add `validateCode` to `ONYXKEYS.CREDENTIALS`

```
    const failureData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.ACCOUNT,
            value: {
                isLoading: false,
                loadingForm: null,
            },
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.SESSION,
            value: {autoAuthState: CONST.AUTO_AUTH_STATE.FAILED},
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.CREDENTIALS,
            value: {validateCode: validateCode},
        },
    ];
```

Result of the above changes can be seen in the video

https://github.com/Expensify/App/assets/2232432/616a3f15-e1d2-421e-9905-41f44a3d1ebd



### What alternative solutions did you explore? (Optional)
None

**Comment by JmillsExpensify** [comment] 2023-06-28 05:00
This is a pretty wild one to reproduce, but I do think we can fix that green in the first input. Opening this up to the community.

**Comment by zanyrenney** [comment] 2023-07-03 10:14
Sounds good to me, closing!

**Closed by zanyrenney** 2023-07-03 10:14 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
