### ISSUE TITLE
[$500] Chat - Composer is not focused when entering a chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30122] opened 2023-10-21 16:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697867038529909

## Action Performed:
1. Go to any chat
2. Notice the composer

## Expected Result:
Composer is focused when entering a chat

## Actual Result:
The composer is not focused

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c2b1af06-729a-471b-b0c3-95780568dbdb

https://github.com/Expensify/App/assets/93399543/db392d6f-ae67-4287-80e7-0d39a2985748

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/6cb40721-6670-4f56-a399-23e8b8086f1e

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/17b7fd19-301e-4ec2-868c-1f2ef9a40390

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6240fdba-e275-466a-b36d-8d92f03a8c2d

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c18b768c063d983</li>
        <li>Upwork Job ID: 1715760908335640576</li>
        <li>Last Price Increase: 2023-10-21</li>
    </ul>
</details>

**Comment by Samueljh1** [comment] 2023-10-21 16:32
.

**Comment by Samueljh1** [comment] 2023-10-21 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The composer is not automatically focused when opening a chat.

### What is the root cause of that problem?
The `focus()` method in the ComposerWithSuggestions component is not called when it is loaded.

### What changes do you think we should make in order to solve the problem?
Call the `focus` method straight away to focus the text input when the chat is opened.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by s-alves10** [comment] 2023-10-21 17:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The main composer doesn't get focused when navigating to a chat

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L124

In the above code, `shouldFocusInputOnScreenFocus` is false for mWeb and native platforms.

This is the root cause

### What changes do you think we should make in order to solve the problem?

This looks like an intentional behavior.
If this still needs to be fixed, we can update the above condition to
```
    const shouldAutoFocus = !modal.isVisible && shouldShowComposeInput;
```

This works as expected


### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-10-21 22:23
This is not a bug. It's intended to be this way. On small devices the auto focus will bring up the keyboard which may be annoying. Reports are optimized for reading. Ref: https://expensify.slack.com/archives/C01GTK53T8Q/p1617201995245400

@conorpendergrast I think we can close this.

**Comment by conorpendergrast** [comment] 2023-10-23 09:28
I agree with you @s77rt. Here's where we added that: https://github.com/Expensify/Expensify/issues/159543. Closing, thanks all!

**Closed by conorpendergrast** 2023-10-23 09:28 UTC
Labels: External, Daily, Help Wanted, Bug
