### ISSUE TITLE
[HOLD for payment 2022-11-02] [$250] IOS - Keyboard field still active on selecting attachment and opens after downloading an attachment @chauchausoup

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11525] opened 2022-10-02 19:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat, type something.
2. Open up an attachment from same chat.
3. Again type something.
4. Download the attachment.
5. Type something again.

## Expected Result:
Keyboard shouldn’t be popped up post download
Entered characters should’t be entered in the previous composer

## Actual Result:
Keyboard gets popped up post download
Entered characters gets entered in the parent composer

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.11.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193471552-cffc3dc2-ae33-45d5-a6fe-8d971e085509.MP4

https://user-images.githubusercontent.com/93399543/193471566-f7e37f0d-6052-452c-9795-68b24117be0d.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @chauchausoup

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664559707668889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ctkochan22** [comment] 2022-10-10 18:14
Sounds like its pretty straight-forward path to investigate.

**Comment by Uros787** [comment] 2022-10-10 19:32
### Proposal
Add Keyboard.dismiss() on [AttachmentModal](https://github.com/Expensify/App/blob/6551eb9d07f54c222bd6cb7411b7613f3ccd03b4/src/components/AttachmentModal.js#L250-L267)
After fileDownload

```
<HeaderWithCloseButton
  title={this.props.headerTitle || this.props.translate("common.attachment")}
  shouldShowBorderBottom
  shouldShowDownloadButton={this.props.allowDownload}
  onDownloadButtonPress={() => {
    fileDownload(sourceURL, this.props.originalFileName);
    Keyboard.dismiss();
  }}
  onCloseButtonPress={() => this.setState({ isModalOpen: false })}
  subtitle={
    fileName ? (
      <TextWithEllipsis
        leadingText={fileName}
        trailingText={fileExtension ? `.${fileExtension}` : ""}
        wrapperStyle={[styles.w100]}
        textStyle={styles.mutedTextLabel}
      />
    ) : (
      ""
    )
  }
/>;
```

After fix:
https://user-images.githubusercontent.com/70144379/194939404-ecacb029-462b-4b2e-8f94-a0b51373fdf7.mov

**Comment by sophiepintoraetz** [comment] 2022-10-13 04:48
@ctkochan22 - we have a proposal, are we happy to go ahead with it?

**Comment by ctkochan22** [comment] 2022-10-13 07:14
Whoops! Must have missed that notification. Let me take a look first thing tomorrow

**Comment by thesahindia** [comment] 2022-10-13 08:30
Sorry for the delay here. 

@Uros787, your solution will work but can you tell why this is happening when we download the image?

**Comment by Uros787** [comment] 2022-10-13 10:08
Hi @thesahindia 
yes so for some reason ios has this weird behavior that other people have also encountered and that is after closing a prompt(alert) the keyboard will for some unknown reason prompt.
And one more thing is that Apple actually advises against using alert as a success prompt but as we do we have to use it, I think the best solution would be to just dismiss the keyboard

**Comment by thesahindia** [comment] 2022-10-13 21:11
> yes so for some reason ios has this weird behavior that other people have also encountered and that is after closing a prompt(alert) the keyboard will for some unknown reason prompt.

Can you share some link, it will be helpful.

**Comment by Uros787** [comment] 2022-10-13 21:55
yes
https://github.com/ionic-team/ionic-framework/issues/9030
https://stackoverflow.com/questions/36028685/alert-instead-of-keyboard-for-input-in-textfield-cursor-stays-in-textfield-s
https://stackoverflow.com/questions/73799004/ios-keyboard-not-hiding-when-alert-or-confirm-box-appears-in-react-js
https://github.com/facebook/react-native/issues/17356

**Comment by ctkochan22** [comment] 2022-10-17 22:23
Sorry, messy week with the deploy. 

@thesahindia So you are suggesting to place `Keyboard.dismiss()` above `fileDownload`? 

If that is the case, yeah that's fine. @Uros787 lets do that.

**Comment by thesahindia** [comment] 2022-10-18 22:13
No, I was just asking if we should use `Keyboard.dismiss()` as @Uros787 proposed or if we should find the reason this occurs and solve the root cause.

**Comment by thesahindia** [comment] 2022-10-18 22:18
Since it's an easy fix, I don't have any problem with the use of `Keyboard.dismiss`.

@Uros787's [proposal](https://github.com/Expensify/App/issues/11525#issuecomment-1273728853) will solve the issue. Let's move forward.

C+ reviewed 🎀👀🎀

**Comment by ctkochan22** [comment] 2022-10-20 23:47
@sophiepintoraetz Can you hire @Uros787 ?

**Comment by sophiepintoraetz** [comment] 2022-10-21 01:23
Done - I've invited you @Uros787 - but here's the [link](https://www.upwork.com/jobs/~01e2b71509d8a18788)

**Comment by J-odion** [comment] 2022-10-21 06:24
looking forward to seeing how this turns out
cheers

**Comment by sophiepintoraetz** [comment] 2022-11-02 23:30
@thesahindia can you please [apply for the job](https://www.upwork.com/jobs/~01e2b71509d8a18788) so that I can close this issue out with payment?
(@Uros787 - you're all set!)

**Comment by thesahindia** [comment] 2022-11-03 06:38
Applied🚀

**Comment by sophiepintoraetz** [comment] 2022-11-07 00:25
All right - contract is with you, Sahil!

I've also DM'd and emailed @chauchausoup to apply for the Upwork job to redeem the reporting bonus

**Closed by sophiepintoraetz** 2022-11-07 00:25 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
