### ISSUE TITLE
Contact method - Inconsistent highlighted email behaviour

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22630] opened 2023-07-11 11:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Write a message with an email address in it.
2. Click the email address.
3. An email client (since it is :mailto) opens.
4. Click Settings (profile icon)
5. Click Profile.
6. Click Contact method.
7. Click [receipts@expensify.com](mailto:receipts@expensify.com) (the text itself, not the copy button)
8. Observe copy behaviour.

## Expected Result:
I think the behaviour for all the bold/highlighted emails in the app should be consistent - either copying or opening the email client - otherwise it is not intuitive and user does not know what to expect.

## Actual Result:
 Different behaviours for bold/highlighted emails in various parts of the app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.39-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/206c9c7d-7617-4f24-8112-a1aa3c35ab69

https://github.com/Expensify/App/assets/93399543/8976d6e2-0457-49db-a8fc-b3bbad319692

**Expensify/Expensify Issue URL:**
**Issue reported by:** requested 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689048128813999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by shawnborton** [comment] 2023-07-11 11:53
This is not a bug, this is intentional. Closing.

**Closed by shawnborton** 2023-07-11 11:53 UTC
Labels: NewFeature, Bug
