### ISSUE TITLE
[$500] Room - For WS added as member, title is displayed but for room, title is not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33903] opened 2024-01-03 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Copy phone number +15082211111
3. Tap on profile icon---- Workspaces----- Workspace
4. Tap on members
5. Tap invite
6. Paste the number +15082211111
7. Tap invite
8. Note, in newly added members list, number is added with title.
9. Navigate to LHN
10. Tap in a room chat
11. Tap header--- members--- Invite
12. Paste the number
+15082211111
13. Tap invite
14. Note, in newly added members list, number is added with title but disappeared within seconds.

## Expected Result:
If specific number contact +15082211111, added to workspace, displayed with title. Similarly, the same number contact added to room, must be displayed with title and title must not be disappeared.

## Actual Result:
If specific number contact +15082211111, added to workspace, displayed with title but same number contact added to room, displayed with title for a second and then title disappeared.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7fc5815e-b159-4557-872f-6f3f98ff6dfc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012834976e9aca901a</li>
        <li>Upwork Job ID: 1742635293250863104</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28081124</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-03 20:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For WS added as member, title is displayed but for room, title is not displayed

### What is the root cause of that problem?
When the `displayName` is empty we are not giving the login as a fallback
### What changes do you think we should make in order to solve the problem?

We should pass the login as a fallback for`displayName` empty case

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-03 20:40
This may be fixed as a part of https://github.com/Expensify/App/issues/31312, where the getDisplayName methods should be consolidated, and the fallback to login will be standard practice.

**Comment by koko57** [comment] 2024-01-04 10:28
@paultsimura Thanks for mentioning https://github.com/Expensify/App/issues/31312! Yes, @puneetlath I think it can be done as a part of the refactor 🙂

**Comment by puneetlath** [comment] 2024-01-04 15:13
Great, makes sense to me. I'll assign you to this one as well @koko57

**Comment by s77rt** [comment] 2024-01-09 00:51
@puneetlath Can we put this on hold for https://github.com/Expensify/App/pull/33930

**Comment by koko57** [comment] 2024-01-09 09:47
I tried to recreate the original issue but I couldn't. Unfortunately, I didn't record the trial with the number from the steps: +15082211111. I tried with other numbers and got this result:

https://github.com/Expensify/App/assets/28020445/8a6869c7-4bef-42d4-a7d7-c0ab817463e5

So either it's fixed and we have a login (here phone number) displayed as a fallback or there's something wrong with a particular phone number. @kbecciv if the issue still exists could you provide another number to test? 

I've noticed another issue while trying to recreate the original bug - it doesn't happen all the time, I only experienced it a few times - the item with the user name disappears when choosing the invitee (checking the checkbox) 

https://github.com/Expensify/App/assets/28020445/13be909f-5e12-4c4e-9d64-ad5b4647978b

**Comment by koko57** [comment] 2024-01-09 18:11
@kbecciv could you please confirm it's still reproducible?

**Comment by kbecciv** [comment] 2024-01-10 16:16
@koko57 Issue is reproducible with Phone number +15082211196

https://github.com/Expensify/App/assets/93399543/19f84c80-b1b6-439e-bf0d-30f7131ae49a

**Comment by koko57** [comment] 2024-01-11 11:22
@kbecciv I couldn't recreate it :/ 

https://github.com/Expensify/App/assets/28020445/abb24876-9249-4e91-9274-49386bdce5db

**Comment by puneetlath** [comment] 2024-01-12 20:14
Let's close this then. Feel free to comment/reopen if anyone is able to consistently reproduce.

**Closed by puneetlath** 2024-01-12 20:14 UTC
Labels: External, Daily, Bug
