### ISSUE TITLE
[$500] Workspace - Some of the new worspace chats name is "Chat Report"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39340] opened 2024-03-31 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Log in with a new expensifail account
2. Create a workspace
3. Invite 3 new expensifail members who doesn't have expensify account yet
4. Navigate to the LHN
5. Click on any WS chats named "Chat Report"

## Expected Result:
Workspace chat name should appear with member name

## Actual Result:
Some of the new worspace chats name is "Chat Report". It changes back if you click on it.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/deac79f4-da1a-45fd-9ddd-285994b918ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de6cc9a1328c3268</li>
        <li>Upwork Job ID: 1774955282860523520</li>
        <li>Last Price Increase: 2024-04-02</li>
    </ul>
</details>

**Comment by yuwenmemon** [comment] 2024-04-01 23:57
![Screenshot 2024-04-01 at 4 56 42 PM](https://github.com/Expensify/App/assets/4741899/a3bd60bf-e0bc-49be-a77a-2a571bda708a)

They also show up has `Hidden` in the workspace

**Comment by yuwenmemon** [comment] 2024-04-02 00:17
Seems like we're somehow not properly falling back on the email on staging.

**Comment by AMohamedAakhil** [comment] 2024-04-02 00:57
Proposal
Please re-state the problem that we are trying to solve in this issue.
Some of the new worspace chats name is "Chat Report"

What is the root cause of that problem?
Chat names not being refetched

What changes do you think we should make in order to solve the problem?
1. Invalidate chat names fetched, as workspace is created and members are invited. 

What alternative solutions did you explore? (Optional)
NA

**Comment by AMohamedAakhil** [comment] 2024-04-02 00:59
Contributor details
Your Expensify account email: a.aakhilmohamed@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0116333babf287853b

**Comment by AMohamedAakhil** [comment] 2024-04-02 00:59
Proposal
Please re-state the problem that we are trying to solve in this issue.
Some of the new worspace chats name is "Chat Report"

What is the root cause of that problem?
Chat names not being refetched

What changes do you think we should make in order to solve the problem?

Invalidate chat names fetched, as workspace is created and members are invited.
What alternative solutions did you explore? (Optional)
NA

**Comment by Pranav2612000** [comment] 2024-04-02 03:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Chats created on inviting new members to a workspace are called "Chat Reports"

### What is the root cause of that problem?
On inviting a new member, we call `addMembersToWorkspace` ( https://github.com/Expensify/App/blob/16525e6d24859c0a396c2693205ad008e3cc999e/src/libs/actions/Policy.ts#L1279 )
which calls `createPolicyExpenseChats` ( https://github.com/Expensify/App/blob/16525e6d24859c0a396c2693205ad008e3cc999e/src/libs/actions/Policy.ts#L1182 ).
In this function, we build an optimistic chat report for each user ( https://github.com/Expensify/App/blob/16525e6d24859c0a396c2693205ad008e3cc999e/src/libs/actions/Policy.ts#L1212 ) with the `reportName` as undefined. Due to this, in `buildOptimisticChatReport` the default chat report name ( i.e. `Chat Report` ) is [set](https://github.com/Expensify/App/blob/16525e6d24859c0a396c2693205ad008e3cc999e/src/libs/ReportUtils.ts#L3713)

### What changes do you think we should make in order to solve the problem?
To solve the problem, we can use the `email` as the `reportName` param to the `buildOptimisticChatReport` function call for each new member in `createPolicyExpenseChat`. This would look something like this - 
```
const optimisticReport = ReportUtils.buildOptimisticChatReport([sessionAccountID, cleanAccountID], email, CONST.REPORT.CHAT_TYPE.POLICY_EXPENSE_CHAT, policyID, cleanAccountID);
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by yuwenmemon** [comment] 2024-04-02 04:41
@Pranav2612000 Are you able to identify the PR in the latest [Staging deploy](https://github.com/Expensify/App/issues/39222) that would be at the heart of your root cause?

**Comment by mollfpr** [comment] 2024-04-02 04:55
@yuwenmemon Are you able to repro the issue? I can't reproduce the issue on the latest `main` or staging.

**Comment by yuwenmemon** [comment] 2024-04-02 05:03
Yeah I'm able to reproduce on staging with these steps:
1. Create a new workspace
2. Invite 3 brand new accounts to that workspace (the accounts have not been created before)
3. Go to your Chats - you'll see 2/3 Workspace chats are "Chat Report" rather than the email of the user you just invited

**Comment by yuwenmemon** [comment] 2024-04-02 05:05
https://github.com/Expensify/App/assets/4741899/293a93e0-9ced-4c8c-9c72-adf41dc21f5c

**Comment by yuwenmemon** [comment] 2024-04-02 05:14
Hm I do see the discrepancy between staging and production in the back-end! Okay looks like this is not a blocker, thanks @dukenv0307!

**Comment by mollfpr** [comment] 2024-04-02 05:28
I can repro the issue but need to refresh the page after the API `AddMembersToWorkspace` finishes.


https://github.com/Expensify/App/assets/25520267/a72539b3-1d1e-4023-bd4d-01e25b9cd8c5

**Comment by Pranav2612000** [comment] 2024-04-02 05:43
Makes sense.
I can still image some edge cases / scenarios where the "optimistic data" is used. 
Do you think we still need to update the `reportName` in "optimistic data" to use user's `email` instead of the `DEFAULT_REPORT_NAME` ?
Thoughts @yuwenmemon ?

**Comment by yuwenmemon** [comment] 2024-04-02 19:18
Seeing this in my logs:
`Missing optimistic accountID in employeeData, user is using outdated version of new dot`

@bondydaa - I feel like this is related to https://github.com/Expensify/Web-Expensify/pull/41268 somehow. Going to look a little more after lunch here.

**Comment by bondydaa** [comment] 2024-04-02 19:24
heh yeah sorry the backend changes went live for some updates to `AddMembersToWorkspace` but we haven't updated new dot yet so that log line could be a red herring. Or my PR could have broken something too.

This is the other issue we are using for working on getting new dot updated properly to call the updated `AddMembersToWorkspace` API https://github.com/Expensify/App/issues/25592

**Comment by bondydaa** [comment] 2024-04-02 19:26
hmm though if there is a current discrepancy between staging and prod then there is probably something else that changed b/c https://github.com/Expensify/Web-Expensify/pull/41268 has been live for almost a week

**Comment by yuwenmemon** [comment] 2024-04-02 20:44
Okay so most likely it's something we're not sending from App. Based on the API, shouldn't we be sending the optimistic `accountID` [here](https://github.com/Expensify/App/blob/3ca25eeccbfe4cef6c3ab4837ea05b42f96c9955/src/libs/actions/Policy.ts#L1350)?
![Screenshot 2024-04-02 at 1 40 59 PM](https://github.com/Expensify/App/assets/4741899/f24358c5-f329-4b06-a097-a52a82cf9750)

**Comment by bondydaa** [comment] 2024-04-02 20:58
Yeah the client has never sent the optimistic accountIDs to the API. That is part of what needs to be addressed in https://github.com/Expensify/App/issues/25592.

so i don't think those not being present matters too much here. 

the API has always returned accountIDs of which accounts were created though and should still be doing that. 

I'm not sure what is up with staging's response in your screenshot here https://github.com/Expensify/App/issues/39340#issuecomment-2031097428

I would start looking for why `displayName` and `login` aren't present in the data on staging

**Comment by bondydaa** [comment] 2024-04-02 23:56
I'm still only able to reproduce this on staging... it does not seem like a back end thing either with it happening on refresh.

**Comment by yuwenmemon** [comment] 2024-04-02 23:58
I'm able to reproduce it on Prod:
![Screenshot 2024-04-02 at 4 57 36 PM](https://github.com/Expensify/App/assets/4741899/324d5752-034f-4c2e-ad32-22bb1e638904)

It's pretty much as @dukenv0307 describes [here](https://github.com/Expensify/App/issues/39340#issuecomment-2031092872)

**Comment by bondydaa** [comment] 2024-04-03 19:22
I sent this to Yuwen as well 1:1 but I'm wondering if maybe we take this bug as an opportunity to move some of this logic from the API and further into our database layer where ideally any of these types of changes get queued up and sent out to clients. 

We already have a way for this to work so I think then what would/should happen is that once the database layer creates the account and reports it will queue and trigger the update to onyx via pusher and the API then won't get anything back directly from it's call.

One way I found to test this properly was to invite 2+ users to the workspace b/c for me when I would go back to the main view we default to opening 1 of the chat reports which then calls OpenReport and properly loads all the data. The other chats that got created though will show `Chat Report` until you click them and trigger a load.

**Comment by yuwenmemon** [comment] 2024-04-04 00:00
I am inclined to believe this has been sitting around as a bug all along since I could reproduce it on both API code from a week ago and App code from a week ago.

So yeah, maybe what we could do is:

1. Move the relevant portions of this command to auth
2. In addition to sending the personal details of the newly created accounts, and blowing away the optimistic accountIDs, also update the policy expense chat to have the participants reflect the new set of accountIDs (i.e. replace the optimistic one with the real one)

Asking about this in Open Source here: https://expensify.slack.com/archives/C01GTK53T8Q/p1712188777239399

**Comment by kevinksullivan** [comment] 2024-04-11 21:17
bumped yuwen's thread in slack for more input

**Comment by kevinksullivan** [comment] 2024-04-15 19:40
Adding to collect project per [this convo](https://expensify.slack.com/archives/C036QM0SLJK/p1713204057810689)

**Comment by kevinksullivan** [comment] 2024-04-19 17:25
bumped in slack again

**Comment by yuwenmemon** [comment] 2024-04-30 04:55
@Beamanator, Any thoughts on what I posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1712188777239399) a couple of weeks back?

**Comment by Beamanator** [comment] 2024-04-30 07:14
Oofdaaaa - responded, sorry for the delay

**Comment by mvtglobally** [comment] 2024-05-01 14:01
Issue not reproducible during KI retests. (First week)

**Comment by yuwenmemon** [comment] 2024-05-03 18:24
Unable to reproduce as well - soooo... looks like this somehow got fixed by someone somewhere somehow 😅

**Comment by yuwenmemon** [comment] 2024-05-03 18:24
Closing this out!

**Closed by yuwenmemon** 2024-05-03 18:24 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Bug
