### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Desktop - RBR - Deleted error notifications reappear after reloading

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27315] opened 2023-09-13 09:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
PDF for the test https://drive.google.com/file/d/1iOhC-C5CFh6x0W_a5ByTbKX8vW6tLTGW/view?usp=sharing

1. Open a New Expensify app
2. Log in with any account
3. Navigate to any report
4. Add a corrupted PDF file as an attachment using the link.
5. Remove the error notification that appears.
6. Refresh the application (CMD+R) or page

## Expected Result:
Deleted error notifications should not reappear after a page refresh or reloading the app

## Actual Result:
Deleted error notifications reappear after refreshing the page or reloading the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.68-15

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/b09fa58f-772a-4eba-b7dd-4debed6d1cae

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109ee3a6201dbf246</li>
        <li>Upwork Job ID: 1702260302620733440</li>
        <li>Last Price Increase: 2023-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 27017995</li>
<li>shubham1206agra | Contributor | 27017996</li>
</ul></li>
    </ul>
</details>

**Comment by programmerkenzi** [comment] 2023-09-15 06:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Desktop - RBR - Deleted error notifications reappear after reloading

### What is the root cause of that problem?
The root cause of this problem appears to be related to how the clearReportActionErrors function handles the deletion of error notifications and the associated report actions. The existing code may not correctly update the state or store data, leading to the reappearance of error notifications upon reloading the application. This issue is specifically observed in the `src/libs/actions/ReportActions.js` file.

### What changes do you think we should make in order to solve the problem?
To address the issue of deleted error notifications reappearing after reloading in the Desktop application, I propose the following changes to the `clearReportActionErrors` function:

In the `src/libs/actions/ReportActions.js` file, I will pass `prevActions` as a parameter to the `clearReportActionErrors` function, allowing us to filter out the deleted item from the list and subsequently set the updated list of actions.


   `src/libs/actions/ReportActions.js`
   ```javascript
   function clearReportActionErrors(reportID, reportAction, prevActions) {
    const originalReportID = ReportUtils.getOriginalReportID(reportID, reportAction);
    if (reportAction.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD) {
        //  Filter out the optimistic action
       const newActions = _.filter(prevActions, (action) => action.reportActionID !== reportAction.reportActionID);
        // set the new actions 
       Onyx.set(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, newActions);
        // If there's a linked transaction, delete that too
        const linkedTransactionID = ReportActionUtils.getLinkedTransactionID(originalReportID, reportAction.reportActionID);
        if (linkedTransactionID) {
            Onyx.set(`${ONYXKEYS.COLLECTION.TRANSACTION}${linkedTransactionID}`, null);
        }



        return;
    }

    Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, {
        [ reportAction.reportActionID ]: {
            errors: null,
        },
    });
}
   ```
![expensify-bug-error-message](https://github.com/Expensify/App/assets/68736908/ca23651d-a9bc-472b-b410-d68340fd6d40)


Please review and let me know if any further information or changes are needed.

**Comment by programmerkenzi** [comment] 2023-09-15 07:00
Contributor details
Your Expensify account email: contact@kenzichen.com
Upwork Profile Link: https://www.upwork.com/fl/kenzichen

**Comment by programmerkenzi** [comment] 2023-09-15 07:04
Contributor details
Your Expensify account email: contact@kenzichen.com
Upwork Profile Link: https://www.upwork.com/freelancers/kenzichen

**Comment by situchan** [comment] 2023-09-18 10:05
@programmerkenzi thanks for the proposals. We can think of better solution.

Still open for proposals

**Comment by programmerkenzi** [comment] 2023-09-18 13:57
## Proposal
[Updated](https://github.com/Expensify/App/issues/27315#issuecomment-1720773017)

**Comment by bfitzexpensify** [comment] 2023-09-21 12:38
Looks like @programmerkenzi's updated proposal is ready for review @situchan

**Comment by situchan** [comment] 2023-09-21 16:24
@programmerkenzi you just copied title in **Please re-state the problem that we are trying to solve in this issue.**
So you seem to agree that it happens only on desktop. Please explain why.

**Comment by programmerkenzi** [comment] 2023-09-22 01:53
> @programmerkenzi you just copied title in **Please re-state the problem that we are trying to solve in this issue.** So you seem to agree that it happens only on desktop. Please explain why.

I apologize for the oversight. I've tested it and found that the issue occurs in all browsers across various platforms. I will update the problem statement. After testing, my solution will address and resolve the issue across all platforms.

**Comment by bfitzexpensify** [comment] 2023-09-25 13:18
How does the updated proposal look @situchan?

**Comment by situchan** [comment] 2023-09-27 11:12
reviewing today

**Comment by situchan** [comment] 2023-09-28 16:31
@programmerkenzi still I don't follow your root cause and solution.
```
        // Delete the optimistic action
        Onyx.merge(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${originalReportID}`, {
            [reportAction.reportActionID]: null,
        });
```
The reason why this code doesn't work should be explained in root cause.
If null value is set, it's expected to be removed in Onyx

**Comment by bfitzexpensify** [comment] 2023-10-02 21:04
It's been 3 weeks since this was reported, I've doubled the bounty

**Comment by shubham1206agra** [comment] 2023-10-03 06:37
## Proposal
### Please re-state the problem that we are trying to solve in this issue

RBR - Deleted error notifications reappear after reloading

### What is the root cause of that problem?

This is due to incorrect flushing of the requests, which are made using `persistedRequests`, i.e., all `API.write()`, which is due to a bug in `remove` method here.

https://github.com/Expensify/App/blob/dcf12b0fe14109b97817f6e134ab6be8a419b4f8/src/libs/actions/PersistedRequests.ts#L29-L40

This is due to the nature of the `splice` method, which also modifies the original array if using referencing. Onyx uses `deepEqual` of the `fast-equals` library, which compares the value sent for set and cache value, but we have used `splice` which also modified the cache value.

Minimal Repro Example

```js
var fastEquals = require("fast-equals")
var x = [[1, 2, 3, 4, 5, 6]];
var y = x[0];
y.splice(0, 1);
console.log(fastEquals.deepEqual(x[0], y), x[0], y);
```

Due to this, this code is triggered

```js
// If the value has not changed, calling Storage.setItem() would be redundant and a waste of performance, so return early instead.
if (!hasChanged) {
    return updatePromise;
}
```

This causes the failure of update of `networkRequestQueue`, which again starts to send requests on reload.

### What changes do you think we should make in order to solve the problem?

Use a shallow copy of persistedRequest before `splice`.

```js
function remove(requestToRemove: Request) {
    /**
     * We only remove the first matching request because the order of requests matters.
     * If we were to remove all matching requests, we can end up with a final state that is different than what the user intended.
     */
    const requests = [...persistedRequests];
    const index = requests.findIndex((persistedRequest) => isEqual(persistedRequest, requestToRemove));
    if (index === -1) {
        return;
    }
    requests.splice(index, 1);
    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, requests);
}
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by shubham1206agra** [comment] 2023-10-03 06:39
Result:

https://github.com/Expensify/App/assets/58412969/b3c92dcd-d724-4e1f-a821-e59ced69b624

**Comment by situchan** [comment] 2023-10-03 16:57
@shubham1206agra thanks for the proposal. I agree with your root cause.

- After applying your solution, 2 api requests are sent to backend. This doesn't happen on main.

<img width="1408" alt="Screenshot 2023-10-03 at 10 54 44 PM" src="https://github.com/Expensify/App/assets/108292595/f971684b-fc21-4b5b-8f91-1b85b78ba564">



- Can we also apply same to save, update? Example cases are needed

**Comment by shubham1206agra** [comment] 2023-10-03 17:00
> @shubham1206agra thanks for the proposal. I agree with your root cause.
> 
> - After applying your solution, 2 api requests are sent to backend. This doesn't happen on main.
> 
> <img width="1408" alt="Screenshot 2023-10-03 at 10 54 44 PM" src="https://github.com/Expensify/App/assets/108292595/f971684b-fc21-4b5b-8f91-1b85b78ba564">
> 
> 

I will check this later
> 
> - Can we also apply same to save, update? Example cases are needed

Ig we can do update
No need for save

**Comment by shubham1206agra** [comment] 2023-10-04 03:39
@situchan I have checked this
This is happening due to a race condition 
We can easily fix this with async await or just adding `persistedRequests = requests` just before `Onyx.set` in the remove/update function.

**Comment by situchan** [comment] 2023-10-04 05:34
@shubham1206agra's [proposal](https://github.com/Expensify/App/issues/27315#issuecomment-1744299388) looks good to me. Let's make sure that the fix doesn't cause any side effect from thorough testing.
🎀 👀 🎀 C+ reviewed

**Comment by bfitzexpensify** [comment] 2023-10-18 19:47
Payment summary: 

Contributor: @shubham1206agra is owed $1500 for work completed and urgency bonus - paid via Upwork ✅ 
C+: @situchan is owed $1500 for work completed and urgency bonus - paid via Upwork ✅

**Comment by bfitzexpensify** [comment] 2023-10-18 19:47
@situchan a reminder to complete the BZ checklist when you get a moment - thanks!

**Comment by situchan** [comment] 2023-10-18 19:53
I think bug existed for long time but just not caught earlier as edge case.
Also this was caught by Applause team, no need another regression test.

**Comment by bfitzexpensify** [comment] 2023-10-19 20:09
Cool, agreed. We're all done here then, closing this one out - thanks everyone!

**Closed by bfitzexpensify** 2023-10-19 20:09 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
