### ISSUE TITLE
Desktop - Unread marker remains after opening chat with new messages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35251] opened 2024-01-26 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33779

## Action Performed:
1. [User A] Send a message to User B.
2. [User B] Open chat with User A.
3. [User B] Switch between chat with User A and different chats.

## Expected Result:
The unread message marker above the new message from User A will disappear.

## Actual Result:
The unread message marker above the new message from User A does not disappear.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/067e439f-e30d-487c-a3b5-d0a07e35edc5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-01-26 14:25
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by arosiclair** [comment] 2024-01-26 20:58
Cannot reproduce on web **v1.4.32-2**. Going to try desktop...

**Comment by arosiclair** [comment] 2024-01-26 21:22
Reproduced on desktop **v1.4.32-2**. It seems like something is marking the report as read when I focus the window and that is causing the bug:

https://github.com/Expensify/App/assets/6833644/bbddc9c3-846b-40e6-8a23-9b0c6d55322e

**Comment by arosiclair** [comment] 2024-01-26 21:36
Seems like this is caused by https://github.com/Expensify/App/pull/34537. cc @FitseTLT @abdulrahuman5196 @hayata-suenaga.

There's another similar blocker. I'm going to ask if both of these can be fixed in the same way.

**Comment by abdulrahuman5196** [comment] 2024-01-28 17:40
https://github.com/Expensify/App/issues/35251 and https://github.com/Expensify/App/issues/35254 are same issue. (We can combine into one issue if required). Since its under the regression period @FitseTLT Should fix this. Kindly assign me as C+ as well. 
On another topic @tienifr 's proposal here https://github.com/Expensify/App/issues/35254#issuecomment-1912292506 works fine.

**Comment by FitseTLT** [comment] 2024-01-28 19:50
Raised [PR](https://github.com/Expensify/App/pull/35292) for these and linked to the original issue 👍

**Comment by mountiny** [comment] 2024-01-29 12:41
Reverted the offending PR

**Closed by mountiny** 2024-01-29 12:41 UTC
Labels: Reviewing, Engineering, Weekly
