### ISSUE TITLE
[Hold for Payment] Emoji selector hides keyboard hides text input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8379] opened 2022-03-30 23:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Action Performed (1):
1. Go to any chat
2. Select any own message
3. Click on Edit Comment
4. Click on Emoji icon

## Expected Result:
Emojis are displayed below the text input box to edit the comment – the text input should still be visible.

## Actual Result:
Emojis are hiding the text input box

## Action Performed (2):
1. Go to any chat
2. Focus the composer.
3. Tap the emoji icon to select an emoji

## Expected Result:
Emojis are displayed below the composer – the composer should still be visible.

## Actual Result:
Emoji selector covers the composer, which is no longer visible.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- mWeb 

**Version Number:** v1.1.49-0
**Reproducible in staging?:** Y
**Reproducible in production?:**  No (new feature)
**Email or phone of affected tester (no customers):** mnata.utest@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/160947820-cd9fea31-a60c-4553-a957-0d7b2b97accc.png" width="40%">

https://user-images.githubusercontent.com/43996225/160947822-19ce1857-e65f-40fb-92e4-949de5f4e539.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
Issue was found when executing #7580

**Comment by stitesExpensify** [comment] 2022-03-31 17:54
Commented on the main emoji picker in edit issue to see if this is a related bug

**Comment by mananjadhav** [comment] 2022-04-01 08:54
While the emoji picker in the edit comment is added with #3245, the behavior is the same as the composer at the moment. When sending a new message too, the input is hidden. IMHO, this should be a feature request.

**Comment by parasharrajat** [comment] 2022-04-01 09:45
I think the issue is a little different. It seems that Editor gets hidden when EmojiPicker is opened not that it is behind the picker. If editor is there but it is behind the picker then I agree it should be Feature Request.

**Comment by stitesExpensify** [comment] 2022-04-04 21:22
Okay so how should we proceed here then? Mark as external and get a fix in?

**Comment by roryabraham** [comment] 2022-04-05 16:51
My take on this issue is that it's an existing bug, not necessarily directly related to the new feature (emoji in the edit comment input). I don't think it's a new feature though – it's a bug.

I'm going to demote this from DeployBlocker to just a regular bug, make it external, and start the price at $500 because it's pretty severe.

**Comment by roryabraham** [comment] 2022-04-05 16:52
GitHub won't let me change the labels 😠

**Comment by roryabraham** [comment] 2022-04-05 16:57
Updated the OP. @NicMendonca as stated above, please start this issue at $500

**Comment by NicMendonca** [comment] 2022-04-05 17:37
Upwork job: https://www.upwork.com/jobs/~0117b13ad85930bd8e

**Comment by NicMendonca** [comment] 2022-04-13 13:13
Doubled: https://www.upwork.com/jobs/~0117b13ad85930bd8e

**Comment by dharmik** [comment] 2022-04-13 14:05
**It's default behavior. Not a 🐞**
When we open keyboard and we are tapping on emoji so new instance will come up it's a modal so keyboard will hide as per default behavior.

Suggestion: We have to change the way how we represent Emojis section. We have to display that emojis inside keyboard which we have to customize it.

@parasharrajat @NicMendonca Any suggestion on it?

**Comment by eVoloshchak** [comment] 2022-04-13 17:33
**Proposal**
When emoji picker is opened, add a `marginBottom` to [ReportActionCompose](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose.js) that is equal to the height of emoji picker. That way, textInput will be visible on top of the picker.

Native:


https://user-images.githubusercontent.com/9059945/163237456-fdc46314-b294-4508-8370-f9284e623786.mp4


mWeb:

https://user-images.githubusercontent.com/9059945/163233545-dfd77b88-7716-4f04-941a-fddd5a0db039.mp4

**Implementation:**

1. Inside [EmojiPickerButton](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerButton.js), add an `onOnen` callback on [this](https://github.com/Expensify/App/blob/c237f3659d843850662d728824aeff6a1a3d587f/src/components/EmojiPicker/EmojiPickerButton.js#L34) line
```javascript
onPress={() => {
    EmojiPickerAction.showEmojiPicker(props.onModalHide, props.onEmojiSelected, emojiPopoverAnchor);
    props.onOpen();
}}
```
2. Then in [ReportActionCompose](https://github.com/Expensify/App/blob/c237f3659d843850662d728824aeff6a1a3d587f/src/pages/home/report/ReportActionCompose.js#L557) we can know whether emoji picker is open, we will track it in `pickerIsVisible` state variable
```javascript
  <EmojiPickerButton
      isDisabled={isBlockedFromConcierge}
      onModalHide={() => {
          this.focus(true);
          this.setState({ pickerIsVisible: false })
      }}
      onEmojiSelected={this.addEmojiToTextBox}
      onOpen={() => this.setState({ pickerIsVisible: true })}
  />
```
3. After that, we add marginBottom to ReportActionCompose's [main container](https://github.com/Expensify/App/blob/c237f3659d843850662d728824aeff6a1a3d587f/src/pages/home/report/ReportActionCompose.js#L405)
```javascript
<View style={[shouldShowReportRecipientLocalTime && styles.chatItemComposeWithFirstRow, { marginBottom: this.getMarginBottom() }]}>
```
4. And implement `getMarginBottom` method
```javascript
  getMarginBottom() {
      if (!this.state.pickerIsVisible || !this.props.isSmallScreenWidth) {
          return 0;
      }

      return styles.emojiPickerList.height + 30;
  }
```
I added 30 to add a small gap between picker and text input, but I'm guessing app has some predefined spacing defined in `styles.js`, which can be used instead

**Comment by parasharrajat** [comment] 2022-04-13 17:48
What is the expected behavior here? input should be shown above the picker menu. ?? cc: @kavimuru @stitesExpensify

**Comment by stitesExpensify** [comment] 2022-04-13 18:05
Yes, you should be able to see the input you're putting the emoji into

**Comment by parasharrajat** [comment] 2022-04-13 18:43
Getting design confirmation https://expensify.slack.com/archives/C01GTK53T8Q/p1649875294455519

**Comment by parasharrajat** [comment] 2022-04-18 07:39
@stitesExpensify Slack is concluded with :do_nothing: What should be the next step here?

**Comment by stitesExpensify** [comment] 2022-04-19 21:29
@NicMendonca let's pay @parasharrajat for being the contributor manager, and pay our base issue rate to @eVoloshchak for his proposal, then we can close the issue.

Thanks for pushing this forward in slack Rajat, and thank you @eVoloshchak for your proposal even though it wasn't used!

**Comment by NicMendonca** [comment] 2022-04-20 13:11
@eVoloshchak @parasharrajat can you both apply to the job please? Thank you! - https://www.upwork.com/jobs/~0117b13ad85930bd8e

**Comment by NicMendonca** [comment] 2022-04-27 13:05
@eVoloshchak paid!

@parasharrajat can you accept the offer please? Thank you!

**Comment by NicMendonca** [comment] 2022-05-03 21:02
paid!

**Closed by NicMendonca** 2022-05-03 21:02 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
