### ISSUE TITLE
App shows an unread count of 1 while no unreads appear in LHN

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#25774] opened 2023-08-23 14:42 UTC
@fedirjh [Here is the relevant Slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1692791817705799).

It seems like the logic in this [PR](https://github.com/Expensify/App/pull/19321) filters what is shown in the LHN as unread/read. However, I have noticed that a room that I have muted might have a new message, causing my unread count to go to 1, but this message does not show up in the LHN. 

However, I see the unread message in Expensify.com:
![image](https://github.com/Expensify/App/assets/2319350/72142087-c637-480f-84f2-c6345817b6ca)

**Comment by shawnborton** [comment] 2023-08-23 14:43
cc @joelbettner @thesahindia @luacmartins @Beamanator as you were reviewers of the potentially offending PR. 

and cc @fedirjh for conversation in Slack.

**Comment by chiragsalian** [comment] 2023-08-24 21:46
Yeah i think this will be solved once this is [live](https://github.com/Expensify/App/pull/25618). Perhaps we can revisit this issue once my PR is live. With my changes even if you muted a chat it will show up in your LHN so this way you should be able to see those unread muted chats.

**Comment by luacmartins** [comment] 2023-08-25 15:52
Thanks for confirming @chiragsalian! Added a hold to this issue.

**Comment by luacmartins** [comment] 2023-08-28 15:19
on hold

**Comment by luacmartins** [comment] 2023-08-30 18:37
still on hold

**Comment by luacmartins** [comment] 2023-09-05 15:58
Yes, we can remove the hold. Is this issue still reproducible?

**Comment by laurenreidexpensify** [comment] 2023-09-07 10:00
@shawnborton @chiragsalian can you confirm if this is still reproducible, or list the repro steps so I can test. thanks!

**Comment by shawnborton** [comment] 2023-09-07 12:26
Hmm well now what's happening is that I have the #announce room for the Lounge Workspace muted, but I still get unreads shown in my LHN for that room. Is that intended?

**Comment by shawnborton** [comment] 2023-09-07 12:49
Curious for @chiragsalian's thoughts on that one.

**Comment by luacmartins** [comment] 2023-09-12 07:37
>Hmm well now what's happening is that I have the #announce room for the Lounge Workspace muted, but I still get unreads shown in my LHN for that room. Is that intended?

@shawnborton so you don't get notifications for it but the LHN still shows something as unread?

**Comment by luacmartins** [comment] 2023-09-12 07:43
Maybe we need to update the logic in [isUnread](https://github.com/Expensify/App/blob/fda0cee2a80d5195ead61ed88ced96ebdef59a54/src/libs/ReportUtils.js#L2646-L2649) to return false if the report is muted?

**Comment by luacmartins** [comment] 2023-09-12 07:48
Just chatted with Jason and apparently this is intended. According to [E.cash: Default Rooms & Room Notifications ](https://docs.google.com/document/d/1xabico6VzVd_biN9qw2LFdLW6Lbr9wpN36etbHTeX8c/edit#heading=h.mnjguil21u0a) design doc, muted chats should count towards the unread count:

`Chat room is bolded as “unread” in LHN, and the chat room moves in the LHN in-line with the existing lastMessage sorting logic in place for DMs`

**Comment by luacmartins** [comment] 2023-09-12 07:49
So I think there's nothing to do here since this is the expected behavior. I'm gonna close the issue. Please reopen if I missed something!

**Closed by luacmartins** 2023-09-12 07:49 UTC
Labels: Daily, Bug
