### ISSUE TITLE
[HOLD for payment 2023-08-03] DEV:  The paid amount appears as 0 after sending a money request between users

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22763] opened 2023-07-12 18:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login as Account A and Account B on 2 devices
2. Account A send money request to Account B
3. Account B send money request back to Account A, with same amount
4. Account B send other money request to Account A (maybe optional)
5. Check the paid amount showing in the report and click to view details

## Expected Result:
The correct paid amount should be displayed.

## Actual Result:
The paid amount appears as 0 and there is error when click to view details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39-7 Dev
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1a17349d-5577-4a96-9d05-bce37d3e3928

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689132698599969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c15b83b5ee2d1b8e</li>
        <li>Upwork Job ID: 1680113093348413440</li>
        <li>Last Price Increase: 2023-07-15</li>
    </ul>
</details>

**Comment by tranvantoan-qn** [comment] 2023-07-12 20:03
Added screenshot and error log for more information:

![Error 2](https://github.com/Expensify/App/assets/10254571/883df73b-cd2f-41c0-855a-59a33466ed1a)
![Error 1](https://github.com/Expensify/App/assets/10254571/d59dca8b-ef6b-402e-9b33-9a4c45f3fcb7)

[console.txt](https://github.com/Expensify/App/files/12032489/console.txt)

**Comment by tranvantoan-qn** [comment] 2023-07-12 20:04
(It didn’t happen initially right after sending the Request Money, but then it started occurring and persisted, even after logging out and logging in again) 

![initially](https://github.com/Expensify/App/assets/10254571/6fb2cef5-a601-4743-adb2-f881744e9ac5)

**Comment by nkuoch** [comment] 2023-07-14 07:37
I saw this bug too, it's because the preview total relies on checking the iouReport, but no iouReport gets returned by the back end because no iouReportID gets returned for the chat once the iou is settled.
To me it happened also previous my PRs. (and I can also reproduce it in prod). I don't see how it ever worked, as auth never returns iouReportID for a chat once it's settled... Or did the getChats query returned some iouReports at some point and not anymore?

I made [this fix](https://github.com/Expensify/App/pull/20821/commits/19df18a8abec3025e26114907085798faca86fdc) to default on the reportAction amount if no iouReport gets returned ... but not sure how reliable it is.

**Comment by tranvantoan-qn** [comment] 2023-07-14 08:15
@nkuoch 
I checked out your branch and now I no longer see the both **sender** and the **amount**
![image](https://github.com/Expensify/App/assets/10254571/fe4450bb-7af9-40ac-91c4-25f2e5ffe3cc)

**Comment by nkuoch** [comment] 2023-07-14 09:10
Can you tell me what you see if you click on the browser Application > IndexedDB > OnyxDB > keyvaluepairs > reportActions_{yourChatReportID}

An open the json with the reportPreview report action > message.

<img width="1728" alt="image" src="https://github.com/Expensify/App/assets/2463975/3bed55c0-3af1-4acf-832c-311afae2ca2a">

**Comment by nkuoch** [comment] 2023-07-14 11:17
Thanks for testing. Can you pull my branch and try again?

**Comment by tranvantoan-qn** [comment] 2023-07-14 11:56
Hi,
It looks much better now as the paid amount is showing, but the **sender name is still missing**, or there is new logic added?
![image](https://github.com/Expensify/App/assets/10254571/46e7707a-96d3-47b1-8933-cc0b0e6c4fad)

**Comment by nkuoch** [comment] 2023-07-14 12:52
Thanks, can you pull my branch and try again?

**Comment by tranvantoan-qn** [comment] 2023-07-14 13:39
![image](https://github.com/Expensify/App/assets/10254571/89b9b4d0-6a8b-4a7d-acd1-6b91e6ae52d4)

It looks really good for me now, both `paid and sender name` are showing

Let me know if I can help you testing it further!

**Comment by tranvantoan-qn** [comment] 2023-07-14 13:50
Ah, sorry, there is one more thing:

It looks like the amount `isn't showing correctly` in the main report, it only get updated to correct value after **clicking on the request to view details then go back** - as explained in the attached image

<img width="1436" alt="Why" src="https://github.com/Expensify/App/assets/10254571/1ea6959d-7c68-4a3f-8c6f-ae657a219c52">

**Comment by adelekennedy** [comment] 2023-07-14 19:37
following along here - I won't be moving this to external for now

**Comment by nkuoch** [comment] 2023-07-15 07:35
Did you originally request 60 or 6000?

Do you mind sharing your steps from scratch (from creating the 2 accounts, make the request etc..). And possibly take a video of it.

**Comment by tranvantoan-qn** [comment] 2023-07-17 05:28
@nkuoch The original request was 6000. But the above issue only happened with the request I created before the fix. 
It works fine if I create new requests

**Comment by adelekennedy** [comment] 2023-07-17 20:50
not overdue conversation above

**Comment by nkuoch** [comment] 2023-07-24 10:11
Will be fixed with https://github.com/Expensify/App/pull/20821

**Comment by adelekennedy** [comment] 2023-08-04 00:01
checking in bugzero cause this one's a little weird

**Comment by adelekennedy** [comment] 2023-08-06 23:10
@tranvantoan-qn I talked this over in Slack - I think in this case even though this was fixed elsewhere you deserve $250 reporting and $250 for help testing

**Closed** 2023-08-06 23:11 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by tranvantoan-qn** [comment] 2023-08-06 23:30
@adelekennedy 
I truly appreciate your consideration!
I've accepted the offer. Thank you!
