### ISSUE TITLE
[hold for payment 2024-07-30] [$250] Chat - Incorrect format is copied to clipboard after copying an edited header with bold markdown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43931] opened 2024-06-18 16:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Inside the compose box paste a header with bold markdown and post it: (e.g. # *header*)
3. Edit the posted comment and append some letters after a space. (e.g # *header* aa)
4. Triple click on the edited comment on step 2
5. Paste it inside the compose box

## Expected Result:
The correct format gets pasted

## Actual Result:
The header markdown is pasted on the first line and the rest of the text is pasted on a new line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7f22f51b-3c2f-4b07-a12f-5ac5c0e3d68f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c865bc9dffbb5438</li>
        <li>Upwork Job ID: 1806067556929314722</li>
        <li>Last Price Increase: 2024-07-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hayata-suenaga</details>

**Comment by lanitochka17** [comment] 2024-06-18 16:27
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-18 16:27
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-06-19 18:04
Adding to live markdown per [this](https://expensify.slack.com/archives/C01SKUP7QR0/p1718735202154699)

**Comment by garrettmknight** [comment] 2024-06-24 20:23
Waiting for SWM to work on this one.

**Comment by BartoszGrajdek** [comment] 2024-06-25 09:46
Hi, I’m Bartosz from SWM `react-native-live-markdown` team. 😄 

I believe this issue is something that could be handled by external contributors, especially considering that it's probably going to require changes just in E/App. WDYT @garrettmknight ?

**Comment by Amoralchik** [comment] 2024-06-27 02:00
Hi there, I can't reproduce it on my latest version. (050641a: Update version to 9.0.2-3)

```
# *Header* s
```

https://github.com/Expensify/App/assets/26862281/4bca4c64-d012-4456-acfb-822c0f354a2a

**Comment by Amoralchik** [comment] 2024-06-28 10:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are adding \n after # in the input when header includes additional tags like `_Text_` or `*Text*` is present in the text.

### What is the root cause of that problem?

We add \n at the end of the line in replaceBlockElementWithNewLine: [here](https://github.com/Expensify/expensify-common/blob/2879643200dcd16041c3fd60799097fe9f188a83/lib/ExpensiMark.ts#L1015)

### What changes do you think we should make in order to solve the problem?
I got stable and successful results changed the first "if" statement conditions to:
```ts
if (text.match(/[\n|>][>]?[\s]?$/) || index === splitText.length - 1 || text === "# ") {
  joinedText += text;
} 
```
https://github.com/Expensify/App/assets/26862281/9d4785a0-aefa-46c3-81af-de9e3d563a6a

**Comment by garrettmknight** [comment] 2024-07-01 15:41
@rushatgabhane can you give this one a look when you get a chance?

**Comment by rushatgabhane** [comment] 2024-07-01 15:44
@Amoralchik's proposal looks good https://github.com/Expensify/App/issues/43931#issuecomment-2196578436

we have unit tests on the library so it should be good 👍 

🎀👀🎀

**Comment by garrettmknight** [comment] 2024-07-03 19:31
@hayata-suenaga can you give this one a look when you get a chance?

**Comment by hayata-suenaga** [comment] 2024-07-04 07:53
sorry I have been sick 🙇 @Amoralchik's proposal looks good to me 😄

**Comment by Amoralchik** [comment] 2024-07-04 19:20
I created the pull request.

**Comment by hayata-suenaga** [comment] 2024-07-08 11:30
reviewing the PR

**Comment by Amoralchik** [comment] 2024-07-25 09:07
Hi there, The changes made [here ](https://github.com/Expensify/expensify-common/pull/744)are now available on staging and ready for testing, by [this](https://github.com/Expensify/App/pull/45556#issuecomment-2249280004) bump expensify-common

**Comment by garrettmknight** [comment] 2024-07-25 09:32
@joekaufmanexpensify just need you to watch this one while I'm out - I'll pick back up when I'm back if it's still going. Thanks!

**Comment by joekaufmanexpensify** [comment] 2024-07-25 12:52
Sounds good! Moving back to weekly as I see PR is in review.

**Comment by rushatgabhane** [comment] 2024-07-25 16:56
Hi, the changes are in production https://github.com/Expensify/App/pull/45556#issuecomment-2249280004

**Comment by Amoralchik** [comment] 2024-07-26 11:19
@joekaufmanexpensify The PR in the App has been closed as the expensify-common update has been completed here: https://github.com/Expensify/App/pull/45556#issuecomment-2249280004. We can either proceed to testing or close it with full payment per the example here: https://github.com/Expensify/App/issues/44835#issuecomment-2248342152.

As mentioned in #44835, #45556 updated the version without following a proper process for issues tracking, and this wasn't the only issue affected. See, for example: #37357 (comment) and #44032 (comment).

**Comment by joekaufmanexpensify** [comment] 2024-07-26 14:46
Got it. Just to make sure my understanding is correct: 


- https://github.com/Expensify/expensify-common/pull/744 was the PR that fixed the actual bug here. 
- Because of the nature of the bug, the fix was brought to production via https://github.com/Expensify/App/pull/45556#issuecomment-2249280004 , which bumped the expensify-common version (alongside some other fixes). 

Is that right? If so, payment would be due 7 days after the fix went to production, which would be 2024-07-30.

**Comment by joekaufmanexpensify** [comment] 2024-07-29 15:16
Awesome. TY! So payment is due tomorrow in that case. We need to pay: 

- @Amoralchik - $250 for PR via Upwork. 
- @rushatgabhane - $250 for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-07-29 15:18
@Amoralchik offer sent for $250!

**Comment by Amoralchik** [comment] 2024-07-29 16:17
@joekaufmanexpensify accepted

**Comment by JmillsExpensify** [comment] 2024-07-29 22:47
$250 approved for @rushatgabhane

**Comment by joekaufmanexpensify** [comment] 2024-07-30 12:56
@Amoralchik $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-07-30 12:56
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-07-30 12:56 UTC
Labels: Reviewing, External, Daily, Bug
