### ISSUE TITLE
[HOLD for payment 2023-10-24] [$1000] Chat - Edit code block inside strike-through moves edited label down

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24281] opened 2023-08-08 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Paste this in composer ->   
![image](https://github.com/Expensify/App/assets/78819774/4dbe39d6-317c-4c90-8fa7-d9f924c1c3ac)
3. Click send -> Edit that message  and add space in between Test
4. Save
5. Again edit same message and put Backticks (`) and tild (~) together and Hit save

## Expected Result:
 Edited label should maintain position

## Actual Result:
 Edited label goes down on editing code block inside strike-through

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.51.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/592c3e91-98d4-4484-be6f-d2abae2d6074

https://github.com/Expensify/App/assets/43996225/7bad3b7f-de7f-44ba-baf7-14314c6226d6

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690918812009579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e64b87477a7b36f2</li>
        <li>Upwork Job ID: 1698540341553090560</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 27140365</li>
<li>DinalJivani | Reporter | 27140369</li>
</ul></li>
    </ul>
</details>

**Comment by yh-0218** [comment] 2023-08-09 17:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edit code block inside strike-through moves edited label down
### What is the root cause of that problem?
Because of Style issue of `<del>` tag in `react-native-render-html` package on iOS.

### What changes do you think we should make in order to solve the problem?
We need to update `react-native-render-html` package.
### What alternative solutions did you explore? (Optional)
We can use other way simply.
```
<del><pre>Test<br /></pre></del><edited ></edited>
```
This is case of issue.
We can update this like this.
```
<del><pre>Test<br /></pre><edited ></edited></del>
```
We can add this function to `applyStrikethrough` function.
https://github.com/Expensify/App/blob/8639fb6847cf20a5335d7f5e0c5329e8529b68c0/src/pages/home/report/ReportActionItemFragment.js#L125

**Comment by mallenexpensify** [comment] 2023-08-23 15:56
@DinalJivani how do you type ` on the keypad on the iOS keyboard in the app?

**Comment by DinalJivani** [comment] 2023-08-24 09:20
@mallenexpensify 
On iOS Keyboard, find Single quote or Apostrophe (‘) Tap and hold that key.


https://github.com/Expensify/App/assets/58871336/838ec4f1-9474-42b8-87a8-1437ea1e7e63

**Comment by mallenexpensify** [comment] 2023-08-29 22:46
Checking on here https://expensify.slack.com/archives/C049HHMV9SM/p1693349126104419?thread_ts=1690918812.009579&cid=C049HHMV9SM

**Comment by mallenexpensify** [comment] 2023-09-04 03:35
Posted this in the [Slack thread above](https://expensify.slack.com/archives/C049HHMV9SM/p1693349126104419?thread_ts=1690918812.009579&cid=C049HHMV9SM)
> Does anyone know why we change the format of text that has markdown when a user attempts to edit the text?  ie. from
~```Test ```~
to
~```
Test
```
~
I'm BZ on [an issue](https://github.com/Expensify/App/issues/24281) where this happens then a bug exists (edited)

From Daniel in the Slack thread above
> So the ``` syntax is for a non-inline code block (vs. ` which is inline) so it automatically converts it to that which adds the line breaks when it goes back and forth from html to markdown. So I think that’s intentional behavior, though that moving of edited def is not.

So, making this `External` to fix the bug where, once edited, we're reformatting the message. 

@anmurali  I'm off this week, can you please keep 👀 on this then I'll snag it back on Monday?  Thx

**Comment by Santhosh-Sellavel** [comment] 2023-09-05 16:08
Can we get a new CME here @Expensify/bug-zero as @mallenexpensify is OOO?

Also, I'm unassigning myself to due low bandwidth, Please assign a new C+ plus here, thanks!

**Comment by Christinadobrzyn** [comment] 2023-09-08 03:11
Just checking here, it looks like we don't have an engineer assigned to this GH for the internal part, is that correct? I'm going to readd the Engineering label. Let me know if I'm missing something!

**Comment by mallenexpensify** [comment] 2023-09-11 06:30
@francoisl I think this can be worked on externally, I was slow to action upon this GH so it went 4-weeks without a hire so it bumped to `Internal`, want to give it another week or two for proposals then take internally if we don't have a hire?

**Comment by francoisl** [comment] 2023-09-11 23:57
Yes, this can be external.

The HTML we store in the backend when you send a message like `~```Test```~` would be `{"html":"<del><pre>Test</pre></del>","lastModified":"xxx"}`, so the issue is most likely happening in the HTML to Markdown conversion logic, which means a change is likely needed in `ExpensiMark`'s [`htmlToMarkdownRules`](https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L241-L246).

**Comment by eVoloshchak** [comment] 2023-09-14 14:17
I agree with @yh-0218's [assessment](https://github.com/Expensify/App/issues/24281#issuecomment-1671848631) of the root cause, this is indeed caused by a `<del>` tag, however

- I'm not sure if applyStrikethrough is the right place to apply the fix, could we do that in [htmlToMarkdownRules](https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L241-L246)?
- Most importantly, why does it work incorrectly only on native platforms? (verified Android also has this problem). Is this an issue with `react-native-render-html` itself? If so, I think it's best we fix it in their repo

**Comment by yh-0218** [comment] 2023-09-18 10:29
Thanks for you replay @eVoloshchak 
We can easily fix this issue.
```
 if (isPendingDelete) {
        return `<del>${html}</del>`;
 }
 if (html.includes(`<del>`)) {
    return `<del>${html.replaceAll(`<del>`, '').replaceAll(`</del>`, '')}</del>`;
 }
 return html;
```
We can update this function.
https://github.com/Expensify/App/blob/d9f35a3b12a0404c4f7db2a458f9c4a6f222b356/src/components/HTMLEngineProvider/applyStrikethrough/index.native.js#L1-L6
Result:
<img width="384" alt="Screenshot 2023-09-18 at 1 29 36 PM" src="https://github.com/Expensify/App/assets/65789015/d4c0c0a8-7684-4778-b7ed-868da8cf99d5">

**Comment by eVoloshchak** [comment] 2023-09-19 11:57
@yh-0218, could you take a look at [this](https://github.com/Expensify/App/issues/24281#issuecomment-1719545885) comment please? Specifically

> why does it work incorrectly only on native platforms? (verified Android also has this problem). Is this an issue with react-native-render-html itself?

We need to figure out **_why_** is this happening

**Comment by yh-0218** [comment] 2023-09-19 21:35
@eVoloshchak I found correct issue. that is not relative with <del> tag. but I am not have rich exp with regExp.
Correct cause of this issue is
```
<any tag><pre>...</pre></any tag>
```
We can change this to
<pre><any tag>...<any tag><pre>
Thanks.

**Comment by eVoloshchak** [comment] 2023-09-21 09:27
@yh-0218, why does it work incorrectly only on native platforms? Is this an issue with react-native-render-html itself?
The main question is **why** is this happening?

**Comment by yh-0218** [comment] 2023-09-21 14:44
@eVoloshchak That is issue with react-native-render-html itself.
`</pre>` is replaced as `</pre> <br />` in react-native-render-html

**Comment by mallenexpensify** [comment] 2023-09-26 07:49
Bumping price to get more 👀.

**Comment by yh-0218** [comment] 2023-09-26 08:32
Cool solution to fix this.

**Comment by eVoloshchak** [comment] 2023-10-02 09:39
Not overdue, awaiting more proposals

**Comment by mallenexpensify** [comment] 2023-10-04 17:11
> @eVoloshchak That is issue with react-native-render-html itself.
</pre> is replaced as </pre> <br /> in react-native-render-html

is this correct for _why_ it's happening @eVoloshchak ? 

I'm unsure what the best next step is here. From the OP
- Click send -> Edit that message and add space in between Test
- Save
After this, the text is presented differently, which I think is the 'bug'

The step after the above
- Again edit same message and put Backticks (`) and tild (~) together and Hit save
When I do this, the text shows correctly

**Comment by mvtglobally** [comment] 2023-10-05 03:05
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment] 2023-10-05 09:27
@mallenexpensify, I can't reproduce this anymore too

There isn't a new `react-native-render-html` version, so this was either fixed by the BE changes or changes to [htmlToMarkdownRules](https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L241-L246)

**Comment by DinalJivani** [comment] 2023-10-05 09:42
@Krishna2323 @eVoloshchak 
Yes, I can't reproduce the Edited label moving down bug,
But while editing message, the format of code is still wrong not sure if that needs to be fixed or not.

https://github.com/Expensify/App/assets/58871336/75712d24-d292-4c52-9a5b-9e812aaf8542

**Comment by DinalJivani** [comment] 2023-10-05 10:01
@Krishna2323 
This was discussed in [Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1693349126104419?thread_ts=1690918812.009579&cid=C049HHMV9SM).

And [this issue](https://github.com/Expensify/App/issues/26490) was reported later than current issue. Not sure what will be next Step 😅 Let's wait for team to review

**Comment by mallenexpensify** [comment] 2023-10-05 23:39
I did some more testing on desktop and here's how bold and italic show 
<img width="189" alt="image" src="https://github.com/Expensify/App/assets/22508304/53c07a52-1b8b-42ff-963b-d03569c2b7e7">

Which makes me think that, whenever code blocks are used with  three ticks the codeblock markdown should take precedence over other markdown since it's intended purpose is to be a block of characters in it's own line.  If we agree on that, then the bug would be that having the `~` before the codeblock should show the same way at the bold and the italic options above do... right?  (sorry if this was discussed before, at some point I was thinking single tick for markdown and not three ticks

**Comment by jeet-dhandha** [comment] 2023-10-08 04:38
I agree with https://github.com/Expensify/App/issues/24281#issuecomment-1749797351 , @mallenexpensify. As slack also does the same thing.

<img width="1162" alt="Screenshot 2023-10-08 at 10 07 36 AM" src="https://github.com/Expensify/App/assets/78416198/97ff0374-dec3-438c-9529-8a06a773884a">

**Comment by jeet-dhandha** [comment] 2023-10-08 05:04
We can C+ @Krishna2323 's Proposal https://github.com/Expensify/App/issues/24281#issuecomment-1748514268.

**Comment by jeet-dhandha** [comment] 2023-10-08 05:05
And we should also add a test to this code in `expensify-common`.
```diff
test('Test code fencing with ExpensiMark syntax outside', () => {
    let codeFenceExample = '# Test1 ```code``` Test2';
    expect(parser.replace(codeFenceExample)).toBe('<h1>Test1 </h1><pre>code</pre> Test2');

    codeFenceExample = '*Test1 ```code``` Test2*';
    expect(parser.replace(codeFenceExample)).toBe('*Test1 <pre>code</pre> Test2*');

    codeFenceExample = '_Test1 ```code``` Test2_';
    expect(parser.replace(codeFenceExample)).toBe('_Test1 <pre>code</pre> Test2_');

+   codeFenceExample = '~Test1 ```code``` Test2~';
+   expect(parser.replace(codeFenceExample)).toBe('~Test1 <pre>code</pre> Test2~');
});
```

**Comment by mallenexpensify** [comment] 2023-10-09 17:05
> as part of this?
@trjExpensify , do you have a link for _this_?

**Comment by mallenexpensify** [comment] 2023-10-09 17:15
ah.. that tracking issue is new to me. 
1. I raised a question about visibility into tracking issues here[ in #bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1696871350674069) 
2. I'm gonna wait to hear back from @Beamanator before taking an action on this issue.

**Comment by trjExpensify** [comment] 2023-10-09 19:00
Yeah, Alex and I were talking about that in the other issue and I agree. He's going to dismantle that tracker, so feel free to move forward here.

**Comment by arosiclair** [comment] 2023-10-11 12:55
@Krishna2323 do not needlessly bump/@mention Expensifiers please

**Comment by DinalJivani** [comment] 2023-10-11 13:14
@trjExpensify 
I have received offer of 50 instead of 250. 
Please check and update.

**Comment by trjExpensify** [comment] 2023-10-11 14:05
>@trjExpensify
I have received offer of 50 instead of 250.
Please check and update.

@mallenexpensify will likely take care of it when we're ready for payments.

**Comment by eVoloshchak** [comment] 2023-10-13 15:13
@Krishna2323, there should be a second PR with updated `expensify-common` hash ([this](https://github.com/Expensify/App/blob/dc1ff84f31ec04206a13489b62f065798e38d7fd/package.json#L99) line)
Unless another PR has already included the last version of `expensify-common`

**Comment by eVoloshchak** [comment] 2023-10-26 13:46
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this, this is the behavior that was implemented initially and we've decided to change it 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: we already have the following item in the reviewer checklist: `If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.`

**Comment by eVoloshchak** [comment] 2023-10-26 13:50
**Regression Test Proposal**

1. Open any report
2. Paste `~```Code```~` into the composer and send the message
3. Verify that the code block text doesn't get strike-through line
4. Verify that there's a `~` symbol above and below the code block
<img width="64" alt="image" src="https://github.com/Expensify/App/assets/9059945/d38a9232-2b8c-4f04-ad18-b54026bb2526">


**Do we agree 👍 or 👎**

**Comment by mallenexpensify** [comment] 2023-10-26 17:15
Issue reporter: @ paid $50 via Upwork
Contributor: @Krishna2323 paid $1500 via Upwork, inc. urgency bonus (deets [here](https://github.com/Expensify/App/issues/24281#issuecomment-1765558559))
Contributor+: @eVoloshchak due $1500 via NewDot, inc. urgency bonus

 Regression Test - https://github.com/Expensify/Expensify/issues/330261

Thanks y'all!

**Closed by mallenexpensify** 2023-10-26 17:15 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by DinalJivani** [comment] 2023-10-27 09:12
> @trjExpensify I have received offer of 50 instead of 250. Please check and update.

@mallenexpensify

**Comment by mallenexpensify** [comment] 2023-10-27 20:37
d'oh, sorry about that @DinalJivani , I was following the auto-amount and should have checked the date the bug was reported.  I bonused you $200 and updated [the comment above](https://github.com/Expensify/App/issues/24281#issuecomment-1781523414) so that it's correct.

**Comment by JmillsExpensify** [comment] 2023-11-01 20:00
$1,500 payment approved for @eVoloshchak based on [this summary](https://github.com/Expensify/App/issues/24281#issuecomment-1781523414).
