### ISSUE TITLE
[HOLD for payment 2024-01-25] [$500] BA - Animation in "One moment" page is smaller than other environments

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33134] opened 2023-12-15 01:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.13-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open Expensify app and log in
2. Go to Settings > Workspaces > Select a workspace > Bank account
3. Initiate the add bank account process until your reach "Company information" form
4. Fill out the form
5. Tap Save & continue, soy the "One moment" page is displayed

## Expected Result:
The animation in "One moment" page should be bigger, like on mWeb covering a larger portion of the screen

## Actual Result:
Animation in "One moment" page is smaller than other environments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6313755_1702594864502!IMG_E2030](https://github.com/Expensify/App/assets/78819774/e4d63310-1c7c-4484-ad6c-a84df1421e65)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ab3b40d6502f686</li>
        <li>Upwork Job ID: 1735477945321639936</li>
        <li>Last Price Increase: 2023-12-15</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 28066410</li>
<li>yh-0218 | Contributor | 28091490</li>
</ul></li>
    </ul>
</details>

**Comment by jasperhuangg** [comment] 2023-12-15 01:52
We don't need to block deploy on this, but we should probably fix this + provide a new animation that matches the light theme.

**Comment by jasperhuangg** [comment] 2023-12-15 01:54
@grgia assigning you since it looks like we'd also need a new animation to match the light theme.

**Comment by yh-0218** [comment] 2023-12-15 08:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
BA - Animation in "One moment" page is smaller than other environments
### What is the root cause of that problem?
incorrect style for Animation.
https://github.com/Expensify/App/blob/4592a7c53a2e8bbbcb440dce8d07ccf165ce1cd3/src/components/ReimbursementAccountLoadingIndicator.js#L42-L43

### What changes do you think we should make in order to solve the problem?
`loadingVBAAnimation` reset `width` and `height`
`loadingVBAAnimationWeb ` is not defined.
### What alternative solutions did you explore? (Optional)

**Comment by grgia** [comment] 2023-12-20 21:09
@alitoshmatov I am reassigning you as C+ for review. I may take this internally, but I'll update in an hour

**Comment by alitoshmatov** [comment] 2023-12-29 19:22
Waiting for @grgia 's update here

**Comment by grgia** [comment] 2024-01-02 23:09
@alitoshmatov apologies, for the delay, let's go ahead and review proposals

**Comment by alitoshmatov** [comment] 2024-01-04 12:56
Reviewing the proposals

**Comment by alitoshmatov** [comment] 2024-01-04 13:09
@yh-0218 What do you mean by resetting width and height? Do you want to change their value?

**Comment by yh-0218** [comment] 2024-01-04 15:34
@alitoshmatov yes. we need to set only width and remove height set.
```
 width: '100%'
```

**Comment by alitoshmatov** [comment] 2024-01-06 09:40
We can go with @yh-0218 's [proposal](https://github.com/Expensify/App/issues/33134#issuecomment-1857471067)

C+ reviewed 🎀 👀 🎀

**Comment by grgia** [comment] 2024-01-09 21:11
all yours @yh-0218 !

**Comment by yh-0218** [comment] 2024-01-10 17:14
Hello, @alitoshmatov [PR](https://github.com/Expensify/App/pull/34243) is ready for review. Thanks.

**Comment by alitoshmatov** [comment] 2024-01-25 09:41
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/13744
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/13744/files#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253ebR541-R542
(Note: Was not able to comment on that PR, [context](https://expensify.slack.com/archives/C02NK2DQWUX/p1706170158155939))

- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- Determine if we should create a regression test for this bug. I am 50/50 on this, provided regression test steps below if others want a regression test
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

- Go to any workspace
- Go to Bank account
- Start entering data manually
- Complete steps until you complete company information
- When `One moment` animation appears, make sure animation is not too small or too big
- 
Do we agree 👍 or 👎

**Comment by alitoshmatov** [comment] 2024-01-25 09:43
@grgia This one is ready for payment.

**Comment by alitoshmatov** [comment] 2024-01-29 13:42
@grgia Kind bump

**Comment by yh-0218** [comment] 2024-02-07 07:48
hi, @alitoshmatov How about my payment?

**Comment by grgia** [comment] 2024-02-21 01:58
@johncschuster 

could you help with [payment for this issue? ](https://github.com/Expensify/App/issues/33134#issuecomment-1897700187)


C+/Contributor owed $500

**Comment by johncschuster** [comment] 2024-02-26 22:12
Sorry I missed your ping, @grgia! I'll work on payment now!

**Comment by johncschuster** [comment] 2024-02-26 22:15
Payment has been issued! Thanks, @alitoshmatov and @yh-0218!

**Closed** 2024-02-26 22:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
