### ISSUE TITLE
[$500] The expense chat doesn't scroll to bottom when we create a distance request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39198] opened 2024-03-28 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1711431374851699

## Action Performed:
1. Go to a WS chat
2. Create a money request
3. Open the expense chat of the request
4. Send some messages or create other requests
5. Scroll to the top of the report
6. Create a distance request in this report
7. After creating this request, notice the report
## Expected Result: 
The report should be scrolled to the bottom as it's when we create other requests like manual or scan

## Actual Result: 
The report isn't scrolled to the bottom

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/41e3ab5b-383e-49bd-80c6-235182206434

https://github.com/Expensify/App/assets/38435837/759e5d5b-3a59-405b-a5fe-043eac729dd3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3b77e7d3b5ad058</li>
        <li>Upwork Job ID: 1775261893332221952</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by nkdengineer** [comment] 2024-03-28 17:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The report isn't scrolled to the bottom

### What is the root cause of that problem?
When we create a new distance request, we always notifyNewAction for the chat report. So if we create this in expense report, this doesn't scroll to bottom

https://github.com/Expensify/App/blob/ad1e214a36af16378bdcc8803c8e47b450485eee/src/libs/actions/IOU.ts#L1417
### What changes do you think we should make in order to solve the problem?
We should do the same way as we do in `requestMoney` here to get the active report and then pass this to `notifyNewAction` function

https://github.com/Expensify/App/blob/ad1e214a36af16378bdcc8803c8e47b450485eee/src/libs/actions/IOU.ts#L2127

https://github.com/Expensify/App/blob/ad1e214a36af16378bdcc8803c8e47b450485eee/src/libs/actions/IOU.ts#L1417

### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-04-01 21:35
@dukenv0307 thanks for reporting this and volunteering to be the reviewer! Is "scrolling to the bottom of the report" a global behavior when other requests are created?

**Comment by nkdengineer** [comment] 2024-04-03 10:17
> Actually, sometime when we open the report, the report doesn't scroll to bottom when we send any action. The RCA of this we're missing scrollToBottomForCurrentUserAction as dependency of this useEffect.
So if the time we open the report the last report action of the report isn't loaded, hasNewestReportAction is always false and then the report never scrolls to bottom.

@dukenv0307 Thanks for your feedback, I also can reproduce this. The RCA is here and I updated proposal https://github.com/Expensify/App/issues/39198#issuecomment-2025737953 with additional RCA and solution to fix this case.

**Comment by nkdengineer** [comment] 2024-04-04 04:39
@dukenv0307 I think we can do that, updated proposal https://github.com/Expensify/App/issues/39198#issuecomment-2025737953 to use ref for `hasNewestReportAction`.

**Comment by aldo-expensify** [comment] 2024-04-04 17:52
@nkdengineer  A note on the proposed solution:

Instead of updating the ref in a `useEffect`, I think it is better if you update the ref right after this line:

https://github.com/Expensify/App/blob/6fb92cf3095fa17758a9199267509b0eccd019fd/src/pages/home/report/ReportActionsList.tsx#L199-L200

so it is never out of sync.

I'm assuming that you recommended to use a ref and not add `hasNewestReportAction` as a dependency of `scrollToBottomForCurrentUserAction` because if we do that, we would have to deal with the subscribe/unsubscribe [here](https://github.com/Expensify/App/blob/6fb92cf3095fa17758a9199267509b0eccd019fd/src/pages/home/report/ReportActionsList.tsx#L348) each time `scrollToBottomForCurrentUserAction` changes thanks to `hasNewestReportAction` changing. Is this correct @dukenv0307 ?

**Comment by nkdengineer** [comment] 2024-04-05 10:12
@dukenv0307 The PR is [here](https://github.com/Expensify/App/pull/39685)

**Comment by nkdengineer** [comment] 2024-05-06 11:58
@johncschuster The PR was [deployed to production](https://github.com/Expensify/App/pull/39685#issuecomment-2069773136) a while ago, could you help with payments here 🙇

**Comment by nkdengineer** [comment] 2024-07-01 12:04
@johncschuster Gentle bump on the [comment above](https://github.com/Expensify/App/issues/39198#issuecomment-2095846628)

**Comment by johncschuster** [comment] 2024-07-02 19:08
Working on this now

**Comment by johncschuster** [comment] 2024-07-02 19:18
Payment has been issued to @dukenv0307 via Upwork.
@nkdengineer can you accept the invite to the job, [here](https://www.upwork.com/nx/wm/offer/102963407)?

**Comment by nkdengineer** [comment] 2024-07-03 04:17
@johncschuster Done! thanks

**Comment by johncschuster** [comment] 2024-07-08 21:58
Paid! Thanks for your patience!

**Comment by nkdengineer** [comment] 2024-08-23 07:04
@johncschuster We can close this issue now.

**Closed** 2024-08-23 17:53 UTC
Labels: Reviewing, External, Monthly, Bug
