### ISSUE TITLE
Header texts in quotes are not aligned vertically in the middle

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18677] opened 2023-05-09 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat and write > # Example in the text composer and hit enter
2. Write > Example in the text composer and hit enter
3. Compare the vertical alignment of the above both comments

## Expected Result:
Both should be aligned vertically in the middle
## Actual Result:
`>Example` is aligned vertically in the middle where as `>#Example` is not aligned vertically in the middle

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0210efd2-63c0-4995-ac5c-2fc2c9f0d93a

<img width="960" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/1a911dd8-ad74-42cb-93d6-bc5af613c9d6">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683643990670769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dukenv0307** [comment] 2023-05-10 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Header texts in quotes are not aligned vertically in the middle
### What is the root cause of that problem?
`h1` tag has default margin top and bottom that is renderer by RenderHTML is 9.38px. 

![Screenshot from 2023-05-10 15-55-59](https://github.com/Expensify/App/assets/129500732/b91642e0-d4e4-4cff-9685-08b0c1935964)

And we set margin bottom 8px for `h1` tag here, but don't set margin top
https://github.com/Expensify/App/blob/18c8f9a3a32661ee5d1b5ccdf2f9a57c9a4f4658/src/styles/styles.js#L136-L139
So that it is not aligned vertically in the middle.
### What changes do you think we should make in order to solve the problem?
We should add style margin top 8px for `h1` tag style in here
https://github.com/Expensify/App/blob/18c8f9a3a32661ee5d1b5ccdf2f9a57c9a4f4658/src/styles/styles.js#L136-L139
### What alternative solutions did you explore? (Optional)
NA

**Comment by adelekennedy** [comment] 2023-05-16 17:32
I think [this](https://github.com/Expensify/App/issues/17367) is related closing for now as that issue is further along

**Closed by adelekennedy** 2023-05-16 17:32 UTC
Labels: Daily, Overdue, Bug

**Comment by Nathan-Mulugeta** [comment] 2023-05-16 17:50
Hey @adelekennedt didn't this issue got deployed to production?
