### ISSUE TITLE
Search - Search history does not show the last 4 card digits

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#52192] opened 2024-11-07 15:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+khcategory18@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51633
## Action Performed:
Precondition:
- User has assigned themselves some virtual cards
1. Go to staging.new.expensify.com
2. Open any report
3. Open search router
4. Enter cardID
5. Select a virtual card
6. Note that it shows last 4 card digits in the search field
7. Hit Enter
8. Go back to report
9. Open search router

## Expected Result:
The search history should show the last 4 card digits, as it will cause confusion if user searches for more than one virtual card

## Actual Result:
The search history does not show the last 4 card digits

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/59ed9952-08b5-4a05-b843-918eb3675683

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sarfaraz01578** [comment] 2024-11-07 19:39
Contributor details
Your Expensify account email: sarfarazghafoor34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018a3960cdaa518f4e

**Comment by sarfaraz01578** [comment] 2024-11-07 19:42
Contributor details
Your Expensify account email: sarfarazghafoor34@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018a3960cdaa518f4e

**Comment by sarfaraz01578** [comment] 2024-11-07 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - Search history does not show the last 4 card digits 

### What is the root cause of that problem?
The root cause of this problem is that the application is not formatting or storing the card ID properly when updating the search history. Specifically, the application does not extract the last four digits of the card ID for display purposes, which leads to confusion when the search history is revisited.

### What changes do you think we should make in order to solve the problem?
Modify the [getFilterCardDisplayTitle](https://github.com/Expensify/App/blob/main/src/pages/Search/AdvancedSearchFilters.tsx#L117) function to display only the last 4 digits of the card ID.
```typescript
function getFilterCardDisplayTitle(filters, cards) {
    const filterValue = filters[CONST.SEARCH.SYNTAX_FILTER_KEYS.CARD_ID];
    
    if (filterValue) {
        const filteredCards = Object.values(cards).filter((card) => filterValue.includes(card.cardID.toString()));
        return filteredCards.map((card) => `**** **** **** ${card.cardID.toString().slice(-4)}`).join(', ');
    }

    return undefined;
}
```
Update the searchAdvancedFilters state to store the card ID properly, ensuring the last 4 digits are displayed in the search history.
```typescript
const updatedFilters = {
    ...searchAdvancedFilters,
    [CONST.SEARCH.SYNTAX_FILTER_KEYS.CARD_ID]: cardID, // Store full cardID or last 4 digits
};
```



### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-11-07 20:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The search history does not show the last 4 card digits

### What is the root cause of that problem?
- In the function to get the display card in case the query string is ```type:expense status:all sortBy:date sortOrder:desc  cardID:21472605```, we are using:

https://github.com/Expensify/App/blob/aedbbde0317b720151a75dbe0b6a7ddea52a20cd/src/libs/SearchQueryUtils.ts#L531-L533

It only display the bank name. If the bank name data is not available, we revert to the card ID. In case of this bug, it only displays "Expensify Card".
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/aedbbde0317b720151a75dbe0b6a7ddea52a20cd/src/libs/SearchQueryUtils.ts#L532
should be updated to:

```
        return filter || cardList[filter]?.bank;
```

### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-11-12 01:20
I can reproduce this. @luacmartins just want a hip check from you on whether this is known? I agree it gets confusing to not show the card you've selected to filter on.

**Comment by luacmartins** [comment] 2024-11-12 01:29
This is known and @Kicu is working on updates to the search results bar to display the correct names and work with autocomplete as well

**Comment by luacmartins** [comment] 2024-11-12 01:29
We can either close or put this on hold for now

**Comment by trjExpensify** [comment] 2024-11-12 01:31
Dope, let's close it then!

**Closed by trjExpensify** 2024-11-12 01:31 UTC
Labels: Daily, Bug
