### ISSUE TITLE
[HOLD for payment 2024-01-04] [HOLD for payment 2024-01-03] [$500] Bank Account - Green square in place of BA icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33602] opened 2023-12-26 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must have connected a bank account to workspace.
1. Open New Expensify app.
2. Go to Settings > Workspaces > Workspace > Bank account.

## Expected Result:
The bank account icon should be displayed on the added account, like the one displayed on the Wallet page.

## Actual Result:
There is a green square in the place of the bank account icon.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/5246ba97-6a65-4464-8410-8fe5d37d4f6b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1b5b4f91e738c9a</li>
        <li>Upwork Job ID: 1739684100655161344</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28070497</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by shubham1206agra** [comment] 2023-12-26 16:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Bank Account - Green square in place of BA icon

### What is the root cause of that problem?

This is happening from https://github.com/Expensify/App/pull/30905/commits/3dc4373a234cc9644b41f238adc8aef7ae5f571d, cause they missed the EnableStep component while refactoring.

### What changes do you think we should make in order to solve the problem?

Add displayInDefaultIconColor in MenuItem in EnableStep


### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-12-26 16:22
<img width="447" alt="Screenshot 2023-12-26 at 9 51 49 PM" src="https://github.com/Expensify/App/assets/58412969/b96fe0de-b7e1-468e-b8a0-6aacf6b223f1">

Fixed

**Comment by shubham1206agra** [comment] 2023-12-26 16:22
@mountiny Can you confirm the icon?

**Comment by mountiny** [comment] 2023-12-26 16:27
@shubham1206agra I think we are not changing the icon right so whatever is supposed to be there now, are you able to create a PR for this? Thanks!

**Comment by shubham1206agra** [comment] 2023-12-26 16:29
@mountiny I need to check one more place where I suspect the problem. I will verify the problem with adhoc build.

**Comment by mountiny** [comment] 2023-12-26 16:39
Making a build of the PR

**Comment by mountiny** [comment] 2023-12-27 00:22
This is CPed and working will need to pay $500 to @shubham1206agra and to @rushatgabhane

**Comment by rushatgabhane** [comment] 2023-12-28 06:51
manual request here https://staging.new.expensify.com/r/923381560208585

**Comment by rushatgabhane** [comment] 2024-01-02 13:44
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by JmillsExpensify** [comment] 2024-01-02 15:31
Still two days to go, though I'm going to handle payment in Expensify anyway. $500 payment approved for @rushatgabhane based on [this comment](https://github.com/Expensify/App/issues/33602#issuecomment-1869838573).

**Comment by NicMendonca** [comment] 2024-01-04 16:21
@shubham1206agra you've been paid via Upwork!

**Comment by NicMendonca** [comment] 2024-01-05 20:54
@rushatgabhane just a bump on the BZ checklist!

**Comment by rushatgabhane** [comment] 2024-01-10 11:34
Checklist here https://github.com/Expensify/App/issues/33602#issuecomment-1874044105
This issue can be closed

**Comment by mountiny** [comment] 2024-01-10 12:31
@NicMendonca we need to pay to @shubham1206agra before closing

**Comment by NicMendonca** [comment] 2024-01-10 19:46
@mountiny yep I did - https://github.com/Expensify/App/issues/33602#issuecomment-1877384236

**Comment by NicMendonca** [comment] 2024-01-10 19:46
@rushatgabhane thanks!

**Closed by NicMendonca** 2024-01-10 19:46 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
