### ISSUE TITLE
[$500] mweb/Safari - Settings - Smart App Banner is not shown on the Workspace Page Detail

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27345] opened 2023-09-13 13:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26172
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Tap on Profile icon
3. Tap on Workspaces
4. Tap on any listed workspace

## Expected Result:
The Smart App Banner should be shown on Workspace Page Detail

## Actual Result:
Smart App Banner is missing on the Workspace Page Detail

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/25a92df6-afb2-4edb-9104-9aef8445e05a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172cb50901906f9d7</li>
        <li>Upwork Job ID: 1702595137900023808</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-09-15 08:07
Reproducible

**Comment by poemsforaphrodite** [comment] 2023-09-15 08:30
i think we agreed to let it be as it is
https://github.com/Expensify/App/issues/8791#issuecomment-1320082103

**Comment by sonialiap** [comment] 2023-09-18 09:00
Thanks Pushpender! Looks like we can't do anything about this, closing

**Closed by sonialiap** 2023-09-18 09:00 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
