### ISSUE TITLE
[$500] Web - Chat created offline with incorrect phone number disappears without any notice or error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27725] opened 2023-09-18 23:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Go offline
3. Create a new chat with an invalid phone number (5555555555555)
4. Send some messages
5. Go online

## Expected Result:
We should show error message that the phone number is invalid (e.g. if using `5555555555555`) as we do on ther platforms.

## Actual Result:
The chat created while in offline mode with the incorrect phone number is created at first, and then randomly disappears without any notice or error message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-8

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd20cd8e-5234-4862-ad2c-2e7462609093

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d0dc9ce11fcd2d6a</li>
        <li>Upwork Job ID: 1707061707929169920</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by michaelhaxhiu** [comment] 2023-09-27 15:57
This is indeed inconsistent with other platforms like chrome, safari, and mobile! I cleaned up the **Expected Result**.

I think we should be showing this error as the number format is clearly invalid whether you are offline or online:

<img width="379" alt="image" src="https://github.com/Expensify/App/assets/13206896/45dabd85-261c-43ab-a5f8-9c7a299f36d1">

Would love C+ input though!

**Comment by michaelhaxhiu** [comment] 2023-09-27 15:59
I'm also re-assigning to another BZ as I'm preparing for sabbatical this Friday. In terms of **next steps**:

- Let's have the C+ help ensure two things (1) The Expected Result makes sense for a user in offline mode and (2) This can be worked on `external` because sometimes, offline mode issues lean toward `internal`

Thanks in advance @mallenexpensify !

**Comment by mallenexpensify** [comment] 2023-10-02 17:31
I was NOT able to reproduce on iOS > Chrome

@lanitochka17 , can you please test again on Windows > Chrome and, after you reconnect to wifi, can you leave it on the chat screen for a little wihle? ~15 seconds?  It took a moment for my chat to update once I connected to wifi. 
Thx

<img width="908" alt="image" src="https://github.com/Expensify/App/assets/22508304/a3b955c7-9a0d-4f1c-b100-492cf56229f3">

**Comment by mallenexpensify** [comment] 2023-10-05 00:48
Thanks @lanitochka17 , closing as two of us weren't able to reproduce

**Closed by mallenexpensify** 2023-10-05 00:48 UTC
Labels: External, Daily, Help Wanted, Bug
