### ISSUE TITLE
Attachment upload of several types has wrong preview

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23372] opened 2023-07-21 20:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to app
2. Open chat
3. Attach .txt file or .svg or anything that will show up like a file (not PDF as it converts to a preview itself)
4. An expensify preview is pops up that has nothing to do with the file
## Expected Result: 
No expensify preview should be visible
## Actual Result:
 An expensify link pops up

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bugSvgFile.webm](https://github.com/Expensify/App/assets/43996225/6e3afd33-a641-4f3c-83fb-f1a18c41cdb5)

[bugtxtfile.webm](https://github.com/Expensify/App/assets/43996225/2905b876-a928-42e0-a18a-a28fad788645)

https://github.com/Expensify/App/assets/43996225/16e51d96-f230-4888-84ce-dbcb33cd99bb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @makiour
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689804697073249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-21 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Attachment upload of several types has wrong preview.

### What is the root cause of that problem?
For video attachment, report action have a message like below.
`<a href=\"https://www.expensify.com/chat-attachments/8765753037344648882/w_a3349f615b947374083796dc8c5667f83e523e2e.txt\" data-expensify-source=\"https://www.expensify.com/chat-attachments/8765753037344648882/w_a3349f615b947374083796dc8c5667f83e523e2e.txt\">1.txt</a>`

This is a valid url, so the `ReportActionsUtils.extractLinksFromMessageHtml` will returns a url, and then  `ExpandURLPreview` API will be called.
https://github.com/Expensify/App/blob/78f8a702512bf8ae91d2fe29e834e8e0c05ae786/src/pages/home/report/ReportActionItem.js#L144-L152
So the url preview is displayed for video attachment.

### What changes do you think we should make in order to solve the problem?
We should add checking whether url is a attachment file.
```js
-   if (_.isEqual(downloadedPreviews.current, urls) || props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
+   if (_.isEqual(downloadedPreviews.current, urls) || props.action.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE || ReportUtils.isReportMessageAttachment(lodashGet(props.action, ['message', 0], {}))) {
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by makiour** [comment] 2023-07-21 21:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue is that attachments are having previews not related just because their HTML links contains a url.

### What is the root cause of that problem?
We are not handling the case of attachment previews links. We need to check if attachment has a previewable link as it is converted to HTML format.
https://github.com/Expensify/App/blob/c9e7f19113e3615cc1d35c4cfbf296d4522547e5/src/pages/home/report/ReportActionItem.js#L150
Here is where we extract the messages urls to be previewed. As the attachment is under HTML format and includes a link. We need to check if link has "chat-attachment" which is part of expensify attachment link. So, we do not need to include them in the URLs, and we can filter them out from the first time. We can handle it here in the regex: https://github.com/Expensify/App/blob/c9e7f19113e3615cc1d35c4cfbf296d4522547e5/src/libs/ReportActionsUtils.js#L217-L228

### What changes do you think we should make in order to solve the problem?
We can change the regex to check if it includes "chat-attachments" as shown in the picture:
![image](https://github.com/Expensify/App/assets/60530038/82aa1531-b170-4f05-a0fa-0fd26ec30a91)


We need to change this line https://github.com/Expensify/App/blob/c9e7f19113e3615cc1d35c4cfbf296d4522547e5/src/libs/ReportActionsUtils.js#L221
and make regex:
`const regex = /<a\s+(?:[^>]*?\s+)?href="(?!.*chat-attachments)([^"]*)"/gi;`

Result:
You can clearly see after the change in the video attached that the URLs containing attachments not returned while others are returned succesfully and preview is shown!
[bugPreview.webm](https://github.com/Expensify/App/assets/60530038/10244267-0b5b-44c9-9037-d916573f3f97)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by bondydaa** [comment] 2023-07-24 19:35
closing this, it's a dupe of https://github.com/Expensify/App/issues/22837 since it's all the same underlying thing. non jpg/img files get uploaded to s3 and then we return a link to the file that can be downloaded.

**Closed by bondydaa** 2023-07-24 19:35 UTC
Labels: Daily, Overdue, Bug
