### ISSUE TITLE
Desktop - There is no secondary WS avatar after the admin paid for the request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22241] opened 2023-07-05 01:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21895
## Action Performed:
1. Have an account that is a member of a workspace and an account that is admin for that account
2. Upload image Workspace avatar
3. Creates a money request from member to that workspace
4. Verify that the avatar of the workspace works properly for the report preview
5. The admin now pays the money request
6. Verify that in the workspace chat, in the member account, the report preview now has the admin avatar with the workspace avatar as a secondary/badge

## Expected Result:
Report preview has the admin avatar with the workspace avatar as a secondary/badge

## Actual Result:
There is no secondary workspace avatar after the admin paid for the request (if WS has image avatar)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.36.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/e319cade-9d2f-425e-9707-eee7567bfe2a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2023-07-05 17:52
Trying to see if either of these ^ are the same

**Comment by Christinadobrzyn** [comment] 2023-07-06 18:56
Dupe of - https://github.com/Expensify/App/issues/21996 closing this one since a contributor is already involved with 21996

**Closed** 2023-07-06 18:56 UTC
Labels: Daily, Bug
