### ISSUE TITLE
[$250] mWeb - Profile-Entering number & comma and saving first&last name shows inconsistent behavior

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46385] opened 2024-07-28 21:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap 3 sections :
profile icon -- profile ,
profile icon -- profile-- legal name,
profile icon- save the world-- I know a teacher
3. Enter 1(number) and comma as first name and last name and try to save it in all three section

## Expected Result:
Entering number & comma and saving first&last name must behave consistently across the app

## Actual Result:
Entering number & comma and saving first&last name behaves inconsistently across the app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0be0bc4c-41e3-4202-8129-b5f79e11e542

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015c78d657370f836b</li>
        <li>Upwork Job ID: 1819336887695900299</li>
        <li>Last Price Increase: 2024-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 103437212</li>
<li>nkdengineer | Contributor | 103437214</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by lanitochka17** [comment] 2024-07-28 21:11
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-28 21:12
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-07-29 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Entering number & comma and saving first&last name behaves inconsistently across the app

### What is the root cause of that problem?
We are using three validate functions and three error messages in three places of the App

https://github.com/Expensify/App/blob/d8d7f7887ea28c70ba71a06be87fcacd2436e2bc/src/pages/settings/Profile/DisplayNamePage.tsx#L49-L50

https://github.com/Expensify/App/blob/d8d7f7887ea28c70ba71a06be87fcacd2436e2bc/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L48-L49

https://github.com/Expensify/App/blob/c486e5627d3787ee7355a120e6d87002ad1ba6e0/src/pages/TeachersUnite/KnowATeacherPage.tsx#L61-L62
### What changes do you think we should make in order to solve the problem?
We should use only one method and one error message, the method and the error message can be discussed. In my opinion, legal name is another case. We can just be consistent for `DisplayNamePage` and `KnowATeacherPage`.

https://github.com/Expensify/App/blob/d8d7f7887ea28c70ba71a06be87fcacd2436e2bc/src/pages/settings/Profile/DisplayNamePage.tsx#L49-L50

https://github.com/Expensify/App/blob/d8d7f7887ea28c70ba71a06be87fcacd2436e2bc/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L48-L49

https://github.com/Expensify/App/blob/c486e5627d3787ee7355a120e6d87002ad1ba6e0/src/pages/TeachersUnite/KnowATeacherPage.tsx#L61-L62
### What alternative solutions did you explore? (Optional)

**Comment by mrandaklak** [comment] 2024-08-02 15:06
![image](https://github.com/user-attachments/assets/6abd304d-d2d4-4c2f-afe3-c5169f89c8f7)
If an application wants to have the most keystroke inputs for first name and last name, use a common function to validate.

**Comment by mihna123** [comment] 2024-08-02 15:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inputing a number into Name field and a comma into Last Name field in "Display Name Page", "Legal Name Page" and "I Know a Teacher Page" show three different error messages.

### What is the root cause of that problem?

All of these pages have different validation methods, which I think is fine because the display name should be more flexible than the legal name (for example numbers are fine in the display name). The cause of the problem is inconsistent
error messages for similar errors:  `privatePersonalDetails.error.hasInvalidCharacter`  and `personalDetails.error.hasInvalidCharacter` are different. `bankAccount.error.firstName` & `bankAccount.error.lastName` error messages that are used in the "I Know a Teacher Page" are different too, but maybe this is intended based on error naming.  

### What changes do you think we should make in order to solve the problem?

One option is to just change the error messages to mach one another. Other option is to use same error message on all three pages, but I think that this is less readable and more confusing. 

Contributor details
Your Expensify account email: mihailonvojinovic@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b24da7a68d33cecb

**Comment by nkdengineer** [comment] 2024-08-08 04:12
@allgandalf The PR is [here](https://github.com/Expensify/App/pull/47027).

**Comment by bfitzexpensify** [comment] 2024-09-04 08:41
I've left this open as the Upwork offer for @nkdengineer remains open for the moment - @nkdengineer, a bump to accept that offer, thank you!

**Comment by nkdengineer** [comment] 2024-09-04 11:20
@bfitzexpensify Thanks for the bump, all good from me now

**Comment by bfitzexpensify** [comment] 2024-09-04 11:27
Thanks! Payment sorted. Let's close this out.

**Closed by bfitzexpensify** 2024-09-04 11:27 UTC
Labels: Reviewing, External, Weekly, Bug
