### ISSUE TITLE
[HOLD for payment 2024-03-20] [$500] Users can enter more characters than the specified limit

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18891] opened 2023-05-13 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the Settings > Profile >Display name
2. Enter a name exceeding the character limit and continue typing  on first name field

## Expected Result:
Users should not enter more than the specified limit of characters
## Actual Result:
Users can enter more characters than the specified limit in the First name and Last name fields and removed extra characters after pressing space button

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e9249874-b82b-4db0-b519-0f38cf300abf

https://github.com/Expensify/App/assets/43996225/57f88ef9-5fa7-4486-a84a-fd1aa14fd930

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683923406716779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a433a674a93990d0</li>
        <li>Upwork Job ID: 1760227161153392640</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 0</li>
<li>dhairyasenjaliya | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-05-22 15:39
No update on #18647 so still on hold

**Comment by laurenreidexpensify** [comment] 2023-05-31 10:28
No update on https://github.com/Expensify/App/issues/18647 so remains on hold again this week

**Comment by joekaufmanexpensify** [comment] 2023-06-07 18:29
Sure!

**Comment by laurenreidexpensify** [comment] 2023-07-04 11:29
Still held on #18647

**Comment by laurenreidexpensify** [comment] 2023-07-11 08:56
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:04
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:23
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-08-08 12:47
Still held on https://github.com/Expensify/App/issues/18647 but it looks like we're close to moving to a proposal being implemented there

**Comment by laurenreidexpensify** [comment] 2023-08-18 14:00
Still held on https://github.com/Expensify/App/issues/18647 - PR nearly up

**Comment by laurenreidexpensify** [comment] 2023-08-30 12:22
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-09-07 11:55
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-09-12 16:29
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-09-20 13:57
Still held on https://github.com/Expensify/App/issues/18647 - seems to be daily action on that one now though

**Comment by laurenreidexpensify** [comment] 2023-10-04 13:23
Still held on https://github.com/Expensify/App/issues/18647 -

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:11
Still held on https://github.com/Expensify/App/issues/18647 -

**Comment by laurenreidexpensify** [comment] 2023-10-18 11:44
Still held on https://github.com/Expensify/App/issues/18647 -

**Comment by laurenreidexpensify** [comment] 2023-10-25 15:39
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-11-08 12:18
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-11-15 11:08
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-11-21 11:40
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-11-30 10:58
Still held on https://github.com/Expensify/App/issues/18647

**Comment by laurenreidexpensify** [comment] 2023-12-14 12:16
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2023-12-20 10:23
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2023-12-29 10:11
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2024-01-09 15:19
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2024-01-15 15:10
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:19
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2024-02-08 17:53
Still held on https://github.com/Expensify/App/issues/18647 which is in review

**Comment by laurenreidexpensify** [comment] 2024-02-15 10:21
Still held on https://github.com/Expensify/App/issues/18647 - payment due 20 Feb!

**Comment by laurenreidexpensify** [comment] 2024-02-19 18:24
Review tomorrow

**Comment by dhairyasenjaliya** [comment] 2024-02-20 11:57
hey @laurenreidexpensify this issue was not part of that PR and I was the author of that, I'm happy to take this one as well since this will be a similar fix as applied to my other changes and I'm adding a proposal for the same

**Comment by dhairyasenjaliya** [comment] 2024-02-20 12:02
### Proposal 

### Please re-state the problem that we are trying to solve in this issue.
 
- Users can enter more characters than the specified limit

### What is the root cause of that problem?

-  The root cause is on current code we have kept maxLength for both display first name and last name and we are not showing any validation error message as per new standards 

### What changes do you think we should make in order to solve the problem?

- As per new limit standard we have added max character set to 100 on legal name and we should add same limit to display name’s as well (but this will also include backend change currently its set to 50 character this need to updated)

- On `DisplayNamePage.js` we need to remove `maxLength` property from both firstName and lastName field so that we can display character limit messages 

- On `DisplayNamePage.js` we also need to add additional condition on `validate` function and add `characterLimitExceedCounter` message if character limit exceed on first name and last name and display `common.error.characterLimitExceedCounter` that will display inputed character and how many character can user add  

``` diff         // First we validate the first name field
        if (!ValidationUtils.isValidDisplayName(values.firstName)) {
            ErrorUtils.addErrorMessage(errors, 'firstName', 'personalDetails.error.hasInvalidCharacter');
         } else if (values.firstName.length > CONST.TITLE_CHARACTER_LIMIT) {
             ErrorUtils.addErrorMessage(errors, 'firstName', ['common.error.characterLimitExceedCounter', {length: values.firstName.length, limit: CONST.TITLE_CHARACTER_LIMIT}]);
       }

        if (!ValidationUtils.isValidDisplayName(values.lastName)) {
            ErrorUtils.addErrorMessage(errors, 'lastName', 'personalDetails.error.hasInvalidCharacter');
         } else if (values.lastName.length > CONST.TITLE_CHARACTER_LIMIT) {
            ErrorUtils.addErrorMessage(errors, 'lastName', ['common.error.characterLimitExceedCounter', {length: values.lastName.length, limit: CONST.TITLE_CHARACTER_LIMIT}]);
       } 
``` 

 ### What alternative solutions did you explore? (Optional)

-  None

**Comment by laurenreidexpensify** [comment] 2024-02-21 08:57
@dhairyasenjaliya cool - let's wait for @aimane-chnaif to review your proposal

**Comment by dhairyasenjaliya** [comment] 2024-02-21 09:14
Just for quick comparison recently we have added a character limit on legal name and other pages and on display name its still old limit of 50 and no message for character exceed 

<img width="377" alt="Screenshot 2024-02-21 at 2 41 50 PM" src="https://github.com/Expensify/App/assets/47522946/54e3445f-ab56-45e0-9e69-b1515c6d5f71">
<img width="380" alt="Screenshot 2024-02-21 at 2 42 02 PM" src="https://github.com/Expensify/App/assets/47522946/13ae484c-9208-4951-a076-1cf87fdd92e8">

**Comment by dhairyasenjaliya** [comment] 2024-02-21 15:29
hey @luacmartins from the backend we have a limit of 50 for first name and last name for the display name page and I think we also need to change that to accept 100 characters from backend as similar we did on legal name page

**Comment by luacmartins** [comment] 2024-02-21 16:07
Sure, I can work on that

**Comment by luacmartins** [comment] 2024-02-21 16:11
@dhairyasenjaliya are you sure there's a 50 char limit? The limit I see on the backend for first/last name is 256 chars.

**Comment by dhairyasenjaliya** [comment] 2024-02-21 16:19
yeah once I override `maxLength` on FE and hit save I can see an error @luacmartins 
<img src=https://github.com/Expensify/App/assets/47522946/fdba34bb-5948-43e8-beac-3a61539fd0cd  width=50%>

**Comment by luacmartins** [comment] 2024-02-21 16:22
Oh lol there's another check later on that uses a hardcoded value instead of the constant. Gonna work on a fix. Thanks for pointing that out!

**Comment by dhairyasenjaliya** [comment] 2024-02-21 16:24
Sounds good 👍

**Comment by luacmartins** [comment] 2024-02-21 16:29
Cool, got a PR up - https://github.com/Expensify/Web-Expensify/pull/40962

**Comment by mvtglobally** [comment] 2024-02-27 16:31
Issue is reproducible during KI retests.

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:54
PR was deployed to prod on 27 Feb

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:58
@aimane-chnaif can you confirm if we need a checklist here?

**Comment by laurenreidexpensify** [comment] 2024-03-12 11:07
Thanks for the catch @aimane-chnaif!

**Comment by ayazhussain79** [comment] 2024-03-12 11:52
@laurenreidexpensify The bug, reported before September 2023 and held for various reasons, is now going to be fixed.

**Comment by laurenreidexpensify** [comment] 2024-03-25 15:57
@ayazhussain79 let's handle your payment in https://github.com/Expensify/App/issues/38941

@aimane-chnaif pls complete checklist above thanks

**Comment by luacmartins** [comment] 2024-03-25 18:44
I don't think that we need to add this case. It's a bit extreme that people would enter more than 100 chars into a name field, so I don't think we need to be explicitly testing this.

**Closed** 2024-03-26 10:19 UTC
Labels: External, Daily, Awaiting Payment, Bug
