### ISSUE TITLE
Desktop - Infinite loading when open App

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10536] opened 2022-08-24 16:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre: App was upgraded and worked normally for around 2 hours
1. Re Open App
2. Try to login with different account

## Expected Result:
User is able to login and works

## Actual Result:
App opens and infinite loading appears, 1 time crashed via reload and return to the spinner.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App - macOS Monterey v. 12.4

**Version Number:** 1.1.89.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Bug5702404_Screen_Shot_2022-08-24_at_10 13 35_AM" src="https://user-images.githubusercontent.com/43996225/186467672-127ac2c5-f167-49fe-9c0e-80430793abff.png">
[Bug5702404_desktop.txt](https://github.com/Expensify/App/files/9417702/Bug5702404_desktop.txt)
<img width="1204" alt="Bug5702404_Screen_Shot_2022-08-24_at_10 41 31_AM" src="https://user-images.githubusercontent.com/43996225/186467677-f1681097-335c-4e05-8833-b9a4f6fded73.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AndrewGable** [comment] 2022-08-24 16:11
Can you please re-test in ~5 minutes? We just pushed a fix via the API side that should fix this once deployed.

**Comment by AndrewGable** [comment] 2022-08-24 16:13
<img width="217" alt="Screen Shot 2022-08-24 at 6 13 18 PM" src="https://user-images.githubusercontent.com/2838819/186469412-0c30df4a-d4fb-4129-a2b6-39c266c0103b.png">

Actually, looking at the logs, this is a confirmed dupe of https://github.com/Expensify/App/issues/10531

**Closed by AndrewGable** 2022-08-24 16:13 UTC
Labels: DeployBlockerCash, Engineering, Hourly
