### ISSUE TITLE
[HOLD for payment 2024-07-17] [$250] Actionable whisper - Whisper options are interactable when the expense is deleted offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43560] opened 2024-06-12 12:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43020
**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline.
3. Go to Self DM.
4. Track an expense.
5. Go to transaction thread.
6. Delete the expense.
7. Back in 1:1 DM, click on any option in actionable whisper.

## Expected Result:
The actionable whisper should not be interactable when the expense is deleted offline.

## Actual Result:
The actionable whisper is interactable when the expense is deleted offline and the options (except Nothing for now) lead to not here page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/280f95b3-4f2a-4c37-b760-c4d0647535ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0102bf6b299104a911</li>
        <li>Upwork Job ID: 1801628978700613798</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 102784394</li>
<li>truph01 | Contributor | 102784396</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by m-natarajan** [comment] 2024-06-12 12:52
@CortneyOfstad FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-12 12:53
We think that this bug might be related to #vip-vsb

**Comment by truph01** [comment] 2024-06-15 08:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The actionable whisper is interactable when the expense is deleted offline and the options (except Nothing for now) lead to not here page.

### What is the root cause of that problem?
- When online, after delete track expense, API ```DeleteMoneyRequest``` return the OnyxData:
```
{
    "html": "What would you like to do with this expense?",
    "resolution": "nothing",
}
```
- With this, the whisper options are not displayed because we have a logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/home/report/ReportActionItem.tsx#L930-L933
- It works as expected in online, but in offline, because when deleting a track expense, we do not set the optimistic data ```"resolution": "nothing"``` to the action whisper, that leads to the current behavior, where the whisper options are still displayed.
### What changes do you think we should make in order to solve the problem?
- In general, we need to optimistically set the ```"resolution": "nothing"``` to the whisper action when deleting expense. And restore that data in case the API is failed.



### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-06-15 09:14
## Proposal
  
### Please re-state the problem that we are trying to solve in this issue.
- The actionable whisper is interactable when the expense is deleted offline and the options (except Nothing for now) lead to not here page.

### What is the root cause of that problem?
- When online, after delete track expense, API ```DeleteMoneyRequest``` return the OnyxData:
```
{
    "html": "What would you like to do with this expense?",
    "resolution": "nothing",
}
```
- With this, the whisper options are not displayed because we have a logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/home/report/ReportActionItem.tsx#L930-L933
- It works as expected in online, but in offline, because when deleting a track expense, we do not set the optimistic data ```"resolution": "nothing"``` to the action whisper, that leads to the current behavior, where the whisper options are still displayed.
### What changes do you think we should make in order to solve the problem?
- In general, we need to optimistically set the ```"resolution": "nothing"``` to the whisper action when deleting expense. And restore that data in case the API is failed.

- To do it, in this logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/libs/actions/IOU.ts#L5557
we can call ```getDeleteTrackExpenseInformation``` with ```actionableWhisperReportActionID``` param is the ```actionableWhisperReportActionID```  of the deleted transaction and ```resolution``` param is 'nothing'.



### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-06-15 10:02
I updated the [solution](https://github.com/Expensify/App/issues/43560#issuecomment-2169234961) to add more detail about the implementation

**Comment by truph01** [comment] 2024-06-16 04:51
I added the alternative [solution](https://github.com/Expensify/App/issues/43560#issuecomment-2169234961)

**Comment by CortneyOfstad** [comment] 2024-06-17 18:15
@rojiphil can you review the proposals from @truph01 by EOD? Thank you!

**Comment by rojiphil** [comment] 2024-06-17 20:38
Thanks for your proposals. 
@Krishna2323 [proposed](https://github.com/Expensify/App/issues/43560#issuecomment-2163255613) to disable the buttons of the whisper action.

Whereas @truph01 [proposed](https://github.com/Expensify/App/issues/43560#issuecomment-2169234961) to prevent displaying the whisper action which goes in sync with online behavior. The main solution of optimistically setting the "resolution": "nothing" to the whisper action LGTM. 
🎀👀🎀 C+ reviewed

**Comment by cristipaval** [comment] 2024-06-18 08:38
@jasperhuangg could you please help me triage this issue? I'm not sure what is the expected behavior here.

**Comment by truph01** [comment] 2024-06-18 18:38
@jasperhuangg When we call API ```DeleteMoneyRequest```, BE returns ``` "resolution": "nothing"``` for the whisper action. So we also need to add it to optimistic data, right? Currently, we don't and it does not follow our [Offline UX Patterns](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md).

**Comment by truph01** [comment] 2024-06-18 18:46
Updated [comment](https://github.com/Expensify/App/issues/43560#issuecomment-2176731793)

**Comment by jasperhuangg** [comment] 2024-06-18 19:00
@truph01 ah thanks for that context, I wasn't aware of that. If for some reason the API command fails then we should just be sure to also set failure data. Let's move forward with your proposal.

**Comment by truph01** [comment] 2024-06-19 07:12
@rojiphil PR https://github.com/Expensify/App/pull/43977 is ready

**Comment by CortneyOfstad** [comment] 2024-06-25 17:43
PR is actively being reviewed!

**Comment by CortneyOfstad** [comment] 2024-07-01 18:03
Has been committed to main, just waiting on staging and production!

**Comment by CortneyOfstad** [comment] 2024-07-18 14:03
So the title is incorrect and this needs to be paid. 

@rojiphil can you please complete the checklist by EOD? Thank you and sorry for the short notice!

**Comment by rojiphil** [comment] 2024-07-19 06:46
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/38709)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/38709/files#r1683889216)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. Existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. :  Since this feature was not implemented before, we can add the test case to the existing list of test cases for this track expense feature.
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

Test Steps
	1	Go offline.
	2	Navigate to Self DM.
	3	Track an expense.
	4	Go to transaction thread.
	5	Delete the expense.
	6	Verify that the actionable whisper is not displayed.

**Comment by rojiphil** [comment] 2024-07-19 06:47
> can you please complete the checklist by EOD?

@CortneyOfstad Checklist is done.

**Comment by CortneyOfstad** [comment] 2024-07-19 19:52
## Payment Summary

@rojiphil — paid $250 via Upwork
@truph01 — paid $250 via Upwork

## Regression Test

https://github.com/Expensify/Expensify/issues/414055

**Closed by CortneyOfstad** 2024-07-19 19:52 UTC
Labels: External, Daily, Awaiting Payment, Bug
