### ISSUE TITLE
[HOLD for payment 2023-12-29] [$1000] IOU - Hmm, not there screen briefly displayed when deleting one IOU out of several

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28969] opened 2023-10-06 00:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Navigate to a chat without previous IOUs
3. Send 3 money requests
4. Open money request detail screen
5. Tap three dots and delete a money request

## Expected Result:
User is navigated to the money request preview

## Actual Result:
"Hmm, not there" briefly is shown while navigating to the IOU preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.78-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/be9f2197-336d-4599-858d-fb7ae416a79f

![Bug6226595_1696547640453!Screenshot_2023-10-05_191151](https://github.com/Expensify/App/assets/78819774/b66071d3-a843-4287-b8cb-ac7bd56b8052)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146ac43978a445e18</li>
        <li>Upwork Job ID: 1710217485696090112</li>
        <li>Last Price Increase: 2023-12-08</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28053787</li>
<li>dukenv0307 | Contributor | 28053789</li>
</ul></li>
    </ul>
</details>

**Comment by s77rt** [comment] 2023-10-06 16:44
@ZhenjaHorbach Thanks for the proposal. Your RCA is correct. But the solution looks like a workaround. The not found page should not be coupled with the focus state as it's unrelated.

**Comment by s77rt** [comment] 2023-10-06 16:51
@dukenv0307 Thanks for the proposal. Your RCA makes sense. However the solution won't work correctly in many cases. If the page is not found then we should show the not found view, even if it was accessible before. Otherwise we would have regressions e.g. if you are viewing a report of a workspace then the admin remove you from the workspace then you will still be looking at the same report instead of the not found page because the delete action was done remotely and our navigation will do nothing about it.

**Comment by s77rt** [comment] 2023-10-07 16:11
@dukenv0307 Testing this out. We are getting an infinite skeleton view

| Before | After |
|--------|-------|
|    <video src='https://github.com/Expensify/App/assets/16493223/fdf05080-44c2-4524-87c0-3d2af55828b4' />    |     <video src='https://github.com/Expensify/App/assets/16493223/3193bb27-6f14-4376-827b-7ede3b4af7df' />  |

**Comment by s77rt** [comment] 2023-10-10 15:37
Not overdue. Still looking for proposals

**Comment by flaviadefaria** [comment] 2023-10-12 10:45
@lschurr  I'm officially no longer in the BugZero team so reassigning this as it will not close until tomorrow.

**Comment by lschurr** [comment] 2023-10-16 15:52
Looks like we're still waiting for proposals.

**Comment by mvtglobally** [comment] 2023-10-17 15:12
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment] 2023-10-19 15:50
@s77rt are you able to reproduce this one?

**Comment by s77rt** [comment] 2023-10-19 20:14
@lschurr

I can't reproduce this any more

https://github.com/Expensify/App/assets/16493223/46a53359-5d39-46f3-89f3-1fb70bcacd2d

![28969](https://github.com/Expensify/App/assets/16493223/70bcf812-c09d-41fe-ab8d-8f84e3dbf92d)

**Comment by lschurr** [comment] 2023-10-19 20:20
Cool - closing.

**Comment by s77rt** [comment] 2023-11-10 15:03
@dukenv0307 Indeed I can reproduce the bug again.


https://github.com/Expensify/App/assets/16493223/2d32de71-1dcf-4816-b20e-fdca95c6df48

**Comment by s77rt** [comment] 2023-11-10 15:03
@lschurr Can we reopen this?

**Comment by lschurr** [comment] 2023-11-13 06:22
Are we still waiting for proposals @s77rt?

**Comment by s77rt** [comment] 2023-11-13 08:05
@lschurr Yes, still looking for proposals

**Comment by s77rt** [comment] 2023-11-18 22:49
Not overdue. Still looking for proposals

**Comment by lschurr** [comment] 2023-11-21 15:14
Still looking for proposals.

**Comment by s77rt** [comment] 2023-11-24 18:51
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2023-11-27 14:06
Still looking for proposals

**Comment by lschurr** [comment] 2023-12-01 06:55
Increased the bounty since we still don't have proposals.

**Comment by lschurr** [comment] 2023-12-04 16:13
@s77rt - thoughts on this one? should we ask a contracted agency to pick this up?

**Comment by s77rt** [comment] 2023-12-04 16:53
@lschurr Yes, that sounds good to me 👍

**Comment by s77rt** [comment] 2023-12-06 15:45
@dukenv0307 Thanks for the update! The suggested solution so far seems to only work if the second user is within the money request report. But if he is the iou report the infinite skeleton will be displayed.


https://github.com/Expensify/App/assets/16493223/b5146ca9-7278-44b2-bbc2-98977b507b6f




PS: When working with the redirection useEffect please make sure that we are not introducing any of these bugs https://github.com/Expensify/App/issues/30020 https://github.com/Expensify/App/issues/30062

**Comment by s77rt** [comment] 2023-12-06 19:55
@dukenv0307 I'm not totally sure how this is expected to work. Did you manage to get it working?

**Comment by s77rt** [comment] 2023-12-11 10:37
Not overdue. Still looking for proposals

**Comment by s77rt** [comment] 2023-12-12 16:04
@dukenv0307 This is looking good so far. Can you please update your proposal including the fix for both the iou report and the money request report

**Comment by s77rt** [comment] 2023-12-13 15:20
@dukenv0307 Thanks for the update. The solution looks good.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/28969#issuecomment-1750717885)

**Comment by francoisl** [comment] 2023-12-13 17:51
Works for me!

**Comment by lschurr** [comment] 2023-12-22 19:40
Could you work on the checklist for this one @s77rt

**Comment by s77rt** [comment] 2023-12-22 21:30
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/10452
- The offending PR has been commented on: https://github.com/Expensify/App/pull/10452#discussion_r1435351925
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: I don't think this qualify for a regression test

**Comment by s77rt** [comment] 2023-12-22 21:30
@lschurr Done!

**Comment by lschurr** [comment] 2023-12-28 18:34
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: @dukenv0307 $1000
- Contributor+: @s77rt $1000

**Comment by lschurr** [comment] 2023-12-29 17:47
Payments issued in Upwork. Closing this one out :)

**Closed by lschurr** 2023-12-29 17:47 UTC
Labels: External, Daily, Awaiting Payment, Bug
