### ISSUE TITLE
[$250] Web - Request money- Copy icon on Scan page is displayed below the text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26607] opened 2023-09-03 15:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website on Android
2. Click on + > Request money > Scan

## Expected Result:
Copy icon on Scan page is displayed in the same line with text

## Actual Result:
Copy icon on Scan page is displayed below the text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![16](https://github.com/Expensify/App/assets/93399543/0a010c1c-3c92-4daa-b106-d9228eabb7a8)

![Screenshot_20230903_110725_Chrome](https://github.com/Expensify/App/assets/93399543/c1a64845-b6fc-4e6b-87f3-1d0d6dec5706)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693372914126379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01230e5b7ac07d0a5e</li>
        <li>Upwork Job ID: 1698836140237864960</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26607219</li>
<li>mahmudjontoraqulov | Reporter | 26607222</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-03 15:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy icon is displayed below text.

### What is the root cause of that problem?
The icon is not embedded in the Text component.

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2023-09-04 23:11
reproducible

**Comment by jjcoffee** [comment] 2023-09-05 14:51
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-09-06 15:28
Unable to reproduce on latest staging (v1.3.64-2). Can anyone else?

**Comment by jjcoffee** [comment] 2023-09-06 15:39
@rmm-fl I don't think we design for <320px since almost no devices have that screen size. I imagine the padding has been adjusted since the original issue was created, which probably sorted the issue!

**Comment by jjcoffee** [comment] 2023-09-06 15:50
Sweet, good catch! It's a bit of an unusual device size but probably still worth fixing as it will be affecting other screens too (see below).

I'm happy with @rmm-fl's [proposal](https://github.com/Expensify/App/issues/26607#issuecomment-1704343201), the RCA is correct and the solution makes sense as it will fix the same issue on other screens, such as the contact methods page:

![image](https://github.com/Expensify/App/assets/27287420/251b3b32-602c-4d1d-8b99-06eb83323bac)

:ribbon::eyes::ribbon: C+ reviewed

**Comment by MonilBhavsar** [comment] 2023-09-11 09:53
Looks good to me too! cc @Expensify/design

**Comment by jjcoffee** [comment] 2023-09-18 15:53
So @rmm-fl has run into an issue on the PR where on native platforms the copy text appears misaligned with the rest of the text like this:
![image](https://github.com/Expensify/App/assets/27287420/6b958138-ea85-4640-81b1-081410706ac4)

@rmm-fl doesn't seem to [think](https://github.com/Expensify/App/pull/27136#issuecomment-1723576020) this is easily fixable, so I think we either need to re-open this for other proposals or just close since it's a fairly minor issue that isn't affecting usability (and only happens at pretty specific screen sizes). cc @adelekennedy

**Comment by jjcoffee** [comment] 2023-09-21 12:24
@adelekennedy Can you re-apply the Help Wanted label and switch back to Daily for this? Unless you think this should be closed. (see my comment [above](https://github.com/Expensify/App/issues/26607#issuecomment-1723790116)).

**Comment by adelekennedy** [comment] 2023-09-21 12:56
oof - it's so small and rare that I don't think it's worth the money to fix @MonilBhavsar for a second opinion

**Comment by jjcoffee** [comment] 2023-09-25 15:03
@adelekennedy We could also just [apply the fix on web](https://github.com/Expensify/App/pull/27136#issuecomment-1723576020) and leave it for native, since the PR is already up and running? (That is if @rmm-fl is still interested!)

**Comment by MonilBhavsar** [comment] 2023-10-09 10:22
Sorry, I missed this ping. We also updated Scan page screen and we no longer have this copy. So we can close this @adelekennedy

**Closed** 2023-10-09 15:29 UTC
Labels: External, Weekly, Bug
