### ISSUE TITLE
Bank account : Console error appears clicking back button on Personal information page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13911] opened 2022-12-30 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Settings >  workspace > Connect bank account > Connect Manually
3. Enter routing number and account number and press continue
4. fill up company information  and press continue
5. fill up personal information  and press continue
6. press back button

## Expected Result:  
should not show any console error

## Actual Result:  
shows console error on click back button

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y 
**Reproducible in production?:** could not test
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210097015-bb4a7b8f-013f-4304-8fed-d4148d81066f.mov

https://user-images.githubusercontent.com/43996225/210097097-fd4a4ff7-b485-46d4-98c7-12000339a90c.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672394805595539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-12-31 00:41
Reproducible (although I had to accept Onfidos terms before clicking back to get the console error)

This looks similar to [Console error appears when clicking Save&Continue without selecting the bank account after successful plaid flow.](https://github.com/Expensify/App/issues/13598#top) which shoud be fixed by https://github.com/Expensify/App/pull/13236 - Is this a dupe @thienlnam ?

**Comment by MitchExpensify** [comment] 2023-01-02 21:57
Not overdue, waiting on a technical buddy check on the question above

**Comment by thienlnam** [comment] 2023-01-03 18:37
Good shout, the error looks different but I'm looks like it will be fixed by https://github.com/Expensify/App/pull/13236

cc @nkuoch to confirm

**Comment by nkuoch** [comment] 2023-01-04 10:41
I confirm

**Comment by MitchExpensify** [comment] 2023-01-04 19:11
Awesome! In that case I think next step is simply to pay @gadhiyamanan reporting bonus and close this

**Comment by MitchExpensify** [comment] 2023-01-04 19:31
Invited to this [Upwork Job](https://www.upwork.com/jobs/~01afdb2ae50dfd1888) for reporting bonus payment

**Comment by MitchExpensify** [comment] 2023-01-04 19:42
Paid and contract ended - Closing

**Closed by MitchExpensify** 2023-01-04 19:42 UTC
Labels: Reviewing, Daily, Bug
