### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Green dot doesn't appear automatically when assigning task to self repeatedly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22149] opened 2023-07-04 02:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a task with no assignee
2. Open the task report.
3. Set the assignee to a random person
4. Set yourself as the assignee
5. Repeat steps 3 and 4 a couple of times.
## Expected Result: 
The green dot in LHN should be visible automatically when assigned to self.
## Actual Result: 
The green dot in LHN is only visible when clicked on another report in LHN.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/eb959ef1-f767-417d-8e6c-b1222728a51e

https://github.com/Expensify/App/assets/43996225/c62c0e8c-e6c8-42fd-a942-dd26e915cd33

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688377006505109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5e85cd8d7e7f90a</li>
        <li>Upwork Job ID: 1677284522382716928</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-07-05 12:45
# Proposal

## Please re-state the problem
Green dot doesn't appear automatically when assigning task to self repeatedly.

## What is the root cause of that problem?
The root cause is that the `OptionRowLHN` (the component which displays the green dot) doesn't get updated when we assign task to self. Now the question arises that when we un-assign ourselves, the component does update but doesn't when we assign it to ourselves.

The answer lies here in the function `Task.setAssigneeValue`:
https://github.com/Expensify/App/blob/11b8908b8ba3282d06543e2808a7c722690521fa/src/libs/actions/Task.js#L486-L498
Here you can see that we are explicitly checking if the assigned user is current user and this is what causes this disparity of updation while un-assigning but no updation when assigning. The line that does the updating is `Report.openReport` on line `498` and as you can see it isn't called when we are setting the assignee to current user.

## What changes do you think we should make in order to solve this problem?
The use of `Report.openReport` I think it to make sure the LHN is updated with the latest assignee chat having their assignment message in the subtitle, but obviously we can't use that for the current user as the current user has nor report.

Notice that after calling `setAssigneeValue`, we are also calling another function called `editTaskAndNavigate`
https://github.com/Expensify/App/blob/f9a8529f18696b2584d57c960933cefdf7b2e6af/src/pages/tasks/TaskAssigneeSelectorModal.js#L166-L172
 
And in `editTaskAndNavigate`, we can see that we are dismissing the task modal in the end.
https://github.com/Expensify/App/blob/f9a8529f18696b2584d57c960933cefdf7b2e6af/src/libs/actions/Task.js#L413
Since we are already dismissing the modal, we can also make sure that the report updates by adding the following line after this:
```js
Report.openReport(report.reportID);
```

## What other alternative approach did you explore (Optional)
N/A

**Comment by NicMendonca** [comment] 2023-07-05 18:39
Trying to reproduce this now

**Comment by NicMendonca** [comment] 2023-07-05 18:43
@esh-g okay I was able to reproduce, but I was also able to reproduce on MacOS desktop. Can we please confirm all the platforms in which this is happening to ensure parity across all? cc @kavimuru

**Comment by StevenKKC** [comment] 2023-07-06 16:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green dot doesn't appear automatically when assigning task to self repeatedly.

### What is the root cause of that problem?
The root cause is that LHN does not re-render when assigning task to self.

If assigning task to self, BE responds only one task report that has a new `managerEmail`.
![Annotation 2023-07-06 123854](https://github.com/Expensify/App/assets/131836113/6f1b8564-6a58-4990-a31b-cf3fbd196226)

And if assigning task to others, BE will responds two reports.
One is a task report, and another is a assignee's chat report that has a `lastMessageText`.
![Annotation 2023-07-06 123841](https://github.com/Expensify/App/assets/131836113/58582fd6-0d74-4193-b09d-21849657f0ca)

SidebarLinks retrieve reports with `chatReportSelector`, and in this function there is no `managerEmail` property.
https://github.com/Expensify/App/blob/4d08b9dee201dcfeaab5b18e54a78db519bc02e7/src/pages/home/sidebar/SidebarLinks.js#L360-L368
https://github.com/Expensify/App/blob/4d08b9dee201dcfeaab5b18e54a78db519bc02e7/src/pages/home/sidebar/SidebarLinks.js#L282-L302

So when assigning task to self, side bar will not be re-render.
And when assigning task to others, since there is a another chat report which has a `lastMessageText`, side bar will be re-render.

### What changes do you think we should make in order to solve the problem?
We can add `managerEmail` property to `chatReportSelector` as below.
```js
const chatReportSelector = (report) =>
    report && {
        ...
+       managerEmail: report.managerEmail,
    };
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by StevenKKC** [comment] 2023-07-06 17:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Green dot doesn't appear automatically when assigning task to self repeatedly.

### What is the root cause of that problem?
The root cause is that LHN does not re-render when assigning task to self.

If assigning task to self, BE responds only one task report that has `managerEmail`.
![Annotation 2023-07-06 123854](https://github.com/Expensify/App/assets/131836113/5ceadde1-a31f-4da9-99f4-4c42a87eb158)

And if assigning task to others, BE will respond two reports.
One is a task report, and another is a assignee's chat report that has a `lastMessageText`.
![Annotation 2023-07-06 123841](https://github.com/Expensify/App/assets/131836113/7b67ef98-7a9c-4642-8ff0-d247e7e42cca)

SidebarLinks retrieve reports with using `chatReportSelector`, and in this function there is no `managerEmail`.
https://github.com/Expensify/App/blob/01a18f02aeff2c1b7a39c094babba56d3a3c5584/src/pages/home/sidebar/SidebarLinks.js#L365-L368
https://github.com/Expensify/App/blob/01a18f02aeff2c1b7a39c094babba56d3a3c5584/src/pages/home/sidebar/SidebarLinks.js#L282-L302

So when assigning task to self, side bar will not be re-render, so does not appear green dot automatically.
And when assigning task to others, since there is a another chat report which has a `lastMessageText`, side bar will be re-render, and green dot will be disappear.

### What changes do you think we should make in order to solve the problem?
We can add `managerEmail` property to `chatReportSelector` as below.
```js
const chatReportSelector = (report) =>
    report && {
        ...
+       managerEmail: report.managerEmail,
    };
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by NicMendonca** [comment] 2023-07-07 11:09
@esh-g also, I think we don't have to specify "repeatedly". It happens when you assign to self after not self-assigning after the first go around when creating the task - but can you please confirm that on your end?

**Comment by esh-g** [comment] 2023-07-07 11:12
@NicMendonca Yes, it almost always happens when assigning yourself but there was one time that it did update, so I thought of adding `repeatedly` but I don't think its required...

**Comment by NicMendonca** [comment] 2023-07-10 10:16
@mollfpr any thoughts on the above proposals?

**Comment by mollfpr** [comment] 2023-07-10 15:57
Reviewing.

**Comment by mollfpr** [comment] 2023-07-12 16:10
Sorry, I got a problem with updating the NPM. I'll be posting an update in the morning.

**Comment by mollfpr** [comment] 2023-07-13 03:50
Sorry for the delay!

@esh-g Based on the NAVIGATION documentation, we should use `Navigation.dismissModal` to navigate to a report after completing a flow. I also try your solution. It makes the green dot appear, but the task modal is not dismissed.

I agree that the root cause is that the sidebar is not re-render, and we need to add the `managerEmail` as the property that we want to trigger the re-render to `chatReportSelector.`

@StevenKKC I like your detailed RCA. It gives me a lot of information regarding this issue. Unfortunately, @dukenv0307 proposed the solution first. I commend you for great RCA 👍

@dukenv0307 The solution looks good, but the RCA needs more improvement.

@NicMendonca Let's go with @dukenv0307 [proposal](https://github.com/Expensify/App/issues/22149#issuecomment-1621386962).

🎀 👀 🎀 C+ reviewed!

**Comment by mollfpr** [comment] 2023-07-17 14:55
Bump @pecanoro for final review on the PR

**Comment by mollfpr** [comment] 2023-07-25 03:59
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/20808

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/20808/files#r1272970129

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Create a task with no assignee
2. Open the task report
3. Set the assignee to a random person
4. Set yourself as the assignee
5. **Verify** that a green dot appears
6. Set assignee to someone else
7. **Verify** that a green dot disappears
8. 👍 or 👎

**Comment by mollfpr** [comment] 2023-07-25 04:01
@dukenv0307 is eligible for the bonus speed. The assignment is on Jul 13, and my approval of the PR is on Jul 14.

**Comment by NicMendonca** [comment] 2023-07-26 11:37
- @esh-g - reporting $250
- @dukenv0307 - C $1500
- @mollfpr C+ $1500 - paid via Upwork *not* Expensify, correct? Or has this changed?

**Comment by NicMendonca** [comment] 2023-07-26 11:38
@esh-g can you please apply to the job? https://www.upwork.com/jobs/~01d5e85cd8d7e7f90a

**Comment by NicMendonca** [comment] 2023-07-26 11:39
@dukenv0307 you've been paid 🎉

**Comment by mollfpr** [comment] 2023-07-26 11:39
@NicMendonca Yeah, the payment still in Upwork.

**Comment by NicMendonca** [comment] 2023-07-26 11:40
@mollfpr you've been paid!

**Comment by esh-g** [comment] 2023-07-26 13:15
@NicMendonca Applied!

**Closed** 2023-07-27 14:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
