### ISSUE TITLE
Wrong bottom navigation icon is highlighted 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44512] opened 2024-06-27 00:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allgandalf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719437029378469

## Action Performed:

1. Open app
2. Go to search tab
3. Click on any existing report
4. Click on the subtitle
5. Press back button
6. Press back button again

## Expected Result:
User should be on the search page
## Actual Result:
the user is on the Chat page, but in bottom navigation, search tab is highlighted
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/86741512-a789-456f-a2b0-eea68fc2f080

https://github.com/Expensify/App/assets/38435837/57b5776f-7369-481c-861f-c6796f4abdc7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-06-27 08:28
@WojtekBoman @adamgrzybowski this seems to be another task good for you

**Comment by adamgrzybowski** [comment] 2024-06-27 11:12
@mountiny I have pending PR for this bug. But it seems to have some problems after merging the newest main. I will investigate it after other high priority issues

**Comment by puneetlath** [comment] 2024-07-03 19:52
@adamgrzybowski how's it going?

**Comment by adamgrzybowski** [comment] 2024-07-04 10:33
@puneetlath old issues were resolved but the reviewer found one more problem. I will investigate it.

**Comment by Kicu** [comment] 2024-07-09 09:56
@allgandalf from what I understand this issue is a duplicate of this issue: https://github.com/Expensify/App/pull/43998
and the 2nd one is being actively fixed

**Comment by puneetlath** [comment] 2024-07-15 12:40
@allgandalf 43998 is on staging now. I'm going to ask for a re-test.

**Comment by kavimuru** [comment] 2024-07-15 20:28
Not reproduced. 

https://github.com/user-attachments/assets/c8bc39f3-0d42-4890-abf0-af24bdf7c83d

**Comment by puneetlath** [comment] 2024-07-15 20:42
Great, thanks everyone!

**Closed by puneetlath** 2024-07-15 20:42 UTC
Labels: Daily, Bug
