### ISSUE TITLE
[hold for payment 2024-08-26] [$250] Split - Unable to split expense with workspace via FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47159] opened 2024-08-09 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4838511)
**Email or phone of affected tester (no customers):**  applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense > Manual
3. Enter amount > Next
4. Select a workspace > Next
5. Split the expense

## Expected Result:
The expense is split in the workspace chat

## Actual Result:
User is unable to split expense with workspace via FAB
App opens a report with RBR on LHN and the report shows infinite skeleton after splitting expense with workspace via FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/40534103-b2ea-4b92-8445-f731727704af

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fde995cf07525892</li>
        <li>Upwork Job ID: 1821964572979581542</li>
        <li>Last Price Increase: 2024-08-09</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103497009</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-08-09 12:30
We think that this bug might be related to #vip-split

**Comment by grgia** [comment] 2024-08-09 17:40
@hoangzinh could you assess the proposal, I think we can assign @bernhardoj

**Comment by thienlnam** [comment] 2024-08-09 21:46
@grgia Did you mean to remove the App blocker? Looks like this is a FE issue

**Comment by bernhardoj** [comment] 2024-08-11 09:05
> because we're getting the report from an array

`ReportConnection.getAllReports()` doesn't return an array, it's an object.

> Btw, I think it's safer if we check existingChatReportID exists before retrieving existingSplitChatReport from array. What do you think?

That's a good idea. I remember we did that before, but it was changed in this [PR](https://github.com/Expensify/App/pull/37458/files#diff-9c07b44e092fd3d975806649be46d76b75a377c16e32ed86597b630a84c290d0)

**Comment by Beamanator** [comment] 2024-08-12 18:44
@bernhardoj if you could please make this fix a priority, that would be great!

**Comment by Beamanator** [comment] 2024-08-12 18:50
Actually if this was really caused by https://github.com/Expensify/App/pull/42302, this shouldn't be a blocker anymore since https://github.com/Expensify/App/pull/42302 is now in prod 😅

**Comment by bernhardoj** [comment] 2024-08-13 09:15
PR is ready

cc: @hoangzinh

**Comment by joekaufmanexpensify** [comment] 2024-08-19 14:16
PR merged!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:58
Sounds good. TY!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 14:05
All set to issue payment here. We need to pay: 

- @hoangzinh - $250 for C+ via Upwork. 
- @bernhardoj - $250 for PR via Upwork.

**Comment by joekaufmanexpensify** [comment] 2024-08-27 14:07
@hoangzinh $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-27 14:07
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-08-27 14:07
Closing as only thing left here is for @bernhardoj to request payment via NewDot!

**Closed by joekaufmanexpensify** 2024-08-27 14:07 UTC
Labels: Reviewing, External, Engineering, Daily, Bug

**Comment by bernhardoj** [comment] 2024-08-27 14:32
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-28 17:28
$250 approved for @bernhardoj
