### ISSUE TITLE
[Awaiting C+ Payment] [HOLD for payment 2023-08-01] [$1000] Dev: Email address is not displayed on task preview when user assigns task to themselves in DM

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22373] opened 2023-07-06 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a tab where user A is signed-in
2. Open an existing chat with user B
3. Click on 'Actions' icon
4. Click on 'Assign task' link
5. Enter title & click on 'Next' button
6. Click on 'Assignee' & assign the task to yourself
7. Click on 'Confirm task' button
8. Switch to the tab where account B is signed in
9. Open the chat with user A
## Expected Result: 
Task report item should display user A's email address for both user A, and user B
## Actual Result:
User A's email address is not displayed on task report item for user B

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  DEV
**Reproducible in staging?:** Dev only
**Reproducible in production?:** dev only
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b14f2638-c17b-4012-a74a-81bb21c1cb12

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688671191419889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cae9815a84594b7f</li>
        <li>Upwork Job ID: 1678459591028834304</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-07-06 21:39
I can't help repro this on dev, sorry. @thienlnam might be aware of any recent task related PRs that might have caused this.

**Comment by thienlnam** [comment] 2023-07-06 22:36
Definitely not a deploy blocker if it's only on dev

**Comment by trjExpensify** [comment] 2023-07-10 10:39
Are you able to repro though @thienlnam? Would be good to keep it moving if so!

**Comment by ColtonMori** [comment] 2023-07-10 18:35
I have checked this issue on my computer and it runs well.

**Comment by Oleksandrr97** [comment] 2023-07-10 18:45
Contributor details
Your Expensify account email: tokar.oleksandrr97@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012e4006e26ea0c254

**Comment by Oleksandrr97** [comment] 2023-07-10 19:01
I have checked this issue. But expensify is working properly on my browser. I can't see any issue.
It shows email address correctly.

**Comment by thienlnam** [comment] 2023-07-11 17:52
Cool cool, going to close since we're getting multiple unable to reproduce comments - if someone can reproduce this reliably on main, please comment the steps

**Comment by Natnael-Guchima** [comment] 2023-07-12 07:54
Hello @Oleksandrr97 @b4s36t4, can one of you share a video reproducing the issue? I am still seeing the issue on staging. 

[Screencast from 2023-07-12 10-50-20.webm](https://github.com/Expensify/App/assets/57330233/79928ea5-ba6d-4798-93e0-25fe57d1ccfe)

**Comment by Oleksandrr97** [comment] 2023-07-12 09:06
Sorry, I have checked again and I can see that issue.
Yesterday, I have checked it three times and I couldn't see that issue. But I can see today.

**Comment by trjExpensify** [comment] 2023-07-12 09:33
Let's reopen. @thienlnam did you attempt to reproduce? The steps in the OP I think are pretty clear to be able to.

**Comment by Natnael-Guchima** [comment] 2023-07-12 10:09
> Sorry, I have checked again and I can see that issue.
> Yesterday, I have checked it three times and I couldn't see that issue. But I can see today.

No problem 👍

**Comment by mananjadhav** [comment] 2023-07-12 17:13
I can reproduce this as well. The steps are clear and I can reproduce it every time.

**Comment by ShogunFire** [comment] 2023-07-14 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we assign a task to ourself, and share it with someone else, he doesn't see our email before the name of the task

### What is the root cause of that problem?

In TaskPreview here: https://github.com/Expensify/App/blob/76e53bb3a49f00b4dd5cfeb3bc3b4ed219428eb7/src/components/ReportActionItem/TaskPreview.js#L69

We retrieve the account Id of the assigne from the taskReport prop.

But as explained in this comment:
https://github.com/Expensify/App/blob/76e53bb3a49f00b4dd5cfeb3bc3b4ed219428eb7/src/components/ReportActionItem/TaskPreview.js#L62-L64
The taskReport prop can be empty and in this case the information are present in the report action

### What changes do you think we should make in order to solve the problem?

We can retrieve the assigne acount id in the report action when the task report is empty.
I believe the account id of the assignee is present in props.action.actorAccountID

So instead of this:
https://github.com/Expensify/App/blob/76e53bb3a49f00b4dd5cfeb3bc3b4ed219428eb7/src/components/ReportActionItem/TaskPreview.js#L69

We can put this:
`const taskAssigneeAccountID = Task.getTaskAssigneeAccountID(props.taskReport) ||  props.action.actorAccountID;`

### What alternative solutions did you explore? (Optional)

Some code improvments are possible but I want to keep the proposal short and easy

**Comment by trjExpensify** [comment] 2023-07-17 13:44
@mananjadhav what do you think of this proposal?

**Comment by mananjadhav** [comment] 2023-07-17 13:47
Thanks for the bump, I missed this notification. I'll check this in a while.

**Comment by mananjadhav** [comment] 2023-07-17 17:19
I think @ShogunFire's [proposal](https://github.com/Expensify/App/issues/22373#issuecomment-1636198345) should work. 

🎀 👀 🎀 C+ reviewed.

**Comment by ShogunFire** [comment] 2023-07-17 21:38
@mananjadhav  PR ready for review

**Comment by mananjadhav** [comment] 2023-07-29 19:23
I've added a comment to the offending [PR](https://github.com/Expensify/App/pull/21781/files#r1278370818).

I don't think any further action is needed on this one. I also don't think we need a regression test for this one.

@trjExpensify This would be ready for payout on 08/01, and eligible for timeline bonus.

**Comment by trjExpensify** [comment] 2023-07-31 16:27
Yup, agreed this one is covered under the task report regression tests now added! 

Confirming payments as follows:

$1,500 - @ShogunFire for the fix & #urgency bonus (offer sent)
$1,500 - @mananjadhav for the C+ review & #urgency bonus (Manan to request)
$250 - @Natnael-Guchima for the bug report.

Sent on [this job](https://www.upwork.com/jobs/~01cae9815a84594b7f).

**Comment by Natnael-Guchima** [comment] 2023-07-31 17:00
Accepted the offer. Thanks, Tom.

**Comment by ShogunFire** [comment] 2023-08-01 00:20
Hello @trjExpensify , thanks I accepted the offer but it was 1000$ instead of 1500$

**Comment by trjExpensify** [comment] 2023-08-01 11:48
Yeah, that will usually happen. I then modify upon ending the contract to incl. the bonus :) 

Settled up with @ShogunFire and @Natnael-Guchima! Over to you Manan. I'll close this issue once actioned.

**Comment by mananjadhav** [comment] 2023-08-01 12:26
@trjExpensify I've raised a request on NewDot. I'll track the request there. You can close this one out.

**Comment by trjExpensify** [comment] 2023-08-01 14:21
I believe we leave them open until confirmation on our side is provided on the GH, then we close. :) CC: @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-08-01 18:50
Reviewed details for @mananjadhav. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by trjExpensify** [comment] 2023-08-01 21:48
Perfect, thanks. Closing!

**Closed by trjExpensify** 2023-08-01 21:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
