### ISSUE TITLE
Task – Main chat opens when edit task title second time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47775] opened 2024-08-21 08:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4877543
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task without assignee
5. Open task details and edit task title
6. Verify task details page opens
7. Click on task title again, edit it and save

## Expected Result:
Task details page opens

## Actual Result:
Main chat opens

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/532ca470-8830-4b5c-bb78-46495625f4a1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-21 08:41
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-21 08:41
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CyberAndrii** [comment] 2024-08-21 12:47
Duplicate of https://github.com/Expensify/App/issues/47671

**Comment by RachCHopkins** [comment] 2024-08-27 02:19
Looks like the other issue is well under way. Closing.

**Closed by RachCHopkins** 2024-08-27 02:19 UTC
Labels: Daily, Overdue, Bug
