### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Fab -  App disables CTRL+K / CTRL+SHIFT+K shortcuts on FAB menu option pages

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29341] opened 2023-10-11 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697011802723769

## Action Performed:
1. Open the app
2. Click on green plus and click on any FAB menu option eg: 'save the world'
3. Click 'CTRL+K' or 'CTRL+SHIFT+K' and observe that it does not work

## Expected Result:
App should not disable CTRL+K / CTRL+SHIFT+K shortcuts

## Actual Result:
App disables CTRL+K / CTRL+SHIFT+K shortcuts on FAB menu option pages

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/cc38432a-364e-4d59-ba78-94967c041053

https://github.com/Expensify/App/assets/93399543/58b9f0ae-3088-4512-a7f9-5261b179ce31

https://github.com/Expensify/App/assets/93399543/a0bb4794-b516-4b37-88c3-9c69f4aad4d7

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/fd1b54b0-40cc-4f7f-8b05-aa520477b835

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015979bf65c1172e21</li>
        <li>Upwork Job ID: 1712146924604538880</li>
        <li>Last Price Increase: 2023-10-11</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-10-11 17:48
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
App disables CTRL+K / CTRL+SHIFT+K shortcuts on FAB menu option pages

### What is the root cause of that problem?
when popovermenu open we are setting closemodal 
https://github.com/Expensify/App/blob/b820046287b7c4c162e11b1c3b6876256d49d2e2/src/components/PopoverWithoutOverlay/index.js#L48
so here when close modal is present its doesn't onModalCloseCallback trigger  
https://github.com/Expensify/App/blob/b820046287b7c4c162e11b1c3b6876256d49d2e2/src/libs/actions/Modal.ts#L17



### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/components/PopoverMenu/index.js#L81
here when once popover menu selected we should clear the modal 
`Modal.setCloseModal(null)`

**Comment by maxconnectAbhi** [comment] 2023-10-11 17:51
### Proposal
## Please re-state the problem that we are trying to solve in this issue
Fab - App disables CTRL+K / CTRL+SHIFT+K shortcuts on FAB menu

## What is the root cause of that problem?
Certainly! It seems that using the keyboard shortcuts CTRL+K or CTRL+SHIFT+K should open a search modal. However, if you've already opened a modal using the FAB menu, these shortcuts won't trigger the search modal again.

https://github.com/Expensify/App/blob/f5578523a10653b03de827e38f99f3ba54241a69/src/libs/Navigation/AppNavigator/AuthScreens.js#L185C8-L198C11

```
        this.unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
            searchShortcutConfig.shortcutKey,
            () => {
                Modal.close(() => {
                    if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
                        return;
                    }
                    return Navigation.navigate(ROUTES.SEARCH);
                });
            },
            searchShortcutConfig.descriptionKey,
            searchShortcutConfig.modifiers,
            true,
        );
```

## What changes do you think we should make in order to solve the problem?
To ensure the CTRL+K or CTRL+SHIFT+K shortcuts activate the search modal, make sure to close any currently open modals beforehand through ` Modal.setCloseModal()` function.

```
this.unsubscribeSearchShortcut = KeyboardShortcut.subscribe(
            searchShortcutConfig.shortcutKey,
            () => {
             if (!Navigation.isActiveRoute(ROUTES.SEARCH)) {
                    Modal.setCloseModal()
                  }
                Modal.close(() => {
                    if (Navigation.isActiveRoute(ROUTES.SEARCH)) {
                        return;
                    }
                    return Navigation.navigate(ROUTES.SEARCH);
                });
            },
            searchShortcutConfig.descriptionKey,
            searchShortcutConfig.modifiers,
            true,
        );
      
```

**result**

https://github.com/Expensify/App/assets/47495619/80ddad48-3610-4dc5-9e0f-0e13c1c7a39f




## What alternative solutions did you explore? (Optional)
NA

**Comment by astrohunter62** [comment] 2023-10-11 18:41
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
App disables CTRL+K / CTRL+SHIFT+K shortcuts after the modal is closed.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/64d3e39a676715b17f2e1deee2335f7e45b31c14/src/components/PopoverWithoutOverlay/index.js#L42-L46

The purpose of this code block is to prevent setting closeModal function to null when the component is invisible the first time it is rendered.
It's not correctly working because `!firstRenderRef.current`.
### What changes do you think we should make in order to solve the problem?
```js

 if (firstRenderRef.current || !props.isVisible) { 
     firstRenderRef.current = false; 
     return; 
 } 
```
### Results:

[29341.webm](https://github.com/Expensify/App/assets/136574831/72095a1f-bcf8-4605-a087-7a8301fcb118)

**Comment by s-alves10** [comment] 2023-10-12 22:48
The root cause of this issue is the wrong condition here
https://github.com/Expensify/App/blob/0c7f390b81833f51f18115763c5047bce1c92a39/src/components/PopoverWithoutOverlay/index.js#L43-L48

This looks weird. This should be updated like this
```
        if (firstRenderRef.current && !props.isVisible) {
            firstRenderRef.current = false;
            return;
        }
        firstRenderRef.current = false;
        Modal.setCloseModal(props.isVisible ? () => props.onClose(props.anchorRef) : null);
```

If agreed, I'll create a PR shortly.

**Comment by mallenexpensify** [comment] 2023-10-12 23:47
@ntdiary can you review the above proposals plz?

**Comment by astrohunter62** [comment] 2023-10-13 01:39
@ntdiary Could you review my [proposal](https://github.com/Expensify/App/issues/29341#issuecomment-1758289078)?

**Comment by s-alves10** [comment] 2023-10-13 04:14
@dukenv0307 

when the first time the component is rendered with isVisible prop as false. This condition is enough with this?
```
if (firstRenderRef.current && !props.isVisible)
```

**Comment by s-alves10** [comment] 2023-10-13 04:26
I'm not sure why you used such complex condition
```
if (prevIsVisible === props.isVisible && (!firstRenderRef.current || !props.isVisible))
```
`prevIsVisible` was removed because it has negative effect. We should remove that.

**Comment by s-alves10** [comment] 2023-10-13 06:47
@parasharrajat @dukenv0307 
What do you think about this https://github.com/Expensify/App/issues/29341#issuecomment-1760749357?
Or should we find the totally new solution?

**Comment by s-alves10** [comment] 2023-10-13 07:08
@parasharrajat 

We need to prevent setting `closeModal` function to `null` when the first time the component is rendered with `isVisible` prop as false
The code is for the condition: first render with `isVisible` props

Anyway, I agree that we should fix the root cause of the original issue

**Comment by mountiny** [comment] 2023-10-20 12:37
Coming from slack, created an issue for this one so we have it in regression suite sooner than later https://github.com/Expensify/Expensify/issues/328177

**Comment by sakluger** [comment] 2023-10-25 19:26
Thanks @mountiny!

I'm a bit unsure about payments here.

- We should definitely pay out @dhanashree-sawant for the bug report (Offer sent)
- @ntdiary it doesn't look like you reviewed any PRs, but you did review proposals and write the regression test steps. Do you think it's fair to pay you 50% of the base price for your work here, or were you thinking otherwise?

**Comment by dhanashree-sawant** [comment] 2023-10-26 04:50
Hi @sakluger, by mistake you have sent me an offer of 500$ instead of 50$, can you rectify it once you are available?

**Comment by sakluger** [comment] 2023-10-27 01:53
@dhanashree-sawant good catch! Thank you for letting me know, I've updated the offer 🙇 
@ntdiary thanks for confirming, I send you an offer.

**Comment by dhanashree-sawant** [comment] 2023-10-27 12:03
Thanks @sakluger, it shows offer is withdrawn, can you check once you are available?

**Comment by sakluger** [comment] 2023-10-27 16:10
@dhanashree-sawant in order to modify an offer that hasn't been accepted yet, I had to withdraw the offer and send a new one. Here is the [new offer link](https://www.upwork.com/nx/wm/offer/27395089), not sure if that offer works for you, but you should be able to find the new offer in your Upwork inbox. Can you let me know once you've accepted?

@ntdiary your payment is completed, thanks!

**Comment by dhanashree-sawant** [comment] 2023-10-28 13:11
Thanks @sakluger, this is what it is displaying, not sure how we can solve it.
![image](https://github.com/Expensify/App/assets/87513216/90e716e7-53cf-436e-8ab4-fb40dbab0e3d)

**Comment by sakluger** [comment] 2023-10-30 19:46
@dhanashree-sawant here's the offer link on my side: https://www.upwork.com/nx/wm/offer/27395089

Can you check your Upwork messages and see if there's a message from me on or around Thu, Oct 26 containing an offer? For you, it might be on Friday, Oct 27 because of the time zone difference.

**Comment by dhanashree-sawant** [comment] 2023-10-31 05:15
No sorry I couldn't find any offer in the messages. If you check the URL in the screenshot, It seems like upwork is displaying offer not available for the same offer link. I think offers on this job won't work and may need a new job.

**Comment by sakluger** [comment] 2023-10-31 16:25
Alright, new job post, let's try this again! https://www.upwork.com/jobs/~0133af5efe5e763c64

Please let me know if that still doesn't work for you.

**Comment by dhanashree-sawant** [comment] 2023-10-31 16:35
Thanks yes now I was able to accept the offer.

**Comment by sakluger** [comment] 2023-11-01 00:29
Great, thank you for your patience while we got that figured out 🙇 

All done now, closing!

**Closed by sakluger** 2023-11-01 00:29 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
