### ISSUE TITLE
[$500] mWeb - App gets stuck on splash screen (launch screen) when we open it from the Floating button of "Chat with concierge". 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28131] opened 2023-09-25 12:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewExpensify on the Android App
2. Click on your Profile > Help
4. Now Kill the "New Expensify" app running in background.
5. Go back to Help page in your browser. And Touch on floating button of  "Chat with concierge"(Triangle icon).

## Expected Result:
App should open without getting stuck on launch screen and chat box with Concierge should appear.

## Actual Result:
App getting stuck on launch screen and no further activity

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.7.30
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b1a6f56f-35ba-4853-8855-5595d3a2ff41

https://github.com/Expensify/App/assets/93399543/7259f5e6-2470-4460-8f7d-5f6616e27e29

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nileshahir286
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695193313415339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4f60c9d85a22f93</li>
        <li>Upwork Job ID: 1706285911617265664</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-09-25 19:33
I can't reproduce this and we didn't mark what app this is affecting in the OP - Asking the reporter. https://expensify.slack.com/archives/C049HHMV9SM/p1695670361538309?thread_ts=1695193313.415339&cid=C049HHMV9SM

**Comment by nileshahir286** [comment] 2023-09-26 05:43
> I can't reproduce this and we didn't mark what app this is affecting in the OP - Asking the reporter. https://expensify.slack.com/archives/C049HHMV9SM/p1695670361538309?thread_ts=1695193313.415339&cid=C049HHMV9SM

 issue is in Platform: Android/Native.  Please follow the reproduction steps.(Issue is Only in Android device)

**Comment by jjcoffee** [comment] 2023-09-28 13:19
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/28131#issuecomment-1734002300) LGTM! I guess introducing the `Freeze` on native is what reintroduced the issue? I wonder if it's best to add the fix for native only in that case?

We also need to make sure to thoroughly test signed in/out as mentioned [here](https://github.com/Expensify/App/issues/25839#issuecomment-1700685551).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by Christinadobrzyn** [comment] 2023-10-03 17:22
Hey @bondydaa could you take a peek at this decision here - https://github.com/Expensify/App/issues/28131#issuecomment-1739149521

Thanks!

**Comment by Christinadobrzyn** [comment] 2023-10-06 18:20
Nudging Bondy for another peek!

**Comment by bondydaa** [comment] 2023-10-09 16:01
sorry for the delay here, thanks for the explanation @bernhardoj 👍

**Comment by jjcoffee** [comment] 2023-10-10 16:00
@bernhardoj Thanks! Will review tomorrow.

**Comment by bondydaa** [comment] 2023-10-12 05:18
looks like this was a dupe of https://github.com/Expensify/App/issues/26867 and the PR https://github.com/Expensify/App/pull/29245 was merged already with the same proposal here. 

@Christinadobrzyn what do we typically do in these situations?

**Comment by Christinadobrzyn** [comment] 2023-10-18 23:09
Hum, 

- I think we can pay the reporter on this GH since https://github.com/Expensify/App/issues/26867#issue-1883916679 doesn't have a report

- @bernhardoj and @jjcoffee how much work have you done on this?

**Comment by jjcoffee** [comment] 2023-10-19 10:07
@Christinadobrzyn Full review was completed as @bernhardoj says, so it was quite a bit of work (though it wasn't an incredibly complex PR or anything!). I don't really know what normally happens in this sort of case, but maybe 50% compensation would make sense? I'd be okay with that at least, I don't know about @bernhardoj.

**Comment by Christinadobrzyn** [comment] 2023-10-24 18:22
okay how about the following payment breakdown?

Payouts due:

Issue Reporter: $50 @nileshahir286
Contributor: $250 @bernhardoj 
Contributor+: $250 @jjcoffee 

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/jobs/~01b4f60c9d85a22f93).

How does this look @bernhardoj and @jjcoffee?

**Comment by jjcoffee** [comment] 2023-10-25 08:12
@Christinadobrzyn Sounds good to me! Thanks for the consideration.

**Comment by Christinadobrzyn** [comment] 2023-10-26 16:35
Alright! Thanks! I paid this out based on this payment structure https://github.com/Expensify/App/issues/28131#issuecomment-1777790383

Closing! Thanks again for all your work on this!

**Closed by Christinadobrzyn** 2023-10-26 16:35 UTC
Labels: Reviewing, External, Daily, Bug
