### ISSUE TITLE
[$500] When editing tag field, the last one chosen does not appear on the recent list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36392] opened 2024-02-13 01:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must have created a collect workspace with tags and have invited a member as employee.

1. As the employee, go to WS chat.
2. Create a manual money request, select tag A.
3. Go to the details page of newly created expense.
4. Tap on the tag field, choose tag B.
5. Go to WS chat again and initiate a new manual money request.
6. Tap on the tag field.
7. Verify tag B is not on the recent list.

## Expected Result:
Tag B should appear on the recent list of tags.

## Actual Result:
Tab B does not appear on the recent list.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/22318b9c-d0b9-4932-857f-4fbb2a2327ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018093514c21b6b93e</li>
        <li>Upwork Job ID: 1757214198782668800</li>
        <li>Last Price Increase: 2024-02-13</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-13 01:32
We (Applause)think this bug might be related to #wave6-collect-submitters
cc @greg-schroeder

**Comment by rushatgabhane** [comment] 2024-02-15 15:17
🎀 👀 🎀 possible internal issue

**Comment by arosiclair** [comment] 2024-02-15 19:25
Looks like a dupe of https://github.com/Expensify/App/issues/35506. Closing this out

**Closed by arosiclair** 2024-02-15 19:25 UTC
Labels: External, Daily, Help Wanted, Bug
