### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Web -Workspace - Inconsistency in Workspace Notification for HTML Character-Based Workspace Names

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24427] opened 2023-08-11 14:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access the workspace settings by clicking on settings > workspace. If there is no existing workspace, create a new one.
2. Enter the HTML character code-based name "&#x0048;&#x0065;&#x006C;&#x006C;&#x006F;" for the workspace in the settings.
3. Navigate back to the workspace and click on the three dots, then enter the admin room. Observe that the workspace name is correctly displayed.
4. Return to the workspace, click the three dots in the right corner again, and delete the workspace. Go back to the admin room and observe the canceled workspace notification. Notice that "&#x0048;&#x0065;&#x006C;&#x006C;&#x006F;" is changed to "Hello".

## Expected Result:
The canceled workspace notification should display the original HTML character code-based name ""&#x0048;&#x0065;&#x006C;&#x006C;&#x006F;"". It should show the same name as observed in the admin room, maintaining consistency and avoiding confusion for users.

## Actual Result:
When a workspace name is set using HTML character codes "&#x0048;&#x0065;&#x006C;&#x006C;&#x006F;", it changes to "Hello" in the canceled workspace notification. This inconsistency in the display of the workspace name can create confusion and incongruity for users.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/aa77072d-90c8-4a22-8ecf-8a405b0733d6

https://github.com/Expensify/App/assets/115492554/bee94efd-0df5-4d85-beb1-ec7db7331d0e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @TewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691073090566039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce586e8be7aadd12</li>
        <li>Upwork Job ID: 1691967857451331584</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>TewodrosGirmaA | Reporter | 26535067</li>
</ul></li>
    </ul>
</details>

**Comment by kursat** [comment] 2023-08-11 15:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a workspace name is set using HTML character codes "Hello", it changes to "Hello" in the canceled workspace notification. This inconsistency in the display of the workspace name can create confusion and incongruity for users.

### What is the root cause of that problem?
HTML characters are not escaped in ArchivedReportFooter

### What changes do you think we should make in order to solve the problem?
We need to escape policyName in ArchivedReportFooter.js:

```js
policyName: `<strong>${_.escape(ReportUtils.getPolicyName(props.report))}</strong>`,
```
![resim](https://github.com/Expensify/App/assets/1279379/0f1b6e4b-f046-455f-a1dc-7b9a71799c0f)



### What alternative solutions did you explore? (Optional)

**Comment by alexpensify** [comment] 2023-08-12 15:58
I ran out of time to test this one yesterday but will review it on Monday.

**Comment by alexpensify** [comment] 2023-08-14 21:29
Tomorrow, I will test more.

**Comment by alexpensify** [comment] 2023-08-17 00:19
@situchan - when you get a chance, can you review the proposals and identify if one will help address this error? Thanks!

**Comment by alexpensify** [comment] 2023-08-18 21:40
No update yet, these proposals need to go through a review.

**Comment by alexpensify** [comment] 2023-08-21 17:57
@situchan - can we get an update here regarding the proposal and if one will work for this GH? Thanks!

**Comment by alexpensify** [comment] 2023-08-24 03:47
@situchan any update here?

**Comment by situchan** [comment] 2023-08-24 16:01
Testing proposals with various cases. Will update soon

**Comment by alexpensify** [comment] 2023-08-28 23:06
@situchan - any update here based on your tests? Thanks!

**Comment by alexpensify** [comment] 2023-08-30 22:21
@situchan - can we get an update here?

**Comment by alexpensify** [comment] 2023-09-01 22:56
@situchan any luck with the tests? I'd like to get this assigned by Tuesday. Thanks!

**Comment by alexpensify** [comment] 2023-09-04 15:26
@situchan - can you please update your test feedback here, so that we an follow along? Thanks!

**Comment by alexpensify** [comment] 2023-09-06 21:31
This has gone past a few business days with no movement, I've reached out in the C+ Slack room. @allroundexperts is ready to step in and help review the proposals.

**Comment by situchan** [comment] 2023-09-06 23:23
The solution to fix archived footer case is straightforward and simple.
But I think we should fix system message as well. No reason for keeping this bug remaining and that's why I didn't approve any proposals yet.

<img width="794" alt="system message" src="https://github.com/Expensify/App/assets/108292595/d231d13d-ecb7-4b42-9c8c-ff29d5803e04">

**Comment by situchan** [comment] 2023-09-06 23:32
Maybe need to check LHN last message as well.

Btw, it's not that simple fix (without any regression) which can be tackled enough in PR review.

**Comment by marcaaron** [comment] 2023-09-07 05:14
>For this particular case, I would suggest to split the compensation between @tienifr / @kursat.

Is that something that @kursat agrees to? 

I will assign @kursat here because the solution looks correct to me and agree that they are the correct person to assign.

**Comment by tewodrosGirmaA** [comment] 2023-09-07 05:48
Hello @alexpensify , I received an offer of $50 from the service, but the issue was created before August 30th, and therefore, I should have received an offer of $250. Could you please assist me with this matter? Thank you

**Comment by kursat** [comment] 2023-09-07 13:29
> Is that something that @kursat agrees to?

> Hope @kursat is happy with this as well 🤝.

Hey guys, I agree and I am happy with it 👍 It has been a while last time I contributed, Idk how splitting compensation works. If you can guide me that would be great.

I will apply to the job in a moment. I just need to check the concerns of @situchan and @bernhardoj 

> The solution to fix archived footer case is straightforward and simple. But I think we should fix system message as well. No reason for keeping this bug remaining and that's why I didn't approve any proposals yet.
> <img alt="system message" width="794" src="https://user-images.githubusercontent.com/108292595/266162438-d231d13d-ecb7-4b42-9c8c-ff29d5803e04.png">


> @allroundexperts just fyi, if we always escaping the text, we will see the escaped text when it is not rendered inside HTML.
> 
> Example: Policy name = `&amp;` Render with RenderHTML = user will see `&amp;` No HTML = user will see `&amp;amp;`

**Comment by kursat** [comment] 2023-09-07 15:31
Hey guys, I am not sure I understand the problem here:

> The solution to fix archived footer case is straightforward and simple. But I think we should fix system message as well. No reason for keeping this bug remaining and that's why I didn't approve any proposals yet.
> <img alt="system message" width="794" src="https://user-images.githubusercontent.com/108292595/266162438-d231d13d-ecb7-4b42-9c8c-ff29d5803e04.png">

On this screenshot I've set workspace name exactly as `Foo &#xA9; bar &#x1D306; baz &#x2603; qux` and its not seen as `Foo © bar 𝌆 baz ☃ qux` anywhere (Also checked LHN). Isn't it supposed to be like this?

On the other hand, it looks like something has changed (prob on BE) since I've sent this proposal and system messages are now decoded.  For workspace name `&amp;&#72;&#101;&#108;&#108;&#111;` which is encoded version of `&Hello` (in decimal encoding) we get this:

![Screenshot 2023-09-07 at 18 18 46](https://github.com/Expensify/App/assets/1279379/3ddebb00-dd95-4f07-88c0-79ddc9ac955c)

**Comment by situchan** [comment] 2023-09-07 15:42
Whatever reason, after the fix, both names should be consistent in displaying same as what user typed in workspace name input field before save.

**Comment by kursat** [comment] 2023-09-07 15:46
@allroundexperts it happens for only system messages. Also please check the update on my last comment.

**Comment by kursat** [comment] 2023-09-07 16:30
Hey @situchan, @allroundexperts,

I've investigated further this issue and here are my findings:

For policy names that doesn't ~~start with~~ include reserved html char (both old and new),  BE sends only `text` field.

```
updated the name of this workspace from "Test2" to "Foo &#xA9; bar &#x1D306; baz &#x2603; qux"
```

But if at least one of them ~~starts with~~ includes reserved char, BE sends both `text` and `html` fields:

```
text: updated the name of this workspace from "Foo &#xA9; bar &#x1D306; baz &#x2603; qux" to "&Foo &#xA9; bar &#x1D306; baz &#x2603; qux"
html: updated the name of this workspace from "Foo &#xA9; bar &#x1D306; baz &#x2603; qux" to "&amp;Foo &#xA9; bar &#x1D306; baz &#x2603; qux"
```

** See in the text version `&amp;` is rendered as `&` into messsage string. And this breaks below logic.

https://github.com/Expensify/App/blob/10ad0cb0634297741e8736ee80ae06ed0adbe053/src/pages/home/report/ReportActionItemFragment.js#L120-L132

Imho, this is seperate, BE bug. If you agree, I would like to report this as a new bug and continue with my PR.

**Comment by marcaaron** [comment] 2023-09-07 22:31
That is pretty low priority for us to fix that in the backend so it's unlikely we would prioritize it anytime soon. Doesn't really seem like the same bug to me so I'd go ahead and report it, but call out that it needs to be fixed in the backend so we can appropriately tag it as `Internal`

**Comment by alexpensify** [comment] 2023-09-19 22:58
The payment date is set for tomorrow. @allroundexperts can you please complete the checklist? Thanks!

**Comment by alexpensify** [comment] 2023-09-19 23:06
Here is the payment summary: 

-  External issue reporter @tewodrosGirmaA $250 
-  Contributor that fixed the issue @kursat $1500 
-  Contributor+ that helped on the issue and/or PR @allroundexperts $1500 

Upwork Job: 


*If applicable, the bonuses will be applied on the final payment: Urgency bonus will be added here 

Extra Notes regarding payment:

**Comment by alexpensify** [comment] 2023-09-19 23:08
@kursat can you please apply for the job in Upwork to ensure that the payment is ready to go tomorrow? Thanks!

**Comment by tewodrosGirmaA** [comment] 2023-09-20 02:37
Hello @alexpensify  you  sent  me 50 dollar offers

**Comment by alexpensify** [comment] 2023-09-20 04:06
@tewodrosGirmaA - I've not completed the process since the payment date is tomorrow. Sorry for the confusion, but it looks like the automation got the amount wrong. I've already flagged that I will add the remaining amount as a bonus. 

https://github.com/Expensify/App/issues/24427#issuecomment-1726662077

**Comment by tewodrosGirmaA** [comment] 2023-09-20 04:13
@alexpensify I have not yet accepted the offer and I was wondering if it would be possible to accept the offer along with an additional bonus, or if an alternate offer could be presented. I would appreciate your thoughts on this matter.

**Comment by alexpensify** [comment] 2023-09-20 04:15
@tienifr thanks for flagging, I've updated the compensation amounts here: 

https://github.com/Expensify/App/issues/24427#issuecomment-1726662077

Please apply for the job here: 

 https://www.upwork.com/jobs/~01ce586e8be7aadd12

**Comment by alexpensify** [comment] 2023-09-20 04:17
@tewodrosGirmaA - please accept as is, I think I can apply the bonus amount when I close the job. If I can't, then I've already noted there is a remaining $200, I can create a new job to cover the missing amount. I will take care of this tomorrow.

**Comment by tewodrosGirmaA** [comment] 2023-09-20 04:21
I accept it, Thank you

**Comment by kursat** [comment] 2023-09-20 11:47
@alexpensify I've already applied, thanks

**Comment by alexpensify** [comment] 2023-09-20 23:08
Alright, @tewodrosGirmaA as promised you were paid $250 -- Done! 

@tienifr and @kursat - please accept and we should be all set 

@allroundexperts -- please complete the checklist and we can close this GH. Thanks!

**Comment by tewodrosGirmaA** [comment] 2023-09-21 02:42
@alexpensify Thank you so  much

**Comment by alexpensify** [comment] 2023-09-22 07:16
Alright, @tienifr and @kursat - you have been paid via Upwork. 

@allroundexperts please submit a request in Chat and complete the Checklist. After, we can close this GH. Thanks!

**Comment by marcaaron** [comment] 2023-09-25 05:08
I think we are just waiting for payment here.

**Comment by alexpensify** [comment] 2023-09-25 06:05
@marcaaron no, this is open because the checklist is not completed yet. 

@allroundexperts -- please complete the checklist and we can close this GH. Thanks!

**Comment by alexpensify** [comment] 2023-09-27 08:05
@allroundexperts bumping again, we need to complete the checklist before I can close -- thanks!

**Comment by alexpensify** [comment] 2023-09-29 01:37
Thank you @allroundexperts!

**Comment by alexpensify** [comment] 2023-10-02 16:18
@allroundexperts - thanks for completing this task. @marcaaron - can you review the regression test and confirm if you agree? Thanks!

**Comment by marcaaron** [comment] 2023-10-03 00:29
LGTM

**Comment by alexpensify** [comment] 2023-10-04 16:37
Closing - the regression test has been created for this case.

**Closed by alexpensify** 2023-10-04 16:37 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by marcaaron** [comment] 2023-10-04 22:38
Thanks @alexpensify 🙇
