### ISSUE TITLE
[Fabric] IOS - New Chat/New Group - The avatar jumps and flashes when opening a chat with a new user.

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#14365] opened 2023-01-17 18:48 UTC
## Action Performed:
1. Log in to NewDot with any type of account
2. Click on the green + button
3. Click on the "New Chat" option
4. Search for a user that you don't have any messages with and open the chat.

## Expected Result:
Transaction should be smooth when opening a new group

## Actual Result:
The avatar jumps and flashes when opening a chat with a new user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] IOS / native

**Version Number:** 1.2.49.0 

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/211158552-fd5e4896-fe9a-4102-9f8d-46e71a5f2076.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-01-17 18:48
Coming from [here](https://github.com/Expensify/App/pull/13767)

**Comment by trjExpensify** [comment] 2023-01-18 00:16
I wonder how much this is down to caching avatars, @roryabraham? 🤔

**Comment by roryabraham** [comment] 2023-01-18 00:29
First things first, I clarified that this issue is only happening on the Fabric branch by adding the `[Fabric]` prefix to the issue title. That seems worth doing for all the Fabric-only issues.

> I wonder how much this is down to caching avatars, @roryabraham? 🤔

Doesn't look related to avatar caching to me. If I had to guess, I would guess that this is happening when the `CREATED` action is updated to be "finalized":

1. Report opens with optimistic `CREATED` action (w/ `pendingAction: 'add')
1. `OpenReport` API command sent.
1. The API command completes, and the `pendingAction` field of the `CREATED` action is set to `null`. This causes `ReportActionItem` to re-render, which is causing a flash for some unknown reason.

**Comment by roryabraham** [comment] 2023-01-18 00:30
Looks like @WoLewicki may be on the case of this bug already: https://expensify.slack.com/archives/C04878MDF34/p1673978560875489

**Comment by trjExpensify** [comment] 2023-01-18 00:41
>First things first, I clarified that this issue is only happening on the Fabric branch by adding the [Fabric] prefix to the issue title. That seems worth doing for all the Fabric-only issues.

Yes, great idea! Let's communicate that somewhere more widely. We could even be more explicit with `[Fabric-only]` as it might get mixed up with simply noting it's part of the project. 

>Doesn't look related to avatar caching to me

Okay, great. Sounds good!

**Comment by WoLewicki** [comment] 2023-01-18 11:31
I am working on this issue now.

**Comment by JmillsExpensify** [comment] 2023-01-18 16:56
Nice! Assigned @WoLewicki as well.

**Comment by JmillsExpensify** [comment] 2023-01-21 05:58
Moved to weekly since that's the speed this project is moving at.

**Comment by j-piasecki** [comment] 2023-01-25 15:53
This issue was caused by the `reportActionID` of action with type `CREATED` being different each time the chat was opened, causing rerender of that component. This has been fixed on the `main` branch and merged into the one with fabric integration.

**Comment by JmillsExpensify** [comment] 2023-01-31 05:06
@roryabraham @trjExpensify It'd be good to align on what our ideal process here from here on out for Fabric improvement issues like this one, where the fix is already on the main branch?

**Comment by trjExpensify** [comment] 2023-02-01 20:37
Oh, so what happened? There was actually a bug on main that was causing this?

**Comment by roryabraham** [comment] 2023-02-01 23:37
Not exactly. What was happening was:

- Optimistic `CREATED` action was shown
- PHP hack inserted `CREATED` action with a random ID
- Created action is received by front-end with new ID
- New reportActionID causes component to re-render (because reportActionID is the key of the item in FlatList)
- UI flashes on Fabric (unclear why)

The migration that added `CREATED` actions to the DB fixed this problem because:

- Optimistic `CREATED` action is shown with client-generated canonical reportActionID
- Since the `reportActionID` remains the same, there is no re-render caused, and therefore no flash

**Comment by roryabraham** [comment] 2023-02-01 23:38
I think we can close this now.

**Closed by roryabraham** 2023-02-01 23:38 UTC
Labels: Engineering, Weekly, NewFeature

**Comment by JmillsExpensify** [comment] 2023-02-02 04:22
Say what? Not sure what that's referring to.
