### ISSUE TITLE
[$500] Assign task - Invalid red dot appears by closing assign the tab when there's no prior action

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31583] opened 2023-11-20 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30679
## Action Performed:
1. Navigate to staging.new.expensify.com and log in to an Expensifail account
2. Click the green plus button
3. Select "Assign task"
4.Click outside the panel or the back button and hold, to close it
5. Repeat steps 2-4

## Expected Result:
No red dot should be seen when closing the Assign task tab

## Actual Result:
An invalid red dot appears briefly when closing the 'Assign task' tab when there is no prior action

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/4b676d93-93db-4294-be1e-e051cef5cd8b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01690c0dbaf0deaaf7</li>
        <li>Upwork Job ID: 1726711332049424384</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by cooldev900** [comment] 2023-11-20 21:24
I am not able to reproduce it.

**Comment by erquhart** [comment] 2023-11-20 21:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When clicking and holding back button or any spot outside of the RHN while assign task view is open, the Title field displays validation error for as long as press/click is held.

### What is the root cause of that problem?

Our form validation intentionally shows a validation error for required fields if they are focused and then blurred. We are autofocusing the field on form open, and by pressing a focusable element, such as outside of the RHN or the back button, we're blurring the input and triggering validation. Note that this is not really a bug, but a side effect of how the validation works.

### What changes do you think we should make in order to solve the problem?

The only reason this seems jarring is because the user hasn't interacted with the form yet, and they didn't manually focus the field, so an error message isn't expected. I wouldn't recommend special handling of this particular case, but that we stick to a design pattern.

We should decide either:

1. We want to continue validating required fields immediately on blur, and leave this as is, or
2. We don't like the side effects of showing error messaging prematurely in some cases, so we'll show missing required fields validation only after the first form submission. This would only impact required field errors, all other error types would continue to show once the field is dirty as we currently do.

Going with the approach in #2 means it is no longer jarring to the user that a validation error is shown, because they would have already seen this error on submission and it makes sense. But it also means we're not giving immediate feedback as they focus in and out of required fields before the first submission. We already show (optional) for optional fields, implying that others are required, so I think this is an acceptable approach.

### What alternative solutions did you explore?

If we really don't like the specific behavior outlined in this issue, but don't want to change our error validation pattern, we could:

1. Not autofocus this field on RHN open - this is probably very undesirable, not recommended, but we could do it.
2. Some kind of hack where we specifically recognize that the user is clicking away from the form. This will involve focus management trickery and pain, highly recommend against this kind of solution for fringe behavior like this.

**Comment by AmjedNazzal** [comment] 2023-11-21 10:29
I'm not sure but perhaps someone can confirm this, but I think maybe this should wait until the From Provider Refractor is finalized since it will include the behaviour of `NewTaskDetailsPage` as mentioned in the [comment](https://github.com/Expensify/App/issues/25397#issuecomment-1743272245)

**Comment by erquhart** [comment] 2023-11-21 13:54
The one thing that does feel off is that the invalid state is clearly visible while the RHN is closing on web/desktop, without holding the click.


https://github.com/Expensify/App/assets/2112202/a4c25008-7975-42ff-9fb5-df8e83df6d5c

**Comment by garrettmknight** [comment] 2023-11-21 19:47
@parasharrajat agreed, this isn't worth fixing right now.

**Closed by garrettmknight** 2023-11-21 19:47 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by erquhart** [comment] 2023-11-21 20:37
cool cool good talk
