### ISSUE TITLE
[Awaiting Payment May 15th] [QBO] advanced configuration: selected accounts are not selected after Relogin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41095] opened 2024-04-26 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.66-2 
**Reproducible in staging?:** Y
**Reproducible in production?:** No, new feature
**Found when validating PR :** https://github.com/Expensify/App/pull/40718
**Email or phone of affected tester (no customers):** applausetester+yuriy.qbo.check1@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log into New Expensify with an account that is on the accounting beta
2. Enable Accounting feature on the More Features page
3. Go to the Accounting screen and connect to QBO
4. After the connection is established, click Advanced
5. Enable "Sync reimbursed reports"
6. Click Quickbooks Online account
7. Check that you see the list of accounts from QBO whose types are either "Bank" or "Credit card"
8. Select one of the account from the list
9.Go back and click "Invoice collection account"
10. Check that you see the list of accounts from QBO whose types are either "Bank" or "Other Current Assets"
11. Select one of the accounts from the list
12. Log out from New Expensify
13. Log into New Expensify again and double confirm that the selected accounts in the previous steps are still selected on the Advanced configuration screen

## Expected Result:
QuickBooks bill payment account and QuickBooks invoice collections account are still selected after relogin (QBO advanced configuatrion)

## Actual Result:
QuickBooks bill payment account and QuickBooks invoice collections account selector are empty after relogin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e0d1d77e-36e3-4d3f-9e23-533d9e4bf919

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-04-26 13:06
This si behind beta so not a blocker

cc @hayata-suenaga @aldo-expensify @trjExpensify @teneeto @narefyev91

**Comment by trjExpensify** [comment] 2024-04-26 15:52
I'll wait for @aldo-expensify to come online later, but I _think_ this is going to be fixed by his PRs for `Import` and `Sync` etc.

**Comment by hayata-suenaga** [comment] 2024-04-29 21:34
> I'll wait for @aldo-expensify to come online later, but I think this is going to be fixed by his PRs for Import and Sync etc.

Hmmm, this does't seem to be related to `Sync` or `Import` stuff. This is just configuration values (i.e. account IDs) not being saved. What do you think, @aldo-expensify? 😄

**Comment by aldo-expensify** [comment] 2024-04-29 22:39
This may have been because of the server errors not handling some "settingNames". Is this still reproducible?

**Comment by hayata-suenaga** [comment] 2024-04-30 17:06
ah that makes sense. Let me know @trjExpensify if you encounter this issue again during your testing 🙇

**Comment by trjExpensify** [comment] 2024-05-01 21:56
I'm trying to retest this and now I can't toggle sync reimbursed reports on at all to see these accounts now: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/a86da1ea-96a6-4ef0-9eda-e1707ca08f9f">

Uncaught TypeError for `TaskQueue`. Cannot read properties of undefined (reading 'id')

**Comment by aldo-expensify** [comment] 2024-05-01 22:00
> Uncaught TypeError for TaskQueue. Cannot read properties of undefined (reading 'id')

hmm I don't see that error and it works for me:


https://github.com/Expensify/App/assets/87341702/d032337f-00f4-4c87-b810-94bc7dc6c9d7

Does this happen if you try in a fresh new workspace?

**Comment by trjExpensify** [comment] 2024-05-01 22:10
This was a fresh workspace I created.

**Comment by aldo-expensify** [comment] 2024-05-01 22:15
> This was a fresh workspace I created. I'll move to a new account and start over. 

You are testing in staging, right?

**Comment by trjExpensify** [comment] 2024-05-01 22:25
Yep! Same result with a fresh workspace and account when clicking `Sync reimbursed reports` toggle: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/64b8eb9c-c9cb-4bb4-a949-d5fdfcc16bd5">
 
Also, our friend `country` came to the party when I clicked the `Import` page

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/fd49b839-4a80-481e-bcdf-1a095005c32c">

**Comment by aldo-expensify** [comment] 2024-05-02 18:09
> Also, our friend country came to the party when I clicked the Import page

Again! I'll check that

**Comment by ikevin127** [comment] 2024-05-09 02:52
⚠️ Automation failed -> this should be on **[HOLD for Payment [2024-05-15]]** according to today's production deploy from [#41530 (comment)](https://github.com/Expensify/App/pull/41530#issuecomment-2101804505).

cc @trjExpensify (not sure if you'll handle payment here)

**Comment by trjExpensify** [comment] 2024-05-09 10:14
I can do! Assigned you, and updated the title!

**Comment by ikevin127** [comment] 2024-05-15 17:15
@trjExpensify Is anything else needed from my side in order for the payment to be issued today ?

**Comment by trjExpensify** [comment] 2024-05-15 20:22
Payment summary as follows: 

$250 to @ikevin127  for the C+ review

**Comment by trjExpensify** [comment] 2024-05-15 20:22
Paid!

**Closed by trjExpensify** 2024-05-15 20:22 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
