### ISSUE TITLE
[HOLD 34424] Chat - Not here page shows up when thread loads after joining and leaving thread offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34649] opened 2024-01-17 15:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34376
## Action Performed: 
1. Go offline
2. Send a message
3. Right click on message > Unsubscribe from thread
4. Right click on message > Reply in thread.
5. Click Join
6. Click 3-dot menu > Leave
7. Right click on message > Reply in thread
8. Click on the header subtitle to return to main chat
9. Right click on message > Reply in thread
10. Go online.

## Expected Result:
Thread view loads successfully.

## Actual Result:
Not here page shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/76c95cbd-468e-4c5c-b05b-9a7528298aa0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-01-18 01:43
@paultsimura @srikarparsi Could you check this one out, seems like a regression from the PR you have worked on possibly, but it and edgecase that i dont think this has to be a blocker

**Comment by srikarparsi** [comment] 2024-01-18 06:43
Yeah agree,  it does seem like a regression from https://github.com/Expensify/App/pull/34376, I can take this one @AndrewGable

**Comment by paultsimura** [comment] 2024-01-18 09:17
Hey @srikarparsi @mountiny, fortunately (for me 🙂) it's not a regression from our PR. We just enabled the "Leave" button on empty threads and made this bug a 
I reverted the PR, and was able to reproduce the same bug with one extra step: need to add a reply in the thread before leaving it (it changes nothing, just shows the "leave" button because the thread becomes non-empty):


https://github.com/Expensify/App/assets/12595293/be8bd88f-50c9-4725-8c19-ff5bdf036173

**Comment by mountiny** [comment] 2024-01-18 14:41
Thanks! I agree its not direct regression but should be looked at

**Comment by paultsimura** [comment] 2024-01-18 16:37
In the referenced issue – https://github.com/Expensify/App/issues/34424 – the Contributors have posted proposals that will fix this issue as well. The root cause here is that we remove the thread from Onyx once leaving it. And when we come back online, we remove it with this `successData`:
https://github.com/Expensify/App/blob/b1e2aeb976d32625c3afde22117ff678440dffe9/src/libs/actions/Report.ts#L2118-L2129

Can we just ask for this failure to be tested in that issue as well?

**Comment by srikarparsi** [comment] 2024-01-24 07:11
Agree, putting it on hold for https://github.com/Expensify/App/issues/34424

**Comment by srikarparsi** [comment] 2024-01-29 19:44
on hold

**Comment by srikarparsi** [comment] 2024-02-06 06:23
on hold

**Comment by srikarparsi** [comment] 2024-02-09 03:08
on hold, moving to weekly

**Comment by srikarparsi** [comment] 2024-02-20 10:45
still on hold

**Comment by srikarparsi** [comment] 2024-02-29 03:33
Holding for this [now](https://github.com/Expensify/App/pull/35869#issuecomment-1970001389).

**Comment by srikarparsi** [comment] 2024-03-11 08:39
This issue is no longer reproducible, closing it out.

<img width="1136" alt="image" src="https://github.com/Expensify/App/assets/48188732/55f4a6e0-6292-44a6-8c76-9e0e64bb5c1b">

**Closed by srikarparsi** 2024-03-11 08:39 UTC
Labels: Engineering, Weekly
