### ISSUE TITLE
iPhone 13 - Can't send message and app gets stuck

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21733] opened 2023-06-27 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  tap +
2.  new chat
3.  pick a contact
4.  type an emoji
5.  try to send the message
6.  app breaks

## Expected Result: 
send the emoji
## Actual Result: 
App freeze

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native - iPhone 13
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduciotn
**Reproducible in production?:**needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b1b38a19-1355-4ab3-9e54-cb88bbc846d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dan1d
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687646457363949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lschurr** [comment] 2023-06-27 21:50
Not able to reproduce on iPhone 13 Pro. Bumped the Slack thread.

**Comment by lschurr** [comment] 2023-06-28 18:02
Still can't reproduce and there's another similar GH here: https://github.com/Expensify/App/issues/21540

Going to close this one.

**Closed by lschurr** 2023-06-28 18:02 UTC
Labels: Daily, Needs Reproduction, Bug
