### ISSUE TITLE
[$500] [SCAN] Dot indicator doesn't display in IOU chat (in LHN) when scanning receipt failure

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27699] opened 2023-09-18 17:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Request Money > Scan
3. Upload an file (not a receipt)
4. Wait until scanning ends
## Expected Result: 
Dot indicator should display in IOU chat (in LHN) when scanning receipt failure
## Actual Result: 
Dot indicator doesn't display in IOU chat (in LHN) when scanning receipt failure

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0af9e646-e84a-459e-a8d1-abffb4b5fa8d

![Snip - (1) New Expensify - Google Chrome (3)](https://github.com/Expensify/App/assets/43996225/eb8296fd-7595-4742-8770-0186d4e956ac)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694593816318179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01961d1d18426714ce</li>
        <li>Upwork Job ID: 1703817596511924224</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-18 17:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dot indicator doesn't display in IOU chat (in LHN) when scanning receipt failure

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/6be8fcac69aa11ff84baaae94d3ef1d495fe5123/src/libs/OptionsListUtils.js#L358-L365

Currently, we only apply error to reportAction that has IOU type (isReportPreviewAction is true). We don't do that to reportAction that has REPORTPREVIEW type (isReportPreviewAction is true)
### What changes do you think we should make in order to solve the problem?
In getAllReportErrors function, add condition to check if isReportPreviewAction is true, we also apply error 
```
else if (ReportActionUtils.isMoneyRequestAction(action)) {
       if (ReportUtils.hasMissingSmartscanFields(report.reportID)) {
               _.extend(reportActionErrors, {smartscan: ErrorUtils.getMicroSecondOnyxError('report.genericSmartscanFailureMessage')});
            }
  }

```

**Comment by MariaHCD** [comment] 2023-09-19 03:59
We've got a fix for this currently in review: https://github.com/Expensify/App/pull/27494

And this was already part of a polish issues being tracked here: https://github.com/Expensify/App/issues/26832

**Closed by MariaHCD** 2023-09-19 03:59 UTC
Labels: External, Daily, Help Wanted, Bug
