### ISSUE TITLE
mWeb/Chrome - Split - Next button is missing when you split bill with participants

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13011] opened 2022-11-24 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with HT account
3. Tap on Fub menu
4. Select Split bill
5. Select Participants

## Expected Result:
Next button should be visible

## Actual Result:
Next button is missing when you split bill with participants

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web/Chrome

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203840755-47e5ece3-630c-4149-8862-0e3357aed60d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-24 18:10
I can repro this in any account on mWeb Chrome and Safari. Looking at potential causes

**Comment by luacmartins** [comment] 2022-11-24 18:13
Actually, this is also reproducible on production so not a blocker. I'll take a look at a fix though

https://user-images.githubusercontent.com/22219519/203846351-09f1f41d-c9e8-43fb-90e1-87ef3a91c834.mov

https://user-images.githubusercontent.com/22219519/203846338-85c65234-813e-430b-8079-4230c89747f3.mov

**Comment by Puneet-here** [comment] 2022-11-24 18:28
I think It's regression from https://github.com/Expensify/App/pull/12366

**Comment by Puneet-here** [comment] 2022-11-24 18:51
@luacmartins, I think we should revert https://github.com/Expensify/App/pull/12366 because this issue will affect user experience (the whole screen is scrolling and this issue is present for all search pages at small screen)

**Comment by Puneet-here** [comment] 2022-11-24 18:59
Confirmed it by reverting the PR

https://user-images.githubusercontent.com/101883770/203850917-4faffc45-bd02-4f29-8489-a6f5f4e5f35d.mov

**Comment by luacmartins** [comment] 2022-11-25 16:03
Revert was deployed. Closing issue.

**Closed by luacmartins** 2022-11-25 16:03 UTC
Labels: Engineering, Daily
