### ISSUE TITLE
[$500]  Deeplinks – App crashes when navigate via Deeplink and log in with a new account.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29775] opened 2023-10-17 14:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of New Expensify
2. Navigate to this link - https://staging.new.expensify.com/r/3504895439653267
3. Click sign in in announce room

## Expected Result:
The announce room opens

## Actual Result:
App crashes when navigate via Deeplink https://staging.new.expensify.com/r/3504895439653267
and log in with a new account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/158a8422-09d2-493d-a76d-05756b492b78

[logs2.txt](https://github.com/Expensify/App/files/12929802/logs2.txt)

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c22034bcedf8303e</li>
        <li>Upwork Job ID: 1714282262768844800</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-10-17 14:24
I am not able to reproduce the issue

**Comment by sammanadh** [comment] 2023-10-17 14:51
unable to reproduce this error locally

**Comment by sammanadh** [comment] 2023-10-17 14:55
Contributor details
Your Expensify account email: sharedwithboys@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018287b8ccf4f064ac

**Comment by JmillsExpensify** [comment] 2023-10-17 21:10
@lanitochka17 Is QA able to reproduce this issue? Looks like we have two confirmed contributors that aren't seeing the same.

**Comment by JmillsExpensify** [comment] 2023-10-24 22:53
No one seems able to reproduce. Closing.

**Comment by JmillsExpensify** [comment] 2023-11-08 12:41
Still waiting for proposals

**Comment by rushatgabhane** [comment] 2023-11-13 07:01
@JmillsExpensify maybe we should consider doubling? App crash for new acc is a critical bug, what do you think?

**Comment by mvtglobally** [comment] 2023-11-18 04:30
Issue not reproducible during KI retests. (First week)

**Comment by JmillsExpensify** [comment] 2023-11-24 18:09
Going to go ahead and close again since the issue is no longer reproducible for a second time.

**Closed by JmillsExpensify** 2023-11-24 18:09 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
