### ISSUE TITLE
[HOLD for payment 2022-11-29] [$1000] BUG:  The text inside the composer input and the menu on the settings page got highlighted when triple-click on the last report chat reported by @mollfpr

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12028] opened 2022-10-20 01:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to the composer input and type something
2. Triple-click to highlight the text of the last report chat
3. Click the account avatar to open the settings modal in the rightDocked side modal

## Expected Result:
Only the intended text selection is highlighted.

## Actual Result:
The intended text select, text inside the composer input, and the menu on the settings page are highlighted.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196834834-73f86df0-db5a-4c75-a57f-ae420bfcd880.mp4

https://user-images.githubusercontent.com/43996225/196834880-bf4a8f77-4043-4eea-9907-1555d75afe27.mov

**Upwork URL:** https://www.upwork.com/jobs/~019c6881ba683194f2
**Issue reported by:** @mollfpr 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666188981167469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-10-20 19:54
Job on Upwork here: https://www.upwork.com/jobs/~019c6881ba683194f2

**Comment by hungvu193** [comment] 2022-10-22 12:10
<b>Proposal</b>
Disable the text selection highlighting can help us fix this problem.

<b>Solution</b>
Apply this style to the ScreenWrapper of InitialSettingPage:

```diff
- <ScreenWrapper >
+  <ScreenWrapper style={[styles.settingsPageWrapper]}>
                <HeaderWithCloseButton
                    title={this.props.translate('common.settings')}
                    onCloseButtonPress={() => Navigation.dismissModal(true)}
                />
```

```javascript
+settingsPageWrapper: {
+      MozUserSelect: "none",
+      WebkitUserSelect: "none",
+      UserSelect: "none",
}
```


https://user-images.githubusercontent.com/16502320/197338308-ce43ee26-2e06-4f19-a751-e5f53996a138.mov

**Comment by thesahindia** [comment] 2022-10-24 15:49
@hungvu193, the text inside the composer still gets selected. I think your solution is a workaround. We need to find the root cause.

**Comment by wildan-m** [comment] 2022-10-26 03:52
### Proposal

### Root cause

I think it's related to how chrome behaves with a triple click. They have a related bug with status won't fix
https://bugs.chromium.org/p/chromium/issues/detail?id=575136

### Workaround
My proposed solution is also a workaround, but let me know if it's acceptable.

The idea is to override the selection with the desired contents.

We can wrap `ReportActionItemFragment` with a div and listen triple-click events to programmatically re-select the text contents.

```diff
git diff src/pages/home/report/ReportActionItemMessage.js
diff --git a/src/pages/home/report/ReportActionItemMessage.js b/src/pages/home/report/ReportActionItemMessage.js
index d226ac9ced..af88ac4e5e 100644
--- a/src/pages/home/report/ReportActionItemMessage.js
+++ b/src/pages/home/report/ReportActionItemMessage.js
@@ -26,18 +26,33 @@ const defaultProps = {
     style: [],
 };
 
+const selectElementContents = (el) => {
+    const sel = window.getSelection();
+    sel.removeAllRanges();
+    const range = document.createRange();
+    range.selectNodeContents(el);
+    sel.addRange(range);
+};
+
+const onClick = (e) => {
+    if (e.detail !== 3) { return; }
+    selectElementContents(e.target);
+};
+
 const ReportActionItemMessage = props => (
     <View style={[styles.chatItemMessage, ...props.style]}>
         {_.map(_.compact(props.action.previousMessage || props.action.message), (fragment, index) => (
-            <ReportActionItemFragment
-                key={`actionFragment-${props.action.sequenceNumber}-${index}`}
-                fragment={fragment}
-                isAttachment={props.action.isAttachment}
-                attachmentInfo={props.action.attachmentInfo}
-                source={lodashGet(props.action, 'originalMessage.source')}
-                loading={props.action.isLoading}
-                style={props.style}
-            />
+            <div role="presentation" onClick={onClick}>
+                <ReportActionItemFragment
+                    key={`actionFragment-${props.action.sequenceNumber}-${index}`}
+                    fragment={fragment}
+                    isAttachment={props.action.isAttachment}
+                    attachmentInfo={props.action.attachmentInfo}
+                    source={lodashGet(props.action, 'originalMessage.source')}
+                    loading={props.action.isLoading}
+                    style={props.style}
+                />
+            </div>
         ))}
     </View>
 );
```


I know this solution will still have the wrong selection at first, but it will immediately correct the text selection. Please have a look at the video.


https://user-images.githubusercontent.com/11847279/197930547-a9dd6a91-dcdf-4c3e-a32c-53ad4ec999f8.mp4

**Comment by thesahindia** [comment] 2022-10-26 20:06
> I think it's related to how chrome behaves with a triple click. They have a related bug with status won't fix

@wildan-m, the issue can be seen on other browsers as well. 

Waiting for more proposals.

**Comment by wildan-m** [comment] 2022-10-27 02:09
### Proposal (Updated)

@thesahindia, you are right, I can also reproduce it in Safari.

I still believe that it's caused by the different triple-click behavior of browsers
At this time, behavior of default action of triple-click isn't specified the W3C spec
Other repos also experience similar issues:
https://github.com/facebook/lexical/issues/2660
https://github.com/ckeditor/ckeditor4/issues/484
https://github.com/ckeditor/ckeditor4/issues/3118

I've resolved glitches in my previous solution by changing the `onClick` event to `onMouseDown` and adding preventDefault if the subsequent click is more than two.

```diff
git diff src/pages/home/report/ReportActionItemMessage.js
diff --git a/src/pages/home/report/ReportActionItemMessage.js b/src/pages/home/report/ReportActionItemMessage.js
index d226ac9ced..deaf8da170 100644
--- a/src/pages/home/report/ReportActionItemMessage.js
+++ b/src/pages/home/report/ReportActionItemMessage.js

@@ -26,18 +27,33 @@ const defaultProps = {
     style: [],
 };
 
+const selectElementContents = (el) => {
+    const sel = window.getSelection();
+    sel.removeAllRanges();
+    const range = document.createRange();
+    range.selectNodeContents(el);
+    sel.addRange(range);
+};
+
+const onMouseDown = (e) => {
+    if (e.detail < 3) { return; }
+    e.preventDefault();
+    selectElementContents(e.target);
+};
+
 const ReportActionItemMessage = props => (
     <View style={[styles.chatItemMessage, ...props.style]}>
         {_.map(_.compact(props.action.previousMessage || props.action.message), (fragment, index) => (
-            <ReportActionItemFragment
-                key={`actionFragment-${props.action.sequenceNumber}-${index}`}
-                fragment={fragment}
-                isAttachment={props.action.isAttachment}
-                attachmentInfo={props.action.attachmentInfo}
-                source={lodashGet(props.action, 'originalMessage.source')}
-                loading={props.action.isLoading}
-                style={props.style}
-            />
+            <div key={`div-${props.action.sequenceNumber}-${index}`} role="presentation" onMouseDown={onMouseDown}>
+                <ReportActionItemFragment
+                    fragment={fragment}
+                    isAttachment={props.action.isAttachment}
+                    attachmentInfo={props.action.attachmentInfo}
+                    source={lodashGet(props.action, 'originalMessage.source')}
+                    loading={props.action.isLoading}
+                    style={props.style}
+                />
+            </div>
         ))}
     </View>
 );
```

No more flickering:

https://user-images.githubusercontent.com/11847279/198174311-e405f8b6-6ac9-4d6f-909c-0b350869832a.mp4

**Comment by wildan-m** [comment] 2022-10-29 02:28
### Proposal (Updated)

@thesahindia, you are right, I can also reproduce it in Safari.

I still believe that it's caused by the different triple-click behavior of browsers
At this time, behavior of default action of triple-click isn't specified the W3C spec
Other repos also experience similar issues:
https://github.com/facebook/lexical/issues/2660
https://github.com/ckeditor/ckeditor4/issues/484
https://github.com/ckeditor/ckeditor4/issues/3118

I've resolved glitches in my previous solution by changing the `onClick` event to `onMouseDown` and adding preventDefault if the subsequent click is more than two.

https://github.com/Expensify/App/blob/73922083c9bc4f2b1f050406b6e3b24c6ba98fc7/src/pages/home/report/ReportActionItemMessage/index.web.js#L10-L40

These changes will be implemented for the web and desktop only.

Complete comparison:
https://github.com/Expensify/App/commit/73922083c9bc4f2b1f050406b6e3b24c6ba98fc7

No more flickering:

https://user-images.githubusercontent.com/11847279/198174311-e405f8b6-6ac9-4d6f-909c-0b350869832a.mp4

**Comment by thesahindia** [comment] 2022-10-31 11:04
I don't prefer adding another wrapper, I wanna wait to see if someone can find the root cause and propose a more simpler solution.

**Comment by trjExpensify** [comment] 2022-10-31 14:54
@thesahindia presumably you believe this is a regression, right? 

>I still believe that it's caused by the different triple-click behavior of browsers

@wildan-m, we see the issue on the desktop app as well (not just in the Web browser), so how can that be the case?

**Comment by trjExpensify** [comment] 2022-10-31 14:56
Job price doubled to $500 on Upwork: https://www.upwork.com/jobs/~019c6881ba683194f2

**Comment by wildan-m** [comment] 2022-10-31 14:59
@trjExpensify The desktop uses electron and electron use chromium, so I think it will behave the same with chrome browser

**Comment by trjExpensify** [comment] 2022-10-31 15:12
Ah, I see. So @thesahindia, to confirm there's a root cause for this regression in App, have you gone back like 10 versions or something to see if it's there?

**Comment by trjExpensify** [comment] 2022-10-31 15:17
Outside of that, the code highlighted in [this comment](https://github.com/Expensify/App/issues/12028#issuecomment-1291460601) was added back in Sept by @marcaaron in [this PR](https://github.com/Expensify/App/pull/10929) released in `1.2.2-0`, so maybe there are some clues there?

**Comment by thesahindia** [comment] 2022-10-31 16:37
I randomly tested this at `v1.2.13-4` and wasn't able to repro, so It's definitely a regression. 
I think https://github.com/Expensify/App/issues/11921 is similar and I wasn't able to repro it at `v1.2.13-4` I think we should merge them?

**Comment by trjExpensify** [comment] 2022-10-31 17:07
Aren't they only similar insofar as it's a bug when triple clicking? It depends really if the root cause is the same?

>I randomly tested this at v1.2.13-4 and wasn't able to repro, so It's definitely a regression.

Nice! That's a good start. This was reported in `1.2.18-2` so we have a window.

**Comment by thesahindia** [comment] 2022-10-31 17:22
> It depends really if the root cause is the same?

I think the root cause is probably the same but let's wait as I am not 100% sure

**Comment by trjExpensify** [comment] 2022-11-01 01:34
Yep!

@wildan-m, are you up for taking a look at the [releases](https://github.com/Expensify/App/releases) in between `v1.2.13-4` and `1.2.18-2` to narrow down what the probable cause was? Something we changed introduced this, so starting there to inform the proposal seems like a good idea.

**Comment by wildan-m** [comment] 2022-11-01 01:36
@trjExpensify sure, I'll check it

**Comment by osama256** [comment] 2022-11-01 18:31
### Proposal

Using drawer legacy Implementation will fix this issue and [this](https://github.com/Expensify/App/issues/11921) as well.

this issue happened because we were using `@react-navigation/drawer` version below `6.3.2`, in these versions the drawer use `useLegacyImplementation={true}` by default so we didn't notice this issue but in higher versions of `@react-navigation/drawer` the part of code that causes `useLegacyImplementation={true}` always true has been removed so we need to make it manually.

in  `src/libs/Navigation/AppNavigator/BaseDrawerNavigator` : 
```diff
        const content = (
            <Drawer.Navigator
+               useLegacyImplementation
                backBehavior="none"
                key="BaseDrawerNavigator"
                defaultStatus={this.state.defaultStatus}
                sceneContainerStyle={styles.navigationSceneContainer}
                drawerContent={this.props.drawerContent}
                screenOptions={{
```

Result:

https://user-images.githubusercontent.com/51829206/199309238-8dd9b046-f590-4d30-8d94-228cb4372729.mp4

**Comment by trjExpensify** [comment] 2022-11-01 18:41
Hey @osama256, looks promising! Can you type something in the compose box to illustrate the fix as per the repro steps in the OP? Thanks!

**Comment by osama256** [comment] 2022-11-01 18:54
>Can you type something in the compose box to illustrate the fix as per the repro steps in the OP?

@trjExpensify Sure.


https://user-images.githubusercontent.com/51829206/199314486-58a67380-d467-4ff8-87ce-045278f783a1.mp4

**Comment by thesahindia** [comment] 2022-11-01 19:01
@osama256, I am getting error when testing this
<img width="349" alt="Screenshot 2022-11-02 at 12 31 10 AM" src="https://user-images.githubusercontent.com/83179295/199316473-b904b78c-aadf-40bc-bdac-b774bc5d25cb.png">

**Comment by osama256** [comment] 2022-11-01 19:44
> I am getting error when testing this

Ops, i was testing on `@react-navigation/drawer`version `6.3.2` it has the same issue but it seems it using a lower version of `react-native-reanimated`.

This is so interesting, in `@react-navigation/drawer` below `6.3.2` `useLegacyImplementation` is always true, but in the current version `useLegacyImplementation` is always false because they are using a higher version of `react-native-reanimated` that doesn't allow `useLegacyImplementation`.

Maybe we can downgrade to `6.3.1` until `react-native-reanimated` make it possible to use `useLegacyImplementation`.

**Comment by trjExpensify** [comment] 2022-11-02 00:15
CC: @roryabraham for visibility on this one wrt `react-native-reanimated`.

**Comment by michaelhaxhiu** [comment] 2022-11-03 18:44
Should we group this issue with https://github.com/Expensify/App/issues/11735? Both relate to triple-click misbehaving. They are a little different but I'd bet 1 stone (PR) can hit both birds (GHs). 🤔

**Comment by michaelhaxhiu** [comment] 2022-11-03 20:01
Also can we try to address @osama256's question above to move this forward (perhaps today or tomorrow)? I know @roryabraham is busy with projects these days so perhaps we post this Q in #expensify-open-source? 

I'll kick off a little movement in the [original thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1666188981167469) where this was reported to help move it forward.

PS @osama256 what's your slack handle?

**Comment by osama256** [comment] 2022-11-03 21:31
@michaelhaxhiu [12028](https://github.com/Expensify/App/issues/12028) and [11921](https://github.com/Expensify/App/issues/11921) are the same issue both happen on Chrome and got fixed when using `@react-navigation/drawer` version below `3.6.2`, but [11735](https://github.com/Expensify/App/issues/11735) is different it happens on Firefox and it seems not related to `@react-navigation/drawer` version.

>what's your slack handle?

My Slack ID is `U032VPYG2A2 `

**Comment by michaelhaxhiu** [comment] 2022-11-03 21:34
Mind sharing your actual email so we can invite you to #expensify-open-source? It won't let me invite by slack ID unfortunately (sorta sh*tty of slack 😢)

**Comment by thesahindia** [comment] 2022-11-03 21:39
> https://github.com/Expensify/App/issues/11735 is different it happens on Firefox and it seems not related to @react-navigation/drawer version.

Yeah it is different (not an only Firefox issue though)

**Comment by osama256** [comment] 2022-11-03 21:49
@michaelhaxhiu I'm already in #expensify-open-source Slack channel.

**Comment by thesahindia** [comment] 2022-11-03 21:55
@osama256, your username is `osamamostafa` right?

**Comment by osama256** [comment] 2022-11-03 21:58
>your username is osamamostafa right?

Yep.

**Comment by michaelhaxhiu** [comment] 2022-11-03 22:07
All set, wasn't 100% sure about the slack handle but that makes sense.

**Comment by trjExpensify** [comment] 2022-11-07 20:47
Okay, where we're at in [the thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1667514109148159?thread_ts=1666188981.167469&cid=C01GTK53T8Q):

- We don't want to downgrade. It's a step backwards in a more holistic sense, and took us a lot of time to get in a position to upgrade to revert all that work for a relatively obscure bug 
- There's a very high chance `drawer-navigation` gets deprecated with the wider project of revisiting navigation in App
- The consensus is to find another way to fix it. 
- What that is isn't known yet, open to ideas. Asking about the feasibility of entertaining an earlier idea [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667853639630239?thread_ts=1666188981.167469&cid=C01GTK53T8Q).

**Comment by trjExpensify** [comment] 2022-11-08 15:59
Okay, so a next step towards a viable proposal, we'd like the contributor to look at the legacy version to understand what in that library prevents this problem, and why it’s not present in the latest version. 

@osama256, if you're interested in investigating and updating your proposal, that would be great!

**Comment by trjExpensify** [comment] 2022-11-09 13:40
Job [doubled to $1,000](https://www.upwork.com/jobs/~019c6881ba683194f2) on Upwork.

**Comment by wildan-m** [comment] 2022-11-10 08:01
### Proposal

I've tried to compare the DOM between `1.2.15-1` and `1.2.15-2`.

Here is the result

<img width="1353" alt="Screen Shot 2022-11-10 at 14 25 27" src="https://user-images.githubusercontent.com/11847279/201030288-ee5d625e-2faa-45ce-9bea-071495e5615e.png">

What makes the issue occur is when the drawer adds `user-select: none` to `sidebar` and `reportScreen` wrapper.

I've tried to compare `drawer 6.3.1` and `drawer 6.3.2`, but couldn't find the exact code that adds the `user-select: none` property, but I'm sure we can't change it directly from `Expensify/App`

After reading this:

> @trjExpensify: There's a very high chance drawer-navigation gets deprecated with the wider project of revisiting navigation in App

I think the fastest and easiest solution is to normalize the inner wrapper property. We can add `userSelect: 'auto'` to `ReportScreen` wrapper

```diff
git diff src/styles/styles.js
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 4363f1825f..1cc094d4a7 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1233,6 +1233,7 @@ const styles = {
     appContent: {
         backgroundColor: themeColors.appBG,
         overflow: 'hidden',
+        userSelect: 'auto',
     },
 
     appContentHeader: {
```

The advantages of this workaround:
1. Simple and fast to implement
2. Doesn't depend on legacy behavior of the `drawer`

Please let me know your thoughts @thesahindia, @trjExpensify

**Comment by thesahindia** [comment] 2022-11-10 14:31
Awesome! We can implement this.
But can you please add explanation about how `userSelect` property is affecting the behaviour and why using `userSelect: 'auto'` fixes it.

**Comment by wildan-m** [comment] 2022-11-11 03:01
@thesahindia 
> how userSelect property is affecting the behaviour

I've created a codepen to create a similar issue:
https://codepen.io/wildanmuhlis2/pen/KKeWGQr?editors=1000

That codepen is not precisely the same, but close enough.

Result In Chrome: (Chromium Based/Webkit)
<img width="212" alt="image" src="https://user-images.githubusercontent.com/11847279/201250959-f5b1398a-4527-45d0-b636-097a46ae5456.png">

Result in Safari: (Webkit)
<img width="186" alt="image" src="https://user-images.githubusercontent.com/11847279/201251065-822c7ff2-fbdf-4cfb-bd6d-e4ea5a8cb99c.png">

Result in Mozilla: (Gecko)
<img width="226" alt="image" src="https://user-images.githubusercontent.com/11847279/201251112-e491668d-1f29-4057-b4c4-812111f40293.png">

Chrome also selects the text inside the text input.
Safari not selecting the text but the selection overlaps with the following line.
Mozilla has no issue.

Similarly, I can only reproduce our bug in Chrome and Safari.

I still believe that it's caused by the different triple-click behavior of browsers
At this time, the behavior of the default action of triple-click isn't specified in the W3C spec

> why using userSelect: 'auto' fixes it.

From: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

> Note: user-select is not an inherited property, though the initial auto value makes it behave like it is inherited most of the time. WebKit/Chromium-based browsers do implement the property as inherited, which violates the behavior described in the spec, and this will bring some issues. Until now, Chromium has chosen to [fix the issues](https://chromium.googlesource.com/chromium/src/+/b01af0b296ecb855aac95c4ed335d188e6eac2de) to make the final behavior meet the specifications.

In Chromium and Webkit-based browsers, `user-select` is an [inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance), so it will inherit the values to all of its child elements by default, if we can normalize/override the value then it will fix our issue. The reason I choose `auto` is its default value.

**Comment by thesahindia** [comment] 2022-11-11 16:41
What I was trying to understand is why `user-select: none` is causing this issue just to be sure about the root cause, I tested this at codepen and now I don't have doubts about it. 

@wildan-m, can you please test that your solution will work on all platforms?

**Comment by wildan-m** [comment] 2022-11-11 17:57
@thesahindia 
I've found chromium code that causes and might fix this behavior:
https://github.com/chromium/chromium/commit/31a47fcc693beef11e18e442342d156f296c3559

It's committed 16 days ago. It might be merged into chrome but I'm not sure when.

Forgot to add `WebkitUserSelect: auto` for Safari:

```diff
git diff src/styles/styles.js
diff --git a/src/styles/styles.js b/src/styles/styles.js
index f2d7cff023..ff418ef535 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1236,6 +1236,8 @@ const styles = {
     appContent: {
         backgroundColor: themeColors.appBG,
         overflow: 'hidden',
+        userSelect: 'auto',
+        WebkitUserSelect: 'auto',
     },
 
     appContentHeader: {
```

I've tested it on the web (chrome, FF, Safari), and desktop and the result is OK.
In Android, it doesn't create any defects thus far. Haven't tested it on ios yet, but I think it will be OK too.

Note:
There is [a newly reported issue](https://github.com/Expensify/App/issues/12554) that prevents us to use `Cmd+C` in safari. Temporarily we can use the edit menu to copy/paste

**Comment by wildan-m** [comment] 2022-11-12 03:51
@thesahindia just tested it on iOS. The result is OK

**Comment by thesahindia** [comment] 2022-11-14 12:24
The [codepen example](https://codepen.io/wildanmuhlis2/pen/KKeWGQr?editors=1000) has the same issue so it's confirmed that `user-select: 'none'` is causing this as mentioned [here](https://github.com/Expensify/App/issues/12028#issuecomment-1309908376)
I like @wildan-m's [proposal](https://github.com/Expensify/App/issues/12028#issuecomment-1312003771), the styles will be passed at `ScreenWrapper`
https://github.com/Expensify/App/blob/e09d22847b476e9a5bc864e4722aa3e5dd4d50ac/src/pages/home/ReportScreen.js#L235-L236

C+ reviewed 🎀👀🎀

cc: @chiragsalian

**Comment by chiragsalian** [comment] 2022-11-15 01:00
Proposal LGTM, feel free to create the PR @wildan-m.

**Comment by trjExpensify** [comment] 2022-11-29 11:26
Alrighty, time to settle up! Payments due: 

$1000 - @wildan-m (C) - offer sent 
$1000 - @thesahindia (C+) - settled 👍 
$500 - @mollfpr for reporting this issue & #11921 - settled 👍

**Comment by trjExpensify** [comment] 2022-11-29 11:32
As for the checklist: 

1. We don't need to add a manual regression test for this minor edge case
2. Where the regression was introduced is known (i.e the drawer navigation lib upgrade) 
3. The engineer that spearheaded the upgrade is aware, as we had a discussion about it in Slack already.

**Comment by trjExpensify** [comment] 2022-11-29 11:51
Alrighty, @wildan-m settled up! Closing, thanks everyone! 🎉

**Comment by thesahindia** [comment] 2022-11-29 11:53
@trjExpensify, I think it's also eligible for the 50% bonus 😄

**Comment by trjExpensify** [comment] 2022-11-29 12:08
Oh, bloody hell! 😅 Sent you both contracts for that.

**Comment by trjExpensify** [comment] 2022-11-29 13:54
Cool, all sorted.

**Closed by trjExpensify** 2022-11-29 13:54 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
