### ISSUE TITLE
Distance offline - Can't delete red dot Error on the request preview in the expense report

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38392] opened 2024-03-15 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4424763&group_by=cases:section_id&group_order=asc&group_id=295814
**Email or phone of affected tester (no customers):** applausetester+requestor.yuriy.14.mar@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Turn off the network
2. Crete distance request with way points kind of “hdhdfjfnfb”
3. Turn on the network
4. Wait for Reddot error
5. Open request details (now you have two reddot errors in the LHN)
6. Try to dismiss reports with reddot errors

## Expected Result:
The user should be able to dismiss red dot errors because of invalid Distance expense

## Actual Result:
There is no button to dismiss red dot error on the request preview in the expense report.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f1241ebe-7dc4-401b-bd14-f52eaaa72045

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-15 12:38
@alexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-15 12:38
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by trjExpensify** [comment] 2024-03-15 13:46
It would be great if the steps were more specific about which chats etc have the red brick road and don't clear properly. Here's my understanding of the issue being reported: 

**>Action steps**
> 1. Go offline
> 2. Crete a distance request with invalid waypoints (e.g "hdhdfjfnfb”)
> 3. Go back online
> 4. Observe the "unexpected error" message is added as the distance requests fails to create
> 5. Observe the red brick road (RBR) red dots added to both the workspace chat row and the expense report row in the LHN
> 6. Dismiss the error message ("X") beneath the report preview component in the workspace chat
> 7. Observe the expense report preview component disappears from the workspace chat and the RBR red dot is cleared from the workspace chat row in the LHN
> 8. Observe the expense report row in the LHN remains and with the RBR red dot 
> 9. Click into the expense report 
> 10. Click on the distance request preview 
> 11. Observe the 404 "Hmm.. it's not there" full page blocking error 

For the expected results. I think this is less about the RBR being dismissable on the expense report, but rather, why does it remain accessible at all? Recall you dismissed the error message and the report preview component disappeared, so it should have been deleted and thus removed from the LHN completely. 

>**Expected Results**
>When the error message is dismissed, delete the distance request and expense report. (Of course, don't do that if there are other expenses on the report already!)

Let me know if I'm missing something! CC: @paultsimura @neil-marcellini @hayata-suenaga 

https://github.com/Expensify/App/assets/16232057/05d89089-e0fc-4755-abd0-d65adaac870c

**Comment by trjExpensify** [comment] 2024-03-15 14:41
Ah, interesting.. why isn't the expense report showing up in the LHN when you give it a go? See mine from above: 

<img width="1096" alt="image" src="https://github.com/Expensify/App/assets/16232057/1bfc4fe3-e32c-4683-b42c-96cb0266dfa2">


1. It fails after coming back online
2. The expense report row appears in the LHN with a red dot (in addition to the workspace chat row).
3. Dismissing the error on the expense report preview component inside the workspace chat doesn't remove the expense report row from the LHN

>This is reproducible only for 1:1 Distance Requests (which is still under Beta).

My repro was distance requests to a workspace, so not 100% sure on that.

**Comment by trjExpensify** [comment] 2024-03-15 14:47
I thought it might be a violations beta or something, but I don't have that beta enabled on my @trj.chat domain.

**Comment by trjExpensify** [comment] 2024-03-15 14:56
Just tried it again, same result: 

https://github.com/Expensify/App/assets/16232057/51d5d655-3d5f-4f35-ad44-41302834baa7

**Comment by neil-marcellini** [comment] 2024-03-15 15:54
I haven't investigated this much, but it should be noted that we never implemented the planned design for handling errors creating distance requests since it was deemed low priority.

Here is the issue for that [[LOW] Distance: Handle errors with geocoding for offline distance requests](https://github.com/Expensify/App/issues/22719#top). We keep having issues created about this. I think we should fix it and use a violations based approach.

**Comment by trjExpensify** [comment] 2024-03-15 16:05
Ah yeah, totally. If we're committed to doing that, then let's go for it. Minimally, it shouldn't get stuck like it is now though in the current imp.

**Comment by alexpensify** [comment] 2024-03-16 00:48
@neil-marcellini and @trjExpensify - should we assign this one as `External`?

**Comment by hayata-suenaga** [comment] 2024-03-16 16:54
I didn't know that dismissing the error results in the deletion of the distance request. That's what I didn't expect...

But if the intended behavior is to delete the money request (expense report), then I agree it shouldn't be there after dismissing the error.

**Comment by trjExpensify** [comment] 2024-03-18 12:08
Yeah, I think ideally we would handle this in a way that still creates a partial transaction that the member can edit the waypoints to fix it - @neil-marcellini references an approach in the [linked issue](https://github.com/Expensify/App/issues/22719#issue-1799825068).

I didn't think that was happening though. So if the expense fails to get created (not even "partially"), then dismissing the error on the "failed" expense would delete the expense report its on if: 

- it's the only expense on the expense report
- there aren't any comments to preserve

Anyhow.. @hayata-suenaga do you think we can take the other issue external to implement a better process for this, or does it need to be internal? If it can go external, perhaps @paultsimura you might be interested in helping with that given you have good context around the distance feature.

**Comment by hayata-suenaga** [comment] 2024-03-18 16:59
> do you think we can take the other issue external to implement a better process for this, or does it need to be internal?

I feel like this needs backend changes as well as front end changes. I'll wait for @neil-marcellini's response though 😄

**Comment by alexpensify** [comment] 2024-03-18 22:57
Alright, waiting for @neil-marcellini's feedback.

**Comment by alexpensify** [comment] 2024-03-20 23:58
Neil has been traveling, so I sent a chat so the last bump didn't get lost in the mix.

**Comment by neil-marcellini** [comment] 2024-03-22 10:41
Hi thanks for the DM Al!

I really think that we should take this internal and design a complete solution with a small design doc. As Tom mentioned, we need to have partial transactions created instead of the request completely failing. Currently the request is not created at all in the backend, so that's why dismissing the error deletes everything. It would also go away if you sign out and back in. To do this the right way, we need backend changes.

Most of the desired behavior in the [linked issue](https://github.com/Expensify/App/issues/22719) still makes sense, but it's written from the perspective of failing to create the initial distance request, rather than creating a partial transaction and using violations.

Let's also confirm broadly in Slack that we want to invest in fixing this now. I don't have the capacity to take this on, but maybe others are interested?

**Comment by alexpensify** [comment] 2024-03-22 19:27
Ok, thanks! I'll start a discussion on Monday.

**Comment by alexpensify** [comment] 2024-03-26 00:31
I didn't get to the discussion today, I'll start one tomorrow.

**Comment by alexpensify** [comment] 2024-03-29 00:31
I started a discussion here: https://expensify.slack.com/archives/C036QM0SLJK/p1711672068496949

**Comment by alexpensify** [comment] 2024-03-29 17:20
Moving to Weekly, for now, I'll bump again next Tuesday when there is more team online.

**Comment by alexpensify** [comment] 2024-04-03 22:08
We have more team online, I bumped the 🧵.

**Comment by alexpensify** [comment] 2024-04-05 22:19
We are in agreement here: 

>There should be a request when offline should be consistent across all request types, so we should bring distance in-line with manual and scan. 

We still need to develop a plan here on how to tackle it.

**Comment by alexpensify** [comment] 2024-04-12 23:30
Ok, next week, I'll need to recruit for help here.

**Comment by alexpensify** [comment] 2024-04-17 21:30
I've been dealing with other GHs and haven't been able to recruit for help. 

## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-04-26 21:09
Still on my radar to get help here.

**Comment by alexpensify** [comment] 2024-05-03 17:02
Weekly Update: No update

**Comment by alexpensify** [comment] 2024-05-10 23:05
Weekly Update: No update, the team has been focused on the May 1 release.

**Comment by alexpensify** [comment] 2024-05-17 16:31
## Heads up, I will be offline until Tuesday, May 28, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

--- 

Since there are higher-priority GHs, I've moved this to Monthly and will regroup when I'm back online.

**Comment by alexpensify** [comment] 2024-06-17 21:54
There is no update yet; other GHs and site needs have been a higher priority.

**Comment by mallenexpensify** [comment] 2024-06-28 00:22
@paultsimura , plz comment so I can assign. Added to 
- https://github.com/Expensify/App/issues/44582

**Comment by alexpensify** [comment] 2024-06-28 14:07
Hi @paultsimura - I've assigned you the GH. Thanks!

**Comment by alexpensify** [comment] 2024-07-04 22:49
Thanks for the update! Just a heads up, @mallenexpensify will help move this GH forward when he returns from Holiday.

**Comment by mallenexpensify** [comment] 2024-07-08 23:15
[Checking on in #wave-collect ](https://expensify.slack.com/archives/C036QM0SLJK/p1720480476291019?thread_ts=1711672068.496949&cid=C036QM0SLJK)

**Comment by mallenexpensify** [comment] 2024-07-09 22:50
@paultsimura , I'm in the process of getting you added to  #wave-collect since there are offline distance conversations happening there. 

This PR just hit production
- https://github.com/Expensify/App/pull/43011#top

The above should (somewhat) help with minimizing the red dot error showing, if the user is traveling to/from the same places frequently. 

For next steps specific to this issue, let's try to figure out why this distance expense that we couldn’t create isn’t being deleted when the RBR is dismissed. Do you have any idea why that might be happening @paultsimura ?

**Comment by neil-marcellini** [comment] 2024-07-09 23:19
As I said in Slack, but repeating it here for @paultsimura, I think we don't clean up all the optimistic data for the distance request when it's deleted, so that's what we'll need to do.

**Comment by mallenexpensify** [comment] 2024-07-15 22:15
I'm uncertain, it _sounds_ right but I defer to @neil-marcellini

**Comment by mallenexpensify** [comment] 2024-07-24 01:26
@neil-marcellini 👀 above plz

**Comment by mallenexpensify** [comment] 2024-07-26 19:28
Pinging Neil in NewDot for 👀

**Comment by neil-marcellini** [comment] 2024-07-26 20:51
Sorry for the delay, thanks for the ping Matt.



> Hey @neil-marcellini @mallenexpensify – from the discussion here and in Slack, I understand the proper solution, for now, will be to remove the failed distance request when dismissing the error. Is that correct?
> 
> If so – we can make this External as the solution is quite straightforward from what I see.

Yeah that's the plan. I think it was already implemented in this issue though [[HOLD for payment 2024-07-26] [$250] BUG: Failed distance request isn't cleaned up properly](https://github.com/Expensify/App/issues/42950#top)

**Comment by mallenexpensify** [comment] 2024-07-29 22:11
added `Weekly` and `retest-weekly`

**Comment by mvtglobally** [comment] 2024-08-09 04:37
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-08-12 23:08
Not able to reproduce either, so closing.

**Closed by mallenexpensify** 2024-08-12 23:08 UTC
Labels: Weekly, Overdue, Bug, retest-weekly
