### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] IOU - Multiline IOU description from 1:1 DM in LHN is not truncated

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39437] opened 2024-04-02 20:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM with user that has no unsettled IOU.
3. Create a money request with multiline description.

## Expected Result:
The 1:1 DM preview in LHN will show truncated IOU description.

## Actual Result:
Multiline IOU description from 1:1 DM in LHN is not truncated.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9dd4cdf6-3874-4c6d-8e56-11dbc0c44069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d08ecf7ecf737a6d</li>
        <li>Upwork Job ID: 1775285976769712128</li>
        <li>Last Price Increase: 2024-04-02</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-02 20:20
We think that this bug might be related to #vip-vsb

**Comment by bernhardoj** [comment] 2024-04-03 02:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat report LHN subtitle shows as multiline when having a money request with multi line description.

### What is the root cause of that problem?
The LHN subtitle when there is a report preview is taken from this logic.
https://github.com/Expensify/App/blob/6463de625ddc2e370b6c38d57b082207f02ccbbc/src/libs/OptionsListUtils.ts#L541-L558

`getReportPreviewMessage` has lots of logic inside it, but in our case, it returns `{payer} owes {amount} for {description}`. If the description is multi-line, the LHN will show it as multi-line too. This doesn't happen if we open the IOU report because in IOU report, the action is a money request action, and for money request action we already handle the multiline by using `formatReportLastMessageText`.
https://github.com/Expensify/App/blob/6463de625ddc2e370b6c38d57b082207f02ccbbc/src/libs/OptionsListUtils.ts#L538-L541

I think this issue has been there and not a regression. In production, the LHN subtitle won't show the description of the money request (`{payer} owes {amount}`) (which is a regression from this [PR](https://github.com/Expensify/App/pull/37773)). Then, the regression is fixed by adding back the description and now the QA catch this multi-line issue.

### What changes do you think we should make in order to solve the problem?

Use `formatReportLastMessageText` for report preview action too.
https://github.com/Expensify/App/blob/6463de625ddc2e370b6c38d57b082207f02ccbbc/src/libs/OptionsListUtils.ts#L541-L557

or maybe we can use it when returning the value here so all case is applied,
https://github.com/Expensify/App/blob/6463de625ddc2e370b6c38d57b082207f02ccbbc/src/libs/OptionsListUtils.ts#L580

**Comment by chiragsalian** [comment] 2024-04-03 17:10
Proposal LGTM, are you around to create a PR for this @bernhardoj in the next hour or so?

**Comment by bernhardoj** [comment] 2024-04-03 17:19
Yes, I'm available. Will open the PR in a few moments.

**Comment by bernhardoj** [comment] 2024-04-03 17:54
PR is ready

cc: @parasharrajat

**Comment by chiragsalian** [comment] 2024-04-03 20:50
Fixes have been CP-d to staging. Tested on staging and it LGTM so removing blocker label.
![image](https://github.com/Expensify/App/assets/14356145/0641f271-d03f-4586-9761-a4555e3e5259)

![image](https://github.com/Expensify/App/assets/14356145/e1e0e37c-a5fd-4878-99e1-16d6bc582eeb)

**Comment by chiragsalian** [comment] 2024-04-03 20:50
Thanks for the quick turnaround time 🙂

**Closed** 2024-04-15 18:02 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-07-02 13:19
$500 approved for @parasharrajat
