### ISSUE TITLE
[HOLD for payment 2024-01-17] [$500] Web - Profile - Legal name not saved/no validation if language specific characters used

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33294] opened 2023-12-19 15:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.1.14.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log in New Expensify with any account
2. Navigate to Settings > Profile > Personal details > Legal name
3. Enter first and last names which contain language specific characters e. g., "Stanisław" and "Kamiński"
4. Click on Save

## Expected Result:
Either the Legal name should be saved or a validation error informing that such characters are not supported should be shown.

## Actual Result:
User is redirected back to Personal details page, and the Legal name is briefly shown but disappears, no validation errors.
The same characters are correctly saved and rendered if used in Display name.
Reproduced with Polish, Turkish, Slovak characters.
Example names to reproduce:
Polish: Stanisław, Rafał, Kamiński.
Turkish: Çağrı, Şimal.
Slovak: Matúš, Mikuláš

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/733cb384-c8db-4c96-8a6b-64a17f151ad3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129b368859e3458c1</li>
        <li>Upwork Job ID: 1739984270624288768</li>
        <li>Last Price Increase: 2023-12-27</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28070802</li>
<li>sourcecodedeveloper | Contributor | 28070803</li>
</ul></li>
    </ul>
</details>

**Comment by sourcecodedeveloper** [comment] 2023-12-19 15:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Profile - Legal name is not saved if language specific characters are used.
### What is the root cause of that problem?
The updateLegalName calls api "UpdateLegalName" and if the first or last name contains language specific characters, the backend replaces the name string with empty string.
https://github.com/Expensify/App/blob/b3ecf327c585ca323a628405f4ffc70877c601a0/src/libs/actions/PersonalDetails.ts#L189

### What changes do you think we should make in order to solve the problem?
Need to add validation logic to ValidationUtils.isValidLegalName

https://github.com/Expensify/App/blob/b3ecf327c585ca323a628405f4ffc70877c601a0/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L58

**Comment by steve-zhao0903** [comment] 2023-12-19 16:29
The API request for Updating Legal Name is **https://www.expensify.com/api?command=UpdateLegalName**(POST method)
This is the payload ( **https://prnt.sc/yCmHYb3m-Bys** )
As we see, payload is correct. but if we see the response, it doesn't return the legalFirstname and legalLastName ( **https://prnt.sc/e1JVZW0AyvVb**)
So I think this issue is related on the Backend side.

**Comment by steve-zhao0903** [comment] 2023-12-19 16:32
Contributor details
Your Expensify account email: darren.zhao0903@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0148c62c1a4c8e3182

**Comment by sourcecodedeveloper** [comment] 2023-12-19 16:38
The backend parses out input string when the regex on the backend matches with invalid input. The similar happens when setting workspace name. The issue should be handled on front end.

**Comment by kmwamasali** [comment] 2023-12-19 19:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Profile - Legal name not saved/no validation if language specific

### What is the root cause of that problem?
The validation check for the legal name only passes if the characters are in latin text

https://github.com/Expensify/App/blob/91c7d0c6a9c8c418ae0273dfb4c49f7de52ca2c1/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L58

### What changes do you think we should make in order to solve the problem?
Add more language validations to the regex that tests the name validity
https://github.com/Expensify/App/blob/91c7d0c6a9c8c418ae0273dfb4c49f7de52ca2c1/src/libs/ValidationUtils.ts#L320C24-L320C24

**Comment by narefyev91** [comment] 2023-12-20 07:39
Proposal from @sourcecodedeveloper looks good to me https://github.com/Expensify/App/issues/33294#issuecomment-1863006900
We already have FE logic to validate characters - let's adjust it
🎀 👀 🎀 C+ reviewed

**Comment by sourcecodedeveloper** [comment] 2023-12-20 11:13
@narefyev91 Thanks. I understand I need to wait to get assigned to the issue before preparing PR.

**Comment by narefyev91** [comment] 2023-12-20 11:18
> @narefyev91 Thanks. I understand I need to wait to get assigned to the issue before preparing PR.

Yup we need final review from @luacmartins

**Comment by luacmartins** [comment] 2023-12-20 11:22
all yours @sourcecodedeveloper

**Comment by sourcecodedeveloper** [comment] 2023-12-20 17:13
@luacmartins thanks

**Comment by sourcecodedeveloper** [comment] 2023-12-25 09:18
@narefyev91 [PR](https://github.com/Expensify/App/pull/33563#issue-2055545499) is ready for review.

**Comment by situchan** [comment] 2023-12-25 09:30
@narefyev91 is now not in C+ team. I can take over if needed.

**Comment by sourcecodedeveloper** [comment] 2023-12-25 09:46
@luacmartins @mountiny Please advise.

**Comment by sourcecodedeveloper** [comment] 2023-12-25 13:16
@luacmartins was assigned before, can probably review the [PR](https://github.com/Expensify/App/pull/33563#issue-2055545499).

**Comment by sourcecodedeveloper** [comment] 2023-12-26 22:44
@mountiny one of the offers should be for the reviewer role but both the offers came out for the contributor role. The second offer should for the reviewer not contributor.

**Comment by situchan** [comment] 2023-12-26 22:55
@sourcecodedeveloper nvm, not affect your payment

**Comment by sourcecodedeveloper** [comment] 2023-12-27 07:46
@situchan cannot be two contributors on the issue, one is contributor and other is reviewer. @mountiny please assign reviewer role.

**Comment by situchan** [comment] 2023-12-27 07:48
@sourcecodedeveloper I will be reviewing https://github.com/Expensify/App/pull/33563. Ignore Melvin's comment

**Comment by sourcecodedeveloper** [comment] 2023-12-27 07:49
@situchan there cannot be two contributors assigned to the issue.

**Comment by sourcecodedeveloper** [comment] 2023-12-27 07:52
@situchan reviewing PR means reviewer role not contributor @mountiny please kindly switch roles.

**Comment by sourcecodedeveloper** [comment] 2023-12-27 08:31
@mountiny Please kindly settle the dispute and send nice reviewer role offer to @situchan. Thanks.

**Comment by sourcecodedeveloper** [comment] 2023-12-27 11:59
@mountiny just need to sending offer for reviewer role would only take few minutes. Another approach would be to since @situchan volunteered to be contributor, they can review the PR as contributor and direct their questions and queries to the assigned internal engineer. The assigned internal engineer that is @luacmartins can review their queries and then decide on the essential aspect and make suggestions. I can wait for @luacmartins to respond, the delay is not an issue as there is really no rush bonus and among other reasons to get the PR out.

**Comment by sourcecodedeveloper** [comment] 2023-12-27 12:20
@mountiny Thank so very much. made the sun shine again

**Comment by sakluger** [comment] 2024-01-02 20:49
Hmm, that actually made things a bit confusing, now each contributor has been sent two Upwork offers. No worries - since the original offers are for the correct amounts and since they have been accepted, we can use those (even though they both say "contributor", it's okay as long as we are paying the correct amounts). I'm going to withdraw the new offers to keep things simple.

Here are the offers we will be paying out once the PR is deployed:

- Contributor+: @situchan - https://www.upwork.com/nx/wm/offer/28069800
- Contributor: @sourcecodedeveloper - https://www.upwork.com/nx/wm/offer/28066013

**Comment by sourcecodedeveloper** [comment] 2024-01-03 08:30
@sakluger the first two offers should have been withdrawn instead of the new offers to line up with the correct roles. Keeps things tidy.

**Comment by sakluger** [comment] 2024-01-04 23:19
@sourcecodedeveloper - The amounts are the same for both roles, so it's okay if the role in the Upwork job title is incorrect, as long as everyone gets paid the correct amount. Since the original offers have already been accepted, I am going to use those offers when we need to pay out.

**Comment by situchan** [comment] 2024-01-18 03:47
No PR caused regression. We can skip regression test as caught by QA team.

**Comment by sakluger** [comment] 2024-01-18 22:34
Sounds good, thanks!

**Closed by sakluger** 2024-01-18 22:34 UTC
Labels: External, Daily, Awaiting Payment, Bug
