### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500]  [Distance] - Route is generated without green line connecting the points after going online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26589] opened 2023-09-02 23:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25980
## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Go to + > Request money > Distance
4. Go to Start > Select address 1 Telegraph Hill Blvd, San Francisco, CA 94133, USA
5. Go to Finish > Select address 88 Kearny St, San Francisco, CA 94108, USA
6. Go online

## Expected Result:
The route is generated from the start to the finish point with a green line connecting

## Actual Result:
The route is generated without a green line connecting the start and finish point

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.62-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ec2970a9-9415-4818-87bd-56cacb68fd01

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017f0ebdf18950167a</li>
        <li>Upwork Job ID: 1699079489951641600</li>
        <li>Last Price Increase: 2023-09-05</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 26511344</li>
<li>pradeepmdk | Contributor | 26511347</li>
</ul></li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-09-04 04:21
> Proposal
> Please re-state the problem that we are trying to solve in this issue.
> Display route line when the device comes back online
> 
> What is the root cause of that problem?
> [App/src/components/DistanceRequest.js](https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L92)
> 
> Line 92 in [d0b2772](https://github.com/Expensify/App/commit/d0b277206ff8b80f8b447ecb49437cec0446f2f8)
> 
>  const doesRouteExist = lodashHas(transaction, 'routes.route0.geometry.coordinates'); 
> 
> here we are checking the coordinates key or not so its will be always true
> because coordinates we are setting as null every every waypoint save
> [App/src/libs/actions/Transaction.js](https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/libs/actions/Transaction.js#L63)
> 
> Line 63 in [d0b2772](https://github.com/Expensify/App/commit/d0b277206ff8b80f8b447ecb49437cec0446f2f8)
> 
>  coordinates: null, 
> 
> but its have null value so that when come back online
> [App/src/components/DistanceRequest.js](https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L158)
> 
> Line 158 in [d0b2772](https://github.com/Expensify/App/commit/d0b277206ff8b80f8b447ecb49437cec0446f2f8)
> 
>  Transaction.getRoute(iou.transactionID, waypoints); 
> not triggering this one
> What changes do you think we should make in order to solve the problem?
> we should update the logic
> 
>     const doesRouteExist = lodashHas(transaction, 'routes.route0.geometry.coordinates') && transaction.routes.route0.geometry.coordinates && transaction. routes.route0.geometry.type;
> token init as well we should update
> 
>     useEffect(() => {
>         if(isOffline) {
>             return;
>         }
>         MapboxToken.init();
>         return MapboxToken.stop;
>     }, [isOffline]);
> when refresh as well working fine

This is a proposal from @pradeepmdk from [this dupe issue](https://github.com/Expensify/App/issues/26596) (which I closed).

This proposal looks good. Assigning @pradeepmdk 

@hoangzinh thank you for letting me know about the dupe. You identified the cause correctly, but I don't believe we need to update the logic for optimistic update. I prefer we set the key but leave the value null (I believe this is the pattern we use across App).

**Comment by hayata-suenaga** [comment] 2023-09-04 04:24
Also, @pradeepmdk could you comment something on this issue? Otherwise, I cannot assign you 😓

**Comment by pradeepmdk** [comment] 2023-09-04 04:26
from https://github.com/Expensify/App/issues/26596#issuecomment-1704024545

### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Display route line when the device comes back online
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L92
here we are checking the `coordinates` key or not   so its will be always true 
because coordinates we are setting as null every every waypoint save 
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/libs/actions/Transaction.js#L63 
but its have null value so that when come back online
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/components/DistanceRequest.js#L158 not triggering this one 



### What changes do you think we should make in order to solve the problem?

we should update the logic 
```javascript
    const doesRouteExist = lodashHas(transaction, 'routes.route0.geometry.coordinates') && transaction.routes.route0.geometry.coordinates && transaction. routes.route0.geometry.type;
``` 

token init as well we should update 
```javascript

    useEffect(() => {
        if(isOffline) {
            return;
        }
        MapboxToken.init();
        return MapboxToken.stop;
    }, [isOffline]);
``` 

`when refresh as well working fine`

**Comment by pradeepmdk** [comment] 2023-09-04 04:41
@hayata-suenaga Yes we don't need that MapboxToken.init() because when coming back online `GetMapboxAccessToken` API is triggering.

**Comment by b4s36t4** [comment] 2023-09-04 04:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance - Route is generated without green line connecting the points after going online
### What is the root cause of that problem?

Coordinates are null and we're not fetching route by calling `getROute` method even if go offline.

https://github.com/Expensify/App/blob/aeffabf2d39af8ef03440d5d69bcb074d1826dd7/src/components/DistanceRequest.js#L92 this will be true even if we have null.

### What changes do you think we should make in order to solve the problem?
We could simply change it to the following line.

```jsx
    const doesRouteExist = lodashGet(transaction, 'routes.route0.geometry.coordinates') !== null;
```

This will set https://github.com/Expensify/App/blob/aeffabf2d39af8ef03440d5d69bcb074d1826dd7/src/components/DistanceRequest.js#L93 `true` when we come back online this will trigger route calling api.


### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/59088937/3d150422-7545-4d76-93c0-d3bf2aebe3c2

**Comment by hayata-suenaga** [comment] 2023-09-05 04:00
@pradeepmdk I apologize for the delay in assigning you to this issue 🙇 

This issue doesn't have a particularly high priority in terms of Distance Request. So we don't have to hurry into merging the PR.

**Comment by pradeepmdk** [comment] 2023-09-05 04:06
@hayata-suenaga np. I will raise the PR. Can you make this external? so that an upwork contract will be created.

**Comment by hayata-suenaga** [comment] 2023-09-05 17:04
yaaaay offer was finally created!

**Comment by pradeepmdk** [comment] 2023-09-06 00:50
@hayata-suenaga Since this one was handled in another PR what should I do now? [paultsimura](https://github.com/paultsimura/Expensify/tree/fix-26537)

Since already worked and am ready to Raise the PR

**Comment by hayata-suenaga** [comment] 2023-09-06 03:47
@pradeepmdk 

The issue you linked handles a different issue (when online, the amount should be "TBD"), while this issue handles the refetching of the route when the devices comes back online after being offline

**Comment by pradeepmdk** [comment] 2023-09-06 04:45
@hayata-suenaga thanks you.let me raise the pr now.

**Comment by pradeepmdk** [comment] 2023-09-06 05:02
@ntdiary  same that was i am thinking  that is the solution and in my proposal also included that null check from lodash.
https://github.com/Expensify/App/issues/26589#issuecomment-1704591168.

so there is no purpose to raise the PR here.

**Comment by pradeepmdk** [comment] 2023-09-07 12:25
useEffect(() => {
        if(isOffline || mapboxAccessToken.token) {
            return;
        }
        MapboxToken.init();
        return MapboxToken.stop;
    }, [isOffline, mapboxAccessToken.token]);

https://github.com/Expensify/App/assets/16595846/7faf176e-763e-48ce-9d29-efa7b6c9884d

when token is not there its not triggering still we need this condition 
@ntdiary @hoangzinh  let me raise the PR 
this is i already included in my proposal https://github.com/Expensify/App/issues/26596#issuecomment-1704024545

**Comment by pradeepmdk** [comment] 2023-09-07 13:41
useEffect(() => {
        if(isOffline || mapboxAccessToken.token) {
            return;
        }
        MapboxToken.init();
        return MapboxToken.stop;
    }, [isOffline, mapboxAccessToken.token]);

so this token not there we try load again
so we need to set null `connectionIDForToken` and  `connectionIDForNetwork` then only it will load the token 
https://github.com/Expensify/App/blob/d0b277206ff8b80f8b447ecb49437cec0446f2f8/src/libs/actions/MapboxToken.js#L141

https://github.com/Expensify/App/assets/16595846/7faf176e-763e-48ce-9d29-efa7b6c9884d

when token is not there its not triggering still we need this condition 

this is i already included in my proposal https://github.com/Expensify/App/issues/26596#issuecomment-1704024545

steps:
1)   when you login go offline
2) then go  distance and set point a and point b map doesn't load when come to online.

and when login and go to oflline means mapbox junk loader error happen  so we need address so when you get this even when you go to online map is not loading to address this 

![Screenshot 2023-09-07 at 6 58 23 PM](https://github.com/Expensify/App/assets/16595846/6be23887-a7ec-4b50-bcb0-b3219396269e)

we need load on this app.js but we should check only .web.js load this fille 
```javascript
import  'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';
``` 
and ``


since this issue offline only @ntdiary @hoangzinh  let me raise the PR

**Comment by pradeepmdk** [comment] 2023-09-08 03:35
@ntdiary @hayata-suenaga Pr is ready for view

**Comment by hayata-suenaga** [comment] 2023-09-11 02:42
> offline --> open distance request --> online --> close distance request --> re-open distance request.

Does this mean that closing the distance request page before the token is fetched after the device comes back online?

**Comment by neil-marcellini** [comment] 2023-09-27 02:48
I'm marking this as done. Let's handle payment and get it closed. If we still need more PRs please update the status to LOW again. Thanks.

**Comment by sakluger** [comment] 2023-10-12 05:57
All paid out! Thanks everyone.

**Closed by sakluger** 2023-10-12 05:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
