### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] [P2P Activation] [HIGH] Pay button in the workspace / DM view is different from the report view

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#29735] opened 2023-10-17 00:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697491822501769

## Action Performed:

1. User A: select Request money
2. User A: enter User B as the person you're requesting from
3. User B: login
4. User B: Navigate to the IOU report, verify you see a split button with a dropdown
5. User B: navigate to the IOU report within the DM

## Expected Result:

The pay button should be the “split pay” button in all cases, like we have in the report view, which allows the payment option a user chooses (first screenshot). And additionally, the split button should work as follows in all cases:

- First time user with USD workspace/iouReport: Pay with Expensify (clicking it should go to wallet page to enable it)
- First time user with non-USD workspace/iouReport: Pay elsewhere (clicking it should manually reimburse the report)
- Returning user: display the lastPaymentMethod used i.e Pay with Expensify or Pay elsewhere

## Actual Result:
The button within the DM/workspace chat view is not split, and therefore does not show a default payment method or the option to change it.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/Expensify/App/assets/22508290/e998b976-c67d-44e7-b985-2446c6b6f343)
![image](https://github.com/Expensify/App/assets/22508290/b84ee0dd-4c4a-445f-a272-eff0d2d63c2e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a1dc28bc812f8183</li>
        <li>Upwork Job ID: 1714286754518675456</li>
        <li>Last Price Increase: 2023-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27265389</li>
<li>akinwale | Contributor | 27265391</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-10-17 02:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The pay button in the report view for a DM does not show a dropdown with payment options.

### What is the root cause of that problem?
The SettlementButton used in the `ReportPreview` component does not have the `shouldShowPaymentOptions` prop enabled.

### What changes do you think we should make in order to solve the problem?
Add `shouldShowPaymentOptions` prop to the SettlementButton in `ReportPreview`.

### What alternative solutions did you explore? (Optional)
None.

**Comment by s77rt** [comment] 2023-10-17 20:44
Confirmed. This need to be fixed.

**Comment by s77rt** [comment] 2023-10-17 20:46
@akinwale Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29735#issuecomment-1765536650)

**Comment by neil-marcellini** [comment] 2023-10-18 19:22
> @akinwale Thanks for the proposal. Your RCA is correct and the solution looks good to me 👍
> 
> 🎀 👀 🎀 C+ reviewed [Link to proposal](https://github.com/Expensify/App/issues/29735#issuecomment-1765536650)

I agree, go for it!

**Comment by akinwale** [comment] 2023-10-18 19:34
@s77rt My [PR](https://github.com/Expensify/App/pull/29902) is ready for review. Thanks.

**Comment by trjExpensify** [comment] 2023-10-20 10:34
@kevinksullivan this one is merged, but awaiting the next staging deploy today. It won't make it to prod ahead of Money2020 on Sunday, but likely Monday with a prod deploy if it passes on staging later.

**Comment by s77rt** [comment] 2023-10-23 21:55
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18692
- The offending PR has been commented on: Not applicable since this was done on purpose and not really a bug
- A discussion in #expensify-bugs has been started: Not needed (not a bug but a design change)
- Determine if we should create a regression test for this bug: No

**Comment by greg-schroeder** [comment] 2023-10-31 15:16
sorry was OOO yesterday, processing today

**Comment by greg-schroeder** [comment] 2023-11-01 03:23
Paid

**Closed by greg-schroeder** 2023-11-01 03:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
