### ISSUE TITLE
[$500] Tapping on back arrow in the thread takes user to LHN instead of the parent message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36040] opened 2024-02-07 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707282748260789

## Action Performed:
1. Open any report
2. Long press and start thread
3. send a message
4. Tap back arrow 
## Expected Result:
Taking user to parent message
## Actual Result:
Takes user to LHN
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/cb5efb4c-7518-41a7-a15f-33382e8946af

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2adb75f9035e2a6</li>
        <li>Upwork Job ID: 1755260136545419264</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-07 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tapping on back arrow in the thread takes user to LHN instead of the parent message

### What is the root cause of that problem?
This is a regression caused by recent changes (Ideal Nav) https://github.com/Expensify/App/pull/33280 of setting the `ROUTES.HOME` from empty string to `Home` now. 
So before when we goBack with home as fallback ` Navigation.goBack(ROUTES.HOME, false, true); ` b/c home is empty string it will falsify this
https://github.com/Expensify/App/blob/f6ba751301d6a6f4e5faa092e615d49fb02d2746/src/libs/Navigation/Navigation.ts#L229-L230
So whenever possible it will `navigationRef.current.goBack` so it worked fine
### What changes do you think we should make in order to solve the problem?

Now everywhere we are calling ` Navigation.goBack(ROUTES.HOME, false, true); ` it is not working right so we have to change in 
`Navigation.goBack` everywhere we used `fallbackRoute` as a condition we need to check it is not `ROUTES.HOME`
```
fallbackRoute && fallbackRoute !== ROUTES.HOME
```
Or similarly everywhere in the codebase we are using `ROUTES.HOME` as a fallbackRoute we need to pass empty string to revert back the previous behaviour
### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2024-02-07 17:37
Unassiging this one due to low bandwidth, please reassign @garrettmknight!

**Comment by situchan** [comment] 2024-02-07 17:41
This should be part of https://github.com/Expensify/App/issues/35626

**Comment by situchan** [comment] 2024-02-07 17:52
@adamgrzybowski please confirm that your PR fixes this as well

**Comment by hayata-suenaga** [comment] 2024-02-07 18:49
this issue is tracked in [this GH issue](https://github.com/Expensify/App/issues/35626). Closing this one 🙇

**Closed by hayata-suenaga** 2024-02-07 18:49 UTC
Labels: External, Daily, Help Wanted, Bug
