### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Login - Focus is shown on login field briefly and scrolled down

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45571] opened 2024-07-17 08:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.8
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4729962
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre- condition
1. Log out of app and clear history and cache
2. Go to https://staging.new.expensify.com/home

## Expected Result:
Focus should be on top login screen and must not scrolled down

## Actual Result:
Focus is shown on login field briefly and scrolled down.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/984a5c37-5a39-4968-9ae7-7e3fbbffb06f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012686d622c878c512</li>
        <li>Upwork Job ID: 1813517786978772508</li>
        <li>Last Price Increase: 2024-07-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by izarutskaya** [comment] 2024-07-17 08:00
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment] 2024-07-17 08:01
We think this issue might be related to the #vip-vsb

**Comment by Julesssss** [comment] 2024-07-17 10:19
[This](https://github.com/Expensify/App/pull/44932#issuecomment-2232955347) PR seems a likely cause. I am hesitant to revert as it fixes many issues.

**Comment by bernhardoj** [comment] 2024-07-17 11:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The login page is scrolled down.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/44932. In that PR, we update the focus trap initial focus logic so that if there is already a focused element, the initial focus won't fire.
https://github.com/Expensify/App/blob/e3b508b89933b44f5ccd59e65e8152ad2f47a6d6/src/components/FocusTrap/FocusTrapForScreen/index.web.tsx#L44-L50

However, on the login page, none of the elements is already focused, so the initial focus fires and focuses on the footer text link instead of the login field. Why? That's because the login form is wrapped with `withOnyx` which delays the input field rendering, so the initial focus found the footer text link first.
https://github.com/Expensify/App/blob/fc9b7ac988a1e520fcdb904ae13dfd6e091f8bcd/src/pages/signin/LoginForm/BaseLoginForm.tsx#L337-L343

On the login page, we actually have a logic to auto-focus the login input field, but it's only for desktop/web. For mWeb/native, we won't auto-focus the input field.
https://github.com/Expensify/App/blob/fc9b7ac988a1e520fcdb904ae13dfd6e091f8bcd/src/pages/signin/LoginForm/BaseLoginForm.tsx#L166-L177

Previously, we always ignored the focus trap initial focus for the login page.

### What changes do you think we should make in order to solve the problem?

Bring back the previous logic that ignores the focus-trap initial focus for login page.

```
const SCREENS_WITH_AUTOFOCUS: string[] = [SCREENS.SIGN_IN_ROOT];

function getScreenWithAutofocus(isAuthenticated: boolean) {
    if (!isAuthenticated) {
        return [...SCREENS_WITH_AUTOFOCUS, NAVIGATORS.BOTTOM_TAB_NAVIGATOR];
    }
    return SCREENS_WITH_AUTOFOCUS;
}

if (screensWithAutofocus.includes(activeRouteName) || isFocusedElementInsideContainer) {
    return false;
```

The `isFocusedElementInsideContainer` logic works well to prevent the initial focus from happening when there is already a focused element, but there is a case where we don't want an initial focus at all, such as sign-in page.

**Comment by mallenexpensify** [comment] 2024-07-19 00:11
@suneox drafted the (likely) [offending PR](https://github.com/Expensify/App/pull/44932) so assigning to them for now.

**Comment by mallenexpensify** [comment] 2024-08-01 18:39
@puneetlath I'm off til Monday afternoon, can you help with payment here? Thx

**Comment by s77rt** [comment] 2024-08-02 01:42
No payment due here. Let's close

**Closed** 2024-08-02 11:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
