### ISSUE TITLE
[$250] mWeb - Chat - Entering multi line text by tapping enter key, cursor goes down instead of next line

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48544] opened 2024-09-04 11:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4919668
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Copy the url and paste in compose
4. Send the message
5. Edit the message by long pressing the message
6. Remove url text and try to enter multi line text by tapping enter key

## Expected Result:
Entering multi line text by tapping enter key, cursor must go to next line

## Actual Result:
Entering multi line text by tapping enter key, cursor goes down instead of next line

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a732486b-d5d7-46c8-a265-a1434259fe77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831319729138132205</li>
        <li>Upwork Job ID: 1831319729138132205</li>
        <li>Last Price Increase: 2024-09-25</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-09-04 11:47
Production:

https://github.com/user-attachments/assets/10cd64e4-eb21-4e85-9ddd-0eaefefb24a4

**Comment by kaushiktd** [comment] 2024-09-05 06:33
when I long-press the message, the option to "Copy URL to clipboard" appears instead of the "Edit" option. How can I resolve this issue and enable message editing?
 here is the video
 
[screen-capture.webm](https://github.com/user-attachments/assets/8a4bd030-26a9-495a-9688-d9e2064774b5)

**Comment by alexpensify** [comment] 2024-09-09 17:12
@Gonals can we get your feedback here? Thanks!

**Comment by Gonals** [comment] 2024-09-11 09:28
> @Gonals @lanitochka17 when I long-press the message, the option to "Copy URL to clipboard" appears instead of the "Edit" option. How can I resolve this issue and enable message editing? here is the video
> 
>  screen-capture.webm

Don't press directly on top of the URL. Just the general message.

**Comment by alexpensify** [comment] 2024-09-13 16:51
@Ollyws when you get a chance, can you review these proposals? Thanks!

**Comment by alexpensify** [comment] 2024-09-16 23:05
Open for proposals here

**Comment by kaushiktd** [comment] 2024-09-17 04:02
@Ollyws when long press on any text message, It shows all the option to edit the message, but when trying to edit URL message or link. It doesn't show edit comment option. It shows only Copy URL. You can find attached image.
![Simulator Screenshot - iPhone 15 Pro - 2024-09-17 at 09 29 31](https://github.com/user-attachments/assets/27529434-edf2-47d2-8ec7-eba3f25740a3)

**Comment by alexpensify** [comment] 2024-09-18 19:30
Waiting for proposals here

**Comment by alexpensify** [comment] 2024-09-20 22:17
Still open here

**Comment by alexpensify** [comment] 2024-09-23 17:23
It is not overdue; we are open to proposals here.

**Comment by QichenZhu** [comment] 2024-09-24 03:46
> The composer is focused before the context menu disappears, causing issues with the focus trap and React event system. PR https://github.com/Expensify/App/pull/48973 will fix this by adding a delay.

The PR has been merged, and this issue is no longer reproducible.

https://github.com/user-attachments/assets/8d60896d-5979-43cf-a4b4-63652ef68401

**Comment by alexpensify** [comment] 2024-09-25 21:41
Closing - it looks like this one was fixed in another GH. Thanks for the update.

**Closed** 2024-09-27 18:02 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
