### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$500] Android - Bank Account - Connect bank account page blinks when navigate from Bills page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27901] opened 2023-09-20 23:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to Workspace Editor
2. Tap on Pay Bills
3. Click on connect bank account

## Expected Result:
User should be redirected to the Connect Bank Account page and none errors should appear

## Actual Result:
Connect bank account page blinks when navigate from Bills page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.72-6

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/969b9a29-d92a-4980-a71a-1808870a6413

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011699c610be6cc9cd</li>
        <li>Upwork Job ID: 1707628269307260928</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>honnamkuan | Contributor | 27123291</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by thienlnam** [comment] 2023-09-21 08:53
Let's fix this, but removing the blocker as it's a minor bug

**Comment by bfitzexpensify** [comment] 2023-09-25 13:25
@marcochavezf is this something we need to handle internally or can it be worked on by contributors?

**Comment by bfitzexpensify** [comment] 2023-09-28 16:02
Bump on https://github.com/Expensify/App/issues/27901#issuecomment-1733709679 @marcochavezf

**Comment by marcochavezf** [comment] 2023-09-29 05:27
Hmm interesting and thanks for the analysis @honnamkuan, yeah this looks like it should be fixed internally. Applying the label

**Comment by marcochavezf** [comment] 2023-10-02 13:35
No update

**Comment by marcochavezf** [comment] 2023-10-05 19:06
I'm swamped with other high-priority items, I will come back to this one after I finish the other pending items

**Comment by marcochavezf** [comment] 2023-10-09 14:41
No update, but prioritizing this one for this week

**Comment by marcochavezf** [comment] 2023-10-10 16:27
After checking the implementation for the Onyx object `reimbursementAccount` in the backend and the default state expected in NewDot, I think it would be better to go with the proposed frontend changes, since the default value for `achData.state` has been empty for OldDot. So, I think it's better to check in the frontend if that value is not empty, as stated in the proposal for root cause 1. 

Assigning @honnamkuan 🚀

**Comment by bfitzexpensify** [comment] 2023-10-19 21:28
**Payment summary:**

**Contributor:** @honnamkuan to be paid $750 (work completed + #urgency bonus) via Upwork
**C+:** @rushatgabhane to be paid $750 (work completed + #urgency bonus) via manual request

**Comment by bfitzexpensify** [comment] 2023-10-19 21:28
Switching this to daily so that I'm on top of it when it's due for payment next week

**Comment by bfitzexpensify** [comment] 2023-10-20 18:24
Due 10/23

**Comment by JmillsExpensify** [comment] 2023-10-23 16:58
$750 payment approved for @rushatgabhane based on summary above.

**Comment by bfitzexpensify** [comment] 2023-10-24 23:08
Thanks for detailed explanation @hoangzinh. 

Of those two behaviours, I think this makes sense to me:
>If no, we should remove the workspace bank account's error out of an RBR in the user avatar. [link to code](https://github.com/Expensify/App/blob/eee46dc3e9fffd2fb737dadbd70975f752787a42/src/components/Indicator.js#L82)

**Comment by bfitzexpensify** [comment] 2023-10-24 23:08
Also a reminder to complete the BZ checklist [here](https://github.com/Expensify/App/issues/27901#issuecomment-1767186884) @rushatgabhane

**Comment by bfitzexpensify** [comment] 2023-10-27 16:46
Bump on the BZ checklist @rushatgabhane - thank you!

**Comment by bfitzexpensify** [comment] 2023-10-31 22:24
@rushatgabhane another bump on the BZ checklist, thank you

**Comment by bfitzexpensify** [comment] 2023-11-07 13:26
Just waiting on BZ checklist here, Melv

**Comment by marcochavezf** [comment] 2023-11-09 18:13
Friendly bump @rushatgabhane

**Comment by rushatgabhane** [comment] 2023-11-14 05:39
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-11-17 06:27
@bfitzexpensify this bug exists since Bank Account flow was first implemented. It's difficult to point out a PR and not so much useful.

**Comment by bfitzexpensify** [comment] 2023-11-17 20:13
Cool that makes sense. Let's close this one out then.

**Closed by bfitzexpensify** 2023-11-17 20:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
