### ISSUE TITLE
[$250] [Tags] Newly added tag status is `disabled` and refreshing the page changes to `enabled`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38265] opened 2024-03-14 00:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Collect workspace.

1. Go to staging.new.expensify.com.
2. Go to Settings > Workspaces > Collect workspace.
3. Go to Categories.
4. Click Add category and add a category.
5. Note that the status of the new category is "Enabled".
6. Go to Tags.
7. Click Add tag and add a tag. observe the status of the tag
8. As employee,  initiate a expense report flow and click on the tag
OR
9. Refresh the page at the step 7

## Expected Result:
Newly added tag should be `enabled ` by default or the tag should not show for employee since it is disabled by default

## Actual Result:
- New tag status is `disabled` and when refreshing the page it changes to `enabled`
- For employee the added tag showing to select

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/1df25d9b-e364-4ac6-a7c3-0b3ec4bc0fc3

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010353991d7fc3df7f</li>
        <li>Upwork Job ID: 1768104273053810688</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by robertjchen** [comment] 2024-03-14 02:42
Not a deploy blocker. Opening for External Contributors

**Comment by Tony-MK** [comment] 2024-03-14 02:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Newly added tag status is disabled and refreshing the page changes to enabled

### What is the root cause of that problem?

In the event the backend fails to create the policy,  the `createPolicyTag` function optimistically sets `enable` as `false` because we don't want to use it in any money request while offline.

https://github.com/Expensify/App/blob/13f8bc010e824312707058eebc0fb5f43c2514dc/src/libs/actions/Policy.ts#L2776-L2781

https://github.com/Expensify/App/blob/13f8bc010e824312707058eebc0fb5f43c2514dc/src/libs/actions/Policy.ts#L2787-L2796

However, when the policy is created successfully, the backend does not set `enable` as `true`. 

Since we are not setting `enable` as `true` in the `successData`, the created policy stays disabled.

https://github.com/Expensify/App/blob/13f8bc010e824312707058eebc0fb5f43c2514dc/src/libs/actions/Policy.ts#L2794-L2796

### What changes do you think we should make in order to solve the problem?


In the `createPolicyTag` function, set `enabled` as `true` in  `successData` over [here](https://github.com/Expensify/App/blob/13f8bc010e824312707058eebc0fb5f43c2514dc/src/libs/actions/Policy.ts#L2794-L2796).

**Comment by jeremy-croff** [comment] 2024-03-14 04:05
The requirements for this are unclear as there's no real precedence. Should the default state of tags be enabled, or disabled, and the BE shouldn't be enabling it?

  There's a design doc on this in here https://github.com/Expensify/App/issues/37311 but I don't have access. Is this experience confirmed?

**Comment by robertjchen** [comment] 2024-03-14 05:12
@jeremy-croff Good point! cc: @luacmartins for clarification on the proper behavior here 🙏

**Comment by askavyblr** [comment] 2024-03-14 11:27
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**

The newly added tag status is disabled and refreshing the page changes to enabled

**What is the root cause of that problem?**

when the user creates Tags by Default Disable and when the user refreshes the page API gets called api?command=OpenPolicyTagsPage and makes it enable 

`"key": "policyTags_5E9B96705932918F",
            "onyxMethod": "set",
            "value": {
                "Tag": {
                    "name": "Tag",
                    "orderWeight": 0,
                    "required": true,
                    "tags": {
                        "PPP": {
                            "enabled": true,
                            "name": "PPP"
                        },
                        "Tag1": {
                            "enabled": true,
                            "name": "Tag1"
                        },
                        "Tag2": {
                            "enabled": true,
                            "name": "Tag2"
                        },
                        "Test": {
                            "enabled": true,
                            "name": "Test"
                        },
                        "Testaaa": {
                            "enabled": true,
                            "name": "Testaaa"
                        },
                        "test2": {
                            "enabled": true,
                            "name": "test2"
                        }`


**What changes do you think we should make in order to solve the problem?**

https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/Policy.ts#L2777-L2778

In the createPolicyTag function, set enabled as true

**Comment by luacmartins** [comment] 2024-03-14 17:14
Thanks for the ping. We'll address this in a follow up PR since this feature is still WIP. cc @waterim all tags should be enabled by default.

**Comment by laurenreidexpensify** [comment] 2024-03-21 10:24
@rushatgabhane bump for review of proposals ^^

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:15
Oh completely misread the above - @luacmartins is taking this on, so we don't need a proposal review of externals.

**Comment by laurenreidexpensify** [comment] 2024-03-21 14:16
@trjExpensify adding to wave-collect as this is tag related

**Comment by trjExpensify** [comment] 2024-03-21 19:00
Noice!

**Comment by luacmartins** [comment] 2024-03-21 19:01
PR up!

**Comment by luacmartins** [comment] 2024-03-21 19:21
Gonna close this issue in favor of https://github.com/Expensify/App/issues/38192

**Closed by luacmartins** 2024-03-21 19:21 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
