### ISSUE TITLE
Web - Assign Task - The padding of the placeholder in different search fields is inconsistent.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22020] opened 2023-07-01 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access the Staging environment and locate the search icon next to the user avatar.
2. Input a name or number in the corresponding placeholder.
3. Observe the padding of the input field along with the entered text.
4. Proceed by clicking the plus sign.
5. Select the "Assign Task" option.
6. Enter a title and click on "Next".
7. Navigate to the "Share somewhere" fields.
8. Input a name or number in the respective placeholder.
9. Observe the padding of the fields for Name, email, or phone number.

## Expected Result:
The padding of the placeholders should be consistent across all pages.

## Actual Result:
 The padding of the placeholders is inconsistent.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6301fd57-6329-4856-a8f3-48628d7ef244

https://github.com/Expensify/App/assets/93399543/293b1f3c-d2f3-49af-98cd-f5bc2d371dd8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688200232292059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by conorpendergrast** [comment] 2023-07-03 11:51
I agree that this is a dupe of https://github.com/Expensify/App/issues/22045, which was reported earlier in Slack. Closing this

**Closed by conorpendergrast** 2023-07-03 11:51 UTC
Labels: Daily, Bug
