### ISSUE TITLE
[Tracking] Investigate IOU commands running to same ID collision

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#13738] opened 2022-12-20 21:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

We have seen that for CreateIOUSplit, CreatePolicy, CreateIOUTransaction, SendMoney and SendMoneyWithWallet, we run into error which signals that the same request has been sent multiple times while the first one succeeded and we tried to create a row in the database with the same id, which fails.

Internal issues for the command failures:
- PayWithWallet 
    - https://github.com/Expensify/Expensify/issues/250629
- SendMoney 
    - https://github.com/Expensify/Expensify/issues/250179
    - https://github.com/Expensify/Expensify/issues/250345
- CreateIOUTransaction 
    - https://github.com/Expensify/Expensify/issues/250309
    - https://github.com/Expensify/Expensify/issues/248926
    - https://github.com/Expensify/Expensify/issues/249687
    - https://github.com/Expensify/Expensify/issues/248926
    - https://github.com/Expensify/Expensify/issues/248224
    - https://github.com/Expensify/Expensify/issues/248212
    - https://github.com/Expensify/Expensify/issues/240998
    - https://github.com/Expensify/Expensify/issues/245318
    - https://github.com/Expensify/Expensify/issues/240997
    - https://github.com/Expensify/Expensify/issues/275299
- CreateIOUSplit
    - https://github.com/Expensify/Expensify/issues/238482
    - https://github.com/Expensify/Expensify/issues/238570
    - https://github.com/Expensify/Expensify/issues/301510
- CreatePolicy
    - https://github.com/Expensify/Expensify/issues/229712  
    - https://github.com/Expensify/Expensify/issues/228660
    - https://github.com/Expensify/Expensify/issues/228658

Reproduction steps for PayWithWallet:
https://github.com/Expensify/App/pull/12646#issuecomment-1359880911

It might need a **high-traffic account**.

We can expect the reproduction steps are similar to pay with wallet
1. Force user to be offline
2. Send money/ Request money from someone you have chatter before (and you have the report loaded)
3. The IOU Preview should show greyed out automatically 
4. Go online
5. Confirm the IOU preview is not greyed out and you dont see any error

## Expected Result:
Describe what you think should've happened

No error shown if the action succeeded.

## Actual Result:
Describe what actually happened

There is an error https://user-images.githubusercontent.com/4741899/208730156-b71e9f0e-082c-42d5-9415-43cbd86dfe01.png, but it is not right, after refresh the message is shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Everything works fine after refresh, the error is confusing UI though.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** https://user-images.githubusercontent.com/4741899/208730156-b71e9f0e-082c-42d5-9415-43cbd86dfe01.png
**Issue reported by:** @yuwenmemon 
**Slack conversation:** here https://expensify.slack.com/archives/C03TQ48KC/p1671559412497409 and here https://expensify.slack.com/archives/C03TQ48KC/p1671549525089169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017cdd21c4f565ed9a</li>
        <li>Upwork Job ID: 1605311650796871680</li>
        <li>Last Price Increase: 2022-12-20</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2022-12-20 21:21
Hey @thesahindia sorry nothing to do right here, this will require internal investigation.

Keeping you assigned @alexpensify as we might need someone to pay out down the line

**Comment by mountiny** [comment] 2022-12-21 23:51
havent had time to look today

**Comment by alexpensify** [comment] 2022-12-23 19:45
@mountiny - I'm going OOO until January 3 and will catch up then to identify if there is any movement here. If you need to issue a payment next week, please reassign the issue to another member on Bug Zero who can help with the Upwork process. Chat with you in 2023!

**Comment by mountiny** [comment] 2022-12-25 16:37
Havent bee able to reproduce reliably locally but we know this is happening in staging/production so it can be a variation of the network state/ size of a policy/chat potentially.

**Comment by alexpensify** [comment] 2022-12-30 18:49
I'm still OOO and plan to review next week when I'm back online.

**Comment by mountiny** [comment] 2023-01-03 13:09
No problem, there was no traction on this one, I have also been ooo

**Comment by mountiny** [comment] 2023-01-09 14:03
Other priorities

**Comment by alexpensify** [comment] 2023-01-11 20:19
Thanks for the update @mountiny-- safe travels!

**Comment by mountiny** [comment] 2023-01-18 17:14
Not super high priority not causing issues to clients.

**Comment by cead22** [comment] 2023-01-21 00:04
@mountiny I looked at the logs for https://github.com/Expensify/Expensify/issues/248926 and found the following

The call to the CreateIOUSplit auth command is passing `"iouReportID":"8824324229232110"`
> Bedrock\Client - Starting a request ~~ command: 'CreateIOUSplit' clusterName: 'auth' headers: '[authToken: '<REDACTED>' chatReportID: '2441593069105568' amount: '500' splits: '[{"email":"jatinsonidev+010@icloud.com","amount":250},{"email":"jatinsonidev@icloud.com","amount":250,"iouReportID":"8824324229232110","chatReportID":"7391743059865632","transactionID":"3795588431536333239","reportActionID":"2152671604058566207","clientID":"1674226326525232"}]' currency: 'INR' comment: '' transactionID: '5881579255060231882' reportActionID: '2626203818684704724' createdReportActionID: '0' clientID: '1674226326522371' isFromGroupDM: '1' idempotent: '' logParam: 'jatinsonidev+010@icloud.com' commitCount: '18324566281' requestID: '78c8a1d12ad63386-LAX' lastIP: '157.38.110.253' writeConsistency: 'ASYNC' priority: '500' timeout: '290000']'

We log the following before the failure
>Creating original transaction for IOU Split with ID 5881579255060231882
>Creating initial IOU split action for reportID 2441593069105568
>CreateReport::process reportID 8824324229232110

And then we see the error, notice the same reportID 8824324229232110

>{SQLITE} Code: 1555, Message: abort at 25 in [INSERT INTO reports ( reportID, created, state, accountID, reportName, currency ) VALUES ( 8824324229232110, ...

So I think what's happening is:
- After logging the lines above, we call `JSON::Value transaction = auth.transaction.createIOU` passing   `iouReportID=8824324229232110`
- In there we call `const int64_t reportID = auth.report.getOrCreateIOUReport` passing `newIOUReportID=8824324229232110`

We the log the following, and call `reportID = auth.report.createWithAction` passing `newReportID=8824324229232110`
>Creating a new IOU report for 14251014 and shared with 12924254

- We call `Report::createWithAction` passing `reportID=8824324229232110`
- We call `Report::create` passing `reportID=8824324229232110`
- We log `CreateReport::process reportID 8824324229232110`
- And then call `INSERT INTO REPORTS(reportID,...) VALUES (8824324229232110,...)`

Can you double check if I traced this correctly? if I'm right this isn't a collision, it's a bug

**Comment by cead22** [comment] 2023-01-21 00:19
I tried splitting a bill with @mountiny and couldn't reproduce

**Comment by cead22** [comment] 2023-01-21 02:00
I submitted a PR to add some logging that I think could be helpful

**Comment by mountiny** [comment] 2023-01-23 14:33
@cead22 Thank you for looking into this. I do follow your flow and seems correct to me.

However, I am not sure if I follow where there is a bug? Can you elaborate on that please? In either case more logs will be helpful to figure this out.

To be clear I dont think we are actually getting collisions, I think there is _some_ bug, but I dont think I understood where you are pointing at here.

**Comment by cead22** [comment] 2023-01-23 20:11
In short, my theory is that we're calling `CreateIOUSplit` with `iouReportID` set to an existing reportID, which we end up passing down all the way to `CreateReport::process` which fails because that reportID already exists in the database -- it's not one that was generated in the client but that hasn't been saved to the database yet.

That said, I tried reproducing and couldn't. I'm not sure if it was because I couldn't trigger the API call `SplitBill`, I was only able to trigger `SplitBillAndOpenReport` (I don't know if they're different)

**Comment by mountiny** [comment] 2023-01-24 14:11
> SplitBill

You can trigger split bill if you `SplitBill` from the existing group chat (not from the Green + button) 

I think I might now understand what you mean, I think we had a bug which was similar to this in payWithWallet just now, where if you Paid money request, we did not set the iouReportId to `null` for the other clients, if that makes sense. Here is a [PR](https://github.com/Expensify/Web-Expensify/pull/36165).

So then if the other user would want to request money we would reuse the report ID, I think.

We should look if this is covered correctly in the other flows

**Comment by mountiny** [comment] 2023-01-25 09:01
Updated the issue so this reflects that this is more a tracking issue for all the collision IDs. Still investigating.

**Comment by alexpensify** [comment] 2023-01-26 18:20
Thanks for the update here @mountiny

**Comment by cead22** [comment] 2023-01-28 00:24
@mountiny here are logs for requests that failed with `UNIQUE constraint failed: reports.reportID`. None of them show the new log line that we added `Generated random reportID:`, and for all of them, if you search for the repotID the error line `'read/write transaction', query failed with error #19 (UNIQUE constraint failed:...`, you'll see that the reportID was passed as a param to each of the API commands. So I'm more convinced that we're just holding it wrong in these flows
- [RequestMoney](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278feed0efe581ac6-SAN%22)+AND+timestamp:[2023-01-27T04:00:40.922Z+TO+2023-01-27T06:00:40.922Z]&index=logs_expensify-020618)
- [SplitBillAndOpenReport](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278feedd35e121ac6-SAN%22)+AND+timestamp:[2023-01-27T04:01:11.808Z+TO+2023-01-27T06:01:11.808Z]&index=logs_expensify-020618)
- [RequestMoney](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278feee9e28e61ac6-SJC%22)+AND+timestamp:[2023-01-27T04:01:44.270Z+TO+2023-01-27T06:01:44.270Z]&index=logs_expensify-020618)
- [RequestMoney](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2278feef99e80c1ac6-SAN%22)+AND+timestamp:[2023-01-27T04:02:24.519Z+TO+2023-01-27T06:02:24.519Z]&index=logs_expensify-020618)

**Comment by mountiny** [comment] 2023-01-30 10:19
Thanks for getting back to this! I think the solution to this might be in the request retry logic:
- https://github.com/Expensify/Expensify/issues/210356
- https://github.com/Expensify/App/issues/13667

**Comment by cead22** [comment] 2023-02-01 02:38
Why do you think it's the retry logic? I'm not saying it isn't but I can't think how this would happen, because we should only retry if a request fails, but in this case the first request wouldn't fail, so why would we replay those requests?

**Comment by mountiny** [comment] 2023-02-01 13:33
Ah I dont really know what specifically is the problem, what I meant is that the only way this is happening is that the client send a request with the same parameter multiple times, even if the first one succeeded, right? Thats is what we are seeing, we have already processed the request, in database we saved the action with particular reportActionID or report with reportID, but a request with the same params seems to come through causing the collision.

**Comment by mountiny** [comment] 2023-02-09 20:15
Still on a backburner

**Comment by cead22** [comment] 2023-02-10 00:55
No updates from me either

**Comment by alexpensify** [comment] 2023-02-17 19:46
Any updates here or still a lower priority?

**Comment by mountiny** [comment] 2023-02-22 18:52
We are also finishing the IOU migration to reportAction ids now so maybe we will see some improvement because of that

**Comment by alexpensify** [comment] 2023-02-24 20:37
Thank you for the update!

**Comment by mountiny** [comment] 2023-03-01 17:05
no updates from me

**Comment by alexpensify** [comment] 2023-03-03 23:31
Thank you for the update here

**Comment by alexpensify** [comment] 2023-03-10 21:42
No update

**Comment by alexpensify** [comment] 2023-03-17 20:55
ECX has been the focus for the full team-- no update

**Comment by alexpensify** [comment] 2023-03-24 23:21
@mountiny and @cead22 - any update here?

**Comment by mountiny** [comment] 2023-03-25 11:04
Havent had time to investigate, its a lower priority now

**Comment by mountiny** [comment] 2023-03-27 11:18
I dont think the manual requests will change in a big way if this is happening. I still believe this is mostly related to the queue and retry logic. I am happy to leave this for someone else to do a deep dive, I have not had time lately.

Maybe @cead22 will want to continue exploring

**Comment by mountiny** [comment] 2023-04-05 18:56
N7 priority

**Comment by mountiny** [comment] 2023-04-13 19:03
No update from my side

**Comment by alexpensify** [comment] 2023-04-21 22:00
@mountiny - I hope you have been enjoying the SF office, checking in if there is an update here. I'm pretty sure there are other priorities but checking in.

**Comment by mountiny** [comment] 2023-04-21 22:54
Not much progress its not blocking users now so not a priority but I can see we are still hitting these errors from time to time

**Comment by alexpensify** [comment] 2023-04-29 00:42
I think Lounge and other GHs have been a priority, but correct me if I'm wrong.

**Comment by mountiny** [comment] 2023-04-29 00:45
Definitely I think we can make this monthly with Tasks, Threads and Manual requests right now, this does not seems to be causing issues to customers right now.

**Comment by alexpensify** [comment] 2023-04-29 01:37
Perfect, thank you for updating to a monthly.

**Comment by mountiny** [comment] 2023-05-19 12:12
Thanks, I think this one is still in a backlog, its not causing issues afaik

**Comment by alexpensify** [comment] 2023-05-24 16:38
Thank you for the update @mountiny

**Comment by alexpensify** [comment] 2023-06-23 16:31
@mountiny and @cead22 - any news here?

**Comment by cead22** [comment] 2023-06-23 16:43
Not from me, I haven't looked at this in a long time, so going to unassign. I'm not sure what the next steps are here

**Comment by mountiny** [comment] 2023-07-06 03:26
Same here, I believe also CarlosM is looking into similar issue on montly basis with no luck. its not a problem affecting users it seems so..

**Comment by JmillsExpensify** [comment] 2023-07-17 23:07
Given that this isn't strictly related to manual requests, I'm actually going to remove this initiative from the project. Feel free to add back if you disagree and thing we should tackle this as part of wave3 cleanup?

**Comment by alexpensify** [comment] 2023-08-21 14:06
@mountiny any update here?

**Comment by mountiny** [comment] 2023-08-21 14:56
No, cannot really get to these with eave3 and wave4 priorities

**Comment by pecanoro** [comment] 2023-09-11 09:37
This seems to have spiked recently for CreateIOUTransaction

![image](https://github.com/Expensify/App/assets/6474442/a4aa2069-55b5-4736-b4a1-6c9141121a33)

**Comment by mountiny** [comment] 2023-09-11 13:56
Most likely just way more testing of these flows because of the conferences, we did not really ever get a report of the command not working because of this so its truly a mistery still, cannot reproduce locally and I believe @luacmartins has been trying for  some other commands too

**Comment by luacmartins** [comment] 2023-09-12 00:45
This is likely the client not getting an update and sending the request with an old iouReportID. I think we should handle this cases more gracefully and just create a new report and update clients though.

**Comment by alexpensify** [comment] 2023-09-21 19:18
Thanks for the feedback!

**Comment by alexpensify** [comment] 2023-10-20 20:39
No recent update, keeping as a monthly

**Comment by alexpensify** [comment] 2023-11-18 01:41
Monthly Update: No news here

**Comment by alexpensify** [comment] 2023-12-18 17:57
Monthly Update: No news

**Comment by mountiny** [comment] 2024-01-18 20:06
Most of these are closed now, not sure if we need to spend much time on this now or we should just close, things work fine and I assume most of these issue come from repeated API command with stale optimistic IDs

@luacmartins @cead22 thoughts on closing this?

**Comment by luacmartins** [comment] 2024-01-18 20:43
I'm good with closing this and reopening if it comes up again.

**Comment by alexpensify** [comment] 2024-01-18 22:30
Alright, based on one of the Carlos' feedback then I'm going to close. Thanks!

**Closed by alexpensify** 2024-01-18 22:30 UTC
Labels: Engineering, Monthly, Internal, Needs Reproduction
