### ISSUE TITLE
Chat - User B name displayed instead of User A

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24105] opened 2023-08-03 12:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22467

## Action Performed:
1. Start a DM between userA and userB
2. Click on the plus actions icon next to "write something.." in the compose message box and select "request money"
3. Click on the expense request preview

## Expected Result:
In the expense report, confirm the subheader says From <userA full name>

## Actual Result:
Subheader displayed as user B name and "From To" UI not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.49.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ea37a8f7-9bf5-411e-83a7-f33b32ff9230

![Bug6151595_Screen_Shot_2023-08-03_at_8 22 05_AM](https://github.com/Expensify/App/assets/78819774/cd212067-9345-4e14-8a2c-d72836ec4023)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-08-03 14:29
That is the parent report name, not a user name. Isn't this intentional?

**Comment by puneetlath** [comment] 2023-08-03 21:35
Yes, I agree with @s-alves10, this is not a bug. It's telling you the parent room this is coming from, which in this case is the DM with userB. Closing!

**Closed by puneetlath** 2023-08-03 21:35 UTC
Labels: Daily, Bug
