### ISSUE TITLE
[$500] Teachers Unite - 'It's not here' page appears briefly before workspace welcome message shows up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29764] opened 2023-10-17 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.3.85-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Save the world > I am a teacher > Sign up.
3. When redirected to Teachers United workspace chat, click + before welcome message shows up.
Note that it's not here appears briefly.

## Expected Result:
'It's not here' page will not appear.

## Actual Result:
'It's not here' page appears briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/115492554/4b6fe1c4-4a35-416e-9c4a-9e1b017238e4

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fa5ace67d976bd9e</li>
        <li>Upwork Job ID: 1714261485751164928</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by Victor-Nyagudi** [comment] 2023-10-17 14:32
[We were told not to use "Save the World" workspace rooms](https://expensify.slack.com/archives/C01GTK53T8Q/p1697459012372029) for any testing since the Teachers Unite campaign is launching today, so how do we go about triaging this issue?

Are we at least allowed to sign up? I feel like that wouldn't accurately portray the actual teachers in the workspace. 

Please advise.

**Comment by trjExpensify** [comment] 2023-10-17 14:59
Maybe as a first step @youssef-lr or @marcochavezf can take a look. This wasn't happening yesterday in mine and @JmillsExpensify's testing, so it would be a real recent regression if so.

**Comment by marcochavezf** [comment] 2023-10-17 23:16
At the moment I haven't been able to reproduce it locally. In the video I noticed in the console log that we're throwing the error `Onyx.set() called after Onyx.merge()`. I monitored the push event logs and seems we're not instructing to call `Onyx.set()` from the `AddSchoolPrincipal` command, which leads to me think that probably there's some kind of race condition in this scenario.

**Comment by marcochavezf** [comment] 2023-10-17 23:20
Additionally, I was thinking that if we allow external contributors to access only the test policy by updating it on the client-side (in the backend we could check if it's a testing policy, we switch to it). So we can have more 👀 to figure out what's happening here. Thoughts? @trjExpensify @youssef-lr

**Comment by trjExpensify** [comment] 2023-10-18 21:10
How does that work in practice? We also don't really want the volunteer@expensify.org account being clogged up with tests.

**Comment by NicMendonca** [comment] 2023-10-20 19:50
@marcochavezf bump ^^

**Comment by marcochavezf** [comment] 2023-10-21 00:11
Yeah, that's true. Instead of using the volunteer@expensify.org we use an expensifail account with a testing control policy. 

The idea would be that in App we switch the public room ID and policyID when the env is dev or staging (Applause could also use it for testing). In the backend we can check if the request contains the testing IDs, if so we switch them there too.

**Comment by trjExpensify** [comment] 2023-10-23 14:51
I don't think staging should be different to production should it? That seems weird to me.

**Comment by marcochavezf** [comment] 2023-10-25 17:13
Ah I mean the staging NewDot app, similar to what we do [here](https://github.com/Expensify/App/blob/1c051fe49a9e4423053c1953c36dacd3ee81c8c0/src/pages/settings/Preferences/PreferencesPage.js#L81-L86) for the test menu in non-production apps, but we switch the IDs for the TU flows

**Comment by marcochavezf** [comment] 2023-10-27 21:31
No update

**Comment by marcochavezf** [comment] 2023-10-30 19:19
Coming from [here](https://github.com/Expensify/Expensify/issues/315545), we should create a test policy that we switch on staging and using another account different from volunteer@expensify.org

**Comment by mvtglobally** [comment] 2023-11-02 03:28
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2023-11-02 18:58
No update, but I will implement soon the switch policyID and reportID for QA and external testing.

**Comment by marcochavezf** [comment] 2023-11-06 20:20
No update

**Comment by marcochavezf** [comment] 2023-11-13 20:28
No update, PR to flip IDs for testing is still in review

**Comment by marcochavezf** [comment] 2023-11-15 20:18
Moving this to weekly, the PR to flip constants is not ready to be merged yet

**Comment by mvtglobally** [comment] 2023-11-18 04:30
Issue not reproducible during KI retests. (Second week)

**Comment by marcochavezf** [comment] 2023-11-27 14:52
No update

**Comment by marcochavezf** [comment] 2023-12-06 01:54
No update, focused on wave7

**Comment by marcochavezf** [comment] 2023-12-14 19:52
Issue not reproducible, also I was wondering if it was caused by slow API calls which have been improved.

**Comment by NicMendonca** [comment] 2023-12-15 22:18
@marcochavezf does that mean we should close this out?

**Comment by marcochavezf** [comment] 2023-12-21 03:09
Yup, we can close this one and reopen it if the issue occurs again

**Closed** 2023-12-21 03:10 UTC
Labels: Engineering, Weekly, Internal, Bug
