### ISSUE TITLE
Chat - Back button brings to LHN while in loading state

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20755] opened 2023-06-14 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/20344

## Action Performed:
Prerequisites: throttle the internet connection
1. Log in
2. Open any chat
3. Verify that styling of top header is unchanged and back button works as before (it do nothing)

## Expected Result:
Back button should do nothing while loading

## Actual Result:
Back button brings back to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4e008da4-96c5-4b37-b2f2-986db8c981f9

https://github.com/Expensify/App/assets/93399543/1d74de7e-48e4-4794-8cb5-bf0822fd3151

https://github.com/Expensify/App/assets/93399543/404211e1-9d35-4a24-92d4-43bc5af991c3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2023-06-14 20:21
Reviewing

**Comment by greg-schroeder** [comment] 2023-06-14 21:17
@kbecciv Hmm - Is that true that pressing the back button is supposed to do nothing? I swear I've seen other issues where pressing the back button while offline is supposed to move you back a step, so I'm not sure on this one. 🤔

Can you offer more context on the expected behavior here? Perhaps there's a previous issue or something that shows the back button doing nothing as what we intended? Thanks!

**Comment by kbecciv** [comment] 2023-06-15 16:21
@greg-schroeder Sorry for confusion, I have not been able to throttle this enough to get the loading state in the header.

**Comment by greg-schroeder** [comment] 2023-06-19 17:53
I don't think I understand - @kbecciv - are you saying that what you showed in the video is not the behavior you're talking about? I'm just having a ton of trouble understanding what is wrong here.

**Comment by greg-schroeder** [comment] 2023-06-21 20:26
Bump @kbecciv - can you clarify your last comment?

**Comment by greg-schroeder** [comment] 2023-06-26 18:22
Closing per team discussion

**Closed by greg-schroeder** 2023-06-26 18:22 UTC
Labels: Daily, Overdue, Bug
