### ISSUE TITLE
[$500] Thread shows up as "Chat Report" in LHN

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35957] opened 2024-02-06 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707241155686709

## Action Performed:
1. Go to a room on a workspace in account A
2. Initiate a message
3. in the thread tag account B
## Expected Result:
Thread title should show up in my LHN
## Actual Result:
Chat Report shows up as the thread title in my LHN
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-02-06 at 12 38 00@2x](https://github.com/Expensify/App/assets/38435837/f3e83570-28d3-40a5-bbe8-c2952e4b1525)

https://github.com/Expensify/App/assets/38435837/7401794b-19a8-4d83-8f98-c3520d65fef7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae85a8837bff1a48</li>
        <li>Upwork Job ID: 1754974220975108096</li>
        <li>Last Price Increase: 2024-02-06</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-02-07 00:08
Since I could not reproduce this, is it still reproducible to anyone else?
Thank you.

**Comment by Tony-MK** [comment] 2024-02-07 01:08
# Notes

I think the pusher did not include `parentReportActionID` in the report.
Hence, it could not be classified as a thread but as a Policy Chat Room.

This is because the `isChatThread` function needs `parentActionID` and `parentReportActionID` to return true.

![Debugger](https://github.com/Expensify/App/assets/22982173/69ea91ee-d53c-44eb-94cf-c3cf06b01d0e)

#
Notice after opening the thread, `parentReportActionID` gets merged. 

Then, the report is recognized as a thread.

![Onyx](https://github.com/Expensify/App/assets/22982173/1ddd9188-6e7d-4edb-b477-00700172506e)

Therefore, I believe the most reasonable solution is to inspect the pusher and `parentReportActionID` alongside `parentActionID`.

**Comment by rushatgabhane** [comment] 2024-02-07 03:14
🎀 👀 🎀 possible internal issue

**Comment by aldo-expensify** [comment] 2024-02-12 19:06
Investigating today...

**Comment by aldo-expensify** [comment] 2024-02-13 03:22
I'm not sure if I'm getting this issue correctly, but this is what is see:

<img width="1724" alt="image" src="https://github.com/Expensify/App/assets/87341702/661e1847-44c9-4036-995c-3210e42a9691">

The user that was mentioned and invited into the room see the "whisper" as the LHN, but this whisper is not really for them so when they open the chat, it is not visible and shouldn't have been used as the "last message" in the LHN

Is this correct? or is there something else that is wrong?

**Comment by aldo-expensify** [comment] 2024-02-13 03:23
The reproduction steps seem to be incomplete. For which user does the thread show up as "Chat Report"? that didn't happen to any user in my test.

**Comment by aldo-expensify** [comment] 2024-02-13 03:30
From further testing it seems like the right steps are:

1. Create two accounts `accountA` and `accountB`
2. Login with both accounts in different sessions
3. With `accountA` create a workspace and a room
4. Send a message in the room and create a thread
6. In the thread send a message mentioning the `accountB`, something like `Hello @xxx@otheruser.com`
7. Click "Invite them"
    <img width="333" alt="image" src="https://github.com/Expensify/App/assets/87341702/a1cf3115-12cf-4c6e-8842-f2e99589efc7">
8. See that the chat will show up in `accountB`'s LHN as "Chat Report"
    <img width="333" alt="image" src="https://github.com/Expensify/App/assets/87341702/c77a4af1-fdae-43f7-b8da-931645d45c64">

The command that is probably pushing an incomplete event to the invited user is `ResolveActionableMentionWhisper`. Will continue investigating that tomorrow.

The last message being incorrect in the LHN reported [here](https://github.com/Expensify/App/issues/35957#issuecomment-1940362159) seems to be an unrelated bug.

**Comment by aldo-expensify** [comment] 2024-02-14 00:10
PR up https://github.com/Expensify/Auth/pull/9933

@Tony-MK 's assessment [here](https://github.com/Expensify/App/issues/35957#issuecomment-1931062545) was on point, the `parentReportActionID` was missing in some backend code producing the report structure for onyx.

**Comment by aldo-expensify** [comment] 2024-02-16 00:49
PR https://github.com/Expensify/Auth/pull/9933 deployed

**Comment by aldo-expensify** [comment] 2024-02-16 00:57
Tested well


https://github.com/Expensify/App/assets/87341702/62eab647-17fb-4259-975c-37ef5cb9b983

**Closed by aldo-expensify** 2024-02-16 00:57 UTC
Labels: Reviewing, Daily, Internal, Bug
