### ISSUE TITLE
Settings - Pressing the back button on the "Keyboard Shortcuts" page leads to a blank screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35703] opened 2024-02-02 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** shussain@applausemail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go the the Account settings > About > View keyboard shortcuts
2. Press back button

## Expected Result:
Keyboard shortcuts modal should be closed and blank screen should not be displayed

## Actual Result:
Pressing the back button on the "Keyboard Shortcuts" page leads to a blank screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/94870091-de7c-4b60-bc12-787297432537

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by johnmlee101** [comment] 2024-02-02 19:22
Able to reproduce

**Comment by shubham1206agra** [comment] 2024-02-02 19:29
@hayata-suenaga This looks like related to goBack problems with Ideal Nav. Can you check this too?

**Comment by hayata-suenaga** [comment] 2024-02-02 19:53
Closing this issue to combine it with [the existing issue](https://github.com/orgs/Expensify/projects/94/views/2?pane=issue&itemId=51976513).

**Closed by hayata-suenaga** 2024-02-02 19:53 UTC
Labels: DeployBlockerCash, Engineering, Hourly
