### ISSUE TITLE
[HOLD for payment 2024-12-25] [$250] Room-On inviting a phone contact via suggestions in room chat, expensify.sms shown in details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#53003] opened 2024-11-23 13:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9. 0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause  - Internal Team

## Action Performed:
1. Launch app
2. Open a room chat
3. Invite a phone number via suggestion eg: +919789945670
4. Send the message
5. From whisper, tap invite
6. Tap header -- member
7. Open the phone number member
8. Note expensify.sms is shown with phone number
9. Navigate to room conversation
10. Tap on highlighted invited member
11. Tap header -- member - phone number contact
12. Now note expensify.sms is not shown

## Expected Result:
Expensify.sms must not be shown with phone number in details page when inviting a phone contact via suggestions in room chat

## Actual Result:
Expensify.sms is shown with phone number in details page when inviting a phone contact via suggestions in room chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/e2360e07-08ee-49cd-813d-eaa7078cf2d3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861102829467266920</li>
        <li>Upwork Job ID: 1861102829467266920</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>Kalydosos | Contributor | 105507469</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by Kalydosos** [comment] 2024-11-24 11:15
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
On inviting a phone contact via suggestions in room chat, expensify.sms shown in details

What is the root cause of that problem?
the display name was not retrieved with the usual considerations including removing any sms domain and formatting the phone number

 const displayName = details.displayName ?? ''; 
### What changes do you think we should make in order to solve the problem?
we should change the following code from

https://github.com/Expensify/App/blob/93c573b1baeadd54460fcb4492b4aa2e280f844d/src/pages/RoomMemberDetailsPage.tsx#L50

into 

> const displayName = formatPhoneNumber(PersonalDetailsUtils.getDisplayNameOrDefault(details));

### RESULT
it works fine
![result](https://github.com/user-attachments/assets/2fe67d67-5437-41c4-82ab-aa86c7de3800)


### What alternative solutions did you explore? (Optional)

None

**Comment by klajdipaja** [comment] 2024-11-26 11:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When inviting a memeber to a room the displaed name shows the full phone number including exepnsify.sms.

### What is the root cause of that problem?
When we invite a user by phone number both `displayName` and `login` information of the user are set to the full phone number. 
Part of the problem is the backend here.
The response of `InviteToRoom` endpoint returns the onxy merge changes for `personalDetails` which contain the details of all accounts and for a non existing user on Expensify it returns both displayName and login as the full name.

![image](https://github.com/user-attachments/assets/792d8833-7aa1-4d2b-affe-f61375d181b8)

If we click on the invited user on the message we then get the correct information from the BE and`personalDetails` key is updated with the formatted `displayName` which does not include the sms domain.

In the frontend we rely only on the `displayName` that the backend returns here:
https://github.com/Expensify/App/blob/93c573b1baeadd54460fcb4492b4aa2e280f844d/src/pages/RoomMemberDetailsPage.tsx#L50

### What changes do you think we should make in order to solve the problem?

We can add a front end fix to format the displayName if it is an sms login by changing the line where we read the displayName into this:




### What alternative solutions did you explore? (Optional)

**Comment by klajdipaja** [comment] 2024-11-26 11:54
Updated proposal https://github.com/Expensify/App/issues/53003#issuecomment-2500478874 due to premature click on the submit button and also added another option while I was at it :D

**Comment by Kalydosos** [comment] 2024-11-26 12:23
@klajdipaja the test is already done in 
https://github.com/Expensify/App/blob/c7c76907f1f948a9be47df34452c292bdb323b71/src/libs/LocalePhoneNumber.ts#L25-L28

formatPhoneNumber will not format the text if it is not a phone number

**Comment by klajdipaja** [comment] 2024-11-26 12:50
@Kalydosos yes I am aware of that. IMO making that explicit check adds valuable information for the developer reading that  line. We are formatting the displayName as a phone number because we expect it that sometimes it can be a phone number.

I also don't like that the `formatPhoneNumber` just returns the text if it's not a number, it doesn't sound like something a  formatter should do.

**Comment by klajdipaja** [comment] 2024-11-26 13:45
Proposal updated https://github.com/Expensify/App/issues/53003#issuecomment-2500478874. Added `Option 2` to handle the issue on a broader scope

**Comment by Kalydosos** [comment] 2024-11-26 15:59
@jayeshmangwani can you give a look at our proposals ?

**Comment by jayeshmangwani** [comment] 2024-11-27 07:05
> Added Option 2 to handle the issue on a broader scope

@klajdipaja Then your proposal will be the same as this one https://github.com/Expensify/App/issues/53003#issuecomment-2495487069, right?

**Comment by jayeshmangwani** [comment] 2024-11-27 07:08
@Kalydosos What difference will it make if we use `formatPhoneNumber` for `PersonalDetailsUtils.getDisplayNameOrDefault(details)`?

We can simply use `PersonalDetailsUtils.getDisplayNameOrDefault(details)` alone, and it will still work correctly. So, what is the purpose of using `formatPhoneNumber` here?

**Comment by klajdipaja** [comment] 2024-11-27 07:57
> > Added Option 2 to handle the issue on a broader scope
> 
> @klajdipaja Then your proposal will be the same as this one [#53003 (comment)](https://github.com/Expensify/App/issues/53003#issuecomment-2495487069), right?

@jayeshmangwani No it's very different.
That proposal is suggesting using `PersonalDetailsUtils.getDisplayNameOrDefault(details)` to get the display name in the desired format but that is wrong.
Assume I have this phone number as my login method: `+355678899777`. The `userDetails.login` for this would be: `+355678899777@expensify.sms`.
If you have `const displayName=PersonalDetailsUtils.getDisplayNameOrDefault(details)` the display name would be `+355678899777` and that's not what we want.
Both my first option and the proposal from @Kalydosos use the `formatPhoneNumber` after we get the display name to format the number in the desired display format (which is for my example: 067 889 9777).
My Option 2. takes that a step further because as you just did in your thinking we assume that `PersonalDetailsUtils.getDisplayNameOrDefault(details)` will return a display name that can be used just like that to be displayed; apparantely it does not do what we think it does. We should change the internals of that fucntion so that if the displayName is a phone number we format it in there instead of moving that responsibility to whoever calls the function.

**Comment by Kalydosos** [comment] 2024-11-27 09:52
> @Kalydosos What difference will it make if we use `formatPhoneNumber` for `PersonalDetailsUtils.getDisplayNameOrDefault(details)`?
> 
> We can simply use `PersonalDetailsUtils.getDisplayNameOrDefault(details)` alone, and it will still work correctly. So, what is the purpose of using `formatPhoneNumber` here?

@jayeshmangwani using formatPhoneNumber is absolutely necessary because that's the only way to display the phone number in a local and user-friendly format and **to maintain consistency with all the other screens** as you can see in the images and videos below

### it is used in the room page to reformat the invite phone number

https://github.com/user-attachments/assets/38ce9763-a78b-42a4-9c48-d17e56b9be0e

### it is used in the room members list screen and when not used in the member detail page the display is inconsistent

https://github.com/user-attachments/assets/00dfe7b0-ea07-45af-ba96-99687dbea6fd

### just  like in the issue demo video
![Capture d’écran de 2024-11-27 10-10-26](https://github.com/user-attachments/assets/69286161-83d9-4492-9f94-3fdeaac50537)
![Capture d’écran de 2024-11-27 10-13-47](https://github.com/user-attachments/assets/df842d0b-08c8-4dd0-b078-25b1a5a5bed4)
![Capture d’écran de 2024-11-27 10-08-33](https://github.com/user-attachments/assets/96a2922e-e2ea-4d1f-bc7d-91479650fff1)

so its usage is absolutely necessary. It is used in the members list screen here also (as you have pointed out indeed)
https://github.com/Expensify/App/blob/f810ac6d4eb6ad0f70cae37738d1e23d5b0a1585/src/pages/RoomMembersPage.tsx#L237

**Comment by klajdipaja** [comment] 2024-11-27 10:13
@jayeshmangwani I completely agree that we need to format the phone number and that @Kalydosos proposal is good for that.

What I would like to point out is that the RCA for this issue manifests in bugs in many places and we need to look at this specific bug in a more holistic approach. 
We either need to replace `formatPhoneNumber(PersonalDetailsUtils.getDisplayNameOrDefault(details))` in all places where we don't take into account that `getDisplayNameOrDefault` results in a un-displayable phone number or we fix the internals of the `getDisplayNameOrDefault` function so that it does what the name of the functions says (Option 2 of my proposal)
Attached you can see two cases where we have almost the same issue as here by showing the improperly formatted phone number which then changes if you visit the profile of the new user.

Recoding 1. Invited a new user to the transaction thread. Notice how the phone number when you have contains the country code and once you visit the profile it does not anymore:


https://github.com/user-attachments/assets/c0a06582-cd08-458c-b611-fb06c9becf72

Recording 2. Submit expense to a new user by phone number. Once the report is created notice all the displayed names include the country code as well and when you visit the profile everything changes.

https://github.com/user-attachments/assets/9267730c-6d56-47df-8cce-f84d353ed125

**Comment by Kalydosos** [comment] 2024-11-27 10:42
@jayeshmangwani in the very specific case, dealing with phone number and for the very screens involved we need to format the phone number and maintain consistency with the same contextual screens. Maybe there are some other screens elsewhere needing that formatting but we should not adress all these issues here in this ticket. It may seems simple to adress them but the reality is that each screen has its context and purpose and reformatting can be or not relevant depending on that context **but in this very case, reformatting is more than necessary to maintain consistency** imho

**Comment by jayeshmangwani** [comment] 2024-11-27 16:22
Thank you all for your respective proposals: @abzokhattab , @Kalydosos  and @klajdipaja 

> adding the formatPhoneNumber  is more of an implmentation detail as the main issue was that the expensify.sms is shown in the title not the format... thus i think this is more of an implementation details ...

@abzokhattab  your point is definitely valid that this can be handled in the PR, and we would catch inconsistencies there.
However, what I personally think is that we should go with @Kalydosos proposal in this specific case, as the change is very small regarding how we should display the username (fallback name). Additionally, they are suggesting applying the same logic to the Member Details page as we do on the Members page. The rest, I can leave to the internal engineer if you feel otherwise.

**Comment by jayeshmangwani** [comment] 2024-11-27 16:26
I agree with @Kalydosos's [Proposal](https://github.com/Expensify/App/issues/53003#issuecomment-2495946266). We can use `formatPhoneNumber(PersonalDetailsUtils.getDisplayNameOrDefault())` for the `displayName` value.

Also, there are a few pages where we are using `PersonalDetailsUtils.getDisplayNameOrDefault()` only as the `displayName`. We would need to fix those inconsistencies as part of this issue.

🎀 👀 🎀 C+ reviewed

**Comment by Kalydosos** [comment] 2024-11-27 17:45
@jayeshmangwani i think it will be difficult to resolve the other non use of formatPhoneNumber here in this ticket as we need to measure any unexpected impact that could have on the context and the purpose of these pages/screens. And already juding by the glimpse on the refactoring in this image https://github.com/Expensify/App/issues/53003#issuecomment-2503519015 i can tell it can be simple or not as we should do an impact check for each screen? I advise us to just stick to what is known as broken (the issue in this ticket) as we can have unexpected impact while conforming other screens imho. My PR is ready for this issue if we go in my advised direction otherwise the tefactoring of the whole screens can take some considerable time and this fix could take also some time to be delivered in production

**Comment by jayeshmangwani** [comment] 2024-11-27 17:51
@Kalydosos I don’t think it will take a lot of time. We can handle those in issue only, as I believe it’s just a UI confirmation, and we can address it on a case-by-case basis. @luacmartins , what do you think?

**Comment by luacmartins** [comment] 2024-11-27 18:08
>@Kalydosos I don’t think it will take a lot of time. We can handle those in issue only, as I believe it’s just a UI confirmation, and we can address it on a case-by-case basis. @luacmartins , what do you think?

I agree

**Comment by Kalydosos** [comment] 2024-11-27 18:12
@jayeshmangwani @luacmartins ok for me then as we all agreed :+1:

**Comment by jayeshmangwani** [comment] 2024-11-27 18:32
> the new format shown https://github.com/Expensify/App/issues/53003#issuecomment-2495946266 hides the country code in most cases, so why do you think that is correct? as a user i would be confused 🤔

This will hide the country code if it's in the same region only

**Comment by Kalydosos** [comment] 2024-12-24 09:11
I formally applied on upwork a few days ago, i dont know if that could help BZ in the payment process

**Comment by jayeshmangwani** [comment] 2024-12-24 09:25
> I formally applied on upwork a few days ago, i dont know if that could help BZ in the payment process

Yes, that would be helpful for BZ. @garrettmknight Issue is closed, though payment is still pending. I’m completing the checklist today.

**Comment by Kalydosos** [comment] 2024-12-24 09:53
Ok, thx @jayeshmangwani

**Comment by jayeshmangwani** [comment] 2024-12-24 10:52
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/47201#discussion_r1896646607

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Open the app and go to a room chat.
2. Invite a phone number via suggestion, e.g., +919789945670.
3. Send the message.
4. From Whisper, tap Invite.
5. Tap the header — Member.
6. Open the phone number member.
7. Verify that `expensify.sms` is not shown with the phone number.

Do we agree 👍 or 👎

**Comment by Kalydosos** [comment] 2024-12-26 09:37
no update on the payment. Is it because the ticket is closed ?

**Comment by jayeshmangwani** [comment] 2024-12-26 09:40
No, but it seems that due to the holiday season, Garrett is OOO until December 30.

**Comment by Kalydosos** [comment] 2024-12-26 09:44
Ok i see, thx for the info @jayeshmangwani :+1:

**Comment by Kalydosos** [comment] 2024-12-30 09:29
@garrettmknight please let me know if there is anything i must do for the payment process, thx

**Comment by luacmartins** [comment] 2024-12-30 15:59
I'm not sure why the merge commit closed this issue, but we're still missing payment here.

**Comment by garrettmknight** [comment] 2024-12-30 17:18
Payment summary:

**Comment by garrettmknight** [comment] 2024-12-30 17:19
Payment Summary:
- Contributor: @Kalydosos $250 via Upwork - offer is out
- Reviewer: @jayeshmangwani $250 via NewDot

**Comment by Kalydosos** [comment] 2024-12-30 17:24
@garrettmknight offer accepted, thanks a lot :+1:

**Comment by Kalydosos** [comment] 2024-12-31 12:27
@garrettmknight do you need anything from me to finalize the process on upwork ? please let me know, thx

**Comment by garrettmknight** [comment] 2024-12-31 15:26
Nope! Just needed you to accept the offer. All paid up - @jayeshmangwani please request in ND when you're ready.

**Closed** 2024-12-31 15:27 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2025-01-01 13:35
Confirming payment summary:

- Contributor: @Kalydosos $250 via Upwork
- Reviewer: @jayeshmangwani $250 via New Expensify

**Comment by garrettmknight** [comment] 2025-01-07 18:34
$250 approved for @jayeshmangwani
