### ISSUE TITLE
mWeb - Room description - When saving specific room description different error shown in stg&pro

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43925] opened 2024-06-18 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4645733
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap header --- room description
4. Paste the @×÷==//^^^&*(/_>[//<[[&^+&*6>[_[_&^*()/*₹*₹*^8÷_€\€|€●■{€|♡ 65€●6
5. Tap save

## Expected Result:
Same error must be shown in staging and production

## Actual Result:
When saving specific room description different error shown in staging and production 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6517312_1718720478838!Screenshot_20240618-193749_Chrome](https://github.com/Expensify/App/assets/78819774/2965bd15-91a9-45cc-bca9-52b536e20e3d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-18 15:53
Production:

![193800_Chrome](https://github.com/Expensify/App/assets/78819774/c62b9cab-d44b-4b6a-9dba-e52e575a34af)

**Comment by lanitochka17** [comment] 2024-06-18 15:54
@bondydaa  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bondydaa** [comment] 2024-06-18 16:03
that text comes from here https://github.com/Expensify/App/blob/main/src/components/Form/FormProvider.tsx#L146 but hasn't changed for ~6 months so something else seems to have changed.

**Comment by bondydaa** [comment] 2024-06-18 16:08
hmm possibly this PR https://github.com/Expensify/App/pull/42970/files?diff=split&w=1#diff-16b60eed4ca05874fc3fadcb18fc790efcb94648af3991004dfa67c7e7f39923

cc @francoisl @fedirjh @nkdengineer

**Comment by bondydaa** [comment] 2024-06-18 16:10
trying to revert this commit locally to confirm https://github.com/Expensify/App/commit/0c4cabc755963e8ccae139198d6f7e9e830d6248

**Comment by nkdengineer** [comment] 2024-06-18 16:23
This is my regression. I'll raise a PR to fix it soon @fedirjh

**Comment by bondydaa** [comment] 2024-06-18 16:25
🙇 thank you @nkdengineer, i tried the proposal but get a crash so seems like we need to import `translate` but i'm not sure which library that is stored in

<img width="2189" alt="image" src="https://github.com/Expensify/App/assets/4073354/bdb38345-ca6a-48c0-b5da-82d1b6925aad">

**Comment by bondydaa** [comment] 2024-06-18 16:27
@jainilparikh no normally with regressions that are introduce we have the PR author fix them, there are cases where we might assign it out to another contributor depending on the urgency and severity but this one seems fine for @nkdengineer to handle.

**Comment by nkdengineer** [comment] 2024-06-18 16:54
@bondydaa  @fedirjh this [PR](https://github.com/Expensify/App/pull/43933) is ready for preview.
<img width="474" alt="Screenshot 2024-06-18 at 23 39 12" src="https://github.com/Expensify/App/assets/161821005/a556555c-cfe8-4875-81ba-b53cc516e2ef">

**Comment by bondydaa** [comment] 2024-06-18 22:11
tested on staging and looking good 🎉 
<img width="2183" alt="image" src="https://github.com/Expensify/App/assets/4073354/4847ce84-5f29-4cdd-8123-4ebbdc46eed6">

removing blocker

**Comment by bondydaa** [comment] 2024-06-18 22:22
I think we can close this out since it was just a regression from https://github.com/Expensify/App/pull/42970, let me know if that's wrong @nkdengineer or @fedirjh

**Closed by bondydaa** 2024-06-18 22:22 UTC
Labels: Reviewing, Engineering, Weekly
