### ISSUE TITLE
[$500] Web - Private notes - Note is missing in group member profile unless the profile is opened in 1:1 DM

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27993] opened 2023-09-22 08:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com.
2. Create a group chat with users you have not previously sent a DM 
3. Click on the group chat header.
4. Click a user you have previously sent a DM to.
5. Observe the option to Message AND add private notes. 
6. Click a user you have not previously sent a DM to.
7. Observe you only have the option to message them. 
8. Click Message <username>.
9. Click on the chat header.
10. Note that the private note section is there.

## Expected Result:
In Step 4, Private notes section is present in group member details view.

## Actual Result:
In Step 4, Private notes section is not present in group member details view. The section only appears after the user profile is opened in 1:1 DM in Step 7.

## Workaround:
1. Send a message to the user
2. Refresh the group

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-9

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/528592ad-7e58-4558-9f4c-e3feedbb6f79

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010164e33b1c83b912</li>
        <li>Upwork Job ID: 1706923253731889152</li>
        <li>Last Price Increase: 2023-10-04</li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-23 11:39
Lookig at the code, this seems intentional.

**Comment by peterdbarkerUK** [comment] 2023-09-25 14:58
I don't seem able to reproduce this, with private member notes appearing @izarutskaya could you look at [this recording](https://app.screencast.com/5fNdonuf5JbSv) and tell me where I'm going wrong?

**Comment by izarutskaya** [comment] 2023-09-26 19:25
Hi @peterdbarkerUK Try please a new account and create a group of members who don't have individual chats.

**Comment by peterdbarkerUK** [comment] 2023-09-27 06:46
Ah yes, it only applies when you don't have any prior DMs with the user. Sounds like the private note function is dependent on a previously created chat report.

**Comment by cubuspl42** [comment] 2023-10-03 10:02
@izarutskaya @peterdbarkerUK 

I think we need some clarification.

Quoting the "Action Performed":

> Create a group chat with users you have not previously sent a DM to, and some you have

In [the video](https://user-images.githubusercontent.com/115492554/269875541-528592ad-7e58-4558-9f4c-e3feedbb6f79.mp4), who is who? Is "Joann..." a user "you have not previously sent a DM to" and "12" is a user "you have [previously sent a DM to]", or the other way around?

**Comment by peterdbarkerUK** [comment] 2023-10-05 11:55
@cubuspl42 I believe in the video both accounts have not previously received a DM. I updated the steps to clarify it only occurs with users you have not previously DM'd, but didn't update the video as the error remains the same.

**Comment by cubuspl42** [comment] 2023-10-05 12:10
But in such a case, this is an intended behavior. The original instruction seems to be "right", it might be taken from some regression test instructions or something like that. It just wasn't followed in full.

**Comment by peterdbarkerUK** [comment] 2023-10-06 09:51
Fair enough - I agree this seems to be happening intentionally, but am not sure if it is in fact our intention haha. [Raised it in slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696585859495479) to discuss if this is intended!

**Comment by peterdbarkerUK** [comment] 2023-10-09 12:40
[Alrighty, closing as something predominantly internal](https://expensify.slack.com/archives/C01GTK53T8Q/p1696591858895699?thread_ts=1696585859.495479&cid=C01GTK53T8Q) - thanks for working with me on @cubuspl42

**Closed by peterdbarkerUK** 2023-10-09 12:40 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
