### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Expense - Payment buttons show different amount for report consisting of submitted & tracked expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44158] opened 2024-06-21 13:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense ($200).
4. Track an expense ($100).
5. Look at the amount on the payment button in expense preview in the main chat and expense report.

## Expected Result:
The amount on the payment button in expense preview in the main chat and expense report should be the same.

## Actual Result:
The amount on the payment button in expense preview in the main chat and expense report are different.
Main chat shows $300.
Expense report shows $200.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/50becb2b-f284-497a-90b5-83c49016b21d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019e4af48063736ac0</li>
        <li>Upwork Job ID: 1805264313238989971</li>
        <li>Last Price Increase: 2024-06-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by m-natarajan** [comment] 2024-06-21 13:08
@slafortune FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-21 13:08
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-21 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount in report preview button and in expense report button is different.

### What is the root cause of that problem?
In report preview, we always use the total amount of the expense.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/components/ReportActionItem/ReportPreview.tsx#L205-L208

In expense report header, we use the `reimbursableSpend` for the amount.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/components/MoneyReportHeader.tsx#L123

The expense report header also have more condition to show the amount, for example, if there is an held expense, then we only show the non-hold amount.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/components/MoneyReportHeader.tsx#L125

But if every expense are held, then we don't show the amount.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/components/MoneyReportHeader.tsx#L242

### What changes do you think we should make in order to solve the problem?

To make it consistent, we can follow the condition/logic from the expense report header. We will create a new function called `getSettlementAmount` which will use the `reimbursableSpend` as the amount and take the other condition from the expense report header.

```
const getSettlementAmount = () => {
    if all is on hold: return empty
    if has held expense and allow settlement: return non held amount
    
    return CurrencyUtils.convertToDisplayString(reimbursableSpend, iouReport?.currency);
}
```

**Comment by dangrous** [comment] 2024-06-28 09:36
whattt I thought I posted a comment here yesterday. Well, it said basically:

This proposal makes sense! But, I want to confirm internally to make sure there's not a specific reason that these DON'T currently match (like, from an accounting or other perspective). I've asked in Slack and should hear back soon! (internal link: https://expensify.slack.com/archives/C03U7DCU4/p1719527792898199)

**Comment by dangrous** [comment] 2024-07-01 10:04
reasked, that was a bad time to do it I think. Hopefully will have an answer soon! If I hear nothing, I think we can move forward because to me it seems to make sense that they should match.

**Comment by dangrous** [comment] 2024-07-01 10:05
rude, melvin.

**Comment by dangrous** [comment] 2024-07-02 10:34
Okay after discussing internally, we're closing this out as expected behavior - thanks so much for the proposal and review @thesahindia and @bernhardoj

Basically the thought is the preview shows all charges, the pay button only shows what you can actually pay currently, and so both serve different purposes.

**Comment by bernhardoj** [comment] 2024-07-02 10:38
> Basically the thought is the preview shows all charges, the pay button only shows what you can actually pay currently, and so both serve different purposes.

Hmm, based on this, it means we need to update the report preview pay button amount, right?
<img width="214" alt="Screenshot 2024-07-02 at 18 37 00" src="https://github.com/Expensify/App/assets/50919443/8ac20b1f-d97c-4413-b9b6-813f78fe0487">

**Comment by dangrous** [comment] 2024-07-03 13:49
Oh okay yep! I misinterpreted what the issue was. I think you are right @bernhardoj, thanks for bumping. I'm confirming again to make sure I'm not re-misunderstanding haha, but will reopen for now.

**Comment by dangrous** [comment] 2024-07-04 11:51
I haven't heard back but I think we should be consistent across locations. I'm going to assign you @bernhardoj and lets just change the pay button specifically.

**Comment by dangrous** [comment] 2024-07-23 19:38
not overdue, payment tomorrow.

**Comment by bernhardoj** [comment] 2024-07-24 15:08
Requested in ND.

**Comment by slafortune** [comment] 2024-07-24 19:21
@bernhardoj can you please complete the checklist?

**Comment by bernhardoj** [comment] 2024-07-25 02:42
@slafortune @thesahindia is the C+ here.

**Comment by slafortune** [comment] 2024-07-25 19:02
Ah yes - sorry about that!

@thesahindia can you please complete the checklist?

**Comment by slafortune** [comment] 2024-07-25 19:03
@bernhardoj  role Contributor - owed $250 via NewDot
@thesahindia role C+ - owed $250 via NewDot

**Comment by JmillsExpensify** [comment] 2024-07-26 00:39
$250 approved for @bernhardoj

**Comment by slafortune** [comment] 2024-07-30 19:19
cc - @JmillsExpensify 
@thesahindia role C+ - owed $250 via NewDot

**Closed by slafortune** 2024-07-30 19:19 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-20 17:28
$250 approved for @thesahindia
