### ISSUE TITLE
iOS - IOU - Save button and offline message in Edit Amount page overlaps with navigation bar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30840] opened 2023-11-03 12:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Tap + > Request money.
3. Create a manual request.
4. Open the IOU details view.
5. Tap Amount.
6. Return to IOU details view.
7. Go offline.
8. Tap Amount.

## Expected Result:
In Step 5, the Save button will not overlap with the white navigation bar.
In Step 8, offline message will not overlap with the white navigation bar.

## Actual Result:
In Step 5, the Save button overlaps with the white navigation bar briefly.
In Step 8, the offline message overlaps with the white navigation bar.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/9b902992-d132-40d8-a8bb-44aabce3bc88

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-11-03 14:11
This looks like a regression of [this PR](https://github.com/Expensify/App/pull/30065)

This PR introduces the `shouldEnableMinHeight` and apply it to `EditRequestAmountPage` and `MoneyRequestSelectorPage`
https://github.com/Expensify/App/blob/839545e846e1d61e5b10107f2ccc4d779a6bd35e/src/pages/EditRequestAmountPage.js#L47
https://github.com/Expensify/App/blob/839545e846e1d61e5b10107f2ccc4d779a6bd35e/src/pages/iou/MoneyRequestSelectorPage.js#L98

So this issue happens in `MoneyRequestSelector` page as well(in offline mode)

In order to solve this issue, we need to `minHeight` considering the `paddingBottom` and `paddingTop`
1. Remove this line
https://github.com/Expensify/App/blob/399b65e7598365922e6447501f24672876cd12bd/src/components/ScreenWrapper/index.js#L49
2. Add the following code [here](https://github.com/Expensify/App/blob/399b65e7598365922e6447501f24672876cd12bd/src/components/ScreenWrapper/index.js#L118)
```
        let minHeight = shouldEnableMinHeight ? initialHeight - (paddingStyle.paddingBottom || 0) - (paddingStyle.paddingTop || 0) : undefined;
```

This works as expected.

**Comment by sarious** [comment] 2023-11-04 13:34
> cc @sarious, could you handle this regression?

Yes, sure, it seems I found the issue, but now I can't the check it on android/ios browser, because the flow of running the app has changed, because of certificates.

**Comment by s-alves10** [comment] 2023-11-04 13:38
@sarious 

What do you think is the root cause of the issue?

**Comment by sarious** [comment] 2023-11-04 16:51
> cc @sarious, could you handle this regression?

@fedirjh should I create a new Pull Request to fix this issue? or where is it better to describe the fix?

**Comment by sarious** [comment] 2023-11-04 17:49
> > should I create a new Pull Request to fix this issue?
> 
> @sarious Yes, you should create a new PR and include links to both this issue and the original issue.
> 
> Edit: Please be aware that any issues labeled as `DeployBlockerCash` need to be addressed promptly and resolved as soon as possible.

I understand that, so I've spent today the whole day to fix the issue. Of course, it took a lot of time to launch the application on different devices, due to the fact that the launch process changed, due to the addition of certificates. I still couldn't launch the app in Chrome on Android.

**Comment by sarious** [comment] 2023-11-04 20:48
@ishpaul777 so, I've created a Pull Request with the fix. So I would be very grateful if you can watch it on Android mWeb Chrome and record the video. I will keep trying to run this on my emulator

**Comment by sarious** [comment] 2023-11-04 21:27
@ishpaul777 I've done it by myself, but thank you for proposal.

**Comment by puneetlath** [comment] 2023-11-06 19:29
Ok I'm going to close this since the fix has been CP'd and there's no payment needed specifically for this issue. Thanks y'all!

**Closed by puneetlath** 2023-11-06 19:29 UTC
Labels: Reviewing, Engineering, Weekly
