### ISSUE TITLE
[$500] Workspace-Tapping "Home" does not trigger action & WSavatar changed into placeholder

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36005] opened 2024-02-07 10:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.37
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. From WS members page copy the URL eg: https://staging.new.expensify.com/workspace/21BDE2487391A8AE/members
3. Launch app as different user which has no connection with above mweb user account
4. Tap on a report
5. Paste the url https://staging.new.expensify.com/workspace/21BDE2487391A8AE/members
6. Send the message
7. Tap on the URL link
8. Note user directed to hhm not here page with "go back to homepage" link below
9. Tap on "Go back to homepage" link
10. Note, tapping on "Go back to homepage" does not trigger any action (home.mp4)
11. Tap back button and navigate back to LHN (home page) and note Workspace avatar changed to placeholder (031136.mp4)
12. Tap on a report
13. Paste WS deeplink anonymous URL eg: https://staging.new.expensify.com/workspace/77336CD9870F8DB1
14. Send the message
15. Tap on the link
16. Note user directed to Hhm, it's not here page with WS avatar changed into placeholder and shown on top left of the page(095732.mp4)

## Expected Result:
Tapping "Go to Home" must direct user to home page & WS avatar must not change into placeholder.

## Actual Result:
Tapping "Go to Home" does not trigger any action & WS avatar changed into placeholder.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/29fee1ad-474d-4909-9012-a2d3c9987983

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015d0cf638a772947b</li>
        <li>Upwork Job ID: 1755181874500005888</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-07 10:51
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-07 13:04
This should be fixed in https://github.com/Expensify/App/pull/35980

**Comment by DylanDylann** [comment] 2024-02-10 02:21
I think we should hold this issue until https://github.com/Expensify/App/pull/35980 is done

**Comment by DylanDylann** [comment] 2024-02-13 19:15
Hold https://github.com/Expensify/App/pull/35980

**Comment by DylanDylann** [comment] 2024-02-16 04:09
same above

**Comment by DylanDylann** [comment] 2024-02-19 11:06
same above

**Comment by johncschuster** [comment] 2024-02-26 21:45
Looks like the linked PR has just been deployed to staging. Will take this off [HOLD] once it's been deployed to prod.

**Comment by johncschuster** [comment] 2024-02-29 22:35
PR has been deployed to prod! Taking this off hold

**Comment by DylanDylann** [comment] 2024-03-01 07:07
It seems this issue is fixed. I can't reproduce anymore 

https://github.com/Expensify/App/assets/141406735/ba2e3dc9-98ea-40fb-9578-e1161e7cc8ce

@izarutskaya Could you help to verify?

**Comment by johncschuster** [comment] 2024-03-01 16:10
Applying the retest-weekly label to see if it is still reproducible.

**Comment by mvtglobally** [comment] 2024-03-05 06:02
Team is still checking. will update tomorrow

**Comment by johncschuster** [comment] 2024-03-05 22:22
Thanks, @mvtglobally! I'll wait on your update tomorrow 👍

**Comment by mvtglobally** [comment] 2024-03-05 22:54
Issue is reproducible during retest 


https://github.com/Expensify/App/assets/43995119/84f6b7e5-8451-43f3-ac88-17227d507afa

**Comment by johncschuster** [comment] 2024-03-06 16:02
Raised a request for proposals [in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1709740930223109)

**Comment by nkdengineer** [comment] 2024-03-11 10:37
@johncschuster The behavior in staging is that: Clicking on "Go back to Homepage" will open the workspace list, which is expected behavior in [PR](https://github.com/Expensify/App/pull/35980)

**Comment by johncschuster** [comment] 2024-03-13 21:14
@nkdengineer bump on my question above!

**Comment by johncschuster** [comment] 2024-03-18 22:13
@nkdengineer No worries! Just so we're clear, are you saying that you were able to reproduce the WS avatar changing _and_ the PR above fixes it, or are you saying you were not able to reproduce the WS avatar changing _at all_?

**Comment by johncschuster** [comment] 2024-03-22 17:41
@nkdengineer bump!

**Comment by johncschuster** [comment] 2024-03-25 20:42
@DylanDylann it looks like this issue has stalled out a bit. Are you able to prioritize this one?

**Comment by DylanDylann** [comment] 2024-03-26 09:41
@johncschuster I just tested again and can't reproduce this bug anymore. @mvtglobally If you still can reproduce, please help to update the steps and the expected in the OP

**Comment by johncschuster** [comment] 2024-04-01 22:16
Thanks for giving it a try, @DylanDylann. I'll put the `retest-weekly` label on so it gets slotted in this week.

**Comment by mvtglobally** [comment] 2024-04-12 05:30
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2024-04-12 21:02
Bumping for Melvin. Waiting on one more retest before closing the issue.

**Comment by johncschuster** [comment] 2024-04-24 22:08
I've asked for an additional retest in #qa.

**Comment by kbecciv** [comment] 2024-04-25 15:27
Issue is not reproducible, build 1.4.66.0

https://github.com/Expensify/App/assets/93399543/ca7e8b10-d45b-49e7-be99-41f716cbe754

**Comment by johncschuster** [comment] 2024-04-25 16:49
Great! Thank you! In that case, I’ll consider this resolved.

**Closed by johncschuster** 2024-04-25 16:49 UTC
Labels: Weekly, Internal, Bug, retest-weekly
