### ISSUE TITLE
Dev - Payment page is flickering

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12928] opened 2022-11-22 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Have unreliable internet connection
2. Go to Payment page

## Expected Result: 
No flickering

## Actual Result: 
Payment page is flickering

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.28
**Reproducible in staging?:** Issue occurs only in Dev - Needs reproduction
**Reproducible in production?:** Issue occurs only in Dev - Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203345969-4bb67780-3bd3-4ae1-998d-f3a4cedd4ff0.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669048381271409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-11-23 21:10
Closing this since it seems to be the expected behavior for now and I don't think that we want to debounce the network status check since this is happening in dev only.

**Closed by luacmartins** 2022-11-23 21:10 UTC
Labels: Daily, Needs Reproduction, Bug
