### ISSUE TITLE
[HOLD for payment 2023-09-29] [$500] Workspace details don't show up in participants selector

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27510] opened 2023-09-15 10:35 UTC
Clean up for: https://github.com/Expensify/App/pull/25564

When you select a workspace in the new request money flow, the workspace details do not show up.

![image](https://github.com/Expensify/Expensify/assets/30609178/9b83e584-bc3e-4157-a27a-d5f31b38083d)

1. Request money
2. Select a workspace
3. Notice that it doesn't contain the details

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018607cb9d54e7235a</li>
        <li>Upwork Job ID: 1702632412164861952</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 26745052</li>
<li>bernhardoj | Contributor | 26745057</li>
</ul></li>
    </ul>
</details>

**Comment by studentofcoding** [comment] 2023-09-15 10:43
> Clean up for: #25564
> 
> When you select a workspace in the new request money flow, the workspace details do not show up.
> 
> ![image](https://github.com/Expensify/Expensify/assets/30609178/9b83e584-bc3e-4157-a27a-d5f31b38083d)
> 
> 1. Request money
> 2. Select a workspace
> 3. Notice that it doesn't contain the details
> 
> Upwork Automation - Do Not Edit

Hey @thienlnam, the Image is broken, can you re-attach again? thanks!

**Comment by situchan** [comment] 2023-09-15 10:45
<img width="334" alt="Screenshot 2023-09-15" src="https://github.com/Expensify/App/assets/108292595/2bf215d3-6ac1-41d4-bcb8-f0c3e2698f37">

**Comment by BhuvaneshPatil** [comment] 2023-09-15 11:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
Currently we use `getParticipantsOptions` to find the details for getting the sections items in `MoneyRequestParticipantsSelector`.
In case of workspace, we have accountID = 0, and we don't find the record for that in personalDetails. and hence the fields are empty and thus we don't have details for them.

### What changes do you think we should make in order to solve the problem?
- Create a new function that will specifically handle the workspaces as participant.
- it will take two arguments, participants and chatReports
```js
function getParticipatingWorkspace(participants, chatReports) {
    const reportIDs = participants.filter((p) => p.accountID === 0).map((workspace) => workspace.reportID);
    const workspaces = chatReports.filter((report) => {
        return reportIDs.includes(report.reportID);
    });
    return workspaces;
}
```
It will filter the workspaces from recent chatReports and return the participating workspaces. we then concat this array for sections in `MoneyRequestParticipantSelector`, in the following section's data

https://github.com/Expensify/App/blob/144e932c2ea863bffafbd26e9cc7602e89b1e352/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L106-L111


The code can be cleaned and handle the conditions better.
result - 
<img width="923" alt="Screenshot 2023-09-15 at 5 06 03 PM" src="https://github.com/Expensify/App/assets/27822551/77846791-c510-41bb-9824-79c4a31875e5">

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2023-09-18 04:54
@situchan Mind reviewing these proposals today? This is a bit of a critical issue with the new global create

**Comment by situchan** [comment] 2023-09-18 07:27
Sure!

**Comment by situchan** [comment] 2023-09-18 11:28
@BhuvaneshPatil @bernhardoj thanks for the proposals.
While @BhuvaneshPatil first identified both issues with the root cause, @bernhardoj provided more detailed solution with regression fixes.
Also I checked edited timeline and @bernhardoj first proposed complete solution.
So I'd like to go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/27510#issuecomment-1722203463).
🎀 👀 🎀 C+ reviewed

**Comment by strepanier03** [comment] 2023-09-18 20:53
@bernhardoj @situchan - Would the fix here resolve this [report](https://expensify.slack.com/archives/C049HHMV9SM/p1695069307703199?thread_ts=1695068652.962549&cid=C049HHMV9SM) as well?

@kbecciv for visibility.

**Comment by situchan** [comment] 2023-09-18 21:17
@strepanier03 yes, should be fixed here

cc: @bernhardoj

**Comment by chiragsalian** [comment] 2023-09-18 23:29
Once the PR is done i think we should CP it so that it addresses the blocker.

**Comment by situchan** [comment] 2023-09-19 04:43
@bernhardoj if that is the offending PR, please continue test after reverting it locally.

**Comment by sophiepintoraetz** [comment] 2023-10-02 02:17
Payouts due:

Issue Reporter: N/A
Contributor: $750 @bernhardoj 
Contributor+: $750 @situchan (once you have completed the BZ checklist, I'll release payment!)

Eligible for 50% #urgency bonus? Y

**Comment by situchan** [comment] 2023-10-02 02:21
No regression. This was clean-up of https://github.com/Expensify/App/pull/25564 in Simplify Global Create project.
I think regression test will be part of https://github.com/Expensify/Expensify/issues/318720

**Comment by sophiepintoraetz** [comment] 2023-10-02 02:23
Ah good point - @thienlnam - can you confirm there is a regression test included for this bug in https://github.com/Expensify/Expensify/issues/318720?

**Closed** 2023-10-02 02:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
