### ISSUE TITLE
[$1000] iOS - Unread LHN - Unread username unbolded after minimize or open command center

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11951] opened 2022-10-18 02:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run NewDot App
2. Open LHN and receive new msg while focused on the tab
3. Minimize App or open Command center few times

## Expected Result:
Unread indication functionality should works without any issues at LHN tab

## Actual Result:
If the user focused on the LHN tab and new msg is received: App minimising or opening command center will lead to unbold username at the LHN tab

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/196318472-54550aed-4e91-4185-8006-dc9c4503182c.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2022-10-18 16:15
hmm strange! tossing to the pool, I don't think this need to be a daily but def isn't great UX.

**Comment by muttmuure** [comment] 2022-10-19 12:28
I think this needs the External label, we've engineering reviewed and triaged out of order

**Comment by muttmuure** [comment] 2022-10-19 12:45
I'm getting an error when I try to post to Upwork. I've raised it in #bugzero https://expensify.slack.com/archives/C01SKUP7QR0/p1666183255766669

**Comment by muttmuure** [comment] 2022-10-19 13:05
Just needed to wait a little bit and now it's posted

**Comment by muttmuure** [comment] 2022-10-19 15:18
The job is here https://www.upwork.com/jobs/~01b43085bb2505c069

**Comment by chauchausoup** [comment] 2022-10-20 04:34
I think this issue was reported first in here by me : https://github.com/Expensify/App/issues/11514

**Comment by thesahindia** [comment] 2022-10-20 06:25
I don't see any similarities. It's a different issue.

**Comment by muttmuure** [comment] 2022-10-28 15:44
Price has been doubled to $500

**Comment by iwiznia** [comment] 2022-11-07 14:58
Should we double again?

**Comment by muttmuure** [comment] 2022-11-07 15:48
Price has been doubled to $1000 - will cross post to Slack.

**Comment by railway17** [comment] 2022-11-08 15:36
### Proposal

**Why this issue is produced ?**
This issue is produced because `unsubscribeVisibilityListener` is not unsubscribed correctly when navigating to home.
As you know, `VisibilityListener` was defined in the `src/pages/home/report/ReportActionsView.js`.
There is also an unsubscriber in `componentWillUnmount` but not called when page is navigated to home by back button because opening the drawer will not destroy the component (navigating to home will be done by DrawerActions.openDrawer()).

```
componentDidMount() {
        this.unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            if (!this.getIsReportFullyVisible()) {
                return;
            }

            // If the app user becomes active and they have no unread actions we clear the new marker to sync their device
            // e.g. they could have read these messages on another device and only just become active here
            this.openReportIfNecessary();
            this.setState({newMarkerSequenceNumber: 0});
        });

        this.keyboardEvent = Keyboard.addListener('keyboardDidShow', () => {
            if (!ReportActionComposeFocusManager.isFocused()) {
                return;
            }
            ReportScrollManager.scrollToBottom();
        });
```

Inside the callback of this listener, `openReportIfNecessary` was defined to update the `report` occasionally.
As mentioned in the comment, this method is needed to update the unread message status. (Internally, it will call API with the `OpenReport` command and update the onyx data).
Because AppState is changed when the app is minimized and open, and the listener is still alive,  `openReportIfNecessary` is called in the callback.
And it updates the report data as if user is still on `ReportActionsView` component (chat page).

**Solution:**
From the above problem, important point is to unsubscribe the `VisibilityListener` when page is leaving from `ReportActionsView` component.
So, I am going to write unsubscribing method like below, and call it by ref. (I know there are several way to unsubscribe. But I used ref here. Hopefully, let me know if this is not a good way for coding style in this project)

`src/pages/home/report/ReportActionsView.js`
```diff
componentWillUnmount() {
+        this.unsubscribeEvents()
   }

+    /**
+     * unsubscribe all of the events when component is unmounted or navigated to home
+     */
+    unsubscribeEvents = () => {
+        if (this.keyboardEvent) {
+            this.keyboardEvent.remove();
+        }
+
+       if (this.unsubscribeVisibilityListener) {
+          this.unsubscribeVisibilityListener();
+        }
+
+       if (this.unsubscribeFromNewActionEvent) {
+            this.unsubscribeFromNewActionEvent();
+        }
+
+       Report.unsubscribeFromReportChannel(this.props.report.reportID);
+    }

```
`src/pages/home/ReportScreen.js`

```diff
        super(props);
        
+        this.reportActionsViewRef = React.createRef();
        this.onSubmitComment = this.onSubmitComment.bind(this);

...
      <OfflineWithFeedback
              pendingAction={addWorkspaceRoomOrChatPendingAction}
              errors={addWorkspaceRoomOrChatErrors}
              shouldShowErrorMessages={false}
          >
              <HeaderView
                  reportID={reportID}
-                  onNavigationMenuButtonClicked={()=> Navigation.navigate(ROUTES.HOME) }
+                  onNavigationMenuButtonClicked={() => {
+                      if (this.reportActionsViewRef.current !== null) {
+                          this.reportActionsViewRef.current.unsubscribeEvents()
+                      }
+                     Navigation.navigate(ROUTES.HOME)
+                  }}
                  personalDetails={this.props.personalDetails}
                  report={this.props.report}
                  policies={this.props.policies}
              />
          </OfflineWithFeedback>

...
      {this.isReportReadyForDisplay() && (
              <ReportActionsView
+                  ref={this.reportActionsViewRef}
                  reportActions={this.props.reportActions}
                  report={this.props.report}
                  session={this.props.session}
                  isComposerFullSize={this.props.isComposerFullSize}
                  isDrawerOpen={this.props.isDrawerOpen}
                  parentViewHeight={this.state.skeletonViewContainerHeight}
              />
          )}
```

This will resolve the issue.
PS: I've also noticed that Android has same problem, and tested in both ios/android platforms.
Those are working fine.

**Comment by thesahindia** [comment] 2022-11-08 22:45
The proposal looks good at first glance but I won't be able to look much into it right now (4 AM for me) will look into it ASAP in the morning.

**Comment by thesahindia** [comment] 2022-11-09 09:23
~The proposal looks good at first glance~ Taking my words back, it doesn't look good after looking into the issue.

@railway17, I am little lost here. I am not sure how your proposal solves this issue, can you confirm the issue? Also can you share a video after the fix?

**Comment by thesahindia** [comment] 2022-11-09 09:27
I found that if you mark the last message as unread and refresh the page then it gets read.

https://user-images.githubusercontent.com/83179295/200791424-bc08dffa-2c80-4722-b0a3-288e75809e27.mov

Steps:-
1. Navigate to any chat
2. Mark the last message as unread
3. Observe that the username is bold
4. Navigate to a different chat
5. Refresh the page
6. Observe that the username is not bold anymore

@iwiznia, should we include it in this issue or should I post this on slack.

**Comment by railway17** [comment] 2022-11-09 09:44
> I found that if you mark the last message as unread and refresh the page then the chat gets read.

> 1. Navigate to any chat
> 2. Mark the last message as unread
> 3. Observe that the username is bold
> 4. Navigate to a different chat
> 5. Refresh the page
> 6. Observe that the username is not bold anymore

Actually, this issue is reported with the reproducible platform - iOS.
So, I tested on mobile platforms (in both iOS and Android) and checked what is working.
But I missed the testing case by reproducing with `Mark as Unread`.
Just tested by sending a new message from another user.
I will update you with videos for both cases.

**Comment by railway17** [comment] 2022-11-09 12:45
@thesahindia 
https://drive.google.com/file/d/1mcirZLECKnUCn-tWBT-d9fsmLk0fp_PS/view?usp=sharing

Here is the video for fixing issue when the user received the new message.
This video is produced from my proposal code.

On the other hand, I've tested with `Mark as Unread`.
But looks like it is caused by another reason. I will catch it up and update you.

**Comment by thesahindia** [comment] 2022-11-09 19:35
It's really strange, I was able to repro this in the morning (on android and ios both) but I can't repro it anymore. 
@kbecciv, can you test this again?

**Comment by railway17** [comment] 2022-11-10 00:46
> 



> It's really strange, I was able to repro this in the morning (on android and ios both) but I can't repro it anymore. @kbecciv, can you test this again?

It's able to be reproduced if you go through `Report page > back to LHN > send message from another device  > minimize > open`.
If user entered into Report page,  `unsubscribeVisibilityListener` listener will be created in the componentDidMount.
But it will not be unsubscribed when go back to LHN page as I mentioned.
Because of it, issue would be produced

**Comment by thesahindia** [comment] 2022-11-10 06:49
Still no luck. 
https://user-images.githubusercontent.com/83179295/201019649-54e31de1-c7d7-42b0-9553-001134cadfd5.mp4

**Comment by railway17** [comment] 2022-11-10 07:15
> Also I am facing another issue. Chat isn't getting bold when receiving message while I am at LHN

@thesahindia 
Are you referring, you got another issue if you use my above change? 🤔

**Comment by thesahindia** [comment] 2022-11-10 09:11
> @thesahindia Are you referring, you got another issue if you use my above proposal code? 🤔

No, I am seeing this issue on production as well.

**Comment by railway17** [comment] 2022-11-10 09:25
@thesahindia 
One question.
Do you think Onyx data can be updated by logging into the console?
I thought all of the onyx data is changed by logging: `[Onyx] set() called for key: ${key}`.
But I've noticed that onyx data is changed without logging.
Who can give me a full answer to my question regarding Onyx?

**Comment by thesahindia** [comment] 2022-11-10 09:38
> But is not working for Mark as Unread.

I was only able to repro this issue by using `Mark as Unread`. I think the solution should work for `Mark as Unread` case too.

> Who can give me a full answer to my question regarding Onyx?

You can ask Onyx related questions at `#expensify-open-source`

**Comment by railway17** [comment] 2022-11-10 09:39
> was only able to repro this issue by using `Mark as Unread`. I think the solution should work for `Mark as Unread` case too.

Yes, I agree with it and still debugging for it 😓 

> You can ask Onyx related questions at #expensify-open-source

Thank you

**Comment by railway17** [comment] 2022-11-10 15:36
@thesahindia 
Which channel do I need to use to ask the API command problem?
Need to ask in the `#expensify-open-source` channel through slack?

**Comment by thesahindia** [comment] 2022-11-10 19:41
> Need to ask in the #expensify-open-source channel through slack?

Yep. If you haven't already joined the channel, you can request by sending an email at [contributors@expensify.com](mailto:contributors@expensify.com).

**Comment by muttmuure** [comment] 2022-11-11 11:40
Looks like we had a lot of great discussion yesterday! @railway17 and @thesahindia - think we can get a working proposal today? There's $1000 in it for ya! 😉

**Comment by railway17** [comment] 2022-11-11 11:42
> Looks like we had a lot of great discussion yesterday! @railway17 and @thesahindia - think we can get a working proposal today? There's $1000 in it for ya! 😉

😉
It's almost fully investigated.
I think I can submit updated proposal today

**Comment by muttmuure** [comment] 2022-11-14 16:54
Any update @railway17 @thesahindia?

**Comment by mvtglobally** [comment] 2022-11-16 02:19
Issue not reproducible during KI retests. (First week)

**Comment by thesahindia** [comment] 2022-11-21 08:04
Not overdue.

**Comment by marcaaron** [comment] 2022-11-22 00:05
Oh fun another one of these 😅

If I had to guess I'd say the chat is being marked as read in a call to `OpenReport` that is marking the report to "read"

Debugging the values of `getIsReportFullyVisible()` would be a good place to start

https://github.com/Expensify/App/blob/00d7c619cc409b96e6dddca5cc0ad406f0785331/src/pages/home/report/ReportActionsView.js#L253-L256

**Comment by marcaaron** [comment] 2022-11-22 00:07
also I think, generally speaking, if we identify a new bug while investigating another one it's a good practice to report a new issue unless you are _certain_ they have the same root cause (which can be difficult to see if we don't yet have a root cause).

**Comment by muttmuure** [comment] 2022-11-22 12:52
@marcaaron if this is no longer reproducible ([see here](https://github.com/Expensify/App/issues/11951#issuecomment-1316194409)) do we close it out?

**Comment by mvtglobally** [comment] 2022-11-22 21:12
Issue not reproducible during KI retests. (Second week)

**Comment by marcaaron** [comment] 2022-11-22 21:23
yeah let's close

**Closed by marcaaron** 2022-11-22 21:23 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug
