### ISSUE TITLE
[Hold] Trying to pay an iou without a debit card and the ability to use the wallet does not open the add debit card sidebar as expected 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21645] opened 2023-06-26 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new account
2. Start a new conversation
3. Receive a payment request
4. Click ‘Pay’
5. Select ‘Debit Card’

## Expected Result: 
the add card form appears on the right hand side
## Actual Result: 
the page refreshes, and the sidebar does not appear

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c66fed29-5f09-4699-9d9f-f9e2d30ba2e8

https://github.com/Expensify/App/assets/43996225/544fdda0-ac4c-4cb8-9626-ca05a5f7d2dc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dgwight
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687300587512869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dgwight** [comment] 2023-06-26 20:52
## Proposal
The correct debit card route needs to be passed down to SettlementButton from ReportPreview.js. I believe `ROUTES.IOU_SEND_ADD_DEBIT_CARD` is the correct route because that is what is passed down to SettlementButton from MoneyRequestConfirmationList.js

### Please re-state the problem that we are trying to solve in this issue.
A bug where the sidebar to add a new card does not open when the Pay button is clicked. 

### What is the root cause of that problem?
addDebitCardRoute is not passed down to SettlementButton from ReportPreview, so it cannot be passed to KYCWall. This makes so the app redirects to an empty url instead of the addDebitCardRoute.

### What changes do you think we should make in order to solve the problem?
The solution would look like this:
``` jsx
<SettlementButton
   currency={props.iouReport.currency}
   policyID={props.iouReport.policyID}
   chatReportID={props.chatReportID}
   iouReport={props.iouReport}
   onPress={(paymentType) => IOU.payMoneyRequest(paymentType, props.chatReport, props.iouReport)}
   enablePaymentsRoute={ROUTES.BANK_ACCOUNT_NEW}
   addBankAccountRoute={bankAccountRoute}
   addDebitCardRoute={ROUTES.IOU_SEND_ADD_DEBIT_CARD}
   style={[styles.requestPreviewBox]}
/>
```

### What alternative solutions did you explore? (Optional)
None

**Comment by dgwight** [comment] 2023-06-26 20:54
Contributor details
Your Expensify account email: dylangwight@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018571e164e984baba

**Comment by dgwight** [comment] 2023-06-26 21:20
I think the addDebitCardRoute should be passed into to the 2 SettlementButton components in MoneyRequestHeader.js also, to prevent a similar issue there

**Comment by muttmuure** [comment] 2023-06-29 15:29
I'm only seeing the option for **Pay Elsewhere**, I think we might have put a pause on P2P bugs

**Comment by dgwight** [comment] 2023-06-29 16:04
@muttmuure it requires these beta permissions 
`Permissions.canUsePayWithExpensify(this.props.betas) && Permissions.canUseWallet(this.props.betas)`
I was confused why it would only appear locally for me, even with the released version 1.3.32-5, but this is because all the beta permissions are automatically enabled locally.

I'm not sure how many users have these beta permissions in production yet, but it would be good to fix this before this feature is given to everyone

**Comment by muttmuure** [comment] 2023-08-01 17:28
No update needed

**Comment by muttmuure** [comment] 2023-09-05 16:55
We'll be picking the wallet back up soon

**Comment by muttmuure** [comment] 2023-10-11 11:28
Will check this again next month

**Comment by muttmuure** [comment] 2023-11-14 21:08
Not had time

**Comment by muttmuure** [comment] 2024-01-02 18:55
Not had time

**Comment by muttmuure** [comment] 2024-02-05 18:33
This flow has changed. If you don't have a debit card added to your wallet, the option defaults to Pay Elsewhere. Closing this in favor of newer reports about this functionality.

**Closed by muttmuure** 2024-02-05 18:33 UTC
Labels: Monthly, Overdue, Bug
