### ISSUE TITLE
[$500] Scan - Preview does not show number of requests and scanning when there is no manual request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33951] opened 2024-01-04 12:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat.
2. Click + > Request money > Scan.
3. Click more than one scan request.
4. Click a manual request.

## Expected Result:
The expense preview will show the number of requests and scanning when there are just scanning requests (Step 3).

## Actual Result:
The expense preview does not show the number of requests and scanning when there are just scanning requests (Step 3).
It only shows when there is a manual request in the report (Step 4).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c5fe56f3-e468-4028-b424-c97f4a3cf66d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4b523f2d65b5178</li>
        <li>Upwork Job ID: 1742891875847671808</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-04 13:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Preview does not show number of requests and scanning when there is no manual request

### What is the root cause of that problem?
We are currently not displaying the number when all the requests are scanning
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/components/ReportActionItem/ReportPreview.js#L156-L157
### What changes do you think we should make in order to solve the problem?

remove the condition
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-01-04 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The number of request doesn't show if the request only contains scan request.

### What is the root cause of that problem?
It might be intentional because we add a condition to only show it ONLY if there is a non-scanning request.
https://github.com/Expensify/App/blob/d5f5856b610cc39d5b5f2b054dab67bb74d66922/src/components/ReportActionItem/ReportPreview.js#L311-L317

### What changes do you think we should make in order to solve the problem?

If we want to change this, then we need to remove `!isScanning` condition.

**Comment by unicorndev-727** [comment] 2024-01-04 16:12
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
It doesn't show request number of request and scanning after we add a manual request.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/components/ReportActionItem/ReportPreview.js#L156

https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/libs/ReportUtils.ts#L1953-L1960

We have already the logic to show number of request and scanning [here](https://github.com/Expensify/App/blob/d5f5856b610cc39d5b5f2b054dab67bb74d66922/src/components/ReportActionItem/ReportPreview.js#L311-L317) but the root cause of that it doesn't work when we add manual request is that we didn't consider the change of action in useEffect here so that areAllRequestsBeingSmartScanned returns true before we revisit page.
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/components/ReportActionItem/ReportPreview.js#L234-L244
### What changes do you think we should make in order to solve the problem?
We need to add `props.action` as a dependency so that `ReportUtils.areAllRequestsBeingSmartScanned` can return false as soon as we have a non-receipt request.
It doesn't break original logics and solve the issue effectively.
```
useEffect(() => {
        const unsubscribeOnyxTransaction = onyxSubscribe({
            key: ONYXKEYS.COLLECTION.TRANSACTION,
            waitForCollectionCallback: true,
            callback: (allTransactions) => {
                if (_.isEmpty(allTransactions)) {
                    return;
                }

                sethasMissingSmartscanFields(ReportUtils.hasMissingSmartscanFields(props.iouReportID));
                setAreAllRequestsBeingSmartScanned(ReportUtils.areAllRequestsBeingSmartScanned(props.iouReportID, props.action));
                setHasOnlyDistanceRequests(ReportUtils.hasOnlyDistanceRequestTransactions(props.iouReportID));
                setHasNonReimbursableTransactions(ReportUtils.hasNonReimbursableTransactions(props.iouReportID));
            },
        });

        return () => {
            unsubscribeOnyxTransaction();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [props.action]);
```

```
useEffect(() => {
        const unsubscribeOnyxTransaction = onyxSubscribe({
            key: ONYXKEYS.COLLECTION.TRANSACTION,
            waitForCollectionCallback: true,
            callback: (allTransactions) => {
                if (_.isEmpty(allTransactions)) {
                    return;
                }

                sethasMissingSmartscanFields(ReportUtils.hasMissingSmartscanFields(props.iouReportID));
                setHasOnlyDistanceRequests(ReportUtils.hasOnlyDistanceRequestTransactions(props.iouReportID));
                setHasNonReimbursableTransactions(ReportUtils.hasNonReimbursableTransactions(props.iouReportID));
            },
        });

        return () => {
            unsubscribeOnyxTransaction();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        const unsubscribeOnyxTransaction = onyxSubscribe({
            key: ONYXKEYS.COLLECTION.TRANSACTION,
            waitForCollectionCallback: true,
            callback: (allTransactions) => {
                if (_.isEmpty(allTransactions)) {
                    return;
                }

                setAreAllRequestsBeingSmartScanned(ReportUtils.areAllRequestsBeingSmartScanned(props.iouReportID, props.action));
            },
        });

        return () => {
            unsubscribeOnyxTransaction();
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [props.action]);
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by joekaufmanexpensify** [comment] 2024-01-04 21:52
I [confirmed internally](https://docs.google.com/document/d/1Il9y1287B6tq0FB5ziXnhBcwn-Lw-n_rSmllZ-AyUVs/edit#bookmark=id.owwus74y28qn) that this is expected behavior. We don't show the number of requests when there are only receipts scanning, since at this point the report is just a preview only the submitter can see (until the receipt scanning of one receipt is done). 

If there are either receipts done scanning, or a manual request on the report, we show the total requests, and the number still scanning, since at this point the report has an actual expense that is visible to others. 

Closing, since this is expected.

**Closed by joekaufmanexpensify** 2024-01-04 21:52 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by unicorndev-727** [comment] 2024-01-04 23:18
@joekaufmanexpensify 
There is one issue though it is expected.
`It doesn't show request number of request and scanning after we add a manual request.(step4)`
Plz check my [proposal](https://github.com/Expensify/App/issues/33951#issuecomment-1877364869) again.
I think it should be fixed.
