### ISSUE TITLE
[$1000] Signin page flickiers on recieveing error message and pressing Continue again.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18907] opened 2023-05-14 11:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the Signin Page.
2. Keep entering wrong magic code till the error appears.
3. Click “Go Back”.
4. Press “Continue”.
5. Notice the error and red dot fllickers if the user keep on pressing “continue“ with the same invalid email.

## Expected Result: 
Signin page should not flicker pressing “continue“ with the same invalid email.

## Actual Result: 
Signin page flickers while pressing “continue“ with the same invalid email.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/60373ffa-bb61-4678-afee-e8b02741358a

https://github.com/Expensify/App/assets/43996225/c5970337-ff74-4bdb-b1af-456428f431b1

https://github.com/Expensify/App/assets/43996225/4c48b053-4067-4d36-a40d-9aea76cf55d3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1684002674106459
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b838367d696b31c</li>
        <li>Upwork Job ID: 1658176808358346752</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-05-15 09:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message in login page is flickering.

### What is the root cause of that problem?
If we slow down the video, we can see there are 2 errors. The first error comes from the response, while the second one is a generic error message set in `failureData`.
https://github.com/Expensify/App/blob/b01caf6bb4d288e0f6ed199026bada9024819c7f/src/libs/actions/Session/index.js#L242-L253

When the request fails, the server error will be merged to the onyx first, then later on we merge the error from `failureData`.
https://github.com/Expensify/App/blob/b01caf6bb4d288e0f6ed199026bada9024819c7f/src/libs/Middleware/SaveResponseInOnyx.js#L21-L24

### What changes do you think we should make in order to solve the problem?

As we have an error from the server, we don't need the generic error set locally anymore. It also overwrite the server error which is more informational (like in this case, it tells us we reached the maximum magic code request attempt). So, we need to remove the error message from `failureData`.

**Comment by tjferriss** [comment] 2023-05-15 18:27
I was able to reproduce the issue and I don't see any duplicates reported.


https://github.com/Expensify/App/assets/8292562/dc3c9038-9d03-4fd3-a03d-dbe3a6f17783

**Comment by tienifr** [comment] 2023-05-16 04:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The error message is flickering in sign in page

### What is the root cause of that problem?

We're showing the error message from account: 
`const serverErrorText = ErrorUtils.getLatestErrorMessage(this.props.account);`

1. When users sign-in, we call API `BeginSignIn` and reset account data 

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/libs/actions/Session/index.js#L218

2. The error message disappear for a moment
3. Response of  BeginSignIn API updates error message 
4. We see the error message appear again

### What changes do you think we should make in order to solve the problem?

We should't clear error in account data when call API BeginSignIn.

If we change the input, we already have the logic to clear error data 

https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/signin/LoginForm.js#L78-L81

So we can remove this line https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/libs/actions/Session/index.js#L218

### Result

https://github.com/Expensify/App/assets/113963320/f5fe9504-e6aa-460d-bb85-9d78dc27ad5a

**Comment by tjferriss** [comment] 2023-05-18 12:31
@0xmiroslav what do you think of the proposal?

**Comment by tylerkaraszewski** [comment] 2023-05-24 18:17
We are still waiting on proposals

**Comment by tylerkaraszewski** [comment] 2023-05-24 19:19
I think the fix looks fine for the second case:

> error message briefly disappears and then appears

@tjferriss - what do you think of this proposed fix?

**Comment by bernhardoj** [comment] 2023-05-25 05:01
Sharing my opinion.

> error message briefly disappears and then appears

I believe this is the expected behavior. It's a good UX to let user know that we are sending a new request (besides the loading on button).

We don't do the same thing with Front End validation because when the text does not change, the error will stay the same, so no point in removing the error for FE validation.

But it's different with server/BE validation because we could get a different response with the same input. (we can see there are lot of place where we reset error in optimisticData)

**Comment by tjferriss** [comment] 2023-05-26 18:30
@bernhardoj thanks for the explanation. I tend to agree with this after giving this some more thought. I actually did not notice the separate error message flicker when initially reviewing the issue.

So let's focus on the original problem when a separate error message flickers.

I actually just tried to reproduce the bug again and I can't even get "You've reached the maximum number of codes..." error message to appear. I tried dozens of magic codes and it still gives me the "Incorrect magic code. Please try again or request a new code" error.

**Comment by bernhardoj** [comment] 2023-05-27 11:10
I can get the max request error by requesting it > 5 times, but I can't reproduce the message flicker anymore.

**Comment by tjferriss** [comment] 2023-05-30 20:27
>I can get the max request error by requesting it > 5 times, but I can't reproduce the message flicker anymore.

@hoangzinh thanks for clarifying. I was able to get the max request error, but similar to @bernhardoj I don't get the flicker of a different error message. Are you still seeing this?

**Comment by tjferriss** [comment] 2023-06-05 19:22
>So let's focus on the original problem when a separate error message flickers.

Huh but in your example we don't see the incorrect error message displayed in the flicker. I think we can close this at this point.

**Closed by tjferriss** 2023-06-05 19:22 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
