### ISSUE TITLE
[$500] The workspace name value initially appears at the top when click the back arrow at "Get assistance" tab

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21735] opened 2023-06-27 19:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Open workspace chat
2- Click at the chat name
3- Click at the chat name again
4- Go to the settings tap
5- Click at the question mark
6- Click at the "back" arrow
## Expected Result: 
The workspace name value remains consistent and appears correctly in its original position when navigating back to the settings tab.
## Actual Result: 
The workspace name value initially appears at the top and then returns to its original position while opening the settings tab.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a05b096c-e971-40cb-9fbf-56edc66b0a28

https://github.com/Expensify/App/assets/43996225/59bb9e67-334d-4ddc-9692-b09a7b2ef67a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @MejedAlkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687626876963139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7f2fb048028a290</li>
        <li>Upwork Job ID: 1674945520690294784</li>
        <li>Last Price Increase: 2023-07-01</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-30 00:40
I really don't know what I'm looking for here. I commented in the Slack thread asking for more specific reproduction steps.

**Comment by sakluger** [comment] 2023-07-01 00:58
Okay I was able to reproduce. For what looks like a single frame, the Workspace name is higher in the box:

![image](https://github.com/Expensify/App/assets/5997400/ba94d5ea-db42-412a-ab38-51a9f56ee22f)

I think that this is barely a bug as is, since it's really not noticeable unless you take a video and play it back frame by frame. But just in case we have performance issues with the app, it could become more noticeable, so we might as well fix.

**Comment by sakluger** [comment] 2023-07-01 00:59
Because this is so low impact, I'm going to change the base price to $500. I'm guessing that it will be an easy fix - @abdulrahuman5196 if this actually is a harder fix, let me know and I can adjust the price accordingly.

**Comment by OctavianGuzu** [comment] 2023-07-01 02:10
I'm working on this, I believe I found the root cause and a fix. Writing the proposed solution in the next 10-15 mins. :)

**Comment by OctavianGuzu** [comment] 2023-07-01 02:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Navigating between the "Workspace Settings" and "Get Assistance" tabs flickers the location of the Workspace Name.

### What is the root cause of that problem?
1. When the user reaches the `Workspace Settings` page the the `TextInput` element has a `height` of `52px`:
<img width="1146" alt="image" src="https://github.com/Expensify/App/assets/23151373/d3cab8d2-cacb-4aeb-91d6-2d071e6bed50">
2. Then, when the user navigates to the "Get Assistance" tab, the height of the `TextInput` becomes `0`:
<img width="1167" alt="image" src="https://github.com/Expensify/App/assets/23151373/f7c2abb3-9dee-4fef-806c-c01345f63c5e">
3. When the user goes back to the `Workspace Settings`, the `height` gets set back to `52px`, which is obviously not instant and has a flickering effect, especially on slower devices, such as older phones or slower computers.

### What changes do you think we should make in order to solve the problem?
Digging into the `TextInput` component for a while, I concluded that we can set the `autoGrowHeight` prop to `true` for the `TextInput` containing the Workspace Name, in `src/pages/workspace/WorkspaceSettingsPage.js`:
<img width="1068" alt="image" src="https://github.com/Expensify/App/assets/23151373/f15f5fbf-0bbd-4be2-8a67-f79a7a5ed51a">
By making this change, we are preventing the height change, which is happening normally here (src/components/TextInput/BaseTextInput.js): 
<img width="893" alt="image" src="https://github.com/Expensify/App/assets/23151373/9f042832-ede7-463b-84cb-f86d8255b709">
where `const isMultiline = this.props.multiline || this.props.autoGrowHeight;`
Even better, the `TextInput` is now adjusting its height automatically and the flickering is prevented as the height stays constant now:

https://github.com/Expensify/App/assets/23151373/dc99ccbd-8903-4a39-9a2e-21fa3d3288b6



### What alternative solutions did you explore? (Optional)
N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by OctavianGuzu** [comment] 2023-07-01 11:03
@abdulrahuman5196 let me know if that works and I'll quickly create a PR. Thanks!

**Comment by abdulrahuman5196** [comment] 2023-07-02 18:03
>I think that this is barely a bug as is, since it's really not noticeable unless you take a video and play it back frame by frame. But just in case we have performance issues with the app, it could become more noticeable, so we might as well fix.

@sakluger Is this even a bug? I don't think its a bug, just seems to be minor transition of elements. I don't think even if we had any performance issues with the app, this wouldn't be a bug(that case we would have multiple elements jittery animations).
**If the jitter is not clearly visible in any platform I would suggest to not consider this as a bug and close the issue**

**Comment by OctavianGuzu** [comment] 2023-07-02 18:07
@abdulrahuman5196 I can put up a PR as I've already invested some time debugging this. Regarding the payout, feel free to set it to whatever you think it would be worth, no hard feelings.

**Comment by abdulrahuman5196** [comment] 2023-07-02 18:17
@OctavianGuzu Thank you for the proposal. But our proposal/reward system doesn't work that way. Kindly go through our contributing guidelines - https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md

**Comment by mejed-alkoutaini** [comment] 2023-07-02 18:28
@abdulrahuman5196 I think this should be considered as a bug since it's very noticeable on the mobiles.
have a look: https://github.com/Expensify/App/assets/79811973/3c2a1cc6-c08b-4c64-a829-ad27514a9e3e

**Comment by mejed-alkoutaini** [comment] 2023-07-02 18:31
Contributor details
Your Expensify account email: majedkot0@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fd6d1871acf14d4b

**Comment by sakluger** [comment] 2023-07-03 18:31
Fair point @abdulrahuman5196! I'll close for now. If this does end up being noticeable at some point later on, we can consider it a bug then.

**Closed by sakluger** 2023-07-03 18:31 UTC
Labels: External, Daily, Help Wanted, Bug
