### ISSUE TITLE
Chat - The picture is squished after took a photo in portrait mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13805] opened 2022-12-22 23:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with any account
3. Tap on any chat
4. Tap on plus button
5. Tap Add attachment - Take a photo
6. Take a photo and save it

## Expected Result:
The picture is squished after took a photo in portrait mode

## Actual Result:
The picture is squished after took a photo in portrait mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android app
- [ ] Android / Chrome

**Version Number:** 1.2.43.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

Uploading Bug5873765_Screen_Recording_20221222_155607_Chrome.mp4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sonialiap** [comment] 2022-12-30 12:05
@kbecciv are you still running into this behavior? I'm not able to reproduce it, maybe it was already resolved?

**Comment by sonialiap** [comment] 2023-01-02 20:30
Will leave this open until the next Overdue label, then will close if there's no update :)

**Comment by sonialiap** [comment] 2023-01-05 19:40
Closing due to not being able to reproduce and no updates on the issue

**Closed by sonialiap** 2023-01-05 19:40 UTC
Labels: Daily, Overdue, Bug
