### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000]  Inconsistency between native and mWeb: +1 is selectable on invite members page on mWeb 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22509] opened 2023-07-09 03:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click Profile icon in LHN
2. Click on an existing Workspace (or create a new)
3. Click Members 
4. Invite 9 members or more click Next
5. On Invite members confirmation page look for a "+1" at the end of the last avatar
6. Click on the +1 and notice it's selectable

## Expected Result: 
+1 should not be selectable

## Actual Result: 
+1 is selectable

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/96e1b4d4-0ed8-4c09-a61d-9efcf2d2969d

https://github.com/Expensify/App/assets/43996225/791c656e-23f5-4349-814e-9620ad826319

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688833661944869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c0def4a19dc0fdb</li>
        <li>Upwork Job ID: 1678540348334403584</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-07-09 03:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency between native and mWeb: +1 is selectable on invite members page on mWeb
### What is the root cause of that problem?
`selectable={false}` not work fine in all platform
### What changes do you think we should make in order to solve the problem?
add style `styles.userSelectNone` here
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/MultipleAvatars.js#L262-L265 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2023-07-09 05:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
For mWeb +1 text on the avatar is selectable

### What is the root cause of that problem?
We are not providing `selectable` prop false here which allows the text to be selecatable.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/MultipleAvatars.js#L216

### What changes do you think we should make in order to solve the problem?
Add `selectable={false}` for the `Text` here which prevents the text selection.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/MultipleAvatars.js#L216

**Comment by Christinadobrzyn** [comment] 2023-07-10 23:03
I can reproduce - added external

**Comment by narefyev91** [comment] 2023-07-11 09:46
Proposal from @Pujan92 looks good to me https://github.com/Expensify/App/issues/22509#issuecomment-1627608348
🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment] 2023-07-13 07:48
Sorry for the ping @nathan, we have made updated the code to prevent it from mentioning false GH handles.

**Comment by rafecolton** [comment] 2023-07-13 11:55
Why was I tagged here? I have no idea what this is.

**Comment by Christinadobrzyn** [comment] 2023-07-13 20:04
Offer sent to @Nathan-Mulugeta in Upwork as reporter. Offer automatically sent to @Pujan92 as C+

Upwork job posting - https://www.upwork.com/jobs/~010c0def4a19dc0fdb

**Comment by Pujan92** [comment] 2023-07-13 20:18
@narefyev91 @techievivek [PR](https://github.com/Expensify/App/pull/22838) is ready for review!

**Comment by Christinadobrzyn** [comment] 2023-07-14 17:52
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, we're reviewing the [PR](https://github.com/Expensify/App/pull/22838) and then it'll be time for payment based on https://github.com/Expensify/App/issues/22509#issuecomment-1634833886

**Comment by joekaufmanexpensify** [comment] 2023-07-17 13:10
Waiting for PR

**Comment by joekaufmanexpensify** [comment] 2023-07-24 20:13
@narefyev91 Could you please complete your portion of the BZ checklist? Once that's complete, we'll issue payment here.

**Comment by joekaufmanexpensify** [comment] 2023-07-24 20:16
@Pujan92 was assigned to the issue on 2023-07-13, and the PR was merged on 2023-07-14. So this qualifies for a speed bonus. So we need to make the following payments: 

- @Pujan92 $1,500 ($1,000 for PR and $500 speed bonus). 
- @Nathan-Mulugeta $250 for reporting. 
- @narefyev91 payment handled separately.

**Comment by joekaufmanexpensify** [comment] 2023-07-25 17:07
Bumped in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-07-25 17:20
@Pujan92 Do you mind stepping in to help with the BZ checklist? @narefyev91 is OOO on vacation right now.

**Comment by Pujan92** [comment] 2023-07-25 18:45
> * [X]  [@narefyev91] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/21402
> * [X]  [@narefyev91] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/21402/files#r1273945899
> * [X]  [@narefyev91] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> * [X]  [@narefyev91] Determine if we should create a regression test for this bug.
> * [X]  [@narefyev91] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Goto Settings -> Workspaces -> Select any workspace -> Members -> Invite
2. Select more than 8 participants to invite which displays the text for an extra number(eg. +1, +2)
3. Verify that extra number text is not selectable

> * [ ]  [@Christinadobrzyn / @joekaufmanexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

@techievivek @joekaufmanexpensify kindly review and let me know if I need to update something.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:42
Thanks! My 2c is this is a fairly niche bug, so I'm going to hold off on creating a regression test issue here. But LMK if anyone disagrees with that!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:43
BZ checklist is complete, all set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:44
@Pujan92 $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:45
@Nathan-Mulugeta $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:46
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-07-26 13:46
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. thanks everyone!

**Closed by joekaufmanexpensify** 2023-07-26 13:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
