### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Split - Participants under “Split with” list disappear after unselecting them

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32808] opened 2023-12-11 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to group chat > + > Split bill.
3. Enter amount > Next.
4. Unselect the participants.

## Expected Result:
Group participants will not disappear from the “Split with” list after unselecting them.

## Actual Result:
Group participants disappear from the “Split with” list after unselecting them.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/9ae38753-b36c-4e25-acf0-f55f7f1936a7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01103b76f36fd3edb8</li>
        <li>Upwork Job ID: 1734224694853259264</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 28035106</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2023-12-11 14:30
I'll look into it this morning.

**Comment by s-alves10** [comment] 2023-12-11 14:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Participants under "Split with" list disappear when unselecting them

### What is the root cause of that problem?

This is a regression of the PR https://github.com/Expensify/App/pull/28618

The root cause is in the following code segment
https://github.com/Expensify/App/blob/a16df0d7b095b98ed3b23df4add3508cbd8a69a2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L371

In the above code, `selectedParticipantsFiltered` is a filtered participants list(selected = true) as you can see here
https://github.com/Expensify/App/blob/a16df0d7b095b98ed3b23df4add3508cbd8a69a2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L361


### What changes do you think we should make in order to solve the problem?

Update the [above line](https://github.com/Expensify/App/blob/a16df0d7b095b98ed3b23df4add3508cbd8a69a2/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L371) to
```
        const unselectedParticipants = _.filter(selectedParticipants, (participant) => !participant.selected);
```

This works as expected


### What alternative solutions did you explore? (Optional)

**Comment by tgolen** [comment] 2023-12-11 14:53
The above [proposal](https://github.com/Expensify/App/issues/32808#issuecomment-1850229772) from @s-alves10 is correct. It was a fix that I missed adding to the refactored component.

**Comment by s-alves10** [comment] 2023-12-11 16:30
@allroundexperts 

PR is ready for review: https://github.com/Expensify/App/pull/32823

**Comment by allroundexperts** [comment] 2023-12-11 20:09
All yours @cubuspl42!

**Comment by tgolen** [comment] 2023-12-13 16:19
I don't think we need a regression test. This was caught during regression testing.

**Comment by s-alves10** [comment] 2023-12-19 10:15
> * [x]  [@s-alves10] Determine if we should create a regression test for this bug.
> * [x]  [@s-alves10] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

This is a regression of refactoring PR https://github.com/Expensify/App/pull/28618. I don't think we need regression test here

Do we agree 👍 or 👎

**Comment by tgolen** [comment] 2023-12-26 15:52
It looks like this can be closed out and we agree that we don't need a regression test.

**Comment by tgolen** [comment] 2023-12-26 15:52
Oops, it looks like this hasn't been paid out. Reopening and assigning someone to help with the payout.

**Comment by tgolen** [comment] 2023-12-26 15:53
@bfitzexpensify Could you please help pay this issue according to https://github.com/Expensify/App/issues/32808#issuecomment-1853706054?

**Comment by bfitzexpensify** [comment] 2023-12-26 20:11
Payment complete, closing this out.

**Closed by bfitzexpensify** 2023-12-26 20:11 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
