### ISSUE TITLE
[$500] mWeb/Chrome - Thread – Avatar stay grey for a second when save edited message in thread.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31429] opened 2023-11-16 11:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to a owned threaded conversation with several messages
4. Navigate to the parent conversation.
5. Edit the parent message to anything and save.

## Expected Result:
The avatar remains as it was

## Actual Result:
Avatar stay grey for a second when save edited message in 1:1 DM or edited message in thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6278750_1700121828701!SS](https://github.com/Expensify/App/assets/115492554/12b89242-4bd9-4c55-be65-af66af3a90ff)

https://github.com/Expensify/App/assets/115492554/7748a2aa-9f98-43a4-9529-977855a7ec86

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da54df1df3990b3a</li>
        <li>Upwork Job ID: 1725108991365107712</li>
        <li>Last Price Increase: 2023-12-09</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-11-16 16:35
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Avatar's grey background can be observed briefly when saving an edited message in 1:1 DM or edited message in a thread.

## What is the root cause of that problem?

The root cause of this issue is caused by a re-render of the edited message as a result of state change when a message is edited. This re-render also causes the `Avatar` image to reload and while this happens we see the `Avatar`'s background color (that grey).

The grey background color of the `Avatar` is set by `StyleUtils.getAvatarStyle()` that returns `backgroundColor: themeColors.offline` -> `offline: colors.darkIcons` -> `darkIcons: '#8B9C8F'`.

## What changes do you think we should make in order to solve the problem?

To handle the `Avatar` image reloading every time edit message is saved I decided to use [React Native's Image.prefetch()](https://reactnative.dev/docs/image#prefetch) to cache the image on disk and use the cached image instead of reloading from URI everytime we save an edited comment. 

For this I created a library at `@libs/PrefetchImage` where there's going to be platform specific implementation which will only apply on web:

```
// @libs/PrefetchImage/index.js:

import {Image as RNImage} from 'react-native';
/**
 * Prefetches a remote image from the provided URI for later use by caching it to the disk.
 * An optional callback can be invoked in the `.then()` block of `refetch` the promise.
 */
export default function prefetchImage(uri: string, callback?: (...args: unknown[]) => unknown) {
    RNImage.prefetch(uri).then(() => callback?.());
};
```

the `index.desktop.ts` and `index.native.ts` functions both return **just the callback** without performing `prefetch()`.

Then use `prefetchImage` in the `Avatar` component:

https://github.com/Expensify/App/blob/30cc17c69f70112cd9180773d53ea06dd241b6b6/src/components/Image/index.js#L39-L41

like so:

```
        prefetchImage(source.uri, () => {
            RNImage.getSize(source.uri, (width, height) => {
                onLoad({nativeEvent: {width, height}});
            });
        });
```

 ### Videos

<details>
<summary>mWeb: Chrome (included frame by frame)</summary>

- normal speed

https://github.com/Expensify/App/assets/56457735/8ce4e259-6fb4-413a-96d2-ad7a6cfafc62

- frame by frame

https://github.com/Expensify/App/assets/56457735/a7a11d80-2e26-4540-8135-f9c1a52e0bd6

</details>

**Comment by robertKozik** [comment] 2023-11-23 16:35
Hi! Sorry for the delay, can we confirm that it still can be reproduced? I cannot see that on my end:
<details>
<summary>videos</summary>

https://github.com/Expensify/App/assets/61146594/17e4f4dd-789d-4d2e-a870-d9a203672b06


https://github.com/Expensify/App/assets/61146594/e02f7454-4632-4206-89be-4d68c22bd2ba


</details>

**Comment by kevinksullivan** [comment] 2023-11-27 23:02
closing out unless we can reproduce.

**Comment by Victor-Nyagudi** [comment] 2023-12-11 14:56
I can't reliably reproduce this. It feels like 75% of my attempts don't reproduce it, and when I do, the grey flickers so quickly I can barely see it. 

I use Expensify on a physical Android Chrome often and have never observed any grey flickering when editing messages, whether they're a parent to a thread or not. 

Can anyone still reliably reproduce?

**Comment by kevinksullivan** [comment] 2023-12-12 03:02
This doesn't seem worth solving given the number of conditions that need to be met in order to barely experience it. Closing.

**Closed by kevinksullivan** 2023-12-12 03:02 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
