### ISSUE TITLE
[HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] [$1000] IOU - Double "request money" tab if request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23962] opened 2023-07-31 21:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22649
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Click on "+" in any chat / click on FAB menu
3. Click on "Request money"
4. Insert amount
5. Click "Next"

## Expected Result:
At step 5 user lands in IOU summary (with destination, amount and description)

## Actual Result:
At step 5 user lands in the same "insert amount" tab, it is duplicated.
Also if user switches to a different chat and requests money - amount from previous IOU would be dispalyed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/4faf2b6d-18e0-4cac-9b8b-41d5a62921d0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d986e83acbb6b2e5</li>
        <li>Upwork Job ID: 1686336524126748672</li>
        <li>Last Price Increase: 2023-08-01</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-07-31 23:07
the product can be still used. the user just have to click twice. this is not a deploy blocker

**Comment by hayata-suenaga** [comment] 2023-07-31 23:09
@mountiny do you think this is part of regression from the navigation refactoring?

**Comment by mountiny** [comment] 2023-08-01 11:18
@hayata-suenaga I think this one should still be a blocker, its should not be related to any navigation changes in general, those were deployed a while ago

**Comment by shubham1206agra** [comment] 2023-08-01 11:47
@mountiny Looks like there's some updation problem 
See this screenshot 
<img width="1478" alt="image" src="https://github.com/Expensify/App/assets/58412969/d2a748a9-d3ac-4b92-a0d0-1aa635471090">


Due to this, the following gets executed
https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L77-L78.

I think we need to put some waiting mechanism so that it doesn't get run on its first rendering.

**Comment by shubham1206agra** [comment] 2023-08-01 11:55
Or we can pass some kind of query params with the page to give assurance that the amount has been checked correctly. Don't worry about it

**Comment by mountiny** [comment] 2023-08-01 11:57
@hannojg maybe this is so quick because of the caching now so we need to add some load state there?

**Comment by shubham1206agra** [comment] 2023-08-01 12:10
> @hannojg maybe this is so quick because of the caching now so we need to add some load state there?

No actually opposite
State update is slow. That's why we see 2 props updates in the log.

I think you can also see saveAmountToState debug logs

**Comment by shubham1206agra** [comment] 2023-08-01 12:13
And for some reason, it is creating 2 different component instead of using one
See 1st
<img width="1478" alt="image" src="https://github.com/Expensify/App/assets/58412969/5ab91353-a3bc-4547-a202-95105d3e384b">
See 2nd
<img width="1478" alt="image" src="https://github.com/Expensify/App/assets/58412969/78f460b0-cd72-451f-8bac-58454f55007a">

**Comment by shubham1206agra** [comment] 2023-08-01 12:13
Both have different keys

**Comment by Pujan92** [comment] 2023-08-01 12:25
Seems it's the same RCA as https://github.com/Expensify/App/issues/23950 https://github.com/Expensify/App/issues/23950#issuecomment-1659127111, we called update the Amount in onyx and navigate to the participants page but in the participants page we received cached data with the amount 0 which again navigate back to the amount page.

https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L77-L79

**Comment by hannojg** [comment] 2023-08-01 12:39
**Problem**

We are setting the state for the current money request in onyx. When we press next we merge the new data (the amount and currency) to onyx here:

https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/iou/steps/MoneyRequestAmountPage.js#L380-L383

Then we navigate to the next page here:

https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/pages/iou/steps/MoneyRequestAmountPage.js#L418-L419

This page then checks the amount, and navigates back if its zero (as @shubham1206agra pointed out earlier):

https://github.com/Expensify/App/blob/89dfb7788ed3a533da5d5e2c9e55335028570d82/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L77-L78

In our case it's still zero, **because XXX used Onyx.merge, which is async (it returns a promise)**. We first have to await these operations to be done, before we can navigate to the next page.

**Solution:**

I was thinking whether this is a problem in onyx. but honestly the latest changes in onyx are only uncovering this bug. This was an incorrectness in the first place. When we merge data and then want to rely on them, we need to first await that they got saved.

My proposal roughly looks like this, waiting for the merged to finish:


```diff
index e25f7acb05..daa2304349 100755
--- a/src/pages/iou/steps/MoneyRequestAmountPage.js
+++ b/src/pages/iou/steps/MoneyRequestAmountPage.js
@@ -379,43 +379,43 @@ function MoneyRequestAmountPage(props) {
 
     const navigateToNextPage = () => {
         const amountInSmallestCurrencyUnits = CurrencyUtils.convertToSmallestUnit(selectedCurrencyCode, Number.parseFloat(amount));
-        IOU.setMoneyRequestAmount(amountInSmallestCurrencyUnits);
-        IOU.setMoneyRequestCurrency(selectedCurrencyCode);
+        Promise.all([IOU.setMoneyRequestAmount(amountInSmallestCurrencyUnits), IOU.setMoneyRequestCurrency(selectedCurrencyCode)]).then(() => {
+            saveAmountToState(selectedCurrencyCode, amountInSmallestCurrencyUnits);
```

However, later on in the function there are other async functions that would need to be awaited so I think this has to be done a bit cleaner additionally, but overall that's the idea to fix the issue.

**Comment by shubham1206agra** [comment] 2023-08-01 12:49
My solution

As I have pointed out earlier, the problem is the slow updating of props. But as @hannojg pointed out in slack, the Onyx.update uses promises to update.

So my thought would be to convert this function to async, and add a `FullScreenLoadingIndicator` so that the user doesn't feel that the page is stuck.

**Comment by railway17** [comment] 2023-08-01 13:17
I agree with @hannojg 
We need to wait until onyx data is updated.

### What alternative solutions did you explore? (Optional)
Alternatively, we can return if props.iou.amount is 0 in the `MoneyRequestParticipantsPage`.
Actually, this is the the user selection page that should be shown after entering the money.
Don''t need to handle any cases if amount is 0.
So, we can change like below
```diff
useEffect(() => {
+        if (props.iou.amount === 0) {
+            return;
+       }
       // ID in Onyx could change by initiating a new request in a separate browser tab or completing a request
        if (prevMoneyRequestId.current !== props.iou.id) {
            // The ID is cleared on completing a request. In that case, we will do nothing
            if (props.iou.id) {
                navigateBack(true);
            }
            return;
        }

        // Reset the money request Onyx if the ID in Onyx does not match the ID from params
        const moneyRequestId = `${iouType.current}${reportID.current}`;
        const shouldReset = props.iou.id !== moneyRequestId;
        if (shouldReset) {
            IOU.resetMoneyRequestInfo(moneyRequestId);
        }

-        if (props.iou.amount === 0 || shouldReset) {
+       if (shouldReset) {
            navigateBack(true);
        }

        return () => {
            prevMoneyRequestId.current = props.iou.id;
        };
    }, [props.iou.amount, props.iou.id]);
```

**Comment by hannojg** [comment] 2023-08-01 13:39
> So my thought would be to convert this function to async, and add a FullScreenLoadingIndicator so that the user doesn't feel that the page is stuck.

There won't be no real noticeable delay for the user. It is async, but in reality we are just controlling the order of events. Everything really happens on the cache and it only takes a few ms until all the promises have been called back, so that isn't really needed.

**Comment by hannojg** [comment] 2023-08-01 13:46
Working on a PR here: https://github.com/Expensify/App/pull/23996

**Comment by hannojg** [comment] 2023-08-01 13:58
@Pujan92 good catch, will look into it as well in the next minutes!

**Comment by hayata-suenaga** [comment] 2023-08-01 16:08
This deploy blocker was solved [by revering an onyx update here](https://github.com/Expensify/App/pull/24003)

**Comment by Beamanator** [comment] 2023-08-01 16:16
Should be fixed now, as of https://github.com/Expensify/App/pull/24003

**Comment by saalimzafar** [comment] 2023-08-01 22:31
Proposal: Addressing Double "Request Money" Tab Issue

Root Problem:
Changes to the money request ID may not be synchronized across all open tabs, leading to the unintended duplication of the "Request Money" tab or other undesired behavior.

Solution:
To fix the double "Request Money" tab issue, we will implement a simple and effective solution using the `useState` hook to manage the current money request ID within the component's local state. This will enable us to accurately track changes to the ID and trigger appropriate navigation and reset logic based on the updated value.

Implementation Steps:

1. Introduce `useState` for Current Money Request ID:
   ```javascript
   import React, { useEffect, useState } from 'react';
   // ... (other imports)

   function MoneyRequestParticipantsPage(props) {
       const [currentMoneyRequestId, setCurrentMoneyRequestId] = useState(props.iou.id);
       // ... (rest of the code remains the same)
   }
   ```
   We use `useState` to create the `currentMoneyRequestId` state variable, initialized with the initial value of `props.iou.id`.

2. Update State When Money Request ID Changes:
   ```javascript
   useEffect(() => {
       if (currentMoneyRequestId !== props.iou.id) {
           if (props.iou.id) {
               navigateBack(true);
           }
           return;
       }

       const moneyRequestId = `${iouType.current}${reportID.current}`;
       const shouldReset = props.iou.id !== moneyRequestId;
       if (shouldReset) {
           IOU.resetMoneyRequestInfo(moneyRequestId);
       }

       if (props.iou.amount === 0 || shouldReset) {
           navigateBack(true);
       }

       return () => {
           setCurrentMoneyRequestId(props.iou.id);
       };
   }, [currentMoneyRequestId, props.iou.id, props.iou.amount]);
   ```
   We use `useEffect` to detect changes in the `currentMoneyRequestId` and `props.iou.id`. If the IDs differ, we navigate back to prevent duplication of the "Request Money" tab. We also update the `currentMoneyRequestId` whenever `props.iou.id` changes to keep the local state in sync.

3. Handle Navigation and Reset Logic:
   ```javascript
   const navigateToNextStep = () => {
       // ... (existing code for navigateToNextStep)
   };

   const navigateBack = (forceFallback = false) => {
       // ... (existing code for navigateBack)
   };
   ```
   The existing navigation logic remains unchanged and is based on the updated `currentMoneyRequestId`. We continue using `navigateToNextStep` and `navigateBack` for seamless navigation.

By implementing this solution, the issue of the double "Request Money" tab will be resolved. The `useState` hook allows us to efficiently manage the money request ID within the component's local state, ensuring accurate tracking and handling of changes. The proposed solution maintains a seamless user experience, providing a consistent view of the "Request Money" tab across all browser tabs.

**Comment by hayata-suenaga** [comment] 2023-08-02 00:10
> @hayata-suenaga do you mind testing that this is not fixed on staging? 🙏

forgot to update here. tested on staging and it's fixed now 🙇

**Comment by hayata-suenaga** [comment] 2023-08-24 15:23
@mallenexpensify I'd appreciate if you could take care of payment when you have time 🙇

**Comment by mallenexpensify** [comment] 2023-08-29 23:09
Sorry for the (lonnnnng) delay.  It appears @aimane-chnaif is the only one due compensation, for C+ review of the PR. If so, @aimane-chnaif , can you please accept the job and reply here once you have?  https://www.upwork.com/jobs/~01d986e83acbb6b2e5

**Comment by mallenexpensify** [comment] 2023-09-04 23:56
Contributor+: @aimane-chnaif paid $1000 via Upwork.

**Closed by mallenexpensify** 2023-09-04 23:56 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Awaiting Payment, Bug
