### ISSUE TITLE
Import categories - Column header for category is imported as a category

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48644] opened 2024-09-05 13:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-9
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account is newly created.
- "File contains column headers" has not been disabled previously.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.
5. Upload the attached csv file that has column header (category name) (attached below).
6. Map Name and Enabled.
7. Click Import.
8. Note that the column header for category is imported as a category.
9. Repeat Step 3 to 6, but now "File contains column headers" is disabled and then reenabled.
10. Click Import.
11. Note that the column header for category is not imported as a category.

## Expected Result:
In Step 8, the column header for category will not be imported as a category (old dot behavior).

## Actual Result:
In Step 8, the column header for category is imported as a category.

This issue only happens when "File contains column headers" has not been disabled previously (enabled by default).

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/aba90814-fbc5-41e8-bf46-d8cc8f1deece

[Bug6593989_1725535163255!real_table_cat (1).csv](https://github.com/user-attachments/files/16894192/Bug6593989_1725535163255.real_table_cat.1.csv)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-09-05 13:36
@filip-solecki, can you look into fixing this one? I think it's a very specific flow. It worked normally for the tester, but they had to go back and enable and disable the toggle to get to this state. They can also easily remove the categories and reupload the CSV, so I don't think this has to be a blocker now that most things are working fine.

**Comment by etCoderDysto** [comment] 2024-09-05 13:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Import categories - Column header for category is imported as a category
### What is the root cause of that problem?

* Here we are assigning a default value true to `containsHeader`, and the switch is enabled  https://github.com/Expensify/App/blob/2ef63e78d7d2bdef18035649582b7bb84fa84b6a/src/components/ImportSpreadsheetColumns.tsx#L51
* But, in `ImportedCategoriesPage` we are not assigning a default value true to `containsHeader`, and column header is not excluded from `categories` that will be exported even if the switch is enabled  
https://github.com/Expensify/App/blob/e1d726e7f5bc0b3e1b5c24ad088411528f2d2a57/src/pages/workspace/categories/ImportedCategoriesPage.tsx#L28
### What changes do you think we should make in order to solve the problem?
We should assign a default value of true below too
```
const {containsHeader = true} = spreadsheet ?? {};
```

https://github.com/Expensify/App/blob/e1d726e7f5bc0b3e1b5c24ad088411528f2d2a57/src/pages/workspace/categories/ImportedCategoriesPage.tsx#L28
### What alternative solutions did you explore? (Optional)

**Comment by filip-solecki** [comment] 2024-09-05 15:22
Ready for review cc @mountiny @rushatgabhane

**Comment by mountiny** [comment] 2024-09-09 15:52
Merged, we can close this now as there is nothing to pay

**Closed by mountiny** 2024-09-09 15:52 UTC
Labels: Reviewing, Engineering, Weekly, Bug
