### ISSUE TITLE
Pay elsewhere button is shown after deleting requested money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23966] opened 2023-07-31 22:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request money to User B
2. Go to the thread on the requested money and send any message
3. Now delete the requested money
4. Go to user B and observe that the pay elsewhere button is still there
## Expected Result: 
Pay elsewhere button is not shown
## Actual Result: 
Pay elsewhere button is shown after deleting requested money

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** y 
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/700403b4-e875-4313-8808-1e0ceb7a1563

https://github.com/Expensify/App/assets/43996225/38ea3e1c-78f7-4c5f-be1a-8f9fc7efa292

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690839098289709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-07-31 23:02
This is being fixed [here](https://github.com/Expensify/App/pull/23828)

**Comment by luacmartins** [comment] 2023-07-31 23:04
I don't think it's a blocker since this feature is still in development.

**Comment by tjferriss** [comment] 2023-08-01 22:04
I was able to reproduce and am able to pay even though the balance is $0. We can close this out as @luacmartins mentions it's already been identified and a fix is in the works.

<img width="993" alt="Screenshot 2023-08-01 at 15 01 25" src="https://github.com/Expensify/App/assets/8292562/67f15943-8e21-4645-85f4-70463dc8c727">

**Closed by tjferriss** 2023-08-01 22:04 UTC
Labels: Reviewing, Engineering, Daily, Bug
