### ISSUE TITLE
Web - Compose box - When moving the cursor over text using arrows in the console, errors occur

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30596] opened 2023-10-30 16:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29434
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Open any chat and paste an RTL text in the compose box, for example " مثال "
4. Write any word in English
5. Use the arrows to move the cursor to the left to the beginning of the Compose Box

## Expected Result:
When moving the cursor over the text (Arabic+English) using arrows in the console, no errors should occur

## Actual Result:
When moving the cursor over the text(Arabic+English) using the arrows in the console, errors appear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/48c94ba4-0937-4861-ad03-c4e2cbeaca35

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-10-30 16:26
Dupe of #30593

**Comment by NikkiWines** [comment] 2023-10-30 16:58
Yep, looks to be a dupe 👍 will add the appropriate labels to that issue

**Closed by NikkiWines** 2023-10-30 16:58 UTC
Labels: Engineering, Hourly, Bug
