### ISSUE TITLE
[$1000] Chat is not marked as read when receiving messages while in the report

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#23733] opened 2023-07-27 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

On mobile
1. User A: Open chat with user B
1. UserB: Send message into chat with user A
1. User A: Go back from chat to chat list.

## Expected Result:
Describe what you think should've happened

The chat should be marked as read

## Actual Result:
Describe what actually happened

The chat will still appear as unread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hannojg 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fb57ede1a93ebb92</li>
        <li>Upwork Job ID: 1684558218046046208</li>
        <li>Last Price Increase: 2023-08-17</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-07-27 13:42
Follow up to https://github.com/Expensify/App/pull/23729

**Comment by Talha345** [comment] 2023-07-27 22:09
## Proposal

Note: I was able to reproduce this issue on Web too, so it was not only on mobile.See below video.


https://github.com/Expensify/App/assets/36226639/60a56d04-33b6-4579-a273-2ede3230a907


### Please re-state the problem that we are trying to solve in this issue.

When a user has a report opened and a new message is received, the message is not marked as read.

### What is the root cause of that problem?

The RC of this issue is the following function logic as it is the entrypoint of any newly received message in a report. Whenever a new message is received, this function is triggered and it calculates if a notification should be shown to the user for that message or not using the `shouldShowReportActionNotification` method which acts as a guard clause.

https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#L1534-L1549

Further down we can see the call to the method `notifyNewAction` , which executes the callback [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.js#L155-L179) which is responsible for performing certain actions including marking the message as read [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionsView.js#L169).

If the guard clause mentioned above prevents the notification to be sent to the user, the function returns and `notifyNewAction` method is never called which in turn never calls the callback responsible for marking the message as read and is also the single source of truth for the "new action" event.

### What changes do you think we should make in order to solve the problem?

The call to the `notifyNewAction` method should be place before the guard clause such that it is always executed irrespective of that a notification should be sent to the user or not.The updated code should look like this:

```
function showReportActionNotification(reportID, action) {
    notifyNewAction(reportID, action.actorAccountID, action.reportActionID);
    
    if (!shouldShowReportActionNotification(reportID, action)) {
        return;
    }

    Log.info('[LocalNotification] Creating notification');
    LocalNotification.showCommentNotification({
        report: allReports[reportID],
        reportAction: action,
        onClick: () => {
            // Navigate to this report onClick
            Navigation.navigate(ROUTES.getReportRoute(reportID));
        },
    });
}
```


### What alternative solutions did you explore? (Optional)

N/A

**Comment by hannojg** [comment] 2023-07-28 06:47
@Talha345 Can you please check if you are still able to reproduce on web, when having the changes from these PR in your branch:

- https://github.com/Expensify/App/pull/23729

I believe you haven't. I think when making the proposal its important to be up to date with the latest state of the branch.

**Comment by Talha345** [comment] 2023-07-28 08:42
> @Talha345 Can you please check if you are still able to reproduce on web, when having the changes from these PR in your branch:
> 
> - https://github.com/Expensify/App/pull/23729
> 
> I believe you haven't. I think when making the proposal its important to be up to date with the latest state of the branch.

@hannojg my local branch was updated with main and I had the changes from this PR of yours while testing.

**Comment by Talha345** [comment] 2023-07-28 10:07
@hannojg I am also able to reproduce this on STG web.See attached video below.

The RC of this bug has nothing to do with your changes and I have explained that in detail in my proposal [here](https://github.com/Expensify/App/issues/23733#issuecomment-1654649490).Also took me a while to get to the RC 😅

https://github.com/Expensify/App/assets/36226639/334cf33e-d485-4261-9e1b-26c484e11d98

**Comment by hannojg** [comment] 2023-08-04 07:33
Hey, I think this needs to be retested on the latest staging / production version!

**Comment by Talha345** [comment] 2023-08-04 10:20
@hannojg Reproduced on latest staging just now.

https://github.com/Expensify/App/assets/36226639/c3248c05-3e04-4fb2-9195-95c6b493c87e

**Comment by Talha345** [comment] 2023-08-06 16:39
@fedirjh Pretty strange because I am able to reproduce on the same version of STG.I tried it with a new account but couldn't reproduce on it so I am guessing it is some specific edge case.

https://github.com/Expensify/App/assets/36226639/03813b48-bda3-49aa-a2b9-7031d67a0e6b

**Comment by sonialiap** [comment] 2023-08-14 18:47
I can still reproduce this issue

**Comment by Talha345** [comment] 2023-08-14 18:57
@sonialiap @fedirjh I have shared a working proposal above.Can you please check it?

**Comment by Talha345** [comment] 2023-08-14 19:54
> cc @sonialiap I am unable to replicate in `v1.3.53-2` on web, could you please reassign another C+
> 
>  CleanShot.2023-08-14.at.20.20.55.mp4

@fedirjh have you tried using 2 devices like web and mobile and sending messages?

**Comment by Talha345** [comment] 2023-08-14 21:17
@fedirjh @sonialiap I tested again and was also able to reproduce on both web and mobile consistently.


https://github.com/Expensify/App/assets/36226639/fa06579d-ac0d-4f88-82bf-2a40c3ccc203

**Comment by sonialiap** [comment] 2023-08-17 22:05
Reassigned C+ per the request https://github.com/Expensify/App/issues/23733#issuecomment-1677933368

**Comment by hannojg** [comment] 2023-08-21 07:31
Hm okay, will double check! You are using the original reproduction steps or any other ones?

**Comment by Talha345** [comment] 2023-08-21 07:51
> Hm okay, will double check! You are using the original reproduction steps or any other ones?

Yes, I am using the reproduction steps mentioned in this issue and have also shared multiple videos in the comments above.You can also see my [proposal](https://github.com/Expensify/App/issues/23733#issuecomment-1654649490) as to what I think is causing this problem.

**Comment by situchan** [comment] 2023-08-21 13:29
@Talha345 can you test again on latest main? I am also not able to reproduce.
Please explain in root cause why this is sometimes reproducible but sometimes not?

**Comment by Talha345** [comment] 2023-08-21 13:31
> @Talha345 can you test again on latest main? I am also not able to reproduce.
> Please explain in root cause why this is sometimes reproducible but sometimes not?

@situchan Okay,I will update in a few hours.

**Comment by Talha345** [comment] 2023-08-21 17:58
@situchan I am no longer able to reproduce this on either platform in dev on latest main but I am still able to reproduce it on STG.Lets wait a day or two and we can test again on STG to see if the issue is no longer present.

**Comment by sonialiap** [comment] 2023-08-28 13:05
I cannot reproduce on staging or production either. Seems like the issue is resolved

Please reopen if the issue shows up again

**Closed by sonialiap** 2023-08-28 13:05 UTC
Labels: Daily, Internal, Overdue, Bug
