### ISSUE TITLE
[Guided Setup Stage 2] - Error shows up when onboarding tasks are created in Concierge chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46614] opened 2024-07-31 21:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new account.
3. Click Chat and split expenses with friends.
4. Must repeat Step 2 and 3 until the onboarding tasks are created in Concierge chat (user ID that ends with even number) and not Expensify.

## Expected Result:
Onboarding tasks will be created in Concierge chat without issue.

## Actual Result:
Error shows up when onboarding tasks are created in Concierge chat.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d9650fd6-dcab-4dda-8c53-d2402ba60201

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-07-31 21:52
We think that this bug might be related to  #vip-vsb

**Comment by Beamanator** [comment] 2024-07-31 23:18
I believe Guided Setup Stage 2 is #wave-collect

@francoisl you're leading this? https://github.com/Expensify/Expensify/issues/356685 any ideas which PR may have caused this? It looks like a backend thing but could be caused by front-end params maybe

**Comment by Beamanator** [comment] 2024-07-31 23:22
Also maybe @marcochavezf could know since this was recently merged & seems related? https://github.com/Expensify/Web-Expensify/pull/42307 (though the issue supposedly isn't reproducible in prod)

**Comment by francoisl** [comment] 2024-08-01 01:51
Hm weird, yes this is related to Guided Setup Stage 2, but all that code has been live for quite some time now. Were you able to repro in dev?

**Comment by francoisl** [comment] 2024-08-01 01:53
I can reproduce in dev, seeing an `402 Invalid task type addBankAccount` in the logs. I see where it comes from, trying to track where it came from 👀

**Comment by francoisl** [comment] 2024-08-01 01:56
This is from https://github.com/Expensify/App/pull/46359, the task `enableWallet` was renamed to `addBankAccount` but we also check the name of the tasks in the backend, so it needed to be changed there too. I don't know how the tests passed in that PR 🤔

**Comment by francoisl** [comment] 2024-08-01 02:07
I suggest we revert that PR for now to unblock the deploy because it will require backend changes that can't be cherry-picked.

**Comment by Beamanator** [comment] 2024-08-01 04:51
Requested CP for revert 🙏  thanks for making that, @francoisl !

**Comment by mollfpr** [comment] 2024-08-01 07:04
Thank you, @francoisl @Beamanator for taking care of this! I did see this error while reviewing the PR, but it also working sometimes so I thought it's temporary and currently being handle internally 🙏

**Comment by Beamanator** [comment] 2024-08-01 15:55
Revert is on staging! Time to test!

**Comment by Beamanator** [comment] 2024-08-01 17:02
Seems to be working well on staging! Thanks for the help @francoisl !

**Closed** 2024-08-01 17:02 UTC
Labels: Engineering, Weekly, Bug
