### ISSUE TITLE
[$500] Web - ave the world: Hmm... it's not here when reloading the page after creating the #teacher-unit room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27454] opened 2023-09-14 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click Save the world
4. Click I know a teacher
5. Create a teacher unit
6. Click the header from the teacher unit
7. Reload the page
8. Wait and observe the result

## Expected Result:
The Hmm... It's not here page shouldn't appear

## Actual Result:
The Hmm... It's not here page appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e5f58999-05ad-44d0-bac7-966dbad77ce8

https://github.com/Expensify/App/assets/93399543/dbc8a4a4-2e44-4a7f-b3a5-81bcb00dc74d

**Expensify/Expensify Issue URL:**
**Issue reported by:** https://expensify.slack.com/archives/C049HHMV9SM/p1694061131439169
**Slack conversation:** @misgana96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0183fa65ac686f749f</li>
        <li>Upwork Job ID: 1706676739868602368</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by iamuddeshya** [comment] 2023-09-14 19:58
# Proposal

## Please re-state the problem that we are trying to solve in this issue.
Hitting refresh triggers the "The Hmm... It's not here page appears" from the teacher unit. 

## What is the root cause of that problem?
When you refresh the page being on the Teacher Unit Details Sidebar, An `"OpenReport"` write API is called. On this API being called, the backend is returning 403, which means _'403 forbidden — you don't have permission to access this resource'_  . [ See attached screenshot ]
![image](https://github.com/Expensify/App/assets/19757182/68706152-d2cb-42fe-a8f2-ec01ad42e2ef)

On receiving this error, the function `applyHTTPSOnyxUpdates` handles it as a failure condition, hence the frontend considers that the user does not have access and shows the "The Hmm... It's not here page appears" page. 

https://github.com/Expensify/App/blob/954c66ded309b1a11f87424b77b9a451ff338010/src/libs/actions/OnyxUpdates.ts#L35-L37

## What changes do you think we should make in order to solve the problem?
The backend must not return a 403 for this request. 

## What alternative solutions did you explore? (Optional)
On frontend we can better manage the call of the `OpenReport` API.

**Comment by marcochavezf** [comment] 2023-09-15 02:55
Assigning myself here to track this bug

**Comment by GianlucaMina** [comment] 2023-09-17 21:01
Contributor details
Your Expensify account email: gianlucamina.gnm@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/gianluca

**Comment by abekkala** [comment] 2023-09-18 14:18
@eVoloshchak have you had a chance to review the proposal?

**Comment by eVoloshchak** [comment] 2023-09-18 17:43
@abekkala, I agree with @iamuddeshya's assessment, this is a back end issue
Could you make this internal so an engineer is assigned?

**Comment by iamuddeshya** [comment] 2023-09-20 12:33
> @abekkala, I agree with @iamuddeshya's assessment, this is a back end issue Could you make this internal so an engineer is assigned?

Is there anything I need to do? What's next for me?
Can help with backend if required. 🙂

**Comment by abekkala** [comment] 2023-09-20 14:21
@eVoloshchak and @iamuddeshya 
@marcochavezf is an internal engineer already assigned

@marcochavezf do you agree this should be moved to internal for you to fix?

**Comment by iamuddeshya** [comment] 2023-09-25 09:00
@abekkala Is the bounty claimable if this issue is to be moved to backend to be fixed?

**Comment by abekkala** [comment] 2023-09-27 05:46
@iamuddeshya 

> Is the bounty claimable if this issue is to be moved to backend to be fixed?

Yes, the [$50] reporting payout still applies!

**Comment by marcochavezf** [comment] 2023-09-29 05:24
No update

**Comment by marcochavezf** [comment] 2023-10-03 05:39
No update, focused on wave7 and traveling back home

**Comment by marcochavezf** [comment] 2023-10-05 19:07
I'm swamped with other high-priority items, I will come back to this one tomorrow

**Comment by marcochavezf** [comment] 2023-10-09 14:41
No update, but prioritizing this one for this week

**Comment by marcochavezf** [comment] 2023-10-11 20:52
Still wrapping up some priorities for wave7, no update

**Comment by marcochavezf** [comment] 2023-10-12 19:39
No update, tackling one issue by one

**Comment by marcochavezf** [comment] 2023-10-13 18:30
No update, focused on TU launch

**Comment by marcochavezf** [comment] 2023-10-16 20:39
No update

**Comment by marcochavezf** [comment] 2023-10-18 02:26
No update

**Comment by marcochavezf** [comment] 2023-10-21 00:40
No update

**Comment by marcochavezf** [comment] 2023-10-24 00:34
No update

**Comment by marcochavezf** [comment] 2023-10-26 18:40
No update

**Comment by marcochavezf** [comment] 2023-10-27 21:34
No update

**Comment by marcochavezf** [comment] 2023-10-30 19:30
No update

**Comment by marcochavezf** [comment] 2023-11-02 18:59
No update

**Comment by marcochavezf** [comment] 2023-11-06 20:13
No update

**Comment by marcochavezf** [comment] 2023-11-08 16:27
Moving this to weekly, swamped with other dailies.

**Comment by marcochavezf** [comment] 2023-11-20 19:54
No update

**Comment by abekkala** [comment] 2023-11-22 21:48
I'm heading out for the Thanksgiving holiday and will be back bright and early Monday morning.

**Comment by marcochavezf** [comment] 2023-11-30 17:06
No update

**Comment by abekkala** [comment] 2023-12-19 20:33
@marcochavezf  I'm going ooo though Jan 03.
I don't think there will be much movement through then so I'm keeping myself assigned as by the time I return this probably won't be at the payment stage for me to take action.
However, if things progress quickly you can reapply the Bug label to get someone one this to submit payment.
(I'll also be checking in on my GH's while I'm ooo)

**Comment by marcochavezf** [comment] 2023-12-20 19:08
No update

**Comment by marcochavezf** [comment] 2023-12-29 19:11
No update

**Comment by marcochavezf** [comment] 2024-01-09 00:45
Focused on wave issues, no update

**Comment by abekkala** [comment] 2024-01-17 19:01
not overdue. Marco is prioritizing wave issues.

**Comment by marcochavezf** [comment] 2024-01-17 19:40
No update

**Comment by marcochavezf** [comment] 2024-01-29 17:30
No update, focused on wave work

**Comment by marcochavezf** [comment] 2024-02-16 16:57
There were more changes to the public rooms, I'm going to apply the `retest-weekly` label to ensure if it's still an issue

**Comment by mvtglobally** [comment] 2024-02-27 15:32
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2024-02-27 18:20
No longer reproducible, closing it out

**Closed by marcochavezf** 2024-02-27 18:20 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, retest-weekly
