### ISSUE TITLE
Web - IOU - When create from FAB IOU appears on the middle of page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37889] opened 2024-03-07 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.48-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/runs/view/20135&group_by=cases:section_id&group_order=asc&group_id=229066
**Email or phone of affected tester (no customers):** gocemate+balto801@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to FAB> Request money> Manual> Add amount> Next
2. Add user you have no previous conversation with> Complete the request flow

## Expected Result:
Created IOU should appear on the bottom of the page

## Actual Result:
Created IOU appears on the middle of the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/04c86543-325e-472c-8837-66c92fc6bb2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-07 12:24
@adelekennedy  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by godofoutcasts94** [comment] 2024-03-09 16:50
This is non reproducable on MacOS: Chrome / Safari

**Comment by adelekennedy** [comment] 2024-03-11 22:10
I also can't reproduce this on chrome - closing

**Closed by adelekennedy** 2024-03-11 22:10 UTC
Labels: Daily, Overdue, Bug
