### ISSUE TITLE
[HOLD #227234] [$8000] Mark as Unread functionality not working with offline mode - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11083] opened 2022-09-19 04:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Go any chat
 2. click on any message and mark that message as   unread
 3. kill the app
 4. reopen app and check chat

## Expected Result:
 Chat Should be mark as unread

## Actual Result:
Chat not mark as unread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.99-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/190949830-5a7b8e9d-cbe4-4df0-a9c3-fa2eb6da3f0b.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01f5eb4b76fce52748
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661600613194619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MitchExpensify** [comment] 2022-09-20 23:10
Reproduced, labeling eng to see if external worthy

**Comment by Luke9389** [comment] 2022-09-23 20:03
Interested to see what comes up here. Not sure if we'll get a proposal that fits perfectly but might as well hear some.

**Comment by michaelhaxhiu** [comment] 2022-09-29 13:14
https://www.upwork.com/jobs/~01f5eb4b76fce52748

**Comment by michaelhaxhiu** [comment] 2022-09-29 13:22
Just added/removed that `exported` label to test something. Ignore :)

**Comment by michaelhaxhiu** [comment] 2022-10-03 13:48
Doubled, fyi

**Comment by michaelhaxhiu** [comment] 2022-10-06 17:46
Still waiting for proposals.

**Comment by michaelhaxhiu** [comment] 2022-10-10 13:19
Doubling price again.

**Comment by michaelhaxhiu** [comment] 2022-10-10 13:46
@gadhiyamanan this was hasty of me, and thanks for your quick comment. Let me try to reproduce (something I should've done *before* doubling price again... oopsie daisy 🥀 ).

**Comment by michaelhaxhiu** [comment] 2022-10-10 16:03
Tested and it does appear to be working now. Can we identify which PR fixed this cc @rushatgabhane? Reason I ask if because I'll payout the bug reporting bonus after 7 days of that PR merging to production.

**Comment by michaelhaxhiu** [comment] 2022-11-08 14:30
cc @mvtglobally and @gadhiyamanan  I'm having a hard time reproducing. Are either of you able to reproduce this one still? Mind trying and including a little video?

**Comment by gadhiyamanan** [comment] 2022-11-08 14:46
@michaelhaxhiu not able to reproduce after [this comment](https://github.com/Expensify/App/issues/11083#issuecomment-1273317179)

**Comment by michaelhaxhiu** [comment] 2022-11-08 14:48
Closing this job unless @mvtglobally can reproduce.

**Comment by kbecciv** [comment] 2022-11-08 15:09
Issue is reproducible in Android app with build 1.2.24.4

https://user-images.githubusercontent.com/93399543/200600847-7516a318-d91a-415c-a3dc-0e4037f564ad.mp4

**Reproducible in IOS app with build 1.2.24.4**

https://user-images.githubusercontent.com/93399543/200600938-d0522b1d-f53e-4070-84d6-42c989bbe913.MP4

**Comment by michaelhaxhiu** [comment] 2022-11-08 15:18
Super valid, thank you. I need to try your exact steps on my side.

**Comment by bondydaa** [comment] 2022-11-11 23:35
going to see if I can figure this out so assigned myself.

**Comment by railway17** [comment] 2022-11-12 00:39
### Proposal

1. Reproducable
I could reproduce this issue like below:
 -  `Mark as Unread` issue (video is attached in the issue description).
 -   User name is not changed to bold when user is on LHN page

2. Why the issue is produced?
To know the above 2 issues, we need to focus on 2 problems.

- There are 3 listeners (mainly, don't need to care for keyboardEvent here) that were defined in the `componentDidMount` of `ReportActionsView.js`.
 Actually, this component is the view of the chat history, which will be frozen in the mobile view when LHN is opened.
I think it was wrapped by `Freeze` component before 2 weeks, and freeze condition is `this.props.isSmallScreenWidth && this.props.isDrawerOpen`.
If a component is frozen, no state/props changing will affect to render, but event listeners will be kept to be alive.
(You can see the document [here](https://github.com/software-mansion/react-freeze/issues/8)).

- Another one is that `MarkAsUnread` api parameter has a problem.

3. Solution
 - Need to disable `OpenReport` in the `VisibilityListener` and resolve the `MarkAsUnread` API issue. (issue 1) 
 ```
        this.unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            if (!this.getIsReportFullyVisible()) {
                return;
            }

            // If the app user becomes active and they have no unread actions we clear the new marker to sync their device
            // e.g. they could have read these messages on another device and only just become active here
            this.openReportIfNecessary();
            this.setState({newMarkerSequenceNumber: 0});
        });
```

We don't need to call `this.openReportIfNecessary()` in the `Visibility.onVisibilityChange` because this listener is needed to check the activity of the AppState (active/inactive), but full reports will be collected when `OpenApp` or `ReconnectApp` is called.
`OpenApp` or `ReconnectApp` is called without fail when app is activated.
     We can debug the responses of `OpenApp` or `ReconnectApp` in the middleware (e.g. SaveResponseInOnyx middleware).
     So, don't need to get `reports` inside of this listener and will remove like below. (If we need to keep it, this should be called from the parent component like issue 2 solution)
```diff
  this.unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
            if (!this.getIsReportFullyVisible()) {
                return;
            }

            // If the app user becomes active and they have no unread actions we clear the new marker to sync their device
            // e.g. they could have read these messages on another device and only just become active here

+           // Calling openReportIfNecessary method is not needed in this listener because full reports will be collecetd when +`OpenApp` and `ReconnectApp` are finished.
+            // We can check the response of them inside middleware.
+            //this.openReportIfNecessary();
            this.setState({newMarkerSequenceNumber: 0});
        });
```
Also, I've noticed that `MarkAsUnread` api parameter has a problem.
```
function markCommentAsUnread(reportID, sequenceNumber) {
    const newLastReadSequenceNumber = sequenceNumber - 1;
    API.write('MarkAsUnread',
        {
            reportID,
            sequenceNumber,
        },
        {
```
In this code, `sequenceNumber` is `maxSequenceNumber`.
If we save in this way, all of the getting report commands (`OpenApp`, `ReconnectApp`, `OpenReport`, ...) will return the wrong report, which target report has  `lastSequenceNumber == maxSequenceNumber` even though `MarkAsUnRead` is finished.
I don't know the backend logic, but I think data is saved somewhere after changing the Onyx data.
So, I can resolve this issue by changing like below:
```diff
function markCommentAsUnread(reportID, sequenceNumber) {
    const newLastReadSequenceNumber = sequenceNumber - 1;
    API.write('MarkAsUnread',
        {
            reportID,
-            sequenceNumber,
+            sequenceNumber: newLastReadSequenceNumber,
        },
        {
```
By doing this, I can get the correct `lastSequenceNumber = maxSequenceNumber - 1` after calling MarkAsUnRead -> <Getting Report Commands>.
By doing this, issue 1 will be resolved.

 - Need to call `ReadNewestAction` in the parent level. (issue 2)
 ```
...
              if (this.currentScrollOffset === 0) {
                    **Report.readNewestAction(this.props.report.reportID);**
                    this.setState({newMarkerSequenceNumber: 0});
                } else if (this.state.newMarkerSequenceNumber === 0) {
...
```
Issue 2 is produced because `unsubscribeFromNewActionEvent` is alive and `Report.readNewestAction` is called when user is on LHN page.
So, need to prevent to call of this method when user is on LHN page.
But we can't use any updated props variable when it is frozen.
So, need to call this method in the parent.
I am writing code like below.
`In the pages/home/ReportScreen.js`
```diff
...
  this.dismissBanner = this.dismissBanner.bind(this);
+  this.readNewestReportAction = this.readNewestReportAction.bind(this);
  this.removeViewportResizeListener = () => {};
....
 chatWithAccountManager() {
        Navigation.navigate(ROUTES.getReportRoute(this.props.accountManagerReportID));
    }

+    /**
+     * read newest reports actions, but will not read when freeze
+     * @param {string} reportID
+     */
+    readNewestReportAction(reportID) {        
+        if (this.props.isSmallScreenWidth && this.props.isDrawerOpen) {
+            return;
+        }
+        Report.readNewestAction(reportID);
+    }

    render() {
...
                {this.isReportReadyForDisplay() && (
                                <ReportActionsView
                                    reportActions={this.props.reportActions}
                                    report={this.props.report}
                                    session={this.props.session}
                                    isComposerFullSize={this.props.isComposerFullSize}
                                    isDrawerOpen={this.props.isDrawerOpen}
                                    parentViewHeight={this.state.skeletonViewContainerHeight}
+                                    readNewestReportAction={this.readNewestReportAction}
                                />
                            )}
...
```
`In the pages/home/report/ReportActionsView.js`
```diff
      // stays in it's previous position.
      if (this.currentScrollOffset === 0) {
-          Report.readNewestAction(this.props.report.reportID);
+          this.props.readNewestReportAction(this.props.report.reportID);
          this.setState({newMarkerSequenceNumber: 0});
      } else if (this.state.newMarkerSequenceNumber === 0) {
          this.setState({newMarkerSequenceNumber: currentLastSequenceNumber});
      }

....
    scrollToUnreadMsgAndMarkReportAsRead() {
         ReportScrollManager.scrollToIndex({animated: true, index: this.props.report.maxSequenceNumber - 
         this.state.newMarkerSequenceNumber}, false);
-         Report.readNewestAction(this.props.report.reportID);
+        this.props.readNewestReportAction(this.props.report.reportID)
    }

```

By fixing the code like above we can get resolved like [here](https://www.dropbox.com/s/t983tmjgglsqo8c/Screen%20Recording%202022-11-11%20at%2012.01.37%20PM.mov?dl=0)

**Comment by JmillsExpensify** [comment] 2022-11-15 03:40
@bondydaa I see you commented before we got a proposal (protip: when you assign yourself, remove the `Help Wanted` label in the future). For now, probably makes just as much sense to have @rushatgabhane review and see where we get.

**Comment by railway17** [comment] 2022-11-15 04:01
> alright this has nothing to do with offline mode. also reproducible whilst online

Yes, correct!

**Comment by michaelhaxhiu** [comment] 2022-11-16 15:39
I'm waiting to proceed with hiring @railway17 until @Luke9389 has had a chance to give his approval too.

**Comment by michaelhaxhiu** [comment] 2022-11-18 18:51
@Luke9389 any chance you can review this today and give the 👍 if you agree?

**Comment by michaelhaxhiu** [comment] 2022-11-18 18:51
Going OOO and re-assigning.

**Comment by Luke9389** [comment] 2022-11-18 21:47
Hey folks, I've carved out some time on Monday to really comb through this flow. I want to know this part of the codebase more intimately before making a call on this one. This behavior has been broken and fixed many times over in the past, so I'm hesitant to pull the trigger on this without absolute confidence. Until then I'm going to put this on HOLD. Thank you in advance for your patience, I know this is a big ticket item.

**Comment by kadiealexander** [comment] 2022-11-21 04:53
@Luke9389, I have a similar issue [here](https://github.com/Expensify/App/issues/12448), since you're diving in are you able to see if it's the same problem causing both behaviours?

**Comment by railway17** [comment] 2022-11-21 13:12
>@Luke9389, I have a similar issue https://github.com/Expensify/App/issues/12448, since you're diving in are you able to see if it's the same problem causing both behaviors?

@kadiealexander , @Luke9389 
I checked and it is a similar issue.
I think you will be notified that my proposal will resolve it too.
Please let me know unless it is resolved.
And, @Luke9389, could you kindly let me know a rough time when you could have confidence? 😸

**Comment by Luke9389** [comment] 2022-11-21 20:37
As I said @railway17 I'll be looking at this flow today.

**Comment by railway17** [comment] 2022-11-22 03:25
@Luke9389, There is another similar issue  #11951 which could be resolved by the above proposal.

**Comment by Luke9389** [comment] 2022-11-22 19:44
Noted, thank you. There were a ton of issues yesterday, so I need some more time on this one.

**Comment by Luke9389** [comment] 2022-11-23 02:15
Hey folks, I know this is not ideal, but I'm going to keep holding this until the end of next week. I need more time to figure out what's going on here and I'll be OOO for the next 4 work days.

**Comment by JmillsExpensify** [comment] 2022-11-29 17:58
That's a great point. I think you're right, it should be held, though more so to Sequence Numbers yeah? vs react navigation?

**Comment by Luke9389** [comment] 2022-11-30 00:42
This is on hold so shouldn't be overdue

**Comment by flodnv** [comment] 2022-11-30 12:01
It honestly looks to me like this and https://github.com/Expensify/App/issues/11515 are near duplicates of eachother. Let's revisit both of them once sequence numbers and react navigation are both done. 

>This is on hold so shouldn't be overdue

@Luke9389 issues on HOLD should not be Daily 😄

**Comment by jliexpensify** [comment] 2022-12-18 22:20
@Luke9389 @rushatgabhane - just a heads up that I'm OOO for the next 2 weeks so if anything needs to be created in Upworks, please re-assign this one :)

**Comment by flodnv** [comment] 2023-06-26 16:45
FWIW there's an ongoing project to revisit the unread marker. I do agree we should at least try reproducing this though, and:
1. If it's not reproducible we close
2. If it's reproducible we HOLD on that project

@jliexpensify

**Comment by jliexpensify** [comment] 2023-06-27 00:40
@flodnv and @rushatgabhane - I've tested on Android v1.3.32-5 and can't repro this: when I disable data/go offline, the Unread Marker is working as intended.

Repro steps:

1. Open app
2. Disable data/go offline
3. Click on chat and mark chat as unread
4. Force close app
5. Enable data again
6. Open app and click on chat
7. Verify same chat is marked as unread

**Closed by jliexpensify** 2023-06-27 00:40 UTC
Labels: External, Engineering, Monthly, Bug
