### ISSUE TITLE
[HOLD for payment 2023-05-29] [$1000] iOS/iPad - Buttons to add attachments, delete workspace, and upload an avatar are unrepsonsive

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19310] opened 2023-05-19 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start iOS / iPad App and login in any account
2. Go to Settings > Profile or Settings > Workspaces > Any workspace > General settings
3. Tap to avatar
4. Tap to 'Upload photo'
===
1. Go to any chat
2. Tap on [ + ] on composer
3. Tap to 'Add attachments'
===
1. Start iOS / iPad App
2. Login with any accounts - gmail or expensifail.
3. Create workspace or goto new workspace.
4. Tap '2 dots' button and tap 'Delete workspace'

## Expected Result:
1. User can select and upload photo for avatar.
2. User can select and upload file in chat.
3. Workspace deleted. User is on the 'Create new workspace' page.

## Actual Result:
1. Nothing happens. 'Upload photo' button is not working.
2. Nothing happens. 'Add attachment' button is not working.
3. The user cannot delete the workspace. After clicking on 'Delete workspace', the application freezes. The workspace is not deleted.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native - iPad
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e6bd5ee4-421e-4789-83d9-250b914ee2aa

https://github.com/Expensify/App/assets/43996225/752c82a5-f616-4bfc-8bc6-eef21862f6e6

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d61f5eb9f4d23355</li>
        <li>Upwork Job ID: 1659749803863924736</li>
        <li>Last Price Increase: 2023-05-20</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-05-20 02:23
Reviewing

**Comment by greg-schroeder** [comment] 2023-05-20 02:32
I reproduced this on an iPad via Browserstack:

https://github.com/Expensify/App/assets/29386373/75edb36a-9c06-48f8-9b52-c00492d6c161

**Comment by greg-schroeder** [comment] 2023-05-20 02:35
Added the unresponsive delete workspace button from https://github.com/Expensify/App/issues/19312

**Comment by AlexanderDmitriev** [comment] 2023-05-20 03:43
## Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Buttons to add attachments, delete workspace, and upload an avatar are unrepsonsive

**What is the root cause of that problem?**
It was passing props for showing modal while animating for dismissing of PopoverMenu like _Delete Workspace_, _Upload Avatar_, _Add Attachment_. So during proceeding for dismissing of PopoverMenu, showing animation of modal was being ignored.

**What changes do you think we should make in order to solve the problem?**
We need to add _timeout_ to show main modal during dismissing PopoverMenu.
![image](https://github.com/Expensify/App/assets/17315937/fc219462-2c6e-4292-a7b6-c209ee063a85)

https://github.com/Expensify/App/assets/17315937/8d280ba2-4854-4c5d-b825-ec85efbd5449

**What alternative solutions did you explore? (Optional)**
None

**Comment by tienifr** [comment] 2023-05-20 11:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
'Upload photo', 'Add attachment',  'Delete workspace' buttons are not working.

### What is the root cause of that problem?
It's here https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/PopoverMenu/index.js#L47 where we're calling `selectedItem.onSelected()` right inside `selectItem`, which is called when the `MenuItem` is pressed. 

For the case of 'Upload photo', 'Add attachment',  'Delete workspace' menu items, when the button is pressed it will open another modal when the current `PopoverMenu` modal doesn't hide completely yet. 2 modals opening at the same time will cause screen freezing in iOS, and the second modal will not show.

This likely comes from [this PR](https://github.com/Expensify/App/pull/18883) where we refactor the `PopoverMenu` from a class component to a function component.

### What changes do you think we should make in order to solve the problem?


We need to call `selectedItem.onSelected` only inside `onModalHide`, which is exactly the approach taken in the class component before the [mentioned PR](https://github.com/Expensify/App/pull/18883) is merged.

We need to:
1. Introduce a new state like `selectedItemIndex` and set it inside here https://github.com/Expensify/App/blob/737862677811acc2b05c68209a56ecd58bee59f3/src/components/PopoverMenu/index.js#LL44C7-L44C7
2. In `onModalHide`, we check if the `selectedItemIndex` is not null, if yes we call the `onSelected` of the menu item
```
props.menuItems[selectedItemIndex].onSelected();
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by tienifr** [comment] 2023-05-20 11:43
I’m happy to open a PR immediately if assigned.

**Comment by tienifr** [comment] 2023-05-20 12:21
sure I’ll get a PR up now 💪

**Comment by tienifr** [comment] 2023-05-20 13:51
@rushatgabhane The PR is ready for review!

**Comment by greg-schroeder** [comment] 2023-05-22 10:27
PR on staging

**Comment by greg-schroeder** [comment] 2023-05-25 00:33
@puneetlath @rushatgabhane - Can either of you clarify why this was deployed twice (thus creating two automated Melvin payment hold/checklist posts?) I'm sure it's something obvious but I couldn't really tell looking at the PR

**Comment by mountiny** [comment] 2023-05-25 06:07
I believe this is a bug when we CPed the PR to staging, speeding up the deployment process. i saw it happen couple of times but the logic there is quite finicky to try to fix this.

You can take the earlier date as valid here

**Comment by greg-schroeder** [comment] 2023-05-26 12:57
Word, thanks Vit!

**Comment by greg-schroeder** [comment] 2023-05-30 08:47
Working on finalizing this one today (back from holiday)

**Comment by greg-schroeder** [comment] 2023-05-30 11:52
That is ... weird. I will try again.

**Closed** 2023-05-30 13:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
