### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Request money - Tabs disappear when navigating with Tab key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26326] opened 2023-08-30 19:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify,com
2. Go to + > Request money
3. Navigate to the buttons in Request money modal using Tab key on the keyboard

## Expected Result:
The tabs do not disappear

## Actual Result:
The tabs disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/bb44cc50-2534-44dc-9d09-33217fbad073

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0163bcce77597627a1</li>
        <li>Upwork Job ID: 1699156588272672768</li>
        <li>Last Price Increase: 2023-09-26</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-08-31 02:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In request money page, tabs disappear when pressing tab key

### What is the root cause of that problem?

When tab key is pressed, the focus is moved to the next focusable element. We have several focusable elements in the money request page, such as amount input in amount page, `Choose file` button in scan page, etc. When focus is moved, the whole tab navigator elements moves to the page.

![image](https://github.com/Expensify/App/assets/126839717/cfdeaa05-8db7-4a0c-83c2-e81fe6bf6029)

This is the root cause.

### What changes do you think we should make in order to solve the problem?

We can disable the tab key event in the money request page. We have already `addKeyDownPressListner` function defined [here](https://github.com/Expensify/App/blob/main/src/libs/KeyboardShortcut/KeyDownPressListener/index.js)

Add the following code in [MoneyRequestSelectorPage](https://github.com/Expensify/App/blob/main/src/pages/iou/MoneyRequestSelectorPage.js)
```
    useEffect(() => {
        const handler = (event) => {
            if (event.code !== CONST.KEYBOARD_SHORTCUTS.TAB.shortcutKey) {
                return;
            }
            // event.preventDefault();
        };
        addKeyDownPressListner(handler);

        return () => removeKeyDownPressListner(handler);
    }, []);
```

This can fix the issue

<details>
    <summary>Result</summary>

https://github.com/Expensify/App/assets/126839717/9c21f05e-1038-46d6-bc9a-67ed4ff3beca

</details>


### What alternative solutions did you explore? (Optional)
We can add `tabIndex: -1` style to all focusable elements, but I don't think this is a good choice because there are so many focusable elements

**Comment by alexpensify** [comment] 2023-09-01 22:55
@cristipaval - Can you confirm if we need to put this one on hold or we should close based on @bernhardoj's feedback that this is an RN issue? Thanks!

**Comment by cristipaval** [comment] 2023-09-04 12:42
yes it seems that the linked RN issue is relevant to our issue. But I am curious what a C+ would say about _skipping_ the issue with the [proposal](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699) that we have.

**Comment by alexpensify** [comment] 2023-09-04 15:28
@cristipaval - are you suggesting assigning C+ to review or start a convo in that Slack room for a larger discussion?

**Comment by cristipaval** [comment] 2023-09-04 17:29
I'm suggesting assigning a C+ to keep the conversation here.

**Comment by alexpensify** [comment] 2023-09-05 20:25
@situchan - please review @cristipaval's thoughts here: 

https://github.com/Expensify/App/issues/26326#issuecomment-1705207247

Let's figure out if this proposal will fix the issue or if we need to hold off until the RN issue is resolved. Thanks!

**Comment by alexpensify** [comment] 2023-09-07 19:36
@situchan any update here?

**Comment by situchan** [comment] 2023-09-07 19:41
Agree this is upstream issue.
We can let contributor fix in upstream or SWM agency fix the issue.

**Comment by alexpensify** [comment] 2023-09-11 22:15
@cristipaval - based on @situchan, should we keep this open for proposals or get SWM involved now?

**Comment by cristipaval** [comment] 2023-09-13 09:43
> Agree this is upstream issue. We can let contributor fix in upstream or SWM agency fix the issue.

@situchan I'm not sure I get what you're saying here. The contributor's [suggestion](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699) is to add a workaround in our code to skip the upstream issue. On the other hand, I wouldn't consider this issue a blocker and I think we can wait longer for an upstream fix.

Curious what @AndrewGable @mountiny @neil-marcellini thoughts are, they have more context about this page.

**Comment by situchan** [comment] 2023-09-13 10:12
> > Agree this is upstream issue. We can let contributor fix in upstream or SWM agency fix the issue.
> 
> @situchan I'm not sure I get what you're saying here. The contributor's [suggestion](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699) is to add a workaround in our code to skip the upstream issue. On the other hand, I wouldn't consider this issue a blocker and I think we can wait longer for an upstream fix.

yes, I meant contributor fork upstream repro and submit PR. Once the fix is deployed, we can simply bump repo version in app PR. This is general process of upstream issue fix.
But as react-navigation is maintained by SWM team, it might be better for SWM agency to be contributor here.

**Comment by mountiny** [comment] 2023-09-13 10:37
Can you bring this up in open source channel with what the problem is in the react navigation, then we can get SWM or Callstack in

**Comment by alexpensify** [comment] 2023-09-15 00:33
@situchan - I'm catching up from being OOO. Did you start a Slack chat? If no, I can do so. Thanks for the update!

**Comment by situchan** [comment] 2023-09-15 04:14
@alexpensify that would be great if you can create thread. Thanks

**Comment by alexpensify** [comment] 2023-09-18 18:38
Slack convo is here: https://expensify.slack.com/archives/C01GTK53T8Q/p1695062095527169

**Comment by alexpensify** [comment] 2023-09-21 18:00
I've bumped the Slack convo to identify if there is a viable workaround. If not, I think we close this one and it will need to be resolved in react-navigation.

**Comment by alexpensify** [comment] 2023-09-25 08:28
I've bumped the thread since it looks like we are leaning towards disabling.

**Comment by situchan** [comment] 2023-09-25 09:39
I will see if we can find better solution not to prevent tab completely.

**Comment by cristipaval** [comment] 2023-09-25 15:22
Thanks a lot @alexpensify for pushing this! So this is on you now, @allroundexperts. You'll review the proposals, correct?

**Comment by situchan** [comment] 2023-09-25 15:23
I am reviewing proposals

**Comment by alexpensify** [comment] 2023-09-26 05:15
Summary from the Slack discussion: 

>Let's plan on disabling the tab for that page instead of leaving it broken until it's resolved in react-navigation.

**Comment by situchan** [comment] 2023-09-26 05:46
I am looking for solution to disable tab (keyboard) only for tabs (navigation), not disabling full page.
So content itself still works like this video:


https://github.com/Expensify/App/assets/108292595/6e43fa5e-5011-4eac-85e5-6603a0ae7ffd

**Comment by s-alves10** [comment] 2023-09-26 08:14
@situchan 

This can be fixed by adding `stopPropgation`, I think

**Comment by situchan** [comment] 2023-09-26 16:10
@s-alves10 on which line to add `stopPropgation`?

**Comment by s-alves10** [comment] 2023-09-26 16:12
I updated the `[proposal](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699)`

**Comment by situchan** [comment] 2023-09-27 11:16
@s-alves10 that still doesn't work as expected. Please test yourelf

**Comment by s-alves10** [comment] 2023-09-27 11:35
@situchan 

It works fine. Can you tell me what doesn't work?

**Comment by situchan** [comment] 2023-09-27 11:37
> @situchan
> 
> It works fine. Can you tell me what doesn't work?

Try https://github.com/Expensify/App/issues/26326#issuecomment-1734867606.
Shift + Tab doesn't work for me

**Comment by s-alves10** [comment] 2023-09-27 12:04
Of course, we can enable Shift + Tab for specific elements like Next button but not sure if it is worth fixing

**Comment by cristipaval** [comment] 2023-10-02 09:51
Discussions are still ongoing here, Melv.

**Comment by alexpensify** [comment] 2023-10-03 23:38
@situchan - should we move forward with this suggestion or continue waiting for proposals here?

**Comment by alexpensify** [comment] 2023-10-06 00:51
@situchan any update here? Thanks!

**Comment by situchan** [comment] 2023-10-06 03:41
was waiting for better solution

**Comment by alexpensify** [comment] 2023-10-06 22:35
Ok, I'll start shopping this GH around for contributors since this is past the 4-week mark.

**Comment by alexpensify** [comment] 2023-10-09 17:20
I'm OOO today but will try to find a contributor tomorrow

**Comment by cristipaval** [comment] 2023-10-12 13:31
Thank you Ana!

**Comment by alexpensify** [comment] 2023-10-13 17:10
@BeeMargarida - I can't find Eto in GitHub but keep us posted on the progress. Tomek mentioned adding them here too, but we will leave this assigned to you only for now.

**Comment by BeeMargarida** [comment] 2023-10-16 08:18
Hi! I still don't have a proposal yet, still investigating. I'm gonna leave here an update of what I've been doing. I've mostly focused on the react-navigation issue for now, it would be great if we could fix it upstream. Eto @teneeto will continue on this issue after today.

**Root cause of the issue:**
The issue only happens if there an interaction component (button or link) in the second or subsequent routes. What happens is when we are clicking on the tab, it will try to focus on the focusable elements. It identifies the focusable element of a route that is hidden, and tries to focus to it. This causes the problematic behaviour where the hidden route is shown and the top bar breaks.

**Possible solutions:**
The first thing that I though would be to force the non focused pages to not be focusable, this means, create a kind of focus trap that does not allow to focus on elements of pages that are not currently being seen by the user.
React native web contains a focusable prop for Views, which basically converts itself into a tabIndex=-1. However, this doesn't work for this specific use case.
Testing in the browser, one thing that fixes it is setting the inert (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) to the outmost view of the non-focused tab. The problem is that react-native-web has no support for this, so there's no way of using in react-navigation.

Still trying to find other workaround/fix.

**Alternate solutions:**
An incomplete solution is to lazy load the non focused tabs
This contains 2 issues: (1) the loading might be slow, (2) the problem persists if we tab again after the loading is done on the other tabs

**Comment by cristipaval** [comment] 2023-10-16 14:14
Thanks for keeping us posted, @BeeMargarida!

**Comment by alexpensify** [comment] 2023-10-19 21:35
@BeeMargarida any update here?

**Comment by BeeMargarida** [comment] 2023-10-20 15:03
Hi! I have no update, I believe @teneeto is currently working on this

**Comment by alexpensify** [comment] 2023-10-20 21:12
Thank you for the update!

**Comment by teneeto** [comment] 2023-10-24 09:07
Hi Alex, I'm helping Ana here. Was attending to another task, but should be able to look in to this now. Sorry for the late responses here.

**Comment by teneeto** [comment] 2023-10-24 09:10
> Hi! I still don't have a proposal yet, still investigating. I'm gonna leave here an update of what I've been doing. I've mostly focused on the react-navigation issue for now, it would be great if we could fix it upstream. Eto @teneeto will continue on this issue after today.
> 
> **Root cause of the issue:** The issue only happens if there an interaction component (button or link) in the second or subsequent routes. What happens is when we are clicking on the tab, it will try to focus on the focusable elements. It identifies the focusable element of a route that is hidden, and tries to focus to it. This causes the problematic behaviour where the hidden route is shown and the top bar breaks.
> 
> **Possible solutions:** The first thing that I though would be to force the non focused pages to not be focusable, this means, create a kind of focus trap that does not allow to focus on elements of pages that are not currently being seen by the user. React native web contains a focusable prop for Views, which basically converts itself into a tabIndex=-1. However, this doesn't work for this specific use case. Testing in the browser, one thing that fixes it is setting the inert (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) to the outmost view of the non-focused tab. The problem is that react-native-web has no support for this, so there's no way of using in react-navigation.
> 
> Still trying to find other workaround/fix.
> 
> **Alternate solutions:** An incomplete solution is to lazy load the non focused tabs This contains 2 issues: (1) the loading might be slow, (2) the problem persists if we tab again after the loading is done on the other tabs

I'll start by exploring other possible solutions. I did talk with Ana once, we looked at a couple of suggested solutions together. I will continue from here.

**Comment by alexpensify** [comment] 2023-10-26 16:54
Thank you @teneeto for the update.

**Comment by alexpensify** [comment] 2023-10-30 23:49
@teneeto any update here?

**Comment by alexpensify** [comment] 2023-11-01 18:37
No update yet

**Comment by teneeto** [comment] 2023-11-02 09:32
Hi, @alexpensify, No Updates yet -  a bit slow because of another investigation. I will try to make out time and provide updates regarding this.

**Comment by alexpensify** [comment] 2023-11-03 16:36
Thank you!

**Comment by cristipaval** [comment] 2023-11-06 14:40
I made this one Weekly for now, as I think it's not a blocker.

**Comment by alexpensify** [comment] 2023-11-09 00:38
Thanks for the update @cristipaval!

**Comment by cristipaval** [comment] 2023-11-20 10:47
bump @teneeto

**Comment by teneeto** [comment] 2023-11-20 12:42
Hi @cristipaval I'm still on this one and will post an update soon.

**Comment by cristipaval** [comment] 2023-11-29 13:38
@teneeto , could we get an update about this one?

**Comment by teneeto** [comment] 2023-11-30 09:32
Hi @cristipaval, My Apologies as I've been kind of trapped in some task switching. On the other I've been looking into the best possible way we can resolve this issue, as I have been trying out different solutions including the ones earlier proposed by @BeeMargarida. 

### Here is my Observation so far.
The issue here is we have a navigation in a modal (on web). Basically, The Tabbing does not work properly in a modal.

_We even have an extra issue to this_ -  Asides Tabs disappearing when navigating with Tab Key, the modal wrapping The Tabs Looses focus and circles through the page beneath the Modal.

### Root Cause of this issue?
- I have tested separately, `Material Top Tabs`, and it works fine on a focused screen, but not when used in a ModalStackNavigator - This leaves me with concerns that this issue could be solved Within `React-navigation`.

### Possible Solution.
- I am looking into how we can trap focus (looking out for a way of restricting focus to tabs that are not focused within a modal).

### Alternative Solution
- Normally in web there is stuff like [focus traps](https://github.com/mantinedev/mantine/blob/master/src/mantine-hooks/src/use-focus-trap/use-focus-trap.ts), but I'm not sure if this is feasible in react-navigation. This will be a good candidate for resolution within react navigation.

### Other Suggestions
- Force tab keys to cycle specific elements in the page in Expensify
  - I think this is dangerous, it breaks accessibility
- Disable Tab keys (this was proposed by another contributor) - not real


### Summary 
I still need a little bit of time to exhaust my options, especially the alternate solution of resolving this within `React Navigation` or trying a trap focus

**Comment by cristipaval** [comment] 2023-11-30 11:04
Thank you for the update, @teneeto!

**Comment by situchan** [comment] 2023-12-18 09:42
Same

**Comment by teneeto** [comment] 2023-12-18 09:48
Hello guys, for a moment i was focused on `Adding Tax Tracking in NewDot `, but I'm back to prioritising this.

Nothing much have changed from my last update.

**Comment by alexpensify** [comment] 2023-12-18 23:53
Thank you for the update!

**Comment by alexpensify** [comment] 2023-12-23 18:49
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by cristipaval** [comment] 2024-01-02 18:03
Any news this week, @teneeto? 👀

**Comment by teneeto** [comment] 2024-01-03 09:07
Hi @cristipaval, I'm still on this. Let me have an update by the end of tomorrow.

**Comment by teneeto** [comment] 2024-01-15 12:40
Hi @cristipaval @alexpensify, I had some discussions and thoughts as well from a colleague at callstack (Satya) and yes, the possible solution to this remains using `focus trap` (_some JS code that traps focus to certain elements_) that restricts focus to this screen. 

I am sure this is same way we could handle similar tab focus issue relating to modals in web. However I'm yet to replicate similar solution for react-native. 

I'm still working on a POC on how this could work for `material-top-tabs`. I'm happy with any further thoughts, assistance or way-to-go on this issue. Thanks...

**Comment by alexpensify** [comment] 2024-01-17 18:32
@cristipaval - let me know if we need to move this to the Open Source room for a bigger discussion. Thanks!

**Comment by alexpensify** [comment] 2024-01-24 17:54
I followed in chat to review the next steps.

**Comment by cristipaval** [comment] 2024-01-24 22:24
> Hi @cristipaval @alexpensify, I had some discussions and thoughts as well from a colleague at callstack (**Satya**) and yes, the possible solution to this remains using `focus trap` (_some JS code that traps focus to certain elements_) that restricts focus to this screen.
> 
> I am sure this is same way we could handle similar tab focus issue relating to modals in web. However I'm yet to replicate similar solution for react-native material-top-tabs.
> 
> I'm still working on a POC on how this could work for `material-top-tabs`. I'm happy with any further thoughts, assistance or way-to-go on this issue. Thanks...

@teneeto I understand here that this possible solution would be fixed in the react-native material-top-tabs, correct?
If yes, then according to [this](https://github.com/Expensify/App/issues/26326#issuecomment-1734844079), I would disable the tab for the page instead of leaving it broken until it's resolved in material-top-tabs, as [this proposal](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699) suggested

**Comment by cristipaval** [comment] 2024-01-24 22:25
Not overdue, Melv

**Comment by teneeto** [comment] 2024-01-25 08:57
> > Hi @cristipaval @alexpensify, I had some discussions and thoughts as well from a colleague at callstack (**Satya**) and yes, the possible solution to this remains using `focus trap` (_some JS code that traps focus to certain elements_) that restricts focus to this screen.
> > I am sure this is same way we could handle similar tab focus issue relating to modals in web. However I'm yet to replicate similar solution for react-native material-top-tabs.
> > I'm still working on a POC on how this could work for `material-top-tabs`. I'm happy with any further thoughts, assistance or way-to-go on this issue. Thanks...
> 
> @teneeto I understand here that this possible solution would be fixed in the react-native material-top-tabs, correct? If yes, then according to [this](https://github.com/Expensify/App/issues/26326#issuecomment-1734844079), I would disable the tab for the page instead of leaving it broken until it's resolved in material-top-tabs, as [this proposal](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699) suggested

Sounds good. I'll work out a temporary solution now.

**Comment by cristipaval** [comment] 2024-01-25 12:16
FYI @alexpensify @situchan , I assigned @s-alves10 to implement the temporary solution ([this proposal](https://github.com/Expensify/App/issues/26326#issuecomment-1700290699)). @teneeto is involved in wave work, and I wouldn't distract him with this for now. Thanks a lot @teneeto for all the investigation you've made here 🙏

**Comment by s-alves10** [comment] 2024-01-25 15:38
@situchan 

PR is ready for review https://github.com/Expensify/App/pull/35154

**Comment by alexpensify** [comment] 2024-01-29 20:36
Awesome, looks like this one is moving forward!

**Comment by alexpensify** [comment] 2024-02-08 00:39
Ok, I have to change the Upwork URL: https://www.upwork.com/jobs/~011b29abee01f46be4

**Comment by alexpensify** [comment] 2024-02-08 00:45
@situchan and @s-alves10 - please accept the job offer in Upwork and I can complete the process. Thanks!

**Comment by alexpensify** [comment] 2024-02-08 15:46
Status Update: 

- @situchan has been paid in Upwork
- Waiting for @s-alves10 to accept the offer in Upwork 

I'll check later to see if I can complete the process and close this GH.

**Comment by alexpensify** [comment] 2024-02-09 16:39
Checking in again, still waiting for @s-alves10 to accept the offer in Upwork. 

I'll check later to see if I can complete the process and close this GH.

**Comment by s-alves10** [comment] 2024-02-12 02:40
@alexpensify I'm sorry. I accepted the offer

**Comment by alexpensify** [comment] 2024-02-12 15:27
It's all good and we are all set here. Everyone has been paid via Upwork. I'm closing this GH and the job is closed in Upwork.

**Closed by alexpensify** 2024-02-12 15:27 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
