### ISSUE TITLE
[Awaiting Payment][$1000] Chat - Google meet opens in new window instead of new tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24288] opened 2023-08-08 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. Click call button in top-right
3. Click Google Meet

## Expected Result:
It should start google meeting in same window but in new tab like Chrome

## Actual Result:
Starts meeting in new window

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/54d6cbf3-f0df-4cc8-8688-ae1396425edb

https://github.com/Expensify/App/assets/43996225/e9bb3453-5024-4402-b516-76e80eb21304

**Expensify/Expensify Issue URL:**

**Issue reported by:** @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690922869306029

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0129c8265c6b7e57ae</li>
        <li>Upwork Job ID: 1688984575738191872</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>Nodebrute | Contributor | 26111248</li>
<li>DinalJivani | Reporter | 26111250</li>
</ul></li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-08-08 18:45
Confirmed on Safari. Chrome opens a new tab so I think we'll want to update this for consistency.

**Comment by ares-dev05** [comment] 2023-08-08 19:32
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
It should start google meeting in same window but in new tab like Chrome
### What is the root cause of that problem?
When you click the Google Meet or Zoom button in the menu, BaseVideoChatButtonAndMenu.js file is running Linking.openURL.
But in React Native, the Linking.openURL() method by default opens the URL in a new tab on web platforms (like React Native Web) and in a new browser window on mobile platforms. There is no built-in way to open a URL in the "same page or tab" using this method as it's designed to protect the user's experience and avoid unexpected navigation.
### What changes do you think we should make in order to solve the problem?
For web, if you're using React Native Web or any library that uses the web's built-in navigation API, you can use the window.location.href  or the window. Open(url, '_self')  method to navigate to a URL in the same tab.

if (Platform.OS === 'web') {
    window.location.href = CONST.NEW_ZOOM_MEETING_URL;
} else {
    Linking.openURL(CONST.NEW_ZOOM_MEETING_URL);
}

![image](https://github.com/Expensify/App/assets/83194791/145e0194-445e-4f48-82ba-6d331784f015)

### What alternative solutions did you explore? (Optional)

**Comment by payal-lathidadiya** [comment] 2023-08-08 19:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Google meet opens in new window instead of new tab

### What is the root cause of that problem?
This seems due to default browser behavior in ios platform.

### What changes do you think we should make in order to solve the problem?
For header context menu's `menuItemData` onPress callback, we should change 
```ts
Linking.openURL(CONST.NEW_ZOOM_MEETING_URL)
```
to
```ts
Link.openExternalLink(CONST.NEW_ZOOM_MEETING_URL)
```

Also apply the same change for Google meet menu item as well.

### What alternative solutions did you explore? (Optional)
None

**Comment by jeet-dhandha** [comment] 2023-08-08 20:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- In Safari Browser, GoogleMeet / Zoom links are not opening in New Tab.

### What is the root cause of that problem?
- By default, Safari browser is opening the GoogleMeet / Zoom links in the new Window. This is the default behaviour of Safari browser.
- Currently user has to set a setting named "Open pages in tabs instead of windows" to "Always" instead of "Automatically", in Safari browser to open the GoogleMeet / Zoom links in the new Tab.

### What changes do you think we should make in order to solve the problem?
- We can update our code to open Link like below which uses window's open method to open the link in new tab.

```js
if (Browser.getBrowser() === CONST.BROWSER.SAFARI) {
    window.open(props.googleMeetURL, '_blank');
} else {
    Linking.openURL(props.googleMeetURL);
}
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by Pluto0104** [comment] 2023-08-09 02:22
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
Linking.openURL(url) opens in new window instead of new tab

## What is the root cause of that problem?
It's Safari's default behavior.

In the Linking component:

```
function openURL(url, target) {
  if (arguments.length === 1) {
    target = "_blank";
  }

  try {
    open(url, target);
    this._dispatchEvent("onOpen", url);
    return Promise.resolve();
  } catch (e) {
    return Promise.reject(e);
  }
}

function open(url, target) {
  if (canUseDOM) {
    var urlToOpen = new URL(url, window.location).toString();
    if (urlToOpen.indexOf("tel:") === 0) {
      window.location = urlToOpen;
    } else {
      window.open(urlToOpen, target, "noopener");
    }
  }
}

```

The problem is `window.open(urlToOpen, target, "noopener");`

## What changes do you think we should make in order to solve the problem?
We need to define a new openLinkOnNewTab function.
For example:

```
function openLinkOnNewTab(url) {
  const open = window.open(url, "_blank");
  if (open == null) {
    alert("Turn off your pop-up blocker!");
  }
}

```

## What alternative solutions did you explore? (Optional)
N/A

**Comment by Pluto0104** [comment] 2023-08-09 02:47
Contributor details
Your Expensify account email: pluto.fed.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0111689310c69ddae7

**Comment by garrettmknight** [comment] 2023-08-11 10:31
@grafaleg Fair point - I still think we want to set this to default to consistent behavior where possible, but that might be a good note to make in the reproduction steps or QA process.

**Comment by Pluto0104** [comment] 2023-08-12 00:49
Contributor details
Your Expensify account email: [fed.dev.pluto@gmail.com](mailto:fed.dev.pluto@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0111689310c69ddae7

**Comment by garrettmknight** [comment] 2023-08-14 10:41
@sobitneupane can you take a look at these proposals when you get a chance?

**Comment by sobitneupane** [comment] 2023-08-14 11:27
Thanks for proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/24288#issuecomment-1670161211) from @Nodebrute looks good to me.

He is proposing to use [`openExternalLink`](https://github.com/Expensify/App/blob/9348d53a098216ce20e66ccd852c3f96a35ba687/src/libs/actions/Link.js#L82). It will result in slight change of behavior, i.e, when offline user won't be redirected to a new tab instead growl will be shown which I think is fine. If we don't want this change, we can add third parameter in [`openExternalLink`](https://github.com/Expensify/App/blob/9348d53a098216ce20e66ccd852c3f96a35ba687/src/libs/actions/Link.js#L82) to not show the growl.

🎀 👀 🎀 C+ reviewed

**Comment by techievivek** [comment] 2023-08-14 12:15
@sobitneupane 
> If we don't want this change, we can add third parameter in [openExternalLink](https://github.com/Expensify/App/blob/9348d53a098216ce20e66ccd852c3f96a35ba687/src/libs/actions/Link.js#L82) to not show the growl.

I think this is fine, given we handle redirecting to the useDot website in a similar way.

**Comment by sobitneupane** [comment] 2023-08-15 05:17
> also, I wanted to gently mention that I identify as female, so 'she' is the correct pronoun 😁

My bad. I am extremely sorry.

**Comment by garrettmknight** [comment] 2023-09-04 09:55
Not sure where this went wrong, but this is fixed and has been for 7 days. I'll process payments now, sorry for the wait!

**Comment by garrettmknight** [comment] 2023-09-04 10:02
**Summary of payments for this issue:**
- #urgency bonus? Yes
- Reporter: @DinalJivani - $250 paid via Upwork
- Contirbutor: @Nodebrute - $1500 paid via Upwork
- Contributor+: @sobitneupane - $1500

Upwork job: https://www.upwork.com/jobs/~0129c8265c6b7e57ae

**Comment by garrettmknight** [comment] 2023-09-04 10:03
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.
- [ ]  [@sobitneupane] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by garrettmknight** [comment] 2023-09-04 10:03
@sobitneupane can you complete the checklist when you get a chance?

**Comment by garrettmknight** [comment] 2023-09-05 15:49
The bug is fixed, melv!

**Comment by sobitneupane** [comment] 2023-09-05 17:46
**Regression Test Proposal**

1. Open a chat in Safari.
2. Click on the phone icon located in the header.
3. Choose either Google Meet or Zoom.
4. Ensure that the link opens in a new tab rather than a new window.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-09-05 18:02
Requested payment on newDot.

https://github.com/Expensify/App/issues/24288#issuecomment-1704978731

**Comment by JmillsExpensify** [comment] 2023-09-10 11:07
$1,500 approved for payment via NewDot based on BZ summary.

**Comment by JmillsExpensify** [comment] 2023-09-10 11:07
Leaving open for regression test.

**Comment by techievivek** [comment] 2023-09-11 11:19
Regression tests https://github.com/Expensify/App/issues/24288#issuecomment-1707044908 looks good to me, @garrettmknight can we please get this added to testRail. Thanks

**Comment by techievivek** [comment] 2023-09-14 09:18
Gentle bump @garrettmknight for adding the [regression test](https://github.com/Expensify/App/issues/24288#issuecomment-1707044908) to testRail.

**Comment by garrettmknight** [comment] 2023-09-14 11:34
Done!

**Closed by garrettmknight** 2023-09-14 11:34 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
