### ISSUE TITLE
[HOLD for payment 2024-05-02] [Guided Setup] [Hold #39687] Onboarding - Font in onboarding flow is cut off when device font size is on the smaller end

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39918] opened 2024-04-09 11:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37733
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to device settings and adjust font to smaller size.
2. Launch New Expensify app.
3. Go to Profile > About > Troubleshoot > 'Navigate' button next to Onboarding flow.
4. Go through the flow.
5. Repeat Step 2 to 4 with different font size (smaller end).

## Expected Result:
The font will not be cut off when the font size is on the smaller end.

## Actual Result:
The font in onboarding flow is cut off when the font size is on the smaller end.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cf5b272d-8ca4-4464-9462-e2bdd85c125f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-04-09 11:53
We think that this bug might be related to #vip-vsb

**Comment by pecanoro** [comment] 2024-04-09 12:19
This bug is minor and probably not a blocker, so I am going to remove the label. However, we probably want this fixed, so I am going to assign the original author.

**Comment by pecanoro** [comment] 2024-04-10 11:49
@mountiny This bug is minor, but it was caused by the onboarding PR. I think ideally, we would want the author to fix it. However, since it's not urgent, should I open it for contributors instead?

**Comment by cdOut** [comment] 2024-04-15 09:27
Hi, I'm Tymoteusz from Software Mansion, the expert agency.

This was a styling issue, we've already fixed it as a part of our [Onboarding - enabled PR](https://github.com/Expensify/App/pull/39687#issuecomment-2052202958).

**Comment by trjExpensify** [comment] 2024-04-15 13:01
Nice, I've put it on hold and the fix can be verified once merged and deployed.

**Comment by pecanoro** [comment] 2024-04-25 13:43
Closing, no need to pay!

**Closed by pecanoro** 2024-04-25 13:43 UTC
Labels: Engineering, Weekly, Awaiting Payment
