### ISSUE TITLE
 iOS/ Android - Payments - Tapping bank account crashes the app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10083] opened 2022-07-25 21:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and login
2. Toggle the staging server
3. Tap payments > bank account

## Expected Result:
User taken to plaid connection flow

## Actual Result:
App is crashed

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android 

**Version Number:** 1.1.86-0
**Reproducible in staging?:**  y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** any
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180878468-67d67c94-03c2-40d5-a00e-caa08d990cea.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by neil-marcellini** [comment] 2022-07-25 21:59
👀

**Comment by neil-marcellini** [comment] 2022-07-25 22:40
I believe #9423 is causing the problem, but I haven't pinned it down exactly yet.

**Comment by neil-marcellini** [comment] 2022-07-25 22:57
Ok, the problem is with the conditional rendering here. @nkuoch 
https://github.com/Expensify/App/blob/dd5a83ec5808cd5f5757b1b114afdce294485499/src/components/AddPlaidBankAccount.js#L151-L155

If `props.plaidData.error` is an empty string then react native will render and empty string, and not the text component. The solution I used was to wrap it in parentheses, but you can also use a ternary statement or `!!props.plaidData.error` to evaluate as a boolean. Easy mistake to make! Here's the SO I used to find this https://stackoverflow.com/questions/52368342/invariant-violation-text-strings-must-be-rendered-within-a-text-component

**Comment by neil-marcellini** [comment] 2022-07-25 23:28
There's something else happening here where the plaid link opens twice, so if you try to close it then the second one remains open in a permanent loading state. I'll see if I can figure it out tomorrow.

**Comment by luacmartins** [comment] 2022-07-26 01:55
Nice investigation so far @neil-marcellini! Let me know if you need any help with this tomorrow!

**Comment by neil-marcellini** [comment] 2022-07-26 17:57
After further investigation it looks like the PlaidLink is rendering with the old `plaidLinkToken` before the token is cleared with [BankAccounts.clearPlaid()](https://github.com/Expensify/App/blob/054045847b49a05b107b6e28d9eea678cf657b87/src/libs/actions/BankAccounts.js#L43). So [openLink](https://github.com/Expensify/App/blob/0f38b9a0107977e2b49edef1534caf1199e08b38/src/components/PlaidLink/index.native.js#L16) is called once with the old token, then `Onyx.set` finishes setting the token to an empty string, and then [openPlaidBankLogin](https://github.com/Expensify/App/blob/054045847b49a05b107b6e28d9eea678cf657b87/src/libs/actions/Plaid.js#L12) returns with the new plaid token, which once again calls `openLink`.

**Closed** 2022-07-26 18:58 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
