### ISSUE TITLE
[$1000] Assignee- Error appears when adding phone number account as Assignee

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19475] opened 2023-05-23 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19335

## Action Performed:
1. Login with any Expensifail account
2. Verify that this account has at least one contact that is an account created by phone number
3. Go to FAB -> Assign Task -> Enter a title and description and navigate to next page
4. Click on the "Assignee" and enter the correct phone number
5. Verify that the account with phone number is added as assignee and no error appears

## Expected Result:
Error should not appeared when adding phone number account as Assignee.

## Actual Result:
Error appears when adding phone number account as Assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/ec7888efd5da4a5ab53d25c7ac2435c076a953e6a5b3b7260677f32ae9b50a8c

https://platform.applause.com/services/links/v1/external/4f84d421bc5f87d23cd8f1d82bc6c49b2caaa6215541f7497a2e25ff24352cf0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01388ffc6e533f7db8</li>
        <li>Upwork Job ID: 1661092904985145344</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-05-23 19:32
I reproduced this, using my own phone number. Interestingly, it didn't work either when I selected the SMS-based user either

<img width="421" alt="image" src="https://github.com/Expensify/App/assets/5802477/55d285bb-92c1-4c2c-87fc-48b0edf43270">


<img width="497" alt="image" src="https://github.com/Expensify/App/assets/5802477/5f81987a-893e-4189-8b16-e062534ee7a0">

**Comment by conorpendergrast** [comment] 2023-05-23 19:33
@yuwenmemon Can you give a quick look and see if you think this should be internal or external? I think it should be internal, but have been wrong before

**Comment by yuwenmemon** [comment] 2023-05-23 19:49
It _looks_ external. Also, cc @cdanwards since this seems to come from your pr here: https://github.com/Expensify/App/pull/17992

**Comment by conorpendergrast** [comment] 2023-05-23 19:52
I live to be wrong. Thanks, I'll switch it to External

**Comment by dukenv0307** [comment] 2023-05-24 03:15
It's duplicate with issue #19203 and out of scope of PR https://github.com/Expensify/App/pull/19335

**Comment by conorpendergrast** [comment] 2023-05-24 07:41
Looks like it's also duplicate of this issue https://github.com/Expensify/App/issues/18649. Closing this out as a result!

**Closed by conorpendergrast** 2023-05-24 07:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
