### ISSUE TITLE
Desktop - Both paid and declined are shown when closing the account of the requested

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20910] opened 2023-06-16 14:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Plus Button
2. Request money
3. Type in the amount and request money
4. Go to another browser and open the requested account.
5. See the requested money
6. Then Close account.

## Expected Result:
When the Money requested account is closed it should only show request declined for the requester account.

## Actual Result:
When the Money requested account is closed it shows request declined and also paid for the requester account.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.25-8

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/1127863/a0c4af17-ad0f-4167-869f-484cd18546f9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686268893659849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-06-21 04:55
Alright, just getting to this one, but I think the video is totally separate from the report. Heading to Slack to figure out what's going on.

**Comment by JmillsExpensify** [comment] 2023-06-28 05:10
Alright, I've updated the correct video at this point.

**Comment by JmillsExpensify** [comment] 2023-06-28 05:12
As for the bug, hmm I think we need to align on what's supposed to happen here, as we should have deprecated decline. I'm confused why it's showing here. @trjExpensify any ideas?

In any case, I tend to think that we should `close` the report, which should remove the GBR from the LHN and at that point there is no required action. The receiving person can just ignore it. I'd guess to clean things up, we'd also remove the pay button in this case and potentially add a system message that so and so closed their account?

**Comment by trjExpensify** [comment] 2023-07-04 13:24
>As for the bug, hmm I think we need to align on what's supposed to happen here, as we should have deprecated decline. I'm confused why it's showing here. @trjExpensify any ideas?

I suspect it's because of the close account command that would previously cancel/decline outstanding money requests. Perhaps @luacmartins work on replacing instances of it with delete hasn't got to this. 

It's an interesting one though now, mainly on the lack of decline or cancel functionality existing in-app going forward. How are we going to handle this? IIRC, the problem surrounding this before was that an iouReport gets unshared once someone closes their account -- so if they had outstanding debts, or reopen it, the old iouReport gets into some weird states with endless spinners and authToken errors. 

Some old context I dug up is [here](https://github.com/Expensify/App/issues/13416#issuecomment-1359285159).

**Comment by JmillsExpensify** [comment] 2023-07-05 12:49
Yeah, agreed. I think we should fit this in overall manual requests clean-up, though it's debatable whether this is a real bug.

**Comment by luacmartins** [comment] 2023-07-10 15:50
I've been replacing these instances with delete. Is that the new expected behavior when closing accounts?

**Comment by JmillsExpensify** [comment] 2023-07-12 13:14
Updated this issue to property reflect that it's not a bug but a result of new, unimplemented features in development.

**Comment by JmillsExpensify** [comment] 2023-07-12 13:15
@luacmartins I think delete is fine for this case.

**Comment by JmillsExpensify** [comment] 2023-07-26 04:38
Still filed in cleanup for wave3

**Comment by JmillsExpensify** [comment] 2023-08-09 16:16
Still on deck for wave3 clean-up.

**Comment by JmillsExpensify** [comment] 2023-08-16 03:48
On the fence whether this is truly LOW priority for wave3. Curious for others thoughts in this issue.

**Comment by luacmartins** [comment] 2023-08-16 14:04
This doesn't happen anymore, BUT I do see a lingering $0 request left behind. I think we should clean this up, but LOW seems correct to me.

**Comment by JmillsExpensify** [comment] 2023-08-22 00:06
@mountiny thoughts from you? I agree with @luacmartins that we should clean this up, though I think it's even lower than a LOW almost. It's only backward looking, right?

**Comment by luacmartins** [comment] 2023-08-25 20:11
I started looking at this again, but I'm unclear on the expected behavior. Asking in our group chat.

**Comment by JmillsExpensify** [comment] 2023-08-30 03:34
Coming from that discussion, I think the most consistent approach is:

 - Delete the outstanding request upon account close
 - Add a system message to the history: `%displayName% deleted this request upon closing their account`

**Comment by luacmartins** [comment] 2023-09-12 02:17
We aligned on the expected behavior, but I haven't been able to prioritize this yet.

**Comment by luacmartins** [comment] 2023-09-21 00:17
Haven't been able to prioritize this yet.

**Comment by luacmartins** [comment] 2023-10-03 16:30
Same as above

**Comment by JmillsExpensify** [comment] 2023-10-12 19:48
Still hasn't been prioritized.

**Comment by luacmartins** [comment] 2023-10-23 18:33
We no longer show the declined message, but the IOU action is still visible with the old amount. We need to update the closeAccount command to call `DeleteMoneyRequest`. That being said, this is not a priority and I haven't been able to prioritize this yet.

**Comment by JmillsExpensify** [comment] 2023-10-24 18:01
Cool, that makes sense to me.

**Comment by luacmartins** [comment] 2023-11-03 17:09
Not a priority

**Comment by JmillsExpensify** [comment] 2023-11-15 16:03
Still not a priority

**Comment by JmillsExpensify** [comment] 2023-11-24 16:52
Still not a priority.

**Comment by JmillsExpensify** [comment] 2023-12-06 04:42
Same, not a priority.

**Comment by JmillsExpensify** [comment] 2023-12-13 05:10
Moving to monthly since we're not prioritizing this

**Comment by luacmartins** [comment] 2024-01-15 17:04
Not a priority

**Comment by luacmartins** [comment] 2024-02-20 00:11
Not a priority

**Comment by luacmartins** [comment] 2024-03-27 00:54
Not a priority

**Closed** 2024-04-08 20:19 UTC
Labels: Engineering, Monthly, NewFeature
