### ISSUE TITLE
iOS - New Room - More space between `#` and `roomname` in the room name creation field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11659] opened 2022-10-07 01:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App
2. Login with expensify account
3. Click on FAB button->New Room
4. Enter the name in the field Room Name

## Expected Result:
There should not be more space between # and room name

## Actual Result:
There is more  space between # and room name

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/194445173-7faf0268-687a-4608-90bb-eb03c60c4c44.jpg" width="40%" height="40%">

https://user-images.githubusercontent.com/43996225/194445174-fcd9eaca-2b3c-48d7-9115-03ddc0c3c891.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dhairyasenjaliya** [comment] 2022-10-07 04:51
**Proposal**

- In order to reduce extra space between `#` and `roomname` we need to reduce paddingLeft from `<BaseTextInput>`
- Here we are adding width according to prefix text and add extra paddingLeft for 4px `StyleUtils.getPaddingLeft(this.state.prefixWidth + styles.pl1.paddingLeft)`
- In order to reduce we need to decrement 4px -> 1px or 2px in below or we can remove completely (not recommended)
- This one will be a global change it will reduce extra space from prefex + textinput

`pl1: {
         paddingLeft: 1,
    },`
    
https://github.com/Expensify/App/blob/0e8fc0274f101453ddeda06158b589b0391e2994/src/styles/utilities/spacing.js#L301-L303

**Results**

<img src=https://user-images.githubusercontent.com/47522946/194470030-eba57360-2ee0-4397-9c9d-e9c55483f231.png  width=50%>


<img src=https://user-images.githubusercontent.com/47522946/194469933-17f2a139-cd49-4969-a9b8-90030f7a7aad.png  width=50%>

**Comment by parasharrajat** [comment] 2022-10-07 16:49
This should be reviewed by design team first.

**Comment by dhairyasenjaliya** [comment] 2022-10-07 17:11
> This should be reviewed by design team first.

Agreed

**Comment by shawnborton** [comment] 2022-10-10 14:29
I think this one has other implications too. For example, I think the chat input on iOS is not vertically centered and thus the text looks like it's shifted towards the bottom too. So I think before we try solving this one in isolation, we should see if there is a bigger problem at hand that needs to be solved for all iOS inputs.

**Comment by shawnborton** [comment] 2022-10-10 14:30
Yup, look how it is pushed down. Perhaps we have another issue open for this? 

![IMG_3988](https://user-images.githubusercontent.com/2319350/194889834-4a9a7286-0e99-4bb7-bbcf-a074e59a9c45.jpg)

**Comment by dhairyasenjaliya** [comment] 2022-10-10 15:14
@shawnborton probably this one you are referring to https://github.com/Expensify/App/issues/10202 ? as this addresses to vertical spacing into text input and this current issue is for horizontal space between prefix - textInput

**Comment by shawnborton** [comment] 2022-10-11 15:12
Ah apologies, taking another look now...

**Comment by shawnborton** [comment] 2022-10-11 15:14
I'm actually just going to go ahead and close this - I don't think this is a bug and this small gap is intended so that there is clear space between the hash and the input.

**Closed by shawnborton** 2022-10-11 15:14 UTC
Labels: Engineering, Daily
