### ISSUE TITLE
[$500] [Wave Collect] [Ideal Nav] Make the header of the workspace list fixed

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#36055] opened 2024-02-07 18:26 UTC
On the Workspace List page (URL: https://new.expensify.com/settings/workspaces), make the header of the list fixed.

The ideas was suggested in [this internal Slack thread](https://expensify.slack.com/archives/C036QM0SLJK/p1707319457925699).

This is a potential pattern that we could adopt across the app wherever we have a list. As we will add another list on the Money page, that new list can also adopt this pettern.

Creating this issue for now so that we can track this in our backlog.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b868d550d02a9a9a</li>
        <li>Upwork Job ID: 1755628933789016064</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-02-08 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We want to make the workspace list header fixed.

### What is the root cause of that problem?
A design change request.

### What changes do you think we should make in order to solve the problem?

To make the header position fixed, we can add `stickyHeaderIndices={[0]}` to the list
https://github.com/Expensify/App/blob/b2a305a82efd39c9f32e46759c5a653ea68c575a/src/pages/workspace/WorkspacesListPage.tsx#L376-L380

Then, we will update the header list style to have a bg color and use padding instead of margin.
https://github.com/Expensify/App/blob/b2a305a82efd39c9f32e46759c5a653ea68c575a/src/pages/workspace/WorkspacesListPage.tsx#L210-L211

`<View style={[styles.flexRow, styles.p5, styles.pl10, styles.appBG]}>`

**Comment by godofoutcasts94** [comment] 2024-02-08 16:35
Can't access Slack Thread

**Comment by hayata-suenaga** [comment] 2024-02-08 19:20
@godofoutcasts94 you don't need access to the Slack thread to understand the requirements of this issue 👍

**Comment by bernhardoj** [comment] 2024-02-09 06:29
PR is ready

cc: @thesahindia

**Comment by mallenexpensify** [comment] 2024-02-13 23:47
Merged yesterday

**Comment by trjExpensify** [comment] 2024-03-05 11:05
What's going on here? Does it need paying?

**Comment by godofoutcasts94** [comment] 2024-03-05 11:13
Is this issue open for proposals ? @trjExpensify

**Comment by bernhardoj** [comment] 2024-03-05 11:17
@trjExpensify yes, it needs paying

**Comment by hayata-suenaga** [comment] 2024-03-06 18:48
maybe we can added another step saying that the tester should shrink the screen vertically or ensure they have enough workspaces to scroll the list

**Comment by mallenexpensify** [comment] 2024-03-10 21:34
Thanks @thesahindia and @hayata-suenaga , TestRail issue created
https://github.com/Expensify/Expensify/issues/377270

**Closed by mallenexpensify** 2024-03-10 21:34 UTC
Labels: External, Daily, NewFeature, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-04-08 03:23
$500 approved for @thesahindia
