### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000]  profile pic does not show in details page if no there is no chat history

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22193] opened 2023-07-04 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. type @ and write email with whom you don't have chat history
3. send that message
4. click on that email to see details
## Expected Result: 
should show profile pic
## Actual Result: 
does not show profile pic

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d4ffb2e8-9bec-41cd-b0cc-c63975e552ba

https://github.com/Expensify/App/assets/43996225/20890a10-75b7-4339-8e51-446f191a86a2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688382917973489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0143734dfc2ac6df2e</li>
        <li>Upwork Job ID: 1677063625717817344</li>
        <li>Last Price Increase: 2023-07-13</li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-07-06 21:14
My initial thought was that maybe we don't want to show profile pictures if the user isn't on your domain, but the profile pic is shown in other apps even if you're not connected and don't have chat history, so I think it's fine to show. Triaging to external

**Comment by mananjadhav** [comment] 2023-07-10 17:27
@honnamkuan I don't understand your solution. I think the issue is:

There's a user A:
1. That has set a profile picture
2. Sender doesn't have a chat history with A.

and when Sender mentions the user, and clicks on the details page the profile picture isn't loaded. I don't think it's about generating a random accountId. @kavimuru Is that correct?

**Comment by kavimuru** [comment] 2023-07-10 21:14
@mananjadhav  the mentioned email has ND account, but does not have chat history before with account logged in.

**Comment by sonialiap** [comment] 2023-07-13 14:14
@mananjadhav what do you think of the updated proposal?

**Comment by sonialiap** [comment] 2023-07-17 18:01
Not overdue, Manan is [traveling](https://expensify.slack.com/archives/C02NK2DQWUX/p1689512159439699) and likely won't be online until tomorrow

**Comment by mananjadhav** [comment] 2023-07-17 20:57
Thanks for the patience here. I saw the [explanation](https://github.com/Expensify/App/issues/22193#issuecomment-1630325513) by @honnamkuan and also the [comment](https://github.com/Expensify/App/issues/22193#issuecomment-1629741625) by @kavimuru.

Hence I think @honnamkuan's proposal [here](https://github.com/Expensify/App/issues/22193#issuecomment-1621253526) is good. 

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-07-26 04:15
I had a hard time pinpointing the offending PR. I did find a commit where this was added [here](https://github.com/esh-g/Expensify/commit/4a12f9c7ddd2a3e88d04bc4b1b7a407b48437e8c). But it looks like this was added while resolving merge conflict. I can't find this change before that conflict being resolved. Hence I am going to tag this [PR commit](https://github.com/esh-g/Expensify/commit/4a12f9c7ddd2a3e88d04bc4b1b7a407b48437e8c).

I don't think any discussion is needed and we don't have any other instance of `UserUtils.getDefaultAvatar()` except for ProfilePage fallback. I also don't think we need a regression test for this one. wdyt @yuwenmemon ?

@sonialiap This is ready for payout today, I'll be raising the request on NewDot, hence can you help with the payout for @honnamkuan ? The timeline bonus applies for this issue.

**Comment by sonialiap** [comment] 2023-07-26 15:51
Thanks Manan 👍 

@gadhiyamanan report ($250) - paid ✔️ 
@honnamkuan fix, bonus ($1500) - paid ✔️ 
@mananjadhav review, bonus ($1500) - via NewDot

**Comment by JmillsExpensify** [comment] 2023-07-27 04:50
Reviewed details for @mananjadhav. This is accurate and approved for payment in NewDot.

**Comment by sonialiap** [comment] 2023-07-27 18:56
@yuwenmemon regression test or no regression test? https://github.com/Expensify/App/issues/22193#issuecomment-1650953060

If no, we can close this issue

**Comment by yuwenmemon** [comment] 2023-07-28 12:10
Close it out!

**Closed by yuwenmemon** 2023-07-28 12:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
