### ISSUE TITLE
[HOLD for payment 2024-04-15] Distance- Blank space above waypoints when transitioning between request and confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39053] opened 2024-03-27 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.57-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Click + > Request money > Distance
4. Enter addresses
5. Click Next
6. Proceed to confirmation page
7. Swipe right to return to previous page.

## Expected Result:
When transitioning between confirmation page and distance request page, there will be no blank space above waypoints in distance request page (production behavior)

## Actual Result:
When transitioning between confirmation page and distance request page, there is blank space above waypoints in distance request page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/78819774/b4490399-219f-4d84-a86c-7829b1b3c5e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-03-27 13:04
@neil-marcellini  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-03-28 04:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance- Blank space above waypoints when transitioning between request and confirmation page

### What is the root cause of that problem?
We are determining the current action based on the 'start' word on the route 

https://github.com/Expensify/App/blob/c4b0bbe66058255ba824d012b13cdd5a3ecfac0d/src/pages/iou/request/step/IOURequestStepDistance.js#L87

It caused the flicker when the route changed

### What changes do you think we should make in order to solve the problem?
We should update like that
```
    const isCreatingNewRequest = !(backTo || isEditing)
```

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-03-28 09:09
@cubuspl42 The PR is ready for review: https://github.com/Expensify/App/issues/39053

**Comment by nkdengineer** [comment] 2024-04-08 09:04
@neil-marcellini The PR is merged. But @DylanDylann used my proposal in his PR. Could I eligible for compensation here?

**Comment by neil-marcellini** [comment] 2024-04-17 20:59
No payment needed to fix a regression.

**Closed by neil-marcellini** 2024-04-17 20:59 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment
