### ISSUE TITLE
[$250] Room - Header markdown is applied for emoji in room description

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#42663] opened 2024-05-27 19:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4575459
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room
3. Tap header -- description
4. Enter # 👍
5. Save the message

## Expected Result:
The description should be changed to '# 👍'

## Actual Result:
The description becomes '👍'. The '#' is automatically removed.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/6d444db7-ee2e-43a8-b8c9-abea81c110b2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012985c67a2ab1760f</li>
        <li>Upwork Job ID: 1795292369265664000</li>
        <li>Last Price Increase: 2024-05-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by kbecciv** [comment] 2024-05-27 19:52
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-05-27 19:53
@Christinadobrzyn FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-05-27 20:36
@dragnoir 

> @kbecciv pls check again, the markdown isn't applied already!

Did you mean to retest again?

**Comment by Christinadobrzyn** [comment] 2024-05-28 03:13
I was able to reproduce this, when you make the description '# 👍' and Save the changes the description becomes '👍'. The '#' is automatically removed.

**Comment by nkdengineer** [comment] 2024-05-28 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The description becomes '👍'. The '#' is automatically removed.

### What is the root cause of that problem?
When we use `# 👍`, the 👍 is parsed as a heading `h1`, so the `#` is removed. This should not happen because when emoji-only is displayed as heading, it will have no difference to normal emoji.

We should not match as `h1` if the header content contains only emojis.

### What changes do you think we should make in order to solve the problem?

In [this rule](https://github.com/Expensify/expensify-common/blob/321e4a7f5e618000be812d5b7dc76d00f81084f9/lib/ExpensiMark.js#L106) we should check if the `g1` value only contains emojis (by stripping all emojis using `<emoji>.*?<\/emoji>` regex, trim it and see if there's any value left), if yes, early return the original value without any replacement.

### What alternative solutions did you explore? (Optional)
Another solution is we do not match the `h1` if the header content contains **any** emoji, we can replace the `only contains emojis` condition above by contains **any** emoji like when we check for the `link` rule [here](https://github.com/Expensify/expensify-common/blob/321e4a7f5e618000be812d5b7dc76d00f81084f9/lib/ExpensiMark.js#L133)

**Comment by mstindia-com** [comment] 2024-05-28 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The description becomes '👍'. The '#' is automatically removed.

### What is the root cause of that problem?
When we use # 👍, the 👍 is parsed as a heading h1 and hense the # is removed.

### What changes do you think we should make in order to solve the problem?
We should modify the regx to not parse if there is Emoji.

Change the following code [here](https://github.com/Expensify/expensify-common/blob/484b980cec748a4f69bb28f00f35e4d0d246b779/lib/ExpensiMark.js#L103) from
```typescript
const regexp = shouldKeepRawInput ? /^# ( *(?! )(?:(?!<pre>|\n|\r\n).)+)/gm : /^# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm;
``` 

to
```typescript
const regexp = shouldKeepRawInput ? /^# ( *(?! )(?:(?!<pre>|\n|\r\n|\p{Emoji}).)+)/gu : /^# +(?! )((?:(?!<pre>|\n|\r\n|\p{Emoji}).)+)/gu;
``` 
I added `\p{Emoji}` to ensure that the regular expression does not match lines containing emojis.

The u flag is added at the end of the regular expression pattern to enable Unicode mode, which is necessary for correctly matching Unicode property escapes like `\p{Emoji}`.

### What alternative solutions did you explore? (Optional)
Yes, we can just add a condition to check for emoji in code and if found return without parsing.

Change code [here](https://github.com/Expensify/expensify-common/blob/484b980cec748a4f69bb28f00f35e4d0d246b779/lib/ExpensiMark.js#L100-L107) from 
```typescript
{
                name: 'heading1',
                process: (textToProcess, replacement, shouldKeepRawInput = false) => {
                    const regexp = shouldKeepRawInput ? /^# ( *(?! )(?:(?!<pre>|\n|\r\n).)+)/gm : /^# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm;
                    return textToProcess.replace(regexp, replacement);
                },
                replacement: '<h1>$1</h1>',
            },
``` 
To
```typescript
{
    name: 'heading1',
    process: (textToProcess, replacement, shouldKeepRawInput = false) => {
  
        const containsEmoji = /[^\x00-\x7F]/.test(textToProcess);
        if (containsEmoji) {
            return textToProcess;
        }

        const regexp = shouldKeepRawInput ? /^# ( *(?! )(?:(?!<pre>|\n|\r\n).)+)/gm : /^# +(?! )((?:(?!<pre>|\n|\r\n).)+)/gm;
        return textToProcess.replace(regexp, replacement);
    },
    replacement: '<h1>$1</h1>',
}

```

**Comment by situchan** [comment] 2024-05-28 20:25
I am not sure this is bug or worth fixing. Is it expected to show markdown or html?
I'd like to hear engineer's thoughts 🎀👀🎀

**Comment by iwiznia** [comment] 2024-05-28 21:30
I don't see why we wouldn't allow emojis there, plus @Christinadobrzyn already oked this issue.

**Comment by Christinadobrzyn** [comment] 2024-05-29 03:01
Hum, I might be missing something with markdown and emojis. I reached out to the team to make sure I'm not missing something about this - https://expensify.slack.com/archives/C01SKUP7QR0/p1716951659784179

**Comment by nkdengineer** [comment] 2024-05-29 10:50
@iwiznia @Christinadobrzyn Emojis in our room description do not have "header" style, the emojis inside header tags show the same as normal emojis, only the `#` will disappear which is confusing and looks buggy. So it shouldn't be parsed as header IMO (unless there's a non-emoji character which will have header style and becomes bold)

**Comment by Christinadobrzyn** [comment] 2024-05-30 02:29
Here's the expected behaviour that our design team would like to see: 

A) We should allow emoji's in room descriptions.
B) We should allow for editing of room description in markdown. That way we can have links etc in details page.
C) We should not render the markdown when it comes to the page header.

Based on these expectations - it sounds like this is behaving as expected, right and shouldn't be fixed? Do I understand that correctly? cc @situchan

**Comment by situchan** [comment] 2024-05-30 04:32
C) We should not render the markdown when it comes to the page header.

This is current behavior so I think nothing to do here.

**Comment by Christinadobrzyn** [comment] 2024-05-31 02:36
I agree, thanks for the buddy check @situchan - closing!

**Closed by Christinadobrzyn** 2024-05-31 02:36 UTC
Labels: External, Daily, Help Wanted, Bug
