### ISSUE TITLE
[$500] Android - Distance - Tabs switch highlight between Manual and Distance when map is rendering

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32554] opened 2023-12-06 10:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.8-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Precondition:
- App location access is denied
- Make sure Distance page is opened when Request money page is opened.

1. Launch New Expensify app.
2. Tap +.
3. Tap Request money.

## Expected Result:
Only the distance tab is highlighted.

## Actual Result:
The tabs switch highlight from Manual to Distance when the map is rendering.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5f658c0f-fd8f-444b-a545-0c02af9b8cda

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015ce5c4e833c5e836</li>
        <li>Upwork Job ID: 1732347541742956544</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-06 15:18
# Proposal

## Please re-state the problem that we are trying to solve in this issue

When opening Request Money on Distance tab, the tabs switch highlight between Distance and Manual while the map is rendering.

## What is the root cause of that problem?

The cause of this issue is the fact that `TabSelector.js` component is re-rendering 6 times because its `state` prop is being passed from the parrent component multiple times even though the `state`'s prop value is the same.

Because the same `state` prop value is passed multiple times to the `TabSelector` component and the component's logic uses the `state` prop to apply selected tab highlight, everytime the component is re-rendered the styles reset for a few `ms` which causes this issue.

## What changes do you think we should make in order to solve the problem?

Wrap `TabSelector` component export with `memo` where we're checking `_.isEqual(prevProps.state, nextProps.state)`. With this applied, the component will only render once and the issue won't occur anymore.

### Changed code

```diff
-       export default TabSelector;

+       export default memo(TabSelector, (prevProps, nextProps) =>  
+           _.isEqual(prevProps.state, nextProps.state),
+       );
```

 ### Videos

<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/56457735/5f9ca018-75da-4cae-8a27-da13074a2643

</details>

**Comment by allroundexperts** [comment] 2023-12-10 18:45
I think @ikevin127 has the correct RCA and the solution proposed seems fine as well. As a suggestion, I think it would be better to memoize the `state` prop in the parent component  (since that is the root cause of the problem) instead of memoizing it in the `TabSelector`. 

Let's go with @ikevin127's [proposal](https://github.com/Expensify/App/issues/32554#issuecomment-1843096884).

🎀 👀 🎀 C+ reviewed

**Comment by allroundexperts** [comment] 2023-12-10 18:56
Just pulled the latest code and retested. This seems to be fixed!

Let's close this.

**Comment by ikevin127** [comment] 2023-12-10 20:33
I agree, the old code related to this issue was prone to future issues.

The refactor did it justice!

**Closed** 2023-12-11 09:45 UTC
Labels: External, Daily, Help Wanted, Bug
