### ISSUE TITLE
[LOW] [Splits] [$500] Individual split amount is inconsistent for manual and scan split bill

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35549] opened 2024-02-01 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4254803
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a group with another two users
2. Create a scan split with a $6.50 receipt
3. Create a manual $6.50 split
4. After scan split is complete, navigate to 1:1 DM with one of the split members

## Expected Result:
Since the split amount for both manual and split scan requests is the same, which is $6.50, the individual split amount should be the same for both types of request

## Actual Result:
The individual split amount for Scan split request is $2.16, while it is $2.17 for Manual split request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8e5bd4a0-1107-48da-841b-c00faf025aa3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01680f4e130a8667a2</li>
        <li>Upwork Job ID: 1753045981654507520</li>
        <li>Last Price Increase: 2024-02-16</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2024-02-05 16:44
@GandalfGwaihir I don't think that is related

**Comment by alitoshmatov** [comment] 2024-02-05 16:46
When opening a 1:1 DM and money request there, backend is sending two different values for scan and manual:

@CortneyOfstad Can we get an internal engineer to take a look at this
<img width="962" alt="Screenshot 2024-02-05 at 21 43 01" src="https://github.com/Expensify/App/assets/59907218/a4853859-bf11-4525-8470-d04b4504b1a4">

**Comment by CortneyOfstad** [comment] 2024-02-05 16:49
Sounds good!

**Comment by CortneyOfstad** [comment] 2024-02-12 13:30
@alitoshmatov No worries, that is what the `hot pick` tag is for. It allows engineers to know that this one is available if they have any free time to snag it 👍

**Comment by CortneyOfstad** [comment] 2024-02-16 20:03
Alright, checked with the team and this can be external, so going to correct the labels. Hopefully we'll get someone to bite, but if not, I'll reach out to CallStack if their team is interested 👍

**Comment by brandonhenry** [comment] 2024-02-16 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The individual split amount is inconsistent between manual and scan split bills, resulting in a discrepancy of $0.01 in the split amount for a $6.50 bill.

## What is the root cause of that problem?
We need to review the code responsible for calculating the individual split amounts in both manual and scan split scenarios. The issue likely lies in the rounding logic or the way the total amount is divided among participants when communicating between the frontend and backend.

**1. Rounding Logic in iouUtils's calculateAmount:**

- The rounding method in `calculateAmount` must be consistent for both scan and manual splits.
- The current rounding method needs a review to ensure it handles edge cases where the split amount does not divide evenly.

https://github.com/Expensify/App/blob/c8826dddb35a401faf35598a9ebc77c760c55335/src/libs/IOUUtils.ts#L33

**2. Currency Conversion Logic in CurrencyUtils:**

- The functions `convertToBackendAmount` and `convertToFrontendAmount` could be introducing rounding errors.
- The discrepancy might occur during the conversion of float to integer or vice versa, especially for currencies with more than two decimal places (which it does seem there is a comment indicating we don't support - are we still receiving that somehow?).

https://github.com/Expensify/App/blob/c8826dddb35a401faf35598a9ebc77c760c55335/src/libs/CurrencyUtils.ts#L81
https://github.com/Expensify/App/blob/c8826dddb35a401faf35598a9ebc77c760c55335/src/libs/CurrencyUtils.ts#L90

### What changes do you think we should make in order to solve the problem?
**1. Review and Update `calculateAmount` Function:**

- Confirm the rounding method matches the desired business logic.
- Ensure that the currency's minor unit (e.g., cents) is correctly factored into the calculations.

**2. Ensure Consistent Conversion Logic:**

- Verify that the conversion logic in `CurrencyUtils` aligns with how the backend expects to receive and send out currency values.
- Adjust any conversion functions to handle currencies with more than two decimal places correctly.

**Comment by CortneyOfstad** [comment] 2024-02-20 14:52
@alitoshmatov thoughts on the proposal above? I have a suspicion that the rounding logic is also affecting this, especially when off by a single cent.

**Comment by brandonhenry** [comment] 2024-02-20 22:09
@CortneyOfstad @alitoshmatov dug deeper on this one

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The individual split amount is inconsistent between manual and scan split bills, resulting in a discrepancy of $0.01 in the split amount for a $6.50 bill. For scan split, the original creator has to pay `2.16` while when doing manual, the original creator has to pay `2.17`

### What is the root cause of that problem?
This is not a problem. In the video, you can clearly see based on the UX steps that you end at the report titled `"THE BOSS" owes MYR 20.48` meaning this is the "request" screen for who has to pay. So this is right, the top image shows the original payer who does have to pay `2.16` and the one on the bottom is `"THE BOSS"`. it doesn't show the scanned imge for them, but that price is related to what they have to pay. 

Does this make sense?

**Comment by mvtglobally** [comment] 2024-02-21 02:29
Issue not reproducible during KI retests. (First week)

**Comment by alitoshmatov** [comment] 2024-02-21 06:19
@brandonhenry Thank you for your proposal but you are not suggesting any meaningful solution.

**Comment by alitoshmatov** [comment] 2024-02-21 06:20
As of my [finding](https://github.com/Expensify/App/issues/35549#issuecomment-1927442800) this is definitely related to backend and cannot be handled by external engineers. 

cc: @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2024-02-22 19:41
Thanks @alitoshmatov! Going to adjust this to internal 👍

**Comment by CortneyOfstad** [comment] 2024-02-26 14:01
Adjusted to show a "unassigned" — hopefully that will get eyes on this 👍

**Comment by CortneyOfstad** [comment] 2024-02-28 15:34
This is considered "Low" Priority, so going to adjust this to Weekly 👍

**Comment by CortneyOfstad** [comment] 2024-02-29 19:57
Hi @miljakljajic! I am heading OoO and will be back March 11th, so reassigned to have someone keep this moving until I am back. At this stage, we're waiting for internal engineers to snag this. Is pretty low priority but wanted to have someone watching just in case. Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-11 17:16
Back from OoO — thanks for holding down the fort @miljakljajic!

**Comment by mvtglobally** [comment] 2024-03-20 03:17
Issue not reproducible during KI retests. (First week)

**Comment by CortneyOfstad** [comment] 2024-03-20 13:11
I am also having trouble recreating this in testing. @alitoshmatov @lanitochka17 is anyone else able to recreate this consistently?

**Comment by CortneyOfstad** [comment] 2024-04-01 13:58
@alitoshmatov @lanitochka17 bump on the comment above ^^^

**Comment by CortneyOfstad** [comment] 2024-04-03 14:04
@alitoshmatov @lanitochka17 bump again — please provide update by EOD today, thank you!

**Comment by alitoshmatov** [comment] 2024-04-03 20:53
Sorry @CortneyOfstad, I was having hard time scanning receipt other days.

I tried now and yes the issue is not reproducible

<img width="417" alt="Screenshot 2024-04-04 at 1 52 23 AM" src="https://github.com/Expensify/App/assets/59907218/2a67eeaf-3c39-462a-9355-96771dd51401">

<img width="380" alt="Screenshot 2024-04-04 at 1 52 18 AM" src="https://github.com/Expensify/App/assets/59907218/63a73dae-9acc-468b-b672-83b2e77a066a">

<img width="382" alt="Screenshot 2024-04-04 at 1 52 08 AM" src="https://github.com/Expensify/App/assets/59907218/0d80752b-1770-4285-b274-0e27189c8322">

**Comment by CortneyOfstad** [comment] 2024-04-09 13:58
No worries @alitoshmatov! Going to close as this is not reproducible 👍

**Closed by CortneyOfstad** 2024-04-09 13:58 UTC
Labels: Engineering, Weekly, Internal, Bug, Hot Pick
