### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500] Focus does not shift directly from  "Manual" option to "Distance" option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27563] opened 2023-09-15 19:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Click on the FAB menu
2. Select "Request money"
3. Choose "Manual > Choose "Distance"
## Expected Result: 
The focus should seamlessly transition to "Distance" option
## Actual Result: 
The focus unexpectedly jumps to "Scan" option

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e88692e0-671f-4cbe-9902-044bcd0c0d76

https://github.com/Expensify/App/assets/43996225/71db4e08-74cb-40c5-86bb-60a727251cfb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694026046030719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a90de5f335cc93e3</li>
        <li>Upwork Job ID: 1702773443318988800</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Contributor | 27116604</li>
<li>aman-atg | Reporter | 27116605</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by ahmedGaber93** [comment] 2023-09-15 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Focus does not shift directly from  "Manual" option to "Distance" option
### What is the root cause of that problem?

https://github.com/Expensify/App/blob/b11bddc054f54bb46d5fb5aaf05e25b8a7df7faf/src/components/TabSelector/TabSelector.js#L76-L86

In `getBackgroundColor` and `getOpacity` we set the background color base on position by `position.interpolate`.
You can notice by slowly swipe tabs like the video


[](https://github.com/Expensify/App/assets/41129870/0b01366f-ad1a-43d5-bcf3-697c821b88d0)





and in this issue case, when we move from the tab index 0 to 2 the tabs swipe horizontal and `position.interpolate` for tab index 1 will be `outputRange: [themeColors.appBG, themeColors.midtone, themeColors.appBG]`, so while the swipe from tab 0 to tab 2 the tab 1 will flicker in the middle

### What changes do you think we should make in order to solve the problem?
I think using `position.interpolate` is not a good idea to use with backgroundColor and opacity when tabs length > 2 because it works good when swipe between tabs and not good from jump between Non-adjacent tabs.

Solution 1: use translateX with `position.interpolate` and this is the good usage of it like whats app, this will work fine swipe and clicks
```javascript
const getTranslateX = (position, routesLength, TabWidth) => {
    const inputRange = Array.from({length: routesLength}, (v, i) => i);
    return position.interpolate({
        inputRange,
        outputRange: _.map(inputRange, (i) => i * TabWidth),
    });
};

function TabSelector({state, navigation, onTabPress, position}) {
    const {translate} = useLocalize();

    const [width, setWidth] = React.useState(0);
    const TabWidth = (width - 40) / state.routes.length;


    return (
        <View onLayout={(event)=> setWidth(event.nativeEvent.layout.width)} style={styles.tabSelector}>
            <Animated.View
                style={{
                    position : 'absolute',
                    width : TabWidth,
                    height : 40,
                    borderRadius : 20,
                    backgroundColor : themeColors.midtone,
                    transform: [{translateX: getTranslateX(position, state.routes.length, TabWidth)}]
                }} />


            {_.map(state.routes, (route, index) => {
           ...
```


https://github.com/Expensify/App/assets/41129870/0dcb8989-2043-454c-af4c-32b2fe40cbe7







Solution 2: use backgroundColor and opacity directly in props, this will work fine in clicks but not affected by slow swipe because there is no `position.interpolate` here

```javascript
<TabSelectorItem
    ...
    activeOpacity={isFocused ? 1 : 0}
    inactiveOpacity={isFocused ? 0 : 1}
    backgroundColor={isFocused ? themeColors.midtone : themeColors.appBG}
/>
```

https://github.com/Expensify/App/assets/41129870/25e2790c-7c0c-46ac-b303-1163f306224d



### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pluto0104** [comment] 2023-09-15 20:00
This is an issue with the tab navigator library. There are numerous problems related to it.
https://github.com/Expensify/App/issues/26407
https://github.com/Expensify/App/issues/26516

**Comment by ahmedGaber93** [comment] 2023-09-15 20:26
@Pluto0104 this issue not related to the mentioned issues above.
This issue when move by clicking the tab bar item from tab 0 to tab 2 the tab 1 is flickering.

**Comment by Pluto0104** [comment] 2023-09-15 20:34
If you don't update the module, you won't be able to fully resolve this issue. Furthermore, your proposed solution is incorrect. It only addresses the tab selector background color. You can observe that the tab content is misaligned when switching from 'manual' to "distance".

**Comment by Pluto0104** [comment] 2023-09-15 20:37
@aldo-expensify @s77rt how do you think about this problem?

**Comment by ahmedGaber93** [comment] 2023-09-15 20:49
> What I meant is that the underlying cause for all these problems is the module issue.

I still disagree with you about this issue root cause, but let us wait for C+ to decide about that.
Thanks!

**Comment by Pluto0104** [comment] 2023-09-15 20:52
Hey @ahmedGaber93, I noticed that I can still see this issue in your video demonstrating your solution.

**Comment by s77rt** [comment] 2023-09-16 00:03
@Pluto0104 I think it's natural that the tab content gets visible for a brief moment since we are passing by it. The tab styling however feels broken, it feels like we go to step 2 stop for a brief moment then continue. The tab animation is from our side so I think we can fix that. The animation provided by @ahmedGaber93 in his first solution looks better but it's missing the opacity.

| Bad | Good |
|-----|------|
|  <img src="https://github.com/Expensify/App/assets/16493223/7e2e455e-7aaa-43a4-a554-c46455cddc29" />    |    <img src="https://github.com/Expensify/App/assets/16493223/c1b55cd1-cb17-4dab-bfc7-3ff27efcf234" /> |

**Comment by sakluger** [comment] 2023-09-18 07:54
> The animation provided by @ahmedGaber93 in his first solution looks better but it's missing the opacity.

@s77rt should @ahmedGaber93 update their proposal to fix the opacity?

**Comment by aldo-expensify** [comment] 2023-09-18 09:56
> @aldo-expensify @s77rt how do you think about this problem?

Thanks @Pluto0104 for helping around.

My opinion on this is that this is not a bug, I don't see a problem with the tab in the middle to become "focused" as we move from Distance to Manual. The example from the library page does exactly that: https://snack.expo.dev/?platform=web


https://github.com/Expensify/App/assets/87341702/70eba3ba-0737-4147-9fd3-723d022e97ff



Or am I getting it wrong what is described here as a bug?

**Comment by ahmedGaber93** [comment] 2023-09-18 10:12
> I don't see a problem with the tab in the middle to become "focused" as we move from Distance to Manual. The example from the library page does exactly

@aldo-expensify I think the example is just a fast demo for explanation, but famous apps don't do that.

**Comment by s77rt** [comment] 2023-09-18 12:30
@aldo-expensify The item being focused is okay I think (or not too much concerning) but the background pill feels broken on our App. In your linked video check the bottom blue bar, it scrolls smoothly, the background pill should do the same instead of partially fading.

Check https://github.com/Expensify/App/issues/27563#issuecomment-1722068523

**Comment by shawnborton** [comment] 2023-09-19 00:07
I think we should just close this out, this is a really poor bug report. There is hardly any detail here. 

For example, in the video, what exactly is happening? Is it just a double click? Or a click? Again, this is just not nearly enough information for any of us to properly understand what's happening here:
<img width="605" alt="image" src="https://github.com/Expensify/App/assets/2319350/adfbe106-bd33-40a5-aed1-bc1fe72f751e">

**Comment by shawnborton** [comment] 2023-09-19 00:08
Ah interesting. I agree that it is weird that the middle tab gets a flash highlight when navigating to the outer tab. @AndrewGable I think you implemented this, any idea what is going on here? 

cc @neil-marcellini as well.

**Comment by shawnborton** [comment] 2023-09-19 00:08
In terms of expected behavior, yes, I would imagine clicking on a tab just highlights the new tab without highlighting the middle tab first

**Comment by AndrewGable** [comment] 2023-09-19 01:33
I do not know if this animation existed when I implemented this initially, so I agree this PR might have added this behavior: https://github.com/Expensify/App/pull/26022

**Comment by sakluger** [comment] 2023-09-21 08:08
It sounds like this is a bug, let's keep it open and fix it.

**Comment by burczu** [comment] 2023-09-25 08:34
@sakluger If we agree this is regression, I think we should assign @allroundexperts to fix it? What do you think?

**Comment by sakluger** [comment] 2023-09-28 07:12
Okay, I'm going to assign @allroundexperts to fix this one. I've also added the engineering label. @allroundexperts please review and let us know if this is a regression from your PR that Andrew [linked above](https://github.com/Expensify/App/issues/27563#issuecomment-1724701039).

**Comment by sakluger** [comment] 2023-10-02 20:18
@burczu sounds like this is not a regression because it's a different action that causes the issue. Mind checking out the proposals we received so far?

**Comment by burczu** [comment] 2023-10-04 11:37
I've just reviewed and tested [the proposal](https://github.com/Expensify/App/issues/27563#issuecomment-1721770104) from @ahmedGaber93 and in general I like it (solution 1 seems to work and the animation looks good). But I agree it needs to be polished by fixing the background opacity pointed out in [this comment](https://github.com/Expensify/App/issues/27563#issuecomment-1722068523).

@ahmedGaber93 Could you update it?

**Comment by ahmedGaber93** [comment] 2023-10-05 08:59
@burczu 
We can do solution 1 for background and solution 2 for opacity, this is looks like WhatsApp, I tested it on native and it looks good in swipe and click, but in web while swipe it seems to have a delay before opacity being active, but we can disable navigator swipe in web and mweb.

If you need to test it in native, add 20 to translateX, and if design accepted, I will focus on the code why it is different on native.
```javascript
// outputRange: _.map(inputRange, (i) => i * TabWidth),
outputRange: _.map(inputRange, (i) => (i * TabWidth) + 20),
```
<details>
<summary>result</summary>


https://github.com/Expensify/App/assets/41129870/076d8e12-4f8c-48c2-972f-d3e3623df087


https://github.com/Expensify/App/assets/41129870/2cf95265-4c52-472c-9232-0290f5a1e93d

in web while swipe it seems to have a delay before opacity being active, but we can disable navigator swipe in web and mweb.
but works fine when clicks.
 

https://github.com/Expensify/App/assets/41129870/4ca449f6-57b2-4ad7-a9c2-7f5e3bfee224



</details>




---

Other solution works fine without change any animation is to define affected tabs in animation and prevent other tab from changing its style.
For example, while we move from tab1 to tab3 by click, the affected tabs is [tab1, tab3] only.

For that we can do the following:
1. the default affected tabs will be all tabs thats for swipe.
2. when tab click set affected tabs [currentTab, clickedTab] and after transition end back affected tabs to default to be all tabs.

[branch](https://github.com/ahmedGaber93/App/commit/362a17f5bd2f80c784ed114b4803ea0547412d38)

<details>
<summary>result</summary>




https://github.com/Expensify/App/assets/41129870/43e42c60-c7b5-4744-bf9b-8a632bd4c0e8




</details>

**Comment by sakluger** [comment] 2023-10-07 03:01
Not overdue, we're making progress.

**Comment by burczu** [comment] 2023-10-09 07:19
@ahmedGaber93 I think your other solution looks good and we could follow it:

> Other solution works fine without change any animation is to define affected tabs in animation and prevent other tab from changing its style.

Is it working correctly on all devices? If so, please update your proposal accordingly. Thank you.

**Comment by ahmedGaber93** [comment] 2023-10-09 07:55
## Proposal
[Updated](https://github.com/Expensify/App/issues/27563#issuecomment-1721770104)

**Comment by ahmedGaber93** [comment] 2023-10-09 07:58
@burczu 
> Is it working correctly on all devices?

Yes, I test it in all platforms and works fine.

**Comment by burczu** [comment] 2023-10-10 07:20
I think [the current proposal](https://github.com/Expensify/App/issues/27563#issuecomment-1721770104) from @ahmedGaber93 looks good and I think we could proceed with it.

🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2023-10-10 09:06
Sounds good, reviewed! Assigning @ahmedGaber93

**Comment by ahmedGaber93** [comment] 2023-10-10 20:17
@burczu PR https://github.com/Expensify/App/pull/29231 is ready for review.

**Comment by sakluger** [comment] 2023-10-27 16:19
I completed payments for @aman-atg and @ahmedGaber93.

@burczu do you mind completing the BZ checklist so we can close the issue? Thanks!

**Comment by sakluger** [comment] 2023-10-31 04:00
Trying to remove overdue, one more comment should do it.

**Comment by burczu** [comment] 2023-10-31 11:35
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **I don't think this is a regression - the animation while switching tabs was just not correctly done since the beginning.**
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **n/a**
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I don't think we need regression test here - the bug wasn't impactful on any important flow of the and it was just UX fix.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@sakluger] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sakluger** [comment] 2023-10-31 23:01
Thanks!

**Closed by sakluger** 2023-10-31 23:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
