### ISSUE TITLE
 IOU - Currency in the amount editor is USD when the request is created in local currency

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40543] opened 2024-04-19 10:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to 1:1 DM.
3. Create a manual request in local currency.
4. Go to transaction thread.
5. Click Amount.

## Expected Result:
The currency in Amount editor should be the local currency,.

## Actual Result:
The currency in Amount editor is USD, when the request is created in local currency.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/95f49bee-4c0c-4803-a28a-02afa03c0fae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-19 10:05
@joekaufmanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-19 10:05
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-04-19 10:06
Production 


https://github.com/Expensify/App/assets/115492554/c79b040c-a514-4f31-985d-2ec3e301aac3

**Comment by nkdengineer** [comment] 2024-04-19 10:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency in Amount editor is USD, when the request is created in local currency.

### What is the root cause of that problem?
We're passing wrong `transaction` data to get the currency here. we should pass is as `transaction` when we're editing instead of `draftTransaction`

https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82
### What changes do you think we should make in order to solve the problem?
Update this line to 

```
const {currency: originalCurrency} = ReportUtils.getTransactionDetails(isEditing ? transaction : draftTransaction) ?? {currency: CONST.CURRENCY.USD};

```
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82



### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-04-19 10:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The currency in Amount editor is USD, when the request is created in local currency.

### What is the root cause of that problem?
We're passing wrong `transaction` data to get the currency here. we should pass it as `transaction` when we're editing instead of `draftTransaction`

https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82
### What changes do you think we should make in order to solve the problem?
Update this line to 

```
const {currency: originalCurrency} = ReportUtils.getTransactionDetails(isEditing ? transaction : draftTransaction) ?? {currency: CONST.CURRENCY.USD};

```
https://github.com/Expensify/App/blob/305f12c52ef228e7ed4845735a1794942a2b8d87/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82



### What alternative solutions did you explore? (Optional)
NA

**Comment by Beamanator** [comment] 2024-04-19 12:43
Oof ya i would say this is a blocker, it's not great to show it's `$100` when it's actually 100 in some other currency 😬

**Comment by Beamanator** [comment] 2024-04-19 14:47
Hmm this one looks pretty sus: https://github.com/Expensify/App/pull/38892

cc @roryabraham @sobitneupane

**Comment by Beamanator** [comment] 2024-04-19 14:53
Posted in slack & tagged ^ those people - https://expensify.slack.com/archives/C01GTK53T8Q/p1713538343234679?thread_ts=1713521084.907369&cid=C01GTK53T8Q

**Comment by bernhardoj** [comment] 2024-04-19 14:59
Hmm, based on @nkdengineer root cause and solution which I already tested, it shouldn't be coming from our PR because we don't change the `isEditing ? draftTransaction : transaction` code/logic.

<img width="1360" alt="image" src="https://github.com/Expensify/App/assets/50919443/7b02d74a-5306-4cbd-b3fa-d9732582a161">

**Comment by bernhardoj** [comment] 2024-04-19 15:11
I think it's coming from https://github.com/Expensify/App/pull/39144. In amount page, we are creating a backup transaction if we are editing a money request.
https://github.com/Expensify/App/blob/4654d6ed3389916e750ecdfdbdad08d637535b8d/src/pages/iou/request/step/IOURequestStepAmount.tsx#L107-L114

`createBackupTransaction` will take the current transaction data and copy it to transactionsDraft, but the PR above changes the name to transactionsBackup.

That's why when we are editing, we pass the draftTransaction instead of transaction to get the data from the backup data.
https://github.com/Expensify/App/blob/4654d6ed3389916e750ecdfdbdad08d637535b8d/src/pages/iou/request/step/IOURequestStepAmount.tsx#L82

Rename the key to transactionsBackup and the issue is fixed.
https://github.com/Expensify/App/blob/4654d6ed3389916e750ecdfdbdad08d637535b8d/src/pages/iou/request/step/IOURequestStepAmount.tsx#L269-L272

`ONYXKEYS.COLLECTION.TRANSACTION_BACKUP`

**Comment by Beamanator** [comment] 2024-04-19 18:57
Thanks @bernhardoj ! I agree it does look like https://github.com/Expensify/App/pull/39144 is the real culprit - they modified `createBackupTransaction` which now updates a new onyx key, and they didn't look where else that function was used & if we needed to subscribe to the new onyx key there (which it looks like we do need to)

**Comment by Beamanator** [comment] 2024-04-19 19:21
Ok I have a PR up for the fix - note I used @bernhardoj 's solution

**Comment by shahinyan11** [comment] 2024-04-20 23:56
My [proposal](https://github.com/Expensify/App/issues/40631#issuecomment-2067772590)  will cover this issue

**Comment by DylanDylann** [comment] 2024-04-21 05:07
@Beamanator @bernhardoj The new field `ONYXKEYS.COLLECTION.TRANSACTION_BACKUP` should only be used in distance requests as explained [here](https://github.com/Expensify/App/pull/39144#issuecomment-2042296642). With the manual request, we should use `draftTransaction` as before.

**Comment by joekaufmanexpensify** [comment] 2024-05-06 13:19
@DylanDylann I see you were already paid for this PR in https://github.com/Expensify/App/issues/40631#issuecomment-2089321279, so I don't think any payment is due here. Closing this out for now, but LMK if you think that is not correct!

**Closed by joekaufmanexpensify** 2024-05-06 13:19 UTC
Labels: Reviewing, Engineering, Weekly, Bug
