### ISSUE TITLE
[HOLD for payment 2023-07-20] [$250] Migrate LogOutPreviousUserPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16238] opened 2023-03-20 08:50 UTC
### Filenames
- [ ] [src/pages/LogOutPreviousUserPage.js](https://github.com/Expensify/App/blob/main/src/pages/LogOutPreviousUserPage.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c913f973d1eef3aa</li>
        <li>Upwork Job ID: 1673398939406794752</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-04-13 21:39
Heads up! The pricing for this issue has been adjusted based on the scope of the work and the fact that no complex bug investigations or proposal are required.

**Comment by alitoshmatov** [comment] 2023-06-06 10:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate LogOutPreviousUserPage.js to function component
### What is the root cause of that problem?
No root cause, just refactoring
### What changes do you think we should make in order to solve the problem?
We should refactor [src/pages/LogOutPreviousUserPage.js](https://github.com/Expensify/App/blob/main/src/pages/LogOutPreviousUserPage.js) to be functional component

### What alternative solutions did you explore? (Optional)

**Comment by muxriddinmuqimov77** [comment] 2023-06-07 02:52
I'd like to work on this.

**Comment by olexyt** [comment] 2023-06-26 19:00
I would like to work on this.

**Comment by akinwale** [comment] 2023-06-26 19:53
I would like to work on this migration task. Thanks.

**Comment by abekkala** [comment] 2023-06-27 19:49
Assigning @Nodebrute as they were the first to comment

**Comment by mallenexpensify** [comment] 2023-06-30 01:38
@Nodebrute hired, welcome aboard! 
@eVoloshchak , please accept https://www.upwork.com/jobs/~01c913f973d1eef3aa

**Comment by abekkala** [comment] 2023-06-30 19:06
@mallenexpensify Unassigning myself for sabbatical as the BZ member here.
Not giving my usual current status summary for this one as you're already assigned and seem up to date!

**Comment by vdem0115** [comment] 2023-07-05 21:23
I can work on this.

**Comment by eVoloshchak** [comment] 2023-07-25 15:08
Requested the payment for this via NewDot
@mallenexpensify, could you settle @Nodebrute's payment when you have time? Thanks!

**Comment by mallenexpensify** [comment] 2023-07-25 21:26
Sorry for the delay @Nodebrute , I was OOO a bit.  Paid via Upwork.  Closing as @eVoloshchak is paid via NewDot

**Closed by mallenexpensify** 2023-07-25 21:26 UTC
Labels: External, Engineering, Daily, Improvement, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-07-27 03:52
@mallenexpensify Can you please summarize the appropriate for all parties involved in this issue? This is holding up @eVoloshchak's NewDot payment. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by mallenexpensify** [comment] 2023-07-27 23:09
Issue reporter: none
Contributor: @Nodebrute $250 (paid via Upwork)
Contributor+: @eVoloshchak $250

**Comment by JmillsExpensify** [comment] 2023-07-29 16:34
Reviewed details for @eVoloshchak. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
