### ISSUE TITLE
[$500] IOU - Receipt in progress font size is big for request scan and small for split bill scan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33649] opened 2023-12-27 17:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon--- request money----Scan 4.Upload receipt
5. Tap request
6. Note the font size of "receipt in progress " is big
7. Tap plus icon--- Split bill----Scan
8. Upload receipt
9. Tap Split
10. Note the font size of "receipt in progress " is small

## Expected Result:
Receipt in progress font size must be consistent throughout the app.

## Actual Result:
Receipt in progress font size is big for request scan and small for split bill scan.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/285fd30f-2818-4661-9d45-516e7d09b4c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed779b5dc41eb203</li>
        <li>Upwork Job ID: 1740069022104629248</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-12-29 16:12
@alitoshmatov any thoughts on these proposals?

**Comment by alitoshmatov** [comment] 2024-01-02 10:18
I am not able to reproduce this issue. Is there any additional steps here

<img width="382" alt="Screenshot 2024-01-02 at 15 12 38" src="https://github.com/Expensify/App/assets/59907218/f3c2e4d6-98bd-4a84-bc11-059ec6d15f85">
<img width="568" alt="Screenshot 2024-01-02 at 15 13 53" src="https://github.com/Expensify/App/assets/59907218/baa1b1ac-fd59-436c-a094-fc2196279941">

**Comment by garrettmknight** [comment] 2024-01-02 18:45
Looks fixed to me too. Closing.

**Closed by garrettmknight** 2024-01-02 18:45 UTC
Labels: External, Daily, Help Wanted, Bug
