### ISSUE TITLE
[HOLD for payment 2024-09-10][$250] [Search v2.1] Selected expense numbers are shown when logging in to another account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47168] opened 2024-08-09 14:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log into an account that have expenses
2. Click on search, found at the bottom
3. Select all the expenses, Notice the selected numbers are shown a the top
4. Log out from the account
5. Log back in with a different account
6. Go to search

## Expected Result:
Selected number is not show

## Actual Result:
Selected number of expenses of the previous account are shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6d5fe55f-8446-4cfa-b92c-d5dfb0436d7e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112a275318e1e1dc4</li>
        <li>Upwork Job ID: 1823627646288296373</li>
        <li>Last Price Increase: 2024-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 103746189</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment] 2024-08-09 14:27
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-09 15:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The selected expense in search page is persisted through different login.

### What is the root cause of that problem?
The number of the selected expenses is coming from the search context provider.
https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/components/Search/SearchPageHeader.tsx#L274
https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/components/Search/SearchPageHeader.tsx#L117

The search context provider is put at App.tsx.
https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/App.tsx#L95

So, even when the user log out, the context data is still persisted.

### What changes do you think we should make in order to solve the problem?

Move the SearchContextProvider to AuthScreen, just like OptionsListContextProvider.
https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L355-L356

### What alternative solutions did you explore? (Optional)
Call `clearSelectedTransactions` when AuthScreens is unmounted.

**Comment by kadiealexander** [comment] 2024-08-23 08:01
@eVoloshchak please take a look at the proposal here!

**Comment by kadiealexander** [comment] 2024-08-27 06:29
@eVoloshchak bump!

**Comment by trjExpensify** [comment] 2024-08-30 00:17
Search is over in #wave-control now, @kadiealexander. Moving this one over. CC: @luacmartins @dylanexpensify

**Comment by kadiealexander** [comment] 2024-08-30 07:44
Thanks for picking this up @DylanDylann!

**Comment by DylanDylann** [comment] 2024-08-30 08:29
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/47168#issuecomment-2278202822) look good to me. We should reset the search context when the user logs out. Then the mobile selection mode will be cleared and don't reset again

https://github.com/Expensify/App/issues/47168#issuecomment-2278202822

**Comment by DylanDylann** [comment] 2024-08-30 08:29
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/47168#issuecomment-2278202822) look good to me. We should reset the search context when the user logs out. Then the mobile selection mode will be cleared and don't reset again

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-08-30 09:24
Just FYI, I prefer the main solution.

**Comment by bernhardoj** [comment] 2024-08-30 14:38
PR is ready

cc: @DylanDylann

**Comment by luacmartins** [comment] 2024-09-11 14:46
PR was [deployed to prod on Sep 3](https://github.com/Expensify/App/pull/48337#issuecomment-2327619347).

**Comment by kadiealexander** [comment] 2024-09-12 03:17
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@DylanDylann] Determine if we should create a regression test for this bug.
- [ ] [@DylanDylann] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-09-12 03:26
Payouts due:

- [ ] Contributor: $250 @bernhardoj via Manual Request
- [ ] Contributor+: $250 @DylanDylann ([offer](https://www.upwork.com/nx/wm/workroom/38265442/overview))

Upwork job is [here](https://www.upwork.com/ab/applicants/1823627646288296373/hired).

**Comment by DylanDylann** [comment] 2024-09-12 06:39
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Open Search page
2. Select some transactions on the page
3. Logout and relogin
4. Open Search page again
5. Verify the selection is cleared and not in a selection mode

Do we agree 👍 or 👎

**Comment by kadiealexander** [comment] 2024-09-16 04:58
Payout summary [here](https://github.com/Expensify/App/issues/47168#issuecomment-2345192278).

**Closed by kadiealexander** 2024-09-16 04:58 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-09-16 11:22
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-09-16 21:13
$250 approved for @bernhardoj
