### ISSUE TITLE
[$500] Entering a link with #something=something), at the end includes the ), in the link

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9332] opened 2022-06-07 04:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a Google Doc
2. add a Header (some text with the Heading 1 type)
3. put your cursor in the header
4. copy the link, paste in NewDot & add ), at the end
5. send the message

## Expected Result:
), should not be included in the link

## Actual Result:
notice that ), is included in the link

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.71-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
<img width="882" alt="Screen Shot 2022-06-03 at 1 26 57 PM" src="https://user-images.githubusercontent.com/43995119/172295001-4eac249e-5e79-4807-a7e3-76b6e508e774.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1654284267860229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2022-06-09 02:24
Created Job in Upwork - 

Internal posting - https://www.upwork.com/ab/applicants/1534722903416881152/job-details
External posting - https://www.upwork.com/nx/job-post/custom/preview?uid=1534722903416881152

**Comment by Christinadobrzyn** [comment] 2022-06-21 18:10
Increased Job price to $500 - still waiting on proposals.

**Comment by parasharrajat** [comment] 2022-06-23 19:12
@marktoman Would you please add diff instead of snippets it would be easier to see what exactly is changed?

**Comment by flodnv** [comment] 2022-06-27 13:32
@parasharrajat it seems like @marktoman has updated his post, can you review please?

**Comment by marktoman** [comment] 2022-06-29 18:57
`URL_FRAGMENT_REGEX` is used [here](https://github.com/Expensify/expensify-common/blob/3d87e9b87c6e5ce5fa4bac05bceb3cdf3ad6ca56/lib/ExpensiMark.js#L10), we don't change that. The only reason why we touch `URL_FRAGMENT_REGEX` is to avoid duplicity, so we extract the character list to a separate variable. Meaning you can choose either line and the outcome is the same.
```diff
- const URL_FRAGMENT_REGEX = `(?:#${addEscapedChar('[-\\w$@.+!*()[\\],=%;\\/:~]')}*)?`;
+ const URL_FRAGMENT_REGEX = `(?:#${addEscapedChar(URL_FRAGMENT_CHARS_REGEX)}*)?`;
```

### Description of the additons to `modifyTextForUrlLinks`
```js
0. const trailingParWithFragCharsMatch = match[2].match(new RegExp(`\\)${URL_FRAGMENT_CHARS_REGEX}$`, 'gi'))
1. if (!match[2].includes('(')
2.    && match[2].match(new RegExp(URL_WITH_FRAGMENT_REGEX, 'gi'))
3.    && trailingParWithFragCharsMatch) {
4.    match[0] = match[0].substr(0, match[0].length - trailingParWithFragCharsMatch[0].length);
5.    match[2] = match[2].substr(0, match[2].length - trailingParWithFragCharsMatch[0].length);
6. } else if (textToCheck[(match.index + match[2].length) - 1] === ')' && !match[2].includes('(')) {
```

- [0. and 3.] Here we check if the URL ends with `)` followed by valid fragment characters. If not, the standard handling is fine, so we don't continue. This is based on the original logic [here](https://github.com/Expensify/expensify-common/blob/3d87e9b87c6e5ce5fa4bac05bceb3cdf3ad6ca56/lib/ExpensiMark.js#L350), but it is modified for fragments.
- [1.] Make sure that the URL does not contain `(`. This is the same as the second part of [that line](https://github.com/Expensify/expensify-common/blob/3d87e9b87c6e5ce5fa4bac05bceb3cdf3ad6ca56/lib/ExpensiMark.js#L350). We make sure that the parenthesis we are about to strip is not closing an opening parenthesis within the URL. If that is the case, we treat them as a pair and part of the URL.
- [2.] We test if the URL is a fragment URL (the one ending with `#` potentially followed by valid fragment characters). We use the new `URL_WITH_FRAGMENT_REGEX` because it only matches the fragment URL. `URL_FRAGMENT_REGEX` on the other hand matches any valid URL, which may or may not have a fragment.
- [4. and 5.] Replace the original matching URL, that is the one that includes the trailing `)` followed by valid symbols, with the same string shortened by the length of the trailing part. This is the same as [the generic version](https://github.com/Expensify/expensify-common/blob/3d87e9b87c6e5ce5fa4bac05bceb3cdf3ad6ca56/lib/ExpensiMark.js#L351-L352).
- [6.] This only adds `else` before the original code. We want to keep everything as is except the handling of the fragment URL.

### Examples

Comment content:
```
(https://docs.google.com/document/d/1HK8wPqQ7NFNMmRgOjQut01VR5SDxJvHwj1TtNrZuLj4/edit#heading=h.renrse8f8gab),
```

Original values (before line 0.):
`match[0]`: 
```
https://docs.google.com/document/d/1HK8wPqQ7NFNMmRgOjQut01VR5SDxJvHwj1TtNrZuLj4/edit#heading=h.renrse8f8gab),
```
`match[2]`: 
```
https://docs.google.com/document/d/1HK8wPqQ7NFNMmRgOjQut01VR5SDxJvHwj1TtNrZuLj4/edit#heading=h.renrse8f8gab),
```
`trailingParWithFragCharsMatch`:
```
['),']
```
After the replace (after line 5.):
`match[0]`:  
```
https://docs.google.com/document/d/1HK8wPqQ7NFNMmRgOjQut01VR5SDxJvHwj1TtNrZuLj4/edit#heading=h.renrse8f8gab
```
`match[2]`: 
```
https://docs.google.com/document/d/1HK8wPqQ7NFNMmRgOjQut01VR5SDxJvHwj1TtNrZuLj4/edit#heading=h.renrse8f8gab
```



### Questions
1. Yes, the tests ran OK.
2. I assume you bring performance because you expect, as I was thinking originally, that this is called when rendering each post. Luckily for general performance, it is called when the user submits the comment. In either case, we introduce one URL match of the original regex (the change is the fragment is made mandatory, the definition does not change). A benchmark is totally dependent on whether the input URLs have fragments or not. If yes, the number of URL matches is the same (line 6.). Further, by swapping lines 2. and 3., we can avoid even that additional URL match for most cases (again, depending on what the input set is). I consider this improvement irrelevant anyway given how low times we deal with here.

**Comment by Christinadobrzyn** [comment] 2022-07-07 20:36
Hey @parasharrajat can we add a reviewing label to this to keep it from going overdue?

**Comment by flodnv** [comment] 2022-07-08 15:48
That is correct, it is used exclusively when the code is in a PR review. 

What are your thoughts on the proposal @parasharrajat ?

**Comment by parasharrajat** [comment] 2022-07-08 16:08
I will some run tests and let you know.

**Comment by parasharrajat** [comment] 2022-07-11 13:12
Opened a internal discussion https://expensify.slack.com/archives/C02NK2DQWUX/p1657544731979729

**Comment by flodnv** [comment] 2022-07-21 13:53
I will get back to this^ discussion next week.

**Comment by wildan-m** [comment] 2022-07-26 16:42
### Proposal

Closing parentheses is a valid URL character, so we can't ignore it.

We already have the logic to extract the URL between parentheses, but we still allow the unnecessary character to end the URL. (e.g. period)

We can solve it by only allowing certain characters to "end" the URL. Ending a URL in common punctuation marks like period, exclamation point, semicolon, etc means those characters will be considered end-of-hyperlink characters and not included in the URL.

```diff 
diff --git a/lib/ExpensiMark.js b/lib/ExpensiMark.js
index 7e3cc80..531775c 100644
--- a/lib/ExpensiMark.js
+++ b/lib/ExpensiMark.js
@@ -7,7 +7,8 @@ const addEscapedChar = reg => `(?:${reg}|&(?:amp|quot|#x27);)`;
 const URL_PATH_REGEX = `(?:${addEscapedChar('[.,=(+$!*]')}?\\/${addEscapedChar('[-\\w$@.+!*:(),=%~]')}*${addEscapedChar('[-\\w~@:%)]')}|\\/)*`;
 const URL_PARAM_REGEX = `(?:\\?${addEscapedChar('[-\\w$@.+!*()\\/,=%{}:;\\[\\]\\|_]')}+)?`;
 const URL_FRAGMENT_REGEX = `(?:#${addEscapedChar('[-\\w$@.+!*()[\\],=%;\\/:~]')}*)?`;
-const URL_REGEX = `(${URL_WEBSITE_REGEX}${URL_PATH_REGEX}(?:${URL_PARAM_REGEX}|${URL_FRAGMENT_REGEX})*)`;
+const URL_ENDING_REGEX = `[-A-Za-z0-9+&@#/%=~_()|}\\]]`;
+const URL_REGEX = `(${URL_WEBSITE_REGEX}(:?${URL_PATH_REGEX}(?:${URL_PARAM_REGEX}|${URL_FRAGMENT_REGEX})*${URL_ENDING_REGEX})?)`;
 const SLACK_SPAN_NEW_LINE_TAG = '<span class="c-mrkdwn__br" data-stringify-type="paragraph-break" style="box-sizing: inherit; display: block; height: unset;"></span>';
 
 export default class ExpensiMark {
```

This idea is adopted from [Jeff's 2nd workaround](https://blog.codinghorror.com/the-problem-with-urls/) to handle URL detection.

**Comment by parasharrajat** [comment] 2022-07-26 20:40
Still in the discussion.

**Comment by flodnv** [comment] 2022-08-01 12:48
We have discussed internally and reached the following conclusion: The handful of existing bugs in our markdown parser are solvable (we already have some proposals). Moving to a 3rd party library would come with its own set of new problems that we'd have to spend time solving. As such, Expensify engineers have decided to have contributors keep solving the Expensimark parsing bugs. Should there be problems other than parsing, these can be discussed separately.

@parasharrajat please review the proposals

**Comment by Christinadobrzyn** [comment] 2022-08-11 05:29
hey @parasharrajat do you have any updates for this? Looks like we're reviewing proposals?

**Comment by mvtglobally** [comment] 2022-08-30 15:23
Issue not reproducible during KI retests. (First week)

**Comment by flodnv** [comment] 2022-09-02 14:51
Not reproducible indeed:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/4164921/188175809-d8a8afdc-3d8e-451a-a98a-6aa2c8593ece.png">

**Comment by mvtglobally** [comment] 2022-09-06 03:17
Issue not reproducible during KI retests. (Second week)

**Closed** 2022-09-06 10:09 UTC
Labels: Exported, External, Engineering, Weekly, Improvement, Help Wanted
