### ISSUE TITLE
[HOLD for payment 2024-07-26] [$250] [Hold] Distance rates- Deleted distance rate is not disabled when submitting distance expense offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44154] opened 2024-06-21 13:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4652159
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has a few distance rates
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Go offline
4. Delete one of the distance rates
5. Go to workspace chat
6. Submit a distance expense with the deleted distance rate
7. Go online

## Expected Result:
In Step 6, app should prevent the deleted distance rate from being selected when submitting a distance distance

## Actual Result:
In Step 6, user can submit a distance expense with the deleted distance rate, which results in error when returning online

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18e08046-57e2-466d-86c2-7f0b9ead18c5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ad6ccc1c574e1a03</li>
        <li>Upwork Job ID: 1810478926161920694</li>
        <li>Last Price Increase: 2024-07-09</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103049061</li>
<li>paultsimura | Contributor | 103049063</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by lanitochka17** [comment] 2024-06-21 13:01
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-21 13:01
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-21 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can still select pending-delete distance rate and will result in an error when submitted.

### What is the root cause of that problem?
We are not filtering any distance rate that is pending-delete when showing the rate list.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L62-L72

### What changes do you think we should make in order to solve the problem?

Filter out any pending-delete rate. To do that:
1. Return the pendingAction from `getMileageRates`
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/libs/DistanceRequestUtils.ts#L59-L65

`pendingAction: rate.pendingAction,`

2. Filter out rate with pending action of delete.
https://github.com/Expensify/App/blob/68374a552f1af8c866753d46df2b0a0349615d2f/src/pages/iou/request/step/IOURequestStepDistanceRate.tsx#L62
`.filter(rate => rate.pendingAction !== 'delete')`

**Comment by OfstadC** [comment] 2024-06-21 21:01
Following [this Slack thread ](https://expensify.slack.com/archives/C036QM0SLJK/p1719000280371749)before proceeding

**Comment by OfstadC** [comment] 2024-06-24 13:20
@mallenexpensify I wonder if the Offline Distance request issues should be consolidated since they might have the same/similar solution? 🤔

**Comment by mallenexpensify** [comment] 2024-06-25 00:06
Asking about consolidating, should have an update tomorrow 🤞

**Comment by OfstadC** [comment] 2024-06-26 16:25
Thanks Matt!

**Comment by OfstadC** [comment] 2024-06-27 18:53
Any update @mallenexpensify ? 😃

**Comment by mallenexpensify** [comment] 2024-06-28 00:11
@paultsimura can you please comment so I can assign to you? 
Created a tracking issue for 'offline distance' issues. 

- https://github.com/Expensify/App/issues/44582

**Comment by OfstadC** [comment] 2024-07-01 15:57
@mallenexpensify Is there any action I need to take here?

**Comment by mallenexpensify** [comment] 2024-07-02 23:35
No @OfstadC ,  @paultsimura is going to to plan to _holistically_ address offline distance bugs.  He'll comment here with an update once he's reviewed all issues (and either raise a PR or recommend making the issue external)

**Comment by mallenexpensify** [comment] 2024-07-09 01:00
@shubham1206agra can review (or... if not, they can post in #contributor-plus to get a volunteer)

**Comment by OfstadC** [comment] 2024-07-09 14:45
@mallenexpensify Which project should we add this to?

**Comment by OfstadC** [comment] 2024-07-09 15:11
Looks like Distance now shows under Wave Collect road map

**Comment by OfstadC** [comment] 2024-07-26 15:13
@shubham1206agra I think you may need to accept the offer in Upwork? It's not showing an option to Approve payment

**Comment by OfstadC** [comment] 2024-07-26 15:14
Payment Summary:

- Paid @paultsimura $250 via Upwork
- Pending payment with @shubham1206agra

**Comment by mallenexpensify** [comment] 2024-07-26 22:42
@shubham1206agra paid via Upwork, payment confirmation updated above.  @shubham1206agra plz complete the BZ checklist above.

**Comment by arosiclair** [comment] 2024-07-30 13:54
@shubham1206agra I think you still need to complete the checklist

**Comment by mallenexpensify** [comment] 2024-07-30 23:59
@shubham1206agra do we want a test case for this? If so, please provide the steps.  If not, please provide reasoning why not.  Thx

**Closed** 2024-07-31 18:27 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
