### ISSUE TITLE
[HOLD for payment 2023-12-29] [$500] Request - When editing the IOU, the "Future Dates" are still locked

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33013] opened 2023-12-13 20:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on + > Request > Complete the manual request to any user (Note that HERE you can edit the "Date" to any future date as this is now expected and WAD)
4. After completing the request click on the IOU twice to get to the "Edit" screen.
5. Click on the "Date" in the IOU section to edit the date (The issue is here)

## Expected Result:
User expects that if it is now intended that the user can send requests for Future dates, that he/she is able to edit future dates in this section as well

## Actual Result:
In the edit IOU page, the user is unable to edit for future dates, the dates are locked

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/91bbf30c-2441-4371-b616-fe0d4e280ee3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01720f5c1caaa419d3</li>
        <li>Upwork Job ID: 1735034888322834432</li>
        <li>Last Price Increase: 2023-12-13</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 28060237</li>
<li>DylanDylann | Contributor | 28060239</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-12-13 20:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 Request - When editing the IOU, the "Future Dates" are still locked

### What is the root cause of that problem?

max date is now 
https://github.com/Expensify/App/blob/958c4312e6713e9ad76174a5f3c95e02dbf21576/src/pages/EditRequestCreatedPage.js#L37-L42
### What changes do you think we should make in order to solve the problem?

make max date after 20 years as done in other places

**Comment by DylanDylann** [comment] 2023-12-14 01:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the edit IOU page, the user is unable to edit for future dates, the dates are locked

### What is the root cause of that problem?
In the edit date page, we are setting max date is now
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/pages/EditRequestCreatedPage.js#L41

In the create date page, we are setting max date after 1 year
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/pages/iou/request/step/IOURequestStepDate.js#L74

It seems we don't allow editing dates to the future date in the request money flow. This difference is caused by this [PR](https://github.com/Expensify/App/pull/28618) I am not sure why in this PR we allow editing date to the future date
Note that in the old component
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/pages/iou/MoneyRequestDatePage.js#L106
we also don't allow setting date to the future date

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/b950c1eae5535abd5e733a5f9eeecd1bd42b8464/src/pages/iou/request/step/IOURequestStepDate.js#L74

In here we should update maxDate is now

### What alternative solutions did you explore? (Optional)
NA

**Comment by jjcoffee** [comment] 2023-12-14 14:59
Very similar proposals that both do the job, but I appreciate the extra attention to detail in @DylanDylann's [proposal](https://github.com/Expensify/App/issues/33013#issuecomment-1854960805), particularly adding `minDate` too and the idea of DRYing up the code by adding a global variable. So let's go with @DylanDylann's proposal!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by abzokhattab** [comment] 2023-12-14 15:09
Hello @jjcoffee

i have introduced the minDate as well in my solution so the “core” change is the same ( which is changing the dates) and mine was posted before it .. so please can you have another look. 

Thanks

**Comment by abzokhattab** [comment] 2023-12-14 15:24
Thanks for the advice I’ll consider that in my future proposals .. but as you said the two proposals are very similar that means we should go with the one posted first

Lets see what @tylerkaraszewski thinks

**Comment by DylanDylann** [comment] 2023-12-15 12:31
@jjcoffee The PR is ready for review https://github.com/Expensify/App/pull/33148

**Comment by alexpensify** [comment] 2023-12-23 03:14
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue @DylanDylann $500
-  Contributor+ that helped on the issue and/or PR @jjcoffee $500 

Upwork Job: https://www.upwork.com/jobs/~01720f5c1caaa419d3

Extra Notes regarding payment: Heads up, I'm OOO until January 4, but I will log in on Friday, December 29 to complete this payment process pending no regression. I've confirmed that @jjcoffee and @DylanDylann are a pending hire, so all set here for the payment date. 

@jjcoffee please complete the checklist when you can, thanks!

**Comment by alexpensify** [comment] 2023-12-29 18:25
Closing - Thank you everyone for your patience here. I've completed the payment process in Upwork and closed this job. 

Happy New Year!

@jjcoffee - please complete the checklist when you get a chance, thanks!

**Closed by alexpensify** 2023-12-29 18:25 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jjcoffee** [comment] 2024-01-02 12:47
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1439418407
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug.
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Click on + > Request > Complete the manual request to any user (Note that HERE you can edit the "Date" to any future date as this is now expected and WAD)
2. After completing the request click on the IOU twice to get to the "Edit" screen.
3. Click on the "Date" in the IOU section to edit the date
4. Verify that we can select a date in the future

Do we agree 👍 or 👎
