### ISSUE TITLE
[$500] BUG: [distance] request money button isn't bottom docked

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#26544] opened 2023-09-01 23:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Run App on latest main branch (for now)
2. Sign in with an account on the distance requests beta (or enable all betas)
3. Click green plus, request money, distance
4. Enter start and finish addresses
5. Click next
6. Select a workspace

## Expected Result:
The request money button is bottom docked, meaning that it is pushed to the bottom of the screen

## Actual Result:
The request money button is not bottom docked

## Workaround:
Ignore it

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Unreleased
**Reproducible in staging?:** Not yet
**Reproducible in production?:** Not yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Originally reported by Tom [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1693523866984759?thread_ts=1693516683.951869&cid=C05DWUDHVK7)

https://github.com/Expensify/App/assets/26260477/f65d4e56-0cbc-4128-b36e-f55d8fa607e3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify / @hayata-suenaga 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693611761287139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6ec526dc1626e01</li>
        <li>Upwork Job ID: 1697758865698336768</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-02 00:32
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
request money button isn't bottom docked

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/8fbe6aa33ba0eb5d0aa5fb56a4c8a31fda7259f2/src/pages/iou/steps/MoneyRequestConfirmPage.js#L253 
here `ScrollView` wrapped with twice


### What changes do you think we should make in order to solve the problem?
we need remove extra `ScrollView`

**Comment by zukilover** [comment] 2023-09-02 00:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money button isn't bottom docked

### What is the root cause of that problem?
`ScrollView` does not have the correct flex rule to make the button bottom docked.

### What changes do you think we should make in order to solve the problem?
Add `flexGrow` rule via the `contentContainerStyle` in the parent `ScrollView` of MoneyRequestConfirmPage.js

**Comment by zukilover** [comment] 2023-09-02 00:42
Contributor details
Your Expensify account email: heri.dehero@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/herihehe

**Comment by BhuvaneshPatil** [comment] 2023-09-02 04:32
- dupe #26418. SAME RCA

**Comment by s77rt** [comment] 2023-09-02 14:35
@pradeepmdk Thanks for the proposal. Your RCA is correct and the solution makes sense. It's not clear why we had to add the double ScrollView so I asked for a confirmation https://github.com/Expensify/App/pull/26179#discussion_r1313848726

**Comment by s77rt** [comment] 2023-09-02 14:38
@allroundexperts Thanks for the proposal. Your RCA is correct. Your solution would also work well but let's have this as our second to go option. Removing the extra ScrollView won't re-introduce https://github.com/Expensify/App/issues/24476.

**Comment by s77rt** [comment] 2023-09-02 14:39
@zukilover Thanks for the proposal but I think it's a dupe.

**Comment by s77rt** [comment] 2023-09-02 14:39
@neonbhai Thanks for the proposal but it's also a dupe.

**Comment by s77rt** [comment] 2023-09-02 14:46
@BhuvaneshPatil A dupe indeed. Given the other issue is not assigned to anyone, I'd like to continue working on this one here. We would still respect the chronological order of proposals.

@namhihi237 and @BhuvaneshPatil have same proposal as @allroundexperts but @namhihi237 was the first of the three.

**Comment by trjExpensify** [comment] 2023-09-04 10:17
👋 Hey all! @s77rt I think this issue can probably be closed, because we took [this direction](https://github.com/Expensify/App/pull/26597) to not have the "show more" button on the distance request confirmation page. Sense check me on that and I'll close this out! 

CC: @hayata-suenaga @JmillsExpensify

**Comment by Julesssss** [comment] 2023-09-04 10:44
Can we still fix this for the regular request flow please

**Comment by Julesssss** [comment] 2023-09-04 10:45
![Screenshot_20230904-114454.png](https://github.com/Expensify/App/assets/10736861/11e1fc52-f0be-4dcb-b468-242dccfc3414)

**Comment by trjExpensify** [comment] 2023-09-04 10:51
Yep, great catch. Let's continue to make sure it's fixed for the confirmation page of `Manual` and `Scan`. I'd say this is a pretty high polish item for SaaStr as it looks strange. @namhihi237 are you able to get a PR up in the next couple of hours so we can make the deploy? Similarly, @s77rt will you be around to review it? Thanks!

**Comment by s77rt** [comment] 2023-09-04 10:56
@trjExpensify I will be around. But I think we may go with @pradeepmdk [proposal](https://github.com/Expensify/App/issues/26544#issuecomment-1703574452). I don't see a reason for the double ScrollView (which is what is causing the bug). No reply on this [comment](https://github.com/Expensify/App/pull/26179#discussion_r1313848726) yet cc @DanutGavrus

**Comment by DanutGavrus** [comment] 2023-09-04 11:03
@trjExpensify @s77rt Hi, I'm checking the discussion right now

**Comment by DanutGavrus** [comment] 2023-09-04 11:30
@trjExpensify @s77rt We need to keep the parent `ScrollView` for reasons explained [here](https://github.com/Expensify/App/pull/26179#discussion_r1314827109). This is a follow up from the scrolling functionality I've added to the `MoneyRequestPage`. I wanted to make the page "full screen" and added `contentContainerStyle={[styles.flex1, styles.flexColumn]}` to the second `ScrollView`, but I forgot to add `contentContainerStyle={[styles.flexGrow1]` to the parent one in order to really be "full screen". It's a very small detail and it should have been part of my original PR, so I can make a PR right now as it's 1 line of code, and we may close this issue if it's ok for you too.

**Comment by DanutGavrus** [comment] 2023-09-04 12:07
Me and @s77rt continued the discussion [here](https://github.com/Expensify/App/pull/26179#discussion_r1313848726) for a little bit more context.

PR is up: https://github.com/Expensify/App/pull/26655. I've re-tested right now all the flows from the originally attached PR videos(different platforms, different screen sizes, different screen orientations and different list lengths) in order to make sure nothing else breaks because of this change.

I think we may close both this and https://github.com/Expensify/App/issues/26418 after merging.

**Comment by s77rt** [comment] 2023-09-08 17:30
Not overdue. PR was deployed to production 2 days ago.

@kevinksullivan I think we only have to pay @misgana96 for bug report ([initial issue](https://github.com/Expensify/App/issues/26418)).

**Comment by s77rt** [comment] 2023-09-11 11:11
@kevinksullivan Let's pay the bug reporter and close this

**Comment by s77rt** [comment] 2023-09-13 22:24
Not overdue. @kevinksullivan ^

**Comment by misgana96** [comment] 2023-09-14 02:34
@s77rt The payment was sechdule for 2023/09/12 if thereis no any regression for the issue [initial issue](#26418)

**Comment by kevinksullivan** [comment] 2023-09-15 15:18
bug reporters were internal so there's no one to pay here.

**Closed by kevinksullivan** 2023-09-15 15:18 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by misgana96** [comment] 2023-09-15 15:40
> @s77rt The payment was sechdule for 2023/09/12 if thereis no any regression for the issue [initial issue](https://github.com/Expensify/App/issues/26418)

@kevinksullivan you make a wrong decission. I am the reporter for the bug. The internal reporter was dupe of my report [initial issue](https://github.com/Expensify/App/issues/26418) @s77rt

**Comment by misgana96** [comment] 2023-09-15 16:10
@kevinksullivan  @s77rt please review the conversation from [initial issue](https://github.com/Expensify/App/issues/26418) and will find that I am the bug reporter

**Comment by kevinksullivan** [comment] 2023-09-21 06:15
It looks like you asked about payment on the original issue, so that'll be where we'd handle it @misgana96

**Comment by misgana96** [comment] 2023-09-21 06:34
> It looks like you asked about payment on the original issue, so that'll be where we'd handle it @misgana96 

The original issue is on hold for payment state that's why I asked there. It was scheduled for 23/09/12

**Comment by kevinksullivan** [comment] 2023-09-21 06:49
Ok, like I said if that' the issue where you should be paid, then we'll discuss it there.

**Comment by misgana96** [comment] 2023-09-21 06:51
> Ok, like I said if that' the issue where you should be paid, then we'll discuss it there.

Thank you
