### ISSUE TITLE
[HOLD for payment 2023-09-13] [$250] [Distance] - Next button hidden and unable to complete distance money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26737] opened 2023-09-05 01:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26601
## Action Performed:
1. Request money for a distance request.
2. After adding all the necessary data

## Expected Result:
Next Button visible to select or page scrollable to select Next button

## Actual Result:
Next button hidden and unable to scroll the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6188602_26601_safari](https://github.com/Expensify/App/assets/78819774/d2a9ca73-c5d7-4423-84f6-19dc8f09d291)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166ea6d21ec0ea15e</li>
        <li>Upwork Job ID: 1699360845004812288</li>
        <li>Last Price Increase: 2023-09-06</li>
    </ul>
</details>

**Comment by joh42** [comment] 2023-09-05 13:41
@mountiny seems like this PR fixed it https://github.com/Expensify/App/pull/26728
Now you can scroll down to the button

**Comment by mountiny** [comment] 2023-09-05 14:29
PR being cherry picked to staging

**Comment by akinwale** [comment] 2023-09-06 09:38
Changing the ScrollView style from `flex1` to `flexGrow1` fixes the inability to scroll on devices with smaller screens (eg iPhone SE first gen or the Nexus 4).

**Comment by mountiny** [comment] 2023-09-06 09:44
Discussed here https://expensify.slack.com/archives/C049HHMV9SM/p1693986149607419

**Comment by mountiny** [comment] 2023-09-06 09:56
Changing the price to $250 per agreement https://expensify.slack.com/archives/C049HHMV9SM/p1693988832434129?thread_ts=1693986149.607419&cid=C049HHMV9SM

**Comment by mountiny** [comment] 2023-09-06 10:11
@parasharrajat yes the PR is already merged so no need for C+

**Comment by mountiny** [comment] 2023-09-06 10:12
PR is being CPed

**Comment by akinwale** [comment] 2023-09-13 12:58
@alexpensify Just checking in here. My [PR](https://github.com/Expensify/App/pull/26859) for this was initially deployed to production on 2023-09-06 ([reference](https://github.com/Expensify/App/issues/26737#issuecomment-1708890986)), so it looks like the correct payment date is 2023-09-13, and the bot got a little carried away.

@mountiny Do I need to do anything with the checklist here?

**Comment by mountiny** [comment] 2023-09-14 11:23
I think we dont need the cheklist here as it was a new feature for the conference so not really regressions

**Comment by alexpensify** [comment] 2023-09-15 00:11
@akinwale - sorry, I was OOO the past two days and still catching up. I thought the payment date was on September 15, so that's why I didn't reassign. Can you please apply for the job here: https://www.upwork.com/jobs/~0166ea6d21ec0ea15e. Tomorrow, I'll complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2023-09-15 18:23
Thanks, I've continued the process in Upwork and need you to accept @akinwale.

**Comment by akinwale** [comment] 2023-09-15 18:54
> Thanks, I've continued the process in Upwork and need you to accept @akinwale.

@alexpensify Accepted, thanks.

**Comment by alexpensify** [comment] 2023-09-15 19:00
Awesome, I've completed the process in Upwork. Thanks for your help here!

**Closed by alexpensify** 2023-09-15 19:00 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by alexpensify** [comment] 2023-09-18 03:45
Here is the payment summary: 

-  External issue reporter N/A 
-  Contributor that fixed the issue @akinwale $250 
-  Contributor+ that helped on the issue and/or PR N/A 

Upwork Job: https://www.upwork.com/jobs/~0166ea6d21ec0ea15e

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: N/A
