### ISSUE TITLE
[HOLD for payment 2023-06-29] CRITICAL [SNH]: Chat - Status “User is typing” shows the email instead of the username

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20956] opened 2023-06-17 00:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: User logged in with 2 different accounts in different devices
1. As account B, type in the composer and check the area under the compose box in account A device
2. Verify there's a message indicated that user B is typing

## Expected Result:
Message is composed by "{Name} is typing..." (E.g: John is typing). The user email is NOT mentioned if the user has set a name

## Actual Result:
Status “User is typing” shows the email instead of the username

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6a20f03e-54cd-4fbf-a8f8-a1b963b6f4eb

![Bug6096210_Screen_Shot_2023-06-16_at_5 55 14_PM](https://github.com/Expensify/App/assets/78819774/ee404c49-4d30-432d-a5bc-d964ab54b087)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8a911757d8cf39e</li>
        <li>Upwork Job ID: 1675915112774844416</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-17 03:49
It seems from the backend in the pusherEvent we need to set accountID instead of loginId.

https://github.com/Expensify/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/src/libs/actions/Report.js#L119-L120

If accountId is passed then the below code will fetch the details correctly with the updated onyx structure for the `personalDetailsList`.
https://github.com/Expensify/App/blob/83ab0160a3b5c385fd26fffe20bdbccabf9249c0/src/libs/actions/PersonalDetails.js#L40

**Comment by Beamanator** [comment] 2023-06-19 11:13
Taking over this one 👍

**Comment by Beamanator** [comment] 2023-06-19 11:40
Bringing this up in slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1687174064671799

There's a few other details we need to think about - like what to show if you don't have the user's personal details stored in Onyx (example: You're in a public room and someone is typing and you don't have their personal details stored in Onyx)

**Comment by luacmartins** [comment] 2023-06-19 21:48
PR merged and being CPed - [CRITICAL [SNH]: Chat - Status “User is typing” shows the email instead of the username](https://github.com/Expensify/App/issues/20956)

**Comment by luacmartins** [comment] 2023-06-20 19:15
Removing the blocker label.

**Comment by Beamanator** [comment] 2023-07-03 08:07
@Christinadobrzyn sorry, reassigning you b/c it looks like when I manually assigned the C+ you accidentally got unassigned 😬 

This is basically done - just waiting for payout to C+ for their review & testing of the PR 👍

**Comment by s77rt** [comment] 2023-07-03 20:34
@Christinadobrzyn Accepted! Thanks!
As for the regression test I think this issue was already caught due to a regression test since it's caught by Applause. This seems to be the regression test https://expensify.testrail.io/index.php?/cases/view/2616830

**Comment by Christinadobrzyn** [comment] 2023-07-03 21:01
Awesome! thanks! Created a regression test - https://github.com/Expensify/Expensify/issues/296902

Paid you in Upwork - closing!

**Closed** 2023-07-03 21:02 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
