### ISSUE TITLE
[HOLD for payment 2024-10-11] Onyx.connect for a collection is not fetching the full collection in some files in dev

### ISSUE THREAD

**Issue by puneetlath** [Expensify/App#49609] opened 2024-09-23 16:59 UTC
We seem to have a dev-only issue with Onyx.connect and collections. Context here: https://expensify.slack.com/archives/C05LX9D6E07/p1726908940614449

<details><summary>Issue Owner</summary>Current Issue Owner: @OfstadC</details>

**Comment by fabioh8010** [comment] 2024-09-23 17:00
Hi, I'm Fábio from Callstack - expert agency - and I would like to work on this issue.

**Comment by fabioh8010** [comment] 2024-09-24 16:39
PR is ready to review

**Comment by OfstadC** [comment] 2024-09-27 13:32
Not overdue - PR was published. So I believe this is just awaiting payment?

**Comment by fabioh8010** [comment] 2024-09-27 17:58
The Onyx PR is ready to review -> https://github.com/Expensify/App/pull/49857

**Comment by fabioh8010** [comment] 2024-10-02 06:27
The [Onyx Bump PR](https://github.com/Expensify/App/pull/49857) was merged 🚀

**Comment by OfstadC** [comment] 2024-10-04 17:49
I believe only @parasharrajat is due payment here. If i'm wrong, please let me know!

## Payment Summary 
- @parasharrajat due $250 vie New Expensify request

**Comment by OfstadC** [comment] 2024-10-04 21:24
Ope - looks like I paid this early 😅 

@fabioh8010 Could you complete the BugZero checklist? Thank you!

**Comment by OfstadC** [comment] 2024-10-10 18:25
Going to close this as we've already issued payment, but if this requires regression testing, please let me know @fabioh8010 ! Thanks!~

**Closed by OfstadC** 2024-10-10 18:25 UTC
Labels: Weekly, Awaiting Payment, Bug

**Comment by fabioh8010** [comment] 2024-10-11 17:25
Hi @OfstadC , I'm from an expert agency, correct me if I'm wrong but it's not up to me to complete this checklist 😅

**Comment by JmillsExpensify** [comment] 2024-12-16 10:20
$250 approved for @parasharrajat
