### ISSUE TITLE
[NewDot Unapprove] Non-admin approvers aren’t able to Unapprove reports on OldDot

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41144] opened 2024-04-27 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714131911473989

## Action Performed:
Pre-req In OldDot:

- User A (ex. c.dobrzyn+123@expensifail.com): create a Collect with Submit & Approve workspace in OldDot
- User A: Add User C (ex. c.dobrzyn+34@expensifail.com) as a member of the workspace (not admin) > Make User C the Submit & Approve workspace approver

**Reproduction Steps:**
1. Sign in as User A
2. Submit a report to Users C
3. Sign in as User C
4. Navigate to the report.
5. Approve the report

 
## Expected Result:
Approver in OldDot who is the "Submit and Approve" Approver should be able to Unapproved reports in OldDot (and NewDot when we add Unapprove).

## Actual Result:
Approver in OldDot who is the "Submit and Approve" Approver can't Unapproved reports created in NewDot - they can only approve

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d67da3ebc3f7c4d</li>
        <li>Upwork Job ID: 1784915314907881472</li>
        <li>Last Price Increase: 2024-04-29</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2024-05-02 02:26
testing: 

test workspace: Testing NonAdmin approver
Owner: c.dobrzyn+123@expensifail.com
Admin: [c.dobrzyn+89@expensifail.com](mailto:c.dobrzyn+89@expensifail.com)
Employee: c.dobrzyn+34@expenisfail.com (Approver in OldDot)

I can't reproduce when submitting to an employee.. trying to submit to a workspace...

**Comment by Christinadobrzyn** [comment] 2024-05-02 09:08
I can't reproduce this, I can't get a report that can be unapproved by anyone in a workspace. I'll keep testing

**Comment by Christinadobrzyn** [comment] 2024-05-03 03:37
Okay I narrowed down the steps to reproduce in OP - this is going to be internal so adding our labels!

**Comment by Christinadobrzyn** [comment] 2024-05-07 07:47
trying to get some help here - https://expensify.slack.com/archives/C036QM0SLJK/p1715068029301439

**Comment by Christinadobrzyn** [comment] 2024-05-08 07:25
posted in BZ to try and get help - https://expensify.slack.com/archives/C01SKUP7QR0/p1715153127360859

**Comment by Christinadobrzyn** [comment] 2024-05-09 06:03
asking Tom for some guidance - https://expensify.slack.com/archives/C036QM0SLJK/p1715068029301439

**Comment by garrettmknight** [comment] 2024-05-09 10:34
Discussed in Slack, but this seems like a new behavior from what we can tell. Taking over and setting as a `New Feature`

**Comment by garrettmknight** [comment] 2024-05-09 10:40
Adding to https://github.com/Expensify/Expensify/issues/384891

**Comment by Christinadobrzyn** [comment] 2024-05-10 06:04
Oh amazing! Thank you @garrettmknight!

**Comment by garrettmknight** [comment] 2024-05-13 16:38
Still holding.

**Comment by garrettmknight** [comment] 2024-05-22 19:45
Still holding.

**Comment by garrettmknight** [comment] 2024-05-30 14:21
Still holding.

**Comment by garrettmknight** [comment] 2024-06-10 18:05
Taking this off hold!

**Comment by garrettmknight** [comment] 2024-06-19 18:58
Awaiting a volunteer!

**Comment by garrettmknight** [comment] 2024-06-28 18:02
Awaiting a volunteer!

**Comment by Beamanator** [comment] 2024-07-01 10:16
To be clear, we also want admins who AREN'T the current approver to be able to unapprove, right? Or no?

**Comment by garrettmknight** [comment] 2024-07-01 15:25
I think we do. If it's easiest to do that as part of this bug fix, cool!

**Comment by Beamanator** [comment] 2024-07-02 07:13
I think it makes sense, at least whoever works on this main issue will also probably have to get enough context that they'll easily be able to fix the 2nd part too :D

Should we add `Hot Picks` & move this to #wave-control?

**Comment by Beamanator** [comment] 2024-07-04 10:38
Grabbing this one

**Comment by Beamanator** [comment] 2024-07-04 11:28
Hmm we currently don't allow Admins (who aren't the approver / "manager") to unapprove, in Auth -> I'll have to update that both for OldDot & NewDot 😅

**Comment by garrettmknight** [comment] 2024-07-04 11:47
Huh, kind of wild that you need to be both an admin and the assigned approver, but if that's how it's set then this isn't really a bug I guess. @Beamanator let's not change in OldDot in that case and just handle NewDot in the Unapproved project.

**Comment by Beamanator** [comment] 2024-07-04 11:49
The one thing we miiiiiiiight want to do is allow non-admin managers to unapprove, which we could still do in this issue

**Comment by garrettmknight** [comment] 2024-07-04 17:53
I like designing to allow for non-admin approvers to unapproved in NewDot - I'm less passionate about changing OldDot to match if it's not what OldDot was initially coded to do.

**Comment by Beamanator** [comment] 2024-07-05 07:23
Brought the convo [to slack](https://expensify.slack.com/archives/C036QM0SLJK/p1720164026455959?thread_ts=1719828527.903419&cid=C036QM0SLJK)

**Comment by Beamanator** [comment] 2024-07-05 14:51
PR in review!

**Comment by Beamanator** [comment] 2024-07-08 11:21
Merged!

**Comment by dylanexpensify** [comment] 2024-08-14 16:38
Reopening as per [this convo](https://expensify.slack.com/archives/C06ML6X0W9L/p1723547542094449?thread_ts=1723491156.124719&cid=C06ML6X0W9L)

**Comment by Beamanator** [comment] 2024-08-15 21:42
should be on prod!

**Closed by Beamanator** 2024-08-15 21:42 UTC
Labels: Weekly, Internal, NewFeature
