### ISSUE TITLE
[$250] [Replace receipt] - A message should appear indicating that the receipt has been modified

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53025] opened 2024-11-23 15:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5255733
**Email or phone of affected tester (no customers):** aatweq+1901@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the URL: https://staging.new.expensify.com/
2. Go to an expense report conversation that has a receipt
3. Click on the receipt thumbnail
4. Click on the tree dots at the top right corner
5. Click on 'Replace'
6. Replace the receipt with a new one

## Expected Result:
A system message is displayed indicating the receipt was added.

## Actual Result:
After click on replace button and submit a new receipt, there is no message indicating that the receipt was changed.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/abc19476-313d-4d9d-9678-3d457aaffef7
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861276404561295777</li>
        <li>Upwork Job ID: 1861276404561295777</li>
        <li>Last Price Increase: 2024-12-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by nkdengineer** [comment] 2024-11-25 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After click on replace button and submit a new receipt, there is no message indicating that the receipt was changed.

### What is the root cause of that problem?

When we replace or remove the receipt, we don't add an action in the optimistic data and backend also doesn't return any report action.

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/actions/IOU.ts#L7570-L7573
### What changes do you think we should make in order to solve the problem?
- Create an action in optimistic data when we replace or delete the receipt. This action is a `MODIFIEDEXPENSE` like updating other fields with two values in `originalMessage` is `oldReceipt` and `receipt`.

1. Add the receipt to updated transaction in this function

```
if (Object.hasOwn(transactionChanges, 'receipt')) {
    updatedTransaction.receipt = transactionChanges?.receipt;
}
```
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/TransactionUtils/index.ts#L252

2. Add a new case for changing receipt in `getModifiedExpenseOriginalMessage` function

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/ReportUtils.ts#L3652

3. In `replaceReceipt`, build a `MODIFIEDEXPENSE` action by using `buildOptimisticModifiedExpenseReportAction` function and add this action to optimistic data, update `pendingAction` to `null` in `successData` and add an error in `failureData`

```
const transactionThread = ReportConnection.getReport(transactionThreadReportID);
const transactionChanges: TransactionChanges = {
    receipt: receiptOptimistic,
};
const updatedTransaction = TransactionUtils.getUpdatedTransaction({
    transaction,
    transactionChanges,
    isFromExpenseReport: false,
    policy,
});

const updatedReportAction = ReportUtils.buildOptimisticModifiedExpenseReportAction(transactionThread, transaction, transactionChanges, false, policy, updatedTransaction);

// Optimistic data
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThreadReportID}`,
    value: {
        [updatedReportAction.reportActionID]: updatedReportAction
    },
},

// Success data
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThreadReportID}`,
    value: {
        [updatedReportAction.reportActionID]: {
            pendingAction: null,
        }
    },
}

// Failure data
{
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${transactionThreadReportID}`,
    value: {
        [updatedReportAction.reportActionID]: {
            errors: ErrorUtils.getMicroSecondOnyxErrorWithTranslationKey('iou.error.genericEditFailureMessage'),
        }
    },
},
```
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/actions/IOU.ts#L7570

4. Pass `reportActionID: updatedReportAction.reportActionID` param here

https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/actions/IOU.ts#L7619

We need to do the same for `detachReceipt`
- Display this action

1. To display this action we need to add a new case for receipt in `getForReportAction` function

```
if (hasModifiedReceipt) {
    buildMessageFragmentForValue(
        reportActionOriginalMessage.oldReceipt ?? '',
        reportActionOriginalMessage.receipt ?? '',
        Localize.translateLocal('common.receipt'),
        false,
        setFragments,
        removalFragments,
        changeFragments,
    );
}
```
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/ModifiedExpenseMessage.ts#L135

2. I think for update receipt action, we only need to show `changed/set/removed the receipt` without the source value

So we can modify the translation without the old value and new value if the `valueName` is the receipt

```
const isModifiedReceipt = valueName === Localize.translateLocal('common.receipt');

if (isModifiedReceipt) {
    const fragment = Localize.translateLocal('iou.modifiedTheRequestWithoutValue', {valueName: displayValueName});
    if (!oldValue) {
        setFragments.push(fragment);
    } else if (!newValue) {
        removalFragments.push(fragment);
    } else {
        changeFragments.push(fragment);
    }
    return;
}
```
https://github.com/Expensify/App/blob/f4f8da74c100f2c5ddb666ff4314038010104cbf/src/libs/ModifiedExpenseMessage.ts#L38


- Require backend change: In `ReplaceReceipt` and `DetachReceipt`, the backend will use the `reportActionID` param to generate the modified expense action for receipt with `oldReceipt` and `receipt` in `originalMessage` as mentioned above 

### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/user-attachments/assets/daa0ffcd-e108-4056-8bce-aef8c6b55fa3

**Comment by pecanoro** [comment] 2024-12-02 16:17
@dominictb @nkdengineer If I am reading this properly, this action doesn't exist at all, right? If it doesn't exist, maybe this is on purpose, or we never considered implementing it, so it would be a new feature. But before @kadiealexander double-checks with the product team, could you guys confirm that this actually has never been a thing, as I suspect?

**Comment by nkdengineer** [comment] 2024-12-03 03:14
>  this action doesn't exist at all, right

Yes, that's correct.

**Comment by pecanoro** [comment] 2024-12-03 18:02
@kadiealexander, it seems this is not a bug and more like a new feature since the action doesn't exist and has never been. Could you double check in Slack if we want to implement this?

**Comment by kadiealexander** [comment] 2024-12-05 05:54
Closing, as I don't think we want to implement this and I think this bug was made in error. Sorry team!

**Closed by kadiealexander** 2024-12-05 05:54 UTC
Labels: External, Weekly, NewFeature, Help Wanted
