### ISSUE TITLE
[$500] Flag - Flag message for flagged parent message disappears when reopening thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34151] opened 2024-01-09 15:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33676ithub.com/Expensify/App/
## Action Performed:
1. [User A] Send a message to User B
2. [User B] Open the message in thread
3. [User B] Send a reply in thread
4. [User B] Flag the message as Intimidation
5. [User B] Return to main chat
6. [User B] Reopen the thread
Note that

## Expected Result:
The flag message for the flagged parent message does not disappear

## Actual Result:
The flag message for the flagged parent message disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5ac15151-36d1-4d4c-b450-399b0cdb0d51

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ea3ffb8d539f6e86</li>
        <li>Upwork Job ID: 1744738298135650304</li>
        <li>Last Price Increase: 2024-01-16</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28104518</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2024-01-09 16:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Flag - Flag message for flagged parent message disappears when reopening thread

### What is the root cause of that problem?

This is due to wrong fallback to `report.reportID` in Onyx subscription in `FlagCommentPage` component.

### What changes do you think we should make in order to solve the problem?

Remove the fallback
```js
parentReportActions: {
            key: ({report}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${report.parentReportID}`,
            canEvict: false,
        },
```

**Comment by yh-0218** [comment] 2024-01-09 17:48
I think this is backend issue

**Comment by yh-0218** [comment] 2024-01-09 18:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Flag - Flag message for flagged parent message disappears when reopening thread 
### What is the root cause of that problem?
I think this is backend issue.
But we can fix on [here](https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/pages/home/report/ReportActionItem.js#L230) easilly.
### What changes do you think we should make in order to solve the problem?
```js
const latestDecision = lodashGet(props, ['action', 'message', 0, 'moderationDecision', 'decision'], '') || lodashGet(props, ['action', 'originalMessage', 'moderationDecision', 'decision'], '');
```
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-01-09 18:18
# Proposal

## Please re-state the problem that we are trying to solve in this issue

The flag message for the flagged parent message disappears when reopening thread.

## What is the root cause of that problem?

https://github.com/Expensify/App/blob/35a6916095300af9dbfb593156470de9952a0b28/src/pages/home/report/ReportActionItem.js#L232-L234

In the line above, we're looking for the decision within `action.message[0]` but when re-fetching OpenReport the BE doesn't pass the decision in message like it does when first calling the flagging endpoint.

## What changes do you think we should make in order to solve the problem?

As fallback to the `latestDecision` from `action.message[0]` we should add `latestDecisionOriginal` which we get from the originalMessage object instead of `action.message[0]` where its missing.

POC looks something like this:

```diff
+   const latestDecisionOriginal = lodashGet(props, ['action', 'originalMessage', 0, 'moderationDecision', 'decision'], '');
    const latestDecision = lodashGet(
            props, ['action', 'message', 'moderationDecision', 'decision'],
+           latestDecisionOriginal
    );
```

**Comment by slafortune** [comment] 2024-01-11 22:05
@tylerkaraszewski do you agree that this is a backend issue but this fix would do the trick?  https://github.com/Expensify/App/issues/34151#issuecomment-1883554095

**Comment by dangrous** [comment] 2024-01-23 15:11
I don't think this is going to be resolved with the other GH, unfortunately - it's just posing some issues with testing haha. Hopefully we can solve this internally!

**Comment by situchan** [comment] 2024-01-23 15:15
Haha yes.
@tylerkaraszewski @dangrous one of you please check internally?

**Comment by tylerkaraszewski** [comment] 2024-01-30 21:42
@dangrous - what do you think we should do with this issue?

**Comment by dangrous** [comment] 2024-01-31 19:44
I think we're probably deprioritizing moderation bugs? It's not currently covered by a wave, as far as I know. Can you think of one where it might fit? I can add this to a list I have of moderation bugs so we can come back to it at some point

**Comment by situchan** [comment] 2024-01-31 19:47
Btw please keep me assigned here in case frontend fix is needed

**Comment by slafortune** [comment] 2024-02-02 19:19
Works for me @dangrous !  I'll assign @situchan so if this is opened again that will still be the assignment and close for now.

**Comment by kbecciv** [comment] 2024-02-06 15:20
Issue is reproduced on build 1.4.37.0 when executing PR https://github.com/Expensify/App/pull/28002

https://github.com/Expensify/App/assets/93399543/9c28d048-5885-4c31-b896-1604a851a2cc

**Closed** 2024-02-07 14:46 UTC
Labels: Engineering, Daily, Internal, Bug, retest-weekly
