### ISSUE TITLE
[$500] mWeb - Magic link - "Open in app" banner is dark themed on magic code page in light mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33476] opened 2023-12-22 00:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Enter an email you have access to
3. Tap on "Continue"
4. Go to email inbox and copy the Magic link and change it to staging
5. Open an incognito tab and navigate to the staging magic link

## Expected Result:
The "Open in app" banner should be in light mode

## Actual Result:
The "Open in app" banner is in dark mode even if the app is in light mode.
It also happens if the app has 2FA enabled and on the "Magic code expired" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

![Bug6323352_1703203267833!IMG_E2161](https://github.com/Expensify/App/assets/78819774/ec1f2296-c323-4695-b15f-891586de69c7)

![Bug6323352_1703203267842!IMG_E2163](https://github.com/Expensify/App/assets/78819774/ec314728-e653-4b78-9971-e54d95cd3bce)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f555a808f6be075d</li>
        <li>Upwork Job ID: 1737996800572018688</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2023-12-22 01:46
The banner looks like it's part of Safari's top bar, right under the status bar.

I think the banner is an OS specific item with functionality which checks whether the user has the New Expensify app installed on device and that's how it knows whether or not to display the banner on mWeb.

<details>
<summary>Real device preview</summary>

![10399](https://github.com/Expensify/App/assets/56457735/0c9f3195-9e56-449b-895d-58e9c6a76c51)

</details

**Comment by rushatgabhane** [comment] 2023-12-22 05:08
### Proposal 

## Root cause:

When logged out, the preferred theme isn't set and defaults to dark mode.

https://github.com/Expensify/App/blob/760c67cbea809a40090f4ee9536d4deef28c49ce/src/hooks/useThemePreference.ts#L13-L17

## Solution

**Comment by cubuspl42** [comment] 2023-12-22 08:42
@rushatgabhane Please stick to the proposal template, read the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) for more details.

😎

**Comment by cubuspl42** [comment] 2023-12-22 08:43
@tienifr 

> We can implement the smart app banner to follow whichever theme the page has

Can we? Would you share some details?

**Comment by ikevin127** [comment] 2023-12-22 15:21
@rushatgabhane is right about the persistence of the `preferredTheme` onyx variable upon logout, we already have an open issue https://github.com/Expensify/App/issues/33160 that's pending review.

Having said that, the current issue can be fixed independent of that one because this one is regarding the system default theme logic compared to the other issue which is regarding the persistence of a chosen theme.

# Proposal

## Please re-state the problem that we are trying to solve in this issue

The "Open in app" banner is in dark mode even if the app is in light mode.

It happens for all `ValidateLoginPage` screens:
- Here is your magic code
- 2FA
- Magic code expired
- Abracadabra, you are signed in!
- FullScreenLoadingIndicator


## What is the root cause of that problem?

The root cause is that we hardcoded the theme to dark for the SignInPage `ThemeProvider` which is wrapping the nested `CustomStatusBarAndBackground` and because of this when the device system theme is light (system default) the custom status bar and background are always using the dark theme colors.

https://github.com/Expensify/App/blob/862b0eac87e969e3c15d2ccde165600a6e40e8fb/src/pages/signin/SignInPage.js#L288-L291

Because of this, the `currentScreenBackgroundColor` is always set to `theme.appBG` which for dark theme the color is `#061B09`.

https://github.com/Expensify/App/blob/862b0eac87e969e3c15d2ccde165600a6e40e8fb/src/components/CustomStatusBarAndBackground/index.tsx#L52

## What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/d70c932092bbc3d117e345bf1f541851e6b979d9/src/hooks/useThemePreferenceWithStaticOverride.ts#L7-L9

To preserve the `SignInPage` to always dark themed according to the block mentioned above while not forcing always dark theme on nested `CustomStatusBarAndBackground` we can wrap `CustomStatusBarAndBackground` in `ThemeProvider` without any default theme prop which will fix the issue for both cases:
- when system default theme is applied (light / dark)
- when theme is specifically selected from Settings

This ensures that when the user reaches the above mentioned screens while in light mode, the background of the "Open in app" banner will be light themed.

### Changed code

```diff
function SignInPage(props) {
    return (
        <ThemeProvider theme={CONST.THEME.DARK}>
            <ThemeStylesProvider>
                <ColorSchemeWrapper>
+                   {/* Re-wrap CustomStatusBarAndBackground to override the hardcoded dark theme set above to system default or the one specifically chosen by the user */ }
+                   <ThemeProvider> 
+                       <CustomStatusBarAndBackground isNested />
+                   </ThemeProvider>
                    <SignInPageInner
                        // eslint-disable-next-line react/jsx-props-no-spreading
                        {...props}
                    />
                </ColorSchemeWrapper>
            </ThemeStylesProvider>
        </ThemeProvider>
    );
}
```

Below I added videos for both cases - when system default theme is light / dark and the issue screens or SignInPage are visited.

## Videos

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/56457735/ded6a617-f92a-411c-ad1d-8a9ee9076fd9

</details>

**Comment by chrispader** [comment] 2023-12-23 23:33
> ### Changed code
> ```diff
> function SignInPage(props) {
>     return (
>         <ThemeProvider theme={CONST.THEME.DARK}>
>             <ThemeStylesProvider>
>                 <ColorSchemeWrapper>
> +                   {/* Re-wrap CustomStatusBarAndBackground to override the hardcoded dark theme set above to system default or onyx `preferredTheme` (if existing) */ }
> +                   <ThemeProvider> 
> +                       <CustomStatusBarAndBackground isNested />
> +                   </ThemeProvider>
>                     ...
> ```

Instead of this, we can also just move the `CustomStatusBarAndBackground` element outside of the `ThemeProvider`, like this:

> ```diff
> function SignInPage(props) {
>     return (
> +    <>
> +      <CustomStatusBarAndBackground isNested />
>         <ThemeProvider theme={CONST.THEME.DARK}>
>             <ThemeStylesProvider>
>                 <ColorSchemeWrapper>
> -                       <CustomStatusBarAndBackground isNested />
>                     ...
> +    </>
> ```

**Comment by cubuspl42** [comment] 2023-12-27 12:15
@grgia Would you comment on [the Rushat's question](https://github.com/Expensify/App/issues/33476#issuecomment-1867246818)?

**Comment by chrispader** [comment] 2023-12-27 14:33
> When logged out, the preferred theme from storage isn't set and defaults to dark mode.
> cc: @grgia @chrispader I'm pretty sure this is the expected behavior?

Yes, if (previously) logged out all the data will be cleared and the default theme should be `dark`. Am i right? @grgia

**Comment by cubuspl42** [comment] 2024-01-02 09:11
@dylanexpensify I think we should close this one. It's more like a design discussion than an apparent bug. Also, the impact seems to be negligible. The dark banner, arguably, composes well with the system bar.

**Closed** 2024-01-09 12:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
