### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500]  The pay button is not shown again after removing the error,  When there’s an error at the moment to pay a request 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33524] opened 2023-12-22 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcochavezf 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703202408554429

## Action Performed:
1. Create a collect policy in OldDot
2. Execute the following JS snippet in the OldDot policy to enable workspace chats creation:
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
3. Add a member and an approver (it can be the same as the policy owner)
4. Add the same bank account for the member and the policy owner
5. Login in one session as a member and in another session as the approver
6. As member, create and submit a money request in the workspace chat
7. As admin/approver click/tap on the request and approve
8. Then select Pay elsewhere
9. An error will appear at the bottom of the expense chat, click on the x to remove it

## Expected result: 
The Pay button should appear again

## Actual result: 
The Pay button doesn’t appear and the user should come back to the workspace chat and open the expense request to refresh the request

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d8cf88af-e0e5-4e9d-96c5-dd812d58be00

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3679b87a3fd246a</li>
        <li>Upwork Job ID: 1740835161555730432</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28089862</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thesahindia</details>

**Comment by marcochavezf** [comment] 2023-12-29 20:40
Assigning myself to track it. Also, I will make external I think this can be fixed on the frontend

**Comment by bernhardoj** [comment] 2023-12-30 08:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we pay a money request and fails, the pay button won't reshow again.

### What is the root cause of that problem?
When we pay a money request, we optimistically update the `statusNum` to REIMBURSED.
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/libs/actions/IOU.js#L2823-L2831

But when fails, we never revert it.

And the pay button won't show if the `statusNum` is REIMBURSED.
https://github.com/Expensify/App/blob/8cb48e468ce3c09ada2d58aaae5354ec206104f9/src/libs/ReportUtils.ts#L579-L595

### What changes do you think we should make in order to solve the problem?

Revert the IOU report data when fails.

_Technically, we should do this to all optimistic data (chat report and nvp last payment method)_

_I currently simulate the error locally as I don't understand what bank account I should add to reproduce the exact same error_

**Comment by marcochavezf** [comment] 2024-01-03 00:31
Not overdue, waiting for proposals' review

**Comment by trjExpensify** [comment] 2024-01-03 15:44
@marcochavezf why is this failing in the first place? Is that being looked into somewhere else?

**Comment by marcochavezf** [comment] 2024-01-03 15:48
In this case it's failing because the bank account is the same for the payer and the member. Not sure if there are more cases that could cause a failure.

**Comment by Christinadobrzyn** [comment] 2024-01-03 20:26
@thesahindia could you review the proposals and see if they might work?

**Comment by Christinadobrzyn** [comment] 2024-01-07 22:50
@thesahindia will any of the current proposals work? Should we increase the bounty?

I'm going ooo for a week so going to assign a BZ teammate to monitor this - status: we're waiting on proposals.

**Comment by marcochavezf** [comment] 2024-01-08 23:25
> the system message after reverting the data is requested xxx it should be paid xxx not requested .. this happens because of the change in the report status..

Ah but the message at the end should be `requested xxx` because the payment failed, no?

**Comment by marcochavezf** [comment] 2024-01-09 01:45
Ah I see, thanks for the explanation @abzokhattab I appreciate it. The problem with updating the request after clearing the error is that we're still showing the request as `Paid` which could be confusing for the user. Also, I think changing the system message to `requested` is better since it reflects the real status of the request.

Said that I agree with @thesahindia's decision and will assign @bernhardoj. But thank you again for spotting those edge cases and bringing them for discussion

**Comment by bernhardoj** [comment] 2024-01-09 09:07
PR is ready

cc: @thesahindia

**Comment by mvtglobally** [comment] 2024-01-11 06:04
Issue not reproducible during KI retests. (First week)

**Comment by Christinadobrzyn** [comment] 2024-01-23 20:49
prepping for payment @thesahindia should we have a regression test?

Payouts due:

Issue Reporter: NA
Contributor: $500 @bernhardoj (in Upwork)
Contributor+: $500 @thesahindia (in NewExpensify)

Eligible for 50% #urgency bonus? NA

Upwork job is [here](https://www.upwork.com/jobs/~01f3679b87a3fd246a).

**Comment by conorpendergrast** [comment] 2024-01-24 11:34
Ah, you're back Christina! I'll unassign myself as you have this all handled

**Comment by Christinadobrzyn** [comment] 2024-01-26 00:00
paying this out based on this payment summary https://github.com/Expensify/App/issues/33524#issuecomment-1906894394

@thesahindia let me know about a regression test

**Comment by Christinadobrzyn** [comment] 2024-01-29 21:00
Awesome! thanks @thesahindia - created the regression test https://github.com/Expensify/Expensify/issues/364696

closing this out! Feel free to reach out if I've missed anything.

**Closed by Christinadobrzyn** 2024-01-29 21:00 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-10 18:11
$500 approved for @thesahindia
