### ISSUE TITLE
[$250] Expense - LHN shows RBR & report loads infinitely when invited member opens transaction thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46214] opened 2024-07-25 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B.
3. [User A] Go to transaction thread of any expense.
4. [User A] Send a user mention containing User C.
5. [User A] Click Invite from the whisper message.
6. [User A] Send a message in the transaction thread.
7. [User C] Click on the invited transaction thread in LHN.

## Expected Result:
User C should be able to access the transaction thread as User C is an invited member

## Actual Result:
The invited transaction thread appears in LHN, but shows RBR and infinite loading when trying to access it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/8ef80203-5467-4df6-8fe2-357e5b11add9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8847daf9b5eef47</li>
        <li>Upwork Job ID: 1816586516522830387</li>
        <li>Last Price Increase: 2024-08-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by joekaufmanexpensify** [comment] 2024-07-25 21:28
I can reproduce this. It isn't strictly limited to 1:1 DMs. If you try and invite someone into an expense in a workspace chat, it happens there too. Sharing a colleague onto a thread for an expense feels like something that could be reasonably common, so we should fix this.

**Comment by joekaufmanexpensify** [comment] 2024-07-26 13:37
Pending proposals

**Comment by NJ-2020** [comment] 2024-07-26 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows RBR & report loads infinitely when invited member opens transaction thread
### What is the root cause of that problem?
When we press the invite button we only remove the Concierge chat or resolve the alert message of inviting the member
We didn't invite the user to our Workspace
https://github.com/Expensify/App/blob/89539876835bc9ecb022f36f793d826a3def610e/src/pages/home/report/ReportActionItem.tsx#L482

### What changes do you think we should make in order to solve the problem?
We can check if the report has a policy (workspace) by invoking the `addMembersToWorkspace` function and passing `report.policyID`, else if it's a normal room we can invoke the `inviteRoom` function and also pass the reportID

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-07-29 18:46
@Pujan92 can you review the proposal here?

**Comment by Pujan92** [comment] 2024-07-30 12:47
I will review it max by tomorrow.

**Comment by joekaufmanexpensify** [comment] 2024-07-31 13:03
TY!

**Comment by Pujan92** [comment] 2024-08-01 12:51
> When we press the invite button we only remove the Concierge chat or resolve the alert message of inviting the member
We didn't invite the user to our Workspace

@NJ-2020 We are making an API call for that resolution, So I believe the backend should handle this and allow user C to access this chat report. Right now accessing that report for User C gives 404(Report no longer exists).

<img width="1324" alt="Screenshot 2024-08-01 at 18 10 20" src="https://github.com/user-attachments/assets/661c0525-7cf6-467f-8b3d-3ba2a7c9fe57">

@joekaufmanexpensify I suggest adding an engineering label to confirm.

**Comment by joekaufmanexpensify** [comment] 2024-08-01 16:34
@Pujan92 Got it. Does that mean you think this issue will be an entirely backend fix?

**Comment by Pujan92** [comment] 2024-08-02 09:17
Yes @joekaufmanexpensify

**Comment by joekaufmanexpensify** [comment] 2024-08-02 13:22
Got it. The engineering label won't auto-assign someone. The only way to auto-assign an engineer to confirm that is if you do the C+ proposal selected message.

**Comment by shah-pujan** [comment] 2024-08-02 13:27
auto-assign an internal engineer to confirm the required change.

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment] 2024-08-02 13:28
auto-assign an internal engineer to confirm the required change.

🎀👀🎀 C+ reviewed

**Comment by blimpich** [comment] 2024-08-02 18:57
I agree with @Pujan92, looks like a backend issue. I can' prioritize this issue so I'll unassign myself.

**Comment by joekaufmanexpensify** [comment] 2024-08-07 12:38
Moved to hotpicks as this needs an internal volunteer

**Comment by joekaufmanexpensify** [comment] 2024-08-08 13:26
Pending internal volunteer

**Comment by joekaufmanexpensify** [comment] 2024-08-09 13:01
Still just waiting for internal prioritization

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:45
Same

**Comment by joekaufmanexpensify** [comment] 2024-08-16 13:43
Still pending someone picking this up

**Comment by joekaufmanexpensify** [comment] 2024-08-19 14:12
Still looking for internal volunteer here

**Comment by joekaufmanexpensify** [comment] 2024-08-20 12:56
Same

**Comment by joekaufmanexpensify** [comment] 2024-08-21 13:15
One of [three remaining](https://expensify.slack.com/archives/C036QM0SLJK/p1724164814821899) collect hot picks. So this should get a volunteer soon!

**Comment by joekaufmanexpensify** [comment] 2024-08-21 13:16
Going to be OOO from tomorrow - Monday. No need to add another BZ here as just waiting for someone internally to pick this up. I can handle anything that comes up when I am back.

**Comment by marcochavezf** [comment] 2024-08-22 15:47
I wasn't able to reproduce the issue locally but created a [WIP PR](https://github.com/Expensify/Auth/pull/12182) to update the report to read-only permissions per this [convo](https://expensify.slack.com/archives/C036QM0SLJK/p1724263633730599?thread_ts=1724164814.821899&cid=C036QM0SLJK)

**Comment by trjExpensify** [comment] 2024-08-26 09:48
Assigning @marcochavezf as he's working on this.

**Comment by joekaufmanexpensify** [comment] 2024-08-26 20:57
Awesome. TY!

**Comment by marcochavezf** [comment] 2024-08-26 21:39
[PR](https://github.com/Expensify/Auth/pull/12182) in review

**Comment by joekaufmanexpensify** [comment] 2024-08-27 13:19
Amazing. TY!

**Comment by joekaufmanexpensify** [comment] 2024-09-02 15:50
Auth PR deployed, so closing this. Thanks again @marcochavezf

**Comment by lanitochka17** [comment] 2024-10-03 16:41
Issue is still reproducible on the latest build 9.0.44-2

https://github.com/user-attachments/assets/b6a0db4c-4f42-4d01-b60a-f0b14620d96d

**Comment by joekaufmanexpensify** [comment] 2024-10-07 15:21
Will re-triage

**Comment by joekaufmanexpensify** [comment] 2024-10-10 22:20
@marcochavezf can you take a look at this? I am also still able to reproduce this bug when I try using the steps [here](https://github.com/Expensify/App/issues/46214#issue-2430656636). Do we think this is a regression?

**Comment by joekaufmanexpensify** [comment] 2024-10-14 13:27
Bumped 1:1

**Comment by marcochavezf** [comment] 2024-10-14 16:50
Oh possibly yes, I will take a look at it today

**Comment by marcochavezf** [comment] 2024-10-15 01:50
I noticed the previous PR covered only expense reports in workspace chats and not IOUs. I created a [PR](https://github.com/Expensify/Auth/pull/12770) to fix that.

**Comment by joekaufmanexpensify** [comment] 2024-10-21 13:40
Great. TY! PR was deployed to auth, so closing this.

**Closed by joekaufmanexpensify** 2024-10-21 13:40 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug
