### ISSUE TITLE
[$500] Workspace - Currency list scrolls up when opening currency list immediately after selecting it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30951] opened 2023-11-07 02:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace.
3. Click Settings > Default currency.
4. Select another currency.
5. Immediately click on Default currency when navigated back to workspace settings.

## Expected Result:
The currency list will not scroll up.

## Actual Result:
The currency list scrolls up.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/fb98e229-4a80-4641-8cac-b4da528042ed

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c774584f7eaf06c</li>
        <li>Upwork Job ID: 1721723629691908096</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-11-07 03:02
Maybe dupe of https://github.com/Expensify/App/issues/26978

**Comment by DylanDylann** [comment] 2023-11-07 03:49
regression from this PR https://github.com/Expensify/App/pull/30438

**Comment by twisterdotcom** [comment] 2023-11-07 14:10
@robertKozik and @allroundexperts - is @DylanDylann correct? Should we treat this as a regression from https://github.com/Expensify/App/pull/30438

**Comment by twisterdotcom** [comment] 2023-11-09 18:02
bump for your thoughts @robertKozik and @allroundexperts

**Comment by sourcecodedeveloper** [comment] 2023-11-10 10:48
@robertKozik and @allroundexperts The issue is regression from (https://github.com/Expensify/App/pull/30438). I have posted [proposal](https://github.com/Expensify/App/issues/31087#issuecomment-1803506915) for other related issues similar to list scrolling and timezone list not selecting first option [#29080](https://github.com/Expensify/App/issues/29080).
I have prepared branch for testing the proposal (https://github.com/sourcecodedeveloper/App/tree/focusSelection_branch).

**Comment by situchan** [comment] 2023-11-10 10:55
We can close this and handle in https://github.com/Expensify/App/issues/29080.
The offending [PR](https://github.com/Expensify/App/pull/30438) should have been reverted earlier but unfortunately that was not marked as deploy blocker though was caught in staging.

**Comment by robertKozik** [comment] 2023-11-13 14:49
@twisterdotcom Yes it is regression from that PR/issue.

**Comment by twisterdotcom** [comment] 2023-11-13 16:55
Okay, closing here then.

**Closed by twisterdotcom** 2023-11-13 16:55 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
