### ISSUE TITLE
[Awaiting Payment] [$250] Single backtick code block is rendered within triple backtick code block when there is emoji

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49276] opened 2024-09-16 14:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to report.
3. Send this message
```
`diamond`
```
4. Note that there is only one code block.
5. Send the same message with emoji behind the text.
```
`diamond`💍
```

## Expected Result:
The single backtick code block will not be rendered within the triple backtick code block when there is an emoji.

## Actual Result:
The single backtick code block is rendered within the triple backtick code block when there is an emoji.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/097a8313-57ea-4bee-9e64-00f4c25fbc30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836063922739129987</li>
        <li>Upwork Job ID: 1836063922739129987</li>
        <li>Last Price Increase: 2024-09-24</li>
<li>Automatic offers: </li>
<ul>
<li>ra-md | Contributor | 104126656</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 14:45
We think that this bug might be related to Live Markdown

**Comment by IuliiaHerets** [comment] 2024-09-16 14:45
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-09-17 15:25
I can repro it, dropping to $125 as it's not really that valuable a problem to solve. 

<img width="782" alt="image" src="https://github.com/user-attachments/assets/bc500c37-2793-4ed9-a13a-591e1bf597d3">

**Comment by avalonprod** [comment] 2024-09-17 18:41
Hello, there is a solution to your problem. You can find emojis using UTF-8 encoding and replace them with an empty string using the replace method.

**Comment by Irbis007** [comment] 2024-09-17 18:44
Hello, there is a solution to your problem. You can find emojis using UTF-8 encoding and replace them with an empty string using the replace method.

**Comment by Irbis007** [comment] 2024-09-17 18:52
Contributor details
Your Expensify account email: suskodomk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0113f16cb1bc8ffdab

**Comment by abhinaybathina** [comment] 2024-09-17 21:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The single backtick code block will not be rendered within the triple backtick code block when there is an emoji

### What is the root cause of that problem?
The problem is in the ExpensiMark package, especially these lines in the constructor. There is nothing like emoji tag in HTML and because of this rule it's separating the text and emoji which returns an incorrect parsed text.

```
    // Apply the emoji first avoid applying any other formatting rules inside of it
    {
        name: 'emoji',
        regex: Constants.CONST.REG_EXP.EMOJI_RULE,
        replacement: (_extras, match) => `<emoji>${match}</emoji>`,
    },

```

### What changes do you think we should make in order to solve the problem?
We don't really need to remove the rule from the ExpensiMark package since we have disabledRules parameter, we can control which rules to be disabled. In our case, we can pass 'emoji' and it'll not apply the rule which should fix this issue.

```
    const disabledRules = ['emoji'];

    if (!isGroupPolicyReport) {
        disabledRules.push('reportMentions');
    }

    return text.length <= CONST.MAX_MARKUP_LENGTH
        ? Parser.replace(textWithMention, {shouldEscapeText: parsingDetails?.shouldEscapeText, disabledRules})
        : lodashEscape(text);
```

### What alternative solutions did you explore? (Optional)

### Working solution
<img width="1470" alt="Screenshot 2024-09-18 at 3 12 06 AM" src="https://github.com/user-attachments/assets/d8673d11-3852-4dd0-8da8-eb29cab4ce74">

**Comment by abhinaybathina** [comment] 2024-09-19 15:13
I couldn't see any changes related to this rule in https://github.com/Expensify/expensify-common/pull/669. Please correct me if I am wrong

**Comment by abhinaybathina** [comment] 2024-09-19 15:39
Thanks for sharing, I'll check and let you know

**Comment by Kalydosos** [comment] 2024-09-21 00:29
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
The single backtick code block will not be rendered within the triple backtick code block when there is an emoji


### What is the root cause of that problem?
The ExpensiMark parser's **inlineCodeBlock** rule is not excluding emoji tags when matching the "ticked" words. The issue applies only when the emoji are after the "ticked" word 


### What changes do you think we should make in order to solve the problem?

We should explicitly add the emoji tag as exclusion factor for a match thus changing the inlineCodeBlock from this

> {
                name: 'inlineCodeBlock',
                regex: /(\B|_|)&#x60;(.*?(?![&#x60;])\S.*?)&#x60;(\B|_|)(?!&#x60;|[^<]*<\/pre>)/gm,
                replacement: '$1<code>$2</code>$3',
            }

to this

> {
                name: 'inlineCodeBlock',
                regex: /(\B|_|)&#x60;(.*?(?![&#x60;])\S.*?)&#x60;(\B|_|)(?!&#x60;**|[^<emoji]**|[^<]*<\/pre>)/gm,
                replacement: '$1<code>$2</code>$3',
            }


### What alternative solutions did you explore? (Optional)
None


### RESULT

it works just fine

![Capture d’écran de 2024-09-21 01-27-42](https://github.com/user-attachments/assets/ab8218c7-6a25-47b4-99f5-51442cb42961)

**Comment by Kalydosos** [comment] 2024-09-21 10:38
> ### Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> The single backtick code block will not be rendered within the triple backtick code block when there is an emoji
> 
> ### What is the root cause of that problem?
> The ExpensiMark parser's **inlineCodeBlock** rule is not excluding emoji tags when matching the "ticked" words. The issue applies only when the emoji are after the "ticked" word
> 
> ### What changes do you think we should make in order to solve the problem?
> We should explicitly add the emoji tag as exclusion factor for a match thus changing the inlineCodeBlock from this
> 
> > {
> > name: 'inlineCodeBlock',
> > regex: /(\B|_|)`(._?(?![`])\S._?)`(\B|_|)(?!`|[^<]*\</pre\>)/gm,
> > replacement: '$1`$2`$3',
> > }
> 
> to this
> 
> > {
> > name: 'inlineCodeBlock',
> > regex: /(\B|_|)`(._?(?![`])\S._?)`(\B|_|)(?!`**|[^<emoji]**|[^<]*\</pre\>)/gm,
> > replacement: '$1`$2`$3',
> > }
> 
> ### What alternative solutions did you explore? (Optional)
> None
> 
> ### RESULT
> it works just fine
> 
> ![Capture d’écran de 2024-09-21 01-27-42](https://private-user-images.githubusercontent.com/572615/369581861-ab8218c7-6a25-47b4-99f5-51442cb42961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTM1MDUsIm5iZiI6MTcyNjkxMzIwNSwicGF0aCI6Ii81NzI2MTUvMzY5NTgxODYxLWFiODIxOGM3LTZhMjUtNDdiNC05OWY1LTUxNDQyY2I0Mjk2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDA2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDA2NDI0NWIxZDM4ZjM4ZmFkZmUwZmIwNmY3ZjZmMDlhYjAwODA2Y2U5ODMyMDY3MDM1OWM5N2I2OGY3NTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bUUiMkIDrUqUKnKXfB-dB5crflDOD0QNN5jx3qb_4Pc)

oups ! i have debugged the wrong version of Expensify-common (2.0.64 instead of 2.0.84). Is it possible to eventually submit another proposal in that case ?

**Comment by abhinaybathina** [comment] 2024-09-22 06:03
@Ollyws I've updated my proposal here https://github.com/Expensify/App/issues/49276#issuecomment-2356990697

**Comment by abhinaybathina** [comment] 2024-09-24 13:16
@Ollyws Did you get a chance to look into my updated solution? Kindly let me know if that works! Thanks :)

**Comment by carlosmiceli** [comment] 2024-09-27 14:37
@ra-md merged!

**Comment by thienlnam** [comment] 2024-10-08 17:53
Yup, looks like this was deployed to prod on Oct 1st, 2024 - cc @trjExpensify Should be good to go

**Comment by trjExpensify** [comment] 2024-10-08 22:16
Confirming payments as follows: 

- $250 to @ra-md for the fix
- $250 to @Ollyws for the C+ review

Go ahead and request, Olly. @ra-md, you've been paid. Closing!

**Closed by trjExpensify** 2024-10-08 22:16 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-09 15:16
$250 approved for @Ollyws
