### ISSUE TITLE
Settings - When user clicks 'Save' without changing their username "Your PayPal username was successfully saved" popup message appears

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26889] opened 2023-09-06 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings
2. Open wallet
3. Click on Add payment method and select paypal.me if you don't add PayPal before
4. Enter user name and click add paypal account
5. Click on your PayPal account
6. Click on Edit
7. Click on save without editing

## Expected Result:
 The "Your PayPal username was successfully saved" popup message should not appear if there is no username change

## Actual Result:
"Your PayPal username was successfully saved" popup message appears without the user changing anything

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.64-2

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ce9eabca-6b44-44b4-becb-dd8daa9ed2d5

https://github.com/Expensify/App/assets/115492554/a623936f-0949-46bb-a5d7-9778d8cf5177

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jo-ui

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693301255846379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-09-06 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are not checking if previous value of name is same as new value before showing the popup.
https://github.com/Expensify/App/blob/c2dab6ea63e0802888e32de3cc36fa15bfb706b8/src/pages/settings/Wallet/AddPayPalMePage.js#L62-L65

### What changes do you think we should make in order to solve the problem?
We shall add following check for checking if new value is different.
```js
    const setPayPalMeData = useCallback(
        (values) => {
            if (lodashGet(props.payPalMeData, 'accountData.username', '') !== values.payPalMeUsername) {
                User.addPaypalMeAddress(values.payPalMeUsername);
                Growl.show(growlMessageOnSave, CONST.GROWL.SUCCESS, 3000);
            }
            Navigation.goBack(ROUTES.SETTINGS_WALLET);
        },
        [growlMessageOnSave, props.payPalMeData],
    );
```

This way we are only calling save method if title is different and display the message if it's different.
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-09-07 09:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When user clicks 'Save' without changing their username "Your PayPal username was successfully saved" popup message appears
### What is the root cause of that problem?
- We are not checking if the previous value of the name is the same as the new value before submitting form:
https://github.com/Expensify/App/blob/c2dab6ea63e0802888e32de3cc36fa15bfb706b8/src/pages/settings/Wallet/AddPayPalMePage.js#L62-L65

### What changes do you think we should make in order to solve the problem?
- Enable the user to click on the submit button without any action being performed in this case will confuse the user.
- So when the input value is the same as the original value, we should disable the "Save PayPal account" button. We can do it by creating the ```getShouldDisableSubmit``` in [```App/src/pages/settings/Wallet/AddPayPalMePage.js```](https://github.com/Expensify/App/blob/c2dab6ea63e0802888e32de3cc36fa15bfb706b8/src/pages/settings/Wallet/AddPayPalMePage.js) like bellow:
```
    const getShouldDisableSubmit = useCallback(
        (values) => {
            if (lodashGet(props.payPalMeData, 'accountData.username', '') !== trim(values.payPalMeUsername) || isEmpty(trim(values.payPalMeUsername))) {
                return false;
            }

            return true;
        },
        [props.payPalMeData],
    );

```
- Then pass it to the <Form /> element and then propagate to the <button /> element in that form the know if we should disable the submit button
### What alternative solutions did you explore? (Optional)
- NA

### Result
[Screencast from 07-09-2023 16:18:24.webm](https://github.com/Expensify/App/assets/141406735/c0182c41-cf57-4058-9a7b-3361f642f8fe)

**Comment by sophiepintoraetz** [comment] 2023-09-08 03:40
We are deprecating paypal (decision [here](https://expensify.slack.com/archives/C057F53HR40/p1694141684236569), GH [here](https://github.com/Expensify/App/issues/26368)) so closing this out, thanks!

**Closed by sophiepintoraetz** 2023-09-08 03:40 UTC
Labels: Daily, Bug
