### ISSUE TITLE
When you send your own email address in a DM, it shows as "you" in LHN - reported by @puneet-here

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12360] opened 2022-11-02 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1.Open website
 2. Go to Chat > send your own email
 3. Now check LHN

## Expected Result:
The email address that you sent in the chat should be shown in the LHN

## Actual Result:
It shows as "You" in the LHN.

## Workaround:
N/A - just a visually weird thing.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.22-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199367381-bad7e2d3-1aeb-4b0c-b401-c53e285e11d9.mov

https://user-images.githubusercontent.com/43996225/199367431-aba2eba2-dd6a-4389-a682-0db551a9824c.mp4

**Upwork job URL:** https://www.upwork.com/jobs/~01c3345eccc1920e68
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659100345685099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2022-11-04 12:40
Job is posted to upwork - https://www.upwork.com/jobs/~01c3345eccc1920e68

**Comment by michaelhaxhiu** [comment] 2022-11-04 12:41
This may be a dupe though... one sec.

**Comment by michaelhaxhiu** [comment] 2022-11-04 12:42
Actually nevermind this is not a dupe!

**Comment by michaelhaxhiu** [comment] 2022-11-04 12:45
Notes:

- @AndrewGable I feel pretty strongly this is `external` but please correct me if I'm mistaken.

- @Puneet-here any interest in taking a crack at solving this one since you reported it? 😄 All good if not, but I see you sometimes solving the bugs you raise 🤜 🤛

**Comment by Puneet-here** [comment] 2022-11-04 12:53
I am not sure I will able to look into this one, I am working on multiple issues right now (on some medium size fishes too hahaha)

**Comment by Beamanator** [comment] 2022-11-04 14:30
@michaelhaxhiu this definitely looooks external, i can't imagine we're doing this swap on the server side 😅

**Comment by michaelhaxhiu** [comment] 2022-11-04 14:37
Thanks @Beamanator - i wonder why both you and Andrew got assigned btw 🤔 I didn't notice that till now.

**Comment by tlerias** [comment] 2022-11-06 00:42
I think this may be happening on the server (see screenshot). We send the correct text over the write API. But we get an event with an updated text to `You`

<img width="1163" alt="Screen Shot 2022-11-05 at 8 39 54 PM" src="https://user-images.githubusercontent.com/3011845/200148749-66b98f90-bf4c-4dcb-9011-615b433676db.png">

**Comment by Beamanator** [comment] 2022-11-07 10:14
Yep it does look like this is a server-side issue, thanks for pointing that out @tlerias 👍

**Comment by Beamanator** [comment] 2022-11-07 10:48
Posted in #expensify-open-source, in the OP [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667817919754449?thread_ts=1659100345.685099&cid=C01GTK53T8Q), to confirm this is an issue (cc @tgolen )

**Comment by Beamanator** [comment] 2022-11-08 13:47
Posted publicly again to get more feedback [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667915173469529?thread_ts=1659100345.685099&cid=C01GTK53T8Q)

**Comment by michaelhaxhiu** [comment] 2022-11-08 13:50
Assignment is tripping... manually assigning myself

**Comment by Beamanator** [comment] 2022-11-16 20:17
Working on this, going OOO though so should have an update next week

**Comment by michaelhaxhiu** [comment] 2022-11-17 21:24
@Beamanator sounds good. I'm going OOO starting monday too.

**Comment by michaelhaxhiu** [comment] 2022-11-19 14:14
Switching this to `daily` are expected for all bugs in E/App. Also going to re-assign a member of BZ team since I'm OOO till Nov 29.

**Comment by abekkala** [comment] 2022-11-21 15:01
I'm not entirely sure where/what I'm supposed to pick up here as this is internal. 
I assume this is something Alex is/will work on when he's back from ooo

**Comment by Beamanator** [comment] 2022-11-21 17:25
Yeah good question @abekkala - I haven't gotten started on this yet (will later this week, as it's not a super high priority fix). I guess you're assigned in case a C+ helps review the PR? Maybe? If it's all internal work though I guess you won't need to do anything 😅

**Comment by joelbettner** [comment] 2022-12-01 16:14
The fix for this has been deployed. I'm guessing that this didn't get closed automatically because the PR is in the Web-Expensify repo, and this issue is in the App repo instead of the Expensify repo.

**Comment by Puneet-here** [comment] 2022-12-01 16:17
@joelbettner, this is eligible for reporting bonus

**Comment by abekkala** [comment] 2022-12-01 16:24
I need to do the payouts - reopening

**Comment by abekkala** [comment] 2022-12-01 16:27
@joelbettner who did the PR Review for this? 
Also I'm having a hard time pinpointing the date range here. 

There is a 7 day hold for payments. Can you let me know when the 7-day regression period ends?

**Comment by joelbettner** [comment] 2022-12-01 18:19
I did the PR for this...

**Comment by abekkala** [comment] 2022-12-01 18:35
Ah ok yeah, that's what I was wondering (if a C+ did the Review)
I do have one other internal issue that noted waiting the 7 days for payout.
But, that could have been due to the C+ having done the Review. 

I'll go ahead and Pay out this one today! and get it closed!

Thanks!

**Comment by Beamanator** [comment] 2022-12-01 18:36
Aah I thinkkkk you're right, it depends on if a C+ did a review or not, cuz they get paid different if there's a regression right?

**Comment by abekkala** [comment] 2022-12-01 18:37
yes, exactly.

**Comment by abekkala** [comment] 2022-12-01 18:50
@Puneet-here I invited you to the job in Upwork, can you accept and I'll pay out the Reporting Bonus!

**Comment by Puneet-here** [comment] 2022-12-01 19:16
@abekkala accepted the offer, thanks!

**Comment by abekkala** [comment] 2022-12-01 19:17
Great, Payment sent!

Thank you!

All set here! 🎉

**Closed by abekkala** 2022-12-01 19:17 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
