### ISSUE TITLE
[HOLD for payment 2023-10-25] Chat - Pasted text reflects Full Display name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28521] opened 2023-09-29 19:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27889
## Action Performed:
1. Navigate to staging.new.expensify.com as User A
2. Request Money from User B
3. Sign in as User B
4. Go to IOU report
5. Click on 'Pay elsewhere' button
6. Click on 'copy to clipboard' icon
7. Paste the copied text

## Expected Result:
The pasted text should reflect what was copied from the message

## Actual Result:
Pasted text reflects copied message plus Full Display name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.75-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/79dfc532-43e2-4022-ad98-fe466111e3f7

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abdel-h66** [comment] 2023-09-30 10:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU text message "Firstname paid elsewhere" does not match the copied text. 

### What is the root cause of that problem?
The copy action of the message `Firstname paid elsewhere` does not use the same logic as the preview. 

In the preview we are getting only the short form of the payer name by passing `true` as second argument to `getDisplayNameForParticipant`

`const payerName = isExpenseReport(report) ? getPolicyName(report) : getDisplayNameForParticipant(report.managerID, true);`

In the copy to clipboard action, we are using almost the same logic but without the `true` flag 

https://github.com/Expensify/App/blob/52f0e3c9ec9ab5c87993672661095f81253bc00d/src/libs/ReportUtils.js#L3654

### What changes do you think we should make in order to solve the problem?

`getIOUReportActionDisplayMessage` responsible to generate the text to copy, is only called in a single place, we can just update the function call to include the short form flag. 

### What alternative solutions did you explore? (Optional)

N/A

**Comment by mountiny** [comment] 2023-10-01 07:58
I can take this one over as I have been assigned to the original PR

I agree this is not a blocker, its a new feature and minor issue.

I think we should use the same methods for when we want the exact same message to be copied @rayane-djouah this is it feels like incompleteness from our PR, can you work on this as a follow up so the copied text exactly copies what the system message says?

**Comment by mountiny** [comment] 2023-10-01 09:39
To confirm, this would be a continuation of the previous upwork job as we should make sure to get this right

**Comment by mananjadhav** [comment] 2023-10-02 16:17
> To confirm, this would be a continuation of the previous upwork job as we should make sure to get this right

@mountiny Does this need review here?

**Comment by mountiny** [comment] 2023-10-19 22:57
This was already paid and this was a regression handled from here https://github.com/Expensify/App/issues/27114

**Closed by mountiny** 2023-10-19 22:57 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
