### ISSUE TITLE
mWeb/Safari - Chat - After opening the image, it opens on top of the whole window

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11123] opened 2022-09-19 22:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with any account
2. Go to any chat
3. Upload any attachment
4. Open the attachment and hold with your finger

## Expected Result:
The image size should not change

## Actual Result:
The image opens on top of the whole window

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Mobile Web/safari

**Version Number:** 1.2.2.0

**Reproducible in staging?:**  Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191130441-3990d50e-ae8f-46ff-a4f2-30f7f0141f83.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-09-21 12:58
That's not a bug. That's how Safari deals with images in any websites if you hold it, opening the default options. Closing this.

**Closed by danieldoglas** 2022-09-21 12:58 UTC
Labels: Engineering, Daily
