### ISSUE TITLE
Android - Scrolling through a page with Options rows activate the  click style for a moment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26108] opened 2023-08-28 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Android app
2. Click on your avatar to open settings
4. Start Scrolling
- You can open any page with options rows

## Expected Result:
No Style should appear for the row you  first touched to start Scrolling.

## Actual Result:
The row which is located in the area you first touched to start Scrolling would have the click event style for a moment.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/377620be-f09f-4077-85bb-e2b5ea5c68c8

https://github.com/Expensify/App/assets/115492554/f066cae4-9853-4e8d-a213-96e8a557792a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Ahmed-Abdella)

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692538620967429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment] 2023-08-31 02:04
I don't really understand the bug. Asked in the linked Slack thread.

**Comment by Ahmed-Abdella** [comment] 2023-08-31 02:09
@anmurali when you click on any row there is a background color appears for the row you clicked. this color appears when you try to scroll.

**Comment by anmurali** [comment] 2023-09-06 00:46
I am really swamped right now and have to prep for Saastr keynote day after at some point. So going to rotate this.

**Comment by trjExpensify** [comment] 2023-09-07 10:43
Luckkkky me. Crush the keynote, @anmurali! <3

>The root cause of this issue is the default touch event propagation in React Native on Android. When a user starts a touch gesture over a touchable item inside the ScrollView but intends to scroll, the touchable component captures the touch event. This behavior leads to the accidental triggering of touchable elements when the primary intent was just to scroll.

Alright, so I don't think this is something to worry about really. I see the same on iOS as well after trying Android on the emulator. If you touch the row it highlights, and when you start to scroll the highlight on the row you touched is removed. 

I think that's just the nature of having touchable components that are also scrollable because of how many there are in the list exceeding the scroll view available. We can't guess a user's primary intent was "just to scroll" when they press one of the rows.  

My vote is :do-nothing: but happy for a second opinion from @shawnborton & @dannymcclain before closing this out as not a bug. 

iOS for reference:

https://github.com/Expensify/App/assets/16232057/8719ed5d-fd68-44dc-95a2-53d6e46a1658

**Comment by shawnborton** [comment] 2023-09-07 12:55
I'm down with do nothing as well here. But thanks for a solid analysis!

**Comment by trjExpensify** [comment] 2023-09-07 13:13
Cool, cool. Closing!

**Closed by trjExpensify** 2023-09-07 13:13 UTC
Labels: Daily, Bug
