### ISSUE TITLE
[$1000] Web - Concierge conversation is not available in LHN after login or relaunch

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26084] opened 2023-08-28 14:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Be logged out
2. Log in
3. Search for the Concierge chat in the Left hand navigation

## Expected Result:
The chat should appear as “Concierge” in LHN

## Actual Result:
The chat does not appear in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a1b1a07d-bf46-47dc-8e8f-7d088d989df4

![image (16)](https://github.com/Expensify/App/assets/93399543/98b3d5f6-33b4-4324-af68-914a346c2eb2)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @kidroca 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692289838505759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0120087ddefe26a0bb</li>
        <li>Upwork Job ID: 1696599281114849280</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-08-29 19:02
I can reproduce this!

**Comment by b4s36t4** [comment] 2023-08-29 19:09
@isabelastisser What is the expected behaviour here? We should show `Concierge` in LHN everytime? even when we have focus mode on?

**Comment by isabelastisser** [comment] 2023-08-29 19:24
hey @b4s36t4, good question! No, I don't believe that we should show Concierge in LHN when the focus mode is on.

**Comment by b4s36t4** [comment] 2023-08-29 19:26
So this is not a bug?

**Comment by studentofcoding** [comment] 2023-08-29 19:49
So right now the behavior are:
- Concierge appears on LHN on initial load,
- When we chat with Concierge, it'll be active and shown on LHN,
- Upon Log out and Log in, the Concierge will still be present 

Based on the above details, Can you kindly check if the above behavior is already correct @isabelastisser, if yes, then I think we have no bug here

**Comment by isabelastisser** [comment] 2023-08-29 19:59
Discussing this [here.](https://expensify.slack.com/archives/C01SKUP7QR0/p1693339142649819)

**Comment by isabelastisser** [comment] 2023-08-29 20:30
I confirmed that this seems to be a bug. Per the recording, the focus mode is `not` on, so Concierge should be showing in LHN, but it is not.

**Comment by isabelastisser** [comment] 2023-08-29 20:41
I just tried to reproduce this again with focus mode `off`, and Concierge is now showing in LNH after logging out and logging back in. 

@b4s36t4 @studentofcoding Are you able to reproduce this? If not, I will close this issue.

**Comment by isabelastisser** [comment] 2023-08-30 15:22
In this [discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1693361147106869?thread_ts=1693339142.649819&cid=C01SKUP7QR0) we confirmed that Concierge is auto-pinned and should show in all modes, unless is unpinned. 

I tried to reproduce the issue again by pinning Concierge, and it appears in LHN both in the `most recent` and `focus` mode for me. Closing this as the issue is no longer reproducible.

**Closed by isabelastisser** 2023-08-30 15:22 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by kidroca** [comment] 2023-08-31 16:38
Hello Team,

I appreciate the efforts to reproduce the issue. However, I'd like to reopen this for further investigation. While it's true that the issue can be manually resolved by the user, I believe it still qualifies as a bug that needs to be addressed.

#### Why This Should Still Be Considered a Bug

1. **User Expectation**: Typically, issues like this should resolve automatically upon logging out and back in. However, in this case, the bug persists.
2. **Manual Steps Required**: To resolve the issue, users have to toggle focus mode on and off, and then manually search for the Concierge conversation. This is not an intuitive solution.
3. **Inconsistency Across Accounts**: I still experience this issue on multiple accounts, indicating that it's not an isolated case.

#### Video Sample
For further clarity, here's a demonstrating the issue and the steps users have to take to resolve it.

https://github.com/Expensify/App/assets/12156624/18c72576-6cf0-42ea-80f9-5d5914d72186

---

> I tried to reproduce the issue again by pinning Concierge, and it appears in LHN

While pinning the chat makes it consistently appear in LHN, the issue arises when the conversation is not originally pinned. In my case, the conversation disappeared even in "most recent mode," and I had to toggle focus mode and search for the chat to make it reappear.

#### Next Steps
Would it be helpful if I share more details or debug the issue myself on the accounts where I still experience it?

Thank you for your attention to this matter.
