### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500]  Chat - After creating IOU report the user cannot be found on Start chat screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30296] opened 2023-10-24 21:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create IOU report with User B
3. Navigate to FAB> Start Chat
4. Enter the User B into search field

## Expected Result:
User B should appear as suggestion

## Actual Result:
After creating IOU report the user cannot be found on Start chat screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/c3e37675-f317-4225-9cd7-798f6760bd90

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a896149e5d91ffcc</li>
        <li>Upwork Job ID: 1716934053164417024</li>
        <li>Last Price Increase: 2023-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27895951</li>
<li>dukenv0307 | Contributor | 27895952</li>
</ul></li>
    </ul>
</details>

**Comment by iiredalert** [comment] 2023-10-25 04:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After adding a report with user B, they no longer appear in the start chat search result.

### What is the root cause of that problem?

In OptionsListUtils.js, we are including the user we are searching for in the personalDetails variable which in turn flips the noOptionsMatchExactly because 

```
option.login === searchValue.toLowerCase()
```
ends up being true once the search term equals the user's email address.

### What changes do you think we should make in order to solve the problem?

We can run the search excluding the personal details by setting includePersonalDetails to false in the getOptions function.  (call it direclty from NewChatPage, porting over the default values set in getFilteredOptions.

### What alternative solutions did you explore? (Optional)

 We could add special logic to ensure that the search value always appears in the result, still ensuring that it is a valid e-mail address or  phone number.

**Comment by abdulrahuman5196** [comment] 2023-10-27 14:55
Will review the proposals in my morning

**Comment by abdulrahuman5196** [comment] 2023-10-30 11:50
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-10-30 12:48
Did test and it seems not only IOU report, direct chat is also not coming. Will review the proposals and update before today.

**Comment by abdulrahuman5196** [comment] 2023-11-02 13:28
Sorry for the delay will review today

**Comment by MitchExpensify** [comment] 2023-11-05 21:28
Any update on the review @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment] 2023-11-07 13:51
Hey sorry missed this one. Will close out today. Or reassign if not.

**Comment by abdulrahuman5196** [comment] 2023-11-09 04:33
Reviewing now.

**Comment by mvtglobally** [comment] 2023-11-09 21:00
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2023-11-13 08:53
> Issue not reproducible during KI retests. (First week)

Will re-test issue.

Will review again today if reproducible, just back from weekend

**Comment by MitchExpensify** [comment] 2023-11-15 23:08
How did the review/testing go, @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2023-11-16 18:17
Checking now

**Comment by abdulrahuman5196** [comment] 2023-11-16 18:28
The issue is still reproducible

**Comment by abdulrahuman5196** [comment] 2023-11-16 20:26
@dukenv0307 Regarding your proposal here - https://github.com/Expensify/App/issues/30296#issuecomment-1778602547

>We have a note here to skip if we aren't including multiple participant reports and this report has multiple participants. So it doesn't make sense to add the check !reportOption.login here. Instead, we should check whether the participant of the report is multiple or not

This seems to be a good catch. But still for accounts which has actual name this fix alone is not solving the issue. I think its still missing a way to connect emailId to the chat. 

One other point is if I logout and login i am able to see the account in search result even without your changes, although it shows the email as a new account(for example abdulrahuman5196+1 account in the search which was requested at last login). There could also be some data clearance issue, if its working after re-login.


https://github.com/Expensify/App/assets/46707890/ed2359ca-43bc-4b65-8018-4c5bb5a81fb1

**Comment by abdulrahuman5196** [comment] 2023-11-20 13:01
Will check on the updated proposal

**Comment by abdulrahuman5196** [comment] 2023-11-21 17:43
I am still working on finalizing the review of the updated proposal here - https://github.com/Expensify/App/issues/30296#issuecomment-1815931695. Will try to close it out in a day.

**Comment by MitchExpensify** [comment] 2023-11-25 02:11
How's the review going @abdulrahuman5196 ?

**Comment by abdulrahuman5196** [comment] 2023-11-27 09:35
Rechecking again.

**Comment by abdulrahuman5196** [comment] 2023-11-27 10:55
@dukenv0307 's updated proposal here https://github.com/Expensify/App/issues/30296#issuecomment-1778602547 looks good and works well.

🎀 👀 🎀
C+ Reviewed

**Comment by MitchExpensify** [comment] 2023-11-29 22:11
@madmax330 does the proposal look good to you too?

**Comment by MitchExpensify** [comment] 2023-12-05 23:29
What's the latest on the PR progress here?

**Comment by MitchExpensify** [comment] 2023-12-21 14:17
Reminder set to pay on the 28th, please review the BZ when you have a chance - Thanks @abdulrahuman5196 !

**Comment by MitchExpensify** [comment] 2023-12-28 12:59
*Payment summary*:

- $500 @abdulrahuman5196 C+ (Upwork)
- $500 @dukenv0307 C (Upwork)

**Comment by MitchExpensify** [comment] 2023-12-28 13:02
Paid and contracts ended, friendly bump on the BZ steps @abdulrahuman5196 🙇

**Comment by abdulrahuman5196** [comment] 2023-12-28 18:15
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a single cause of this bug as regression

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Go to FAB > Request money
2) Create a request money with a new user
3) Go to FAB > Start chat
4) Enter the user whom we created request above
5) Verify that this user is displayed in start chat

Thank you @MitchExpensify . Added BZ steps as well.

**Closed** 2023-12-29 17:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
