### ISSUE TITLE
[HOLD for payment 2023-09-13] [HOLD for payment 2023-09-12] CRITICAL: Can't go back to LHN

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#26733] opened 2023-09-04 23:46 UTC
On mobile web if you go all the way into the request details and then tap back until the workspace, you can’t get back to the LHN. Pretty sure we need to reset the < on the workspace chat to go UP because there is no BACK at that point.

Test steps: 

1. Sign-up via the Saastr route with new public account e.g [staging.new.expensify.com/saastr](http://staging.new.expensify.com/saastr)
2. You’re navigated to the workspace chat on first sign-in
3. Tap the + icon > request money
4. create and send a request to the SaaStr workspace
5. Tap the expense report preview component to navigate to the expense report
6. Tap the request preview component to navigate to the request transaction thread
7. Tap `<` to navigate to the expense report
8. Tap `<` to navigate to the workspace chat
9. Tap `<` again and observe you go nowhere
10. Refresh the page
11. Tap `<` again and observe you’re navigated to the LHN

https://github.com/Expensify/App/assets/60117248/49e90145-d47b-4ddb-b3b7-a7b3aed9245b

**Comment by mountiny** [comment] 2023-09-05 05:07
I could not reproduce this in main

**Comment by mountiny** [comment] 2023-09-05 09:19
reproducible unreliably but can be, @adamgrzybowski is helping, I gave it a shot but got into a dead end, even if we call REPLACE the "sbe" stays sometimes in the stack which then just calls the demo again when trying to go up

**Comment by dylanexpensify** [comment] 2023-09-14 09:14
payment time!

**Comment by dylanexpensify** [comment] 2023-09-19 08:05
@mountiny anything due here?

**Comment by mountiny** [comment] 2023-09-19 08:27
Nothing required here, going to close this one as it was all internal and for the conference

**Closed by mountiny** 2023-09-19 08:27 UTC
Labels: Daily, Task, Awaiting Payment, Bug
