### ISSUE TITLE
Android - Categories - Category list opens & closes instantly with last few spend categories

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48676] opened 2024-09-06 05:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48391
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > Categories.
3. Tap Settings.
4. Scroll down to the bottom of the list.
5. Tap Utilities.

## Expected Result:
Category list will open without closiing.

## Actual Result:
Category list opens and closes instantly.
This issue happens with the categories at the bottom of the list.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e824d6c3-56a6-4030-94df-395016dd17ad

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MariaHCD** [comment] 2024-09-06 09:39
@BartoszGrajdek @ahmedGaber93 @BrtqKr Could you take a look at this deploy blocker?

This might be a regression from https://github.com/Expensify/App/pull/48391

**Comment by BartoszGrajdek** [comment] 2024-09-06 09:46
I'll look into it! 👀

**Comment by lakchote** [comment] 2024-09-06 16:30
CP requested [here](https://expensify.slack.com/archives/C07J32337/p1725640182048459)

**Comment by lakchote** [comment] 2024-09-06 18:46
QA tests passed since CP ([link](https://expensify.slack.com/archives/C9YU7BX5M/p1725641700250469?thread_ts=1725641215.569279&cid=C9YU7BX5M)).

Removing the deploy blocker label.

**Comment by MariaHCD** [comment] 2024-09-09 07:45
Thanks, all! 

Looks like the bug here was fixed in https://github.com/Expensify/App/pull/48708

Closing since there is no payment required here, I believe.

**Closed by MariaHCD** 2024-09-09 07:45 UTC
Labels: Reviewing, Engineering, Weekly, Bug
