### ISSUE TITLE
Tapping a task in a Concierge DM auto-expands the keyboard.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46678] opened 2024-08-01 17:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722471988185849

## Action Performed:
1. In mWeb chrome - creat a new account > tap track expense > tap Concierge
2. Tap the track an expense task in Concierge

## Expected Result:
The keyboard should never auto-expand unless an open text box is tapped
## Actual Result:
The keyboard auto-expands making task impossible to read
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [X] iOS: mWeb Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9cfc389f-7558-45c1-8488-641612b11a4d

https://github.com/user-attachments/assets/da8cdbad-563b-413e-98a6-b71132721b62

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-08-01 20:29
Can't reproduce. [Discussing ](https://expensify.slack.com/archives/C049HHMV9SM/p1722544152811909?thread_ts=1722471988.185849&cid=C049HHMV9SM)

**Comment by joekaufmanexpensify** [comment] 2024-08-02 13:45
Still pending slack discussion

**Comment by joekaufmanexpensify** [comment] 2024-08-05 13:24
will follow up

**Comment by joekaufmanexpensify** [comment] 2024-08-05 17:07
Chatted more in Slack, and we can't reproduce this anymore. Closing.

**Closed by joekaufmanexpensify** 2024-08-05 17:07 UTC
Labels: Daily, Bug

**Comment by joekaufmanexpensify** [comment] 2024-08-06 14:31
Hm, I think it is fine. Tasks have a text box for adding chatting, and we consistently focus on chat boxes on mobile when you open a page.
