### ISSUE TITLE
[Hold for #395046] [Search v1] [$500] Add a search bar on the workspaces list

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#38854] opened 2024-03-23 00:44 UTC
coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1711147247599549...

### Problem

If you have many workspaces on your workspaces list, it can be hard to find a particular one.

### Solution

Add a search bar to filter the workspaces list.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fc1028e9b86cc67</li>
        <li>Upwork Job ID: 1771337546180210688</li>
        <li>Last Price Increase: 2024-03-30</li>
<li>Automatic offers: </li>
<ul>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @GandalfGwaihir</details>

**Comment by hayes102** [comment] 2024-03-23 00:54
Hi Rory, can i make a proposal for this one? or is it already taken?

**Comment by nkdengineer** [comment] 2024-03-23 03:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a search bar on the workspaces list

### What is the root cause of that problem?
This is a new feature
### What changes do you think we should make in order to solve the problem?
We can re-use the filter logic in `WorkspaceSwitcherPage` to filter the workspace in `WorkspaceListPage`

1. Create a state for search term

```
const [searchTerm, setSearchTerm] = useState('');
```

2. Create a textInput component

```
const textInput = (
        <TextInput 
          defaultValue={searchTerm}
          onChangeText={(value) => {
              setSearchTerm(value);
          }}
          selectTextOnFocus
          spellCheck={false}
          iconLeft={MagnifyingGlass}
          placeholder={translate('workspace.switcher.placeholder')}
      />
  )
```
* Note: this is the main idea, other logics like focus, blur, ... of TextInput can be done on the PR

3. Update `listHeaderComponent` to include the search bar

```
const listHeaderComponent = useCallback(() => {
    const headerContent = isLessThanMediumScreen ? (
        <View style={styles.mt5} />
    ) : (
        <View style={[styles.flexRow, styles.gap5, styles.p5, styles.pl10, styles.appBG]}>
            <View style={[styles.flexRow, styles.flex1]}>
                <Text
                    numberOfLines={1}
                    style={[styles.flexGrow1, styles.textLabelSupporting]}
                >
                    {translate('workspace.common.workspaceName')}
                </Text>
            </View>
            <View style={[styles.flexRow, styles.flex1, styles.workspaceOwnerSectionTitle]}>
                <Text
                    numberOfLines={1}
                    style={[styles.flexGrow1, styles.textLabelSupporting]}
                >
                    {translate('workspace.common.workspaceOwner')}
                </Text>
            </View>
            <View style={[styles.flexRow, styles.flex1, styles.workspaceTypeSectionTitle]}>
                <Text
                    numberOfLines={1}
                    style={[styles.flexGrow1, styles.textLabelSupporting]}
                >
                    {translate('workspace.common.workspaceType')}
                </Text>
            </View>
            <View style={[styles.ml10, styles.mr2]} />
        </View>
    )

    return (
        <>
            <View style={[styles.gap5, styles.p5, styles.pl10, styles.appBG]}>
                {workspaces.length >= CONST.WORKSPACE_SWITCHER.MINIMUM_WORKSPACES_TO_SHOW_SEARCH && textInput}
            </View>
            {headerContent}
        </>
    );
}, [isLessThanMediumScreen, styles, translate, workspaces]);
```

4. Create a filter workspace variable, re-use the logic [here](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/WorkspaceSwitcherPage.tsx#L147)

```
const sortWorkspacesBySelected = (workspace1: WorkspaceItem, workspace2: WorkspaceItem, selectedWorkspaceID: string | undefined): number => {
    if (workspace1.policyID === selectedWorkspaceID) {
        return -1;
    }
    if (workspace2.policyID === selectedWorkspaceID) {
        return 1;
    }
    return workspace1.title?.toLowerCase().localeCompare(workspace2.title?.toLowerCase() ?? '') ?? 0;
};
const filteredAndSortedUserWorkspaces = useMemo(
    () =>
    workspaces
            .filter((policy) => policy.title?.toLowerCase().includes(searchTerm?.toLowerCase() ?? ''))
            .sort((policy1, policy2) => sortWorkspacesBySelected(policy1, policy2, activeWorkspaceID)),
    [searchTerm, workspaces, activeWorkspaceID],
);
```

5. Pass `filteredAndSortedUserWorkspaces` as the data of `FlatList`

```
data={filteredAndSortedUserWorkspaces}
```
https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/workspace/WorkspacesListPage.tsx#L410
### What alternative solutions did you explore? (Optional)
NA

### Result


https://github.com/Expensify/App/assets/161821005/f8dcaaaf-e830-4b63-bfab-d57a5da36d8e

**Comment by nayabatir1** [comment] 2024-03-23 08:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add search is workspace list

### What is the root cause of that problem?
This is a new feature

### What changes do you think we should make in order to solve the problem?
Added search bar in workspace list. Based on user input it will filter the list of workspace.

<details>
    <summary>Header Component</summary>
<img width="948" alt="image" src="https://github.com/Expensify/App/assets/91016903/201516ca-60e3-4686-bc21-b879697068a2">

</details>

<details>
<summary>Filter workspace logic</summary>

<img width="946" alt="image" src="https://github.com/Expensify/App/assets/91016903/4ae58abe-258a-41f9-8758-6019edd55a47">
</details>

<details>
<summary>Demo video</summary>

https://github.com/Expensify/App/assets/91016903/533cad91-da43-4ca0-a215-bc77fab22ecc
</details>

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by eVoloshchak** [comment] 2024-03-25 15:20
This is a feature request rather than a bug, so the first proposal to correctly explain the general idea of how to implement the feature - is a winning proposal. Extensive code diffs aren't needed ([Source](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md#what-alternative-solutions-did-you-explore-optional)), the exact details of the implementation can be worked out during the PR review

Based on that, I think we should proceed with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/38854#issuecomment-2016335583)
🎀👀🎀 C+ reviewed!

**Comment by wildan-m** [comment] 2024-03-26 02:04
To prevent such situations, I suggest removing the 'Help Wanted' tag if the issue is specific to a particular individual. If the proposed assignment is unsatisfactory, then we can consider adding the tag to seek alternative solutions. I've experienced the same situation [here](https://github.com/Expensify/App/issues/38748) 😆

**Comment by eVoloshchak** [comment] 2024-03-28 19:58
> i actually had the first dibs here, [context](https://expensify.slack.com/archives/C01GTK53T8Q/p1711154723380109?thread_ts=1711147247.599549&cid=C01GTK53T8Q):

@GandalfGwaihir, thanks for linking that!
In that case, @roryabraham, could you assign @GandalfGwaihir to this please?

**Comment by sonialiap** [comment] 2024-04-03 13:25
@GandalfGwaihir all yours, looking forward to having a workspace search! 🙏

**Comment by trjExpensify** [comment] 2024-04-03 19:04
I think we should park the breaks on this and wait for search v2 and introducing it consistently. We purposefully left it out of the v1 of the Workspaces page knowing we'd be working into a more holistic search design. CC: @Expensify/design

**Comment by shawnborton** [comment] 2024-04-03 19:07
I agree with that.

**Comment by JmillsExpensify** [comment] 2024-04-03 19:19
Agree with pausing this. It hasn't gone through our internal design process yet, though it will within the next 1-2 weeks, and at that point once we have alignment, we can pick this back up.

**Comment by trjExpensify** [comment] 2024-04-03 19:46
Going to track it as part of `[Search v1]` for now to keep it in view, though I'll likely update this to wherever we go with Search v2.

**Comment by eVoloshchak** [comment] 2024-04-15 17:08
Not overdue, this is on HOLD

**Comment by sonialiap** [comment] 2024-06-27 13:18
search v2 is being worked on here https://github.com/Expensify/Expensify/issues/395046

**Comment by sonialiap** [comment] 2024-06-28 07:59
Closing this out because it's a very long way from being implemented ([slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1719511944942239?thread_ts=1719399283.156149&cid=C01GTK53T8Q))

**Closed by sonialiap** 2024-06-28 07:59 UTC
Labels: External, Monthly, NewFeature, Not a priority
