### ISSUE TITLE
[HOLD for payment 2023-11-17] [$500] No text size change on bold on single backtick code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30203] opened 2023-10-23 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698062570837299

## Action Performed:
1. Open the app
2. Open any report
3. Send normal message, observe font-size for sent message
4. Send bold message (add # in beginning) and observe font-size for sent message, it will be bigger then normal message
5. Send normal single backtick code block eg: `Hello` and observe its font size
6. Send bold single backtick code block eg: # `Hello` and observe its font size, it is bold but font size is same as normal single backtick text

## Expected Result:
App should increase text size on bold (using #) of single backtick code block as it does for normal text

## Actual Result:
App keeps same text size on bold (using #) of single backtick code block as normal text size of single backtick code block

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![android native no bold text issue](https://github.com/Expensify/App/assets/93399543/5a890646-81d5-4e9a-90af-d99f1303e2f0)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 
![android chrome no bold text issue](https://github.com/Expensify/App/assets/93399543/ea0d8eb1-8210-4d8f-bf3c-de9f88b5f4ae)

</details>

<details>
<summary>iOS: Native</summary>

 
![ios native text size issue](https://github.com/Expensify/App/assets/93399543/76f02f85-c690-4d54-952a-71bffe27ef9c)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 
![ios safari text size issue](https://github.com/Expensify/App/assets/93399543/0998ce0b-407f-47a9-bcfd-17921888ee0e)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 
![mac chrome text size issue](https://github.com/Expensify/App/assets/93399543/cba59ec3-f5d2-41be-bd23-03fbbe524391)

https://github.com/Expensify/App/assets/93399543/39c8c2d8-85c9-4223-9355-e548faf0d65c

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![mac desktop text size issue](https://github.com/Expensify/App/assets/93399543/7a35c325-6d52-42cf-be4a-ec14f1798803)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b5dbaab7f1156a1</li>
        <li>Upwork Job ID: 1716547328191115264</li>
        <li>Last Price Increase: 2023-10-23</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 27506802</li>
<li>dhanashree-sawant | Reporter | 27506803</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by yakupafsin** [comment] 2023-10-23 23:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The problem we aim to address in this issue is the incorrect rendering of messages with bold styling (messages starting with `#`) or when code is sent as a message, resulting in different font sizes.

### What is the root cause of that problem?

The root cause of this problem lies in the way the backend handles such messages. When a user sends a message with bold styling (starting with #), the backend saves this message using the `<h1>` HTML tag. Consequently, in the frontend, when a message contains HTML tags, it is rendered with styles that deviate from the default ones. This is due to the fact that in the style files, under the `webViewStyles` section, the `<h1>` tag is assigned a font size of `variables.fontSizeLarge` while a normal message is styled with `variables.fontSizeNormal`. This discrepancy leads to messages being displayed with varying font sizes.

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we should make the following changes:
* 		Change the font size for the `<h1>` tag to `variables.fontSizeNormal`
* 		Adjust the font size for the `<code>` tag to `variables.fontSizeNormal`
The relevant style code changes should be implemented in the following sections of the codebase:



The style codes needs to be changed:

https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/styles/styles.ts#L177-L184

https://github.com/Expensify/App/blob/112061b732fec0273fb619ca53a4fd98496c4615/src/styles/styles.ts#L197-L200


### What alternative solutions did you explore? (Optional)

N/A


<details><summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/66640310/649de82d-68d1-47d1-8174-6ca61c0ecdb4



</details>

**Comment by s77rt** [comment] 2023-10-24 08:31
@yakupafsin Thanks for the proposal. But you are fixing the wrong bug here. What we are looking is to have the heading message always rendered with fontSizeLarge. i.e.

```
# msg
```

 should be rendered with fontSizeLarge (already working)
```
# `msg`
```
 should be rendered with fontSizeLarge as well but it's not (bug is here)

**Comment by yakupafsin** [comment] 2023-10-24 09:10
> @yakupafsin Thanks for the proposal. But you are fixing the wrong bug here. What we are looking is to have the heading message always rendered with fontSizeLarge. i.e.
> 
> ```
> # msg
> ```
> 
> should be rendered with fontSizeLarge (already working)
> 
> ```
> # `msg`
> ```
> 
> should be rendered with fontSizeLarge as well but it's not (bug is here)

Hi, sorry. I guess it was too late I made a mistake. But I've edited my proposal and it's aiming the right problem now.

**Comment by yakupafsin** [comment] 2023-10-24 12:07
> @yakupafsin Thanks for the proposal. But you are fixing the wrong bug here. What we are looking is to have the heading message always rendered with fontSizeLarge. i.e.
> 
> ```
> # msg
> ```
> 
>  should be rendered with fontSizeLarge (already working)
> ```
> # `msg`
> ```
>  should be rendered with fontSizeLarge as well but it's not (bug is here)
> 
> 
> 

Do I have to send it again, or just editing enough?

**Comment by s77rt** [comment] 2023-10-24 12:36
@yakupafsin Thanks for the update. I don't think we can just omit the font size. This will make code tag text render at size 15px which does not seem intended. 


> Do I have to send it again, or just editing enough?

Editing is enough

**Comment by yakupafsin** [comment] 2023-10-24 20:20
@s77rt, I have revised my solution. This time, it only changes the font size if the element is a child of an `<h1>` tag. However, I would still recommend not keeping the font size as 13 for code blocks. We can change it to use `variable.fontSizeNormal`. I didn't include this in the proposal because it's not part of this specific issue, but in the future, it could potentially cause problems with other devices if we leave it at 13.

**Comment by s77rt** [comment] 2023-10-25 01:33
@yakupafsin Thanks for update. The use of size 13px for code tags is [intended](https://github.com/Expensify/App/pull/2307#issuecomment-816283297) to keep the outer height consist with the rest of the text. Similarly for code tags under h1, we don't want to apply 17px but 14.5px. Can you please update your proposal based on that?

___

cc @shawnborton To 👀 the below changes (changed font size of code tag if it's inside a heading message from 13px to 14.5px)

Before:
<img width="701" alt="Screenshot 2023-10-25 at 2 15 06 AM" src="https://github.com/Expensify/App/assets/16493223/d28c5b52-c198-417f-abe4-aeb1d1656e83">

After:
<img width="701" alt="Screenshot 2023-10-25 at 2 14 49 AM" src="https://github.com/Expensify/App/assets/16493223/91c13ee9-751a-4437-a229-781b3aee21a6">

**Comment by yakupafsin** [comment] 2023-10-25 08:47
@s77rt I've applied the changes. Because on previous comment you mentioned that 

> What we are looking is to have the heading message always rendered with fontSizeLarge.

**Comment by shawnborton** [comment] 2023-10-25 13:00
How did we arrive at 14.5? I am not a fan of using a half-pixel font size here. If anything, can we use 15px since we use that font size elsewhere? cc @Expensify/design for visibility here

**Comment by yakupafsin** [comment] 2023-10-25 14:14
@shawnborton yes I can change it with 15. Or I can just use the one of the values from style page. Whatever best for the app.

**Comment by shawnborton** [comment] 2023-10-25 14:18
15 should be the default font size of the app, so I like just grabbing that for the size var.

**Comment by yakupafsin** [comment] 2023-10-25 14:39
@s77rt In the same proposal, we can include this change and handle it with a single pull request (PR). I suggest taking the font size of the h1 element and applying 85% of that size to the code tag, as shown in the code snippet below:

'fontSize = h1FontSize/100*85'

Please note that this is just an example, and the actual code may differ.

**Comment by shawnborton** [comment] 2023-10-25 14:50
Understood, but I still would prefer 15 so we don't need to manage another font size.

**Comment by s77rt** [comment] 2023-10-25 15:04
Got it. Thanks!

@yakupafsin Let's get this fixed 🚀 

🎀 👀 🎀 C+ reviewed
[Link to proposal
](https://github.com/Expensify/App/issues/30203#issuecomment-1776167351)

**Comment by abeebridwan** [comment] 2023-10-25 15:29
I know I am late 
just about to submit it... 

Not taking the proposal 
I want you to look it from here
Here is what I found 

textStyle applied to both are the same ... which came from the backend
the sending and receiving of the text are all good except the styles

![image](https://github.com/Expensify/App/assets/66317334/57f0649e-3b38-4d5a-88a4-b2e8f6b1a05b)

the merging and overring of the styles happens here
![image](https://github.com/Expensify/App/assets/66317334/cc872368-98e4-420a-a602-1fba7d89dd91)

**Comment by abeebridwan** [comment] 2023-10-25 15:33
it could be fixed by sending right styles based on `<code> hello</code> vs <h1> <code>hello</code></h1>`

**Comment by abeebridwan** [comment] 2023-10-25 15:35
Also in the <Text> there is already default `font-size: 15px`

**Comment by s77rt** [comment] 2023-10-25 15:37
@abeebridwan The styles are defined in the frontend https://github.com/Expensify/App/blob/d4d9f78be5d54e18d71b9a6c1881734dea3e7780/src/styles/styles.ts#L118.

**Comment by abeebridwan** [comment] 2023-10-25 15:52
Thanks 
Oh I see. I actually thought they came from Onyx

**Comment by yakupafsin** [comment] 2023-10-25 17:29
Hi @s77rt, do I have to wait until the issue is assigned to my name before I can create a PR? 
(It's my first PR on the Expensify app.)

**Comment by s77rt** [comment] 2023-10-25 17:54
@yakupafsin Yes. Please wait for the engineer review

**Comment by yakupafsin** [comment] 2023-10-25 17:55
@s77rt thank you 😊. Just wanted to make sure.

**Comment by yakupafsin** [comment] 2023-10-28 13:51
Hi @s77rt , I just want to double-check if there is any update?

**Comment by s77rt** [comment] 2023-10-28 14:44
@yakupafsin No update yet.

**Comment by laurenreidexpensify** [comment] 2023-10-30 11:18
@roryabraham pls assign if proposal works thanks

**Comment by laurenreidexpensify** [comment] 2023-11-01 11:46
@roryabraham bump ^^

**Comment by roryabraham** [comment] 2023-11-03 15:45
Very sorry for the delay here. @yakupafsin's proposal looks good, with one modification. Rather than just checking the parent, let's traverse up the tree until we reach the top or find an H1. Some function like `isDescendentOf`.

**Comment by yakupafsin** [comment] 2023-11-03 16:48
@roryabraham Thank you for reviewing the proposal. I've sent my proposal on UpWork. Do I have to wait until I've been hired for the project, or can I send my PR straight away?

**Comment by s77rt** [comment] 2023-11-03 16:51
@yakupafsin You can raise the PR now. You will be hired on Upwork only for the payment (everything else is done in Github / Slack)

**Comment by roryabraham** [comment] 2023-11-08 20:07
PR merged

**Comment by s77rt** [comment] 2023-11-11 21:20
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/2307
- The offending PR has been commented on: https://github.com/Expensify/App/pull/2307#discussion_r1390287531
- A discussion in #expensify-bugs has been started: I don't think this is needed here
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Open any report
2. Send a normal message e.g. Hello Expensifiers 
3. Send a heading message (add # in beginning) e.g. # Hello Expensifiers
4. **Verify** that the font size of the heading message is bigger than that of the normal message
5. Send a normal single backtick code block e.g. `Hello Expensifiers`
6. Send a heading single backtick code block e.g. # `Hello Expensifiers`
7. **Verify** that the font size of the heading message is bigger than that of the normal message

**Comment by laurenreidexpensify** [comment] 2023-11-20 12:01
Automation failed here - issuing payments now

**Comment by laurenreidexpensify** [comment] 2023-11-20 12:05
Payment Summary:

- C+ - @s77rt $500 - payment issued in Upwork 
- Contributor - $500 - @yakupafsin requires payment
- Bug Report - $50 @dhanashree-sawant payment issued in Upwork

**Comment by laurenreidexpensify** [comment] 2023-11-20 12:11
Final Step: Issue payment to @yakupafsin in Upwork once they accept request

**Comment by yakupafsin** [comment] 2023-11-20 12:16
@laurenreidexpensify offer accepted, Thank you.

**Comment by laurenreidexpensify** [comment] 2023-11-21 10:40
Payment Summary:

C+ - @s77rt $500 - payment issued in Upwork
Contributor - $500 - @yakupafsin requires payment issued in Upwork
Bug Report - $50 @dhanashree-sawant payment issued in Upwork

**Closed by laurenreidexpensify** 2023-11-21 10:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
