### ISSUE TITLE
[HOLD for payment 2024-12-16] [$125] Error message displayed when adding a UK zip code to a GBP payment card 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52642] opened 2024-11-15 18:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @muttmuure 
**Slack conversation** (hyperlinked to channel name):  [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1731500192445509)

## Action Performed:
1. Go to Settings
2. Go to Subscriptions
3. Click Add a payment card
4. Change the currency to GBP
5. Add a Zip Code

## Expected Result:
A UK post code is accepted

## Actual Result:
The Zip Code field shows an error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![Snip - (2) New Expensify - Google Chrome (2)](https://github.com/user-attachments/assets/4535c58e-b191-40a6-a187-1aaa6185c362)

![Snip - (2) New Expensify - Google Chrome](https://github.com/user-attachments/assets/56b3325f-44e7-4fd9-93ad-57f2f6016d87)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021857542773027117579</li>
        <li>Upwork Job ID: 1857542773027117579</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 105099990</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by sakluger** [comment] 2024-11-15 21:54
This seems like a pretty easy change. I'm going to set the initial price at $125.

If this needs to be done for several countries, and each one requires specific treatment, then we can consider a higher price, but it doesn't seem like that's necessary for now.

**Comment by ikevin127** [comment] 2024-11-16 02:34
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Error message displayed when adding a UK zip code to a GBP payment card.

### What is the root cause of that problem?

The current `PaymentCardForm.tsx` component's [`validate`](https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/components/AddPaymentCard/PaymentCardForm.tsx#L145-L177) function, specifically the Zip Code validation logic is the root cause of our issue as it only validates US Zip Code regardless of the selected Currency.

https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/components/AddPaymentCard/PaymentCardForm.tsx#L168-L170

### What changes do you think we should make in order to solve the problem?

Adjust the validate logic similarly to what we do in [Address / AddressForm](https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/components/AddressForm.tsx#L112-L131) which is Zip Code validation based on the selected country, in our case for a more comprehensive solution we'll validate Zip Code based on selected Currency.

To do this we will add / adjust the following:
1. In `CurrencyUtils`create a new function called `getCurrencyCountryCodes` which will take as argument `currencyCode` and return an array with the country code / codes using that currency:

```ts
/**
 * Get the country code for a certain currency(ISO 4217) Code
 */
function getCurrencyCountryCodes(currencyCode: keyof typeof CONST.CURRENCY): Array<keyof typeof CONST.ALL_COUNTRIES> {
    const currencyCountryMap: Record<keyof typeof CONST.CURRENCY, Array<keyof typeof CONST.ALL_COUNTRIES>> = {
        [CONST.CURRENCY.USD]: ['US'],
        [CONST.CURRENCY.AUD]: ['AU'],
        [CONST.CURRENCY.CAD]: ['CA'],
        [CONST.CURRENCY.GBP]: ['GB'],
        [CONST.CURRENCY.NZD]: ['NZ'],
        [CONST.CURRENCY.EUR]: ['AT', 'BE', 'CY', 'EE', 'FI', 'FR', 'DE', 'GR', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PT', 'SK', 'SI', 'ES'],
    };

    return currencyCountryMap[currencyCode] ?? [];
}
```

2. Within the `PaymentCardForm.tsx` component in the [`validate`](https://github.com/Expensify/App/blob/99bf5541f9d49da20952bd7f2592b7e773a6073b/src/components/AddPaymentCard/PaymentCardForm.tsx#L145-L177) function replace the current Zip Code validation logic with the following:

```ts
// Use provided currency or default to USD
const currency = data?.currency ?? CONST.PAYMENT_CARD_CURRENCY.USD;
// Get countries associated with the currency
const countries = CurrencyUtils.getCurrencyCountryCodes(currency);

// Check if the addressZipCode matches any country-specific regex
if (values.addressZipCode) {
    const zipCode = values.addressZipCode.trim();
    const isValidZip = countries.some((countryCode) => {
        const regexDetails = CONST.COUNTRY_ZIP_REGEX_DATA[countryCode];
        // Optionally: check for empty string after trim
        if (!zipCode) {
            return false;
        }

        return 'regex' in regexDetails && regexDetails.regex.test(zipCode);
    });

    if (!isValidZip) {
        errors.addressZipCode = translate(label.error.addressZipCode);
    }
}
```

this will ensure that the Zip Code is validated based on the currency selected in the **Add payment card**, defaulting to USD just like the Currency field.

Here's a test branch: [ikevin127-cardZipCodeValidation](https://github.com/Expensify/App/compare/main...ikevin127:Expensify:ikevin127-cardZipCodeValidation) for testing convenience or the [diff](https://github.com/Expensify/App/compare/main...ikevin127:Expensify:ikevin127-cardZipCodeValidation.diff) if preferred.

### Result video (before / after)

<details>
<summary>MacOS: Chrome</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/6e482eaa-ae88-41c5-8618-2813e4176d0c"> | <video src="https://github.com/user-attachments/assets/ad4cf0b2-1c35-4a6f-bad1-062486d8340e"> |

</details>

**Comment by ikevin127** [comment] 2024-11-16 03:00
> If this needs to be done for several countries, and each one requires specific treatment, then we can consider a higher price, but it doesn't seem like that's necessary for now.

@sakluger In the [proposed solution](https://github.com/Expensify/App/issues/52642#issuecomment-2480341251) I made sure to include logic for each specific currency / country and also for the `EUR` currency which is used in multiple european countries. Even though the current `Add payment card` currency selector stops at `NZD`, I wanted the solution to be future proof as we might add `EUR` to the list.

I'd say that justifies the base $250 bounty for this issue **in case the proposed solution will be the one selected**. Thank you!

**Comment by sakluger** [comment] 2024-11-18 17:08
> I'd say that justifies the base $250 bounty for this issue in case the proposed solution will be the one selected. Thank you!

@ikevin127 that sounds fair to me! If your solution is selected, then I will increase the price to $250.

**Comment by ikevin127** [comment] 2024-11-18 19:36
@getusha Are you sure you read my proposal ? Asking because I'm confused by your note since I did use `COUNTRY_ZIP_REGEX_DATA` in the solution I proposed.

**Comment by YahyaDalbah** [comment] 2024-11-18 19:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message displayed when adding a UK zip code to a GBP payment card

### What is the root cause of that problem?
We only check valid US zip code and not check valid UK zip code
https://github.com/Expensify/App/blob/8e1b0fde744d47298042991a8f52a3a0a04d0e53/src/components/AddPaymentCard/PaymentCardForm.tsx#L168-L170

### What changes do you think we should make in order to solve the problem?
we must handle UK zip code when the GBP currency is selected

1. make a new util function in `ValidationUtils.ts`
```
function isValidUKZipCode(zipCode: string): boolean {
    return CONST.COUNTRY_ZIP_REGEX_DATA.GB.regex.test(zipCode);
}
```

2. update `validate`  function in `PaymentCardForm.tsx` [here](https://github.com/Expensify/App/blob/main/src/components/AddPaymentCard/PaymentCardForm.tsx#L168)
```
if (values.currency == CONST.PAYMENT_CARD_CURRENCY.GBP) {
    if (values.addressZipCode && !ValidationUtils.isValidUKZipCode(values.addressZipCode)) {
        errors.addressZipCode = translate(label.error.addressZipCode);
    }
} else {
    if (values.addressZipCode && !ValidationUtils.isValidZipCode(values.addressZipCode)) {
        errors.addressZipCode = translate(label.error.addressZipCode);
    }
}
```

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-11-18 20:00
@getusha If by generic regex you mean simply allowing any postcode then we might as well remove any validation as we're not interested in actually validating based on each country's regex.

The reason why I propose validating based on currency is because especially in the US, if you don't input the Zip Code matching the card - the bank will reject authorization / payment.

## Updated proposal

Added alternative solution where we map over all `CONST.COUNTRY_ZIP_REGEX_DATA` countries regex and allow Zip Codes matching any of our available countries.

Hopefully this will satisfy, otherwise I need more specificity on what exactly you're expecting in terms of solution here.

**Comment by YahyaDalbah** [comment] 2024-11-18 20:01
Contributor details
Your Expensify account email: yahya1dalbah@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018af63917b9a4424c

**Comment by ikevin127** [comment] 2024-11-18 20:49
@getusha You are not making any sense honestly, first you say:

> we already have COUNTRY_ZIP_REGEX_DATA, i suggest you to have a look at AddressForm/Profile/Address page component. i don't think there is a need to create a new utility function.

Then when I suggested 2 different solutions using `COUNTRY_ZIP_REGEX_DATA` you say that they are not good enough because one is validating Zip Code based on currency and the other "might" cause performance issues.

I don't understand what are your expectations in this case, can you clarify ?

**Also please test the solutions and come back with solid proof that the solution does introduce performance issues, because "might" means nothing.**

Let me know if you have the capacity to do that and want to review this issue properly, otherwise I will propose re-assigning another reviewer. Thanks!

**Comment by ikevin127** [comment] 2024-11-18 21:04
@sakluger Could you please help pull in somebody from the team who's assigned to the cards flow to clarify whether or not it's expected to validate Zip Code based on selected currency or some other criteria ?

Asking because the way this issue is presented it leads contributors to think that it is wxpected that when GBP is selected -> validate UK Zip Code and the reviewer seems to think we shouldn't do that.

I feel like we're assuming a lot and investing time in proposals / reviews but we don't know the requirements for sure.

**Comment by ikevin127** [comment] 2024-11-18 22:07
Cool, I agree and thanks for clarifying!

### Updated [proposal](https://github.com/Expensify/App/issues/52642#issuecomment-2480341251)
- added 3rd alternative for a more generic Zip Code validation as suggested in https://github.com/Expensify/App/issues/52642#issuecomment-2484212088

**Comment by sakluger** [comment] 2024-11-19 22:21
I asked [in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1732054782674749?thread_ts=1731500192.445509&cid=C049HHMV9SM) whether we can be 100% certain that a GBP currency payment card will have a UK postal code. I'll report back here once I get confirmation.

**Comment by sakluger** [comment] 2024-11-21 16:22
We can be reasonably certain that a GBP currency payment card will have a UK postal code, or a similarly formated postal code. We wouldn't expect someone with a US postal code to enter a GBP payment card.

**Comment by sakluger** [comment] 2024-11-22 16:17
We have four billing currencies - USD, GBP, AUD, and NZD. I'm going to ask how we validate the billing card postal code field  in OldDot, because I assume we should just reuse that logic.

**Comment by sakluger** [comment] 2024-11-25 16:06
FYI I asked [here in Slack](https://expensify.slack.com/archives/C03SSAQ7P/p1732292767903449). I'm still waiting for a response so I bumped my question.

**Comment by sakluger** [comment] 2024-11-26 17:48
I heard back from the team and discovered that there is no postal code validation in OldDot (none in frontend or backend). I also checked with the people who lead the project to add billing cards to NewDot, and they think that we should copy OldDot.

That means that **we should remove all postal code validation from NewDot**. @daledah @ikevin127 @YahyaDalbah could you please update your proposals with the new guidance if you'd like to be considered? Thanks!

**Comment by ikevin127** [comment] 2024-11-26 19:23
@getusha I already suggested removing any specific Zip Code validation in my proposal, **Alternative solution 2**.

**Comment by MitchExpensify** [comment] 2024-11-26 19:58
This impacted renan.picoli@fauke.com.br too, FullStory session here https://app.fullstory.com/ui/o-1WN56P-na1/session/1095778184561457754:1095778184561457754!3940192719987210063

**Comment by ikevin127** [comment] 2024-11-27 00:04
♻️ **Update regarding the issue**: I drafted the PR already, awaiting to be assigned so I can open it.

While testing the fix, I noticed that on mWeb platforms the keyboard was locked to numeric because of this line:

https://github.com/Expensify/App/blob/c4ff235cbfb6bc6582a3bb045b813e4d43151135/src/components/AddPaymentCard/PaymentCardForm.tsx#L289

As part of the PR I removed that line as well since UK Zip Codes contain both **characters** and **numbers**, therefore we don't want to restrict users to numeric input only. More details in this PR https://github.com/Expensify/App/pull/53178#discussion_r1859425470.

**Comment by ikevin127** [comment] 2024-11-27 19:48
PR https://github.com/Expensify/App/pull/53178 is ready for review! 🚀

**Comment by ikevin127** [comment] 2024-11-29 20:20
♻️ **Status update**: PR has been open and ready for review 2 days ago, awaiting @getusha's review.

**Comment by ikevin127** [comment] 2024-12-02 22:12
♻️ **Status update**: PR has been open and ready for review for 5 days, still awaiting @getusha's review.
Bumped in the PR as well - awaiting a response.

**Comment by trjExpensify** [comment] 2024-12-03 23:00
Just as a bit of a follow-up here if that PR is almost done and dusted, but I think we should change the label name to `Zip / Postcode` to match the label name found in the form on profile > private > address. Only the US uses "Zip code" terminology.

**Comment by ikevin127** [comment] 2024-12-03 23:05
@trjExpensify Sure, will change the label before the PR gets merged - linking to your comment for the reason.

**Comment by trjExpensify** [comment] 2024-12-03 23:08
Excellent!

**Comment by ikevin127** [comment] 2024-12-12 19:27
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment] 2024-12-16 20:34
@sakluger for visibility

**Comment by sakluger** [comment] 2024-12-17 18:07
Summarizing payment on this issue:

Contributor: @ikevin127 $125, paid via Upwork
Contributor+: @getusha $125, please request on Newdot

**Closed by sakluger** 2024-12-17 18:07 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2025-01-29 21:08
$125 approved for @getusha
