### ISSUE TITLE
[HOLD #44582] Workspace - Distance rate enabled offline when creating the workspace online not grayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44163] opened 2024-06-21 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nahummelaku9+A3@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in to staging.new.expensify.com
2. Create a new workspace
3. Navigate to more features
4. Go offline
5. Enable Distance rates
6. Navigate to Distance rates

## Expected Result:
List of rates should be grayed out.

## Actual Result:
List of rates is not grayed out.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9548f7c8-7688-4875-a5c9-f25255037f34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-06-21 14:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The distance rates aren't grayed out when enabling the distance rate while offline.

### What is the root cause of that problem?
When we create a new workspace, the distance rates are already added to the workspace. When the workspace creating is still pending, we also add it as the distance rate pending action.
https://github.com/Expensify/App/blob/7512346c2fd5c03882e3f9951b03530d8cbf7972/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L118

After the request is complete, there is no pending action anymore. When we enable the distance rate, the list won't be grayed out because the pending action is already done.

### What changes do you think we should make in order to solve the problem?

If we still want to grayed it out when enabling it while offline, then we can add a 
`policy?.pendingFields?.areDistanceRatesEnabled,`
condition so it's grayed out when the distance rate is enabled while offline.
https://github.com/Expensify/App/blob/7512346c2fd5c03882e3f9951b03530d8cbf7972/src/pages/workspace/distanceRates/PolicyDistanceRatesPage.tsx#L113-L118

**Comment by mallenexpensify** [comment] 2024-06-21 20:05
[Checking on in  #wave-collect
](https://expensify.slack.com/archives/C036QM0SLJK/p1719000280371749)
> Noticing[ a lot of Offline Distance issues lately. ](https://github.com/Expensify/App/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+distance+offline)Are these being addresses holistically anywhere?  (asking cuz I'm [assigned to one ](https://github.com/Expensify/App/issues/44163#issuecomment-2182894960)and considering next steps)

**Comment by OfstadC** [comment] 2024-06-21 21:00
[This](https://github.com/Expensify/App/issues/44154) seems pretty similar

**Comment by mallenexpensify** [comment] 2024-06-24 22:22
Yeah, please hold here, trying to figure out a holistic plan, since there are a lot of these

**Comment by OfstadC** [comment] 2024-06-25 17:23
Sounds good Matt!

**Comment by mallenexpensify** [comment] 2024-06-28 00:14
@paultsimura , please comment so I can assign to you

**Comment by mallenexpensify** [comment] 2024-07-08 22:45
@paultsimura I _think_ the vid is supposed to show that there's discrepancy when creating new workspaces and then going offline and adjusting the mileage rate. I'm assuming that when a new workspace is created, we're not _carrying over_ any distance rate info from other workspaces, is that correct?

**Comment by mallenexpensify** [comment] 2024-07-09 23:59
Stepping back, to make sure I'm understanding things.  From the vid it appears the user creates a new workspace, goes offline, _does_ distance and the mileage rate is greyed out. They then do the same (or very similar) steps again and that time, the mileage rate isn't greyed out.  Is that correct? And, if so, do you know what that's happening?

**Comment by mallenexpensify** [comment] 2024-07-12 00:04
Thx for the details @paultsimura , sounds like we should close this then, it's working as expected.  Right?

**Closed** 2024-07-15 21:04 UTC
Labels: Weekly, Bug
