### ISSUE TITLE
[HOLD] [$250] [MEDIUM] Smartscan: Receipt thumbnail should show the top of the receipt

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34120] opened 2024-01-09 05:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-6
**Reproducible in staging?:** yes
**Reproducible in production?:**.yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704757554079199

## Action Performed:
1. create an IOU using receipt scanning
2. Observe the thumbnail of the receipt

## Expected Result:
Should be showing from the top of the receipt

## Actual Result:
Showing the middle portion of the receipt

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-01-09 at 12 00 13 AM](https://github.com/Expensify/App/assets/38435837/7db0c2de-aab4-4490-bab9-45048580d3e4)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019bb6b442f89fba02</li>
        <li>Upwork Job ID: 1744585981661257728</li>
        <li>Last Price Increase: 2024-04-24</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 28117185</li>
<li>dukenv0307 | Contributor | 28117186</li>
</ul></li>
    </ul>
</details>

**Comment by aswin-s** [comment] 2024-01-09 08:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Receipt thumbnail is not showing the top of the image

### What is the root cause of that problem?

For displaying a [receipt](https://github.com/Expensify/App/blob/85fee5aeb683729aac48300c71da932a8049b83f/src/components/ReportActionItem/ReportActionItemImage.js#L70-L76) `<ThumbnailImage/>` [component](https://github.com/Expensify/App/blob/85fee5aeb683729aac48300c71da932a8049b83f/src/components/ThumbnailImage.tsx#L97) is used with `shouldDynamicallyResize` prop set to false. This causes the image to fill to the given container width and height. However the `ImageWithSizeCalculation` component [covers the image](https://github.com/Expensify/App/blob/85fee5aeb683729aac48300c71da932a8049b83f/src/components/ImageWithSizeCalculation.tsx#L78) to available width and height. This ensures that the displayed image properly covers the parent container. However a side effect of cover is that the image gets scaled and positioned such that it entirely covers the container, there by causing the vertical or horizontal alignment of image to be adjusted as needed.

### What changes do you think we should make in order to solve the problem?

For always displaying the top section of receipt thumbnail, the image container width needs to be set to the width of thumbnail and the height should be set as per aspect ratio of the image. This makes sure that the thumbnail image gets rendered fully and not get scaled or repositioned due to 'cover'.

```tsx
function ThumbnailImage({previewSourceURL, style, isAuthTokenRequired, imageWidth = 200, imageHeight = 200, shouldDynamicallyResize = true}: ThumbnailImageProps) {
    // Use a variable to save container width on layout
    const [containerWidth, setContainerWidth] = useState(100);
    ...

    // Now compute the aspect ratio of the image
    const aspectRatio = currentImageWidth && currentImageHeight ? currentImageWidth / currentImageHeight : 1;

    // Set the thumbnail height as per image aspect ratio
    const sizeStyles = shouldDynamicallyResize ? [StyleUtils.getWidthAndHeightStyle(currentImageWidth ?? 0, currentImageHeight)] : [styles.w100, {height: containerWidth / aspectRatio}];

    return (
        <View
            style={[style, styles.overflowHidden]}
	    // Get container width 
            onLayout={(e) => setContainerWidth(e.nativeEvent.layout.width)}
        >
            <View style={[...sizeStyles, styles.alignItemsCenter, styles.justifyContentCenter]}>
                <ImageWithSizeCalculation
                    url={previewSourceURL}
                    onMeasure={updateImageSize}
                    isAuthTokenRequired={isAuthTokenRequired}
                />
            </View>
        </View>
    );
```

Above logic also handles images whose width is larger than height. Also the logic works for both native and web platforms.

There are a couple of screens like MoneyRequestConfirmationList and ReportActionItemImage etc where Image component is used instead of ThumbnailImage for displaying receipt. Such instances need to be replaced so that all occurrences of receipt image is properly displayed

Result

**iOS**

https://github.com/Expensify/App/assets/6880914/2c14b40c-990b-4056-a262-2c7f39960b48 

**Web**

https://github.com/Expensify/App/assets/6880914/615f7472-e5b7-46a2-b877-11bd17426f65 





### What alternative solutions did you explore? (Optional)
None (edited)

**Comment by shubham1206agra** [comment] 2024-01-09 08:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
 
Receipt thumbnail is not showing the top of the image

### What is the root cause of that problem?

Inside `ReportActionItemImage`, the `ThumbnailImage` component is being used. But this component uses `100%` for height and width, which makes image center (looks like center but not exactly). 

### What changes do you think we should make in order to solve the problem?

We need to use `aspectRatio` technique to properly scale the images so that always top can be shown. We need to correctly scale the images for `landscape`, and `portrait` images.

Test branch - https://github.com/shubham1206agra/App/tree/test-thumbnail

Note - Naming of function is not final.

### What alternative solutions did you explore? (Optional)

NA

**Comment by aswin-s** [comment] 2024-01-09 08:52
Noted @dukenv0307. My proposal has just one approach detailed which works on all platforms. I've tested on both iOS and web and shared the screen grabs as well. I've also addressed scenarios like serving local image when receipt upload is in progress in the above video. So it is not exactly same or abstract like your proposal.

I'll leave the merit of the proposal to the C+.

**Comment by shubham1206agra** [comment] 2024-01-09 08:53
> Noted @dukenv0307. My proposal has just one approach detailed which works on all platforms. I've tested on both iOS and web and shared the screen grabs as well. I've also addressed scenarios like serving local image when receipt upload is in progress in the above video. So it is not exactly same or abstract like your proposal.
> 
> I'll leave the merit of the proposal to the C+.

Don't worry. C+ will take care of these things :)

**Comment by cubuspl42** [comment] 2024-01-09 09:22
@dukenv0307 

I'll first ask about your main solution.

> object-position: top

I assume you mean the [`object-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position) CSS property. How would this solve the problem on all supported platforms?

@aswin-s @shubham1206agra 

Do I understand correctly that you suggest modifying the logic of `ThumbnailImage`, so it always aligns to the top? Does this component have other usages, where we might prefer different alignment?

@shubham1206agra 

Are `landscape` and `portrait` some code / CSS constants?

Do I understand correctly that you, like @aswin-s, suggest adjusting the math of `ThumbnailImage`, but in a different way?

**Comment by shubham1206agra** [comment] 2024-01-09 09:27
> Do I understand correctly that you suggest modifying the logic of `ThumbnailImage`, so it always aligns to the top? Does this component have other usages, where we might prefer different alignment?

I have a prop to control that `shouldShowTop`, if it is `false`, then it will revert to older configuration (`100%` one).

> Are `landscape` and `portrait` some code?

No, its image orientation.

![image](https://github.com/Expensify/App/assets/58412969/fe31a17f-a3b9-440c-aead-7a8232a83b8d)

> Do I understand correctly that you, like @aswin-s, suggest adjusting the math of `ThumbnailImage`, but in a different way?

Yes

**Comment by aswin-s** [comment] 2024-01-09 09:38
> @aswin-s @shubham1206agra
> 
> Do I understand correctly that you suggest modifying the logic of `ThumbnailImage`, so it always aligns to the top? Does this component have other usages, where we might prefer different alignment?

@cubuspl42  Yes my proposal is to modify the logic in `ThumbnailImage` component so that the image aligns to top when `shouldDynamicallyResize` is set to false. 

Thumbnail component is used currently for Image attachment previews and Receipt previews.  For image attachments in ReportAction, we always show the entire image in the thumbnail and `shouldDynamicallyResize` is always set to true. For receipt thumbnails the prop `shouldDynamicallyResize` is always set to `false` so that the thumbnail size is always fixed irrespective of the receipt image size.

In my proposal image alignment is changed only when `shouldDynamicallyResize` is set to false. So image attachment thumbnails in chat will remain unaffected. There is not enough differences in implementation to warrant for a completely different component like `ReceiptThumbnail`.

**Comment by aswin-s** [comment] 2024-01-09 09:38
> @aswin-s @shubham1206agra
> 
> Do I understand correctly that you suggest modifying the logic of `ThumbnailImage`, so it always aligns to the top? Does this component have other usages, where we might prefer different alignment?

@cubuspl42  Yes my proposal is to modify the logic in `ThumbnailImage` component so that the image aligns to top when `shouldDynamicallyResize` is set to false. 

Thumbnail component is used currently for Image attachment previews and Receipt previews.  For image attachments in ReportAction, we always show the entire image in the thumbnail and `shouldDynamicallyResize` is always set to true. For receipt thumbnails the prop `shouldDynamicallyResize` is always set to `false` so that the thumbnail size is always fixed irrespective of the receipt image size.

In my proposal image alignment is changed only when `shouldDynamicallyResize` is set to false. So image attachment thumbnails in chat will remain unaffected. There is not enough differences in implementation to warrant for a completely different component like `ReceiptThumbnail`.

**Comment by cubuspl42** [comment] 2024-01-09 10:11
@shubham1206agra Thank you. Let's use Markdown code syntax for technical and code identifiers only, as it can create confusion otherwise.

@aswin-s You accidentally double-sent your comment

**Comment by cubuspl42** [comment] 2024-01-09 10:49
@dukenv0307 I'm confused as to why you started with a pure CSS solution and switched to a cross-platform one late. I haven't yet analyzed the updated solution.

> ThumbnailImage solution will work for receipts that don't use ThumbnailImage to display (like local images)

This is an important observation. I missed this fact. Indeed, there's some conditional logic in `ReportActionItemImage`.

When is the receipt a local image? How does alignment work now in such a case?

**Comment by aswin-s** [comment] 2024-01-09 10:58
@cubuspl42 I've mentioned about handling other receipt images in my proposal.

>There are a couple of screens like MoneyRequestConfirmationList and ReportActionItemImage etc where Image component is used instead of ThumbnailImage for displaying receipt. Such instances need to be replaced so that all occurrences of receipt image is properly displayed

I also mentioned about it in my response to dukenv0307

>  I've also addressed scenarios like serving local image when receipt upload is in progress in the above video. So it is not exactly same or abstract like your proposal.

When the receipt image is getting uploaded it shows image url from local device or from blob (web platform). It gets handled over here.

https://github.com/Expensify/App/blob/a4bdebe94750e438fe22a7f569e68b54d37df1d0/src/components/ReportActionItem/ReportActionItemImage.js#L79-L82

And for confirmation page over here.

https://github.com/Expensify/App/blob/a4bdebe94750e438fe22a7f569e68b54d37df1d0/src/components/MoneyRequestConfirmationList.js#L607-L616

Both these places use Image component to show the thumbnail at the moment. So if we want the same behaviour as in chat, these should be replaced with `ThumbnailImage` component. That's what I mentioned in my proposal towards last.

**Comment by DanutGavrus** [comment] 2024-01-09 11:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt thumbnail should show the top of the receipt.

### What is the root cause of that problem?
We are using `width: 100%` and `height: 100%` in combination with `resizeMode: cover` which crops the image to the middle, both vertically and horizontally. 

### What changes do you think we should make in order to solve the problem?
Smallest change to make in order to fix this issue is to replace `height: 100%` with `height: *actual height of the thumbnail*` in `ReportActionItemImage` for the `ThumbnailImage` component. The overflow is hidden, and the image will automatically start from the **top** with no other changes. If we want to make this change in other places too, we can generalise this approach. In order to obtain the actual `height` of the image in `ReportActionItemImage` we may use: *RNImage.getSize(\`${thumbnail}?authToken=${NetworkStore.getAuthToken()}\`, (width, height) => {})* where `RNImage` is imported directly from react-native like `import {Image as RNImage} from 'react-native'`.

**Comment by dragnoir** [comment] 2024-01-09 14:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Receipt show the middle part.

### What is the root cause of that problem?
The component `ImageWithSizeCalculation` is using the react native Image to display Images.
https://github.com/Expensify/App/blob/bddf15dc51111d393d2f0f23ff8441b1c490b5d1/src/components/ImageWithSizeCalculation.tsx#L74-L91

1- [React native Image](https://reactnative.dev/docs/image#resizemode), render a container (1 in screenshot) and a child (2 in screenshot) where the image is set as background-image
`style` prop of the Image component from react native, allow only to style the container (1 in screenshot) and not the block where the image is a background (2 in screenshot)

![image](https://github.com/Expensify/App/assets/12425932/0715b584-0a72-498b-955d-868e0a739c14)

2- Why the image is display only the middle part?
The Image native component allow us to pick from prop resizeMode few options, `cover` is the one we are using now + Image native add a style `background-position: center center;` whish make the display show the middle part. (4 in screenshot)

Changing the last style to background-position: top will solve the issue, but we don't have access to edit this style :(

### What changes do you think we should make in order to solve the problem?
Another option allowed on the prop [resizeMode](https://reactnative.dev/docs/image#resizemode) is `contain`

If the block is using background-image and `background-size: contain;` we will be able to adjust the position of this image from the parent container :)

Due that we have access to style the parent container from the `style` prop of the Image component.
We do the following
1- Change [here](https://github.com/Expensify/App/blob/bddf15dc51111d393d2f0f23ff8441b1c490b5d1/src/components/ImageWithSizeCalculation.tsx#L78) to contain
```js
resizeMode={RESIZE_MODES.contain}
```
2- Adjust height of the container to fill the space by the  image.
```js
const [imageHeight, setImageHeight] =  useState(0);

const  imageLoadedSuccessfully  = (event:  OnLoadNativeEvent) => {
  setImageHeight(Math.ceil(event.nativeEvent.height  / (event.nativeEvent.width  /  396)));
};

<Image
  style={[styles.w100, {height:  imageHeight}]}
/>
```
Because now the image background is set the contain, the parent should allow full space for this block.
This is why I we need to calculate the height:

    setImageHeight(Math.ceil(event.nativeEvent.height  / (event.nativeEvent.width  /  396)));
this function take the size of the original picture and calculate the height that fits the container we are using (400  x 200) in our case. (396 = 400 - 2px borders)

More enhancement of the height calculation can be in PR process.

POC:

![image](https://github.com/Expensify/App/assets/12425932/937cb5c7-8138-441b-bd68-754fd9259d82)

### What alternative solutions did you explore? (Optional)

Use native [ImageBackground](https://reactnative.dev/docs/imagebackground) component instead of Image

**Comment by dragnoir** [comment] 2024-01-10 14:43
@cubuspl42 I checked the solution created by aswin and it's causing issues on the UI, pls check video below:

https://github.com/Expensify/App/assets/12425932/7dd6a68e-6678-4ee2-a9d8-56e927baaae2

Also don't you think this is a playaround? We are facking the details for the Child Image component. As example, currently what ever you pass to resizeMode, it will always be the same result.

Please bear with me as I pay close attention to the details :)

**Comment by shubham1206agra** [comment] 2024-01-10 15:03
In that case, @aswin-s take my solution given in branch. :)

**Comment by cubuspl42** [comment] 2024-01-10 15:04
@dragnoir 

I wonder why this effect is not visible on the videos @aswin-s posted. Could it be related to caching? I agree that it doesn't look good. Also, on your video, the receipt image re-layouts _three_ times (I could understand two). We'll have to 

@shubham1206agra 

I assume they have their own, just not shared

**Comment by shubham1206agra** [comment] 2024-01-10 15:19
> @shubham1206agra
> 
> I assume they have their own, just not shared

Looks like @dragnoir have the solution posted https://github.com/dragnoir/App/commit/1352857bef7dad999196e5f7b788e4c7aa6bf9ea.

**Comment by dragnoir** [comment] 2024-01-10 15:20
@cubuspl42 if you console.log the sizeStyles (new style applied to the View container)
`console.log('sizeStyles: ', sizeStyles);`
You will see the below

![image](https://github.com/Expensify/App/assets/12425932/d4a330fc-e1da-4b64-95fb-c1d2508dad4a)

As you can see, the new height will be different from the time the component render to the final state.
I opened on the screenshot 3 values of the sizeStyles.

For theose values, from time component mount to final state:
1- We give to the Image (Child) component a height equal to 0
Result: resizeMode is on cover and will show the center.

2- Height new value but not the correct one, 
Result: <Image> change position

3- Final value of height

My prosal is similar to eswin but not loading issues. I calculate the new values with `onLoadEnd` and I do not ignore the resizeMode prop.

**Comment by cubuspl42** [comment] 2024-01-10 16:58
@dukenv0307

> Just curious why you think it's not a better solution.

Isn't that a question that any author of any of the other proposals could've asked? There will always be some arguments for a given solution, and selecting a specific one is often a matter of taste and personal engineering experience.

> ThumbnailImage has extra code 

If that code _does_ something, not much different from what you're supposed to add to `Image`. Taking into consideration the component depth in our app (and in any modern web app, for what it's worth), one layer more or less is not that big of a difference.

`ThumbnailImage`, as opposed to `Image`, always has known width and height (as it has defaults used in case these values aren't passed explicitly), so I expected it to be a better candidate for implementing the discussed logic. Possibly, contrary to the findings from @dragnoir; I'm not sure yet, as two videos have different behavior.

> @aswin-s FYI your solution's the same as one of my alternate solution

> my solution doesn't have the UI glitch

So is the `ThumbnailImage` / `aspectRatio` **your** solution or **isn't it**? So far, it feels like you're juggling it and changing stances, whatever is more suitable in a given second. Arguing hardly against a solution present in one's own "_What changes do you think we should make in order to solve the problem?_" section is not serious, in my opinion.

Finding a technical issue in another contributor's solution and summaring the findings, so we can all settle on the best solution: GOOD ✅

Undermining the C+ decision because "my solution is **mine** and it's **better**", pinging the internal engineer for that reason: NOT GOOD ❌ (might result in a warning in the future)

**Comment by aswin-s** [comment] 2024-01-11 04:15
@cubuspl42  

> I wonder why this effect is not visible on the videos @aswin-s posted. Could it be related to caching? I agree that it doesn't 
look good. Also, on your video, the receipt image re-layouts _three_ times (I could understand two). We'll have to

I checked above issue in my implementation and yes it definitely happens during first render. I didn't notice this in my proposal because it happens only if you turnoff caching in network panel. This reason is that image needs to be rendered once for the native dimensions to be calculated. On web, by the time the layout measurements are available first render is already finished. Then the aspectRatio gets calculated and image is re-rendered with optimal size. So technically this cannot be avoided. However the image could be hidden from view and the loader could be shown until the aspectRatio calculation is complete by setting opacity or showing the loader. This is just an implementation detail that could be handled in the PR.

**Comment by DanutGavrus** [comment] 2024-01-11 08:47
@aswin-s @cubuspl42 
> This reason is that image needs to be rendered once for the native dimensions to be calculated.

Just a note: maybe you could make use of `getSize` from react-native's Image, which returns the dimensions so we know them in the first render too. If we want to avoid calling `getSize` more than once we may also use `useMemo`. 

Also, from what I've noticed, **if** we end up knowing the dimensions from the start, we may keep our `Image` component as is, and just replace height: `100%` with the actual value.

**Comment by cubuspl42** [comment] 2024-01-11 09:20
@Beamanator Let's wait with the assignment; we have to figure things out here first

**Comment by cubuspl42** [comment] 2024-01-11 09:32
@aswin-s 

> This is just an implementation detail that could be handled in the PR.

Maybe, maybe not. It complicates the solution to the point where other solutions might be more reasonable. I'll have to re-evaluate.

**Comment by aswin-s** [comment] 2024-01-11 09:58
> @aswin-s
> 
> > This is just an implementation detail that could be handled in the PR.
> 
> Maybe, maybe not. It complicates the solution to the point where other solutions might be more reasonable. I'll have to re-evaluate.

@cubuspl42 
Sure no problem. Just want you to consider that all receipt images are of varying sizes and without knowing their native resolution it cannot be resized to parent container keeping the aspect ratio. So any viable proposal will need to get the native resolution first and then set the container / image size accordingly. And in the process the image needs to be rendered once.

@Beamanator The getSize method exported by ReactNative uses Fresco image library under the hood. It has some [known issues loading](https://github.com/facebook/react-native/issues/33498)high resolution images. For native platforms we are using expo-image which uses Glide image library. So not sure if both will return the same image dimensions for high resolution images.

**Comment by cubuspl42** [comment] 2024-01-11 10:06
> So any viable proposal will need to get the native resolution first and then set the container / image size accordingly.

@dukenv0307 suggests otherwise...

> Also my solution doesn't have the UI glitch that @dragnoir mentioned.

Guys, I'm getting tired here. I want to assign fairly, but I'm also assigned to multiple issues and can't get stuck here. I know you tested your solutions. Please just share the branches, and I'll give it a look locally.

**Comment by aswin-s** [comment] 2024-01-11 12:23
@cubuspl42 Here is my branch.
https://github.com/aswin-s/App/tree/fix/issue-34120

Also full disclosure I've [updated my proposal](https://github.com/Expensify/App/issues/34120#issuecomment-1882856388) to adjust the aspect ratio calculation so that it can accomodate multiple receipts stacked together. The core idea of the proposal is still the same so that it doesn't conflict with any other proposals.

<img src="https://github.com/Expensify/App/assets/6880914/248d68b6-1e9b-4229-98a8-8d1e38280c63" width="400"/>


https://github.com/Expensify/App/assets/6880914/7130c33f-7fac-4f01-a241-ddf4e709106c

**Comment by dragnoir** [comment] 2024-01-12 09:01
@cubuspl42 I removed my proposal. after more testing, I don't like the way I did it. I feel it's also a workaround.
I will post another proposal if I find a better solution and the "Help wanted" still actif here.

I apologize if my focus on the details caused any inconvenience. I have the utmost respect for your decision and appreciate the opportunity to discuss this matter.

**Comment by cubuspl42** [comment] 2024-01-12 09:36
@dragnoir I didn't have any complaints about your attitude, it was more towards @dukenv0307. But we're fine now, everyone seems to agree, let's move on 🙂

I'll proceed with the testing  👍

**Comment by cubuspl42** [comment] 2024-01-12 12:25
@aswin-s 

I couldn't reproduce the discussed glitch.

@aswin-s 

But I found another problem:

https://github.com/Expensify/App/assets/2590174/75aa7073-477f-4067-9b79-f1ab2b74084b

Put attention to the spinner. It's not at the center of the preview frame.

@dukenv0307 

You use the following style in your code:

```
!aspectRatio && {opacity: 0}
```

I thought that when you said:

> Also my solution doesn't have the UI glitch

...I understood that your proposal doesn't have this _problem_, not that you solved it / worked it around (the same way @aswin-s mentioned recently).

**Comment by shubham1206agra** [comment] 2024-01-12 12:29
@cubuspl42 Just for sake of completeness, can you test my branch too?

**Comment by cubuspl42** [comment] 2024-01-12 12:42
@shubham1206agra I didn't test it, because as I see it, @dukenv0307 is second in line here:

- His solution doesn't have the non-centered spinner problem or other observable bugs
- He was first to notice and suggest a solution/workaround for the non-available aspect ratio (at the time when I didn't understand that this is a serious problem)

Do I miss something objective?

**Comment by shubham1206agra** [comment] 2024-01-12 13:15
No I just wanted to know if my solution has some problem. I don't care of selection of proposal.

**Comment by aswin-s** [comment] 2024-01-12 13:16
@cubuspl42 The branch that @dukenv0307 shared is not working for wide images, when receipts are stacked. Aspect ratio calculation needs to accommodate images whose height are greater than width and vice versa.

![image](https://github.com/Expensify/App/assets/6880914/9d8c8a82-2e5d-4bb3-8782-84276ab4d2b7)

**Comment by aswin-s** [comment] 2024-01-12 13:27
@cubuspl42 However, I think these small glitches like these can be refined in the PR stage. I'm wondering, at the proposal stage, should we aim for a completely functional branch, or just propose the overall method for tackling the issue? It might be more efficient to focus on the main idea at this stage. Curious to know your thoughts on this.

**Comment by cubuspl42** [comment] 2024-01-15 12:01
> should we aim for a completely functional branch, or just propose the overall method for tackling the issue?

It's a great question. I don't think that there's a good, definitive answer.

If an issue is technical, the major differences among the proposals can lie in details like the ones we discuss. If working around the fact that the spinner is not centered in one solution will require a hack, then choosing a different proposal would very likely be a better option.

When I focus on a main idea when selecting a proposal, there's a 90% chance that I'll get a response from another Contributror saying "the selected proposal has this technical issue X, and my doesn't". And I agree that if that's indeed the case, the other proposal might be a better pick.

It's very easy to sketch an idea that sounds great but _doesn't work_ and fixing its issues requires 3 hacks which later cause 3 regressions. So that's why I sometimes ask about the code which was used to test the idea, as it can contain very ugly make-up above a pretty idea, which is a big regression risk if there are no good ideas for removing these hacks. I don't have to remind you that the compensation system is built around regressions.

It's possible that I focus too much on the details here and overfocus on "fairness". Frankly, most of our proposals here are good enough and could be forged into good PRs with one or two iterations of PR feedback.

**Comment by cubuspl42** [comment] 2024-01-15 12:07
Okey, let's wrap this up.

The previously selected proposal by @aswin-s was proven to have issues. It's likely that they could be solved during PR implementation.

At the same time, the proposal by @dukenv0307 also has its strengths. It's solving the problem on a lower level (in-house `Image` component), which makes the solution more reusable in the future. A risk is that it's also more prone to regressions (as we modify more widely used code), **but** the new logic is mostly conditional. Also, it's been proven that there are known solutions for related minor technical problems.

We had some interesting meta-discussions about proposal selection and how the technical issues can be solved in the PR implementation phase. While it's difficult to reach ultimate conclusions here, I think we're all left with some notes for the future.

I change my decision toward approving the [proposal](https://github.com/Expensify/App/issues/34120#issuecomment-1882437734) by @dukenv0307 

C+ reviewed 🎀 👀 🎀 (again)

**Comment by adelekennedy** [comment] 2024-01-17 18:17
This was a thorny one - thank you for pushing this forward @cubuspl42

**Comment by Beamanator** [comment] 2024-01-23 09:12
Yikes sorry for the delay! Will review today

**Comment by Beamanator** [comment] 2024-01-23 09:29
Amazing discussions here, thanks for leading us through it @cubuspl42 , and thanks to everyone for getting us to the best path forward 🙏

**Comment by adelekennedy** [comment] 2024-01-29 20:11
@dukenv0307 is working on the PR

**Comment by dragnoir** [comment] 2024-01-29 21:10
@adelekennedy this PR is mentioned here https://github.com/Expensify/App/pull/35041

**Comment by cubuspl42** [comment] 2024-02-06 09:31
We should hold on https://github.com/Expensify/App/issues/12603. They're actively working on the `Image` component, and some stuff just got (likely, temporarily) reverted. It interferes with our PR work and it's easiest to wait till things settle.

**Comment by cubuspl42** [comment] 2024-03-01 09:44
We're holding on issue https://github.com/Expensify/App/issues/12603 / PR https://github.com/Expensify/App/pull/36560. We _could_ try providing without that hold, but I believe that (considering the relatively small impact), we're find to hold.

**Comment by cubuspl42** [comment] 2024-04-02 15:10
This is off-hold, but we're discussing some issues found during testing

**Comment by Beamanator** [comment] 2024-04-16 14:38
I just submitted an internal PR that should start cropping thumbnails at the top of the images - a.k.a. centered horizontally, and floating to the top of the image. I'll update here as it gets reviewed / merged / deploye

**Comment by Beamanator** [comment] 2024-04-17 09:31
Ok @cubuspl42 @dukenv0307 the backend PR is on staging, can y'all test with the App PR please? 🙏

**Comment by Beamanator** [comment] 2024-04-17 09:58
Thanks @dukenv0307 ! So looks like we're good to move forward with [your PR](https://github.com/Expensify/App/pull/35041), yeah? Can you please pull main & retest? :pray

**Comment by Beamanator** [comment] 2024-04-17 11:21
Nice, thanks @dukenv0307 - I requested @cubuspl42 also retest, then we can hopefully get this merged 🙏

**Comment by Beamanator** [comment] 2024-04-23 07:21
@dukenv0307 @cubuspl42 it looks like QA tested and didn't find that the solution worked - https://github.com/Expensify/App/pull/35041#issuecomment-2070283356

Can y'all please take a look?

**Comment by Beamanator** [comment] 2024-04-23 10:19
@dukenv0307 thanks for the quick PR! I don't believe your PR is fixing a deploy blocker though, right? Just fixing 1 case where we weren't showing the top of the receipt? If so, no CP needed, this can go through the normal process 🙏

**Comment by Beamanator** [comment] 2024-04-23 11:24
@dukenv0307  Cool thanks for confirming, let's go through the normal process 👍

**Comment by mallenexpensify** [comment] 2024-04-24 00:46
@Santhosh-Sellavel reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks
@dukenv0307 , can you please update @Santhosh-Sellavel on where we're at here?

**Comment by Beamanator** [comment] 2024-04-24 08:42
@dukenv0307 it looks like we've been showing the top of receipts for distance request receipts as well, but we don't want that behavior - see https://github.com/Expensify/App/issues/40791

**Comment by garrettmknight** [comment] 2024-04-24 09:26
@adelekennedy dropping to $250 for a regression.

**Comment by Santhosh-Sellavel** [comment] 2024-05-02 21:02
@mallenexpensify/@ad Can you assign me here please, seems I got unassigned accidentally

> @Santhosh-Sellavel reassigning, please take over as C+. If you don't have bandwidth, unassign yourself.

**Comment by mallenexpensify** [comment] 2024-05-03 01:54
Done, added @Santhosh-Sellavel , sorry about that

**Comment by Beamanator** [comment] 2024-05-14 18:53
Hmm @dukenv0307 your PR went to prod a week or so ago, are we waiting on anything here?

**Comment by mallenexpensify** [comment] 2024-05-19 21:28
Looks like this hit production on 4/23, so gonna pay
https://github.com/Expensify/App/pull/35041#issuecomment-2073662737

Contributor: @dukenv0307  paid $250 via Upwork
Contributor+: @Santhosh-Sellavel owed $250 via NewDot

**Closed by mallenexpensify** 2024-05-19 21:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
