### ISSUE TITLE
other users can access and replay to Concierge message "Hi there! This is your first time chatting ..." using link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24520] opened 2023-08-13 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- using User A, initiate a new chat with User B.
2-on User B  click reply on the concierge message
3- copy the link
4- past the link in user A
5 - send a message
## Expected Result: 
after pasting the link "Hmm ... it's not here" page should be displayed
## Actual Result: 
User A is able to send replays to User B Concierge message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[concierge-bug (1).webm](https://github.com/Expensify/App/assets/43996225/665bd604-dfc4-4485-a255-3ad4e3eb4a71)

https://github.com/Expensify/App/assets/43996225/33468d1a-016e-47d8-a764-a560e94b761e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691277889680489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yh-0218** [comment] 2023-08-14 17:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
other users can access and replay to Concierge message "Hi there! This is your first time chatting ..." using link
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/9348d53a098216ce20e66ccd852c3f96a35ba687/src/pages/home/ReportScreen.js#L297
Because we are missing condition for thread with Concierge.
### What changes do you think we should make in order to solve the problem?
1. check if thread chat with Concierge
`action.participantAccountIDs` contains Concierge ID or `action. participants` contains concierge@expensify.com.
2. In this case, check `actorAccountID` of `ReportActionsUtils.getParentReportAction(report)` for thread chat with .
if <1> is true and <2> is null, then we have to set `shouldShow` of `FullPageNotFoundView` as `true`
### What alternative solutions did you explore? (Optional)

**Comment by NicMendonca** [comment] 2023-08-14 23:47
> after pasting the link "Hmm ... it's not here" page should be displayed

Why? I don't think I understand this. Isn't it a link to the chat with the user?

**Comment by hichamcc** [comment] 2023-08-15 00:09
> > after pasting the link "Hmm ... it's not here" page should be displayed
> 
> Why? I don't think I understand this. Isn't it a link to the chat with the user?

Link to the reply of the concierge message.

**Comment by NicMendonca** [comment] 2023-08-17 18:58
I don't think this is an actually use case a customer will take. closing this for now

**Closed by NicMendonca** 2023-08-17 18:58 UTC
Labels: Daily, Bug
