### ISSUE TITLE
Android - Attachment - Android - Image is shaking when zooming with the pinch method

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49755] opened 2024-09-25 22:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** https://expensify.testrail.io/index.php?/tests/view/5010394&group_by=cases:section_id&group_id=292107&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with any account
3. Open any 1:1 chat
4. Tap on + - Add attachment
5. Take or upload any image to the chat
6. Open the image
7. Slowly zoom in and out with the pinch method

## Expected Result:
Zooming should be smooth.

## Actual Result:
Image is shaking when zooming with the pinch method.
## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0d36cf5d-3d24-4fc6-8460-843e70886c51

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-25 22:53
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by CortneyOfstad** [comment] 2024-09-27 19:19
Going to see if Stevie will be willing to help me as she has an Android. I believe she is out for the weekend, so I will get in touch with her ASAP on Monday morning!

**Comment by jacobkim9881** [comment] 2024-09-30 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Image view, zooming gesture moves focal points of the screen.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/components/MultiGestureCanvas/usePinchGesture.ts#L141-L146
On current version, this code causes unmatched focal points after pinching gesture. When zooming a image, a focal point moves too by changing image's scale within limits. For this code, it have solved "overzoomed" or "underzoomed" screen issue by re-calculating how much to move screen. 

> // If the zoom scale is within the zoom range, we perform the regular pinch translation
> // Otherwise it means that we are "overzoomed" or "underzoomed", so we need to bounce back

 Because the screen always have overzoomed or underzoomed, the code above calculates how much bounce back to match the focal point. On pinching end the value is added for matching  the focal point. Without the calculation on current version, we can see zooming gesture doesn't make unmatched focal point.

### What changes do you think we should make in order to solve the problem?
We can let the gesture act better by removing the code.     

https://github.com/user-attachments/assets/2b7657b0-e7cd-4748-988a-69115fa5d51a

Out of limits there is the other code for bouncing back: 

https://github.com/Expensify/App/blob/86360745431edb355c91e5594c741a54e5f88581/src/components/MultiGestureCanvas/usePinchGesture.ts#L146-L151

If a zooming range is out of minimum or maximum limit(when the user zooming out/in over the maximum/minimum size like pinching each corner of the screen or zooming over and over), it is recalculated to match it's focal point. But in this case too screen is shaking too on the current app.

https://github.com/user-attachments/assets/3802af70-479f-45b1-86b2-93aa634e0e93


https://github.com/user-attachments/assets/af842153-1cbd-41fa-9015-69b78a5b4a62



We can also remove the other code for solving shaking screen issue.

https://github.com/user-attachments/assets/7c3f988d-c063-4426-b49f-8547d9863457

https://github.com/user-attachments/assets/41649f8e-fc6c-4b77-95be-37ca1ed720a0



### What alternative solutions did you explore? (Optional)
N/A

**Comment by CortneyOfstad** [comment] 2024-10-01 19:52
Sorry, was OoO yesterday! Working with @slafortune to have her test on her Android 🙏

**Comment by CortneyOfstad** [comment] 2024-10-01 19:59
We were not able to recreate this. When testing on Stevie's phone we were able to pinch the image smoothly without any lags, shakes, or hesitation from the image. 

With a manual action like zooming via the pinch-method, there is too many variables to classify this as a `bug`. And if this were to be consistently recreated, this would be a low priority bug, so closing!

**Closed by CortneyOfstad** 2024-10-01 19:59 UTC
Labels: Daily, Bug
