### ISSUE TITLE
Expense - Unable to save report title for workspace expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35694] opened 2024-02-02 18:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any workspace
3. Create a manual request
4. Go to expense report
5. Click Title row
6. Change to a new title and save it

## Expected Result:
The new report title is saved

## Actual Result:
The new report title is not saved. This issue is only reproducible for workspace expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/09d43e83-eaa0-4764-bf10-43bf545e87b1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-02 18:33
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by deetergp** [comment] 2024-02-02 22:44
I was able to reproduce this on web. After digging through the code, it looks like it was most recently touched in this PR https://github.com/Expensify/App/pull/34483.

**Comment by allroundexperts** [comment] 2024-02-02 22:45
Checking.

**Comment by allroundexperts** [comment] 2024-02-02 23:06
@thienlnam The backend is not letting the report being renamed. It throws the following:

```
You can't rename the report of a free plan
```

We can do one of the following:
1. Allow rename from the backend for the free plan users.
2. Disable ONLY the title field for free plan users.
3. Disable ALL report fields for the free plan users.

Let me know what we want to do here.

**Comment by thienlnam** [comment] 2024-02-02 23:18
You shouldn't be able to set report fields for free workspaces - this should be a control / collect policy only. How are you setting report fields for free plan users?

**Comment by thienlnam** [comment] 2024-02-02 23:19
Will take this over since I have context - we don't need to block on this since it's behind a beta and you shouldn't be able to set report fields on a free plan

**Comment by allroundexperts** [comment] 2024-02-02 23:19
For free workspaces, we're always sending a title report field attached to the policy. That is why people from free workspaces are able to see the option to edit the title.

**Comment by thienlnam** [comment] 2024-02-02 23:19
By default, there might be the text_title for free workspaces. If that's the case, I will update the BE so that it does not return for free workspaces

**Comment by allroundexperts** [comment] 2024-02-02 23:20
Yep, that's exactly what is the issue.

**Comment by thienlnam** [comment] 2024-02-02 23:20
Ah I see, yeah I'll handle this via the BE then

**Comment by thienlnam** [comment] 2024-02-05 18:04
Working on it this week, moving to a weekly since this is still behind beta

**Comment by thienlnam** [comment] 2024-02-14 01:58
This is handled by https://github.com/Expensify/App/pull/36044

**Closed by thienlnam** 2024-02-14 01:58 UTC
Labels: Engineering, Weekly, Overdue
