### ISSUE TITLE
[Awaiting Payment 17th April] [Wave Collect][QBO] Implement Accounting page

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/App#37706] opened 2024-03-05 00:56 UTC
Implement a new page called "Accounting page" for the QuickBooks Online (QBO) connection project.

QBO is a well-known accounting software that Expensify supports integration with. Once the user establishes a connection to QBO, Expensify exports expense reports, also known as money requests, to QBO. This enables expenses, referred to as transactions in QBO terminology, to appear in the accounting software.

Your task is to implement the Accounting page where the user can set up and configure the accounting integration with QBO.

This page has two states: before connection and after connection.

- Before the connection, the page presents the option to connect to the QBO.
- After the connection is established, the page shows the main menu items. These items represent different configurations that the user can adjust concerning the QBO connection. When a menu item is clicked, the user is taken to another page where they can modify the configuration. This task does not include creating these individual configuration pages.

Refer to the mockups in the Production Specifications section below for visual information.

## Product Specifications

<details>
<summary>1</summary>

![Screenshot 2024-03-04 at 4 48 25 PM](https://github.com/Expensify/App/assets/98560306/fb135f81-73f2-4f08-871e-401bcb466841)

</details>

<details>
<summary>2</summary>

![Screenshot 2024-03-04 at 4 48 52 PM](https://github.com/Expensify/App/assets/98560306/31542c54-3b39-494f-93de-0cb9b51e56af)

</details>

<details>
<summary>3</summary>

![Screenshot 2024-03-04 at 4 49 24 PM](https://github.com/Expensify/App/assets/98560306/15f8ba67-ffde-4001-87e3-55d728fb5bab)

</details>

<details>
<summary>4</summary>

![Screenshot 2024-03-04 at 4 49 53 PM](https://github.com/Expensify/App/assets/98560306/f17cf948-cb09-47e0-9479-81b5c41eccd3)

</details>

<details>
<summary>5</summary>

![Screenshot 2024-03-04 at 4 50 25 PM](https://github.com/Expensify/App/assets/98560306/1f49862a-6619-4934-851b-b53b5fedad2d)

</details>

## Design documentation excerpts

<details>
<summary>code skeleton</summary>

![Screenshot 2024-02-23 at 8 33 03 AM](https://github.com/Expensify/App/assets/98560306/63d9c72d-dcb7-4ec5-b74a-248cc1846e69)

</details>

<details>
<summary>supporting text and error handling</summary>

![Screenshot 2024-02-23 at 8 35 00 AM](https://github.com/Expensify/App/assets/98560306/78318e50-63cb-4f6d-90d6-e463a99a0f46)

</details>

<details>
<summary>menu items</summary>

![Screenshot 2024-02-23 at 8 36 08 AM](https://github.com/Expensify/App/assets/98560306/599cdf98-a9b3-4e1e-b47b-ebee13326a6d)

</details>

<details>
<summary>connection setup button</summary>

![Screenshot 2024-02-23 at 8 37 14 AM](https://github.com/Expensify/App/assets/98560306/07b3e873-596e-4ba4-8f4a-699523ca9eda)

</details>

## Assets
[Integration.Logo.Icons.zip](https://github.com/Expensify/App/files/14593191/Integration.Logo.Icons.zip)

## Notes
The tasks in the QBO project is done in parallel, including the work in the backend code. Thera are some functions or navigations that are incomplete at the time of this writing. This section lists out these items.

- QBO setup (i.e. synchronization) logic.
When a connection with QBO isn't established, the Accounting page displays a user interface with a button to set up the connection. If the logic to establish the connection isn't available yet, leave the button's callback blank.

- A function to check if a connection has been established.
The Account page displays different UIs based on the existence of a connection. This can be verified by examining the policy object, which can be subscribed to using `withPolicy` or `withOnyx` Higher Order Components. However, if the logic to establish a connection with QBO is unavailable, the policy object will lack connection information. In such a scenario, declare a temporary boolean variable within the component to toggle between the two states of being connected and not connected.

- Information about the synchronization state
During QBO connection and synchronization, the progress should be displayed on the Accounting page (refer to the above excerpts for more details). However, this progress information comes from data stored in Onyx. Since the actual connection might not be ready yet, you need to create mock data for this. This also applies to the error state of synchronization, if any. Please contact @hayata-suenaga for more details.

- Navigation when the menu item is clicked
Certain configuration pages linked from the Accounting page might not be available. If this happens, leave the callback blank. This allows for navigation logic to be added later. If the PR is completed before individual pages are implemented, we may merge the PR with these blank callbacks.

## Please ask questions
This task comes with a lengthy list of specifications. Please direct any questions you may have to @hayata-suenaga. You most likely will have some. 🙇

**Comment by hayata-suenaga** [comment] 2024-03-08 19:48
@abekkala this is an engineering issue. A CallStack engineer is going to work on it next week. The specifications are written in the design doc, and there are screenshots of the design doc in the OP.

You're auto-assigned to this issue because of the `NewFeature` flag. You will handle the payments to a C+ that is going to review the PRs once they're ready.

However, this might take some time. Please feel free to un-assign yourself until payments are needed. 🙇

**Comment by hayata-suenaga** [comment] 2024-03-11 17:38
@teneeto, please review the requirements of this GH ticket and don't hesitate to ask questions. The requirements are somewhat complex, so any clarifying questions are welcome 😄 

I look forward to working with you 🚀

**Comment by hayata-suenaga** [comment] 2024-03-12 14:46
@teneeto, thank you for reading over the requirements and for your questions 😄 

I answer your questions in Slack here in this comment.

> 1. I see we have to toggle on the Accounting Feature on the integration section of the More Features. Where do we find the initial QBO connection setup Page - what workspace has the more features? (I couldn't find it).

In short, you don't need to concern yourself with this aspect. There's no need to implement the 'More Features' page or the logic to toggle the accounting feature. Assume that the information on whether the accounting feature is activated for the workspace is available on the 'Accounting' page, which you will be implementing. For now, implement the routing logic regardless of whether the accounting feature is on or off. I'll continue to provide updates on this.

> 2. For Confirmation, `Xero` is not within the scope of this implementation, right?

That's correct 👍 Xero is not in the scope of this GH ticket.

> 3. We Will need all icon assets.

I'll provide the icon assets shortly.

> 4. We need any API calls ? - how do we receive/discuss endpoints? on slack?

There's no need to call the API for this GitHub ticket's pull request, as it will initially be under a dark launch. Although we'll deploy the code, it won't be in use immediately. Please refer to the "Note" section in the initial post, the relevant parts of which are copied below for convenience.

> When a connection with QBO isn't established, the Accounting page displays a user interface with a button to set up the connection. If the logic to establish the connection isn't available yet, leave the button's callback blank.

> 5. Is it possible we have a design doc. - screenshots are too small here.

The doc is now shared with your CallStack email address 😄

**Comment by teneeto** [comment] 2024-03-12 16:13
Thank you @hayata-suenaga

**Comment by abekkala** [comment] 2024-03-12 17:53
Ah I see I'm only applied via new feature to process payments. 
Based on @hayata-suenaga's comment above - I'm going to unassign for now

**Comment by hayata-suenaga** [comment] 2024-03-13 14:26
@teneeto if you could share your daily progress in this GH ticket, we'd appreciate it 🙇 😄

**Comment by teneeto** [comment] 2024-03-14 10:10
Hi @hayata-suenaga I have created the navigation and accounting page for QBO integration with a [Draft_PR](https://github.com/Expensify/App/pull/38283)

**Comment by teneeto** [comment] 2024-03-15 10:31
@hayata-suenaga I have added all possible initial components, next is to set up a connection for QBO and authorize the sharing of data between Expensify and Intuit. 

I have also opened PR for soft review - any early tips on how to set up a connection for QBO are welcomed. 😉

**Comment by hayata-suenaga** [comment] 2024-03-15 15:16
great! thank you for the update! I'll take a look at your PR today

**Comment by hayata-suenaga** [comment] 2024-03-24 20:34
I've been sick at the end of last week. I'll review this this Monday 🙇

**Comment by hayata-suenaga** [comment] 2024-03-27 05:24
building [an ad hoc build](https://github.com/Expensify/App/actions/runs/8447079956) to prepare for the design team review

**Comment by trjExpensify** [comment] 2024-04-15 13:21
@dylanexpensify assigning yah as #39954 was closed in favour of this and there's no BZ.

**Comment by dylanexpensify** [comment] 2024-04-15 13:30
Sounds good @trjExpensify!!

**Comment by trjExpensify** [comment] 2024-04-22 12:26
Can you pay this one out and close it? Thanks!

**Comment by dylanexpensify** [comment] 2024-04-29 10:09
Yes! Sorry, was OOO! Finishing today 👍

**Comment by dylanexpensify** [comment] 2024-04-29 10:14
Payment summary:
- Contributor: @teneeto $1,000
- Contributor+: @s77rt $1,000

Please request or [apply here](https://www.upwork.com/jobs/~01e967a966d8441af2)!

**Comment by dylanexpensify** [comment] 2024-04-30 13:42
@s77rt updated!

**Comment by s77rt** [comment] 2024-04-30 13:46
@dylanexpensify Applied!

**Comment by inwake** [comment] 2024-04-30 15:24
Hi @hayata-suenaga and the Expensify team,

I've been closely following the [Wave Collect][QBO] Implement Accounting page project and have been diligently preparing a proposal for the task. However, I've noticed that the issue is currently in the "Awaiting Payment" status, and I'm a bit confused about the workflow and whether new proposals are still being considered.

Given the current status of the project, I wanted to reach out and clarify if it would still be beneficial for me to submit my proposal. I've invested a significant amount of time in understanding the requirements and drafting a comprehensive solution, and I'm eager to contribute to the project if there's still an opportunity to do so.

Could you please provide some guidance on whether the project is still open to new proposals, or if it has indeed moved past the proposal stage? I want to ensure that my efforts align with the current needs of the project and that any contribution I make will be timely and relevant.

Thank you for your time and assistance. I look forward to your response and the possibility of contributing to this and future projects.

Best regards,
- Vitaliy

**Comment by dylanexpensify** [comment] 2024-04-30 18:07
Hi @inwake! Thanks for reaching out! We've had this one done, so no new proposals are needed. We just need to finish it by paying the contracts out. Thanks for your interest here, and please keep looking at our available bugs!

**Comment by s77rt** [comment] 2024-04-30 21:22
@dylanexpensify Accepted! Thanks!

**Comment by dylanexpensify** [comment] 2024-05-01 07:41
Wahoo!

**Comment by dylanexpensify** [comment] 2024-05-01 14:53
Done!

**Closed by dylanexpensify** 2024-05-01 14:53 UTC
Labels: Daily, NewFeature, Awaiting Payment
