### ISSUE TITLE
[HOLD for payment 2023-08-16] [$2000] Assign task - Unable to select a user for Share somewhere

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20898] opened 2023-06-16 11:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login with any account (without a existing conversation)
2. Click FAB icon >> Assign task
3. Fill in Title and Description >> Next
4. Press Assignee
5. Select the current user
6. Press Confirm task
7. Press Share somewhere >> Select any contact

## Expected Result:
Able to select any user

## Actual Result:
Unable to select a user for Share somewhere

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0644fe56-78e2-471d-8068-bced5f30fb56

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8579508a8256236</li>
        <li>Upwork Job ID: 1670858090487717888</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 25773105</li>
<li>Thanos30 | Contributor | 25866908</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-06-19 18:18
looks good!

**Comment by Thanos30** [comment] 2023-06-19 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After creating a new task and setting ourselves (the current user) as the assignee, it is not possible to set as share destination a chat report that doesn't exist.

### What is the root cause of that problem?

The root cause of this issue is on the `TaskShareDestinationSelectorModal.js` file:

```
const selectReport = (option) => {
        if (!option) {
            return;
        }

        if (option.reportID) {
            // Clear out the state value, set the assignee and navigate back to the NewTaskPage
            setSearchValue('');
            TaskUtils.setShareDestinationValue(option.reportID);
            Navigation.goBack();
        }
    };

```

When we select a share location for a chat that doesn't have a report open, the onSelectReport doesn't get into any of the 2 `if` we have, and therefore nothing happens.

### What changes do you think we should make in order to solve the problem?
We should add code there that will handle the scenario where this will be shared on a new chat report:

```
const selectReport = (option) => {
        if (!option) {
            return;
        }

        if (option.reportID) {
            // Clear out the state value, set the assignee and navigate back to the NewTaskPage
            setSearchValue('');
            TaskUtils.setShareDestinationValue(option.reportID);
            Navigation.goBack();
        } else {
            const newChat = ReportUtils.buildOptimisticChatReport([option.login]);
            TaskUtils.setShareDestinationValue(newChat.reportID);
            Report.openReport(newChat.reportID, [option.login], newChat);
            Navigation.goBack();
        }
    };

```
This solves the issue.

**Comment by slafortune** [comment] 2023-06-21 21:10
@0xmiroslav thoughts?

**Comment by slafortune** [comment] 2023-06-26 23:28
Getting verification on this -https://expensify.slack.com/archives/C01SKUP7QR0/p1687822015988679

**Comment by thienlnam** [comment] 2023-06-26 23:57
This seems to work as intended - 

When choosing where to share the task, it has to be a location that exists. 

However, you can assign anyone to a task in which case it will create a DM between the task creator and the user

**Comment by Thanos30** [comment] 2023-06-27 00:00
@thienlnam In that case, shouldn't we hide the options that don't have an existing chat, instead of showing them and not doing anything when the user clicks on them?

**Comment by thienlnam** [comment] 2023-06-27 00:13
Hmm, I thought that was already the case but I guess not, so I'll reopen this - thanks for the note! I believe the expected behavior here is to hide the options

**Comment by Thanos30** [comment] 2023-06-27 00:14
I can update my proposal to fix that, I initially thought that we should handle the creation of a new chat since we were showing the chats that didn't exist.

**Comment by thienlnam** [comment] 2023-06-27 00:19
Hold on, let me confirm with the team and then get back to you

**Comment by Thanos30** [comment] 2023-06-27 00:20
Got it, thank you!

**Comment by thienlnam** [comment] 2023-06-28 23:13
Let's hide the options you don't have access to right now @Thanos30. We're updating the flow for users you haven't chatted with and can update that flow later

**Comment by Thanos30** [comment] 2023-06-28 23:24
Perfect, @thienlnam , thanks for getting back at me. Should I update my PR now?

**Comment by thienlnam** [comment] 2023-06-28 23:50
Yes please!

**Comment by Thanos30** [comment] 2023-06-29 01:01
@thienlnam Proposal is updated, Thank you!

**Comment by thienlnam** [comment] 2023-06-29 20:58
@0xmiroslav Can you please review the proposal here? https://github.com/Expensify/App/issues/20898#issuecomment-1597736984

**Comment by Thanos30** [comment] 2023-06-29 22:16
> > includePersonalDetails: false, ---> Make this false, not to get new chats.
> 
> 
> 
> This is wrong. It excludes all personal details which are not in recent list but already in contacts list.

This is what was filling the results with the extra data. My assumption was that if recent list max results are set to 0 (unlimited), it will return all the available chats we have on LHN, which is the desired result. Correct me if I am wrong please, thank you for the feedback

**Comment by Thanos30** [comment] 2023-06-30 00:27
@0xmiroslav Thank you once again for the example given. I found out what the issue here is.

On `OptionsListUtils.js`, lines 766-774 :

```
if (
        searchValue &&
        (noOptions || noOptionsMatchExactly) &&
        !isCurrentUser({login: searchValue}) &&
        _.every(selectedOptions, (option) => option.login !== searchValue) &&
        ((Str.isValidEmail(searchValue) && !Str.isDomainEmail(searchValue)) || parsedPhoneNumber.possible) &&
        !_.find(loginOptionsToExclude, (loginOptionToExclude) => loginOptionToExclude.login === addSMSDomainIfPhoneNumber(searchValue).toLowerCase()) &&
        (searchValue !== CONST.EMAIL.CHRONOS || Permissions.canUseChronos(betas))
    ) {

```

The above `if` statement checks (among other checks) if we have searched for a "completed" email address, and our options list is empty OR if we don't have a perfect match with an account on our list. If this `if` statement is `true`, it will create a new option based on the new "completed" email searched by the user. We can disable that if statementby sending another prop to the `getOptions` function.

The reason you are seeing this duplicate, is because you are searching for  a non-verified account. I saw the email you searched and I figured that would be the issue. If you try to log the options returned by the function, you will see that this email, and all unverified emails, have a `login: undefined` instead of the actual email.

This is why the `noOptionsMatchExactly` returns true, because it compares the `searchKeyword` with the `option.login`.

Thank you again for pinpointing this issue. We could fix this too by sending an extra prop to the function as I mentioned above, as I believe we won't be allowing unverified emails in live app.

Also, if you still want to include the `personalDetails` , we could simply filter all the returned options to keep only the ones that have a `reportID !== undefined`, but as I mentioned, this will be extra calculations for no reason, getting all the recentReports does our job.

**Comment by Thanos30** [comment] 2023-07-03 12:12
@0xmiroslav Hmm, the login property for that option is `undefined` for some reason though. I will investigate it further, but the solution would still be the same, we will send a prop to that function so that it won't create a new chat if we type in a valid email address that we don't have previously chatted with. This will solve the problem

**Comment by slafortune** [comment] 2023-07-05 20:36
@0xmiroslav thoughts?

**Comment by Thanos30** [comment] 2023-07-05 20:51
@0xmiroslav Did you check my comment above?

**Comment by Thanos30** [comment] 2023-07-06 01:55
@0xmiroslav After further investigation and digging, I found out that the duplicate issue you mentioned before is discussed on this thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1687390694872859

In any case, this is a different issue that appears in various places, and will be handled elsewhere. The solution here remains unchanged, I updated my proposal, please take a look when you are available. Thanks!

**Comment by thienlnam** [comment] 2023-07-10 17:16
Doubled the bounty - let's get some proposals!

**Comment by Thanos30** [comment] 2023-07-10 17:18
@thienlnam @0xmiroslav  Did you check my comment above? I believe I got this issue down to the core of it, I would appreciate any feedback, Thank you!

**Comment by thienlnam** [comment] 2023-07-10 17:20
cc @0xmiroslav Could you review again when you get the chance?

**Comment by Thanos30** [comment] 2023-07-10 17:29
@0xmiroslav Yes, I do understand that. Did you check the Slack thread I sent above? The duplicate chats issue is discussed there. It's a different issue that has to do with the `login` property. Team is working on using the accountID for these and not the login. 

Despite these though, the fix will remain the same, as we do not want to include "creation of new chat" in the share destination select.

**Comment by Thanos30** [comment] 2023-07-10 22:31
@0xmiroslav @thienlnam Pardon my questions, but my proposal makes it work the way you described. 

@0xmiroslav For the duplicate options, as I explained above, the team is well aware of this, as it happens in all the searching components, and they discussed it in this thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1687390694872859

But this only happens when we allow the searching to create a new chat if we put a valid email address, and in our case here, we don't want to allow that to happen. Therefore, we do solve the duplicate options here too.

I don't understand what the problem is, my proposal seem to work great.

**Comment by Thanos30** [comment] 2023-07-13 20:56
@0xmiroslav Could you please give me an example of a failure case? I have been testing thisd for a while now and didn't face any issues. Sorry for the disturbance, and thank you once again for the feedback 🙏

**Comment by Thanos30** [comment] 2023-07-14 17:26
@0xmiroslav Thank you. In this recording the `if` statement I mentioned on my proposal is `true`. Did you add all the code changes I mentioned to make this if be `false` when searching for the Sharing Destination?  Let me quote the changes for you:

> On OptionsListUtils.js we should change the getShareDestinationOptions function as follows:

```
function getShareDestinationOptions(reports, personalDetails, betas = [], searchValue = '', selectedOptions = [], excludeLogins = [], includeOwnedWorkspaceChats = true, disallowNewChats = true) {
    return getOptions(reports, personalDetails, {
        betas,
        searchInputValue: searchValue.trim(),
        selectedOptions,
        maxRecentReportsToShow: 0,  ---> Set this from 5 to 0 (unlimited), in order to get all the Reports active to the user.
        includeRecentReports: true,
        includeMultipleParticipantReports: true,
        includePersonalDetails: false, ---> Make this false, not to get new chats.
        excludeLogins,
        includeOwnedWorkspaceChats,
        disallowNewChats,  ---> New prop to disable 
    });
}
```

> Furthermore, on OptionsListUtils.js, lines 766-774, there is an if statement that will create a new chat if we type a valid email address and it doesn't exist. We should avoid that with an extra prop:


```
if (
        searchValue &&
        (noOptions || noOptionsMatchExactly) &&
        !isCurrentUser({login: searchValue}) &&
        _.every(selectedOptions, (option) => option.login !== searchValue) &&
        ((Str.isValidEmail(searchValue) && !Str.isDomainEmail(searchValue)) || parsedPhoneNumber.possible) &&
        !_.find(loginOptionsToExclude, (loginOptionToExclude) => loginOptionToExclude.login === addSMSDomainIfPhoneNumber(searchValue).toLowerCase()) &&
        (searchValue !== CONST.EMAIL.CHRONOS || Permissions.canUseChronos(betas)) &&
        !disallowNewChats <----- The new prop
    ) {
```

> And of course, getOptions will become:

```
function getOptions(
    reports,
    personalDetails,
    {
        reportActions = {},
        betas = [],
        selectedOptions = [],
        maxRecentReportsToShow = 0,
        excludeLogins = [],
        includeMultipleParticipantReports = false,
        includePersonalDetails = false,
        includeRecentReports = false,
        // When sortByReportTypeInSearch flag is true, recentReports will include the personalDetails options as well.
        sortByReportTypeInSearch = false,
        searchInputValue = '',
        showChatPreviewLine = false,
        sortPersonalDetailsByAlphaAsc = true,
        forcePolicyNamePreview = false,
        includeOwnedWorkspaceChats = false,
        includeThreads = false,
        includeTasks = false,
        includeMoneyRequests = false,
        disallowNewChats = false,
    },
)
```

**Comment by Thanos30** [comment] 2023-07-14 17:31
@0xmiroslav I am positive, yes, I did quite a lot of testing on that. Maybe they are reports that are not for chat, but for Money Request etc.? Could also provide an example of that please? I am sorry for the inconveniences, I did test a lot and never had any issues. I appreciate your help 🙏

**Comment by getusha** [comment] 2023-07-14 17:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to select available user to share somewhere
### What is the root cause of that problem?
the root cause of the problem is we're including other chats that are not available on our contact list
which is inside `personalDetails` but we only want to show our contact list.

https://github.com/Expensify/App/blob/d4cf9a8c246672e3dd3108c09e1a3fbc4c990622/src/pages/tasks/TaskShareDestinationSelectorModal.js#L76

### What changes do you think we should make in order to solve the problem?


we should remove `filteredPersonalDetails` with it's usages so we will show only `filteredRecentReports`
in order to make other users visible we have to add another prop inside `getShareDestinationOptions` called `maxLength` which will determine the length of the list that will be returned from contacts. it will have a default value of 5. then we will pass 0 to make sure it returns all contact items.

https://github.com/Expensify/App/blob/d4cf9a8c246672e3dd3108c09e1a3fbc4c990622/src/pages/tasks/TaskShareDestinationSelectorModal.js#L76

Result:

<img width="1680" alt="Screenshot 2023-07-14 at 8 42 15 PM" src="https://github.com/Expensify/App/assets/75031127/2aeb4cb7-bb3f-4ff9-a15e-3d4de18beeb7">

### What alternative solutions did you explore? (Optional)

**Comment by StevenKKC** [comment] 2023-07-14 19:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to select available user to share somewhere.

### What is the root cause of that problem?
The root cause is that we does not filter out unavailable report and includes other chat (for example, the chat with new account).

### What changes do you think we should make in order to solve the problem?
First, we should filter out unavailable chat report.
Add checking if is an archived room or not to [this line](https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L54) as below, because archived room does not allow add comment and `isAllowedToComment` does not check archived room.
```js
if (!ReportUtils.isAllowedToComment(props.reports[reportKey]) || ReportUtils.isArchivedRoom(props.reports[reportKey])) {
```

Since we only show all reports where assign task is applicable, we can remove below code blocks.
https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L48-L49
https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L74
https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L76
https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L104-L119
And change [this line](https://github.com/Expensify/App/blob/2c365997adad247d5bdf1b60841bb9e509894c43/src/pages/tasks/TaskShareDestinationSelectorModal.js#L62) as below.
```js
const {recentReports} = OptionsListUtils.getShareDestinationOptions(
```

Also, we should pass correct parameter to `getOptions`.
```js
function getShareDestinationOptions(reports, personalDetails, betas = [], searchValue = '', selectedOptions = [], excludeLogins = [], includeOwnedWorkspaceChats = true) {
    return getOptions(reports, personalDetails, {
        betas,
        searchInputValue: searchValue.trim(),
        selectedOptions,
-       maxRecentReportsToShow: 5,
+       maxRecentReportsToShow: 0, // Unlimited
        includeRecentReports: true,
        includeMultipleParticipantReports: true,
-       includePersonalDetails: true,
+       includePersonalDetails: false,
        excludeLogins,
        includeOwnedWorkspaceChats,
+       includeThreads: true,
+       includeMoneyRequests: true,		
    });
}
```
Additionally, I think we can pass `showChatPreviewLint: true,` and `sortByReportTypeInSearch: true,` for better user experience.
### What alternative solutions did you explore? (Optional)
None.

**Comment by thienlnam** [comment] 2023-07-17 20:49
Bump @0xmiroslav looks like we have a few more proposals here to review

**Comment by slafortune** [comment] 2023-07-20 20:28
@0xmiroslav is there a proposal here that we should get assigned out to?

**Comment by situchan** [comment] 2023-07-24 05:54
Coming from https://expensify.slack.com/archives/C02NK2DQWUX/p1690178033848139?thread_ts=1690177499.108059&cid=C02NK2DQWUX, I'd like to take this as C+

**Comment by Thanos30** [comment] 2023-07-25 13:46
@situchan Could you please take a look at my proposal and my comments? I think @0xmiroslav missed them. Thanks 🙏

**Comment by slafortune** [comment] 2023-07-26 20:40
Removing the overdue!

**Comment by situchan** [comment] 2023-07-30 17:04
I think we can show all reports (no matter threads, tasks, money requests) as long as task can be assigned there.
So after our fix, Share somewhere list will be all reports that have "Assign task" option in composer + menu.
@thienlnam do you agree?

**Comment by situchan** [comment] 2023-07-30 17:13
I think @StevenKKC's proposal is the most close. Just one case is missing: https://github.com/Expensify/App/issues/20898#issuecomment-1636155504.
@StevenKKC can you please update your proposal to cover this case?

**Comment by Thanos30** [comment] 2023-07-30 17:19
@situchan @thienlnam stated that we needed the chats that are available on the LHN. I was constantly discussing this issue and the desired results with the assigned team. How is my proposal diverting from the desired case? I would really appreciate the feedback, as I posted a proposal here since the very beginning of the issue and really looked into it.

**Comment by situchan** [comment] 2023-07-30 17:21
@Thanos30 your solution doesn't cover all chats available in LHN. Please test yourself - threads, tasks, iou, expense reports

**Comment by Thanos30** [comment] 2023-07-30 17:24
@situchan In that case, we just need to include the:
```
includeOwnedWorkspaceChats = true,
        includeThreads = true,
        includeTasks = true,
        includeMoneyRequests = true,
```
I was told not to includes these when I asked questions about the issue.

My proposal also solves the issue mentioned by @0xmiroslav , I also posted a comment with a thread that this is being discussed

**Comment by situchan** [comment] 2023-07-30 17:26
> I was told not to includes these when I asked questions about the issue.

Can you please share that link?

**Comment by Thanos30** [comment] 2023-07-30 17:28
Sure, basically, this is an issue that occurs widely across the app, discussed here: https://expensify.slack.com/archives/C01GTK53T8Q/p1687390694872859

In our case though, the solution will remain the same regardless of solving the global issue, because we do not want to allow creation of new chats in the share destination, at least that was the case when I first proposed my solution. You can check that in my proposal, but the general issue with showing duplicate options is discussed on the above thread, it's something to do with `accoundID`

**Comment by situchan** [comment] 2023-07-30 17:30
>        includeOwnedWorkspaceChats = true,
>        includeThreads = true,
>        includeTasks = true,
>        includeMoneyRequests = true,

Oh, there were tons of discussions on that thread. Can you please share link to the exact comment where these should not be included in Share somewhere list?

**Comment by Thanos30** [comment] 2023-07-30 17:38
Eehh, sorry, I couldn't find that, but I was told to keep the default values of getOptions for special chats.

I could change that specific case if that's the only issue, as my solution also covers disabling the creation of new chats, which doesn't happen on other proposals and I believe we don't desire that.

Also, while Steve's  proposal looks great, he is filtering out unavailable reports as I can see, while that can be avoided in the getOptions function in the first place.

If my proposal is lacking on any other field I would really appreciate the feedback.

Again, thank you for your time!

**Comment by situchan** [comment] 2023-07-30 17:46
@thienlnam I think we should confirm these option flags:
- sortByReportTypeInSearch
- showChatPreviewLine
- forcePolicyNamePreview
- includeOwnedWorkspaceChats
- includeThreads
- includeMoneyRequests
- includeTasks

I suggest all these values to true to be aligned with global Search options list. What do you suggest?

**Comment by Thanos30** [comment] 2023-07-30 17:48
These are the default values in `getOptions` function
https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/OptionsListUtils.js#L595-L617

**Comment by situchan** [comment] 2023-07-30 17:53
Personally I wanna keep ordering and display names (title, subtitle) same as 🔍 but just filter only available reports where task can be created.

https://github.com/Expensify/App/blob/eb020063789091eb2e3086b5b54af3ead8436645/src/libs/OptionsListUtils.js#L872-L888

**Comment by Thanos30** [comment] 2023-07-30 17:55
Correct me if I am wrong, but I think they would like it to be sorted by most recent report. Makes sense if this is about sharing a task

**Comment by situchan** [comment] 2023-07-30 18:00
> Correct me if I am wrong, but I think they would like it to be sorted by most recent report. Makes sense if this is about sharing a task

Search already does, doesn't it?

**Comment by Thanos30** [comment] 2023-07-30 18:10
Hmm, I might be confused due to the high traffic account I checked. You could be right, sorry for the inconvenience. I believe this is how it worked in my proposal, unless the sorting was added afterwards

**Comment by Thanos30** [comment] 2023-07-30 18:38
Also @situchan, I apologize for the mini-spam, it's just that I worked and put a lot of time in this issue, more than a month ago, and was in many conversations on it. I tried to propose the best solution that would cover all of the undesired functionalities, and I wouldn't want to miss it for something that changed overtime.

I am sorry if that came out differently, I don't mean to be offensive towards anyone contributing here if that was misunderstood 😁

**Comment by StevenKKC** [comment] 2023-07-31 07:13
@situchan Thanks for your reply. 
In my proposal, does not retrieve `userToInvite` from `OptionsListUtils.getShareDestinationOptions`, so the case mentioned in https://github.com/Expensify/App/issues/20898#issuecomment-1636155504 will not occur.
```js
const {recentReports} = OptionsListUtils.getShareDestinationOptions(
```

**Comment by thienlnam** [comment] 2023-07-31 17:26
The option flags you listed in https://github.com/Expensify/App/issues/20898#issuecomment-1657229130 sound good to me - you should be able to create a task within any one of those reports.

**Comment by situchan** [comment] 2023-07-31 18:11
@StevenKKC's [proposal](https://github.com/Expensify/App/issues/20898#issuecomment-1636289283) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by getusha** [comment] 2023-07-31 18:17
@situchan is the proposal any different from mine? https://github.com/Expensify/App/issues/20898#issuecomment-1636181694 can you please check?

**Comment by situchan** [comment] 2023-07-31 18:23
@getusha yes, I reviewed your proposal already. It doesn't cover https://github.com/Expensify/App/issues/20898#issuecomment-1657221140 and https://github.com/Expensify/App/issues/20898#issuecomment-1636155504.

**Comment by Thanos30** [comment] 2023-07-31 18:25
@situchan
Can't help to feel a bit deprived here to be honest. I proposed a solution way before anyone else, and covered all the desired aspects that I was asked to.

I don't want to undermine the other 2 proposals, but my proposal was there with plenty of info to explain the various issues that were going on, and the only issue you found out was something that changed overtime.

In addition to all these, purely code-wise, we can avoid doing extra work to filter out reports, when we should not pull them in the first place.

**Comment by situchan** [comment] 2023-07-31 18:43
@Thanos30 I agree the idea of setting `maxRecentReportsToShow` to 0 first came out from you, but https://github.com/Expensify/App/issues/20898#issuecomment-1629672152 is also important which you didn't cover in your proposal. So I gave approval timestamp to the first complete proposal which @StevenKKC submitted.
Still there's a chance of another opinion from @thienlnam. Let's wait for the final call.

**Comment by Thanos30** [comment] 2023-07-31 18:49
I totally get that @situchan , but I was initially told to use the default values of `getOptions` function, that's why I deliberately left these out.

These are just extra parameters we use on the function, not any code additions that I missed while working on it.

Also, `maxRecentReportsToShow` is one thing, but in my proposal, I set `includePersonalDetails` to false too, which doesn't pull any reports not available in LHN, and speeds up the task by a great amount, and also doesn't require the filtering afterwards.

**Comment by situchan** [comment] 2023-07-31 18:58
The solution to fix this issue is mainly changing flags in `getOptions`.
While you proposed only `maxRecentReportsToShow` and `includePersonalDetails` change, proposal I recommended has many more flags to update.

> + the removal of creating a new chat when typing a valid email address was also on my proposal

Please check https://github.com/Expensify/App/issues/20898#issuecomment-1657797800

**Comment by Thanos30** [comment] 2023-07-31 19:01
As I mentioned, I didn't change the flags that I was told not to change (was told to keep the default values for the report types). I saw that he did that, what I mean is that this was also covered in my proposal.

**Comment by getusha** [comment] 2023-07-31 19:02
>@getusha yes, I reviewed your proposal already. It doesn't cover https://github.com/Expensify/App/issues/20898#issuecomment-1657221140 and https://github.com/Expensify/App/issues/20898#issuecomment-1636155504.

@situchan can't that be taken care of in the PR? because if we agreed to remove `filteredRecentReports` as i suggested `filteredUserToInvite` will also can be suggested to be removed and to modify other arguments.

**Comment by situchan** [comment] 2023-07-31 19:09
> As I mentioned, I didn't change the flags that I was told not to change (was told to keep the default values for the report types).

I asked https://github.com/Expensify/App/issues/20898#issuecomment-1657226238 but you couldn't find that.

> @situchan can't that be taken care of in the PR?

No, this kind of discussion should be done in proposal stage. If I follow you, kind of "getOptions flags should be adjusted" should be enough proposal to be accepted.

**Comment by getusha** [comment] 2023-07-31 19:18
@situchan i noticed this here, the proposal doesn't have to be perfect and post code diffs until it's perfect if it has the general fix with the right root cause, isn't that what qualifies to be the accepted proposal? thank you for your answers tho.

>Our process is - Get the issue assigned as soon as possible to the first contributor that can explain the root cause and has a solution to fix the root cause.
If we get into the nitty gritty, we’ll keep doing a back and forth in the issue which isn’t really effective.
Doing a back and forth in a PR is faster because we can test and reference code.
We stopped code diffs as proposals because of this reason only. To avoid back and forth of small tweaks to a proposal until it’s perfect.

**Comment by Thanos30** [comment] 2023-07-31 19:23
@situchan You are right about that. I searched again but I can't find it, unfortunately, it happened more than a month ago.

**Comment by situchan** [comment] 2023-07-31 19:25
@getusha yes, it's general process, but not all the issues. i.e. For regex issues, the proposal should include correct regex. "We should fix regex" is not acceptable.
Also, "getOptions flags should be adjusted" - if this is acceptable, @Thanos30 is first so you're still not eligible.

**Comment by Thanos30** [comment] 2023-07-31 19:32
@situchan Thank you for your responses and again sorry for the back n forth conversation here.

I somewhat agree to agree to what @getusha mentioned, he did himself added the specific changes he would do so it wasn't that general.

Based on that, something like "we should add all the types of reports" could be possible to be discussed on the PR, as this is more like an extra thing and not the source of the problem to our issue here.

I mostly feel it's a bit unfair since I was really early on this and spotted the core of the issue after a fair amount of investigation.

I do admire your reviews and you wanting to be fair with everyone though 🙏

**Comment by thienlnam** [comment] 2023-07-31 23:27
Thanks for the proposals and conversation everyone - I am going with @Thanos30 here as I agree the root cause is the important part that needs to be addressed and then other smaller details can be addressed within the PR. I also appreciate your dedication on this issue and sticking through it!

**Comment by situchan** [comment] 2023-08-01 01:42
Thanks @thienlnam. I follow your decision.
@Thanos30 you finally got assigned 👍. Now please focus on raising perfect PR 🚀

**Comment by Thanos30** [comment] 2023-08-01 12:46
@thienlnam @situchan I really appreciate both of you, thank you for your consideration 🙏  🙏 

I will have the PR ready by tonight! 🚀

**Comment by Thanos30** [comment] 2023-08-01 18:05
PR is ready for review @situchan , @thienlnam 

@situchan I didn't include `sortByReportTypeInSearch`, as this only takes place when `personalDetails` are also pulled.

In our case where we only pull recentReports, this won't do any difference, but please let me know if we should include it.

Thanks!

**Comment by slafortune** [comment] 2023-08-16 15:50
External issue reporter - applause - no payment
Contributor that fixed the issue - @Thanos30 $3000 - PD
Contributor+ that helped on the issue and/or PR  - @situchan $3000 - PD

Speed bonus applied 🎉 
@Thanos30 got assigned: 2023-07-31 23:27:33 Z
when the PR got merged: 2023-08-03 21:03:11 UTC

**Comment by slafortune** [comment] 2023-08-16 15:51
@situchan Can you complete the checklist?  Thanks much!

**Comment by situchan** [comment] 2023-08-16 15:57
No PR caused regression. We didn't consider unknown user (never chatted yet) case during initial implementation of task destination selection.
I'd say this is a new feature rather than bug so no regression test is needed.

**Comment by slafortune** [comment] 2023-08-16 15:58
Ah!  Thanks for that 👍

**Closed by slafortune** 2023-08-16 15:58 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
