### ISSUE TITLE
[$250] BUG: Pointer cursor is lost when FAB menu button is clicked reported by @mdneyazahmad

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11707] opened 2022-10-10 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to https://staging.new.expensify.com/
2. Hover over the fab button
3. Click on the fab button

## Expected Result:
Pointer cursor is not lost

## Actual Result:
Pointer cursor is lost

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.2.12 -2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/194929563-a34901da-f05d-45d3-86e7-7a369f9e03d8.mov

https://user-images.githubusercontent.com/43996225/194929531-fa81826a-17ed-409e-8ff9-67474b1abcaf.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665394506103059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by davidcardoza** [comment] 2022-10-11 07:23
I am not able to reproduce this issue. Can you please reopen if the issue continues to happen.

**Comment by mdneyazahmad** [comment] 2022-10-11 07:25
@davidcardoza it is still reproducible

**Comment by davidcardoza** [comment] 2022-10-11 07:34
Ah okay, I was able to reproduce on staging and production.

![2022-10-11_00-33-17 (1)](https://user-images.githubusercontent.com/6643649/195024600-85deb41d-5740-4fa8-b9b0-0d53312bc47e.gif)

**Comment by techievivek** [comment] 2022-10-14 20:19
This can be worked externally, so passing it to lovely contributors to lend a helping hand.

**Comment by neil-marcellini** [comment] 2022-10-17 18:06
Waiting for proposals.

**Comment by neil-marcellini** [comment] 2022-10-19 23:28
Same

**Comment by neil-marcellini** [comment] 2022-10-24 18:52
Still waiting for proposals. It has been a week now so can we please double the price @davidcardoza?

**Comment by davidcardoza** [comment] 2022-10-26 19:27
The job wasn't posted to upwork, I put it up now https://www.upwork.com/jobs/~01905d666d9e627d40

**Comment by neil-marcellini** [comment] 2022-10-31 20:10
@davidcardoza now we need to double twice to $1000 right?

**Comment by davidcardoza** [comment] 2022-11-01 06:14
@neil-marcellini Someone submitted a proposal this evening. The contract proposal is now pending.

**Comment by neil-marcellini** [comment] 2022-11-01 16:16
What do you mean? Where is the github comment for the proposal? No one should be hired on upwork until the proposal is approved by C+ and CME here. Also why isn't there a C+ on this issue? Oh I see that @techievivek unassigned him, why? I will add the C+ back to this issue so we can continue with the #bug-zero process outline in [this SO](https://stackoverflow.com/c/expensify/questions/14418).

**Comment by neil-marcellini** [comment] 2022-11-04 17:25
@davidcardoza please double the price to $1000 and update the issue title https://github.com/Expensify/App/issues/11707#issuecomment-1297624869

**Comment by neil-marcellini** [comment] 2022-11-04 17:56
I think the main problem is that the create menu is in a modal so everything outside of that menu is not hoverable since it's covered by a modal backdrop. You can see that the backdrop has a very high z-index meaning it covers everything. I'm not quite sure what the best solution is. I'm also not sure if this is really a problem worth fixing.

![image](https://user-images.githubusercontent.com/26260477/200043157-ed9a1d92-99f4-4a18-a015-defa0e6f8a59.png)

**Comment by thesahindia** [comment] 2022-11-04 17:58
I just came to comment the same. Let's close this.

**Comment by neil-marcellini** [comment] 2022-11-04 18:06
Yeah in a perfect world maybe you would see a pointer style cursor over the X button, but it's a very minor issue and I think it would require a lot of investigation and refactoring to fix. I doubt any users will complain about this as well.

**Closed by neil-marcellini** 2022-11-04 18:06 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
