### ISSUE TITLE
[HOLD for Payment 2024-09-12][$250]  Import categories - Nothing happens after dragging and dropping file into RHP

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48533] opened 2024-09-04 09:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Categories.
3. Click 3-dot menu.
4. Click Import spreadsheet.
5. Drag and drop a file into the RHP.

## Expected Result:
The file can be dragged and dropped into the RHP.

## Actual Result:
Nothing happens after dragging and dropping file into RHP.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/20c39abd-37ee-46cf-aeeb-6602b01b2f47

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831640860340610285</li>
        <li>Upwork Job ID: 1831640860340610285</li>
        <li>Last Price Increase: 2024-09-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by mkzie2** [comment] 2024-09-04 09:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens after dragging and dropping file into RHP.

### What is the root cause of that problem?

The drop event data does not include the file's URI, we need to manually create it:

https://github.com/Expensify/App/blob/aafd20d02c82f242589d14efe0a7ee6994d0f281/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L549-L553

### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)

In [here](https://github.com/Expensify/App/blob/a637a8ab33b175b85ea94dceb5e4869277cad823/src/components/ImportSpreadsheet.tsx#L171), create URI for the file object:

```javascript
if (file) {
                                        file.uri = URL.createObjectURL(file);
                                        readFile(file);
                                    }
```

**Comment by tuseefahmed786** [comment] 2024-09-04 10:05
> Edited by **proposal-police**: This proposal was **edited** at 2024-09-04 09:42:02 UTC.
> 
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Nothing happens after dragging and dropping file into RHP.
> 
> ### What is the root cause of that problem?
> The drop event data [here](https://github.com/Expensify/App/blob/a637a8ab33b175b85ea94dceb5e4869277cad823/src/components/ImportSpreadsheet.tsx#L171) does not include the file's URI, later we would early return if it's missing URI:
> 
> https://github.com/Expensify/App/blob/a637a8ab33b175b85ea94dceb5e4869277cad823/src/components/ImportSpreadsheet.tsx#L78-L80
> 
> ### What changes do you think we should make in order to solve the problem?
> We need to manually create it following the below implementation:
> 
> https://github.com/Expensify/App/blob/562d7b48226247253625b9ac1fd45266cb53eda8/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L549-L553
> 
> In [here](https://github.com/Expensify/App/blob/a637a8ab33b175b85ea94dceb5e4869277cad823/src/components/ImportSpreadsheet.tsx#L171), create URI for the file object:
> 
> ```js
> if (file) {
>     file.uri = URL.createObjectURL(file);
>     readFile(file);
> }
> ```

I was considering another method. I see that manually creating the URI with `URL.createObjectURL` is a workable solution. However, I wanted to make a point about potential memory management issues.

When using `URL.createObjectURL,` it's important to remember that these object URLs persist in memory until explicitly overridden. To prevent a possible memory leak, we should make sure that we call URL.revokeObjectURL() when the object URL is no longer needed.

Would it be helpful to add this cleanup step to our solution to manage memory usage more efficiently? I'd love to get feedback!

**Comment by mountiny** [comment] 2024-09-04 10:13
cc @filip-solecki @rushatgabhane @rlinoz coming from the import spreadsheet PR

**Comment by mountiny** [comment] 2024-09-04 10:19
This indeed feels like a blocker for the feature, not demoting. Added @rushatgabhane as he reviewed the original PR https://github.com/Expensify/App/pull/47827

**Comment by filip-solecki** [comment] 2024-09-04 10:47
@mkzie2 Proposal looks good, maybe it will be better to put `createObjectURL` function inside `readFile` and use `revokeObjectURL` in finally as @tuseefahmed786 mentioned

**Comment by mountiny** [comment] 2024-09-04 14:55
@mkzie2 this is a deploy blocker, are you able to raise this PR and make it ready for review/ testing in the next couple of hours?

**Comment by mkzie2** [comment] 2024-09-04 15:58
Sure thing!

**Comment by mountiny** [comment] 2024-09-05 10:30
This is fixed in staging

**Comment by mountiny** [comment] 2024-09-05 10:32
I think the text was fixed too, not sure how to take this drag screenshot witchcraft though 😄 @dannymcclain

**Comment by mountiny** [comment] 2024-09-05 10:32
$250 to @mkzie2, no paymen to @rushatgabhane on this issue as his payment is handled in the op for the project

**Comment by dannymcclain** [comment] 2024-09-05 13:20
Yup! I see both things fixed on staging. 🚀 

![CleanShot 2024-09-05 at 08 18 47@2x](https://github.com/user-attachments/assets/3d642423-5493-486a-8857-fac93b3e5a25)

**Comment by rlinoz** [comment] 2024-09-12 18:28
This is in prod: https://github.com/Expensify/App/pull/48574#issuecomment-2332467743

**Comment by MariaHCD** [comment] 2024-09-17 06:52
The fix for this one was deployed to production. I believe we're just awaiting payment.

**Comment by JmillsExpensify** [comment] 2024-09-25 17:22
Payment summary:

 - Contributor: @mkzie2 $250
 - Reviewer: @rushatgabhane $250

**Comment by garrettmknight** [comment] 2024-09-26 15:38
$250 approved for @rushatgabhane

**Comment by JmillsExpensify** [comment] 2024-10-02 17:26
@mkzie2 are you still due payment on this issue?

**Comment by mkzie2** [comment] 2024-10-10 03:40
@JmillsExpensify offer accepted, we can pay out and close 👍

**Comment by JmillsExpensify** [comment] 2024-10-16 17:56
All done!

**Closed by JmillsExpensify** 2024-10-16 17:56 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
