### ISSUE TITLE
[$500] Web - When opening a receipt with a workspace from OD, a red dot appears. There is no error message if the receipt fails.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31364] opened 2023-11-15 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99.0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1 Case:
1. Create a WS from OD.
2. Navigate to the workspace chat as the employee
3. Select the option to Request money > Scan receipt
4. Select the option to upload a receipt
5. Upload a receipt file
6. Click on Request
7. Navigate to the request conversation
8. Wait until the scan of the receipt is complete
9. Once complete navigate to the request conversation

2 Case:
1. Create a WS from OD.
2. As the employee, navigate to the workspace chat
3. Select Request money > Scan
4. Upload a image of a blurry receipt
5. Complete the money request
6. After the scanned receipt shows a failure
7. Navigate to the workspace chat
8. Click on the preview to navigate to the report conversation

## Expected Result:
1 Case:
Verify the amount is updated and displayed
Verify the merchant field is filled (this is only filled if the merchant is visible in the receipt picture)
2 Case:
Verify there's an error message indicating "receipt scanning failed. Please enter the details manually"

## Actual Result:
1 Case:
Red dot appears when open a receipt if WS is from OD.
2 Case:
No error message indicating "receipt scanning failed. Please enter the details manually" if Receipt scan failed.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

**Case 1**

https://github.com/Expensify/App/assets/93399543/6bd2c913-8689-4e2f-b1cb-b4923239d9d7

**Case 2**

https://github.com/Expensify/App/assets/93399543/497446eb-a933-43db-9a2a-d3d3bdbc972d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fcb884d4c1db2d5</li>
        <li>Upwork Job ID: 1724773389816594432</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by keisyrzk** [comment] 2023-11-20 13:37
`case 1 - scanned receipt value`
Tried with two different PDFs and the server returns "0.00" value starting from "ReportScreen" component.
Test example:  `params.reportID` = 3241712811412309
----------
`the red dot` is appearing because the report has `smart scan errors`. Looks like the smart scan have problems with scanning the provided PDF receipt file. 
The `hasMissingSmartscanFields` returns true as:
- `hasReceipt(transaction)` - true
- `!isDistanceRequest(transaction)` - true
- `!isReceiptBeingScanned(transaction)` - true
- `areRequiredFieldsEmpty(transaction)` - true
----------

`no error message` 
The server response in this case is as follows:
`[
  {
    "amount": 0,
    "billable": false,
    "cardID": 18340638,
    "category": "",
    "comment": "",
    "created": "2023-11-20",
    "currency": "PLN",
    "filename": "w_e06bbd07a65bb1c6387e915a890cdbd50fa69f9e.pdf",
    "hasEReceipt": false,
    "merchant": "(none)",
    "modifiedAmount": 0,
    "modifiedCreated": "",
    "modifiedCurrency": "USD",
    "modifiedMerchant": "",
    "originalAmount": 0,
    "originalCurrency": "",
    "parentTransactionID": "",
    "receipt": {
      "receiptID": 674799630,
      "source": "https://www.expensify.com/receipts/w_e06bbd07a65bb1c6387e915a890cdbd50fa69f9e.pdf",
      "state": "SCANFAILED"
    },
    "reimbursable": true,
    "reportID": "7288149649442128",
    "status": "Posted",
    "tag": "",
    "transactionID": "2258001490579795195"
  }
]`

worth pointing that the scan failed
`"state": "SCANFAILED"`

------------
`Next Steps`
- **Is there any acceptable receipt forms so the algorithm is able to scan it?**
- would recommend checking backend logic and the scanning algorithm as well

**Comment by kevinksullivan** [comment] 2023-11-21 23:33
@akinwale can you take a look at the above?

**Comment by akinwale** [comment] 2023-11-23 19:01
@kevinksullivan It looks like this may be a backend issue, as observed in the post.

**Comment by kevinksullivan** [comment] 2023-11-27 23:02
ah apologies for missing that, updating the label.

**Comment by kevinksullivan** [comment] 2023-12-01 21:06
Hey @deetergp , can you take a look at this?

**Comment by deetergp** [comment] 2023-12-04 17:32
Hey @kevinksullivan. I will take a look at it later today.

**Comment by deetergp** [comment] 2023-12-11 20:06
bump @keisyrzk

**Comment by deetergp** [comment] 2023-12-14 19:50
@kevinksullivan @keisyrzk was using an un-SmartScan-able receipt for his testing.

**Comment by kevinksullivan** [comment] 2023-12-20 01:13
So this should be `external` then @deetergp ?

**Comment by deetergp** [comment] 2023-12-27 00:27
> So this should be external then @deetergp ?

Yes, I think so. Let's make sure we do any testing with a receipt that has at least a merchant, amount, and a created date.

**Comment by deetergp** [comment] 2024-01-03 06:21
Still waiting on a proposal.

**Comment by deetergp** [comment] 2024-01-09 23:49
Since we're still waiting on a proposal, I am setting it to weekly.

**Comment by mvtglobally** [comment] 2024-01-18 22:23
Issue not reproducible during KI retests. (First week)

**Comment by deetergp** [comment] 2024-01-19 00:37
That's hopeful. If we get a second week of it not being reproducible, let's close it.

**Comment by mvtglobally** [comment] 2024-01-30 04:54
Issue not reproducible during KI retests. (Second week)

**Comment by deetergp** [comment] 2024-01-31 17:08
Hasn't been reproducible for 2 weeks, so let's close it.

**Closed** 2024-02-01 19:27 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
