### ISSUE TITLE
[HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] IOU - When a new IOU is opened, the sum of the previous IOU is displayed in the modal window

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23973] opened 2023-08-01 00:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Preconditions:
Start creating an IOU, but close the modal window at the moment you select a contact
1. Open https://staging.new.expensify.com/

2. Click on the "Global action" button (Big green plus button in LHN)
3. Click on "Request money"

## Expected Result:
The amount of the previous IOU should not be saved when opening a new IOU

## Actual Result:
When opening a new IOU in the modal window, the amount of the previous uncompleted IOU has already been entered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/a1054e9c-12e5-48ad-a07c-1e07fdc64d28

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Tam / @natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690830970030189?thread_ts=1690829632.233769&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-08-01 02:54
No idea which PR might have introduced this. Nothing obvious stands out. I'd maybe check to see if the recent Onyx changes have something to do with it first.

**Comment by shubham1206agra** [comment] 2023-08-01 12:58
> No idea which PR might have introduced this. Nothing obvious stands out. I'd maybe check to see if the recent Onyx changes have something to do with it first.

This PR https://github.com/Expensify/App/pull/23749 introduces the issue.

**Comment by shubham1206agra** [comment] 2023-08-01 13:09
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

IOU - When a new IOU is opened, the sum of the previous IOU is displayed in the modal window

### What is the root cause of that problem?

As I have discussed with @hannojg on slack. This issue https://github.com/Expensify/App/pull/23749 creates read faster than writes, due to this, 
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/libs/actions/IOU.js#L1441 
depends on 
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/libs/actions/IOU.js#L64-L72.

As Onyx.update is slow, at `MoneyRequestAmountPage` older values populate the page due to read cached behaviour.

### What changes do you think we should make in order to solve the problem?

Since `Onyx.update` returns a promise, we can chain 
https://github.com/Expensify/App/blob/6c9e459f8114f1cd2986a83ede1d73fb150aa366/src/libs/actions/IOU.js#L1443
under a `.then` so we make sure that `MoneyRequestAmountPage` opens with latest values.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by Beamanator** [comment] 2023-08-01 15:54
@hannojg yeah good question, I feel like we should collapse all of these issues into 1 😅  I think it's fair to compensate if we use their solution 👍

**Comment by Beamanator** [comment] 2023-08-01 16:16
Should be fixed now, as of https://github.com/Expensify/App/pull/24003

**Comment by Natnael-Guchima** [comment] 2023-08-14 10:52
A gentle bump for reporting payment @Beamanator 🙂

**Comment by Beamanator** [comment] 2023-08-14 15:54
@marcaaron can you help get a BZ assigned to sort out payment? 🙏

**Comment by marcaaron** [comment] 2023-08-14 21:27
@slafortune can you help with https://github.com/Expensify/App/issues/23973#issuecomment-1677103356 🙏

**Comment by slafortune** [comment] 2023-08-16 21:18
External issue reporter - @Natnael-Guchima $250 - [OFFER](https://www.upwork.com/nx/wm/offer/26164886) sent
 Contributor that fixed the issue - NA
 Contributor+ that helped on the issue and/or PR - NA

**Comment by Natnael-Guchima** [comment] 2023-08-17 07:03
Accepted the offer. Thanks @slafortune

**Closed** 2023-08-17 12:56 UTC
Labels: Reviewing, Engineering, Daily, Awaiting Payment, Bug
