### ISSUE TITLE
[HOLD for payment 2024-08-14] [$250] [Payment card / Subscription] - Error message is not dismissed after entering text in the response field

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46182] opened 2024-07-25 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Found when validating https://github.com/Expensify/App/pull/44763
**Version Number:** 9.0.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** no this is new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Account has collect workspace with an annual subscription.

1. Go to staging.new.expensify.com
2. Go to Subscription.
3. Click "Request early cancellation".
4. Without selecting a reason, click Submit.
5. Select a reason.
6. Note that the error message disappears.
7. Click Submit without entering response in the text field.
8. Enter response in the text field.

## Expected Result:
The error message will be dismissed after entering text in the response field.

## Actual Result:
The error message is not dismissed after entering text in the response field.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/05fe3dd8-b897-47cf-bb89-e743de121310

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019378d79c0bd60aef</li>
        <li>Upwork Job ID: 1817975652284460058</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by m-natarajan** [comment] 2024-07-25 12:45
We think that this bug might be related to #wave-collect - Release2

**Comment by MariaHCD** [comment] 2024-07-25 14:31
This does not need to block the web deploy since this is a UX improvement

**Comment by francoisl** [comment] 2024-07-25 18:01
This doesn't block from requesting the early cancelation so I don't think it's worth blocking on.

https://github.com/user-attachments/assets/226091a2-a50a-49a0-8041-17ac56425290


cc @JKobrynski @blimpich as this likely comes from https://github.com/Expensify/App/pull/44763

**Comment by blimpich** [comment] 2024-07-25 18:06
Yeah I would consider this to be polish follow up for the PR @francoisl mentioned. I'll pick this up since I'm managing that project.

**Comment by blimpich** [comment] 2024-07-25 18:07
@JKobrynski can you make a follow up PR for this?

**Comment by blimpich** [comment] 2024-07-29 17:13
I'm going to mark this as external and get the ball rolling on this one.

**Comment by JKobrynski** [comment] 2024-07-30 13:55
Hi, I'm Julian from Callstack - expert agency - and I would like to work on this issue.

**Comment by trjExpensify** [comment] 2024-07-30 14:31
Assigned!

**Comment by trjExpensify** [comment] 2024-07-30 18:36
This is a regression follow-up from https://github.com/Expensify/App/pull/44763 for which Julian authored. 👍

**Comment by allroundexperts** [comment] 2024-08-11 20:59
## Regression test

1. Sign in to an account that has a collect workspace with an annual subscription.
2. Go to Subscription and click "Request early cancellation".
3. Without selecting a reason, click Submit.
4. Verify that an error message appears.
5. Select a reason.
6. Verify that the error message disappears.
7. Click Submit without entering response in the text field.
8. Verify that an error appears.
9. Enter response in the text field.
10. Verify that the error message will be dismissed after entering text in the response field.

Do we 👍 or 👎 ?

**Comment by greg-schroeder** [comment] 2024-08-13 16:02
This is a regression follow-up, so no payments are due in this issue tomorrow. I've filed the regression test above as well. Closing for now. Please reopen if I've missed anything.

**Comment by allroundexperts** [comment] 2024-08-15 00:20
@greg-schroeder I was not involved in the previous issue (if there was any). I think my payment is pending here for the review.

**Comment by greg-schroeder** [comment] 2024-08-15 07:00
@allroundexperts okay thanks! in that case you can make a manual request via ND for $250 for the reviewer role

**Closed** 2024-08-15 15:13 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-10-04 11:11
$250 approved for @allroundexperts
