### ISSUE TITLE
Users aren't receiving messages from Guides

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#22604] opened 2023-07-11 02:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Clicked the chat link within my email summary
2. Don't see the messages that my email says should be present
3. Sent a reply message to the SDR in NewDot
4. Message the SDR in Slack because they did not respond to me in New Dot
5. The SDR let me know that they did not receive my message
6. I went back into New Dot, did not see my message

## Expected Result:
Messages should be showing in NewDot if shown in email, and new messages should be delivered to the recipient

## Actual Result:
No messages shown in the email summary are in chat, and chats sent aren't received by the recipient

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [X] MacOS / Desktop

**Version Number:** Don't know
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** paige.smith@team.expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

See most recent chat in email:
![image](https://github.com/Expensify/App/assets/22508290/df45140e-3658-488a-a205-7f8ca36cf7ef)

Newdot doesn't show the message above in the email summary:
![image](https://github.com/Expensify/App/assets/22508290/07a44fcc-babd-432c-9255-45e80f92f8d7)

SDR says they never got the message

![image](https://github.com/Expensify/App/assets/22508290/c600f0a0-84cd-4ce7-b828-82e1db316c63)

**Slack conversation:** https://expensify.slack.com/archives/C036S0BVAHH/p1688578526266679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014978668b0019f93f</li>
        <li>Upwork Job ID: 1678586787802390528</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-07-12 15:58
@srikarparsi let me know what else you need to investigate this.

**Comment by srikarparsi** [comment] 2023-07-13 00:35
Hey @kevinksullivan! I was looking into this today and tried checking out the logs but couldn't figure out whether the message was actually sent and stored in the db and if there is a problem rendering it in new dot or if there was a problem with sending the message itself and it is not being encoded correctly. I asked @chiragsalian  if he had any advice and we scheduled a call for tomorrow morning so I should be able to figure out if I need any other information by then.

**Comment by srikarparsi** [comment] 2023-07-13 18:45
Query to find the report id using both participants:

`SELECT sr.reportID, COUNT(DISTINCT accountID) AS totalParticipants FROM sharedReports sr INNER JOIN reportNameValuePairs rNVPs ON rNVPs.reportID = sr.reportID WHERE rNVPs.name = 'expensify_policyID' AND rNVPs.value = '_FAKE_' AND sr.reportID IN (SELECT sr1.reportID FROM sharedReports sr1 INNER JOIN sharedReports sr2 ON sr1.reportID = sr2.reportID  WHERE sr1.accountID = 14645748  AND sr2.accountID = 11617966 ) AND sr.reportID NOT IN (SELECT reportID FROM reportNameValuePairs WHERE name =  'parentReportActionID' ) GROUP BY sr.reportID HAVING totalParticipants = 2;`

**Comment by chiragsalian** [comment] 2023-07-13 18:47
```
chirag@db2.rno:~$ sudo readdb.sh "SELECT sr.reportID, COUNT(DISTINCT accountID) AS totalParticipants FROM sharedReports sr INNER JOIN reportNameValuePairs rNVPs ON rNVPs.reportID = sr.reportID WHERE rNVPs.name = 'expensify_policyID' AND rNVPs.value = '_FAKE_' AND sr.reportID IN (SELECT sr1.reportID FROM sharedReports sr1 INNER JOIN sharedReports sr2 ON sr1.reportID = sr2.reportID  WHERE sr1.accountID = 14645748  AND sr2.accountID = 11617966 ) AND sr.reportID NOT IN (SELECT reportID FROM reportNameValuePairs WHERE name =  'parentReportActionID' ) GROUP BY sr.reportID HAVING totalParticipants = 2;"
reportID          totalParticipants
----------------  -----------------
1916732770519279  2
```

**Comment by srikarparsi** [comment] 2023-07-13 19:09
Hey @kevinksullivan! Do you think you could ask Paige to refresh the page and also to sign out and sign back in to see if she gets the "Sorry Paige, would you mind adding my email to the meeting invite ..." message. Me and Chirag were debugging for a bit and we do see that message in the database so seeing if it comes up on refresh/sign out sign in would help figure out whether it's an issue with pusher to send notifications or something else.

**Comment by zanyrenney** [comment] 2023-07-17 09:20
bump @kevinksullivan

**Comment by zanyrenney** [comment] 2023-07-18 12:50
<img width="1415" alt="2023-07-18_13-50-44" src="https://github.com/Expensify/App/assets/56830058/4184e667-98b8-4af0-97aa-733d04fd3d98">

**Comment by PaigeSE** [comment] 2023-07-18 16:00
Hi,
I went into New Dot and refreshed the page. When I refreshed the black screen with the Expensify symbol showed for about a minute and then the room came up but none of the dialog appeared. I waited for 6 minutes and decided to try and sign out instead and I would get a pop-up window saying the tab wasn't responding. 

Since I was not able to refresh or sign out before searching for the room I decided just to search for the chat. The chat room came up and I was able to see the messages with in the room.

**Comment by srikarparsi** [comment] 2023-07-18 20:53
Thanks @PaigeSE! Just wanted to confirm, were you able to see the "Sorry Paige, would you mind adding my email to the meeting invite ..." message?

**Comment by srikarparsi** [comment] 2023-07-20 04:17
Got it, thanks Paige. For this issue then, I think it's related New Dot being slow in general and especially slow for guides who deal with significantly more policies. I asked about it in the vip-fast-apis channel [here](https://expensify.slack.com/archives/C05CBC62HGW/p1689826622043449) and will update this issue with a response.

**Comment by zanyrenney** [comment] 2023-07-21 10:18
thanks @srikarparsi

**Comment by zanyrenney** [comment] 2023-07-24 15:15
any update on this one yet @srikarparsi ?

**Comment by srikarparsi** [comment] 2023-07-25 03:46
Hey @zanyrenney, not yet unfortunately, I'll look into it more tomorrow and ask if I need any more information.

**Comment by srikarparsi** [comment] 2023-07-27 21:32
Investigating these [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227e8bec5acd594519-ATL%22)+AND+timestamp:[2023-07-18T14:57:56.342Z+TO+2023-07-18T16:57:56.342Z]&index=logs_expensify-023363)

**Comment by zanyrenney** [comment] 2023-07-31 11:07
Anything come up from the logs that can help move this forward @srikarparsi ?

**Comment by srikarparsi** [comment] 2023-07-31 22:06
Hey @zanyrenney! I haven't been able to get this today. How big of a priority is this? I'm focussed on a lot of WAQ bugs at the moment and am wondering if I can demote this to a weekly.

**Comment by zanyrenney** [comment] 2023-08-01 17:07
Seeing as Guides drive our sales effort and help us grow, and this is part of ND, this one should be a priority too.

**Comment by zanyrenney** [comment] 2023-08-01 17:08
I'm heading OOO so if you have other questions @srikarparsi - @kevinksullivan might be a good point of contact as he reported the bug. I'll also assign a Bug buddy to watch over this.

**Comment by srikarparsi** [comment] 2023-08-03 22:04
Hi @PaigeSE! Do you think you could send the urls for any other chats that this is occurring for?

**Comment by zanyrenney** [comment] 2023-08-07 11:34
Bump @PaigeSE please can you send those URLs?

**Comment by srikarparsi** [comment] 2023-08-08 05:47
The URLs for when you sent the message, can see it, and the other person didn't get it please.

**Comment by PaigeSE** [comment] 2023-08-08 17:00
I know for sure this is one of them: https://new.expensify.com/r/7772587009623187

**Comment by srikarparsi** [comment] 2023-08-09 06:31
Thanks @PaigeSE, if you have any details regarding the message that was sent which the other person didn't get, that would be helpful as well. Also, is this still reproducible for that chat? As in, if you send a new message in that chat, is it still the case that the other person won't receive it?

**Comment by srikarparsi** [comment] 2023-08-10 20:59
Hey @PaigeSE! Bump on the above question. I also said you think this might've gotten resolved [here](https://expensify.slack.com/archives/C036S0BVAHH/p1691593261204129?thread_ts=1691077967.058719&cid=C036S0BVAHH). If that is the case, I can close out this issue and if it reoccurs, can you please provide a screenshot?

**Comment by PaigeSE** [comment] 2023-08-11 19:32
Hi @srikarparsi and @zanyrenney, so I rewatched the video to find the conversation. Here's the link to the meeting https://drive.google.com/file/d/1COPvgrMJSEwDfxqWR_1h420c3E3yg1F4/view?usp=sharing and the time stamp should be 22:20-27:55 when we discuss him not getting the message and you can see his chat. I had sent a message to him titled Expensify Post-Demo Follow Up and he did not receive it to his email. I resent it while we were on the call. I could see it on my end but he could not see it on his end. He did find the original message but that message never came into his Inbox as an email like it should have.

Hey, I can not be sure it's resolved until someone brings it to my attention that a message was sent to me or never received from me. To my knowledge, it is resolved.

**Comment by PaigeSE** [comment] 2023-08-11 20:39
I have a customer saying that they've been reaching out to me but I have nothing from them as you can see from the screenshot. So maybe the issue is not fixed.

![Screenshot (1071)](https://github.com/Expensify/App/assets/104375837/8ef286ca-a531-42b5-8050-33bafcb8e7ce)

**Comment by PaigeSE** [comment] 2023-08-11 21:09
I'm not sure if I should post this here but I have another user who just messaged me. She was saying she isn't sure if I got her message and resent me what she told me before. I did get her message and I replied but I'm looking and I don't see the reply. All I see is an automated message that was sent. Should I post those details here or no?

**Comment by zanyrenney** [comment] 2023-08-14 09:17
Hey @PaigeSE yes please. 

@srikarparsi what's the latest here? this is affecting real users (our Guides!) and preventing us from closing deals which has a direct impact on revenue. Please can you prioritise this? Feel free to DM Paige to get more immediate answers, I've done that when working with SR/Guides and it helps speed up the process a bunch. Thanks!

**Comment by PaigeSE** [comment] 2023-08-15 13:09
This is the other chat. As you can see she messaged me to give me an update on the Expensify Card she applied for. The second screenshot shows my reply but you can see that she follows up saying she doesn't know if I got her message and retells me what's in the first screenshot. I would also like to know when I posted here on Aug. 11 about this chat I also could not see my reply to her, so it looked as if I never responded.

![Screenshot (1095)](https://github.com/Expensify/App/assets/104375837/ed538924-6921-4707-9549-c623a242d71e)

![Screenshot (1094)](https://github.com/Expensify/App/assets/104375837/f57d50cb-96f1-4500-a922-16f0378c4826)

**Comment by PaigeSE** [comment] 2023-08-15 16:37
Hi @srikarparsi ,

I cannot find my hello message or the message that I resent that day but luckily I have a screenshot showing that I had sent a message. The first screenshot is what I can see today. The second screenshot is from July 5 and you can clearly see that above Trevor messages I had resent the Follow Up message to him.

![Screenshot (1098)](https://github.com/Expensify/App/assets/104375837/caf168e9-0991-4c08-bc63-c5b5e8ed177e)

![Screenshot (877) point](https://github.com/Expensify/App/assets/104375837/1ad98750-8d35-4c50-8d6c-347387ca081a)

**Comment by srikarparsi** [comment] 2023-08-16 02:50
From what I've understood, it looks like there's a couple of issues combined in this.

1. Messages that guides sent are disappearing when they try to view the message later. These messages are also not being sent to users. This probably means that the message is not being stored in the database. [Link](https://github.com/Expensify/App/issues/22604#issuecomment-1679267769)
2. Messages that guides are sending are still visible to guides later on. But these messages are not being received by users. This means the message is being stored in the database but might not be being stored correctly. [Link](https://github.com/Expensify/App/issues/22604#issuecomment-1678911565)
3. Messages that users are sending are not being received by guides. We're not sure whether or not the user can see the message when they revisit the chat. [Link](https://github.com/Expensify/App/issues/22604#issuecomment-1675380147)

I'm trying to find logs for each of the examples linked to figure out what command is going wrong but I'm having trouble locating them since we don't show the messages themselves in logs. I'm going to ask for help on this one since I understand it's pretty urgent for guides.

**Comment by PaigeSE** [comment] 2023-08-16 16:24
![Screenshot (1107)](https://github.com/Expensify/App/assets/104375837/620198d5-5111-49fd-bd1a-f66b6e0b09cd)

**Comment by srikarparsi** [comment] 2023-08-16 20:25
Hey @PaigeSE, sorry for asking a ton of questions but could you send the urls of the chats I linked in this [comment](https://github.com/Expensify/App/issues/22604#issuecomment-1679884920). Whenever you get a chance. We store the reportID in the url and having that information would help us see which messages are being stored in the database and which are not.

**Comment by srikarparsi** [comment] 2023-08-17 02:45
Want to provide an update on this issue. @cead22 helped me debug for 40ish minutes today and we analyzed the examples from this [comment](https://github.com/Expensify/App/issues/22604#issuecomment-1679884920). 

For [2](https://github.com/Expensify/App/issues/22604#issuecomment-1678911565), we do see the messages in the database so this means that it's a problem on the users side and not the guides side. This would probably be solved with the user signing out and signing back into New Dot.

For [3](https://github.com/Expensify/App/issues/22604#issuecomment-1675380147), we weren't able to investigate this because we don't have a screenshot from the users side that shows the messages they sent that are not showing up. If we can a screenshot from their end, it would be helpful to see exactly what's going wrong since this happened in the last 35 days. I do understand if that's difficult though since the user seems a little frustrated already.

[1](https://github.com/Expensify/App/issues/22604#issuecomment-1679267769) is the main issue we're curious about. The message sent "I've added a few resources below to recap the demo" doesn't appear in the database but we can clearly see it in the screenshot without an error or it being grayed out. We tried to investigate further by searching through the logs but unfortunately this example is from July 3rd and our logs only go back 35 days so we weren't able to access this. If there's a similar example of a message disappearing from your end that occurred more recently, then we could investigate this better since right now we're kind of at a dead end.

**Comment by PaigeSE** [comment] 2023-08-17 13:08
Hi @srikarparsi , while responding to emails and new dot messages yesterday afternoon/evening time my active messages went from being around 20-30 to 1,6000+. Would this have something to do with what we are working on here?? Could these be messages that were sent but just couldn't be seen on my end or is this a totally different issue?

**Comment by srikarparsi** [comment] 2023-08-17 16:05
Hey! I don't believe so since we didn't make any changes to the code. But this does seem like a bug. Could you check if other guides are experiencing a similar issue?

**Comment by srikarparsi** [comment] 2023-08-17 16:18
Hey, actually someone already posted an issue for this internally and it should be solved soon since the PR is already out.

Also, please do let me know if you see any other examples of "disappearing chats" where you send a message and it disappears when you try to view it at a later time. Screenshots would be really helpful as well if possible.

**Comment by zanyrenney** [comment] 2023-08-21 10:24
hey @srikarparsi thanks for the update!

>  it should be solved soon since the PR is already out.
Mind linking the PR please?

**Comment by srikarparsi** [comment] 2023-08-21 16:01
Hey! Yup, here's the comment which explains the [PR](https://expensify.slack.com/archives/CC7NECV4L/p1692288369797639?thread_ts=1692285984.619439&cid=CC7NECV4L) that was deployed to fix this.

**Comment by zanyrenney** [comment] 2023-08-22 11:24
Brilliant, thanks @srikarparsi - closing this one out then! 🎉

**Comment by srikarparsi** [comment] 2023-08-22 15:59
Hey @zanyrenney! Just to clarify, the PR that I linked doesn't solve this issue. It solves the other issue Paige commented about [here](https://github.com/Expensify/App/issues/22604#issuecomment-1682257188) where guides have tons of unread indicators. I [asked Paige](https://github.com/Expensify/App/issues/22604#issuecomment-1682585564) to link any examples of disappearing chats she sees from her end because of the conclusions drawn from [here](https://github.com/Expensify/App/issues/22604#issuecomment-1681528446). But these are kind of hard to find since she would have to screenshot any message she has a doubt will disappear to later show that it disappeared.

**Comment by zanyrenney** [comment] 2023-08-23 17:11
Oh thanks for reopening, that wasn't clear to me! @PaigeSE please can you help with those examples for Srikar.

**Comment by srikarparsi** [comment] 2023-08-28 20:08
Waiting for above.

**Comment by zanyrenney** [comment] 2023-08-29 11:19
@PaigeSE please can you give an update for Srikar?

**Comment by PaigeSE** [comment] 2023-08-29 21:54
Hey @srikarparsi and @zanyrenney I have an example of a chat that was said to be sent but I didn't get anything. So yesterday in Slack I got a message in [customer chat](https://expensify.slack.com/archives/CAS1DND4H/p1693251453871119) saying a customer was trying to reach out to me. I searched my email and couldn't find anything. He then informed me he reached out in our chat. I checked my 1-to-1 chat with him there was nothing. I checked for the admin rooms of the two policies and one doesn't show up at all and the other doesn't have any messages in them.

![Screenshot (1170)](https://github.com/Expensify/App/assets/104375837/681b0bbc-da85-4805-b2eb-34a9b411a471)

![Screenshot (1171)](https://github.com/Expensify/App/assets/104375837/653b8b57-8e41-4bf3-b5e4-18e8725be0ba)

![Screenshot (1172)](https://github.com/Expensify/App/assets/104375837/1e94ac2b-0c58-4069-bf7d-f6caee9491fb)

![Screenshot (1173)](https://github.com/Expensify/App/assets/104375837/a40782d2-7a3f-4f20-8339-d3d2a6839818)

![Screenshot (1174)](https://github.com/Expensify/App/assets/104375837/2394bc28-a8f9-47c1-8baa-f43252cd8c97)

![Screenshot (1176)](https://github.com/Expensify/App/assets/104375837/75b51bdf-76d5-4975-b448-f236a7916f00)

**Comment by zanyrenney** [comment] 2023-08-30 17:36
thanks for the extra info @PaigeSE 

@srikarparsi hopefully this helps us diagnose what's going on more here!

**Comment by srikarparsi** [comment] 2023-08-31 01:45
Hey Paige! Do you think you can ask the user to send a screenshot from their side with the message they sent. I'm not finding it in the logs and have a feeling that they might have sent the message incorrectly. Like if they sent it to someone else on accident or if their internet connection was unstable.

**Comment by PaigeSE** [comment] 2023-09-02 02:00
Hi @srikarparsi ,
Yes, I will reach out to him next week after the holiday and see if he will send me a screenshot of the message.

**Comment by zanyrenney** [comment] 2023-09-04 09:32
Waiting on screenshot from @PaigeSE

**Comment by PaigeSE** [comment] 2023-09-06 13:21
Hi @zanyrenney and @srikarparsi ,
Just to update you, I reached out to Mathieu yesterday morning asking if he could send a screenshot of the chat. I am still waiting for a response.

**Comment by zanyrenney** [comment] 2023-09-06 14:23
Thanks for the update @PaigeSE !

**Comment by zanyrenney** [comment] 2023-09-13 09:54
Thanks for the update. If we don't hear back in a few days, I think we should close this out because its now been 2 months and with the amount of other deploys, if we don't have recent examples, we can probably assume this is not a large issue anymore.

**Comment by srikarparsi** [comment] 2023-09-18 00:59
Agree with that as well :)

**Closed** 2023-09-18 07:24 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by PaigeSE** [comment] 2023-09-18 16:42
Hi @zanyrenney , sounds good.
