### ISSUE TITLE
[$250] [Search v2.2] - List does not scroll down and "To" field is hidden when "Save search" button appears

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49257] opened 2024-09-16 10:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search.
3. Click Filters.
4. Scroll down to the bottom.
5. Click "To".
6. Select any user and save it.

## Expected Result:
The list will auto scroll down to show "To" field when "Save search" button appears.

## Actual Result:
The list does not auto scroll down and "To" field is hidden when "Save search" button appears.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/506dde1a-c497-4934-8e02-e34fb4eaac13

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835635471984345939</li>
        <li>Upwork Job ID: 1835635471984345939</li>
        <li>Last Price Increase: 2024-09-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by IuliiaHerets** [comment] 2024-09-16 10:48
We think that this bug might be related to #wave-control

**Comment by lakchote** [comment] 2024-09-16 11:02
Not a blocker, it's a minor UI bug. Putting the external label.

**Comment by BhuvaneshPatil** [comment] 2024-09-16 11:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - List does not scroll down and "To" field is hidden when "Save search" button appears

### What is the root cause of that problem?
When we go to different page, the `AdvancedSearchFilters` component is unmounted/removed from dom. And we lose scroll position of scroll view. That's why it's always on top

### What changes do you think we should make in order to solve the problem?
We need to save the scroll offset. We need to do the following.
1. Create a ref for scroll view 
https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/pages/Search/AdvancedSearchFilters.tsx#L290

2.. We need to use `ScrollOffsetContext` to store the offset.
```tsx
const {saveScrollOffset, getScrollOffset} = useContext(ScrollOffsetContext);
```

3. We need to create `onScroll` function. This will be called when scroll the view. We need to handle the case when layout measurement is 0.
```tsx
    const onScroll = useCallback<NonNullable<ScrollViewProps['onScroll']>>(
        (e) => {
            saveScrollOffset(route, e.nativeEvent.contentOffset.y);
        },
        [route, saveScrollOffset],
    );
```

4. We need to use `useLayoutEffect` that will scroll down the view when component mounts.
```tsx
    useLayoutEffect(() => {
        if(!scrollRef.current){
            return;
        }
        const scrolledOffset = getScrollOffset(route);
        if (!scrolledOffset) {
            return;
        }
        scrollRef.current.scrollTo({y: scrolledOffset, animated: false});
    }, [getScrollOffset, route]);
```

### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-09-16 11:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

List does not scroll down and "To" field is hidden when "Save search" button appears

### What is the root cause of that problem?

After applying the `Save` filter, the `Save Search` button becomes visible

https://github.com/Expensify/App/blob/19d037b3a900b08de1f8ba2f22624ba445abe3a5/src/pages/Search/AdvancedSearchFilters.tsx#L310-L317
<img width="1709" alt="Screenshot 2024-09-16 at 18 41 02" src="https://github.com/user-attachments/assets/bedfeb20-6463-4508-b13f-7e623bc5f5b3">

### What changes do you think we should make in order to solve the problem?

We should calculate the current offset of the scroll and add the height of the `Save Search` button. Some thing like that:
```diff
// .src/pages/Search/AdvancedSearchFilters.tsx#L236
+ useFocusEffect(
+      useCallback(() => {
+           if (scrollViewRef.current && !SearchUtils.isCannedSearchQuery(queryJSON)) {
+               scrollViewRef.current.scrollTo({y: lastScrollPosition.current + 52, animated: false});
+           }
+       }, []),
+    );
```
 
### What alternative solutions did you explore? (Optional)

**Comment by drminh2807** [comment] 2024-09-16 12:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
List does not scroll down and "To" field is hidden when "Save search" button appears

### What is the root cause of that problem?
The "Save search" button make scroll view layout change

### What changes do you think we should make in order to solve the problem?

Auto-scroll to last visible position when layout changed
```js
            <ScrollView
                ref={scrollViewRef}
                onLayout={(e) => {
                    const newPosition = positionRef.current - e.nativeEvent.layout.height;
                    if (newPosition < 0) {
                        return;
                    }
                    scrollViewRef.current?.scrollTo({
                        y: newPosition,
                        animated: false,
                    });
                }}
                onScroll={(e) => {
                    positionRef.current = e.nativeEvent.contentOffset.y + e.nativeEvent.layoutMeasurement.height;
                }}
                contentContainerStyle={[styles.flexGrow1, styles.justifyContentBetween]}
            >
```


### What alternative solutions did you explore? (Optional)
N/A

**Comment by huult** [comment] 2024-09-17 03:13
## [Proposal update](https://github.com/Expensify/App/issues/49257#issuecomment-2352698200)

- Create function get/set/clear offset by name
- Add test branch

**Comment by VictoriaExpensify** [comment] 2024-09-19 04:40
Hey @akinwale - can you please review these proposals and let us know what you think?

**Comment by ChavdaSachin** [comment] 2024-09-19 06:01
> [!NOTE]  
Here's the reason why I have recommended to always show the save button over the other approaches.([My Proposal](https://github.com/Expensify/App/issues/49257#issuecomment-2352709831))
I checked out @huult's [solution](https://github.com/Expensify/App/issues/49257#issuecomment-2352698200) and it again has wrong scrolling behavior for different case.

<details><summary><h2>Check this video</h2></summary>
https://github.com/user-attachments/assets/24e76771-4917-4157-a31d-8d58840ecfc2
</details>
Notice `Merchant` was scrolled out of view.

And @drminh2807's [solution](https://github.com/Expensify/App/issues/49257#issuecomment-2352727450) would also behave similar for this case.

So rather, always showing `save` button is fairly simple and effective solution. 

cc. @akinwale

**Comment by huult** [comment] 2024-09-19 06:50
Thank you for your note, @ChavdaSachin ,
[My proposal](https://github.com/Expensify/App/issues/49257#issuecomment-2352698200) directly addresses this issue. I will provide an update on your problem after testing during the PR phase. I will update it as follows:
```diff
+   const onScroll = useCallback<NonNullable<ScrollViewProps['onScroll']>>((event) => {
+    const { layoutMeasurement, contentOffset, contentSize } = event.nativeEvent;

+    if (layoutMeasurement.height === 0) return;

+    const isAtBottom = layoutMeasurement.height + contentOffset.y >= contentSize.height;

+    if (isAtBottom) {
+        saveScrollOffsetByName(ADVANCED_SEARCH_FILTER, contentOffset.y);
+    } else {
+      getScrollOffsetByName(ADVANCED_SEARCH_FILTER) &&  clearScrollOffsetByName(ADVANCED_SEARCH_FILTER);
+    }
+}, []);
```

<summary>
<details>
POC

https://github.com/user-attachments/assets/5855d9e5-ca8f-48fa-8ea9-4c5913e01733

</details>
</summary>

cc @akinwale

**Comment by ChavdaSachin** [comment] 2024-09-19 07:52
@huult let me help you with the test cases here. 
1. Edit first field and check scroll behavior.
2. Edit last field and check scroll behavior.
3. Make sure first field is hidden and then edit second field
4. Make sure last field is hidden and then edit second last field
5.  Make sure first field is hidden and then edit last visible field
6. Make sure last field is hidden and then edit first visible field

> [!NOTE]
> Perform all of the above test with and without saving.

**Comment by akinwale** [comment] 2024-09-19 10:41
@ChavdaSachin Could you post a test video of your proposed solution?

**Comment by ChavdaSachin** [comment] 2024-09-19 10:49
Make `save` button always visible but disable it until all search fields are empty

https://github.com/user-attachments/assets/21409cbc-7967-4247-9f2c-70242e09692d

**Comment by ChavdaSachin** [comment] 2024-09-19 10:52
@akinwale my solution does not need the steps I mentioned above.

**Comment by ChavdaSachin** [comment] 2024-09-19 10:54
@akinwale do you want me to make a video on steps I mentioned [above](https://github.com/Expensify/App/issues/49257#issuecomment-2360247685)

**Comment by luacmartins** [comment] 2024-09-23 23:44
This is the expected behavior and not an issue. Closing this issue

**Closed by luacmartins** 2024-09-23 23:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
