### ISSUE TITLE
[$500] Split - Unexpected error create this chat and App crashed when go to announce

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30196] opened 2023-10-23 18:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Launch App and login as gmail account [kotkot7200@gmail.com](mailto:kotkot7200@gmail.com)
2. Tap on FAB
3. Select the Request Money
4. Select Manual tab
5. Enter amount select 3-4 users
6. Tap split bill
7. App crashed repro on all environments

## Expected Result:
6. Land in the Group DM with issue "Unexpected error creat this chat, please try again later”
7. App crashed repro on all environments

## Actual Result:
Step 6 repro on Android App

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/b7caeb91-e4b8-4f8a-b1c1-bc242f794eb7

![Bug6247605_1698077878012!IMG_7555](https://github.com/Expensify/App/assets/78819774/2de8e5b6-f8e1-412b-8e66-955799389261)

https://github.com/Expensify/App/assets/78819774/4842e4f0-e058-4503-861e-432cfbb63549

[logs.txt](https://github.com/Expensify/App/files/13077756/logs.txt)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b8c68459b0dd8b3</li>
        <li>Upwork Job ID: 1716524524646162432</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-10-25 17:39
Cannot reproduce on v1.3.90-2 but from my own account 

[kotkot7200@gmail.com](mailto:kotkot7200@gmail.com) How do I use this profile? @lanitochka17

**Comment by MitchExpensify** [comment] 2023-10-25 21:04
Closing until I hear back how to test with [kotkot7200@gmail.com](https://www.expensify.com/_support/?supportEmail=kotkot7200%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2030196&location=_support/) or if @lanitochka17 is still experiencing this on v1.3.90-2+

**Comment by tranvantoan-qn** [comment] 2023-10-26 03:11
It happened to me as well with the same step above, the full API response is below:

```
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "61F4D57E-F025-4289-B7F0-483FA8EB820D",
    "message": "There is a previously existing chat between these users.",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_8050269410285934",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1698289688911550": "There is a previously existing chat between these users."
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "report_8114495400597163",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1698289688911541": "There is a previously existing chat between these users."
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "report_6546399004525551",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1698289688911543": "There is a previously existing chat between these users."
                        }
                    }
                }
            },
            {
                "onyxMethod": "merge",
                "key": "report_6694334485956159",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1698289688911543": "There is a previously existing chat between these users."
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_8050269410285934",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1698289688911550": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_8114495400597163",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1698289688911541": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_6546399004525551",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1698289688911543": "There is a previously existing chat between these users."
                    }
                }
            }
        },
        {
            "onyxMethod": "merge",
            "key": "report_6694334485956159",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1698289688911543": "There is a previously existing chat between these users."
                    }
                }
            }
        }
    ],
    "requestID": "81bf7e3aebcb0953-HKG"
}
```

And there is a similar issue reported https://github.com/Expensify/App/issues/30140

**Comment by MitchExpensify** [comment] 2023-10-28 21:31
@tranvantoan-qn were you logged in to this account? [kotkot7200@gmail.com](https://www.expensify.com/_support/?supportEmail=kotkot7200%40gmail.com&comment=better%20supportal%20issue%20nubmer%3A%2030196&location=_support/)

**Comment by MitchExpensify** [comment] 2023-10-28 21:32
Either way, this is a dupe of https://github.com/Expensify/App/issues/30140 so closing this issue

**Closed by MitchExpensify** 2023-10-28 21:32 UTC
Labels: External, Daily, Help Wanted, Bug
