### ISSUE TITLE
[HOLD for payment 2023-11-27] [$1000] Web - Chat - The display name goes down when deleting an attachment in main thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25415] opened 2023-08-17 15:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Open any chat from LHN
3. send a pdf as an attachment
4. create a reply in the thread for the attachment
5. send a text in the thread
6. click the header in the thread and back to the main chat room
7. delete the pdf file
8. observe the display name

## Expected Result:
The display name should be in a fixed position

## Actual Result:
The display name goes down

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-1

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9cd42750-072e-4afc-923f-550e9acabb94

https://github.com/Expensify/App/assets/115492554/7921292a-3235-498c-aac5-8d96321dcf59

**Expensify/Expensify Issue URL:**

**Issue reported by:** @misgana96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692281066076859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015df75499581661dc</li>
        <li>Upwork Job ID: 1693715531299635200</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Contributor | 26249100</li>
<li>misgana96 | Reporter | 26249103</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-08-17 17:26
Going to see if I can replicate this but reviewing the information, I'm not sure its deploy-blocker worthy?

**Comment by yuwenmemon** [comment] 2023-08-17 18:20
Yes, defintely not deploy blocker worthy.

**Comment by yuwenmemon** [comment] 2023-08-17 18:21
This can be external as well @sophiepintoraetz - feel free to add at your leisure.

**Comment by Pujan92** [comment] 2023-08-17 18:33
I think regression or intentional from this [PR](https://github.com/Expensify/App/pull/24539)

**Comment by getusha** [comment] 2023-08-18 10:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a margin after deleting an attachment.
### What is the root cause of that problem?
This is a regression from https://github.com/Expensify/App/pull/24539
The external margin is only need for attachments that are not displayed as a group (for attachments that are the first message with avatar and name). Since the margin is applied to a component that renders every type of comment, it will also be applied to the `[Deleted message]` and then removed right away after the conditions are met. which will result in being applied and then removed causing this issue.

We should move the margin and conditions from the current place from here:
https://github.com/Expensify/App/pull/24539/files#diff-b9ff030858e3f02f7df3df9722486ca2e56c4c875b1af163819d5f980c168bf6R39
to:
https://github.com/Expensify/App/blob/fdcae9ff99696a1ac6068efbfe8927e1bcf108b7/src/pages/home/report/ReportActionItemFragment.js#L127

we also have to pass `isAttachment` from here:
https://github.com/Expensify/App/pull/24539/files#diff-b9ff030858e3f02f7df3df9722486ca2e56c4c875b1af163819d5f980c168bf6R37
Since the ThumbnailImage will be rendered here, it's the appropriate place to add the margin. We can wrap it with a View and apply the margin based on the conditions.

```js
<View style={[!props.displayAsGroup && props.isAttachment ? styles.mt2 : {}]}>
     <RenderHTML ... />
</View>
```
### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment] 2023-08-21 09:59
I created two small PRs:
- https://github.com/Expensify/App/pull/25560
- https://github.com/Expensify/App/pull/25557

After they will be merged, we'll choose whether we go with [a more local fix](https://github.com/Expensify/App/pull/25484) or [a refactoring](https://github.com/Expensify/App/pull/25524).

**Comment by sophiepintoraetz** [comment] 2023-08-21 20:03
Yup - I can reproduce - @yuwenmemon, are you comfortable assigning @cubuspl42 given their work introduced the PR?

**Comment by misgana96** [comment] 2023-08-22 00:02
Offer accepted. Thank You

**Comment by cubuspl42** [comment] 2023-08-22 08:09
@yuwenmemon I don't think I'm eligible for compensation, as the original issue is in the regression period.

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 17:44
Unassigning myself as there is C+ (@cubuspl42 ) assigned already

**Comment by cubuspl42** [comment] 2023-08-30 15:52
I bumped [the PRs I mentioned before](https://github.com/Expensify/App/issues/25415#issuecomment-1686024219). I'm sad about how much resistance I encountered, but that's a topic for a later time. Now, I'm focusing on closing this ASAP.

**Comment by sophiepintoraetz** [comment] 2023-09-04 06:02
@cubuspl42 - what do you mean you encountered resistance? Feel free to DM me in slack if you don't feel comfortable sharing it publicly. In anycase, I agree with you, let's hold until 11 Sep!

**Comment by sophiepintoraetz** [comment] 2023-09-13 07:33
Okay, I don't think we in the merge freeze so @cubuspl42 - are you good to carry on here?

**Comment by cubuspl42** [comment] 2023-09-13 09:23
I updated [both PRs](https://github.com/Expensify/App/issues/25415#issuecomment-1686024219) I mentioned before, also pinged the reviewers.

**Comment by yuwenmemon** [comment] 2023-09-14 16:44
Seems like @flodnv has been reviewing this one so reassigning to him

**Comment by cubuspl42** [comment] 2023-09-15 10:40
One PR merged (https://github.com/Expensify/App/pull/25560), one ready for review (https://github.com/Expensify/App/pull/25557), one work in progress.

@flodnv Could you help with moving forward https://github.com/Expensify/App/pull/25557?

**Comment by marcaaron** [comment] 2023-09-18 08:10
Tagging in C+ @situchan to help with the testing here.

**Comment by situchan** [comment] 2023-09-18 08:11
I requested changes in https://github.com/Expensify/App/pull/25557.
Any other PR pending my review here?

**Comment by cubuspl42** [comment] 2023-09-18 09:36
@situchan Not right now, but there will be soon! I'm glad this is unblocked and I'll try to get this issue closed ASAP.

**Comment by flodnv** [comment] 2023-09-21 09:13
I am a bit confused, why am I assigned here? What are the next steps? Do you know @yuwenmemon ?

**Comment by cubuspl42** [comment] 2023-09-21 10:14
@flodnv We'll waiting for https://github.com/Expensify/App/pull/25557 to be merged, then I'll rebase https://github.com/Expensify/App/pull/25524 on top of it.

You're probably assigned because I broke the process by separating the work into more than 1 PR, which seemed like a good idea in the beginning. But in consequence, everyone is confused.

**Comment by cubuspl42** [comment] 2023-09-21 10:18
The logic was like this.
We had a simple solution, but two things are getting into our way:
- Code duplication
- A totally unused chunk of code

My thought, based on my experience in software engineering was _let's deal with that two things first. A day after tomorrow we'll proceed with our solution, which now will be clear and easy to grasp!_. That was a month ago.

**Comment by flodnv** [comment] 2023-09-21 10:25
That sounds like it was (and still is) a good plan, so as previously mentioned, I think you should have linked all PRs to this GH, so it would have assigned 1 person with all the context to all PRs 😄 Next time! For now let's keep moving forward with this plan 👍

**Comment by sophiepintoraetz** [comment] 2023-09-28 08:34
Still ticking along on the PR - awaiting a review from @situchan

**Comment by sophiepintoraetz** [comment] 2023-10-02 09:25
Not overdue - waiting for the merge to hit production.

**Comment by cubuspl42** [comment] 2023-10-02 11:10
With https://github.com/Expensify/App/pull/25557 now merged, I rebased https://github.com/Expensify/App/pull/25524 on top of `main,` as [I said before](https://github.com/Expensify/App/issues/25415#issuecomment-1729274583).

> Not overdue - waiting for the merge to hit production.

...we also need to have https://github.com/Expensify/App/pull/25524 reviewed and merged, but then we're done!

**Comment by cubuspl42** [comment] 2023-10-26 09:07
We're working on the last fixes on the last PR

**Comment by misgana96** [comment] 2023-11-15 16:00
@flodnv  the issue has closed without paying for reporter bonus. I think I am an eligible for the reporter bonus. Please check it again.

**Comment by flodnv** [comment] 2023-11-15 18:57
Thanks for the call-out, we will also need to confirm it's indeed fixed.

**Comment by sophiepintoraetz** [comment] 2023-11-15 20:02
@misgana96 - you've been paid. @cubuspl42 or @situchan, can you confirm whether this is fixed?

**Comment by situchan** [comment] 2023-11-15 20:04
This was accidentally closed. This should go through QA. Not hit staging yet.

**Comment by cubuspl42** [comment] 2023-11-27 12:46
> * @cubuspl42 requires payment [offer](https://www.upwork.com/nx/wm/offer/26249100) (Contributor)

This doesn't formally qualify for payment, as it was a regression from a PR I was reviewing as a C+.

I would be grateful if this was treated individually, though. From my perspective, the bug had origins in the pre-existing convoluted code, which I cleaned over from unused leftovers and refactored, so a similar problem is less likely to return.

For various reasons, it took more work than I originally predicted, but I'm glad we finally merged it.

Thanks to everyone who helped review this!

**Comment by situchan** [comment] 2023-11-27 14:32
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24539
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24539#issuecomment-1827946924 but the author and reviewers already learned from mistake.
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

The bug itself is very minor and unusual case so I don't propose regression test.

**Comment by sophiepintoraetz** [comment] 2023-11-28 04:39
Fair enough, @cubuspl42 - have amended the offer. @situchan - you should have an offer in your inbox for review.

**Closed by sophiepintoraetz** 2023-11-28 04:39 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
