### ISSUE TITLE
[$1000] When adding Emoji (:face_in_clouds: ) shows weird and also one extra emoji gets added (:no_mouth: )

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13822] opened 2022-12-25 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. Go to chatting
3. Click this emoji (:face_in_clouds: ) ( it looks different in android though) from the app emoji
4. Click on this (:heart_on_fire:) emoji

## Expected Result:
 Emoji should show

## Actual Result:
Emoji doesn't show and also one extra emoji comes 
One emoji split into 2 emojis, @:heart_on_fire: -:heart: :fire: 

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209470322-b384b31f-2c37-47cd-90a3-e2cf8e813cbc.mp4

https://user-images.githubusercontent.com/43996225/209470346-1b19ebe9-3465-4693-a232-1ae920e71c2a.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ekramkhan66
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671825384904819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01117b6d2a14275aa5</li>
        <li>Upwork Job ID: 1607999811434373120</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2022-12-28 07:20
Feels like a contributor level issue.

**Comment by Pujan92** [comment] 2022-12-28 08:16
I am not able to reproduce it on my real android device.

**Comment by Prince-Mendiratta** [comment] 2022-12-28 08:35
# Proposal
# Cause
The 😶‍🌫️ emoji is part of the one of the latest release of modern emojis. To support these emojis, it is required to download the relevant emoji font pack. In Android Versions 11 and below do not have the ability to update the emoji font, thus the font must be updated manually on those lower versions. ([Source](https://developer.android.com/develop/ui/views/text-and-emoji/emoji2#java))
As can be seen from the original bug report at [Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1671825384904819), the OP is indeed on Android 11, thus the issue.

# Solution
Traditionally, this issue is resolved on Android by using the `androidx.emoji2:emoji2` library, which would replace the TextViews with the relevant Emoji inputs. However, there is no support for this in `React-Native`.

## Solution 1
In apps lke `Slack`/`WhatsApp`, emojis are provided by mapping them to the little images of the emoji for compatibility. However, We could implement such a system for the modern emojis but would increase bundle size, need your opinion on this.

## Solution 2
Use AppCompat 1.4 or higher as it includes support for emoji back to Android 4.4. This is a the usual fix but it's compatibility with React Native and it's impact on existing implementation needs to be further investigated.

**Comment by bernhardoj** [comment] 2022-12-28 12:51
This also happens to windows.

**Comment by bluestardragon** [comment] 2022-12-28 16:33
Hello
How about use this https://www.npmjs.com/package/react-native-emoji-input instead of TextInput of React native.

Following is some useful article, I think.
https://www.npmjs.com/package/react-native-emoji-input#missing-emojis-on-some-devices

**Comment by s77rt** [comment] 2022-12-28 20:39
What is the minimal Android version we are supposed to support? I think the use of images is something already planned to happen at some point.

**Comment by bluestardragon** [comment] 2022-12-28 21:23
I think Solution 2 is correct way. Current code is supported on Android 5.1 above and use androidX Appcompat libraries.
So if we are appending one line code for implementing support emoji library, emoji problem will be fix.

**Comment by mananjadhav** [comment] 2023-01-02 06:21
Thanks for the comments/proposal folks. @kavimuru Can you please confirm the Android device details (device info, OS version, etc.) I can't reproduce this in my Android device.

@Prince-Mendiratta Thank you for checking the version here, but I want to confirm the version QA is testing on.

Ideally we would want to support emojs instead of images atleast for the time being. Based on the Android version, we might not take any action too. @madmax330 @bfitzexpensify do we know what's the oldest version for each platforms we would want to support?

> It also happens on windows.

@bernhardoj Do you mean all browsers on Windows platform?

**Comment by bernhardoj** [comment] 2023-01-02 06:48
@mananjadhav Yes. Tested on Edge, Chrome, and Firefox.

Even on GitHub itself, it shows 2 emojis.

![image](https://user-images.githubusercontent.com/50919443/210201414-aff56592-2ae0-4c10-b662-483b9ce4d0ad.png)

**Comment by kavimuru** [comment] 2023-01-03 17:59
@mananjadhav My device is Galaxy S10 /11.0

**Comment by mananjadhav** [comment] 2023-01-05 05:57
> Based on the Android version, we might not take any action too. @madmax330 @bfitzexpensify do we know what's the oldest version for each platforms we would want to support?

@madmax330 @bfitzexpensify can you help with the above question?

**Comment by madmax330** [comment] 2023-01-05 11:20
@mananjadhav from this thread in slack it looks like we do support android 11
https://expensify.slack.com/archives/C01GTK53T8Q/p1672917496759309?thread_ts=1672910791.783889&cid=C01GTK53T8Q

**Comment by mananjadhav** [comment] 2023-01-05 12:59
Thanks for checking @madmax330.  So we're open for proposals!

**Comment by stitesExpensify** [comment] 2023-01-06 19:31
IMO we should just leave this as is. It's not our problem that Android/Windows aren't interpreting the unicode correctly. That's what we decided for flags in this issue https://github.com/Expensify/App/pull/13196

**Comment by jatinsonijs** [comment] 2023-01-06 19:37
I think it's different problem here if Android not able to interpret unicode it should also not work for emoji picker. But in attached video its showing correct emoji on emoji picker but when its added to Input create problem there.

**Comment by madmax330** [comment] 2023-01-09 09:08
Ah that's a good point @stitesExpensify maybe those emojis weren't yet supported on that version of android.

> But in attached video its showing correct emoji on emoji picker and when its added to Input display incorrect there.

If you look at the video in the OP, the bug is coming from the emoji picker. Can you clarify what you meant here by this @jatinsonijs

**Comment by jatinsonijs** [comment] 2023-01-09 09:19
@madmax330 Mean emoji picker and input are both part of Expensify app here. Emoji picker displaying latest emoji correctly as shown in video. But when we add it to input box splitting there ( showing 2 emojis). If it is not supported by Android it should also show 2 emoji on "emoji picker".
example for in below screenshot android emulator not able to interpret emoji so its showing same kind of behaviour in all area of app.

![Screenshot_1673255695](https://user-images.githubusercontent.com/114683042/211274514-63c60e9d-f692-49be-833e-1d34ddfdf5c9.png)

Here incorrect behaviour after adding in emoji in input.
check in attached video
https://github.com/Expensify/App/issues/13822#issue-1510332549

**Comment by madmax330** [comment] 2023-01-09 09:26
@jatinsonijs thanks, I see what you mean. 
What's making me hesitate is that these emojis work fine on other versions of android in the input. So any change we make here is specifically to support this version of android, which I'm not sure we want to do. Will ask for some other opinions in slack.

**Comment by madmax330** [comment] 2023-01-09 09:51
Brought up in slack here: https://expensify.slack.com/archives/C01GTK53T8Q/p1673257745362739

**Comment by bfitzexpensify** [comment] 2023-01-11 04:13
Sounds like from the Slack thread we agree that we shouldn't bother with a fix that is only applicable to Android 11. Let's close this out.

**Closed by bfitzexpensify** 2023-01-11 04:13 UTC
Labels: External, Daily, Help Wanted, Bug
