### ISSUE TITLE
[$250] Split - Date for split expense follows the day the split is created instead of receipt date

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42579] opened 2024-05-24 10:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4570881
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Split expense.
3. Upload a valid receipt with date.
4. Select a few users.
5. Split the expense.
6. Click on the split preview after scanning is successful.

## Expected Result:
The date in split details view should follow the date in the receipt.

## Actual Result:
The date in split details view follows the date the split is created.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8fd3d410-1f1e-4edf-bb5a-00fdb227d016

Receipt

![Bug6490054_1716516035756!Receipt_Example](https://github.com/Expensify/App/assets/115492554/bf2b9f82-ae60-429e-87f4-90e671d7ba9b)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e02b4ff506c31b0</li>
        <li>Upwork Job ID: 1794061080506175488</li>
        <li>Last Price Increase: 2024-05-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by izarutskaya** [comment] 2024-05-24 10:13
We think this issue might be related to the #vip-split.

**Comment by tsa321** [comment] 2024-05-25 14:28
I think back end issue...
The modifiedCreated of transaction doesn't changes for the split bill transaction after scans finished.

**Comment by MonilBhavsar** [comment] 2024-05-28 13:32
Looking into this...

**Comment by MonilBhavsar** [comment] 2024-05-28 17:29
PR is in review!

**Comment by MonilBhavsar** [comment] 2024-05-31 06:16
PR is deployed to production, We need to test it and update QA steps.

**Comment by garrettmknight** [comment] 2024-05-31 18:00
Not overdue - will test on Monday!

**Comment by garrettmknight** [comment] 2024-06-03 18:44
Testing here: https://staging.new.expensify.com/r/3146507204643460

**Comment by garrettmknight** [comment] 2024-06-04 10:39
Confirmed that it's using the SS date instead of the created date.

**Comment by garrettmknight** [comment] 2024-06-04 10:44
Closing since this didn't use any C+ review or external contributors.

**Closed by garrettmknight** 2024-06-04 10:44 UTC
Labels: Daily, Internal, Help Wanted, Bug
