### ISSUE TITLE
[$1000] Web - Task - Task actions not updated in real time in task report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20266] opened 2023-06-06 14:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19515

## Action Performed:
1. Login with any account
2. Click FAB icon >> Assign task
3. Fill in Title and Description >> Next
4. Select a contact for Assignee (Select the current user) and share somewhere
5. Press Confirm task
6. Navigate to the newly create Task report
7. Press Mark as done
8. Navigate to the Task report
9. Press vertical three dots menu on report header >> Mark as incomplete

## Expected Result:
Verify that the task is successfully marked as done in both Task report and parent report
Verify that the task is successfully re-opened in both Task report and parent report

## Actual Result:
Task actions are not updated in real time in task report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c9339f8b-9785-4820-9eae-a115000c2124

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c08a5e26aeab6cb2</li>
        <li>Upwork Job ID: 1666168015864901632</li>
        <li>Last Price Increase: 2023-06-13</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-06-06 19:40
reproducible, and I can't find an identical bug > external

**Comment by namhihi237** [comment] 2023-06-07 02:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Verify that the task is successfully marked as done in both Task report and parent report
Verify that the task is successfully re-opened in both Task report and parent report

### What is the root cause of that problem?
Currently "mark as done" and "Mark as incomplete" will call 2 APIs in `completeTask` and `reopenTask` functions.
But the problem here is that it's not realtime because the `optimisticData` data hasn't updated for `reportAction_{taskReportID}` just updated for `reportAction_{parentReportID}`.
### What changes do you think we should make in order to solve the problem?
We will add data in `optimisticData` and `failureData` in 2 functions `completeTask` and `reopenTask`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by rojiphil** [comment] 2023-06-07 07:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When tasks are completed and reopened in Task Report, the Task Report is not getting updated realtime.

### What is the root cause of that problem?
Once the task actions for `complete task` and `reopen task` are initiated and completed, the front end does not have the updated comments from the Task Report action. Hence, there is no real time update of the Task Report . This is the root cause.

### What changes do you think we should make in order to solve the problem?

Once the API request for `CompleteTask` and `ReopenTask` commands are initiated, also initiate an API request for `OpenReport` command so that updated report actions are triggered to perform real time updates to the Task Report.

The following line needs to be added after API calls
`    Report.openReport(taskReportID);
`

The code is referenced for [CompleteTask here](https://github.com/rojiphil/App/blob/15ea059e849f779c3eb62aa83e528b5c2b7b6c06/src/libs/actions/Task.js#L227) and for [ReopenTask here](https://github.com/rojiphil/App/blob/15ea059e849f779c3eb62aa83e528b5c2b7b6c06/src/libs/actions/Task.js#L290).

Alternatively, the backend can also update the Report Actions for the Task Report as part of API response of `CompleteTask` and `ReopenTask`. This will trigger the updates to the Task Report. 

Test Result Video:

https://github.com/Expensify/App/assets/3004659/a2d97199-b74a-4591-8fac-1f7adc7eea20


### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2023-06-07 16:08
Just checked this issue with 1.3.25-4.
Looks like the issue is resolved with pusher updates.

**Comment by abdulrahuman5196** [comment] 2023-06-07 18:22
@adelekennedy  Same here not able to reproduce on the latest main. Can we re-check and close the issue if its not reproducible?

**Comment by abdulrahuman5196** [comment] 2023-06-12 16:53
@adelekennedy could you check on this?https://github.com/Expensify/App/issues/20266#issuecomment-1581305114

**Comment by mvtglobally** [comment] 2023-06-13 19:03
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2023-06-13 21:22
ai - coming back to this late. I just tried to reproduce and I'm seeing the task updates in real time. I think we can close this due to the upstream fix
<img width="1128" alt="Screenshot 2023-06-13 at 2 21 02 PM" src="https://github.com/Expensify/App/assets/60450566/dbf0d9a3-aedf-46c8-be8c-668186cf3dea">

**Closed by adelekennedy** 2023-06-13 21:22 UTC
Labels: External, Daily, Help Wanted, Bug
