### ISSUE TITLE
[held #41246] mWeb - Room - Leaving room shows hhm not here & app back button not responsive

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45097] opened 2024-07-09 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4705047
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate using the public room link -https://staging.new.expensify.com/r/2091104345528462
2. Login using google
3. Note sign in button shown briefly after login
4. Tap header -- leave room
5. Note hhm not page is shown
6. Tap app back button
7. Note back button is not responsive

## Expected Result:
Sign in button must not be shown briefly after logged in and leaving room user must be directed to concierge page and app's back button must be responsive

## Actual Result:
Sign in button shown briefly after logged in and leaving room user is directed to hhm not here page and app's back button is not responsive

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8ccdbcb0-1e89-48eb-a270-8b412b7b67e1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-07-09 16:03
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alitoshmatov** [comment] 2024-07-09 21:15
I think this is related to https://github.com/Expensify/App/issues/41246, where reports are not loading when signing in with google

**Comment by joekaufmanexpensify** [comment] 2024-07-09 21:17
@alitoshmatov Got it. Do you think it's a dupe of that one?

**Comment by joekaufmanexpensify** [comment] 2024-07-10 21:55
@alitoshmatov bump on the above Q when you have a sec

**Comment by joekaufmanexpensify** [comment] 2024-07-12 14:45
[Bumped in Slack ](https://expensify.slack.com/archives/C02NK2DQWUX/p1720795544860159)

**Comment by joekaufmanexpensify** [comment] 2024-07-15 14:35
Still waiting for confirmation. I think it's likely we will end up closing this one though.

**Comment by alitoshmatov** [comment] 2024-07-16 12:08
@joekaufmanexpensify That's likely caused by the same issue, though I couldn't find exact root cause yet. I suggest we hold this one and see if https://github.com/Expensify/App/issues/41246 solves it

**Comment by joekaufmanexpensify** [comment] 2024-07-16 14:53
Sounds good! Going to assign you here as C+ as you have context on the other one, in case we do need to end up fixing anything after that one is closed.

**Comment by joekaufmanexpensify** [comment] 2024-07-16 14:54
Putting on hold for https://github.com/Expensify/App/issues/41246

**Comment by joekaufmanexpensify** [comment] 2024-07-23 13:27
Based on [this](https://expensify.slack.com/archives/C066HJM2CAZ/p1721684527960509?thread_ts=1721683272.509669&cid=C066HJM2CAZ), it sounds like we don't want to be prioritizing chat issues that aren't already in progress, so closing this for now.

**Closed by joekaufmanexpensify** 2024-07-23 13:27 UTC
Labels: Monthly, Bug
