### ISSUE TITLE
[$250] Android/IOS - Blank screen and an error displays while trying to delete a workspace right after creating it @adeel0202

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11524] opened 2022-10-02 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Create a new workspace
3. Delete the workspace (without going back)
4. When workspace deletes, on Android, press the device's back button. On iOS, swipe from left to right to go back
5. Observe there is a blank screen. Also, on iOS workspace deletes, but on Android, workspace doesn't delete and there is an error too

## Expected Result:
Workspace deletes without blank screen and error

## Actual Result:
There is a blank screen and  on android, the workspace doesn't delete and there is an error too

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.11.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/193471236-cd023644-1211-4f01-9091-81eb597e16ee.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202

**Slack conversation:**  https://expensify.slack.com/archives/C01GTK53T8Q/p1664537582980719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![IMG_4987](https://user-images.githubusercontent.com/93399543/193471239-d4c217ee-4f5f-47fa-a262-b9510bb1e371.png)

https://user-images.githubusercontent.com/93399543/193471240-db607f07-eebb-4b13-ba7a-5ee2d09a7b1d.mp4

https://user-images.githubusercontent.com/93399543/193471245-55d69ffb-d8f6-4f81-b2db-36efa4cf0e9b.mov

**Comment by joekaufmanexpensify** [comment] 2022-10-03 15:40
Seems like related bugs on both iOS and android. 

I see this bug occurred on iOS v1.2.9-0. I just tried to reproduce on v1.2.10-1 and am not seeing this error. 

I don't have an android device so asking for help reproducing!

**Comment by joekaufmanexpensify** [comment] 2022-10-03 15:49
[Posted](https://expensify.slack.com/archives/C03TQ48KC/p1664812112477419) for help reproducing.

**Comment by adeel0202** [comment] 2022-10-03 16:04
@joekaufmanexpensify I'm able to reproduce on the latest versions of both platforms. And apologies if the reproduction steps were not clear enough.

**Comment by twisterdotcom** [comment] 2022-10-04 14:12
This happened on my pixel 6a, on v1.2.10-1, account: twisterdotcom@gmail.com

https://user-images.githubusercontent.com/9133401/193842325-72473207-b544-4ba0-ae22-f2dbd1b78673.mp4

**Comment by joekaufmanexpensify** [comment] 2022-10-04 14:37
awesome, thanks @twisterdotcom! So this can be reproduced on both iOS and android using [these steps](https://github.com/Expensify/App/issues/11524#issuecomment-1265666971).

**Comment by roryabraham** [comment] 2022-10-06 22:50
Putting this on HOLD for https://github.com/Expensify/Expensify/issues/221853

**Comment by roryabraham** [comment] 2022-10-06 22:50
Removed `Help Wanted` for now

**Comment by roryabraham** [comment] 2022-10-12 18:06
The internal issue has been made public, this issue is on HOLD for https://github.com/Expensify/App/issues/11768

**Comment by roryabraham** [comment] 2022-10-18 03:27
Still on HOLD, making this a weekly for now.

**Comment by zanyrenney** [comment] 2022-10-26 08:50
Not overdue, on hold.

**Comment by JmillsExpensify** [comment] 2022-11-03 18:35
Snagging this since I'm on the tracking issue.

**Comment by roryabraham** [comment] 2022-11-14 21:19
Still on HOLD

**Comment by JmillsExpensify** [comment] 2022-11-17 04:03
Thanks for clearing. To add additional context, we're still very early in the planning process, with the next step a design doc. Expect the hold to last for a bit.

**Comment by JmillsExpensify** [comment] 2022-11-22 07:06
Still on hold as we go through the process.

**Comment by JmillsExpensify** [comment] 2022-11-27 06:28
On hold per the larger react navigation initiative.

**Comment by JmillsExpensify** [comment] 2022-12-05 13:39
Still on hold for the larger navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-12 12:33
Still on hold for the navigation re-write.

**Comment by JmillsExpensify** [comment] 2022-12-19 01:41
Held on navigation revamp.

**Comment by JmillsExpensify** [comment] 2022-12-27 20:04
Switching out weekly for monthly given that the project is large and we have no defined ETA.

**Comment by JmillsExpensify** [comment] 2023-01-11 05:40
Still on hold for the navigation project.

**Comment by roryabraham** [comment] 2023-02-13 22:06
Still on HOLD

**Comment by roryabraham** [comment] 2023-03-20 19:41
Still on HOLD for react-navigation reboot

**Comment by JmillsExpensify** [comment] 2023-04-24 15:42
Still on hold for navigation.

**Comment by JmillsExpensify** [comment] 2023-05-31 02:07
Same as above.

**Comment by roryabraham** [comment] 2023-06-29 23:12
Looks like this can come off HOLD

**Comment by roryabraham** [comment] 2023-06-29 23:13
Requested retest by Applause: https://expensify.slack.com/archives/C9YU7BX5M/p1688080407073189?thread_ts=1688079598.241329&cid=C9YU7BX5M

**Comment by isagoico** [comment] 2023-07-03 16:19
Issue not reproducible in Android and IOS 🎉 . Videos below

https://github.com/Expensify/App/assets/44479856/a8d8fc3f-32d7-41aa-98a9-6943b77af6b2

https://github.com/Expensify/App/assets/44479856/f9a1cc28-ed83-4a90-be2a-8d43dddebea0

**Comment by roryabraham** [comment] 2023-07-06 16:47
Thanks @isagoico! 🎉

**Comment by roryabraham** [comment] 2023-07-08 00:24
My mistake @adeel0202. @JmillsExpensify Can we pay the reporting bonus here then close this out?

**Comment by roryabraham** [comment] 2023-07-13 15:12
@JmillsExpensify bump

**Comment by roryabraham** [comment] 2023-08-15 02:04
@JmillsExpensify seems like this one flew under the radar because it had a `HOLD` and was a monthly. Removing HOLD and making daily so we can pay the reporting bonus and close this out.

**Comment by JmillsExpensify** [comment] 2023-08-15 05:04
Apologies, and yeah sorry about that. Please reach out to me via NewDot if I miss these in the future.

**Comment by JmillsExpensify** [comment] 2023-08-15 05:08
@adeel0202 just sent over a contract for this Upwork job: https://www.upwork.com/jobs/~01ccdeb131a3a7622d. Once you're paid out then we can close.

**Comment by JmillsExpensify** [comment] 2023-08-15 05:57
All paid out. Closing.

**Closed by JmillsExpensify** 2023-08-15 05:57 UTC
Labels: External, Engineering, Daily, Bug
