### ISSUE TITLE
IOS - Input is not auto focused the first time private note is opened

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53043] opened 2024-11-24 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52693
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2156@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Sign up with a new account
2. Start a chat with a new account
3. Tap on header > Private note
4. Wait for a while, Go back and Open private note agains

## Expected Result:
Input gets auto focused on step 3

## Actual Result:
Input doesn't get auto focused the first time opening private notes

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/00673cf6-55aa-49c5-b6b5-71a4371558ca
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment] 2024-11-25 06:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Input is not auto focused the first time private note is opened

### What is the root cause of that problem?

The `focus()` method for the `TextInput` inside the `InputWrapper` component does not work as expected when called immediately in in the `ref` callback. This issue occurs primarily on iOS, where the reference ( `privateNotesInput.current`) is not yet assigned at the time of attempting to invoke the focus() method.

https://github.com/Expensify/App/blob/021c725441d73c2d3fd8f302f38b34ed9ef353da/src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L161

https://github.com/Expensify/App/blob/82b76c1a36cf1a01b00c14510a5812a591e7f2fd/src/libs/updateMultilineInputRange/index.ios.ts#L23

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we must ensure that the render function has completed, React has assigned the ref, and we delay calling focus. Some thing like that:

We can use `InteractionManager` or `requestAnimationFrame` to ensure that `input.focus()` is called after all ongoing interactions, once the input is rendered and its layout is stabilized.

```diff
//src/libs/updateMultilineInputRange/index.ios.ts#L22
    if (shouldAutoFocus) {
+        InteractionManager.runAfterInteractions(() => {
+            requestAnimationFrame(() => {
                input.focus();
+            });
+        });
    }
```

## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:53043-test-branch?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/9ca60e75-d6a4-4670-9c04-f320a3038bae

</details>

### What alternative solutions did you explore? (Optional)
If we only want this to be specific to the private notes edit page, then it would look like this:
```diff
//src/pages/PrivateNotes/PrivateNotesEditPage.tsx#L161
                    <InputWrapper
                        ...
                        ref={(el: AnimatedTextInputRef) => {
                            if (!el) {
                                return;
                            }
                            if (!privateNotesInput.current) {
-                                updateMultilineInputRange(el);
+                                InteractionManager.runAfterInteractions(() => {
+                                    requestAnimationFrame(() => {
                                        updateMultilineInputRange(el);
+                                    });
+                                });
                            }
                            privateNotesInput.current = el;
                        }}
                        isMarkdownEnabled
                    />
```

**Comment by trjExpensify** [comment] 2024-11-26 16:24
This is a feature that pretty much nobody uses or will, it's mainly an internal function. I'm closing for #focus.

**Closed by trjExpensify** 2024-11-26 16:24 UTC
Labels: Daily, Bug
