### ISSUE TITLE
[HOLD for payment 2024-03-07] [HOLD][$500] [MEDIUM] Tags: All tags are revealed when searching for hidden tag and clearing the search field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37335] opened 2024-02-27 18:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has more than 500 tags.
1. Go to workspace chat.
2. Open money request page.
3. Proceed to confirmation page.
4. Click Show more > Tag.
5. Search for a term that is originally hidden behind "Show more" button.
(If there are 700 tags, the last 200 will be hidden behind "Show more". In this case, we can search for the 700th tag.)
6. Clear the search field.
7. Scroll down.

## Expected Result:
Only the first 500 tags will appear and the remaining will be hidden with "Show more" button.

## Actual Result:
All the tags are revealed and there is no "Show more" button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/add3e82b-e325-41c4-a715-e3711946f144

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171a76cd580844a9b</li>
        <li>Upwork Job ID: 1762547976110538752</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 18:39
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by NikkiWines** [comment] 2024-02-27 20:15
Looks like this is a regression from https://github.com/Expensify/App/pull/31606, which has several other regressions tied to it as well. cc: @Piotrfj since it looks like you're handling the regressions that arose from that PR

**Comment by dragnoir** [comment] 2024-02-28 14:57
@NikkiWines ther's an ongoing refactor and a cleanup for the BaseOptionsSelector  https://github.com/Expensify/App/pull/37353 , I think this should be onhold for now

**Comment by roryabraham** [comment] 2024-02-28 21:41
ended up closing https://github.com/Expensify/App/pull/37353 in favor of the revert of https://github.com/Expensify/App/pull/31606. I'll closely review the 2nd attempt to migrate this component in hopes that most or all of the simplifications from https://github.com/Expensify/App/pull/37353 make it into the migration round 2.

**Comment by Piotrfj** [comment] 2024-02-29 13:00
Update: re-refactoring is ready to be tested, it fixes all the regression issues I was aware of. Please test it (especially the tags, because I could not yet replicate the scenario on my site).
The fix is based on the @roryabraham solution, so special thanks for him!
Link to PR: https://github.com/Expensify/App/pull/37494

**Comment by greg-schroeder** [comment] 2024-03-02 00:03
Okay @ishpaul777 you were assigned on the other issue for payment i believe (https://github.com/Expensify/App/issues/37256) so I don't think this one actually requires payment based on what happened, as @fedirjh didn't actually do the review on the linked PR

**Comment by greg-schroeder** [comment] 2024-03-02 00:03
We may be able to close in that case

**Comment by trjExpensify** [comment] 2024-03-05 20:00
Let's close it then! :)

**Closed by trjExpensify** 2024-03-05 20:00 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment
