### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] Task – When task name is changed offline, the task's chat report in the LHN doesn't update after going back online

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40121] opened 2024-04-11 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0

**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4486193
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Go to any chat
4. Create a task with assignee
5. Go Offline and edit task name
6. Go back Online and observe task name in a DM chat in LHN (not task details)

## Expected Result:
Offline edited task name changed without delay in DM chat LHN

## Actual Result:
Offline edited task name changed with delay in DM chat LHN when go Online. Task name in LHN must be changed when Offline

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/f4eeab0d-a315-4154-b3db-41367119a06a

[Bug6445047_1712787643540!Log.txt.txt](https://github.com/Expensify/App/files/14947966/Bug6445047_1712787643540.Log.txt.txt)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018db3c535ab60f25e</li>
        <li>Upwork Job ID: 1779911172994191360</li>
        <li>Last Price Increase: 2024-04-15</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-04-11 15:09
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by bernhardoj** [comment] 2024-04-12 04:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we update the task title, the LHN of the chat report doesn't update with the new title.

### What is the root cause of that problem?
The task title in the LHN last message takes the title from `getTaskTitle`.
https://github.com/Expensify/App/blob/bbc676100f7309a4495307885d0c6823b2825d47/src/libs/TaskUtils.ts#L40-L52

`getTaskTitle` will first get the title from the task report `reportName` and fallback to the task action `childReportName`. When we edit the task, we already optimistically update the task report `reportName`.
https://github.com/Expensify/App/blob/bbc676100f7309a4495307885d0c6823b2825d47/src/libs/actions/Task.ts#L447-L450

However, `getTaskTitle` never use `reportName`. That is because the task report here is always an empty object because we access it incorrectly
https://github.com/Expensify/App/blob/bbc676100f7309a4495307885d0c6823b2825d47/src/libs/TaskUtils.ts#L40-L41

`allReports` contains the collection of the report which is keyed by `report_{id}` but we try to access it with `{id}`. This started to happen after https://github.com/Expensify/App/pull/38464. Previously, `allReports` is keyed by `{id}`.
<img width="1099" alt="image" src="https://github.com/Expensify/App/assets/50919443/43395145-63be-46e8-9f15-ba7badbd3f64">

### What changes do you think we should make in order to solve the problem?

Access the task report by `report_{id}`.
```
const taskReport = allReports?.[`${ONYXKEYS.COLLECTION.REPORT}${taskReportID}`] ?? {};
```

### What alternative solutions did you explore? (Optional)
Use the old approach by keyed it with `{id}` and remove `waitForCollectionCallback`.
https://github.com/Expensify/App/blob/bbc676100f7309a4495307885d0c6823b2825d47/src/libs/TaskUtils.ts#L10-L17

**Comment by lakchote** [comment] 2024-04-17 13:26
@bernhardoj's proposal LGTM.

**Comment by bernhardoj** [comment] 2024-04-17 14:01
PR is ready

cc: @getusha

**Comment by sakluger** [comment] 2024-05-08 18:19
I paid @bernhardoj's contract. @bernhardoj could you please complete the BZ checklist?

**Comment by bernhardoj** [comment] 2024-05-10 03:04
@sakluger I think @getusha should be the one that complete the checklist

**Comment by sakluger** [comment] 2024-05-10 03:56
@bernhardoj you're right, my bad! @getusha please complete the checklist when you have a moment.

**Comment by getusha** [comment] 2024-05-10 04:26
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/38464
- [x] [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/38464/files#r1596233138
- [x] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- [x] [@getusha] Determine if we should create a regression test for this bug. No, it looks like a minor bug
- [x] [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/a

**Comment by sakluger** [comment] 2024-05-10 15:28
Thanks! All paid out.

**Closed by sakluger** 2024-05-10 15:28 UTC
Labels: External, Daily, Awaiting Payment, Bug
