### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] Cursor position is stuck after emoji on copy pasting text with emoji text in it

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29795] opened 2023-10-17 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697546821680559
 
## Action Performed:
1. Open the app
2. Open any report
3. Copy text from any source which has emoji text in middle and not in end eg: Hello How are you :joy test  (colon after joy)
4. Paste in composer and observe that cursor is stuck after emoji instead of displaying it in the end
## Expected Result: 
App should display cursor at the end of text when we paste any text
## Actual Result: 
App displays cursor after emoji even when we paste text with emoji text in middle and not in end
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/c72ff78c-e03e-47bd-9aaf-1062406a58da

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/2fbfca1f-2995-4657-a401-56efa1a473c4

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/7b67d659-4471-4bc2-98f9-c269971ba0e4

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/27262098-a874-45c3-972d-e837048a034b

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/ec0cb89c-6003-456d-882a-6bf7c471439e

https://github.com/Expensify/App/assets/38435837/cd13a4ac-293c-42fe-b395-ef5b07ec5e75

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/10818487-d001-4157-b5a4-0d8cd500cb25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d23deb324334bf75</li>
        <li>Upwork Job ID: 1714318176195219456</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 27651044</li>
<li>barros001 | Contributor | 27651045</li>
<li>dhanashree-sawant | Reporter | 27651046</li>
</ul></li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-10-18 13:53
@Ollyws any thoughts on the proposals above? TIA!

**Comment by CortneyOfstad** [comment] 2023-10-18 20:20
I am heading OoO until Oct. 25 so reassigning BZ to keep an eye on this while I am gone 👍

**Comment by johncschuster** [comment] 2023-10-20 10:49
@Ollyws, what are your thoughts on the proposals above?

**Comment by johncschuster** [comment] 2023-10-25 14:05
[Posted in Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1698242725755719)

**Comment by barros001** [comment] 2023-10-25 15:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When pasting a text that contains an emoji into the composer, the cursor is positioned after the last emoji and not at the end of the text just pasted.

### What is the root cause of that problem?

src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js:230
```js
                const remainder = ComposerUtils.getCommonSuffixLength(commentValue, newComment);
                setSelection({
                    start: newComment.length - remainder,
                    end: newComment.length - remainder,
                });
```

The first parameter passed into `getCommonSuffixLength` is wrong. The first parameter should be the original value of the composer _before_ the new text had been pasted into it. `commentValue` is the current text after pasting but before converting any Emojis.

### What changes do you think we should make in order to solve the problem?

Replacing `commentValue` with `commentRef.current` resolves the issue as remainder is correctly calculated.

I also found another potential small problem with how Emojis are converted. The code will add a space after the last Emoji but only at the end of the message. This doesn't seem to be the case. Pasting the following text will add a space between the last emoji and the last word of the message, which is not what's intended:

```
Emoji :joy: test
```

That's because in EmojiUtils.js the code is only checking if it's the last Emoji and adding the space. It does not check if its at the end of the message:

src/libs/EmojiUtils.js:370
```js
            // If this is the last emoji in the message and it's the end of the message so far,
            // add a space after it so the user can keep typing easily.
            if (i === emojiData.length - 1) {
                emojiReplacement += ' ';
            }
```

We should add one more check if it's at the end of the message, such as:

```
                // Ensure emoji is at the end of the message before adding space
                if (newText.indexOf(emojiData[i]) + emojiData[i].length === newText.length) {
                    emojiReplacement += ' ';
                }
```



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by alitoshmatov** [comment] 2023-10-25 16:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Cursor position is stuck after emoji on copy pasting text with emoji text in it
### What is the root cause of that problem?
The problem is that we are always updating selection when text is replaced with emoji
https://github.com/Expensify/App/blob/5903e5e866d5ee2af45a4e69a1e03dd7c3b22d1e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L230-L236

The assumption here was that emoji is only placed right after user types emoji name. But as we can see this not a valid assumption, pasting the code is also triggering this action but user was not typing emoji name itself

### What changes do you think we should make in order to solve the problem?
I think we can update our logic so that **we only update cursor position when cursor was around(or in between) of replaced emoji name**.

For that we should get cursor position when emoji name was typed, and compare it with emoji name's start and finish positions, like so:
```
const lastCursorPosition = selection.end;
const emojiNameStart = commentValue.length - remainder - newEmojis[0].name.length;
const emojiNameFinish = commentValue.length - remainder;

if(lastCursorPosition>=emojiNameStart && lastCursorPosition<=emojiNameFinish){
    setSelection({
        start: newComment.length - remainder,
        end: newComment.length - remainder,
    });
}
```

This way we can identify if emoji was indeed typed the way we expect it to be, if not we do not update cursor position.

### What alternative solutions did you explore? (Optional)

**Comment by barros001** [comment] 2023-10-26 14:22
@Ollyws Got it. I experimented a little bit more and I'm convinced the first parameter simply cannot be `commentValue`, it will always return the wrong value. Adding if/else logic will make it too complex and fragile, increasing the odds of it breaking down the road under different scenarios. 

After playing a little bit, this seemed to resolve both issues (current issue and not re-creating https://github.com/Expensify/App/issues/27672).

```js
const remainder = ComposerUtils.getCommonSuffixLength(commentRef.current, commentValue);
```

First parameter always have to be the previous string, otherwise it will mistakenly think that part of the suffix was already there while it wasn't. Example:

You paste: `Emoji :joy: test`. Then it will be converted to `Emoji 😂 test`. Finally, `ComposerUtils.getCommonSuffixLength` will try to find, from right to left, where the strings differ. ` test` will still match, so the first divergence is `:joy:`. It will trick it into placing the cursor after the emoji because it thinks that's where we pasted our text, which is wrong. That's why comparing current value to current value with emojis converted is wrong.

Now, as for https://github.com/Expensify/App/issues/27672 I understand the problem. If you paste the same emojis over and over again, we'll have a similar issue. For example:

```
[Log] {current: "", commentValue: ":joy:", newComment: "😂 ", remainder: 0, length: 3, …}
[Log] {current: "😂 ", commentValue: "😂 :joy:", newComment: "😂 😂 ", remainder: 0, length: 6, …}
[Log] {current: "😂 😂 ", commentValue: "😂 😂 :joy:", newComment: "😂 😂 😂 ", remainder: 0, length: 9, …}
```

This is what happens after passing `:joy:` 3 times in a row. If you compare `newComment` against `current`, it will work fine the first time, but then the second time it's impossible to tell which 😂 was pasted when you compare 😂 to 😂😂. So cursor gets stuck.

Now, if you compare `current` against `commentValue`, that works because it will be able to tell what changed when you compare `😂` to `😂:joy:`, or `😂` against `:joy:😂`. The match will work. I tried a few different scenario and it seems to work perfectly.

Let me know if you find any flaws with this approach. Also let me know your thoughts on the change I proposed when adding an extra space after pasting a text with emojis:

```js
            // If this is the last emoji in the message and it's the end of the message so far,
            // add a space after it so the user can keep typing easily.
            if (i === emojiData.length - 1) {
                // Ensure emoji is at the end of the message before adding space
                if (newText.indexOf(emojiData[i]) + emojiData[i].length === newText.length) { // <-- ADDED THIS IF
                    emojiReplacement += ' ';
                }
            }
```

**Comment by barros001** [comment] 2023-10-26 14:50
@Ollyws apologize for commenting and then deleting my comment. I quickly found a flaw with my approach.

The more I toyed with this, the more I convinced myself that there's something fundamentally wrong with the original approach. Trying to find where two strings diverge by comparing one against the other is just hard, if not impossible, due to numerous edge cases. 

Here's one example:

`Emoji 😹 test` vs `Emoji 😹: testEmoji 😹 test`. Can you really tell me what I pasted? You could say I did paste `Emoji 😹 test` but you could also argue that I pasted ` testEmoji 😹`. 

You can't really tell for sure. There's has to be a better way to handle this without adding too much logic around it.

This is what I found out. `selection` holds the original position of the cursor _before_ the pasted text. Knowing that, it's easy to determine where the new position should be. `selection.end + (newString.length - previousString.length)`. I'm using end here because if you paste on top of a selection, we want to use the farthest cursor location when doing this calculation. 

This is the change I tested with (left the remainder portion commented out to illustrate the change):

```js
            if (commentValue !== newComment) {
                // const remainder = ComposerUtils.getCommonSuffixLength(commentRef.current, commentValue);
                setSelection({
                    start: selection.end + (newComment.length - commentRef.current.length),
                    end: selection.end + (newComment.length - commentRef.current.length),
                });
            }
```

This approach doesn't need to figure what changed, all it cares is that cursor was positioned at position X, there are now Y more characters in the string, so we'll move cursor to X+Y.

Let me know your thoughts on this.

**Comment by barros001** [comment] 2023-10-30 11:25
@Ollyws so many edge cases, this is a tough one. I thought of something else though, I’ll try it out soon and update the proposal if it works.

**Comment by CortneyOfstad** [comment] 2023-10-31 16:13
@Ollyws thoughts on the proposal updates above ^^^ TIA!

**Comment by barros001** [comment] 2023-11-06 02:24
@Ollyws can you provide more details as to why you think it would conflict with #30412? I just merged master into a branch I have locally, resolved a minor conflict (git conflict), and everything still seems to be working just fine. The changes implemented on the mentioned PR still works, so do the changes implemented to fix the current issue.

Btw, I found a couple of potential issues with the PR you mentioned, I'll comment on the issue related to it.

**Comment by CortneyOfstad** [comment] 2023-11-10 18:40
@Ollyws do you have an updates? Thanks!

**Comment by barros001** [comment] 2023-11-13 15:47
@Ollyws thanks for reviewing my proposal. 

> There` is one small issue where if you paste innertext :joy: innertext between two peices of text, the cursor will remain after the emoji rather than the second innertext, but that can be ironed out in the PR and I think we have enough here to move things forward.

I just tested this scenario and it works as expected, see video below. Maybe this got fixed along the way as I was working on the proposal. But as you said, any issues that arises we'll iron out in the PR.

https://github.com/Expensify/App/assets/765936/ce7cb60c-4c81-45e3-a414-2204cbf1f059

**Comment by CortneyOfstad** [comment] 2023-12-01 14:01
@dhanashree-sawant, @Ollyws @barros001 — all have been paid via Upwork and no regression test required, so closing! Thanks all!

**Closed by CortneyOfstad** 2023-12-01 14:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
