### ISSUE TITLE
[HOLD for payment 2023-06-01] Android - Threads -  Date is not truncated and very close to screen border 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#19142] opened 2023-05-17 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to a group conversation where a 99+ thread has taken place

## Expected Result:
Conversation content should not be almost in contact with screen border. If the screen is small, the content should be truncated 

## Actual Result:
Date of the latest message in thread is in contact with the screen border

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.15-5

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Unknown

**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![image](https://github.com/Expensify/App/assets/44479856/3cdaae7e-5f9d-426a-9b92-cd0a6cf5d5b2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:** N/A

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

Found while executing QA for https://github.com/Expensify/App/pull/18876 - CC @grgia 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188f09b53362835dd</li>
        <li>Upwork Job ID: 1659133757113516032</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-05-17 21:13
@grgia I have a vague memory of you raising a discussion for this. Is this something that you're already working on addressing?

**Comment by grgia** [comment] 2023-05-18 09:58
@Milos213 Thank you for your proposal! However, we intended to take this issue Internally as I already knew the solution and this bug was caused by my PR.

That said, we have tons of issues that are actively accepting proposals. You can always look out for the `Help Wanted` label to indicate that we are currently accepting proposals. You can find open jobs [here](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+NOT+Hold+in%3Atitle+sort%3Acreated-desc+label%3ABug), thanks!

**Comment by s77rt** [comment] 2023-05-25 09:26
- The PR that introduced the bug has been identified: This existed since day one https://github.com/Expensify/App/pull/18274
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18274#issuecomment-1562554698
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1685006794560419
- Determine if we should create a regression test for this bug: No

**Comment by grgia** [comment] 2023-06-01 09:52
@puneetlath I reassigned you as you were selected by puller bear originally. Would you mind helping out with the $1000 [C+ review ](https://github.com/Expensify/App/pull/19182) payment for @s77rt ?

**Comment by s77rt** [comment] 2023-06-02 16:32
@puneetlath Accepted!

**Comment by puneetlath** [comment] 2023-06-02 17:38
Paid!

**Closed by puneetlath** 2023-06-02 17:38 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
