### ISSUE TITLE
[$500]  Request Money - Unable to continue to the next page after a reload

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31721] opened 2023-11-22 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Request Money
2. Switch to manual
3. Enter the amount and click on next
4. Choose a user
5. Go to more (the three dots) and Add a Receipt
6. Go back to the user list by clicking the back button
7. Reload page
8. Try choosing a user. Notice that the page keeps returning to the list page

## Expected Result:
Choosing a user takes you to the next page

## Actual Result:
After choosing a user, the page keeps returning back to the list page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/898d9efb-bfe7-45ba-a88b-0a31a8035e7c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193941e6234a37574</li>
        <li>Upwork Job ID: 1727358733943631872</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-22 16:14
This issue is mentioned [in here](https://github.com/Expensify/App/issues/30884#issuecomment-1793453231) with the fix for it. I think we should close this one

**Comment by s-alves10** [comment] 2023-11-22 16:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After adding a receipt to the manual request, page refresh causes manual request to be stuck

### What is the root cause of that problem?

When we adding a receipt to the manual request, we create blob URL and set it to the iou
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/ReceiptSelector/index.js#L135-L136
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/ReceiptSelector/index.js#L154-L155

But this object URL is only valid for the current session and will be revoked once the page is refreshed. So when navigating to the confirmation page, file would be null and it'll be redirected to the manual request page or previous page.
https://github.com/Expensify/App/blob/7bd51eba84f6708409dfd6e6886bf968eff3358f/src/pages/iou/steps/MoneyRequestConfirmPage.js#L106-L109

This is the root cause

### What changes do you think we should make in order to solve the problem?

I don't think we need to go back to the manual request page when object URL is not valid.
I suggest to reset the receipt in this case

Update the above code to
```
        FileUtils.readFileAsync(props.iou.receiptPath, props.iou.receiptFilename).then((file) => {
            if (!file) {
                IOU.setMoneyRequestReceipt('', '');
            } else {
```


<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/a530ef22-a62e-4c72-95b2-dd63bb0ba697


</details>

### What alternative solutions did you explore? (Optional)

**Comment by krflol** [comment] 2023-11-22 20:48
(FROM UPWORK)
Proposal
Technical Explanation:
The blob is being orphaned making the state representation no longer valid.
Proposed solution:
Convert the blob to a URI/URL

```
convertBlobToDataURL(fileBlob, (dataURL) => {
    // Store dataURL in the state
});
```

```
// After page reload, recreate the blob if needed
const blob = dataURLToBlob(storedDataURL);
```

This should have a streamlined user experience, where the selected file is applied after reload. This may fix the issue in other places of the codebase as well.

**Comment by krflol** [comment] 2023-11-22 20:54
Contributor details
Your Expensify account email: keenanfinkelstein@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fe1ab70d555a8b4c

**Comment by zanyrenney** [comment] 2023-11-27 15:46
Agree with the comment here - https://github.com/Expensify/App/issues/31721#issuecomment-1823071263

Closing in favour of the initial issue.

**Closed by zanyrenney** 2023-11-27 15:46 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
