### ISSUE TITLE
[$250] Workspace - Single category and tag isn't auto selected when requesting money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40591] opened 2024-04-19 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/40217
## Action Performed:
1. Log in with a new Gmail account
2. Create a workspace
3. Edit categories and tags so you only have one of each
4. Make tags and categories required
5. Navigate to FAB - Submit expense - Manual
6. Select the workspace chat
7. Tap on the "Show more" button

## Expected Result:
Category and tag fields should auto select the single entry

## Actual Result:
Single category and tag isn't auto selected when requesting money

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4393eec4-0e65-44b4-ace6-3a2b22552b60

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01342dc85ef896c8e8</li>
        <li>Upwork Job ID: 1782368096132030464</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
<li>GandalfGwaihir | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-19 16:41
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-19 16:44
We think that this bug might be related to #wave-collect - Release 1

**Comment by shahinyan11** [comment] 2024-04-19 17:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - Single category and tag isn't auto selected when requesting money
### What is the root cause of that problem?
There is an implementation for this
### What changes do you think we should make in order to solve the problem?
Update [this](https://github.com/Expensify/App/blob/2863f6948bff150f58eaeb9b6cddf955cf49c292/src/components/CategoryPicker.tsx#L73) line as below
const selectedOptionKey = useMemo(() =>{
    if(sections?.[0]?.data.length === 1 ){
        return sections?.[0]?.data[0].keyForList
    }
    
    return (sections?.[0]?.data ?? []).filter((category) => category.searchText === selectedCategory)[0]?.keyForList
} , [sections, selectedCategory]);
### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2024-04-20 03:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Single category and tag isn't auto selected when requesting money

### What is the root cause of that problem?

This is a regression caused by https://github.com/Expensify/App/pull/40217 and was suggested in https://github.com/Expensify/App/issues/38744#issuecomment-2049248660.

`iouCategory` and `transactionID` should be included in the category dependencies required because the `iouCategory` will change after the first render.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L515-L523


The tag field does not have this issue because the dependencies are set properly.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L537-L539

This is why I only experienced this with the category field.

I believe the category dependencies should not have the `eslint rule` line like the tag dependencies`.

*Note:* 

I noticed you can empty the tag and category for a brief moment before the backend reverts them.

Hence, I recommend we prohibit the ability to change the tag or category in this situation on the edit pages in the PR.


### What changes do you think we should make in order to solve the problem?


First, add `iouCategory` and `transactionID` as apart dependies. Hence, it should look like the code example below.


```
}, [iouCategory, transactionID, shouldShowCategories, policyCategories, isCategoryRequired]);
```

Finally, remove the `eslint rule` line below because there will be no dependency issues. 

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L522

### What alternative solutions did you explore? (Optional)

Since `iouCategory` is defaulted to an empty string, we can initialize it to the only categories in the `MoneyRequestConfirmationListProps` if the `enabledCategories` is equal to one and categories are required.

**Comment by Tony-MK** [comment] 2024-04-20 03:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Single category and tag isn't auto selected when requesting money

### What is the root cause of that problem?

This is a regression caused by https://github.com/Expensify/App/pull/40217 and was suggested in https://github.com/Expensify/App/issues/38744#issuecomment-2049248660.

`iouCategory` and `transactionID` should be included in the category dependencies required because the `iouCategory` will change after the first render.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L515-L523


The tag field does not have this issue because the dependencies are set properly.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L537-L539

This is why I only experienced this with the category field.

I believe the category dependencies should not have the `eslint rule` line like the tag dependencies`.

### What changes do you think we should make in order to solve the problem?


First, add `iouCategory` and `transactionID` as apart dependencies. 
Hence, it should look like the code example below.

```
}, [iouCategory, transactionID, shouldShowCategories, policyCategories, isCategoryRequired]);
```

Finally, remove the `eslint rule` line below because there will be no dependency issues. 

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L522

### What alternative solutions did you explore? (Optional)

Since `iouCategory` is defaulted to an empty string, we can initialize it to the only categories in the `MoneyRequestConfirmationListProps` if the `enabledCategories` is equal to one and categories are required.

### Note 

I noticed you can empty the tag and category for a brief moment before the backend reverts them.

Hence, I recommend we prohibit the ability to change the tag or category in this situation on the edit pages in the PR.

**Comment by Tony-MK** [comment] 2024-04-20 03:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Single category and tag isn't auto selected when requesting money

### What is the root cause of that problem?

This is a regression caused by https://github.com/Expensify/App/pull/40217 and was suggested in https://github.com/Expensify/App/issues/38744#issuecomment-2049248660.

`iouCategory` and `transactionID` should be included in the category dependencies required because the `iouCategory` will change after the first render.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L515-L523


The tag field does not have this issue because the dependencies are set properly.

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L537-L539

This is why I only experienced this with the category field.

I believe the category dependencies should not have the `eslint rule` line like the tag dependencies`.

### What changes do you think we should make in order to solve the problem?


First, add `iouCategory` and `transactionID` as apart dependencies. 
Hence, it should look like the code example below.

```
}, [iouCategory, transactionID, shouldShowCategories, policyCategories, isCategoryRequired]);
```

Finally, remove the `eslint rule` line below because there will be no dependency issues. 

https://github.com/Expensify/App/blob/1e510b52a5c65a2c812e74feb686debea6e0b040/src/components/MoneyRequestConfirmationList.tsx#L522

### What alternative solutions did you explore? (Optional)

Since `iouCategory` is defaulted to an empty string, we can initialize it to the only categories in the `MoneyRequestConfirmationListProps` if the `enabledCategories` is equal to one and categories are required.

### Note 

I noticed you can empty the tag and category for a brief moment before the backend reverts them.

Hence, I recommend we prohibit the ability to change the tag or category in this situation on the edit pages in the PR.

https://github.com/Expensify/App/assets/22982173/991f05bc-85f2-416c-a63c-3a4ab4fd1a9b

**Comment by Tony-MK** [comment] 2024-04-22 00:44
Hey @Krishna232, the `useEffect` needs the `iouCategory` dependency like the `useEffect` for the tags hook.

**Comment by zanyrenney** [comment] 2024-04-22 11:17
adding external label

**Comment by zanyrenney** [comment] 2024-04-25 10:30
@ahmedGaber93 we have a few proposals now, please review them and let me know which we should go forward with. As this is related to release one this is pretty urgent so if you don't have capacity, please assign yourself and I will assign another C+.

**Comment by ahmedGaber93** [comment] 2024-04-25 10:36
@zanyrenney Reviewing today.

**Comment by ahmedGaber93** [comment] 2024-04-25 20:24
Thanks for the proposal every one!

@Krishna2323 your proposal will work, but it will auto select the single item even if tags/categories isn't set as a required which not match the expected result.

@GandalfGwaihir your RCA is correct, and your fix should work fine, but that's mean `isCategoryRequired` and `isTagListRequired` is under beat `canUseViolations`, I will ask in slack, and you can dig in the code to find why this is still under beta while we can access categories/tags in IOU request and make them required in workspace settings without this beta.

@Tony-MK your RCA is incorrect, if you have beta [`canUseViolations`](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-beta-features) it should work fine without your fix.

**Comment by ahmedGaber93** [comment] 2024-04-25 20:44
Asking in slack to know why [isCategoryRequired](https://github.com/Expensify/App/blob/a7951273ace7a9d1d1cc20df59cb30a9a643812f/src/components/MoneyRequestConfirmationList.tsx#L325) and [isTagListRequired](https://github.com/Expensify/App/blob/c6117097e247a8ca7c51b5d59d9d08a901b75162/src/components/MoneyRequestConfirmationList.tsx#L530) is under beat `canUseViolations`, while we can access categories/tags when create IOU request and can make them required in workspace settings categories/tags without this beta.
If this intended, or it is issue ?

https://expensify.slack.com/archives/C02NK2DQWUX/p1714077357630999

**Comment by ahmedGaber93** [comment] 2024-04-25 20:45
> I misunderstood the issue here, I think auto-selection works fine when we have single tag/category and it is required. Can you pls tell me what I'm missing?

@Krishna2323 if you have beta `canUseViolations` auto select will work fine, if this intended, this will not been issue.

**Comment by zanyrenney** [comment] 2024-04-29 12:28
going to manually assign @dukenv0307 to take a look.

**Comment by ahmedGaber93** [comment] 2024-04-30 06:44
I think we can move forward with @GandalfGwaihir's [proposal](https://github.com/Expensify/App/issues/40591#issuecomment-2067416986) and discuss that with the internal engineer.

Why choosing removing beta `canUseViolations` check from [isCategoryRequired](https://github.com/Expensify/App/blob/a7951273ace7a9d1d1cc20df59cb30a9a643812f/src/components/MoneyRequestConfirmationList.tsx#L325) and [isTagListRequired](https://github.com/Expensify/App/blob/c6117097e247a8ca7c51b5d59d9d08a901b75162/src/components/MoneyRequestConfirmationList.tsx#L530)?
I think using `canUseViolations` here is by mistake and not intentionally for these reasons:
1. `isCategoryRequired` and `isTagListRequired` are used for UI cases only in [autoselect](https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/components/MoneyRequestConfirmationList.tsx#L531-L539) and display [label required](https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/components/MoneyRequestConfirmationList.tsx#L869) and in [isSupplementary](https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/components/MoneyRequestConfirmationList.tsx#L873) which display it under "show more" section, and not used on validation before sending the API in [confirm method](https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/components/MoneyRequestConfirmationList.tsx#L591), and also not affected on `shouldShow` condition.

2. `isCategoryRequired` and `isTagListRequired` will not affect in the final output,  because the user can select category manually instead of `autoselect`, and can expand "show more" manually instead of `isSupplementary`, **the only effect here is `required` label will be displayed, and we don't have validation for required tags/categories before sending the API in [confirm method](https://github.com/Expensify/App/blob/a462d5854359850359f248aaec58ad4bc2c0efcd/src/components/MoneyRequestConfirmationList.tsx#L591), so we may keep `canUseViolations` in `required` label only or add vaidation before send the API.**

3. we can access categories/tags when create IOU request and can make them required in workspace settings categories/tags without this beta.


🎀 👀 🎀 C+ reviewed

**Comment by zanyrenney** [comment] 2024-05-03 16:31
@GandalfGwaihir please let me know how you get on here!

**Comment by ahmedGaber93** [comment] 2024-05-06 14:57
I am not sure if we should have waited for @cristipaval to accept the proposal before move forward with PR, but as the PR is already started, I am going to review the PR, and we can move any discussion there.

**Comment by zanyrenney** [comment] 2024-06-19 10:57
Hey @allgandalf thanks for checking the status, great thing to do :) I was also then at a conference so i appreciate your patience.

**Comment by zanyrenney** [comment] 2024-06-19 11:00
not sure why @dukenv0307 is on the Upwork listingm because the payments should be 

@allgandalf as contributor
@ahmedGaber93 as contributor+

paying out as per these assignments:

<img width="306" alt="2024-06-19_12-00-26" src="https://github.com/Expensify/App/assets/56830058/6b1b9824-4e75-4664-a968-e9149bf985f9">

**Comment by zanyrenney** [comment] 2024-06-19 11:02
paid @ahmedGaber93 $250
paid @allgandalf $250

closing!

**Closed by zanyrenney** 2024-06-19 11:02 UTC
Labels: Reviewing, External, Weekly, Bug
