### ISSUE TITLE
[$500] Settings - Height of the name input field in the Settings page changes upon returning from the Get Assistance page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28723] opened 2023-10-03 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging
2. Navigate to Settings > Workspaces and select any Workspace.
3. Choose "Settings."
4. Click the question mark icon and then go back.
5. Observe that the name input field flickers.

## Expected Result:
The height of the name input field should remain consistent without any flickering

## Actual Result:
The height of the name input field flickers after returning from the Get Assistance page

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8137cb68-1157-4bf9-a3ae-6c5c7322507d

https://github.com/Expensify/App/assets/93399543/202deeb5-e5e5-4c90-9945-75f94d4e040e

https://github.com/Expensify/App/assets/93399543/d2f7c94a-88c1-4cb0-a2ad-3af38fa79d65

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695501792775439

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018dd0d2c305a6b136</li>
        <li>Upwork Job ID: 1709204008133660672</li>
        <li>Last Price Increase: 2023-10-17</li>
    </ul>
</details>

**Comment by Rosh008** [comment] 2023-10-03 14:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Height of the name input field changes, when returning to the field containg the text input.

### What is the root cause of that problem?
The text input field is getting _default prop_ value props, and switching screens it's causing the field to re-render, due to which a slight delay is caused between getting the props and populating the textfield. Due to which the height of the text input changes. 

### What changes do you think we should make in order to solve the problem?

I propose to add a `autoGrowHeight` field to the text input which will fix the above issue.

https://github.com/Expensify/App/assets/55692562/d1084714-d3e0-4b50-a19c-0950f44e1f60


### What alternative solutions did you explore? (Optional)

**Comment by Rosh008** [comment] 2023-10-03 14:42
Contributor details
Your Expensify account email: roshanwazare@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01df188f0ecefae56c

**Comment by eVoloshchak** [comment] 2023-10-05 10:33
@Rosh008's [proposal](https://github.com/Expensify/App/issues/28723#issuecomment-1745120612) looks good to me!
> Autogrow input container height based on the entered text

This is the exact intended usage of `autoGrowHeight` prop

🎀👀🎀 C+ reviewed!

**Comment by tgolen** [comment] 2023-10-05 16:04
Hm, I'm not a very big fan of that solution, though I agree it would fix the problem. I think it only fixes a symptom and not the root cause. For me, the root cause is that `onLayout()` is being triggered when the view is hidden. If a view is hidden, there should be no reason to trigger onlayout (or anything that would visually change the render).

I think a better solution would be to do something to prevent that from being triggered (or maybe add a flag so that `onLayout` knows that the view has been hidden and can have an early return).

What do you think about incorporating something more like the above into your solution @Rosh008 ?

**Comment by Rosh008** [comment] 2023-10-05 16:54
@tgolen Then we can check  for `layout.height` in onLayout if it's invisible that is 0 we will simply return,  that fixes the problem.

**Comment by tgolen** [comment] 2023-10-05 17:24
Is it possible at all the prevent `onLayout` from being called when it's hidden?

**Comment by Rosh008** [comment] 2023-10-05 17:57
I don't think we can suppress the callback from getting fired.

**Comment by tgolen** [comment] 2023-10-05 18:02
OK, thanks! I have a hunch that there are better and less-hacky solutions, so for now, I'm going to hold off on accepting the current proposal to see if we can get some more ideas for this. If in the end, your proposal is still the best, then we will go with it.

**Comment by tgolen** [comment] 2023-10-06 13:59
I just realized I made a mistake with my previous comments. I missed the fact that there were two proposals and I was actually responding to the `layout.height` proposal instead of the `autoGrowHeight` proposal, and then I got you both mixed up. I really apologize for that!

@tienifr if you go through my previous comments, it'll probably be more clear knowing that I am in fact responding to your proposal for `layout.height` and not the C+ accepted proposal from @Rosh008. 

Now, to address the C+ accepted proposal for `autoGrowHeight`, I also don't feel like it is acceptable currently. My main concerns (for both of these proposals really) are:

- It feels like we really haven't gotten to the root of the problem yet, let's dig deeper. _Why_ is the layout not being set properly when coming back to this view?
- Why don't we have this problem with other inputs on other settings pages?

**Comment by eVoloshchak** [comment] 2023-10-09 11:04
> I guess it's intention behavior of RN navigation

Looks like this is a bug (https://github.com/facebook/react-native/issues/10743), but the discussion ended in 2016. There isn't a consensus on whether this is caused by react-native or react-navigation, but I agree, let's dig deeper to figure out the actual root cause for this

**Comment by mvtglobally** [comment] 2023-10-17 15:18
Issue not reproducible during KI retests. (First week)

**Comment by tgolen** [comment] 2023-10-17 16:11
@abekkala I think this is ready to have its price increased. It would be especially helpful if we could learn if this is indeed no longer reproducible also.

**Comment by tgolen** [comment] 2023-10-18 14:44
bump @abekkala

**Comment by tgolen** [comment] 2023-10-18 19:12
Thanks, all. Closing this one out.

**Closed by tgolen** 2023-10-18 19:12 UTC
Labels: External, Daily, Help Wanted, Bug
