### ISSUE TITLE
[HOLD for payment 2023-12-07] [$500] Request money get $250 not formatted correctly

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31554] opened 2023-11-20 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-3
**Reproducible in staging?:** y
**Reproducible in production?:** seems new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1700345578210519

## Action Performed:
1. Click on the `+` fab
2. Request money
3. Enter an amount and go to the participants selection step
4. Click on the `Request money, get $250` bottom alert.

## Expected Result:
 `Request money, get $250` text to be formatted correctly.

## Actual Result: 
Incorrect formatting (includes an extra space before the amount)

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screenshot 2023-11-19 at 2 27 45 AM](https://github.com/Expensify/App/assets/38435837/e2c27260-814a-43fb-83ac-a8a84cc9312e)

https://github.com/Expensify/App/assets/38435837/e5373504-7eee-4155-ad94-4018f39ed8b0

![New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/b61858bc-2ee2-431d-9e65-ca2f009a50fd)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6c623a72781c0f8</li>
        <li>Upwork Job ID: 1726615300061036544</li>
        <li>Last Price Increase: 2023-11-27</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27852593</li>
</ul></li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2023-11-20 14:56
Proposal from @allroundexperts 

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Request money, get $250 not formatted correctly.
### What is the root cause of that problem?
We have added an extra space [here](https://github.com/allroundexperts/Expensify/blob/2b024fa79ba18283c6462f6219a41cf7fe867106/src/languages/en.ts#L1923)
### What changes do you think we should make in order to solve the problem?

Just remove the extra space [here](https://github.com/allroundexperts/Expensify/blob/2b024fa79ba18283c6462f6219a41cf7fe867106/src/languages/en.ts#L1923).
### What alternative solutions did you explore? (Optional)
None

**Comment by esh-g** [comment] 2023-11-20 14:59
# Proposal

## Root cause
We have extra space here:
https://github.com/Expensify/App/blob/aeced9a93f987acfe17427c241736856fba3a980/src/languages/en.ts#L1923

## Changes
We need to remove the space

**Comment by situchan** [comment] 2023-11-20 15:00
This should be handled as follow-up of https://github.com/Expensify/App/pull/30372
cc: @waterim @cubuspl42 @puneetlath

**Comment by yatinj30** [comment] 2023-11-20 15:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money, get $250 is not formatted correctly.

### What is the root cause of that problem?
There is an extra space before an amount.

### What changes do you think we should make in order to solve the problem?
Remove that extra space before an amount.

### What alternative solutions did you explore? (Optional)
None

**Comment by mallenexpensify** [comment] 2023-11-20 22:50
@fedirjh , please review the above, reckon it'll be a pretty quick fix.  Let me know if you'd like me to loop in a designer to confirm anything.  Thx

**Comment by allroundexperts** [comment] 2023-11-27 15:27
I think this is fixed somehow.

**Comment by puneetlath** [comment] 2023-11-27 18:13
@waterim can I assign this to you since it came from your PR?

**Comment by waterim** [comment] 2023-11-27 18:21
@puneetlath sure, can update this typo

**Comment by puneetlath** [comment] 2023-11-27 18:25
Thanks!

**Comment by mallenexpensify** [comment] 2023-12-08 01:29
@fedirjh can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01f6c623a72781c0f8

**Comment by mallenexpensify** [comment] 2023-12-13 00:12
Contributor+: @fedirjh paid $500 via Upwork.  

I don't think we need to add this to the design/edge case tests we occasionally run, checking with QA to see if anyone disagrees. 
https://expensify.slack.com/archives/C9YU7BX5M/p1702426325644959

**Closed by mallenexpensify** 2023-12-13 00:12 UTC
Labels: External, Daily, Awaiting Payment, Bug
