### ISSUE TITLE
 New task - Empty task form appears when tapping back from reassigning assignee menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21279] opened 2023-06-21 23:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20840
## Action Performed:
1. Login to NewDot
2. Assign a task
3. Open task chat
4. Click header to change assignee
5. Click Back arrow

## Expected Result:
Back arrow should not be there, or clicking/tapping it should close assignee list and bring back to task chat

## Actual Result:
Empty task form is opened, however all details of the task were submitted in step 2

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** .3.30.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2316f91d-7467-4e3d-a89b-d86b1dabddc3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-06-22 02:45
Dupe of https://github.com/Expensify/App/issues/21200

**Closed** 2023-06-22 06:00 UTC
Labels: Daily, Bug
