### ISSUE TITLE
[HOLD for payment 2023-02-10] Update new chat empty state

### ISSUE THREAD

**Issue by shawnborton** [Expensify/App#12256] opened 2022-10-28 17:45 UTC
Note: This issue is part of the greater **[Implement Our New Branding in NewDot](https://github.com/Expensify/Expensify/issues/239140)** project. 

**What is it:**
Updating the default screen you see when you first start a chat with someone. Let’s also use our green brick road pattern for the green plus button (highlight this button in green until text is typed), and let’s use a randomized message for “Say hello!” 

![image](https://user-images.githubusercontent.com/2319350/198699782-775ba627-eb20-4071-85fb-4774602fcf5d.png)

**Does it require a mini design doc:**
Yes, this requires code changes

Design finished: No, still need to create designs for default rooms, group chats, etc. 

cc @GabiHExpensify 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d6a1829f0afc04e</li>
        <li>Upwork Job ID: 1605699152274489344</li>
        <li>Last Price Increase: 2022-12-21</li>
    </ul>
</details>

**Comment by dangrous** [comment] 2022-10-29 01:01
Lemme know what you need in order to help with the design and/or design doc! First time getting involved this early in a project so not sure what's most useful at this point.

**Comment by JmillsExpensify** [comment] 2022-11-02 17:44
If you need any help with the high-level design in the mini-doc, I think this one could probably use a more fleshed out non-detailed part – especially for our approach to GBR as well as the randomized welcome messages.

**Comment by shawnborton** [comment] 2022-11-02 20:08
We're hoping to have another engineer join in on the fun and help lead this one, I'll keep soliciting volunteers in the room this week.

**Comment by shawnborton** [comment] 2022-11-03 23:05
[Posted some Slack discussion here](https://expensify.slack.com/archives/C03KN50J0PM/p1667516425430569)

**Comment by shawnborton** [comment] 2022-11-04 17:59
Okay so based on the Slack discussion, we decided against:
- any kind of special green brick road plus button treatment
- random welcome messages

So that being said this one becomes way more straight forward and I don't think it needs a design doc. Curious if you agree @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-11-06 02:26
Agree 100%.

**Comment by dangrous** [comment] 2022-11-08 00:15
Cool! I can start playing around with this this week, if no design doc needed. Will likely have some questions as I go. First one - are we removing the timezone call out that's in the left hand image?

**Comment by JmillsExpensify** [comment] 2022-11-08 04:43
> are we removing the timezone call out that's in the left hand image?

No, that's just a detail not included in the mock. Let's keep that functionality as is.

**Comment by shawnborton** [comment] 2022-11-09 19:48
Yup agree, that was just an oversight on my part regarding the timezone.

**Comment by dangrous** [comment] 2022-11-18 18:44
@shawnborton I am OOO all next week - is it okay to pick this up when I'm back on 11/28? If not I can see if I can find a willing sub in the meantime (not sure what our goal timeline here is)

**Comment by shawnborton** [comment] 2022-11-18 19:42
I think we want to move as quickly as we can, so it can't hurt to see if anyone can take this over from you. Maybe by sending a quick message in open source letting people know it's up for grabs?

**Comment by mallenexpensify** [comment] 2022-12-21 00:11
@dangrous , @mananjadhav is due payment for C+ on [the associated PR](https://github.com/Expensify/App/pull/12965), correct? I'm assuming it $1000, can either of you let me know if that's not correct? Once confirmed I'll create an Upwork job and issue payment

**Comment by dangrous** [comment] 2022-12-21 14:38
@mallenexpensify yep! 1k is correct.

**Comment by CherylWalsh** [comment] 2022-12-21 16:38
Say hello! - keep this copy . 

You can also use the + button below to send or request money. Try it, it's super easy! 

please change the above copy to: 
You can also use the + button below to send or request money! 

Reference here: https://expensify.slack.com/archives/C03SSAQG5/p1671637303512219

**Comment by mallenexpensify** [comment] 2022-12-21 17:55
@mananjadhav will get to soon, checking on an upwork issue and want to resolve before creating the job (also... I wonder if I could just add then remove the `External` label to have the job created.  @thienlnam , any reason that wouldn't work?)

**Comment by thienlnam** [comment] 2022-12-21 19:26
Yeah that would work, though we've also made a change recently [here](https://github.com/Expensify/Expensify/issues/247613) where we create an Upwork job and add a C+ internal reviewer for 'Internal' jobs as well so you could also just add the internal label here and keep it on

**Comment by mallenexpensify** [comment] 2022-12-21 23:02
woah... what are the chances, Manan got assigned, hahahh.  
Please apply @mananjadhav 
https://www.upwork.com/jobs/~019d6a1829f0afc04e

@dangrous , last thing... Should I wait til 7 days after this issue is closed before paying?

**Comment by mananjadhav** [comment] 2022-12-22 02:40
@mallenexpensify I am unable to apply to the job. Also the PR in discussion is already deployed to the production and crossed the 7 day regression period. 

I think there’ll be more than one PRs here so issue won’t get closed.

**Comment by mallenexpensify** [comment] 2022-12-23 01:27
@mananjadhav , please try to submit again https://www.upwork.com/jobs/~019d6a1829f0afc04e
Thx

**Comment by mananjadhav** [comment] 2022-12-23 02:34
This worked, applied @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-23 23:40
Hired @mananjadhav , please accept and I'll pay  https://www.upwork.com/jobs/~019d6a1829f0afc04e 

fwiw... the reason you likely weren't able to apply @mananjadhav is because, for the trigger from `Internal`, the job is private since it's for C+ (I think, still new to me)

**Comment by mananjadhav** [comment] 2022-12-27 01:26
@mallenexpensify this still pending for payout. Can you please help with the same ?

**Comment by mallenexpensify** [comment] 2022-12-27 15:38
Paid @mananjadhav , thanks!
@JmillsExpensify , @shawnborton , do we update regression test steps for design improvements?  If so, I think it's just be "Verify _new_ design is shown (with weird characters, dark green)"

**Comment by JmillsExpensify** [comment] 2022-12-27 16:19
We don't have a serious of regression steps for the broader design updates we've made. That topic has been [broached here](https://github.com/Expensify/Expensify/issues/247948#issuecomment-1360783748).

**Comment by mallenexpensify** [comment] 2022-12-30 02:19
That does appear to be a bit confusing @parasharrajat , I'm unsure what might have gone _wrong_ nor what the best next step is.  What would you and/or @mananjadhav suggest?

Regardless, if you've invested the time in https://github.com/Expensify/App/pull/13647, which it appears you have, you'll be eligible for compensation.

**Comment by mananjadhav** [comment] 2022-12-30 02:29
I think this issue was being resolved in two parts - one with composer changes and one with the empty state and hence two separate PRs.

We could create a separate issue just for the composer bar, I am not sure if there’s any specific tracking done per issue? Or consider this an exception (as it generally doesn’t happen), and treat two PRs for the linked issue.

**Comment by mallenexpensify** [comment] 2022-12-30 21:02
Thanks @mananjadhav and @parasharrajat. So... 
1. In the future it's best to have separate GH issues to keep from there being multiple PRs linked to the same issue, right?  I agree with this for multiple reasons - best practice, consistency, easier to follow/track/pay and also for automation inc. Upwork<>GH integration .  
2. @mananjadhav 's been paid for his review, @parasharrajat you are also due $1000 7 days after https://github.com/Expensify/App/pull/13647 is merged, correct? If so we'll leave this open.

**Comment by mananjadhav** [comment] 2023-01-02 06:12
I am unassigning myself here now, as the main PR is tagged to @parasharrajat already.

**Comment by dangrous** [comment] 2023-02-13 14:51
I think we're good to pay and close this one out, right?

**Comment by shawnborton** [comment] 2023-02-13 15:33
I would say so, yeah.

**Comment by mallenexpensify** [comment] 2023-02-14 00:43
@parasharrajat , invited you to the job, can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~016aa125cd7c545ae8

**Comment by shawnborton** [comment] 2023-02-20 15:09
Not overdue. @parasharrajat see above please!

**Comment by mallenexpensify** [comment] 2023-02-22 19:44
@parasharrajat is paid $1000!

**Closed by mallenexpensify** 2023-02-22 19:44 UTC
Labels: Daily, Internal, Design, Overdue, Waiting for copy, Awaiting Payment
