### ISSUE TITLE
[$1000] Settings -Changes "Notifications"/ Priority mode offline aren't saved

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11778] opened 2022-10-12 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Log in with any account
3. Navigate to Settings > Preferences
4. Disable the internet connection in the device
5. Toggle the Notification option
6. Go back online

## Expected Result:
Notifications toggle is still in the same position as it was offline

## Actual Result:
Changes "Notifications" made offline aren't saved. The switch returns to its original position.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Mobile Web

**Version Number:** 1.2.13.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes
 
**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/195450805-1ebebfc4-15a0-429c-b861-21b8e3a176db.mp4

https://user-images.githubusercontent.com/93399543/195452894-8ce88219-6874-4cb9-a203-5b7389a57fda.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c0254925e0e226e4</li>
        <li>Upwork Job ID: 1603370449146945536</li>
        <li>Last Price Increase: 2022-12-15</li>
    </ul>
</details>

**Comment by alex-mechler** [comment] 2022-10-13 17:43
I'm not able to reproduce this on Web, although I'm not on an ios device. If I switch the toggle while offline, it remains in the correct position after going back. Is this only reproducible on iOS @kbecciv?

**Comment by kbecciv** [comment] 2022-10-13 23:42
@alex-mechler Checking with team, will update you shortly.

**Comment by alex-mechler** [comment] 2022-10-14 21:38
@kbecciv did you hear back from the team?

**Comment by kbecciv** [comment] 2022-10-15 02:27
@alex-mechler , we can reproduced in all environments.


https://user-images.githubusercontent.com/93399543/195964799-57483124-01e3-4ebf-9cac-63c2e6740f7a.MP4


https://user-images.githubusercontent.com/93399543/195964776-dc2a89b0-7b19-4b8c-abac-553efbacedb8.mp4

https://user-images.githubusercontent.com/93399543/195964762-c87da9dd-0b98-43f0-870a-5158a2add778.MP4


https://user-images.githubusercontent.com/93399543/195964765-093bab9f-b4dd-4a16-a6c5-7f63d03a086e.mp4

.

**Comment by alex-mechler** [comment] 2022-10-17 16:54
Thanks for checking! Sending this external, since I can't get it to reproduce, I don't think it requires API changes

**Comment by Beamanator** [comment] 2022-10-18 12:05
mooost likely this is due to the fact that Pusher isn't sending messages, due to hitting an API quota limit

**Comment by Beamanator** [comment] 2022-10-18 12:05
Putting on hold till we figure out if that's the problem (I can reproduce this error in dev)

**Comment by alexpensify** [comment] 2022-10-19 00:16
For now, I won't take any action and will hold on uploading to Upworks.

**Comment by Beamanator** [comment] 2022-10-19 12:23
Ya I can't reproduce this anymore in dev or staging, I'll close for now, can reopen if someone can reproduce

**Comment by kbecciv** [comment] 2022-11-10 13:47
Issue is reproduced with build 1.2.26.0

https://user-images.githubusercontent.com/93399543/201108434-b3de8b40-7895-414b-b4bc-030fdc109d0e.MP4

**Comment by Beamanator** [comment] 2022-11-10 22:12
Woah that's really weird that the setting switched back & forth many times after waiting a while 🤔

**Comment by Beamanator** [comment] 2022-11-10 22:16
Hmm I'm not able to reproduce on Android, @kbecciv which device are you using? I'm Android, Samsung galaxy A71, App version v1.2.26-0

**Comment by kbecciv** [comment] 2022-11-14 14:47
@Beamanator It was on IOS device for the video above.
Let me know if we need to re-test in all environments with current build.

**Comment by alexpensify** [comment] 2022-11-18 17:47
@Beamanator - I think you are traveling today. Any chance we can get an update early next week?

**Comment by alexpensify** [comment] 2022-11-26 03:19
@Beamanator - I'm OOO until Wednesday, can we get an update here on the next steps? Thanks!

**Comment by Beamanator** [comment] 2022-11-28 19:17
Oooops so sorry for the delay!! Will have an update soon

**Comment by Beamanator** [comment] 2022-11-28 20:04
Ok ok so I believeee I'm seeing the issue on iOS (still not on web or Android for some reason) and here's what I'm thinking the problem is: when I followed the steps to reproduce (go offline, update priority mode, go back online) in web, I saw these 3 API commands being called, in this order:

<img width="457" alt="Screen Shot 2022-11-28 at 9 58 24 PM" src="https://user-images.githubusercontent.com/3885503/204369426-cac6ae48-e44b-49da-83eb-b094873d1b21.png">

I haven't 100% confirmed if this is happening in iOS (hard to test offline in an iOS simulator, & hard to get logs directly from a device haha) but it would make sense we could get problems iff the `ReconnectApp` command starts gathering its data as the `UpdateChatPriorityMode` hits, updates, sends its updates to the device, then the `ReconnectApp` information returns to the device (with old data).

Iffff this is the case, we should be able to see "real" data if the user logs out & in after following the above steps, as in that case the app should pull in only correct, live data.

@kbecciv can you please try the steps you used to reproduce on iOS, then do these steps:
1. Log out, log in
2. Check what the priority mode is (hoping to see it's the correct, updated value)

**Comment by alexpensify** [comment] 2022-12-06 00:41
@kbecciv any luck to follow @Beamanator steps?

**Comment by kbecciv** [comment] 2022-12-07 20:56
@alexpensify @Beamanator  Just checked provided steps in IOS app with build 1.2.36.2 and priority mode is not updated correctly after log out and log in again: 
1. Go offline
2. Update priority mode
3. Go back online
4. Log out and log in
5. Check what the priority mode

https://user-images.githubusercontent.com/93399543/206293689-7cae7c19-a057-48c9-a088-58f15d3f9c9c.MP4

**Comment by alexpensify** [comment] 2022-12-14 19:39
@Beamanator - could you share feedback regarding the steps?

**Comment by Beamanator** [comment] 2022-12-15 12:44
Thanks for testing that flow @kbecciv ! Very strange behavior, but since it's very reproducible I think we should keep this open & see if we can get help externally - I am guessing the issue has something to do with multiple requests being sent & returning with different values of the priority mode, though I have no idea _why_ that would be the case 😅

**Comment by priyeshshah11** [comment] 2022-12-16 12:26
## Proposal

### Problem

@Beamanator rightly pointed out [here](https://github.com/Expensify/App/issues/11778#issuecomment-1353006478) that this an issue where there are multiple requests that changes/toggles the data and the ReconnectApp comes back with the first value which triggers the onChange function and multiple requests are sent and it goes into an infinite loop of requests. This happens for all places where the data value change automatically triggers the api request.

### Solution

1. Implement a replace function in the `SequentialQueue` & `PersistedRequests` that replaces the requests with the same key for all those requests that triggers api requests on data value change.

Add a new prop `shouldReplace` to `write` function which determines push or replace behaviour.
```diff
diff --git a/src/libs/API.js b/src/libs/API.js
--- a/src/libs/API.js
+++ b/src/libs/API.js
@@ -14,11 +14,12 @@ import CONST from '../CONST';
  * @param {Object} onyxData  - Object containing errors, loading states, and optimistic UI data that will be merged
  *                             into Onyx before and after a request is made. Each nested object will be formatted in
  *                             the same way as an API response.
+ * @param {Boolean} shouldReplace - Indicator to replace existing queued requests with same command.
  * @param {Object} [onyxData.optimisticData] - Onyx instructions that will be passed to Onyx.update() before the request is made.
  * @param {Object} [onyxData.successData] - Onyx instructions that will be passed to Onyx.update() when the response has jsonCode === 200.
  * @param {Object} [onyxData.failureData] - Onyx instructions that will be passed to Onyx.update() when the response has jsonCode !== 200.
  */
-function write(command, apiCommandParameters = {}, onyxData = {}) {
+function write(command, apiCommandParameters = {}, onyxData = {}, shouldReplace = false) {
     // Optimistically update Onyx
     if (onyxData.optimisticData) {
         Onyx.update(onyxData.optimisticData);
@@ -43,6 +44,11 @@ function write(command, apiCommandParameters = {}, onyxData = {}) {
         },
         ..._.omit(onyxData, 'optimisticData'),
     };
+    if (shouldReplace) {
+        SequentialQueue.replace(request);
+    } else {
+        // Write commands can be saved and retried, so push it to the SequentialQueue
+        SequentialQueue.push(request);
+    }

```


2. Implement the replace function that removes queued requests with the same key. 
> Note: Code has been refactored to follow DRY.
```diff
diff --git a/src/libs/Network/SequentialQueue.js b/src/libs/Network/SequentialQueue.js
index f37eb8422..1d644adb2 100644
--- a/src/libs/Network/SequentialQueue.js
+++ b/src/libs/Network/SequentialQueue.js
@@ -83,13 +83,7 @@ function isRunning() {
 // Flush the queue when the connection resumes
 NetworkStore.onReconnection(flush);
 
-/**
- * @param {Object} request
- */
-function push(request) {
-    // Add request to Persisted Requests so that it can be retried if it fails
-    PersistedRequests.save([request]);
-
+function triggerFlush() {
     // If we are offline we don't need to trigger the queue to empty as it will happen when we come back online
     if (NetworkStore.isOffline()) {
         return;
@@ -104,6 +98,24 @@ function push(request) {
     flush();
 }
 
+/**
+ * Pushes a new request to the queue
+ * @param {Object} request
+ */
+function push(request) {
+    // Add request to Persisted Requests so that it can be retried if it fails
+    PersistedRequests.save([request]);
+    triggerFlush();
+}
+
+/**
+ * Replaces any existing request with the same key
+ * @param {Object} request
+ */
+ function replace(request) {
+     // Add request to Persisted Requests so that it can be retried if it fails
+     PersistedRequests.replace(request);
+     triggerFlush();
+ }

```

3. Finally, pass `shouldReplace` as `true` for all `API.write` calls where we want to replace requests. I am only aware of these two places at this stage but we can do this everywhere where data change automatically triggers api requests. Potentially can do this for `UpdatePreferredEmojiSkinTone` too.
```diff
diff --git a/src/libs/actions/User.js b/src/libs/actions/User.js
index 6a4a0775f..2ca75e09d 100644
--- a/src/libs/actions/User.js
+++ b/src/libs/actions/User.js
@@ -161,7 +161,7 @@ function updateNewsletterSubscription(isSubscribed) {
                 value: {isSubscribedToNewsletter: !isSubscribed},
             },
         ],
-    });
+    }, true);
 }
 
 /**
@@ -427,7 +427,7 @@ function updateChatPriorityMode(mode) {
     ];
     API.write('UpdateChatPriorityMode', {
         value: mode,
-    }, {optimisticData});
+    }, {optimisticData}, true);
 }
 
 /**
```
@sobitneupane

**Comment by abdulrahuman5196** [comment] 2022-12-17 11:23
Proposal:
Background:
What API responses can change the Onyx key value of 'nvp_priorityMode' (Chat priority mode key)?
1) UpdateChatPriorityMode - API to change the priority mode
2) ReconnectApp - API to refresh app data including 'nvp_priorityMode'
3) Pusher notification including 'nvp_priorityMode'

Root cause:
Now as you see, we have 3 ways in which a 'nvp_priorityMode' can be updated. But there aren't any concurrency checks between them to make sure no overlapping is happening.
Like for the case @Beamanator  mentioned if ReconnectApp API completes before UpdateChatPriorityMode API, it will bring back the non-updated 'nvp_priorityMode' data from server. And UpdateChatPriorityMode API doesn't have any response onyxData and we don't set any successData as well. In this case app will show old data from ReconnectApp API until we get a pusher notification or 'ReconnectApp' API is triggered again which will return proper data.

Solution:
There are couple of things we can do to fix the concurrency issue in a long term for other API's as well.

1) Add successData to UpdateChatPriorityMode API:
We can add successData to UpdateChatPriorityMode API which will ensure only proper value is set to Onyx after successful API call. This will also remove any stale 'nvp_priorityMode' values present due any other concurrency edge case.

```
const successData = [
        {
            onyxMethod: CONST.ONYX.METHOD.MERGE,
            key: ONYXKEYS.NVP_PRIORITY_MODE,
            value: mode,
        },
    ];
    API.write('UpdateChatPriorityMode', {
        value: mode,
    }, {optimisticData, successData});

```

2) Add API priority mechanism:
Having API priority mechanism will be helpful as a long term solution for other similar API's as well. 
For example in this case, we can consider API's with higher priority to be executed first and we can set API priority as follows,
```
UpdateChatPriorityMode - priority -  5
ReconnectApp - priority -  3
```
This way we can ensure UpdateChatPriorityMode is completed before ReconnectApp completes which will avoid any concurrency issues between related API's

3) Keep only latest API request:
We can remove older UpdateChatPriorityMode requests from the SequentialQueue when user triggers new UpdateChatPriorityMode API call. 
I have seen examples of this similar replace proposals by different people in different places on this repository which could indicate this as a common problem. https://github.com/Expensify/App/issues/13521#issuecomment-1347700448


I think implementing all 3 solutions proposed above would have long-term advantages in terms of API handling in the application. 
@sobitneupane

**Comment by Beamanator** [comment] 2022-12-19 09:22
@sobitneupane do you have time to review the proposals ^ today?

**Comment by priyeshshah11** [comment] 2022-12-19 10:31
> @priyeshshah11 Thanks for your proposal.
> 
> You have used `PersistedRequests.replace(request);` I can not find replace function in PersistedRequests.
> 
> ```diff
> + function replace(request) {
> +     // Add request to Persisted Requests so that it can be retried if it fails
> +     PersistedRequests.replace(request);
> +     triggerFlush();
> + }
> ```
> 
> Don't you think the same issue can arise in other dropdown(like Language, Unit in Reimburse expenses) and toggles?

@sobitneupane yes my bad, that part is missing from my diff (copy-pasting) error. Also, yes this issue can arise in those dropdowns & toggles too thus I said this
> This happens for all places where the data value change automatically triggers the api request.

but did not know about how many/which ones there are but the same principal applies there.

```diff
diff --git a/src/libs/actions/PersistedRequests.js b/src/libs/actions/PersistedRequests.js
index 260526c13..5a7a8333b 100644
--- a/src/libs/actions/PersistedRequests.js
+++ b/src/libs/actions/PersistedRequests.js
@@ -49,10 +49,21 @@ function incrementRetries(request) {
     return persistedRequestsRetryCounter.incrementRetries(request);
 }
 
+/**
+ * @param {Array} requestToReplace
+ */
+function replace(requestToReplace) {
+    const updatedPersistedRequests = _.filter(persistedRequests, request => request.command !== requestToReplace.command);
+    updatedPersistedRequests.push(requestToReplace);
+    persistedRequests = updatedPersistedRequests;
+    Onyx.set(ONYXKEYS.PERSISTED_REQUESTS, persistedRequests);
+}
+
 export {
     clear,
     save,
     getAll,
     remove,
     incrementRetries,
+    replace,
 };

```

**Comment by sobitneupane** [comment] 2022-12-19 10:35
@abdulrahuman5196 Thanks for your proposal.

Can you be more specific please. Which are the files you are proposing the changes. Can you link those files and explain what are the changes you are proposing? (Example: https://github.com/Expensify/App/issues/11778#issuecomment-1354689948)

**Comment by sobitneupane** [comment] 2022-12-19 10:38
@priyeshshah11 

> the ReconnectApp comes back with the first value which triggers the onChange function 

Your proposal might prevent the subsequent requests. But if the ReconnectApp comes back with the previous value, won't it reset the values to the state received in ReconnectApp?

**Comment by priyeshshah11** [comment] 2022-12-19 10:41
> @priyeshshah11
> 
> > the ReconnectApp comes back with the first value which triggers the onChange function
> 
> Your proposal might prevent the subsequent requests. But if the ReconnectApp comes back with the previous value, won't it reset the values to the state received in ReconnectApp?

@sobitneupane That issue arrises only when multiple requests are sent simultaneously, otherwise ReconnectApp always comes back with the right state (new updated state).

**Comment by sobitneupane** [comment] 2022-12-19 14:00
@priyeshshah11 
 I tested your proposal and it didn't work for me. Still Priority mode changed offline are not being saved.

**Comment by priyeshshah11** [comment] 2022-12-19 14:02
> @priyeshshah11 I tested your proposal and it didn't work for me. Still Priority mode changed offline are not being saved.

are you able to share a video of the behaviour that you're seeing? I will try to do the same

**Comment by sobitneupane** [comment] 2022-12-19 14:21
I was able to reproduce the issue on native devices only not on desktop and Web.

Steps:
1. Open the app
2. Log in with any account
3. Navigate to Settings > Preferences
4. Disable the internet connection in the device
5. Change the priority mode
6. Go back online

Tested on IOS.

https://user-images.githubusercontent.com/25876548/208446133-445997e4-158c-4bf6-a457-4130a588cb2e.mp4

**Comment by priyeshshah11** [comment] 2022-12-19 14:40
@sobitneupane I can reproduce on iOS without my fix but cannot reproduce it with my fix (so I mean to say that it works).

### Without fix
https://user-images.githubusercontent.com/38547776/208450274-a164cf74-035c-4e74-9252-0d4a650ac9dc.mov

### With my fix
https://user-images.githubusercontent.com/38547776/208450334-7eb2f527-e4dd-40dd-865c-3405d2927d9f.mov

**Comment by sobitneupane** [comment] 2022-12-19 14:50
On web, When I change the priority mode quickly for few times, it starts oscillating between the modes.


https://user-images.githubusercontent.com/25876548/208452548-232a5d74-9216-45d6-a9ce-d216cf2469db.mov

**Comment by priyeshshah11** [comment] 2022-12-19 15:16
> On web, When I change the priority mode quickly for few times, it starts oscillating between the modes.
> 
>  Screen.Recording.2022-12-19.at.20.30.10.mov

@sobitneupane The above solution fixes the OG bug, I think "switching between modes quickly several times" is currently showing this odd behaviour due to the fact that the server is running a bit slow right now thus it queues a new request before it has received a response back from the previous one which I think is a very rare edge case i.e How often are users actually going to switch between modes so quickly & frequently along with the server being slow at the same time?

If we still want to fix this particular edge case, then the only option would be to disable the picker until we get a response back, just like we do for SignIn.

**Comment by s77rt** [comment] 2022-12-19 18:38
This seems to be another issue related to the Pusher.
I think this needs to be handled internally, at least partly

- The solution should revolve around adding certain fields to the pusher notifications where we use those fields to validate events and ignore those that does not pass the validation e.g. `timestamp`.
- Another solution is to implement a lock mechanism i.e. a value on onyx should not be modified if it's locked by another "`thread`" (similarity on how concurrency works on other languages...)

I don't have a proper proposal at the moment, just wanted too share my toughts hopefully we will be heading to the right solution.

___

@priyeshshah11 Your solution won't work if the request has been sent already.

**Comment by abdulrahuman5196** [comment] 2022-12-20 14:41
> @abdulrahuman5196 Thanks for your proposal.
> 
> Can you be more specific please. Which are the files you are proposing the changes. Can you link those files and explain what are the changes you are proposing? (Example: [#11778 (comment)](https://github.com/Expensify/App/issues/11778#issuecomment-1354689948))

Hi, @sobitneupane  my original proposal is here,  
https://github.com/Expensify/App/issues/11778#issuecomment-1356204283

For solution 
Action item 1

```
--- a/src/libs/actions/User.js
+++ b/src/libs/actions/User.js
@@ -425,9 +425,16 @@ function updateChatPriorityMode(mode) {
             value: mode,
         },
     ];
+    const successData = [
+        {
+            onyxMethod: CONST.ONYX.METHOD.MERGE,
+            key: ONYXKEYS.NVP_PRIORITY_MODE,
+            value: mode,
+        },
+    ];
     API.write('UpdateChatPriorityMode', {
         value: mode,
-    }, {optimisticData});
+    }, {optimisticData, successData});
 }
 
```

Action item 2:
This might be a more complex step, To implement API priority we have to add API priority logic in 'SequentialQueue' 'process' function. There we have to sort and pick tasks based on priority. This way we can make sure 'ReconnectApp' or other data refresher APIs are executed after 'UpdateChatPriorityMode'. This would be difficult to provide draft working code.

Action item 3:
I have already noted a different comment on different issue

```
We can remove older UpdateChatPriorityMode requests from the SequentialQueue when user triggers new UpdateChatPriorityMode API call.
I have seen examples of this similar replace proposals by different people in different places on this repository which could indicate this as a common problem. 
https://github.com/Expensify/App/issues/13521#issuecomment-1347700448
```

**Comment by alexpensify** [comment] 2022-12-21 20:07
@Beamanator - It sounds like this one is on hold. Should we move it to Weekly to give more time for the regroup process?

**Comment by PauloGasparSv** [comment] 2022-12-21 20:10
I don't think there is a need for that right now @alexpensify

**Comment by JmillsExpensify** [comment] 2022-12-21 20:15
Yeah this is not on hold. This should remain a daily.

**Comment by alexpensify** [comment] 2022-12-23 18:12
Thanks for the feedback! I'm going OOO until January 3 and will catch up then to identify if there is any movement here.

**Comment by JmillsExpensify** [comment] 2022-12-23 19:04
Cool, I will keep at eye out, as this is one of the oldest issues in the repo without a PR.

**Comment by PauloGasparSv** [comment] 2022-12-26 13:56
I think we should change those toggles to be [Pattern D or C](https://docs.google.com/document/d/1RWPLDgdrJ4eW1KfseVmrYYy_fDUWWDQpek-hmdzAtuM/edit#heading=h.ns12dr1f35rx), so we block the UI when the user goes offline.

This request order issue looks generic enough that it could affect other requests though, so I want some more input on this. I'll throw this on slack and see what the team thinks of it.

**Comment by JmillsExpensify** [comment] 2022-12-26 17:07
Based on [the discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463621448669) in the Slack thread, the title of this issue is incorrect. It seems that we are saving the settings correctly, but due to site slows, the two requests hit two different servers – one of which is behind versus the other – so older data gets served up. Refreshing would correctly show the "correct" data. 

Again, based on this discussion, we're closing this issue. If we experience it again during site slows, or come up against backend performance more in the future, we'll re-assess.

**Closed by JmillsExpensify** 2022-12-26 17:07 UTC
Labels: Engineering, Daily, Internal, Bug
