### ISSUE TITLE
Web - Workspace - Inviting a member offline does not cross the name out

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14780] opened 2023-02-03 01:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Click on profile > Workspace > Manage members
4. Invite a member
5. Turn off internet connection
6. Remove the member while offline

## Expected Result:
User expects the name to be crossed out while offline

## Actual Result:
The name just simply disappears from the members list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.64.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/216486595-6b97ca63-fa6c-4658-be41-852b64b67389.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team / @Tushu17 

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-02-03 01:08
Not repro in Production

<img width="1440" alt="Screenshot 2023-02-02 at 21 45 18" src="https://user-images.githubusercontent.com/93399543/216486715-ca4b7525-5cfa-43ba-8967-9dc41bbaf54b.png">

**Comment by bfitzexpensify** [comment] 2023-02-03 06:17
Working for me on both staging:

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/38236554/216526696-0df39b33-1c4a-4be3-9681-689a9fcbf3ee.png">

And production:

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/38236554/216526628-bc6d913a-55e0-4f23-99dd-6c2a50f19fb0.png">

Going to close this one out for the moment

**Comment by kbecciv** [comment] 2023-02-03 23:52
@bfitzexpensify This is issue happening in Web ONLY.

**Comment by bfitzexpensify** [comment] 2023-02-06 07:24
@kbecciv sorry, the first screenshot looks like the desktop app, but it is in web. 

Here's a clearer screenshot:

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/38236554/216909839-193fed51-5000-4cab-8f24-259da1a5cf56.png">

Are you able to reproduce?

**Comment by mountiny** [comment] 2023-02-06 13:25
<img width="370" alt="image" src="https://user-images.githubusercontent.com/36083550/216983046-84317655-9e17-444e-9f51-5ee180669626.png">


Also could not repro on latest staging web. Closing for now

**Closed by mountiny** 2023-02-06 13:25 UTC
Labels: Daily, Bug
