### ISSUE TITLE
Reaction to as task disappears inside task when coming back from main chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22213] opened 2023-07-04 19:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a task
2. Close and reopen the task in the main chat
2. Go to the task and React to the task
3. Go to main chat
4. Come back
## Expected Result: 
The reaction should be there
## Actual Result: 
The reaction disappears

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[react to a task disappears.webm](https://github.com/Expensify/App/assets/43996225/6eb1ab31-8b6e-4873-a90e-42042a41d50a)

https://github.com/Expensify/App/assets/43996225/2a450606-0414-4d2b-bd24-30bb24b1bf92

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kassahun-asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688414177188309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-05 01:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reactions to task disappears when come back from parent chat

### What is the root cause of that problem?

When reacting to the message, we get the original report ID here
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/libs/ReportUtils.js#L2392-L2394

Taking a look into `isThreadFirstChat` function
https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/libs/ReportUtils.js#L554-L556

we can notice that task messages(TASKCOMPLETED and TASKREOPENED) meet the condition, but they are not the thread first messages. So when reacting to task messages, parent reportID is used. This is wrong.

This is the 1st reason of the issue.

When call reaction API with the corrected reportID, backend returns reactions in originalMessage, not in message
![image](https://github.com/Expensify/App/assets/126839717/ad5f6ea1-106c-4dae-9a52-98920e2f5c78)

This is the 2nd reason of the issue

### What changes do you think we should make in order to solve the problem?

1. Frontend only solution
Creates the `isTaskAction` function in ReportActionUtils.js
```
function isTaskAction(reportAction) {
    const taskActions = [
        CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED,
        CONST.REPORT.ACTIONS.TYPE.TASKREOPENED,
        CONST.REPORT.ACTIONS.TYPE.TASKCANCELED,
    ];
    return _.includes(taskActions, lodashGet(reportAction, 'actionName', ''));
}
```

Updates the `isThreadFirstChat` function
```
    return (
        isThreadFirstChat(reportAction, reportID) && !ReportActionUtils.isTaskAction(reportAction) ?
        lodashGet(allReports, [`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, 'parentReportID']) :
        reportID
    );
```

Merge `message`'s reactions and `originalMessage`'s reactions

This works as expected.

2. Frontend & Backend solution
The 1st issue can be fixed in frontend and the 2nd issue can be fixed in backend

3. Backend only solution
Backend should return task messages without `childReportID`. I think this is reasonable
Backend also should return reactions in `message`


### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment] 2023-07-05 02:19
Dupe https://github.com/Expensify/App/issues/22061

**Closed by sophiepintoraetz** 2023-07-05 02:19 UTC
Labels: Daily, Bug
