### ISSUE TITLE
[$500] Distance - While editing distance, "use current location" option is not displayed

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32404] opened 2023-12-02 15:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon near compose
4. Tap request money---distance
5. Enter start and finish waypoints
6. Tap request
7. Tap on created distance request to open distance request detail page
8. Tap on distance
9. Tap start and note "use current location" option not displayed
10. Tap finish and note "use current location" option not displayed
11. Tap Add stop and note "use current location" can be seen

## Expected Result:
While editing distance, "use current location" option must be displayed for start and finish waypoints.

## Actual Result:
While editing distance, "use current location" option is not displayed for start and finish waypoints.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c10e96b0-94d1-4982-b854-9a466c845eb3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011640a9e861eb16d6</li>
        <li>Upwork Job ID: 1730973067322466304</li>
        <li>Last Price Increase: 2023-12-02</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-12-02 15:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While editing distance, "use current location" option is not displayed

### What is the root cause of that problem?
Currently, "use current location" option is displayed when the search value is empty. But when editing distance, the search value will be current waypoint as default
### What changes do you think we should make in order to solve the problem?
We can update to display "use current location" option even though search value is not empty

### What alternative solutions did you explore? (Optional)
We can reset search value to empty in edit waypoint page

**Comment by DylanDylann** [comment] 2023-12-02 16:14
@trjExpensify Currently, "use current location" option is displayed when the search value is empty. But when editing distance, the search value will be the current waypoint as default. What do you think if we display "use current location" option even though search value is not empty

**Comment by s77rt** [comment] 2023-12-02 21:22
@DylanDylann Thanks for the proposal. Your RCA is correct. However I don't think we want to keep the "Use current location" option always visible as it may be annoying when searching for other places.

**Comment by s77rt** [comment] 2023-12-02 21:37
@Krishna2323 On it

**Comment by s77rt** [comment] 2023-12-02 22:10
@Krishna2323 Thanks! That's looks good to me 👍 

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/32404#issuecomment-1837197476)

**Comment by DylanDylann** [comment] 2023-12-04 14:42
@s77rt 

[updated proposal](https://github.com/Expensify/App/issues/32404#issuecomment-1837185106) to disable "use current location" option if a user is editing the waypoint

**Comment by s77rt** [comment] 2023-12-04 16:49
@DylanDylann Thanks for the update. I don't think we should completely disable the "use current location" option even if the address input is empty. @trjExpensify meant [this](https://github.com/Expensify/App/issues/32404#issuecomment-1838494232) in the sense that this is not a bug.

**Comment by trjExpensify** [comment] 2023-12-04 16:54
Right, I think this issue should be closed. It's working as expected, IMO. When the field input is empty, it shows "use current location" otherwise it shows results that match what's entered. 

Happy for a second opinion from Neil and Jason though before we close it out.

**Closed** 2023-12-07 15:31 UTC
Labels: External, Daily, Help Wanted, Bug
