### ISSUE TITLE
[$1000]  Home address - Blank space between City / Zip input and keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24007] opened 2023-08-01 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22788
## Action Performed:
1. Open iOS app
2. Open "Settings"
3. Tap on "Profile"
4. Tap on "Personal details"
5. Tap on "Home address"
6. Tap on "City" or "Zip" field

## Expected Result:
Input fields and fields below them are completely visible when user sets focus to them

## Actual Result:
When user sets focus to "City" Blank space appears between "City" input and keyboard, which hides ZIP input . Blank space covers "Zip" input when user sets focus to it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6149369_IMG_8700](https://github.com/Expensify/App/assets/78819774/7d4ea038-40ec-4253-b307-12405ca9c73a)

Uploading Bug6149369_RPReplay_Final1690886551.mp4…

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f80da5c51765299</li>
        <li>Upwork Job ID: 1686690703095570432</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 25901299</li>
</ul></li>
    </ul>
</details>

**Comment by pac-guerreiro** [comment] 2023-08-01 16:35
I'm Pedro Guerreiro, an expert from Callstack and I wish to take a look into this issue 😄

**Comment by CortneyOfstad** [comment] 2023-08-01 20:47
Heading OoO until 8/14, so reassigning the BZ label to get this tackled 👍

**Comment by greg-schroeder** [comment] 2023-08-02 10:51
Looks like CS wants to take a stab at this one!

**Comment by greg-schroeder** [comment] 2023-08-02 10:51
Assigning you @pac-guerreiro to proceed

**Comment by pac-guerreiro** [comment] 2023-08-02 16:42
@greg-schroeder 

This issue was caused by this PR - https://github.com/Expensify/App/pull/23222

**Comment by jscardona12** [comment] 2023-08-02 17:06
This is a dup of https://github.com/Expensify/App/issues/23481

**Comment by greg-schroeder** [comment] 2023-08-02 17:28
Damn, I didn't see #23481 when I looked around. Closing.

**Closed by greg-schroeder** 2023-08-02 17:28 UTC
Labels: External, Daily, Bug
