### ISSUE TITLE
[$250] Workspace - Added non-existent members in WS disappear from the list.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40301] opened 2024-04-16 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with a new HT account
3. Create a new WS
4. Add 6 non-existent users to the created WS
5. Navigate to the LHN chat menu
6. Go back to the list of WS members

## Expected Result:
Added non-existent members in WS should be displayed in the list of members with their login and work chats with them should be displayed by their login

## Actual Result:
Added non-existent members in WS disappear from the list of members, go to "Hidden" status after update, work chats with them are shown as "Chat Report" until you update them

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d8c1f298-2198-471c-808c-661789476972

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012892de41a5162e21</li>
        <li>Upwork Job ID: 1780450224453574656</li>
        <li>Last Price Increase: 2024-04-17</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-16 16:21
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-04-16 16:21
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-04-17 04:16
@lanitochka17 my staging version is v1.4.61-8 and I can't repro this. Going to see if C+ can.

**Comment by jliexpensify** [comment] 2024-04-17 04:17
Hi @mananjadhav - any chance you can repro this? My staging is not 1.4.62-10, is yours? Thanks!

**Comment by brunovjk** [comment] 2024-04-17 11:15
We're working on ["Allow arbitrary users to be added/removed to/from workspace chat via @mention or members list"](https://github.com/Expensify/App/issues/35391) and I'm facing the same issue. I believe it has to do with the server response.

**Comment by jliexpensify** [comment] 2024-04-18 03:48
Thanks @brunovjk - assigning @jasperhuangg for his eyes on this issue.

**Comment by jasperhuangg** [comment] 2024-04-22 20:54
Hmm yes, this does seem like a back-end issue

**Comment by jasperhuangg** [comment] 2024-04-22 21:38
Hmm, it appears we are sending a personal details update, but the issue is that we don't consider the users that were created as "known" to the current user.

I'm unable to reproduce the issue where the users just disappear from workspace members list on dev, but I'm able to reproduce it on staging.

**Comment by jasperhuangg** [comment] 2024-04-22 21:43
Very strange, it appears when adding a single non-existing user, it works, but if you try to add multiple non-existent users, then `isKnown` is returned as false so we don't send their full personal details.

**Comment by jasperhuangg** [comment] 2024-04-22 22:15
@brunovjk @mananjadhav @jliexpensify 

There seem to be two issues at play here:
- Invited non-existent users disappear from the members list shortly after being invited
- Invited non-existent users show as "Hidden" in the members list after being invited

I raised a PR to fix the latter, but I wasn't able to reproduce the former in dev. Let's wait to see after my PR is deployed to staging to see if anything changes.

**Comment by brunovjk** [comment] 2024-04-22 23:06
> I wasn't able to reproduce the former in dev.

I can reproduce both issues on our [PR](https://github.com/Expensify/App/pull/40220):
- Navigate to Workspace chat > Details page > Members > Invite button > Add an unknown user

**Invite:**
![Invite Screenshot](https://github.com/Expensify/App/assets/95647348/3d03013b-6cb0-4395-80fd-7a3e8479506e)

**Shortly after:**
![Shortly After Screenshot](https://github.com/Expensify/App/assets/95647348/9845c135-cd93-4e65-a61c-1d3256c570ad)

**Comment by jasperhuangg** [comment] 2024-04-22 23:11
@brunovjk thanks for that. You are able to reproduce because your dev environment points to our staging servers.

Might be another issue that I'll look into. For now let's wait for my changes to hit staging to see if you can still reproduce.

**Comment by brunovjk** [comment] 2024-04-22 23:13
Nice 🙂 thank you 🚀

**Comment by brunovjk** [comment] 2024-04-25 12:16
I can no longer reproduce on the latest main 🙂 **v1.4.65-5 (04/25)**
Can we check please? Thanks.

**Comment by brunovjk** [comment] 2024-04-25 18:36
I can no longer reproduce.

_"I think this should have been fixed in https://github.com/Expensify/Web-Expensify/pull/41771"_

**Comment by brunovjk** [comment] 2024-04-25 18:36
I can no longer reproduce.

**Comment by jliexpensify** [comment] 2024-04-25 23:24
Thanks for checking @brunovjk - going to close this one now. Job removed from Upworks.

**Closed by jliexpensify** 2024-04-25 23:24 UTC
Labels: Reviewing, Daily, Internal, Bug
