### ISSUE TITLE
[HOLD for payment 2023-10-09] [HOLD App#28154] [$500] Chat - Editing composer is closed when saving empty message in thread first chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27605] opened 2023-09-16 20:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Add a comment
3. Click to reply in thread
4. Edit the first chat of thread
5. Click to save empty message and delete confirm dialog pop up
6. Notice the editing composer is closed

## Expected Result:
 The background editing composer shouldn't be closed

## Actual Result:
 The background editing composer is closed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.70-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/baa51548-fee8-4ab4-b254-824eaea65756

https://github.com/Expensify/App/assets/78819774/d84c9641-6c9c-4c24-b63b-4e22371ef1ca

**Expensify/Expensify Issue URL:**

**Issue reported by:** @eh2077

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694791088007549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e90a30ac9429cad3</li>
        <li>Upwork Job ID: 1703145967100735488</li>
        <li>Last Price Increase: 2023-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 26851327</li>
<li>eh2077 | Reporter | 26851330</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-09-16 21:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Edit composer is closed on the first message in a thread when attempting to save an empty message.

### What is the root cause of that problem?
There is an attempt to save the draft in the `publishDraft` method of the ReportActionItemMessageEdit component. Calling this saveReportActionDraft causes the edit composer to close, even when the new message draft is empty.

### What changes do you think we should make in order to solve the problem?
Add a condition to check if the new message is empty before trying to save the draft.
```diff
-if (props.action.childReportID) {
+if (props.action.childReportID && trimmedNewDraft.length > 0) {
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by c3024** [comment] 2023-09-17 14:19
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Editing composer is closed when parent message of a thread is removed in editing composer and saved.
### What is the root cause of that problem?
These here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L274-L284
set draft messages for parent message action in the parent report, and thread report.
When we edit the parent message this here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ContextMenu/ContextMenuActions.js#L293
sets the draft message for ``${ONYXKEYS.COLLECTION.REPORT_ACTIONS_DRAFTS}${props.action.childReportID}_${props.action.reportActionID}``
Since the edited comment is a parent action, it has a child report and this condition here 
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L280
is `true` and this here 
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L281
is also `true` because of the draft message set in the `editAction` code.
Once the draft message is set to empty this here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItem.js#L365
is `true` and 
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItem.js#L367
here appears in place of this here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItem.js#L398
that is the editing composer disappears.
### What changes do you think we should make in order to solve the problem?
We should move this
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L286-L291
up here
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/home/report/ReportActionItemMessageEdit.js#L270
so that if `trimmedDraft` is empty we do the deleting action and return early before setting the draft messages preventing consequent change from `ReportActionItemMessageEdit` to `ReportActionItemMessage` as specified above.
### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-09-19 02:35
@thesahindia can you give these two proposals a look when you get a chance?

**Comment by garrettmknight** [comment] 2023-09-21 10:46
Bumping in slack.

**Comment by mountiny** [comment] 2023-09-25 07:04
Feel free to raise the PR please

**Comment by c3024** [comment] 2023-09-25 15:36
PR ready for review @thesahindia

**Comment by situchan** [comment] 2023-09-26 10:24
Heads up: In https://github.com/Expensify/App/pull/28154, we're removing all codes introduced in https://github.com/Expensify/App/pull/23706 which caused this regression.
So after https://github.com/Expensify/App/pull/28154, this will be no longer reproducible.

**Comment by mountiny** [comment] 2023-09-26 10:26
Yoinks, in that case we should probably go with the standard 25% reward for the efforts here.

**Comment by garrettmknight** [comment] 2023-10-09 17:44
@mountiny / @thesahindia just making sure I've got this one right: 
- @c3024 got a PR up, we haven't reviewed it because this was a result of a regression that should have been fixed in [this PR](https://github.com/Expensify/App/pull/28154)
- @eh2077 should still get paid for reporting
- @c3024's PR isn't necessary so we won't pay for it in this issue
- @thesahindia hasn't reviewed the PR so we won't pay for it in this issue

Melv got a little trigger happy with payment on this issue for a separate PR, just confirming.

**Comment by c3024** [comment] 2023-10-09 17:48
I think 25% is paid because the issue was assigned and PR was made. @garrettmknight

**Comment by garrettmknight** [comment] 2023-10-09 17:53
Got it - so this is a partial pay scenario for C/C+. I think that makes sense. @c3024 can you test and make sure this bug is no longer happening? If it is, then we still might end up fixing with a separate solution.

**Comment by mountiny** [comment] 2023-10-09 17:53
@garrettmknight Per [this comment](https://github.com/Expensify/App/issues/27605#issuecomment-1735260469), @c3024 should get $125 for their proposal and PR even if we did not end up using it. The fact there fwas a third party PR which changed the behaviour was unexpected

**Comment by garrettmknight** [comment] 2023-10-11 19:27
**Summary of payments for this issue:**
- Reporter: @eh2077 $50 paid via Upwork
- Contributor: @c3024 $250 paid via Upwork
- Reviewer: @thesahindia $250

Upwork Job: https://github.com/Expensify/App/issues/27605

**Comment by garrettmknight** [comment] 2023-10-16 14:20
@thesahindia I think you're eligible for payment in NewDot right?

**Comment by garrettmknight** [comment] 2023-10-16 16:05
Dropping to weekly while @thesahindia requests payment.

**Comment by JmillsExpensify** [comment] 2023-10-25 17:03
$125 payment approved for @thesahindia based on BZ summary.

**Comment by garrettmknight** [comment] 2023-10-27 17:57
Cool, closing!

**Closed by garrettmknight** 2023-10-27 17:57 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
