### ISSUE TITLE
 Android - Chat - The compose box opens momentarily when user starts typing the message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19209] opened 2023-05-18 20:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the App.
2. Login with any account.
3. Open any chat.
4. Start typing the message

## Expected Result:
Should be no issue when user is typing the message

## Actual Result:
The compose box opens momentarily when user starts typing the message. 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/206f70beb59ca146a4b2350bbd2c100cad4a1d99f2a9af5ed6d59f81a112a2d1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2023-05-19 21:13
Going to try reproducing this on staging now

**Comment by roryabraham** [comment] 2023-05-19 21:18
I'm not able to reproduce this on my Pixel 4a.

**Comment by roryabraham** [comment] 2023-05-19 21:19
Going to close this

**Closed by roryabraham** 2023-05-19 21:19 UTC
Labels: DeployBlockerCash, Engineering, Hourly
