### ISSUE TITLE
[HOLD for payment 2024-11-28] [$250] Onboarding task - `Take me to...` link contains -1 instead of WS ID and opens not here page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52236] opened 2024-11-08 08:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5195696
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/ and log in with a new account
2. Select "Get paid back from my employer" and enter a name
3. Click on FAB > Submit expense
4. Submit a manual expense to a new user
5. Log out and log in as the other user
6. Navigate to the 1:1 chat with the expense submitter
7. Click on Pay with Expensify > Business bank account
8. Close the Connect bank account RHP
9. Navigate to Concierge
10. Open an onboarding task with a link to WS settings, e.g. "Set up categories"
11. Click on the link "Take me to..."

## Expected Result:
The link contains the Workspace ID, and user is navigated to the corresponding workspace settings

## Actual Result:
The link contains -1 instead of the Workspace ID, and user is navigated to the "Not here" page

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
  
https://github.com/user-attachments/assets/1604f7e4-e14a-4255-a64b-e79f820da8a3
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021856146440240693847</li>
        <li>Upwork Job ID: 1856146440240693847</li>
        <li>Last Price Increase: 2024-11-12</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104903064</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by mkzie2** [comment] 2024-11-08 09:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The link contains -1 instead of the Workspace ID, and user is navigated to the "Not here" page

### What is the root cause of that problem?

When we select `Bussiness bank account`, we complete onboarding here with `onboardingPurpose` as `CONST.ONBOARDING_CHOICES.MANAGE_TEAM`

https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/components/AddPaymentMethodMenu.tsx#L120


https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/libs/actions/IOU.ts#L7676-L7679

Then we call `completeOnboarding` without `onboardingPolicyID` which causes the setting tag/category to have the WS link with ID `-1`

https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/libs/actions/IOU.ts#L7684
### What changes do you think we should make in order to solve the problem?
We can add a new prop in `AddPaymentMethodMenu` `shouldCallCompletePaymentOnboarding` with the default value as `true` and only call `completePaymentOnboarding` in this component if `shouldCallCompletePaymentOnboarding` is `true`

After that, we can pass  `shouldCallCompletePaymentOnboarding={false}` [here](https://github.com/Expensify/App/blob/17cae112dd45a4cb80b8dbbab020102f70ba7407/src/components/KYCWall/BaseKYCWall.tsx#L231) 

And we will call `completePaymentOnboarding` in each case of `selectPaymentMethod` function and pass `onboardingPolicyID` to `completePaymentOnboarding` function if we create a new policy.

https://github.com/Expensify/App/blob/17cae112dd45a4cb80b8dbbab020102f70ba7407/src/components/KYCWall/BaseKYCWall.tsx#L101

https://github.com/Expensify/App/blob/17cae112dd45a4cb80b8dbbab020102f70ba7407/src/components/KYCWall/BaseKYCWall.tsx#L111

### What alternative solutions did you explore? (Optional)
In this function here, we can check if we don't have any policy that we're owner, we will call `Policy.createWorkspace` function and get the policyID, adminReportID to pass to `completeOnboarding` [here](https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/libs/actions/IOU.ts#L7684)

https://github.com/Expensify/App/blob/c658375530adce8cf24d641523556a91712e741d/src/libs/actions/IOU.ts#L7676-L7679

**Comment by trjExpensify** [comment] 2024-11-12 01:26
@deetergp @blazejkustra this is a bug with the Guided Setup: Stage 3. Do you agree with the approach here?

**Comment by deetergp** [comment] 2024-11-12 23:46
Yes, that approach makes sense to me. @eh2077 does it make sense to you?

**Comment by eh2077** [comment] 2024-11-13 00:23
@deetergp Thanks for looking into this. Yes, the proposal looks good. But I can't reproduce the issue following the reproduction steps. In step 7, there's only `Pay elsewhere` option and no option to pay with Expensify.

<img width="1431" alt="image" src="https://github.com/user-attachments/assets/798c4a2a-6a5e-4651-85a4-eebeb9e0435b">

@mkzie2 Are you still able to reproduce it? Or am I missing something

**Comment by mkzie2** [comment] 2024-11-13 02:15
@eh2077 `Business bank account` option only appears with the default currency `USD`. You can change this in the personal workspace in OD.

**Comment by eh2077** [comment] 2024-11-14 14:47
I managed to reproduce this issue with the above advice! 

I agreed with @mkzie2 's RCA and their solution makes sense to me.

🎀👀🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2024-11-20 14:28
PR hit staging a couple of days ago, should start the clock today.

**Comment by trjExpensify** [comment] 2024-11-28 13:49
👋 time for the checklist please!

**Comment by trjExpensify** [comment] 2024-12-02 13:10
@eh2077, still awaiting the checklist to process payments here.

**Comment by eh2077** [comment] 2024-12-03 13:04
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by trjExpensify** [comment] 2024-12-03 16:38
Thanks! As for the regression test, I think we should incorporate navigating from that link in one of @deetergp's: https://github.com/Expensify/Expensify/issues/449586

**Comment by trjExpensify** [comment] 2024-12-03 16:40
Payment summary as follows: 

- $250 to @mkzie2 for the fix (paid!)
- $250 to @eh2077 for the C+ review (Go ahead and request!)

Closing, thanks!

**Closed by trjExpensify** 2024-12-03 16:40 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-12-05 13:20
$250 approved for @eh2077
