### ISSUE TITLE
[$1000] While editing a message, the text and cursor extend beyond the boundary of the composer box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23882] opened 2023-07-30 17:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to https://staging.new.expensify.com/
2. Go to any chat
3. Send a long message like : Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
4. Edit the message and then scroll down
5. Observe that the message and cursor extend outside the boundaries of the composer box
## Expected Result:
The behavior should remain consistent
## Actual Result:
The behavior is inconsistent
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e5a7cf86-7f8b-44ce-a4e0-ad42b35bc1e3

https://github.com/Expensify/App/assets/43996225/d8b2e371-8910-40ca-a2b2-a7dd9d5ee094

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690456226212329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ccd5c01b74ddbae</li>
        <li>Upwork Job ID: 1686253425295224832</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-07-30 17:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While editing a message, the text and cursor extend beyond the boundary of the composer box
### What is the root cause of that problem?
There is no `styles.overflowHidden` style in composer box here
https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/home/report/ReportActionItemMessageEdit.js#L301-L307
### What changes do you think we should make in order to solve the problem?
we need to add style `styles.overflowHidden` to composer box [here](https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/pages/home/report/ReportActionItemMessageEdit.js#L301-L307) or [here](https://github.com/Expensify/App/blob/975146fa30bc65a19df8e0cca525af32ce2ceda5/src/styles/styles.js#L1579)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by JmillsExpensify** [comment] 2023-08-01 05:51
I'm having a hard time following the reproduction steps, though I do agree that the behavior is different, even if I think this bug is very low value.

**Comment by Pujan92** [comment] 2023-08-01 06:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the edit message textarea text goes beyond the curved boundary

### What is the root cause of that problem?
We are giving the border-radius of `24px` and the left padding for the text is `12px` which seems to be the issue as the text starts from the curved area.

### What changes do you think we should make in order to solve the problem?
Either we need to reduce the border-radius to around `16px` or we can increase the left padding around `16px` for the text to make it start from the straight boundary of the border.

**Comment by nileshahir286** [comment] 2023-08-01 06:41
### **Proposal**
### **Please re-state the problem that we are trying to solve in this issue.**
Edit a message, text and cursor extend beyond the boundary of the composer box

### **What is the root cause of that problem?**
Need to give styles.overflowHidden style in composer box

### **What changes do you think we should make in order to solve the problem?**
Just need to add style styles.overflowHidden.

**Comment by nileshahir286** [comment] 2023-08-01 06:43
> My Expensify Account Email : [nileshahir286@gmail.com](mailto:nileshahir286@gmail.com)
> 
> My Upwork Profile : https://www.upwork.com/freelancers/~0126f3665fe23ff297?s=996364627857502209
> 
> ### **Proposal**
> ### **Please re-state the problem that we are trying to solve in this issue.**
> Edit a message, text and cursor extend beyond the boundary of the composer box
> 
> ### **What is the root cause of that problem?**
> Need to give styles.overflowHidden style in composer box
> 
> ### **What changes do you think we should make in order to solve the problem?**
> Just need to add style styles.overflowHidden.

I have update the Contributor details.

**Comment by nileshahir286** [comment] 2023-08-01 06:46
> 📣 @nileshahir286! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Updated the proposal

**Comment by JmillsExpensify** [comment] 2023-08-08 03:40
How are the reviews going?

**Comment by JmillsExpensify** [comment] 2023-08-16 13:44
I'm not sure I agree that both should be fixed. This isn't the final state of the text input.

**Comment by ahmedGaber93** [comment] 2023-08-28 16:18
> cursor bubble beyond the boundary

@aimane-chnaif 
I am not understanding what is the expected result for cursor bubble?
I think it should be beyond the boundary, and it is in all inputs in the app

the new message composer
![Screenshot 2023-08-28 at 6 16 15 PM](https://github.com/Expensify/App/assets/41129870/c7611606-8056-4e52-8ca7-5eb3fd819a94)

search input
![Screenshot 2023-08-28 at 6 16 57 PM](https://github.com/Expensify/App/assets/41129870/2c3a8b4b-60b2-4c13-9ca5-d5c9b377d21b)

**Comment by ahmedGaber93** [comment] 2023-08-29 09:39
The both edit and main composer behavior is to display the cursor bubble, but the issue appears in the edit composer became the corner.

I think we can add padding left 24 equal border radius to fix this.

I am trying to set high border radius and overflowX hidden to the input but the cursor bubble not affect by any of them.
 
![Screenshot 2023-08-29 at 11 33 35 AM](https://github.com/Expensify/App/assets/41129870/d4c8595e-e036-44d8-8595-0a2e626506ed)

**Comment by JmillsExpensify** [comment] 2023-09-07 02:13
@aimane-chnaif ok that's fair. Before we move forward, let's get some input from @Expensify/design about whether that latest proposal above is the direction we want to go.

**Comment by shawnborton** [comment] 2023-09-07 13:45
Hmm I am curious why this would even be happening? If you look closely, the textarea is within the border of the composer wrapper itself:
<img width="1023" alt="image" src="https://github.com/Expensify/App/assets/2319350/38072a9b-7449-4761-85a3-158050c160af">

**Comment by shawnborton** [comment] 2023-09-07 13:50
Oh, I see how - it's the edit message box and not the original composer. 
<img width="417" alt="image" src="https://github.com/Expensify/App/assets/2319350/8ced8e3e-10cd-4500-ad5f-c0432613b09f">

So I think what we should do is remove the padding from this textarea and just add it to the immediate parent wrapper:
<img width="1192" alt="image" src="https://github.com/Expensify/App/assets/2319350/f87cf6ef-de20-4989-a7a5-ca04aa895315">


Also, does this count as a regression? As in, rather than treat this like a new bug, let's work with the contributor who implemented comment editing and ask them to fix it.

**Comment by ahmedGaber93** [comment] 2023-09-07 16:17
> So I think what we should do is remove the padding from this textarea and just add it to the immediate parent wrapper:

@shawnborton I think this will crop the text before reach to the bottom because we have padding bottom 5px, and if we move the horizontal padding only to the textarea, the issue still reproduced.

![Screenshot 2023-09-07 at 6 05 48 PM](https://github.com/Expensify/App/assets/41129870/b2738dcc-adef-41aa-8574-7a63cf8b4e97)


What do you think of adding padding left 24 equal border radius to fix this?

**Comment by shawnborton** [comment] 2023-09-07 16:39
Got it, if that's the case, I would only apply the horizontal padding to the outer wrapper, and keep the vertical padding on the textarea itself. We might also need to add 1px of vertical padding to the wrapper to prevent the weird overlap on the border, right?

**Comment by ahmedGaber93** [comment] 2023-09-07 18:01
@shawnborton 
Applying padding vertical 1px for the wrapper prevent the weird overlap from the bottom corner but it still in top corner.
Tested in web chrome, do you have the result?

![Screenshot 2023-09-07 at 7 55 38 PM](https://github.com/Expensify/App/assets/41129870/bf9f7734-cd65-4a27-a5d7-be69948cfcd2)

**Comment by Pujan92** [comment] 2023-09-07 19:35
@shawnborton how about reducing the border-radius for it? bcoz currently due to high border-radius the curve is long and that causing the issue.

| Issue  | Reduce border-radius to 16 from 24 |
| ------------- | ------------- |
|  <video src="https://github.com/Expensify/App/assets/14358475/de12b83f-395d-4250-86d2-55ec21a30e3c">  | <video src="https://github.com/Expensify/App/assets/14358475/21b9f6a9-1660-454b-8b10-6b9ab83057c8">  |

**Comment by shawnborton** [comment] 2023-09-08 12:58
I don't think we should reduce the border radius because then we get some funkiness happening on the bottom right near the send button:
<img width="192" alt="image" src="https://github.com/Expensify/App/assets/2319350/985ad9a1-e38a-48e8-b4ac-363c2f96c051">

**Comment by Pujan92** [comment] 2023-09-08 13:10
> I don't think we should reduce the border radius because then we get some funkiness happening on the bottom right near the send button: <img alt="image" width="192" src="https://user-images.githubusercontent.com/2319350/266617528-985ad9a1-e38a-48e8-b4ac-363c2f96c051.png">

Oh, yes. Other option which I am suggesting is to increase the padding either horizontally from both sides or only on the left.

https://github.com/Expensify/App/assets/14358475/8b48293f-d84b-46da-a573-18bbaf2258d2

**Comment by shawnborton** [comment] 2023-09-08 13:18
Hmm but I am confused, I actually don't see the same thing you are seeing. You are showing this:
<img width="162" alt="image" src="https://github.com/Expensify/App/assets/2319350/69c212d9-6a99-4805-b0b9-9efa9af9f3ab">


Whereas I see this on desktop:
<img width="261" alt="image" src="https://github.com/Expensify/App/assets/2319350/0fc9fdb4-b068-4bb9-9751-4481d057c467">

Shouldn't that bottom padding prevent that weird overlap from happening?

**Comment by Pujan92** [comment] 2023-09-08 13:33
I think you have selected the text only whereas I am hovering on the entire div to highlight.

https://github.com/Expensify/App/assets/14358475/c215f8d5-e2fb-4326-abaf-6d8ab93b4c8c

**Comment by shawnborton** [comment] 2023-09-08 13:40
Ah, got it, I did not have enough text. I see it now:
<img width="264" alt="image" src="https://github.com/Expensify/App/assets/2319350/38a5f1fd-18a1-4a63-aafd-8483e8a3e951">


But wow, I am wondering if this is even worth worrying about? Like this feels virtually undetectable by most users, I don't think most people would see this and think "wow, this is a design bug that was not considered" - cc @Expensify/design for thoughts here too. 

Otherwrise yes, I think we would want to increase the left padding to accommodate this.

**Comment by JmillsExpensify** [comment] 2023-09-13 08:04
Still working through the proposal/solution.

**Comment by Pujan92** [comment] 2023-09-13 11:38
> Otherwrise yes, I think we would want to increase the left padding to accommodate this.

If we consider this then I have proposed to add left padding in my alternate solution. 
After providing `20px` left padding

https://github.com/Expensify/App/assets/14358475/c3b285b5-ff53-40c6-a9ea-23587b39992b

**Comment by ahmedGaber93** [comment] 2023-09-13 15:24
My original proposal using `styles.overflowHidden` will fix the main issue, and alternatively we can use padding left to include fixing "cursor bubble beyond the boundary" (I am the first proposed fix using padding left here https://github.com/Expensify/App/issues/23882#issuecomment-1697103396).
Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-10 20:31
> Ah, got it, I did not have enough text. I see it now: <img alt="image" width="264" src="https://user-images.githubusercontent.com/2319350/266627699-38a5f1fd-18a1-4a63-aafd-8483e8a3e951.png">
> 
> But wow, I am wondering if this is even worth worrying about? Like this feels virtually undetectable by most users, I don't think most people would see this and think "wow, this is a design bug that was not considered" - cc @Expensify/design for thoughts here too.
> 
> Otherwrise yes, I think we would want to increase the left padding to accommodate this.

Coming back to this comment from Shawn, I think he's right. This isn't worth worrying about and we should close this report.

**Closed by JmillsExpensify** 2023-10-10 20:31 UTC
Labels: Weekly, Internal, Bug
