### ISSUE TITLE
[$500] Web - App opens search page in background when 'Update to USD' popup is open and closes both on ESC

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27686] opened 2023-09-18 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->workspaces->any workspace->settings
3. Change currency to any other then USD
4. Click on back and click on bank account
5. When 'Update to USD' popup is open, press CTRL+K/CMD+K to open search page
6. Observe that popup is not closed and search page is opened in background
7. Click on ESC and observe that both popup and RHN closes

## Expected Result:
App should close Update to USD popup when we open search page by shortcut

## Actual Result:
App does not close Update to USD popup when we open search page by shortcut, opens the page in background and closes both the popup and RHN on ESC

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/061d51bb-1326-4710-97db-33496484e20f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694760915670659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124302e7a606f239a</li>
        <li>Upwork Job ID: 1703788221086208000</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by dhanashree-sawant** [comment] 2023-09-18 15:29
Solution video:

https://github.com/Expensify/App/assets/87513216/da7c9216-d1d3-43bd-8586-b0925ff12657

**Comment by trjExpensify** [comment] 2023-09-19 11:16
@sophiepintoraetz assigned first, dropping off.

**Comment by Pluto0104** [comment] 2023-09-21 14:58
hmm, I can't reproduce it.

**Comment by sophiepintoraetz** [comment] 2023-09-25 11:22
@cubuspl42 - are you able to reproduce/review the propsal?

**Comment by cubuspl42** [comment] 2023-09-25 11:44
@sophiepintoraetz I'm not able to reproduce

**Comment by sophiepintoraetz** [comment] 2023-09-25 11:47
Cool, closing. Thank you @cubuspl42!

**Closed by sophiepintoraetz** 2023-09-25 11:47 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
