### ISSUE TITLE
[HOLD] [$1000]  iOS: Paypal.me payment method disappears when deleting a PayPal user name offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22064] opened 2023-07-02 18:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings then choose Payments
2. Click on Add payment method button.
3. Choose paypal.me
4. Now turn off your internet connection and be offline
5. Insert user name and click on Add Paypal Account
6. Now click the account you added and Delete the account.
7. Now turn on your internet connection and be online.
8. Now click the Add Payment Method button. Notice that the paypal.me choice is not there.
## Expected Result:
Paypal.me payment method should be there
## Actual Result:
Paypal.me payment method is not there
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c99fa0d0-a602-403c-bbb2-164e1c72d390

https://github.com/Expensify/App/assets/43996225/20e18049-504a-4e5d-8e43-948b1797df3b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687805526273609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01424c2ea7e73e9df8</li>
        <li>Upwork Job ID: 1675717205927723008</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-07-03 04:04
Reproduced!
https://github.com/Expensify/App/assets/42940078/48928ec1-d6e8-4812-a3d2-6bb3bf9201df

**Comment by asadath1395** [comment] 2023-07-03 06:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paypal.me payment method disappears when deleting a PayPal user name offline

### What is the root cause of that problem?
Its happening because of wrong `optimisticData`. When the user is online and he tries to delete the Paypal.me method, the following is the API response we get
```
  {
      "jsonCode": 200,
      "requestID": "7e0cf514bf8c2fe3-CNN",
      "onyxData": [
          {
              "onyxMethod": "set",
              "key": "paypal",
              "value": null
          }
      ]
  }
```
but in the code we have the following optimistic data https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/actions/User.js#L535-L541
We can see that the `onyxMethod` and `value` is not matching with the API response. Because of wrong optimistic data, the list is getting filtered here https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/settings/Payments/PaymentMethodList.js#L149-L154 because the `pendingAction` is set to `CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE`

### What changes do you think we should make in order to solve the problem?
We can update the optimistic data to match the API response

### What alternative solutions did you explore? (Optional)
NA

**Comment by manjesh-yadav** [comment] 2023-07-03 06:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paypal.me payment method disappears when deleting a PayPal user name offline 
### What is the root cause of that problem?

- We add Paypal.me in offline mode and then Delete the same Paypal.me in offline mode.
- That makes two API calls persisted to disk `addPaypalMeAddress` and `deletePaypalMeAddress`
- When we go online that two API call simultaneously

Unfortunately, we use `Onyx.merge` for `addPaypalMeAddress` and `Onyx.set` for  `deletePaypalMeAddress` with same key Onyx key `paypal` but **it is recommended use set or merge at once not both**

<img width="1433" alt="Screenshot 2023-07-03 at 11 47 24 AM" src="https://github.com/Expensify/App/assets/70934016/1e14c95f-a499-40a8-971e-a899d9bb46b3">


Actually, we use `Onyx.set` for `deletePaypalMeAddress` for solving [issue](https://github.com/Expensify/App/issues/17795)  in [PR](https://github.com/Expensify/App/pull/17903#discussion_r1175763081)

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/libs/actions/User.js#L542-L550

### What changes do you think we should make in order to solve the problem?

#### Solution 1
We can also use `Onyx.METHOD.SET (Onyx.set)` for `addPaypalMeAddress` to avoid conflict.

#### Soluciton 2
I check we hide add payment method button in offline mode for the Debit card and Bank accounts we can also hide it for `Papal.me` to avoid conflict.


### What alternative solutions did you explore? (Optional)
Hide payment method for `Papal.me` in offline mode

**Comment by pradeepmdk** [comment] 2023-07-03 06:45
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Paypal.me payment method disappears when deleting a PayPal user name offline

### What is the root cause of that problem
When offline mode add the paypal method and delete after that coming to online onyx set or merge conflict throwing the error so that set not happen
<img width="828" alt="Screenshot 2023-07-03 at 12 12 06 PM" src="https://github.com/Expensify/App/assets/16595846/27a4928f-712d-40b2-8aac-0c8156ea9dcb">

<img width="1433" alt="Screenshot 2023-07-03 at 12 10 38 PM" src="https://github.com/Expensify/App/
<img width="608" alt="Screenshot 2023-07-03 at 12 14 01 PM" src="https://github.com/Expensify/App/assets/16595846/67de36f2-1fb1-41ee-9b8a-53e6a87921d0">
assets/16595846/aa674505-60c0-4c15-9ace-34fbb9bed4fc">
em?


### What changes do you think we should make in order to solve the problem?
we need merge the data
<img width="825" alt="Screenshot 2023-07-03 at 12 14 15 PM" src="https://github.com/Expensify/App/assets/16595846/3359f4f2-1330-4a6f-a7dd-dc2988593f82">



### What alternative solutions did you explore? (Optional)
N/A

**Comment by s77rt** [comment] 2023-07-03 22:18
@asadath1395 Thanks for the proposal. Your RCA is correct. The first solution would work but it's basically a revert of https://github.com/Expensify/App/pull/17903 which will reintroduce https://github.com/Expensify/App/issues/17795. The second solution is not clear i.e. what data should we work with and which method?

**Comment by s77rt** [comment] 2023-07-03 22:23
@manjesh-yadav Thanks for the proposal. Your RCA is correct. The first solution (same note as above ^) it's a revert of https://github.com/Expensify/App/pull/17903 which will reintroduce https://github.com/Expensify/App/issues/17795. We would still need to fix https://github.com/Expensify/App/issues/17795 if we go with the revert approach. The second solution does not seem much relevant here, how would that fix the root cause, we would still be using two different Onyx methods.

**Comment by s77rt** [comment] 2023-07-03 22:29
@pradeepmdk Thanks for the proposal. Your RCA is correct. Your suggested solution makes sense but it's hard to maintain every object key. I think we should clear the object root directly instead of clearing each key separately. This may require some data restructure.

**Comment by pradeepmdk** [comment] 2023-07-04 03:06
@s77rt  yes. we can use the root key for this.

**Comment by s77rt** [comment] 2023-07-04 16:39
@pradeepmdk Can you please elaborate how would that work? Merging an empty object seems to be a noop.

**Comment by s77rt** [comment] 2023-07-04 16:45
@asadath1395 I'm not sure we are looking at the same issue. That issue is about order inconsistency while this one is about the SET method not taking effect at all and we get a thrown error. I think we should try to avoid mixing the methods for now as mixed methods (for same key) does not seem to be supported (it's more like limitation than a bug).

**Comment by pradeepmdk** [comment] 2023-07-05 05:49
> @pradeepmdk Can you please elaborate how would that work? Merging an empty object seems to be a noop.

@s77rt   I thought it will work... but still merging with object only. because when come to online two more api call happen 
`ReconnectApp ` and `OpenPaymentsPage ` that also having the paypal key with merge. so object only merged.
`    const successData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PAYPAL,
            value: '',
        },
    ];
`
as per the documentation, we can't use both. when come online due to a conflict other api also has this key its happen.
![Screenshot 2023-07-05 at 10 42 11 AM](https://github.com/Expensify/App/assets/16595846/d7b03256-8d20-4981-9ac2-dd0b3e2af0cf)

### Alternative Solution
on delete success instead of set we can use merge with some key for identifying for API is success ex:
    const successData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PAYPAL,
            value: {deletedSuccess: true},
        },
    ];
after that using connect we can set an empty object

Onyx.connect({
    key: ONYXKEYS.PAYPAL,
    callback: (val) => {
        console.log(val);
        if(val && val.deletedSuccess) {
            Onyx.set(ONYXKEYS.PAYPAL, {});
        }
    },
});

**Comment by s77rt** [comment] 2023-07-05 13:14
@pradeepmdk Thanks for the update. I don't think the alternative solution is something that we should do, it looks too hacky.

**Comment by s77rt** [comment] 2023-07-08 01:28
Not overdue. Still looking for proposals...

**Comment by pradeepmdk** [comment] 2023-07-08 02:31
@s77rt 
another alternative solution 
actually, they are hiding the paypal.me option based on the `description` in the `AddPaymentMethodMenu.js.` on that, we can add one more condition this
` ...(props.shouldShowPaypal && (!props.payPalMeData.description || props.payPalMeData.pendingAction == CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE)`
in the same way we need empty the pendingAction on addpaypal address

<img width="635" alt="Screenshot 2023-07-08 at 8 00 34 AM" src="https://github.com/Expensify/App/assets/16595846/82ecc8d4-9d7a-4a49-aa26-f41eca96927d">

**Comment by s77rt** [comment] 2023-07-08 11:00
@pradeepmdk Thanks for the follow up. I don't see how is that solution fixing the root cause. Seems like a workaround.

**Comment by s77rt** [comment] 2023-07-11 23:13
Had a discussion here https://expensify.slack.com/archives/C01GTK53T8Q/p1689031771678159 where we encountered a similar onyx problem. I think we may just hold for https://github.com/Expensify/react-native-onyx/issues/266 but I'm not sure if that would actually fix the issue. Yet seems a safe call. cc @neil-marcellini

**Comment by pradeepmdk** [comment] 2023-07-12 16:34
@s77rt In the latest code we are facing new issue delete is not happing.when offline to online
https://github.com/Expensify/App/assets/16595846/4c5445f6-2380-4767-850d-adc06ea5e3bc

**Comment by s77rt** [comment] 2023-07-12 17:44
@pradeepmdk It could be related to the same issue. The onyx SET does not seem to take effect.

**Comment by sophiepintoraetz** [comment] 2023-07-14 15:07
@s77rt - so is your recommendation to hold or solicit more proposals or do both?

**Comment by s77rt** [comment] 2023-07-14 15:13
@sophiepintoraetz Let's hold for https://github.com/Expensify/react-native-onyx/issues/266

**Comment by sophiepintoraetz** [comment] 2023-07-24 21:56
Still holding.

**Comment by sophiepintoraetz** [comment] 2023-08-02 04:52
Still holding.

**Comment by s77rt** [comment] 2023-08-10 21:39
Still on hold

**Comment by sophiepintoraetz** [comment] 2023-08-21 20:07
Still holding

**Comment by s77rt** [comment] 2023-08-30 14:14
Still on hold. https://github.com/Expensify/react-native-onyx/issues/266

**Comment by pradeepmdk** [comment] 2023-08-31 12:09
I think PayPal going to deprecate https://github.com/Expensify/App/issues/26368

**Comment by sophiepintoraetz** [comment] 2023-09-05 01:39
Great spot - thanks @pradeepmdk

**Comment by sophiepintoraetz** [comment] 2023-09-05 01:47
[Checking in slack](https://expensify.slack.com/archives/C03U7DCU4/p1693878390761159)

**Comment by sophiepintoraetz** [comment] 2023-09-08 03:34
Closing, we are deprecating Paypal.

**Closed by sophiepintoraetz** 2023-09-08 03:34 UTC
Labels: External, Weekly, Help Wanted, Bug
