### ISSUE TITLE
Workspace - Error page appears when create Workspace with expensifail account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37549] opened 2024-02-29 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4350577
**Email or phone of affected tester (no customers):** applausetester+gm54@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create new Expensifail account
2. Go to Settings> Create Workspace

## Expected Result:
New workspace should be created with no errors

## Actual Result:
Error page appears when create Workspace with expensifail account

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9eb6126a-6eec-40ee-81e7-7258d22159d5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-29 18:17
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by twisterdotcom** [comment] 2024-03-01 12:16
Can't reproduce, must be fixed by v1.4.45-6.


https://github.com/Expensify/App/assets/9133401/abd7a4e0-94bb-4770-b970-872599a0c9d6

**Closed by twisterdotcom** 2024-03-01 12:16 UTC
Labels: Daily, Bug
