### ISSUE TITLE
[$500] Avatar - Avatar is blank instead of placeholder and no spinner when loading it offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33614] opened 2023-12-26 18:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go offline.
3. Tap Search.
4. Search for users with custom avatar.
5. Tap on the user with blank custom avatar.
6. Tap on the chat head
7. Tap on the avatar

## Expected Result:
In Step 4, users with custom avatar will show the avatar placeholder (production behavior - circular head with body with green background).
In Step 7, spinner will be shown when loading user avatar.

## Actual Result:
In Step 4, the users with custom avatar are blank and gray.
In Step 7, the spinner only appears for a split second.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1bb795f9-1885-4810-bf22-fdfbe273b064

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017c4e38b1b18578d0</li>
        <li>Upwork Job ID: 1739771161764048896</li>
        <li>Last Price Increase: 2024-01-23</li>
<li>Automatic offers: </li>
<ul>
<li>aswin-s | Contributor | 28129529</li>
<li>dukenv0307 | Contributor | 28135456</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by kbecciv** [comment] 2023-12-26 19:00
Issue is not reproducible on production

https://github.com/Expensify/App/assets/93399543/6dfa7f23-6f62-4471-aff0-c8d737879b54

**Comment by marcaaron** [comment] 2023-12-26 19:24
I guess either related to personal details or the search page. [This PR](https://github.com/Expensify/App/pull/33347/files) looks the most likely culprit, but have not reverted to test the theory yet.

**Comment by marcaaron** [comment] 2023-12-26 19:52
Oh hmm it could also be this ginormous expo image PR https://github.com/Expensify/App/pull/30905

**Comment by situchan** [comment] 2023-12-26 19:55
> Oh hmm it could also be this ginormous expo image PR #30905

I believe it. As this bug was tagged only on android/iOS.

https://github.com/Expensify/App/pull/33347 doesn't depend on platform

**Comment by marcaaron** [comment] 2023-12-26 20:06
I don't feel strongly that this needs to be a blocker. When you come back online the images are restored. But will leave it to the deployer to make the final decision.

**Comment by mountiny** [comment] 2023-12-26 22:12
I agree this is not a blocker, only happens on the native devices and works fine when online

@WojtekBoman @WoLewicki in case you could explore too

**Comment by shubham1206agra** [comment] 2023-12-27 08:40
@dukenv0307 Thanks for the proposal, but this solution will become way more tedious very quickly as you don't know where and when you need to fill color.

**Comment by shubham1206agra** [comment] 2023-12-27 08:42
@mountiny I will try to upgrade expo-image version to 1.9.0 as https://github.com/expo/expo/pull/25377 may fix these problems all at once

**Comment by shubham1206agra** [comment] 2023-12-27 08:52
> > And you can't control this through a prop
> 
> @shubham1206agra what do you mean by this? (we're already doing the same [here](https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/MenuItem.tsx#L229))
> 
Nope I am thinking about generalized approach. We may add a prop but this will quickly get into problems and will make the code complex, and also I see this as a workaround.

If you have another approach, feel free to update the proposal

**Comment by shubham1206agra** [comment] 2023-12-27 11:05
@dukenv0307 Can you create a test branch so we can know how complex the logic goes?

**Comment by bfitzexpensify** [comment] 2023-12-29 17:13
@eVoloshchak please review - thank you

**Comment by mountiny** [comment] 2023-12-29 19:34
SWM developers will be back from ooo in new year so I think its fine to wait for them to review

**Comment by WojtekBoman** [comment] 2024-01-02 12:43
Hello! I think that introducing the `displayInDefaultIconColor` prop to the `Avatar` component might be a good idea :) It can be used for example [here](https://github.com/Expensify/App/blob/320ff544570be797b018279693fcd44da8b838c7/src/components/MentionSuggestions.tsx#L75C1-L75C1). However, we should take into account one more case, which is when we want to display avatar for workspaces. In this situation we should use the default values defined inside the `Avatar` component. So, it can be solved in parent components by adding an additional check for workspace icon types: `displayInDefaultIconColor={icons[0].type !== CONST.ICON_TYPE_WORKSPACE},` (for example [here](https://github.com/dukenv0307/App/blob/739c22de8e2b16c94d5b164f3727fba3f8df970e/src/components/MultipleAvatars.tsx#L158C1-L158C1)) or inside the `Avatar` component. If we choose the first option, we will need to cover more places where the `Avatar` component displays workspace icons. On the images attached below can be noticed why we need this additional check in the `displayInDefaultIconColor` prop for workspaces (letter colors in workspace icons).
![Screenshot 2024-01-02 at 13 01 39](https://github.com/Expensify/App/assets/47774969/1f72c315-4870-401d-b0c7-879736ce3d19)
![Screenshot 2024-01-02 at 13 02 03](https://github.com/Expensify/App/assets/47774969/dc9c379d-bfe5-40de-88ea-35b7e367e76f).

**Comment by bfitzexpensify** [comment] 2024-01-02 16:31
@eVoloshchak will review when back from ooo this week, this is not urgent

**Comment by bfitzexpensify** [comment] 2024-01-09 17:57
@eVoloshchak bump on this one

**Comment by eVoloshchak** [comment] 2024-01-14 23:39
@dukenv0307, thanks for the [proposal](https://github.com/Expensify/App/issues/33614#issuecomment-1870073805)!

> In [here](https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/Avatar.tsx#L101), if there's image error, it's always filling the gray color to the icon. If the icon is Expensicons.FallbackAvatar, do not fill the gray color because that icon already has the color.

This does look like a workaround, I think there's potentially a better way to fix this

1. Was this problem preset before https://github.com/Expensify/App/pull/30905 was merged?
2. Why is this issue present only on native platforms?

**Comment by marcaaron** [comment] 2024-01-23 00:06
@eVoloshchak any thoughts on the above question from @dukenv0307?

**Comment by eVoloshchak** [comment] 2024-01-23 21:24
> An alternative is we can create an upstream fix so that if the SVG already contains fill, do not override it with the fill prop specified

@dukenv0307, I think this would be the best approach
That would also keep the behavior consistent across platforms, we would achieve the same behavior on native and web
Could you elaborate on how we would fix that in `expo-image`?

**Comment by aswin-s** [comment] 2024-01-24 18:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Fallback avatar is gray when network is offline on native devices

### What is the root cause of that problem?

On native devices we are using expo-image library to display svg Icons.

However for SVG icons fill prop is not supported by expo-image library. Instead for colored svg icons are acheived using the [tintColor Prop](https://docs.expo.dev/versions/latest/sdk/image/#tintcolor) of expo-image library. Any color passed via fill prop is passed over to image component as tintColor.

https://github.com/Expensify/App/blob/b0e2a92a3d856109b6cce916370ec8435770e2af/src/components/ImageSVG/index.native.tsx#L7

A downside of this approach is that tint gets applied over the entire svg shape. If there are multiple paths with different fill colors in the svg all of them will get overlaid by tintColor.



This is what is happening with fallback Avatar icon. When network is offline and image loading fails, `theme.offline` color is passed to FallbackAvatar as fill prop. 

https://github.com/Expensify/App/blob/db0d01bac3f6443fdb3d8b969fa31c0669b31efc/src/components/Avatar.tsx#L102

FallbackAvatar has two shapes within it, a circular path with fill `#085239` and a person shape with fill `#FFFFFF`. But since `offline.theme` tint is applied over the svg shape, entire shape gets tinted in a single color and looks like a solid circle.

![image](https://github.com/Expensify/App/assets/6880914/378dfeaa-70f5-4f83-9f80-bd56e56ec8bd)


This is the reason fallback avatar is blank when offline.


### What changes do you think we should make in order to solve the problem?

Two tone icons can be acheived by using an SVG image with a clipped inner shape. The result is that tintColor gets applied only to the outer shape and the inner shape shows the background color.

<img src="https://github.com/Expensify/App/assets/6880914/7f6a3405-b28c-4922-beab-1ce9eb8de6c1" width="500" />

<img src="https://github.com/Expensify/App/assets/6880914/dc3e798d-5395-4bd9-ad21-5ad560d66859" width="500"/>

We've used this approach to show hover and pressed states in menu items. So this is not a hack or a new technique per say.


| Normal |  Pressed In |
|--|--|
|![Screenshot 2024-01-24 at 11 38 21 PM](https://github.com/Expensify/App/assets/6880914/c537028e-8a93-4812-858b-16b5cd1d9e51) | ![Screenshot 2024-01-24 at 11 38 39 PM](https://github.com/Expensify/App/assets/6880914/1b2e616a-276f-4837-adbf-1b4fb9011d2b) |  


Similarly use a clipped SVG variant as fallback icon for `Expensicons.FallbackAvatar` & `WorkspaceBuilding` icon. This way the same effect could be achieved without any major code change. And it works seamlessly both on web and native platforms.

Here are the clipped variants of Avatar fallback and workspace fallback icons.

**fallback-avatar.svg**

```svg
<svg fill="none" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m40 20c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm-20-1c2.2 0 4-1.7998 4-4s-1.8-4-4-4-4 1.7998-4 4 1.8 4 4 4zm6.5 10c1.5 0 2.5-.5 2.5-2 0-4-4.5-7-9-7s-9 3-9 7c0 1.5.9 2 2.5 2h6.5z" fill="#8b9c8f" fill-rule="evenodd"/></svg>
```

**fallback-workspace-avatar.svg**

```svg
<svg fill="none" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="m40 20c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm-20-1c2.2 0 4-1.7998 4-4s-1.8-4-4-4-4 1.7998-4 4 1.8 4 4 4zm6.5 10c1.5 0 2.5-.5 2.5-2 0-4-4.5-7-9-7s-9 3-9 7c0 1.5.9 2 2.5 2h6.5z" fill="#8b9c8f" fill-rule="evenodd"/></svg>
```
Result

|| Light | Dark |
|--|--|--|
|Android|<img src="https://github.com/Expensify/App/assets/6880914/8cbf8e8d-a83a-42e3-b083-a9d756f2b4e5" width="300"/>| <img src="https://github.com/Expensify/App/assets/6880914/9293553a-1d99-4c79-846d-366359d2d97c" width="300"/>|
|Web |<img src="https://github.com/Expensify/App/assets/6880914/21b94685-33ab-4f74-b9c5-add3f4d72184" width="300"/>| <img src="https://github.com/Expensify/App/assets/6880914/09c0ee26-3abc-4c46-86fd-43c895dcecac" width="300"/>|


The background and foreground colors of the fallback icon could be adjusted by setting appropriate fill color and backgroundColor in Avatar component.


### What alternative solutions did you explore? (Optional)
None

**Comment by eVoloshchak** [comment] 2024-01-29 10:42
I think the most simple yet effective approach would be using @dukenv0307 [alternative solution](https://github.com/Expensify/App/issues/33614#issuecomment-1870073805)

> Or we can add a prop to control if we should fill the color for the icon or not, similar to the displayInDefaultIconColor prop [here](https://github.com/Expensify/App/blob/6365aebb9cdb3dd4a66e77117afd0fb1b1fa8957/src/components/MenuItem.tsx#L229), and only fill (or not fill) the color if the flag is added to Avatar. In the case of this issue it will be not to fill color. We need to make sure to account for the cases of workspace avatar https://github.com/Expensify/App/issues/33614#issuecomment-1873981305 as well, this can be handled during PR process.

@aswin-s, thank you for the [proposal](https://github.com/Expensify/App/issues/33614#issuecomment-1908741277)! This approach is also valid, achieving effectively the same result, but differently. I do think having a separate prop is easier (we don't have to make changes (clip) multiple SVG's and, most importantly, the problem won't pop up in the future when we device to use a different SVG)


🎀👀🎀 C+ reviewed!

**Comment by marcaaron** [comment] 2024-01-29 21:29
Oops. Assigned the wrong person. But @dukenv0307 is already working on quite a large PR. Can we have @aswin-s work on this one instead?

**Comment by aswin-s** [comment] 2024-02-01 09:17
@dukenv0307 It's all yours. Not planning to work on your proposal. @marcaaron Please reassign.

**Comment by marcaaron** [comment] 2024-02-01 20:03
Sounds good! Thanks for your flexibility everyone 🙇

**Comment by bfitzexpensify** [comment] 2024-02-07 05:37
Great, thanks @dukenv0307

**Comment by bfitzexpensify** [comment] 2024-02-12 01:03
Looks like the PR is still being worked on. Do you have an ETA @dukenv0307?

**Comment by eVoloshchak** [comment] 2024-05-21 13:59
@bfitzexpensify, a gentle bump on the above

**Comment by bfitzexpensify** [comment] 2024-05-21 14:05
Thanks for the bump @eVoloshchak. 

@marcaaron, do you think the work in https://github.com/Expensify/App/pull/35639 constitutes perhaps a half-payment out here?

**Comment by mallenexpensify** [comment] 2024-08-12 17:35
Reopened and made @bfitzexpensify the owner to get 👀, removed 'reviewing' too.

**Comment by bfitzexpensify** [comment] 2024-08-13 11:32
Reviewed again. Agree that there was a substantial amount of work, but I still think it missed the mark on urgency. Given that, I think a 50% payout is fair here.

Payment summary:

@dukenv0307 to be paid $250 for contributor work - offer sent via Upwork
@eVoloshchak to be paid $250 for C+ work via manual request

**Comment by bfitzexpensify** [comment] 2024-08-14 12:05
You're very welcome. Payment complete. Closing this out again.

**Closed by bfitzexpensify** 2024-08-14 12:05 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-08-19 15:53
$250 approved for @eVoloshchak
