### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Update Dropdown Button UI

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22540] opened 2023-07-10 07:52 UTC
Coming from: https://github.com/Expensify/App/issues/20486

before:
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/38015950/3c256d23-47ee-420f-831a-86fcb968e48e">

after (in mockup):
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/38015950/0f9e648e-7288-4118-8d39-ba19fded0cff">

Notes:
- [ ] Button height (40px)
- [ ] Divider line (1px, same color as text, 28px height)
- [ ] Caret is still 20x20 px
- [ ] Same flex styling, here's an example on an expense report view. 

![image](https://github.com/Expensify/App/assets/38015950/9f258e47-c4ca-422e-8a14-b30fae875c3f)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01939b2277abfdcd49</li>
        <li>Upwork Job ID: 1678311351793197056</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 25926814</li>
<li>dhairyasenjaliya | Contributor | 25926817</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-10 10:18
Is this open for contributors to work? I can do it. Do i need to submit a poposal?

**Comment by abdulrahuman5196** [comment] 2023-07-10 10:39
@ygshbht  Only issues open and have a 'Help Wanted' label is open for contributors to submit proposals

**Comment by grgia** [comment] 2023-07-11 11:53
cc @shawnborton does this style change affect only the settlement button, or all dropdown buttons?

**Comment by shawnborton** [comment] 2023-07-11 11:56
I guess we'd want to do that to all split buttons that exist for consistency!

**Comment by grgia** [comment] 2023-07-17 11:00
I'm going to make this one external @abdulrahuman5196. Happy to help with any styling questions that come up

cc @ygshbht if you're still interested!

**Comment by himanshuragi456** [comment] 2023-07-17 11:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

UI changes are required to make the component as per the design.

### What is the root cause of that problem?

Unwanted UI changes that need to be fixed



### What changes do you think we should make in order to solve the problem?

Will fix the following points:

 Button height (40px)
 Divider line (1px, same color as text, 28px height)
 Caret is still 20x20 px
 Same flex styling, here's an example on an expense report view.


### What alternative solutions did you explore? (Optional)

N/A

**Comment by ishpaul777** [comment] 2023-07-17 11:09
Proposal
Please re-state the problem that we are trying to solve in this issue.
UI changes are required to make the component as per the design.

What is the root cause of that problem?
Not a problem

What changes do you think we should make in order to solve the problem?
Will add following changes to the ButtonWithDropdownMenu component https://github.com/Expensify/App/blob/HEAD/src/components/ButtonWithDropdownMenu.js

Button height (40px)
Divider line (1px, same color as text, 28px height)
Caret is still 20x20 px
Same flex styling, here's an example on an expense report view.

What alternative solutions did you explore? (Optional)
N/A

**Comment by neonbhai** [comment] 2023-07-17 15:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update Dropdown Button UI 

### What is the root cause of that problem?
New Feature Request

### What changes do you think we should make in order to solve the problem?
The `ButtonWithDropdownMenu` component renders the divider using the line:
 https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/components/ButtonWithDropdownMenu.js#L88

which references the CSS:
https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/styles/styles.js#L551-L556

To change the colour to the divider to the same color as text we would the property of `backgroundColor` to `themeColors.text`



To change the height we need to pass the medium prop to the `Button` component calls in `ButtonWithDropDownMenu.js`
Currently `Button` component without a size prop renders with CSS:
https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/styles/styles.js#L443-L449

The minHeight is `componentSizeLarge` which is 52px 


If we pass the `medium` prop the `buttonMedium` CSS style is applied  the button which renders with `minHeight` of `componentSizeNormal` which is 40px as required.


### What alternative solutions did you explore? (Optional)
To reduce the button size anytime a general button is rendered we can simply change the button component's style `minHeight` to `componenntSizeNormal` in the CSS:
https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/styles/styles.js#L446

With this change anytime a large button has to be rendered, we would have to explicitly pass the large prop. This change should be done only if the Expensify Design Team is moving away from a general button size to be large. I would advocate for this approach since 40px height buttons look more elegant

**Comment by ygshbht** [comment] 2023-07-17 18:51
Thanks for letting me know @grgia. Looks like some awesome proposals have already taken off. So I'll let this one go and jump to other open issues

> I'm going to make this one external @abdulrahuman5196. Happy to help with any styling questions that come up
> 
> cc @ygshbht if you're still interested!

**Comment by grgia** [comment] 2023-07-18 14:25
@abdulrahuman5196 bump on proposals

**Comment by abdulrahuman5196** [comment] 2023-07-19 20:07
@grgia I am not sure if we should review proposals or basically choose the first one requested for work on this since it is kind of a feature request with details already known?

Changes required:
>Button height (40px)
Divider line (1px, same color as text, 28px height)
Caret is still 20x20 px

**Comment by Nikhil-Vats** [comment] 2023-07-19 20:12
Hey @abdulrahuman5196, even after the details in the description the proposals are still different in their implementation.

**Comment by neonbhai** [comment] 2023-07-19 20:23
Hey @abdulrahuman5196, agreeing with @Nikhil-Vats There are different ways to implement this, hope you choose a proposal where at least some implementation details were mentioned!

**Comment by himanshuragi456** [comment] 2023-07-20 00:58
@abdulrahuman5196 I sent the first proposal, I could have added the changes but then actually the changes are very basic and everyone's solution boils down to pretty much the same changes. after all, some minor things can be discussed in the PR. It was mentioned in contributing guidelines that the first proposal shall be considered.

**Comment by abdulrahuman5196** [comment] 2023-07-21 16:02
@grgia Gentle ping to look into this https://github.com/Expensify/App/issues/22540#issuecomment-1642685562

**Comment by grgia** [comment] 2023-07-24 15:13
@abdulrahuman5196 because this component is fairly nested, let's choose the first proposal that included a plan of action

**Comment by garrettmknight** [comment] 2023-07-26 22:18
@abdulrahuman5196 does the first proposal with the POA look good to you?

**Comment by garrettmknight** [comment] 2023-07-31 10:59
@abdulrahuman5196 can you take a look at this one when you get a chance?

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:54
Reviewing today

**Comment by abdulrahuman5196** [comment] 2023-08-01 10:32
Since the requirements are straightforward. I am choosing the first proposal with atleast some plan of action.

@dhairyasenjaliya 's proposal here https://github.com/Expensify/App/issues/22540#issuecomment-1638251904  looks good. 

🎀 👀 🎀
C+ Reviewed

cc: @grgia

**Comment by shawnborton** [comment] 2023-08-03 16:29
We have three button sizes:
- Small (28px tall)
- Regular/medium (40px tall)
- Large (52px tall)

We want to use regular/medium buttons for the screens you shared above, so that would include the preview card and then the report/expense view.

**Comment by shawnborton** [comment] 2023-08-03 17:38
For the first screenshot you shared, I believe that button will be moving to the top header area right? cc @trjExpensify @JmillsExpensify @grgia on that one

**Comment by grgia** [comment] 2023-08-03 22:28
that's correct that Money request header buttons will be at the top in the header.

**Comment by trjExpensify** [comment] 2023-08-07 10:05
>For the first screenshot you shared, I believe that button will be moving to the top header area right? cc @trjExpensify @JmillsExpensify @grgia on that one

Just so I'm sure, which is the first screenshot being referenced? 😅

**Comment by trjExpensify** [comment] 2023-08-07 10:41
Thanks! That's the confirmation screen ahead of creating the request. I don't believe that confirmation button is moving to the top header area. I've been out for a couple of days though, so might have missed something? @shawnborton @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2023-08-08 02:36
Great catch, agree with @trjExpensify

**Comment by garrettmknight** [comment] 2023-09-11 10:31
Summary of payments

urgency bonus: no
Reporter: N/A
Contributor: @dhairyasenjaliya  $1000 paid in Upwork
Contributor+: @abdulrahuman5196  $1000 paid in Upwork

**Closed by garrettmknight** 2023-09-11 10:31 UTC
Labels: External, Daily, Overdue, Awaiting Payment
