### ISSUE TITLE
[$500] Split bill - App crashes when clicking on bill split preview when it is loading as participant

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30028] opened 2023-10-19 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.87-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Go to a group chat with User B and C
3. {User B] Open the group chat
4. [User A] Create a split bill
4. [User B] While the bill split preview is loading, click on it

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/c1b9778b-2c21-4a8d-80a2-75c592c90087

https://github.com/Expensify/App/assets/78819774/ac004289-ca5b-4630-9b6f-58ba920baff1

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd21f2658e39844e</li>
        <li>Upwork Job ID: 1715109151896576000</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by shahzoab** [comment] 2023-10-19 22:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill preview crashes when it's in a loading state and the user clicks on it.

### What is the root cause of that problem?
The data is not fully loaded like `props.transaction` and the user clicks on it which causes it to crash.

### What changes do you think we should make in order to solve the problem?
We need to disable it in the loading state so that the user is unable to click it until it finishes loading.
https://github.com/Expensify/App/blob/79845f986c43efa9418e855388216036692a7fdc/src/components/ReportActionItem/MoneyRequestPreview.js#L341-L351

### What alternative solutions did you explore? (Optional)
N/A

**Comment by youssef-lr** [comment] 2023-10-20 09:05
Sorry folks this is gonna require a backend change to send the transaction through a pusher update. I'll work on this next week.

**Comment by youssef-lr** [comment] 2023-10-20 09:07
Actually, looks like this is a duplicate of https://github.com/Expensify/App/issues/27200, so I'll be closing this one.

**Closed by youssef-lr** 2023-10-20 09:07 UTC
Labels: Daily, Internal, Bug
