### ISSUE TITLE
Web - In responsive mode, when selecting the tablet size (768px), a portion of the map is not displayed as expected

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26905] opened 2023-09-06 20:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Clicked on the FAB menu > Request money > Distance.
2. Inspected the website > Toggled Device toolbar > Chose Tablet

## Expected Result:
When selecting the tablet size (768px), the map should fully display without any missing portions.

## Actual Result:
In responsive mode with a tablet-sized viewport (768px), a portion of the map is not displayed as it should be

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c8d58fa0-beb6-4ce3-9160-9016c5663bb6

https://github.com/Expensify/App/assets/93399543/6530b557-c227-44e1-8180-acc558fc0f93

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693569700628289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by akinwale** [comment] 2023-09-07 04:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In responsive mode, the map does not properly resized if the window or viewport size increases.

### What is the root cause of that problem?
The Mapbox implementation on web does not automatically re-render when the container size or viewport size is increased. This seems to be a [known issue](https://stackoverflow.com/questions/70352188/how-to-make-mapbox-resize-when-changing-the-browser-width) with a number of other posts suggesting the same thing.

### What changes do you think we should make in order to solve the problem?
Call the `resize()` method on the Mapbox when the window is resized to ensure that the map re-renders in the available space after the window or browser viewport is resized.

### What alternative solutions did you explore? (Optional)
None

**Comment by akinwale** [comment] 2023-09-10 07:52
Turns out this is a duplicate of https://github.com/Expensify/App/issues/26540

**Comment by anmurali** [comment] 2023-09-13 01:57
Gonna close since this is a dupe.

**Closed by anmurali** 2023-09-13 01:57 UTC
Labels: Daily, Overdue, Bug
