### ISSUE TITLE
[$1000] Dev: Clicking on task header sometimes opens assignee page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22498] opened 2023-07-08 19:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to the "Assign task" section
3. Enter a title and create task
4. After creating click on task header somewhere

## Expected Result:
 Clicking on task header should not open assignee page

## Actual Result:
Clicking on task header sometime open assignee page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.38-3
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/eeb8105f-47cc-4f1d-b63c-1a5aa6464717

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688771023484909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188e528004d0d6c31</li>
        <li>Upwork Job ID: 1678461651273142272</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-07-10 16:24
Only reproducible on dev so removing blocker

**Comment by thienlnam** [comment] 2023-07-10 17:36
Actually, with the latest task redesign I don't think this bug exists anymore. If by assignee page you mean the DM - that is expected

**Comment by ayazhussain79** [comment] 2023-07-10 17:45
@thienlnam this bug is on after new task redesign you can check that that is regression of this [PR](https://github.com/Expensify/App/pull/20841)

**Comment by thienlnam** [comment] 2023-07-10 17:48
@ayazhussain79 From the video in the issue post it looks like clicking the task header opens the chat with the assignee. That's expected behavior. Is there another issue you're trying to point out here that I'm missing?

**Comment by thienlnam** [comment] 2023-07-10 17:50
Ohhh I see - yes that does look like a bug - thanks for clarifying

**Comment by Pujan92** [comment] 2023-07-10 19:21
@thienlnam isn't it should open the assignee page for taskreport as looks correct as per the code?
https://github.com/Expensify/App/blob/0bdca706efb6344adfbccc6cff9f02a74f5a3650/src/pages/home/HeaderView.js#L165

**Comment by thienlnam** [comment] 2023-07-10 20:40
cc @jasperhuangg Was it intended to make this change? I believe the only spot we want to allow changing the assignee is when clicked below - thoughts?

**Comment by Nikhil-Vats** [comment] 2023-07-10 20:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Dev: Clicking on header area opens assignee page.

### What is the root cause of that problem?
Here, we are opening the assignee page if the report is a task report. This is a regression from [this PR](https://github.com/Expensify/App/pull/20841).
https://github.com/Expensify/App/blob/751cf85c7bfc13c649abf54e85dd175b4dec566a/src/pages/home/HeaderView.js#L164-L167
### What changes do you think we should make in order to solve the problem?
If we want to open the details page when we click on the header area (except parent chat) then we can change line 165 to -

```javascript
onPress={() => ReportUtils.navigateToDetailsPage(props.report)}
```

Also, we should remove the `disabled` prop in line 167 as we won't open assignee page in any case now.

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-07-10 20:59
@thienlnam in the previous design, user was not able to open assignee page when clicking around header but user was able to open assignee page when clicked on the assignee shown after "To" (in old header design). But I agree, in the new design the header should not open assignee page.

**Comment by tjferriss** [comment] 2023-07-12 05:38
Assigning @jasperhuangg and un-assigning @yuwenmemon as Jasper is working on the PR.

**Comment by jasperhuangg** [comment] 2023-07-17 20:09
The PR is on prod cc @tjferriss 

Let's get @ayazhussain79 paid out for reporting the bug and we should be good to close this out

**Comment by tjferriss** [comment] 2023-07-18 16:41
@ayazhussain79 offer has been sent via Upworks

**Comment by ayazhussain79** [comment] 2023-07-18 16:44
@tjferriss offer accepted, Thank you

**Comment by tjferriss** [comment] 2023-07-18 17:03
Payment has been sent.

**Closed by tjferriss** 2023-07-18 17:03 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted
