### ISSUE TITLE
[$500] Web - Chat  - 2 APIs updateFrequentlyUsed emoji is sent

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27579] opened 2023-09-16 15:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Select emoji from emoji picker or suggestion list
3. See APIs in Network tab of the dev tool

## Expected Result:
1 APIs updateFrequentlyUsed emoji is sent

## Actual Result:
2 APIs updateFrequentlyUsed emoji is sent

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/83714a99-4fb6-4bd7-bb48-30dffd44b4de

https://github.com/Expensify/App/assets/93399543/ca0c1cb3-9af7-41fd-a41e-e5577789bd9b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694762881668309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f5849f6d3603f6e</li>
        <li>Upwork Job ID: 1703066676577357824</li>
        <li>Last Price Increase: 2023-09-16</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-09-16 15:22
Prposal by: @DylanDylann
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1694762881668309

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When selecting emoji from suggestion list or emoji Picker, this emoji is added to frequently used emoji 2 times
### What is the root cause of that problem?
When an emoji is selected from suggestion list or emoji Picker we will call updateComment function
https://github.com/Expensify/App/blob/e48121cb35052e958928c002d2b3a7d78a930ff3/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L176-L183
But we also have another logic to update frequently used emojis when selecting emoji from suggestion list or emoji picker
**- Logic update frequently used emojis when selecting from Suggestion list**
https://github.com/Expensify/App/blob/e48121cb35052e958928c002d2b3a7d78a930ff3/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L138-L143
**- Logic update frequently used emojis when selecting from Emoji picker**
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L191
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L462
### What changes do you think we should make in order to solve the problem?
Because we always update frequently used emoji in updateComment function so we don’t need logic to update frequently used emoji. So let’s remove it
**- Logic update frequently used emojis when selecting from Suggestion list**
https://github.com/Expensify/App/blob/e48121cb35052e958928c002d2b3a7d78a930ff3/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L138-L143
**- Logic update frequently used emojis when selecting from Emoji picker**
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L191
https://github.com/Expensify/App/blob/c36ac0c98cf8a92a5b7136bbf090550cca5ea90c/src/components/EmojiPicker/EmojiPickerMenu/index.js#L462
Same things in EmojiPickerMenu/index.native.js
The same problem happen in ReportActionItemMessageEdit.js, we also need to fix it with the same way
### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2023-09-17 19:22
I think we should hold this in the favor of https://github.com/Expensify/App/issues/27464. With the given solution, I think we won't be adding the frequently used emojis twice as described in the issue.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 07:32
Ah, is this one just a dupe of that one you linked above?

**Comment by mananjadhav** [comment] 2023-09-18 07:36
I think fixing that should resolve this one too, or we can merge the issues and close this one out. Essentially the root cause is the same.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 07:39
Got it. IMO, if root cause is the same, let's merge and close this one. No need to work on the same thing in two places.

**Comment by joekaufmanexpensify** [comment] 2023-09-18 09:38
Cool cool, closing!

**Closed by joekaufmanexpensify** 2023-09-18 09:38 UTC
Labels: External, Daily, Help Wanted, Bug
