### ISSUE TITLE
[HOLD for payment 2024-11-05] [$250] Invoices - Invoice thread (x owes y) appears in participant list when sending invoice offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49941] opened 2024-09-30 15:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Create a new workspace
4. Go to workspace settings > More features
5. Enable Invoices
6. Go to FAB > Send invoices
7. Send invoice to anyone in offline mode
8. Go to FAB > Send invoices
9. Enter amount > Next

## Expected Result:
Invoice thread (report title "user owes x") should not appear in the user list

## Actual Result:
Invoice thread (report title "user owes x") appears in the user list
When selecting the thread as the recipient, it ends up sending an invoice to yourself

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/302347bf-3f40-4ba1-9fee-74ed7d5e2e13

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844118840980357719</li>
        <li>Upwork Job ID: 1844118840980357719</li>
        <li>Last Price Increase: 2024-10-16</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104518233</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-09-30 15:38
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-09-30 15:39
We think that this bug might be related to #vip-bills

**Comment by mkzie2** [comment] 2024-09-30 23:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Invoice report is included in send invoice participants list.

### What is the root cause of that problem?

We're excluding multiple participants reports here:

https://github.com/Expensify/App/blob/b76fb4555e8390a3cb5f1188aebb36a894172ca8/src/libs/OptionsListUtils.ts#L1973-L1975

Where an undefined/empty `reportOption.login` indicates a report with multiple participants (i.e. reports with defined `login` has 1 participant only):

https://github.com/Expensify/App/blob/b76fb4555e8390a3cb5f1188aebb36a894172ca8/src/libs/OptionsListUtils.ts#L797-L798

When we create the optimistic invoice report, for participants, we only include the current user, not the receiver account:

https://github.com/Expensify/App/blob/b76fb4555e8390a3cb5f1188aebb36a894172ca8/src/libs/ReportUtils.ts#L4352-L4356

That makes the invoice report be misunderstood as report with only 1 participant while it is supposed to be multiple (compared to actual BE response).

### What changes do you think we should make in order to solve the problem?


Add `receiverAccountID` to the optimistic participants above.

```javascript
participants: {
    [currentUserAccountID ?? -1]: {
        notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
    },
    [receiverAccountID]: {
        notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
    },
},
```

**Comment by JmillsExpensify** [comment] 2024-10-09 20:52
Opened up to external

**Comment by JmillsExpensify** [comment] 2024-10-16 18:06
Still the same. Waiting for proposals

**Comment by mkzie2** [comment] 2024-10-16 21:27
@rushatgabhane Can you review my proposal https://github.com/Expensify/App/issues/49941#issuecomment-2384381346?

**Comment by Anaslancer** [comment] 2024-10-18 17:47
@lanitochka17 How did you pass the step of company info (name and url) at the invoice?

**Comment by JmillsExpensify** [comment] 2024-11-05 19:14
Payment summary:

 - Contributor: @mkzie2 $250 via Upwork
 - Reviewer: @rushatgabhane $250 via NewDot.

**Comment by JmillsExpensify** [comment] 2024-11-05 22:59
Paid contributor via Upwork. @rushatgabhane I'm going to close this one out. I'm assuming you already have it on your radar, so please make sure that you finish the checklist and then submit an expense via Expensify.

**Closed by JmillsExpensify** 2024-11-05 22:59 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-06 12:04
$250 approved for @rushatgabhane
