### ISSUE TITLE
Chat - Page not found when mention is open in new tab

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22479] opened 2023-07-08 12:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat -> Tag someone and send message
2. If we click it normally it opens Mentioned user's detail page
3. If you click with Roller button of mouse on mention It will open in new tab, But this time it shows Error

## Expected Result:
It should open new tab, with Chat and RHN(User detail popup) open

## Actual Result:
It shows "You don't have access to this page" on opening mention in new tab with Mouse roller button click
This same happens in mWeb when you Tap and hold on mention and open it in new tab. (But also if remove "r/" from url it loads proper)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c42b375-5dad-44fd-9495-4833f41b9986

https://github.com/Expensify/App/assets/93399543/de406a7e-b208-4b2d-b5e5-cf4632e079ed

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688739080988249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-07-08 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
clicking on mentioned user link to open in a new tab gives 404 page not found error.

### What is the root cause of that problem?
For the mentioned user `TextLink` we are setting a relative path for the `href` prop and that is causing the issue by keeping the `/r` before the details path.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L44

### What changes do you think we should make in order to solve the problem?
Provide the absolute path for the `href` prop by adding a `/` at the beginning to fix this.
```
href={`/${ROUTES.getDetailsRoute(loginWithoutLeadingAt)}`}
```

**Comment by MitchExpensify** [comment] 2023-07-10 21:22
Can you help me understand what this means please @dinaljivani?

"If you click with Roller button of mouse on mention It will open in new tab"

What is the "Roller button of mouse" specifically?

**Comment by DinalJivani** [comment] 2023-07-11 08:05
@MitchExpensify 
>"Roller button of mouse"

With "Roller button of mouse" I meant the Scroll wheel button click.

We generally use Scroll wheel click in browser to open that link in new tab.
Thanks

**Comment by MitchExpensify** [comment] 2023-07-12 22:03
Chatted internally on whether theres appetite to fix this and I'm leaning to closing. Thanks for reporting!

**Closed by MitchExpensify** 2023-07-12 22:03 UTC
Labels: Daily, Bug

**Comment by DinalJivani** [comment] 2023-07-13 07:47
@MitchExpensify  
I think there is solution to this issue and @Pujan92 has posted proposal which seems to be working.
Also What is the link of internal discussion? Is it open to Contributor?

**Comment by MitchExpensify** [comment] 2023-07-13 23:31
Thanks for the bump! Seeing as this bug is tied to an external piece of hardware we're going to close this. Also seems edgy enough not to worry about it honestly

**Comment by Pujan92** [comment] 2023-07-14 03:36
@MitchExpensify just to share I used to click on the mouse wheeler when I had that to open the link in new tab. I think people with that mouse are generally use the roller wheel click for the link. It seems like a edgy and also fine if it won't reopened but I felt to share my thought.

**Comment by MitchExpensify** [comment] 2023-07-14 19:43
I appreciate that, thanks @Pujan92 !
