### ISSUE TITLE
[$500] Start chat - `Chat` option hidden for the moment if switch between `Chat` and `#Room`

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34695] opened 2024-01-18 01:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Start chat
4. Switch between `Chat` and `#Room`

## Expected Result:
`Chat` option not hidden

## Actual Result:
`Chat` option hidden for the moment

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/487195d2-55e3-45cc-ba08-726f291e8610

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-18 01:29
[#vip-vsb](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ)

**Comment by shubham1206agra** [comment] 2024-01-18 05:41
This is a dupe (I don't remember the issue). But @kacper-mikolajczak is working on it.
You can close this one out.

**Comment by bernhardoj** [comment] 2024-01-18 07:54
This one https://github.com/Expensify/App/issues/34377

**Comment by sadiamehreen** [comment] 2024-01-18 12:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat tab disappears when switching frequently between the chat and room tabs.

### What is the root cause of that problem?
The problem is that the TextInput Component is used in both the tabs as Name,email, or Phone field in the chat tab and room name input in the room tab. The cleanup function for the visibility listener in the useEffect hook of the TextInput component is not being properly set and cleared. This can lead to unexpected behavior, such as the visibility listener not being removed when the component is unmounted.
Given below is the recording of the issue
[before.webm](https://github.com/Expensify/App/assets/146823806/7c0ff904-3d15-4a7b-8431-563f29a9f83d)


### What changes do you think we should make in order to solve the problem?

To fix this, I made changes to properly set and clear the removeVisibilityListenerRef.current and used the useCallback hook to memoize the removeVisibilityListener function. These changes ensure that the visibility listener is correctly cleaned up when the component is no longer needed.
Given below is the recording of the solution
[after.webm](https://github.com/Expensify/App/assets/146823806/9eb2466c-33dd-48a9-8714-273f6a4bc19f)


### What alternative solutions did you explore? (Optional)
N/A

**Closed** 2024-01-22 16:56 UTC
Labels: External, Daily, Overdue, Bug
