### ISSUE TITLE
[$1000] Task - Red dot appears & task report page freeze when open task as group external user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28465] opened 2023-09-29 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any user
1. Navigate to a Group Chat
2. Click on the + in the compose box and select "Assign task"
3. Enter a Title and a Description
4. Assign a user who is NOT part of the group and that you have access to
5. Create the task and log out
1. Log in as the user that was assigned the task
2. Click on the task report/conversation

## Expected Result:
The user can access the task that was created and shared in a group without access

## Actual Result:
Red dot appears in LHN and task report page does not load when open assigned task as group external user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.75-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/85fd4924-4b4a-495a-94c0-2d26d2f149cb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016e5e4776b1195fc2</li>
        <li>Upwork Job ID: 1709336069783883776</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-10-04 07:07
No proposals yet

**Comment by zzarcon** [comment] 2023-10-09 17:03
# Proposal

I have been doing some investigation and I can see that what we get back from the request shows as

```/api?command=OpenReport```

```
{
  htmlMessage: "",
  jsonCode: 404,
  message: "Report no longer exists"
}
```

<img width="531" alt="image" src="https://github.com/Expensify/App/assets/1194982/feba7ddb-bf4e-4c23-9c3e-a764df2161d3">


https://github.com/Expensify/App/assets/1194982/6387352b-df23-4f65-a98d-5f00231d6974

To me, it seems that we can't do much from the frontend side besides showing an error message instead of the loading skeleton and potentially stop the polling after N tries.

Please let me know if I'm missing something, otherwise if this error handling will be fine I will be happy to implement it

**Comment by paultsimura** [comment] 2023-10-09 17:17
This doesn't happen only when sharing in a group. This also happens if we share a task in a chat with user B, but assign it to user C.

**Comment by zzarcon** [comment] 2023-10-09 17:49
Interesting, I can see there is some logic creating an infinite loop, related with my comment above, where we poll for report forever and I think is related in the logic used to render the `<ReportActionsSkeletonView>` vs `<ReportActionsView>`.

in `src/pages/home/ReportScreen.js`

we use this logic to render the skeleton
```
{(!isReportReadyForDisplay || isLoadingInitialReportActions || isLoading) && <ReportActionsSkeletonView />}
```

and the problem is related with the `isLoadingInitialReportActions` variable, which keeps changing from true to false, subsequentially switching rendering components from the Skeleton and the View on each render.

I think we need to change the logic for `isLoadingInitialReportActions` by checking if it's only in the first render, we can use the existing `firstRenderRef` variable:

<img width="969" alt="image" src="https://github.com/Expensify/App/assets/1194982/d51f0a69-d28d-4ad7-b75b-d896ad3370ae">

By doing that + adding the error handling I mentioned before we could fix the issue

**Comment by abdulrahuman5196** [comment] 2023-10-10 17:38
we have some hypothesis from contributors. Will check on this tomorrow.

**Comment by abdulrahuman5196** [comment] 2023-10-15 07:38
Currently while testing I am not seeing app freeze but a NotFoundPage.

But I am not sure on the expected behavior here. Like should we even allow a task to be assigned to user outside of the group? Since the assignee is not able to access the task?
@thienlnam Could you provide some guidance here? Or tag someone who provide guidance here?

**Comment by thienlnam** [comment] 2023-10-16 18:07
> But I am not sure on the expected behavior here. Like should we even allow a task to be assigned to user outside of the group? Since the assignee is not able to access the task?

If the task is assigned to a user outside the group then they should be able to access it - the task report is a report separate from the group chat, and you can have access to the task but not the group chat. Is that not happening here?

**Comment by akamefi202** [comment] 2023-10-19 06:51
It's not reproducible anymore. Looks like fixed.

**Comment by abdulrahuman5196** [comment] 2023-10-20 18:37
>If the task is assigned to a user outside the group then they should be able to access it - the task report is a report separate from the group chat, and you can have access to the task but not the group chat. Is that not happening here?

This was not happening previously. Will check if the issue is reproducible any more since contributor commented not reproducible,

**Comment by abdulrahuman5196** [comment] 2023-10-23 11:30
Yes. Issue is not reproducible anymore. @kevinksullivan We can close it, should have been fixed with some backend changes.

**Closed** 2023-10-23 17:51 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
