### ISSUE TITLE
[HOLD for payment 2023-12-08] Incorrect month is opening when tapping Oct2023 statement in OldDot app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30743] opened 2023-11-02 02:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction (don't have statement)
**Reproducible in production?:** needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @cead22 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698869124487529

## Action Performed:
1. Go to OldDot and login
2. Tap on Oct 2023 statement 

## Expected Result:
Statement should open in NewDot with correct header and translation. Link shou

## Actual Result:

- Tapping on the link to the Oct 2023 statement in old app opens new dot, but with a header `Noviembre 2023 Statement`
- The translation is wrong, it should be  `Estado de cuenta de Octubre 2023`
- Opening the statement in NewDot opens a new safari window and lands in sign in page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![IMG_27E3D7E5C44C-1](https://github.com/Expensify/App/assets/38435837/61c46cdf-a933-4229-9e1d-1dfae9c5ed32)

![IMG_0203E760C83B-1](https://github.com/Expensify/App/assets/38435837/2c1f0338-f32c-4930-8ecc-156f5429282c)

![IMG_5545E052961E-1](https://github.com/Expensify/App/assets/38435837/9f239840-e005-4ca3-a2aa-57ce72ec30c2)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f250a418a4564fbf</li>
        <li>Upwork Job ID: 1720223933365579776</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-11-02 23:38
I'm not sure if this can be external so going to apply internal for now.

**Comment by Christinadobrzyn** [comment] 2023-11-06 20:28
hey @mananjadhav can this be external? Let me know your thoughts!

**Comment by mananjadhav** [comment] 2023-11-07 12:39
@Christinadobrzyn Catching up, I'll test this by tomorrow.

**Comment by mananjadhav** [comment] 2023-11-07 18:09
I just checked this. Due to the lack of context from OldDot, I am not sure how do I reproduce this. @Christinadobrzyn are you able to reproduce this?

@m-natarajan Can you please elaborate the steps to reproduce and also post a video instead of screenshot? 

> Tap on Oct 2023 statement

I don't know what we mean by this.

and do I need to open Expensify in the iOS Native? to test this?  I also followed through the slack conversation but no info there.

**Comment by Christinadobrzyn** [comment] 2023-11-07 19:21
No, I was not able to reproduce this, sorry I pushed it forward because it was reported by internal engineers. I'll reach out to QA in Slack to see if they can test again and update the OP steps so I can get a better idea of what is happening. Asking QA for some help - https://expensify.slack.com/archives/C9YU7BX5M/p1699384867315839

**Comment by mvtglobally** [comment] 2023-11-07 22:03
@cead22 can you pls help us out on this issue? we do not have access to statements to verify reproduction again.

**Comment by cead22** [comment] 2023-11-08 17:04
How can I help? 

This only applies to accounts that have expensify cards. If you have one and have received a statement, you should be able to navigate to https://new.expensify.com/statements/202310 to see the October statement (hence the `202310` in the URL), and you'll see November shows on the header

<img width="385" alt="image" src="https://github.com/Expensify/App/assets/165133/0ff924b8-988c-4fd6-a058-04de86754c21">

**Comment by Christinadobrzyn** [comment] 2023-11-08 22:08
So it sounds like this should be internal since it relates to OldDot and Expensify Cards. I'll add an engineering label to see if we can get someone internal to work on this.

**Comment by Christinadobrzyn** [comment] 2023-11-08 22:09
Oh no, @cead22 it assigned to you 😞 Let me know if you want me to try and find another engineer to work on this.

**Comment by cead22** [comment] 2023-11-09 18:24
If you can, please do

**Comment by Christinadobrzyn** [comment] 2023-11-10 16:52
Reached out to see if other engineers would be able to grab this - https://expensify.slack.com/archives/C01SKUP7QR0/p1699635102177169

**Comment by Christinadobrzyn** [comment] 2023-11-13 21:08
asking the team again - https://expensify.slack.com/archives/C01SKUP7QR0/p1699909684516149

**Comment by Christinadobrzyn** [comment] 2023-11-14 23:32
Hi @hayata-suenaga would you be able to help us with this fix?

**Comment by hayata-suenaga** [comment] 2023-11-15 19:08
hi @Christinadobrzyn 

I can try to move the issue forward. To begin with, could you tell me how I can find my Expensify card statements on OldDot?

**Comment by Christinadobrzyn** [comment] 2023-11-17 02:22
Hi! Thank you! I'm not getting statements so I'm having a hard time nailing down how to reproduce this. I think they are related to Expensify Card purchases. 

I wonder if @Gonals might know more about this based on https://github.com/Expensify/Expensify/issues/234459

**Comment by Christinadobrzyn** [comment] 2023-11-17 23:51
@Gonals ended up not working on https://github.com/Expensify/Expensify/issues/234459 so they are not familiar with statements. 

I'm not sure what to do here as I am not getting statements. Posting to the team to see if anyone can take this forever or at least while I'm ooo until Nov 27th - https://expensify.slack.com/archives/C01SKUP7QR0/p1700265001449449

**Comment by Christinadobrzyn** [comment] 2023-11-18 00:30
I'm going to assign someone else from the BZ team to see if they might be able to help with guidance on what to do next to reproduce this.

**Comment by hayata-suenaga** [comment] 2023-11-20 16:34
I gonna so ask the engineering team if anyone is familiar with the statement generation logic.

**Comment by muttmuure** [comment] 2023-11-21 12:39
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/e0a92c0d-96a6-4d95-8c13-c746a1cb5f05">

I clicked https://new.expensify.com/statements/202310 and it shows November in the heading. That's the bug right?

**Comment by muttmuure** [comment] 2023-11-21 12:40
I clicked https://new.expensify.com/statements/202310 and I see November 2023 in the heading.

That's the bug, right? 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/fe569d47-e7e8-46cc-ae34-690fd15906f0">

**Comment by thienlnam** [comment] 2023-11-21 18:50
These are generated internally and we grab the month from the URL - 

> I clicked [new.expensify.com/statements/202310](https://new.expensify.com/statements/202310) and I see November 2023 in the heading.

This does seem like the bug. I'd first check this locally and seeing what happens [here](https://github.com/Expensify/Web-Expensify/blob/c0c04ee36b722f0955ec04930118c2e127f85462/statement.php#L24-L31)

**Comment by hayata-suenaga** [comment] 2023-11-22 02:01
will work on this next week.

Is it okay we change the priority to weekly?

**Comment by muttmuure** [comment] 2023-11-22 14:30
Doesn't seem as high priority as some of the other stuff going on. Let's put daily back on next week

**Comment by hayata-suenaga** [comment] 2023-11-24 15:40
gonna go back to [the Slack convo](https://expensify.slack.com/archives/C03TQ48KC/p1700498197734459) and see what I need to do

**Comment by hayata-suenaga** [comment] 2023-11-24 16:50
PR is up and under review.

**Comment by cead22** [comment] 2023-12-01 20:05
🎉  
<img width="1643" alt="image" src="https://github.com/Expensify/App/assets/165133/818190bb-740a-48ff-9bb4-69f8e403a652">

**Comment by Christinadobrzyn** [comment] 2023-12-06 01:31
prepping for payment! 

Payouts due:

Issue Reporter: NA
Contributor: NA
Contributor+: $500 @mananjadhav (paid through NewExpensify)

Eligible for 50% #urgency bonus? N 

Upwork job is NA

@mananjadhav do we need a regression test for this?

**Comment by mananjadhav** [comment] 2023-12-06 02:55
I don't think we do, but I would still want to confirm with @hayata-suenaga. This was fixed internally and I reviewed the code.

**Comment by hayata-suenaga** [comment] 2023-12-06 17:42
I also don't think we need a regression test

**Comment by Christinadobrzyn** [comment] 2023-12-08 17:50
Awesome! I think this can be closed out but @mananjadhav please make sure to request payment through NewExpensify.

**Closed** 2023-12-09 14:59 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-11 01:36
$500 payment approved for @mananjadhav based on this summary.
