### ISSUE TITLE
Conversation - Receipt image does not load and download file not working in old conversation

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41915] opened 2024-05-09 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.72-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** nhut.nguyenminh.it+2@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in nhut.nguyenminh.it+2@gmail.com
2. Go to any conversation and have a owed message (Paid + have with image) or create a new scan expense
3. Tap on detail
4. Try to tap on image 

## Expected Result:
Receipt image can be open and download

## Actual Result:
Receipt image does not load and the download file not working in the  conversation
Also console error appier

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/4ebdf711-e368-4761-860e-1991063ac130

https://github.com/Expensify/App/assets/115492554/3727e608-c279-439e-8c81-6ed4d14151b3

![Screenshot 2024-05-09 165156](https://github.com/Expensify/App/assets/115492554/afc3275b-67ef-4e11-9b0f-cdb548e9f523)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-05-09 14:07
I couldn't upload the image for this issue here because it's more than 10 MB

**Comment by arosiclair** [comment] 2024-05-09 15:04
Not able to reproduce on **v1.4.72-0** with my personal account. I agree that this isn't a deploy blocker and might be an issue specific to that account.

**Comment by arosiclair** [comment] 2024-05-09 15:13
I supportal'd into their account can see and download the receipt on OldDot. Unfortunately I can't get anything to load when supportal'd into NewDot. This is probably a legit bug but needs repro.

**Comment by isabelastisser** [comment] 2024-05-13 17:20
I can't reproduce this either. I tried to supportal into NewDot but it crashed. What should I do next, @arosiclair ? thanks!

**Comment by arosiclair** [comment] 2024-05-13 20:25
I think it's okay to close this out if it's not reproducible for you either.

**Closed** 2024-05-14 14:36 UTC
Labels: Daily, Needs Reproduction, Bug
