### ISSUE TITLE
mWeb - Chat - Keyboard pops up with emoji picker disappears after selecting category

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22957] opened 2023-07-15 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open NewDot
2. Open any chat
3. Open emoji picker
4. Select any emoji category

## Expected Result:
Keyboard should not appear upon selecting emoji from picker

## Actual Result:
Keyboard pops up together with emoji picker on mWeb and then disappears after selecting any category

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c9ba85d4-cbbe-4962-b073-eaf6270fa957

**Expensify/Expensify Issue URL:**

**Issue reported by:**Applause - Internal Team

**Slack conversation:**

**Comment by MitchExpensify** [comment] 2023-07-16 16:41
Isn't this expected because you have the search field highlighted @lanitochka17 ? I think I'd expect the keyboard to show when a text field is highlighted

**Comment by lanitochka17** [comment] 2023-07-16 16:51
@MitchExpensify  In iOS/Safari, when 2 keyboards are o

https://github.com/Expensify/App/assets/78819774/af973984-e325-41d4-b5ad-2e0b8aaa67b7

pen, it works strangely: the keyboard gets stuck or rises up

**Comment by MitchExpensify** [comment] 2023-07-17 20:37
Mind filing a separate issue for that @lanitochka17 ? That seems like a separate bug to the keyboard being open with the search text field highlighted but curious if you agree!

**Comment by MitchExpensify** [comment] 2023-07-21 22:52
Closing as expected behavior

**Closed by MitchExpensify** 2023-07-21 22:52 UTC
Labels: Daily, Overdue, Bug
