### ISSUE TITLE
[$1000] Concierge - Concierge chat opened from https://staging.new.expensify.com/concierge can't be exited

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25839] opened 2023-08-24 12:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. With user logged in to New Dot go to https://staging.new.expensify.com/concierge
2. Try to exit the chat

## Expected Result:
User can exit the concierge chat opened via the link https://staging.new.expensify.com/concierge

## Actual Result:
User can't exit the concierge chat opened via the link https://staging.new.expensify.com/concierge
but needs to refresh the page or use another URl to access the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS /  Safari
- [x] Windows / Chrome

**Version Number:** 1.3.57-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/1a91e1ae-78e8-41bd-a3ff-fee338137b4f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0130feb263dacc9958</li>
        <li>Upwork Job ID: 1696446505854025728</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-08-25 17:33
I believe this is being handled internally, but will check Monday to confirm!

**Comment by dylanexpensify** [comment] 2023-08-28 11:10
updating today!

**Comment by dylanexpensify** [comment] 2023-08-29 08:55
Confirmed!

**Comment by mananjadhav** [comment] 2023-08-30 20:57
I think we've always had `Concierge` in the RootStack. In principle @bernhardoj's [proposal](https://github.com/Expensify/App/issues/25839#issuecomment-1691784005) looks good to me. 

I am going to confirm this from @adamgrzybowski on why we removed `Navigation.isNavigationReady()` from `ConciergePage` [here](https://github.com/Expensify/App/pull/16581/files#diff-dee473482f17c430c462f98d9335ed3f4eea15f0e9ff8117a183f49117edebeaL30-L33).

🎀 👀 🎀 C+ reviewed.

**Comment by mountiny** [comment] 2023-08-31 09:27
I am not sure, I think there is lots of custom logic because of deeplinking to this particular page and the fact that it is a report but we dont know its reportID when we are not logged in yet.

During testing, @bernhardoj make sure to really thoroughly test all the deeplinking when signed on or signed out on web and on native too

**Comment by adamgrzybowski** [comment] 2023-08-31 12:17
The concierge page with the loading indicator (the one in RootStack) is something else than the concierge report page. 

The concierge page is only here to redirect to the concierge report and should be removed from the stack after that. It looks like it's not removed properly. 

```js
function ConciergePage(props) {
    useFocusEffect(() => {
        if (_.has(props.session, 'authToken')) {
            // Pop the concierge loading page before opening the concierge report.
            Navigation.goBack();
            Report.navigateToConciergeChat();
        } else {
            Navigation.navigate();
        }
    });

    return <FullScreenLoadingIndicator />;
}
```

**Comment by mananjadhav** [comment] 2023-08-31 14:47
I didn't understand your response @adamgrzybowski. I understand removing the Concierge from the stack. I meant to ask is we removed `Navigation.isNavigationReady()`, is there a specific reason for that?

**Comment by adamgrzybowski** [comment] 2023-08-31 15:02
> I didn't understand your response @adamgrzybowski. I understand removing the Concierge from the stack. I meant to ask is we removed Navigation.isNavigationReady(), is there a specific reason for that?

Sorry that was an explanation to this one 😄 
> I also wonder why Concierge screen has the same level with CENTRAL_PANE_NAVIGATOR while it's only a normal report 🤔


About `Navigation.isNavigationReady()` I don't remember why it was removed. Maybe we just forgot to replace `isDrawerReady` with `isNavigationReady` or it just worked well when we were testing it. 

But I don't think there was any particular reason. 


Looking at this problem I think it makes sense to bring it back.

**Comment by mountiny** [comment] 2023-08-31 18:17
@adamgrzybowski There might be a regression we got that the `/concierge` route does not work reliably. We should treat it as a deploy blocker tomorrow 🔥

**Comment by dylanexpensify** [comment] 2023-09-04 10:18
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! @mountiny @adamgrzybowski any update here?

**Comment by mananjadhav** [comment] 2023-09-04 16:28
Yes I agreed.  As I mentioned earlier [here](https://github.com/Expensify/App/issues/25839#issuecomment-1699829539) @bernhardoj's proposal makes sense.

**Comment by dylanexpensify** [comment] 2023-09-11 10:28
Coming back from conference last week - updating today!

**Comment by mvtglobally** [comment] 2023-09-13 17:21
Issue not reproducible during KI retests. (First week)

**Comment by dylanexpensify** [comment] 2023-09-13 20:07
Are we still able to repro? @mananjadhav

**Comment by Gonals** [comment] 2023-09-15 02:35
If the original issue is fixed, I think we can close this for now! Any other issues can be discussed in their own GH/slack thread

**Closed by Gonals** 2023-09-15 02:35 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
