### ISSUE TITLE
[$500] Web- IOU - The IOU is blank when creating a scan IOU with a corrupted image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38845] opened 2024-03-22 22:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/38397
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to FAB - Request money - Scan
2. Upload a corrupted image
3. Click on the IOU

## Expected Result:
The IOU should be shown with the appropriate error message.

## Actual Result:
The IOU is blank when creating a scan IOU with a corrupted image. Sometimes you get a "Hmm... it's not here" message.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/84454ea6-07e0-496d-9e5d-9f30f3796983

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012352796e24064fd2</li>
        <li>Upwork Job ID: 1772361144570482688</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-22 22:05
We think that this bug might be related to  #wave-collect - Release 1

**Comment by Pujan92** [comment] 2024-03-26 08:24
I am also not able to reproduce, @kbecciv could you plz retest and confirm?

https://github.com/Expensify/App/assets/14358475/97f07655-6384-466a-97e2-cf35ca080722

**Comment by MonilBhavsar** [comment] 2024-03-26 09:38
Thank you for taking a look!

**Comment by kbecciv** [comment] 2024-03-26 15:01
@Pujan92 Checking

**Comment by MonilBhavsar** [comment] 2024-03-28 05:13
@kbecciv was this reproducible?

**Comment by stephanieelliott** [comment] 2024-03-28 21:48
Even it this can be repro'd, I kinda don't see a lot of value in fixing this -- this is pretty edge case it seems silly to optimize for corrupted PDFs. Will wait for the repro results though.

**Comment by kbecciv** [comment] 2024-03-29 17:58
Able to reproduce it!

https://github.com/Expensify/App/assets/93399543/a7a6b657-6226-457f-ba70-8d622624d877

**Comment by MonilBhavsar** [comment] 2024-04-01 16:53
I am unable to reproduce. May be @kbecciv if you can share the corrupted image you used for reproduction?

**Comment by mvtglobally** [comment] 2024-04-04 03:34
Issue is reproducible during KI retests. 

![1711987093914!0104](https://github.com/Expensify/App/assets/43995119/386d91fc-37ae-4462-b4d9-a6034f9259f4)

**Comment by stephanieelliott** [comment] 2024-04-04 16:03
I'm gonna close this based on the comment [here](https://github.com/Expensify/App/issues/38845#issuecomment-2026189419), and also due to it being specific to Chrome makes it edge case

**Closed by stephanieelliott** 2024-04-04 16:03 UTC
Labels: External, Engineering, Weekly, Help Wanted, Bug
