### ISSUE TITLE
Web -Empty green avatar on details page if mentioned a user without account (works well in a chat))                   

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21940] opened 2023-06-30 10:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Go to any chat and mention a user without expensify account (example: @[useremail@gmail.com](mailto:useremail@gmail.com))
3. Click on mention and notice that details page opens up with empty green avatar
4. But now with the same user if you go to a chat, avatar is shown (Fot this- click on message user option present on the details page and notice when a new chat is created , avatar is shown)
5. Now if you return back to the chat on step 2 and again click on the mentioned user, this time avatar will be shown

## Expected Result:
Normal avatar should be shown on details page if mentioned a user without account in a similar way how a chat behaves

## Actual Result:
Empty green avatar on details page if mentioned a user without account (works well in a chat))

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fa4a8830-3577-4595-981f-0152c661e27e

https://github.com/Expensify/App/assets/93399543/b0bc04f0-effb-4433-9251-0504c4fad53e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688013054514389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-30 11:09
I think this is duplicate of - https://github.com/Expensify/App/issues/21054

**Comment by slafortune** [comment] 2023-06-30 11:54
AH!  Yes - I agree, this is a duplicate.  Thanks @alitoshmatov . . . closing

**Closed by slafortune** 2023-06-30 11:54 UTC
Labels: Daily, Bug
