### ISSUE TITLE
[HOLD for payment 2023-08-01] Back button after clicking on menu gets back to list of workspace on admins channel( works well if not clicked on menu)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22065] opened 2023-07-02 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome on staging dot
2. Go to any admins channel and click on header
3. Click on workspace name below admins channel and notice the workspace opens up
4. Now click on back button and see it naviagtes back to admin channel which is working well
5. But now again click on workspace and now click on any menu of the workspace and click on back button so that we can get back to admins channel
6. But notice that on clicking on back button from the workspace page, it navigates to the workspace lists (Whereas in the previous case, it navigated back to the admins channel)
## Expected Result:
The back button after clicking on menu should get back to admins channel
## Actual Result:
Back button after clicking on menu gets back to list of workspace on admins channel( works well if not clicked on menu)
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5f0f0e90-d940-4599-9c04-6e71fdc59bd8

https://github.com/Expensify/App/assets/43996225/e8c2df4f-2c87-4d18-8fa3-81d2d312c872

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686140160128449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-03 11:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking back button after clicking on menu gets back to list of workspace on admins channel.

### What is the root cause of that problem?
If the user clicks on the workspace name on the report detail page, the navigation will create a new item in the `RightModalNavigator` because [`Report_Details_Root`](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/linkingConfig.js#L229) and [`Workspace_Initial`](https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/linkingConfig.js#L179-L181) are different screens in [`linkingConfig`](https://github.com/Expensify/App/blob/main/src/libs/Navigation/linkingConfig.js).
Therefore, there are two items in the `RightModalNavigator`.
![Annotation 2023-07-03 070335](https://github.com/Expensify/App/assets/131836113/9ac245e7-d058-491a-9533-88ab4712a53d)

When user click menu, the menu item and workspace initial page are on the same screen in `linkingConfig`, new item will be added to `Workspace_Initial`.
![Annotation 2023-07-03 064710](https://github.com/Expensify/App/assets/131836113/7f6d2b90-e9e5-40ce-92a9-04ba25f1c75a)

When the user clicks the back button, navigation will iterate `Workspace_Settings` routes and return 0, and then `fallbackRoute` will be navigated accordingly.
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/Navigation.js#L45-L61
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/libs/Navigation/Navigation.js#L99-L102

Because `fallbackRoute` is `ROUTES.SETTINGS_WORKSPACES`, we'll be returned to the list of workspaces.
https://github.com/Expensify/App/blob/b0add9454e4e1a3fcc94acdbf838040c4c15acbe/src/pages/workspace/WorkspaceInitialPage.js#L197-L197
### What changes do you think we should make in order to solve the problem?
We can remove `fallbackRoute`.
```js
-   onBackButtonPress={() => Navigation.goBack(ROUTES.SETTINGS_WORKSPACES)}
+   onBackButtonPress={() => Navigation.goBack()}
```
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2023-07-05 12:43
Slammed with bug reports. I'll close the loop on these today.

**Comment by JmillsExpensify** [comment] 2023-07-12 12:38
@mountiny more navigation bugs. I wanted to confirm that we should actually go UP vs BACK in this case?

**Comment by mountiny** [comment] 2023-07-12 20:23
I think this is kinda expected but there will be potentially a lot of edge cases in these flows. Essentially we are deeplinking to the workspace settings and the up button should lead to the workspace list and settings basically down the path you would expect in RHP.

Browser back should lead to the admin page I assume. 

Do you think we can close this one out?

**Comment by mountiny** [comment] 2023-07-17 12:23
@adamgrzybowski what do you think of the proposal above?

**Comment by adamgrzybowski** [comment] 2023-07-17 13:49
I am afraid that this function never returns a `null`.
> if (shouldEnforceFallback || (getActiveRouteIndex(navigationRef.current.getState()) == null && fallbackRoute)) {

So we never enter this if now and it is responsible for handling the up button after deep linking.

e.g.

1. Copy `http://localhost:8080/settings/profile`
2. Press the UP button

Expected:
The user should be on the settings page

Actual: 
RHP is completely closed

**Comment by StevenKKC** [comment] 2023-07-17 14:00
@adamgrzybowski Because 0 is a valid route index, so we should check for `getActiveRouteIndex` returns null or undefined. `== null` just check for an undefined or null value.

**Comment by adamgrzybowski** [comment] 2023-07-17 14:21
Yeah but it still breaks the flow described above

**Comment by mountiny** [comment] 2023-07-17 15:25
@StevenKKC Thanks for the proposal, the navigation reboot has been a project we worked on with SWM so they have more context about the changes, we appreciate your contributions and hopefully you can find some issue with Help Wanted label which you can help us with!

**Comment by JmillsExpensify** [comment] 2023-07-24 22:33
Should we now close this issue based on the linked quick fix above? I see that's merged.

**Comment by JmillsExpensify** [comment] 2023-07-26 04:04
Not sure who's kicking off the bug zero checklist above, though that's our todo between now and when the regression period passes.

**Comment by mountiny** [comment] 2023-07-26 14:20
@allroundexperts Can you handle the checklist given you have reviewed the PR pleasE?

**Comment by JmillsExpensify** [comment] 2023-08-02 20:51
In the meantime, summarizing the payments for this issue:

 - Issue reporter: @priya-zha $250
 - Contributor: @adamgrzybowski $1500 (incl. urgency bonus)
 - Contributor+: @allroundexperts $1500 (incl. urgency bonus)

@mountiny Would you please confirm that this is eligible for the bonus? It was based on the PR alone. 

Upwork job [is here](https://www.upwork.com/jobs/~01a8b9c94a1d85c0bb) for issue reporter.

**Comment by priya-zha** [comment] 2023-08-03 11:12
Applied. Thanks.

**Comment by mountiny** [comment] 2023-08-06 18:33
@JmillsExpensify so Adam is agency worker so as that I think most of these project issues they work on are handled as internal review so flat $1000 and no urgency bonus.

Also Adam in paid differently so he does not have to be in the summary

It should be $1000 to @allroundexperts here I believe.

Thanks everyone for good work here 🚀

**Comment by JmillsExpensify** [comment] 2023-08-09 16:18
Ok thank you for confirming the special situations! Updated the amounts above. @allroundexperts have you submitted via NewDot? I'll check there in any case shortly. Then @priya-zha offer was sent via Upwork.

**Comment by JmillsExpensify** [comment] 2023-08-10 04:07
Issue reporter is paid out and @allroundexperts is approved for payment via NewDot, so I'm closing this issue out.

**Closed by JmillsExpensify** 2023-08-10 04:07 UTC
Labels: Daily, Awaiting Payment, Bug
