### ISSUE TITLE
[$250] Fab – Hmm... it's not here page when open Pay someone via Fab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43475] opened 2024-06-11 13:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4613714&group_by=cases:section_id&group_order=asc&group_id=309127
**Email or phone of affected tester (no customers):** gocemate+a214@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Click on FAB
2. Click on pay someone
3. Pay an individual with paid elsewhere
4. Click on FAB> Click QAB> Pay

## Expected Result:
The BNP should open and "Pay elsewhere" or "Pay with Expensify" is displayed in the confirm button

## Actual Result:
Hmm... it's not here page when try to Pay someone via QAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b479cf61-6315-4701-865e-9bbce4744ed4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f68c40ae41d4c5d8</li>
        <li>Upwork Job ID: 1800566417161242823</li>
        <li>Last Price Increase: 2024-07-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by lanitochka17** [comment] 2024-06-11 13:16
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-06-11 16:30
There are some similar issues floating around but I think this isn't covered by any of the existing ones...maybe 🤔 Moving to external

**Comment by TheGithubDev** [comment] 2024-06-11 20:53
### **Proposal**

### **Please re-state the problem that we are trying to solve in this issue:**
The user encounters a "Hmm... it's not here" page when trying to pay someone via the Quick Action Button (QAB) in the FAB menu.

### **What is the root cause of that problem?**
The root cause of this issue is likely due to incorrect or missing navigation routes when the "Pay someone" option is selected via the QAB. The navigation system may not be properly handling the route or parameters required to display the "Pay elsewhere" or "Pay with Expensify" options.

### **What changes do you think we should make in order to solve the problem?**
To solve this problem, we need to ensure that the correct navigation routes and parameters are used when the "Pay someone" option is selected via the QAB. This can be achieved by:

1. ### **Verify and Correct Navigation Routes:**
- Ensure the navigation route used for "Pay someone" is correctly defined and accessible.
2. ### **Pass Required Parameters:**
- Ensure all necessary parameters are passed when navigating to the "Pay someone" screen to display the appropriate options.

### **Example of changes:**

1. ### **Correct Navigation Routes:**
   - Ensure the route for "Pay someone" is correctly configured in the navigation stack.
   ```javascript
   // Navigation configuration
   const AppNavigator = createStackNavigator({
       Home: HomeScreen,
       PaySomeone: PaySomeoneScreen,
       // Other screens
   });
   ```

2. ### **Pass Required Parameters:**
   - Ensure parameters like `paymentMethod` are passed when navigating to the "Pay someone" screen.
   ```javascript
   // Function to navigate to PaySomeone screen
   const navigateToPaySomeone = (navigation, paymentMethod) => {
       navigation.navigate('PaySomeone', { method: paymentMethod });
   };

   // Example usage in the FAB menu
   <FAB
       onPress={() => navigateToPaySomeone(navigation, 'Pay with Expensify')}
   >
       Pay Someone
   </FAB>
   ```

### **Any alternative solutions explored? (Optional)**
1. **Refactor FAB Menu Logic:**
- We could consider refactoring the FAB menu logic to ensure that all navigation routes are correctly defined and accessible.
2. **Use Conditional Rendering:**
- We could also implement conditional rendering based on the route parameters to ensure the correct options are displayed.
3. **Error Handling**:
- Using error handling to provide a fallback mechanism in case of navigation failures, guiding the user to the correct screen.

_Please note that the above explanation outlines only the technical approach I plan to take. I'll submit the finalized solution after getting accepted, as mentioned._

_Thanks!_

**Comment by c3024** [comment] 2024-06-12 06:02
I don't see the bug being reproducible on `main`


https://github.com/Expensify/App/assets/102477862/ad355099-da0d-40b1-b4a4-9ad7f804618e

**Comment by c3024** [comment] 2024-06-18 05:35
@sonialiap this is not reproducible and I think can be closed.

**Comment by lanitochka17** [comment] 2024-07-10 19:01
Issue is still reproducible on the latest build 9.0.6-0

https://github.com/Expensify/App/assets/78819774/84a8e46f-782b-4333-bd0d-f03c4e76983d

**Comment by c3024** [comment] 2024-07-11 06:33
@lanitochka17 Is this repro on any account?

**Comment by lanitochka17** [comment] 2024-07-12 13:29
This happens on Android and Web - Gmail account

**Comment by mvtglobally** [comment] 2024-07-19 03:23
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment] 2024-07-19 17:17
> Issue not reproducible during KI retests. (First week)

@lanitochka17 Can you please close this if it is not reproducible anymore?

I am seeing a flash of not found page for all flows including Pay someone flow. But that appears to be a different bug and there must likely be an issue for that.

https://github.com/user-attachments/assets/e736a5af-c6ec-468a-9733-92414498f935

Thanks!

**Closed** 2024-07-23 10:13 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
