### ISSUE TITLE
[$250] LHN - LHN does not display HTML code text on the message preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43563] opened 2024-06-12 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4620777
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Pre-requisite: the user must be logged in.

1. Go to any chat.
2. Send this message: <a href=""takia.html"">asd</a>
3. Verify that LHN message preview only displays "asd" and not the entire message.

## Expected Result:
The entire message should be displayed on the message preview on LHN.

## Actual Result:
The HTML code text is not displayed on the message preview on LHN, only the text that the code contains.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6510214_1718164484854!image](https://github.com/Expensify/App/assets/38435837/e6279341-ff4b-480e-9ee2-2214048f1c60)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01658743cd2f344b13</li>
        <li>Upwork Job ID: 1816155806292661045</li>
        <li>Last Price Increase: 2024-07-24</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by m-natarajan** [comment] 2024-06-12 12:58
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-12 12:59
We think that this bug might be related to  #vip-vsb

**Comment by bernhardoj** [comment] 2024-06-12 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN last message doesn't show HTML code written in plain text.

### What is the root cause of that problem?
This happens after https://github.com/Expensify/App/pull/40845 is merged. In that PR, we are converting HTML to text, so the HTML code is removed but you can still see the text inside the HTML tag.
https://github.com/Expensify/App/blob/b70b136c0c30c4948798888ff1722dceba96d0e6/src/components/LHNOptionsList/OptionRowLHN.tsx#L243

It's to solve this [issue](https://github.com/Expensify/App/issues/40348) where the last message text of the workspace #admins chat contains an HTML tag. It was a BE issue because the last message text shouldn't include any HTML tag. The one that includes the HTML tag is the last message HTML.

### What changes do you think we should make in order to solve the problem?

Revert the change from https://github.com/Expensify/App/pull/40845.

I can't repro the BE issue anymore, if anyone can repro it, then it should be fixed on the BE first.

**Comment by abekkala** [comment] 2024-06-18 18:42
https://expensify.slack.com/archives/C01SKUP7QR0/p1718735202154699

**Comment by abekkala** [comment] 2024-06-21 11:57
this will be handled by SWM

**Comment by abekkala** [comment] 2024-06-24 18:29
Not overdue - SWM will be picking this up

**Comment by BartoszGrajdek** [comment] 2024-06-26 09:48
Hi! I'll be taking a look at the problem here later this week! 👀

**Comment by abekkala** [comment] 2024-06-26 18:44
Thanks @BartoszGrajdek

**Comment by abekkala** [comment] 2024-07-02 13:29
being worked on by SWM - @BartoszGrajdek

**Comment by BartoszGrajdek** [comment] 2024-07-03 19:03
Hi! I'm going OOO 4.07-7.07. At the beginning of next week, we'll check if there's anyone available to handle it @ SWM, we may have some more people available to work on this. 

I was busy handling issues with a higher priority in recent days, so sorry for the delay here 🙏🏻

**Comment by BartoszGrajdek** [comment] 2024-07-09 13:44
I've looked into this issue and it seems like @bernhardoj fix is working just fine - it's also the easiest one IMO. I didn't manage to reproduce the backend issue from https://github.com/Expensify/App/issues/40348. However, it doesn't mean that won't happen again - maybe in a different scenario. 

Not sure how we want to proceed here. Personally, I think we can just go with @bernhardoj solution because ultimately things like these should be handled by the backend, but maybe the `parser.htmlToText` is desired as a safety net. 

Let me know what you think! @abekkala  🙌🏻

**Comment by abekkala** [comment] 2024-07-12 20:10
@BartoszGrajdek Ok, we can proceed with the fix proposed by @bernhardoj 
We can get an internal engineer to weigh in on 

> maybe the parser.htmlToText is desired as a safety net.

**Comment by abekkala** [comment] 2024-07-12 20:13
🎀 👀 🎀

**Comment by mallenexpensify** [comment] 2024-07-24 16:58
@eVoloshchak can you review the above then add 🎀 to assign an engineer, if needed.  thx

**Comment by mallenexpensify** [comment] 2024-07-29 23:34
@eVoloshchak👀 [above](https://github.com/Expensify/App/issues/43563#issuecomment-2248495969) plz.

**Comment by eVoloshchak** [comment] 2024-07-30 18:07
I agree with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/43563#issuecomment-2163070937), we should remove the conversion. 
This ends up creating an inconsistency between how message is presented in LHN and in the actual chat window
<img width="1511" alt="Screenshot 2024-07-30 at 20 05 52" src="https://github.com/user-attachments/assets/7b005b35-d5e5-49dc-a855-43f215e74dff">

We have to add test steps to make sure we aren't breaking both https://github.com/Expensify/App/issues/40348 and https://github.com/Expensify/App/issues/41141

🎀👀🎀 C+ reviewed!

**Comment by bernhardoj** [comment] 2024-08-01 05:43
PR is ready

cc: @eVoloshchak

**Comment by abekkala** [comment] 2024-08-20 13:31
@eVoloshchak is there a delay in reviewing this one?

**Comment by bernhardoj** [comment] 2024-08-20 15:17
Oh, I forgot about this one, but we actually [needs a BE fix to be able to merge the PR](https://github.com/Expensify/App/pull/46638#issuecomment-2262086438).

**Comment by bernhardoj** [comment] 2024-08-21 10:23
@bondydaa can you check if you can handle the BE issue?

**Comment by bondydaa** [comment] 2024-08-21 16:43
okay actually after discussing this with the team, I was mistaken on the intended behavior here and this isn't actually a bug and shouldn't have been assigned out.

This is working as intended, as was written on https://github.com/Expensify/App/pull/40845/. 

we don't actually want to support HTML in messages, when sending something like 
<img width="370" alt="image" src="https://github.com/user-attachments/assets/5e344b4c-012f-438d-a7bf-66bcb5cea797">

we still consider that just text not actually HTML. 

we want to have the support for the markdown parsing / html stripping in the LHN which means that text like `<p>this is a test of html tags</p>` only shows up like `this is a test of html tags` which we are fine with.

closing this out and the associated PR, sorry about that!

**Closed by bondydaa** 2024-08-21 16:43 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by bernhardoj** [comment] 2024-08-21 16:52
> we still consider that just text not actually HTML.

> <p>this is a test of html tags</p> only shows up like this is a test of html tags which we are fine with.

I can't access the internal disc, but if we consider it as a text, shouldn't we show the text as it is in the last message just like before? Also, if we type any HTML tag in a code block, the HTML tag will be removed too. For example, if we send,

````
here is the code: `<a>test</a>`
````

the last message will be: here is the code: test

If we follow WhatsApp for example, they just show the text as it is.
<img width="212" alt="image" src="https://github.com/user-attachments/assets/6fc12a2f-6aa1-4a6a-8e1f-e1b5bd1e9932">
