### ISSUE TITLE
[$1000] Chat - Nothing happens on click of mark as unread option on [Deleted message] message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22186] opened 2023-07-04 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send any message
3. Hover of that message and select reply in thread option
4. Go to thread
5. Send any message in thread
6. Delete first message of thread which is parent message
7. Go back to parent report screen
8. Hover on [Deleted message]  option and click on mark as unread  option

## Expected Result:
Message should be mark as unread and New indicator line should show

## Actual Result:
The new unread indicator is added, but the chat row in the LHN is not bold to mark it as unread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

Original: 
https://github.com/Expensify/App/assets/93399543/e7df802d-2b95-47ba-b0e0-ff2d3ee61988
https://github.com/Expensify/App/assets/93399543/aa3e2059-5771-4754-a16a-311149675985

Latest retest:
<img width="1199" alt="image" src="https://github.com/Expensify/App/assets/16232057/cc55caa0-3b17-46e9-b04d-770ce507b567">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688463329453089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01916889bd02b24df2</li>
        <li>Upwork Job ID: 1676507628036976640</li>
        <li>Last Price Increase: 2023-07-05</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-07-05 08:21
I reproduced this now 👍

**Comment by s-alves10** [comment] 2023-07-05 09:33
This is an opposite issue of https://github.com/Expensify/App/issues/20759?

**Comment by s-alves10** [comment] 2023-07-05 11:32
Backend should calculate the lastVisibleActionCreated considering the deleted parent action

**Comment by mananjadhav** [comment] 2023-07-10 17:19
Because this also requires a backend fix, I am going to tag an internal engineer for discussion.

🎀 👀 🎀 C+ reviewed, no proposals shortlisted yet.

**Comment by marcochavezf** [comment] 2023-07-11 17:52
Hi @conorpendergrast, yes, I'm already working on a fix for this on the back-end, so it should be internal

**Comment by conorpendergrast** [comment] 2023-07-11 19:52
Seems like we don't need @mananjadhav here, so unassigning you too!

**Comment by conorpendergrast** [comment] 2023-07-14 12:22
Looks like Marco is working to optimising a query, via the WIP PR

**Comment by marcochavezf** [comment] 2023-07-14 17:11
Updated CQ and asked for it's timing

**Comment by marcochavezf** [comment] 2023-07-17 15:50
Bumped for timing the updated CQ [here](https://expensify.slack.com/archives/C03TQ48KC/p1689608995339709)

**Comment by marcochavezf** [comment] 2023-07-18 16:44
The updated CQ has better performance, now we'll time a [large CQ](https://github.com/Expensify/Auth/pull/8259#issuecomment-1640557840) that can be impacted by the updated CQ.

**Comment by marcochavezf** [comment] 2023-07-21 15:31
[Bumped](https://expensify.slack.com/archives/C03TQ48KC/p1689953456289479) for help to time the CQ

**Comment by marcochavezf** [comment] 2023-07-28 19:57
PR is still in review

**Comment by marcochavezf** [comment] 2023-07-31 18:26
> PR is still in review

**Comment by marcochavezf** [comment] 2023-08-01 18:33
Bumped reviewer in [PR](https://github.com/Expensify/Auth/pull/8259)

**Comment by conorpendergrast** [comment] 2023-08-03 12:20
Looks like PR has feedback and Marco is working on that!

**Comment by marcochavezf** [comment] 2023-08-07 21:10
No update

**Comment by marcochavezf** [comment] 2023-08-16 18:01
No update, moving this weekly, focused on bugs with customers and wave7

**Comment by conorpendergrast** [comment] 2023-09-11 12:51
@laurenreidexpensify I'm on parental leave; re-assigning! @marcochavezf is working on a PR for this, as an internal fix

**Comment by laurenreidexpensify** [comment] 2023-09-20 14:05
@marcochavezf what's the latest on this one?

**Comment by laurenreidexpensify** [comment] 2023-10-05 10:52
@marcochavezf bump, what is the latest here?

**Comment by marcochavezf** [comment] 2023-10-05 19:23
I'm a bit swamped with other items. The query I wrote first seems it's not working, we should recreate the query or look for another solution.

**Comment by laurenreidexpensify** [comment] 2023-10-13 13:12
@conorpendergrast re-adding you now that you back from parental leave :)

**Comment by conorpendergrast** [comment] 2023-10-18 09:56
@marcochavezf Hey! Which approach are you going to take for this; recreate the query or look for another solution?

**Comment by conorpendergrast** [comment] 2023-10-25 10:47
@marcochavezf Bump!

**Comment by conorpendergrast** [comment] 2023-11-01 13:25
@marcochavezf Bumpity bump the third!

**Comment by marcochavezf** [comment] 2023-11-01 13:27
Oops I have other items with higher priority, I will try to make space for this one this week

**Comment by conorpendergrast** [comment] 2024-01-16 20:56
I'm looking to make this a #vip-vsb issue, and have posted to the internal Slack channel to confirm that https://expensify.slack.com/archives/C066HJM2CAZ/p1705438540668619

**Comment by conorpendergrast** [comment] 2024-01-29 16:34
Ah, I never got confirmation on that. Checking now

**Comment by quinthar** [comment] 2024-01-29 17:13
Assigning to VSB.  @marcochavezf above it says you were working on a fix, whatever happened with that?  Think you can knock it off our list?

**Comment by trjExpensify** [comment] 2024-02-14 02:16
Taking this over. Since this issue was reported, it looks like the actual results have changed slightly - so I updated that. When I mark as unread a `[Deleted message]` parent comment, the unread marker is added now, but the LHN chat row is still not bold to signal that it's unread:

<img width="1199" alt="image" src="https://github.com/Expensify/App/assets/16232057/3318d2a4-eff2-495b-9487-2ce4f3c3bf90">

Summarising the issue history to date (largely for my benefit:

- This issue has been open since last July
- We had an external proposal [here](https://github.com/Expensify/App/issues/22186#issuecomment-1621568828) but it's determined this requires backend work to fix.
- Marco opened [a PR](https://github.com/Expensify/Auth/pull/8259) in July, but it's stale and untouched since August. 
- Last [update in Oct](https://github.com/Expensify/App/issues/22186#issuecomment-1749510577) highlighted looking for another solution: _"The query I wrote first seems it's not working, we should recreate the query or look for another solution."_
- At this point, I don't think we should have the `Reviewing` label on this issue because the PR is stale, so I've removed that. I've also put this on `Weekly` as a LOW instead of `Daily`.

@MonilBhavsar given your work on this area with the unread indicators, do you think this issue still requires backend work and/or have a suggestion here to help @marcochavezf move this along? Thanks!

**Comment by mananjadhav** [comment] 2024-02-14 04:02
@trjExpensify In case this is External given the updated behavior, do you want a C+? I was unassigned as it was internal and backend.

**Comment by MonilBhavsar** [comment] 2024-02-14 05:56
Idea looks good 👍 
> The query I wrote first seems it's not working, we should recreate the query or look for another solution.

I agree with this. We should be updating the logic in GetChats query where lastVisibleActionCreated time is added to response.

**Comment by MonilBhavsar** [comment] 2024-02-14 06:33
Looks like we now have `isDeletedParentAction` data piece in messageJSON and that will be helpful in this case

**Comment by trjExpensify** [comment] 2024-02-14 13:17
>@trjExpensify In case this is External given the updated behavior, do you want a C+? I

Yep, will add you back if it goes `External`. 

>Looks like we now have isDeletedParentAction data piece in messageJSON and that will be helpful in this case

Do you mind elaborating? Does that mean to say we have the necessary data needed now to fix bolding the chat row in the LHN when marked as unread in this case, or do we still have backend work to do here?

**Comment by MonilBhavsar** [comment] 2024-02-14 14:39
We still need to update backend to fix this issue. I meant we now have a simple way to check if message is a deleted parent report or not as opposed to a complex query.
I think this difference most probably fixes the issue https://github.com/Expensify/Auth/compare/monil-fixUnreadThread?expand=1

**Comment by trjExpensify** [comment] 2024-02-14 15:27
Okay, great. Thanks! Given you've got the insight on this, do you fancy taking it on so we can close the loop on this finally?

**Comment by MonilBhavsar** [comment] 2024-02-15 14:45
Can co assign and give it a try!

**Comment by trjExpensify** [comment] 2024-02-15 16:10
That would be great! Done!

**Comment by MonilBhavsar** [comment] 2024-02-20 05:31
This issue is fixed by Auth PR so closing

**Closed by MonilBhavsar** 2024-02-20 05:31 UTC
Labels: Reviewing, Weekly, Internal, Bug
