### ISSUE TITLE
[Awaiting Payment Sept 15th][$125] Room-mWeb-Inconsistency in Character allowed to create room from fab & via mentions

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48168] opened 2024-08-28 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4896867
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab - start chat -- room
3. Paste the room name - 345688988765544445665555444555455555555555555555555555555552357777dfghgggggggg5muuuddu
4. Create a room
5. Via mentions create another room with same number of characters - 345688988765544445665555444555455555555555555555555555555552357777dfghgggggggg6muuuddp
6. Note user not shown whisper to create room with all characters entered

## Expected Result:
There must be consistency in Character allowed to create room from fab & via mentions.

## Actual Result:
Inconsistency in Character allowed to create room from fab & via mentions.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8cf9e4c0-a756-4907-907f-0ffcde81a30f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f61735c851b2aec</li>
        <li>Upwork Job ID: 1829102787350296440</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 103992433</li>
<li>NJ-2020 | Contributor | 103992435</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-08-28 12:30
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by NJ-2020** [comment] 2024-08-28 12:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room-mWeb-Inconsistency in Character allowed to create room from fab & via mentions
### What is the root cause of that problem?
Inside the expensify-common, we limit up to 80 characters only
https://github.com/Expensify/expensify-common/blob/331f53580a4ddd7f1c8e73c7c1494d0bb22962c7/lib/ExpensiMark.ts#L298-L303
```ts
{
    name: 'reportMentions',
    regex: /(?<![^ \n*~_])(#[\p{Ll}0-9-]{1,80})(?![^<]*(?:<\/pre>|<\/code>|<\/a>))/gimu,
    replacement: '<mention-report>$1</mention-report>',
},
```
But here in our case we mention the room name more than 80 characters, which 87 in our case
### What changes do you think we should make in order to solve the problem?
We can change the limit to 100 or 90, so it will be:
```ts
{
    name: 'reportMentions',
    regex: /(?<![^ \n*~_])(#[\p{Ll}0-9-]{1,100})(?![^<]*(?:<\/pre>|<\/code>|<\/a>))/gimu,
    replacement: '<mention-report>$1</mention-report>',
},
```
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-08-28 13:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Room-mWeb-Inconsistency in Character allowed to create room from fab & via mentions

### What is the root cause of that problem?
We are allowing only 80 characters when we parse reportMenions in [common](https://github.com/Expensify/expensify-common/blob/331f53580a4ddd7f1c8e73c7c1494d0bb22962c7/lib/ExpensiMark.ts#L298-L303) But the room name character limit we are using in FE is 90 here
https://github.com/Expensify/App/blob/ac5ee2ef790231c67ca3ddb14dc481d77da5bcea/src/CONST.ts#L917
### What changes do you think we should make in order to solve the problem?

We need to be consistent and pick a max limit value and ensure that same value is used in both places
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-08-29 10:24
I agree we should be consistent here, but this is a quick fix, so I'm dropping the price.

**Comment by NJ-2020** [comment] 2024-09-03 07:46
### [Proposal updated](https://github.com/Expensify/App/issues/48168#issuecomment-2315236567)
 * Added a minor explanation about the react-native-live-markdown,

**Comment by alitoshmatov** [comment] 2024-09-03 16:30
Seems very straightforward task and all proposals are suggesting the same solution. 
I think we can go with @NJ-2020 's [proposal](https://github.com/Expensify/App/issues/48168#issuecomment-2315236567). Even without edits his original proposal suggested to update mention name length

C+ reviewed 🎀 👀 🎀

**Comment by NJ-2020** [comment] 2024-09-05 12:55
@alitoshmatov PR ready for review

**Comment by trjExpensify** [comment] 2024-09-09 18:36
Payment summary as follows: 

- $125 to @NJ-2020 for the fix 
- $75 to @alitoshmatov for the C+ review of the proposal

Doesn't look like @alitoshmatov actually reviewed [the PR here](https://github.com/Expensify/expensify-common/pull/796), so I reduced partial payment of $75 for the proposal review only. 

Let me know if that's correct, and I'll issue payments after the regression period.

**Comment by trjExpensify** [comment] 2024-09-09 22:12
Melv, go away. @alitoshmatov @NJ-2020, we might need a version bump of expensify-common here actually?

**Comment by NJ-2020** [comment] 2024-09-09 22:59
@trjExpensify Yes we need to bump the expensify-common to the latest version

**Comment by trjExpensify** [comment] 2024-09-10 00:40
Cool, and will you raise a PR for that?

**Comment by NJ-2020** [comment] 2024-09-10 10:08
@trjExpensify PR ready

Just to confirm that we only need to update the expensify-common version to the latest version inside react-native-live-markdown only?

**Comment by trjExpensify** [comment] 2024-09-10 10:28
I'll defer to @alitoshmatov on that. 👍

**Comment by alitoshmatov** [comment] 2024-09-11 15:17
@trjExpensify Everything looks good for me

**Comment by trjExpensify** [comment] 2024-09-11 21:00
Great, so we should be good here when payment is due.

**Comment by trjExpensify** [comment] 2024-09-16 22:13
Okay, [offers](https://www.upwork.com/ab/applicants/1829102787350296440/offers) have been sent. Please accept, and I'll modify accordingly to match [this payment summary](https://github.com/Expensify/App/issues/48168#issuecomment-2338824904) and close it out.

**Comment by trjExpensify** [comment] 2024-09-18 14:37
Settled up, closing!

**Closed by trjExpensify** 2024-09-18 14:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
