### ISSUE TITLE
[Payment due 3-7][$500] [MEDIUM] Connect Bank Account - No limit for entering amount in transition field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33065] opened 2023-12-14 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS or create it -> Bank account -> Connect manually
4. Use our Fake Test account and `Save and Continue` through all these steps: 

- Routing `011401533` 
- Account Number `1111222233331111` 
- Company Name `create any name, address, phone, tax ID, company type, incorporation date`
- Personal Info `create any name, address, SSN can be 3333`
- Go through the Onfido step of uploading an ID/passport

5. When you finish the flow - the modal asks for 3 amounts of test transactions
6. There is no character limit on the 3 test transaction fields of the Test Transactions page

## Expected Result:
Limit for entering an amount in the transition field presents

## Actual Result:
No limit for entering amount in transition field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b57c04cb-7db8-40dc-959f-1a7850f5949e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec80ed70582379a7</li>
        <li>Upwork Job ID: 1735304593582518272</li>
        <li>Last Price Increase: 2024-01-04</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment] 2023-12-14 14:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Connect Bank Account - No limit for entering amount in transition field

### What is the root cause of that problem?
We don't pass the `maxLength` prop here:
https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/ReimbursementAccount/ValidationStep.js#L159-L187

### What changes do you think we should make in order to solve the problem?
We should pass the maxLength prop like we do in other areas of the app:

```js
maxLength={CONST.FORM_CHARACTER_LIMIT}
```

**Comment by sfurqan2** [comment] 2023-12-14 14:34
Dont you think we should create a new CONST to handle this? I dont think 50 is the precise limit either.

So we can add a const like CONST.BANK_ACCOUNT.MAX_LENGTH.AMOUNT and specify the value there. As this is test amounts i dont think they will be more than 6 digits. 

What do you think? @ZhenjaHorbach  @neonbhai

**Comment by neonbhai** [comment] 2023-12-14 14:49
@sfurqan2 Thank you for the comment, it does seem like 50 might be too much for the verification transaction amount, but I've suggested the limit since we use this const globally for form character limit. Let's see if the C+ team has thoughts on this while reviewing.

**Comment by neonbhai** [comment] 2023-12-14 14:54
## Proposal 
### [Updated](https://github.com/Expensify/App/issues/33065#issuecomment-1855954828)

Added an Alternative approach with another const limiting the text field to few characters for better UX

**Comment by sourcecodedeveloper** [comment] 2023-12-14 14:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When connecting bank account manually, no limit for entering test amounts transactions.

### What is the root cause of that problem?

On validate(), the length is not being validated for the transition fields.

### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/207d4ac23598dd10dad0275344d750b62b67a4a3/src/pages/ReimbursementAccount/ValidationStep.js#L86
Need to add validation to check length for the three amounts (amount1, amount2, amount3).

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2023-12-14 16:57
I think this does need to be fixed (maybe a medium priority) and could be fixed as part of the VBA updates on Wave 6 - going to add to that wave for review to determine the priority of fixing this.

**Comment by abdulrahuman5196** [comment] 2023-12-18 08:04
Will review today.

**Comment by abdulrahuman5196** [comment] 2023-12-19 10:24
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-12-19 10:27
@Christinadobrzyn some questions on the issue

1) What is the limit we are expecting? like 10 digits or something else

2) Could you share steps to test "Pending State Withdrawal Account" ?

**Comment by Christinadobrzyn** [comment] 2023-12-19 22:19
Yep! working on these answers with our curators  https://expensify.slack.com/archives/C02MW39LT9N/p1703024244988059

I'll follow up as soon as possible!

**Comment by Christinadobrzyn** [comment] 2023-12-20 19:26
working on the answers to https://github.com/Expensify/App/issues/33065#issuecomment-1862501486

**Comment by Christinadobrzyn** [comment] 2023-12-21 19:17
Hi @abdulrahuman5196 answers to your question: 

- `What is the limit we are expecting? like 10 digits or something else` - let's make it a 20 digit limit

- Could you share steps to test "Pending State Withdrawal Account" ? Yes, I added those details to the OP. 

Let me know if you need anything else!

**Comment by Christinadobrzyn** [comment] 2023-12-21 21:57
Hi @ZhenjaHorbach Only looking at the Test Transactions screen - all three amount fields would have this 20 limit 

![image](https://github.com/Expensify/App/assets/51066321/f9c0e8c7-8167-47ca-a631-c36e844f26dc)

**Comment by abdulrahuman5196** [comment] 2023-12-25 12:11
Hi, Thank you for the confirmation. I will close out on proposal before tomorrow.

**Comment by abdulrahuman5196** [comment] 2023-12-28 18:05
Sorry for the delay. Will close out over my morning.

**Comment by abdulrahuman5196** [comment] 2024-01-01 14:32
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-01 15:21
@Christinadobrzyn I am unable to get the issue page. Could you kindly let me know if I am missing something?


https://github.com/Expensify/App/assets/46707890/0bf12bc1-1d43-4ddc-9165-2eeacf7cc605

**Comment by Christinadobrzyn** [comment] 2024-01-03 00:56
Hi @abdulrahuman5196 I'm not sure what you mean by 

> I am unable to get the issue page. Could you kindly let me know if I am missing something?

Are you enable to get the the test transaction page?

**Comment by abdulrahuman5196** [comment] 2024-01-03 06:41
> Hi @abdulrahuman5196 I'm not sure what you mean by 
> 
> > I am unable to get the issue page. Could you kindly let me know if I am missing something?
> 
> Are you enable to get to the test transaction page to test?

@Christinadobrzyn I don't get the test transaction page, not sure if my account need to be in some kind of settings?

**Comment by Christinadobrzyn** [comment] 2024-01-03 22:06
Ah okay! Do you have access to the steps in this [SO](https://stackoverflowteams.com/c/expensify/questions/342/525#525) to get the Pending business bank account state?

If not, here's what it says, maybe this is better than what's in the OP (I can update it if these work)

To create a PENDING bank account (this state means we're waiting for the user to enter the 3 validation amounts he received):

- Add Bank Account (note: in order to access this flow on NewDot, use the URL staging.new.expensify.com/bank-account):
- Click Connect Manually
- Routing Number: 011401533
- Account number: 1111222233331111

**Company Info** (Enter the info below, and anything in non-specified fields):

- Legal Business Name: Alberta Bobbeth Charleson
- Company website: Enter any valid formatted website
- Tax ID number: 123456789 (any nine digits)
- Industry classification code: 123456 (any six digits)
- Confirm company is not on list of restricted businesses
- Save & Continue

**Requestor Information** (Enter the info below, and anything in non-specified fields):

- First name: Alberta
- Second name: Charleson
- Last 4 SSN: 3333
- Toggle confirmation you are authorized to use company bank account

**Beneficial Owners:**

- Toggle terms and conditions
- Toggle confirmation that the information provided is true and accurate
- Validate

**Comment by Christinadobrzyn** [comment] 2024-01-04 21:57
Let me know how this is going @abdulrahuman5196 - thanks!

**Comment by Christinadobrzyn** [comment] 2024-01-08 00:33
I'm going to be ooo next week so adding a buddy to monitor this while I'm gone. 

Status- @abdulrahuman5196 is trying to reproduce this so we can work on a fix.

**Comment by abdulrahuman5196** [comment] 2024-01-08 19:33
Pending my check on this comment - https://github.com/Expensify/App/issues/33065#issuecomment-1876033423

**Comment by abdulrahuman5196** [comment] 2024-01-11 12:14
Reviewing now

**Comment by abdulrahuman5196** [comment] 2024-01-11 15:52
I was still unable to get a account in pending state. Anyways I code modified and came to the test transactions page for testing.

@ZhenjaHorbach 's proposal here https://github.com/Expensify/App/issues/33065#issuecomment-1855951686 looks good and works well. It was the first to suggest `maxLength` prop to fix the issue. 

🎀 👀 🎀
C+ Reviewed

**Comment by NikkiWines** [comment] 2024-01-11 18:39
The bank account flow is being refactored so I'm not sure this should be updated at this time (cc: @mountiny for your input) 

I also kind of think this isn't really a bug - there's no reason a user to would intentionally want to enter that many digits into this field and the fact that there isn't an error or limit isn't necessarily wrong, it's just kind of neutral.

**Comment by mountiny** [comment] 2024-01-11 23:19
@NikkiWines I agree I think we can put this on hold for the refactor and fix as a polish there

**Comment by sonialiap** [comment] 2024-01-15 11:16
@NikkiWines @mountiny are you guys ok with me moving this to `weekly`?

**Comment by mountiny** [comment] 2024-01-15 12:17
yes, even monthly, we could do that

**Comment by sonialiap** [comment] 2024-02-15 16:58
Is the VBA refactor still ongoing? If yes, is there a tracking issue for it?

**Comment by NikkiWines** [comment] 2024-02-20 22:55
I think the VBBA refactor is complete now but CC: @mountiny to confirm

**Comment by mountiny** [comment] 2024-02-20 23:42
Correct, this is no completed! this can be worked on

**Comment by abdulrahuman5196** [comment] 2024-02-21 12:04
Hi, Are we tracking to fix this internally or with the already reviewed proposal?

**Comment by NikkiWines** [comment] 2024-02-22 02:24
Oh, this can definitely be external. @ZhenjaHorbach's proposal you reviewed [earlier](https://github.com/Expensify/App/issues/33065#issuecomment-1887461756) looks good. @ZhenjaHorbach are you still interested in taking on this issue? 

If not, we'll open this up to new proposals!

**Comment by Christinadobrzyn** [comment] 2024-02-27 01:06
PR is in staging - getting close! https://github.com/Expensify/App/pull/37106

**Comment by abdulrahuman5196** [comment] 2024-03-05 09:25
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

No a regression. Seems to be the case for sometime.

>Determine if we should create a regression test for this bug.
If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. Wouldn't be benificial to add for this UX case bug.

@Christinadobrzyn Added BZ checklist. This is for payment due on March 7th. But seems melvin didn't auto update here.

**Comment by Christinadobrzyn** [comment] 2024-03-05 21:03
Thanks for the heads up @abdulrahuman5196! 

Can we confirm this is the payment for March 7th (assuming no regressions)? 

Contributor: $500 @ZhenjaHorbach (in Upwork)
Contributor+: $500 @abdulrahuman5196 (in Upwork)

Upwork job is [here](https://www.upwork.com/ab/applicants/1735304593582518272/job-details).

**Comment by abdulrahuman5196** [comment] 2024-03-07 14:23
@Christinadobrzyn I think the offer has been accepted already. Do let me know if there is some issue.

**Comment by Christinadobrzyn** [comment] 2024-03-08 02:47
No issue with the offer - just adding them to the [payment summary](https://github.com/Expensify/App/issues/33065#issuecomment-1979631164) for tracking/easy reference. 

This is paid out - closing!

**Closed by Christinadobrzyn** 2024-03-08 02:47 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
