### ISSUE TITLE
[HOLD for payment 2024-03-29] [$500] [Wave Collect] [Ideal Nav] Incorrect animation direction on Wallet and Troubleshooting page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37359] opened 2024-02-27 22:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause -Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/37078
## Action Performed:
Pre-requisite: user must be logged in and have an Expensify card assigned
1. Go to Settings > Wallet
2. Tap on Expensify card
3. Tap on the back button

1. Tap on the avatar to open the `account settings`
2. Tap `about`
3. Tap `troubleshoot`
4. Then Tap `<`until you reach `LHN`
5. Observe the sliding behavior

## Expected Result:
A transition animation from left to right should appear (going back to previous page)

____

Opening each page `account settings, about and troubleshoot`should slige from the right overtop of the previous page and When pressing `<` button the page should slide away to the right 

## Actual Result:
A transition animation from right to left appears (as if it were a new page, not a previous one)

____

When pressing back button Troubleshoot page, About page slides in from the right, again, overtop Troubleshoot
Similarly pressing back button again,  Profile slides in from the right
Finally, pressing back button, Account Settings slides away to the right  which is the correct behavior

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b7bfa84-f639-41ed-808d-aded99903c2d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01588c7a6a3b8f24cb</li>
        <li>Upwork Job ID: 1762991723171692544</li>
        <li>Last Price Increase: 2024-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-02-27 22:27
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Santhosh-Sellavel** [comment] 2024-03-05 16:20
> Pre-requisite: user must be logged in and have an Expensify card assigned

@kadiealexander Can contributor/C+ get an account with Expensify card or enable one?

**Comment by godofoutcasts94** [comment] 2024-03-05 16:22
i don't think a contributor can get Expensify card. @Santhosh-Sellavel

**Comment by kadiealexander** [comment] 2024-03-08 04:03
Asking about this internally [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1709870615943059).

**Comment by brunovjk** [comment] 2024-03-11 11:39
I managed to reproduce the same issue in the 'Troubleshoot' tab:
<details>
<summary>repro_37359</summary>


https://github.com/Expensify/App/assets/95647348/4149b0a2-f9db-43d9-a667-3c601432722a

</details>

**Comment by kadiealexander** [comment] 2024-03-11 21:52
@Expensify/design would love your thoughts on whether this is worth fixing! We're trying to focus on bugs that align with a #wave and are affecting the usability of the site, which this isn't really.

**Comment by dubielzyk-expensify** [comment] 2024-03-12 04:02
This is worth fixing imo cause it's very disorienting for the animation to go forward when in reality you're going back. I also recon this should be a reasonably quick fix as it looks like a regression.

The expected behavior is that the screen animates off screen to the right when tapping back.

**Comment by shawnborton** [comment] 2024-03-12 12:27
Agree.

cc @luacmartins @mountiny @trjExpensify as I think this is related to the weird `goBack` bugs we've seen - not sure if we have another issue that is tracking those improvements or if we should treat this as a separate bug.

**Comment by trjExpensify** [comment] 2024-03-12 18:25
Yeah, I think it's worth fixing. @adamgrzybowski is spearheading sprucing up goBack, but I believe Adam has been OoO for a bit until today. This is the issue for the refactor: https://github.com/Expensify/App/issues/35938 CC: @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2024-03-12 20:24
thank you Tom for letting me know about the issue 🙇 

I've included this issue in the Wave Collect project. Additionally, I've commented on related issues to determine if this problem will be resolved alongside them.

**Comment by luacmartins** [comment] 2024-03-12 20:57
I noticed that we have [this PR](https://github.com/Expensify/App/pull/37998) and [issue](https://github.com/Expensify/App/issues/37982) in the checklist that seems to fix the right/left animation for wallet pages

**Comment by mountiny** [comment] 2024-03-12 21:01
Taking this one on

@Santhosh-Sellavel Can you check the proposal from @apeyada I think it should work. cc @bernhardoj also fixed a similar issue recently https://github.com/Expensify/App/pull/37998

**Comment by mountiny** [comment] 2024-03-12 21:26
@apeyada @GandalfGwaihir Can we please get a proposal which treats this on all the pages there you can find the same issue? We do not want to be create issues for each individual page. As part of the proposal, can you also list all the other pages which suffer with this issue? Thanks!

**Comment by mountiny** [comment] 2024-03-12 22:32
Yep I think we can increase the value given you will handle all the pages suffering with this issue. Can you confirm however, that deeplinking to these pages, either on desktop or in narrow view will still keep the < button functionality as expected? 

Can you include tests in the PR for all the pages please? thats also for the QA to make sure they verify all of them.

Thank you 🙇

**Comment by Santhosh-Sellavel** [comment] 2024-03-14 17:04
Waiting for updates on PR

> Will test it tomorrow:) and update on the PR accordingly

**Comment by allroundexperts** [comment] 2024-03-17 18:50
Taking over. @kadiealexander Can you please assign this issue and the PR to me?

**Comment by mountiny** [comment] 2024-03-31 20:04
$500 to @allroundexperts and $500 to @GandalfGwaihir

**Comment by kadiealexander** [comment] 2024-04-03 05:12
@GandalfGwaihir I can't find you on Upwork, can you please apply [here](https://www.upwork.com/jobs/~01588c7a6a3b8f24cb)?

@allroundexperts please don't forget the checklist!

**Comment by kadiealexander** [comment] 2024-04-04 04:10
Offer sent :)

**Comment by kadiealexander** [comment] 2024-04-09 04:54
@allroundexperts please complete the checklist so we can get this closed out.

**Comment by allroundexperts** [comment] 2024-04-10 10:22
On it today.

**Comment by allroundexperts** [comment] 2024-04-11 20:52
## Checklist
1. There isn't a single PR which introduced this. I think over the time, we were just following the same pattern, and as a result we had a bunch of pages with similar problem.
2. N/A
3. N/A
4. A regression test would be useful. The steps mentioned un the OP look good enough to me!

**Closed** 2024-04-15 07:43 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by kadiealexander** [comment] 2024-04-15 07:44
Payment summary [here](https://github.com/Expensify/App/issues/37359#issuecomment-2033542014).

**Comment by JmillsExpensify** [comment] 2024-04-30 23:03
$500 approved for @allroundexperts
