### ISSUE TITLE
[HOLD for payment 2023-09-04] [$1000] Not allowed sign does not show when an attachment is drag and dropped

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22218] opened 2023-07-04 20:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat and upload a picture
2. Open the picture uploaded
3. Open a file > drag and drop any picture without closing the picture shown.
4. Notice that not allowed sign is not shown
## Expected Result: 
Not allowed to drag and drop when an attachment is open.
## Actual Result: 
allowed to drag and drop when an attachment is open.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/aa717cd2-c601-4bed-b94c-48df70532e83

https://github.com/Expensify/App/assets/43996225/39639605-6a1b-487f-98a7-5a01812488f4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688500850249469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010870acccad3ed186</li>
        <li>Upwork Job ID: 1676676820896407552</li>
        2023-07-26<li>Automatic offers: </li>
<ul>
<li>daveSeife | Reporter | 25785739</li>
</ul></li>
    </ul>
</details>

**Comment by flaviadefaria** [comment] 2023-07-05 11:13
Just coming online, but @deetergp seems to be on it!

**Comment by Julesssss** [comment] 2023-07-05 13:45
This one is problematic. It looks like @deetergp located the original PR, but as we've already followed up with additional changes for other blockers I don't think we can simply revert it... 

Best course of action might be to unblock the release and resolve this without classing it as a blocker. I think this is fine as it's not blocking the user. 

We're already one day behind the release schedule and the alternative of reverting multiple PRs in a certain order is too time-consuming/complex and will prevent me from releasing.

**Comment by Julesssss** [comment] 2023-07-05 13:46
@kidroca it would be great if you could confirm/deny [our suspicion](https://github.com/Expensify/App/pull/20167#issuecomment-1620735660) about this. We'll need to fix but I'm moving forward with the app release.

**Comment by deetergp** [comment] 2023-07-05 19:37
I'd love @kidroca's thoughts on it, but I'm going to go ahead and apply the `External` label and open it up to proposals.

**Comment by rain2o** [comment] 2023-07-06 18:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Drag and drop is not prevented in the attachment preview modal.

### What is the root cause of that problem?

As suspected in previous comments, this is a result of the restructuring in #20167. Previously, `AttachmentModal` was a child of `ReportScreen`, and it benefited from the logic in [DragAndDrop](https://github.com/Expensify/App/blob/main/src/components/DragAndDrop/index.js), which prevents drag & drop outside of the specified area. Now that `AttachmentModal` is in its own `RootStack.Screen`, it no longer benefits from that logic.

### What changes do you think we should make in order to solve the problem?


We need to add these event handlers to [ReportAttachments](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportAttachments.js), as this is the top-level component for the new stack dedicated to showing attachment modals.

We can use the same logic as is in `DragAndDrop`, but much more simplified.
```javascript
const preventDropEvent = useCallback((event) => {
    event.preventDefault();
    // eslint-disable-next-line no-param-reassign
    event.dataTransfer.dropEffect = 'none';
}, []);

useEffect(() => {
    document.addEventListener('dragenter', preventDropEvent);
    document.addEventListener('drop', preventDropEvent);

    return () => {
        document.removeEventListener('dragenter', preventDropEvent);
        document.removeEventListener('drop', preventDropEvent);
    }
}, [preventDropEvent])
```

### What alternative solutions did you explore? (Optional)

We could wrap [ReportAttachments](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportAttachments.js) in the `DragAndDrop` component and set `shouldAcceptDrop` to always return `false`. But I think this would add unnecessary bloat to this stack, as there's a bit going on under the hood in that component.

**Comment by deetergp** [comment] 2023-07-10 20:34
@rain2o That proposal sounds good to me. Interested to hear how @thesahindia feels about it.

**Comment by kidroca** [comment] 2023-07-11 14:59
I think the alternative is better - simply wrap with the existing `DragAndDrop` component, why write the same code twice?

Keep in mind this is only for web, if you decide to duplicate the code, you'll have to dedicate a script or multiple scripts to handle all platforms, even though native would be noops - this again advocates to just use the existing component for the purpose (as outlined in the alternative approach)

**Comment by kidroca** [comment] 2023-07-11 16:19
By the way I wanted to bring up another point. Currently, the focus seems to be on preventing the drag-and-drop functionality solely on the attachment view. 

However, in my opinion, this approach may not be the most efficient one. I propose that we instead default to disabling drag-and-drop across the application and selectively enable it where needed, like on the compose screen. This should prevent us from dealing with similar issues on a case-by-case basis.

A pertinent example is the settings screen. At present, the drag-and-drop feature is not disabled there, leading to an identical problem where dragging and dropping a file opens the file in a new tab - why should this be allowed to happen on the settings screen, but not allowed to happen on the attachments screen?

**Comment by deetergp** [comment] 2023-07-11 16:47
That's a great point @kidroca. I think maybe a brief discussion about it is warranted in #expensify-open-source just to get buy-in from others and then we should make it a separate GH as it's bigger than just this bug.

**Comment by deetergp** [comment] 2023-07-11 16:51
Discussion here: https://expensify.slack.com/archives/C01GTK53T8Q/p1689094256959329

**Comment by deetergp** [comment] 2023-07-14 20:24
The discussion is starting to wind down and it looks like we are probably going to go with @kidroca's suggestion of disallowing D&D by default and only explicitly allowing it where intended.

**Comment by flaviadefaria** [comment] 2023-07-17 09:55
What's the latest here?

**Comment by flaviadefaria** [comment] 2023-07-24 12:54
It seems like we all agreed to go with @kidroca's suggestion as the desired outcome:

>However, in my opinion, this approach may not be the most efficient one. I propose that we instead default to disabling drag-and-drop across the application and selectively enable it where needed, like on the compose screen. This should prevent us from dealing with similar issues on a case-by-case basis.

**Comment by flaviadefaria** [comment] 2023-07-24 12:55
So I imagine we need any proposals to take the above into account.

**Comment by flaviadefaria** [comment] 2023-07-26 09:06
@thesahindia what are your thoughts on the above proposals?

**Comment by flaviadefaria** [comment] 2023-07-27 11:58
Perfect I just assigned @allroundexperts to the GH as the C+.

**Comment by ishpaul777** [comment] 2023-07-30 19:05
# Proposal
## Problem 
 Not allowed sign does not show when an attachment is drag and dropped

## Root Cause
The current behaviour of dragover event datatransfer dropeffect is "copy" 

## Solution 
Wrapping  ReportAttachments with NoDropZone will prevent the fails the drop and no new Tab opens

```jsx
 <NoDropZone>
         <AttachmentModal
            allowDownload
            defaultOpen
            report={report}
            source={source}
            onModalHide={() => Navigation.dismissModal(reportID)}
            onCarouselAttachmentChange={(attachment) => {
                const route = ROUTES.getReportAttachmentRoute(reportID, attachment.source);
                Navigation.navigate(route);
            }}
        /> 
 </NoDropZone>
```

**Comment by flaviadefaria** [comment] 2023-07-31 08:39
@allroundexperts what do you think of the updated proposals?

**Comment by kidroca** [comment] 2023-07-31 10:31
@allroundexperts 
> We recently implemented the `NoDropZone` component as part of [this](https://github.com/Expensify/App/pull/23528) PR. This was added to RHN only. I think we can leverage that in our models and in LHN.
> 
> Can we please get an updated proposal that takes into account the recent changes that we did in #23528 and #23589?

You appear to be advocating for the application of the `NoDropZone` component to each area of the application that should not accept drops. This seems to be at odds with @deetergp's comment:

> The discussion is starting to wind down and it looks like we are probably going to go with @kidroca's suggestion of disallowing D&D by default and only explicitly allowing it where intended.

If I recall correctly, the consensus from the discussion was to disallow Drag & Drop (D&D) by default and only explicitly allow it in designated areas. Did I misunderstand something, or has the preference shifted to disabling D&D individually in each part of the application?

**Comment by deetergp** [comment] 2023-08-01 01:26
> If I recall correctly, the consensus from the discussion was to disallow Drag & Drop (D&D) by default and only explicitly allow it in designated areas. Did I misunderstand something, or has the preference shifted to disabling D&D individually in each part of the application?

This is still the plan. We need D&D disabled everywhere and then enabled only in the areas where we want explicitly want to use it.

**Comment by flaviadefaria** [comment] 2023-08-02 13:50
@deetergp @allroundexperts what are the next steps here so that we can close this GH asap?

**Comment by kidroca** [comment] 2023-08-05 07:31
> @kidroca It seems like you've been an active part of the discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690855840796519). Do you mind submitting a proposal as well 😄?

My proposal would be similar to the existing - disable on the `document` level and then enable where appropriate with the provider component

**Comment by flaviadefaria** [comment] 2023-08-07 12:25
@allroundexperts thoughts on @ginsuma's proposal?

**Comment by deetergp** [comment] 2023-08-11 21:27
Let's go with @ginsuma's proposal, making sure to address what @allroundexperts mentioned, in the PR:
> One thing that I noticed is that after applying the changes, any popover already opened closes when an image is dragged over it.

**Comment by flaviadefaria** [comment] 2023-09-05 17:36
Payment summary:

>For reference, here are some details about the assignees on this issue:
@ginsuma requires payment
@allroundexperts does not require payment (Eligible for Manual Requests)
@daveSeife requires payment [offer](https://www.upwork.com/nx/wm/offer/25785739) (Reporter)

@ginsuma = $1000 (no bonus)
@allroundexperts = $1000 (no bonus)
@daveSeife = $250

**Comment by flaviadefaria** [comment] 2023-09-11 10:39
@ginsuma can you please share your UW profile here, I'm not sure that I have found the right person- thanks!
@daveSeife - Contract sent.

**Comment by flaviadefaria** [comment] 2023-09-11 11:00
Thanks, @ginsuma - contract sent.

**Comment by flaviadefaria** [comment] 2023-09-11 11:32
Oops, sorry about that, sent a new offer with the correct amount.

**Comment by flaviadefaria** [comment] 2023-09-11 11:38
@ginsuma - paid
@daveSeife - waiting to accept offer

**Comment by daveSeife** [comment] 2023-09-11 11:40
@flaviadefaria accepted offer, thank you!

**Comment by flaviadefaria** [comment] 2023-09-11 12:28
@daveSeife you have been paid.

>@allroundexperts does not require payment (Eligible for Manual Requests)
Please request payment I'll switch this to weekly for now.

**Comment by flaviadefaria** [comment] 2023-09-26 10:12
Cool seems like all payments have been requested or made so closing this for now.

**Closed by flaviadefaria** 2023-09-26 10:12 UTC
Labels: Engineering, Weekly, Internal, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 12:53
$1,000 payment approved for @allroundexperts based on BZ summary.
