### ISSUE TITLE
IOS - Keyboard covers the main composer when going to the thread and coming back

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23423] opened 2023-07-23 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with any account and go to any chat
2. Send any message and select reply in thread
3. Back to the main chat by clicking back button in the header
4. Set focus the main composer

## Expected Result:
Keyboard doesn't cover the main composer

## Actual Result:
Keyboard covers the main composer

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bcf1dccf-7724-46d6-af45-dbd90a62ae99

https://github.com/Expensify/App/assets/93399543/8db2e3cf-4275-45b4-ac7b-e7cebb22779a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @s-alves10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689948179939349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-23 22:50
### Please re-state the problem that we are trying to solve in this issue.

Keyboard covers the composer when going into the thread and coming back

### What is the root cause of that problem?

This is from the [PR](https://github.com/Expensify/App/pull/23024)

This is the known issue as in
https://stackoverflow.com/questions/64454207/keyboardavoidingview-react-navigation-safe-area-view-not-working
https://github.com/react-navigation/react-navigation/issues/11244

### What changes do you think we should make in order to solve the problem?

One workaround is to re-render the page when navigation back. We can do this by adding withNavigationFocus to the ReportScreen 

This works as expected.

### What alternative solutions did you explore? (Optional)

**Comment by isabelastisser** [comment] 2023-07-25 17:13
I can't reproduce this on iOS. Closing!

**Closed by isabelastisser** 2023-07-25 17:13 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by s-alves10** [comment] 2023-07-26 06:53
@isabelastisser 

This is still reproducible on ios native. I think we should reopen this issue

**Comment by s-alves10** [comment] 2023-07-31 12:09
@isabelastisser 

This is still reproducible. Please check
https://github.com/Expensify/App/assets/126839717/df61a5a3-e66a-417f-b2cc-4538b0777fc3

**Comment by s-alves10** [comment] 2023-08-16 18:38
@isabelastisser 

This is still reproducib;e. Let's reopen this
Please refer https://github.com/Expensify/App/issues/24555
