### ISSUE TITLE
mWeb Chrome - Blue box hightlight on parent div in LHN in help docs

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24050] opened 2023-08-02 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://help.expensify.com/hubs/split-bills on mobile device.
2. Open LHN and click on any of the links below Split bills.
3. Notice a blue highlight box appears around all the links i.e the parent div.
## Expected Result: 
The blue highlight should not appear at all because it does not appear in Safari/Chrome on IOS but only appears in Chrome on Android.
## Actual Result: 
A blue highlight box appears around all the links i.e the parent div.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/be4bf20b-8c1c-43af-9b81-adae15948c5a

https://github.com/Expensify/App/assets/43996225/a2461c61-89b2-411c-aa4a-40ece337065d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Talha345
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690473637347049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Talha345** [comment] 2023-08-02 12:22
### Note:

I posted this proposal with the Bug Report in Slack [here](https://app.slack.com/client/T03SC9DTT/C049HHMV9SM/thread/C049HHMV9SM-1690473637.347049) but the QA member forgot to add it to the issue so adding it here again and therefore I think it should be given priority to the proposal above.
 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
A blue highlight appears around the parent div when clicking on any of the sublinks below Split Bills in LHN on Chrome in Android.
### What is the root cause of that problem?
The behaviour of the tap highlight in Android Chrome is a design decision made by the browser's developers and therefore is the default behaviour. We already have a custom CSS to highlight the the link once it is clicked so we do not need this highlight.
### What changes do you think we should make in order to solve the problem?
Since this issue only appears in Android Chrome and we do not have any such highlights in Safari/Chrome on IOS, we should disable the blue highlight altogether which can be done by setting the following CSS property [here](https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/docs/_sass/_main.scss#L15-L22):
```
* {
    -webkit-tap-highlight-color: transparent; 
}
```
### What alternative solutions did you explore? (Optional)
N/A

**Comment by tjferriss** [comment] 2023-08-03 18:24
I'm going to close this as I think we should stick with the default behavior. This is not a bug that is preventing someone from using the app.

**Closed by tjferriss** 2023-08-03 18:24 UTC
Labels: Daily, Bug
