### ISSUE TITLE
Web - Admin can't flag a message on 'Admins only' post mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22311] opened 2023-07-05 20:58 UTC
https://github.com/Expensify/App/assets/93399543/50fa5f81-54ca-4180-a2a2-9de8bc9eee96

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account A is admin of an announce room X, and account B is a member
1. On the tab where account B is signed-in, open announce room X
2. Send message in the announce room
3. On the tab where account A is signed-in, open announce room X
4. Change who can post option to 'Admins only'
5. Flag the sent message with one of the flagging options

## Expected Result:
Admin should be able to flag the message

## Actual Result:
Admin cannot flag the message and system throw a technical error message (Auth CreateReportAction returned an error)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e40c51c6-0668-48b4-8c88-ecccbd0056a0

https://github.com/Expensify/App/assets/93399543/286e9d50-4baf-4a82-9da9-4dfd3c0f9723

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688507697557859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e0e4760439d37c7</li>
        <li>Upwork Job ID: 1676921863418765312</li>
        <li>Last Price Increase: 2023-07-06</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-06 04:47
Looks like Backend error.

**Comment by jasperhuangg** [comment] 2023-07-06 18:49
Yup, this looks like it has to be fixed internally cc @dangrous do you wanna look into this? I think it's the `FlagComment` Auth command

**Comment by dangrous** [comment] 2023-07-06 19:39
Oh interesting. Does Concierge not have permission to post when it's set to admins only? It seems to be an issue with posting the whispers, rather than flagging itself

**Comment by jasperhuangg** [comment] 2023-07-07 20:59
> Oh interesting. Does Concierge not have permission to post when it's set to admins only? It seems to be an issue with posting the whispers, rather than flagging itself

yup, just reproduced it on dev, here's the error message, which originates from [this line](https://github.com/Expensify/Auth/blob/main/auth/command/CreateReportAction.cpp#L52-L56):

```
[info] Error processing command 'CreateReportAction' (401 Non-admins can't create comment actions on admin-only reports), ignoring.
```

Should we make it so that Concierge always bypasses this particular check? Makes sense since a lot of our system whispers and other messages could potentially come from Concierge.

**Comment by dangrous** [comment] 2023-07-07 21:06
Yep that sounds like a good idea!

**Comment by jasperhuangg** [comment] 2023-07-07 21:09
@dangrous Thanks! I posted in Slack [here](https://expensify.slack.com/archives/C04QEB4MJEQ/p1688764123182969) to get more eyes on this.

**Comment by dangrous** [comment] 2023-07-12 19:55
This is merged to prod, right? y no automated posts?

**Comment by jasperhuangg** [comment] 2023-07-13 21:48
yerp it's on prod, closing

**Comment by Natnael-Guchima** [comment] 2023-07-14 05:18
@jasperhuangg I haven't been paid for reporting bonus.

**Comment by dangrous** [comment] 2023-07-14 14:19
reopening for payment!

**Comment by NicMendonca** [comment] 2023-07-14 15:19
@Natnael-Guchima can you please apply to the job? https://www.upwork.com/jobs/~010e0e4760439d37c7

**Comment by Natnael-Guchima** [comment] 2023-07-14 15:29
@NicMendonca I can't apply to job. It says it is a private job posting. Please, invite me to job if possible. Here is a link to my Upwork profile: https://www.upwork.com/freelancers/~0135b3a84ec2709c21

Thanks. 

![Screenshot_20230714_182506_Chrome.jpg](https://github.com/Expensify/App/assets/57330233/149d0624-ba1f-4136-bb02-823483fdcee1)

**Comment by NicMendonca** [comment] 2023-07-14 17:14
@Natnael-Guchima SORRY! Refresh, please. Just made it public

**Comment by Natnael-Guchima** [comment] 2023-07-14 18:42
No problem. Applied to the job @NicMendonca . Thanks.

**Comment by NicMendonca** [comment] 2023-07-18 13:33
paid! 🎉

**Closed by NicMendonca** 2023-07-18 13:33 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
