### ISSUE TITLE
[$500] Running "enableMemoryOnlyKeys()" and "disableMemoryOnlyKeys()" gives "undefined"

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34321] opened 2024-01-11 07:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #32164
**Version Number:** 1.4.24-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with an expensifail account
2. Run "enableMemoryOnlyKeys()" and "disableMemoryOnlyKeys()" code in the browser console

## Expected Result:
The log should give "[MemoryOnlyKeys] enabled" and "[MemoryOnlyKeys] disabled".

## Actual Result:
Running "enableMemoryOnlyKeys()" and "disableMemoryOnlyKeys()" gives "undefined" as a console response.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6338579_1704958035816!capture](https://github.com/Expensify/App/assets/43996225/4a663492-73e5-4d72-b9d8-4eb3bbfe8bb0)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01115f10f0e89dfa60</li>
        <li>Upwork Job ID: 1745354784959995904</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2024-01-11 08:09
I don't think this is a bug, since when we run a function in console it prints whatever the executed function is returning. Since this function is not returning anything it consoles undefined only. It's not an issue Or bug.

**Comment by getusha** [comment] 2024-01-11 16:45
@kavimuru not able to repro on staging.

<img width="991" alt="Screenshot 2024-01-11 at 7 44 15 PM" src="https://github.com/Expensify/App/assets/75031127/a443f9ef-d75d-4e1a-89dd-652a9496a937">

**Comment by yunongj** [comment] 2024-01-12 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We are expecting running "enableMemoryOnlyKeys()" and "disableMemoryOnlyKeys()" in browser's console would show logs saying "[MemoryOnlyKeys] enabled" and "[MemoryOnlyKeys] disabled" respectively. Instead, nothing was shown.

### What is the root cause of that problem?
The log level of the `clientLoggingCallback` function passed in is `debug`: https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/libs/Log.ts#L50-L56

`debug` messages will not show up in console at default log level. In order for debug messages to be shown in the console, we need to tick the "Verbose" option in Chrome's console. Safari does not have such issue as Safari shows all log messages by default.

### What changes do you think we should make in order to solve the problem?
We don't make any changes in code, but instead remember to tick the "Verbose" option in Chrome if we need to see the log.

### What alternative solutions did you explore? (Optional)
We could change the log level to "info" in code so that it will be logged at default level in Chrome , like below:
```
const Log = new Logger({
    serverLoggingCallback,
    clientLoggingCallback: (message) => {
        console.info(message);
    },
    isDebug: true,
});
```

However, since this function is being used by a lot of other places, it will affect the behavior of other callers. So I don't think this is a recommended approach.

**Comment by yunongj** [comment] 2024-01-12 07:08
Contributor details
Your Expensify account email: jiangyntz@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cbf89dbb686496f8

**Comment by puneetlath** [comment] 2024-01-12 20:17
@VickyStash can you weigh in here? Is it an expectation that you should be able to use these functions for some purpose and have them return something in the console?

**Comment by VickyStash** [comment] 2024-01-12 21:38
@puneetlath I was just working on the TS migration of the `MemoryOnlyKeys` functionality. The original functionality was implemented in [this PR](https://github.com/Expensify/App/pull/23831).
Overall, it looks like it works as expected, to see expected logs you just need to turn on `Verbose` logs in the console.
See the screenshot
![image](https://github.com/Expensify/App/assets/23176449/a2c05d08-ce68-4c51-8724-77e444839042)

**Comment by puneetlath** [comment] 2024-01-12 21:42
Ok cool, thanks for confirming! I'm going to go ahead and close this then. Feel free to comment/reopen if anyone disagrees or I've misunderstood.

**Closed by puneetlath** 2024-01-12 21:42 UTC
Labels: External, Daily, Help Wanted, Bug
