### ISSUE TITLE
[HOLD for payment 2024-01-17] [HOLD for payment 2024-01-18] Chat - The app crashes if I open an image attachment in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34047] opened 2024-01-05 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a conversation
2. Send an image attachment
3. Go offline
4. Tap on the attachment

## Expected Result:
The app shouldn't crash

## Actual Result:
The app crashes if I open an image attachment in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/eeee83d3-04dc-4675-9a4b-ab8c3def04cb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-01-05 21:05
@0xmiroslav Made a request to the tester

**Comment by lanitochka17** [comment] 2024-01-05 22:24
@0xmiroslav 
[log.txt](https://github.com/Expensify/App/files/13847191/log.txt)

**Comment by NikkiWines** [comment] 2024-01-05 23:21
I can't reproduce this on staging (iOS  1.4.22.0 and  1.4.22.1) or on dev 🤔 

https://github.com/Expensify/App/assets/16747822/72ba44ba-0ec1-4c49-bdfc-8be5f7b32737

**Comment by situchan** [comment] 2024-01-05 23:42
Checking crash log, this happens on pdf attachment and dupe of #34017

<img width="780" alt="crash" src="https://github.com/Expensify/App/assets/108292595/1dc3992d-6f0b-4c12-9a02-995f9bf7e68f">

Here's context: https://github.com/Expensify/App/issues/34017#issuecomment-1878780001

@NikkiWines I am available now to raise PR

**Comment by NikkiWines** [comment] 2024-01-05 23:56
oh nice, good catch on the dupe @situchan. It looks like we updated to 6.7.4 because of another issue related to the app crashing with PDFs (https://github.com/Expensify/App/pull/33561/) so I'm not sure downgrading is in our best interest 🤔 

I guess it depends on which scenario we think would be more common: 
a. User viewing a PDF file in offline mode
b. User uploading a PDfs with formulas/maths symbols

**Comment by situchan** [comment] 2024-01-05 23:59
https://github.com/Expensify/App/issues/29743 is android only issue and happened on specific pdfs.
https://github.com/Expensify/App/issues/34047 is native (android/iOS) issue and happens on all pdfs.
So I believe https://github.com/Expensify/App/issues/34047 is more common scenario

**Comment by marcaaron** [comment] 2024-01-05 23:59
hmm I am kind of confused actually and questioning the relatedness now. Tester is not using PDFs are they?

**Comment by situchan** [comment] 2024-01-05 23:59
The clear repro step is https://github.com/Expensify/App/issues/34017

**Comment by marcaaron** [comment] 2024-01-06 00:01
This issue does not reference anything about a PDF.

**Comment by situchan** [comment] 2024-01-06 00:02
1. `Go to the chat where you have sent the PDF file`
2. Send any image
3. Tap on the image preview
4. Tap on the back button

I believe @lanitochka17 missed Step 1 in repro step.
I checked crash log in https://github.com/Expensify/App/issues/34047#issuecomment-1879326954 and crash happened on pdf.

**Comment by marcaaron** [comment] 2024-01-06 00:03
Not seeing it. How did you determine that?

**Comment by situchan** [comment] 2024-01-06 00:03
> Not seeing it. How did you determine that?

<img width="780" alt="crash" src="https://github.com/Expensify/App/assets/108292595/1dc3992d-6f0b-4c12-9a02-995f9bf7e68f">

**Comment by situchan** [comment] 2024-01-06 00:05
As no one is able to reproduce, I think we can ask QA team test staging build again after fixing pdf crash.

**Comment by marcaaron** [comment] 2024-01-06 00:06
Nah, I just reproduced on Android with a PDF. They are the same 👍👍

**Comment by marcaaron** [comment] 2024-01-06 00:11
>I guess it depends on which scenario we think would be more common:
a. User viewing a PDF file in offline mode
b. User uploading a PDfs with formulas/maths symbols

Maybe one of these: 

1. Remove the blocker and wait for the upstream fix. 
2. Don't try to load any PDFs if we are offline. Better than a crash.

**Comment by situchan** [comment] 2024-01-06 00:13
> Don't try to load any PDFs if we are offline. Better than a crash.

This happens even when online.
https://github.com/Expensify/App/issues/34017 which was closed as dupe has repro step in online mode

**Comment by situchan** [comment] 2024-01-06 00:14
https://github.com/Expensify/App/assets/108292595/2a2764fd-29a1-4c2b-86f5-dfae43773e1c

**Comment by marcaaron** [comment] 2024-01-06 00:29
It works fine for me while online 🤷, but agree with the above.

**Comment by NikkiWines** [comment] 2024-01-06 03:42
Hmm, yeah I can reproduce this offline but not while online regardless of file type. 

I can also reproduce https://github.com/Expensify/App/issues/34017 while online, but only with a non-PDF 😅 

Sounds like either way, upgrading to 6.7.4 has introduced some weirdness so it's probably safer to downgrade. @situchan if you're still available, feel free to make a PR. Otherwise, I can push up the changes and we can compensate you for finding the root cause.

**Comment by shubham1206agra** [comment] 2024-01-06 05:20
@NikkiWines Give me some time. I may have found the problem.

**Comment by mvtglobally** [comment] 2024-01-07 04:52
Still repro on build 1.4.22-2 


https://github.com/Expensify/App/assets/43995119/8b6d95ce-21e3-4929-9d44-5f34611f4a6b


https://github.com/Expensify/App/assets/43995119/fd13f5ba-a069-42e2-abcc-fb3135b7f687

**Comment by NikkiWines** [comment] 2024-01-08 21:10
PR is in review

**Comment by roryabraham** [comment] 2024-01-09 04:23
> PR is in review

@NikkiWines just to be clear, are you referring to [the RN 0.73 upgrade](https://github.com/Expensify/App/pull/31558) ?

**Comment by mountiny** [comment] 2024-01-09 13:45
Should this still have the DB label? @NikkiWines I believe we just had a deploy

**Comment by situchan** [comment] 2024-01-09 13:59
This is now fixed. Seems like automation failed

**Comment by NikkiWines** [comment] 2024-01-09 17:09
> @NikkiWines just to be clear, are you referring to https://github.com/Expensify/App/pull/31558 ?

Sorry, I was referring to https://github.com/Expensify/App/pull/34078 which was CP'd [here](https://expensify.slack.com/archives/C07J32337/p1704770848289109). 

> Should this still have the DB label? @NikkiWines I believe we just had a deploy

Nope, this should be resolved.

**Comment by NikkiWines** [comment] 2024-01-10 00:02
Updating the labels for this one so we don't forget to issue payment

**Comment by puneetlath** [comment] 2024-01-17 17:08
Hm, what's due here? Is this the PR that @situchan should be paid for? https://github.com/Expensify/App/pull/34078

**Comment by situchan** [comment] 2024-01-17 17:34
yes

**Comment by puneetlath** [comment] 2024-01-17 17:35
And how much is due? $250 since this was a straight revert? Or something else?

**Comment by situchan** [comment] 2024-01-17 17:50
I am not sure if [this case](https://github.com/Expensify/App/issues/31217#issuecomment-1808963967) applies here.

Though solution was straight revert, there was an effort to reproduce and find the root cause.

**Comment by puneetlath** [comment] 2024-01-23 16:22
Ok sounds good, thanks for the link. 

Payment summary: 
- $500 @situchan for finding root cause and fixing issue. Offer here: https://www.upwork.com/nx/wm/offer/100583192

Please ping me on the issue when you've accepted.

**Comment by situchan** [comment] 2024-01-23 16:24
Accepted thanks

**Comment by puneetlath** [comment] 2024-01-23 16:27
Paid. Thanks everyone!

**Closed by puneetlath** 2024-01-23 16:27 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
