### ISSUE TITLE
[$250]  iOS - Onboarding task deeplinks used within the app redirect users to the web

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46495] opened 2024-07-30 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/46082
## Action Performed:
1. Open the iOS app
2. Create a new account (please use a public domain)
3. In the onboarding modal, select "manage my team's expenses"
4. Go to Expensify chat to view the task checklist
5. Open a task that contains a deeplink (e.g., meet your setup specialist or set up categories)
6. Open the desired task and tap on the hyperlink present within the steps (e.g., #admins room if meeting your setup specialist, or Workspaces if setting up categories)

## Expected Result:
Onboarding task deeplinks used within the app should redirect users to the correct screen within the app

## Actual Result:
Onboarding task deeplinks used within the app redirect users to the web

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e2cda409-0859-40b5-b27e-4ebb715d2281

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe8e043da71e3915</li>
        <li>Upwork Job ID: 1818998994406051154</li>
        <li>Last Price Increase: 2024-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103652377</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by arosiclair** [comment] 2024-07-30 15:50
I reproduced on staging and not on production. It seems like there might be something wrong with our staging ENV for iOS since the link is generated and NewDot and it is using the prod URL. I'll try reproducing on Android to verify.

**Comment by arosiclair** [comment] 2024-07-30 17:45
Not reproducible on Android staging **v9.0.14.-3**. I'm almost certain there's something going on with our staging .env

**Comment by arosiclair** [comment] 2024-07-30 18:01
In [these logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228ab73a59ba078ca2-EWR%22)+AND+timestamp:[2024-07-30T16:56:53.464Z+TO+2024-07-30T18:56:53.464Z]&index=logs_expensify-029608) you can see we're sending `Meet your setup specialist...` text as a param with the prod link.

**Comment by arosiclair** [comment] 2024-07-31 14:50
Okay this .env issue also affects Android so I no longer think that's the root problem. 

From what I can see debugging on web, we render the link with the `AnchorRenderer` and we attempt to parse the link as an internal path [here](https://github.com/Expensify/App/blob/4ffbd422296227ae003bfe0b5e584188bae5d68d/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L30). The link should get parsed regardless of whether it's a prod/staging/dev link. However, [Link.getInternalNewExpensifyPath](https://github.com/Expensify/App/blob/5a2602c441170093e99850e2194808218b0aa838/src/libs/actions/Link.ts#L107-L113) is returning an empty string for the link `https://new.expensify.com/r/7732527507011683` which is incorrect.

Fixing `Link.getInternalNewExpensifyPath` should fix the issue. This code hasn't been modified in many months, so this seems like an old problem that we're only noticing now. I'd say we should fix this but not continue blocking the deploy on it.

**Comment by arosiclair** [comment] 2024-07-31 14:59
Easier repro steps:

1. Log into staging Android/iOS
2. Copy URL for any report
3. Paste the URL into the self DM (it should be a staging link)
4. Paste the URL again but remove `staging.`
5. Verify the staging link opens in-app
6. Verify the production link opens in-app
    - This works on Android but not on iOS. I'm guessing Android is just doing a better job redirecting the link at an OS level here

**Comment by nkdengineer** [comment] 2024-08-02 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding task deeplinks used within the app redirect users to the web

### What is the root cause of that problem?

The link to the admin room in the onboarding task is the production link. As expected in `openLink` function, we will open a new tab as an external link because `hasSameOrigin` is `false`. That is the reason the bug can only reproduce in staging and dev.

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/actions/Link.ts#L125

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/actions/Link.ts#L161

### What changes do you think we should make in order to solve the problem?
1. For the link that is rendered by `RenderHTML` component, we should navigate internally if it's possible. To do that we can add an extra param in `openLink` like `shouldNavigateIfPossible` with the default value is `false`. Then we will navigate internally if `internalNewExpensifyPath` exists and `shouldNavigateIfPossible` or `hasSameOrigin` is `true`

```
if (internalNewExpensifyPath && (hasSameOrigin ||  shouldNavigateIfPossible)) {
```

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/actions/Link.ts#L145

2. Pass `shouldNavigateIfPossible` as `true` here

```
onPress={() => Link.openLink(attrHref, environmentURL, isAttachment, true)} 
```
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L41

```
onPress={internalNewExpensifyPath || internalExpensifyPath ? () => Link.openLink(attrHref, environmentURL, isAttachment, true) : undefined} 
```
https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.tsx#L74
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-08-07 14:38
@abdulrahuman5196 mind reviewing the proposals?

**Comment by JmillsExpensify** [comment] 2024-08-07 14:43
Not super sure what's going on with the overdue label but whatever melvin.

**Comment by abdulrahuman5196** [comment] 2024-08-08 12:52
Checking now

**Comment by abdulrahuman5196** [comment] 2024-08-08 17:26
> Given this is in the onboarding flow and it takes them out of the app to web, I'm going to move this into Sept with some other polish items in core flows. 👍  

@trjExpensify I don't understand what this means, should we hold till sept?

**Comment by trjExpensify** [comment] 2024-08-08 18:41
No, I'm just moving it up in priority to be done for our September release. 👍

**Comment by abdulrahuman5196** [comment] 2024-08-11 20:26
On @nyomanjyotisa 's proposal here https://github.com/Expensify/App/issues/46495#issuecomment-2258406603 the RCA seems incorrect, even on registering via dev builds I am facing this issue.

**Comment by abdulrahuman5196** [comment] 2024-08-11 20:28
On @nkdengineer 's proposal here https://github.com/Expensify/App/issues/46495#issuecomment-2264918462 the RCA seems correct, but I am not aligned on the solution for Link or anchor components to pass a param, instead we should handle it in the openLink itself similar to how its handled for prod app

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/actions/Link.ts#L145

**Comment by trjExpensify** [comment] 2024-08-15 00:45
What do you think, @nkdengineer?

**Comment by nkdengineer** [comment] 2024-08-15 07:07
### Updated [proposal](https://github.com/Expensify/App/issues/46495#issuecomment-2264918462)

- Updated new solution

**Comment by nkdengineer** [comment] 2024-08-15 07:08
@abdulrahuman5196 I updated my proposal with a new idea. Please help to check again.

**Comment by arosiclair** [comment] 2024-08-19 13:43
@abdulrahuman5196 @nkdengineer I think [this](https://github.com/Expensify/App/issues/46495#issuecomment-2260706331) would be the right approach. Have you looked at it yet?

**Comment by nkdengineer** [comment] 2024-08-19 13:46
I will check this soon.

**Comment by nkdengineer** [comment] 2024-08-19 13:57
@arosiclair I checked and `getInternalNewExpensifyPath` returns the correct path. As I mentioned in my proposal, the problem here is `hasSameOrigin` is false if we're in staging or dev because the `href` is a production URL.

https://github.com/Expensify/App/blob/5a2602c441170093e99850e2194808218b0aa838/src/libs/actions/Link.ts#L145

then we don't navigate to this route here
https://github.com/Expensify/App/blob/5a2602c441170093e99850e2194808218b0aa838/src/libs/actions/Link.ts#L126

**Comment by abdulrahuman5196** [comment] 2024-08-19 18:44
Let me also check it.

**Comment by arosiclair** [comment] 2024-08-20 13:43
Ah okay I see `AnchorRenderer` is still calling `Link.openUrl` which does the `hasSameOrigin` check. In that case, I think the proper fix is to just generate the correct dev/staging/prod URL when we create the onboarding tasks [here](https://github.com/Expensify/App/blob/2c0ca23dad53b65bbed83556b16e5159f46387ab/src/libs/actions/Report.ts#L3367-L3368).

**Comment by nkdengineer** [comment] 2024-08-20 14:13
> In that case, I think the proper fix is to just generate the correct dev/staging/prod URL when we create the onboarding tasks [here](https://github.com/Expensify/App/blob/2c0ca23dad53b65bbed83556b16e5159f46387ab/src/libs/actions/Report.ts#L3330-L3331).

That is the idea from my proposal.

@abdulrahuman5196 Can you please review my In that case, I think the proper fix is to just generate the correct dev/staging/prod URL when we create the onboarding tasks [here](https://github.com/Expensify/App/blob/2c0ca23dad53b65bbed83556b16e5159f46387ab/src/libs/actions/Report.ts#L3330-L3331). again, thanks.

**Comment by abdulrahuman5196** [comment] 2024-08-21 17:02
> Ah okay I see `AnchorRenderer` is still calling `Link.openUrl` which does the `hasSameOrigin` check. In that case, I think the proper fix is to just generate the correct dev/staging/prod URL when we create the onboarding tasks [here](https://github.com/Expensify/App/blob/2c0ca23dad53b65bbed83556b16e5159f46387ab/src/libs/actions/Report.ts#L3330-L3331).

@arosiclair 
I am not sure if this is the right path. For example, the onboarding tasks creating will be shown in both dev and staging environment for the same account, so if the user created the task in dev and opened the same chat in staging app we would face the same issue again. 
IMO Instead we should redirect internally if the url belongs to any expensify url, similar to how we find if the url is internal expensify url using all 3 environments(dev, staging, prod)

https://github.com/Expensify/App/blob/4f16e2654ec1f1bd8db19fb52d4752e22e358c0d/src/libs/actions/Link.ts#L107-L113

**Comment by nkdengineer** [comment] 2024-08-21 17:43
@abdulrahuman5196 My proposal can work for all platforms.

**Comment by arosiclair** [comment] 2024-08-21 18:10
> IMO Instead we should redirect internally if the url belongs to any expensify url, similar to how we find if the url is internal expensify url using all 3 environments(dev, staging, prod)

I thought about that, but I'm not sure if that's always desired. For example if I send you a staging link, I usually want you to open it in staging. I'll raise the question internally to see which direction we should go.

**Comment by arosiclair** [comment] 2024-08-22 21:31
Alright the verdict is to continue opening new expensify links in their respective environment (eg: staging link should open in staging even if you're in prod).

> After creating an optimistic task report, we will update the task description by replacing the CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL with %baseURL/. We need to replace it after we create the optimistic task report because it's used to parse the markdown to link [here](https://github.com/Expensify/App/blob/68128f5a561e2910a31c11a97b514fec0471c701/src/libs/ReportUtils.ts#L5522)

This feels hacky. We shouldn't create the report with the wrong link and then fix it later. Can we just create the task with the correct dev/staging/prod link to begin with? It's fine if it doesn't work in a different environment.

**Comment by nkdengineer** [comment] 2024-08-23 04:20
> Can we just create the task with the correct dev/staging/prod link to begin with? It's fine if it doesn't work in a different environment.

@arosiclair  Yes, we can do this. Updated alternative [solution](https://github.com/Expensify/App/issues/46495#issuecomment-2264918462) with this expected

**Comment by arosiclair** [comment] 2024-08-23 14:24
Thank you let's go with your alternative solution.

**Comment by abdulrahuman5196** [comment] 2024-08-29 16:19
```
Expected Result:

Onboarding task deeplinks used within the app should redirect users to the correct screen within the app
Actual Result:

Onboarding task deeplinks used within the app redirect users to the web
```
@arosiclair 
Just to confirm on decision. The current issue OP is not correct. We don't consider current issue OP as issue but that is the expected behaviour.

So during task creation itself we will use current environment and generate the link. If that link is opened in a different environment mobile app/platform, it would be redirect to web(if particular environment app is not present).
So current expectation is to update the task creation link to have the current environment URL.

**Comment by arosiclair** [comment] 2024-08-29 17:03
> So current expectation is to update the task creation link to have the current environment URL.

That's correct. If we create an account on staging, the onboarding task should generate a link with a staging URL. On production, it should be a production URL.

**Comment by arosiclair** [comment] 2024-09-24 19:26
This hit prod [3 weeks ago](https://github.com/Expensify/App/pull/47983#issuecomment-2332465122) so we should be good for payment and closing.

**Comment by JmillsExpensify** [comment] 2024-09-26 18:54
Payment summary:

 - Contributor: @nkdengineer $250
 - Reviewer: @abdulrahuman5196 $250

**Comment by JmillsExpensify** [comment] 2024-09-26 18:55
@abdulrahuman5196 can you complete the BZ checklist please?

**Comment by abdulrahuman5196** [comment] 2024-09-27 14:30
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Doesn't seem to be a regression.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1) Create a new account (please use a public domain)
2) In the onboarding modal, select "manage my team's expenses"
3) Go to Expensify chat to view the task checklist
4) Open a task that contains a deeplink (e.g., meet your setup specialist or set up categories)
5) Open the desired task and tap on the hyperlink present within the steps (e.g., #admins room if meeting your setup specialist, or Workspaces if setting up categories)
6) Onboarding task deeplinks used within the app should redirect users to the correct screen within the app

@JmillsExpensify Added the BZ checklist. Sorry for missing it previously.

**Comment by trjExpensify** [comment] 2024-09-30 08:38
Confirming payment summary as follows:

- $250 to @abdulrahuman5196 for the C+ review 
- $250 to @nkdengineer for the fix

**Comment by JmillsExpensify** [comment] 2024-09-30 08:38
$250 approved for @abdulrahuman5196

**Comment by JmillsExpensify** [comment] 2024-09-30 16:43
All contributors paid and regression test created. Closing.

**Closed** 2024-09-30 16:44 UTC
Labels: External, Daily, Awaiting Payment, Bug
