### ISSUE TITLE
Android : Chat : Message sent as longer emails are not displayed properly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14108] opened 2023-01-07 03:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the android app
2. Open any report
3. Write sentence that takes up more than two lines in chat message.

## Expected Result:
Chat message should occupy full available horizontal space when displayed in messages (Like it does in mWeb chrome)

## Actual Result:
Chat message breaks into next line even though further horizontal space is available

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native

**Version Number:** 1.2.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/211128885-55f9552d-9643-4504-8f06-2901e3e374db.mp4

https://user-images.githubusercontent.com/43996225/211128908-831db437-aa95-45bf-a758-914467819df0.mp4

<img src="https://user-images.githubusercontent.com/43996225/211128893-5c9ddb9b-2c58-48df-ba4f-a379738488d6.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673023806589679

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-01-12 03:14
This is the same on iOS and I think a stylistic feature, not a bug. Closing!

**Closed by sophiepintoraetz** 2023-01-12 03:14 UTC
Labels: Daily, Overdue, Bug
