### ISSUE TITLE
[$500] Log in -  Shift Enter triggers error on login page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28414] opened 2023-09-28 19:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If logged in then logout
3. In email/phone number field, try shift+enter and observe that it triggers error
4. For similar field in app, try new contact method in settings->profile->contact method->New contact method and observe that it does not trigger error on shift+enter

## Expected Result:
 App shouldn't trigger error on login page on Shift+Enter similar to other fields throughout the app

## Actual Result:
App triggers error on login page on shift+enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x]  Windows/ Chrome
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c05ddffb-9a75-4d8e-bad5-193302200abd

https://github.com/Expensify/App/assets/78819774/48150919-8ba8-42db-9bc1-60b3bfeed0d1

https://github.com/Expensify/App/assets/78819774/46914593-9aee-4620-babf-a1f209365d88

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695837000312909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117914aba40dea29d</li>
        <li>Upwork Job ID: 1707478319902584832</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by cg813** [comment] 2023-09-28 21:37
### Proposal
**Please re-state the problem that we are trying to solve in this issue.**
Shift Enter triggers error on login page

**What is the root cause of that problem?**
`Button` component is triggering the keyboard events with modifier keys.

**What changes do you think we should make in order to solve the problem?**
We can add modifier keys for Enter key. here:
In this case: ['shift']
<img width="652" alt="image" src="https://github.com/Expensify/App/assets/57125237/16b6e92e-8696-4665-aad6-3321b26691a2">

**Comment by cg813** [comment] 2023-09-28 21:54
## Proposal
[Updated](https://github.com/Expensify/App/issues/28414#issuecomment-1740038064)

We can add another one for shift+enter event.
```
SHIFT_ENTER: {
            descriptionKey: null,
            shortcutKey: 'Enter',
            modifiers: ['shift'],
            trigger: {
                DEFAULT: {input: keyInputEnter},
                [PLATFORM_OS_MACOS]: {input: keyInputEnter},
                [PLATFORM_IOS]: {input: keyInputEnter},
            },
        },
```

**Comment by cg813** [comment] 2023-09-29 06:31
Contributor details
Your Expensify account email: dev.s.ly813@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0135b98b5120b39aab

**Comment by mzeeshanid** [comment] 2023-09-29 10:52
Contributor details
Your Expensify account email: mzeeshanid@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016fe2b0c9f5009b00

**Comment by eikcalb** [comment] 2023-09-29 12:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log in - Shift Enter triggers error on login page

### What is the root cause of that problem?
The button used in the login page, `FormAlertWithSubmitButton`, creates an event listener that listens for the `Enter` key.
The handler defined in this button then calls the `validateAndSubmitForm` function, which triggers the error.

### What changes do you think we should make in order to solve the problem?
Modifying https://github.com/Expensify/App/blob/dfb3f9b0b536d9640f81a85d59e095581dc06dba/src/components/Button/index.js#L178 to filter modifiers just like is done here: https://github.com/Expensify/App/blob/dd7820ddc4368a4d700f72b884ab3290fb7ba2bd/src/components/FormSubmit/index.js#L16, should prevent this issue.

**Comment by eikcalb** [comment] 2023-09-29 12:02
Contributor details
Your Expensify account email: agwaisraelonome@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ac41c8e74c9da237

**Comment by eikcalb** [comment] 2023-10-02 16:18
> @anmurali I am not sure if this is a valid bug? If it's a Shift+Enter and if haven't subscribed, I think it would be okay to call method binded to Enter.
> 
> 
> 
> 

I'd like to point out that in the other fields in the app do not behave this way because the input is wrapped in a "Form" and this form checks for key modifiers. In this case the submit button is setting up a listener

**Comment by anmurali** [comment] 2023-10-11 02:41
@mananjadhav I am closing this. Please DM me if I misunderstood your comment https://github.com/Expensify/App/issues/28414#issuecomment-1743314098

**Closed by anmurali** 2023-10-11 02:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by mananjadhav** [comment] 2023-10-30 11:32
@dukenv0307 I still feel this isn't a big priority but let me tag @Expensify/design @shawnborton too, to get their feedback.

**Comment by dubielzyk-expensify** [comment] 2023-11-01 02:39
From a UX perspective, this isn't a bug. You've entered nothing in the login field and it throws an error when user is trying to press Enter. I'm okay with this issue being closed 👍

**Comment by dubielzyk-expensify** [comment] 2023-11-15 12:27
In my view consistency should be broken if it's confusing. I'd prefer predictive and intuitiveness over consistency in most cases, but I appreciate the callout and it's a fair point. 

Would be curious to hear if @Expensify/design has any other thoughts. Otherwise I think we can leave this remained as closed.

**Comment by shawnborton** [comment] 2023-11-15 13:33
I agree with Jon here, this one can remain closed and I think it's working as the user would expect.
