### ISSUE TITLE
[$500] hmm it's not there page displayed for offline distance expense when going back online

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30319] opened 2023-10-25 00:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.90-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Create a distance expense in offline
2. Go online and open distance expense details

## Expected Result:
The distance expense is not greyed out, the map loads and displays the trip road
and the details of the miles and amount are displayed

## Actual Result:
Map doesn't load and amount not updated. hmm it's not there page displayed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari (Video added)
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/43996225/f769d82f-40db-40be-862e-e04950563add

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b86585a91287a44</li>
        <li>Upwork Job ID: 1716971073774956544</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by hayata-suenaga** [comment] 2023-10-25 01:23
@parasharrajat do you have any idea why this is happening? anyway, I don't think this doesn't have to be a deploy blocker. Removing the label.

**Comment by arosiclair** [comment] 2023-10-25 14:07
> I don't think this doesn't have to be a deploy blocker.

Why not? Is this not a regression?

**Comment by hayata-suenaga** [comment] 2023-10-27 15:59
ah I should have treated this as a regression in the hindsight. We can get contributors working on this as soon as possible

**Comment by situchan** [comment] 2023-10-27 17:45
@suneox I think you submitted proposal on wrong issue. This is not about attachment carousel.

**Comment by situchan** [comment] 2023-10-27 18:09
> @situchan The action performed is short so I missed steps reproduce let me check again. Additional info, currently on the latest main branch when visiting an attachment carousel from a distance request also crashed

It's another deploy blocker which fix was already deployed to staging. Please work on latest main always

**Comment by AmjedNazzal** [comment] 2023-10-28 08:12
What am I doing wrong here? I can't reproduce this! 

https://github.com/Expensify/App/assets/74202751/8f5daa99-64b7-4f87-8b77-96f2b060aa8e

**Comment by hayata-suenaga** [comment] 2023-10-30 16:24
still accepting and reviewing proposals

**Comment by hayata-suenaga** [comment] 2023-11-01 16:32
melvin, I posted a message about this issue in the open source channel

**Comment by CortneyOfstad** [comment] 2023-11-06 16:46
@hayata-suenaga any updates? Thanks!

**Comment by Tony-MK** [comment] 2023-11-07 02:06
@hayata-suenaga @parasharrajat, and @kavimuru This looks like an interesting issue to solve.
However, I have repeatedly failed to reproduce this bug.
Can one of you kindly help me elaborate on the steps to reproduce?
Is it only reproducible with `expensyfail.com` accounts?
Thank you 😄

**Comment by hayata-suenaga** [comment] 2023-11-07 17:57
Another contributor also cannot reproduce the issue. We can close this for now.

**Comment by lanitochka17** [comment] 2023-12-05 14:31
Issue reproducible in  the  latest build 1.4.8-0


https://github.com/Expensify/App/assets/78819774/6143c038-92bd-44c5-ac39-c8d8ba9c6bef

**Comment by CortneyOfstad** [comment] 2023-12-08 14:52
Not overdue

**Comment by hayata-suenaga** [comment] 2023-12-08 19:24
@parasharrajat are we still accepting proposals?

**Comment by CortneyOfstad** [comment] 2023-12-11 14:34
@parasharrajat bump ^^^ thanks!

**Comment by CortneyOfstad** [comment] 2023-12-12 13:42
Hey! Sorry for the confusion here, but we just got an internal update. Per [this post](https://expensify.enterprise.slack.com/archives/C01SKUP7QR0/p1702341886807759), we can close any bugs that are not related to Waves, so closing this out 👍 We will re-address once the waves are completed.

**Closed by CortneyOfstad** 2023-12-12 13:42 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
