### ISSUE TITLE
[Awaiting Checklist Completion] [$500] IOU-Unable to create distance request after deleting finish waypoint, error displayed

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32908] opened 2023-12-12 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11
**Reproducible in staging?:**Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a Workspace chat
3. Tap plus icon --- Request money --- Distance
4. Enter start and finish waypoints
5. Tap next
6. Tap request
7. Tap distance
8. Tap add stop and select a location
9. Tap save
10. Tap map and confirm 3 waypoints displayed
11. Tap distance
12. Tap finish and delete that waypoint and save

## Expected Result:
In distance request, after deleting finish point and when user taps save, the two waypoints must be saved & error "Please enter atleast two different addresses" must not be displayed.

## Actual Result:
In distance request, after deleting finish point and when user taps save, error "Please enter atleast two different addresses" is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/72d20aab-253d-4527-8f1d-d350b19d254e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01977bdc1084795472</li>
        <li>Upwork Job ID: 1734520501399977984</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 28044312</li>
<li>Pujan92 | Contributor | 28044314</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-12-12 10:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In distance request, after deleting finish point and when user taps save, error "Please enter atleast two different addresses" is displayed.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/83bd22f5f7380daf5137a2de6b864f94898f68b4/src/libs/actions/Transaction.ts#L61

It seems we have a mistake here. If isDraft === true we should merge `ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transactionID}`

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/83bd22f5f7380daf5137a2de6b864f94898f68b4/src/libs/actions/Transaction.ts#L61

update like this
```
    Onyx.merge(`${isDraft ?  ONYXKEYS.COLLECTION.TRANSACTION_DRAFT}${transactionID} : ONYXKEYS.COLLECTION.TRANSACTION `


```
### What alternative solutions did you explore? (Optional)
NA

**Comment by Pujan92** [comment] 2023-12-12 10:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete waypoint and then save transaction is not working

### What is the root cause of that problem?
Seems partial transaction has been passed to the `removeWaypoint` from `WaypointEditor`.  commit https://github.com/Expensify/App/commit/d1ec9ee39ec68a361c112dacd2a545607782b76e
https://github.com/Expensify/App/pull/28618 

### What changes do you think we should make in order to solve the problem?
As we have updated the param from transactionID to transaction we should pass the full transaction.
We can remove this selector from here and pass full transaction object which eventually used to create new transaction.

https://github.com/Expensify/App/blob/2d8523ae3fd8a5b692700a91efb90adac7f1175f/src/pages/iou/WaypointEditor.js#L257-L259

**Comment by twisterdotcom** [comment] 2023-12-12 11:50
@Gonals, @neil-marcellini does this need to be hourly?

**Comment by Gonals** [comment] 2023-12-12 12:25
No. I have no idea why the bot decided to hourly it 😕

**Comment by shubham1206agra** [comment] 2023-12-12 12:49
@twisterdotcom This is a deploy blocker. Maybe that's why this was hourly

**Comment by Gonals** [comment] 2023-12-12 12:53
True. I'm marking it as internal too, for now, and investigating the origin

**Comment by shubham1206agra** [comment] 2023-12-12 12:56
@Gonals It was decided the origin will not be reverted as this was a big PR.

**Comment by DylanDylann** [comment] 2023-12-12 12:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In distance request, after deleting finish point and when user taps save, error "Please enter atleast two different addresses" is displayed.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/bd3383d24e51026537eba54ee80d53dcdd26cb98/src/libs/actions/Transaction.ts#L162

When removing the waypoint, we update new transaction with a lack of some fields

Let's see this logic
https://github.com/Expensify/App/blob/bd3383d24e51026537eba54ee80d53dcdd26cb98/src/libs/actions/Transaction.ts#L132-L136

The transaction from params is lack of some fields becasue this selector

https://github.com/Expensify/App/blob/bd3383d24e51026537eba54ee80d53dcdd26cb98/src/pages/iou/WaypointEditor.js#L259


### What changes do you think we should make in order to solve the problem?


### What alternative solutions did you explore? (Optional)
https://github.com/Expensify/App/blob/bd3383d24e51026537eba54ee80d53dcdd26cb98/src/pages/iou/WaypointEditor.js#L259
I think that the selector here help us to improve performance.
So I suggest we only pass transactionID to `removeWaypoint` function and using TransactionUtils.getTransaction to get transaction

**Comment by Gonals** [comment] 2023-12-12 12:58
> We can remove this selector from here and pass full transaction object which eventually used to create new transaction.

Do we have an ongoing conversation for this?

**Comment by shubham1206agra** [comment] 2023-12-12 12:59
See https://expensify.slack.com/archives/C01GTK53T8Q/p1702303752079129

**Comment by Pujan92** [comment] 2023-12-12 13:01
> > We can remove this selector from here and pass full transaction object which eventually used to create new transaction.
> 
> Do we have an ongoing conversation for this?

I don't think so as I haven't started any but with that PR we are expecting the transaction data so I suggested that.

**Comment by Gonals** [comment] 2023-12-12 13:03
> See https://expensify.slack.com/archives/C01GTK53T8Q/p1702303752079129

Thanks! Moving it back to external, for now. @fedirjh, we can start proposal reviews. I'll be back in a bit to take another look

**Comment by Julesssss** [comment] 2023-12-12 15:13
> @Gonals, @neil-marcellini does this need to be hourly?

Yes, it is a deploy blocker

**Comment by Pujan92** [comment] 2023-12-12 15:48
Earlier we were passing only `transactionID` and fetching the transaction in the `removeWaypoint` method. So selector used to fetch only the required fields.
https://github.com/Expensify/App/pull/28618/files#diff-b547a9efd51e73e311c9594c13035dfb3f1d523cbd5f4cad58b3b774af8561dcL157

But now the implementation changed and now the caller of `removeWaypoint` needs to pass the transaction.

**Comment by Julesssss** [comment] 2023-12-12 15:59
Excellent. This is pretty urgent, so I'm going to go ahead and assign @Pujan92

**Comment by Pujan92** [comment] 2023-12-12 16:00
> I see and what is the specific missing data ?

Mostly all fields except comment and transactionID.

**Comment by yh-0218** [comment] 2023-12-12 16:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In distance request, after deleting finish point and when user taps save, error "Please enter atleast two different addresses" is displayed.
### What is the root cause of that problem?
1. When remove we are missing some value because of selector.
2. we didn't consider `isDraft` when call `removeWaypoint`
3. we have issue on `removeWaypoint` function
### What changes do you think we should make in order to solve the problem?
1. need to remove selector or need to select more values
https://github.com/Expensify/App/blob/75041d0075f69dcbffa188fc6536ba855f311b66/src/pages/iou/WaypointEditor.js#L259
2. `isDraft` when call `removeWaypoint`
```
 Transaction.removeWaypoint(transaction, waypointIndex, isEditingWaypoint);
```
3. update condition on `removeWaypoint` function
```
if (!isDraft) {
```
### What alternative solutions did you explore? (Optional)

https://github.com/Expensify/App/assets/65789015/6523ff9a-d184-4f43-a93b-ffbff1825ac4

**Comment by Gonals** [comment] 2023-12-12 16:37
> Excellent. This is pretty urgent, so I'm going to go ahead and assign @Pujan92

Coolio 👍

**Comment by luacmartins** [comment] 2023-12-12 19:08
Tested in staging. This is a pass.

**Comment by twisterdotcom** [comment] 2023-12-20 14:16
Payment Summary:

@Pujan92 paid $500 [here](https://www.upwork.com/nx/wm/offer/28044314) (Contributor)
@fedirjh paid $500 [here](https://www.upwork.com/nx/wm/offer/28044312) (Reviewer)

**Comment by Gonals** [comment] 2023-12-27 11:14
@fedirjh, can you complete the checklist?

**Comment by Gonals** [comment] 2023-12-28 18:47
Thanks!

**Closed** 2024-01-02 13:54 UTC
Labels: External, Engineering, Daily, Overdue, Bug
