### ISSUE TITLE
[$250] Pay someone - Unapprove option is available for "Pay someone" expense, which gives error

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44966] opened 2024-07-08 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any DM.
3. Go to + > Pay someone.
4. Enter amount and pay them.
5. Click on the expense preview.
6. Click on the report header..
7. Click Unapprove.

## Expected Result:
Unapprove option should not be available for "Pay someone" expense.

## Actual Result:
Unapprove option is available for "Pay someone" expense, which results in error.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/eea20d0a-ed5e-4f37-8ed3-fac430aecbe7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010702f689c6b7150e</li>
        <li>Upwork Job ID: 1826736492231832841</li>
        <li>Last Price Increase: 2024-08-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Pujan92</details>

**Comment by m-natarajan** [comment] 2024-07-08 13:54
@johnmlee101 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-08 13:54
We think that this bug might be related to  #vip-vsb

**Comment by Beamanator** [comment] 2024-07-09 09:23
@rushatgabhane looks like we gotta fix this!

**Comment by Beamanator** [comment] 2024-07-09 09:46
PR up soon

**Comment by Beamanator** [comment] 2024-07-09 10:55
Fix merged & CPing

**Comment by Beamanator** [comment] 2024-07-16 10:46
There's 3 app PRs listed in that PR, we only need to handle payment in 1 of those - so I was thinking we'll do that in a different one, not this one

**Comment by Beamanator** [comment] 2024-08-13 03:01
Aah yep looks like @ishpaul777 hasn't been paid for reviewing https://github.com/Expensify/App/pull/45049 🙏  @MitchExpensify can you please help with that? 🙏

**Comment by Beamanator** [comment] 2024-08-22 20:50
asked for payment help internally

**Comment by mallenexpensify** [comment] 2024-08-22 21:47
ah.. shit, sorry @Pujan92 , forgot to assign @ishpaul777 BEFORE adding `External`.   

@ishpaul777 can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~010702f689c6b7150e

**Comment by mallenexpensify** [comment] 2024-08-26 15:01
Contributor+: @ishpaul777 paid $250 via Upwork.  

@ishpaul777 we want a regression test for this, right? Assuming so, can you fill out the checklist? Thx

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment] 2024-08-26 15:28
Thanks @ishpaul777 test case GH created
- https://github.com/Expensify/Expensify/issues/423317

**Closed by mallenexpensify** 2024-08-26 15:28 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
