### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Distance - Transaction thread opens after saving distance edit when there is only one request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39457] opened 2024-04-02 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled request.
3. Create a distance request.
4. Click on the request preview to go to one transaction report view.
5. Click Distance.
6. Edit the distance and save it.

## Expected Result:
App will stay in one transaction report view after saving the distance edit because there is only one request.

## Actual Result:
Transaction thread opens after saving distance edit when there is only one request.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b4b0edde-ed20-410e-9929-014070291f1c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01034c7477c396612a</li>
        <li>Upwork Job ID: 1776364222315294720</li>
        <li>Last Price Increase: 2024-04-05</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-02 22:40
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment] 2024-04-03 00:18
I was not able to reproduce this, but ran into another bug:

![2024-04-02_14-16-46](https://github.com/Expensify/App/assets/32969087/d03cedb3-6fb3-4a39-a975-46c728599758)

A call to `GetNewerActions` hit a server error. Unsure if related. Checking logs...

```
{
  "code": 666,
  "jsonCode": 666,
  "type": "Expensify\\Libs\\Error\\ExpError",
  "UUID": "5757c554-3198-11ee-be56-0242ac120002",
  "message": "Missing reportActionID or reportID",
  "title": "",
  "data": [],
  "htmlMessage": "",
  "onyxData": [],
  "requestID": "86e4de6e880ebc79-HNL"
}
```

**Comment by marcaaron** [comment] 2024-04-03 00:25
Ok, tried a second time and could not reproduce that error (worked OK).

Also can't reproduce the issue.

>Expected: App will stay in one transaction report view after saving the distance edit because there is only one request.
>Actual: Transaction thread opens after saving distance edit when there is only one request.

I'm not really sure what this is trying to communicate. What is a "transaction report" vs. a "transaction thread"?

I'm gonna remove the blocker and have this triaged as a normal bug.

**Comment by bernhardoj** [comment] 2024-04-03 07:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Saving the distance waypoints brings the user to the transaction thread.

### What is the root cause of that problem?
This happens after the one transaction report page. In the expense report page, we show the money request view and pass `transactionThreadReport` as the `report` prop.
https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/home/report/ReportActionItem.tsx#L756-L773

`transactionThreadReport` is the transaction thread report object. When we open the distance edit page, it will use the passed report `reportID` and use it as the param.
https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/components/ReportActionItem/MoneyRequestView.tsx#L354-L356

In distance page, if we were editing, pressing save will call `Navigation.dismissModal(reportID)`
https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/iou/request/step/IOURequestStepDistance.js#L194-L205

and because the `reportID` is the ID of the transaction thread report, we are navigated to the transaction thread report page.

### What changes do you think we should make in order to solve the problem?

This doesn't happen with other fields (amount, description, etc.) because when we save them, we just call `Navigation.dismissModal` without a reportID, so I suggest to do the same for distance page.
https://github.com/Expensify/App/blob/879378ff68dc026c1b4ba6af30b70051b99c6d35/src/pages/iou/request/step/IOURequestStepAmount.js#L157-L170

### What alternative solutions did you explore? (Optional)
We can add a new param to the route to tell which report we want to go after dismissing the modal.

**Comment by greg-schroeder** [comment] 2024-04-05 21:39
Awaiting proposal review

**Comment by marcochavezf** [comment] 2024-04-08 00:12
Sounds good, thanks @paultsimura, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment] 2024-04-08 05:00
PR is ready

cc: @paultsimura

**Comment by greg-schroeder** [comment] 2024-04-15 02:59
Merged and deployed to staging. Awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2024-04-26 07:30
Processing payments

**Comment by greg-schroeder** [comment] 2024-04-26 07:32
Please complete the checklist @paultsimura and we can close this out!

**Comment by greg-schroeder** [comment] 2024-04-26 19:27
Thanks! Filing

**Closed by greg-schroeder** 2024-04-26 19:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
