### ISSUE TITLE
[HOLD for Regression Test] Composer highlighted even though the global create a menu is opened

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13561] opened 2022-12-13 18:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. create a new user
2. check the composer when global create a menu is opened first time automatic

## Expected result: 
composer should not be highlighted

## Actual result: 
composer highlighted

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.38-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/207419550-dff2be52-02b5-4c27-9de6-800dc42644b0.mp4

![Screenshot 2022-12-13 at 3 17 50 PM](https://user-images.githubusercontent.com/43996225/207419566-92d5b0b4-7812-4c82-897d-0fb337140e00.png)

https://user-images.githubusercontent.com/43996225/207419570-e9959728-119c-4542-ba7d-323d8b1af608.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670942696047359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alex-mechler** [comment] 2022-12-14 20:55
Looks like a bug we should fix. Assigning myself to fix this internally

**Comment by alex-mechler** [comment] 2022-12-16 19:39
Hmmm, @kavimuru I'm not seeing this on staging. This is what I get following your steps. Is this still reproducible? 
![image](https://user-images.githubusercontent.com/22447860/208175910-6a3b5937-2aec-44c5-911f-cb1fe14b5f47.png)

**Comment by alex-mechler** [comment] 2022-12-16 19:41
Ah, I am still getting this on production, so something that went out to staging must have fixed this.

**Comment by kavimuru** [comment] 2022-12-17 03:50
@alex-mechler Still it is repro in staging

https://user-images.githubusercontent.com/43996225/208222382-c8a11d9c-f1fc-4540-9c30-812382c2cac3.mp4

**Comment by alex-mechler** [comment] 2022-12-19 19:07
Hmm, on staging im still not seeing it 
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/22447860/208500823-24740d1f-0f55-42e4-a18d-fdc87afb4f24.png">

In your video, it doesnt look liek the focused color 
<img width="1772" alt="image" src="https://user-images.githubusercontent.com/22447860/208500979-d6ed5bfb-20dd-4704-a260-9f4010852610.png">

**Comment by alex-mechler** [comment] 2022-12-19 19:19
Oh interesting, I can reproduce this in incognito. I must have an extension doing something here that causes me to not be able to reproduce normally

**Comment by alex-mechler** [comment] 2022-12-19 22:23
@eVoloshchak added you here to track for payment purposes

**Comment by alex-mechler** [comment] 2023-01-09 16:06
@eVoloshchak I've gone ahead an unlocked this, forgot to do that earlier! 

@greg-schroeder can you get this paid out? Its a few days past the hold window with no regressions

**Comment by eVoloshchak** [comment] 2023-01-16 18:30
Not overdue, waiting for the payment to be settled

**Comment by alex-mechler** [comment] 2023-01-17 17:47
@greg-schroeder Bump :D

**Comment by greg-schroeder** [comment] 2023-01-19 22:49
Okay, dealing with this today

**Comment by greg-schroeder** [comment] 2023-01-19 22:54
Job posted here: https://www.upwork.com/jobs/~01439f03386b290b0b

@gadhiyamanan
@eVoloshchak 

Please apply - I will accept and work on paying ASAP

**Comment by greg-schroeder** [comment] 2023-01-19 22:58
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@alex-mechler / @eVoloshchak] The PR that introduced the bug has been identified. Link to the PR: 
- [ ] [@alex-mechler / @eVoloshchak]  The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
- [ ] [@alex-mechler / @eVoloshchak]  A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
- [ ] [@greg-schroeder] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:

**Comment by eVoloshchak** [comment] 2023-01-19 23:04
> @eVoloshchak ($1500)

Applied. It should be $1000, I just reviewed the PR, there is no bonus involved

**Comment by greg-schroeder** [comment] 2023-01-20 00:31
Thanks for letting me know, updated. 

Apologies to everyone for the delay on this, I was out for an extended period and had a hell of a time getting caught back up on everything.

**Comment by gadhiyamanan** [comment] 2023-01-20 03:36
@greg-schroeder applied

**Comment by alex-mechler** [comment] 2023-01-23 17:13
Filled out the eng side of the BZ checklist, and started the discussion in #expensify-bugs. Just waiting on payment to be wrapped up / regression tests to be updated

**Comment by greg-schroeder** [comment] 2023-01-24 08:04
Hired @gadhiyamanan, @eVoloshchak

**Comment by greg-schroeder** [comment] 2023-01-27 10:31
Paid, closed, doing regression

**Comment by greg-schroeder** [comment] 2023-01-30 12:47
Posted in slack re: regression here: https://expensify.slack.com/archives/C01SKUP7QR0/p1675082794909789

**Comment by greg-schroeder** [comment] 2023-01-30 17:11
Per Slack discussion, any potential regressions covered by design guidelines. Closing.

**Closed by greg-schroeder** 2023-01-30 17:11 UTC
Labels: Daily, Awaiting Payment, Bug
