### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] mWeb-Emoticon- In offline, emoji badge not greyed out when applied to the message sent in online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28059] opened 2023-09-23 11:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap profile- preferences
3. Toggle on forced offline
4. Navigate to LHN
5. Tap on a report with emoji badge used in conversation
6. Send a message
7. Long press the message sent and select any suggested emoji to note that added badge is greyed out
8. From above conversation with emoji badge used, tap on emoji picker near by and select it.
9. Note the applied emoji badge is not greyed out
10. From emoji picker, select any emoji for message sent in offline again

## Expected Result:
In offline, emoji badge must be greyed out when applied to the message sent in online/offline.

## Actual Result:
In offline, emoji badge is not greyed out when applied to the message sent in online.
In offline, emoji badge is greyed out only when applied to the message sent in offline.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/10b06914-d91e-47b9-91eb-6ea78b31ddea

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fd3015956e36877</li>
        <li>Upwork Job ID: 1706211356001812480</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26935912</li>
<li>abdel-h66 | Contributor | 26935913</li>
</ul></li>
    </ul>
</details>

**Comment by abdel-h66** [comment] 2023-09-23 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Offline mode, emojies that added to an existing message will not have a reduced opacity. 

### What is the root cause of that problem?
Adding emojies to a comment does not create a pending action related to the action. 

https://github.com/Expensify/App/blob/5aa7f6da94ddb1c8ca55a6cce714555f819c1dd0/src/libs/actions/Report.js#L1699-L1718



### What changes do you think we should make in order to solve the problem?

We can start first by modifying the `addEmojiReaction` action to correcly have optimistic and failure data as the usual. 
I will only provide snippets 

`[emoji.name]: {
                    pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.ADD,
                    createdAt,
                    users: {
                        [currentUserAccountID]: {
                            skinTones: {
                                [!_.isUndefined(skinTone) ? skinTone : -1]: createdAt,
                            },
                        },
                    },
                },
                `
                
  for `successData` and `failureData` we will just remove the pendingAction from the object. 
  
  The second step of the refactoring will be wrapping each emoji inside the `OfflineWithFeedback` comopnent, and with our new pendingAction property inside the reaction object we willl do something like this.
```
  <OfflineWithFeedback
      pendingAction={reaction.pendingAction}
      shouldDisableStrikeThrough
  >
```



### What alternative solutions did you explore? (Optional)

N/A

**Comment by greg-schroeder** [comment] 2023-09-25 07:37
Applying `External`

**Comment by jjcoffee** [comment] 2023-09-28 11:38
@abdel-h66's [proposal](https://github.com/Expensify/App/issues/28059#issuecomment-1732406339) LGTM! It makes sense to treat emojis the same way we're treating messages, i.e. use `pendingAction` in the `optimisticData` and wrap with `OfflineWithFeedback`.

:ribbon::eyes::ribbon: C+ reviewed

**Comment by srikarparsi** [comment] 2023-09-29 05:05
yeah looks good!

**Comment by abdel-h66** [comment] 2023-09-29 21:31
PR is ready for review @srikarparsi  @jjcoffee 🎉

**Comment by greg-schroeder** [comment] 2023-10-12 17:52
This is ready for payment tomorrow unless any regressions pop up

**Comment by jjcoffee** [comment] 2023-10-13 10:12
- The PR that introduced the bug has been identified. Link to the PR: **N/A** - looks like a missed case as the behaviour has always been there as far as I can tell
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go offline
2. Add an emoji reaction to any message
3. Verify that the emoji reaction is greyed out
4. Come back online
5. Verify that the emoji reaction displays normally

Do we agree 👍 or 👎

**Comment by greg-schroeder** [comment] 2023-10-16 13:13
Apologies, was sick on Friday. Processing today

**Comment by greg-schroeder** [comment] 2023-10-16 14:33
Payments made, filed regression test, closing.

**Closed by greg-schroeder** 2023-10-16 14:33 UTC
Labels: External, Daily, Awaiting Payment, Bug
