### ISSUE TITLE
Web - Back arrow takes the user back to the bank account flow event when it is completed.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23587] opened 2023-07-25 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the Settings Page.
2. Go to any workspace.
3. Click the last menu item `Bank Account`.
4. Finish the follow till you reach validate bank account.
5. Close the Page via clicking the main report area.
6. Repeat 1-3.
7. Notice that you are on validate bank account step. Click back arrow on the top header.

## Expected Result:
 As we have completed the bank account flow and validation is outside this normal flow, clicking back arrow should not take user back into the flow. There is a dedicated button to reset the bank account on the validate bank account page.

## Actual Result:
 User is taken back into the add bank account flow after it is has reached to Validate step.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.3
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/2f25f020-1b01-41c3-95a7-5950fc1fbf6f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690217980150829
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2023-07-26 18:19
Thanks @allroundexperts, closing this since this is expected behavior.

**Closed by isabelastisser** 2023-07-26 18:19 UTC
Labels: Daily, Needs Reproduction, Bug
