### ISSUE TITLE
[HOLD for payment 2023-02-07] [$1000] member count not updated for #announce

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14254] opened 2023-01-12 22:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Actions Performed:

1. create a workspace by userA
2. add userB as member
3. for userB, go to #announce > details > members
4. for userA, add a new member to the workspace
5. new member will be shown in the members list for userB , go back to details page and check the members count

## Expected Result:
member count should be updated

## Actual Result:
member count not updated

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.53-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/212194416-a695372c-3f40-45d7-8933-0204d49b578b.mov
https://user-images.githubusercontent.com/43996225/212194438-05051f6b-3b5f-4522-bfda-dcdc5daa13c5.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673513127757489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010681c413bd1587cd</li>
        <li>Upwork Job ID: 1615344869262090240</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-01-12 23:39
I'm OOO starting tonight until Tuesday and I won't get a chance to look at it in a timely manner. Reassigning to ensure the client isn't waiting on my return.

**Comment by twisterdotcom** [comment] 2023-01-17 13:46
My first few of these, so taking the template from StackOverflowTeams: https://stackoverflowteams.com/c/expensify/questions/14418

- [x] The "bug" is actually a bug.
- [x] The bug is not a duplicate report of an existing GH
- [x] The bug is reproducible, following the reproduction steps.
- [x] The GH template is filled out as fully as possible
- [x] The GH was created by an Expensify employee or a QA tester.
- [x] The bug is an /App issue

---

Okay, agreed. This happens both ways as well, when adding on desktop or web and when adding on iOS or Android. Seems completely cross platform that we're just not pushing the updated number. Viewing the list is also fine, that updates just like the chat does across platforms, so it's just the number in this option menu.

**Comment by tienifr** [comment] 2023-01-17 13:47
# Proposal
## Problem
When`props.report.participants` is updated in ONYX, the `menuItems` isn't updated
## Solution
We should add logic to update `menuItems` when `props.report.participants` is changed

```diff
diff --git a/src/pages/ReportDetailsPage.js b/src/pages/ReportDetailsPage.js
index 62afb287e..5a48e401c 100644
--- a/src/pages/ReportDetailsPage.js
+++ b/src/pages/ReportDetailsPage.js
@@ -106,6 +106,13 @@ class ReportDetailsPage extends Component {
             OptionsListUtils.getPersonalDetailsForLogins(participants, this.props.personalDetails),
             isMultipleParticipant,
         );
+        const membersItemIndex = _.findIndex(this.menuItems, item => item.key === CONST.REPORT_DETAILS_MENU_ITEM.MEMBERS);
+        if (membersItemIndex >= 0) {
+            this.menuItems[membersItemIndex] = {
+                ...this.menuItems[membersItemIndex],
+                subtitle: lodashGet(this.props.report, 'participants', []).length,
+            };
+        }
         return (
```

## Result

https://user-images.githubusercontent.com/113963320/212274833-e0658a04-dce7-49ff-8025-d99fdfd0fb04.mp4

**Comment by Pujan92** [comment] 2023-01-17 14:22
**Proposal**

Update the length of the participants for the first menu item as it is added statically and will be the first item always.

```diff
diff --git a/src/pages/ReportDetailsPage.js b/src/pages/ReportDetailsPage.js
index 62afb287e..0ca5f24de 100644
--- a/src/pages/ReportDetailsPage.js
+++ b/src/pages/ReportDetailsPage.js
@@ -101,6 +101,10 @@ class ReportDetailsPage extends Component {
         const isChatRoom = ReportUtils.isChatRoom(this.props.report);
         const chatRoomSubtitle = ReportUtils.getChatRoomSubtitle(this.props.report, this.props.policies);
         const participants = lodashGet(this.props.report, 'participants', []);
+        if (this.menuItems.length) {
+            // Update participants length in the menu item Members subtitle
+            this.menuItems[0] = {...this.menuItems[0], subtitle: participants.length};
+        }
         const isMultipleParticipant = participants.length > 1;
```

**Comment by Pujan92** [comment] 2023-01-17 14:26
> Update the length of the participants for the first menu item as it is added statically and will be the first item always.

https://user-images.githubusercontent.com/14358475/212924415-4bc87e69-787b-4e1a-854d-42ba8e141482.mp4

**Comment by tienifr** [comment] 2023-01-17 14:27
# Proposal 2

Since the menu items are generated in `constructor`, it will not change when `this.props.report` is changed, which might cause further inconsistency issue besides this one. So another way we can do is to generate the `menuItems` whenever the component render. This way, any update to the `this.props.report` will be reflected correctly in the menu items. 

```diff
diff --git a/src/pages/ReportDetailsPage.js b/src/pages/ReportDetailsPage.js
index 62afb287ed..9c8d1a739e 100644
--- a/src/pages/ReportDetailsPage.js
+++ b/src/pages/ReportDetailsPage.js
@@ -56,32 +56,36 @@ const propTypes = {
 class ReportDetailsPage extends Component {
     constructor(props) {
         super(props);
-
         this.menuItems = [];
+    }
+
+    setMenuItems() {
         if (ReportUtils.isArchivedRoom(this.props.report)) {
             return;
         }
 
+        const menuItems = [];
+
         // All nonarchived chats should let you see their members
-        this.menuItems.push({
+        menuItems.push({
             key: CONST.REPORT_DETAILS_MENU_ITEM.MEMBERS,
             translationKey: 'common.members',
             icon: Expensicons.Users,
-            subtitle: lodashGet(props.report, 'participants', []).length,
-            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(props.report.reportID)); },
+            subtitle: lodashGet(this.props.report, 'participants', []).length,
+            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(this.props.report.reportID)); },
         });
 
         if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.SETTINGS,
                 translationKey: 'common.settings',
                 icon: Expensicons.Gear,
-                action: () => { Navigation.navigate(ROUTES.getReportSettingsRoute(props.report.reportID)); },
+                action: () => { Navigation.navigate(ROUTES.getReportSettingsRoute(this.props.report.reportID)); },
             });
         }
 
         if (ReportUtils.isUserCreatedPolicyRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.INVITE,
                 translationKey: 'common.invite',
                 icon: Expensicons.Plus,
@@ -94,6 +98,8 @@ class ReportDetailsPage extends Component {
                 action: () => { /* Placeholder for when leaving rooms is built in */ },
             });
         }
+
+        this.menuItems = menuItems;
     }
 
     render() {
@@ -106,6 +112,7 @@ class ReportDetailsPage extends Component {
             OptionsListUtils.getPersonalDetailsForLogins(participants, this.props.personalDetails),
             isMultipleParticipant,
         );
+        this.setMenuItems();
         return (
             <ScreenWrapper>
                 <HeaderWithCloseButton
```

**Comment by tienifr** [comment] 2023-01-17 14:32
The [proposal 2](https://github.com/Expensify/App/issues/14254#issuecomment-1385509929) will be more preferable if:
- We expect there could be any change in the `report` leading to the evaluation of `isPolicyExpenseChat`, `isChatRoom`, `isUserCreatedPolicyRoom` changes
- We plan to add anything related to the `this.props.report` into the menu items in the future (similar to the participants count in this issue) and want to be safe

**Comment by tienifr** [comment] 2023-01-17 15:14
In the first proposal, I made some mistakes when I uploaded the video. 
This is the result of the first proposal

https://user-images.githubusercontent.com/113963320/212936245-c5a56a65-363f-4703-85a9-20d9387e7196.mp4

**Comment by flodnv** [comment] 2023-01-18 15:45
@parasharrajat what are your thoughts?

**Comment by fedirjh** [comment] 2023-01-18 16:17
### Proposal

#### Root cause
When props are updated , `this.menuItems` isn't updated hence the component will not re-render Menu ,So  we either refactor `this.menuItems` to use state and add update it `componentDidUpdate` or we have to always get menuItems during the render
#### Solution 

```diff
diff --git a/src/pages/ReportDetailsPage.js b/src/pages/ReportDetailsPage.js
index 62afb287ed..8578a8fd86 100644
--- a/src/pages/ReportDetailsPage.js
+++ b/src/pages/ReportDetailsPage.js
@@ -54,25 +54,28 @@ const propTypes = {
 };
 
 class ReportDetailsPage extends Component {
+    // eslint-disable-next-line no-useless-constructor
     constructor(props) {
         super(props);
+    }
 
-        this.menuItems = [];
+    getMenuItems() {
+        const menuItems = [];
         if (ReportUtils.isArchivedRoom(this.props.report)) {
-            return;
+            return menuItems;
         }
 
         // All nonarchived chats should let you see their members
-        this.menuItems.push({
+        menuItems.push({
             key: CONST.REPORT_DETAILS_MENU_ITEM.MEMBERS,
             translationKey: 'common.members',
             icon: Expensicons.Users,
-            subtitle: lodashGet(props.report, 'participants', []).length,
-            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(props.report.reportID)); },
+            subtitle: lodashGet(this.props.report, 'participants', []).length,
+            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(this.props.report.reportID)); },
         });
 
         if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.SETTINGS,
                 translationKey: 'common.settings',
                 icon: Expensicons.Gear,
@@ -81,7 +84,7 @@ class ReportDetailsPage extends Component {
         }
 
         if (ReportUtils.isUserCreatedPolicyRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.INVITE,
                 translationKey: 'common.invite',
                 icon: Expensicons.Plus,
@@ -94,6 +97,8 @@ class ReportDetailsPage extends Component {
                 action: () => { /* Placeholder for when leaving rooms is built in */ },
             });
         }
+
+        return menuItems;
     }
 
     render() {
@@ -106,6 +111,7 @@ class ReportDetailsPage extends Component {
             OptionsListUtils.getPersonalDetailsForLogins(participants, this.props.personalDetails),
             isMultipleParticipant,
         );
+        const menuItems = this.getMenuItems();
         return (
             <ScreenWrapper>
                 <HeaderWithCloseButton
@@ -149,7 +155,7 @@ class ReportDetailsPage extends Component {
                             </View>
                         </View>
                     </View>
-                    {_.map(this.menuItems, (item) => {
+                    {_.map(menuItems, (item) => {
                         const brickRoadIndicator = (
                             ReportUtils.hasReportNameError(this.props.report)
                             && item.key === CONST.REPORT_DETAILS_MENU_ITEM.SETTINGS
```

**Comment by s77rt** [comment] 2023-01-18 17:10
### Proposal
```diff
diff --git a/src/pages/ReportDetailsPage.js b/src/pages/ReportDetailsPage.js
index 62afb287ed..1679ce8b92 100644
--- a/src/pages/ReportDetailsPage.js
+++ b/src/pages/ReportDetailsPage.js
@@ -1,4 +1,4 @@
-import React, {Component} from 'react';
+import React, {PureComponent} from 'react';
 import PropTypes from 'prop-types';
 import {withOnyx} from 'react-native-onyx';
 import _ from 'underscore';
@@ -53,35 +53,34 @@ const propTypes = {
     personalDetails: PropTypes.objectOf(participantPropTypes).isRequired,
 };
 
-class ReportDetailsPage extends Component {
-    constructor(props) {
-        super(props);
-
-        this.menuItems = [];
+class ReportDetailsPage extends PureComponent {
+    buildMenuItems() {
         if (ReportUtils.isArchivedRoom(this.props.report)) {
-            return;
+            return [];
         }
 
+        const menuItems = [];
+
         // All nonarchived chats should let you see their members
-        this.menuItems.push({
+        menuItems.push({
             key: CONST.REPORT_DETAILS_MENU_ITEM.MEMBERS,
             translationKey: 'common.members',
             icon: Expensicons.Users,
-            subtitle: lodashGet(props.report, 'participants', []).length,
-            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(props.report.reportID)); },
+            subtitle: lodashGet(this.props.report, 'participants', []).length,
+            action: () => { Navigation.navigate(ROUTES.getReportParticipantsRoute(this.props.report.reportID)); },
         });
 
         if (ReportUtils.isPolicyExpenseChat(this.props.report) || ReportUtils.isChatRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.SETTINGS,
                 translationKey: 'common.settings',
                 icon: Expensicons.Gear,
-                action: () => { Navigation.navigate(ROUTES.getReportSettingsRoute(props.report.reportID)); },
+                action: () => { Navigation.navigate(ROUTES.getReportSettingsRoute(this.props.report.reportID)); },
             });
         }
 
         if (ReportUtils.isUserCreatedPolicyRoom(this.props.report)) {
-            this.menuItems.push({
+            menuItems.push({
                 key: CONST.REPORT_DETAILS_MENU_ITEM.INVITE,
                 translationKey: 'common.invite',
                 icon: Expensicons.Plus,
@@ -94,9 +93,12 @@ class ReportDetailsPage extends Component {
                 action: () => { /* Placeholder for when leaving rooms is built in */ },
             });
         }
+
+        return menuItems;
     }
 
     render() {
+        const menuItems = this.buildMenuItems();
         const isPolicyExpenseChat = ReportUtils.isPolicyExpenseChat(this.props.report);
         const isChatRoom = ReportUtils.isChatRoom(this.props.report);
         const chatRoomSubtitle = ReportUtils.getChatRoomSubtitle(this.props.report, this.props.policies);
@@ -149,7 +151,7 @@ class ReportDetailsPage extends Component {
                             </View>
                         </View>
                     </View>
-                    {_.map(this.menuItems, (item) => {
+                    {_.map(menuItems, (item) => {
                         const brickRoadIndicator = (
                             ReportUtils.hasReportNameError(this.props.report)
                             && item.key === CONST.REPORT_DETAILS_MENU_ITEM.SETTINGS
```

### RCA
The `menuItems` variable is a member of the class component and is only computed once on the `constructor` function. The thing is `menuItems` relies on the props that are passed to `<ReportDetailsPage />`. If any of those props changes, the `menuItems` becomes outdated as it won't change.

To have our component change the `menuItems` as well it must be treated as a state variable (because changing state variables triggers `render` function). This will require some additional work such as implementing `componentDidUpdate` or `getDerivedStateFromProps`. Neither are a good fit as the former will lead to double-render and the latter will make the component complex..

We can do a shortcut, by simply computing the `menuItems` at every render, but that requires us to use some kind of a memorisation technique otherwise the `menuItems` will be computed many times when not necessary. The most straightforward memorisation is to use `PureComponent` instead of `Component`

**Comment by twisterdotcom** [comment] 2023-01-23 17:20
Bump for @parasharrajat.

**Comment by flodnv** [comment] 2023-01-25 19:15
We've been discussing this one with @parasharrajat, thank you for your continued patience. ([Internal Slack link](https://expensify.slack.com/archives/C02NK2DQWUX/p1674485678159659))

**Comment by flodnv** [comment] 2023-01-25 20:01
I agree with @parasharrajat, let's hire @tienifr for his 2nd proposal, @twisterdotcom. 

@tienifr I have a small suggestion: how about getting rid of `this.menuItems`, renaming `setMenuItems` to `getMenuItems`, and calling `getMenuItems` in `render()`?

**Comment by tienifr** [comment] 2023-01-26 01:02
@flodnv sure, all good with that.et me implement accordingly in the PR.

Thanks.

**Comment by twisterdotcom** [comment] 2023-01-26 15:07
@tienifr - please make sure you've proposed on Upwork too. (Same @parasharrajat).

**Comment by tienifr** [comment] 2023-01-26 15:23
sorry @twisterdotcom I'm waiting for the assignment like [this](https://github.com/Expensify/App/issues/14314#issuecomment-1400205298) as the signal to get started on the PR. Would you mind handling the assignment?

thanks

**Comment by tienifr** [comment] 2023-01-26 17:32
Hi @parasharrajat, The [PR](https://github.com/Expensify/App/pull/14596) is ready for review. Please help to review it

**Comment by twisterdotcom** [comment] 2023-02-06 22:53
Just a heads up, I'm OOO tomorrow so this will be paid out on Feb 8th. Apologies for the minor delay.

**Comment by twisterdotcom** [comment] 2023-02-08 15:06
@gadhiyamanan and @parasharrajat could you add your applications to https://www.upwork.com/jobs/~010681c413bd1587cd please?

**Comment by twisterdotcom** [comment] 2023-02-08 15:08
Assigned: https://github.com/Expensify/App/issues/14254#event-8365191213 Jan 26 at 15:30 UTC
Merged: https://github.com/Expensify/App/pull/14596#event-8390985636 Jan 30 at 18:00 UTC

**Comment by twisterdotcom** [comment] 2023-02-09 23:43
@parasharrajat I still need your application on https://www.upwork.com/jobs/~010681c413bd1587cd

@parasharrajat and @flodnv - could you help with the three steps here: https://github.com/Expensify/App/issues/14254#issuecomment-1410947195

**Comment by tienifr** [comment] 2023-02-13 08:25
@twisterdotcom I think this issue is eligible for the PR timeline bonus since it's merged within 3 working days.

**Comment by twisterdotcom** [comment] 2023-02-14 14:13
Also @tienifr - great spot. I only just saw this was business days.

**Comment by twisterdotcom** [comment] 2023-02-14 14:15
@parasharrajat and @tienifr you should both have offers in Upwork to accept.

**Comment by twisterdotcom** [comment] 2023-02-14 15:01
@parasharrajat and @flodnv can you check off the boxes here: https://github.com/Expensify/App/issues/14254#issuecomment-1410947195

If there was no regression, as it seems like this was just how it was originally designed to work, let's just close this out.

**Comment by twisterdotcom** [comment] 2023-02-14 15:31
@tienifr are you able to propose the regression steps for me?

**Comment by tienifr** [comment] 2023-02-14 15:47
# Regression Test Proposal

**Bug**: Timezone changes to some 1st option in the list while pressing the enter key

**Proposed Test Steps**:

1. On device 1, create workspaceC by userA
2. Add userB as member
3. On device 2, for userB, go to #announce of the workspaceC  > details > members
4.  On device 1, for userA, add a new member to the workspace
5. Verify that on device 2, the new member will be shown in the members list for userB , go back to details page and verify the members count is display correctly

Do we :+1: or :-1: 

Video demo (Regression Test):
https://user-images.githubusercontent.com/113963320/212936245-c5a56a65-363f-4703-85a9-20d9387e7196.mp4

**Comment by flodnv** [comment] 2023-02-14 17:20
Sounds good 👍 

>Bug: Timezone changes to some 1st option in the list while pressing the enter key

But this is wrong, no? 😄

**Comment by tienifr** [comment] 2023-02-14 17:40
@flodnv oh my bad, I just updated.

**Comment by twisterdotcom** [comment] 2023-02-17 12:28
Slack discussion: https://expensify.slack.com/archives/C01SKUP7QR0/p1676636903920779

**Closed** 2023-02-17 12:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
