### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] Verify push to page design 

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#21715] opened 2023-06-27 17:44 UTC
https://github.com/Expensify/App/pull/21553#issuecomment-1609933984

> When a push row has no value, the label should float vertically and have a font size of 15px which matches our default font size. Then when it does have a value, the label is at 13px and sits above the value:

> In your screenshot, the labels with no value are too small.

Let's verify what we're using for the push to page font values. I believe we're using the same general component but those styles might have been updated somewhere 

cc @shawnborton 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01764a647f1d382849</li>
        <li>Upwork Job ID: 1673785844117725184</li>
        <li>Last Price Increase: 2023-06-27</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-06-27 17:45
Thanks!

**Comment by Nikhil-Vats** [comment] 2023-06-27 18:29
@thienlnam @shawnborton I checked and this is not the standard in app anymore, maybe the code was removed -

![image](https://github.com/Expensify/App/assets/31413407/a4e3b135-5d5f-4607-bf46-82df6baacf99)

https://github.com/Expensify/App/blob/c122266f96bab047cda55f0cebff8b3a61e97700/src/components/MenuItem.js#L89-L96

In line 93, we can see that if title (value) is populated then only margin is added. `font-size` is fixed in `textLabelSupporting` as `13px` -
https://github.com/Expensify/App/blob/c122266f96bab047cda55f0cebff8b3a61e97700/src/styles/styles.js#L1042-L1046

**Comment by Nikhil-Vats** [comment] 2023-06-27 18:48
@thienlnam @shawnborton I checked and this is not the standard in app anymore, I think the code was removed at some point -

![image](https://github.com/Expensify/App/assets/31413407/a4e3b135-5d5f-4607-bf46-82df6baacf99)

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/c122266f96bab047cda55f0cebff8b3a61e97700/src/components/MenuItem.js#L89-L96

In line 93, we can see that if title (value) is populated then margin is added otherwise we don't change `font-size` to `15px`. `font-size` is fixed in `textLabelSupporting` as `13px` -
https://github.com/Expensify/App/blob/c122266f96bab047cda55f0cebff8b3a61e97700/src/styles/styles.js#L1042-L1046

<details>
<summary>
Screenshots
</summary>

<img width="376" alt="Screenshot 2023-06-28 at 12 01 47 AM" src="https://github.com/Expensify/App/assets/31413407/23d3811f-aed3-4e9a-8828-b3dd42aa8bce">
<img width="372" alt="Screenshot 2023-06-28 at 12 02 06 AM" src="https://github.com/Expensify/App/assets/31413407/a2831ae4-febf-457c-8214-362ea5a7fecc">
<img width="372" alt="Screenshot 2023-06-28 at 12 02 16 AM" src="https://github.com/Expensify/App/assets/31413407/f80e936a-db79-4d3d-9cd1-f51dd5d3cd97">
<img width="370" alt="Screenshot 2023-06-28 at 12 02 42 AM" src="https://github.com/Expensify/App/assets/31413407/bd79d53f-46c3-48d6-87b9-fcef1b895f92">


</details>

### What changes do you think we should make in order to solve the problem?

We just need to add it back like - 
```javascript
props.title ? descriptionVerticalMargin : StyleUtils.getFontSizeStyle(variables.fontSizeNormal),
```

**Comment by shawnborton** [comment] 2023-06-27 20:06
Welp, let's fix it!

**Comment by thienlnam** [comment] 2023-06-27 20:10
Hah - lovely. Let's just make it external!

**Comment by thienlnam** [comment] 2023-06-27 20:10
@fedirjh Could you please review this proposal? https://github.com/Expensify/App/issues/21715#issuecomment-1610044723

**Comment by anmurali** [comment] 2023-07-07 16:59
https://www.upwork.com/nx/wm/offer/25415819 - @fedirjh 
https://www.upwork.com/nx/wm/offer/25415841 - @Nikhil-Vats 

Will pay on 10th!

**Comment by anmurali** [comment] 2023-07-14 10:53
Everyone's been paid!

**Closed by anmurali** 2023-07-14 10:53 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment
