### ISSUE TITLE
[$1000] Web - User details tooltip in workspace members list is different

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22062] opened 2023-07-02 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace
2. Go to members
3. Hover over the members icon

## Expected Result:
Tooltip should show display name in bold and login in gray

## Actual Result:
Only login is shown in gray, no display name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/437075f5-6f14-41d6-a587-2844acc84037

https://github.com/Expensify/App/assets/93399543/871c9eb7-f3cb-437b-b172-a790cfa9be5e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688199036733839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c11ba48600bf6205</li>
        <li>Upwork Job ID: 1676186298947235840</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-02 13:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

user details tooltip in workspace members list is different, display name is not present

### What is the root cause of that problem?

Root cause of the issue is the missing accountID in the icons prop of `<OptionRow/>` here

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/pages/workspace/WorkspaceMembersPage.js#L323-L340

The icons prop is passed to `<OptionRow/>` which passes the data in icons prop to `<MultipleAvatar/>` component which finally renders the `<UserDetailsTooltip/>`

`<UserDetaisTooltip/>` fetches the display name using the accountID which it expects in its icons prop.

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/MultipleAvatars.js#L83-L83

So when we don't pass accountID in the icons prop of `<OptionRow/>`, missing id field finally lands in `<UserDetailsTooltip/>` because of which it fails to render the display name.

### What changes do you think we should make in order to solve the problem?

As explained above, icons prop expects an `id` field which carries accountID for that member, so we need to provide that.
We are using item object to render details of each member which already has the accountID stored in it. We are also using that accountID to fetch the avatar of that member. So along with that, we can pass it to icons prop too to solve our issue.

```js
<OptionRow
    boldStyle
    isDisabled={disabled}
    option={{
        text: props.formatPhoneNumber(item.displayName),
        alternateText: props.formatPhoneNumber(item.login),
        participantsList: [item],
        icons: [
            {   
                id: item.accountID,
                source: UserUtils.getAvatar(item.avatar, item.accountID),
                name: item.login,
                type: CONST.ICON_TYPE_AVATAR,
            },
        ],
        keyForList: item.accountID,
    }}
    onSelectRow={() => toggleUser(item.accountID, item.pendingAction)}
/>
```

<details>
  <summary>Results</summary>


https://github.com/chiragxarora/pdf-download/assets/54641656/89ba8cef-29a2-46aa-9957-632d6a8c17ad





</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by daordonez11** [comment] 2023-07-05 00:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tooltip in the `WorkspaceMembersPage` is missing `displayName`
### What is the root cause of that problem?
 Coming from the PR https://github.com/Expensify/App/pull/21696 I included the fix of searching by ID but the actual issue is not sending the id, that is part of the migration to accountID, the real issue here is the inconsistency between different pages and components. My original [issue](https://github.com/Expensify/App/issues/21099) was in the search. Even though sending the id is a workaround the root cause is not reusing the code that already exists for this `getIcons` in the `ReportUtils` class. Hence, avoiding the anti-pattern of duplicating code. In the future if we want to change how the icon information is loaded we only have to change a single place.

### What changes do you think we should make in order to solve the problem?
Remove the manual creation of the icons in `WorkspaceMembersPage`

https://github.com/Expensify/App/blob/7e908b17565e7bf659309f4b4d95141e70094ab9/src/pages/workspace/WorkspaceMembersPage.js#L323-L340

And reuse the util code in `ReportUtils`

``` js
icons: ReportUtils.getIcons(undefined, props.personalDetails, UserUtils.getAvatar(item.avatar, item.accountID), false, item.login, item.accountID),
```
Video of solution working:

[New Recording - 4_7_2023, 19_37_59.webm](https://github.com/Expensify/App/assets/13544910/c5d2d65e-326d-4581-a663-7facf35eedb6)

### What alternative solutions did you explore? (Optional)
Just proposing to avoid code duplication no other alternatives explored.

**Comment by daordonez11** [comment] 2023-07-05 02:15
Yeah it is actually an old method. I recommend deep diving into similar components for a more valuable proposal, Also I don't think you can just take another proposal and use it as an alternative solution. I'll just let the C+ decide which proposal is better/simpler.

**Comment by daordonez11** [comment] 2023-07-05 02:47
How is it an expansion if it is my own solution from https://github.com/Expensify/App/pull/21696 😂? We even have different RCA. Again, I think it is in the hands of the C+ in charge 😀

**Comment by daordonez11** [comment] 2023-07-05 03:23
> Also **RCA is missing accountID 
That is where you are wrong.

Man, check my PR, you were literally one blame away from seeing that I changed the line of `getDisplayNameForParticipant`. The root cause as I mentioned in https://github.com/Expensify/App/pull/21696 is the migration that occurred in https://github.com/Expensify/App/pull/21026 here everything changed from login to accountID! That is the real root cause: duplicated code + refactor. Since that change, this issue started happening. That's why BZ List is so important, you didn't even find the original PR that introduced the issue before proposing the solution. 

If you had really read my proposal you would see that it enters the first if, because here there is no report.

**Comment by daordonez11** [comment] 2023-07-05 04:22
You are right! @chiragxarora. Including additional parameters isn't the solution if we want to unify it we should send the `personalDetail` object and get out the information there or create an specific method like `getIconWithPersonalDetail` but I'm thinking about the future. If it is a method at least you know that you have to check all places where the method is called, that is the main added value.  Without it you would have to manually search all places where information is sent to `MultipleAvatars`, even though it is a workaround it is easier for future developers that touch the code! Just thinking about future coding and devs. Maybe it can be another util or maybe it can be adding the additional parameter if things are not going to change for that component but since recently there was the [update](https://github.com/Expensify/App/pull/20276) of `UserDetailsTooltip` I'm afraid it can happen again.

You are right the idea is to force it so it is clear whenever someone touches again this part of the code. 

I'm just claiming it is a different solution than yours with different purposes, as you have stated, nothing else. You were right regarding my RCA that's why I updated it! Thanks for pointing that out.

**Comment by dylanexpensify** [comment] 2023-07-05 07:21
@rushatgabhane can we please get reviews?

**Comment by daordonez11** [comment] 2023-07-07 05:25
The problem is with `MultipleAvatars`. For example `DisplayNames` has an implementation that receives `displayNamesWithToolTips` via params:

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/OptionRow.js#L213-L216

On the other side MultipleAvatars only receives the icons prop, which doesn't even contain the displayName and builds the information manually here: 

https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/MultipleAvatars.js#L72-L87

We could definitely send the `displayName` via props on the icon but it would also require a lot of changes for consistency in points like: `SearchPage state, ReportParticipantsPage, BaseReactionList` or we could do something like

```js
displayName: props.icons[0].displayName || ReportUtils.getDisplayNameForParticipant(props.icons[0].id),
```

For retrocompat Still the main idea is to unify the way icons are built through the different instances of `OptionRow` ideally with a util method to ensure future changes in the behavior of tooltips.

@rushatgabhane

**Comment by dylanexpensify** [comment] 2023-07-10 07:23
@rushatgabhane let's get an update today!

**Comment by daordonez11** [comment] 2023-07-10 12:13
Hey there! So @chiragxarora was the first to propose! But his proposal was just sending the ID to MultipleAvatars. I discovered the real root cause and explained why it was required in other instances. He then created a new proposal based on our discussion but it was my idea to reuse a Util in the different places to avoid future issues he later proposed using a different util instead of just the id. To be clear. I just think this is unnecessary we should assign @chiragxarora and move over 😂 I just wanted to fix the real issue from its root!

Cc @rushatgabhane

**Comment by daordonez11** [comment] 2023-07-10 20:40
Thanks for the update @chiragxarora! Just commented on the offending [PR](https://github.com/Expensify/App/pull/20512), they caused a regression! Regarding RCA It is this [commit](https://github.com/daordonez11/DanielExpensify/commit/ef3d9558f796a6401b1a05d1ecb50c890cf120cd#diff-65c096044d5f69b35bcdec14c99c4fda4580759df9b1a7c36650d58eea276f1d) As explained in my proposal. The component started failing after the migration from login to accountId. I like your idea of the util better and it is important to include in this PR that all the calls in OptionRow should use the same method to generate the user icons! @amyevans whenever you can give it a check please assign @chiragxarora who proposed first and improved his solution as expected.

**Comment by dylanexpensify** [comment] 2023-07-12 08:45
@rushatgabhane can we get a reply on the above comment today? Thank you!!

**Comment by grgia** [comment] 2023-07-12 08:59
Copying over from slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1689152366088119?thread_ts=1689077322.531679&cid=C01GTK53T8Q

**Comment by dylanexpensify** [comment] 2023-07-17 09:17
Reviewing today!

**Comment by dylanexpensify** [comment] 2023-07-24 08:33
@rushatgabhane @chiragxarora mind recapping where we're at here?

**Comment by rushatgabhane** [comment] 2023-07-25 16:11
@chiragxarora what action is pending?

**Comment by dylanexpensify** [comment] 2023-07-27 17:17
@chiragxarora we can pay for the reporting bonus! Have you applied?

**Comment by dylanexpensify** [comment] 2023-07-31 09:10
bump @chiragxarora

**Comment by amyevans** [comment] 2023-07-31 13:30
@dylanexpensify this bug was fixed elsewhere, can you pay the $250 reporting bonus and then we can close this out?

**Comment by dylanexpensify** [comment] 2023-08-03 11:22
Yes! @chiragxarora will pay out for both

**Comment by dylanexpensify** [comment] 2023-08-03 11:22
Done!

**Closed by dylanexpensify** 2023-08-03 11:22 UTC
Labels: Engineering, Daily, Internal, Bug
