### ISSUE TITLE
[$500] IOU - "Hmm... it's not here" message displayed when opening the description via URL

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33879] opened 2024-01-03 16:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open a chat.
2. Create a 1:1 conversation
3. Click on plus button and select Request
3. Enter an amount and click next.
4. Click on the description and copy the URL.
5. Send the URL to the chat conversation and click on it.
6. Observe that the message "Hmm... it's not here" is displayed.

## Expected Result:
When opening the description via URL, the "Hmm... it's not here" message should not be displayed, as it is not displayed in the sending money section.

## Actual Result:
The "Hmm... it's not here" message is displayed when opening the description via URL.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/0a05ffcc-2e28-4e53-a49e-ac34d15c4dd5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014547bde1303442cc</li>
        <li>Upwork Job ID: 1742586561977024512</li>
        <li>Last Price Increase: 2024-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28089560</li>
</ul></li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2024-01-04 21:39
@kbecciv - I can't play your video to confirm, not sure what's up with mp4s lately for me, but are there additional steps between 3 and 4? Should I split the request with someone, just select a user? Do I need to save the request as well before clicking the description? 

For step 5, is the "user" the person you sent the request with?

It would be great if you could flush out your repro steps with some additional info if possible. Thanks!

**Comment by kbecciv** [comment] 2024-01-08 19:00
@strepanier03 I reduced the size of the video. Please let me know if it works.

https://github.com/Expensify/App/assets/93399543/9ffc9aec-f4ba-4d2a-83d9-d9438075ebd4

**Comment by situchan** [comment] 2024-01-08 21:39
I'd be interested in reviewing this

**Comment by strepanier03** [comment] 2024-01-08 22:01
@situchan - Assigned you in the C+ role, thanks for stepping up.

**Comment by strepanier03** [comment] 2024-01-08 22:02
@kbecciv - Thanks for the video, it's working now and I can see the steps very clearly, I appreciate it a lot. I'm testing again now.

**Comment by strepanier03** [comment] 2024-01-08 22:09
I tested this and can recreate following the steps. 

To me it makes sense that you can't find the request with he link because it wasn't saved and created, but you get the same behavior even if enter a description, save, reopen and copy the link again so I think we need to fix this.

**Comment by strepanier03** [comment] 2024-01-10 00:46
Did another round of testing and can confirm that the steps in the OP recreate the issue, but it's expected because the Money Request is not fully created, so the URL isn't expected to link to the description. 

If you fully create the Money Request, then the URL works as expected. 

If you use the same link from the creation step there will be an error, but if you use the edit link it should work

Create:
https://dev.new.expensify.com:8082/create/request/description/1/2746965716522490?backTo=%2Fcreate%2Frequest%2Fconfirmation%2F1%2F2746965716522490

Edit:
https://dev.new.expensify.com:8082/r/5390101976261911/edit/description

Since this is expected behavior, I'm going to close this out.

**Closed by strepanier03** 2024-01-10 00:46 UTC
Labels: External, Daily, Bug
