### ISSUE TITLE
Stuck on loading skeleton when opening search

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#53363] opened 2024-12-02 00:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.69-1
**Reproducible in staging?:** Y
**Reproducible in production?:**
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_quality](https://expensify.slack.com/archives/C05LX9D6E07/p1733091158732149)

## Action Performed:
1. Go to staging.new.expensify.com
2. Click search
## Expected Result:
Expense page displayed
## Actual Result:
Loading skeleton displayed 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/97ef3698-63fe-4743-83cb-c0427e986ecf

<img src="https://github.com/user-attachments/assets/40309d95-23ed-4632-8404-adb807b68b6d" width="40%" height="40%">

https://github.com/user-attachments/assets/373f9e83-f9e9-48d7-ae6a-b673790f78cc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huult** [comment] 2024-12-02 15:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search section loads infinitely when opened after logging in

### What is the root cause of that problem?

We called the search API with this `jsonQuery`, but the response returned an empty `onyxData` array.
```json
jsonQuery: {"type":"expense","status":"all","sortBy":"date","sortOrder":"desc","filters":null,"inputQuery":"type:expense status:all sortBy:date sortOrder:desc","hash":243428839,"recentSearchHash":422547233,"offset":0}
```

The reason for the empty `onyxData` array might be that the backend validated the query as having the wrong format or something similar.

And since `onyxData` is an empty array, `shouldShowLoadingState` always returns `false`, which is why the loading state is not hidden.
https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L222

https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L309

### What changes do you think we should make in order to solve the problem?

To resolve this issue, we need to do two things:

1. Double-check the JSON query to match the backend's requirements.
2. Handle the case where `onyxData` is an empty array.

https://github.com/Expensify/App/blob/9933888bd1576e2723560b938945b805b8a8d3d3/src/components/Search/index.tsx#L308
```diff
    if (searchResults === undefined && !isOffline) {
        setShouldShowStatusBarLoading(false);
        
        return (
            <View style={[shouldUseNarrowLayout ? styles.searchListContentContainerStyles : styles.mt3, styles.flex1]}>
                <EmptySearchView type={type} />
            </View>
        );
    }
```

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/9dbc71d4-3779-4c1a-a389-83213b48f445

</details>

### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment] 2024-12-02 15:52
related https://github.com/Expensify/App/issues/53285

**Comment by youssef-lr** [comment] 2024-12-02 15:53
Thanks @huult, I think we can close this in favor of the other issue.

**Closed by youssef-lr** 2024-12-02 15:53 UTC
Labels: Daily, Weekly, Bug, AutoAssignerNewDotQuality
