### ISSUE TITLE
Attachment - White blank page is displayed for a brief moment when uploading PDF file

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14438] opened 2023-01-20 16:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log i with any account
3. Go to any chat
4. Tap on plus button
5. Select Add Attachment
6. Select Documents
7. Select PDF file and Send
8. Open the PDF file
**PDF file**
[House Party 3 Lunar New Year Flyer.pdf](https://github.com/Expensify/App/files/10467962/House.Party.3.Lunar.New.Year.Flyer.pdf)

## Expected Result:
No white blank page is displayed for a brief moment when uploading PDF file

## Actual Result:
White blank page is displayed for a brief moment when uploading PDF file

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / Chrome
- [ ] iOS / Safari
- [ ] Web / Chrome / 

**Version Number:** 1.2.57.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/213747499-30e1f3b4-fd66-489d-bf2a-7319e37aa887.mp4

https://user-images.githubusercontent.com/93399543/213747713-03766c67-c46a-4e3f-be9b-6b9412d1f652.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-01-20 22:53
I think we should close this. It's not really worth fixing / barely noticeable. Also we are already taking advantage of the base libraries "loading" prop and it appears to work as intended in the video shared.

**Closed by marcaaron** 2023-01-20 22:53 UTC
Labels: Daily, Bug
