### ISSUE TITLE
[HOLD for payment 2023-10-30] [HOLD #25714] Split bill - App crashes when splitting bill in group with both expensifail and gmail accounts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21268] opened 2023-06-21 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20838
## Action Performed:
1. Login to NewDot
2. Create a group with several gmail and expensifail accounts
3. Go to created group chat
4. Tap + and create a split bill for the whole group

## Expected Result:
Successful Split Bill

## Actual Result:
App crashes (Android)
App freezes (Web, mWeb)
Error message when creating split bill (iOS)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5b133a20-28e7-48fd-acba-f26dff8e9b9d

https://github.com/Expensify/App/assets/78819774/3ae0f5fe-fce4-4bfd-8d9a-aef27d1ec279

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-06-21 22:13
@aldo-expensify if it helps, I see these logs in crashlytics:

```
Non-fatal Exception: io.invertase.firebase.crashlytics.JavaScriptError: array list[1] is not type String
       at .stringListFromIterable(address at index.android.bundle:1:5688527)
       at .anonymous(address at index.android.bundle:1:5690123)
       at .arrayToString(address at index.android.bundle:1:1847665)
       at .createSplitsAndOnyxData(address at index.android.bundle:1:2878809)
       at .splitBill(address at index.android.bundle:1:2881501)
       at .anonymous(address at index.android.bundle:1:2671772)
       at .onConfirm(address at index.android.bundle:1:2672957)
       at .anonymous(address at index.android.bundle:1:2767405)
       at .onPress(address at index.android.bundle:1:2767806)
       at .onPress(address at index.android.bundle:1:2770537)
       at .onPress(address at index.android.bundle:1:1725618)
       at .anonymous(address at index.android.bundle:1:1839331)
       at ._performTransitionSideEffects(address at index.android.bundle:1:416247)
       at ._receiveSignal(address at index.android.bundle:1:415835)
       at .onResponderRelease(address at index.android.bundle:1:414649)
       at .apply((native):0:0)
       at .invokeGuardedCallbackImpl(address at index.android.bundle:1:337841)
       at .apply((native):0:0)
       at .invokeGuardedCallback(address at index.android.bundle:1:337898)
       at .apply((native):0:0)
       at .invokeGuardedCallbackAndCatchFirstError(address at index.android.bundle:1:337930)
       at .executeDispatch(address at index.android.bundle:1:338062)
       at .executeDispatchesAndReleaseTopLevel(address at index.android.bundle:1:342319)
       at .forEach((native):0:0)
       at .forEachAccumulated(address at index.android.bundle:1:339560)
       at .anonymous(address at index.android.bundle:1:342671)
       at .batchedUpdatesImpl(address at index.android.bundle:1:401877)
       at .batchedUpdates(address at index.android.bundle:1:342239)
       at ._receiveRootNodeIDEvent(address at index.android.bundle:1:342512)
       at .receiveTouches(address at index.android.bundle:1:396657)
       at .apply((native):0:0)
       at .__callFunction(address at index.android.bundle:1:139406)
       at .anonymous(address at index.android.bundle:1:137771)
       at .__guard(address at index.android.bundle:1:138724)
       at .callFunctionReturnFlushedQueue(address at index.android.bundle:1:137729)
```

**Comment by aldo-expensify** [comment] 2023-06-21 22:17
I got this on web:

<img width="588" alt="image" src="https://github.com/Expensify/App/assets/87341702/2039aae5-1465-4d36-84fb-f4ab0a62d833">

The error looks similar to the one above.

**Comment by aldo-expensify** [comment] 2023-06-21 22:21
The `gmail` participants of the group have `login: undefined`: 

<img width="722" alt="image" src="https://github.com/Expensify/App/assets/87341702/7277004d-28c7-47d2-9aaa-c05325892c4d">

I find it strange because these are accounts that existed in my database (I created them before creating the group)

The code crashes around here:

https://github.com/Expensify/App/blob/1745b01ef0ceea8f39b0d41f21b47d142d7380d0/src/libs/actions/IOU.js#L462

**Comment by aldo-expensify** [comment] 2023-06-21 22:38
Asking in slack about expected behaviour: https://expensify.slack.com/archives/C03TQ48KC/p1687387011143229

**Comment by aldo-expensify** [comment] 2023-06-21 23:58
Considering [this](https://expensify.slack.com/archives/C03TQ48KC/p1687391533906429?thread_ts=1687387011.143229&cid=C03TQ48KC), this is not a deploy blocker anymore.

**Comment by aldo-expensify** [comment] 2023-06-22 00:21
I created a [draft PR](https://github.com/Expensify/App/pull/21290) with the progress I was able to make to disallow splitting with accounts that have a missing `login`. Since less accounts are selected than the total of the group, this ends up creating a sub group with only the selected accounts of the split. See the result in the video here: https://github.com/Expensify/App/pull/21290

I will prioritize other things for now since this is not for SNH anymore.

cc @Beamanator @puneetlath feel free to continue working on this if you want, I won't remove my assignment for now.

**Comment by aldo-expensify** [comment] 2023-06-30 21:15
@puneetlath @Beamanator I haven't been able to get back to this, and I'm going OOO for the next week. I'll reassign it to @puneetlath since you offered yourself before :)

**Comment by puneetlath** [comment] 2023-07-11 18:23
I will pick this back up soon.

**Comment by jeet-dhandha** [comment] 2023-07-14 18:33
The issue here is that when creating a new chat with unknown member the `personalDetails` don't have `login` key's value, we can see similar issue in given link https://github.com/Expensify/App/issues/22503.

**Comment by jeet-dhandha** [comment] 2023-07-14 18:34
Thus everything depending on the `login` should show some issue like this. Even in the backend.

**Comment by puneetlath** [comment] 2023-07-27 21:45
Plan to start on this very soon. Just wrapping up some report.participants stuff first that is semi-related.

**Comment by puneetlath** [comment] 2023-08-08 20:48
Almost ready to start on this. participants stuff is getting closer.

**Comment by puneetlath** [comment] 2023-08-23 16:04
Putting on hold for https://github.com/Expensify/App/issues/25714

**Comment by puneetlath** [comment] 2023-09-07 02:46
Still on hold.

**Comment by Julesssss** [comment] 2023-09-13 08:21
Reproduced on Android native and iOS native today: `1.3.67-3`

**Comment by puneetlath** [comment] 2023-09-18 19:07
https://github.com/Expensify/App/issues/25714 is getting close.

**Comment by puneetlath** [comment] 2023-10-04 17:08
Seems to be fixed now!

**Comment by izarutskaya** [comment] 2023-10-10 10:49
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
** This bug is reproducible again
Creating a Split Bill from a group conversation freezes and an error appears in the console

## Expected Result:
Successful Split Bill

## Actual Result:
App crashes (Android)
App freezes (Web)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.80.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/6bc1818c-bbde-427e-b5a8-6d85b49b6776

An error appears in production

![Screenshot 2023-10-10 134530](https://github.com/Expensify/App/assets/115492554/49fa56fd-bbae-4e43-91fe-d166b77973e6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Comment by puneetlath** [comment] 2023-10-30 15:41
I don't think anyone needs to be paid here, so closing out.

**Closed by puneetlath** 2023-10-30 15:41 UTC
Labels: Engineering, Daily, Awaiting Payment
