### ISSUE TITLE
[$1000] Can enter composer when confirm modal is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24045] opened 2023-08-02 10:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Chat any message
3. Hover above message => Edit
4. Delete all text
5. Click save changes, Observe that the confirm delete comment modal is open
6. Press any letter keyboard
## Expected Result: 
Unable to enter composer while modal confirm is open
## Actual Result: 
Able to enter composer while modal confirm is open
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/43042304-a0c7-4ad5-b8b2-32effbb738fc

https://github.com/Expensify/App/assets/43996225/d8194477-03a0-4d96-876f-254ff92157b7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690735241187249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb5e9bdf1f58de21</li>
        <li>Upwork Job ID: 1689380619329187840</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:19
On @samh-nl 's proposal here. It is causing the focus to jump to main composer when we select 'Cancel' in the modal.


https://github.com/Expensify/App/assets/46707890/f6b51096-e060-47a3-b211-a7d77c8038c5

**Comment by ShogunFire** [comment] 2023-08-13 12:15
> On @samh-nl 's proposal here. It is causing the focus to jump to main composer when we select 'Cancel' in the modal.
> 
>  Screen.Recording.2023-08-13.at.2.46.56.PM.mov

This is actually another issue, and the PR is being made based on this proposal to give back the focus to the right composer after a modal is closed https://github.com/Expensify/App/issues/23898#issuecomment-1664008195

**Comment by b4s36t4** [comment] 2023-08-14 03:33
Maybe dupe of #23403?

**Comment by Santhosh-Sellavel** [comment] 2023-08-14 16:58
Yes this is dupe of #23403

**Comment by danieldoglas** [comment] 2023-08-21 15:03
This also happens with `Delete Request`, which also uses `ConfirmModal`.

**Closed** 2023-08-22 17:11 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
