### ISSUE TITLE
[$250] Android - Room - When 2nd user suggestions whisper triggered, 1st whisper disappeared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47255] opened 2024-08-12 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.19
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** [N/A](https://expensify.testrail.io/index.php?/tests/view/4847423)
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Tap on a room chat
3. Enter @[jaihanumanblog@gmail.com](mailto:jaihanumanblog@gmail.com)
& send the message
4. Note whisper is shown
5. Enter @[vincenzoddragon@gmail.com](mailto:vincenzoddragon@gmail.com)
& send the message
6. Note whisper for step 5 user shown but step 4 whisper disappeared.
7. Navigate to troubleshoot-- clear cache
8. Revisit the room chat
9. Now note 2 whisper message displayed

## Expected Result:
When 2nd user suggestions whisper triggered, 1st whisper must not be disappeared

## Actual Result:
When 2nd user suggestions whisper triggered, 1st whisper disappeared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6496f93c-4c6e-4472-a32d-7462cd02da97

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01510cc10b7d91bb22</li>
        <li>Upwork Job ID: 1823376178599453123</li>
        <li>Last Price Increase: 2024-08-27</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103711687</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-08-12 18:14
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-08-13 15:08
Sounds like a bug to me

**Comment by sonialiap** [comment] 2024-08-16 13:20
@stephanieelliott I'm OOO Aug 19-30, adding leave buddy. 
Status: waiting for proposals

**Comment by akinwale** [comment] 2024-08-20 08:28
Still waiting for proposals.

**Comment by burczu** [comment] 2024-08-23 07:45
Hi, I’m Bartek from Callstack and I would like to work on this issue.

**Comment by VincentCorleone** [comment] 2024-08-23 19:37
# Proposal
## Please re-state the problem that we are trying to solve in this issue.
After mentioning a user who are not in the cureent room the second time, previous ACTIONABLEMENTIONWHISPER message disappear.
## What is the root cause of that problem?
### Short Answer
After mentioning a user who is not in the current room the second time, the browser requests the addComment api to the backend, then the backend gives back an inappropriate response that contains a merge command that will delete the previous ACTIONABLEMENTIONWHISPER message.
### Long Answer
Let's observe three JSON segments first.

Onyx data after update from the previous response(Unrelevant fields are omitted):
```json
{
    "reportActions_3703223916129889": {
        "297903893454568668": {
            "actionName": "ACTIONABLEMENTIONWHISPER",
            "message": [
                {
                    "deleted": "",
                    "html": "Heads up, <mention-user accountID=15075387></mention-user> isn't a member of this room.",
                    "isDeletedParentAction": false,
                    "isEdited": false,
                    "text": "Heads up,  isn't a member of this room.",
                    "type": "COMMENT",
                    "whisperedTo": [
                        17159591
                    ]
                }
            ],
        }
    }
}
```


Onyx data after update from the previous response(Unrelevant fields are omitted):
```json
{
    "reportActions_3703223916129889": {
        "297903893454568668": {
            "actionName": "ACTIONABLEMENTIONWHISPER",
            "message": [
                {
                    "deleted": "2024-08-23 17:15:21.188",
                    "type": "TEXT"
                }
            ],
        }
    }
}
```


Onyx data after clearing cache and refresh(Unrelevant fields are omitted):
```json
{
    "reportActions_3703223916129889": {
        "297903893454568668": {
            "message": [
                {
                    "type": "COMMENT",
                    "html": "Heads up, <mention-user accountID=15075387></mention-user> isn't a member of this room.",
                    "text": "Heads up,  isn't a member of this room.",
                    "isEdited": false,
                    "whisperedTo": [
                        17159591
                    ],
                    "isDeletedParentAction": false,
                    "deleted": ""
                }
            ],
            "actionName": "ACTIONABLEMENTIONWHISPER"
        }
    }
}
```

We can see in Onyx data after updating from the previous response, reportActions_3703223916129889.297903893454568668.message.deleted is modified to a specific timestamp from an empty string and reportActions_3703223916129889.297903893454568668.message lost detail message to show in the UI layer. After my investigation, I got that ReportActionsUtils.isDeletedAction(reportAction) equals false when deleted is set to an empty string and ReportActionsUtils.isDeletedAction(reportAction) equals true when deleted is set to a specific time stamp. That ReportActionsUtils.isDeletedAction(reportAction) equals false will result in this report action not showing in the UI layer.

What makes the modification? It's the second response of the addComment api.
Let's compare the first and the second response of the addComment api. The difference is [here](https://www.diffchecker.com/rqdkzifc/). We can see onyxData[0] makes the modification.

So the root cause is the inappropriate response of addComment api from the backend.


## What changes do you think we should make in order to solve the problem?
Ask the backend developer to remove the logic that generates onyxData[0] in  the second response of the addComment api.

## What alternative solutions did you explore? (Optional)
none

**Comment by stephanieelliott** [comment] 2024-08-28 00:51
Sounds good @burczu, will assign you!

**Comment by burczu** [comment] 2024-08-28 07:31
@akinwale Please take a look at the proposal from @VincentCorleone - I've requested to be assigned to this issue as a contributor from the agency, but if the proposal is legit, I think it's better to assign its author.

**Comment by stephanieelliott** [comment] 2024-08-30 01:48
Hey @akinwale bump on the above ^^, can you review the proposal for us?

**Comment by akinwale** [comment] 2024-08-30 05:12
After taking a look, the proposal suggests that this ideally should be fixed in the BE. The alternative approach is more of a workaround which isn't suitable, so we're looking for a better solution on the frontend, if viable. 

cc @stephanieelliott @burczu

**Comment by burczu** [comment] 2024-09-02 11:42
@akinwale I've done my research and I agree with the @VincentCorleone proposal, that this is the backend issue and we should ask someone from the backend team to take a look at this.

This part of the AddComment API response removes the previous whisper indeed:

![Screenshot 2024-09-02 at 13 41 17](https://github.com/user-attachments/assets/5b079539-5631-405e-9e8f-abe11191c1d8)

**Comment by sonialiap** [comment] 2024-09-03 10:16
Sounds like both @akinwale and @burczu agree that this should be an internal issue 👍 ? If yes, I'll add the internal label

**Comment by akinwale** [comment] 2024-09-08 16:28
> Sounds like both @akinwale and @burczu agree that this should be an internal issue 👍 ? If yes, I'll add the internal label

Yes, this can be made internal.

**Comment by sonialiap** [comment] 2024-09-10 16:08
Moved to internal

**Comment by sonialiap** [comment] 2024-09-12 10:04
VSB is on hold so internal issues aren't being picked up unless it's an important bug. I don't think this issue is critical but would be good to fix, so keeping it open but moving to weekly

**Comment by sonialiap** [comment] 2024-09-24 10:28
Not an engineering priority

**Comment by sonialiap** [comment] 2024-10-03 09:59
closing for focus

**Closed by sonialiap** 2024-10-03 09:59 UTC
Labels: Weekly, Internal, Overdue, Bug, Hot Pick
