### ISSUE TITLE
[HOLD FOR PAYMENT 2024-07-15] Expense - Missing report title in report details page after the expense is paid

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44959] opened 2024-07-08 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat with no unsettled expense
3. Submit an expense
4. Go to transaction thread
5. Pay the expense (same account as admin)
6. Click on the report header

## Expected Result:
There will be report title in report details page after the expense is paid

## Actual Result:
There is no report title in report details page after the expense is paid

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4c452064-22b0-46c0-80f4-e381d53cf66f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by lanitochka17** [comment] 2024-07-08 13:25
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 13:25
We think that this bug might be related to #wave-collect - Release 1

**Comment by Julesssss** [comment] 2024-07-08 14:10
Thanks @ShridharGoel, I'm not familiar with this flow but your logic makes sense to me. Please go ahead and submit a PR

**Comment by Julesssss** [comment] 2024-07-08 14:16
Possibly related to the edit report title [PR](https://github.com/Expensify/App/pull/44671).

**Comment by allroundexperts** [comment] 2024-07-08 14:51
@Julesssss can you assign this to me? Thanks!

**Comment by johncschuster** [comment] 2024-07-10 14:12
@Julesssss just making sure I'm following along correctly – the PR that I should be watching for regressions is https://github.com/Expensify/App/pull/44973, right?

**Comment by Julesssss** [comment] 2024-07-10 14:25
Hey @johncschuster. Yep that's correct 👍

**Comment by johncschuster** [comment] 2024-07-11 14:36
Thanks! Looks like it was approved on July 8, so I will pay this out on July 15 assuming no regressions 👍

**Comment by johncschuster** [comment] 2024-07-15 14:19
No regressions! I'll get this paid out today.

**Comment by johncschuster** [comment] 2024-07-15 14:25
# Payment Summary:
Contributor+: @allroundexperts  - $250 - paid via Manual request
Contributor: @ShridharGoel  - $250 - paid via [Upwork](https://www.upwork.com/offer/103124714)

**Comment by johncschuster** [comment] 2024-07-16 13:38
@ShridharGoel, can you accept the job linked above so I can issue payment?

**Comment by johncschuster** [comment] 2024-07-17 14:35
Bumped in Slack 👍

**Comment by johncschuster** [comment] 2024-07-19 14:46
Upwork job has not been accepted yet. Holding on that.

**Comment by johncschuster** [comment] 2024-07-22 15:01
Payment has been issued to @ShridharGoel! @allroundexperts, please request payment via ND if you haven't already done so.

**Closed by johncschuster** 2024-07-22 15:01 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 11:08
$250 approved for @allroundexperts
