### ISSUE TITLE
[$250] The mobile attachment picker on Android web is giving option to record audio and video

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46336] opened 2024-07-26 23:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721965815025499

## Action Performed:
1. Go to staging.new.expensify.com
2. Tap Global +
3. Tap Track > Scan > Attachment picker

## Expected Result:

1. On Android native, we don't offer "Take photo" when opening the attachment menu from the camera
2. On Android web, let's really try to just follow the exact same flow as Android native
3. On Android web, let's not ask to take a video or record audio

## Actual Result:
Not matching with Android native and giving option to record audio and video for attachment picker
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [X] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<img src="https://github.com/user-attachments/assets/a6d729a7-6f3d-4048-866b-ef23cfac72b8" width="40%" height="40%">

<img src="https://github.com/user-attachments/assets/55f1b6c4-b857-4c1a-b9d7-b050ee714418" width="40%" height="40%">

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014aa6bba3d11a7600</li>
        <li>Upwork Job ID: 1818599086364884619</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103436535</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by eh2077** [comment] 2024-07-31 15:14
@daledah Thanks for your proposal! 

Does the inconsistency only happen with mobile Chrome? Or both mobile web platforms have same issue?

As your solution suggests to pass accepted files types in `App/src/components/AttachmentPicker/index.tsx`, I'm not sure if it would break some feature on web platforms.

**Comment by eh2077** [comment] 2024-08-04 16:01
@daledah 's [proposal](https://github.com/Expensify/App/issues/46336#issuecomment-2260290282) looks good to me. Coding details can be discussed in PR and we need to ensure mobile platforms have consistent behaviour.

🎀👀🎀 C+ reviewed

**Comment by eh2077** [comment] 2024-08-07 16:04
Not overdue, we're wait for @danieldoglas 's review

**Comment by miljakljajic** [comment] 2024-08-21 09:57
Deployed to prod two days ago. Will update the payment schedule header.

**Comment by eh2077** [comment] 2024-08-21 14:49
@daledah Can you take a look at this comment https://github.com/Expensify/App/pull/47028#issuecomment-2294890330 please?

**Comment by miljakljajic** [comment] 2024-08-23 11:07
@daledah please apply to this job too and we'll get you paid

**Comment by eh2077** [comment] 2024-08-27 01:38
> @daledah Can you take a look at this comment https://github.com/Expensify/App/pull/47028#issuecomment-2294890330 please? 

@daledah Friendly bump

**Comment by miljakljajic** [comment] 2024-08-27 11:35
Seems like this one isn't ready to be paid yet

**Comment by miljakljajic** [comment] 2024-09-03 13:18
Offer for @daledah is here: https://www.upwork.com/nx/wm/offer/103795902

**Comment by eh2077** [comment] 2024-09-03 13:28
Hi @miljakljajic, sorry this issue is not ready yet for payment. Because we haven't fully get the expected behaviors. We have active discussions on closed PR

**Comment by miljakljajic** [comment] 2024-09-04 12:07
Don't worry, I have just extended the offer but I will not pay til payment is due. Thank you @eh2077

**Comment by eh2077** [comment] 2024-09-16 15:31
I'll post a summary of our discussions from the closed PR https://github.com/Expensify/App/pull/47028 soon

**Comment by eh2077** [comment] 2024-09-20 13:38
> Did we decide to close without moving forward, or will payment still be due?

@miljakljajic Thanks for checking this. Sorry for the late update, I think it's better to hold it for a while to hear feedback from internal engineering team.

**Comment by eh2077** [comment] 2024-09-20 13:38
Here's the summary of the status on this issue
1. We have a PR https://github.com/Expensify/App/pull/47028 merged but only managed to remove the `record audio` option
2. On mobile Chrome, we still have the `Camera Camcorder` option - the  **_record video_** option
<details>
  <summary> The screenshot of what's look like after the PR merged </summary>
  
  <img src="https://github.com/user-attachments/assets/12043ce6-89fb-48f6-a567-2687adf61b6d" width="300">
</details>

---

@daledah and I spent sometime to find a solution to remove the `Camera Camcorder` option but we ended up a conclusion that, _**on mobile Chrome, we can't control options to show on the attachment picker modal**_. Instead, it's the default behaviour of mobile Browser. There's a demonstration video https://github.com/Expensify/App/pull/47028#issuecomment-2335154502  by @daledah 

See also 

1. https://stackoverflow.com/questions/48503345/how-to-disable-camera-option-for-file-upload-from-mobile-browser
2. https://stackoverflow.com/questions/21523544/html-file-input-control-with-capture-and-accept-attributes-works-wrong

---

That said, I tend to leave the record video option, `Camera Camcorder`, as it is.

@danieldoglas What do you think?

cc @quinthar @daledah

**Comment by danieldoglas** [comment] 2024-09-20 14:15
I see. So, that's more of a limitation on Android, not on our side. If that's not something we can control, I think it's fine to keep it as is. @miljakljajic are you OK with that too?

**Comment by miljakljajic** [comment] 2024-09-20 15:10
I agree - it doesn't look like a bug. Closing. Thank you for investigating!

**Comment by eh2077** [comment] 2024-09-20 15:30
@miljakljajic This should be eligible for payment right? We have worked on a PR https://github.com/Expensify/App/pull/47028 here.

**Comment by danieldoglas** [comment] 2024-09-20 15:54
Yep, this is eligible for payment - we indeed solved the situation with the audio recording.

**Comment by miljakljajic** [comment] 2024-09-24 21:53
Sorry, paid!

**Closed by miljakljajic** 2024-09-24 21:53 UTC
Labels: Reviewing, External, Weekly, Bug
