### ISSUE TITLE
[$250] [Polish] Log in - Leave the login input when the user hits `back` from the password page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11732] opened 2022-10-11 22:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Enter email or phone 
3. Hit continue
4. Hit back

## Expected Result:
When incorrect login is provided and the user goes back leave the login in the input so they can fix their mistake

## Actual Result:
Form is cleared 

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![2022-10-11_10-41-12](https://user-images.githubusercontent.com/43996225/195207642-6492201d-120c-4343-8c21-4f2e1193c49d.png)
![2022-10-11_10-41-18](https://user-images.githubusercontent.com/43996225/195207644-cdd0c3ee-9462-4416-8ee0-52774e87803c.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665520951085549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2022-10-12 04:11
<b>Proposal</b>
This because after press Continue, our code clear the input text in here:
https://github.com/Expensify/App/blob/299f07bfa29c0dd81a6126691aae29e161097baa/src/pages/signin/LoginForm.js#L92

Solution:

```diff
-         if (this.state.login) {
-            this.clearLogin();
-        }
```
Here is the result:
https://user-images.githubusercontent.com/16502320/195248049-0d843642-5bbd-4bfa-b686-af92acd985c8.mov

**Comment by sakluger** [comment] 2022-10-12 19:22
I think this one is worth solving! Passing along to engineering.

**Comment by NikkiWines** [comment] 2022-10-13 10:16
Yep, sounds like nice, quick improvement. Marking external.

**Comment by mananjadhav** [comment] 2022-10-13 10:45
Well the feature request looks okay, but I am in two minds if we should even fix this. 

Nevertheless if we plan to fix this one, we need to ensure that when I do enter the correct login, we have `Not <login>? Go back`. Clicking on which also takes you back to the login page. I am assuming here we do want the login to be cleared.


https://user-images.githubusercontent.com/3069065/195576849-008341f1-4314-410c-acd2-772425862d60.mov

**Comment by marcaaron** [comment] 2022-10-13 17:33
>I am assuming here we do want the login to be cleared

No, that is the opposite of what this issue is proposing. There's no way to tell that you've entered your email correctly or incorrectly. But 9/10 times if the email on that screen is wrong then you are probably off by one character or it's a typo. This change will bring the New app up to parity with the old one (where IMO we have achieved a good UX):

https://user-images.githubusercontent.com/32969087/195665958-e32a77e4-ace6-4103-a5f3-8c217efb112e.mp4

**Comment by marcaaron** [comment] 2022-10-13 17:35
But yes let's update the description maybe so that both of these flows (password or magic sign in page) have the same effect of leaving the email in the input.

**Comment by hungvu193** [comment] 2022-10-13 17:43
> Proposal This because after press Continue, our code clear the input text in here:
> 
> https://github.com/Expensify/App/blob/299f07bfa29c0dd81a6126691aae29e161097baa/src/pages/signin/LoginForm.js#L91-L93
> 
> Solution:
> 
> ```diff
> -         if (this.state.login) {
> -            this.clearLogin();
> -        }
> ```
> 
> Here is the result: https://user-images.githubusercontent.com/16502320/195248049-0d843642-5bbd-4bfa-b686-af92acd985c8.mov

I tested this as well, in both way this solution will leave the email in the input:
https://user-images.githubusercontent.com/16502320/195667349-08573c0b-665d-4609-a34e-ae389d2d192a.mov

**Comment by mananjadhav** [comment] 2022-10-14 07:46
Thanks for the clarification @marcaaron. 

@hungvu193's proposal [here](https://github.com/Expensify/App/issues/11732#issuecomment-1277963871) looks fine to me. @pecanoro All yours.

🎀 👀 🎀 
C+ reviewed

**Comment by vladamx** [comment] 2022-10-14 12:57
@marcaaron @mananjadhav 

Wouldn't it be better if we save login email to async storage so it can survive screen remounts if by any means it gets recycled by the OS during context switching like user receiving a call etc...

Also we could use the value from storage to autofill previously logged-in user if user signs out.

Just not clearing the input is OKish but not really bulletproof

**Comment by pecanoro** [comment] 2022-10-18 19:13
@vladamx It could be an option, but it seems a bit overkill since I am not sure how often that happens, but I don't have a strong opinion. @marcaaron @mananjadhav what do you think?

**Comment by mananjadhav** [comment] 2022-10-18 19:30
> seems a bit overkill since

Agree with you @pecanoro.  I don't think we should retain the login into a persistent storage.

**Comment by hungvu193** [comment] 2022-10-19 06:22
Lemme know when I can create a PR for this issue :)

**Comment by mananjadhav** [comment] 2022-10-20 20:44
Waiting on @pecanoro to assign the job.

**Comment by pecanoro** [comment] 2022-10-21 16:03
@hungvu193 Feel free to apply for the job and work on a PR!

**Comment by hungvu193** [comment] 2022-10-21 16:04
> @hungvu193 Feel free to apply for the job and work on a PR!

can you send me the link of the job please?

**Comment by pecanoro** [comment] 2022-10-21 16:08
@johncschuster Can you send @hungvu193 the link for the Upwork job?

**Comment by johncschuster** [comment] 2022-10-21 16:38
Sure! I'll get that going now.

**Comment by johncschuster** [comment] 2022-10-21 20:43
Sorry for the delay folks. Here's the posting!
https://www.upwork.com/jobs/~0172b47f9e5677177d

@hungvu193, can you apply and let me know when you've done that?

**Comment by hungvu193** [comment] 2022-10-22 01:44
@johncschuster I've just applied

**Comment by johncschuster** [comment] 2022-10-25 19:32
I've accepted your applications, @hungvu193 and @mananjadhav 👍

**Comment by hungvu193** [comment] 2022-10-26 01:08
> I've accepted your applications, @hungvu193 and @mananjadhav 👍 

Cool, I've accepted the ofer

**Comment by mananjadhav** [comment] 2022-11-05 18:55
@johncschuster @pecanoro  This was deployed to production but it's payment date is updated.

**Comment by johncschuster** [comment] 2022-11-07 20:45
For my own notes:
[PR deployed to production](https://github.com/Expensify/App/pull/12062#issuecomment-1303898844) on Nov 4. I'll keep monitoring the PR for regressions until Nov 11. 👍

**Comment by mananjadhav** [comment] 2022-11-14 03:55
@johncschuster Quick bump on the Upwork payment.

**Comment by mananjadhav** [comment] 2022-11-15 17:03
@johncschuster Did you get a chance to look at above comments for payment?

**Comment by johncschuster** [comment] 2022-11-15 17:22
@mananjadhav, yep! I've just paid it out now.

**Comment by mananjadhav** [comment] 2022-11-15 17:24
Thank you so much @johncschuster. @hungvu193 paid as well? then we're good to close this one out too.

**Comment by hungvu193** [comment] 2022-11-15 17:28
Thank you guys, I got paid 😀

**Comment by mananjadhav** [comment] 2022-11-17 08:21
@johncschuster Good to close the issue here?

**Comment by mananjadhav** [comment] 2022-11-23 13:42
@johncschuster Quick bump to close this.

**Comment by JmillsExpensify** [comment] 2022-11-26 22:37
Closing based on the above comments from contributors.

**Closed by JmillsExpensify** 2022-11-26 22:37 UTC
Labels: Reviewing, External, Engineering, Weekly, Improvement
