### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000]  Login - 'sign in here' on expired magic code page redirects to chat which loads infinitely

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22736] opened 2023-07-12 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Copy the magic code link
3. Paste the link in a incognito tab
4. Tap just sign in here

## Expected Result:
User is redirected to LHN after successful login

## Actual Result:
User is redirected to the conversation and the conversation loads infinitely

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/59cb597e-bed6-4ea5-a2ae-2d9605157c2a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8001b7ff3552709</li>
        <li>Upwork Job ID: 1679249935481970688</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-07-12 18:49
I'm not able to follow these steps -asking for some guidance from QA - https://expensify.slack.com/archives/C9YU7BX5M/p1689187723167809

**Comment by Christinadobrzyn** [comment] 2023-07-12 22:02
I can't reproduce through Browserstack but it's been tested with QA so moving forward

**Comment by Christinadobrzyn** [comment] 2023-07-14 17:15
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. At this time, we're receiving and reviewing propsoals.

**Comment by maddylewis** [comment] 2023-07-18 15:32
i can update the title to `Login - 'sign in here' on a magic code redirects to a report instead of LHN(home) screen` if we think that makes more sense 👍 
https://github.com/Expensify/App/issues/22736#issuecomment-1638462769

**Comment by maddylewis** [comment] 2023-07-21 18:52
asked about this here - https://expensify.slack.com/archives/C02NK2DQWUX/p1689965537714879

**Comment by maddylewis** [comment] 2023-07-24 18:15
shoot, im not able to test/repro this for the same reason @Christinadobrzyn could not - I don't think Browserstack has incognito capabilities. 

if you think you've pinpointed the bug @0xmiroslav and a contributor can reproduce, i think we're good to move forward with reviewing proposals for a fix for that.

**Comment by maddylewis** [comment] 2023-07-31 16:45
@0xmiroslav - will you take a look at @tienifr's latest proposal when you have a chance? thanks!

**Comment by Christinadobrzyn** [comment] 2023-07-31 17:40
Back from ooo - going to take this back, thanks @maddylewis! 

@arosiclair how do you feel about @0xmiroslav review here? https://github.com/Expensify/App/issues/22736#issuecomment-1658762567

**Comment by Christinadobrzyn** [comment] 2023-08-11 20:46
@0xmiroslav will we need a regression test for this?

Payouts due:

Issue Reporter: $250 NA
Contributor: $1000 + $500 bonus @tienifr 
Contributor+:  $1000 + 500 bonus @0xmiroslav 

Eligible for 50% #urgency bonus? Yes - https://github.com/Expensify/App/issues/22736#issuecomment-1666029699

Upwork job is [here](https://www.upwork.com/jobs/~01d8001b7ff3552709)
Internal job posting- https://www.upwork.com/ab/applicants/1679249935481970688/job-details

**Comment by maddylewis** [comment] 2023-08-15 17:14
moving to daily since payment is due tomorrow. i can process payments, xtina. thank you!

**Comment by maddylewis** [comment] 2023-08-17 18:53
paid @tienifr 👍 

im a bit confused on how we're paying @0xmiroslav. I've asked internally and will follow up once payment is processed.

**Comment by maddylewis** [comment] 2023-08-21 13:11
everyone is paid https://github.com/Expensify/App/issues/22736#issuecomment-1675386260

**Closed by maddylewis** 2023-08-21 13:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
