### ISSUE TITLE
Web - Profile - App is crashing when hit the Enter key after searching the user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8996] opened 2022-05-13 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go https://staging.new.expensify.com/
2. Log in with any account
3. On Search start typing any NEW user you haven't chat with before
4. Hit Enter Key

## Expected Result:
App is not crashed after use the Enter key for searched user

## Actual Result:
App is crashed after use the Enter key for searched user

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.60

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/168346137-715eab9f-34b7-4631-8fe2-7de16b5c5bd6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tylerkaraszewski** [comment] 2022-05-13 18:44
I can't reproduce this.

**Comment by mvtglobally** [comment] 2022-05-13 18:47
@tylerkaraszewski, 
Did you use the physical keyboard after searching and then hitting ENTER ? This is consistently repro for us.

**Comment by tylerkaraszewski** [comment] 2022-05-13 18:57
It's not doing it for me:

https://user-images.githubusercontent.com/705000/168356458-9d84def3-da2d-47b6-954a-800de19bd9b1.mov

**Comment by Santhosh-Sellavel** [comment] 2022-05-13 19:04
@tylerkaraszewski Issue is able to reproduce, type an email (a new user) which whom you never had chat, and press enter.

Since its a deployer block I spun a PR

**Comment by tylerkaraszewski** [comment] 2022-05-13 19:06
Yes, with "email (a new user) which whom you never had chat" it is reproducible.

The reproduction steps say: "On Search start typing any user" which does not cause the problem.

**Comment by isagoico** [comment] 2022-05-13 19:06
@tylerkaraszewski Able to reproduce the issue, here's the JS error in consoles
![image](https://user-images.githubusercontent.com/44479856/168365892-05f57e44-e4c3-4264-a487-16d4ff33b4fa.png)

**Comment by mvtglobally** [comment] 2022-05-13 19:07
@tylerkaraszewski, I  didnt realize it has to be a new user as we often use new accounts. I fixed the steps

**Comment by roryabraham** [comment] 2022-05-15 19:54
I believe this is fixed now, closing it out.

**Closed by roryabraham** 2022-05-15 19:54 UTC
Labels: DeployBlockerCash, External, Engineering, Daily

**Comment by Santhosh-Sellavel** [comment] 2022-05-16 17:59
@NicMendonca Ping for Upwork, fixing the deploy blocker!

**Comment by NicMendonca** [comment] 2022-05-19 11:49
@Santhosh-Sellavel -- https://www.upwork.com/jobs/~01746018cccbba15e0

**Comment by Santhosh-Sellavel** [comment] 2022-05-19 14:14
Thanks @NicMendonca
