### ISSUE TITLE
[HOLD for payment 2022-11-29] [$250] An emoji is entered multiple times on repeated presses without closing the emoji picker - reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12691] opened 2022-11-11 22:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open emoji keyboard in any chat
2. Press an emoji multiple times

Note: Notice the emoji picker is not immediately closed after the first emojis is selected (pressed)

## Expected Result:
The emoji picker should be closed immediately after the first emoji is selected. 
## Actual Result: 
The emoji picker takes some time to close and captures multiple presses, adding them multiple times in the compose box
## Workaround:
None 
## Platform:

Where is this issue occurring?

- Android
- Desktop

**Version Number:** 1.2.27-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/201441185-ea2e9384-6b65-46a2-928a-a4a307938cfe.mp4

https://user-images.githubusercontent.com/43996225/201441220-9ee4ca2b-160d-40a4-9a78-ce6fb5e2f118.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1668023958715039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2022-11-14 17:44
### Proposal
```diff
diff --git a/src/components/EmojiPicker/EmojiPicker.js b/src/components/EmojiPicker/EmojiPicker.js
index c379d9f83..75451cb47 100644
--- a/src/components/EmojiPicker/EmojiPicker.js
+++ b/src/components/EmojiPicker/EmojiPicker.js
@@ -56,6 +56,9 @@ class EmojiPicker extends React.Component {
      * @param {String} emoji
      */
     selectEmoji(emoji) {
+        if (!this.emojiPopoverAnchor) {
+            return;
+        }
         this.hideEmojiPicker();
         if (_.isFunction(this.onEmojiSelected)) {
             this.onEmojiSelected(emoji);
```

### Details
Since we set emojiPopoverAnchor prop to null right on the hide function we can rely on it to not select another emoji.

**Comment by mollfpr** [comment] 2022-11-14 17:53
@s77rt [proposal's](https://github.com/Expensify/App/issues/12691#issuecomment-1314141991) looks good to me!
The next pressed emoji will not be selected while the popover will hide.

cc @jasperhuangg 
🎀 👀 🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2022-11-14 17:57
Also CCing @stitesExpensify since you're working on the linked tracking issue for emojis.

**Comment by jasperhuangg** [comment] 2022-11-15 19:22
@s77rt on a roll lately, assigned!

**Comment by s77rt** [comment] 2022-11-15 20:13
@jasperhuangg I have PR waiting to be merged #12746
Should I wait till then to make a new PR? (and do i need to be unassigned then assigned again or it's okay staying assigned)

**Comment by mollfpr** [comment] 2022-11-15 20:18
@s77rt You should be good to go after being assigned and never unassign yourself if you are still hired.

**Comment by s77rt** [comment] 2022-11-15 21:49
Applied in Upwork.
[PR](https://github.com/Expensify/App/pull/12755) is ready.

**Comment by JmillsExpensify** [comment] 2022-11-17 04:54
Hired @s77rt via Upwork and offer sent to @mollfpr as well. Going to prioritize the BZ checklist between here and the PR merging.

**Comment by mollfpr** [comment] 2022-11-17 04:58
@JmillsExpensify is the PR timeline eligible for the bonus?

**Comment by JmillsExpensify** [comment] 2022-11-17 04:59
Great call. It is, so can you update the price before accepting?

**Comment by mollfpr** [comment] 2022-11-17 05:02
Yup, I just update the price for the Upwork proposal, thanks!

**Comment by s77rt** [comment] 2022-11-17 09:40
@JmillsExpensify I think am eligible for the bonus as well, right?

**Comment by huzaifa-99** [comment] 2022-11-17 11:12
@JmillsExpensify am I eligible for the reporting bonus?

**Comment by jasperhuangg** [comment] 2022-11-17 20:05
> The PR that introduced the bug has been identified. Link to the PR:

This wasn't as much a regression as much as a bug that was always present, but simply wasn't uncovered since it's somewhat of an edge case. Therefore, I'm not linking a PR for this.

> A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I'm also not really too sure what we could have done differently since this is an edge case, I honestly wouldn't have thought to rapidly tap the emoji picker when testing it. This problem is pretty specific to the implementation of this component, so it's difficult to come up with an overarching statement on what we could do differently for next time.

**Comment by jasperhuangg** [comment] 2022-11-17 22:04
The PR for this is on staging! https://github.com/Expensify/App/pull/12755

**Comment by JmillsExpensify** [comment] 2022-11-18 08:51
@mollfpr Great thanks.

@s77rt Yes, I've updated your offer.

@huzaifa-99 Yes, the reporting bonus is $250. Can you apply to the [Upwork job](https://www.upwork.com/jobs/~01447aa76a5e810018) please?

**Comment by huzaifa-99** [comment] 2022-11-18 09:59
@JmillsExpensify Applied, thanks.

**Comment by jasperhuangg** [comment] 2022-11-21 14:59
Hey Melvin, hope ya had a great weekend!

Still waiting for the PR to go out to prod, not overdue.

**Comment by JmillsExpensify** [comment] 2022-11-22 05:36
As for wait for the PR to hit production and the regression period to start, noting that I do need to circle back on the BZ checklist. I'll plan on that for this week.

**Comment by JmillsExpensify** [comment] 2022-11-29 04:59
Ok, circling back on the regression test and related payment todos now that we are nearing the end of the regression period.

**Comment by JmillsExpensify** [comment] 2022-11-29 05:08
Alright, the regression test has been added. We are only an hour away from the 29th, so I'm going to go ahead and issue payments and then close out this issue.

**Comment by JmillsExpensify** [comment] 2022-11-29 05:11
All contributors paid out. Closing issue.

**Closed by JmillsExpensify** 2022-11-29 05:11 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
