### ISSUE TITLE
Messages are duplicating sometimes 

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8708] opened 2022-04-20 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Receive a DM
2. Leave that DM for a moment, and come back (i.e. click into another DM)
3. See the DM duplicated
4. Type a message, hit send and close lid immediately  

Steps 2
1. Jump into any DM
2. Send 1-2 messages
3. Close laptop lid right immediately sending those messages.
4. Count 3 seconds, and then re-opened the laptop lid.
5. See dupes

## Expected Result:
Messages should not be duplicated 

## Actual Result:
Messages are duplicate 

## Workaround:
unknown 
## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.1.55-0
**Reproducible in staging?:** Y
**Reproducible in production?:** need repro
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="818" alt="image - 2022-04-20T160806 051" src="https://user-images.githubusercontent.com/43995119/164314187-0ee0d7c5-1bba-4b5e-ac81-707adf67be98.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @michaelhaxhiu 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1650039849909709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2022-04-20 20:42
Looks like we're creating multiple actions even though we have a clientID that can help us determine if we've already created one
```
  created = 2022-04-20 19:45:52
 reportID = 64889286
accountID = 3000672
   action = ADDCOMMENT
  message = {"html":"123","clientID":"1650483952607338"}

  created = 2022-04-20 19:45:54
 reportID = 64889286
accountID = 3000672
   action = ADDCOMMENT
  message = {"html":"123","clientID":"1650483952607338"}
```

**Comment by cead22** [comment] 2022-04-20 20:43
If we solve that in the backend, which seems like it should be an easy fix, it has to be done internally

**Comment by cead22** [comment] 2022-04-20 20:44
There were two requests made for that comment it seems https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=blob%3A%22Processing%20'Report_AddComment'%22%20AND%20blob%3A%221650483952607338%22%20AND%20timestamp%3A%5B2022-04-20T00%3A00%20TO%202022-04-21T23%3A59%5D

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/165133/164319547-8d5e53fe-57bf-49b4-ae74-9f0f4c5b2b60.png">

**Comment by robertjchen** [comment] 2022-04-21 14:04
Got it, so it sounds like we would check the clientID of the new, incoming comment on the backend, to make sure it's unique within the past, say, 5 recent actions on that chat report. We would reject the `Report_AddComment` command if that's not the case.

I think this would be a great FistPick, going to raise it in Slack 👍

**Comment by michaelhaxhiu** [comment] 2022-04-21 14:12
@robertjchen I love first picks, but isn't a pre-req that this should be easily reproducible? Just wanted to check on that aspect as we can't reproduce this in a steadfast manner

**Comment by robertjchen** [comment] 2022-04-21 14:20
Great point! It might not be reproducible consistently with the steps above, but it could be easily simulated locally for testing.

**Comment by cead22** [comment] 2022-04-21 16:52
> to make sure it's unique within the past, say, 5 recent actions on that chat report. We would reject the `Report_AddComment` command if that's not the case.

At first I thought they should all be unique but this made me realize there can be collisions. That said, would it make sense to make sure the clientID isn't repeated in the same reportID, instead of in the same reportID and the last 5 actions in that reportID? In any case this may be a premature optimization, but just something I thought about when I read this

**Comment by marcaaron** [comment] 2022-04-21 22:13
Can easily reproduce this by following the steps here... 

https://expensify.slack.com/archives/C02HWMSMZEC/p1649356192074339?thread_ts=1649352308.973269&cid=C02HWMSMZEC

**Comment by michaelhaxhiu** [comment] 2022-04-25 18:17
such a sweet add, thanks @marcaaron !!

**Comment by neil-marcellini** [comment] 2022-04-26 17:13
My plan is to call `report->getActionList()` and then create a set of clientIDs at the beginning of [ReportAPI::addComment](https://github.com/Expensify/Web-Expensify/blob/4c94d9f2e2553f94affa9defc916baa23f1329a5/lib/ReportAPI.php#L320). If the clientID of the incoming message exists in the set then I will reject the `Report_AddComment` command.

I think it might be best to only check against a limited number of past actions since reports can have an unlimited number of actions, but I'm not sure how to determine what that limit should be.

Does that sound like a good approach?

**Comment by marcaaron** [comment] 2022-04-26 17:54
It sounds like we want to: 

- prevent duplicates by checking the clientIDs of any report actions on a report 
- prevent losing data because we somehow have an identical clientID for 2 distinct comments

I might be confused about which case we are discussing though WRT those comments. 

>reject the Report_AddComment command

Is there any benefit to rejecting this vs. just having it return `jsonCode: 200` with the `Report_AddComment` response? This would indicate that the comment was successfully created at some point and we do not need to create it again. But the front end wouldn't necessarily need to "handle" this (though agree `Log::hmm()` or something would be good so it's more obvious it happened).

How do we tell between a collision (two distinct comments) vs. a true duplicate request (same comment and clientID)?

>I think it might be best to only check against a limited number of past actions since reports can have an unlimited number of actions, but I'm not sure how to determine what that limit should be.

If we are talking about preventing duplicates then I think we always need to check _all_ the actions e.g. we might have some really old persisted action that is finally sending from a client that has not logged in for some time. Meanwhile many more comments could have been left via other clients so checking the last 5 would not be good enough.

**Comment by neil-marcellini** [comment] 2022-04-26 18:04
> Is there any benefit to rejecting this vs. just having it return jsonCode: 200 with the Report_AddComment response?

That sounds like a good idea, I'm happy to do that.

> If we are talking about preventing duplicates then I think we always need to check all the actions e.g. we might have some really old persisted action that is finally sending from a client that has not logged in for some time.

Makes sense 👍

**Comment by cead22** [comment] 2022-04-26 18:14
> @cead22 Could we approximate this by looking at the message content + clientID?

Yeah I vote we do nothing.

> If we are talking about preventing duplicates then I think we always need to check _all_ the actions e.g. we might have some really old persisted action that is finally sending from a client that has not logged in for some time

I think this is also an edge case that we don't need to optimize for -- I think it's better to drop a really old message which likely isn't relevant anymore, than create a duplicate in this case. Regardless, I think we can check all the report actions, but this could get slow on really channels with a lot of messages

**Comment by neil-marcellini** [comment] 2022-04-29 00:16
I just added an automated test for adding a duplicate chat. I have a question about how to access the response in the test, and I also still need to do the query timing.

**Comment by neil-marcellini** [comment] 2022-05-06 20:53
The PR has been merged and deployed to production so I'm going to close this. Maybe i didn't it close automatically because the issue is in the App repo?

**Closed by neil-marcellini** 2022-05-06 20:53 UTC
Labels: Reviewing, Engineering, Daily, FirstPick
