### ISSUE TITLE
[$1000] Empty chat header when starting a chat with any email containing captial letter

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21459] opened 2023-06-23 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to the app and click the `Search` icon in the LHN.
2. Type an email that is not in your contact list and make sure that the email contains an uppercase letter ie [aH@asd.com](mailto:aH@asd.com).
3. Select this contact.
## Expected Result: 
The chat header should show the email and not be empty.
## Actual Result: 
Chat header is empty

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="955" alt="Screenshot (374)" src="https://github.com/Expensify/App/assets/43996225/e4dccca7-c8c3-4c54-be5a-031744343c21">

https://github.com/Expensify/App/assets/43996225/1b90542d-36a9-4f0d-8bb7-5be5e4872131

**Expensify/Expensify Issue URL:**
**Issue reported by:** @allroundexperts 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687051826855649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0139d93d50b04a4799</li>
        <li>Upwork Job ID: 1673367434378838016</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-23 22:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty chat header appears when starting with a chat with any email containing capital letter

### What is the root cause of that problem?

Weird message returns when email has capital letter as follows
```
{
  "onyxMethod": "merge",
  "key": "report_6157911605865567",
  "value": {
    "reportID": "6157911605865567",
    "reportName": "Chat Report",
    "type": "chat",
    "chatType": "",
    "ownerEmail": "__fake__",
    "ownerAccountID": 0,
    "policyID": "_FAKE_",
    "participants": [],
    "participantAccountIDs": [],
    "isPinned": false,
    "lastReadTime": null,
    "lastMentionedTime": null,
    "lastReadSequenceNumber": 0,
    "lastVisibleActionCreated": "2023-06-23 21:30:51.301",
    "lastVisibleActionLastModified": "2023-06-23 21:30:51.301",
    "lastMessageText": "",
    "lastActorEmail": "__fake__",
    "lastActorAccountID": 0,
    "notificationPreference": "always",
    "welcomeMessage": "",
    "stateNum": 0,
    "statusNum": 0,
    "oldPolicyName": "",
    "visibility": null,
    "isOwnPolicyExpenseChat": false,
    "lastMessageHtml": "",
    "hasOutstandingIOU": false,
    "policyName": null,
    "hasParentAccess": null,
    "parentReportID": null,
    "parentReportActionID": null,
    "writeCapability": "all"
  }
}
```

As you can see above, empty participants is returned. This makes the report title empty string and shows nothing because of this line
https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/pages/home/HeaderView.js#L158

### What changes do you think we should make in order to solve the problem?

This issue looks like a backend issue but can have a workaround.
We can remove response data with keys staring with `report_` and value with lastReadTime is null(check the above response) before the below line
https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/libs/Middleware/SaveResponseInOnyx.js#L24C120-L24C120

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/71a607ba-9edf-40dd-8bba-629d659907bc


</details>

### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-06-26 16:27
Reproducible, triaging to external

**Comment by sonialiap** [comment] 2023-06-29 16:17
@rushatgabhane we have some proposals, what do you think?

**Comment by s-alves10** [comment] 2023-06-30 21:53
@rushatgabhane 

Yes. First, we received the message with valid `participantAccountIDs`, but please check the later items in the `onyxData` array. It has the report item as well and it has empty array `participantAccountIDs`. So if all of them are merged, `participantAccountIDs` would become an empty array. That's why I suggest to filter out the invalid `onyxData` items.

**Comment by flodnv** [comment] 2023-07-03 15:24
>the OpenReport API returns an empty array for participantAccountIDs

I agree this seems like the root cause and would need a backend fix. 

>we also optimistic store the email with capital letter in personalDetailsList

@Beamanator @puneetlath can you check this out? I think we are about to remove this part of the frontend?

**Comment by Beamanator** [comment] 2023-07-03 15:39
@flodnv 

> >we also optimistic store the email with capital letter in personalDetailsList
>
> @Beamanator @puneetlath can you check this out? I think we are about to remove this part of the frontend? 

We removed `personalDetails`, we're not removing `personalDetailsList`

I think this will require both back & front-end fixes, I can take a look at the backend part tomorrow if you want @puneetlath

**Comment by Beamanator** [comment] 2023-07-06 12:16
Web PR is up - https://github.com/Expensify/Web-Expensify/pull/38069

@rushatgabhane I think we agreed we need to also have an App PR which lowercases emails when storing them in Onyx? Are we ready to review proposals here? Or do we want to wait till the backend PR is on staging?

**Comment by Beamanator** [comment] 2023-07-06 12:29
@s-alves10 by "fixed in the backend" do you mean "allow mixed-case emails everywhere"?

**Comment by s-alves10** [comment] 2023-07-06 12:35
We can do all email comparison in lowercase. I think users should see what they input. Email is not case sensitive and there is no side effects.

**Comment by Beamanator** [comment] 2023-07-06 13:25
Sadly in or backend email is case sensitive 😬  And we expect it to be lowercase...

**Comment by Beamanator** [comment] 2023-07-10 09:17
I put a backend fix in place which is now in staging, but not in production yet - but i still think we need to auto-lowercase the optimistic emails we set when creating the new chat

**Comment by rushatgabhane** [comment] 2023-07-13 05:29
Can we get new proposals please. Let's fix this close to where we're creating an optimistic report. 
I don't like the solutions proposing a fix in search page.

**Comment by flodnv** [comment] 2023-07-17 09:09
@sonialiap can you confirm it's fixed and if so, close the issue?

**Comment by sonialiap** [comment] 2023-07-17 12:50
Tested, confirming that this issue has been fixed

<img width="1603" alt="image" src="https://github.com/Expensify/App/assets/17131195/f1d86942-8297-49b2-9f10-4feece0f9d12">

**Closed by sonialiap** 2023-07-17 12:50 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
