### ISSUE TITLE
[HOLD for payment 2024-08-29] [CVP] [$250] Default Selected Tab is Scan when submitting an expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46916] opened 2024-08-06 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @davidcardoza 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1722959330691129

## Action Performed:

1. Navigate to the app on either the mobile or web platform.
2. Open Global create > Tap submit expense

## Expected Result:
The default selected option should be set to "Scan."

- The issue was identified as a regression via this [GH PR](https://github.com/Expensify/App/pull/26984).
- We changed the default selectedTab to Scan during the Saastr activation.
- It appears that this file no longer exists, likely broken during a TypeScript migration.

## Actual Result:
The default selected option is set to "Manual."
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8e002e5a-c4bb-42d6-bf3f-59b0ed0538d5

![Snip - (13) New Expensify - Google Chrome](https://github.com/user-attachments/assets/537101f6-bb36-4fb4-bd9f-1170fa3099e1)

- The issue was identified as a regression via this [GH PR](https://github.com/Expensify/App/pull/26984).
- We changed the default selectedTab to Scan during the Saastr activation.
- It appears that this file no longer exists, likely broken during a TypeScript migration.

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e779507128f89c4</li>
        <li>Upwork Job ID: 1821296903042091088</li>
        <li>Last Price Increase: 2024-08-07</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 103493720</li>
<li>dominictb | Contributor | 103493721</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by BhuvaneshPatil** [comment] 2024-08-06 19:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default selected tab is not Scan when submitting scan

### What is the root cause of that problem?
We are not passing default value of `iouType` prop.

https://github.com/Expensify/App/blob/07008547603aa476f5e06206977a7d5daf8ad7c0/src/pages/iou/request/IOURequestStartPage.tsx#L33-L38

### What changes do you think we should make in order to solve the problem?
We shall add default prop as scan.

```ts
function IOURequestStartPage({
    route,
    route: {
        params: { iouType = SCREENS.MONEY_REQUEST.STEP_SCAN, reportID },
    },
}: IOURequestStartPageProps) {
```


https://github.com/user-attachments/assets/f4a384e7-2056-4df0-b29d-dcbaca834bb1

### What alternative solutions did you explore? (Optional)

**Comment by brunovjk** [comment] 2024-08-08 17:37
@trjExpensify, could you clarify one thing please? the `'Scan'` tab should be the default _across the entire app_, or just when _submitting an expense_? Thanks

**Comment by trjExpensify** [comment] 2024-08-08 18:37
What do you mean by "entire app"? 

>or just when submitting an expense?

also, just to clarify as well, it's only the default for the first time you use `Submit expense`. Thereafter, your choice is remembered, as it is today. The bug is just that the default for the first time using `Submit expense` is `Manual` instead of `Scan`.

**Comment by brunovjk** [comment] 2024-08-09 22:01
@trjExpensify, sorry for any confusion in my poor choose of words hehe Im lucky you understood correctly, and thanks for clarifying. Given this, the [proposal](https://github.com/Expensify/App/issues/46916#issuecomment-2272561252) RCA seems accurate to me; `selectedTab` is indeed `undefined` initially, causing the default to be `Manual` due to the `0` index. However, I've tested the proposed solution and noticed it briefly displays the `Manual` tab before switching to `Scan`. 

https://github.com/user-attachments/assets/5284bb53-84b1-4123-994f-4f32dbcdc88f


@dominictb Do you have a branch with this change, or perhaps an alternative approach? Thanks!

**Comment by trjExpensify** [comment] 2024-08-09 22:18
No worries! If it's helpful, this is the PR where we added this initially before the TypeScript migration: https://github.com/Expensify/App/pull/26984

**Comment by BhuvaneshPatil** [comment] 2024-08-10 03:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When submitting an expense not opening selected tab but manual everytime.

### What is the root cause of that problem?
To get previously selected tab we use onyx data - 

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/libs/Navigation/OnyxTabNavigator.tsx#L69-L73

But in case of it's not present in Onyx, the value `initialRouteName` is undefined. As it's undefined we use `0` index type as request type.

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/libs/Navigation/OnyxTabNavigator.tsx#L50-L57

### What changes do you think we should make in order to solve the problem?
I am assuming we want this action is performed from FAB's `Submit Expense` action and I have tailored my solution for that.

1. When we click on `Submit Expense` button, we call `IOU.startMoneyRequest()`. This function also takes conditional parameter for it, `requestType` - 

https://github.com/Expensify/App/blob/e6546d658b17a8dc94aee6e8ceba1eb988397053/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L395-L407

3. We can leverage this param for this case. We will add `selectedRequestTab` (or some other name) to onyx prop for `FloatingActionButtonAndPopover` component. That will give us value for selected tab from onyx. Its key will be - 
```ts
   selectedRequestTab: {
        key: `${ONYXKEYS.COLLECTION.SELECTED_TAB}${CONST.TAB.IOU_REQUEST_TYPE}`
    }
```
and based on value of this we will pass new argument to mentioned function - 
```tsx
onSelected: () =>
                            interceptAnonymousUser(() =>
                                IOU.startMoneyRequest(
                                    CONST.IOU.TYPE.SUBMIT,
                                    // When starting to create an expense from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                                    // for all of the routes in the creation flow.
                                    ReportUtils.generateReportID(),
                                    selectedRequestTab ? undefined : 'scan',
                                ),
                            ),
```


### What alternative solutions did you explore? (Optional)
Second option is to make changes `OnyxTabNavigator`.

We remove `selectedTab` from props and HOC of onyx and use `useOnyx` instead.

As this component is used at some other places as well, we can add check of `id` to be `CONST.TAB.IOU_REQUEST_TYPE` and conditionally return 'scan'

```tsx
const [selectedTab] = useOnyx(`${ONYXKEYS.COLLECTION.SELECTED_TAB}${id}`, {
    selector: (value) => {
        if (value) {
            return value;
        }
        return 'scan';
    },
});

```

This will work as expected without that lag where it shows manual for sometime.

https://github.com/user-attachments/assets/f50c9003-1831-4b1d-96e5-3222758c66db

**Comment by BhuvaneshPatil** [comment] 2024-08-10 05:25
@dominictb 

About re-submitting the proposal, I mis-understood the problem during submitting that proposal, But after [comment](https://github.com/Expensify/App/issues/46916#issuecomment-2276433479) that it should open what previously selected, I deleted my proposal.

About lag, that is mentioned in [comment](https://github.com/Expensify/App/issues/46916#issuecomment-2278807830) I didn't notice that in my solution. I am not implying anything. Let @brunovjk Test my solution as well. Thanks

**Comment by brunovjk** [comment] 2024-08-10 23:15
> @brunovjk I cannot reproduce [bug](https://github.com/Expensify/App/issues/46916#issuecomment-2278807830) with my solution. Can you give me the test steps?

@dominictb Thank you for the branch. I tested it and observed the same result:
1. **Log in with a new account.**
2. Click on the `global FAB `> `Submit Expense`.
3. Verify that the default tab is indeed `Scan`, but it briefly switches to `Manual` before returning to `Scan`.

https://github.com/user-attachments/assets/444f8e46-a6bd-4862-9f54-556676269d91

**Comment by brunovjk** [comment] 2024-08-11 00:45
Thank you very much for the proposals, @dominictb and @BhuvaneshPatil. However, it seems that our RCA is not entirely accurate. I’ve attempted several approaches to set a default value for `selectedTab`, but I consistently see `manual` flash briefly before it settles. I experimented with different types, similar to the approach in the old PR mentioned [here](https://github.com/Expensify/App/issues/46916#issuecomment-2278821443), and also considered cleaning up `OnyxTabNavigator`, where we have two `selectedTab` type keys there that could potentially use `useOnyx`,
https://github.com/Expensify/App/blob/93dc1c91437ea8cb9bd48a2a65f395e6da3c678b/src/libs/Navigation/OnyxTabNavigator.tsx#L16-L25
but unfortunately, this did not resolve the issue. I suggest we further research and investigate the root cause. Let’s Smash this bug! :D

**Comment by BhuvaneshPatil** [comment] 2024-08-11 00:58
@dominictb Yes on two pages we use onyx key to set default tab - new chat/room page and submit expense step.

Did you try the approach mentioned in my [proposal](https://github.com/Expensify/App/issues/46916#issuecomment-2278960569)?

**Comment by BhuvaneshPatil** [comment] 2024-08-11 00:59
@dominictb I am not sure about desktop app or IOS, but you can follow the steps similar to attached video in my proposal

**Comment by brunovjk** [comment] 2024-08-11 01:04
> @brunovjk Yes on two pages we use onyx key to set default tab - new chat/room page and submit expense step.
> 
> Did you try the approach mentioned in my [proposal](https://github.com/Expensify/App/issues/46916#issuecomment-2278960569)?

Yes @BhuvaneshPatil , and I get the same behavior as the @dominictb solution, I'm starting to think it's something on my side. Tomorrow I will come back and test your proposals further, if I continue to have the same problem I will tag an intern to test it. Thank you very much :D

**Comment by brunovjk** [comment] 2024-08-12 14:43
After further investigation, I identified a few issues we should address:

1. Replace `withOnyx` with `useOnyx` in `src/libs/Navigation/OnyxTabNavigator.tsx` and create a second variable to handle the `selectedTab` from Onyx separately from the _"default"_ `selectedTab` passed as a component prop.
2. In some point after TypeScript migration, we lost the [default tab being passed](https://github.com/Expensify/App/pull/26984) to `src/pages/iou/request/IOURequestStartPage.tsx`.

I believe we can proceed with @dominictb's [proposal](https://github.com/Expensify/App/issues/46916#issuecomment-2272561252). However, I suggest we tweak the PR slightly, such as using `CONST.TAB_REQUEST.SCAN` instead of the string `"scan"`. We can fine-tune these details in the there.

Thank you for the proposal @BhuvaneshPatil. Both proposals are very similar, but given that dominictb posted first, I think we can proceed with their solution.

🎀👀🎀 C+ reviewed

**Comment by mountiny** [comment] 2024-08-12 15:06
+1 to using useOnyx where we can

**Comment by brunovjk** [comment] 2024-08-15 18:24
PR under review

**Comment by brunovjk** [comment] 2024-08-21 12:06
[PR](https://github.com/Expensify/App/pull/47310) going through deploy checklist: https://github.com/Expensify/App/issues/47760

**Comment by brunovjk** [comment] 2024-08-26 11:37
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. 

**Regression Test Proposal**
  - Login to a new account (Or clear the Onyx state in the troubleshooting settings)
  - Navigate to the app on either the mobile or web platform.
  - Open Global create > Tap submit expense
  - Verify that the default selected tab is `Scan`
  - Do we agree 👍 or 👎

**Comment by trjExpensify** [comment] 2024-08-29 23:22
👋 Not to nitpick, but pretty sure there must be a PR that caused this regression because it was working when we introduced it for SaaStr. Equally, "N/A" with no other context isn't overly helpful to convey your thinking on why something in the checklist is "not applicable".

**Comment by brunovjk** [comment] 2024-08-29 23:35
> 👋 Not to nitpick, but pretty sure there must be a PR that caused this regression because it was working when we introduced it for SaaStr.

Not nitpicking at all, I appreciate the feedback and apologize for the carelessness. I will investigate and find the PR

**Comment by brunovjk** [comment] 2024-08-30 12:48
Hi @trjExpensify, I've updated the checklist. Could you please take a look and let me know if everything looks good now?
Additionally, I've also updated the checklist for another [issue](https://github.com/Expensify/App/issues/46768#issuecomment-2309997414) with the same payment due date, but the BZ member appears to be OOO. If appropriate, could you review that one as well and process the payment if everything is in order? Thank you!

**Comment by trjExpensify** [comment] 2024-09-02 19:21
Excellent, thanks for that! 

Payment summary as follows:

- $250 to @brunovjk for the C+ review
- $250 to @dominictb for the fix

Paid you both, closing!

**Closed by trjExpensify** 2024-09-02 19:21 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
