### ISSUE TITLE
[HOLD] IOU - Missing Hold request, Replace and Delete receipt option when there is one IOU request

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39491] opened 2024-04-03 12:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Go to 1:1 DM with user that has no unsettled IOU.
3. Create a manual request with receipt.
4. Click on the IOU preview.
5. Click 3-dot menu.

## Expected Result:
Hold request option will be present.

## Actual Result:
Hold request option is not present.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/8818b21e-5e30-416f-8d7c-bfbea6ff46e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-04-03 13:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold request, Replace and Delete receipt option are missing when there is only one IOU request.

### What is the root cause of that problem?
We don't add hold or uphold option into three-dot menu items of `MoneyReportHeader`

https://github.com/Expensify/App/blob/ebc8de8229fa700e5a7d08f4589db934a79d4f1d/src/components/MoneyReportHeader.tsx#L164

For three-dot in receipt, this is dupe of https://github.com/Expensify/App/issues/39436#issuecomment-2033854684
### What changes do you think we should make in order to solve the problem?
We should use the same approach in `MoneyRequestHeader` to add `hold` or `unhold` option to three-dot menu item.

https://github.com/Expensify/App/blob/ebc8de8229fa700e5a7d08f4589db934a79d4f1d/src/components/MoneyRequestHeader.tsx#L125

https://github.com/Expensify/App/blob/ebc8de8229fa700e5a7d08f4589db934a79d4f1d/src/components/MoneyRequestHeader.tsx#L118

https://github.com/Expensify/App/blob/ebc8de8229fa700e5a7d08f4589db934a79d4f1d/src/components/MoneyReportHeader.tsx#L164

### What alternative solutions did you explore? (Optional)
NA

**Comment by izarutskaya** [comment] 2024-04-03 15:20
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-03 15:20
We think this issue might be related to the #collect project.

**Comment by arosiclair** [comment] 2024-04-03 15:54
I wouldn't expect `Hold request` to be in the 3-dot menu for the receipt image. I _would_ expect `Replace` and `Delete` though. If we are going to address `Replace` and `Delete` in https://github.com/Expensify/App/issues/39436, then I think we can close this out.

**Comment by kbecciv** [comment] 2024-04-04 21:22
Reopening the issue for a second chance. It seems to occur only when there is a single request.

https://github.com/Expensify/App/assets/93399543/7cc5acd7-219a-4b0b-8f88-e05a555c6d29

**Comment by arosiclair** [comment] 2024-04-08 12:58
> Reopening the issue for a second chance. It seems to occur only when there is a single request.

This seems to be for the three dot menu on the expense. I'm not sure if that behavior is expected or not I'll ask internally

**Comment by arosiclair** [comment] 2024-04-09 14:55
Discussion about this is ongoing [here](https://expensify.slack.com/archives/C036QM0SLJK/p1712581226991889) and [here](https://expensify.slack.com/archives/C05RECHFBEW/p1712601251249849?thread_ts=1712113359.149339&cid=C05RECHFBEW). I'm gonna put a hold on this since there's no UI to show which expenses are held.

**Comment by arosiclair** [comment] 2024-04-12 17:48
Unassigning since there's no more action to take for now

**Comment by stephanieelliott** [comment] 2024-04-15 21:51
Moving to Weekly while we're on hold

**Comment by stephanieelliott** [comment] 2024-05-03 23:25
Still held

**Comment by stephanieelliott** [comment] 2024-05-16 19:14
> I'm gonna put a hold on this since there's no UI to show which expenses are held.

Still held

**Comment by stephanieelliott** [comment] 2024-05-25 01:22
Still holding

**Comment by stephanieelliott** [comment] 2024-06-04 00:16
We have a design for the UI pattern now, this scenario has been incorporated into the design: https://github.com/Expensify/App/issues/39989

**Closed by stephanieelliott** 2024-06-04 00:16 UTC
Labels: Weekly, Overdue, Bug
