### ISSUE TITLE
[HOLD for payment 2024-03-26] [HIGH] [$500] [Mentions] Cannot confirm mention via clicking or hitting the enter key

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#38358] opened 2024-03-14 21:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.51-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dylanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1710448753252709

## Action Performed:
1. Head to any room
2. Thread any comment in the room
3. Mention any user in the thread who hasn't commented in it

## Expected Result:
The mention is selected, auto-filled, and the hover menu disappears

## Actual Result:
The mention flickers and doesn't complete. On prod, it updates the handle, but still flickers and doesn't complete.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/60117248/3bbec873-de25-407e-be3f-8e74041ce189

https://github.com/Expensify/App/assets/60117248/f1e397d3-38b6-4665-92cb-f4efac6322f9

https://github.com/Expensify/App/assets/60117248/bfcf6b3a-e40e-4a7b-aee3-2ab26830a9f5

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01072b12ec0438630b</li>
        <li>Upwork Job ID: 1768384067744870400</li>
        <li>Last Price Increase: 2024-03-14</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by situchan** [comment] 2024-03-14 21:11
This looks quite similar to https://github.com/Expensify/App/issues/32280.
Not sure @koko57's [PR](https://github.com/Expensify/App/pull/37262) might cover this case as well.

**Comment by quinthar** [comment] 2024-03-16 03:57
Let's definitely do a root cause analysis to figure out where this regression came from, and how it slipped through our testing.

**Comment by quinthar** [comment] 2024-03-16 23:47
@getusha can you give an ETA for when you'll be able to fix this?

**Comment by getusha** [comment] 2024-03-17 07:17
@quinthar will review the PR in 2 hours https://github.com/Expensify/App/pull/38361

**Comment by allroundexperts** [comment] 2024-03-17 12:04
> Let's definitely do a root cause analysis to figure out where this regression came from, and how it slipped through our testing.

This came up when we added the [shortened private domain mentions feature](https://github.com/Expensify/App/pull/36697). In our code [here](https://github.com/Expensify/App/blob/main/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L167), we had a condition that kept on calculating mention suggestions when the mention text (with a space) was same as the display text. This was always true because the mention code was always different from the user's display text. With the implementation of the above feature, there were cases where the display name became equal to the mention code. This resulted in an endless loop for the calculation of suggestion items which resulted in this bug.

**Comment by mountiny** [comment] 2024-03-18 13:56
Merged the fix

**Comment by bfitzexpensify** [comment] 2024-04-16 14:53
Payment summary:

@getusha to be paid $500 for contributor work - paid via Upwork ✅ 
@allroundexperts to be paid $500 for C+ work - to be made via manual request

Regression steps proposed in https://github.com/Expensify/Expensify/issues/388157. 

We're all done here, thanks everyone.

**Closed by bfitzexpensify** 2024-04-16 14:53 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-05-02 18:40
$500 approved for @allroundexperts
