### ISSUE TITLE
[HOLD for payment 2024-11-18] [$250] New users seeing Expensify (notifications@expensify.com) in Contacts

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49673] opened 2024-09-24 23:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727214973622039

## Action Performed:

1. Sign up for a new account
2. Selected Manage my team as intention
3. Go through onboarding
4. Select Start chat

## Expected Result:
Expensify DM not displayed in contacts as it is deprecated

## Actual Result:
Expensify ([notifications@expensify.com](mailto:notifications@expensify.com))is displayed in my contacts
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/user-attachments/assets/5acf5b08-670f-4ef6-83b0-dfac4a751be2)

![image (1)](https://github.com/user-attachments/assets/c0b1938c-a106-4f64-9537-1309f9490fc6)

https://github.com/user-attachments/assets/830c4f06-85ca-4dbd-8dcc-6aeec02d3014

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839750030898104642</li>
        <li>Upwork Job ID: 1839750030898104642</li>
        <li>Last Price Increase: 2024-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>ahmedGaber93 | Reviewer | 104411774</li>
<li>Nodebrute | Contributor | 104411779</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @joekaufmanexpensify</details>

**Comment by mkzie2** [comment] 2024-09-25 01:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expensify ```notifications@expensify.com``` is displayed in my contacts.

### What is the root cause of that problem?
All our report and contact data across the search pages come from the [OptionsListContextProvider](https://github.com/Expensify/App/blob/main/src/components/OptionListContextProvider.tsx#L47). Within this provider, we use [createOptionList](https://github.com/Expensify/App/blob/dc74ee347bf3dc134b5488d2a28911cd031104b3/src/libs/OptionsListUtils.ts#L1518) to generate the options, but it does not filter out contacts where its login is ```notifications@expensify.com```.

### What changes do you think we should make in order to solve the problem?
We should add:

```
?.filter((o) => o.login !== CONST.EMAIL.NOTIFICATIONS)
```
to this data:

https://github.com/Expensify/App/blob/dc74ee347bf3dc134b5488d2a28911cd031104b3/src/libs/OptionsListUtils.ts#L1553



### What alternative solutions did you explore? (Optional)

We should clear all the personal data which has login is ```notifications@expensify.com``` after user finishing the onboarding flow.

**Comment by mkzie2** [comment] 2024-09-26 05:20
[Proposal updated](https://github.com/Expensify/App/issues/49673#issuecomment-2372687143)

**Comment by joekaufmanexpensify** [comment] 2024-09-27 19:32
Reproduced.

**Comment by joekaufmanexpensify** [comment] 2024-09-30 13:48
pending review of proposals by @ahmedGaber93

**Comment by ahmedGaber93** [comment] 2024-09-30 13:59
Reviewing today

**Comment by ahmedGaber93** [comment] 2024-09-30 21:05
@Nodebrute thanks for the proposal.
 >    const excludedEmails = isGroupChat 
    ? [CONST.EMAIL.NOTIFICATIONS, ...excludedGroupEmails] 
    : [CONST.EMAIL.NOTIFICATIONS];
    

`excludedGroupEmails` already have `CONST.EMAIL.NOTIFICATIONS`, no need to add it again in `isGroupChat` case

**Comment by ahmedGaber93** [comment] 2024-09-30 21:08
@mkzie2 thanks for the proposal.
> We've already prevented users from chatting with this account and hidden it from search and the LHN in https://github.com/Expensify/App/issues/32340.

Yeah, but we allowed it again [here](https://github.com/Expensify/App/pull/41290/files#diff-7d43f3c3e4decdb0057928e895f456d51c0f4081837edd5e2c4ed7ddd570e274)

**Comment by ahmedGaber93** [comment] 2024-09-30 21:34
@Krishna2323 thanks for the proposal.
I don't think we need to prevent the user from starting chat with all `excludedGroupEmails`, I think we need only `CONST.EMAIL.NOTIFICATIONS`

**Comment by mkzie2** [comment] 2024-10-01 01:02
@joekaufmanexpensify We only hide ```notification@expensify.com``` in new chat page, or all the search pages in the app (chat search, expense filter, participant selector,...)? cc @Expensify/design

**Comment by ahmedGaber93** [comment] 2024-10-01 08:14
I think `notification@expensify.com` now is hidden in all those places, expect new chat and search page. Here we will hide it on the new chat page, and I think no need to hide it from the search page because user should be able to find it to browse the old chat messages any time he need it.

**Comment by joekaufmanexpensify** [comment] 2024-10-01 11:45
We deprecated the Expensify DM `notification@expensify.com`. If we still show it in the new chat and search page, will someone who previously has no history with it still see it? Or do you mean only those who had messages with this DM prior to when we deprecated it?

**Comment by ahmedGaber93** [comment] 2024-10-01 13:13
Currently, `notification@expensify.com` is displayed in search page for the new users, but if we decide to hide it from here, I think we can't limit displaying it for old users only, and it will disappear for all.

![Screenshot 2024-10-01 at 6 07 48 AM](https://github.com/user-attachments/assets/16e89212-d61b-48a2-84f9-775638f45f54)

**Comment by ahmedGaber93** [comment] 2024-10-01 13:37
> but I think we can't create groups with expensify emails except for concierge. This was the behaviour before the refactor of the NewChatPage.

@Krishna2323 I agree it is an issue, but it is a different root cause, and I think it should fix separately, unless @joekaufmanexpensify thinks otherwise.

**Comment by joekaufmanexpensify** [comment] 2024-10-01 19:54
[Confirmed](https://expensify.slack.com/archives/C049HHMV9SM/p1727812450510209?thread_ts=1727214973.622039&cid=C049HHMV9SM) we should hide it for everyone on every page where it might appear

**Comment by joekaufmanexpensify** [comment] 2024-10-03 13:30
>@joekaufmanexpensify, what do you think about this? I think it's tightly related to this issue and should be fixed here. The solution is also not complex.

Is this saying that it's not currently possible for anyone using a non-expensify.com email address to create a group chat with an email address that has `expensify.com` in it?

**Comment by ahmedGaber93** [comment] 2024-10-03 19:56
The current code have a [logic](https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/pages/NewChatPage.tsx#L40) to prevent adding those [emails](https://github.com/Expensify/App/blob/b027baaf086c4a8f57bec48dd1cbbfb3c317726b/src/CONST.ts#L1431-L1450) to groups, but this code doesn't work fine after refactoring `NewChatPage`.




https://github.com/user-attachments/assets/935ffea3-e193-46b6-9c5a-f5da779c15f9



I think this issue should fix separately, please let me know if it should be fixed here?

**Comment by joekaufmanexpensify** [comment] 2024-10-04 15:16
Got it. If we want to keep it, it'd be nice to fix it here too, if it's an easy fix. I am [confirming internally](https://expensify.slack.com/archives/C03U7DCU4/p1728054938695209) and will circle back!

**Comment by joekaufmanexpensify** [comment] 2024-10-07 14:45
We discussed internally, and decided we want to: 

- Fix the logic preventing adding [these system accounts](https://github.com/Expensify/App/blob/b027baaf086c4a8f57bec48dd1cbbfb3c317726b/src/CONST.ts#L1431-L1450) to group chats.
- Allow any other [expensify.com](http://expensify.com/) email to be added to a group chat.

Can we easily do that as a part of this issue?

**Comment by ahmedGaber93** [comment] 2024-10-07 18:00
> Can we easily do that as a part of this issue?

Yes, we can.

**Comment by joekaufmanexpensify** [comment] 2024-10-08 13:29
>are users allowed to chat with system accounts such as ([accounting@expensify.com](https://www.expensify.com/_support/?supportEmail=accounting%40expensify.com&comment=better%20supportal%20issue%20number%3A%2049673&location=_support/)Copy to clipboard)?

No, we want to fix the logic so you cannot create group chats with the system accounts on the top bullet point [here](https://github.com/Expensify/App/issues/49673#issuecomment-2397138062).

**Comment by ahmedGaber93** [comment] 2024-10-08 14:43
I think there are two cases here
1. add them to group. Not allowed.
2. DM with any of them. Allowed.

**Comment by ahmedGaber93** [comment] 2024-10-09 21:41
This issue is combined from two parts after expanding the scope [here](https://github.com/Expensify/App/issues/49673#issuecomment-2397138062)
1. New users seeing Expensify (notifications@expensify.com) in Contacts
@Nodebrute's [alternative proposal](https://github.com/Expensify/App/issues/49673#issuecomment-2372619998) LGTM! (the last update from @Krishna2323 also propose it, but @Nodebrute propose it first)

2. user able to adding those Expensify [emails](https://github.com/Expensify/App/blob/b027baaf086c4a8f57bec48dd1cbbfb3c317726b/src/CONST.ts#L1431-L1450) to groups
@Krishna2323's [alternative proposal point 2](https://github.com/Expensify/App/issues/49673#issuecomment-2381037850) is a good to move forward

I think split 50% for every one is fair, one of you will raise the PR and the second will review it. Your both will be completely responsible about PR

🎀 👀 🎀 C+ reviewed

**Comment by joekaufmanexpensify** [comment] 2024-10-09 22:04
>I think there are two cases here based on the code
>add them to group. Not allowed (have a bug and will fix here to confirm preventing adding them)
>DM with any of them. Allowed.

@ahmedGaber93 Is this how the current logic (that is broken now) works? Basically before the change a few weeks ago that broke this, this is how it worked?

**Comment by joekaufmanexpensify** [comment] 2024-10-09 22:05
It does seem a bit odd to me that you could start a chat with some of [these system accounts](https://github.com/Expensify/App/blob/b027baaf086c4a8f57bec48dd1cbbfb3c317726b/src/CONST.ts#L1431-L1450), so want to make sure I understand correctly.

**Comment by ahmedGaber93** [comment] 2024-10-09 22:14
> DM with any of them. Allowed.

@joekaufmanexpensify DM logic is not broken. it was allowed before and after the refactoring. I think we never prevent  chatting with them.

The broken logic that needs to be fixed is related to "add to group"

**Comment by lakchote** [comment] 2024-10-10 10:42
I'm with @joekaufmanexpensify it doesn't make sense to be able to DM a system account, as the user won't be able to receive any kind of response.  What's the point of chatting if it's one way conversation? Let's prevent this in the first place.

Even if it was allowed before, it doesn't mean it wasn't broken. Maybe we just forgot to handle it.

**Comment by joekaufmanexpensify** [comment] 2024-10-10 12:26
Agreed largely. Though there are some where you need to be able to DM. Like Concierge, chronos, and maybe some of the accounting ones? Let's hold on this a sec, and I'll bring it back to the slack thread to align on which ones we want to allow/block.

**Comment by joekaufmanexpensify** [comment] 2024-10-10 12:34
[Discussing ](https://expensify.slack.com/archives/C03U7DCU4/p1728563640444039?thread_ts=1728054938.695209&cid=C03U7DCU4)

**Comment by joekaufmanexpensify** [comment] 2024-10-10 21:45
Okay, I think we landed on sticking with [this ](https://github.com/Expensify/App/issues/49673#issuecomment-2397138062), meaning no restrictions on DMs (same as now). Agree @lakchote ?

**Comment by joekaufmanexpensify** [comment] 2024-10-14 13:28
I think we just need @lakchote's sign off to proceed with the selected proposal here.

**Comment by lakchote** [comment] 2024-10-14 15:01
Agree @joekaufmanexpensify let's go with [this](https://github.com/Expensify/App/issues/49673#issuecomment-2397138062), without any restrictions on DMs for now.

**Comment by Nodebrute** [comment] 2024-10-15 17:46
I can raise the PR. @Krishna2323, can you do the final review if that's okay?

**Comment by Nodebrute** [comment] 2024-10-15 22:41
Pr will be ready in few hours.

**Comment by joekaufmanexpensify** [comment] 2024-10-17 17:25
Great. TY!

**Comment by Nodebrute** [comment] 2024-10-17 19:01
@Krishna2323 @ahmedGaber93 [pr](https://github.com/Expensify/App/pull/50937) is ready for review

**Comment by joekaufmanexpensify** [comment] 2024-10-21 13:41
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-10-28 16:50
same

**Comment by joekaufmanexpensify** [comment] 2024-11-04 16:03
PR in review. Asked if we're good to merge it

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:25
PR on staging

**Comment by joekaufmanexpensify** [comment] 2024-11-11 15:53
Hm, I just updated it? That is wrong.

**Comment by joekaufmanexpensify** [comment] 2024-11-18 15:53
@ahmedGaber93 could you please do the checklist so we can prep for payment?

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:35
TY! regression test issue is here: https://github.com/Expensify/Expensify/issues/446304

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:40
@ahmedGaber93 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:42
OG upwork job closed, so need to open [a new one](https://www.upwork.com/jobs/~021859276011284551207) to pay @Nodebrute and @Krishna2323

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:45
@Krishna2323 offer sent for $125!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:46
@Nodebrute offer sent for $125

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:54
@Krishna2323 $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:54
@Nodebrute $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:55
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-11-20 16:55
All set, thanks everyone!

**Closed by joekaufmanexpensify** 2024-11-20 16:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
