### ISSUE TITLE
IOU - An administrator cannot edit an unpaid IOU created by an employee

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34181] opened 2024-01-09 19:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a Collect group policy, enable categories and add 3 categories, add an employee to the policy.
1. Open New Expensify app
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. Select a category and fill in the rest of the required data
10. Complete the IOU request
11. Re-login with the administrator account
12. Navigate to the WS room where the IOU was sent
13. Open the IOU created by the employee
14. Try editing the IOU details

## Expected Result:
The administrator should be able to edit an unpaid IOU created by an employee

## Actual Result:
An administrator cannot edit an unpaid IOU created by an employee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/465030d9-5da8-4f7c-9e8c-35609a714f34

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by unicorndev-727** [comment] 2024-01-09 19:31
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
IOU - An administrator cannot edit an unpaid IOU created by an employee
### What is the root cause of that problem?
The root cause is that only isRequestor can edit if the report is not approved or settled here.
https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/libs/ReportUtils.ts#L1970
### What changes do you think we should make in order to solve the problem?
We need to update like this.
```
return !isReportApproved(moneyRequestReport) && !isSettled(moneyRequestReport?.reportID) && (isRequestor || isAdmin || isManager);
```
### What alternative solutions did you explore?
N/A

**Comment by tgolen** [comment] 2024-01-09 19:38
@youssef-lr can you confirm this was a regression from your PR and if so, work on a fix for it? If you confirm it's not related to your PR, please assign it back to me. @unicorndev-727 thanks for the initial RCA!

**Comment by Pujan92** [comment] 2024-01-09 19:41
Is it intentional to not allow edit when the status is OPEN as I am seeing the comment in that [PR](https://github.com/Expensify/App/pull/33633/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR1899).

https://github.com/Expensify/App/blob/5d0931dc47bb5b01d0ff7a3d7662d7cea78f9868/src/libs/ReportUtils.ts#L1896-L1898

**Comment by youssef-lr** [comment] 2024-01-09 20:09
Removing blocker for now, will wait for confirmation from Tom whether or not reports in Free policies can be edited by admins while they're still open.

**Comment by trjExpensify** [comment] 2024-01-09 21:48
How are there open reports on free workspaces, given that the report start out on `processing`? 😕

**Comment by youssef-lr** [comment] 2024-01-12 03:43
ah I think this was tested on a Collect workspace, @lanitochka17 can you confirm please whether you tested on a Free or Collect workspace?

**Closed** 2024-01-12 03:44 UTC
Labels: Engineering, Daily
