### ISSUE TITLE
[$500] Search-Spinner is not shown while searching a contact in room and workspace invite

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33050] opened 2023-12-14 10:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap fab
3. Tap Start chat
4. Search for a contact by pasting a phone number
5. Note spinner is displayed
6. Navigate to LHN
7. Tap fab
8. Tap assign task
9. Enter title and tap next
10. Tap share somewhere
11. Search for a contact by pasting a phone number
12. Note spinner is displayed
13. Navigate to LHN
14. Tap on a room chat
15. Tap header---members----invite
16. Search for a contact by pasting a phone number
17. Note spinner is not displayed
18. Navigate back to LHN
19. Tap profile icon ---- Workspaces---Workspace
20. Tap members---Invite
21. Search for a contact by pasting a phone number
22. Note spinner is not displayed

## Expected Result:
Spinner must be shown while searching a contact in search input (name, email or phone number) section in entire app in a consistent manner.

## Actual Result:
Spinner is not shown while searching a contact in room and workspace invite but displayed in start chat, task share somewhere.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/15be0ea6-41e4-479b-81d8-17e636cd54d9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0174c6d17a23d1edc0</li>
        <li>Upwork Job ID: 1735239063629557760</li>
        <li>Last Price Increase: 2023-12-14</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-14 10:14
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Search-Spinner is not shown while searching a contact in room and workspace invite

### What is the root cause of that problem?

This is due to WorkspaceInvite Page uses SelectionList whereas NewChatPage uses OptionSelector

### What changes do you think we should make in order to solve the problem?



### What alternative solutions did you explore? (Optional)

Maybe use OptionSelector in WorkspaceInvite page

**Comment by paultsimura** [comment] 2023-12-14 10:15
This looks like an expected behavior:

The spinner is shown for searches that perform BE search in the background – e.g. the ones that are searching for Reports (like when sharing a task etc.)
The members' search is not performing any BE API calls and the results are shown instantly, therefore the spinner was not added here intentionally.

**Comment by BhuvaneshPatil** [comment] 2023-12-14 10:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search spinner is not shown while searching a contact in room and workspace invite.

### What is the root cause of that problem?
We have not used any flag for `isLoading` to know if search has been done.

### What changes do you think we should make in order to solve the problem?
We shall create a new flag/state `isLoading` that will be set to false, when search starts and set to false when search ends.
We shall add this flag to `showLoadingPlaceholder` prop.

### What alternative solutions did you explore? (Optional)

**Comment by Zaki-BZD** [comment] 2023-12-14 11:37
Hey izarutskaya,

### Understanding the Problem:
how spinner work : when you tap a number, the spinner will spin while the function find your result (like-loading)
Your problem: As we can see, the spinner does not show, but the function is still working, and it will give you the result that you want.
That means it is a design function issue, so how will we fix it?

### How we can fix it:
we will compare the design code between  the start chat function and the assign function, specify the problem and fix it 

### conclusion 
Izarutskaya  I truly appreciate you posting it; I had pleasure reading it and found the solution, even if I can't fix it right away because I didn't see the code.

**Thanx.**

**Comment by adelekennedy** [comment] 2023-12-14 13:57
This is expected behavior - closing this as a polish as we're focusing in our roadmap issues

**Closed by adelekennedy** 2023-12-14 13:57 UTC
Labels: External, Daily, Help Wanted, Bug
