### ISSUE TITLE
[$1000] Chat - Message sent without space but while edit comment a single space is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25681] opened 2023-08-22 14:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap any report
3. Enter >[she@gmail.com](mailto:she@gmail.com)
4. Tap send
5. Long press the sent message
6. Tap edit comment

## Expected Result:
The user sent message without space >[she@gmail.com](mailto:she@gmail.com)
and so while editing also, the message must be shown without space >[she@gmail.com](mailto:she@gmail.com)

## Actual Result:
The user sent message without space >[she@gmail.com](mailto:she@gmail.com)
but while editing, the message is shown with space
> [she@gmail.com](mailto:she@gmail.com)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9752547c-1c27-47a1-8930-eebc0368f8a0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0101564ea93c635e12</li>
        <li>Upwork Job ID: 1694030108841062400</li>
        <li>Last Price Increase: 2023-08-22</li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-08-22 18:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Quote message was sent without leading space but while editing comment, a single space is shown in the composer.

### What is the root cause of that problem?
When we send a quote message, the parser removes all leading spaces.
And when we edit a quote message, `htmlToMarkdown` function of `ExpensiMark` class adds a leading space to markdown text.
https://github.com/Expensify/expensify-common/blob/7735de14112a968fd6a4f5af710d2fbaefc8809d/lib/ExpensiMark.js#L314

If we save the updated quote message, the parser removes that appended leading space again.

### What changes do you think we should make in order to solve the problem?
If we want to change this, we need to update `htmlToMarkdownRules` of `expensify-common` repo by removing a leading space.
```
const resultString = g2.replace(/\n?(<h1># )/g, '$1')
                        .replace(/(<h1>|<\/h1>)+/g, '\n')
                        .trim()
                        .split('\n')
                        .map(m => `>${m}`)
                        .join('\n');
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by burczu** [comment] 2023-08-23 08:45
I think we should proceed with [the proposal](https://github.com/Expensify/App/issues/25681#issuecomment-1688822380) from @Krishna2323 - it covers all the scenarios preserving none, one or multiple spaces after the quote sign

[The proposal](https://github.com/Expensify/App/issues/25681#issuecomment-1688708684) from @akamefi202 is limited: it always show quote without spaces in edit mode, even if there were some spaces originally

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-08-23 08:58
@akamefi202 I think quotes are special case where want to preserve original formatting

**Comment by dangrous** [comment] 2023-08-23 18:11
okay sooooooo if we choose to fix this, I think @Krishna2323's solution makes sense.

However, I'm not entirely sure it needs to be fixed. For example, Slack also automatically adds a space if there isn't one (it also collapses spaces down, so:
* no spaces -> 1 space
* 1 space -> 1 space
* 2 spaces -> 2 spaces (1 in the quote, one not visible except on edit)
* 3 spaces -> 3 spaces (2 in the quote, one not visible except on edit).

I think we might be fine as is, sort of a middle ground - at the very least I think this would end up being a new feature request not a bug. What do you think, @kevinksullivan? Should we just trim/expand to one space?

**Comment by dangrous** [comment] 2023-08-23 18:42
Yeah it's harder to tell with the live preview. Try changing your preferences (Preferences > Advanced) to "Format messages with markup". That's closer to how ours works since we don't have the preview (yet).

<img width="460" alt="image" src="https://github.com/Expensify/App/assets/5487802/eeef7e9c-3cf4-4fb2-8098-8efae235febc">

**Comment by kevinksullivan** [comment] 2023-08-24 18:59
Thanks for breaking this down @dangrous . After your summary I tend to agree, that this is really a new feature rather than a bug. I'm going to close this out.

**Closed by kevinksullivan** 2023-08-24 18:59 UTC
Labels: External, Daily, Help Wanted, Bug
