### ISSUE TITLE
[HOLD for payment 2024-03-11] [HOLD for #36401] [$500] Reimburse - Pressing 'Enter' key on 'Rate' page refreshes the page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36439] opened 2024-02-13 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (new feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open workspace settings page
2. Click on 'Reimbursements'
3. Click on 'Rate'
4. Click on 'Rate' again
5. Modify the rate > press 'Enter' key
## Expected Result:
Amount change should be saved

## Actual Result:
Page refreshes

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/e4efd075-a0bf-4dc0-bfcd-8b9a634c49c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01255e944bed02c24a</li>
        <li>Upwork Job ID: 1757576298278928384</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment] 2024-02-13 21:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reimburse - Pressing 'Enter' key on 'Rate' page refreshes the page
### What is the root cause of that problem?
The main root cause of the problem is that `Form` is getting submitted automatically when we hit `Enter` key on the keyboard. 
https://github.com/Expensify/App/blob/19e28491a92d2ea74b85b73b86aad1f2f3e06174/src/pages/workspace/reimburse/WorkspaceRateAndUnitPage/RatePage.tsx#L85-L105
### What changes do you think we should make in order to solve the problem?

The main change that will stop this issue is, we need to stop the `Form` from getting submitted, when we hit `Enter` keyboard, by adding some kind off `e.preventDefault()`, which is basically the default behaviour of the form, which will not only just stop submitting the form, but would also stop the page from reloading again and again on hitting `Enter` key.
### What alternative solutions did you explore? (Optional)
N/A

**Comment by deetergp** [comment] 2024-02-14 01:38
I don't think this is a blocker. I have confirmed that the bug exists in `main` and that the PR that @shubham1206agra raised for https://github.com/Expensify/App/issues/36363 fixes this one too.

I was going to say that I'd expect hitting `Enter` would function the same clicking the Save button, but isn't how production works either.

**Comment by cubuspl42** [comment] 2024-02-14 09:03
I understand that PR https://github.com/Expensify/App/pull/36401 fixes this issue, right?

**Comment by Christinadobrzyn** [comment] 2024-02-16 19:57
@deetergp or @Ollyws could you confirm this for us? https://github.com/Expensify/App/issues/36439#issuecomment-1943336419

**Comment by deetergp** [comment] 2024-02-16 20:26
> I understand that PR https://github.com/Expensify/App/pull/36401 fixes this issue, right?

It seemed to for me when I tested it @cubuspl42 but can't say definitively till it's finished and merged.

> Oh I am working on this on separate PR. This is from another PR I raised earlier.

Can you elaborate @shubham1206agra?

**Comment by cubuspl42** [comment] 2024-02-19 09:28
This issue is now being handled in the regression path, and PR https://github.com/Expensify/App/pull/36401 has been created to solve it. I'm not sure if we call such cases "holding".

**Comment by cubuspl42** [comment] 2024-02-21 08:52
Unless there's any objection, we'll assume the expected behavior @shubham1206agra mentioned.

**Comment by getusha** [comment] 2024-02-23 06:42
>Clarification here: The expected behaviour should be that the page should not refresh. We do not submit form on pressing Enter now on this specific page.

Is there any way to allow submitting the form on enter yet preventing the refresh?

**Comment by getusha** [comment] 2024-02-23 07:51
>For submitting the form on Enter, I need to change so many components to achieve the same, so it might be a feature request for me. (This is context to this component only).

I feel like this should be handled here? or as a follow up? @shubham1206agra

**Comment by getusha** [comment] 2024-02-23 07:57
thanks @shubham1206agra, and the expected result is **Amount change should be saved** 😄

**Comment by deetergp** [comment] 2024-02-28 15:52
Where are we at with this one?

**Comment by deetergp** [comment] 2024-03-01 18:57
Nice! Looks like it got merged yesterday.

**Comment by cubuspl42** [comment] 2024-03-05 09:50
- No payment due for @Ollyws 
- BugZero checklist is redundant, as this was handled as a regression

**Comment by deetergp** [comment] 2024-03-06 07:53
I think that means we can close this one out then, right?

**Comment by Christinadobrzyn** [comment] 2024-03-07 01:27
Yep! closing!

**Closed by Christinadobrzyn** 2024-03-07 01:27 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
