### ISSUE TITLE
[$1000] Duplitcate record is created on LHN when sending an IOU

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19037] opened 2023-05-16 16:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Precondition: Sender and recipient shouldn't have an existing chat
## Action Performed:

1. Sign in with account A
2. Send an IOU to account B
3. Shift to the tab where account B is signed in
4. Observe two LHN records are created for Sender account A, and Recipient account B on the sender and recipient side

## Expected Result: 
Duplicate records shouldn't be created on LHN
## Actual Result: 
Duplicate records are created on LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bb540e07-5ecb-4897-9b99-2af70b707527

https://github.com/Expensify/App/assets/43996225/176dbfc8-12cf-469d-be17-6c8d698746e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684140542624389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e6465336f99ff325</li>
        <li>Upwork Job ID: 1658551075223650304</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-05-16 19:12
Looks good!

**Comment by Natnael-Guchima** [comment] 2023-05-16 19:18
@slafortune I think there is a similar issue raised on this [GH issue](https://github.com/Expensify/App/issues/18969)  and it was agreed that it is an expected behavior to have a duplicate chat in LHN

**Comment by Natnael-Guchima** [comment] 2023-05-16 19:20
> @slafortune I think there is a similar issue raised on this [GH issue](https://github.com/Expensify/App/issues/18969)  and it was agreed according to this [comment](https://github.com/Expensify/App/issues/18969#issuecomment-1548524219 ) that it is an expected behavior to have a duplicate chat in LHN

**Comment by alex-mechler** [comment] 2023-05-17 00:09
Thanks @Natnael-Guchima, this is expected behavior now, closing it out since the linked issue will update the test rails

**Closed by alex-mechler** 2023-05-17 00:09 UTC
Labels: External, Daily, Help Wanted, Bug
