### ISSUE TITLE
Web - Chat - IOU Preview is displayed only for last Split Bill in group chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18743] opened 2023-05-10 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Create a group chat
3. Create Split bill in the group chat several times

## Expected Result:
The separate IOU Preview should be displayed for each split

## Actual Result:
IOU Preview is displayed only for last Split Bill in group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/e5b9d195-723a-4497-af2f-1babe80d9937

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tienifr** [comment] 2023-05-11 08:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Only last split bill message has IOU Preview in group chat

### What is the root cause of that problem?

This commit cause the problem https://github.com/Expensify/App/commit/ac3083bac239d82b557750b30aae3ec04c12f5b0

We just show the IOU Preview in the most recent IOU action

### What changes do you think we should make in order to solve the problem?

I think we should remove shouldShowIOUPreview check and show IOU Preview in every split bill action

**Comment by trjExpensify** [comment] 2023-05-11 22:24
@Julesssss can you confirm this is going to be fixed elsewhere before I close it out? Every split will have an IOUPreview, not just the last. I.e 

![image](https://github.com/Expensify/App/assets/16232057/ee7f94bc-7fd6-478b-9256-611e0add9178)

**Comment by Julesssss** [comment] 2023-05-12 08:20
Yeah, I couldn't remove the `shouldShowIOUPreview` logic at this point, but it is done in [this PR. ](https://github.com/Expensify/App/pull/18486)

**Closed by Julesssss** 2023-05-12 08:20 UTC
Labels: Daily, Bug
