### ISSUE TITLE
[$1000] Money request is shown from the other account instead of current user.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22862] opened 2023-07-14 03:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new chat.
2. Click on '+' and request money.
## Expected Result: 
The IOU should be from the current user.
## Actual Result: 
The IOU is shown to be from the user we are chatting with.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2d6cf88f-64f7-4d11-aad3-f9ee94af5eb8

https://github.com/Expensify/App/assets/43996225/f036316d-f700-4117-90c5-db643bd3da34

**Expensify/Expensify Issue URL:**
**Issue reported by:** @esh-g 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689261117044569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019b2ea0a8e06090db</li>
        <li>Upwork Job ID: 1684323672353202176</li>
        <li>Last Price Increase: 2023-07-26</li>
    </ul>
</details>

**Comment by francoisl** [comment] 2023-07-14 04:26
Is this actually a bug? The same behavior is happening on production for me. Besides, it says "<other person> owes", 
 showing that the money request was sent to them

Production | Staging
--- | ---
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/c418f7e2-3048-4df0-8a12-5feba3995d09"> | <img width="1512" alt="image" src="https://github.com/Expensify/App/assets/2229301/729d5f48-a54e-4a1c-9ba6-52271ea3c601">

**Comment by jeet-dhandha** [comment] 2023-07-14 04:36
The message should have gone from the requester's account instead of the payer's account.

**Comment by francoisl** [comment] 2023-07-14 05:01
I think that's how it's supposed be rendered, the preview clearly says who owes money to who. I can see how it can be confusing though – let's see of someone who's more familiar with this can chime in.

Anyway, even if it were a bug, the same also happens on production, so I'm going to remove the deploy blocker label for now.

**Comment by esh-g** [comment] 2023-07-14 05:27
@francoisl I'm not able to repro on prod.. Maybe it is a glitch in `accountID` sequence or something that is specific to accounts?
https://github.com/Expensify/App/assets/77237602/fe907f95-35c3-42ae-a97a-75f96e6866ff

**Comment by mountiny** [comment] 2023-07-14 06:32
I think this might be related to when you start chatting with unknown user and you request money, i believe the email used is incorrect in such case.

**Comment by rojiphil** [comment] 2023-07-14 10:44
I can consistently reproduce this on staging. Here is the video.

https://github.com/Expensify/App/assets/3004659/37a14d15-bdc4-458f-8552-7ae14f853485

**Comment by rojiphil** [comment] 2023-07-14 10:52
A question on this [code in ReportUtils.js](https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/libs/ReportUtils.js#L1632C7-L1632C7)
Any idea, why we are setting the `accountID` using `iouReport.managerID` on creation of optimistic report preview action? As I understand, `managerID` may turn out to be payerID or payeeId depending on context. 
I think, we should be using `currentUserAccountID` here. 
wdyt?

**Comment by rojiphil** [comment] 2023-07-14 11:53
I notice that the backend also works this way because `actorAccountID` set to that of the other user and not the current user. If this is a bug, even backend would need to fix.

**Comment by michaelhaxhiu** [comment] 2023-07-18 23:38
@rojiphil sorry but I don't follow the bug from your recording. What is incorrect or inconsistent exactly? Mind screenshotting the point in the video where the problem exists so I can understand?

**Comment by michaelhaxhiu** [comment] 2023-07-18 23:51
IMO this bug isn't reproducible reliably. I tried with real users, and then I tried to take @mountiny's advice too:

>I think this might be related to when you start chatting with unknown user and you request money, i believe the email used can be incorrect in such case but I dont have clear repro steps yet

But when I use an unknown phone numbers, the DM flickers for a moment and I get re-routed to a chat DM with Concierge. So like it won't really let me reproduce. Here's a quick video:

https://recordit.co/lFXdZNBVQE

If I pause at the split second frame, it looks like the "amount" and "owes" text is all accurate to me 🤔 

<img width="777" alt="image" src="https://github.com/Expensify/App/assets/13206896/9745f3af-0303-462e-ae6d-4fbb44ceedb4">

**Comment by michaelhaxhiu** [comment] 2023-07-18 23:51
@robertjchen what do you think about this one?

**Comment by rojiphil** [comment] 2023-07-19 01:45
> @rojiphil sorry but I don't follow the bug from your recording. What is incorrect or inconsistent exactly? Mind screenshotting the point in the video where the problem exists so I can understand?

@michaelhaxhiu  The problem is not with the amount or who owes it. The problem is that the chat initiator's avatar and name are not displayed in the chat. If you look at my video here - https://github.com/Expensify/App/issues/22862#issuecomment-1635674621, chat is sent from T5 to T6. However, the chat is attributed to be sent by T6 (refer to the attached screenshot) even though it was initiated by T5. According to me, this is the problem.

The root cause of this issue is [at this line](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/libs/ReportUtils.js#L1629) where we are building an optimistic report preview. Here, the `actorAccountID` is set to report's managerID which could be payer/payee depending on the context. Setting `actorAccountID` to `currentUserAccountID` seems to be the right thing to do here but, then, the response of the API request resets the `actorAccountID` back. Not sure, if this is by design or if this is a real bug that needs a fix in frontend and backend. To me, this looks like a bug.

![bug_detail](https://github.com/Expensify/App/assets/3004659/73272d3a-777b-4083-a4d9-f222d162bdc5)

**Comment by michaelhaxhiu** [comment] 2023-07-26 22:03
@rojiphil Thanks for fleshing that out more for me. I find your input compelling. Let's go `external` and see if we can fix the small issue.

**Comment by rojiphil** [comment] 2023-07-27 04:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that the chat initiator's avatar and name are not displayed in the chat. If you look at my video here - https://github.com/Expensify/App/issues/22862#issuecomment-1635674621, chat is sent from T5 to T6. However, the chat is attributed to be sent by T6 even though it was initiated by T5. This is the problem we are trying to solve.

### What is the root cause of that problem?
The root cause of this issue is [at this line](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/libs/ReportUtils.js#L1629) where we are building an optimistic report preview. Here, the `actorAccountID` is set with report's `managerID` which could be payer/payee depending on the context. 

### What changes do you think we should make in order to solve the problem?

Setting `actorAccountID` with `currentUserAccountID` would ensure that the chat initiator's details will be set to the current user who initiated it.
The change has to be made at [this line here](https://github.com/Expensify/App/blob/edfea4be3fc08f8d6d61edcbf353c248425927d3/src/libs/ReportUtils.js#L1629) like this:

`        actorAccountID: currentUserAccountID,`

Further, when API with command `RequestMoney` is sent, the BE should ensure that reportAction with `actionName: REPORTPREVIEW` has the `actorAccountID` set to the first time initiator's account id. I think, subsequent `RequestMoney` requests from either actors (T5 or T6) shouldn't update the `actorAccountID`. wdyt?  

### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 22:48
This looks like expected behavior to me @michaelhaxhiu please check with the product & design team.

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:15
Thansk for your input @Santhosh-Sellavel. I spent time to look into this a little further and have changed my stance, we do this intentionally. Closing this GH.

**Closed by michaelhaxhiu** 2023-07-31 13:15 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
