### ISSUE TITLE
[Held requests] Held and unpaid expense disappears when paying only the unheld expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46370] opened 2024-07-27 23:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4775912
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B
3. [User A] Hold one of the submitted expenses
4. [User B] Go to expense report from User A
5. [User B] Click Pay button
6. [User B] Pay partially the expense (pay the unheld expense)

## Expected Result:
For User A and B,
- the paid system message should display "paid <unheld amount> elsewhere"
- the unpaid expense will be moved to a new report

## Actual Result:
For User A and B,
- the paid system message displays "paid <the total amount including the held one> elsewhere"

For User A,
- the unpaid expense disappears.

For User B,
- the unpaid expense becomes negative in another report, and it leads to not here page.
- the unpaid expense disappears after clearing app cache and restarting app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/ff5a6c14-fb0d-4f66-aa7c-9efc33b09cb2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d67b0d3a732826c4</li>
        <li>Upwork Job ID: 1821690332875199057</li>
        <li>Last Price Increase: 2024-08-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertjchen</details>

**Comment by lanitochka17** [comment] 2024-07-27 23:05
We think that this bug might be related to #wave-collect - Release 1

**Comment by lanitochka17** [comment] 2024-07-27 23:06
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by JmillsExpensify** [comment] 2024-08-07 14:35
Going to highlight this one in the project issue.

**Comment by JmillsExpensify** [comment] 2024-08-08 23:29
Flagged this in #wave-collect. I'll go ahead and add it to polish for now, though @trjExpensify we can remove depending on how the wave-collect/polish hit list pans out.

**Comment by trjExpensify** [comment] 2024-08-12 13:58
@dukenv0307 any more insight on that? CC: @robertjchen

**Comment by robertjchen** [comment] 2024-08-14 07:19
Looks like the backend is not sending Onyx updates when something is being unheld. Testing out some solutions locally to see if it'll help here.

**Comment by robertjchen** [comment] 2024-08-15 18:14
Investigating this one at the moment. See update in https://github.com/Expensify/Expensify/issues/274076#issuecomment-2290830771

**Comment by robertjchen** [comment] 2024-08-15 23:05
Got a potential BE fix in review

**Comment by robertjchen** [comment] 2024-08-16 18:23
Fix was merged and should go out Monday, we can re-test then

**Comment by robertjchen** [comment] 2024-08-19 15:35
Fix should be deployed later today

**Comment by garrettmknight** [comment] 2024-08-20 13:51
Awesome @JmillsExpensify can you retest?

**Comment by robertjchen** [comment] 2024-08-20 14:12
Auth deploy was [blocked](https://expensify.slack.com/archives/C07J32337/p1724113539981129?thread_ts=1724109473.132529&cid=C07J32337) yesterday- still waiting on BE changes to go out

**Comment by robertjchen** [comment] 2024-08-20 18:37
BE changes are now live 👍

**Comment by robertjchen** [comment] 2024-08-27 05:10
Re-tested this and the issue is still present- dove into it a bit more today and the RCA is accurate, the expense disappears since it gets moved onto a new workspace... It seems like the partial approve/pay logic we have in place for expense reports isn't working properly for direct money requests. Continuing to investigate.

**Comment by robertjchen** [comment] 2024-08-27 19:38
calm down melvin-bot

**Comment by trjExpensify** [comment] 2024-09-03 22:21
I'm removing the `Reviewing` label as this there isn't an active PR in dev for this.

**Comment by JmillsExpensify** [comment] 2024-09-04 14:02
Yeah, still working through the issue.

**Comment by trjExpensify** [comment] 2024-09-09 13:58
Suggested next steps from @luacmartins [in thread](https://expensify.slack.com/archives/C036QM0SLJK/p1725635856468069?thread_ts=1725283921.221589&cid=C036QM0SLJK): 

>This is happening because we're moving an IOU expense to a new expense report, instead of an IOU report, because we call `moveTransactionsToNewExpenseReport`
>we need to check if we're moving a transaction on iou or expense report and then move it to a new iou report instead

**Comment by robertjchen** [comment] 2024-09-13 01:17
PR with fix for negative amounts with held expenses merged 👍 Finishing this off with the iou report moving issue

**Comment by robertjchen** [comment] 2024-09-18 02:39
Draft PR has working flow in place, testing still in progress for the final optimistic updates. Should be ready to review before EOW

**Comment by robertjchen** [comment] 2024-09-19 12:49
PR under review

**Comment by robertjchen** [comment] 2024-09-20 12:42
FE PR under review

**Comment by robertjchen** [comment] 2024-09-25 08:22
Tested and held IOUs no longer "disappear" off to an inaccessible policy 👍

Did come across two minor bugs coming off of the new flow- created new successor issues linked below:
- https://github.com/Expensify/Expensify/issues/430923
- https://github.com/Expensify/App/issues/49689

**Closed by robertjchen** 2024-09-25 08:22 UTC
Labels: Reviewing, Daily, Internal, Bug
