### ISSUE TITLE
[HOLD for payment 2022-12-27] White screen appears when loading chat, after being redirected from IOU modal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13074] opened 2022-11-28 04:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Have an account with some good number of chats between accounts A and B
2. From account A, go to any other chat except B
3. Signout from A
4. Sign in into A again
5. From + button, Request Money from B
6. In the chat view with B, white screen appears while chats are loading

## Expected Result:
Skeleton view should appear

## Actual Result:
White screen appears

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.32-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204194300-ebbb7960-7a92-4936-b15d-fdfda3bc74ad.mov

https://user-images.githubusercontent.com/43996225/204194309-f65f746a-d4bb-4de8-850e-a86e91747eb6.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @MonilBhavsar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669293337450379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2022-11-28 18:58
Managing a BUG issue

From  this  SO: https://stackoverflow.com/c/expensify/questions/14418
_______
- [ ] Confirm the "bug" is actually a  bug
- [ ] Confirm the  bug is  not  a  duplicate  report of  an existing  GH (close  the  GH  and  add  any  relevant  details  to  the  original  GH ) 
- [ ] The  bug  is  reproducible

**If you’re unable  to  reproduce  the  bug:**
-  [ ] Add  the `Needs reproduction`  label
-  [ ] Comment  on the  issue  outlining the steps  you  took  to reproduce the bug, and your  results
-  [ ] Tag the issue reporter and the Applause QA member who created the issue. Ask  them  to  clarify  the reproduction steps  and/or to  check  the  reproduction  steps  again.

If the bug is reproducible:
- [ ] The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?)
- [ ] The GH was created by an Expensify employee or a QA tester
- [ ] If  the bug is an OldDot issue,  you  should  decide  whether  it  is  widespread  enough  to  justify fixing or  it  is  better  to  wait  for  reunification. If  it’s  better  to  wait,  close  the  GH and  provide details
- [ ] If there's  a  link  to  Slack, check the discussion and see why we decided to fix it or not
- [ ] Decide if  the GH should be resolved  by an External contributor or Internal engineer, add the appropriate  label

**Comment by MonilBhavsar** [comment] 2022-11-29 07:09
@yuwenmemon thanks for picking this. I did some digging in the past issue. Happy to help here too and could you please assign me for a review as I'm curious about the fix.

**Comment by yuwenmemon** [comment] 2022-11-29 15:28
@MonilBhavsar do you have a link to the past issue?

**Comment by MonilBhavsar** [comment] 2022-11-29 16:59
Here is the issue https://github.com/Expensify/App/issues/11471
We decided to create a new issue to fix the root cause.

**Comment by yuwenmemon** [comment] 2022-11-30 20:05
Commented in the PR here: https://github.com/Expensify/App/pull/12960#issuecomment-1332677573

**Comment by yuwenmemon** [comment] 2022-12-01 20:48
@MonilBhavsar I wonder if the latency is the same as when we are loading the report in general? In which case would we just want to show some skeleton UI above showing that the chat messages are loading?

When accessing the report fresh without coming from an IOU request:
https://user-images.githubusercontent.com/4741899/205155341-cf5ed81c-167e-4565-bc34-82bb3f4a7293.mp4

When accessing via an IOU:
https://user-images.githubusercontent.com/4741899/205155930-1cc11d36-cbfd-4c53-a28d-537d2190e27f.mp4

I guess the other solution could be to show the skeleton UI we see in the first screenshot uniformly - and show the new IOU and messages together at once?

**Comment by yuwenmemon** [comment] 2022-12-01 22:23
Yep, so here's what happens:

When we load a report, we use [two criteria](https://github.com/Expensify/App/blob/c10d5fb2d5c196986cb614cd2161ee83577ebcba/src/pages/home/ReportScreen.js#L313-L317) for showing the skeleton UI: A call to the internal method `isReportReadyForDisplay()` and the variable `isLoadingInitialReportActions` which looks to make sure that the `reportActions` prop for the ReportScreen has items inside of it.

For the normal flow of loading the report we see these properties change like so when the `reportActions` are finally set in Onyx:
<img width="1585" alt="Screenshot 2022-12-01 at 2 14 18 PM" src="https://user-images.githubusercontent.com/4741899/205171438-7d906543-928d-4bd5-a2a6-f366a509837b.png">

However, when coming from the Request Money flow, we optimistically merge the IOU `reportAction` into Onyx, which means that we end up setting `isLoadingInitialReportActions` to `false`, even though we haven't loaded the bulk of the actual `reportActions` in Onyx:
<img width="1589" alt="Screenshot 2022-12-01 at 2 14 54 PM" src="https://user-images.githubusercontent.com/4741899/205171644-dfeb0df3-2c34-4ec3-bff1-072bcc7d9ec3.png">

**Comment by yuwenmemon** [comment] 2022-12-01 23:10
Okay, so then how to solve... @marcaaron it seems like you've been touching a lot of the logic around this the last month or so. Curious if you have any thoughts?

In an ideal world, I guess we show the skeleton UI _above_ the optimistic IOU. But I'm a bit lost on how we can do that.

**Comment by marcaaron** [comment] 2022-12-02 22:03
This seems very similar to the problem @techievivek is trying to solve in [this PR](https://github.com/Expensify/App/pull/13233)

It deals with what the correct _offline_ behavior should be when we are visiting a chat that we do not have any locally stored comments for yet, but know exists. That feels like a parallel situation to this one because we haven't yet loaded any true `reportActions` from the server, but we have an optimistic action.

So I think (though wouldn't mind hearing @shawnborton's take on this) that the solution for that would be...

**online:** show the skeleton loader before any optimistic comments we're trying to add like 

![2022-12-02_12-00-41](https://user-images.githubusercontent.com/32969087/205397527-bd4770d0-d681-41aa-a956-57cfc46181ff.png)

**offline:** show some kind of temporary inline message that says "[broken cloud] Let's sync up when you get back online." 

![2022-12-02_12-00-41](https://user-images.githubusercontent.com/32969087/205397649-3ed0053e-92f4-4c34-b55c-abb18eb090a1.png)

(but probably something better than that because I am not marketing)

>In an ideal world, I guess we show the skeleton UI above the optimistic IOU. But I'm a bit lost on how we can do that.

Yes, can definitely try to think of some things! Let's figure out what we want first.

**Comment by yuwenmemon** [comment] 2022-12-02 22:48
Lol, great mockups. Yeah, I like that idea! Will wait for @shawnborton's input as well.

**Comment by shawnborton** [comment] 2022-12-03 00:16
The online part makes sense to me. 

For offline, wouldn't the user already have the offline indicator at the bottom of their screen? Maybe we just show skeleton UI but show it in a way that doesn't animate so it doesn't look like anything is going to load?

**Comment by yuwenmemon** [comment] 2022-12-05 19:18
> For offline, wouldn't the user already have the offline indicator at the bottom of their screen?

Correct they will.

> Maybe we just show skeleton UI but show it in a way that doesn't animate so it doesn't look like anything is going to load?

I like that idea. Looks like the SkeletonViewLines has an [animate](https://github.com/Expensify/App/blob/a11ea8a3204f32d03b00f634fc637e5c6a542670/src/components/ReportActionsSkeletonView/SkeletonViewLines.js#L21) property already

**Comment by yuwenmemon** [comment] 2022-12-07 18:55
The idea discussed above is a bit different from what is being worked on in @techievivek's PR [here](https://github.com/Expensify/App/pull/13233), so trying to get on the same page in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1670436579919349).

**Comment by yuwenmemon** [comment] 2022-12-13 00:08
> Yes, can definitely try to think of some things! Let's figure out what we want first.

@marcaaron now that we know what we want - any thoughts on where you would point me to look into first for this? I was initially thinking we would do the logic for showing the skeleton above the optimistic report action in the [ReportScreen](https://github.com/Expensify/App/blob/main/src/pages/home/ReportScreen.js) component. We'll probably have to change some of the logic around [`state.skeletonViewContainerHeight`](https://github.com/Expensify/App/blob/ecb60196794be5acbe835f22f45e5c74c77461b6/src/pages/home/ReportScreen.js#L279-L287) as well.

Although, I also realize that we also render a Skeleton deeper in the [ReportActionsList](https://github.com/Expensify/App/blob/4cc45c4aa5e64c1ea9736dfe0604b4b94e35d0b4/src/pages/home/report/ReportActionsList.js#L164-L166) as well.

**Comment by marcaaron** [comment] 2022-12-15 03:45
Hey @yuwenmemon sorry, I didn't get to reply or look at this today. Lmk if you still need help!

**Comment by yuwenmemon** [comment] 2022-12-15 17:16
Nope, all good! Have a PR up if you're interested but that's it.

**Comment by yuwenmemon** [comment] 2022-12-20 21:25
@maddylewis I believe this was all internal - is anyone getting paid for this in reality?

**Comment by yuwenmemon** [comment] 2022-12-22 17:49
Cool so then I think we can close this out.

**Closed by yuwenmemon** 2022-12-22 17:49 UTC
Labels: Reviewing, Weekly, Internal, Awaiting Payment, Bug
