### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] QBO - "Required" remains enabled when all tags are disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43666] opened 2024-06-13 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/42972
## Action Performed:
Precondition:
- Account is connected to QBO
1. Go to staging.new.expensify.com
2. Go to workspace settings
3. Go to Tags
4. Click Classes
5. Toggle on Required
6. Select all tags
7. Disable all tags

## Expected Result:
"Required" will be disabled and locked when all tags are disabled (same behavior when all categories are disabled)

## Actual Result:
"Required" remains enabled when all tags are disabled

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ffbee882-3d37-4f3e-829a-0d358b45d4e0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4ad944ec831b5b7</li>
        <li>Upwork Job ID: 1801300917150271805</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 102740102</li>
<li>Krishna2323 | Contributor | 102740104</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

**Comment by lanitochka17** [comment] 2024-06-13 15:02
@cead22  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by akinwale** [comment] 2024-06-14 05:48
@Krishna2323's [proposal](https://github.com/Expensify/App/issues/43666#issuecomment-2166495823) works here since it follows the same method of an already existing implementation for categories.

🎀👀🎀 C+ reviewed.

**Comment by mallenexpensify** [comment] 2024-07-30 19:19
Contributor: @Krishna2323 paid $250 via Upwork
Contributor+: @akinwale paid $250 via Upwork. 

@akinwale plz complete the BZ checklist below?

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by akinwale** [comment] 2024-07-30 19:23
> * [x]  [@] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. The specific functionality was not implemented.

> * [x]  [@] Determine if we should create a regression test for this bug.
> * [x]  [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
_Precondition: Account is connected to QBO_

1. Launch Expensify.
2. Navigate to the settings for the workspace connected to QBO.
3. Navigate to Tags.
4. Toggle the Required switch.
5. Select all tags.
6. Disable all tags.
7. Verify that the "Required" switch is disabled and locked when all tags are disabled.

Do we agree 👍 or 👎?

**Comment by mallenexpensify** [comment] 2024-07-30 21:01
Thanks @akinwale , test case created! 
https://github.com/Expensify/Expensify/issues/416507

**Closed by mallenexpensify** 2024-07-30 21:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment
