### ISSUE TITLE
[HOLD for payment 2024-03-20] [HelpDot] Link this issue to auto assign Rushat for a review.

### ISSUE THREAD

**Issue by rushatgabhane** [Expensify/App#36581] opened 2024-02-15 13:24 UTC
When creating a PR, link this issue so that I'm auto assigned for a review.

**Comment by rushatgabhane** [comment] 2024-02-15 13:25
@lschurr you may unassign to avoid pings

**Comment by rushatgabhane** [comment] 2024-02-26 16:10
@maddylewis could you please assign me this issue

**Comment by garrettmknight** [comment] 2024-03-22 19:08
@JmillsExpensify I think payment happens in the separate payment issues and the automation is incorrect here.

**Comment by garrettmknight** [comment] 2024-03-22 19:11
Checking what's going on with this on in [slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1711134702809349)

**Comment by rushatgabhane** [comment] 2024-03-22 19:14
@garrettmknight this is the issue for payment - https://github.com/Expensify/App/issues/32825
It has the necessary payment details

**Comment by rushatgabhane** [comment] 2024-03-22 19:17
This issue is created only for the purpose of auto-assigning me for reviews.

**Comment by JmillsExpensify** [comment] 2024-03-24 02:42
Ok cool. I'm going to close this issue then.

**Closed by JmillsExpensify** 2024-03-24 02:42 UTC
Labels: Reviewing, Weekly, Awaiting Payment, Bug

**Comment by amyevans** [comment] 2024-05-21 21:38
I think I'm getting all PR reviews assigned me to because I am assigned on this GH 🤔. That isn't _necessarily_ a problem, but I do think it'd be better to round-robin the reviews via PullerBear so I'm going to unassign.

**Comment by rushatgabhane** [comment] 2024-05-21 21:42
@amyevans could you please reopen the issue

**Comment by amyevans** [comment] 2024-05-21 21:53
Why can't it rely on PullerBear? 😄

**Comment by rushatgabhane** [comment] 2024-05-21 21:57
does it work on closed issues?

**Comment by amyevans** [comment] 2024-05-21 22:33
I think it will just assign a random internal engineer on the PR review (according to PullerBear logic, which is based on lowest number of reviews), but if it ends up not working we can reassess!

**Comment by dangrous** [comment] 2024-08-02 18:59
not a bug, no checklist needed. 

Is this issue complete? It is not showing up in my K2; I just got an email about it to check in.

I think the Expensify Help stuff is still going on, right?
