### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] LHN:  Emoji is misaligned with message 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41367] opened 2024-04-30 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.68-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714492986409729

## Action Performed:
1. Send a message with emoji from A to B
2. Login as B and observe the LHN
## Expected Result:
There is no misalignment with emoji
## Actual Result:
Emoji is misaliged
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/38435837/e7587913-c4d5-41cd-a541-e2af690cca94" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/38435837/7b2f2d40-ce71-4874-a2d9-2944cc214273" width="40%" height="40%">
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d8085509ba977455</li>
        <li>Upwork Job ID: 1785441141151866880</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>samilabud | Contributor | 0</li>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @isabelastisser</details>

**Comment by samilabud** [comment] 2024-05-01 04:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN: Emoji is misaligned with message in focus mode

### What is the root cause of that problem?
When we are in focus mode we are showing the content of each conversation in the same line, this makes the content try to fit but we are also adding an unnecessary line height and min height which cause the misalignement.

### What changes do you think we should make in order to solve the problem?
We should remove the line height and min height when user is in focus mode from [OptionRowLHN component](https://github.com/Expensify/App/blob/57d2aee42ecc04d196cb3f86730b30415969836c/src/components/LHNOptionsList/OptionRowLHN.tsx#L65), like:
```
const alternateTextStyle = isInFocusMode
        ? [textStyle, styles.textLabelSupporting, styles.optionAlternateTextCompact, styles.ml2, style]
        : [textStyle, styles.optionAlternateText, styles.textLabelSupporting, style];
```
Testing the change in IOS:

https://github.com/Expensify/App/assets/5216036/1d03faa1-07ca-4952-a817-4dffbe1c0c7a

Testing in other platforms:
Android Chrome:
<img width="385" alt="Android Chrome" src="https://github.com/Expensify/App/assets/5216036/5d74b244-de95-49cd-a446-7a59f730d16d">
Android:
<img width="385" alt="Android" src="https://github.com/Expensify/App/assets/5216036/ff64c209-9272-4afe-b9fa-8a7289237943">
IOS Safari:
<img width="359" alt="IOS Safari" src="https://github.com/Expensify/App/assets/5216036/fbf4412d-1868-4e57-9d25-bc6102473e92">
Mac Chrome:
<img width="1126" alt="MAC Chrome test" src="https://github.com/Expensify/App/assets/5216036/7661b4c1-d2b6-45c3-a401-75c9662ee336">

**Comment by kaushiktd** [comment] 2024-05-01 09:42
### Please re-state the problem that we are trying to solve in this issue.
LHN: Emoji is misaligned with message in focus mode

### What is the root cause of that problem?
Currently, we've observed that emojis within the LHN can appear misaligned when users are in focus mode. This misalignment not only affects the visual consistency of the interface but also may lead to usability issues, particularly for users who rely on visual cues for navigation.

### What changes do you think we should make in order to solve the problem?
adjusting the lineHeight property from its current value to a slightly larger value. By increasing the lineHeight, we ensure that there is adequate vertical spacing between lines of text, including emojis, thereby improving their alignment within the LHN.
https://github.com/Expensify/App/blob/57d2aee42ecc04d196cb3f86730b30415969836c/src/styles/index.ts#L1832
we can use this

` lineHeight: variables.lineHeightXXXLarge,`

ScreenShot:-
![image](https://github.com/Expensify/App/assets/43398804/7d87c192-72e1-4e76-9093-091b62829b10)

**Comment by isabelastisser** [comment] 2024-05-01 14:15
@mananjadhav, please review the proposals above. Thanks!

**Comment by shawnborton** [comment] 2024-05-01 20:11
Hmm I would think the emoji should just have the same line height as the text that is next to it, no?

**Comment by dubielzyk-expensify** [comment] 2024-05-02 03:30
Yeah I also assumed that would fix the issue

**Comment by samilabud** [comment] 2024-05-02 13:19
Hi @shawnborton and @dubielzyk-expensify,
 
It would be good to know what the target is, because it looks like the one reported here is for this misalignment:

<img width="191" alt="image" src="https://github.com/Expensify/App/assets/5216036/a9fad158-2f62-4c88-ba22-cce4cc3c7d48">

After my proposal I put all the content text in the same line height:

<img width="234" alt="image" src="https://github.com/Expensify/App/assets/5216036/7e07988b-0dfa-4219-a211-84544097994f">

Even in gmail emoticons can cause the effect of needing more line height depending on which one it is, see this:
<img width="475" alt="image" src="https://github.com/Expensify/App/assets/5216036/2f1de541-d85b-4096-9ca4-1fa66febcd8c">

Also even here in github (I think this should be the correct alignment):
Hello 🏰

This is not noticeable in emoticons such as 😄:
Hello 😄 
Hello 🏰😄

**Comment by kaushiktd** [comment] 2024-05-02 14:01
@shawnborton raises an important consideration regarding the alignment of emojis with adjacent text. While initially, both text height and lineHeight were set to the same values, we encountered issues with misalignment. Despite having the same line height as the adjacent text, emojis may still appear misaligned due to variations in rendering, inherent size differences, and platform-specific rendering behaviors.

**Comment by shawnborton** [comment] 2024-05-02 14:45
I agree that this one is the correct alignment I would expect - and it looks like the emoji is not getting any special kind of line height or anything like that, it just follows whatever is being applied on the `p` element:
![CleanShot 2024-05-02 at 10 45 06@2x](https://github.com/Expensify/App/assets/2319350/d728fa32-e2d9-4810-88f0-3a9a3c2f0b7d)

**Comment by isabelastisser** [comment] 2024-05-07 14:11
@mananjadhav, can you please provide an update? Thanks!

**Comment by isabelastisser** [comment] 2024-05-07 14:13
Not overdue.

**Comment by isabelastisser** [comment] 2024-05-07 19:17
Waiting for @mananjadhav to update.

**Comment by mananjadhav** [comment] 2024-05-07 19:20
I don't see any proposals that solve this in an accurate way. I agree that Emojis being rendered different on platforms, apps and devices. But if the expectation is that the emoji should pick the line height of the given`<p>` tag, we are looking at proposals to solve this instead of updating the line height for generic style.

**Comment by samilabud** [comment] 2024-05-07 19:30
Hi @mananjadhav, is there any visual example of how this should look like, it could be from another platform just to get an idea.

**Comment by mananjadhav** [comment] 2024-05-08 17:16
@samilabud It's added [here](https://github.com/Expensify/App/issues/41367#issuecomment-2090693846) in the previous comment.

**Comment by samilabud** [comment] 2024-05-08 17:24
> @samilabud It's added [here](https://github.com/Expensify/App/issues/41367#issuecomment-2090693846) in the previous comment.

Got it, I think that was added based on my proposal, isn't it?

**Comment by isabelastisser** [comment] 2024-05-13 18:47
@mananjadhav, can you please provide an update? Thanks!

**Comment by mananjadhav** [comment] 2024-05-13 18:54
I think I am going to reassign this one.

**Comment by mananjadhav** [comment] 2024-05-13 19:19
@ikevin127 is taking this over.

**Comment by ikevin127** [comment] 2024-05-13 19:24
> can you please provide an update? Thanks!

I will review proposals today and provide an update by EOD (PST timezone).

**Comment by ikevin127** [comment] 2024-05-13 23:29
@kaushiktd Your RCA does not clearly state the root cause of the issue, instead it's more of an observation. As for the proposed solution I agree with https://github.com/Expensify/App/issues/41367#issuecomment-2089054405, that we sould not change the global `styles.optionAlternateText` style as this could lead to regressions across the app in all the other 6 components where the style is used.

**Comment by ikevin127** [comment] 2024-05-13 23:31
@samilabud's [proposal](https://github.com/Expensify/App/issues/41367#issuecomment-2087951179) looks good to me and tests well.

The **RCA** is correct in the sense that for `isInFocusMode` true we're adding the same `styles.optionAlternateText` as for the most recent mode (not focus mode).
Based on my tests, the proposed **solution** of removing the `styles.optionAlternateText` styles only for `isInFocusMode` true seems to fix the issue on iOS: Native (see diff screenshots below) based on design team input [here](https://github.com/Expensify/App/issues/41367#issuecomment-2090693846), and it does not seem to affect the UI on any of the other platforms when `isInFocusMode` is true.

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <img src="https://github.com/Expensify/App/assets/56457735/83571c5e-441c-4f2d-a249-71d2573cc725"/> | <img src="https://github.com/Expensify/App/assets/56457735/11675fa1-52d1-4858-87a5-1661088c1519"/> |

</details>

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-05-14 19:57
@tgolen @isabelastisser Can any of you help with assignment for me as reviewer ? I need this for both the issue and PR https://github.com/Expensify/App/pull/42162 (reviewer was auto-assigned already).

**Comment by samilabud** [comment] 2024-05-15 00:05
> @samilabud Is PR ready for review ?

Yes it is

**Comment by ikevin127** [comment] 2024-05-15 00:11
@tgolen Can you please also remove the auto-assigned reviewer from the PR https://github.com/Expensify/App/pull/42162 and add me so I can start working on the checklist ?

**Comment by tgolen** [comment] 2024-05-15 12:39
Done!

**Comment by isabelastisser** [comment] 2024-06-04 00:36
The payments were processed in Upwork. All set!

**Closed by isabelastisser** 2024-06-04 00:36 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
