### ISSUE TITLE
[$500] IOU - There is no violation in the IOU details

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36951] opened 2024-02-20 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue  found when executing PR** https://github.com/Expensify/App/pull/34983
## Action Performed:
Preconditions: Create a collect policy in OD. Enable the workspace chat. Enable "Must use tags" and "Multi level tags". Import the attached csv. Invite a member
1. Log in with the member
2. Open the workspace chat
3. Create a manual IOU without using any of the tags
4. Open the IOU details

## Expected Result:
There should be only 1 "Required" text as you only have to use one tag
You should be getting a violation

## Actual Result:
All of the multi level tags have the "Required" text next to them
There is no violation in the IOU details if you open it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

**https://github.com/Expensify/App/assets/78819774/ae765859-1d56-4e23-b054-71c1f9ff3bd9**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c63e2b36821bb55</li>
        <li>Upwork Job ID: 1760050849869365248</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by wildan-m** [comment] 2024-02-21 03:27
> Import the attached csv.

Which one?

**Comment by wildan-m** [comment] 2024-02-21 07:56
The problem is not reproducible; also, the "must use tags" option disappears when we enable multiple tags and refresh the page.
<img width="1365" alt="image" src="https://github.com/Expensify/App/assets/11847279/e4e354dc-6d23-41d9-a023-1765d90e87c2">

**Comment by chiragsalian** [comment] 2024-02-21 23:33
@lanitochka17, can you retest and confirm if the issue still persists?

**Comment by chiragsalian** [comment] 2024-02-21 23:52
> > Import the attached csv.

> Which one?

I think its the one linked in this 
> Issue found when executing PR https://github.com/Expensify/App/pull/34983

So this one,
> - You can import an [attached collection](https://github.com/Expensify/App/files/14099562/Multiple_levels_of_tags_tags.csv) of multiple levels of tags.

**Comment by lanitochka17** [comment] 2024-02-22 17:47
Issue is not reproduced in the latest build 1.4.43-12


https://github.com/Expensify/App/assets/78819774/2babe832-ae5b-409e-a0b8-392753877170

**Comment by chiragsalian** [comment] 2024-02-22 18:55
Cool, closing this issue since its not reproducible.

**Closed by chiragsalian** 2024-02-22 18:55 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted
