### ISSUE TITLE
Workspace - Unable to delete workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39294] opened 2024-03-29 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.58-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Sign in with a regular Gmail account
2. Create a workspace
3. Delete the workspace

## Expected Result:
Workspace should be deleted

## Actual Result:
You can't delete your workspace error message is displayed

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/b6ccf7cd-89d5-4701-8fe2-46fa2ea394e7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-03-29 21:04
We think that this bug might be related to #wave-collect - Release 1

**Comment by neil-marcellini** [comment] 2024-03-29 23:31
I'm able to reproduce the issue. I'm pretty sure it's a backend problem, so I'm going to make another internal issue referencing this one.

**Comment by neil-marcellini** [comment] 2024-03-29 23:38
Actually IDK, I think the error message makes sense that we don't allow you to delete a collect workspace. So it seems like we just didn't think it through after changing NewDot to create collect workspaces. Asking in Slack.

**Comment by neil-marcellini** [comment] 2024-04-01 17:37
Assigning to Tim as he [requested in Slack here](https://expensify.slack.com/archives/C036QM0SLJK/p1711769954190539?thread_ts=1711755683.331809&cid=C036QM0SLJK)

**Comment by tgolen** [comment] 2024-04-01 19:53
I'm also asking about it [in Slack](https://expensify.slack.com/archives/C036QM0SLJK/p1712001188718719) 😁

**Comment by tgolen** [comment] 2024-04-01 19:54
I think for now, this doesn't need to be a deploy blocker, so I am going to remove the label.

**Comment by tgolen** [comment] 2024-04-01 20:24
I'm having trouble reproducing this. I think that it might only happen once you've begun paying for a policy. If you delete the policy during the free-trial period, deleting it works OK.

Since subscription management is coming soon (see #368528), I'm just going to close this.

**Comment by lanitochka17** [comment] 2024-06-10 17:23
Issue is still reproducible on the latest build 1.4.81-4

https://github.com/Expensify/App/assets/78819774/98ff6f10-af91-409e-bbbf-48220d92760a

**Closed** 2024-06-10 17:25 UTC
Labels: Engineering, Hourly
