### ISSUE TITLE
[$500] Default category set for distance expense in a policy does not auto populate when creating expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34448] opened 2024-01-12 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705010484215319

## Action Performed:
1. Set a default currency for distance expense in olddot
2. Invite member B to the account in OD
3. Open the workspace chat in ND as. a member B
4. Create a distance expense
5. Observe the confirmation page

## Expected Result:
Default currency should be auto populated

## Actual Result:
Not auto populated. Only after creating the expense category is set

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/8f805094-e00c-4b53-a53f-a0ee83dbb7e9

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164f6cd9ebd57caa6</li>
        <li>Upwork Job ID: 1745836097956413440</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-12 16:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default category set for distance expense in a policy does not auto populate when creating expense

### What is the root cause of that problem?
We are only displaying category if it exists in the transaction here
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L786-L787
### What changes do you think we should make in order to solve the problem?

We should display the default category checking the workspace participant has default category set.
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-12 16:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a default Distance category is set for the workspace, it should be visible on the Confirmation step as well.

### What is the root cause of that problem?
We have not yet implemented the `defaultCategory` handling for the Distance requests. We only show the transaction.category on the Category field, and for the distance requests it's not set.

### What changes do you think we should make in order to solve the problem?
**First**, we should fetch the distance-specific default category. It is located under the `policy.customUnits[].defaultCategory`.

We can add it as an util function to the `DistanceRequestUtils` similar to the `getDefaultMileageRate`:

```js
function getDefaultCategory(policy: OnyxEntry<Policy>): string | null {
    if (!policy?.customUnits) {
        return null;
    }

    const distanceUnit = Object.values(policy.customUnits).find((unit) => unit.name === CONST.CUSTOM_UNITS.NAME_DISTANCE);
    return distanceUnit?.defaultCategory;
}
```

Then, we should handle this default category similar to how we handle the tax rates: if it's not present on the transaction, use the default one on the Confirmation Step:

https://github.com/Expensify/App/blob/076f03e62c0c339cccbcbd687644857d832242d0/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L295-L297

And on the Category Selection step to mark the default category as selected:

https://github.com/Expensify/App/blob/72693dc25bdf4e345026933e21273d9df901e250/src/pages/iou/request/step/IOURequestStepTaxRatePage.js#L57-L59

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2024-01-12 16:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Default category isn't set for the distance transaction whereas it is set in the policy

### What is the root cause of that problem?
Currenty, we are not fetching and setting the default category from the policy for the transaction in `IOURequestStepConfirmation` component.

### What changes do you think we should make in order to solve the problem?
Consider fetching the `customUnits` from the policy for the distance unit, if it is available take default category and set it to the transaction. We need to set it to the transaction so when user opens category picker the default option gets selected.

```
const distanceCustomUnit = _.find(lodashGet(policy, 'customUnits', {}), (unit) => unit.name === CONST.CUSTOM_UNITS.NAME_DISTANCE);
if(distanceCustomUnit) {
    IOU.setMoneyRequestCategory_temporaryForRefactor(transactionID, distanceCustomUnit.defaultCategory);
}
```

**Comment by isabelastisser** [comment] 2024-01-12 18:27
Hey @c3024, can you please review the proposals above? Thanks!

**Comment by c3024** [comment] 2024-01-16 17:36
Will update today

**Comment by isabelastisser** [comment] 2024-01-17 18:16
Hey @c3024, did you have the chance to review the proposals? Thanks!

**Comment by c3024** [comment] 2024-01-18 13:44
Thank you for all your proposals.

I think setting the category in the transaction is the best solution. It updates the category picker page as well correctly.

@Pujan92 's [proposal here](https://github.com/Expensify/App/issues/34448#issuecomment-1889608246) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by isabelastisser** [comment] 2024-01-18 17:39
Thanks for the heads up, @dukenv0307 ! Closing this issue then.

**Closed by isabelastisser** 2024-01-18 17:39 UTC
Labels: External, Daily, Help Wanted, Bug
