### ISSUE TITLE
IOS - Can't play videos or download videos in any format

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8923] opened 2022-05-10 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue was found when executing PR:** https://github.com/Expensify/App/pull/7849

## Action Performed:
1. Open App
2. Login any user in which you have videos upload
3. Go to any chat with the video attachment on the iOS native app
4. Click on the download icon on the right of the attachment view

## Expected Result:
The preview of the video should be shown and you can download it

## Actual Result:
The video preview is not shown and cannot be downloaded

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.57.12

**Reproducible in staging?:** Yes

**Reproducible in production?:** No/Yes (in production the preview of the video is not shown but it can be downloaded)

**Email or phone of affected tester (no customers):** utester29+1@gmail.com/Epa12345678

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/167690497-85951332-3dd9-4276-8e23-cc1daf73bb61.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Justicea83** [comment] 2022-05-11 10:34
Can we make this an external issue?

**Comment by thienlnam** [comment] 2022-05-12 00:40
I believe this was also a regression from https://github.com/Expensify/App/issues/7909, I have a revert up for it here: https://github.com/Expensify/App/issues/7909

**Comment by thienlnam** [comment] 2022-05-16 23:44
Is this still reproducible @kbecciv?

**Comment by kbecciv** [comment] 2022-05-19 11:40
@thienlnam Yes. Issue is still reproduced on last QA Regression.

**Comment by thienlnam** [comment] 2022-05-25 18:02
Back from OOO, will look into this later today

**Comment by thienlnam** [comment] 2022-05-25 22:05
I don't think we ever had the functionality to view videos inside the app / it always needed to be downloaded.  Going to close this since it works as expected now (shows as attachment and can be downloaded)

**Closed by thienlnam** 2022-05-25 22:05 UTC
Labels: Engineering, Daily

**Comment by mallenexpensify** [comment] 2022-05-26 18:00
We have this issue
https://github.com/Expensify/App/issues/7835
I imagine that's cover iOS too
