### ISSUE TITLE
[Action 22 Jan] Budget - Missing "for" word in workspace budget message in #admin room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33773] opened 2023-12-29 18:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an admin of Control workspace
- The Control workspace has a category that is set up with a budget
Old Dot
1. Create expenses with category that has a budget and add them to the report until the total amount exceeds the workspace threshold
2. Submit and final approve the report
3. Create another report with some expenses with the same category
4. Submit the report without approving it
5. Create another report with some expenses with the same category
6. Leave this report in the open state
New Dot
1. Navigate to #admin room of the Control workspace

## Expected Result:
The message in #admin shows "This workspace has a $[individual budget amount] per person per month *for* Advertising.."

## Actual Result:
The message in #admin shows "This workspace has a $[individual budget amount] per person per month Advertising..".
"for" is missing in the sentence

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6328544_1703869425820!Screenshot_2023-12-29_at_19 40 20](https://github.com/Expensify/App/assets/78819774/adb0f3d7-372a-4d75-b58c-fb831962a9b3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179a33322f31d5c48</li>
        <li>Upwork Job ID: 1740798848503259136</li>
        <li>Last Price Increase: 2023-12-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by laurenreidexpensify** [comment] 2024-01-02 12:39
This looks like a straight copy update, so I'll get a PR up for it this week

**Comment by MonilBhavsar** [comment] 2024-01-03 05:25
@laurenreidexpensify thank you! Happy to review a PR
Just flagging this copy was reviewed here by Marketing team https://github.com/Expensify/Expensify/issues/353253

**Comment by laurenreidexpensify** [comment] 2024-01-03 11:36
@NickTooker as you did the copy review in https://github.com/Expensify/Expensify/issues/353253 can you confirm we should update this to the suggestion above. I agree that it reads much smoother with "for" in it, so I'm a 👍🏽 for this change

**Comment by laurenreidexpensify** [comment] 2024-01-08 13:44
@NickTooker bump please confirm so I can get a PR up for this thanks

**Comment by NickTooker** [comment] 2024-01-08 17:20
@laurenreidexpensify Sorry, I did not see this! 

I am fine inserting the "for" into the sentence.  Thumbs up from me - good to go. 👍

**Comment by laurenreidexpensify** [comment] 2024-01-09 10:09
Perfect thanks, I will work on this PR later  this week

**Comment by laurenreidexpensify** [comment] 2024-01-09 10:24
This is a backend change on Expensify/Expensify so removing C+

**Comment by MonilBhavsar** [comment] 2024-01-11 12:43
A note: PR is merged. Once deployed we need to update regression tests here https://expensify.testrail.io/index.php?/suites/view/7722&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296768

**Comment by laurenreidexpensify** [comment] 2024-01-18 13:04
Went on prod 15 Jan - so let's add regression test on 22 Jan

**Comment by laurenreidexpensify** [comment] 2024-01-22 12:12
Submitted request for updating TestRail - closing

**Closed by laurenreidexpensify** 2024-01-22 12:12 UTC
Labels: Reviewing, Weekly, Internal, Bug
