### ISSUE TITLE
[$1000] Web - Back button after page reload does not work properly on profile page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22887] opened 2023-07-14 11:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new a group and invite someone
2. Click header to open details page
3. Click one of row
4. Click back button, Observe the correct back to the details page
5. Click one row again
6. Reload page
7. Click back button, observed back to home

## Expected Result:
After reloading the page, pressing the back button still goes back to the details page

## Actual Result:
After reloading the page, pressing the back button goes back to home

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7194f731-97d0-4608-97ec-4af88c930582

https://github.com/Expensify/App/assets/93399543/4f86a746-f27b-4e88-839c-3f656cba468e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689267806742509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebbd66fe602e6683</li>
        <li>Upwork Job ID: 1681048622962212864</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-07-14 20:00
This is definitely reproducible, and I can't find a dupe. i don't see this issue if I use my browser's back button though 🤷‍♀️

**Comment by ygshbht** [comment] 2023-07-14 20:27
@adelekennedy I agree with your observation that the browser's back button doesn't reproduce the issue. This detail helps highlight the discrepancy between the app's and browser's back button behaviors.

**Comment by ygshbht** [comment] 2023-07-14 20:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the current application, after reloading the profile page, clicking the back button navigates the user to the home screen instead of the previous participants details page. This issue is due to the app not considering the originating route when navigating back from the `ProfilePage`, and using a default fallback route to the _home screen_.

### What is the root cause of that problem?
The root cause of this issue is the limited flexibility of the back navigation logic in the `ProfilePage `component. The back button's action is designed to fall back to the `ROUTES.HOME` screen if there isn't any previous screen in the React Navigation stack.

The existing back navigation code is as follows:

```
<HeaderWithBackButton
    title={props.translate('common.profile')}
    onBackButtonPress={() => Navigation.goBack(ROUTES.HOME)}
/>
```

This issue arises when the app is reloaded on the `ProfilePage` without navigating from the Participants page first. As a result, there's no record of the previous screen in the React Navigation stack, leading the app to default to the home screen.

### What changes do you think we should make in order to solve the problem?
To solve this problem, we can introduce a new property **fallbackRoute** that can be passed to the `ProfilePage `component. This prop would specify the route to navigate to when the back button is pressed if there's no previous route in the navigation stack.

The back navigation code would be updated as follows:

```
<HeaderWithBackButton
    title={props.translate('common.profile')}
    onBackButtonPress={() => Navigation.goBack(props.fallbackRoute || ROUTES.HOME)}
/>
```

In the `ReportParticipantsModalStackNavigator `component of the `ModalStackNavigators` page, the code would be modified as follows:

```
{
    getComponent: () => {
        const ProfilePage = require('../../../pages/ProfilePage').default;
        const WrappedComponent = React.forwardRef((props, ref) => {
            return (
                <ProfilePage
                    ref={ref}
                    {...props}
                    fallbackRoute={ROUTES.getReportParticipantsRoute(props.route.params.reportID)}
                />
            );
        });
        return WrappedComponent;
    },
}
```

Original code:
```
{
        getComponent: () => {
            const ProfilePage = require('../../../pages/ProfilePage').default;
            return ProfilePage;
        },
        name: 'Profile_Root',
},
```

This change ensures that if a user is on the `ProfilePage `and reloads the application, the back button will correctly navigate back to the last visited page.

**Comment by adelekennedy** [comment] 2023-07-17 21:10
Moving this to external

**Comment by s77rt** [comment] 2023-07-18 17:19
@adelekennedy Looks like a dupe of https://github.com/Expensify/App/issues/22041 (same root cause). Let's close this.

**Comment by greg-schroeder** [comment] 2023-07-19 10:08
Can we take a look at https://github.com/Expensify/App/issues/23036 as well? should we consolidate these?

**Comment by s77rt** [comment] 2023-07-19 13:07
@greg-schroeder Yes but the previous reported issue was closed. I'm not sure if we should start fixing those issues or not.

**Comment by s77rt** [comment] 2023-07-22 00:25
Not overdue. This is a dupe. We should probably close this one and reopen the first one (if needed).

**Comment by greg-schroeder** [comment] 2023-07-22 03:52
Okay then. 👍

**Closed by greg-schroeder** 2023-07-22 03:52 UTC
Labels: External, Daily, Help Wanted, Bug
