### ISSUE TITLE
Chat - Concierge chat is opened after clicking invalid chat red dot

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18838] opened 2023-05-12 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in with the same account in the main testing device and a secondary device
2. Disable the internet connection in the main testing device
3. In the secondary device Split a bill with 2 users, this should create a new group and 2 new 1:1 conversations
4. In the main testing device (should be offline) create the SAME split bill with the 2 users
5. Enable the internet connection in the main testing device. The split bill request will be sent and you will get an error in the main device only.
6. Duplicated chats are display in the LHN
7. Click into the any of the duplicate chats that have a red dot
8. Click X to close error message (the one that closes chat)

## Expected Result:
LHN should be displayed.

## Actual Result:
Concierge chat is displayed across all platforms.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/25cf972a-5578-42ae-b0b0-8d8d0f3e5227

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by therealsujitk** [comment] 2023-05-12 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When a report is deleted due to an error, we are navigated to Concierge instead of displaying the LHN (smaller screens).

### What is the root cause of that problem?

This is intended behaviour, when an error occurs a function is called to delete the report and navigate to concierge (`navigateToConciergeChatAndDeleteReport()`). This is done in the code shown below (attribute: `onClose`).

https://github.com/Expensify/App/blob/1de10c2e9fcbc1ca90e358e1afabef2d6b363979/src/pages/home/report/ReportActionItemCreated.js#L46-L51

### What changes do you think we should make in order to solve the problem?


To change this behaviour, we can simply navigate home (Open the drawer) after navigating to Concierge.

```js
function navigateToConciergeChatAndDeleteReport(reportID) {
    navigateToConciergeChat();
    deleteReport(reportID);
    Navigation.navigate(ROUTES.HOME);   // This was added
}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by hungvu193** [comment] 2023-05-14 16:53
I believe this one is intentional, not a bug.

**Comment by therealsujitk** [comment] 2023-05-14 17:06
@hungvu193 it is intentional, but it looks odd on smaller screens when the user is navigation to Concierge instead of the drawer.

**Comment by kadiealexander** [comment] 2023-05-15 03:27
I'm going to close this as it is not a bug. If you want to make a new feature request in #expensify-bugs @therealsujitk, by all means go ahead! I think it would be better to recommend this as a new feature and discuss with the team whether this intended behaviour should change. :)

**Closed by kadiealexander** 2023-05-15 03:27 UTC
Labels: Daily, Overdue, Bug
