### ISSUE TITLE
Chat - Mentions pop-up doesn't disappear after sending message if none of options selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20859] opened 2023-06-15 20:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open report
2. Click on Compose box
3. Type message with any mention, f.e. Hello @here
4. Click Send message icon (without selection any option from mentions pop-up)

## Expected Result:
Mentions pop-up should disappear

## Actual Result:
Mentions pop-up doesn't disappear and hides the send message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/93e8a7ac-3926-4ce3-b9c9-dc6ba5169924

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-06-15 21:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mentions pop-up doesn't disappear after sending message if none of options selected

### What is the root cause of that problem?
We are not resetting the suggestions on send message.

### What changes do you think we should make in order to solve the problem?
We can add a function call `this.resetSuggestions()` here within `prepareCommentAndResetComposer` which will reset the suggestions on send message.

https://github.com/Expensify/App/blob/38fe17f8a299692966777a53f1b305419d8384c2/src/pages/home/report/ReportActionCompose.js#L839-L840

**Comment by zanyrenney** [comment] 2023-06-19 17:13
Closing in favour of the older dupe posted above by @dukenv0307 - thanks!

**Closed by zanyrenney** 2023-06-19 17:14 UTC
Labels: Daily, Overdue, Bug
