### ISSUE TITLE
[HOLD for payment on 2022-12-06] [$250]  BUG:  "Unavailable workspace" archived appears in the LHN after deleting a workspace reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11895] opened 2022-10-16 20:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new workspace
2. Go to settings > workspace
3. Click on three vertical dots
4. Click on Delete workspace
5. Click on Delete to confirm
6. Go back to chats

## Expected Result:
Workspace deletes without any message in the LHN or should appear with name of the workspace deleted

## Actual Result:
Workspace deletes with a new room named "Unavailable workspace"

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196057718-ad247bee-f2ad-449c-99bd-7f51a14ab88b.mp4

https://user-images.githubusercontent.com/43996225/196057727-2102c840-fdc8-4eb5-9fb9-3f0f6ca8a9b5.mov

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @adeel0202
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665938294791939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by abekkala** [comment] 2022-10-19 14:18
I was able to to recreate the same outcome.

**Comment by abekkala** [comment] 2022-10-21 19:07
https://www.upwork.com/jobs/~016adeac1fdb2fad89

**Comment by bernhardoj** [comment] 2022-10-25 11:54
### **Proposal**

The chat name comes from `ReportUtils.getPolicyName`. We can add a check whether it's an archived room or not and return it's `oldPolicyName` if it's an archived room.

**_ReportUtils.js_**
```diff
function getPolicyName(report, policies) {
+    if (isArchivedRoom(report)) {
+        return report.oldPolicyName
+    }
    
    if (_.isEmpty(policies)) {
        return Localize.translateLocal('workspace.common.unavailable');
    }

    const policy = policies[`${ONYXKEYS.COLLECTION.POLICY}${report.policyID}`];
    if (!policy) {
        return Localize.translateLocal('workspace.common.unavailable');
    }

    return policy.name
        || report.oldPolicyName
        || Localize.translateLocal('workspace.common.unavailable');
}
```

**Comment by Santhosh-Sellavel** [comment] 2022-10-25 14:26
@AndrewGable What's the expected OP here?

**Comment by AndrewGable** [comment] 2022-10-27 00:54
Good question - I think you should bring this question to Slack to get confirmation, I am unsure and would like to have a discussion.

**Comment by Santhosh-Sellavel** [comment] 2022-10-30 20:54
Maybe I misread this one earlier, I think this should be internal.  

Reason,
Here `unavailable workspace` chat is created when every workspace is created. But it's not shown for all users, only for users are BETA.

It's not shown when created but shown after deleting for users without BETA Access.

**Comment by AndrewGable** [comment] 2022-11-01 22:58
I'm fine making it internal, but just curious why you think beta == internal? We can whitelist users, but maybe you've been told otherwise?

**Comment by Santhosh-Sellavel** [comment] 2022-11-04 13:17
Ah missed this, I was told this wouldn't work if we are not part of Beta. 
Workspace Chat would show only for users with BETA, So I am not sure it can be fixed externally.

**Comment by abekkala** [comment] 2022-11-07 12:24
@AndrewGable which way do you want to go with this? Do you want internal or whitelist?

**Comment by AndrewGable** [comment] 2022-11-07 21:35
We can make it internal due to beta 👍

**Comment by neil-marcellini** [comment] 2022-11-09 16:50
I'm going to remove help wanted since it's an internal demolition issue. I found this while looking for WAQ bugs to work on.

**Comment by abekkala** [comment] 2022-11-09 20:18
oh yeah, thanks for noticing that @neil-marcellini !

**Comment by MariaHCD** [comment] 2022-11-10 13:15
Not sure about the expected behavior when an admin deletes a workspace. From [this refactor PR](https://github.com/Expensify/App/pull/10491), I see that the workspace chats are archived but still shown in the LHN.

Asked in Slack here: https://expensify.slack.com/archives/C03TQ48KC/p1668086036201419

**Comment by MariaHCD** [comment] 2022-11-14 09:45
Based on [this comment](https://expensify.slack.com/archives/C03TQ48KC/p1668125179264449?thread_ts=1668086036.201419&cid=C03TQ48KC), it might be that there is a mismatch between the optimistic data set in the frontend and the Onyx data set via the API. Looking into it further.

**Comment by MariaHCD** [comment] 2022-11-21 10:12
Looking into the issue this week

**Comment by MariaHCD** [comment] 2022-11-24 14:02
The PR is out for review: https://github.com/Expensify/App/pull/12993

**Comment by abekkala** [comment] 2022-11-30 14:41
@MariaHCD I see that this went into production last night. 
Can this be closed now? 
Is it correct that there are only two payments needed: $250 reporting bonus to Adeel and then $250 to Santosh for reviewing PR?

**Comment by MariaHCD** [comment] 2022-11-30 17:13
@abekkala Sounds correct to me. I think this is now subject to the 7-day regression period.

**Comment by Santhosh-Sellavel** [comment] 2022-11-30 17:36
@abekkala 

I believe Flat $1000 Internal PR Reviews refer [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668726522584349) thanks!

cc: @MariaHCD

**Comment by abekkala** [comment] 2022-11-30 19:01
I do see via that update:
 **there is one small tweak for the C+ team for internal issues -- you’ll be issued a flat $1000 bounty for your PR review.**

I'd like to confirm if that's retro-active for GH's that were **already in place** or only for **new** ones created after the updated rate went into effect.

**Comment by abekkala** [comment] 2022-12-06 19:50
reporting bonus has been sent to Adeel 🎉 

PR reviewing bonus contract has been sent to @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2022-12-06 19:57
Thanks accepted @abekkala!

**Comment by abekkala** [comment] 2022-12-06 20:00
Done! @Santhosh-Sellavel has been paid 🎉 

We're all set here - closing! 
Thank you!

**Closed by abekkala** 2022-12-06 20:00 UTC
Labels: Reviewing, Engineering, Daily, Demolition, Internal, Bug
