### ISSUE TITLE
[HOLD for payment 2024-06-28] [$250] Task - Checkmark box is higher then the task title if font size is larger

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42934] opened 2024-05-31 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: font size of your device should be larger
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open any chat
4. Create a task without assignee

## Expected Result:
Checkmark box is on the same level as the task title if font size is larger

## Actual Result:
Checkmark box is higher then the task title in the chat if font size is larger

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6497518_1717160943687!Screenshot_2024-05-31-10-50-08-578_com expensify chat-edit (1)](https://github.com/Expensify/App/assets/78819774/a12e81a1-753a-405f-815d-4f4bfa43dcb3)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c835d73e1fb0a508</li>
        <li>Upwork Job ID: 1798750213257011740</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102718395</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by lanitochka17** [comment] 2024-05-31 15:17
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-31 15:17
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-06-01 03:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Checkbox position is higher than the task title when the font is large.

### What is the root cause of that problem?
When we increase the font size of the device, the line height of the font is also increased. In this case, we use fontSizeNormalHeight as the line height. The initial value is 21 and the max value is 28.
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/styles/variables.ts#L66

The alignment of both checkbox and the text is flex-start. When the line height is increased it make sense that the text is "pushed down".

<img width="121" alt="Screenshot 2024-06-01 at 11 42 14" src="https://github.com/Expensify/App/assets/50919443/7b60fd4f-e8c2-405d-bc52-13226a37fd60">

### What changes do you think we should make in order to solve the problem?

When the line height is increased, we need to add some margin top to the checkbox. We can caclulate the margin by subtracting the current line height with the minimum line height, that is 21 in this case.
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/components/ReportActionItem/TaskPreview.tsx#L97-L98
```
marginTop: variables.fontSizeNormalHeight - 21 (or any new variable created to hold this value)
```

Result:
<img width="324" alt="image" src="https://github.com/Expensify/App/assets/50919443/d1ca184a-f380-4650-9a54-08619ec46d63">

Optionally, we can add a base margin top if we want to push down the checkbox more and also we can apply this to the > icon too.

OR

Set the alignment to center.

**Comment by alexpensify** [comment] 2024-06-03 23:28
I'll run a test tomorrow and update with the next steps.

**Comment by alexpensify** [comment] 2024-06-05 23:01
I'm able to replicate the experience on my Android device: 

![image](https://github.com/Expensify/App/assets/8107070/5cbf5f8e-0409-4c1a-883a-0d7ccca5e0ff)

**Comment by alexpensify** [comment] 2024-06-05 23:03
@dannymcclain I'd like some Design feedback on how we should handle when the Android device has the increased font size. After that, I'll assign this to `External` to get help. Thanks!

**Comment by dannymcclain** [comment] 2024-06-06 13:49
This isn't only happening when the font size is increased though, right? I'm seeing it in the mac desktop app (with default font size). Ideally we want the checkbox centered with the first line of text in all cases. If we can't figure out an elegant way to make that happen, I'd say we should just center the checkbox with the task title (regardless of size/number of lines/etc.)

![CleanShot 2024-06-06 at 08 46 25@2x](https://github.com/Expensify/App/assets/7516624/926dfd93-336f-4902-8467-9d19af608537)
![CleanShot 2024-06-06 at 08 48 06@2x](https://github.com/Expensify/App/assets/7516624/f1567223-0703-4048-b192-216371cca158)

**Comment by dannymcclain** [comment] 2024-06-06 13:58
Here's a quick mock to show the alignment options:

![image](https://github.com/Expensify/App/assets/7516624/25de3790-02f9-4766-97a0-9af2f5045feb)

cc @Expensify/design I very much prefer aligning with the top line of text, but curious what you all think is acceptable. Also, I thought our default text line-height was `20px`, not `21px`?

**Comment by bernhardoj** [comment] 2024-06-06 14:05
> This isn't only happening when the font size is increased though, right?

Yep, I see it too without the font size increase.

Btw, here is how it looks in real by centering it to the first line.
Before:
<img width="563" alt="image" src="https://github.com/Expensify/App/assets/50919443/70468946-eb9d-49cb-9cb7-e6b71bfbff2c">

After:
<img width="570" alt="image" src="https://github.com/Expensify/App/assets/50919443/46bdd82c-7dd3-4013-9dba-0d016a0f9fda">

(with a scaled font)
<img width="395" alt="image" src="https://github.com/Expensify/App/assets/50919443/fa0c9252-8efa-42de-8dac-2a0406cf54b1">

**Comment by dannymcclain** [comment] 2024-06-06 14:15
@bernhardoj oh I think your afters look good!

**Comment by alexpensify** [comment] 2024-06-06 14:39
@dannymcclain - This GH is only for Android, so thanks for flagging that this might happen on other platforms. I only tested Android 🤦🏼‍♂️ .

**Comment by dannymcclain** [comment] 2024-06-06 14:43
Ah dang yeah it looks like it's happening on all the platforms 😬

**Comment by shawnborton** [comment] 2024-06-06 14:59
Hmm yeah, our default line height should be 20px. If it's not, let's fix it. I also prefer top alignment. From your mocks [here](https://github.com/Expensify/App/issues/42934#issuecomment-2152615595) though, should we add a bit more space between checkbox and text though?

**Comment by shawnborton** [comment] 2024-06-06 15:00
Also just want to flag @thienlnam here - do you remember this from when you implemented Tasks, or maybe a regression has happened that caused the misalignment?

**Comment by thienlnam** [comment] 2024-06-06 15:29
I think this is a regression, we had an issue like this we had fixed in the past. This may have been from recent bumps of react-native-live-markdown

**Comment by dannymcclain** [comment] 2024-06-06 15:43
>From your mocks https://github.com/Expensify/App/issues/42934#issuecomment-2152615595 though, should we add a bit more space between checkbox and text though?

Yeah I think it should have a little more space, but in [these screenshots](https://github.com/Expensify/App/issues/42934#issuecomment-2152630612), the spacing looks good to me. Looks like in the product the gap is `8px` and I just erroneously had it at `4px` in my Figma doodles. So I think we just keep it at `8px` (like it currently is in the product).

>Hmm yeah, our default line height should be 20px. If it's not, let's fix it.

Down to fix this too.

**Comment by shawnborton** [comment] 2024-06-06 16:01
Okay cool, so I guess we should open this up for proposals then? cc @alexpensify

**Comment by alexpensify** [comment] 2024-06-06 16:18
Thanks, team! I've updated the title to avoid confusion and ensure that we go with a plan that supports all platforms. 

@aimane-chnaif please review the proposals and feedback from the Design team. Thanks!

**Comment by oXSMo** [comment] 2024-06-07 01:12
![photo_2024-06-06_18-10-09](https://github.com/Expensify/App/assets/83725293/193be8ca-c350-40bf-a666-f7af0989577e)
![photo_2024-06-06_18-10-05](https://github.com/Expensify/App/assets/83725293/f6863ef8-f203-4580-aa67-399a5c19a397)

do you want to place the checkbox in the middle !!? becaus it's ez

**Comment by bernhardoj** [comment] 2024-06-07 01:55
Based on this [commit message](https://github.com/bernhardoj/Expensify/commit/aa708ef0037718b4db8c677e77507468a11ec7f7), we update the line height to 21 to fix emojis being cut off.

Here is what I got when update it to 20.
<img width="221" alt="image" src="https://github.com/Expensify/App/assets/50919443/4c186742-863a-414c-b1a1-fa2539a6d8fe">

@dannymcclain @shawnborton

**Comment by bernhardoj** [comment] 2024-06-07 02:36
Yes, that's in my alternative solution too.

**Comment by shawnborton** [comment] 2024-06-07 06:09
I think we need to think of a different way to handle the emojis while still keeping our line height at 20px. Perhaps it's an overflow issue or something, but either way, I think that was a mistake to make that change :( cc @roryabraham

**Comment by alexpensify** [comment] 2024-06-10 17:40
@aimane-chnaif - do we have enough feedback to carry on with the review process? Thanks for the update.

**Comment by roryabraham** [comment] 2024-06-11 01:42
I'm [generally all for it](https://expensify.slack.com/archives/CNKBZSQ07/p1689006936357709), but just FWIW I don't think New Expensify is really set up to "officially" support different OS font sizes. So part of me wonders if we should take bug reports for that, or if we should try to holistically start supporting multiple OS font fizes, and include some automated UI and/or regression tests to cover it.

Anyways, that's not the case with this issue, as it's happening with normal font sizes too.

> I think the clean solution is to set checkbox container height same as text lineHeight and center checkbox vertically inside container.

Agree with this.

> I think we need to think of a different way to handle the emojis while still keeping our line height at 20px. Perhaps it's an overflow issue or something, but either way, I think that was a mistake to make that change

Created an issue to address this: https://github.com/Expensify/App/issues/43449

**Comment by shawnborton** [comment] 2024-06-11 06:16
Thanks! Though I already brought this up in the SWM Slack channel, and made this [GH issue here](https://github.com/Expensify/App/issues/43371).

**Comment by alexpensify** [comment] 2024-06-12 19:03
We are waiting for a proposal update here.

**Comment by bernhardoj** [comment] 2024-06-13 02:45
Huh, weird. Pretty sure I already included that solution in my alternative before. Maybe I forget to press the update button.

Updated my [proposal](https://github.com/Expensify/App/issues/42934#issuecomment-2143271048).

**Comment by bernhardoj** [comment] 2024-06-13 10:55
PR is ready

cc: @aimane-chnaif

**Comment by alexpensify** [comment] 2024-06-14 18:04
This PR is going through the review process.

**Comment by alexpensify** [comment] 2024-06-27 20:45
Automation worked here, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2024-06-28 17:34
Payouts due: 2024-06-28

- [x] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @aimane-chnaif 

Upwork job is [here](https://www.upwork.com/jobs/~01c835d73e1fb0a508).

Status: @aimane-chnaif please submit a request in Chat. @bernhardoj has been paid in Upwork.

**Comment by alexpensify** [comment] 2024-10-04 21:51
Reopening so that I can review this notice in more detail.

**Comment by alexpensify** [comment] 2024-10-04 21:54
Ok, I found the notice here: https://expensify.slack.com/archives/C01SKUP7QR0/p1727830262798869. I'll need to create a new Upwork job for this payment.

**Comment by alexpensify** [comment] 2024-10-07 16:44
I need to hold on creating the job because there is a payment issue with Upwork right now: https://expensify.slack.com/archives/C01GTK53T8Q/p1728319262830679

**Comment by alexpensify** [comment] 2024-10-08 18:50
@aimane-chnaif - I sent an offer here: https://www.upwork.com/jobs/~021843723525891848670

Please accept and I can complete the payment process. Thanks!

**Comment by alexpensify** [comment] 2024-10-10 21:08
@aimane-chnaif - I've completed the payment process via Upwork and updated the summary here: 


https://github.com/Expensify/App/issues/42934#issuecomment-2197376861

**Closed by alexpensify** 2024-10-10 21:08 UTC
Labels: External, Weekly, Design, Awaiting Payment, Bug
