### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Chat - System message about adding tag in Parent: Child format shows Parent\: Child

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43465] opened 2024-06-11 12:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43392
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log with any account
3. Go to account settings -> Workspaces -> Create WS if needed
4. Enabled Tags
5. Add a tag in Parent: Child format
6. Go to #admins room and check the system message

## Expected Result:
System message about adding tag in Parent: Child format shows as Parent: Child, not `Parent\: Child`

## Actual Result:
System message about adding tag in Parent: Child format shows `Parent\: Child`

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![_227_](https://github.com/Expensify/App/assets/78819774/1cdc6159-2c25-475c-9bb6-14781e82dc61)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a67ec2b09731f24</li>
        <li>Upwork Job ID: 1800543159428158713</li>
        <li>Last Price Increase: 2024-06-11</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 102720454</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by lanitochka17** [comment] 2024-06-11 12:11
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-06-11 14:58
FYI @lanitochka17 - GitHub was removing the `\` from your comment because it's a Markdown formatting character in GH - it's an escape character used to ignore other markdown formatting ([more details here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#ignoring-markdown-formatting)).

I updated your comment to add that character back. 😄

**Comment by truph01** [comment] 2024-06-12 04:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- System message about adding tag in Parent: Child format shows Parent\: Child

### What is the root cause of that problem?
- With the system message about adding tag, BE returns a message like:
```
{
    "actionName": "POLICYCHANGELOG_ADD_TAG",
    "message": [
        {
            "html": "added the tag \"name\\: age\" to the list \"Tag\"",
            "text": "added the tag \"name\\: age\" to the list \"Tag\""
        }
    ]
}

```
- And we display this message by using ```ReportActionItemMessage```:
https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/home/report/ReportActionItem.tsx#L647
that will display a message base on raw ```reportAction.message``` data.
- So that leads to the bug.
### What changes do you think we should make in order to solve the problem?
- We need to add an additional else logic to this:
https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/pages/home/report/ReportActionItem.tsx#L638
```
 else if (action.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_TAG){
            children = <ReportActionItemBasicMessage message={PolicyUtils.getCleanedTagName(action.message?.[0]?.text ?? '')} />;
```

- Then, we add an additional else logic to this:
https://github.com/Expensify/App/blob/8d11d0b185083a6a813daeb0fe7c0697a5627ef6/src/libs/SidebarUtils.ts#L378
```
else if (lastAction?.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.ADD_TAG) {
            result.alternateText = PolicyUtils.getCleanedTagName(lastAction?.message?.[0]?.text ?? '');
```
to fix the LHN issue.

### What alternative solutions did you explore? (Optional)
- There are a few component where we have the same issue, for example, copy to clipboard action and we need to address them as well.

**Comment by eh2077** [comment] 2024-06-12 16:08
Thank you for your proposals!

@devguest07 Your proposal is close to success. You dived into the code and found a line to fix the effect, though that's not the best way to fix it. No worries, as you seem new to the project. Just a small tip for you: try to find out if there are similar existing coding patterns in the codebase when you're going to make changes. I believe you will soon land on a successful proposal.

@truph01 's [proposal](https://github.com/Expensify/App/issues/43465#issuecomment-2162094545) looks good to me. Their solution fixes both report and LHN message. More detail changes can be discussed in PR.

🎀👀🎀 C+ reviewed

**Comment by rlinoz** [comment] 2024-06-13 13:26
Looks good, thanks!

**Comment by eh2077** [comment] 2024-06-14 09:58
@truph01 Kindly let us know when we can expect a PR to be ready for review, thanks!

**Comment by truph01** [comment] 2024-06-14 12:41
@eh2077 I created PR https://github.com/Expensify/App/pull/43765. It can be reviewed now.

**Comment by rlinoz** [comment] 2024-06-25 13:40
@sakluger this issue was fixed by some other PR and is not reproducible anymore, but we had a working PR and all, can you proceed with payment to @truph01 and @eh2077 ?

**Comment by sakluger** [comment] 2024-06-25 14:28
Summarizing payment on this issue:

Contributor: @truph01 $250, payable via Upwork
Contributor+: @eh2077 $250, paid via Upwork

**Comment by rlinoz** [comment] 2024-06-25 14:29
Not sure why Melvin think this is overdue

**Comment by sakluger** [comment] 2024-06-25 14:29
@truph01 could you please apply to the job on Upwork (https://www.upwork.com/jobs/~014a67ec2b09731f24) or share your Upwork profile link so that we can pay you for your work and close out the GH issue? Thanks!

**Comment by sakluger** [comment] 2024-06-25 14:30
@truph01 could you please apply to the job on Upwork (https://www.upwork.com/jobs/~014a67ec2b09731f24) or share your Upwork profile link so that we can pay you for your work and close out the GH issue? Thanks!

**Comment by rlinoz** [comment] 2024-06-25 14:54
@sakluger I actually messed up and got things wrong, the main issue is still reproducible, and we are fixing it in the PR, I am really sorry about that.

**Comment by truph01** [comment] 2024-07-09 07:38
@sakluger I accepted that offer, TY

**Comment by sakluger** [comment] 2024-07-10 18:20
Thanks, all paid!

@eh2077 we're just holding for the BZ checklist before we can close this issue.

**Comment by sakluger** [comment] 2024-07-11 16:32
Bump @eh2077

**Comment by eh2077** [comment] 2024-07-13 00:01
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: _**There's not such PR that causes this bug because the system message if from backend.**_
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. **_No_**

cc @sakluger

**Closed** 2024-07-15 18:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
