### ISSUE TITLE
[HOLD for payment 2024-08-19]  [$250] Send invoice - Hold option is present for invoice and the invoice cannot be held

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45518] opened 2024-07-16 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4728016
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User has received invoice.
- The following steps will be performed by the invoice receiver.

1. Go to staging.new.expensify.com
2. Go to invoice chat.
3. Click on the invoice preview.
4. Click on the report header.
5. Click Hold.
6. Enter a reason and save it.

## Expected Result:
There should be no Hold option for invoice.

## Actual Result:
Hold option is present for invoice and the invoice cannot be held.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/38881d15-a3d0-47eb-bc0e-9dcbb504f568

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0178cd3e6d26424c8a</li>
        <li>Upwork Job ID: 1813589312856914205</li>
        <li>Last Price Increase: 2024-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103157119</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by neonbhai** [comment] 2024-07-16 20:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold option is shown for invoice requests

### What is the root cause of that problem?
`shouldShowHoldAction` here does not account for invoice reports
https://github.com/Expensify/App/blob/c7d7bf4c3273d2cbbd230f49d9d355f5f6306abf/src/pages/ReportDetailsPage.tsx#L521-L524

### What changes do you think we should make in order to solve the problem?
We should not show Hold option for invoice reports. We will add a check for `!ReportUtils.isInvoiceReport(report)` in `shouldShowHoldAction`

**Comment by etCoderDysto** [comment] 2024-07-16 20:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hold option is present for invoice and the invoice cannot be held
### What is the root cause of that problem?
We are referencing `isPolicyAdmin` function that is declared [here](https://github.com/Expensify/App/blob/12acd133c5cb73ed8b73540476869fbd3f641687/src/libs/ReportUtils.ts#L1385-L1386), rather making `isPolicyAdmin()` function call. Therefore `canModifyStatus` is `true` for invoice recipient. 
https://github.com/Expensify/App/blob/12acd133c5cb73ed8b73540476869fbd3f641687/src/libs/ReportUtils.ts#L2826


### What changes do you think we should make in order to solve the problem?
* We should check if the user is a policy admin by calling `isPolicyAdmin` function. 
```javascript
const isAdmin = isPolicyAdmin(moneyRequestReport?.policyID ?? '-1', allPolicies);
```
* use `isAdmin` in place of `isPolicyAdmin` 

### What alternative solutions did you explore? (Optional)

**Comment by rafecolton** [comment] 2024-07-16 21:17
Seems like we are already enforcing non-holding of invoices on the back-end due to the error shown in the video. So I think that means this is only a front-end issue where we need to not show the button. @neonbhai's solution sounds simplest to me, but it's possible I'm missing some nuance about how invoices work.

**Comment by etCoderDysto** [comment] 2024-07-16 21:27
[Updated admin workspace scenario video](https://github.com/Expensify/App/issues/45518#issuecomment-2231741566)

**Comment by cead22** [comment] 2024-07-16 21:30
I agree this is a front end issue, so removing the deploy blocker label

**Comment by chiragsalian** [comment] 2024-07-16 21:31
nice, i was just looking here and agree. it looks like a front issue and not a blocker for backend.

**Comment by thienlnam** [comment] 2024-07-16 22:45
Going to remove the blocker - this is a new feature and I don't think invoices on NewDot are really used yet

**Comment by neonbhai** [comment] 2024-07-16 22:52
> Seems like we are already enforcing non-holding of invoices on the back-end due to the error shown in the video. So I think that means this is only a front-end issue where we need to not show the button. @neonbhai's solution sounds simplest to me, but it's possible I'm missing some nuance about how invoices work.

@rafecolton hi, production does not show `Hold` option to either the workspace admin, send or receiver of an invoice. We should be fine to hide it from the Report Details Page

**Comment by cdOut** [comment] 2024-07-17 10:22
I’m already working on a [PR to clean up hold/unhold logic](https://github.com/Expensify/App/issues/44573), I could handle this case there unless there are any objections against it.

**Comment by stephanieelliott** [comment] 2024-07-17 15:00
I think that sounds fine @cdOut, will go ahead and assign you to this one.

**Comment by cdOut** [comment] 2024-07-29 14:41
Will be sent for a re-review today and should be merged in a few days max.

**Comment by stephanieelliott** [comment] 2024-07-30 23:05
Just linking the PR for this: https://github.com/Expensify/App/pull/45151

**Comment by cdOut** [comment] 2024-08-01 18:21
PR is currently being re-reviewed.

**Comment by stephanieelliott** [comment] 2024-08-16 01:08
Ok seems this was deployed to prod on 8/12 per this comment: https://github.com/Expensify/App/pull/45151#issuecomment-2289786918

Updating for 7 day hold with payment pending labels.

**Comment by stephanieelliott** [comment] 2024-08-20 08:39
Summarizing payment on this issue: 

 - Contributor: @cdOut - no payment due (agenty)
 - Contributor+: @ishpaul777 - no payment/no review required
 
 Upwork job is here: https://www.upwork.com/jobs/~0178cd3e6d26424c8a

**Closed by stephanieelliott** 2024-08-20 08:39 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
