### ISSUE TITLE
[$1000] Chat - App removes strikethrough formatting on copy and resend for code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23034] opened 2023-07-17 19:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send strikethrough code block eg: ~```Hello```~
4. Hover on message and click on copy to clipboard OR edit the message and copy the message
5. Send the copied message and observe that app removes strikethrough format from the code block

## Expected Result:
 App should keep the format of text same when we copy it to clipboard or copy from edit message and resend the message

## Actual Result:
App does not keep the format of strikethrough on code block on copy to clipboard or copy from edit message and resend the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0c2b5085-106a-465d-bf58-467a0d0425bf

https://github.com/Expensify/App/assets/93399543/afd39161-3b5a-4f17-8a7d-b5a694ab46eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH handle - @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689525870441879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012fc66a9c82073e51</li>
        <li>Upwork Job ID: 1681045679677927424</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by eh2077** [comment] 2023-07-17 19:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App removes strikethrough formatting on copy and resend for code block.

### What is the root cause of that problem?

The root cause of this issue is that we translate 

````
~```test```~
````

to HTML 

```html
<del><pre>test</pre></del>
```

through [strikethrough rule](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L206-L210) and the HTML is converted back to Markdown

````md
~```
Hello
```
~
````

through [htmlToMarkdownRules](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L241).

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can skip applying [strikethrough rule](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L206-L210) if it contains `pre` tag, just like [italic](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L192-L196) and [bold](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L204) rule. So, we can change this [line](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L209) to

```js
replacement: (match, g1) => (g1.includes('<pre>') || this.containsNonPairTag(g1) ? match : `<del>${g1}</del>`),
```

By doing so, we won't apply strikethrough style for markdown input, like

````
~```test```~
````

So, copying and pasting comment will have consistent style, just like italic and bold syntax do.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by joekaufmanexpensify** [comment] 2023-07-17 20:57
I can reproduce this. I don't think we're really "removing" the formatting though when copying the code block. It's just that when it's pasted, there's a space between the last ``` and `~`. If the space is removed before you send the message you copied, we do show the strikethrough.

**Comment by hurtdusk** [comment] 2023-07-18 00:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App removes strikethrough formatting on copy and resend for code block

### What is the root cause of that problem?
When the "Edit Message" button is clicked, the raw text has a newline between the final ` and the second ~ which differs from the original raw message content. When a newline is introduced in this manner, the rule/pattern for strikethrough does not match. It seems that the code block is what causes the newlines to be inserted. Note that inserting newlines into any strikethrough message will cause the strikethrough to disappear.

### What changes do you think we should make in order to solve the problem?
There are two options to solve this issue in my view. The first option is to make sure that when "Edit Message" is clicked, the raw text displayed is identical to the raw text that was sent originally (do not introduce newlines). The second option is to update the rule/pattern for strikethrough so that it also matches text that contains newlines.

**Comment by hurtdusk** [comment] 2023-07-18 00:31
Contributor details
Your Expensify account email: emil05joh@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012188f4918fcf5a7b

**Comment by mehvash-Khan** [comment] 2023-07-18 11:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

While chatting with a user, if I send `~```hello```~` to the user, copy it to clip board and paste it in the chat, the closing `~` is pasted in the next line like below:

````
~```
hello
```
~
````

### What is the root cause of that problem?

Regex used in `ExpensiMark.js` [here](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L243-L247)  for converting HTML to Markdown code  is adding new line i.e `<br />` after closing  ` ``` ` which adds a new line before closing strike through `~`. This is expected, `</br>` should be added after closing `</pre>` tag, but when a new closing tag `</del>` appears after </pre> it does not handle it, hence not allowing it to be pasted as a striked through code block.

### What changes do you think we should make in order to solve the problem?

One possible solution for this problem of adding new line after ` ``` `, can be adding an additional regex in `htmlToMarkdownRules`. Add an aditional condition in this regex which handles any closing tag `</>` which appears after `</pre>` and does not add `</br>` after `</pre>` if there is a closing tag following it. Please check below

```js
{
             name: 'replacepre2',
              regex: /<\/pre>(<\/.*>)(.)/gi,
              replacement: '</pre>$1<br />$2',
}
```
 if we want it to be specific just for strike through `</del>`, we can update the regex just for strike through like
 `   regex: /<\/pre>(<\/del>)(.)/gi, ` and it should work as expected.

Additionally, to handle  the behaviour where `<br />` should be added after `</pre>` like it does usually, we will change the current regex `replacepre` to this:

```js
{
        name: 'replacepre',
        regex: /<\/pre>(?!<\/.*>)(.)/gi,
        replacement: '</pre><br />$1',
}
```

This will add `<br/>` i.e new line after closing `</pre>` if there is an additional text or code after it which is not closing tag.

### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:18
Proposals pending review

**Comment by joekaufmanexpensify** [comment] 2023-07-18 18:24
Thanks! Yep, I saw. Just commented to make sure the issue doesn't go overdue today.

**Comment by joekaufmanexpensify** [comment] 2023-07-20 18:19
Sounds good! LMK if there's anything else I can help with as you review the proposals here.

**Comment by payal-lathidadiya** [comment] 2023-07-24 08:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In chat - app removes strikethrough formatting on copy and resend for code block

### What is the root cause of that problem?
When we've code block inside strike through `~```hello```~`, it gets converted to following HTML
`<del><pre>hello</pre></del>`

And this HTML, gets converted back to below markup [here](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L241)

````md
~```
Hello
```
~
````

However, above markdown doesn't get parsed as valid strikethrough section using regular expression [here](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L206-L210)
[regex test link](https://regex101.com/r/CUlMhe/1)

### What changes do you think we should make in order to solve the problem?

To fix this, we should change strikethrough rule regex [here](https://github.com/Expensify/expensify-common/blob/d7e424913550349acc779d029319af5b074c7c9e/lib/ExpensiMark.js#L208) to below;
```
\B~((?=\S)((~~(?!~)|[^( \t\r\f)~]|\s(?!~))+?))~\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g
```

[Regex fix test result](https://regex101.com/r/qzW5GQ/1)

**Explanation:**
> Here, in previous regex for 3rd capturing group, 2nd alternative `[^\s~]` will match a single character which is not present in \s (whitespace characters i.e. `[ \t\r\n\f]`) followed by `~`. In example given in issue, we have new line character i.e. `\n` before `~`. So that should be excluded from that group.

### What alternative solutions did you explore? (Optional)
None

**Comment by joekaufmanexpensify** [comment] 2023-07-24 13:29
Still pending review of proposals

**Comment by joekaufmanexpensify** [comment] 2023-07-25 12:59
@parasharrajat Curious if there's an update on your review of the proposals on this issue? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-27 15:18
Pending further review

**Comment by eh2077** [comment] 2023-07-28 03:07
> Note to me: I think the root cause here is incorrect parsing of `pre` rule And I think that issue was stated after this PR [Expensify/expensify-common#496](https://github.com/Expensify/expensify-common/pull/496).

@parasharrajat Maybe the twisted of code block feature ` ``` ` can be solved in a separate issue or other issues, like https://github.com/Expensify/App/issues/16982 and https://github.com/Expensify/App/issues/18928. So, we can move this issue forward by keeping `italic`, `bold` and `strikethrough` consistent in formatting code block. Do you agree with this?

**Comment by Antasel** [comment] 2023-07-28 08:40
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
App removes strikethrough formatting on copy and resend for code block.

### What is the root cause of that problem?
1. in ExpensiMark.js, htmlToMarkdown's 'replacepre' rule is adding <br /> after </pre> tag, that is, line break is added after closing three backticks, before closing ~ (like `~```\nHello\n```\n~`). so it is not parsed as expected, strikethrough formatting is removed.
2. another root cause is existed, \r\n is copied when edit message and copy from it on windows platform.
EOL(end of line) code is \r\n on windows, so it's converted to \r<br /> and backend will return \n<br />. so one more <br /> will be added.
on Unix
these are root causes

### What changes do you think we should make in order to solve the problem?
- To fix first root cause, change replacepre rule of html to markdown rules as following, then it will add <br /> after </del> tag
```
{
             name: 'replacepre',
              regex: /<\/pre>((?:<\/.*>)*)((?!<\/).)/gi,
              replacement: '</pre>$1<br />$2',
}
```
- along with second root cause, even after first cause is fixed, copied text from edit message will be `~```\r\nHello\r\n```~` it's not parsed like `~```\nHello\n```~`, but we expect same parsed result.
to fix it, add a tweak on codefence regex and newline regex as following.

codefence Regex:
```
/(&#x60;&#x60;&#x60;(?:(?:\r\n)|\n)?)((?:\s*?(?![\n]?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?)((?=\n?)&#x60;&#x60;&#x60;)/g
```

newline Regex:
```
/\r?\n/g
```

as result, we keep consistency of strikethrough formatting on copy(from clipboard and edit input) and resend for code block.
and it does not cause other auto-test cases failed.

**Comment by joekaufmanexpensify** [comment] 2023-07-31 13:05
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-08-02 16:46
Discussing in Slack.

**Comment by joekaufmanexpensify** [comment] 2023-08-03 21:43
Pending review of proposals.

**Comment by joekaufmanexpensify** [comment] 2023-08-04 19:04
Still discussing in Slack

**Comment by eh2077** [comment] 2023-08-08 15:20
@parasharrajat I noticed a dupe https://github.com/Expensify/App/issues/23801 and linked it FYI

**Comment by joekaufmanexpensify** [comment] 2023-08-09 12:48
Still discussing in above Slack thread

**Comment by joekaufmanexpensify** [comment] 2023-08-10 20:22
Same

**Comment by joekaufmanexpensify** [comment] 2023-08-11 19:10
Bumped slack discussion.

**Comment by joekaufmanexpensify** [comment] 2023-08-14 12:36
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-08-15 20:42
Bumped slack thread.

**Comment by joekaufmanexpensify** [comment] 2023-08-21 12:55
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-08-22 21:26
[Reposted the Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1692739553293539) to generate more interest in the discussion), so we can identify a path forward.

**Comment by joekaufmanexpensify** [comment] 2023-08-23 19:41
More discussion now in the [Slack thread. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1692799908413129?thread_ts=1691177693.070819&cid=C01GTK53T8Q)

**Comment by joekaufmanexpensify** [comment] 2023-08-24 18:01
@parasharrajat you have a chance to look at the latest response in the thread?

**Comment by joekaufmanexpensify** [comment] 2023-08-25 20:38
Bumped slack thread again

**Comment by joekaufmanexpensify** [comment] 2023-08-28 12:55
Not overdue

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:38
Great, ty!

**Comment by joekaufmanexpensify** [comment] 2023-08-29 20:27
Pending further input on the slack thread from Rajat.

**Comment by joekaufmanexpensify** [comment] 2023-08-30 19:57
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-08-31 20:18
@parasharrajat any update on your analysis of the Slack thread?

**Comment by Skalakid** [comment] 2023-09-04 11:58
Hey I’m Michał from Software Mansion, an expert agency, and I will help close this issue out 😄

**Comment by Skalakid** [comment] 2023-09-04 13:50
@eh2077 Thanks for the proposal, I really like it. I think it is a good idea to keep the behavior of strikethrough consistent with the ***bold*** and _italic_. Also, I can't find striking through the code block on other apps. @parasharrajat what do you think about that?

**Comment by Antasel** [comment] 2023-09-04 13:58
@Skalakid we can find striking through in code block on discord. and italic and bold as well

**Comment by Skalakid** [comment] 2023-09-05 11:24
@mehvash-Khan I was testing your proposal and it fixes this bug but when I'm copying the strikethrough codeblock and paste it, it pastes it with 2 new lines below it

**Comment by Skalakid** [comment] 2023-09-06 08:59
@spcheema I tested your solution and I cant't make it work 😅 also I think it would be better to make it not only for <del> tag but also for other formats

**Comment by Skalakid** [comment] 2023-09-06 09:18
@payal-lathidadiya Thanks for the proposal, however I'm not sure if we want to edit strikethrough rule. On many apps such a behavior is blocked and you can't ad formating when the end is the beginning of the new line (for example on GitHub/Slack).

~hello
~

**Comment by joekaufmanexpensify** [comment] 2023-09-06 13:39
Still pending discussions

**Comment by joekaufmanexpensify** [comment] 2023-09-07 19:44
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2023-09-08 19:20
@parasharrajat is there anyone specific you're looking for input from on those threads? If so, I'm happy to just tag them so we can try to push this forward.

**Comment by joekaufmanexpensify** [comment] 2023-09-11 13:24
I'm sure people will be interested! Just concerned the thread might have gotten buried in the room. I see there's been more input, but I will bump it now.

**Comment by thienlnam** [comment] 2023-09-12 02:04
Closing in favor of https://github.com/Expensify/App/issues/23034

**Closed** 2023-09-12 04:43 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-09-12 05:09
Hi @thienlnam, you have written the same issue number in your message, maybe you were marking any other issue?

**Comment by thienlnam** [comment] 2023-09-12 05:15
Updated, thanks
