### ISSUE TITLE
Getting notification in ND for the OD expense report comment and opens without any system message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20298] opened 2023-06-06 18:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to OD and ND with same account A
2. Create a expense report in OD and submit to Account B
3. Leave a comment in the report as a user B in OD
## Expected Result:
There shouldn't be any notification to account A NewDot and should have some system message
## Actual Result:
Notification received and clicking on it blank header shows up
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/54289762-2c02-4d63-8be9-ada4197e4134)

![image](https://github.com/Expensify/App/assets/43996225/df420397-b1fe-4aa8-b2cd-ee257c98e955)

<img width="960" alt="Screenshot (352)" src="https://github.com/Expensify/App/assets/43996225/e9455662-4d83-4e26-85ca-6515468af759">

<img width="957" alt="1" src="https://github.com/Expensify/App/assets/43996225/47d4f243-84c8-492c-9469-16ae1a97bac6">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685721501722059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by strepanier03** [comment] 2023-06-08 04:53
Hmmm, I'm struggling to recreate this, I'm not getting a chat created in Newdot or a notification of the message left by user B on the report. 

I have tested on a workspace and a personal policy so I'll set up a test policy and try again.

**Comment by strepanier03** [comment] 2023-06-08 04:55
Very odd, still unable to recreate when the report is on a Group policy either.

**Comment by strepanier03** [comment] 2023-06-13 00:19
Fresh round of testing and I think the problem recreating is unique to me because I've noticed I'm not getting any notifications at all. 

Normally I use desktop app but have had Newdot open in an incognito window since I started testing this and I'm getting zero notifications.

**Comment by strepanier03** [comment] 2023-06-13 00:21
Asked for testing [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1686615667838029).

**Comment by strepanier03** [comment] 2023-06-15 22:22
@MitchExpensify - I am heading out on sabbatical in a couple of hours and haven't found someone to recreate this for me. You'll see above I linked to a Slack post I made asking for help testing. I can't get notifications to work on iOS/Chrome but don't have time to resolve it now. 

This needs testing and recreation to move forward but I can't recreate without notifications so originally I thought I couldn't repro but I think notifications are the issue blocking for me.

Thank you for handling this and moving it forward!

**Comment by MitchExpensify** [comment] 2023-06-18 23:59
Can't access the app to test this right now - Seeing if anyone else is running into this [here](https://expensify.slack.com/archives/C03U7DCU4/p1687124061446649?thread_ts=1687123626.458739&cid=C03U7DCU4)

**Comment by MitchExpensify** [comment] 2023-06-21 21:27
Like Sheena, I had trouble reproducing this mostly because of notification settings and NewDot buggyness. Hoping whoever gets assigned while I'mm ooo until Tuesday has more luck reproducing this one! I'll take it back over once I return 👍

**Comment by abekkala** [comment] 2023-06-26 13:31
Oh, I did attempt to recreate this last week and forgot to comment. 

I was not able to replicate the outcome shown above.

**Comment by abekkala** [comment] 2023-06-29 13:34
@MitchExpensify I think you're back now. This has gone through Sheena and Myself while you were ooo.

How do you want to proceed?

**Comment by abekkala** [comment] 2023-06-30 15:42
@MitchExpensify unassigning myself as the second person here as I'm leaving for sabbatical. 
As noted above neither Sheena nor I was able to reproduce this while you were out.

**Comment by MitchExpensify** [comment] 2023-07-01 18:50
Closing as none of us can reproduce

**Closed by MitchExpensify** 2023-07-01 18:50 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
