### ISSUE TITLE
Web - Login - 'Couldn't retrieve account details' error shows up for new account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28033] opened 2023-09-22 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to [https://26772.pr-testing.expensify.com/.](https://26772.pr-testing.expensify.com/)
2. Enter a new email with no ND account.
3, Click Continue.

## Expected Result:
User enters magic code page with no error message.

## Actual Result:
The error message 'Couldn't retrieve account details, please try to sign in again‘ shows up in magic code page.

This issue is also reproducible on staging build.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.72-9 PR:26772

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/fdae65d4-aa7f-467b-84da-4d34446900ca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2023-09-22 16:30
Issue found when testing this PR# https://github.com/Expensify/App/pull/26772

**Comment by kbecciv** [comment] 2023-09-22 17:39
@aman-atg QA team reported first 
![image](https://github.com/Expensify/App/assets/93399543/56b12f20-3018-49bf-9739-20069641795c)

**Comment by rojiphil** [comment] 2023-09-22 17:56
@chiragsalian 
I think, BE needs a fix here.
Here are my observations:
When a new email address is used for login (i.e. which was not previously used in BE), the `BeginSignIn` API returns with 0 as jsonCode. But, when an existing email address is used for login, the API returns with 200 as jsonCode. This is why this problem occurs. Not sure what significance it has for BE to send 0 as jsonCode for new login. 
I think, BE needs to send 200 as jsonCode even for a new login.

**Comment by chiragsalian** [comment] 2023-09-22 17:58
Interesting theory, but someone i dont think we changed the backend code for this flow in a while and yet it works fine on production but not on staging. Have you verified if the backend returns something different for production vs staging. I've yet to confirm it. I'm working on building this on my dev environment at the moment.

**Comment by chiragsalian** [comment] 2023-09-22 18:01
staging, lol wtf - invalid socket ID,
![image](https://github.com/Expensify/App/assets/14356145/d2ce6947-4b6a-4778-b79b-1300232b16b2)

**Comment by chiragsalian** [comment] 2023-09-22 18:03
Same payload between staging and production but the response is different. One has an error message and the other does not. Weird. Okay this does not look like an App deploy blocker but I'll investigate further before i clear it.

**Comment by chiragsalian** [comment] 2023-09-22 18:13
Yup, the issue is definitely only related to backend. When i use production code it works just fine. I think i found the offending backend PR but I'll test it a bit more before i confirm.

**Comment by chiragsalian** [comment] 2023-09-22 19:11
I've got a fix up. Testing it a bit and then ill put it for review. If it gets reviewed/merged soon I'll move it to staging immediately.

**Comment by chiragsalian** [comment] 2023-09-22 19:55
This is done. I CP-d a fix for this. I tested on staging and it looks good to me.
Can you retest @izarutskaya and if the issue is resolved can you close out this issue.

**Comment by chiragsalian** [comment] 2023-09-25 19:52
I think this is a non issue anymore. Closing. Feel free to reopen if anyone disagrees.

**Closed by chiragsalian** 2023-09-25 19:52 UTC
Labels: Engineering, Daily, Bug

**Comment by izarutskaya** [comment] 2023-09-26 19:20
Hi @chiragsalian, sorry for waiting. Works fine now. Thanks

https://github.com/Expensify/App/assets/115492554/237e6837-24e2-44c5-82f9-d9c80d7c2674
