### ISSUE TITLE
Android - Chat - The name show in brief moment in chat even after deleting first name and last name @gadhiyamanan

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11207] opened 2022-09-22 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and log in with account where you have your first and last name sets up
2. Go to settings > Profile
3. Delete first name and last name
4. Go to any chat

## Expected Result:
Name should not show

## Actual Result:
 Name shows for second

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.4.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/191790315-95c7ee43-b834-47a3-b346-9d1cca589a5d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @gadhiyamanan

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661943751632949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-09-22 17:00
@jasperhuangg I think this is related to our conversation [here](https://expensify.slack.com/archives/C03TQ48KC/p1663797332998359)

**Comment by gadhiyamanan** [comment] 2022-10-12 08:52
@marcaaron is it fixed? I am not able to reproduce it.

**Comment by gadhiyamanan** [comment] 2022-10-14 07:50
> @marcaaron is it fixed? I am not able to reproduce it.

bump @marcaaron  ^^

**Comment by gadhiyamanan** [comment] 2022-10-18 14:06
> @marcaaron is it fixed? I am not able to reproduce it.

bump @marcaaron  @jasperhuangg ^^

**Comment by MitchExpensify** [comment] 2022-10-19 22:00
Asked for Android reproduction help here https://expensify.slack.com/archives/C01GTK53T8Q/p1666216792881779

**Comment by MitchExpensify** [comment] 2022-10-19 22:04
@thesahindia kindly stepped in to reproduce and was unable to - Closing

**Comment by gadhiyamanan** [comment] 2022-10-20 03:06
@MitchExpensify am i eligible for reporting because at the time of reporting it reproduced and it's handled internally

**Comment by MitchExpensify** [comment] 2022-10-24 17:03
Sorry for the delay @gadhiyamanan! I think so, yes. [Here is the Upwork Job I've invited you to for reporting payment](https://www.upwork.com/jobs/~01db5842f8ea48d540)

**Comment by gadhiyamanan** [comment] 2022-10-24 17:08
@MitchExpensify accepted :)

**Comment by thesahindia** [comment] 2022-10-24 17:34
I am not completely sure but I don't think any specific PR for this issue was raised. No engineer is assigned here and there's no link of any PR.

According to the internal [thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1665598030501879?thread_ts=1665598030.501879&cid=C02NK2DQWUX) the contributor shouldn't be paid for reporting in a case like this.
cc: @mallenexpensify @MitchExpensify

**Comment by mallenexpensify** [comment] 2022-10-24 18:12
Here's the [blurb in CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#proposing-a-job-that-expensify-hasnt-posted)
>  If it's a valid job proposal that we choose to implement by deploying it to production — either internally or via an external contributor — then we will compensate you $250 for identifying and proposing the improvement. If the bug is fixed by a PR that is not associated with your bug report, the contributor is not eligible for compensation unless they can find the PR that fixed the bug then show their bug report preceded the one associated with the PR.

So... @gadhiyamanan wouldn't be eligible for compensation unless it's fixed. If we're going to keep this issue closed, is there an internal one we can link to for auditing so that we'll know if it's fixed internally?

**Comment by MitchExpensify** [comment] 2022-10-25 15:55
Thanks for the course correction @mallenexpensify and @thesahindia, I'll end the contract now. Apologies for the confusion

**Closed** 2022-10-31 22:52 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
