### ISSUE TITLE
[$250] Email address flickering - Reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11134] opened 2022-09-20 05:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open settings > profile
2. remove first name and last name
3. uncheck or check timezone radio button, click on save
4. immediate go back to settings screen

## Expected Result:
email address shows for a second and after that it's not visible

## Actual Result:
email address should not show

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Android
- Mobile Web

**Version Number:** 
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/191176486-59a77899-eaf7-49c2-8225-6d7a6caca2ba.mov

https://user-images.githubusercontent.com/43995119/191176489-81b8f232-1991-44ca-9a96-ce7e15131681.mp4

https://user-images.githubusercontent.com/43995119/191176491-598f4f16-1430-45ac-948e-07f88728b55d.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661501281504419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-09-20 06:18
### Proposal 

It happens when you save profile changes and there is no name in the profile this causes display name to be empty

We should remove this check https://github.com/Expensify/App/blob/50d42954276ca93d2cc0c9aaec5d0b2bd740f6f4/src/pages/settings/InitialSettingsPage.js#L269

**Comment by Christinadobrzyn** [comment] 2022-09-20 06:59
I can't find any other GHs that match this same issue so sending to Eng to see if it should be fixed now.

**Comment by alex-mechler** [comment] 2022-09-20 22:24
@mvtglobally I'm not able to reproduce this, are you?

**Comment by mvtglobally** [comment] 2022-09-21 04:00
@alex-mechler  We are not able to repro as well

**Comment by gadhiyamanan** [comment] 2022-09-21 05:44
@Puneet-here are you able to reproduce?
 it's reproducible for me.

**Comment by Puneet-here** [comment] 2022-09-21 06:13
Yes, it's reproducible. 
Note: You have to keep the first and last name empty when saving.

**Comment by alex-mechler** [comment] 2022-09-21 15:53
What version(s) are you able to reproduce on? I was unable to reproduce on staging web yesterday (v1.2.3-0)

**Comment by gadhiyamanan** [comment] 2022-09-22 04:58
>What version(s) are you able to reproduce on?

(v1.2.3-1)-production

cc: @alex-mechler

**Comment by Puneet-here** [comment] 2022-09-22 11:06
@parasharrajat, check the video below:-
1. The email is shown in below the avatar 
2. Saving changes without names makes it blank
3. After refreshing it works fine again

https://user-images.githubusercontent.com/101883770/191729971-e5dfd545-c21f-4721-bdf8-f4ec1dfcd270.mov

**Comment by sobitneupane** [comment] 2022-09-22 16:38
**Proposal:**
I am assuming that we would not want to show email twice.
Here we are checking `this.props.currentUserPersonalDetails.displayName` assuming it will have value only if firstName or lastName are set which is not the case. After firstName and lastName are removed, `this.props.currentUserPersonalDetails.displayName` takes the value `Str.removeSMSDomain(login);`. Thus, emails are being shown in two places.
```diff
-                            {this.props.currentUserPersonalDetails.displayName && (
+                            {(!_.isEmpty(this.props.currentUserPersonalDetails.firstName) || !_.isEmpty(this.props.currentUserPersonalDetails.lastName)) && (
                                <Text
                                    style={[styles.textLabelSupporting, styles.mt1]}
                                    numberOfLines={1}
                                >
                                    {Str.removeSMSDomain(this.props.session.email)}
                                </Text>
                            )}
```

**Comment by Puneet-here** [comment] 2022-09-22 17:01
IMO it's useful. When the email is longer it will be in ellipsis at the upper row but in the second row the text is small so it is fully visible. Also It was like this from the starting.

**Comment by sobitneupane** [comment] 2022-09-22 17:40
> It's ideal to fix in backend by sending correct displayName in socket event as I proposed in other GH. 

@aimane-chnaif 
I was planning to raise this issue in slack. As you have done great work with the analysis, why don't you start the conversation in slack as well. It will have more eyes.

**Comment by iwiznia** [comment] 2022-09-23 11:52
If this is a backend error, then we should fix it in the backend. But I am not sure exactly what the error is. Specifically, after calling which API command are we receiving the wrong `displayName` in the `personalDetails` onyx key?

**Comment by iwiznia** [comment] 2022-09-23 13:38
Ah ok thanks! Was not completely sure.

**Comment by iwiznia** [comment] 2022-09-23 13:40
ok, I think I know what the issue is. In order to be sure, I'd like reproduction steps. It _seems_ to me this happens when you update your first and last names to empty?

**Comment by iwiznia** [comment] 2022-09-23 13:45
ok I think I got a fix, but it's in the backend.

**Comment by stephanieelliott** [comment] 2022-09-27 13:12
Removing `Help Wanted` since we will fix this internally.

**Comment by Puneet-here** [comment] 2022-10-05 07:00
We can close this since it's a dupe of https://github.com/Expensify/App/issues/10891, right?

**Comment by iwiznia** [comment] 2022-10-05 12:35
I don't know why this was not auto closed when this was deployed https://github.com/Expensify/Web-Expensify/pull/34940

**Closed by iwiznia** 2022-10-05 12:35 UTC
Labels: Reviewing, Engineering, Daily

**Comment by gadhiyamanan** [comment] 2022-10-05 12:38
@iwiznia am i eligible for reporting?

**Comment by iwiznia** [comment] 2022-10-05 12:39
I think no, since the other issue was reported earlier.

**Comment by gadhiyamanan** [comment] 2022-10-05 12:42
@iwiznia i think the issue is different

**Comment by iwiznia** [comment] 2022-10-05 12:49
I don't think it is. Can you reproduce it?
