### ISSUE TITLE
[HOLD for payment 2023-08-03] [$1000] mWeb - Horizontal message settings being displayed on mobile

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22759] opened 2023-07-12 17:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open a chat
2. Click with 2 fingers on 2 different message twice

## Expected Result:
The comment action menu should only open on one long press on one comment

## Actual Result:
The comment action menu opens when tapping quickly on separate comments

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cf50220f-8123-431c-a91a-2c41e0ef15ae

https://github.com/Expensify/App/assets/93399543/8a938db6-ce50-4c96-aec6-86b2c3855d3e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689119360544589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e2c7a6952e9ef076</li>
        <li>Upwork Job ID: 1679930169256824832</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-07-12 17:12
# Proposal

## Please re-state the issue
Mini report action context menu is visible on small screen devices.

## What is the root cause of that problem?
The menu is supposed to be visible when there is a hover action and mainly this is possible with a mouse, but sometimes, hover can be triggered on a click as well.

## What changes do you think we should make in order to solve this problem?
In this file: 
https://github.com/Expensify/App/blob/29ae9421d61c5a05e12408c258f64d4b65c3c2c4/src/pages/home/report/ReportActionItem.js#L466-L473
We should add `!this.props.isSmallWidthScreen` condition to `isVisible` prop with a logical `AND`.

## What other alternative approaches did you explore?
N/A

**Comment by esh-g** [comment] 2023-07-12 17:16
It might be difficult to reproduce... So be sure to check the slack convo

**Comment by MitchExpensify** [comment] 2023-07-12 22:20
This requires a physical android which I do not have, looking for another Bug Zero volunteer to take this on 👁️

**Comment by MitchExpensify** [comment] 2023-07-12 22:26
Asked here for help https://expensify.slack.com/archives/C01SKUP7QR0/p1689200759769169

**Comment by MitchExpensify** [comment] 2023-07-12 22:35
Clarified expected and actual here https://expensify.slack.com/archives/C049HHMV9SM/p1689201312520879?thread_ts=1689119360.544589&cid=C049HHMV9SM

**Comment by Santhosh-Sellavel** [comment] 2023-07-14 19:13
@bernhardoj [Proposal](https://github.com/Expensify/App/issues/22759#issuecomment-1633972343) Looks good to me!

C+ Reviewed
🎀 👀 🎀

**Comment by mejed-alkoutaini** [comment] 2023-07-14 23:08
Contributor details
Your Expensify account email: majedkot0@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fd6d1871acf14d4b

**Comment by mejed-alkoutaini** [comment] 2023-07-14 23:11
Why it's tagging another person! and why I always have to store my contributor details again and again, 😅 anyway I applied to the Upwork job 🙌🏻

**Comment by iwiznia** [comment] 2023-07-21 20:10
@roryabraham reassigning this to you since you already have some context and I am going on sabbatical. Feel free to ask for a fair reassignment via auto assigner

**Comment by roryabraham** [comment] 2023-07-22 08:16
np, I can take this one 👍🏼

**Comment by MitchExpensify** [comment] 2023-07-28 13:04
- Hired @mejed-alkoutaini 
- Hired @bernhardoj 
- @Santhosh-Sellavel will be compensated via NewDot 

Reporting: $250
C: $1000
C+: $1000 (Via NewDot to @Santhosh-Sellavel)

👍

**Comment by roryabraham** [comment] 2023-08-07 19:24
@MitchExpensify seems like we just need to finish issuing payments here?

@Santhosh-Sellavel did you request money via NewDot?

**Comment by Santhosh-Sellavel** [comment] 2023-08-08 21:16
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/12168
> * [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/12168#issuecomment-1670316755
> * [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://expensify.slack.com/archives/C049HHMV9SM/p1691529374343869
> * [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A
> * [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
> * [ ]  [@MitchExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by MitchExpensify** [comment] 2023-08-09 22:09
All paid and contracts ended via Upwork! 

Just waiting for confirmation of @Santhosh-Sellavel 's payment via NewDot to close this out

**Comment by Santhosh-Sellavel** [comment] 2023-08-10 03:01
Requested on ND

**Comment by MitchExpensify** [comment] 2023-08-14 16:57
Great, let's close this out once ND payment is confirmed!

**Comment by JmillsExpensify** [comment] 2023-08-15 16:36
Reviewed the details for @Santhosh-Sellavel. Approved for payment in ND based on the summary from BZ above.

**Closed by JmillsExpensify** 2023-08-15 16:36 UTC
Labels: External, Daily, Awaiting Payment, Bug
