### ISSUE TITLE
[PENDING BUG REPORT PAYOUT][$500] Dev: Can't request money using Distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30022] opened 2023-10-19 20:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.87.0
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697736215925649

## Action Performed:
1. Click on the "+" button or go to the expense room.
2. Navigate to Request money > Distance.
3. Select the Start and Finish points and send the request.
4. Go to the distance request detail page.
5. Attempt to send it.
6. Observe that the send button is disabled without any error message

## Expected Result:
The Distance "Request" button should not be disabled without showing an error message

## Actual Result:
 The Distance "Request" button is disabled without any error message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/17c13451-cc07-4d25-ad5a-c6a1a384e982

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/9025440e-8120-45ad-99e7-9d00de0a7053

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6db67e0d-3855-4052-94fd-e2415159d623

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/3fd879cf-a53c-4699-b183-151c9690f7ee

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/d7d5fb4d-1b17-4dda-9856-22e8254de363

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/8029d4fb-2930-48c9-b4b1-76a81fff9011

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fce63774ec87caa</li>
        <li>Upwork Job ID: 1715097232167661568</li>
        <li>Last Price Increase: 2023-10-19</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-10-19 20:25
I'm heading ooo and need to reassign this.

**Comment by incregeni** [comment] 2023-10-19 20:33
I am interested in

**Comment by Izurii** [comment] 2023-10-19 20:57
Contributor details
Your Expensify account email: heitor_massarente@msn.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0151fd6281bfe00ecc

**Comment by ChrissieBosman** [comment] 2023-10-19 23:48
Contributor details
Your Expensify account email: chrissiebosmanwork@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0195025a8dee38e619

**Comment by ChrissieBosman** [comment] 2023-10-19 23:49
Contributor details
Your Expensify account email: [chrissiebosmanwork@gmail.com](mailto:chrissiebosmanwork@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0195025a8dee38e619

**Comment by ChrissieBosman** [comment] 2023-10-19 23:52
Contributor details
Your Expensify account email: [chrissiebosmanwork@gmail.com](mailto:chrissiebosmanwork@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/~0195025a8dee38e619](url)

**Comment by pecanoro** [comment] 2023-10-20 00:43
Adding a deploy blocker to this issue since this one is pretty bad as it broke the whole distance functionality, some recent PR must have broken it

**Comment by thienlnam** [comment] 2023-10-20 00:48
This should be resolved now, 

This was the [PR](https://github.com/Expensify/App/pull/27547#issuecomment-1771692897) that caused the regression, we ended up reverting it in this [PR](https://github.com/Expensify/App/pull/30040) to solve a different regression

**Comment by thienlnam** [comment] 2023-10-20 00:52
Going to run through the steps just to verify very quickly

**Comment by thienlnam** [comment] 2023-10-20 00:55
Yup verified 👍 Leaving this open for bug report though

**Comment by garrettmknight** [comment] 2023-10-23 18:35
@ayazhussain79 offer out to you for the reporter role - accept and I'll pay!

**Comment by ayazhussain79** [comment] 2023-10-23 18:42
@garrettmknight Offer accepted, Thank you

**Comment by garrettmknight** [comment] 2023-10-23 19:02
Paid, closing!

**Closed by garrettmknight** 2023-10-23 19:02 UTC
Labels: Daily, Bug
