### ISSUE TITLE
[$250] LHN - GBR not displayed in LHN for employee until the workspace chat opened

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40241] opened 2024-04-15 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4490029&group_by=cases:section_id&group_id=296773&group_order=asc
**Email or phone of affected tester (no customers):** hohovemgo+employee36@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user has created collect workspace as admin and invited employee to the workspace
1. Open app
2. Sign In as employee
3. Navigate to workspace chat
4. Create a Money Request
5. Navigate to LHN or select other chat in case if you testing on landscape view
6. In OD as admin set the Scheduled Submit as Manually
7. In ND Observe workspace chat status in LHN
8. Tap on the workspace chat in ND
9. Navigate back to LHN in ND
10. In ND Observe workspace chat status in LHN

## Expected Result:
GBR should be displayed in LHN for employee when admin set Scheduled Submit as Manual

## Actual Result:
GBR not displayed in LHN for employee until user open workspace chat with unsubmitted expense and navigate back to LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/41e55bdb-8d0e-4d20-8882-1ad27555695c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d40d6b8aee046bd</li>
        <li>Upwork Job ID: 1783252867850891264</li>
        <li>Last Price Increase: 2024-05-01</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-15 14:36
We think this issue might be related to the #collect project.

**Comment by johncschuster** [comment] 2024-04-15 19:12
@izarutskaya Why do you think `GBR should be displayed in LHN for employee when admin set Scheduled Submit as Manual`? I'm under the impression GBR is displayed when a user needs to take action on some kind of violation. What action do you think the user needs to take after the admin has changed Scheduled Submit to `manual`?

**Comment by nkdengineer** [comment] 2024-04-16 05:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
GBR not displayed in LHN for employee until user open workspace chat with unsubmitted expense and navigate back to LHN

### What is the root cause of that problem?
We show the GBR if the report has no error has `ReportUtils.requiresAttentionFromCurrentUser` returns `true`. When we change the `Scheduled Submit` in OD, no GBR appears in LHN because `hasOutstandingChildRequest` of the report is still `false`. After we open this report again, `OpenReport` API is called and backend returns `hasOutstandingChildRequest` as `true` and then GBR appears.

https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/components/LHNOptionsList/OptionRowLHN.tsx#L56


### What changes do you think we should make in order to solve the problem?
We should check if the policy expense chat has unsubmit transaction and the `autoReporting` of the policy is false we will display GBR in LHN. That will make sure GBR will be displayed in LHN correctly even we don't open this report again.

1. In `ReportUtils`, create util like `hasUnSubmitTransaction` that will return true if at least one report preview action is unsubmited

```
function hasUnSubmitTransaction(reportActions: OnyxEntry<ReportActions>) {
    return Object.values((reportActions ?? {}) as ReportActions).some((action) => {
        if (!ReportActionsUtils.isReportPreviewAction(action)) {
            return false;
        }
        const IOUReportID = ReportActionsUtils.getIOUReportIDFromReportActionPreview(action);
        const iouReport = getReport(IOUReportID);
        const {reimbursableSpend} = getMoneyRequestSpendBreakdown(iouReport);
        return isOpenExpenseReport(iouReport) && reimbursableSpend !== 0;
    });
}
```



2. We should return an extra field in `getOptionData` like `shouldShowGreenDotIndicator` 

https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/SidebarUtils.ts#L189

with default value is `false` here

```
shouldShowGreenDotIndicator: false
```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/SidebarUtils.ts#L240

And update this here like this

```
result.shouldShowGreenDotIndicator = !result.brickRoadIndicator && (ReportUtils.requiresAttentionFromCurrentUser(report, parentReportAction) || (ReportUtils.hasUnSubmitTransaction(reportActions)) && !policy?.autoReporting)

```
https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/libs/SidebarUtils.ts#L286

3. In `OptionRowLHN`, we will replace `shouldShowGreenDotIndicator` here with `optionItem. shouldShowGreenDotIndicator`

https://github.com/Expensify/App/blob/90412ec0c38cc1ccd0a1198cf1f4712474667906/src/components/LHNOptionsList/OptionRowLHN.tsx#L56
### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-04-24 21:48
I'm still not sure if this is a bug. I've raised a discussion [here](https://expensify.slack.com/archives/C03U7DCU4/p1713995264301859)

**Comment by johncschuster** [comment] 2024-04-24 21:53
Ok! I've got confirmation that the expected behavior is correct! Triaging!

**Comment by kmbcook** [comment] 2024-04-24 22:22
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
GBR not displayed in LHN for employee until the workspace chat opened

### What is the root cause of that problem?
See below: triggerUnreadUpdate is automatically run in response to changes in reports and in navigation state, but not in response to change in workspace scheduled submit.

https://github.com/Expensify/App/blob/9a727de1e67013a8baf2dff018063af03d963ada/src/libs/UnreadIndicatorUpdater/index.ts#L46-L57

### What changes do you think we should make in order to solve the problem?
Automatically run triggerUnreadUpdate when policies change too.

**Comment by DylanDylann** [comment] 2024-04-30 16:55
In this case, the green dot should display because in this report we have a request that requires action from the current user.  Thus, in this case, we should handle it from BE. On the other hand, we can make a workaround in the FE as @nkdengineer's solution. Leave the final decision to the internal engineer  
 
🎀👀🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-05-02 04:00
> Thus, in this case, we should handle it from BE to return hasOutstandingChildRequest is true as this comment

I think this bug should be fixed in FE because it doesn't make sense to update `hasOutstandingChildRequest` of all related reports of the workspace via pusher when we change the `Scheduled  submit` on OD and when we open the report BE return `hasOutstandingChildRequest` correctly in `OpenReport` API.

**Comment by DylanDylann** [comment] 2024-05-03 18:24
Waiting for @jasperhuangg's decision on [this comment](https://github.com/Expensify/App/issues/40241#issuecomment-2085987328)

**Comment by jasperhuangg** [comment] 2024-05-03 18:26
@DylanDylann thanks for the bump, I can check on the backend solution for this issue.

**Comment by jasperhuangg** [comment] 2024-05-06 16:58
Taking a look at this today

**Comment by jasperhuangg** [comment] 2024-05-06 23:04
After reading over the OP I think this is a really specific edge case that doesn't require our attention now. If people feel differently then they can reopen it. Changing the auto report frequency is something that should happen extremely infrequently.

**Closed by jasperhuangg** 2024-05-06 23:04 UTC
Labels: External, Daily, Help Wanted, Bug
