### ISSUE TITLE
[HOLD for payment 2024-10-29] [HOLD for payment 2024-10-25] [$250] Receipt - Receipt 3dots menu doesn't show options to replace and delete receipt

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50980] opened 2024-10-17 08:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open 1:1 with an user (or workspace chat)
3. Submit an expense
4. Open the expense
5. Tap plus placeholder and using camera upload an image
6. Tap on receipt -- 3 dots
7. Note the receipt options

## Expected Result:
Receipt 3dots menu must show options to replace and delete receipt.

## Actual Result:
Receipt 3dots menu doesn't show options to replace and delete receipt.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/75a0f39e-fe5c-4012-a092-e7bd47b2aab4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021846827472906199686</li>
        <li>Upwork Job ID: 1846827472906199686</li>
        <li>Last Price Increase: 2024-10-17</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 104459504</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @RachCHopkins</details>

**Comment by mkzie2** [comment] 2024-10-17 08:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt 3dots menu doesn't show options to replace and delete receipt.

### What is the root cause of that problem?

The `readonly` route param here is parsed as string:

https://github.com/Expensify/App/blob/9f8e8c5abcb7c3d842398de18a516eb8b79d36ce/src/pages/TransactionReceiptPage.tsx#L30

so when it is `"false"` (string), the `canEditReceipt` here is `false` (because `!"false"` is boolean `false`)

https://github.com/Expensify/App/blob/9f8e8c5abcb7c3d842398de18a516eb8b79d36ce/src/pages/TransactionReceiptPage.tsx#L75

And eventually we cannot edit the receipt (neither replace nor delete)

### What changes do you think we should make in order to solve the problem?


Explicitly check if `route.params.readonly === 'true'`

**Comment by Beamanator** [comment] 2024-10-17 08:40
Ooh your change does look like it fixes the problem 👍 👍 🎉  though I'm still curious to try to find any regressed PR(s) if possible!

**Comment by Pujan92** [comment] 2024-10-17 08:41
@mkzie2's RCA and proposal looks correct, let me also find the offended PR

**Comment by huult** [comment] 2024-10-17 08:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Receipt 3dots menu doesn't show options to replace and delete receipt 

### What is the root cause of that problem?

This issue happend by [this pull request](https://github.com/Expensify/App/commit/01a9daad5c2b56c5461cc6eaccd7bb6b6aaf7aef#diff-8c80af31c75a0f4fcb67272bd2df5b42c9611c040ecc66584fcd6bde05dbbd78L1180). 

`receipt${readonly ? '?readonly=true' : ''}$` to  changed `readonly=${readonly}`

So the condition here returns the string 'false', which causes this issue during the check
https://github.com/Expensify/App/blob/cd2c7ddc3f6e063c3b0648d3326495ddede3f7b1/src/pages/TransactionReceiptPage.tsx#L30

### What changes do you think we should make in order to solve the problem?
We need to update condition
```diff
//.src/pages/TransactionReceiptPage.tsx#L74
canEditReceipt={canEditReceipt && route.params.readonly === 'false'}
```

### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-10-17 08:45
Offending PR https://github.com/Expensify/App/pull/50546. Explicitly [this change](https://github.com/Expensify/App/pull/50546/files#diff-8c80af31c75a0f4fcb67272bd2df5b42c9611c040ecc66584fcd6bde05dbbd78L1179). Before that we never have `readonly=false`, only `readonly=true`.

**Comment by Beamanator** [comment] 2024-10-17 08:49
Wow good find both of y'all 😅 

So it sounds like that PR only really uncovered a bug in the [App/src/pages/TransactionReceiptPage.tsx](https://github.com/Expensify/App/blob/9f8e8c5abcb7c3d842398de18a516eb8b79d36ce/src/pages/TransactionReceiptPage.tsx#L75) file, right? If so, I think let's hire @mkzie2 to fix real quick

**Comment by mkzie2** [comment] 2024-10-17 08:50
@Pujan92 I added an [alternative solution](https://github.com/Expensify/App/issues/50980#issuecomment-2418894460), which one should we proceed?

**Comment by Pujan92** [comment] 2024-10-17 08:51
Yes @Beamanator, I think so.

**Comment by Pujan92** [comment] 2024-10-17 08:53
> @Pujan92 I added an [alternative solution](https://github.com/Expensify/App/issues/50980#issuecomment-2418894460), which one should we proceed?

As route param will always be a string then I believe it is better to proceed with your main solution which is to check value 'true'

**Comment by Beamanator** [comment] 2024-10-17 08:54
Also @mkzie2 please make this a priority today since this is a deploy blocker 🙏

**Comment by Beamanator** [comment] 2024-10-17 10:46
Successfully CP'd! @mkzie2 @Pujan92 can y'all please test on staging to make sure this is fixed? 🙏

**Comment by Pujan92** [comment] 2024-10-17 12:06
@Beamanator Just verified in staging and it gets fixed. 👍

**Comment by Beamanator** [comment] 2024-10-17 12:19
Amazing! Thanks!

**Comment by Christinadobrzyn** [comment] 2024-10-21 03:49
HI there, just checking to see if this might be a regression https://github.com/Expensify/App/issues/51142

**Comment by Beamanator** [comment] 2024-10-21 08:24
Hmm @Christinadobrzyn that seems unlikely b/c the fix for this issue is now in production 🤔

**Comment by RachCHopkins** [comment] 2024-10-25 05:43
@Pujan92 can you please complete the checklist so that I can issue payment?

**Comment by Pujan92** [comment] 2024-10-25 10:52
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/47536
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/47536/files#r1816465370
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. Yes
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. Submit an expense and add a receipt to it
2. Goto that expense and open an image modal
3. Click on 3 dots menu
4. Verify Replace and Delete receipt options are shown

**Comment by RachCHopkins** [comment] 2024-10-29 05:02
Will pay this tomorrow!

**Comment by RachCHopkins** [comment] 2024-10-30 00:03
Payment Summary:

Contributor: @mkzie2 paid $250 via Upwork
Contributor+: @Pujan92 to be paid $250 via Newdot manual request
Upwork job [here](https://www.upwork.com/jobs/~021846827472906199686)

**Comment by RachCHopkins** [comment] 2024-10-30 00:11
Contributor has been paid, the contract has been completed, and the Upwork post has been closed.

**Closed** 2024-10-30 00:13 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-11-06 12:02
$250 approved for @Pujan92
