### ISSUE TITLE
[$500] Wallet - Radio buttons in questionnaire page have a different design

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32119] opened 2023-11-28 13:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** cannot check production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31050

## Action Performed:
Precondition: User has added a bank account.
1. Navigate to staging.new.expensify.com
2. Go to Settings > Wallet > Enable wallet.
3. Proceed to questionnaire page.

## Expected Result:
The radio button has a tick in the button when unchecked and has green background when selected (Please refer to PR attachment).

## Actual Result:
The radio button does not have a tick in the button when unchecked and does not have a green background when checked (different radio button from PR).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

**Staging** 
![Screenshot 2023-11-28 at 13 30 50](https://github.com/Expensify/App/assets/93399543/c1f61cbd-7578-411f-a385-9bc4918ddb59)

**PR** 
![Screenshot 2023-11-28 at 13 32 03](https://github.com/Expensify/App/assets/93399543/d4d8de5c-289b-4c00-a4d5-148b2ca09e07)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3dc5fe1ec3e1343</li>
        <li>Upwork Job ID: 1729517232411906048</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-28 15:33
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Wallet - Radio buttons in questionnaire page have a different design

## What is the root cause of that problem?

I don't know why this is a bug
Because the styles that are used are in the RadioButton component

## What changes do you think we should make in order to solve the problem?

We can update styles like

```
            <View style={[styles.radioButtonContainer, hasError && styles.borderColorDanger, disabled && styles.cursorDisabled, isChecked ? {backgroundColor: theme.checkBox} : {}]}>
                <Icon
                    src={Expensicons.Checkmark}
                    fill={theme.white}
                    height={14}
                    width={14}
                />
            </View>
```

https://github.com/Expensify/App/blob/5eea6289a1bcbb36115a8bc31598e9105ebe16cd/src/components/RadioButton.tsx#L40-L50


## What alternative solutions did you explore? (Optional)
NA (edited)

**Comment by dangrous** [comment] 2023-11-30 22:35
Yep! Staging is correct, this is an intentional update - to double check cc @dubielzyk-expensify but I think we're good

**Comment by miljakljajic** [comment] 2023-12-04 12:55
So this is expected? Should we close?

**Comment by mananjadhav** [comment] 2023-12-04 13:05
Yes @miljakljajic we should close this one out.

**Closed** 2023-12-08 10:13 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
