### ISSUE TITLE
[$500] Category & Tag - "Required" is not shown next to Category and Tag in request details page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34363] opened 2024-01-11 14:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace
- Category and Tag are set to require on Old Dot
1. Navigate to workspace chat
2. Create a bill split
3. Click on the bill split preview
4. Note that "Required" is shown next to Category and Tag in the split details view
5. Create a manual request
6. Go to the request details page

## Expected Result:
"Required" is shown next to Category and Tag in the details view

## Actual Result:
There is no "Required" next to Category and Tag in the details view

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1c02a45f-3b8c-45f7-b2db-4e7e5c218795

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a5c37c32ad77a5d</li>
        <li>Upwork Job ID: 1745457868659580928</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2024-01-17 14:57
I'm pretty this is by-design so far, but I'm double-checking in [an internal channel](https://expensify.slack.com/archives/C03U7DCU4/p1705503427648659).

**Comment by conorpendergrast** [comment] 2024-01-19 20:58
Wait, I may be wrong again

**Comment by conorpendergrast** [comment] 2024-01-19 21:02
@cead22 based on [this message](https://expensify.slack.com/archives/C02MW39LT9N/p1705623365267159) (internal channel), it looks like only users from domains added to the beta will show the categories or tags required at this point. So I think that this is not a bug and is as-designed so far (while we're implementing and rolling that out). 

I'll close this, but reopen if I'm wrong!

**Closed by conorpendergrast** 2024-01-19 21:02 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by cead22** [comment] 2024-01-19 21:06
This is working fine, but the reason is that we only show the Required when creating money requests, not when updating them, so if you create one and come back to it later, the Required label should not be there.

The reason is, once the money request is created, if the category is required you won't see the Required label but instead you'll see a Missing Category violation. I'm guessing it's not showing in this case because of the beta
