### ISSUE TITLE
[$1000] Referral program - Console error on help.expensify.com page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21827] opened 2023-06-28 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21241
## Action Performed:
1. Login to NewDot
2. Go to help.expensify.com
3. Go to others > Referral program

## Expected Result:
No console errors

## Actual Result:
Console error appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/45110dee-1a7e-4e2d-a6b6-180d74cbf1eb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6f48f866029666f</li>
        <li>Upwork Job ID: 1674884321258209280</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-06-30 20:56
Reproduced, but I can also see the web page, so I'm not sure how much of an issue this is. 

<img width="1350" alt="image" src="https://github.com/Expensify/App/assets/22508290/8e687eb0-24a9-48f5-84a2-00e6b4786dc4">

**Comment by kevinksullivan** [comment] 2023-07-06 16:29
@rushatgabhane can you provide an ETA on reviewing proposals?

**Comment by kevinksullivan** [comment] 2023-07-10 17:07
Still waiting on proposals and reviews from @rushatgabhane

**Comment by rojiphil** [comment] 2023-07-11 11:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a console error "Refused to execute inline script..." which comes up on launching help.expensify.com. We are trying to remove the console error.

### What is the root cause of that problem?
The root cause of the issue seems to be with the script injected by Cloudflare. The script is injected when Bot Management is enabled. Since this code also depends on dynamic creation of script elements, the console error shows up.

The following script is injected at the end of the index.html file by Cloudflare (can be located in browser console) .
```
<
script > (function() {
    var js = "window['__CF$cv$params']={r:'7e4e0fad8ef01d3d',m:'wG5HPO3QnVOBt5Jt_Wq3nuYeQhCTgi4FQ2.VOGD8DSo-1689047206-0-Ae/ASQ/1IYofYD1rFikbs+oAcyS0U/zve6C8CX8RnsIU'};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/invisible.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";
    var _0xh = document.createElement('iframe');
    _0xh.height = 1;
    _0xh.width = 1;
    _0xh.style.position = 'absolute';
    _0xh.style.top = 0;
    _0xh.style.left = 0;
    _0xh.style.border = 'none';
    _0xh.style.visibility = 'hidden';
    document.body.appendChild(_0xh);

    function handler() {
        var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;
        if (_0xi) {
            var _0xj = _0xi.createElement('script');
            _0xj.nonce = '';
            _0xj.innerHTML = js;
            _0xi.getElementsByTagName('head')[0].appendChild(_0xj);
        }
    }
    if (document.readyState !== 'loading') {
        handler();
    } else if (window.addEventListener) {
        document.addEventListener('DOMContentLoaded', handler);
    } else {
        var prev = document.onreadystatechange || function() {};
        document.onreadystatechange = function(e) {
            prev(e);
            if (document.readyState !== 'loading') {
                document.onreadystatechange = prev;
                handler();
            }
        };
    }
})(); < /script></body >
```

### What changes do you think we should make in order to solve the problem?

The following change are required in [_layouts\default.html](https://github.com/Expensify/App/blob/38890e2e3c32b52dad11a7dfc09494924519946b/docs/_layouts/default.html#L5C5-L5C5)

a) As per [Cloudflare CSP recommendation](https://developers.cloudflare.com/bots/reference/javascript-detections/#if-you-have-a-content-security-policy-csp), usage of `nonce` will help in resolving this issue.
b) Since the injected script by Cloudflare also uses `document.createElement('script')`, we will have to use `script-dynamic` as follows. [Reference documentation is here](https://content-security-policy.com/#:~:text=%27strict%2Ddynamic%27,script%27)

```
- <meta http-equiv="Content-Security-Policy" content="script-src ...
+ <meta http-equiv="Content-Security-Policy" content="script-src 'strict-dynamic' 'nonce-2726c7f26c' ...
```

c) Since `strict-dynamic` is present, host-based allowlisting will be disabled. This would mean that the `nonce` must be used for other scripts as well.
e.g.

```
-   <script src="https://kit.fontawesome.com/263e5e8608.js" crossorigin="anonymous"></script>
+   <script nonce="2726c7f26c" src="https://kit.fontawesome.com/263e5e8608.js" crossorigin="anonymous"></script>
```

### What alternative solutions did you explore? (Optional)
- Not sure if Bot Management is consciously enabled here by Expensify. If not required, we can disable the Bot Management. Then, that is the only thing to do.
- Also, can this be a virus? A search in google did not give any evidence for this. So, didn't pursue in this direction.

**Comment by rojiphil** [comment] 2023-07-12 12:50
@kevinksullivan @rushatgabhane  Can you please have a look at my proposal? I just want to rule out something suspicious happening to the help.expensify.com site.
Here is a video that points out the issue:

https://github.com/Expensify/App/assets/3004659/41593410-0321-4d74-9751-8f1db7207c1e

**Comment by rushatgabhane** [comment] 2023-07-13 05:47
reviewing today

**Comment by kevinksullivan** [comment] 2023-07-17 15:39
@rushatgabhane can you provide an update on the reviews?

**Comment by rushatgabhane** [comment] 2023-07-21 16:02
hi, im not confident about reviewing and recommending the right proposals. asking for help on c+ channel

**Comment by rojiphil** [comment] 2023-07-21 19:14
@allroundexperts  I fail to understand how the backend is going to solve this issue. Can you please elaborate on this?

**Comment by kevinksullivan** [comment] 2023-07-24 19:14
Going to close this out then @justinpersaud 👍

**Closed by kevinksullivan** 2023-07-24 19:14 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
