### ISSUE TITLE
[$250] Web - VBA - Complete verification step appears again after confirmation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38880] opened 2024-03-23 15:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/2950426
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in with a applause.expensifail account (that does not have any bank account already added)
2. Navigate to the add bank account modal
3. Select the Manual method to add a bank account
4. Procced the flow until the final step 'Complete Verification'
5. Mark all checkboxes > click 'Save & Continue'

## Expected Result:
"Validate your bank account" page is displayed

## Actual Result:
'Complete Verification' page is displayed again with unchecked checkboxes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6c9770ae-d253-4e13-a0e6-b1489d0c3f2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce37badb4c0cec2d</li>
        <li>Upwork Job ID: 1774905029376946176</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @nkuoch</details>

**Comment by lanitochka17** [comment] 2024-03-23 15:08
@isabelastisser  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mmmbytes** [comment] 2024-04-05 03:20
@thesahindia @lanitochka17 

Hi! I'm currently investigating this bug and have been searching through the documentation and contributor guidelines for information on applause.expensifail accounts, but haven't found any relevant details. Could someone guide me on how to access one of these accounts on the staging environment? Thank you!

**Comment by isabelastisser** [comment] 2024-04-05 16:47
Not overdue.

**Comment by isabelastisser** [comment] 2024-04-05 16:48
@thesahindia @lanitochka17, can you please follow up on this comment? Thanks!

https://github.com/Expensify/App/issues/38880#issuecomment-2038767296

**Comment by lanitochka17** [comment] 2024-04-05 17:15
@mmmbytes  Hello. The tester used this account on the  staging  environment: applausetester+bp022124@applause.expensifail.com

**Comment by isabelastisser** [comment] 2024-04-10 19:47
@thesahindia can you please provide an update here? Thanks!

**Comment by mvtglobally** [comment] 2024-04-12 05:29
Issue not reproducible during KI retests. (First week)

**Comment by isabelastisser** [comment] 2024-04-15 17:07
Not overdue, but needs an internal engineer assignment.

**Comment by isabelastisser** [comment] 2024-04-19 17:28
Needs an internal engineer assignment.

**Comment by trjExpensify** [comment] 2024-04-24 23:27
To put this on the radar of internal engineers looking to pick up issues, we need to move it into `Hot Picks` and add the label. I've done that now for yah! CC: @nkuoch @MariaHCD who might have some context on the VBBA flow here.

**Comment by isabelastisser** [comment] 2024-04-29 18:24
Not overdue.

**Comment by isabelastisser** [comment] 2024-05-01 16:52
Not overdue. Waiting for assignment.

**Comment by isabelastisser** [comment] 2024-05-07 01:05
Not overdue. Waiting for assignment.

**Comment by nkuoch** [comment] 2024-05-07 08:27
I tried on staging and couldn't reproduce. Closing. Please reopen if you still can

**Closed by nkuoch** 2024-05-07 08:27 UTC
Labels: Daily, Internal, Bug, Hot Pick
