### ISSUE TITLE
[Ready for C+ payment via Newdot][$1000] Web - Chat - The flags list are still open even when the attachment was deleted from sender's side

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20674] opened 2023-06-13 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Go to a chat with User B and send an attachment
3. Login with User B on another web chrome (Place the window side by side to make work easier)
4. Now from User B, click on offensive message icon and notice that a list of flags appears (do not close it)
5. From User A account, delete the attachment
6. On User B side notice that even when the attachment are already deleted from User A side , the flags menu is still opened, and if you click on bullying flag, it shows shows a warning message even for an empty attachment message.

## Expected Result:
The flags list should not be open when the attachment was deleted from the sender's side

## Actual Result:
The flags list are still open even when the attachment was deleted from sender's side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/19879b84-53f7-478a-b5b3-be3d63373abc

https://github.com/Expensify/App/assets/93399543/6653d7ae-4a62-4236-8cef-c855b36e33b9

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686207956963489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127efb9c7f0ca6faa</li>
        <li>Upwork Job ID: 1668865351377502208</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-14 06:17
Reproduced:

https://github.com/Expensify/App/assets/59587260/01159abc-9707-4a64-bc04-c56343fa4ac3

**Comment by spcheema** [comment] 2023-06-14 14:54
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
The flags list remains open when an attachment is deleted from sender side
 

**What is the root cause of that problem?**

There is no check to verify if a report is deleted or not



**What changes do you think we should make in order to solve the problem?**

We need to add a check for deleted report inside the `flagComment` method and use `useEffect` to trigger close model in the case of report is deleted

```javascript
 const flagComment = (severity) => {
        let reportID = getReportID(props.route);

        // Handle threads if needed
        if (reportAction === undefined) {
            reportID = ReportUtils.getParentReport(props.report).reportID;
            reportAction = ReportActionsUtils.getParentReportAction(props.report);
        }

        React.useEffect(() => {
            if (ReportActionsUtils.isDeletedAction(reportAction)) {
                Navigation.dismissModal();
            }
        }, [reportAction]);
        Report.flagComment(reportID, reportAction, severity);
        Navigation.dismissModal();
    };

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by dangrous** [comment] 2023-06-16 17:55
Huh, this is an interesting case. I think we wouldn't want the pane to automatically close because I think that would be confusing for the person who was using it.

My only question (I have not tested this), is there an error if the flagger chooses an option in this case, or does just nothing happen? If nothing happens, I think we can close this bug. If there's an error, we probably want to update it to notify the flagger that the comment no longer exists, and hide the error.

**Comment by francoisl** [comment] 2023-06-16 21:00
> Once the message is fully deleted, shouldn't the report action be removed fully from the front end

Good point, I wasn't sure so I asked internally, and so basically we could make that change in the backend but it might not be super obvious as there would be other things to take into account like the Unread message marker for example.

I'm thinking for now, we can probably do one of the front-end solutions proposed initially, to hide the hide panel. That said, both proposals define the `useEffect()` inside the function `flagComment`, which AFAIK they shouldn't.

**Comment by dangrous** [comment] 2023-06-16 21:37
Ah yeah, I guess I was combining two things. To clarify (mostly for me):
* The bug listed in this particular issue - I'm not sure we need to fix, as long as it doesn't break things elsewhere. I think it would be more confusing for the flagger for that pane to suddenly close if the author deleted their comment. I'd prefer it to stay open, allow the flagger to flag, and then just do nothing.
* [This](https://github.com/Expensify/App/issues/20674#issuecomment-1595083152) is a different bug, which is more related to my question [here](https://github.com/Expensify/App/issues/20674#issuecomment-1595091111).

**Comment by kadiealexander** [comment] 2023-06-19 06:11
@michaelhaxhiu since this is actively seeking proposals I've reassigned to ensure things move along while I'm OOO this week. If we don't land on a proposal by Tuesday your time please take action, otherwise I'll pick this up when I'm back next Monday! Thanks so much!

**Comment by dangrous** [comment] 2023-06-20 17:09
Hm, so there's an existing bug with a known (just not implemented) solution that I think would fix that as well. That should be up soon.

It also looks like in the video you're providing a fake reportID via the URL, right? Can you try it again with a message that's been deleted from another account, while the window is open? Or let me know if I'm misunderstanding.

**Comment by francoisl** [comment] 2023-06-20 18:04
Being able to see the panel with a fake/invalid report ID sounds like a different issue.

Also looks like the issue from https://github.com/Expensify/App/issues/20674#issuecomment-1595083152 may have been resolved? On dev, I don't see the "Reveal message" button anymore.


https://github.com/Expensify/App/assets/2229301/291de961-0cf7-453f-b72e-fd0986fa04e2

**Comment by Santhosh-Sellavel** [comment] 2023-06-22 20:01
@francoisl @dangrous I'm kind of confused here, what should we do here?

**Comment by francoisl** [comment] 2023-06-23 00:31
Ya sorry, let me try to summarize and clarify:

- Both @dangrous and I agree that we shouldn't close the flag modal when the comment is deleted. It would be confusing for the flagger, as Daniel explains [here](https://github.com/Expensify/App/issues/20674#issuecomment-1595342162)
- I tried reproducing the issue that @dukenv0307 showcased in [this comment](https://github.com/Expensify/App/issues/20674#issuecomment-1595083152), where the "Reveal" button is displayed after flagging a deleted comment, but couldn't reproduce it. You can see the video in my last comment [here](https://github.com/Expensify/App/issues/20674#issuecomment-1599267087).

So I'm thinking, can someone confirm if the reveal button no longer appears after flagging a deleted comment? If so, we can close this issue.

**Comment by dangrous** [comment] 2023-06-23 14:21
hm that's an interesting note - it's two different things:
* appearing and then disappearing is the optimistic data from the flag getting set, and then immediately being removed by the update from the server that the message is gone. That's almost certainly something we could fix on the front end
* Not sending the Concierge message if the message has already been deleted is an interesting idea - I'm not 100% sure it would be worth doing but we certainly **could**. @francoisl that one would be a backend fix

**Comment by Santhosh-Sellavel** [comment] 2023-06-23 21:10
I can see the Reveal Message button for a while!

https://github.com/Expensify/App/assets/85645967/f1b89886-1de3-465d-9303-b9cb3ddabcd6

**Comment by francoisl** [comment] 2023-06-23 22:58
Ok so how about:

- For now, we update the frontend so that it doesn't show "This message has been flagged.... [Reveal message]" when flagging a comment that has been deleted while the flag page was open
    - We'd still keep the Flag page open if the message is deleted by the sender, so this would require new proposals
- Separately, I'll look into updating the backend so that it doesn't send the Concierge message if the message has been deleted

**Comment by kadiealexander** [comment] 2023-06-26 03:08
Thanks for the help while I was away, @michaelhaxhiu!

**Comment by kadiealexander** [comment] 2023-06-26 03:25
@Santhosh-Sellavel do you have any thoughts on these two updated proposals? 

https://github.com/Expensify/App/issues/20674#issuecomment-1589302534
https://github.com/Expensify/App/issues/20674#issuecomment-1590620505

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 19:54
It's pretty much straightforward to post this [comment](https://github.com/Expensify/App/issues/20674#issuecomment-1605086286). Both proposals are similar here. With a few hours different @hungvu193 has been the earlier one and @dukenv0307 was the later one. 

IMO that hiring @dukenv0307 only is a fair decision here, as helped the issue move forward.
I'll let you make the final call here @francoisl 

C+ Reviewed
🎀 👀 🎀

**Comment by francoisl** [comment] 2023-06-26 23:30
Yes I agree, @dukenv0307 was active in  the discussions that led to the current proposals, and that's appreciated.
Let's go with your alternative proposal @dukenv0307.

**Comment by dangrous** [comment] 2023-06-30 16:04
I'll defer to you @francoisl!

For me, I think we could potentially keep both, since they're a bit different - I'd still prefer the flag comment page doesn't disappear in the middle of a user looking at it, but would otherwise show not found if it was clicked AFTER something was deleted. I'd also be okay with one of @dukenv0307's [suggestions](https://github.com/Expensify/App/issues/20674#issuecomment-1614747908), probably the first one, but I think that would be my second choice. This is all definitely personal opinion though.

**Comment by Santhosh-Sellavel** [comment] 2023-06-30 17:45
I'm confused here, I'll just wait for @francoisl!

**Comment by francoisl** [comment] 2023-06-30 19:00
Hmm yeah not ideal. @dukenv0307 can you think of a way to update your current PR so that it doesn't switch to the `FullPageNotFoundView` if the flag panel was already open before the comment got deleted, but without breaking your previous changes from https://github.com/Expensify/App/pull/21771?

**Comment by francoisl** [comment] 2023-07-03 21:08
> We want to just keep it for now and will display not found page if reload

Yes ^

> If we want to keep it we can remove the check !ReportActionsUtils.isDeletedAction(reportAction) in canFlagComment function. I think it fine because the deleted action will be hidden and canFlagComment still work as well to display flag icon or not.

That would sorta work but I think that solution has a disadvantage: if you reload the page while the flag page is open, we would still show the flag options for the deleted message.

I can't think of a solution that would basically act as follows:
- if the flag page is **already** open when the message gets deleted, then keep it open and do nothing when an option is chosen
- if the user reloads the page (or opens a `/flag/{reportID}/{reportActionID}` link) **after** the message got deleted, then show the PageNotFound

So taking all that into consideration, I'd say the next best option is to close this issue and the PR, and accept that the current behavior is expected.

**Comment by francoisl** [comment] 2023-07-05 17:54
Based on the 👍 reactions it seems like everyone agrees, so I'm going to close the issue and the PR. Thanks for the proposals and working with through together 🙌

**Comment by kadiealexander** [comment] 2023-07-25 01:35
Spoken about this privately and agreed to pay out contributor and C+ for this. I have sent Upwork contracts to both.

**Comment by kadiealexander** [comment] 2023-07-26 06:53
Payouts due:

- [ ] Issue Reporter: $250 @priya-zha
- [ ] Contributor: $X @dukenv0307 
- [ ] Contributor+: $X @Santhosh-Sellavel 

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/ab/applicants/1683651034399637504/job-details).

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 23:50
Requested $1k on ND

**Comment by JmillsExpensify** [comment] 2023-07-29 16:46
Reviewed details for @Santhosh-Sellavel. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-07-30 21:33 UTC
Labels: Reviewing, External, Weekly, Bug
