### ISSUE TITLE
Web - Resizing browser triggers reaction emoji picker to shift to LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21982] opened 2023-06-30 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Keep your browser in non full screen mode
4. Right click on any message and click on add reaction
5. Click on browser full screen mode and observe that emoji picker is shifted over LHN

## Expected Result:
 App should not display emoji picker on LHN

## Actual Result:
App displays reaction emoji picker on LHN when we resize browser

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**  v1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (7)](https://github.com/Expensify/App/assets/93399543/6c07eff5-1d55-4bc6-91c5-368f9443e0dd)

https://github.com/Expensify/App/assets/93399543/a2dac688-6d2d-4de7-af61-32079d484a75

**Expensify/Expensify Issue URL:**
**Issue reported by:** 1.3.34-1
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688053285771839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-06-30 20:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Resizing browser triggers reaction emoji picker to shift to LHN

### What is the root cause of that problem?

@samh-nl's root cause is correct

### What changes do you think we should make in order to solve the problem?

When vertical === 0 and horizontal === 0, leave it unchanged.

```
    if (value.vertical === 0 && value.horizontal === 0) {
        return;
    }

    setEmojiPopoverAnchorPosition(value);
```

This works as expected.

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by kadiealexander** [comment] 2023-07-03 06:49
Agreed, dupe of https://github.com/Expensify/App/issues/17603. Please post your proposals there. Thanks @daraksha-dk!

**Closed by kadiealexander** 2023-07-03 06:49 UTC
Labels: Daily, Bug
