### ISSUE TITLE
[$250] Unable to copy paste the part of the codeblock message 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42551] opened 2024-05-23 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716470973050419
  
## Action Performed:
1. Send a mutliline codeblock message to a chat
2. Select a part of the code and copy it using Cmd + C
3. Paste the code into the compose field in a line after typing "- "

## Expected Result:
Code should be pasted with no problem
## Actual Result:
Console error, sometimes crashing the app
Note: Doesn't crash for me

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/069e7e48-ae84-4e0e-866c-0d4f25453442

https://github.com/Expensify/App/assets/38435837/5b9eab09-bc8b-4a28-8034-316adfb47118

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01936d9219002e83a4</li>
        <li>Upwork Job ID: 1795874078765723648</li>
        <li>Last Price Increase: 2024-05-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by b4s36t4** [comment] 2024-05-29 19:34
I'm not able to repro this it's working fine for me.

**Comment by jayeshmangwani** [comment] 2024-05-30 07:19
@Beamanator Console error is the same root cause as this issue https://github.com/Expensify/App/issues/39971; either we can close or HOLD this issue for the other one

**Comment by Beamanator** [comment] 2024-05-30 07:22
Ooh nice find @jayeshmangwani , yes this looks like a dupe! closing

**Closed by Beamanator** 2024-05-30 07:22 UTC
Labels: External, Daily, Help Wanted, Bug
