### ISSUE TITLE
[HOLD E#326093] [$1000]  Chat inconsistency between User A and User B after a Request money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24042] opened 2023-08-02 09:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1) user A login
2) user A creates a money request for user B
3) user B login
4) user B pays request money from user A
5) user A writes a message in the IOU thread with user B, click send
6) user B cannot see the message
7) user B must exit the chat and enter again to be able to see the message sent by user A
## Expected Result: 
both users should be able to see chat messages the moment they are sent
## Actual Result: 
both users cannot see the chat messages at the time they are sent, one of the users must exit the chat to update
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2c1da535-cfd9-401e-8f5f-6e1d9a32683e

https://github.com/Expensify/App/assets/43996225/703cebfe-09c2-4c6d-b691-d411ee12332b

https://github.com/Expensify/App/assets/43996225/ec0e4c91-36ea-4001-a036-01c9dde1a3eb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690939247360729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106ee6101f89ce228</li>
        <li>Upwork Job ID: 1691926490954178560</li>
        <li>Last Price Increase: 2023-08-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @flodnv</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @flodnv</details>

**Comment by johncschuster** [comment] 2023-08-09 19:38
I haven't gotten to testing this behavior. I'll work on it this afternoon.

**Comment by johncschuster** [comment] 2023-08-16 21:41
Commenting to get Melvin to chill out with the Overdue label.

**Comment by Piotrfj** [comment] 2023-08-21 08:42
Hey, I'm Piotr from Callstack - expert contributor group - I would like to help resolve this issue

**Comment by Piotrfj** [comment] 2023-08-22 15:07
Update: I was able to reproduce the issue. Seems like it could be backend issue, I've checked in websocket and there were no events to add new report.

**Comment by johncschuster** [comment] 2023-08-28 14:10
@eVoloshchak do you agree with @Piotrfj that this could be a backend issue? If so, I'll make this internal.

**Comment by eVoloshchak** [comment] 2023-08-28 15:07
@johncschuster, yes, looks like this could be a backend issue, I also can't see any events. 
This isn't 100% reproducible though, it didn't work for me initially, but was working properly after I refreshed the browser  for user B

**Comment by johncschuster** [comment] 2023-08-29 20:00
Got it. Thanks for calling out the difficulty of reproducing this!

**Comment by flodnv** [comment] 2023-08-30 08:02
@mountiny @luacmartins what are your thoughts on this one? FWIW I'll be ooo for the next 10 days so if this is urgent we should reassign, or otherwise downgrade it to weekly.

**Comment by luacmartins** [comment] 2023-08-30 16:38
Can we consistently reproduce this issue? It seems like we had some issue in the past, which makes me think that's related to pusher being flaky and we could just close the issue. However, if we can consistently reproduce then I agree this is internal and has some urgency to it.

**Comment by johncschuster** [comment] 2023-08-30 18:39
I get the sense that we cannot reliably reproduce this issue but I could be wrong. @Piotrfj, are you able to clarify the reproduction steps to consistently reproduce this?

**Comment by Piotrfj** [comment] 2023-08-31 09:26
@johncschuster I also wasn't able to reproduce it every time, but it occurred in more than 50% trials.

**Comment by luacmartins** [comment] 2023-08-31 16:12
can we confirm that this is indeed 50%? It seems like this is just pusher being flaky at times, but I wouldn't expect it to be that high though.

**Comment by johncschuster** [comment] 2023-09-05 20:03
I'm not sure how I would confirm it's above or below 50% of the time. Is there a way to tell that Pusher is being flaky when we are testing this behavior? Like, how do we know if we can attribute the behavior to Pusher vs something else?

**Comment by luacmartins** [comment] 2023-09-05 23:52
@Piotrfj do you get the pusher events with the new comments? I took a look at the backend code and I couldn't find any logic that filters out events. So if you're not getting the pusher update, that means something must be happening on pusher's end.

**Comment by flodnv** [comment] 2023-09-11 05:49
Ping @Piotrfj ?

**Comment by Piotrfj** [comment] 2023-09-12 12:59
@luacmartins @flodnv Here is an example of websocket actions comparing IOU thread and normal thread


https://github.com/Expensify/App/assets/41384305/07ff3ed7-54c4-45f0-929e-1d0eec43d2ff


https://github.com/Expensify/App/assets/41384305/a51ac63e-fdef-4f3f-aca5-adffc97aa45f

As you can see in IOU thread frontend does not receive the 'reportComment' event.

**Comment by luacmartins** [comment] 2023-09-13 00:08
@Piotrfj I've found the WS console to be quite unreliable for inspecting these events. Could you try logging `pushJSON` [here](https://github.com/Expensify/App/blob/0ab130ce7e0d5243b55f84d6652e59a0c762c2a2/src/libs/actions/User.js#L584)? Do you still see the same results?

**Comment by johncschuster** [comment] 2023-09-13 14:38
(Bumping to make Melvin happy since Carlos' comment didn't count)

**Comment by Piotrfj** [comment] 2023-09-14 12:51
@luacmartins After debugging in proposed approach I've received this output:

<img width="467" alt="Zrzut ekranu 2023-09-14 o 11 26 44" src="https://github.com/Expensify/App/assets/41384305/dd84f886-92e0-4785-b063-54054db36d71">
<img width="455" alt="Zrzut ekranu 2023-09-14 o 11 27 01" src="https://github.com/Expensify/App/assets/41384305/efdf024d-e099-4980-af65-7738b02441c1">

First screen is presenting IOU thread, second one normal 1v1 thread.

**Comment by luacmartins** [comment] 2023-09-15 00:30
That response does indicate that we're missing the message in the update. We gotta investigate this internally then.

**Comment by flodnv** [comment] 2023-09-19 10:09
No updates, and probably none for a while.

**Comment by johncschuster** [comment] 2023-09-20 15:38
In that case, do we want to downgrade the label?

**Comment by flodnv** [comment] 2023-09-29 06:04
I can confirm I was able to reproduce this

**Comment by johncschuster** [comment] 2023-10-10 21:21
Nice one, @flodnv!

**Comment by johncschuster** [comment] 2023-10-19 20:42
No update here

**Comment by flodnv** [comment] 2023-10-24 12:24
No updates, still focusing on higher priority strategic projects.

**Comment by johncschuster** [comment] 2023-10-26 20:41
Thanks for the update, @flodnv! Should we downgrade the label on this one?

**Comment by flodnv** [comment] 2023-10-27 12:19
I did that but you undid that last week 😄

**Comment by flodnv** [comment] 2023-11-06 15:22
Still no update for now.

**Comment by flodnv** [comment] 2023-11-13 19:49
Sorry for the delay. Turns out user B will never receive the pusher update, does not matter how many message there are in the IOU thread, the backend was never sending it, so I fixed that 🙃 PR is in review...

**Comment by mountiny** [comment] 2023-11-15 11:59
I will put this on hold for internal issue https://github.com/Expensify/Expensify/issues/326093

**Closed** 2024-02-02 15:19 UTC
Labels: Reviewing, Engineering, Monthly, Internal, Bug
