### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Request Money - User gets highlighted in send/request money on changing of language during the process

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21538] opened 2023-06-25 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From device 1, login with user A
2. From device 2, login with user A
3. From device 1, open any report, click on plus, click on send/request money, enter any amount and click continue
4. From device 2, change the language from English to Spanish or vis a versa
5. Observe in device 1 that user gets highlighted after language change (by default user is not highlighted)

## Expected Result:
App should not highlight user in send/request money on language change

## Actual Result:
App highlights user in send/request money while changing language during the process

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c0e4ee98-fe71-45f4-a6d1-7859987300d2

https://github.com/Expensify/App/assets/93399543/427846e1-96a8-4add-b463-65338b625553

**Expensify/Expensify Issue URL:**
**Issue reported by:**@dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687200047072349

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b389dab3622e04c</li>
        <li>Upwork Job ID: 1673230286457331712</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-06-26 07:51
The steps to reproduce do not match the video.

**Comment by bernhardoj** [comment] 2023-06-26 07:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Changing the app language will highlight the first item in the money request confirmation list.

### What is the root cause of that problem?
The money request confirmation list uses OptionsSelector to show the list. The first time we open it, it will get the initial focus index. In a money request confirmation list case, the initially focused index is 1.
https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/components/OptionsSelector/BaseOptionsSelector.js#L55-L60
https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/components/OptionsSelector/BaseOptionsSelector.js#L174-L190

It has some conditions to decide what is the correct index.

When the app language is changed, the list text (header) is updated to the selected language. This will trigger the update to OptionsSelector.
https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/components/OptionsSelector/BaseOptionsSelector.js#L127-L139

In `componentDidUpdate`, we immediately set the new index to be `this.props.selectedOptions.length`, which is 0. The money request confirmation list is not selectable. That's why the first item becomes highlighted.

### What changes do you think we should make in order to solve the problem?

We should update the new focused index with the value from `this.getInitiallyFocusedIndex` too.
`const newFocusedIndex = this.getInitiallyFocusedIndex(newOptions);`

**Comment by rojiphil** [comment] 2023-06-26 12:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User gets highlighted in the Money Request Confirmation Page when the language gets changed.

### What is the root cause of that problem?
The root cause of the problem is that the index of the focused row is getting updated even when the arrow key management is not required.

### What changes do you think we should make in order to solve the problem?
To solve the problem, we need to initialize `focusedIndex` to -1 and, also, disable update of `focusedIndex` when `disableArrowKeysActions` is true.
Following two changes are required in BaseOptionsSelector.js:
1) Initialize focusedIndex to -1;

```
     constructor(props) {
         super(props);
         ...
-        const focusedIndex = this.getInitiallyFocusedIndex(allOptions);
+        const focusedIndex = this.props.disableArrowKeysActions ? -1 : this.getInitiallyFocusedIndex(allOptions);
```

2) Prevent updates to `focusedIndex`.

```
     componentDidUpdate(prevProps) {
     	...
-        const newFocusedIndex = this.props.selectedOptions.length;
+        const newFocusedIndex = this.props.disableArrowKeysActions ? -1 : this.props.selectedOptions.length;
```

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-06-28 08:40
@aimane-chnaif couple of proposals ready for review when you get a chance!

**Comment by bfitzexpensify** [comment] 2023-07-03 07:41
Bump to review proposals @aimane-chnaif

**Comment by rojiphil** [comment] 2023-07-03 16:42
@aimane-chnaif Were you able to review [my proposal ](https://github.com/Expensify/App/issues/21538#issuecomment-1607330768)? I think this should solve the problem. Please let me know your feedback.

**Comment by rojiphil** [comment] 2023-07-03 18:06
@aimane-chnaif 
Two observations:
a) I think, this specific issue is referring to the confirmation page reached via the report screen. My proposal focuses on this issue.   
b) Also, I have a feeling that you came to the participants' page via the Sidebar screen. But, I do agree that the identified issue on the participants' page is also a valid one and needs to be addressed.  I have made a slight modification to the logic to include this change too [in my proposal](https://github.com/Expensify/App/issues/21538#issuecomment-1607330768).  I think, this solves the problem.
Will also share a test video in some time.

**Comment by rojiphil** [comment] 2023-07-03 18:17
@aimane-chnaif  I have also attached the test video in the [proposal ](https://github.com/Expensify/App/issues/21538#issuecomment-1607330768) itself. Kindly let me know what you think.

**Comment by bfitzexpensify** [comment] 2023-07-06 09:06
@aimane-chnaif couple of comments to address - thank you!

**Comment by ShogunFire** [comment] 2023-07-07 23:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When we change the language, the selected option changes

### What is the root cause of that problem?

In BaseOptionSelector, in ComponentDidUpdate here:
https://github.com/Expensify/App/blob/3475812665c9e57b2be2ea6feb18e82562340fce/src/components/OptionsSelector/BaseOptionsSelector.js#L135-L139

We change the options and the focused index even if the options have not changed.


### What changes do you think we should make in order to solve the problem?


We should return early if the options have not changed. We can test it like this:

```
const newOptions = this.flattenSections();
if(_.isEqual(newOptions,this.state.allOptions))
    return;
```

Result:

https://github.com/Expensify/App/assets/19537677/b3cd4aa5-ab46-4ba8-afc7-9e466da079f3



### What alternative solutions did you explore? (Optional)

**Comment by ShogunFire** [comment] 2023-07-07 23:55
Hello @aimane-chnaif I have made a proposal, actually now that I think about it, the alternative solution might be more regression free, can you check ?

**Comment by rojiphil** [comment] 2023-07-08 06:18
@aimane-chnaif  I think we need to update the `focusedIndex` only when the state of `focusedIndex` has changed within `componentDidUpdate`. I think this will solve the problem.
The last time I updated the proposal with my [comment here](https://github.com/Expensify/App/issues/21538#issuecomment-1618960066), I had already integrated the logic.
I have refactored the code and have updated [the proposal](https://github.com/Expensify/App/issues/21538#issuecomment-1607330768) accordingly for your consideration.

**Comment by ShogunFire** [comment] 2023-07-12 09:36
@aimane-chnaif My [Proposal](https://github.com/Expensify/App/issues/21538#issuecomment-1626368613) keeps the selection unchanged for those particular case, I have added an alternative solution if we want to make it work even when the text of the options changes during translation, I can make it more detailed if necessary, what do you think ?

**Comment by ShogunFire** [comment] 2023-07-13 12:53
@aimane-chnaif Actually I just found out that we don't really need my alternative solutions for now because everytime we use OptionsSelector, the options are emails, phone numbers or currencies which don't change when we change language.

If we still want to do it, just to confirm,if the order of the options change should we keep focusing the same transalted option or should we keep focusing the same index as before ?

Example
In english, let's say the option2 is selected:
{option1, 'Airport'}
{option2, 'Car'}
{option3, 'Train'}

We change the language to french (didn't find a good example in spanish :P):
{option1, 'Avion'}
{option3, 'Train'}
{option2, 'Voiture'}

The option2 is now at the index3, should I focus the index 3 or should I keep focusing the index 2 ?

**Comment by ShogunFire** [comment] 2023-07-13 13:14
Also if options have changed but the focused option is still here, should we keep focusing this option ?

**Comment by ShogunFire** [comment] 2023-07-13 13:18
Let's say instead of 
{option1, 'Airport'}
{option2, 'Car'}
{option3, 'Train'}

We now have 
{option1, 'Airport'}
{option2, 'Car'}
{option4, 'Jet'}
{option3, 'Train'}
{option5, 'Yatch'}

Should we keep focusing on option2 'Car' if that was the case before ?

**Comment by ShogunFire** [comment] 2023-07-13 13:19
Or let's say Train was focused before so that the index change

**Comment by ShogunFire** [comment] 2023-07-13 13:44
## Proposal
[Updated](https://github.com/Expensify/App/issues/21538#issuecomment-1626368613)

**Comment by rojiphil** [comment] 2023-07-13 14:58
@aimane-chnaif  You have not commented on my [updated proposal](https://github.com/Expensify/App/issues/21538#issuecomment-1607330768) yet. My [latest comment](https://github.com/Expensify/App/issues/21538#issuecomment-1626882712) is here. The proposal you are currently considering is already addressed in my proposal. How is this proposal better than mine?

**Comment by rojiphil** [comment] 2023-07-13 15:11
> @rojiphil you should have commented like [this](https://github.com/Expensify/App/issues/21538#issuecomment-1634273903) for updated proposal to be reviewed.

Oh! Didn't realize this aspect as I am also relatively new. Thanks for pointing this out.

**Comment by rojiphil** [comment] 2023-07-13 15:55
@ShogunFire Interesting observations. Appreciate your comments. Thanks.

**Comment by bfitzexpensify** [comment] 2023-07-17 09:25
@aimane-chnaif please let us know if one of the proposals we have is sufficient - thanks!

**Comment by ShogunFire** [comment] 2023-07-18 11:19
> I am thinking of case where options list requires dynamic locale change. Maybe I missed but might exist.

I didn't found either but I was thinking it is more secure to change the list anyway. If you think it's ok to just return we can remove this line.

**Comment by bfitzexpensify** [comment] 2023-08-01 13:48
Offers sent - @aimane-chnaif, please complete the BZ checklist when you get a chance, thank you!

**Comment by bfitzexpensify** [comment] 2023-08-04 12:15
Bump on the BZ checklist, thanks @aimane-chnaif

**Comment by bfitzexpensify** [comment] 2023-08-07 12:52
Another friendly bump @aimane-chnaif

**Comment by bfitzexpensify** [comment] 2023-08-10 14:08
Another bump @aimane-chnaif - please complete this when you get a chance and I'll finalise payment, thank you!

**Comment by bfitzexpensify** [comment] 2023-08-11 10:00
Thanks @aimane-chnaif, I agree. OK, last payment finalised, closing this out

**Closed by bfitzexpensify** 2023-08-11 10:00 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
