### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Xero - Onboarding modal shows up after refreshing page with 2FA setup prompt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46026] opened 2024-07-23 15:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Account is connected to Xero
- 2FA is disabled after Xero is set up
- Expensifail account is used as it does not require onboarding
1. Go to staging.new.expensify.com
2. Log out if logged in
3. Log in to the account with Xero connected and 2FA disabled
4. After login, 2FA setup prompt will show up
5. Without setting up 2FA, refresh the page

## Expected Result:
Onboarding modal will not show up after refreshing the page

## Actual Result:
Onboarding modal shows up after refreshing the page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/dc343c18-803c-47ac-91a8-12dc3a775236

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0186166f403ad15af9</li>
        <li>Upwork Job ID: 1815869402034012020</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @lschurr</details>

**Comment by lanitochka17** [comment] 2024-07-23 15:11
We think that this bug might be related to #wave-collect - Release 2

**Comment by mountiny** [comment] 2024-07-23 15:46
This is most likely not a backend issue. cc @rushatgabhane. This seems to be mixing your changes with the ones from @filip-solecki and @WojtekBoman. Can you guys have a look, please?

**Comment by francoisl** [comment] 2024-07-23 20:11
Either way, sounds like an edge case, going to demote to a daily issue for now.

**Comment by tushar-a-b** [comment] 2024-07-26 21:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onboarding modal shows up along with 2FA setup prompt after logging in and refreshing the page when Xero is connected.

### What is the root cause of that problem?

The root cause of this issue is the missing required `nvp_onboarding` key data for the logged-in user in ONYX. The absence of the `nvp_onboarding` key data in ONYX is because the server is not sending the `nvp_onboarding` data when `Xero` is connected and `2FA` is `disabled`, which results in server's response with error that user need to complete their 2FA setup.

#### Explanation:
https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/Navigation/NavigationRoot.tsx#L90-L121

In the above code, we are calculating `initialState` to provide it to the `NavigationContainer`, which will redirect the user to the calculated initial route. Refer to the code below:

https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/Navigation/NavigationRoot.tsx#L169-L178


But the problem here is we are getting incorrect `initialState`, i.e. `onboarding` route, since below condition while calculating `initialState` is satisfied.

https://github.com/Expensify/App/blob/750c34eca1531a48ace4fd5aca24caf3398d9176/src/libs/Navigation/NavigationRoot.tsx#L95-L100

In the above condition, we should get `hasCompletedGuidedSetupFlow` as `true` for users who have already completed the onboarding process. However, we end up getting `false`, which satisfies the condition and results in an incorrect `initialState` that is the `onboarding` route, thereby triggering the onboarding modal.

The reason for getting an incorrect `hasCompletedGuidedSetupFlow` value is that we do not have the `nvp_onboarding` key data in ONYX yet.

The main reason for not having `nvp_onboarding` data in ONYX is due to receiving an error from the server with `code=666` and `message=Your organization requires Two Factor Authentication. Go to your Inbox to get set up` for the `OpenApp` API. This error occurs because of a pending `2FA` setup, which is required when `Xero` is connected.

https://github.com/Expensify/App/blob/7af1d37ce797797b1c842f5415a70a78ce041486/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L257-L264

As per the above code, we call the `OpenApp` API to fetch the initial data of the app when the user successfully logs in. Let's take a look at the data received from the server through the `OpenApp` API in the scenarios where `2FA` is `enabled` and `disabled` with `Xero` connected. Refer to the screenshots below for the server responses.

* API `OpenApp` response when 2FA disabled and Xero connected.

<img width="1680" alt="Screenshot 2024-07-25 at 12 35 52 PM" src="https://github.com/user-attachments/assets/4dac9a93-50b8-4144-a03e-3831f840e4c1">



* API `OpenApp` response when 2FA enabled and Xero connected.

<img width="1680" alt="Screenshot 2024-07-25 at 1 25 17 PM" src="https://github.com/user-attachments/assets/f9d079d3-c7d9-4a6e-a8e9-61b351013621">

In the first screenshot, we can clearly notice that the server is responding with an error: when `2FA` is `disabled`, we are receiving an empty `onyxData`, resulting in no required initial user data such as `nvp_onboarding` in ONYX on the client side.

On the other hand, in the second screenshot, when `2FA` is `enabled`, we are receiving all the onyxData for the logged-in user, including the `nvp_onboarding` key, which is required in this case.

Since there is no `nvp_onboarding` in ONYX, we are incorrectly getting the value of `hasCompletedGuidedSetupFlow` as `false` here:

https://github.com/Expensify/App/blob/b751d4e770741c310064b3a0ab4739d3d101bffb/src/libs/Navigation/NavigationRoot.tsx#L86-L88

https://github.com/Expensify/App/blob/b751d4e770741c310064b3a0ab4739d3d101bffb/src/libs/hasCompletedGuidedSetupFlowSelector.ts#L4-L10

which will satisfies the below condition and result in opening of onboarding modal along with 2FA setup.

https://github.com/Expensify/App/blob/b7dabee0802fdc0d20d8dc5d53974aff10a79049/src/libs/Navigation/NavigationRoot.tsx#L97-L100


### What changes do you think we should make in order to solve the problem?

We can achieve the expected results by making changes either on the frontend or the server. This solution focuses on making changes on the frontend:

Since there is no availability of `nvp_onboarding` data in ONYX when 2FA is disabled with `Xero`, We can add check for `shouldShowRequire2FAModal` while calculating `initialState` and prevent onboarding when `shouldShowRequire2FAModal` is `true`.
We can update the condition from below in `NavigationRoot.tsx`

https://github.com/Expensify/App/blob/e9975021850693e8af99ba388e0c8e6e51543719/src/libs/Navigation/NavigationRoot.tsx#L95-L100

to 

```
if (!hasCompletedGuidedSetupFlow && authenticated && !shouldShowRequire2FAModal) {
    const {adaptedState} = getAdaptedStateFromPath(ROUTES.ONBOARDING_ROOT, linkingConfig.config);
    return adaptedState;
}
```
We can get `shouldShowRequire2FAModal` as `prop` from parent component that is `Expensify` to child component `NavigationRoot`: 
https://github.com/Expensify/App/blob/67a3378212ff0455a60570cd1c6e37057b2fa0cb/src/Expensify.tsx#L107-L114




### What alternative solutions did you explore? (Optional)

This solution focuses on making changes on the backend:
When user completes the authentication we are calling the API `SigninUser` which responds with authenticated user's data (Refer below screenshot). Here, in `SigninUser` API's response we should add additional data of `nvp_onboarding` so that we will have availability of `nvp_onboarding` data in ONYX, no need to rely on API `OpenApp` since it will not send the `onyxData` as 2FA is disabled.
<img width="1680" alt="Screenshot 2024-07-26 at 1 15 29 PM" src="https://github.com/user-attachments/assets/c5cb159e-1096-4ea2-b30b-cd2c67511d56">

#### Solution Conclusion

To address the root cause of the issue, I propose two potential solutions:

* Ensure the `nvp_onboarding` data is available to the application initially. This will prevent the incorrect calculation of the `hasCompletedGuidedSetupFlow` value, thereby avoiding unintended navigation to the onboarding route.

* Implement logic to prevent triggering the onboarding process when the 2FA prompt needs to be displayed to the user. This will ensure that users are correctly guided to complete their 2FA setup without encountering the onboarding flow.

By adopting either of these solutions, we can effectively resolve the issue and improve the user experience.

#### Results by making changes on frontend: 

https://github.com/user-attachments/assets/72d230f9-678d-446c-a618-154ad7111480


In the video above, we resolved the issue of the onboarding modal opening during the 2FA setup. However, this introduced a new problem where `undefined` is automatically appended to the URL. This causes the `Hmm... Not Found` view to appear in a report because the app treats `undefined` as a `reportID`. Consequently, no report is found since there is no report with an ID of `undefined`. 

```
Note: Even after making changes to server and getting correct data for `nvp_onboarding` may not fix above issue unless instead of error, server responds with all the `onyxData` even if 2FA is disabled with `Xero` connected.
``` 

This issue is happing in below code: 
https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L214-L229

In above code we are trying to get the `initialReportID` to pass it to the below: 
https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L487-L498

Since we do not have any `:reportID` to our url and also there is no `LastAccessedReport` data since we are just logged-in and due to required 2FA setup we are not getting any data for ONYX for initialization we will end up getting `initialReportID` as `undefined` below.
https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L220-L226

Since we keep `initialReportID` as `undefined` below code leads us to `/r/undefined`.
https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L493

Solution for above issue is that we should not keep `initialReportID` as `undefined` instead we can set `initialReportID=""` when `initialReportID` is `undefined` by changing below code: 
https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L224-L226
to 
```
if (!initialReportID) {
   const initialReport = ReportUtils.findLastAccessedReport(!canUseDefaultRooms, shouldOpenOnAdminRoom(), activeWorkspaceID);
   initialReportID = initialReport?.reportID ?? "";
}
```

This keeps `initialReportID` as `""` if it is `undefined` so now below code will lead us to the route `/r` instead of `/r/undefined`. 

https://github.com/Expensify/App/blob/1908bd183b8d1953d81b69ce074c172f30826f90/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L493

* Final Result:

https://github.com/user-attachments/assets/1d9e23df-f82a-462d-8314-75a043b95144

**Comment by tushar-a-b** [comment] 2024-07-26 21:55
Contributor details
Your Expensify account email: onmactab@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c3775ee22f439793?mp_source=share

**Comment by Julesssss** [comment] 2024-08-01 10:43
Sounds good to me.

**Comment by tushar-a-b** [comment] 2024-08-01 12:00
Thank you for assigning this job to me!

I have applied to the Upwork job, and you can expect the PR to be ready for review by 2nd of August.

**Comment by tushar-a-b** [comment] 2024-08-02 06:22
@Julesssss  I have applied for the job on Upwork but have not been accepted yet. Should I wait for the acceptance before starting to work on the PR, or should I begin working on it now? Additionally, is there a specific template for the PR that I should follow?

**Comment by tushar-a-b** [comment] 2024-08-02 09:14
okay got it.
Thank you @fedirjh

**Comment by tushar-a-b** [comment] 2024-08-02 19:36
[PR](https://github.com/Expensify/App/pull/46750) is ready for review

**Comment by Julesssss** [comment] 2024-08-19 15:37
@fedirjh sounds good to me

**Comment by lschurr** [comment] 2024-08-19 18:16
@tushar-a-b - Offer sent in Upwork (https://www.upwork.com/nx/wm/offer/103591411)

**Comment by tushar-a-b** [comment] 2024-08-19 18:28
@lschurr Thank you! I've accepted the offer👍🏻

**Comment by lschurr** [comment] 2024-08-19 18:46
All set - Payment summary is correct: https://github.com/Expensify/App/issues/46026#issuecomment-2297133680

**Closed by lschurr** 2024-08-19 18:46 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-09-04 14:11
$250 approved for @fedirjh
