### ISSUE TITLE
[$500] Add Empty State Background To Tasks

### ISSUE THREAD

**Issue by grgia** [Expensify/App#27495] opened 2023-09-15 06:38 UTC
We're missing the empty state background in Task reports. Follow up from https://github.com/Expensify/App/pull/27478
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8fb00801e6f1236</li>
        <li>Upwork Job ID: 1702572656769077248</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27346707</li>
<li>Pujan92 | Contributor | 27346708</li>
</ul></li>
    </ul>
</details>

**Comment by grgia** [comment] 2023-09-25 06:41
not overdue

**Comment by grgia** [comment] 2023-10-04 11:50
@aimane-chnaif making external

**Comment by Pujan92** [comment] 2023-10-04 13:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add empty state background for tasks report

### What is the root cause of that problem?
We do not have that logic currently in the `TaskView` component.

### What changes do you think we should make in order to solve the problem?
Replicate the same logic in `TaskView` component `View` what we have for `MoneyRequestView` component for showing the background image.

https://github.com/Expensify/App/blob/24aa7c12c269796008f6a96ae153fbd8ced5b43b/src/components/ReportActionItem/MoneyRequestView.js#L139-L141
 
https://github.com/Expensify/App/blob/24aa7c12c269796008f6a96ae153fbd8ced5b43b/src/components/ReportActionItem/TaskView.js#L56

<img width="1440" alt="Screenshot 2023-10-04 at 18 38 43" src="https://github.com/Expensify/App/assets/14358475/02b9d83c-0d8c-4ec7-a039-8a50c8ab6776">

**Comment by Pujan92** [comment] 2023-10-05 12:51
Thanks, I will check and update based on that.

**Comment by Pujan92** [comment] 2023-10-05 13:59
@aimane-chnaif I have updated the proposal a bit and here are the screencasts.

https://github.com/Expensify/App/assets/14358475/7fa50e19-2b53-4290-802d-6cc4578be147

https://github.com/Expensify/App/assets/14358475/79244bfe-2e9c-4ca8-8f56-79e6366e1e4c

**Comment by Pujan92** [comment] 2023-10-10 16:05
Yes @aimane-chnaif

**Comment by Pujan92** [comment] 2023-10-17 17:44
Yes @aimane-chnaif, currently it seems to be an issue for scrolling which either fix with https://github.com/Expensify/App/pull/29102/files#diff-0ce28fbd4cc98192907f355be9190ce12783cc8d13e0d1b9e183fa67eab7df0cL44 otherwise needs a bit updation for the structure. 

```js
<View style={[StyleUtils.getReportWelcomeContainerStyle(props.isSmallScreenWidth), StyleUtils.getMinimumHeight(CONST.EMPTY_STATE_BACKGROUND.MONEY_REPORT.MIN_HEIGHT)]}> 
    <AnimatedEmptyStateBackground /> 
    <View style={[StyleUtils.getReportWelcomeTopMarginStyle(props.isSmallScreenWidth)]}>
        <TaskView
```

**Comment by grgia** [comment] 2023-10-18 19:38
@aimane-chnaif could I get an update on this?

**Comment by Pujan92** [comment] 2023-10-20 10:23
@aimane-chnaif @grgia  as the other PR is merged, the scrolling issue won't occur now with my proposal.

https://github.com/Expensify/App/assets/14358475/8c3b7682-fb9a-47ed-9bce-be5fade1bba0

**Comment by grgia** [comment] 2023-10-24 11:29
Assigned @Pujan92 !

**Comment by Pujan92** [comment] 2023-10-27 08:54
> @Pujan92 what is ETA?

Working on it and will raise a PR within an hour.

**Comment by grgia** [comment] 2023-11-28 09:50
@aimane-chnaif I think this was fixed and we can close

**Comment by stephanieelliott** [comment] 2023-12-04 17:34
Summarizing payment on this issue: 

 - Issue reporter: N/A
 - Contributor: @Pujan92 $500, paid via Upwork 
 - Contributor+: @aimane-chnaif, to pay via Upwork 
 
 Upwork job is [here](https://www.upwork.com/ab/applicants/1702572656769077248/job-details), [X] bonus is included on final payout

@aimane-chnaif can you please complete the BZ checklist above? Once completed I will issue payment. Thanks!

**Comment by stephanieelliott** [comment] 2023-12-04 18:40
Sounds good to me - all paid !

**Closed by stephanieelliott** 2023-12-04 18:40 UTC
Labels: Reviewing, External, Daily, Bug
