### ISSUE TITLE
Hybrid app- Search page not loading

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45083] opened 2024-07-09 14:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** daniel@expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1720479616986669

## Action Performed:
1. Launch the app and login
2. Navigate to the Search page
## Expected Result:
Search page displayed without any issue
## Actual Result:
Continous loading skeleton displayed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [X] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8ba1c9a7-b486-425d-b33f-20e6d18561a3

[logs-2024-07-08 22_57_56.602.txt](https://github.com/user-attachments/files/16144747/logs-2024-07-08.22_57_56.602.txt)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2024-07-10 04:39
Added to #wave-collect polish for now, though I'm unable to reproduce this one.

**Comment by luacmartins** [comment] 2024-07-10 14:52
The logs just showed that there was a long queue of write requests and the Search API command was never made because of that. I'm not sure what caused the long queue though

**Comment by danielrvidal** [comment] 2024-07-12 23:41
I can't reproduce this in my account anymore either... so not sure what to do in this case.

**Comment by luacmartins** [comment] 2024-07-15 15:00
I think we can close this for now and reopen if we run into it again. Just for reference, these were the logs we captured this time around:

[logs-2024-07-08 22_57_56.602.txt](https://github.com/user-attachments/files/16236384/logs-2024-07-08.22_57_56.602.txt)

We can see that we had a long queue of write commands:

```
[info] [API] 'SendPerformanceTiming' is waiting on 186 write commands
```

Which indicates the Sequential Queue was blocking newer API command responses to be written to Onyx and thus creating long loading times on certain pages that didn't have any data stored yet.

**Closed by luacmartins** 2024-07-15 15:00 UTC
Labels: Daily, Needs Reproduction, Bug, AutoAssignerNewDotQuality
