### ISSUE TITLE
Android/IOS- Attachment - Protected PDF file does not have password field to enter it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10544] opened 2022-08-24 18:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Select any user for conversation
4. Tap on Plus button
5. Add attachment
6. Tap Choose from document
7. Select any protected PDF file and send it

## Expected Result:
Protected PDF file have password field to enter it

## Actual Result:
Protected PDF file does not have password field to enter it

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.89.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186494773-7d049171-6362-46f6-83f6-2fa3b7df146e.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by cead22** [comment] 2022-08-25 12:43
Can we close this one then @parasharrajat since it's kind of a duplicate of https://github.com/Expensify/App/issues/8595?

**Closed** 2022-08-29 07:01 UTC
Labels: Engineering, Daily, Overdue
