### ISSUE TITLE
[HOLD] [$500] Web - Leaving and revisiting #teachers-unite page displays 'Hmm its not here' page for sometime

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26608] opened 2023-09-03 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click save the world
3. Click on 'I know a teacher'
4. Fill in details and click 'Lets do this!'
5. Visit #teachers-unite page and copy the URL
6. Click on header and leave the thread
7. Paste the URL and revisit, observe that it displays 'Hmm its not here' page for some time before rejoining

## Expected Result:
App should either display 'skeleton view' or instantly rejoin when we leave thread and again visit #teachers-unite page

## Actual Result:
App displays 'Hmm its not here' page for some time when we leave thread and again visit #teachers-unite page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/14dd5ebc-8c71-4f99-950b-2b37ec2687bf

https://github.com/Expensify/App/assets/93399543/25123bdc-47a8-4bb9-8cb9-42c013a95003

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693374999062339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116c116dcad14c52c</li>
        <li>Upwork Job ID: 1698576378656542720</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-09-04 05:58
![2023-09-04_17-56-02 (1)](https://github.com/Expensify/App/assets/42940078/8a957f7a-2918-499c-adc5-033d0caf685b)

**Comment by marlisajp** [comment] 2023-09-04 07:01
Hi my name is Marlisa from Upwork and I would like to submit a proposal for this issue.

Proposed Solution:

1. Initial Investigation:
Clone the Expensify repository and reproduce the issue in a local environment.
Check browser console logs and network requests to identify any errors or delays during navigation.

2. Potential Causes:
Delays in data fetching from the backend causing the temporary display.
Incorrect route handling or caching issues.
Component's lifecycle events causing an unintended re-render or delay.

3. Addressing Data Fetching:
If data fetching is causing the delay, implement a loading spinner or a more user-friendly message instead of the "Hmm its not here" placeholder.
Consider prefetching data or employing optimistic UI techniques to make navigation seem instantaneous.

4. Route and Navigation:
Ensure that routes are set up correctly, especially for the #teachers-unite page.
Implement client-side caching or utilize service workers to provide faster page loads when revisiting.

5. Component Optimization
Review the lifecycle events or hooks associated with the #teachers-unite page. Ensure unnecessary renders or delays are minimized.
Use React's performance tools or browser dev tools to profile component renders and optimize accordingly.

6. Testing
Test the fix on multiple browsers to ensure cross-browser compatibility.
Ensure that revisiting the #teachers-unite page is seamless, without any noticeable delays or placeholder messages.
Consider adding end-to-end tests using tools like Cypress to catch similar issues in the future.

**Comment by rafi16jan** [comment] 2023-09-04 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A placeholder of 'Hmm its not here' is displayed seconds before re-joining the teachers-unite page

### What is the root cause of that problem?
It seems that there is some kind of race condition or data retrieve failure when leaving and re-joining teachers-unite

### What changes do you think we should make in order to solve the problem?
Either to debug the race condition and directly fix the order of execution, or implement an await that defer authentication tokens (if that's the root cause) or any other dependency before retrieving the said page itself

### What alternative solutions did you explore? (Optional)
An ugly alternative solution would be hiding the Hmm its not here placeholder or replacing it with a loading indicator before the real page loads.

**Comment by rafi16jan** [comment] 2023-09-04 07:05
Contributor details
Your Expensify account email: abdurrafi16jan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016fcec68abaa3bc96

**Comment by marlisajp** [comment] 2023-09-04 07:05
Contributor details
Expensify account email: marlisajp@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01545b41c7fab75f4b

**Comment by ankitsehgal94** [comment] 2023-09-04 07:34
Contributor details
Your Expensify account email: codingmunk94@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c1048ef2c2e1cb54

**Comment by mollfpr** [comment] 2023-09-04 14:53
I think this has the root cause as https://github.com/Expensify/App/issues/25698, and we already have the PR.

**Comment by sophiepintoraetz** [comment] 2023-09-05 03:19
Ah, nice find @mollfpr. In which case, let's wait until https://github.com/Expensify/App/pull/26602 is merged and we can confirm (and close).

**Comment by sophiepintoraetz** [comment] 2023-09-06 04:41
Waiting for review of linked PR.

**Comment by mollfpr** [comment] 2023-09-06 04:42
@sophiepintoraetz I think we can put this on HOLD.

**Comment by sophiepintoraetz** [comment] 2023-09-12 02:33
@mollfpr - are we good to close this issue out?

**Comment by sophiepintoraetz** [comment] 2023-09-15 05:06
@mollfpr - we're still holding?

**Comment by mollfpr** [comment] 2023-09-15 18:12
Sorry for the delay! We finished discussing the expected result in the PR https://github.com/Expensify/App/pull/26602. I will try to reproduce this while completing the test, and let you know the result.

**Comment by mollfpr** [comment] 2023-09-18 09:26
@sophiepintoraetz  The PR #26602 is merged now, and tested the current `main` the issue is not reproduced.

**Comment by sophiepintoraetz** [comment] 2023-09-21 04:37
Thank you @mollfpr - let me doublecheck what needs to happen here!

**Comment by sophiepintoraetz** [comment] 2023-09-25 11:28
Unnngh, have not found the time to do so - I think I need to double-check this https://docs.google.com/document/d/1BA9A1ZouVgUlR6mTGRYSPOqsgFks5-ErHmPjw64AL-U/edit

**Comment by sophiepintoraetz** [comment] 2023-10-02 00:23
Apologies, this is still with me - hopefully I'll have some time tomorrow to confirm what needs to happen here.

**Comment by sophiepintoraetz** [comment] 2023-10-05 10:21
Okay, @mollfpr and @dhanashree-sawant are due for payments here - offers sent!

**Closed by sophiepintoraetz** 2023-10-05 10:21 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by mollfpr** [comment] 2023-10-05 10:26
@sophiepintoraetz I think I'm not due for any payment here.

**Comment by sophiepintoraetz** [comment] 2023-10-05 10:27
You actually are here - https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit#bookmark=id.wfm6lkgp0c6 though I think I might want to double check this.
