### ISSUE TITLE
[HOLD for Payment 2024-10-24] [$250] Bank account - Not here page shows up when clicking add bank account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48506] opened 2024-09-03 20:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.28-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Add a bank account
4. On another tab sign in with a new account (This is going to be invited as an employee)
5. As the admin invite the user signed in on step 4
6. As the employee submit an expense
7. Admin pays the expense with expensify
8. As the employee navigate to the expense report page and click on Add bank account

## Expected Result:
User gets navigated to validate their account first

## Actual Result:
Hmm not here page shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/72d7893a-36bd-47e1-b3ff-3922ea760ca1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834204861349531229</li>
        <li>Upwork Job ID: 1834204861349531229</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-09-03 20:29
@kevinksullivan  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-09-04 09:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hmm not here page shows up

### What is the root cause of that problem?

We show not found page when use is not validated:

https://github.com/Expensify/App/blob/7c50964cb08ff35c6e7d741f25ba49c5256cef2a/src/pages/AddPersonalBankAccountPage.tsx#L70

### What changes do you think we should make in order to solve the problem?


We should not disable `Add bank account` button in the message because that is a CTA button, without it, user wouldn't know what to do next to get reimbursed.

We should follow the behavior from policy's add bank account page, when user is not validated, we would show a warning message requesting them to validate their accounts first:

![Screenshot 2024-09-04 at 16 24 01](https://github.com/user-attachments/assets/6d998008-db0b-4c3c-91e4-a8168b7b1cd3)

To do this, in `AddPersonalBankAccountPage`:
1. Remove the `FullPageNotFoundView` logic
2. Show `ValidateAccountMessage` component when `isUserValidated` is not satisfied:


```javascript
{isUserValidated ? (
    {shouldShowSuccess ? <ConfirmationPage /> : <FormProvider />}
) : (
    <ValidateAccountMessage backTo={ROUTES.SETTINGS_ADD_BANK_ACCOUNT}/>
)}
```

**Comment by mkzie2** [comment] 2024-09-11 08:55
@kevinksullivan Please proceed this one.

**Comment by mkzie2** [comment] 2024-09-12 03:33
@kevinksullivan Can you reassign BZ here since you're heading OOO?

**Comment by kevinksullivan** [comment] 2024-09-12 12:17
I'd put this in collect since it's the mainline reimbursement flow. Also looping in another BZ as I am going OOO

**Comment by allroundexperts** [comment] 2024-09-12 19:47
Thanks for the proposals everyone. I think @mkzie2's [proposal](https://github.com/Expensify/App/issues/48506#issuecomment-2328368800) is better, since disabling the button straight away would just cause confusion to the user. Let's also confirm with the design team if this is something we need to do here. 

@Expensify/design can you please weigh in?

**Comment by dannymcclain** [comment] 2024-09-12 20:46
Definitely agree that we don't want to just disable the button. @shawnborton can correct me if I'm wrong, but I thought we recently talked about just making the magic code validation the very first step of the add bank account flow for unvalidated users. Does that sound right?

**Comment by trjExpensify** [comment] 2024-09-12 23:46
^^ that sounds like it could be a decent improvement instead of that kinda' bulky error text at the bottom we use in places for this 😅 So here, they'd click `Add bank account` and get a magic code sent to them and land on a magic code input page, right?

**Comment by shawnborton** [comment] 2024-09-13 05:21
> but I thought we recently talked about just making the magic code validation the very first step of the add bank account flow for unvalidated users. Does that sound right?

Indeed that does sound correct from my understanding.

**Comment by mkzie2** [comment] 2024-09-13 06:41
[Updated my proposal](https://github.com/Expensify/App/issues/48506#issuecomment-2328368800) to reflect the latest expectations.

**Comment by dannymcclain** [comment] 2024-09-13 13:20
>So here, they'd click Add bank account and get a magic code sent to them and land on a magic code input page, right?

Yes. They'd land on the magic code validation page _in the RHP_, and it would essentially act as the first step of the add bank account flow. I _think_ Shawn had recently worked on this for adding a VBBA if I'm remembering correctly.

**Comment by trjExpensify** [comment] 2024-09-13 14:08
>They'd land on the magic code validation page in the RHP, and it would essentially act as the first step of the add bank account flow. 

Kewl.

> I think Shawn had recently worked on this for adding a VBBA if I'm remembering correctly.

Got it, I don't think I've seen that. It's not in prod either.

**Comment by allroundexperts** [comment] 2024-09-15 19:57
Given that we have an agreement that we should show the magic code validation page if the user is not validated, @mkzie2's [proposal](https://github.com/Expensify/App/issues/48506#issuecomment-2328368800) makes the most sense then. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment] 2024-09-19 01:16
Nice, PR is up and being worked on!

**Comment by greg-schroeder** [comment] 2024-09-23 03:05
PR still in draft, work continues

**Comment by MariaHCD** [comment] 2024-09-23 08:38
Any updates here, @mkzie2 ?

**Comment by mkzie2** [comment] 2024-09-24 09:53
@allroundexperts The PR is ready.

**Comment by mkzie2** [comment] 2024-09-26 04:20
@greg-schroeder @allroundexperts Let's hold this for https://github.com/Expensify/App/pull/49230.

**Comment by greg-schroeder** [comment] 2024-09-27 19:41
Held

**Comment by greg-schroeder** [comment] 2024-10-03 01:23
[#49230](https://github.com/Expensify/App/pull/49230) was merged. Awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2024-10-08 21:22
Taking this off hold now @mkzie2 @allroundexperts

**Comment by mkzie2** [comment] 2024-10-09 07:57
Post an update in PR, we can continue reviewing.

**Comment by greg-schroeder** [comment] 2024-10-14 21:45
I believe @allroundexperts is next up on the review

**Comment by greg-schroeder** [comment] 2024-10-17 22:56
Same as above

**Comment by allroundexperts** [comment] 2024-10-20 23:02
Seems like PR has no diff at all. Waiting for @mkzie2's comment.

**Comment by mkzie2** [comment] 2024-10-21 03:45
@greg-schroeder @allroundexperts Validate code step was added to adding bank account flow in https://github.com/Expensify/App/pull/50228. We can proceed payments and close this.

**Comment by greg-schroeder** [comment] 2024-10-21 22:13
Okay so just to be clear - the linked PR above is irrelevant and will be closed? I'm confused

**Comment by mkzie2** [comment] 2024-10-21 22:40
In short, this issue was already fixed in https://github.com/Expensify/App/pull/50228 so we can close the current PR https://github.com/Expensify/App/pull/49366.

**Comment by greg-schroeder** [comment] 2024-10-24 19:45
Okay, reviewing again

**Comment by greg-schroeder** [comment] 2024-10-24 19:54
Payment summary:

Contributor: @mkzie2 - $250 - Upwork
C+: @allroundexperts - $250 - Manual request via ND

**Comment by greg-schroeder** [comment] 2024-10-24 19:56
@mkzie2 Do you mind applying to the new job I created so I can pay you, thanks! https://www.upwork.com/jobs/~021849539020945682815

**Comment by greg-schroeder** [comment] 2024-10-24 22:50
Go away Melvin

**Comment by greg-schroeder** [comment] 2024-10-29 15:48
bump @mkzie2

**Comment by mkzie2** [comment] 2024-10-29 17:31
@greg-schroeder I applied 🙏

**Comment by greg-schroeder** [comment] 2024-10-29 21:09
Offer sent @mkzie2

**Comment by mkzie2** [comment] 2024-10-30 09:20
@greg-schroeder I accepted 🙏

**Comment by greg-schroeder** [comment] 2024-10-30 17:38
paid

**Closed by greg-schroeder** 2024-10-30 17:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2025-02-13 22:01
$250 approved for @allroundexperts
