### ISSUE TITLE
iOS Invoices - App remains on the same page instead of workspace LHN after enabling Invoices

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50056] opened 2024-10-02 12:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.43-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace settings > More features.
3. Enable Invoices.

## Expected Result:
App will return to workspace LHN and invoices tab will be shown.

## Actual Result:
App remains in More features page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4cdd8202-e4d5-4e79-a236-3a53f8297350

![Screenshot 2024-10-02 at 19 56 24](https://github.com/user-attachments/assets/15ea4bda-0556-4207-a7b4-18fe28e5af82)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-02 12:02
We think that this bug might be related to #vip-bills

**Comment by arosiclair** [comment] 2024-10-02 12:45
> Reproducible in production?: N/A - new feature, doesn't exist in prod

> Uncomment the following line when the invoices screen is ready - https://github.com/Expensify/App/issues/45175.

Looks pretty intentional and not a bug for now. I'm just going to close this out since it looks like we already have a plan for re enabling this. cc @madmax330

**Closed by arosiclair** 2024-10-02 12:45 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
