### ISSUE TITLE
[$500] App hangs/freeze when pressing back button in attachment preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29109] opened 2023-10-09 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tsa321 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696824854320599

## Action Performed:
1. Send 3 or more image in a report
2. View the first image
3. Press back browser back button
4. Notice the app freeze/hangs
## Expected Result:
The App must go back to the report page and not hangs
## Actual Result:
The App freeze/hangs
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/55812c84-d7e2-4a7f-a2b4-6305f1acb60e

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/8267fb99-9077-45f0-abef-9c880ef7e163

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/6a7bb8c3-85c7-41ae-823e-33d36540a082

https://github.com/Expensify/App/assets/38435837/9996240c-b8b8-49a5-84be-07249185d85b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0189b09e365f4d7d47</li>
        <li>Upwork Job ID: 1711433460882178048</li>
        <li>Last Price Increase: 2023-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by paultsimura** [comment] 2023-10-09 21:43
I suggest fixing this in my proposal here: https://github.com/Expensify/App/issues/27237#issuecomment-1753912527

**Comment by pradeepmdk** [comment] 2023-10-10 03:52
same root cause https://github.com/Expensify/App/issues/27237#issuecomment-1751743967

**Comment by garrettmknight** [comment] 2023-10-11 18:55
@allroundexperts tested and confirmed the bug - can you comment on whether it has the same root cause as https://github.com/Expensify/App/issues/27237?

**Comment by garrettmknight** [comment] 2023-10-16 14:48
Can do!

**Comment by garrettmknight** [comment] 2023-10-25 18:13
Still holding on https://github.com/Expensify/App/issues/27237

**Comment by garrettmknight** [comment] 2023-11-03 17:15
Still holding on https://github.com/Expensify/App/issues/27237 - moving to weekly

**Comment by garrettmknight** [comment] 2023-11-13 19:59
Still holding on https://github.com/Expensify/App/issues/27237

**Comment by garrettmknight** [comment] 2023-11-22 19:50
Still holding on https://github.com/Expensify/App/issues/27237

**Comment by garrettmknight** [comment] 2023-12-01 18:05
Issue is deployed - updating to daily to test next week.

**Comment by garrettmknight** [comment] 2023-12-05 19:50
No more hanging between the 2 images!

**Comment by garrettmknight** [comment] 2023-12-05 19:58
Sent an offer for the reporter bonus: https://www.upwork.com/en-gb/ab/applicants/1732126827545030656/job-details

**Comment by tsa321** [comment] 2023-12-06 00:03
Thank you, I have accepted the offers

**Closed** 2023-12-06 16:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
