### ISSUE TITLE
[$500] Distance-App crashes tapping on download receipt in android& on tapping receipt in mweb&web

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30489] opened 2023-10-27 10:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.92-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap fab
3. Tap request money
4. Tap distance
5. Select start and finish waypoints
6. Tap next
7. Select a Workspace
8. Tap Request amount
9. Tap on distance request created to open distance request detail page
10. Tap on the receipt
11. Tap on 3 dots on top and select download receipt

## Expected Result:
When user taps on receipt or taps on download receipt app must not crash.

## Actual Result:
App crashes tapping on download receipt in android& on crashes on tapping receipt in mweb & web

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/2d1c387f-9081-4d2d-8bbf-5451f0538c20

[Bug6252678_1698372747379!app_crashes.txt](https://github.com/Expensify/App/files/13187806/Bug6252678_1698372747379.app_crashes.txt)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/115492554/5e6efb91-301d-4f97-967d-72d355cf917a

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fac84786d952629</li>
        <li>Upwork Job ID: 1717850193169375232</li>
        <li>Last Price Increase: 2023-10-27</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2023-10-27 10:28
Not reproduced in production

https://github.com/Expensify/App/assets/115492554/97328b0a-3751-4452-a8db-7f59479a657b

**Comment by hungvu193** [comment] 2023-10-27 10:38
Seem regression from this PR: 
https://github.com/Expensify/App/pull/29643

https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/components/Attachments/AttachmentCarousel/index.js#L210

`updatePage` is an useCallback it will re-create when its dependencies changed and it's not supported with `onViewableItemsChanged`. We should revert it to useRef.
<img width="713" alt="Screenshot 2023-10-27 at 17 38 22" src="https://github.com/Expensify/App/assets/16502320/ef6f6461-b33e-4558-8efc-caf4cd75b4cb">

**Comment by situchan** [comment] 2023-10-27 10:40
beng fixed in https://github.com/Expensify/App/pull/30481

**Comment by MariaHCD** [comment] 2023-10-27 11:50
Thanks, @situchan! Going to close this one in favor of https://github.com/Expensify/App/issues/30490 since this is happening for all attachments not just for distance requests.

**Closed by MariaHCD** 2023-10-27 11:50 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
