### ISSUE TITLE
Invite members: very little space between the lines and the highlighted lines are overlapping

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13741] opened 2022-12-20 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > manage members
2. Click invite button
3. Select the text at add a personal message field

## Expected Result:
The highlighted lines are not overlapping

## Actual Result:
There is very little space between the lines

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / Chrome
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/208771821-b74fbbcb-b97e-4928-9776-992d8c987132.png">
<img width="365" alt="Screenshot 2022-12-20 at 2 18 08 AM" src="https://user-images.githubusercontent.com/43996225/208771837-b1f12f21-b5ee-4a5f-ac97-3b18d976d5bb.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671484774271469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eeb6a2bced2c4533</li>
        <li>Upwork Job ID: 1606405025835712512</li>
        <li>Last Price Increase: 2022-12-23</li>
    </ul>
</details>

**Comment by NikkiWines** [comment] 2022-12-21 19:20
Able to reproduce locally. Likely introduced by [this change](https://github.com/Expensify/App/commit/99971de55492d7acfe6f2792e3491e55707a26af#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253ebR737) and [this change](https://github.com/Expensify/App/blob/3b54638d85bfe9e82b4fa02d749eaf64325050d8/src/styles/variables.js#L72) since `lineHeightNormal` appears to be 16px on web, which is too small. 

Looks like it impacts any multiline `<TextInput>` element. 

<img width="651" alt="Screenshot 2022-12-21 at 14 11 22" src="https://user-images.githubusercontent.com/16747822/208984668-d5c6ee1c-7a6f-4fda-a71a-3e6b44cc61fe.png">

**Comment by NikkiWines** [comment] 2022-12-21 19:23
Looks like @Luke9389's [PR](https://github.com/Expensify/App/pull/12447) should resolve the issue.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/16747822/208986536-b2e23fdf-f6b3-43a8-befc-2e75353d28e8.png">
<img width="601" alt="Screenshot 2022-12-21 at 14 21 30" src="https://user-images.githubusercontent.com/16747822/208986344-8e33d1ee-b8bf-4e15-b411-b20a0b10dce4.png">

**Comment by Luke9389** [comment] 2022-12-21 20:40
@NikkiWines I'll test this one out on my branch to be sure it fixes it. If not, I'll include the fix in my PR. Thanks for the heads up!

**Comment by Luke9389** [comment] 2022-12-21 20:50
Ok cool, I can confirm that my branch form the linked PR above fixes this issue. 👍

**Comment by flaviadefaria** [comment] 2022-12-23 21:43
As a note, I'm going to be OOO from Dec 23rd to January 9th. In case this needs to be paid before the week of January 9th then please reassign.

**Comment by flaviadefaria** [comment] 2023-01-10 14:11
@Luke9389 @NikkiWines has this been fixed by Luke's PR? Can we close this?

**Comment by NikkiWines** [comment] 2023-01-10 18:31
@flaviadefaria it looks like https://github.com/Expensify/App/pull/12447 is still open, so no, I don't think it's been resolved yet. However, looks like they're in the final stages for review for that PR so it should be resolved shortly.

**Comment by Luke9389** [comment] 2023-01-11 00:59
Yep, that PR should be merged soon. I've mentioned this issue in the description of my PR so I _think_ this one will automatically close when it's merged.

**Comment by flaviadefaria** [comment] 2023-01-27 08:54
Reopening so that I can remember to pay the reporting bonus to @daraksha-dk some time today!

**Comment by flaviadefaria** [comment] 2023-01-27 16:27
Offer sent, waiting for @daraksha-dk to accept it so that I can pay.

**Comment by flaviadefaria** [comment] 2023-01-27 17:16
Paid!

**Closed by flaviadefaria** 2023-01-27 17:16 UTC
Labels: Reviewing, Daily, Internal, Bug

**Comment by flaviadefaria** [comment] 2023-01-30 11:00
I'm confused with these latest post from Melvin. @NikkiWines do we just check it all off or do we need to do anything here?

**Comment by NikkiWines** [comment] 2023-01-31 00:43
Updated my steps. @flaviadefaria I think in this case since the bug was introduced in the midst of a major UI refresh that we don't need a regression test for this particular issue. I think you can check off that final check box.
