### ISSUE TITLE
[HOLD for payment 2023-09-06] [$1000] Android - Sign In - Get started below page is cut off if switch tab than come back to app & start typing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23718] opened 2023-07-27 10:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the login page
2. Tap on the email field to open the soft keyboard
3. Scroll down and click on any link (Expense report in my case)
4. Switch back to the login page

## Expected Result:
When start typing I should see the complete login page without any cut offs

## Actual Result:
When start typing after Step 4 the login page is not scrolled to the top - "Get started below" page is cut off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/82d1ba84-8533-4de7-b573-180a78f44736

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bbebff5900a82ee</li>
        <li>Upwork Job ID: 1686501797532385280</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 25998264</li>
<li>joh42 | Contributor | 25998265</li>
</ul></li>
    </ul>
</details>

**Comment by tjferriss** [comment] 2023-08-01 22:19
Reproducible.

<img width="353" alt="Screenshot 2023-08-01 at 15 18 22" src="https://github.com/Expensify/App/assets/8292562/2d87fa1b-87da-4ddc-acf6-d7b851fe1fcd">

**Comment by daanish-shaikh** [comment] 2023-08-03 03:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard is shown but textinput not visible, while switching back to the app from another app.

### What is the root cause of that problem?
While switching between apps, when user switches back to the app then the textinput gets focused and keyboard is shown but the screen is positioned to where it was before leaving the app. Ideally if the keyboard is shown user should be scrolled to top of the screen.

### What changes do you think we should make in order to solve the problem?
Add a listener for keyboard to check when it is shown and according to that we invoke `scrollPageToTop()` to make the textinput field visible while typing.

Add listener for keyboard in src/pages/signin/SignInPageLayout/index.js
```
import {View, ScrollView, Keyboard} from 'react-native';
```
```
    useEffect(() => {
        this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
        return () => {
            this.keyboardDidShowListener.remove();
        };
    }, []);

    const _keyboardDidShow = () => {
        scrollPageToTop();
    };

```

**Comment by joh42** [comment] 2023-08-04 14:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is that when we reopen the app on the [SignInPage](https://github.com/Expensify/App/blob/6730662b0c89c0f32045e57273ff39e0d78661a7/src/pages/signin/SignInPage.js) after clicking on a link, the app does not scroll back to the top like on mWeb.
### What is the root cause of that problem?
We do not listen for when the app becomes active again. Rather, we use default scrolling whenever we start typing, which means that only the input field is scrolled into view when we type.
### What changes do you think we should make in order to solve the problem?

If we want to replicate the behavior on mWeb, I suggest we use the `AppStateMonitor.addBecameActiveListener` to listen for when the app becomes active. If we are not at the top when the user goes back to the app on the [SignInPage](https://github.com/Expensify/App/blob/6730662b0c89c0f32045e57273ff39e0d78661a7/src/pages/signin/SignInPage.js), we scroll to the top. Also, it's worth noting that on mWeb there is no scrolling animation, rather we're immediately sent to the top.

Link to the AppStateMonitor: https://github.com/Expensify/App/blob/6730662b0c89c0f32045e57273ff39e0d78661a7/src/libs/AppStateMonitor/index.js
### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-08-05 11:12
Thanks @joh42 for the proposal. I confirm that the issue is also happening on iOS, although we might want the page to go to the top only when the input is focused. Is it doable?

**Comment by joh42** [comment] 2023-08-05 20:28
Thanks for your reply @mollfpr. That makes sense, it might be confusing to users if the page scrolls even if the input field is not focused. I just threw together a quick test, and yes we can check if the input is focused when the app is opened:

https://github.com/Expensify/App/assets/138504087/ff0ff71e-b031-49e2-9d47-c274ff8ba645

**Comment by joh42** [comment] 2023-08-05 20:41
Thanks for your reply @mollfpr. That makes sense, it might be confusing to users if the page scrolls even if the input field is not focused. I just threw together a quick test, and yes we can check if the input is focused when the app is opened:

https://github.com/Expensify/App/assets/138504087/bbb93ac4-53fb-4039-9f8f-b5a1db4ef5b3


https://github.com/Expensify/App/assets/138504087/9de4a240-dab2-42d5-a112-cf1ec26d030a

**Comment by mollfpr** [comment] 2023-08-06 02:55
Looks great, thanks @joh42 

Let's go with @joh42 [proposal](https://github.com/Expensify/App/issues/23718#issuecomment-1665741165). It will scroll up when the input focus and the app is active.

🎀 👀 🎀 C+ reviewed!

**Comment by daanish-shaikh** [comment] 2023-08-07 03:38
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Keyboard is shown but textinput not visible, while switching back to the app from another app.
> 
> ### What is the root cause of that problem?
> While switching between apps, when user switches back to the app then the textinput gets focused and keyboard is shown but the screen is positioned to where it was before leaving the app. Ideally if the keyboard is shown user should be scrolled to top of the screen.
> 
> ### What changes do you think we should make in order to solve the problem?
> Add a listener for keyboard to check when it is shown and according to that we invoke `scrollPageToTop()` to make the textinput field visible while typing.
> 
> Add listener for keyboard in src/pages/signin/SignInPageLayout/index.js
> 
> ```
> import {View, ScrollView, Keyboard} from 'react-native';
> ```
> 
> ```
>     useEffect(() => {
>         this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', _keyboardDidShow);
>         return () => {
>             this.keyboardDidShowListener.remove();
>         };
>     }, []);
> 
>     const _keyboardDidShow = () => {
>         scrollPageToTop();
>     };
> ```

Hi @mollfpr, There was no comment or feedback on my proposal, was it not reviewed. And I feel I have correctly identified the root cause and solution for this issue before @joh42. Would like to here your feedback.

**Comment by joh42** [comment] 2023-08-07 08:01
While I certainly agree that you identified the root cause as well @daanish-shaikh, listening to the keyboard wouldn't actually work (on my phone at least):


https://github.com/Expensify/App/assets/138504087/e25f3293-710d-48c6-a811-10245e2d24ac

The keyboard doesn't actually open when I go back to the app, even though the input field still has focus. For context I'm on a Oneplus running Android, and I tried with the default keyboard as well which behaved identically.

**Comment by mollfpr** [comment] 2023-08-07 11:18
@daanish-shaikh Sorry, I forget to post the feedback on your proposal. I already tested your proposal, but I feel using the `keyboardDidShow` is not the correct solution. On Android, the keyboard can be closed while the input is still in focus. As given example above, the input is focused but the keyboard is closed.

**Comment by francoisl** [comment] 2023-08-07 22:48
I feel like this was almost not a bug in the first place (the text input _is_ visible when you start typing), but since the behavior is already different on mWeb, let's go ahead and make it consistent on all platforms.

+1 for joh42's solution, let's go with it.

**Comment by joh42** [comment] 2023-08-08 20:12
Thanks! You can expect the PR to be ready for review either on the 9th or 10th of August. I'll write an update here tomorrow either way.

**Comment by joh42** [comment] 2023-08-09 23:03
Just a quick update - the PR will be ready for review on the 10th

**Comment by joh42** [comment] 2023-08-10 22:48
Another update - I'm unfortunately going to need some more time before this is ready.

**Comment by joh42** [comment] 2023-08-13 16:50
The PR is now ready for review @mollfpr, I apologize for the delays.

The unit test check currently fails as there is a failing unit test on main. I've written this on the PR that I think introduced this, and also reported it as a bug in Slack.

**Comment by joh42** [comment] 2023-08-22 20:03
According to Slack @francoisl is OOO until the 28th. How do we proceed with the PR? @tjferriss @mollfpr

**Comment by tjferriss** [comment] 2023-08-24 16:25
I'm working on finding someone to review the PR.

**Comment by tjferriss** [comment] 2023-08-28 22:07
The PR was merged to staging today.

**Comment by tjferriss** [comment] 2023-08-30 04:42
PR was merged more than 9 days after the assignment so we'll have to apply the 50% penalty.

@mollfpr can you please get started on the checklist when you get a chance?

**Comment by mollfpr** [comment] 2023-08-30 17:33
>PR was merged more than 9 days after the assignment so we'll have to apply the 50% penalty.

Sorry for this; I got sick the last few weeks 🙏

> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR; this is a feature request to scroll the page on native while the input is focused and the app back active.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Tests only for iOS and Android**

**With focus**

1. Go to the login page
2. Tap on the phone/email input field to open the keyboard
3. Scroll down a bit
4. Exit the app (either by clicking on a link or by clicking on the home button)
5. Reopen the app
6. **Verify** that you are scrolled back to the top of the login page


**Without focus**

1. Go to the login page.
2. Make sure the phone/email input field is blurred (click outside the input field; the line under it should not be green)
3. Scroll down a bit.
4. Exit the app (either by clicking on a link or by clicking on the home button)
5. Reopen the app
6. **Verify** that you are not scrolled back to the top of the login page

**Comment by tjferriss** [comment] 2023-09-05 19:24
We're all set for payments to go out tomorrow.

**Comment by luacmartins** [comment] 2023-09-11 13:28
@tjferriss are we done with payments?

**Comment by tjferriss** [comment] 2023-09-12 21:54
We are now. Regression test issue has also been created. So we're all set here.

**Closed by tjferriss** 2023-09-12 21:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
