### ISSUE TITLE
[HOLD for payment 2024-01-03] [$125] Split Bill - Merchant must have the same value after creating the split bill

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29691] opened 2023-10-16 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697047715565069

## Action Performed:
1. Click FAB button
2. Click request money
3. Enter amount => Next
4. Click split 2 users
5. Click add to split
6. Click show more => Merchant, Observe that the default value is "Request"
7. Click split
8. Click Split preview
9. Click show more, in merchant, Observe "Split with...."

## Expected Result:
Merchant must have the same value after creating the split bill

## Actual Result:
There is a difference between the merchant after splitting the bill, when they create the merchant the value is "Request" but when the slit bill is created the merchant has the value "Split with...."

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/b94866a3-8c2d-4a18-a453-0a0580ca9328

</details>

<details>
<summary>Android: mWeb Chrome</summary>

  

https://github.com/Expensify/App/assets/93399543/69dfccdf-e128-4457-82b5-e27984947767

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/2a0ef148-3f5a-455e-9851-a6a318423105

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2b43ff04-a898-451c-9f02-8200c1eaf937

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/b5df915c-adb8-4426-a650-260c32af09ba

https://github.com/Expensify/App/assets/93399543/9c2cc70f-9fbb-4a6f-8d37-e045fa72a29f

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/ed459ce7-63b8-4629-865a-039b8bd8573e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sicarius97** [comment] 2023-10-16 17:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Instead of taking in the user input in the merchant field (by default "Request") in the split bill screen, it automatically defaults to "Split with [participants]".

### What is the root cause of that problem?
The cause of this issue is that in this code the merchant is automatically formatted on splits to the above mentioned:

https://github.com/Expensify/App/blob/a456ef90fe1998d289a892a98578a9ab0f5a5f28/src/libs/actions/IOU.js#L914-L927

### What changes do you think we should make in order to solve the problem?

Instead of automatically formatting it to the "Split with [participants]" by default like it is currently, line 922 above should instead take in the submitted user input when building the transaction so that it reflects that value on submission like it does for the other fields.

**Comment by trjExpensify** [comment] 2023-10-16 17:33
Oh interesting, I think @youssef-lr should have solved this.

**Comment by youssef-lr** [comment] 2023-10-16 17:44
Sorry @sicarius97 this needs to be internal as we also hardcode that merchant in the backend, so even if you send the merchant from the frontend it won't be used.

**Comment by sicarius97** [comment] 2023-10-16 17:49
@youssef-lr Gotcha, no worries. I saw it looked like you had merged some updates for the one on one splits that seemed to be the correct requested format as well

**Comment by sicarius97** [comment] 2023-10-16 17:54
If there is any part of that or the TS transition I can contribute to, let me know!

**Comment by vadymbokatov** [comment] 2023-10-16 21:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant does not have the same value that user entered after creating the split bill or in case the user did not enter it, it does not have the default value.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/a456ef90fe1998d289a892a98578a9ab0f5a5f28/src/libs/actions/IOU.js#L914-L927
in line 922, the value of Merchant is set to a default value.
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/a456ef90fe1998d289a892a98578a9ab0f5a5f28/src/pages/iou/steps/MoneyRequestConfirmPage.js#L229-L243
here after `props.iou.category `, `props.iou.merchant, ` should be passed as a parameter to `IOU.splitBillAndOpenReport` and should be passed to https://github.com/Expensify/App/blob/a456ef90fe1998d289a892a98578a9ab0f5a5f28/src/libs/actions/IOU.js#L1274-L1275
`createSplitsAndOnyxData` to be used as merchant value

**Comment by dangrous** [comment] 2023-10-26 15:21
@youssef-lr Is this issue complete? Or will there be another PR (web-e or app)? Asking so I know whether to take https://github.com/Expensify/App/issues/29713 off of hold. Thanks!

**Comment by trjExpensify** [comment] 2023-10-31 13:30
Not sure why the automation hasn't run here if it's on prod. Asking @youssef-lr to confirm.

**Comment by youssef-lr** [comment] 2023-10-31 16:26
@trjExpensify I missed a Web-E PR that I have locally that's needed, as well as an App PR, will work on these now and request a review shortly.

**Comment by trjExpensify** [comment] 2024-01-03 11:00
👋 @aimane-chnaif checklist time, please!

**Comment by trjExpensify** [comment] 2024-01-03 11:38
Nice, so similarly I think the regression test will get added holistically with the project. So we can close this now.

**Closed by trjExpensify** 2024-01-03 11:38 UTC
Labels: Daily, Internal, Awaiting Payment, Bug

**Comment by namhihi237** [comment] 2024-01-03 11:48
@trjExpensify i think i can receive bonus as a reporter

**Comment by trjExpensify** [comment] 2024-01-03 12:24
Yup, Oct 24th the program change went into effect, so I've sent you an offer of $50 for the bug report.
