### ISSUE TITLE
[$1000] Add the ability to search for rooms by reportID in NewDot

### ISSUE THREAD

**Issue by zsgreenwald** [Expensify/App#24289] opened 2023-08-08 18:21 UTC
# Problem
Guides receive a full pipeline email for their active deals every morning https://github.com/Expensify/Expensify/issues/270849 and we discovered early on there we 2 main problems:

1. We used to hyperlink the Policy room column to take the Guide straight to the #admins room but it would open up a new tab every time, which impacts the performance of NewDot. 
2. We then listed out the reportID, but this forces the Guide to have to copy/paste the ID in the URL and reload the page, producing a similar result as the first problem. 

# Why is this important?
We rely on this daily email to help Guides boost conversion and interact with their most active deals. 

# Solution
Add the ability to copy/paste a reportID in NewDot search, and have it populate the exact #admins room (or for future cases, any room). By using chat switcher (ctrl-k), and using the daily deal digest, it'll make it easy for Guides to search for specific #admins rooms without having to reload NewDot every time. 

Here's the email for reference:
<img width="984" alt="image" src="https://github.com/Expensify/Expensify/assets/11618505/c4a1b9ca-d456-4e99-b41e-442c32f00996">

cc: @quinthar @puneetlath 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d6b632fa0a14d323</li>
        <li>Upwork Job ID: 1688979679126392832</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Contributor | 26114925</li>
</ul></li>
    </ul>
</details>

**Comment by kmwamasali** [comment] 2023-08-08 18:42
Firstly, The image is not loading.
Secondly, is there any guideline for submitting the proposal or is the standard format expected

**Comment by kmwamasali** [comment] 2023-08-08 18:42
Firstly, The image is not loading.
Secondly, is there any guideline for submitting the proposal or is the standard format expected

**Comment by puneetlath** [comment] 2023-08-08 18:43
Hmm, the image is loading for me. But in any case, the solution is simply that we want to allow searching by reportID in the existing search field. 

Yes, the standard proposal template should work fine here.

**Comment by kmwamasali** [comment] 2023-08-08 18:46
Dunno why I'm getting this, see attached screenshot and even 404 on the image link.
Will follow up with the standard proposal
![Screenshot 2023-08-08 214454](https://github.com/Expensify/App/assets/13502241/736e653c-efa8-4f6d-a708-1a751b4dd099)
![Screenshot 2023-08-08 214516](https://github.com/Expensify/App/assets/13502241/1ac39147-5f52-40be-82c7-539b2d3fb283)

**Comment by Pujan92** [comment] 2023-08-08 19:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add feature to search the chat/rooms by reportID

### What is the root cause of that problem?
Currently, we are not considering the reportID for the search.

### What changes do you think we should make in order to solve the problem?
We can add the reportID condition for generating the `recentReportOptions` here which will also check for the reportID within reports.

https://github.com/Expensify/App/blob/db5ad3808506798a16f7d668d650c4add4bfd40d/src/libs/OptionsListUtils.js#L755

```
if (searchValue && (!isSearchStringMatch(searchValue, searchText, participantNames, isChatRoom) && !_.isEqual(reportOption.reportID, searchValue))) {
```

With this, we need to update the error condition here to allow 16 digits text which won't show the valid phone number error.
https://github.com/Expensify/App/blob/db5ad3808506798a16f7d668d650c4add4bfd40d/src/libs/OptionsListUtils.js#L1037

The above changes will affect all the places where we have a similar search.

**Comment by kmwamasali** [comment] 2023-08-08 19:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Guides receive a full pipeline email for their active deals every morning https://github.com/Expensify/Expensify/issues/270849 and we discovered early on there we 2 main problems:

We used to hyperlink the Policy room column to take the Guide straight to the #admins room but it would open up a new tab every time, which impacts the performance of NewDot.
We then listed out the reportID, but this forces the Guide to have to copy/paste the ID in the URL and reload the page, producing a similar result as the first problem.

### What is the root cause of that problem?
Currently the OptionsList utils searches through reports and personal details 
https://github.com/Expensify/App/blob/2e9caea9967bdcfc8d54fc8aa16bcae93524d4c6/src/libs/OptionsListUtils.js#L587C1-L596C21
But does not use the report ID as a valid search result

### What changes do you think we should make in order to solve the problem?
We set the report ID as a valid search result as  by adjusting these params and the following search logic that follows after
https://github.com/Expensify/App/blob/2e9caea9967bdcfc8d54fc8aa16bcae93524d4c6/src/libs/OptionsListUtils.js#L636-L640C11

**Comment by blazejkustra** [comment] 2023-08-09 12:53
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
We want to make it possible for users to find chats by using report IDs.

### What is the root cause of that problem?
Right now, our system lets you search for chats only by using the chat's name or the user's login details. It doesn't let you search with the report ID of a chat.

### What changes do you think we should make in order to solve the problem?
We need to do support searching for report ids here:

https://github.com/Expensify/App/blob/587cd0e414fe70fd1e2ded3069d5c09dd618187d/src/libs/OptionsListUtils.js#L755
After:
```js
if (searchValue) {
    const isReportIdSearch = isChatRoom && Str.startsWith(reportOption.reportID, searchValue);
    if (!isSearchStringMatch(searchValue, searchText, participantNames, isChatRoom) && !isReportIdSearch) {
        continue;
    }
}
```

`Str.startsWith` is utilised as this allows to type only the beginning of reportID.

To fix the header message, additional condition here is needed:

https://github.com/Expensify/App/blob/587cd0e414fe70fd1e2ded3069d5c09dd618187d/src/libs/OptionsListUtils.js#L1037

After:
```js
 if (searchValue && CONST.REGEX.DIGITS_AND_PLUS.test(searchValue) && !isValidPhone && !hasSelectableOptions) { 
```

### What alternative solutions did you explore? (Optional)

None.

Result:

https://github.com/Expensify/App/assets/46095609/dd3a6d0c-0447-4e1f-9859-63e76e7b60ce

**Comment by jeet-dhandha** [comment] 2023-08-09 18:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Feature Request: Implement search with `reportID`.

### What is the root cause of that problem?
- No root cause as its a feature request.

### What changes do you think we should make in order to solve the problem?
- we will add `reportID` as a new attribute in function `isSearchStringMatch` and pass them from below lines:

https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/libs/OptionsListUtils.js#L753

https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/libs/OptionsListUtils.js#L774

- we add a 3rd condition in below line:

https://github.com/Expensify/App/blob/d4490726ca1f6cc340b3c03044fd8c2ca350fdb8/src/libs/OptionsListUtils.js#L556

- Now there can be 2 cases:
    1. To match the exact reportID with `word`. 
        - Eg: `654413879034271` will return the [`654413879034271`].
    2. To match the part of reportID.
        - Eg: `654413` will return the rooms [`654413`879034271, 88333455`654413`].
    
(Using `word` instead of `valueToSearch` as this will allow us to match the exact reportID even if user has added extra space after search).

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by mollfpr** [comment] 2023-08-11 04:29
Sorry, I got sick yesterday. I will give an update today 🙏

**Comment by jeet-dhandha** [comment] 2023-08-14 15:50
Agreed with your review

**Comment by kmwamasali** [comment] 2023-08-14 16:32
Thank you for the review @mollfpr @puneetlath I have a question, if you have multiple reports that begin with the same number will the chosen proposal pick the right one?

**Comment by mollfpr** [comment] 2023-08-14 16:44
@kmwamasali I think that's an edge case, but showing multiple reports is okay if it matches the search value.

For example, you name a room with the first word from someone's email from your list. Both the user and the room should be displayed. Same case if you name a room with another room reportID.

**Comment by kmwamasali** [comment] 2023-08-14 16:48
@mollfpr sorry I had edited my question when I saw that it would be a bit of an edgecase when I reread the desired behaviour, thank you for the time

**Comment by blazejkustra** [comment] 2023-08-14 18:47
@mollfpr [PR](https://github.com/Expensify/App/pull/24548) is ready! 

JFYI I'm ooo tomorrow.

**Comment by zsgreenwald** [comment] 2023-08-21 16:50
It looks like this is still pending a merge to staging due to QA, is that correct @puneetlath ?

**Comment by puneetlath** [comment] 2023-08-21 16:51
That's right. The PR has been merged but isn't on staging yet.

**Comment by mollfpr** [comment] 2023-09-12 11:23
We don't have the BZ checklist here, and this is a feature request, but in case we want to have the regression step.

1. Sign in to the App
2. Click on the search button (magnifying glass icon) on LHN
3. Type #admins/#announce report id into the search bar
4. **Verify** that appropriate reports show up on the list when typing
5. Search with random numbers
6. **Verify** that no results show up
7. Search with a valid phone number
8. **Verify** that a phone number shows up
9. 👍 or 👎

**Comment by mollfpr** [comment] 2023-09-25 16:38
@puneetlath Could we complete the issue now? Thanks!

**Comment by puneetlath** [comment] 2023-09-26 03:16
Whoops, looks like our automation never ran. Looks like the only payment due is @mollfpr for C+. Paid. 

Thanks everyone!

**Closed by puneetlath** 2023-09-26 03:16 UTC
Labels: Reviewing, External, Weekly, NewFeature
