### ISSUE TITLE
[$250] [Workspace Feeds] Auth RequestReplacementExpensifyCard returned an error when deactivating card

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50394] opened 2024-10-08 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh051001@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [Admin] Asssign a virtual card to member.
3. [Admin] Go to Expensify Card.
4. [Admin] Click on the member with the virtual card in Step 2.
5. [Admin] Change the limit to 0.00
6. [Member] Go to Wallet.
7. [Member] Click on the Expensify Card.
8. [Member] Click Report virtual card fraud.
9. [Member] Click Deactivate card.

## Expected Result:
The error message should be a proper error message.

## Actual Result:
The error message is Auth RequestReplacementExpensifyCard returned an error.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/735968bd-64a8-44a5-87cf-0ab58089552c

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021844041896258257372</li>
        <li>Upwork Job ID: 1844041896258257372</li>
        <li>Last Price Increase: 2024-10-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @koko57</details>

**Comment by IuliiaHerets** [comment] 2024-10-08 10:54
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment] 2024-10-08 10:54
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mountiny** [comment] 2024-10-09 23:08
This needs better error handling, when the card is deactivated we send the onyx update to remove the card, but it might take longer so the user was still able to see the card there

**Comment by mountiny** [comment] 2024-10-09 23:25
@koko57 would you be able to look as well? I can see that the updates are being queued to remove the card from Onyx, but it seems like it's not being applied correctly/ re-rendered. 

I will need to look more later too

**Comment by koko57** [comment] 2024-10-10 06:17
@mountiny yeah, of course I will take a look. If any other problems with Expensify Card will be found, ping me please, I can take care of them

**Comment by mountiny** [comment] 2024-10-10 08:34
If you find this needs to be addressed in BE, then please ping me in slack 🙌

**Comment by koko57** [comment] 2024-10-11 06:36
@mountiny Sorry for the delay here - I just checked this flow and looks like we're getting this message from the BE
<img width="1024" alt="Screenshot 2024-10-11 at 13 33 12" src="https://github.com/user-attachments/assets/aa9dade3-ddf7-418e-ac3f-d80fa8176be7">

I'll check if we're handling it somehow on the FE, but still the BE message would need to be changed.

**Comment by mountiny** [comment] 2024-10-14 10:35
From the [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228d0cd0bc3848799c-BKK%22%20AND%20timestamp%3A%5B2024-10-10T00%3A00%20TO%202024-10-15T23%3A59%5D), its because the account does not have the legal first name set, but I think we do not have this restriction when creating a new virtual card. We should add better error handling for sure.

**Comment by mountiny** [comment] 2024-10-14 11:07
The problem here is that the card was in a deactivated state when you tried to get a new one; they took the action very fast, so the pusher update did not come in. Normally, the card would be removed from Onyx, and they could not go to the details. In this case I guess the best option is just to handle the error better so it says the card was deactivated

**Comment by koko57** [comment] 2024-10-16 03:39
@mountiny any changes required from the FE side?

**Comment by mountiny** [comment] 2024-10-16 04:07
I think we should do the same as when creating the card and show a spinner when the replacement card is requested until we get a response and then show an error in case there was one

**Comment by mountiny** [comment] 2024-10-16 04:08
I will try to handle the errors nicer in backend

**Comment by mountiny** [comment] 2024-10-18 03:35
On my list

**Comment by mountiny** [comment] 2024-10-21 10:43
Still on my list

**Comment by mountiny** [comment] 2024-10-23 12:20
Started a draft, will need to test more

**Comment by mountiny** [comment] 2024-10-24 05:02
Web Pr is in staging

**Comment by mountiny** [comment] 2024-10-24 05:03
@koko57 the error response shape now should be 
![image](https://github.com/user-attachments/assets/a31ffbfe-705b-4736-b880-d273ae5e5e42)

Can you please update the flow to handle the error and show it under the button when the user tries to replace the card?

**Comment by muttmuure** [comment] 2024-10-29 16:15
Is this one done?

**Comment by slafortune** [comment] 2024-10-29 16:38
Deployed to Web-Expensify/production 5 days ago 👍 
@koko57 did you address [this](https://github.com/Expensify/App/issues/50394#issuecomment-2434306787) comment?

**Comment by koko57** [comment] 2024-10-30 10:23
@slafortune @mountiny Sorry, I've somehow missed the notification for this issue 🙇🏻  I'll try to address this today, if I won't manage to do that I'll ask someone from my team

**Comment by mountiny** [comment] 2024-10-30 13:48
np

**Comment by narefyev91** [comment] 2024-10-31 07:58
@mountiny will try to fix this today - can you help to understand what exactly we try to fix here? Just to show correct message under the button - "Cannot replace card that has no limit set"?

**Comment by koko57** [comment] 2024-11-04 08:37
I'm back I can take it over back

**Comment by mountiny** [comment] 2024-11-04 22:52
Let me know if there is more changes in BE required @koko57

**Comment by koko57** [comment] 2024-11-05 04:41
@mountiny Sorry I've been working mainly on some other issue yesterday. I've pulled the newest main and I couldn't reproduce the issue - I cant't change the limit to 0.00. This PR introduced this regression (? - I think we wanted to be abe to set the value to 0). I can fix it here but I just wanted to confirm we want to be able to set it to 0.00.

**Comment by koko57** [comment] 2024-11-05 05:06
@mountiny on which API call we get this error you pasted here? I'm still getting "Auth RequestReplacementExpensifyCard returned an error" for ReportVirtualExpensifyCardFraud

**Comment by koko57** [comment] 2024-11-05 05:11
And I see that it now looks different as it's not displayed in the RHP but it is closed and only appears below the card in the wallet with the generic error

<img width="507" alt="Screenshot 2024-11-05 at 12 09 48" src="https://github.com/user-attachments/assets/a65d3017-b897-46aa-bf37-4db55e23eb20">

**Comment by koko57** [comment] 2024-11-05 07:51
btw if only the error message will be changed like here https://github.com/Expensify/App/issues/50394#issuecomment-2434306787 we don't need any changes on the FE

**Comment by mountiny** [comment] 2024-11-05 10:24
It should be possible to change the limit to 0, that will deactivate the card too. We should probably handle that case with optimistic update too

I need to look into this later today or tomorrow

**Comment by koko57** [comment] 2024-11-05 13:02
Doubled error message is from the changes here https://github.com/Expensify/App/pull/51841 cc @DylanDylann 
I think we want only one error to be displayed - I will fix it here

**Comment by mountiny** [comment] 2024-11-06 10:37
@koko57 I think we can also create a new key for the error to show it above the button same as we do when trying to create a new card

**Comment by koko57** [comment] 2024-11-08 05:43
@mountiny we discussed on Slack, we don't need it, we can use the one we already have. I've opened a draft PR https://github.com/Expensify/App/pull/52162 for fixing the value to be enabled to be changed to 0 and the loader + error on the RequestReplacement page. I'll check it once again, but yesterday I was still getting "Auth RequestReplacementExpensifyCard returned an error"

**Comment by koko57** [comment] 2024-11-08 10:13
@mountiny after implementing the magic code we have the error and loader back on the RequestReplacement page. 
I see we have wonder a very similar error message for removing a workspace member. I wonder why actually only this one: "Auth RequestReplacementExpensifyCard returned an error" was raised as a bug.

<img width="604" alt="Screenshot 2024-11-08 at 17 00 50" src="https://github.com/user-attachments/assets/8abca60e-
aed6-4230-bf6b-b3f5e1062abd">

LMK what else should we do with this issue - should it be changed on the BE the way you [mentioned](https://github.com/Expensify/App/issues/50394#issuecomment-2434306787)? If so, there's nothing to do on the FE, maybe apart from this [validation](https://github.com/Expensify/App/issues/50394#issuecomment-2456219963) on EditCardLimit page

**Comment by mountiny** [comment] 2024-11-08 16:11
ok thanks, I will need to follow up on this and test locally for the errors

**Comment by mountiny** [comment] 2024-11-13 01:16
still

**Comment by mountiny** [comment] 2024-11-15 14:29
will update

**Comment by mountiny** [comment] 2024-11-18 12:33
On my list

**Comment by mountiny** [comment] 2024-11-20 13:00
same, prioritizing more important fixes

**Comment by mountiny** [comment] 2024-11-25 20:49
no update

**Comment by mountiny** [comment] 2024-11-29 17:53
looking

**Comment by mountiny** [comment] 2024-11-29 18:10
@koko57 I might need a refresh on when exactly we running into this issue. Are you able to reproduce still? If so, can you please share the email/ requestID with the issue? thanks!

**Comment by koko57** [comment] 2024-12-02 10:12
@mountiny ok, I will check as I need a refresher myself 😅 and will let you know if there's still a problem

**Comment by mountiny** [comment] 2024-12-02 12:21
I am just curious what errors we are not handling as from what I can see it seems like we should handle most of the errors ok now

**Comment by slafortune** [comment] 2024-12-06 13:50
@koko57 wanted to check if you had an update on this?

**Comment by koko57** [comment] 2024-12-09 08:27
@slafortune sorry for the delay - I'm checking it today

**Comment by koko57** [comment] 2024-12-09 08:58
On staging - we're still validating if the amount is changed to 0 - so I'm not able to recreate the whole flow

**Comment by koko57** [comment] 2024-12-09 09:16
Still having this error after blocking the validation locally 
<img width="379" alt="Screenshot 2024-12-09 at 10 15 03" src="https://github.com/user-attachments/assets/bfa8ded5-0b0b-46c1-8ae6-f61d3726a5d4">

**Comment by koko57** [comment] 2024-12-09 09:18
<img width="781" alt="Screenshot 2024-12-09 at 10 17 30" src="https://github.com/user-attachments/assets/cce6c3ef-7386-4fa2-9c33-9d38b5fb055e">


response from ReportVirtualExpensifyCardFraud cc @mountiny

**Comment by mountiny** [comment] 2024-12-09 11:21
This styling looks wrong 
<img width="725" alt="image" src="https://github.com/user-attachments/assets/77f17867-ab86-4d86-9f4d-9fa9af7669a6">

@koko57 do you see that too? Would you be able to create a fix for these styles to match other form designs? 

Created a PR which should hopefully show the correct errors now
https://github.com/user-attachments/assets/131f0ead-9233-4f52-97d5-f92466362485

**Comment by koko57** [comment] 2024-12-09 13:13
@mountiny I'll check it, I haven't reached this screen today and I will open a PR when I fix it

**Comment by mountiny** [comment] 2024-12-09 13:19
You need to issue someone the physical card and then as the assignee try to get it shipped

**Comment by koko57** [comment] 2024-12-09 13:40
ok, thanks for the hint!

**Comment by koko57** [comment] 2024-12-09 14:05
@mountiny just to confirm - when we go to confirmation page and click on of the item to edit the field and we're then redirected to a proper step - what should the header back button do?

- [current behavior] get the user back to the card page (exit the flow like on the recording)

https://github.com/user-attachments/assets/24d3ae2c-e3b8-418d-9bad-5480cd813015


- get the user back to the confirmation?

**Comment by koko57** [comment] 2024-12-09 14:29
PR ready for review https://github.com/Expensify/App/pull/53755

**Comment by mountiny** [comment] 2024-12-09 15:19
Same as on any confirmation page of a form - it should go back to the confirmation page

**Comment by koko57** [comment] 2024-12-09 15:57
ok, so then should I fix it here or a new issue is necessary?

**Comment by mountiny** [comment] 2024-12-09 16:06
Lets fix it here

**Comment by koko57** [comment] 2024-12-09 16:22
@mountiny should I also unlock the validation to enable changing the value to 0?

**Comment by mountiny** [comment] 2024-12-09 16:54
@koko57 lets leave that out for a separate PR/ issue

**Comment by koko57** [comment] 2024-12-10 11:50
navigation issue fixed https://github.com/Expensify/App/pull/53755

**Closed** 2024-12-11 11:40 UTC
Labels: Reviewing, Weekly, Internal, Bug
