### ISSUE TITLE
[HOLD for payment 2024-04-05] [Simplified Collect][Taxes] Android - Workspace - Tax name field isn't auto focused the keyboard isn't visible

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38572] opened 2024-03-19 11:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue found when executing PR:** https://github.com/Expensify/App/pull/37967
**Issue reported by:** Applause - Internal team

## Action Performed:
Precondition: With a new expensifail account in OD, create a Collect workspace with workspace chat enabled.
1. In ND, log in with the same account
2. Navigate to Workspace settings - More features
3. Enable Taxes
4. Navigate to Workspace settings - Taxes
5. Tap on the "+ Add rate" button
6. Tap on the "Name" field

## Expected Result:
The keyboard should be visible.

## Actual Result:
Tax name field isn't auto focused, the keyboard isn't visible, only the cursor is shown. The keyboard appears if you tap inside the field.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/4c36e1c7-e780-42d1-bf98-46366d157bff

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb504f048b994348</li>
        <li>Upwork Job ID: 1770073117296906240</li>
        <li>Last Price Increase: 2024-03-19</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-19 11:51
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-03-19 11:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tax name field isn't auto focused, the keyboard isn't visible, only the cursor is shown. The keyboard appears if you tap inside the field.

### What is the root cause of that problem?

We pass `autoFocus` props into tax name TextInput that makes the cursor appears but the keyboard doesn't appear

https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L102
### What changes do you think we should make in order to solve the problem?
We should use `useAutoFocus` hook in `TextSelectModal` and pass the ref as `inputCallbackRef`

https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L102
### What alternative solutions did you explore? (Optional)
NA

**Comment by askavyblr** [comment] 2024-03-19 13:30
### Proposal


### Please re-state the problem that we are trying to solve in this issue.

The tax name field lacks auto-focus, rendering the keyboard invisible.

### What is the root cause of that problem?

We don't have autofocusing behavior

### What changes do you think we should make in order to solve the problem?

Add autofocusing behavior by using useAutoFocusInput

`const {inputCallbackRef} = useAutoFocusInput();`

`ref={inputCallbackRef} and remove autoFocus `

https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/components/TextPicker/TextSelectorModal.tsx#L41-L45

What alternative solutions did you explore? (Optional)

N/A

**Comment by ahmedGaber93** [comment] 2024-03-19 14:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Workspace - Tax name field isn't auto focused the keyboard isn't visible

### What is the root cause of that problem?
this a common behaviour in android native when try to focus input while transition is not ended yet.
### What changes do you think we should make in order to solve the problem?
we should wait transition to end then focus input by those steps.

follow this approech in [TextSelectorModal.tsx](https://github.com/Expensify/App/blob/34fa9871c541ccfa03db46bc6e9e428288f718a3/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx)

```javascript
const inputRef = useRef<BaseTextInputRef | null>(null);

<Modal
  ...
  onModalShow={() => rest?.autoFocus && inputRef.current?.focus()}
>

   <TextInput
      {...rest}
      autoFocus={false}  // <<<< add this after rest.
      ref={(e) => inputRef.current = e}  // <<<< add this after rest.
   />

</Modal>

```

<details>
<summary>result</summary>


https://github.com/Expensify/App/assets/41129870/7e2aec3d-1848-48df-b600-9e141b74b12f



</details>

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment] 2024-03-19 18:39
This is not a blocker and something we can address in a follow up to the feature implementation.

**Comment by luacmartins** [comment] 2024-03-19 18:39
cc @kosmydel @filip-solecki

**Comment by ArekChr** [comment] 2024-03-20 15:10
Hey @luacmartins, I'm available to handle this issue, please assign me

**Comment by situchan** [comment] 2024-03-20 15:39
I think this can be handled in #37955.
We're just looking for other pages where this issue happens.
cc: @Krishna2323

**Comment by trjExpensify** [comment] 2024-03-21 21:46
Ah, should we hold on #37955 then? Perhaps you could test it with that PR maybe?

**Comment by situchan** [comment] 2024-03-21 21:47
This case was not covered on that PR

**Comment by luacmartins** [comment] 2024-03-21 22:46
Ok, so we still need this issue. cc @ArekChr since you're assigned to it

**Comment by luacmartins** [comment] 2024-03-22 23:06
I'll take this one

**Comment by ahmedGaber93** [comment] 2024-03-23 01:03
@luacmartins 
I think you missed fixing `add new rate page` (current GitHub issue), and you only fix `edit rate page`.
https://github.com/Expensify/App/blob/729d4758be1ca005113148f1dc0dd3f9694ffa5b/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L100

**Comment by luacmartins** [comment] 2024-03-25 15:19
Thanks @ahmedGaber93! It seems like we were already using `autoFocus` there so it was working when I tested. I created a PR to make the behavior consistent.

**Comment by alitoshmatov** [comment] 2024-04-01 12:58
No payment needed for me as C+ reviewer

**Comment by luacmartins** [comment] 2024-04-05 18:42
No [payment needed](https://github.com/Expensify/App/issues/38572#issuecomment-2029720843). Closing.

**Closed by luacmartins** 2024-04-05 18:42 UTC
Labels: External, Engineering, Weekly, Awaiting Payment
