### ISSUE TITLE
[Awaiting checklist] [$250]  Mention - Delay in removing mention list when pressing CMD+K

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41136] opened 2024-04-27 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4523297&group_by=cases:section_id&group_order=asc&group_id=306201
**Email or phone of affected tester (no customers):** shussain+accoun1@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open a chat
2. Enter "@" to open mention list
3. Now press CMD+K to open search modal
4. Notice mention (or emoji)  list removed after a delay

## Expected Result:
Mention list should be removed without delay

## Actual Result:
Delay in removing mention list when pressing CMD+K

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0af475b9-e467-4a71-a138-9249fd0d9b43

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d621ca194199c72</li>
        <li>Upwork Job ID: 1784861924277809152</li>
        <li>Last Price Increase: 2024-05-07</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-04-27 13:54
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-27 13:54
We think that this bug might be related to #vip-vsp

**Comment by bernhardoj** [comment] 2024-04-27 14:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The mention suggestion is closed with a delay when we open search page with shortcut.

### What is the root cause of that problem?
The mention suggestion list will close when the composer is blurred. 
https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L346-L348
https://github.com/Expensify/App/blob/10fc359d9fdd1e05e03a4769e2a73f95e703be51/src/pages/home/report/ReportActionCompose/SuggestionMention.tsx#L281-L285

When we open the search page through shortcut, the focus will shift from the composer to the search page search input after the navigation completes, so it feels delayed.

If we open the search page by mouse, then the composer is immediately blurred when we press the search button, so the issue doesn't happen.

If we open the keyboard shortcut page, then the composer will never be blurred and the suggestion will still be shown.

### What changes do you think we should make in order to solve the problem?

Blur the composer immediately when the shortcut is pressed by blurring the active element.
```
document.activeElement.blur() // we do this for web only
```

**Comment by twisterdotcom** [comment] 2024-05-03 09:16
Bump @eVoloshchak on these proposals!

**Comment by twisterdotcom** [comment] 2024-05-03 12:07
@isabelastisser I'll be OOO next week. Just tagging you in to move this along.

**Comment by eVoloshchak** [comment] 2024-05-06 15:37
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/41136#issuecomment-2080792346) looks good to me!

> do for other shortcuts too

I agree, let's have a universal method that would ensure it's called for every shortcut

🎀👀🎀 C+ reviewed!

**Comment by bernhardoj** [comment] 2024-05-11 05:15
@eVoloshchak hey, after reading @ZhenjaHorbach, I think the idea to use the navigation `isFocused` state is better to hide the suggestion menu. The only difference is, that I would put the `isFocused` usage here.
https://github.com/Expensify/App/blob/ada489f1cc6061d674066e59b26c0c000a0a9a52/src/pages/home/report/ReportActionCompose/SuggestionEmoji.tsx#L152-L158

```
if (shouldBlockCalc.current || !value || !isFocused) {
    shouldBlockCalc.current = false;
    resetSuggestions();
    return;
}
```

**Comment by twisterdotcom** [comment] 2024-05-13 11:03
@eVoloshchak and @AndrewGable - does this sound good? I think we can still let @bernhardoj complete it, but @bernhardoj we should probably split maybe $200 / $50 for you / @ZhenjaHorbach here on the payment.

**Comment by twisterdotcom** [comment] 2024-05-14 09:41
@bernhardoj do you agree here? Apologies, but it sounded from this...
>The only difference is, that I would put the `isFocused` usage here

...like you were still using the majority of your own solution anyway.

If it truly is that the whole of @ZhenjaHorbach's solution is better (which @AndrewGable and @eVoloshchak should confirm too), then we should just assign @ZhenjaHorbach.

**Comment by bernhardoj** [comment] 2024-05-14 11:54
I tested @ZhenjaHorbach first solution but it doesn't work because of an issue that's why I suggested a different usage of `isFocused`, but after applying his additional changes (which address the issue) from the proposal, it works.

But I'd still suggest separating the `isComposerFocused` and `isFocused` because they are not dependent on each other.

We can reassign this to @ZhenjaHorbach

**Comment by eVoloshchak** [comment] 2024-05-27 14:27
[PR](https://github.com/Expensify/App/pull/42255) is ready, will be merged once the merge freeze is over

**Comment by AndrewGable** [comment] 2024-06-03 16:55
PR merged

**Comment by twisterdotcom** [comment] 2024-06-14 13:48
### Payment Summary
[Upwork Job](https://www.upwork.com/jobs/~014d621ca194199c72)
- Reviewer: @eVoloshchak paid $250 via NewDot
- Contributor: @ZhenjaHorbach paid $250 via Upwork (https://www.upwork.com/nx/wm/offer/102735169)

**Comment by twisterdotcom** [comment] 2024-06-17 11:58
Still waiting on @eVoloshchak.

**Comment by eVoloshchak** [comment] 2024-06-18 20:55
- The PR that introduced the bug has been identified. Link to the PR: unable to pinpoint the exact PR that has caused this, as this was present in the initial implementation 
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed

**Regression Test Proposal**

1. Open a chat
2. Enter "@" or start typing an emoji name to open mentions/emoji list
3. Press CMD+K to open the search modal
4. Verify there is no delay when mentions or emoji list is hidden

**Do we agree 👍 or 👎**

**Comment by JmillsExpensify** [comment] 2024-06-19 05:21
$250 approved for @eVoloshchak

**Closed** 2024-06-19 15:42 UTC
Labels: External, Daily, Bug
