### ISSUE TITLE
[$1000] Assign Task - Attendee name disappears when editing the title of the task for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23684] opened 2023-07-26 19:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/23342

## Action Performed:
1. Access staging.new.expensify.com
2. Tap on the FAB button
3. Select "Assign task"
4. Enter a Title and confirm
6. Assign someone the task
7. Create the task
8. Edit the title of the task in the DM

## Expected Result:
User expects the title to be edited and the assigned person to remain

## Actual Result:
The title is edited but the assigned person disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:**  n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c048c5ad-9d4e-4991-b400-55ceb98d2057

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team / @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690264910826859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a2f6fe3ad8185d61</li>
        <li>Upwork Job ID: 1686172805336526848</li>
        <li>Last Price Increase: 2023-08-11</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2023-07-26 19:52
This looks related to https://github.com/Expensify/App/issues/23549#issuecomment-1652293926

**Comment by thienlnam** [comment] 2023-07-26 20:02
I can't seem to reproduce this with a valid task

**Comment by thienlnam** [comment] 2023-07-26 20:14
Actually I can, it seems that it has to be an existing task with a fresh login for this to work

**Comment by thienlnam** [comment] 2023-07-26 20:25
Happens on prod so this is not a blocker, I think this needs to be updated in the BE though

**Comment by situchan** [comment] 2023-07-26 20:25
yes, this happens because `managerEmail` doesn't exist in task report saved in Onyx. (this is expected, coming from secure logins refactor)
I also clarified repro step in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690336612960059?thread_ts=1690264910.826859&cid=C049HHMV9SM).

**Comment by situchan** [comment] 2023-07-26 20:26
After assign task again, `managerEmail` is added optimistically so not repro anymore before logout.

**Comment by thienlnam** [comment] 2023-07-26 21:12
cc @Beamanator Ah, I think this is because the BE still relies on assignee email and doesn't grab it from the assigneeAccountID. We should probably update the auth command

**Comment by thienlnam** [comment] 2023-08-01 00:33
Part of removing the managerEmail is that now we'll have to update the FE to grab the login from the managerID

**Comment by Beamanator** [comment] 2023-08-01 07:37
Yeah makes sense to me 👍

**Comment by thienlnam** [comment] 2023-08-04 00:08
BE should already be returning the managerID, though I'm not sure if the FE will have the email for the personal details for the managerID. Going to throw the external label to have someone investigate

**Comment by thienlnam** [comment] 2023-08-04 00:34
Not overdue, just added external

**Comment by pradeepmdk** [comment] 2023-08-04 02:30
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
The title is edited but the assigned person disappears

### What is the root cause of that problem?
`CreateTask` manager email is not stored in the onyx.
so first time edit task assignees name not passing so api return managerID null and managername empty
![Screenshot 2023-08-04 at 7 55 51 AM](https://github.com/Expensify/App/assets/16595846/95cdb8bb-c554-4240-9dee-78f7cabb5db1)

 
![Screenshot 2023-08-04 at 7 57 34 AM](https://github.com/Expensify/App/assets/16595846/87675a06-cce8-4bae-a7ed-0787e5716de4)

i think in the backend side they are using the assignee keyword instead of assigneeAccountID

### What changes do you think we should make in order to solve the problem?
1) We need to fix it from the back-end side based assigneeAccountID need retrieve the managerEmail
2) on create task we need store the managerEmail
### What alternative solutions did you explore? (Optional)
NA

**Comment by isabelastisser** [comment] 2023-08-07 16:50
@rushatgabhane can you please review the proposals above? Thanks!

**Comment by rushatgabhane** [comment] 2023-08-07 16:54
Sure thing!

**Comment by pradeepmdk** [comment] 2023-08-07 19:04
@rushatgabhane can you check my RCA once, I have the exact reason behavior for returning the `managerId 0 `.but still we can fix this on the backend side. I just updated with highlighting the keyword https://github.com/Expensify/App/issues/23684#issuecomment-1664886591

**Comment by pradeepmdk** [comment] 2023-08-07 19:10
@rushatgabhane can you My RCA once.  because I have the exact behavior of the backend returning as `managerId 0 `. but still, this is a backend issue only. I just updated with highlighting keywords https://github.com/Expensify/App/issues/23684#issuecomment-1664886591

**Comment by thienlnam** [comment] 2023-08-09 21:34
Internal PR has been merged, can we still see if this problem exists?

**Comment by pradeepmdk** [comment] 2023-08-10 00:41
![Screenshot 2023-08-10 at 6 08 08 AM](https://github.com/Expensify/App/assets/16595846/8165fa59-bf0c-4dc5-a5d5-149ecc8b2c87)
@thienlnam @rushatgabhane   now it's fixed. working correctly.

**Comment by thienlnam** [comment] 2023-08-10 17:51
We're removing managerEmail entirely as part of a separate project and that should be taken care of there. 

cc @isabelastisser Could we just get a payment to the reporter of this bug?

**Comment by isabelastisser** [comment] 2023-08-16 16:48
https://www.upwork.com/freelancers/~01223f6e853d3d82b4

All set!

**Closed by isabelastisser** 2023-08-16 16:48 UTC
Labels: Engineering, Daily

**Comment by mvtglobally** [comment] 2023-08-16 20:44
Issue not reproducible during KI retests. (First week)
