### ISSUE TITLE
[$500] Web -  An error occurs in the console when we send a link and an image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27247] opened 2023-09-12 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Login >> Open console
2. Click on plus sign >> Create a chat
3. Copy and paste a link in the chat >> Click on send
4. Click on plus sign >> Click on "Add attachment"
5. Select an image >> Send image (In this instance we can see the errors in the console, error: "Unhandled Promise Rejection: DataCloneError: Failed to store record in an IDBObjectStore: BlobURLs are not yet supported.")

## Expected Result:
This process should be done without errors.

## Actual Result:
This process is done with errors.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (38)](https://github.com/Expensify/App/assets/93399543/d1c923f6-e688-42b5-a099-34a5100cd3ad)

https://github.com/Expensify/App/assets/93399543/202feda1-997b-4666-b5d6-9c27b8524b41

**Expensify/Expensify Issue URL:**
**Issue reported by:** @eusalazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694188803526719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f8d9f9c0ae33a1d</li>
        <li>Upwork Job ID: 1701573765381185536</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-12 12:45
I think this is browser limitations, and only happens when you're using Private Mode.

**Comment by EliteDevSolution** [comment] 2023-09-12 13:20
Blob URLs are temporary URLs that represent the data of a Blob or File object. They are typically used to display images or other media directly in a browser window. The error message is indicating that Blob URLs are not supported in the context where you're trying to use them (possibly inside IndexedDB).

**Comment by studentofcoding** [comment] 2023-09-13 06:50
Yes can confirm that this is happening only on the Private Mode.

**Comment by s77rt** [comment] 2023-09-14 20:46
@zukilover @EliteDevSolution @studentofcoding Did you happen to check the root cause (besides the bug being reproducible in private mode only) i.e. what is causing this to fail in private mode and is it something that we can fix?

**Comment by zukilover** [comment] 2023-09-14 22:19
@s77rt This seems to be a webkit bug. It's been reported here before: https://bugs.webkit.org/show_bug.cgi?id=188438

**Comment by s77rt** [comment] 2023-09-18 12:55
Not overdue. I think we can close being a browser bug. cc @JmillsExpensify @isabelastisser

**Comment by EliteDevSolution** [comment] 2023-09-19 16:29
I have already several checks about this issue.
Unfortunately I can not reproduction such as above issue.

**Comment by isabelastisser** [comment] 2023-09-20 15:58
Closing this based on the comments above.

**Closed by isabelastisser** 2023-09-20 15:58 UTC
Labels: External, Daily, Help Wanted, Bug
