### ISSUE TITLE
[$500] User receiving "new message" notification sound even if the phone is on DND 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36714] opened 2024-02-16 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708049588944159

## Action Performed:
1. Enable DND in the android phone
2. Send a message to the expensify account logged in the phone

## Expected Result:
No sound notification

## Actual Result:
Sound notification is heard

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01861dee3b63d29cfc</li>
        <li>Upwork Job ID: 1758531931545219072</li>
        <li>Last Price Increase: 2024-03-01</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2024-02-16 16:47
cc @Julesssss in case you wanna take this one.

**Comment by shahinyan11** [comment] 2024-02-16 17:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User receiving "new message" notification sound even if the phone is on DND
### What is the root cause of that problem?
Missing  code for this functionality
### What changes do you think we should make in order to solve the problem?
1. Instal package to get device DND status
2. Wrap [this](https://github.com/Expensify/App/blob/1f5e0ba30854410e8970d428f30d28a666648896/src/libs/actions/User.ts#L555C25-L555C58) line in `if` blcok

### What alternative solutions did you explore? (Optional)

**Comment by divyanshk443** [comment] 2024-02-17 06:37
**Proposal**


**Please re-state the problem that we are trying to solve in this issue.**

Even if phone is on DND , user is receiving new message notification sound.

**What is the root cause of that problem?**
Need to make changes to the code that handles the notification sounds, specifically in the playSoundForMessageType function which is present in App/src/libs/actions/User.ts. Current implementation doesn't explicitly handle Do Not Disturb (DND) mode

**What changes do you think we should make in order to solve the problem?**

```
function playSoundForMessageType(pushJSON: OnyxServerUpdate[]) {
    // ... (existing code)

    isDNDActive().then((dndActive) => {
        if (!dndActive) {
            // Only play sounds if not in DND mode
            try {
                // ... (existing sound-playing logic)
            } catch (e) {
                // Handle any errors
                // ...
            }
        }
    });
}

```
To implement a function that checks whether the Do Not Disturb (DND) mode is active on a mobile device, we need to use platform-specific APIs provided by the operating system. 

**For example in iOS:**
we can use the AVAudioSession class from the AVFoundation framework to check the current audio session category. In iOS, the audio session category will change when the device enters Do Not Disturb (DND) mode.

Here's how we can implement the isDNDActive function for iOS:

```
const isDNDActive = () => {
    return new Promise((resolve, reject) => {
        const session = AVAudioSession.sharedInstance();
        const currentMode = session.mode;

        if (currentMode === AVAudioSessionModeDoNotDisturb) {
            resolve(true); // DND mode is active
        } else {
            resolve(false); // DND mode is not active
        }
    });
};

```
**For Android:**
On Android, we can use the NotificationManager class to check whether Do Not Disturb (DND) mode is active. we'll need to use the getNotificationPolicy method to retrieve the current notification policy and check if the DND mode is enabled.

Here's how  we can implement the isDNDActive function for Android:

```
const isDNDActive = () => {
    return new Promise((resolve, reject) => {
        const notificationManager = getSystemService(Context.NOTIFICATION_SERVICE);
        const currentPolicy = notificationManager.getCurrentNotificationPolicy();

        if (currentPolicy.priorityCategories.includes(NotificationManager.PRIORITY_CATEGORY_ALARMS)) {
            resolve(false); // DND mode is not active
        } else {
            resolve(true); // DND mode is active
        }
    });
};


```
**What alternative solutions did you explore? (Optional)**
Null

**Comment by Julesssss** [comment] 2024-02-19 09:32
Are we not confusing two things here? DND should block/silence native push notifications, but this sound is occurring from a message received by pusher websocket while the app is alive. It's not a push notification, but an in-app event.

Perhaps we should not play the sound if the app is not in the foreground, but there's an argument that the sound should be played in this case:
- User has media volume above 0
- User hasn't disabled sounds within our settings
- This is an in-app event sound

If pusher triggered a push notification then i would agree with us needing to mute it.

**Comment by mallenexpensify** [comment] 2024-02-19 15:44
I have sound muted on Desktop and I'm still receiving sound notifications. Is that the same bug as here or should I report separately in #expensify-bugs?

**Comment by pecanoro** [comment] 2024-02-19 16:10
@Julesssss I also experienced this, but there are two weird things going on here.

1. As you mentioned, no way to disable the sounds to send the message, I tried muting the phone, DND, vibration only and nothing, since there are no in-app settings to mute them, the sound when you send a message will be always played.

2. My phone has all notifications muted and as David experienced, many times I get the notification sound even if I am not using my phone, so somehow is ignoring the phone settings, not sure how.

**Comment by pecanoro** [comment] 2024-02-19 16:36
> Hey @pecanoro, so on Android our message received sound is controlled by the media volume setting, which I think makes sense for the message SENT sound.

Do you know if we are planning to add the functionality to disable the sounds to the app? It feels pretty weird having to disable media sound in the whole phone just to mute an app.

**Comment by kirillzyusko** [comment] 2024-02-19 17:48
> When I mute in Desktop, it doesn't change my settings on Web/Chrome, even after refresh. Is that related to this bug or should I report in #expensify-bugs ?

@mallenexpensify I think you describe the same problem as in https://github.com/Expensify/App/issues/36487 right?

**Comment by Julesssss** [comment] 2024-02-20 16:32
Ah thanks @nikihatesgh, I added that to the [tracking issue](https://github.com/Expensify/App/issues/36846)

**Comment by mallenexpensify** [comment] 2024-02-21 01:56
> When I mute in Desktop, it doesn't change my settings on Web/Chrome, even after refresh. Is that related to this bug or should I report in #expensify-bugs ?

@kirillzyusko this is expected behaviour, that you need to mute each platform because you might want sounds on one but not another, and there'd be no way to enable this if one switch controlled all.

**Comment by Julesssss** [comment] 2024-02-21 09:59
@mallenexpensify that sounds like expected behaviour.

It's possible to enable an account-wide preference, but this is backend work that I doubt we can prioritize over wave project work.  Also, that would prevent users from having a per-client preference which isn't ideal.

**Comment by Julesssss** [comment] 2024-02-21 11:16
I think we should close this, as it's expected behaviour AND is being handled on separate issues collected [here](https://github.com/Expensify/App/issues/36846). We'll probably keep these internal for now as testing push notifications on iOS is impossible for contributors. 

Once we remove the audio cue from being played on mobile and move the audio cue to the native notification, this will be resolved. Let me know if anyone disagrees.

**Comment by pecanoro** [comment] 2024-02-21 15:51
How is this expected behavior? If my phone is muted, it should not play any notification sounds when I am getting new messages 🤔

**Comment by Julesssss** [comment] 2024-02-21 16:03
> How is this expected behavior? 

@pecanoro  I should have made it clearer, but that was in response to @mallenexpensify's account-wide preference, not your issue. Your issue (which I 100% agree with) was due to a faulty implementation that has to be rewritten and is being handed separately [here](https://github.com/Expensify/App/pull/36807).

We can keep this issue open, but there are lots of different issues being reported here and it's getting confusing. I wanted to close this issue to help clear up our [list of tasks](https://github.com/Expensify/App/issues/36846).

**Comment by Julesssss** [comment] 2024-02-21 16:10
I'll re-open as the PR is about to be merged anyway. 

But further comments should only be related to the iOS/Android sound cue playing. Please raise other issues on the parent [issue tracker](https://github.com/Expensify/App/issues/36846)

**Comment by dylanexpensify** [comment] 2024-02-26 11:51
Question: does this solution cover notification preferences? E.g. notifications set to `Daily` vs `Insant`?

**Comment by Julesssss** [comment] 2024-02-26 12:16
> Question: does this solution cover notification preferences? E.g. notifications set to `Daily` vs `Instant`? [Context](https://github.com/Expensify/App/issues/36875)

If your issue is just the sound playing, then yes I believe so. Right now we're removing the local sound and tying it to mobile push notifications. Once that is done we'll be looking at the room preference.

**Comment by Julesssss** [comment] 2024-02-26 12:17
Wait @dylanexpensify, perhaps [this ](https://github.com/Expensify/App/issues/37098#issuecomment-1963980110)is the issue you are looking for?

**Comment by dylanexpensify** [comment] 2024-02-26 12:41
thanks @Julesssss!

**Comment by dylanexpensify** [comment] 2024-02-26 12:43
Ahh interesting, it looks like mine is similar, but technically earlier than that one linked! However, that one is further along and mine was reported by Applause, so I think we can close mine in favor of that one.

**Comment by Julesssss** [comment] 2024-02-27 15:38
@muttmuure  @dylanexpensify would you mind retesting on the latest staging build, please? This is fixed for me on Android

**Comment by Julesssss** [comment] 2024-02-28 16:00
Just waiting on a review, not overdue

**Comment by Julesssss** [comment] 2024-03-01 16:19
This should be fixed, though i'm unable to verify. My iPhone doesn't play loud notifications for ANY app.

**Comment by kirillzyusko** [comment] 2024-03-04 11:10
@Julesssss should we ask reporter to verify it again?

**Comment by Julesssss** [comment] 2024-03-04 12:17
Hi @m-natarajan, could you please retest on the latest builds? Thanks!

**Comment by Julesssss** [comment] 2024-03-04 13:09
Verified fixed on Android: 

![Screenshot_20240304-130505](https://github.com/Expensify/App/assets/10736861/75648c77-264a-4584-90cc-f245c59b29ec)

**Closed** 2024-03-04 13:09 UTC
Labels: External, Daily, Help Wanted, Bug
