### ISSUE TITLE
[HOLD E/E #359760] [$500] No "Hold Request" and "Add a receipt" option on workspace expense report as Admin

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36202] opened 2024-02-09 02:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing #35744
**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create a new expense request on a collect policy
2. Submit the expense
3. Open the expense report
4. Right-click/long-press the expense preview
5. (if employee) Verify there is no Delete Request (if admin) Verify there is a Delete Request option
6. Press the expense preview to open the transaction thread
7. Press the three-dots button
8. (if employee) Verify there is no Delete Request and Add receipt (if admin) Verify there is a Delete Request and Add receipt option

## Expected Result:
There should be Hold Request and Add a receipt option on Admins side

## Actual Result:
No "Hold Request" and "Add a receipt" option on workspace expense report as Admin

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/c5d1909f-974f-4739-a770-5959a320a8d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c35580d297f84569</li>
        <li>Upwork Job ID: 1755778907181215744</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-02-09 03:21
As the test step coming from my PR, I would like to clarify one thing. The delete request and add receipt option will be shown if the user is an admin AND the action/request owner, so this is not a bug.

**Comment by bernhardoj** [comment] 2024-02-09 10:30
The action owner condition has existed for quite some time
https://github.com/Expensify/App/blob/9463e22ba5c0897d519c0ccc85c12ae591742541/src/libs/ReportUtils.ts#L1239

and I added the admin condition based on this [comment](https://github.com/Expensify/App/issues/34538#issuecomment-1924438029)

**Comment by marcaaron** [comment] 2024-02-09 23:49
>Create a new expense request on a collect policy

Gonna mark this as a non-blocker as people on Collect policies are not actually using these flows yet

**Comment by MitchExpensify** [comment] 2024-02-13 21:39
Where is the option to "Delete Request" in your video @kavimuru ? Are both screens from the admins perspective?

**Comment by MitchExpensify** [comment] 2024-02-13 21:40
This seems pretty clearly wave 6, right @greg-schroeder?

**Comment by MitchExpensify** [comment] 2024-02-18 23:38
Friendly bump @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-02-19 21:24
Looking

**Comment by greg-schroeder** [comment] 2024-02-19 21:25
I think Wave 8 is correct, as the behavior that doesn't match expected is tied to the admin's experience ... if the submitter experience is working as expected, it wouldn't fit in Wave 6's current scope

**Comment by Victor-Nyagudi** [comment] 2024-02-26 10:47
I'm confused on the expected result here. 

- Why would the admin have an "Add receipt" option for a money request they didn't make/submit? Shouldn't the person who submitted the request be the only one to add a receipt because they probably are the only one who has it?

- Giving the admin the ability to delete money requests they didn't make sounds a bit suspicious. That means they could go about deleting any money request in the WS. 

> As the test step coming from my PR, I would like to clarify one thing. The delete request and add receipt option will be shown if the user is an admin AND the action/request owner, so this is not a bug.

This sounds about right.

**Comment by MitchExpensify** [comment] 2024-03-02 02:24
> @greg-schroeder do you know if admins should in fact be able to Add a receipt or Delete?

Friendly bump @greg-schroeder

**Comment by MitchExpensify** [comment] 2024-03-05 05:34
> do you know if admins should in fact be able to Add a receipt or Delete?

@trjExpensify are you able to confirm this perhaps?

**Comment by trjExpensify** [comment] 2024-03-05 10:11
>@trjExpensify are you able to confirm this perhaps?

To answer your question, no they shouldn't be able to delete someone else's request, only put it on hold.

**Comment by youssef-lr** [comment] 2024-03-05 10:13
@trjExpensify we don't allow modifying receipts for admins as well, so I'm thinking we can just close this issue?

**Comment by trjExpensify** [comment] 2024-03-05 10:51
Hm, you sure? I thought an admin/approver on a workspace can attach a receipt for a submitter today on OldDot?

**Comment by youssef-lr** [comment] 2024-03-05 10:54
Ah okay. I though since they can't edit a receipt they can't attach one either. What's the use case for this though? I think I agree with @Victor-Nyagudi [here](https://github.com/Expensify/App/issues/36202#issuecomment-1963830316)

**Comment by JmillsExpensify** [comment] 2024-03-05 14:36
> Why would the admin have an "Add receipt" option for a money request they didn't make/submit? Shouldn't the person who submitted the request be the only one to add a receipt because they probably are the only one who has it?

This is a pretty common use case, especially for employees who are provided a corporate card and the admin has access to the service/receipts. In fact, in some companies employees are instructed to add no receipts, the accounting team handles it for them. I think we need to support this case in order to continue supporting our customers.

**Comment by youssef-lr** [comment] 2024-03-05 14:38
Interesting, thanks for clarifying @JmillsExpensify! So with that in mind, should we also allow admins to replace receipts? Because currently we don't.

**Comment by youssef-lr** [comment] 2024-03-05 14:44
Also, since this falls under editing expenses in general, I think we can have this on hold on my [PR](https://github.com/Expensify/App/pull/36838), because chances are I'll have to update the changes that fixes this later on

**Comment by JmillsExpensify** [comment] 2024-03-05 16:34
>Interesting, thanks for clarifying @JmillsExpensify! So with that in mind, should we also allow admins to replace receipts? Because currently we don't.

We don't allow this, on the logic that admins should be able to add a receipt is none exists. If one does, then they shouldn't be able to "delete" one receipt in order to add a new one. So that's why we allow adding a receipt but not replacing.

**Comment by youssef-lr** [comment] 2024-03-11 14:12
Not overdue, still in the works.

**Comment by youssef-lr** [comment] 2024-03-14 21:27
Still held.

**Comment by youssef-lr** [comment] 2024-03-18 19:51
Same.

**Comment by MitchExpensify** [comment] 2024-03-25 23:26
Almost ready to un-hold @youssef-lr ?

**Comment by MitchExpensify** [comment] 2024-04-01 19:52
Friendly bump @youssef-lr

**Comment by youssef-lr** [comment] 2024-04-08 20:59
We should be able to merge the Web-E PR today, I'll continue work on the App PR meanwhile, starting tomorrow.

**Comment by MitchExpensify** [comment] 2024-04-09 21:26
Nice one @youssef-lr !

**Comment by MitchExpensify** [comment] 2024-04-15 20:43
Checking in on this progress @youssef-lr

**Comment by MitchExpensify** [comment] 2024-04-22 16:29
No worries, switching to weekly as this is polish

**Comment by MitchExpensify** [comment] 2024-04-30 16:24
Can do, I've updated the title and body to reflect that these options are expected from an admin's perspective on a workspace expense:

1. Hold request
2. Add a receipt

**Comment by trjExpensify** [comment] 2024-05-01 23:25
Thanks!

**Comment by youssef-lr** [comment] 2024-05-08 19:34
Working on this next week!

**Comment by MitchExpensify** [comment] 2024-05-20 22:58
Fire likely slowed us down here, do you think this week is the week @youssef-lr ? 😄

**Comment by MitchExpensify** [comment] 2024-06-03 21:10
Fire issues still being prioritized over this I imagine

**Comment by MitchExpensify** [comment] 2024-06-18 02:48
Do you think you'll have bandwidth for this soon @youssef-lr ?

**Comment by youssef-lr** [comment] 2024-06-27 16:25
Yes, I'll find some time for it next week @MitchExpensify

**Comment by MitchExpensify** [comment] 2024-07-08 21:52
Melvin, @youssef-lr is finding time for this when they can

**Comment by MitchExpensify** [comment] 2024-07-16 19:42
Reassigning while I'm leave 🙇

**Comment by youssef-lr** [comment] 2024-07-30 23:57
Looking into this one today @hoangzinh

**Comment by youssef-lr** [comment] 2024-08-07 16:04
I've added a fix here since I touched that logic in the PR https://github.com/Expensify/App/pull/46931/commits/06f3d4d11ac683a23fba1ea758d1cd258617e3db, this is aligned with what we have in OldDot

**Comment by trjExpensify** [comment] 2024-08-09 01:48
So this will be fixed by https://github.com/Expensify/App/pull/46931 in review, right?

**Comment by youssef-lr** [comment] 2024-08-09 09:18
Yup!

**Comment by kevinksullivan** [comment] 2024-08-24 20:49
it's been a while so we no longer have the three dots, but I see hold on this expense. 
![image](https://github.com/user-attachments/assets/dc8a53dc-678a-4377-9859-fd58e04b475e)

**Comment by kevinksullivan** [comment] 2024-08-24 21:03
@hoangzinh original posting expired so here is a new one in upwork

https://www.upwork.com/jobs/~014ecea72e003c577c

lmk when you accept!

**Comment by kevinksullivan** [comment] 2024-08-30 00:08
still looking for internal volunteer

**Comment by trjExpensify** [comment] 2024-09-03 23:03
https://github.com/Expensify/App/issues/36202#issuecomment-2276998969 - yep, closing.

**Closed by trjExpensify** 2024-09-03 23:03 UTC
Labels: Engineering, Daily, Internal, Bug
