### ISSUE TITLE
Web -  Editing Description with Numbers Causes Previous Notification to Empty

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26005] opened 2023-08-26 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money".
2. Enter the desired amount and email address for the money request.
3. Go to the IOU and edit the Description using numbers.
4. Edit the Description again using words and observe that the previous Description notification is now empty.

## Expected Result:
When editing the Description using numbers in the notification, it should still appear in the previous notification just like when editing using words.

## Actual Result:
Editing the Description with numbers causes the previous notification to become empty, which is not the expected behavior

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/88ea6f6e-8d14-4af4-94bf-0687da7b39bb

https://github.com/Expensify/App/assets/93399543/8ce5c86d-7b50-47e3-8fbd-a08cebcfcb57

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692264045005859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c3aafe510f0622f0</li>
        <li>Upwork Job ID: 1696598570983079936</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-08-26 20:31
<img width="391" alt="Screenshot 2023-08-27 at 1 55 34 AM" src="https://github.com/Expensify/App/assets/59088937/b5dcda78-41b9-486a-8546-3776641ac36f">

I think this is a backend issue, when we send just numbers  with description backend is sending the value as integer. If the previous comment is of integet (in-backend) backend is not sending the `oldComment` in originalMessage.

<img width="439" alt="Screenshot 2023-08-27 at 1 57 53 AM" src="https://github.com/Expensify/App/assets/59088937/ccf89f7e-8be8-48da-8a08-d15cadc4eaff">

**Comment by johncschuster** [comment] 2023-08-29 18:59
Thanks for calling that out, @b4s36t4! I'll go ahead and make this an internal issue then.

**Comment by thienlnam** [comment] 2023-08-29 21:43
@mountiny or @luacmartins either of you want to take this one?

**Comment by luacmartins** [comment] 2023-08-29 23:44
I'm the deployer this week and I'll likely not be able to take it as a daily. I'll circle back if deploy duty doesn't take too much time

**Comment by mountiny** [comment] 2023-08-30 16:56
I will take this on

**Comment by b4s36t4** [comment] 2023-08-31 10:00
@mountiny Please also take up this issue -> #26006. If we're sending any extra characters backend is stripping them. Also this happens only with the `comment` property. Alternate solution can be JSON.parsing the comment before sending but this would require some changes in places which we show the changes related to modifiedexpense type. Action is upto you.

**Comment by b4s36t4** [comment] 2023-08-31 10:01
Both the solutions can be solved just by doing a `JSON.stringfy` before sending to backend.. and I think backend parsing is working fine.

**Comment by mountiny** [comment] 2023-09-04 10:07
Havent got around to this

> Both the solutions can be solved just by doing a JSON.stringfy before sending to backend.. and I think backend parsing is working fine.

You suggesting this can be external then? Did you try the solution with `JSON.stringfy`?

**Comment by b4s36t4** [comment] 2023-09-04 10:34
@mountiny Yes I tried with `JSON.stringify` but seems few other changes also required. At that point I have verified that it's working with description change page. Not with the `MODIFIEDEXPESE` report actions.

**Comment by mountiny** [comment] 2023-09-11 15:43
Havent got aroung to this

**Comment by johncschuster** [comment] 2023-09-13 21:12
Hmm... I don't recall adding the `Daily` label. I'm going to remove it and leave the `Weekly` one you've applied, @mountiny

**Comment by mountiny** [comment] 2023-09-18 08:15
Not able to prioritize still

**Comment by mountiny** [comment] 2023-09-25 15:01
Still unable to prioritize

**Comment by johncschuster** [comment] 2023-10-05 20:51
@mountiny Is this one on hold for another issue, or is it just a matter of working on higher priority issues?

**Comment by mountiny** [comment] 2023-10-05 21:32
Not on hold for anything, but higher priority stuff does not really let me work on this issue now

**Comment by mountiny** [comment] 2023-10-17 01:39
Not able to prioritize still

**Comment by johncschuster** [comment] 2023-10-25 14:00
Same as last week

**Comment by mountiny** [comment] 2023-10-25 20:30
cc @rlinoz arent you working on this on another issue?

**Comment by tewodrosGirmaA** [comment] 2023-10-26 09:15
Hello @rlinoz, I had reported a bug prior to the one mentioned in issue https://github.com/Expensify/App/issues/26665. My report was submitted on August 26th, whereas the other report was submitted on September 4th. Hence, my report is the original one, and the one you referred to is a duplicate that has similar root causes. Thank you

**Comment by mountiny** [comment] 2023-10-28 13:18
Thanks! Unassigned and closing in favoour of https://github.com/Expensify/App/issues/26665

Will update the reporters there

**Closed** 2023-10-28 13:18 UTC
Labels: Engineering, Weekly, Internal, Bug
