### ISSUE TITLE
Web -  Assignee contact list is not showing up after user reloads the page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23540] opened 2023-07-25 10:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Open a new account on ND
2. Click on FAB > assign task > give it a title > click on next > click on assignee
3. Reload the page

## Expected Result:
The contact list should show up again after a reload

## Actual Result:
Contact list is not showing up after a reload and only the skeleton is being shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/25e3435b-b4be-44fd-85c4-e2cca5a00822

https://github.com/Expensify/App/assets/93399543/ddbbfb2d-301c-4d41-8cd1-9b36d40f5c46

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690275713777569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by situchan** [comment] 2023-07-25 11:22
Dupe of https://github.com/Expensify/App/issues/22508

**Comment by Nathan-Mulugeta** [comment] 2023-07-25 11:43
How are those two issues the same?

**Comment by situchan** [comment] 2023-07-25 11:45
> How are those two issues the same?

Please check proposals on that issue. All these pages are using `shouldShowOptions={didScreenTransitionEnd` in `OptionsSelector`

**Comment by situchan** [comment] 2023-07-25 13:58
> I'm unable to reproduce neither this issue or the dupe one you linked @situchan. Do you have any clues on why it might not be reproducible by everyone?

Same to you. I am not able to reproduce both issues on staging/production but only dev. I also pointed dev to staging version and still able to reproduce. It's strange that they have inconsistent reproducibility between same codebase.

**Comment by youssef-lr** [comment] 2023-07-25 18:40
Unable to reproduce this on any environment. Closing!

**Closed by youssef-lr** 2023-07-25 18:40 UTC
Labels: DeployBlockerCash, Engineering, Hourly
