### ISSUE TITLE
[$1000] Can do an emoji reaction twice.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19635] opened 2023-05-25 22:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to account A on your first device.
2. Go to Settings -> Preferences -> Enable force offline
3. Login to account A on your second device.
4. On second device, go to a message and react to it with a thumbs up.
5. On first device (offline), go to the same message and react to it with a thumbs up.

## Expected Result: 
Thumbs up count should be 1.
## Actual Result: 
Thumbs up count is 2.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/803d4fb4-efc5-43f3-9a9f-65948406e34a

https://github.com/Expensify/App/assets/43996225/444e31a4-12c9-4763-895c-eda435652a87

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rushatgabhane 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684890055115509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e665bd7d655044ed</li>
        <li>Upwork Job ID: 1662166250333257728</li>
        <li>Last Price Increase: 2023-07-10</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2023-05-26 18:24
Reviewing this now.

**Comment by isabelastisser** [comment] 2023-05-26 18:35
I can reproduce this!

**Comment by AyoubMoujane** [comment] 2023-05-26 22:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

One user has two clients of the app, if he goes offline on one app, reacts to a comment in the online app, reacts to the same comment on the offline app then comes back online. He'll see two reactions on the comment

Reacting twice with the same emoji to a same comment should not be possible.

### What is the root cause of that problem?

When you add a reaction offline it pushes the `AddEmojiReaction` command in the queue (because the app doesn't know there's already a reaction on the comment), when connection resumes the queued command is called on the API. And we end up with duplicate reactions like so

![Screenshot 2023-05-26 at 23 57 22](https://github.com/Expensify/App/assets/50808670/6c18487e-402d-4b0b-b334-42c20ca54a85)

If the app was online the created action would have been `RemoveEmojiReaction` but since the app is offline it has no way of knowing that there is already a reaction on the command

### What changes do you think we should make in order to solve the problem?

I would make the app more resilient to this case by filtering the reactions according to `accountID` (removing duplicates) in this [line](https://github.com/Expensify/App/blob/a6e6fe9252af0d3cc19966abaf550e5eba5a466c/src/components/Reactions/ReportActionItemReactions.js#LL59C17-L59C17)

The fix works well locally and make sense because duplicate reaction should never exist

### What alternative solutions did you explore? (Optional)

Find a way to not fire the command when there's already a reaction but I feel like this solution would be too complex

**Comment by AyoubMoujane** [comment] 2023-05-26 23:02
Agreed 100% but that would mean that after going online and during the dequeuing of the command queue, we would need to be able to compare the current state of the report to know if the command called on the API or not. Do we have a way to do that ? That's the alternative solution I talked about but seem rather complex to implement.

If not the duplicate filtering proposal is a good fix to the bug IMO, when the user will click again on the react emoji, the  `RemoveEmojiReaction` command will be triggered and delete both reaction (the original & the duplicate) which takes us back to a clean state.

**Comment by MonilBhavsar** [comment] 2023-05-29 10:34
AFAIK, we have a validation in backend to prevent duplicate reactions. I think the root cause lies on server side and should be fixed from there

**Comment by isabelastisser** [comment] 2023-05-31 16:29
Bump @MonilBhavsar on the comment above. Let's please choose a proposal and move forward with this soon; thanks!

**Comment by isabelastisser** [comment] 2023-06-02 20:26
bump @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2023-06-05 04:51
Sorry, we're doing a refactor of how emoji works and this should be on HOLD for https://github.com/Expensify/Expensify/issues/281934.
Putting it on HOLD and bumping to weekly!

**Comment by MonilBhavsar** [comment] 2023-06-14 05:02
Sorry, because it is in an internal repo.
Btw, this is still on HOLD

**Comment by isabelastisser** [comment] 2023-06-22 20:35
Not overdue, still on hold!

**Comment by MonilBhavsar** [comment] 2023-07-03 13:10
This is off HOLD now. Not able to reproduce this issue now. Can anyone please also confirm. We can close it then cc @isabelastisser @aimane-chnaif Thanks!

**Comment by isabelastisser** [comment] 2023-07-05 20:35
Hey @MonilBhavsar, to confirm, can I process the payment to the issue reporter `Issue reported by: @rushatgabhane` and close this one then?

**Comment by MonilBhavsar** [comment] 2023-07-06 10:44
Let's please confirm the issue is not reproducible anymore, in case I am missing something.
I left a comment in the slack thread https://expensify.slack.com/archives/C049HHMV9SM/p1688640164461249?thread_ts=1684890055.115509&cid=C049HHMV9SM

If not reproducible, yes, we can pay to Rushat and close this issue

**Comment by rushatgabhane** [comment] 2023-07-13 04:25
issue is not reproducible, thanks!

**Comment by MonilBhavsar** [comment] 2023-07-13 05:54
Thanks for the updated!

**Closed by MonilBhavsar** 2023-07-13 05:54 UTC
Labels: External, Weekly, Help Wanted, Bug
