### ISSUE TITLE
[HOLD for payment 2023-11-30] [$500] IOU-Description is shown in preview in manual request while receipt is uploading.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31104] opened 2023-11-09 09:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money--- Manual
4. Enter an amount and tap next
5. Select a user
6. Tap on 3 dots and "add receipt"
7. Enter description
8. Tap request amount
9. Tap on IOU

## Expected Result:
In IOU report, the description must not be shown in preview while receipt is uploading.

## Actual Result:
In IOU report, the description is shown in preview in manual request while receipt is uploading.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/e0d51111-c360-4129-8c39-230ab22add88

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0136e412ae57e89702</li>
        <li>Upwork Job ID: 1722554040572862464</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27670888</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-09 10:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOU-Description is shown in preview in manual request while receipt is uploading

### What is the root cause of that problem?
This is the currently logic
```
    const shouldShowDescription = !_.isEmpty(description) && !shouldShowMerchant;
```

we don't have logic to check if receipt is canning 
### What changes do you think we should make in order to solve the problem?

Should add a logic to check if receipt is canning we will hide description
### What alternative solutions did you explore? (Optional)

**Comment by MitchExpensify** [comment] 2023-11-14 20:54
Are we good to assign @DylanDylann , @marcochavezf ?

**Comment by marcochavezf** [comment] 2023-11-14 21:27
Yup, thanks for the review @allroundexperts, the solution lgtm as well, assigning @DylanDylann 🚀

**Comment by DylanDylann** [comment] 2023-11-15 11:16
@allroundexperts PR https://github.com/Expensify/App/pull/31348 is ready to review

**Comment by MitchExpensify** [comment] 2023-11-23 19:44
**Payment summary:**

$500 - @allroundexperts, C+, NewDot
$500 - @DylanDylann, C,  Upwork

**Comment by allroundexperts** [comment] 2023-11-26 21:46
## Checklist
1. https://github.com/Expensify/App/pull/26603
2. https://github.com/Expensify/App/pull/26603/files#r1405482536
3. N/A
4. Regression test would be helpful. The steps given in the OP look good enough to me!

**Comment by MitchExpensify** [comment] 2023-12-04 21:00
Paid and contract ended, @DylanDylann 

Added request for new test here: https://github.com/Expensify/Expensify/issues/343038

Closing as payment for @allroundexperts will occur on NewDot 

Thanks every one!

**Closed by MitchExpensify** 2023-12-04 21:00 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-13 20:44
$500 payment approved for @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/31104#issuecomment-1824854255).
