### ISSUE TITLE
Reimbursable - After reload on changing unit when you click outside the it goes back to the previous value reported by @puneet-here

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11698] opened 2022-10-10 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Go to settings > Workspace > Reimburse expenses
3. Reload the page and change unit > now click outside to remove the focus

## Expected Result:
The value shouldn't change

## Actual Result:
The value changes

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.12.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/194879414-b16eb638-7eaa-4e8a-9b6d-c2fa7a799d25.mp4
https://user-images.githubusercontent.com/93399543/194879416-d36ffbce-3cbe-4f20-846c-dcc806006da5.mp4

https://user-images.githubusercontent.com/43996225/194890807-196e23df-a6fc-4494-9bb8-7396707d00d6.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Puneet-here and Applause internal team

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665263408333949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-10-17 12:48
This might be related to this [PR](https://github.com/Expensify/App/pull/10557)

**Comment by danieldoglas** [comment] 2022-10-17 12:54
@kbecciv actually I was not able to simulate this again. Can you please try it again?

**Comment by kbecciv** [comment] 2022-10-17 14:23
@danieldoglas  Checking, updating you shortly

**Comment by kbecciv** [comment] 2022-10-17 14:25
Unable to reproduce it with build 1.2.16.4

https://user-images.githubusercontent.com/93399543/196203117-12acf827-758c-4eb2-9ba9-1d64adeec647.mp4

**Comment by danieldoglas** [comment] 2022-10-20 13:18
Moving this to weekly but looks like we can't reproduce it anymore.

**Comment by danieldoglas** [comment] 2022-10-31 07:53
@kbecciv is this still not reproducible?

**Comment by kbecciv** [comment] 2022-10-31 13:32
@danieldoglas Checking, update you shortly.

**Comment by kbecciv** [comment] 2022-10-31 13:37
Unable to reproduce it with build 1.2.21.4

https://user-images.githubusercontent.com/93399543/199020887-0ef9bfe3-a24a-49dc-8ebc-eb82dca9dde3.mp4

**Comment by danieldoglas** [comment] 2022-10-31 14:02
Ok, closing this issues since it was not reproducible for 2 weeks.

**Closed by danieldoglas** 2022-10-31 14:02 UTC
Labels: Engineering, Weekly, Bug
