### ISSUE TITLE
[$1000] Chat is inserting empty lines when pasting a large text copied from any website that generates big text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23670] opened 2023-07-26 17:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Copy a bug text from https://www.fancytextpro.com/BigTextGenerator
2- paste the text in the chat and hit enter
3- empty lines are added to the text
## Expected Result:
 the pasted text should remain in the same format
## Actual Result: 
empty lines are added to the text

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[bigtext.webm](https://github.com/Expensify/App/assets/43996225/a0f5383f-65ef-4e58-b598-70cfe4da9219)

https://github.com/Expensify/App/assets/43996225/4bdd183b-7d2c-4666-a9a3-bc0bafb55162

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hichamcc
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690294867467309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01896a724274d065f2</li>
        <li>Upwork Job ID: 1685700440103550976</li>
        <li>Last Price Increase: 2023-08-06</li>
    </ul>
</details>

**Comment by blizxd** [comment] 2023-07-30 18:09
Is the issue already fixed?

**Comment by blizxd** [comment] 2023-07-30 18:23
Contributor details
Your Expensify account email: <nikita.mi777@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~012cc10ba78b95dab6>

**Comment by blizxd** [comment] 2023-07-30 18:25
Contributor details
Your Expensify account email: nikita.mi777@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012cc10ba78b95dab6

**Comment by MayankVir** [comment] 2023-07-31 12:02
@kavimuru Hey, I am unable to reproduce it on staging

**Comment by hichamcc** [comment] 2023-07-31 12:05
Contributor details
Your Expensify account email: owenhicham@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/hichamg9

**Comment by MayankVir** [comment] 2023-07-31 12:06
Contributor details
Your Expensify account email: virmanimayank15@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0155c699362e3388b9

**Comment by kavimuru** [comment] 2023-07-31 12:15
@MayankVir Did you try with the text used in the bug report?

**Comment by MayankVir** [comment] 2023-07-31 12:28
Yes @kavimuru  tried with same. Here is the screen recording for staging.


https://github.com/Expensify/App/assets/41983025/3dd2e670-4dda-4156-83e4-d6ccd7665f2c

**Comment by mollfpr** [comment] 2023-07-31 12:53
I also couldn't reproduce it in staging.

**Comment by MayankVir** [comment] 2023-07-31 12:54
But the screen recording is of the staging environment only.

**Comment by annscode** [comment] 2023-07-31 13:26
Contributor details
Your Expensify account email: anesxbox007@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c8c523f07ca9b1da

**Comment by johncschuster** [comment] 2023-08-01 22:33
@sakluger continues to experience this.

**Comment by mollfpr** [comment] 2023-08-05 07:56
Can't reproduce it on staging `v1.3.50-2`.


https://github.com/Expensify/App/assets/25520267/4977ee35-e756-4c15-b8e8-6f2f6379f281

**Comment by johncschuster** [comment] 2023-08-07 21:24
I've asked @hichamcc to re-test the behavior to see if they can reproduce it.

**Comment by johncschuster** [comment] 2023-08-08 21:17
Ok, I checked with Sasha as well, and it sounds like this behavior has been fixed. Closing!

**Closed by johncschuster** 2023-08-08 21:17 UTC
Labels: External, Daily, Help Wanted, Bug
