### ISSUE TITLE
[$500] Web - Troubleshoot - Troubleshoot RHP does not open smoothly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36576] opened 2024-02-15 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Profile settings.
3. Go to About.
4. Go to Troubleshoot.

## Expected Result:
Troubleshoot RHP will open smoothly.

## Actual Result:
Troubleshoot RHP does not open smoothly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/86fac6dc-4ec9-41cc-8ff2-633ecf8b3836

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ad8eba175f66ec3</li>
        <li>Upwork Job ID: 1758114410676678656</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-15 13:02
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by Beamanator** [comment] 2024-02-15 14:52
Can reproduce on web 👍  but i don't think this should be a blocker

**Comment by amyevans** [comment] 2024-02-15 15:50
>Can reproduce on web 👍 but i don't think this should be a blocker

+1 to Alex's assessment

Looks like the Troubleshoot menu was added in this PR: https://github.com/Expensify/App/pull/35306. @TMisiukiewicz do you plan on tackling polish/clean up issues related to the feature? Let me know and I can assign you! Thanks!

**Comment by TMisiukiewicz** [comment] 2024-02-15 15:58
@amyevans we are having a discussion about moving this page to full card [here](https://github.com/Expensify/App/issues/34082#issuecomment-1946080892), I think we can wait until we establish the proper implementation because if we change it, this ticket may become obsolete

**Comment by marcaaron** [comment] 2024-02-16 01:12
Seems like a possible dupe of https://github.com/Expensify/App/issues/36645

**Comment by techievivek** [comment] 2024-02-16 10:34
Yes, we will be improving that as part of the original GH https://github.com/Expensify/App/issues/34082

**Comment by amyevans** [comment] 2024-02-16 15:44
Okay great, thanks for confirming. I'll close this one out.

**Closed by amyevans** 2024-02-16 15:44 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
