### ISSUE TITLE
[PAY 7/9] [$250] Expense - Unable to click Mark as cash button in expense report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47580] opened 2024-08-16 18:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4865202
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)

3. Go to workspace chat.
4. Submit two same scan receipts that will match with card transaction.
5. Go to expense report after the scanning for both expenses is complete.
6. Click on Mark as cash button in expense report (not transaction thread).

## Expected Result:
User should be able to click on Mark as cash button in the expense report.

## Actual Result:
Nothing happens when clicking on Mark as cash button in the expense report.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

![Bug6573957_1723828838914!w_36c28f96b13346496d0a81b0a7119fb3c11ca8af-2024-08-16_17_12_29 294](https://github.com/user-attachments/assets/37a8bab0-1514-494f-ae0d-f21f93217f6c)

https://github.com/user-attachments/assets/f1156703-089a-4c67-88a7-85f7d5c0da07

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e2e93352cb1e755</li>
        <li>Upwork Job ID: 1825845317524560506</li>
        <li>Last Price Increase: 2024-08-20</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Reviewer | 103636257</li>
<li>nkdengineer | Contributor | 103636259</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by IuliiaHerets** [comment] 2024-08-16 18:17
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment] 2024-08-16 18:18
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-08-16 19:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to click Mark as cash button in expense report

### What is the root cause of that problem?
We are early retuning in markAsCash if `requestParentReportAction` doesn't exist 
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/components/MoneyReportHeader.tsx#L183-L186
### What changes do you think we should make in order to solve the problem?

If we are early retuning in markAsCash if `requestParentReportAction` doesn't exist then we shouldn't also display the mark as cash button (or disable it)
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/components/MoneyReportHeader.tsx#L321-L322
```
    const canMarkAsCash = allHavePendingRTERViolation && !!requestParentReportAction

```
and replace all `allHavePendingRTERViolation` instances with canMarkAsCash as `allHavePendingRTERViolation` is now being used to identify if the button is displayed in MoneyReportHeader.
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-08-19 05:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Nothing happens when clicking on Mark as cash button in the expense report.

### What is the root cause of that problem?
We do nothing if `requestParentReportAction` doesn't exist

https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyReportHeader.tsx#L184-L186

and it only exists when the report is the combined report
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyReportHeader.tsx#L67-L69
### What changes do you think we should make in order to solve the problem?
We should not show the mask as cash button if the report is not the combine report.

As the way we should this button in `MoneyRequestHeader` [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyRequestHeader.tsx#L64), we should update `allHavePendingRTERViolation` condition here to only check the `transaction` [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyReportHeader.tsx#L76-L80) has pending RTER pending violation or not since this is the transaction of combine report and only exists if the report is the combine report. 

```
const allHavePendingRTERViolation = TransactionUtils.allHavePendingRTERViolation([transaction?.transactionID ?? '-1']);
```

OPTIONAL: we can replace `allHavePendingRTERViolation` with `hasAllPendingRTERViolations`
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyReportHeader.tsx#L110

With this, we also reduce the violation of all transactions that aren't necessary since we only want to display this in the combine report
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-08-21 16:03
@mkhutornyi I think we should only pass the `transaction` that is the transaction of the combine report to `allHavePendingRTERViolation`. Let's imagine a case in which we have many transactions in the expense report, `allHavePendingRTERViolation` will be called with many transactions if we do this solution. It can take many times and it's unnecessary because in this case we don't need to do that.

**Comment by nkdengineer** [comment] 2024-08-22 07:09
> @nkdengineer ok, so your proposed solution is more like optimization beyond the scope of this issue, isn't it?

@mkhutornyi It's not beyond the scope of this issue, it's the simplest solution and optimization. It is also consistent with the way we show the mark as cash button in `MoneyRequestHeader` [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/components/MoneyRequestHeader.tsx#L64)

**Comment by trjExpensify** [comment] 2024-09-02 23:19
@bfitzexpensify just noting this is a #wave-control feature, so moving it over to that project. 

(It also hit prod 3 days btw).

**Comment by bfitzexpensify** [comment] 2024-09-06 15:25
Payments complete. Closing this out.

**Closed by bfitzexpensify** 2024-09-06 15:25 UTC
Labels: Reviewing, External, Weekly, Bug
