### ISSUE TITLE
[HOLD for Payment: 2023-12-21 ] [$500] Web - App displays empty value when sending 3 backtick code block in single backtick code block

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26966] opened 2023-09-07 14:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send text in following format : `(```Test```)`
4. Observe that it displays empty value for some time after sending the message
5. Again edit the message and change the format back to: `(```Test```)`
6. Save and observe that now it does not display the text until we revisit the report

## Expected Result:
App should display the message as it is after sending and after editing

## Actual Result:
App displays empty message on sending the message in specific format for some time and using same format in edit displays empty text until report is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/bbe50ef8-824b-469b-929a-fe924c3f4515

https://github.com/Expensify/App/assets/93399543/52026ebe-be9f-466f-987b-0d86c118dd41

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693741353234359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fc0553d7b989f1b</li>
        <li>Upwork Job ID: 1704043272417964032</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>akamefi202 | Contributor | 27749619</li>
</ul></li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-09-11 10:30
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment] 2023-09-13 20:29
unable to repro - @dhanashree-sawant @kbecciv can you confirm

**Comment by dhanashree-sawant** [comment] 2023-09-14 05:44
Able to reproduce on v1.3.69-1 staging, let me know the text you are using, I can help to understand what could be missing or different

https://github.com/Expensify/App/assets/87513216/877f9b30-bfa0-481d-b05f-a124a28b9985

**Comment by dylanexpensify** [comment] 2023-09-19 08:02
Confirmed!

**Comment by agilejune** [comment] 2023-09-19 09:20
`(
```
test
```
)`

**Comment by dylanexpensify** [comment] 2023-09-21 10:04
no proposals yet!

**Comment by dylanexpensify** [comment] 2023-09-25 10:45
same as above

**Comment by dylanexpensify** [comment] 2023-09-27 11:06
no proposals

**Comment by dylanexpensify** [comment] 2023-10-03 17:43
@dhanashree-sawant can you still repro?

**Comment by dhanashree-sawant** [comment] 2023-10-05 06:10
Yes still reproducible.

**Comment by dylanexpensify** [comment] 2023-10-09 14:06
assigning internal

**Comment by akamefi202** [comment] 2023-10-09 14:22
@ArekChr Could you please let me know your opinion on my proposal?
https://github.com/Expensify/App/issues/26966#issuecomment-1745686470

**Comment by ArekChr** [comment] 2023-10-10 11:40
Sorry for delay, working on other urgent issues, I will review tomorrow.

**Comment by dylanexpensify** [comment] 2023-10-10 18:45
Thanks for update @ArekChr!

**Comment by MonilBhavsar** [comment] 2023-10-13 12:46
Waiting for reviews or proposals

**Comment by ArekChr** [comment] 2023-10-16 09:28
I'm okay with changing the code formatting to match how it is on Slack. This regex will transform the message from this code block:

<img width="134" alt="Zrzut ekranu 2023-10-16 o 11 21 43" src="https://github.com/Expensify/App/assets/24796318/3da0c4e7-70c8-4249-a3e6-47d52f9c3998">

To this:
<img width="78" alt="Zrzut ekranu 2023-10-16 o 11 21 05" src="https://github.com/Expensify/App/assets/24796318/6ca261bb-4b40-423e-b83a-8c965b72e30f">

However, I'm not the best in regex, so we must ensure it doesn't inadvertently break anything else.

**Comment by akamefi202** [comment] 2023-10-16 09:38
@ArekChr Yeah. That's what I meant too. I confirmed that it doesn't cause regression by jest testing.

**Comment by ArekChr** [comment] 2023-10-16 09:45
@akamefi202 jest tests would be needed, for cases of the current problem and similar cases as well

**Comment by agilejune** [comment] 2023-10-16 11:27
@cead22 @ArekChr 
I think it's not expected result, rather slack has other output
![image](https://github.com/Expensify/App/assets/86615752/1a9120c6-0350-4e43-a978-bd2e573f1861)
I am wondering how @akamefi202 gets the result of his proposal on Slack.

CodeBlock markdown parser's behavior is discussed thoroughly here(https://expensify.slack.com/archives/C01GTK53T8Q/p1694011229493309) but looks like still not confirmed.

**Comment by dylanexpensify** [comment] 2023-10-18 08:24
@ArekChr thoughts?

**Comment by MonilBhavsar** [comment] 2023-10-23 13:51
I might be missing something. But I am not able to see the empty message as described in the issue steps


https://github.com/Expensify/App/assets/32012005/60835745-1800-46d2-a622-8512e18dd576

**Comment by MonilBhavsar** [comment] 2023-10-27 10:05
Need to clarify on actual and expected behavior here

**Comment by dylanexpensify** [comment] 2023-10-30 09:52
@MonilBhavsar your vid doesn't have the ` before and after the (```Test```), try it that way (I had the same prob haha)

**Comment by MonilBhavsar** [comment] 2023-11-02 12:56
Thanks Dylan! I am able to reproduce now. I was missing the tick.
Slack and github has different outputs and aligns with how they work.
Slack parses markdown as we type, so it is on first in first out kind of basis.
And github parses everything after typed(like ours currently), so it parses everything as code block inside outer single ticks. I think we should do similar.

**Comment by dylanexpensify** [comment] 2023-11-06 10:55
agree @MonilBhavsar! Let's get this fixed!

**Comment by MonilBhavsar** [comment] 2023-11-06 11:18
Sounds good 👍 
To clarify again - Since we do not support live formatting now and message is formatted once we submit the message after writing or editing markdown, we'll parse the message with the most outer markdown. In this case - a backtick or code "`".
Similar to how github works. I feel this will help us to simplify the use case and get rid of unnecessary nested markdown issues.


https://github.com/Expensify/App/assets/32012005/213c5dc9-287d-433d-bca2-676b3c0bfe5f

**Comment by MonilBhavsar** [comment] 2023-11-06 11:20
@ArekChr is already C+ here. Not sure why it did assign a new C+ here. Adjusting it

**Comment by MonilBhavsar** [comment] 2023-11-06 11:21
@akamefi202 if you would like to submit updated proposal based on the expected outcome https://github.com/Expensify/App/issues/26966#issuecomment-1794598022

**Comment by ArekChr** [comment] 2023-11-06 11:29
> @ArekChr is already C+ here. Not sure why it did assign a new C+ here. Adjusting it

@MonilBhavsar I was taken off the C+ team while I was on holiday. I'm back now, and I'm catching up on everything that I missed.

**Comment by MonilBhavsar** [comment] 2023-11-06 12:15
Ah I see, that makes sense 👍 
Thank you!

**Comment by akamefi202** [comment] 2023-11-06 18:28
@MonilBhavsar 
Github has a huge difference in parsing backticks.
Only triple backticks with linebreak is translated into code block in Github parsing(`<pre>`).
Triple backticks without linebreak is still translated into inline code(`<code>`).

https://github.com/Expensify/App/assets/53784473/3c6d8fe8-21c4-4ef1-952b-435df1d0ea28

As a result, "\`(\`\`\`test\`\`\`)\`" text isn't supposed to include `<pre>` tag in Github.
It is only regarded as an inline code(`<code>`) and that's why it looks like that it parses everything as code block inside outer single ticks.
So I still think that https://github.com/Expensify/App/issues/26966#issuecomment-1764079303 is the correct expression.

**Comment by dylanexpensify** [comment] 2023-11-07 10:01
Hmm, @MonilBhavsar for thoughts

**Comment by MonilBhavsar** [comment] 2023-11-07 10:21
I see. So this is how it looks for me in slack. It formats as I type the message "`(```Test```)`"

<img width="397" alt="Screenshot 2023-11-07 at 3 49 03 PM" src="https://github.com/Expensify/App/assets/32012005/df553328-cf15-4066-ae80-d218b391a0c9">

And it looks different from the comment you have linked

**Comment by akamefi202** [comment] 2023-11-07 10:33
@MonilBhavsar As you told, it's because of live formatting.
But if we copy the message "\`(\`\`\`test\`\`\`)\`" in Slack instead of typing, we can see the same formatting with https://github.com/Expensify/App/issues/26966#issuecomment-1764079303.

https://github.com/Expensify/App/assets/53784473/16d428b4-d5fa-4876-82d2-dd2c5c500a5a

**Comment by MonilBhavsar** [comment] 2023-11-07 10:36
It doesn't format at all If I paste it in slack 🤔 
 
https://github.com/Expensify/App/assets/32012005/5a17cc6c-218f-484b-9a17-6e448bc8dbcc

**Comment by akamefi202** [comment] 2023-11-07 11:00
@MonilBhavsar You can also apply formatting in Slack by pressing Ctrl/CMD + Shift + F.

**Comment by MonilBhavsar** [comment] 2023-11-09 20:30
Ok thanks! It worked and we can go ahead with that
@dylanexpensify does this formatting look good?

<img width="323" alt="Screenshot 2023-11-10 at 1 58 53 AM" src="https://github.com/Expensify/App/assets/32012005/244d1bc7-a6ba-4cca-ac3b-ce77ef37e1de">

**Comment by dylanexpensify** [comment] 2023-11-14 10:05
yes @MonilBhavsar! Let's move forward

**Comment by akamefi202** [comment] 2023-11-14 10:17
@dylanexpensify @MonilBhavsar If you all agree, could you please approve my proposal?
https://github.com/Expensify/App/issues/26966#issuecomment-1745686470

**Comment by akamefi202** [comment] 2023-11-20 12:09
Thanks. I will make sure it.

**Comment by akamefi202** [comment] 2023-11-21 11:12
I created a PR in `expensify-common` repo. Please review it.

**Comment by dylanexpensify** [comment] 2023-11-22 09:27
bump @ArekChr ^

**Comment by akamefi202** [comment] 2023-11-22 13:26
@MonilBhavsar Could you please review soon if you have any time for it?

**Comment by MonilBhavsar** [comment] 2023-11-22 13:32
Done!

**Comment by ArekChr** [comment] 2023-11-28 09:08
Sorry for delay, I will take a look @MonilBhavsar

**Comment by dylanexpensify** [comment] 2023-12-05 20:10
Any update @ArekChr

**Comment by ArekChr** [comment] 2023-12-06 09:43
Hi @dylanexpensify, the PR is still undergoing review. We are actively discussing and testing the proposed solution.

**Comment by dylanexpensify** [comment] 2023-12-11 07:59
@ArekChr mind giving us a rough ETA on this one? TY! 🙇‍♂️

**Comment by akamefi202** [comment] 2023-12-11 08:05
@dylanexpensify @ArekChr 
https://github.com/Expensify/App/pull/32639
PR merge is paused because of license/snyk test. Could you please let me know what I can do to fix this?

**Comment by akamefi202** [comment] 2023-12-12 13:08
https://github.com/Expensify/App/pull/32639
@dylanexpensify @ArekChr @MonilBhavsar PR is merged finally.

**Comment by akamefi202** [comment] 2023-12-16 14:02
@ArekChr @MonilBhavsar Could you please update status of this issue to hold?

**Comment by dylanexpensify** [comment] 2023-12-20 09:26
tomorrow!

**Comment by dylanexpensify** [comment] 2023-12-21 12:33
Payment summary:
- Contributor: @akamefi202 $500
- Contributor+: @ArekChr 

Payment sent!

**Comment by dylanexpensify** [comment] 2023-12-22 11:31
@dhanashree-sawant please [apply here](https://www.upwork.com/jobs/~0141747d3e27f017b9)!

**Comment by dhanashree-sawant** [comment] 2023-12-28 08:51
Thanks @dylanexpensify, I have applied to the job.

**Comment by dylanexpensify** [comment] 2024-01-08 09:13
offer sent @dhanashree-sawant !

**Comment by dylanexpensify** [comment] 2024-01-08 09:52
done!

**Closed by dylanexpensify** 2024-01-08 09:52 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
