### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500][Simplified Collect][Categories] CreateWorkspaceCategoriesPage: full page implementation, onyx action

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#35710] opened 2024-02-02 19:47 UTC
Implement `CreateWorkspaceCategoriesPage: full page implementation, onyx action` from the [Simplified Collect: Profile, Members, Categories design doc](https://docs.google.com/document/d/1gk3xqOs7epMbUrSSiX8K7YcqfPLVgqEos0sf-D-GMDA/edit)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ba488440a2f9a1b8</li>
        <li>Upwork Job ID: 1755659204123680768</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2024-02-02 19:48
@ArekChr can you please comment here so I can assign you to the issue?

**Comment by ArekChr** [comment] 2024-02-05 08:15
Sure, please assign me @luacmartins

**Comment by greg-schroeder** [comment] 2024-02-12 21:42
@ArekChr is there a PR for this one we can link to?

**Comment by greg-schroeder** [comment] 2024-02-12 21:43
Go away melvin

**Comment by ArekChr** [comment] 2024-02-13 08:56
Hi @greg-schroeder this issue is blocked by https://github.com/Expensify/App/issues/35705, need to finish categories page first

**Comment by greg-schroeder** [comment] 2024-02-13 09:27
Thanks, updated

**Comment by greg-schroeder** [comment] 2024-02-22 06:55
Held

**Comment by trjExpensify** [comment] 2024-02-23 18:33
Removing the holds.

**Comment by luacmartins** [comment] 2024-03-01 18:49
@ArekChr is still working through the other implementation issues.

**Comment by luacmartins** [comment] 2024-03-04 23:35
I'll start working on this one

**Comment by mananjadhav** [comment] 2024-03-13 18:04
@greg-schroeder This will be ready for payout tomorrow.  Could you update the payout summary when this is ready for payout?

Because this is a new feature there's no offending PR. But I think it makes sense we add a regression test with the Test steps from the PR.

**Comment by greg-schroeder** [comment] 2024-03-14 00:03
Yup @mananjadhav you can make a manual request for $500 for the reviewer role

**Comment by greg-schroeder** [comment] 2024-03-14 00:05
Filed regression test issue. I'm going to close this as there's no payment actually due from me, and you can make a manual request and review the comment above

**Closed by greg-schroeder** 2024-03-14 00:05 UTC
Labels: External, Engineering, Weekly, NewFeature, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-03-18 15:11
$500 approved for @mananjadhav based on [this comment](https://github.com/Expensify/App/issues/35710#issuecomment-1996154425).
