### ISSUE TITLE
[$500] Admins channel showing categories audit log in LHP, but not in the main room

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33497] opened 2023-12-22 15:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @conorpendergrast 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703156545464319

## Action Performed:
1. Sign in to www.Expensify.com and create a new Control plan workspace
2. Connect that workspace to NetSuite, with auto-sync enabled
3. Trigger the auto-sync bedrock job, or wait for that to run automatically
4. Go to New Expensify, and observe that for this workspace, the left-hand panel #admins channel room preview says "[email@domain.com](mailto:email@domain.com) updated categories via netsuite" (incorrectly)
5. Observe that this does not appear in the #admins itself (correctly)

## Expected Result:
As those actions (which happen via the the NetSuite integration) should be filtered out, the channel's preview should not show the "[email@domain.com](mailto:email@domain.com) updated categories via netsuite"

## Actual Result:
The channel's preview showed the "[email@domain.com](mailto:email@domain.com) updated categories via netsuite"

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (17)](https://github.com/Expensify/App/assets/38435837/791821c0-e30e-4512-9363-5885a5f980c6)

![Snip - (51) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/e6d79c52-f5e3-4da0-8cda-14f8af1541b6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2947a8e5e27ea6a</li>
        <li>Upwork Job ID: 1738222517774311424</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by adriancova** [comment] 2023-12-22 17:57
Without a NetSuite test account I don't think this one is possible to replicate, any chance you could share some expensify test credentials where an integration to netsuite has already been done or maybe just the report that was generated?

Or if it's ok with you, (and again without having been able to reproduce the issue) I could draft a proposal for a new check inside shouldReportActionBeVisibleAsLastAction called isNetSuiteIntegrationAction that will filter the message by looking at the text content.

**Comment by peterdbarkerUK** [comment] 2023-12-27 11:45
@adriancova I can create a NS connected workspace and add you to it as an admin. What's your testing email?

**Comment by adriancova** [comment] 2023-12-27 16:03
That'd be great, thanks @peterdbarkerUK  it's adriancova.95+1@gmail.com

**Comment by peterdbarkerUK** [comment] 2024-01-02 20:49
I'm sorry @adriancova, I got sick right after this and then with the holidays slipped behind. 

I've created [a workspace connected to NS](https://www.expensify.com/policy?policyID=9F03EBE581D27D45) and added you. Workspace is called Test 33497.

**Comment by peterdbarkerUK** [comment] 2024-01-02 20:55
@conorpendergrast how do you trigger the auto-sync bedrock job? I'm struggling to reproduce this, as it only behaved as described when I made the initial connection

**Comment by mvtglobally** [comment] 2024-01-03 05:54
Issue not reproducible during KI retests. (First week)

**Comment by conorpendergrast** [comment] 2024-01-08 16:26
@peterdbarkerUK ah, it looks like you don't need to wait for Auto Sync at all - you should be able to get the same effect using a manual sync!

**Comment by peterdbarkerUK** [comment] 2024-01-10 10:50
@adriancova were you able to repro?

**Comment by conorpendergrast** [comment] 2024-01-10 10:52
It looks like a fix is in the works via https://github.com/Expensify/Expensify/issues/356789, so we can close this out!

**Closed by conorpendergrast** 2024-01-10 10:52 UTC
Labels: External, Daily, Help Wanted, Bug
