### ISSUE TITLE
Split Bill - Unable to split account and triggers console error: TypeError: Iterable yielded undefined which is not a string

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22883] opened 2023-07-14 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
*First open inspect console
1. Click plus sign
2. Click New group
3. Select three participants, of the new group
4. Click plus sign and select Split bill
5. Type five numbers or more and click the Next button
6. Click Button Split

## Expected Result:
Being able to split the account and not trigger an error in the console

## Actual Result:
Unable to split account and triggers console error: TypeError: Iterable yielded undefined which is not a string

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/68c0cb50-5e93-415b-bfd5-9ca9ff9e4952

https://github.com/Expensify/App/assets/93399543/b269e206-3a1a-4c9a-9ae9-baa16e498775

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Mauri-salazar
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689276542633869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2023-07-14 10:47
dupe of https://github.com/Expensify/App/issues/21268

**Comment by MitchExpensify** [comment] 2023-07-14 20:06
Thanks @gadhiyamanan !

**Closed by MitchExpensify** 2023-07-14 20:06 UTC
Labels: Daily, Bug
