### ISSUE TITLE
Web - Integrations - Import / Export menu disappears after sync / connection for QBO / Xero

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46493] opened 2024-07-30 12:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4784244
**Email or phone of affected tester (no customers):** applausetester+79pronin@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace
3. Go to workspace settings > "More Features" > Enable the "Accounting" toggle
4. Go to Accounting
5. Connect QBO or Xero

## Expected Result:
Import / Export / Advanced menu should be displayed

## Actual Result:
Import / Export / Advanced menu appears for a second and then disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/07026c51-2e1a-4e71-a24a-8bc05931217b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hungvu193** [comment] 2024-07-30 14:07
Dupe of https://github.com/Expensify/App/issues/46445

**Comment by roryabraham** [comment] 2024-07-30 15:01
Closing as dupe

**Closed by roryabraham** 2024-07-30 15:01 UTC
Labels: DeployBlockerCash, Engineering, Hourly, DeployBlocker
