### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Sign in banner stays few seconds after logging in with existing account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36976] opened 2024-02-20 23:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Log out of ND
2. Go to https://staging.new.expensify.com/r/4098419659819887
3. Tap the sign-in button
4. Sign in with an existing account that has a lot of conversations

## Expected Result:
Sign in banner disappears right after login to the account

## Actual Result:
Sign in banner takes few seconds to disappear

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/b29a2655-7ba9-45ef-9356-2dc0159423fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162c20b82939c30bf</li>
        <li>Upwork Job ID: 1761040636334718976</li>
        <li>Last Price Increase: 2024-02-23</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by mallenexpensify** [comment] 2024-02-21 01:39
@CortneyOfstad posted in #vip-vsb https://expensify.slack.com/archives/C066HJM2CAZ/p1708478310286439
> Also reported by QA, this does not seem like one we need to fix, more polish

**Comment by CortneyOfstad** [comment] 2024-02-23 14:50
@Pujan92, there is a proposal from @dukenv0307 [here](https://github.com/Expensify/App/issues/36976#issuecomment-1958570178). Interested to hear your thoughts on this to see if it would work in this situation. Thanks!

**Comment by bernhardoj** [comment] 2024-02-23 15:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sign in footer banner is still shown for a few seconds after login as an anonymous user.

### What is the root cause of that problem?
The sign in banner will be shown when the user is anonymous.
https://github.com/Expensify/App/blob/b80cd5a455804d83c50631adac62c52c1d56201f/src/pages/home/report/ReportFooter.js#L119-L120

The sign in modal is closed before the report footer component receives the latest session data. 

Currently, we close the sign in modal by connecting to session onyx and listen for any change.
https://github.com/Expensify/App/blob/b80cd5a455804d83c50631adac62c52c1d56201f/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L72-L87

The close modal code above is called earlier than the report footer component receiving the latest data. 

Btw, if you notice, the report footer doesn't subscribe to session data
https://github.com/Expensify/App/blob/b80cd5a455804d83c50631adac62c52c1d56201f/src/pages/home/report/ReportFooter.js#L157-L162

which means it depends on other factors (other props) to re-render, but even if we subscribe to it, it still receives the latest data after the modal is closed.

_if I can guess, it's because withOnyx batch the update broadcast_

### What changes do you think we should make in order to solve the problem?

Instead of closing the modal here
https://github.com/Expensify/App/blob/b80cd5a455804d83c50631adac62c52c1d56201f/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L72-L87

we can close it inside SignInModal itself. Currently, we have this code to dismiss the page, but it's only run once because the page is never updated.
https://github.com/Expensify/App/blob/b80cd5a455804d83c50631adac62c52c1d56201f/src/pages/signin/SignInModal.tsx#L11-L21

So, we can subscribe to session data and close the page whenever the user is not an anonymous account.

```
useEffect(() => {
    if (session?.authTokenType !== 'anonymousAccount') {
        // Signing in RHP is only for anonymous users
        Navigation.isNavigationReady().then(() => {
            Navigation.dismissModal();
        });
    }
}, [session])
```

and optionally subscribe to session data in the report footer and use it to detect the user type instead of using `Session.isAnonymousUser()`, just like we did above.

**Comment by situchan** [comment] 2024-02-23 15:54
I remember this was reported before but closed

**Comment by Pujan92** [comment] 2024-02-26 04:23
Thanks for the proposals. I am inclined towards @bernhardoj's RCA and proposal as it seems signIn modal closed early before  `ReportFooter` has the latest data and gets rerendered. It makes sense to close the modal within `SignInModal` instead of the Onyx callback as suggested by them.

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment] 2024-02-26 04:24
> I remember this was reported before but closed

Please link that in case you find it.

**Comment by dangrous** [comment] 2024-02-27 22:01
I just went on parental leave so @CortneyOfstad do you think you can fish for another engineer volunteer in Slack?

**Comment by mallenexpensify** [comment] 2024-02-27 23:46
@Pujan92 , can you please post again with 🎀👀🎀 C+ reviewed to get an engineer auto-assigned?  Thx

**Comment by Pujan92** [comment] 2024-02-28 03:06
🎀👀🎀 C+ reviewed

**Comment by marcochavezf** [comment] 2024-02-29 20:12
Thanks for the review @Pujan92, assigning @bernhardoj 🚀

**Comment by bernhardoj** [comment] 2024-03-01 06:51
PR is ready

cc: @Pujan92

**Comment by CortneyOfstad** [comment] 2024-03-13 16:33
## Payment Summary

@Pujan92 — paid $500 via Upwork
@bernhardoj — paid $500 via Upwork

**Comment by CortneyOfstad** [comment] 2024-03-13 16:33
@Pujan92 — can you have the checklist above completed by EOD? Thanks!

**Comment by CortneyOfstad** [comment] 2024-03-14 15:23
Regression test created here — https://github.com/Expensify/Expensify/issues/378887

Closing as payment and checklist have been completed!

**Closed by CortneyOfstad** 2024-03-14 15:23 UTC
Labels: External, Engineering, Weekly, Bug
