### ISSUE TITLE
[HOLD for payment 2024-03-25] [HOLD 31374,30874] [$500] Room  - Email id searched not found is not displayed in "Invite" page on tapping invite

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34301] opened 2024-01-10 22:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a room chat
3. Tap header---- members
4. In "Find a member" section, enter an email id which is not found
5. Tap invite
6. In "Invite new members" page , note the email id not found in "members" page is not displayed
7. Navigate to KHN
8. Tap profile icon
9. Tap Workspaces ----- Workspace ---- Members
10. In "Find a member" section, enter an email id which is not found
11. Tap invite
12. In "Invite new members" page , note the email id not found in "members" page is displayed

## Expected Result:
In room, members page, email id searched not found must be displayed in "Invite new members" page when tapping "invite" like in Workspace "Invite new members" page

## Actual Result:
In room, members page, email id searched not found is not displayed in "Invite new members" page when tapping "invite" like in Workspace "Invite new members" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c08bc156-4043-4550-a4b3-37ae28c3d219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fabaa72dd4c7bad6</li>
        <li>Upwork Job ID: 1745204029918879744</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment] 2024-01-15 11:37
put on hold

**Comment by dylanexpensify** [comment] 2024-01-23 13:20
holding

**Comment by dylanexpensify** [comment] 2024-01-29 11:55
holding

**Comment by dylanexpensify** [comment] 2024-02-07 10:28
holding

**Comment by dylanexpensify** [comment] 2024-02-13 20:21
same

**Comment by dylanexpensify** [comment] 2024-02-21 10:44
same

**Comment by dylanexpensify** [comment] 2024-02-28 08:57
same

**Comment by dylanexpensify** [comment] 2024-02-28 08:58
same!

**Comment by dylanexpensify** [comment] 2024-03-06 11:01
same

**Comment by dylanexpensify** [comment] 2024-03-13 10:42
Same

**Comment by jjcoffee** [comment] 2024-03-13 10:51
Actually this one can come off hold I think! #31374 is closed and #30874 is held on developing a unified design. Since that's likely to take a while I don't think it makes sense for it to block this issue.

Happy to go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/34301#issuecomment-1886174988) here!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by dylanexpensify** [comment] 2024-03-20 10:56
Payment coming up!

**Comment by jjcoffee** [comment] 2024-03-25 10:27
- The PR that introduced the bug has been identified. Link to the PR: **N/A - this is more of a feature request, I think**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a private room
2. Go to the room > header > member
3. Search for an email that isn't already a member
4. Click on the invite button
5. Verify that the email that we entered in (3) is displayed in the search input of the invite page
6. Invite some users
7. After we go back to the invite page, verify that the search input is cleared

Do we agree 👍 or 👎

**Comment by jjcoffee** [comment] 2024-03-27 10:38
@dylanexpensify Friendly bump for payment :bow:

**Comment by dylanexpensify** [comment] 2024-03-27 11:19
Will pay today! Thanks for the bump, Joel!

Dylan Courtney (He/Him/His)

**Comment by jjcoffee** [comment] 2024-04-08 10:09
@dylanexpensify Friendly bump for payment on this :bow:

**Comment by dylanexpensify** [comment] 2024-04-08 11:00
Payment summary!

- Contributor: @dukenv0307 $500
- Contributor+: @jjcoffee $500

Please apply [here](https://www.upwork.com/jobs/~01a31737517a34d1f4)!!

**Comment by jjcoffee** [comment] 2024-04-08 11:05
@dylanexpensify Many thanks, applied!

**Comment by dylanexpensify** [comment] 2024-04-08 11:06
Offer sent @jjcoffee!!

**Comment by dylanexpensify** [comment] 2024-04-08 11:16
@jjcoffee paidddd! 🤑

**Comment by puneetlath** [comment] 2024-04-17 20:49
@dylanexpensify can we pay this and close it out?

**Comment by dylanexpensify** [comment] 2024-04-23 19:13
Apologies for delay here - done!!

**Closed by dylanexpensify** 2024-04-23 19:13 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
