### ISSUE TITLE
[$500] [LOW] Billable option is not disabled in the paid expense from employee view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33920] opened 2024-01-04 01:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an employee of Collect workspace on Old Dot
- The Collect workspace has "Re-bill expenses to clients" set to "Default to billable"
1. Go to workspace chat as employee
2. Click + > Request money > Manual
3. Create a manual request with billable toggled on
4. Submit the expense
5. As admin, pay the request
6. As employee, navigate to details page and toggle off billable option

## Expected Result:
User should not be able to toggle on or off the billable option when the request is paid

## Actual Result:
User is able to toggle on or off the billable option when the request is paid, which results in an error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/73d5626b-7782-4d35-8109-44dfbbacd891

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cbb306028f0e1261</li>
        <li>Upwork Job ID: 1742713735658586112</li>
        <li>Last Price Increase: 2024-01-25</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2024-01-04 08:06
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
User is able to toggle on or off the billable option when the request is paid, which results in an error
### What is the root cause of that problem?
The root cause is that we don't restrict the editablity of billable in `Switch` depending on report and user here.
https://github.com/Expensify/App/blob/4b9b55e01315ec2d2dd36c7fd0d02256b9a14a37/src/components/ReportActionItem/MoneyRequestView.js#L301

### What changes do you think we should make in order to solve the problem?
We need to add canEditBillable method in ReportUtils.ts and can use in several places for disabling Switch.
And we need to add disabled property to `Switch` component.
```
function canEditBillable(reportAction: OnyxEntry<ReportAction>): boolean {
    const isDeleted = ReportActionsUtils.isDeletedAction(reportAction);

    if (isDeleted) {
        return false;
    }

    // If the report action is not IOU type, return true early
    if (reportAction?.actionName !== CONST.REPORT.ACTIONS.TYPE.IOU) {
        return false;
    }

    const moneyRequestReportID = reportAction?.originalMessage?.IOUReportID ?? 0;

    if (!moneyRequestReportID) {
        return false;
    }

    const moneyRequestReport = getReport(String(moneyRequestReportID));
    const isPolicyExpense = isPolicyExpenseChat(getRootParentReport(isNotEmptyObject(moneyRequestReport) ? moneyRequestReport : null));
    if (!isPolicyExpense) return false;
    const isReportSettled = isSettled(moneyRequestReport?.reportID);
    const isAdmin = isExpenseReport(moneyRequestReport) && (getPolicy(moneyRequestReport?.policyID ?? '')?.role ?? '') === CONST.POLICY.ROLE.ADMIN;

    return !isReportSettled || (isReportSettled && isAdmin);
}
```

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by michaelhaxhiu** [comment] 2024-01-18 21:01
Awaiting update from @0xmiroslav

**Comment by michaelhaxhiu** [comment] 2024-01-23 15:21
@0xmiroslav bump, update please or let's re-assign to a new C+

**Comment by michaelhaxhiu** [comment] 2024-01-23 20:58
Hmm I would think disabled on both sides. But good Q to post in slack channel (and link to this GH) to make sure!!

**Comment by mallenexpensify** [comment] 2024-01-24 03:35
@alitoshmatov reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by alitoshmatov** [comment] 2024-01-24 13:13
> @mallenexpensify I think @aimane-chnaif can take over this as C+ since already started on the other dupe issue

Agreed, if @aimane-chnaif has already spent investigating similar issue, I think it would only be fair to assign him

**Comment by michaelhaxhiu** [comment] 2024-01-25 20:29
Seems we are closing these issues given that we don't have a defined strategy on admin access of draft or open reports.

**Comment by michaelhaxhiu** [comment] 2024-01-25 20:29
re-open if you disagree

**Comment by garrettmknight** [comment] 2024-01-26 18:33
I don't think we've consciously changed strategy from OldDot - so if you can change billable flag on a paid expense in OldDot, you should be able to do the same in NewDot. @michaelhaxhiu can you test and confirm OldDot behavior to confirm before closing?

**Comment by twisterdotcom** [comment] 2024-02-02 17:13
@greg-schroeder gonna put this in Wave 6 for submitters on LOW.

**Comment by alitoshmatov** [comment] 2024-02-02 18:37
I can take a look at this issue tomorrow

**Comment by twisterdotcom** [comment] 2024-02-13 13:40
@alitoshmatov please try to confirm if this can be External this week.

**Comment by alitoshmatov** [comment] 2024-02-21 07:02
Sorry missed this one since it was weekly. @twisterdotcom Yes it can be external.

**Comment by alitoshmatov** [comment] 2024-02-21 07:03
@dukenv0307 The RCA is correct and your solution does solve the issue

@unicorndev-727 Your proposal is also very similar to @dukenv0307 's proposal.

**Comment by alitoshmatov** [comment] 2024-02-21 07:04
We can go with @dukenv0307 's [proposal](https://github.com/Expensify/App/issues/33920#issuecomment-1876175946)
which states that we disabled billable toggle based on `canEdit` condition used on other fields

C+ reviewed 🎀 👀 🎀

**Comment by srikarparsi** [comment] 2024-02-26 09:10
Hey! I'll take a look into this tomorrow

**Comment by twisterdotcom** [comment] 2024-02-28 17:02
How is the PR coming @dukenv0307?

**Comment by alitoshmatov** [comment] 2024-03-01 10:28
@dukenv0307 Can you clarify what is slowing down your PR. 

> @srikarparsi @alitoshmatov When I change billable after the request is paid. BE returns error now.

I think this is expected since you shouldn't be able to change request after it is paid

**Comment by twisterdotcom** [comment] 2024-03-06 12:50
FWIW, I do think a request should be able to have its billable state updated after approval.

**Comment by srikarparsi** [comment] 2024-03-07 08:18
Hm okay, in that case it would be a backend change.

I'm curious though, why should requests be able to have their billable state updated after approval? I thought that billable expenses meant that they need to be re-billed to another vendor. And in that case, I think that the approver might have to know that information before approving it?

For example, if I submit an expense to you and mark it billable and you approve it and then I remove the billable option, then that would mean it's no longer being reimbursed by someone else but instead yourself right? And you might not want that since you initially approved it since it's coming from a different vendor?

I might be mistaken in how billable works though since I'm not too familiar with the feature.

**Comment by twisterdotcom** [comment] 2024-03-07 10:26
It's pretty common for business to choose what they rebill a after they've approved expenses I'm afraid, and the approvers for an expense may not be the same people who issue invoices to clients.

**Comment by srikarparsi** [comment] 2024-03-07 20:48
Ah got it, that makes sense then, thank you! Do you think you could check if there's a wave/vip this would fit into since it needs to be taken internally?

**Comment by twisterdotcom** [comment] 2024-03-08 17:57
This is already in #wave-collect under `Polish`. So we can leave it there for now and make it `Weekly`

**Comment by srikarparsi** [comment] 2024-03-20 04:16
Sounds good, I'll try to get it done towards the end of this week.

**Comment by srikarparsi** [comment] 2024-04-02 01:46
Hey @twisterdotcom, just to clarify, you're saying that both the employee and the approver should be able to modify the billable status of a report right?

**Comment by srikarparsi** [comment] 2024-04-02 01:56
The current behavior is that the approver can change the billable status after the expense is approved, but the employee cannot.

Approver:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/44869291-b201-46d3-bb73-8b3848a2e501">


Employee:
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/48188732/161f3c23-a6c2-4f89-a294-b2af4c3a2ac8">

**Comment by twisterdotcom** [comment] 2024-04-03 12:44
>you're saying that both the employee and the approver should be able to modify the billable status of a report right?

Ah no, just the admin and approver should.

**Comment by srikarparsi** [comment] 2024-04-04 19:37
Ah cool! That's the current behavior in the backend then. @dukenv0307 let's go with your frontend PR then to disabled billable toggle based on canEdit. cc @alitoshmatov

**Comment by twisterdotcom** [comment] 2024-04-29 20:09
It's `Reviewing` Melvin.

**Comment by srikarparsi** [comment] 2024-04-29 20:23
We merged the [PR](https://github.com/Expensify/App/pull/37065) actually, not sure why this didn't close automatically. Closing it out now since it's on production.

**Comment by twisterdotcom** [comment] 2024-04-30 08:27
Okay, who needs paying now?

**Comment by twisterdotcom** [comment] 2024-10-10 15:05
Payment Summary:

- @alitoshmatov paid $500 via Upwork [here](https://www.upwork.com/nx/wm/offer/new/35826559) (C+)
- @dukenv0307 paid $500 via Upwork [here](https://www.upwork.com/nx/wm/offer/new/1030872159) (Contributor)

**Closed by twisterdotcom** 2024-10-10 15:05 UTC
Labels: Reviewing, Monthly, Internal, Bug
