### ISSUE TITLE
[$250] [Search v2.1] Search loads infinitely when search filter has tax rate in A: B name format

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48407] opened 2024-09-02 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Add a tax rate with A: B as name and any rate
4. Go to Search
5. Click Filters
6. Click Tax rate
7. Select the tax rate with A: B name
8. Click Save
9. Click View results

## Expected Result:
Search will not load infinitely

## Actual Result:
Search loads infinitely when search filter has tax rate in A: B name format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/afe07d96-a6b2-491d-854d-1da0549d376a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831467372268005074</li>
        <li>Upwork Job ID: 1831467372268005074</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rushatgabhane</details>

**Comment by bernhardoj** [comment] 2024-09-02 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search loads infinitely when enter tax rate with A: B format.

### What is the root cause of that problem?
When we create a tax rate with the name of A: B, the tax code becomes id_A:_B
<img width="383" alt="image" src="https://github.com/user-attachments/assets/9eda493e-605b-4c14-b3ef-6486d4923a38">

Filtering tax code will filter based on the tax code and because it contains a colon `:`, the parser considered it as an AND operator.
<img width="418" alt="image" src="https://github.com/user-attachments/assets/64d197e6-07d0-4793-889e-5ddd71d88bce">

And the BE will eventually return an error.
<img width="424" alt="image" src="https://github.com/user-attachments/assets/7a9024ca-d004-45b4-86c9-f97733ec4304">

This happens if we filter based on other things too if we include `:` without a space.

### What changes do you think we should make in order to solve the problem?

We need to sanitize the string if it contains `:` just like we did when it contains a space or comma.
https://github.com/Expensify/App/blob/9aca655e04608e32ae84aeb99b8ec1e006f201e8/src/libs/SearchUtils.ts#L411-L416

The sanitation will wrap the keyword with ".

**Comment by VictoriaExpensify** [comment] 2024-09-04 23:01
Agree this is an issue and it should be fixed

**Comment by trjExpensify** [comment] 2024-09-05 12:11
Moving to wave-control, as it's search related. CC: @luacmartins for vis

**Comment by luacmartins** [comment] 2024-09-05 17:06
I think this may be solved once we update the syntax grammar in [this PR](https://github.com/Expensify/App/pull/47789)

**Comment by luacmartins** [comment] 2024-09-06 18:15
This is being solved [here](https://github.com/Expensify/App/pull/48312)

**Comment by VictoriaExpensify** [comment] 2024-09-11 06:15
Closing this out since this has been solved

**Closed by VictoriaExpensify** 2024-09-11 06:15 UTC
Labels: Reviewing, External, Daily, Bug
