### ISSUE TITLE
Create Task - Creating a Task from FAB generates 2 duplicate tasks

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#20493] opened 2023-06-09 02:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the global create menu (FAB) 
2. Select assign task 
3. Fill the required fields and assign another user
4. Navigate to the main conversation with the user

## Expected Result:
Only 1 task should be created in the main conversation. 

## Actual Result:
2 tasks are created in the main conversation. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.26-1

**Reproducible in staging?:** Yes 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image](https://github.com/Expensify/App/assets/44479856/152f8dcf-6e34-4b24-a6ee-859d30a6d80d)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d377dc6a0a0b5435</li>
        <li>Upwork Job ID: 1668243746662768640</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2023-06-09 02:16
When double checking that this issue is reproducible every time, this happened in one of my conversations. 
One task was stuck at the top and there was a weird flickering. It's reproducible in my account so reach out to me if it's needed to access it for debugging.  
https://github.com/Expensify/App/assets/44479856/f7ef0151-9b02-4c3d-b34d-e377f26417d5

**Comment by StevenKKC** [comment] 2023-06-09 09:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Creating a task from FAB generates 2 duplicate tasks in the main conversation.

### What is the root cause of that problem?
When create a task from FAB, will create 2 task report action. One is the created task report action, and another is the assigned task report action.
![Annotation 2023-06-09 050950](https://github.com/Expensify/App/assets/131836113/c007cd99-f107-4926-8e74-37d0d2607051)
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/libs/actions/Task.js#L33-L44

Because there is no logic that does not display the assigned task report action in the `shouldReportActionBeVisible` function, these two task report action will be displayed in the main conversation.
https://github.com/Expensify/App/blob/82ce35f114a01a0f48180632f1f045aeaae7c8b3/src/libs/ReportActionsUtils.js#L286-L314
### What changes do you think we should make in order to solve the problem?

We should don't display the assigned task report action.
Because the assigned task report action does not contain `childStateNum` and `childStatusNum` field, add a utility function as below in `ReportActionUtils.js`.
```
function isAssignedTaskReportAction(reportAction) {
    return reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && _.has(reportAction.originalMessage, 'taskReportID') && !_.has(reportAction, 'childStateNum') && !_.has(reportAction, 'childStatusNum');
}
```

And in `shouldReportActionBeVisible` function, add below codes.
```
    if (isAssignedTaskReportAction(reportAction)) {
        return false;
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-06-12 13:09
This looks like there's an issue with the optimistic data, which lies in the front-end, so I'm adding the `External` label so we can get some eyes on this from our community.

**Comment by thienlnam** [comment] 2023-06-12 16:06
I'm pretty sure this is resolved on main, or may be a regression from this PR https://github.com/Expensify/App/issues/19126

**Comment by jasperhuangg** [comment] 2023-06-12 17:18
@isagoico can you retest to see if this is still reproducible?

**Comment by thienlnam** [comment] 2023-06-12 17:26
We will have to wait until that PR reaches staging to see if it is reproducible there, or someone can test with main locally

**Comment by jasperhuangg** [comment] 2023-06-14 14:49
Can repro consistently locally as well

**Comment by jasperhuangg** [comment] 2023-06-14 15:17
Ok, so this is what happens. I think @hoangzinh's [understanding of the issue](https://github.com/Expensify/App/issues/20493#issuecomment-1587521772) should be correct, but I don't agree with their solution. We should instead modify [this function](https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/libs/ReportActionsUtils.js#L420-L422) as it is incorrectly catching assigned actions as created actions. I can handle this internally.

cc @thienlnam

**Comment by jasperhuangg** [comment] 2023-06-14 16:31
@hoangzinh This change may actually require back-end changes so I'm marking it as internal, just FYI

**Comment by jasperhuangg** [comment] 2023-06-14 17:31
After doing some digging I found that @StevenKKC's approach is actually correct, you've been assigned, thanks!

**Comment by jasperhuangg** [comment] 2023-06-14 17:37
Sorry @StevenKKC I made a mistake and it turns out your proposal isn't correct, sorry for the back and forth.

**Comment by jasperhuangg** [comment] 2023-06-14 17:50
@mananjadhav should be fine, I can reassign you if necessary

**Comment by StevenKKC** [comment] 2023-06-14 19:23
@jasperhuangg Could you please let me know what isn't correct in my proposal?

**Comment by jasperhuangg** [comment] 2023-06-14 20:51
@StevenKKC I did some investigation with an internal engineer and the back-end is incorrectly creating the `assigned` action. That shouldn't even exist in the database. Therefore this bug requires back-end changes to correct. Your solution is correct, but is more of a bandaid on what the actual issue is.

**Comment by jasperhuangg** [comment] 2023-06-21 18:56
Was deployed a while ago, closing

**Closed by jasperhuangg** 2023-06-21 18:56 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
