### ISSUE TITLE
[Waiting for payment][$1000] LHN  - Face issue when two user click each another at same time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23437] opened 2023-07-23 19:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Take two device
2. Search for user B in device A & Search for user A on device B
3. You will see one account in search result
4. click on that account from both device together
5. It wont reflect profile image an if you send message it will show error

## Expected Result:
 It should behave properly and take user to original chat screen between each other
 
## Actual Result:
It opens up two chat screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6d1f4fee-50e9-4cd9-b889-f550dcdd66fb

https://github.com/Expensify/App/assets/93399543/6f5b2ce7-13e7-4be9-8895-a932d0590b85

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689936480446639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b8478f5b1e48991e</li>
        <li>Upwork Job ID: 1684794155842043904</li>
        <li>Last Price Increase: 2023-08-04</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25995540</li>
<li>tienifr | Contributor | 25995542</li>
<li>DinalJivani | Reporter | 25995544</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-25 04:50
I attempted to reproduce this and wasn't able to on staging app version 1.3.44-2. @DinalJivani can you please update the iOS app to the latest version and let me know if you can still reproduce this?

**Comment by DinalJivani** [comment] 2023-07-25 11:55
> I attempted to reproduce this and wasn't able to on staging app version 1.3.44-2. @DinalJivani can you please update the iOS app to the latest version and let me know if you can still reproduce this?

I tested this issue with lates iOS/Native and that version is still not updated, So basically on iOS/Native I'm using latest version.

**Comment by kadiealexander** [comment] 2023-07-26 07:31
I understand the two actions were taken simultaneously, and I did the same on my iOS device and web browser:


https://github.com/Expensify/App/assets/59587260/b6b40e6a-d7df-4519-bd0e-357b96c8ab99


https://github.com/Expensify/App/assets/59587260/707dc8a2-3691-4a4c-abaf-aecf22825e99

**Comment by kadiealexander** [comment] 2023-07-28 05:13
Thanks @DinalJivani, reproduced:

https://github.com/Expensify/App/assets/59587260/f6f6ee3e-5ea2-41be-ae34-56797bca1c7a

**Comment by kadiealexander** [comment] 2023-08-04 04:12
@fedirjh any thoughts on the above?

**Comment by kadiealexander** [comment] 2023-08-07 03:28
Bumped @fedirjh in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1691378345638289).

**Comment by NikkiWines** [comment] 2023-08-07 19:31
Yep, @tienifr's proposal looks solid! Assigning 🚀

**Comment by NikkiWines** [comment] 2023-08-21 18:46
@kadiealexander looks like this issue was resolved via a separate PR (https://github.com/Expensify/App/pull/24320) so the [PR](https://github.com/Expensify/App/pull/24295) for this issue has been closed and we can wrap this issue up

**Comment by NikkiWines** [comment] 2023-09-28 09:55
DM'd @kadiealexander about this so we can move it along

**Comment by kadiealexander** [comment] 2023-09-28 19:41
Oops sorry team I'm not sure how I missed this one! I don't think anyone needs payment if this was solved by a previous bug report, please reopen if you disagree.

**Comment by kadiealexander** [comment] 2023-10-05 04:52
Payouts due:

Issue Reporter: $250 @DinalJivani
Contributor: $1000 @tienifr 
Contributor+: $1000 @fedirjh

Eligible for 50% #urgency bonus? No

Upwork job is [here](https://www.upwork.com/jobs/~01b8478f5b1e48991e).

**Comment by kadiealexander** [comment] 2023-10-05 04:54
@fedirjh please accept the Upwork contract [here](https://www.upwork.com/nx/wm/offer/25995540).

**Comment by kadiealexander** [comment] 2023-11-09 11:04
Sent one [here](https://www.upwork.com/nx/wm/client/dashboard?offerRid=27591159&teamUid=1328455843768528896)

**Closed** 2023-11-12 22:52 UTC
Labels: Reviewing, External, Daily, Bug
