### ISSUE TITLE
Hold - Emoji context menu doesn't close when hold RHN modal opens

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52749] opened 2024-11-19 10:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** expensify416+da2@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to a workspace chat
2. Submit two manual request
3. Click on the IOU component and navigate to combined expense report
4. Right click on one of the IOU > click hold

## Expected Result:
Emoji context menu should close when hold RHN modal opens

## Actual Result:
Emoji context menu doesn't close when hold RHN modal opens

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e8c9eeb3-cb68-47b6-8ee9-8bb500a4f7a5

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment] 2024-11-19 11:01
Same root cause and the fix is been worked out [here](https://github.com/Expensify/App/issues/52744#issuecomment-2485280321)

**Comment by Julesssss** [comment] 2024-11-19 11:22
Thanks. Fix PR is [here](https://github.com/Expensify/App/pull/52752) and I have just kicked off test builds.

**Comment by Julesssss** [comment] 2024-11-19 16:35
Asked for a retest [here](https://expensify.slack.com/archives/C9YU7BX5M/p1732034115588639)

**Comment by mallenexpensify** [comment] 2024-11-19 22:04
Thanks @izarutskaya !  Closing as it's not reproducible.

**Closed by mallenexpensify** 2024-11-19 22:04 UTC
Labels: Reviewing, Engineering, Daily, Bug
