### ISSUE TITLE
[$500] IOU - "Unsubscribe from thread" button is visible on the hover menu

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34428] opened 2024-01-12 10:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.24.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Create a workspace
2. Create a scan IOU with a PDF in the workspace chat (make sure to keep hovering over the IOU on Windows)

## Expected Result:
The button shouldn't disappear.

## Actual Result:
"Unsubscribe from thread" button is visible for a short time on the hover menu.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2d0ecb19-ba4b-4fbe-97d5-1154433af0ea

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0117b089c8644a20b4</li>
        <li>Upwork Job ID: 1745750063528005632</li>
        <li>Last Price Increase: 2024-01-12</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2024-01-12 10:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Unsubscribe from thread" button is visible for a short time on the hover menu.

### What is the root cause of that problem?
We don't set childReportNotificationPreference in reportAction of request money message 

### What changes do you think we should make in order to solve the problem?
We should set childReportNotificationPreferenc === 'hidden' in optimistic data of  request money message 

### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2024-01-12 10:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The unsubscribe option menu shows for a brief moment on a scanning request.

### What is the root cause of that problem?
One of the conditions the unsubs option will show is that the `childReportNotificationPreference` is not hidden. When we create a scan request, the `childReportNotificationPreference` is empty.
https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/pages/home/report/ContextMenu/ContextMenuActions.js#L199-L213

Because it's empty, based on the logic above, the value will default to ALWAYS because we are the creator. Then, later we will get a HIDDEN value from the server, so the button hides, but the subscribe option never shows because we hide it if it's a whisper.

https://github.com/Expensify/App/blob/b6a18b185f485cf17474c18add56359f4624b56a/src/pages/home/report/ContextMenu/ContextMenuActions.js#L170-L171

### What changes do you think we should make in order to solve the problem?

We can hide the unsubscribe option too if it's a whisper.

**Comment by AliKhokhar123** [comment] 2024-01-12 13:33
**Problem Statement:**
The "Unsubscribe from thread" button is briefly visible on the hover menu, causing a momentary glitch.

**Root Cause Analysis:**
Upon reviewing the provided information, it appears that the issue lies within the handling of childReportNotificationPreference in the ContextMenuActions.js file. Specifically, when creating a scan request, childReportNotificationPreference is initially empty, and later, a value of 'hidden' is returned from the server. However, due to the logic in place, the value defaults to 'ALWAYS' before being updated to 'HIDDEN', causing the button to briefly appear.

**Solution Approach:**
To address this issue, I propose the following changes:

Explicitly Set childReportNotificationPreference:
In cases where the API returns childReportNotificationPreference: 'hidden' for a scan request, we should explicitly set this value in the ContextMenuActions.js file. This ensures that the correct notification preference is established upfront, preventing the momentary display of the "Unsubscribe from thread" button.

javascript
Copy code
// Add this line where appropriate based on the logic flow
childReportNotificationPreference = 'hidden';
Optional Setting for Whisper Cases:
Considering the nature of the whisper scenario, we can hide the "Unsubscribe from thread" button if it's a whisper. This adjustment ensures that the button is not visible when it shouldn't be, providing a more consistent user experience.

javascript
Copy code
// Update the existing condition to include the check for whisper
return subscribed && (isCommentAction || isReportPreviewAction || isIOUAction) && (!isDeletedAction || shouldDisplayThreadReplies) && !isWhisper;
Optimistic Setting for Scanned Requests:
Optionally, we can set the notification preference to 'hidden' optimistically when the request is going to be scanned. This can be achieved by checking the length of the whisperedToAccountIDs in the buildOptimisticIOUReportAction function.

javascript
Copy code
// Add this check in buildOptimisticIOUReportAction
if (whisperedToAccountIDs.length > 0) {
    reportAction.childReportNotificationPreference = 'hidden';
}

**Conclusion:**
These proposed changes aim to resolve the issue of the momentary visibility of the "Unsubscribe from thread" button by ensuring proper handling of childReportNotificationPreference in relevant scenarios. I am committed to implementing these changes once officially onboarded and given access to the codebase.

I look forward to your feedback and the opportunity to contribute to enhancing the stability and usability of the Expensify system.

Best regards,

Ali Ahmed
alikhokhar01233210@gmail.com
Upwork Profile: https://www.upwork.com/freelancers/~015c32305f13acc7f8

**Comment by s77rt** [comment] 2024-01-13 13:27
@DylanDylann Thanks for the proposal. Your RCA is about right. However when the server response is received I expected the subscribe button to appear. The fact that it didn't means we have some other inconsistency to deal with (not a blocker). Setting the `childReportNotificationPreference` in the optimistic data is not a wrong approach but I don't think it's necessary, we don't seem to be setting this field anywhere so let's keep it that way for simplicity.

**Comment by s77rt** [comment] 2024-01-13 13:33
@bernhardoj Thanks for the proposal. Your RCA is correct. Hiding the unsubscribe option for whisper actions seems to be the most straightforward solution here. Let's go with that.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/34428#issuecomment-1888823828)

cc @srikarparsi

**Comment by s77rt** [comment] 2024-01-13 13:35
@AliKhokhar123 Thanks for the proposal. Unfortunately it's a dupe.

**Comment by s77rt** [comment] 2024-01-13 13:48
@puneetlath While at it, can you check those two BE bug (also related to this issue):

## Bug 1:

1. Create IOU request (manual)
2. The `childReportNotificationPreference` should be `always`


## Bug 2
1. Create IOU request (scan)
2. The `childReportNotificationPreference` should be `always` even if it's scanning. I don't see why it's being returned as `hidden`



Technically the BE fix should also fix this issue. But for consistency I think we should still apply the FE fix (disable unsubscribe option for whisper actions)


https://github.com/Expensify/App/assets/16493223/be61e8a0-e0fb-4da9-bcb7-089d502ff8fb

**Comment by s77rt** [comment] 2024-01-16 01:27
Not overdue. @puneetlath ^

**Comment by srikarparsi** [comment] 2024-01-16 06:46
Hey, coming from this [issue](https://github.com/Expensify/App/issues/30644) where we removed the ability to `subscribe` and `reply in thread` to whisper messages. The rationale for keeping the `unsubscribe from thread` option is that it would make it easier to remove these threads from a users LHN but if we remove the `unsubscribe from thread` option, they would still be able to remove it by clicking into the thread. Also, I left a comment here with the reasoning behind removing `subscribe` and `reply in thread` from whisper messages.

**Comment by s77rt** [comment] 2024-01-18 18:42
Not overdue. @puneetlath ^

**Comment by s77rt** [comment] 2024-01-22 16:55
@puneetlath ^

**Comment by puneetlath** [comment] 2024-01-25 15:11
@srikarparsi are you saying that the current behavior is the right behavior and we should close this issue?

**Comment by srikarparsi** [comment] 2024-01-26 04:55
Sorry, I think that this issue is a bug. I just think that the solution to this is to remove the `unsubscribe from thread` in the same way that we [removed](https://github.com/Expensify/App/issues/30644) the `subscribe` and `reply in thread` options.

I previously wanted to keep the `unsubscribe from thread` option so that it would make it easier to remove these threads from a users LHN but since this is causing bugs I don't think it's too needed. Users can still remove these threads by clicking into them and leaving from the top right of the header.

**Comment by s77rt** [comment] 2024-01-29 18:33
@puneetlath Did you get a chance to check https://github.com/Expensify/App/issues/34428#issuecomment-1890463646?

**Comment by mvtglobally** [comment] 2024-01-30 04:57
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2024-02-01 22:18
@puneetlath ^

**Comment by s77rt** [comment] 2024-02-05 14:38
@puneetlath When you get a chance please check https://github.com/Expensify/App/issues/34428#issuecomment-1890463646

Also cc @rlinoz as I think you worked on notification preferences

**Comment by rlinoz** [comment] 2024-02-06 12:18
I think we started returning `hidden` so it doesn't show up in the LHN, but I am not sure if this is the same thing.

cc: @srikarparsi @marcaaron

**Comment by s77rt** [comment] 2024-02-07 18:06
Not overdue. ^

**Comment by srikarparsi** [comment] 2024-02-09 07:47
Hey, we actually [removed](https://github.com/Expensify/App/pull/35573) the leave thread/unsubscribe from thread option everywhere so I don't think this issue will be there anymore?

**Comment by s77rt** [comment] 2024-02-09 18:18
@srikarparsi Correct! This is no longer reproducible

**Comment by puneetlath** [comment] 2024-02-09 18:39
Ah cool, I'll go ahead and close this out then. Thanks y'all.

**Closed by puneetlath** 2024-02-09 18:39 UTC
Labels: Engineering, Daily, Internal, Bug
