### ISSUE TITLE
Expense - Unable to drag and drop receipt to Upload receipt RHP

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49901] opened 2024-09-29 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to DM
3. Submit an expense without receipt
4. Go to transaction thread
5. Click on Add receipt modal
6. Drag and drop an image to the RHP

## Expected Result:
Image can be dragged and dropped to Upload receipt RHP

## Actual Result:
Image cannot be dragged and dropped to Upload receipt RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/cf0d7f03-23d8-4686-8543-da33b6cbdb16

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-09-29 18:50
We think that this bug might be related to #wave-control

**Comment by huult** [comment] 2024-09-30 02:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Android- expense - In camera screen receipt header is missing

### What is the root cause of that problem?

The `backTo` is `undefined`, which prevents the wrapper from showing and causes this issue.

https://github.com/Expensify/App/blob/36346702f2e2e1621bb2b31d6a7d35cbe1c1d105/src/pages/iou/request/step/IOURequestStepScan/index.tsx#L698

`backTo` is `undefined` because `Navigation.getReportRHPActiveRoute()` returns `undefined` when clicked from the money request view.
https://github.com/Expensify/App/blob/3047c1baa21f47825f5c1ffd652184341dd22256/src/components/ReportActionItem/MoneyRequestView.tsx#L538

### What changes do you think we should make in order to solve the problem?
We should check if `getReportRHPActiveRoute` returns `undefined`, and if so, use `getActiveRouteWithoutParams`.
```diff
// src/components/ReportActionItem/MoneyRequestView.tsx#L538
{shouldShowReceiptEmptyState && (
                    <ReceiptEmptyState
                        hasError={hasErrors}
                        disabled={!canEditReceipt}
                        onPress={() =>
                            Navigation.navigate(
                                ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
                                    CONST.IOU.ACTION.EDIT,
                                    iouType,
                                    transaction?.transactionID ?? '-1',
                                    report?.reportID ?? '-1',
-                                    Navigation.getReportRHPActiveRoute(),
+                                    Navigation.getReportRHPActiveRoute() || Navigation.getActiveRouteWithoutParams(),
                                ),
                            )
                        }
                    />
                )}
```

### What alternative solutions did you explore? (Optional)
We used getActiveRouteWithoutParams instead of getReportRHPActiveRoute.
```diff
// src/components/ReportActionItem/MoneyRequestView.tsx#L538
{shouldShowReceiptEmptyState && (
                    <ReceiptEmptyState
                        hasError={hasErrors}
                        disabled={!canEditReceipt}
                        onPress={() =>
                            Navigation.navigate(
                                ROUTES.MONEY_REQUEST_STEP_SCAN.getRoute(
                                    CONST.IOU.ACTION.EDIT,
                                    iouType,
                                    transaction?.transactionID ?? '-1',
                                    report?.reportID ?? '-1',
-                                    Navigation.getReportRHPActiveRoute(),
+                                    Navigation.getActiveRouteWithoutParams(),
                                ),
                            )
                        }
                    />
                )}
```
Note: Same as [my proposal](https://github.com/Expensify/App/issues/49881#issuecomment-2381248111) posted previously.
<summary>
<details>POC

- <img width="1512" alt="Screenshot 2024-09-30 at 09 37 57" src="https://github.com/user-attachments/assets/98d79d5b-e592-4141-bd9d-1e3012c012e6">


</details>
</summary>

**Comment by Gonals** [comment] 2024-09-30 10:49
Not a Web-E blocker

**Comment by carlosmiceli** [comment] 2024-09-30 13:37
I think @bernhardoj already fixed this [here](https://github.com/Expensify/App/pull/49916)? Should I assign you to this one? I don't think this should be weekly btw, I'll change it to Hourly until we confirm this is solved today since it's a rough bug.

**Comment by bernhardoj** [comment] 2024-09-30 14:36
@carlosmiceli yes, I'm fixing it in https://github.com/Expensify/App/pull/49916. Not sure if I need to get assigned here though.

**Comment by carlosmiceli** [comment] 2024-09-30 15:01
Since @luacmartins is reviewing that PR I'll let him decide, should @bernhardoj be assigned to this issue too?

**Comment by luacmartins** [comment] 2024-09-30 18:36
Confirmed fix on staging.

**Comment by luacmartins** [comment] 2024-09-30 18:36
This was a regression so I'm gonna close the issue.

**Closed** 2024-09-30 18:36 UTC
Labels: Reviewing, Engineering, Hourly
