### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] Web - Sign in - Safari Password module does not go away after signing in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32683] opened 2023-12-07 16:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

## Action Performed:
Pre-Cond: You have at least one login saved on Safari browser
1. Access staging.new.expensify.com on Safari
2. Sign into a valid account and on the password screen DON'T dismiss the password module
3. Input the magic code and navigate the app

## Expected Result:
User expects two things, that either this password module doesn't show at all (Because now you need a magic code and its no longer relevant) OR that if it does show, its dismissed after signing in.

## Actual Result:
The password module does not dismiss itself and the user navigates through the site and it continues to show

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/dc1d5d5b-dba3-45fd-9c16-20f6327c1b65

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a736d294b1b7be1</li>
        <li>Upwork Job ID: 1732796554278481920</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 102946366</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by ZhenjaHorbach** [comment] 2023-12-07 17:05
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

Web - Sign in - Safari Password module does not go away after signing in

## What is the root cause of that problem?

The problem is related to the operating principle of the popup
Which triggers
Not when the input is in focus, but when we change the value of the input

https://github.com/Expensify/App/blob/710ebbf6ca3d34bf9806169a9196dd8a6c5779ac/src/components/MagicCodeInput.js#L175-L177

## What changes do you think we should make in order to solve the problem?

To fix this bug we can update this code  and move blur at the end:

```
        props.onFulfill(props.value);
        lastValue.current = '';

        // Blurs the input and removes focus from the last input and, if it should submit
        // on complete, it will call the onFulfill callback.
        blurMagicCodeInput();
```

https://github.com/Expensify/App/blob/710ebbf6ca3d34bf9806169a9196dd8a6c5779ac/src/components/MagicCodeInput.js#L175-L177

## What alternative solutions did you explore? (Optional)
NA

**Comment by MitchExpensify** [comment] 2023-12-12 19:42
You won't need a magic code to sign into NewDot soon, closing

**Comment by MitchExpensify** [comment] 2023-12-15 21:54
@tienifr https://github.com/Expensify/App/issues/30794

**Comment by ikevin127** [comment] 2024-06-20 23:55
> You won't need a magic code to sign into NewDot soon, closing

@MitchExpensify Looks like this issue is still present 6 months later as we still need magic code to sign-in into ND.

I think this is worth fixing since it's an easy fix and **more importantly** it's really bad UX for both desktop and mobile Safari users (cc @Expensify/design). My [proposal](https://github.com/Expensify/App/issues/32683#issuecomment-1845843335) is still valid and ready for review / implementation if selected.

> [!note]
> Bumping on this since I still encounter the bug everytime I test on Safari and I need to login 😅
> **I can take this on fixing this as both Contributor and C+ reviewer if @situchan is not available for review.**

**Comment by situchan** [comment] 2024-06-21 01:31
I am still available for C+ review.

**Comment by shawnborton** [comment] 2024-06-21 05:56
Cool, this is probably worth fixing but I think we should drastically reduce the bug bounty here.

**Comment by ikevin127** [comment] 2024-06-21 06:21
Indeed, I agree based on what was stated in [this Slack 🧵](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1712256409152489) regarding the bounty change from $500 to $250 that:

> Any issues created before this date will maintain their original stated price.

but given that an issue is in the works to eventually remove the magic code functionality, I think $250 would be fair.

Do we agree 👍 or 👎.

**Comment by trjExpensify** [comment] 2024-06-21 15:44
Yeah, I don't think unvalidated sign-ups makes a difference here. If at any point you decide to sign-out and then need to sign back in using the magic code this autofill will get in the way. 

Reopening, adjusting the price. @situchan please review @ikevin127's proposal as a next step. 👍

**Comment by situchan** [comment] 2024-06-24 14:58
Please also cover the fix of https://github.com/Expensify/App/issues/34699 which was closed in favor of this one.

**Comment by situchan** [comment] 2024-06-26 01:05
Waiting for updated proposal

**Comment by MitchExpensify** [comment] 2024-06-26 21:35
Can you take a look here please @situchan ? Thanks

**Comment by ikevin127** [comment] 2024-06-26 21:44
> Please also cover the fix of https://github.com/Expensify/App/issues/34699 which was closed in favor of this one.

I am not able to reproduce that bug on Safari: mWeb. Regardless, my [proposed solution](https://github.com/Expensify/App/issues/32683#issuecomment-1845843335) would fix that issue too (if still present) which can be verified by understanding the issue's RCA as explained and by reviewing and testing the proposal.

**Comment by ikevin127** [comment] 2024-06-29 21:18
From **C+ Process Doc**:
> ### C+ assigning and process
> 
> When External label is added C+ is assigned via OSBotify random assignment  to review incoming proposals and they are made the issue owner.  **If C+ hasn’t provided a meaningful review within one business day of a proposal being submitted, the internal engineer or BZ member will “bump” the C+ on Github asking for a review. If the C+ doesn’t review the next day, the internal employee will post in #contributor-plus in Slack and request the first available C+ to take over. The original C+ will not be paid.** The same process applies for proposal and PR reviews. No changes/updates will be needed here because the Daily issue will be marked with the Overdue label if it’s not commented on within 24 hours

@trjExpensify @MitchExpensify As per the C+ process doc, given this issue is `Daily` -> I think 3+ days is enough to consider current reviewer unavailable after **MitchExpensify**'s [bump](https://github.com/Expensify/App/issues/32683#issuecomment-2192664257). 

**Can we please re-assign C+ here either by auto-assign or by asking if other C+ on Slack ?**

**Comment by situchan** [comment] 2024-07-01 04:40
@ikevin127 FYI: you didn't consider weekend when calculate 3 days. And the ball was not on my side at the moment when Mitch bumped me [here](https://github.com/Expensify/App/issues/32683#issuecomment-2192664257). And issue was Overdue only during weekend.

**Comment by situchan** [comment] 2024-07-01 04:40
@ikevin127 please take this over as C+

**Comment by ikevin127** [comment] 2024-07-01 16:51
@MitchExpensify Please assign me as C+ here so I can start reviewing the existing proposals and move this forward, thank you!

**Comment by trjExpensify** [comment] 2024-07-01 16:55
^^ done!

**Comment by ikevin127** [comment] 2024-07-01 19:18
I double-checked both proposals and there are some differences in both RCA and solution:
- **ikevin127**'s RCA makes more sense in actually pointing out the **root cause** of why the Safari email auto-fill popup is showing for an input that it shouldn't show-up for
- **tienifr**'s RCA is vague in the sense that it doesn't show why the email auto-fill popup is showing-up on an input that is not of type email

To double-down on the RCAs evaluation -> this is also showing-up when it comes to the different solutions:
- **ikevin127**'s solution makes it such that the email auto-fill popup doesn't show-up at all on the magic code screen (see video below)
- with **tienifr**'s solution we still see the email auto-fill popup on the magic code screen until we actually input the code and sign-in is performed (see video below)

**tienifr**'s [solution](https://github.com/Expensify/App/issues/32683#issuecomment-1847659731)

<details>
<summary>MacOS: Safari</summary>

https://github.com/Expensify/App/assets/56457735/f6fa217e-ca73-482d-902b-674107a1564c

</details>

**ikevin127**'s [solution](https://github.com/Expensify/App/issues/32683#issuecomment-1845843335)

<details>
<summary>MacOS: Safari</summary>

https://github.com/Expensify/App/assets/56457735/e154869a-4b89-426e-a822-25663d4ca76c

</details>

##

Quote from **C+ Process Doc**:
> If C+ wants to submit a proposal to fix the issue they do so and tag the internal engineer (by adding “ 🎀👀🎀”) to review the proposal.  All other aspects of working on the issue as the same as other contributors (as of Feb 2024 this is very rare) 

Regarding this issue, I'm fine with either of the following:
1. Allow **tienifr** to be Contributor and implement my solution and I will be C+ reviewer -> we each get paid.
2. I will handle both PR and review and only get paid the bounty once.

Given the above video results and the issue's **expected result** I'm inclined to go with my own solution, but since this might be seen as biased since I'm the C+ as well, I will defer this to the team / assigned CME for final decision.

🎀👀🎀 C+ reviewed

**Comment by cristipaval** [comment] 2024-07-02 07:52
yes, I also prefer the solution proposed by @ikevin127. Given that they are the C+ here, I would prefer to either assign another C+ for review or let @tienifr implement the solution and @ikevin127 review it. I think it's good to have 2 pairs of eyes on the solution, that's why I don't want to have the same person as the contributor and C+.

**Comment by cristipaval** [comment] 2024-07-02 07:53
I'll assign @tienifr as the contributor as they already have knowledge around it.

**Comment by ikevin127** [comment] 2024-07-02 19:39
@tienifr Regarding the solution, I was thinking we could create a `SafariFormWrapper` component to apply the `form` wrapper targeted for Safari only using `Browser.isSafari()` to prevent any possible regressions / unexpected behaviour on other browsers where this issue is not present. Wdyt ?

```ts
function SafariFormWrapper({ children }) {
    if (Browser.isSafari()) {
        return <form>{children}</form>;
    }

   return <>{children}</>;
}
```

**Comment by ikevin127** [comment] 2024-07-03 22:56
@tienifr Sorry we didn't ask, do you want to work on this or should we find another contributor to open the PR for this issue ?

**Comment by ikevin127** [comment] 2024-07-08 07:17
@tienifr Yes, I can still reproduce the issue on Safari web, you need to have autocomplete login data saved in order to reproduce.

The mentioned `FormElement` component doesn't use html `<form>` (proposed solution), it's just a react native `<View>` wrapper if you check the component source.

##

If you cannot reproduce, let us now and we'll reassign somebody who can and wants to open the PR.

**Comment by ikevin127** [comment] 2024-07-08 21:21
@tienifr My bad I didn't notice the `form` role. Anyway, I can still reproduce the issue on staging and local dev without the proposed fix, just as shown in OP video.

I looked into why the parent `<form>` applied by `FormElement` doesn't fix the issue and the proposed solution does.
As a note, the solution was inspired by this SO [comment](https://stackoverflow.com/a/57678169/13182454).

The `FormElement` wrapper contains the following logic:

https://github.com/Expensify/App/blob/fb7fe9f47acb4db2e4cf855be0fe8121211038db/src/components/FormElement/index.tsx#L18-L36

There's 2 ways in which, compared to the empty `<form>` proposed by the solution, the logic above facilitates the issue:
1. The presence of the `novalidate` attribute.
2. The lack of the `dataset` attribute, with empty object passed.

**How did I test this ?**
I commented out the `novalidate` attribute addition and added the `dataset` attribute like so:
```diff
        // Prevent the browser from applying its own validation, which affects the email input
+       // formCurrent.setAttribute('novalidate', '');
+       formCurrent.setAttribute('dataset', '{}');
```
and the result is that the issue is fixed because the form would behave like the proposed solution form wrapper.

The reason why I proposed wrapping the `BaseValidateCodeForm` with the empty `<form>` wrapper and **only** for Safari is because it does the following:
1. Maintains the `FormElement` logic / added attributes which are global (apply for all browsers).
2. Fixes our issue by wrapping only `BaseValidateCodeForm` which only contains the magic code / recovery code inputs.
3. It applies the fix for the issue targeted for Safari only.

Therefore the 2nd form wrapper will only show-up on Safari and will be an empty form with empty object `dataset` attribute applied like so:

```html
<form dataset='[object Object]'>
...
</form>
```
which will fix our issue while not interfering with `FormElement`'s logic.

## Again

Please let me know ASAP if you CAN reproduce this and are willing to open the PR so we can move this forward right away as it has been dragging for a loooong time already.

**Comment by MitchExpensify** [comment] 2024-07-16 19:27
Reassigning while I'm out 🙇

**Comment by ikevin127** [comment] 2024-07-20 19:14
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/13655
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/13655/files#r1685519848
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

**Precondition**: You have at least one login saved on **Safari**.

<img width="327" alt="Screenshot 2024-07-20 at 12 07 21" src="https://github.com/user-attachments/assets/d1bfdeb4-738d-4a89-bf35-296d89bd9a10">

**Note**: The above autofill popup should **only** show-up on the **Phone or email** field.

1. Access the Expensify app on Safari web browser.
2. Select the the valid saved account using the autofil popup and click **Continue**.
3. Verify that on the next step -> **the magic code screen**, the email autofil popup is **not** visible.
4. Input the magic code and proceed with login.
5. Once logged-in, verify that the email autofill popup is not visible.

Do we agree 👍 or 👎.

**Comment by Christinadobrzyn** [comment] 2024-07-23 19:29
Regression test - https://github.com/Expensify/Expensify/issues/414729

Payouts due:

- [ ] Contributor: $250 @ikevin127 (Upwork offer - https://www.upwork.com/nx/wm/offer/102946366)
- [ ] Contributor+: $250 @tienifr (payment through NewDot)

**Comment by Christinadobrzyn** [comment] 2024-07-24 19:25
Payment day is here - payment summary - https://github.com/Expensify/App/issues/32683#issuecomment-2246125009

Closing this as @tienifr will be paid through NewDot.

**Closed by Christinadobrzyn** 2024-07-24 19:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
