### ISSUE TITLE
[Pay 4/29][$500] Group chat - Share code subtitle does not include the group creator

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39316] opened 2024-03-30 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause -Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Start chat
3. Create a group chat
4. Click on the group chat header
5. Click Share code

## Expected Result:
Share code subtitle will include the group creator, as group creator is shown in every part of the group chat/

## Actual Result:
Share code subtitle does not include the group creator

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ccee62e4-dcc3-407d-9d3d-d08b3a59848d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190680b621c41acf8</li>
        <li>Upwork Job ID: 1774823882828201984</li>
        <li>Last Price Increase: 2024-04-01</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-30 16:30
@CortneyOfstad  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-03-30 16:31
We think that this bug might be related to #vip-vsp

**Comment by CortneyOfstad** [comment] 2024-04-01 15:39
@cubuspl42 We have some proposals above — if you have any feedback, feel free to share. Thanks!

**Comment by cubuspl42** [comment] 2024-04-02 12:41
@gijoe0295 @nkdengineer

Both your proposals are relatively similar, I understand that @nkdengineer discovered another bug and provides a solution of that bug, too.

But what bothers me is that you both suggest to synchronize the code, so it's the same, instead of de-duplicating it. Why is that?

**Comment by nkdengineer** [comment] 2024-04-02 14:06
@cubuspl42 I do not fully understand the term "de-duplicating it" that you mentioned. But I assume that you mean is that, we should create a function, named ```getReportName``` and use it in LHN, Header, Sharecode, ... to reduce the duplication. Is that right?

**Comment by nkdengineer** [comment] 2024-04-02 14:42
@cubuspl42 I updated [my proposal (#### Option 2)](https://github.com/Expensify/App/issues/39316#issuecomment-2031556151)

**Comment by cubuspl42** [comment] 2024-04-02 15:25
> should create a function, named getReportName and use it in LHN, Header, Sharecode, ... to reduce the duplication.

Yeah, something like that.

De-duplication is a broad class of actions performed to reduce duplication, which is typically understood as the presence of the same ("copied-and-pasted") blocks of code or very similar blocks of code in the codebase.

I didn't suggest any exact strategy of de-duplication in this specific case; it's typically easier to spot the duplication than to solve it. 🙂

**Comment by cubuspl42** [comment] 2024-04-02 15:31
@nkdengineer What you suggest in Option 2 (extending `getReportName`) sounds elegant.

Have you ensured there is no specific reason why the code wasn't phrased this way? Are there any spots where we might want the "old" `getReportName` behavior in the case of group chats?

**Comment by nkdengineer** [comment] 2024-04-02 15:37
> Are there any spots where we might want the "old" getReportName behavior in the case of group chats

There is a lot of logic that we use ```getReportName```. And I cannot verify that whether we want to use the old ```getReportName``` behavior right now

**Comment by cubuspl42** [comment] 2024-04-03 12:26
Thanks everyone for their input!

I approve the proposal by @gijoe0295 

The element that shifted my decision towards their proposal is [the investigation of the reason why the code is as it is](https://github.com/Expensify/App/issues/39316#issuecomment-2032539076), which is very important information when changing something.

C+ reviewed 🎀 👀 🎀

**Comment by cubuspl42** [comment] 2024-04-03 12:28
@gijoe0295 While this is not related, it would be great if you added pronouns and a first name to your GitHub account; it can help refer to a person.

**Comment by nkdengineer** [comment] 2024-04-03 12:36
@cubuspl42 I see that the selected proposal will lead to regression with a thread in group report. Can you help check again. Also, my proposal does not encountered that regression

**Comment by cubuspl42** [comment] 2024-04-03 12:45
@nkdengineer 

Do you mean what you described here...

> Currently, if we create a group chat with [user A, user B, user C, user D (me)]. Then we send any message ("Hello" for example) to report and reply in the thread. We can see that, the header title is "user D".

...? I thought that this is another problem which also happens on `main`, not related to any proposed solutions.

**Comment by nkdengineer** [comment] 2024-04-03 12:47
@cubuspl42  No. I mean this casecase. You can see the below screen recording.

https://github.com/Expensify/App/assets/161821005/98af2e9f-3bcf-43f0-aaf4-effa70e0b734

**Comment by nkdengineer** [comment] 2024-04-03 13:23
@gijoe0295 
- In your [main solution](https://github.com/Expensify/App/issues/39316#issuecomment-2028257203), you say that we will apply the change same as Header View. If we do like that, the [regression](https://github.com/Expensify/App/issues/39316#issuecomment-2034519704) will appear
- In your alternative solution, I do not see any suggestion about "moved the group check into getReportName", and how to implement it. You just said "need to investigate and fix there as well".

**Comment by CortneyOfstad** [comment] 2024-04-03 17:20
Posted in VIP-VSB for confirmation [here](https://expensify.enterprise.slack.com/archives/C066HJM2CAZ/p1712164807609589)

**Comment by cubuspl42** [comment] 2024-04-03 17:59
Thanks for the constructive discussion!

Both Contributors (@gijoe0295, @nkdengineer) had constructive input:

- @gijoe0295 was the first one to provide a solution and did a valuable investigation
- @nkdengineer provided a proposal with improvements preventing the introduction of a regression

We could leave the assignment, but use @nkdengineer improvements and split the compensation:
- $330 for @gijoe0295 
- $330 for @nkdengineer 
- $330 for me

**Comment by srikarparsi** [comment] 2024-04-04 19:40
This [breakdown](https://github.com/Expensify/App/issues/39316#issuecomment-2035256446) sounds good to me. @CortneyOfstad does it sound good for you as well?

**Comment by marcaaron** [comment] 2024-04-05 17:59
@cubuspl42 when approving a proposal can you please link to the proposal? Helps save us some time! Thanks!

**Comment by marcaaron** [comment] 2024-04-05 18:01
> const isGroupChat = ReportUtils.isGroupChat(report) || ReportUtils.isDeprecatedGroupDM(report); 

This seems wrong to me or at least not really necessary. Just check `ReportUtils.isGroupChat(report)`. The Group DMs are getting deprecated so we don't need to make any special exceptions for them.

**Comment by marcaaron** [comment] 2024-04-08 18:37
Yes!

**Comment by cubuspl42** [comment] 2024-04-09 08:09
Would you assign a Contributor?

- My assignment recommendation is [here](https://github.com/Expensify/App/issues/39316#issuecomment-2034454750)
- As there was a discussion where we seem agree that the solution is a joint work, I suggested splitting the issue budget to 3 [here](https://github.com/Expensify/App/issues/39316#issuecomment-2035256446)

**Comment by CortneyOfstad** [comment] 2024-04-09 15:15
@marcaaron ^^^

**Comment by marcaaron** [comment] 2024-04-10 20:46
Please update the proposal? 

```js
const isGroupChat = ReportUtils.isGroupChat(report) || ReportUtils.isDeprecatedGroupDM(report);
```

Should not be checking the deprecated Group DM. Those are being deprecated...

>This issue also happens in several places using getReportName so we need to investigate and fix there as well. For example (this group has 3 members):

>Report details

This should be resolved in another PR

Other spots look good.

Please update and then we can proceed.

**Comment by marcaaron** [comment] 2024-04-10 20:47
I am fine with the proposed sharing if everyone else is. Can we get some thumbs up?

**Comment by cubuspl42** [comment] 2024-04-11 06:53
> Please update the proposal?

> Can we handle this when working on the PR?
> Yes

I meant to ask whether we can handle the suggestion when working on the PR. I assumed that it might not be worth updating the proposal because of the timezone differences. But it was just a minor misunderstanding.

**Comment by marcaaron** [comment] 2024-04-12 18:38
Oh ok, yes sorry I misunderstood you. I think a good best practice would be to update the proposal so there is clarity about what we decided to do. Less confusion later for future reference. Thanks for your understanding 🙇

**Comment by CortneyOfstad** [comment] 2024-04-17 15:00
PR is still in review [here](https://github.com/Expensify/App/pull/40134) 👍

**Comment by cubuspl42** [comment] 2024-04-18 08:10
Reviewed and merged 👍

**Comment by CortneyOfstad** [comment] 2024-04-29 14:18
## Payment Summary

- @gijoe0295 paid $500 via Upwork

Waiting for @cubuspl42 to accept the proposal in Upwork so they can be paid 👍

**Comment by cubuspl42** [comment] 2024-04-30 07:50
I accepted 👍

Just for cross-reference, this wasn't processed in https://github.com/Expensify/App/issues/41121 (which I didn't notice)

**Comment by nkdengineer** [comment] 2024-04-30 09:33
@CortneyOfstad @marcaaron Please help check our decision [here](https://github.com/Expensify/App/issues/39316#issuecomment-2035256446)

**Comment by CortneyOfstad** [comment] 2024-04-30 13:37
Sorry about that! @gijoe0295 I requested a refund for $170, so you should see that in Upwork now 👍 

@cubuspl42 — unfortunately Upwork would not let me modify the original proposal, so I had to send you a new proposal. Please let me know once you accept and I can get that paid ASAP. 

@nkdengineer — I sent you a proposal in Upwork, so please let me know once you accept and I'll get that paid ASAP. 

Thank you!

**Comment by CortneyOfstad** [comment] 2024-05-01 15:45
@cubuspl42 and @nkdengineer please let me know once you accept the proposals above ^^^ Thanks!

@gijoe0295 — thanks for the refund on the overpayment and sorry about that again!

**Comment by nkdengineer** [comment] 2024-05-02 15:40
@CortneyOfstad I accepted the offer, appreciate it 🙏

**Comment by CortneyOfstad** [comment] 2024-05-02 15:42
Payment made! 

@cubuspl42 waiting for you to accept the payment proposal — thanks!

**Comment by CortneyOfstad** [comment] 2024-05-06 14:39
Bump @cubuspl42 ^^^

**Comment by CortneyOfstad** [comment] 2024-05-08 19:19
Bump @cubuspl42 ^^^

**Comment by cubuspl42** [comment] 2024-05-09 15:17
I'm sorry! I wasn't active on GitHub or Upwork in the recent days. I accepted the offer.

**Comment by CortneyOfstad** [comment] 2024-05-09 16:24
No worries and payment made! Payment summary below!

## Payment Summary

@cubuspl42 — paid $330 via Upwork
@gijoe0295 — paid $330 via Upwork
@nkdengineer — paid $330 via Upwork

Closing!

**Closed by CortneyOfstad** 2024-05-09 16:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
