### ISSUE TITLE
Task title text is cut off in the marked complete message

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21469] opened 2023-06-23 22:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log into an account with tasks enabled on web.
2. Open a report (create it if it doesn't exist) and click on the '+' sign in the composer.
3. Choose 'Assign task' and fill out the title and description.
4. Click 'Next' and then fill out the remaining fields.
5. Click on the green button that says 'Confirm task'.
6. Open the task from the LHN and mark it as complete on Android.
7. Observe the message shown after marking as complete.
## Expected Result:
 The task's title in the message shown is shown in its entirety.
## Actual Result: 
The task's title is cut off in the message shown.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression  testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9a82d065-337c-4303-8b72-59727311d83f

<img src="https://github.com/Expensify/App/assets/43996225/8d5dece2-5576-4619-aafa-3a31ab6f0975" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Victor-Nyagudi 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687095102963459

[View all open jobs on GitHub](https://github
.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-06-24 05:35
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
* Problem 1 : We have a problem where long task names are not displayed properly in report actions view.
<details>
    <summary>Screenshot:</summary>
<img width="459" alt="Screenshot 2023-06-24 at 11 01 10 AM" src="https://github.com/Expensify/App/assets/78416198/7681c15c-19dc-43ad-b0b8-cd2f3acaca70">

</details>

* Problem 2 : I was also able to identify a different problem where long user names takes the mark as done button out of the screen.
<details>
    <summary>Screenshot:</summary>
<img width="480" alt="Screenshot 2023-06-24 at 11 01 06 AM" src="https://github.com/Expensify/App/assets/78416198/816b8d46-03be-4875-8d7e-ed93c4d400cb">

</details>

### What is the root cause of that problem?
* The root cause for Problem 1:
    - As both `Task name` and `Completed Task` are in the same view and both are give flex row direction so that they can be in the same line. But thats the issue as both will cover the same area. Thus not allowing to display the full text of the `Task name`.

* The root cause for Problem 2: 
    - The root cause for this problem is that the User's name is not given overflow hidden thus its taking the whole space and pushing the `Mark as done` button out of the screen.

### What changes do you think we should make in order to solve the problem?
### Solution For Problem 1:
- We should move `Completed Task`'s text component inside of the Task name's text component. 
(Changes are in `TaskAction.js` file.)

<details>
    <summary>Code Changes:</summary>

```diff
function TaskAction(props) {
    ...rest code

+   messageLinkText = `${messageLinkText} : `; // For better seperation between `complete task` and `task report name``

    return (
        <>
+           <View style={[styles.flex1, styles.flexRow, styles.alignItemsCenter]}>
-               <Text style={styles.chatItemMessageLink}>{messageLinkText}</Text>
-               <Text style={[styles.chatItemMessage]}>{` ${taskReportName}`}</Text>
-           <View style={[styles.flex1]}>
+               <Text style={[styles.chatItemMessage]}>
+                   <Text style={styles.chatItemMessageLink}>{messageLinkText}</Text>
+                   {` ${taskReportName}`}
+               </Text>
            </View>
        </>
    );
```

</details>

### Solution For Problem 2:
- We should make some changes in styling of the name by giving it flex2 and also overflow hidden to text component of user's name.
- Also adding some margin to the `Mark as done` button so that there's some space between the button and the user's name.
(Changes are in `TaskHeader.js` file.)

<details>
    <summary>Code Changes:</summary>

```diff
function TaskHeader(props) {
...rest code
                        <View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween, styles.pv3]}>
-                           <View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween]}>
+                           <View style={[styles.flexRow, styles.alignItemsCenter, styles.justifyContentBetween, styles.flex2]}>
                                {assigneeAccountID && assigneeAccountID > 0 && (
                                    <>
                                        <Avatar
                                            name={assigneeName}
                                            size={CONST.AVATAR_SIZE.HEADER}
                                        />
-                                       <View style={[styles.flexColumn, styles.ml3]}>
+                                       <View style={[styles.flexColumn, styles.ml3, styles.flex1]}>
                                            <Text
-                                               style={[styles.headerText, styles.pre]}
+                                               style={[styles.headerText, styles.pre, styles.overflowHidden, styles.flex1]}
                                                numberOfLines={1}
                                            >
                                                {assigneeName}
...rest code
                                    </>
                                )}
                            </View>
-                           <View style={[styles.flexRow]}>
+                           <View style={[styles.flexRow, styles.ml4]}>
                                {isCompleted ? (
...rest code
}
```

</details>

<details>
    <summary>Final Result:</summary>
    
<img width="452" alt="Screenshot 2023-06-24 at 11 00 26 AM" src="https://github.com/Expensify/App/assets/78416198/22b85567-9926-49e1-92b6-381858e7dd17">

</details>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mallenexpensify** [comment] 2023-06-26 21:24
Thanks @dhairyasenjaliya , I'll put on hold and make it a Weekly

**Comment by mallenexpensify** [comment] 2023-07-06 00:28
PR is in review for the help issue
- https://github.com/Expensify/App/issues/19330#issuecomment-1620695962
-

**Comment by mallenexpensify** [comment] 2023-07-17 19:46
- https://github.com/Expensify/App/pull/20841
The above, for issue #19330 caused a regression so I'm going to wait a bit before moving this forward

**Comment by mallenexpensify** [comment] 2023-07-26 01:30
Need to retest with the redesign, will do soon

**Comment by mallenexpensify** [comment] 2023-09-26 05:51
@kavimuru can you see if you're able to reproduce? 
If not, can you close please? 
The below, which this was held on, is closed. 
- https://github.com/Expensify/App/issues/19330

**Comment by mallenexpensify** [comment] 2023-10-02 14:02
@kavimuru can you please see if you, or someone from Applause, can reproduce? Thx

**Comment by mallenexpensify** [comment] 2023-10-10 00:57
Unable to reproduce.  Can you test again @kavimuru ?  Thx

https://github.com/Expensify/App/assets/22508304/31ba5b9f-b779-476e-bc9f-f20207880a56

**Comment by kavimuru** [comment] 2023-10-10 14:07
@mallenexpensify Checking with team. Also tagged contributor.

**Comment by kavimuru** [comment] 2023-10-10 14:27
@mallenexpensify not able to reproduce by our internal team 

Uploading az_recorder_20231010_161510.mp4…

**Comment by mallenexpensify** [comment] 2023-10-11 02:31
Thanks @kavimuru !  Closing

**Closed by mallenexpensify** 2023-10-11 02:31 UTC
Labels: Daily, Task

**Comment by Victor-Nyagudi** [comment] 2023-10-11 03:48
@mallenexpensify I didn't receive an offer for the reporting bonus of this one.

Kindly assist.

**Comment by mallenexpensify** [comment] 2023-10-12 00:24
@Victor-Nyagudi the bug report needs to be fixed in order to receive compensation, per [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=If%20it%27s%20a%20valid%20bug%20that%20we%20choose%20to%20resolve%20by%20deploying%20it%20to%20production%20%E2%80%94%20either%20internally%20or%20via%20an%20external%20contributor%20%E2%80%94%20then%20we%20will%20compensate%20you%20%2450%20for%20identifying%20the%20bug)

>  If it's a valid bug that we choose to resolve by deploying it to production — either internally or via an external contributor — then we will compensate you $50 for identifying the bug

**Comment by Victor-Nyagudi** [comment] 2023-10-12 03:49
I'm a little confused. Isn't that what happened here and is the reason the bug's no longer reproducible @mallenexpensify ?

**Comment by Victor-Nyagudi** [comment] 2023-10-12 05:25
My apologies. 

I've just seen that the issue this was held for came before my bug report, so it's not eligible for the reporting bonus.

In other words, there was already a fix in the works when my report came in.

The docs say that if you can prove your report came before the fix and find the PR with the fix, you'll get the bonus, but alas, that is not the case here. 

That was my initial reasoning..

**Comment by mallenexpensify** [comment] 2023-10-16 15:47
Thanks for the comment @Victor-Nyagudi , we do our best to follow CONTRIBUTING.md and update when needed, if anything isn't included or correct.
