### ISSUE TITLE
[HOLD for payment 2024-11-11] [HOLD for payment 2024-11-01] E2E Testing: PRs merged after a regression all get marked as regression as well

### ISSUE THREAD

**Issue by hannojg** [Expensify/App#48085] opened 2024-08-27 13:07 UTC
With the current architecture of the e2e tests there is a problem where:

- A new release is created, this will be the baseline for the e2e performance regression testing
- PR1 is merged which introduces a performance regression
- PR2 is merged with no performance regression
- PR3 is merged with no performance regression

however, all PRs will be compared against the same baseline. Thus not only PR1 gets marked as deploy blocker for having introduced a performance regression, but also PR2 and PR3.

This creates confusion and additional spam in slack:

![Screenshot 2024-08-27 at 15 04 46](https://github.com/user-attachments/assets/a4e02653-2e7a-4379-8243-fd6cce65499b)

[As discussed here](https://expensify.slack.com/archives/C05LX9D6E07/p1724753789480349), the proposed solution is to create for each merge commit to make a new baseline build from the previous merge commit and compare it against that one.

**Comment by hannojg** [comment] 2024-08-27 13:07
cc @kirillzyusko can you comment here so it can be assigned to you? Thanks!

**Comment by mountiny** [comment] 2024-08-27 13:21
cc @AndrewGable does this sound good to you?

**Comment by AndrewGable** [comment] 2024-08-27 15:58
Yes sounds great!

**Comment by mountiny** [comment] 2024-08-27 22:05
@kirillzyusko, are you going to take this one on? Can you comment here if so? thanks

**Comment by kirillzyusko** [comment] 2024-08-28 08:18
Yeah, feel free to assign this to me 🙌

**Comment by mountiny** [comment] 2024-09-06 10:57
not overdue

**Comment by kirillzyusko** [comment] 2024-09-11 10:26
I think we discussed this internally with Hanno, but I'll post here as well.

We think that we should postpone this PR, because current e2e tests are not very stable (i. e. sometimes they pass, sometimes not) and having such unstable pipeline with assembling builds for each new commit may lead to uncaught regressions, i. e.:

```
A <- first commit in chain, e2e passed no regression has been detected
|
|
B <- commit that introduces a regression and e2e tests fails
|
|
C <- e2e tests pass again, but we compare with a build that introduced a regression and this regression was unnoticed
```

So I think we need to have a good e2e pipeline first and only then go ahead with this PR 👀

**Comment by mountiny** [comment] 2024-09-15 23:39
Sounds good, are you or someone else actively working on fixing the pipeline?

**Comment by kirillzyusko** [comment] 2024-09-16 10:42
> Sounds good, are you or someone else actively working on fixing the pipeline?

@mountiny current e2e pipeline slightly unstable, but we need to have gather logs/videos for all latest failures to detect what needs to be fixed first.

From what I saw - we have several major problems:
- sometimes tests fail after 2-3 mins - looks like a job can not be started properly;
- sometimes tests fail after 9-10 minutes - it means that something is wrong with first test;
- sometimes third test fails;

I think we need to gather kind of analytics on what is the most frequent failure, gather logs for this failure and try to fix it. How does it sound for you?

I can prepare analytic based on latest failures (and attach links for all of them) but I need someone to help me to get logs + videos. Would you be able to help me? 👀

**Comment by mountiny** [comment] 2024-09-16 12:09
Provided some more logs in DM and also created an issue to give you and some other people from Margelo access to the device farm

**Comment by mountiny** [comment] 2024-09-27 15:49
@kirillzyusko how is this looking

**Comment by kirillzyusko** [comment] 2024-09-30 13:47
@mountiny I prepared two PRs:
- https://github.com/Expensify/App/pull/49649 (should fix a problem with failure after 8-10 minutes);
- https://github.com/Expensify/App/pull/49925 (should fix random build failures).

The remaining problem will be AWS scheduling - my assumption is that we'll need to add retry mechanism to that step (I think we can try to use https://github.com/marketplace/actions/retry-action).

But overall with these 2 fixes tests should become pretty stable (we should have 1-2 failures per week, which I think is kind of acceptable).

**Comment by mountiny** [comment] 2024-10-07 14:23
Bumped the PRs

**Comment by mountiny** [comment] 2024-10-16 08:59
How is this looking? Can @chrispader help here? I read he has some spare cycles

**Comment by kirillzyusko** [comment] 2024-10-18 10:02
@mountiny I will work on it 👀 Just will finish `react-native-app-logs` and will switch back to e2e tests stuff!

**Comment by mountiny** [comment] 2024-11-11 15:12
This was a follow up to improve the E2E test suite, I dont think we need a checklist in this case as Margelo keeps slowly improving the suite. No external review was done so no payment required either

**Closed by mountiny** 2024-11-11 15:12 UTC
Labels: Weekly, Awaiting Payment
