### ISSUE TITLE
[$1000] Primary login account is added to split bill participant list and amount also gets divided changing default contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19981] opened 2023-06-01 16:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: account should have primary login account A, and secondary login account B
1. Click on 'FAB' icon > click on 'Split bill' link > enter amount > click on 'Next' button
2. Select two users
3. Click on 'Split' button
4. Click on IOU preview component & verify that total of 3 participants are displayed in the details section
5. Click on 'Profile' icon > click on 'Contact methods' link > click on secondary login account B > click on 'Set as default' button
6. Close RHN & refresh the page for the changes to take effect
7. Click on the IOU preview component
## Expected Result:
 Primary login account A shouldn't be added to the split bill participant list
## Actual Result: 
Primary login account A is added to the split bill participant list
amount is also divided between primary login account and secondary login account on changing default contact method.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/66585e83-865d-4891-93b0-b98950edfe32

https://github.com/Expensify/App/assets/43996225/165d8a92-0bfb-4fb0-8ef9-ffb955d46e55

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685434411591889
https://expensify.slack.com/archives/C049HHMV9SM/p1685430101536709
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b4c1bac53442a0dd</li>
        <li>Upwork Job ID: 1664579284030091264</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-02 10:23
conorpendergrast+19981c@gmail.com created the split, then changed the default contact method to conorpendergrast+19981cc@gmail.com

Before the default contact method change: 

![image](https://github.com/Expensify/App/assets/5802477/55fe5670-7b9d-4d72-9813-738cb450f716)

After the default contact method change: 

![image](https://github.com/Expensify/App/assets/5802477/85a1d7ad-0547-4c02-8eaa-b93ddb44e3ab)

**Comment by wildan-m** [comment] 2023-06-03 09:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The primary login account is added to the split bill participant list and the amount also gets divided changing the default contact method 

### What is the root cause of that problem?

`reportAction.originalMessage.participants` not updated to the recent default contact method.

<img width="376" alt="SCR-20230603-m5u" src="https://github.com/Expensify/App/assets/11847279/b8a8e4f6-3728-4371-a4e3-e1f2757354d7">

We started to use participants data here:
https://github.com/Expensify/App/blob/0813e2ca1476635a8324cbd9f998424663a33128/src/pages/iou/SplitBillDetailsPage.js#L67

That makes users' old default contact added to split participants.

### What changes do you think we should make in order to solve the problem?
Update the originalMessage participants to the current default contact method in the backend.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by madmax330** [comment] 2023-06-05 09:02
@thesahindia have you had a chance to review the proposals?

**Comment by madmax330** [comment] 2023-06-08 05:11
Okay will ask internally to see if anyone knows about this.

**Comment by mountiny** [comment] 2023-06-08 12:10
@tienifr I think using the accountId makes sense and we are actively working now to make sure we are re-keying the personal details with accountIDs so I believe this should work well

**Comment by madmax330** [comment] 2023-06-08 15:27
Actually we discussed this internally and we're refactoring personalDetails by accountID already. So let's hold on that so that we don't duplicate work

**Comment by conorpendergrast** [comment] 2023-06-15 15:25
Still on hold for https://github.com/Expensify/App/issues/19007

**Comment by conorpendergrast** [comment] 2023-06-23 13:04
@madmax330 I see that https://github.com/Expensify/App/issues/19007 is now on Production, so I think we can take this off hold, re-test and fix. Do you agree?

**Comment by madmax330** [comment] 2023-07-03 11:37
Yeah seems like we can take this off hold

**Comment by conorpendergrast** [comment] 2023-07-04 07:59
Off-hold, ready to re-test and fix (if it still exists as an issue)

**Comment by JmillsExpensify** [comment] 2023-07-17 23:22
Removing from the manual request project since this is a wave2 issue.

**Comment by conorpendergrast** [comment] 2023-07-18 21:22
@tienifr What are you asking for as compensation? We can certainly discuss it!

**Comment by conorpendergrast** [comment] 2023-07-28 13:52
Ok, I agree with that! I'll queue up contracts via Upwork.com now (the job post is closed so I need to do that manually)

**Comment by conorpendergrast** [comment] 2023-07-28 13:57
- [ ] External issue reporter - @Natnael-Guchima: $250 in [this offer](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25808974), and contract TBC
- [ ] Contributor that fixed the issue: @tienifr: $1000 in [this offer](https://www.upwork.com/nx/wm/pre-hire/c/8577561/offer/25809013), and contract TBC
- [ ] Contributor+ that helped on the issue and/or PR: @thesahindia: $1000 - please send Manual Request via New Expensify
- [ ] Urgency bonus: N/A
Original Upwork job: https://www.upwork.com/jobs/~01b4c1bac53442a0dd

**Comment by Natnael-Guchima** [comment] 2023-07-28 13:59
Accepted the offer. Thanks @conorpendergrast

**Comment by conorpendergrast** [comment] 2023-07-31 07:43
Paid @tienifr 👍 Closing, as @thesahindia will send a Manual Request.

**Closed by conorpendergrast** 2023-07-31 07:43 UTC
Labels: External, Daily, Overdue, Bug

**Comment by JmillsExpensify** [comment] 2023-09-22 08:54
$1,000 payment approved for @thesahindia based on BZ summary.
