### ISSUE TITLE
Workspace - Schedule a setup call button not displayed for expensifail account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20878] opened 2023-06-15 23:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing** https://github.com/Expensify/App/pull/20639

## Action Performed:
1. Open the app
2. Login with private domain account or expensifail account
3. Go to settings
4. Go to workspaces
5. Select a workspace
6. Click the help icon in header (get assistance)

## Expected Result:
Schedule a setup call button displayed

## Actual Result:
Schedule a setup call button not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screen Shot 2023-06-15 at 12 11 42 PM](https://github.com/Expensify/App/assets/93399543/026f2081-e64c-46ab-b8f7-a6944e6788ff)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by isabelastisser** [comment] 2023-06-20 15:30
@kbecciv can you please share the slack conversation link?

**Comment by isabelastisser** [comment] 2023-06-22 20:38
Bumped the discussion in Slack.

**Comment by isabelastisser** [comment] 2023-06-23 13:45
Based on this [discussion](https://expensify.slack.com/archives/C01SKUP7QR0/p1687275205700669) in Slack, this is expected behavior, not a bug. Closing this!

**Closed by isabelastisser** 2023-06-23 13:45 UTC
Labels: Daily, Bug

**Comment by isabelastisser** [comment] 2023-06-23 13:47
@Expensify/applause @Expensify/applauseleads Hey team, can you please check if those steps are not in a regression test in the workspace editor on NewDot specifically? Thanks!
