### ISSUE TITLE
[HOLD for Regression Test] Web - Chat - After refreshing the page, the input field is initially missing

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11856] opened 2022-10-14 17:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Refresh the page

## Expected Result:
The input field should be visible immediately

## Actual Result:
The input field is initially missing

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.15.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![Untitled (2)](https://user-images.githubusercontent.com/93399543/195903366-c7003f0d-4af5-48ed-a3af-a56ab976a3c1.png)

https://user-images.githubusercontent.com/93399543/195903370-a319e668-d9c2-4b5b-a490-04308ffbee94.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017e4db016aa092c59</li>
        <li>Upwork Job ID: 1606465371376586752</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by parasharrajat** [comment] 2022-10-14 17:12
Should be marked as regression.

**Comment by bondydaa** [comment] 2022-10-14 17:14
it's reproducible on production already so that's why there's no deploy blocker

**Comment by bondydaa** [comment] 2022-10-14 17:41
just looking at recent PRs these could be related 

https://github.com/Expensify/App/pull/11217
https://github.com/Expensify/App/pull/10591

those both of those are pretty old.

**Comment by bondydaa** [comment] 2022-10-14 17:41
cc @jasperhuangg

**Comment by bondydaa** [comment] 2022-10-14 20:19
tossing this to the pool as I'm not the most qualified to handle this

**Comment by parasharrajat** [comment] 2022-10-18 13:08
@bondydaa let's re-apply the engineering label so that someone is assigned to it. Seems important to me.

**Comment by bondydaa** [comment] 2022-10-18 16:11
that's not exactly how our system works. the person assigned to triage (me) can chose to keep assigned if they're going to work on it or send it to our engineering pool for it to be picked up. The engineering label isn't a "you must do this" it just annoys other engineers when they have to context switch, see it's been triaged, unassign themselves again. It's marked as a daily, which I think is the correct label as well.

**Comment by parasharrajat** [comment] 2022-10-18 16:45
Ok, I see.

**Comment by isabelastisser** [comment] 2022-10-19 13:07
I was able to reproduce it:



https://user-images.githubusercontent.com/31258516/196699559-4ca2c578-6a6e-4972-af78-21805c47d86d.mp4

**Comment by Beamanator** [comment] 2022-10-24 09:08
Waiting for proposals (though this maaay be a regression of a recent PR - see https://github.com/Expensify/App/issues/11856#issuecomment-1279290052)

**Comment by greg-schroeder** [comment] 2022-10-26 12:36
Internal: https://www.upwork.com/ab/applicants/1585248825536315392/job-details
External: https://www.upwork.com/jobs/~01e1ccf6d1ca9a2ff6

**Comment by mvtglobally** [comment] 2022-11-03 03:12
Issue not reproducible during KI retests. (First week)

**Comment by Beamanator** [comment] 2022-11-03 15:48
Bump @rushatgabhane

**Comment by Beamanator** [comment] 2022-11-07 09:05
I agree that looks like a good idea, let's make sure @0xmiroslav 's PR fixes both this issue & https://github.com/Expensify/App/issues/11840 (assuming we do revert the changes from https://github.com/Expensify/App/pull/11853)

**Comment by Beamanator** [comment] 2022-11-24 16:50
Solution is still being discussed in the PR

**Comment by trjExpensify** [comment] 2022-12-09 01:38
👋 Can see this one has merged. Just a reminder to keep the issue up to date and add the `reviewing` label when the linked PR goes into review.

**Comment by Beamanator** [comment] 2022-12-20 15:51
@rushatgabhane are you able to sign in to App? If not, I'll try to test this out tomorrow

**Comment by JmillsExpensify** [comment] 2022-12-22 21:33
Do we need to get another engineers and contributors on this issue? I think it's pretty important that we close the loop.

**Comment by mallenexpensify** [comment] 2022-12-24 01:45
Not sure why the auto-assigners went crazy here, hmm... maybe it was cuz of OOO?
Unassigning @arosiclair and @JmillsExpensify 

@rushatgabhane added @thesahindia to help.  Since the IP issue is on our end, can you both due what ya can to move this along, then we'll settle compensation at the end, with the default being that you'll both get paid if you invested any time.

**Comment by mallenexpensify** [comment] 2022-12-29 00:19
For internal engineers and C+, the BugZero (BZ) team will need some guidance on payment here, specifically the 50% _penalty_ for - "Merged PR within 9 business days - 50% penalty" 

Nov 4th - new process with bonus for timeliness ([link](https://expensify.slack.com/archives/C01GTK53T8Q/p1667607226305649))
Nov 7th - @0xmiroslav hired 
Dec 28th - PR merged.

**Comment by mallenexpensify** [comment] 2023-01-03 00:31
I feel like this is kinda a "perfect storm" issue with so much happening between @0xmiroslav being hired and now (process change right before, the fix doesn't appear to be a _quick one_ and required [discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1669259814248689), [minimum job price soon after being hired](https://expensify.slack.com/archives/C01GTK53T8Q/p1668726522584349), IP address issue in the middle, Christmas break). I'm leaning towards paying the full amount and calling this an edge case. 

@0xmiroslav and @rushatgabhane can you please accept the job and reply here once you have?

**Comment by mallenexpensify** [comment] 2023-01-05 23:50
Thanks @rushatgabhane, ended your contract.  @thesahindia can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~017e4db016aa092c59

**Comment by thesahindia** [comment] 2023-01-06 10:30
Accepted, thanks!

**Comment by mallenexpensify** [comment] 2023-01-06 17:04
@thesahindia paid.  @greg-schroeder or I need to add the regression test steps then we'll be done.  Making this a weekly til then

**Comment by greg-schroeder** [comment] 2023-01-19 22:41
Working on regression test steps now

**Closed** 2023-01-30 12:19 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug

**Comment by greg-schroeder** [comment] 2023-01-30 12:31
Regression check here: https://expensify.slack.com/archives/C01SKUP7QR0/p1675081857853569

**Comment by greg-schroeder** [comment] 2023-01-30 18:29
File issue to update TestRail w/ new test: https://github.com/Expensify/Expensify/issues/258910

This issue is done now
