### ISSUE TITLE
[$1000]  The transition of opening a new workspace at the creation doesn't match to other pages reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12246] opened 2022-10-28 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > workspaces
2. Create a workspace
3. Check the transition

## Expected Result:
The transition should match with other pages when we navigate from one page to another

## Actual Result:
The previous page disappear and new page opens

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666951689786119

https://user-images.githubusercontent.com/43996225/198681345-b835ec79-cada-4aeb-83d5-62e9ac73ca75.mov

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/198681377-5963936d-c789-483e-9350-47570d7fff08.mp4

**Comment by michaelhaxhiu** [comment] 2022-11-03 23:52
Hey @kevinksullivan, just dropping a note as a reminder to [keep the pressure](https://expensify.slack.com/archives/C01SKUP7QR0/p1667064948124109) on to find a contributor and get this one closed out :)

Is this one `external` or `internal`? Let's label it accordingly and decide if it belongs in upwork or with an internal engineer. Either way, gonna add the `engineering` label so we can move it forward in terms of the process.  L

**Comment by kevinksullivan** [comment] 2022-11-04 03:09
Oh sorry @michaelhaxhiu , thanks for the reminder! Hm, this seems ever so slightly off so I could see a case for fixing. Posting to upwork for external, and hired @Puneet-here for reporting.

https://www.upwork.com/jobs/~018725fa3aa6f93d59

**Comment by tungmt** [comment] 2022-11-04 04:06
PROPOSAL:

Cause: The previous page disappear and new page opens because before navigate to new page the modal of previous page has been dismissed by `Navigation.dismissModal();`

Proposal: Remove the line `Navigation.dismissModal();` it look like work normal on model. For the web with current source when we close the new page (new workspace that just created) it go to /settings . When we remove line `Navigation.dismissModal();` it go to /settings/workspaces. Which one should be correct path when we close a workspace setting?

**Comment by eVoloshchak** [comment] 2022-11-04 10:35
@tungmt
You are right, this inconsistency is caused by [this](https://github.com/Expensify/App/blob/e434efa1c455620c510441628b94081e0f8a564e/src/libs/actions/Policy.js#L832) 
`Navigation.dismissModal()`
However we can't remove it, it was [added](https://github.com/Expensify/App/pull/10949/commits/08e2218f4233c3db789da0f1a11d3a347e94ad0c) to fix an issue with transitions  to existing workspaces from OldDot
```
Navigation.dismissModal(); // Dismiss /transition route for OldDot to NewDot transitions
```

So we have to either find a way to fix this without removing `Navigation.dismissModal()` or to find a way to resolve https://github.com/Expensify/App/pull/10949 without using `Navigation.dismissModal()`

**Comment by eVoloshchak** [comment] 2022-11-11 16:18
Not overdue, waiting for proposals

**Comment by kevinksullivan** [comment] 2022-11-11 19:42
Doubling price

**Comment by Puneet-here** [comment] 2022-11-11 21:01
### Proposal
Add a new param `transitionFromOldDot` at `createWorkspace` function
https://github.com/Expensify/App/blob/ecafa3cf9538b89b21db4ef22290a6c0737b53c2/src/libs/actions/Policy.js#L701

Add an if statement here
https://github.com/Expensify/App/blob/ecafa3cf9538b89b21db4ef22290a6c0737b53c2/src/libs/actions/Policy.js#L866-L868
```js
  if (transitionFromOldDot) {
                Navigation.dismissModal(); // Dismiss /transition route for OldDot to NewDot transitions
            }

```

Pass true here as an argument in the end

@eVoloshchak, I am sure it will work but I wasn't able to test this locally can you help me test it?

**Comment by tungmt** [comment] 2022-11-12 00:51
@Puneet-here yeah I think it should work, pass isLoggingInAsNewUser to createWorkspace function

**Comment by eVoloshchak** [comment] 2022-11-14 15:34
@Puneet-here, cool, I like your solution!

It indeed fixes this issue
And it also works correctly when transitioning from OldDot to NewDot, however, I verified this by calling `setUpPoliciesAndNavigate` manually with mock data, which is not sufficient. 
There is no `Get started with a free plan` option for me on OldDot, the one that can be seen in the description of https://github.com/Expensify/App/pull/10949

I'll investigate this and will your proposal locally, expect an answer in 24h

**Comment by eVoloshchak** [comment] 2022-11-16 18:13
Wasn't able to find this task in OldDot, asking in [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1668622366210179)

**Comment by eVoloshchak** [comment] 2022-11-16 22:24
Got a response and was able to test, @Puneet-here's [proposal](https://github.com/Expensify/App/issues/12246#issuecomment-1312188539) looks good!

🎀👀🎀 C+ reviewed!
cc: @kevinksullivan

**Comment by srikarparsi** [comment] 2022-11-16 23:58
this looks good to me as well. Assigning you to the issue @Puneet-here.

**Comment by Puneet-here** [comment] 2022-11-18 12:36
@eVoloshchak the PR is ready for review.

**Comment by eVoloshchak** [comment] 2022-11-21 16:52
Not overdue, PR was merged recently

**Comment by srikarparsi** [comment] 2022-11-24 09:06
^

**Comment by eVoloshchak** [comment] 2022-11-28 17:50
Not overdue, PR has been deployed to production 5 days ago

**Comment by kevinksullivan** [comment] 2022-11-29 20:29
Hm looks like this one just missed the notification to label properly. Waiting out the 7 day period still.

**Comment by JmillsExpensify** [comment] 2022-12-01 19:42
Can you add [HOLD awaiting payment [Date]] on this issue? Just came across it trying to clear out bugs that need more help.

**Comment by Puneet-here** [comment] 2022-12-01 19:48
It's ready for payment. It was deployed to production 8 days ago.

**Comment by JmillsExpensify** [comment] 2022-12-01 20:04
Even better. Let's issue payment and close this out!

**Comment by kevinksullivan** [comment] 2022-12-01 21:09
Paid @eVoloshchak for the C+ review and @Puneet-here for reporting + fixing.

**Closed by kevinksullivan** 2022-12-01 21:09 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by Puneet-here** [comment] 2022-12-01 21:19
@kevinksullivan, I think it's also eligible for 50% bonus because the PR was merged within 3 business days ( there was saturday and sunday in the middle )
<img width="897" alt="Screenshot 2022-12-02 at 2 49 16 AM" src="https://user-images.githubusercontent.com/101883770/205161338-d9c3d2b1-a706-4696-938e-6bce55389659.png">

**Comment by Puneet-here** [comment] 2022-12-05 11:58
bump @kevinksullivan

**Comment by kevinksullivan** [comment] 2022-12-06 22:32
Created a new job to pay out bonus

https://www.upwork.com/jobs/~0165757f92835a450f

@Puneet-here @eVoloshchak let me know once you've accepted. Thanks
