### ISSUE TITLE
Web - Bank Account - Dummy text/symbols accepted (Manual)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20133] opened 2023-06-03 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Desktop chrome and login and create a new workspace
2. Go to your workspaces > your workspace > Bank account > Connect manually
3. It will ask for bank account name and number. Enter Routing number. Enter 4 digit bank account number. It accepts minimum of 4 digits.
4. On the next page, enter symbols & texts at Legal Business name, company address and city as shown in the video
Click on save and continue. It will redirect you to next page.

## Expected Result:
1. Error while entering only 4 digits as bank account number
2. Error while entering symbols at Legal Business name, company address and city.
3. We should not have been able to save and continue to next page with all these possible errors and dummy symbols

## Actual Result:
1. NO Error message while entering only 4 digits as bank account number
2. NO Error message while entering symbols at Legal Business name, company address and city.
3. NO Error message while clicking on save and continue

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.23.6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/574f4760-50a1-4fba-a1d4-9b5f1da98296

https://github.com/Expensify/App/assets/93399543/44a498f7-eb90-4c55-950a-39573cf0e6bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** @av--shek-jha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685574028328809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment] 2023-06-08 01:40
I don't agree either of these are a bug. 

Bank account numbers can range in length, and a company could, potentially, have a name that is all symbols. Going to raise in Slack for consensus.

**Comment by arielgreen** [comment] 2023-06-08 17:32
Closing; discussed internally, this is not a bug.

**Closed by arielgreen** 2023-06-08 17:32 UTC
Labels: Daily, Bug
