### ISSUE TITLE
[$1000] Web - Delete Button Fails to Delete Changed Description in IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#25997] opened 2023-08-26 17:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on the plus sign and select "Request Money"
2. Enter desired amount and email address for Request Money
3. Open the IOU and change the description
4. Click on the three dots and select "Delete Request"
5. Observe that the Request is deleted, but the changed description remains in the IOU

## Expected Result:
The Delete button should delete the changed description from the IOU as well.

## Actual Result:
The Delete button fails to delete the changed description inside the IOU.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-17T112708.989.webm](https://github.com/Expensify/App/assets/93399543/6c11d6c7-3878-471a-b70b-1d88d087c6a0)

https://github.com/Expensify/App/assets/93399543/70e2dbeb-22bb-4292-933f-845225c9e5b4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692252491955339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01462271c6de352d0a</li>
        <li>Upwork Job ID: 1696152844806086656</li>
        <li>Last Price Increase: 2023-09-18</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-08-28 13:28
Was able to recreate, as shown in the screenshots below. Getting eyes on this!

<img width="1351" alt="Screenshot 2023-08-28 at 8 27 42 AM" src="https://github.com/Expensify/App/assets/10926327/027daf06-2545-4b65-a3af-be1e375a2dc0">
<img width="1351" alt="Screenshot 2023-08-28 at 8 27 52 AM" src="https://github.com/Expensify/App/assets/10926327/d5e5cb10-469b-48fe-af99-ee0a6aef449f">

**Comment by binary3oul** [comment] 2023-08-29 20:12
@Kbecciv, If a user deletes the request, should the corresponding item in the chat user list be deleted as well? 
If that is the case, then there is no need for us to fix it, correct?

**Comment by davewish** [comment] 2023-08-29 20:17
###  Proposal 

## Please re-state the problem that we are trying to solve in this issue.
 The Delete request  button fails to delete the changed description inside the IOU.

### What is the root cause of that problem?
The  transactionThread  is  deleted if  there are not visible  comments in thread . incase of ModifiedExpense  `actionName` and has  comment or message , hence `shouldDeleteTransactionThread` becomes   `false`
https://github.com/Expensify/App/blob/cf1d50ada102bfba344f83309b090606278f48b2/src/libs/actions/IOU.js#L1075-L1078

###  What changes do you think we should make in order to solve the problem?
we have to exclude  the  ModifiedExpense    from `visibleActions`  in  getLastVisibleAction ``
` const visibleActions = _.filter(actions, (action) => shouldReportActionBeVisibleAsLastAction(action) && !isModifiedExpense(action));`


### What alternative solutions did you explore? (Optional)
N/A

**Comment by carlosalmonte04** [comment] 2023-08-29 23:46
I think we should remove the reportActions of `actionName === "MODIFIEDEXPENSE"` instead of making them invisible. Keeping them will result in accumulating unnecessary data in the FE.

I also think deleting the change description actions alone will result in the FE adjusting the report to the desired experience.

**Comment by binary3oul** [comment] 2023-08-30 12:28
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Delete Button Fails to Delete Changed Description in IOU
### What is the root cause of that problem?
The actions with the name "MODIFIEDEXPENSE" have been included in the determination of the visibleActions list.
Please see [here](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportActionsUtils.js#L375)

### What changes do you think we should make in order to solve the problem?
To begin with, we need to follow these steps:

1. Press the F12 key.
2. Clear the contents of the following directory path: Application\IndexedDB\OnyxDB\keyvaluepairs.
3. After that, we have to update the filter logic on the specified [line](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/ReportActionsUtils.js#L375)with the following changes.
 `const visibleActions = _.some(actions, action => shouldReportActionBeVisibleAsLastAction(action)) ? [] : _.filter(actions, action => shouldReportActionBeVisibleAsLastAction(action));`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2023-08-30 17:11
I'll review the proposals in the morning, thanks!

**Comment by binary3oul** [comment] 2023-09-01 10:19
@mollfpr Please check my proposal. I resolved this issue for updating just one line.

**Comment by CortneyOfstad** [comment] 2023-09-01 15:45
@mollfpr Just checking to see if you had time to check the proposals? TIA!

**Comment by mollfpr** [comment] 2023-09-01 15:57
Hi @CortneyOfstad, I'm in the middle of testing the proposals now. For an update now, @davewish proposal is similar to what @dukenv0307 proposed.

, and for @binary3oul 

>Clear the contents of the following directory path: Application\IndexedDB\OnyxDB\keyvaluepairs.

I don't understand what this step has to do with the solution.

**Comment by mollfpr** [comment] 2023-09-01 16:08
@binary3oul I tried your solution, but it deletes the thread regardless of whether it only has a comment.

https://github.com/Expensify/App/blob/5db24452f475e51226be1d12ef5e8d47878d8879/src/libs/actions/IOU.js#L1075

The thread shouldn't be deleted.

**Comment by mollfpr** [comment] 2023-09-01 16:23
@dukenv0307 Could you elaborate on the solution for adding `shouldExcludeModifiedExpense`? I think, for now, we are good with handling the filter in `getLastVisibleAction` instead of passing the function as a parameter.

**Comment by binary3oul** [comment] 2023-09-01 18:43
@mollfpr  Thank you for your feedback.
If so, we can try with this line.

**Comment by binary3oul** [comment] 2023-09-02 13:33
@dukenv0307  [That ](https://github.com/Expensify/App/issues/25997#issuecomment-1702989190)is understandable.
I have found a solution to this problem.

I discovered that there is no calculation taking place when the action .actionName is "MODIFIEDEXPENSE." on [these lines](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/pages/home/report/ReportActionItem.js#L471-L529).

Simply, like this:  

![Screenshot 2023-09-02 082458](https://github.com/Expensify/App/assets/134395032/75f48bd1-da07-46af-a3a9-4f8479544e9c)
So, I added the following lines of code as shown below and solved this issue simply.

```
if (props.action.actionName === CONST.REPORT.ACTIONS.TYPE.MODIFIEDEXPENSE) {
        const parentReportAction = ReportActionsUtils.getParentReportAction(props.report);
        if(ReportActionsUtils.isDeletedAction (parentReportAction))
            return null;
   }
```
![Screenshot 2023-09-02 082841](https://github.com/Expensify/App/assets/134395032/82b52d65-77e0-4ad8-aca8-2d9337d7e800)

**Comment by binary3oul** [comment] 2023-09-02 13:42
@dukenv0307  [That ](https://github.com/Expensify/App/issues/25997#issuecomment-1702989190)is understandable.
I have found a solution to this problem.

I discovered that there is no calculation taking place when the action .actionName is "MODIFIEDEXPENSE." on [these lines](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/pages/home/report/ReportActionItem.js#L471-L529).

Simply, like this:  

![Screenshot 2023-09-02 082458](https://github.com/Expensify/App/assets/134395032/75f48bd1-da07-46af-a3a9-4f8479544e9c)
So, I added the following lines of code as shown below and solved this issue simply.

```
if (props.action.actionName === CONST.REPORT.ACTIONS.TYPE.MODIFIEDEXPENSE) {
        const parentReportAction = ReportActionsUtils.getParentReportAction(props.report);
        if(ReportActionsUtils.isDeletedAction (parentReportAction))
            return null;
   }
```
![Screenshot 2023-09-02 082841](https://github.com/Expensify/App/assets/134395032/82b52d65-77e0-4ad8-aca8-2d9337d7e800)

**Comment by binary3oul** [comment] 2023-09-04 12:02
@mollfpr Would you kindly take a look at my [updated proposal](https://github.com/Expensify/App/issues/25997#issuecomment-1699075435)? 
I have resolved the issue by adding a few lines.

**Comment by mollfpr** [comment] 2023-09-04 17:19
Thanks @bernhardoj 

I agree. The report should be deleted from BE, too, so it won't be accessible.

@CortneyOfstad Could you help confirm if the thread should be deleted when there are only modified actions in the thread?

If yes, I think we can separate that into another issue internally.

---

>If it's desirable to delete all MODIFIEDEXPENSE actions even though there're other non-MODIFIEDEXPENSE actions in the list, we can remove them in the optimisticData [here](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/libs/actions/IOU.js#L1136C25-L1136C25) as well.

>The back-end will need to be fixed similarly

@dukenv0307 Are you suggesting updating the BE to delete the report?

---

![Screenshot 2023-09-05 at 00 18 37](https://github.com/Expensify/App/assets/25520267/0986aecc-9379-4812-ad95-23ca3fba29b9)

@binary3oul Your solution will not display the actions `MODEFIEDEXPENSE` even though the thread has a message. It's only showing the message `Hi`.

![Screenshot 2023-09-05 at 00 19 24](https://github.com/Expensify/App/assets/25520267/9b3cfdea-bd56-4380-b6e9-316a3019de98)

**Comment by binary3oul** [comment] 2023-09-04 17:28
@mollfpr  Do you mean that User icon and  **Assignee Task** are missing?
![265517047-0986aecc-9379-4812-ad95-23ca3fba29b9](https://github.com/Expensify/App/assets/134395032/9cb5d604-a2c1-46af-9191-e88fd5ada35a)

**Comment by mollfpr** [comment] 2023-09-04 17:33
Yes, and also the message `set the description to...`. If there's no message in the thread, but only the modified actions, it should be deleted from the thread. Similar to deleting a request when there's no message or update on the request.

**Comment by binary3oul** [comment] 2023-09-04 18:02
Please check the following:

`children = <ReportActionItemBasicMessage message={ReportActionsUtils.isDeletedAction (ReportActionsUtils.getParentReportAction(props.report)) ? null : ReportUtils.getModifiedExpenseMessage(props.action)} />;`

instead of 

`children = <ReportActionItemBasicMessage message={ReportUtils.getModifiedExpenseMessage(props.action)} />;`

in [this line](https://github.com/Expensify/App/blob/64ff471fc614a57645edf34b5d2ac346046f12c1/src/pages/home/report/ReportActionItem.js#L327)

**Comment by binary3oul** [comment] 2023-09-04 18:58
@mollfpr Please check the [my update](https://github.com/Expensify/App/issues/25997#issuecomment-1705586668).

**Comment by mollfpr** [comment] 2023-09-05 12:05
@binary3oul We still need to show the action for modifying the request. Your RCA needs to be corrected. This issue concerns the thread not being deleted when there are only actions to modify the request, but your solution only filters the actions.

---

@tsa321 I think we can do that. It is working well. But it's not working. Do the full flow and delete while offline.

1. Make the app offline
2. Create request money, open the IOU preview and the IOU thread
3. Send a message
4. Delete the request
5. The thread and IOU preview shouldn't deleted

https://github.com/Expensify/App/assets/25520267/baf6acac-e395-4620-a458-9e216b503cd2

Also, what's your suggestion for the BE changes?

**Comment by binary3oul** [comment] 2023-09-05 14:16
@mollfpr

Do you mean that there should be filtering both of thread and actions?

**Comment by binary3oul** [comment] 2023-09-05 14:53
I understand it. 
Once the thread is deleted, where will the page be redirected to?

**Comment by mollfpr** [comment] 2023-09-06 00:54
@tsa321 The behavior should be the same with deleting the request on online.

**Comment by mollfpr** [comment] 2023-09-07 05:03
@tsa321 In your solution, you pass the `transactionID` to `ReportActionsUtils.hasCommentThread`, but the function accepts the report action. Is that intended?

**Comment by mollfpr** [comment] 2023-09-08 14:12
Sorry, I didn't get the time to review this issue. I'll get back tomorrow morning 🙏

**Comment by CortneyOfstad** [comment] 2023-09-11 15:05
Not overdue, as @mollfpr will be reviewing 👍

**Comment by mollfpr** [comment] 2023-09-13 12:00
I'm getting out of track with this issue.

@CortneyOfstad I have to clarify this, Is this issue regarding the message on updating the fields not removed, or the IOU thread is not deleted?

**Comment by mollfpr** [comment] 2023-09-18 10:33
Friendly bump @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2023-09-21 15:38
Sorry @mollfpr! The issue is that the when the request is deleted, the description field still lingers behind. When deleting the request, the description details should be removed as well. Hopefully that clears it up!

**Comment by CortneyOfstad** [comment] 2023-09-25 13:45
Any updates @mollfpr? TIA!

**Comment by mollfpr** [comment] 2023-09-25 15:36
@tsa321 I might be misinterpreting the clarification, but @CortneyOfstad doesn't say anything about deleting the thread. Also, this aligns with the response from the BE where the report is not deleted.

**Comment by mollfpr** [comment] 2023-09-28 17:24
@dukenv0307 Do you know why the report actions message doesn't clear immediately after deleting the request?


https://github.com/Expensify/App/assets/25520267/17abecfa-b99e-4464-8400-99215338a4f1

@CortneyOfstad Can we get the `External` label back? Thanks!

**Comment by mollfpr** [comment] 2023-10-02 14:35
>It's because the report actions list itself were not updated (just that the thread is now deleted so those actions should be filtered out), so the list doesn't rerender.

@dukenv0307 You have the solution for the offline issue with your proposal?

Could you attach a video for the offline case? I might be applying your solution wrong.

**Comment by CortneyOfstad** [comment] 2023-10-05 13:19
@mollfpr bump on the comment above ^^^

**Comment by mollfpr** [comment] 2023-10-05 19:14
Thanks @dukenv0307, for the update.

>When deleting the request, the description details should be removed as well.

From the above-expected result, the [proposal](https://github.com/Expensify/App/issues/25997#issuecomment-1735874400) from @dukenv0307 looks good to me.

@CortneyOfstad Could you help add the label again, thanks!

🎀 👀 🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment] 2023-10-09 13:25
> @CortneyOfstad Could you help add the label again, thanks!

Sorry @mollfpr for my confusion, but which label needs to be added again? Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-18 19:55
I'm heading OoO until Oct. 25, so reassigning BZ to keep an eye on this while I'm gone 👍

**Comment by CortneyOfstad** [comment] 2023-10-18 19:56
NO MELVINBOT 🙃

**Comment by CortneyOfstad** [comment] 2023-10-25 17:04
Thanks @maddylewis!!

**Comment by CortneyOfstad** [comment] 2023-10-31 14:18
@mollfpr any updates on the PR review? Thanks!

**Comment by mollfpr** [comment] 2023-11-02 13:16
@CortneyOfstad The PR is still under review, and the result still does not meet the expected result.

**Comment by CortneyOfstad** [comment] 2023-11-06 15:37
Thanks @mollfpr — keep me posted if anything changes. Thank you!

**Comment by CortneyOfstad** [comment] 2023-11-17 16:20
@mollfpr any updates? TIA!

**Comment by jasperhuangg** [comment] 2023-11-29 23:44
bump! @mollfpr

**Comment by CortneyOfstad** [comment] 2023-12-22 14:08
@mollfpr update on the PR? Thank you!

**Comment by jasperhuangg** [comment] 2024-01-02 04:17
The linked PR is still under view. https://github.com/Expensify/App/pull/28995

Some changes have occurred to the associated back-end behavior, so the PR has had to be updated accordingly.

**Comment by CortneyOfstad** [comment] 2024-01-02 15:51
Thanks @jasperhuangg!

**Comment by mollfpr** [comment] 2024-01-06 08:42
@CortneyOfstad This specific issue is not reproducible anymore because the thread report is now deleted when it has no chat message.

![Screenshot 2024-01-06 at 15 37 24](https://github.com/Expensify/App/assets/25520267/613dc158-ac51-49f8-b485-a5869d88a88c)

We still show the edit expense message after the request is deleted. I don't know if this was intended, but I remember not showing the message before.


cc @jasperhuangg @dukenv0307

**Comment by jasperhuangg** [comment] 2024-01-08 03:21
I asked for clarification on how to proceed, will let you know what the decision is.

**Comment by jasperhuangg** [comment] 2024-01-17 15:41
a PR isn't necessary here anymore, but @dukenv0307 and @mollfpr have spent a considerable amount of time with investigating this issue. Even though we didn't end up merging any code, I think we should move ahead with paying them out for the time they've spent on this.

@CortneyOfstad can we be sure that this happens?

**Comment by CortneyOfstad** [comment] 2024-01-17 15:54
@jasperhuangg I think that would be fair. Do you have a price in mind? Or would you be more comfortable opening it up to the BZ for a broader discussion?

**Comment by jasperhuangg** [comment] 2024-01-17 16:02
I already posted [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1704683936633799) in BZ without any response yet.

Definitely think we should see if we can get some more eyes on that thread.

**Comment by mallenexpensify** [comment] 2024-01-23 00:46
For https://github.com/Expensify/App/issues/27570#issuecomment-1831506981
> A proposal was https://github.com/Expensify/App/issues/27570#issuecomment-1754831233 and while implementing the https://github.com/Expensify/App/pull/29259, it was decided that the issue would be best solved on the backend.

and our internal doc states
> We also pay 100% to the contributor and C+ if we hired them then decided to fix the issue internally or close the issue (assuming the contributor and C+ were both actively working on the issue).

This issue is different because we didn't make a decision to fix it on the backend. 

For https://github.com/Expensify/App/issues/30692#issuecomment-1873639393
Both Jasper and Vivek agreed to close the issue, so that's also different than issue and also fits with the stated guideline above. 

Part of what leads me to believe 50% is fair is because the hire date was [Oct 5](https://github.com/Expensify/App/issues/25997#event-10567814603) and the PR was still being worked on as of [Dec 28th](https://github.com/Expensify/App/pull/28995#issuecomment-1871723122) and there were multiple bumps to move the PR along.  If this PR would have been merged before the one that fixed it, would it have _made a difference_? (I don't know).  If so, then we could have saved time both working on this one AND the other by closing them both sooner.  

We appreciate and value the time and investment, our main goal is to get bugs fixed and to do it with urgency, which is what I consider the a benchmark for similar issues like there where another PR (appears to) magically fix the bug (from what I know, I'm not the most well versed on this specific issue or PR)

**Comment by mallenexpensify** [comment] 2024-01-26 00:23
Thanks @dukenv0307 , we're discussing internally.

**Comment by jasperhuangg** [comment] 2024-01-26 01:49
@dukenv0307 @mollfpr Thank you for your patience with this matter. We've discussed this internally and have decided to keep full payment on your work considering the sheer amount of time and effort you've put into implementation and review. Thank you for sticking with it, we really appreciate your hard work!

**Comment by jasperhuangg** [comment] 2024-01-29 19:06
@CortneyOfstad can you help with issuing payment here?

**Comment by CortneyOfstad** [comment] 2024-01-29 19:20
Created a new Job post here — https://www.upwork.com/jobs/~016e3532aa6b8d64fd

@dukenv0307 sent you a proposal in Upwork

@mollfpr you'll be paid via NewDot — I'll create the proposal once Duc accepts in Upwork 👍

**Comment by tewodrosGirmaA** [comment] 2024-01-30 15:13
@CortneyOfstad @jasperhuangg May I inquire about my eligibility for compensation regarding the bug report? Thank you.

**Comment by mallenexpensify** [comment] 2024-01-30 23:51
ah.. yes, @tewodrosGirmaA you are eligible since this was reported forever ago, ha. Amount is $250 because[ it was before the decrease to $50. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649). 
@CortneyOfstad can you pay out plz?

**Comment by CortneyOfstad** [comment] 2024-01-31 13:43
Sorry about that @tewodrosGirmaA! I sent you a proposal in Upwork — let me know once you accept and I'll get that paid ASAP. Thanks!

**Comment by tewodrosGirmaA** [comment] 2024-01-31 13:58
Hello @CortneyOfstad  i accept it , Thank you

**Comment by CortneyOfstad** [comment] 2024-01-31 14:20
## Payment Summary

@tewodrosGirmaA (reporter) — paid $250 via Upwork
@dukenv0307 (contributor) — paid $1000 via Upwork
@mollfpr  (C+) — to be paid $1000 via NewDot

**Comment by tewodrosGirmaA** [comment] 2024-01-31 14:21
Thank you @CortneyOfstad

**Closed** 2024-01-31 14:21 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2024-01-31 15:21
$1,000 approved for @mollfpr for based on summary above.
