### ISSUE TITLE
[$250] Expense - User invited to the expense report can hold the expenses

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48306] opened 2024-08-29 23:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4901045
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit two expenses to User B
3. [User A] Click on the expense preview in the main chat to go to expense report
4. [User A] Send a user mention containing User C
5. [User A] Click Invite from the whisper message
6. [User A] Send a message in the transaction thread
7. [User C] Open the invited expense report
8. [User C] Click on any expense.
9. [User C] Click on the header > Hold.
10. [User C] Hold the expense.

## Expected Result:
Invited user (User C) should not be able to hold the expenses.

## Actual Result:
Invited user can hold the expenses.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cffc3706-c7d8-459f-a681-09cd59a9ce71

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831812891788709823</li>
        <li>Upwork Job ID: 1831812891788709823</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by IuliiaHerets** [comment] 2024-08-29 23:16
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by raza-ak** [comment] 2024-09-06 15:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - User invited to the expense report can hold the expenses
### What is the root cause of that problem?
The problem arises because the system currently does not properly verify if the logged-in user is the same as the creator of the expense. This results in users who did not create the expense being able to access or hold it, violating access control rules.
### What changes do you think we should make in order to solve the problem?

To fix this issue, we need to update the function responsible for opening the "hold" modal. The change will ensure that access is granted only if the email of the logged-in user matches the email of the user who created the expense.The following changes in the component should resolve the issue:Update Access Logic: Modify the function that handles opening the hold modal to verify that the logged-in user's email matches the expense creator's email (reportAction.email).Conditional Access: Implement conditional logic to ensure that only users with matching emails are allowed to proceed.
Following changes will fix the issue:
![IMG-20240906-WA0001](https://github.com/user-attachments/assets/bb471764-6ba7-46e9-874b-78e4bce86e1d)

Uploading 365193203-876ce5fa-0b1b-4b19-b67a-54cfeeb9fef0 (1).mp4…

**Comment by abekkala** [comment] 2024-09-09 19:13
@abdulrahuman5196 can you please review the proposal?

**Comment by abdulrahuman5196** [comment] 2024-09-11 18:17
Checking now

**Comment by abdulrahuman5196** [comment] 2024-09-17 19:10
Sorry for the delay. Checking now.

**Comment by abdulrahuman5196** [comment] 2024-09-17 19:49
@abekkala The backend API to hold/unhold is also passing. @Krishna2323 solution could fix the problem in frontend but still for backend we need internal fix. Could you loop in internal engineer for this issue?

**Comment by abekkala** [comment] 2024-09-20 16:13
Looks like we'll need an internal fix first

**Comment by abekkala** [comment] 2024-09-25 19:31
we need an internal fix first

**Comment by abekkala** [comment] 2024-09-27 18:09
waiting on internal - `internal` and `hot pick` applied

**Comment by abdulrahuman5196** [comment] 2024-10-02 16:43
>I think we can make the frontend changes first since they are not entirely related to the backend changes. WDYT?

Yes. I agree we can make both frontend and backend changes in parallel. Still we would need a engineer to approve that? That's why wanted to get eyes from internal engineer on this.

**Comment by abekkala** [comment] 2024-10-02 17:57
@Krishna2323 

> I think we can make the frontend changes first since they are not entirely related to the backend changes. WDYT?

> Yes. I agree we can make both frontend and backend changes in parallel. Still we would need a engineer to approve that? That's why wanted to get eyes from internal engineer on this.

yes, this is correct. We are waiting for an Internal eng. to pick this one up

**Comment by abekkala** [comment] 2024-10-08 18:34
Not sure why the hot pick label didn't put it in that status??

**Comment by abekkala** [comment] 2024-10-09 18:40
still waiting for an internal pick up on this one

**Comment by abekkala** [comment] 2024-10-11 14:18
@OfstadC 

### STATUS: this is an `Internal` / `Hot Pick` - still waiting on someone to pick up for fix. I'm not sure there will be much movement in one week.

**Comment by abdulrahuman5196** [comment] 2024-10-17 13:06
still waiting for pick up

**Comment by abekkala** [comment] 2024-10-21 12:52
I'm back from ooo - unassigning @OfstadC

**Comment by abekkala** [comment] 2024-10-24 13:00
@Krishna2323 no, hot picks require an internal engineer volunteer to pick up (typically someone who would be familiar with the feature) vs. an engineer being auto assigned.

**Comment by abekkala** [comment] 2024-11-06 19:50
still waiting on internal pick up

**Comment by mvtglobally** [comment] 2024-11-16 01:52
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-11-29 04:21
Issue not reproducible during KI retests. (Second week)

**Comment by abekkala** [comment] 2024-12-04 18:27
I'll wait until the 3rd week of attempted retest before closing

**Comment by mvtglobally** [comment] 2024-12-07 05:07
Issue not reproducible during KI retests. (Third week)

**Closed** 2024-12-11 14:20 UTC
Labels: Monthly, Internal, Help Wanted, Bug, Hot Pick

**Comment by abdulrahuman5196** [comment] 2024-12-17 07:53
>If a contributor has been hired for a job and we decide to close the job before it is successfully completed
50% payment to contributor and C+ if the contributor was 🎀👀🎀 by a C+ or hired/assigned. 


@abekkala I think this issue should be partially compensated since were already having an approved proposal but waiting on internal engineer assignment - https://github.com/Expensify/App/issues/48306#issuecomment-2389284535.

**Comment by abdulrahuman5196** [comment] 2024-12-17 07:54
Sorry @mjasikowski,  I think the melvin bot wrongly assigned you since the c+ approved emoji was present

**Comment by abdulrahuman5196** [comment] 2024-12-25 14:48
> > If a contributor has been hired for a job and we decide to close the job before it is successfully completed
> > 50% payment to contributor and C+ if the contributor was  by a C+ or hired/assigned.
> 
> @abekkala I think this issue should be partially compensated since were already having an approved proposal but waiting on internal engineer assignment - [#48306 (comment)](https://github.com/Expensify/App/issues/48306#issuecomment-2389284535).

@abekkala Gentle ping on this

**Comment by abekkala** [comment] 2025-01-09 17:00
paying @Krishna2323 $125 via upwork 
[Offer](https://www.upwork.com/nx/wm/offer/105627736)

**Comment by abekkala** [comment] 2025-01-09 17:02
Paid! 🎉 
Thanks @Krishna2323

**Comment by abdulrahuman5196** [comment] 2025-01-13 17:50
@abekkala Could you also kindly provide payment summary for me as C+ so that I can request in new dot.

**Comment by abekkala** [comment] 2025-03-10 12:52
### PAYMENT SUMMARY

- @abdulrahuman5196 [$125] paid via NewDot

**Comment by JmillsExpensify** [comment] 2025-03-10 16:41
$125 approved for @abdulrahuman5196
