### ISSUE TITLE
[HOLD for payment 2023-09-12] [$500] DEV: Distance merchant being applied to any kind of request

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#26600] opened 2023-09-03 10:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Break down in numbered steps

1. go to fab button -> request money ->scan
2. click on choose any file
3. select a jpg file
4. now click on show more and notice on Merchant there shows "0.00 miles @ $0 / mile".

## Expected Result:
Describe what you think should've happened

Merchant should show Request.

## Actual Result:
Describe what actually happened

Merchant there shows "0.00 miles @ $0 / mile".

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** dev
**Reproducible in staging?:** n
**Reproducible in production?:** n 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693732474765259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e00cf547fa834fe</li>
        <li>Upwork Job ID: 1698289132659306496</li>
        <li>Last Price Increase: 2023-09-03</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-09-03 10:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
This happens because we set merchant here in useEffect - 

https://github.com/Expensify/App/blob/9661a4b446884177760940ea6c30a58de32eb716/src/components/MoneyRequestConfirmationList.js#L295-L298

### What changes do you think we should make in order to solve the problem?
We shall add the check if request is distance request or not.
```js
    useEffect(() => {
        if (!props.isDistanceRequest) return;
        IOU.setMoneyRequestMerchant(distanceMerchant);
    }, [distanceMerchant, props.isDistanceRequest]);
```

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-09-03 10:58
@BhuvaneshPatil I have already handled this internally, thanks

**Comment by BhuvaneshPatil** [comment] 2023-09-03 10:59
oh, that's great. Was this fix right?(just asking if I was able to figure that out)

**Comment by mountiny** [comment] 2023-09-03 11:00
Yes 🚀

**Comment by ashimsharma10** [comment] 2023-09-13 14:56
Waiting for payment. Thanks!

**Comment by michaelhaxhiu** [comment] 2023-09-15 18:33
@ashimsharma10 did you apply to the upwork job by the way?

**Comment by ashimsharma10** [comment] 2023-09-16 02:39
@michaelhaxhiu Can you please send me offer directly. 
Profile : https://www.upwork.com/freelancers/~018a92cf13e1e88eed
Running out of upwork connects.

**Comment by michaelhaxhiu** [comment] 2023-09-18 00:21
mkay i sent a direct offer here https://www.upwork.com/nx/wm/offer/26722640

**Comment by michaelhaxhiu** [comment] 2023-09-18 00:22
bug was reported on sept 3, which is when the new bug bonus rate took effect. That price is what was used in the job link above

**Comment by michaelhaxhiu** [comment] 2023-09-19 18:01
Bug reporter: $50 to @ashimsharma10 (paid)
C+ work: $500 @allroundexperts 
Contributor: n/a @mountiny  did it

@allroundexperts can you request payment in newdot please and confirm here when it's done?

**Comment by michaelhaxhiu** [comment] 2023-09-21 18:32
Thanks 👍. Will close when we get notice here that you were paid.

**Comment by mountiny** [comment] 2023-09-25 14:14
making this weekly then

**Comment by michaelhaxhiu** [comment] 2023-09-28 13:54
I'm re-assigning this to another BZ as part of my preparation for Sabbatical (starting Friday).

**Next steps:**
- Wait for @allroundexperts confirms payment was handled via newDot, then close this.

**Comment by MitchExpensify** [comment] 2023-09-29 07:38
I believe we close when all that is left is NewDot payment according to https://stackoverflowteams.com/c/expensify/questions/16949

**Closed by MitchExpensify** 2023-09-29 07:38 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 13:02
$500 payment approved for @allroundexperts based on BZ summary.
