### ISSUE TITLE
[HOLD for payment 2024-03-14] [$500] iOS - Photos - Error message displayed even though the image has been downloaded

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36870] opened 2024-02-20 11:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/36154

**Version Number:** v1.4.43-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** vdargentotest+web021924@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: on the device settings, photos access should be set to "Add Photos Only" for New Expensify app. To do this, first set it to None, go to the app and try to download an image, it will request you to change the privacy settings, redirecting you to the settings page and the option should show up.

1. Go to any chat with an image.
2. Hold onto an image in the chat and select "Download".
3. Verify an error message is displayed.

## Expected Result:
A message saying that the file was successfully downloaded should be displayed.

## Actual Result:
An error message is displayed, but the image is actually downloaded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/00ac9b20-5628-4ac2-803f-0dabe7baaa5b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be2c326a20f0e643</li>
        <li>Upwork Job ID: 1759903796285509632</li>
        <li>Last Price Increase: 2024-02-20</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>shahinyan11 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-20 11:33
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by shahinyan11** [comment] 2024-02-20 12:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Photos - Error message displayed even though the image has been downloaded
### What is the root cause of that problem?
It is the `@react-native-camera-roll/camera-roll` package error and only accuses when the `Photo library access` permission is set `Add photos only` . I we set `Full access` it will not happen 
### What changes do you think we should make in order to solve the problem?
Do the changes in [this](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/575#issuecomment-1906102209) comment  and patch the package

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-02-20 15:07
## Proposal
[Updated](https://github.com/Expensify/App/issues/36870#issuecomment-1954158785)

**Comment by shahinyan11** [comment] 2024-02-20 15:28
For uploading vide we have another [downloadVideo](https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/libs/fileDownload/index.ios.ts#L38C10-L38C23) function . Why you need to see it ?

**Comment by mollfpr** [comment] 2024-02-20 17:39
@shahinyan11 I try your proposal but the error message still shown.

https://github.com/Expensify/App/assets/25520267/cb132bd3-7453-4d07-a8a9-67611e68dfe9

**Comment by shahinyan11** [comment] 2024-02-20 18:29
## Proposal
[Updated](https://github.com/Expensify/App/issues/36870#issuecomment-1954158785)

**Comment by shahinyan11** [comment] 2024-02-20 18:31
@mollfpr I updated the application proposal try again

**Comment by mollfpr** [comment] 2024-02-21 13:12
@shahinyan11 I believe your solution is from the workaround here https://github.com/react-native-cameraroll/react-native-cameraroll/issues/575.

**Comment by shahinyan11** [comment] 2024-02-21 13:22
> @shahinyan11 I believe your solution is from the workaround here [react-native-cameraroll/react-native-cameraroll#575](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/575).

@mollfpr  Yes

**Comment by shahinyan11** [comment] 2024-02-22 11:04
## Proposal
[Updated](https://github.com/Expensify/App/issues/36870#issuecomment-1954158785). Added new solution as a main

**Comment by mollfpr** [comment] 2024-02-22 17:40
Thanks @shahinyan11! I downgraded the package and it's fixed the issue! Do you what's fixed on that version?

I still have doubts tho on downgrading. The current version seems pretty important to use the new arch for the package.

https://github.com/Expensify/App/issues/35986

**Comment by shahinyan11** [comment] 2024-02-22 19:03
@mollfpr The version was updated from `5.4.0`  to `7.4.0`.  Maybe the `7.2.2` version also suits the new arch. 
Anyway  I proposed 2 different solutions. You can choose what to use .

**Comment by shahinyan11** [comment] 2024-02-23 14:24
@mollfpr The package has been actively updated in recent days. I tested the latest version added today but the error still exists. But I think sooner or later a version will be published that will contain something like this
> 
> ```
> if (![createdAsset isKindOfClass:[PHAsset class]]) {
>   resolve(@{
>     @"node": [NSNull null]
>   });
>   return;
> }
> ```

**Comment by mollfpr** [comment] 2024-02-23 15:15
>Maybe the 7.2.2 version also suits the new arch.

@shahinyan11 I'm not sure about this. You can check the commit https://github.com/react-native-cameraroll/react-native-cameraroll/commit/7c15ac856aa21cf4c1828950e684f42497f2ce58

>Use CameraRoll.saveAsset instead CameraRoll.save [here](https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/libs/fileDownload/index.ios.ts#L32C23-L32C27). The save method is deprecated and it is mentioned in package codes. [here](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/8a8f55c8ebc0fd02d8796858a770f43a2f943524/src/CameraRoll.ts#L231C1-L235C6)

Your suggestion to use `saveAsset` instead is on function `downloadImage`, and while we use `downloadVideo` for the download action.

**Comment by mollfpr** [comment] 2024-02-23 16:09
I tried the patch and updated the `downloadVideo` function to use `CameraRoll.saveAsset`, and it shows the successful download alert. My only concern is, that the value return from `CameraRoll.saveAsset` is `{"node": null}`.

I was expecting that the return would be full asset information.

https://github.com/react-native-cameraroll/react-native-cameraroll?tab=readme-ov-file#saveasset

**Comment by shahinyan11** [comment] 2024-02-23 16:27
> Your suggestion to use `saveAsset` instead is on function `downloadImage`, and while we use `downloadVideo` for the download action.

Sorry but i do not understand  you here. We us [downloadImage](https://github.com/Expensify/App/blob/669ac330b4eeaad2238419bdb501811d3e031e13/src/libs/fileDownload/index.ios.ts#L78C1-L88C10) for images and `downloadVideo`

**Comment by shahinyan11** [comment] 2024-02-23 16:41
> I tried the patch and updated the `downloadVideo` function to use `CameraRoll.saveAsset`, and it shows the successful download alert. My only concern is, that the value return from `CameraRoll.saveAsset` is `{"node": null}`.

@mollfpr  And what do you think. what would be the right thing to do

**Comment by mollfpr** [comment] 2024-02-23 18:38
@shahinyan11 The documentation doesn't explain what the above result means. Our current implementation is expecting a value _string_ or _null_ from `CameraRoll.save`. The _string_ value should be the URI of the created asset. While the above result with `CameraRoll.saveAsset` is mostly null, so we don't have information on the URI.

So we need to have a confirmation that the `CameraRoll.saveAsset` returning `{"node": null}` while the asset save in the galery is expected, then we can moving forward we the implementation.

**Comment by shahinyan11** [comment] 2024-02-24 09:20
@mollfpr The cause of returning `{"node": null}` is not `saveAssets` function. It comes from our implementation .
```
if (![createdAsset isKindOfClass:[PHAsset class]]) {
  resolve(@{
    @"node": [NSNull null]
  });
  return;
}
```

**Comment by mollfpr** [comment] 2024-02-26 06:32
@shahinyan11 You are right!

The alternative solution from @shahinyan11 [proposal](https://github.com/Expensify/App/issues/36870#issuecomment-1954158785) looks good!

🎀 👀 🎀 C+ reviewed!

**Comment by thienlnam** [comment] 2024-02-26 17:34
Sounds good to fix the blocker we currently have, in addition @mollfpr Could you please raise an issue in the repo so that we can get this fixed for the community as well and re-bump this in the future?

**Comment by thienlnam** [comment] 2024-02-26 19:47
I downgraded the version so we can unblock deploy, but I'm reopening as we still want to upgrade this version so we unblock the New Arch upgrade

**Comment by mollfpr** [comment] 2024-03-14 13:16
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

The issue arise after https://github.com/Expensify/App/pull/36154 is merged but mainly the main issue is on the upstream library. So we decided to patch the latest version `react-native-camera-roll` to quickly fix it.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

I think the regression test is enough here.

> [@mollfpr] Determine if we should create a regression test for this bug.
[@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

We already have the test case for downloading an image https://expensify.testrail.io/index.php?/cases/view/2644131. I'm suggesting we add one more verification on the last point for the native platform.

13. **Verify** the success message is displayed in iOS/Android.

**Comment by mollfpr** [comment] 2024-03-14 13:17
@mallenexpensify Could you give the payment summary? Thank you!

**Comment by shahinyan11** [comment] 2024-03-15 18:28
@mallenexpensify  Could you please send payment ?

**Comment by mallenexpensify** [comment] 2024-03-15 23:52
Contributor: @shahinyan11 paid $500 via Upwork
Contributor+: @mollfpr owed $500 via NewDot

TR Update GH https://github.com/Expensify/Expensify/issues/379569
Thanks y'all.

**Closed by mallenexpensify** 2024-03-15 23:52 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-18 15:01
$500 approved for @mollfpr based on summary.
