### ISSUE TITLE
[$500] New Group - Default icon displayed after creating a Group Chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8573] opened 2022-04-09 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com
2. Log in with expensifail account
3. Tap on Fub menu - Select New Group
4. Select a few users and tap Create Group

## Expected Result:
User icons displayed when creating Group Chat

## Actual Result:
Default icon displayed after creating a Group Chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android
- Desktop App

**Version Number:** 1.1.54.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+033122abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/162551406-d305f52e-860c-4a39-9328-d17133dc0f1b.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bondydaa** [comment] 2022-04-11 21:21
the expected result and actual result are the same in the OP. 

I'm not familiar enough to know which icon should be shown so if we know which icon it is can we make sure it's stated which one? pretty sure this is external.

**Comment by mallenexpensify** [comment] 2022-04-11 21:55
@kbecciv, the actual and expected are the same in the OP, can you update please?  I'll post the job after.

**Comment by kbecciv** [comment] 2022-04-11 22:15
@mallenexpensify Sorry about that, updated!

**Comment by mallenexpensify** [comment] 2022-04-12 01:38
Thanks @kbecciv !
Job posted https://www.upwork.com/jobs/~01139053e67fc42e9e

**Comment by mountiny** [comment] 2022-04-12 17:37
@kbecciv Do you have an illustration/mock up of how it should look like? I assume you should have if that is a QA step, but otherwise we can ask the design team.

**Comment by mountiny** [comment] 2022-04-12 17:57
Just good to show this to contributors, who should work on it.

Feels like this is a regression, however, from a previous versions as the issue suggests this is already in production.

A good hint to look into the previous PRs which most likely caused this.

**Comment by mountiny** [comment] 2022-04-14 20:24
I am going ooo for 5 weeks so I am re-assigning some CME issues assigned to me. This one still awaits a proposal! Thank you for your help @iwiznia!

**Comment by mallenexpensify** [comment] 2022-04-20 16:24
Doubled price to $500
https://www.upwork.com/jobs/~01139053e67fc42e9e

**Comment by rushatgabhane** [comment] 2022-04-26 01:44
@Expensify/contributor-plus wanna pick this up? I'll be OOO because school exams 📖👨‍🏫
No proposals yet

**Comment by mananjadhav** [comment] 2022-04-30 21:55
Waiting for proposals.

**Comment by mvtglobally** [comment] 2022-05-03 03:53
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2022-05-04 22:07
Going to wait to double since @mvtglobally wasn't able to reproduce. I just tried on web and wasn't able to reproduce (web wasn't mentioned in the list of platforms though...)

**Comment by mvtglobally** [comment] 2022-05-10 04:28
Issue not reproducible during KI retests. (Second week)

**Comment by mananjadhav** [comment] 2022-05-12 18:34
@mallenexpensify Are we good to close this? Second week and issue not reproducible.

**Comment by michaelhaxhiu** [comment] 2022-05-12 23:20
Good call, let's close @mananjadhav

**Closed by michaelhaxhiu** 2022-05-12 23:20 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
