### ISSUE TITLE
[HOLD for Payment 2024-10-4][$250] Profile - There is tooltip for Profile Share button but no tooltip for Workspace Share button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#48418] opened 2024-09-02 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile
3. Hover over Share button
4. Note that there is a tooltip
5. Go to any workspace > Profile
6. Hover over Share button
7. Note that there is no tooltip

## Expected Result:
In Step 4 and 7, there should be consistency whether tooltip is required for Share code button

## Actual Result:
There is tooltip when hovering over Share button in Profile page (Step 4), but there is no tooltip when hovering over Share button in Workspace Profile page
The font used in Profile Share button is also larger than Workspace Profile Share button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a449f9d7-4d03-4755-9620-5c3a1708017d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df3c5b108dfdd9f0</li>
        <li>Upwork Job ID: 1831003804836352528</li>
        <li>Last Price Increase: 2024-09-03</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 103918746</li>
<li>Krishna2323 | Contributor | 103918747</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by lanitochka17** [comment] 2024-09-02 16:52
@zanyrenney  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by haris-ali9211** [comment] 2024-09-03 21:58
# Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is no tooltip for the Workspace Share button as there is for the Profile Share button.

### What is the root cause of that problem?

The previous implementation did not include a tooltip for the Workspace Share button. When attempting to directly wrap the `Button` component with a `Tooltip`, it did not work correctly due to the `Button` component's structure, which returns sibling elements. Tooltips require a single child element, causing the tooltip to malfunction.

### What changes do you think we should make in order to solve the problem?

To address this issue, We can add a `PressableWithFeedback` component wrapped with the `Tooltip` instead of directly applying the tooltip to the `Button`. The `PressableWithFeedback` component allows for the required flexibility, ensuring the tooltip functions correctly while maintaining the intended button behavior and styling. The same approach was applied to the Delete button for consistency.

<div style="border: 1px solid #444; padding: 10px; border-radius: 5px; background-color: #222;">
  <strong>File:</strong> <a href="https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceProfilePage.tsx">App/src/pages/workspace/WorkspaceProfilePage.tsx</a><br>
  <strong>Line:</strong> 274 to 291
</div>
<br/>

```jsx
<View style={[styles.flexRow, styles.mt6, styles.mnw120, styles.gap2]}>
    <Tooltip text={translate('common.shareCode')}>
        <PressableWithFeedback
            accessibilityLabel={translate('common.shareCode')}
            accessibilityRole="button"
            accessible
            onPress={onPressShare}
            style={[styles.button, styles.flexRow, styles.gap1, styles.p3]}
        >
            <Icon
                src={Expensicons.QrCode}
                width={variables.iconSizeSmall}
                height={variables.iconSizeSmall}
                fill={theme.icon}
            />
            <Text style={styles.buttonMediumText}>{translate('common.share')}</Text>
        </PressableWithFeedback>
    </Tooltip>
</View>

**Comment by haris-ali9211** [comment] 2024-09-03 22:09
Contributor details
Your Expensify account email: [haris.aali9211@gmail.com](https://www.upwork.com/freelancers/~01d817e5e279394799)
Upwork Profile Link: [https://www.upwork.com/freelancers/~01d817e5e279394799](https://www.upwork.com/freelancers/~01d817e5e279394799)

**Comment by haris-ali9211** [comment] 2024-09-03 22:16
Contributor details
Your Expensify account email: haris.aali9211@gmail.com
Upwork Profile Link: [https://www.upwork.com/freelancers/~01d817e5e279394799](https://www.upwork.com/freelancers/~01d817e5e279394799)

**Comment by Gajendra-Gupta** [comment] 2024-09-04 13:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no tooltip for the Workspace Share button as there is for the Profile Share button.
### What is the root cause of that problem?
Tooltip not added for button.
### What changes do you think we should make in order to solve the problem?
Wrap this [button](https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/pages/workspace/WorkspaceProfilePage.tsx#L269-L275) in a ToolTip with Pressable
```
<Tooltip text={translate('common.shareCode')}>
                                    <Pressable>
                                <Button
                                    accessibilityLabel={translate('common.share')}
                                    text={translate('common.share')}
                                    onPress={onPressShare}
                                    medium
                                    icon={Expensicons.QrCode}
                                />
                                </Pressable>
                                </Tooltip>
```

**Comment by bondydaa** [comment] 2024-09-05 17:40
@c3024 can you get to these proposals? thanks!

**Comment by bondydaa** [comment] 2024-09-06 17:32
i'll be OOO next week so if we get proposals ready please ask for another engineer to review

**Comment by c3024** [comment] 2024-09-06 18:21
Sure. Thanks. I'll update today.

**Comment by c3024** [comment] 2024-09-08 14:21
@Expensify/design 

The actual result of the issue states:

> There is a tooltip when hovering over the Share button on the Profile page (Step 4), but no tooltip appears when hovering over the Share button on the Workspace Profile page. The font used on the Profile Share button is also larger than that on the Workspace Profile Share button.

Can you please confirm:
1. Is a tooltip necessary for the `Share` button on the Profile page? The button text seems to be clear enough and the tooltip does not seem to provide any useful info.
2. Do we need to match the button and font sizes on the Workspace Profile page with those on the Profile page?

**Comment by shawnborton** [comment] 2024-09-08 15:28
Hmm I feel like we usually don't use tooltips on buttons with labels, so I am cool with removing it. 

As for the font size differences, it does look like the font size on the Profile's share button is too big. This should easily be fixed by passing in the correct `medium` prop.

**Comment by c3024** [comment] 2024-09-08 16:50
@Krishna2323 's proposal LGTM!

🎀 👀 🎀 C+ Reviewed

**Comment by dangrous** [comment] 2024-09-09 18:18
Hi! Just to confirm from [here](https://github.com/Expensify/App/issues/48418#issuecomment-2336726834) - it looks like we want to move forward with @Krishna2323's alternative solution, removing the tooltip and updating the button on the Profile Page? If so, I'd probably go with updating the `PressableWithFeedback` to a `Button`. 

Let me know if I'm understanding correctly, and I can assign!

I also feel like this is probably a $125 issue, since it's very minor - @bondydaa / @zanyrenney what do you think?

**Comment by zanyrenney** [comment] 2024-09-13 15:34
how are we getting along here @Krishna2323 @c3024 ?

**Comment by c3024** [comment] 2024-09-13 15:40
PR yet to be opened. I think @Krishna2323 will soon open a PR.

**Comment by dangrous** [comment] 2024-09-30 14:40
melvin is doing an awful job recently on the automations - this was deployed to prod on 9/27, according to the comments on the PR....

**Comment by zanyrenney** [comment] 2024-10-02 14:48
Hi! I am going OOO tomorrow when this payment is due, back on 7th october. please could you handle the payment? I would be happy to take it back if there are any blockers when I am back. thanks!

**Comment by sonialiap** [comment] 2024-10-04 11:20
Payment summary:
@Krishna2323 $250 - paid in upwork ✔️ 
@c3024 $250 - paid in upwork ✔️

**Closed** 2024-10-04 11:21 UTC
Labels: Reviewing, External, Daily, Bug
