### ISSUE TITLE
[HOLD for payment 2024-12-25] [Performance] Re-profile ReportConnection and ReportActionsConnection to check if they are still necessary

### ISSUE THREAD

**Issue by fabioh8010** [Expensify/App#53141] opened 2024-11-26 15:51 UTC
Slack discussion: https://expensify.slack.com/archives/C01GTK53T8Q/p1731581014860089

**Summary**

We implemented [ReportConnection.ts](https://github.com/Expensify/App/blob/main/src/libs/ReportConnection.ts) and [ReportActionsConnection.ts](https://github.com/Expensify/App/blob/main/src/libs/ReportActionsConnection.ts) in the past in order to have a centralized place of the `ONYXKEYS.COLLECTION.REPORT` and `ONYXKEYS.COLLECTION.REPORT_ACTIONS` connections, improving performance in the App.

It turns out that these files introduce a risk in the project: They will lead to stale data situations if they are used in component files to render the UI. For that use case we should use `useOnyx` and not these files. It's very easy for someone to make this mistake and use these functions to render the UI, leading to bugs.

On top of that, as we now have the Onyx connection manager in place, we probably don't need these utility files anymore as the connection manager already reuse the connections (kinda the same purpose of the files).

**Action Plan**

1. Re-profile these files again to see if they are really improving the App's performance or not anymore. **Please note that these files might contain additional logic that need to be moved somewhere else!**
2. If they are **irrelevant** to performance:
   1. Remove them and move the necessary logic to another place, if necessary.
3. If they are **still relevant** to performance:
   1. Add a ESLint rule to the project to prevent importing these files in component files (we already use `no-restricted-imports` for some cases in the App, so we can think in a similar solution).

cc @mountiny 

<details><summary>Issue Owner</summary>Current Issue Owner: @VickyStash</details>

**Comment by VickyStash** [comment] 2024-11-28 08:42
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment] 2024-11-28 19:53
**Updates**
I've recorded some initial metrics to compare to the future ones and started revising the usage of **ReportConnection** methods:

[ReportConnection.updateReportData](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportConnection.ts#L58) - was implemented not so long ago, used in one place only. It should be easy to get rid of it. Overall, a more logical implementation of this would be using `Onyx.set` rather than updating the `allReports` variable.

[ReportConnection.getReport](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportConnection.ts#L51C10-L51C19) - same, was implemented not so long ago, used in one place. Overall it's a duplicate of [ReportUtils.getReport](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportUtils.ts#L760)

[ReportConnection.getAllReportsNameMap](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportConnection.ts#L43) - used in [Parser](https://github.com/Expensify/App/blob/ddcc5b44dce9f405bf3cd802736ef3c711cb3801/src/libs/Parser.ts#L33) utility only. It can be moved there if we want to esolate it.

[ReportConnection.getAllReportsLength](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportConnection.ts#L47) - used in [Firebase/utils ](https://github.com/Expensify/App/blob/ddcc5b44dce9f405bf3cd802736ef3c711cb3801/src/libs/Firebase/utils.ts#L15)only. It can be moved there if we want to esolate it.

[ReportConnection.getAllReports](https://github.com/Expensify/App/blob/ba9f9d5351d0bc3adb59e57c842c564ca19e9a9b/src/libs/ReportConnection.ts#L38) - **most usable** one, used in ~100 places in the code. There are a lot of cases when this method is used inside another utility method just to get the specific report,  but in fact the report already available in the component the method is called from. I'm looking through this method usages and check where it can be easily simplified. Then I'm going to re-check performance metrics to see the results.

**Comment by mountiny** [comment] 2024-12-02 10:09
@VickyStash thanks for the progress. Excited for more details on this one

**Comment by VickyStash** [comment] 2024-12-02 16:17
**Updates:**
I've prepared the [Draft PR](https://github.com/Expensify/App/pull/53385) with ReportConnection removal. It's in the internal review right now. It hasn't any effect on the performance.

**Comment by VickyStash** [comment] 2024-12-04 17:10
**Updates:**
- Updated the PR to remove ReportActionsConnection as well
- Resolved conflicts and errors after merging the main
- Added test steps

**Comment by VickyStash** [comment] 2024-12-05 14:56
The [PR](https://github.com/Expensify/App/pull/53385) has been opened for the review!

**Comment by VickyStash** [comment] 2024-12-10 17:03
**Updates:**
Working in progress on reviewer's feedback, I think I should finalize it tomorrow.

**Comment by VickyStash** [comment] 2024-12-13 12:33
The main [PR](https://github.com/Expensify/App/pull/53385) got merged!
I'm starting my work on the follow-up to get rid of the export of ReportUtils.getReport command. More context here: https://github.com/Expensify/App/pull/53385#discussion_r1878257810

**Comment by VickyStash** [comment] 2024-12-13 15:48
Opened [Draft PR](https://github.com/Expensify/App/pull/54113) with the removal of the `ReportUtils.getReport` method. The next step is extensive testing and preparing the PR for the review.

**Comment by VickyStash** [comment] 2024-12-16 12:34
The follow-up [PR](https://github.com/Expensify/App/pull/54113) is open for review.

**Comment by bfitzexpensify** [comment] 2024-12-25 14:30
I can see 2 PRs reviewed on this issue by @thesahindia. 

Payment summary:

@thesahindia due $500 for PR reviews via NewDot manual request

**Closed by bfitzexpensify** 2024-12-25 14:30 UTC
Labels: Daily, Task, Awaiting Payment

**Comment by garrettmknight** [comment] 2025-01-29 20:38
$500 approved for @thesahindia
