### ISSUE TITLE
[$500] [Desktop ONLY] [Distance] - Current location feature is accessible when location access is disabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26484] opened 2023-09-01 13:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/25990
## Action Performed:
Precondition: Location access on the device is disabled
1. Launch New Expensify app
2. Go to + > Request money > Distance
3. Tap 'Start'
4. Click Use current location

## Expected Result:
App shows the error message 'We were unable to find your location, please try again or enter an address manually'

## Actual Result:
The app is able to use current location feature despite not allowing location access on the device

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/c85704c4-4316-4299-841f-9d0e61a613b1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d4f91fb1f56b7041</li>
        <li>Upwork Job ID: 1697617876228902912</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-09-01 14:28
I confirmed that this is only occuring on Desktop and added a step to make the bug clearer. 

But it's not a deploy blocker IMO so I'm going to remove the label. Let's get this fixed though!

**Comment by shubham1206agra** [comment] 2023-09-01 14:58
Looks like mac is able to retrieve the location even though location service is off
In my case, it gave out my approximate location

**Comment by Julesssss** [comment] 2023-09-01 15:07
Yeah, same here. But because of the following I would suggest we don't try to 'guess' the users location:
- This is very innacurate, and pretty useless for distance tracking
- It feels like a violation of my data

**Comment by hayata-suenaga** [comment] 2023-09-01 15:07
is this only desktop?

**Comment by im-adithya** [comment] 2023-09-01 15:12
Proposal:

We can use the permissions API to check if permission is available and then proceed

```js
const permission = await navigator.permissions.query({ name: 'geolocation' })
```

**Comment by neil-marcellini** [comment] 2023-09-01 16:05
Wow that's so weird that this works without location permission. Yes let's do an extra check for location permission and if it's not granted, handle it like an error, as described in the design doc plan in [this issue description](https://github.com/Expensify/App/issues/25855).

**Comment by hayata-suenaga** [comment] 2023-09-26 01:27
Closing this issue as the issue is handled in the PR for a different issue

**Closed by hayata-suenaga** 2023-09-26 01:27 UTC
Labels: Reviewing, External, Engineering, Monthly, Improvement, Help Wanted
