### ISSUE TITLE
[$1000] Currency in Submit button in final confirmation page has lower case letter

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18823] opened 2023-05-12 07:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. open a chat
2. click + button
3. click Request money
4. Choose a currency that does not have dedicated symbol e.g. SGD
5. Enter 100 as amount and click next

## Expected Result:
Green submit button should have text “Request SGD 100.00”
## Actual Result:
Green submit button displaying text “Request Sgd 100.00",  inconsistent lettercase compared to Amount field

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/010dc620-df97-4475-8450-659bd0d995ac">

https://github.com/Expensify/App/assets/43996225/d3a12254-23a1-4db3-a388-b6ced205fb1e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @honnamkuan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683800647653469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01750cd430f4708452</li>
        <li>Upwork Job ID: 1658422921107083264</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by payal-lathidadiya** [comment] 2023-05-12 08:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Currency text in Submit button in confirmation page has lower case letter

### What is the root cause of that problem?
We are converting text copy [here](https://github.com/allroundexperts/Expensify/blob/9fcbeba4f0adce3b2e71a895cf0bb57576725412/src/components/MoneyRequestConfirmationList.js#L110) which will convert it to title case.

### What changes do you think we should make in order to solve the problem?

We have to modify logic here and create new function which will convert first letter to whole input to Capital instead of each word in string.

So, `request SGD 100` will become as splitAmount `Request SGD 100`

### What alternative solutions did you explore? (Optional)
None

**Comment by payal-lathidadiya** [comment] 2023-05-12 08:03
Contributor details
Your Expensify account email: payal.lathidadiya@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01961fe1f0c2d39e9b

**Comment by Pujan92** [comment] 2023-05-12 10:08
Seems regression from https://github.com/Expensify/App/pull/18143

**Comment by Julesssss** [comment] 2023-05-12 12:57
Ah right. We removed capitalisation for the messages but should have added it specifically to the currency.

**Comment by dukenv0307** [comment] 2023-05-12 13:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Currency in Submit button in final confirmation page has lower case letter
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/2376b776226974c3cc49433e33c5333433c75452/src/components/MoneyRequestConfirmationList.js#L110-L114

 We are modifying the string so the first letter of each word is capitalized and the rest lowercased.
### What changes do you think we should make in order to solve the problem?
we only should modify the first letter of the string to be capitalized. So we can use UCFirst function instead of recapitalize function

https://github.com/Expensify/expensify-common/blob/5f4672c84e19122fc77b4bf1ac092d4919472112/lib/str.js#L329-L333
### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2023-05-16 10:40
Hey @allroundexperts, are you able to submit this today if I assign you?

> Probably, we also should change the translations for split and request such that they start with upper case [here](https://github.com/allroundexperts/Expensify/blob/ec87028d419c68daedf7b96b6a2de100b0f0dfdb/src/languages/en.js#L321-L322).

We don't want to do this, because when shown beneath an IOUPreview it should remain uncapitalized (that's why I made this change originally)

**Comment by Julesssss** [comment] 2023-05-16 10:43
Awesome, thanks.

**Comment by Julesssss** [comment] 2023-05-16 10:44
So just to clarify. We want the submit button to be capitolized, but not when it's displayed in the ReportPreview. (the second case might be tricky to test currently, so let me know when it's ready and I'll help test)

**Comment by JmillsExpensify** [comment] 2023-05-22 19:25
Re-applying the `bug` label for payment since I'll be out the rest of this week.

**Comment by Julesssss** [comment] 2023-05-23 07:46
Ah sorry @parasharrajat, I must have accidentally removed you, which caused the automation to assign a C+ member randomly 🤦

**Comment by Julesssss** [comment] 2023-05-30 08:02
Ready for payment @michaelhaxhiu

**Comment by michaelhaxhiu** [comment] 2023-06-02 18:52
Sorry for the delay 😞

**Comment by michaelhaxhiu** [comment] 2023-06-02 18:54
@Julesssss Should I hire @0xmiroslav to this GH as the C+?

Seems they reviewed the PR here? 
https://github.com/Expensify/App/pull/19005

**Comment by michaelhaxhiu** [comment] 2023-06-02 18:56
This was assigned & merged on May 16 [here](https://github.com/Expensify/App/pull/19005#event-9258212306). 50% bonus is surely in play :)

So we'd have:
- **Bug reporter** - $250 @honnamkuan 
- **Contributor** - $1500 @allroundexperts 
- **C+** - $1500 @0xmiroslav

**Comment by michaelhaxhiu** [comment] 2023-06-02 19:06
Awaiting confirmation on these offers:
<img width="982" alt="image" src="https://github.com/Expensify/App/assets/13206896/b05a0044-f828-4a84-9708-9601fdf53df7">

**Comment by michaelhaxhiu** [comment] 2023-06-02 22:49
The checklist here still remains https://github.com/Expensify/App/issues/18823#issuecomment-1552507645

@Julesssss @0xmiroslav

**Comment by michaelhaxhiu** [comment] 2023-06-02 22:49
All parties are paid.

**Comment by michaelhaxhiu** [comment] 2023-06-05 01:42
That looks great! Thanks :)

QA steps GH: https://github.com/Expensify/Expensify/issues/288863

**Closed by michaelhaxhiu** 2023-06-05 01:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
