### ISSUE TITLE
 Web - Workspace - Member is shown in the created rooms after removing member from workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11773] opened 2022-10-12 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing the PR #11560

## Action Performed:
1. Invite a user to a workspace
2. Create a room with this workspace
3. On another browser window in incognito mode sign in as that user
4. On the window where you invited the user: Remove the same user from the workspace

## Expected Result:
Member is removed from the room created in step 2

## Actual Result:
Member is not removed and removed member still can send chat

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2-13-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195430891-938c342e-2ddb-42ce-a10f-caade600a878.mp4

https://user-images.githubusercontent.com/43996225/195430893-bdd01b85-b1ee-4e2f-8087-134e3a715f8f.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-10-26 10:19
Seeing if this can still be reproduced

**Comment by roryabraham** [comment] 2022-10-26 10:39
I was blocked from testing this bug on staging by https://expensify.slack.com/archives/C01GTK53T8Q/p1666779967663819

Overall I think this is probably a legitimate bug report, but I'm not sure what the status of user-created policy rooms is. I think there are many bugs surrounding the flow, but I also think many of them are behind a beta.

@trjExpensify @JmillsExpensify is there a tracking issue for user-created policy rooms somewhere? This should probably be added to that and then handled when those are re-prioritized.

**Comment by roryabraham** [comment] 2022-10-26 10:40
I propose we add this to the tracking issue and put it on HOLD. Going to unassign for now

**Comment by trjExpensify** [comment] 2022-10-31 10:53
>@trjExpensify @JmillsExpensify is there a tracking issue for user-created policy rooms somewhere? This should probably be added to that and then handled when those are re-prioritized.

@MitchExpensify has been leading user-created rooms, and @Luke9389 is helping to carry it to the finish line with the missing functionality like leave/join. To answer the question though, the main issue is [here](https://github.com/Expensify/Expensify/issues/137514) I believe.

**Comment by JmillsExpensify** [comment] 2022-11-01 19:54
For what it's worth, we are rounding out that functionality now. cc @Luke9389 since I recently re-opened the issues for invite/leave.

**Comment by Luke9389** [comment] 2022-11-01 21:02
Yeah I think we should close this for now. 

We're going to be testing this flow extensively as we build out user created rooms.

**Closed by Luke9389** 2022-11-01 21:02 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2022-11-01 22:59
That works for me.
