### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250] mWeb-In new WS, for distance rate selecting a category & opening it directs to hmm not here

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44206] opened 2024-06-22 13:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/

2. Tap profile icon -- Workspace -- New Workspace
3. Tap more features -- Enable distance rate
4. Tap Distance rates
5. Tap settings
6. Select a default category
7. Open the selected default category

## Expected Result:
In new workspace, for distance rate selecting a default category and opening it must show the selected category

## Actual Result:
In new workspace, for distance rate selecting a default category and opening it directs to hmm it's not here page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29d0e392-6363-41d7-9d67-09d3a0e547c2

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf4b3c18873471ae</li>
        <li>Upwork Job ID: 1805141403738762533</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 103065121</li>
<li>wildan-m | Contributor | 103065123</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by lanitochka17** [comment] 2024-06-22 13:52
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-22 13:54
We think that this bug might be related to #wave-collect - Release 1

**Comment by Muhammad-UmairAli** [comment] 2024-06-24 11:51
Clone the Expensify/App repository and create a new branch from the latest main.
Reproduce the issue and start debugging the navigation logic in the affected components.
Identify and fix the navigation issue, ensuring the selected category is correctly passed and displayed.
Write and run tests to confirm the fix works as expected.
Submit the pull request for review, including all necessary details and test evidence.

**Comment by Muhammad-UmairAli** [comment] 2024-06-24 11:54
Contributor details
Your Expensify account email: motivizor.hintsforlife@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0145449b71231ec7db

**Comment by isogit123** [comment] 2024-06-24 15:56
I can't reproduce the issue.

**Comment by isogit123** [comment] 2024-06-24 16:39
Contributor details
Your Expensify account email: aboutabl6@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~011b9b21b42a676c99

**Comment by situchan** [comment] 2024-06-26 01:06
No proposals to review

**Comment by jriyyya** [comment] 2024-06-26 06:14
HI @situchan , I am working on the proposal, I will soon come up with it.
I did find out that the issue is not related to selecting a default category, but to reproduce, If you just enable the distance rate and wait there for a few seconds, the Hmm not here shows up for about 1-2 seconds.

https://github.com/Expensify/App/assets/96080203/8558c9b6-3c22-43af-a4da-5a45301618ac

**Comment by jriyyya** [comment] 2024-06-26 06:18
Contributor details
Your Expensify account email: riya1jain567@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a88295f6ba1ce1bc?mp_source=share

**Comment by wildan-m** [comment] 2024-07-02 08:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

mWeb-In new WS, for distance rate selecting a category & opening it directs to hmm not here

### What is the root cause of that problem?
We attempted to address this issue with [this PR](https://github.com/Expensify/App/pull/40650), but some of the code modifications unintentionally led to [removal](https://github.com/Expensify/App/commit/6a18afb5f0b1622f8d7df3d61548aad90bb03aa0#diff-02a144ebc6affd9967462ce091c46afe40b38a3823c8880dd38f3d35235816f5). The modification involved changing the name from `FeatureEnabledAccessOrNotFoundWrapper` to `AccessOrNotFoundWrapper`, but after the refactoring, the fix was only partially applied.

### What changes do you think we should make in order to solve the problem?
Re-apply the changes that were missing from [this PR](https://github.com/Expensify/App/pull/40650). The updated code will be in the AccessOrNotFoundWrapper.tsx file.

```tsx
    const isFeatureEnabled = featureName ? PolicyUtils.isPolicyFeatureEnabled(policy, featureName) : true;
    const [isPolicyFeatureEnabled, setIsPolicyFeatureEnabled] = useState(isFeatureEnabled);
    const {isOffline} = useNetwork();

    const isPageAccessible = accessVariants.reduce((acc, variant) => {
        const accessFunction = ACCESS_VARIANTS[variant];
        return acc && accessFunction(policy, login, report, allPolicies ?? null, iouType);
    }, true);

    const isPolicyNotAccessible = isEmptyObject(policy) || (Object.keys(policy).length === 1 && !isEmptyObject(policy.errors)) || !policy?.id;
    const shouldShowNotFoundPage = (!isMoneyRequest && !isFromGlobalCreate && isPolicyNotAccessible) || !isPageAccessible || !isPolicyFeatureEnabled || shouldBeBlocked;

    // We only update the feature state if it isn't pending.
    // This is because the feature state changes several times during the creation of a workspace, while we are waiting for a response from the backend.
    // Without this, we can have unexpectedly have 'Not Found' be shown.
    useEffect(() => {
        if (pendingField && !isOffline && !isFeatureEnabled) {
            return;
        }
        setIsPolicyFeatureEnabled(isFeatureEnabled);
    }, [pendingField, isOffline, isFeatureEnabled]);
```

[Branch for this solution.](https://github.com/Expensify/App/compare/main...wildan-m:App:wildan/fix/44206-not-found-page-enable-ws-features?expand=1)

### What alternative solutions did you explore? (Optional)

**Comment by mvtglobally** [comment] 2024-07-03 14:38
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2024-07-03 18:51
> **mWeb**-In new WS, for distance rate selecting a category & opening it directs to hmm not here

@wildan-m thanks for the proposal. As you re-stated, can you please explain why this happens only on mWeb in root cause?

**Comment by wildan-m** [comment] 2024-07-03 22:28
@situchan My [proposal updated](https://github.com/Expensify/App/issues/44206#issuecomment-2202252254).

Change log: explain why the issue mostly occurred on mweb

> Issue not reproducible during KI retests. (First week)

@mvtglobally try using more effective reproduction steps as explained in the root cause of [my proposal](https://github.com/Expensify/App/issues/44206#issuecomment-2202252254)

**Comment by situchan** [comment] 2024-07-04 07:37
reviewing updated proposal

**Comment by situchan** [comment] 2024-07-09 04:53
updating today

**Comment by situchan** [comment] 2024-07-09 21:47
@wildan-m's [proposal](https://github.com/Expensify/App/issues/44206#issuecomment-2202252254) LGTM!
🎀👀🎀 C+ reviewed

**Comment by mvtglobally** [comment] 2024-07-11 03:50
Issue not reproducible during KI retests. (Second week)

**Comment by wildan-m** [comment] 2024-07-11 09:26
@situchan The [pull request](https://github.com/Expensify/App/pull/45239) is prepared for review.

**Comment by kadiealexander** [comment] 2024-07-24 05:41
Payouts due:

- [x] @wildan-m requires $250 payment ([automatic offer](https://www.upwork.com/nx/wm/offer/103065123) (Contributor))
- [ ] @situchan requires $250 payment ([automatic offer](https://www.upwork.com/nx/wm/offer/103065121) (Reviewer))

Upwork job is [here](https://www.upwork.com/jobs/~01bf4b3c18873471ae).

**Comment by kadiealexander** [comment] 2024-07-26 04:04
@situchan bump on the checklist!

**Closed** 2024-07-29 07:53 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
