### ISSUE TITLE
[HOLD for payment 2022-11-18] [$250] Space is not added after rendering emoji via text reported by @adeel0202

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12314] opened 2022-10-31 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Type :wave: in composer

## Expected Result:
Space is added after the emoji

## Actual Result:
Space is not added after the emoji

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.22-1

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199114556-cfce4d7d-56d7-4cc3-b96e-a6365ff640e6.mp4

https://user-images.githubusercontent.com/43996225/199114573-ad97238d-9e19-43e1-8603-e9eb89ec1838.mov

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667208968300839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Puneet-here** [comment] 2022-10-31 21:48
### Proposal

We just have to return 
```js
`${newText} `
```
https://github.com/Expensify/App/blob/2174ef50cd16fb3da074ef5dce880ac1653e7d23/src/libs/EmojiUtils.js#L201

**Comment by adeel0202** [comment] 2022-11-01 09:50
@Puneet-here you should've waited for the `Help Wanted` label before posting your proposal.

**Comment by Puneet-here** [comment] 2022-11-01 10:53
@adeel0202, proposals can be posted any time after the issue gets created. Please refer [here](https://github.com/Expensify/App/issues/10990#issuecomment-1249790443).

**Comment by dylanexpensify** [comment] 2022-11-01 13:04
Upwork: https://www.upwork.com/jobs/~01b305b99cbec3f000

**Comment by StefanNemeth** [comment] 2022-11-01 13:24
I'd like to work on it. Should be quite straightforward to change by adding a space when replacing the emojis in EmojiUtils. It might make sense to not do it in case the text is pasted in as this might cause unwanted spaces.

**Comment by officialksolomon** [comment] 2022-11-01 14:05
MY PROPOSAL FOR 
[$250] Space is not added after rendering emoji via text reported by @adeel0202 #12314 @dylanexpensify 

Situation: Space is not added after rendering emoji via text.

Solution: Use regular expression to detect emoji inputs, separate emojis from normal text and perform necessary string manipulation to add space to the beginning of the separated text.

Steps:
1. Create a function that detects the emoji text.
2. Create a function for the string manipulations
3. Store manipulated text with emoji in state variable.
4. And update input value.

Benefits:
My solution accounts for bot typed and pasted text.

**Comment by neil-marcellini** [comment] 2022-11-01 15:54
This is a feature not a bug. The implementation comes from [this commit](https://github.com/Expensify/App/commit/8541cc4b33de93c6581f842db2be6a20089725f8) from [this PR](https://github.com/Expensify/App/pull/11161) to implement [this feature request issue](https://github.com/Expensify/App/issues/11100).

https://github.com/Expensify/App/blob/064eeea9e36bc4cb8cacb3b92ad02acf8ea6b35d/src/pages/home/report/ReportActionCompose.js#L315-L321

**Comment by neil-marcellini** [comment] 2022-11-01 16:19
Oh ok, thanks for clearing that up @adeel0202! You are right, I'll try to read more carefully next time.

**Comment by neil-marcellini** [comment] 2022-11-01 16:41
At first glance I like @Puneet-here's proposal https://github.com/Expensify/App/issues/12314#issuecomment-1297727461, but @adeel0202 brings up a good point that it doesn't work properly when pasting in text with emojis.

When I type `:apple:` in the composer box it should replace that with an apple and a space following it, e.x "🍎 ", so that I can keep typing with ease. However, if I past in some text like this `:smile::apple::hamburger:no space after emojis` then I want to see the emojis right next to each other and text immediately following the last emoji, e.x "😄🍎🍔no space after emojis". In other words, I think we should only manually append a space after an emoji if it is the last character in the text. Do you guys agree?

If so, please submit a proposal that handles these cases.

**Comment by Puneet-here** [comment] 2022-11-01 17:51
### Updated proposal

Check the `emojiData.length`
```js
    if (emojiData.length > 1) {
        return newText;
    }
    return `${newText} `;
```
https://github.com/Expensify/App/blob/2174ef50cd16fb3da074ef5dce880ac1653e7d23/src/libs/EmojiUtils.js#L201

**Comment by Karim-30** [comment] 2022-11-01 20:49
in `src/libs/EmojiUtils.js` : 

```diff
function replaceEmojis(text) {
    let newText = text;
    const emojiData = text.match(CONST.REGEX.EMOJI_NAME);
    if (!emojiData || emojiData.length === 0) {
        return text;
    }
    for (let i = 0; i < emojiData.length; i++) {
        const checkEmoji = emojisTrie.search(emojiData[i].slice(1, -1));
        if (checkEmoji && checkEmoji.metaData.code) {
-           newText = newText.replace(emojiData[i], checkEmoji.metaData.code);
+           newText = newText.replace(emojiData[i], `${checkEmoji.metaData.code} `);
        }
    }
    return newText;
}
```

https://user-images.githubusercontent.com/108357004/199337922-d2fc8cd0-6c2f-455a-aabd-45b1eeb71174.mp4



I will not paid for it.

**Comment by neil-marcellini** [comment] 2022-11-04 18:31
> @neil-marcellini what if we're inserting an emoji in the middle of a comment

It's important that if the user pastes in text it shows up as they expect, so we don't want to insert spaces after emojis in the middle of a comment when pasting text, e.x `:smile::apple::hamburger:no space after emojis`. Maybe we could replace the emojis without adding spaces when we [handlePaste](https://github.com/Expensify/App/blob/0610934792957b8e70897e3ea3be9ef9e9d57736/src/components/Composer/index.js#L276)?

Alternatively we could let the user add the space themselves when inserting an emoji in the middle of a comment.

**Comment by neil-marcellini** [comment] 2022-11-04 19:01
## Proposal
Insert a space when replacing emojis if the emoji is at the end of the current message.

If @rushatgabhane likes this proposal too then I would like @Puneet-here to go ahead an implement it for me, because he had the first proposal.

```diff
diff --git a/src/libs/EmojiUtils.js b/src/libs/EmojiUtils.js
index ed67a2aed..f70413d68 100644
--- a/src/libs/EmojiUtils.js
+++ b/src/libs/EmojiUtils.js
@@ -195,7 +195,13 @@ function replaceEmojis(text) {
     for (let i = 0; i < emojiData.length; i++) {
         const checkEmoji = emojisTrie.search(emojiData[i].slice(1, -1));
         if (checkEmoji && checkEmoji.metaData.code) {
-            newText = newText.replace(emojiData[i], checkEmoji.metaData.code);
+            let emojiReplacement = checkEmoji.metaData.code;
+
+            // If this is the last emoji in the message and it's the end of the message so far, add a space after it so the user can keep typing easily.
+            if (i === emojiData.length - 1 && text.endsWith(emojiData[i])) {
+                emojiReplacement += ' ';
+            }
+            newText = newText.replace(emojiData[i], emojiReplacement);
         }
     }
     return newText;
diff --git a/tests/unit/EmojiTest.js b/tests/unit/EmojiTest.js
index 5a66a57e9..387d716a1 100644
--- a/tests/unit/EmojiTest.js
+++ b/tests/unit/EmojiTest.js
@@ -78,9 +78,14 @@ describe('EmojiTest', () => {
         expect(EmojiUtils.containsOnlyEmojis('😄  👋')).toBe(true);
     });

-    it('replaces emoji codes with emojis inside a text', () => {
-        const text = 'Hi :smile::wave:';
-        expect(EmojiUtils.replaceEmojis(text)).toBe('Hi 😄👋');
+    it('replaces an emoji code with an emoji and a space', () => {
+        const text = 'Hi :smile:';
+        expect(EmojiUtils.replaceEmojis(text)).toBe('Hi 😄 ');
+    });
+
+    it('will not add a space after the last emoji if there is text after it', () => {
+        const text = 'Hi :smile::wave:no space after last emoji';
+        expect(EmojiUtils.replaceEmojis(text)).toBe('Hi 😄👋no space after last emoji');
     });

     it('suggests emojis when typing emojis prefix after colon', () => {

```

**Comment by neil-marcellini** [comment] 2022-11-07 17:48
> nitpick: an edgecase with this [proposal](https://github.com/Expensify/App/issues/12314#issuecomment-1304016775) is that it won't add a space for a multiline comment.

That's true, but I think it's just another case where the user is inserting an emoji in the middle of a comment and we already decided that the user can add a space manually.

**Comment by neil-marcellini** [comment] 2022-11-07 17:57
@Puneet-here I'm assigning you to implement this proposal https://github.com/Expensify/App/issues/12314#issuecomment-1304016775. Please let me know within a day or so if you can implement this, otherwise I'll pick someone else so we can move this forward quickly. Thanks!

**Comment by Puneet-here** [comment] 2022-11-07 19:14
Thanks @neil-marcellini, I have raised the PR.

**Comment by dylanexpensify** [comment] 2022-11-09 13:39
@Puneet-here @rushatgabhane would you mind applying on the Upwork job above please? 🙇

**Comment by dylanexpensify** [comment] 2022-11-21 10:49
reviewing today!

**Comment by Puneet-here** [comment] 2022-11-22 08:39
Accepted the offer.

**Comment by dylanexpensify** [comment] 2022-11-22 12:17
all have been paid out, contracts ended

**Comment by Puneet-here** [comment] 2022-11-22 12:23
@dylanexpensify, I think the 50% bonus applies here as it was merged within 2 days

**Comment by dylanexpensify** [comment] 2022-11-22 12:28
ah, good catch @Puneet-here - I've sent each individual the 50% bonus now

**Comment by neil-marcellini** [comment] 2022-11-25 17:16
@dylanexpensify I think all that remains to close this out is adding a regression test right? https://github.com/Expensify/App/issues/12314#issuecomment-1307949663

**Comment by dylanexpensify** [comment] 2022-11-28 10:03
Correct! Getting on this today now that I'm back from OOO!

**Comment by dylanexpensify** [comment] 2022-11-28 11:25
posted regression test buddy check

**Comment by dylanexpensify** [comment] 2022-11-30 10:22
Regression test update GH [here](https://github.com/Expensify/Expensify/issues/245551)

**Closed by dylanexpensify** 2022-11-30 10:22 UTC
Labels: External, Daily, Awaiting Payment, Bug
