### ISSUE TITLE
[HOLD for payment 2022-05-02] [$250] Close account - Unnecessary extra vertical margin above the pop up message when tapping close account

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8404] opened 2022-03-31 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with account [kbecciv+2002@gmail.com/Feya86Katya](mailto:kbecciv+2002@gmail.com/Feya86Katya)[](javascript:)
on New dot.
3. Go to Settings - Security - Close account.
4. Enter the message in input box.
5. Enter email which you are going to close.
6. Click close account.

## Expected Result:
Normal space between border and message in popup after tap close account

## Actual Result:
Too much space in popup message after tap close account

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.49.0

**Reproducible in staging?:**  Y

**Reproducible in production?:** Y

**Email or phone of affected tester (no customers):** kbecciv+2002@gmail.com / Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
![Bug5514198_Screenshot_20220331-121058_New_Expensify](https://user-images.githubusercontent.com/43996225/161108952-438ca46e-cf46-4b9a-928c-87f2eaaf7989.jpg)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause @Tushu17 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1648072472591519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Tushu17** [comment] 2022-03-31 18:26
Hi @kavimuru I had reported this on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1648072472591519), is this eligible for the reporting bonus.

**Comment by sobitneupane** [comment] 2022-04-01 07:10
**Proposal:**
**Reason:** The Confirm Modal in CloseAccountPage has space as title so extra space appears at the top.
There are two ways to deal with this issue.
1. Add title to Confirm Modal in CloseAccountPage. All Confirm Modal except in CloseAccountPage has title so we might be tempted to add title to this confirm modal as well. We can use `"Unable to Close Your Account"` or similar title.
https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/pages/settings/Security/CloseAccountPage.js#L113-L115
2. Show the header section only if title is present.
https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/components/ConfirmContent.js#L58-L60
```
        {props.title.length > 0 && (
            <View style={[styles.flexRow, styles.mb4]}>
                <Header title={props.title} />
            </View>
        )}
```

**Comment by Puneet-here** [comment] 2022-04-01 10:01
### Proposal 

We aren't using any title for this modal and we have some margin at bottom for the title that's why there's extra space.
https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/pages/settings/Security/CloseAccountPage.js#L113-L114

if we use this code there won't be any extra space when there's no title.
```js
 {!_.isEmpty(props.title) && (
        <View style={[styles.flexRow, styles.mb4]}>
            <Header title={props.title} />
        </View>
        )}
```
Also the title is required here -
https://github.com/Expensify/App/blob/50496a0a0d7dd283f9936988cda95abf69741342/src/components/ConfirmContent.js#L11-L13

There can be other modals in future that won't need a title so if we want we can make it optional by removing `isRequired` and we can add  `title: ''` in default props we also need to make the title optional ConfirmModal as it passes the title to ConfirmContent

And also if we want we can add a title in this modal -
<img width="385" alt="Screenshot 2022-04-01 at 1 40 33 PM" src="https://user-images.githubusercontent.com/101883770/161222817-2f9a946f-a43b-493f-a2d2-46379360efad.png">

**Comment by marcaaron** [comment] 2022-04-04 20:28
LGTM. I updated the title so the issue would be more clear. I thought it was referring to a white space character and not extra vertical margin.

**Comment by mallenexpensify** [comment] 2022-04-04 20:41
>Hi @kavimuru I had reported this on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1648072472591519), is this eligible for the reporting bonus.

@kavimuru , can you confirm this is the same ·(or... the same-enough) as https://github.com/Expensify/App/issues/8457?  If so, I'll close that issue and add `reported by @Tushu17 ` to the OP here.

**Comment by isagoico** [comment] 2022-04-06 17:30
Looks like the same issue but in a different modal in my opinion - @mallenexpensify I think you can go ahead with closing the other issue and editing this one

**Comment by rushatgabhane** [comment] 2022-04-07 20:00
> see if there are any details there that need to be added here

All is set!

**Comment by rushatgabhane** [comment] 2022-04-07 20:08
> Add title to Confirm Modal in CloseAccountPage. 



🎀 👀 🎀 C+ reviewed
I recommend @sobitneupane's [proposal](https://github.com/Expensify/App/issues/8404#issuecomment-1085517358). I guess "Oops!" would be a decent title.

Or we could add `waiting for copy` label to get a better title.
cc: @stitesExpensify

**Comment by rushatgabhane** [comment] 2022-04-07 20:13
@Puneet-here I really appreciate your proposal but it's too similiar to [this proposal](https://github.com/Expensify/App/issues/8404#issuecomment-1085517358) which came earlier. Feel free to have a look at other open issues. Thanks!

**Comment by stitesExpensify** [comment] 2022-04-07 20:31
Let's toss `waiting for copy` on. I think the proposal of "Unable to close account" is good, my only fear is that it will wrap on mobile. "oops" would probably be fine too but I'll let Marketing decide that :)

**Comment by stitesExpensify** [comment] 2022-04-07 20:31
Proposal looks good though besides copy

**Comment by mallenexpensify** [comment] 2022-04-08 00:47
ah... interesting, since I'm the CM assigned and also on the marketing team, I stay assigned for waiting for copy (not surprised but haven't had it happen before).

I like "Unable to close account" and _think_ it will fit.  Without involving our design team, is there an _easy_ way to find out?

**Comment by stitesExpensify** [comment] 2022-04-08 14:11
Yeah it should be trivial to toss that in there 😄 Let's go ahead and hire @sobitneupane and they can take care of it

**Comment by rushatgabhane** [comment] 2022-04-08 14:13
>  Without involving our design team, is there an easy way to find out?

@mallenexpensify if you access to the design (figma) files. You could find out if it fits.

Anyway, I gave the proposal a try and "Unable to Close Your Account" fits comfortably for small devices.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/29673073/162453459-a21c0e1c-f9d4-425b-9e13-90e68c6b257a.png">

**Comment by stitesExpensify** [comment] 2022-04-08 15:47
Spanish translation: `No se pudo cerrar tu cuenta`

**Comment by sobitneupane** [comment] 2022-04-11 03:42
> Job posted https://www.upwork.com/jobs/~01ac2d33f4be5cc3d3

Applied for the job.

**Comment by mallenexpensify** [comment] 2022-04-12 17:42
Everyone is hired in Upwork!

**Comment by stitesExpensify** [comment] 2022-04-14 20:15
Not overdue

**Comment by stitesExpensify** [comment] 2022-04-14 20:33
PR is now merged

**Comment by mvtglobally** [comment] 2022-04-26 04:44
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2022-04-30 00:18
I'm out Mon/Tues so I paid $250 ea today to @Tushu17 , @sobitneupane and @rushatgabhane 
Thanks!

**Closed by mallenexpensify** 2022-04-30 00:18 UTC
Labels: Exported, External, Engineering, Weekly, Awaiting Payment
