### ISSUE TITLE
[$500] iOS - Request Money - Searching for specific HT account while using HT account has an odd behavior

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30803] opened 2023-11-02 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30591

## Action Performed:
Pre-requisite: user must be logged in with a HT account.
1. Tap on "+" button.
2. Tap on "Request money".
3. Select "Manual".
4. Enter any amount and tap on "Next".
5. Search for a specific HT account, such as "[applausetester+vd_htmain@applause.expensifail.com".](mailto:applausetester+vd_htmain@applause.expensifail.com%22.)

## Expected Result:
The search results should only show the requested account.

## Actual Result:
The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/7edf62e1-2fb8-4105-98fe-61fd1c96cc66

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c1e5f3f5dad45859</li>
        <li>Upwork Job ID: 1720190449397870592</li>
        <li>Last Price Increase: 2023-11-02</li>
    </ul>
</details>

**Comment by orshikh-dev** [comment] 2023-11-03 07:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars.
### What is the root cause of that problem?
It shows an existing account with a specific existing email and it also adds a non-existed account with non-existed email.

When we are searching with some text, search input sends a search term for every single character. In every request, it will call this method, this method returns all list options:

https://github.com/Expensify/App/blob/a61572e1d794c219592d806b4be11001b8e39f93/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L111-L160

If we find a user with a specific email, that user will be added to sections

https://github.com/Expensify/App/blob/a61572e1d794c219592d806b4be11001b8e39f93/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L115-L124

And if a user does not exist, we add non-existing users into sections as well,

https://github.com/Expensify/App/blob/a61572e1d794c219592d806b4be11001b8e39f93/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L147-L159

There are 2 possible cases:
CASE 1: THE USER DOES NOT EXIST
Non-existing user is added into sections, no issues:

https://github.com/Expensify/App/blob/a61572e1d794c219592d806b4be11001b8e39f93/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L147-L159

CASE 2: USER EXIST
In this case, the user will be added to the section, just like this:

https://github.com/Expensify/App/blob/a61572e1d794c219592d806b4be11001b8e39f93/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L124

But, in every single valid email address, it will be a non-existent user:
For example applausetester+vd_htmain@applause.expensifail.com

**Existed user:** 
If the email address is valid, it will be added into sections:
applausetester+vd_htmain@applause.e is enough, not required to be whole email, just valid, existed email pattern is enough


**Non-existed users with valid emails:**
applausetester+vd_htmain@applause.e          <=   here we know this email is valid and found existed user with this email
applausetester+vd_htmain@applause.ex
applausetester+vd_htmain@applause.exp
applausetester+vd_htmain@applause.expe
applausetester+vd_htmain@applause.expen
             . . .
applausetester+vd_htmain@applause.expensifail.co   <= till, not whole email address

That's why the avatar is changing because, for every valid email, for every single character, it will send a request, in every request, the non-exist user(all different user) will be added into sections, in this example, for all characters in this text [xpensifail.co]. The email was so long, so we didn't see it was changing in the row.

Please see from this video:
[https://drive.google.com/file/d/1LOnmzTz-fSW9oCk-p55pkh0PlKRmRBv0/view?usp=sharing](https://drive.google.com/file/d/1LOnmzTz-fSW9oCk-p55pkh0PlKRmRBv0/view?usp=sharing)


### What changes do you think we should make in order to solve the problem?


1. This is not a bug, but we need to fix UX. We can make some changes to the email address, maybe we can concat from the middle, or concat from the head, now it is concating from the tail.

<img width="355" alt="image" src="https://github.com/Expensify/App/assets/149475800/b864d40c-cb8d-4d1d-b295-1ec8727ba551">


Concating from head:
<img width="351" alt="image" src="https://github.com/Expensify/App/assets/149475800/e6f32752-e342-4dd2-976a-e0e09f481cda">


Concating from middle:
<img width="357" alt="image" src="https://github.com/Expensify/App/assets/149475800/28283466-4649-4f36-8b2d-6bff5f67dd77">

2. We can make other UX design changes, user can easily understand what is going on.

### What alternative solutions did you explore? (Optional)
Or we can set a limit on email length, so it can't be that long to be out of the screen. In example, 42 character length email:
<img width="348" alt="image" src="https://github.com/Expensify/App/assets/149475800/3cfaa608-92f5-4b67-a812-59718eae8286">


**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by rojiphil** [comment] 2023-11-03 10:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In request money participants selector page, the search results keeps getting constantly updated (i.e avatar, search result itself) even after the user has stopped entering the search value. This is the problem we are trying to solve here.

### What is the root cause of that problem?

When a long search text is entered (e.g. [applausetester+vd_htmain@applause.expensifail.com](mailto:applausetester+vd_htmain@applause.expensifail.com%22.)), this will generate many API requests to the server for reports as shown [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L260). Since each of these responses will come back at some time later and trigger the `useEffect` [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L226C1-L255C127), updation of the `sections` [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L113) will get delayed in a HT environment with lots of results.

### What changes do you think we should make in order to solve the problem?

We can solve this problem by debouncing the updation of chat options thereby saving processing time which will matter a lot in a HT environment. 

1) We can move the contents of `useEffect` [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L226C1-L255C127) into a new function `updateChatOptions` like this

```
    const updateChatOptions = useCallback(() => {
       // Contents of useEffect here  
    }, [betas, reports, participants, personalDetails, translate, searchTerm, setNewChatOptions, iouType, isDistanceRequest]);
```

2) Debouncing the `updateChatOptions` can be done like this [here]()

```
    useEffect(() => {
        const debouncedFetchChatOptions = _.debounce(updateChatOptions, 200);
        debouncedFetchChatOptions();
        return () => {
            debouncedFetchChatOptions.cancel();
        };
    }, [updateChatOptions]);
``` 

### What alternative solutions did you explore? (Optional)

**Comment by puneetlath** [comment] 2023-11-06 19:20
Thoughts on the proposals @mananjadhav?

**Comment by mananjadhav** [comment] 2023-11-07 12:40
Will review this today.

**Comment by mananjadhav** [comment] 2023-11-07 19:36
I can see the multiple API calls for the search. I think @rojiphil's [proposal](https://github.com/Expensify/App/issues/30803#issuecomment-1792220306) would work.

🎀 👀 🎀 C+ reviewed.

**Comment by puneetlath** [comment] 2023-11-07 22:45
I think it also makes sense to debounce the API calls for this. Would just like a second opinion from @marcaaron since I believe he implemented this.

**Comment by marcaaron** [comment] 2023-11-08 06:09
>Since each of these responses will come back at some time later and trigger the useEffect [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L226C1-L255C127), updation of the sections [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L113) will get delayed in a HT environment with lots of results.

API calls happening "too many times"? Not sure I really buy that. 

There's a debounce for the API calls already. Maybe they happen too many times, but what does it have to do with:

>The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars

Do we feel like we have a clear understanding of what this bug report is about?

**Comment by rojiphil** [comment] 2023-11-08 08:26
> > Since each of these responses will come back at some time later and trigger the useEffect [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L226C1-L255C127), updation of the sections [here](https://github.com/Expensify/App/blob/c0657fa0b2c3cc5a88659c3f4d21ee37439a2fdc/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L113) will get delayed in a HT environment with lots of results.
> 
> API calls happening "too many times"? Not sure I really buy that.
> 
> There's a debounce for the API calls already. Maybe they happen too many times, but what does it have to do with:
> 
> > The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars
> 
> Do we feel like we have a clear understanding of what this bug report is about?

@marcaaron 
Agree that there is debounce for the API calls already. But it looks like when it is called too many times (I.e. due to long mail id applausetester+vd_htmain@applause.expensifail.com) in a HT environment, rendering gets stacked up for each of these responses until it gets rendered sequentially. As a result, we can see constantly changing avatars even after the user has stopped entering the email.
Does this make sense? No?

There is a similar approach used [here](https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/pages/tasks/TaskShareDestinationSelectorModal.js#L82C1-L88C25) in `TaskShareDestinationSelectorModal` where we additionally debounce the handling of responses along with debounced API calls. Could be related to this.

**Comment by marcaaron** [comment] 2023-11-08 22:45
>As a result, we can see constantly changing avatars even after the user has stopped entering the email. Does this make sense?

Backing up, why does the avatar change? It changes on every render? I would look at that first before considering the API requests as the solution (but perhaps both can end up in the final proposal).

**Comment by marcaaron** [comment] 2023-11-08 22:47
>There is a similar approach used [here](https://github.com/Expensify/App/blob/24184e4a987aba011b5231680da66dcef11f6a24/src/pages/tasks/TaskShareDestinationSelectorModal.js#L82C1-L88C25) in TaskShareDestinationSelectorModal where we additionally debounce the handling of responses along with debounced API calls. Could be related to this.

To solve a [rendering performance issue](https://github.com/Expensify/App/issues/20075).

So what bug are we solving? I think it needs clarifying.

**Comment by rojiphil** [comment] 2023-11-10 13:34
@marcaaron 

> To solve a [rendering performance issue](https://github.com/Expensify/App/issues/20075).

Thanks for pointing this out. My bad. Just needed a simple blame check to reach here.

> Backing up, why does the avatar change? It changes on every render? I would look at that first before considering the API requests as the solution (but perhaps both can end up in the final proposal).

> So what bug are we solving? I think it needs clarifying.

From [here](https://github.com/Expensify/App/blob/ee275ef7787a3c8ce9a07dc54a0f9d3226445419/src/libs/OptionsListUtils.js#L1342) and [here](https://github.com/Expensify/App/blob/ee275ef7787a3c8ce9a07dc54a0f9d3226445419/src/libs/OptionsListUtils.js#L1322), avatars can change for users not yet saved in Onyx as it depends on the `searchValue`. In our case, since the searchValue keeps changing, the avatar keeps changing due to the side effect call to `getFilteredOptions` [here](https://github.com/Expensify/App/blob/ee275ef7787a3c8ce9a07dc54a0f9d3226445419/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsSelector.js#L227). 

As shown in the test video of the issue, since the avatars keep changing even after the user has stopped keying in, it seems like the side effects of incoming data from API response in a HT environment is resulting in a performance problem. 
Makes sense? No?

**Comment by marcaaron** [comment] 2023-11-10 21:54
Thanks! I'm going OOO soon so @puneetlath can hopefully continue this convo with you @rojiphil.

Without doing a deep dive - I would expect that the avatar color would change only if the login itself changes.

IMO it feels like the problem here is that we are regenerating an optimistic accountID on each render and inside the `getOptions()` method.

>it seems like the side effects of incoming data from API response in a HT environment is resulting in a performance problem

This ticket is unrelated to performance AFAICT...

**Bug that was reported:**

>The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars.

**Comment by rojiphil** [comment] 2023-11-11 06:35
> I would expect that the avatar color would change only if the login itself changes.
> IMO it feels like the problem here is that we are regenerating an optimistic accountID on each render and inside the getOptions() method.

Regenerating an optimistic accountID based on searchValue within getOptions() seems to be an intentional change as per this [PR here](https://github.com/Expensify/App/pull/22791). Not sure if we want to revisit this.

> Bug that was reported:
> The account being searched is at the top of the list, but then reappears at the bottom constantly changing avatars.

Meanwhile, on having a closer observation of the test video attached to this issue, I noticed a massive lag from 0:34 sec onwards (i.e. after the spinner stops). 
Doesn’t this seem to be the real issue here? 
Also, this looks similar to the one mentioned in [issue here](https://github.com/Expensify/App/issues/20075). 
Maybe, the bug description here is somewhat misleading.

**Comment by rojiphil** [comment] 2023-11-16 08:30
@puneetlath 
Looking forward to your feedback to the [comment here](https://github.com/Expensify/App/issues/30803#issuecomment-1806715603)
Or do we wait until @marcaaron is back from OOO

**Comment by puneetlath** [comment] 2023-12-06 16:26
Sorry for the delay. @mananjadhav what are your thoughts on all this?

**Comment by mananjadhav** [comment] 2023-12-06 16:35
@puneetlath I am not sure if I can get to this sooner, can you please reassign?

**Comment by rojiphil** [comment] 2023-12-06 16:37
@puneetlath
The last discussion we had was [here](https://github.com/Expensify/App/issues/30803#issuecomment-1806715603). 
We need to continue from there.

**Comment by situchan** [comment] 2023-12-06 16:44
interested in reviewing this

**Comment by situchan** [comment] 2023-12-12 13:34
Reviewed all conversations. reviewing proposals.

**Comment by puneetlath** [comment] 2023-12-15 15:53
Let us know your thoughts @situchan

**Comment by situchan** [comment] 2023-12-19 04:23
I tested on latest main and the behavior is not that odd.
@rojiphil can you please retest and share video?
FYI: debounce was introduced in https://github.com/Expensify/App/pull/32962 and just deployed to staging

**Comment by puneetlath** [comment] 2023-12-22 21:58
I'm going to go ahead and close this issue based on @situchan's experience. @rojiphil feel free to let us know if you think otherwise and we can reopen if there is something to fix.

**Closed by puneetlath** 2023-12-22 21:58 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
