### ISSUE TITLE
Search - App exits selection mode when going to a different status

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47672] opened 2024-08-19 21:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has expenses in Outstanding or Paid tabs.

1. Launch New Expensify app.
2. Go to Search.
3. Long press on the expense > Select.
4. Go to a different status (outstanding for example).

## Expected Result:
Describe what you think should've happened

## Actual Result:
App exits selection mode when going to a different status.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3556c8ee-7b44-444b-9366-ced33753a6f8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-19 21:22
We think that this bug might be related to #wave-collect - Release 1

**Comment by francoisl** [comment] 2024-08-19 21:59
Yeah I could see it being on purpose, otherwise it might be confusing if, for example, you switch between expense statuses, select other expenses, then you tap on the "[N] selected" > "Download" option, and have a bunch of expenses from the previous view included in the download.

**Comment by francoisl** [comment] 2024-08-19 22:09
Either way, doesn't sound like something worth blocking for. Going to demote until confirmation.

**Comment by Kicu** [comment] 2024-08-20 10:11
I agree with @rayane-djouah that IMO this is not a bug. 

To expand: every time we change `status` or `type` (status is coming from status bar, type is coming from the pop-up selector, only `Expense` for now) we are changing the search query.
Every time part of query changes we need to make a fresh request to backend and might get completely different list of results. And we will get a full re-render of displayed results because of that.

I think trying to preserve selection mode between this search re-renders will be more confusing in the long run.

Also this is a related issue: https://github.com/Expensify/App/issues/47670 where the same thing applies to the part: "selection is cleared when going from Inbox to Search" - in that case I believe dropping the selection also makes sense.
CC @luacmartins

**Comment by luacmartins** [comment] 2024-08-20 13:54
This is not a bug. Closing.

**Closed by luacmartins** 2024-08-20 13:54 UTC
Labels: Engineering, Daily, Bug
