### ISSUE TITLE
[HOLD for payment 2024-04-04] [$500] Chat - The app crashes when opening a high resolution image

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35171] opened 2024-01-25 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Upload the provided high resolution image to any chat
2. Tap on it once it finished loading

## Expected Result:
It shouldn't crash.

## Actual Result:
The app crashes when opening a high resolution image. On iOS mWeb it crashed as soon as I select the image with a blank preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/408cb459-5e86-4d7d-ab9b-9d48c1cc5a2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01788ec8d9af6ffdc5</li>
        <li>Upwork Job ID: 1750587875060334592</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by FitseTLT** [comment] 2024-01-25 18:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes when opening a high resolution image

### What is the root cause of that problem?
We are not limiting the resolution as we do for Avatar
https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/AvatarWithImagePicker.js#L207-L211
### What changes do you think we should make in order to solve the problem?

We should implement a resolution limit for attachements too as we did for avatar
Check if the resolution of the uploaded image has greater than the max resolution and set/display error message (same as what we did for [avatar](https://github.com/Expensify/App/blob/e9f27ab4218ec21ac6ecd755d4026b85c50f67d6/src/components/AvatarWithImagePicker.js#L207-L211
)).

### What alternative solutions did you explore? (Optional)

**Comment by kbecciv** [comment] 2024-01-25 19:42
@ZhenjaHorbach I have original file, but unable to attach to GH

![image](https://github.com/Expensify/App/assets/93399543/3e61a6ed-7b3e-41f4-9002-5ec07b703350)

**Comment by kbecciv** [comment] 2024-01-31 19:35
Sent DM for file https://expensify.slack.com/archives/D05CP2F12RE/p1706729679968449

**Comment by sakluger** [comment] 2024-02-07 21:49
Adding to #vip-vsb. Hopefully we'll get some more proposals soon!

**Comment by sourcecodedeveloper** [comment] 2024-02-12 08:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when user uploads high resolution image.

### What is the root cause of that problem?
The android native app crashes when the user tries to upload high res image to chat. Running adb logcat, the following exception is found

02-10 17:33:46.324 28446 28446 E AndroidRuntime: FATAL EXCEPTION: main
02-10 17:33:46.324 28446 28446 E AndroidRuntime: Process: com.expensify.chat, PID: 28446
02-10 17:33:46.324 28446 28446 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(110712580bytes) bitmap.

The ImageView native index uses Lightbox
https://github.com/Expensify/App/blob/06c7dac74ad5bcc8009c614570625afe4006f621/src/components/ImageView/index.native.tsx#L20
The Lighbox has index.tsx which calls the relevant Image component for native or web.
For the native the lightbox calls index.native.js which uses expo-image component for displaying images on native. The web uses react-native Image component.

The ImageComponent does not use any sort of subsampling or resize the original image.
https://github.com/Expensify/App/blob/4bb42fad0686193b0dfb50130a77a65a30fb7c76/src/components/Image/index.native.js#L37

Also the LightBox component is setting resizeMode="contain" and then passing the prop to expo-image component.
https://github.com/Expensify/App/blob/55af216a88233694e1e45117eeb0ff2ddde82480/src/components/Lightbox/index.tsx#L198

But according to expo-image documentation, resizemode is deprecated and contentFit should be used.
https://docs.expo.dev/versions/latest/sdk/image/#resizemode

The resizeMode prop should only be applied to the react-native image component and not expo-image component for native.

The app crashes because resizeMode is deprecated in expo-image and the entire high res image loaded into memory without any kind of resizing or scaling.

### What changes do you think we should make in order to solve the problem?
To mitigate the app crash on android, the resizeMode prop should only be applied to react-native image component and not expo-image. For expo-image component need to follow documentation and use relevant attributes to allow downscaling.

expo-image component has allowDownscaling prop
https://docs.expo.dev/versions/latest/sdk/image/#allowdownscaling

Also contentFit should be set instead of resizeMode
https://docs.expo.dev/versions/latest/sdk/image/#allowdownscaling

The resizeMode="contain" set in Lightbox is also passed to expo-image and can be removed
https://github.com/Expensify/App/blob/55af216a88233694e1e45117eeb0ff2ddde82480/src/components/Lightbox/index.tsx#L198

For Native:

The expo-image component set allowDownscaling={true} and contentFit={'contain'}

https://github.com/Expensify/App/blob/55af216a88233694e1e45117eeb0ff2ddde82480/src/components/Image/index.native.js#L37

For Web:
Pass resizeMode="contain" in the RNImage component

https://github.com/Expensify/App/blob/55af216a88233694e1e45117eeb0ff2ddde82480/src/components/Image/index.js#L48

The android app no longer crashes.

### What alternative solutions did you explore? (Optional)

**Comment by sourcecodedeveloper** [comment] 2024-02-12 12:33
@aimane-chnaif I was only able to crash on Android native and not any other platform. I tested using Pixel 4 Api 31 x84_64, Android 12.0 (release name S). The android consistently crashes simply run adb logcat > logcat.txt and try to upload the provided image.

**Comment by mvtglobally** [comment] 2024-02-13 04:57
Issue not reproducible during KI retests. (First week)

**Comment by jeremy-croff** [comment] 2024-02-13 05:47
> Issue not reproducible during KI retests. (First week)
I see you posted this on 20+ issues in a matter if minutes.

This is still reproducable.

**Comment by sakluger** [comment] 2024-02-15 00:44
@jeremy-croff, fyi @mvtglobally is one of our QA testers, so it's normal for them to leave all those comments. They run through a large set of regression tests weekly and comment on the issues where they can't reproduce the bug.

That being said, if you can still reproduce this, then we'll leave it open. Thanks for letting us know!

**Comment by sourcecodedeveloper** [comment] 2024-02-15 18:15
@aimane-chnaif When I was testing contentFit along with allowDownscaling on expo-image did resolve the crash. I can retest by removing allowDownscaling and only replacing resizeMode with contentFit to find out if the crash persists. Then allowDownscaling would be the only needed option to help prevent crash.

**Comment by sourcecodedeveloper** [comment] 2024-02-16 15:15
@aimane-chnaif I did some more testing and the findings are
1) resizeMode does not need to be replaced with contentFit but contentFit defaults to 'cover' when not defined, so when only resizeMode (deprecated) is specified with contentFit, the expo-image uses 'cover' for contentFit, when contentFit should be using 'contain' which is what the resizeMode is using. To help with the crash, resizeMode can be used alongside with contentFit and contentFit needs to be sit to 'contain'. I have tested by not specifiying contentFit and only resizeMode and the app crashes, using resizeMode alongside with contentFit="contain" the app does not crash.
2) allowDownscaling did not help prevent the crash.

**Comment by sourcecodedeveloper** [comment] 2024-02-19 17:02
@aimane-chnaif I have found two approaches for resolving the crash,
1) The react Image has resizeMethod prop which can be leveraged in the event the image size is high res or much larger than the view. Using either the 'resize' or 'auto' option also resolves the crash.
https://reactnative.dev/docs/image.html#resizemethod-android
The resizeMethod option is not available in expo-image component. To leverage the resizeMethod option, the solution would be to delete the index.native.js of the Image component so the index.js is used and then for RNImage pass resizeMethod="auto" along with resizeMode="contain". 

2) The expo-image can still be used for Android by passing contentFit='contain' (to prevent default value) alongside with resizeMode.

**Comment by sakluger** [comment] 2024-02-23 17:03
Hey @sourcecodedeveloper - do you have a full proposal you're ready to make on this one, or should we see if there are others who would like to work on it?

**Comment by sakluger** [comment] 2024-02-24 01:11
Got it, thanks. @aimane-chnaif what are your thoughts on @sourcecodedeveloper's question?

**Comment by sakluger** [comment] 2024-02-28 18:17
@aimane-chnaif bump.

**Comment by jsdev2547** [comment] 2024-02-29 08:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crashes on Android when user open high resolution image.
### What is the root cause of that problem?
The Image component for native (index.native.js) uses expo-image library for loading images on native.

https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/components/Image/index.native.js#L37

The native uses LightBox for displaying images. The lightbox passes resizeMode="contain" to the expo-image component
https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/components/Lightbox/index.tsx#L238

According to expo-image component documentation,
https://docs.expo.dev/versions/latest/sdk/image/#contentfit

If contentFit is not specified, contentFit defaults to 'cover' but if the image aspect ratio does not match the aspect ratio of the container, then the image will be clipped to fit and not resized or scaled. 

To mitigate the crash, need to set contentFit to 'contain' so the image is scaled down to fit the container box.

### What changes do you think we should make in order to solve the problem?
In the expo-image component,
https://github.com/Expensify/App/blob/48b24ec69b585d4fc660e9569a59d72aeb21c637/src/components/Image/index.native.js#L37

pass contentFit="contain"

I have tested and the high resolution image no longer crashes on Android.

### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-03-01 13:56
@aimane-chnaif When available, please also provide input on using contentFit="contain" alongside with resizeMode. I have tested and the crash is resolved.

**Comment by jsdev2547** [comment] 2024-03-05 09:50
@aimane-chnaif Only contentFit="contain" prop would need to be passed, the other property resizeMode="contain" is already passed and set correctly. The prop to add would be contentFit="contain".

The resizeMode is included in the "...rest" and I am suggesting to pass contentFit="contain",
https://github.com/Expensify/App/blob/9c49ab65db3f40e719c75516d5655f11b68c0f87/src/components/Image/index.native.tsx#L31
```
        <ImageComponent
            // eslint-disable-next-line react/jsx-props-no-spreading
            {...rest}
            contentFit="contain"
            source={imageSource}
            onLoad={(evt) => {
                const {width, height, url} = evt.source;
                dimensionsCache.set(url, {width, height});
                if (onLoad) {
                    onLoad({nativeEvent: {width, height}});
                }
            }}
        />
```
I have tested on latest main and the issue is still reproducible. I applied the solution directly to main branch and the issue does get resolved. Easiest to test would be to get latest main and then pass contentFit="contain" to ImageComponent and try loading high res image. The android app crashes simply by trying to upload the high res image. If still having difficulty please ask for branch again and I can prepare branch.

**Comment by sakluger** [comment] 2024-03-06 19:44
@jsdev2547 I was so confused where your earlier comments went, then I saw what you wrote in Slack about your `@sourcecodedeveloper` account. Good to see abck here you under the new profile!

**Comment by jsdev2547** [comment] 2024-03-06 20:34
@sakluger I was also puzzled as to what happened. I have not yet heard back from github support regarding what happened to the earlier comments, PR etc.

**Comment by sakluger** [comment] 2024-03-08 16:57
@aimane-chnaif do you have the time to prioritize this one? I want to make sure we're able to keep the urgency on this issue.

**Comment by jsdev2547** [comment] 2024-03-11 07:17
@aimane-chnaif I have revised the proposal and the effective approach is to update expo-image component.

https://github.com/Expensify/App/blob/bee752ac593f40d96391199f680b14466076ab9d/package.json#L106
"expo-image": "1.10.1",
to
"expo-image": "1.11.0",

https://github.com/expo/expo/blob/main/packages/expo-image/CHANGELOG.md
expo-image 1.11.0,
[Android] Adds automatic downsampling when the asset exceeds the hardware bitmap size limit.

I have tested and the crash is indeed resolved. Please use the following commit for testing,
https://github.com/Expensify/App/commit/a5c582e64dc5a75f1881b334ece1699f9619d9b9

**Comment by sakluger** [comment] 2024-03-13 00:16
@aimane-chnaif thoughts on the updated proposal?

**Comment by jsdev2547** [comment] 2024-03-13 22:43
@aimane-chnaif Thanks. The Pixel 2 was not crashing but I found another crash effecting Pixel 3 and 4 devices so I had to revise the proposal slightly. The reason for the crash in Pixel 3 and 4 was the lightbox component is multiplying the image width and height with PixelRatio, which is increasing the requestedHeight and requestedWidth sometimes doubling. I have tested thoroughly on Pixel 2, 3 and 4 using various high res images and did not come across any crashes.

**Comment by jsdev2547** [comment] 2024-03-18 21:11
@aimane-chnaif I have PR(https://github.com/Expensify/App/pull/38515) ready for review.

**Comment by jsdev2547** [comment] 2024-03-20 13:04
@aimane-chnaif I had to make another PR to resolve expo-image patches. PR(https://github.com/Expensify/App/pull/38671) is ready for review.

**Comment by tgolen** [comment] 2024-03-29 15:26
@jsdev2547 since #38671 was deployed to production, can this issue be closed? If not, what's the current status of this issue?

**Comment by tgolen** [comment] 2024-04-12 15:09
Now that it's past April 3, what needs to happen here?

**Comment by jsdev2547** [comment] 2024-04-15 06:07
@mountiny Please assist with payment. Also automation did not send offer, probably need to assign and unassign.

**Comment by sakluger** [comment] 2024-04-16 22:25
Summarizing payment on this issue:

Contributor: @jsdev2547 $500, sent Upwork offer: https://www.upwork.com/nx/wm/offer/101896672
Contributor+: @aimane-chnaif $500, sent Upwork offer: https://www.upwork.com/nx/wm/offer/101896675

**Comment by sakluger** [comment] 2024-04-17 23:57
Paid @jsdev2547, now just waiting for @aimane-chnaif to accept the offer.

**Comment by sakluger** [comment] 2024-04-19 17:32
Hey @aimane-chnaif could you please accept the Upwork offer?

**Comment by sakluger** [comment] 2024-04-22 17:38
Bumped Aimane in Slack.

**Comment by sakluger** [comment] 2024-04-23 21:05
Moving this to weekly since I'm not sure when Aimane will be back online. @aimane-chnaif feel free to DM me in Slack once you're back.

**Comment by sakluger** [comment] 2024-05-03 15:54
Still OOO.

**Comment by sakluger** [comment] 2024-05-16 19:00
Hey @muttmuure, assigning to you while I'm OOO for the next two weeks.

We still owe Aimane payment for this issue via Upwork, but he's been OOO for the past month or so and so he never accepted the Upwork offer. Can you keep an eye on this every once in a while, and if Aimane gets back before I return, please pay out the Upwork offer (or send a new one if the old one has expired)?

**Comment by sakluger** [comment] 2024-06-05 00:21
Welcome back! I just got back from OOO as well.

The contact is all paid out, we can close out this issue.

**Closed by sakluger** 2024-06-05 00:21 UTC
Labels: Reviewing, External, Engineering, Weekly, Awaiting Payment, Bug
