### ISSUE TITLE
[LOW] [Splits] [$500] Android – Notification about description/merchant/date changing shows old amount in the title

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37651] opened 2024-03-01 22:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4354410
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app.
2. Log in with a new Gmail account
3. As the secondary user - Request money to the main user
4. Navigate to the expense/transaction details conversation and send a message (this will subscribe the user to notifications)
5. Navigate away from the conversation
6. As the Secondary user - change the amount of the money request
7. As the Secondary user - change the description of the money request
8. Verify the money request recipient receives a notification for the edit action and look on it title

## Expected Result:
The notification title shows new amount from step 3

## Actual Result:
The notification title shows old amount from step 1

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/41a4fc24-f960-45e3-9387-2d0559f5b338

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b28c4e6f7663ce0</li>
        <li>Upwork Job ID: 1765788612568784896</li>
        <li>Last Price Increase: 2024-03-14</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2024-03-07 17:16
I'm pretty sure we can handle this externally

**Comment by zanyrenney** [comment] 2024-03-07 17:16
adding the label

**Comment by zanyrenney** [comment] 2024-03-11 12:07
looking for proposals here.

**Comment by zanyrenney** [comment] 2024-03-14 11:29
still waiting on proposals, will bump channel if we dont have any tomorrow!

**Comment by zanyrenney** [comment] 2024-03-18 14:59
still looking for proposals.

**Comment by zanyrenney** [comment] 2024-03-18 15:01
https://expensify.slack.com/archives/C01GTK53T8Q/p1710774087028929

**Comment by ikevin127** [comment] 2024-03-18 15:38
I'm pretty sure this is BE related as that's where the notifications are emitted from based on  what fields changed / updated.

**Comment by zanyrenney** [comment] 2024-03-18 15:49
going to look for the appropriate VIP/Wave

**Comment by nagypite** [comment] 2024-03-18 16:36
After some research it seems the outdated data is coming from Airship (specifically `roomName` property).

I've done some experiments to try to alter before the notification is triggered, but (a) had no success so far, (b) that feels more like a hack than a proper solution.

**Comment by zanyrenney** [comment] 2024-03-19 17:49
We uncovered this is a BE issue.

**Comment by zanyrenney** [comment] 2024-03-20 15:43
Will need to be handled by internal engineer. Added to the correct VIP.

**Comment by zanyrenney** [comment] 2024-04-02 14:27
@arielgreen Do you mind doing a call-out for an engineer, maybe hotpicks in your daily update for this one please as it must be handled internally?

**Comment by mallenexpensify** [comment] 2024-04-09 17:36
Removed `Help Wanted` since it's internal

**Comment by eVoloshchak** [comment] 2024-04-09 21:44
Not overdue, waiting for someone from the internal team to pick this

**Comment by zanyrenney** [comment] 2024-04-15 15:40
asked in the channel - here https://expensify.slack.com/archives/C05RECHFBEW/p1713195608742809

**Comment by zanyrenney** [comment] 2024-04-18 17:46
have bumped the channel

**Comment by zanyrenney** [comment] 2024-04-22 09:06
have been asking in the channel: 
<img width="462" alt="2024-04-22_10-05-08" src="https://github.com/Expensify/App/assets/56830058/5dcc1174-7213-4382-b2b1-acc1d246fd90">

also asked @arielgreen the curator to call it out in the update but it hasn't been called out yet.

**Comment by zanyrenney** [comment] 2024-04-25 09:43
still nothing, it's in the project board as unassigned.

I have tried:
- bumping the channel
- asking the curator to call it out (multiple times)

I am sort of stuck here without any way to move forward. @arielgreen are there engineers on this VIP team who could pick this up?

**Comment by zanyrenney** [comment] 2024-04-29 12:14
Keep bumping and part of VIP split project board but no volunteer yet. After May 1st release we may have more luck 🤞🏼

**Comment by zanyrenney** [comment] 2024-05-01 20:27
I have asked Ariel about this one in DM because I'm not sure how to move it forward.

**Comment by zanyrenney** [comment] 2024-05-07 13:14
No response from @arielgreen - @arielgreen any ideas on how this should be prioritised?

**Comment by zanyrenney** [comment] 2024-07-09 13:55
This is paused.

**Comment by mvtglobally** [comment] 2024-08-09 04:24
Issue not reproducible during KI retests. (First week)

**Comment by zanyrenney** [comment] 2024-08-12 19:06
Also can't repro. Going to close this out!

**Closed by zanyrenney** 2024-08-12 19:06 UTC
Labels: Monthly, Internal, Overdue, Bug, Hot Pick
