### ISSUE TITLE
[HOLD for payment 2024-12-05] [$250] WS switcher-Different back button behavior when creating workspace via + and Get started button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47603] opened 2024-08-17 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.21-4
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has no workspace.

1. Go to staging.new.expensify.com
2. Open workspace switcher.
3. Click + icon next to "Workspaces".
4. Click app back button on workspace editor page.
5. Note that app opens workspace switcher when returning from workspace editor after creating a workspace from workspace switcher.
6. Delete the workspace.
7. Go to Inbox.
8. Open workspace switcher.
9. Click Get started on "Create a workspace" modal.
10. Click app back button on workspace editor page.

## Expected Result:
App will open workspace switcher when clicking app back button after creating workspace from Create a workspace" modal (should display the same behavior as when the + button is used).

## Actual Result:
App returns to Account settings instead.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b6c6d620-376a-4c2e-8a41-e004ccafbd30

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013645bc6cec0aa80d</li>
        <li>Upwork Job ID: 1828169605427820408</li>
        <li>Last Price Increase: 2024-11-18</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 104995900</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-08-17 20:58
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-17 20:58
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-08-17 21:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different back button behavior when creating workspace via + and Get started button
### What is the root cause of that problem?
Here we are not passing `backTo` param of `createWorkspaceWithPolicyDraftAndNavigateToIt()`
https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/workspace/card/WorkspaceCardCreateAWorkspace.tsx#L22-L24
### What changes do you think we should make in order to solve the problem?
We should pass the current route to `backTo` param following the same pattern used [here](https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L37)
```
const activeRoute = Navigation.getActiveRouteWithoutParams();
App.createWorkspaceWithPolicyDraftAndNavigateToIt('', '', false, false, activeRoute)
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-17 21:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different back button behavior when creating workspace via + and Get started button
### What is the root cause of that problem?
Here we are not passing `backTo` param of `createWorkspaceWithPolicyDraftAndNavigateToIt()`
https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/workspace/card/WorkspaceCardCreateAWorkspace.tsx#L22-L24
### What changes do you think we should make in order to solve the problem?
We should pass the current route to `backTo` param following the same pattern used [here](https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L37)
```javascript
const activeRoute = Navigation.getActiveRouteWithoutParams();
App.createWorkspaceWithPolicyDraftAndNavigateToIt('', '', false, false, activeRoute)
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-08-17 21:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Different back button behavior when creating workspace via + and Get started button
### What is the root cause of that problem?
Here we are not passing `backTo` param of `createWorkspaceWithPolicyDraftAndNavigateToIt()`
https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/workspace/card/WorkspaceCardCreateAWorkspace.tsx#L22-L24
### What changes do you think we should make in order to solve the problem?
We should pass the current route to `backTo` param following the same pattern used for '+' button of `WorkspacesSectionHeader` [here](https://github.com/Expensify/App/blob/67ad466251078a3b54558a2ed84876ec2fe18608/src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx#L37)
```javascript
const activeRoute = Navigation.getActiveRouteWithoutParams();
App.createWorkspaceWithPolicyDraftAndNavigateToIt('', '', false, false, activeRoute)
```
Note we can wrap `App.createWorkspaceWithPolicyDraftAndNavigateToIt` with `interceptAnonymousUser` if we want to display sign in page when an anonymous user tries to create a workspace 
### What alternative solutions did you explore? (Optional)

**Comment by JmillsExpensify** [comment] 2024-08-21 12:51
Hmm interesting. I agree that's inconsistent. I think this comes down to whether we should move UP on pressing back or now. @marcaaron thoughts on this consideration? I can kind of see the argument that UP is a more valid action, so you should always be taken back to the workspace list.

**Comment by marcaaron** [comment] 2024-08-21 19:01
Not _too_ passionate about this one as it's a pretty specific set of actions the user will take to uncover this inconsistency and can't imagine anyone feeling too impeded by either result. Both bring you to a list of workspaces. Both lead to the option to create a new workspace if you choose to do that after you just created one (which is probably an uncommon action in any case).

Ignoring the rules of navigation for a second - I see the workspace selector as less of a "page" and almost more of a pop up selector menu from a UX POV so it doesn't really need to be something we can navigate back to.

**Comment by JmillsExpensify** [comment] 2024-08-21 19:29
> Ignoring the rules of navigation for a second - I see the workspace selector as less of a "page" and almost more of a pop up selector menu from a UX POV so it doesn't really need to be something we can navigate back to.

Cool, I agree with this. So then let's make sure that "back" goes to the workspace list for both of these cases.

**Comment by JmillsExpensify** [comment] 2024-09-04 14:03
Still waiting for proposals

**Comment by etCoderDysto** [comment] 2024-09-04 14:27
I have a proposal here https://github.com/Expensify/App/issues/47603#issuecomment-2294986203

**Comment by mananjadhav** [comment] 2024-09-04 17:20
> Cool, I agree with this. So then let's make sure that "back" goes to the workspace list for both of these cases.

@etCoderDysto Couldn't understand from your proposals if it covers the expected behavior ^

**Comment by etCoderDysto** [comment] 2024-09-05 08:24
> > Cool, I agree with this. So then let's make sure that "back" goes to the workspace list for both of these cases.
> 
> @etCoderDysto Couldn't understand from your proposals if it covers the expected behavior ^

@mananjadhav I have updated [my proposal](https://github.com/Expensify/App/issues/47603#issuecomment-2294986203) to cover the expected behaviour.

**Comment by wildan-m** [comment] 2024-09-07 07:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

WS switcher: Different back button behavior when creating workspace using the + and Get started button.

### What is the root cause of that problem?

Inconsistent call to `createWorkspaceWithPolicyDraftAndNavigateToIt` in `WorkspaceCardCreateAWorkspace.tsx` and `src/pages/WorkspaceSwitcherPage/WorkspacesSectionHeader.tsx`

### What changes do you think we should make in order to solve the problem?

I believe the back button should navigate to the previous route. Contrary to the previous suggestion, I suggest adding `activeRoute` to the `createWorkspaceWithPolicyDraftAndNavigateToIt` function call.

src/pages/workspace/card/WorkspaceCardCreateAWorkspace.tsx
```tsx
                onPress={() => {
                    const activeRoute = Navigation.getActiveRouteWithoutParams();
 
                    interceptAnonymousUser(() => App.createWorkspaceWithPolicyDraftAndNavigateToIt('', '', false, false, activeRoute)); 
                }}

```

Adding `interceptAnonymousUser` is optional, but I recommend including it to prevent other inconsistencies.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mananjadhav** [comment] 2024-09-08 20:50
Reviewing the proposals.

**Comment by mananjadhav** [comment] 2024-09-12 17:34
> I believe the back button should navigate to the previous route.

@JmillsExpensify To an extent even I agree with this. wdyt? Will review accordingly.

**Comment by etCoderDysto** [comment] 2024-09-12 17:54
**A kind reminder to C+:** My first proposal covers a solution to navigate user to the previous route as the issue report mentions. I only edited my proposal when the expected behaviour was changed. Please checkout [my proposal edit](https://github.com/Expensify/App/issues/47603#issuecomment-2294986203) that was made 3 weeks ago. 

<img width="1072" alt="Screenshot 2024-09-12 at 8 47 14 in the evening" src="https://github.com/user-attachments/assets/20c88789-3736-49d8-8b7e-59b8a68fb58c">

**Comment by wildan-m** [comment] 2024-09-12 19:26
> A kind reminder for C+: My first proposal covers a solution to navigate user to the previous route as the issue report mentions. I only edited my proposal when the expected behaviour was changed. Please checkout https://github.com/Expensify/App/issues/47603#issuecomment-2294986203 that was made 3 weeks ago.

@mananjadhav @JmillsExpensify  If that solution was chosen, I want to point out that the proposal was made 3 weeks ago before the `External` and `Help Wanted` labels were added (2 weeks ago), and the author later changed the solution (not adding it as alternative). I think the official evaluation should consider the solution after the external labels were added.

![image](https://github.com/user-attachments/assets/7ad84035-d374-4cc6-ab87-31ccdaf46c2a)

**Comment by mananjadhav** [comment] 2024-09-18 18:54
@JmillsExpensify Can you respond to this [question](https://github.com/Expensify/App/issues/47603#issuecomment-2346868438)?

**Comment by JmillsExpensify** [comment] 2024-09-25 17:20
Yes, the back button should navigate to the previous route. Sorry, missed this last week.

**Comment by JmillsExpensify** [comment] 2024-10-02 17:24
Not the highest priority, though I think we're still aligned that the back button is the previous route.

**Comment by mananjadhav** [comment] 2024-10-14 16:11
I'll review the proposals again on this one.

**Comment by mananjadhav** [comment] 2024-11-05 17:55
Missed this one. I'll check this by tomorrow.

**Comment by JmillsExpensify** [comment] 2024-11-20 17:41
Still waiting for proposal review

**Comment by mananjadhav** [comment] 2024-11-20 19:16
Sorry for the delay. I checked and I think the @etCoderDysto  [proposal](https://github.com/Expensify/App/issues/47603#issuecomment-2346907769) is good to go.

🎀 👀 🎀 C+ reviewed.

**Comment by JmillsExpensify** [comment] 2024-11-27 10:38
PR is merged

**Comment by mananjadhav** [comment] 2024-12-04 18:11
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<summary>Bug classification</summary>

Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. 

    Link to comment: Couldn't pinpoint the offending PR.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: NA

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [x] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1. Sign up with a new user
2. Click on workspace switcher
3. Click on Get started button
4. Click on back button
5. Verify that user is navigated to Chose a workspace modal

Do we agree 👍 or 👎

**Comment by mananjadhav** [comment] 2024-12-08 17:17
@JmillsExpensify Can you please post the payout summary so that I can raise the request?

**Comment by JmillsExpensify** [comment] 2024-12-09 09:52
Payment summary: 

- Contributor: $250 @etCoderDysto via Upwork
- Reviewer: $250 @mananjadhav via New Expensify

**Comment by JmillsExpensify** [comment] 2024-12-09 09:56
Contributor paid via Upwork, regression test created, and reviewer is paid via New Expensify. Closing this one.

**Closed by JmillsExpensify** 2024-12-09 09:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-10 12:52
$250 approved for @mananjadhav
