### ISSUE TITLE
Web – Payments– Unlike in other sections, the option modal to delete does not appear in the center of the window

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24303] opened 2023-08-09 02:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.	Open the "Settings" menu.
2.	Click on "Payments".
3.	Choose "Add Payment Method".
4.	Select "PayPal" as the payment method.
5.	After successfully adding the "PayPal" account, click on it.
6.	A modal will open with options to "Edit" and "Delete".
7.	It is noticed that, unlike other sections, the modal does not appear in the middle of the window.

## Expected Result:
Consistency is expected, where the modal should appear in the middle of the window.

## Actual Result:
The modal appears below the added account, whereas in other sections, the modal appears in the middle of the window.

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/1302f94c-9bdd-4469-849f-caacf72f6c30

https://github.com/Expensify/App/assets/43995119/34cf6f89-8cbe-45e3-8dcb-bd0642eb6296

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690960970084909

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment] 2023-08-09 02:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web – Payments– Unlike in other sections, the option modal to delete does not appear in the center of the window.

### What is the root cause of that problem?
We are using the `ConfirmContent` which shows in view.

### What changes do you think we should make in order to solve the problem?
We should replace it with the `ConfirmModal` component which is used in other places. It will be a plug & play change.

**Comment by DanutGavrus** [comment] 2023-08-09 07:15
@bernhardoj As per [this comment](https://github.com/Expensify/App/issues/19212#issuecomment-1572291617) from there, this was intentional back then and should have been fixed by implementing push to page behavior for payment methods change. Do you know it that has been implemented?

**Comment by puneetlath** [comment] 2023-08-11 15:40
I think the current guideline is that if we do decide it's something we want to address, we'll pay out like normal. If we decide not to do anything and close the issue, then no payout.

**Comment by muttmuure** [comment] 2023-08-14 14:38
https://github.com/Expensify/App/issues/19212#issuecomment-1572291617 

We said that changing this was dependent on implementation of push to page. Did we do that

**Comment by muttmuure** [comment] 2023-08-22 17:11
Going to close for now.

**Closed by muttmuure** 2023-08-22 17:11 UTC
Labels: Daily, Overdue, Bug
