### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250]  Expensify Card -App returns to card feed selection page after issuing card from member profile

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50243] opened 2024-10-04 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Bank account is already set up in Expensify Card page.
- Company card feature is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Click on any member.
4. Click New Card.
5. Click Expensify Card.
6. Go through the setup process.
7. Click Issue card on the confirmation page.

## Expected Result:
App will return to member profile page after issuing card from member profile.

## Actual Result:
App returns to card feed selection page after issuing card from member profile.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/2a265016-f82f-4283-bf56-2e6bff607003

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843172551777303100</li>
        <li>Upwork Job ID: 1843172551777303100</li>
        <li>Last Price Increase: 2024-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 104321384</li>
<li>abzokhattab | Contributor | 104321385</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-10-04 14:21
We think that this bug might be related to #wave-collect - Release 2

**Comment by IuliiaHerets** [comment] 2024-10-04 14:21
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-10-07 06:12
I'm not sure if this needs to be a backend but since we have a proposal let's start with External

**Comment by mountiny** [comment] 2024-10-08 11:57
@koko57 @VickyStash can you look at the proposals? I think this must be regression from adding the select feed option

**Comment by koko57** [comment] 2024-10-08 12:06
@mountiny @paultsimura I agree with @paultsimura - @abzokhattab proposal looks good. We're using this pattern quite frequently and it doesn't cause any problems with normal back button behaviour. 

@cretadn22 could you please add some evidence (screen recording) that it doesn't work as expected and breaks the navigation?

**Comment by narefyev91** [comment] 2024-10-08 12:12
Agree with @paultsimura - that's why backTo was introduced - we have a lot of pages which may start the same workflows from different starting point. And when user comes to the last step of the workflow - navigation should move them back to the initial screen

**Comment by koko57** [comment] 2024-10-08 12:25
just tested it and it's working
https://github.com/user-attachments/assets/ff532155-a7f2-4963-939e-60c1e4e48311

**Comment by mountiny** [comment] 2024-10-08 12:48
yep agreed, great job figuring this out

**Comment by mountiny** [comment] 2024-10-08 14:04
@abzokhattab can you please raise the PR? thanks!

**Comment by Christinadobrzyn** [comment] 2024-10-15 08:44
Looks like the PR is in staging so we're getting close! https://github.com/Expensify/App/pull/50597

**Comment by Christinadobrzyn** [comment] 2024-10-15 08:45
Looks like the PR is in staging so we're getting close! https://github.com/Expensify/App/pull/50597

**Comment by Christinadobrzyn** [comment] 2024-10-22 05:10
Payment coming in a few days so I'm going to move this to daily so I don't miss it

**Comment by Christinadobrzyn** [comment] 2024-10-23 02:01
Prepping for payment...

- [ ] Contributor: $250 @abzokhattab (Upwork offer - https://www.upwork.com/nx/wm/offer/104321385)
- [ ] Reviewer: $250 @paultsimura (Upwork offer - https://www.upwork.com/nx/wm/offer/104321384)

Regression test - https://github.com/Expensify/Expensify/issues/438129

**Comment by Christinadobrzyn** [comment] 2024-10-24 02:56
Payment day! Paid out based on this summary - https://github.com/Expensify/App/issues/50243#issuecomment-2430662549 

Closing

**Closed by Christinadobrzyn** 2024-10-24 02:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
