### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] IOU - Request money is not successful after refreshing in confirm page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28347] opened 2023-09-27 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Click on + button and request money
3. Upload an image for receipt
4. Refresh the page
5. Press the request button

## Expected Result:
Money should be requested and it should show scanning

## Actual Result:
 Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/81e77d81-7fd8-4fab-90d4-fd349c9cf4c2

https://github.com/Expensify/App/assets/78819774/ca400e31-186f-4f31-b392-86e05b68e910

**Expensify/Expensify Issue URL:**

**Issue reported by:** @alitoshmatov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694717028781839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e5061c23f7df911</li>
        <li>Upwork Job ID: 1707121850103009280</li>
        <li>Last Price Increase: 2023-09-27</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27022006</li>
<li>DylanDylann | Contributor | 27022008</li>
<li>alitoshmatov | Reporter | 27022010</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-09-27 19:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Request money is not successful after refreshing in confirm page
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/446f29b7d47b3dc60dc0b16d7a4adddd0127b58c/src/pages/iou/ReceiptSelector/index.js#L84

In the web, we are creating a new Object URL to save the file. But when we reload the page that object URL is removed (reference for this point: https://stackoverflow.com/questions/13966186/how-long-does-a-blob-persist)
### What changes do you think we should make in order to solve the problem?
Let's see another place where we also use a new Object URL to save the file

https://github.com/Expensify/App/assets/141406735/604a1fa1-c0c6-447a-a64d-18c0a0a569fe

In adding an attachment, when reloading we hide the selected attachment modal. So, I suggest that we check if the url Object is removed, we will redirect to ReceiptSelector page. To do that, in here
https://github.com/Expensify/App/blob/144e932c2ea863bffafbd26e9cc7602e89b1e352/src/pages/iou/steps/MoneyRequestConfirmPage.js#L75

Add this code to check objectURL is valid or not

```
if (props.iou.receiptPath && props.iou.receiptSource) {
            FileUtils.readFileAsync(props.iou.receiptPath, props.iou.receiptSource).then((receipt) => {
                if (!receipt) {
                    const fallback = ROUTES.getMoneyRequestRoute(iouType.current, reportID.current);
                    Navigation.goBack(fallback);
                } else {
                    setReceiptState(receipt)
                }
            });
        }
```

And then in here
https://github.com/Expensify/App/blob/144e932c2ea863bffafbd26e9cc7602e89b1e352/src/pages/iou/steps/MoneyRequestConfirmPage.js#L205
we only need to check receiptState and request money
```
if (receiptState) {
                requestMoney(selectedParticipants, trimmedComment, receiptState);
                return;
            }
```

### What alternative solutions did you explore? (Optional)
We can save uploaded files to localStorage

**Comment by mollfpr** [comment] 2023-09-28 10:32
@DylanDylann Does your alternative solution use Onyx to save the URL object? The better fix should make the submit still processable.

**Comment by DylanDylann** [comment] 2023-09-29 07:32
@mollfpr I can't reproduce this bug when reloading the App redirects to the initial page. Do you want to fix as suggestion here

> The better fix should make the submit still processable.

**Comment by mollfpr** [comment] 2023-09-29 13:00
>In adding an attachment, when reloading we hide the selected attachment modal. So, I suggest that we check if the url Object is removed, we will redirect to ReceiptSelector page.

@DylanDylann The expected result should keep the user on the same page after reloading and the submit request is successful. From your RCA the issue is because the object URL is removed after reloading, so I'm thinking your alternative solution is to keep the object URL and set it back.

**Comment by DylanDylann** [comment] 2023-10-02 06:22
We need to wait for this reverted PR https://github.com/Expensify/App/pull/28410 to be merged. So we can move forward this bug

**Comment by mollfpr** [comment] 2023-10-02 14:10
@DylanDylann Where's the revert issue?

**Comment by DylanDylann** [comment] 2023-10-03 04:42
@mollfpr We had a blocker that blocked this issue on the main yesterday. But now It is resolved. Please ignore the above comment

**Comment by DylanDylann** [comment] 2023-10-03 06:04
@mollfpr 
> The expected result should keep the user on the same page after reloading and the submit request is successful.

To do that, I have 2 suggestions:
1. Created new API to update receipt image to server when user uploading image
2. Using FileSystem API  `you'll need to request PERSISTENT storage, and the user will have to agree to let you store data on their machine permanently.`

I understand the benefit from your viewpoint But both ways are complicated. I see It's a bit overkill for this issue. Note that 
1. when the user uploads the receipt image and close modal we also remove the uploaded image 
2. When the user uploads attachment then reloading, this attachment also be removed

Anyways, Let's confirm the expected before moving forward. 

@shawnborton Please help to give some thought from UX perspective on this issue.

**Comment by shawnborton** [comment] 2023-10-03 14:47
Hmm I am a bit confused here about this one. @alitoshmatov since you reported this one, can you walk me through when exactly you think a user would experience this? I am having a hard time understanding why a user would refresh the app after they upload a receipt.

**Comment by mollfpr** [comment] 2023-10-04 15:32
Thanks @DylanDylann. It seems reasonable to redirect the user back.

@luacmartins I think you already agree with the expected result, and the [proposal](https://github.com/Expensify/App/issues/28347#issuecomment-1737991760) looks good!

🎀 👀 🎀 C+ reviewed!

**Comment by luacmartins** [comment] 2023-10-04 16:21
Thanks for the link @aimane-chnaif. We'll refactor navigation for multi-step flows, but I still think the changes to readFileAsync mentioned in this proposal are good and shouldn't overlap with that refactor, so I think we can move on with this issue.

**Comment by DylanDylann** [comment] 2023-10-05 07:21
@mollfpr The PR is ready for review

**Comment by johncschuster** [comment] 2023-10-20 10:56
Waiting to issue payment on `2023-10-25`

**Comment by mollfpr** [comment] 2023-10-25 13:51
> [@luacmartins] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/23770


> [@luacmartins] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/23770/files#r1371795681

> [@luacmartins] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr / @DylanDylann] Determine if we should create a regression test for this bug.
 [@mollfpr / @DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**_Only testable in Web, mWeb, and Desktop._**

1. Clicking + (FAB) Button
2. Clicking on the scan request
3. Upload an image for receipt
4. Go to a confirmation page
5. Refresh the page
6. Verify that the App navigates back to the Scan Request Page
7. 👍 or 👎

---

@johncschuster Could you give us the payment summary? I'll request the payment in NewDot, thanks!

**Comment by luacmartins** [comment] 2023-10-25 18:15
Thanks for filling the checklist. 👍 to the regression tets

**Comment by mollfpr** [comment] 2023-10-27 07:28
@johncschuster Could you give us the payment summary? Thank you!

**Comment by luacmartins** [comment] 2023-10-30 16:33
Just pending payment

**Comment by johncschuster** [comment] 2023-10-30 16:33
On it!

**Comment by johncschuster** [comment] 2023-10-31 00:16
# Payment Summary:

 External issue reporter: @alitoshmatov - $50 - paid via Upwork
 Contributor that fixed the issue: @DylanDylann - $500 - paid via Upwork
 Contributor+ that helped on the issue and/or PR: @mollfpr - $500 - paid via manual request

**Comment by johncschuster** [comment] 2023-10-31 00:18
Payment has been issued via Upwork

**Closed by johncschuster** 2023-10-31 00:18 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-01 20:13
$500 payment approved for @mollfpr based on summary above.
