### ISSUE TITLE
[$125] Profile - The character limit has not been increased to 100 characters

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43865] opened 2024-06-17 20:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84_2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4632338
**Email or phone of affected tester (no customers):** albertodege+2024@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite: The user is logged in to the website.
1. Navigate to the Legal name page
2. Enter a a long name (>100 characters) and save and save
3. Verify there's an error about character limit exceeded

## Expected Result:
The user should not be able to submit a legal name that is longer 100 characters

## Actual Result:
The character limit has not been increased to 100 characters

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![characters_limit](https://github.com/Expensify/App/assets/78819774/f483b3c8-9753-42c7-b6f5-7ea32258aab2)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01125f9cbfc0be0653</li>
        <li>Upwork Job ID: 1803119001279122354</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by lanitochka17** [comment] 2024-06-17 20:33
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sakluger** [comment] 2024-06-18 17:33
This is a very simple change so I'm going to set the price to $125.

**Comment by msuleman526** [comment] 2024-06-18 20:47
You said enter the long name greater then 100 characters.
So first you have to set the limit to 100 in constant file.

And then we have to change the if condition 
name.count < MAX_NAME_COUNT {
// comment : Name must be greater then 100 characters

**Comment by msuleman526** [comment] 2024-06-18 20:51
Contributor Details: 
Expensive account Email: suleman.muh526@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c87dbd15282b0aef

**Comment by msuleman526** [comment] 2024-06-18 20:52
Or if you just want to check name should not be greater then 100 then we can only change the limit in constant file

**Comment by Sparth19** [comment] 2024-06-18 22:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
legal name (legal first name and legal last name) max character length should be 100.

### What is the root cause of that problem?
As per the code, current limit is only 40 characters.

https://github.com/Expensify/App/blob/11b66a04015d137f90d80b16714935bf044a750b/src/CONST.ts#L166-L168

### What changes do you think we should make in order to solve the problem?
We should change MAX_LENGTH to 100. it will be used by 
https://github.com/Expensify/App/blob/11b66a04015d137f90d80b16714935bf044a750b/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L56

and 

https://github.com/Expensify/App/blob/11b66a04015d137f90d80b16714935bf044a750b/src/pages/settings/Profile/PersonalDetails/LegalNamePage.tsx#L73

**Comment by Sparth19** [comment] 2024-06-18 22:44
Contributor details 
Expensify account email: parthshekhaliya18@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~012b39c24ce0019a98?mp_source=share

**Comment by sakluger** [comment] 2024-06-21 23:10
Great find, @hoangzinh! According to https://github.com/Expensify/App/issues/39591, the expected result is:

> The frontend and backend character limit for the legal name field should be the same. Let's update the character limit on the front-end to 40 to match the backend.

I created an issue to update the TestRail test case. Otherwise, we can close this issue.

**Closed by sakluger** 2024-06-21 23:10 UTC
Labels: External, Daily, Help Wanted, Bug
