### ISSUE TITLE
[HOLD for payment 2023-09-06] [$500] Attachments - Navigation arrows are not shown on PDF until navigated to an image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24375] opened 2023-08-10 15:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Select a chat that has attached images and pdf
3. Open a PDF

## Expected Result:
The navigation arrows are displayed

## Actual Result:
The navigation arrows are not shown until I swipe to an image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.52.3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/877d8197-092f-4838-9b0a-3558f78a9b7c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01373e4d2b9f6c1a7d</li>
        <li>Upwork Job ID: 1689735843772346368</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26199945</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-08-10 15:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
Set the default value for isPinchGestureRunning to false.

### What alternative solutions did you explore? (Optional)
None.

**Comment by puneetlath** [comment] 2023-08-15 18:48
@rushatgabhane thoughts on the proposal?

**Comment by rushatgabhane** [comment] 2023-08-18 04:57
@tienifr does pdf zooming using pinch even work on native?

**Comment by rushatgabhane** [comment] 2023-08-18 08:38
cool, let's go with @tienifr's proposal https://github.com/Expensify/App/issues/24375#issuecomment-1675713255 then

C+ reviewed 🎀 👀 🎀

**Comment by puneetlath** [comment] 2023-08-31 20:11
@rushatgabhane friendly reminder about the checklist so that we can pay next week. Thanks!

**Comment by puneetlath** [comment] 2023-09-07 21:48
@rushatgabhane bump on the checklist.

**Comment by puneetlath** [comment] 2023-09-11 15:34
@rushatgabhane bump again on the checklist so that we can pay this out. Thanks!

**Comment by puneetlath** [comment] 2023-09-12 16:10
Payment summary: 
- Contributor @tienifr paid $500 via Upwork
- C+ @rushatgabhane due $500 via NewDot

**Comment by puneetlath** [comment] 2023-09-12 16:11
Issue to add regression test: https://github.com/Expensify/Expensify/issues/316113

**Comment by puneetlath** [comment] 2023-09-15 19:03
Dropping to weekly. Just waiting on @JmillsExpensify for payment.

**Comment by puneetlath** [comment] 2023-09-16 21:03
I believe the process if or @JmillsExpensify to close the issue when he pays. Is that right @JmillsExpensify or can I go ahead and close it once they've made the request?

**Comment by JmillsExpensify** [comment] 2023-09-16 21:29
Feel free to close this issue. I don't need it open for tracking purposes.

**Closed** 2023-09-18 17:47 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-07 15:10
$500 payment approved for @rushatgabhane based on BZ summary.
