### ISSUE TITLE
[HOLD for payment 2023-02-03] URLs does not show on the bottom left on hovering the texts with links in Personal Information page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13999] opened 2023-01-05 01:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to Profile > Workspace > Connect a bank account > Connect manually
2. Enter a valid routing number and account number
3. Click save & continue
4. Fill the form in company information page
5. Click save & continue
6. In personal information page, hover over the texts with links in the bottom

## Expected Result:
URLs are displayed in the bottom left for the texts with links

## Actual Result:
URLs are not displayed in the bottom left for few texts with links i.e. Onfido's Facial Scan Policy and Release, Privacy policy and Terms of service.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.48-2
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210678989-72e3a02d-8f0d-4104-ae5f-1ea2b734bbe5.mov

https://user-images.githubusercontent.com/43996225/210679001-6bfd99c9-dbe5-4d1e-9e61-3450b6020c8f.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670245685889779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0146c161b3563d7012</li>
        <li>Upwork Job ID: 1612416224676945920</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by MonilBhavsar** [comment] 2023-01-06 16:45
Pushed a quick fix to compensate for a tough day

**Comment by MonilBhavsar** [comment] 2023-01-09 05:01
PR in review

**Comment by dylanexpensify** [comment] 2023-01-09 14:18
@Santhosh-Sellavel when you have a moment, would you give us an eta on when you plan to review? Thank you!

**Comment by Santhosh-Sellavel** [comment] 2023-01-09 14:49
@dylanexpensify PR is merged already

**Comment by MonilBhavsar** [comment] 2023-01-13 15:00
PR is deployed to Production too.
@dylanexpensify can we please issue the payment for reviewing the PR to @Santhosh-Sellavel and close the issue

**Comment by dylanexpensify** [comment] 2023-01-13 15:12
Nice! Please apply then @adeel0202 !!

**Comment by MonilBhavsar** [comment] 2023-01-13 15:30
@dylanexpensify also, let's add this to regression testing (On Web). Basically all the pages with hyperlinks should display URL's in the bottom left corners. List of pages:

1. About (Settings > About)
2. Bank Account steps (Workspace > Connect Bank account)

**Comment by dylanexpensify** [comment] 2023-01-13 15:32
@adeel0202 I'll invite you!

**Comment by dylanexpensify** [comment] 2023-01-13 15:33
@adeel0202 sent invite

**Comment by dylanexpensify** [comment] 2023-01-17 11:38
@adeel0202 payment sent, contract closed! 
@Santhosh-Sellavel sent offer!

**Comment by dylanexpensify** [comment] 2023-01-18 13:43
Payment sent and contract ended @Santhosh-Sellavel !

**Comment by dylanexpensify** [comment] 2023-01-18 13:50
RT buddy check posted [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1674049730286939)

**Comment by tgolen** [comment] 2023-01-18 18:09
I'm sorry I'm late to this party, but _WHY_ do we want those links to display in the bottom left? The description of this issue seems to assume that the reason must be apparent, but I don't know why we want or need that. 

Furthermore, I think this behavior is now a bit inconsistent throughout the app. When it came to links inside of comments, we opted to display a tooltip above the link which shows the full URL of the link (to give some protection against nefarious links). I think we should handle all links the same. Either use tooltips for them all, or use the native browser hover for them all.

Lastly, there are three more links on other pages that also need the same fix applied. Two of them in `ShortTermForms.js` and one in `LongTermsForm.js`.

**Comment by dylanexpensify** [comment] 2023-01-19 09:48
Alright, coming back here to recap: 
- we'll be keeping this open while we suss out other areas for this bug. 
- while everyone has been paid, we still expect the C+ to see this through with it's new scope
- adding RT posted above, but we will update as we find more areas

Any issues or concerns, ping here! cc @MonilBhavsar @Santhosh-Sellavel

**Comment by MonilBhavsar** [comment] 2023-01-19 10:54
> I'm sorry I'm late to this party, but WHY do we want those links to display in the bottom left? The description of this issue seems to assume that the reason must be apparent, but I don't know why we want or need that.

Hmm, it's the default behaviour, and I noticed hovering was working fine on another bank setup page, and settings page. And, we were not using the correct component in this page.

> Furthermore, I think this behavior is now a bit inconsistent throughout the app. When it came to links inside of comments, we opted to display a tooltip above the link which shows the full URL of the link (to give some protection against nefarious links). I think we should handle all links the same. Either use tooltips for them all, or use the native browser hover for them all.

Good point! I missed chat messages. Yes, we have tooltip for links in chat message, and it works for desktop app and desktop browser. I think that - on browser, the link being displayed in the corner is the default behaviour, so the tooltip fixes the issue(to give some protection against nefarious links) for the desktop app only. So I am not sure if it is worth. I feel like to give protection to users against nefarious links, and across all platforms, we should have an intermediate page and display a warning that reads "You're being redirected to this site from app" (google does like this) with the ability to toggle this setting on or off, and kill tooltip in parallel.

> Lastly, there are three more links on other pages that also need the same fix applied. Two of them in ShortTermForms.js and one in LongTermsForm.js.

Looking now...

**Comment by MonilBhavsar** [comment] 2023-01-19 12:09
Good catch Tim! I missed the terms and fees page. But, noticed that the links aren't working properly.
I have asked here https://expensify.slack.com/archives/C03U7DCU4/p1674130044750449

Will fix both issues together.

**Comment by dylanexpensify** [comment] 2023-01-23 11:44
@MonilBhavsar any updates?

**Comment by MonilBhavsar** [comment] 2023-01-24 06:43
One of the remaining place will be fixed by the PR.
And, we can the discuss [this](https://github.com/Expensify/App/issues/13999#issuecomment-1396783233) and create a new feature request issue

**Comment by dylanexpensify** [comment] 2023-02-06 10:19
Working on this today!

**Comment by MonilBhavsar** [comment] 2023-02-06 12:39
@tgolen should we bring this to slack to get more thoughts?
https://github.com/Expensify/App/issues/13999#issuecomment-1396783233

**Comment by tgolen** [comment] 2023-02-06 15:50
I think that'd be great, yes!

**Comment by MonilBhavsar** [comment] 2023-02-08 13:32
Posted here https://expensify.slack.com/archives/C01GTK53T8Q/p1675863109333139

**Comment by dylanexpensify** [comment] 2023-02-13 15:12
@MonilBhavsar when you have a free moment, would you mind posting a recap of where that convo landed? 🙏

**Comment by MonilBhavsar** [comment] 2023-02-15 05:23
The idea is to do nothing for now

**Comment by dylanexpensify** [comment] 2023-03-03 13:32
bump on above @MonilBhavsar 🙇

**Comment by MonilBhavsar** [comment] 2023-03-03 15:17
Oops, sorry I missed this ping. Yes we can close this now.
All pages are fixed and for now we decided to do nothing

**Closed by MonilBhavsar** 2023-03-03 15:17 UTC
Labels: Weekly, Internal, Awaiting Payment, Bug
