### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] BA - Personal information / Beneficial Form entered offline isn't saved after returning online

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31612] opened 2023-11-21 10:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to staging.new Expensify.com or open Expensify App
2. Login with expensifail account
3. Go to existing or create new workspace
4. Go to Settings > Workspace > Bank Account
5. Select any connection type
6. Follow the flow until Personal Information page or Beneficial form page
7. Go offline
8. Fill out form
9. Reload page for web or kill app for apps
10. Go online
11. Go Settings > Workspace > Bank Account
12. Click / Tap 'Continue with setup'

## Expected Result:
Information on Personal Information page or Beneficial form page entered offline should be saved

## Actual Result:
Information on on Personal Information page or Beneficial form page was NOT saved

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/47b214cb-89f9-44e9-8337-dfae511e9311

https://github.com/Expensify/App/assets/115492554/5afe71d7-439f-4fd9-9b27-6350c9f21c1e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172d17b769e15f37c</li>
        <li>Upwork Job ID: 1726917672947712000</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @madmax330</details>

**Comment by izarutskaya** [comment] 2023-11-21 10:59
Not repro on production

https://github.com/Expensify/App/assets/115492554/bbc3507e-4cfe-4763-9569-5c7af354ecb5

**Comment by s-alves10** [comment] 2023-11-21 11:50
Looks like a regression of the PR https://github.com/Expensify/App/pull/30568

**Comment by s77rt** [comment] 2023-11-21 12:19
We already have a PR that's adding the draft functionality https://github.com/Expensify/App/pull/31401 cc @kowczarz

**Comment by luacmartins** [comment] 2023-11-21 19:00
@tienifr are you still able to work on a fix for this? I know we already have a PR adding drafts back to FormProvider, but that PR's main focus is something else and it seems like it won't get merged soon.

**Comment by luacmartins** [comment] 2023-11-21 20:51
I'm gonna demote this to NAB. This is an existing issue with all forms using FormProvider and we have a fix for it [here](https://github.com/Expensify/App/pull/31401)

**Comment by luacmartins** [comment] 2023-11-22 18:17
Not needed anymore. I added this issue to the list of fixed issues in https://github.com/Expensify/App/pull/31401

**Comment by s77rt** [comment] 2023-11-23 19:03
This is mostly fixed by https://github.com/Expensify/App/pull/30525. The form is being saved correctly now except the date of birth which I think will be fixed in a follow up PR.

**Comment by s77rt** [comment] 2023-11-29 13:38
The checklist above ^ is not due yet. This issue is not totally fixed yet

**Comment by s77rt** [comment] 2023-11-29 13:38
@luacmartins Can you please remove the `Awaiting Payment` label?

**Comment by s77rt** [comment] 2023-11-29 13:40
@kowczarz Would you like to handle this? Since it's seems a regression from https://github.com/Expensify/App/pull/29098 (ref: https://github.com/Expensify/App/pull/31401#issuecomment-1824820003)

**Comment by kowczarz** [comment] 2023-12-07 14:00
Yes, I will prepare a followup PR in following days.

**Comment by abekkala** [comment] 2023-12-19 21:30
@sakluger 

### STATUS: 
I'm ooo through Jan 02

This is at the finish line and a PR has already been deployed to staging. after production the waiting period for payment will begin. 

- Issue reported by: Applause-Internal Team
- Fix: @kowczarz
- PR Review: @s77rt

**Comment by s77rt** [comment] 2023-12-22 22:34
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29098
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29098#discussion_r1435365362
- A discussion in #expensify-bugs has been started: not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**

1. Open App
2. Create a workspace if you don't have one
3. Go to Settings > Workspaces > workspace > Bank Account
4. Click Connect manually
5. Follow the flow until you reach the "Company information" step
6. In incorporation date, select any date
7. Refresh the page or restart the flow
8. Verify that the selected date is preserved

**Comment by sakluger** [comment] 2024-01-02 05:00
@s77rt I sent you an offer via Upwork. Please let me know once you've accepted, thanks!

**Comment by s77rt** [comment] 2024-01-02 13:57
@sakluger  Accepted! Thanks!

**Comment by sakluger** [comment] 2024-01-02 17:05
Perfect, thanks! All paid out, thanks everyone 🙇

**Closed by sakluger** 2024-01-02 17:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
