### ISSUE TITLE
Web - Focus Mode popup is not closed by device back button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52467] opened 2024-11-13 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52072
**Email or phone of affected tester (no customers):** testpayment935+609@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. In an account with "Focus" mode enabled, change the mode to "Most Recent"
2. Type "Onyx.set("focusModeNotification",true);" in console and get focus mode notification instantly
3. Use device back button try to close focusMode popup

## Expected Result:
Using device back button when focusMode popup is visible, focusMode popup should be closed.

## Actual Result:
FocusMode popup is not closed by device back button.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/f0041f4f-f827-470b-ba60-6dd138721476

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-11-13 12:21
This might be expected as for web the modal should close on press of esc only
https://github.com/Expensify/App/blob/d1e30bbd68dce79a4559e522f0822cb628e6b17a/src/components/Modal/BaseModal.tsx#L230

**Comment by ChavdaSachin** [comment] 2024-11-13 13:12
Yes this is expected here, Backspace button on keyboard does not count as device back button.
Despite see

> Test 2.
> 
> 1. Get focusModeNotification (steps mentioned above).
> 2. Use device back button when focusMode popup is visible and verify focusMode popup is closed.
> 
> (Test 2 might not work on web and mweb see [#51432 (comment)](https://github.com/Expensify/App/issues/51432#issuecomment-2455759523) and [#51432 (comment)](https://github.com/Expensify/App/issues/51432#issuecomment-2456224161))

So right now Test 2 is super specific to Android Native.

**Comment by lschurr** [comment] 2024-11-13 19:16
Closing since this is expected behavior.

**Closed by lschurr** 2024-11-13 19:16 UTC
Labels: Daily, Bug
