### ISSUE TITLE
Travel - Expensify Travel page opens with delay, "Something went wrong" error

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46971] opened 2024-08-07 14:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

Issue found when executing PR: https://github.com/Expensify/App/pull/46333
## Action Performed:
1. Account B: Navigate to https://staging.new.expensify.com/
in Chrome incognito
2. Account B: Log in with a new expensifail account
3. Account A: Navigate to https://staging.new.expensify.com/
in Chrome
4. Account A: Log in with a new expensifail account
5. Account B: Create a workspace
6. Account B: Navigate to Account settings - Workspaces - Created workspace - Members
7. Account B: Click on "+ Invite member"
8. Account B: Invite account A
9. Account A: Navigate to FAB - Book travel
10. Account A: Click on the "Book travel" button
11. Account A: Type "123" into Address line 1 and choose any of the suggested addresses
12. Account A: Click on the "Save" button
13. Account A: Click on the "Book travel" button
14. Account A: Click insode the TOS checkbox
15. Account A: Click on the "Continue" button a few times until the Travel page opens

## Expected Result:
Expensify Travel page should open instantly. The "Before we continue..." RHP should close in ND.
## Actual Result:
Expensify Travel page opens with a delay of 3-4 seconds. "Something went wrong. Please try again later." error message appears above the "Continue" button after clicking it a few times.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/06a2cb57-ac7a-4553-a837-d2777817470e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-07 14:15
We think that this bug might be related to #vip-travel

**Comment by trjExpensify** [comment] 2024-08-07 15:12
@shubham1206agra @rushatgabhane @stitesExpensify this deploy blocker was created when executing this PR: https://github.com/Expensify/App/pull/46333

**Comment by trjExpensify** [comment] 2024-08-07 15:16
Also, @puneetlath @AndrewGable travel is behind a beta, so I think we can demote this as a deploy blocker.

**Comment by stitesExpensify** [comment] 2024-08-09 20:57
@rushatgabhane are you taking a look at this?

**Comment by rushatgabhane** [comment] 2024-08-09 21:01
@stitesExpensify i cannot reproduce this

**Comment by stitesExpensify** [comment] 2024-08-12 21:35
@IuliiaHerets can you please try this again with a brand new account?

**Comment by IuliiaHerets** [comment] 2024-08-13 04:31
@stitesExpensify our team will check this and I will get back to you with the actual result.

**Comment by IuliiaHerets** [comment] 2024-08-13 11:48
@stitesExpensify QA Team still can reproduce the issue

https://github.com/user-attachments/assets/adaf1bf8-cbf5-4210-a8ce-d031f0553a90

**Comment by rushatgabhane** [comment] 2024-08-13 12:50
@stitesExpensify the authCide is being returned. 

So I'm guessing after clicking book travel multiple times, the final API call was successful 

Is it possible that the policy has not been provisioned on spotnana? 

@stitesExpensify sorry im not able to figure out what could be causing this bug. I think we'll have to see the logs

**Comment by stitesExpensify** [comment] 2024-08-13 22:06
> Click on the "Continue" button a few times until the Travel page opens

Based on this I'm thinking that it has something to do with the temporary auth tokens that we use to log in on spotnana. IMO the best solution is to disable the button and show a loading indicator until we get a response from the request so that:
1. The user knows something is happening and doesn't get frustrated
2. We don't allow sending a bunch of provision requests all at once

Thoughts @Expensify/design ?

**Comment by dubielzyk-expensify** [comment] 2024-08-13 23:41
Hmm. Yeah I don't mind the idea of turning it into a spinner button while it's loading. That being said we can also limit the requests being sent without telling the user or changing the button. I think I'm still leaning towards doing the loading button for this:

![CleanShot 2024-08-14 at 09 41 08@2x](https://github.com/user-attachments/assets/cc032d8c-2590-432c-996f-3d2e5f324aa1)

Keen to hear what the other designers think though

**Comment by shawnborton** [comment] 2024-08-14 01:49
Yup, I agree with that Jon.

**Comment by dannymcclain** [comment] 2024-08-14 13:48
Same!

**Comment by rushatgabhane** [comment] 2024-08-14 13:55
sounds good 👍

Will add a loading state to the button

**Comment by puneetlath** [comment] 2024-08-19 21:16
How's it going @rushatgabhane?

**Comment by rushatgabhane** [comment] 2024-09-16 06:27
we're good to close this. pr on production last month

**Comment by puneetlath** [comment] 2024-10-10 15:17
Sorry about that @aimane-chnaif. I've sent you an offer. Please ping me here when you've accepted it. https://www.upwork.com/nx/wm/offer/104357498

**Comment by puneetlath** [comment] 2024-10-23 15:16
Paid!

**Closed by puneetlath** 2024-10-23 15:16 UTC
Labels: Reviewing, Engineering, Weekly, Bug
