### ISSUE TITLE
[Pay 6/23][$1000] Right click popup on emoji reaction is not displayed in reply reports

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19439] opened 2023-05-23 12:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Hover on any message, click on reply in thread and add new message in it
4. React to message in new reply report
5. Right click on reaction and observe that no popup is displayed on reaction

## Expected Result:
App should display popup on emoji reaction right click in reply reports as it does on normal reports and in reply reports on android chrome
## Actual Result:
App does not display popup on emoji reaction right click in reply reports
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0390dbce-cf4c-410c-8311-cd53f038ab49

https://github.com/Expensify/App/assets/43996225/8e8766bc-902f-46f0-a9da-4c230fa45b71

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684492116384729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d2ee49d94fafe854</li>
        <li>Upwork Job ID: 1664749040145555456</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-05-24 00:59
@chiragsalian [here](https://expensify.slack.com/archives/C049HHMV9SM/p1684353595895229?thread_ts=1684352685.125699&cid=C049HHMV9SM) I see you said 
> yes, but it depends on where you react to it. It works from the parent report.
It does not work from the child report and thats a known bug. Let me see if i can find the issue.

And [this issue ](https://github.com/Expensify/Expensify/issues/282991)you worked on fixed _something_ . 

Can you take a look at the OP and confirm this is a bug we want to fix?

**Comment by mallenexpensify** [comment] 2023-05-26 21:18
@chiragsalian since you have context, can you take a look above, assigned to you so you'll see, unassign after commenting (or I will)

**Comment by chiragsalian** [comment] 2023-05-31 00:25
I found the steps pretty confusing. Why does it mention to add a new message in the thread and react to the new message? That doesn't have anything to do with the video and it confused me since i kept checking issues around the new message when it took me a while to realize the problem was with the parent comment.

**Easier steps IMO**:
1. Open the app
2. Open any report
3. Hover on any message, react to it. Right click the emoji and confirm you see the popup.
4. Thread the same message.
5.  In the new threaded report right-click the parent report action's emoji. Notice the popup doesn't show up

cc @stitesExpensify, @grgia, @srikarparsi, let me know if you guys would like to handle this or prefer to mark it external.

**Comment by StevenKKC** [comment] 2023-06-01 04:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Right click popup on emoji reaction is not displayed in reply reports.

### What is the root cause of that problem?
In order to show the emoji reaction popup, should get the emoji reaction related information in the `PopoverReactionList.js.`
If there is no related information, the popup is not displayed.
https://github.com/Expensify/App/blob/9fa12f3cd6bc422d2b9723ac98d575c7ce48f05d/src/pages/home/report/ReactionList/PopoverReactionList.js#L91-L109

But in the case of the thread report, the reportActions does not contain the emoji reaction related information. The related information is contained within the parent reportActions.
![Annotation 2023-06-01 000419](https://github.com/Expensify/App/assets/131836113/a511fb7b-b5f9-4d17-9ddd-a89d894202e4)

So the popup is not displayed in reply thread reports.

### What changes do you think we should make in order to solve the problem?

We should find the emoji reaction information from the parent reportActions in case of the thread report.

In `ReportActionsView.js`, pass parent report ID to the PopoverReactionList component.
```
                <PopoverReactionList
                    ref={ReactionList.reactionListRef}
                    reportID={this.props.report.reportID}
                    parentReportID={this.props.report.parentReportID || ''}
                />
```

In `PopoverReactionList.js`, first get the parent reportActions.
```
export default compose(
...
        parentReportActions: {
            key: (props) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${props.parentReportID}`,
            canEvict: false,
        },
...
)(PopoverReactionList);
```

And if the parent report ID is valid, we would get the emoji reaction related information from the parent reportActions.
```
    componentDidUpdate() {
...
        const selectedReaction = this.getSelectedReaction(this.props.parentReportID === '' ? this.props.reportActions : this.props.parentReportActions, this.state.reportActionID, this.state.emojiName);
...
    }

```

### What alternative solutions did you explore? (Optional)
None.

**Comment by mallenexpensify** [comment] 2023-06-02 21:42
Added `External` to move along.  

@parasharrajat can you review @StevenKKC 's proposal above?
https://github.com/Expensify/App/issues/19439#issuecomment-1571308504

**Comment by mallenexpensify** [comment] 2023-06-06 01:49
@parasharrajat , can you please review and comment on @StevenKKC proposal above?

**Comment by StevenKKC** [comment] 2023-06-06 08:25
@parasharrajat Thanks for your reply. ReportActionsUtils.getParentReportAction returns only one parent action, and getSelectedReaction function requires the full report actions list.
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/ReportActionsUtils.js#L65-L70
https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/pages/home/report/ReactionList/PopoverReactionList.js#L142-L147
![Annotation 2023-06-06 041708](https://github.com/Expensify/App/assets/131836113/9cedfffe-2a73-4194-9102-394bf4e52b8d)

If we don't use subscribing to the collection for reportActions, we should change getSelectedReaction in order to get reaction or add utility function get parent actions list.

I want to know your opinion.

**Comment by StevenKKC** [comment] 2023-06-12 18:28
@AndrewGable What do you think about my proposal? Could you please let me know your opinion?

**Comment by AndrewGable** [comment] 2023-06-12 21:50
Contributor was just assigned.

**Comment by StevenKKC** [comment] 2023-06-13 09:21
@parasharrajat @AndrewGable PR(https://github.com/Expensify/App/pull/20656) is ready for review.

**Comment by mallenexpensify** [comment] 2023-06-19 22:18
Updated to pay on 6/23.  Thanks for the ping

**Comment by StevenKKC** [comment] 2023-06-26 16:35
@mallenexpensify Could you please finish payment?

**Comment by mallenexpensify** [comment] 2023-06-26 22:40
Sorry for the delay @StevenKKC.  You, @parasharrajat and @dhanashree-sawant have been hired, can you please accept the job and reply here once you have?  
https://www.upwork.com/jobs/~01d2ee49d94fafe854

**Comment by StevenKKC** [comment] 2023-06-26 23:15
@mallenexpensify I have accepted the job. Thanks.

**Comment by dhanashree-sawant** [comment] 2023-06-27 02:34
Thanks @mallenexpensify, I have accepted the job.

**Comment by StevenKKC** [comment] 2023-06-28 17:09
@mallenexpensify Sorry, there seems to be a problem with my upwork account.

**Comment by mallenexpensify** [comment] 2023-06-30 03:03
@StevenKKC, (Maksym K in Upwork) paid $1500, @dhanashree-sawant paid $250 for reporting
@parasharrajat , please accept the job so I can pay
https://www.upwork.com/jobs/~01d2ee49d94fafe854

**Comment by mallenexpensify** [comment] 2023-07-14 23:28
K, I'm gonna make a weekly then

**Comment by JmillsExpensify** [comment] 2023-07-27 23:22
@mallenexpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @rushatgabhane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by mallenexpensify** [comment] 2023-07-29 17:09
Issue reporter: @dhanashree-sawant paid $250 via Upwork
Contributor: @StevenKKC paid $1500 via Upwork
Contributor+: @parasharrajat

**Comment by JmillsExpensify** [comment] 2023-07-29 17:12
Reviewed details for @parasharrajat. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Closed** 2023-08-01 04:49 UTC
Labels: Reviewing, External, Weekly, Bug
