### ISSUE TITLE
[$250] [HOLD for payment 2024-10-17] [Wave Control] [QBD] Handle the initial connection for QBD

### ISSUE THREAD

**Issue by lakchote** [Expensify/App#49697] opened 2024-09-25 12:35 UTC
Will be worked on by an external contributor (see https://expensify.slack.com/archives/C03SLTAEULW/p1726876645021139).

Design doc link: https://docs.google.com/document/d/1LQNlTBlHjFqRdru_4UkqVr0QRseNNDq2IhFFpXcgfwY/edit#bookmark=id.uy1tfxvjfmf3
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021847419775270058956</li>
        <li>Upwork Job ID: 1847419775270058956</li>
        <li>Last Price Increase: 2024-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 104527673</li>
<li>ZhenjaHorbach | Contributor | 104527674</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hoangzinh</details>

**Comment by mallenexpensify** [comment] 2024-10-18 23:31
@hoangzinh can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021847419775270058956

You were assigned on the date of your eligibility, since you're not setup on NewDot payments yet and I want to err on the safe side, I want to pay this via Upwork.

**Comment by mallenexpensify** [comment] 2024-10-22 00:29
Contributor: @hoangzinh paid $250 via Upwork
Contributor+: @ZhenjaHorbach owed $250 via Upwork

@ZhenjaHorbach can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~021847419775270058956

Also, plz complete the BZ checklist. 

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment] 2024-10-22 19:29
Thanks @ZhenjaHorbach , you've ben paid, payment confirmation updated above

test case created
- https://github.com/Expensify/Expensify/issues/438053

**Closed by mallenexpensify** 2024-10-22 19:29 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
