### ISSUE TITLE
 Attachment - Wrong PDF is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39833] opened 2024-04-08 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to any report
2. Send two pdf files
3. Open the last one

## Expected Result:
The last pdf file should be opened

## Actual Result:
The first pdf file is opened

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b630734f-9ec2-4f8c-9dde-8026ca5ddde8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-08 15:41
@amyevans  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by amyevans** [comment] 2024-04-08 21:33
I verified by reverting https://github.com/Expensify/App/pull/39578 locally that it's the source of the regression cc @abzokhattab @hungvu193 @flodnv.

Since the package bump PR is tied to a rather non-urgent bug fix I think it makes the most sense to just revert the bump PR, but speak up soon if you disagree.

**Comment by amyevans** [comment] 2024-04-09 02:10
PR has been merged but waiting on CP: https://expensify.slack.com/archives/C07J32337/p1712628550724549

**Comment by hungvu193** [comment] 2024-04-09 02:11
Hey @amyevans I can reproduce even when I downgrade react-fast-pdf to 1.0.6

**Comment by hungvu193** [comment] 2024-04-09 02:15
https://github.com/Expensify/App/assets/16502320/9d398e2f-918d-4689-916e-e267aeec01c9

**Comment by amyevans** [comment] 2024-04-09 02:17
Can you verify the version is `"version": "1.0.6",` within `/node_modules/react-fast-pdf/package.json`? You'd likely need to delete your node_modules folder and run `npm ci` to get it to "downgrade" to 1.0.6

**Comment by hungvu193** [comment] 2024-04-09 02:19
> Can you verify the version is `"version": "1.0.6",` within `/node_modules/react-fast-pdf/package.json`? You'd likely need to delete your node_modules folder and run `npm ci` to get it to "downgrade" to 1.0.6

@amyevans  I see, seems like caching. Confirmed it's fixed with 1.0.6. My bad 🤦

**Comment by amyevans** [comment] 2024-04-09 02:33
No worries!

**Comment by kidroca** [comment] 2024-04-09 09:03
I confirm this seems to be related to #23546 and the version bump can be a coincidence 
The wrong attachment bug manifests with all attachment types, you just need to scroll a bit to the past in the conversation in order to pre-fill the local database with comments with attachments

**Comment by hungvu193** [comment] 2024-04-09 10:23
> I confirm this seems to be related to #23546 and the version bump can be a coincidence The wrong attachment bug manifests with all attachment types, you just need to scroll a bit to the past in the conversation in order to pre-fill the local database with comments with attachments

@kidroca I saw you were assigned on that issue, do you have any WIP? So I can test if it solved this issue as well 😄

**Comment by kidroca** [comment] 2024-04-09 13:23
> @kidroca I saw you were assigned on that issue, do you have any WIP? So I can test if it solved this issue as well 😄

@hungvu193 here's my WIP: 
- https://github.com/Expensify/App/pull/39930

**Comment by hungvu193** [comment] 2024-04-09 14:39
> > @kidroca I saw you were assigned on that issue, do you have any WIP? So I can test if it solved this issue as well 😄
> 
> 
> 
> @hungvu193 here's my WIP: 
> 
> - https://github.com/Expensify/App/pull/39930

Awesome! I'll give it a try. Thank you 🙏

**Comment by amyevans** [comment] 2024-04-09 15:16
Testing on:

_[This branch](https://github.com/Expensify/App/pull/39930) + react-fast-pdf 1.0.8:_

https://github.com/Expensify/App/assets/7277067/46e6f013-dfb9-4a68-a385-ce3f9a4b61ef

The behavior is inconsistent, but it _usually_ seems to do what's in the recording: briefly flashes the wrong attachment before loading the correct (most recent) one.

_main + react-fast-pdf 1.0.6:_

https://github.com/Expensify/App/assets/7277067/78d391c0-7887-40ef-b494-a2e5da33d323

Bug is not reproducible.

_main + react-fast-pdf 1.0.7:_

https://github.com/Expensify/App/assets/7277067/461292c4-8c57-405a-81aa-262e85bae5ed

Bug is reproducible.

While perhaps the root cause might be similar to what's being worked on in https://github.com/Expensify/App/pull/39930, I don't think it is coincidental that the bug manifests on 1.0.7 but not on 1.0.6, so I still think proceeding with the revert is the right course of action. Do you all agree or disagree? Cc @Julesssss as well as deployer this week

**Comment by amyevans** [comment] 2024-04-09 16:05
Alright I retested on staging following the CP: https://github.com/Expensify/App/pull/39869#issuecomment-2045561540. I think we can close this one out, thanks for the discussion!

**Closed by amyevans** 2024-04-09 16:05 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly

**Comment by kidroca** [comment] 2024-04-11 10:40
Should we open and track an issue for `react-fast-pdf` or maybe have a note that the library shouldn't be updated since a bug manifests in more recent versions?

**Comment by amyevans** [comment] 2024-04-11 13:57
Yes, I believe they're working on a patch in the original issue but I left a note (https://github.com/Expensify/App/issues/34816#issuecomment-2049754801) to clarify expectations.
