### ISSUE TITLE
Scan - Large attachment message does not disappear when opening Scan in another tab

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26962] opened 2023-09-07 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > IOU
3. Upload a PDF file larger than 24 MB
4. Without closing the error message, close the tab
5. Go to staging ND in another tab
6. Go to + > Request money > IOU
Note that the error message appears again

## Expected Result:
The error message about the large file size will not appear

## Actual Result:
The error message about the large file size appears

Unknowm

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/3f700d9f-63d7-4e38-a819-e429e5e763b1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by saisixthblock** [comment] 2023-09-08 05:53
**Please re-state the problem that we are trying to solve in this issue.**
Scan - Large attachment message does not disappear when opening Scan in another tab
**What is the root cause of that problem?**
We're storing scan validation error  and only clear them when user press Close button from Validation Modal, We are not removing the validation error while loading the page.
**What changes do you think we should make in order to solve the problem?**
We need to call clearUploadReceiptError function while loading the page each and every time to clear the validation errors.

**Comment by michaelhaxhiu** [comment] 2023-09-20 17:12
wow sorry for the long delay!

**Comment by michaelhaxhiu** [comment] 2023-09-20 17:14
dupe of https://github.com/Expensify/App/issues/27403

**Comment by michaelhaxhiu** [comment] 2023-09-20 17:14
lmk if this is a mistake of course

**Closed by michaelhaxhiu** 2023-09-20 17:14 UTC
Labels: Daily, Bug
