### ISSUE TITLE
[HOLD for payment 2024-07-24] [$500] mWeb-Scan-On refreshing scan submit expense confirmation page all details are disappeared

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40936] opened 2024-04-24 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4510603
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- submit expense - scan
3. Upload an image using camera
4. Select a user
5. Enter description and save it
6. Refresh the page

## Expected Result:
On refreshing scan submit expense confirmation page all details must not be disappeared

## Actual Result:
On refreshing scan submit expense confirmation page all details are disappeared. To and description details also disappeared

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0ac52777-3e1b-4b33-9e6c-04d1cfcd5165

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a06fc87f92014ba9</li>
        <li>Upwork Job ID: 1783312719597031424</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 102676237</li>
<li>dominictb | Contributor | 102676238</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify / @bfitzexpensify</details>

**Comment by lanitochka17** [comment] 2024-04-24 19:09
We think that this bug might be related to #wave-collect - Release 1

**Comment by shahinyan11** [comment] 2024-04-25 11:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb-Scan-On refreshing scan submit expense confirmation page all details are disappeared
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/actions/IOU.ts#L5942C9-L5942C97) we do not pass `iouAction` param to `IOUUtils.navigateToStartMoneyRequestStep` method so it navigates wrong screen after refresh
### What changes do you think we should make in order to solve the problem?
Pass `iouAction` param in `IOUUtils.navigateToStartMoneyRequestStep` method [here](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/libs/actions/IOU.ts#L5942)
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-04-25 16:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb-Scan-On refreshing scan submit expense confirmation page all details are disappeared

Looking at [this](https://github.com/Expensify/App/blob/d8e6990103092d241d582984302731905c6a5e8f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L164C1-L167C103) comment I think the current **Expected Result:** is incorrect 
### What is the root cause of that problem?
After the refresh, the mounting of current page occurs twice. The first one is when the [NavigationRoot](https://github.com/Expensify/App/blob/f9b05c0034f9ed804a03f668f5573ae7e3511c8f/src/libs/Navigation/NavigationRoot.tsx#L62C10-L62C24) component is rendered and second, when navigating to current page from [here](https://github.com/Expensify/App/blob/690609052072c89c52f24b21d95ea02b2819a769/src/libs/actions/Report.ts#L2437C16-L2437C88).
### What changes do you think we should make in order to solve the problem?
Wrap [this](https://github.com/Expensify/App/blob/690609052072c89c52f24b21d95ea02b2819a769/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L183C9-L183C156) line in `InteractionManager.runAfterInteractions`

### What alternative solutions did you explore? (Optional)
Add check if the route is `MONEY_REQUEST_STEP_CONFIRMATION` in [shouldSkipDeepLinkNavigation](https://github.com/Expensify/App/blob/690609052072c89c52f24b21d95ea02b2819a769/src/libs/shouldSkipDeepLinkNavigation/index.web.ts#L3) function and return `true` in this case

**Comment by abdulrahuman5196** [comment] 2024-04-30 08:19
Checking now

**Comment by shahinyan11** [comment] 2024-05-01 19:46
> And another question is On root cause being true, this means does every screen on refresh being navigate twice? But I don't see that happening. If so we should fix the navigation happening multiple times.

In both places, there are a few `if` blocks with early `return` before navigating. So this behavior is not for every screen and there may be screens for which it happens early `return`.

**Comment by bfitzexpensify** [comment] 2024-05-06 14:47
Update on this one @abdulrahuman5196?

**Comment by abdulrahuman5196** [comment] 2024-05-07 12:13
> Update on this one @abdulrahuman5196?

We don't have proposals to approve yet

**Comment by shahinyan11** [comment] 2024-05-07 19:28
> > I tried this on mac web and didn't work for me.
> 
> @shahinyan11 where you able to check on this?

@abdulrahuman5196 It works for me on mac web with `InteractionManager.runAfterInteractions`

https://github.com/Expensify/App/assets/46921547/efcb053e-3666-49e6-b92f-76779f6a4cb6

**Comment by bfitzexpensify** [comment] 2024-05-09 17:04
Still waiting on full proposals

**Comment by abdulrahuman5196** [comment] 2024-05-10 14:47
> > > I tried this on mac web and didn't work for me.
> > 
> > 
> > @shahinyan11 where you able to check on this?
> 
> @abdulrahuman5196 It works for me on mac web with `InteractionManager.runAfterInteractions`
> Untitled.mov

Could be an inconsistent fix. Anyways, then could you share your test code, I can also check again with your exact code.

**Comment by abdulrahuman5196** [comment] 2024-05-15 15:00
There is no proposal to approve yet. Waiting on new proposals.

**Comment by ShaheFS** [comment] 2024-05-16 07:31
@abdulrahuman5196 The behavior in your video is the same as in the video I shared [here](https://github.com/Expensify/App/issues/40936#issuecomment-2099150056).  
You may be confused by the fact that the behavior does not match the expected result in the GH issue. But I think the expected result should be changed because when browser is refreshed the uploaded image ceases to exist. ( See  [this](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103) comment )

**Comment by shahinyan11** [comment] 2024-05-16 07:31
@abdulrahuman5196 The behavior in your video is the same as in the video I shared https://github.com/Expensify/App/issues/40936#issuecomment-2099150056.
You may be confused by the fact that the behavior does not match the expected result in the GH issue. But I think the expected result should be changed because when browser is refreshed the uploaded image ceases to exist. ( See [this](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103) comment )

**Comment by bfitzexpensify** [comment] 2024-05-21 19:48
>But I think the expected result should be changed because when browser is refreshed the uploaded image ceases to exist. ( See [this](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103) comment )

I think the expected result can remain the same - it seems like [this](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103) indicates that the receipt image will be deleted, but if it's possible to save the details added, then we should do that.

**Comment by mvtglobally** [comment] 2024-05-22 04:39
Issue not reproducible during KI retests. (First week)

**Comment by abdulrahuman5196** [comment] 2024-05-22 20:02
We don't have proposal yet to approve fitting the OP result

**Comment by shahinyan11** [comment] 2024-05-23 03:53
> I think the expected result can remain the same - it seems like [this](https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103) indicates that the receipt image will be deleted, but if it's possible to save the details added, then we should do that.

@bfitzexpensify And how the receipt image should be added after it ?

**Comment by abdulrahuman5196** [comment] 2024-05-28 18:43
> We don't have proposal yet to approve fitting the OP result

same

**Comment by bfitzexpensify** [comment] 2024-05-28 21:02
This is now a month old - increasing the bounty

**Comment by shahinyan11** [comment] 2024-05-29 04:47
@bfitzexpensify Could you please answer to my question [here](https://github.com/Expensify/App/issues/40936#issuecomment-2126182043)

**Comment by bfitzexpensify** [comment] 2024-05-29 13:44
Sorry @shahinyan11, I missed that. 

>@bfitzexpensify And how the receipt image should be added after it ?

The user should have the option to add a receipt as they would in any situation where an expense was created and no receipt had been attached

**Comment by shahinyan11** [comment] 2024-05-29 15:27
@bfitzexpensify What I mean is that if we save all the data without the receipt image leaving the user on the confirmation page, he will not have the option to add the receipt image in that page

**Comment by bfitzexpensify** [comment] 2024-05-29 15:53
Let me confirm I understand: 
- right now, we don't save the details, which leaves an empty state for the expense where the user can add a receipt and the other details
- if we update this to save the details upon a refresh, then this will not allow the user to add a receipt

Is that correct?

**Comment by bfitzexpensify** [comment] 2024-05-30 17:01
Assigning a second BZ team member while I am on leave until June 11th. 

@puneetlath, summary:
- currently in proposal review
- there are two things being discussed in this issue

1. IOU request details being removed if the page is refreshed
2. The redirect back to the 'start' of the request that comes after refreshing. 

The 'start again' approach comes from https://github.com/Expensify/App/blob/ac09bc5612cd4da6d3ec1bede187f80c1563fd7f/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L199C1-L202C103, but I think saving any details entered is preferable behaviour.

**Comment by puneetlath** [comment] 2024-06-04 22:12
@abdulrahuman5196 is there anything you need from me here? Or are you still just reviewing proposals?

**Comment by s77rt** [comment] 2024-06-07 00:40
Regarding the part where the data is reset, I agree that's a bug. But the navigation part is expected as on refresh the blob urls are revoked and the receipt would no longer be accessible. I'm currently trying to double check but not able to due to attachments not working at all from my end.

@dominictb Were you able to get the receipt loaded after refresh? Also are the attachments working from your side?

<img width="480" alt="Screenshot 2024-06-07 at 1 30 32 AM" src="https://github.com/Expensify/App/assets/16493223/aaf1e4b0-fe77-4108-ba9c-7217b8b21bbc">

**Comment by ShaheFS** [comment] 2024-06-08 05:35
Hi there. @s77rt Could you please check my [proposal](https://github.com/Expensify/App/issues/40936#issuecomment-2077693255) and give some feedback.

**Comment by ShaheFS** [comment] 2024-06-08 05:40
> Let me confirm I understand:
> 
> * right now, we don't save the details, which leaves an empty state for the expense where the user can add a receipt and the other details
> * if we update this to save the details upon a refresh, then this will not allow the user to add a receipt
> 
> Is that correct?

@bfitzexpensify The first point is not correct. The user can add all the details except with the receipt. There is no upload button on the confirmation page.

**Comment by shahinyan11** [comment] 2024-06-08 05:42
Hi there. @s77rt Could you please check my [proposal](https://github.com/Expensify/App/issues/40936#issuecomment-2077693255) and give some feedback.

**Comment by shahinyan11** [comment] 2024-06-08 05:42
> Let me confirm I understand:
> 
> * right now, we don't save the details, which leaves an empty state for the expense where the user can add a receipt and the other details
> * if we update this to save the details upon a refresh, then this will not allow the user to add a receipt
> 
> Is that correct?

@bfitzexpensify The first point is not correct. The user can add all the details except with the receipt. There is no upload button on the confirmation page.

**Comment by s77rt** [comment] 2024-06-08 11:30
@dominictb That was in general. It's not strictly related to this issue. Regarding your solution I think we want to fix the 1st point only (draft being unexpectedly cleared), the second point does not add a significant value. Please update your proposal.

**Comment by s77rt** [comment] 2024-06-08 11:35
@shahinyan11 Your RCA does not explain why the drafts are cleared. The navigations are expected.

**Comment by shahinyan11** [comment] 2024-06-08 13:58
> @shahinyan11 Your RCA does not explain why the drafts are cleared. The navigations are expected.

@s77rt  Is the current expected result confirmed? If yes, then how should a new receipt be added after the refresh?  I need to understand this part clearly before updating my proposal.

**Comment by s77rt** [comment] 2024-06-09 16:26
@shahinyan11 The receipt is not expected to be loaded again but the other info such as the description should persist

**Comment by s77rt** [comment] 2024-06-09 16:32
@dominictb The reported bug here https://github.com/Expensify/App/issues/40936#issuecomment-2155201014 is actually a regression after applying the suggested solution. If we start the submit request and the initial tab is scan the request type is still seen as `manual`

**Comment by s77rt** [comment] 2024-06-10 17:10
@dominictb Thanks for looking into the bug. The updated solution looks good to me 👍.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/40936#issuecomment-2138147750)

**Comment by bfitzexpensify** [comment] 2024-07-02 13:49
Hey @dominictb - how is this one going?

**Comment by s77rt** [comment] 2024-07-19 15:31
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/40370
- The offending PR has been commented on: https://github.com/Expensify/App/pull/40370#discussion_r1684545667
- A discussion in #expensify-bugs has been started: Not needed (unique bug)
- Determine if we should create a regression test for this bug: No (this seems already coming from a TestRail test)

**Comment by bfitzexpensify** [comment] 2024-07-24 13:55
Payments complete, closing this out.

**Closed by bfitzexpensify** 2024-07-24 13:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
