### ISSUE TITLE
[$500] Public room can't be seen on LHN after opening it from a link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30615] opened 2023-10-30 23:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:**Y
**Reproducible in production?:**Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log out
3. Navigate to this link - https://staging.new.expensify.com/r/3504895439653267
4. Log in with any accounts

## Expected Result:
The public room should be displayed

## Actual Result:
The public room can't be seen on LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Window: Chrome </summary>

 

![Bug6257319_1698697773901!Screenshot_602](https://github.com/Expensify/App/assets/78819774/c2979e29-5f8a-49c4-a6a1-1fa69804033a)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cd18e947fb2a8d5</li>
        <li>Upwork Job ID: 1719138151952470016</li>
        <li>Last Price Increase: 2023-10-30</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 27493079</li>
</ul></li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-10-31 00:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If the current chat is a public room, it should show in the left hand nav.

### What is the root cause of that problem?
Public rooms were removed from the left hand nav in a recent PR:
https://github.com/erquhart/expensify-app/commit/5dc91a13a198bd8e16c5f761b2188be25b3aeb2b

### What changes do you think we should make in order to solve the problem?

Revert to fix (tested locally, works).

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jliexpensify** [comment] 2023-10-31 01:08
Hmm I'm unable to repro on Staging v1.3.93-0 (Chrome) - LHN is there for me:

![image](https://github.com/Expensify/App/assets/30815269/c1c1356e-abeb-42e9-8700-7cb2869714cb)

**Comment by erquhart** [comment] 2023-10-31 01:16
@jliexpensify left hand nav is there, but the public channel currently being viewed isn’t in the list.

**Comment by jliexpensify** [comment] 2023-10-31 02:42
Ah sorry, my mistake - thanks @erquhart!

**Comment by jasperhuangg** [comment] 2023-11-01 18:52
@thesahindia I can't seem to find your comment, do you mind linking it again?

**Comment by jasperhuangg** [comment] 2023-11-01 18:54
So it's actually expected that the participantAccountIDs are empty if you're not a member of the workspace that the public room is a part of.

This is because of privacy concerns. So no BE fixes are needed here.

**Comment by jasperhuangg** [comment] 2023-11-01 18:56
We just need to update the condition [here](https://github.com/Expensify/App/blob/deb267f81a771114b9d304f6386d887498320e0f/src/libs/ReportUtils.js#L3278-L3283) to be the following:

```js
report.participantAccountIDs.length === 0 && 
 !isChatThread(report) && 
 !isUserCreatedPolicyRoom(report) && 
 !isPublicRoom(report) && 
 !isArchivedRoom(report) && 
 !isMoneyRequestReport(report) && 
```

**Comment by erquhart** [comment] 2023-11-01 20:20
@jasperhuangg that's what my existing proposal is, I just didn't check to see what else that PR had. When I say to revert, I only meant reverting the exclusion of the `isPublicRoom()` condition. I'll go ahead and make an updated proposal.

**Comment by erquhart** [comment] 2023-11-01 20:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Public rooms opened via link aren't showing in the left hand nav.

### What is the root cause of that problem?
Reports with a `visibility` property matching `PUBLIC` or `PUBLIC_ANNOUNCE` used to be included in the left hand nav via `isPublicReport()`:
https://github.com/Expensify/App/blob/1700ecfa697411588de13b50dc67d9ff7fb70f00/src/libs/ReportUtils.js#L411-L413

This was removed with - based on the PR conversation from #27966 - the understanding that public rooms were expected to be included in `isUserCreatedPolicyRoom()`, but that function only includes reports with a `POLICY_ROOM` chat type. `isPublicRoom()` is still needed to match report visibility against `PUBLIC` and `PUBLIC_ANNOUNCE` types.

### What changes do you think we should make in order to solve the problem?

Re-add the `isPublicRoom(report)` statement to this conditional: https://github.com/Expensify/App/blob/deb267f81a771114b9d304f6386d887498320e0f/src/libs/ReportUtils.js#L3277-L3283

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by jasperhuangg** [comment] 2023-11-02 18:01
Got it, since @dukenv0307 had a clearer proposal and was more in line with what I was thinking, let's assign them. cc @neil-marcellini

**Comment by neil-marcellini** [comment] 2023-11-02 19:32
Cool, I agree that the [proposal](https://github.com/Expensify/App/issues/30615#issuecomment-1786828180) from @dukenv0307 looks good. Hired!

**Comment by jliexpensify** [comment] 2023-11-21 04:27
Hrrrm what happened with the updater here? It looks like this hit production 2 weeks ago right? If so, I should be paying + the checklist should be worked on, right?

**Comment by jliexpensify** [comment] 2023-11-21 04:33
If we are going off https://github.com/Expensify/App/pull/30814, here's the Payment Summary:

- Contributor: @dukenv0307 $750 (bonus as it was merged in 3 working days)
- C+: @thesahindia$750 (bonus as it was merged in 3 working days) - NEW.DOT PAYMENT

[Upworks job](https://www.upwork.com/jobs/~010cd18e947fb2a8d5)

is this all correct? @thesahindia could you complete the checklist too?

**Comment by jliexpensify** [comment] 2023-11-21 04:51
Paid and job closed. Waiting on checklist to be completed!

**Closed** 2023-11-22 23:06 UTC
Labels: Reviewing, External, Weekly, Bug
