### ISSUE TITLE
[HOLD for payment 2023-07-10] [$1000] BUG:  Workspace- Default currency for new workspace is showing as USD initially reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12047] opened 2022-10-20 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Create a new workspace
2. Go to general settings
3. Check the Default currency
4. Click on back arrow
5. Go back to general settings

## Expected Result:
The default currency should be correct

## Actual Result:
The default currency is set to USD and changes after closing the page and going back

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.18-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/197042182-e9f78854-0547-499d-889a-a098b7d87eb2.mov

https://user-images.githubusercontent.com/43996225/197042199-d2cf882a-b63d-4f1b-ae2b-0216798d6e98.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @thesahindia 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666282701270589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4777e3f65d57ff5</li>
        <li>Upwork Job ID: 1673219225271455744</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2022-10-21 20:22
@kadiealexander  new BZ chore SO is [here](https://stackoverflow.com/c/expensify/questions/14418), we want to ensure BZ stays assigned to all issues so we can get to BugZero,

**Comment by kadiealexander** [comment] 2022-10-25 01:04
Wasn't able to reproduce this on Version 1.2.18-4 of the desktop app:

![2022-10-25_14-02-09 (1)](https://user-images.githubusercontent.com/59587260/197658163-16dc7d63-4321-4886-bd8b-bde5cee22bec.gif)

Also can't reproduce this on web:

![2022-10-25_14-03-59 (1)](https://user-images.githubusercontent.com/59587260/197658259-c18740cd-adce-40ef-8da1-9c28aa5ecd94.gif)

**Comment by kadiealexander** [comment] 2022-10-25 01:05
@thesahindia could you please review the gifs above to see if I used the right steps to reproduce this error? Also, can you please update your app version and see if this is happening on the most recent version?

**Comment by thesahindia** [comment] 2022-11-11 14:48
@kadiealexander, It is reproducible.

https://user-images.githubusercontent.com/83179295/201364338-3699e6f7-3623-46da-b2eb-90e28ee82429.mov

**Comment by kadiealexander** [comment] 2022-11-15 04:31
@thesahindia please post the steps you took to reproduce this error.

**Comment by thesahindia** [comment] 2022-11-15 09:55
Steps:

1. Go to settings
2. Click on workspaces
3. Click on `new workspace` button
4. Check the default currency for newly created workspace

cc: @kadiealexander

**Comment by mallenexpensify** [comment] 2023-04-10 22:53
I'm reopening to ensure @kadiealexander sees it. @thesahindia , can you drop in a screenshot or vid showing the bug?

**Comment by kadiealexander** [comment] 2023-04-10 23:35
@thesahindia I'm still unable to reproduce this issue using [these steps](https://github.com/Expensify/App/issues/12047#issuecomment-1315064397). Please share a video and let me know the steps I need to take to reproduce this issue. 

https://user-images.githubusercontent.com/59587260/231018896-b0aa608f-be0e-4f94-a20c-ea217fea5917.mp4

**Comment by kadiealexander** [comment] 2023-04-14 04:47
Made a brand new gmail account (kadielizzy+12047@gmail.com) and still was unable to reproduce this one on the staging web app in Chrome. 

https://user-images.githubusercontent.com/59587260/231944025-22f1e242-87a9-4aa9-9291-16e93a69bcd0.mp4

The version number for this is now quite out of date, @thesahindia could you please retest on the latest version and let me know if you're still experiencing this?

**Comment by kadiealexander** [comment] 2023-06-26 06:37
Sorry @thesahindia I missed this until you tagged me in [this](https://expensify.slack.com/archives/C049HHMV9SM/p1687421667971209) thread. 

I was able to reproduce by slowing my throttling down to "Slow 3G":

Uploading 2023-06-26_18-36-31.mp4…

**Comment by bernhardoj** [comment] 2023-06-26 07:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Creating a workspace will set the initial currency as USD for a while.

### What is the root cause of that problem?
We can actually easily reproduce this by creating a new workspace while offline. The reason is, when we create a new workspace, we will optimistically set the workspace currency as USD.
https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Policy.js#L868-L878

If we do it while online, we will get the correct currency later on after the API request is completed

### What changes do you think we should make in order to solve the problem?

Optimistically set the currency from current user personal details.
```
lodashGet(personalDetails, [sessionAccountID, 'localCurrencyCode'], 'USD')
```

**Comment by mollfpr** [comment] 2023-06-27 08:03
Thanks @bernhardoj for the proposal! I agree with your proposal and solution. @kadiealexander the proposal looks good to me 🚀

🎀 👀 🎀 C+ reviewed!

**Comment by jasperhuangg** [comment] 2023-06-27 21:06
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Creating a workspace will set the initial currency as USD for a while.
> 
> ### What is the root cause of that problem?
> We can actually easily reproduce this by creating a new workspace while offline. The reason is, when we create a new workspace, we will optimistically set the workspace currency as USD.
> 
> https://github.com/Expensify/App/blob/64b720c5b74c3001bf3f9eceac1f54511611c6b7/src/libs/actions/Policy.js#L868-L878
> 
> If we do it while online, we will get the correct currency later on after the API request is completed
> 
> ### What changes do you think we should make in order to solve the problem?
> Optimistically set the currency from current user personal details.
> 
> ```
> lodashGet(personalDetails, [sessionAccountID, 'localCurrencyCode'], 'USD')
> ```

Looks good to me, local currency code is always set in OpenApp and is set via the user's IP, so this approach should work great. Assigned!

**Comment by bernhardoj** [comment] 2023-06-28 05:03
PR is ready.

cc: @mollfpr

**Comment by kadiealexander** [comment] 2023-07-10 03:19
Have sent contracts to all! @mollfpr please don't forget about the checklist :)

**Comment by mollfpr** [comment] 2023-07-10 06:24
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/10723

> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/10723/files#r1257761483

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Turn off the internet connection
2. Go to Settings > Workspaces
3. Press New Workspace. Verify you are brought to the workspace page
4. Open the workspace Settings
5. **Verify** the currency shown is your local currency
6. 👍 or 👎

**Comment by kadiealexander** [comment] 2023-07-11 06:37
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@mollfpr] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/issues/12047#issuecomment-1628316347
- [ ] [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/issues/12047#issuecomment-1628316347
- [x] [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: https://github.com/Expensify/App/issues/12047#issuecomment-1628316347
- [x] [@mollfpr] Determine if we should create a regression test for this bug.
- [x] [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [x] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon: https://github.com/Expensify/Expensify/issues/298952

**Closed** 2023-07-11 06:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
