### ISSUE TITLE
Unable to sign-in to NewDot with a new account on production

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10653] opened 2022-08-29 14:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Add an account to the policyExpenseChat beta
2. Head to [new.expensify.com](http://new.expensify.com/) and sign-up
3. Click the magic sign-in link received on email
4. Observe the infinite loading spinner on sign-in

## Expected Result:
User should be able to sign up / Sign In

## Actual Result:
Unable to sign-in to NewDot with a new account on production when account is in Beta 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.91-0
**Reproducible in staging?:** N
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
<img width="1510" alt="image - 2022-08-29T104111 686" src="https://user-images.githubusercontent.com/43995119/187227785-3f5d1356-fe1e-4192-84c0-4030fd92e89f.png">
<img width="1511" alt="image - 2022-08-29T104108 801" src="https://user-images.githubusercontent.com/43995119/187227789-6a00486a-33e9-466a-95ad-836d83140842.png">

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661768050779429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-08-29 15:21
Given that this is apparently limited to accounts on the `policyExpenseChat` beta, I think this is likely `internal` @aldo-expensify. 

CC: @AndrewGable @marcaaron from [the thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1661768050779429).

**Comment by marcaaron** [comment] 2022-08-29 16:10
Logs don't tell me much unfortunately other than @trjExpensify has one report on this account (which I'd assume is their 1:1 chat report, but that might not be true). 

I can see that the app times out before hiding the loading spinner:

https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2274247de428af6689-SJC%22)+AND+timestamp:[2022-08-29T09:09:32.920Z+TO+2022-08-29T11:09:32.920Z]&index=logs_expensify-018320

And it's the "Main Drawer" here -> https://github.com/Expensify/App/blob/89e7e7db469d2f222ebceb7aefa72cb4add0de78/src/libs/Navigation/AppNavigator/MainDrawerNavigator.js#L58-L64

Which would happen if there were 0 reports available to show in the LHN.

The only thing I can think of is that maybe [this methods](https://github.com/Expensify/App/blob/89e7e7db469d2f222ebceb7aefa72cb4add0de78/src/libs/ReportUtils.js#L189-L197) is filtering out that one chat for some reason, but it's hard to tell without being able to inspect the report object.

**Comment by trjExpensify** [comment] 2022-08-29 16:46
Is there anything I can help grab from the console? In the slack thread I shared the OpenApp response I grabbed.

**Comment by aldo-expensify** [comment] 2022-08-29 20:35
Hmm, there must be something else to this. I tried the steps with a new account under a non-controlled domain that I own, and it worked fine:

Account: aldo+test-create-account-bug123@chilepropiedades.cl

I added the beta `policyExpenseChat` using https://www.expensify.com/_support/beta to the account before creating it.

**Comment by marcaaron** [comment] 2022-08-30 08:28
Alright so took a look at the data and it seems like the one report you have has a type of `domainAll` 

<img width="327" alt="Screen Shot 2022-08-30 at 9 49 50 AM" src="https://user-images.githubusercontent.com/32969087/187381175-1371bac1-6494-4a0f-9eaf-19abb5e1561c.png">

Still not able to reproduce though and I don't get that room when creating a new account locally.

**Comment by trjExpensify** [comment] 2022-08-30 10:12
Oh, interesting. That's the default domain room, but it won't show up unless you're on the `defaultRooms` beta.

**Comment by aldo-expensify** [comment] 2022-09-02 14:13
I haven't got the time to check on this yet, I'll try to do it today by the end of day as soon as I finish with a N7 refactor PR

**Comment by trjExpensify** [comment] 2022-09-02 15:01
Thank you, @aldo-expensify! ❤️

**Comment by aldo-expensify** [comment] 2022-09-03 20:38
In dev, I created and account and validated a domain for it. Then created a new account under the controlled domain through new dot, validated it with the email link, and now I get only the `domainAll` report, no Concierge chat. I think this is a bug right? I think there should be always a Concierge chat

<img width="880" alt="Screen Shot 2022-09-03 at 9 32 00 PM" src="https://user-images.githubusercontent.com/87341702/188286833-f9170b47-ad40-4299-af0e-22722c7bf7ac.png">

I doesn't stay loading forever like it happens for @trjExpensify though

**Comment by trjExpensify** [comment] 2022-09-05 13:37
Yeah, every new account on sign-up should have a Concierge chat.

**Comment by aldo-expensify** [comment] 2022-09-06 11:59
I'm pretty sure that this is happening because of this code:

https://github.com/Expensify/Web-Expensify/blob/1ee6395cec9e9174aa694fdd9629440a7b05c7a6/lib/AppInit.php#L123-L131

The domain room is already available for new users we create under the domain, then miss creating the Concierge chat because `Auth::getChats` returns this chat

I created a draft PR, I'll test it further and make it ready for review today

**Comment by aldo-expensify** [comment] 2022-09-26 16:30
No overdue, this [PR](https://github.com/Expensify/Web-Expensify/pull/34790) was merged/deployed a while ago

@trjExpensify can you check if you can still reproduce this bug by creating an account under `@tommocks.art`? 🙏

**Comment by trjExpensify** [comment] 2022-09-26 22:41
Trying! Just signed up with tom+wcrun15@tommocks.art on staging and I haven't received a validation link yet. 😅

**Comment by trjExpensify** [comment] 2022-09-26 22:49
Apparently we sent the email: 

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/16232057/192393652-7e985087-a37f-41b2-9791-b84672778c0d.png">

But I got put on the email suppression list: 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16232057/192393800-2c5b0905-78e9-40ff-a1d2-56a75bdc7714.png">

Unblocked it and re-sent the link: 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16232057/192394042-d081306d-e05c-4757-82db-f01baab97d91.png">

Still nothing. 🤔

**Comment by trjExpensify** [comment] 2022-09-26 23:23
I think I figured it out - that domain expired on the 17th Sept. Chatting with @kevinksullivan to see if we can get it renewed as he's the owner of it.

**Comment by aldo-expensify** [comment] 2022-09-27 01:40
Thanks for testing, I hope it works :) 🤞

**Comment by trjExpensify** [comment] 2022-09-27 23:07
Still trying. Looks like we're having email delivery problems, so can't get a validation link to myself today.

**Closed** 2022-09-29 13:55 UTC
Labels: Reviewing, Engineering, Daily
