### ISSUE TITLE
[Needs regression test steps] IOU - "Split" is not clickable after split bill between participants.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13022] opened 2022-11-24 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Tap on Fub menu
4. Select Split Bill
5. Put amount and Select the users
6. Tap Split Bill
7. Tap on text - Split

## Expected Result:
"Split" should be clickable after split bill between participants.

## Actual Result:
"Split" is not clickable after split bill between participants.

## Workaround:
Uknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.31.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/203862451-c9dcfee1-1cbd-419a-be6b-c29222a2fca1.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal team
 
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016472556625f2bc3e</li>
        <li>Upwork Job ID: 1606462648801792000</li>
        <li>Last Price Increase: 2022-12-24</li>
    </ul>
</details>

**Comment by Tushu17** [comment] 2022-11-24 21:09
I've reported this issue on slack - [here](https://expensify.slack.com/archives/C049HHMV9SM/p1669313996027739)
### Proposal 
 We just need to change:- 
```diff
-                    <Text style={[styles.chatItemMessageLink]}>
+                   <Text style={[props.shouldAllowViewDetails ? styles.chatItemMessageLink : undefined]}>
```  
  https://github.com/Expensify/App/blob/585816ce3a3362673e864ff8545d6a0c303520ee/src/components/ReportActionItem/IOUQuote.js#L48

**Comment by hungvu193** [comment] 2022-11-25 04:47
This can be a backend problem since the IOUReportID didn't exist in split message. 
<img width="1269" alt="Screen Shot 2022-11-25 at 11 47 13" src="https://user-images.githubusercontent.com/16502320/203903270-a43553e4-47a8-43e2-847d-4afbc1b1109e.png">

**Comment by Gonals** [comment] 2022-11-25 14:15
Hmmm. @amyevans, @Julesssss, will [this PR](https://github.com/Expensify/Web-Expensify/pull/35588) fix this?

**Comment by Julesssss** [comment] 2022-11-25 14:27
> "Split" should be clickable after split bill between participants.

Should it? Where would this take you? 

The entire message is clickable already so I don't know why we hightlight 'split'. Additionally, there is not such thing as an IOU on a group chat, we dsimply create multiple 1:1 IOUs in this case, so the only clickable link should appear in the 1:1 chat.

**Comment by Gonals** [comment] 2022-11-28 11:41
@Julesssss It certainly `looks` clickable 😆

**Comment by amyevans** [comment] 2022-11-28 19:40
> will https://github.com/Expensify/Web-Expensify/pull/35588 fix this?

Nope.

To @Julesssss point though, it doesn't make sense for `Split` to be (or appear to be) hyperlinked somewhere, because there's no one place to take the user. So I'd vote we remove the hyperlink styles on the word `Split`.

**Comment by Gonals** [comment] 2022-11-29 10:17
Agreed. I'll just remove the formatting 👍

**Comment by Tushu17** [comment] 2022-11-29 10:46
Hello @Gonals, I was aware that we don't have a iou page for 'split' payment, I had reported this issue on slack [(here)](https://expensify.slack.com/archives/C049HHMV9SM/p1669313996027739) to remove hyperlink style from the word 'split'. I had already posted a solution for the same.

> ### Proposal
> We just need to change:-
> 
> diff
> -                    <Text style={[styles.chatItemMessageLink]}>
> +                   <Text style={[props.shouldAllowViewDetails ? styles.chatItemMessageLink : undefined]}>
> 
> 
> https://github.com/Expensify/App/blob/585816ce3a3362673e864ff8545d6a0c303520ee/src/components/ReportActionItem/IOUQuote.js#L48

can anyone review my proposal and Since I reported my issue on slack before this issue was logged, will i be eligible for reporting bonus?

**Comment by Gonals** [comment] 2022-11-29 15:21
@sonialiap, we would recognize the bug report @Tushu17 mentions, right?

**Comment by Tushu17** [comment] 2022-11-29 17:24
@Gonals The solution used in your PR is quite similar to my proposal ([here](https://github.com/Expensify/App/issues/13022#issuecomment-1326836243)) which I posted few days back, Ig I should be compensated for the solution as well.

**Comment by Tushu17** [comment] 2022-11-30 19:49
> @Gonals The solution used in your PR is quite similar to my proposal ([here](https://github.com/Expensify/App/issues/13022#issuecomment-1326836243)) which I posted few days back, Ig I should be compensated for the solution as well.

@mountiny, Can you please look into this matter.

**Comment by mountiny** [comment] 2022-11-30 21:59
@Tushu17 Hello! Thanks for reporting, this indeed does not make sense and mentioned. You are eligible for reporting bonus.

Unfortunately, to follow the contribution guidelines and make sure they are applied consistently everywhere, this issue has not been labelled as `External` or `Help Wanted` hence any proposals posted can be used by us to fix the issue without compensation. I am sorry for that and trust me we appreciate your help with the issues here.

**Comment by Tushu17** [comment] 2022-12-01 14:00
@mountiny Thanks for looking into this, I've read the contribution guidelines, and based on those guidelines, your decision makes sense to me.

> this issue has not been labelled as `External` or `Help Wanted`.

I posted my solution before any label because I assumed this issue would be an external issue as it's a small fix.

> Unfortunately, to follow the contribution guidelines and make sure they are applied consistently everywhere,

In issue #13203, The reporter has posted a solution just like me before any "External" or "Help Wanted" label, but the contributor there is getting compensated for his solution. So IG guidelines are not being followed everywhere, which is kind of unfair for other contributors.

**Comment by mountiny** [comment] 2022-12-01 15:38
@Tushu17 Sorry for this, with so many people on the team who manage contributors it is inevitable someone does not follow the guidelines.

We thrive to create fair conditions and environment so I have started a discussion on this topic and how we could ensure we all take same approach to all involved parties and keep than happy :) I will update here once we decide about the process to follow.

**Comment by dhairyasenjaliya** [comment] 2022-12-02 07:03
hello, @Tushu17 @mountiny  In my case internal developer agreed to use my proposal 
https://github.com/Expensify/App/issues/13203#issuecomment-1332704868 ,  but there might be a case without a `help wanted` label internal members can solve the issue on their own even if they have a proposal I have faced multiple times but that is quite fair actually according to guild line if we post a solution before label `help wanted` does not guarantee compensation, that's the risk generally an external contributor should be considered while proposing the solution before the label 

- I have been working here for quite a while, and the team is quite fair to all

**Comment by mountiny** [comment] 2022-12-02 10:25
thanks @dhairyasenjaliya

Please allow us couple days to align internally on the guidelines, we havent updates this rule since a while now and lots of parts of the process has changed (mainly focus on urgency) so it is good to revisit this.

**Comment by mallenexpensify** [comment] 2022-12-24 01:33
@thesahindia can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~016472556625f2bc3e

**Comment by thesahindia** [comment] 2022-12-24 08:37
> @thesahindia can you please accept the job and reply here once you have? https://www.upwork.com/jobs/~016472556625f2bc3e

Accepted!

**Comment by Tushu17** [comment] 2022-12-24 08:47
> @sonialiap, we would recognize the bug report @Tushu17 mentions, right?

Hello @mallenexpensify I'm eligible for reporting bonus. 

>  I will update here once we decide about the process to follow.

@mountiny was checking on my eligibility for contributing compensation. So can you also conclude his final decision?

**Comment by mountiny** [comment] 2022-12-25 17:37
@Tushu17 hello, yes sorry for not posting here. We have reaffirmed the guidelines and since then the issues are closed before External label is applied. To stick with this process, I would say we wont proceed with paying out for the solution per the existing guidelines. Thanks for understanding and hopefully coming forward these borderline situations wont occur.

@mallenexpensify Can you please check the reporting bonus for @Tushu17 They have mentioned it in their proposal https://github.com/Expensify/App/issues/13022#issuecomment-1326836243

**Comment by mallenexpensify** [comment] 2022-12-27 00:16
Thanks for the help @mountiny 
@thesahindia you've been paid $1000 for PR review
@Tushu17 , I hired you for $250 for reporting, can you please accept the job and reply here once you have?

**Comment by Tushu17** [comment] 2022-12-27 17:13
@mallenexpensify Thank you, Offer accepted.

**Comment by mallenexpensify** [comment] 2022-12-27 17:49
Paid @Tushu17 
@Gonals @sonialiap , can you update the BZ checklist plz ? https://github.com/Expensify/App/issues/13022#issuecomment-1341857234

bumping to weekly

**Comment by mallenexpensify** [comment] 2023-01-20 00:27
@sonialiap this wasn't going overdue because of the `Reviewing` label, so you likely missed it.  Can you add the regression test step please then close?  Thx https://github.com/Expensify/App/issues/13022#issuecomment-1341857234

**Comment by mountiny** [comment] 2023-01-25 08:59
I think this one is already covered by the IOU tests Applause has since clicking the Split/ Requested/ Cancelled should open the details page so I think we are good to close this issue out given that. The bug was also caught by Applause which means they most likely test for this already

**Closed by mountiny** 2023-01-25 08:59 UTC
Labels: Engineering, Daily, Improvement, Internal, Overdue, Awaiting Payment, Bug
