### ISSUE TITLE
mWeb - Chat - Not here page displayed when going online after deleting a thread message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51825] opened 2024-10-31 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**  N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nathanmulugetatesting+2004@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/51422
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open a chat report
3. Go offline
4. Send a message
5. Reply in thread of that message
6. Send a message and delete the message inside of the thread
7. Go online

## Expected Result:
Nothing happens

## Actual Result:
Hmmm not here page is displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/6e194429-81a2-4e07-a95b-af250a2ad93f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-31 18:35
@OfstadC  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-11-01 02:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page is shown after going to a new thread while offline.

### What is the root cause of that problem?
When we open the new thread while offline, there will be 3 open report request (but only the last one sent). The first one when we optimistically create the thread and then send the parent report action ID to the request (along with other data).
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/libs/actions/Report.ts#L1099-L1101

The 2nd one is when the report screen is mounted.
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/home/ReportScreen.tsx#L489-L496

And the 3rd one is in this effect. (there is an issue to prevent this to be called)
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/home/ReportScreen.tsx#L580-L587

The 2nd and 3rd calls shouldn't be made because it's an optimistic report.
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/home/ReportScreen.tsx#L441-L446

`shouldFetchReport` will return false for optimistic report and report that has not found error.
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/libs/shouldFetchReport.ts#L4-L8

However, the ` && (isInitialPageReady || isLinkedMessagePageReady)` was added in https://github.com/Expensify/App/pull/44488 which causes the OpenReport to be called. `isInitialPageReady` checks for the report actions length.
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/home/ReportScreen.tsx#L337-L339

But when we open report, the report actions is still loading, so `isInitialPageReady` return false and an OpenReport request is made with a `parentReportActionID` as -1.

### What changes do you think we should make in order to solve the problem?

I think it doesn't make sense to tie `shouldFetchReport` with `isInitialPageReady`. If `shouldFetchReport` is false, then don't fetch the report. No need for the report actions to be available. `shouldFetchReport` only checks for the `report` object, so it doesn't depend on report actions. So, the solution is to remove, ` && (isInitialPageReady || isLinkedMessagePageReady)`
https://github.com/Expensify/App/blob/6763f1a114817c059426c7304b605e1e31cdaa10/src/pages/home/ReportScreen.tsx#L441-L443

**Comment by OfstadC** [comment] 2024-11-04 22:08
I feel like this isn't a real world scenario - so closing

**Closed by OfstadC** 2024-11-04 22:08 UTC
Labels: Daily, Overdue, Bug

**Comment by bernhardoj** [comment] 2024-11-05 05:54
@OfstadC hi, just to clarify, you can reproduce this issue just by opening a new thread while offline (without deleting any message) and then go online which I think a real scenario that could happen commonly.

It also sometimes happen without going offline at all, but it's just easier to repro while offline.
