### ISSUE TITLE
 Invoices - App crashes after sending an invoice from FAB

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47914] opened 2024-08-23 12:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch New Expensify app
2. Go to FAB > Send invoice
3. Enter amount > Next
4. Select a user > Next
5. Send the invoice

## Expected Result:
App will not crash

## Actual Result:
App crashes after sending an invoice from FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e3f11df2-dac9-4ead-925c-e2cd2802a46f

[logs (2).txt](https://github.com/user-attachments/files/16728617/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @tgolen</details>

**Comment by tgolen** [comment] 2024-08-23 14:06
Thank you @VickyStash!

**Comment by VickyStash** [comment] 2024-08-23 14:09
I've tried to reproduce the crash on different platforms and accounts and had no luck.

https://github.com/user-attachments/assets/2b0a3761-88e2-4526-8a1f-16aca5729900

https://github.com/user-attachments/assets/21137979-adea-4de8-8ad9-f41ece31e14c

@lanitochka17 Do I miss anything?

**Comment by lanitochka17** [comment] 2024-08-23 17:55
Issue is still reproducible on IOS

https://github.com/user-attachments/assets/594837ef-c92d-4cc2-8e6a-c175f253dc13

**Comment by nkdengineer** [comment] 2024-08-26 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after sending an invoice from FAB

### What is the root cause of that problem?
After we create a send invoice, `IOURequestStepConfirmation` can be unmounted after the draft transaction is reset then `report?.policyID ?? policy?.id` to be `undefined`

https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L624

Then `policyID` prop here is an empty string by default that causes the app crash [here](https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/components/MoneyRequestConfirmationList.tsx#L215-L218) since the OnyxKey change from `policyDrafts_id` to `policyDrafts_`


https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/components/MoneyRequestConfirmationList.tsx#L196

### What changes do you think we should make in order to solve the problem?
We should use `getIOURequestPolicyID` function to get the `policyID` as we do [here](https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L644)


https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/pages/iou/request/step/IOURequestStepConfirmation.tsx#L624

OPTIONAL: We can also fallback `-1` here to prevent the same bug if we pass the empty string `policyID` to `MoneyRequestConfirmationList`
```
const [mileageRatesDraft] = useOnyx(`${ONYXKEYS.COLLECTION.POLICY_DRAFTS}${policyID || -1}`, { 
   selector: (selectedPolicy: OnyxEntry<OnyxTypes.Policy>) => DistanceRequestUtils.getMileageRates(selectedPolicy), 
}); 
```

https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/components/MoneyRequestConfirmationList.tsx#L215-L218
### What alternative solutions did you explore? (Optional)
NA

**Comment by nkdengineer** [comment] 2024-08-26 08:30
@VickyStash @tgolen I can reproduce this issue on the latest main on mWeb safari.

https://github.com/user-attachments/assets/b367e97f-2bfe-444f-b88b-ec8962daca36

**Comment by VickyStash** [comment] 2024-08-26 08:43
Good catch @nkdengineer! So it looks like [this PR](https://github.com/Expensify/App/pull/46859/files#diff-29ef0426ea09b0af3420c95911645adcd54c0d3d4c0d8c4fa5aa99dfe37a3646R215) caused this regression, right?

**Comment by nkdengineer** [comment] 2024-08-26 08:44
@VickyStash Yes.

**Comment by tgolen** [comment] 2024-08-26 16:51
@dominictb Looks like https://github.com/Expensify/App/pull/46859 caused the regression here so I will assign it to you. If you cannot write a fix today, then we'll need to revert that PR until a fix can be made. Are you able to submit a fix today?

**Comment by tgolen** [comment] 2024-08-26 17:03
@Nodebrute OK, thank you for letting me know. Unless I'm missing something though, your issue is unrelated to what is causing the crash in the original description of this issue, right?

**Comment by tgolen** [comment] 2024-08-26 17:12
@Nodebrute Thank you for clarifying! Please use our normal bug reporting process for the crash you found: https://github.com/Expensify/App/issues/new?assignees=&labels=Bug%2C+Daily&projects=&template=Standard.md

**Comment by puneetlath** [comment] 2024-08-26 21:42
Demoting since the fix has been CP'd.

**Comment by tgolen** [comment] 2024-08-30 14:42
# Weekly Update
- The crash was fixed in [this PR](https://github.com/Expensify/App/pull/48016)
- The regression is being handled in the [original GH](https://github.com/Expensify/App/issues/46008)

### Next Steps
- @tgolen Close this issue since the fix has been deployed to production

#### ETA
- Today, Aug 30

**Closed by tgolen** 2024-08-30 14:42 UTC
Labels: Reviewing, Engineering, Weekly
