### ISSUE TITLE
[$500] [HOLD for payment 2024-03-29] [HOLD for payment 2024-03-26]  Category - Parent category is not checked above subcategories when there is <8 categories

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38564] opened 2024-03-19 10:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- There are categories in Parent and Parent: Child format.
- There are more than 8 categories.

1. Go to staging.new.expensify.com.
2. Go to workspace chat.
3. Start manual request flow.
4. In confirmation page, click Show more > Category.
5. Select Parent category.
6. Click Category.
7. Note that the parent category is checked at the top and also above subcategories.
8. As admin, disable categories so that there are less than 8 categories.

## Expected Result:
The parent category will be checked at the top and also above the subcategorie swhen there are less than 8 categories.

## Actual Result:
The parent category is only checked at the top and not checked above the subcategories when there are less than 8 categories.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a89b465b-fca3-473e-99f9-f889c8b036a0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014cdd234c5c7999da</li>
        <li>Upwork Job ID: 1775543168628084736</li>
        <li>Last Price Increase: 2024-04-03</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-19 10:16
Production video 


https://github.com/Expensify/App/assets/115492554/940bfb52-8967-4a32-a6e4-bb1e12637fef

**Comment by lakchote** [comment] 2024-03-19 10:25
Offending [PR](https://github.com/Expensify/App/pull/38279) found.

**Comment by lakchote** [comment] 2024-03-19 12:33
> On production, it's not working properly already.

Hmm, it it said `Reproducible in production?: N` so I thought your PR would be the the root cause given it concerned <8 categories.

Thanks for the fast TA and raising a follow-up PR, it's appreciated.

**Comment by miljakljajic** [comment] 2024-03-19 13:40
Just getting to this now after some calls - reviewing

**Comment by miljakljajic** [comment] 2024-03-19 13:43
Fantastic, thank you

**Comment by hungvu193** [comment] 2024-03-19 14:50
I'm assigned to this one, I can review it

**Comment by c3024** [comment] 2024-03-19 14:52
I'm available.

**Comment by lakchote** [comment] 2024-03-19 17:14
> @miljakljajic @lakchote PR is ready but I'm not sure who is the correct C+ to be assigned here. Please handle that for me. Thanks!

Good question, I'd say it's @c3024 that should be the reviewer since he had the context of the issue beforehand and knew a follow-up PR for this problem was going to be raised. @miljakljajic please feel free to say otherwise if you feel that shouldn't be the case.

**Comment by AndrewGable** [comment] 2024-03-19 22:40
Bug looks resolved from my testing, however, I do want to leave this open for @miljakljajic to confirm everything is working with tags correctly.

**Comment by miljakljajic** [comment] 2024-03-28 12:06
Testing now and will issue payment

**Comment by miljakljajic** [comment] 2024-04-03 15:16
Apologies I never updated this GH - working as expected now:

<img width="1437" alt="image" src="https://github.com/Expensify/App/assets/28715117/35de1797-5a47-4eda-a0e9-cd1fa00ed8bb">

**Comment by lakchote** [comment] 2024-04-03 15:36
> Thank you @gijoe0295 ! @lakchote @AndrewGable just to be sure, is there no payment for @c3024 here? I thought we issued payment when a PR was reviewed regardless of whether it was caused by a regression?

I would say yes to give payment, given it's a follow-up and a case we didn't cover yet. I'm asking for confirmation, and will let you know.

**Comment by miljakljajic** [comment] 2024-04-04 14:20
Noted, thank you Lucian! In that case, I think we can close.

**Closed by miljakljajic** 2024-04-04 14:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
