### ISSUE TITLE
LHN chat appearing for $0 invoice not finish loading and won't marked as read

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44276] opened 2024-06-24 15:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1719235655502919

## Action Performed:
1. Open app
2. Click on the chat with $0 invoice
## Expected Result:
Chat should finish loading
## Actual Result:
Not loading and unable to make that read and stuck in the LHN
The reportID: 2746481461214539
[Logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22898d063c5c1c516e-DEN%22)+AND+timestamp:[2024-06-24T12:22:02.378Z+TO+2024-06-24T14:22:02.378Z]&index=logs_expensify-029074) of an OpenReport command that fails with error Got empty report summary from Auth::openReport, user does not have access to this report
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (19)](https://github.com/Expensify/App/assets/38435837/d413fb86-6dc2-4873-b992-0ccd53b416f9)

![image (18)](https://github.com/Expensify/App/assets/38435837/e5c900a6-d2a7-40d5-af63-e576091d3979)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2024-06-25 14:36
@arosiclair it looks like you were maybe the one that added [this error](https://github.com/Expensify/Web-Expensify/blob/d53237b29602971816886c13d410c8328e269eef/lib/ReportAPI.php#L5707) in Web-E. Do you have any insight into what caused it for me? I think @cristipaval was starting to look into this, but I don't know that he got too far in the investigation.

I think there is also something we need to do to handle this error on the frontend better. It's easy to test this out locally (just force that throw to happen by replacing `!$reportSummary` with `true`, and then switching chats on NewDot. The backend will return this error which the frontend doesn't handle and just stays in a loading state:

```
{
    "code": 666,
    "jsonCode": 403,
    "type": "Expensify\\Libs\\Error\\ExpError",
    "UUID": "da7984df-628f-41f6-a2b8-ecd4499f7975",
    "message": "Report not found",
    "title": "",
    "data": {
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_6008608092027638",
                "value": {
                    "errorFields": {
                        "notFound": {
                            "1719326012640726": "Report not found"
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_6008608092027638",
            "value": {
                "errorFields": {
                    "notFound": {
                        "1719326012640726": "Report not found"
                    }
                }
            }
        }
    ],
    "requestID": "o3lOxW"
}
```

**Comment by tgolen** [comment] 2024-06-25 14:39
It looks like those `errorFields` are either not making it into Onyx, or they are being immediately cleared out by something else. Here is what my Onyx looks like for that ^ report.

![image](https://github.com/Expensify/App/assets/1228807/a654f54c-dbb4-4a61-b623-526308d86daa)

**Comment by tgolen** [comment] 2024-06-25 14:41
Here are my client-side logs (note: I had to get these logs from triggering the error on a second report, so the reportIDs won't match, but it's still the same problem.

<details>
<summary>logs</summary>

```
Log.ts:69 [info] [Onyx] set called for key: reportUserIsLeavingRoom_4116327630963703 hasChanged: false - ""
Log.ts:69 [hmmm] [Pusher] Attempted to unsubscribe or unbind from a channel, but Pusher-JS has no knowledge of it - {"channelName":"private-report-reportID-4116327630963703-8ebfd8b0df6742c79a3660185b63bffxxxtim","eventName":"client-userIsLeavingRoom"}
8[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
Log.ts:69 
```

</details>

**Comment by tgolen** [comment] 2024-06-25 14:43
My guess is that maybe these are cancelling each other out:

![image](https://github.com/Expensify/App/assets/1228807/5e3238c8-a8ba-4a81-8429-d8f01484069b)

**Comment by dylanexpensify** [comment] 2024-06-26 09:22
Ongoing

**Comment by arosiclair** [comment] 2024-06-26 13:51
The updates to `errorFields.notFound` canceling out may get fixed in [this issue](https://github.com/Expensify/App/issues/43357#issuecomment-2158558652) I'm working on. In a normal scenario though, `errorFields.notFound` should trigger the Not Found page to display [here](https://github.com/Expensify/App/blob/8a26c9d08d5a00a9e6e42284cdfcd2d208d4edf6/src/pages/home/ReportScreen.tsx#L295-L297).

**Comment by tgolen** [comment] 2024-06-26 14:20
All right, if that's the case, then I don't know if there is much more to do in this issue since it can't be readily reproduced. I'm going to close it for now.

**Closed by tgolen** 2024-06-26 14:20 UTC
Labels: Daily, Bug, AutoAssignerNewDotQuality
