### ISSUE TITLE
[$250] Chat - Emoji codes overlapping for some emoji suggestions

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41779] opened 2024-05-07 16:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+1117ck@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch ND app & log in
2. Navigate to any chat
3. Type ":tr" or ":arr" ::hea" to trigger emoji suggestions
4. Scroll down & observe emoji codes overlapping

## Expected Result:
Emojis codes should should be clearly shown in emoji suggestions list & all suggestions should be displayed in the list

## Actual Result:
1. Emoji codes overlapping for some emoji suggestions (for eg - :heartbeat: & :revolving_hearts:, :next_track_button: & :previous_track_button:, :arrows_clockwise: & :arrows_counterclockwise:)
2. Overlapped emoji suggestion missing from list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d9dbbda2-33dc-43d9-9aeb-0b5c97c4fd67

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0121813b34b025e1d6</li>
        <li>Upwork Job ID: 1788031980674232320</li>
        <li>Last Price Increase: 2024-06-05</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 102518894</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by izarutskaya** [comment] 2024-05-07 16:29
We think this issue might be related to the #vip-vsb.

**Comment by c3024** [comment] 2024-05-10 16:08
This is not reproducible on `main`.


https://github.com/Expensify/App/assets/102477862/ac2c2141-b1c8-4127-9b9c-092dc2738e5e

**Comment by c3024** [comment] 2024-05-13 16:39
Thanks for the bump. I'll check.

**Comment by c3024** [comment] 2024-05-14 07:04
Is this specific to some devices? This is on a POCO M4 for a new account.

https://github.com/Expensify/App/assets/102477862/a69d983d-5b9a-4a8c-b401-612618a34157

**Comment by slafortune** [comment] 2024-05-17 20:35
I **had** been able to reproduce this, I also have a Samsung - Galaxy Z Flip 4 - I can't reproduce this any more.  I did have a mobile update yesterday.

@dominictb are you still able to reproduce this?

**Comment by c3024** [comment] 2024-05-18 04:36
Let me check on another physical device as well.

**Comment by c3024** [comment] 2024-05-18 08:14
@dominictb 

I tested again with the [change you suggested](https://github.com/Expensify/App/issues/41779#issuecomment-2102456269). 

I still see this  
>When the popup first appears the letters overlap

https://github.com/Expensify/App/assets/102477862/84f90e36-10bc-4088-953f-25668c88a865

**Comment by c3024** [comment] 2024-05-22 03:49
@dominictb 

From [the video here](https://github.com/Expensify/App/issues/41779#issuecomment-2118689385)

![frame_0079 copy](https://github.com/Expensify/App/assets/102477862/fdf697b3-f095-4cc3-bef8-5fad22a316c6)
![frame_0152 copy](https://github.com/Expensify/App/assets/102477862/e4e5b1fd-9c9c-4ccc-bce9-1466e2a7f3ce)
![frame_0246 copy](https://github.com/Expensify/App/assets/102477862/8d18bb34-3787-4f4e-90b3-2e6e9c7a2272)
![frame_0247 copy](https://github.com/Expensify/App/assets/102477862/4fb2be80-9846-4339-a495-402da99a6485)
![frame_0589 copy](https://github.com/Expensify/App/assets/102477862/eead78ca-2f40-41fb-b423-3a4c11552e22)

**Comment by slafortune** [comment] 2024-05-23 22:33
@dominictb I am not able to reproduce this any longer.  If this is only reproducible on Main inconsistantly and not on staging, I suggest we close this issue.

I'm still trying to determine if this is a consistent issue. I'll be out until June 4th, so I'm adding another BZ in the meantime.

**Comment by c3024** [comment] 2024-05-24 15:23
Tried with a Samsung F23 and still can't repro the bug on `main` even with [steps suggested here](https://github.com/Expensify/App/issues/41779#issuecomment-2123094097)

**Comment by c3024** [comment] 2024-05-27 15:10
I tried several times and it is not repro on any devices with me.

cc: @Expensify/contributor-plus , if anyone can reproduce this bug, please take this.

**Comment by DylanDylann** [comment] 2024-05-27 15:27
I can take over this issue as C+

**Comment by c3024** [comment] 2024-05-27 15:29
Thanks, unassigning myself.

**Comment by DylanDylann** [comment] 2024-05-30 07:38
@dominictb There have been many changes since your proposal was created and I see it is outdated in some points. Please help to update your proposal

**Comment by DylanDylann** [comment] 2024-06-04 07:56
@MelvinBot Calm down, the contributor just came back. Let's give him a bit time to update this issue

**Comment by mvtglobally** [comment] 2024-06-05 21:21
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2024-06-10 10:12
@slafortune PLease add re-test label here

**Closed** 2024-06-10 13:52 UTC
Labels: External, Daily, Help Wanted, Bug
