### ISSUE TITLE
[$500] Workspace - Unable to open settings on a policy disabled account

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#35802] opened 2024-02-05 10:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Log in as [applausetester+disabledpolicy@applause.expensifail.com](mailto:applausetester+disabledpolicy@applause.expensifail.com)
2. Open preferences and go offline
3. Go back to LHN
4. Click on the "Settings" button
5. Create a new workspace with the top right "New workspace" button
6. Click on the "Chats" button
7. Open preferences and go online
8. Go back to LHN
9. Wait until the workspace chats disappear
10. Click on the "Choose a workspace" button - "Expensify"
11. Click on the "Choose a workspace" button - "Workspace with a red dot"
12. Click on the "Choose a workspace" button
13. Click away to close it
14. Click on the "Settings" tab

## Expected Result:
I should be albe to navigate to the settings tab.

## Actual Result:
I get a "Hmm... it's not here" error when clicking on "Settings". I could repro it with other normal accounts too with different steps regarding the workspace but it didn't show up every time there.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/2a89811d-47d2-46d3-af3d-93ad658e8db4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b7315d221412f0b</li>
        <li>Upwork Job ID: 1754455245810069504</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-02-05 10:43
We think that this bug might be related to #wave8-collect-admins
CC @zanyrenney

**Comment by Gonals** [comment] 2024-02-05 12:36
@izarutskaya, I'm trying to follow the steps, but:

> Wait until the workspace chats disappear

 This one never happens for me. Do you get any errors in the console (or anywhere)?

**Comment by Gonals** [comment] 2024-02-05 13:56
I've tried with a couple of test accounts and haven't seen the issue. I can't log in with applausetester+disabledpolicy@applause.expensifail.com, though (Gmail is not letting me in)

**Comment by mountiny** [comment] 2024-02-05 14:44
It seems like the policy creation has failed and this was the end results, if we can create policies though in general this should not be a blocker

**Comment by Gonals** [comment] 2024-02-07 16:11
Still unable to reproduce, so I think it might be a one-case scenario. Closing for now. Feel free to reopen if you disagree

**Closed by Gonals** 2024-02-07 16:11 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
