### ISSUE TITLE
[HOLD for payment 2024-02-12] [$500] Search - Selecting last possible member to group hides previously selected members

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34111] opened 2024-01-08 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
. Login to NEwDot
2. Click on the green + button
3. Click on the "Start chat" option
4. Make a search to narrow option, f.e. "pronin"
5. Select 8 random users from the search list

## Expected Result:
Selected members should be displayed like they were during selection

## Actual Result:
Selected members are not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/30173e6f-791b-49af-81e2-7a2fc3763217

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016db68bc29d435aaa</li>
        <li>Upwork Job ID: 1744445899583787008</li>
        <li>Last Price Increase: 2024-01-08</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28109754</li>
<li>Krishna2323 | Contributor | 28109755</li>
</ul></li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2024-01-08 19:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Selecting last possible member to group hides previously selected members

### What is the root cause of that problem?

When, the `maxParticipantsReached` is true we return an empty list of participants.

### What changes do you think we should make in order to solve the problem?


Add the participants to `sectionsList` when `maxParticipantsReached` is true

**Comment by unicorndev-727** [comment] 2024-01-08 19:56
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Selecting last possible member to group hides previously selected members
### What is the root cause of that problem?
The root cause is here.
```
const maxParticipantsReached = selectedOptions.length === CONST.REPORT.MAXIMUM_PARTICIPANTS;
```

 https://github.com/Expensify/App/blob/7ae1ec7e74b908e6340bccaf7e42b0345d766711/src/pages/iou/request/step/IOURequestStepConfirmation.js#L220
### What changes do you think we should make in order to solve the problem?
We need to send the maxParticipantsReached as a false here.
```
const headerMessage = OptionsListUtils.getHeaderMessage(
        filteredPersonalDetails.length + filteredRecentReports.length !== 0,
        Boolean(filteredUserToInvite),
        searchTerm.trim(),
        maxParticipantsReached,
        _.some(selectedOptions, (participant) => participant.searchText.toLowerCase().includes(searchTerm.trim().toLowerCase())),
    );
```
### What alternative solutions did you explore?
N/A

**Comment by aim-salam** [comment] 2024-01-08 22:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - Selecting last possible member to group hides previously selected members

### What is the root cause of that problem?

When `maxParticipantsReached` is true, sectionsList will return zero item

This is because `formatResults` will show the selected item when searchTerm is `' '`



```
const formatResults = OptionsListUtils.formatSectionsFromSearchTerm(searchTerm, selectedOptions, filteredRecentReports, filteredPersonalDetails, {}, false, indexOffset);
```

https://github.com/Expensify/App/blob/c0c4d64f67d263472a713f5c1aa4b0ec8b0080f9/src/pages/NewChatPage.js#L78-L84

https://github.com/Expensify/App/blob/5cb22df483ef73040cac6808f1f23988c0c7b342/src/libs/OptionsListUtils.js#L1886-L1892

### What changes do you think we should make in order to solve the problem?

When `maxParticipantsReached` is true, set searchTerm into `' '`

```diff
        if (maxParticipantsReached) {
+            setSearchTerm('')


            return sectionsList;
        }
```

https://github.com/Expensify/App/blob/5cb22df483ef73040cac6808f1f23988c0c7b342/src/pages/NewChatPage.js#L82-L84C10


### What alternative solutions did you explore? (Optional)

**Comment by aim-salam** [comment] 2024-01-09 02:15
.

**Comment by aim-salam** [comment] 2024-01-09 04:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Search - Selecting last possible member to group hides previously selected members

### What is the root cause of that problem?

When `maxParticipantsReached` is true, `sections` only pushed by `formatResults`'s list only.
This cause no `recents`,`contacts`,`filteredUserToInvite` list.

https://github.com/Expensify/App/blob/668e54bb705c74ece910cb9f920030070d8c6a5a/src/pages/NewChatPage.js#L82-L84

But `formatResults` have no item when `OptionsListUtils.formatSectionsFromSearchTerm()` return no item when `searchTerm` was given in.

https://github.com/Expensify/App/blob/668e54bb705c74ece910cb9f920030070d8c6a5a/src/pages/NewChatPage.js#L78

This is due to `selectedParticipantsWithoutDetails` only return `true` when selected participant meet `isPartOfSearchTerm && !isReportInRecentReports && !isReportInPersonalDetails`.

https://github.com/Expensify/App/blob/668e54bb705c74ece910cb9f920030070d8c6a5a/src/libs/OptionsListUtils.js#L1914

Meaning selected participant who is meet 
1. match with `searchTerm`
2. not in `recent` and `contact`



Result:
`recent`,`contact`,`filteredUserToInvite` not pushed into `sectionLists`
`formatResults` doesnt have items to show up even push into `sectionLists`.


### What changes do you think we should make in order to solve the problem?

When `formatSectionsFromSearchTerm()` provided with `searchTerm`,
`selectedParticipantsWithoutDetails` should have condition when `maxParticipantsReached` is true.

https://github.com/Expensify/App/blob/668e54bb705c74ece910cb9f920030070d8c6a5a/src/libs/OptionsListUtils.js#L1909-L1915


```diff
    const selectedParticipantsWithoutDetails = _.filter(selectedOptions, (participant) => {
        const accountID = lodashGet(participant, 'accountID', null);
        const isPartOfSearchTerm = participant.searchText.toLowerCase().includes(searchTerm.trim().toLowerCase());
        const isReportInRecentReports = _.some(filteredRecentReports, (report) => report.accountID === accountID);
        const isReportInPersonalDetails = _.some(filteredPersonalDetails, (personalDetail) => personalDetail.accountID === accountID);
+       if(maxParticipantsReached){
+       return isPartOfSearchTerm && isReportInRecentReports || isReportInPersonalDetails;
+       }
        return isPartOfSearchTerm && !isReportInRecentReports && !isReportInPersonalDetails;
    });
```

So, when `maxParticipantsReached` is true, any selected participant meet this requirement
1. must be match with `searchTerm`
2. must be inside `recent` or `contact`

will be return into `formatResults`

Result:
When `maxParticipantsReached` is true, `formatResults` have items to show


https://github.com/Expensify/App/assets/142758714/67bc86ec-7c31-4e94-b437-8fcae8176366



### What alternative solutions did you explore? (Optional)

**Comment by sophiepintoraetz** [comment] 2024-01-12 02:51
Hey @c3024 - can you take a look at the proposals please?

**Comment by c3024** [comment] 2024-01-15 03:28
Thank you all for your proposals.

I too think that passing maxParticipantsReached flag to the formatSectionsFromSearchTerm is the way to go. I see @Krishna2323 's proposal suggested this correctly without repetition of code first and with additional search optimization.

@Krishna2323 's [proposal here](https://github.com/Expensify/App/issues/34111#issuecomment-1881839835) looks good to me.

🎀 👀 🎀 C+ Reviewed

**Comment by abzokhattab** [comment] 2024-01-15 08:28
Isn’t that proposal almost the same as mine @sophiepintoraetz @c3024 please keep in mind that i was the first to identify the actual root cause of the issue and pointed out that we have the same issue in other pages

**Comment by sophiepintoraetz** [comment] 2024-01-19 03:29
Waiting on @Beamanator to review the proposals.

@abzokhattab - it is more than just identifying the root cause, it is also having the best solution to the problem. In this instance, @c3024 elected for @Krishna2323 technical proposal for reasons given. Hope that clears things up!

**Comment by Beamanator** [comment] 2024-01-19 09:26
Overall I agree with choosing @Krishna2323 's proposal since:
1. It requires less code being added to `formatSectionsFromSearchTerm`
2. It results in calling `Report.searchInServer` less often

It does look like @abzokhattab 's proposal is the first to identify passing `maxParticipantsReached` to `formatSectionsFromSearchTerm`, and it does identify that this needs to happen on 3 pages (NewChatPage, MoneyTemporaryForRefactorRequestParticipantsSelector, and MoneyRequestParticipantsSelector) which is helpful, but still we should go with @Krishna2323 's implementation

**Comment by garrettmknight** [comment] 2024-02-06 20:13
Went to prod yesterday.

**Comment by garrettmknight** [comment] 2024-02-12 19:08
Paid out - @c3024 can you finish the checklist when you get a chance?

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  [@c3024] The PR that introduced the bug has been identified. Link to the PR:
- [ ]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  [@c3024] Determine if we should create a regression test for this bug.
- [ ]  [@c3024] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ]  [@garrettmknight] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by c3024** [comment] 2024-02-13 06:03
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
 
* [x]   [@c3024] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/commit/8f8f2c0d94d88edf0fb0785be8f762998c7d2907
* [x]   [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/8f8f2c0d94d88edf0fb0785be8f762998c7d2907#r138560696
* [x]   [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a missed case for the case of maximum participants selected. A discussion on Slack is unlikely to give steps that could have prevented this.
* [x]   [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]   [@c3024] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

### Regression Test Proposal
1. Click on FAB
2. Click on the "Start chat" option
3. Select 8 random users from the list
4. Enter some text in the search input
5. Verify that all selected members are shown below
6. Repeat the steps 3 and 4 for "Split Bill" flow and verify that all selected members are shown below

👍 or 👎

**Comment by garrettmknight** [comment] 2024-02-13 13:34
Closing!

**Closed by garrettmknight** 2024-02-13 13:34 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
