### ISSUE TITLE
Web -  Editing and deleting simultaneously ends up in deleted messages showing up again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26578] opened 2023-09-02 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a workspace Where User A is an admin
2.  Add User B to the workspace in step 1 and open the same Workspace from User B on another bowser
3.  Send a message from Use B to the workspace.
4.  Open the message from User A in the workspace
5.  Hover on the message from User A & Click on the Delete Icon and leave the pop up confirmation as opened
6.  Hover on the same message from user B and click on edit message, edit the message and leave it unsaved
7. Go to your network and disable connection (get offline)
8. From user A screen on the confirmation pop up click on delete
 9. Go to your network and get back online
10. Now immediately click on save changes from user B edit text field
11. The deleted message will reappear on both user A and User B screen as edited message

## Expected Result:
 The message will be deleted

## Actual Result:
The deleted message reappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.62.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b130e7c2-46b3-425f-bb64-dec19aa652c1

https://github.com/Expensify/App/assets/93399543/a501be7f-23e3-4648-bc19-a26a07245c14

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693253911482689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by garrettmknight** [comment] 2023-09-06 17:49
Couldn't reproduce on v1.3.64-2, closing.

**Closed by garrettmknight** 2023-09-06 17:49 UTC
Labels: Daily, Bug

**Comment by lidiyakelay** [comment] 2023-09-07 10:26
@kbecciv or @garrettmknight  the issue is still occurring in the latest version i have been able to reproduce

https://github.com/Expensify/App/assets/59802743/4abac286-716d-4c42-a7a6-0f76b7d32db5

**Comment by lidiyakelay** [comment] 2023-09-20 14:08
@kbecciv or @garrettmknight can you please check this
