### ISSUE TITLE
Dev: Web - The message "This is the beginning of your chat" is displayed for a while when opening the requested money detail

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23647] opened 2023-07-26 14:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to "Request money"
3. Enter the amount and request it
4. Now open requested money detail

## Expected Result:
The message "This is the beginning of your chat" should not be displayed when opening the requested money detail

## Actual Result:
The message "This is the beginning of your chat" is displayed for a while when opening the requested money detail

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.45-
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6a4e79ec-2436-46fd-96aa-a5bb225370a3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690313678511779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ayazhussain79** [comment] 2023-07-26 14:18
it is also reproducible when you click on "Reply in thread"

**Comment by Pujan92** [comment] 2023-07-26 14:21
Same RCA https://github.com/Expensify/App/issues/23638

**Comment by ayazhussain79** [comment] 2023-07-26 14:25
@Pujan92 its not about console error or workspace please check the steps and also the bug title

**Comment by Pujan92** [comment] 2023-07-26 14:28
@ayazhussain79 I have mentioned here https://github.com/Expensify/App/issues/23638#issuecomment-1651783608 in the comment that for 3 flows the RCA seems to be the same(new workspace, request money action & child report navigation)

**Comment by ayazhussain79** [comment] 2023-07-26 14:30
And you can check that on slack i have reported this bug before this one https://github.com/Expensify/App/issues/23638

**Comment by Pujan92** [comment] 2023-07-26 14:31
I am just trying to connect similar issues to avoid duplication. Definitely, the team will prioritize the earliest bug in that case.

**Comment by isabelastisser** [comment] 2023-07-26 19:56
I can't reproduce it, I don't get the `This is the beginning of your chat` view when clicking on the amount requested, it works as expected for me. Closing!

**Closed by isabelastisser** 2023-07-26 19:56 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by ayazhussain79** [comment] 2023-07-26 20:19
@isabelastisser please try that on latest main branch code its still reproducible 
You can also reproduce it on dev using these steps:

1. Open a chat 
2. Send a message and click on "Reply in thread"

**Comment by ayazhussain79** [comment] 2023-07-26 20:43
@Pujan92 @s-alves10 are you guys able to reproduce it right?

**Comment by ayazhussain79** [comment] 2023-07-28 15:53
@isabelastisser can you please check that again? now it is reproducible on staging

**Comment by s-alves10** [comment] 2023-07-28 15:59
@ayazhussain79 

Please check https://github.com/Expensify/App/issues/23638. Someone is working on this

**Comment by ayazhussain79** [comment] 2023-07-28 16:03
@s-alves10 Thank you commented there
