### ISSUE TITLE
[HOLD for payment 2023-12-28] [HOLD for payment 2023-12-26] [HOLD #32672] [Theme Switching] 🐛 Web - Chat - The scroll bar is white in the emoji suggestion list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32591] opened 2023-12-06 22:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Enter any emoji code (e.g: :wave: , :grimacing: , :smile: , etc) or "@" for opens a list of user suggestions

## Expected Result:
The scroll bar is grey

## Actual Result:
The scroll bar is white

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 
![Bug6303682_1701897642639!0612_1](https://github.com/Expensify/App/assets/78819774/7d08a23c-0386-49d0-8562-c8e5b6ff7939)

![Bug6303682_1701897642637!image__186_](https://github.com/Expensify/App/assets/78819774/8d2af3e5-02ec-4f7e-abf5-82994cb5e88c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c2daa05ba8f632d</li>
        <li>Upwork Job ID: 1732790748658282496</li>
        <li>Last Price Increase: 2023-12-07</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27999537</li>
</ul></li>
    </ul>
</details>

**Comment by bondydaa** [comment] 2023-12-06 22:45
taking a look at the staging checklists but I don't think this needs to block future deploys, it's a style thing which can be handled with a follow up PR.

**Comment by ZhenjaHorbach** [comment] 2023-12-06 22:47
Looks like a regression this PR
https://github.com/Expensify/App/pull/13036

**Comment by bondydaa** [comment] 2023-12-06 22:51
hmm what makes you think that PR? I don't see that it touched anything with emojis or style sheets.

**Comment by situchan** [comment] 2023-12-06 22:53
I think we can demote this to NAB unless that offending PR caused any other regressions.

**Comment by bondydaa** [comment] 2023-12-06 22:58
ok great thanks for confirming that

**Comment by grgia** [comment] 2023-12-06 23:05
<img width="406" alt="image" src="https://github.com/Expensify/App/assets/38015950/3d28d634-b54a-4b92-a063-3888116e230f">
@bondydaa I'm also unable to reproduce on mac. If this is windows only, its not a bug

**Comment by situchan** [comment] 2023-12-06 23:07
@grgia you need to type emoji code or mention @ in composer, not emoji button

https://github.com/Expensify/App/assets/108292595/d95275eb-b873-4971-be53-13a1dbd3d010

**Comment by grgia** [comment] 2023-12-06 23:11
if the other scrollbars are working, I think there's an alternative fix @situchan

**Comment by bondydaa** [comment] 2023-12-07 15:55
doh sorry @shubham1206agra I was too slow on getting the assignment after i added labels.

**Comment by sakluger** [comment] 2023-12-07 20:47
Happy to help, I withdrew the existing offer.

@chrispader do you need to be paid through Upwork, or are you with one of the agencies we work with?

**Comment by sakluger** [comment] 2023-12-08 17:16
Based on https://github.com/Expensify/App/issues/18963, @chrispader works with an agency so they do not require payment through Upwork. And @parasharrajat will be paid via NewDot manual request.

@bondydaa just to confirm, this will be fixed in https://github.com/Expensify/App/pull/32672 correct?

**Comment by chrispader** [comment] 2023-12-08 17:31
> Based on #18963, @chrispader works with an agency so they do not require payment through Upwork. And @parasharrajat will be paid via NewDot manual request.
> 
> @bondydaa just to confirm, this will be fixed in #32672 correct?

yes!

**Comment by sakluger** [comment] 2023-12-11 17:09
@parasharrajat thanks for clarifying, that helps! I've added a hold for https://github.com/Expensify/App/pull/32672.

**Comment by sakluger** [comment] 2023-12-25 16:34
I'm offline this week, along with most of my team for the holidays. I'll handle payment as soon as I return on Jan 2.

**Comment by sakluger** [comment] 2024-01-03 04:06
Sounds good, closing.

**Closed by sakluger** 2024-01-03 04:06 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
