### ISSUE TITLE
[$1000] Android - On first visit after login, app does not display emoji reaction in reply in thread main message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25902] opened 2023-08-24 22:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report and add few reactions to any message
3. Hover on that message and click on reply in thread
4. Add any message in it
5. Logout and again login
6. Directly open reply in thread report of step 4 and observe that app does not display emojis in it

## Expected Result:
App should display added reactions on visit to reply in thread report after login

## Actual Result:
App should display added reactions on main message when we visit to reply in thread report first time after login

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.57-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/34545ab3-b481-4514-8f38-6bf638f04a5f

https://github.com/Expensify/App/assets/115492554/ca0ac297-7810-441a-aca0-9751ac5e808e

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691906944875479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184d2ee9438cd3144</li>
        <li>Upwork Job ID: 1695163217342586880</li>
        <li>Last Price Increase: 2023-08-25</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-08-25 14:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On first visit after login, app does not display emoji reaction in reply in thread main message
### What is the root cause of that problem?

If we observe the flow clearly the we've added reactions in the main report which would come under report A's reportactions.

So whatever the info related to the reportaction would be saved under the Report A's info.

This only happens with the first message of a thread because that message is related to parent report.

After logout we won't be having any of parent report until parent report info saved into `Onyx`, because of that reactions would appear only after opening the parent report.


### What changes do you think we should make in order to solve the problem?
Maybe this can be backend but I don't think this needs backend intervention because I feel the system is designed the way it is and it's working good as well.

To solve this before opening any thread we should first get the info about the `parentReportID`.

Example here https://github.com/Expensify/App/blob/1f22dfed6448591493ecf1124ee3654fee74aec3/src/pages/home/report/ReportActionsView.js#L143 we could add a check like the following

```jsx
// Fetch Parent Report before fetching the child report.
if(props.report.parentReportID){
    Report.openReport(props.reportParentID)
}

```


### What alternative solutions did you explore? (Optional)
NA


## Result


https://github.com/Expensify/App/assets/59088937/289ad57e-952c-4b1b-a986-bee0b434b487

**Comment by adelekennedy** [comment] 2023-08-25 19:50
🐛

**Comment by imranaalam** [comment] 2023-08-26 04:34
**Problem Statement**: 
On the first visit after login, the app does not display the emoji reaction in the reply of the thread's main message. This is due to the fact that the emoji reactions are stored in the parent report. When a user logs out and logs back in, the app doesn't have this parent report data loaded until it's explicitly fetched.

**Proposed Solution**:
In the `App/src/pages/home/report/ReportActionsView.js`, add a condition that checks for the presence of a `parentReportID` for the thread's main message. If found, it opens the parent report to fetch its data:
```javascript
if(props.report.parentReportID){
    Report.openReport(props.reportParentID);
}
```

**Why this Solution Might Not Be Optimal**:
1. **Performance Overhead**: Fetching the entire parent report for one message's reactions can lead to a delay.
2. **Data Redundancy**: Loading some of the same data twice if a user navigates to the parent report afterward.
3. **User Experience**: A potential lag due to fetching an extensive parent report before accessing the desired thread.
4. **Network Costs**: Fetching entire reports for limited data can be costly, especially for users on constrained data plans.
5. **Complexity**: This approach can make the code harder to maintain due to added logic checks and unnecessary fetches.

**More Optimal Solution**:
1. **Backend Modification**: Modify the backend to return the necessary reaction data for the first message of a thread, even when querying just that child report.
2. **Lazy Load Reactions**: If a backend tweak isn't feasible, lazily load the reactions for the first message:
```javascript
useEffect(() => {
    if (props.report.parentReportID && !props.report.firstMessageReactionsLoaded) {
        Report.fetchReactionsForMessage(props.report.reportID, props.report.firstMessageID);
    }
}, []);
```
In the Report API handler:
```javascript
function fetchReactionsForMessage(reportID, messageID) {
    // Call to backend API to get reactions for a specific message by its ID and reportID
}
```
This solution fetches only the necessary reactions, making it efficient and modular, which allows for further optimizations and a better separation of concerns.

**Comment by imranaalam** [comment] 2023-08-26 04:50
> 📣 @imranaalam! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: imranaalam@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010d9646baeae737aa

**Comment by adelekennedy** [comment] 2023-08-28 15:55
pending proposal review from @burczu

**Comment by burczu** [comment] 2023-08-29 07:55
@adelekennedy I reviewed both proposals and tend to agree with @imranaalam and his Optimal Solution that this should be first updated on the backend side:

> Backend Modification: Modify the backend to return the necessary reaction data for the first message of a thread, even when querying just that child report.

If we agree, I think we should change it to `Internal`. What do you think?

**Comment by adelekennedy** [comment] 2023-08-31 19:30
moved to internal

**Comment by adelekennedy** [comment] 2023-09-04 22:32
@francoisl can you make the backend update suggested [here](https://github.com/Expensify/App/issues/25902#issuecomment-1696951146) or should we deprioritize for now?

**Comment by francoisl** [comment] 2023-09-06 01:03
Yeah, finished the fix - just need to update tests for it. The internal PR should be ready for review tomorrow.

**Comment by burczu** [comment] 2023-09-06 13:06
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by francoisl** [comment] 2023-09-13 19:08
Backend fix was deployed to production yesterday. @adelekennedy I think we'll need to compensate for reporting the issue?

**Comment by adelekennedy** [comment] 2023-09-14 02:18
I think reporting and C+?

**Comment by adelekennedy** [comment] 2023-09-21 11:09
**Payouts due:**

Issue Reporter: $250 @dhanashree-sawant Upwork
Contributor+: $1000 @burczu Upwork

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~0184d2ee9438cd3144).

**Comment by burczu** [comment] 2023-09-21 11:10
@adelekennedy I'm not eligible for payment here - I'm a contractor from Callstack.

**Comment by dhanashree-sawant** [comment] 2023-09-22 05:44
Thanks @adelekennedy, I have accepted the offer.

**Comment by imranaalam** [comment] 2023-09-22 10:13
**Report on Transitioning Expensify Issue from External to Internal: Consideration for Partial Compensation to Community Contributors**

**Introduction**:
The transition of an issue from an external to an internal status in Expensify raises concerns about community engagement and motivation. While it is acknowledged that moving an issue internally may be necessary for various reasons, this report explores the potential benefits of providing partial compensation to the community members who initially contributed to the issue. This approach aims to maintain community morale and incentivize future contributions.

**Background**:
Expensify is a platform where users and community members actively engage in issue reporting and problem-solving. In some cases, issues initially opened to the external community may be reclassified as internal, limiting the visibility to external contributors.

**Benefits of Transitioning to Internal**:
Transitioning an issue to an internal status can be beneficial for several reasons:
1. **Focused Problem Resolution**: It allows the internal team to concentrate on the issue without external distractions.
2. **Confidentiality**: Certain issues may involve sensitive information that needs to be protected.
3. **Streamlined Communication**: Internal discussions can be more efficient and tailored to the team's needs.
4. **Resource Allocation**: It enables better resource allocation for issue resolution.

**Challenges with Transitioning to Internal**:
While the decision to move an issue internally is often the right one, it poses some challenges:
1. **Community Disengagement**: External contributors may feel disheartened when their contributions are no longer visible or considered.
2. **Loss of Motivation**: The lack of recognition and engagement may discourage future community efforts.
3. **Reduced Collaboration**: Community members may hesitate to participate if they perceive a risk of their efforts being "lost."

**Proposed Approach**:
To mitigate the challenges mentioned above, we propose considering partial compensation for community contributors when an issue transitions from external to internal. This approach can offer several advantages:
1. **Recognition and Incentive**: Providing partial compensation acknowledges the efforts of the community contributors and incentivizes future participation.
2. **Positive Community Relations**: It fosters goodwill and maintains a positive relationship with the community.
3. **Enhanced Future Contributions**: The prospect of compensation can motivate community members to continue contributing valuable insights and reports.
4. **Retaining Community Trust**: Compensation demonstrates that their contributions are valued, even if not immediately actionable.

**Implementation Details**:
Implementing this approach requires defining criteria for compensation, such as the significance of the issue, the quality of the report, or the level of community involvement. Compensation can be in the form of credits, recognition, or other tangible benefits.

**Conclusion**:
Transitioning an issue from external to internal is sometimes necessary for efficient resolution, but it should not come at the cost of community engagement and motivation. Offering partial compensation to community contributors is a proactive approach that recognizes their efforts, fosters goodwill, and encourages ongoing participation. This approach not only benefits the community but also contributes to maintaining a positive image and strong relations between Expensify and its dedicated user base.

**Comment by imranaalam** [comment] 2023-09-22 10:22
**Proposal for a Survey to Address the Bug Policy Issue**

**Introduction**:
The identification of a bug in our current policy, which may potentially result in a slower pace of bug fixing, is a matter of significant concern. To comprehensively assess the validity of this issue and explore potential solutions, we propose conducting a survey. This survey aims to gather insights from contributors and users to determine if the policy needs adjustments and, if so, how to address it effectively.

**Survey Objectives**:
The primary objectives of this survey are as follows:
1. **Validate the Issue**: Confirm whether there is a genuine concern regarding the bug policy impacting bug-fixing efficiency.
2. **Identify Specific Concerns**: Understand the specific aspects of the policy that contributors and users find problematic.
3. **Gauge Community Feedback**: Collect feedback from the community, including contributors and users, to ensure their voices are heard.
4. **Propose Solutions**: Based on the survey results, propose effective solutions or adjustments to the policy that address the identified concerns.

**Survey Structure**:
The survey will consist of a series of questions designed to achieve the objectives mentioned above. The questions will cover topics such as:
- Participants' experience with the bug policy.
- Instances where bug fixing was delayed or impacted by the policy.
- Suggestions for policy improvements.
- Open-ended questions for additional comments and feedback.

**Survey Distribution**:
The survey will be distributed among the following groups:
1. **Contributors**: Individuals who actively report bugs and contribute to issue resolution.
2. **Users**: Individuals who use our product but may not necessarily contribute to issue reporting.
3. **Bloggers and Community Members**: Those who have publicly expressed concerns about the bug policy.

**Survey Analysis**:
Upon collecting survey responses, the data will be thoroughly analyzed to identify common themes, concerns, and potential solutions. This analysis will serve as the basis for further action.

**Follow-Up Actions**:
Based on the survey findings, the following actions can be taken:
1. **Policy Adjustments**: If the survey confirms issues with the bug policy, consider making specific adjustments to address the concerns.
2. **Communication**: Communicate the survey results and any proposed policy changes to the community.
3. **Feedback Loop**: Establish a feedback loop to continuously gather input from contributors and users to ensure ongoing policy improvements.

**Conclusion**:
Conducting a survey to address the bug policy issue is a proactive step toward ensuring the efficiency of our bug-fixing process and maintaining a positive relationship with our community. By involving contributors, users, and concerned bloggers, we can collectively work towards a solution that benefits all stakeholders and improves the overall bug-fixing experience.

**Comment by imranaalam** [comment] 2023-09-22 10:24
**Bug Policy Feedback Survey**

---

**Introduction:**
Thank you for taking the time to participate in this survey. Your feedback is crucial in helping us assess our current bug policy and make necessary improvements. Please answer the questions honestly and provide as much detail as possible.

---

**Demographics (Optional):**
1. What is your age range?
   - [ ] Under 18
   - [ ] 18-24
   - [ ] 25-34
   - [ ] 35-44
   - [ ] 45-54
   - [ ] 55+

2. How do you primarily engage with our platform?
   - [ ] Contributor (actively report bugs)
   - [ ] User (use the product without active contribution)
   - [ ] Blogger or community member (publicly discuss the platform)

---

**Bug Policy Experience:**

3. On a scale of 1-10, how familiar are you with our current bug policy? (1 being not familiar at all, 10 being extremely familiar)
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] ...
   - [ ] 10

4. Have you ever felt that our bug policy affected the pace of bug fixing?
   - [ ] Yes
   - [ ] No
   - [ ] Unsure

   If yes, please describe the situation:

   [Text box for detailed answer]

5. Have you encountered instances where bugs remained open or unresolved due to the current policy?
   - [ ] Yes
   - [ ] No
   - [ ] Unsure

   If yes, please provide specific examples:

   [Text box for detailed answer]

---

**Suggestions and Feedback:**

6. What aspects of the current bug policy do you believe need improvement or modification?
   
   [Text box for detailed answer]

7. If you could suggest one major change to the bug policy, what would it be?

   [Text box for detailed answer]

8. Are there any other policies or practices you believe contribute to delays in bug fixing?

   [Text box for detailed answer]

---

**Additional Comments:**

9. Please provide any additional feedback, comments, or concerns you have regarding our bug policy or any other related topic.

   [Text box for detailed answer]

---

**Closure:**
Thank you for your valuable feedback! We are committed to improving our processes and ensuring a better experience for all stakeholders.

---

[SUBMIT BUTTON]

---

**Comment by imranaalam** [comment] 2023-09-22 10:31
graph TD
    A[Issue Transitioned from External to Internal] --> B[Community Disengagement]
    B --> C[Loss of Motivation]
    C --> D[Reduced Collaboration]
    D --> E[Decreased Issue Reporting & Problem Solving]
    E --> F[Less Efficient Resolution]
    F --> A

**Comment by francoisl** [comment] 2023-10-04 22:25
@dhanashree-sawant did you receive the payment for this? @adelekennedy is OOO this week, but if you received it then I think we can close this.

**Comment by dhanashree-sawant** [comment] 2023-10-05 05:39
Hi @francoisl, yes I have received the payment, we can close this

**Closed** 2023-10-05 18:13 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
