### ISSUE TITLE
[HOLD for payment][$250] - LHN preview is missing distance rate name in distance rate removal system message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46967] opened 2024-08-07 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4827991
**Email or phone of affected tester (no customers):**  applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Workspace has some distance rates
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Delete a distance rate
4. Go to #admins room of the same workspace
5. Refresh the page

## Expected Result:
The LHN preview will display the complete distance rate removal system message

## Actual Result:
The LHN preview is missing the name of the removed distance rate in the system message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/02c7414b-77e1-4a1a-9b7e-bce0b636b452

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016424eee2de4a22ba</li>
        <li>Upwork Job ID: 1821384517474279929</li>
        <li>Last Price Increase: 2024-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 103698148</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-08-07 13:15
We think that this bug might be related to #wave-collect - Release 1

**Comment by FitseTLT** [comment] 2024-08-07 19:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN preview is missing distance rate name in distance rate removal system message

### What is the root cause of that problem?
We are not dealing with `POLICY_CHANGE_LOG.DELETE_CUSTOM_UNIT` action types when getting `alternateText` for the LHN so it is falling back to setting it to the lastMessage of the report which misses distance rate name 
### What changes do you think we should make in order to solve the problem?

We need to return the getReportActionMessageText of the lastAction if the last action type is `POLICY_CHANGE_LOG.DELETE_CUSTOM_UNIT` (FYI: That is how the report action is displayed in report action item) [here](https://github.com/Expensify/App/blob/b806725c60547ac3e71470670cf34a0de107000b/src/libs/SidebarUtils.ts#L426-L428)
```
else if (lastAction?.actionName === CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG.DELETE_CUSTOM_UNIT) {
            result.alternateText = ReportActionsUtils.getReportActionMessageText(lastAction) ?? '';
        } 
```
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-08-09 17:52
@lanitochka17 @kadiealexander Can you try reproducing the bug. I was able to do that yesterday but not anymore

**Comment by trjExpensify** [comment] 2024-08-09 21:14
CC: @neil-marcellini who's working on this project externally with context to help squash these? I think this one is conditional on the p2p beta for `rate`, so #vip-vsb related.

**Comment by kadiealexander** [comment] 2024-08-23 08:01
@allroundexperts please take a look at the proposal above!

**Comment by lanitochka17** [comment] 2024-08-23 12:31
Issue is still reproducible  

https://github.com/user-attachments/assets/59a7b738-23e3-444e-88d9-93b73e8eddba

**Comment by allroundexperts** [comment] 2024-08-25 23:18
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/46967#issuecomment-2274211129) works good. I think the solution proposed is making sense as well. Let's go with them.

🎀 👀 🎀 C+ reviewed

**Comment by neil-marcellini** [comment] 2024-09-04 21:52
I'm now realizing that this is related to distance rate configuration alone, not the P2P distance project.

**Comment by allroundexperts** [comment] 2024-09-24 18:14
I think this is pending payment. Can someone please take a look?

**Comment by Julesssss** [comment] 2024-09-25 08:07
HI @kadiealexander would you mind checking that payment hasn't occurred yet? Thanks

**Comment by FitseTLT** [comment] 2024-10-03 12:05
@kadiealexander Payment overdue

**Comment by FitseTLT** [comment] 2024-10-11 17:48
@kadiealexander Can you pls issue payment here?? Thx

**Comment by kadiealexander** [comment] 2024-10-13 22:16
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@allroundexperts] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@allroundexperts] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@allroundexperts] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@allroundexperts] Determine if we should create a regression test for this bug.
- [ ] [@allroundexperts] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-13 22:20
Payouts due:

- [ ] Contributor: $250 @FitseTLT ([Offer link](https://www.upwork.com/nx/wm/offer/103698148))
- [ ] Reviewer: $250 @allroundexperts

Upwork job is [here](https://www.upwork.com/jobs/~016424eee2de4a22ba).

**Comment by JmillsExpensify** [comment] 2024-10-14 21:57
$250 approved for @allroundexperts

**Closed** 2024-10-22 09:33 UTC
Labels: Reviewing, External, Daily, Bug
