### ISSUE TITLE
IOUBadge displayed with 0.00 total for any chat with an associated iouReport that has a total of 0

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12115] opened 2022-10-25 11:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Refresh the page
4. Cancelled all unpaid money requests
5. Refresh the page

## Expected Result:
LHN now shows many red and green bars next to new chats at top for amounts owed to me and others

## Actual Result:
IOU icons should not be displayed for canceled money requests

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.2.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/197763821-12787201-16cc-4923-b372-40b3035b32df.mp4

![2510](https://user-images.githubusercontent.com/93399543/197763824-5c98eccc-646c-4aa7-bc2a-fe359995c7d3.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-10-25 11:42
Trying to get this auth PR merged to fix this hopefully https://github.com/Expensify/Auth/pull/7095

**Comment by Julesssss** [comment] 2022-10-25 11:44
This is an internal issue. 

Thankfully I have a PR in review which was improving this logic, and will resolve the issue. Preventing the need for a revert.

**Comment by Julesssss** [comment] 2022-10-25 12:18
Until the last Web-E deploy, [this issue](https://github.com/Expensify/Expensify/issues/229735) existed on staging. A fix for that issue uncovered this bug. 

The problem is that `getActiveIOUReport` retrieves IOUReports with a total of 0. This occurs when an iouReport is opened, but then all ious are rejected or canceled. This Auth PR introduces a change where the iouReportID is only returned from GetChats if the iouReport has a non-zero total. We then set the iouReportID as a param on the chatReport. 

In addition, this [Web-E PR](https://github.com/Expensify/Web-Expensify/pull/35144/files) will complete the fix, by linking and returning iouReports in our API commands ONLY if the iouReportID is included.

**Comment by mountiny** [comment] 2022-10-25 13:12
Auth PR here https://github.com/Expensify/Auth/pull/7095

**Comment by Julesssss** [comment] 2022-10-25 14:31
Hey @Justicea83 @cead22, please take another look when you have a moment, as this PR now resolves a Web-E and App[ deploy blocker](https://github.com/Expensify/App/issues/12115).

**Comment by Julesssss** [comment] 2022-10-25 14:59
[Auth PR](https://github.com/Expensify/Auth/pull/7095) has been approved, now we're just awaiting @cead22's review as he previously added some comments which were resolved.

**Comment by Julesssss** [comment] 2022-10-26 10:20
This was merged, but awaiting Auth deployment. Adding a note to the deploy checklist that it should be unblocked soon.

**Comment by roryabraham** [comment] 2022-10-26 14:05
As discussed in [slack](https://expensify.slack.com/archives/C07J32337/p1666702384758809) I'm going to investigate a front-end solution for this too. While the Auth solution was the root cause, the front-end should know not to display $0-IOUs.

**Comment by Julesssss** [comment] 2022-10-26 16:15
Fixed, removing this blocker from the deploy checklist.

**Closed by Julesssss** 2022-10-26 16:16 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Improvement, Hourly
