### ISSUE TITLE
[HOLD for payment 2023-06-29] [$1000] Feature: Improve the Task Preview UI

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20535] opened 2023-06-09 17:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with account
3. Create a task with an assignee

## Expected Result:
1. Anchor the checkbox to the top
2. The checkbox outline should be updated

Desired:
<img width="334" alt="Screenshot 2023-06-14 at 3 40 20 PM" src="https://github.com/Expensify/App/assets/30609178/8924d742-6cac-42da-bc43-a3b6cb2e6652">

## Actual Result:
Clicking mentions in the Task opens user details

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (61)](https://github.com/Expensify/App/assets/93399543/9b24a783-1ab5-4fa8-bfda-9da79d5323c2)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @parasharrajat

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1686292351956649

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a05776980db2f044</li>
        <li>Upwork Job ID: 1667239039660699648</li>
        <li>Last Price Increase: 2023-06-09</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-06-09 18:06
Going to take this one if ya'll don't mind. Was involved in the related convo.

**Comment by Nikhil-Vats** [comment] 2023-06-09 18:25
@JmillsExpensify I was also involved in this convo. Are you planning to open it for external contributors? Can I add a proposal? Apologies, if this is supposed to be internal.

**Comment by thienlnam** [comment] 2023-06-09 18:49
I think for tasks specifically, but @shawnborton should we use the updated checkbox through the entire app?

**Comment by rayane-djouah** [comment] 2023-06-09 19:01
I would love to take this

**Comment by Nikhil-Vats** [comment] 2023-06-09 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Improve the UI of TaskPreview

### What is the root cause of that problem?
No root cause, this is not a bug.

### What changes do you think we should make in order to solve the problem?

We should make the following changes in `checkboxContainer` -
https://github.com/Expensify/App/blob/94e00696d2f7ddb529451dc715b5a510f4e3f3f8/src/styles/styles.js#L2455-L2464

1. Change `borderColor` of `checkboxContainer` in styles to `borderLighter` (`#2B5548`).
2. Change `borderRadius` from `2` to `4`.
3. Change `borderWidth` from `1` to `2`.
4. Change the layout for `TaskPreview` along with adding margin for checkbox -
```javascript
<View style={[styles.flex1, styles.flexRow, styles.alignItemsStart]}> // first column for checkbox aligned at start/top
    <Checkbox
        style={[styles.mr2, styles.mt2]} // add some top margin
        containerStyle={[styles.taskCheckbox]}
        isChecked={isTaskCompleted}
        disabled={TaskUtils.isTaskCanceled(props.taskReport)}
        onPress={() => {
            if (isTaskCompleted) {
                TaskUtils.reopenTask(props.taskReportID, taskTitle);
            } else {
                TaskUtils.completeTask(props.taskReportID, taskTitle);
            }
        }}
    />
    <View style={[styles.flex1, styles.flexColumn, styles.alignItemsStart]}> // second column with 2 rows - title, assignee
        <RenderHTML html={htmlForTaskTitle} />
        {!_.isEmpty(htmlForTaskAssignee) && <RenderHTML html={htmlForTaskAssignee} />}
    </View>
</View>
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-06-09 20:13
@shawnborton I was using mt1 (4px) because that's the lowest value for margin but the TaskPreview component matches the screenshot in the expected result **when I use `2px` as `marginTop`**. 

I am using the margin for aligning the checkbox with task title as task title has `line-height: 20px` due to which it has some space at the top and bottom. What's the best way to handle this?
1. Using a `2px` margin or,
2. Reducing `line-height` or,
3. Something else?

**Comment by shawnborton** [comment] 2023-06-12 06:57
Personally I would love it if we had a global, custom checkbox component across the entire app.

**Comment by thienlnam** [comment] 2023-06-12 16:37
Agreed, holding until we figure out where mention should go.
Created by and Assignee looking smaller will be handled in this PR https://github.com/Expensify/App/issues/19330

**Comment by thienlnam** [comment] 2023-06-14 22:40
We landed on keeping the task assignee in the same location. This is ready to go now

**Comment by Nikhil-Vats** [comment] 2023-06-15 04:01
@thienlnam @JmillsExpensify @narefyev91 

[Proposal updated.](https://github.com/Expensify/App/issues/20535#issuecomment-1585021608)

**Comment by narefyev91** [comment] 2023-06-15 10:55
@Nikhil-Vats looks good to me - the only concern - we need to decide - if that styling should be unique inside the whole app for checkbox - or it should be custom one

**Comment by Nikhil-Vats** [comment] 2023-06-15 11:51
@shawnborton [said above](https://github.com/Expensify/App/issues/20535#issuecomment-1586698059) -
> Personally I would love it if we had a global, custom checkbox component across the entire app.

But I would also like to clarify -
Right now, the default styles are in `checkboxContainer` in [styles.js](https://github.com/Expensify/App/blob/94e00696d2f7ddb529451dc715b5a510f4e3f3f8/src/styles/styles.js#L2455-L2464) -
1. Do we just change them so that we use the new checkbox with green outline everywhere and remove the default styling altogether?
2. Do we make a new styles object for the new checkbox with green outline and in the [Checkbox component](https://github.com/Expensify/App/blob/94e00696d2f7ddb529451dc715b5a510f4e3f3f8/src/components/Checkbox.js#L93C4-L95) we can use default/new styles based on an optional prop? (Default will be the new styles with green outline)

**Comment by narefyev91** [comment] 2023-06-15 13:28
@Nikhil-Vats based on the slack discussion - we should apply this new styles only for squared checkboxes

**Comment by Nikhil-Vats** [comment] 2023-06-28 14:50
Hey @thienlnam @narefyev91 I wanted to know if this issue was eligible for urgency bonus since it was merged in a few hours over 3 days and there was some delay due to discussions on the UI of checkbox in focus state which was not a part of the issue description and was discovered during PR review.

<img width="556" alt="Screenshot 2023-06-28 at 8 05 02 PM" src="https://github.com/Expensify/App/assets/31413407/d9c6f644-04f2-4e18-8c49-5ed605d2bf01">

<img width="630" alt="Screenshot 2023-06-28 at 8 04 17 PM" src="https://github.com/Expensify/App/assets/31413407/7433cb82-495d-4717-889b-c7f5ea81c94d">

17th and 18th were weekend days.

**Comment by thienlnam** [comment] 2023-07-03 19:23
I'd say so, though @JmillsExpensify is BZ on this issue so will defer to him

**Comment by thienlnam** [comment] 2023-07-06 00:24
We've pending payments here

**Comment by thienlnam** [comment] 2023-07-10 21:14
Bump @JmillsExpensify on payouts here

**Comment by Nikhil-Vats** [comment] 2023-07-14 18:32
Hey @JmillsExpensify 👋, is this issue eligible for urgency bonus? Timeline details here - https://github.com/Expensify/App/issues/20535#issuecomment-1611589718

**Comment by Nikhil-Vats** [comment] 2023-07-15 13:14
I agree the complexity was simple @parasharrajat but the delay was because we found another small detail (checkbox outline) that we wanted to fix and still the PR was approved within 3 days by @narefyev91 and only 2-3 hours over 3 days by @thienlnam . And @thienlnam also agreed that it is eligible for urgency bonus.

Anyway, whatever @JmillsExpensify thinks is fair is okay for me.

**Comment by JmillsExpensify** [comment] 2023-07-19 13:48
Upwork job is here: https://www.upwork.com/jobs/~0142f871715d9bb1b2. Please let me know when you've applied. 

Thanks @parasharrajat for letting me know you'll be handled separately.

**Comment by Nikhil-Vats** [comment] 2023-07-19 13:55
@JmillsExpensify done. Thanks. :)

**Comment by anmurali** [comment] 2023-07-21 16:08
Yup, I fixed it. I got the links mixed up. I will remove the 1500 comment to avoid confusion.

**Comment by JmillsExpensify** [comment] 2023-07-24 13:19
Went ahead and extended the Upwork offer to @Nikhil-Vats. I'll pay the bonus when issuing payment and closing out the contract.

**Comment by JmillsExpensify** [comment] 2023-07-24 21:48
All paid out! Thank you. 🙌🏼

**Closed by JmillsExpensify** 2023-07-24 21:48 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
