### ISSUE TITLE
[HOLD #37281][$1000] Onyx data does not get removed cleanly on sign out

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34473] opened 2024-01-13 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction ( Don't have account with several hundreds of chats)
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705012041676559

## Action Performed:
1. Signed into an account with many many chats
2. Signed out
3. Signed in with a brand new account (which should have only the Concierge chat)

## Expected Result: 
Nothing from the account that I signed out from should be persisted in the client data whatsoever.

## Actual Result: 
Tons of chats from the first account show up in the second account. A ton of Onyx keys still have values of `{hasDraft: false}` and there are also straight up reports that shouldn't be there at all. These also show up in the LHN.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![2024-01-11_12-21-12](https://github.com/Expensify/App/assets/38435837/554c3965-27ce-44a3-9e56-8626e333607e)
![2024-01-11_12-22-20](https://github.com/Expensify/App/assets/38435837/c986823d-a4c3-42aa-b9ed-c964c8e5c3fe)

![2024-01-11_12-19-23](https://github.com/Expensify/App/assets/38435837/f555b0d8-5a21-45dd-8111-e0845fd183cd)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01211aa8ecc46d7a5e</li>
        <li>Upwork Job ID: 1759703332875366400</li>
        <li>Last Price Increase: 2024-03-24</li>
    </ul>
</details>

**Comment by anmurali** [comment] 2024-01-16 19:56
I cannot reproduce
<img width="1468" alt="image" src="https://github.com/Expensify/App/assets/14225673/4b0d30a1-8e0f-4290-b5e1-138a12b53a2a">
The two reports I see are Concierge DM and domain room, and the new account has both. 

@marcaaron can you test this again and reopen if you still run into it?

**Comment by marcaaron** [comment] 2024-01-17 00:43
It seems dependent on how much data you have in the first account when signing out. If you have a lot - not all of it gets cleared.

We can close it - but feels like there is some obvious reason why this is happening and it should be patched at some point. Switching from one account to another is not such a common thing though so we can deprioritize it for now (but it is still happening for me).

![2024-01-16_14-41-03](https://github.com/Expensify/App/assets/32969087/d660320e-745e-4201-bd99-d4714ce86fe6)

**Comment by mallenexpensify** [comment] 2024-02-19 22:16
Experiencing what I believe is the same bug 
https://expensify.slack.com/archives/C049HHMV9SM/p1708356217921739

I put the below on hold
- https://github.com/Expensify/App/issues/36804  

@thesahindia can you see if you're able to reproduce?  thx

**Comment by mallenexpensify** [comment] 2024-03-02 00:48
@s77rt do you think is related?
https://github.com/Expensify/App/pull/37401#issuecomment-1972148693

Can you also attempt reproduction?  Thx

**Comment by s77rt** [comment] 2024-03-02 01:14
@mallenexpensify No I don't think that PR is related.

> Can you also attempt reproduction?

I'm able to reproduce this. On logout still seeing leftover reports

<img width="695" alt="Screenshot 2024-03-02 at 2 13 12 AM" src="https://github.com/Expensify/App/assets/16493223/5ec444ef-42fd-494a-aa38-3e9546318f02">

**Comment by mallenexpensify** [comment] 2024-03-03 23:55
Thanks @s77rt , I commented in the #vip-vsb room, I think it should be part of that project
https://expensify.slack.com/archives/C066HJM2CAZ/p1709510064411879

Do you happen to know of any agencies that might be working on this @s77rt or @marcaaron ?  If so, I can post in their Slack room.

**Comment by s77rt** [comment] 2024-03-04 11:28
It seems like the onyx data is removed correctly but then another process sets the data. I'm seeing `removeItems` call first and then it's followed by a bunch of `multiSets` 


https://github.com/Expensify/App/assets/16493223/8cdf211b-c7c3-4005-92f6-887ce478afc5

**Comment by mallenexpensify** [comment] 2024-03-04 19:31
From David in #vip-vsb 
> I don't know which agency is working on that but it definitely sounds like a bug.  I feel like we've had variations of this bug before; I don't know why we don't blow everything in Onyx, we retain some information and it keeps causing this bug to reappear.

@s77rt , do you think this can be worked on externally? I see you're able to gather a bunch of the Onyx details, not sure if the fix is backend though.

**Comment by s77rt** [comment] 2024-03-04 21:28
@mallenexpensify Yes, this looks `External` to me

**Comment by mallenexpensify** [comment] 2024-03-05 01:39
Thanks @s77rt , I updated to `External` and removed `Needs Reproduction` because you were able to reproduce above.

**Comment by s77rt** [comment] 2024-03-05 17:00
@tienifr I think getting ride of that dependency is the optimal solution but I'm not sure if this is possible. Your suggested solution would work but it does not address the root cause and the bug could resurface if we delete both policies and reports in any other way (besides logout). Let's keep that as last resort option.

**Comment by s77rt** [comment] 2024-03-06 13:06
@tienifr 

> Onyx.connect again inside the policy callback to get the value

That's a good solution in terms that it addresses the root cause. But doing Onyx.connect that way is like doing Onyx.get which is discouraged.

**Comment by s77rt** [comment] 2024-03-06 23:26
@tienifr Unfortunately your solution is a workaround. If we delete both the policies and the reports in any other process besides logging out e.g. server response, then the bug would be still reproducible.

**Comment by s77rt** [comment] 2024-03-07 20:44
@tienifr I have raised a Slack discussion https://expensify.slack.com/archives/C01GTK53T8Q/p1709843924926719

**Comment by mallenexpensify** [comment] 2024-03-10 22:28
Thanks @s77rt , thanks for raising the convo in #expensify-open-source, thanks @tienifr for chiming in too. 

It looks like ended up with
> Cool, then the `Onyx.getFromCache` approach looks promising. Should we move ahead with that? 

and, from Rory
> I think we'd need a broader conversation with a P/S before opening a PR

Since this issue's been open a while, it's important to fix and it's proving to require some work, I raised the price to $1000. 

@tienifr can you raise a P/S for @s77rt to review then bring it to the Slack convo for feedback from Rory? It might be best to comment in that thread and share with the room to ensure bonus 👀 too.

**Comment by hayes102** [comment] 2024-03-10 22:31
is this still open for proposals from others, @mallenexpensify ?

**Comment by mallenexpensify** [comment] 2024-03-10 22:33
Yes @hayes102 , please keep in mind this [from our CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Note%3A%20Before%20submitting%20a%20proposal%20on%20an%20issue%2C%20be%20sure%20to%20read%20any%20other%20existing%20proposals.%20ALL%20NEW%20PROPOSALS%20MUST%20BE%20DIFFERENT%20FROM%20EXISTING%20PROPOSALS.%20The%20difference%20should%20be%20important%2C%20meaningful%20or%20considerable.)
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

**Comment by mstindia-com** [comment] 2024-03-11 06:14
Contributor details
Your Expensify account email: test@mstindia.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d37fe96dfcf61856

**Comment by s77rt** [comment] 2024-03-11 13:54
@tienifr Can you please post that on the slack thread and share with the room?

**Comment by roryabraham** [comment] 2024-03-11 17:19
Thanks @tienifr, great writeup! I hope you don't mind - I went over your proposal and made some minor grammatical edits. Agree with @s77rt that you should post it in #expensify-open-source, and I look forward to hearing what people think.

**Comment by waseemAnsari11011** [comment] 2024-03-13 11:28
**Please re-state the problem that we are trying to solve in this issue.**


Our current system faces two primary issues:

1. **Unpredictable Assignment of Draft Status:** Upon logging out, the `{hasDraft: false}` status is inconsistently assigned to Policy-related reports. This inconsistency results in reports sometimes being marked as `{hasDraft: false}`, while at other times, they are not.

2. **Persistence of Previous Account Data:** When logging into a different account, the system retains and displays chats from the previous account.


**What is the root cause of that problem?**

1. **Unpredictable Assignment of Draft Status:**  

a. Sometimes it gets assigned because we are getting policy-related reports as it is not yet cleared from the storage.

b.  Sometimes it doesn’t get assigned because we are not getting policy-related reports as it has already got cleared away from the storage because of `onyx.clear()`.


2. **Persistence of Previous Account Data:** 

When logging into a different account the reports from the previous account are not cleared away that is why we are seeing chats(previous account’s persisted reports) from previous account.


**What changes do you think we should make in order to solve the problem?**

1. **Addressing Unpredictable Draft Status Assignment:** To ensure consistency in the assignment of draft status to Policy-related reports, I propose instructing Onyx to preserve these reports upon logout using `Onyx.clear(keysToPreserve)`. By explicitly specifying which keys to preserve, we can prevent the inadvertent clearing of these reports from storage.

2. **Resolving Persistence of Previous Account Data:** To mitigate the persistence of data from previous accounts, I propose **storing the email** of the user upon logout in the session. This stored information will then be utilized to clear all persisted data associated with the previous account when a new user login. This approach ensures that no remnants of the previous account's data are retained, maintaining user privacy and system integrity.

**Comment by waseemAnsari11011** [comment] 2024-03-13 11:30
Contributor details
Your Expensify account email: waseemahm11011@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01be39f3f2dc0050c2?mp_source=share

**Comment by waseemAnsari11011** [comment] 2024-03-13 11:37
Contributor details
Your Expensify account email: waseemahm11011+123@gmail.com
Upwork Profile Link: https://www.upwork.com/fl/~01be39f3f2dc0050c2?mp_source=share

**Comment by waseemAnsari11011** [comment] 2024-03-13 11:38
Contributor details
Your Expensify account email: waseemahm11011+123@gmail.com
Upwork Profile Link: [<REPLACE LINK HERE>](https://www.upwork.com/fl/~01be39f3f2dc0050c2?mp_source=share)

**Comment by s77rt** [comment] 2024-03-13 13:10
@waseemAnsari11011 Thanks for the proposal. Regarding your RCA
> When logging into a different account the reports from the previous account are not cleared away that is why we are seeing chats(previous account’s persisted reports) from previous account

Can you specify why they are not cleared? Isn't this related to the first problem or do they have different root causes?

**Comment by waseemAnsari11011** [comment] 2024-03-13 13:44
Hi @s77rt , i trust this message finds you well.

Correct me if i me wrong.

No the root cause isn't the same. 

The first scenerio is where we need to store the reports with hasDraft value in local storage for the **same** user. 

The second scenario is where **different** user is login & we don't need to store previous user's data.

**Comment by s77rt** [comment] 2024-03-13 14:18
@waseemAnsari11011 We don't want to store the reports on logout in any case

**Comment by s77rt** [comment] 2024-03-13 20:52
@waseemAnsari11011 That's not intended. That's actually the bug.

**Comment by waseemAnsari11011** [comment] 2024-03-14 08:19
@s77rt I have some doubts can you please clarify.

Policy can be deleted in two ways 1. Logout 2. When some user deletes it manually.

When policy is deleted on logout then we need to clear all policies & reports from local storage  & that's it.

When a policy is deleted manually in that case we have to need to archive reports with hasDraft set to false using BE then clear all policies & reports from local storage.

Is that what we intend to do?

**Comment by s77rt** [comment] 2024-03-14 14:08
@waseemAnsari11011 

> When policy is deleted on logout then we need to clear all policies & reports from local storage & that's it.

Kinda, on logout we need to clear all policies & reports from local storage & that's it.

> When a policy is deleted manually in that case we have to need to archive reports with hasDraft set to false using BE then clear all policies & reports from local storage.

No, when a policy is deleted we have to archive reports and set hasDraft to false & that's it.

**Comment by waseemAnsari11011** [comment] 2024-03-15 04:23
@s77rt 
Can we do something like this where we can a add a conditional check inside policy callback to check whether this policy is deleted manually or deleted because of logout.

In case when the policy is deleted manually, we can allow for unsetting the draft indicator.

In case of logout we will not allow this to happen.

We can do something like this
```
let islogout: boolean = false
Onyx.connect({
    key: ONYXKEYS.IS_LOGOUT,
    callback: (value) => {
        if (value !== null) {
            islogout = value;
        }
    }
});
```

```
const allPolicies: OnyxCollection<Policy> = {};
Onyx.connect({
    key: ONYXKEYS.COLLECTION.POLICY,
    callback: (val, key) => {
        if (!key) {
            return;
        }
        console.log(key, val)
        console.log("policy callback running")
        if (val === null || val === undefined && islogout === false) {
            console.log("draft false running")
            // If we are deleting a policy, we have to check every report linked to that policy
            // and unset the draft indicator (pencil icon) alongside removing any draft comments. Clearing these values will keep the newly archived chats from being displayed in the LHN.
                                  
        }
```

        allPolicies[key] = val;
    },
});

—-----------------
On Login we will set the isLogout value to false
On Logout we will set isLogout value to true before onyx.clear()

**Comment by s77rt** [comment] 2024-03-18 14:42
Still discussing in Slack

**Comment by mvtglobally** [comment] 2024-03-20 03:14
Issue not reproducible during KI retests. (First week)

**Comment by s77rt** [comment] 2024-03-21 02:13
No update. Still discussing in Slack

**Comment by s77rt** [comment] 2024-03-26 19:06
@shubham1206agra Thank you! Indeed that PR shall prevent this issue from happening. Let's put this one on hold

**Comment by mallenexpensify** [comment] 2024-03-26 23:58
Put on hold, removed `External` and `Help Wanted`, bumped to `Weekly`

**Comment by s77rt** [comment] 2024-04-05 21:50
https://github.com/Expensify/App/pull/37281 is merged. Issue not longer reproducible. Let's close this

**Comment by mallenexpensify** [comment] 2024-04-07 21:48
Throwing `retest-weekly` on this to confirm, then we can close.  thx!

**Comment by anmurali** [comment] 2024-04-17 01:59
@mallenexpensify any updates?

**Comment by mallenexpensify** [comment] 2024-04-18 20:28
Closing, just tried to repro with no luck
<img width="905" alt="image" src="https://github.com/Expensify/App/assets/22508304/36f320b9-6285-4f21-88c1-9f84c39845cd">

**Closed by mallenexpensify** 2024-04-18 20:28 UTC
Labels: Weekly, Bug, retest-weekly
