### ISSUE TITLE
[$500] Search - No loading animation when pasting text for first time

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34516] opened 2024-01-15 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and login with any user
2. Copy any text to clipboard
3. Open search
4. Paste the text in search and observe that no loading animation is displayed

## Expected Result:
App should display loading animation on pasting text in search

## Actual Result:
App does not display loading animation on pasting text in search when search box is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/49a621bd-7cda-4b46-9ae9-53d39c642ae8

https://github.com/Expensify/App/assets/78819774/d74534dc-aecb-43b2-b99f-e73957c5e341

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fb5965c49371271</li>
        <li>Upwork Job ID: 1746942114537074688</li>
        <li>Last Price Increase: 2024-01-15</li>
<li>Automatic offers: </li>
<ul>
<li>namhihi237 | Contributor | 28109839</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Gonals</details>

**Comment by namhihi237** [comment] 2024-01-15 17:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app should display a loading animation on pasting text in the search
### What is the root cause of that problem?
We use search as the state when passing it here:
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L135-L137

But initially, the value is empty so when pasted, `searchValue` still has an empty value so the loading is not displayed.
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/libs/actions/Report.ts#L2563-L2567
### What changes do you think we should make in order to solve the problem?
We should pass in using `value` instead of `searchValue`.
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L135-L136

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Pujan92** [comment] 2024-01-15 17:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On first text change the search loader isn't displayed 

### What is the root cause of that problem?
In this [PR commit](https://github.com/Expensify/App/commit/e3e75a00e4cf0a6323156af29482ef7577634655#diff-2c1ba6f0659c1c37d11e0067a493fd0ab18905105d151d4c35633e72203b55a5R143-R145) while merging it seems the conflict isn't resolved correctly. Due to that instead of `value` it is passing `searchValue`.
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L135-L138
cc: @TMisiukiewicz 

### What changes do you think we should make in order to solve the problem?
Correct the passed variable with `value` instead `searchValue`.

**Comment by miguelesco** [comment] 2024-01-15 17:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app should display a loading animation on pasting text in the search

### What is the root cause of that problem?
It is sending the value of the search before it get save in the state
### What changes do you think we should make in order to solve the problem?
I will change 
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L135C4-L138C7
to: 
` const onChangeText = (value = '') => {
        setSearchValue(value);
    };`

and: 
https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L81C5-L90C23

to: 
`useEffect(() => {
        if (!isMounted.current) {
            isMounted.current = true;
            return;
        }
        Report.searchInServer(searchValue);
        updateOptions();
    }, [searchValue]);`

in this way when the state is properly updated the search is made

### What alternative solutions did you explore? (Optional)
N/A

**Comment by miguelesco** [comment] 2024-01-15 17:56
Contributor details
Your Expensify account email: miguelangelescorche@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01751af6e9f5d7c8a2

**Comment by abzokhattab** [comment] 2024-01-15 18:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search - No loading animation when pasting text for first time


### What is the root cause of that problem?
instead of `value` we pass `searchValue`.

 [App/src/pages/SearchPage.js](https://github.com/Expensify/App/blob/a4e3ae2546882b0971ed80e6ce0fd4c6b85cf956/src/pages/SearchPage.js#L135-L137)

### What changes do you think we should make in order to solve the problem?

- in selectedProposal: Right now, `onChangeText` updates searchValue and then calls `Report.searchInServer(searchValue)`. However, since `setSearchValue` is asynchronous, `searchValue` may not be updated immediately, causing the outdated value to be used in the search.

```js
 const onChangeText = (value = '') => { 
     setSearchValue(value); 
     Report.searchInServer(searchValue); 
 }; 
```

Proposed Approach: We will update `onChangeText` to immediately pass the new value to `Report.searchInServer`. This ensures that the search function always uses the most current input from the user.


```js
 const onChangeText = (value = '') => { 
     setSearchValue(value); 
     Report.searchInServer(value); 
 }; 
```

**Comment by sophiepintoraetz** [comment] 2024-01-18 01:21
Hi @Gonals - can you take a look at the [C+ approved proposal](https://github.com/Expensify/App/issues/34516#issuecomment-1892577771)?

**Comment by Gonals** [comment] 2024-01-19 10:39
> @namhihi237's [proposal](https://github.com/Expensify/App/issues/34516#issuecomment-1892548966) looks good to me.
> 
> 🎀 👀 🎀 C+ Reviewed

Sounds good!

**Comment by namhihi237** [comment] 2024-01-20 11:12
@shubham1206agra  [PR ](https://github.com/Expensify/App/pull/34846) is already for review but I am not sure why the reviewer is incorrect. Can you re-assign C+ for this PR @Gonals . Thanks

**Comment by CortneyOfstad** [comment] 2024-02-02 14:15
@Gonals bump on the comment [here](https://github.com/Expensify/App/issues/34516#issuecomment-1902067665)

**Comment by Gonals** [comment] 2024-02-02 15:34
> @Gonals bump on the comment [here](https://github.com/Expensify/App/issues/34516#issuecomment-1902067665)

Ah, I already handled it back then 😁

**Comment by Gonals** [comment] 2024-02-12 15:54
> @Gonals, I think we need to talk about [#34846 (comment)](https://github.com/Expensify/App/pull/34846#issuecomment-1932483146) here.

True. @CortneyOfstad,  @namhihi237 worked on a fix for this issue for a while, and it was almost ready. However, the refactor of `SearchPage` got rid of the issue before their fix merged. What do we do regarding payment in these cases?

**Comment by CortneyOfstad** [comment] 2024-02-14 14:28
Reaching out to @Gonals to discuss 👍

**Comment by CortneyOfstad** [comment] 2024-02-14 14:34
@shubham1206agra @namhihi237 — after a discussion with the team, it was decided to offer a 50% payment ($250) to both of you for the work put in. If that is okay with you both, I'll get the Upwork proposals sent over ASAP. Thanks for your patience!

**Comment by CortneyOfstad** [comment] 2024-02-14 14:47
Thanks! 

@namhihi237 — you've been paid in Upwork, so you're all set!

@shubham1206agra — I sent you a proposal in Upwork, let me know once you accept!

**Comment by CortneyOfstad** [comment] 2024-02-14 14:52
Awesome — thanks! Payments have been completed and sharing the payment summary below!

**Comment by CortneyOfstad** [comment] 2024-02-14 14:53
## Payment Summary

@namhihi237 (contributor) — paid $250 via Upwork
@shubham1206agra (C+) — paid $250 via Upwork

**Closed by CortneyOfstad** 2024-02-14 14:53 UTC
Labels: Reviewing, External, Daily, Bug
