### ISSUE TITLE
[$1000] Reaction number indicator doesn't show up

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21976] opened 2023-06-30 18:07 UTC
HOLD for https://github.com/Expensify/Auth/pull/8145#discussion_r1240407965

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. Hover over the message on account A and click on reply in thread
3. Add a reaction from account A on the first thread message
4. Observe that the reaction number shows up and remove the reaction
5. Add a reaction on the first message from account B
## Expected Result: 
Reaction number should show up on account A's first thread message
## Actual Result: 
Reaction number doesn't show up on account A's first message inside of the thread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/69525c04-258b-4646-a389-819608fff4f6

https://github.com/Expensify/App/assets/43996225/9ff1be00-f4e2-497a-b99b-82a4de3e427d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687818774044589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a74fc4df34e0cc9</li>
        <li>Upwork Job ID: 1674855461324615680</li>
        <li>Last Price Increase: 2023-06-30</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-06-30 19:00
I was only able to reproduce this on OSX Chrome, with a normal window for Account A and an incognito window for Account B

![image](https://github.com/Expensify/App/assets/5802477/baf5161c-f76c-472e-a9e7-81e1e28806b8)

**Comment by staticGuru** [comment] 2023-06-30 20:05
@kavimuru issues are not able to reproduceable.

**Comment by s-alves10** [comment] 2023-06-30 21:58
This looks like a backend issue. Backend doesn't send any events after the thread is newly created.

**Comment by staticGuru** [comment] 2023-07-01 04:43
> 📣 @staticGuru! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: vigneshguru274@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010f381f7a58a7ba26

**Comment by StevenKKC** [comment] 2023-07-01 15:22
This is a BE issue.
If account B add a reaction on the first message, server respond as below. Error message is "Report no longer exists", but have a correct reaction information.
![Annotation 2023-07-01 111445](https://github.com/Expensify/App/assets/131836113/2bf5cc57-d036-4311-b626-eae3c2dff972)

And BE does not send any push event.

**Comment by OctavianGuzu** [comment] 2023-07-01 15:31
It doesn't seem to be a BE issue. I found the root cause and it is client-side. Writing a proposal now.

**Comment by conorpendergrast** [comment] 2023-07-06 11:06
@fedirjh I missed this before now, thank you! I'll move to Internal

**Comment by johnmlee101** [comment] 2023-07-06 17:54
@chiragsalian had a great summary here: https://expensify.slack.com/archives/C01SKUP7QR0/p1688664864651269?thread_ts=1688662232.784009&cid=C01SKUP7QR0

**Comment by johnmlee101** [comment] 2023-07-06 18:07
Putting this on hold for the changes https://github.com/Expensify/Auth/pull/8145#discussion_r1240407965 potentially introduced here cc @cristipaval

**Comment by conorpendergrast** [comment] 2023-07-10 14:11
Still on hold

**Comment by conorpendergrast** [comment] 2023-07-14 12:21
And, still on hold

**Comment by conorpendergrast** [comment] 2023-07-17 17:44
Still on hold for https://github.com/Expensify/Auth/pull/8145

**Comment by conorpendergrast** [comment] 2023-07-19 20:56
Same agaib

**Comment by johnmlee101** [comment] 2023-07-25 21:37
on HOLD

**Comment by conorpendergrast** [comment] 2023-07-31 09:57
Still held

**Comment by conorpendergrast** [comment] 2023-08-03 11:57
It is... still on hold!

**Comment by conorpendergrast** [comment] 2023-08-07 16:05
Yep, still on hold for https://github.com/Expensify/Auth/pull/8145#discussion_r1240407965

**Comment by conorpendergrast** [comment] 2023-08-10 13:33
Still held

**Comment by conorpendergrast** [comment] 2023-08-14 15:12
Still held

**Comment by conorpendergrast** [comment] 2023-08-21 19:24
Yep, still on hold!

**Comment by conorpendergrast** [comment] 2023-08-25 12:17
Still, still, still on hold!

**Comment by conorpendergrast** [comment] 2023-08-29 11:56
Still held on https://github.com/Expensify/Auth/pull/8145

**Comment by conorpendergrast** [comment] 2023-09-04 12:28
Still held on https://github.com/Expensify/Auth/pull/8145. I'm going to move this to Weekly as that PR is taking time

**Comment by conorpendergrast** [comment] 2023-09-11 12:32
@maddylewis This is held on https://github.com/Expensify/Auth/pull/8145!

**Comment by maddylewis** [comment] 2023-09-20 18:48
still holding - https://github.com/Expensify/App/issues/21976#issuecomment-1713786591

**Comment by maddylewis** [comment] 2023-09-29 14:37
holding - https://github.com/Expensify/App/issues/21976#issuecomment-1713786591

**Comment by maddylewis** [comment] 2023-10-16 17:00
ok this is merged - https://github.com/Expensify/Auth/pull/8145

@fedirjh -  is the best next step to see if this is still reproducible and then go from there? or, should we be re-reviewing existing proposals to move forward with a fix for this one?

**Comment by Nathan-Mulugeta** [comment] 2023-10-16 17:38
I just retested this and the issue is not reproducible to me either.

**Comment by maddylewis** [comment] 2023-10-26 00:59
noted! it sounds like im good to close this out then 👍

**Closed by maddylewis** 2023-10-26 00:59 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
