### ISSUE TITLE
[HOLD for payment 2024-04-15] [$250] Bank account - Company's website field is missing https://

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38585] opened 2024-03-19 13:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to Profile > Workspaces > any workspace.
3. Go to Bank account > Connect manually.
4. Proceed until Company's website step.

## Expected Result:
Company website field will have https://
in the field by default (production behavior).

## Actual Result:
Company website field does not have https://
in the field. The field is empty.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7c50ba5b-7e74-4c93-864e-0c0b2c24353a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166d2a81ddf61dab7</li>
        <li>Upwork Job ID: 1772294434143510528</li>
        <li>Last Price Increase: 2024-03-25</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-19 13:34
We think that this bug might be related to #wave-collect - Release 1

**Comment by godofoutcasts94** [comment] 2024-03-19 15:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Bank account - Company's website field is missing https://
### What is the root cause of that problem?
Here :
https://github.com/Expensify/App/blob/e34f10ec01a21ecddebc4b12c721705ba7bd514d/src/pages/ReimbursementAccount/BusinessInfo/substeps/WebsiteBusiness.tsx#L51-L55
because of empty string the website field is empty.
### What changes do you think we should make in order to solve the problem?

We can remove things `useMemo` and add this :
```
const defaultCompanyWebsite = 'https://';
```
this will show `https://`
### What alternative solutions did you explore? (Optional)
N/A

**Comment by godofoutcasts94** [comment] 2024-03-19 15:14
Updated [Proposal](https://github.com/Expensify/App/issues/38585#issuecomment-2007454967)

**Comment by cristipaval** [comment] 2024-03-19 16:29
I'm demoting this one as NAB given that it is a minor UI issue. We have the URL validation so the user can't add invalid data 🤷‍♂️

**Comment by cristipaval** [comment] 2024-03-19 16:30
@mateuuszzzzz would you work to fix this one?

**Comment by cristipaval** [comment] 2024-03-19 16:30
I'm also adding @aimane-chnaif as the C+ since he was also assigned to the original PR

**Comment by godofoutcasts94** [comment] 2024-03-19 16:46
Hey @cristipaval how about my proposal?

**Comment by godofoutcasts94** [comment] 2024-03-22 03:20
Hey @dukenv0307 can you please review my proposal?

**Comment by cristipaval** [comment] 2024-03-25 16:07
Given that this is a super simple issue, I would make it a $250 issue. Let me know guys if you think this is not fair

**Comment by godofoutcasts94** [comment] 2024-03-25 16:09
hey @dukenv0307 how about my proposal?

**Comment by godofoutcasts94** [comment] 2024-03-25 17:53
Can you check my working video ? or I can post a working video for your reference @dukenv0307

**Comment by cristipaval** [comment] 2024-03-27 11:50
Thanks @dukenv0307!
Assigning @tienifr to not disturb @mateuuszzzzz from wave work.

**Comment by puneetlath** [comment] 2024-04-15 20:26
All paid. Thanks everyone.

**Closed by puneetlath** 2024-04-15 20:26 UTC
Labels: External, Engineering, Daily, Awaiting Payment
