### ISSUE TITLE
[HOLD for payment 2024-02-07] Bank account - Wrong account number error is still shown after restarting the add BA process

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35095] opened 2024-01-24 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** Y
**Reproducible in production?:** no, unable to check prod
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4234233
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a Workspace
1. Go to Settings > Workspaces > Select Workspace > Bank account
2. Try to add BA with Plaid, selecting Chase bank and the account ending in "1111"
3. When entering the account number, enter "1111222233334444", an error should appear when trying to submit the form
4. Restart the process selecting the same bank and the account ending in "1111"

## Expected Result:
No error should appear as the process was restarted

## Actual Result:
Wrong account number error is shown after the process is restarted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2779182a-a6a1-42f8-8612-d8e79475ac9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NikkiWines** [comment] 2024-01-24 19:25
Hmm, yeah we should probably be clearing the errors once you press `Connect online with Plaid` 

Side note also that the styling for the dropdown for the accounts is super wonky
![image](https://github.com/Expensify/App/assets/16747822/b0f025eb-217a-4046-b83a-79e364d606f3)

**Comment by NikkiWines** [comment] 2024-01-24 20:03
dropdown looks fine on dev MacOS-Chrome though, probably a platform-specific thing. 

![image](https://github.com/Expensify/App/assets/16747822/d6fbf69a-0a63-4cc6-bcc3-6ada772980b4)

I'm able to reproduce the issue on dev, looking into a fix now.

**Comment by sofi-a** [comment] 2024-01-24 21:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong account number error is still shown after restarting the add BA process

### What is the root cause of that problem?
Reimbursement account error data is not getting reset when clicking on the back button to exit the bank account plaid step form.

### What changes do you think we should make in order to solve the problem?
Reset reimbursement account error onyx data for manual step in back button press handler [here](https://github.com/Expensify/App/blob/adf594e4bc55494fafa8587fcd0d1ec07447148f/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L358);

```js
import * as ReimbursementAccountErrors from '@libs/actions/ReimbursementAccount/errors';

...

    const goBack = () => {
    ...
            case CONST.BANK_ACCOUNT.STEP.BANK_ACCOUNT:
                if (hasInProgressVBBA()) {
                    setShouldShowContinueSetupButton(true);
                }
                if (subStep) {
                    BankAccounts.setBankAccountSubStep(null);
                    BankAccounts.setPlaidEvent(null);
+                    ReimbursementAccountErrors.resetReimbursementAccount();
                } else {
                    Navigation.goBack(backTo);
                }
                break;
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by NikkiWines** [comment] 2024-01-24 23:54
@thienlnam since you're App deployer this week, if the above PR isn't merged / CP'd by tomorrow I wouldn't hold the deploy on this since the behavior is pretty niche and it's not a significant error or breaking anything really.

**Comment by thienlnam** [comment] 2024-01-25 04:35
Sounds good, thanks!

**Comment by NikkiWines** [comment] 2024-02-08 18:02
@rushatgabhane do we owe you payment for reviewing https://github.com/Expensify/App/pull/35117?

**Comment by NikkiWines** [comment] 2024-02-13 19:10
Seems we are all set here, closing!

**Comment by rushatgabhane** [comment] 2024-02-20 05:00
Hi @NikkiWines, i missed this because i wasn't assigned.
Anyway, could you please attach payment summary for review of 
- https://github.com/Expensify/App/pull/35117

**Comment by NikkiWines** [comment] 2024-02-21 23:23
@twisterdotcom can we issue payment to @rushatgabhane for reviewing https://github.com/Expensify/App/pull/35117 please 🙇

**Comment by twisterdotcom** [comment] 2024-02-22 21:23
@rushatgabhane is paid via newDot: https://github.com/Expensify/Web-Expensify/blob/058e9134d8e6b038b9a31364f496406e2b2415a7/_devportal/lib/KernelScheduling/Data.php#L261C10-L261C23

**Comment by twisterdotcom** [comment] 2024-02-22 21:23
Payment Summary:

- @rushatgabhane paid $500 via NewDot Requests (C+)

**Comment by JmillsExpensify** [comment] 2024-02-23 17:14
$500 approved for @rushatgabhane based on summary above.

**Closed** 2024-02-26 09:34 UTC
Labels: Engineering, Daily, Overdue, Awaiting Payment, Bug
