### ISSUE TITLE
[$500] Android-Workspace-Unable to return to LHN from workspace chat when logged in as new invited member

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26876] opened 2023-09-06 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition:
- User A - Expensifail account
- User B - Gmail account
- User A invites User B which is not registered to ND account to a workspace.

Steps:
1. As User B, go to email and validate the account.
2. As User B, log in to New Expensify app.
3. After being redirected to the workspace chat, return to LHN.

## Expected Result:
User B is able to return to LHN.

## Actual Result:
User B is prevented from returning to LHN in workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/78b4ec43-c965-4606-8dad-67b9b8ccff93

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e4851b2489cbd6f4</li>
        <li>Upwork Job ID: 1701604219338174464</li>
        <li>Last Price Increase: 2023-10-03</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-09-12 14:30
Triaged

**Comment by eVoloshchak** [comment] 2023-09-18 16:38
Not overdue, awaiting proposals

**Comment by eVoloshchak** [comment] 2023-09-21 10:59
Not overdue, awaiting proposals

**Comment by eVoloshchak** [comment] 2023-09-25 14:02
Not overdue, awaiting proposals

**Comment by mvtglobally** [comment] 2023-09-28 03:25
Issue not reproducible during KI retests. (First week)

**Comment by eVoloshchak** [comment] 2023-10-02 09:44
Not overdue, looks like this isn't reproducible anymore (let's wait for the second week)

**Comment by johncschuster** [comment] 2023-10-04 21:21
@eVoloshchak it doesn't look like we received any proposals. This one's all yours!

**Comment by johncschuster** [comment] 2023-10-10 21:12
@eVoloshchak how's this one going?

**Comment by eVoloshchak** [comment] 2023-10-17 14:44
Not overdue, this needs reproduction

**Comment by johncschuster** [comment] 2023-10-19 19:42
@mvtglobally bump! Are you able to reproduce this?

**Comment by johncschuster** [comment] 2023-10-24 12:44
@mvtglobally bump! Can you please check to see if you are able to reproduce this!

**Comment by eVoloshchak** [comment] 2023-10-30 09:38
Not overdue, needs reproduction
cc: @mvtglobally

**Comment by johncschuster** [comment] 2023-11-01 14:24
^This

**Comment by eVoloshchak** [comment] 2023-11-06 15:16
Not overdue, needs reproduction
cc: @mvtglobally

**Comment by mvtglobally** [comment] 2023-11-08 19:39
No longer repro on Android. 
We are checking mWeb as well https://github.com/Expensify/App/assets/43995119/282f1c08-86eb-4b8e-a28f-6dbd16415507

**Comment by johncschuster** [comment] 2023-11-14 22:27
Looks like we're waiting on reproducing on mWeb.

**Comment by johncschuster** [comment] 2023-11-14 22:27
Looks like we're waiting on reproducing on mWeb.

**Comment by eVoloshchak** [comment] 2023-11-21 21:58
@mvtglobally, is this reproducible on mWeb?

**Comment by johncschuster** [comment] 2023-11-29 04:03
@mvtglobally bump!

**Comment by johncschuster** [comment] 2023-12-08 21:43
Waiting on an update on tests

**Comment by johncschuster** [comment] 2023-12-13 15:10
Still waiting on tests. @mvtglobally were you able to reproduce this on web?

**Comment by eVoloshchak** [comment] 2023-12-22 11:58
Not overdue, waiting on tests
@mvtglobally were you able to reproduce this on web?

**Comment by johncschuster** [comment] 2024-01-02 22:36
@mvtglobally bump!

**Comment by mvtglobally** [comment] 2024-01-05 17:50
it doesnt look like we can repro the issue any more 

https://github.com/Expensify/App/assets/43995119/78c16a52-6aac-42fc-b07a-e955c3a0bf7a

**Comment by mvtglobally** [comment] 2024-01-05 17:56
https://github.com/Expensify/App/assets/43995119/1f430234-d079-4114-909d-a1ab153d918f

**Comment by johncschuster** [comment] 2024-01-09 21:42
Ok! It sounds like this is no longer reproducible. Closing!

**Closed by johncschuster** 2024-01-09 21:42 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Overdue, Bug
