### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Desktop - Unread messages get marked as read without me visiting the chats

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26824] opened 2023-09-05 20:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send the message from Account A (mobile) to Account B (Desktop app)
2. Check if message is Unread in Desktop app

## Expected Result:
 Unread messages displayed in LHN

## Actual Result:
Unread messages get marked as read without me visiting the chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.64.0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

n/a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693523157400069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100b1d4dc36ebfcc0</li>
        <li>Upwork Job ID: 1699281016069742592</li>
        <li>Last Price Increase: 2023-09-06</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26649040</li>
</ul></li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-09-06 04:39
Given that there are [multiple reports](https://expensify.slack.com/archives/C049HHMV9SM/p1693544177045929?thread_ts=1693523157.400069&cid=C049HHMV9SM), I'm going to go ahead and put this one out there.

**Comment by sophiepintoraetz** [comment] 2023-09-06 04:40
cc @danieldoglas - as Rocio's theory is that this is coming from #vip-reliable-updates - do you agree?

**Comment by burczu** [comment] 2023-09-06 11:53
@kbecciv @sophiepintoraetz @tienifr I wasn't able to reproduce it (sending messages from ios app to the desktop app and messages in LHN are not marked as read)... According to this [thread on Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1693523157400069) I guess this occurs only in some special circumstances, am I right? What are these circumstances?

**Comment by burczu** [comment] 2023-09-06 13:05
Just to inform: I'll be OOO on Thursday and Friday (7-8 September).

**Comment by davewish** [comment] 2023-09-06 13:27
### Proposal 
   ----
### Please re-state the problem that we are trying to solve in this issue.
Desktop: Unread message gets marked as read , without visiting the opening the message.
### What is the root cause of that problem?
In the below , It is not checked  whether  `optionItem ` is unread or not ,It only checks  with mention.
https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/LHNOptionsList/OptionRowLHN.js#L105-L109
### What changes do you think we should make in order to solve the problem?
We should update the line by adding `optionItem.isUnread`
```JAVASCRIPT
 const shouldShowGreenDotIndicator =
        !hasBrickError &&
        (optionItem.isUnreadWithMention ||  optionItem.isUnread ||
            ReportUtils.isWaitingForIOUActionFromCurrentUser(optionItem) ||
            (optionItem.isTaskReport && optionItem.isTaskAssignee && !optionItem.isCompletedTaskReport && !optionItem.isArchivedRoom));
```

### what alternative solutions did you explore?(Optional)
N/A

**Comment by sophiepintoraetz** [comment] 2023-09-12 02:34
@tienifr - are you able to reproduce this?

**Comment by burczu** [comment] 2023-09-12 10:31
Ok, I've finally reproduced the issue successfully! I didn't notice at first that it is marked as read after some short period of time.

Also reviewed proposals and [the solution](https://github.com/Expensify/App/issues/26824#issuecomment-1707834004) from @tienifr seem to be correct and I think we could proceed with it.

[Solution](https://github.com/Expensify/App/issues/26824#issuecomment-1708362100) proposed by @davewish is, I think incorrect - it also fixes the issue but it adds the green dot next to the unread message which shouldn't happen.

🎀 👀 🎀 C+ reviewed

**Comment by davewish** [comment] 2023-09-13 02:45
please , I need clarification ,    my proposal is reviewed as incorrect   by @burczu  and   job assigned to me . then I will proceed with the job

**Comment by burczu** [comment] 2023-09-13 06:41
yeah @cristipaval - I've recommended solution from @tienifr

**Comment by cristipaval** [comment] 2023-09-13 08:53
@tienifr, you should be all set now! 🚀

**Comment by sophiepintoraetz** [comment] 2023-09-28 06:26
Payouts due:

Issue Reporter: N/A 
Contributor: $750 @tienifr 
Contributor+: $750 @burczu - can request seeing as you have completed the BZ checklist, thank you!

Eligible for 50% #urgency bonus? Y

**Closed** 2023-09-28 06:26 UTC
Labels: External, Daily, Needs Reproduction, Awaiting Payment, Bug

**Comment by burczu** [comment] 2023-09-28 07:32
@sophiepintoraetz I'm not eligible for payment as I'm contractor from Callstack.

**Comment by sophiepintoraetz** [comment] 2023-09-28 07:35
Oh thanks for confirming, then we are super done!
