### ISSUE TITLE
Accounting - Integration tries to sync again after disconnect

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49018] opened 2024-09-11 18:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/cases/view/3155298
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition: workspace added. Accounting is enabled.

1. Go to WS > Accounting
2. Connect to integration (NetSuite, Sage intact)
3. Go to Import > change any value or toggle (e.g. enable Tax)
4. Click on three dots near synced integration > Disconnect
5. Wait ~40-60 sec

## Expected Result:
After step 5, no sync will triggered. All integrations are disconnected.

## Actual Result:
After step 5, disconnected integration is triggered to sync again. Sync fails. User has to manually disconnect integration again.

NOTE: assume the root cause is in the lag between any action (step 3) and sync. Actually, toggle change sync is trigger after disconnection that causes sync again.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/cd552f93-7b0d-4fbb-9dc0-6b757f693069

https://github.com/user-attachments/assets/0eeea20d-ff68-4bb1-a3a6-3ea9daed4498

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-11 18:40
We think that this bug might be related to #wave-control

**Comment by IuliiaHerets** [comment] 2024-09-11 18:41
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by anmurali** [comment] 2024-09-25 01:22
I couldn't reproduce this. So closing for now.

**Closed by anmurali** 2024-09-25 01:22 UTC
Labels: Daily, Overdue, Bug
