### ISSUE TITLE
[HOLD for payment 2024-11-14] [$250] Splitting 9000 with 4 users, the confirmation page incorrectly displays the participant amounts as 0.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51800] opened 2024-10-31 14:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-0.
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Only in stand alone, Hybrid is not updated yet
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  @rayane-djouah 
**Slack conversation** (hyperlinked to channel name):  https://expensify.slack.com/archives/C049HHMV9SM/p1730291114159429

## Action Performed:
1. Start a group
2. Split money (e.g 9000)
3. Enter the value in the BNP
4. Observe the individual split amount 
## Expected Result:
Should be 2250
## Actual Result:
Showing as 0
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

https://github.com/user-attachments/assets/b0754162-20d2-4e62-bdd1-7a8ebb0101c5

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021852081957595400665</li>
        <li>Upwork Job ID: 1852081957595400665</li>
        <li>Last Price Increase: 2024-10-31</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by mkzie2** [comment] 2024-10-31 15:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to edit

### What is the root cause of that problem?
It comes from https://github.com/Expensify/App/pull/51202

The amount regex doesn't accept commas character

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/components/MoneyRequestAmountInput.tsx#L277

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/libs/MoneyRequestUtils.ts#L43-L47
### What changes do you think we should make in order to solve the problem?
We should update this function with another param, `isAllowCommas,` whose default value is `false`, and introduce a new prop, `isAllowCommas,` with the same default value in `MoneyRequestAmountInput`.

if `isAllowCommas` is true, we should return the regex that allows the commas

```
/**
 * Get amount regex string
 */
function amountRegex(decimals: number, amountMaxLength: number = CONST.IOU.AMOUNT_MAX_LENGTH, isAllowCommans = false): string {
    const amountRegexWithoutDecimals = isAllowCommans ? `(?:\\d{1,3})(?:,\\d{3}){0,${Math.floor((amountMaxLength - 1) / 3)}}$|^\\d{1,${amountMaxLength}}` : `\\d{0,${amountMaxLength}}`;
    return decimals === 0
        ? `^${amountRegexWithoutDecimals}$` // Don't allow decimal point if decimals === 0
        : `^${amountRegexWithoutDecimals}(?:(?:\\.|\\,)\\d{0,${decimals}})?$`; // Allow the decimal point and the desired number of digits after the point
}
```

https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/libs/MoneyRequestUtils.ts#L43-L47


Update this line to pass `isAllowCommans` prop

```
const regex = useMemo(() => MoneyRequestUtils.amountRegex(decimals, undefined, isAllowCommans), [decimals]);
```
https://github.com/Expensify/App/blob/72163109c2fbc82d16f444d52b7e2a25f32bed43/src/components/MoneyRequestAmountInput.tsx#L277

After that we can pass `isAllowCommans={true}` here
https://github.com/Expensify/App/blob/224b633c284fd32e928684010084c587627d5e9a/src/components/MoneyRequestConfirmationList.tsx#L548
### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-10-31 17:21
Hmm this is starting to get a little bit complicated as what the user can input vs what the BE consider valid are two different things e.g.
- 1500.79
- 1,500.79
- 1.500,79

All the above are valid numbers and can be entered by the user but only the first is accepted in the BE

**Comment by marcochavezf** [comment] 2024-10-31 20:15
I haven't been able to reproduce it on the web; seems it's only happening on Android. So I don't think this should block the deploy, but it should be fixed. 

> All the above are valid numbers and can be entered by the user but only the first is accepted in the BE

But why is it working on other platforms? Given it's still in the regression period, can you fix it @s77rt?

**Comment by mkzie2** [comment] 2024-11-01 03:01
When we send the value to BE we will send the correct amount. In other cases, the formatted amount is only used to display. Since editing the amount with commas seems complex, when we focus on the amount input we can change the text input to the value amount and only change it to the formatted amount text after we blur the text input.

**Comment by s77rt** [comment] 2024-11-01 07:48
I'm working on it. The bug does not happen on web because the regex prop only is only available in native (it was added on native to prevent some flickering)

**Comment by s77rt** [comment] 2024-11-01 11:41
I spent some time on this. I can't seem to find an easy solution because the comma position for groups is not predetermined e.g. if the input is 1,90|0.00 (| is the cursor) and you press delete the value would be 1,90.00 which is not a valid amount but it's a valid intermediate state. An option to fix this is to have 2 regex but I found this will pretty much re-introduce the original bug https://github.com/Expensify/App/issues/47875. For that reason I think it's best to revert the PR

**Comment by mkzie2** [comment] 2024-11-01 13:57
@s77rt What do you think about my [idea](https://github.com/Expensify/App/issues/51800#issuecomment-2451204225) above?

**Comment by s77rt** [comment] 2024-11-01 14:13
@mkzie2 The value is displayed 0 even before focus

**Comment by mkzie2** [comment] 2024-11-01 14:20
We still need to update the regex to accept commas but use the idea above to edit the amount with commas.

**Comment by s77rt** [comment] 2024-11-01 14:59
@mkzie2 I think that would fix that bug but I faced another problem since now you can paste `14,500.00` but in some places the grouping is not allowed and it keeps only periods or commas (depending on the locale) making the value `14.500.00` or `14,500,00` which is not a number (NaN).


https://github.com/user-attachments/assets/d02c2234-49d6-4e6a-950e-1a74937c3ca7

**Comment by sonialiap** [comment] 2024-11-12 11:49
Thanks!

Closing since no payment is needed

**Closed by sonialiap** 2024-11-12 11:49 UTC
Labels: External, Engineering, Weekly, Help Wanted, Awaiting Payment, Bug
