### ISSUE TITLE
[HOLD for payment 2023-02-06] [$1000] The emoji titles are not vertically centered in android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14462] opened 2023-01-22 18:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any chat
3. Open emoji picker
4. You'll notice that the emoji titles aren't vertically centered

## Expected Result:
Emoji titles should be vertically centered

## Actual Result:
They aren't vertically centered in Android

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/213932852-badb3fc3-a343-4e7a-b6d1-546e3c26da2b.PNG" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/213932854-92225ec8-63d7-49e8-ba3e-d37d968ff5a5.jpg" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/213932862-34cab836-2180-4e99-b4a1-a1ea35b0cccd.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/213932863-3364c6ce-c5cd-4827-b3e9-000372fe94ca.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674393700959009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c89c9325c04466a1</li>
        <li>Upwork Job ID: 1618082297115369472</li>
        <li>Last Price Increase: 2023-01-25</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-01-25 02:16
Per discussion in Slack we're not sure if this is `Bug` or `NewFeature`, discussing

**Comment by Pujan92** [comment] 2023-01-25 03:04
*Proposal**

It seems we need to wrap the `Text` in the `View`(bcoz `Text` doesn't required 32px height) which will be the solution for this rendering issue(Text renders different in the native), and for better change and consistency we can apply the same for web too.

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.js b/src/components/EmojiPicker/EmojiPickerMenu/index.js
index 924d81a2b..3994f17d4 100755
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.js
@@ -438,9 +438,11 @@ class EmojiPickerMenu extends Component {
 
         if (header) {
             return (
-                <Text style={styles.emojiHeaderStyle}>
-                    {this.props.translate(`emojiPicker.headers.${code}`)}
-                </Text>
+                <View style={styles.emojiHeaderWrapper}>
+                    <Text style={styles.emojiHeaderText}>
+                        {this.props.translate(`emojiPicker.headers.${code}`)}
+                    </Text>
+                </View>
             );
         }
 
diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.native.js b/src/components/EmojiPicker/EmojiPickerMenu/index.nati
ve.js
index 754ed20fd..17a9d50e9 100644
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.native.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.native.js
@@ -107,9 +107,11 @@ class EmojiPickerMenu extends Component {
 
         if (item.header) {
             return (
-                <Text style={styles.emojiHeaderStyle}>
-                    {this.props.translate(`emojiPicker.headers.${item.code}`)}
-                </Text>
+                <View style={styles.emojiHeaderWrapper}>
+                    <Text style={styles.emojiHeaderText}>
+                        {this.props.translate(`emojiPicker.headers.${item.code}`)}
+                    </Text>
+                </View>
             );
         }
 
diff --git a/src/styles/styles.js b/src/styles/styles.js
index e30b5f77b..6077e7f47 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1459,12 +1459,16 @@ const styles = {
         height: 240,
     },
 
-    emojiHeaderStyle: {
+    emojiHeaderWrapper: {
         backgroundColor: themeColors.componentBG,
         width: '100%',
         height: 32,
         display: 'flex',
+        flexDirection: 'row',
         alignItems: 'center',
+    },
+
+    emojiHeaderText: {
         fontFamily: fontFamily.EXP_NEUE_BOLD,
         fontWeight: fontWeightBold,
         color: themeColors.heading,
```

**Comment by Pujan92** [comment] 2023-01-25 03:18
> This is a regression caused by this [PR](https://github.com/Expensify/App/pull/13787)

Yes, the removal of vertical padding and applied height without wrapper caused this. Thanks for the find.

**Comment by jatinsonijs** [comment] 2023-01-25 04:01
**Root Case**:
We are applying height and align center on Text component but align center work for children where it is apply not for itself.

Occurred after these changes
PR: https://github.com/Expensify/App/pull/13787
Issue: https://github.com/Expensify/App/issues/12772

**Proposal**
We should also use const value of emoji header height as we already have const for header height to make it consistent everywhere we should use const.

```diff
diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.js b/src/components/EmojiPicker/EmojiPickerMenu/index.js
index 924d81a2bf..e2ad3bed1b 100755
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.js
@@ -438,9 +438,11 @@ class EmojiPickerMenu extends Component {
 
         if (header) {
             return (
-                <Text style={styles.emojiHeaderStyle}>
-                    {this.props.translate(`emojiPicker.headers.${code}`)}
-                </Text>
+                <View style={styles.emojiHeaderContainer}>
+                    <Text style={styles.emojiHeaderStyle}>
+                        {this.props.translate(`emojiPicker.headers.${code}`)}
+                    </Text>
+                </View>
             );
         }
 
diff --git a/src/components/EmojiPicker/EmojiPickerMenu/index.native.js b/src/components/EmojiPicker/EmojiPickerMenu/index.native.js
index 754ed20fd7..d70eed9880 100644
--- a/src/components/EmojiPicker/EmojiPickerMenu/index.native.js
+++ b/src/components/EmojiPicker/EmojiPickerMenu/index.native.js
@@ -107,9 +107,11 @@ class EmojiPickerMenu extends Component {
 
         if (item.header) {
             return (
-                <Text style={styles.emojiHeaderStyle}>
-                    {this.props.translate(`emojiPicker.headers.${item.code}`)}
-                </Text>
+                <View style={styles.emojiHeaderContainer}>
+                    <Text style={styles.emojiHeaderStyle}>
+                        {this.props.translate(`emojiPicker.headers.${item.code}`)}
+                    </Text>
+                </View>
             );
         }
 
diff --git a/src/styles/styles.js b/src/styles/styles.js
index e30b5f77b5..7f8906fe3f 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1459,12 +1459,14 @@ const styles = {
         height: 240,
     },
 
-    emojiHeaderStyle: {
+    emojiHeaderContainer: {
         backgroundColor: themeColors.componentBG,
         width: '100%',
-        height: 32,
+        height: CONST.EMOJI_PICKER_HEADER_HEIGHT,
         display: 'flex',
-        alignItems: 'center',
+        justifyContent: 'center',
+    },
+    emojiHeaderStyle: {
         fontFamily: fontFamily.EXP_NEUE_BOLD,
         fontWeight: fontWeightBold,
         color: themeColors.heading,

```

**Comment by Pujan92** [comment] 2023-01-25 08:38
> It seems we need to wrap the `Text` in the `View`(bcoz `Text` doesn't required 32px height) which will be the solution for this rendering issue(Text renders different in the native), and for better change and consistency we can apply the same for web too.

**SS**

![Screenshot_1674635792](https://user-images.githubusercontent.com/14358475/214516627-2c879b3d-3a3f-460a-92be-3ab35ca6768f.png)
![Simulator Screen Shot - iPhone 14 - 2023-01-25 at 08 41 33](https://user-images.githubusercontent.com/14358475/214516636-81a643b1-945a-460a-8c11-d25834bbd416.png)

**Comment by jatinsonijs** [comment] 2023-01-25 18:09
@thesahindia If it is about PR caused regression I have already reported it in slack thread.

**Comment by jatinsonijs** [comment] 2023-01-25 18:10
https://expensify.slack.com/archives/C049HHMV9SM/p1674566201027659?thread_ts=1674393700.959009&cid=C049HHMV9SM

**Comment by jatinsonijs** [comment] 2023-01-25 18:17
I think we all already have proposal for this sol, but there is not enough time as proposal was posted immediately, I have just added one extra think height: CONST.EMOJI_PICKER_HEADER_HEIGHT, and first who tell the regression PR.

**Comment by jatinsonijs** [comment] 2023-01-25 18:22
Its seem like race we have to post immediately after External tag added 🙂, Is using height from constant does not matter here ?

**Comment by Pujan92** [comment] 2023-01-25 18:40
> I agree with you, I am not in support of the "race" since most of the contributors doesn't get chance to contribute but I am not sure what can be done to stop that.

As these are straightforward changes I think it is going to be in race as we won't have much to enhance/improve.

**Comment by pecanoro** [comment] 2023-01-25 23:09
Assigning @daraksha-dk to the issue. Another reason to go with @daraksha-dk is that the regression was introduced by @Pujan92 so I think it would be unfair to get paid for fixing your own bug 😅

**Comment by Pujan92** [comment] 2023-01-26 02:13
> Assigning @daraksha-dk to the issue. Another reason to go with @daraksha-dk is that the regression was introduced by @Pujan92 so I think it would be unfair to get paid for fixing your own bug 😅

@pecanoro I would disagree over here, I was thought and asked for direct PR in [slack](https://expensify.slack.com/archives/C049HHMV9SM/p1674619875319779?thread_ts=1674393700.959009&cid=C049HHMV9SM) as this issue caused due to my PR. IMO As this won't be considered a regression now, I am allowed to propose a solution to this fresh issue. cc: @JmillsExpensify 

As it is already assigned I am ok with it but just wanted to make my point, Thanks.

**Comment by asAnyOne** [comment] 2023-01-26 08:19
![image](https://user-images.githubusercontent.com/91405921/214787933-51e61247-6767-49ad-9bac-aa29ec2760d5.png)
Why don't to add just a style like this?

**Comment by greg-schroeder** [comment] 2023-02-07 21:11
Was OOO yesterday, dealing with payment and regression steps now!

**Comment by greg-schroeder** [comment] 2023-02-07 23:15
Issue reporter: @daraksha-dk ($250)
Contributor: @daraksha-dk ($1000)
PR Reviewer: @thesahindia ($1000)

PR merged within 3 business days, eligible for 50% bonus

**Comment by greg-schroeder** [comment] 2023-02-07 23:19
Sent offers to you both - please accept and I'll take care of payment + bonus

**Comment by greg-schroeder** [comment] 2023-02-08 06:13
Paid, job closed.

**Comment by greg-schroeder** [comment] 2023-02-08 08:03
Filed regression test request per https://github.com/Expensify/App/issues/14462#issuecomment-1419612773

**Closed by greg-schroeder** 2023-02-08 08:03 UTC
Labels: External, Weekly, Awaiting Payment, Bug
