### ISSUE TITLE
Notifications - Push notification is arriving when chatting with current user.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14299] opened 2023-01-13 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Open any chat
3. Send a message from B to A.

## Expected Result:
Push notification is not arriving when chatting with current user.

## Actual Result:
Push notification is arriving when chatting with current user.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Android / native
- [ ] iOS / native

**Version Number:** 1.2.54.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/212418016-50e2fdee-d261-44e2-9a2e-0f90697343c0.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2023-01-16 22:34
Oh whoops, sorry for the delay! In any case, I don't think we should do anything on this one until the notification refactor is officially done. Do you agree with that, @Julesssss @arosiclair?

**Comment by arosiclair** [comment] 2023-01-17 00:21
Yeah this is intended behavior currently not a bug. This will be improved in the [polish phase.](https://github.com/Expensify/Expensify/issues/255265)

**Comment by JmillsExpensify** [comment] 2023-01-17 05:04
Great thank you! Closing.

**Closed by JmillsExpensify** 2023-01-17 05:04 UTC
Labels: Daily, Bug
