### ISSUE TITLE
Taxes - Tax rate and tax amount take some time to show up in transaction thread

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39615] opened 2024-04-04 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.60-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace that has taxes.
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a manual request with tax.
4. Go to transaction thread immediately after the request is created.

## Expected Result:
Tax rate and tax amount will instantly show up in transaction thread.

## Actual Result:
Tax rate and tax amount take some time to show up in transaction thread.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5e7a7400-27de-426c-aadd-619fe7622723

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013d484f5c32510e05</li>
        <li>Upwork Job ID: 1775993187810840576</li>
        <li>Last Price Increase: 2024-04-04</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-04 14:54
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment] 2024-04-04 15:08
Not a blocker, i think
We'll be fixing as a regression from https://github.com/Expensify/App/pull/33927

**Comment by alitoshmatov** [comment] 2024-04-04 20:19
This is related to offline updates which was not on scope of mentioned PR, and is going to be handled separately, ref: https://github.com/Expensify/App/pull/33927#issuecomment-2015690795

**Comment by MonilBhavsar** [comment] 2024-04-05 04:47
> This is related to offline updates which was not on scope of mentioned PR, and is going to be handled separately, ref:

@alitoshmatov I don't think this is related to offline in any case. This looks an issue with rendering

**Comment by MonilBhavsar** [comment] 2024-04-05 05:58
Okay, I think this is fixed with this change https://github.com/Expensify/App/pull/39638/files#diff-eec4675b6213eb7b4c8826a7b0a536ee7455e6a5580476ef0f9c8964e5deea81R163

@kbecciv can we please retest and confirm. Thank you!

**Comment by MonilBhavsar** [comment] 2024-04-08 12:10
Waiting for confirming from QA team (cc @kbecciv)
If reproducible, Eto Olei will be taking a look

**Comment by lschurr** [comment] 2024-04-08 15:39
Asked for a retest here: https://expensify.slack.com/archives/C9YU7BX5M/p1712590740591719

**Comment by kavimuru** [comment] 2024-04-08 17:02
@lschurr issue is fixed now. 
https://github.com/Expensify/App/assets/43996225/32d39438-ccfd-4346-a36e-5b404108d506

@MonilBhavsar https://github.com/Expensify/App/issues/39804 which was closed as dupe of [#39615](https://github.com/Expensify/App/issues/39615) still repro. Can we reopen that issue?

**Comment by MonilBhavsar** [comment] 2024-04-09 10:27
Thank you for confirming @kbecciv!
We can close this issue then

---

https://github.com/Expensify/App/issues/39804 is really a duplicate of https://github.com/Expensify/App/issues/39615
Once https://github.com/Expensify/App/issues/39615 is fixed, https://github.com/Expensify/App/issues/39804 will also be fixed. They have the same root cause - data not updated optimistically. As a result, there is some delay as data is being returned by server.

**Closed** 2024-04-09 10:27 UTC
Labels: Engineering, Daily, Internal, Bug, retest-weekly
