### ISSUE TITLE
Web - Chat - If you navigate the emoji list with arrow key, error appears in the console

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13895] opened 2022-12-29 23:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with any account
3. Go to any chat
4. Click on the emoji picker button
5. Navigate the emoji list with arrow key on the right column

## Expected Result:
Nothing should happen.

## Actual Result:
When the last emoji is reached, an error appears in the console.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Web / Chrome 

**Version Number:** 1.2.46.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/210022122-223cc69e-14c5-4b0a-a751-36451d0faecf.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-12-30 18:15
Unable to repro on Chrome staging. Neither on Firefox or in desktop app. 
@kbecciv are you on a mac or PC?  
Anything else I might be doing _wrong_?  The end of my emoji list is flags.

**Comment by tgolen** [comment] 2023-01-02 17:28
I can't reproduce this either so I will close this.

**Closed by tgolen** 2023-01-02 17:28 UTC
Labels: Daily, Overdue, Bug

**Comment by kbecciv** [comment] 2023-01-11 16:06
Tester was using Windows/Chrome

**Comment by mallenexpensify** [comment] 2023-01-11 18:37
Trying to find a BZ who has access to windows https://expensify.slack.com/archives/C01SKUP7QR0/p1673462066278179
