### ISSUE TITLE
[$1000] Web - Girl with earings default avatar glitches when coming back from share code

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25602] opened 2023-08-21 17:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Create group with user which has 'girl with earings' default avatar
3. Visit shareCode page by deep link, link: https://staging.new.expensify.com/settings/shareCode
4. Click on back and observe the avatar in group, it will be blacked out

## Expected Result:
Default avatars should not change color when visiting different pages

## Actual Result:
Girl with earings default avatar turns fully black when we visit shareCode page by deeplink and come back to settings page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/10f3b7f3-4c21-42ab-b970-5e223cbe1fc4

https://github.com/Expensify/App/assets/115492554/7b5d8ec6-c1b5-4a81-987a-19951c63370b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691648410032539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f62a96abd1e374f5</li>
        <li>Upwork Job ID: 1694034176852705280</li>
        <li>Last Price Increase: 2023-08-29</li>
    </ul>
</details>

**Comment by mvtglobally** [comment] 2023-08-21 17:19
This has been repro in older builds and for some reason not repro in prod now. We added a Blocker label, but not sure if it's really a blocker 

@mountiny @roryabraham since you are on checklist this week.

**Comment by CortneyOfstad** [comment] 2023-08-21 18:54
Bump @puneetlath @roryabraham @mountiny Do we feel like this is an actual blocker?

**Comment by roryabraham** [comment] 2023-08-21 21:32
Definitely not going to treat this as a deploy blocker. Let's verify that it can be reproduced then make it external with a lower bounty amount of $500. Thanks!

**Comment by dhanashree-sawant** [comment] 2023-08-22 05:25
Hi @0xmiroslav, although similar, that issue is not recreatable with your steps now and avatar too is different. Not sure if same root cause but I believe current issue reproduction steps are consistent and helped us to understand the issue properly.

**Comment by CortneyOfstad** [comment] 2023-08-24 12:33
still waiting on proposals, so not overdue 👍

**Comment by CortneyOfstad** [comment] 2023-08-28 12:27
@eVoloshchak @puneetlath Are either of you able to reproduce this? I'm not able to

**Comment by puneetlath** [comment] 2023-08-29 16:56
Hm, me either.

**Comment by CortneyOfstad** [comment] 2023-09-01 15:40
Okay, I'm going to close this. If this pops up again, feel free to reopen the GH and we can re-address 👍

**Closed by CortneyOfstad** 2023-09-01 15:40 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug

**Comment by dhanashree-sawant** [comment] 2023-09-01 16:28
I couldn't find that avatar anymore, did we decide to remove it?
