### ISSUE TITLE
[$250] Self DM - Self DM header shows skeleton loading after clearing cache and restarting app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47405] opened 2024-08-14 11:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Troubleshoot > Clear cache and restart
3. Click Reset and restart
4. Go to self DM

## Expected Result:
The self DM header will not show skeleton loading

## Actual Result:
The self DM header shows skeleton loading after clearing cache and restarting app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/fb6ff043-0e5a-4d3d-9e62-743a8139cefe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec9b2f42d3c8310a</li>
        <li>Upwork Job ID: 1823720855143736666</li>
        <li>Last Price Increase: 2024-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103625207</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-08-14 11:52
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-08-14 14:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The self DM header shows skeleton loading after clearing cache and restarting app

### What is the root cause of that problem?

After we clear cache and restarting app, the `reportNameCache` of the self DM becomes an empty string and then because the selfDM chat has `reportName`is empty string, it returns early as an empty string here.

https://github.com/Expensify/App/blob/04d0b1b463d04842c58ca17d625fedb5aa15da0d/src/libs/ReportUtils.ts#L3656-L3658

As expected the `HeaderView` display loading since the report name is an empty string
### What changes do you think we should make in order to solve the problem?
We should only return early if `reportNameFromCache.reportName` is not empty string

https://github.com/Expensify/App/blob/04d0b1b463d04842c58ca17d625fedb5aa15da0d/src/libs/ReportUtils.ts#L3656-L3658
### What alternative solutions did you explore? (Optional)
Or we should only store the cache if the value is not empty

https://github.com/Expensify/App/blob/04d0b1b463d04842c58ca17d625fedb5aa15da0d/src/libs/ReportUtils.ts#L3772

https://github.com/Expensify/App/blob/04d0b1b463d04842c58ca17d625fedb5aa15da0d/src/libs/ReportUtils.ts#L3753

**Comment by wildan-m** [comment] 2024-08-15 07:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The Self DM header displays skeleton loading after cache clearing and app restart.

### What is the root cause of that problem?

personalDetails is not re-loaded yet after the cache and selfDM doesn't have `displayName` value

personalDetails will contain this value
```tsx
{
    "isOptimisticPersonalDetail": true
}
```

### What changes do you think we should make in order to solve the problem?

If it's self DM, use currentUserEmail as fallback when  personalDetails is not loaded. Replace [this code](https://github.com/Expensify/App/blob/57ef25c998748332864ae98a43579989d6529c22/src/libs/ReportUtils.ts#L2023-L2025) to:
```tsx
    // For selfDM, we display the user's displayName followed by '(you)' as a postfix
    const isSelfDM = accountID === currentUserAccountID;
    const shouldAddPostfix = shouldAddCurrentUserPostfix && isSelfDM;

    // This is to check if account is an invite/optimistically created one
    // and prevent from falling back to 'Hidden', so a correct value is shown
    // when searching for a new user
    if (personalDetails.isOptimisticPersonalDetail === true) {
        return !isEmpty(formattedLogin) ? formattedLogin : (isSelfDM ? PersonalDetailsUtils.getDisplayNameOrDefault(personalDetails, currentUserEmail, shouldFallbackToHidden, shouldAddPostfix) : '');
    }

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by carlosmiceli** [comment] 2024-08-19 18:57
Have you had a chance to look at the proposals @eVoloshchak ?

**Comment by eVoloshchak** [comment] 2024-08-21 18:48
> We should only return early if reportNameFromCache.reportName is not empty string


@nkdengineer's [proposal](https://github.com/Expensify/App/issues/47405#issuecomment-2288966976) looks good to me, a simple and universal solution
 
 🎀👀🎀 C+ reviewed!

**Comment by carlosmiceli** [comment] 2024-09-16 18:48
@eVoloshchak this was fixed by your other PR, right? We can close this?

**Comment by eVoloshchak** [comment] 2024-09-19 14:07
@carlosmiceli, no, this was resolved by https://github.com/Expensify/App/pull/47831 ( the original PR for this issue)
Not sure why the automation has failed, it was deployed to production 3 weeks ago. Posting a checklist below

**Comment by eVoloshchak** [comment] 2024-09-19 14:12
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/47156
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:  https://github.com/Expensify/App/pull/47156/files#r1766911979
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is a simple issue, I don't think an additional discussion is needed

**Regression Test Proposal**

1. Go to Troubleshoot > Clear cache and restart
2. Click Reset and restart
3. Go to self DM
4. Verify that the self DM header is displayed correctly

**Do we agree 👍 or 👎**

**Comment by carlosmiceli** [comment] 2024-09-19 14:18
Yeah, that sounds good, thanks!

**Comment by mallenexpensify** [comment] 2024-09-19 22:18
Contributor: @nkdengineer paid $250 via Upwork
Contributor+: @eVoloshchak due $250 via NewDot

Testrail GH 
- https://github.com/Expensify/Expensify/issues/429566

@carlosmiceli , the step for you would be to add `Bug` or `New Feature` to assign a BZ to manage!

**Closed by mallenexpensify** 2024-09-19 22:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-09-23 20:31
$250 approved for @eVoloshchak
