### ISSUE TITLE
There are too many contact methods showing

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45336] opened 2024-07-12 13:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shubham1206agra 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720707891026509

## Action Performed:
1. Open app
2. Go to settings > profile
3. Click `Contact methods`
## Expected Result:
Only the added contact methods should appear
## Actual Result:
There are many contact emails are appearing
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/48b83e34-9d86-47ef-80d7-6601c3da1079

![Snip - (4) New Expensify - Google Chrome](https://github.com/user-attachments/assets/27e37c0d-044a-4476-8a37-815bc857e5a6)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2024-07-12 13:14
Removing the blocker labels. This doesn't occur for new/typical users and only shows up for power users like the Expensify and Applause teams:

![Screenshot 2024-07-12 at 14 13 18](https://github.com/user-attachments/assets/eb637820-2441-4505-91dd-ee977ea06541)

**Comment by Tony-MK** [comment] 2024-07-12 14:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There are too many contact methods showing

### What is the root cause of that problem?

The root cause of the problem is that the other `login?.partnerName`s are not filtered out of the `loginMenuItems` and will be displayed.

https://github.com/Expensify/App/blob/1048f9a9a14a6f0fd1ec70bd06f7cc62cfd69b1d/src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx#L49-L52

Therefore, all the other logins will be displayed in the [`ContactMethodsPage`](https://github.com/Expensify/App/blob/1048f9a9a14a6f0fd1ec70bd06f7cc62cfd69b1d/src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx) by the screenshot seen below.

![loginItems](https://github.com/user-attachments/assets/35c8de21-b678-484c-9a5e-917b44a7bad1)

### What changes do you think we should make in order to solve the problem?


Let's only display the partner name that is needed and add a second condition to exclude the other partner logins that don't need to be shown over [here](https://github.com/Expensify/App/blob/1048f9a9a14a6f0fd1ec70bd06f7cc62cfd69b1d/src/pages/settings/Profile/Contacts/ContactMethodsPage.tsx#L50-L53) like below.

```
if (!login?.partnerUserID && !pendingAction || (!login?.partnerName?.includes('expensify.com'))) {
    return null;
}
```

We could also use regex with a constant to find out if the `login?.partnerName` can be included in the `loginMenuItems`.

![Result](https://github.com/user-attachments/assets/7dca5f9e-8917-4d2d-8f84-4f032731a445)

**Comment by Tony-MK** [comment] 2024-07-12 14:52
Hey @Julesssss and @shubham1206agra, Are there other specific contact methods that should be shown except if the partner name is `expensify.com`?

**Comment by Julesssss** [comment] 2024-07-12 15:23
> Hey @Julesssss and @shubham1206agra, Are there other specific contact methods that should be shown except if the partner name is `expensify.com`?

Do you mean to replace the domain with Expensify?

**Comment by Tony-MK** [comment] 2024-07-12 15:31
> Do you mean to replace the domain with Expensify?

For the `logins`, yes.

**Comment by Tony-MK** [comment] 2024-07-12 15:35
> > Hey @Julesssss and @shubham1206agra, Are there other specific contact methods that should be shown except if the partner name is `expensify.com`?
> 
> Do you mean to replace the domain with Expensify?

Well, @Julesssss, this is an FE problem and some logins are visible.

I would like to know if any other `login?.partnerName` should be displayed except for the Expensify domain.

However, after testing with other domains I believe the solution works.

Thanks.

**Comment by RachCHopkins** [comment] 2024-07-15 04:50
@Julesssss should we be surfacing the expensify.cash emails at all? I can't imagine how it would be useful to show anything that's not an email or phone number. 

It is also an issue for real customers, here's my customer Sarah and I'm 100% sure these are all from messaging me:

![image](https://github.com/user-attachments/assets/194c841a-9e1c-4fbf-bcaf-37a308730f4c)

**Comment by Julesssss** [comment] 2024-07-15 09:42
Closing as dupe of https://github.com/Expensify/App/issues/45266.

Thanks @RachCHopkins,that does sound valid so lets continue to resolve on the above issue.

**Closed by Julesssss** 2024-07-15 09:42 UTC
Labels: Engineering, Daily, Bug
