### ISSUE TITLE
[HOLD for payment 2024-08-13] [$250] Context menu - Unable to add reaction by Enter key/navigate from first option to last by up key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44095] opened 2024-06-20 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4647677
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Right click on any message
4. Press Tab key
5. Press Enter
6. Press down arrow key
7. Press up arrow key

## Expected Result:
In step 5., The highlighted emoji should be added as reaction to the message (works well for hover menu)
In step 7., User should be able to navigate from first highlighted option to the last one using arrow keys

## Actual Result:
Step 5. Nothing happens user is unable to add reaction or open emoji picker using Enter key in context menu.
Step 7. Option does not change, user is unable to navigate from first option to last by up arrow key and from last to first by down arrow key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4a76d21b-ab4a-497d-9c21-9730e9373cd1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3361b27929e9c6b</li>
        <li>Upwork Job ID: 1805668929991815674</li>
        <li>Last Price Increase: 2024-07-23</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 102900677</li>
<li>Krishna2323 | Contributor | 103280879</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abekkala</details>

**Comment by lanitochka17** [comment] 2024-06-20 16:00
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-06-21 04:55
The cyclic traversal is being discussed [here](https://github.com/Expensify/App/issues/32279#issuecomment-2175047572)

**Comment by abekkala** [comment] 2024-06-26 18:48
@DylanDylann can you review the proposal above?

**Comment by DylanDylann** [comment] 2024-06-27 09:52
I have low bandwidth now, please re-assign this issue to another C+

**Comment by abekkala** [comment] 2024-06-27 13:52
thank you @dukenv0307

**Comment by abekkala** [comment] 2024-07-05 13:15
on HOLD

**Comment by roryabraham** [comment] 2024-08-02 18:51
@francoisl assigning to you since you reviewed [the PR](https://github.com/Expensify/App/pull/46379).

**Comment by abekkala** [comment] 2024-08-07 17:18
### PAYMENT SUMMARY FOR AUG 13, if no regressions

- Fix: @Krishna2323  [$250] [offer](https://www.upwork.com/nx/wm/offer/103280879)
- PR Review: @dukenv0307 [$250] [offer
](https://www.upwork.com/nx/wm/offer/102900677)

**Comment by abekkala** [comment] 2024-08-13 17:05
@Krishna2323 and @dukenv0307 payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2024-08-13 17:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
