### ISSUE TITLE
iOS Hold - App returns to Hold - reason page when tapping on back button after holding expense

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45446] opened 2024-07-16 02:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when validating https://github.com/Expensify/App/pull/44880
**Version Number:**  9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to workspace chat that has no unsettled expense.
3. Submit an expense.
4. Tap on the expense preview to go to expense report.
5. Tap on the report header.
6. Tap Hold.
7. Enter a reason and save it.
8. Tap on the back button on transaction thread.

## Expected Result:
App will return to the previous page (main chat or expense report).

## Actual Result:
App returns to Hold - reason page when tapping on back button after holding an expense.

NOTE: This issue only happens when there is only one expense in the combined report.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4dbe2f9b-5292-44d2-9668-85bde85319ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2024-07-16 14:14
looks like [a PR](https://github.com/Expensify/App/issues/45446) was created and the issue is tracked [here](https://github.com/Expensify/App/issues/45443)

removing the deploy blocker from this issue

**Comment by joekaufmanexpensify** [comment] 2024-07-16 14:19
@hayata-suenaga if this issue has the same RCA as the other one and a PR is up, should we just close this one?

**Comment by hayata-suenaga** [comment] 2024-07-17 14:50
yes I think we can close this one 😄

**Closed by hayata-suenaga** 2024-07-17 14:50 UTC
Labels: Engineering, Daily, Bug

**Comment by joekaufmanexpensify** [comment] 2024-07-17 14:51
Sweet. TY!
