### ISSUE TITLE
[$500] Public room - Unable to play video after navigating to LHN and back to public room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36975] opened 2024-02-20 23:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/r/4098419659819887
2. Play the video attachment
3. Tap the back icon to navigate to the LHN
4. Open the public room from LHN
5. Tap the video to play
## Expected Result:
Video is playing
## Actual Result:
"Hmm not there" screen is displayed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/4db22572-7d62-47e1-b0ad-1071ef187367

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8c3f0a0c2e92cab</li>
        <li>Upwork Job ID: 1760080983071113216</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by NikkiWines** [comment] 2024-02-20 23:20
@francoisl iirc we're having a couple different video player issues at the moment, do you know if this is a new one?

**Comment by francoisl** [comment] 2024-02-20 23:48
Looks like a new one, yes.

cc @kowczarz

**Comment by Tony-MK** [comment] 2024-02-20 23:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Public room - Unable to play video after navigating to LHN and back to the public room

### What is the root cause of that problem?

The `reportID` is retrieved from the `parseReportRouteParams` function using the `activeRoute`. 

https://github.com/Expensify/App/blob/ea0c07b7671bdcde20485c48f841212d7f1a925b/src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx#L25-L26

The first time the `activeRoute` is `r/4098419659819887`.

https://github.com/Expensify/App/blob/ea0c07b7671bdcde20485c48f841212d7f1a925b/src/components/HTMLEngineProvider/HTMLRenderers/VideoRenderer.tsx#L37-L38

However, on the return visit, `reportID` is an empty string because the `activeRoute` is more complicated and doesn't parse the `reportID` from the route properly. 

Hence, the report will not be found.

### What changes do you think we should make in order to solve the problem?


Instead of using the `parseReportRouteParams` function, we can use the `useCurrentReportID` hook to get the `reportID`.

### What alternative solutions did you explore? (Optional)

Improve the `parseReportRouteParams` function to parse the `reportID` properly with different `activeRoute` params.

**Comment by bernhardoj** [comment] 2024-02-21 02:32
Dupe of https://github.com/Expensify/App/issues/36899

**Comment by NikkiWines** [comment] 2024-02-21 03:19
Oh, nice catch @bernhardoj - closing this in favor of that issue

**Closed by NikkiWines** 2024-02-21 03:19 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug
