### ISSUE TITLE
BUG:  The composer input is not focused after closing the user details page reported by @mollfpr 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11781] opened 2022-10-12 22:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat and click the composer input
2. Click on the user profile
3. Close the profile page

## Expected Result:
The composer input should be focused after closing the profile page

## Actual Result:
The composer is not focused after closing the profile page
## Workaround:
unknown
## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:**  1.2.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195459177-6e5ad91f-9e5f-4d6b-ab22-8390754b98d7.MP4

https://user-images.githubusercontent.com/43996225/195459189-210ac871-cbb0-4ea0-9b05-d940956bbf63.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mollfpr 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665588042546159

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by CortneyOfstad** [comment] 2022-10-13 11:56
@kavimuru I reviewed the videos and to be honest, I don't see the bug. Can you provide a bit more context into the issue? From what I can see the system is moving smoothly and I don't see this as a bug per se.

**Comment by kavimuru** [comment] 2022-10-13 14:21
@CortneyOfstad At the 0:04 second in the video cursor is not autofocused in the message compose field. Not reproduced in web.

https://user-images.githubusercontent.com/43996225/195622946-94b92c30-82fa-441a-95c8-2480dc121b86.mp4

**Comment by CortneyOfstad** [comment] 2022-10-13 14:27
Thanks for the clarification. I'm not sure this is super high priority, as it seems pretty clear to me still, but going to get additional eyes on this just in case.

**Comment by jasperhuangg** [comment] 2022-10-13 17:11
Yeah, not sure if this is actually a bug since this behavior is expected. This isn't a regression, closing

**Closed by jasperhuangg** 2022-10-13 17:11 UTC
Labels: Engineering, Daily, Improvement
