### ISSUE TITLE
Chat is being created erroneously with a phone number that isn't tied to a user

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14691] opened 2023-01-31 15:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open search
3. Search for random valid number outside of your country (number used in test: +17243748910)
4. Click on user in search result

## Expected Result:
App should allow to start chat with that number

## Actual Result:
App displays 'An error occurred using the phone number provided, use your email address instead' error and does not allow to start chat with that number

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.62-1
**Reproducible in staging?:**  y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/215804962-632ab3b7-b46f-4d34-990c-ccd7db4b1a41.mp4

https://user-images.githubusercontent.com/43996225/215804987-e4014522-93b7-4464-a867-9524b47d7a92.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675060631104939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by maddylewis** [comment] 2023-02-01 15:43
waiting for alberto confirm question asked here - https://expensify.slack.com/archives/C049HHMV9SM/p1675112925631049?thread_ts=1675060631.104939&cid=C049HHMV9SM

**Comment by maddylewis** [comment] 2023-02-06 18:20
i reached out directly to alberto to for clarification ^^^

will follow up once I've heard back :)

**Comment by maddylewis** [comment] 2023-02-07 19:47
It sounds like we're able to create chats with random phone numbers (regardless of country code) and then an error populates. 

it seems like if a phone number isn't tied to a user, an error should be thrown first and a chat should not be created.

**Comment by maddylewis** [comment] 2023-02-07 19:55
i will follow up on this slack convo to confirm a proposal before adding the `external` label - https://expensify.slack.com/archives/C049HHMV9SM/p1675060631104939

**Comment by maddylewis** [comment] 2023-02-08 18:20
so backing up a bit - i dont think this is actually a bug. its expected to not be able to create a chat with a random phone number that isn't tied to a user.

**Comment by maddylewis** [comment] 2023-02-08 18:21
ill close this out since this is expected behavior.

**Closed by maddylewis** 2023-02-08 18:21 UTC
Labels: Daily, Bug
