### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Chat - App does not replace # on selection of mention

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29187] opened 2023-10-10 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696496817615989

## Action Performed:
Precondition: User should know a user with # in display name
1. Open the app
2. Open any report
3. Write '@#' and select the user in result
4. Observe that app does not replace # with result

## Expected Result:
 On selecting user from mention result, app should replace search term with result

## Actual Result:
 On selecting user from mention result, app does not replace search term with result if term is '#'

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/95d001f9-c301-45a2-8473-f6bd0ac09327

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/078344ba-a8c8-414e-9457-c1604eded24f

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/7f326775-ed5c-4c5e-9a58-7821e86a2e9d

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/a06a1255-f490-43f3-b703-a62f47d56a5a

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/517489f2-9883-4e54-96c1-8acc1e713a65

</details>

<details>
<summary>MacOS: Desktop</summary>

  

https://github.com/Expensify/App/assets/93399543/84866951-b88a-4add-aa65-40452e87f824

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0159ee5a631ff4f0b0</li>
        <li>Upwork Job ID: 1711736982382366720</li>
        <li>Last Price Increase: 2023-11-01</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27547155</li>
<li>abzokhattab | Contributor | 27547156</li>
<li>dhanashree-sawant | Reporter | 27547157</li>
</ul></li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2023-10-10 13:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The # is not replaced on the selection of the mention

### What is the root cause of that problem?

The root cause of this problem is the presence of the `|[#*0-9]\uFE0F?\u20E3` part in the regex pattern. This part prematurely terminates the match when encountering the '#' character, leading to incomplete matches.

https://github.com/Expensify/App/blob/4078503d8e2468a3f0c54fc37af0f888ed2abf41/src/CONST.ts#L1258-L1260

### What changes do you think we should make in order to solve the problem?

Modify the regex to :

```javascript
/^@[^\n\r]*?(?=$|[\s,/?"{}[\]()&^%\\;`$=<>!*\p{Extended_Pictographic}\u200d\u{1f1e6}-\u{1f1ff}\u{1f3fb}-\u{1f3ff}\u{e0020}-\u{e007f}\u20E3\uFE0F]|#[#*0-9]\uFE0F?\u20E3)/u;
```

This pattern will match mentions that include emojis and hashtags while avoiding the issue of prematurely stopping at #. It retains the existing structure without causing any breaking changes to the existing functionality

### POC:

https://github.com/Expensify/App/assets/59809993/632f03ca-1779-4712-b909-1f698092ed19

**Comment by conorpendergrast** [comment] 2023-10-16 12:48
Still waiting for https://github.com/Expensify/App/pull/29239

**Comment by abzokhattab** [comment] 2023-10-18 12:58
Proposal is [updated ](https://github.com/Expensify/App/issues/29187#issuecomment-1755441866) please review and let me know

**Comment by abzokhattab** [comment] 2023-10-23 00:19
okay I thought we wanted to cover only the hashtag, but in this case, we need to remove the SPECIAL_CHAR matching completely.. in this case, the space or the new line would be the only characters that stop the matching 

POC:

<img width="744" alt="image" src="https://github.com/Expensify/App/assets/59809993/c6969264-45b2-4fb4-b496-e62feaa9c207">

**Comment by conorpendergrast** [comment] 2023-10-26 11:42
Any more thoughts here? Looking at the blame I can see that we added up a few reasons to use `MENTION_REPLACER` in the past (before we [consolidated](https://github.com/Expensify/App/pull/29239) to `SPECIAL_CHAR` and after)

https://github.com/Expensify/App/pull/18469
https://github.com/Expensify/App/pull/19004

From a scan of that, it looks like we may end up with regressions by removing `SPECIAL_CHAR` entirely, but I'd like another perspective on that!

**Comment by abzokhattab** [comment] 2023-10-26 11:43
looking more into it today

**Comment by abzokhattab** [comment] 2023-10-27 22:42
Okay again so the problem that we will have if we decide to remove the `SPECIAL_CHAR` is this issue https://github.com/Expensify/App/issues/18867 .. so basically if you type `@ab/` and you select a mention that contains only `ab` the regex would remove the `/` as well when selecting a mention which shouldn't happen..


so after having a deep look into the issue i found that there is no need to use the `MENTION_REPLACER` in deciding the comment after the mention .. instead we can use the index of the last char of `suggestionValues.mentionPrefix` and fetch the string after it 

i think it is easier to illustrate it by providing the code changes, so we should change this: 

https://github.com/Expensify/App/blob/49bc03bca208ac6503291640215104ece3098751/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L84

To:

```js
            const commentAfterAtSignWithMentionRemoved = value.slice(suggestionValues.atSignIndex).substring(suggestionValues.atSignIndex + suggestionValues.mentionPrefix.length + 1);
```
 
and of course, remove the `MENTION_REPLACER` from the `const.ts` file

POC: 


https://github.com/Expensify/App/assets/59809993/834ac7e1-e4df-449c-af36-df7f50ea0f73


Please let me know what you think @conorpendergrast  @fedirjh

**Comment by ShogunFire** [comment] 2023-10-28 23:27
Before we were only stopping the match for mention ast whitespace and newline.

The issue where we decided to stop at special characters was here: https://github.com/Expensify/App/issues/19027 but we made the change in this PR : https://github.com/Expensify/App/pull/19004 and this PR: https://github.com/Expensify/App/pull/29239

**Comment by conorpendergrast** [comment] 2023-10-31 13:33
From a UX perspective I think that video seems fine. @fedirjh what do you think?

**Comment by anzokhattab** [comment] 2023-10-31 14:31
Awesome.. gonna update my original proposal then we can move forward

**Comment by abzokhattab** [comment] 2023-10-31 14:33
Awesome gonna update my original proposal then we can move forward

**Comment by abzokhattab** [comment] 2023-10-31 19:27
Proposal is updated

**Comment by abzokhattab** [comment] 2023-11-05 12:18
A kindly reminder on this

**Comment by marcochavezf** [comment] 2023-11-06 20:18
Thanks for the review @fedirjh, the proposed solution looks good. Assigning @abzokhattab 🚀

**Comment by abzokhattab** [comment] 2023-11-08 17:29
Kindly reminder, @fedirjh  @conorpendergrast  ... PR is ready

**Comment by conorpendergrast** [comment] 2023-11-23 21:11
Payouts due:
- [ ] Issue Reporter: $50 @dhanashree-sawant - [offer](https://www.upwork.com/nx/wm/offer/27547157) (Reporter)
- [ ] Contributor+: $500 @fedirjh - [offer](https://www.upwork.com/nx/wm/offer/27547155)
- [ ] Contributor: $500 @abzokhattab - [offer](https://www.upwork.com/nx/wm/offer/27547156) (Contributor)

Upwork job is [here](https:://www.upwork.com/jobs/~0159ee5a631ff4f0b0).

**Comment by conorpendergrast** [comment] 2023-11-23 21:14
All paid now, and I agree with you @fedirjh for the C+ checklist. Closing out!

**Closed by conorpendergrast** 2023-11-23 21:14 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
