### ISSUE TITLE
[HOLD for 49012][$250] Chat - Text+video pasted content shown in horizontal with blank preview

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49469] opened 2024-09-19 14:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 9.0.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open a chat
3. Enter a text + upload a video
4. Send the message
5. Note video briefly in vertical position and changed to horizontal and video preview can be seen
6. Long press the message and select copy to clipboard
7. Paste and send the message
8. Note video now displayed in displayed position with blank preview

## Expected Result:
Text+video pasted content must be shown as original content.

## Actual Result:
Text+video pasted content shown in horizontal with blank preview.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/785709a9-08a8-48be-974a-7445845a2955

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021837224206540526510</li>
        <li>Upwork Job ID: 1837224206540526510</li>
        <li>Last Price Increase: 2024-09-20</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ntdiary</details>

**Comment by IuliiaHerets** [comment] 2024-09-19 14:22
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-09-20 20:15
I can reproduce this with the steps in the OP - I'm not sure if this is a internal issue so sending it to external first.

**Comment by Kalydosos** [comment] 2024-09-22 23:02
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
copied and pasted Text+video comment is displayed with blank preview.

### What is the root cause of that problem?
There is a bug in the function **isReportActionAttachment**  of **ReportActionsUtils.ts** which allows to "copy to clipboard" a comment with attachment (with text or attachment only). It make sense not to allow copying such comments as the attachments are already loaded server side, then such comments could only be referenced ("copy link") or edited (by their authors only) as show in the pictures below

![no_copy_attachmentcomment3](https://github.com/user-attachments/assets/d9b530b1-1621-4b7a-8308-e4333edbda32)
![no_copy_attachmentcomment2](https://github.com/user-attachments/assets/b413af0b-d43e-4b4d-a61d-af653bb276cc)
![no_copy_attachmentcomment1](https://github.com/user-attachments/assets/2e3b3747-f6c8-45f6-940b-82d2f093a07c)

To fix the problem, the following line must be changed from

https://github.com/Expensify/App/blob/934821fa827d761d9092aed8001bc92524ed135e/src/libs/ReportActionsUtils.ts#L1081

to

> return !!reportAction.isAttachmentWithText||!!reportAction.isAttachmentOnly;

which fixes the issue

### RESULT
Only authors can edit their comments made of text+attachment. Otherwise such comments can only be referenced by links. See image below. Only texts can be copied to clipboard

![no_copy_attachmentcomment5](https://github.com/user-attachments/assets/02af24c1-f7cb-4801-bf86-3b0dc3a10e40)



**About the horizontal or vertical display of the attachment** (specially videos thumbnails), it depends on the aspect ratio of the video itself as show in the image below where one video thumbnail displays horizontally and another vertically 

![attachments_thumbnails_displays](https://github.com/user-attachments/assets/b5964f04-8eaf-410d-bc72-0baeea279585)


### What alternative solutions did you explore? (Optional)

None

**Comment by Christinadobrzyn** [comment] 2024-09-23 20:25
@ntdiary thanks for the heads up! Feel free to let me know the results of the Slack convo! I can assign whoever is chosen

**Comment by Christinadobrzyn** [comment] 2024-09-24 16:05
Based on the Slack convo - this might get fixed with https://github.com/Expensify/App/issues/49012. Adding a hold to this issue in favour of https://github.com/Expensify/App/issues/49012.

**Comment by Christinadobrzyn** [comment] 2024-09-24 16:06
I'm going to be ooo for the rest of the week but it looks like 49012 is just getting started so going to move this to weekly for the time being.

**Comment by Christinadobrzyn** [comment] 2024-09-30 04:47
Thanks @Kalydosos! 

@ntdiary can you review @Kalydosos's comment and let us know what you think? https://github.com/Expensify/App/issues/49469#issuecomment-2374441891

**Comment by Christinadobrzyn** [comment] 2024-09-30 04:47
Thanks @Kalydosos! 

@ntdiary can you review @Kalydosos's comment and let us know what you think we should do based on that? https://github.com/Expensify/App/issues/49469#issuecomment-2374441891

**Comment by Christinadobrzyn** [comment] 2024-10-01 01:42
Sounds good @ntdiary - asking the team for some direction with this one - https://expensify.slack.com/archives/C036QM0SLJK/p1727746940327659

**Comment by Kalydosos** [comment] 2024-10-01 17:29
@Christinadobrzyn @ntdiary just to add something regarding the feature of copying a text+attachment comment to clipboard and pasting it as @luliiaHerets did, i tried to implement that feature to see if it was possible and i even succeeded doing so (having the thumbnail of the copied attachment) but in the case of a video, when you click "play" on the copy, it's the original video from the original comment that plays instead. Which is normal as both objects are the "same" in the thread and reference the same resource server side. So it really seems that copy/pasting text+attachment was not intented as a feature.

**Comment by Christinadobrzyn** [comment] 2024-10-02 01:13
Thanks for the insight and testing @Kalydosos! Talking this over with the team, we're going to close without action. This best fits the vip-vsb project which has been tabled. Thanks!

**Closed by Christinadobrzyn** 2024-10-02 01:13 UTC
Labels: External, Daily, Help Wanted, Bug
