### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Task - Chat messages are out of order after reassigning task, sometimes beginning of chat is duplicated

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#38439] opened 2024-03-16 14:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.53-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log into an account where you have multiple chats
2. Navigate to a user from the recent contacts
3. Tap the "+" > Assign task
4. Enter the task name and proceed to the next screen
5. Tap "Assignee" and search for a user you have not messaged yet
6. Assign the task to that user
6. Tap the "Assignee" again and reassign the task to the same user you are sharing it with
7. Create the task

## Expected Result:
The task is displayed as the last message in the report

## Actual Result:
A duplicated beginning of the report is displayed, sometimes task is shown as the first message

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/d49baaf6-21e3-43fd-9ca5-40d449985c91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01479bcdfebb5e0089</li>
        <li>Upwork Job ID: 1770147572055535616</li>
        <li>Last Price Increase: 2024-03-26</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-16 14:55
@sakluger I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-16 14:56
We think that this bug might be related to #vip-vsb

**Comment by ahmedGaber93** [comment] 2024-03-17 02:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task - Beginning of chat shown after reassigning task from user you have no chat to recent user
### What is the root cause of that problem?
when we select assignee we call `setAssigneeChatReport`.

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/libs/actions/Task.ts#L660
which merge the value with the old value.
https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/libs/actions/Task.ts#L623-L625

the root cause is the merge leed to  merge `ReportUtils.buildOptimisticChatReport`  for new user with `ReportUtils.getChatByParticipants` for user chated before and this add optimistic fields like `isOptimisticReport` to the old report


### What changes do you think we should make in order to solve the problem?
we need to reset the old value of `assigneeChatReport` before merge the new value here.
https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/libs/actions/Task.ts#L623-L625

we can do that by set it to null then set to the new value.
### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-03-18 08:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A duplicated beginning of the report is displayed, sometimes task is shown as the first message

### What is the root cause of that problem?

When we select an assignee that is a new user, we create an optimistic report here and set it to `assigneeChatReport`. After we re-select a recent contact, another chat report is set to `assigneeChatReport` but other fields like `isOptimisticReport`, `pendingFields` are in-correct because we merge from old assignee report.

https://github.com/Expensify/App/blob/c915e7f026eddc710dd01a38abc3afc9334002ae/src/libs/actions/Task.ts#L660

And then a created action is created here.
https://github.com/Expensify/App/blob/c915e7f026eddc710dd01a38abc3afc9334002ae/src/libs/ReportUtils.ts#L4813-L4814
### What changes do you think we should make in order to solve the problem?
Instead of storing assignReport in task data, we can store the assigneeChatReportID which is the ID of chat report and then get the correct data from Onyx to check here.


https://github.com/Expensify/App/blob/c915e7f026eddc710dd01a38abc3afc9334002ae/src/libs/ReportUtils.ts#L4813-L4814

I checked all use of `task.assigneeChatReport` and saw that it's only used when we create the task. So we can only store the reportID of chat report and then get the report data from Onyx correctly.
### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2024-03-19 17:56
Updated the issue title and description for clarify.

**Comment by hungvu193** [comment] 2024-03-20 02:14
Reviewing today

**Comment by hungvu193** [comment] 2024-03-20 09:36
I'm not able to reproduce this one on latest main :/

https://github.com/Expensify/App/assets/16502320/6e9386b9-459a-4933-9cf9-e383c03bd5cc

**Comment by nkdengineer** [comment] 2024-03-20 15:28
> Tap "Assignee" and search for a user you have not messaged yet

@hungvu193 You should search and select a new user first that is important step to reproduce this bug.

**Comment by hungvu193** [comment] 2024-03-21 00:43
> > Tap "Assignee" and search for a user you have not messaged yet
> 
> @hungvu193 You should search and select a new user first that is important step to reproduce this bug.

Thank you, I'll try to reproduce today

**Comment by hungvu193** [comment] 2024-03-23 15:47
Ok, I can reproduce.

https://github.com/Expensify/App/assets/16502320/fa7e5fd7-cb1f-4083-b62a-2e9e61160353

But I couldn't reproduce the issue once it already happened with that report. Here's the steps to test:
1. Open the app and log into an account where you have multiple chats
2. Navigate to a user from the recent contacts
3. Tap the "+" > Assign task
4. Enter the task name and proceed to the next screen
5. Tap "Assignee" and search for a user you have not messaged yet
6. Assign the task to that user
7. Tap the "Assignee" again and reassign the task to the same user you are sharing it with
8. Create the task => Saw the issue
9. Reload the app
10. Repeat step 3 to 8.

My question is can you guys still the see issue with my above reproduction steps? If not, why did it only happen the first time, since both proposals pointed out that we're using wrong optimistic data. Thank you.

**Comment by ahmedGaber93** [comment] 2024-03-24 04:04
@hungvu193 
> why did it only happen the first time

https://github.com/Expensify/App/blob/e40fba13be231a88c76f789ac94c4a65ec34f280/src/libs/actions/Task.ts#L636-L638
this because we build optimistic chat report only if `chatReport` gotten by `getChatByParticipants` not found.
And after that the `chatReport = ReportUtils.getChatByParticipants` is already exist, so no need to build optimistic chat again

**Comment by nkdengineer** [comment] 2024-03-25 09:21
@hungvu193 After the first time, `isOptimisticReport` of the chat report is updated to `false` and then if we repeat the step again, `isOptimisticReport` will be updated correctly in `assigneeChatReport` because `isOptimisticReport` is updated correct.


https://github.com/Expensify/App/blob/eba217fcdba3cdfae0fdfadf102fc3b73d3c9129/src/libs/ReportUtils.ts#L5003

**Comment by hungvu193** [comment] 2024-03-27 05:16
Thank you both and sorry for late reply, I was sick last few days, but it's close to select proposal.

**Comment by hungvu193** [comment] 2024-03-27 21:29
@nkdengineer 's alternative proposal [here](https://github.com/Expensify/App/issues/38439#issuecomment-2003151319) looks good to me. It has correct RCA and solution 🎀 👀 🎀  C+ reviewed.

Thanks @ahmedGaber93, your solution worked but I prefer correct falsely fields rather than do another merge to update task value.

**Comment by ahmedGaber93** [comment] 2024-03-27 21:52
@hungvu193 I think reverse the attribute that cause the issue will solve the current issue, but other similar issues may arise in the future during merge.
My proposal try to fix the root cause, and prevent similar issues in the future.

**Comment by hungvu193** [comment] 2024-03-27 21:59
> @hungvu193 I think reverse the attribute that cause the issue will solve the current issue, but other similar issues may arise in the future during merge. My proposal try to fix the root cause, and prevent similar issues in the future.

As I said earlier, the issue here that we've been using wrong optimistic data, so I expect a solution that aims to fix the optimistic data rather than reset it, then merge it. Your solution will always set task to null for every `setAssigneeValue` called, I don' think that's a good idea. Anyway, that's just my opinion, I'll let @srikarparsi decide. Thanks for your patience 😄

**Comment by ahmedGaber93** [comment] 2024-03-27 23:34
> Your solution will always set task to null for every setAssigneeValue called, I don' think that's a good idea.

No, it will set only `assigneeChatReport` not `task` to null while replace it from optimistic report (not exist chat) to exist chat report.
[here](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Report.ts#L1097) similar case, we set the optimistic report to null before replace it with the real value.
Thanks for your patience.

**Comment by hungvu193** [comment] 2024-03-28 00:26
> > Your solution will always set task to null for every setAssigneeValue called, I don' think that's a good idea.
> 
> No, it will set only `assigneeChatReport` not `task` to null while replace it from optimistic report (not exist chat) to exist chat report. [here](https://github.com/Expensify/App/blob/d8361eee3486ccb5472060f2af7655e96461471e/src/libs/actions/Report.ts#L1097) similar case, we set the optimistic report to null before replace it with the real value. Thanks for your patience.

I got your point here, but if you take a look, you can see we used `Onyx.set` there, which to deleted the optimistic data and we also recommended to use `set` when you want to delete data completely, but we can't use `set` here, since we shouldn't combine `merge` and `set` together. Also `merge` are batched, so it will cause another re-render.

Also the case you mentioned is a little different with this issue, in [here](https://github.com/Expensify/App/blob/e542ba7c2d9e216c2cd401de0de8ed225fff4a7b/src/libs/actions/Report.ts#L1103) we already knew that our current optimistic data was wrong so we deleted it and loaded the server response later when we navigated user to that report. In our case, we have valid chat report, we just need to adjust to make sure `isOptimisticReport` is updated correctly.

**Comment by ahmedGaber93** [comment] 2024-03-28 00:50
you are right about `Onyx.set`there.

But here
> In our case, we have valid chat report, we just need to adjust to make sure isOptimisticReport is updated correctly.

I think in our case we merge two different reports, the first for `userA and is optimistic` and the second is for `userB one is real`.
and here we use `Onyx.merge` which may keep attributes from one of them into the other, I know we can't use `Onyx.set` in this case, so my proposal was to merge `assigneeChatReport` to null then merge second report.

In any case, the decision is yours and the internal developer's.
Thanks!

**Comment by srikarparsi** [comment] 2024-03-28 01:06
Hey, is this issue still reproducible? Am I missing a step?

https://github.com/Expensify/App/assets/48188732/483c603e-eeef-4306-9a3c-620d25de2ae8

**Comment by hungvu193** [comment] 2024-03-28 01:15
I still can reproduce

https://github.com/Expensify/App/assets/16502320/b66e162a-a424-404e-852d-a55796680bfe


Tips: I used high traffic account and choose a random account on the list that I've never chatted before

**Comment by ahmedGaber93** [comment] 2024-03-28 01:23
I also can reproduce in the last main.

https://github.com/Expensify/App/assets/41129870/ba6bcf04-55be-4944-969b-3b2bfd3c85e0

**Comment by nkdengineer** [comment] 2024-03-28 02:42
In this case, the report data in Onyx is correctly, we only have the problem with `assigneeChatReport`.  it's used to create new created `reportAction` if the report is new report and doesn't update anything to report data so we only need to verify that this will display correct in assign task flow and the logic to create report action will be correct.

To not have any concern about saving `assigneeChatReport`, we also can do with my main solution to only store `assigneeChatReportID` and then get the correct data in Onyx.

**Comment by srikarparsi** [comment] 2024-03-28 05:54
Cool just looked over everything. I also like @nkdengineer alternate solution since it's more straightforward and is better for performance without the double merge.

**Comment by nkdengineer** [comment] 2024-03-28 09:27
@hungvu193 The PR is [here](https://github.com/Expensify/App/pull/39152).

**Comment by sakluger** [comment] 2024-04-15 16:19
Summarizing payment on this issue:

Contributor: @nkdengineer $500, sent offer via Upwork (https://www.upwork.com/nx/wm/offer/101873781)
Contributor+: @hungvu193 $500, paid via Upwork

@hungvu193 could you please complete the BZ checklist?

**Comment by sakluger** [comment] 2024-04-15 19:14
Paid @nkdengineer, just waiting on the checklist now.

**Comment by hungvu193** [comment] 2024-04-16 01:51
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/22778
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/22778/files#r1566611957
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: No

This is an edge case, so I don't think we need regression test for this one.

**Comment by sakluger** [comment] 2024-04-16 22:25
Thanks!

**Closed by sakluger** 2024-04-16 22:25 UTC
Labels: External, Daily, Awaiting Payment, Bug
