### ISSUE TITLE
[HOLD for payment 2023-07-28] [$250] Migrate RadioButtons.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16194] opened 2023-03-20 08:42 UTC
### Filenames
- [ ] [src/components/RadioButtons.js](https://github.com/Expensify/App/blob/main/src/components/RadioButtons.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0167493f0dce0f663f</li>
        <li>Upwork Job ID: 1678837331340034048</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by dostongulmatov** [comment] 2023-06-06 10:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Migrate BaseOptionsList.js to function component
### What is the root cause of that problem?
No root cause, just refactoring 
### What changes do you think we should make in order to solve the problem?
We should update https://github.com/Expensify/App/blob/main/src/components/RadioButtons.js into functional component

**Comment by s-alves10** [comment] 2023-06-06 11:06
I'd love to work on this.

**Comment by dayana7204** [comment] 2023-06-27 19:29
I am ready to work on this ticket. :)

**Comment by dayana7204** [comment] 2023-06-27 19:33
Contributor details
Your Expensify account email: yavorskadayana@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01be516fe8babc58d6

**Comment by olexyt** [comment] 2023-07-07 14:05
I can work on this issue.

**Comment by alexxxwork** [comment] 2023-07-11 18:45
I would love to work on this issue

**Comment by kmwamasali** [comment] 2023-07-11 18:49
would like to work on this

**Comment by yh-0218** [comment] 2023-07-11 18:49
I can work on this task. Thanks.

**Comment by crazy-coding** [comment] 2023-07-11 18:49
I'd love to work on this.

**Comment by disha-np** [comment] 2023-07-11 18:49
I'd like to work on this

**Comment by Talha345** [comment] 2023-07-11 18:52
I'd love to work on this.

**Comment by Vadym-33** [comment] 2023-07-11 18:54
I hope to work on this task.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 18:54
I'm able to work on this if needed!

**Comment by neonbhai** [comment] 2023-07-11 18:55
I can work on this

**Comment by KrAbhas** [comment] 2023-07-11 19:02
I would like to work on this

**Comment by vdem0115** [comment] 2023-07-11 19:03
I can work on this.

**Comment by Talha345** [comment] 2023-07-11 19:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `RadioButtons.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by ishpaul777** [comment] 2023-07-11 20:54
I would like to work on this..

**Comment by to-ai** [comment] 2023-07-11 21:21
I am able to work on this task.

**Comment by mkhutornyi** [comment] 2023-07-11 21:33
I'd like to work on this.

**Comment by PhantomOz** [comment] 2023-07-11 23:59
> ####Here is my proposal for how I will fix this issue:

> * I will use the React Hooks API to convert the class component to a function component. Specifically, I will use the useState hook to manage the state values, the useRef hook to create and access the refs, and the useEffect hook to replicate the componentDidMount behavior.
> * I will also use the React.memo function to wrap the function component and optimize its rendering performance. This will ensure that the component only re-renders when its props change.
> * I will test the refactored component on all platforms (iOS, Android, web, desktop) to make sure that it works as expected and does not introduce any regressions or breaking changes.

**Comment by s77rt** [comment] 2023-07-12 14:43
Thank you all for your interest here.

- @rayane-djouah Skipping since you are "assigned" to another migration ([here](https://github.com/Expensify/App/issues/16172))
- @alexxxwork Skipping since you should get assigned to another functional migration ([here](https://github.com/Expensify/App/issues/16191#issuecomment-1632645174))
- @payal-lathidadiya Let's do it! :rocket: 

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by robertjchen** [comment] 2023-07-12 14:56
Sounds good, let's do it!

**Comment by payal-lathidadiya** [comment] 2023-07-12 19:33
[PR](https://github.com/Expensify/App/pull/22770) is up for review

cc: @s77rt @robertjchen

**Comment by s77rt** [comment] 2023-07-19 22:30
Not overdue. PR is merged.

**Comment by greg-schroeder** [comment] 2023-07-28 10:16
Assigned: July 12th
Merged: July 19th

Payments:

@payal-lathidadiya - C = $250
@s77rt - C+ = $250

**Comment by greg-schroeder** [comment] 2023-07-28 10:22
Please accept the offer @payal-lathidadiya and you'll be paid accordingly! All set to go here otherwise.

**Closed by greg-schroeder** 2023-07-28 10:22 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment

**Comment by payal-lathidadiya** [comment] 2023-07-28 15:38
accepted, thank you
