### ISSUE TITLE
[$1000] Web - For new user, blank invite members page is displayed even though it has few chats available

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25402] opened 2023-08-17 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Search for new unique user (ensure that you have access to that email) and click on search
3. From different device, sign in with searched user in step 2
4. Observe that it has chat with user A
5. Open search and observe that user  A is visible without any search
6. Open settings->workspaces->new workspace->members
7. Click on invite and observe that invite page does not have user A in recent contacts

## Expected Result:
App should display contacts to which we have chats on invite members page

## Actual Result:
App does not display contacts for new user on invite members page even if few users has already initiated chat with the new user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/437f87d0-cd15-425f-b14a-ec6230a0c7dc

https://github.com/Expensify/App/assets/115492554/ff316f3f-2124-4e5f-8eb3-88112eb9c3f1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691317653758699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e57558bbcf4ebb80</li>
        <li>Upwork Job ID: 1695130525911900160</li>
        <li>Last Price Increase: 2023-09-01</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-17 16:01
Temporarily we filter the options with only the users for who we have the login and I might be wrong but I think to have the login the other user has to send a message which doesn't seem to be the case in the video

**Comment by ShogunFire** [comment] 2023-08-17 16:02
Should we do the same for the search ?

**Comment by dylanexpensify** [comment] 2023-08-21 08:42
reviewing today!

**Comment by dylanexpensify** [comment] 2023-08-22 21:01
reviewing tomorrow! Got caught up with higher priorities today! Bumping the message

**Comment by dylanexpensify** [comment] 2023-08-24 10:42
Reviewing now!

**Comment by Santhosh-Sellavel** [comment] 2023-08-25 18:13
@dhanashree-sawant is this reproducible now?

**Comment by lmeullibre** [comment] 2023-08-26 00:23
## Proposal
### Problem Statement:
When a user opens the drawer to view workspace members in our application, only the admin information is displayed, regardless of the actual number of users his/her account has connections to. 

### Root Cause:
The issue arises from the application fetching workspace member data from the IndexedDB of our browser using the endpoint `api?command=OpenWorkspaceMembersPage`. This endpoint internally accesses a specific record, denoted as `"policyMembers_${policy_id}"`, in the IndexedDB to retrieve member details. Currently, this record only contains the admin information, resulting in only the admin being displayed when querying for workspace members.

For clarity, on my local machine I received: `15455180: {role: 'admin'}`. As we can see, is missing the other users I have a connection with (reports).

### Proposed Solution:
To ensure that all members of a workspace are accurately represented in the drawer, we should regularly update the database record (`"policyMembers_${policy_id}"`). Specifically, each time a new chat is created from the main page, the corresponding record should be updated to reflect any changes in workspace membership.

A suitable location to implement this update is within the openReport function located in `Report.js`. By making sure that the `policyMembers_${policy_id} `record is refreshed every time this function runs, we can ensure the latest member information is available when accessing the workspace members drawer.

By manually modifying our `"policyMembers_${policy_id}"` by appending a new user, we can see it's working:
<img width="399" alt="image" src="https://github.com/Expensify/App/assets/32779308/63d33c20-2e0e-49cd-90d5-577d7e8c60c3">

**Comment by lmeullibre** [comment] 2023-08-26 00:26
Contributor details
Your Expensify account email: sergimartinezrodriguez@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0179522c29b19e1e1c

**Comment by dylanexpensify** [comment] 2023-08-28 11:10
updating today!

**Comment by Santhosh-Sellavel** [comment] 2023-08-28 21:09
Seems like a Backend issue

**Comment by dylanexpensify** [comment] 2023-08-29 09:36
Hmm, having a hard time reproing, @Santhosh-Sellavel can you repro?

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 22:00
Yes can reproduce, but not sure about what's wrong here and what needs to be fixed.

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 22:03
Here are the facts,

1. User A just created a chat with User B who didn't even signup i.e using email
2. User B Finds, User A's contact on the search option for chat
3.  User B Did not find, User A's contact on the search option for workspace invite.
4.  User B Did not Finds, User A's chat on the LHN

**Comment by lmeullibre** [comment] 2023-08-29 22:20
It's a bug, a backend one. The invite drawer from user B should contain User A as a potential workspace member on the list. However the Client only lists users which has the attribute `login` on them, and since the backend is returning the connections without this attribute, the list appears empty. It can be patched quickly from the Client but it should be better fixed on the Server.

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 22:23
@dylanexpensify Can you assign a internal engineer here lets discuss sort things out here, thanks!

**Comment by dylanexpensify** [comment] 2023-08-31 09:01
Done!

**Comment by hayata-suenaga** [comment] 2023-09-01 21:21
@Santhosh-Sellavel if you could, could you provide a summary of the issue and what kind of changes are required on the backend side?

**Comment by lmeullibre** [comment] 2023-09-03 19:45
@hayata-suenaga as per my research, I found the endpoint `http://localhost:8082/api?command=OpenApp` reponse is missing the `login` attribute. It should be fixed by just adding it.

**Comment by dylanexpensify** [comment] 2023-09-04 10:18
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi!

**Comment by hayata-suenaga** [comment] 2023-09-04 18:32
I feel like this issue is related to the secure login project. [Asked](https://expensify.slack.com/archives/C03TQ48KC/p1693852290649199) involved engineers about this issue on slack.

**Comment by Santhosh-Sellavel** [comment] 2023-09-07 18:31
@hayata-suenaga Unassigning if C+ assistance required please re-assign a new C+ by adding external label here thanks!

**Comment by hayata-suenaga** [comment] 2023-09-07 20:45
[I'm confirming with the engineering team](https://expensify.slack.com/archives/C03TQ48KC/p1694119435545279?thread_ts=1693852290.649199&cid=C03TQ48KC) if this issue is related to the secure login project.

**Comment by hayata-suenaga** [comment] 2023-09-07 21:12
[I confirmed this is an expected behavior](https://github.com/Expensify/App/pull/25991#issuecomment-1709747925). I'm closing this issue 🙇

**Closed by hayata-suenaga** 2023-09-07 21:12 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
