### ISSUE TITLE
[$250] Error message is threw when approving 2 of the 3 expenses which is smartscanning

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#46160] opened 2024-07-25 02:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @youssef-lr 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1721747936002519

## Action Performed:
1. Submit 2 manual expenses in a workspace
2. Add 3rd expense as a receipt
3. Now the preview will be showing as 2 requests, 1 scanning
4. Log in as a approver and approve the report before smartscanning is completed
5. Open the report as a submitter and click on the expense
## Expected Result:
Once the report was approved the smartscanning expense should have been moved to a new report,
## Actual Result:
Instead infinite loading on the receipt and clicking on it error message is thrown
## Workaround:
unknwon
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Logs : https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%228a7c9f9bff440d76-MRS%22)+AND+timestamp:[2024-07-23T14:15:09.937Z+TO+2024-07-23T16:15:09.937Z]&index=logs_expensify-029507

https://github.com/user-attachments/assets/6620ce50-b003-4d64-b75e-2b51f25c4ac5

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5e3b7220258d829</li>
        <li>Upwork Job ID: 1816550074824655118</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by abdulrahuman5196** [comment] 2024-07-30 18:00
Hi, Will check on this tomorrow

**Comment by abdulrahuman5196** [comment] 2024-08-01 15:28
We don't have any proposal to review

**Comment by abdulrahuman5196** [comment] 2024-08-08 12:51
No proposals to review

**Comment by rezkiy37** [comment] 2024-08-13 12:18
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by slafortune** [comment] 2024-08-13 19:59
This is being worked on by an expert contributor, it will also have a 7-day regression period, so I don't feel the need to add another BZ person to this.
I'll be out until 8/21 and will check in on this then.

**Comment by rezkiy37** [comment] 2024-08-14 14:41
I was able to reproduce the bug. I am investigating it.

**Comment by rezkiy37** [comment] 2024-08-16 12:42
I've found a code block that is the root cause of the bug. I am preparing a proposal.

**Comment by rezkiy37** [comment] 2024-08-16 13:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When the admin **pays** (_not approves_) a few expenses along with the receipt, the infinite loading on the receipt and clicking on it an error message is thrown.

### What is the root cause of that problem?

There is a scenario when the app optimistically generates an IOU action. 

https://github.com/Expensify/App/blob/578006fe4d2b7ba13155e795bcef541019aad8ea/src/pages/home/report/ReportActionsView.tsx#L188-L205

Regarding the particular bug, **this happens because of the outdated value** of `childMoneyRequestCount` of `reportPreviewAction`. The app considers that some IOU is missing and optimistically creates the IOU action. 

### What changes do you think we should make in order to solve the problem?

1. The backend should update the `childMoneyRequestCount` of `reportPreviewAction` for **PayMoneyRequest**
2. The backend should send the updated `childMoneyRequestCount` of `reportPreviewAction` via **Pusher** for subscribed users.

So from my investigations, I see that the bug should be fixed on the backend side. I don't know the app's code for fixing it.

<details><summary>Details</summary>

<img width="876" alt="Screenshot 2024-08-16 at 15 51 46" src="https://github.com/user-attachments/assets/7e1af7a7-a297-42cf-a6a8-97f9d0688b0e">
<img width="891" alt="Screenshot 2024-08-16 at 15 56 07" src="https://github.com/user-attachments/assets/f56a8e42-9215-480f-9214-486268c59077">


</details> 

### What alternative solutions did you explore? (Optional) 
N/A

**Comment by abdulrahuman5196** [comment] 2024-08-20 17:04
Hi @slafortune, Seems this could be an backend issue. Can we take this internal?

**Comment by rezkiy37** [comment] 2024-08-23 08:26
@slafortune just a friendly reminder https://github.com/Expensify/App/issues/46160#issuecomment-2299337543.

**Closed** 2024-08-23 17:23 UTC
Labels: External, Daily, Overdue, Bug
