### ISSUE TITLE
[$250] Mac / Firefox - Composer height increases on adding emoji reported by @daraksha-dk

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12745] opened 2022-11-15 19:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat
2. Add emoji to the message composer

## Expected Result: 
Composer height should not increase

## Actual Result : 
Composer height increases

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Mac / Firefox

**Version Number:** `v1.2.28`
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1440" alt="Screen Shot 2022-11-15 at 2 39 27 PM" src="https://user-images.githubusercontent.com/43996225/202011043-4bfef429-36e6-4055-ab0a-dad9c583cab2.png">

https://user-images.githubusercontent.com/43996225/202010791-3747c86d-cda0-47a7-a982-44efb7211f39.mov

**Upwork URL:** https://www.upwork.com/jobs/~01275834e00548fe27
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668510274384019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-11-16 00:10
I can reliably reproduce this on `Web - FireFox` (staging `v1.2.28-0`, using a Mac):

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/16232057/202050730-bed2f594-c587-4a81-9426-ad5b3065d436.png">

Confirmed the issue is not present on `Web - Chrome` & `Web - Safari` nor the desktop app. Confident this is an `external` issue, so adding the label. 

Tagging a few people that were involved in this [recent issue](https://github.com/Expensify/App/issues/10202) for any potential clues. CC: @Santhosh-Sellavel @fedirjh @Julesssss

**Comment by trjExpensify** [comment] 2022-11-16 00:15
Upwork job here: https://www.upwork.com/jobs/~01275834e00548fe27

**Comment by fedirjh** [comment] 2022-11-16 01:29
@trjExpensify a quick look, you can reproduce in the edit input too , the  `scrollHeight` for emojis in Firefox is greater than `lineHeight` this will make number of rows = 2 for first input

<img width="501" alt="Screenshot 2022-11-16 at 2 10 41 AM" src="https://user-images.githubusercontent.com/36869046/202059016-8379b91b-d11c-4e99-befa-793cee6a3509.png">

<img width="704" alt="Screenshot 2022-11-16 at 2 14 22 AM" src="https://user-images.githubusercontent.com/36869046/202059149-24c5cf00-ea07-4de4-a009-da203ed992e5.png">

The solution is to increase `lineHeight` to match the scrollHeight , but make sure to run tests against any changes when editing the compose styles as it is easy to introduce regressions

https://github.com/Expensify/App/blob/12dd4c6ea78e2454938ca9bf720d4e1b64d31ef0/src/styles/styles.js#L1396

```diff
-        lineHeight: 20,
+        lineHeight: 21,
```

### Test Firefox
#### Before
<img width="571" alt="Screenshot 2022-11-16 at 2 28 10 AM" src="https://user-images.githubusercontent.com/36869046/202060911-89a370e8-ba72-4dd3-8898-adcb209adb2a.png">
#### After
<img width="571" alt="Screenshot 2022-11-16 at 2 27 50 AM" src="https://user-images.githubusercontent.com/36869046/202060950-5e453f9a-4aa5-4aed-b833-fa5549fe0512.png">

**Comment by trjExpensify** [comment] 2022-11-16 18:45
@fedirjh are you interested in taking point on this issue?

Also, sounds like we have another firefox issue being reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1668612572582969), this time on mWeb. I've tagged you all for thoughts. If the root cause is the same, let's combine and increase the bounty for tackling both :)

**Comment by fedirjh** [comment] 2022-11-17 01:52
@trjExpensify the root cause is the same for both issues which is `scrollHeight` > `lineHeight`

**Comment by fedirjh** [comment] 2022-11-17 02:20
> Nice find. Would each browser use a different default though?

I think this is related to font-smoothing , each browser uses different values , Firefox mobile doesn't support this feature , FireFox Web implements this property but only works on macOS

**Comment by mollfpr** [comment] 2022-11-17 03:53
I just test the INPUT scroll height on each Mac Chrome, Safari, and Firefox. On Chrome and Safari, the INPUT scroll height remains the same after adding a text or emoji. But on Firefox as @fedirjh is adding an extra `1px` after adding an emoji to the INPUT.

> @trjExpensify the root cause is the same for both issues which is scrollHeight > lineHeight , tested on mWeb , there is extra 2px for both emojis and text

This means that changing the `lineHeight` style value will not resolve the issue in all devices.

> I think this is related to font-smoothing , each browser uses different values , while Firefox mobile doesn't support this feature , FireFox Web implements this property but only works on macOS . check https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth

So if we remove the `font-smoothing` it will resolve the issue?

---

One thing that I found in my Firefox if I set the browser to not allow the pages to choose the fonts, the input is working fine. 
<img width="839" alt="Screen Shot 2022-11-17 at 10 49 06" src="https://user-images.githubusercontent.com/25520267/202350530-23bcd6ad-510f-4037-82b8-18d7c3a11494.png">

https://user-images.githubusercontent.com/25520267/202350901-ecbe37f5-fd78-4e0a-9e35-b99918b51a5f.mov

**Comment by trjExpensify** [comment] 2022-11-17 15:49
^^ isn't that video of the desktop app, not firefox?

**Comment by mollfpr** [comment] 2022-11-17 15:54
It’s from Firefox. I just crop it 😅

**Comment by mollfpr** [comment] 2022-11-17 16:04
Here's another video

https://user-images.githubusercontent.com/25520267/202496683-3f7f75d9-e874-4dbd-a0c1-61eab4b1fb10.mov

**Comment by fedirjh** [comment] 2022-11-17 18:46
> This means that changing the lineHeight style value will not resolve the issue in all devices.

@mollfpr i think this is the only option for for this issue #12745 , we had similar one before on mac #2490

For the 2nd issue we can add the extra px to lineheight when we `getNumberOfLines` 

https://github.com/Expensify/App/blob/12dd4c6ea78e2454938ca9bf720d4e1b64d31ef0/src/libs/ComposerUtils/index.js#L11-L12

```diff
-     let newNumberOfLines = Math.ceil((scrollHeight - paddingTopAndBottom) / lineHeight); 
+     let newNumberOfLines = Math.ceil((scrollHeight - paddingTopAndBottom) / (lineHeight + 2)); 
```

**Comment by mollfpr** [comment] 2022-11-18 16:14
>@mollfpr i think this is the only option for for this issue https://github.com/Expensify/App/issues/12745 , we had similar one before on mac https://github.com/Expensify/App/issues/2490
>
>For the 2nd issue we can add the extra px to lineheight when we getNumberOfLines

Thanks for the proposal and the investigation! @fedirjh 

But I think we should know first why the Firefox count `scrollHeight` is different, and what we know is that the value on Mac and Android is different. What I am confused about is, I can't repro this [issue](https://expensify.slack.com/archives/C049HHMV9SM/p1668612572582969) in the Android emulator. Could it have different values too on an Android tablet?

Thought about the [proposal](https://github.com/Expensify/App/issues/12745#issuecomment-1319058200)? @tgolen @trjExpensify 

---

This might be helpful. 

I'm playing around with text input styles by adding `padding-top: 1px; padding-bottom: 1px;`. After that, the `scrollHeight` is calculated correctly.

<img width="1800" alt="Screen Shot 2022-11-18 at 23 12 15" src="https://user-images.githubusercontent.com/25520267/202750387-e47104d1-c540-4976-84a9-30f51b8875c6.png">

**Comment by fedirjh** [comment] 2022-11-18 18:06
> I'm playing around with text input styles by adding padding-top: 1px; padding-bottom: 1px;. After that, the scrollHeight is calculated correctly.

@mollfpr modifying padding will create regression on android #10202

![image](https://user-images.githubusercontent.com/36869046/202772871-f47a502b-8a4d-453c-a08f-7b5f7fbaf163.png)

**Comment by fedirjh** [comment] 2022-11-19 00:05
After investigation , i found two other solutions to fix 1st issue  

- `font-size-adjust: 0.5;` applied to `textInputCompose` : this css property works only on firefox [browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust#browser_compatibility) so i think it's the best option here 
- `size-adjust: 90%;` applied to the `font-face` : i don't recommend this solution as this change will affect the whole app and maybe it will create regression , check this [source](https://web.dev/css-size-adjust/) for more info

All proposed solutions will only fix only the first issue , i think that 2nd issue is a different one , I fond that Firefox Android has an option to apply android font size instead of our font , this option when enabled will scale font by `x 1.1 ` , so instead of `15px` there is `16.5px` applied 

This is the log :

This is the option :
![Screenshot from 2022-11-19 00-35-19](https://user-images.githubusercontent.com/36869046/202822486-53a447f6-db65-4bbb-8a5f-12b94afd1bb3.png)

**Comment by mollfpr** [comment] 2022-11-20 14:46
Thanks for the investigation really appreciate @fedirjh!

I try a solution by adding `font-size-adjust: 0.5;` to our composer input, and this fix the line height issue but the emoji is kinda small to me.
**With font-size-adjust**
<img width="454" alt="Screen Shot 2022-11-20 at 21 19 21" src="https://user-images.githubusercontent.com/25520267/202907570-7f0b1c80-37d2-4b2a-bc34-36e8ce03466b.png">

**Without font-size-adjust**
<img width="438" alt="Screen Shot 2022-11-20 at 21 29 51" src="https://user-images.githubusercontent.com/25520267/202907965-0c55944b-1a42-4d52-a1ff-2cc4f9810567.png">

Here's my opinion:
- The issue is specified as Firefox scaled up the font size of our input.
- I agree `font-size-adjust: 0.5;` is the best option because is not change the size of the text and only applied to Firefox. But the downside is the emoji look smaller than the text.
- I also consider this [proposal](https://github.com/Expensify/App/issues/12745#issuecomment-1316144650) which raises the line height, but maybe raising it to `22` so it resolves the mWeb and applies it only to Firefox?

cc @trjExpensify @tgolen

**Comment by trjExpensify** [comment] 2022-11-21 14:18
I agree the emoji size looks too small in the first screenshot. @tgolen do you have thoughts on the right direction to go here?

**Comment by trjExpensify** [comment] 2022-11-24 14:42
@tgolen are you able to jump in here, please?

**Comment by iwiznia** [comment] 2022-11-25 12:45
AFAIK we said we would not be focusing on supporting firefox, so I think we should close this issue.

**Comment by mollfpr** [comment] 2022-11-27 15:36
@trjExpensify @tgolen Do we want to close this issue?

**Comment by trjExpensify** [comment] 2022-11-29 14:03
Sorry, been out for a couple of days. Personally, I think it's worth it because it's a bug impacting both text and emojis in the composer. That's front and centre as the most used component in the app. I shared that sentiment [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1668733432461889?thread_ts=1668730285.445209&cid=C01GTK53T8Q) on the topic.

**Comment by mollfpr** [comment] 2022-11-29 15:57
@trjExpensify Thanks for the insight! Let's see how @tgolen feel about the current state.

**Comment by tgolen** [comment] 2022-11-30 15:52
I think that just like tablets are not considered a supported platform (for things like landscape/portrait rotation), I think the same goes for supporting Firefox. Let's just focus on our supported platforms now (which would be Chrome). Any support for other browsers should be considered a feature request and not a bug. I'm going to close this out.

**Closed by tgolen** 2022-11-30 15:52 UTC
Labels: External, Daily, Help Wanted, Bug
