### ISSUE TITLE
[$1000] "Owes you" message shows up in the search page after searching for a contact after settling a money request

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19370] opened 2023-05-22 02:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a money request from account A to account B
2. Settle the money request from account B
3. Go to account A and click on FAB > New chat
4. Input account B's email inside of the search input field

## Expected Result:
User B should show up.
## Actual Result:
"Owes you" message shows up and doesn't show account B

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/71027825-7773-4ccb-a901-34aea585d187

https://github.com/Expensify/App/assets/43996225/c3af5200-6b47-4920-8274-5cdf7567d0d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684400092434069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b1abad8b1af373d</li>
        <li>Upwork Job ID: 1661084207028908032</li>
        <li>Last Price Increase: 2023-05-23</li>
    </ul>
</details>

**Comment by tienifr** [comment] 2023-05-22 09:56
## Proposal


### Please re-state the problem that we are trying to solve in this issue.
After settling a money request, the 'owes you' message shows up in the search page

### What is the root cause of that problem?
As explained by @huzaifa-99 , this is happening because the option data coming from recent reports are being added with the owe message.


### What changes do you think we should make in order to solve the problem?

We can modify the `text` value in [NewChatPage](https://github.com/Expensify/App/blob/8180113819532fe5503bc3719ba46ffc566e4ead/src/pages/NewChatPage.js#L107) to use the username value instead.
```diff
-        const recentReportsWithoutSelected = _.filter(this.state.recentReports, ({login}) => !filterText.includes(login));
+        let recentReportsWithoutSelected = _.filter(this.state.recentReports, ({login}) => !filterText.includes(login));
+        recentReportsWithoutSelected = recentReportsWithoutSelected.map(report => ({
+            ...report,
+            text: ReportUtils.getDisplayNameForParticipant(report.login)
+       }))
```

### What alternative solutions did you explore? (Optional)
We could consider adding a `useDisplayName` prop in [getSearchOptions](https://github.com/Expensify/App/blob/7db96195db30393e6db2e7376a2686626dd73db4/src/libs/OptionsListUtils.js#L772). Then, this prop could be passed all the way down to [createOption](https://github.com/Expensify/App/blob/7db96195db30393e6db2e7376a2686626dd73db4/src/libs/OptionsListUtils.js#L366), and we could add a check to use the user name for the displayed text, something like
```
if (useDisplayName) {
        result.text = ReportUtils.getDisplayNameForParticipant(report.managerEmail)
}
```

**Comment by bernhardoj** [comment] 2023-05-22 11:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we search for a user, the new chat list will only show the money request report.

### What is the root cause of that problem?
The new chat list shows the 5 most recent report and all user, except the user that already shown in the most recent by checking the `login` property.

Every money request will create a new report (assuming we don't have one) and it's also included in the list and the `login` attribute is the same as the `login` of the user we requested the money on. So, for example we request money to user A. First, it will be included in the most recent and the `login` is added to the exclude list. 
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L680-L683

Then, when we are trying to include users into the new chat list, we will skip if the user `login` is in the exclude list.
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L688-L692

So, we can only see the money request report in the new chat, but not the user report.

### What changes do you think we should make in order to solve the problem?

We shouldn't push the money request report to the exclude list here:
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L680-L683

In addition to check if `login` exist, we should also check if the report is a money request report and don't push it to the list if it's true.

`reportOption.login && !reportOption.isMoneyRequestReport`

-------
Additionally, I think it's intentional to have money request report in new chat or search page, but I think it's not expected to have money request report in new group/money request participants page (or maybe there are other page too). So, to further improve this, we can exclude money request report from the list just for some page. We can do same thing like this where we will pass `includeMoneyRequest` to true for new chat/search page:
https://github.com/Expensify/App/blob/c917c447f225fe3b194a5e03f568cca0de9e5e71/src/libs/OptionsListUtils.js#L593-L609


https://github.com/Expensify/App/assets/50919443/50f0a65a-0eeb-492f-a7ff-9cdc44226688

**Comment by kevinksullivan** [comment] 2023-05-25 00:19
Hm shouldn't be overdue, this just got to Alex yesterday.

**Comment by alex-mechler** [comment] 2023-05-25 16:18
@Santhosh-Sellavel there is a bunch of proposals in here to review when you get a chance

**Comment by Santhosh-Sellavel** [comment] 2023-05-25 16:26
Yeah, I got that on my list today!

**Comment by Santhosh-Sellavel** [comment] 2023-05-25 21:54
@alex-mechler After looking at proposals, we need to confirm what the issue & what's expected here.

1. Is showing owes you after settling up the transaction a problem?
2. We should not show IOU Transactions chat in the Search Page or New Group or New Chat

**Comment by alex-mechler** [comment] 2023-05-26 00:24
I'm going to defer to @kevinksullivan on those, I'm not sure what the intended behavior should be, but my thoughts are below

> Is showing owes you after settling up the transaction a problem?

I think in the LHN this isnt a problem, since its what was happening in the transaction

> We should not show IOU Transactions chat in the Search Page or New Group or New Chat

I think this is correct, or at least we should show them in addition to the user. We should still be showing the User who was entered

**Comment by kevinksullivan** [comment] 2023-05-26 18:11
Putting in slack to make sure I understand what we're discussing

https://expensify.slack.com/archives/C049HHMV9SM/p1685124620154599?thread_ts=1684400092.434069&cid=C049HHMV9SM

**Comment by kevinksullivan** [comment] 2023-05-26 18:53
sorry for the delay, but this is not reproducible and was already fixed.

https://expensify.slack.com/archives/C049HHMV9SM/p1685126944940099?thread_ts=1684400092.434069&cid=C049HHMV9SM

**Closed by kevinksullivan** 2023-05-26 18:53 UTC
Labels: External, Daily, Help Wanted, Bug
