### ISSUE TITLE
[HOLD for payment 2023-05-29] [$1000] LHN shows email address instead of “you” after deleting a mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18850] opened 2023-05-12 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open account A and be in another chat
2. Open account B and send a comment to account A mentioning account A
3. Go to account A and notice that on the LHN it says "you"
4. Go to account B and send a comment mentioning another person other than account A
5. Delete the last comment mentioning another person other than account A
6. Open account A's LHN

## Expected behavior:
It should say "you" just like before
## Actual behavior:
It shows account A's email address

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.3
**Reproducible in staging?:** y
**Reproducible in production?:** 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/35618786-92aa-4c2a-b86e-ea27fbe9171a

https://github.com/Expensify/App/assets/43996225/695f5f3e-42d7-4db8-8274-586ce493222d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683804623639899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f518f3db7e3629ae</li>
        <li>Upwork Job ID: 1657082877270765568</li>
        <li>Last Price Increase: 2023-05-19</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-05-12 22:48
Heads up, the root cause might be interlinked with the green dot persisting: https://github.com/Expensify/App/issues/18850

**Comment by YousefKhawaga** [comment] 2023-05-15 00:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN shows email address instead of “you” after deleting a mention, also after reconnecting (going offline then online)

https://github.com/Expensify/App/assets/37553623/64f2645c-b70d-4657-90fe-159d9d2cc048


### What is the root cause of that problem?
the backend returning the data doesn't check for the email to convert to you outside except for adding comment API.
also in case of deleting the action is responsible for building the lastMessageText which then doesn't check for the mention.
https://github.com/Expensify/App/blob/9fb9875ff2a739e6753355b4a231065a58ed6885/src/libs/actions/Report.js#L794-L801
### What changes do you think we should make in order to solve the problem?
adding a line inside getOptionFunction converting the mention to you in case of the mentioned user is the current user to ensure the data transformation.



### What alternative solutions did you explore? (Optional)
NA

**Comment by YousefKhawaga** [comment] 2023-05-15 00:10
Contributor details
Your Expensify account email: yousefkhawaga@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0176943ab81532aab1

**Comment by hayata-suenaga** [comment] 2023-05-15 20:38
@rushatgabhane can you review proposals?

**Comment by abekkala** [comment] 2023-05-17 18:51
@rushatgabhane did you have a chance to review the proposals yesterday?

**Comment by YousefKhawaga** [comment] 2023-05-18 11:23
@rushatgabhane 
While ReportAction is correct message Text is you 
the report itself which gets built on the backend returns the message by parsing HTML to text
![image](https://github.com/Expensify/App/assets/37553623/98ac813f-09d3-45eb-a5d9-a083d7195c38)

to fix the delete message issue we can change the getLastVisibleMessage to get the text instead of parsing the html itself
``` diff --git a/src/libs/ReportActionsUtils.js b/src/libs/ReportActionsUtils.js
index 6cb4e475f2..5b50c2296d 100644
--- a/src/libs/ReportActionsUtils.js
+++ b/src/libs/ReportActionsUtils.js
@@ -230,9 +230,9 @@ function getLastVisibleMessageText(reportID, actionsToMerge = {}) {
         return CONST.ATTACHMENT_MESSAGE_TEXT;
     }
 
-    const htmlText = lodashGet(lastVisibleAction, 'message[0].html', '');
-    const parser = new ExpensiMark();
-    const messageText = parser.htmlToText(htmlText);
+    const messageText = lodashGet(lastVisibleAction, 'message[0].text', '');
+    // const parser = new ExpensiMark();
+    // const messageText = parser.htmlToText(htmlText);
     return String(messageText).replace(CONST.REGEX.AFTER_FIRST_LINE_BREAK, '').substring(0, CONST.REPORT.LAST_MESSAGE_TEXT_MAX_LENGTH).trim();
 }
 ```
 
 but after sometimes when the api get the refreshed chat from /api?command=openReport it send the built report action also by parsing. if you want to fix this in frontend we can change createOption function as the new getOptionFunction is a building the option in createOption Function
 
``` diff --git a/src/libs/ReportActionsUtils.js b/src/libs/ReportActionsUtils.js
index 6cb4e475f2..5b50c2296d 100644
--- a/src/libs/ReportActionsUtils.js
+++ b/src/libs/ReportActionsUtils.js
@@ -230,9 +230,9 @@ function getLastVisibleMessageText(reportID, actionsToMerge = {}) {
         return CONST.ATTACHMENT_MESSAGE_TEXT;
     }
 
-    const htmlText = lodashGet(lastVisibleAction, 'message[0].html', '');
-    const parser = new ExpensiMark();
-    const messageText = parser.htmlToText(htmlText);
+    const messageText = lodashGet(lastVisibleAction, 'message[0].text', '');
+    // const parser = new ExpensiMark();
         } else {
             lastMessageTextFromReport = report ? report.lastMessageText || '' : '';
+            lastMessageTextFromReport = lastMessageTextFromReport.replace(`@${currentUserEmail}`, Localize.translateLocal('common.you'))
         }
         ```

**Comment by YousefKhawaga** [comment] 2023-05-18 12:17
Okay this is 2 problem one from frontend in case of deleting it parse html message to text in which case the email shows the solution is to get message text directly the other problem is after stale time or when user became offline to online again the response send lastMessageText containing the email not “you”

**Comment by YousefKhawaga** [comment] 2023-05-18 12:35
So the fix for the originally bug is changing  getLastVisibleMessage To get the text instead of getting the html then parsing it to text

**Comment by YousefKhawaga** [comment] 2023-05-18 13:21
The backend fix will fix when the user goes offline then online to get correct last message text

**Comment by hayata-suenaga** [comment] 2023-05-19 18:13
@rushatgabhane thank you for confirming that

I'll mark this issue internal and will work on this myself

**Comment by hayata-suenaga** [comment] 2023-05-22 23:04
[This line of code](https://github.com/Expensify/Web-Expensify/blob/5bb9ed4506fa8963c6b230781ab5351b996c1a31/lib/ReportUtils.php#L1491) that gets the email of the mentioned user might be the problem

**Comment by hayata-suenaga** [comment] 2023-05-22 23:08
Showing "you" was actually a bug. On both LHN and chat message itself, the mention should not be replaced with "you"

so this PR does not need a fix

the issue of @mentions replaced with "you" was solved in [this PR](https://github.com/Expensify/Web-Expensify/pull/37521).

**Comment by hayata-suenaga** [comment] 2023-05-22 23:11
@abekkala can you check if the issue reporter still needs to be paid?
otherwise, this issue can be closed

**Comment by abekkala** [comment] 2023-05-24 17:03
@hayata-suenaga ah ok - I can sent the [$250] reporting payment to @Nathan-Mulugeta and close this!

**Comment by Nathan-Mulugeta** [comment] 2023-05-24 17:12
Just accepted offer @abekkala

**Comment by Nathan-Mulugeta** [comment] 2023-05-27 03:17
Hey @hayata-suenaga and @abekkala payment has not been settled yet.

**Comment by mountiny** [comment] 2023-05-29 09:29
Reopening to get the payment handled

**Comment by abekkala** [comment] 2023-05-29 12:34
@Nathan-Mulugeta - you've been paid and contract ended - thank you! 🎉

**Closed by abekkala** 2023-05-29 12:34 UTC
Labels: External, Daily, Internal, Overdue, Awaiting Payment, Bug

**Comment by Nathan-Mulugeta** [comment] 2023-05-29 13:06
Thank you, received payment.
