### ISSUE TITLE
Web -  Profile - Autofill prompt does not appear for names fields

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#7982] opened 2022-03-02 17:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue was found when executing #7879**
## Action Performed:
Pre:
For Chrome go to chrome://settings/addresses
Add an address and enter a first and last name in the name field. Add a phone number including a country code (e.g, +1-945-881-9540).

1. Create a new account on new expensify.
2. Go to Settings > Profile.
3. Click into the first name field.

## Expected Result:
An autofill prompt should be appeared.
## Actual Result:
An autofill prompt doesn't appear.
Issue not reproduced on OldDot autofill prompt is appeared when enter data to Bank Account.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:**  v1.1.41-1
**Reproducible in staging?:**  Y
**Reproducible in production?:**  Y (New feature)
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![Bug5475752_Screen_Shot_2022-03-02_at_10 37 35_AM](https://user-images.githubusercontent.com/43996225/156410355-87e4488d-bff9-46e1-b904-5a317ea1b583.png)
![Bug5475752_Screen_Shot_2022-03-02_at_10 34 44_AM](https://user-images.githubusercontent.com/43996225/156410357-c0a0f152-d428-44ff-9806-fbb6aa8a06f8.png)

https://user-images.githubusercontent.com/43996225/156410360-4a59a33b-aaa0-4715-aaf4-7b56a7e552f5.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2022-03-02 17:12
cc @neil-marcellini Would you be bale to look into this one, it comes the [form PR](https://github.com/Expensify/App/pull/7879) most likely, but not sure why would it be broken.

Given it says it is reproducible in Production, I dont think this should be DeployBlocker and this issue does not prevent users from using the App so for urgency reasons I will take the DEbloyBlocker label off.

**Comment by neil-marcellini** [comment] 2022-03-02 17:15
Thanks Vit! I can look into this.

**Comment by mountiny** [comment] 2022-03-02 17:20
Thank you very much 🙇

**Comment by neil-marcellini** [comment] 2022-03-02 18:38
I'm changing this to weekly since it isn't super critical.

**Comment by afaqrajpoot** [comment] 2022-03-02 18:52
@neil-marcellini @neil-marcellini @mountiny 
I looked deeply into issue and i figure it out why its not working

How i will fix:
 
 I will use UseRef and declare a variable and initially it will be assigned as null and in the relative input field i will pass that variable to ref argument of the input field
 
 const emailField = useRef(null);

<input
  ref={emailField}
  id='email'
  type='email'                   
  name='email'
  value={email}
  
/>

**Comment by neil-marcellini** [comment] 2022-03-02 23:48
Autofill works fine for me on the profile page on staging. It doesn't work on production since my change hasn't been deployed there yet. I am unable to get it to fail at all on staging. Can anyone else make it fail?

**Comment by neil-marcellini** [comment] 2022-03-02 23:50
> How i will fix:
> 
> I will use UseRef and declare a variable and initially it will be assigned as null and in the relative input field i will pass that variable to ref argument of the input field
> 
> const emailField = useRef(null);
> 
> <input ref={emailField} id='email' type='email' name='email' value={email}
> 
> />

This is not an email field, there is a first name field and a last name field. Why would this kind of approach fix it?

**Comment by mountiny** [comment] 2022-03-02 23:55
Tried it on staging now and works well and I can confirm Production does not work. I think we can close this for now and QA will come back if the problem will still persist for them 👍

**Closed by mountiny** 2022-03-02 23:55 UTC
Labels: Engineering, Weekly

**Comment by afaqrajpoot** [comment] 2022-03-03 05:33
> > How i will fix:
> > I will use UseRef and declare a variable and initially it will be assigned as null and in the relative input field i will pass that variable to ref argument of the input field
> > const emailField = useRef(null);
> > <input ref={emailField} id='email' type='email' name='email' value={email}
> > />
> 
> @afaqrajpoot This is not an email field, there is a first name field and a last name field. Why would this kind of approach fix it?

This was just sample that how i will fix
defiantly all the input field will have its relevant  UseRef variables like
const firstName = useRef(null)
