### ISSUE TITLE
[$500] "Welcome to Expensify" modal is not dismissed when navigate to New Dot via link

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#36138] opened 2024-02-08 12:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Login with new account
3. Wait until Welcome to Expensify modal appears
4. Navigate to app via link from external app ( For example, https://staging.new.expensify.com/concierge)

## Expected Result:
"Welcome to Expensify" should dismiss

## Actual Result:
"Welcome to Expensify" modal is not dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Uploading Bug6371610_1707390579173!az_recorder_20240208_040301.mp4…

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0154dbaedfbd90c606</li>
        <li>Upwork Job ID: 1755565833584525312</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2024-02-08 12:17
Dupe of https://github.com/Expensify/App/issues/35663

**Closed** 2024-02-08 13:33 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by situchan** [comment] 2024-02-08 13:34
@shubham1206agra while saying you're dupe, can you confirm that solution used to fix https://github.com/Expensify/App/issues/35663 fixes this case as well?
This is reverse effect.
