### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Web - Select and copy does not copy New Expensify link in link format

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23251] opened 2023-07-20 10:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send normal link eg: `[test](google.com)`
4. Select the text and copy
5. Paste and see  it has proper link format
6. Send newdot link eg: `[test](staging.new.expensify.com/r/64705864)` (note, the home link new.expensify.com does not reproduce this issue)
7. Select the text and copy, paste and observe that now text is only displayed without link

## Expected Result:
App should copy all links equally on select and copy

## Actual Result:
App does not copy expensify links as links and display their text normally

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-18
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/173c49bc-c56a-4856-a3c8-e3ef7fd98e8e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689704143206879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c078f18bc8d09c6</li>
        <li>Upwork Job ID: 1683719949577637888</li>
        2023-07-25<li>Automatic offers: </li>
<ul>
<li>dhanashree-sawant | Reporter | 25815614</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-07-21 05:08
I'm not able to reproduce this:

https://github.com/Expensify/App/assets/59587260/298a426e-3aa0-4dd7-a91f-cef430cb28e0

@dhanashree-sawant could you please take a look and see if we need to update the reproduction steps?

**Comment by dhanashree-sawant** [comment] 2023-07-21 05:18
Hi @kadiealexander, can you try once with newdot expensify link? I am able to reproduce with that. On staging, with staging link and on live, with live link

**Comment by kadiealexander** [comment] 2023-07-25 04:13
@dhanashree-sawant I tried both and was still unable to reproduce:

Tested with new.expensify.com link from new.expensify.com on Chrome:

https://github.com/Expensify/App/assets/59587260/d019258e-c015-42df-aa1b-7f04549885af

Tested with staging.new.expensify.com link from staging.new.expensify.com on Chrome:

https://github.com/Expensify/App/assets/59587260/f2bf6df1-bf19-437d-84dc-0b706c75cee8

**Comment by dhanashree-sawant** [comment] 2023-07-25 05:40
Thanks yes, sorry now I got it, I have tested with plain main page links and that seems to be working fine, if I write anything after the first '/', it causes the issue

eg: Try to copy any other report URL and send it as link with different alias [test](https://staging.new.expensify.com/r/1234) and that will trigger the error.

Sorry for the inconvenience till now.

https://github.com/Expensify/App/assets/87513216/19463464-9d95-46a3-947f-f144b08419ad

**Comment by kadiealexander** [comment] 2023-07-25 06:03
All good, glad we got to the root if it! :)

https://github.com/Expensify/App/assets/59587260/4c6d0d7a-33e3-4bd0-8dec-124358f70ee3

**Comment by kadiealexander** [comment] 2023-07-25 06:04
Updated the reproduction steps with our findings.

**Comment by Parshvi16** [comment] 2023-07-25 09:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

new dot expensify URL can't be copied as URL if if is having some nesting in route

### What is the root cause of that problem?
in BaseAnchorForCommentsOnly.js
src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js

in case of nesting in route of new dot expensify URL, we are not getting `href` in `linkProps`, we are getting only `onPress` in `linkProps`.

when no `href` is present, `Text` component from react-native is not treating this as a Link, it is treating the data as text only, therefore we are not able to copy the link.


### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L78-L85

here no href is being passed as `linkProps.href` is null/undefined in our case

so we can pass `href={linkProps.href || props.href}` this href value.

but, it leads to a problem, this internal link starts opening in new window.

to fix this, we modify line no. 80 as:

``` diff
    target: isEmail || linkProps.onPress ? '_self' : props.target,
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Parshvi16** [comment] 2023-07-25 10:19
Contributor details
Your Expensify account email: parshvij16@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0172429e55178883a7

**Comment by mananjadhav** [comment] 2023-07-26 18:59
Both the proposals have the correct RCA, but @Parshvi16's proposal is more complete as it mentions how to deal with links opened in new window.

🎀 👀 🎀 C+ reviewed.

**Comment by Parshvi16** [comment] 2023-07-26 22:41
Thanks @mananjadhav, I'll start with the PR. 
@samh-nl yes, I have that in mind already, no need to worry about it, the navigation will use react-navigation only.

**Comment by Parshvi16** [comment] 2023-07-26 22:45
why is this auto-assigned to @roryabraham ?
@mananjadhav please check

**Comment by Parshvi16** [comment] 2023-07-27 00:00
Thanks @mananjadhav, I'll start with the PR. 
@samh-nl yes, I have that in mind already, no need to worry about it, the navigation will use react-navigation if the reviewer chooses that. Currently, I'll just create a PR for my initial proposal and @mananjadhav can suggest changes in the PR if required.

coming to navigation part, mentioning just 

> we should maintain navigation via onPress by stopping the event default behavior inside the handler function.

is not enough of a solution, implementation should have been shared in your proposal, because using `event.preventDefault()` in normal `if` statement will raise linting issues. I have already updated in my proposal the exact code that needs to be added to enable react-navigation without raising linting issues.

and as far as the fix for target is concerned, it needs a little edit and it can still be added while using react-navigation approach.

``` diff
-target: isEmail || linkProps.onPress ? '_self' : props.target,
+target: isEmail || !linkProps.href ? '_self' : props.target,
```

now it will act as a fallback for edge cases when we do not have `href` in linkProps.

**Comment by Parshvi16** [comment] 2023-07-27 01:16
@mananjadhav the PR is ready for review!

**Comment by mananjadhav** [comment] 2023-07-27 11:12
@Parshvi16 the job wasn’t assigned to you yet. Hence I’ll review the PR only after it is assigned. Please read our contributing guidelines to understand the process. 

We are still waiting for a confirmation from an Expensify engineer.

**Comment by mananjadhav** [comment] 2023-07-28 19:14
@roryabraham quick bump

**Comment by mananjadhav** [comment] 2023-07-31 14:43
Apologies for the delay in the response here. I see some of the comments edited, hence wanted to verify before I respond.

@samh-nl to address your comments, your proposal originally lacked any technical details. I don't expect the code, but at-least where/how do we pass the hrefs, etc. should've been a part of the proposal. And we do work out changes in the PR, bugs that come across testing when the PR is raised.

About you mentioning the proposal being completely incorrect, if we come across this in the PR/issue, we would open up again for the proposals, where the new/existing proposals would be reviewed for the expected behavior. This generally doesn't happen, but I won't say it has never happened.

Lastly, @Parshvi16 I would recommend sticking to the original proposals while implementing the solution, so that we're fair in any process without any conflicts.

**Comment by mananjadhav** [comment] 2023-08-03 03:56
> @roryabraham I'm not yet hired on upwork for this issue. Please check.

@kadiealexander Can you please help here?

**Comment by kadiealexander** [comment] 2023-08-03 04:19
@Parshvi16 please apply to the [Upwork job](https://www.upwork.com/jobs/~011c078f18bc8d09c6), as I can't find your application. Thanks!

**Comment by kadiealexander** [comment] 2023-08-04 00:44
@Parshvi16 Please post on the associated Github issues for those jobs and the relevant team member will assist you.

For this job, I need you to apply here: https://www.upwork.com/jobs/~011c078f18bc8d09c6

**Comment by kadiealexander** [comment] 2023-08-04 00:56
Could you please let me know the name of the person you used to apply?

**Comment by kadiealexander** [comment] 2023-08-04 01:02
Offer sent :)

**Comment by kadiealexander** [comment] 2023-08-04 01:05
Payouts due:

Issue Reporter: $250 @dhanashree-sawant
Contributor: $1000 + $500 bonus @Parshvi16
Contributor+: $1000 + $500 bonus @mananjadhav

Eligible for 50% #urgency bonus? [Yes](https://github.com/Expensify/App/issues/23251#issuecomment-1660910934)

Upwork job is [here](upwork.com/jobs/~011c078f18bc8d09c6).

**Comment by mananjadhav** [comment] 2023-08-08 16:55
I can't pinpoint to a specific PR, as we've got the links working since a long time. 

I also don't think we need a regression test for this one.

**Comment by mananjadhav** [comment] 2023-08-10 03:44
@kadiealexander  I've raised my request on NewDot.

**Comment by JmillsExpensify** [comment] 2023-08-10 03:48
Reviewed the details for @mananjadhav. This is approved for payment in NewDot.

**Closed** 2023-08-10 07:42 UTC
Labels: External, Daily, Awaiting Payment, Bug
