### ISSUE TITLE
IOS - Remove admin user after the invite new member in WS

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22532] opened 2023-07-09 18:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create new WS(profile-> worspace-> create new WS)
2. Then click on members
3. Click on invites
4. Select some email and invite
5. Observe the email list

## Expected Result:
Admin email should not be gone

## Actual Result:
After inviting the users, i not able to see admin user in list of members list.
When i am go back and again go to member list then it is showing.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/49875d5a-47bb-4d47-8d49-a77889358c1b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688786931252889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment] 2023-07-14 15:16
I cannot reproduce this!

**Comment by zanyrenney** [comment] 2023-07-14 15:17
Commented in slack, neither me nor applause can repro. closing!

**Closed by zanyrenney** 2023-07-14 15:17 UTC
Labels: Daily, Needs Reproduction, Bug
