### ISSUE TITLE
[HOLD for payment 2024-10-16] [$75] Migrate withReportOrNotFound from withOnyx to useOnyx

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#49108] opened 2024-09-12 17:34 UTC
Coming from https://expensify.slack.com/archives/C01GTK53T8Q/p1725973460005309?thread_ts=1725905735.105989&cid=C01GTK53T8Q

Migrate `src/pages/home/report/withReportOrNotFound.tsx` to use `useOnyx` instead of `withOnyx`.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834284536815669432</li>
        <li>Upwork Job ID: 1834284536815669432</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 103949135</li>
<li>Tony-MK | Contributor | 103949136</li>
<li>DylanDylann | Contributor | 104254755</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by abhinaybathina** [comment] 2024-09-12 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate from withOnyx HOC to useOnyx hook

### What is the root cause of that problem?
withOnyx HOC is deprecated

### What changes do you think we should make in order to solve the problem?
Whatever props are coming from withOnyx HOC should be replaced with useOnyx hook

### What alternative solutions did you explore? (Optional)

**Comment by mkzie2** [comment] 2024-09-12 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate withReportOrNotFound from withOnyx to useOnyx
### What is the root cause of that problem?
A new feature
### What changes do you think we should make in order to solve the problem?
We need to migrate the `withOnyx` here to use `useOnyx`. We also need to make sure the key we pass to `useOnyx` will be the collection member key to prevent the app crashes.

After using `useOnyx`, we can remove the type [here](https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportOrNotFound.tsx#L18)

https://github.com/Expensify/App/blob/7748eff72fc43ecaf3db6159928d8d581a63ab99/src/pages/home/report/withReportOrNotFound.tsx#L107

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2024-09-13 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Migrate withReportOrNotFound from withOnyx to useOnyx

### What is the root cause of that problem?

Migration

### What changes do you think we should make in order to solve the problem?


We should replace the `withOnyx` HOC, shown below, with `useOnyx` while cleaning up  `withReportOrNotFound`.

https://github.com/Expensify/App/blob/587698f1f4c703bab45d10056551ede97a67abe0/src/pages/home/report/withReportOrNotFound.tsx#L107-L122

**Comment by roryabraham** [comment] 2024-09-13 16:28
Going to assign to @Tony-MK since @abhinaybathina and @mkzie2 are assigned to migrate other components. Trying to assign these out first-come-first-serve while spreading them out to as many people as I can

**Comment by roryabraham** [comment] 2024-09-16 21:08
awaiting PR from @Tony-MK

**Comment by roryabraham** [comment] 2024-10-04 23:23
Going on parental leave and have to reassign this. @grgia I'm choosing you at random, hope you don't mind 🙃

**Comment by JmillsExpensify** [comment] 2024-10-16 18:17
Payment summary:

 - Contributor: $250 to @Tony-MK via Upwork
 - Reviewer: $250 to @DylanDylann via Upwork

**Comment by JmillsExpensify** [comment] 2024-10-16 18:18
@DylanDylann mind completing the BZ checklist?

**Comment by DylanDylann** [comment] 2024-10-17 02:19
@JmillsExpensify This is refactor task so I think we don't require checklist for this one

**Comment by JmillsExpensify** [comment] 2024-10-21 10:59
Updated the payment summary and issued payments via Upwork. Closing this one out!

**Closed by JmillsExpensify** 2024-10-21 10:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
