### ISSUE TITLE
[$1000] Unexpected error while splitting money- After task history- mobile number

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22031] opened 2023-07-02 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-requisite: There must be a task history over user A and user B. Please assign task from User A to User B and send some messages.  User B must be a phone number. 
1 Login as User A and click on + button and click on split money
2 Set amount and description and select User B 
3. Split money and verify if you get error
## Expected Result: 
There should be no error in splitting money with registered users.
## Actual Result: 
Got these errors : “There is a previously existing chat between these users.”
“Auth GetEmailByAccountID returned an error” and “Unexpected error requesting money, please try again later”
I got error with both registered and unregistered mobile numbers

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/7bb244ec-72db-4845-9591-ea47ed8752ed

https://github.com/Expensify/App/assets/43996225/f0dee343-751c-44e7-bd8c-126d53f3ae14

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688104145295479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016b1c3dd2f7daeaad</li>
        <li>Upwork Job ID: 1676297367694114816</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-07-04 18:31
Updated OP to make it clear at the beginning that User B needs to be a phone number. I was able to reproduce, 
<img width="614" alt="image" src="https://github.com/Expensify/App/assets/22508304/afd1b8db-4a54-4f3d-8de2-f46fb4daa509">

@abdulrahuman5196 , can you also test to see if you're able to reproduce then propose if this should be internal or external? thx

**Comment by abdulrahuman5196** [comment] 2023-07-07 20:14
Will check and update in the morning

**Comment by abdulrahuman5196** [comment] 2023-07-08 07:15
@mallenexpensify  I was able to reproduce this issue. I think there should be some issue in what report Id we are using for split in frontend, since it is not expected to create a new report since we already have a chat with the user created by the task.
**We can open it for external**, there could be some internal work. But the investigation place to start is in frontend.

**Comment by mallenexpensify** [comment] 2023-07-11 04:35
Made External, dropped a comment on https://github.com/Expensify/App/issues/22433 for Kadie to keep tabs on this, thanks for the comment @bernhardoj

**Comment by abdulrahuman5196** [comment] 2023-07-14 14:06
I think both the issues are related from the root cause from @bernhardoj. I will review the proposal here and re-check if the solution solves both the issues and update back.
Meanwhile, @bernhardoj  could you kindly post your proposal here as well specific to this issue?

**Comment by mallenexpensify** [comment] 2023-07-17 21:19
@abdulrahuman5196 , please review @bernhardoj 's proposal above

**Comment by mallenexpensify** [comment] 2023-07-19 13:41
@abdulrahuman5196 , please review @bernhardoj 's proposal above, it's been 5 days.
https://github.com/Expensify/App/issues/22031#issuecomment-1635998348

**Comment by abdulrahuman5196** [comment] 2023-07-19 18:22
Sorry for the delay. Reviewing the proposal now.

**Comment by abdulrahuman5196** [comment] 2023-07-19 18:59
On @bernhardoj 's proposal here https://github.com/Expensify/App/issues/22031#issuecomment-1635998348

I did a dive deep and I am not able to see `getChatByParticipants` causing issues in this particular case.

For instance I kept a debugger at `getChatByParticipants`, it was only called on this line but for that too `getChatByParticipants` return `undefined` and was never called again in split money flow. But still the issue occured for me. **So I think the root cause is somewhere else for this particular issue in hand.** 

https://github.com/Expensify/App/blob/a2dc004c6342c3b2e1e9a61bdc40b99da4fb647c/src/libs/actions/IOU.js#L456-L458


https://github.com/Expensify/App/assets/46707890/7a8087f4-a8aa-4ede-a328-50386abb62ca

**Comment by abdulrahuman5196** [comment] 2023-07-19 19:23
We don't have any other suitable proposals yet here.

**Comment by abdulrahuman5196** [comment] 2023-07-24 12:42
@mallenexpensify I think there is an explanation for why the proposal was not working - https://github.com/Expensify/App/issues/22031#issuecomment-1645159927

So now, we don't have a proposal yet. I think we need to increase the bounty.

@bernhardoj Kindly feel free to propose a different solution if you have already found the cause if possible.

**Comment by abdulrahuman5196** [comment] 2023-07-31 11:53
There hasn't been any proposal. Will check on the above comment to see if something could change in internal from backend to fix this.

**Comment by abdulrahuman5196** [comment] 2023-08-01 16:23
@mallenexpensify @bernhardoj 's analysis seems to be correct. We need to check how was case expected to work with the secure login change. Can we involve an internal engineer to check on this query?
This is the account information present in onyx

<img width="383" alt="Screenshot 2023-08-01 at 9 48 31 PM" src="https://github.com/Expensify/App/assets/46707890/2bab83f9-8a5c-4969-9d31-24d67148e7a9">


This is the data present in split api call being made, the accountID is different

<img width="766" alt="Screenshot 2023-08-01 at 9 50 04 PM" src="https://github.com/Expensify/App/assets/46707890/3c7df61a-07ac-48bf-b273-ca8cbede6a3e">

**Comment by abdulrahuman5196** [comment] 2023-08-08 17:40
@mallenexpensify Could you kindly check on this?

**Comment by abdulrahuman5196** [comment] 2023-08-11 09:18
Pinged in slack

**Comment by abdulrahuman5196** [comment] 2023-08-17 15:58
Need an internal engineer on this 

🎀 👀 🎀

**Comment by abdulrahuman5196** [comment] 2023-08-17 15:59
@tgolen Could you kindly check on this https://github.com/Expensify/App/issues/22031#issuecomment-1660665502?

**Comment by tgolen** [comment] 2023-08-17 16:35
Rather than assigning an internal engineer to a GH when you have a question like that, can you please post it in slack in the #expensify-open-source channel and tag @engineering-team, please? That way more eyes can see it and maybe get you an answer faster/better.

**Comment by mallenexpensify** [comment] 2023-08-23 14:04
@abdulrahuman5196 , can you please post your [comment above ](https://github.com/Expensify/App/issues/22031#issuecomment-1660665502)in the thread for the bug report (and be sure to check the box to share with the room so you get more 👀 ) https://expensify.slack.com/archives/C049HHMV9SM/p1688104145295479

If you don't receive a reply in a couple days, please post the same to #expensify-open-source 

Thx

**Comment by abdulrahuman5196** [comment] 2023-08-23 16:43
I had already posted in open source channel days back, missed to paste the reference here https://expensify.slack.com/archives/C01GTK53T8Q/p1692383613454819

But still no update

**Comment by abdulrahuman5196** [comment] 2023-09-04 09:03
This needs to be on hold as discussed here https://expensify.slack.com/archives/C01GTK53T8Q/p1693412993417589?thread_ts=1692383613.454819&cid=C01GTK53T8Q

cc: @puneetlath @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-09-05 02:44
Put on Hold, will add issue number once it's dropped in the thread. https://expensify.slack.com/archives/C01GTK53T8Q/p1693818288598599?thread_ts=1692383613.454819&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2023-09-11 07:14
Checking again for issue link
https://expensify.slack.com/archives/C01GTK53T8Q/p1694416424585289?thread_ts=1692383613.454819&cid=C01GTK53T8Q

**Comment by mallenexpensify** [comment] 2023-09-11 07:16
Aldo commented, we're on hold for 
- https://github.com/Expensify/App/issues/22480

**Comment by mallenexpensify** [comment] 2023-09-21 05:04
- https://github.com/Expensify/App/issues/22480#issuecomment-1725051296
> Made PR ready for review

Held issue is moving along

**Comment by mallenexpensify** [comment] 2023-10-04 17:54
Off hold, @kavimuru can you see if you can still reproduce?
Thx

**Comment by mallenexpensify** [comment] 2023-10-14 00:40
@kavimuru , are you able to reproduce?  Thx

**Comment by kavimuru** [comment] 2023-10-16 21:06
@mallenexpensify I am not able to reproduce

https://github.com/Expensify/App/assets/43996225/96ccae96-5534-4295-bbcf-006a1c92f3e6

**Comment by mallenexpensify** [comment] 2023-10-17 21:31
Closing, unable to reproduce and a lot of shit's changed with split and associated flow.

**Closed by mallenexpensify** 2023-10-17 21:31 UTC
Labels: Engineering, Weekly, Internal, Bug
