### ISSUE TITLE
[$500] Personal status not updating

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33982] opened 2024-01-04 19:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Beamanator 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704297912043559

## Action Performed:
1. Add a status w/ an emoji & text
2. Try to update the status just by adding a few letters to the text
3. Click Save
## Expected Result: 
Status should update
## Actual Result: 
Nothing happens - page doesn't change & network request is not sent

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3fe8ac73-5ecf-4543-a7fd-460613dc8398

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee550d7256ee4c3e</li>
        <li>Upwork Job ID: 1742988305435738112</li>
        <li>Last Price Increase: 2024-01-04</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2024-01-04 19:21
Dupe of https://github.com/Expensify/App/issues/33168

**Comment by twisterdotcom** [comment] 2024-01-05 09:49
Closing then.

**Closed by twisterdotcom** 2024-01-05 09:49 UTC
Labels: External, Daily, Help Wanted, Bug
