### ISSUE TITLE
[HOLD for payment 2023-11-22] [HOLD for payment 2023-11-21] [$500] IOU-In employee WS, in manual request, description entered is not saved in description page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31230] opened 2023-11-11 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on Employee WS
3. Tap plus icon near compose
4. Tap request money
5. Enter an amount
6. Tap next
7. Enter description and tap save
8. Tap request
9. Tap manual request created
10. Tap on Description

## Expected Result:
In employee WS, in manual request, description entered must be saved in description page.

## Actual Result:
In employee WS, in manual request, description entered is not saved in description page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/d4e67acc-240f-4d9e-88bf-cb77a74b8ab7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f13c7e52024929d1</li>
        <li>Upwork Job ID: 1723316971710357504</li>
        <li>Last Price Increase: 2023-11-11</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-11 13:11
This is another regression from https://github.com/Expensify/App/pull/28866, changes in `EditRequestPage`.

We render the edit description form twice, the first time with `transaction === {}`, therefore `propsToParse.defaultValue === ""`. On the second render, when the transaction is loaded, the form value does not update, because the `inputValues[inputID]` is not undefined anymore here, but filled with an empty string:

https://github.com/Expensify/App/blob/7f44418cfb1da3d5228900bcf172dee8ed6475d3/src/components/Form/FormProvider.js#L214-L217

**Comment by wlegolas** [comment] 2023-11-11 14:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU-In employee WS, in manual request, description entered is not saved in description page

### What is the root cause of that problem?

The `EditRequestPage` component is rendered more than once, and in the first render the `transaction` props have an empty object, but in the next render process, the `transaction` props have the correct value.

The description value is extracted from `transaction` using the method `ReportUtils.getTransactionDetails` and passed this value to the `InputWrapper` component, this component registers the input component using the [registerInput](https://github.com/Expensify/App/blob/main/src/components/Form/FormProvider.js#L205) method from `FormProvider`, as in the first render the `registerInput` method was called with an empty string, this value is memoized in the context, that way will generate the default value for this field using the last `else if` in this expression:

https://github.com/Expensify/App/blob/f0fb7a825a26967766e9f040e71a79d6006b027e/src/components/Form/FormProvider.js#L212-L220

### What changes do you think we should make in order to solve the problem?

The [registerInput](https://github.com/Expensify/App/blob/main/src/components/Form/FormProvider.js#L205) method receives in the second parameter the object `propsToParse`, this object has a property `shouldUseDefaultValue` that forces to use the default value. 

#### **Use the `shouldUseDefaultValue` property to force to use the default value:**

We should change the `EditRequestDescriptionPage` component to pass the property `shouldUseDefaultValue` to the `InputWrapperWithRef` component.

https://github.com/Expensify/App/blob/f0fb7a825a26967766e9f040e71a79d6006b027e/src/pages/EditRequestDescriptionPage.js#L60-L82

For example,

```js
<InputWrapperWithRef
    // Comment field does not have its modified counterpart
    InputComponent={TextInput}
    inputID="comment"
    name="comment"
    defaultValue={defaultDescription}
    shouldUseDefaultValue // <- Here we should pass the property
    label={translate('moneyRequestConfirmationList.whatsItFor')}
    accessibilityLabel={translate('moneyRequestConfirmationList.whatsItFor')}
    role={CONST.ACCESSIBILITY_ROLE.TEXT}
    ref={(el) => {
        if (!el) {
            return;
        }
        descriptionInputRef.current = el;
        updateMultilineInputRange(descriptionInputRef.current);
    }}
    autoGrowHeight
    containerStyles={[styles.autoGrowHeightMultilineInput]}
    inputStyle={[styles.verticalAlignTop]}
    submitOnEnter={!Browser.isMobile()}
/>

```

As the `EditRequestDescriptionPage` component will always receive the `defaultDescription` even if the transaction is not available, the field will show the correct value.

#### **Change the `registerInput` to use the `defaultValue` if this value is not `undefined`**

In the [registerInput](https://github.com/Expensify/App/blob/main/src/components/Form/FormProvider.js#L205), when the property `shouldUseDefaultValue` is `true` we need to add another validation, to ensure the `propsToParse.defaultValue` is not undefined.

With this improvement, we can avoid the problem when the `propsToParse.defaultValue` is `undefined`.

```js
if (!_.isUndefined(propsToParse.value)) {
    inputValues[inputID] = propsToParse.value;
} else if (propsToParse.shouldUseDefaultValue && !_.isUndefined(propsToParse.defaultValue)) { // <- Here we need to validate the defaultValue
    // We force the form to set the input value from the defaultValue props if there is a saved valid value
    inputValues[inputID] = propsToParse.defaultValue;
} else if (_.isUndefined(inputValues[inputID])) {
    // We want to initialize the input value if it's undefined
    inputValues[inputID] = _.isUndefined(propsToParse.defaultValue) ? getInitialValueByType(propsToParse.valueType) : propsToParse.defaultValue;
}
```

### What alternative solutions did you explore? (Optional)

N/A

**POC**


https://github.com/Expensify/App/assets/698363/09309cb0-b3d6-4772-9b08-f14561d38e59

**Comment by waitingwittykitty** [comment] 2023-11-11 17:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU-In employee WS, in manual request, description entered is not saved in description page

### What is the root cause of that problem?

The root cause of the problem is that the `registerInput` method is called twice. The first time, the value is `undefined`, causing the input to display an empty string. The next time, it receives a new value from the API, but it does not update because the `inputValue` is already set to an empty string.

### What changes do you think we should make in order to solve the problem?

To solve the problem, we can add a flag state to the component to indicate if it has been edited by the user. This way, the `inputValue` will only change by `value` prop if the user has not already edited it. We can set the flag state to true in the `onInputChange` function.

### What alternative solutions did you explore? (Optional)

As an alternative solution, we can render the input after the API call is finished. During the loading process, we can display a skeleton loader or simply disable the input.

**Comment by waitingwittykitty** [comment] 2023-11-11 17:30
Contributor details
Your Expensify account email: fasterthanclock@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ab529e479e41351f

**Comment by narefyev91** [comment] 2023-11-13 11:05
Issue was fixed based on this revert PR https://github.com/Expensify/App/pull/31231

**Comment by zanyrenney** [comment] 2023-11-22 18:01
Payment summary:
@narefyev91 does not require payment (Contractor)

Closing!

**Closed by zanyrenney** 2023-11-22 18:01 UTC
Labels: External, Daily, Help Wanted, Awaiting Payment, Bug
