### ISSUE TITLE
[$250] Scan - Missing scanning failed message from Expensify when scanning fails

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39937] opened 2024-04-09 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4480584
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Create a scan request with an invalid receipt.
4. When the scanning fails, go to the transaction thread.

## Expected Result:
There will be a message from Expensify saying that "Receipt scanning failed. Renter the details manually".

## Actual Result:
"Receipt scanning failed. Renter the details manually" message from Expensify is missing when scanning fails.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/1f0c2cb3-7c17-4d06-b67a-788be1331b94

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01385312802391945b</li>
        <li>Upwork Job ID: 1778610813595639808</li>
        <li>Last Price Increase: 2024-04-19</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-09 13:40
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-09 13:40
@greg-schroeder 
I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by greg-schroeder** [comment] 2024-04-12 02:27
Adding to #wave-collect

**Comment by shahinyan11** [comment] 2024-04-12 15:42
@kbecciv @greg-schroeder Could you please give an example of where and how it should be displayed. I think there is very little information to work on issue

**Comment by greg-schroeder** [comment] 2024-04-15 03:03
@shahinyan11 I think [this issue](https://github.com/Expensify/App/issues/34579) shows what QA is talking about here.

**Comment by shahinyan11** [comment] 2024-04-15 07:53
@greg-schroeder I couldn't find an answer there whether the message from Expensify should be displayed or the message under the receipt preview.

**Comment by kaushiktd** [comment] 2024-04-17 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan - Missing scanning failed message from Expensify when scanning fails 

### What is the root cause of that problem?

When scan a request with an invalid receipt, it will not update the error field for transaction thread in IOU.

### What changes do you think we should make in order to solve the problem?

To address the error detection during report scanning, a function is required to ascertain if a report contains any scanning errors. The function, named `hasScanError`, if a report contains any scanning errors the function will return True; otherwise, it will return False. Create `hasScanError` [here](https://github.com/Expensify/App/blob/main/src/libs/TransactionUtils.ts#L649) like below and export It.

```
function hasScanError(transaction: OnyxEntry<Transaction> | undefined): boolean {
    return transaction?.receipt?.state == CONST.IOU.RECEIPT_STATE.SCANFAILED;;
}
```

Add Below mention code [here](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestView.tsx#L257)

```
let errors = transaction?.errors ?? {};
const hasScanError = hasReceipt && TransactionUtils.hasScanError(transaction);
const errorKey = DateUtils.getMicroseconds();
if(hasScanError) {
    errors = {
        ...errors,
        ...(hasScanError ? { [errorKey]: ['iou.receiptScanningFailed', {isTranslated: false}] } : {})
    };
}
```

To get the scan error from the report, we'll add to current error list to show here. As well as, Add condition  `{(errors || showMapAsImage || hasReceipt) && (` inside `OfflineWithFeedback` component [here](https://github.com/Expensify/App/blob/main/src/components/ReportActionItem/MoneyRequestView.tsx#L263).


### Video
https://app.screencastify.com/v3/watch/jNOVk80oLRSZvgSxavkE

**Comment by greg-schroeder** [comment] 2024-04-19 22:55
Hmm maybe you're right, I guess this should be `Internal` then huh

**Comment by greg-schroeder** [comment] 2024-04-24 20:46
This might need to be a `Hot Pick`, will let Wave Collect curator decide though

**Comment by greg-schroeder** [comment] 2024-05-01 22:06
No update

**Comment by greg-schroeder** [comment] 2024-05-07 09:38
Same as above, polish waiting for an engineer to take

**Comment by greg-schroeder** [comment] 2024-05-09 05:36
Applying `Hot Pick`

**Comment by greg-schroeder** [comment] 2024-05-13 12:21
Still waiting for an internal engineer to pick this up

**Comment by greg-schroeder** [comment] 2024-05-15 22:40
Same as above, gonna move this to weekly I guess

**Comment by greg-schroeder** [comment] 2024-05-22 00:20
Same story, no real movement here. This is actually probably better served at `Monthly` until we start prioritizing `Polish` tbh

**Comment by greg-schroeder** [comment] 2024-06-25 01:10
Same as above

**Comment by mvtglobally** [comment] 2024-07-11 03:53
Issue not reproducible during KI retests. (First week)

**Comment by greg-schroeder** [comment] 2024-07-16 21:42
No updates here

**Comment by mvtglobally** [comment] 2024-07-19 03:19
Issue not reproducible during KI retests. (Second week)

**Comment by greg-schroeder** [comment] 2024-07-25 10:50
Closing as not reproducible, reopen if you disagree

**Closed by greg-schroeder** 2024-07-25 10:50 UTC
Labels: Monthly, Internal, Bug, Hot Pick
