### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] The tooltip disappears when the "Copy to clipboard" option is clicked multiple times.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19693] opened 2023-05-26 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go to any chat.
2.	Hover over any message to display the popup.
3.	Click on the "Copy to clipboard" option.
        I.	On the first click, click in the center to ensure that the tooltip is visible.
       II.	On the second click, click on the edge and observe that the tooltip remains hidden until the cursor is moved to other options.
## Expected Result: 
The tooltip should appear for the "Copy to clipboard" option, irrespective of placement of click.
## Actual Result: 
The tooltip for "Copy to clipboard" does not appear when clicked multiple times, especially after clicking on the edge.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-2
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e21b4a08-e272-4f7b-b06c-de137346a15b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684917973805069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9c2c343f15e297b</li>
        <li>Upwork Job ID: 1662216780603080704</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-05-26 21:58
I was able to reproduce by clicking on the edge of the "copy to clipboard" option.

**Comment by lschurr** [comment] 2023-05-26 22:53
I reproduced on staging @fedirjh - are you able to reproduce?

**Comment by MrJithil** [comment] 2023-05-27 09:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While the user hovers over the context icons, and repeatedly clicks on them on the edge of the hover area causing the disappearance of the tooltip. I also, found that the tooltip will not show if the user immediately clicks on any icons like "Copy to clipboard" or "Copy URL" etc before showing the tooltip, and not moving the mouse.

An easily replicated video is attached here:

https://github.com/Expensify/App/assets/26359740/d6fe9150-de0c-44cd-b2ec-0ed6c1e0622e



### What is the root cause of that problem?
We are showing an animated tooltip that has a delay of `500ms`, if the user clicks on any icon quickly before this animation is completed, the tooltips will miss the further hover in/out events. So that the tooltips will be hidden permanently till the user leaves the hover-able area. 

### What changes do you think we should make in order to solve the problem?

On icon, press we should stop the tooltip animation and display the tooltip instantly.
```
showTooltipInstantly(){
    this.animation.stopAnimation();
     this.animation.setValue(1);
}
```
For handling this, we need to declare a new event on hover handling component and bind it with `onPress`
```
onPress={this.showTooltipInstantly}
```

To avoid any impacts of other press event listeners, we must need to call the child prop `onPress` if defined. 
```
    child.props.onPress(el);
```

Evidence of the working code (side by side with the localhost  and production)

https://github.com/Expensify/App/assets/26359740/eafa1bdd-a6e9-4817-9992-7603ce197da8




All these code are samples only, so for questions regarding the working of this fix, please slack me.

### What alternative solutions did you explore? (Optional)

**Comment by gfrmoretti** [comment] 2023-05-27 16:09
# My Proposal

## The root cause

The root cause is a delay of 500ms in the animation tooltip. Like MrJtil identify if the user clicks on any icon quickly before this animation is completed, the tooltips will be disappear.

## Possible solutions:

### Easier Solution

- Remove the delay, just doing that the problem was solved.

```javascript
 Animated.timing(this.animation, {
                toValue: 1,
                duration: 140,
                delay: 0,
                useNativeDriver: false,
            }).start();
``` 

### More complex solution

- I propose to create a state control for these component for the delay time, why this ? When the user clicks in any item in ContextMenu in the onPress event I be able to set the delay time with zero, this make the animation stops and show the tooltip normally. For this to work I need to create a delay state flow control to change the delay time in OnPress event.

The animation will be like this :


```javascript
 Animated.timing(this.animation, {
                toValue: 1,
                duration: 140,
                delay: this.props.delay,
                useNativeDriver: false,
            }).start();
``` 

### Evidence

I test both solutions and they solve the problem.
Video Evidence bellow:


https://github.com/Expensify/App/assets/127613860/ca283436-855e-4d6a-a4e4-5677658c131c

**Obs**: Important to know, that this is a preview solution, this state control flow can be optimize in the final solution.

**Comment by MrJithil** [comment] 2023-05-28 00:25
Contributor details
Your Expensify account email: jithil@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01efe261118bd962c0

**Comment by MrJithil** [comment] 2023-05-28 00:27
> # My Proposal
> ## The root cause
> The root cause is a delay of 500ms in the animation tooltip. Like MrJtil identify if the user clicks on any icon quickly before this animation is completed, the tooltips will be disappear.
> 
> ## Possible solutions:
> ### Easier Solution
> * Remove the delay, just doing that the problem was solved.
> 
> ```js
>  Animated.timing(this.animation, {
>                 toValue: 1,
>                 duration: 140,
>                 delay: 0,
>                 useNativeDriver: false,
>             }).start();
> ```
> 
> ### More complex solution
> * I propose to create a state control for these component for the delay time, why this ? When the user clicks in any item in ContextMenu in the onPress event I be able to set the delay time with zero, this make the animation stops and show the tooltip normally. For this to work I need to create a delay state flow control to change the delay time in OnPress event.
> 
> The animation will be like this :
> 
> ```js
>  Animated.timing(this.animation, {
>                 toValue: 1,
>                 duration: 140,
>                 delay: this.props.delay,
>                 useNativeDriver: false,
>             }).start();
> ```
> 
> ### Evidence
> I test both solutions and they solve the problem. Video Evidence bellow:
> 
>  Screencast.2023-05-27.13.06.53.mp4 
> 
> **Obs**: Important to know, that this is a preview solution, this state control flow can be optimize in the final solution.
> 
> ## Contributor details
> Your Expensify account email: [gfrmoretti@gmail.com](mailto:gfrmoretti@gmail.com) Upwork Profile Link: [Upwork Profile](https://www.upwork.com/freelancers/~01616fbbe25baa196c?viewMode=1)

This solution of onPress event and delay time zero is a rewording of the previous proposal.

**Comment by robertjchen** [comment] 2023-05-29 15:45
Thanks for the proposals so far! Though, I wonder why we had the `500ms` delay in the first place- maybe it was to address some other bug in the past? 🤔

**Comment by MrJithil** [comment] 2023-05-30 00:16
> @MrJithil The root cause doesn’t looks accurate. This issue looks to affects only this tooltip (copy to clipboard) , If the animation is the root cause , shouldn’t we have all tooltips affected ? I feel this is related to some focus trap.

You could see the evodence of localhost and prod comparison, I have attached it. 

Here, I mentioned about animation because, a click before animation completes leading to a false state.

**Comment by MrJithil** [comment] 2023-05-30 03:16
> @MrJithil That doesn’t not answer the question , we have other places where tooltip is used, but it is only reproducible in copy to clipboard tooltip, So we are missing some explanation here. Please check the video
> 
>  Screen.Recording.2023-05-30.at.2.42.39.AM.mov

I think, you are confused. 

I can see the issues with all the places we are using tooltips.

Please see the evidence.

**Comment by MrJithil** [comment] 2023-05-30 10:35
@fedirjh Are you still unable to reproduce this issue aftrr following the latest video I attached regarding pin unoin button? 

Please let me know, so that I can  can define a list of steps to follow. 

Basically, to reproduce this issue, we need to quicker than animation delay. Becasue, the Hoverable component will instantly start the tooltip animation, and if you are clicking before its completed only we will be able to see that issue. 

I have verified it again in other places like profile icon where we are using the hoverable/pressable components. 

Thanks,

**Comment by priya-zha** [comment] 2023-05-31 02:53
According to this comment [here](https://github.com/Expensify/App/issues/19725#issuecomment-1567199931) , if [19725](https://github.com/Expensify/App/issues/19725) is a duplicate of [19693](https://github.com/Expensify/App/issues/19693), then I think [19693](https://github.com/Expensify/App/issues/19693) should also be a duplicate of [17307](https://github.com/Expensify/App/issues/17307) that I reported in April.

**Comment by lschurr** [comment] 2023-06-02 16:02
Any updates on this one @fedirjh?

**Comment by lschurr** [comment] 2023-06-07 20:25
Any update @huzaifa-99?

**Comment by MrJithil** [comment] 2023-06-08 10:19
@fedirjh Yes. As you said. This is a focus trap and after hours of investigation found the fix. This is causing by the `Hoverable` component. If the user clicking on any icon before the tooltip is shown, The `Hoverable` will miss the focus state permanently. Means, the `onMouseEnter`, `onMouseLeave` will not trigger as the user not moving the mouse pointer out of the hoverable area. And this way, the focus will be trapped. This is happening in all the icons has tooltips. Eg: Copy To URL, Pin/Unpin etc. 

To fix it, we need to implement `onPress ` event on the `Hoverable` component, and call `this.setIsHovered(true);`. 

I have updated the above proposal with this change.
https://github.com/Expensify/App/issues/19693#issuecomment-1565310313

Please check and let me know in case of queries.

**Comment by MrJithil** [comment] 2023-06-09 12:08
@fedirjh the root cause is mentioned in the updated proposal.

Since, the user not moving out the hoverable bound area of the icon, the hoverin/hoverout will not trigger again.

**Comment by MrJithil** [comment] 2023-06-12 13:44
> @MrJithil I don't believe the root cause is accurate. As I mentioned earlier, this bug seems to be specific to certain tooltips. It appears that tooltips with the `successText` attribute are the ones affected by this issue.

no problem. Thanks for the time and inputs.

**Comment by lschurr** [comment] 2023-06-15 00:31
Could you review these recent comments @fedirjh?

**Comment by lschurr** [comment] 2023-06-16 20:10
Hi @fedirjh - any update here?

**Comment by lschurr** [comment] 2023-06-21 20:28
@robertjchen @fedirjh - how should we move forward here?

**Comment by lschurr** [comment] 2023-06-26 15:21
@robertjchen should we increase the bounty on this one?

**Comment by BeeMargarida** [comment] 2023-06-27 11:14
Hey 👋 I’m Ana from Callstack, an expert agency, and I would like to help close this issue out. I see that there are some insights but the root cause is not clear. I would like to investigate it more in depth and see if I can help identify the problem and if any of the solutions provided or a new one could fully fix it.

**Comment by lschurr** [comment] 2023-06-27 16:50
Thanks @BeeMargarida!

**Comment by BeeMargarida** [comment] 2023-06-28 10:47
Update: still investigating and preparing a summary, I'm also going back in time to find out what commit/PR introduced the problem

**Comment by BeeMargarida** [comment] 2023-06-29 15:14
Update: I found the commit that introduced the behaviour, I'm finishing drafting a summary of what's happening and why it's happening. I'll post it here today or tomorrow morning at the latest

**Comment by BeeMargarida** [comment] 2023-07-03 09:52
@fedirjh There's an issue with that check, if we stop hovering and then the text changes, it will animate and show the tooltip. It would need to include the `this.state.isVisible`, like:

```javascript
if (this.state.isVisible && this.props.text && this.props.text !== prevProps.text) {
...
}
```

Also, two questions:
* Why the `TooltipSense.isActive()` check? I don't think it's necessary, since it might be active and the tooltip not be showing (for example if the animation was canceled).
* With this code snippet, the tooltip will just appear (without doing the animation) when we click and the text changes. This is expected behaviour, right?

**Comment by BeeMargarida** [comment] 2023-07-03 11:33
The thing is that I don't think the `!TooltipSense.isActive()` will ever be true in this case. The first `if` will only trigger if the text changes and the tooltip is visible, so it means the the showTooltip will have be called previously, which means the tooltipSense will always be active. So this can be removed from the check. 

Regarding the isCanceled, I'm not sure if we are over-optimizing here. But if we go forward, I think the solution you provided is good 👍

**Comment by robertjchen** [comment] 2023-07-05 08:17
Thanks so much for the in-depth discussion and analysis here @fedirjh @huzaifa-99 @BeeMargarida ! 🙇  To an outsider it may seem like a small UI quirk, but this attention to quality is definitely valuable.

Having reviewed the discussion here, I also approve of @huzaifa-99 's updated proposal. Let's move forward with that solution

**Comment by usmantariq96** [comment] 2023-07-06 06:10
@lschurr in Upwork job is no longer available.
How I can apply then ?

**Comment by lschurr** [comment] 2023-07-06 16:16
I created a new job since the old one expired - https://www.upwork.com/jobs/~01782c71ac1d47755b

**Comment by usmantariq96** [comment] 2023-07-06 17:12
@Ischurr the job is of $1000 whereas bug bounty is required to be of $250.

It is requested to kindly send me offer via message at Upwork please.

**Comment by lschurr** [comment] 2023-07-06 18:50
You should be able to apply with the price of $250 @usmantariq96

**Comment by usmantariq96** [comment] 2023-07-07 03:19
@lschurr  I am not able to apply. 
It is requested to kindly send me offer via message at Upwork please.
https://github.com/Expensify/App/assets/127622389/c44c5431-7054-4c09-999e-92c7fc33cf75

**Comment by lschurr** [comment] 2023-07-13 16:23
@fedirjh @huzaifa-99 @usmantariq96 - please apply for the job here: https://www.upwork.com/jobs/~01782c71ac1d47755b

**Comment by lschurr** [comment] 2023-07-13 16:23
@fedirjh do we need a regression test for this one?

**Comment by usmantariq96** [comment] 2023-07-13 16:35
@ischurr can you please share offer via direct message in Upwork, as I'm not able to access the link.

**Comment by lschurr** [comment] 2023-07-13 16:43
Can you share your Upwork profile here @usmantariq96?

**Comment by usmantariq96** [comment] 2023-07-13 17:03
https://www.upwork.com/freelancers/~0162e9ec0b876900fb

Please find above @lschurr 
Thanks

**Comment by lschurr** [comment] 2023-07-13 17:12
Ah, yeah I think that's the problem. Can you log out and try the link again? https://www.upwork.com/jobs/~01782c71ac1d47755b

**Comment by lschurr** [comment] 2023-07-14 15:38
Alright, I've invited @fedirjh @huzaifa-99 @usmantariq96 to the job - are you able to accept in Upwork?

**Comment by usmantariq96** [comment] 2023-07-14 16:11
@Ischurr thanks accepted.

**Comment by lschurr** [comment] 2023-07-14 16:22
Great! Offers sent.

**Comment by lschurr** [comment] 2023-07-14 17:01
Payments made to @usmantariq96 and @fedirjh. Just need @huzaifa-99 to accept the offer.

Additionally, @fedirjh - do we need a regression test for this? Could you work on the checklist here so that we can close this out? https://github.com/Expensify/App/issues/19693#issuecomment-1625186498

**Comment by usmantariq96** [comment] 2023-07-14 17:10
@Ischurr thanks.

**Comment by lschurr** [comment] 2023-07-14 18:03
Yep @huzaifa-99! That will be issued with the payment.

**Comment by lschurr** [comment] 2023-07-14 18:05
All payments issued. Closing!

**Closed by lschurr** 2023-07-14 18:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
