### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Tooltip show email instead of display name when hover in remaining users avatar in a group

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23378] opened 2023-07-21 21:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account
2. Create a group chat of more than 4 people.
3. Hover on the remaining users avatar in LHN or Report header of a chat group
## Expected Result:
 The tooltip should display name of remaining users. Because we're showing the display name in the header already. It's inconsistency and hard for user to map emails in tooltip and display names in header
## Actual Result: 
The tooltip is showing emails of remaining users.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3f14af05-f240-4dbf-8039-dfe383ac6e85

https://github.com/Expensify/App/assets/43996225/f9110c07-648b-41af-a80f-a777433bbb53

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689607619109389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01957373b884cf9d96</li>
        <li>Upwork Job ID: 1683585334338797568</li>
        <li>Last Price Increase: 2023-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 25906124</li>
<li>hoangzinh | Contributor | 25906128</li>
<li>hoangzinh | Reporter | 25906134</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-07-21 21:24
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Tooltip show email instead of display name when hover in remaining users avatar in a group
### What is the root cause of that problem?
The old tooltip text is getting from the props.icon.name https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/components/MultipleAvatars.js#L79
And when we get the icon.name of an chat group, we're preferring the login email over the displayName
https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/libs/ReportUtils.js#L754
### What changes do you think we should make in order to solve the problem?
I think we need to change the order of getting here so that we get the displayName first, then get login email as a fallback https://github.com/Expensify/App/blob/7770b866bff96efa42c337fb5db8473d34102e71/src/libs/ReportUtils.js#L754

**Comment by Nikhil-Vats** [comment] 2023-07-21 21:32
@puneetlath what's the expected behaviour here? 

IMO, we do see the names in the header and when we hover the names in the header, we see the mapping of names to emails. So, I think it's fine but the new tooltip looks so much better than the old one that it'd be nice if we show something like it for the remaining users (+2 icon).

**Comment by puneetlath** [comment] 2023-07-24 20:13
Hmm, interesting. I guess showing display names instead of emails would make sense in this scenario.

**Comment by slafortune** [comment] 2023-07-24 21:09
Yep, I think the display name would be more informative than the email at times.

**Comment by priyankrawat** [comment] 2023-07-25 15:20
**Proposal**
Please re-state the problem that we are trying to solve in this issue.
Tooltip show email instead of display name when hover in remaining users avatar in a group 


What is the root cause of that problem?
The code is fetching the participant's login i.e. the email and avatar URL from the personalDetails object, but it didn't include any logic to fetch the participant's first name or display name. 

What changes do you think we should make in order to solve the problem?
Modifying the participantsList loop to fetch the participant's first name along with their login and avatar URL from the personalDetails object should solve the issue.



https://github.com/Expensify/App/assets/30529816/7794e5e1-b2e2-4800-8ed9-6fa3beb26419

**Comment by priyankrawat** [comment] 2023-07-25 15:30
In ReportUtil.js file, we need to make this changes in Line 797-798:

         

`lodashGet(personalDetails, [accountID, 'firstName'], lodashGet(personalDetails, [accountID, 'displayName'], '')),
 lodashGet(personalDetails, [accountID, 'login'], ''),`

**Comment by priyankrawat** [comment] 2023-07-26 03:29
@Nikhil-Vats Will keep this in mind going forward. I'll edit my response. Thanks!

**Comment by slafortune** [comment] 2023-07-27 21:52
@situchan have you had a chance to review this?

**Comment by situchan** [comment] 2023-07-31 12:50
@hoangzinh's [proposal](https://github.com/Expensify/App/issues/23378#issuecomment-1646252758) looks good to me.
I think we should use `||` operator instead of lodashGet fallback for safety in case `displayName` is empty string (`''`).
@hoangzinh please comment here to get assigned.
🎀 👀 🎀 C+ reviewed

**Comment by slafortune** [comment] 2023-08-16 15:22
External issue reporter - @hoangzinh - $250 - PD
 Contributor that fixed the issue - @hoangzinh $1500 - PD
 Contributor+ that helped on the issue and/or PR - @situchan $1500 - PD

Speed bonus given 🎉 
when @hoangzinh got assigned: 2023-08-02 15:04:51 Z
when the PR got merged: 2023-08-07 04:34:29 UTC

**Comment by slafortune** [comment] 2023-08-16 15:23
@situchan can you complete the checklist, please?

**Comment by situchan** [comment] 2023-08-16 15:30
- [x] The PR that introduced the bug has been identified. Link to the PR: N/A. This was not bug but inconsistency.
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create a group chat of more than 4 people (I.e, userA and userB already set first/last name, userC and user D hasn't set first/last name yet)
2. Hover on the remaining users avatar in LHN or Report header of a chat group
3. Verify that tooltip shows display name of user A and user B
4. Verify that tooltip shows login email of user C and user D

**Closed** 2023-08-16 15:33 UTC
Labels: External, Weekly, Awaiting Payment, Bug
