### ISSUE TITLE
[$500]  Members - "Member not found" message does not appear when ad comma on Members page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30391] opened 2023-10-25 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to Workspace> Members
3. Type comma into search field

## Expected Result:
"Member not found" message should appear

## Actual Result:
"Member not found" message does not appear when ad comma ( out of context ) into search field on Members page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/aec976bc-e323-4407-8ca3-e1005db65271

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0194b093e86de4e9f0</li>
        <li>Upwork Job ID: 1717285405933965312</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by bertyruan** [comment] 2023-10-26 06:23
Contributor details
Your Expensify account email: berty.ruan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/bertyruan

**Comment by bertyruan** [comment] 2023-10-26 06:28
In my Upwork proposal, I uploaded a video showing a similar bug under Assign Task > Assignee. It can also be seen in Assign Task > Share somewhere. Should these details be added to this issue or created in a new one?

**Comment by getusha** [comment] 2023-10-26 10:36
@bertyruan you should post your proposal here.

**Comment by bertyruan** [comment] 2023-10-26 14:07
### Question 1: Please re-state the problem that we are trying to solve in this issue.
When searching for a user in the Workspace/Members tab, if the search string is the comma ',' character, the 'Member Not Found' error does not appear.

### Question 2: What is the root cause of that problem?
The root cause is due to parsing a function parameter called "SearchValue" into "SearchWords" through a regex function. The regex function uses the comma as the delimiter for a list of search words.

For example, if SearchValue is a string with value "one, two, three", the function will parse it into an array ['one', 'two', 'three'].

As a byproduct, if SearchValue contains a search word that is a comma, it misinterprets it as a delimiter. This bug can be seen in another section. Please refer to the video below for reference.

https://github.com/Expensify/App/assets/5183841/433e4f55-d2ac-4994-aeed-8ea157cf201f

Bug Location:
OptionsListUtils.js | isSearchStringMatch()

```
function isSearchStringMatch(searchValue, searchText, participantNames = new Set(), isChatRoom = false) {
    const searchWords = new Set(searchValue.replace(/,/g, ' ').split(' '));
    ...
}
```


### Question 3: What changes do you think we should make in order to solve the problem?
I propose to refactor the function. The method is used in two separate files. In both instances, the delimiter feature isn't used. In addition, the initial value is defined in both files by the following statement:
`const [searchValue, setSearchValue] = useState('');`

```
//The following statement can be transformed from
const searchWords = new Set(searchValue.replace(/,/g, ' ').split(' '));
//to
const searchWords = new Set(searchValue.split(',').filter(Boolean));
```
In all scenarios, e2e testing needs to be done to make sure no side effects occur.

**Comment by getusha** [comment] 2023-10-27 12:07
I start a discussion in `expensify-open-source` about the expected result
https://expensify.slack.com/archives/C01GTK53T8Q/p1698408127981499

**Comment by getusha** [comment] 2023-10-28 05:32
@lschurr after the discussion ^ this is the expected result and not a bug. we can close this.

**Comment by lschurr** [comment] 2023-10-30 15:19
Great thanks!

**Closed by lschurr** 2023-10-30 15:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
