### ISSUE TITLE
Web - Workspace - Cursor is not focused in search box when invite a member 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10218] opened 2022-08-02 21:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with account
3. Go to Setting - Workspace
4. Manage members
5. Click Invite button

## Expected Result:
Cursor is focused in Search box after click Invite button

## Actual Result:
Cursor is not focussed

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.87.8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/182480792-9c876b4f-df32-480c-8092-84b3632e4963.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2022-08-02 22:21
Seems to be a feature not a bug: https://github.com/Expensify/App/blob/71609fdcfe1a39bf97c1f4659f8ae81b27bf9c28/src/pages/workspace/WorkspaceInvitePage.js#L264, will confirm if this is the wanted behaviour or not, in case it is we can close this issue.

**Closed** 2022-08-03 12:38 UTC
Labels: Engineering, Weekly
