### ISSUE TITLE
[$250] iOS - Chat - Chat gets blank after deleting task and does load until user swipes down

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45727] opened 2024-07-18 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #45279 
**Version Number:** 9.0.9.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause Internal Team
**Slack conversation:** 

## Action Performed:
1. Open the app and log in
2. Navigate to any report with some chat history
3. Tap + > Assign task
4. Enter title and complete task creation
5. Open the created task
6. Tap the header and delete the task
## Expected Result:
User is returned to the report and previous chat history is displayed
## Actual Result:
The chat history is not displayed until user swipes down
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/user-attachments/assets/1c2d0b29-3d72-40aa-b330-bcb6eb8b7c49

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018e3d29dc110bc703</li>
        <li>Upwork Job ID: 1815451828641310685</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by m-natarajan** [comment] 2024-07-18 21:58
@abekkala FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-07-18 22:04
@abekkala We think that this bug might be related to  #vip-vsb

**Comment by Zakpak0** [comment] 2024-07-23 13:39
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Given it is the latest report action, when deleting the last task in an **Assign Task** list creates a navigation error which leaves the screen blank.
### What is the root cause of that problem?
It seems like we aren't waiting for the navigator to be ready before we navigate back to the original report.
What changes do you think we should make in order to solve the problem?

We should change these lines here
[src/libs/actions/Task.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/Task.ts#L1058-L1060)
```typescript
    if (shouldDeleteTaskReport) {
            Navigation.goBack(ROUTES.REPORT_WITH_ID.getRoute(parentReport?.reportID ?? '-1'));
    }
```
To the following:
If we should delete the task report, then lets wait for navigation to be ready and then navigate the user back.
```typescript
    if (shouldDeleteTaskReport) {
        Navigation.isNavigationReady().then(() => {
            Navigation.goBack(ROUTES.HOME)
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(parentReport?.reportID ?? '-1'));
        })
    }
```
[Here](https://github.com/Zakpak0/Expensify-App-Fork/tree/zakpak0/bugfix-issue-%2345727) is a test branch with my changes

What alternative solutions did you explore? (Optional)
My inbox and it's search options are flooded with [Deleted task] threads. I'm not sure if this expected behavior. If it is not then I believe that could mean the task feature isn't fully fleshed out? And task actions aren't being handled as well as other features? Like filtering and navigating. I'm not sure, but if my suspicion is correct this could also be contributing to the root cause.

**Comment by abekkala** [comment] 2024-07-29 16:20
@eVoloshchak can you review the proposal above?

**Comment by abekkala** [comment] 2024-07-30 15:14
@eVoloshchak are you able to review that proposal today?

**Comment by eVoloshchak** [comment] 2024-07-30 18:19
> It seems like we aren't waiting for the navigator to be ready before we navigate back to the original report.

@Zakpak0, inside the [Navigation.goBack](https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/libs/Navigation/Navigation.ts#L193) we check if navigation is ready ([canNavigate](https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/libs/Navigation/Navigation.ts#L194) -> [navigationRef.isReady()](https://github.com/Expensify/App/blob/d4104a73c1a6159e61c170bbbaf3949865991852/src/libs/Navigation/Navigation.ts#L48C9-L48C32))
There is a difference in implementation between isNavigationReady and navigationRef.isReady(), we need to figure out exactly why the first works, but the second doesn't, so this is resolved app-wide (in `goBack` method itself)

**Comment by Zakpak0** [comment] 2024-08-01 04:29
@eVoloshchak thank you, will look into this more today.

**Comment by eVoloshchak** [comment] 2024-08-05 18:01
Not overdue, don't have any satisfactory proposals just yet

**Comment by abekkala** [comment] 2024-08-08 18:21
@Zakpak0 are you able to provide an updated proposal?

**Comment by abekkala** [comment] 2024-08-09 17:34
Given that we haven't received a proposal and vsb is on hold - I'm closing

**Closed by abekkala** 2024-08-09 17:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
