### ISSUE TITLE
[WAITING ON CHECKLIST] [$250] Expense Details - The header of the expense details displays "[amount] for [Description]"

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49993] opened 2024-10-01 13:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.42-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5023024
**Email or phone of affected tester (no customers):** biruknew45+1278@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a workspace
3. Go to the workspace chat
4. Click the plus button > Submit Expense > enter amount, description, and merchant, and complete the submission
5. Open the expense details

## Expected Result:
The conversation title in the LHN should display "[amount] for [Merchant]"

## Actual Result:
The conversation title in the LHN displays "[amount] for [Description]"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/68534efe-26e9-4652-a19d-ae6e42395f3c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841274388644598293</li>
        <li>Upwork Job ID: 1841274388644598293</li>
        <li>Last Price Increase: 2024-10-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-10-01 13:40
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-10-01 14:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We pass the `comment` as description here then LHN displays `amount for description`

https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3471

https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3482
### What changes do you think we should make in order to solve the problem?
Here we should get the merchant first then fallback to description if the merchant is empty

```
let comment = !isEmptyObject(linkedTransaction) ? TransactionUtils.getMerchant(linkedTransaction) || TransactionUtils.getDescription(linkedTransaction) : undefined; 
```

https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3471

OPTIONAL: we can also do the same [here](https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L7193)

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by bernhardoj** [comment] 2024-10-01 14:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last message when we submit an expense with a merchant and description will show the description instead of the merchant.

### What is the root cause of that problem?
We always use the description here.
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3471
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3482

### What changes do you think we should make in order to solve the problem?

We need to follow the same logic from `getTransactionReportName` which checks whether the merchant is empty or not before using it because (none) merchant is also empty.
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3322

```
let comment = !isEmptyObject(linkedTransaction) ? (!TransactionUtils.isMerchantMissing(linkedTransaction) ? TransactionUtils.getMerchant(linkedTransaction) : TransactionUtils.getDescription(linkedTransaction)) : undefined;
```

We can apply the same fix here
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3373
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L3395
https://github.com/Expensify/App/blob/d46f21888154dc77a799e06d22e576eaece80368/src/libs/ReportUtils.ts#L7193

**Comment by jliexpensify** [comment] 2024-10-01 23:44
I can repro but not sure if we made this change intentionally, so asking here: https://expensify.slack.com/archives/C036QM0SLJK/p1727826242838209

**Comment by jliexpensify** [comment] 2024-10-02 00:30
Confirmed that this seems to be a bug:

>merchant should take priority over description like the preview component

**Comment by jliexpensify** [comment] 2024-10-02 00:31
@alitoshmatov I'm OOO from 3rd to 14th, but I don't think anything is needed from me during this period. Feel free to reassign to another B0 if urgent payment is needed, otherwise I'll catch up on this issue when I get back!

**Comment by alitoshmatov** [comment] 2024-10-06 09:14
@nkdengineer @bernhardoj Thank you both for proposals. Your RCA is correct and you provide with almost the same solution. 

It is hard choice to make since both proposals are very similar solution, even though @bernhardoj was the second one to submit he did have small additional changes.

I think we should go with @bernhardoj's [proposal](https://github.com/Expensify/App/issues/49993#issuecomment-2386150540) since it has additional changes that we might have missed it 

C+ reviewed 🎀 👀 🎀

**Comment by jliexpensify** [comment] 2024-10-22 09:07
Bumping @alitoshmatov - any checklist needed here?

Payment Summary

- C: @bernhardoj $250 (New.Dot payment)
- C+: @alitoshmatov $250 (Upworks is error-ing for me , can you apply here: https://www.upwork.com/jobs/~021841274388644598293)

**Comment by bernhardoj** [comment] 2024-10-22 09:36
Requested in ND.

**Comment by jliexpensify** [comment] 2024-10-22 22:52
Sorry, upworks is being really weird and won't let me access the job so I closed it and am trying to see if another Job is created.

**Comment by jliexpensify** [comment] 2024-10-22 22:57
@alitoshmatov waiting on checklist, and invited you to a new job here:

https://www.upwork.com/jobs/~021848861002130198557

**Comment by jliexpensify** [comment] 2024-10-23 09:42
Paid @alitoshmatov via Upworks, just waiting on checklist

**Comment by alitoshmatov** [comment] 2024-10-23 10:06
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37282
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37282/files#r1812400386
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Closed** 2024-10-23 10:08 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by JmillsExpensify** [comment] 2024-10-24 17:04
$250 approved for @bernhardoj based on [this summary](https://github.com/Expensify/App/issues/49993#issuecomment-2428713135).
