### ISSUE TITLE
Size is not same for both icon, and also hit area is small for search icon

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13877] opened 2022-12-29 02:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Goto https://staging.new.expensify.com/
2. Hover over the search icon on homepage

## Expected Result:
There should be equal spacing for all icons

## Actual Result: 
The spacing is not same, and therefore the hit

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari

**Version Number:** 1.2.45 -0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209894554-1f0373f6-9759-4f13-b714-cf410cdf29c3.mp4

https://user-images.githubusercontent.com/43996225/209894571-2dc5db73-600b-4379-978a-74c3d765ede3.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mdneyazahmad 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672221807909359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-12-29 14:25
@MitchExpensify I posted in bug-zero since I think this is not a bug and we can simply close it.

**Comment by pecanoro** [comment] 2022-12-29 16:53
After some discussion, we decided not to change this as it's not a bug (nothing is broken) and it does not improve user experience. Because of that, I am closing it!

**Closed by pecanoro** 2022-12-29 16:53 UTC
Labels: Daily, Bug

**Comment by MitchExpensify** [comment] 2022-12-30 00:17
Thanks @pecanoro!
