### ISSUE TITLE
[$500] Web - Request money-Tooltip is partially displayed on the chat page if drag a mouse to the left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33913] opened 2024-01-03 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the URL https://staging.new.expensify.com/
2. Login with any account
3. Go to FAB -> Request money -> Manual
4. Hover the mouse over the currency to display a tooltip and move to the left

## Expected Result:
Tooltip disappears on the chat page

## Actual Result:
Tooltip is partially displayed on the chat page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/af710344-aa8c-48b4-8a6d-41e7fd75be6c

![Bug6331694_1704318319206!0301](https://github.com/Expensify/App/assets/78819774/b3f40218-f9f9-44e3-8607-67ccb8ceefe1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c9c1639fe8bdd01</li>
        <li>Upwork Job ID: 1742675153533714432</li>
        <li>Last Price Increase: 2024-01-03</li>
    </ul>
</details>

**Comment by codebycarlos** [comment] 2024-01-04 01:05
I think the main challenge here is the tooltip is always rendered in the body (much higher up in the DOM than the hover target). Hence why it doesn't get clipped during overflow.

**Comment by nabhiraj** [comment] 2024-01-04 01:09
hi :) , the tooltip takes care of the gutterwidth to shift it left or right to avoid the over flow, but this only happens on the window level, we can can pass a gutter width for left and right boundary depending upon the right side navigator, i guess we can use this gutter widths to fix this.

**Comment by nabhiraj** [comment] 2024-01-04 01:13
Contributor details
Your Expensify account email: nabhinewton04@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010ffad1aef68cbf91

**Comment by nabhiraj** [comment] 2024-01-04 03:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

when we select the currency symbol and drag to the left the tool-tip is overflowing on the chat window

### What is the root cause of that problem?

this is happening because css property of the tool-tip is of display type fixed (but this is necessary because we want tool tip to hover over the element)

### What changes do you think we should make in order to solve the problem?
we can apply the same solution as we use in window level i.e we can use a gutter width, if the position of the tooltip crosses this gutter width then we can shift it towards the right side. we can get the offset of the righ navigation modal from the `src/pages/iou/steps/MoneyRequestAmountForm.js`

```let tempRef=useRef();
    let [viewWidth,setViewWidth] = useState(500); 
    useEffect(
        ()=>{
            const rect = tempRef.current.getBoundingClientRect();
            console.log('hanele resize',rect.x);
            setViewWidth(rect.x);
        });
//this tempRef (will think of a good name) will be the ref for View (i.e first child of ScrollView)
```
then we can drill these offeset paramenter till `src/styles/getTooltipStyles.ts` 
and there we can use this value to set gutterWidthValue
something like this
```
function computeHorizontalShift(windowWidth: number, xOffset: number, componentWidth: number, tooltipWidth: number, manualShiftHorizontal: number,leftBoundryPos: number): number {
    // First find the left and right edges of the tooltip (by default, it is centered on the component).
    const componentCenter = xOffset + componentWidth / 2 + manualShiftHorizontal;
    const tooltipLeftEdge = componentCenter - tooltipWidth / 2;
    const tooltipRightEdge = componentCenter + tooltipWidth / 2;
    if(leftBoundryPos && tooltipLeftEdge < leftBoundryPos){
        return roundToNearestMultipleOfFour(leftBoundryPos - tooltipLeftEdge);
    }else if(tooltipLeftEdge < GUTTER_WIDTH) {
        // Tooltip is in left gutter, shift right by a multiple of four.
        return roundToNearestMultipleOfFour(GUTTER_WIDTH - tooltipLeftEdge);
    }

    if (tooltipRightEdge > windowWidth - GUTTER_WIDTH) {
        // Tooltip is in right gutter, shift left by a multiple of four.
        return roundToNearestMultipleOfFour(windowWidth - GUTTER_WIDTH - tooltipRightEdge);
    }

    // Tooltip is not in the gutter, so no need to shift it horizontally
    return 0;
}
//where leftBoundryPos is the value of the left edge which we found earlier
// i am using these variable name just for the proposal in the PR i will use meaningful names.
```

### What alternative solutions did you explore? (Optional)

NA

**Comment by dragnoir** [comment] 2024-01-04 10:52
The toolyip is rendered just inside the body tag (at the end) with a [fixed position](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed).

> The element is removed from the normal document flow, and no space is created for the element in the page layout. The element is positioned relative to its initial [containing block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block), which is the viewport in the case of visual media. Its final position is determined by the values of top, right, bottom, and left.

The `overflow: hidden` can't be applied to it.

**Comment by abekkala** [comment] 2024-01-04 16:32
@shawnborton I know there have been some recent talks about tooltips in #product and #wave8. 
Does fixing the placement of this one require an external fix (and assigning to a specific wave)? Or, can we just do this internally?

**Comment by shawnborton** [comment] 2024-01-04 16:38
Honestly, I think I would just close this one out. It's such an edge case. cc @Expensify/design in case they disagree.

**Comment by dannymcclain** [comment] 2024-01-04 17:20
Totally agree. This doesn't seem like it's worth addressing to me.

**Comment by abekkala** [comment] 2024-01-04 17:22
I agree, Closing

**Closed by abekkala** 2024-01-04 17:22 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by nabhiraj** [comment] 2024-01-04 19:58
hi :) , i have sent the mail to contributors@expensify.com with subject "Slack Channel Invites" but i am not getting a invite for #expensify-open-source in slack, can please someone add me to this channel. thanks.

**Comment by iamwesofph** [comment] 2024-01-07 05:53
Hi, I also sent mail to contributors@expensify.com multiple times already but I am not getting an invite too.  Kindly add me: piuswesley@gmail.com

**Comment by iamwesofph** [comment] 2024-01-07 05:56
Contributor details
Your Expensify account email: piuswesley@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0129f08884f50d1176
