### ISSUE TITLE
Web - Mention list is not dismissed when pressing Send button

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23343] opened 2023-07-21 10:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any report
2. Enter an full email that matched the mention list
3. Press send button.

## Expected Result:
Mention list should be dismissed after sending

## Actual Result:
Mention list is not dismissed after sending

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0f9e6f0f-eeaf-4c7c-b2d2-a83b7d716786

https://github.com/Expensify/App/assets/93399543/702be113-2414-4340-927d-ce0bd22210d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689843014356199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-21 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention list is not dismissed when pressing Send button
### What is the root cause of that problem?
We're not dismissing our suggestions when pressing Send button in here:
https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/pages/home/report/ReportActionCompose.js#L938-L953
### What changes do you think we should make in order to solve the problem?
In our submit function [here](https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/pages/home/report/ReportActionCompose.js#L938-L953) we can add a condition to dismiss suggestions if necessary.

```javascript
  const suggestionsExist = this.state.suggestedEmojis.length > 0 || this.state.suggestedMentions.length > 0;
if (suggestionsExist) {
 this.resetSuggestions();

}
```



### What alternative solutions did you explore? (Optional)
N/A

**Comment by gadhiyamanan** [comment] 2023-07-21 10:16
Dupe of https://github.com/Expensify/App/issues/15934

**Comment by MitchExpensify** [comment] 2023-07-21 18:20
Thanks, team!

**Closed by MitchExpensify** 2023-07-21 18:20 UTC
Labels: Daily, Bug
