### ISSUE TITLE
Workspace features-User not returned to WS settings after enabling Accounting in more features

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42789] opened 2024-05-29 19:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team
 
**Issue found when executing PR** https://github.com/Expensify/App/pull/42026
## Action Performed:
1. Open the app and log in
2. Create a new workspace
3. Navigate to the workspace settings
4. Open More features
5. Enable Accounting

## Expected Result:
User is returned to workspace settings, the Accounting feature is highlighted

## Actual Result:
User is not returned to the workspace settings. The Accounting feature is not removed immediately after disabling

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/54f3ee28-a161-442a-959d-67995f058132

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bfitzexpensify** [comment] 2024-05-30 13:34
Assigning a second BZ team member to this one while I head OOO from later on today until Tuesday June 11th. 

@kadiealexander Next steps: 
- get confirmation from https://github.com/Expensify/App/issues/42789#issuecomment-2139566470 if this can be handled as a regression related to https://github.com/Expensify/App/pull/42026
- if not, open this up for external proposals

**Comment by kadiealexander** [comment] 2024-06-04 06:10
Thanks @Nodebrute! I'd like to get confirmation from someone who worked on the original issue, @sobitneupane could you please confirm since you were C+ on the original PR?

**Comment by sobitneupane** [comment] 2024-06-04 07:26
@allroundexperts Looks like https://github.com/Expensify/App/issues/39214 issue was not addressed in https://github.com/Expensify/App/pull/42026 PR.

**Comment by allroundexperts** [comment] 2024-06-04 07:31
Yep, you're correct @sobitneupane. I'll create a PR for this.

**Comment by allroundexperts** [comment] 2024-06-04 16:04
PR: https://github.com/Expensify/App/pull/43043

**Comment by thienlnam** [comment] 2024-06-06 14:48
Merged, it looks like we forgot to add this in a previous PR

**Comment by kadiealexander** [comment] 2024-06-11 01:05
@thienlnam do you think anyone is due payment here?

**Comment by thienlnam** [comment] 2024-06-11 18:10
Doesn't look like it since this was a feature that was missed as part of a previous PR - looks like we're good to close

**Closed by thienlnam** 2024-06-11 18:10 UTC
Labels: Reviewing, Weekly, Bug
