### ISSUE TITLE
[$250] Unbold Self DM Email in LHN when Marked Unread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39712] opened 2024-04-05 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.60-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1, Click on the Search button and search for "You."
2, Enter the self DM and write a message, then mark it as unread.
3, Notice that a new message line appears, but the self-DM email in the LHN doesn't appear bold.

## Expected Result:
When writing a message in self-DM and marking it as unread, the self-DM email should appear bold in LHN.

## Actual Result:
When marking the message as unread in self-DM, a new message line appears above the message, but the self-DM email doesn't appear bold in LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d94510a4-421d-4a4a-a198-ba1cf42865f8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0170aaaa13241fdd11</li>
        <li>Upwork Job ID: 1776255609655586816</li>
        <li>Last Price Increase: 2024-04-05</li>
    </ul>
</details>

**Comment by projects-ashish** [comment] 2024-04-06 07:50
# Proposal

**Please re-state the problem that we are trying to solve in this issue.**

When marking the message as unread in self-DM from RHN options, Then in the self-DM email/report doesn't appear bold in LHN. But when opened it then new Message line came before it.

### What is the root cause of that problem?
- In LHN, we don't bold the email/report title if the notification preference of the report is MUTE. In thi case, "DO NOT mark muted reports unread in the LHN (eg, in bold), even if they have unread messages"
- In self DM case, the notification preference is MUTE, so the this isn't bold.
- This is caused after this https://github.com/Expensify/App/pull/33779 and added below code to cause:

https://github.com/Expensify/App/blob/7dcb3e0eb79ed36c1cc7622fbc6375c7e084a917/src/components/LHNOptionsList/OptionRowLHN.tsx#L58


### What changes do you think we should make in order to solve the problem?

- As In self DM case, the notification preference is MUTE, we can not changes to preference in that case, we can do any one from below:

**Proposal 1:**
 We should not enable the "mark as unread" feature for notifications and also remove the "new message" label from this message since he is adding the message for himself. You can check this in Slack.
 
 **Proposal 2:**
 If we want to make exception to bold the report in LHN in case self DM, then we can do this:

 ```js
 const textUnreadStyle = optionItem?.isUnread && (optionItem?.isSelfDM ?? optionItem.notificationPreference !== CONST.REPORT.NOTIFICATION_PREFERENCE.MUTE) ? [textStyle, styles.sidebarLinkTextBold] : [textStyle];
    
 ```

**Comment by projects-ashish** [comment] 2024-04-06 07:56
Contributor details
Your Expensify account email: projects.ashishgadiya@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0145304c35e1920e71?viewMode=1&s=1110580755107926016

**Comment by cubuspl42** [comment] 2024-04-08 11:23
@slafortune 

> After this https://github.com/Expensify/App/pull/33779, we don't bold the title if the notification preference of the report is MUTE. In self DM case, the notification preference is MUTE, so the title isn't bold.

Doesn't this make the observed behavior the expected behavior? Maybe the report is a result of an outdated regression test?

**Comment by slafortune** [comment] 2024-04-08 17:56
Ah!  Thanks @cubuspl42 , Yes - I agree!

Closing

**Closed by slafortune** 2024-04-08 17:56 UTC
Labels: External, Daily, Help Wanted, Bug
