### ISSUE TITLE
 IOU - IOU preview does not disappear when deleting request first and then IOU thread

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26408] opened 2023-08-31 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26194
## Action Performed:
1. Go to staging.new.expensify,com
2. Request money from User B
3. As User A, go to IOU thread
4. Send an attachment, or a text reply
5. Delete the request
6. Delete the attachment

## Expected Result:
IOU preview disappears once the reply is deleted

## Actual Result:
IOU preview does not disappear when the reply is deleted. It appears as MYR0.00 and the report is empty

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7c667fec-fc07-42cf-a19f-7f1234147a44

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rojiphil** [comment] 2023-09-05 06:11
I think, this is dupe of #25930

**Closed** 2023-09-05 12:31 UTC
Labels: Daily, Overdue, Bug
