### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] "Expense" is showing as a "new comment" when opening the one expense report for the first time

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42472] opened 2024-05-22 13:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716320170918369
## Action Performed:
1. Submit a expense report with one expense as an employee
2. Sign in as a approver of the expense report (shouldn't be signed in before so that you don't have the expense report or transaction thread locally)
3. Throttle network connection to slow 3G, so that OpenReport takes a little bit to return
4. Click on the expense report to view the details

## Expected Result:
Should not see a green `New` line like a comment

## Actual Result:
"Expense" is showing as a "new comment" with greenline

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ed5e257f-1eb9-4b85-86c0-be4463027ec2

![Screenshot 2024-05-21 at 3 35 40 PM](https://github.com/Expensify/App/assets/38435837/53017c72-035f-4446-b7b7-c187783cb4f3)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a3e7a662efa0b69</li>
        <li>Upwork Job ID: 1794039154450477056</li>
        <li>Last Price Increase: 2024-06-07</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 102691860</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney / @zanyrenney</details>

**Comment by nkdengineer** [comment] 2024-05-23 07:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Expense" is showing as a "new comment" with greenline

### What is the root cause of that problem?
Before `OpenReport` API of the `expenseReport` is called, transaction thread report actions is empty

https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L152-L153

and then we return all report actions of the expense report which contains the `IOU` action here 
https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/libs/ReportActionsUtils.ts#L313-L315

So this action is displayed as a action in combine report
### What changes do you think we should make in order to solve the problem?
1. I see that the logic to calculate `reportActionsToDisplay` is added in this PR https://github.com/Expensify/App/pull/36657. As this comment, the aim of this to generate created action for money request report if it doesn't exist so I think we should use `allReportActions` which are all report actions of current report to calculate `reportActionsToDisplay` firstly and then we will use this to get the combine report actions [here](https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L152-L153
). So we should move this block [here](https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L485) to before this [block](https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L152-L153
) and use `allReportActions` instead of `reportActions`


https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L480-L485

2. We should add an extra param in `getCombinedReportActions` like `isCombineReport` and then we only return `reportActions` if transactionThreadReportActions is empty and the report isn't a combine report

```
if (isEmptyObject(transactionThreadReportActions) && !isCombineReport) {
    return reportActions;
}
```
 
https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/libs/ReportActionsUtils.ts#L313-L315

3. Pass `!!transactionThreadReportID` as `isCombineReport` param into `getCombinedReportActions` function

```
const combinedReportActions = useMemo(
    () => ReportActionsUtils.getCombinedReportActions(reportActionsToDisplay, transactionThreadReportActions, !!transactionThreadReportID),
    [reportActionsToDisplay, transactionThreadReportActions, transactionThreadReportID],
);
```
https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L152-L153

4. Finally, pass `sortedReportActions={reportActions}` here instead of `reportActionsToDisplay`

https://github.com/Expensify/App/blob/aa9bbcfb9b5a1ae0dd8050efad11eeabd9f65c58/src/pages/home/report/ReportActionsView.tsx#L554
### What alternative solutions did you explore? (Optional)
NA

**Comment by zanyrenney** [comment] 2024-05-24 16:13
Adding the external label - looks like NK engineer already has a proposal.

**Comment by zanyrenney** [comment] 2024-05-24 16:14
hey there @mollfpr - please can you review the proposal from @nkdengineer above! thanks!

**Comment by zanyrenney** [comment] 2024-05-24 16:17
Hey there! I am going OOO until the 9th of June. Please can you handle this and I will take it back once I return? Thanks!

**Comment by lschurr** [comment] 2024-05-28 02:03
Bump on this @mollfpr - Can you review the proposal?

**Comment by mollfpr** [comment] 2024-05-28 02:53
Looking now!

**Comment by lschurr** [comment] 2024-06-03 03:42
Hi @mollfpr - Looks like we still need your review here.

**Comment by lschurr** [comment] 2024-06-03 15:19
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1717427976382659

**Comment by nkdengineer** [comment] 2024-06-03 18:45
@mollfpr We use this in step 3 of my proposal to get combine report action.

**Comment by nkdengineer** [comment] 2024-06-06 04:04
> @nkdengineer Have you tried your solution with the step as this PR https://github.com/Expensify/App/pull/36657? I think if we use allReportActions in the step 4 this will won't be showing the optimistic money request preview.

@mollfpr It will work well because

1. If the iou report is combine report we will not show the optimistic money request preview
2. If not, `combinedReportActions` will only contain the report action of iou report so the optimistic money request preview is displayed if the condition is match when we calculate `reportActionsToDisplay` in the step 1 of my proposal
3. Actually the optimistic money request preview only depend on `allReportActions`

**Comment by lschurr** [comment] 2024-06-10 15:42
@mollfpr can you take a look at this one?

**Comment by zanyrenney** [comment] 2024-06-10 17:02
thanks for the hustle moving this one along @lschurr

**Comment by mollfpr** [comment] 2024-06-10 19:04
Thanks for the detail @nkdengineer!

We can proceed with the [proposal](https://github.com/Expensify/App/issues/42472#issuecomment-2126455601) then.

🎀 👀 🎀 C+ reviewed!

**Comment by nkdengineer** [comment] 2024-06-12 04:38
@mollfpr this [PR](https://github.com/Expensify/App/pull/43531) is ready for preview

**Comment by zanyrenney** [comment] 2024-07-10 13:48
@mollfpr requires payment through NewDot Manual Requests - owed $250 once comment above is complete.
@nkdengineer requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102691860) (Contributor) - paid $250 on upwork.

**Comment by zanyrenney** [comment] 2024-07-10 13:49
@srikarparsi please can you do me a favour and once this checklist is complete, close out the issue? 

I am OOO until Tuesday 16th so don't want to keep this open during my OOO if all the steps are complete. 

I have also DM'd @mollfpr

**Comment by JmillsExpensify** [comment] 2024-07-11 17:52
$250 approved for @mollfpr

**Comment by srikarparsi** [comment] 2024-07-15 18:55
The regression steps look good to me. @zanyrenney once you're back from OOO and you have some time, do you know who's in charge of adding the regression test to TestRail?

**Comment by zanyrenney** [comment] 2024-07-17 11:56
Yep, i can add them!

**Comment by zanyrenney** [comment] 2024-07-17 11:57
Added, closing! https://github.com/Expensify/App/issues/45595

**Closed by zanyrenney** 2024-07-17 11:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
