### ISSUE TITLE
[$1000]  adds blue border to three dot on closing delete workspace context menu using ESC

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18826] opened 2023-05-12 08:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to workspace
2. click three dots to open delete menu
3. Press ESC to close the menu

## Expected results: 
should close the menu without any blue border
## Actual results: 
adds blue border to three dots

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9f686c7b-1b00-4d6f-af00-5b2bf31245f6

https://github.com/Expensify/App/assets/43996225/eb6ebbc5-912b-4c26-ba67-9470ae49a0a6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683802759431379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6ca7d54980bcbc9</li>
        <li>Upwork Job ID: 1658572235686973440</li>
        <li>Last Price Increase: 2023-05-16</li>
    </ul>
</details>

**Comment by johncschuster** [comment] 2023-05-12 21:42
I am going OOO so re-assigning a new coach to oversee this

**Comment by dukenv0307** [comment] 2023-05-16 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On the web, if you click on three dot on closing delete workspace and then press Esc, the three dot button is highlighted with a blue border.

### What is the root cause of that problem?

The default behavior when pressing Esc after open model delete workspace. In this case, when button ESC is pressed this `Pressable` gets focused and the blue outlines are shown by using the :focus-visible CSS styling.
```
  :focus-visible {
     outline: 0;
     box-shadow: inset 0px 0px 0px 1px #5AB0FF;
  }
```

### What changes do you think we should make in order to solve the problem?


Remove focus styles in `Pressable` component by adding already styles `styles.noOutline`

### What alternative solutions did you explore? (Optional)
NA

### Result

https://github.com/Expensify/App/assets/129500732/0e25c3ae-9cf9-44d9-8158-46e0d9e088ac

**Comment by adelekennedy** [comment] 2023-05-16 20:36
I can reproduce and I'm not seeing a duplicate issue - moving to external

**Comment by adelekennedy** [comment] 2023-05-16 20:45
@dukenv0307 now that this issue has moved to external we'll consider your proposal

**Comment by mananjadhav** [comment] 2023-05-16 20:51
Do we really want to fix this? This is generally the behavior of the focused button. 

I am going to ask @Expensify/design @shawnborton to confirm if we think this is necessary? wdyt @flodnv ?

**Comment by shawnborton** [comment] 2023-05-17 13:15
Yeah, I feel like this is fine and we can close this out.

**Closed by shawnborton** 2023-05-17 13:15 UTC
Labels: External, Daily, Help Wanted, Bug
