### ISSUE TITLE
User is able to access edit side panel through deeplink even if user is not able to edit task

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23610] opened 2023-07-26 02:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a workspace with account A and invite account B into the workspace
2. Inside the announce room click on the plus icon > assign task
3. Give the task a title and do not assign anyone and confirm the task
4. Go to account B and open the announce room of account A's workspace
5. Open the last task created by account A
6. Try to edit the task title by hovering over the title and notice user B is not able to edit the task title
7. Click on the URL bar of the browser and append "/title" on the current URL and click enter
## Expected Result: 
 "Hmmm its not here" page should show up since user B is not able to edit the task title
## Actual Result: 
Account B is able to edit the title by using deep link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.45-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8031f0a8-e90b-4ea0-a459-00e31dbe634f

https://github.com/Expensify/App/assets/43996225/680017c1-9c91-429d-a58f-1e49db68f674

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690272321815229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sakluger** [comment] 2023-07-27 23:42
Thanks @dukenv0307, this does look like a duplicate of that one. Closing.

**Closed by sakluger** 2023-07-27 23:42 UTC
Labels: Daily, Bug
