### ISSUE TITLE
Nothing happen when clicking enter on invite-message page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21718] opened 2023-06-27 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any workspace
2. Go to Member --> Invite
3. Select a member > Click "next"
4. In the welcome message type something 
5. Click enter
## Expected Result: 
The message should be submitted
## Actual Result: 
Nothing happen when clicking enter on invite-message page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bf351005-7772-4cda-be21-4fd00394b942

https://github.com/Expensify/App/assets/43996225/7679d403-0c8a-45a6-a309-e15e6e5144c4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @cheng
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687620757310639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-06-27 17:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ae331c69e71ee25bc5103df956525da6d8a913c3/src/pages/workspace/WorkspaceInviteMessagePage.js#L202
We don't set submitOnEnter prop for this text input
### What changes do you think we should make in order to solve the problem?
We should add submitOnEnter prop in the text input here
https://github.com/Expensify/App/blob/ae331c69e71ee25bc5103df956525da6d8a913c3/src/pages/workspace/WorkspaceInviteMessagePage.js#L202
### What alternative solutions did you explore? (Optional)

**Comment by Nathan-Mulugeta** [comment] 2023-06-28 20:02
This issue is dupe of this issue [#18429](https://github.com/Expensify/App/issues/18429)

**Comment by trjExpensify** [comment] 2023-06-30 13:31
Yup, nice! Agree with @JmillsExpensify's comment here: https://github.com/Expensify/App/issues/18429#issuecomment-1535677945

Closing!

**Closed by trjExpensify** 2023-06-30 13:31 UTC
Labels: Daily, Overdue, Bug
