### ISSUE TITLE
[HOLD for payment 2024-05-06] [$125] Sending image with message has `'` appears as HTML for temporarily until the image appears fully

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40578] opened 2024-04-19 15:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713478343633609

## Action Performed:
1. Open any chat
2. Write a message like "It's breaking" with apostrophe
3. Paste an image and send the image

## Expected Result:
Text is sent without any weirdness

## Actual Result:
Message appears as it&#x27;s breaking
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/44df0ad1-6527-4bf8-8e95-b767704387f4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192ead78ec42f211a</li>
        <li>Upwork Job ID: 1782467123537166336</li>
        <li>Last Price Increase: 2024-04-22</li>
<li>Automatic offers: </li>
<ul>
<li>rojiphil | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by tgolen** [comment] 2024-04-22 15:49
I believe @ShridharGoel's proposal is probably the right fix for this. It might need to be ````${parser.htmlToText(htmlForNewComment)}\n${CONST.ATTACHMENT_UPLOADING_MESSAGE_HTML}`;````

**Comment by amyevans** [comment] 2024-04-22 17:50
Alright, the fix is certainly straightforward and agreed upon, therefore I'm going to post the price as $125 and let an open source contributor post the PR.

**Comment by rojiphil** [comment] 2024-04-22 18:13
Yes. This is a straightforward fix. @ShridharGoel [proposal](https://github.com/Expensify/App/issues/40578#issuecomment-2067772888) LGTM.
🎀👀🎀 C+ reviewed

**Comment by sakluger** [comment] 2024-05-03 16:00
@greg-schroeder can you handle payment on Monday since I'll be OOO? Here are the Upwork offer links: https://github.com/Expensify/App/issues/40578#issuecomment-2083831708

**Comment by greg-schroeder** [comment] 2024-05-07 09:39
Taking care of payments

**Comment by greg-schroeder** [comment] 2024-05-07 09:41
@ShridharGoel you have to accept the offer in Upwork before we can pay you, FYI!

**Comment by greg-schroeder** [comment] 2024-05-07 09:41
@rojiphil can you take care of [the checklist](https://github.com/Expensify/App/issues/40578#issuecomment-2083831732) above?

**Comment by sakluger** [comment] 2024-05-07 21:32
Thanks Greg! Taking back over.

Just waiting for @ShridharGoel to accept the Upwork offer and @rojiphil to complete the BZ Checklist before we can close the issue.

**Comment by rojiphil** [comment] 2024-05-08 04:54
* [x]  [@rojiphil] The PR that introduced the bug has been identified. Link to the PR: [Offending PR](https://github.com/Expensify/App/pull/39007)
* [x]  [@rojiphil] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: [Added comment](https://github.com/Expensify/App/pull/39007/files#r1593371218)
* [x]  [@rojiphil] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required. The existing checklist is good enough to capture such issues.
* [x]  [@rojiphil] Determine if we should create a regression test for this bug. : I don’t think this is required
* [x]  [@rojiphil] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by rojiphil** [comment] 2024-05-08 04:55
> and @rojiphil to complete the BZ Checklist

@sakluger BZ Checklist is completed.

**Comment by sakluger** [comment] 2024-05-09 21:36
Thanks! I paid @ShridharGoel so we're all good here.

**Closed by sakluger** 2024-05-09 21:36 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
