### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Web -  Pasting emojis freezes cursor position in composer box (works fine in edit message)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27672] opened 2023-09-18 13:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. React to any message with any emoji
4. Right click on reaction and copy the emoji text
5. Paste the copied emoji text few times in compose box and observe that cursor is freezes after first pasted emoji
6. Try to paste similarly in edit message and observe that it works fine

## Expected Result:
App should move cursor to end on pasting the emojis in compose box as it does in edit message box

## Actual Result:
App freezes cursor after first pasted emoji in compose box

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a43d2682-54b0-4159-9f5c-a4bcee2fd3e7

https://github.com/Expensify/App/assets/93399543/1d06fd2c-9adb-4b40-8ae0-da0c378fa560

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694883795401949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0141004fff370e0c4e</li>
        <li>Upwork Job ID: 1703759230392123392</li>
        <li>Last Price Increase: 2023-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26897303</li>
<li>jeet-dhandha | Contributor | 26897305</li>
<li>dhanashree-sawant | Reporter | 26897308</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-09-18 14:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Cursor staying after the first emoji in the text input when continuosly pasting ":joy:".

### What is the root cause of that problem?
- Cursor position is not being as we are comparing wrong values. `commentRef.current & newComment`

https://github.com/Expensify/App/blob/9b302c980f4dcaba08d113f47d4852dc121c7e4e/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L188

- I am still not sure why we are comparing `commentRef.current` with `newComment` instead of `commentValue`.

### What changes do you think we should make in order to solve the problem?
- We should compare the `newComment` with the `commentValue` instead of `commentRef.current`.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by Christinadobrzyn** [comment] 2023-09-18 15:53
This is reproducible and I can't find another GH related so I think we can move forward with reviewing these proposals.

**Comment by Christinadobrzyn** [comment] 2023-09-19 21:37
Hi @Ollyws would you be able to take a peek at the proposals to see if they will work?

**Comment by jeet-dhandha** [comment] 2023-09-27 09:51
@Ollyws - PR Ready for Review.

**Comment by jeet-dhandha** [comment] 2023-10-10 14:38
Bump for Payment.

**Comment by Christinadobrzyn** [comment] 2023-10-10 19:35
Payouts due:

Issue Reporter: $50 @dhanashree-sawant (paid in Upwork)
Contributor: $500 + $250 bonus @jeet-dhandha (paid in Upwork)
Contributor+: $500 + $250 bonus @Ollyws (paid in Upwork)

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/27672#issuecomment-1738370915

Upwork job is [here](https://www.upwork.com/jobs/~0141004fff370e0c4e) (it's now closed so let me know if you need something)

Closing as complete!

**Closed by Christinadobrzyn** 2023-10-10 19:35 UTC
Labels: External, Daily, Awaiting Payment, Bug
