### ISSUE TITLE
Web - Search - Focus is not showm on first entry after clearing search box query

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51405] opened 2024-10-24 12:21 UTC
:zxIf you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.53-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** negasofonias@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open search dialog using ctr+K
2. type some search query, select the query and clear the query using "Delete"
3. Observe that first line item after is not focused from the list

## Expected Result:
First line item should be focused after clearing search query

## Actual Result:
First line item is not focused

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/9b92fc6a-2837-4e30-993a-022df6ba459b

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-24 12:22
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by joekaufmanexpensify** [comment] 2024-10-24 13:42
Agreed. The video is wrong. I also tried reproducing by following the written steps, and I don't understand what the bug is, or see any behavior that seems unexpected. 

Closing this for now, but please feel free to reopen if there is in fact a bug here once the issue is updated so the video matches the testing sterps.

**Closed by joekaufmanexpensify** 2024-10-24 13:42 UTC
Labels: Daily, Bug

**Comment by IuliiaHerets** [comment] 2024-11-04 16:24
Sorry, I added the wrong video first, fixed it.
Issue is still repro, build - v9.0.56-9 

https://github.com/user-attachments/assets/b1cad018-4bfb-43e5-9b88-f216cb9a7c1a

**Comment by joekaufmanexpensify** [comment] 2024-11-04 21:43
@IuliiaHerets Thanks for sharing the updated video. I watched it several times, and I still don't understand what the bug is. The search field is focused after you delete your search query, and I am not quite sure what you mean by "first entry". 

Do you mind clarifying further what the bug is here? I am going to close again for now as I don't see any bug currently, but please feel free to reopen if there is more context here about what the bug is here.
