### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000]  Payment delete modal menu missing margin at the top

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18581] opened 2023-05-08 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open App
2. Go to Settings > Payments
3. If no payment has been added then add any one
4. Press on the added payment method
5. It will open the delete modal from the
6. Press on delete
7. It will open a confirmation modal
8. Observe both modal’s top padding

## Expected Result:
There should be some padding between the payment option and the delete modal
## Actual Result:
There is no padding between the payment option and the delete modal

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236858004-c8c2d9f0-7003-4ee6-aac5-2de8179a74d7.mov

![delete-modal-no-spacing](https://user-images.githubusercontent.com/43996225/236858007-f44f9535-c3cf-4dae-ae1d-ffa41ea1a3fd.png)

https://user-images.githubusercontent.com/43996225/236858021-0e9f66f3-ec92-4422-91df-e137b733d7cc.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1682631614889629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01510361e941b5686d</li>
        <li>Upwork Job ID: 1656321116447989760</li>
        <li>Last Price Increase: 2023-05-10</li>
    </ul>
</details>

**Comment by jayeshmangwani** [comment] 2023-05-08 14:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Delete Payment modal has a missing margin at the top compared to the payment option.

### What is the root cause of that problem?
At the time of calculating the top anchor position in setPositionAddPaymentMenu, we are not adding any additional top margin outside the touch area, so when the user press MenuItem(Payment method), we count the top position like this, MenuItem height + Pressed MenuItem component position from top `(position.top + position.height)`

https://github.com/Expensify/App/blob/4a4b22bc3bdd801ae13373422dfa15f35e3299c6/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L153-L162


### What changes do you think we should make in order to solve the problem?
We can add the top margin many ways, but I would suggest that when calculating the `anchorPositionTop`, we should add the six margins to the top of `position.top + position.height` , 

 we should add six here in `anchorPositionTop: position.top + position.height + 6`
https://github.com/Expensify/App/blob/4a4b22bc3bdd801ae13373422dfa15f35e3299c6/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L155-L160

we can add the top margin to individual PopOver too, like this `top: this.state.anchorPositionTop + 6` , but for adding the top margin to all the PopOver on page,

https://github.com/Expensify/App/blob/4a4b22bc3bdd801ae13373422dfa15f35e3299c6/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L436-L439

**Why 6 margin ?**
We have the 6 margins on this page between Add Payment button and Add Payment popover for consistency we can add 6 (or we can add a margin by confirming with the design team).

Throughout the app, we added different margins from the top and bottom of the touchable area, but for this page, we can use 6.

I am attaching a video here with 6 pixel space

<details>
  <summary>Result</summary>
  

https://user-images.githubusercontent.com/105707133/236840296-75977b4b-824c-4210-9511-57eb46651f0f.mov


</details>

### What alternative solutions did you explore? (Optional)
N/A

**Comment by bernhardoj** [comment] 2023-05-10 09:23
We do nothing before here https://expensify.slack.com/archives/C049HHMV9SM/p1670338674482959

**Comment by Nikhil-Vats** [comment] 2023-05-12 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no space between the payment delete popover and the payment method.

I would also like to highlight two related issues that are quite important I believe -
1. On the web and desktop app (on large screen size), the Confirm delete payment modal has inconsistent styling with other Confirm Modals like delete workspace and delete comment. The delete payment modal is not centered on the screen like others and it doesn't look good at all.

2. If we show the `MakeDefaultButton` then the buttons have little space in between. See the image below.

<details>
  <summary>Very less gap between buttons</summary>
 
<img width="356" alt="image" src="https://github.com/Expensify/App/assets/31413407/c7eb6823-19b7-4521-ae44-db771143ef36">
</details>

### What is the root cause of that problem?
The root cause of this issue is how we calculate the `anchorPositionTop` of the delete `Popover`. `anchorPositionTop` is equal to the top position of the target (PaymentMethod) plus the height of the target which doesn't leave any space between the `PaymentMethod` and the `Popover` component.

The root cause of additional similar issues mentioned -
1. Confirm Delete Modal not centred - The `BasePaymentsPage` uses the `ConfirmContent` component with its own styles and `anchorPosition` rather than using the `ConfirmModal` which is used everywhere else. This is an inconsistency with all other similar modals and should be fixed.
2. Very less gap between `MakeDefaultButton` and `DeletePaymentMethodButton` - There is no style added for `gap` in the styles prop of the `View` wrapper.

### What changes do you think we should make in order to solve the problem?


The add payment button has a vertical `padding` of `6px` so for keeping consistency we can add the same `6px` to the `anchorPositionTop` in `setPositionAddPaymentMenu`.

To fix other issues -
1. Use `ConfirmModal` instead of `ConfirmContent` to center the delete payment method confirm modal.
2. Use `styles.gap1` in the parent `View` of `MakeDefaultButton` and `DeletePaymentMethodButton`.

### What alternative solutions did you explore? (Optional)
In my opinion from a UX perspective clicking on the payment method to reveal a Popover which has a delete button and other buttons like make default method is inconsistent with our other similar menus and also unintuitive.

For example - The delete workspace popover is opened using the `ThreeDotsMenu` which looks better and is also better for UX.

<img width="1188" alt="Screenshot 2023-05-13 at 12 45 21 AM" src="https://github.com/Expensify/App/assets/31413407/cf906812-184a-42bd-be1c-70d938451bfd">

I think we should use `ThreeDotsMenu` for showing the delete and make default payment method button. Also, clicking on the delete button should show a centred modal using the `ConfirmModal` component.

I strongly believe we should do this but I added it as an alternative solution because its scope is bigger than the core issue here.

A rough final look should be something like this -
Please note that the Paypal button also looks selected but that is because I wanted to visualize the UI so didn't clean up that code and wrote a rough version of it -

![delete_payment_method](https://github.com/Expensify/App/assets/31413407/aa748596-e703-4b71-9dea-5905cc22706d)

**Comment by Nikhil-Vats** [comment] 2023-05-12 19:57
> We have the 6 margins on this page between Add Payment button and Add Payment popover for consistency we can add 6 (or we can add a margin by confirming with the design team).

It seems like in your screenshot the top border has less width than the other three sides due to which its difficult to notice but it looks okay here -
<img width="374" alt="image" src="https://github.com/Expensify/App/assets/31413407/671d5b81-3fac-447a-8232-66d88be190b0">

**Comment by PauloGasparSv** [comment] 2023-05-13 19:39
Thks for bringing [this](https://github.com/Expensify/App/issues/18581#issuecomment-1541720023) up @bernhardoj.

I'm not sure why we did nothing last time since it looks like everyone agreed it wasn't a bug but that we should add the space. I think we should fix it this time.

**Comment by mananjadhav** [comment] 2023-05-14 17:21
I am not sure either. @shawnborton do you want to chime in here if we are open to fix it now?

**Comment by shawnborton** [comment] 2023-05-15 16:16
I'm cool with adding some margin above the menu.

**Comment by slafortune** [comment] 2023-05-15 17:58
I actually feel like that green box around the delete button seems odd to have - or doesn't seem to add anything.  Are we set on that staying?

**Disclaimer** _*not a designer*_

**Comment by mananjadhav** [comment] 2023-05-15 20:21
thanks for the confirmation @shawnborton. Could you also specify how much margin do we want to keep?

@slafortune I think the green border would be required to show the popup? It is due to no margin we can't identify the border.

That being said, I think @jayeshmangwani's initial proposal is good to go with. @Nikhil-Vats's proposal is also on the similar lines and as they also agree their alternative solutions are not relevant to fix the current PR.


@PauloGasparSv All yours.

**Comment by PauloGasparSv** [comment] 2023-05-15 20:28
Thks @mananjadhav, I'm assigning @jayeshmangwani since it was the first proposal here

**Comment by jayeshmangwani** [comment] 2023-05-15 21:22
@PauloGasparSv @mananjadhav  [PR](https://github.com/Expensify/App/pull/18977) is ready for review

@shawnborton Added margin 6 between the delete modal and Payment Option and it looks like this
<img width="1123" alt="Screenshot 2023-05-16 at 2 51 09 AM" src="https://github.com/Expensify/App/assets/35371050/cbbae449-7ff2-47c3-935e-66fb982ade93">

**Comment by shawnborton** [comment] 2023-05-16 06:25
We should do everything using blocks of our 4px spacer. We already have some helper classes built in for this too. So you could use something like `mt2` which is margin-top-2xSpacer, which will give you a margin top of 8px.

**Comment by jayeshmangwani** [comment] 2023-05-16 06:44
@shawnborton We can add 8 directly to the `position.top + position.height` sum
https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L153
As we are calculating anchorPositionTop in state value and using it at every PopOver on the page, here we can not use mt2 from styles.
e.g. here we are calculating anchorPositionRight by adding an additional 13 px 
https://github.com/Expensify/App/blob/dd5fbb6d12e5daa66458b3db07f0ea88dbc4d449/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L156-L157

**Comment by mananjadhav** [comment] 2023-05-16 06:51
@jayeshmangwani You can add the value to `variables.js` and use it here.

**Comment by jayeshmangwani** [comment] 2023-05-16 06:59
> @jayeshmangwani You can add the value to `variables.js` and use it here.

@mananjadhav Right now there are 4 constants in variables.js, that have an 8px value

1. componentBorderRadius
2. componentBorderRadiusNormal
3. iconSizeXXSmall
4. sliderBarHeight

IMO we should add a new variable whose name is relevant to Modal/Popover
`e.g. popoverTopSpacing`

**Comment by mananjadhav** [comment] 2023-05-16 08:49
Yeah that's what I meant when I said `add the value` instead of hardcoding 8. While we're at it, we should also move 13 to the variables.

**Comment by jayeshmangwani** [comment] 2023-05-16 10:53
@mananjadhav Updated code to use variables value and updated desktop and web video with 8 top margins to PR

**Comment by mananjadhav** [comment] 2023-05-25 04:49
I think the closest PR where we add the margin changes was [here](https://github.com/Expensify/App/pull/9622). I won't treat this as a bug (more so feature request/UI change) because when the earlier PR was reviewed, we didn't set any requirements for the margin top.

Neither I think we should add a regression test for this one. wdyt @slafortune @PauloGasparSv ?

**Comment by PauloGasparSv** [comment] 2023-05-25 12:47
I agree @mananjadhav. IMO we could reference that P.R. as the one that "added the bug" and mark the rest of the checklist  as complete but do nothing : )

**Comment by mananjadhav** [comment] 2023-05-25 20:27
@slafortune this one is ready for payout then. thank you.

**Comment by slafortune** [comment] 2023-05-25 20:45
@mananjadhav and @jayeshmangwani offers sent!

**Comment by mananjadhav** [comment] 2023-05-25 21:13
Accepted @slafortune

**Comment by jayeshmangwani** [comment] 2023-05-26 05:25
@slafortune I am not able to accept the offer, shows offer withdrawal by the client

<img width="700" alt="Screenshot 2023-05-26 at 10 53 14 AM" src="https://github.com/Expensify/App/assets/35371050/ae7d61d4-25a4-4bbf-af88-010015b97880">

**Comment by slafortune** [comment] 2023-05-26 11:48
Shoot!  I've had run into so many error with Upworks recently. Resent @jayeshmangwani

**Comment by jayeshmangwani** [comment] 2023-05-26 11:51
Thanks @slafortune , Offer accepted

**Closed** 2023-05-26 11:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
