### ISSUE TITLE
[Distance]  Distance - "Hmm...It's not here" page is displayed instead the route receipt image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26827] opened 2023-09-05 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26704
## Action Performed:

1. Launch App login with user which has workspace
2. Tap on FAB > Request money > Distance
3. Add Start and Finish 
4. Tap Next
5. Select WS
6. Tap on Request
7. Tap on map

## Expected Result:
Verify the route receipt image also displays there for the expense

## Actual Result:
"Hmm...It's not here" page is displayed instead the route receipt image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.64-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/5f2e74c0-09cb-4c8f-be05-149f940c0ce0

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hayata-suenaga** [comment] 2023-09-05 23:30
I cannot reproduce this

https://github.com/Expensify/App/assets/98560306/ce7f29fc-423d-450f-9cc5-e10f31c8d48b

**Comment by hayata-suenaga** [comment] 2023-09-06 03:42
QA tester also couldn't reproduce after the latest update. closing this issue 🙇

**Closed by hayata-suenaga** 2023-09-06 03:42 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug

**Comment by mountiny** [comment] 2023-09-06 07:07
@hayata-suenaga lets please keep removing the `DeployBlockerCash` label when its not a blocker, thanks!
