### ISSUE TITLE
[$500] There's a lot of extra space above the receipt

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35921] opened 2024-02-06 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V1.4.37-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @amyevans 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707179218830079

## Action Performed:
1.Initiate a request money by scanning a receipt
2.Tap the preview 
## Expected Result:
No extra space above the receipt image
## Actual Result:
There's a lot of extra space above the receipt
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![IMG_0028](https://github.com/Expensify/App/assets/38435837/81211efe-a245-445c-9cd9-3a7f3cceea46)

https://github.com/Expensify/App/assets/38435837/1396b1cd-2bc1-4717-81b3-cfb63c336fae

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01afdff2fbe1dee085</li>
        <li>Upwork Job ID: 1754909179622940672</li>
        <li>Last Price Increase: 2024-02-20</li>
    </ul>
</details>

**Comment by parthvaghani** [comment] 2024-02-06 17:32
Proposal

Please re-state the problem that we are trying to solve in this issue.

There's a lot of extra space above the receipt

What is the root cause of that problem?
https://github.com/Expensify/App/blob/main/src/styles/utils/index.ts#L727

What changes do you think we should make in order to solve the problem?


When marginTop is 0, it is removing extra space above the receipt. that's where we should calculate height correctly and dynamically

**Comment by parthvaghani** [comment] 2024-02-06 17:37
Contributor details
Your Expensify account email: vaghani98@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pvaghani

**Comment by parthvaghani** [comment] 2024-02-06 17:41
Contributor details
Your Expensify account email: vaghani98@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pvaghani

**Comment by parthvaghani** [comment] 2024-02-06 18:13
Hello @m-natarajan could you please help with storing my contributor details?

**Comment by parthvaghani** [comment] 2024-02-07 16:49
Contributor details
Your Expensify account email: parthvaghani14@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/pvaghani

**Comment by parthvaghani** [comment] 2024-02-12 15:54
@shubham1206agra Could you please assign this bug to me?

**Comment by shawnborton** [comment] 2024-02-20 15:34
Yup, that's my thinking!

**Comment by miljakljajic** [comment] 2024-02-23 12:09
Referenced this issue in the original, closing.

**Closed by miljakljajic** 2024-02-23 12:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
