### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500] Profile page opens with a lag when clicking from a chat

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37986] opened 2024-03-08 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709868083089229

## Action Performed:
1. Login with high traffic account
2. Go to any report that has messages.
3. Click on user avatar

## Expected Result: 
Profile page should appear smoothly

## Actual Result: 
It's a bit laggy when Profile page appears.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/d457cd48-fc27-4a81-9e4c-5f5a1c6025e7

https://github.com/Expensify/App/assets/38435837/3a20d601-0466-4ccc-8995-e72ee3c9b29b

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0127b4383974c1d34e</li>
        <li>Upwork Job ID: 1768699308285607936</li>
        <li>Last Price Increase: 2024-03-15</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2024-03-08 17:03
offending PR as I mentioned earlier in slack: https://github.com/Expensify/App/pull/37223

**Comment by dragnoir** [comment] 2024-03-11 11:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Profile page lagging when opened.

### What is the root cause of that problem?

After the updates from https://github.com/Expensify/App/pull/37223

Every component using `withOnyx` to `key: ONYXKEYS.PERSONAL_DETAILS_LIST` will be rendered once we open the profile page and this cause lots of browser memory usage in the background due to lost of images called.

### What changes do you think we should make in order to solve the problem?

On profile page, we need to check if we already have the profile details available, if so, we don't have to call the API.

```js
const profileDetailsAvailable = details.avatar && details.avatarThumbnail && details.displayName && details.login && details.timezone;

useEffect(() => {
        if (ValidationUtils.isValidAccountRoute(accountID) && !profileDetailsAvailable) {
            PersonalDetails.openPublicProfilePage(accountID);
        }
    }, [accountID, profileDetailsAvailable]);
```

**Comment by trjExpensify** [comment] 2024-03-11 11:25
>We haven't added any new logic. Before our PR, the API was still called under some conditions. We just made the conditions less strict. This performance glitch must have been present before; it's just more easily observable now.

@puneetlath @stitesExpensify as you guys were involved in #36610, do you agree with this assessment or do you think this is a regression from [the PR](https://github.com/Expensify/App/pull/37223)?

**Comment by stitesExpensify** [comment] 2024-03-11 18:07
I think that both things are true. The performance issue did exist under some conditions, but that PR has caused it to happen under all conditions. To me that is a regression since this was not happening all of the time before and is happening now.

**Comment by kmbcook** [comment] 2024-03-12 15:00
https://github.com/Expensify/App/issues/36610 is unusual in that it requires the API to be called every time an avatar is clicked. Most issues are about improving some aspect of user experience, such as this one. 36610 is different in that it is about implementing a specified method of operation (not about improving a specified aspect of user experience).

It is true that always calling the API does solve some problems, and that there may be other ways to solve those problems. It may be appropriate to create additional issues specific each of those problems and invite proposals.

This issue is not a regression, rather it is a consequence of implementing the method of operation required by the other issue.

**Comment by puneetlath** [comment] 2024-03-12 16:32
Question: if you already have the personal details locally for userA. And then you open the profile page of userA which calls the API and returns/merges the same personal details that you already have. Why does anything re-render? Nothing in Onyx or any of the props has actually changed right?

**Comment by kmbcook** [comment] 2024-03-12 18:13
The personalDetails prop to ProfilePage contains a list of personal details for all users in the high traffic account (a lot of data), not just the personal details of the user whose profile is shown in that page. It might be a good idea to change the page so that it only depends upon the personal details of one user.

**Comment by kmbcook** [comment] 2024-03-12 18:25
Doesn't Onyx have to do a lot of work to determine that nothing in personalDetails has actually changed (assuming no changes), after the merge to personalDetails which results from the API call? All that work is done on the client. Is that why a lag is observed?

**Comment by puneetlath** [comment] 2024-03-12 18:41
Can we use the selector feature of withOnyx to only subscribe to personalDetails updates for the one accountID we're looking at?

**Comment by kmbcook** [comment] 2024-03-12 18:49
OK, I'd be willing to propose that as a solution to this issue.

**Comment by cubuspl42** [comment] 2024-03-13 09:12
@kmbcook No proposal is needed. If you agree that this is a good solution to the uncovered performance problem, implement it and see if you observe the improvement.

If you can easily reproduce the problem in the first place, of course.

**Comment by trjExpensify** [comment] 2024-03-14 19:15
What are the next steps, here? Are we assigning @cubuspl42 and @kmbcook?

**Comment by stitesExpensify** [comment] 2024-03-14 19:33
> Using a high-traffic account, and never making the API call, response time is still slow and only slightly faster than always making the API call.

This seems like its own problem in and of itself. If we don't make the API call and it's still slow then there must be something wrong on the front end right?

**Comment by cubuspl42** [comment] 2024-03-15 09:29
@trjExpensify 

I think that it's been decided that the answer is "no".

https://github.com/Expensify/App/issues/36610#issuecomment-1996123739

**Comment by trjExpensify** [comment] 2024-03-15 18:01
Got it, so `External` and `Help wanted`.

**Comment by puneetlath** [comment] 2024-03-16 14:43
That's interesting. Do we even need to have `isLoading` in Onyx at all? What would happen if we didn't?

**Comment by c3024** [comment] 2024-03-17 13:49
I tried checking how removing `isLoading` affects performance. I tried 5 times and on average, it looks like it reduces ~250ms scripting time.

`isLoading` of `personalDetail` is used only in `ProfilePage` and `ProfileAvatar` as far as I have found.

Removing `isLoading` in these pages shows `NotFound` page briefly before showing the details of the user when the profile page or avatar are accessed with deep link. With `isLoading` it shows a loading indicator before showing the details of the user when the profile page or avatar are accessed with deep link.

**Comment by trjExpensify** [comment] 2024-03-18 11:01
>Removing isLoading in these pages shows NotFound page briefly before showing the details of the user when the profile page or avatar is accessed with deep link

Ah, and that looks pretty janky in practice. 🤔

**Comment by puneetlath** [comment] 2024-03-18 19:46
Ok got it. @tienifr's suggestion seems pretty good then. What do you think @c3024?

**Comment by c3024** [comment] 2024-03-19 02:50
Yes, @tienifr 's [main proposal here](https://github.com/Expensify/App/issues/37986#issuecomment-2001906544) looks good to me as well.

**Comment by trjExpensify** [comment] 2024-03-19 16:09
Cool, so are we assigning @tienifr then? :)

**Comment by c3024** [comment] 2024-04-11 05:52
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #20144 
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20144/files#r1560462615
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: This is not a case that can be identified sooner or incorporated in the checklist. So, no discussion has been started.
* [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression test proposal
1. Logon to ND with a high traffic account
2. Go to any report with several messages
3. Press any user avatar in the report
4. Verify profile page appears seamlessly without any lag
5. Repeat step 3 for some other avatars and verify that the profile pages appear seamlessly without any lag

👍 or 👎

**Comment by trjExpensify** [comment] 2024-04-16 00:45
👋 Payment summary as follows:

- $500 to @c3024 for the C+ review - paid
- $500 to @tienifr for the fix - paid
- Bug was reported by @hungvu193, but we don't pay bounties for them anymore.

We have a [regression test](https://expensify.testrail.io/index.php?/cases/view/2458011&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296759) for testing opening the profile from a user in a conversation, so I think we should be able to catch any noticeable lag or issues with loading that, to the point where we don't need another one. 

Thanks ya'll, closing!

**Closed by trjExpensify** 2024-04-16 00:45 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
