### ISSUE TITLE
[$1000] Splitting bill shows deleted message for a brief moment of time

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19487] opened 2023-05-23 20:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign into staging New Expensify 
2. Select + icon > click Split Bill > create an amount > Choose person > Next > click Split button
3. A 1:1 chat should open with the Split Bill Details
4. Click the Split Amount Box in the chat (money report box)
5. Notice [Deleted Message] at the top of the page for a moment and then the amount box shows again

## Expected Result:
Splitting bill should not show the deleted message for a brief moment of time

## Actual Result:
Deleted message appears for some period of time and then it changes to the message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android / native
- [X] Android / Chrome
- [X] iOS / native
- [X] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/483a017a-48b8-4854-9766-80e26c124432

https://github.com/Expensify/App/assets/43996225/fdda1662-b744-4967-8157-5700395c7194

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684592253606429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ef39d4d0e55c94e</li>
        <li>Upwork Job ID: 1661459081945231360</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-05-24 19:48
I'm able to reproduce it, I don't think it's related to an existing issue. I think this can be external?

**Comment by tienifr** [comment] 2023-05-25 16:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

[Deleted message] is shown in a new split bill thread

### What is the root cause of that problem?

1. When we create a new thread for `split bill` action, we call onIOUPreviewPressed function. But we pass `props.requestReportID` as parentReportID this would be empty in split bill


https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/components/ReportActionItem/MoneyRequestAction.js#L122-L125

https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/pages/home/report/ReportActionItem.js#L184-L188

2. We update the displayName in 

https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/libs/SidebarUtils.js#L109

3. Because the parentReportID is empty so we can't find the parentReportAction, that why we return the displayName as `deletedMessage` ('[Deleted Message]')

https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/libs/ReportUtils.js#L1116-L1121

### What changes do you think we should make in order to solve the problem?

update this line https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/components/ReportActionItem/MoneyRequestAction.js#L122

to 

```
 props.chatReportID 
```

as what BE returns

### Result

https://github.com/Expensify/App/assets/113963320/4b138d39-5f44-4bb7-a4f8-6618d2f1f373

**Comment by s77rt** [comment] 2023-05-25 23:39
@brianlee1025 Thanks for the proposal. I don't think your RCA is correct. The App is based on an offline first design and we don't need to wait for the server response (you can reproduce the bug when offline - this should not happen). Apparently the root cause is that the optimistic data that we create is incorrect.

**Comment by s77rt** [comment] 2023-05-25 23:53
@tienifr Thanks for the proposal. Your RCA makes sense. The suggested fix works but we actually used to pass `props.chatReportID`. It was changed on purpose by https://github.com/Expensify/App/pull/18604/commits/6a353641c71b55a0898ec700241b1be5ca6a52bd. I have asked for a clarification here https://github.com/Expensify/App/pull/18604#discussion_r1206096887.

Maybe we can define `parentReportID` as `chatReportID` if SPLIT, otherwise `requestReportID`.

**Comment by mountiny** [comment] 2023-05-26 00:05
hmm I think we have to look more into this. The iou action should be the parent report action and hence the money report where the iou action resides is the parent report.

If you do a Split with just one person, I am not sure how exactly that should be handled, shouldnt we just make one request of the half price? @Julesssss @luacmartins ?

**Comment by tienifr** [comment] 2023-05-26 05:30
@s77rt @mountiny I have one suggestion: IOUs of type split only exist in group DMs when the participants.length > 1, so I want to add this condition to decide we should delete IOUReportID or not

https://github.com/Expensify/App/blob/0925c25015fad74a55b0bcc87855b0283ae53c2b/src/libs/ReportUtils.js#L1450-L1454

and add IOUReportID as eighth arg (groupChatReport.reportID) in 

https://github.com/Expensify/App/blob/0925c25015fad74a55b0bcc87855b0283ae53c2b/src/libs/actions/IOU.js#L414

Result:

https://github.com/Expensify/App/assets/113963320/03e45ce0-9afd-4569-a753-b524d9f07e0e

Please tell me what're your thoughts. Thanks.

**Comment by s77rt** [comment] 2023-05-26 11:11
I'm not sure how to proceed here but based on @luacmartins statement looks like we may do nothing. Clicking the split preview box is planned to open a details modal (RHN) and not a new report. Ongoing PR: https://github.com/Expensify/App/pull/19390.

**Comment by luacmartins** [comment] 2023-05-26 15:39
Yea this behavior shouldn't exist. We don't create a thread when we press the split preview component. I think we can close this issue.

**Comment by mountiny** [comment] 2023-05-26 16:11
I agree, lets close this up, sorry for the confusion this is still in development

**Closed by mountiny** 2023-05-26 16:11 UTC
Labels: External, Daily, Help Wanted, Bug
