### ISSUE TITLE
Web- Workspace - When tapping "back", user is taken to VBA flow again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10585] opened 2022-08-26 02:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Create a workspace
4. Tap on the Profile icon > Workspace name > Reimburse expenses > connect to bank
5. Tap "back" on the "Continue with setup" page

## Expected Result:
User expects to be returned to the previous Reimburse expenses page. (Works for any of the options in the workspace, reimburse expenses is just an example)

## Actual Result:
The user is redirected to a second VBA flow showing the "Connect online with plaid/manual" options

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.91.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/186801947-922f81c0-b84b-4c2e-8382-eac036bc43f6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2022-08-26 07:17
I confirmed that this happens in staging but not in prod.

**Comment by jasperhuangg** [comment] 2022-08-26 07:28
No idea why this is happening, reached out in #engineering-chat for some help

**Comment by luacmartins** [comment] 2022-08-26 07:32
Git bisect tells me [this is the offending commit](https://github.com/Expensify/App/commit/1e27aca6b835a40907574cd5f7dd95ce03208601) but I have no idea why

**Comment by luacmartins** [comment] 2022-08-26 07:35
Hmm maybe I did something wrong along the way haha reverting those changes doesn't seem to fix the issue

**Comment by jasperhuangg** [comment] 2022-08-26 07:40
https://github.com/Expensify/App/pull/10454 isn't included in this deploy checklist but is only on staging at the moment, feel like that's probably what's causing the problem because it's the only thing that's modified the WorkspaceBankAccountPage recently cc @luacmartins

**Comment by jasperhuangg** [comment] 2022-08-26 07:47
> Git bisect tells me [this is the offending commit](https://github.com/Expensify/App/commit/1e27aca6b835a40907574cd5f7dd95ce03208601) but I have no idea why

@luacmartins yeah I have no idea how changing KeyboardAvoidingView behavior would change that.. I don't think that's the reason either.

**Comment by luacmartins** [comment] 2022-08-26 07:48
https://github.com/Expensify/App/pull/10454 is actually on [prod](https://github.com/Expensify/App/blob/production/src/pages/workspace/WorkspaceBankAccountPage.js) (we must have missed the deploy comment)

**Comment by jasperhuangg** [comment] 2022-08-26 08:11
It appears this issue is being caused by https://github.com/Expensify/App/pull/10026, can we revert?

**Comment by mallenexpensify** [comment] 2022-10-18 16:22
Reopening to pay @aneequeahmad for reporting (instead of opening a new GH)
https://expensify.slack.com/archives/C01GTK53T8Q/p1661446815440409

<img width="480" alt="image" src="https://user-images.githubusercontent.com/22508304/196486903-564fd614-76d1-409b-a674-e2086b7b6bb5.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/22508304/196486915-56bb2468-bdb7-4ac1-9c2f-c246f1ba2339.png">

@aneequeahmad please accept the Upwork offer then I'll pay 
https://www.upwork.com/jobs/~01ee11f9634848c1fd

**Comment by sketchydroide** [comment] 2022-10-19 13:15
I don't know why this is still set as deploy blocker, this is to old to be one, removing

**Comment by aneequeahmad** [comment] 2022-10-19 15:46
> @mallenexpensify I accepted the offer. Thank you for mentioning.

oops,  i  applied to the job offer here, apologies.

@mallenexpensify  Just accepted the offer on Upwork, Thanks for opening the issue and sending me the job offer.

**Comment by mallenexpensify** [comment] 2022-10-20 20:03
Paid, closing! Thanks @aneequeahmad

**Closed by mallenexpensify** 2022-10-20 20:03 UTC
Labels: Reviewing, Engineering, Daily, Bug
