### ISSUE TITLE
 IOU - Comment on a deleted IOU isn't opening from the combined report view

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39512] opened 2024-04-03 14:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59.3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39433
## Action Performed:
1. Create a manual IOU with an account you never had contact before
2. Create a second manual IOU
3. Open the first IOU
4. Add some comments
5. Delete the first IOU
6. Navigate to the combined report view
7. Click on "Replies"

## Expected Result:
I should be able to view comments

## Actual Result:
Comment on a deleted IOU isn't opening from the combined report view after deleting the first IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/37e8ea6b-9053-4bc8-bdbe-236fd609a3d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-04-03 15:00
@tgolen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by tgolen** [comment] 2024-04-03 15:44
Yeah, I do think this is a bug. Before going `external` with it, there are a couple of suspect PRs on the deploy list which might have caused this.

@NikkiWines @bernhardoj Could this be a regression from #39419? 
@srikarparsi @pac-guerreiro Could this be a regression from #35253?

**Comment by bernhardoj** [comment] 2024-04-03 15:48
https://github.com/Expensify/App/pull/39419 only touches the receipt attachment modal page, so it shouldn't cause this issue.

**Comment by srikarparsi** [comment] 2024-04-03 17:16
Ah, looks like a PR for [single transaction](https://github.com/Expensify/App/pull/36934) pages does exist. @NikkiWines do you think this could be a regression from that?

**Comment by tgolen** [comment] 2024-04-03 17:19
Thanks @srikarparsi if we can't find this one quickly, I'll make sure I can reproduce it and then use `git bisect` to find out exactly what broke it. I'll be able to do that in about 2 hours as I'm in a meeting currently.

**Comment by NikkiWines** [comment] 2024-04-03 18:07
Sorry for the delay! It does look like it's likely tied to the one-transaction changes - though I'm not sure what the expected behavior is for comments on a request that no longer exists. 

I'll double-check how we handle it on prod

**Comment by pac-guerreiro** [comment] 2024-04-03 18:10
@NikkiWines I reverted your PR locally and the issue got resolved 😅

This is the previous behaviour without your changes: 

https://github.com/Expensify/App/assets/48553277/cdbd3d77-954a-42ed-9837-f9415f732a0a

**Comment by NikkiWines** [comment] 2024-04-03 18:24
Oh interesting, because we keep it on the report 🤔 Thanks for checking that out @pac-guerreiro 

I wonder if then we should just not consider it a one-transaction report if there's a previously deleted request... I'm not sure how we'd show the deleted request in a reasonable way otherwise

**Comment by tgolen** [comment] 2024-04-03 18:55
I'm going to assign this to you for now @NikkiWines. 

As for the behavior, I think the situation where there is a deleted request would indicate it couldn't be a one-transaction report.

**Comment by NikkiWines** [comment] 2024-04-03 19:06
Cool, I think that makes sense. I'm makng a follow up PR to handle some of these edge-cases and bugs we've found for this new view, so I'm gonna mark this as a non-blocker and handle it in that follow up PR.

**Closed** 2024-06-26 18:09 UTC
Labels: Reviewing, Engineering, Monthly, Improvement

**Comment by NikkiWines** [comment] 2024-06-26 20:02
Oops, this was actually handled as part of https://github.com/Expensify/App/pull/39472 but the issue was never closed 😅  regardless, this one has been successfully resolved 😄
