### ISSUE TITLE
[HOLD for payment 2023-09-12] [$1000] Web - Payments - Unexpected behaviour occur when clicking two times simultaneously on Payment option

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25594] opened 2023-08-21 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to settings > Payments
3. Add Paypal as payment method
4. Click on Paypal Username two times simultaneously

## Expected Result:
The model should close after the second click or nothing should happen

## Actual Result:
One option disappear/'Edit' option changes to 'Make payment method default' after the second click

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.55-7

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/ba8aeb4c-2dcc-4cfd-b85b-88a6f8780eff

https://github.com/Expensify/App/assets/115492554/0e588446-7602-4153-967d-3914e8dedc41

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691676935055309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b423d2ec84f5ac83</li>
        <li>Upwork Job ID: 1694077444400852992</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 26427416</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-08-21 14:41
# Proposal

## Please re-state the problem we are trying to solve
Clicking on the paypal payment option more than once causes the 'Edit' option to go away.

## What is the root cause of the problem?
In `BasePaymentsPage.js` the edit option is only shown if the selected option is of type `CONST.PAYMENT_METHODS.PAYPAL` and when we click on it, the selected option is set to that. But when we click on it once again, `onClose()` callback for the popover containing the action buttons is also called.
https://github.com/Expensify/App/blob/5a1b35c297a6b9c6f2ee502a674b7f460bd90734/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L417

And this `onClose()` then calls `resetSelectedPaymentMethodsData`, which clears out the selected account option (currently paypal) and sets it to null.
https://github.com/Expensify/App/blob/5a1b35c297a6b9c6f2ee502a674b7f460bd90734/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L210-L218

## What changes do you think should me made to fix this?
There is no need of clearing the selected option on closing the popover. So, we can just change the following line in `Popover`:
https://github.com/Expensify/App/blob/8a856e7adc5ff3a3c2e463371d6b4a8b42644e86/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L417
to
```js
onClose={() => hideDefaultDeleteMenu(false)
```
This will make sure that the menu is hidden but the selection is not reset because `shouldClearSelectedData` will be set to `false`

Now, there might be doubts as to the need of the selection reset code then... Well, the function to reset the selection `resetSelectedPaymentMethodData` was introduced in this PR: https://github.com/Expensify/App/pull/14869
This PR was fixing the case of closing the modal if the payment option is deleted from another device. And where this code is essentially needed is in the `useEffect` that handles the change in the payment methods here:
https://github.com/Expensify/App/blob/8a856e7adc5ff3a3c2e463371d6b4a8b42644e86/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L360-L365
Therefore, it still is fulfilling it's purpose and is being removed from where it is not needed. So, I think we can safely set `shouldClearSelectedData` to `false` when calling `hideDefaultDeleteMenu()` to prevent the running of the function `resetSelectedPaymentMethodData()`

## What alternative options did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-08-22 20:01
[Confirmed bug](https://expensify.slack.com/archives/C049HHMV9SM/p1692734391793479?thread_ts=1691676935.055309&cid=C049HHMV9SM), Paypal shouldn't have a 'Make default' option.

**Comment by garrettmknight** [comment] 2023-08-25 14:14
@mananjadhav can you take a look at these proposals when you get a chance?

**Comment by garrettmknight** [comment] 2023-08-28 16:50
@mananjadhav please review this or let me know if I need to reassign.

**Comment by mananjadhav** [comment] 2023-08-29 04:59
I'll have these reviewed today. I missed notification on this one.

**Comment by mananjadhav** [comment] 2023-08-30 05:28
I've reproduced the error and glanced through the proposals as well. I just need to test and choose the one of them. I'll have them tested and post an update here. Would be choosing from the existing ones only. So no new proposals needed.

**Comment by mananjadhav** [comment] 2023-08-30 19:31
While all the proposals work, I think @bernhardoj's [proposal](https://github.com/Expensify/App/issues/25594#issuecomment-1687976343) is good as it corrects the anchor ref too, and actually solves the root cause. Plus I also liked the possibility of getting rid of InteractionManager.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-09-07 19:06
I couldn't pinpoint the offending PR as I am not sure if we considered this case anytime during our development. The overall approach also is about removing the reference altogether along with InteractionManager.

I think we could add a regression test here, as it is easy to miss out this case building Popovers.

**Comment by mananjadhav** [comment] 2023-09-12 17:36
@garrettmknight Can you please update the payment summary here?

**Comment by garrettmknight** [comment] 2023-09-13 11:47
**Summary of payments:**

urgency bonus? Yes
Reporter: @aman-atg $250 offer sent in Upwork
Contributor: @bernhardoj $1500 paid via Upwork
Contributor+: @mananjadhav 

Upwork job: https://www.upwork.com/ab/applicants/1694077444400852992

**Comment by garrettmknight** [comment] 2023-09-14 04:42
Udpated, everyones been paid via upworks and @mananjadhav is ready to be paid.

**Comment by garrettmknight** [comment] 2023-09-19 03:45
Can you complete this part of the checklist @mananjadhav ?
>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by Julesssss** [comment] 2023-09-19 04:13
@garrettmknight I'd agree that this case shouldn't be treated as a regression

> I couldn't pinpoint the offending PR as I am not sure if we considered this case anytime during our development.

**Comment by garrettmknight** [comment] 2023-09-19 06:25
>I think we could add a regression test here, as it is easy to miss out this case building Popovers.
Sure, but that doesn't affect whether we introduce a regression test for it, right?

**Comment by Julesssss** [comment] 2023-09-19 07:18
True, this one is a bit tricky though as the fix applies to only a single usage of the component. It'd be a waste of time to create a regression test for every single popover menu where this could occur. 

Ideally, some sort of lint check would prevent these cases app-wide. But that's not necessarily easy and I'd still lean towards not creating a regression test here.

**Comment by JmillsExpensify** [comment] 2023-09-21 09:17
$1,500 payment approved for @mananjadhav based on BZ summary.

**Comment by garrettmknight** [comment] 2023-09-21 11:10
No regression test, closing.

**Closed by garrettmknight** 2023-09-21 11:10 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
