### ISSUE TITLE
IOU- Paid status and green checkmark for IOU disappear after signout and signin again

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37411] opened 2024-02-28 11:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause Internal Team

## Action Performed:
Prerequisite: An IOU is made by User A. Execute the following steps by User B
1. On the IOU report Click the Pay button "I’ll settle up elsewhere"
2. Verify that the IOU message shows "paid [amount] elsewhere" with a checkmark
3. Click on the header link to navigate to the parent conversation
4. Verify that the 1:1 conversation opens
5. Verify the IOU report preview shows the status of paid
6. Logout
7. Login
8. Verify the IOU report preview shows the status of paid

## Expected Result:
Paid status and green checkmark for IOU should never disappear

## Actual Result:
If signed out and then signed in, paid status and green checkmark for IOU disappear

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fed682c8-d877-42fd-8a77-db6c3a526dc4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-28 11:39
@sonialiap I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-02-28 11:40
We think that this bug might be related to #wave7-collect-approvers
CC @RachCHopkins

**Comment by sonialiap** [comment] 2024-03-05 13:25
Asking about adding to wave7 https://expensify.slack.com/archives/C02NZ2HGJAZ/p1709644985629129

**Comment by sonialiap** [comment] 2024-03-15 11:08
Closing because I am unable to reproduce. Please reopen if it's still an issue

**Closed by sonialiap** 2024-03-15 11:08 UTC
Labels: Daily, Overdue, Bug
