### ISSUE TITLE
Can open assign page after task canceled

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#24478] opened 2023-08-12 02:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Create a task
3. Click assignee and copy url
4. Send url on the task chat
5. Cancel task
6. Click the link just sent
## Expected Result:
not found page appears
## Actual Result:
Can open the assignee page
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/2aed8133-b304-41ff-a1b7-aa3fe625b808

https://github.com/Expensify/App/assets/38435837/d8ebb8a0-5108-4ca6-9eb4-b3e7ac4c15f2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691118080971949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by BhuvaneshPatil** [comment] 2023-08-12 03:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can open assign page after task is canceled

### What is the root cause of that problem?
The rot cause for this problem is we are not checking if task can be modified in `TaskAssigneeSelectorModal`.


### What changes do you think we should make in order to solve the problem?
We can wrap the component in `FullPageNotFoundView`.
The condition for that will be - 
```js
    const isOpen =  ReportUtils.isOpenTaskReport(report);
    const isCanceled = ReportUtils.isCanceledTaskReport(report);
    const canModifyTask = Task.canModifyTask(props.task.report, props.session.accountID);
```
We can provide `subtitleKey` for each state (can be modified), ex - 
- task is canceled -> we can show `Task is canceled, this action can't be done`
- task is completed -> `Assignee can't be changed for completed task, please reopen and try again`
- user doesn't have permission to edit task -> `You don'r have enough permission to edit the task`


Similar changes can be done for `TaskDescriptionPage`, `TaskTitlePage`.

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-08-12 04:30
Looks similar to this - https://github.com/Expensify/App/issues/22451

**Comment by conorpendergrast** [comment] 2023-08-15 09:05
Agreed, this is a dupe of https://github.com/Expensify/App/issues/22451#issuecomment-1626369393 (in that comment on July 8th, see that editing the attendee is mentioned already).

I'm closing this as a duplicate of the same bug

**Closed by conorpendergrast** 2023-08-15 09:05 UTC
Labels: Daily, Overdue, Bug
