### ISSUE TITLE
Message order is changing, and sometimes messages disappear momentarily

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14677] opened 2023-01-31 01:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Send a series of messages to a user in a DM (like 3 or 4)
2. Refresh New Expensify, or navigate away/back to New Expensify
3. See the order of messages you sent change

## Expected Result:
Messages order in a DM should be preserved at all times.

## Actual Result:
The order of delivered messages in a DM are changing around

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![M6Xk4sR1GB](https://user-images.githubusercontent.com/43996225/215601115-5840f8c9-3397-44c3-92ea-12e95c0b906d.gif)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @michaelhaxhiu 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674839140008569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-01-31 09:35
cc @dangrous since its related to the issue you got assigned

**Comment by miljakljajic** [comment] 2023-02-07 17:56
which do you mean, @mountiny / @dangrous? I'm not seeing anything similar assigned to Dan!

**Comment by mountiny** [comment] 2023-02-07 18:16
I think it was this one https://github.com/Expensify/App/issues/14625

**Comment by dangrous** [comment] 2023-02-07 18:51
Primarily being discussed in Slack - https://expensify.slack.com/archives/C049HHMV9SM/p1674669337825539

**Comment by miljakljajic** [comment] 2023-02-10 12:51
I haven't been able to reproduce this when I've tried - everything is being sent in order.

**Comment by mountiny** [comment] 2023-02-10 12:57
I think this is still happening you just need to send message quickly after each other

**Comment by miljakljajic** [comment] 2023-02-10 13:09
Ah yes you're right: 

![image](https://user-images.githubusercontent.com/28715117/218100010-9411f790-9e4e-47e3-9ad2-f3f75c56b2c9.png)

**Comment by miljakljajic** [comment] 2023-02-10 13:11
@mountiny / @dangrous do you think this is fine for an external contributor to work on?

**Comment by miljakljajic** [comment] 2023-02-10 13:22
Seems like it needs to be internal? https://github.com/Expensify/App/issues/14576#issuecomment-1405815446

**Comment by mountiny** [comment] 2023-02-10 13:49
I think we had been discussing this issue before quite extensively and always came to conclusion to do nothing for now if the messages get to correct order and it does not happening with normal speed of messaging. 

If we are strictly talking about the order of the messages after being sent super fast then I think we could close this issue for now!

**Comment by miljakljajic** [comment] 2023-02-10 15:45
Makes sense Vit - I will close for now, as this is the behaviour I'm experiencing:

> the messages get to correct order and it does not happening with normal speed of messaging.

**Closed by miljakljajic** 2023-02-10 15:45 UTC
Labels: Daily, Bug
