### ISSUE TITLE
Workspace settings – Name and value are not greyed out when create a new tax rate Offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41067] opened 2024-04-26 08:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4516486
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a new Workspace
4. Navigate to the workspace editor
5. Navigate to "More Features"
6. Enable the tax toggle
7. Navigate to Taxes in the workspace editor
8. Go offline
9. Click on the "Add rate" button
10. Enter a name and a rate
11. Save the new rate
12. Open just created tax rate

## Expected Result:
Name and value are greyed out when create a new tax rate Offline

## Actual Result:
Name and value are not greyed out when create a new tax rate Offline, but greyed out when edit it.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1c2fded1-8376-4b0e-ad5b-a8e951a84da6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-26 08:17
We think this issue might be related to the #collect project.

**Comment by trjExpensify** [comment] 2024-04-27 12:04
I can't reproduce this on iOS (native, mWeb) nor Web (Chrome) or Desktop. In all instances the tax rate is added is at 50% opacity while offline and reverts to 100% when coming back online. That's the expected result, so I think we should close this.

**Closed by trjExpensify** 2024-04-27 12:04 UTC
Labels: Daily, Bug
