### ISSUE TITLE
IOS -  Assign task - Text is flickering in case of editing saved description field

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20836] opened 2023-06-15 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19377

## Action Performed:
1. Assign a new task, fill title, multiline description and tap on the Next button
2. Try to edit multiline description field

## Expected Result:
The user should be able to edit description fields without any issues

## Actual Result:
Text is flickering in case of editing multi line description field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28.3

**Reproducible in staging?:** yes

**Reproducible in production?:** new feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5218b2cd-5407-47cc-845b-ce03070e62cf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2023-06-15 18:20
@dan1d Please bring any setup related questions to #expensify-open-source in slack!

**Comment by thienlnam** [comment] 2023-06-15 18:23
Not a blocker, only happens when you go beyond the multiple lines. This appears to be a regression of this though

https://github.com/Expensify/App/issues/19135

**Comment by akinwale** [comment] 2023-06-15 18:55
Looks like this is a side effect of using the state to set the TextInput selection prop. It's happening in the `NewTaskDescriptionPage` and `TaskDescriptionPage` components. This didn't seem to happen during my tests so I may have missed it somehow.

After taking a look, I can use the `onEntryTransitionEnd` event handler to set the selection range after `inputRef.current.focus()`, like so:
```
if (inputRef.value && inputRef.setSelectionRange) {
    const length = inputRef.value.length;
    inputRef.setSelectionRange(length, length);
}
```

This is the way it's being done in `WorkspaceInviteMessagePage`. It places the text cursor at the end, however, the text input does not automatically scroll until typing starts.

@sobitneupane What do you think of this approach?

**Comment by sobitneupane** [comment] 2023-06-16 04:33
> This is the way it's being done for the welcomeMessage text input in WorkspaceInviteMessagePage. It places the text cursor at the end, however, the text input does not automatically scroll to the position until typing starts.

@akinwale We want the text to be scrolled as well.

**Comment by akinwale** [comment] 2023-06-17 05:03
@sobitneupane 

I've spent quite a number of hours on this, and it appears that the TextInput just won't scroll to the end without user interaction. Every attempt that I've made to programmatically achieve this does not change the scroll position.

I have tried the following:
- Tried the `setSelectionRange` as indicated above, but apparently, this will only work on web, not native. The cursor is already always at the end for native platforms.
- Used `setNativeProps` to set the selection, however, this does not make the scroll position change.
- Tried to set the `selection` prop to undefined after initially setting it. This will still reset the cursor position back to the start of the TextInput.
- Looked for a way to scroll the `TextInput` directly. Unfortunately, it looks like this is not possible as there are no functions exposed to do this.
- Tried to programmatically dispatch a keydown event for the Down cursor key. This can be achieved on web platforms using KeyboardEvent, but I'm not seeing a way to do this on native.

I'd like to attempt wrapping the TextInput with a ScrollView as I've seen in some suggestions, which would allow being able to programmatically scroll the ScrollView using the `scrollToEnd` method, but we may lose the bottom border styling on the text input. Please let me know what you think of this approach.

If you also have any other ideas that may help here, please let me know so that I can try. Thanks.

**Comment by akinwale** [comment] 2023-06-21 09:19
@sobitneupane I haven't found any. I experimented with wrapping the TextInput with a ScrollView but this breaks the input styling and also requires a fixed height to be set, so it doesn't autogrow.

Right now, the viable options I can see in order to move forward are:
1. Remove the selection prop and use the ref solution proposed above so that it doesn't cause issues on iOS. This however means that the user would have to manually scroll to the bottom (only on iOS native) when trying to edit.
2. Leave the selection prop as is and hope it gets fixed on the React Native side.

Please let me know what you think. Thanks.

**Comment by sobitneupane** [comment] 2023-06-21 09:22
> Leave the selection prop as is and hope it gets fixed on the React Native side.

Is there any open issue for this on React Native?

**Comment by akinwale** [comment] 2023-06-21 09:23
> > Leave the selection prop as is and hope it gets fixed on the React Native side.
> 
> Is there any open issue for this on React Native?

Yes, since 2020. https://github.com/facebook/react-native/issues/30298

**Comment by sobitneupane** [comment] 2023-06-21 09:24
Oh no. We cannot wait for the issue that is open from 2020.😄

**Comment by sobitneupane** [comment] 2023-06-21 09:26
> Remove the selection prop and use the ref solution proposed above so that it doesn't cause issues on iOS. This however means that the user would have to manually scroll to the bottom (only on iOS native) when trying to edit.

So, the best solution we have as of now is https://github.com/Expensify/App/issues/20836#issuecomment-1593572133

What's your opinion on this @thienlnam?

**Comment by thienlnam** [comment] 2023-06-21 17:57
Thank you both for your investigation into this - let's continue with this proposal to fix the regression for now https://github.com/Expensify/App/issues/20836#issuecomment-1593572133

But since there is an issue in RN for this, let's also try to get some proposals to resolve that root cause over there as well

**Comment by akinwale** [comment] 2023-06-23 05:41
@sobitneupane The PR is ready for review. As can be observed from my test videos, the description input automatically scrolls to the bottom when editing for every platform except iOS native.

**Comment by thienlnam** [comment] 2023-07-11 19:27
No payment due here since we fixed a regression

**Comment by thienlnam** [comment] 2023-07-11 19:29
Going to close this for now, I'd like to revisit https://github.com/facebook/react-native/issues/30298 in the future to see if we can find someone to make a proposal for that

**Closed** 2023-07-11 19:28 UTC
Labels: Engineering, Weekly
