### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Distance - Map, amount and distance in the background shows TBD when editing distance

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32120] opened 2023-11-28 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to a workspace chat with distance request.
3. Open distance request details page.
4. Click Distance.
5. Click Add stop.
6. Add a new address.

## Expected Result:
The map, amount and distance in the background will not show TBD because user is editing the distance without saving.

## Actual Result:
The map, amount and distance in the background shows TBD without saving.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/935e2d12-f90a-49eb-b8d7-44a45d038084

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c7d894fb538d33ef</li>
        <li>Upwork Job ID: 1729498349642403840</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 28055126</li>
<li>DylanDylann | Contributor | 28055129</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-11-28 14:12
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Distance - Map, amount and distance in the background shows TBD when editing distance

### What is the root cause of that problem?

This is because we are editing directly on `transaction` Onyx. And we are using backup in `transactionDraft_` collection for saving the last transaction.

### What changes do you think we should make in order to solve the problem?

We can do the opposite. Use Transaction Draft for editing and then transfer the updated data on transaction collection later.

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2023-11-28 14:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When editing a Distance request, the distance and amount fields are set to "TBD" before the actual update happens.

### What is the root cause of that problem?
We are not handling the loading state of the distance transaction properly.

We set the `transaction.isLoading` when modifying the distance request here:

https://github.com/Expensify/App/blob/cd9cd57e23af82b4af73915c4d7d53e659376576/src/libs/actions/IOU.js#L757-L766

And we handle this state in other places, like here:

https://github.com/Expensify/App/blob/19c8e2548d44128e02b1792c32baf009340d549f/src/components/DistanceRequest/index.js#L84

But we do not handle this state on the `MoneyRequestView` page. Instead, we use the `const hasPendingWaypoints = lodashGet(transaction, 'pendingFields.waypoints', null);`

### What changes do you think we should make in order to solve the problem?

On `MoneyRequestView`, replace the hasPendingWaypoints with:

```js
const isLoading = lodashGet(transaction, 'isLoading', false);
```


### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2023-12-01 20:19
@ntdiary a few proposals to review above!

**Comment by paultsimura** [comment] 2023-12-05 11:03
> we may need to refactor the changes in PR #30232 using this condition

I was initially oriented on the changes of this PR when posting my proposal. Just didn't want to clutter the proposal with all the changes, but yes, we'll need to make changes in all the places where PR #30232 used pending waypoints.

**Comment by DylanDylann** [comment] 2023-12-05 11:08
@ntdiary What about my alternative solution?

**Comment by DylanDylann** [comment] 2023-12-11 11:45
@ntdiary I think it makes sense because `isDraft = isEditingWaypoint`, we will update the pending field to `UPDATE` if `isEditingWaypoint` is true. If `isDraft == isEditingWaypoint == false` It means that we are creating new waypoint so we update the pending field to `ADD`

But my curious here that why we need to update the pending field here even though we don't call API

**Comment by tgolen** [comment] 2023-12-11 15:33
@ntdiary is right in [their comment](https://github.com/Expensify/App/pull/28618#discussion_r1422281216) that I got the `isDraft` logic backwards for the Onyx key. This is probably a deploy blocker. I'm not sure though how it relates to this issue. Would fixing the onyx key logic fix this entire issue?

**Comment by DylanDylann** [comment] 2023-12-11 15:56
@tgolen Could you help to explain why why we need to set `pendingField.waypoint` when selecting a waypoint 
https://github.com/Expensify/App/blob/935608bf47aeea6386c34da9c9b5ae3900951ed4/src/libs/actions/Transaction.ts#L61
Even though we don't call API in here. Normally, pendingField and pending action only be added in optimisticaData (apply before sending API) and It is re-set in successData and failureData
So I think we should not set `pendingField.waypoint` when the user updates a new waypoint, we only set the pending field if the user clicks save button

**Comment by tgolen** [comment] 2023-12-11 16:23
I wish I had a good answer for you, but I honestly am not sure and it's totally possible that those could be removed. I agree with you that we probably don't want to show those as pending until the API request is made. Let's clean this up if we can. I'm guessing the offline flow was the focus of that change so as long as the offline flow still matches all of our patterns in the end, I think it's fine to remove them.

**Comment by DylanDylann** [comment] 2023-12-13 07:24
@ntdiary based on [this comment](https://github.com/Expensify/App/issues/32120#issuecomment-1850418510), Could you  re-check my alternative solution [here](https://github.com/Expensify/App/issues/32120#issuecomment-1829915666)?

**Comment by DylanDylann** [comment] 2023-12-14 08:14
@ntdiary https://github.com/Expensify/App/pull/33043
the PR is ready for review. Please help to re-assign to you

**Comment by DylanDylann** [comment] 2024-01-02 06:08
@adelekennedy Could you help to move forward with this issue?
cc @ntdiary

**Comment by adelekennedy** [comment] 2024-01-05 20:42
Back from ooo and picking this up - I agree we can skip the regression test here!

### Payouts due:

Contributor: $500 @ntdiary 
Contributor+: $500 @DylanDylann 

Upwork job is [here](https://www.upwork.com/freelance-jobs/apply/500-Distance-Map-amount-and-distance-the-background-shows-TBD-when-editing-distance-32120-Expensify_~01c7d894fb538d33ef/).

**Closed** 2024-01-05 20:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
