### ISSUE TITLE
[HOLD for payment 2024-04-25] [MEDIUM] New Feature : Click to autofocus does not work in the Scan receipt camera

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34898] opened 2024-01-22 15:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705687521786479

## Action Performed:
1. Scan a receipt using camera
2. Keep closer to the receipt
3. Try to tap in to focus the image

## Expected Result:
We should be able to tap in to focus the image

## Actual Result:
Click to autofocus does not work and cannot tap in to focus the image

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f43696563238cad</li>
        <li>Upwork Job ID: 1749863408754200576</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by mountiny** [comment] 2024-01-22 16:13
Asking Margelo if they can work on this

**Comment by mrousavy** [comment] 2024-01-23 12:51
Yup, we'll do it right after Flash for V3 is done!

**Comment by janicduplessis** [comment] 2024-01-23 17:54
I can take this one!

**Comment by mountiny** [comment] 2024-01-23 18:35
@janicduplessis Can you also address the rotation issue?

Our native apps have landscape mode disabled so the UI does not rotate but the camera does which leads to weird UX 😄

**Comment by janicduplessis** [comment] 2024-01-23 21:03
@mountiny Yes I can have a look at that also

**Comment by mountiny** [comment] 2024-01-23 23:20
It can be a same pr i think

**Comment by mountiny** [comment] 2024-01-24 19:34
Progress is looking good

**Comment by mountiny** [comment] 2024-02-06 16:11
This seems like it did not work in the staging/ prod ios build https://github.com/Expensify/App/pull/35014#issuecomment-1930175534 @ishpaul777 @janicduplessis

**Comment by janicduplessis** [comment] 2024-02-06 16:17
Replied in the PR.

**Comment by Christinadobrzyn** [comment] 2024-03-05 02:30
Wow, did I miss this? I'm so sorry for the delay @ishpaul777 

How's this look for payment:

Contributor+: $500 @ishpaul777 (through Upwork)

Upwork job is [here](https://www.upwork.com/nx/wm/offer/101214359).

**Comment by Christinadobrzyn** [comment] 2024-03-07 06:22
Paid this out @ishpaul777 based on this payment summary https://github.com/Expensify/App/issues/34898#issuecomment-1977836178

@janicduplessis should you also be paid for this? Not sure about the role that each of you had since this is an internal job. cc @mountiny

**Comment by janicduplessis** [comment] 2024-03-11 18:45
I don't think I am eligible as I am a contractor with Margelo.

**Comment by mountiny** [comment] 2024-03-11 22:40
@ishpaul777 Can you please propose a TestRail test case as well for @Christinadobrzyn to add? I think we should make sure QA is checking for this behaviour

**Comment by mountiny** [comment] 2024-03-12 22:34
Thanks! @Christinadobrzyn all yours!

**Comment by Christinadobrzyn** [comment] 2024-03-12 23:28
Regression test here - https://github.com/Expensify/Expensify/issues/378241

Closing!

**Comment by mountiny** [comment] 2024-03-28 00:01
I will reopen this to handle a follow up, its not fully working yet

**Comment by mrousavy** [comment] 2024-03-29 11:36
wdym it's not fully working yet @mountiny ?

**Comment by mountiny** [comment] 2024-03-29 22:05
@mrousavy yeah on ios, you are still not able to focus from various distances I believe and there is this PR to help with it https://github.com/Expensify/App/pull/35926

**Comment by mrousavy** [comment] 2024-04-02 10:44
Ah yeah true, we might want to use the dual wide camera again so it can automatically switch to the "macro lens". I can also fix that in a follow-up PR once the V4 revert is reverted :)

**Comment by janicduplessis** [comment] 2024-04-02 15:51
Yea, maybe you want to make that change @mrousavy, since in v4 the api to pick device is a lot nicer, right now I have to do the fallback to different cameras manually. I think our conclusion from that PR is the best is dual -> ultra-wide -> wide as priority of device to use.

**Comment by mrousavy** [comment] 2024-04-02 17:15
will do in a follow-up PR in a few mins!

**Comment by mountiny** [comment] 2024-04-02 19:49
nice, thank you

**Comment by mountiny** [comment] 2024-04-04 11:43
Thanks, let me know if you need any help

**Comment by mountiny** [comment] 2024-04-20 19:13
$250 to @ishpaul777

**Comment by Christinadobrzyn** [comment] 2024-04-23 08:11
Payouts due:

- [ ] Contributor+: $250 @ishpaul777 (upwork offer - https://www.upwork.com/nx/wm/offer/101986939)

Upwork job is [here](https://www.upwork.com/jobs/~01eac3bd3b7aa88b6d).

**Comment by Christinadobrzyn** [comment] 2024-04-26 05:59
Alright paid out based on this [payment summary](https://github.com/Expensify/App/issues/34898#issuecomment-2077858536)

No regression test due here so closing.

**Closed by Christinadobrzyn** 2024-04-26 05:59 UTC
Labels: Daily, Internal, NewFeature, Awaiting Payment
