### ISSUE TITLE
[$500] DEV - The app crashes when attempting to send money after changing the currency

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#30086] opened 2023-10-20 14:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** dev
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** 
https://expensify.slack.com/archives/C049HHMV9SM/p1697739450327549

## Action Performed:
1. Open a chat
2. Go to the send money
3. Click on the currency and change it
4. Enter the amount and attempt to send it
## Expected Result: 
The app should not crash during the process of sending money
## Actual Result: 
The app crashes when attempting to send money after changing the currency

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/38435837/461788a9-4a10-4aca-85bb-6b7fab6788df

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/cb96e47f-b6ca-4d8c-a8e7-e2ac95c0c1d9

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/App/assets/38435837/3a10c442-2772-45ed-aac9-2464e209d65b

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/4218c906-1158-4ca4-802c-d9340fb611f2

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/39f251a6-dfb4-494d-bf1a-9f2b58a88bcf

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/App/assets/38435837/d058ffa0-7910-4a90-85d7-a99ed4ebdcee

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014506069eb0680897</li>
        <li>Upwork Job ID: 1715379061964460032</li>
        <li>Last Price Increase: 2023-10-20</li>
    </ul>
</details>

**Comment by ayazhussain79** [comment] 2023-10-20 16:23
@ishpaul777 try these steps on dev:
1. Open a chat
2. Go to the send money
3. Click on the currency and change it to USA
4. Enter the amount and attempt to send it by "Pay elsewhere"

**Comment by raoinvoker** [comment] 2023-10-23 02:59
@ayazhussain79 I am able to reproduce the issue, in all platforms, its a render error.

![image](https://github.com/Expensify/App/assets/78265752/1ecc9b90-ee54-4e54-80cf-c8695434204d)

we are reading the value from undefined identity.

**Comment by raoinvoker** [comment] 2023-10-23 03:23
Contributor details
Your Expensify account email: lalitkumaryadav9090@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f5f854cbbb68f9fb

@ayazhussain79 I am able to reproduce the issue, in all platforms, its a render error.

![image](https://github.com/Expensify/App/assets/78265752/1ecc9b90-ee54-4e54-80cf-c8695434204d)

we are reading the value from undefined identity.

**Comment by kadiealexander** [comment] 2023-10-24 05:59
@allroundexperts you're C+ for both issues, do you think this is a dupe of https://github.com/Expensify/App/issues/29336?

**Closed** 2023-10-25 05:47 UTC
Labels: External, Daily, Help Wanted, Bug
