### ISSUE TITLE
[$250] "Get it" button not displayed in Allow location access modal when scan expense

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#51124] opened 2024-10-19 15:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50543
**Email or phone of affected tester (no customers):** applausetester+ck1018@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Submit Expense > Scan > Upload a receipt > Choose a recipient > Submit
3. Notice that "Allow location access" modal is displayed

## Expected Result:
Get It" option should be displayed in allow location access modal

## Actual Result:
"Get it" button not displayed in Allow location access modal when scan expense

Instead "Continue" button is displayed

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<img width="1280" alt="Bug6639212_1729289167841!Screenshot_2024-10-18_at_5 56 46_PM" src="https://github.com/user-attachments/assets/996002ec-5707-40e2-8f94-729428fde094">

https://github.com/user-attachments/assets/56741e33-4299-4de4-a521-427ab566c5db

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848254647579098944</li>
        <li>Upwork Job ID: 1848254647579098944</li>
        <li>Last Price Increase: 2024-10-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @s77rt</details>

**Comment by IuliiaHerets** [comment] 2024-10-19 15:51
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-10-19 15:52
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Shahidullah-Muffakir** [comment] 2024-10-19 16:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
showing wrong text in the confirm button
### What is the root cause of that problem?
we are showing this:
```
 const getConfirmText = (): string => {
        if (!hasError) {
            return translate('common.continue');
        }
```
### What changes do you think we should make in order to solve the problem?

create a new text  for get it, and then use common.getIt
```
 if (!hasError) {
            return translate('common.getIt');
        }
```
### What alternative solutions did you explore? (Optional)

**Comment by omoh128** [comment] 2024-10-21 10:28
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
The location permission modal is displaying incorrect button text ("Continue") instead of the required "Get it" text when requesting location access.

**What is the root cause of that problem?**
The component is using the wrong translation key. Currently in `App/src/components/LocationPermissionModal/index.tsx`:
```typescript
if (!hasError) {
    return translate('common.continue');
}
```

**What changes do you think we should make in order to solve the problem?**

1. Add new translation key in language files:
```typescript
// en.ts
common: {
    getIt: "Get it"
}

// es.ts
common: {
    getIt: "Entendido"  
}

Using a conditional translation based on the modal context.


if (!hasError) {
    return isLocationModal ? translate('common.getIt') : translate('common.continue');
}

Creating a separate component for location-specific modals,


const LocationAccessButton = () => {
    return <Button text={translate('common.getIt')} />;
};

```

2. Update the modal component to use the new translation key:
```typescript
if (!hasError) {
    return translate('common.getIt');
}
```

What alternative solutions did you explore? (Optional)

Using a hardcoded string directly in the component.


if (!hasError) {
    return "Get it";
}

**Comment by s77rt** [comment] 2024-10-21 19:00
This is not a valid. Looking at the code we will show "Got it" only if you block location access on web platform. IOW
Is location access blocked ? "Got it" (web) / "Settings" (native). Otherwise "Continue"

@kadiealexander Let's close this one

**Closed** 2024-10-23 09:25 UTC
Labels: External, Daily, Help Wanted, Bug
