### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] Authorized payer - Enter key does not select another member as authorized payer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38203] opened 2024-03-13 06:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.51-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- User is an owner of Collect workspace.
- There is at least another admin in the workspace.

1. Go to staging.new.expensify.com.
2. Go to workspace settings > Collect workspace.
3. Go to Workflows.
4. Enable Make or track payments if not enabled.
5. Click Authorized payer.
6. Navigate to another admin via keyboard and hit Enter.

## Expected Result:
Enter key will select another admin as the authorized payer.

## Actual Result:
Enter key is not responsive when the selection is on another admin.
When the selection is on the authorized payer, Enter key exits the RHP.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/5e2009cf-13a4-40ea-a06c-bd9dae30b4d4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cb6806f250da1d85</li>
        <li>Upwork Job ID: 1767835771147452416</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 0</li>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2024-03-13 06:51
@Beamanator  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by Beamanator** [comment] 2024-03-13 08:51
This does look like it can be worked externally 👍  And it doesn't look like a big enough problem to be a deploy blocker - i bet this is a newer feature where we didn't build in the "Select with enter key"?

**Comment by Beamanator** [comment] 2024-03-13 08:52
Ya looks like it was built here: https://github.com/Expensify/App/pull/37629

**Comment by Beamanator** [comment] 2024-03-13 08:54
@luacmartins @shawnborton @ishpaul777 @jjcoffee can y'all help decide if we want to build this as a follow-up to the PR that just got to staging, or if we think this can be worked separately, in this issue, by another contrib?

**Comment by jjcoffee** [comment] 2024-03-18 10:11
@lschurr Can you assign me here as I was the C+ for the PR? Thanks! :pray:

**Comment by lschurr** [comment] 2024-03-19 22:41
Could you work through the checklist on this one @jjcoffee?

**Comment by jjcoffee** [comment] 2024-03-20 09:14
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37629
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37629/files#r1531725204
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to Workspace settings > Collect workspace.
2. Go to Workflows.
3. Enable Make or track payments if not enabled.
4. Click Authorized payer.
5. Navigate to another admin via keyboard and hit Enter, verify currect user is Selected as authoirized payer

Do we agree 👍 or 👎

**Comment by luacmartins** [comment] 2024-03-20 20:01
We'll add regression steps once this feature is fully implemented.

**Comment by jjcoffee** [comment] 2024-03-25 09:51
@lschurr Friendly bump for payment! :bow:

**Comment by lschurr** [comment] 2024-03-25 16:53
All set! Payment for $500 sent via Upwork to @jjcoffee

**Comment by lschurr** [comment] 2024-03-25 17:24
Ah it looks like this GH wasn't assigned to you so that's why the offer didn't go out @ishpaul777

**Comment by lschurr** [comment] 2024-03-25 17:44
Payment summary:

- Contributor: @ishpaul777 $500 (paid in Upwork)
- Contributor+: @jjcoffee $500 (paid in Upwork)

**Closed by lschurr** 2024-03-25 17:44 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
