### ISSUE TITLE
[HOLD for payment 2023-05-25] [$1000] On click of ESC while 'copy URL to clipboard' popup is open, app closes both 'copy URL to clipboard' popup and RHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18558] opened 2023-05-07 18:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open settings
3. Right click on Help to open 'copy URL to clipboard'
4. Click on ESC

## Expected Result: 
App should only close 'copy URL to clipboard' popup on ESC click like it does for delete workspace popup
## Actual Result: 
App closes both 'copy URL to clipboard' popup and RHN on single ESC click

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236695417-f8f36fa3-260f-4151-adb4-094e398bc254.mp4

https://user-images.githubusercontent.com/43996225/236695423-bbdaf8c3-5ed0-4907-9471-dbb7ef1f9035.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683388261937479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f4c841961ae2e365</li>
        <li>Upwork Job ID: 1656822582847545344</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-05-09 00:44
@dhanashree-sawant and/or @huzaifa-99 , can you please document all areas of the app where this is happening so we can fix them at one time?  I see two more instances here
<img width="445" alt="image" src="https://user-images.githubusercontent.com/22508304/236966118-1c0db7b2-dd72-4e05-9683-01cf16d01778.png">

**Comment by dhanashree-sawant** [comment] 2023-05-10 03:00
HI @mallenexpensify, Sure will go through it and let you know all the instances.

**Comment by dhanashree-sawant** [comment] 2023-05-10 14:53
Few more instances of the issue which @huzaifa-99 missed:
1. In settings page, help link
![image](https://github.com/Expensify/App/assets/87513216/0b02d452-8f03-488d-bebb-f5ed62515fc2)
2. In settings->workspaces->any workspace->Reimburse expenses->View all receipts link
![image](https://github.com/Expensify/App/assets/87513216/ca69f742-fbc4-4ff6-99f4-54b617273267)
3. In settings->workspaces->any workspace->Pay bills->View all bills link
![image](https://github.com/Expensify/App/assets/87513216/0a76325c-d5d8-416f-a7a8-fa2ddd486349)
4. In settings->workspaces->any workspace->Send invoices-> send invoice link and view all invoices link
![image](https://github.com/Expensify/App/assets/87513216/589c5c14-184a-4427-a3d9-b5c43ee12e12)

**Comment by mallenexpensify** [comment] 2023-05-12 00:44
Thanks @huzaifa-99 and @dhanashree-sawant , teamwork!!! 
@s77rt , can you please review?

**Comment by s77rt** [comment] 2023-05-12 11:07
@huzaifa-99 Thanks for the proposal. I don't think your RCA is complete. It seems that you are treating this bug as a feature request but it's actually a bug, the feature is already implemented on [ScreenWrapper](https://github.com/Expensify/App/blob/d76e066777902145eb02bdb5b838670c32f23754/src/components/ScreenWrapper/index.js#L45-L51).

**Comment by s77rt** [comment] 2023-05-12 11:22
@allroundexperts Thanks for the proposal. Your RCA is correct; We are missing the case where the modal is initially rendered visible. The suggested fix makes sense; Cover that case by calling `willAlertModalBecomeVisible` on `componentDidMount`.

I just have a non-blocking question, what cases would it cover calling  `willAlertModalBecomeVisible` on `componentWillUnmount`.

:ribbon: :eyes: :ribbon: C+ reviewed
cc @techievivek 

And please copy the proposal from the other issue to this for visibility.

**Comment by s77rt** [comment] 2023-05-12 11:44
@allroundexperts Yeah I got the idea. I'm asking if you can pinpoint a real existing case. I'm asking because although we mostly have **1** visible modal at a time, we may have **n** rendered modal at a time. If we are going to call `willAlertModalBecomeVisible` on `componentWillUnmount` we need to make sure that the modal getting unmounted was actually visible.

**Comment by s77rt** [comment] 2023-05-12 12:48
@allroundexperts Thanks for the quick follow up. Let's do this then:
1. `componentDidMount` if modal is visible call `Modal.willAlertModalBecomeVisible(true)`
2. `componentWillUnmount` if modal is visible call `Modal.willAlertModalBecomeVisible(false)`

**Comment by techievivek** [comment] 2023-05-15 08:25
Not overdue. Job has been assigned to @allroundexperts

**Comment by s77rt** [comment] 2023-05-18 17:42
- The PR that introduced the bug has been identified: This existed since day one. The following PR could have fixed it but it's not a regression https://github.com/Expensify/App/pull/5889
- The offending PR has been commented on: https://github.com/Expensify/App/pull/5889#issuecomment-1553375107
- A discussion in #expensify-bugs has been started: https://expensify.slack.com/archives/C049HHMV9SM/p1684430857010149
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**
1. Open App
2. Go to Settings
3. Right click on "Help"
4. Verify a modal popover is shown
5. Press ESC
6. Verify the modal is closed but the Settings page is still shown
7. Press ESC
8. Verify the Settings page is closed

**Comment by mallenexpensify** [comment] 2023-05-25 23:42
@s77rt , @allroundexperts , @dhanashree-sawant can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01f4c841961ae2e365

**Comment by s77rt** [comment] 2023-05-26 00:01
@mallenexpensify Accepted!

**Comment by dhanashree-sawant** [comment] 2023-05-26 02:56
Thanks @mallenexpensify, Accepted the offer.

**Comment by techievivek** [comment] 2023-05-30 03:52
Not overdue, we are waiting for the payment to complete.

**Comment by mallenexpensify** [comment] 2023-05-30 23:43
@dhanashree-sawant paid $250 for reporting, @s77rt and @allroundexperts paid $1500, including the 50% timeliness bonus. 

TestRail update GH 
- https://github.com/Expensify/Expensify/issues/287386

Thanks all!

**Closed by mallenexpensify** 2023-05-30 23:43 UTC
Labels: External, Daily, Awaiting Payment, Bug
