### ISSUE TITLE
[HOLD for payment 2023-08-08] [$1000] Web - The Not Allowed sign is not shown when dragging & dropping attachments if the settings or search bar is open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22305] opened 2023-07-05 20:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings
2. Drag and drop a file.
3. Notice that the Not Allowed sign is not shown and when you drop it, the attachment is opened in a new tab.

## Expected Result:
Not allowed sign is not shown

## Actual Result:
Not allowed sign is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fbade5ef-3439-434f-8edb-42b0ccf77430

https://github.com/Expensify/App/assets/93399543/502ba6e6-22b9-4c5d-b8e7-940076f87030

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688503808253309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c9a4080884f501d</li>
        <li>Upwork Job ID: 1678901220787363840</li>
        2023-07-19<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 25726938</li>
<li>daveSeife | Reporter | 25726939</li>
</ul></li>
    </ul>
</details>

**Comment by ishpaul777** [comment] 2023-07-08 12:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - The Not Allowed sign is not shown when dragging & dropping attachments if the settings or search bar is open 

### What is the root cause of that problem?
The current behaviour of dragover event datatransfer dropeffect is "copy" on setting screens.

### What changes do you think we should make in order to solve the problem?
We need to add a eventlistner for dragover and set e.datatransfer.dropeffect = "none" in callback function when the right sidebar renders

Ref- https://codepen.io/SitePoint/pen/epQPNP
### What alternative solutions did you explore? (Optional)
None

**Comment by michaelhaxhiu** [comment] 2023-07-11 23:00
This is indeed External, but I don't agree with the `Expected Result` as it stands -- it's not specific enough.

> ## Expected Result:
> Not allowed sign is not shown

What would be the best UX when dragging & dropping a file with the RHN/chatswitcher expanded?

**Comment by michaelhaxhiu** [comment] 2023-07-11 23:01
Ok I'm gonna take a small step backward, and removing all assignments until we get clear on the Expected Result. I posted on the slack thread to converse further.

**Comment by TopTen1310** [comment] 2023-07-12 02:20
Hello, Expensify team,

After reviewing the issue, I determined that it is common in browsers.
In detail, you didn't apply any prevent default effect according to onDrag handler of the parent div, so the above issue happened. You can check the same effect on any website. To resolve it, we need to override onDrag and onDragOver handlers, then call preventDefault() for them.
For example,

//////////////////////////////////////////////////////////////////////////////////////////
import React from 'react';

class App extends React.Component {
onDrop = (event) => {
event.preventDefault();
// Handle dropped files here
}

onDragOver = (event) => {
event.preventDefault(); // Prevent file from being opened in the browser
}

render() {
return (
<div
onDrop={this.onDrop}
onDragOver={this.onDragOver} // Necessary to prevent default behavior
style={{ height: '100vh', width: '100%' }}
>
You will not able to drop your file here.
</div>
);
}
}

export default App;
//////////////////////////////////////////////////////////////////////////////////////////

I can fix this issue within 1 hour.

Hope to hear from you soon.

Thanks

**Comment by TopTen1310** [comment] 2023-07-12 02:23
Contributor details
Your Expensify account email: yuan59880@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0120e214441fe64abb

Hello, Expensify team,

After reviewing the issue, I determined that it is common in browsers.
In detail, you didn't apply any prevent default effect according to onDrag handler of the parent div, so the above issue happened. You can check the same effect on any website. To resolve it, we need to override onDrag and onDragOver handlers, then call preventDefault() for them.
For example,

//////////////////////////////////////////////////////////////////////////////////////////
import React from 'react';

class App extends React.Component {
onDrop = (event) => {
event.preventDefault();
// Handle dropped files here
}

onDragOver = (event) => {
event.preventDefault(); // Prevent file from being opened in the browser
}

render() {
return (

You will not able to drop your file here.
); } }
export default App;
//////////////////////////////////////////////////////////////////////////////////////////

I can fix this issue within 1 hour.

Hope to hear from you soon.

Thanks

**Comment by ishpaul777** [comment] 2023-07-12 06:09
> This is indeed External, but I don't agree with the `Expected Result` as it stands -- it's not specific enough.
> 
> > ## Expected Result:
> > Not allowed sign is not shown
> 
> What would be the best UX when dragging & dropping a file with the RHN/chatswitcher expanded?

@michaelhaxhiu we can either just close the RHN when file is dragged over or show the drop not allowed cursor.

**Comment by michaelhaxhiu** [comment] 2023-07-18 19:22
Hmm collapsing the RHN could be an option too. 
I noticed that @daveSeife suggested just showing the 🚫 symbol.

I wonder if we have a pre-existing theme to rely on here 🤔

**Comment by michaelhaxhiu** [comment] 2023-07-18 19:44
Right now I am not sure if it makes sense to also add a 🚫 or something (e.g. on the cursor) to make this clear to the user that the upload won't work. I think we'd need to use this theme on all platforms if we do.

**Comment by ishpaul777** [comment] 2023-07-18 19:51
@michaelhaxhiu also on step 3 the the cursor changes to 🚫 with white square same as when dragging over the LHN,

**Comment by michaelhaxhiu** [comment] 2023-07-18 19:53
@ishpaul777 are you saying that's the behavior you see **today**? I don't see it chrome web 🤔 

Or are you saying that you suggest this 🚫 in this scenario?

**Comment by ishpaul777** [comment] 2023-07-18 19:55
I have noticed this 🚫 behaviour on LHN on web  while drafting the initial proposal and also in the screencast above

**Comment by michaelhaxhiu** [comment] 2023-07-18 19:59
Hm for some reason I don't see it on my Mac. Perhaps my Macbook doesn't do the same as PC in that scenario?

**Comment by ishpaul777** [comment] 2023-07-18 20:23
I am not aware of Macbook behaviour.  Can you please share a screencast of file dragging over the LHN? 

Cursor on Windows when on LHN-
https://www.loom.com/share/cd8d63e496a643879d32fe88a92d3d38?sid=579032d6-e9c6-4dcb-ad21-8f939f9e4e23

**Comment by ishpaul777** [comment] 2023-07-19 08:41
@robertKozik is dropping a file on LHN opens a new tab or silently fails. On windows it fails the drop.

**Comment by robertKozik** [comment] 2023-07-19 09:07
@ishpaul777 Fails gracefully, so here we have unified behaviour - video attached

https://github.com/Expensify/App/assets/61146594/8cf1e1f2-2f36-4628-94df-e57de7941bdc

As for the cursor, I'm not sure if it would work, but we can check the styles from `styles/utilites/cursor`. Maybe they will be applicable for this scenario if applied on right container. But if we cannot unify this, it's ok too

**Comment by robertKozik** [comment] 2023-07-19 12:07
Alright 👌🏼 as soon as I get confirmation that [this is expected behaviour](https://github.com/Expensify/App/issues/22305#issuecomment-1640862184) I'll proceed with checking the proposals

**Comment by robertKozik** [comment] 2023-07-21 16:56
@ishpaul777 I have one concern to your [proposal](https://github.com/Expensify/App/issues/22305#issuecomment-1627220271), as document-scoped listener won't get removed until this compoent would be unmounted. I think redirecting in new navigation only casuses navigation focus/blur events, not unmounting of whole page. Could you double check this scenario?
1. Redirect to RHN
2. Redirect back to chat
3. Verify that user is able to drag&drop attachment

**Comment by robertKozik** [comment] 2023-07-21 17:01
@TopTen1310 your proposal have correctly address the root cause, but it's very general and don't address new dot app itself

**Comment by TopTen1310** [comment] 2023-07-21 17:29
> @TopTen1310 your proposal have correctly address the root cause, but it's very general and don't address new dot app itself

@robertKozik So you said my proposal can't solve new dot app itself. Could you please explain more about it?

**Comment by robertKozik** [comment] 2023-07-21 17:38
I don't mean that, as preventing with listeners would solve the app. Your proposal doesn't follow the template, moreover you don't specified where to prevent the drag&drop within the app.  Your example didn't provide any conditions for preventing the drag&drop (like which components in app should be prevented from drag&dropping).

**Comment by TopTen1310** [comment] 2023-07-21 17:41
> I don't mean that, as preventing with listeners would solve the app. Your proposal doesn't follow the template, moreover you don't specified where to prevent the drag&drop within the app. Your example didn't provide any conditions for preventing the drag&drop (like which components in app should be prevented from drag&dropping).

Oh, Understood. Actually this is my first in Expensify, so I didn't think I needed to provide it in detail.
Thanks for your feedback. Is it okay to mention in detail about it for now?

**Comment by robertKozik** [comment] 2023-07-21 17:52
Sure, the proposal is yet to be chosen, but keep in mind that @ishpaul777's proposal was earlier than yours and looks very promising, I just have one minor concern to it

**Comment by ishpaul777** [comment] 2023-07-21 19:52
@robertKozik check this out 

https://github.com/Expensify/App/assets/104348397/cb26a9f8-5839-4306-9c1f-21d1818b1bf3

**Comment by robertKozik** [comment] 2023-07-24 18:25
@ishpaul777 Thanks for checking this scenario and confirming your solution. I really like your proposal as It introduces the reusable component for such a use-cases and tackles the root cause of the issue directly. Also it follows the expected behaviour from [here](https://github.com/Expensify/App/issues/22305#issuecomment-1640862184).

Due to these reasons I would go with the @ishpaul777 [proposal](https://github.com/Expensify/App/issues/22305#issuecomment-1627220271)

🎀 👀 🎀 C+ reviewed

**Comment by dangrous** [comment] 2023-07-24 19:39
Hi! I'm trusting y'all a bit on confirming what the expected behavior should be - my only question which I couldn't quite tell from the examples - When the RHN is open, can you still drop a file onto the main chat window (just not on the RHN itself?) or can you not drop a file at all until the RHN is closed.

(Proposal generally looks good but I wanted to make sure I understand what we're going for here before approving).

Thank you!

**Comment by ishpaul777** [comment] 2023-07-24 20:32
Thank you for reviewing the proposal, @robertKozik @dangrous, 

Regarding the expected behaviour, when the RHN is open the user won't be able to drop the file at all, neither on opaque bg nor the RHN itself.

**Comment by robertKozik** [comment] 2023-07-24 20:53
@dangrous it is the same behaviour we can see on the desktop app. When user tries to drag&drop the file when RHN is open, it just silently fails. Doesn't matter whether we drop it exactly on RHN or next to it.

**Comment by dangrous** [comment] 2023-07-24 21:26
Great, thank you both! This all makes sense - assigning @ishpaul777 now.

**Comment by ishpaul777** [comment] 2023-07-24 21:44
Thanks, Accepted the offer! Will raise a PR in few hours.

**Comment by ishpaul777** [comment] 2023-07-24 21:44
Thanks, Accepted the offer! Will raise a PR in a few hours.

**Comment by ishpaul777** [comment] 2023-07-31 15:39
Thanks for clarifying @dangrous. Can you please clarify what's the impact of this regression on compensation?

**Comment by dangrous** [comment] 2023-07-31 20:37
> Thanks for clarifying @dangrous. Can you please clarify what's the impact of this regression on compensation?

So this will dock the pay due to the regression, unfortunately. (cc @michaelhaxhiu) Technically the 7 days also resets, though that's moot here since I think it was the same day

**Comment by ishpaul777** [comment] 2023-08-01 11:24
Understood! Thanks for clarification.

**Comment by ishpaul777** [comment] 2023-08-04 15:23
@michaelhaxhiu according to guidelines, isn't it just dock the speed bonus due to bonus, i couldn't find the penalty for regression in docs

**Comment by michaelhaxhiu** [comment] 2023-08-04 15:33
https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#payment-for-contributions
>A 50% penalty will be applied to the Contributor and Contributor+ for each regression on an issue.

**Comment by sakluger** [comment] 2023-08-07 19:58
I went ahead and paid @daveSeife for the bug report today. Tomorrow is the payment date for the rest assuming no more issues arise.

@robertKozik could you please complete the BugZero checklist ([GH comment](https://github.com/Expensify/App/issues/22305#issuecomment-1658923186)) when you have some time so that we can close this issue out after payment? Thanks!

**Comment by daveSeife** [comment] 2023-08-08 00:35
@sakluger I have received the payment, thank you!

**Comment by robertKozik** [comment] 2023-08-08 13:15
@sakluger I'm not sure whether I filled it right, as this issue was not fixing any regression (only caused one 🥲). Ping me if it should be filled another way

> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR:  _**This PR was not fixing the regression**_
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. N/A
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

**Comment by dangrous** [comment] 2023-08-08 21:12
So you're right about it not being a regression, I believe. For the regression test, we might want to add one though - basically the testing steps in this issue. Thanks!

**Comment by ishpaul777** [comment] 2023-08-09 19:07
Bump @sakluger for pay reminder. Thanks!

**Comment by sakluger** [comment] 2023-08-09 23:21
Completed payment including 50% penalty for the regression.

@robertKozik thanks for filling out the checklist and writing out regression steps, looks perfect!

**Closed by sakluger** 2023-08-09 23:21 UTC
Labels: External, Daily, Awaiting Payment, Bug
