### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] Workspace - Go to #announce room option is missing when app is in #focus mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33995] opened 2024-01-05 01:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to Settings > Workspaces > Create new workspace
2. Click 3-dot menu > Go to #announce room (to make sure #announce is read)
3. Log out
4. Log in
5. Go to Settings > Workspaces
6. Click the workspace created in Step 2
7. Click 3-dot menu
8. Disable #focus mode by going to Settings > Preferences > Priority mode > Most recent
9. Return to the 3-dot menu of the workspace in Step 7

## Expected Result:
Go to #announce room option is present in the overflow menu regardless of the priority mode

## Actual Result:
Go to #announce room option is absent in the overflow menu when the app is in #focus mode (Step 7).
It appears when the priority mode is "Most recent" (Step 9)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67c2f6cc-cc90-4c21-b995-c5e2bf9cc82f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fcb45002c3d18848</li>
        <li>Upwork Job ID: 1743085534873509888</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28096226</li>
<li>rojiphil | Contributor | 28096227</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2024-01-05 01:51
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Request with empty distance can be created by changing the link to participant link
### What is the root cause of that problem?
The root cause is that we are checking account room here.
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/pages/workspace/WorkspaceInitialPage.js#L216-L222
### What changes do you think we should make in order to solve the problem?
We need to delete above condition.
### What alternative solutions did you explore?
N/A

**Comment by rojiphil** [comment] 2024-01-06 12:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

`Go to #announce room` option is missing in the 3 Dots menu of a workspace. This is the problem we are trying to solve. 

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/pages/workspace/WorkspaceInitialPage.js#L103C1-L105C14), we look within `reports` in Onyx to find out `policyAnnounce` room. If not found, the menu option is not shown as seen [here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/pages/workspace/WorkspaceInitialPage.js#L216C1-L222C10). The recent intentional changes in BE to send reduced content in `openApp` results in the `policyAnnounce` reports to be absent in Onyx which is what is causing this issue.  
 
### What changes do you think we should make in order to solve the problem?

We can tackle this problem within the `workspace` policy itself by introducing a property for `announce` room report id. For now, let’s call this `policyAnnounceReportID`. 

The following changes can be done:
1) During optimistic creation of workspace chats i.e. [here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/actions/Policy.js#L1207C1-L1221C19) and [here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/libs/actions/Policy.js#L1568C1-L1582C7), we can save `policyAnnounceReportID: announceChatReportID`
2) Further, we can display the `Go to #announce room` option in 3Dots menu based on `policyAnnounceReportID` [here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/pages/workspace/WorkspaceInitialPage.js#L216) and also use this for navigation [here](https://github.com/Expensify/App/blob/0c351a4534f0bfb8278f2fa9b8c0a10187b6c8bb/src/pages/workspace/WorkspaceInitialPage.js#L220)

However, this approach would also need BE’s support in maintaining a property for `policyAnnounceReportID` within `policy`. 

If we are going this way, it may be better to extend this issue to include support for `admin` rooms too.

### What alternative solutions did you explore? (Optional)

**Comment by situchan** [comment] 2024-01-08 15:52
I'd like to hear engineer's thought as BE change is required if this should be fixed.
🎀 👀 🎀

**Comment by unicorndev-727** [comment] 2024-01-09 12:35
https://github.com/Expensify/App/blob/dc3e19bdcc95023d74cd7fdd433f6208707eaaf8/src/pages/workspace/WorkspaceInitialPage.js#L209-L215

This is because we don't show if adminRoom report doesn't exist.

**Comment by unicorndev-727** [comment] 2024-01-09 12:39
We need to check when BE send the all chat report. `focus` mode or `most recent`?
if BE doesn't send all chat report on both mode, we need to introduce new mode so that BE send all chat report to the FE, I think.

**Comment by MariaHCD** [comment] 2024-01-09 13:06
Just to clarify, @situchan which proposal do you recommend here? :)

> if BE doesn't send all chat report on both mode,

@unicorndev-727 We don't send all chat reports on both modes, focus mode is specifically designed to reduce the number of reports returned from the BE.

**Comment by situchan** [comment] 2024-01-09 13:10
I haven't recommended yet. I just assigned you just to hear your thoughts.

**Comment by situchan** [comment] 2024-01-09 13:12
At least I give 👎 to @unicorndev-727's proposal

**Comment by MariaHCD** [comment] 2024-01-09 13:13
I like the idea of having the BE return the chat report IDs in the policy Onyx data as @rojiphil is suggesting. We can then use that to navigate to the room even if we're in focus mode.

**Comment by MariaHCD** [comment] 2024-01-11 12:56
I've created the BE PRs for including two new props for the policy data: `chatReportIDAnnounce` and `chatReportIDAnnounce` (I believe we'll need to add these to Policy.ts as part of the App PR as well)
- https://github.com/Expensify/Auth/pull/9617
- https://github.com/Expensify/Web-Expensify/pull/40436

I can update here once deployed to staging.

@situchan thoughts?

**Comment by situchan** [comment] 2024-01-11 12:59
👍 from me.
Once they're merged and deployed to staging, we can assign @rojiphil for app PR

**Comment by situchan** [comment] 2024-01-11 13:00
> I've created the BE PRs for including two new props for the policy data: `chatReportIDAnnounce` and `chatReportIDAnnounce` (I believe we'll need to add these to Policy.ts as part of the App PR as well)

one is `chatReportIDAdmins` maybe?

**Comment by MariaHCD** [comment] 2024-01-11 13:09
Whoops, yes, it's `chatReportIDAdmins` - updated my comment :)

**Comment by MariaHCD** [comment] 2024-01-12 07:35
The BE changes are on staging! Assigning @rojiphil.

![Screenshot 2024-01-12 at 11 35 36 AM](https://github.com/Expensify/App/assets/12268372/3c2f6c74-4a93-4e27-9d0f-ef2cad4069e1)

**Comment by MariaHCD** [comment] 2024-01-15 11:06
Not overdue, awaiting the PR from @rojiphil

**Comment by rojiphil** [comment] 2024-01-15 12:36
I will look into this today and share the update in a day.

**Comment by rojiphil** [comment] 2024-01-18 15:02
@situchan
Gentle bump for your feedback to the PR comment  [here](https://github.com/Expensify/App/pull/34565#issuecomment-1893647524).

**Comment by miljakljajic** [comment] 2024-01-22 12:50
@situchan I'm noticing multiple bumps for your feedback on the PR. When will you be able to prioritise the review?

**Comment by situchan** [comment] 2024-01-22 12:51
updating today

**Comment by rojiphil** [comment] 2024-01-24 16:35
@situchan 
Can you please prioritize on the PR review [here](https://github.com/Expensify/App/pull/34565)?

**Comment by situchan** [comment] 2024-01-24 16:48
will complete review eod

**Comment by miljakljajic** [comment] 2024-02-07 09:14
Paid and closed contracts!

**Closed by miljakljajic** 2024-02-07 09:14 UTC
Labels: External, Weekly, Awaiting Payment, Bug
