### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] The Composer isn't getting focus again after the attachment modal is dismissed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#52898] opened 2024-11-21 13:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @DylanDylann 
**Slack conversation** (hyperlinked to channel name): [ts_external_expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1732158845744109)

## Action Performed:
1. Go to any chat
2. Click on Emoji button on composer
3. Click outside to turn off emoji modal
4. The main composer is focused again
5. Click on Search button
6. Click outside to turn off search modal
7. The main composer is focused again
8. Click on + Button > Add attachment
9. Close the attachment modal

## Expected Result:
The Composer should be focused again
## Actual Result:
The Composer isn't getting focus again
The same issue also happens when turning off task creation RHP
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

https://github.com/user-attachments/assets/aca55734-0f61-4127-b0be-ba4d7d56d8e9

https://github.com/user-attachments/assets/b7547442-247f-4035-a8c9-3146d18c1a84

https://github.com/user-attachments/assets/e9a46911-ecb7-4d3b-a2c9-2dbe9da8eb89

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021861194329606469814</li>
        <li>Upwork Job ID: 1861194329606469814</li>
        <li>Last Price Increase: 2024-11-25</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 105121364</li>
<li>FitseTLT | Contributor | 105121366</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @VictoriaExpensify</details>

**Comment by m-natarajan** [comment] 2024-11-21 13:03
Discovered this bug while reviewing [this PR](https://github.com/Expensify/App/pull/51172) by @DylanDylann

**Comment by DylanDylann** [comment] 2024-11-21 13:13
@VictoriaExpensify  Could I take over this issue if this is external? because of more context [here](https://github.com/Expensify/App/issues/10731)

**Comment by VictoriaExpensify** [comment] 2024-11-25 23:44
Thanks for the context @DylanDylann - It's all yours

**Comment by VictoriaExpensify** [comment] 2024-11-25 23:45
Not overdue

**Comment by FitseTLT** [comment] 2024-11-26 15:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The Composer isn't getting focus again after the attachment modal is dismissed

### What is the root cause of that problem?
We are not focusing the composer on closing of the attachment modal unlike emoji picker case here
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L529
### What changes do you think we should make in order to solve the problem?

We should pass `focus` for `onCanceledAttachmentPicker` of the attachment picker
https://github.com/Expensify/App/blob/084a711842d6be379b18491ebe2cc6b48280006e/src/pages/home/report/ReportActionCompose/ReportActionCompose.tsx#L465
```
                                            onCanceledAttachmentPicker={focus}

```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-11-27 15:30
Please detail your alternative solution. Note that we only apply this fix for the large screen

Additionally, you missed the second bug: The main composer focus again after turn off RHP strict create expense but not in other RHP

**Comment by FitseTLT** [comment] 2024-11-27 22:32
@DylanDylann [Updated](https://github.com/Expensify/App/issues/52898#issuecomment-2501114819)

**Comment by DylanDylann** [comment] 2024-11-28 03:17
I don't think setTimeout is recommended in our codebase

**Comment by FitseTLT** [comment] 2024-11-28 11:26
@DylanDylann what about runAfterInteraction?

**Comment by FitseTLT** [comment] 2024-11-28 11:53
@DylanDylann Let me explain it a bit for you:
For our modals we already have our method `isReadyToFocus`
https://github.com/Expensify/App/blob/70461d0871b9db9f149437e923c695476b02ae84/src/libs/focusComposerWithDelay/index.ts#L30
which will dispatch the focus when the open modal has been dismissed
https://github.com/Expensify/App/blob/70461d0871b9db9f149437e923c695476b02ae84/src/components/Modal/BaseModal.tsx#L151-L153
The problem is RHP are not like our modals and it is opened by navigation and the modal value will be set to false when the current screen/RHP is blurred here
https://github.com/Expensify/App/blob/70461d0871b9db9f149437e923c695476b02ae84/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L214-L215
that will trigger the effect to focus the composer here
https://github.com/Expensify/App/blob/70461d0871b9db9f149437e923c695476b02ae84/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L646-L654
But the onBlur is called too early immediately when the navigation away from the RHP starts even before the animation to close the RHP is finished so if there is a text input in the RHP our focus function will not focus the composer.
Therefore for a similar solution we used as `isReadyToFocus` one we should set some file-level variable on blur of the screen like `didRHPDismissed` and here instead immediately resolving when there is no promise when the `didRHPDismissed` is true we will resolve it after some delay as `CONST.ANIMATED_TRANSITION` because the modal is correctly dismissed  by that time. WDYT

**Comment by DylanDylann** [comment] 2024-11-29 03:29
@FitseTLT's https://github.com/Expensify/App/issues/52898#issuecomment-2501114819 looks good to me

After testing I see setTimeout gives a better output than runAfterInteraction. However, runAfterInteraction can be a safer option because we need to avoid using setTimeout as much as possible in our App.

Note in the PR phase: We need to make sure this change doesn't affect the current behavior on mobile web, app

🎀 👀 🎀 C+ Reviewed

**Comment by VictoriaExpensify** [comment] 2024-12-16 22:15
Payment Summary:
Contributor: @FitseTLT paid $250 via Upwork
C+: @DylanDylann paid $250 via Upwork

**Closed by VictoriaExpensify** 2024-12-16 22:15 UTC
Labels: External, Daily, Awaiting Payment, Bug
