### ISSUE TITLE
[HOLD for payment 2024-11-07] Android Hybrid - Launch - App crashes everytime it is launched.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51682] opened 2024-10-29 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.55-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the Expensify app
2. Verify the app is correctly opened and can be navigated properly

## Expected Result:
The user should be able to launch the app, log in and navigate properly

## Actual Result:
The Expensify app crashes everytime it is launched

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/f79250c9-dc3f-4261-bfa6-70228390a851

[logs3.txt](https://github.com/user-attachments/files/17560996/logs3.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arosiclair** [comment] 2024-10-29 20:32
@mountiny @hannojg @kirillzyusko looks like you guys just worked on this here: https://github.com/Expensify/App/issues/51454. Can you guys take a look?

**Comment by arosiclair** [comment] 2024-10-29 20:36
I do not have access to the beta version of OldApp atm so I'm having trouble reproducing.

**Comment by kirillzyusko** [comment] 2024-10-29 21:01
@arosiclair in #51454 we had a different problem (the app was trying to use LocalForage which is available on web only).

The current crash happens because of this:

```bash
Caused by: undefined is not an object (evaluating 'Store.ReportHistory.bindCacheClearingEvents') at position 81:24 in app/expensify.js
```

**Comment by Beamanator** [comment] 2024-10-30 08:52
@kirillzyusko i'm going to ping you in slack to see if you have any more ideas about that crash 🙏

**Comment by Beamanator** [comment] 2024-10-31 07:10
Seems this should have been fixed in https://github.com/Expensify/App/pull/51746, right?

**Comment by arosiclair** [comment] 2024-10-31 16:50
Fixed in https://github.com/Expensify/App/pull/51746

**Closed by arosiclair** 2024-10-31 16:50 UTC
Labels: Engineering, Weekly
