### ISSUE TITLE
[HOLD for payment 2024-01-18] [$250] Dev: IOS - App crashes when opening a transaction report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27392] opened 2023-09-13 20:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the ios app
2. Open an iou report that has transactions
3. Click on a transaction to open the transaction report

## Expected Result:
App does not crash

## Actual Result:
App crashes with console error: Render Error Invalid time value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.69.1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d5d81b9a-3fa4-4fdc-9c30-ae1b6d2b48c0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tienifr
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694440628004359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d24045ce9cc8210</li>
        <li>Upwork Job ID: 1716907956821823488</li>
        <li>Last Price Increase: 2024-06-27</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 28015222</li>
<li>tienifr | Contributor | 28015224</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by DylanDylann** [comment] 2023-09-18 08:47
I also see this bug on the IOS App (production version). It seems this bug is serious

**Comment by NicMendonca** [comment] 2023-09-18 23:03
@situchan proposal here for you! ^^

**Comment by NicMendonca** [comment] 2023-09-21 20:53
bump @situchan ^

**Comment by situchan** [comment] 2023-09-25 10:36
reviewing today

**Comment by situchan** [comment] 2023-09-28 10:58
@tienifr proposal looks promising but do you have clear repro step?

**Comment by NicMendonca** [comment] 2023-10-02 20:22
@situchan have you been able to try? ^^

**Comment by NicMendonca** [comment] 2023-10-05 21:52
@situchan bumped you here: https://expensify.slack.com/archives/C02NK2DQWUX/p1696542533862449

**Comment by situchan** [comment] 2023-10-10 13:02
I managed to reproduce following this step - https://github.com/Expensify/App/issues/27392#issuecomment-1738941311.
@tienifr's [proposal](https://github.com/Expensify/App/issues/27392#issuecomment-1721053555) LGTM!
🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2023-10-10 13:54
Sounds good since we are already using format.js, assigning @tienifr

**Comment by mvtglobally** [comment] 2023-10-12 03:51
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2023-10-12 10:57
> Since this one is the prerequisite to fix #27927. I would combine them into one PR #29113.

If so, you could put #27927 on hold until PR for this one is merged.

**Comment by NicMendonca** [comment] 2023-10-24 20:02
@situchan @tienifr can you both please apply to the job? https://www.upwork.com/jobs/~010d24045ce9cc8210

**Comment by pecanoro** [comment] 2023-10-25 17:00
@tienifr should we open this back to proposals?

**Comment by pecanoro** [comment] 2023-10-30 14:20
I am returning this one back to the pool since haven't got any replies from @tienifr in more than a week

**Comment by situchan** [comment] 2023-11-02 17:09
@tienifr can you please share test branch? I now have Sonoma so able to valid your solution

**Comment by pecanoro** [comment] 2023-11-06 16:44
Waiting for @tienifr and @situchan to test the proposal

**Comment by pecanoro** [comment] 2023-11-08 15:49
friendly bump!!!

**Comment by situchan** [comment] 2023-11-10 09:10
@tienifr so you mean that original PR should work now?

**Comment by NicMendonca** [comment] 2023-11-13 13:52
@tienifr @situchan any update here?

**Comment by pecanoro** [comment] 2023-11-20 16:35
@situchan friendly bump!

**Comment by situchan** [comment] 2023-11-24 13:11
Sorry I will test and approve on Monday

**Comment by pecanoro** [comment] 2023-11-27 16:00
@situchan Friendly bump 😄

**Comment by pecanoro** [comment] 2023-12-04 20:09
@situchan Friendly bump!

**Comment by pecanoro** [comment] 2023-12-07 15:04
@situchan Pinged you in Slack in case you missed all these pings haha

**Comment by situchan** [comment] 2023-12-08 22:25
Sorry for late. @tienifr's [new proposal](https://github.com/Expensify/App/issues/27392#issuecomment-1791126160) looks good to me.
cc: @pecanoro 
🎀 👀 🎀 C+ reviewed

**Comment by pecanoro** [comment] 2023-12-08 22:59
Ok! Let's try this again haha Assigning @tienifr

**Comment by situchan** [comment] 2024-01-10 20:11
Not deploy blocker - https://github.com/Expensify/App/issues/34247#issuecomment-1885638041

**Comment by NicMendonca** [comment] 2024-01-17 17:57
everyone has been paid!

**Comment by pecanoro** [comment] 2024-06-26 14:19
@jliexpensify It seems we are missing a reporting bonus here for a while ago. Could you double-check? Nicole is OOO so she won't be able to check for a while

**Comment by jliexpensify** [comment] 2024-06-27 02:52
I can confirm that @tienifr quaklifies for a $50 payout as [indicated here](https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649)

**Comment by jliexpensify** [comment] 2024-06-27 02:53
Damn, I thought that would create a new Upworks job.

**Comment by jliexpensify** [comment] 2024-06-27 02:54
Ah, no need! I can just do a ND payment 😓 

- @tienifr $50 ([Reporting Bonus from ages ago](https://github.com/Expensify/App/issues/27392#issuecomment-2193068292))

**Closed by jliexpensify** 2024-06-27 02:54 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-08 17:36
$50 approved for @tienifr

**Comment by kavimuru** [comment] 2024-10-25 19:49
Not reproducible with this build ad hoc build on iOS https://github.com/Expensify/App/pull/51456#issuecomment-2437546337
