### ISSUE TITLE
[$500] Distance-There is no space between category &Request button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32522] opened 2023-12-05 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**1.4.8-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab---Request money--- Distance
3. Enter start and finish waypoints
4. Tap next
5. Select a WS
6. Tap on Each and every field (eg: Amount, description, date, distance and category) and note enough space is between selected field and next field)
7. Repeat the same for all fields

## Expected Result:
When tapping on "category", like other fields, there must be enough space between selected (Category) field and next field (Request button)

## Actual Result:
No space between "category" and "request amount" button like other sections while making distance request
When tapping on "category", like other fields, there is no enough space between selected (Category)field and next field (Request button)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/13bb6bd6-3738-426f-9054-c2b30f643238

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c3a7580a767d207</li>
        <li>Upwork Job ID: 1732127606928424960</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-12-05 20:05
This is expected as the button is simply docked to the screen bottom and does not have the top padding/margin. It's the same on other Money Request types, and depends solely on the screen height.

**Comment by hamzasaleem2** [comment] 2023-12-05 21:12
## Proposal

the issue is with the padding, 
currently padding only applies to right,left,bottom but is missing the top padding.
i found an issue here of missing calculation for top padding.

https://github.com/Expensify/App/blob/f80fbe34db2dbb5839946ccfe8b46d8c16462f83/src/styles/StyleUtils.ts#L294-L301

### Please re-state the problem that we are trying to solve in this issue.
padding problem with the Request {amount_money}, no space between "category" and request button on `MoneyRequestConfirmPage.js` page.

### What is the root cause of that problem?
top-padding key is missing from `getSafeAreaPadding` function

### What changes do you think we should make in order to solve the problem?
top padding should also be calculated and changed like other 3 padding

i tested the padding by changing in browser mode, and i get this fixed with correct spacing between the button and the View react component.

here's how it should look after the fix.
<img width="344" alt="Screenshot 2023-12-06 at 2 07 29 AM" src="https://github.com/Expensify/App/assets/133140745/1e408be7-50ba-4ae2-9a8a-3a1462e16019">

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-12-07 05:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is no space between category &Request button
### What is the root cause of that problem?
We don't add padding-top to the button on the confirmation page

https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/components/FixedFooter.tsx#L15

We only apply padding-horizontal and padding-bottom
### What changes do you think we should make in order to solve the problem?
If we add style padding-top or padding-vertical in FixedFooter Component
https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/components/FixedFooter.tsx#L15
Because the `FixedFooter` Component is used in many places, It causes breaks in other places like this 

<img width="1440" alt="Screenshot 2023-12-07 at 12 07 33" src="https://github.com/Expensify/App/assets/141406735/fd0dbdf7-62b8-4095-8110-c18ab08ae449">

In this case, the previous element has a padding-bottom style. So if we add padding-top to the `FixedFooter` Component, the space will become so large

If we add padding-top in `FixedFooter` Component, we need to ensure that in all used `FixedFooter` places, the children component doesn't have padding/margin-top style and the previous element doesn't have padding/margin-bottom styles
For example, in this case
<img width="1440" alt="Screenshot 2023-12-07 at 12 07 33" src="https://github.com/Expensify/App/assets/141406735/fd0dbdf7-62b8-4095-8110-c18ab08ae449">

We can wrap both buttons and referred program Notes in `FixedFooter`

Additional: we also consider using `FixedFooter` Component in other footers for consistency 

### What alternative solutions did you explore? (Optional)
I suggest that we don't make any changes FixedFooter Component. In 2 button here
https://github.com/Expensify/App/blob/43b17220873536cba7e22723d160f719a2b9d4e3/src/components/MoneyRequestConfirmationList.js#L501
we should add `style={[styles.pt5]}`   // We need to confirm with the design team about the suitable padding top here

This bug also happens in some other places like RequestMoneyParticipantPage, WorkspaceInvitePage, NewChatPage,... We also need to add padding on top to fix

**Comment by Christinadobrzyn** [comment] 2023-12-07 22:15
The steps in the QA make it sound like the issue is AFTER you've clicked the Category button but I don't see an issue with spacing them, as @paultsimura mentioned, it seems like the issue is on the main screen. 

Asking QA to confirm - https://expensify.slack.com/archives/C9YU7BX5M/p1701987277815159

**Comment by Christinadobrzyn** [comment] 2023-12-08 20:42
Okay so the issue is that the spacing between Category and Request is different from the other fields. I'm not sure this is an urgent bug to fix. @ntdiary what do you think? Is there any reason to work on this now and not as part of another job?

**Comment by jacobkim9881** [comment] 2023-12-09 07:48
@DylanDylann 
> This bug also happens in some other places like RequestMoneyParticipantPage, WorkspaceInvitePage, NewChatPage,... We also need to add padding on top to fix

Adding `padding-top` such places is not needed. Editing padding `FixedFooter` changes padding to other Footers. But I am not sure your solution can solve problems by adding padding to such places. 0 `padding-top` doesn't make any issue without Request money confirmation page but such places. I think there were developer's intent to add no padding-top.

**Comment by paultsimura** [comment] 2023-12-09 07:58
@Christinadobrzyn @ntdiary according to the [initial design](https://github.com/Expensify/App/issues/3055), the top padding on the fixed footer was not added intentionally.

Is the money request flow an exception here?

**Comment by jacobkim9881** [comment] 2023-12-09 11:54
Contributor details
Your Expensify account email: jacobkim9881@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a8c81cab2f86058e

**Comment by Christinadobrzyn** [comment] 2023-12-09 18:12
> @Christinadobrzyn @ntdiary according to the https://github.com/Expensify/App/issues/3055, the top padding on the fixed footer was not added intentionally.
> 
> Is the money request flow an exception here?

Ah good catch @paultsimura! I should have checked for a previous issue related to this. @Jag96 or @parasharrajat could you help us determine if the spacing between Category and the Request button need to be fixed?

**Comment by Christinadobrzyn** [comment] 2023-12-11 18:31
Awesome thank you for your help @ntdiary and @parasharrajat! I'll close without action.

**Closed by Christinadobrzyn** 2023-12-11 18:31 UTC
Labels: External, Daily, Help Wanted, Bug
