### ISSUE TITLE
[$250] Search-App crashes when deleting all expenses in Shared after deleting one of them in Expenses

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45513] opened 2024-07-16 19:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.7-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit two expenses.
4. Go to Search > Expenses.
5. Go to Search > Shared (Important).
6. Go back to Search > Expenses.
7. Click checkbox on one expense (only one).
8. Click on the dropdown > Delete.
9. Delete the expense.
10. Go to Search > Shared without switching to any other page (Important).
11. Click Select all checkbox to select both expenses (including the already deleted one).
12. Click on the dropdown > Delete.
13. Delete the selected expenses.
## Expected Result:
App will not crash.

## Actual Result:
App crashes.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

[Uploading Bug6543392_1721092873177!staging.new.expensify.com-1721092641739.txt…]()

https://github.com/user-attachments/assets/e468a306-3adf-47ea-be6f-1d668aaae7c7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d3b370e3b25c0229</li>
        <li>Upwork Job ID: 1814395190825877892</li>
        <li>Last Price Increase: 2024-08-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by m-natarajan** [comment] 2024-07-16 19:23
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-07-17 08:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes.

### What is the root cause of that problem?
The `reportIDToTransactions[reportKey]` can be undefined when we delete all expense

https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/libs/SearchUtils.ts#L207-L211
### What changes do you think we should make in order to solve the problem?
We should check `reportIDToTransactions[reportKey]` is undefined or not before update here

```
} else if (reportIDToTransactions[reportKey]) { 
     reportIDToTransactions[reportKey].transactions = [transaction]; 
} 
```
https://github.com/Expensify/App/blob/52b8fddcda6177b4bf4aa9a803853a1b2670daef/src/libs/SearchUtils.ts#L209-L211

### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2024-07-17 19:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app crash when deleting all expense in Shared search page.

### What is the root cause of that problem?
When we delete one of the expenses from the Expense tab and then open the Shared tab, the search API result still shows the deleted expense. The search API response returns an Onyx merge request that actually doesn't include the deleted expense, but because it's a merge request, the deleted expense isn't removed from Onyx.

For example, let's say we delete transaction1.
[transaction1, transaction2] merge with [transaction2] -> [transaction1, transaction2]

Nothing changed.

The API should return null for the deleted transaction so it's removed from Onyx. Now, when we delete the grouped expense, it will delete the whole transaction. For this one, the `DeleteMoneyRequestOnSearch` request clears both the IOU report and the other transactions (transaction2 in our example) correctly.
<img width="359" alt="image" src="https://github.com/user-attachments/assets/2c547367-fff0-44ce-9ab3-dd04204e732a">

But because the transaction1 still exists and the page re-renders, it eventually crashes in this block.
https://github.com/Expensify/App/blob/b928e40d997ed2bb11bc9b990f16e422f1121bcb/src/libs/SearchUtils.ts#L209-L211

The reason is that `reportIDToTransactions[reportKey]` is undefined, but we are trying to access and set the `transactions` attribute. It's undefined because we haven't initialized the mapping for the specific `reportKey` yet.

The way it works is that it will initialize the `reportIDToTransactions[reportKey]` from the IOU report data,
https://github.com/Expensify/App/blob/b928e40d997ed2bb11bc9b990f16e422f1121bcb/src/libs/SearchUtils.ts#L162-L179

then when it encounters a `transaction`, it will just update the `reportIDToTransactions[reportKey].transactions`.
https://github.com/Expensify/App/blob/b928e40d997ed2bb11bc9b990f16e422f1121bcb/src/libs/SearchUtils.ts#L207-L211

But in our case, the IOU report is already deleted and the transaction1 still exists, thus it crashes.

### What changes do you think we should make in order to solve the problem?

Initialize the object instead of directly accessing the property.
```
reportIDToTransactions[reportKey] = {
    ...(reportIDToTransactions[reportKey] ?? {}),
    transactions: [transaction]
};
```

**Comment by strepanier03** [comment] 2024-07-19 20:21
Putting this forward for now, but I'm unable to test as I'm troubleshooting a different issue with loading staging atm.

**Comment by rojiphil** [comment] 2024-07-24 09:31
Reviewing today

**Comment by rojiphil** [comment] 2024-07-29 08:41
Hmm… I am unsure why the deleted expense is not removed from the `shared` search results. Isn’t that the problem to be addressed here? 
cc @luacmartins

**Comment by luacmartins** [comment] 2024-07-29 15:04
We should fix the transaction not being removed in the first place, but we can also introduce the conditional chaining to be safe and prevent a crash. For the first solution, I'm thinking of making the API return a `set` onyx update if offset = 0, since we always want to clear the results and start fresh in that case. Subsequent requests with offset > 0 would use a `merge` operation.

**Comment by mvtglobally** [comment] 2024-08-23 12:04
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-08-23 14:06
This is fixed. Closing.

**Closed by luacmartins** 2024-08-23 14:06 UTC
Labels: External, Weekly, Help Wanted, Overdue, Bug
