### ISSUE TITLE
[HOLD for payment 2024-09-18][$250] Workspaces -"Add custom segment or record" image appears briefly after adding the first one

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47501] opened 2024-08-15 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/Web-Expensify/pull/42969
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to NetSuite and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Navigate to Accounting - Import - Custom Segments/records
9. Click on the "Add custom segment/record" button
10. Add a Custom record with any random data

## Expected Result:
I should only the added segment or record.

## Actual Result:
"Add custom segment or record" image appears briefly after adding the first one.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Note: A shorter video showing the problem is here: https://github.com/Expensify/App/issues/47501#issuecomment-2291851003

https://github.com/user-attachments/assets/08925f2c-ea0d-40f1-8b82-278317c46d79

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f07df597970e1a9f</li>
        <li>Upwork Job ID: 1824147642331660429</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by izarutskaya** [comment] 2024-08-15 14:43
Created by this comment https://github.com/Expensify/Web-Expensify/pull/42969#issuecomment-2265845791

**Comment by aldo-expensify** [comment] 2024-08-15 17:50
The relevant part of the video un the body is this:



https://github.com/user-attachments/assets/a1d827a1-f283-4eaf-bc4b-25670976337e

This screen frashing briefly after having added the first segment:

![Uploading image.png…]()

**Comment by puneetlath** [comment] 2024-08-15 18:09
It is short, but I feel like we should still fix it if possible. An external contributor could do it right?

**Comment by puneetlath** [comment] 2024-08-21 19:45
Updated the price to see if we can get a proposal.

**Comment by NJ-2020** [comment] 2024-08-22 03:55
Is there is any NetSuite credentials for testing this issue? Thanks

cc: @puneetlath

**Comment by CyberAndrii** [comment] 2024-08-22 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Add custom segment or record" image appears briefly after adding first segment.

### What is the root cause of that problem?

It's a bug with `withOnyx` where it doesn't give the most up-to-date data, in this case on the first rendering. This causes the "Add custom segment or record" page to appear until `withOnyx` returns the correct value during the second render.

### What changes do you think we should make in order to solve the problem?

As `withOnyx` is now deprecated, we can replace it with `useOnyx` in `withPolicy` component

https://github.com/Expensify/App/blob/56f021d20c548770c4e7333db553989fa2a65007/src/pages/workspace/withPolicy.tsx#L92-L99

**Comment by CyberAndrii** [comment] 2024-08-22 09:25
One thing — I haven't found a consistent way to reproduce this with 100% certainty about my solution. It happens once in about 10 attempts. Maybe you have some ideas?

> Is there is any NetSuite credentials for testing this issue? Thanks

@NJ-2020 you can disable credentials validation with this changes

```diff
diff --git a/src/pages/workspace/accounting/PolicyAccountingPage.tsx b/src/pages/workspace/accounting/PolicyAccountingPage.tsx
index 11c47a21f2e..869dd8cf600 100644
--- a/src/pages/workspace/accounting/PolicyAccountingPage.tsx
+++ b/src/pages/workspace/accounting/PolicyAccountingPage.tsx
@@ -231,7 +231,7 @@ function PolicyAccountingPage({policy}: PolicyAccountingPageProps) {
             return [];
         }
         const shouldShowSynchronizationError = !!synchronizationError;
-        const shouldHideConfigurationOptions = isConnectionUnverified(policy, connectedIntegration);
+        const shouldHideConfigurationOptions = false;
         const integrationData = getAccountingIntegrationData(connectedIntegration, policyID, translate, policy);
         const iconProps = integrationData?.icon ? {icon: integrationData.icon, iconType: CONST.ICON_TYPE_AVATAR} : {};
```

```diff
diff --git a/src/pages/workspace/accounting/netsuite/import/NetSuiteImportPage.tsx b/src/pages/workspace/accounting/netsuite/import/NetSuiteImportPage.tsx
index c3d77b656b5..15bc437782b 100644
--- a/src/pages/workspace/accounting/netsuite/import/NetSuiteImportPage.tsx
+++ b/src/pages/workspace/accounting/netsuite/import/NetSuiteImportPage.tsx
@@ -23,7 +23,7 @@ function NetSuiteImportPage({policy}: WithPolicyConnectionsProps) {
     const {canUseNetSuiteUSATax} = usePermissions();
 
     const policyID = policy?.id ?? '-1';
-    const config = policy?.connections?.netsuite?.options.config;
+    const config = policy?.connections?.netsuite?.options?.config;
     const {subsidiaryList} = policy?.connections?.netsuite?.options?.data ?? {};
     const selectedSubsidiary = useMemo(() => (subsidiaryList ?? []).find((subsidiary) => subsidiary.internalID === config?.subsidiaryID), [subsidiaryList, config?.subsidiaryID]);
```

**Comment by NJ-2020** [comment] 2024-08-22 12:11
@CyberAndrii Thank you

**Comment by mollfpr** [comment] 2024-08-26 18:08
>One thing — I haven't found a consistent way to reproduce this with 100% certainty about my solution. It happens once in about 10 attempts. Maybe you have some ideas?

@CyberAndrii You can consistently reproduce it if you haven't created custom segments/records.

---

The [proposal](https://github.com/Expensify/App/issues/47501#issuecomment-2304178485) from @CyberAndrii looks good to me and working well!

🎀 👀 🎀 C+ reviewed!

**Comment by CyberAndrii** [comment] 2024-08-27 15:20
@mollfpr I didn't realize until now that my fix works in a browser and the desktop app, but not in the mobile app. I'm not sure why it behaves differently or how to fix it. The only difference I've noticed is that on mWeb clicking the "Confirm" button instantly opens the next page, while in the native app it plays a modal closing animation. Maybe the modal prevents the page behind it from re-rendering until the modal is closed?

<details>
<summary>mWeb iOS</summary>

https://github.com/user-attachments/assets/160cd697-6f43-4197-9b3f-6f425b3e7ce1
</details>

<details>
<summary>Native iOS</summary>

https://github.com/user-attachments/assets/b2ebb409-c241-499c-b182-4af2a23738fb
</details>

**Comment by mollfpr** [comment] 2024-08-29 17:35
Not overdue, Melv.

**Comment by CyberAndrii** [comment] 2024-09-16 17:11
The PR was deployed to production in https://github.com/Expensify/App/issues/48791. The payment is due **2024-09-18**.

**Comment by mollfpr** [comment] 2024-09-18 08:18
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR but I believe this issue is a race condition on transitioning the page and displaying the Onyx data. We fix the issue by replacing the deprecated `withOnyx` with the hook `useOnyx`.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

1. Open the app
2. Log in or create a new account
3. Open Account settings > Workspaces
4. Create a new workspace
5. Enable "Accounting" on the "More features" page
6. Navigate to "Accounting"
7. Connect to NetSuite and upgrade the workspace to Control when asked
8. Wait for the sync to finish
9. Navigate to Accounting - Import - Custom segments/records
10. Click on the "Add custom segment/record" button
11. Add a Custom record with any random data
12. Verify that the "Add custom segment or record" image did not appear after clicking the "Confirm" button on the last step
13. 👍 or 👎 

---

@puneetlath Could you create the payment summary? Thank you!

**Comment by puneetlath** [comment] 2024-09-21 22:46
@CyberAndrii can you provide me your Upwork profile? It doesn't look like you were hired for the job. 

Payment summary: 
- C - $250 - @CyberAndrii  - to be paid via Upwork
- C+ - 250 - @mollfpr - to be paid via NewDot

**Comment by CyberAndrii** [comment] 2024-09-22 02:32
@puneetlath https://www.upwork.com/freelancers/~01ca590af4f896abcb

It was a manual application https://github.com/Expensify/App/issues/47501#issuecomment-2310814232, but the job seems to have been closed a few days ago

**Comment by puneetlath** [comment] 2024-09-22 19:21
Ok I sent you a new offer here: https://www.upwork.com/nx/wm/offer/104079114. Please ping me on this issue when you've accepted.

**Comment by CyberAndrii** [comment] 2024-09-22 20:09
@puneetlath done

**Comment by puneetlath** [comment] 2024-09-22 20:15
Ok @CyberAndrii has been paid. @mollfpr please request on NewDot. Thanks everyone!

**Closed by puneetlath** 2024-09-22 20:15 UTC
Labels: Reviewing, External, Weekly, Bug
