### ISSUE TITLE
[HOLD for payment 2024-08-26][$250] Workspace – System message for changed workspace name is not translated to Spanish

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46219] opened 2024-07-25 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** gocemate+a706@gmail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45970
## Action Performed:
1. On an account with multiple policies in NewDOt, create an expense on one.
2. Log into OldDot and change the policy name
3. Back in NewDot verify that there's a message in #Admin that says "updated the workspace name from X to Y"
4. Go to Preferences> Change the language to Spanish
5. From OldDot Cchange the workspace name again
6. Go to admin room and check language on system message

## Expected Result:
The system message should be translated to Spanish

## Actual Result:
System message for changed workspace is not translated to Spanish. It appear on English even language is changed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/36a24a0e-8f72-45f2-82db-0ea26e5feb6a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cff222f969263a52</li>
        <li>Upwork Job ID: 1818044405838732218</li>
        <li>Last Price Increase: 2024-07-29</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103338869</li>
<li>FitseTLT | Contributor | 103338870</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-07-25 18:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace – System message for changed workspace name is not translated to Spanish

### What is the root cause of that problem?
We are not displaying the action `POLICYCHANGELOG_UPDATE_NAME` translating it but instead display the action with ReportItemActionMessage
### What changes do you think we should make in order to solve the problem?

We need to include a translation first for policy changed text that takes new and old name as a params then display it here by creating an else if for `POLICYCHANGELOG_UPDATE_NAME` by translating it 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/home/report/ReportActionItem.tsx#L655-L656

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-25 18:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace – System message for changed workspace name is not translated to Spanish

### What is the root cause of that problem?
We are not displaying the action `POLICYCHANGELOG_UPDATE_NAME` translating the message but instead display the action with `ReportActionItemMessage` which only displays the `message` fragments without translation
### What changes do you think we should make in order to solve the problem?

We need to include a translation first for policy changed text that takes new and old policy name as params then we will display the action here by creating an else if for `POLICYCHANGELOG_UPDATE_NAME` type action by translating it 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/home/report/ReportActionItem.tsx#L655-L656

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-07-25 18:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace – System message for changed workspace name is not translated to Spanish

### What is the root cause of that problem?
We are not displaying the action `POLICYCHANGELOG_UPDATE_NAME` translating the message but instead display the action with `ReportActionItemMessage` which only displays the `message` fragments without translation
### What changes do you think we should make in order to solve the problem?

We need to include a translation first for policy changed text that takes new and old policy name as params then we will display the action here by creating an else if for `POLICYCHANGELOG_UPDATE_NAME` type action and pass the translated text as the message of `ReportActionItemBasicMessage` 
https://github.com/Expensify/App/blob/b0f810df06c3df866b7fdbed4959f8f1fef803ed/src/pages/home/report/ReportActionItem.tsx#L655-L656

We can of course create  a util that returns the translated text. And also we can apply the same for other type of actions too that do not support translation yet.
### What alternative solutions did you explore? (Optional)

**Comment by robertjchen** [comment] 2024-07-31 10:24
Thanks for the proposals and review. Let's go with @FitseTLT 's 👍

**Comment by FitseTLT** [comment] 2024-08-01 21:26
@johncschuster I need a copy for 
`updated the name of this workspace from ${oldName} to ${newName}`

**Comment by FitseTLT** [comment] 2024-08-02 19:08
@johncschuster or @robertjchen Can you add the `Need a Copy` label? Thx

**Comment by FitseTLT** [comment] 2024-08-06 14:44
@danielrvidal Can you pls give us the translation of [this](https://github.com/Expensify/App/issues/46219#issuecomment-2264036971)? Thx.

**Comment by FitseTLT** [comment] 2024-08-06 19:11
@danielrvidal Can you pls give us the translation of [this](https://github.com/Expensify/App/issues/46219#issuecomment-2264036971)? Thx.

**Comment by johncschuster** [comment] 2024-08-06 20:41
Just bumped @danielrvidal in DM 👍

**Comment by danielrvidal** [comment] 2024-08-06 21:15
For our internal team, I'm confirming the translation here: https://expensify.slack.com/archives/C21FRDWCV/p1722978885798709

**Comment by johncschuster** [comment] 2024-08-06 21:38
Thanks @danielrvidal!

**Comment by danielrvidal** [comment] 2024-08-06 23:54
Here you are @FitseTLT 

> actualizó el nombre de este espacio de trabajo de “${oldName}” a “${newName}”

Let me know if you have any questions.

**Comment by johncschuster** [comment] 2024-08-09 21:36
Awesome. Thanks, @danielrvidal!

**Comment by robertjchen** [comment] 2024-08-16 18:32
Just some conflicts to be resolved on the PR and I can merge 👍

**Comment by robertjchen** [comment] 2024-08-19 16:12
Merged and on the way out!

**Comment by robertjchen** [comment] 2024-08-23 15:42
On prod

**Comment by robertjchen** [comment] 2024-08-27 20:51
@johncschuster could you please help with the next steps here? Thanks!

**Comment by suneox** [comment] 2024-09-03 17:21
This issue has been deployed to production 2 weeks ago. We're waiting for payment

**Comment by johncschuster** [comment] 2024-09-03 21:19
Sorry about that! I process my "Hold for payment" issues every morning (by way of filtering specifically for those issue titles), and I missed this since the automation didn't seem to change the title. I'll get this sorted!

**Comment by johncschuster** [comment] 2024-09-03 21:24
# Payment Summary:

Contributor: @FitseTLT paid $250 via [Upwork](https://www.upwork.com/offer/103803793)
Contributor+: @suneox owed $250 via [Upwork](https://www.upwork.com/offer/103803805)

**Comment by johncschuster** [comment] 2024-09-03 21:25
(I've updated the title to make sure I see this when I action my payment issues in the morning)

**Comment by suneox** [comment] 2024-09-04 01:36
@johncschuster I've accepted the offer

**Comment by FitseTLT** [comment] 2024-09-04 10:41
@johncschuster There is already an [offer](https://github.com/Expensify/App/issues/46219#issuecomment-2260184248) that I have already accepted.

**Comment by johncschuster** [comment] 2024-09-04 15:00
I've issued payment! Thank you both for your contributions! 🎉

**Comment by robertjchen** [comment] 2024-09-04 17:10
thanks!

**Closed by robertjchen** 2024-09-04 17:10 UTC
Labels: External, Daily, Awaiting Payment, Bug
