### ISSUE TITLE
[HOLD for payment 2023-08-10] [$250] Migrate index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16176] opened 2023-03-20 08:39 UTC
### Filenames
- [ ] [src/components/Modal/index.js](https://github.com/Expensify/App/blob/main/src/components/Modal/index.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171f2a01c70848034</li>
        <li>Upwork Job ID: 1682085982094520320</li>
        <li>Last Price Increase: 2023-07-20</li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:57
I'd like to work on this issue

**Comment by s-alves10** [comment] 2023-06-06 10:28
I'd love to work on this.

**Comment by vdem0115** [comment] 2023-07-06 04:15
I can work on this issue.

**Comment by olexyt** [comment] 2023-07-07 13:53
I can work on this issue.

**Comment by mkhutornyi** [comment] 2023-07-12 03:01
I'd like to work on this.

**Comment by alexxxwork** [comment] 2023-07-20 17:53
I would love to work on this issue

**Comment by reinesarchisorte** [comment] 2023-07-20 17:54
I would like to work on this.

**Comment by himanshuragi456** [comment] 2023-07-20 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate index.js to function component

### What is the root cause of that problem?
It is a class-based component

### What changes do you think we should make in order to solve the problem?
I will make it a functional component

**Comment by devanshu-josh** [comment] 2023-07-20 17:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate index.js to function component

### What is the root cause of that problem?
It is a class-based component

### What changes do you think we should make in order to solve the problem?
I will make it a functional component, making all the necessary changes

**Comment by devanshu-josh** [comment] 2023-07-20 17:59
Contributor details
Your Expensify account email: devanshuragi456@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ef33f7f0e3767c59

**Comment by vadymbokatov** [comment] 2023-07-20 18:00
I can work on this issue

**Comment by mollfpr** [comment] 2023-07-20 18:02
@kosmydel from SWM will work on this issue.

**Comment by himanshuragi456** [comment] 2023-07-20 18:06
why is it assigned to @kosmydel? Contributing guidelines say that first person to send a Proposal in proper template should get assigned.

**Comment by mollfpr** [comment] 2023-07-20 18:11
>No proposals are necessary. If you want to work on an issue make sure that it is off HOLD and has the External + Help Wanted label applied. The first to leave a comment after the issue is taken off HOLD will most likely get assigned to the issue, but Expensify will use our discretion here in case there is someone we’d rather have the migration done by due to experience, overlap with another project, etc.

https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119

**Comment by himanshuragi456** [comment] 2023-07-20 23:58
> > No proposals are necessary. If you want to work on an issue make sure that it is off HOLD and has the External + Help Wanted label applied. The first to leave a comment after the issue is taken off HOLD will most likely get assigned to the issue, but Expensify will use our discretion here in case there is someone we’d rather have the migration done by due to experience, overlap with another project, etc.
> 
> https://expensify.slack.com/archives/C01GTK53T8Q/p1685727880152119

and this applies to only $250 tasks or all tasks?

**Comment by mollfpr** [comment] 2023-07-21 03:58
@himanshuragi456 I believe the above rule is for React class component migration. The other issues will still be based on the CONTRIBUTING doc.

Another context regarding the class component migration https://expensify.slack.com/archives/C01GTK53T8Q/p1685739036649559?thread_ts=1685727883.004839&cid=C01GTK53T8Q

**Comment by devanshu-josh** [comment] 2023-07-21 10:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

"Close" tooltip stays visible for a moment after modal closes on Profile Image.

### What is the root cause of that problem?

The issue arises from the fact that animations, such as fading effects when unmounting, don't remove components from the DOM instantly. As a result, the tooltip associated with the close button persists for a fraction of a second after the modal has closed.

### What changes do you think we should make in order to solve the problem?

We may propose an effective solution to automatically hide the Tooltip when its target element disappears. By detecting modal visibility and introducing trigger actions (hideTooltip()) for the Tooltip, we can ensure a seamless and user-friendly experience.
In this case, we can handle all modal tooltips including this issue.

https://github.com/Expensify/App/blob/7fea760c2bb7556815aaca2d61861bd1cf39d6b1/src/components/Tooltip/index.js#L18-L21

### What alternative solutions did you explore? (Optional)

Exploring

**Comment by kosmydel** [comment] 2023-07-21 10:38
This component apparently is not used anywhere, because it has implementations specific for each platform:
- iOS has `index.ios.js`,
- Android has `index.android.js`
- web/desktop/mWeb has: `index.web.js`.

Please correct me if I am wrong.

I've created [a thread on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1689935585941709).

**Comment by rk111** [comment] 2023-07-21 12:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Migrate index.js to function component 

### What is the root cause of that problem?
To convert the class based component into a functional component.
### What changes do you think we should make in order to solve the problem?
We can make use of the React Hooks API. Specifically, we need to use the useEffect hook to handle the lifecycle methods and useRef hook to create the baseModalRef reference.

**Comment by rk111** [comment] 2023-07-21 12:50
Contributor details
Your Expensify account email: <mrrightrk111@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01e970825478398245>

**Comment by rk111** [comment] 2023-07-21 12:51
Contributor details
Your Expensify account email: mrrightrk111@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e970825478398245

**Comment by rk111** [comment] 2023-07-21 20:19
I want to work on this issue.

**Comment by marcaaron** [comment] 2023-07-21 21:08
>This component apparently is not used anywhere, because it has implementations specific for each platform:

@kosmydel I think you might be right there. `web.js` should cover desktop and web. Let's just delete it then and make sure everything builds OK (it should).

**Comment by michaelhaxhiu** [comment] 2023-07-24 12:51
PR is in progress, adding this comment to clear the `Overdue` label for 24 hours

**Comment by michaelhaxhiu** [comment] 2023-08-03 21:18
Note: I'm preparing to go OOO for ~2 weeks, and need a buddy to oversee this while I'm gone so that payment gets sent on time. Thanks in advance for your help.

**Comment by michaelhaxhiu** [comment] 2023-08-03 21:18
@kevinksullivan this is a $250 job whereby we just pay 1 person (@kosmydel) and then it can be closed.

**Comment by kevinksullivan** [comment] 2023-08-04 21:19
I am also going OOO for next week and taking a similar approach as @michaelhaxhiu here...

**Comment by kevinksullivan** [comment] 2023-08-04 21:20
@Christinadobrzyn tapping you in here since I will be OOO next week. Thanks!

**Comment by Christinadobrzyn** [comment] 2023-08-07 21:28
Does this need a regression test @mollfpr?

**Comment by mollfpr** [comment] 2023-08-11 04:33
Sorry for the delay 🙏 @Christinadobrzyn We don't need one.

**Comment by Christinadobrzyn** [comment] 2023-08-11 17:57
Payouts due:

Issue Reporter: NA
Contributor: NA
Contributor+: $250 @mollfpr 

Eligible for 50% #urgency bonus? NO

Upwork job is [here](https://www.upwork.com/jobs/~0171f2a01c70848034)
Internal job- https://www.upwork.com/ab/applicants/1682085982094520320/job-details

@mollfpr if you want to accept the offer I'll pay you out for this one!

**Comment by Christinadobrzyn** [comment] 2023-08-14 23:11
Paid @mollfpr in Upwork
Closed the job in Upwork
Closing this GH

**Closed by Christinadobrzyn** 2023-08-14 23:11 UTC
Labels: External, Engineering, Daily, NewFeature, Overdue, Awaiting Payment, Bug
