### ISSUE TITLE
[HOLD #17387] [$1000] Sending or requesting money to an invalid email resulted in irremovable report

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20105] opened 2023-06-02 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open staging.new.expensify.com
2. Do a send (or request) money
3. Set the recipient to an invalid email (ex. "__@__.com")
4. Execute the send (or request) money command and examine what happened on the chat report and LHN
## Expected Result: 
The problematic report should be able to be removed from the LHN, just like when a report for an invalid email created from "New Chat" that can be removed
## Actual Result: 
The report generated can't be removed from the chat report and LHN, causing the invalid report to stay on the LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/82abe0ae-17d9-4f59-b49b-29e92a061568

https://github.com/Expensify/App/assets/43996225/83698492-6612-4ac2-a81e-87b785c3b042

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685624383460229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5663d8563d288dc</li>
        <li>Upwork Job ID: 1665699860255768576</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by abekkala** [comment] 2023-06-05 12:40
I was able to recreate this and I _believe_ it would make sense to allow it to be removed from LHN similar to creating a new chat with an invalid email

**Comment by eh2077** [comment] 2023-06-06 03:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Sending or requesting money to an invalid email resulted in irremovable report

### What is the root cause of that problem?

The root cause of this issue is that the backend doesn't return complete `onyxData` data to support error handling from frontend.

<img width="800" alt="Screenshot 2023-06-06 at 10 27 49 AM" src="https://github.com/Expensify/App/assets/117511920/b3a6a2ea-d366-4e40-afa6-a977521cf10a">

```json
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Error\\Email\\InvalidEmail",
    "UUID": "a9444a52-b2b2-491a-a0a3-3c56c6a16c09",
    "message": "__@__.com - is not a valid email address",
    "title": "",
    "data": {
        "emailAddress": "__@__.com"
    },
    "htmlMessage": "",
    "onyxData": [],
    "requestID": "7d2d34dae8ce40b6-SIN"
}
```

So the frontend just keeps try issuing fetch report API.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we should have a backend fix to let send money APIs

https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/actions/IOU.js#L1112

https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/actions/IOU.js#L1128

https://github.com/Expensify/App/blob/936a3a773cead07916e3a2303e880cf56d8453aa/src/libs/actions/IOU.js#L1144

 return `onyxData` data when the email is invalid to support error handling on frontend.

The backend should return `onyxData` data like when we try to chat with an invalid email account, for example

```json
{
    "code": 666,
    "jsonCode": 666,
    "type": "Expensify\\Error\\Email\\InvalidEmail",
    "UUID": "a9444a52-b2b2-491a-a0a3-3c56c6a16c09",
    "message": "__@_.com - is not a valid email address",
    "title": "",
    "data": {
        "emailAddress": "__@_.com",
        "onyxData": [
            {
                "onyxMethod": "merge",
                "key": "report_8484099831331605",
                "value": {
                    "errorFields": {
                        "createChat": {
                            "1686019291926459": "__@_.com - is not a valid email address"
                        }
                    }
                }
            }
        ]
    },
    "htmlMessage": "",
    "onyxData": [
        {
            "onyxMethod": "merge",
            "key": "report_8484099831331605",
            "value": {
                "errorFields": {
                    "createChat": {
                        "1686019291926459": "__@_.com - is not a valid email address"
                    }
                }
            }
        }
    ],
    "requestID": "7d2d4bfdce5040b6-LAX"
}
```

Then the `onyxData` report data won't be empty and won't keep issuing fetch report requests. 

I think the current frontend should be able to handle the `invalid email address` error just like it does for chat once we have backend fix to return `onyxData` report data. We can double check it again after we have backend fix ready.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by abekkala** [comment] 2023-06-08 11:59
@youssef-lr do you agree that this should behave similarly and allow it to be removed from LHN similar to creating a new chat with an invalid email?

If so, 
@sobitneupane what is your thought on the proposal that came in?

**Comment by youssef-lr** [comment] 2023-06-12 11:47
Agreed @sobitneupane, I'll work on the backend fix.

**Comment by abekkala** [comment] 2023-06-14 15:53
@youssef-lr do you want me to change this to `Internal`?

**Comment by abekkala** [comment] 2023-06-19 13:07
Changed this to Internal as @youssef-lr is working on this

**Comment by youssef-lr** [comment] 2023-06-21 19:58
Gonna get to this tomorrow.

**Comment by youssef-lr** [comment] 2023-06-26 10:38
Working on a fix either today or tomorrow.

**Comment by youssef-lr** [comment] 2023-06-30 21:01
On second thought here, I just noticed that our `Str.isValidEmail` is actually returning `true` for `___@__.com` which is wroen, I tested a different [regex](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address) from the HTML spec and it works properly. However, changing the regex in https://github.com/Expensify/expensify-common resulted in some mentions tests failing. So I think we actually need to fix this in the frontend, we shouldn't be creating optimistically account and display it in the search result if the email is not valid. Can we explore fixing the regex without breaking any tests?

**Comment by youssef-lr** [comment] 2023-06-30 21:09
Thanks @aimane-chnaif! Yeah looks like we can put this on hold. Regardless, an email thrown from the backend should not result in a non-removable report so I will still proceed with a backend fix for future proofing.

**Comment by youssef-lr** [comment] 2023-07-03 16:20
Moving to weekly based on HOLD.

**Comment by sophiepintoraetz** [comment] 2023-07-12 11:33
Still holding.

**Comment by sophiepintoraetz** [comment] 2023-07-21 04:31
Holding!

**Comment by youssef-lr** [comment] 2023-07-31 11:57
Still on hold!

**Comment by sophiepintoraetz** [comment] 2023-08-09 05:04
Still holding

**Comment by sophiepintoraetz** [comment] 2023-08-21 20:06
Still holding.

**Comment by youssef-lr** [comment] 2023-08-30 21:17
The PR this issue was held on is live on staging, let's wait for it to hit production then we can remove the hold and re-test.

**Comment by sophiepintoraetz** [comment] 2023-09-05 02:51
It's hit production and we no longer have a send function. Additionally, we come up with an error for invalid emails so I'm closing this issue out!
![2023-09-05_14-50-42 (1)](https://github.com/Expensify/App/assets/42940078/7de8741a-9579-4214-a8ec-b875a0674f57)

**Closed by sophiepintoraetz** 2023-09-05 02:51 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by kerupuksambel** [comment] 2023-09-05 03:06
@sophiepintoraetz Apologies for upping this issue, but given the issue is reported by the external reporter, are there any compensation for the issue reporter? Thanks beforehand.

**Comment by sophiepintoraetz** [comment] 2023-09-05 03:14
@kerupuksambel - thanks for checking in but not in this case. There wasn't a clear identifiable fix and we also changed the product so that this bug was rendered obsolete.

**Comment by sophiepintoraetz** [comment] 2023-09-14 01:02
@kerupuksambel that was before [we changed the functionality](https://github.com/Expensify/App/issues/20105#issuecomment-1705875604). I appreciate it's disappointing but we cannot reimburse for a bug report that no longer exists in today's product. You are welcome to keep contributing!
