### ISSUE TITLE
[$250] IOU-Duplicate waypoints occur if delete the waypoint via Troubleshoot-Force Offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41086] opened 2024-04-26 11:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.66-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Create a distance request with 3 or more waypoints
2. Navigate to the distance expense details conversation
3. Disable the internet connection via Troubleshoot-Force Offline
4. Select the the distance item
5. Verify you’re navigated to a page to edit the waypoints of the route
6. Verify the waypoints you initially input are already set
7. Remove any stop from the route via selecting it and deleting
8. Save the change
9. Go back online
10. Select the the distance item and verify duplicate waypoints
11. Click on the mini map to see the distance receipt and verify duplicate waypoints

## Expected Result:
Deleted waypoint should vanish

## Actual Result:
Two same waypoints appear after getting online if user deletes any of the waypoints via Troubleshoot-Force Offline
Note: The issue does not occur if internet connection is turned off via computer/router.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0ce65153-f434-4580-9267-71dbd091c571

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137e06a0e9b33107e</li>
        <li>Upwork Job ID: 1784774224953176064</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-26 11:13
We think this issue might be related to the #collect project.

**Comment by adelekennedy** [comment] 2024-04-26 17:20
@izarutskaya can you explain Troubleshoot-Force Offline? does this mimic a real world condition a user would encounter?

**Comment by adelekennedy** [comment] 2024-04-29 02:38
reproducible - moving it to wave collect for distance

**Comment by jsdev2547** [comment] 2024-04-29 10:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last waypoint is duplicated when three waypoints are entered and the second waypoint removed.

### What is the root cause of that problem?
In IOURequestStepDistance,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L354

the transaction object is passed but the original transaction is stored in transactionbackup.

### What changes do you think we should make in order to solve the problem?
In updatWayPoints callback,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L354

pass transactionBackup instead of transaction, also the dependency array should use transactionBackup instead of transaction.
```
TransactionAction.removeWaypoint(transactionBackup, emptyWaypointIndex.toString(), action === CONST.IOU.ACTION.CREATE),
```

```
[transactionID, transactionBackup, waypoints, waypointsList, action],
```


### What alternative solutions did you explore? (Optional)

**Comment by jsdev2547** [comment] 2024-04-29 10:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The last waypoint is duplicated when three waypoints are entered and the second waypoint removed.

### What is the root cause of that problem?
In IOURequestStepDistance,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L354

the transaction object is passed but the original transaction is stored in transactionbackup.

### What changes do you think we should make in order to solve the problem?
In updateWayPoints callback,
https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/pages/iou/request/step/IOURequestStepDistance.tsx#L354

pass transactionBackup instead of transaction, also the dependency array should use transactionBackup instead of transaction.
```
TransactionAction.removeWaypoint(transactionBackup, emptyWaypointIndex.toString(), action === CONST.IOU.ACTION.CREATE),
```

```
[transactionID, transactionBackup, waypoints, waypointsList, action],
```


### What alternative solutions did you explore? (Optional)

**Comment by adelekennedy** [comment] 2024-05-06 17:05
no takers but this is a `polish` issue

**Comment by adelekennedy** [comment] 2024-05-08 19:25
still waiting

**Comment by adelekennedy** [comment] 2024-05-10 18:40
I'm not going to increase the price on this one as it's pretty edge case-y

**Comment by MrMuzyk** [comment] 2024-05-13 09:58
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

**Comment by MrMuzyk** [comment] 2024-05-14 09:27
I believe the issue is somewhere inside `react-native-onyx` and I will explain why is that below. First I wanted to add that @rezkiy37 is debugging [issue](https://github.com/Expensify/App/issues/41284) that is similar to this one and root cause might be the same - onyx returning incorrect data. It might be a tricky one to fix, I dont have a solution yet and it would have to be in `react-native-onyx`. I will investigate this more and see if I can come up with some kind of fix for this.

Here are my findings:

I've added a couple of logs inside component displaying waypoints

<img width="937" alt="Screenshot 2024-05-14 at 11 09 58" src="https://github.com/Expensify/App/assets/23487612/7cab99b2-da00-4bcc-b6f7-7a1351b87706">

---
Next I've reproduced the issue step by step. On the first screenshot IOU is stored correctly inside OnyxDB.

<img width="1920" alt="1" src="https://github.com/Expensify/App/assets/23487612/a8590917-f99f-4bda-a177-0aaf6b186f5e">

---

I've went offline and opened the receipt. We can see in the console that it logged 2 waypoints correctly as it should which are later on passed to proper component that display them 

<img width="1920" alt="2" src="https://github.com/Expensify/App/assets/23487612/f557f0d1-d252-4fe4-84e8-84f86a28c269">

---
I've checked OnyxDB and receipt was stored correctly there

<img width="1920" alt="3" src="https://github.com/Expensify/App/assets/23487612/50d1643e-0667-4b69-8f35-dac6a9ed6283">

---

After that I've removed one waypoint, saved it and went back online. We can see in the console that component received via props a transaction that had 3 waypoints in it - one was duplicated. This console.log happens straight away after receiving waypoints from props. They're not modified in any way before they're passed to component - this is data straight out of Onyx.

<img width="1920" alt="4" src="https://github.com/Expensify/App/assets/23487612/ee6ba5e1-f5db-474e-b707-ea0a379de3f1">

---

However when we look inside OnyxDB we can see that data stored there is correct - it has only 2 waypoints. I believe that the issue has to be somewhere inside onyx because this is the only place where this data could be modified during process of extracting it from OnyxDB and passing it component.

<img width="1920" alt="5" src="https://github.com/Expensify/App/assets/23487612/0040d516-a232-4699-823e-c9e5e38e1578">

---

I'd like to also point out that the issue doesn't exist after page refresh - it's just a one time thing after turning off offline mode in the app. I also wasn't able to reproduce that issue when disabling internet connection via devtools or disabling/enabling directly wifi on my machine

**Comment by adelekennedy** [comment] 2024-05-14 15:32
@MrMuzyk 
>I'd like to also point out that the issue doesn't exist after page refresh - it's just a one time thing after turning off offline mode in the app. I also wasn't able to reproduce that issue when disabling internet connection via devtools or disabling/enabling directly wifi on my machine

In this case this doesn't seem worth it to me to keep this issue open, unless I'm missing something a "real" user wouldn't actually experience this?

**Comment by MrMuzyk** [comment] 2024-05-14 16:08
It shouldn't. Here is recording where I'm not able to reproduce the same behaviour while turning of wifi on my laptop

https://github.com/Expensify/App/assets/23487612/c4a1b786-2d0a-4398-9db0-61a58191bef1

**Comment by izarutskaya** [comment] 2024-07-11 11:41
Issue is still reproducible on iOS and Android App
build 9.0.6-0

https://github.com/Expensify/App/assets/115492554/d684055f-c519-4b66-83cc-14b3196904d0

**Comment by izarutskaya** [comment] 2024-07-31 13:38
Let me try please

**Comment by izarutskaya** [comment] 2024-07-31 15:46
It is reproducible by disabling the internet on device

https://github.com/user-attachments/assets/d3bf69ac-313a-436b-8a0d-8870b455d54b

**Comment by MrMuzyk** [comment] 2024-08-01 07:06
@parasharrajat I can look into it again but as my original comment with explanation stated - I believe that issue has to be on the Onyx side. Data that we're getting is coming straight from the Onyx and yet it's incorrect.

**Comment by MrMuzyk** [comment] 2024-08-01 09:19
I've tried again to reproduce that on web and couldn't get the same result - it's working fine on web. Sadly I do not have real mobile device to try to reproduce that.

https://github.com/user-attachments/assets/d5635752-4c05-45a5-bc09-97d6ec579c0a

**Comment by mvtglobally** [comment] 2024-08-03 04:08
Issue not reproducible during KI retests. (First week)

**Comment by adelekennedy** [comment] 2024-08-08 16:24
It seems like we can close this out (I also can't reproduce either)

**Closed by adelekennedy** 2024-08-08 16:24 UTC
Labels: External, Weekly, Help Wanted, Bug
