### ISSUE TITLE
[Hold for Payment] [$1000] mWeb- Compose-Adding hyphen in url, although invalid shown as link and editing shows different forma

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27080] opened 2023-09-09 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap any report
3. Enter -77.com
4. Send the message
5. Long press the sent message
6. Tap edit comment
7. Enter -[77.com](https://77-.com/
) [slash add before dot com]
8. Tap tick
9. Long press the message
10. Tap edit comment

## Expected Result:
When user sends -[77.com](https://77-.com/
), then edits this comment, it must be displayed in same format
-[77.com](https://77-.com/
)

## Actual Result:
When user sends -[77.com](https://77-.com/
) , it is shown as link. And when user edit this comment, it is displayed in different format -77.com

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/4fa45646-6a4d-487d-9b8b-3f7d34dfc6fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:**@

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185d689f506bdc532</li>
        <li>Upwork Job ID: 1701603965592113152</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-09-12 14:29
Applying `External`

**Comment by greg-schroeder** [comment] 2023-09-18 10:41
awaiting proposal review

**Comment by greg-schroeder** [comment] 2023-09-25 07:32
Any chance you're able to take a look @allroundexperts? Thanks!

**Comment by greg-schroeder** [comment] 2023-10-02 15:10
I actually agree. I think the initial part saying it shouldn't be sent as a link isn't correct, so I edited the OP

**Comment by greg-schroeder** [comment] 2023-10-06 07:17
Still waiting for proposals, might see if CS or SWM want to take a stab

**Comment by greg-schroeder** [comment] 2023-10-10 16:27
Will double bounty soon

**Comment by greg-schroeder** [comment] 2023-10-13 19:13
Did the thing

**Comment by byte1012** [comment] 2023-10-16 07:32
# Proposal
### Please re-state the problem that we are trying to solve in this issue.
Compose-Adding hyphen in url, although invalid shown as link and editing shows different format.

### What is the root cause of that problem?
Currently frontend app is allowing incorrect values in Url, but backend does not, so inconsistency is there when editing the chat composer. The main cause of it is that [LOOSE_URL_WEBSITE_REGEX](https://github.com/Expensify/expensify-common/blob/7735de14112a968fd6a4f5af710d2fbaefc8809d/lib/Url.js#L14C4-L14C4) is allowing starting & ending hyphen, but it's not allowed [RFC1034](https://datatracker.ietf.org/doc/html/rfc1034),
also currently it allows underscore(_) , it's out of scope for this issue, but we should handle it as well to parse url correctly.

### What changes do you think we should make in order to solve the problem?
To fix the root cause, we should fix to block starting and ending with hyphen and underscore on LOOSE_URL_WEBSITE_REGEX.
after fix, will be as following: 
```
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}([a-z0-9](?:[-a-z0-9]*[a-z0-9])?\\.)*(?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?)(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```
To shorten the regex pattern, we can export `[a-z0-9](?:[-a-z0-9]*[a-z0-9])?` as a variable.
```
const DOMAIN_REGEX = '[a-z0-9](?:[-a-z0-9]*[a-z0-9])?'
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}(${DOMAIN_REGEX}\\.)*(?:${DOMAIN_REGEX})(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;

```
It's tested with auto test cases and does not effect other cases.

**Comment by byte1012** [comment] 2023-10-16 07:35
@allroundexperts could you check my proposal ?

**Comment by greg-schroeder** [comment] 2023-10-16 14:46
Pending proposal review

**Comment by greg-schroeder** [comment] 2023-10-19 00:41
bump @allroundexperts when you're able :)

**Comment by greg-schroeder** [comment] 2023-10-23 10:20
Bump!

**Comment by greg-schroeder** [comment] 2023-10-26 00:04
Reached out in Slack

**Comment by byte1012** [comment] 2023-10-30 03:56
@allroundexperts please check video

before:

https://github.com/Expensify/App/assets/86615752/a80c3a4f-0936-4911-8c56-1b92df6140ec

after:

https://github.com/Expensify/App/assets/86615752/f9bd641f-864a-4bcf-9d03-7055aa05fbda

**Comment by greg-schroeder** [comment] 2023-11-02 18:11
Waiting for proposal review

**Comment by chiragsalian** [comment] 2023-11-07 23:28
@byte1012 can you give explain and give me examples of what this matches?
```
const DOMAIN_REGEX = '[a-z0-9](?:[-a-z0-9]*[a-z0-9])?'
```
I think of a domain as `google.com` or `apple.com`
but your regex would match something like `1234` right? 

I would think of a domain regex as,
```
[a-zA-Z\d\.-]+\.[a-zA-Z]{2,}
```
would this regex work too?

Let me know.

**Comment by chiragsalian** [comment] 2023-11-07 23:37
In the suggestion
```
const DOMAIN_REGEX = '[a-z0-9](?:[-a-z0-9]*[a-z0-9])?'
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}(${DOMAIN_REGEX}\\.)*(?:${DOMAIN_REGEX})(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```
I think i get why you use `[a-z0-9](?:[-a-z0-9]*[a-z0-9])?`. It looks similar to what we have in `URL_WEBSITE_REGEX` but there we check for `www` and end with `TLD_REGEX` so having `[a-z0-9](?:[-a-z0-9]*[a-z0-9])?` makes more sense to me there.

In your suggestion i don't think we should use the variable `DOMAIN_REGEX` because that regex doesn't really match domains. Also can you elaborate this bit `*(?:${DOMAIN_REGEX})` in your suggestion. Why is it not using `TLD_REGEX` instead? (P.S I haven't looked deeply into the usages of these regex)

**Comment by byte1012** [comment] 2023-11-08 09:12
@chiragsalian 
LOOSE_URL_WEBSITE_REGEX is for parsing localhost-style URLS, which is with a protocol, regardless of TLD presence
https://localhost
http://my.localhost.local-host

URL_WEBSITE_REGEX is to parse url with TLD, regardless of Protocol
http://example.com
example.com

**Comment by byte1012** [comment] 2023-11-08 11:50
> const DOMAIN_REGEX = '[a-z0-9](?:[-a-z0-9]*[a-z0-9])?'

It refers to a domain label. e.g. example in https://test.example.com
I suggest you to check LOOSE_URL_WEBSITE regex more carefully

**Comment by chiragsalian** [comment] 2023-11-08 20:19
> LOOSE_URL_WEBSITE_REGEX is for parsing localhost-style URLS, which is with a protocol, regardless of TLD presence

oh neat. okay it makes sense that it does not need TLD presence.

I'm not a fan of DOMAIN_REGEX variable and prefer this solution by you,
```
const LOOSE_URL_WEBSITE_REGEX = `${URL_PROTOCOL_REGEX}([a-z0-9](?:[-a-z0-9]*[a-z0-9])?\\.)*(?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?)(?:\\:${ALLOWED_PORTS}|\\b|(?=_))`;
```
This is because that regex matches `testsomething` or even `123456789` which is not a domain. So I'm afraid someone would see `DOMAIN_REGEX` and think it matches only domains when in reality it does not so the variable name feels incorrect to me.

Feel free to create the PR @byte1012. Also let me know if you disagree with my suggestion.

**Comment by byte1012** [comment] 2023-11-09 07:34
@greg-schroeder @chiragsalian @allroundexperts 
The PR https://github.com/Expensify/expensify-common/pull/598 for expensify-common repo is ready

**Comment by greg-schroeder** [comment] 2023-11-13 09:32
merged, awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2023-11-13 09:43
@allroundexperts ... I ... do not know. I didn't actually look at the PR, I just saw it was merged 😅 

That is not correct

**Comment by greg-schroeder** [comment] 2023-11-13 09:44
@lakchote can you explain what's going on here per Sibtain's question above?

**Comment by lakchote** [comment] 2023-11-13 10:16
@greg-schroeder The PR was wrongfully assigned to only me. It should has been assigned to @allroundexperts.

Sorry Sibtain, didn't mean to do harm. 

Next time, I won't merge but approve just in case, to prevent these kind of scenarios. And I'll double check if the C+ has been correctly assigned.

**Comment by greg-schroeder** [comment] 2023-11-14 16:47
@allroundexperts should we still do the review/checklist? I know it was merged already but I think it might be a good idea

**Comment by byte1012** [comment] 2023-11-15 08:46
@greg-schroeder @allroundexperts 
The App PR https://github.com/Expensify/App/pull/31346 is ready

**Comment by greg-schroeder** [comment] 2023-11-26 20:06
Looks like this was deployed to prod 5 days ago, not sure what's up with the automation 🤔

**Comment by greg-schroeder** [comment] 2023-11-26 20:07
Although this one wasn't deployed at all afaict: https://github.com/Expensify/expensify-common/pull/598

This one is weird because of the unusual merging/review situation - can anyone help confirm what's left before this can be considered finished up?

**Comment by allroundexperts** [comment] 2023-11-26 20:09
@greg-schroeder https://github.com/Expensify/expensify-common/pull/598 doesn't need to be deployed as its just a package. The second PR actually applied the changes of the first PR into our App. This is finished already.

**Comment by byte1012** [comment] 2023-12-01 00:57
@greg-schroeder @allroundexperts 
It's been more than a week since deployed to staging app.
Looks like there is no other regression.
How can we move forward

**Comment by greg-schroeder** [comment] 2023-12-19 01:35
Okay sorry for the delay on this one, there's no automation at all so my filters keep ignoring this issue. Let me go through and figure out what's left to do here so we can close it.

**Comment by greg-schroeder** [comment] 2023-12-19 01:40
PR 1: https://github.com/Expensify/App/pull/31346
PR 2: https://github.com/Expensify/expensify-common/pull/598

Reporter: QA / NA
Contributor was @byte1012
C+ was @allroundexperts 

So this was eventually upgraded to $1k, so I will send a manual offer to @byte1012 for this one. Sibtain you can make a manual request for $1k for the reviewer role.

**Comment by greg-schroeder** [comment] 2023-12-19 01:55
@byte1012 can you follow the steps [here](https://github.com/Expensify/App/issues/27080#issuecomment-1763892282) so I can pay you? Thanks!

**Comment by greg-schroeder** [comment] 2023-12-19 01:57
You could also apply for the job I made here: https://www.upwork.com/ab/applicants/1736927955655499776/job-details

**Comment by allroundexperts** [comment] 2023-12-19 12:15
## Checklist

1. https://github.com/Expensify/expensify-common/pull/535/
2. https://github.com/Expensify/expensify-common/pull/535/files#r1431325869
3. N/A
4. A regression test would be overkill in this case since we've covered this particular case in the unit tests pretty comprehensively.

**Comment by greg-schroeder** [comment] 2023-12-20 00:37
Thanks!

**Comment by greg-schroeder** [comment] 2023-12-21 22:32
Bump @byte1012

**Comment by greg-schroeder** [comment] 2023-12-22 18:41
Trying to get this contributor's details: https://github.com/Expensify/App/issues/26941#issuecomment-1867978086

**Comment by byte1012** [comment] 2023-12-25 06:46
Contributor details
Your Expensify account email: kelleyaquilino@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f484b51cfedb480a

**Comment by byte1012** [comment] 2023-12-25 06:48
@greg-schroeder done. sorry about delay. I missed this issue for a while

**Comment by byte1012** [comment] 2023-12-25 09:03
@greg-schroeder could you send me an offer on upwork ?

**Comment by greg-schroeder** [comment] 2023-12-31 10:28
@byte1012 offer sent

**Comment by greg-schroeder** [comment] 2024-01-03 18:36
Once you're able to accept we'll close this out!

**Comment by greg-schroeder** [comment] 2024-01-06 00:31
Paid!

**Closed by greg-schroeder** 2024-01-06 00:31 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-24 23:52
$1,000 payment to @allroundexperts based on [this comment](https://github.com/Expensify/App/issues/27080#issuecomment-1861963679).
