### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Chat - Quote with strike through markdown, vertical line displays big & "edited" not shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28169] opened 2023-09-25 16:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap on a report
3. Enter >*××××* and send it
4. Long press the sent message and tap edit comment
5. Enter >_××××_ and send it
6. Long press the sent message and tap edit comment
7. Enter >~××××~ and send it

## Expected Result:
When user edit comment and send quote message with strike through markdown, the vertical line must not display big and "edited" status of message must be shown

## Actual Result:
When user send quote message with bold markdown, it is correctly applied. When user edited comment and send quote message with italic markdown, it is displayed correctly with " Edited " status. But when user edit comment and send quote message with strike through markdown, the vertical line displays big and "edited" status of message is not shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/9b587423-e9d1-4ca6-a7bd-a4c98fb78c3a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106a55a980636498f</li>
        <li>Upwork Job ID: 1707682565947748352</li>
        <li>Last Price Increase: 2023-09-29</li>
<li>Automatic offers: </li>
<ul>
<li>abdel-h66 | Contributor | 26983210</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2023-09-27 00:55
Seems most likely related to https://github.com/Expensify/App/pull/28113

**Comment by marcaaron** [comment] 2023-09-27 01:08
FWIW, seems to be working fine on web and desktop. Can't reproduce there.

**Comment by zanyrenney** [comment] 2023-09-27 01:12
I also can't reproduce this @marcaaron

**Comment by zanyrenney** [comment] 2023-09-27 01:12
do we want to close this or is there something else to check?

**Comment by marcaaron** [comment] 2023-09-27 02:37
I'm gonna give it one more try on Android to confirm before closing. But it feels like a non-blocker to me.

**Comment by marcaaron** [comment] 2023-09-27 02:45
It is reproducible on Android:

<img width="397" alt="2023-09-27_10-44-56" src="https://github.com/Expensify/App/assets/32969087/811c573f-8241-4ff8-9e01-833c53060e5a">

**Comment by zanyrenney** [comment] 2023-09-29 09:03
seems like this one can be external though.

**Comment by abdel-h66** [comment] 2023-09-30 13:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
inilne code that contains a `<del> `tag are rendered incorrectly on iOS and Android 

### What is the root cause of that problem?
The issue seems to be partially coming from this  https://github.com/Expensify/App/issues/17365
And specifically come from the new style of the del tag with a `flex: 1` causing it to expand 

https://github.com/Expensify/App/blame/52f0e3c9ec9ab5c87993672661095f81253bc00d/src/styles/styles.js#L80-L84


### What changes do you think we should make in order to solve the problem?
I am stilll not sure what's the reason of introducing the `flex:1` to the `del` tag as removing didn't affect the outcome of https://github.com/Expensify/App/issues/17365 

By removing the `{flex: 1}` from the del tag styling seems to fix the issue as it no longer expand all the way down. 

I also made sure it didnt affect the previous by checking the reproduction steps of this issue here https://github.com/Expensify/App/issues/17365 

https://github.com/Expensify/App/assets/144037189/a6a2c06e-4400-4d71-83d2-84307b064c14


### What alternative solutions did you explore? (Optional)

N/A

**Comment by narefyev91** [comment] 2023-10-02 09:33
Proposal from @abdel-h66 looks good to me https://github.com/Expensify/App/issues/28169#issuecomment-1741768281
Agree that flex:1 is not really needed in these cases
🎀 👀 🎀 C+ reviewed

**Comment by abdel-h66** [comment] 2023-10-03 10:34
PR is ready for review @narefyev91  @tylerkaraszewski 🎉

**Comment by zanyrenney** [comment] 2023-10-16 11:18
PAYMENT SUMMARY

 External issue reporter. -  n/a reported by applause
 Contributor that fixed the issue - paid $750 ($500 + $250 urgency)
 Contributor+ that helped on the issue and/or PR - expert agency should be paid via invoice.

**Closed by zanyrenney** 2023-10-16 11:18 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
