### ISSUE TITLE
Chat - Extra space is missing on Android app and mWeb if selected from emojis picker

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19648] opened 2023-05-26 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19304

## Action Performed:
1. Login to NewDot
2. open any chat
3. Tap on compose box
4. Select an emoji from emoji picker

## Expected Result:
Extra space should appear after emoji

## Actual Result:
Extra space is missing on Android app and mWeb if selected from emojis picker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/5e94b19fcac35462b2065357736d0c7a50a46b9fda23459b156b7f46ea873905

https://platform.applause.com/services/links/v1/external/47810df62211054bc27b23f3addf325f865b627985c31fa82ca7a2467f49f2e1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by AlexanderDmitriev** [comment] 2023-05-26 03:02
###Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Extra space is missing on Android app and mWeb if selected from emojis picker

### What is the root cause of that problem?
It was inserting `space` after picked emoji when click one emoji from suggested emojis.
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/home/report/ReportActionCompose.js#L623
![image](https://github.com/Expensify/App/assets/17315937/8a1a831f-ba7c-48b2-8ffe-fe2f54d22161)

### What changes do you think we should make in order to solve the problem?
Remove the `space` from the line

        this.updateComment(`${commentBeforeColon}${emojiCode}${this.trimLeadingSpace(commentAfterColonWithEmojiNameRemoved)}`, true);

![image](https://github.com/Expensify/App/assets/17315937/60239941-0b68-4048-a8e7-ae6979606117)


### What alternative solutions did you explore? (Optional)
N/A

**Comment by tienifr** [comment] 2023-05-26 09:33
This is not a bug but intentional as per this thread: https://expensify.slack.com/archives/C01GTK53T8Q/p1668009281985659?thread_ts=1667208968.300839&cid=C01GTK53T8Q

**Comment by joekaufmanexpensify** [comment] 2023-05-26 12:26
Yep, closing as this is intentional, per the above thread!

**Closed by joekaufmanexpensify** 2023-05-26 12:26 UTC
Labels: Daily, Bug
