### ISSUE TITLE
[HOLD for payment 2024-03-13] MEDIUM: [$500] Drop domain names when searching for users and auto-filling mentions

### ISSUE THREAD

**Issue by NikkiWines** [Expensify/App#35532] opened 2024-02-01 01:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** N/A
**Logs:**  N/A
**Expensify/Expensify Issue URL:** N/A
**Issue reported by:** N/A
**Slack conversation:** N/A

## Action Performed:
1. Create a room with 4 members: 2 on the same private domain, 1 on another private domain, and 1 on a public domain
2. Draft a message that includes mentions for each user. 

## Expected Result:
When mentioning a user on the same private domain, the search result for the mention should not include the domain for the user's email. For example, given a message between two users -  nikkiwines@expensify.com and puneet@expensify.com - the search and auto-complete behavior should look like this: 

<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/619ccd84-2063-40cb-8db7-7f4880a652e9">
<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/d2df9b9c-ec58-43dc-839a-057a0ac551d6">

When mentioning a user on a public domain or on a different private domain, the behavior should remain largely as it is, though we will now prepend an `@` to the front of the login details (e.g. `Nikki Wines nikkiwines@expensifail.com` becomes `Nikki Wines @nikkiwines@expensifail.com`) when showing the mention options in search.

## Actual Result:
The search result and mention auto-complete a same-private-domain mention contains the full email domain, even though the domain name gets removed after sending the message. 

https://github.com/Expensify/App/assets/16747822/860a332c-b2e2-44dc-ad00-8f5f8fc409bf
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c84c193620b0a5db</li>
        <li>Upwork Job ID: 1754684823991881728</li>
        <li>Last Price Increase: 2024-02-06</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2024-02-01 01:57
@NikkiWines what would you think about including the @ symbol in the auto-selection dialog. So instead of having it be: 

>**Puneet Expensicorp** puneet@expensicorp.com
>**Puneet Lath** puneet

To have it be: 
>**Puneet Expensicorp** @puneet@expensicorp.com
>**Puneet Lath** @puneet

So that we really reinforce this idea of the handle

**Comment by ayoung19** [comment] 2024-02-01 07:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Users on the same private domain should have the doamin omitted in the list of suggestions.

### What is the root cause of that problem?

Currently the suggestions retrieved are displayed as is.

https://github.com/Expensify/App/blob/c6758578fb85e9eff6f9ccf5a52f3dd34e6e6383/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.js#L148

### What changes do you think we should make in order to solve the problem?

Like already done in the `CompanyStep` component, the `ComposerWithSuggestions` component should get the user and session object from Onyx to figure out whether the user is a from a public domain. If not, the domain can be extracted with `Str.extractEmailDomain` from the session object and this value can be used to hide the domain from the list of suggestions.

### What alternative solutions did you explore? (Optional)

**Comment by NikkiWines** [comment] 2024-02-01 17:11
I'm fine with it! I based this issue on what we have currently in product and also what Slack does. 

<img width="390" alt="image" src="https://github.com/Expensify/App/assets/16747822/87e58be8-0673-4fde-8870-6c3952e90a8e">

But, since the autocomplete mention in the message draft prepends `@`, I think it'd be fine to display it in the search as well. I'll update the screenshots

**Comment by NikkiWines** [comment] 2024-02-01 17:20
@puneetlath do you think we should also highlight the `@` in the search or do you think it's fine as it is in this screenshot

<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/619ccd84-2063-40cb-8db7-7f4880a652e9">

**Comment by alexpensify** [comment] 2024-02-02 22:10
@NikkiWines - let me know if you want me to run this over to Design and then I can assign `external`. Thanks!

**Comment by NikkiWines** [comment] 2024-02-02 22:35
Always get to get a once over by the experts! Let's grab someone from design to give things a look just to be certain

**Comment by alexpensify** [comment] 2024-02-06 00:30
I asked for feedback here: 

 https://expensify.slack.com/archives/C03TME82F/p1707179243394239

**Comment by dubielzyk-expensify** [comment] 2024-02-06 00:36
I don't feel super strongly. Given the name in bold won't have a @ sign I err on the side of not highlighting it. If we highlighted the `@` symbol we'd end up with different highlights. 
![CleanShot 2024-02-06 at 10 35 36@2x](https://github.com/Expensify/App/assets/145416827/ed4eec06-a8a7-40f2-b171-55ce4c7b6b92)

I hope that made sense, but yeah, I'm mostly on not highlighting it. Keen on @dannymcclain and @shawnborton thoughts too though

**Comment by shawnborton** [comment] 2024-02-06 01:30
Yup, what Jon said! I agree with that.

**Comment by NikkiWines** [comment] 2024-02-06 01:53
Nice, thanks, guys! I think this one is ready for proposals then 🚀

**Comment by ayoung19** [comment] 2024-02-06 01:58
Hey all! I'm a new contributor and am a bit unfamiliar with the proposal flow. Was this issue previously not available for proposals? Do I have to resubmit mine? Thanks!

**Comment by NikkiWines** [comment] 2024-02-06 02:17
You can post a proposal before the `Help Wanted` label is added, but it comes with some risk and won't be reviewed until the issue is marked as ready for pickup (via the aforementioned `Help Wanted` label).

There are some more details in the `Propose a solution for the job` section of the contributing readme [here](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job), which is a good resource to review in general.

**Comment by ayoung19** [comment] 2024-02-06 02:19
Ah got it. Thank you so much for clarifying, I missed that part of the doc and was kind of just cargo cult'ing other proposals.

**Comment by alexpensify** [comment] 2024-02-07 23:48
Bringing you back @allroundexperts as the C+, please keep us posted if a proposal here will fix the one. Thanks!

**Comment by alexpensify** [comment] 2024-02-09 17:56
@allroundexperts - will any of these proposals help here? Thanks!

**Comment by allroundexperts** [comment] 2024-02-12 04:57
Hi @tienifr. I don't understand why we need to touch the `ExpensiMark` library? We're matching `@...` without the email already. Since we will be dropping the domain part from suggestion text, the highlight should work as expected as well.

https://github.com/Expensify/App/assets/30054992/a206ada8-ee70-44aa-ac30-0c6746d48bc5

Let me know if I missed something.

**Comment by allroundexperts** [comment] 2024-02-12 05:07
Please don't lie @MelvinBot. Are you having memory issues? 💀

**Comment by allroundexperts** [comment] 2024-02-12 18:55
That makes sense. Thanks for the detailed explanation. @tienifr's [proposal](https://github.com/Expensify/App/issues/35532#issuecomment-1928906247) should work well!

🎀 👀 🎀 C+ reviewed

**Comment by alexpensify** [comment] 2024-02-14 19:22
Daily Update: It's been assigned and waiting for a PR to review.

**Comment by NikkiWines** [comment] 2024-02-14 19:33
Sorry, actually hadn't quite finished reviewing the proposals. I agree @tienifr's proposal looks good - thanks for the clarification on the ExpensiMark changes needed.

**Comment by quinthar** [comment] 2024-02-16 05:19
what's the latest here?  Who is picking this up?

**Comment by allroundexperts** [comment] 2024-02-16 06:08
This got assigned to @tienifr yesterday and we are waiting for a PR here.

**Comment by NikkiWines** [comment] 2024-02-16 21:25
@tienifr it looks like your changes from [this PR](https://github.com/Expensify/App/pull/34013/) were accidentally excluded when `MentionUserRenderer` was migrated to typescript, so shortened mentions aren't shown any longer. 

Could you add your original changes from that PR as part of this issue, please?

**Comment by allroundexperts** [comment] 2024-02-21 10:27
@tienifr Bump on https://github.com/Expensify/App/issues/35532#issuecomment-1949356557

**Comment by allroundexperts** [comment] 2024-02-28 06:08
@alexpensify A PR was raised and merged for this already [here](https://github.com/Expensify/App/pull/37132)

**Comment by alexpensify** [comment] 2024-02-28 15:44
Perfect, thanks for the update @allroundexperts

**Comment by alexpensify** [comment] 2024-03-01 02:05
Heads up, I will be offline until Tuesday, March 5, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the Open Source Slack Room-- thanks!

**Comment by NikkiWines** [comment] 2024-03-04 22:25
Technically the phone number logins are emails and would fall under the same category 😅 but I understand your meaning and it definitely wasn't clear in the issue description. Additionally, since updating the phone number logins required separate logic from the email ones, I think an argument can be made for applying a bonus here. What do you think @alexpensify?

**Comment by alexpensify** [comment] 2024-03-05 18:59
Ok, after reviewing, this wouldn't be a reporting bonus but the amount wouldn't be the full payment amount for a PR. I'm suggesting to go with 25% of the PR amount and apply that as a payment for the extra update. In this case, it would be 500 for the PR and then 125 for the additional PR update.

**Comment by situchan** [comment] 2024-03-12 10:18
There's regression - https://github.com/Expensify/App/issues/38074#issuecomment-1991267250

**Comment by alexpensify** [comment] 2024-03-12 15:10
Thanks for flagging.

**Comment by alexpensify** [comment] 2024-03-13 23:18
I'm going to hold off until tomorrow to review the payment details here.

**Comment by alexpensify** [comment] 2024-03-15 01:13
Here is the payment summary: 

-  External issue reporter - N/A 
-  Contributor that fixed the issue @tienifr $500 
-  Contributor+ that helped on the issue and/or PR @allroundexperts $250 

Upwork Job: https://www.upwork.com/jobs/~01c84c193620b0a5db

Extra Notes regarding payment: There is regression, so I've accounted for that in the payment summary. Closing since everyone who is paid in Upwork has been sent one there.

**Comment by allroundexperts** [comment] 2024-03-17 22:54
Hi @alexpensify!
I think you forgot to account for https://github.com/Expensify/App/issues/35532#issuecomment-1979444185 in the payment summary?

**Comment by alexpensify** [comment] 2024-03-18 15:38
@allroundexperts - thanks for the reminder. I'll work on this update later today.

**Comment by alexpensify** [comment] 2024-03-19 19:09
I've updated the payment summary: 

https://github.com/Expensify/App/issues/35532#issuecomment-1998726031

**Comment by alexpensify** [comment] 2024-03-19 19:16
Alright, closing again - the summary and the payment in Upwork has been updated accordingly.

**Closed by alexpensify** 2024-03-19 19:16 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-22 21:30
$375 approved for @allroundexperts based on summary.
