### ISSUE TITLE
[$500] Task - Unavailable workspace displayed in header of task created in new group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36231] opened 2024-02-09 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4295156
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Tap the FAB and select 2 users you do not have a group chat yet
3. In the group chat assign a task with a description
4. Log out and logged in as the same user
5. Open the task created in step 3

Alternate steps - same issue with the following scenario:

1. Create a task and assign it to user A
2. Share the task with User B (DM conversation)
3. Login as User A and check the task

## Expected Result:
Task name and "From <chat>" are mentioned in the header, no other information

## Actual Result:
"In unavailable workspace" and task description as the workspace name are displayed in the header. The same is observed when opening a task as an external assignee.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2ef11c0f-6b77-4f91-bd83-50328bbabfe3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec02ec8bbcbc31c5</li>
        <li>Upwork Job ID: 1755957338322825216</li>
        <li>Last Price Increase: 2024-03-08</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-09 14:11
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by ikevin127** [comment] 2024-02-09 15:30
# Proposal

### Please re-state the problem that we are trying to solve in this issue

"In unavailable workspace" and task description as the workspace name are displayed in the header.
The same is observed when opening a task as an external assignee.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/85c990eb3ddba4a8709ce51f69d5c1393896f1ea/src/pages/home/HeaderView.js#L114

Issue comes from this line, and within the `getPolicyName` function we return `Unavailable workspace` in these 2 cases:
-  `const noPolicyFound = returnEmptyIfNotFound ? '' : Localize.translateLocal('workspace.common.unavailable')`
 if (isEmptyObject(report)) {return noPolicyFound;}
- `(!allPolicies || Object.keys(allPolicies).length === 0) && !report?.policyName`

### What changes do you think we should make in order to solve the problem?

In HeaderView where we call getPolicyName, add `returnEmptyIfNotFound` prop as `true` so that when the policy is empty we don't return the `Unavailable workspace`.

**Comment by ikevin127** [comment] 2024-02-09 16:00
# Proposal

### Please re-state the problem that we are trying to solve in this issue

"In unavailable workspace" and task description as the workspace name are displayed in the header.
The same is observed when opening a task as an external assignee.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/85c990eb3ddba4a8709ce51f69d5c1393896f1ea/src/pages/home/HeaderView.js#L114

Issue comes from this line, because within the `getPolicyName` function we return `Unavailable workspace` in these 3 cases:

1.
```js
    const noPolicyFound = returnEmptyIfNotFound ? '' : Localize.translateLocal('workspace.common.unavailable');
    if (isEmptyObject(report)) {
        return noPolicyFound;
    }
```

2. 
```js
    if ((!allPolicies || Object.keys(allPolicies).length === 0) && !report?.policyName) {
        return Localize.translateLocal('workspace.common.unavailable');
    }
```

3. 
```js
    const policyName = finalPolicy?.name || report?.policyName || report?.oldPolicyName || parentReport?.oldPolicyName || noPolicyFound;
    return policyName;
```

Our issue is with the last return which in our case, because all variables are undefined, it returns the last one `noPolicyFound` which was initialized with `Unavailable workspace` since `returnEmptyIfNotFound` is false by default.

### What changes do you think we should make in order to solve the problem?

In HeaderView where we call getPolicyName, add `returnEmptyIfNotFound` prop as `true` so that when the policyName is empty at the last return, the `noPolicyFound`will return empty string instead of `Unavailable workspace`.

```js
const policyName = ReportUtils.getPolicyName(props.report, true);
```

This will make it such that when the HeaderView `renderAdditionalText` function checks the policyName here:

https://github.com/Expensify/App/blob/85c990eb3ddba4a8709ce51f69d5c1393896f1ea/src/pages/home/HeaderView.js#L180

it won't return the component rendering `Unavailable workspace` since `policyName` will be an empty string.

### Videos

<details>
<summary>iOS: Native</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/dcab9357-5c2e-4cea-bdb7-d7115c7386f3"> | <video src="https://github.com/Expensify/App/assets/56457735/9250d0de-68df-4385-ae41-540cb726d5b1"> |

</details>

**Comment by isagoico** [comment] 2024-02-09 17:28
I was also able to reproduce the same issue with the following scenario: 

1. Create a task and assign it to user A
2. Share the task with User B (DM conversation) 
3. Login as User A and check the task 

![image](https://github.com/Expensify/App/assets/44479856/e894de2c-e71b-48af-802f-736b9a13a060)

I'm guessing that since User A doesn't have access to the conversation between the creator and user B the header should display something like "Shared in a separate conversation" or just nothing. 

Tagging @thienlnam since your my task behavior sensei 😅

**Comment by thienlnam** [comment] 2024-02-09 20:21
Yeah that looks correct - if the task is created in a DM or room that the assigned user does not have access to, it should say something like 'Unavailable workspace' / 'Shared in a separate conversation'.

Though the group chat flow in the description is interesting, because if you create a group chat with 
User A
User B
User C

And then create a task within that group chat and assign it to C, then C should be able to see that it's within the group chat since they have access to where the task was created.

In that case since the parent is a chat chat and not part of a workspace, I imagine that would not show anything?

**Comment by miljakljajic** [comment] 2024-02-13 16:58
still discussing

**Comment by miljakljajic** [comment] 2024-02-21 09:18
still discussing

**Comment by ikevin127** [comment] 2024-02-25 22:24
@brandonhenry Yes it does, as long as it has the `Help Wanted` label and nobody was assigned as a Contributor yet - you can go for it. See [`Propose a solution for the job`](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job) for more details.

There's always a chance other proposals
missed some critical details in their RCA (root cause analysis) or solution and there are cleaner / better ways to do it. 

In this case you can try a different / better way to tackle what I proposed or go for the other possible solutions mentioned by https://github.com/Expensify/App/issues/36231#issuecomment-1936551364, since the team has not yet decided which way we should go with this one.

**Comment by ikevin127** [comment] 2024-02-26 14:48
@parasharrajat I'm confused 🤔, `Unavailable workspace` is what we see currently and the issue's **Expected result** is asking to not show that at all - which is what my proposal's solution accomplishes.

Maybe the team can clear things up as to what we want to do here and whether we should change the issue's expected result (if something else is desired) - so I can update my proposal or post a new one depending on what we want to do here.

cc @thienlnam @miljakljajic @isagoico

**Comment by miljakljajic** [comment] 2024-03-20 15:40
I think we can close this honestly - it's pretty low priority

**Closed by miljakljajic** 2024-03-20 15:40 UTC
Labels: Engineering, Weekly, Internal, Bug
