### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$1000] Web - Share code avatar shows broken image in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21899] opened 2023-06-29 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log in with a new account
2. Go offline
3. Click your avatar > Share code

## Expected Result:
Avatar should be shown

## Actual Result:
A broken image is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
All
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/26260477/2085f475-3cd0-4ad8-9f03-a9f88f2071f3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687980039132169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164a0dfb23339d59b</li>
        <li>Upwork Job ID: 1675977766780624896</li>
        <li>Last Price Increase: 2023-07-24</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26403078</li>
<li>Nathan-Mulugeta | Reporter | 26403079</li>
<li>b4s36t4 | Contributor | 27063878</li>
</ul></li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-07-03 16:36
I cannot reproduce this using these steps.

**Comment by MitchExpensify** [comment] 2023-07-03 21:19
Went to get your the recording and reproduced on Safari

<img width="940" alt="image" src="https://github.com/Expensify/App/assets/36425901/3e3ffbfb-ae6a-49b5-b1f1-8ad8f0a040e0">

**Comment by pradeepmdk** [comment] 2023-07-04 02:37
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Share code avatar shows the broken image in offline mode

### What is the root cause of that problem
image load from cloud URL
![Screenshot 2023-07-04 at 8 03 42 AM](https://github.com/Expensify/App/assets/16595846/f7113dd6-e5f3-4086-b91d-1404a6d6dcb5)

### What changes do you think we should make in order to solve the problem?
we need to convert the URL into base64 and store it local. we need a load from local base64

### What alternative solutions did you explore? (Optional)
N/A

**Comment by MitchExpensify** [comment] 2023-07-10 22:06
How does the proposal above look to you @0xmiroslav ?

**Comment by pradeepmdk** [comment] 2023-07-17 12:14
@0xmiroslav ya, the image is already cached above Scanrio. How mean by default react native this image cache system
https://reactnative.dev/docs/image


<img width="893" alt="Screenshot 2023-07-17 at 5 33 10 PM" src="https://github.com/Expensify/App/assets/16595846/30c112df-3e4d-42d2-99c2-ef6e819a30bb">
<img width="764" alt="Screenshot 2023-07-17 at 5 36 23 PM" src="https://github.com/Expensify/App/assets/16595846/2b67b993-9d30-4e3d-b6ae-0252625b4449">
in the share code component, we are calling the getAvatarUrl its returns as a URL. but all other places we are calling the `UserUtils.getAvatar` it will return as the default avatar from local file as svg component.

so by default, there is no possibility to call that image Http URL from   react-native `<Image/> ` Tag. so that when we go offline and navigate to share code page means it will failed to load the image.

### Solution
 in the initalSettingpage also we need to call `getAvatarUrl` instead of `getAvatar` so that it will cache the image.

**Comment by pradeepmdk** [comment] 2023-07-17 16:44
@0xmiroslav 
we can catch url using this
https://reactnative.dev/docs/image#prefetch

**Comment by pradeepmdk** [comment] 2023-07-17 17:10
@0xmiroslav 
we can cache the image using this 
https://reactnative.dev/docs/image#prefetch  in `sidebaarLinks.js`

` Image.prefetch(UserUtils.getAvatarUrl(this.props.currentUserPersonalDetails.avatar, this.props.currentUserPersonalDetails.accountID));`

**Comment by getusha** [comment] 2023-07-20 03:42
@0xmiroslav custom avatar will not show when offline everywhere.

**Comment by getusha** [comment] 2023-07-20 19:22
@0xmiroslav this is what i am seeing


https://github.com/Expensify/App/assets/75031127/225a1293-8326-41f1-936f-75a1ac43f4cc

**Comment by pbkompasz** [comment] 2023-07-22 11:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The profile picture is not accessible in the  `QRShare` component in offline mode. 

### What is the root cause of that problem?

The `QRShare` components accepts a URL for the `logo` prop.
Currently this URL points to CDN which is inaccessible in offline mode.

### What changes do you think we should make in order to solve the problem?

The images are present before going offline, but when the client goes offline every image is replaced by `fallback-avatar.svg`. 
We could apply the same to the `QRShare` component.
The solution would be calling `createObjectURL` on the `fallback-avatar.svg` asset and passing the URL to the `QRShare` component.



### What alternative solutions did you explore? (Optional)

Another solution would be caching the images locally and continue displaying those.

**Comment by pbkompasz** [comment] 2023-07-22 11:33
Contributor details
Your Expensify account email: kompaszbence@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~010a99c9f94b50a5da

**Comment by pbkompasz** [comment] 2023-07-23 08:51
@0xmiroslav When a client enters offline mode the avatars change to the default ones. This mechanism is probably to notify the user about being offline. I think applying the same logic to the `QRShare` component would be best option.
There are more details in [my proposal](https://github.com/Expensify/App/issues/21899#issuecomment-1646558708).

**Comment by pbkompasz** [comment] 2023-07-24 05:42
@0xmiroslav This is what I get
[Screencast from 24.07.2023 08:34:02.webm](https://github.com/Expensify/App/assets/47194071/0b265e7f-7afa-42bd-b82f-755d210cd844)
When we go offline we get the default avatar(upper-left corner), this doesn't happen for the QR code.
And when we go back online the avatars are fetched automatically. This functionality doesn't exist when the avatar is accessed through the `getAvatarUrl` method.

**Comment by MitchExpensify** [comment] 2023-07-26 20:33
Friendly bump here @0xmiroslav 🙇

**Comment by aldo-expensify** [comment] 2023-07-28 18:42
I think this would be good to ask to a designer, but Shawn is out of office today. I'll try on Monday.

**Comment by aldo-expensify** [comment] 2023-07-28 18:50
Shawn I wanted your opinion on this: https://github.com/Expensify/App/issues/21899#issuecomment-1655659911 🙏

**Comment by shawnborton** [comment] 2023-07-31 12:19
Can you actually download this image if you are offline?

**Comment by aldo-expensify** [comment] 2023-08-02 22:27
> I am not confident if we should use that as backup. This page also supports download feature and downloaded image should have that fallback avatar?

I don't think the default avatar is better than https://github.com/Expensify/App/issues/21899#issuecomment-1658256549 or no avatar at all. I think it can cause more confusion because it is less obvious that you are seeing that because you are offline.

**Comment by aldo-expensify** [comment] 2023-08-02 22:28
> So is it fine to download different QR images generated when offline vs online?

If you can't put the real avatar, then I think any alternative between no image or [this](https://github.com/Expensify/App/issues/21899#issuecomment-1658256549) is good enough for me.

**Comment by aldo-expensify** [comment] 2023-08-02 22:44
I see, thanks for explaining. Yes **fallback** or no avatar is fine for me if it is not possible to retrieve the real avatar.

> So it seems any of option 1-4 is pickable. Maybe choose the best one depending on how difficult to implement?

Sounds like a good plan for me

**Comment by aldo-expensify** [comment] 2023-08-09 19:44
@MitchExpensify now that we have better defined the expected results, do you know if we can make this `External` again? or should it stay `Internal` because it is older than 4 weeks?

**Comment by MitchExpensify** [comment] 2023-08-10 20:36
Lets go `external` seeing as it was waiting on better steps so lets see if any solid proposals come in before going `internal`

**Comment by b4s36t4** [comment] 2023-08-13 18:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Share code avatar shows broken image in offline mode
### What is the root cause of that problem?
RCA for this issue is we're loading avatar from URL instead of saved image/static asset.
### What changes do you think we should make in order to solve the problem?

To solve this issue we have to patch `react-native-qrcode-svg` package/raise a upstream PR.

Since this involves an error from network and there's no way to figure out the error/success with the `react-native-qrcode-svg` package.

https://reactnative.dev/docs/image#onerror using this prop here https://github.com/awesomejerry/react-native-qrcode-svg/blob/42b0817803a67c295604db962311392a6dabc97d/src/index.js#L57-L63 inside the package let's us handle the error scenario (offline issue)

Using this we introduce a new state here inside this page https://github.com/Expensify/App/blob/01fc9285e5eeff2ac79173d799fad75f9d624d99/src/pages/ShareCodePage.js#L41.

Whenever we have the error callback triggered we update the state and conditionally render the `logo`. If there is error we send `undefined` to `logo` prop which makes the QR code with no logo.

If we want a fallback avatar we should have a png variant of fallback avatar and just render it conditionally depends on the error should show the fallback variant.



### What alternative solutions did you explore? (Optional)
NA

##Result

https://github.com/Expensify/App/assets/59088937/61b652d0-cf8e-4070-9af9-33d170eacf27

**Comment by MitchExpensify** [comment] 2023-08-14 19:16
@0xmiroslav how does @b4s36t4 's proposal look to you?

**Comment by b4s36t4** [comment] 2023-08-16 19:03
@0xmiroslav can you review my proposal?

**Comment by shawnborton** [comment] 2023-08-21 13:43
Not overdue, reviewing proposals.

**Comment by aldo-expensify** [comment] 2023-08-25 19:54
Friendly bump @0xmiroslav for proposals review

**Comment by b4s36t4** [comment] 2023-08-28 15:20
Bumping @0xmiroslav :)

**Comment by aldo-expensify** [comment] 2023-08-29 01:14
No updates, waiting on @0xmiroslav to review proposals

**Comment by MitchExpensify** [comment] 2023-08-29 04:39
@0xmiroslav I'm going to have to unassign you as C+ here if you cannot jump in very soon

**Comment by situchan** [comment] 2023-08-29 06:00
I can review this today

**Comment by MitchExpensify** [comment] 2023-08-30 03:57
Done, thanks!

**Comment by MitchExpensify** [comment] 2023-08-30 03:58
Sorry for the auto-offer @Nathan-Mulugeta , that seems premature. I was just hoping to reasisgn @0xmiroslav to @situchan

**Comment by b4s36t4** [comment] 2023-08-31 09:39
@situchan have u reviewed the proposals?

**Comment by aldo-expensify** [comment] 2023-09-01 21:19
Waiting on @situchan to review proposals

**Comment by MitchExpensify** [comment] 2023-09-05 13:15
Chatted 1:1 - @situchan hopes to get to this in the next 24 hours

**Comment by b4s36t4** [comment] 2023-09-08 20:10
@situchan any update on the proposals?

**Comment by situchan** [comment] 2023-09-08 20:13
I will provide feedback on Monday when freeze will be over

**Comment by aldo-expensify** [comment] 2023-09-11 12:41
No overdue, waiting for @situchan feedback

**Comment by MitchExpensify** [comment] 2023-09-13 19:32
Friendly bump here @situchan

**Comment by situchan** [comment] 2023-09-13 19:33
reviewing today

**Comment by MitchExpensify** [comment] 2023-09-14 21:58
Thank you @situchan

**Comment by situchan** [comment] 2023-09-18 09:54
updating today

**Comment by shawnborton** [comment] 2023-09-21 03:07
What's the latest here?

**Comment by b4s36t4** [comment] 2023-09-21 03:09
Proposals Review from @situchan

**Comment by situchan** [comment] 2023-09-25 10:34
sorry for late. will update today for sure

**Comment by MitchExpensify** [comment] 2023-09-26 04:39
Hows the update coming along @situchan ?

**Comment by aldo-expensify** [comment] 2023-09-29 10:12
Waiting on @situchan 's update

**Comment by shawnborton** [comment] 2023-10-02 13:45
Waiting for an update still, @situchan how is this one going?

**Comment by MitchExpensify** [comment] 2023-10-03 22:06
Bumped @situchan 1:1

**Comment by situchan** [comment] 2023-10-06 12:33
Can everyone share demo video after applying your solution? (Both default avatar and custom avatar cases, open page first time offline, 2nd time offline after opened when online)
cc: @hungvu193 @pradeepmdk @pbkompasz @b4s36t4

**Comment by b4s36t4** [comment] 2023-10-06 12:41
@situchan I have added demo videos (except custom avatar)

**Comment by situchan** [comment] 2023-10-06 12:42
custom avatar is the main one I am going to review

**Comment by b4s36t4** [comment] 2023-10-06 12:51
@situchan Sorry, custom avatar is what I added in my demo, default one's will do in sometime.

**Comment by neil-marcellini** [comment] 2023-10-06 18:37
Taking over for Aldo as he requested [here](https://expensify.slack.com/archives/C03TQ48KC/p1696595416254989) (internally).

**Comment by neil-marcellini** [comment] 2023-10-06 19:03
@situchan Aldo and I agree that we should request a new C+ in Slack because the progress is moving too slowly here.

**Comment by neil-marcellini** [comment] 2023-10-06 19:27
After looking into this more I'm noticing that the test steps in the description are out dated. The workspace share code no longer uses the workspace avatar image.
![image](https://github.com/Expensify/App/assets/26260477/e6c153a4-b0cd-403d-a0ed-870a580e20f6)

I see that in @b4s36t4's [proposal](https://github.com/Expensify/App/issues/21899#issuecomment-1676425219) he is testing with the profile share code.

I'll update the description with these new steps. I verified that this is a problem.
1. Log in with a new account
2. Go offline
3. Click your avatar, Share code

https://github.com/Expensify/App/assets/26260477/2085f475-3cd0-4ad8-9f03-a9f88f2071f3

I like @b4s36t4's [proposal](https://github.com/Expensify/App/issues/21899#issuecomment-1676425219). While we're waiting for the upstream PR, maybe we can remove the avatar from the share code if the app is offline?

Also it's odd that we can see the avatar loaded in one place, but we can't load it elsewhere. I guess that's a result of how the caching works but it would be cool if we could use that same cached image. Please DM me if you have an explanation for that and in the meantime please get started on the PRs 🚀

**Comment by situchan** [comment] 2023-10-06 20:54
Apologize for the slow progress. I am now back on this.

We should fix report avatar (newDot logo) case as well.

https://github.com/Expensify/App/assets/108292595/b105577c-c9bc-42c4-9d21-5bce8320871b


It's the most simple solution to remove logo completely when offline or error, no matter user profile avatar / report avatar, default avatar / custom avatar. So this is agreed solution, right?
If we should use the cached/local image, it's another challenge and should be part of proposal before assign.

**Comment by pradeepmdk** [comment] 2023-10-08 01:04
@situchan @neil-marcellini Sorry for the late response

we have two scenarios here 
`logo={isReport ? expensifyLogo : UserUtils.getAvatarUrl(this.props.currentUserPersonalDetails.avatar, this.props.currentUserPersonalDetails.accountID)}`


`expensifyLogo`  this logo is local reference so that offline its doesn't load
`UserUtils.getAvatarUrl` this will point a external url since we are not caching so that this also failed load 
but this case `getAvatarUrl` we can fix this  precache
https://github.com/Expensify/App/issues/21899#issuecomment-1638547521
https://github.com/Expensify/App/issues/21899#issuecomment-1638006473
using those any of them we can fix this 

`expensifyLogo` never load in offline so we can add isoffline statement to hide the image. or we can implement the service worker to cache the image. once we implement the service worker we can add all local cache images and put them here.

since we are all the place we are using svg so here also we can put patch fix for support svg in the 'react-native-qrcode-svg'. so that it will keep loading the offline also because svg load as react component using `@svgr/webpack`

**Comment by situchan** [comment] 2023-10-08 09:30
I think it's better to hide all types of images completely when offline for consistency, unless we implement svg cache which is a new feature and could be handled separately.

Seems like we picked up Option 4 in https://github.com/Expensify/App/issues/21899#issuecomment-1655659911 as we agreed [here](https://github.com/Expensify/App/issues/21899#issuecomment-1663065167).

**Comment by neil-marcellini** [comment] 2023-10-10 16:51
Not overdue, waiting for contributor to raise a PR.

**Comment by situchan** [comment] 2023-10-11 11:34
@b4s36t4 now that we clarified everything on slack, it should be straight forward. How's PR going?

**Comment by MitchExpensify** [comment] 2023-10-18 21:08
What is the actual payment date here @situchan just as a buddy check 👁️

**Comment by MitchExpensify** [comment] 2023-10-20 20:23
- $1000 *Payment Su@b4s36t4 requires payment [offer](https://www.upwork.com/nx/wm/offer/27063878) (Contributor)
- $1000 @situchan requires payment [offer](https://www.upwork.com/nx/wm/offer/26403078) (Contributor)
- $250 - @Nathan-Mulugeta requires payment [offer](https://www.upwork.com/nx/wm/offer/26403079) (Reporter)

**Comment by situchan** [comment] 2023-10-20 20:26
Just to friendly remind that this is eligible for bonus.
PR was approved by engineer less than 3 days. 10 min delay was just from waiting final approval from design team

**Comment by b4s36t4** [comment] 2023-10-20 20:26
Was about to say same, thanks @situchan

**Comment by MitchExpensify** [comment] 2023-10-20 20:27
Oh cool, thanks for flagging1

**Comment by MitchExpensify** [comment] 2023-10-20 20:31
Paid all but @situchan as I had to create a new offer [here](https://www.upwork.com/nx/wm/offer/27300890) for you

**Comment by situchan** [comment] 2023-10-20 20:38
- [x] The PR that introduced the bug has been identified. Link to the PR: N/A
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

As a regression test, we can use 3 test cases in Tests Steps of [PR](https://github.com/Expensify/App/pull/29343).

**Comment by MitchExpensify** [comment] 2023-10-22 18:44
> As a regression test, we can use 3 test cases in Tests Steps of https://github.com/Expensify/App/pull/29343.

Mind bringing the number steps you are referring to and suggesting we add here, just to be sure @situchan?

**Comment by situchan** [comment] 2023-10-22 18:45
> Mind bringing the number steps you are referring to and suggesting we add here, just to be sure @situchan?

<img width="696" alt="Screenshot 2023-10-23 at 12 44 55 AM" src="https://github.com/Expensify/App/assets/108292595/3fc98b08-a4ce-4079-b677-6a16a8fcb520">

**Comment by MitchExpensify** [comment] 2023-10-22 19:27
Thanks for clarifying! Added here https://github.com/Expensify/Expensify/issues/328592

**Comment by neil-marcellini** [comment] 2023-10-25 17:49
@MitchExpensify are we good to close this out now that we have an issue for regression tests?

**Comment by MitchExpensify** [comment] 2023-10-28 21:24
Paid out @situchan and contracts ended - Closing!

**Closed by MitchExpensify** 2023-10-28 21:24 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug
