### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] Dev: Console error on bank account Onfido flow

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29868] opened 2023-10-18 13:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev 1.3.86.1
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @Pujan92 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697636190219869

## Action Performed:
1. For any workspace go to Bank Account
2. Reach to step 3 which is Personal information(Choose document)
3. Observe the console warning in dev tools

## Expected Result:
There should not be console warnings

## Actual Result:
Console warnings exists due to `withLocalizePropTypes`.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 
![Screenshot_1697636185](https://github.com/Expensify/App/assets/93399543/91c30c78-7ee5-458c-a9bb-29095b7d72a8)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-18 at 18 58 04 (1)](https://github.com/Expensify/App/assets/93399543/84d7f757-cb8d-408e-90c4-41d188e8c5ce)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Screenshot 2023-10-18 at 18 53 37](https://github.com/Expensify/App/assets/93399543/f8bab6c5-fce9-4eb0-b458-fd0218bebbc1)

</details>

<details>
<summary>MacOS: Desktop</summary>

 
![Screenshot 2023-10-18 at 19 05 08](https://github.com/Expensify/App/assets/93399543/acb562f2-4c18-4b9a-9966-62bcf4a8db84)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010994b55eb605b669</li>
        <li>Upwork Job ID: 1714642342115131392</li>
        <li>Last Price Increase: 2023-10-18</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reporter | 27273804</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-10-18 13:59
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Console warning for not providing withLocalizeProps
### What is the root cause of that problem?
It is a regression from https://github.com/Expensify/App/pull/27424 where we removed `withLocalize` and used `useLocalize` but in the `propTypes` we have `StepPropTypes` which expects props `withLocalizePropTypes` and giving the console warnings.
### What changes do you think we should make in order to solve the problem?
We can take out `withLocalizePropTypes` from the `StepPropTypes` and add it to those components that require it bcoz now it seems to be not general for all steps. And I think sooner we are going to use `useLocalize` for other components too.

**Comment by trjExpensify** [comment] 2023-10-19 00:51
@barttom @sobitneupane - I think this should be handled by you guys right from https://github.com/Expensify/App/issues/16246?

**Comment by barttom** [comment] 2023-10-19 06:25
@trjExpensify YUp, I'll handle this

**Comment by trjExpensify** [comment] 2023-10-19 09:09
Cool, thanks. I'm going to assign you for tracking and remove `help wanted` :)

**Comment by trjExpensify** [comment] 2023-10-19 09:09
Also, @sobitneupane I'll switch you for @mananjadhav.

**Comment by tylerkaraszewski** [comment] 2023-11-01 23:54
@barttom - I believe you need to check off these items?

**Comment by barttom** [comment] 2023-11-02 10:05
@tylerkaraszewski That was a simple mistake during development, so I don't see the possibility of writing a test for it.

**Comment by tylerkaraszewski** [comment] 2023-11-02 16:24
You can check the items off if you decide we don't need a test.

**Comment by trjExpensify** [comment] 2023-11-02 16:35
In terms of payments, I think we just need $50 to @Pujan92 for the bug report right? This was a regression from https://github.com/Expensify/App/issues/16246

**Comment by barttom** [comment] 2023-11-02 18:03
@tylerkaraszewski checkboxes are disabled for me

**Comment by trjExpensify** [comment] 2023-11-02 18:59
Ahh, @thesahindia ended up being the C+ on the PR instead of @sobitneupane. That'll be why Melv was asking you for the checklist @barttom. 

Okay, so then we do need to pay @thesahindia $500 for the review because he wasn't involved in the PR that caused the regression. :)

**Comment by trjExpensify** [comment] 2023-11-03 15:26
Perfecto, settled up with @Pujan92 on Upwork. Closing!

**Closed by trjExpensify** 2023-11-03 15:26 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 22:12
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/29868#issuecomment-1791372461).
