### ISSUE TITLE
Pay button appears even it has been paid

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20988] opened 2023-06-18 15:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send an IOU from account A to B
2. Pay the money owed as account B
3. Send another IOU from Account A to B
4. Log in to account B
## Expected Result:
There should be only one `Pay` button for the 2nd request
## Actual Result:
There are 2 `Pay` buttons for both requests, when clicking first IOU showing as paid
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (2)](https://github.com/Expensify/App/assets/43996225/f1ff3820-12b0-46d8-8132-7446ffd2e615)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686350806883009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by twisterdotcom** [comment] 2023-06-20 09:43
I think we'll need two Gold Wallet users to test this.
<img width="555" alt="image" src="https://github.com/Expensify/App/assets/9133401/c98e6b1e-e59e-4680-91bd-d4690aa5a2ec">

**Comment by twisterdotcom** [comment] 2023-06-20 10:12
Downgrading to weekly for now.

**Comment by joekaufmanexpensify** [comment] 2023-06-20 15:05
@sonialiap and I tried to test this and were not able to reproduce. After paying the first IOU, and receiving a second, I see the pay button only once on my end, next to the second IOU: 

<img width="1134" alt="image" src="https://github.com/Expensify/App/assets/54866469/18c7a185-4af0-4ff2-84f7-08472ea6ea02">

**Comment by tranvantoan-qn** [comment] 2023-07-03 06:07
@twisterdotcom  @joekaufmanexpensify 
Look at the attached images, I think the steps weren't correct. It should be like this (_though I couldn't reproduce it with these steps either - maybe b/c I don't have a Gold wallet_):

- Send an IOU from **account A to B**
- Pay the money owed as **account B**
- Send another IOU from **Account B to A**

<img width="1440" alt="Steps revised" src="https://github.com/Expensify/App/assets/10254571/5c4e9f35-ede3-45f3-a742-6659c2c85461">

**Comment by twisterdotcom** [comment] 2023-07-04 23:28
@joekaufmanexpensify did you say we have a P2P master issue somewhere we can file this for testing closer to release? I think this is not really a bug we'll figure out until then.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 12:46
Yep, it's [here](https://github.com/Expensify/Expensify/issues/207285)!

**Comment by twisterdotcom** [comment] 2023-07-05 14:50
Nice just added this to the polish section. Going to close this out for now.

**Closed by twisterdotcom** 2023-07-05 14:50 UTC
Labels: Daily, Needs Reproduction, Bug
