### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Error highlighting inconsistent when using 'Fix errors' link

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20869] opened 2023-06-15 21:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings.
2. Go to your workspace.
3. Navigate to 'Travel' and connect bank account manually.
4. Add Routing number (074000078) and Account number (1234), then try to continue without accepting the terms.
5. The error will appear, and when clicking on the "Fix errors" link, it does not focus on the error.

## Expected Result: 
The app should highlight specific errors for the user when they do not accept the terms and an error occurs, similar to how it directs the user to specific errors and highlights them when issues occur with Routing and Account numbers.
## Actual Result: 
When the user doesn't accept the terms and an error occurs, clicking on the 'Fix errors' link doesn't highlight them.
- This causes confusion since the app highlights specific errors when issues occur with Routing and Account numbers.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (72).webm](https://github.com/Expensify/App/assets/43996225/1386db3b-d044-4e6b-8416-714103093f37)

https://github.com/Expensify/App/assets/43996225/35272f6a-68cb-4273-b24d-42354484cabd

https://github.com/Expensify/App/assets/43996225/35272f6a-68cb-4273-b24d-42354484cabd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686296570841189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b233772b18dcdce</li>
        <li>Upwork Job ID: 1669783824811683840</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-06-19 17:51
@mollfpr bump on reviewing [this proposal ](https://github.com/Expensify/App/issues/20869#issuecomment-1593935759)

**Comment by wildan-m** [comment] 2023-06-19 21:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error highlighting is inconsistent when using 'Fix errors' link in the checkbox component

### What is the root cause of that problem?
Checkbox have the focus but it doesn't have focus styling

### What changes do you think we should make in order to solve the problem?
Users can easily notice the pointer when the error is from textInput component, but checkbox doesn't have a cursor.

To mimic a similar cursor pointer, we can add a slight animation to the checkbox when it `hasError` and `isFocused`.

We can add this snippet to our `Checkbox` component.

```
 const [isFocused, setIsFocused] = useState(false);
    const borderColorValue = useRef(new Animated.Value(0)).current;
    const blinkingAnimation = useRef(Animated.loop(
        Animated.sequence([
          Animated.timing(borderColorValue, {
            toValue: 1,
            duration: 0,
            useNativeDriver: false,
          }),
          Animated.delay(500),
          Animated.timing(borderColorValue, {
            toValue: 0,
            duration: 0,
            useNativeDriver: false,
          }),
          Animated.delay(500),
        ]),
        { iterations: -1 }
      )).current;


    
    useEffect(() => {
      if (props.hasError && isFocused) {
        startBlinking();
      } else {
        stopBlinking();
      }
    }, [props.hasError, isFocused]);
  
    const startBlinking = () => {
        blinkingAnimation.start();
    };
  
    const stopBlinking = () => {
        blinkingAnimation.stop();
        blinkingAnimation.reset();
        borderColorValue.setValue(0);
    };
  
    const handleFocus = () => {
      setIsFocused(true);
    };
  
    const handleBlur = () => {
      setIsFocused(false);
    };
  
    const interpolatedColor = borderColorValue.interpolate({
      inputRange: [0, 1],
      outputRange: [styles.borderFocus, styles.borderColorDanger.borderColor], // Customize the border color here
    });
```

We can adjust the animation loop (e.g. twice) if infinite blinking is too much

### Result

https://github.com/Expensify/App/assets/11847279/1d2cc325-e5ad-4fe8-942b-c1de477dbb82


### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2023-06-20 13:57
Thanks @wildan-m for other suggestion!

Do you have an example for other applications that use the same approach?

**Comment by wildan-m** [comment] 2023-06-20 21:38
@mollfpr not exactly the same case but I just found that this [mui sample page](https://mui.com/material-ui/react-checkbox/) use pulsating animation when the checkbox focused

https://github.com/Expensify/App/assets/11847279/2caa01fe-14c0-447b-a560-13f724ca062d

**Comment by marcochavezf** [comment] 2023-06-22 22:39
Oh the animation is an interesting effect, but I think we should discuss it widely on the [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) channel since it introduces a new UI pattern that we would need to change in different places. Thanks for posting that proposal @wildan-m, feel free to post in the channel to discuss with the community.

Meanwhile, I will assign @allroundexperts here with the approved proposal 🚀 Thanks for the review @mollfpr!

**Comment by NicMendonca** [comment] 2023-06-23 19:30
@mallenexpensify I am going OOO until Wednesday. Can you watch this while I am away? I'll unassign you when I am back. Thank you!

**Comment by NicMendonca** [comment] 2023-06-30 20:30
^ not overdue

**Comment by iwiznia** [comment] 2023-07-03 16:45
This was reverted here https://github.com/Expensify/App/pull/22124 because it caused this regression https://github.com/Expensify/App/issues/22119

**Comment by iwiznia** [comment] 2023-07-03 16:59
Some conversation here  https://expensify.slack.com/archives/C01GTK53T8Q/p1688401889214749
IMO we added this inconsistency between platforms and I don't think we should've done that.

**Comment by tewodrosGirmaA** [comment] 2023-07-13 09:45
@mallenexpensify , Hello

**Comment by tewodrosGirmaA** [comment] 2023-07-13 09:52
@mallenexpensify, am I eligible for payment?

**Comment by NicMendonca** [comment] 2023-07-14 08:56
@tewodrosGirmaA This shouldn't have been a bug in the first place. It was our bad for not paying attention that it was a consistency in different platforms and could cause a regression. Closing!

**Closed by NicMendonca** 2023-07-14 08:56 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
