### ISSUE TITLE
[HOLD for payment 2023-09-12] Dev: Web - Request button in the wrong position

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26418] opened 2023-08-31 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Click the + icon from LHN
3. Click request money
4. Enter the amount and click next
5. Observe the Request button from cash detail

## Expected Result:
The Request button should be at the bottom

## Actual Result:
The request button is in the wrong position

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.60.1
**Reproducible in staging?:** no
**Reproducible in production?:** no
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/0b6d9bb3-aac9-43ef-9d6b-af619255d671

**Expensify/Expensify Issue URL:**
**Issue reported by:** @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693502582644489

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by misgana96** [comment] 2023-09-01 16:30
It is reproducible in staging too for the latest version v1.3.61-2
[Screencast from 01-09-2023  7:28:50 ከሰዓት.webm](https://github.com/Expensify/App/assets/48551032/64f184e2-11f0-4d38-832f-7b237aca12f1)

**Comment by BhuvaneshPatil** [comment] 2023-09-01 19:01
## Proposal
Can create a PR ASAP if required

### Please re-state the problem that we are trying to solve in this issue.
Next button while creating split bill is not at bottom

### What is the root cause of that problem?
Regression from #26179
Because of added ScrollView, it's not taking full height.

### What changes do you think we should make in order to solve the problem?
We should make this flex grow

in `MoneyRequestConfirmPage`
```js
<ScrollView contentContainerStyle={[styles.flexGrow1]}>
                        <ScrollView
                            horizontal
                            contentContainerStyle={[styles.flex1, styles.flexColumn]}
                        >
```
result - 
<img width="830" alt="Screenshot 2023-09-02 at 12 18 31 AM" src="https://github.com/Expensify/App/assets/27822551/338cff1b-5301-47bd-a29b-bf44f8ff4d9c">

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-09-02 14:46
@tjferriss Can you please close this one? We will handle this in https://github.com/Expensify/App/issues/26544

**Comment by misgana96** [comment] 2023-09-02 14:57
@s77rt Why do we close this one? since #26544  is a dupe of #26418

**Comment by s77rt** [comment] 2023-09-02 14:59
@misgana96 No specific reason except that I'd like to work on the other issue and this one is not assigned to anyone. You'd be still the bug reporter for the other issue.

**Comment by misgana96** [comment] 2023-09-02 15:01
@s77rt Thank you for your quick response

**Comment by neil-marcellini** [comment] 2023-09-04 14:45
Even though this issue was first I'm closing it in favor of https://github.com/Expensify/App/issues/26544 since we have already started fixing it over there.

**Comment by misgana96** [comment] 2023-09-16 17:57
@marcaaron @tjferriss The payment was scheduled for 2023/09/12 if there is no regression. Can you process the payment, please? It is almost 11 days since the PR was deployed to production, and I haven't received the payment for the bug reporter. Thank you

**Comment by misgana96** [comment] 2023-09-22 10:19
@marcaaron @tjferriss still waiting for your response. It is almost 16 days since it merged in the production but payment not processed still now.

**Comment by marcaaron** [comment] 2023-09-25 04:57
Not involved in the payments system. I will reopen it so that @tjferriss can take a look though.

**Comment by misgana96** [comment] 2023-09-25 05:46
> Not involved in the payments system. I will reopen it so that @tjferriss can take a look though.

Thank you

**Comment by tjferriss** [comment] 2023-09-25 07:16
@misgana96 sorry for the delay. Let's get you paid. I just sent an offer via Upworks: https://www.upwork.com/jobs/~01f0919fe7166fcdbe.

**Comment by tjferriss** [comment] 2023-09-26 07:39
Payment has been sent to @misgana96

**Closed by tjferriss** 2023-09-26 07:39 UTC
Labels: Weekly, Needs Reproduction, Awaiting Payment, Bug

**Comment by misgana96** [comment] 2023-09-26 08:09
Accepted. Thank you
