### ISSUE TITLE
JS console error message displayed for chronos

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44660] opened 2024-06-29 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @rafecolton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1719522042334589

## Action Performed:
1. Go to staging.new.expensify.com
2. Initiate a chat with Chronos
## Expected Result:
No console error displayed
## Actual Result:
Console error displayed
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Screenshot 2024-06-27 at 1 59 57 PM](https://github.com/Expensify/App/assets/38435837/ceb187fe-da1e-4874-8867-0b7239cc9004)
![Screenshot 2024-06-27 at 2 00 48 PM](https://github.com/Expensify/App/assets/38435837/5ae8722a-f283-4077-95cd-06208822fb27)

![Production](https://github.com/Expensify/App/assets/38435837/876352e8-9f6c-48f9-8924-97ae8b55d985)
![Staging](https://github.com/Expensify/App/assets/38435837/dbf52c23-3831-4410-a6a6-d37504527ec5)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bbd4ecc222ba2d37</li>
        <li>Upwork Job ID: 1807900884343246877</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by jacobkim9881** [comment] 2024-06-30 23:51
I think this issue shouldn't be solved from FE.

**Comment by VictoriaExpensify** [comment] 2024-07-01 22:15
I've looked at the [Slack thread](https://expensify.slack.com/archives/C049HHMV9SM/p1719522042334589) and it seems we agree this is an issue.

Since this is chat related, but not expense relates, I think this belongs to #VIP-VSB

**Comment by jacobkim9881** [comment] 2024-07-02 06:32
@allgandalf Add chronos@expensify.com

**Comment by jacobkim9881** [comment] 2024-07-02 06:44
@allgandalf Yes, it was reproducible. I only got an error console starting with "Refuse to execute..." but not last error starting with "FullStory orgId..." as I remember.

**Comment by VictoriaExpensify** [comment] 2024-07-03 04:48
>@VictoriaExpensify , how do we initiate a chat with chronos?, having hard time searching for it

@allgandalf It looks like @jacobkim9881 helped you out with that - did that work for you?

**Comment by VictoriaExpensify** [comment] 2024-07-09 00:01
Ohhhh I don't think I should have made this an External issue - sorry, I'm still quite new to BZ. I'm going to make this an internal issue and see if we can get some traction.

**Comment by jacobkim9881** [comment] 2024-07-16 00:50
@allgandalf  I think I saw @VictoriaExpensify went out from slack channel.

**Comment by mvtglobally** [comment] 2024-08-03 04:11
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-08-09 04:27
Issue not reproducible during KI retests. (Second week)

**Comment by VictoriaExpensify** [comment] 2024-08-15 02:02
I think we can close this out. @rafecolton you reported this issue initially so please reopen if you can still reproduce and think it needs attention

**Closed by VictoriaExpensify** 2024-08-15 02:02 UTC
Labels: Weekly, Internal, Help Wanted, Overdue, Bug, Hot Pick
