### ISSUE TITLE
[$500]  IOU -The category dropdown options can not be switched via tab key

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35491] opened 2024-01-31 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
Prerequisite: Collect policy and Categories are setup in Olddot
1. Login ND Expensify
2. Start an IOU request on the workspace chat
3. Enter an amount and continue
4. Click on "show more"
5. Click on the "Category" field
6. Verify the search is focused
7. Press tab key to switch between categories dropdown options

## Expected Result:
User can switch categories dropdown options via tab key

## Actual Result:
The first option is selected with blue borderline and subsequent tab key press does nothing

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e127f0dc-da38-414e-86cc-47a75cf06ac7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011045bbd241e57e38</li>
        <li>Upwork Job ID: 1752737524806991872</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-01-31 16:56
we think it could be #wave6-collect-submitters cc @greg-schroeder

**Comment by FitseTLT** [comment] 2024-01-31 17:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The category dropdown options can not be switched via tab key

### What is the root cause of that problem?
We haven't passed `tab-index` to pressable to the option rows
### What changes do you think we should make in order to solve the problem?

We need to pass `tab-index` to pressable to the option rows
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-01-31 21:56
I [don't think](https://expensify.slack.com/archives/C01GTK53T8Q/p1701968767957349?thread_ts=1668604822.482759&cid=C01GTK53T8Q) we are fixing these types of issues until there is a standard framework for how keyboard navigation works in the app. As right now, this behavior is not consistent everywhere. 

Closing.

**Closed by joekaufmanexpensify** 2024-01-31 21:56 UTC
Labels: External, Daily, Help Wanted, Bug
