### ISSUE TITLE
[$500] BA - Validate code was entered more then 20 times, error message was not shown in most cases

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29832] opened 2023-10-17 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.85-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Can not check BA connection in production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com or open iOS or Desktop App
2. Create new workspace or go to existing one
3. Go to Settings > Workspace > Bank Account > Connect Manually
4. Follow the flow until the "Test transaction" step
5. Submit three random amounts and Verify that you see the following error: The validate code you entered is incorrect, please try again
6. Submit the amounts 7 more times (9 attempts in previous test cycles) and Verify that the validation has been disabled due too many attempts

## Expected Result:
5. The user receives an error message.
6. After the 9th attempt, validation is blocked

## Actual Result:
5. Most validation attempts did not display an error message.
6. Validation blocked after more than 20 attempts

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/78819774/5ab40d7e-f690-4d3e-bded-d0af0bdac4b1

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/f907fd33-0559-49af-8e42-a125ad51817c

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/78819774/bac3c9e2-49b1-4c16-9749-09b556d3386d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a443e9d9fdcb80c2</li>
        <li>Upwork Job ID: 1714392323287330816</li>
        <li>Last Price Increase: 2023-11-07</li>
    </ul>
</details>

**Comment by kevin-williams** [comment] 2023-10-18 07:32
**Proposal**

**Please restate the problem that we are trying to solve in this issue**

Validation code for number of attempts is not keeping track properly so more attempts can be done than should be allowed.

**What is the root cause of that problem**

The validation call is an asynchronous call, but the validation logic is not accounting for that.  So you can do a second call before the first one has totally finished and updated the state. So something like this
Call 1 -> failure
Call 2 before Call 1 finishes -> failure, but call failure state only set to 1 in Onyx.

**What changes do you think we should make in order to solve the problem**

add a useState variable on the ValidateStep.js file for validationInProgress.   Set to true when submit is called, but only set to false once the isLoading variable on the reimbursement account goes back to false.  Use a useEffect that checks validationInProgress is true and isLoading is false to set validationInProgress back to false. 

Then disable the validate button while validationInProgress is true.  isDisabled={validationInProgress}
I would also have submit return immediately if validationInProgress is true to safeguard it.

That will now ensure that the validation step is complete before another is attempted which will allow the state to be updated, so an accurate count of attempts is maintained.  Also this will ensure that the error has time to happen and be shown.

**What alternatives did you explore?**

**Comment by kevin-williams** [comment] 2023-10-19 06:23
@lanitochka17 Is there a set of test data I can use to get successfully past the manual validation so I can test it?  The bank id, tax id, biz address, that sort of thing?  I would like to validate my fix.   I guessed at info, but am now stuck at needed to chat to someone to finish.

Thank you!

**Comment by greg-schroeder** [comment] 2023-10-23 10:17
Awaiting proposal review

**Comment by greg-schroeder** [comment] 2023-10-26 00:04
@jjcoffee is up!

**Comment by jjcoffee** [comment] 2023-10-26 09:19
@greg-schroeder I have the same [question](https://github.com/Expensify/App/issues/29832#issuecomment-1770139412) as @kevin-williams, as well as generally what the best way to test adding manual bank accounts is!

**Comment by lanitochka17** [comment] 2023-10-30 21:22
@kevin-williams Hello
Unfortunately, hor testing we do not use: bank id, tax id, biz address

**Comment by kevin-williams** [comment] 2023-10-31 03:38
So, how do you get to the needed screen to test?

I think I have the solution but need to verify it so need more detailed test steps to get to the failure point.

I can manually override the code to get past the checks but that doesn't seem wise as it might effect the code we are testing.

**Comment by kevin-williams** [comment] 2023-10-31 14:40
I updated my proposal.   https://github.com/Expensify/App/issues/29832#issuecomment-1767839491

I did modify the variables so I could at least get to the screen.  And yes it was as I thought, the validate form is shown before the validate API call finishes.   I did update my proposal to make it even easier.   Just add one more condition before showing the validate form.

{!maxAttemptsReached && state === BankAccount.STATE.PENDING && **!reimbursementAccount.loading** (
           
So while the validate step is being processed, the form is shown and the loading modal stays so you can't submit 2 validation attempts at once.

**Comment by greg-schroeder** [comment] 2023-11-01 11:05
@jjcoffee I'm not honestly sure - perhaps we can start a discussion in the Slack room to make sure this information is disseminated?

**Comment by mvtglobally** [comment] 2023-11-02 03:28
Issue not reproducible during KI retests. (First week)

**Comment by jjcoffee** [comment] 2023-11-03 15:53
@kevin-williams Are you still able to reproduce this?

**Comment by kevin-williams** [comment] 2023-11-04 05:12
It is a race condition so a throttled internet connection would help.   Set it to 3g in the browser and you probably can reproduce it.

I could not totally reproduce it as I modified the code to get to the 3 amount entry screen, but could see that I was able to submit another attempt before the previous one finished.

Once I  put the fix in I no longer could.

**Comment by jjcoffee** [comment] 2023-11-08 16:04
Hmm I wonder if this is too hard to reproduce if it's worth fixing? cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2023-11-09 11:31
Yeah I can't repro and neither can QA ... let's just close this.

**Closed by greg-schroeder** 2023-11-09 11:31 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
