### ISSUE TITLE
Web - Request money details are missing if money requested in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26115] opened 2023-08-28 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. go to offline
2. go to an chat
3. click on request money
4. enter money and request money
5. go to transaction thread

## Expected Result:
should show request money details

## Actual Result:
request money details are missing

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.58.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/de8ee21c-7ee2-466a-b73b-086cdaac65bb

https://github.com/Expensify/App/assets/93399543/44efb2f2-9a33-4107-abc3-d60153ed1083

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693201810929339

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-08-28 19:04
BTW @yuwenmemon this seems to be happening in dev only

**Comment by gadhiyamanan** [comment] 2023-08-28 19:07
@luacmartins right now it's reproducible in staging

**Comment by yuwenmemon** [comment] 2023-08-28 21:42
Yeah I can see this on staging

**Comment by yuwenmemon** [comment] 2023-08-28 21:51
I'm pretty sure this is coming from https://github.com/Expensify/App/pull/25429 cc @vitHoracek @rushatgabhane @grgia

**Comment by yuwenmemon** [comment] 2023-08-28 22:40
Hmmm... Can't seem to figure out why 🤔

**Comment by mountiny** [comment] 2023-08-28 23:06
Can you check if this fixes it https://github.com/Expensify/App/pull/26118?

**Comment by mountiny** [comment] 2023-08-28 23:07
I should be able to look at this tomorrow morning.

cc @alitoshmatov might also be able to look

**Comment by yuwenmemon** [comment] 2023-08-28 23:36
Ah yep, this will be fixed by https://github.com/Expensify/App/pull/26118

**Comment by yuwenmemon** [comment] 2023-08-29 02:52
Fix has been CP'd to staging. Closing

**Closed by yuwenmemon** 2023-08-29 02:52 UTC
Labels: DeployBlockerCash, Engineering, Hourly
