### ISSUE TITLE
[$500] mWeb - Login - With input field focused & scroll down, blank white space appears above keypad

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35521] opened 2024-01-31 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.34-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap on email/phone input field
3. With the keypad active, scroll down the log in page

## Expected Result:
No blank white space appears above keypad when login page scrolled down

## Actual Result:
With input field focused & scroll down login page, blank white space appears above keypad

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/06fcfe51-a709-4271-80f0-ca95fc66f95f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb73e43a4d3be18a</li>
        <li>Upwork Job ID: 1752809330009219072</li>
        <li>Last Price Increase: 2024-02-21</li>
    </ul>
</details>

**Comment by BryceAltman** [comment] 2024-02-01 04:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty space can be seen at the bottom of the screen on login page, when email input is focused.

### What is the root cause of that problem?
On small screen sizes, two scroll views are rendered and are overlapping, this is causing the strange behaviour when scrolling to the bottom of the screen. 

I reproduced the issue and also confirmed to be appearing in other browsers, sometimes with different behaviour. The screenshot below shows the double scrollable area, note the two scroll bars on the right.

![IMG_0825](https://github.com/Expensify/App/assets/7864862/5b2917d8-c84d-45a2-bc01-0fcf7fee7fdb)


### What changes do you think we should make in order to solve the problem?
Double ScrollView can be seen here [https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/signin/SignInPageLayout/index.js#L118](url)

Both areas do not need to be independently scrollable, removing one of them should fix the issue on small screens and will not affect larger screen sizes.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2024-02-01 17:20
>Double ScrollView can be seen here

@BryceAltman But on the small screen we don't use a double scroll view as you mention, no?

**Comment by BryceAltman** [comment] 2024-02-02 00:13
> > Double ScrollView can be seen here
> 
> @BryceAltman But on the small screen we don't use a double scroll view as you mention, no?

On line 118 the first ScrollView is closed and on the next line 119 another one is created. These ScrollViews overlap when the keyboard is present causing this behaviour

**Comment by mollfpr** [comment] 2024-02-02 12:14
https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/signin/SignInPageLayout/index.js#L102-L119

@BryceAltman I mean the line you mention seems not rendered on the small screen device. While the small screen doesn't use two scroll view.

https://github.com/Expensify/App/blob/889051cf6c155c225a9c602c17d95ec40d740839/src/pages/signin/SignInPageLayout/index.js#L158-L187

**Comment by mollfpr** [comment] 2024-02-05 16:47
Not overdue

**Comment by mollfpr** [comment] 2024-02-08 16:58
Waiting for better proposals.

**Comment by mollfpr** [comment] 2024-02-12 16:21
No new proposals.

**Comment by mollfpr** [comment] 2024-02-15 17:24
No new proposals!

**Comment by mollfpr** [comment] 2024-02-20 18:23
@suneox Could you elaborate more why we should use `ScreenWrapper`? And why this is only occurring on the safari?

**Comment by mollfpr** [comment] 2024-02-22 12:23
@suneox Why do we need to create props for the `SignInPage`?

**Comment by mollfpr** [comment] 2024-02-26 09:35
Not overdue, waiting for new proposals and contributor feedback.

**Comment by mollfpr** [comment] 2024-03-04 14:33
@anmurali We can close this issue. This issue solved here https://github.com/Expensify/App/issues/36515

**Closed** 2024-03-07 00:25 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
