### ISSUE TITLE
[Testrail?] Markdown - Bold and Italic markdowns are not applied on links and emails

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46309] opened 2024-07-26 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.13-2
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4774425
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify
2. Navigate to any chat
3. Send a message with link or email with bold or italic markdown, e. g. [_italic@mail.com_](mailto:_italic@mail.com_)

## Expected Result:
Message should be sent and appropriate markdown should be correctly applied

## Actual Result:
Message is sent but markdown is not applied. It is only visible when drafting or editing the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/e29c1075-3245-4fef-b50e-70da64c800e7

![Bug6553697_1721999487363!obraz](https://github.com/user-attachments/assets/6a351e63-803d-408b-8030-465db38a4c8e)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by lanitochka17** [comment] 2024-07-26 14:24
@mallenexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-26 14:25
We think that this bug might be related to  #Live Markdown

**Comment by rlinoz** [comment] 2024-07-26 15:13
The HTML comes back correctly from the AddComment command, so not backend.

**Comment by rlinoz** [comment] 2024-07-26 15:28
Tested a local revert and it is coming from here https://github.com/Expensify/App/pull/41115

cc: @fabioh8010 @mollfpr

**Comment by kpadmanabhan** [comment] 2024-07-26 16:35
@lanitochka17 / @mallenexpensify : unable to repro this in main HEAD. was there a fix that laready went in?

![image](https://github.com/user-attachments/assets/5f36e169-ac4c-4a3b-964d-cd77cf693fd9)

**Comment by rlinoz** [comment] 2024-07-26 16:40
Hmm, still reproduceable in latest main:

<img width="1041" alt="image" src="https://github.com/user-attachments/assets/4027b02f-ca03-4db1-b917-00e862f23421">

**Comment by kpadmanabhan** [comment] 2024-07-26 17:04
> Tested a local revert and it is coming from here #41115
> 
> cc: @fabioh8010 @mollfpr

@rlinoz : sorry, you are right. mine was yesterday night's HEAD. I see that #41115 went in 20 hrs ago. 
i am able to repro this in main HEAD. 
in fact earlier italic and bold text also is re-formatted due to trhe processing of received data from backend.
also this is happening only for links (http: or mailto:)

![image](https://github.com/user-attachments/assets/b1f81f4a-cc99-48cf-937f-64623b87f966)

@mollfpr / @fabioh8010 / @mallenexpensify : pls let me know if you are making this external, in which case I can pick this up for fixing.

**Comment by rlinoz** [comment] 2024-07-26 17:21
I gotta go, but I think this is not necessarily a blocker and I am not eager to revert that big PR..

Thoughts @roryabraham @francoisl ?

**Comment by roryabraham** [comment] 2024-07-26 17:52
agree, nab

**Comment by roryabraham** [comment] 2024-07-26 17:52
cc @fabioh8010 can you look into this one please?

**Comment by fabioh8010** [comment] 2024-07-26 17:53
Will look now

**Comment by fabioh8010** [comment] 2024-07-26 18:29
Found the problem and fix, will open PR soon.

**Comment by fabioh8010** [comment] 2024-07-26 19:16
PR is up -> https://github.com/Expensify/App/pull/46322

**Comment by rlinoz** [comment] 2024-07-29 13:32
Didn't mean to close it.

**Comment by mallenexpensify** [comment] 2024-08-08 23:10
Contributor+: @rushatgabhane owed $250 via NewDot

@rushatgabhane , think we want a test case for this?  It might fall under some version of "when text is marked bold or italic, it should as bold or italic"

**Comment by JmillsExpensify** [comment] 2024-08-08 23:22
$250 approved for @rushatgabhane

**Comment by mallenexpensify** [comment] 2024-08-12 21:06
@rushatgabhane , from above:
> @rushatgabhane , think we want a test case for this? It might fall under some version of "when text is marked bold or italic, it should as bold or italic"

**Comment by rushatgabhane** [comment] 2024-08-12 21:13
@mallenexpensify i think this comes under verify that markdown style is correct.

Don't think we need to add a test for it. Any PR modifying the fonts will have tests for it

**Closed** 2024-08-13 22:02 UTC
Labels: Engineering, Daily, Awaiting Payment
