### ISSUE TITLE
[HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [$500] IOS - Task - Unable to scroll down task description

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41567] opened 2024-05-03 10:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4538850
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app and log in
2. Tap FAB > Assign task
3. Enter any title and add a long comment
4. On the confirmation screen open the the description and scroll down
5. Finish creating a task
6. Open the created task and tap the description
7. Scroll down

## Expected Result:
User is able to scroll down the task descriptionUser is able to scroll down the task description

## Actual Result:
User is unable to scroll down the task description on the task confirmation screen and in created task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6b2c0f4d-3003-4ad0-8823-ff6b518d176c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180926895abca5e37</li>
        <li>Upwork Job ID: 1786441016250023936</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102536438</li>
<li>QichenZhu | Contributor | 102536440</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by izarutskaya** [comment] 2024-05-03 10:28
We think this issue might be related to the #vip-vsb.

**Comment by zanyrenney** [comment] 2024-05-03 17:01
nice, we should be able to scroll 100% so this is a bug.

**Comment by zanyrenney** [comment] 2024-05-03 17:01
Adding external

**Comment by samilabud** [comment] 2024-05-04 02:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Unable to scroll down task description

### What is the root cause of that problem?
This situation occurs on IPhone/IOS due to the way scrolls work by default, they are automatically hidden and if like in this case if you are using an IPhone and scroll the parent component all the children transform their behavior temporarily (about 1s) to be scrollable and each one hides its own scrollbar. 

### What changes do you think we should make in order to solve the problem?
This could be something that can not fixed at 100%, but we can control it putting the [input description](https://github.com/Expensify/App/blob/main/src/pages/tasks/NewTaskDescriptionPage.tsx) inside a ScrollView and disabling the scroll like:

```
<ScrollView
                style={styles.flex1}
                scrollEnabled={false}
            >
```

Tests:
Before changes (Please note that if you wait a second you will be able to scroll):

https://github.com/Expensify/App/assets/5216036/ea870160-05d0-4724-8997-c8b50ce23399

After changes:

https://github.com/Expensify/App/assets/5216036/574c33f1-510e-4223-a2ec-38ee3b11baea

**Comment by hungvu193** [comment] 2024-05-06 02:45
Thanks everyone! For more context, we have another similar issue related to `MarkDownTextInput` [here](https://github.com/Expensify/App/issues/40994), please see [this comment](https://github.com/Expensify/App/issues/40994#issuecomment-2078693365),
We also having a PR to fix that issue here: https://github.com/Expensify/App/pull/41103. So, the ideal solution should aim to fix the issue with `MarkDownTextInput` rather than remove it.

**Comment by samilabud** [comment] 2024-05-06 03:58
## Proposal
[Updated](https://github.com/Expensify/App/issues/41567#issuecomment-2093969164)

**Comment by hungvu193** [comment] 2024-05-07 03:15
I can not reproduce this issue on latest (after react-native-live-markdown is updated).

https://github.com/Expensify/App/assets/16502320/7d8cd72c-2984-4391-82e0-db4cb0cae70b

**Comment by zanyrenney** [comment] 2024-05-09 13:59
Nice @hungvu193 - we can close this one out then 🎉

**Comment by samilabud** [comment] 2024-05-09 17:08
Hi @zanyrenney and @hungvu193, it is reproducible, the test should start by trying to scroll first from the middle (or any other side - outside of the input) of the screen and then you should try to edit the description (see my root cause y my [proposal](https://github.com/Expensify/App/issues/41567#issuecomment-2093969164))

<details>
<summary>**Tests v1.4.72**</summary>

https://github.com/Expensify/App/assets/5216036/fd5231a2-f5b7-44df-8b12-6971df3c957e

Version:
<img width="373" alt="image" src="https://github.com/Expensify/App/assets/5216036/60533f6d-a6b0-4f64-a283-76d89103ff5e">
</details>

**Comment by lanitochka17** [comment] 2024-05-14 00:06
Issue is still reproducible on the latest build 1.4.73-0

https://github.com/Expensify/App/assets/78819774/6b42c389-a612-4108-b22b-fa241980e618

**Comment by zanyrenney** [comment] 2024-05-17 14:51
I can still reproduce!

**Comment by zanyrenney** [comment] 2024-05-17 14:51
adding external

**Comment by zanyrenney** [comment] 2024-05-17 14:51
@hungvu193 can you please review the proposal?

**Comment by hungvu193** [comment] 2024-05-17 14:52
Yeah sure. I can reproduce on latest main

**Comment by zanyrenney** [comment] 2024-05-17 15:00
thanks!

**Comment by hungvu193** [comment] 2024-05-18 00:37
I'll take a look this weekend

**Comment by hungvu193** [comment] 2024-05-18 11:11
Thanks @suneox and @samilabud, I feel both proposals are workaround to me.
Still waiting for proposal.

**Comment by samilabud** [comment] 2024-05-18 11:38
> Thanks @suneox and @samilabud, I feel both proposals are workaround to me. Still waiting for proposal.

Got it, but this is not a bug is the usual behavior of the OS, I think only workarounds going to work.

**Comment by hungvu193** [comment] 2024-05-18 11:41
This bug only happens after we switch to use MarkdownTextInput. So again as I mentioned above ideal solution will aim to fox MarkdownTextInput

**Comment by samilabud** [comment] 2024-05-18 11:47
> This bug only happens after we switch to use MarkdownTextInput. So again as I mentioned above ideal solution will aim to fox MarkdownTextInput

Good to know thanks, I'm going to do some tests then and let you know.

**Comment by samilabud** [comment] 2024-05-18 12:50
@hungvu193 as you can see in the video below, I have removed the MarkdownTextInput, I left a normal textinput (from react native) and I start scrolling first (for more details see my root cause explanation [here](https://github.com/Expensify/App/issues/41567#issuecomment-2093969164)) and then try to click on the TextInput to edit but I only get the scrolling behavior:

https://github.com/Expensify/App/assets/5216036/928ba2b6-b98b-45c5-97dd-0c99765fab6e

**Comment by hungvu193** [comment] 2024-05-21 08:55
Little bump @zanyrenney

**Comment by zanyrenney** [comment] 2024-05-21 09:17
increased!

**Comment by hungvu193** [comment] 2024-05-22 10:30
Still waiting for proposals

**Comment by hungvu193** [comment] 2024-05-24 02:45
Same

**Comment by hungvu193** [comment] 2024-05-27 01:50
Same here. Still waiting for proposals

**Comment by hungvu193** [comment] 2024-05-28 16:08
Bumped on Slack

https://expensify.enterprise.slack.com/archives/C01GTK53T8Q/p1716538433440779

**Comment by QichenZhu** [comment] 2024-05-29 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task description is sometimes not scrollable.

### What is the root cause of that problem?
`react-native-live-markdown` switches  the text view into TextKit 1 compatibility mode at [this line](https://github.com/Expensify/react-native-live-markdown/blob/6541a6ea44785d3e3de8fc83ac085963fea30829/ios/MarkdownTextInputDecoratorView.mm#L74), and the content height changes after the switch.

We can add logs to verify this:

```objc
RCTLogWarn(@"Before: %g, %g", _textView.contentSize.width, _textView.contentSize.height);
NSLayoutManager *layoutManager = _textView.layoutManager; // switching to TextKit 1 compatibility mode
RCTLogWarn(@"After: %g, %g", _textView.contentSize.width, _textView.contentSize.height);
```
<img width="552" alt="Screenshot 2024-05-30 at 4 04 41 AM" src="https://github.com/Expensify/App/assets/57348009/db282825-ec29-4302-8c1c-49d9557a71e2">

### What changes do you think we should make in order to solve the problem?
Saving the content size before switching to TextKit 1 compatibility mode and resetting it after the switch.
```objc
CGSize previousContentSize = _textView.contentSize;
NSLayoutManager *layoutManager = _textView.layoutManager; // switching to TextKit 1 compatibility mode
[_textView setContentSize: previousContentSize];
```

(After `react-native-live-markdown` [migrates to TextKit 2](https://github.com/Expensify/react-native-live-markdown/issues/145), we can re-test and remove this fix if it is no longer needed.)

### What alternative solutions did you explore? (Optional)
N/A

**Comment by QichenZhu** [comment] 2024-05-29 17:18
## Proposal
[Updated](https://github.com/Expensify/App/issues/41567#issuecomment-2137792675)

**Comment by hungvu193** [comment] 2024-05-30 02:38
Unfortunately, I can't reproduce it now, Can you reproduce the issue on your simulator?
I can reproduce this issue on Testflight version but can't reproduce on main

https://github.com/Expensify/App/assets/16502320/27df74b9-f51a-4faf-9447-44eb650049ba

**Comment by samilabud** [comment] 2024-05-30 03:04
> I can't reproduce it now

You should start scrolling first (for more details see my root cause explanation https://github.com/Expensify/App/issues/41567#issuecomment-2093969164) and then try to click on the TextInput to edit the text.

**Comment by hungvu193** [comment] 2024-05-30 03:09
Still the same. I can reproduce this one on TF version, so not sure if there's any current change that fixed this one?

https://github.com/Expensify/App/assets/16502320/77aff8cb-dbb7-4e38-81d0-601f33c25982

**Comment by QichenZhu** [comment] 2024-05-30 03:19
@hungvu193 I can reproduce it with a shorter text than your test data.

https://github.com/Expensify/App/assets/57348009/f55b203e-e202-4a79-ad6e-1f91115551c1

**Comment by hungvu193** [comment] 2024-05-30 03:22
@QichenZhu  I think that the different thing between your video and mine is the textinput in my video scrolled to the bottom meanwhile your textinput didn't do it. 
What's your `react-native-live-markdown` version? Here's is what I'm using:
` "@expensify/react-native-live-markdown": "0.1.70",`

**Comment by QichenZhu** [comment] 2024-05-30 03:29
@hungvu193 I can observe the same expected behavior using the same data as you.


https://github.com/Expensify/App/assets/57348009/d786609d-885f-4bc8-b3c5-dc92b46dec9a



I'm using version `0.1.76` from `package.json` of `main`.

https://github.com/Expensify/App/blob/f6aa6c20a18e2d64f3143815f5266d064ce7cb6a/package.json#L68

**Comment by hungvu193** [comment] 2024-05-30 04:00
Yeah, you're right, I can now reproduce with the issue. I will do a quick review now.

https://github.com/Expensify/App/assets/16502320/32cb3cd3-d7bd-4487-b0c9-3a9d76b7be3c

**Comment by hungvu193** [comment] 2024-05-30 06:29
@QichenZhu [Your main proposal](https://github.com/Expensify/App/issues/41567#issuecomment-2137792675) looks good to me. Given that `width` doesn't change after we switch to TextKit 1 compatibility mode, may be we should only need to correct the height?

**Comment by QichenZhu** [comment] 2024-05-30 06:59
## Proposal
[Updated](https://github.com/Expensify/App/issues/41567#issuecomment-2137792675)

**Comment by hungvu193** [comment] 2024-05-30 07:02
@QichenZhu 's [proposal here](https://github.com/Expensify/App/issues/41567#issuecomment-2137792675) looks good to me! 🎀 👀 🎀  C+ reviewed

**Comment by QichenZhu** [comment] 2024-05-30 07:03
@hungvu193 Thanks for your review and advice.

**Comment by QichenZhu** [comment] 2024-05-31 05:57
Thanks you! @hungvu193 @madmax330 What's the next step? Should I submit a PR to the [`react-native-live-markdown`](https://github.com/Expensify/react-native-live-markdown) project?

**Comment by hungvu193** [comment] 2024-05-31 05:58
> Thanks you! @hungvu193 @madmax330 What's the next step? Should I submit a PR to the [`react-native-live-markdown`](https://github.com/Expensify/react-native-live-markdown) project?

Yes please go ahead

**Comment by hungvu193** [comment] 2024-05-31 09:32
Here's the detail steps:
- Create PR in react-native-live-markdown. (Link this issue in that PR).
- After above PR is merged, create another PR in this repo to bump `react-native-live-markdown` version.

Let's me know if you have any question.

**Comment by QichenZhu** [comment] 2024-05-31 10:40
Got it, aiming to submit the first PR by Monday.

**Comment by hungvu193** [comment] 2024-06-01 10:43
Contributor will submit PR on Monday

**Comment by hungvu193** [comment] 2024-06-04 23:48
PR in react-native-live-markdown is merged.

@QichenZhu feel free to raise a PR to bump react-native-live-markdown version

**Comment by QichenZhu** [comment] 2024-06-05 02:50
The PR is released in 0.7.79, but we can't upgrade because 0.7.76 has a [regression](https://github.com/Expensify/App/pull/42454#issuecomment-2140731557). We might need to wait for a fix in a future version.

**Comment by hungvu193** [comment] 2024-06-05 02:59
Hmm yeah. We should hold until that issue is fixed. The PR you mentioned was reverted 🤦

**Comment by hungvu193** [comment] 2024-06-07 03:52
Still holding on above comment

**Comment by hungvu193** [comment] 2024-06-07 03:57
Can we put this issue on hold for until react-native-live-markdown is upgrade please @zanyrenney ?

**Comment by hungvu193** [comment] 2024-06-07 13:45
Hold for this one:

https://github.com/Expensify/App/pull/43255

**Comment by hungvu193** [comment] 2024-06-11 02:09
react-native-live-markdown was bumped [here](https://github.com/Expensify/App/pull/43340)
We can test this issue again once it reaches staging.

**Comment by hungvu193** [comment] 2024-06-13 09:44
https://github.com/Expensify/App/pull/43340 reached production. We can now verify this issue

**Comment by hungvu193** [comment] 2024-06-13 09:52
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/react-native-live-markdown/pull/144
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: We actually discuss about this during our reviewing process, so I don't think we need to comment on that PR again.
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: No

**Comment by zanyrenney** [comment] 2024-06-20 11:19
payment summary:

For reference, here are some details about the assignees on this issue:

@hungvu193 requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102536438) (Reviewer) - paid $500 via upwork
@QichenZhu requires payment [automatic offer](https://www.upwork.com/nx/wm/offer/102536440) (Contributor) - paid $500 via upwork

@hungvu193 please complete the steps above too. This doesn't need a new regression test.

**Closed by zanyrenney** 2024-06-20 11:19 UTC
Labels: External, Daily, Awaiting Payment, Bug
