### ISSUE TITLE
Bank account  - Animation in One moment page is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35747] opened 2024-02-03 14:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4278523
**Email or phone of affected tester (no customers):** applausetester+vd_web020224@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a workspace
1. Go to Workspaces > Select Workspace > Bank account
2. Start and follow the add BA process with the testing credentials until you reach the Company information page
3. Fill out the form and click on "Save & continue"

## Expected Result:
After the Company information form is submitted, the One moment page with the animation should be displayed

## Actual Result:
The One moment page is displayed without the animation, only the text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d4d5164a-5744-4dcf-9d7d-ae0fdd82c4f4

![Bug6365472_1706919070308!image](https://github.com/Expensify/App/assets/78819774/ec2cf827-6025-44d6-87f8-a3a40bf1a96b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2024-02-05 09:44
I also can't reproduce. 

@lanitochka17 could you please retest this? I think it might have been fixed with a different issue. Thanks

**Comment by lanitochka17** [comment] 2024-02-05 15:13
@Julesssss  Hello 
Issue is not reproducible with build 1.4.36-1

https://github.com/Expensify/App/assets/78819774/8aafe039-6e21-45ce-bdfa-a61774a593d8

**Comment by Julesssss** [comment] 2024-02-05 15:54
Great, thank you. I'm going to close as it must have been fixed elsewhere.

**Closed by Julesssss** 2024-02-05 15:54 UTC
Labels: Engineering, Daily
