### ISSUE TITLE
[$250] mWeb - Pay someone report showing incorrect user name and green dot in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42528] opened 2024-05-23 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- pay someone
3. Enter an amount and tap next
4. Select a user
5. Tap pay someone
6. Navigate to LHN

## Expected Result:
The report header must not load and name must show correct user and LHN must not shown green dot

## Actual Result:
The report header loading, this is the beginning of chat with user name showing incorrect and LHN showing green dot

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e4f490f9-6b0e-4b68-94bf-427698a9170b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013a88569b48366cec</li>
        <li>Upwork Job ID: 1794828867986399232</li>
        <li>Last Price Increase: 2024-07-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by lanitochka17** [comment] 2024-05-23 14:55
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by getusha** [comment] 2024-05-30 03:08
Waiting for proposals

**Comment by samilabud** [comment] 2024-05-31 19:41
I can't reproduce this:

https://github.com/Expensify/App/assets/5216036/458cb0bb-a3d1-4f56-9e23-8afb81943f11

Could you?

Version Number: 1.4.78-3

**Comment by MitchExpensify** [comment] 2024-06-03 20:06
Can't reproduce but that because my android virtual device won't load staging
<img width="427" alt="image" src="https://github.com/Expensify/App/assets/36425901/139a5dda-b9ef-4e46-ba04-74402297febd">

**Comment by MitchExpensify** [comment] 2024-06-03 22:46
@lanitochka17 are you still able to reproduce this still?

**Comment by lanitochka17** [comment] 2024-06-04 13:15
Issue is not reproducible on the latest build 1.4.78-0

**Comment by ijmalik** [comment] 2024-07-14 03:58
@MitchExpensify, @getusha, @lanitochka17

**Issue is reproducible:**
This issue arises only when there is a **new chat with the account**. If an existing chat already exists, the problem does not occur.

**Comment by ijmalik** [comment] 2024-07-14 03:59
**_Proposal_**

**Please re-state the problem that we are trying to solve in this issue.**
The Pay someone report is displaying an incorrect username and a green dot in the LHN.


**What is the root cause of that problem?**
"Green dot in the LHN" is a different issue. A issue has been created here https://github.com/Expensify/App/issues/41082. I am trying to provide solution there.

Here I am handling only "incorrect username" issue

This issue arises only when there is a **new chat with the account**. If an existing chat already exists, the problem does not occur.

https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/actions/IOU.ts#L5720-L5757

In above code following lines are clearing the account data from allPersonalDetails (key: ONYXKEYS.PERSONAL_DETAILS_LIST) even though the back-end (BE) has been sent the actual data

```
            successPersonalDetailListAction[accountID] = null;
            redundantParticipants[accountID] = null;
```


**What changes do you think we should make in order to solve the problem?**

In above code replace
```
 const successData: OnyxUpdate[] = []; 
  
 // Add optimistic personal details for recipient 
 let optimisticPersonalDetailListData: OnyxUpdate | EmptyObject = {}; 
 const optimisticPersonalDetailListAction = isNewChat 
    ? { 
           [recipientAccountID]: {
               accountID: recipientAccountID, 
               // Disabling this line since participant.displayName can be an empty string 
               // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing 
               displayName: recipient.displayName || recipient.login, 
               login: recipient.login, 
           }, 
       } 
     : {};
```
with
```
    const successData: OnyxUpdate[] = [];
    const shouldCreateOptimisticPersonalDetails = isNewChat && !allPersonalDetails[recipientAccountID];

    // Add optimistic personal details for recipient
    let optimisticPersonalDetailListData: OnyxUpdate | EmptyObject = {};
    const optimisticPersonalDetailListAction = shouldCreateOptimisticPersonalDetails
    ? { 
           [recipientAccountID]: { 
               accountID: recipientAccountID, 
               // Disabling this line since participant.displayName can be an empty string 
               // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing 
               displayName: recipient.displayName || recipient.login, 
               login: recipient.login, 
           }, 
       } 
     : {};
```

**Similar thing has already been addressed e.g. in the following functions** 
1- getSendInvoiceInformation
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/actions/IOU.ts#L1813-L1825

2- function getMoneyRequestInformation
https://github.com/Expensify/App/blob/633e708dfe3d2aba47dbb2091ba1f0f8683bfaaf/src/libs/actions/IOU.ts#L2039-L2054


**Before Code Change:**

Staging: 

https://github.com/user-attachments/assets/5546f5cc-d2a8-478e-a07e-a38f7c16e63c

Local: 

https://github.com/user-attachments/assets/d3e7a0f1-3079-46f7-aa3a-e43f2239e1ae


**After Code Change:**

https://github.com/user-attachments/assets/73c1bf4c-43f7-42f7-8b90-a617e9000905



**What alternative solutions did you explore?**

**Comment by ijmalik** [comment] 2024-07-22 05:09
Hi @MitchExpensify, @getusha, @lanitochka17 ,

Following up on my previous message regarding [#42528](https://github.com/Expensify/App/issues/42528#issuecomment-2227186572). The issue is still reproducible when there is a new chat with the account. If an existing chat already exists, the problem does not occur.

Could you please review this and consider reopening the issue?

Thank you!

**Comment by MitchExpensify** [comment] 2024-07-22 17:20
Reassigning as I'm paternity leave

**Comment by jliexpensify** [comment] 2024-07-23 03:40
Hi @ijmalik can you share a video? I'm having trouble reproducing this on a Pixel 7.

**Comment by ijmalik** [comment] 2024-07-23 12:07
Hi @jliexpensify, sure,  It might take a little time to reproduce the issue and create the video. I’ll share it with you as soon as I have it ready. I appreciate your understanding!

**Comment by jliexpensify** [comment] 2024-07-24 00:50
Thanks, appreciate it @ijmalik. @getusha - you definitely can't repro [this](https://github.com/Expensify/App/issues/42528#issuecomment-2227186466) right?

For now, I'll add it under #wave-collect

**Comment by ijmalik** [comment] 2024-07-24 18:30
Hi @jliexpensify, @getusha,

Thank you for your message. When I initially proposed my solution, we were on version 9.0.6-3, where the behavior was different, showing a continues skeleton instead of the account name.

In the current version 9.0.11-2, the behavior is as follows when pressing the "Pay elsewhere" button:

The account info is shown with optimistic data, displaying the email address (e.g., expensifyijm+17@gmail.com).

After the [SendMoneyElsewhere API response](https://github.com/user-attachments/files/16365898/SendMoneyElsewhere-respose.json), a skeleton is shown instead of the account name.
When the [GetMissingOnyxMessages API response](https://github.com/user-attachments/files/16365926/GetMissingOnyxMessages-respose.json) is received, the skeleton remains.
Finally, the [OpenReport API response](https://github.com/user-attachments/files/16365933/OpenReport-respose.json), which includes the personalDetailsList with the account name details, is received, and the proper account name replaces the skeleton.

This means we have to wait for the OpenReport response, which can take around 2 seconds or more.

My proposal (https://github.com/Expensify/App/issues/42528#issuecomment-2227186572) aims to show the immediate account name without the skeleton, enhancing the user experience by avoiding the waiting period.

Thank you for considering this update.

Skeleton Shown:
![skeleton_1](https://github.com/user-attachments/assets/9213b1a2-a65a-4e51-94ce-9f53a3099742)

https://github.com/user-attachments/assets/7cd73432-3e3b-4368-9c4e-6b6784469d7c


**After code change:**

https://github.com/user-attachments/assets/d9e22baa-ede7-4d4e-bd5c-ad767b763868

**Comment by jliexpensify** [comment] 2024-07-25 02:29
Thanks for sharing these videos @ijmalik, I appreciate it - I can see the difference but for me, it's very slight. I'm not sure this is worth fixing - @getusha do you have any thoughts?

**Comment by getusha** [comment] 2024-07-25 20:01
If the account name loads successfully anyway, I don't think this is worth fixing. it seems insignificant.

**Comment by jliexpensify** [comment] 2024-07-26 01:06
Yep, that's where I'm landing on as well. Thanks, closing!

**Closed by jliexpensify** 2024-07-26 01:06 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by ijmalik** [comment] 2024-08-07 08:10
**_Proposal_**

**Please re-state the problem that we are trying to solve in this issue.**
The Pay someone report is displaying an incorrect username and a green dot in the LHN.


**What is the root cause of that problem?**
Other issues have already been resolved.

Here I am handling only "Offline - showing skeleton instead of username" issue. 

This issue arises only when there is a **new chat with the account**. If an existing chat already exists, the problem does not occur.

https://github.com/Expensify/App/blob/de894796363ad1bc42fa360c6d7b74f8a26c4b61/src/pages/home/HeaderView.tsx#L85

Above line of code is run before personalDetails is updated with newly account email. So title is empty

https://github.com/Expensify/App/blob/de894796363ad1bc42fa360c6d7b74f8a26c4b61/src/pages/home/HeaderView.tsx#L137
Here because title is empty isLoading is become true which causing continuously showing skeleton instead of username 

**What changes do you think we should make in order to solve the problem?**

Replace
https://github.com/Expensify/App/blob/de894796363ad1bc42fa360c6d7b74f8a26c4b61/src/pages/home/HeaderView.tsx#L85
with
```
const [title, setTitle] = React.useState('');

React.useEffect(() => {
    const fetchTitle = async () => {
        const reportTitle = await ReportUtils.getReportName(reportHeaderData, undefined, parentReportAction);
        setTitle(reportTitle);
    };

    fetchTitle();
}, [reportHeaderData, parentReportAction, report.reportID, personalDetails]);

```

**Before Code Change:**

Staging: 


https://github.com/user-attachments/assets/a6e0aab7-5446-408f-889e-7a58c34ea236


**After Code Change:**
Local:



https://github.com/user-attachments/assets/2a11fe73-3f1c-4ea6-a82d-d843b6c4c50c






**What alternative solutions did you explore?**

**Comment by ijmalik** [comment] 2024-08-07 08:16
@jliexpensify @getusha

While the online issues have been resolved, the offline issue of "showing skeleton instead of username" persists. Could you please refer to the details above in [#42528 (comment)](https://github.com/Expensify/App/issues/42528#issuecomment-2272879523)? 

Thank you.

**Comment by ijmalik** [comment] 2024-08-12 03:58
Hi @jliexpensify and @getusha,

Just following up on the **offline** issue of "showing skeleton instead of username" mentioned in [#42528 (comment)](https://github.com/Expensify/App/issues/42528#issuecomment-2272879523). Could you please check and provide an update?

Thank you!

**Comment by jliexpensify** [comment] 2024-08-12 04:39
@ijmalik I can't load either of your videos in GH (not sure why the video player in GH has been so bad lately, but I can only load the first 5 seconds of each one). My thoughts are that `showing skeleton instead of username in offline mode` isn't very significant.

There's also a specific condition:

>This issue arises only when there is a new chat with the account. If an existing chat already exists, the problem does not occur.

So it depends on the user:

- Having an entirely new account
- For their first action to pay someone

This might affect some users, but I would guess the majority of new signups won't notice/won't care/won't pay someone first.

If @getusha wants to weigh in further, please do, but I don't think this is worth fixing.

**Comment by ijmalik** [comment] 2024-08-12 10:28
> I can't load either of your videos in GH (not sure why the video player in GH has been so bad lately, but I can only load the first 5 seconds of each one).

@jliexpensify, GitHub can behave like that, especially if the issue page has been open for a while.

**Solution:** Try refreshing the page, then either download the video or watch it online.
