### ISSUE TITLE
[HOLD for payment 2023-11-22] [$500] Distance - Address search term not highlighted on refocus

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#30198] opened 2023-10-23 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698057007022009

## Action Performed:
1. Open the app
2. Click on green plus and click request money
3. Click on distance and click on start/finish
4. Type anything in search
5. Remove focus from search and focus back on search
6. Observe that app does not highlight search term
7. Similarly try on any other search in the app like search page and observe that search term is highlighted on refocus

## Expected Result:
App should highlight search term on refocus

## Actual Result:
App does not highlight search term on refocus for address search

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/bd68e3bb-01f5-47a3-8ddb-2be6caf96072

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/03e798f4-a23f-4a03-96aa-c5dd52937a26

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/c400f454-e7c2-4736-82fa-63909ab2cc18

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6dbd570c-9929-479f-a2bb-7d957a752a98

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/2d2d284a-9616-46df-9bed-5f9aea295b67

https://github.com/Expensify/App/assets/93399543/4f92ee69-95f5-4ec6-9891-b5736aadd533

https://github.com/Expensify/App/assets/93399543/da25e5a5-bfdb-4301-a7f4-7f3fb238f94d

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/e36bb517-fe71-4574-a492-a1c3f7cec555

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142e6f24bf8176632</li>
        <li>Upwork Job ID: 1716527404788051968</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-23 18:49
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Text is not selected when focused on the text input in way point selection page.
### What is the root cause of that problem?
We are not passing the prop `selectTextOnFocus` here
https://github.com/Expensify/App/blob/3f32b7dabbc9ee19e6e859d6460f7652f4824c4d/src/components/AddressSearch/index.js#L402
in `GooglePlacesAutocomplete`.
### What changes do you think we should make in order to solve the problem?
We should also pass the `selectTextOnFocus: true` prop to `textInputProps` specified above
```js
                        textInputProps={{
                            selectTextOnFocus: true,
```
### What alternative solutions did you explore? (Optional)
<details>
<summary>Result</summary>


https://github.com/Expensify/App/assets/102477862/6dda80a9-68de-43e7-af4f-7d0427ede3df






</details>

**Comment by DylanDylann** [comment] 2023-10-24 18:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Address search term not highlighted on refocus
### What is the root cause of that problem?
- We do not apply the ```selectTextOnFocus``` in the textInputProps as below:
https://github.com/Expensify/App/blob/e968637a35b19dfbd7ad7f437b68fda57fc16d63/src/components/AddressSearch/index.js#L402

### What changes do you think we should make in order to solve the problem?
- We should apply ```selectTextOnFocus``` to the text input, but there are two cases that we need to consider:
1. User are typing on search input, then blur, and then refocus on search input. In this case ```selectTextOnFocus``` is true.
2. User clicking on any waypoint (for example "123 W Main St...") , it will navigate user to search address page with the input value is "123 W Main St...". In this case, ```selectTextOnFocus``` should be false. Then , if user blur the search input and then refocus, ```selectTextOnFocus``` should be set to true 
- We can do it by creating the ```shouldSelectTextOnFocus``` state with the default value is false. And update
https://github.com/Expensify/App/blob/e9507a010f3825414e97e9136242714ca037d717/src/components/AddressSearch/index.js#L402
to 
```
           textInputProps={{
           selectTextOnFocus: shouldSelectTextOnFocus,
```
-  When user blurs the search input, set it to true


### What alternative solutions did you explore? (Optional)
- NA

**Comment by JmillsExpensify** [comment] 2023-10-24 22:56
Open for proposals and should be going through proposal review soon.

**Comment by cubuspl42** [comment] 2023-10-25 07:14
@DylanDylann While I get the general idea of your proposal, I'm unsure if I fully understand the details of when/how `shouldSelectTextOnFocus` should change. Do you have a Git branch at hand, so I could quickly test it?

**Comment by DylanDylann** [comment] 2023-10-25 07:35
@cubuspl42 sure, please wait a minute

**Comment by DylanDylann** [comment] 2023-10-25 07:40
https://github.com/Expensify/App/pull/30326 @cubuspl42 please help check this one

**Comment by c3024** [comment] 2023-10-25 08:01
I think selecting the whole search string when a user clicks on waypoint to edit it is better because, in Autocomplete situations like these, it is unlikely that a user adds a letter after the existing way point or delete some letters from the waypoint. Instead, selecting/highlighting the string on user clicking on waypoint to edit appears to be more logical because in components like GoogleAutoComplete, a user likely searches for a waypoint afresh instead of deleting some letters or moving to another position in the string with keyboard.

**Comment by cubuspl42** [comment] 2023-10-26 09:51
@DylanDylann I tested your solution, and it doesn't seem to be a noticeable improvement. It's related to a corner case. A user can still easily place their cursor at any position of the text input with another click, if they want to.

**Comment by cubuspl42** [comment] 2023-10-26 09:51
I approve the proposal by @c3024, which is the first one to suggest passing the `selectTextOnFocus` property.

C+ reviewed 🎀 👀 🎀

**Comment by DylanDylann** [comment] 2023-10-26 10:18
@Julesssss Should this be the expected behavior? https://github.com/Expensify/App/issues/30198#issuecomment-1778691233. If not, i think @c3024 `s proposal is the best

**Comment by Julesssss** [comment] 2023-10-26 10:38
I agree with @cubuspl42 here. Assigning @c3024

**Comment by cubuspl42** [comment] 2023-10-26 10:38
It's worth noting that to get to the state from the first frame of a video, the user has to first search for and select an address.

**Comment by Julesssss** [comment] 2023-10-26 10:41
@JmillsExpensify any idea what label I'm missing here? Melvin didn't seem to add some of the UpWork/raise a PR comments.

**Comment by cubuspl42** [comment] 2023-11-20 11:49
- The PR that introduced the bug has been identified. Link to the PR:
    -  It seems that the bug was present in the relevant components since they were created
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    -  No need for a regression test
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - N/A

**Comment by JmillsExpensify** [comment] 2023-11-24 18:31
Closing the loop on payments. Thanks for the regression suggestion @cubuspl42! 

Payment summary:
 - Issue report: @dhanashree-sawant $50
 - Contributor: @c3024 $500 
 - Contributor+: @cubuspl42 $500

**Comment by JmillsExpensify** [comment] 2023-11-24 19:21
Offers sent to everyone in Upwork based on the above summary.

**Comment by JmillsExpensify** [comment] 2023-11-26 21:21
Everyone has been paid out based on the summary above and no regression test required, so closing one out!

**Closed by JmillsExpensify** 2023-11-26 21:21 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
