### ISSUE TITLE
[$500]  LHN - White line between LHN and chat view when the webpage zoom level is 75%

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32745] opened 2023-12-08 20:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Decrease webpage zoom level to 75%.

## Expected Result:
There is no visual issue involving white element

## Actual Result:
The line between LHN and chat view becomes white when the webpage zoom level is 75%

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6cf75338-72de-4f91-b851-47f3cce5490c

![Bug6306186_1702063920544!bandicam_2023-12-09_03-29-06-183](https://github.com/Expensify/App/assets/78819774/39fefe5e-0e63-47ab-aa52-77f0cc7913ee)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012343f6a46c0a8e3f</li>
        <li>Upwork Job ID: 1733215408636047360</li>
        <li>Last Price Increase: 2023-12-22</li>
    </ul>
</details>

**Comment by happy-devs** [comment] 2023-12-08 20:04
This also happens on 110% zoom

**Comment by happy-devs** [comment] 2023-12-08 20:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The line between LHN and chat view becomes white when the webpage zoom level is 75%

### What is the root cause of that problem?
The css class `box-sizing: border-box` inside the `#lhn` class in `_main.css` is causing the issue. once removed it's no longer there



### What changes do you think we should make in order to solve the problem?

replace this class with an alternative

**Comment by ZhenjaHorbach** [comment] 2023-12-08 22:49
# Proposal
## Please re-state the problem that we are trying to solve in this issue.

 White line between LHN and chat view when the webpage zoom leve

## What is the root cause of that problem?

in fact, this is a problem related to sideBarWidth

https://github.com/Expensify/App/blob/adbeba13ef409abb11024a2bf602a6625d3249fb/src/styles/variables.ts#L87

Since our meaning is too specific
It is very difficult to scale
As a result, we have non-integer values for styles
What causes white streaks to appear between components

## What changes do you think we should make in order to solve the problem?

The easiest way to fix this
This is to change the indentation from an odd number to an even number
Which won't affect anything visually
But the bug will disappear

`        rootNavigatorContainerStyles: (isSmallScreenWidth: boolean) => ({marginLeft: isSmallScreenWidth ? 0 : variables.sideBarWidth - 1, flex: 1} satisfies ViewStyle),`

https://github.com/Expensify/App/blob/271b0a5f26555920dcf518e5d12cc31608e3a0d1/src/styles/styles.ts#L2406


Or we can set global value from 375 to 374

https://github.com/Expensify/App/blob/271b0a5f26555920dcf518e5d12cc31608e3a0d1/src/styles/variables.ts#L87

## What alternative solutions did you explore? (Optional)
NA

**Comment by shahinyan11** [comment] 2023-12-09 09:29
https://github.com/Expensify/App/issues/31573

I think this two issues need to be considered together

**Comment by mvtglobally** [comment] 2023-12-21 16:17
Issue not reproducible during KI retests. (First week)

**Comment by peterdbarkerUK** [comment] 2023-12-27 12:34
Not reproducible, closing

**Closed by peterdbarkerUK** 2023-12-27 12:34 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
