### ISSUE TITLE
[HOLD][$1000] Web - An extra room is being created if user starts a new chat with a new account after adding to a new workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22233] opened 2023-07-05 00:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account A
2. Click on FAB > New workspace > members > Invite > paste an email of account B
3. Click on FAB > new chat > Paste the email of account B and select it

## Expected Result:
Only a new chat with account B should be created

## Actual Result:
An extra room is being created and it disappears after user clicks on another chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/dfa1387b-caa7-4680-bf6b-848e5b5653e7

https://github.com/Expensify/App/assets/93399543/d8bef1a7-6803-4443-b694-b610214f10c4

**Expensify/Expensify Issue URL:**
**Issue reported by:**@Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688456422758769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106b169ef87fc6e50</li>
        <li>Upwork Job ID: 1676695921440915456</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-07-05 20:53
Looks good!

**Comment by TZubiri** [comment] 2023-07-06 00:29
Hey. The issue is marked as ocurring in the web browser platform. Does this only occur in web browsers? Or is it the only confirmed platform?

**Comment by TZubiri** [comment] 2023-07-06 00:37
Contributor details
Your Expensify account email:  expensify@tomaszubiri.com
Upwork Profile Link: https://www.upwork.com/freelancers/tomzubiri

**Comment by waterim** [comment] 2023-07-10 14:01
Hi!
I'm Artem from Callstack - expert contributor group
Maybe I can help with this one?

**Comment by slafortune** [comment] 2023-07-12 18:58
@waterim sounds good - assigning you!  THX

**Comment by waterim** [comment] 2023-07-13 18:45
Not a proposal yet.

My update: 
After a long investigation of this random bug(It can be reproduced 1/5 times or 4/5 times, its fully random). Issue here is in onyx data, after logout we have an Onyx.clear but it still has some weird empty reports.
Investigating whats wrong there.
Attaching an image: 
![telegram-cloud-photo-size-4-5872984520624553211-y](https://github.com/Expensify/App/assets/39777589/3aa8fe46-f086-472a-bb26-0b8396873e0d)

**Comment by waterim** [comment] 2023-07-17 10:44
This one is on hold. 
It looks like solution from this [issue](https://github.com/Expensify/App/issues/15321) will solve this bug.
(Some wrong data added to Onyx after Onyx.clear().)

**Comment by slafortune** [comment] 2023-07-19 20:33
Still on hold to make sure the connect GH fixes this issue

**Comment by slafortune** [comment] 2023-07-24 19:36
Still on hold

**Comment by slafortune** [comment] 2023-07-26 20:34
Updating to weekly

**Comment by slafortune** [comment] 2023-08-07 19:37
Looks like the other GH will fully resolve the issue, so closing this one.

**Closed by slafortune** 2023-08-07 19:37 UTC
Labels: External, Weekly, Overdue, Bug

**Comment by waterim** [comment] 2023-08-07 20:00
@slafortune great
