### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] Inconsistent input field size in close account page message field

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20904] opened 2023-06-16 13:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to settings > security > close account
2. Notice the "Enter message here" input field's height
3. Go to settings > workspaces > select a workspace > manage members > invite members > invite a member
4. Notice the "Message" input field's height in Add message page

## Expected Result:
The height of the message input field should be consistent with in both pages. (i.e close account page and invite members page) Close account message field should dynamically adjust it's height based on the content inside of it.
## Actual Result:
Manage members page's message input field is different from the close account message input field. Close account message field does not adjust height dynamically based on the content inside of it.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28. 5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f82c6bed-1eb0-4c7e-9bef-a4be0ec482ad

https://github.com/Expensify/App/assets/43996225/52fe1201-06db-4ead-94b2-47ecdc941de0

https://github.com/Expensify/App/assets/43996225/c774f338-47b2-4221-b0bb-bf7dc49124ce

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684480867153739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e2a10f74dd3ef35</li>
        <li>Upwork Job ID: 1670702078642098176</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by reinaldosg** [comment] 2023-06-16 13:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistent input field size in close account page message field

### What is the root cause of that problem?
Both TextInput has different style

https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/settings/Security/CloseAccountPage.js#L104-L110

https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/workspace/WorkspaceInviteMessagePage.js#L201-L213

### What changes do you think we should make in order to solve the problem?
Change the TextInput style on CloseAccountPage to be the same with TextInput on WorkspaceInviteMessagePage

``` js
<TextInput
    inputID="reasonForLeaving"
    autoGrowHeight
    textAlignVertical="top"
    label={this.props.translate('closeAccountPage.enterMessageHere')}
    containerStyles={[styles.mt5, styles.autoGrowHeightMultilineInput]}
/>
```

### What alternative solutions did you explore? (Optional)

**Comment by shawnborton** [comment] 2023-06-16 17:50
Correct, this isn't a bug.

**Comment by shawnborton** [comment] 2023-06-16 17:51
Actually sorry on second thought, I think we'd want to make all textareas behave the same way, which means we should update the textarea on the close account page.

**Comment by srikarparsi** [comment] 2023-06-22 06:38
thanks @thesahindia, it looks good to me as well, assigning you to the issue @reinaldosg

**Comment by reinaldosg** [comment] 2023-06-22 17:07
Hi @srikarparsi  @thesahindia ! My [PR](https://github.com/Expensify/App/pull/21333) is ready for review.

**Comment by reinaldosg** [comment] 2023-07-06 18:27
hi @thesahindia @srikarparsi, when can I expect to receive the payment?

**Comment by dylanexpensify** [comment] 2023-07-10 09:37
@reinaldosg apologies, working on this today! Have you applied to the upwork job?

**Comment by reinaldosg** [comment] 2023-07-10 12:24
@dylanexpensify yes, I've submitted the proposal in upwork as well

**Comment by Nathan-Mulugeta** [comment] 2023-07-12 08:14
Hey @dylanexpensify could we process the payment for this issue?

**Comment by dylanexpensify** [comment] 2023-07-12 08:55
Yes! Sorry for delay!

**Comment by dylanexpensify** [comment] 2023-07-12 08:57
@reinaldosg offer sent! @Nathan-Mulugeta I don't see your proposal, mind tackling? @thesahindia don't see yours either!

**Comment by Nathan-Mulugeta** [comment] 2023-07-12 09:13
I am the bug reporter @dylanexpensify

**Comment by reinaldosg** [comment] 2023-07-12 11:08
hi @dylanexpensify, I want to confirm, since I eligible with 50% bonus ([ref](https://github.com/Expensify/App/issues/20904#issuecomment-1608389679)), is it gonna be a separate offer on Upwork ? Because the offer is still $1000 without 50% bonus

**Comment by dylanexpensify** [comment] 2023-07-17 09:15
@Nathan-Mulugeta yes yes, did you apply for that?? @reinaldosg correct! I'll send bonus payment when paying out today!

**Comment by Nathan-Mulugeta** [comment] 2023-07-17 09:20
Just applied on the upwork job @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-07-20 08:33
fyi @reinaldosg sent payment of $1500! @Nathan-Mulugeta sent offer!

**Comment by Nathan-Mulugeta** [comment] 2023-07-20 08:40
Accepted offer @dylanexpensify

**Comment by reinaldosg** [comment] 2023-07-20 15:26
@dylanexpensify thank you!

**Comment by JmillsExpensify** [comment] 2023-09-22 08:50
@dylanexpensify Do you mind providing a payment summary on this issue so that I can pay @thesahindia?

**Comment by dylanexpensify** [comment] 2023-09-25 10:34
Ahh yep! Payment summary:
- Reporter: @Nathan-Mulugeta $250
- Contributor: @reinaldosg $1,500
- Contributor+: @thesahindia $1,500

Upwork job. Please apply! (cc @JmillsExpensify)

**Comment by dylanexpensify** [comment] 2023-09-27 11:08
closing

**Closed by dylanexpensify** 2023-09-27 11:08 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:35
$1,500 payment approved for @thesahindia based on BZ summary.
