### ISSUE TITLE
[$250] Animation not smooth while closing attachment modal - reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#11359] opened 2022-09-27 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to any chat
2.  click on any PDF
3.  Press :x: button

## Expected Result:
animation should be smooth

## Actual Result:
animation is not smooth

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.3-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/192631660-2f415093-22d7-4fb0-a56b-c1c53eb167e3.mov

**Expensify/Expensify Issue URL:**  
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1663057956998529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2022-10-04 19:12
not overdue

**Comment by arielgreen** [comment] 2022-10-05 05:13
https://www.upwork.com/jobs/~010323d5793ea6c484

**Comment by RafehWaqar** [comment] 2022-10-05 08:39
Hello Expensify.
I would like to work with you. For the problem, my thinking is that it could be a problem in the api if the opening and closing is not custom coded and if it is custom coded then the problem would be in the code but either way I can't know where is the problem until I see the code.

Thank you.

**Comment by sobitneupane** [comment] 2022-10-05 10:46
Hello @RafehWaqar, Thanks for your interest.

Please do follow [Contributing Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#working-on-expensify-jobs) to know how you can contribute.

**Comment by sobitneupane** [comment] 2022-10-10 15:54
Unable to reproduce on my device.

cc: @srikarparsi @arielgreen

**Comment by srikarparsi** [comment] 2022-10-10 16:36
also no longer able to reproduce, @arielgreen I think we can close out the issue

**Comment by arielgreen** [comment] 2022-10-10 23:45
Closed.

**Closed by arielgreen** 2022-10-10 23:45 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted
