### ISSUE TITLE
[HOLD for payment 2024-09-07] [$250] Taxes - Name field is no longer grayed out after editing tax code offline

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47747] opened 2024-08-20 20:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.22-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4874241
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes.
3. Go offline.
4. Click on any tax rate.
5. Click Name.
6. Edit the name and save it.
7. Click Tax code.
8. Edit Tax code and save it.

## Expected Result:
Name field will remain grayed out after editing tax code offline.

## Actual Result:
Name field is no longer grayed out after editing tax code offline.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/096e04a3-79a3-46e9-9c65-a91e1e7cf762

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01da26942e57c47d6b</li>
        <li>Upwork Job ID: 1826075814524858613</li>
        <li>Last Price Increase: 2024-08-21</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by IuliiaHerets** [comment] 2024-08-20 20:18
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-20 20:18
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-08-21 04:58
@Krishna2323 's first posted proposal comment shows the offending code block correctly in the RCA and the suggested solution is clear enough. I think we can proceed with his [proposal](https://github.com/Expensify/App/issues/47747#issuecomment-2299704135) because his is first.

🎀 👀 🎀 C+ Reviewed

**Comment by mountiny** [comment] 2024-08-23 20:05
Go ahead please @Krishna2323

**Comment by c3024** [comment] 2024-08-31 13:49
Automation failed here. This was deployed to production yesterday. Payment due on 7-Sep or 8-Sep.  

cc: @kadiealexander

**Comment by mountiny** [comment] 2024-09-02 10:35
Updated

$250 to @Krishna2323 and to @c3024

**Comment by kadiealexander** [comment] 2024-09-04 22:38
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@c3024] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@c3024] Determine if we should create a regression test for this bug.
- [ ] [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by c3024** [comment] 2024-09-08 14:31
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: #43156 
> * [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/commit/bee9d44584a82ad6efa1b689f1aac65b9884b387#r146398000
> * [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No discussion was started because this could not have identified earlier.
> * [x]  [@c3024] Determine if we should create a regression test for this bug. Yes
> * [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Go to workspace settings > Taxes.
2. Go offline.
3. Click on any tax rate.
4. Click on Name.
5. Edit the name and save it.
6. Click on Tax code.
7. Edit the Tax code and save it.
8. Verify that the name field remains greyed out.

**Comment by kadiealexander** [comment] 2024-09-09 01:02
Not overdue, offers sent!

**Closed** 2024-09-10 06:53 UTC
Labels: External, Daily, Awaiting Payment, Bug
