### ISSUE TITLE
Android - Workspace settings - There is no option to choose the default currency

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10099] opened 2022-07-26 01:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to App and login with a applause.expensifail account
2. Click on Create a New Workspace (if it has not been created before)
3. Navigate to the General settings page

## Expected Result:
It is possible to choose the default currency

## Actual Result:
There is no option to choose the default currency

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** v1.1.86-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**Email or phone of affected tester (no customers):**  Any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/180901602-9e78b428-cf74-4003-b297-5a49304e3422.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-07-26 17:16
Not able to reproduce this.

**Comment by luacmartins** [comment] 2022-07-26 17:19
@kavimuru I'm also not able to reproduce this. Can you please check again?

**Comment by mvtglobally** [comment] 2022-07-26 18:33
Checking and will update in a bit

**Comment by mvtglobally** [comment] 2022-07-26 18:47
@luacmartins @marcaaron We are consistently able to repro on build 1.1.86-0 on Android 
 We are unable to check 1.1.86-1, as build goes back to 1.1.85-8 and new version is not available to install at all

https://user-images.githubusercontent.com/43995119/181087254-55e9798a-a26f-495d-9b4a-47f3d9165b1e.mp4

**Comment by luacmartins** [comment] 2022-07-27 20:04
@kavimuru We are still not able to repro this. Could you try to reproduce from a fresh app start?

**Comment by neil-marcellini** [comment] 2022-07-27 20:06
^ and log out 🙂

**Comment by luacmartins** [comment] 2022-07-27 20:09
The only way I could reproduce this was delaying the response from the `OpenApp` command using a setTimeout. @kavimuru does the option eventually show up?

**Comment by luacmartins** [comment] 2022-07-27 20:22
@kavimuru can you test this again with the steps below?

1. Log out
2. Log in
3. Wait 15-20s
4. Navigate to `Workspace > General Settings`
5. Verify that the currency selection dropdown shows up

**Comment by mvtglobally** [comment] 2022-07-28 02:24
Checking with the team

**Comment by luacmartins** [comment] 2022-07-29 00:13
Removing the blocker label since we couldn't reproduce and this would only affect a beta feature. @mvtglobally Can we add this to the KI tests?

**Comment by kavimuru** [comment] 2022-07-29 13:12
@luacmartins Issue is still able to reproduced with 1.1.86-5

https://user-images.githubusercontent.com/43996225/181767747-eb2f66d1-b039-4b51-af5b-86eb119fb013.mp4

**Comment by neil-marcellini** [comment] 2022-08-01 19:29
I just reproduced this accidentally when testing something else. I did the following:
1. Create a new workspace
2. Wait for the workspace page to open
3. Click "General settings"

**Comment by neil-marcellini** [comment] 2022-08-02 19:05
Workspace don't seem to be loading properly on Android, at least on dev. I created a workspace on the account `workspace-curr@gmail.com` on iOS, and everything works well. If I sign into that account on Android I don't see any workspaces.

**Comment by neil-marcellini** [comment] 2022-08-12 17:04
All yours @luacmartins.

**Comment by luacmartins** [comment] 2022-08-19 15:53
@kavimuru is this issue still reproducible?

**Comment by kavimuru** [comment] 2022-08-22 13:16
@luacmartins Checking with the team

**Comment by luacmartins** [comment] 2022-08-22 15:21
Thanks for confirming. Similar to the other android specific issues, I think we solved it in https://github.com/Expensify/Web-Expensify/pull/34497. Closing this issue.

**Closed by luacmartins** 2022-08-22 15:21 UTC
Labels: Engineering, Weekly
