### ISSUE TITLE
[$250] Report fields - Report fields values do not update when changed for submitted expense

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47566] opened 2024-08-16 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Preconditions: Existing workspace with report fields enabled and report fields set up
1. Navigate to workspace chat
2. Create new manual expense
3. Open the expense and submit it
4. Change any of the report fields value
5. Repeat step 4. if issue not reproduced on first change

## Expected Result:
Correct report field value should be displayed

## Actual Result:
The value selected by the user is briefly displayed and reverts to the previous value

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/6b04590b-2746-4f5d-978c-129161dd761c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833275366215587344</li>
        <li>Upwork Job ID: 1833275366215587344</li>
        <li>Last Price Increase: 2024-10-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by lanitochka17** [comment] 2024-08-16 12:32
@anmurali  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by codewaseem** [comment] 2024-08-17 09:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Changing the report field value resets back to the old value even though the updates are applied on the backend. 

### What is the root cause of that problem?
I think the root cause is passing wrong update IDs to the GetMissingOnyxMessages API which merges the the new state with the old state.

https://github.com/Expensify/App/blob/76158981580aa046592df17c940fb6b289b0924d/src/libs/actions/OnyxUpdateManager/index.ts#L136-L143

Here the `previousUpdateIDFromServer` value is off by some updates and `lastUpdateIDFromClient` value will also include the old updates as well which overrides the new state while merging. 

### What changes do you think we should make in order to solve the problem?
I think changing the updates id range from `lastUpdateIDFromClient -> previousUpdateIDFromServer` to `previousUpdateIDFromServer -> lastUpdateIDFromServer` will apply the correct changes. 

### What alternative solutions did you explore? (Optional)

**Comment by codewaseem** [comment] 2024-08-19 13:46
## Proposal Updated
https://github.com/Expensify/App/issues/47566#issuecomment-2294804511
Added demo video

**Comment by anmurali** [comment] 2024-08-28 01:10
https://github.com/user-attachments/assets/17fbd93d-4cfa-4c4f-8c25-2b67ddd9aec4

Seems to be working as expected.

**Comment by IuliiaHerets** [comment] 2024-08-31 15:04
QA team can reproduce this issue, build - v9.0.27-0

https://github.com/user-attachments/assets/6b13f075-b3de-4b08-9618-c387e63270b0

**Comment by anmurali** [comment] 2024-09-09 22:45
@aimane-chnaif - there is a proposal above from @codewaseem for you to review.

**Comment by trjExpensify** [comment] 2024-09-11 00:40
Report fields are being built in #wave-control, moving this over to that project.

**Comment by codewaseem** [comment] 2024-09-11 05:36
@aimane-chnaif yes. I think this is a backend issue.

**Comment by mvtglobally** [comment] 2024-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by IuliiaHerets** [comment] 2024-10-08 20:26
@aimane-chnaif Issue not reproducible anymore 

https://github.com/user-attachments/assets/0b755921-0b2a-4e07-8f8b-b2966e09a870

**Closed** 2024-10-15 15:23 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
