### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Bank account - Selected bank account is not checked in bank account selection step

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37290] opened 2024-02-27 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal team

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to workspace settings.
3. Select a workspace.
4. Go to Bank account.
5. Click Connect online with Paid.
6. Log in with Chase account.
7. Back in bank account selection page, select any bank account.

## Expected Result:
The selected bank account is checked in the checkbox.

## Actual Result:
The selected bank account is not checked in the checkbox.
This issue also occurs with the checkbox in Company owner steps.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5ec1d4f7-7363-4203-a8fc-4f21c5e6282b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f67808490772984d</li>
        <li>Upwork Job ID: 1762476893193760768</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 0</li>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-27 13:57
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by flodnv** [comment] 2024-02-27 14:05
Probably good, do you agree with the fix @jjcoffee @roryabraham @danieldoglas ?

**Comment by danieldoglas** [comment] 2024-02-27 14:10
That sounds good to me as well, I noticed that happening on https://github.com/Expensify/App/issues/37271 as well, but the error logged is different there.

**Comment by danieldoglas** [comment] 2024-02-27 14:44
@ZhenjaHorbach hmm thanks for checking that. 

Yeah, thanks for pointing out that pull request. 

I think checking if the value exists makes sense since most of the forms are not using value outside of the form like it's the case with the exit survey and that property was just implemented.  @roryabraham @mollfpr what do you think?

**Comment by jjcoffee** [comment] 2024-02-27 14:56
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/37290#issuecomment-1966682179) LGTM and makes sense that it comes from https://github.com/Expensify/App/pull/34925 given this is only happening on staging. Also agree that checking if `value` is undefined makes sense here as `value` is an optional prop that's meant to only be used if using the component as a controlled input (i.e. it _should_ work as expected without it!).

https://github.com/Expensify/App/blob/22b63905fa23b83c21208eb6d707dd8c86d4d1a7/src/components/RadioButtons.tsx#L35-L36

:ribbon::eyes::ribbon: C+ reviewed

**Comment by flodnv** [comment] 2024-02-27 17:55
Leaving this to you @roryabraham since you originally wrote the code

**Comment by roryabraham** [comment] 2024-02-27 18:14
whoops, my mistake. I made RadioButtons a controlled component without refactoring other usages to be controlled. I like @ZhenjaHorbach's proposal to make it work as controlled or uncontrolled, but I think that we can leave `defaultCheckedValue` as it still has a utility for parent components using RadioButtons as an uncontrolled component

**Comment by roryabraham** [comment] 2024-02-27 18:17
btw @ZhenjaHorbach, are you in the #expensify-open-source slack room?

**Comment by jjcoffee** [comment] 2024-03-07 10:11
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/34925/
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/34925/files#r1515894840
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Go to workspace settings
2. Select a workspace
3. Go to Bank account
4. Click Connect online with Paid
5. Log in with Chase test account details
6. Back in bank account selection page, select any bank account
7. Verify that selected bank account is checked in the checkbox

Do we agree 👍 or 👎

**Comment by Christinadobrzyn** [comment] 2024-03-07 20:48
Payouts due:

Contributor: $500 @ZhenjaHorbach (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36490106/overview)
Contributor+: $500 @jjcoffee (paid in Upwork - https://www.upwork.com/nx/wm/workroom/36497814/overview

Upwork job is [here](https://www.upwork.com/jobs/~01f67808490772984d).

Regression test here - https://github.com/Expensify/Expensify/issues/376594

closing

**Closed by Christinadobrzyn** 2024-03-07 20:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment
