### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] Distance - Map pending not scaled and not fully visible when creating > 1 expenses

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43420] opened 2024-06-10 18:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4613584
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39243
## Action Performed:
precondition: user a member of a workspace
1. Open the app and log in
2. Open the workspace chat
3. Create more than 1 distance expenses

## Expected Result:
"Map pending" text is scaled in the report preview depending on the number of expenses

## Actual Result:
"Map pending" is not fully visible, and it is displayed in multiple lines in the report preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/7106409e-3879-4a5c-aaac-833f1b5bad47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fbedebd9a7bc999</li>
        <li>Upwork Job ID: 1801433825996987873</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 102816669</li>
<li>Krishna2323 | Contributor | 102816670</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by lanitochka17** [comment] 2024-06-10 18:38
@francoisl  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-10 18:38
We think that this bug might be related to #wave-collect - Release 1

**Comment by luacmartins** [comment] 2024-06-10 18:38
I'm gonna demote this to NAB since it doesn't break anything and is a small issue

**Comment by francoisl** [comment] 2024-06-10 19:10
Just compared with production and we used to use a placeholder icon instead of the "Map pending" view:

<img width="356" alt="Screenshot 2024-06-10 at 12 01 59 PM" src="https://github.com/Expensify/App/assets/2229301/5bf29fed-119e-484d-98c8-476e1997cdae">

It sounds like a minor issue coming from https://github.com/Expensify/App/pull/39243, cc @FitseTLT @mollfpr what do you think?

**Comment by zoro008-svg** [comment] 2024-06-15 06:49
When multiple expenses are created, the map view does not scale appropriately to accommodate all expense entries.

Scaling Adjustment: Implement a dynamic scaling mechanism for the map view based on the number of expenses being created.
Visibility Enhancement: Ensure that all markers or map elements are fully visible and accessible to users without overlapping or clipping.

Implement changes to the map component to resolve scaling and visibility issues.
Conduct thorough testing to verify that the map behaves as expected when creating multiple expenses.
Provide documentation or comments in the codebase explaining the implemented changes

Why I’m a Suitable Candidate:
Problem-Solving Skills: I excel in identifying and resolving frontend issues, ensuring optimal user experience.
Collaborative Approach: I am committed to working closely with Expensify’s team to deliver solutions that meet their requirements and enhance product usability.

I acknowledge the issue and propose to resolve it using the outlined technical approach.
Upon acceptance, I will proceed to post my proposal on Upwork as per Expensify’s guidelines.
Once hired, I will promptly initiate work on implementing the proposed solution and conduct thorough testing to ensure quality and functionality.
By structuring your response in this manner, you demonstrate a clear understanding of the issue, propose a feasible solution, and highlight your qualifications and commitment to addressing Expensify's needs effectively. Adjust the details according to your specific experience and the requirements outlined in the GitHub issue to create a compelling proposal.

**Comment by ikevin127** [comment] 2024-06-15 08:57
@zoro008-svg Please make sure you read [Contributing to Expensify](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and once you have a good grasp please format your [comment](https://github.com/Expensify/App/issues/43420#issuecomment-2169165674) to match the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1) if you are interested in fixing this issue, otherwise it won't qualify for review.

**Comment by zoro008-svg** [comment] 2024-06-15 09:38
> @zoro008-svg Please make sure you read [Contributing to Expensify](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and once you have a good grasp please format your [comment](https://github.com/Expensify/App/issues/43420#issuecomment-2169165674) to match the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1) if you are interested in fixing this issue, otherwise it won't qualify for review.

Contributor details
Your Expensify account email: [ahadnan.bex@gmail.com](mailto:ahadnan.bex@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d227ef6816d3f37c?mp_source=share

**Comment by zoro008-svg** [comment] 2024-06-15 09:41
Contributor details
Your Expensify account email: [ahadnan.bex@gmail.com](mailto:ahadnan.bex@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01d227ef6816d3f37c?mp_source=share

**Comment by zoro008-svg** [comment] 2024-06-15 09:43
Contributor details
Your Expensify account email: ahadnan.bex@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d227ef6816d3f37c

**Comment by truph01** [comment] 2024-06-16 10:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "Map pending" is not fully visible, and it is displayed in multiple lines in the report preview.

### What is the root cause of that problem?
- We always set the ```mapPadding``` to ```50``` in this logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/ConfirmedRoute.tsx#L111

- The current value is effective when there are only one or two thumbnails. However, with more than two thumbnails, this value becomes disproportionately large relative to the map size, resulting in insufficient remaining space to display routes or waypoints effectively.
### What changes do you think we should make in order to solve the problem?
- We can change that value to the smaller value if there are more than two thumbnails, for example, ```10```.

### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment] 2024-06-16 10:42
## Proposal
 
### Please re-state the problem that we are trying to solve in this issue.
- "Map pending" is not fully visible, and it is displayed in multiple lines in the report preview.

### What is the root cause of that problem?
- We always set the ```mapPadding``` to ```50``` in this logic:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/ConfirmedRoute.tsx#L111

- The current value is effective when there are only one or two thumbnails. However, with more than two thumbnails, this value becomes disproportionately large relative to the map size, resulting in insufficient remaining space to display routes or waypoints effectively.
### What changes do you think we should make in order to solve the problem?
- We can change that value to the smaller value if there are more than two thumbnails, for example, ```10``` (Can be modify when implementing PR). Below is the details:
- First, we need to pass down the ```numberOfShownImages``` in this:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/ReportActionItem/ReportActionItemImages.tsx#L47
to the ```ConfirmedRoute``` component.

- Then update this:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/components/ConfirmedRoute.tsx#L111
to:
```
            mapPadding={numberOfShownImage > 2 ? 10 : 50}
```


### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-06-17 07:43
♻️ Will review existing proposals today!

**Comment by truph01** [comment] 2024-06-17 12:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- "Map pending" text is not fully visible, and it is displayed in multiple lines in the report preview.

### What is the root cause of that problem?
- In Android, in this [PR](https://github.com/Expensify/App/pull/27395), we need to add the view "Map pending ..." to fix the issue "Wrong location briefly shows before San Francisco upon first open of the Distance request page in android native". (I name it as change 1)
- In this [PR](https://github.com/Expensify/App/pull/39243), we display the map routes instead of the placeholder icon. (I name it as change 2)

- The change 2 does not cover the case in change 1, that leads to the current behavior.
### What changes do you think we should make in order to solve the problem?
- We can update:
https://github.com/Expensify/App/blob/2eb3b4851a3c0413b109b06d45bced6885e46989/src/components/ReportActionItem/ReportActionItemImage.tsx#L80
to:
```
    if (showMapAsImage && getPlatform() !== 'android') {
```
so in Android native, it will display as it is when we did not implement change 2.

### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-06-18 03:03
@truph01 Thanks for your proposal. Unfortunately your RCA is not detailed enough even though it pointed out the offending PRs, additionally the proposed solutions don't align with what we want here code-wise or from a UI point of view.

##

If interested, here's some additional feedback regarding your proposal:
1. While you **correctly** identified the PRs which led to this issue, **more** and **clearer** details would help a reviewer actually make sense of the specific part which led to the issue's root cause.
2. When it comes to the **solution**, a few bullet points which would help greatly improve your future proposals:
    - We're generally against platform-specific code (e.g. `Platform.OS === "android"` conditions), instead we're following the [Platform-Specific File Extensions](https://github.com/expensify/app?tab=readme-ov-file#platform-specific-file-extensions) model to implement platform-specific code when necessary.
    - Whis suggestion ties into the one above ^ and it's about looking out for already-existing platform-specific files and suggest solutions which implement changes there instead of adding additional code / logic when not necessary.
    - Regarding the alternative solution, again, we're trying to keep the code **DRY** (don't repeat yourself) and this also means that we're mindful of adding more code to the codebase like effects and conditions when these are not absolutely necessary.
    - It's always a good idea to look into the involved components **existing props** which could help you come up with a more holistic solutions.

**Comment by ikevin127** [comment] 2024-06-18 03:46
@Krishna2323 Thank you for your proposal. I'm afraid the RCA is only partially correct as in: that's the component that displays the bug of this issue on Android: Native. I initially thought your main solution (2.) would be the right way to go here but upon further testing I noticed that the solution would create regressions in other parts of the distance expense flow where the same component is displayed.

Note: The alternative solution would also break things since it would completely remove `BlockingView` instead of replacing it with `PendingMapView` as the main solution suggests and is demonstrated in the video below.

Here's the current vs your solution (2.) preview on **Android: Native**:

<details>
<summary>Android: Native</summary>

| Current | Proposal 1 |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/d63908e0-025e-4d4e-97ba-958c14066916"> | <video src="https://github.com/Expensify/App/assets/56457735/17105787-35a5-49ac-ae22-057684e7db63">  |

</details>

The same thing happens on **web-based** and **all other platforms**:

<details>
<summary>MacOS: Web</summary>

https://github.com/Expensify/App/assets/56457735/8e0cd9e7-1fbb-42e8-a13e-9f9c7d50f180

</details>

**Note:** In order to get the Map Pending state you have to simulate **not having the mapbox access code** available. I did this locally by changing `return !isOffline && !!accessToken && !!currentPosition` in MapView.tsx / MapView.website.tsx to `!accessToken` (falsy).

##

The problem with this issue originates in the `ConfirmedRoute` component where `DistanceMapView` splits into the following logic:

**DistanceMapView**
 ┣ index.android.tsx (which contains separate logic for `isMapReady` compared to `MapView.tsx`)
 ┃ -> MapView.tsx
 ┃ -> BlockingView.tsx
 ┣ index.tsx (no separate logic, goes straight to `MapView.tsx`)
 ┃ -> MapView.tsx

similarly for the `MapView` component:

**MapView**
 ┗ index.tsx (used by all platforms **except** Web, mWeb and Desktop)
 ┗ index.website.tsx (used **only** on Web, mWeb and Desktop)

The reason why we notice the issue easier on Android: Native is because the MapBox can take longer to initialize with the `accessToken` compared to Web / mWeb / Desktop which are all web based platforms and the mapbox is faster.
But nonetheless - the issue is present on all platforms.

##

> [!Note]
> For now we're **still looking for a proposal** which can address the issue on all platforms, **without** breaking other parts of the distance request flow.

##

cc @Expensify/design Since we're dealing with more complicated logic here when it comes to UI / UX, some of you might want to chime in and let us know what we're expecting here since the current **expected result** doesn't make much sense if you ask me.

**Comment by truph01** [comment] 2024-06-18 04:28
@ikevin127 Thanks for your feedback. I've updated my RCA and proposed an alternative solution. Please review them when you have a chance. Link to the proposal https://github.com/Expensify/App/issues/43420#issuecomment-2173284262

**Comment by ikevin127** [comment] 2024-06-18 05:07
Thanks for the updates, I will check again **after** we get some feedback from the design team regarding the expected result from a UI point of view.

> [!note]
> I'd suggest not to update your proposals until we get some feedback from the design team in order to not waste time with solutions which might not align with the final design requirements.

##

> @ikevin127, I don't think the issue is present on all platforms, are you able to reproduce on other platforms?

No, I am not able to reproduce on other platforms following the same steps.

However, as I mentioned above, because of the way in which mapbox is initialized:

> The reason why we notice the issue easier on Android: Native is because the MapBox can take longer to initialize with the accessToken compared to Web / mWeb / Desktop which are all web based platforms and the mapbox is faster.
But nonetheless - the issue is present on all platforms.

What I mean by this is that on web-based platforms, the mapbox initialization is almost instant and is persisted: once initialized in the distance confirmation page, when request is made and added to the report preview -> the map is already initialized so we won't see the map pending view in the report preview -> the map will load right away.

But if for whatever reason (mapbox service down, bad accessCode, or initialization will timeout due to bad internet / no internet) -> the user will notice the same issue on web:

<details>
<summary>MacOS: Web</summary>

https://github.com/Expensify/App/assets/56457735/8e0cd9e7-1fbb-42e8-a13e-9f9c7d50f180

</details>

I mentioned how this can be tested (if one has access to the codebase locally):

> Note: In order to get the Map Pending state you have to simulate not having the mapbox access code available. I did this locally by changing return !isOffline && !!accessToken && !!currentPosition in MapView.tsx / MapView.website.tsx to !accessToken (falsy).

Given this, my objective here is to fix the issue for all platforms, even if the testers won't be able to verify the fix on web-based platforms.

##

**Note:** In the meantime, I'll try to find steps to reproduce the issue on the other platforms as well, but I think we should fix it regardless.

##

Unless @francoisl or anybody else disagrees and thinks we should only fix it on **Android: Native** because only there we can actually reproduce it due to differences in mapbox initialization between platforms.

**Comment by dannymcclain** [comment] 2024-06-18 13:42
Hmm, I thought we already took care of this [with this PR](https://github.com/Expensify/App/pull/39243) 🤔

[This video](https://github.com/Expensify/App/pull/39243#pullrequestreview-2092746776) shows the expected behavior. The preview should show the placeholder map image until we have the actual map to display—then the actual map preview should replace the placeholder image. The "map pending" text should never show in the preview. Does that make sense?

**Comment by truph01** [comment] 2024-06-18 16:25
> https://github.com/Expensify/App/pull/39243#pullrequestreview-2092746776 shows the expected behavior

- The video you mentioned is in offline mode. Our current bug is in online and only encountered in Android, where the "Map pending" text still appears.

**Comment by dannymcclain** [comment] 2024-06-18 16:31
>The video you mentioned is in offline mode. Our current bug is in online and only encountered in Android, where the "Map pending" text still appears.

I understand, I'm just saying that video shows the expected behavior if we don't have the route map, regardless of whether you're offline or not. If we don't have the full map, we should show the map placeholder icon until we do, and then swap the placeholder for the route map.

**Comment by ikevin127** [comment] 2024-06-18 23:42
## Summary

Given **dannymcclain**'s input from https://github.com/Expensify/App/issues/43420#issuecomment-2176136920 and https://github.com/Expensify/App/issues/43420#issuecomment-2176518358 we can conclude the **expected result**:

1. The "map pending" text **should never show in the expense preview**. "Preview" means 1, 2, 3 or more expenses:

      <details>
      <summary>See the preview variations</summary>
      
      | 1 | 2 | 3 |
      | ------------- | ------------- | ------------- |
      | <img width="215" alt="Screenshot 2024-06-18 at 15 49 27" src="https://github.com/Expensify/App/assets/56457735/9e0412de-0e05-4b69-9b13-a375f461324a"> | <img width="219" alt="Screenshot 2024-06-18 at 15 49 38" src="https://github.com/Expensify/App/assets/56457735/ebb7455c-a700-47cc-8179-8136d273498d"> | <img width="217" alt="Screenshot 2024-06-18 at 15 50 17" src="https://github.com/Expensify/App/assets/56457735/28747caf-0780-4eed-adab-527021e2e962"> |
      
      </details>

2. Point (1.) from above should apply regardless of being **online** or **offline**.
3. While map is pending, the expense preview should show the following map placeholder icon:

| <img width="217" alt="Screenshot 2024-06-18 at 15 50 17" src="https://github.com/Expensify/App/assets/56457735/28747caf-0780-4eed-adab-527021e2e962"> |

## Conclusion

Given the 🟢 from design, I think the **expected result** is clear enough and if still interested -> the proposals should be updated to reflect the updated expected result.

**Comment by ikevin127** [comment] 2024-06-19 22:23
> I have also added option 3 in my proposal but I still prefer option 1 as the solution.

@Krishna2323 The reason I wasn't comfortable with option 1 code-wise is because I'm against the idea of prop-drilling components. But given that the solution works I think the other details can be worked on during PR.

**Here's what I need in order for the solution to be accepted**:
1. Pass `requireRouteToDisplayMap` to ConfirmedRoute's `DistanceMapView` component as a prop and use it only in `index.android.tsx` something like this:
```ts
{!isMapReady && (
    <View style={[styles.mapViewOverlay, overlayStyle]}>
         // MAKE SURE TO ADD A COMMENT HERE EXPLAININMG WHY WE DID THIS
        {requireRouteToDisplayMap ? (
            // MAKE SURE THIS IS STYLED CORRECTLY SO WE DON'T GET REGRESSIONS ANYWHERE IN DISTANCE FLOW
            <PendingMapView isSmallerIcon />
        ) : (
            <BlockingView
                icon={Expensicons.EmptyStateRoutePending}
                title={translate('distance.mapPending.title')}
                subtitle={isOffline ? translate('distance.mapPending.subtitle') : translate('distance.mapPending.onlineSubtitle')}
                shouldShowLink={false}
                iconColor={theme.border}
            />
        )}
    </View>
)}
```
2. Make sure the change is styled accordingly since currently the styling looks bad on different stages of the preview:

| 1 | 2 | 3 |
| ------------- | ------------- | ------------- |
| <img width="335" alt="1" src="https://github.com/Expensify/App/assets/56457735/dbdf6388-6745-479a-a25f-2f1be9733e6d"> | <img width="338" alt="2" src="https://github.com/Expensify/App/assets/56457735/245b77c9-aac4-4c88-a527-0292b36fa789"> | <img width="336" alt="3" src="https://github.com/Expensify/App/assets/56457735/6d123bec-721e-4dfe-b556-899e31f17806"> |

**Comment by ikevin127** [comment] 2024-06-19 22:32
@truph01 I tested your **alternative solution** and it would introduce serious regressions in the distance request flow due to the usage of `interactive` prop which I think it's not the right prop to use for fixing our issue, see the video below:

**Note:** Ignore the report loading error as that's not related to your solution.

https://github.com/Expensify/App/assets/56457735/1331abfc-8922-494e-ab84-34af670c48dd

**Comment by ikevin127** [comment] 2024-06-20 20:07
Thanks for working with us to get this to a desirable final result 🎉 

##

@Krishna2323's [updated proposal](https://github.com/Expensify/App/issues/43420#issuecomment-2173129986) looks good to me. **Root cause** was identified correctly and the updated main **solution** (1.) fixes the issue as per the updated [expected result](https://github.com/Expensify/App/issues/43420#issuecomment-2177259287) agreed upon with the design team.

The solution tests well and looks great on both themes:

<details>
<summary>Android: Native (preview)</summary>

| Dark | Light |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/4fc0bc62-be69-41bc-a05b-9a61e8efa07b"> | <video src="https://github.com/Expensify/App/assets/56457735/e1335743-2892-4016-a303-81c5a1ed4260"> |

</details>

🎀👀🎀 C+ reviewed

## PR Notes
Please make sure to add the code-comment as suggested in https://github.com/Expensify/App/issues/43420#issuecomment-2179522570:

```ts
{!isMapReady && (
    <View style={[styles.mapViewOverlay, overlayStyle]}>
         // MAKE SURE TO ADD A COMMENT HERE EXPLAININMG WHY WE ADDED THIS LOGIC // <- HERE
        {requireRouteToDisplayMap ? (
            // MAKE SURE THIS IS STYLED CORRECTLY SO WE DON'T GET REGRESSIONS ANYWHERE IN DISTANCE FLOW
            <PendingMapView isSmallerIcon />
        ) : (
            <BlockingView
                icon={Expensicons.EmptyStateRoutePending}
                title={translate('distance.mapPending.title')}
                subtitle={isOffline ? translate('distance.mapPending.subtitle') : translate('distance.mapPending.onlineSubtitle')}
                shouldShowLink={false}
                iconColor={theme.border}
            />
        )}
    </View>
)}
```

**Comment by ikevin127** [comment] 2024-07-07 21:55
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27395
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27395/files#r1667770691
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

Precondition: User is member of a workspace.

1. Open the workspace chat.
2. Create more than 1 distance expenses.
3. Right after creating the distance expense, in report IOU preview -> verify that the pending icon is shown (see [reference](https://github.com/Expensify/App/issues/43420#issuecomment-2181476581)) as opposed to the `map pending` text.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-07-10 00:07
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27395
* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27395/files#r1667770691
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

## Regression Test Proposal

Precondition: User is member of a workspace.

1. Open the workspace chat.
2. Create more than 1 distance expenses.
3. Right after creating the distance expense, in report IOU preview -> verify that the pending icon is shown (see [reference](https://github.com/Expensify/App/issues/43420#issuecomment-2181476581)) as opposed to the `map pending` text.

Do we agree 👍 or 👎.

**Comment by francoisl** [comment] 2024-07-10 00:41
Works for me. Opened an internal issue to create the regression tests – https://github.com/Expensify/Expensify/issues/411499

**Comment by ikevin127** [comment] 2024-07-10 23:26
cc @JmillsExpensify Friendly bump for payments!

**Comment by greg-schroeder** [comment] 2024-07-11 11:48
@JmillsExpensify I paid this given the contributor pinged about it - I'll file the regression test proposal as well given I am already here.

**Closed** 2024-07-11 11:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-11 18:34
Thanks so much @greg-schroeder
