### ISSUE TITLE
[$250] Track expense - System message appears on wrong LHN report after changing merchant or desc

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42858] opened 2024-05-30 18:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Open personal report
3. Create a tracked expense
4. Update either the description or the merchant of the tracked expense

## Expected Result:
System message indicating merchant or description being updated gets displayed on LHN for the combined report of the tracked expense only

## Actual Result:
System message indicating merchant or description being updated is shown on the LHN of the personal space report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4b095fa-7c13-433e-b93e-d4955399a2e4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e89fac46add8bf9d</li>
        <li>Upwork Job ID: 1797717388975722496</li>
        <li>Last Price Increase: 2024-06-03</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 102627885</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allroundexperts</details>

**Comment by lanitochka17** [comment] 2024-05-30 18:24
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-05-30 18:24
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by c3024** [comment] 2024-06-01 14:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
System message (like changing of merchant) appears as subtitle of self DM in LHN. It should only appear as last message in the transaction thread and not in the selfDM in LHN.
### What is the root cause of that problem?
This bug happens only when there is only one transaction in the self DM report.
Here in `OptionsListUtils` 
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/OptionsListUtils.ts#L291-L299
we merge the transaction thread report actions into IOU report actions if it is oneTransactionThreadReport so the last transaction of modified merchant is added into the report actions and set as the lastReportAction. In the present case of self DM, the lastMessage of modifying merchant appears on the LHN.

But this merging of transaction thread report actions for single transaction reports is not applicable for self DM because unlike other reports the tracked expenses are shown as separate report actions here instead of a single report preview merging all IOUs as shown in other reports.

Additionally, we don't see this report action of modifying merchant in the self DM report screen though the transaction report actions are added here as well 
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/home/report/ReportActionsView.tsx#L160
with `transactionThreadReportActions` obtained from onyx with the `transactionThreadReportID` passed from `ReportScreen` 
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/home/ReportScreen.tsx#L331-L334
This is because there is a check here when getting the `getOneTransactionThreadReportID`
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/ReportActionsUtils.ts#L878-L887
and it returns `null` when the `skipReportTypeCheck` is passed as `false` as seen here for track expenses because it is not one of the actions being checked there
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/pages/home/ReportScreen.tsx#L332
whereas it is passed as `true` here 
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/OptionsListUtils.ts#L293
which skips the check. If the check is not skipped it returns `null` and LHN shows correct message.
### What changes do you think we should make in order to solve the problem?
We can check if the report is self DM and pass the boolean here
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/OptionsListUtils.ts#L293
like
```js
const isSelfDM = ReportUtils.isSelfDM(ReportUtils.getReport(reportID));

            // If the report is a one-transaction report and has , we need to return the combined reportActions so that the LHN can display modifications
            // to the transaction thread or the report itself
            const transactionThreadReportID = ReportActionUtils.getOneTransactionThreadReportID(reportID, actions[reportActions[0]], !isSelfDM);
            
```
### What alternative solutions did you explore? (Optional)
I see this skip of check added here in #39472 for showing correct messages in LHN for edge cases. I changed the skipcheck to `false` in `OptionsListUtils` directly (irrespective of whether it is a self DM or not) and the tests succeeded fine. So, we might consider changing this 
https://github.com/Expensify/App/blob/0cb2dc052f01b6a024ac872ad8bf628159fe7873/src/libs/OptionsListUtils.ts#L293
simply to
```js
const transactionThreadReportID = ReportActionUtils.getOneTransactionThreadReportID(reportID, actions[reportActions[0]], false);
```

**Comment by allroundexperts** [comment] 2024-06-04 15:06
Reviewing today.

**Comment by allroundexperts** [comment] 2024-06-04 19:59
@c3024's [proposal](https://github.com/Expensify/App/issues/42858#issuecomment-2143466075) looks good to me. I would suggest to go with the main proposal since its less likely to cause a regression.

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment] 2024-06-06 04:45
> I see this skip of check added here in https://github.com/Expensify/App/pull/39472 for showing correct messages in LHN for edge cases. I changed the skipcheck to false in OptionsListUtils directly (irrespective of whether it is a self DM or not) and the tests succeeded fine. So, we might consider changing this

I just double-checked this, and the behavior without the `skipReportType` check is fine for me as well. Even though I agree with @allroundexperts that it's more likely to cause regressions, I think we should use the alternative proposal, but go one step further and remove the `skipReportTypeCheck` altogether since it's apparently unnecessary now. 

@allroundexperts @c3024 how does that sound to you?

**Comment by c3024** [comment] 2024-06-06 13:49
Yes, let's remove it. I don't think anything will be broken.

**Comment by c3024** [comment] 2024-06-07 13:08
@allroundexperts PR ready for review!

**Comment by c3024** [comment] 2024-06-18 17:15
@johncschuster This was deployed to production 4 days ago but automation failed here.

**Comment by c3024** [comment] 2024-06-25 14:24
@johncschuster Can you please complete the payment here? This was deployed to production 10 days ago. Thanks!

**Comment by mallenexpensify** [comment] 2024-06-26 18:47
Contributor: @c3024 paid $250 via Upwork
Contributor+: @allroundexperts due $250 via NewDot

@allroundexperts can you fill out the BZ checklist plzzzz

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:
- [ ]

**Comment by allroundexperts** [comment] 2024-06-28 06:57
On to the checklist today.

**Comment by allroundexperts** [comment] 2024-06-30 13:51
## Checklist

1. https://github.com/Expensify/App/pull/36934
2. The PR author (@NikkiWines) is aware of the bug already.
3. N/A
4. A regression test would be helpful.

## Regression test

1. Login to any account and open the chat with yourself (personal report)
2. Create a tracked expense
3. Update either the description or the merchant of the tracked expense

Verify that the system message indicating merchant or description being updated gets displayed on LHN for the combined report of the tracked expense only.

Do we 👍 or 👎 ?

**Comment by mallenexpensify** [comment] 2024-07-02 23:21
Thanks @allroundexperts 
- https://github.com/Expensify/Expensify/issues/409882

**Closed by mallenexpensify** 2024-07-02 23:21 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-20 17:22
$250 approved for @allroundexperts
