### ISSUE TITLE
[$500] Web - The 'green line and new text' doesn't appear when you click mark unread for the last completed task text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28023] opened 2023-09-22 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat > Assign Task
2. Complete the task by clicking the box
3. Reopen the task by clicking the box
4. Repeat step 3 and 4 and complete the task
5. Hover over on each completed and reopened task text's and try to mark unread

## Expected Result:
The green line should appear for the last completed task text

## Actual Result:
The green line doesn't appear for the last completed task text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/79bfef17-1ddd-49cc-babc-37423f40f92d

https://github.com/Expensify/App/assets/93399543/056a68a9-0589-461b-a84c-c57d1f5e6cec

**Expensify/Expensify Issue URL:**
**Issue reported by:** @@Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695215232530069
 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0137062903059fb1b7</li>
        <li>Upwork Job ID: 1705235664586768384</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-24 11:56
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The 'green line and new text' doesn't appear when you click mark unread for the last completed task text

### What is the root cause of that problem?
The context menu loses references to the correct report actions due to `originalReportID`:

https://github.com/Expensify/App/blob/4ea4a55ad2c9ecdb66d45cc1872612ea22e4605f/src/pages/home/report/ContextMenu/BaseReportActionContextMenu.js#L174-L177

With the `originalReportID`,  report actions other than `CREATED` and `ADDCOMMENT` are not included.

### What changes do you think we should make in order to solve the problem?
Change `originalReportID` to `reportID` so that it includes the complete report actions:
```
 reportActions: {
            key: ({reportID}) => `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
            canEvict: false,
 },
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by akamefi202** [comment] 2023-09-27 07:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "green line and new text" doesn't appear in correct position when you click "Mark as unread" for completed/reopened task texts. It only appears over the last task action text.

### What is the root cause of that problem?
![Untitled](https://github.com/Expensify/App/assets/53784473/bcaa1806-bb1a-4ff2-a7ea-453ec7f8cbb5)

Every task action message contains data of child report, which is the report of current task.

https://github.com/Expensify/App/blob/d61f55ac16b797f831e4cb1b9669ba326ac7b8f9/src/libs/ReportUtils.js#L690-L692

So every task action message is recognized as first chat message by `isThreadFirstChat` function.

https://github.com/Expensify/App/blob/d61f55ac16b797f831e4cb1b9669ba326ac7b8f9/src/libs/ReportUtils.js#L3439-L3441

If it's first chat message, `getOriginalReportID` function returns ID of parent report to get correct action data.

But for this issue, it's not working correctly.
Because we can get data of task action messages from task report, not parent report.

### What changes do you think we should make in order to solve the problem?
To fix this issue in FE without affecting other parts, I think we need to fix `getOriginalReportID` function.
We need to add below code so we can get correct report ID.

```
if (ReportActionsUtils.isTaskAction(reportAction)) {
    return reportID;
}
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by strepanier03** [comment] 2023-09-27 23:21
Was out of the office but I'm back now. Triaging this and will update.

**Comment by strepanier03** [comment] 2023-09-27 23:38
I'm not able to recreate the behavior in the OP comment video. 

----

Mac/OS Chrome
staging.new.expensify.com

Marking unread puts the greenline on the last message. 

https://github.com/Expensify/App/assets/10925636/2911d974-b6d5-44f2-8fc5-a17da8013cf9

**Comment by strepanier03** [comment] 2023-09-27 23:39
@@Yokabdk @kbecciv - Are you still able to recreate this? It looks correct to me in my testing.

**Comment by strepanier03** [comment] 2023-10-02 21:46
Tried again and it's working as expected. No updates from the reporter or QA so I'm closing for now and we can reopen if we need to.

**Closed by strepanier03** 2023-10-02 21:46 UTC
Labels: External, Daily, Needs Reproduction, Help Wanted, Bug
