### ISSUE TITLE
Too much space between avatar and sender name in report page header

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39981] opened 2024-04-10 01:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712676235201539

## Action Performed:
1. go to staging.new.expensify.com and sign in 
2. Open any expense report
3. Click on the preview
4. Observe the header

## Expected Result:
The sender name should be 12px to the right of the avatar

## Actual Result:
The sender name seems to be too far to the right
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-04-09 at 9 22 39 PM](https://github.com/Expensify/App/assets/38435837/d9250c63-1549-41f7-987f-a22ee0f5dfb2)

![CleanShot 2024-04-09 at 17 21 22@2x](https://github.com/Expensify/App/assets/38435837/54494ea3-e788-4cbd-bb05-6aa7dd238f18)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by bernhardoj** [comment] 2024-04-10 01:54
Dupe of https://github.com/Expensify/App/issues/39868

**Comment by shawnborton** [comment] 2024-04-10 07:09
Sounds good, we can close then.

**Closed by shawnborton** 2024-04-10 07:09 UTC
Labels: Daily, Bug
