### ISSUE TITLE
[$1000] Zoom view in the attachment preview is lost with 4 or more attachments

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18614] opened 2023-05-08 22:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open report with 4 or more image attachments
3. Open first image and zoom in
4. Navigate back 4 images and again navigate back to first image and observe that image is zoomed out
5. Repeat step 3 and 4 with 3 images in step 4 and observe that image is zoomed in

## Expected Result: 
App should remember zoomed in position throughout the attachment navigations as it does when we only navigate back 3 images
## Actual Result: 
Image is zoomed out when we navigate back 4 images in attachment preview

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236950717-3feb43b9-3263-4535-b4c9-a565cc919411.mp4

https://user-images.githubusercontent.com/43996225/236950730-c7c1c16f-e69a-48fe-a7e5-2db537b21442.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683535771247579

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0185edcdfdafdda6aa</li>
        <li>Upwork Job ID: 1657031802775678976</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by therealsujitk** [comment] 2023-05-09 09:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Zoom gets reset after navigating 3 attachments before or after.

### What is the root cause of that problem?

This isn't a bug, it's intended behaviour. To prevent devices from lagging/crashing it is limited to load **three** attachments at the same time, after which the furthest attachment gets unloaded to clear up cache. This is done using the `maxToRenderPerBatch` attribute in line *375* in the code shown below.

https://github.com/Expensify/App/blob/bc8cc52162dca556db0a9b4a4719d09682e49745/src/components/AttachmentCarousel/index.js#L347-L383

### What changes do you think we should make in order to solve the problem?


To keep behaviour consistent, we could store data related to the state of the attachment (such as position, scroll, etc.) in an array. This way we can restore it's state when it's reloaded. For this an attribute (ex: `initialState`) can be created in the `AttachmentView` component to specify what the view should look like when initially loaded.

### What alternative solutions did you explore? (Optional)

- One solution would be to disable navigation while an attachment is zoomed in like WhatsApp does.
- Another solution would be to reset zoom if navigated to keep behaviour consistent.

**Comment by michaelhaxhiu** [comment] 2023-05-09 12:34
small note: re-assigning as I'm OOO till next week

**Comment by maddylewis** [comment] 2023-05-09 22:49
i am OOO starting tomorrow but will try to repro this now / push this along

**Comment by maddylewis** [comment] 2023-05-10 23:14
whew, i am so sorry to do this @miljakljajic. i was reassigned this issue when i was about to take OOO and am confused by the repro steps / didn't have a chance to get to this one today. 

if you have a chance Thurs/Fri, could you try reproducing this one and adding the `external` or `internal` label for someone to start working on this one? 

then, once im back on Monday, i can take over triaging the issue from there. 

sorry again. i don't like pawning GHs off to others, but this one has already been sitting for 2 days so wanted to get it assigned to someone. thx!

**Comment by miljakljajic** [comment] 2023-05-12 14:35
I was able to reproduce this: 

https://github.com/Expensify/App/assets/28715117/e9b05c0c-d452-47c9-aee2-88daf4639222

No problem, Maddy. I'll OOO travelling to EC3 on Monday but you can pick it up from there.

**Comment by miljakljajic** [comment] 2023-05-15 08:03
Hey @maddylewis - travelling to EC3 so will unassign myself. Seems like you're back on today. Thank you!

**Comment by maddylewis** [comment] 2023-05-15 15:33
thanks, @miljakljajic !

**Comment by maddylewis** [comment] 2023-05-17 01:30
@fedirjh - when you have a chance, will you provide an update on which solution you're thinking we should go with? thx!

**Comment by therealsujitk** [comment] 2023-05-17 06:42
@fedirjh I've updated my proposal with the required information.

> One solution would be to disable navigation while an attachment is zoomed in like WhatsApp does.

This solution is by far the simplest, I haven't written much on it as it's already being used (explained in proposal).

**Comment by therealsujitk** [comment] 2023-05-18 00:39
@fedirjh there's another thing that should be considered here, PDFs will have something similar to this issue for scrolling as well i.e. the PDF scroll will get reset after navigating past 3 attachments.

Considering this issue what is the approach to take?
- Apply this fix only for zoom and ignore scrolling for now
- Don't fix either issue (Drop this issue completely)
- Something else

**Comment by therealsujitk** [comment] 2023-05-18 04:23
The best way to fix this would be to save the state of each attachment, but you might be right about it affecting performance. I don't think storing an array of the states in the state will affect performance as it would still take `O(n)` space since the attachments itself are also stored in an array, HOWEVER the problem arises while updating this state, react doesn't allow updating just a single element in the array, the whole array will have to be updated resulting in `O(n)` time for every single state update (ideally it would be `O(1)`). One way would be to store the attachment states individually with unique keys (`{'attachment_state_1': {}, 'attachment_state_2': {}}` instead of `{'attachment_states': [{}, {}]}`) but that seems too messy and not right.

If someone can provide some insight on this that would be great, otherwise dropping this might be the best option.

**Comment by therealsujitk** [comment] 2023-05-18 13:18
I just realised, we don't need to store the attachment states in the react state. Since we'll only be using it when the component mounts, we can store it as a normal variable. I've updated [my proposal](https://github.com/Expensify/App/issues/18614#issuecomment-1539824261) with this solution.

**Comment by therealsujitk** [comment] 2023-05-18 13:19
@fedirjh I just realised, we don't need to store the attachment states in the react state. Since we'll only be using it when the component mounts, we can store it as a normal variable. I've updated [my proposal](https://github.com/Expensify/App/issues/18614#issuecomment-1539824261) with this solution.

**Comment by therealsujitk** [comment] 2023-05-19 17:45
@fedirjh their GitHub repository says [it's possible to scroll to a page](https://github.com/wojtekmaj/react-pdf/issues/271) so I was thinking of saving the `scrollHeight` or something similar (will have to experiment), I can try it this weekend and let you know for sure how does that sound?

**Comment by therealsujitk** [comment] 2023-05-19 17:59
It won't be possible to get an element easily from a `Set` (plus we'll need the previous state), but we can use an `Object` with the index as key (or a `Map`, not sure which is better). Unless I've misunderstood what you're suggesting?

**Comment by therealsujitk** [comment] 2023-05-19 18:29
I'll test for that case too (add and delete attachment while the carousel is open), I remember seeing some issue open about the carousel getting closed when an attachment is deleted earlier today.

Anyway, I'll create the branch, if everything goes well it should be ready for you by Monday.

**Comment by michaelhaxhiu** [comment] 2023-05-20 13:54
@maddylewis if you like I can take this back since I am back from OOO (in light of the new internal process for re-assigning GHs during/after OOO)

**Comment by therealsujitk** [comment] 2023-05-20 16:49
@fedirjh the branch is ready! - [`fix-1814`](https://github.com/therealsujitk/expensify-app/tree/fix-18614). It works quite well from what I've tested, one tiny issue is that the `react-native-pdf` package we use only has a `setPage()`, you can't scroll to a point so on native devices it'll scroll to the page that the user was viewing which may not be the *exact* scroll position but it'll be pretty close.

**Comment by kidroca** [comment] 2023-05-24 09:47
Hi @fedirjh,

Thanks for looping me into this discussion. You've correctly pinpointed the issue to be with the FlatList virtualization. However, I'd like to clarify that `maxToRenderPerBatch` merely decides the number of images to render per unit of time (imagine rendering 3 images no more often than every 100ms). The actual cause of the problem lies in the `windowSize={5}` setting, which permits a maximum of 5 attachments to be mounted—two each on either side of the current page.

From what I understand, the proposed solution aims to preserve the state of the attachment, which I see could be beneficial especially for document attachments with multiple pages—allowing users to return to the last viewed page. For image attachments, however, I'm wondering about the user experience of returning to a previously zoomed-in state. Could you shed some light on any particular use-cases where this might be beneficial?

If maintaining the attachment state is indeed a key requirement, allow me to suggest an alternative that I believe is simpler. It wouldn't necessitate altering the individual attachment components to satisfy the Carousel. 

The `windowSize={5}` setting has always been more about network performance (reducing simultaneous loading) rather than rendering performance. We certainly wouldn't want to initiate multiple attachment loads as soon as the Carousel is opened. However, progressively increasing the number as we navigate through the carousel images should pose no issues.

Why not consider maintaining a Set of unique items that have already been rendered, and then using this Set to determine the `windowSize`?

```jsx
renderedItems = new Set();

renderItem({ item }) {
  this.renderedItems.add(item);
  return <Item ... />
}

render() {
  return <FlatList ... windowSize={Math.max(5, this.renderedItems.size)} />
}
```

As we render more images, the window size would gradually increase, keeping the already loaded attachments from unmounting and hence preserving their state. What do you think of this approach?

**Comment by therealsujitk** [comment] 2023-05-24 13:47
> Thanks for looping me into this discussion. You've correctly pinpointed the issue to be with the FlatList virtualization. However, I'd like to clarify that `maxToRenderPerBatch` merely decides the number of images to render per unit of time (imagine rendering 3 images no more often than every 100ms). The actual cause of the problem lies in the `windowSize={5}` setting, which permits a maximum of 5 attachments to be mounted—two each on either side of the current page.

Ah, I was mistaken. I said `maxToRenderPerBatch` based on the the number `3` :sweat_smile:.

> For image attachments, however, I'm wondering about the user experience of returning to a previously zoomed-in state. Could you shed some light on any particular use-cases where this might be beneficial?

This was done mainly to keep it consistent, but there could be a case where the attachment has some text written on it (say a receipt) and the user would like it to be zoomed in while they're navigating through attachments.

> Why not consider maintaining a Set of unique items that have already been rendered, and then using this Set to determine the `windowSize`?

This is a good idea, I never thought of that. However, I have a few concerns.

1. Will there be a case where the `FlatList` component ignores the `windowSize` prop due to lack of system resources, I feel there's a possibility of this so the application wouldn't crash.
2. This approach could slow done the system as more and more attachments are added especially if they are heavy. And again there may be a possibility that `FlatList` destroys attachments to prevent crashes.

**Comment by kidroca** [comment] 2023-05-24 15:16
> 1. Will there be a case where the `FlatList` component ignores the `windowSize` prop due to lack of system resources, I feel there's a possibility of this so the application wouldn't crash.

While it's a valid consideration, it's important to note that the FlatList component isn't designed to manage system resources. Instead, it will simply attempt to perform the task we've specified. If we start to notice any performance degradation, it will be our responsibility to revisit and refine our solution accordingly.

> 2\. This approach could slow down the system as more and more attachments are added especially if they are heavy. And again there may be a possibility that `FlatList` destroys attachments to prevent crashes.

Indeed, an excessive number of image attachments could pose a performance challenge. However, this would only be an issue if the user scrolls past hundreds of images. We can manage this effectively by setting an upper limit.

```jsx
const desiredSize = Math.max(5, this.renderedItems.size);
const windowSize = Math.min(100, desiredSize);
```

This boundary ensures that the window doesn't grow beyond a manageable size. While technically the issue could still occur, we have to ask: would a user realistically zoom into an attachment, scroll 100 attachments away, and then scroll back?

A potential complementary or standalone solution to the virtual window size could involve using [react-freeze](https://www.npmjs.com/package/react-freeze). This package preserves the component state while replacing off-screen items with a low-cost placeholder. It's a method we're already employing in a different part of the app.
We could render items outside the immediate view area as 'frozen' with the following:

```jsx
renderItem({ item, index }) {
  const diff = Math.abs(index - this.state.page);
  if (diff > 2) // return FreezedItem
  else // return RegularItem
}
```

This approach would ensure that off-screen items don't overly tax system resources while maintaining user experience continuity.

**Comment by MonilBhavsar** [comment] 2023-05-29 10:40
> The only concern is that we may have more memory consumption. I think we can limit the max windowSize to just 20 or maybe 10. It doesn’t looks realistic for a user to scroll 10 attachments away, and then scroll back and expects to get the maintained zoom state.

I agree with this 👍

**Comment by MonilBhavsar** [comment] 2023-05-29 10:48
> Users are experiencing a good and reasonable interaction, with the attachment state (including zoom and scroll position) being successfully preserved for the last 3 visited attachments.

Well, I personally think it is fair to maintain zoomed state for last 3 visited attachments. cc Bug-zero team - @maddylewis @miljakljajic @michaelhaxhiu
If not, we can :donothing: and consider this as "a feature and not a bug"

**Comment by maddylewis** [comment] 2023-05-31 20:30
@MonilBhavsar - i think we can consider this a feature and not a bug!

**Closed by maddylewis** 2023-05-31 20:30 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
