### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] IOU - Currency edit is saved when the edit is discarded in confirmation page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32826] opened 2023-12-11 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.11-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com.
2. Go to 1:1 DM > + > Request money.
3. Enter amount > Next.
4. On confirmation page, click Amount.
5. Click on the currency and select a different currency.
6. Click back button.

## Expected Result:
The previous currency is preserved as the new currency is not saved.

## Actual Result:
The new currency is saved when the changes are discarded.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/205d37a8-18fd-4b62-9634-5eb062d8d7c1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f3d94b5f2243152</li>
        <li>Upwork Job ID: 1734278105112006656</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Reviewer | 28037137</li>
<li>s-alves10 | Contributor | 28037138</li>
<li>situchan | Contributor | 28038451</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-12-11 16:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Currency edit is saved when the edit amount page is discarded in confirmation page

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/pages/iou/request/step/IOURequestStepCurrency.js#L81

As you can see above, we save the currency data when select the currency. 

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to implement the logic used [here](https://github.com/Expensify/App/blob/55903d45103ad446cb891dd1099d4e1dd7ea1ec1/src/pages/iou/IOUCurrencySelection.js#L110): use of `currency` query parameter

### What alternative solutions did you explore? (Optional)

**Comment by blimpich** [comment] 2023-12-11 17:47
I'm looking at this. Taking some time to understand the code before deciding on anything. @s-alves I've reviewed your proposal and like it, but I'm going to briefly spend some time seeing if adding the data to the url is the best way to do this. I will update this issue hourly and decide as soon as I can on how to proceed.

**Comment by blimpich** [comment] 2023-12-11 18:20
Okay after looking at the code and understanding a bit more I think your solution @s-alves10 is definitely what we want. Thank you for your patience. Assigning you.

**Comment by blimpich** [comment] 2023-12-11 18:27
Looks related to: https://github.com/Expensify/App/pull/28618/. Not going to revert that as that PR is huge and important and we have a solution proposed.

**Comment by s-alves10** [comment] 2023-12-11 19:50
@c3024 

PR is ready for review https://github.com/Expensify/App/pull/32851

**Comment by luacmartins** [comment] 2023-12-11 21:26
Requested an expedited C+ review [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1702329959171139)

**Comment by Julesssss** [comment] 2023-12-12 10:29
Merged and CP'd

**Comment by Christinadobrzyn** [comment] 2023-12-12 19:51
I'm not sure if this should remain open to be paid or if there's nothing to pay since this was a regression @Julesssss or @luacmartins could you clarify?

**Comment by luacmartins** [comment] 2023-12-12 19:53
We should pay @s-alves10 for the fix and @situchan for the review

**Comment by Christinadobrzyn** [comment] 2023-12-12 19:58
Awesome thanks @luacmartins  

Following this PR for payment - https://github.com/Expensify/App/pull/32851

**Comment by Christinadobrzyn** [comment] 2023-12-20 19:36
Ready for payment. Payouts due:

Issue Reporter: NA
Contributor: $500 @s-alves10 (paid in Upwork)
Contributor+: $500 @situchan (paid in Upwork)

Eligible for 50% #urgency bonus? N

Upwork job is [here](https://www.upwork.com/jobs/~018f3d94b5f2243152).

@situchan can you let me know about a regression test?

**Comment by situchan** [comment] 2023-12-20 19:39
We don't need another regression test as bug was caught during staging deploy test

**Comment by Christinadobrzyn** [comment] 2023-12-21 22:06
Awesome thanks @situchan 

Payments sent through Upwork based on this payment summary - https://github.com/Expensify/App/issues/32826#issuecomment-1865029133

this can be closed!

**Closed by Christinadobrzyn** 2023-12-21 22:06 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
