### ISSUE TITLE
Web -  Sender's name or email not displayed in the notification email sent by system

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23351] opened 2023-07-21 11:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to an account on Mobile
2. Receive a Request money request or a message from an Unknown account
3. Wait for the notification email sent by system
4. Check content "inside the email" and compare with the content on push notification

## Expected Result:
Email's content should contain information about who sent the request/message by showing sender's Name or Email

## Actual Result:
There is no information about sender's Name or Email, So I did know who made that request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43.5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Issue (1)](https://github.com/Expensify/App/assets/93399543/ebc79b9d-c045-4b57-83d7-b7f629f852e5)

![Correct (1)](https://github.com/Expensify/App/assets/93399543/8a427f44-9e4d-4063-b727-fbdce51fd877)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689881297643739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135d7e7e7e8ff970a</li>
        <li>Upwork Job ID: 1683806567577432064</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2023-07-21 12:15
Testing - waiting on IOU email

**Comment by garrettmknight** [comment] 2023-07-21 12:52
Confirmed the issue, but I think the behavior might actually be technically expected even though we should change it. Chatting with @puneetlath and @Beamanator in the slack thread to confirm since they worked on masking emails/usernames for secure logins.

**Comment by garrettmknight** [comment] 2023-07-24 17:22
Checking whether it needs to be Internal or whether we can have a contributor take it in the slack thread.

**Comment by srikarparsi** [comment] 2023-08-03 20:53
Messaged @Beamanator if he had any tips as I'm not able to find where the data is coming from.

**Comment by Beamanator** [comment] 2023-08-04 07:35
@srikarparsi I believe you're on the exact right track, I would look at this function for the logic:

https://github.com/Expensify/Web-Expensify/blob/06fa196fbf0ca8d86ca63421d5504f0a5a9281e4/lib/Notification/Report/Comment.php#L205-L242

**Comment by garrettmknight** [comment] 2023-08-07 16:47
@srikarparsi how we doing on this one?

**Comment by srikarparsi** [comment] 2023-08-08 05:48
Hey, didn't get to this today and was OOO friday but will provide an update tomorrow.

**Comment by srikarparsi** [comment] 2023-08-10 06:19
Hey wasn't able to get to this today either since I was focussing on wave 6 and other WAQ bugs but will try to get to this tomorrow as I'm OOO friday.

**Comment by srikarparsi** [comment] 2023-08-15 03:37
Got back from OOO today and was catching up on a bunch of PR reviews. I looked at the code and it seems like the subject of "IOU" might be being passed in the comment so I'm looking to find if that's being set anywhere to change it.

**Comment by srikarparsi** [comment] 2023-08-29 04:11
Hey sorry for the delay, worked on this a good bit on this one today but I'm having trouble figuring out where the subject is being set. I tried using Bondy's method [here](https://expensify.slack.com/archives/C03TQ48KC/p1693277917012519?thread_ts=1693272400.652549&cid=C03TQ48KC) and confirmed that the method is getting hit but am not too familiar with this section of the codebase so am having trouble back tracking. @Beamanator, would you be open to a call maybe tomorrow by any chance to work on it together?

**Comment by Beamanator** [comment] 2023-08-29 06:52
Hey @srikarparsi I think today will be pretty crazy busy for me, maybe we can try to chat Thurs or Friday?

**Comment by srikarparsi** [comment] 2023-08-29 16:13
Yeah cool! I just added a meeting for Thursday but I will investigate more today so will hopefully be able to figure it out by then.

**Comment by srikarparsi** [comment] 2023-09-06 07:42
Was catching up after the long weekend, reached a conclusion [here](https://expensify.slack.com/archives/C049HHMV9SM/p1693497454106399?thread_ts=1689881297.643739&cid=C049HHMV9SM) and will implement tomorrow.

**Comment by srikarparsi** [comment] 2023-09-11 08:10
Looked through the notification code and have a high level understanding. The solution we came up with is to include the names of the participants in the IOU similar to how we do it with a normal chat.

**Comment by srikarparsi** [comment] 2023-09-18 09:26
Working on it rn, should have a PR in the next hour

**Comment by srikarparsi** [comment] 2023-09-18 10:14
PR in review :)

**Comment by srikarparsi** [comment] 2023-09-26 05:24
PR's been merged, currently in staging

**Comment by srikarparsi** [comment] 2023-09-27 02:41
closing this out, prs been deployed to production :)

**Comment by tranvantoan-qn** [comment] 2023-09-27 03:00
I am waiting for the offer 😄

**Comment by garrettmknight** [comment] 2023-09-27 08:23
**Summary of payments for this issue:**
- Reporter: @tranvantoan-qn $250

Upwork Job: https://www.upwork.com/ab/applicants/1706946885960343552/job-details

**Comment by garrettmknight** [comment] 2023-09-27 08:23
Offer sent

**Comment by tranvantoan-qn** [comment] 2023-09-27 08:27
Thank you, I've accepted the offer

**Comment by garrettmknight** [comment] 2023-09-28 06:02
Paid, closing!

**Closed by garrettmknight** 2023-09-28 06:02 UTC
Labels: Engineering, Daily, Internal, Bug
