### ISSUE TITLE
[$500] Distance - Distance rate shows $TBD instead of TBD in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30376] opened 2023-10-25 18:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.91-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition:
- There is at least a workspace
- Log out and log in again and do not open workspace and request money page
1. Navigate to staging.new.expensify.com
2. Go offline
3. Go to + > Request money > Distance
5. Enter any start and finish point
6. Proceed to the confirmation page
7. Go to the distance request (preview, details page)

## Expected Result:
The distance rate shows TBD

## Actual Result:
The distance rate shows $TBD instead of TBD

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/42df684f-6a19-46ee-abd9-85289f7b2fb5

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ffaa57ea238f4625</li>
        <li>Upwork Job ID: 1717251966495088640</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-10-25 19:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance rate shows $TBD instead of TBD in offline mode


### What is the root cause of that problem?

The distance rate is determined [here](https://github.com/Expensify/App/blob/5dbfdf7cce7a383c153deb0508e21cfa6b4b4891/src/libs/DistanceRequestUtils.js#L95) where the currency symbol is attached to the ratePerUnit. However, the currency symbol is applied even when rate is not available. This is the root cause

### What changes do you think we should make in order to solve the problem?

To solve the problem, we need to set the `currencySymbol` to empty string if rate is invalid like this:

`const currencySymbol = rate ? CurrencyUtils.getCurrencySymbol(currency) || `${currency} ` : ‘’;`


### What alternative solutions did you explore? (Optional)

**Comment by Santhosh-Sellavel** [comment] 2023-10-25 21:41
This is a simple and straightforward issue 

@rojiphil's proposal looks good to me!

C+ Reviewed
🎀 👀 🎀

**Comment by Santhosh-Sellavel** [comment] 2023-10-25 21:45
@GItGudRatio 

> I got delayed by a few seconds

These are bound to happen on simple issues, better luck next time.

> Isn't adding code diffs to the proposal against the proposal guidelines

Yeah, large diffs without explaining the root cause. But I'm good with this as it's a relatively simpler one!

cc: @luacmartins

**Comment by rojiphil** [comment] 2023-10-26 16:11
Working on this now

**Comment by puneetlath** [comment] 2023-11-08 19:47
According to QA this is still happening on iOS, so let's make sure it also gets fixed there.

**Comment by rojiphil** [comment] 2023-11-09 03:09
> According to QA this is still happening on iOS, so let's make sure it also gets fixed there.

@puneetlath 

I am not able to reproduce the problem on the latest main (v1.3.97-1) with both iOS native and iOS mweb. Also, attaching the test videos for reference below. Maybe I am missing something simple here.

Can you please ask the QA to send a test video demonstrating the problem on iOS? 


https://github.com/Expensify/App/assets/3004659/97834988-1974-43ba-afcb-6172b86623b7


https://github.com/Expensify/App/assets/3004659/d5562149-7942-4963-b80e-97ca78064f7a

**Comment by rojiphil** [comment] 2023-11-09 15:11
> I am not able to reproduce $TBD but I see the mileage rate in offline mode in the latest build.

@kavimuru

Ok. Got it. I think the test description along with the precondition may help here. And sorry for the lack of clarity in the test steps.
I have updated that in the PR Test Section [here](https://github.com/Expensify/App/pull/30459#issue-1964045969).
Can you please try again along with the precondition?
Let me know if you still face problems.

**Comment by kavimuru** [comment] 2023-11-09 15:33
@rojiphil Thanks will validate and update you.

**Comment by rojiphil** [comment] 2023-11-22 06:49
@adelekennedy 
Now that the fix has been in production since Nov 10 according to this [comment here](https://github.com/Expensify/App/pull/30459#issuecomment-1804805934), 
can we not go ahead with the payments?

**Comment by adelekennedy** [comment] 2023-11-22 19:43
yes! Sorry about that it looks like this didn't update automatically 

Payouts due:

Contributor: $500 @rojiphil (Upwork)
Contributor+: $500 @thesahindia (NewDot)

Upwork job is [here](https://www.upwork.com/jobs/~01ffaa57ea238f4625) @rojiphil will you apply?

**Comment by rojiphil** [comment] 2023-11-22 19:53
> Upwork job is [here](https://www.upwork.com/jobs/~01ffaa57ea238f4625) @rojiphil will you apply?

Just applied using the link. Thanks for taking this forward.

**Comment by Santhosh-Sellavel** [comment] 2023-11-23 18:16
@adelekennedy I'm C+ here can you update payment summary please, thanks!

**Comment by JmillsExpensify** [comment] 2023-12-11 01:20
@adelekennedy re-opening for payment summary.

**Comment by JmillsExpensify** [comment] 2023-12-11 20:08
Apologies, I missed [this payment summary](https://github.com/Expensify/App/issues/30376#issuecomment-1823416379). $500 payment approved for @Santhosh-Sellavel.

**Closed by JmillsExpensify** 2023-12-11 20:08 UTC
Labels: Reviewing, External, Weekly, Bug
