### ISSUE TITLE
[HOLD for payment 2023-09-21] Bank account - Temporarily disabled message not displayed after 21 attempts

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26354] opened 2023-08-30 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20747
## Action Performed:
1. From NewDot, try adding a deposit account. Choose any Plaid bank, and enter 19 times some wrong credentials
2. Exit Plaid's modal. You should be able to choose a Plaid bank again. Enter 2 more wrong credentials
3. Exit Plaid's modal and try adding deposit account again

## Expected Result:
User should not be able to use Plaid again

## Actual Result:
Able to use plaid login again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aac3667f-4db0-4ade-bc1c-0752ff63a988

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-08-30 23:17
FWIW I can also keep entering invalid credentials in prod, so I don't think this is a blocker

**Comment by luacmartins** [comment] 2023-08-31 00:30
I'm gonna demote this to NAB since I could reproduce the behavior in prod. @nkuoch can you take a look at this one when you get a chance?

**Comment by nkuoch** [comment] 2023-08-31 10:18
@lanitochka17 can you tell me which email you tested it from in the video?

**Comment by lanitochka17** [comment] 2023-08-31 12:10
@nkuoch applasetester+30085@applause.expensifail.com

**Comment by ArekChr** [comment] 2023-09-04 11:54
@nkuoch After clicking 'Try Again' the modal closes automatically 

Also, after entering the wrong credentials more than 20 times, I don't see an error message. 

https://github.com/Expensify/App/assets/24796318/c4f5282e-6c03-46ce-aad7-08b71ba2b865

**Comment by alexpensify** [comment] 2023-09-08 23:36
PR is still in review

**Comment by alexpensify** [comment] 2023-09-20 22:58
@nkuoch - correct me if I'm wrong, but I don't think there's a payment here in Upwork. 

Here is the payment summary: 

-  External issue reporter - Applause - Payment N/A 
-  Contributor that fixed the issue - Internal - Payment N/A 
-  Contributor+ that helped on the issue and/or PR - @ArekChr Payment via vendor 

Upwork Job: N/A 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment:

**Comment by nkuoch** [comment] 2023-09-21 13:50
ah yes sorry.

**Comment by alexpensify** [comment] 2023-09-21 17:28
All good, I'm going to close this GH since there is no payment action here.

**Closed by alexpensify** 2023-09-21 17:28 UTC
Labels: Daily, Improvement, Awaiting Payment, Bug
