### ISSUE TITLE
[HOLD for payment 2022-09-30] [$250] Web - Login - The input field does not focus after following the magic link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10968] opened 2022-09-13 17:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. In the email field, enter a gmail email address for a new account
3. Navigate to the email inbox of the account and open the validation email
4. Copy the link and change it to staging
5. Navigate to the staging link

## Expected Result:
The input field must be focused

## Actual Result:
The input field does not focus

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.0.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189963694-b68a0db3-04cc-43bc-a5ce-9f8a69a430c6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2022-09-14 11:12
Not a big issue, but I suppose we should try to get this working.

**Comment by thesahindia** [comment] 2022-09-14 12:26
### Proposal 
We have to use `componentDidMount` in [NewPasswordForm.js ](https://github.com/Expensify/App/blob/main/src/pages/settings/NewPasswordForm.js)

```js
    componentDidMount() {
        if (!canFocusInputOnScreenFocus() || !this.input) {
            return;
        }
        this.input.focus();
    }
```

Need to pass `ref={el => this.input = el}` here -
https://github.com/Expensify/App/blob/a0340070ebf94fe3acde872c8c0c4222edd984c3/src/pages/settings/NewPasswordForm.js#L72

**Comment by mallenexpensify** [comment] 2022-09-14 22:26
@parasharrajat can you review @thesahindia 's proposal above? Thx
Job posted https://www.upwork.com/jobs/~016f4999710bb43714

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-14 22:52
**Proposal**

We need to pass autoFocus={true} props to TextInput and it fixes the issue.
https://github.com/Expensify/App/blob/a0340070ebf94fe3acde872c8c0c4222edd984c3/src/pages/settings/NewPasswordForm.js#L72

Like This 
### <TextInput
                    autoFocus={true}
                    label={`${this.props.translate('setPasswordPage.enterPassword')}`}
                    secureTextEntry
                    autoComplete={ComponentUtils.NEW_PASSWORD_AUTOCOMPLETE_TYPE}
                    textContentType="newPassword"
                    value={this.props.password}
                    onChangeText={password => this.props.updatePassword(password)}
                    onBlur={() => this.onBlurNewPassword()}
                    onSubmitEditing={() => this.props.onSubmitEditing()}
/>

After Fixing The Issue


Uploading Screen Recording 2022-09-15 at 3.49.44 AM.mov…

**Comment by Julesssss** [comment] 2022-09-15 11:16
I agree the autofocus prop seems preferable. Curious how this is handled on mobile platforms though. Is it simply ignored, or will the soft keyboard be displayed?

**Comment by thesahindia** [comment] 2022-09-15 11:30
Hey, just a question: Why aren't we using autofocus at other places like [LoginForm](https://github.com/Expensify/App/blob/main/src/pages/signin/LoginForm.js)

**Comment by mallenexpensify** [comment] 2022-09-16 00:21
@Julesssss can you confirm @syedsaroshfarrukhdot 's hire by assigning the issue to them and then I'll hire in Upwork

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-18 05:51
@mallenexpensify @Julesssss should i apply on upwork ?

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-19 11:01
@parasharrajat @mallenexpensify  @Julesssss  Just submitted a proposal on Upwork.

**Comment by mallenexpensify** [comment] 2022-09-19 20:13
Yup, @Julesssss will be back tomorrow.  Something to do with a Queen? English bank holiday?  👑

**Comment by syedsaroshfarrukhdot** [comment] 2022-09-20 15:31
Already submitted Proposal on Upwork. I will be making a PR by tomorrow.

**Comment by mallenexpensify** [comment] 2022-09-20 23:25
Hired @syedsaroshfarrukhdot in Upwork.  @parasharrajat will you apply for C+ plz
https://www.upwork.com/jobs/~016f4999710bb43714

**Comment by mvtglobally** [comment] 2022-09-27 05:13
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2022-10-03 11:54
👋 I settled up with @syedsaroshfarrukhdot. 

The other hire on this job is @mananjadhav, but @parasharrajat was C+. Any idea what happened there? In the meantime, I've sent Rajat an offer.

**Comment by mananjadhav** [comment] 2022-10-03 12:04
I did work on an issue related to magic link and forgot password. But I don't think it is this one.

**Comment by trjExpensify** [comment] 2022-10-03 12:15
Gotcha. Any idea which issue and contract that is? Looks like you've been paid for this one, you see.

**Comment by mananjadhav** [comment] 2022-10-03 12:18
Yeah I found the issue. Looks like I was paid for https://github.com/Expensify/App/issues/10785 with this issue's Upwork job. I don't see any Upwork job or payment for 10785.

**Comment by trjExpensify** [comment] 2022-10-03 12:38
Got it, got it. Cool, so just waiting on @parasharrajat to accept the contract for this job and then we can close it out!

**Comment by trjExpensify** [comment] 2022-10-03 15:22
Cool, settled up with @parasharrajat. Thanks everyone! 🎉

**Closed by trjExpensify** 2022-10-03 15:22 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment
