### ISSUE TITLE
WS - Members - Avatars group on final screen moves to the left if admin invites more 8 users

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22685] opened 2023-07-11 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open and login with expensifail account to staging.new.expensify.com or Expensify App
2. Go to existing or create new workspace
3. Go to Workspace > Members
5. Click / Tap 'Invite'
6. Select more then 8 users
7. Click 'Next'

## Expected Result:
The avatar group on the final screen is always in the center

## Actual Result:
The avatars group on final screen moves to the left if admin invites more 8 users
The shift to the left gets bigger with each user added

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/6270a85f-7709-4d21-83af-20573a379ff2

![Bug6124175_WS-Invite-users-avatars-cut](https://github.com/Expensify/App/assets/78819774/418bb494-e9fe-4127-b062-e14c5973dc72)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by StevenKKC** [comment] 2023-07-11 20:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Avatars group on final screen moves to the left if admin invites more 8 users.

### What is the root cause of that problem?
Avatar group's width is calculated as below.
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/components/MultipleAvatars.js#L138-L142
If have more than 8 avatar, `length` would be greater than `props.maxAvatarsInRow` (i.e. 4).
So avatar group moves to the left.

### What changes do you think we should make in order to solve the problem?
Avatar group's width should be smaller than or equal to `props.maxAvatarsInRow`.
We can change code as below.
```js
-   const length = avatarRows.length > 1 ? Math.max(avatarRows[0].length, avatarRows[1].length) : avatarRows[0].length;
+   const length = Math.min(avatarRows.length > 1 ? Math.max(avatarRows[0].length, avatarRows[1].length) : avatarRows[0].length, props.maxAvatarsInRow);
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by DrLoopFall** [comment] 2023-07-12 10:36
There's also another issue #22632, connected to this, even though the issues are different, the root cause remains the same.
I've made a [proposal](https://github.com/Expensify/App/issues/22632#issuecomment-1631418875) there which would solve both issues, I'll also leave a proposal below just in case.

**Comment by DrLoopFall** [comment] 2023-07-12 10:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace members avatars group on the final screen moves to the left if the admin invites more than 8 users

### What is the root cause of that problem?
We are using `left` for positioning/shifting avatars, which causes it to use more space than required.
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/styles/StyleUtils.js#L906
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/styles/StyleUtils.js#L923
Also, currently, we are calculating the width, as a [workaround](https://github.com/Expensify/App/issues/22445#issuecomment-1629454284), which is also a part of the problem in this issue.
> @stitesExpensify I think the `width` was set as a workaround for the issue described in my [proposal](https://github.com/Expensify/App/issues/22445#issuecomment-1627413019) (the 2nd issue)
> 
> > We are using `left` for positioning/shifting avatars but the `PressableWithoutFeedback` itself is not shifted, which causes it to be clickable in both the original and shifted positions.
> 
> If we use `margin-left` instead, we can remove the `width`, which may prevent any future issues.

https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/components/MultipleAvatars.js#L138-L144

### What changes do you think we should make in order to solve the problem?
Use `margin-left` instead of `left` for positioning the avatar.
```js
// in getHorizontalStackedAvatarStyle
- left: -(overlapSize * index)
+ marginLeft: index > 0 ? -overlapSize : 0

// in getHorizontalStackedOverlayAvatarStyle
- left: -(oneAvatarSize.width * 2 + oneAvatarBorderWidth * 2)
+ marginLeft: -(oneAvatarSize.width + oneAvatarBorderWidth * 2)
```
We should also need to remove the width, as we don't need it anymore, because this proposal also removes the need for the [workaround](https://github.com/Expensify/App/issues/22445#issuecomment-1629454284) as it fixes the issue in the root, and removing it may prevent future issues like this.
https://github.com/Expensify/App/blob/702d8e254760b3ac3d90586d80528acebbb0b529/src/components/MultipleAvatars.js#L138-L144

**Comment by johncschuster** [comment] 2023-07-18 21:16
If the root cause will be fixed in another issue, does this issue need to remain open?

(I'm not sure, so I'm asking in [Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1689706135527179))

**Comment by johncschuster** [comment] 2023-07-20 14:02
bumping my question above

**Comment by Santhosh-Sellavel** [comment] 2023-07-20 23:07
@johncschuster Yeah can close this one in favor of #22632

**Comment by johncschuster** [comment] 2023-07-21 21:00
Thanks, @Santhosh-Sellavel!

**Closed by johncschuster** 2023-07-21 21:00 UTC
Labels: Daily, Bug
