### ISSUE TITLE
Split - User can split bill with only one user and billable option is present in split menu

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37488] opened 2024-02-29 12:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Request money > Manual.
3. Enter amount > Next.
4. Click Split next to one user.
5. Click Add to split.
6. Click Split.
7. In 1:1 DM, click on the split preview.

## Expected Result:
In Step 6, user should not be able to split bill with only one user. There is no split bill option from + menu in 1:1 DM.
In Stepp 7, there should be no billable option since it is not present when splitting bill.

## Actual Result:
In Step 6, user is able to split bill with only one user.
In Step 7, the split preview shows billable option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/68c60f3f-70cb-48e5-ba68-6ba9e0ad3821

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-02-29 12:13
@puneetlath I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by situchan** [comment] 2024-02-29 17:05
There are 2 bugs reported here.

Split - User can split bill with only one user - regression from https://github.com/Expensify/App/pull/33482
billable option is present in split menu - this is dupe of #37522 and it seems offending PR is being reverted


I think better to revert https://github.com/Expensify/App/pull/33482 as well since it also caused multiple regressions

**Comment by puneetlath** [comment] 2024-02-29 17:05
FYI, this is likely fixed by [this revert](https://github.com/Expensify/App/pull/37529). Will have QA re-test once it is CP'd.

**Comment by bernhardoj** [comment] 2024-02-29 17:07
Splitting with one user is not a regression. 
https://github.com/Expensify/App/issues/32912#issuecomment-1857028520

**Comment by puneetlath** [comment] 2024-02-29 19:00
Was fixed by revert.

**Closed by puneetlath** 2024-02-29 19:00 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
