### ISSUE TITLE
[Guides] Guides cannot load NewDot

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#22601] opened 2023-07-11 00:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in
2. Land on a chat

## Expected Result:
Page should load

## Actual Result:
Page never loads

## Platforms:
Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** natasha.varner@team.expensify.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

![image](https://github.com/Expensify/App/assets/22508290/2a2dcb3d-905a-4c13-8146-ddbdfd9311e9)

![image](https://github.com/Expensify/App/assets/22508290/1f61735c-ed3c-41aa-9266-f806e1ac6d0a)

**Issue reported by:** natasha.varner@team.expensify.com
**Slack conversation:** https://expensify.slack.com/archives/C036S0BVAHH/p1688125556672379
**Report ID:** 7189374516190979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01146f966b0e7c6f11</li>
        <li>Upwork Job ID: 1678561816277438464</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by techievivek** [comment] 2023-07-11 09:24
Can we please get a screen recording of the network events being fired after the user logs in? From the screenshots, it is not  clear whether this is a backend issue(we are waiting for the response from the server) or if it is a frontend issue(it is taking a considerable amount of time applying all the Onyx updates).

**Comment by techievivek** [comment] 2023-07-11 09:28
Looking at all the [conversations](https://expensify.slack.com/archives/C04JD99283A/p1689022385973089) it looks like a frontend issue where setting a lot of Onyx data in slow, we have a similar issue here https://github.com/Expensify/App/issues/21766

**Comment by techievivek** [comment] 2023-07-17 11:35
@kevinksullivan Should we close this now since we are looking into the same thing on a different issue?

**Comment by kadiealexander** [comment] 2023-07-19 05:14
Closing as per [this comment](https://github.com/Expensify/App/issues/21766#issuecomment-1636568486) showing Guides are currently fine and the issue is being worked on there. Please feel free to reopen if you disagree!

**Closed by kadiealexander** 2023-07-19 05:14 UTC
Labels: Engineering, Daily, Internal, Bug

**Comment by kevinksullivan** [comment] 2023-07-19 13:10
Sorry for the delay, was OOO. I agree with closing this out 👍
