### ISSUE TITLE
[HOLD for payment 2024-07-10] Thread - Thread title not updated in header and in LHN after editing parent message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44430] opened 2024-06-26 08:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4675207
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Open any chat
3. Send a message and create a thread
4. Change the parent message to anything

## Expected Result:
The thread title is updated in the header and in LHN

## Actual Result:
The thread title still displays the parent message before editing. It updates in the header after opening the thread again, but does not change in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/f33a4fae-a38d-4b01-89c3-c1a5ec42a674

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by izarutskaya** [comment] 2024-06-26 08:42
@trjExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 08:43
We think this issue might be related to the  #vip-vsb

**Comment by bernhardoj** [comment] 2024-06-26 11:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread title and LHN title doesn't update immediately when updating the thread parent message.

### What is the root cause of that problem?
For the thread title, we get the title from `getReportActionMessage` which uses `parseReportActionHtmlToText`. `parseReportActionHtmlToText` has a cache mechanism with the cache key being the combination of the `reportID`, `reportActionID`, and the report action `lastModified`.
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/libs/ReportUtils.ts#L3238-L3242

There are 2 problems here. First, we don't optimistically update the `lastModified` when editing a message, so we rely on the BE response to update it. Second, we get the report action by using the deprecated `getParentReportAction` which means the component won't react to the parent report action updates and relies on other updates.
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/libs/ReportUtils.ts#L3322-L3324

### What changes do you think we should make in order to solve the problem?

First, update the lastModified optimistically (and revert if fails).
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/libs/actions/Report.ts#L1530-L1543

This change alone is enough because the report data is also updated which triggers the `getReportName`, but I think we should start passing the parent report action as the 3rd param.
https://github.com/Expensify/App/blob/0c20881a308244867119efa6196481b65bb81274/src/pages/home/HeaderView.tsx#L106
`const title = ReportUtils.getReportName(reportHeaderData, undefined, parentReportAction);`

**Comment by trjExpensify** [comment] 2024-06-26 12:33
Have we identified the PR on the staging checklist that broke this?

**Comment by bernhardoj** [comment] 2024-06-26 13:26
I think it's the [react-compiler](https://github.com/Expensify/App/pull/42287).

In prod, I can see that the thread and LHN title are late to update.

https://github.com/Expensify/App/assets/50919443/7c7644f5-edb7-4015-9c06-9e909b7877a0

But in `main` (or staging), the thread title is never updated which is worse than prod.

https://github.com/Expensify/App/assets/50919443/f826b1cd-b43b-4117-b9ed-54fe8ef68424

So, there are 2 problems, 1 is an old problem and the other one is caused by the react-compiler. (NOTE: it shows that the react-compiler did its job)

I have updated my proposal to mention the react-compiler PR.

**Comment by mountiny** [comment] 2024-06-26 14:48
@kirillzyusko Could you check this out too please?

**Comment by mountiny** [comment] 2024-06-26 14:49
FWIW the proposal from @bernhardoj makes sense

**Comment by kirillzyusko** [comment] 2024-06-27 06:52
@mountiny yeah, the proposal looks good for me as well 👍

**Comment by bernhardoj** [comment] 2024-06-27 08:54
PR is ready

**Comment by rushatgabhane** [comment] 2024-07-08 21:44
1. The PR that introduced the bug has been identified. Link to the PR: the bug stems from react compiler pr - https://github.com/Expensify/App/pull/42287

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42287#pullrequestreview-2164493144

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N.A.

4. Determine if we should create a regression test for this bug. No because caught by QA and rca was react compiler which is one time thing.
 
5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again - N.A.

**Comment by trjExpensify** [comment] 2024-07-10 17:49
Payment summary as follows: 

- $250 to @bernhardoj for the fix
- $250 to @rushatgabhane for the review

Feel free to go ahead and request, both of you. Closing!

**Closed by trjExpensify** 2024-07-10 17:49 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by bernhardoj** [comment] 2024-07-11 01:27
Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-07-11 03:22
$250 approved for @bernhardoj

**Comment by JmillsExpensify** [comment] 2024-07-17 19:46
$250 approved for @rushatgabhane
