### ISSUE TITLE
[HOLD for payment 2024-07-31][$250] Compose Box - Bold markdown is not working if followed by an underscore

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44032] opened 2024-06-19 19:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-6
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** nahummelaku9+cd1@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log into staging.new.expensify.com
2. Navigate to a conversation
3. Write a text with a bold markdown
4. Write an underscore next to the bold markdown
5. Send the text in the compose box

## Expected Result:
A text in bold followed by an underscore is shown in the conversation

## Actual Result:
Asterix on both sides of the text and an underscore are sent to the conversation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2c6199e1-a404-425d-af0f-de8a6117dcb7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164dc21fd43760287</li>
        <li>Upwork Job ID: 1805749444451342734</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @parasharrajat</details>

**Comment by lanitochka17** [comment] 2024-06-19 19:32
We think that this bug might be related to #Live Markdown

**Comment by dylanexpensify** [comment] 2024-06-21 10:02
cc @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-06-21 19:55
Just need to add to Live Markdown project, I bumped to Weekly since the folks are prioritizing fixes over there.  I'd await an update from them.

**Comment by mallenexpensify** [comment] 2024-06-25 23:47
Thanks @BartoszGrajdek , made external, `help wanted` added too.

**Comment by jp928** [comment] 2024-06-26 13:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Asterix on both sides of the text and an underscore are sent to the conversation without markdown style.

### What is the root cause of that problem?

[The ](https://github.com/Expensify/expensify-common/blob/2879643200dcd16041c3fd60799097fe9f188a83/lib/ExpensiMark.ts#L464)

The regular expression cannot match `_*test*` because of the `\B` makes the * has to be the start of the word. test cases as below: 
<img width="1286" alt="Screenshot 2024-06-26 at 11 42 07 PM" src="https://github.com/Expensify/App/assets/659612/fdb56dd0-efce-4b21-84e1-98b0a2484899">

### What changes do you think we should make in order to solve the problem?
Remove the `\B` in the regular expression
use `regex: /(?<!<[^>]*)\*(?![^<]*(?:<\/pre>|<\/code>|<\/a>))((?![\s*])[\s\S]*?[^\s*](?<!\s))\*(?![^<]*>)(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,` instead. test cases as below: 
<img width="1269" alt="Screenshot 2024-06-26 at 11 44 39 PM" src="https://github.com/Expensify/App/assets/659612/3b16ee8b-b9bb-4bd7-8d2e-9a5b4d142cff">


### What alternative solutions did you explore? (Optional)
NA

**Comment by jp928** [comment] 2024-06-28 15:36
@parasharrajat 
The current ExpensiMark works with all other special characters except _, and not work with any letters.

https://github.com/Expensify/App/assets/659612/b9e5f6ac-467d-40f3-97d2-b89e7729ed86

**Comment by jp928** [comment] 2024-06-28 15:39
@parasharrajat Also, just notice there is another \B to prevent the markdown end with a letter, so currently *b* end with a letter doesn't work either.

**Comment by jp928** [comment] 2024-07-02 08:16
@parasharrajat Thanks for reviewing. The proposal updated.

**Comment by jp928** [comment] 2024-07-05 14:05
@parasharrajat I tried the italic parsing rule, it will fail some test cases.
`/(<(pre|code|a|mention-user)[^>]*>(.*?)<\/\2>)|((\b_+|\b)\*((?![\s_])[\s\S]*?[^\s_](?<!\s))\*(?![^\W_])(?![^<]*>)(?![^<]*(<\/pre>|<\/code>|<\/a>|<\/mention-user>)))/g`
this is what I used to test.

**Comment by jp928** [comment] 2024-07-05 22:09
@parasharrajat There are more some cases the italic one can't handle: `*sentence,* ` `*Here is a multi-line\ncomment that should\nbe bold*`, I just updated my proposal with minimum change to just fix the bug in this thread.

**Comment by jp928** [comment] 2024-07-12 10:03
@parasharrajat PR is linked but not sure if the package version update is needed.

**Comment by jp928** [comment] 2024-07-12 11:08
I have read the CLA Document and I hereby sign the CLA

**Comment by hayata-suenaga** [comment] 2024-07-16 14:10
not problem 😄

**Comment by jp928** [comment] 2024-07-17 12:36
@parasharrajat My first PR has been merged. Please advise what would be included in the next PR?

**Comment by hayata-suenaga** [comment] 2024-07-26 15:28
what are we waiting here?

**Comment by roryabraham** [comment] 2024-08-02 18:54
@dylanexpensify looks like this is ready to pay out. @parasharrajat can you help out with a payment summary for this issue please?

**Comment by dylanexpensify** [comment] 2024-08-05 12:31
Payment summary:
- Contributor: @jp928 $250
- Contributor+: @parasharrajat $250

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-08-05 12:33
@jp928 [please apply here](https://www.upwork.com/ab/applicants/1820437868732301808/job-details)!

**Comment by jp928** [comment] 2024-08-07 01:46
Contributor details
Your Expensify account email: piaojingtai@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a3ce7f9619e1a922?mp_source=share

**Comment by dylanexpensify** [comment] 2024-08-12 09:39
@jp928 sent invite!

**Comment by dylanexpensify** [comment] 2024-08-12 09:59
@jp928 offer sent!

**Comment by dylanexpensify** [comment] 2024-08-12 12:16
all done!

**Closed by dylanexpensify** 2024-08-12 12:16 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-09-02 11:55
$250 approved for @parasharrajat
