### ISSUE TITLE
Category IOU - All the categories are bold

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27347] opened 2023-09-13 13:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/26501
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to the workspace chat as the invited member
3. Go to + > Request money
4. Enter an amount > Next
5. Click Show more > Category

## Expected Result:
Only the selected category appears bold

## Actual Result:
All the categories are bold

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.69-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/afed8759-315f-46a4-b458-585330ecb848

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2023-09-13 13:40
I believe this is the proper design and not a bug, right @yuwenmemon @shawnborton? Looking at [the doc](https://docs.google.com/document/d/1itXKWlhms5YHcF4-lujO6g8T5LPdLVD_7onjtZBsATQ/edit#heading=h.fvluo2r33dar), it seems so. 

In any case, removing the deploy blocker label since this is a beta feature.

**Comment by Pluto0104** [comment] 2023-09-13 13:41
I have changed Permission file but I can't see category picker. how can I reproduce it?

**Comment by yuwenmemon** [comment] 2023-09-13 16:47
Yep, they should be bold - closing

**Closed by yuwenmemon** 2023-09-13 16:47 UTC
Labels: Engineering, Daily
