### ISSUE TITLE
[$1000]  Mentioned list is not showing with display name with & in between

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22375] opened 2023-07-06 20:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Please change the display name of user B to anything but should have & in the display name
1. Go to staging dot on web and login with User A
2. Go to any chat and try to mention user B by  FULL display name with &
3. Notice that if the display name contains & , the mention suggestion will not be shown
## Expected Result: 
Mentioned list should be shown with display name having & in between
## Actual Result: 
Mentioned list is not showing with display name with & in between

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a582c109-83b5-47c4-822c-59b9ee20ae0d

https://github.com/Expensify/App/assets/43996225/3663addd-2743-42d3-9665-48a0890090ab

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688574053007549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5bdd04db4b9c2a1</li>
        <li>Upwork Job ID: 1677163730809729024</li>
        <li>Last Price Increase: 2023-07-21</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-07-06 20:34
This seems like a duplicate of https://github.com/Expensify/App/issues/22374

**Comment by kadiealexander** [comment] 2023-07-06 22:03
I think they're slightly different, right? Yours is where the display name won't show at all for new users, whereas mine Is related to the `&` symbol being in the name for any user? 

@s77rt could you please take a look and see if these might have the same root cause? Thanks so much!

**Comment by kadiealexander** [comment] 2023-07-07 03:52
Repro:

https://github.com/Expensify/App/assets/59587260/dc9a56ac-c22b-41e5-8b5a-e4f5cd034eec

**Comment by s77rt** [comment] 2023-07-07 13:54
@kadiealexander The two issues look different.

**Comment by LiaqatSaeed** [comment] 2023-07-07 16:03
Contributor details
Your Expensify account email: liaqatsaeed007@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/liaqatsaeed

**Comment by eVoloshchak** [comment] 2023-07-10 22:52
Not overdue, reviewing a proposal tomorrow

**Comment by Victor-Nyagudi** [comment] 2023-07-12 14:08
After investigating this issue, I arrived at a similar conclusion to @c3024 [above](https://github.com/Expensify/App/issues/22375#issuecomment-1624499673). 

I just thought I'd add that the bug occurs not just when there's an `&` in the middle of the name - it's also there when the character is a `#` or some other special characters, so hopefully, whoever gets assigned checks for those too. 

If the proposal isn't accepted, then I'm open to taking another crack at this, otherwise, all the best.

**Comment by eVoloshchak** [comment] 2023-07-13 18:32
I agree with @c3024 [assessment](https://github.com/Expensify/App/issues/22375#issuecomment-1624499673) of the root cause

I like the general direction of the proposal, but it didn't resolve the issue for me. 
However, I agree with the approach, looks like we were using a similar approach before changing it in https://github.com/Expensify/App/pull/19004
@c3024, could you please verify once more your solution is working?

**Comment by eVoloshchak** [comment] 2023-07-18 21:07
Testing

**Comment by eVoloshchak** [comment] 2023-07-19 20:45
@c3024, can confirm it working, thanks
I wonder if we could simplify the logic here. What is the purpose of `SPECIAL_CHAR_OR_EMOJI_FOR_MENTIONS` in
```
const words = leftString.split(CONST.REGEX.SPECIAL_CHAR_OR_EMOJI_FOR_MENTIONS);
```
Can we replace it with const `words = leftString.split(' ')`?

**Comment by eVoloshchak** [comment] 2023-07-20 23:00
@c3024, ah, I see, thanks
I think this is a bit weird, we allow user to use special characters to break the word (i.e. use comma in `@abc/de,@` to start a new mention), while simultaneously allowing the same special characters to be used in names
I'll start a discussion on Slack to get more opinions

**Comment by eVoloshchak** [comment] 2023-07-26 18:43
Asking here: https://expensify.slack.com/archives/C01GTK53T8Q/p1690397006388229

**Comment by kadiealexander** [comment] 2023-07-26 21:55
We agreed not to fix this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1690397006388229), as it's a very unlikely use case we'll wait for a real user to report it.

**Closed by kadiealexander** 2023-07-26 21:55 UTC
Labels: External, Daily, Help Wanted, Bug
