### ISSUE TITLE
[HOLD for payment 2024-01-17] Unsubscribe icon shows up after leaving your own thread

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#30546] opened 2023-10-27 23:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** @srikarparsi and Applause
**Slack conversation:** N/A

Issue found when executing PR https://github.com/Expensify/App/pull/27994

## Action Performed:
Break down in numbered steps

1. Comment on a report
2. Reply to the comment
3. Go into the thread, and then click leave thread
4. Return to the parent report.
5. The unsubscribe icon will show up even if the report is no longer shared.

## Expected Result:
Describe what you think should've happened

The subscribe icon should show up

## Actual Result:
Describe what actually happened

The unsubscribe icon shows up instead

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Yes

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/48188732/0ff4cd69-a4fe-4d45-9245-9f10efae0127

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a3500c3ff4829ca</li>
        <li>Upwork Job ID: 1719512812572073984</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-28 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "Unsubscribe" button is visible even after the thread was left

### What is the root cause of that problem?
The issue is that on leaving the thread, we call this action:

https://github.com/Expensify/App/blob/a59d56f00a67607a1dbae1b422807f76f548f1f0/src/libs/actions/Report.js#L2017

Here: 

https://github.com/Expensify/App/blob/fb0899f2a98c4c2a146065c5795b6b2a3ad69958/src/pages/home/HeaderView.js#L130-L136

But it doesn't update the `childReportNotificationPreference` of the parent `reportAction`.

### What changes do you think we should make in order to solve the problem?
We should add an optimistic Onyx `merge` operation to update the `childReportNotificationPreference` of the parent `reportAction` to `hidden`, in case if the report is a thread.



### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-30 04:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unsubscribe icon shows up after leaving your own thread

### What is the root cause of that problem?
When clicking the subcribe or unsubcribe button on the ContextMenu modal. We will call toggleSubscribeToChildReport function to update Notification Preference
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/pages/home/report/ContextMenu/ContextMenuActions.js#L215
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/pages/home/report/ContextMenu/ContextMenuActions.js#L181

When leaving the thread, we don't call toggleSubscribeToChildReport to unsubscribe this thread
### What changes do you think we should make in order to solve the problem?
When leaving the thread, we should call toggleSubscribeToChildReport to unsubscribe this thread like we did here
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/pages/home/report/ContextMenu/ContextMenuActions.js#L206-L215

We also consider calling toggleSubscribeToChildReport to true when the user clicks the thread again after leaving the thread

Optional: While investigating this issue I see a problem. Let's see the below image

<img width="946" alt="Screenshot 2023-10-30 at 11 22 56" src="https://github.com/Expensify/App/assets/141406735/6ee44e48-ab8f-463c-aa1f-352c260b1c7c">

The unsubscribe button displayed on context menu modal even It is single message not thread (there are no child message). The RC is 
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/pages/home/report/ContextMenu/ContextMenuActions.js#L197
https://github.com/Expensify/App/blob/e99c297332c738475cfe5701e0a00ba0b5d58029/src/pages/home/report/ContextMenu/ContextMenuActions.js#L204
we are using this condition to display unsubcribe button

Solution: I suggest we add a condition to make sure it is a thread (Ex: childVisibleActionCount > 0). If It is true, we display unsubcribe or subcribe button

### What alternative solutions did you explore? (Optional)

**Comment by sakluger** [comment] 2023-10-30 16:55
I spoke with @MitchExpensify, neither of us think that this needs to be a deploy blocker. I'm going to leave assigned to @srikarparsi and demote back to daily, and switch the assigned BZ member from me to Mitch.

**Comment by srikarparsi** [comment] 2023-11-01 00:32
Hey, I'm taking this internally, just reported the issue in advance so that work wouldn't be duplicated.

**Comment by MitchExpensify** [comment] 2023-11-03 22:19
Updates in #launchsuperapp

**Comment by DylanDylann** [comment] 2023-11-07 14:01
@srikarparsi  Could you take a look at [my proposal](https://github.com/Expensify/App/issues/30546#issuecomment-1784469094)? Maybe It will give some information

**Comment by srikarparsi** [comment] 2023-11-08 08:38
Hey @DylanDylann, thank you for your proposal but I'm taking this one internally since there are backend changes to be made. I'm implementing a slightly different solution so that we're not making two different requests in the same method but it effectively does what you're suggesting.

**Comment by MitchExpensify** [comment] 2023-11-13 02:06
How is coming along @srikarparsi ?

**Comment by srikarparsi** [comment] 2023-11-16 09:21
Got it working! In review now :)

**Comment by MitchExpensify** [comment] 2023-11-17 02:31
Nice one!

**Comment by MitchExpensify** [comment] 2023-12-12 19:57
Good to close @srikarparsi ?

**Comment by situchan** [comment] 2023-12-12 19:58
[PR](https://github.com/Expensify/App/pull/30812) is in review

**Comment by MitchExpensify** [comment] 2024-01-08 23:05
Done

**Comment by MitchExpensify** [comment] 2024-01-17 17:30
Offer here for you @situchan https://www.upwork.com/nx/wm/offer/100498634

**Comment by MitchExpensify** [comment] 2024-01-17 18:06
paid and contract ended! Closing

**Closed by MitchExpensify** 2024-01-17 18:06 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
