### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Noticeable Delay When Selecting Assignee During Task Assignment

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44443] opened 2024-06-26 10:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. FAB > Assign Task
2. Add title > Go to Assignee
3. Click on Assignee > Select User

## Expected Result:
There should be no noticeable delay, and the process should be smooth when selecting an assignee from the dropdown during task assignment

## Actual Result:
Noticeable delay when selecting an assignee

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/056ef1e0-76c4-4b31-a3fc-c9a8e1ab4640

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179306ad6d57e7abf</li>
        <li>Upwork Job ID: 1805923850414823822</li>
        <li>Last Price Increase: 2024-07-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by izarutskaya** [comment] 2024-06-26 10:43
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-26 10:43
We think this issue might be related to the  #vip-vsb

**Comment by mountiny** [comment] 2024-06-26 11:19
I barely saw som delay in the video, demoting and marking external

**Comment by mountiny** [comment] 2024-06-26 14:04
@huzaifa-99 @parasharrajat this seems to be coming from your PR then. can you have a look please

**Comment by mountiny** [comment] 2024-06-27 21:45
Yeah I am not 100% sure either, the animation is a bit clunky so it might be actually from that

**Comment by MitchExpensify** [comment] 2024-07-01 20:54
What is the latest here @mananjadhav ?

**Comment by mountiny** [comment] 2024-07-05 00:40
@MitchExpensify I cannot really reproduce, can you? Do you want to close it if you cannot?

**Comment by mountiny** [comment] 2024-07-05 09:13
> it's 0.2 second delay tho

Yeah I think this is the main problem, its small enough that its hard to notice. I am not sure if we have to do anything about this if its to help with double selection/ openinig

**Comment by mananjadhav** [comment] 2024-07-07 22:47
@mountiny Are we then prioritizing this? Can you please confirm?

**Comment by mountiny** [comment] 2024-07-08 09:41
@mananjadhav Can you review the proposal? I think that if we can:
- remove the delay
- and ensure we cannot trigger the navigation/ action upon click twice

we should implement this cc @huzaifa-99 @parasharrajat what do you think of the proposal?

**Comment by mananjadhav** [comment] 2024-07-10 00:35
Read through the reasoning, yeah doesn't make sense removing the delay. Let's find an alternative solution.

**Comment by mountiny** [comment] 2024-07-10 15:23
I have shared this with SWM as it seems like there are no good proposals for this now

**Comment by mountiny** [comment] 2024-07-12 23:19
@SzymczakJ excited for your investigation

**Comment by SzymczakJ** [comment] 2024-07-15 13:27
Work in progress, experimenting with some other solutions but they don't fix the issue yet 😬

**Comment by MitchExpensify** [comment] 2024-07-16 17:55
Reassigning as I'm headed on leave 🙇

**Comment by BrtqKr** [comment] 2024-07-16 21:50
Please assign me, I'll take over this after @SzymczakJ

**Comment by BrtqKr** [comment] 2024-07-17 11:29
In general, the change causing it has been introduced in [this PR](https://github.com/Expensify/App/pull/25604) to fix the navigation problem. There's one alternative solution we could apply, which is wrapping onSelect from the `BaseSelectionList` into `useSingleExecution`, which would prevent the function from triggering additional time. This way we could avoid using debounce, removing delay in result. 

Unfortunately, there has been [one problem](https://github.com/Expensify/App/pull/24482#issuecomment-1748624299) with using `useSingleExecution` on the web - it was causing list items to turn disabled when switching between online and offline. It was present in the old settings modal and I'm unable to reproduce it in the current state of the app, so there's a chance it's no longer present. Are you aware of any issues that could arise after applying it? If not, I think we could proceed with this approach. 

@mountiny @dylanexpensify

**Comment by dylanexpensify** [comment] 2024-07-18 09:12
assigned @BrtqKr! @mountiny will defer to you on this query

**Comment by mountiny** [comment] 2024-07-20 00:07
@BrtqKr I am not aware of any issues, feel free to go ahead with it and try it

**Comment by BrtqKr** [comment] 2024-07-22 08:44
ok, it doesn't seem to be happening in the current state of the app, so I guess the PR is ready for the review.

**Comment by dylanexpensify** [comment] 2024-07-22 12:49
@mananjadhav for review!

**Comment by dylanexpensify** [comment] 2024-08-05 12:24
bump @mananjadhav

**Comment by mananjadhav** [comment] 2024-08-05 13:52
I am done with my review and here's the [checklist](https://github.com/Expensify/App/pull/45874#issuecomment-2257848819). Waiting on @mountiny but I think he was OOO last week.

**Comment by dylanexpensify** [comment] 2024-08-12 10:03
Payment coming up!

**Comment by mananjadhav** [comment] 2024-08-20 14:46
@dylanexpensify Can you please complete the payout summary?

I don't think we have any offending PR here. We did link a PR earlier but we've been using debounce even before. The existing regression tests for changes from debounce to useSingleExecution should cover the tests. Hence no new tests needed.

**Comment by dylanexpensify** [comment] 2024-08-21 09:40
Reviewing today! Apologies for delay!

**Comment by dylanexpensify** [comment] 2024-08-21 10:06
Payment summary:

Contributor+: @mananjadhav $250 via NewDot

Please apply/request!

**Closed by dylanexpensify** 2024-08-21 10:06 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-21 11:12
$250 approved for @mananjadhav
