### ISSUE TITLE
[$500] `Next` button is cut off when creating distance requests

### ISSUE THREAD

**Issue by JmillsExpensify** [Expensify/App#26712] opened 2023-09-04 19:33 UTC
When creating a distance request on mWeb (iOS/Safari), we're seeing that the `Next` button is about 25% or so cut off. This could happen for any number of reasons:

 - User is using a small screen mobile phone
 - User also has the mobile app downloaded, and accordingly, sees the "smart" banner to use the app (my example below).

![Image](https://user-images.githubusercontent.com/1127863/265531681-e543da96-ccaf-49af-8c25-1c5ef6600a6c.PNG)

Whatever the case, we need to ensure that the `Next` button isn't cut off. Some potential solutions might be:

 - Dynamically decrease the size of the mileage map
 - Bottom dock the `Next` button so that it's always right above the bottom of the scroll view

I tend to favor the last one though we can use this issue to discuss. 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c7d29a4ac924ce8</li>
        <li>Upwork Job ID: 1698781518139650048</li>
        <li>Last Price Increase: 2023-09-04</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26495852</li>
<li>jeet-dhandha | Contributor | 26495854</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-09-04 19:34
cc @neil-marcellini @hayata-suenaga

**Comment by jeet-dhandha** [comment] 2023-09-04 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Button is cutting off in distance request. But major issue is that its not scrollable.

### What is the root cause of that problem?
- I think we should add a scroll view to the Distance request screen.

### What changes do you think we should make in order to solve the problem?
- We can cover Distance request screen with scroll view.

```js
<ScrollView style={[styles.w100, styles.flex1]}>
... rest code
</ScrollView>
```

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by JmillsExpensify** [comment] 2023-09-04 21:11
Oh good catch. We chatted internally and I don't think we realized this. I think we should probably close, and in the meantime, I've asked Neil and Hayata to jump into that issue.

**Comment by hayata-suenaga** [comment] 2023-09-04 21:14
Closing this in favor of[ this issue](https://github.com/Expensify/App/issues/26541)

**Comment by hayata-suenaga** [comment] 2023-09-04 21:15
Assigned a C+ over the other issue for a quick PR

**Closed by hayata-suenaga** 2023-09-04 21:14 UTC
Labels: External, Daily, Bug
