### ISSUE TITLE
[$500] Web – Assign task - The arrow is not available for navigation in Assign Task BNP

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#28986] opened 2023-10-06 08:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any Gmail account.
3. On LHN, click on the FAB button.
4. Select Assign Task.
5. Enter a title, description and tap Next.
6. Tap on the arrow for Assignee selection.

## Expected Result:
Opens the List of contacts.

## Actual Result:
Nothing happenes. The arrow is not available for navigation, it is possible to navigate only by typing on the text.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.78-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/13cf7907-786a-4d11-946c-9da5301858cb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015814755865c3b7a7</li>
        <li>Upwork Job ID: 1710214036611854336</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by martin12345678900** [comment] 2023-10-06 09:02
# **Proposal**

## **Please re-state the problem that we are trying to solve in this issue**
When pressing on arrow on creation of new task it doesn't redirect.

## **What is the root cause of the problem**
The root cause of the problem is that we don't pass ```onIconRightPress``` prop the ```<MenuItem />```

```javascript
<MenuItem
                                label={assignee.displayName ? props.translate('task.assignee') : ''}
                                title={assignee.displayName || ''}
                                description={assignee.displayName ? LocalePhoneNumber.formatPhoneNumber(assignee.subtitle) : props.translate('task.assignee')}
                                icon={assignee.icons}
                                onPress={() => Navigation.navigate(ROUTES.NEW_TASK_ASSIGNEE)}
                                shouldShowRightIcon
                            />
```

## **What changes do you think we should make in order to solve the problem?**
We should pass ```onIconRightPress``` prop in order to make arrow pressable and navigate to the appropriate screen. For example:

```javascript
                           <MenuItem
                                label={shareDestination.displayName ? props.translate('newTaskPage.shareSomewhere') : ''}
                                title={shareDestination.displayName || ''}
                                description={shareDestination.displayName ? shareDestination.subtitle : props.translate('newTaskPage.shareSomewhere')}
                                icon={shareDestination.icons}
                                onPress={() => Navigation.navigate(ROUTES.NEW_TASK_SHARE_DESTINATION)}
                                interactive={!props.task.parentReportID}
                                shouldShowRightIcon={!props.task.parentReportID}
                                onIconRightPress={() => Navigation.navigate(ROUTES.NEW_TASK_SHARE_DESTINATION)}
                            />
```
## **What alternative solutions did you explore? (Optional)**
N/A

**Comment by strepanier03** [comment] 2023-10-07 00:10
I'll test Monday and action.

**Comment by strepanier03** [comment] 2023-10-09 17:04
I'm unable to recreate this behavior on any of the devices/platforms in the OP description. Going to close this out since it appears it is resolved with this commit
https://github.com/Expensify/App/commit/9987574b30574e6e0404e00ec6cb9edb88199b2e.

**Closed by strepanier03** 2023-10-09 17:04 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
