### ISSUE TITLE
[$250] WS - Profile - Share - Workspace QR code is not downloaded to the device

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40080] opened 2024-04-11 06:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4489045
**Email or phone of affected tester (no customers):** applausetester+041023dr02@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open Expensify App on mobile device
2. Login with any account
3. Go to any workspace > Settings > Profile or User > Settings
4. Click on the Share button
5. Click on the download option
6. Verify the QR code is downloaded to the device

## Expected Result:
QR code is downloaded to the device

## Actual Result:
Nothing happens. Workspace QR code is NOT downloaded to the device.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[Bug6445227_1712791486535!Profile_trace_for_1.4.62-0.cpuprofile](https://github.com/Expensify/App/files/14942286/Bug6445227_1712791486535.Profile_trace_for_1.4.62-0.cpuprofile)

https://github.com/Expensify/App/assets/115492554/f45d9d61-4b50-4b82-81a3-c5df9248e63a

[Bug6445227_1712791486543!App_Info_1.4.62-0.json](https://github.com/Expensify/App/files/14942300/Bug6445227_1712791486543.App_Info_1.4.62-0.json)
[Bug6445227_1712791486538!logs-2024-04-10_23_13_01.025.txt](https://github.com/Expensify/App/files/14942301/Bug6445227_1712791486538.logs-2024-04-10_23_13_01.025.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fdd6488cdadd975</li>
        <li>Upwork Job ID: 1778361122906787840</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-11 06:43
@JmillsExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-11 06:43
We think this issue might be related to the #collect project.

**Comment by lakchote** [comment] 2024-04-11 10:20
Here is the error:
<img width="399" alt="image" src="https://github.com/Expensify/App/assets/21549771/4d3894ea-944b-4466-9377-0c0df489a622">

I thought it'd be a dependency update given the component's code for QRShareWithDownload hasn't changed but it doesn't seem like it.

I've tried to revert:
- https://github.com/Expensify/App/pull/39372
- https://github.com/Expensify/App/pull/40008
- https://github.com/Expensify/App/pull/39854

But that didn't fix it.

**Comment by s77rt** [comment] 2024-04-11 11:22
Regression from https://github.com/Expensify/App/pull/13767. `react-native-view-shot` does not support new arch yet, there is this merged PR https://github.com/gre/react-native-view-shot/pull/516 but no new version yet.

**Comment by s77rt** [comment] 2024-04-11 11:27
And it requires react-native 0.74.0 which is also not released yet

**Comment by WoLewicki** [comment] 2024-04-11 11:58
@s77rt did you maybe try to apply the changes from the PR to the App to see what is not yet present in RN 0.73.x? Ping me if you have problems with making it work and we will also take a look and try to make it work in App.

**Comment by Julesssss** [comment] 2024-04-11 13:05
I agree with not blocking on this. But to avoid confusion lets hide the download button while we're awaiting a proper fix.

**Comment by lakchote** [comment] 2024-04-12 13:44
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> QR code download using `react-native-view-shot` doesn't work after moving to the new arch.
> 
> ### What is the root cause of that problem?
> The `react-native-view-shot` library has introduced the new architecture support in latest version, but we are still using 3.8.0. ([gre/react-native-view-shot#516](https://github.com/gre/react-native-view-shot/pull/516))
> 
> Also, [these](https://github.com/facebook/react-native/pull/43594) changes in react-native need to be included.
> 
> ### What changes do you think we should make in order to solve the problem?
> Add patch for the view-shot library with the changes for the new architecture or bump the version to `4.0.0-alpha.0`. Add patch for [these](https://github.com/facebook/react-native/pull/43594) changes in `react-native`.

I'm not a fan of patching since it's not a critical matter and the new version for `react-native` will fix this.

@s77rt thoughts?

**Comment by WoLewicki** [comment] 2024-04-12 14:25
I'm testing bumping the version of library and adding all the proper files to `react-native` as a patch as part of the efforts of follow-ups to this PR: https://github.com/Expensify/App/pull/13767. I'll try to report quickly if it is a viable option.

**Comment by WoLewicki** [comment] 2024-04-12 15:08
From a quick look it seems to still not work correctly after bumping the version with only the one commit mentioned here:  https://github.com/gre/react-native-view-shot/pull/516#issue-2200273763 is not enough to make it work on `Android`. Also, `iOS` needs bump of version and probably multiple commits to start working again too. So I think we should leave till we bump the App to RN `0.74`.

**Comment by s77rt** [comment] 2024-04-19 23:32
Oops didn't notice this on K2. Waiting for RN 0.74 seems best since the QR download button is a minor functionality. Let's close this issue since we have this tracking one https://github.com/Expensify/App/issues/40110

**Closed** 2024-04-29 14:33 UTC
Labels: Reviewing, External, Engineering, Daily, Help Wanted, Bug
