### ISSUE TITLE
[HOLD for payment 2024-12-05] [HOLD for payment 2024-12-03] Android Hybrid - Login - Blank page if logging in via Magic Link and crash if resending link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53033] opened 2024-11-23 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.66-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** ibellicotest+35@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Log out from the account.
3. Tap on "Log In"
4. Complete with any account and tap on "Next"
5. Wait for the Email with Magic Code and Magic Link to arrive.
6. Open the Email and tap on "Click this Magic Link"
7. Verify you are redirected to the app again and logged in to the account.

## Expected Result:
The user should be logged in to the chosen account after tapping on "Click on this Magic Link" on the received Email.

## Actual Result:
When the user receives Email with Magic Code and Magic Link and taps on "Click on this Magic Link" to log in to the account, a blank page is displayed when redirected to app. After killing the app, re opening it and tapping on "Didn´t receive Magic Code?", the app crashes.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

[2311_1.txt](https://github.com/user-attachments/files/17882264/2311_1.txt)

https://github.com/user-attachments/assets/f39c865d-d635-436f-9a14-14cec2110d7f
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by mateuuszzzzz** [comment] 2024-11-25 15:01
Hi @IuliiaHerets! What is your OS version and device model? It would greatly help in identifying the root cause in Crashlytics.

**Comment by mountiny** [comment] 2024-11-25 16:07
the device used was: Motorola Moto G60 - Android 12

**Comment by mountiny** [comment] 2024-11-25 16:25
Seems like not a backend issue

**Comment by garrettmknight** [comment] 2024-11-25 17:48
@mountiny should we assign @war-in or yourself to this one since you're actively working on it?

**Comment by srikarparsi** [comment] 2024-11-25 17:50
I added @mountiny, this is the [slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1732389054691799), I think we're just checking to make sure this [PR](https://github.com/Expensify/App/pull/53074) doesn't break anything on IOS

**Comment by mountiny** [comment] 2024-11-25 18:02
PR looks promising so moving it to staging to thoroughly test

**Comment by mountiny** [comment] 2024-11-25 18:30
Fix CPed

**Comment by mountiny** [comment] 2024-11-29 10:01
This was fixed by changes in the oldApp as we enabled deeplinks for the hybrid app. SWM was aware of these changes, no regression tests required, noone to pay either

**Closed by mountiny** 2024-11-29 10:01 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
