### ISSUE TITLE
[$2000] Split bill - Split bill is displayed twice if swipe back from split bill chat

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22313] opened 2023-07-05 21:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/
2. Tap on "+" FAB
3. Tap "Split bill"
4. Enter amount
5. Tap "Next"
6. Select users
7. Tap "Next"
8. Tap "Split"
9. Swipe to the right
10. Swipe to the right again

## Expected Result:
User lands in LHN either at step 9 or 10

## Actual Result:
"Split bill enter mount" page is displayed twice when user swipes to the right at steps 9 and 10 from split bill chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/db145200-7e46-4e93-9485-454b8a421b7f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019fd945448c329b5e</li>
        <li>Upwork Job ID: 1679918056642871296</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-06 04:47
Looks like Backend error.

**Comment by manjesh-yadav** [comment] 2023-07-06 10:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill is displayed twice if swipe back from split bill chat
### What is the root cause of that problem?

We should not Enforces navigation to fallback route when a money request has already been created and we have a new `moneyRequestId` it forces to reload the same route again when we go back



### What changes do you think we should make in order to solve the problem?

```diff
useEffect(() => {
        // ID in Onyx could change by initiating a new request in a separate browser tab or completing a request
        if (prevMoneyRequestId.current !== props.iou.id) {
            // The ID is cleared on completing a request. In that case, we will do nothing
            if (props.iou.id) {
                navigateBack(true);
            }
            return;
        }

        // Reset the money request Onyx if the ID in Onyx does not match the ID from params
        const moneyRequestId = `${iouType.current}${reportID.current}`;
        const shouldReset = props.iou.id !== moneyRequestId;
        if (shouldReset) {
            IOU.resetMoneyRequestInfo(moneyRequestId);
        }

        if (props.iou.amount === 0 || shouldReset) {
-            navigateBack(true);
+          navigateBack();
        }

        return () => {
            prevMoneyRequestId.current = props.iou.id;
        };
    }, [props.iou.amount, props.iou.id]);
```

**Comment by flaviadefaria** [comment] 2023-07-14 18:18
Added the external label.

**Comment by flaviadefaria** [comment] 2023-07-17 10:04
@parasharrajat thoughts on the proposal above?

**Comment by flaviadefaria** [comment] 2023-07-24 12:56
@parasharrajat do you have an update?

**Comment by flaviadefaria** [comment] 2023-07-26 09:06
Friendly bump here!

**Comment by flaviadefaria** [comment] 2023-07-31 08:40
@parasharrajat have you reached nay conclusions? Do you need help? We can always take this to Slack for discussion if needed.

**Comment by flaviadefaria** [comment] 2023-08-02 13:50
Friendly bump @parasharrajat!

**Comment by flaviadefaria** [comment] 2023-08-07 12:26
Cool waiting for an update from you in the next days @parasharrajat.

**Comment by flaviadefaria** [comment] 2023-08-18 10:27
@greg-schroeder I'm heading OoO for a week so reassigning this in the meantime.

**Comment by flaviadefaria** [comment] 2023-08-18 10:28
@parasharrajat it's been over a week since your last update can you please provide an update today? Thanks!

**Comment by greg-schroeder** [comment] 2023-08-21 17:44
Yes, bump @parasharrajat!

**Comment by greg-schroeder** [comment] 2023-08-24 17:09
Perhaps we should re-assign this @flaviadefaria?

**Comment by greg-schroeder** [comment] 2023-08-30 12:55
Re-assigning new C+ per slack thread

**Comment by flaviadefaria** [comment] 2023-08-30 13:18
Thanks @greg-schroeder I was OoO but am back now and will take this over again.

**Comment by cubuspl42** [comment] 2023-08-31 08:43
I think @parasharrajat did a good job investigating this issue. [This thread](https://github.com/bernhardoj/Expensify/commit/74dac7e0730409592af6225ac3bbc94ae56902ed#r122124171) is a good summary of the findings. 

I'm also not completely convinced by the single proposal we have so far. In my experience, issues related to navigation might seem trivial but can be difficult to get right. I believe that in this case, raising the bounty to get more eyes on it is appropriate. When it's done, I can also post a message on Slack.

**Comment by flaviadefaria** [comment] 2023-09-05 10:48
Raised the bounty as suggested.

**Comment by cubuspl42** [comment] 2023-09-05 11:39
[Advertised on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1693913877858359)

**Comment by ShogunFire** [comment] 2023-09-05 12:28
I think we need more informations on why the dismissModal act this way:

> Navigation.dismissModal(); can accept a targetReportID. If it's empty or equal to getTopmostReportId, it will simply pop all the RHP modals. In this case, going back won't open back the RHP.
https://github.com/Expensify/App/blob/391c41267ccb6dc14530ea552bf08772f99ce0ec/src/libs/Navigation/Navigation.js#L154-L162
But this is not the case when targetReportID exists and is not equal to getTopmostReportId. It will replace the RHP with the target report screen, and going back will open back the RHP. This issue is happening https://github.com/Expensify/App/issues/21356 and https://github.com/Expensify/App/issues/22313 which I believe you came from the 2nd issue.

I feel like dismissModal should pop the RHP screens in every cases. Do you know about this @adamgrzybowski ?

**Comment by pradeepmdk** [comment] 2023-09-05 12:41
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
 Split bill - Split bill is displayed twice if swipe back from split bill chat

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L75-L80
here when `shouldReset` resetting the form we are creating the fallback route. why means when `navigateBack(true)` it will pass to here
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L59
here we are passing fallbackroute to `goback` function  in this `shouldEnforceFallback` true means it will create the fallbackroute again its goes to `"split/new/"` we already one have ""split/new/"" so that its rendered twice

https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/libs/Navigation/Navigation.js#L130


### What changes do you think we should make in order to solve the problem?
we should update shouldReset false only we need to create fallback route
```javascript
 navigateBack(!shouldReset);
```

**Comment by napster125** [comment] 2023-09-05 13:34
I can't reproduce this issue, is there any specific step?

**Comment by cubuspl42** [comment] 2023-09-05 14:49
Ouch. It seems that I made a fuss, assuming that this bug is reproducible. I just checked that this indeed does not occur anymore.

@napster125 @bernhardoj Thank you for checking!

@flaviadefaria I believe that we can just close this in such case

**Comment by pradeepmdk** [comment] 2023-09-05 15:31
@cubuspl42 this is weird I am still able to reproduce in iOS/Safari. I am in main with latest only.

https://github.com/Expensify/App/assets/16595846/a77541fc-3080-4c5f-8f1f-dba061c5f8ad

**Comment by pradeepmdk** [comment] 2023-09-05 17:42
@cubuspl42 on staging I am not able to reproduce this one. There may be something wrong in my local.

**Comment by cubuspl42** [comment] 2023-09-11 08:52
This issue should be closed, as finally [it turned out it's not reproducible](https://github.com/Expensify/App/issues/22313#issuecomment-1706768352)

**Comment by flaviadefaria** [comment] 2023-09-11 10:41
Thanks @cubuspl42 and everyone else.

**Closed by flaviadefaria** 2023-09-11 10:41 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
