### ISSUE TITLE
[PAID] [$125] Web - App crashes when navigate /request/new/confirmation page directly

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27085] opened 2023-09-09 11:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open https://staging.new.expensify.com/request/new/confirmation
2. Observe that it's redirected to /request/new/distance
3. Close RHP
4. Send message containing https://staging.new.expensify.com/request/new/confirmation in any chat
5. Click this link

## Expected Result:
Navigate to RHP

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/33daa437-c3b3-4b92-80ee-018065fc7940

https://github.com/Expensify/App/assets/93399543/37d89ffa-900d-4a36-b027-77bb1e5b03d8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693886463699189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b6aa9a432e651fc5</li>
        <li>Upwork Job ID: 1700477720195043328</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>sourcecodedeveloper | Contributor | 26730222</li>
<li>situchan | Reporter | 26730224</li>
</ul></li>
    </ul>
</details>

**Comment by sourcecodedeveloper** [comment] 2023-09-10 12:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
login app and open request/new/confirmation, observe the RHP open, close the RHP. Open any chat and paste the link  https://staging.new.expensify.com/request/new/confirmation 

click on the link and observe the app crash.

### What is the root cause of that problem?

The root cause is in Navigation.js goback function. The goback() is using navigationRef.current.getState(). Notice how the first time the request/new/confirmation page loads the RHP opens but does not crash, but after closing RHP and clicking on the link in the chat causes the app to crash. That is because
getState() only stores the right model navigator route the first time the page loads, after closing the RHP the state information is not preserved. Next the fuction below is called

`const isFirstRouteInNavigator = !getActiveRouteIndex(navigationRef.current.getState());
`
because the state information of RHP is not preserved, the return value from getActiveRouteIndex is 0 which is true and the execution flow through the if condition check
```
if (isFirstRouteInNavigator) {
    const rootState = navigationRef.getRootState();
    const lastRoute = _.last(rootState.routes);
    // If the user comes from a different flow (there is more than one route in RHP) we should go back to the previous flow on UP button press instead of using the fallbackRoute.
    if (lastRoute.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && lastRoute.state.index > 0) {
        navigationRef.current.goBack();
        return;
    }
}

```
then the code is calling getRootState() which grabs the root state which does have th RHP state but the state is undefined and the execution flow continue to check lastRoute.state.index where state is undefined and the app crashes.


### What changes do you think we should make in order to solve the problem?
Need to make these changes

1) getRootState should be used instead of getState() like below
`const isFirstRouteInNavigator = !getActiveRouteIndex(navigationRef.current.getRootState());
`
2) getActiveRouteIndex should check for route.state along with route.name,

if (route.state && route.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR) {
        return 0;
}



### What alternative solutions did you explore? (Optional)

**Comment by pradeepmdk** [comment] 2023-09-11 10:01
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes when navigate /request/new/confirmation page directly]

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L118
and 
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L121
We are using `navigationRef.current.getState()` and `navigationRef.getRootState()` both are working differently. RHP closes time the state is reset at the time `navigationRef.current.getState()` completed removed the right side navigation but in the `navigationRef.getRootState()` only remove the state field. so that when state field is undefined trying to get index filed so its crashes.

### What changes do you think we should make in order to solve the problem?
1) 
when `RIGHT_MODAL_NAVIGATOR` is not there in the `navigationRef.current.getState()` means it returns some other state index in this function like `CentralPaneNavigator` state
https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L118
so we need change this function using lodash filter only ` NAVIGATORS.RIGHT_MODAL_NAVIGATOR` and return their state index.

in this function  `getActiveRouteIndex(navigationRef.current.getState())` to 
 `getActiveRouteIndex(navigationRef.getRootState())` also not worked. because of the above statement.

2) just checking the state is key there or not
```javascript
lastRoute.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && lastRoute.state.index > 0
to 
lastRoute.name === NAVIGATORS.RIGHT_MODAL_NAVIGATOR && lastRoute.state && lastRoute.state.index > 0
```  
or we can use lodash get `lodashGet(lastRoute, 'state.index', 0) > 0`

**Comment by sourcecodedeveloper** [comment] 2023-09-11 10:31
@sobitneupane please review [proposal](https://github.com/Expensify/App/issues/27085#issuecomment-1712800059)

**Comment by flaviadefaria** [comment] 2023-09-11 11:28
It seems like @strepanier03 was assigned here first so unassigning myself. @strepanier03 let me know in case I missed something.

**Comment by strepanier03** [comment] 2023-09-12 20:50
@flaviadefaria - That's fine, thanks for the heads up. Been seeing the double assignment quite frequently lately so no worries at all, I got this.

**Comment by sourcecodedeveloper** [comment] 2023-09-13 08:35
@strepanier03 @sobitneupane requesting to review [proposal](https://github.com/Expensify/App/issues/27085#issuecomment-1712800059). actually some proposals have suggested duplicate solutions.

**Comment by sobitneupane** [comment] 2023-09-14 09:21
Thanks for the proposal everyone.

@sourcecodedeveloper Can you please explain why should the `getState` should be replaced by `getRootState`? We are using `getActiveRouteIndex` in other places as well. Won't the change in `getActiveRouteIndex` affect other use cases? Don't you think its good idea to just use lodashGet [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L124)?

Detailed explanation with references will be appreciated.

**Comment by sobitneupane** [comment] 2023-09-14 09:22
FYI, [This](https://github.com/Expensify/App/pull/23007) was the PR which introduced the codeblock.

**Comment by pradeepmdk** [comment] 2023-09-14 09:48
@sobitneupane `getActiveRouteIndex` used here only.  and  I already updated the reason behind this one https://github.com/Expensify/App/issues/27085#issuecomment-1713570089

**Comment by sourcecodedeveloper** [comment] 2023-09-14 12:38
> Thanks for the proposal everyone.
> 
> @sourcecodedeveloper Can you please explain why should the `getState` should be replaced by `getRootState`? We are using `getActiveRouteIndex` in other places as well. Won't the change in `getActiveRouteIndex` affect other use cases? Don't you think its good idea to just use lodashGet [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L124)?
> 
> Detailed explanation with references will be appreciated.

I checked the call to getActiveRouteIndex is being used in Navigation.js only and in two locations

Line# 58 return getActiveRouteIndex(childActiveRoute, route.index || 0);
Line# 63 return getActiveRouteIndex(childActiveRoute, route.state.index || 0);

and the actual call 

Line 118# const isFirstRouteInNavigator = !getActiveRouteIndex(navigationRef.current.getState());


The reason why lastRoute.state is showing undefined is because inside the if (isFirstRouteInNavigator) 
line# 121 navigationRef.getRootState() is being called. The getRootState function correctly captures the state as being undefined,
the execution should have not entered that if (isFirstRouteInNavigator) block should the state have been undefined. So the point is when the lastRoute.state is undefined the execution should have skipped on that if (isFirstRouteInNavigator) block. Execution should only enter the if block should the lastRoute.state be defined. As for the fallbackRoute, in the event if the fallbackRoute is also not available the execution would eventually hit Line 135 and call navigationRef.current.goBack()



> Thanks for the proposal everyone.
> 
> @sourcecodedeveloper Can you please explain why should the `getState` should be replaced by `getRootState`? We are using `getActiveRouteIndex` in other places as well. Won't the change in `getActiveRouteIndex` affect other use cases? Don't you think its good idea to just use lodashGet [here](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L124)?
> 
> Detailed explanation with references will be appreciated.

I checked the call to getActiveRouteIndex is being used in Navigation.js only and in two locations

Line# 58 return getActiveRouteIndex(childActiveRoute, route.index || 0);
Line# 63 return getActiveRouteIndex(childActiveRoute, route.state.index || 0);

and the actual call 

Line 118# const isFirstRouteInNavigator = !getActiveRouteIndex(navigationRef.current.getState());


The reason why lastRoute.state is showing undefined is because inside the if (isFirstRouteInNavigator) 
line# 121 navigationRef.getRootState() is being called. The getRootState function correctly captures the state as being undefined, the execution should have not entered that if (isFirstRouteInNavigator) block should the state have been undefined. So the point is when the lastRoute.state is undefined the execution should have skipped on that if (isFirstRouteInNavigator) block. Execution should only enter the if block should the lastRoute.state be defined. As for the fallbackRoute, in the event if the fallbackRoute is also not available the execution would eventually hit Line 135 and call navigationRef.current.goBack()


For the sake of argument,  considering Line# 121 if getState() were to be used instead of getRootState(), the lastRoute.name would turn out to be centralpanenavigator and not match NAVIGATORS.RIGHT_MODAL_NAVIGATOR, therefore that if condition would get skipped anyway so there would be no point in putting the lodashGet or lastRoute.state check in that if [condition](https://github.com/Expensify/App/blob/6b1a6679042c4fa9bb628360e028f93a5f27b2f2/src/libs/Navigation/Navigation.js#L124)

![screenshot_getState](https://github.com/Expensify/App/assets/141340971/8c5acd44-af2b-4937-b369-e2085103c33e)

**Comment by sobitneupane** [comment] 2023-09-18 10:49
Thanks for the update @sourcecodedeveloper 

[Proposal](https://github.com/Expensify/App/issues/27085#issuecomment-1712800059) from @sourcecodedeveloper looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by sourcecodedeveloper** [comment] 2023-09-18 11:05
> Thanks for the update @sourcecodedeveloper
> 
> [Proposal](https://github.com/Expensify/App/issues/27085#issuecomment-1712800059) from @sourcecodedeveloper looks good to me.
> 
> 🎀 👀 🎀 C+ reviewed

Thanks for accepting the proposal.

**Comment by sourcecodedeveloper** [comment] 2023-09-18 23:31
@sobitneupane The PR [#27718](https://github.com/Expensify/App/pull/27718) is ready for review.

**Comment by sobitneupane** [comment] 2023-10-02 08:19
The issue is not reproducible any longer on my end. We will not require [the PR](https://github.com/Expensify/App/pull/27718) any longer. But I would request making the payment to the contributor as the PR was already raised and was in good shape.

cc: @mountiny @strepanier03

**Comment by sourcecodedeveloper** [comment] 2023-10-02 08:55
> The issue is not reproducible any longer on my end. We will not require [the PR](https://github.com/Expensify/App/pull/27718) any longer. But I would request making the payment to the contributor as the PR was already raised and was in good shape.
> 
> cc: @mountiny @strepanier03

@sobitneupane Thanks

**Comment by sourcecodedeveloper** [comment] 2023-10-02 09:12
> The issue is not reproducible any longer on my end. We will not require [the PR](https://github.com/Expensify/App/pull/27718) any longer. But I would request making the payment to the contributor as the PR was already raised and was in good shape.
> 
> cc: @mountiny @strepanier03

@sobitneupane Thanks

**Comment by mountiny** [comment] 2023-10-02 20:57
In such cases we usually follow the 25% rule so I would pay $125 to @sourcecodedeveloper sorry this did not work out fully

**Comment by sourcecodedeveloper** [comment] 2023-10-09 19:53
@strepanier03 @mountiny Please confirm once payment has been sent.

**Comment by mountiny** [comment] 2023-10-09 20:54
@strepanier03 Could you please pay $125 to @sourcecodedeveloper for their work on this issue which at the later phase got resolved by other changes unrelated to this issue? 

Also $50 to @situchan for reporting

**Comment by strepanier03** [comment] 2023-10-12 22:23
Sure thing, will take care of that.

**Comment by strepanier03** [comment] 2023-10-12 22:32
@sourcecodedeveloper - Can you please apply for this [job](https://www.upwork.com/jobs/~01ae5ff3c35c9ca2f5) or share your UPwork profile with me? I'm not sure who you are in Upwork so can't hire you directly at this time.

**Comment by situchan** [comment] 2023-10-12 22:35
@strepanier03 I can help on behalf

Here it is - https://github.com/Expensify/App/issues/23488#issuecomment-1664115599

**Comment by sourcecodedeveloper** [comment] 2023-10-13 08:33
@strepanier03 
upwork profile: https://www.upwork.com/freelancers/~01d03b3b9d60c82dde

**Comment by smukherjee-drapefit** [comment] 2023-10-13 15:36
Hello

**Comment by smukherjee-drapefit** [comment] 2023-10-13 15:37
Can we work with together at this prj?

**Comment by strepanier03** [comment] 2023-10-16 18:24
Thank you @situchan, I appreciate it a lot!

@sourcecodedeveloper - I've sent you the offer and will check again by the end of the day to pay.

----

@smukherjee-drapefit - This issue is already resolved and is set to be closed in the next day or two. 

Was there something specific you were asking to work on? Check out our [contributing.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#contributing-to-expensify) to learn more about how to work as a member of our community.

**Comment by strepanier03** [comment] 2023-10-17 00:12
@sourcecodedeveloper - I've paid out your contract in UpWork and closed the contract. 

@situchan - I've hired you to a reporting job and will check back in for payment. Sorry, I missed that before.

**Comment by situchan** [comment] 2023-10-17 05:51
I already accepted offer from https://github.com/Expensify/App/issues/27085#issuecomment-1723179949

**Comment by strepanier03** [comment] 2023-10-17 23:36
Aaah, that comment was hidden and I missed it, thanks for linking it. Handling now.

**Comment by strepanier03** [comment] 2023-10-17 23:40
Okay, everyone's been paid here and I unraveled the mess I made. 

Thanks again everyone!

**Closed by strepanier03** 2023-10-17 23:40 UTC
Labels: Reviewing, External, Daily, Awaiting Payment, Bug
