### ISSUE TITLE
[HOLD for payment 2024-01-04] [$500] Distance - Description is not saved when created offline and description edit message becomes amount

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31142] opened 2023-11-09 16:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: Have some saved address offline
1. Navigate to staging.new.expensify.com
2. Go offline
3. Go to workspace chat > + > Distance
4. Create a Distance request that has a description
5. Go to Distance request details page
6. Click on Description and add a description again
7. Go online

## Expected Result:
In Step 5, the description which is added in Step 4 will appear in the distance details page
In Step 7, when the request is created, the system message for 'set a description to' will not change

## Actual Result:
In Step 5, the description which is added in Step 4 is not saved
In Step 7, when the request is created, the system message for 'set a description to' changes to 'changed the amount to 0.00'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/89259ef6-84ad-4dc5-957e-6f1dc55ff037

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018d38eec8fb70c3c2</li>
        <li>Upwork Job ID: 1722653765286424576</li>
        <li>Last Price Increase: 2023-11-09</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27953114</li>
<li>esh-g | Contributor | 27953116</li>
</ul></li>
    </ul>
</details>

**Comment by esh-g** [comment] 2023-11-09 17:04
# Proposal

## Please re-state the problem
Distance - Description is not saved when created offline and description edit message becomes amount

## Root cause
This happens because we don't do a deep merge here:
https://github.com/Expensify/App/blob/7b78542175a9c56359f23c47cc7ff2fb2c08aa4a/src/libs/actions/IOU.js#L511-L522

## What changes should be made to fix this?
We just do a deep merge at the fore-mentioned code:
```js
if (existingTransaction) {
    optimisticTransaction = merge(optimisticTransaction, existingTransaction),
}
```
import merge function from lodash

**Comment by esh-g** [comment] 2023-11-09 17:09
>These are still all in the code, but it's not causing any problems, so I am just going to close this since I haven't had any chance to look into it.

@tgolen Seems like it is causing problems... 😅

**Comment by tgolen** [comment] 2023-11-09 17:15
There is a first time for everything! Thanks for looking into it.

**Comment by esh-g** [comment] 2023-11-09 17:21
@0xmiroslav You can see the following line comment in the code I quoted in my proposal
> If there is an existing transaction (which is the case for distance requests)

Basically it is because `distanceRequest` already have a transaction created with the waypoints set and we need to merge the optimistic transaction into it which has the description that user entered.
For manual requests, there is no existing transaction

**Comment by esh-g** [comment] 2023-11-13 16:47
@0xmiroslav Please also notice that @namhihi237 builds upon my proposal of using deep merge (moreover, 'deep merge' isn't even mentioned in their proposal, only 'deep copy') and as for the second issue, I think it might be better that we handle the amount issue on the backend... because currently, when we change any field of the transaction, we send the whole transaction as a parameter to be updated. This means that even if we implement the proposed solution, the backend still sends the message that amount is changed, we just don't display it.

<img width="655" alt="Screenshot 2023-11-13 at 10 14 54 PM" src="https://github.com/Expensify/App/assets/77237602/0352e271-564a-44a1-b0a0-0fdf51dea79e">

**(notice the amount and also the category)**

I think it would be better if we:
Option 1: Change the api endpoint to only accept the changed fields in the transaction.
Option 2: Add a safeguard in the backend that makes sure the amount is not set to 0

**Comment by dylanexpensify** [comment] 2023-11-14 09:30
@youssef-lr to confirm proposal! Though @youssef-lr I know you're about to head ooo, so let us know if we should reassign!

**Comment by DylanDylann** [comment] 2023-11-17 04:51
@youssef-lr @0xmiroslav Relating to the second problem of this issue, while checking this issue I see that when creating a distance request offline and going to the transaction thread, the reportID of the transaction thread is only optimistic reportID. Then if we go online, the BE will return another reportID for the transaction thread. So that if we are in a transaction thread and go online, there are no updates, we need to back to the expense report and go to the transaction thread again to get new updates



https://github.com/Expensify/App/assets/141406735/4ba45deb-0522-4d03-b6ad-3b98989b9546

**Comment by dylanexpensify** [comment] 2023-11-22 09:23
bump @0xmiroslav for reply on above! 🙇‍♂️

**Comment by techievivek** [comment] 2023-11-28 20:53
Not overdue, will take a look into it tomorrow morning.

**Comment by techievivek** [comment] 2023-12-01 07:57
Hmm, I am a bit confused about why we send all the details when we call `UpdateDistanceRequest` instead of sending just the updated field? Like in this case just the updated comment field.

**Comment by techievivek** [comment] 2023-12-01 08:15
This appears to be a critical bug from a logical standpoint. It seems that when we intend to update only the description, the system is also updating the amount, category, and description fields.

<img width="1299" alt="Screenshot 2023-12-01 at 1 43 01 PM" src="https://github.com/Expensify/App/assets/35863227/c5a80827-ac69-4482-8591-c9eb66f0667b">

I will reach out to @arosiclair to take a look at this issue since he seems to have on the backend part of it.

**Comment by tgolen** [comment] 2023-12-01 17:26
@techievivek this API is being refactored in https://github.com/Expensify/App/issues/28358 due to issues exactly like this so I think we can close this.

**Comment by tgolen** [comment] 2023-12-01 17:49
I think that's a good idea. I looked at the proposal and I was left a little curious about what exactly "deep copy" or "deep merge" implies. I would like to see the proposal updated to be a little more descriptive on what the intended solution is.

**Comment by esh-g** [comment] 2023-12-01 18:59
@0xmiroslav I have already proposed in my proposal the exact solution: to use the merge function imported from the lodash library. Please do let me know if any further details are required...

**Comment by esh-g** [comment] 2023-12-02 13:53
@tgolen I have updated my [proposal](https://github.com/Expensify/App/issues/31142#issuecomment-1804217463) root cause explaining this in more detail and also an example.

**Comment by arosiclair** [comment] 2023-12-04 14:17
Thanks for the update that description makes sense to me. Any objections @tgolen?

**Comment by tgolen** [comment] 2023-12-04 16:13
As long as it doesn't need to be performant, I think that is fine. If I recall, we built our own `fastMerge()` lib that we use in `react-native-onyx` where we needed something super performance since it was so low-level.

**Comment by esh-g** [comment] 2023-12-04 16:38
@tgolen I just checked and `OnyxUtils.fastMerge()` works well in this case as well. I'll go ahead with that in the PR

**Comment by dylanexpensify** [comment] 2023-12-05 19:15
Making progress!

**Comment by dylanexpensify** [comment] 2023-12-20 09:24
Any update @0xmiroslav

**Comment by dylanexpensify** [comment] 2024-01-09 12:19
Payment Summary:
- Contributor: @esh-g $500
- Contributor+: @0xmiroslav $500

Please apply!

**Comment by dylanexpensify** [comment] 2024-01-09 12:21
Just paid! Had to post summary for good measure!

**Comment by dylanexpensify** [comment] 2024-01-09 12:21
@0xmiroslav mind completing checklist?

**Closed** 2024-01-15 10:42 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
