### ISSUE TITLE
[$500] IOU - Description and Merchant in IOU preview are displayed in different style

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35393] opened 2024-01-30 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.33-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM.
2. Create two money requests - one with merchant, and another one with only description.
3. Go to IOU report.

## Expected Result:
Merchant and Description will be displayed in IOU preview in the same style.

## Actual Result:
Merchant is not bolded and appear grayed out, while the description is bolded in IOU preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7eadc010-39c7-4b5d-9976-4b7785206c4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01370109af3b78ad99</li>
        <li>Upwork Job ID: 1752312317782040576</li>
        <li>Last Price Increase: 2024-01-30</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 12:47
We think that this bug might be related to #vip-bills
CC @davidcardoza

**Comment by DylanDylann** [comment] 2024-01-30 13:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Merchant is not bolded and appear grayed out, while the description is bolded in IOU preview.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/27271d566ec42815e6c34d61e43ccb39840e3ce0/src/components/ReportActionItem/MoneyRequestPreview.js#L337-L338

we are rendering merchant and description in 2 different way 
### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/27271d566ec42815e6c34d61e43ccb39840e3ce0/src/components/ReportActionItem/MoneyRequestPreview.js#L337-L338

Because in 2 cases, we both render the same value `merchantOrDescription`. So we should update like that
```
{(shouldShowDescription || shouldShowMerchant) && <RenderHTML html={parser.replace(merchantOrDescription)} />} 

```

Or 

```
 {(shouldShowDescription || shouldShowMerchant) && <Text style={[styles.textLabelSupporting, styles.textNormal]}>{merchantOrDescription}</Text>} 
```
### What alternative solutions did you explore? (Optional)
NA

**Comment by bernhardoj** [comment] 2024-01-30 13:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text color style between merchant and description is different.

### What is the root cause of that problem?
The description is rendered with RenderHTML while the merchant is rendered with text with a style that has a `color` of `textSupporting`.
https://github.com/Expensify/App/blob/82ae62f5f5b8ecf4a4f6e9e1bd26269647e3f49f/src/components/ReportActionItem/MoneyRequestPreview.js#L337-L338

The default style for RenderHTML can be seen below which is different from the merchant text style (the color).
https://github.com/Expensify/App/blob/82ae62f5f5b8ecf4a4f6e9e1bd26269647e3f49f/src/styles/index.ts#L217-L220

### What changes do you think we should make in order to solve the problem?

To make them both show the same color, we can wrap the description with `<muted-text>` tag.
```
{shouldShowDescription && <RenderHTML html={`<muted-text>${parser.replace(merchantOrDescription)}</muted-text>`} />}
```

**Comment by rushatgabhane** [comment] 2024-02-05 05:51
reviewing

**Comment by rushatgabhane** [comment] 2024-02-06 05:15
I like @bernhardoj's proposal 🎀 👀 🎀 
https://github.com/Expensify/App/issues/35393#issuecomment-1916810920

**Comment by anmurali** [comment] 2024-02-08 16:09
@marcochavezf based on https://github.com/Expensify/App/issues/35393#issuecomment-1928799752, should we assign the job to @bernhardoj ?

**Comment by marcochavezf** [comment] 2024-02-08 20:42
Yes, assigning @bernhardoj 🚀 thanks for the review @rushatgabhane, and apologies for the delay

**Comment by bernhardoj** [comment] 2024-02-09 06:17
PR is ready

cc: @rushatgabhane

**Comment by rushatgabhane** [comment] 2024-03-11 23:09
@anmurali could you please attach payment summary, thanks 🙇

**Comment by rushatgabhane** [comment] 2024-03-11 23:10
payment request here https://staging.new.expensify.com/r/1789662421125982

**Comment by JmillsExpensify** [comment] 2024-03-18 15:39
@anmurali please add a payment summary when you get a chance.

**Comment by anmurali** [comment] 2024-03-19 21:21
- [ ] Contributor: @bernhardoj $500 via Upwork
- [ ] Contributor+: @rushatgabhane $500 via NewDot

**Comment by anmurali** [comment] 2024-03-19 21:23
@JmillsExpensify added above and paid @bernhardoj. I am closing the issue as it sounds like you already have a ND request for @rushatgabhane and you can check it off here after you process payment for this on ND.

**Closed by anmurali** 2024-03-19 21:23 UTC
Labels: Reviewing, External, Monthly, Bug

**Comment by JmillsExpensify** [comment] 2024-03-20 02:21
$500 approved for @rushatgabhane based on summary.
