### ISSUE TITLE
[$500] Workspace - Icons overlay and phone number cropping on the Onfido page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30057] opened 2023-10-20 08:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR:** https://github.com/Expensify/App/pull/29874

**Version Number:** 1.3.87-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Go to settings > Workspaces > Any workspace > Bank Account > Connect manually.
4. Reach the 3rd step of Connect Bank Account.
5. Go to Passport > Get Secure Link > Get link via sms.
6. Enter the correct phone number and press the Send link (1-st issue - the number is cut off)
7. Clear input field - appear 2 overlapped icons (tube and globe) - 2nd issue

## Expected Result:
No any visual effects (number is not cut off and tube and globe icon are not superimposed)

## Actual Result:
The number is cut off and tube and globe icon are superimposed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![Bug6243622_1697752365735!PR1](https://github.com/Expensify/App/assets/115492554/052b4483-6ff8-496c-b9ba-969144c7f982)

![Bug6243622_1697752365752!PR2](https://github.com/Expensify/App/assets/115492554/12e70355-3b41-47e0-aabf-8fb25257d1e1)

https://github.com/Expensify/App/assets/115492554/df48f28d-d259-4165-95d5-d8b7970cd991

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01719dcab4e36ecb01</li>
        <li>Upwork Job ID: 1715290150161666048</li>
        <li>Last Price Increase: 2023-11-24</li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-10-20 14:38
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Workspace - Phone number cropping on the Onfido page

### What is the root cause of that problem?

This is due to default font size of `--onfido-font-size-base`, which is set to 16px.

### What changes do you think we should make in order to solve the problem?

Add this styling to `index.css` present in Onfido folder
```css
.onfido-sdk-ui-PhoneNumberInput-phoneNumberContainer input {
    font-size: 12px !important;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by Victor-Nyagudi** [comment] 2023-10-21 12:38
I can't reproduce this. 

What buttons are being pressed to clear the number field?

I've tried manually deleting the number, selecting all and then deleting, and selecting all and cutting, but the icons don't show - the flag shows up where the supposed overlapped icons should be. 

I've even tried with the number in the video once, but nothing still.

**Comment by shubham1206agra** [comment] 2023-10-21 12:42
@Victor-Nyagudi Just go to international in dropdown

**Comment by Victor-Nyagudi** [comment] 2023-10-21 15:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Workspace - Icons overlay and phone number cropping on the Onfido page

### What is the root cause of that problem?

The current font size of the phone input is inherited from `.onfido-sdk-ui-PhoneNumberInput-phoneNumberContainer input` class and is a calculation resulting in `1em` that translates to `16px`. This size is slightly too big for the space in the input, so some of the content overflows and is cut off. 

![expensify-onfido-phone-input-class](https://github.com/Expensify/App/assets/79470910/d273ab9c-94a8-410d-b962-c05922da12db)

![expensify-onfido-phone-input-current-font-size](https://github.com/Expensify/App/assets/79470910/ccdc0d9b-e12d-49a6-8640-d4d115175d65)

I believe the icons overlapping is intentional because they appear when you choose "International" from the dropdown. 

The globe means the number is from somewhere in the world (globe icons are used all the time to symbolize something is international), and the telephone above it symbolizes a number one can call. 

When put together (overlapping), these icons symbolize an international phone number. Separating them would result in the meaning being lost i.e. what should one stand for? What's the globe for, and why is it next to a telephone? Are the two separate things?

### What changes do you think we should make in order to solve the problem?

I propose adding a font size to the phone input in the Onfido's CSS file i.e. `index.css` [before the media query](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/components/Onfido/index.css#L50). 

We can use the input's `id` property (see first image above for reference) since this is unique.  There's currently no other styling on the phone input - all the styles it has are inherited. 

```css
#phoneNumberInput {
    font-size: 15px !important;
}
```

I chose `15px` because: 

1. It's the same size as the text that says, "Send this one-time link to your phone" that inherits its size from `.onfido-sdk-ui-PageTitle-subTitle`, so some consistency is assured.

![expensify-onfido-title-HTML-element](https://github.com/Expensify/App/assets/79470910/93787044-8194-4907-9ad4-48845346182d)

![expensify-onfido-title-current-font-size](https://github.com/Expensify/App/assets/79470910/cccdb559-a630-4bc3-afae-ef3d57df6d9d)

2. The phone input text is adjusted by a small number, so it'll still be legible (good for accessibility) and fit the input's container, even for [Chinese numbers](https://worldpopulationreview.com/country-rankings/phone-number-length-by-country) that can be 13 digits long. 

<details>

<summary>Short demo after making changes</summary>

https://github.com/Expensify/App/assets/79470910/7ee3cae9-d5b6-4632-9845-ab015bb93594

</details>

Most international numbers don't usually go over 13 digits, but given [international numbers can be up to 15 digits](https://www.google.com/search?q=inetrnational+phone+number+limit&oq=inetrnational+phone+number+limit&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABgIGA0YHjIKCAIQABgIGA0YHjIKCAMQABgIGA0YHjIKCAQQABgIGA0YHjIKCAUQABgIGA0YHjIKCAYQABgIGA0YHjIKCAcQABgIGA0YHjIKCAgQABiGAxiKBTIKCAkQABiGAxiKBdIBCDkwMjVqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8), should Expensify want to cover numbers that long, then the font size would need to be roughly `13.5px`, give or take half a pixel, to ensure the whole number is shown in the input. 

```css
#phoneNumberInput {
    font-size: 13.5px !important;
}
```

Here's what it would look like at `13.5px`. 

![expensify-15-digit-number-13-and-half-px-size](https://github.com/Expensify/App/assets/79470910/35587355-ee04-4e18-a782-d78caeda9829)

### What alternative solutions did you explore? (Optional)

I decided to style the input using just the `id` and `!important` which I felt was enough in terms of specificity, but if we wanted to go all out and ensure nothing else overwrites the font size change, we could add an element and a class to the selector. 

Something like this. 

```css
input#phoneNumberInput.PhoneInputInput {
    font-size: 15px !important;
}
```

**Comment by burczu** [comment] 2023-10-24 07:11
@shubham1206agra @Victor-Nyagudi I think you both identified the root cause correctly and I agree overlapping two icons is intentional. In terms of the solution I think styling CSS ids should be avoided so I tend to prefer the solution from @shubham1206agra but I wonder if we could also avoid using `!important` modifier somehow?

**Comment by shubham1206agra** [comment] 2023-10-24 07:15
> @shubham1206agra @Victor-Nyagudi I think you both identified the root cause correctly and I agree overlapping two icons is intentional. In terms of the solution I think styling CSS ids should be avoided so I tend to prefer the solution from @shubham1206agra but I wonder if we could also avoid using `!important` modifier somehow? 

`!important` is required here to enforce the styling cause onfido styles apply later due to compilation. And it is used throughout the index.css file.

**Comment by Victor-Nyagudi** [comment] 2023-10-24 07:24
@burczu In my alternate solution, I explored using a different selector for better specificity. 

The `id` included in that one was one possible selector, that's why I used the phrase "something like this".

What do you think of the font size chosen, though?

**Comment by burczu** [comment] 2023-10-26 10:58
@Victor-Nyagudi In terms of avoiding `id` in css styling, this is general rule of thumb in web development, because classes are less specific and you can use more than one class to style single element so they provide better reusability and maintainability. But I think this is special use case where we are overriding styles provided by elements rendered by some external library - in this case I think using `id's` for styling makes sense.

When it comes to the font to choose - I think `15px` would be best because we use this size of fonts for other input elements in the App.

**Comment by burczu** [comment] 2023-10-26 11:05
@anmurali @izarutskaya I'm thinking about this issue and to be honest I'm not sure if this is a bug actually... The input has fixed width based on the width of the sidebar, and I can image there are longer phone numbers in some countries than the input width - should we adjust the font size to cover all the possible phone number formats? I don't think so... If the number does not fit the text input part of it is hidden and it is not a bug in my opinion. What do you think?

**Comment by shubham1206agra** [comment] 2023-10-26 13:32
> @anmurali @izarutskaya I'm thinking about this issue and to be honest I'm not sure if this is a bug actually... The input has fixed width based on the width of the sidebar, and I can image there are longer phone numbers in some countries than the input width - should we adjust the font size to cover all the possible phone number formats? I don't think so... If the number does not fit the text input part of it is hidden and it is not a bug in my opinion. What do you think?

@burczu I think we can adjust the size so that we can see the whole placeholder text atleast

**Comment by burczu** [comment] 2023-10-31 13:01
Just to inform, I'll be ooo for the next few days and we'll be back on Monday, November 6th.

**Comment by burczu** [comment] 2023-11-13 09:50
@anmurali @izarutskaya What do you think about this: https://github.com/Expensify/App/issues/30057#issuecomment-1780900446 - maybe we should ask someone from @Expensify/design?

**Comment by shawnborton** [comment] 2023-11-13 14:57
Yeah, most of these styles are coming from Onfido and sometimes there isn't a whole lot we can do :-/

I agree with Danny though.

**Comment by burczu** [comment] 2023-11-20 09:16
@anmurali It looks like designers agreed with my [comment](https://github.com/Expensify/App/issues/30057#issuecomment-1780900446) ([here](https://github.com/Expensify/App/issues/30057#issuecomment-1808239089) and [here](https://github.com/Expensify/App/issues/30057#issuecomment-1808320995)) that this is not a bug, so I guess we can consider closing this issue. What do you think?

**Comment by anmurali** [comment] 2023-11-29 04:52
Love it, closing as not a bug.

**Closed by anmurali** 2023-11-29 04:52 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
