### ISSUE TITLE
 Not Allowed sign is not shown when dragging attachments on LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23969] opened 2023-07-31 23:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat
2. drag attachments on LHN
## Expected Result: 
Not Allowed sign is shown when dragging the attachment on LHN
## Actual Result: 
Copy sign is shown when dragging the attachment on LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/407e3105-4898-4ee4-98ac-9833e2827d86

![Untitled](https://github.com/Expensify/App/assets/43996225/022b02a5-53d3-4045-a2e8-6a54e5978985)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690836365230309

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2023-07-31 23:38
@roryabraham do you maybe know what is up with this one? I thought I remember you saying something about refactoring drag and drop things.

**Comment by marcaaron** [comment] 2023-07-31 23:39
Related PR -> https://github.com/Expensify/App/pull/23589

**Comment by s-alves10** [comment] 2023-08-01 00:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Not allowed sign isn't shown when dragging attachment on LHN

### What is the root cause of that problem?

We're not wrapping the LHN with NoDropZone

### What changes do you think we should make in order to solve the problem?

Wrapping the LHN with `NoDropZone` would solve the issue
1. Add `fullScreen` props with default true to the `NoDropZone` component
2. Wrap the LHN with `NoDropZone` in `ThreePaneView`

```
        if (route.name === SCREENS.HOME) {
            return (
                <NoDropZone key={route.key} fullScreen={false}>
                    <View
                        style={[styles.borderRight, styles.flex1, styles.leftPanelContainer]}
                    >
                        {props.descriptors[route.key].render()}
                    </View>
                </NoDropZone>
            );
        }
```

This works as expected

<details>
    <summary>Result</summary>


</details>

### What alternative solutions did you explore? (Optional)

**Comment by roryabraham** [comment] 2023-08-01 00:38
> We're not wrapping the LHN with NoDropZone

@s-alves10 I don't think that's the root cause of the problem – its a proposed solution.

**Comment by s-alves10** [comment] 2023-08-01 00:44
@roryabraham 

Can you provide me with the link?

**Comment by roryabraham** [comment] 2023-08-01 00:54
@marcaaron I'll grab this from you since I almost certainly caused it with a recent PR of mine

**Comment by roryabraham** [comment] 2023-08-01 01:22
I think it is a regression, because it's reproducible on staging but not main

**Comment by roryabraham** [comment] 2023-08-01 01:40
Ok, going to close this one in favor of https://github.com/Expensify/App/issues/22218 then and remove the deploy blocker

**Closed by roryabraham** 2023-08-01 01:40 UTC
Labels: DeployBlockerCash, Engineering, Daily, Bug

**Comment by roryabraham** [comment] 2023-08-01 01:46
FWIW I think the simplest quick-and-dirty fix to this issue would be to update [this listener](https://github.com/Expensify/App/blob/6eb03b08dd72f30fdcbae491e7d0d5b9a7dea633/src/pages/home/sidebar/SidebarScreen/index.js#L30) to also set `dropEffect: none` on the event.
