### ISSUE TITLE
Web - Only one Payload formdata with name:expensify_freePlanBankAccountID toggling offline/online in workspace settings

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#9042] opened 2022-05-16 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue was found when executing #8946 
## Action Performed:
1. Launch the NewDot login
2. Click on your profile pic and then click on your Workspace
3. Click on General Settings
4. Open the developer console (F12 on chrome) and go to the Network Tab
5. In the Network tab, turn off the internet connection and then turn it back on
6. Still in the Network Tab, Check the api?command=Get request for payload formData containing name: 

## Expected Result:
There are two api?command=Get request with the payload formData containing name: expensify_freePlanBankAccountID

## Actual Result:
There is only one api?command=Get request with the payload formData containing name: expensify_freePlanBankAccountID

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.61-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/168681441-1e7acb3c-8a96-4950-b442-c9aeb32bdf1b.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2022-05-17 19:50
@kavimuru Why is it expected that there would be two requests? Can you point me to where that assumption comes from?

**Comment by tgolen** [comment] 2022-05-17 19:53
Also, I was unable to reproduce this and I only saw one GET request for `expensify_freePlanBankAccountID`

**Comment by mvtglobally** [comment] 2022-05-25 03:56
@tgolen We found this issue as part of the PR https://github.com/Expensify/App/pull/8946
Steps refer to "make sure there are two api?command=Get requests". Let us know if we misunderstood this step

**Comment by ctkochan22** [comment] 2022-06-08 05:41
I can't get to this at the moment esp after taking on some N7 refactor stuff. Going to unassign

**Comment by mvtglobally** [comment] 2022-08-09 04:36
Issue not reproducible during KI retests. (First week)

**Comment by tgolen** [comment] 2022-08-17 15:47
@PauloGasparSv Can you please help us understand why this is looking for two requests?

> make sure there are two api?command=Get request with the payload formData containing name: expensify_freePlanBankAccountID

I still am only seeing one request, but I _think_ that's the way it should be.

**Comment by PauloGasparSv** [comment] 2022-08-17 15:57
Sure!
@kavimuru @tgolen, I don't think this is an issue.

That was just the amount of times the request appeared to me while testing and developing the feature. And if I removed the network toggle feature one of those request kept being fired.

I think it was being called somewhere else in the code not related to my P.R. and the steps are to make sure my changes were firing a request.

So I think we can close this.

**Comment by tgolen** [comment] 2022-08-17 16:20
Great, thank you! I will do the honors then.

**Closed by tgolen** 2022-08-17 16:20 UTC
Labels: Engineering, Monthly, Improvement
