### ISSUE TITLE
Login - Contradicting instruction on sign-in page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21631] opened 2023-06-26 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to the sign-in page
2. Enter email > click on continue button
3. Request code till system throws "You've reached the maximum number of magic codes. Please wait a few minutes and try again."
4. Observe that 'Request a new code in:30s' message is displayed

## Expected Result:
The system shouldn't display a contradicting message: Wait a few minutes & request a new code in:30s'

## Actual Result:
System displays a contradicting message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.31-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image - 2023-06-26T160704 573](https://github.com/Expensify/App/assets/93399543/7b598529-d354-4817-8ff6-5affe735e409)

![photo_2023-06-25_23-04-08](https://github.com/Expensify/App/assets/93399543/1e984ce4-603c-4ef0-a973-1ece9570c245)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687460550460549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lealobanov** [comment] 2023-06-27 04:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Login shows a contradictory message - "'Request a new code in:30s'" after maximum number of magic codes has been exceeded.

### What is the root cause of that problem?

In the file BaseValidateCodeForm.js, 2 components are used to display a form error and re-issue a new magic code: 

```
{hasError && <FormHelpMessage message={ErrorUtils.getLatestErrorMessage(props.account)} />}
                    <View>
                        {timeRemaining > 0 && !props.network.isOffline ? (
                            <Text style={[styles.mt2]}>
                                {props.translate('validateCodeForm.requestNewCode')}
                                <Text style={[styles.textBlue]}>00:{String(timeRemaining).padStart(2, '0')}</Text>
                            </Text>
                        ) : (
                            <PressableWithFeedback
                                style={[styles.mt2]}
                                onPress={resendValidateCode}
                                underlayColor={themeColors.componentBG}
                                disabled={props.network.isOffline}
                                hoverDimmingValue={1}
                                pressDimmingValue={0.2}
                                accessibilityRole="button"
                                accessibilityLabel={props.translate('validateCodeForm.magicCodeNotReceived')}
                            >
                                <Text style={[StyleUtils.getDisabledLinkStyles(props.network.isOffline)]}>{props.translate('validateCodeForm.magicCodeNotReceived')}</Text>
                            </PressableWithFeedback>
                        )}
                    </View>
```

The hasError flag is used to check whether to show the top error message in red. However, the re-issue code message does not depend on 'hasError'.

### What changes do you think we should make in order to solve the problem?

The View containing reissuance logic should not be shown if hasError is true. 



### What alternative solutions did you explore? (Optional)

If we want to restrict reissuance logic not being shown *only* if the error message is equal to "You've reached the maximum number of magic codes. Please wait a few minutes and try again.", we can validate the contents of 'hasError' as well before hiding the View containing reissuance logic.

**Comment by Christinadobrzyn** [comment] 2023-06-27 17:57
This is a dupe of https://github.com/Expensify/App/issues/21617

**Comment by Christinadobrzyn** [comment] 2023-06-27 18:09
Going to close this one as the other issue was reported first - https://github.com/Expensify/App/issues/21617#issuecomment-1609993292

**Closed by Christinadobrzyn** 2023-06-27 18:09 UTC
Labels: Daily, Bug
