### ISSUE TITLE
IOS - Workspace - App crashed after back online when adjusted workspace name while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10901] opened 2022-09-08 14:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/10723

## Action Performed:
1. Launch the app
2. Log in with expensifail account
3. Create a workspace while offline
4. Notice that the default chats are also created and you are still navigated to the workspace settings
5. Adjust the workspace name while offline and notice that it is updated successfully
6. Go back online and ensure that everything syncs with the server

## Expected Result:
No app crashed after back online when adjusted workspace name while offline

## Actual Result:
App crashed after back online when adjusted workspace name while offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.98.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/189148839-ce1c0628-0c0b-49ba-887a-def035e7f3fc.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2022-09-08 16:20
@marcochavezf Updated, credentials used: applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Comment by marcaaron** [comment] 2022-09-08 16:37
Not able to reproduce this one locally.

**Comment by chiragsalian** [comment] 2022-09-09 00:00
Removing deploy blocker label since we're trying to get https://github.com/Expensify/App/pull/10908 out the door soon.

**Comment by marcochavezf** [comment] 2022-09-12 22:40
Probably related to this [issue](https://github.com/Expensify/App/issues/10897), I'm going to change the priority to daily.

**Comment by marcochavezf** [comment] 2022-09-15 20:04
I'm going to close this issue in favor of https://github.com/Expensify/App/issues/10897, but feel free to re-open it if you think it's a different issue.

**Closed by marcochavezf** 2022-09-15 20:04 UTC
Labels: Engineering, Daily, Overdue
