### ISSUE TITLE
[$500] Dev: Web - Mark as unread not working for [Deleted task]

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27787] opened 2023-09-19 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select assign task
3. Enter title and create task
4. Go to task thread and delete the task
5. Go to parent report screen
6. Hover on [Deleted task] and select mark as unread option

## Expected Result:
New marker should show

## Actual Result:
Does not show new marker

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71.7
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9e9bf68f-8b25-4e3c-9893-7c90ec0798e9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695100712196889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a8da6d5d1e6cf3d</li>
        <li>Upwork Job ID: 1704141069563166720</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-19 14:45
Duplicate of https://github.com/Expensify/App/issues/27780

**Comment by gadhiyamanan** [comment] 2023-09-20 05:08
@paultsimura both are different issues

**Comment by paultsimura** [comment] 2023-09-20 08:17
Sorry @gadhiyamanan I meant that the RCA is likely the same.

**Comment by abekkala** [comment] 2023-09-25 06:24
Steps are a dupe of 27780. closing

**Closed by abekkala** 2023-09-25 06:24 UTC
Labels: External, Daily, Help Wanted, Overdue
