### ISSUE TITLE
[$500] Prevent nesting code blocks in markdown

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#27208] opened 2023-09-12 02:04 UTC
We've been running into all sorts of issues by allowing nested markdown rules. 

Ex: https://github.com/Expensify/App/issues/23034
Ex: https://github.com/Expensify/App/issues/26941

Context: https://expensify.slack.com/archives/C01GTK53T8Q/p1694011229493309

As one of the new rules, let's prevent nested markdown

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f8d855ec7167b7ca</li>
        <li>Upwork Job ID: 1701416634058772480</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Contributor | 27885116</li>
</ul></li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-09-12 05:20
Just to clarify is _**Hello world**_ also nested markdown? Or is it only for cases with code-fence?

**Comment by thienlnam** [comment] 2023-09-12 05:21
Good question, I think code fence situations only

**Comment by alitoshmatov** [comment] 2023-09-12 05:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Prevent nested markdown in code blocks
### What is the root cause of that problem?
I tested all combinations with nested code blocks and it looks like only strikethrough is applied to nested code blocks.
For example here are results of doing `*```bold```*`, `_```italic```_`, `~```strike```~` 
<img width="381" alt="Screenshot 2023-09-12 at 10 36 40" src="https://github.com/Expensify/App/assets/59907218/7b48e081-438c-49a6-bc78-0c6882899a87">

This is because in all other cases except strike-through we are checking if nested content contains `<pre>`, which means codeblock, we do not apply the styling.
https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L209
Only in strikethrough we do not have this condition
https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L214
### What changes do you think we should make in order to solve the problem?
I think adding `g1.includes('<pre>') ` condition should resolve the issue:
```javascript
  replacement: (match, g1) => (g1.includes('<pre>') ||this.containsNonPairTag(g1) ? match : `<del>${g1}</del>`)
```

### What alternative solutions did you explore? (Optional)

**Comment by cubuspl42** [comment] 2023-09-12 09:14
@thienlnam This issue is mistitled, you are talking about fenced code blocks nested in markdown (inlines), not the other way around.

**Comment by cubuspl42** [comment] 2023-09-13 08:12
@parasharrajat Do you suggest extending the scope of this issue and closing the other one?

**Comment by stephanieelliott** [comment] 2023-09-29 05:47
Hey @parasharrajat any update here?

**Comment by stephanieelliott** [comment] 2023-10-04 01:19
Not overdue, @parasharrajat let us know he would be OOO.

**Comment by stephanieelliott** [comment] 2023-10-06 05:11
Het @parasharrajat I believe you're back -- any update on this?

**Comment by stephanieelliott** [comment] 2023-10-10 02:40
Bump on this again @parasharrajat! Just want to check -- are you working on a PR for this (i.e. fixing it yourself)? Should we still be collecting proposals, or is this more of a tracking issue (and thus should be moved to `Weekly`) at this time?

**Comment by stephanieelliott** [comment] 2023-10-11 05:06
Hey @parasharrajat bump on my earlier question: 

> Bump on this again @parasharrajat! Just want to check -- are you working on a PR for this (i.e. fixing it yourself)? Should we still be collecting proposals, or is this more of a tracking issue (and thus should be moved to Weekly) at this time?

**Comment by stephanieelliott** [comment] 2023-10-17 01:17
Sounds good @parasharrajat, will remove the `Help Wanted` label since it sounds like you will be raising the PRs!

**Comment by stephanieelliott** [comment] 2023-10-30 16:09
Hey @parasharrajat any update on this? Seeing as this we're treating this as more of a project and it doesn't have any impact on functionality, I'm going to move this to `Weekly`

**Comment by stephanieelliott** [comment] 2023-11-06 21:38
Bump @parasharrajat, any update?

**Comment by stephanieelliott** [comment] 2023-11-13 15:45
Hey @parasharrajat it's been a while -- can you give an update please?

**Comment by stephanieelliott** [comment] 2023-11-29 00:23
Bumped @parasharrajat for an update in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1701217378545439

**Comment by alitoshmatov** [comment] 2023-12-02 07:40
Looks like this issue was resolved in https://github.com/Expensify/App/issues/24281 which applied the same solution as I proposed.

**Closed** 2023-12-04 17:27 UTC
Labels: External, Weekly

**Comment by s77rt** [comment] 2023-12-11 10:53
This was closed without fixing the other linked issue https://github.com/Expensify/App/issues/26941
