### ISSUE TITLE
[HOLD for payment 2023-07-14] [$1000] Web - Country field does not autofill for certain addresses.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21520] opened 2023-06-25 15:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Open your profile.
2.Click on "Settings".
3.Click on "Personal Details".
4.Click on "Home Address".
5.Notice that when selecting an address from the options menu, the country field is not automatically filled.
## Expected Result:
The Country field should be auto filled, similar to when the user selects other addresses.
## Actual Result:
The Country field is not auto filled for certain addresses.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/93cce2c0-8f32-41f4-a7f3-450f8bab7905

https://github.com/Expensify/App/assets/43996225/490d72a4-0258-4855-b857-f17eeacafda7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687237650003769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d5d43c97434907d</li>
        <li>Upwork Job ID: 1673420349109485568</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-26 19:57
I can reproduce this. But it seems like it only happens when you type in the specific address `bangladesh border road` into the search box and then select it. I can't get this to not work for any other address (and I tried a bunch). 

Part of me wonders if this has something to do with the data we're getting from the API for this address, which prevents auto-filling? Regardless, it is reproducible, so we should fix (as long as this isn't an issue with the address API that we have no control over).

**Comment by nishancx** [comment] 2023-06-27 03:36
@joekaufmanexpensify  This seems like address API response data issue. Adresses are fetched from `/place/autocomplete/json`, the response from API contains an array `address_components` which contains address auto fll data.
First recommendation for `bangladesh` only contains addressLine1 thats why counry isn't being autofilled. Maybe some entries in adress json need to be updated.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 17:45
@nishancx Thanks for confirming! Is that something we can update on our end. Or just an issue related to the API we use (over which we have no control).

**Comment by crystal6117** [comment] 2023-06-27 21:39
Hello, @joekaufmanexpensify. I think this is an issue in google place data. So we have to find a solution not to show such addresses in google place autocomplete component.

**Comment by joekaufmanexpensify** [comment] 2023-06-27 21:41
Hm, got it. If this is an issue with the google API data, then I'm not sure we should do anything. I think we'd rather have an address not auto-complete, than remove an address that exists from the search results. Curious if you agree @mollfpr ?

**Comment by mollfpr** [comment] 2023-06-28 02:01
@joekaufmanexpensify The response from Google API only returns the type of `route` we use for address line 1, but we still can get the country-long name from the autocomplete data.

https://github.com/Expensify/App/blob/52a18912a42567fdc25cb6c64676516959a16781/src/components/AddressSearch/index.js#L143-L145

![Screenshot 2023-06-28 at 08 51 42](https://github.com/Expensify/App/assets/25520267/f2a5cf3e-e6ef-40d4-bb8c-a63335686837)

We can get the country name from the autocomplete fallback and get the country's short-name by searching it on `CONST.ALL_COUNTRIES`.

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:15
@mollfpr Got it, thanks! In that case, it sounds like this is something we can fix. Is that right? If so, then let's keep this open for proposals.

**Comment by nishancx** [comment] 2023-06-29 01:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Country field does not auto-fill for certain addresses (eg. Bangladesh Border Road)

### What is the root cause of that problem?
This seems like address API response data issue. Addresses are fetched from `/place/autocomplete/json`, the response contains an array `address_components` which contains address auto-fill data.
First recommendation for Bangladesh only contains `addressLine1` that's why country isn't being auto-filled.

### What changes do you think we should make in order to solve the problem?
We are fetching country with `getAddressComponents()`. 
And we are already fetching `state` and `city` with `getPlaceAutocompleteTerms()` and it also returns `country` which we can use as a fallback.
`country` fetched with `getPlaceAutocompleteTerms()` contains full name of country, which needs to be converted to country code in order to perform checks later down in the code. This conversion can be done by using lodash to `findKey` from `CONST.ALL_COUNTRIES`.
Now that we have fallback for country code fetched from `getPlaceAutocompleteTerms()`, it can be used as a fallback for `country` fetched from `getAddressComponents()` to solve this issue.

**Comment by mollfpr** [comment] 2023-06-29 02:26
Thanks for the proposal @nishancx 

It is similar to what I have in mind, and the [proposal](https://github.com/Expensify/App/issues/21520#issuecomment-1612312837) looks good!

🎀 👀 🎀 C+ reviewed!

**Comment by francoisl** [comment] 2023-06-29 04:52
Looks good to me!

**Comment by nishancx** [comment] 2023-06-29 05:04
Offer accepted.
Ill try to make a PR within 24 hours.

**Comment by nishancx** [comment] 2023-06-29 06:57
I have finished everything except testing with high traffic account, I have requested for my account to be converted to high traffic account in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q) and I'm waiting for the request to go through.

**Comment by nishancx** [comment] 2023-06-29 07:12
I have made a draft [PR](https://github.com/Expensify/App/pull/21853), I'll update it as soon as I have a high traffic account to test with.

**Comment by nishancx** [comment] 2023-06-29 12:08
I have tested changes with high traffic account and it works as expected, the [PR](https://github.com/Expensify/App/pull/21853) is ready for review.

**Comment by usmantariq96** [comment] 2023-07-04 05:58
@kavimuru please update the "Issue reported by:" with my GH Handle 
Thanks

**Comment by joekaufmanexpensify** [comment] 2023-07-07 16:54
Not overdue. PR is in review.

**Comment by nishancx** [comment] 2023-07-07 20:35
> Not overdue. PR is in review.

The [PR](https://github.com/Expensify/App/pull/21853#issuecomment-1625214651) is already deployed to production.

**Comment by francoisl** [comment] 2023-07-07 23:55
Ah, the automation didn't work because the pull request description doesn't follow the proper format.

<img width="794" alt="image" src="https://github.com/Expensify/App/assets/2229301/edad7e7f-a85d-4854-8b03-3f1c6256e4dd">


I'm going to remove the `Reviewing` label like it was supposed to do after the production deploy. For the next PRs, make sure to use the format `$ https://github.com/Expensify/App/issues/XXXX` 🙂

**Comment by nishancx** [comment] 2023-07-08 01:31
Sure @francoisl, thank you.

**Comment by nishancx** [comment] 2023-07-08 02:00
When should I submit work in upwork right now or after 7 days regression  period?

Also, if no regressions happen, this should be eligible for bonus right? Since PR got merged within 3 days, 23 hours with weekend in between and without counting weekend it got merded within 1 day, 23 hours of accepting proposal.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 13:50
Yep, we'll send an offer in upwork soon. We'll issue payment on 2023-07-14. And then this does qualify for a speed bonus. That will be added when we issue payment!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 20:20
Manually creating BZ checklist, since the automation did not work here: 

BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@mollfpr ] The PR that introduced the bug has been identified. Link to the PR: 
 [@mollfpr ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: 
 [@mollfpr ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: 
 [@mollfpr ] Determine if we should create a regression test for this bug.
 [@mollfpr ] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 @joekaufmanexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by joekaufmanexpensify** [comment] 2023-07-11 20:21
@mollfpr could you please complete your portion of the BZ checklist when you have a sec? Thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 20:26
@mollfpr offer sent for $1,000 (We'll issue $500 as bonus during payment)!

**Comment by joekaufmanexpensify** [comment] 2023-07-11 20:27
@usmantariq96 offer sent for $250!

**Comment by usmantariq96** [comment] 2023-07-12 03:11
@joekaufmanexpensify  offer accepted.
Thanks

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:11
Bumped BZ checklist in Slack. On track to issue payment tomorrow!

**Comment by mollfpr** [comment] 2023-07-14 04:24
>  [@mollfpr ] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr ] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

No offending PR is causing the issue. We were unaware there was a result from Google API that doesn't have a country value. So this is an improvement we made to handle that.

>  [@mollfpr ] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This is a one-time bug, so the regression test should be enough.

>  [@mollfpr ] Determine if we should create a regression test for this bug.
 [@mollfpr ] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Sign in to the App
2. Go to the Home Address page from Settings > Profile > Personal Details > Home Address
3. Enter Bangladesh in the Address line 1 field
4. Select an option (In this case, Bangladesh Border Road , which was causing the issue)
5. Verify that the Country field is filled with Bangladesh
6. 👍 or 👎

**Comment by francoisl** [comment] 2023-07-14 04:29
👍 for the regression steps (and the rest too)

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:07
Great, thanks! I updated the BZ checklist with that information. I also created a regression test issue and linked it above.

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:12
@nishancx $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:13
@mollfpr $1,500 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:13
@usmantariq96 $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:14
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2023-07-14 19:14
Bug is fixed, BZ checklist complete, and all payment issued. Closing as this is all set. Thank you everyone!

**Closed by joekaufmanexpensify** 2023-07-14 19:14 UTC
Labels: External, Daily, Awaiting Payment, Bug
