### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] Categories - Error in Empty Category Not Dismissed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52765] opened 2024-11-19 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+tw4355353333@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to Settings > Workspace > Categories.
2. Delete all categories and import a CSV file.
3. Select a field to map from the spreadsheet (e.g., Amount), enable it, and save
4. Observe the error message. Click the "Close" button to dismiss the error.

## Expected Result:
The error message should be dismissed upon clicking the "Close" button.

## Actual Result:
The error message remains displayed even after clicking the "Close" button.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/50ab8270-c0c4-4744-8cd2-e0694c6801b2

[Bug6669395_1732017654330!Bulk_Export_id_DEFAULT_CSV__1_.csv](https://github.com/user-attachments/files/17815316/Bug6669395_1732017654330.Bulk_Export_id_DEFAULT_CSV__1_.csv)
 

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021859068445047163468</li>
        <li>Upwork Job ID: 1859068445047163468</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>brunovjk | Reviewer | 105006793</li>
<li>abzokhattab | Contributor | 105006794</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by huult** [comment] 2024-11-19 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Error in Empty Category Not Dismissed

### What is the root cause of that problem?

We are unable to close this error because we can't find the category. As a result, we return early and cannot set the error to null to hide the error message.

https://github.com/Expensify/App/blob/faa48b605d708d7e8814e54fbf2b88a883c9c0c0/src/libs/actions/Policy/Category.ts#L845-L857

https://github.com/Expensify/App/blob/be6acac6f051b290d96e14353704065e4928b53a/src/components/OfflineWithFeedback.tsx#L147-L154

We can't find the category because we don't have a category name. The reason we don't have a category name is that the imported CSV does not include a name field.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we shouldn't accept a CSV containing invalid data. We should check whether the CSV includes a name field or not. If the CSV does not include a name field, we should return early and display an error message. Something like this:

```diff
// src/components/ImportSpreadsheet.tsx#L96
+    const rowTitle = data.at(0) as string[];

+    if (!rowTitle.includes(CONST.CSV_IMPORT_COLUMNS.NAME)) {
+        setUploadFileError(true, 'spreadsheet.importFailedTitle', 'spreadsheet.invalidFileMessage');
+        setIsReadingFIle(false);
+        if (fileURI && !file.uri) {
+            URL.revokeObjectURL(fileURI);
+        }
+        return;
+    }
```
## [Test branch](https://github.com/Expensify/App/compare/main...huult:App:52765-test-branch?expand=1)

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/4f62c871-dc02-40ac-96a5-2c60d2b7c3b7


</details>

**Comment by brunovjk** [comment] 2024-11-20 10:03
Reviewing proposals soon.

**Comment by brunovjk** [comment] 2024-11-20 12:23
Thank you all for the proposals.

@Nodebrute, I think your proposal alone is not enough as it doesn’t address the root cause of allowing empty categories during CSV import. @Abzokhattab, @huult, and @nkdengineer, correct me if I’m wrong, but your proposals seem similar in that they focus on updating the CSV import validation. 

With that, I think we should go with @Abzokhattab's [proposal](https://github.com/Expensify/App/issues/52765#issuecomment-2485758445), as it is the first robust solution addressing the root cause effectively while maintaining user clarity.

🎀👀🎀 C+ reviewed

**Comment by huult** [comment] 2024-11-20 12:37
@brunovjk Yes, thank you for your feedback. For my proposal, I suggest notifying the user about invalid steps during the CSV import process to enhance the user experience. Regarding the proposal you voted for, validation occurs after the import. However, since editing the data fields is not possible at that step and validation is always shown but cannot proceed, it becomes redundant.

**Comment by neil-marcellini** [comment] 2024-11-21 14:49
> Thank you all for the proposals.
> 
> @Nodebrute, I think your proposal alone is not enough as it doesn’t address the root cause of allowing empty categories during CSV import. @abzokhattab, @huult, and @nkdengineer, correct me if I’m wrong, but your proposals seem similar in that they focus on updating the CSV import validation.
> 
> With that, I think we should go with @abzokhattab's [proposal](https://github.com/Expensify/App/issues/52765#issuecomment-2485758445), as it is the first robust solution addressing the root cause effectively while maintaining user clarity.
> 
> 🎀👀🎀 C+ reviewed

I agree, it's a good proposal and resulting UX. Hiring.

**Comment by brunovjk** [comment] 2024-11-22 20:04
Hey @abzokhattab :D just checking, would you happen to have an ETA for this PR? Thanks.

**Comment by brunovjk** [comment] 2024-11-27 11:14
**Update:** PR still under review.

**Comment by brunovjk** [comment] 2024-12-06 12:35
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [x] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: Applause Internal Team

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: No PR directly introduced the bug. This happens because the current validation allows empty names in the Name column during CSV upload.

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal

### Test:


 1. Navigate to **Settings Workspace Categories** .
2. Click on the **three-dot menu**  and select **Import a Spreadsheet** .
3. Use a spreadsheet file where one column contains one or more empty cells (e.g., the attached [example file](https://github.com/user-attachments/files/17936329/Categories-2024-11-24.21_02_39.241.csv)).
4. Select the column with empty values as the **Name**  field.
5. Choose another column as the **Required**  field.
6. Click **Submit**  and verify that the following error message appears:
   `Oops! The field ("Name") contains one or more empty values. Please review and try again.`
7. Update the **Name**  field to a column that does not contain empty values and retry the process.
8. Confirm that the categories are imported successfully without any errors.

Do we agree 👍 or 👎

**Comment by kadiealexander** [comment] 2024-12-09 02:48
Test GH: https://github.com/Expensify/Expensify/issues/451500

**Comment by kadiealexander** [comment] 2024-12-09 02:49
Contributor: @abzokhattab paid $250 via Upwork ([Offer link](https://www.upwork.com/nx/wm/offer/105006794))
Reviewer: @brunovjk owed $250 via Upwork ([Offer link](https://www.upwork.com/nx/wm/offer/105006793))

**Closed** 2024-12-09 02:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
