### ISSUE TITLE
[HOLD for payment 2024-03-22] [$500] IOU - The cursor isn't centered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35435] opened 2024-01-30 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35119
## Action Performed:
1. Open app
2. Tap FAB - Request money

## Expected Result:
The cursor should be centered

## Actual Result:
The cursor isn't centered. It affects the manual IOU and custom time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/68a63a44-fe4d-4129-974d-62c643f18510

https://github.com/Expensify/App/assets/78819774/db2196c4-e6f0-4fd5-8f23-1b16663cba32

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01501e5a4487cb18d9</li>
        <li>Upwork Job ID: 1752428207590764544</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2024-01-30 20:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cursor for time selection is not centered. It's at end

### What is the root cause of that problem?
We are setting cursor position at 2, when setting state in `TimePicker`
https://github.com/Expensify/App/blob/eb031dc2ee42def13f84e47dd978992659a11a05/src/components/TimePicker/TimePicker.js#L122

### What changes do you think we should make in order to solve the problem?
We shall change it to 
```js
 const [selectionMinute, setSelectionMinute] = useState({start: 0, end: 0}); /
```

### What alternative solutions did you explore? (Optional)

**Comment by mallenexpensify** [comment] 2024-02-03 00:17
Same question as @ntdiary 

> The cursor should be centered

Hi, @lanitochka17, this means that the cursor should be vertically centered, right?

**Comment by mallenexpensify** [comment] 2024-02-06 23:23
also assigning to @lanitochka17 to help get 👀 on the above.

**Comment by mallenexpensify** [comment] 2024-02-13 23:27
@lanitochka17 👀 plz.  Also checking with QA on a process for pinging QA in GHs.

**Comment by isagoico** [comment] 2024-02-14 00:30
> > The cursor should be centered
> 
> Hi, @lanitochka17, this means that the cursor should be vertically centered, right?

To answer this question, yes, we raised this issue since the cursor is not vertically centered. This is affecting both the BNP and the time selector in setting a status. 

IOU: 
![image](https://github.com/Expensify/App/assets/44479856/3d5409ca-4b11-4971-a10c-db2c9d44f5e0)

Time selector: 
![image](https://github.com/Expensify/App/assets/44479856/c135ffae-4b30-44a9-aaa8-47c78f4db4e8)

**Comment by mallenexpensify** [comment] 2024-02-18 19:07
@dannymcclain please see screenshots above.  I was planning to close this because it's a small bug that's not directly related to a VIP or wave project.  Let me know if you disagree.

**Comment by dannymcclain** [comment] 2024-02-19 14:03
@mallenexpensify I agree we should close and `:donothing:`

**Comment by dannymcclain** [comment] 2024-02-19 17:35
It makes me a little uncomfortable to edit our font files (my main concern is other unintended consequences). Let's see if the @Expensify/design team has any other thoughts/opinions about this.

**Comment by shawnborton** [comment] 2024-02-19 18:34
Hmm I can reach out to our font foundry and get their opinion on this, but part of me thinks this is not really a "bug" and we can close. Either way, I'll send an email and cc the @Expensify/design team.

**Comment by dannymcclain** [comment] 2024-02-19 19:32
Thanks @shawnborton! It's interesting too because it looks perfectly centered on Mac web/desktop. So it can't be fully inherent in the font file, ya know?

**Comment by shawnborton** [comment] 2024-02-19 20:45
This is what our foundry said:

> In the screenshot you attached there seems to be something strange going on with the vertical alignment of the text. The colon is low or the numbers are high.
>Perhaps correcting this will help - in the font the colon is correctly positioned with the bottom dot aligned on the baseline, so this must be something in the web code.

>Also, vertical metrics in the font are set to accommodate (as best possible) all the glyphs, so the cursor may look low when next to 123ABC, but high when next to gjpy.

**Comment by shawnborton** [comment] 2024-02-19 20:45
Is there something we're doing with line heights or something else in the app? Sounds like the issue is NOT our fonts, phew!

**Comment by mallenexpensify** [comment] 2024-02-21 01:09
Bumping to weekly, I wanna see if we get any feedback on 
> Is there something we're doing with line heights or something else in the app?

Posted about it [in #expensify-open-source ](https://expensify.slack.com/archives/C01GTK53T8Q/p1708477713832529)

**Comment by mallenexpensify** [comment] 2024-02-28 00:03
Coming from [this #contributor-plus Slack chat. ](https://expensify.slack.com/archives/C02NK2DQWUX/p1709024519896479)

This might be related to
- https://github.com/facebook/react-native/issues/35951#issuecomment-1966050548

**Comment by mallenexpensify** [comment] 2024-02-28 02:29
^ Doesn't look like it's related.  
So now we're back to... 
1. Close
2. Drop in the #vip-vsb room to see about about adding to that project. 

@dannymcclain what do you think?

**Comment by dannymcclain** [comment] 2024-02-28 14:48
Honestly I'm pretty tempted to just close it. @Expensify/design what do you all think? Is it worth investing time to investigate further right now?

**Comment by shawnborton** [comment] 2024-02-28 15:10
I'd say we just close it. We confirmed with our font foundry that there is no issue with the vertical metrics.

**Comment by shawnborton** [comment] 2024-02-28 19:36
Hmm what exactly are the differences between OS/2 and Hhea and usWin?

**Comment by mallenexpensify** [comment] 2024-03-04 18:32
@tienifr , thanks for all the details above. 
@shawnborton , based on the above, do you still recommend closing this issue?

**Comment by shawnborton** [comment] 2024-03-04 18:38
I'll take this new information and reach out to our foundry and see if they have any comments. Will report back!

**Comment by shawnborton** [comment] 2024-03-05 14:00
Reached out, will report back when I hear a response.

**Comment by shawnborton** [comment] 2024-03-06 12:45
Okay, here is an updated set of font files to try: [ExpensifyNewKansasMedium.zip](https://github.com/Expensify/App/files/14510026/ExpensifyNewKansasMedium.zip)

@tienifr let me know how those work!

**Comment by shawnborton** [comment] 2024-03-06 15:53
Wonderful!

**Comment by dannymcclain** [comment] 2024-03-06 16:10
@tienifr thanks for sticking with it and pushing for a resolution! Also thank you @shawnborton for reaching out to the type foundry! `:extreme-teamwork:`

**Comment by mallenexpensify** [comment] 2024-03-07 16:33
Thanks everyone! 
I need to add this to a project, I want to raise a question in the #design room beforehand to see which Wave/VIP design issues like this should be added to.

**Comment by chiragsalian** [comment] 2024-03-07 19:14
Proposal LGTM, feel free to create a PR @tienifr.

**Comment by shawnborton** [comment] 2024-03-08 13:38
Are you sure we need the .woff file though? I feel like it's becoming more standard to just use a .woff2. Either way, I can ask for it.

**Comment by shawnborton** [comment] 2024-03-11 13:58
Okay, I have the .woff files but our type foundry confirmed my thinking that these aren't really used anymore... are you sure we need to implement them? 

Either way, here it is: [ENK_Medium_Woff.zip](https://github.com/Expensify/App/files/14559671/ENK_Medium_Woff.zip)

**Comment by mallenexpensify** [comment] 2024-03-27 02:31
@ntdiary @tienifr can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~014cdc2015b019d9f8

@ntdiary , please complete the BZ checklist above too.

**Comment by mallenexpensify** [comment] 2024-03-29 22:27
Contributor: @tienifr paid $500 via Upwork
Contributor+: @ntdiary paid $500 via Upwork. 

@ntdiary I created the TestRail GH because QA doesn't monthly runs for design and edge case issues and they _might_ want to do one for this.  I prefer to err on the side of letting QA make the decision.

**Closed by mallenexpensify** 2024-03-29 22:27 UTC
Labels: External, Engineering, Daily, Design, Awaiting Payment, Bug
