### ISSUE TITLE
[HOLD #20473] Web- Chat - No Concierge tooltip in staging public room

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20751] opened 2023-06-14 13:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome
2. Create a new room in public mode
3. Copy the room URL and paste it on a new window
4. Hover over the Concierge avatar (present at the side of the message)
5. Notice that tooltip is not present in the public room on staging
6. Follow the same steps on production and notice the tooltip is present

## Expected Result:
Concierge tooltip should be present in staging public room also

## Actual Result:
No Concierge tooltip in staging public room

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.3

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/81a12a33-9473-4d37-8823-be2b13be6468

https://github.com/Expensify/App/assets/93399543/17c6c89c-94d8-4e1b-9754-cf571008edec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686744443134009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2023-06-14 14:09
This is most likely another deploy blocker that will be fixed by https://github.com/Expensify/App/pull/20473

I'd recommend making this not a blocker & putting it on hold for that PR

**Comment by mountiny** [comment] 2023-06-19 21:21
@kavimuru @kbecciv Could you please try to reproduce now?

**Comment by kavimuru** [comment] 2023-06-20 14:49
@mountiny Issue is still reproducible

https://github.com/Expensify/App/assets/43996225/9f9b8698-b8b9-4db6-8858-bd087cfd87cb

**Comment by johnmlee101** [comment] 2023-06-20 16:03
Is this still a blocker? Is it reproducible on prod?

**Comment by kavimuru** [comment] 2023-06-20 17:18
@johnmlee101 It's not a blocker. I am able to reproduce in production too.

**Comment by johnmlee101** [comment] 2023-06-20 17:29
@mountiny should I go ahead and open as a bug then?

**Comment by mountiny** [comment] 2023-06-20 19:09
@johnmlee101 Probably, I am honestly not sure with all the public rooms and whisper considerations. Could we maybe check with Rocio in case this is expected for whisper in public room?

**Comment by johnmlee101** [comment] 2023-06-20 19:31
Rocio said wait til after the auth deploy since they'll be known users soon, so we'll see if it fixes it

**Comment by johnmlee101** [comment] 2023-06-26 18:21
@kavimuru is this still reproducible?

**Comment by priya-zha** [comment] 2023-06-27 17:06
@kavimuru @johnmlee101 It's not reproducible today. Tooltip is shown perfectly.

**Comment by johnmlee101** [comment] 2023-06-27 17:55
https://github.com/Expensify/Auth/pull/8141 This fix was created after. Let's pay the reporting bonus. Whoever is assigned to bug-zero, please pay out the reporter and we'll close this out immediate since its fixed.

**Comment by bfitzexpensify** [comment] 2023-06-28 08:36
@priya-zha offer sent for reporting.

**Comment by priya-zha** [comment] 2023-06-28 08:45
Accepted. Thanks.

**Comment by bfitzexpensify** [comment] 2023-06-28 09:17
Contract paid out and ended. Seems we're good to close this out.

**Closed by bfitzexpensify** 2023-06-28 09:17 UTC
Labels: Engineering, Daily, Bug
