### ISSUE TITLE
Search - Search Icon on LHN doesn't work properly when enter key

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51021] opened 2024-10-17 14:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** testpayment935@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Click on search icon on LHN
3. Search "you" and press enter

## Expected Result:
Search works properly and navigate to the your chat

## Actual Result:
Search Icon is not navigating to the user rather show "Noting to show" page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/4a020ee1-2306-4903-ac99-0313d82af542

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-10-17 14:05
Video in Production: 

https://github.com/user-attachments/assets/f8380d2f-409f-4efd-8df1-28826998f73a

**Comment by AndrewGable** [comment] 2024-10-17 15:09
cc @Kicu @luacmartins Seems to be a regression from https://github.com/Expensify/App/pull/49984

**Comment by luacmartins** [comment] 2024-10-17 15:47
This seems like the expected behavior to me. After typing `you` the first item in the search router list is the search for the keyword `you`. Once the user presses enter, we then navigate the user to the search results page with a search for the keyword `you`. I think we can close this.

**Closed** 2024-10-17 15:47 UTC
Labels: Engineering, Hourly
