### ISSUE TITLE
[$1000] Attachments in chat are overlapping with user name padding bottom (normal text chat are fine)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14214] opened 2023-01-10 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report with attachment
3. Inspect and check bottom padding for user name over a text and over an attachment

## Expected Result:
Attachment should be equally spaced from user name as the text chat.

## Actual Result:
Attachment overlaps with padding-bottom of user name.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.52-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
![image (9)](https://user-images.githubusercontent.com/43996225/211678960-80533cc8-1447-4eeb-a730-e15cbf10b069.png)
![image (8)](https://user-images.githubusercontent.com/43996225/211678964-6718fafc-7347-481b-ab67-29a54b8acf4f.png)
![image (7)](https://user-images.githubusercontent.com/43996225/211678966-92c8a287-1a85-4acf-bf50-bc72f3adcf63.png)
<img width="960" alt="Screenshot (144)" src="https://user-images.githubusercontent.com/43996225/211679046-6ae86ba5-7b3c-46b3-ad4c-c36ae7e35507.png">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Dhanashree-Sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673358852271389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01671f6ce82c5cfea2</li>
        <li>Upwork Job ID: 1612948354743050240</li>
        <li>Last Price Increase: 2023-01-10</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-01-10 23:04
@dhairyasenjaliya it looks like you already investigated this. Wanna send a proposal?

**Comment by priyeshshah11** [comment] 2023-01-11 00:39
# Proposal

## Problem
There is a negative margin being applied to the chatItemMessage style

## Solution 

Remove negative margin-top and potentially remove the negative margin-bottom too

https://github.com/Expensify/App/blob/ea6c52c1686e4aa5405c44bde7b29551e67bfd7d/src/styles/styles.js#L1348

**Comment by Pujan92** [comment] 2023-01-11 00:48
**Proposal**

I think the negative top and bottom margin is set to display the grouped messages nearby. Removing that is causing more distance between grouped messages.

<img width="819" alt="Screenshot 2023-01-11 at 6 12 58 AM" src="https://user-images.githubusercontent.com/14358475/211691854-38e5dece-f05b-48e1-9649-c8ea8c2af8dc.png">

We can adjust the vertical padding of `chatItem` to cover both cases.

<img width="769" alt="Screenshot 2023-01-11 at 6 17 26 AM" src="https://user-images.githubusercontent.com/14358475/211692189-2a7ee795-6f7b-48ed-b7c8-c324ca4a6689.png">

**Comment by dhanashree-sawant** [comment] 2023-01-11 04:41
**Proposal**

Rather than changing chat item style which will affect all the chat types, we can add a condtion to ReportActionItemMessage to check whether the message is an Attachment or not and if it is, add paddingTop:2 to it to compensate for marginTop: -2

**Code Changes**

```
src/pages/home/report/ReportActionItemMessage.js

const ReportActionItemMessage = props => (
-    <View style={[styles.chatItemMessage, ...props.style]}>
+    <View style={[styles.chatItemMessage,props.action.isAttachment ? style.chatItemMessageAttachment: null, ...props.style]}>
         {_.map(_.compact(props.action.previousMessage || props.action.message), (fragment, index) => (
                <ReportActionItemFragment
                                key={`actionFragment-${props.action.reportActionID}-${index}`}
                                fragment={fragment}
                                isAttachment={props.action.isAttachment}
                                attachmentInfo={props.action.attachmentInfo}
                                source={lodashGet(props.action, 'originalMessage.source')}
                                loading={props.action.isLoading}
                                style={props.style}
                            />
        ))}
    </View>
);
```

```
src/styles/styles.js


    chatItemMessage: {
        color: themeColors.text,
        fontSize: variables.fontSizeNormal,
        fontFamily: fontFamily.EXP_NEUE,
        lineHeight: variables.lineHeightXLarge,
        marginTop: -2,
        marginBottom: -2,
        maxWidth: '100%',
        cursor: 'auto',
        ...whiteSpace.preWrap,
        ...wordBreak.breakWord,
    },

+   chatItemMessageAttachment: {
+       paddingTop: 2,
+   },
```

**Comment by Pujan92** [comment] 2023-01-11 05:09
@dhanashree-sawant I think we should avoid negative margins here for all elements as it does overlap.

<img width="1057" alt="Screenshot 2023-01-11 at 10 39 04 AM" src="https://user-images.githubusercontent.com/14358475/211722558-8fc79385-b412-4c7a-82bd-6963ac343ab5.png">

**Comment by priyeshshah11** [comment] 2023-01-11 11:30
@Pujan92 your solution would decrease the space between all messages right? If that's the case then it doesn't really show any difference in the gap between single & grouped messages.

**Comment by Pujan92** [comment] 2023-01-11 11:50
> @Pujan92 your solution would decrease the space between all messages right? If that's the case then it doesn't really show any difference in the gap between single & grouped messages.

@priyeshshah11 It decreases the vertical padding to compensate negative margin, and the difference in the gap will be reduced but currently also it is uninformed and irrelevant of single or grouped messages as `chatItem` is the common class provided for all the items.

**Comment by priyeshshah11** [comment] 2023-01-11 11:54
> > @Pujan92 your solution would decrease the space between all messages right? If that's the case then it doesn't really show any difference in the gap between single & grouped messages.
> 
> @priyeshshah11 It decreases the vertical padding to compensate negative margin, and the difference in the gap will be reduced but currently also it is uninformed and irrelevant of single or grouped messages as `chatItem` is the common class provided for all the items.

I believe negative margins are used to depict a difference between a single message & a grouped message, thus decreasing the vertical padding doesn't keep the same effect, it just reduces the vertical spacing for all messages.

**Comment by Pujan92** [comment] 2023-01-11 12:10
Just to show why padding decrease requires with the removal of the negative margin

**Current SS** 

<img width="524" alt="Screenshot 2023-01-11 at 5 31 43 PM" src="https://user-images.githubusercontent.com/14358475/211802205-cab33ee9-825d-4b3e-aeec-41c8b155fbc5.png">

**SS after removing negative margin only(makes more space between messages)**

<img width="523" alt="Screenshot 2023-01-11 at 5 31 06 PM" src="https://user-images.githubusercontent.com/14358475/211802404-69fe90f7-f059-4b61-9261-07c0d4211cdf.png">

**SS after removing negative margin + padding decrease**

<img width="523" alt="Screenshot 2023-01-11 at 5 32 22 PM" src="https://user-images.githubusercontent.com/14358475/211802637-55efc588-cd5c-49ce-909f-7ea84bec98e0.png">

**Comment by sobitneupane** [comment] 2023-01-11 12:13
> I think we should avoid negative margins here for all elements as it does overlap.

I agree with @Pujan92 https://github.com/Expensify/App/issues/14214#issuecomment-1378248277. Not only attachments, text messages are also overlapping with displayname.

Since it involves change in UI, I believe we should take suggestion from Design Team first.

cc: @luacmartins

**Comment by priyeshshah11** [comment] 2023-01-11 12:17
@Pujan92 Thanks for the SS, however it also reduces the space between two single messages, let's see if the design team is ok with that 👍

**Comment by luacmartins** [comment] 2023-01-11 19:12
@shawnborton do you have any preference here? [This proposal](https://github.com/Expensify/App/issues/14214#issuecomment-1378089650)seems to be the best one so far.

**Comment by shawnborton** [comment] 2023-01-11 20:30
Hmm this is an interesting one. I think we did this to make things perfectly aligned so that when you have a simple message, you have an avatar that is 40px tall, and then a sender/timestamp + message that is also 40px tall. 

So to undo the negative margin changes from the text, we'd have to address some things in the sender/timestamp area as well. 

For the sender/timestamp area, I think we can do a couple things to make sure that stays at 20px tall:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/2319350/211910700-044ec129-7741-4372-b418-57188405b9a0.png">

Remove the bottom 4px padding from the sender name:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/2319350/211910885-7e01a759-027f-476d-8067-9e9351e06f63.png">

Remove the height from the timestamp, and give it a lineHeight of 16:
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/2319350/211910983-7e707215-3bae-4e9a-a87e-177bfde2b05f.png">


Use `align-items: baseline` for the sender + timestamp:
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/2319350/211911066-d7f3517f-6a49-4116-8904-9845eda750d9.png">


Then we can remove the negative margin for the message: 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/2319350/211911160-1eff055c-c25a-4d3a-affd-b80f03d64916.png">

And everything is still 40px tall!
<img width="276" alt="image" src="https://user-images.githubusercontent.com/2319350/211911240-f35aee6f-061d-404c-af2b-60574f996646.png">

**Comment by situchan** [comment] 2023-01-11 21:02
### **Proposal**

```diff
    chatItemMessageHeader: {
-       alignItems: 'center',
+       alignItems: 'baseline',
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'nowrap',
    },

    chatItemMessageHeaderSender: {
        color: themeColors.heading,
        fontFamily: fontFamily.EXP_NEUE_BOLD,
        fontSize: variables.fontSizeNormal,
        fontWeight: fontWeightBold,
        lineHeight: variables.lineHeightXLarge,
-       paddingBottom: 4,
        ...wordBreak.breakWord,
    },

    chatItemMessageHeaderTimestamp: {
        flexShrink: 0,
        color: themeColors.textSupporting,
        fontSize: variables.fontSizeSmall,
-       height: 24,
-       lineHeight: variables.lineHeightXLarge,
+       lineHeight: variables.lineHeightNormal,
    },

    chatItemMessage: {
        color: themeColors.text,
        fontSize: variables.fontSizeNormal,
        fontFamily: fontFamily.EXP_NEUE,
        lineHeight: variables.lineHeightXLarge,
-       marginTop: -2,
-       marginBottom: -2,
        maxWidth: '100%',
        cursor: 'auto',
        ...whiteSpace.preWrap,
        ...wordBreak.breakWord,
    },
```

**Comment by shawnborton** [comment] 2023-01-12 08:37
Oh interesting, why would the About page be using a style called `chatItemMessageHeaderTimestamp`? We should just have a global style for this kind of micro supporting text. But I agree, we can just add some bottom margin or padding if we think it's too close to the bottom.

**Comment by sobitneupane** [comment] 2023-01-12 08:58
@shawnborton With [these changes](https://github.com/Expensify/App/issues/14214#issuecomment-1379448383), attachment appear too close to the sender name.

With the change:
<img width="645" alt="Screenshot 2023-01-12 at 14 41 14" src="https://user-images.githubusercontent.com/25876548/212022396-de77d1e9-fcd0-489b-8e7e-2029dc05025b.png">

Existing:
<img width="645" alt="Screenshot 2023-01-12 at 14 41 24" src="https://user-images.githubusercontent.com/25876548/212022416-ff036409-4244-47db-bdbb-fb248782ee1f.png">

**Comment by shawnborton** [comment] 2023-01-12 09:03
Hmm then maybe we should give attachments some vertical padding/margin? Or n the very least, if the attachment comes right after the sender/timestamp, add some top margin?

I'm starting to wonder if this one is even worth changing, it's such a small technicality at this point.

**Comment by sobitneupane** [comment] 2023-01-12 09:08
> I'm starting to wonder if this one is even worth changing, it's such a small technicality at this point.

Agreed. Same thoughts.

**Comment by shawnborton** [comment] 2023-01-12 09:11
I think I could get down with what @dhairyasenjaliya proposed.

**Comment by priyeshshah11** [comment] 2023-01-12 09:19
I think removing the negative top margin should be enough to fix this & use `align-items: baseline;` in `chatItemMessageHeader` to align the sender name & timestamp

**Comment by shawnborton** [comment] 2023-01-12 09:21
I don't think we should remove the negative margin from the normal text messages though.

And changing to baseline isn't quite enough, we also need to modify heights. I say we handle the sender/timestamp thing in a separate issue and not touch it here.

**Comment by priyeshshah11** [comment] 2023-01-12 09:23
> I don't think we should remove the negative margin from the normal text messages though.

is this for group messages to appear close to each other?

**Comment by sobitneupane** [comment] 2023-01-12 09:27
[The proposal](https://github.com/Expensify/App/issues/14214#issuecomment-1378275612) does not completely solves the issue. It removes overlapping issue only for html elements(like attachments) not for normal text messages (https://github.com/Expensify/App/issues/14214#issuecomment-1378248277).

And also with the change, anchor text will also have 4px marginTop. So, the message containing link will appear 4px below the sender's name than the normal case.

**Comment by priyeshshah11** [comment] 2023-01-12 09:27
> I think it's because the sender/timestmap is 24px tall, and a message is 20px tall, and then if you add the negative margin to the message, you get 24px + 16px which is a perfect 40px to match the avatar to the left.

In that case changing the line height to 16 will compensate for removing the negative margin, right?

**Comment by shawnborton** [comment] 2023-01-12 09:33
Hmm actually, I'm just going to go ahead and close this and say this is not a bug. The bug title says that attachments overlap but text chats are fine, but that's not actually true - text chats also have the same overlap:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/2319350/212030321-3b1b0907-516f-4639-a2f9-dcd284f6b922.png">


So I think if anything is a bug, it's the fact that the sender/timestamp is not aligned super well and could be 20px tall instead of 24px. That would be a totally separate bug though.

**Closed by shawnborton** 2023-01-12 09:33 UTC
Labels: External, Daily, Help Wanted, Bug
