### ISSUE TITLE
LHN - Missing space between user and to in "invited 1 userto #room" when inviting user to room

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47248] opened 2024-08-12 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Click on the room header > Members.
4. Invite a member to the room.
5. Go to #admins.

## Expected Result:
#admins report preview in LHN will display "invited 1 user to #room".

## Actual Result:
#admins report preview in LHN displays "invited 1 userto #room".

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5d2cc8ea-f05d-46dc-a3cc-b71fc54f3d20

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-08-12 16:58
We think that this bug might be related to #vip-vsb

**Comment by etCoderDysto** [comment] 2024-08-12 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Missing space between user and to in "invited 1 userto #room"
### What is the root cause of that problem?
`formatReportLastMessageText` trims the space before `preposition` and return `${preposition} ${roomName}`
https://github.com/Expensify/App/blob/9aa78ffb88c9519327e096430d9fe8111450d248/src/libs/SidebarUtils.ts#L418
### What changes do you think we should make in order to solve the problem?
We should add space before the value returned from `formatReportLastMessageText`
```
result.alternateText += ` ${ReportUtils.formatReportLastMessageText(`${preposition} ${roomName}`)}`;
```
Note: we can check for all instances of `ReportUtils.formatReportLastMessageText` to see if it trimmed a space before a message on other places, and apply the same change.

### What alternative solutions did you explore? (Optional)

**Comment by blimpich** [comment] 2024-08-12 17:17
Shouldn't be blocking backend deploys, and I'd also say this probably isn't a frontend deploy either. It doesn't look good but I don't think its a blocker.

**Comment by blimpich** [comment] 2024-08-12 17:55
@etCoderDysto thank you for pointing out the problematic code 🙏. In the future when proposing a solution to an issue marked as a `DeployBlocker` please make sure to link to the PR that introduced the issue, which in this case would be [this PR](https://github.com/Expensify/App/pull/46976/files).

Generally for deploy blockers we would assign this to the contributor who caused the regression in the first place. But we might assign to a contributor who makes a proposal if (A) the contributor who caused the regression isn't available to work on it or isn't easily reachable via Slack (B) we don't want to revert the original PR and (C) the issue is truly urgent and the contributor who proposed a fix is able to work on it quickly.

For this case I think A & B are true, but I don't think C is true. I don't consider this urgent. So I'm going to assign the original contributor and C+ to work on this as follow up.

cc: @daledah @mollfpr

**Comment by blimpich** [comment] 2024-08-12 17:59
@daledah for some reason GH won't let me assign you to this PR, but could you please raise a PR to fix this issue since it was caused by [the PR](https://github.com/Expensify/App/pull/46976) you raised last week?

Sidenote: what is your Slack username? I tried to find you in Slack to ask you about this issue but couldn't find you.

**Comment by etCoderDysto** [comment] 2024-08-12 18:06
> In the future when proposing a solution to an issue marked as a `DeployBlocker` please make sure to link to the PR that introduced the issue. 

Sorry, I will do that for the future.

**Comment by sakluger** [comment] 2024-08-24 02:00
FYI - I'll be OOO for the next week, back on Aug 30. @blimpich hopefully I won't be needed between now and then - if so, you can assign another BZ member by removing me, then removing and re-adding the Bug label.

**Comment by greg-schroeder** [comment] 2024-08-27 05:49
This seems to have been deployed to prod on 8/19 - regression period is through today

**Comment by greg-schroeder** [comment] 2024-08-27 05:51
Seems this was a regression fix by original PR authors (@daledah and @mollfpr) so no payment is due here. Payment will be handled in original issue https://github.com/Expensify/App/issues/46190

**Closed by greg-schroeder** 2024-08-27 05:51 UTC
Labels: Reviewing, Engineering, Daily, Bug
