### ISSUE TITLE
[$500] Chat - Workspace's name is shown as unavailable when opening the notification from admin room

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31368] opened 2023-11-15 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.99-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Log in with a new account
3. Kill the app or leave the app in the background
4. Log in with the same account to OD on web on the secondary device
5. Create a Collect policy on OD
6. Open the notification from the admins' room on the main device

## Expected Result:
The correct workspace name is displayed in both the room header and LHN

## Actual Result:
"Unavailable" is displayed in both the room header and LHN while room is loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7a0705f-af6b-4aa4-8c80-08ea124fb9fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f3ce00bd2206fbaf</li>
        <li>Upwork Job ID: 1724790205605269504</li>
        <li>Last Price Increase: 2023-11-22</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-11-19 20:07
No proposals yet

**Comment by newtome8888** [comment] 2023-11-20 16:01
can't reproduce it

**Comment by johncschuster** [comment] 2023-11-22 22:01
@lanitochka17 can you try reproducing this behavior again? If you're able to, can you please clarify the reproduction steps?

Thanks!

**Comment by johncschuster** [comment] 2023-11-29 01:09
Looks like this is no longer reproducible! Closing! 💃

**Closed by johncschuster** 2023-11-29 01:09 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
