### ISSUE TITLE
[HOLD for payment 2023-10-12] [HOLD for payment 2023-10-10] [$500] Web - Green drag and drop area does not show in full screen

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28014] opened 2023-09-22 13:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB icon and select Request money
2. Go to scan tab
3. Upload receipt and request money
4. Go to transaction thread
5. Click on image
6. Click on three dots and select replace
7. Try to drop image

## Expected Result:
green drag and drop area should show in full screen same as scan tab

## Actual Result:
 drag and drop area does not cover full screen

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b0fdedb2-2603-4bab-adb3-fccfc57ad619

https://github.com/Expensify/App/assets/93399543/0e38e084-cdb1-4f14-8e0a-df8ea37fd2fb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695210899596209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a657764a62d532c</li>
        <li>Upwork Job ID: 1705215482777022464</li>
        <li>Last Price Increase: 2023-09-22</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 26876728</li>
<li>gadhiyamanan | Contributor | 26876729</li>
<li>gadhiyamanan | Reporter | 26876731</li>
</ul></li>
    </ul>
</details>

**Comment by ahmedGaber93** [comment] 2023-09-22 13:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
green drag and drop area does not show in full screen in `EditRequestReceiptPage.js` but it shown in `MoneyRequestSelectorPage.js`
### What is the root cause of that problem?
the root cause is the `HeaderWithBackButton` is not a child of `DragAndDropProvider`.
https://github.com/Expensify/App/blob/94c07eabcf8f0c927b759956f24a72c28710186e/src/pages/EditRequestReceiptPage.js#L35-L44
### What changes do you think we should make in order to solve the problem?
we need to move `HeaderWithBackButton` inside `DragAndDropProvider`


### What alternative solutions did you explore? (Optional)
N/A

**Comment by c3024** [comment] 2023-09-22 13:40
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Drag and drop highlighting when replacing the receipt from 3 dot menu is different from the drag and drop highlighting in request money scan page.
### What is the root cause of that problem?
We are wrapping only the `ReceiptSelector` here with `DragAndDropProvider`
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/EditRequestReceiptPage.js#L35-L44
unlike here
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/iou/MoneyRequestSelectorPage.js#L88-L93
that wraps the header as well.
### What changes do you think we should make in order to solve the problem?
We wrap the header as well like this in `EditRequestReceiptPage`
```js
            <DragAndDropProvider>
                <HeaderWithBackButton
                    title={translate('common.receipt')}
                    onBackButtonPress={Navigation.goBack}
                />
                <ReceiptSelector
                    route={route}
                    transactionID={transactionID}
                />
            </DragAndDropProvider>
```
### What alternative solutions did you explore? (Optional)
If we don't want the header highlighting for both cases we might wrap with `DragAndDropProvider` from only here in `MoneyRequestSelectorPage`
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/iou/MoneyRequestSelectorPage.js#L97
excluding the `HeaderWithBackButton`

**Comment by gadhiyamanan** [comment] 2023-09-22 13:41
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
green drag and drop area does not show in full screen
### What is the root cause of that problem?
HeaderWithBackButton is excluded from DragAndDropProvider [here](https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/pages/EditRequestReceiptPage.js#L36C1-L45)
### What changes do you think we should make in order to solve the problem?
Add HeaderWithBackButton as child element of DragAndDropProvider in EditRequestReceiptPage.js
https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/pages/EditRequestReceiptPage.js#L36-L45
### What alternative solutions did you explore? (Optional)
N/A

**Comment by kbecciv** [comment] 2023-09-22 13:41
Proposal by: @gadhiyamanan
Slack conversation: https://expensify.slack.com/archives/C049HHMV9SM/p1695210899596209

## Proposal
### Please re-state the problem that we are trying to solve in this issue.
green drag and drop area does not show in full screen
### What is the root cause of that problem?
HeaderWithBackButton is excluded from DragAndDropProvider [here](https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/pages/EditRequestReceiptPage.js#L36C1-L45)
### What changes do you think we should make in order to solve the problem?
Add HeaderWithBackButton as child element of DragAndDropProvider in EditRequestReceiptPage.js
https://github.com/Expensify/App/blob/a240941e2a6d5143177c2ce2cf0dfc8776c9c043/src/pages/EditRequestReceiptPage.js#L36-L45
### What alternative solutions did you explore? (Optional)
N/A

**Comment by c3024** [comment] 2023-09-22 13:45
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Drag and drop highlighting when replacing the receipt from 3 dot menu is different from the drag and drop highlighting in request money scan page.
### What is the root cause of that problem?
We are wrapping only the `ReceiptSelector` here with `DragAndDropProvider`
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/EditRequestReceiptPage.js#L35-L44
unlike here
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/iou/MoneyRequestSelectorPage.js#L88-L93
that wraps the header as well.
### What changes do you think we should make in order to solve the problem?
We wrap the header as well like this in `EditRequestReceiptPage`
```js
            <DragAndDropProvider>
                <HeaderWithBackButton
                    title={translate('common.receipt')}
                    onBackButtonPress={Navigation.goBack}
                />
                <ReceiptSelector
                    route={route}
                    transactionID={transactionID}
                />
            </DragAndDropProvider>
```
### What alternative solutions did you explore? (Optional)
If we don't want the header highlighting for both cases we might wrap with `DragAndDropProvider` from only here in `MoneyRequestSelectorPage`
https://github.com/Expensify/App/blob/9ab20c588094463d86e9eb7e456b689f83cb1598/src/pages/iou/MoneyRequestSelectorPage.js#L97
excluding the `HeaderWithBackButton`

**Comment by lschurr** [comment] 2023-09-25 04:31
Bump @roryabraham - as long as we all agree, we just need to assign this one to @gadhiyamanan

**Comment by gadhiyamanan** [comment] 2023-09-26 07:59
@hoangzinh [PR](https://github.com/Expensify/App/pull/28219) is ready for review

**Comment by mountiny** [comment] 2023-10-03 14:25
@hoangzinh @gadhiyamanan Based on QA this is still not fixed in desktop, can you please confirm

**Comment by gadhiyamanan** [comment] 2023-10-03 14:26
[PR](https://github.com/Expensify/App/pull/28579) merged for desktop but didn't hit staging

**Comment by dylanexpensify** [comment] 2023-10-10 11:09
Payment summary:

- Reporter: @gadhiyamanan $50
- Contributor: @gadhiyamanan $500
- Contributor+: @hoangzinh $500

**Comment by dylanexpensify** [comment] 2023-10-10 18:38
updated @dhairyasenjaliya!

**Comment by dylanexpensify** [comment] 2023-10-16 10:26
on it!

**Comment by dylanexpensify** [comment] 2023-10-16 10:28
@hoangzinh @gadhiyamanan both of you have been paid!

**Comment by dylanexpensify** [comment] 2023-10-16 10:59
@dhairyasenjaliya done!

**Comment by dylanexpensify** [comment] 2023-10-16 11:01
offer sent @dhairyasenjaliya !

**Comment by dylanexpensify** [comment] 2023-10-16 11:02
done!

**Closed by dylanexpensify** 2023-10-16 11:02 UTC
Labels: External, Daily, Awaiting Payment, Bug
