### ISSUE TITLE
Unread notification was shown to the recipient for a direct message (DM), despite me deleting the DM that generated that unread notification.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12471] opened 2022-11-04 14:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a DM to a recipient, which will generate an unread notification for them.
2. Delete the DM you sent (which should remove the unread notification?).
3. The recipient still has an unread notification in New Expensify.

## Expected Result:
The unread notification should be removed if the corresponding DM is deleted or retracted.

## Actual Result:
the unread notification persists for the recipient, as though a new unread message awaits… but there is no unread message

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- mWeb

**Version Number:** 1.2.23-9

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 
<img width="951" alt="Screenshot (42)" src="https://user-images.githubusercontent.com/43996225/199999535-e7441ada-7d21-4366-8677-d6fd59dc6f9b.png">
<img width="960" alt="Screenshot (41)" src="https://user-images.githubusercontent.com/43996225/199999538-6643074a-7df3-4ac3-92df-401c27aea49b.png">
<img width="1203" alt="Screen Shot 2022-11-04 at 10 16 05 AM" src="https://user-images.githubusercontent.com/43996225/199999563-a2d87f0f-bf1d-4014-99a4-df0a975e00ed.png">
<img width="1183" alt="Screen Shot 2022-11-04 at 10 16 10 AM" src="https://user-images.githubusercontent.com/43996225/199999567-97b9cd8e-e0ca-4b26-98f0-a9a90d38dfa1.png">
<img width="763" alt="image (2)" src="https://user-images.githubusercontent.com/43996225/199999614-f8b7f86d-8bf5-47bc-a7ce-def6333982b6.png">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @michaelhaxhiu 

**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1667494591420219
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2022-11-06 21:25
@kavimuru - I'm on v1.1.44-5 and just tested this one. It looks like this issue doesn't exist anymore.

Can you verify on your side?

**Comment by jliexpensify** [comment] 2022-11-07 21:20
Thanks @kavimuru - apologies, I didn't realise my app was so old!

I've tested in staging (v1.2.24-3) with a colleague and this doesn't seem to be an issue anymore:

![image](https://user-images.githubusercontent.com/30815269/200417636-f13c900e-94bf-4bf4-b01d-b9216b175d30.png)

She reported not seeing the first "testing testing bug" message that I deleted, and not getting an unread notification.

Could you try on staging? Assigning this to you.

**Comment by marcaaron** [comment] 2022-11-29 23:50
Gonna close this one out as it seems not reproducible and nobody is actively assigned.

**Closed by marcaaron** 2022-11-29 23:50 UTC
Labels: Weekly, Bug
