### ISSUE TITLE
[HOLD #19363][$1000] Web - Chat - On deleting the top message in the thread, the alternate text of thread report changes to the last message of the main chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20390] opened 2023-06-07 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a chat
2. Send "A" and "B" as two individual messages in the chat
3. Hover over "B" and create a thread
4. Send "C" as a message in the thread
5. Check the LHN alternate text it will be C
6. Now delete the thread top message, which is "B"
7. Check the LHN, the alternate text will change to "A" instead of using the latest message which is "C"

## Expected Result:
The alternate text should be the latest message

## Actual Result:
he alternate text changes to the last message of the main report instead of using the last message of the thread

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/aeb49eea-1a2c-436d-b05b-bf35de659582

https://github.com/Expensify/App/assets/93399543/43cc36c7-4803-4e47-a1a0-7076c27a096a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685786003278599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0105a8834c661e3be8</li>
        <li>Upwork Job ID: 1666643708275687424</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by sophiepintoraetz** [comment] 2023-06-08 03:09
Able to reproduce!
<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/42940078/8eb374fe-076d-4978-bbf6-b540ed492810">

**Comment by dangrous** [comment] 2023-06-09 21:35
Hm yeah, this is definitely at least backend, though I think it might require some frontend updates too.

It's tricky, because "A" IS the correct `lastMessageText` for the deleted comment B in the main chat (not the thread). We'll have to figure out how to send two different sets of information to the frontend, IF the deleted message is threaded from.

For internal reference, [here's](https://github.com/Expensify/Web-Expensify/blob/8aab8fc79ec29c612a9137761a2dcd92fe3774c0/lib/ReportAPI.php#L647-L652) the code that we might want to modify, if not elsewhere.

I will start a discussion about this internally, and we can move forward from there.

**Comment by sophiepintoraetz** [comment] 2023-06-12 10:02
@anmurali - I'm headed OOO til 20 June (I'll take it back it if's still going then. At the moment, it's likely to be internal, so possibly the only payment due is for the reporter (offer is [here](https://www.upwork.com/nx/wm/offer/24986371)). Daniel will keep you updated!

**Comment by dangrous** [comment] 2023-06-12 21:16
Okay here's an update:

This behavior only happens if you delete the parent message from the thread view - if you delete the same message from the main chat, it acts as it should. Which means I think this can actually be **External** - since we can modify the call deleting the comment to act as if it's coming from the parent chat.

Let's see if we can get any proposals for this.

**Comment by dangrous** [comment] 2023-06-13 17:50
Realized I should have tagged @mananjadhav - can you check my work above? Does it only happen when deleted from the thread view?

**Comment by dangrous** [comment] 2023-06-16 20:39
Bumping [this](https://github.com/Expensify/App/issues/20390#issuecomment-1589772112) @mananjadhav - if you have a moment; I'd like to confirm that it's actually External before increasing the bounty. Thanks!

**Comment by mananjadhav** [comment] 2023-06-17 04:07
Sorry I missed. I'll check this today.

**Comment by jeet-dhandha** [comment] 2023-06-17 08:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Currently, when a user creates a thread from a message and adds more messages to it, deleting the main message of the thread causes an issue. The LHN Option view doesn't update properly and still shows the name as "(main message)" along with the last message text from the parent report thread, instead of displaying the last message text from the current thread.

### What is the root cause of that problem?
- The main issue is that LHN Option view doesn't update properly due to some caching from onyx.

### What changes do you think we should make in order to solve the problem?
1. We need to pass `parentReportID` to the `deleteReportComment` and for that we have to make few changes in below files.
<img width="942" alt="Screenshot 2023-06-17 at 2 18 03 PM" src="https://github.com/Expensify/App/assets/78416198/b74354d7-26ae-4697-8a5f-cd2fd03545db">
<img width="938" alt="Screenshot 2023-06-17 at 2 17 45 PM" src="https://github.com/Expensify/App/assets/78416198/4aaab450-2027-4365-b866-99a420a9ecfc">
<img width="935" alt="Screenshot 2023-06-17 at 2 17 34 PM" src="https://github.com/Expensify/App/assets/78416198/a02b2abc-2d34-4511-af4f-3dcd3b3603e9">

2. After passing `parentReportID` to the `deleteReportComment` will use `openReport` to update the LHN Option view for `reportID` and `parentReportID` both.
<img width="934" alt="Screenshot 2023-06-17 at 2 18 13 PM" src="https://github.com/Expensify/App/assets/78416198/236518d5-8574-424e-b148-2f9724cbd1ec">

After Fix:

https://github.com/Expensify/App/assets/78416198/1091b60c-dceb-40b5-a1bf-bba32f46202b



### What alternative solutions did you explore? (Optional)
N/A

**Comment by anmurali** [comment] 2023-06-19 22:07
>Bumping https://github.com/Expensify/App/issues/20390#issuecomment-1589772112 @mananjadhav - if you have a moment; I'd like to confirm that it's actually External before increasing the bounty. Thanks!

@mananjadhav - what are we doing here? I am also going to bump you in #expensify-contributors, so we figure this out

**Comment by anmurali** [comment] 2023-06-19 22:08
https://expensify.slack.com/archives/C02NK2DQWUX/p1687212506626499

**Comment by mananjadhav** [comment] 2023-06-20 20:19
Thanks for the bump @anmurali, apologies for the delay here. @dangrous You're right this can be resolved externally. I like @HezekielT's proposal as it is simple and fixes our use case. We're essentially going to pass the parent report ID in case it's the first message in the thread, otherwise delete from the thread. @dangrous what do you think?


@jeet-dhandha Your RCA is also correct, but the solution seems to be unnecessarily complex. Also one recommendation, avoid pasting bulk of code changes/diffs. It makes it difficult to read, and it is against the proposal guidelines. It could also lead to rejection of the proposal.

C+ reviewed 🎀👀🎀

**Comment by dangrous** [comment] 2023-06-20 21:41
@aimane-chnaif I think it's slightly different, however there's a chance that the fix in progress for #19363 might also fix this. 

What do you think, @mananjadhav, should we put this on hold for #19363 so we can see if it's still happening, and if so, take on @HezekielT's proposal (which looks good to me)?

Or can you confirm that this will not be fixed by the solution to #19363, and in which case move forward now!

Thanks!

**Comment by sophiepintoraetz** [comment] 2023-06-20 21:44
(@anmurali - thanks for looking over this! I'll take it back now)

**Comment by jeet-dhandha** [comment] 2023-06-20 22:47
@mananjadhav What is the optimal Solution/Proposal to you whenever you are provided with a bug ?

**Comment by mananjadhav** [comment] 2023-06-21 11:53
@dangrous Yeah while I think the issue would be different root cause, but looking at the PR it is possible this one gets fixed too.

**Comment by dangrous** [comment] 2023-06-21 20:42
okay cool - I'll put this on hold for now and we can retest once that's deployed! Then we can either close or move forward with a proposal here.

**Comment by dangrous** [comment] 2023-06-27 14:48
The fix for #19363 is on staging - can we test and see if this issue is fixed? Thanks!

**Comment by mananjadhav** [comment] 2023-06-27 15:07
I can see this is fixed on staging. I think we're good to close this one out.

**Comment by dangrous** [comment] 2023-06-27 20:12
Yep! Thanks for testing, @mananjadhav! Just confirmed.

So @sophiepintoraetz I think we can close out, after paying @Puneet-here for bug reporting.

**Comment by sophiepintoraetz** [comment] 2023-06-28 05:31
Puneet is paid so closing, thanks Daniel for helping to move this along!

**Closed by sophiepintoraetz** 2023-06-28 05:31 UTC
Labels: External, Weekly, Help Wanted, Bug
