### ISSUE TITLE
[$500] Full text displayed only when hovering on the ellipsis and not hovering on any part of the text

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37646] opened 2024-03-01 21:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709310335035499

## Action Performed:
1. Open any chat
2. Send a very long message
3. Create a Reply in Thread
4. Hover over the `...` ellipsis to reveal the full text in the header
5. Hover over any part of the text in the header

## Expected Result:
Full text should reveal when hovering any part 

## Actual Result:
Does not trigger when hover any part of the text

NOTE: lt is impossible to see the full text of an ellipsis in native apps

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/7ea57f4a-ec58-4241-b068-74ee604d622c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fa03b98e699456a</li>
        <li>Upwork Job ID: 1764752684265254912</li>
        <li>Last Price Increase: 2024-03-04</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-03-02 08:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip only shows when we hover over the text ellipsis.

### What is the root cause of that problem?
The tooltip is currently only being placed for the ellipsis.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L78-L84

So, the tooltip only shows when we hover over the ellipsis.

### What changes do you think we should make in order to solve the problem?

We can move the tooltip and wrap it to the whole text.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L50-L53

This would change it for all component that uses DisplayNames, such as the LHN title. If we only want to apply this for report header, then we can introduce a new prop to conditionally disable (`shouldRender`) the tooltip.

**Comment by iwiznia** [comment] 2024-03-04 15:40
Not the assignee for this issue, but something in my comment in slack that was not added to the issue is: it would be nice if we could, as part of this issue, make tap&hold work on mobile devices, so it is equivalent to the hover on web/desktop.
Otherwise there's no way of seeing the full text in mobile.

**Comment by Christinadobrzyn** [comment] 2024-03-04 20:39
I can reproduce this following the steps in the OP, I think it can be external gonna.

**Comment by hungvu193** [comment] 2024-03-05 02:57
Hey @Christinadobrzyn. What's the expected behavior here? Does it include @iwiznia 's suggesstion?

> Not the assignee for this issue, but something in my comment in slack that was not added to the issue is: it would be nice if we could, as part of this issue, make tap&hold work on mobile devices, so it is equivalent to the hover on web/desktop. Otherwise there's no way of seeing the full text in mobile.

**Comment by Christinadobrzyn** [comment] 2024-03-05 21:07
Let me ask the team but I think the expected behaviour is that you see the entire message when you hover over `...` in the chat thread. Also, on the mobile, you can tap and hold over the `...` to see the entire message on the mobile app. 

Let me confirm this with the team and I'll get back!

**Comment by kaushiktd** [comment] 2024-03-06 05:25
### Please re-state the problem that we are trying to solve in this issue.
Full text displayed only when hovering on the ellipsis and not hovering on any part of the text

### What is the root cause of that problem?
the tooltip is wrapped around the ellipsis element, causing it to be triggered only when hovering over the ellipsis and not when hovering over other parts of the text.

### What changes do you think we should make in order to solve the problem?
```
https://github.com/Expensify/App/blob/main/src/components/DisplayNames/DisplayNamesWithTooltip.tsx#L56-L84
<Tooltip
    text={fullTitle}
    shouldRender // Always render the tooltip when `shouldRender` is true
>
 <Text
            style={[textStyles, styles.pRelative]}
            numberOfLines={numberOfLines || undefined}
            ref={containerRef}
            testID={DisplayNamesWithToolTip.displayName}
        >
......
</Text>
</Tooltip>
```
the tooltip will always render when `shouldRender` is true, which can only enable the tooltip when it is true also We need to wrap the Text component with Tooltip.

### video:- 
https://drive.google.com/file/d/1E5oEIuFlyrJtRKZyPwYon9aZIxED9luc/view?usp=sharing

**Comment by Christinadobrzyn** [comment] 2024-03-07 00:42
The decision by the [team](https://expensify.slack.com/archives/C066HJM2CAZ/p1709768408355829?thread_ts=1709674104.406489&cid=C066HJM2CAZ) is to do nothing and leave this as it is. 

So going to close this out without action - let me know if you have any questions @hungvu193

**Closed by Christinadobrzyn** 2024-03-07 00:42 UTC
Labels: External, Daily, Help Wanted, Bug
