### ISSUE TITLE
[HOLD] New marker appears when clicking on the message option in the details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13861] opened 2022-12-28 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the chat screen for userA and userB
2. sent message from userA to userB
3. click on name of userA in userB screen(it will show user details)
4. click on message option in details page

## Expected Result:
should not show New marker

## Actual Result:
New marker appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209850004-890dd206-4e4e-4d94-a7c7-4177f506f004.mov

https://user-images.githubusercontent.com/43996225/209850032-30cdff51-9476-45db-9e5b-64a1317883df.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672147098865319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01782e2f06bca03f51</li>
        <li>Upwork Job ID: 1608229584366911488</li>
        <li>Last Price Increase: 2022-12-28</li>
    </ul>
</details>

**Comment by sketchydroide** [comment] 2022-12-28 22:32
this does aound like a bug, it might be affected by the changes to the sequenceNumber though. I will take this

**Comment by sketchydroide** [comment] 2022-12-28 22:33
I feel this should be internal regardless as there might be some Web work (I don't think so atm but it's possible)

**Comment by sketchydroide** [comment] 2022-12-30 10:46
will probably only work on it next week

**Comment by sketchydroide** [comment] 2023-01-02 10:34
Yep will work on this week

**Comment by sketchydroide** [comment] 2023-01-03 15:33
Probably tomorrow

**Comment by sketchydroide** [comment] 2023-01-04 11:53
Hmm, I think we need to wait for the sequence number deprecation to finish before we review this one.
Setting this to Hold, and weekly while we wait for that.

**Comment by Christinadobrzyn** [comment] 2023-01-16 02:17
Here's the depreciate sequence numbers tracking issue - https://github.com/Expensify/Expensify/issues/227234

looks like this is still in the works so keeping this on hold

**Comment by sketchydroide** [comment] 2023-01-30 10:28
Deprecated sequence number is still WIP, seems closet to being finished though

**Comment by sketchydroide** [comment] 2023-02-08 16:46
I think sequence numbers is finished meaning we can probably remove this from hold

**Comment by sketchydroide** [comment] 2023-02-08 16:47
@Christinadobrzyn can you try to reproduce with the latest version?

**Comment by Christinadobrzyn** [comment] 2023-02-09 07:03
- [ ]  Android / native
- [ ]  Android / Chrome
- [X]  iOS / native v1.2.67-7
- [X]  iOS / Safari v1.2.68-0
- [X]  MacOS / Chrome / Safari v1.2.68-0
- [X]  MacOS / Desktop v1.2.66-0


### Action Performed:

- Open the staging chat screen for userA and userB
- sent message from userA to userB
- click on name of userA in userB screen (it will show user details)
- click on message option in details page
- check to see if I get a 'new message' marker in the chat  > I did not

### Result

I am not getting the new message marker 

![2023-02-09_14-51-37 (1)](https://user-images.githubusercontent.com/51066321/217739239-9092cfea-ceb7-4800-912f-971f49ca60dc.gif)

**Comment by Christinadobrzyn** [comment] 2023-02-09 07:04
We don't have a C+ on this right? I can just pay out the @gadhiyamanan as the reporter if this is good to close!

**Comment by sketchydroide** [comment] 2023-02-09 08:41
That sounds good

**Comment by Christinadobrzyn** [comment] 2023-02-10 06:17
Created job in Upwork: 
Internal posting - https://www.upwork.com/ab/applicants/1623928469866430464/job-details
External posting - https://www.upwork.com/jobs/~01b2a651de89bc994f

Hired @gadhiyamanan as reported. Let me know when you've accepted the job and I'll pay you!

**Comment by gadhiyamanan** [comment] 2023-02-10 06:18
@Christinadobrzyn accepted

**Comment by Christinadobrzyn** [comment] 2023-02-10 06:19
I _believe_ we also need to do this checklist (at least the Test Rail step) - @sketchydroide let me know if I'm wrong. 

BugZero Checklist: The PR fixing this issue has been merged! 

 [@sketchydroide] The PR that introduced the bug has been identified. Link to the PR:
 [@sketchydroide] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@sketchydroide] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
 [@sketchydroide & @Christinadobrzyn] Propose [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
 [@Christinadobrzyn] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by Christinadobrzyn** [comment] 2023-02-10 06:22
Paid @gadhiyamanan 🎉 Closed the upwork job

**Comment by Christinadobrzyn** [comment] 2023-02-21 07:34
Sorry, working on a regression test.

**Comment by Christinadobrzyn** [comment] 2023-02-22 09:06
reached out for Regression Test Buddy check - https://expensify.slack.com/archives/C01SKUP7QR0/p1677056787584049

**Comment by Christinadobrzyn** [comment] 2023-02-22 09:16
Regression Test GH request here - https://github.com/Expensify/Expensify/issues/263913

closing!

**Closed by Christinadobrzyn** 2023-02-22 09:16 UTC
Labels: Daily, Internal, Bug
