### ISSUE TITLE
[HOLD for payment 2023-06-28] Font color is blue instead of white in mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20819] opened 2023-06-15 13:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. type @ and enter your mail

## Expected Result: 
blue font is not visible clearly with green background
## Actual Result: 
font color is blue

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c86b94e7-2056-4b74-9d19-fab131a5edbc

<img width="954" alt="Screenshot (367)" src="https://github.com/Expensify/App/assets/43996225/abe804c5-6137-440b-93db-458bc1e5436e">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686815472503979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Pujan92** [comment] 2023-06-15 14:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Text color is not visible properly for the mention

### What is the root cause of that problem?
Seems it is a regression from https://github.com/Expensify/App/issues/19303, when `Text` is modified to `TextLink` but the `color` style we are not passing properly.

### What changes do you think we should make in order to solve the problem?
We need to update the below part to pass `color` attribute with the style array and remove color prop line.

https://github.com/Expensify/App/blob/d39643006874bf5ffec923291afa6b43884a4aec/src/components/HTMLEngineProvider/HTMLRenderers/MentionUserRenderer.js#L41-L47

```
style={[props.style, {color: StyleUtils.getMentionTextColor(isOurMention)}, StyleUtils.getMentionStyle(isOurMention)]}
```

**Comment by marcaaron** [comment] 2023-06-15 21:17
@puneetlath related to mentions feature (I think you said you would fix all of these somewhere :trollface:)

**Comment by marcaaron** [comment] 2023-06-15 21:45
Merged linked PR so this should be able to be checked off once it hits staging.

**Comment by luacmartins** [comment] 2023-06-19 16:54
Fixed here - https://github.com/Expensify/App/pull/20845

**Comment by puneetlath** [comment] 2023-06-22 16:28
>@puneetlath related to mentions feature (I think you said you would fix all of these somewhere :trollface:)

Yes I did! 😅  Feel free to assign me as CME on any mentions-related bugs in the future if you like!

**Comment by youssef-lr** [comment] 2023-06-26 10:35
Not overdue.

**Comment by abekkala** [comment] 2023-06-28 12:02
* Issue reported by: @gadhiyamanan [$250] - Upwork payment offer sent! 

Fix was included in the PR above

**Comment by gadhiyamanan** [comment] 2023-06-28 12:05
@abekkala accepted, thanks!

**Comment by abekkala** [comment] 2023-06-28 12:06
Paid and contract ended - thank you! 🎉

**Closed by abekkala** 2023-06-28 12:06 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
