### ISSUE TITLE
[$1000] 2FA - Crash when login with expired then active magic link with 2FA enabled

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#20550] opened 2023-06-09 20:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open iOS app
2. Input email for account with 2FA setup
3. Tap "Continue"
4. Tap "Didn't receive a magic code"
5. Open 1st email with expired magic link
6. Paste link modified to staging in notes app
7. Tap on the link
8. Open 2nd email with active magic link
9. Paste link modified to staging in notes app
10. Tap on the link

## Expected Result:
User lands in 2FA input page after tapping on active magic link

## Actual Result:
User lands in an error page "Uh-Oh something with wrong".
Issue is also reproducible if user doesn't modify links to staging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/75f97d32-f6e5-4a10-82d0-dc42a5e3896d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014d820fa677af5f37</li>
        <li>Upwork Job ID: 1668329278170382336</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by isagoico** [comment] 2023-06-09 20:39
Just confirmed this issue is not reproducible in the production iOS build. Adding the label.

**Comment by joekaufmanexpensify** [comment] 2023-06-09 21:25
@deetergp curious if you agree this should be an hourly deploy blocker?

**Comment by deetergp** [comment] 2023-06-09 23:43
I'm not really sure that it should be a blocker. Yes, it's not ideal and should definitely be fixed, but it also feels like a bit of an edge case that shouldn't hold up the rest of the deploy. That changing the link between staging & prod produces the same result definitely makes it seem like it's not a back-end issue. FWIW, I am going to be ooo on Monday (but back on Tuesday) so if this ends up staying a blocker, we may want to reassign it.

**Comment by joekaufmanexpensify** [comment] 2023-06-12 12:59
Discussing more [here. ](https://expensify.slack.com/archives/C03TQ48KC/p1686574780001569)

**Comment by joekaufmanexpensify** [comment] 2023-06-12 15:43
Based on the above discussion, making this a daily since this is an edge case. We'll handle this like a standard bug report!

**Comment by joekaufmanexpensify** [comment] 2023-06-13 18:20
Waiting for proposals here.

**Comment by joekaufmanexpensify** [comment] 2023-06-14 19:33
Sounds good! I will try to reproduce again.

**Comment by joekaufmanexpensify** [comment] 2023-06-15 20:25
Okay, yeah I just tried to reproduce in the staging app and this is not happening for me. @deetergp given several people can no longer reproduce this, I'm thinking we should close. Thoughts?

**Comment by deetergp** [comment] 2023-06-16 18:17
I agree @joekaufmanexpensify, if we can no longer reproduce it and there aren't any other steps, let's close it.

**Comment by joekaufmanexpensify** [comment] 2023-06-16 19:16
Cool cool. Closing as this seems to be fixed!

**Closed by joekaufmanexpensify** 2023-06-16 19:16 UTC
Labels: External, Daily, Help Wanted, Bug
