### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Copy to clipboard tooltip moves to top left corner on copy to clipboard click

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29678] opened 2023-10-16 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84.4
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697387056991069

## Action Performed:
1. Open the app
2. Open any report
3. Click on self profile pic or any user profile pic
4. Hover first on email/phone number and then hover and click on 'copy to clipboard'
5. Do not move the cursor and observe that tooltip shifts to top left corner of screen

## Expected Result:
App should display tooltip above copy to clipboard after click on it

## Actual Result:
App displays tooltip in top left corner after click on copy to clipboard

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/7a0feff0-0f4d-42e0-aa6e-9f30618c65c4

https://github.com/Expensify/App/assets/93399543/cad0ad16-9b4f-4f5c-a98b-7b9d57fc0bb9

https://github.com/Expensify/App/assets/93399543/d87012be-a2d6-4320-9e40-e5be19c4b82c

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/c8990d38-e37b-4324-a079-16140bdd57a4

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2023-10-16 14:09
Clearly a big but I dont think we have to block deploy on this

**Comment by Julesssss** [comment] 2023-10-16 14:16
Yep, removing the blocker label. and updating the checklist.

**Comment by alitoshmatov** [comment] 2023-10-16 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy to clipboard tooltip moves to top left corner on copy to clipboard click
### What is the root cause of that problem?
Changed button icon when pressed is triggering `updateBounds` function to recalculate tooltips position. 
https://github.com/Expensify/App/blob/7fdbe508c6a240b1db74adf74fbf8ddffe907010/src/components/Tooltip/BaseTooltip.js#L129
This function ,in turn, is calling `chooseBoundingBox` to get bounding box of the button. 
https://github.com/Expensify/App/blob/7fdbe508c6a240b1db74adf74fbf8ddffe907010/src/components/Tooltip/BaseTooltip.js#L52

When mouse is not moved, `target` element is unmounted from dom, because button icon is changing. Also `target` only gets updated when mouse is [moved](https://github.com/Expensify/App/blob/7fdbe508c6a240b1db74adf74fbf8ddffe907010/src/components/Tooltip/BaseTooltip.js#L199). That is why `chooseBoundingBox` is returning us inaccurate target element. Also fallback bounding box is inaccurate here, since target element is unmounted
https://github.com/Expensify/App/blob/7fdbe508c6a240b1db74adf74fbf8ddffe907010/src/components/Tooltip/BaseTooltip.js#L51-L52


### What changes do you think we should make in order to solve the problem?
We should utilize `bounds` argument provided in `updateBounds` function and set it as fallback in `chooseBoundingBox`. We can either path `bounds` to `chooseBoundingBox` function and replace last return with this:
```javascript
// If no matching bounding box is found, fall back to getBoundingClientRect.
    return target.getBoundingClientRect();
```
Or we can return `null` from `chooseBoundingBox` when no valid bounding box is selected, and use available `bounds`:
```javascript
const betterBounds = chooseBoundingBox(target.current, initialMousePosition.current.x, initialMousePosition.current.y) || bounds;
```

### What alternative solutions did you explore? (Optional)

**Comment by garrettmknight** [comment] 2023-10-16 15:55
Reproduced - opening up to external for a fix

**Comment by akamefi202** [comment] 2023-10-17 10:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy to clipboard tooltip moves to top left corner on copy to clipboard click.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/components/Tooltip/BaseTooltip.js#L80-L83

Whenever `hover` event occurs, `updateTargetAndMousePosition` function is called to get `target` of the event.

https://github.com/Expensify/App/blob/91e2120e647aa9ee22171b6dbb772b4aebe64992/src/components/Tooltip/BaseTooltip.js#L51-L52

And from `target`, the app gets bounds data to display tooltip.

>5. Do not move the cursor and observe that tooltip shifts to top left corner of screen

But in the step 5 of this issue, `target` of `hover` event returns `<svg>` or `<path>` tag because the user is pointing on the icon.
And the app gets zero as bounds data because `<svg>` & `<path>` tags are not DOMRect objects.
`getBoundingClientRect` & `getClientRects` function return empty or zero data in this case.

As a result, we see the tooltip in the top left corner of the screen.

### What changes do you think we should make in order to solve the problem?
We should get `currentTarget` of the event inside `updateTargetAndMousePosition` function.
```
target.current = e.currentTarget;
```

So we can get correct object which has the handler and we can also get correct bounds data for tooltip.

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-10-17 19:33
This is a regression from https://github.com/Expensify/App/pull/29134. I think @akamefi202 solution is best here.

@alitoshmatov The argument `bounds` and the result of `chooseBoundingBox` should be the same if there is only one bounding box. The fact that they are not means we are evaluating two different elements.

**Comment by s77rt** [comment] 2023-10-17 19:34
@abdulrahuman5196 I will handle this since it's a regression

**Comment by s77rt** [comment] 2023-10-17 19:35
Let's go with @akamefi202 proposal.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/29678#issuecomment-1766147591)

**Comment by akamefi202** [comment] 2023-10-17 19:41
@s77rt Thank you. So I guess my proposal will fix 3 issues at once.

**Comment by akamefi202** [comment] 2023-10-18 22:05
@garrettmknight Can we start this job soon if you have some time for this?

**Comment by garrettmknight** [comment] 2023-10-19 08:59
Upwork job: https://www.upwork.com/en-gb/ab/applicants/1714929142813540352/suggested

**Comment by akamefi202** [comment] 2023-10-19 09:11
@garrettmknight It shows "Sorry, we can't let you in" error.

**Comment by grgia** [comment] 2023-10-19 09:32
All yours @akamefi202! Thank you for your proposal

**Comment by akamefi202** [comment] 2023-10-19 13:00
The PR is merged.

**Comment by s77rt** [comment] 2023-10-23 21:49
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/29134
- The offending PR has been commented on: https://github.com/Expensify/App/pull/29134#discussion_r1369279130
- A discussion in #expensify-bugs has been started: Not needed
- Determine if we should create a regression test for this bug: Yes

___

**Regression Test Proposal**
https://expensify.testrail.io/index.php?/cases/view/1977387

4. Verify that the correct tooltip is displayed over each of the action options (copy link, download, copy to clipboard, mark as unread)
5. Click the copy to clipboard option
6. Verify the tooltip position stays the same
7. Move the cursor away from the options

**Comment by garrettmknight** [comment] 2023-10-24 09:20
QA added - now we wait for payment.

**Comment by garrettmknight** [comment] 2023-10-24 09:31
Offers out for payment in the meantime.

**Comment by akamefi202** [comment] 2023-10-24 10:17
@garrettmknight I received the offer in Upwork? I should accept it again?

**Comment by s77rt** [comment] 2023-10-24 10:42
@garrettmknight No payment is due for me here since it's a regression.

**Comment by garrettmknight** [comment] 2023-10-24 17:09
My mistake @s77rt thanks for keeping me honest

**Comment by akamefi202** [comment] 2023-10-30 09:44
@garrettmknight Could you please complete this issue if there isn't other problem?

**Comment by garrettmknight** [comment] 2023-10-30 19:23
**Summarizing payment:**
- Urgency bonus: Yes
- Reporter: @dhanashree-sawant $50 paid via Upwork
- Contributor: @akamefi202 $750 paid via Upwork

**Closed by garrettmknight** 2023-10-30 19:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
