### ISSUE TITLE
[HOLD for payment 2023-10-30] [$250] Distance - Waypoints are not correctly ordered in generated eReceipt

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29621] opened 2023-10-14 17:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27204
## Action Performed:
1. Enter the start location, finish location and 10 other stops
2. Click on "Next"
3. Select the workspace
4. Confirm the request
5. Go to the distance report
6. Click on the map

## Expected Result:
The generated eReceipt should have all points ordered as they were entered at the time of request

## Actual Result:
The generated eReceipt does not have the points correctly ordered

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop
- [x] Windows: Chrome

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/d1f7fae9-ed4c-471d-98b0-a6ac80bcf96e

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

<details>
<summary>Windows: Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/f72c87b5-2434-45d8-bebe-80295efef5d6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c57e39dd4e2e4a50</li>
        <li>Upwork Job ID: 1713630588584648704</li>
        <li>Last Price Increase: 2023-10-15</li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-10-15 19:00
This is a new feature and i dont think this has to be blocker, its not ideal experience but i think we can fix this in a quick follow up @neil-marcellini @arosiclair rather then hold deploy on this fix.

**Comment by marcochavezf** [comment] 2023-10-16 19:02
Posted in wave5 for visibility in case someone from the distance req team wants to take it over

**Comment by neil-marcellini** [comment] 2023-10-16 20:02
Ah I think this is a backend problem where we aren't sorting the waypoints by key when creating the request and assuming that they are in order. JSON doesn't guarantee that they are in order and clearly they are not.

I can tell because the route image shows the waypoints out of order. I'll work on a fix soon.

**Comment by neil-marcellini** [comment] 2023-10-17 15:41
Here are a bunch of waypoints that reproduce the problem.

<details>
<summary>Waypoints</summary>

```json
{
  "waypoint0": {
    "lat": 37.9004816,
    "lng": -122.6444263,
    "address": "Stinson Beach, CA 94970, USA"
  },
  "waypoint1": {
    "lat": 37.8652634,
    "lng": -122.3111483,
    "address": "Berkeley Marina, Berkeley, CA, USA"
  },
  "waypoint2": {
    "lat": 37.8064291,
    "lng": -122.4506915,
    "address": "Crissy Field East Beach, San Francisco, CA 94129, USA"
  },
  "waypoint3": {
    "lat": 37.8727428,
    "lng": -122.4554066,
    "address": "Tiburon, CA 94920, USA"
  },
  "waypoint4": {
    "lat": 37.9445266,
    "lng": -122.5086664,
    "address": "Larkspur, CA 94939, USA"
  },
  "waypoint5": {
    "lat": 37.8974259,
    "lng": -122.4885845,
    "address": "Blackies Pasture, Tiburon, CA 94920, USA"
  },
  "waypoint6": {
    "lat": 36.6002378,
    "lng": -121.8946761,
    "address": "Monterey, CA, USA"
  },
  "waypoint7": {
    "lat": 37.8309974,
    "lng": -122.2919998,
    "address": "4400 Shellmound St, Emeryville, CA 94608, USA"
  },
  "waypoint8": {
    "lat": 37.9435872,
    "lng": -122.5405003,
    "address": "800 Magnolia Ave, Larkspur, CA 94939, USA"
  },
  "waypoint9": {
    "lat": 37.6191671,
    "lng": -122.3816108,
    "address": "San Francisco, CA 94128, USA"
  },
  "waypoint10": {
    "lat": 37.7156188,
    "lng": -122.2143079,
    "address": "1 Airport Dr, Oakland, CA 94621, USA"
  },
  "waypoint11": {
    "lat": 37.7935724,
    "lng": -122.483638,
    "address": "Baker Beach, San Francisco, CA, USA"
  }
}
```
</details>

**Comment by neil-marcellini** [comment] 2023-10-18 03:38
The waypoint ordering problem is fixed now with a very simple change on the front end. However I also noticed that the eReceipt and image weren't loading properly sometimes, so I'm planning to fix that in the same PR.

**Comment by neil-marcellini** [comment] 2023-10-19 01:25
Up for review!

**Comment by conorpendergrast** [comment] 2023-10-31 13:50
Let's skip the C+ checklist, as this is a brand new feature for now

**Comment by conorpendergrast** [comment] 2023-10-31 13:51
@situchan [Offer sent](https://www.upwork.com/nx/wm/offer/27455511)!

**Comment by conorpendergrast** [comment] 2023-10-31 20:46
Payouts due:

- [x] Contributor+: $250 @situchan 

Eligible for 50% #urgency bonus? N/A - internal issue

Upwork job is [here](https://www.upwork.com/jobs/~01c57e39dd4e2e4a50).

**Comment by conorpendergrast** [comment] 2023-10-31 20:46
All done!

**Closed by conorpendergrast** 2023-10-31 20:46 UTC
Labels: Reviewing, Engineering, Daily, Internal, Awaiting Payment, Bug
