### ISSUE TITLE
[$1000] mWeb - Close Account - Scroll bar is black color instead light green

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13592] opened 2022-12-14 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings > Security > Close Account
4. Enter the any letter and tap Return button
5. Do it until you can see the scroll bar

## Expected Result:
The scroll bar should be light green

## Actual Result:
Scroll bar is black color

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (only Safari)

**Version Number:** 1.2.39.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207699235-6070cf18-cfcd-4cb4-a64e-f956e249c57a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fdb138457063279</li>
        <li>Upwork Job ID: 1603397981957001216</li>
        <li>Last Price Increase: 2022-12-15</li>
    </ul>
</details>

**Comment by Delgee** [comment] 2022-12-15 15:31
### Proposal

If we want to change scrollbar color we can just add this CSS.

```css
textarea {
  scrollbar-width: thin;
  scrollbar-color: #03d47c transparent;
}
textarea::-webkit-scrollbar {
  width: 6px;
}
textarea::-webkit-scrollbar-track {
  background-color: transparent;
}
textarea::-webkit-scrollbar-thumb {
  background-color: #03d47c;
  border-radius: 6px;
  border: 3px solid #03d47c;
}
```

It will work on cross browser.

Ios safari mobile web working example.


![Screenshot 2022-12-15 at 23 31 11](https://user-images.githubusercontent.com/6459339/207901219-52282fd6-5d9e-4f9d-bf6f-c1ad8b4e92fc.png)

**Comment by syedsaroshfarrukhdot** [comment] 2022-12-15 21:45
I believe this issue to be a dupe of [GH Issue](https://github.com/Expensify/App/issues/12914). As we might end up updating -webkit-scrollbar styles there it will fix the issue of scrollbar inconsistency in the app. It should be fixed automatically here also. I think it should be put on hold till then.

**Comment by normaldev112** [comment] 2022-12-16 00:53
![image](https://user-images.githubusercontent.com/95582366/207997391-838d6a12-1727-4bf0-892f-36a6e7edcc00.png)

do you mean this issue?

**Comment by normaldev112** [comment] 2022-12-16 00:54
> ### Proposal
> If we want to change scrollbar color we can just add this CSS.
> 
> ```css
> textarea {
>   scrollbar-width: thin;
>   scrollbar-color: #03d47c transparent;
> }
> textarea::-webkit-scrollbar {
>   width: 6px;
> }
> textarea::-webkit-scrollbar-track {
>   background-color: transparent;
> }
> textarea::-webkit-scrollbar-thumb {
>   background-color: #03d47c;
>   border-radius: 6px;
>   border: 3px solid #03d47c;
> }
> ```
> 
> It will work on cross browser.
> 
> Ios safari mobile web working example.
> 
> ![Screenshot 2022-12-15 at 23 31 11](https://user-images.githubusercontent.com/6459339/207901219-52282fd6-5d9e-4f9d-bf6f-c1ad8b4e92fc.png)

this will works, but it has ability to affect others).
This is my suggestion.

**Comment by priyeshshah11** [comment] 2022-12-16 09:28
## Proposal

Actually this problem exists for all scrollbars throughout the app and is a complex problem for iOS & android as react-native doesn't provide an easy way to do this. 

### All platforms

For iOS we do have an `indicatorStyle` prop for scrollview with values either 'light', 'dark' or 'default' but nothing for custom colour. It can be implemented in native code or we can hide the native scrollbars and create our custom scrollbar and display it over the scrollview with the help of Animated API and a few scroll events, somewhat like [this](https://stackoverflow.com/a/57839837/16762514) but that will need to be implemented for Flatlists too. 

Sorry, I am currently not in a position (time-wise) to provide the full code for this.


### Web only solution:
Add the below css in web/index.html

```
/* Customize scrollbar color & width for firefox */
body {
    scrollbar-width: thin;
    scrollbar-color: #03d47c transparent;
}
/* Customize scrollbar color & width for most browsers except firefox */
::-webkit-scrollbar {
    width: 4px;
}
::-webkit-scrollbar-track {
    background-color: transparent;
}
::-webkit-scrollbar-thumb {
    background-color: #03d47c;
    border-radius: 4px;
}
```

**Comment by grgia** [comment] 2022-12-16 16:08
I agree with @syedsaroshfarrukhdot that this is a dupe. Let's close this and tackle it in https://github.com/Expensify/App/issues/12914

**Closed** 2022-12-19 12:19 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
