### ISSUE TITLE
[$250] Newly created IOUs land on a “paid” (closed) report, show violations

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41458] opened 2024-05-01 21:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714565513087969

## Action Performed:
1. Request IOU from user A to user B
2. Complete the IOU request to have an existing `closed` IOU report
3. Request several IOU (e.g.off-workspace)
## Expected Result:
IOUs are added a new report, don’t show violations
## Actual Result:
IOUs are added an existing closed report, show violation

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-05-01 at 06 12 12@2x](https://github.com/Expensify/App/assets/38435837/32b40a28-1919-45c0-837e-eeabf7d85fe2)
![CleanShot 2024-05-01 at 06 12 35@2x](https://github.com/Expensify/App/assets/38435837/a334049c-7e1a-4ad5-987a-edf47b02a7cd)
![Screen Shot 2024-05-01 at 4 04 36 PM](https://github.com/Expensify/App/assets/38435837/0367d3b2-0c94-4216-9847-a1975fe12686)
![Screen Shot 2024-05-01 at 5 32 05 PM](https://github.com/Expensify/App/assets/38435837/8d64a590-b05b-4e8a-920c-e3cee30f3c89)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0107db764bbff3a0f3</li>
        <li>Upwork Job ID: 1787692523690471424</li>
        <li>Last Price Increase: 2024-05-14</li>
    </ul>
</details>

**Comment by garrettmknight** [comment] 2024-05-09 18:10
Awaiting proposals.

**Comment by garrettmknight** [comment] 2024-05-13 14:53
Still awaiting proposals.

**Comment by rezkiy37** [comment] 2024-05-16 12:33
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by garrettmknight** [comment] 2024-05-16 19:29
@rezkiy37 please put forward a root cause analysis and proposal, thanks!

**Comment by rezkiy37** [comment] 2024-05-17 08:43
Yes, I am actively working on the issue.

**Comment by rezkiy37** [comment] 2024-05-17 09:13
Just tested. I was not able to reproduce the bug. My steps:
1. [User A] Open a new DM with user B.
2. [User A] Request IOU once for the user B.
3. [User B] Pay the IOU.
4. [User A] Request several IOUs.
5. [User A] No violations.
6. [User B] No violations.

<details><summary>Details</summary>
<p>

#### User A

https://github.com/Expensify/App/assets/57314631/ca34c27b-4194-498d-ac3c-015eed75604a

#### User B

<img width="287" alt="Screenshot 2024-05-17 at 11 13 05" src="https://github.com/Expensify/App/assets/57314631/431666f9-2f26-40c5-8757-70bbe3f97a99">
<img width="574" alt="Screenshot 2024-05-17 at 11 13 08" src="https://github.com/Expensify/App/assets/57314631/d666ea18-9d55-4f4d-9c4f-89dba9225b82">


</p>
</details> 

cc @garrettmknight @JmillsExpensify @m-natarajan

**Comment by garrettmknight** [comment] 2024-05-17 13:09
Looks like the reports are correctly being set as Processing now. Closing!

**Closed by garrettmknight** 2024-05-17 13:09 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
