### ISSUE TITLE
Web - Whisper messages sent to the workspace creator

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23865] opened 2023-07-29 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. As the workspace creator, I made the rooms.

## Expected Result:
The whisper message shouldn’t be sent every single time an anonymous user or someone new joins the room.

## Actual Result:
Whisper messages are sent to the workspace creator every single time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a3b047df-3c99-4597-9b70-c2c1f137e3d7

**Expensify/Expensify Issue URL:**
**Issue reported by:** @RobertLadue 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690572144167179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2023-08-01 22:21
@pecanoro I see you're working on whisper messages. Do you have a fix already for this?

@RobertLadue how could I reproduce this?

**Comment by pecanoro** [comment] 2023-08-02 11:18
@RobertLadue Hehe this is by design, the policy owner is supposed to get the whispers if they sent them. Maybe we should just skip the ones sent to anonymous accounts? But you will still get the rest.

**Comment by RobertLadue** [comment] 2023-08-02 17:19
@tjferriss to recreate it you need to make a public workspace and then use any of the rooms to have people come in - anonymous or with an account. You'll get the whisper in either case.

I don't think I care enough about getting a whisper ever. I have confidence it was sent and I don't need to know about it every time someone joins a room. I'm struggling to think of a time when, as the workspace creator, I would want to see the Whisper.

**Comment by tjferriss** [comment] 2023-08-09 05:04
Got it. I tend to agree with you, especially with anonymous users and such large, public rooms. Though with typical rooms/policies I would expect this is far less annoying and actually helpful to see these messages.

Would we consider adding some type of toggle to turn off these whispers?

**Comment by sakluger** [comment] 2023-08-09 16:11
@pecanoro is this a duplicate of https://github.com/Expensify/App/issues/21681? I see you are working on that issue as well.

**Comment by tjferriss** [comment] 2023-08-10 20:08
Thanks for pointing out that this is a dupe @sakluger. I'm going to close.

@RobertLadue can you respond to Sasha's question?

**Comment by pecanoro** [comment] 2023-08-15 10:55
This is not a duplicate of that issue, it's unrelated, so I am going to reopen it. I decided to hide the whispers for the policy owner, but normal whispers will be showed to both, the sender and the receiver.

**Comment by pecanoro** [comment] 2023-09-22 08:26
This is done!

**Closed by pecanoro** 2023-09-22 08:26 UTC
Labels: Reviewing, Weekly, Bug
