### ISSUE TITLE
[$500] Web – Task – Edited task marks unread for a second in the LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33610] opened 2023-12-26 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with any account.
3. Navigate to a task report that is assigned to your user (create one if needed)
4. Click on the Title
5. Change the title to anything and save

## Expected Result:
The title is updated in the task report info and header and edited task not marks unread in the LHN

## Actual Result:
The title is updated in the task report info and header, but edited task marks unread for a second in the LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/31d20829-db1f-4727-b575-4ab2543e65d6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f6f310d1270bdb5</li>
        <li>Upwork Job ID: 1739718839546228736</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by Tony-MK** [comment] 2023-12-27 01:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Edited task marks unread for a second in the LHN

### What is the root cause of that problem?

When the `editTask` endpoint is called, the backend doesn't return the value of `report.lastReadTime` but only returns the value `report.lastVisibleActionCreated`. `report.lastVisibleActionCreated` will be set a couple `ms` ahead of `report.lastReadTime`. Therefore, the `isUnread` will return true. The LHN row will appear unread. However, the `ReadNewestActions` endpoint is called immediately. Thus, the `report.lastReadTime` will be bigger than `report.lastVisibleActionCreated` making `isUnread` return false. The `AddComment` endpoint responds with `report.lastReadTime` and isn't affected.

**Onyx**
![Onyx Logs](https://github.com/Expensify/App/assets/22982173/1d4fd518-fe23-405f-8a5c-fd837e15fe63)

### What changes do you think we should make in order to solve the problem?


The best option is to change the `backend` to return `report.lastReadTime` and equate it to the `report.lastVisibleActionCreated`. Just like the `AddComment` endpoint. 

### What alternative solutions did you explore? (Optional)

From the front end, we can create a condition to check whether the task report is unread. The condition will only apply to this situation, an edited task. For example, with the boolean value `lastVisibleActionLastModified`, we can use the report actions stored in the onyx to check if `report.lastVisibleActionCreated` will be an accurate value to compare with `report.lastReadTime`.

**Comment by Santhosh-Sellavel** [comment] 2024-01-01 19:37
Yeah, I agree this better get handled in BackEnd.

@JmillsExpensify Can you add `internal` label here, please thanks!

**Comment by Santhosh-Sellavel** [comment] 2024-01-09 17:50
> Yeah, I agree this better get handled in BackEnd.
> 
> @JmillsExpensify Can you add `internal` label here, please thanks!

bump @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2024-01-23 17:10
Added the `internal` label, thanks for the DM btw!

**Comment by JmillsExpensify** [comment] 2024-01-23 17:16
Ah yes, I forgot about this. Honestly, I don't think tasks are a priority at the moment, and thus, I'm inclined to close it. Tasks are still largely a beta feature, and they will remain that way probably until next year.

**Comment by JmillsExpensify** [comment] 2024-01-23 17:29
In fact, thinking on this a bit more, I'm just going to close this issue. We can re-open when task become a more strategic priority, or this ends up happening for other cases.

**Closed by JmillsExpensify** 2024-01-23 17:29 UTC
Labels: Engineering, Daily, Internal, Help Wanted, Bug
