### ISSUE TITLE
[HOLD for payment 2023-08-01] [HOLD for payment 2023-07-28] Web - Workspace avatar is not updating after renaming

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23189] opened 2023-07-19 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a new account
2. Click on FAB > new workspace > Rename the workspace
3. Do step 2 again and notice the announce room vs the admin room avatars

## Expected Result:
Both announce room and admin room avatar should change at the same time to reflect the renamed workspace

## Actual Result:
 Only admin changes and announce room avatar doesn't update

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6644c097-4b06-47a2-9e73-6483fe58b230

https://github.com/Expensify/App/assets/93399543/8bf9304f-0e48-4cd9-a14a-4ccc109597de

**Expensify/Expensify Issue URL:**
**Issue reported by:** GH @Nathan-Mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689794502432149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-07-19 20:10
For mWeb both admin and announce rooms avatars don't update

**Comment by s-alves10** [comment] 2023-07-19 20:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Admin and announce room avatar are not updated after renaming workspace

### What is the root cause of that problem?

This issue is from this [PR](https://github.com/Expensify/App/pull/21406/files)
We don't get option data when policy changes as you can see below(no dependency)
https://github.com/Expensify/App/blob/fa473e96f52b76419623ce286f0ca96c5d108e76/src/components/LHNOptionsList/OptionRowLHNData.js#L58-L66

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to add policy as dependency for policy reports.
The code would look like
```
    const policy = lodashGet(policies, [`${ONYXKEYS.COLLECTION.POLICY}${fullReport.policyID}`], '');

    const optionItemRef = useRef();
    const optionItem = useMemo(() => {
        // Note: ideally we'd have this as a dependent selector in onyx!
        const item = SidebarUtils.getOptionData(fullReport, personalDetails, preferredLocale);
        if (deepEqual(item, optionItemRef.current)) {
            return optionItemRef.current;
        }
        optionItemRef.current = item;
        return item;
    }, [fullReport, preferredLocale, personalDetails, policy]);
```

This works perfect
### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2023-07-19 21:40
It looks like a regression from https://github.com/Expensify/App/pull/21406.

**Comment by francoisl** [comment] 2023-07-19 22:27
Sounds good, hopefully @hannojg can chime in, otherwise @s-alves10 's [proposal above](https://github.com/Expensify/App/issues/23189#issuecomment-1642693682) makes sense and works well for me.

**Comment by jasperhuangg** [comment] 2023-07-20 03:43
> I think another solution is adding an optimistic data to the announce report when the policy name is updated.

I'm not sure if that would work for other clients that receive an Onyx update with the new policy name.

> I think @s-alves10 proposal makes sense to me as well. Let's just wait for @hannojg feedbacks. I think the solution will make unnecessary re-renders when any other prop changes, maybe we should limit the dependency to policy.name ?

Sounds good with me! let's wait

**Comment by hannojg** [comment] 2023-07-20 05:47
Hey gang, I am here to look into it now!

**Comment by hannojg** [comment] 2023-07-20 06:08
Just adding to the proposal of @s-alves10, while this may work we explicitly want to express all the dependencies we need to calculate the option item data. By that I mean that we preferably want to forward the policy to the `getOptionData` function.

**Comment by s-alves10** [comment] 2023-07-20 06:10
@hannojg 
Yes, you're right. I'm doing that work now

**Comment by hannojg** [comment] 2023-07-20 06:27
@s-alves10 there are a lot of places where this change needs to be made. Just to be sure that we catch all of them, I am also looking into it (you can do the final PR with your proposal if you want, right now I am just concerned to solve this properly).

You can find my (yet unfinished) draft PR here: 

- https://github.com/Expensify/App/pull/23240

I gotta leave for an hour and then will come back to it!

**Comment by mountiny** [comment] 2023-07-20 08:10
Taking this one over from Francois as I have been also involved in the offending PR. Thanks for a quick fix. 

@s-alves10 you will also get compensated for your help while Hanno implements it

**Comment by hannojg** [comment] 2023-07-20 08:53
The PR is now up!

**Comment by s-alves10** [comment] 2023-07-20 12:28
@hannojg 

I have found that getOptionData depends on reportActions as well. I'm curious why you did ignore that

**Comment by mountiny** [comment] 2023-07-20 13:13
PR merged, going to CP this

**Comment by mountiny** [comment] 2023-07-20 18:09
@slafortune This was a regression from another PR so Hanno and @fedirjh dont need any payment but @s-alves10 helped with finding the solution so we should pay them $250 for their help

Additionalyt @Nathan-Mulugeta to the issue reporter

**Comment by slafortune** [comment] 2023-08-02 19:10
@s-alves10 and @Nathan-Mulugeta  - offers sent!

**Comment by Nathan-Mulugeta** [comment] 2023-08-03 04:07
Offer accepted

**Comment by slafortune** [comment] 2023-08-03 17:42
All Paid

**Closed by slafortune** 2023-08-03 17:42 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
