### ISSUE TITLE
[Violations] [$1000] Violations are not shown as approver

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36441] opened 2024-02-13 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707848268463619

## Action Performed:
1. Go to OldDot staging.expensify.com and open or create a Collect policy 
2. Make tags required for the policy 
- Go to Settings > [Workspace] > Tags
- Enable "People must tag expenses"
- Add a tag
3. Set violations for category as to be required
4. Go to the policy page
5. In the JS console with the policy open do:

p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();

6. Invite a user to the policy as employee
7. As an employee sign in to the NewDot, create a expense report without category and tag set
5. Open the report as approver logged in to NewDot

## Expected Result:
Error message for violations are shown

## Actual Result:
Not seeing violations as approver

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Screen Shot 2024-02-13 at 5 01 52 PM](https://github.com/Expensify/App/assets/38435837/505a92f4-dd0d-4152-b69c-1be70a663097)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ebca0f5b1a041068</li>
        <li>Upwork Job ID: 1757526242287419392</li>
        <li>Last Price Increase: 2024-02-22</li>
    </ul>
</details>

**Comment by brandonhenry** [comment] 2024-02-15 06:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approvers are not seeing the expected error messages for violation of expense report policies, specifically when category and tag settings are required but not set by the employee on the report.

### What is the root cause of that problem?
The root cause may involve the policy enforcement logic within the approver's view. It appears the validation checks that trigger error messages for missing categories or tags are not executing correctly, or the UI is not displaying the results of these checks as it should.

### What changes do you think we should make in order to solve the problem?

- Review the expense report validation flow to ensure that the checks for required fields are triggered when an approver reviews a report.
- Update the UI components responsible for displaying the error messages to approvers to ensure they are activated correctly when violations are detected.
- Ensure that the state management for the report correctly reflects the presence of violations and binds this state to the UI elements for error message display.
- Conduct tests on all supported platforms to ensure that upon opening a report with set violations, the approver is presented with the appropriate error messages.

### What alternative solutions did you explore? (Optional)
- An alternative solution could be to implement a pre-approval validation step, prompting the employee to correct the violations before submission to the approver. However, this may not be desirable as it shifts the responsibility from the approver to the employee.

**Comment by bfitzexpensify** [comment] 2024-02-16 05:05
@cead22 is this something you're planning on working on yourself, or is this something that contributors can tackle?

**Comment by cead22** [comment] 2024-02-16 22:00
Contributors can tackle it, I just assigned myself so I can be the reviewer of the PR since I've been leading violations and am familiar with the coe

**Comment by bfitzexpensify** [comment] 2024-02-19 08:26
Sweet - OK, awaiting proposals.

**Comment by brandonhenry** [comment] 2024-02-19 22:09
Was going to update my proposal here, but I am having a really hard time reproducing this issue. I'm not able to see this details request screen in ND. I'm also not able to access any workspace that supports tags inside of ND. There's no way to view a workspace other than free workspace in ND in prod right now. I don't think this is an urgent issue but maybe thats just me

**Comment by bfitzexpensify** [comment] 2024-02-21 05:38
[Posted](https://expensify.slack.com/archives/C9YU7BX5M/p1708493909425009) for help in the #qa channel

**Comment by kavimuru** [comment] 2024-02-21 14:22
I have edited the OP. Please check if this helps.

**Comment by bfitzexpensify** [comment] 2024-02-22 05:20
Thanks @kavimuru!

**Comment by bfitzexpensify** [comment] 2024-02-22 05:28
No full proposals after a week, let's increase the bounty

**Comment by brandonhenry** [comment] 2024-02-22 07:13
# Updated Proposal

## Problem Statement
Approvers are not seeing the expected error messages for violation of expense report policies, specifically when category and tag settings are required but not set by the employee on the report.

## Root Cause
The root cause of the problem is that the `getErrorForField` function, which is responsible for determining and displaying error messages for field violations, does not include checks for `category` and `tag` violations. As a result, even when these fields are required by the policy and left unset by the employee, no error messages are displayed to the approver.

https://github.com/Expensify/App/blob/d33bf6e0454fae9550422da28b0407f01b23c969/src/components/ReportActionItem/MoneyRequestView.tsx#L204

## Proposed Changes

1. **Update `getErrorForField` Function:** Modify `getErrorForField` function to include checks for `category` and `tag` violations. This will ensure that error messages are displayed for these fields when they are required by the policy but not set by the employee.

2. **Ensure Correct Dependency Handling:** Update the dependency array of the `useCallback` hook for the `getErrorForField` function to include `transactionCategory` and `transactionTag`. This will ensure that the function updates correctly when these values change.

```javascript
const getErrorForField = useCallback(
    (field: ViolationField, data?: OnyxTypes.TransactionViolation['data']) => {
        // Checks applied when creating a new money request
        // NOTE: receipt field can return multiple violations, so we need to handle it separately
        const fieldChecks: Partial<Record<ViolationField, {isError: boolean; translationPath: TranslationPaths}>> = {
            amount: {
                isError: transactionAmount === 0,
                translationPath: 'common.error.enterAmount',
            },
            merchant: {
                isError: !isSettled && !isCancelled && isPolicyExpenseChat && isEmptyMerchant,
                translationPath: 'common.error.enterMerchant',
            },
            date: {
                isError: transactionDate === '',
                translationPath: 'common.error.enterDate',
            },
            category: {
                isError: !transactionCategory,
                translationPath: 'common.error.selectCategory',
            },
            tag: {
                isError: !transactionTag,
                translationPath: 'common.error.selectTag',
            },
        };

        // .. code is the same
    },
    [transactionAmount, isSettled, isCancelled, isPolicyExpenseChat, isEmptyMerchant, transactionDate, transactionCategory, transactionTag, hasErrors, canUseViolations, hasViolations, translate, getViolationsForField],
);
```

**Comment by Tony-MK** [comment] 2024-02-22 08:33
This https://github.com/Expensify/App/pull/36821/ might fix this.

**Comment by brandonhenry** [comment] 2024-02-22 14:16
@Tony-MK that PR addresses MoneyRequestPreview. This ticket root cause is related to MoneyRequestView

**Comment by cead22** [comment] 2024-02-26 20:34
Still working on it

**Comment by cead22** [comment] 2024-02-29 16:59
It will

**Comment by cead22** [comment] 2024-03-05 01:11
Is this still reproducible?

**Comment by bfitzexpensify** [comment] 2024-03-05 06:08
Asked QA to retest in [Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1709618919908989)

**Comment by bfitzexpensify** [comment] 2024-03-05 21:05
QA are still able to reproduce @cead22 


https://github.com/Expensify/App/assets/38236554/51a99e3d-d9e9-463c-be36-3a07ac5152d7

**Comment by cead22** [comment] 2024-03-08 18:28
Thanks, I think I found the bug

**Comment by cead22** [comment] 2024-03-08 20:02
There are two things happening here:
1. We're not returning transaction violations for anyone other than the user that made the request in OpenReport
2. We don't push transaction violations to all the relevant users from the RequestMoney API command


I'll fix 1. for this issue, and 2. as part of https://github.com/Expensify/App/issues/37013

**Comment by cead22** [comment] 2024-03-08 23:21
PR submitted for item number 1. above

**Comment by cead22** [comment] 2024-03-13 00:48
PR submitted for item number 2. above

**Comment by JmillsExpensify** [comment] 2024-03-26 03:30
Nice! With both of those merged and on production, can we close this issue now?

**Comment by cead22** [comment] 2024-03-26 03:42
Yup!

**Closed by cead22** 2024-03-26 03:42 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
