### ISSUE TITLE
[HOLD for payment 2023-10-09] [Awaiting payment Oct 2 2023 / $500] Web -  green dot appears even if task is deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27805] opened 2023-09-19 18:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Click on + icon and select assign task
3. Enter title and assign task to you
4. Create task
5. Go to task thread and delete the task

## Expected Result:
should not show green dot show if task is deleted

## Actual Result:
green dot appears even if task is deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71-5
**Reproducible in staging?:** Y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/5a1ef321-1f2e-4f76-8aef-8be54fdab124

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695106297939429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01833b320ff7bd97a7</li>
        <li>Upwork Job ID: 1704197379523981312</li>
        <li>Last Price Increase: 2023-09-19</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Contributor | 26790441</li>
<li>gadhiyamanan | Reporter | 26790444</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-09-19 19:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The green dot is displayed in LHN for deleted task

### What is the root cause of that problem?

Here we check for the `optionItem.isArchivedRoom` to check if the task is closed. The archival logic was removed now.

https://github.com/Expensify/App/blob/f2282b2814025f283b36846c2a9124466e6f7431/src/components/LHNOptionsList/OptionRowLHN.js#L104-L108

### What changes do you think we should make in order to solve the problem?

We need to check for `optionItem.isArchivedRoom` instead.

### What alternative solutions did you explore? (Optional)

**Comment by abzokhattab** [comment] 2023-09-19 19:07
https://github.com/Expensify/App/blob/0603fe110a3f87f52510437ee6a61b6c938f738a/src/components/LHNOptionsList/OptionRowLHN.js#L105-L109

**Comment by rojiphil** [comment] 2023-09-20 08:03
Not able to reproduce in latest main - v1.3.71-11

**Comment by paultsimura** [comment] 2023-09-20 08:19
Still reproducible on `1.3.71-13`

<img width="674" alt="image" src="https://github.com/Expensify/App/assets/12595293/9ba35606-d1f1-4ce7-9b59-eb9122670360">

**Comment by rojiphil** [comment] 2023-09-20 08:47
Oops! Sorry @paultsimura. I can also reproduce it. Thanks for the verification.

**Comment by jasperhuangg** [comment] 2023-09-21 04:14
It seems this bug has made its way onto staging and isn't only specific to dev now.

**Comment by tgolen** [comment] 2023-09-21 05:35
I'm OK with that proposal, but I do have a request, can it be cleaned up a little by adding another utility method please? Something like:

```

            ReportUtils.isWaitingForIOUActionFromCurrentUser(optionItem) ||
            ReportUtils.isOpenTaskReportAssignedToUser(optionItem)
```

**Comment by paultsimura** [comment] 2023-09-21 05:43
Thanks @tgolen, I'll make a separate util function👍

**Comment by paultsimura** [comment] 2023-09-21 08:02
The PR is ready for review

**Comment by paultsimura** [comment] 2023-09-21 08:24
Please note: when canceling a task on one device, there is a buggy behavior in another: you have to open the task thread in order to fetch the actual state of the task. But it's a different issue as after the thread was opened, both the LHN title and green indicator are fixed.

<img width="376" alt="image" src="https://github.com/Expensify/App/assets/12595293/edba1465-651e-46b6-9b4b-e8ad7511fe4c">
<img width="373" alt="image" src="https://github.com/Expensify/App/assets/12595293/2b08d37b-8b67-4845-be84-dac92eca98c7">

**Comment by thienlnam** [comment] 2023-09-21 08:45
Going to remove the blocker on this as it's not a common flow right now and doesn't need to block deploy

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:30
Weird, the payment window wasn't added automatically. 🤔  Should be 7 days after the PR's deploy to watch for regressions.

**Comment by michaelhaxhiu** [comment] 2023-09-27 21:32
I'm handing this off to another BZ as I'm going on sabbatical by end of week, and want to ensure this is paid.

**Next steps** are as follows:
- Bug reporter: @gadhiyamanan $50
- Contributor: @paultsimura $750 (50% bonus x OG price)
- C+: @allroundexperts $750 (50% bonus x OG price)

**Comment by flaviadefaria** [comment] 2023-10-02 12:19
@paultsimura you've been paid
@gadhiyamanan please accept the offer so that I can pay you.

**Comment by gadhiyamanan** [comment] 2023-10-02 12:35
@flaviadefaria offer accepted, thanks!

**Comment by flaviadefaria** [comment] 2023-10-03 10:37
@allroundexperts can you address the comment above so that I can proceed to payment? Thanks!

**Comment by JmillsExpensify** [comment] 2023-10-05 13:32
$750 payment approved for @allroundexperts based on BZ summary.

**Comment by flaviadefaria** [comment] 2023-10-09 10:19
Alright, I believe everyone has been paid so closing this.

**Closed by flaviadefaria** 2023-10-09 10:19 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
