### ISSUE TITLE
[HOLD for payment 2024-12-16] [$250] [HOLD for payment 2024-12-07] [HOLD for payment 2024-12-03] Clean up card assignment when only one member and/or card

### ISSUE THREAD

**Issue by joekaufmanexpensify** [Expensify/App#52820] opened 2024-11-20 13:51 UTC
Coming from [here](https://expensify.slack.com/archives/C06ML6X0W9L/p1732108218713529?thread_ts=1731609778.494899&cid=C06ML6X0W9L), if you assign a third party card now on a workspace with only one member and/or card, you have to manually select the member and the card. This is unnecessary because the member will always see the card being assigned and to whom on the confirmation page Let's update this so:

- If there's one workspace member, we select them automatically (skipping the step) and land directly on the card selection. 
- If there's multiple workspace members, but only one card, after selecting a member, we select the card automatically (skipping the step) and landing on the start date. 
- If there's one workspace member AND one card, automatically select the member and card (skipping both steps) and land directly on the transaction start date. 

cc @mountiny @JmillsExpensify 

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021865953482835499840</li>
        <li>Upwork Job ID: 1865953482835499840</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by joekaufmanexpensify** [comment] 2024-11-20 13:57
It sounds like maybe @koko57 will take this one?

**Comment by koko57** [comment] 2024-11-20 14:00
looks like I'm the chosen one 😃 yup, taking it!

**Comment by joekaufmanexpensify** [comment] 2024-11-20 14:09
TY!

**Comment by mountiny** [comment] 2024-12-08 23:45
@DylanDylann @joekaufmanexpensify Could you please write up and add a regression test for this logic before closing this one? Thanks!

**Comment by DylanDylann** [comment] 2024-12-09 03:22
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by kadiealexander** [comment] 2024-12-18 04:55
Regression test: https://github.com/Expensify/Expensify/issues/454327

**Closed** 2024-12-18 04:57 UTC
Labels: Weekly, Awaiting Payment, Bug

**Comment by DylanDylann** [comment] 2024-12-19 04:45
@kadiealexander  I have given full refund for https://github.com/Expensify/App/issues/52820#issuecomment-2544995567.

This will be paid later when the batch of issues I'm working on is completed.
