### ISSUE TITLE
[HOLD for payment 2023-10-25] [$500] Dev: Web - The "Copy URL to clipboard" tooltip does not appear when hovering over a task description link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27812] opened 2023-09-19 20:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Assign task" section.
3. Enter a title and insert a link in the description, then create the task.
4. After task creation, right-click on the description link.
5. Observe that the tooltip for "Copy URL to clipboard" does not appear

## Expected Result:
 When hovering over a task description link and right-clicking, the "Copy URL to clipboard" tooltip should be displayed

## Actual Result:
The "Copy URL to clipboard" tooltip does not appear when hovering over a task description link

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.71.7
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/142b1276-6de9-4d8c-a03d-740f5e82cedb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695131883280419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f37f0d47d0bab66</li>
        <li>Upwork Job ID: 1704225979412377600</li>
        <li>Last Price Increase: 2023-10-04</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 27066533</li>
<li>ZhenjaHorbach | Contributor | 27066534</li>
</ul></li>
    </ul>
</details>

**Comment by jjcoffee** [comment] 2023-09-20 13:51
We may want to hold this on https://github.com/Expensify/App/pull/27769 in case they want to fix the regression. I've [asked](https://github.com/Expensify/App/pull/27769#issuecomment-1727777324) there.

**Comment by jjcoffee** [comment] 2023-09-20 14:06
@alexpensify can you update the title to hold on https://github.com/Expensify/App/pull/27769, per [this comment](https://github.com/Expensify/App/pull/27769#issuecomment-1727804374).

**Comment by alexpensify** [comment] 2023-09-20 23:20
Thanks for flagging @jjcoffee -- Done!

**Comment by alexpensify** [comment] 2023-09-29 06:12
@jjcoffee - this GH we were holding on is in production now. Can you test to confirm if we should keep this one open? Thanks!

**Comment by jjcoffee** [comment] 2023-09-29 12:05
@alexpensify Thanks for the heads up! Looks like they [decided](https://github.com/Expensify/App/pull/27769#issuecomment-1729310791) not to fix it, and I can still repro, so we're good to take this off hold.

We also already have a [proposal](https://github.com/Expensify/App/issues/27812#issuecomment-1726531560) from @ZhenjaHorbach we can go with. I like the idea of adding a `shouldEnableLinks` prop, but I'm unsure how necessary it is. Did you think of a situation where we would not want this enabled @ZhenjaHorbach?

:ribbon::eyes::ribbon: C+ reviewed

**Comment by jjcoffee** [comment] 2023-09-29 12:24
@ZhenjaHorbach Hmm I'm not sure what the expected behaviour is when creating a task. It does autolink there too at the moment (unless that's a separate bug :smile:) so I think I would err on the side of making it copyable (as links generally are in the app).

**Comment by alexpensify** [comment] 2023-10-03 23:29
@jjcoffee any feedback for @ZhenjaHorbach's latest update? Thanks!

**Comment by jjcoffee** [comment] 2023-10-04 09:22
@alexpensify Ah sorry, I was thinking we'd just handle this on the PR so was just waiting for @youssef-lr to assign @ZhenjaHorbach! I don't feel too strongly either way, currently we have the same behaviour in manual money requests so maybe for consistency we just leave the tooltip out. Fielding some opinions [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1696411224802679), but I think we're ready to assign regardless as we can easily change this on the PR!

**Comment by alexpensify** [comment] 2023-10-04 22:27
Thanks @jjcoffee for starting the Slack convo.

**Comment by jjcoffee** [comment] 2023-10-05 08:00
Okay there weren't really any bites on Slack so I think we'll go ahead with the assumption that it's okay for the link to have the copy tooltip. If it's decided in future not to autolink in `MenuItem` then the tooltip will magically disappear anyway!

@youssef-lr Please could you assign @ZhenjaHorbach, thanks!

**Comment by alexpensify** [comment] 2023-10-06 22:40
@youssef-lr we need the assignment so that @ZhenjaHorbach can carry on with the next steps. Thanks!

**Comment by youssef-lr** [comment] 2023-10-06 22:42
Done!

**Comment by alexpensify** [comment] 2023-10-09 17:24
@ZhenjaHorbach -- there is a more recent discussion going on in Slack. Please jump in there before starting this PR. Thanks!

**Comment by alexpensify** [comment] 2023-10-11 20:48
I've followed up in the Slack thread to confirm if we need to make changes here or close this GH.

**Comment by jjcoffee** [comment] 2023-10-12 08:07
@alexpensify Sorry, should've posted an update - we've [settled](https://github.com/Expensify/App/pull/28951#issuecomment-1753435337) on there needing to be markdown rendering correctly in all these views (Confirm Task, Task detail, Private Notes), so we're good to keep this open. Just waiting for @youssef-lr to approve the PR!

**Comment by alexpensify** [comment] 2023-10-12 20:12
Whoops - thanks for calling that out because I didn't check the PR 🤦🏼

**Comment by alexpensify** [comment] 2023-10-13 17:30
I reached out in Chat to see if we can get the review soon.

**Comment by jjcoffee** [comment] 2023-10-26 08:23
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27736
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27769#issuecomment-1727777324
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression test proposal**

1. Open any chat
2. Click the + and "Assign task"
3. Enter a title and insert the following in the description field
```
https://new.expensify.com/
~https://new.expensify.com/~
# https://new.expensify.com/
```
5. Save the description and verify that the `Confirm Task` screen correctly renders the markdown and links.
6. Right click any of the links in the description and verify that the "Copy URL to clipboard" tooltip appears
7. Save the task.
8. On the task detail screen, verify the same as in steps 5 and 6.

Do we agree 👍 or 👎

**Comment by alexpensify** [comment] 2023-10-26 22:16
Here is the payment summary: 

-  External issue reporter - @ayazhussain79 $50 
-  Contributor that fixed the issue - @ZhenjaHorbach $750 
-  Contributor+ that helped on the issue and/or PR - @jjcoffee $750  

Upwork Job: 

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is no urgency bonus but no penalty either since this GH required discussion and review on the right solution.

**Comment by alexpensify** [comment] 2023-10-26 22:17
@ayazalavi - I need your help to accept the offer in Upwork, looks like automation failed here.

**Comment by ayazhussain79** [comment] 2023-10-26 22:18
@alexpensify offer accepted, Thank you

**Comment by alexpensify** [comment] 2023-10-27 18:26
Closing - everyone has been paid and I've created the regression test request.

**Closed by alexpensify** 2023-10-27 18:26 UTC
Labels: External, Daily, Awaiting Payment
