### ISSUE TITLE
[HOLD for payment 2023-10-23] [$500] user have to press two times on Use current location

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29100] opened 2023-10-09 15:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.79-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696574867561759

## Action Performed:
1. click on FAB and select Request money
2. go to distance tab
3. click on Start
4. enter any character which will suggest you location
5. click on Use current location
## Expected Result: 
current location should be applied as start point
## Actual Result: 
on first click suggestion closes and on second click current location applies

## Workaround:
UnKnown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/6d22bc02-bda8-4d65-b72f-d95f1c7d2ff3

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

https://github.com/Expensify/App/assets/38435837/1e4c3b13-0b4d-4ad1-907b-2a7ac65f2ff5

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

https://github.com/Expensify/App/assets/38435837/226bb51e-aeca-4418-ae31-76c3599ac1f8

https://github.com/Expensify/App/assets/38435837/d5489cd7-7756-43b9-a02b-197a6b8a82d5

<details>
<summary>MacOS: Desktop</summary>

</details>

https://github.com/Expensify/App/assets/38435837/72c2ea95-9265-40be-bd0c-9dc6ae7f4bb0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013503150cd677c799</li>
        <li>Upwork Job ID: 1711409892031705088</li>
        <li>Last Price Increase: 2023-10-09</li>
<li>Automatic offers: </li>
<ul>
<li>graylewis | Contributor | 27142852</li>
<li>gadhiyamanan | Reporter | 27142856</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-10-09 16:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The user has to press the Use current location button twice before the button actually registers a click if the address search suggestions are visible.

### What is the root cause of that problem?
The dismissal of the address search suggestions moves the button which prevents the click event from being registered.

### What changes do you think we should make in order to solve the problem?
Use a fixed position for the button.

### What alternative solutions did you explore? (Optional)
None.

**Comment by graylewis** [comment] 2023-10-09 16:52
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The location button is not clickable because it moves when the autocomplete receives the onBlur event.

### What is the root cause of that problem?
Because onBlur is processed before onClick (causing the button to move), the UserCurrentLocationButton never receives the onClick event.

### What changes do you think we should make in order to solve the problem?
Since onMouseDown is processed before onBlur, we can use onMouseDown (desktop) and onTouchStart (mobile) to intercept the action and prevent the onBlur event from propagating. 

`onMouseDown={(e) => {e.preventDefault()}}`
`onTouchStart={(e) => {e.preventDefault()}}`

This allows the UserCurrentLocationButton to be triggered without any layout changes and without interfering with the operation of the autocomplete field. 

### What alternative solutions did you explore?
N/A

**Comment by burczu** [comment] 2023-10-11 11:22
[The proposal](https://github.com/Expensify/App/issues/29100#issuecomment-1753349612) from @graylewis does the trick and I think we can proceed with it.

Solutions [proposed](https://github.com/Expensify/App/issues/29100#issuecomment-1753295026) by @akinwale involve relocation of the `Use current location` button which, I think, is something we would like to avoid.

🎀 👀 🎀 C+ reviewed

**Comment by graylewis** [comment] 2023-10-11 17:41
I'm expecting to submit a PR in the next few hours for this issue.

**Comment by CortneyOfstad** [comment] 2023-10-18 19:43
Heading OoO until Oct. 25 so reassigning this so it can be paid on time 👍

**Comment by abekkala** [comment] 2023-10-19 14:49
### PAYMENTS TO BE MADE OCT 23

- @gadhiyamanan [$50] (Reporter)
- @graylewis requires [$500 = $250 Bonus] (Contributor)
- @burczu does not require payment (Contractor)

**Comment by abekkala** [comment] 2023-10-23 21:05
@burczu can you complete the checklist above?

**Comment by abekkala** [comment] 2023-10-23 21:07
@gadhiyamanan payment made and contract ended  - thank you! 🎉 

@graylewis payment made and contract ended  - thank you! 🎉

**Comment by abekkala** [comment] 2023-10-27 15:04
@burczu can you complete the checklist above?

**Comment by abekkala** [comment] 2023-10-30 17:38
@burczu can you complete the checklist above?

**Comment by burczu** [comment] 2023-10-31 11:45
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: **I don't think that any other PR introduced this issue. It was done this way since the beginning.**
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **n/a**
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **n/a**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I don't think we need regression tests here - the bug wasn't impactful and didn't block any flow in the App. It was just inconvenient behaviour for the user so it was just UX fix.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@CortneyOfstad] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2023-10-31 16:00 UTC
Labels: External, Daily, Awaiting Payment, Bug
