### ISSUE TITLE
[HOLD for payment 2024-01-24] [$500]  Share code/Get $250 - Copy referral link is not activated using the Tab button

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32080] opened 2023-11-28 00:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Share code -> Get $250
4. Using the Tab button, move around the page

## Expected Result:
Copy referral link activated using the Tab button

## Actual Result:
Copy referral link is not activated using the Tab button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4204faf6-f2ae-4d1a-8548-6327977f619f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ee2e7fab6291ccf2</li>
        <li>Upwork Job ID: 1731398508571623424</li>
        <li>Last Price Increase: 2023-12-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27998178</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by DylanDylann** [comment] 2023-11-28 03:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Share code/Get $250 - Copy referral link is not activated using the Tab button

### What is the root cause of that problem?
- Currrently, the wrapper component of the "Coppy referral link" button is a Text, so it can not be focus by using Tab.

### What changes do you think we should make in order to solve the problem?
- We can update:
https://github.com/Expensify/App/blob/61ed9009dfcb1882ac540550191777e143575bd8/src/components/Pressable/PressableWithDelayToggle.tsx#L95
to:
```
        <PressableView  accessible accessibilityRole="button"  tabIndex={0}   ... />
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by mountiny** [comment] 2023-11-28 13:45
Not a blocker, same happens in production
https://github.com/Expensify/App/assets/36083550/ada6e6b7-c30e-4abf-a4e5-d410139cd20d

**Comment by DylanDylann** [comment] 2023-12-03 04:46
@robertjchen I just pdated my [proposal](https://github.com/Expensify/App/issues/32080#issuecomment-1829011804)

**Comment by robertjchen** [comment] 2023-12-03 19:42
Thanks, opening it up for a C+ review 👀

**Comment by dawoodtrumboo** [comment] 2023-12-04 03:12
**Proposal :** Ensuring Keyboard Accessibility of Custom Pressable Component

The objective is to modify the PressableWithDelayToggle custom component to ensure it is focusable via keyboard navigation, thereby enhancing accessibility in compliance with web standards and best practices.

**Technical Approach:**
The proposal outlines the following technical steps to address the keyboard focus issue:
1. Review of Current Implementation: Conduct a thorough review of the PressableWithDelayToggle component, with a focus on the properties affecting accessibility.
2. Ensuring ARIA Compliance: Appropriate ARIA (Accessible Rich Internet Applications) attributes will be added or adjusted to ensure that the custom component's role, state, and focusability are clearly communicated to assistive technologies.
3. Handling Ref Forwarding: The handling of refs will be assessed to ensure they are being forwarded correctly within the component to maintain focus management functionality.
4. Keyboard Event Listeners: Implement or enhance keyboard event listeners to ensure that actions tied to the custom component can be triggered via keyboard inputs.
5. Testing Across Browsers and Devices: Perform comprehensive testing across various browsers and devices to ensure consistent behavior in terms of focusability and keyboard navigation.
6. Documentation: Update inline documentation and comments to reflect the changes made for accessibility improvements.
7. Code Review: Prepare the code for review, ensuring it adheres to the project's coding standards and guidelines, and collaborate with the project maintainers for any necessary iterations.

**Deliverables:**

1. A revised version of the PressableWithDelayToggle component with improved keyboard accessibility.
2. Documentation of the changes made and their impact on accessibility.
3. Testing report showing the component's behavior in different browsers and devices.


**Upon acceptance, I will await further instructions regarding the submission process on Upwork and proceed with the implementation following the accepted practices of the Expensify/App GitHub repository.**

**Comment by dawoodtrumboo** [comment] 2023-12-04 03:24
Contributor details
Your Expensify account email: mohammaddawoodtrumboo@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~015a16b5a5982cca92

**Comment by DylanDylann** [comment] 2023-12-04 13:30
@situchan I am waiting @robertjchen review the proposal

**Comment by situchan** [comment] 2023-12-04 13:34
I know but lots of accessibility issues (i.e. Tab or Enter key) were closed in the past as no priority

**Comment by DylanDylann** [comment] 2023-12-04 13:37
@situchan Oh. I do not know about that. But the accessibility issue is not the main of this issue.

**Comment by dawoodtrumboo** [comment] 2023-12-04 13:57
Can't we access this code to analyse it more deeply?  because when I tried to run this repository on my system, it opened some other version of the expensify.

**Comment by robertjchen** [comment] 2023-12-07 14:08
> I know but lots of accessibility issues (i.e. Tab or Enter key) were closed in the past as no priority

@situchan Interesting, can you raise those on Slack for discussion, maybe we can start looking addressing those (if they still exist)? 🙏 

For now, let's move forward with this 👍

**Comment by DylanDylann** [comment] 2023-12-11 04:41
Open the PR today

**Comment by DylanDylann** [comment] 2023-12-11 11:15
@narefyev91 PR https://github.com/Expensify/App/pull/32790 is ready to review

**Comment by DylanDylann** [comment] 2024-01-02 09:42
@robertjchen Couold you help to process this issue?

**Comment by robertjchen** [comment] 2024-01-04 22:28
@greg-schroeder Could you please assist with the next steps here now that the PR has been merged and deployed? Thanks!

**Comment by robertjchen** [comment] 2024-01-09 10:14
bump @greg-schroeder 🙏

**Comment by robertjchen** [comment] 2024-01-19 00:44
bump @greg-schroeder 🙏

**Comment by greg-schroeder** [comment] 2024-01-24 18:20
Okay looks like this is ready to pay

**Comment by greg-schroeder** [comment] 2024-01-24 18:21
C: @DylanDylann 
C+: @narefyev91 

both $500

**Comment by greg-schroeder** [comment] 2024-01-24 21:36
The upwork job closed for inactivity so I have to create a new one

**Comment by greg-schroeder** [comment] 2024-01-24 21:40
offer sent @DylanDylann - also I forgot @narefyev91 you're CS, right?

**Closed** 2024-01-24 21:41 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
