### ISSUE TITLE
[HOLD #39616][$250] [Track Tax] - Tax does not show up in the Expense report when created offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40051] opened 2024-04-10 23:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/39723
## Action Performed:
Prerequisites:
Create WS collect, include Tax, add 5% rate.
1. Open https://staging.new.expensify.com/
2. Navigate to a workspace room
3. Switch on offline
4. Create and send to the IOU room with 5% tax.
5. Navigate to the IOU details

## Expected Result:
The tax should appear in the IOU report when created offline

## Actual Result:
Tax does not show up in the IOU report when created offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/58c95119-7e89-4b79-9805-cf93f8223cb4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d25bb36f4e169f12</li>
        <li>Upwork Job ID: 1779966508736303104</li>
        <li>Last Price Increase: 2024-04-15</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-10 23:22
@abekkala  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-10 23:23
We think that this bug might be related to #wave-collect - Release 1

**Comment by nkdengineer** [comment] 2024-04-11 09:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Tax - Tax does not show up in the IOU report when created offline
### What is the root cause of that problem?
- In [requestMoney](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/actions/IOU.ts#L2258) the [onyxData](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/actions/IOU.ts#L2296) does not contain the ```taxCode``` and ```taxAmount```, that leads to there is no tax data shown in offline mode.
### What changes do you think we should make in order to solve the problem?
- We need to call [getMoneyRequestInformation](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/actions/IOU.ts#L2297C9-L2297C35) with additional params, ```taxAmount``` and ```taxCode```. 
- Then, in [getMoneyRequestInformation](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.ts#L1111), call [buildOptimisticTransaction](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/actions/IOU.ts#L1190) with these params, ```taxAmount``` and ```taxCode```.
- Then in [buildOptimisticTransaction](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/TransactionUtils.ts#L86), add these two params to [here](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/TransactionUtils.ts#L116)

- One note is that we need to make sure that the optimistic ```taxAmount``` is the same as the ```taxAmount``` returned by BE. To do that, we need to format the ```taxAmount``` before passing it to [buildOptimisticTransaction](https://github.com/Expensify/App/blob/260a7de64b083e82d3a79ad8b48d94b4a32885c2/src/libs/actions/IOU.ts#L1190)
```
    let optimisticTransaction = TransactionUtils.buildOptimisticTransaction(
        ReportUtils.isExpenseReport(iouReport) ? -amount : amount,
        ...
        taxCode,
         ReportUtils.isExpenseReport(iouReport) ? -taxAmount : taxAmount,
    );
```
### What alternative solutions did you explore? (Optional)

- NA

**Comment by abekkala** [comment] 2024-04-15 20:15
@jayeshmangwani it looks like we've already received a couple proposals for review! 🎉

**Comment by jayeshmangwani** [comment] 2024-04-17 10:29
Will review proposals today

**Comment by jayeshmangwani** [comment] 2024-04-17 22:19
Thanks @GandalfGwaihir  and @nkdengineer  for the proposals 

Both proposals are correct, and RCA is on point. @nkdengineer  has added some extra details than @GandalfGwaihir  for editing taxCode, but that is additional to the original issue. @GandalfGwaihir proposed a working solution first for the described issue, so in this case, we can go with user @GandalfGwaihir 's [Proposal](https://github.com/Expensify/App/issues/40051#issuecomment-2048776595)

🎀 👀 🎀 C+ reviewed

**Comment by trjExpensify** [comment] 2024-04-18 02:31
👋 Just a heads up to make sure we distinguish between `iouReport` and `expenseReport` in the title and OP of the issue. A request to a workspace goes onto an `expense` report. Tax tracking is a feature of workspaces. You can't track tax on requests to individuals, that go on `iou` Reports.

**Comment by trjExpensify** [comment] 2024-04-18 02:31
CC: @MonilBhavsar as it's Track Tax related.

**Comment by nkdengineer** [comment] 2024-04-18 02:38
@arosiclair More about this C+ [comment](https://github.com/Expensify/App/issues/40051#issuecomment-2062557478): We have addtional bugs related to the tax flow in offline mode (mentioned in my proposal), should we plan to fix it in this issue? If not, I think we can go with the [selected proposal](https://github.com/Expensify/App/issues/40051#issuecomment-2048776595)

**Comment by MonilBhavsar** [comment] 2024-04-18 05:17
This is dupe of implementation issue - https://github.com/Expensify/App/issues/39616

**Comment by MonilBhavsar** [comment] 2024-04-18 15:19
Let's close it 👍

**Closed** 2024-04-18 15:55 UTC
Labels: External, Daily, Help Wanted, Bug
