### ISSUE TITLE
[HOLD for payment 2023-09-07] [$1000]  IOU - IOU content is not translated to Spanish and inconsistent message after kogout

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21959] opened 2023-06-30 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20446
## Action Performed:
1. Go to staging.new..expensify.com in English
2. Request money from account A to account B
3. Verify that, In the DM between A:B and LHN, the latest message displays as: "[account B's firstName] owes [amount]"
4. As account A, Go to Preferences -> Language, change to Spanish
5. Verify that, In the DM between A:B and LHN, the latest message displays as: "[account B's firstName] debe [amount]"
6. In accountB, click "Pay elsewhere" button
7. As account A, verify that, In the DM between A:B and LHN, the latest message displays as: "pagó [amount] de otra forma"
8. Go to Preferences -> Language, change to English
9. Verify that, In the DM between A:B and LHN, the latest message displays as: "paid [amount] elsewhere"
10. Sign out and sign in again to account A
11. Verify that in DM and LHN, it shows as "paid [amount] elsewhere"

## Expected Result:
In Step 7, the message displayed in IOU report view and LHN is "pagó [amount] de otra forma"
In Step 11, in DM and LHN, it shows as "paid [amount] elsewhere"

## Actual Result:
In Step 7, the message displayed in IOU report view and LHN is "paid [amount] elsewhere".
In Step 11, in DM and LHN, it shows as "paid [amount]". The word "elsewhere" is missing. It only shows "paid [amount] elsewhere" after user opens IOU report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ef8a56cd-666c-4d06-bd13-b6c86620580c

![Bug6112092_IOU_in_English](https://github.com/Expensify/App/assets/78819774/927b136d-f418-47bf-acfc-d6634933069b)

![Bug6112092_After_logout_and_logging_back_in](https://github.com/Expensify/App/assets/78819774/9ed24396-f0db-4930-8257-77da0f2476d6)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198145f8879a9366b</li>
        <li>Upwork Job ID: 1676321404270100480</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 26237637</li>
</ul></li>
    </ul>
</details>

**Comment by sonialiap** [comment] 2023-07-04 20:05
Triaging to external

**Comment by sonialiap** [comment] 2023-07-17 17:46
- `Translation`: I cannot reproduce this any longer
- `The word "elsewhere" is missing`: the issue https://github.com/Expensify/App/issues/21894 was opened before this one so this report is a dupe

Since the first issue is no longer reproducible and the second is under a different issue, closing this out

**Comment by lanitochka17** [comment] 2023-08-01 13:47
Issue reproducible in Build 1.3.48-0. 

![Screenshot 2023-08-01 at 20 56 50](https://github.com/Expensify/App/assets/78819774/741e708a-5b38-4674-9783-810448967d43)

**Comment by madmax330** [comment] 2023-08-21 11:10
Job assigned, sorry for the delay, I was out sick last week

**Comment by sonialiap** [comment] 2023-09-08 12:40
Reviewer assigned Aug 22 6:48am
Review completed Aug 29 5:36pm

Four full business days = no time bonus

**Comment by sonialiap** [comment] 2023-09-08 13:13
Payments:
- @HezekielT fix $1000
- @aimane-chnaif review $1000

Upwork: https://www.upwork.com/jobs/~01f6188c02a39ab8b2

**Comment by sonialiap** [comment] 2023-09-19 07:32
My apologies! Payments sent

**Closed** 2023-09-19 07:33 UTC
Labels: External, Weekly, Awaiting Payment, Bug
