### ISSUE TITLE
[HOLD for payment 2023-09-20] [$1000] Workspace Bank Connections: resizing browser when entering Step 3 personal information triggers reload

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22035] opened 2023-07-02 01:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

- Open website and Click on Avatar to open the settings
- Click Workspaces > Any Workspace's name > Cards > Connect bank account > Connect manually (or Choose "Continue with setup" if you have already started with it)
- Reach 3rd step which is "Personal Information" that includes some inputs (First name, Last name, Date, ... etc)
- Resize your browser(should be less than 801px)

## Expected Result: 
Form should instantly resize and shouldn't reload 

## Actual Result:
Form throws a "we're taking a look at your information" interstitial and takes a while to reload

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3534d920-95b9-46d1-9881-ba2e8f852809

[screen-capture (34).webm](https://github.com/Expensify/App/assets/43996225/5e9fc2e9-03ba-4a75-a666-3090dc139e26)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688112326007589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0158fdd5240a39a3cb</li>
        <li>Upwork Job ID: 1676854347206664192</li>
        <li>Last Price Increase: 2023-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26550577</li>
<li>mahmudjontoraqulov | Reporter | 26550579</li>
</ul></li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-07-04 09:37
@MahmudjonToraqulov can you please break down the repo steps in more detail, listing every action and path needed to reproduce, thanks!

**Comment by MahmudjonToraqulov** [comment] 2023-07-04 11:16
> @MahmudjonToraqulov can you please break down the repo steps in more detail, listing every action and path needed to reproduce, thanks!

Hi @laurenreidexpensify. Of Course! 

## Action Performed:
1. Open website and Click on Avatar to open the settings
2. Click Workspaces > Any Workspace's name > Cards > Connect bank account > Connect manually (or Choose "Continue with setup" if you have already started with it)
3. Reach 3rd step which is "Personal Information" that includes some inputs (First name, Last name, Date, ... etc)
4. Resize your browser(should be less than 801px)

**Comment by mountiny** [comment] 2023-07-06 19:51
Put this on hold

**Comment by laurenreidexpensify** [comment] 2023-07-10 09:27
Continuing to hold on #20404

**Comment by laurenreidexpensify** [comment] 2023-07-19 13:18
Continuing to hold on https://github.com/Expensify/App/issues/20404

**Comment by laurenreidexpensify** [comment] 2023-07-31 10:39
Continuing to hold on https://github.com/Expensify/App/issues/20404

**Comment by laurenreidexpensify** [comment] 2023-08-18 13:34
Continuing to hold on https://github.com/Expensify/App/issues/20404 where the PR is still in review

**Comment by laurenreidexpensify** [comment] 2023-08-30 12:26
Continuing to hold on https://github.com/Expensify/App/issues/20404 where the PR is still in review

**Comment by laurenreidexpensify** [comment] 2023-09-07 12:01
@mountiny @parasharrajat looks like #20404 is deployed to prod for 7 days now, I'm taking off hold

**Comment by b4s36t4** [comment] 2023-09-07 16:45
Yes, all we need to add position absolute.

**Comment by b4s36t4** [comment] 2023-09-07 16:47
We all already have a override in onfido.css we can modify that. Or we can add a css height property on the element which is having

_onfido-mount_

**Comment by b4s36t4** [comment] 2023-09-07 16:48
Considering the issue, I feel adding position absolute is the way to go, just how onfido does with their mobile styling. Which won't raise any other css issues further.

**Comment by tgolen** [comment] 2023-09-07 17:02
I am 👍 for the proposal. I think I prefer the `100%` height approach better. Once you go down the `!important` path, it never ends!

**Comment by b4s36t4** [comment] 2023-09-07 17:09
Got it. @tgolen

**Comment by b4s36t4** [comment] 2023-09-07 17:41
Hey, @tgolen can you assign this to me, if you're ok with the proposal?!

**Comment by tgolen** [comment] 2023-09-07 17:55
Oh, sorry. I thought I did! My bad

**Comment by tgolen** [comment] 2023-09-07 17:56
As far as the reporting bonus, we could also consider splitting it between both people.

**Comment by b4s36t4** [comment] 2023-09-07 19:36
@parasharrajat @tgolen Raised PR here #26983

**Comment by MahmudjonToraqulov** [comment] 2023-09-08 10:06
Hey @parasharrajat @tgolen @b4s36t4 @laurenreidexpensify. The price for reporter role should be 250$ as it's created before 30th August. We already discussed about that on channel that the issues created before 30th August is eligible for 250$ payment.

**Comment by MahmudjonToraqulov** [comment] 2023-09-08 13:43
Thanks @parasharrajat. I didn't accept the offer for now.  Will you send another one or update it to 250$?

**Comment by laurenreidexpensify** [comment] 2023-09-20 08:34
Payment Summary

-  External issue reporter - @MahmudjonToraqulov - $250 - waiting for @MahmudjonToraqulov to accept job in Upwork  
-  Contributor that fixed the issue @b4s36t4 - $500 + 50% urgency bonus = $1000, paid in Upwork
-  Contributor+ that helped on the issue and/or PR - @parasharrajat - $500 + 50% urgency bonus = $1000, please request in Newdot

**Comment by b4s36t4** [comment] 2023-09-20 09:02
@laurenreidexpensify I think you've made wrong calculations here.

Bounty amount is 1000$ and 50% urgency bonus would become 1500$ right?

**Comment by b4s36t4** [comment] 2023-09-20 13:58
Bump on above question @laurenreidexpensify

**Comment by MahmudjonToraqulov** [comment] 2023-09-22 06:32
> Payment Summary
> 
> * External issue reporter - @MahmudjonToraqulov - $250 - waiting for @MahmudjonToraqulov to accept job in Upwork
> * Contributor that fixed the issue @b4s36t4 - $500 + 50% urgency bonus = $1000, paid in Upwork
> * Contributor+ that helped on the issue and/or PR - @parasharrajat - $500 + 50% urgency bonus = $1000, please request in Newdot

@laurenreidexpensify  I didn't accept the offer as it's 50$ as I said before. But didn't accept updated offer. Will you send new one pls? Thanks.

**Comment by laurenreidexpensify** [comment] 2023-09-24 09:57
@MahmudjonToraqulov we will pay the updated fee of $250 in Upwork, please accept the offer as it is now even if it's $50, it will be adjusted before payment

**Comment by laurenreidexpensify** [comment] 2023-09-24 09:58
Updated Summary - 

- External issue reporter - @MahmudjonToraqulov - $250 - waiting for @MahmudjonToraqulov to accept job in Upwork
- Contributor that fixed the issue @b4s36t4 - $1000 + 50% urgency bonus = $1500, paid in Upwork
- Contributor+ that helped on the issue and/or PR - @parasharrajat - $1000 + 50% urgency bonus = $1500, please request in Newdot

**Comment by b4s36t4** [comment] 2023-09-24 14:51
@laurenreidexpensify I'm sorry that I'm a bit confused here. I have only got 1000$ in my upwork contract could please have a look at it? I don't see any new upwork jobs or any contract updates or whatsoever. Thanks!

**Comment by b4s36t4** [comment] 2023-09-24 14:55
Sorry received, Thanks :). Missed it.

**Comment by MahmudjonToraqulov** [comment] 2023-09-25 03:31
> @MahmudjonToraqulov we will pay the updated fee of $250 in Upwork, please accept the offer as it is now even if it's $50, it will be adjusted before payment

@laurenreidexpensify I accepted the offer.

**Comment by laurenreidexpensify** [comment] 2023-09-26 05:37
Update: Paymens have been issued in Upwork, Rajat will request in NewDot.

**Closed by laurenreidexpensify** 2023-09-26 05:37 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-09 16:57
$1,500 payment approved for @parasharrajat based on BZ summary.
