### ISSUE TITLE
[$500] Blank screen appears after deleting money request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36605] opened 2024-02-15 16:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @MonilBhavsar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708001690787499

## Action Performed:

1. Open the app
2. Navigate to a workspace chat without previous IOUs
3. Send 1 money request
4. Open money request detail screen
5. Tap three dots and delete a money request

## Expected Result:
Empty chat view should appear

## Actual Result:
Blank screen appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e153921d-b741-47a5-abbc-864911b2e0ed

https://github.com/Expensify/App/assets/38435837/da42043d-f472-454a-a117-a8cdb1dbf450

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bcf8cb6b42d5cf14</li>
        <li>Upwork Job ID: 1758164510632783872</li>
        <li>Last Price Increase: 2024-02-15</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-15 16:48
and dupe of https://github.com/Expensify/App/issues/36518

**Comment by abekkala** [comment] 2024-02-15 18:08
@MonilBhavsar I'll close this one out as the fix for the GH issue already in place should resolve.

**Closed by abekkala** 2024-02-15 18:08 UTC
Labels: External, Daily, Help Wanted, Bug
