### ISSUE TITLE
Emojis are pasted like images when copied and pasted from other apps (e.g Slack, Gmail) 

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#4888] opened 2021-08-27 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Copy text from Slack which includes emojis (or text with image)
2. Paste the text in a NewDot conversation and see that the emoji is treated as image attachment and there is no text

## Expected Result:
Since we currently do not have option to send text and image at the same time and we are still in works of adding `colon-coded` emojis, we should strip the image/emoji from the clipboard and only paste the text. 

More complex solution will be coming in next iterations of the `App`

## Actual Result:
Emoji is pasted as an image. (@parasharrajat gives more information on this [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1630080141069200?thread_ts=1630077768.065600&cid=C01GTK53T8Q) and text is not added to the Compose box

## Workaround:
There is no workaround, we cannot paste both text and image at the same time. For now, we need to choose and that is to only copy paste text or only image.

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.0.88-2

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

![image](https://user-images.githubusercontent.com/44479856/131177570-ff79b3b1-0ec9-468a-a0a9-78de7a1cb3a6.png)

**Expensify/Expensify Issue URL:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

___ 
From @mallenexpensify https://expensify.slack.com/archives/C01GTK53T8Q/p1630077768065600

> Emoji aren't pasting correctly into NewDot.   When trying to paste a sentence that contains an emoji, only the emoji shows up in the Send attachment screen. More deets in Thread
> Tested by sending this sentence - sending message with :heart:
> Issue exists when copy/pasting from Slack and gmail into NewDot Desktop Version 1.0.86-11. Didn't seem to be happening from Google Docs.  My hunch is has to do with the size of the emoji, in NewDot it appears we keep emoji the same size as other characters while it seems to be enlarged in Slack. If you paste from the compose window in Slack it works but not once the message in Slack has been sent

**Comment by parasharrajat** [comment] 2021-08-30 16:45
I think there is already a proposal here so I don't need to propose here and looks similar to what I mentioned on the slack thread. cc: @mountiny

**Comment by mountiny** [comment] 2021-09-02 15:04
The option 1. seems good to me, definitely the easier and more straightforward option to achieve. I will leave this to @tgolen to decide if the proposal is sufficient as he is on the CME team 🙌 or let me know if I should take over, I am looking into joining CME.

**Comment by tgolen** [comment] 2021-09-02 15:13
I agree with @mountiny but I have some concerns about the option 1 proposal. It's not a complete proposal and it needs to be more detailed since it's just giving a broad overview of the approach

> If there's a use-case of retaining embedded images then we won't be able to use this approach.

I think this could be dangerous and we need to have a larger discussion and consensus about this change in behavior.

**Comment by mananjadhav** [comment] 2021-09-02 15:24
> It's not a complete proposal and it needs to be more detailed since it's just giving a broad overview of the approach
Okay, I'll send in a detailed approach later today.

> I think this could be dangerous and we need to have a larger discussion and consensus about this change in behavior.

I agree.  Hence I highlighted this part.

**Comment by stitesExpensify** [comment] 2021-09-02 18:25
We're putting [this](https://github.com/Expensify/App/issues/4324) on hold until a doc comes out for it. Should we also put this on pause since solution 1 is going to convert `:grimacing:` into emojis? Or should we just keep this open and for now paste the "colon code" version for now? Another option would be to just parse out the emoji completely and paste nothing for now.

**Comment by mountiny** [comment] 2021-09-03 13:15
@stitesExpensify I would lean towards parsing the emoji out complete for now to fix this and enable users to copy/paste texts with emojis, which is now impossible. Then have a follow up issue to convert them to "colon code" once that is out.

**Comment by mananjadhav** [comment] 2021-09-03 14:44
Well @mountiny in that case with Text + Image as well we are only showing the Image and discarding the text. Are considering showing the text in that scenario as well?

**Extension to Proposal 1**

```
if (types.includes(TEXT_HTML)) {
     const plainText = event.clipboardData.getData(`text/plain`); // this will give me Hello World `:grinning:`
     const pastedHTML = event.clipboardData.getData(TEXT_HTML);
     
```

`plainText` can help me know if there's an Emoji that exists.

```
.then((x) => {
                        const extension = IMAGE_EXTENSIONS[x.type];
                        if (!extension) {
                            throw new Error(this.props.translate('textInputFocusable.noExtentionFoundForMimeType'));
                        }

                        return new File([x], `pasted_image.${extension}`, {});
                    })
                    .then(this.props.onPasteFile) // Change this to following
```

```
    .then((file) => {
           this.handlePastedHTML(stripImagesFromHTML(pastedHTML));
           if(!emojiExist(plainText)) {
                return this.props.onPasteFile(file);  // if we want to retain images but not emoji
           }
    });

```

Helper functions:
```
function emojiExist(text) {
   return text.matches(/(:[^\s:]+(?:::skin-tone-[2-6])?:)/);

}

function stripImageTags(html) {
   return html.replace(/<img[^>]*>/g,"");
}
```

**Comment by tgolen** [comment] 2021-09-03 19:00
@mountiny I agree with you about splitting this up into separate issues. 

@mananjadhav Thank you for the more detailed proposal! Just to confirm, your solution skips the parsing of the colon-emoji for now, and still allows for embedded images? If so, then 👍  It's just not super clear to me that this is the result of the proposal.

**Comment by mananjadhav** [comment] 2021-09-04 04:51
>  this.handlePastedHTML(stripImagesFromHTML(pastedHTML));
>            if(!emojiExist(plainText)) {
>                 return this.props.onPasteFile(file);  // if we want to retain images but not emoji
>            }

@tgolen  This particular line checks if the text contains Emoji. If it doesn't then it proceeds for showing the attachment Popup. Hope this clarifies.


> Well @mountiny in that case with Text + Image as well we are only showing the Image and discarding the text. Are considering showing the text in that scenario as well?

@tgolen @mountiny Can you help me clarify this one? The text will still not be pasted for Text + Image combination.

**Comment by tgolen** [comment] 2021-09-07 15:11
I'm going to discuss with @mallenexpensify and @mountiny in order to get a better idea of the problem so that I can more accurately answer your questions and grade the proposal. Thanks for being patient on this!

**Comment by mananjadhav** [comment] 2021-09-07 15:57
Sure. Thanks a lot. I can then accordingly update the proposal to accommodate any new changes

**Comment by mountiny** [comment] 2021-09-08 10:30
As per discussion with @tgolen in Slack, I will take over this issue as CME 🎉  (one of my first, excited to work with you @mananjadhav 😊 )

We have clarified internally, what the problem was and as of now, we are kind of forced to choose not ideal solution _now_ just to make copy/pasting work (as more complex solution is being worked on for next versions of the app)

Since currently we are not supporting composing a message with image (such as on Slack) and it is in our roadmap for next iterations, we think the best thing to do right now is to strip the image/emoji from the clipboard contents whenever there is text+emoji found in the clipboard.

> Can you help me clarify this one? The text will still not be pasted for Text + Image combination.

@mananjadhav I am very sorry for my misleading comment I have left above, I see what you meant now and what I wrote [here](https://github.com/Expensify/App/issues/4888#issuecomment-912531198) has been confusing. I have clarified it in the comment there, but I will do so here as well just for sake of understanding each other correctly.

What we want to achieve now is to paste only text whenever there is _**some**_ text present in the clipboard, cutting out any images/emojis. Keep the pasting functionality for images/files as it is now if it is is purely image/file.

Please, let me know if that is clear enough and don't hesitate to ask for further clarifications.

Could you please update the proposal once more now knowing we are all on the same page? Thank you very much 🙌

**Comment by mananjadhav** [comment] 2021-09-08 11:20
Thanks, @mountiny in taking this time and making an evaluated decision. I just have to strip some code from my previous proposal. The rest of it will work anyway. I'll update my proposal within a few hours

**Comment by mananjadhav** [comment] 2021-09-08 13:53
@mountiny Glad to be working with you.

**Updated Proposal**
Here's what is expected now:
1. A single Image/File/Emoji will be handled as an attachment along with the current popup and then Send button
2. A combination of Text + Image/Emoji will retain the text portion only. We'll strip the image/emoji part from the message.

Here's what I'll propose, in `TextInputFocusable`

```
handlePaste(event) {
  const {files, types} = event.clipboardData;
  const TEXT_HTML = 'text/html';

  // If paste contains files, then trigger file management
  if (files.length > 0) {
    // Prevent the default so we do not post the file name into the text box
    event.preventDefault();
    this.props.onPasteFile(event.clipboardData.files[0]);
    return;
  }

  // If paste contains HTML
  if (types.includes(TEXT_HTML)) {
    const pastedHTML = event.clipboardData.getData(TEXT_HTML);
    event.preventDefault();
    // Manan:  Here we had the logic of `embeddedImages` which we can remove.
    this.handlePastedHTML(this.stripImageTags(pastedHTML));
  }
}

// Add a function to strip `img` tags.
stripImageTags = html => html.replace(/<img[^>]*>/g, '');

```

Basically, there's a whole block start with `domParser` and `embeddedImages` that we need to remove. Please let me know if you need any clarification.

**Comment by mountiny** [comment] 2021-09-09 10:16
@mananjadhav Thank you for updating the proposal.

It seems to me like it should be good for our purpose here, but I am worried about regressions being associated with such a change (omitting quite big blocks of code). Can you please make sure the classic image/file copy/pasting works as expected with these proposed change?

If that will be the case, I am happy to proceed with you proposal!  

Thanks for checking this out.

**Comment by mountiny** [comment] 2021-09-09 10:40
@mananjadhav Actually, I just thought of a potential regression.

If we have an image in the current chat and we do secondary click to bring up the option modal, we can select `Copy to clipboard`. 
![image](https://user-images.githubusercontent.com/36083550/132671375-283045de-bc1a-4091-9eed-ed188f4872de.png)

When you paste that back into the Compose box, it is pasted as img tag: 

![image](https://user-images.githubusercontent.com/36083550/132671348-26884cd7-d82f-4ef4-9c8b-5555920d7e50.png)

We need to make sure our logic will interpret this as an image. I would assume if the message is _**only**_ image tag, then we still want to parse the image (there is no other text related to it) and this is expected way how users will copy/paste the images between the chats.

What do you think of this? Would you be able to update your proposal to accommodate for this? Thank you 🙌

**Comment by mananjadhav** [comment] 2021-09-09 11:10
@mountiny Thanks for reviewing. I'll answer both your questions:


> It seems to me like it should be good for our purpose here, but I am worried about regressions being associated with such a change (omitting quite big blocks of code). 

I agree we'll test it thoroughly.

> Can you please make sure the classic image/file copy/pasting works as expected with these proposed change?

I'll have a screencast for this scenario specifically. If you checkout `handlePaste` event, the following block takes care of just image/file.

```
// If paste contains files, then trigger file management
  if (files.length > 0) {
      // Prevent the default so we do not post the file name into the text box
      event.preventDefault();
      this.props.onPasteFile(event.clipboardData.files[0]);
      return;
  }
```

**We won't be removing this block**



> @mananjadhav Actually, I just thought of a potential regression.
> 
> If we have an image in the current chat and we do secondary click to bring up the option modal, we can select `Copy to clipboard`.
> ![image](https://user-images.githubusercontent.com/36083550/132671375-283045de-bc1a-4091-9eed-ed188f4872de.png)
> 
> When you paste that back into the Compose box, it is pasted as img tag:

This isn't a regression but the current limitation of our Copy to Clipboard functionality. We don't get the image/attachment as a Blob, rather a <img> string when we paste from the clipboard.  We're tracking this as a separate issue here. https://github.com/Expensify/App/issues/4629

I don't think it would be a part of this scope. I hope it makes sense?

**Comment by mountiny** [comment] 2021-09-09 15:48
@mananjadhav Thanks for answering the concerns. I know we won't be removing the block for handling pasting of files, but I was worried about the other scenarios for which the current code is in place.

Looking forward the PR and we will have to make sure to test this thoroughly 🎉

**Comment by mananjadhav** [comment] 2021-09-09 15:52
@mountiny then should I assume that I am assigned this and get started on the PR?

**Comment by mountiny** [comment] 2021-09-09 15:55
@mananjadhav You shall not assume anymore (sorry about the confusion, still learning this process).

@mallenexpensify Can you please hire Manan on Upwork for this job? 🙏

**Comment by parasharrajat** [comment] 2021-09-09 16:19
Sorry, I am late for the party, I was out on vacation. 

@mountiny 
Is the decision to testify the embedded images (`img` tags in HTML)?  Specifically, asking! all images?

#### **Then I propose**

Then we modify our ExpensiMark Html to MD parser and convert all the `img` tags to attached alt tags.

This is the default behaviour of the browser and thus If you check the copied emoji from Slack the same thing will be found in the alt tag. This is what WhatsApp follows. I think it should be the case.


```BASH
<br class="Apple-interchange-newline">

<img src="https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f638@2x.png" aria-label="smile cat emoji" 

alt=":smile_cat:"

 data-stringify-type="emoji" 

data-stringify-emoji=":smile_cat:" style="box-sizing: inherit; overflow: hidden; position: absolute; top: 10.8px; object-fit: contain; height: 22px; width: 22px; margin-top: -11px; color: rgb(29, 28, 29); font-family: Slack-Lato, appleLogo, sans-serif; font-size: 15px; font-style: normal; font-var...
```

**Comment by mananjadhav** [comment] 2021-09-09 16:31
> This will then paste the text as say: Hello World :grinning: which can then be converted to an emoji very easily. I had raised an issue to allow code-based emoji #4324

I had proposed this earlier here but I guess we decided to split it into two issues and for now remove the image. Hence I recommended the strip Images approach.

**Comment by parasharrajat** [comment] 2021-09-09 16:33
Then you don't need to strip `img` tags manually. Expensimark will take care of it.

**Comment by mallenexpensify** [comment] 2021-09-09 16:43
@mananjadhav , can you submit a proposal then I'll hire you? https://www.upwork.com/jobs/~01277425d12d2826ab
Thanks

**Comment by mananjadhav** [comment] 2021-09-09 16:49
@mallenexpensify Done.

**Comment by mallenexpensify** [comment] 2021-09-09 17:09
Hired @mananjadhav in Upwork!

**Comment by mountiny** [comment] 2021-09-09 18:37
@parasharrajat Thank you for your thoughts here!

We have decided to go the easiest way ahead now to enable pasting in texts from Slack and others. The issue for introducing colon-coded emojis already exists (I think Manan linked it above).

**Comment by mallenexpensify** [comment] 2021-09-10 00:55
tbc.... 
> introducing colon-coded emojis already exists (I think Manan linked it above).
This is something we've been discussing internally since the very beginning, like 9 months ago.  It wouldn't be available for a reporting bonus.

**Comment by mananjadhav** [comment] 2021-09-13 17:46
@mountiny PR raised, testing in progress.

**Comment by mountiny** [comment] 2021-09-14 11:03
@mananjadhav Thanks for the update! Let us know how it goes in the PR.

**Comment by kadiealexander** [comment] 2021-09-16 04:13
Hi @mananjadhav, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

**Comment by mountiny** [comment] 2021-09-16 13:43
As per a discussion in Slack here and in a light of new findings about this problem (as it might get very messy and the solution  might not be platform-agnostic), we have decided to do nothing about this as this problem is not considered to be a blocker and instead wait for a more complex solution with `:colon-coded:` emojis, which is in progress internally.

I will follow up with details how to handle this issue soon!

**Comment by mountiny** [comment] 2021-09-16 15:06
As discussed before, we will not proceed with solving this particular issue as it would be merely a temporary fix. 

Thank you very much for your time and help working on this @mananjadhav and @parasharrajat. 

@mallenexpensify could you please pay Manan on Upwork and we can then close this issue once paid!

**Comment by mountiny** [comment] 2021-09-17 12:20
@mallenexpensify bump on this one, please, if you get around to it  🚀 Thank you very much 🙏

**Comment by mallenexpensify** [comment] 2021-09-18 00:09
Thanks @mananjadhav , paid in Upwork, closing...

**Closed by mallenexpensify** 2021-09-18 00:09 UTC
Labels: Exported, External, Engineering, Weekly, n6-hold
