### ISSUE TITLE
[HOLD for payment 2023-08-02] [$250] Migrate index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16138] opened 2023-03-20 08:33 UTC
### Filenames
- [ ] [src/components/DatePicker/index.js](https://github.com/Expensify/App/blob/main/src/components/DatePicker/index.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e1cb4c2da152efa</li>
        <li>Upwork Job ID: 1686847396210348032</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 25912631</li>
</ul></li>
    </ul>
</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:52
I'd like to work on this issue

**Comment by s-alves10** [comment] 2023-06-06 10:24
I'd love to work on this.

**Comment by marcaaron** [comment] 2023-06-26 18:24
Taking this one off HOLD.

**Comment by mejed-alkoutaini** [comment] 2023-07-11 19:00
I'm able to work on this if needed!

**Comment by shubham1206agra** [comment] 2023-07-26 16:06
@marcaaron Since the PR was reverted. Can I try it converting this functional component?

**Comment by marcaaron** [comment] 2023-07-26 20:20
It's up to @srikarparsi really. Need any help with this @srikarparsi?

**Comment by srikarparsi** [comment] 2023-07-26 20:26
Hi @shubham1206agra, yes that would be great! Do you think you will be able to get a PR out by Thursday?

**Comment by marcaaron** [comment] 2023-07-26 21:57
Also can we see some proposal for what is causing the regression in the previous PR? Seems like the code was like 99% there - but we just introduced a regression. What was the root cause of that?

**Comment by shubham1206agra** [comment] 2023-07-27 07:00
I want to bypass 1st step of bank setup. How to do that?
I want to test the component

**Comment by shubham1206agra** [comment] 2023-07-27 16:12
> Also can we see some proposal for what is causing the regression in the previous PR? Seems like the code was like 99% there - but we just introduced a regression. What was the root cause of that?

I may have found the RCA, but I need to confirm the behaviour of the component.

**Comment by srikarparsi** [comment] 2023-07-27 17:25
Hi @shubham1206agra, can you please try it on chrome when you get a chance. You can also double check expected behavior by trying the same test steps on main without any changes.

**Comment by shubham1206agra** [comment] 2023-07-28 02:43
@srikarparsi Same behaviour with the existing class-based component. Checked with staging new dot

**Comment by srikarparsi** [comment] 2023-07-28 05:27
Cool! Assigning you to the issue. Please push your PR whenever you get a chance.

**Comment by shubham1206agra** [comment] 2023-07-30 13:57
@srikarparsi Check the PR

**Comment by srikarparsi** [comment] 2023-08-09 06:28
Hi @lschurr! Can you please pay @shubham1206agra for creating this PR and @sobitneupane for testing this PR whenever you get a chance?

**Comment by lschurr** [comment] 2023-08-09 15:54
Sure! The automation says both are $250. Is that correct @srikarparsi?

**Comment by srikarparsi** [comment] 2023-08-09 18:34
Yup, that's right, thanks @lschurr!

**Comment by lschurr** [comment] 2023-08-09 18:42
Payment summary:

- @shubham1206agra $250 (paid in Upwork)
- @sobitneupane $250 (please request in NewDot)

**Comment by srikarparsi** [comment] 2023-08-09 18:55
Hey yeah closing this out! I don't think regression tests are needed because they already covered this case which is why the [issue](https://github.com/Expensify/App/issues/23576) was reported.

**Closed by srikarparsi** 2023-08-09 18:55 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2023-08-21 07:34
Requested payment on newDot.

https://github.com/Expensify/App/issues/16138#issuecomment-1671949857

**Comment by JmillsExpensify** [comment] 2023-08-30 04:17
Reviewed the details for @sobitneupane. $250 approved for payment via NewDot based on BZ summary above.
