### ISSUE TITLE
[$250] IOS - Hold request - Keyboard overlaps education modal after putting expense on hold

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43989] opened 2024-06-19 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4645099
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition: user is a member of a workspace
1. Open the app and log in as a member of a workspace
2. Navigate to the workspace chat
3. Submit 2 expenses
4. Open one of the expenses > 3 dots
5.Select Hold and enter the comment

## Expected Result:
The education modal is displayed and fully visible

## Actual Result:
Keyboard comes out and overlaps the education modal.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0b420f64-6771-4373-a65f-0eed213dde8f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f5e0c27cb4a2e57</li>
        <li>Upwork Job ID: 1805194799193979622</li>
        <li>Last Price Increase: 2024-08-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Julesssss</details>

**Comment by izarutskaya** [comment] 2024-06-19 12:32
We think this issue might be related to the #collect project.

**Comment by Sparth19** [comment] 2024-06-25 08:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- On iOS, when the hold expense is triggered, the keyboard overlaps the educational modal, causing the modal to be hidden behind the keyboard.

### What is the root cause of that problem?

- Upon pressing the hold button, the user is navigated to the hold reason page. After submitting the hold reason, the system returns to the Report Screen, automatically focusing on the composer input field to open the keyboard.

### What changes do you think we should make in order to solve the problem?

- The keyboard can be dismissed when the educational modal is opened here.

https://github.com/Expensify/App/blob/621e8fc63f78858ac15b8c2c1fda0516f49cf27d/src/components/MoneyRequestHeader.tsx#L180-L185

```
 setShouldShowHoldMenu(isOnHold && !dismissedHoldUseExplanation);
 Keyboard.dismiss();
```

- Result 

https://github.com/Expensify/App/assets/30714258/dab54555-eb16-461e-8f5c-4ef36ab97663



### What alternative solutions did you explore? (Optional)

**Comment by Sparth19** [comment] 2024-07-01 04:58
@parasharrajat Thanks for your suggestions. I have reviewed the functionality of the Popover Component and its relevant props.

- `avoidKeyboard` prop is designed to move the modal up when the keyboard is opened to ensure that the modal content remains visible.

- However, using `avoidKeyboard` results in the modal being repositioned in a way that can disrupt the user experience. It can make the modal appear to jump or move unexpectedly, which is not ideal for smooth interaction.

- We have already implemented `shouldSetModalVisibility` in our modal, but it did not resolve the issue.

**Comment by Sparth19** [comment] 2024-07-02 14:24
I applied for the job on Upwork. The PR will be ready by tomorrow.
Thanks!

**Comment by Sparth19** [comment] 2024-07-03 12:50
@Julesssss [PR](https://github.com/Expensify/App/pull/44771) is ready for review. Thanks!

**Comment by kavimuru** [comment] 2024-07-11 16:55
Issue is not reproducible anymore.

https://github.com/Expensify/App/assets/43996225/21fe5f64-90e2-4e6d-a590-f0b9adcc2497

**Comment by bfitzexpensify** [comment] 2024-07-12 09:27
Payment summary:

@parasharrajat to be paid $250 for C+ work via manual request
@Sparth19 to be paid $250 for contributor work - paid via Upwork ✅

**Comment by JmillsExpensify** [comment] 2024-07-16 05:28
$250 approved for @parasharrajat

**Comment by lanitochka17** [comment] 2024-07-24 17:17
Issue is still reproducible 

https://github.com/user-attachments/assets/0a1a537f-1e8c-4fa0-88c3-1f061b734616

**Comment by Julesssss** [comment] 2024-08-05 10:55
Hey, @bfitzexpensify is OOO until Thursday. I think we should reopen for proposals, yeah.

**Comment by cdOut** [comment] 2024-08-05 18:44
Hi, I’m Tymoteusz from Software Mansion, the expert agency, and I worked on both the hold feature and report details revamp. If there aren’t any proposals yet I can overtake this issue and look for a fix.

**Comment by Julesssss** [comment] 2024-08-06 08:43
Hi @cdOut that sounds good to me. 

@parasharrajat just to check, are you happy to remain C+ here?

**Comment by cdOut** [comment] 2024-09-16 21:00
cc @Julesssss @parasharrajat 

Hi, I'm not sure who's currently assigned to this issue but it can be closed. 

I was creating a PR with a fix for this one, but it appears that in the meantime some other changes were merged that successfully fixed it and it's no longer reproducible on the latest main branch. I've attached a test video which shows the keyboard hiding properly under the educational modal [in the closed PR](https://github.com/Expensify/App/pull/47392#issuecomment-2349485851), we've both checked the flow and it's no longer broken.

**Comment by Julesssss** [comment] 2024-09-17 16:11
> Hi, I'm not sure who's currently assigned to this issue but it can be closed.

Ah thanks 👍 

@bfitzexpensify it seems like the PR was reviewed and pretty much ready. Does a half paymentfor both sound good to you.

**Comment by bfitzexpensify** [comment] 2024-10-04 10:35
Payment summary:

@parasharrajat to be paid $125 for C+ review

Closing this out

**Closed by bfitzexpensify** 2024-10-04 10:35 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by JmillsExpensify** [comment] 2024-12-16 10:14
$125 approved for @parasharrajat
