### ISSUE TITLE
[$1000] iOS - Split bill - Keyboard displayed abruptly when split bill animation slides in

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21394] opened 2023-06-23 11:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21310
## Action Performed:
1. Open iOS app
2. Open group DM
3. Set focus to message composer (so keyboard is displayed)
4. Tap on "+" near composer
5. Tap on "Split bill"

## Expected Result:
Split bill screen animation slides in smoothly with no unnecessary elements displayed

## Actual Result:
Keyboard is still displayed for a couple of seconds when Split bill screen animation slides in

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/42ac89e6-2ece-428c-830a-6de75399c0e3

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fd7b79c5ae42e842</li>
        <li>Upwork Job ID: 1673323311936536576</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by waterim** [comment] 2023-06-26 15:16
Hi!
I'm Artem from Callstack - expert contributor group
Maybe I can help with this one?

**Comment by s77rt** [comment] 2023-06-26 15:24
@CortneyOfstad Can you please assign @waterim here

**Comment by CortneyOfstad** [comment] 2023-06-26 15:30
@s77rt Do you want me to remove your assignment in favor of @waterim, or have you both assigned?

**Comment by s77rt** [comment] 2023-06-26 15:33
@CortneyOfstad Both. I will be the C+ here for review

**Comment by aabantariqmurtaza** [comment] 2023-06-26 18:59
I am trying to run iOS application. For that i want to read iOS document. 
But It is redirecting me to page asking my Enter your @expensify.com email to get started
I don't have this email. plz help setting up this.

**Comment by aabantariqmurtaza** [comment] 2023-06-26 19:03
Contributor details
Your Expensify account email: aban.softengr@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ecb1d62beec30401

**Comment by s77rt** [comment] 2023-06-29 10:52
@waterim Any updates here?

**Comment by waterim** [comment] 2023-06-29 11:42
@s77rt Found a root of the issue, will add proposal today.

**Comment by waterim** [comment] 2023-06-29 22:10
@s77rt Will send it tomorrow, found one issue with random black blink after the navigation

**Comment by waterim** [comment] 2023-06-30 09:45
@s77rt I was reviewing Popover animation, everything was correct there. After I decided to try to restart IOS simulator and this black blink just disappeared.

**Comment by waterim** [comment] 2023-06-30 09:46
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Keyboard displayed abruptly after navigation to split bill screen
### What is the root cause of that problem?
The main issue here is a behaviour of Native IOS keyboard. If the keyboard dismissal occurs after the navigation has started, it may result in a momentary blink as the new screen is displayed.
**File we are working with**: ReportActionCompose.js
### What changes do you think we should make in order to solve the problem?
The best way to fix this issue is to hide Keyboard with Keyboard.dismiss() before the actual Popover with (Split Bill and Add Attachment) was opened. This will add a natural feeling of the application - Keyboard will disappear with a native animation before Popover is opened.
### What alternative solutions did you explore?
N/A

**Comment by s77rt** [comment] 2023-06-30 14:09
@waterim Thanks for the proposal. I don't think your RCA is correct/complete. Your provided little info on why the bug is occurring in the first place. For instance why the keyboard is even getting pulled up? Is it because we are re-focusing the input after closing the modal or something else? I think the point that I'm trying to make here is that instead of pulling the keyboard up and then dismiss it, we should not even pull it in the first place.

**Comment by waterim** [comment] 2023-06-30 14:29
@s77rt okay, I will add more information to the Proposal. 

here is an answer to your question:
original behavior - we are not closing the keyboard itself when we are opening Popover, and after the navigation to the split bill screen we are dismissing the keyboard, thats why it still blinks for a second, because we are closing it only on the split bill screen.
In my proposal Im adding dismiss before even popover opens, with this solution we are getting smooth keyboard close before opening popover(like telegram for example has) and with this solution when we are navigating to a new screen we don’t have any keyboard pulled up before.

**Comment by s77rt** [comment] 2023-06-30 14:33
@waterim After we click on the plus grey button, the keyboard is already dismissed. Why after we click on "Split bill" it appears again?

**Comment by waterim** [comment] 2023-06-30 16:55
@s77rt After additional investigation: 
**"Why after we click on "Split bill" it appears again?"**
1. "grey button" opens a modal from react-native-modal which handles automatically the keyboard. It means it dismisses the keyboard on open and shows the keyboard after it close(if it was opened before we opened the modal itself)
2. After the click on the button "split bill" we are making a navigation and closing the modal and it means that our keyboard will show up. But on the page Split bill we have a logic to dismiss a keyboard and thats why keyboard will be opened just for a second.
3. With my solution we are closing the keyboard manually before modal is showing thats why it will not dismiss the keyboard automatically and will not open it again after modal is closed.(because it was closed before we opened the modal)

**Comment by CortneyOfstad** [comment] 2023-06-30 19:35
Heading OoO for the week (back July 10) so re-assigning this in the meantime 👍

**Comment by s77rt** [comment] 2023-06-30 20:22
@waterim Thanks for the follow up.

> "grey button" opens a modal from react-native-modal which handles automatically the keyboard. It means **it dismisses the keyboard on open** and **shows the keyboard after it close**(if it was opened before we opened the modal itself)

Can you please back this up with link to code? I know this behaviour exists in RNW for accessibility reasons as part of the [FocusTrap](https://github.com/necolas/react-native-web/blob/b10c66351eae55a8ea798a1217254d7a2658c5b1/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L142-L143) implementation. But I don't see any relevant code in [`react-native-modal`](https://github.com/react-native-modal/react-native-modal/blob/master/src/modal.tsx). Perhaps this is something coming from RN's `<Modal />`?

Also, how come this issue is only reproducible in iOS and not in Android?

___


Feedback: Everytime you make a statement it's really recommended that you link to code supporting that statement e.g. in "But on the page Split bill we have a logic to dismiss a keyboard", it would have been great and much helpful if you linked to that logic. This makes the review process much faster.

**Comment by s77rt** [comment] 2023-06-30 20:39
Sorry @waterim I just realised that this issue may be a dupe of https://github.com/Expensify/App/issues/13922.
@lschurr I think we can close this one.

**Comment by waterim** [comment] 2023-06-30 20:42
@s77rt actually with my solution add attachment works perfectly, without any keyboard blinks

**Comment by waterim** [comment] 2023-06-30 20:43
@s77rt thank you for your feedback, will add more details, more relevant code to future proposals

**Comment by s77rt** [comment] 2023-06-30 20:48
@waterim What I meant to say is that we may already be working on fixing this issue. I see we have an open PR https://github.com/Expensify/App/pull/15337 for that.

**Comment by waterim** [comment] 2023-06-30 20:52
@s77rt okay, sure)
Just one suggestion to add a native animation for a keyboard dismiss after clicking on the “+” button, it will feel more natural and native

**Comment by s77rt** [comment] 2023-06-30 22:24
@waterim Thanks, this feels like an improvement. I think we should let the assignees handle the bug fix first then we can discuss such animations in Slack.

**Comment by lschurr** [comment] 2023-07-03 15:25
Just to confirm - should this one be closed for now @s77rt?

**Comment by s77rt** [comment] 2023-07-03 15:29
@lschurr Yes

**Closed** 2023-07-05 16:59 UTC
Labels: External, Daily, Bug
