### ISSUE TITLE
[$1000] Chat - User receives messages in offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24000] opened 2023-08-01 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. In account A, toggle off internet using force offline
3. In account B, send messages to account A

## Expected Result:
The messages must be received after user enable internet

## Actual Result:
The messages are received in offline. The messages received can be seen in LHN and notification, when device in offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0cb7fd17-f3cf-41e0-98ae-6b588195c912

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fac559f455883efd</li>
        <li>Upwork Job ID: 1686830060052582400</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Contributor | 25930336</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment] 2023-08-02 20:03
Bug report looks good!

**Comment by hayata-suenaga** [comment] 2023-08-03 16:12
> When a user is offline we shouldn't be receiving any push notifications, right?

Yes on staging. Force offline option is only available in the staging app so that we can simulator offline network condition when developing and testing. We should unsubscribe from push notifications when tester is put on the offline mode

**Comment by slafortune** [comment] 2023-08-29 20:08
@parasharrajat is there an update on this?

**Comment by hayata-suenaga** [comment] 2023-08-30 14:38
heyyy @parasharrajat I'm so sorry for the late reply. It's very easy to miss slack notifications 😓 

you can also ping me on GH here (that's more noticeable on my end). Anyway, I asked [a follow up question to the channel](https://expensify.slack.com/archives/C02NK2DQWUX/p1693406217385319?thread_ts=1691172435.257529&cid=C02NK2DQWUX)

**Comment by hayata-suenaga** [comment] 2023-09-02 00:38
Let me get back to you once I discuss this with the internal team

**Comment by slafortune** [comment] 2023-09-08 19:00
@parasharrajat any update here?

reassigning a BZ member since I'm out on sabbatical

**Comment by hayata-suenaga** [comment] 2023-09-11 01:46
heyyy I'm back! I think the internal team hasn't responded yet. Let me bump them 🏃

**Comment by hayata-suenaga** [comment] 2023-09-13 03:00
nop 😭 

I think we don't have to hurry this into merge. We have several features pushed right now. I really don't want to cause any regression from this PR

**Comment by hayata-suenaga** [comment] 2023-09-21 04:26
@parasharrajat do you think ⬆️ is a good approach?

**Comment by hayata-suenaga** [comment] 2023-09-27 03:02
why do we need the offline toggle inside the app (staging) by the way? I don't know much context on why we added this toggle, but can't testers just turn off the network of their device to test offline behavior?

**Comment by hayata-suenaga** [comment] 2023-09-27 03:25
but can't we use the network tab to control the offline state after we load the website?

**Comment by hayata-suenaga** [comment] 2023-09-27 03:29
I don't think we don't need to account for the same when the device becomes offline and then the user tries to reload the website.

@parasharrajat do you know why we needed the offline toggle?

**Comment by hayata-suenaga** [comment] 2023-10-10 01:01
> I also think if we are investing resources in this, then let's finish this already if changes do not affect the app's real functionality.

I still prefer not adding extra code that isn't for features normal users use. Any additional code is something we have to maintain.

But I appreciate the work @parasharrajat and @hungvu193 already put into this issue

@garrettmknight I think we can do half the posted price.

**Comment by garrettmknight** [comment] 2023-10-19 13:12
**Summary of payment:**
- Note: Half payment for work done even though we decided not to go through with the PR.
- Contributor: @hungvu193 $500 paid via Upwork
- Reviewer: @parasharrajat $500

Upwork job: https://www.upwork.com/jobs/~01fac559f455883efd

**Closed** 2023-10-20 14:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
