### ISSUE TITLE
Android - Chat - Keyboard not immediately disappeared when tapped on plus button or navigated to LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40107] opened 2024-04-11 13:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open app
2. Navigate to workspace chat
3. Tap on the composer box
4. Tap on plus button
5. Wait about 5 second
6. Tap outside of the action menu
7. Tap on the compose box
8. Tap on back arrow button

## Expected Result:
Keyboard should be immediately disappeared when user tapped on plus button or navigated to LHN

## Actual Result:
Google Keyboard (Gboard) not immediately disappeared when tapped on plus button or navigated to LHN

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e6057592-18b4-4952-8d53-04d3d1063f47

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2024-04-11 19:19
Trying to reproduce

**Comment by srikarparsi** [comment] 2024-04-11 20:01
Was able to reproduce on staging. I think this might be related to [Enable Fabric and TurboModules on iOS & Android](https://github.com/Expensify/App/pull/13767), I couldn't find any other issues that could be causing this.

@roryabraham or @WoLewicki do you guys have any thoughts? Maybe we could make this external and bump the price similar to what we did [here](https://github.com/Expensify/App/issues/40048#issuecomment-2049507626)?

**Comment by WoLewicki** [comment] 2024-04-15 15:43
For now I managed to get to a point where the problem disappears when disabling `reanimated` commit hook. I will investigate it further what is the root cause of it breaking with the hook.

**Comment by srikarparsi** [comment] 2024-04-21 23:15
Hey @WoLewicki, any updates on this? Or should this be on hold for a different issue?

**Comment by srikarparsi** [comment] 2024-04-25 23:19
Hey @WoLewicki, friendly bump on the above

**Comment by WoLewicki** [comment] 2024-04-26 09:10
I think this should be resolved by https://github.com/Expensify/App/pull/40302 but we are also working on fixing it correctly so that we can bring back the animation.

**Comment by srikarparsi** [comment] 2024-05-06 01:02
OOO until Wednesday. Will test and hopefully close once I'm back as this should've been [resolved](https://github.com/Expensify/App/issues/40107#issuecomment-2078971353)?

**Comment by srikarparsi** [comment] 2024-05-09 18:26
This is no longer reproducible on android (or iOS), closing it out.

**Closed by srikarparsi** 2024-05-09 18:26 UTC
Labels: Engineering, Daily, Overdue
