### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Workspace - The empty loading chats are shown in the half part of the screen and the other half is blank

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19490] opened 2023-05-23 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on chrome
2. Go offline
3. Create a workspace
4. Go to announce and send any message
5. Reply in the same thread
6. Notice that the 3 loading chats are shown and all the remaining are black blank that makes it look weird
7. Now go online
8. Notice that the loading chats are shifted above and the remaining down portion are plain black and doesn't go away until you refresh the page

## Expected Result:
The loading chats should not be shown in the half part of the screen that makes it look weird.

## Actual Result:
The loading chats are shown in the half part of the screen and the other half is blank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/cb876d99-639a-4985-9df6-9287436b6040

https://github.com/Expensify/App/assets/93399543/894ac253-647e-4dc1-adf2-6dfe3fe60bc4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684420395406219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0144bfc6df266a73d1</li>
        <li>Upwork Job ID: 1661207831671959552</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by tienifr** [comment] 2023-05-24 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The report action skeletons are shown when users reply the message

### What is the root cause of that problem?

In https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/pages/home/report/ReportActionsList.js#L159-L178

We're showing ReportActionsSkeletonView if props.report.isLoadingMoreReportActions is true

1. when users open the new thread, the API ReadOldestAction is called

https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/libs/actions/Report.js#L538-L540

2. Because we're in offline mode and it's read request => there's no way to update isLoadingMoreReportActions = false =>  isLoadingMoreReportActions = true
3. The skeletons are shown
 
### What changes do you think we should make in order to solve the problem?

We should have the logic to update failureData with read request

**Comment by s77rt** [comment] 2023-05-24 18:18
@tienifr Thanks for the proposal. Your RCA makes sense. As I understood the sensitive part is the missing CREATED action. We show the skeleton view up until we encounter a CREATED report action and in our case this action is missing. Would that be about right?

I have asked here https://github.com/Expensify/App/pull/18522#discussion_r1204597404.

**Comment by s77rt** [comment] 2023-05-24 23:34
Confirmed ^

@marcochavezf Let's go with @tienifr's proposal.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by marcochavezf** [comment] 2023-05-26 02:38
Perfect, thanks @s77rt, assigning @tienifr 🚀

**Comment by jliexpensify** [comment] 2023-05-26 02:49
Invites sent via Upworks. 

@tienifr I assume you're Tien Anh. N? If so, can you please add your full name to your GH account so we can easily see who you are for next time? Cheers.

**Comment by tienifr** [comment] 2023-05-26 02:53
@jliexpensify Done. Thanks for the suggestion!

**Comment by s77rt** [comment] 2023-06-02 22:55
Not overdue. We have a PR already and it's waiting for @marcochavezf's review.

**Comment by s77rt** [comment] 2023-06-06 21:52
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/18522
- The offending PR has been commented on: https://github.com/Expensify/App/pull/18522#discussion_r1204597404
- A discussion in #expensify-bugs has been started: I don't feel there is much to discuss here, the bug is an edge case and the offending PR was prioritised to be merged within a deadline thus some offline tests were missed
- Determine if we should create a regression test for this bug: No

**Comment by jliexpensify** [comment] 2023-06-14 01:26
@marcochavezf couple of questions for you:

- Is no regression test ok?
- It looks like the iOS and Android deploys for this PR were cancelled, this shouldn't be an issue for payments right?

If not, I'll pay $1000 to both @tienifr and @s77rt .

**Comment by jliexpensify** [comment] 2023-06-14 22:52
Bump @marcochavezf to the above questions!

**Comment by marcochavezf** [comment] 2023-06-15 18:54
Hi @jliexpensify, yeap, it's fine

**Comment by jliexpensify** [comment] 2023-06-15 22:29
Everyone has been hired! Thanks Marco.

**Comment by jliexpensify** [comment] 2023-06-17 00:04
Everyone's paid, job closed. Cheers!

**Closed by jliexpensify** 2023-06-17 00:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
