### ISSUE TITLE
Action Menu - Mark as Unread action does not work on latest message from the other Participant

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#10912] opened 2022-09-08 23:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
_**FIRST SCENARIO**_
1. Log in to Account A on a IOS
2. From account B on another device sent a message to account A
3. As account A, verify you receive the message and it's visible in the conversation
4. Log out and back in to account A
5. Navigate to the conv with Account B
6. Press and hold on the latest message and select "Mark as Unread"
7. Tap < to go to LHN

_**SECOND SCENARIO**_
_Not reproducible in all conversations_
1. In a conversation were the latest message is from the other participant, scroll up and delete one of your messages
2. Scroll to the bottom and press and hold on the latest message > press on "Mark as Unread" 
3. Tap < to go back to LHN 

_**Note: This is consistently happening on my and @mallenexpensify conversation**_

## Expected Result:
Mark as Unread action works and the message is marked as unread in both the conversation and the LHN. 
## Actual Result:
Mark as Unread action does nothing on the message and it's not displayed as bold on LHN

## Workaround:
After sending a few messages the action works as expected. 

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.1.98-0

**Reproducible in staging?:** Yes
**Reproducible in production?:** 

**Email or phone of affected tester (no customers):** igoicoechea@applausemail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
_**FIRST SCENARIO**_

https://user-images.githubusercontent.com/44479856/189241844-9bf1bb5c-d3de-41e2-9f51-89806b01e077.MP4

_**SECOND SCENARIO**_

https://user-images.githubusercontent.com/44479856/189245360-eb11bfd6-da53-4267-a8a8-6355765e9dd6.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @mallenexpensify 
**Slack conversation:** thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1662670283670099), issue was found when trying to reproduce the issue described on the main message. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mallenexpensify** [comment] 2022-09-08 23:51
Might be related this this that Marc is working on https://github.com/Expensify/Expensify/issues/227410

**Comment by marcaaron** [comment] 2022-09-09 08:20
I think it's a dupe so assigning myself to keep a close 👁️. We can close if my changes fix this (pretty confident they will).

**Comment by mallenexpensify** [comment] 2022-09-13 17:15
Hoping this is fixed soon with 
https://github.com/Expensify/Expensify/issues/227410
and 
https://github.com/Expensify/Auth/pull/7041

**Comment by mallenexpensify** [comment] 2022-09-15 00:10
Tested on Desktop and web and wasn't able to reproduce so closing

**Closed by mallenexpensify** 2022-09-15 00:10 UTC
Labels: Engineering, Weekly, Internal
