### ISSUE TITLE
[$500] Assign task - Can't find existing user (assign task)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33611] opened 2023-12-26 18:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/33347

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Open any chat
4. Open chat menu and select "Assign task"
5. Add title and press "Next"
6. Press "Assignee"
7. Type in "[tomasz.misiukiewicz@callstack.com"](mailto:tomasz.misiukiewicz@callstack.com%22)

## Expected Result:
User should be able to find an existing user.

## Actual Result:
User cannot find [tomasz.misiukiewicz@callstack.com.](mailto:tomasz.misiukiewicz@callstack.com.)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/2b159e00-1429-4532-8449-129bffe711d4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ef63cf1654af54ad</li>
        <li>Upwork Job ID: 1739719702996258816</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by adriancova** [comment] 2023-12-26 21:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Existing users are not listed as an option for assigning a task.

### What is the root cause of that problem?
In the component `TaskAssigneeSelectorModal`  the call to `OptionsListUtils.getFilteredOptions`  is done with the parameter `canInviteUser` set as false. This translates to the list of users available being limited to only contacts and recent.

### What changes do you think we should make in order to solve the problem?
Change the parameter to true, this will update the behavior of assigning tasks to be the same as start chat, request money and send money. Where you can select already existing users even if they're not in your recent or contact lists.

### What alternative solutions did you explore? (Optional)
NA

**Comment by bfitzexpensify** [comment] 2023-12-29 17:12
How does the proposal in https://github.com/Expensify/App/issues/33611#issuecomment-1869772433 look @ntdiary?

**Comment by bfitzexpensify** [comment] 2024-01-01 21:19
Bump on review here when you get a chance @ntdiary - thanks!

**Comment by bfitzexpensify** [comment] 2024-01-03 16:15
Cool, agreed, closing this out.

**Closed by bfitzexpensify** 2024-01-03 16:15 UTC
Labels: External, Daily, Help Wanted, Bug
