### ISSUE TITLE
[HOLD for payment 2023-06-05] [$1000] Disabled cursor is being shown instead of default cursor

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19208] opened 2023-05-18 19:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app and keep the screen size below 800px
2. Navigate to Settings > Payments > Have Paypal as a payment method
3. Click on the Paypal account
4. Hover over Paypal.me and username
5. You'll notice cursor is disabled

## Expected Result: 
Default cursor should be shown
## Actual Result: 
Disabled cursor is being shown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6f2f3bf2-ddc8-47aa-b711-df4c233f5fbf

https://github.com/Expensify/App/assets/43996225/1ff38bd0-d3a0-4e58-97b7-2187d824227f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daraksha-dk 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684248402352109

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e327fcf150738b2d</li>
        <li>Upwork Job ID: 1659343886988689408</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-18 19:02
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
 Wrong cursor styling for read-only MenuItem
 ### What is the root cause of that problem?
The root cause of this issue is that we are using `disabled={true}` with `interactive={false}` to make a read-only MenuItem. Which adds the extra disabled styles to the component.
### What changes do you think we should make in order to solve the problem?

 To fix this, we first need to decide what type of styling is needed when:
  - disabled and interactive are true
  - disabled is true and interactive is false
  - disabled is undefined/false and interactive is false
#### My suggestion:
(keeping `interactive` true by default)
   - When interactive is true & disabled is false/undefined => default state with cursor pointer
   - When both disabled & interactive are true => apply disabled styles like cursor disabled (normal scenario for disabled state)
   - When both disabled & interactive are false => Use the default cursor styling. (when data is read-only like Title)
   - When interactive is false & disabled is true => Add a different type of disabled styling like an opacity change (optional)
 These changes will be needed to be done in `src/components/MenuItem.js` and after making these changes other places where it's being used will need to be updated accordingly.
by @daraksha-dk

**Comment by kushu7** [comment] 2023-05-18 19:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Disabled cursor is being shown instead of default cursor
### What is the root cause of that problem?
Its happening because We are using `MenuItem` here with `disabled=true`. its adding cursor disabled.
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/7d7fa72d83a9c34aeff83eea200297bc2dd10a2c/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L438-L445
we can set disabled= false. it will make cursor pointer. then we can ovveride it by 
adding styles.cursorDefault to wrapperStyle array


### What alternative solutions did you explore? (Optional)
None


Result:


https://github.com/Expensify/App/assets/31707153/d70e607c-21e8-4df3-87c6-ffa877765e24

**Comment by loveheenavasu** [comment] 2023-05-19 05:51
**Please re-state the problem that we are trying to solve in this issue.**
A disabled cursor is being shown instead of the default cursor

**What is the root cause of that problem?**
This is causing a problem because here in MenuItem using disabled which is making the cursor disabled.

**What changes do you think we should make in order to solve the problem?**
We need to update or remove the disabled prop from the menuItem.
` <MenuItem 
     title={this.state.formattedSelectedPaymentMethod.title || ''} 
     icon={this.state.formattedSelectedPaymentMethod.icon} 
     description={this.state.formattedSelectedPaymentMethod.description} 
     wrapperStyle={[styles.pv0, styles.ph0, styles.mb4]} 
     disabled 
     interactive={false} 
 />`
 
 When the disabled prop is removed or updated to disabled={false}, it will change that cursor to the pointer.
 Then we can change the styles to make it the default cursor.

**Comment by loveheenavasu** [comment] 2023-05-19 05:59
Contributor details
Your Expensify account email: trivediheenalove@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016adf33c4f0ca2e1c/

**Comment by akshay-bharadva** [comment] 2023-05-19 14:59
## Proposal

### Under [/settings/payments](https://new.expensify.com/settings/payments) path for paypal.me `MenuItem` the not-allowed cursor is being shown instead of default cursor.

### Root cause of this problem is that `disabled` props has been passed to [`MenuItem`](https://github.com/Expensify/App/blob/cb6ba23ea1e99a3b332983568ee8e9aa0c2a09dd/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L442) component.

### To solve this issue we should remove the `disabled` props this way the cusor will changed to pointer and to show default cursor we should add `styles.cursorDefault` into `wrapperStyle` props array. By adding `styles.cursorDefault` will solve the issue.

**Comment by akshay-bharadva** [comment] 2023-05-19 15:17
Contributor details
Your Expensify account email: akshaybharadva19@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/akshayb17

**Comment by bondydaa** [comment] 2023-05-22 16:18
sorry for the delay, assigned out.

**Comment by miljakljajic** [comment] 2023-05-23 08:31
Apologies for not catching this while I was at EC3. Removing my assignment as I'm OOO - will reapply the label

**Comment by arielgreen** [comment] 2023-05-26 02:03
Reassigning, OOO tomorrow/Monday

**Comment by greg-schroeder** [comment] 2023-05-26 12:07
PR merged and deployed to staging

**Closed** 2023-06-06 18:38 UTC
Labels: External, Weekly, Awaiting Payment, Bug
