### ISSUE TITLE
Track expense - In track expense, edit amount shows dollar briefly

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40873] opened 2024-04-24 12:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/39956
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on a chat --- tap the FAB > track expense
3. Enter an amount > change currency to RP>  tap next
4. Tap track expense (add a merchant when required) 
5. Tap on newly created expense to open epense details
6. Tap amount to edit the currency
7. Choose RP > Save 
8. Tap on amount to edit current 
9. Choose RP > Save 
10. Notice the $ shows for a brief moment after Saving expense and while the changes loading

## Expected Result:
In track expense when clicking indian Rupee (RP), edit amount should not show any other currency

## Actual Result:
In track expense while the amount in Indian Rupee (RP), edit amount shows dollar briefly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3e90961c-8e37-4cc6-b53e-5597cfcb874c

https://github.com/Expensify/App/assets/51066321/b31ffbbe-8582-470e-9f32-adbd0f525bc6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-24 12:06
@Christinadobrzyn I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by mountiny** [comment] 2024-04-24 12:18
Seems like a second regression from https://github.com/Expensify/App/pull/39956 @shubham1206agra @thienlnam @allroundexperts 

Its minor as well, can you follow up with a quick fix

**Comment by mountiny** [comment] 2024-04-24 16:11
demoting this as its minor but @shubham1206agra @allroundexperts assinging you as this is most likely coming from your PR

**Comment by allroundexperts** [comment] 2024-04-30 07:19
I think @shubham1206agra were unable to reproduce this. Is this correct @shubham1206agra?

**Comment by Christinadobrzyn** [comment] 2024-04-30 09:09
I can't reproduce this either. I'll ask QA to test - https://expensify.slack.com/archives/C9YU7BX5M/p1714468168251599

**Comment by kavimuru** [comment] 2024-04-30 11:11
Bug is still reproduced.

https://github.com/Expensify/App/assets/43996225/bdb940c5-553f-4106-9862-fea6f9447848

**Comment by Christinadobrzyn** [comment] 2024-05-02 08:10
I'm still not able to reproduce this... @shubham1206agra or @allroundexperts can you test again and let me know if you get this?

**Comment by Christinadobrzyn** [comment] 2024-05-03 04:32
Okay, I was able to reproduce this again when testing on iOS app - I uploaded the video to the OP and updated the steps. 

Since this only seems to be affecting RP expenses, I'm kinda inclined to close this as a not critical, edge case, not part of our ROI. We can reevaluate it at a later time. 

@thienlnam @allroundexperts what are your thoughts?

**Comment by thienlnam** [comment] 2024-05-06 21:07
I agree, doesn't seem like something we need to fix at this time

**Closed** 2024-05-06 21:08 UTC
Labels: Engineering, Daily, Bug
