### ISSUE TITLE
[$250] Desktop - Blank screen is displayed after update to new build 1.2.28-0

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12760] opened 2022-11-16 01:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Update app to build 1.2.28-0.
2. Open App

## Expected Result:
App should be open and the user able to login

## Actual Result:
A blank screen is displayed after the update to the new build 1.2.28-0.
The issue occurred after fully deleting and new installing.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** 1.2.28-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1196" alt="Bug5822409_Screen_Shot_2022-11-15_at_7 23 18_PM" src="https://user-images.githubusercontent.com/43996225/202061134-957ffc00-6014-45a9-8930-5a18c697d265.png">
https://user-images.githubusercontent.com/43996225/202061568-fe9959dc-3ca4-4893-936c-61b2bd1e0124.mp4
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @michaelhaxhiu  / Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment] 2022-11-16 13:19
Job posting: https://www.upwork.com/jobs/~01f438a60531a83517

**Comment by roryabraham** [comment] 2022-11-16 17:22
Sorry for the miscommunication, but @NicMendonca we should never make hourly deploy blockers external. They need to be treated with more urgency than our contributing process allows for

**Comment by roryabraham** [comment] 2022-11-16 17:24
It was indeed a regression caused in https://github.com/Expensify/App/pull/12334 (works in dev, but not release mode). @vladamx stepped up to fix it proactively because it was a correction of his implementation of https://github.com/Expensify/App/issues/12234

**Comment by roryabraham** [comment] 2022-11-16 18:27
https://github.com/Expensify/App/pull/12785 merged and CPing

**Comment by roryabraham** [comment] 2022-11-16 18:28
We should leave this open for a bit ... I need to do the BugZero checklist steps above ^

**Comment by roryabraham** [comment] 2022-11-16 21:45
Done

**Closed by roryabraham** 2022-11-16 21:45 UTC
Labels: Reviewing, DeployBlockerCash, External, Engineering, Hourly, Bug

**Comment by roryabraham** [comment] 2022-11-29 06:17
@NicMendonca I think that @aimane-chnaif is eligible for compensation. You can see they pointed out cause for the regression [here](https://github.com/Expensify/App/issues/12234#issuecomment-1317305225) before the [PR to fix the regression](https://github.com/Expensify/App/pull/12785) was created.

**Comment by NicMendonca** [comment] 2022-12-02 23:21
@aimane-chnaif can you please [accept the job offer?](https://www.upwork.com/jobs/~01f438a60531a83517)

**Comment by NicMendonca** [comment] 2022-12-10 16:58
@aimane-chnaif paid, thank you! 😊
