### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Upgrade Electron package to latest version

### ISSUE THREAD

**Issue by blimpich** [Expensify/App#35600] opened 2024-02-01 22:51 UTC
# Problem

Electron is a core part of our app and we are currently several major versions behind. We should be up to date in order to gain the benefit of up-to-date security patches and also added functionality. One example is that https://github.com/Expensify/App/issues/34829 will be partially fixed when [this Electron issue](https://github.com/electron/electron/issues/38955) gets closed, but only if we are on the most recent version.

# Solution

Upgrade to the most recent stable version of Electron. As of the time of writing this issue that is major version `28` but [major version `29` should become the new latest stable version sometime in February](https://www.electronjs.org/docs/latest/tutorial/electron-timelines). Keep that in mind as this issue progresses.

**Note:** for testing make sure to test the [electron auto updater](https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/desktop/README.md#testing-electron-auto-update)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01411beff5fb7fab7c</li>
        <li>Upwork Job ID: 1753189399602946048</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>jeremy-croff | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by jeremy-croff** [comment] 2024-02-02 02:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Need to update electron

### What is the root cause of that problem?
Visibility bug will improve our user experience on electron

### What changes do you think we should make in order to solve the problem?
We should wait for issue https://github.com/electron/electron/issues/38955 to get merged and released to a stable version. Only then upgrade to that electron version with the steps documented in https://github.com/Expensify/App/blob/4f103255b77271d60666d39a0670104d113c44b5/desktop/README.md#testing-electron-auto-update.

I did a spot check against  tohttps://www.electronjs.org/docs/latest/breaking-changes make sure we don't have any larger migration changes needed.

### What alternative solutions did you explore? (Optional)

**Comment by rushatgabhane** [comment] 2024-02-05 16:25
@blimpich based on https://github.com/Expensify/App/issues/35600#issuecomment-1922661868 should this be `weekly`?

**Comment by blimpich** [comment] 2024-02-05 18:23
We don't need to wait for the upstream fix in my opinion. Once we are updated to the latest major version there will be little risk in bumping the minor version needed to make use of that upstream Electron PR. This can be done in parallel. And actually I'd prefer that this be done in parallel so that we can sort out any issues / regression that bumping the major version might cause now rather than later.

However, after thinking about it, I would like this upgrade to be done once the latest Electron major version is released on February 20th. So lets table this issue until then. Hopefully the upstream issue is fixed by then and we get two birds with one stone.

**Comment by blimpich** [comment] 2024-02-06 17:41
Upstream issue is officially fixed 🎉 https://github.com/electron/electron/issues/38955#issuecomment-1929219329

**Comment by jeremy-croff** [comment] 2024-02-06 19:01
Let's see if it's just a minor version bump. Would you like a proposal for that too?

**Comment by blimpich** [comment] 2024-02-07 01:32
@jeremy-croff Not sure if I understand, do you mean one proposal for the major version upgrade and one proposal for the minor version upgrade? If so, no, just the major. Or really simply the latest version once 29 is released.

**Comment by MitchExpensify** [comment] 2024-02-11 22:52
What is our next step here? Is this still a problem or was it resolved here: https://github.com/electron/electron/issues/38955#issuecomment-1929219329?

**Comment by blimpich** [comment] 2024-02-12 18:05
@MitchExpensify we're waiting till February 20th, which is when the newest stable version of Electron should be released according to [this](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by jeremy-croff** [comment] 2024-02-12 18:27
@blimpich @MitchExpensify There's some turbulence with the expected fix. Latest is that the occlusion fix got reverted:
https://github.com/electron/electron/pull/41311
And there's a new draft open for the feature.

**Comment by MitchExpensify** [comment] 2024-02-13 22:28
Thanks for the update

**Comment by blimpich** [comment] 2024-02-19 22:59
Not overdue. Tomorrow the newest version of electron comes out and then we can start the upgrade.

**Comment by blimpich** [comment] 2024-02-20 17:38
29 is out, lets get started on this.

![Screenshot 2024-02-20 at 9 38 33 AM](https://github.com/Expensify/App/assets/17171674/4d47bf47-dd3d-4b04-a6ef-a5773d358e5d)

**Comment by jeremy-croff** [comment] 2024-02-20 17:55
> @jeremy-croff @rushatgabhane are you both still good to work on this?

Can start today

**Comment by MitchExpensify** [comment] 2024-03-07 04:37
Reminder set to pay

**Comment by rushatgabhane** [comment] 2024-03-07 21:24
@MitchExpensify checklist not applicable because this isn't a bug / feature

**Comment by MitchExpensify** [comment] 2024-03-08 19:25
*Payment summary*:

- C+: $500 @rushatgabhane (NewDot)
- C: $500 @jeremy-croff (Upwork)

**Comment by rushatgabhane** [comment] 2024-03-11 23:08
request here https://staging.new.expensify.com/r/7234444884705194

**Comment by MitchExpensify** [comment] 2024-03-13 17:19
Contract ended and paid @jeremy-croff

**Closed by MitchExpensify** 2024-03-13 17:19 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-18 15:38
$500 approved for @rushatgabhane based on summary.
