### ISSUE TITLE
[$500] mWeb: Extra white space on the right - reported by @ahmdshrif

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10347] opened 2022-08-11 17:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to Expensify
2. Open to https://new.expensify.com/ again
3. Note the space on the right

## Expected Result:
UI appears without extra space

## Actual Result:
there is extra space on the right

## Workaround:
unknown. 

## Platform:

Where is this issue occurring?

- Mobile Web / Samsung browser

**Version Number:** 1.1.82-5
**Reproducible in staging?:** needs repro 
**Reproducible in production?:** Y (Needs repro) 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![Screenshot_20220718-133844_Samsung Internet (2)](https://user-images.githubusercontent.com/43995119/184200797-04928d6f-9573-4c06-b747-40760c78fb68.jpg)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @ahmdshrif
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1658148136422609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-10-19 20:32
Hi, @shawnborton can you please confirm if this is an issue that we would like to fix?

**Comment by shawnborton** [comment] 2022-10-19 20:43
I think it would make sense for the scroll bar portion to sit on top of the content and not add the extra space on the right. @Julesssss thoughts on this one? Tagging you since this is Android specific.

**Comment by Julesssss** [comment] 2022-10-20 16:53
@shawnborton yeah i agree. The scrollbar sits above and shouldn't introduce a margin

**Comment by shawnborton** [comment] 2022-10-20 17:46
Cool, I agree with that!

**Comment by techievivek** [comment] 2022-10-21 05:44
Passing it to contributors to have a look.

**Comment by smrutiparida** [comment] 2022-10-21 06:43
### Proposal

I quickly added a padding-right:0 and this is how it looks in below screenshot. is this what expected as a change. 

<img width="272" alt="Screen Shot 2022-10-21 at 12 08 57" src="https://user-images.githubusercontent.com/5945400/197130028-ca3bd4ad-f60d-4a67-a661-5beb29cc82b2.png">

Code snippet below

<img width="775" alt="Screen Shot 2022-10-21 at 12 10 51" src="https://user-images.githubusercontent.com/5945400/197130073-183bf487-eb76-4bff-92d1-a06205909875.png">

Please review @shawnborton @techievivek @Julesssss

**Comment by Julesssss** [comment] 2022-10-21 09:37
> Please review @shawnborton @techievivek @Julesssss

That doesn't look correct to me. The OptionRow items should have padding (notice the pin icon is now far too close to the egde). Instead, the extra space needs to be removed from the FlatList itself.

**Comment by parasharrajat** [comment] 2022-10-21 10:17
Correct, @smrutiparida 's proposal does not solve the correct problem and breaks the UI.

**Comment by parasharrajat** [comment] 2022-10-21 10:18
Just to be sure, is this still reproducible? This issue was created 2 months back.

**Comment by ahmdshrif** [comment] 2022-10-21 14:00
@parasharrajat I can't repro it now.  I think this was a react-navigation issue.  not a style issue. 
 anyway, it's working fine now.

**Comment by parasharrajat** [comment] 2022-10-21 14:22
@Expensify/applause Could you please retest it?

**Comment by kbecciv** [comment] 2022-10-21 14:36
@parasharrajat Sure, will update you shortly.

**Comment by smrutiparida** [comment] 2022-10-21 15:57
> > Please review @shawnborton @techievivek @Julesssss
> 
> That doesn't look correct to me. The OptionRow items should have padding (notice the pin icon is now far too close to the egde). Instead, the extra space needs to be removed from the FlatList itself.

You are right. That is not the right place to add padding. I will wait for @kbecciv to confirm a repro now and then can try removing the extra space from Flatlist

**Comment by kbecciv** [comment] 2022-10-21 18:40
Issue is not reproducible in our end
![Screenshot_20221021-143837_Chrome](https://user-images.githubusercontent.com/93399543/197267018-6593cb1e-351a-47cd-a16a-2fa35b41bcf8.jpg)
![Screenshot_20221021-143846_Gallery](https://user-images.githubusercontent.com/93399543/197267020-589c11aa-a4dc-463c-a7cb-4254ac2c8bbd.jpg)

**Comment by techievivek** [comment] 2022-10-24 07:47
Looking into it just to confirm this is not reproducible.

**Comment by techievivek** [comment] 2022-10-24 07:53
I wasn't able to reproduce this on chrome(android). @Julesssss, are we good to close it then?

**Comment by Julesssss** [comment] 2022-10-24 10:00
> are we good to close it then?

It sounds like this was only occurring on the Samsung `mWeb` browser. My guess is that it's unlikely to be fixable, as Samsung devices have lots of bugs like this, but lets leave it open for now.

**Comment by Julesssss** [comment] 2022-11-02 10:20
Hey @isabelastisser could you please double the bounty? Thanks

**Comment by isabelastisser** [comment] 2022-11-02 18:02
Internal job posting: https://www.upwork.com/ab/applicants/1587865128594698240/job-details

External job posting: https://www.upwork.com/jobs/~01a93f8c0f8635f427

**Comment by Gonals** [comment] 2022-11-07 12:01
Waiting on proposals

**Comment by isabelastisser** [comment] 2022-11-10 12:15
No overdue, waiting for proposals.

**Comment by Julesssss** [comment] 2022-11-14 10:29
Hey @isabelastisser, could we double the bounty again please?

**Comment by shawnborton** [comment] 2022-11-16 20:42
Not overdue

**Comment by JmillsExpensify** [comment] 2022-11-17 21:34
@Julesssss @Gonals To help clear out the extensive backlog of /App bugs, we're putting the spotlight on all bugs older than 4 weeks old. To help unblock the roadmap and get our bug pipeline back in equilibrium, can you:

 - Decide whether any proposals currently meet our guidelines and can be approved as-is
 - For any that can't, please take this issue internal and treat it as one of your highest priorities
 - If you have any questions, don't hesitate to start a discussion in #bug-zero

Thanks everyone!

**Comment by Julesssss** [comment] 2022-11-18 10:33
Closing based on [this](https://github.com/Expensify/App/issues/10347#issuecomment-1288765984) ^

**Closed by Julesssss** 2022-11-18 10:33 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug
