### ISSUE TITLE
Web -  The message "Auth EditTask returned an error" appears when attempting to edit the title of a completed task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26410] opened 2023-08-31 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account
2. Open User B's chat
3. Go to the "Assign task" section
4. Create a task by entering a title
5. Click on the task title field
6. Open another browser and log in to User B's account
7. Open User A's chat and open the task
8. Click on "Mark as done" from UserB's account
9. Go back to User A's account
10. Edit the task title and click on “Save” which you have opened in step 5

## Expected Result:
The RHN should be closed when User B marks the task as done so that User A cannot edit the completed task

## Actual Result:
The "Auth EditTask returned an error" message appears when trying to edit the title of a completed task

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/3686cdf1-d35d-43d0-b18f-56259a050e2f

https://github.com/Expensify/App/assets/93399543/0d4e39cd-ea00-4ea3-9451-aefe77398fa6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692918073657819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jayeshmangwani** [comment] 2023-08-31 16:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When assigned user Mark as done the task and then the creator of the task tries to edit the title we get the error "Auth EditTask returned an error"

### What is the root cause of that problem?
We are not checking on the title page, if the task is marked as done then still we are showing the edit task page, If the task is marked as done then this page should not be accessible

### What changes do you think we should make in order to solve the problem?
On [TaskTitlePage](https://github.com/Expensify/App/blob/main/src/pages/tasks/TaskTitlePage.js) we should add a check that if the task is complete then navigate back to the previous page

```javascript
    useEffect(()=> {
        if(ReportUtils.isCompletedTaskReport(props.report)) {
            Navigation.goBack()
        }
    },[props.report]);

```

**Comment by MitchExpensify** [comment] 2023-09-01 18:21
Closing as a dupe

**Closed by MitchExpensify** 2023-09-01 18:21 UTC
Labels: Daily, Bug
