### ISSUE TITLE
[HOLD for payment 2024-11-20] [$250] Duplicate system message when resolving duplicates selecting "Keep all"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#51493] opened 2024-10-25 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.54-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1729791374775059

## Action Performed:
1. Create a workspace as user A
2. Add user B to the workspace
3. Submit duplicate expenses to the workspace
4. As user A resolve the duplicate expenses by selecting "Keep all"

## Expected Result:
Only one system message "resolved the duplicate" appears
## Actual Result:
Duplicate resolved the duplicate message appears
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  

https://github.com/user-attachments/assets/473fe8fe-5de5-47dc-8ffc-26437defff8f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021849911355476934677</li>
        <li>Upwork Job ID: 1849911355476934677</li>
        <li>Last Price Increase: 2024-10-25</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sakluger</details>

**Comment by JmillsExpensify** [comment] 2024-10-25 20:30
Opening up to the community to see if we can get this long-standing bug fixed.

**Comment by ranli** [comment] 2024-10-27 06:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Duplicate system message("resolved the duplicate") when resolving duplicates selecting "Keep all"

### What is the root cause of that problem?
In `src/libs/actions/Transaction.ts` file, `dismissDuplicateTransactionViolation()` function keeps adding same reporting actions whenever user review and select "keep all" a new submitted duplicate expense. This is because we are using`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}` as the key, so same action get added everytime. 

```
  const optimisticReportActions: OnyxUpdate[] = transactionsReportActions.map((action, index) => ({
      onyxMethod: Onyx.METHOD.MERGE,
      key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}`,
      value: {
          [optimisticDissmidedViolationReportActions.at(index)?.reportActionID ?? '']: optimisticDissmidedViolationReportActions.at(index) as ReportAction,
      },
  }));
```
### What changes do you think we should make in order to solve the problem?
Append the violation type to the key, so the same violation wont be added twice.
```
const optimisticReportActions: OnyxUpdate[] = transactionsReportActions.map((action, index) => ({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}${CONST.VIOLATIONS.DUPLICATED_TRANSACTION}`,
    value: {
        [optimisticDissmidedViolationReportActions.at(index)?.reportActionID ?? '']: optimisticDissmidedViolationReportActions.at(index) as ReportAction,
    },
}));
....
const failureReportActions: OnyxUpdate[] = transactionsReportActions.map((action, index) => ({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}${CONST.VIOLATIONS.DUPLICATED_TRANSACTION}`,
    value: {
        [optimisticDissmidedViolationReportActions.at(index)?.reportActionID ?? '']: null,
    },
}));
...
const successData: OnyxUpdate[] = transactionsReportActions.map((action, index) => ({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}${CONST.VIOLATIONS.DUPLICATED_TRANSACTION}`,
    value: {
        [optimisticDissmidedViolationReportActions.at(index)?.reportActionID ?? '']: {
            pendingAction: null,
        },
    },
}));

...
```

### What alternative solutions did you explore? (Optional)
1. Add a attribute the report action type, so that we can use a dynamic value as the key. This will impact many places, as report action is used by many other components. regression may happen.
2. Filter the action at view level (ReportActionItem component). This component has many business logic, filtering may also cause regression.

### Contributor details
Your Expensify account email: [ranli.ryan@gmail.com](mailto:ranli.ryan@gmail.com) 
Upwork Profile Link: https://www.upwork.com/freelancers/~0184337af0a7f3752b

**Comment by ranli** [comment] 2024-10-27 07:18
Contributor details
Your Expensify account email: [ranli.ryan@gmail.com](mailto:ranli.ryan@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~0184337af0a7f3752b

**Comment by ranli** [comment] 2024-10-27 07:20
Contributor details
Your Expensify account email: ranli.ryan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0184337af0a7f3752b

**Comment by sakluger** [comment] 2024-10-28 16:09
Not overdue - we just got a new proposal yesterday.

**Comment by sakluger** [comment] 2024-10-30 17:53
Hey @ZhenjaHorbach, were you able to review the proposal?

**Comment by ranli** [comment] 2024-10-31 17:58
@ZhenjaHorbach Sure.

To reproduce this bug, you need to enable the beta feature here. Otherwise the "resolve duplicate" button wont show.
https://github.com/Expensify/App/blob/8f3b7e40779e0f82b09daf3cac81e181f7d2d438/src/libs/Permissions.ts#L7
Reproduce video:

[screen-capture (1).webm](https://github.com/user-attachments/assets/c9c17c75-d816-4700-b1f1-08aa80cc0854)

**Comment by ranli** [comment] 2024-10-31 18:00
After fix video:

[screen-capture (2).webm](https://github.com/user-attachments/assets/f33b5352-2b71-46ca-be5c-1a876bc7c415)

**Comment by FitseTLT** [comment] 2024-10-31 23:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Duplicate system message when resolving duplicates selecting "Keep all"

### What is the root cause of that problem?
In most cases, we have a simpler situation with regard to creating optimistic report actions. We will have one report action and one parent report so the BE response will merge the real report action it created that will replace the report action that was created optimistically in FE.
But here for `dismissDuplicateTransactionViolation` it is a bit complicated
https://github.com/Expensify/App/blob/f7f61674a0545a13229e3a1cae26a9e39f049f9a/src/libs/actions/Transaction.ts#L351-L355
we create violation dismiss report actions for every expense report linked to every duplicate transactions and we set it optimistically and then we pass the array of the report actions here to the API
https://github.com/Expensify/App/blob/f7f61674a0545a13229e3a1cae26a9e39f049f9a/src/libs/actions/Transaction.ts#L439
But the problem is the BE is returning the report actions linking them to parent reports that doesn't comply with what we set optimistically. Therefore, report action 1 is set to report 1 optimistically and BE will link, for instance, report action 2 with report 1 so we will have duplicate report actions. If you clear cache the one from the optimistic data will be cleared so there will no more be duplicates.
### What changes do you think we should make in order to solve the problem?

As we are passing only report action id array to the API we will send it a different random report action id array and then we will clear the optimistic report actions we created on successData
https://github.com/Expensify/App/blob/f7f61674a0545a13229e3a1cae26a9e39f049f9a/src/libs/actions/Transaction.ts#L426-L440
```
const successData: OnyxUpdate[] = transactionsReportActions.map((action, index) => ({
        onyxMethod: Onyx.METHOD.MERGE,
        key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${action?.childReportID ?? '-1'}`,
        value: {
            [optimisticDissmidedViolationReportActions.at(index)?.reportActionID ?? '']: null,
        },
    }));

    const params: DismissViolationParams = {
        name: CONST.VIOLATIONS.DUPLICATED_TRANSACTION,
        transactionIDList: transactionIDs.join(','),
        reportActionIDList: optimisticDissmidedViolationReportActions.map(() => NumberUtils.rand64()).join(','),
    };
```
### What alternative solutions did you explore? (Optional)

**Comment by pecanoro** [comment] 2024-11-01 15:40
Thank you for reviewing the proposals! Assigning @FitseTLT to the issue!

**Comment by sakluger** [comment] 2024-11-01 19:00
Sent offers to:

- @FitseTLT - https://www.upwork.com/nx/wm/offer/104700036
- @ZhenjaHorbach - https://www.upwork.com/nx/wm/offer/104700026

**Comment by sakluger** [comment] 2024-11-04 17:55
Hey @FitseTLT, please let us know when you have a PR for this one. Thanks!

**Closed** 2024-11-20 17:27 UTC
Labels: External, Daily, Awaiting Payment, Bug
