### ISSUE TITLE
Profile - The tabs for "Preferred pronouns" or "Set my time zone automatically" are showing white spaces

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13127] opened 2022-11-29 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.  Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Click on Profile
4. Click on “Preferred Pronouns” or “Set my timezone automatically” option

## Expected Result:
The "Preferred Pronouns" or "Set my time zone automatically" tabs should show a selection of pronouns and countries

## Actual Result:
The tabs for "Preferred pronouns" or "Set my time zone automatically" are empty
NOTE: This is happening in the workspace list when creating rooms, Country selection

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- mweb - White background appears
- Android 

**Version Number:** 1.2.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/204540469-f53fd2e1-4e15-4850-a98b-5720e34707c7.mp4

https://user-images.githubusercontent.com/43996225/204540473-75357258-cf68-4585-b413-8662842bce11.mp4
![image (1)](https://user-images.githubusercontent.com/43996225/204541890-fa794ce2-6b4e-4cd1-8d6a-eaaeda7273dc.png)
![image](https://user-images.githubusercontent.com/43996225/204541898-8656e02d-3dc7-43e5-b1d5-929414dcfa88.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Gonals** [comment] 2022-11-29 15:44
I'm not seeing this behavior. What browser are you using?
<img width="382" alt="Screenshot 2022-11-29 at 4 43 56 PM" src="https://user-images.githubusercontent.com/19366280/204575499-71a63735-9693-4204-bbb8-0faa071ecdaa.png">

**Comment by luacmartins** [comment] 2022-11-29 17:25
I'm also not able to reproduce
![Screenshot 2022-11-29 at 9 17 00 AM](https://user-images.githubusercontent.com/22219519/204599376-307f517f-d48f-406a-a30e-5720538def2f.png)

**Comment by pecanoro** [comment] 2022-11-29 19:24
I tried to reproduce on Safari, working just fine as well.

![Monosnap Monosnap 2022-11-29 14-23-52](https://user-images.githubusercontent.com/6474442/204628441-4b924ed1-cb2b-45f4-a330-da6b5b0e6fba.png)

**Comment by luacmartins** [comment] 2022-11-29 19:31
I confirmed that this happens on Windows Chrome

**Comment by mvtglobally** [comment] 2022-11-29 22:32
@pecanoro @Gonals @luacmartins we are seeing the dropdown issue across multiple platforms and places. Should we log them individually  or we can use this issue for tracking. See screenshots 

https://user-images.githubusercontent.com/43995119/204662811-88dd775c-c07a-48c0-9056-e1af02452baa.mp4

![image - 2022-11-29T173056 386](https://user-images.githubusercontent.com/43995119/204662819-fe3940b5-25de-4d0c-9327-acaad4da352e.png)
![IMG_2894](https://user-images.githubusercontent.com/43995119/204662820-f104079c-2f36-4344-a3c9-5ce8fa56ad65.png)
![Screenshot_2022-11-29-23-50-44-39_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/43995119/204662822-7b2c428b-3d1f-4b51-a01e-6346b69341b4.jpg)

**Comment by luacmartins** [comment] 2022-11-29 22:36
No need to log them individually, they all seem to have the same root cause. @pecanoro how's that PR coming along?

**Comment by luacmartins** [comment] 2022-11-30 16:50
This was fixed by https://github.com/Expensify/App/pull/13174. Closing.

**Closed by luacmartins** 2022-11-30 16:50 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Hourly
