### ISSUE TITLE
LHN - Last message is not displayed when delete Task from 1:1 chat

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49399] opened 2024-09-18 15:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4979851&group_by=cases:section_id&group_order=asc&group_id=291935
**Email or phone of affected tester (no customers):** gocemate+a2172@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to FAB> Start chat> Complete the flow
2. Type "Hello" into chat composer> Send the message
3. Verify that "Hello" is displayed as recent message in LHN
4. Go to +> Assign task> Complete the flow
5. Delete the task
6. Take a look at recent message of 1:1 chat in LHN

## Expected Result:
"Hello" should be the last message displayed in 1:1 chat in LHN

## Actual Result:
"This is the beginning of your chat with ..." is displayed on 1:1 chat as recent message in LHN

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e0b31925-24dc-4faf-b2d1-3426c3fb8466

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-18 15:50
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by FitseTLT** [comment] 2024-09-18 18:19
BE bug: not updating lastMessageText properly

**Comment by Christinadobrzyn** [comment] 2024-09-18 19:12
Oh interesting catch! I can reproduce this following the steps in the OP. Adding internal label (thanks for checking that @FitseTLT).

**Comment by Christinadobrzyn** [comment] 2024-09-21 22:29
waiting for a volunteer to grab this

**Comment by Christinadobrzyn** [comment] 2024-09-23 21:27
moving to weekly while we wait on a volunteer.

**Comment by Christinadobrzyn** [comment] 2024-09-30 06:02
posting for a volunteer - https://expensify.slack.com/archives/C06ML6X0W9L/p1727676111203019

**Comment by Christinadobrzyn** [comment] 2024-10-01 01:21
Sounds like the decision is to close this out since we're only focused on tasks related to onboarding and not 1:1 chat. Closing this without action.

**Closed by Christinadobrzyn** 2024-10-01 01:21 UTC
Labels: Daily, Internal, Bug, Hot Pick
