### ISSUE TITLE
Dev: No functionality to request money but message displays the opposite

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22475] opened 2023-07-08 11:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. On dev web chrome
2. Create a new workspace and invite a member to the workspace
3. On LHN, click on the combined workspace + user chat
4. The message displays 'Collaboration between user1 and user's Workspace starts here! :tada: This is the place to chat, REQUEST MONEY and settle up.'
5. If clicked on + button on the chat, you can see no Request money functionality is being displayed which is opposite to the message being shown.

## Expected Result:
Either request money should be shown on clicking + button OR the message ''This is the place to chat, request money and settle up.' should remove the 'Request money' part

## Actual Result:
No functionality to request money but message displays the opposite

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5 dev 
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ebebfe9d-2ca6-42a9-bdab-d6d5645b9a61

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688733753494609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by NicMendonca** [comment] 2023-07-10 14:04
@Beamanator since this is a dev bug, would you mind triaging for me? 🙏

**Comment by Beamanator** [comment] 2023-07-11 07:54
Sure thing! Will do now!

**Comment by Beamanator** [comment] 2023-07-11 08:03
Hmm I invited a member to a workspace but I didn't see that new workspace chat from the OP - @NicMendonca are you able to reproduce that on staging?

**Comment by Beamanator** [comment] 2023-07-11 11:06
Hmm I do see this room created in dev - but I do see the "Request money" option - this could be a betas mismatch issue

**Comment by NicMendonca** [comment] 2023-07-14 09:03
@Beamanator I was not able to reproduce 😓

**Comment by NicMendonca** [comment] 2023-07-17 11:37
@Beamanator are we closing this?

**Comment by Beamanator** [comment] 2023-07-18 09:12
I think we can close - if this is only reproducible on dev and never makes it to staging, we probably don't need to change anything, right?

**Closed** 2023-07-18 13:24 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
