### ISSUE TITLE
[HOLD for payment 2024-06-13] [HOLD for payment 2024-06-11] Unable to open composer + menu and FAB menu after refreshing RHP

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42912] opened 2024-05-31 10:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.78-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Click on the chat header.
4. Refresh the page while RHP is open.
6. Click outside the RHP to dismiss it.
7. Click + button next to the composer.
8. Click FAB button.

## Expected Result:
Menu will open when clicking on composer + button and FAB button after refreshing RHP.

## Actual Result:
Menu does not open when clicking on composer + button and FAB button after refreshing RHP.
Also, right-click menu also does not open after refreshing RHP.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/89345840-367e-434c-a015-c973019d6ff0

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @MitchExpensify</details>

**Comment by izarutskaya** [comment] 2024-05-31 10:31
@MitchExpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-31 10:31
We think this issue might be related to the #vip-vsb

**Comment by izarutskaya** [comment] 2024-05-31 10:32
production 


https://github.com/Expensify/App/assets/115492554/dd894114-1b0f-47e2-93a4-0d2ecb402135

**Comment by bernhardoj** [comment] 2024-05-31 12:13
Same root cause as https://github.com/Expensify/App/issues/42911

**Comment by danieldoglas** [comment] 2024-06-02 19:05
I think the proposals in #42911 will fix this, so I'm not exporting it.

**Comment by danieldoglas** [comment] 2024-06-02 19:05
Removing deploy blocker since this was not caused by API changes, leaving deployblcokercash.

**Comment by Julesssss** [comment] 2024-06-03 14:37
> I think the proposals in #42911 will fix this, so I'm not exporting it.

FYI we don't have a solution for this yet. We have a proposal but need more eyes on this as this is the only remaining blocker

**Comment by roryabraham** [comment] 2024-06-03 16:44
@danieldoglas why did you make this a `Daily`? Since it's still a deploy blocker, it should be `Hourly`. It's also on HOLD for something that's not a deploy blocker, which doesn't really make sense priority-wise.

**Comment by danieldoglas** [comment] 2024-06-03 16:47
The issue this was linked to (https://github.com/Expensify/App/issues/42911) was demoted as a deploy blocker today after I added HOLD on this one. The solutions being discussed there were solve the issues being described here, which is why I didn't think it made sense to put both as external.

**Comment by roryabraham** [comment] 2024-06-03 16:48
I agree having a duplicate issue being made external doesn't make sense. going to continue discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1717186513798119)

**Comment by roryabraham** [comment] 2024-06-03 22:14
I'm hoping this will be fixed by https://github.com/Expensify/App/pull/43013. Going to test to confirm.

**Comment by roryabraham** [comment] 2024-06-03 22:17
Confirmed this is fixed by https://github.com/Expensify/App/pull/43013

**Comment by roryabraham** [comment] 2024-06-06 17:04
C+ payment due to @hoangzinh for this one.

**Comment by MitchExpensify** [comment] 2024-06-07 23:43
Reminder set to pay

**Comment by MitchExpensify** [comment] 2024-06-15 20:47
Contract ended and paid, thanks @hoangzinh

**Closed** 2024-06-15 20:47 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
