### ISSUE TITLE
Can't set distance rate on a new workspace, Oops... something went wrong error appears

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#39341] opened 2024-03-31 22:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.58-2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with a new expensifail account
2. Create a new workspace
3. Enable distance rates in the More features tab
4. Navigate to Distance rates
5. Tap on the distance rate
6. Tap on the rate
7. Change the rate and save it
## Expected Result:
I should be able to set a new rate without errors.

## Actual Result:
I can't set distance rate on a new workspace, "Oops... something went wrong" error appears when I try. Sometimes I get a Hmm... it's not here" error when trying to open the rate.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a6a2a59c-bda2-41db-b283-b1570f3015ab

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-04-01 16:39
@deetergp do you think this should be a deploy blocker? I can reproduce

**Comment by tgolen** [comment] 2024-04-01 20:03
I think it should, yes. This is related to the new collect workspaces being created. I'm guessing the backend is throwing an error. Can someone please get the requestID of the failed API call or at least post the login of the account you used to reproduce the issue?

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:17
Yep, one sec!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:22
The account I used earlier today was jkaufman+18@expensifail.com. However, I'm trying to get a requestID for a new attempt and I can't reproduce this now on staging any longer. @tgolen are you still able to reproduce it?

**Comment by joekaufmanexpensify** [comment] 2024-04-01 20:25
Cool. Yeah it worked for me on two different accounts just now too.

**Comment by tgolen** [comment] 2024-04-01 20:25
I guess since neither of us can reproduce it, I'll close this for now. Thank you, Joe!

**Closed** 2024-04-01 20:25 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Bug
