### ISSUE TITLE
Android - Not here page shows up after deleting workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38301] opened 2024-03-14 12:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Go to Profile > Workspaces > any workspace.
3. Go to Profile.
4. Tap Delete.
5. Delete the workspace.

## Expected Result:
App will redirect to All workspaces page.

## Actual Result:
Not here page shows up after deleting workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0af5cf75-7701-4edb-9e7f-61003ddc9c8f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by izarutskaya** [comment] 2024-03-14 12:31
@pecanoro I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-03-14 12:31
We think that this bug might be related to #wave-collect - Release 1
CC @trjExpensify

**Comment by mountiny** [comment] 2024-03-14 13:01
Might be related to the ideal nav PR

**Comment by kosmydel** [comment] 2024-03-14 13:53
Hey, I'm from Software Mansion I'm going to investigate it.

**Comment by jayeshmangwani** [comment] 2024-03-14 17:46
Sorry for the confusion @mkhutornyi, I skipped the process and reviewed the PR, next time I will keep in mind to first tag the C+ of the offending PR

**Comment by luacmartins** [comment] 2024-03-14 17:58
I can still reproduce this in staging after the CP

https://github.com/Expensify/App/assets/22219519/f20b795e-e146-4328-aa61-aba8e44c5a6b

**Comment by kosmydel** [comment] 2024-03-15 09:16
> I think this might be related to Ideal Nav v2 @WojtekBoman @mountiny. I'm gonna demote it to NAB since the user is no longer stuck in the not found page, but we need to look into this and prevent the not found page to be shown.

Oh, sorry for the inconvenience. I must have missed that there is a short glimpse of that not-found screen. Glad that it at least stopped being a deploy blocker. 

I or @WojtekBoman will look at this on Monday because today I'm only at for a while at work and it is no longer a deploy blocker.

**Comment by bfitzexpensify** [comment] 2024-04-05 16:00
Thanks for the bump @jayeshmangwani - offer sent.

**Comment by jayeshmangwani** [comment] 2024-04-05 16:04
Thanks, offer accepted

**Comment by bfitzexpensify** [comment] 2024-04-05 16:27
Payment complete, closing this out.

**Closed by bfitzexpensify** 2024-04-05 16:27 UTC
Labels: Reviewing, Engineering, Weekly, Bug
