### ISSUE TITLE
[$500] Public room - Public room disappears in LNH

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43770] opened 2024-06-14 13:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83- 0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4599455
**Email or phone of affected tester (no customers):** monitozb87+admin2305@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites:
1. User not logged in New Expensify
2. Navigate to this link - https://staging.new.expensify.com/r/2652281908731856
3. Log in with an existing account
4. Verify the room is still displayed after login in
5. Click on the back button to navigate back to LHN

## Expected Result:
Verify you can see the public room in the LHN

## Actual Result:
I can't see the public room in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fa6ee40e-0c76-43bf-a97a-9b6fcae11904

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d646141e4b224feb</li>
        <li>Upwork Job ID: 1802876107834769220</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

**Comment by rigestshala** [comment] 2024-06-18 22:57
Could not reproduce

**Comment by johncschuster** [comment] 2024-06-21 21:08
This just got triaged recently. Still waiting on proposals.

**Comment by johncschuster** [comment] 2024-06-21 21:11
This just got triaged recently. Still waiting on proposals.

**Comment by johncschuster** [comment] 2024-06-24 20:43
Still waiting on proposals

**Comment by johncschuster** [comment] 2024-06-27 21:21
Still waiting on proposals

**Comment by johncschuster** [comment] 2024-07-01 21:09
Raised in [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1719868164749019) that we're looking for proposals.

**Comment by johncschuster** [comment] 2024-07-08 21:03
Bumped one more time for proposals.

**Comment by johncschuster** [comment] 2024-07-11 20:38
Ok, we may need to escalate this to an agency. I'm going to have it retested first to make sure the behavior persists. ([Slack](https://expensify.slack.com/archives/C9YU7BX5M/p1720730263759449))

**Comment by wasxxm** [comment] 2024-07-14 20:43
Are you still looking for proposals?

**Comment by kavimuru** [comment] 2024-07-14 22:12
Bug is fixed

https://github.com/user-attachments/assets/f41f1097-7ff4-414a-a24d-4157f072d3d0

**Comment by kavimuru** [comment] 2024-07-15 19:57
Bug is not reproducible 

https://github.com/user-attachments/assets/6c5b2f7d-0718-43ca-b52e-8f7bcc3a2447

**Comment by johncschuster** [comment] 2024-07-15 20:12
Thanks for the re-test! Given it is no longer reproducible. I think we can close this.

**Closed by johncschuster** 2024-07-15 20:12 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
