### ISSUE TITLE
[$500] IOU - Description entered as "0" disappears after selecting a category while making money request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30197] opened 2023-10-23 18:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.89-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab
3. Tap request money---manual
4. Enter an amount
5.Tap next
6. Select a Workspace
7. Tap Request amount
8. Tao on IOU to open IOU detail page
9. Tap on description and enter zero "0" and save
10. Tap on category and select any category
11. Scroll up to see the description section

## Expected Result:
Description entered as zero "0" must not disappear after selecting a category while making money request with a workspace

## Actual Result:
Description entered as zero "0" disappears after selecting a category while making money request with a workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/bb2a57c8-01a8-4879-86dd-03825bb94ee0

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a3dd7030d48e5a3</li>
        <li>Upwork Job ID: 1716525848525471744</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-10-23 19:51
When entered only number in description backend is sending description in number format, this is additionally causing app to crash when opening description

I think this should be fixed in backend where description type always should be a string
<img width="852" alt="Screenshot 2023-10-24 at 00 48 50" src="https://github.com/Expensify/App/assets/59907218/7c3f4d8c-756d-4168-a1cd-eec5f3f780c9">


https://github.com/Expensify/App/assets/59907218/283c14af-2f2a-4376-a2a3-ccff3685c79d

**Comment by iiredalert** [comment] 2023-10-23 20:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we enter 0 as a description for an IOU, it does not reflect the value we entered when the IOU is viewed.

### What is the root cause of that problem?
Even though we save the 0 as a string type, when it is getting loaded it comes back as a number and the getDescription function in TransactionUtils.ts is returning a '' instead of the number.

### What changes do you think we should make in order to solve the problem?

In TransactionUtils.ts, update the getDescription() function to convert the comment to a string.
```
function getDescription(transaction: Transaction): string {
    return transaction?.comment?.comment?.toString() ?? '';
}
```

### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment] 2023-10-24 03:39
@alitoshmatov While it would be ideal for the backend to return numeric values as strings, I think we can move forward with a proposal here since it's fixable in the app.

**Comment by akinwale** [comment] 2023-10-24 03:39
Both proposals by @yh-0218 and @iiredalert correctly identify the root cause, and their corresponding solutions work as expected. However, since this is a simple, straightforward fix and the [proposal](https://github.com/Expensify/App/issues/30197#issuecomment-1775953418) by @yh-0218 was posted first, I recommend we go with @yh-0218's proposal.

@yh-0218  It's a cleaner approach to place the `toString()` method in the `TransactionUtils.getDescription` method implementation. Also, in the future, please flesh out your proposals more. In your proposal for this issue, the root cause can be described in more detail.

🎀 👀 🎀 C+ reviewed.

**Comment by paultsimura** [comment] 2023-10-24 06:02
This has a way older duplicate – https://github.com/Expensify/App/issues/26665, and it's been taken internally: https://github.com/Expensify/App/issues/26665#issuecomment-1775197275

**Comment by akinwale** [comment] 2023-10-24 06:50
This can be closed then.

**Closed** 2023-10-24 17:12 UTC
Labels: External, Daily, Help Wanted, Bug
