### ISSUE TITLE
[HOLD for payment 2024-01-02] [$500] Web - Search - Selected dropdown item with tab key is not opened in Search

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32388] opened 2023-12-01 22:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.7-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login to ND Expensify
2. Press CTRL+K or click Magnifying glass icon
3. Select any dropdown item with Tab key
4. Press Enter key

## Expected Result:
Items in search dropdown should be selected consistently both with up&down and tab keys, and the correct one is opened after pressing Enter key

## Actual Result:
Highlighted item (default first one) with Up&Down keys is opened instead of blue bordered item which is selected with Tab key

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/312f7a06-fa7d-4f6d-837b-19943167f303

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015640f29df912d30c</li>
        <li>Upwork Job ID: 1730709594365632512</li>
        <li>Last Price Increase: 2023-12-01</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28062509</li>
<li>DylanDylann | Contributor | 28062510</li>
</ul></li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-01 22:50
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Highlighted item (default first one) with Up&Down keys is opened instead of blue bordered item which is selected with Tab key
### What is the root cause of that problem?
The root cause is that the pressOnEnter is set on Confirm button and it's priority is 1 so when we click enter, the button is pressed first.
https://github.com/Expensify/App/blob/db37e46f58aceea23c0136e1bdce6e3ed9d2d90f/src/components/OptionsSelector/BaseOptionsSelector.js#L656-L662
### What changes do you think we should make in order to solve the problem?
we need to adjust button's priority here.

### What alternative solutions did you explore? (Optional)
  N/A

**Comment by DylanDylann** [comment] 2023-12-02 03:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Web - Search - Selected dropdown item with tab key is not opened in Search 

### What is the root cause of that problem?
- We're selecting the row based on highlighted item, and we don't consider the blue focus one
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/OptionsSelector/BaseOptionsSelector.js#L302-L325

### What changes do you think we should make in order to solve the problem?
- Generally, we need to change the logic that we use to get ```focusedOption```:
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/OptionsSelector/BaseOptionsSelector.js#L303
- Now, it only based on the ```this.state.focusedIndex```, so if there is another option is select by tab key, we will not consider it.
- To implement the above idea:
1. Passing additional prop named ```keyForList``` to [OptionRow](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/OptionsList/BaseOptionsList.js#L201). It will become to:
```
            <OptionRow
                keyForList={item.keyForList}
```
2. Then, pass the above ```keyForList``` props to [PressableWithFeedback](https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/OptionRow.js#L164)
It will become to:
```
                    <PressableWithFeedback
                        testID={props.keyForList}
``` 
3. Finally, update the logic to get the ```focusedOption``` in here:
https://github.com/Expensify/App/blob/1682be47d71b5a84c20c2396e833c0a015829252/src/components/OptionsSelector/BaseOptionsSelector.js#L303
It will become to:
```
const focusedItemKey = lodashGet(e, ['target', 'attributes', 'data-testid', 'value']);
        const focusedOption = focusedItemKey ? _.find(this.state.allOptions, (option) => option.keyForList === focusedItemKey) : this.state.allOptions[this.state.focusedIndex];
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by alexpensify** [comment] 2023-12-04 21:40
@alitoshmatov please keep us posted if any of the proposals will fix this issue. Thanks!

**Comment by sourcecodedeveloper** [comment] 2023-12-04 23:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN search can not select item using tab key.

### What is the root cause of that problem?
The ArrowKeyFocusManager is setup for arrowupkey and arrowdownkey only. When the user tabs through the list and presses enter, the highlighted item is opened.

### What changes do you think we should make in order to solve the problem?
The BaseOptionsSelector.js and the BaseSelectionList.js would need to be able to select items using tab key. The ArrowKeyFocusManager.js can subscribe to Tab key and then call focus() on the item selected by tab key. 

In CONST.ts
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/CONST.ts#L407
need to add tab trigger
```
trigger: {
    DEFAULT: {input: 'tab'},
    [PLATFORM_OS_MACOS]: {input: 'tab'},
    [PLATFORM_IOS]: {input: 'tab'},
}
```

In ArrowKeyFocusManager
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/ArrowKeyFocusManager.js#L36
Add tab shortcut
```
const tabConfig = CONST.KEYBOARD_SHORTCUTS.TAB;
this.onTabKey = this.onTabKey.bind(this);
```

Add callback for tab,
```
onTabKey() {
    if (this.props.maxIndex < 0) {
        return;
    }

    const currentFocusedIndex = this.props.focusedIndex < this.props.maxIndex ? this.props.focusedIndex + 1 : 0;
    let newFocusedIndex = currentFocusedIndex;

    while (this.props.disabledIndexes.includes(newFocusedIndex)) {
        newFocusedIndex = newFocusedIndex < this.props.maxIndex ? newFocusedIndex + 1 : 0;
        if (newFocusedIndex === currentFocusedIndex) {
            // all indexes are disabled
            return; // no-op
        }
    }

    this.props.onFocusedIndexChanged(newFocusedIndex);
}
```

The above steps are sufficient to select items using tab key in both BaseOptionsSelector.js and BaseSelectionList.js. The only thing that would not be visible is the blue border around the highlighted item. Next steps are to get the blue border around the highlighted item for tab key.
The steps covered are for BaseOptionsSelector only and BaseSelectionList would also need to be modified.

Add prop function to ArrowKeyFocusManager
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/ArrowKeyFocusManager.js#L6
`onTabFocusChanged: PropTypes.func,`

set onTabFocusChange to
`onTabFocusChanged={() => this.list.props.extraData.current.focus()} `

https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/OptionsSelector/BaseOptionsSelector.js#L572

In the callback for tab after calling onFocusedIndexChanged,
this.props.onTabFocusChanged();

In BaseOptionsList.js need to add const focusedOptionRef
const focusedOptionRef = useRef();

pass focusedOptionRef as prop to OptionRow
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/OptionsList/BaseOptionsList.js#L201

In OptionRow.js
need to set focusedOptionRef to focused item
https://github.com/Expensify/App/blob/414c08ce28916817b54239f3f49ef455293cfa45/src/components/OptionRow.js#L165
```
if(props.optionIsFocused)
{
    props.focusedOptionRef.current = el;
}
```

**Comment by alitoshmatov** [comment] 2023-12-06 19:17
Reviewing

**Comment by alitoshmatov** [comment] 2023-12-07 18:22
@unicorndev-727 I don't think confirm button is related here.

**Comment by alitoshmatov** [comment] 2023-12-07 18:35
@sourcecodedeveloper I think binding tab key to our selection will effect native accessibility that used by tab key. Moreover 
as @DylanDylann mention https://github.com/Expensify/App/pull/32252 PR already solved similar issue, and logical approach would be applying consistent, similar approach here.

**Comment by alitoshmatov** [comment] 2023-12-07 18:38
@DylanDylann your RCA is correct. Your solution looks good also as you mention we can follow https://github.com/Expensify/App/pull/32252 PR and apply the same solution here. But can you make sure we are covering all instances of this issue so that we don not come across similar one again.

**Comment by DylanDylann** [comment] 2023-12-07 19:00
@situchan I think the https://github.com/Expensify/App/issues/31635 is fixed, so, for consistency, I think we should fix this issue as well

**Comment by alitoshmatov** [comment] 2023-12-11 16:27
I agree with @DylanDylann, @deetergp Can you confirm this?

**Comment by alexpensify** [comment] 2023-12-13 23:07
@deetergp - can we get feedback here? Let me know if we need to have a bigger discussion in Open Source. Thanks!

**Comment by deetergp** [comment] 2023-12-15 16:42
I agree, let's go with @DylanDylann's proposal.

**Comment by alexpensify** [comment] 2023-12-18 23:52
@DylanDylann how's the proposal going? I don't see a PR associated with this GH yet. Thanks!

**Comment by DylanDylann** [comment] 2023-12-19 04:15
@alitoshmatov PR #33265 is ready to review

**Comment by alexpensify** [comment] 2023-12-21 00:00
Daily Update: PR is in review!

**Comment by alexpensify** [comment] 2023-12-23 18:39
**Heads up, I will be offline from Friday, December 22, to Thursday, January 4, 2024. I will not be actively watching over this GitHub during that period. If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!**

**Comment by alexpensify** [comment] 2023-12-29 18:16
Here is the payment summary-- TBD, @alitoshmatov please confirm if this regression is due to this PR or something else. Thank you! 

-  External issue reporter - N/A 
-  Contributor that fixed the issue - @DylanDylann  
-  Contributor+ that helped on the issue and/or PR - @alitoshmatov 

Upwork Job: https://www.upwork.com/jobs/~015640f29df912d30c

Extra Notes regarding payment: Heads up, I'm OOO until January 4, but I will log in on Wednesday, January 3 to check this payment process pending if the regression is resolved by then. I've confirmed that everyone here is a pending hire, so all set here for the payment date.

**Comment by alexpensify** [comment] 2024-01-03 18:42
@alitoshmatov or @deetergp - can you please help confirm if this PR did cause regression? Thanks!

**Comment by alitoshmatov** [comment] 2024-01-04 13:25
Based on my observation, our PR didn't directly cause this regression, the regression didn't occur after merging our PR. However our solution was based on faulty approach which was already implemented by https://github.com/Expensify/App/pull/32252. We took this solution for granted and followed the same approach. Finally https://github.com/Expensify/App/pull/33491 PR caused the regression which broke our faulty solution. I am okay if penalty is applied to my payment, since I should have been more cautious on my review.

cc: @alexpensify, @deetergp, @Beamanator (since you worked on fixing the regression)

**Comment by alexpensify** [comment] 2024-01-05 00:14
Thank you @alitoshmatov for this update. @Beamanator and @deetergp can I get some feedback here regarding this payment? Thanks!

**Comment by alexpensify** [comment] 2024-01-08 22:22
Bumping - @deetergp and @Beamanator can I get your feedback here?

**Comment by Beamanator** [comment] 2024-01-10 12:24
I agree with @alitoshmatov 's summary here: https://github.com/Expensify/App/issues/32388#issuecomment-1877091604
1. The PR for this issue (https://github.com/Expensify/App/pull/33265) was merged 3 weeks ago
2. The PR which technically caused the regression was https://github.com/Expensify/App/pull/33491, which was merged 2 weeks ago

While the PR for this issue and [this one](https://github.com/Expensify/App/pull/32252) were a bit iffy & weren't perfect, they didn't cause the regressions so I don't believe payment here should have the penalty applied

**Comment by alexpensify** [comment] 2024-01-11 00:08
Thanks, I'll work on the payment process tomorrow.

**Comment by alexpensify** [comment] 2024-01-11 22:01
Closing - I updated the summary here: https://github.com/Expensify/App/issues/32388#issuecomment-1872257819

Everyone has been paid via Upwork and I closed that job.

**Closed by alexpensify** 2024-01-11 22:01 UTC
Labels: External, Daily, Awaiting Payment, Bug
