### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Editing just emoji on a chat cuts the top part on android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19605] opened 2023-05-25 12:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to android
2. Go to any chat
3. Send just emoji
4. Now edit the message and add one more emoji and save it (Do not add any text)
5. Notice that the top part of the emoji message is totally cut off

## Expected Result: 
The top part of emoji should not be cut off on editing the emoji message
## Actual Result: 
The top part of the emoji is cut off on editing the emoji message

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:**n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ddde1d1b-ccd3-4bad-88fe-76a9bf2c8723

https://github.com/Expensify/App/assets/43996225/3147680b-013a-4108-a423-f97e4be26bd4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685014708492129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c149c7f2dfb4aae</li>
        <li>Upwork Job ID: 1661744463659536384</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by lschurr** [comment] 2023-05-25 14:36
@cristipaval - does this need to go through the typical Bug Zero process? Should I be testing and adding External or is this an Internal fix?

**Comment by cristipaval** [comment] 2023-05-25 14:37
Hmm.. it looks like this is a deploy blocker. Let me triage this one.

**Comment by cristipaval** [comment] 2023-05-25 14:41
This also happens in production 1.3.17-5
Not a deploy blocker, so making it external.

**Comment by kushu7** [comment] 2023-05-25 17:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Editing just emoji on a chat cuts the top part on android
### What is the root cause of that problem?
Its happening because space between message and edited text.
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/home/report/ReportActionItemFragment.js#L126-L131
We are not providing fontSize or lineHeight to it. so its uses default `variables.fontSizeNormalHeight` depends on metrics. if its smaller than `styles.onlyEmojisText` then we can see kind of behavior.
### What changes do you think we should make in order to solve the problem?
We have 2 ways to fix it. first is we can provide same fontFamily as its parent:
- 1st option:
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/home/report/ReportActionItemFragment.js#L122
```js
 <Text
    fontSize={variables.fontSizeSmall} <-- add this
    selectable={false}
    ...
>
    {' '}
</Text>
```
- 2nd Option
If we want to keep spacing of `fontSizeNormal` then we can provide lineHeight to styles of `Space Text` same as `onlyEmojisText.lineHeight` only when `EmojiUtils.containsOnlyEmojis(text)` is true.

IMO, 2nd option is good it will keep same spacing between edited and message.



### What alternative solutions did you explore? (Optional)
None

**Comment by AlexanderDmitriev** [comment] 2023-05-25 18:47
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Editing just emoji on a chat cuts the top part on android

### What is the root cause of that problem?
Space between `emojis` and `(edited)` was problem
https://github.com/Expensify/App/blob/fe67d69c9043734486c6a639a0d3ba66d5440a04/src/pages/home/report/ReportActionItemFragment.js#L126-L131

### What changes do you think we should make in order to solve the problem?
Remove the `Text` element for `space` and add `space` like this:

                    {Boolean(props.fragment.isEdited) && (
                        <Text
                            fontSize={variables.fontSizeSmall}
                            color={themeColors.textSupporting}
                            style={[styles.alignItemsBaseline, editedLabelStyles]}
                        >
                            {` ${props.translate('reportActionCompose.edited')}`}
                        </Text>
                    )}

### What alternative solutions did you explore? (Optional)
N/A

**Comment by qasimkhan23** [comment] 2023-05-26 07:59
Contributor details
Your Expensify account email: <kqasim109@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01e6450b44146c99e7>

**Comment by qasimkhan23** [comment] 2023-05-26 08:05
Contributor details
Your Expensify account email: <qasiminssi@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~01e6450b44146c99e7>

**Comment by qasimkhan23** [comment] 2023-05-26 08:22
Contributor details
Your Expensify account email: kqasim109@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e6450b44146c99e7

**Comment by mananjadhav** [comment] 2023-05-28 18:58
Thanks for the proposals folks. I don't think ` {` ${props.translate('reportActionCompose.edited')}`}` is a good idea as we had it earlier and adding it back will cause a regression.


@kushu7 quick question,

> If we want to keep spacing of fontSizeNormal then we can provide lineHeight to styles of Space Text same as 
 onlyEmojisText.lineHeight only when EmojiUtils.containsOnlyEmojis(text) is true.

Sorry I don't understand. Are you saying for emoji you want to set `onlyEmojisText.lineHeight`, and if false then what?

**Comment by kushu7** [comment] 2023-05-29 02:34
> 
> @kushu7 quick question,
> 
> > If we want to keep spacing of fontSizeNormal then we can provide lineHeight to styles of Space Text same as
> > onlyEmojisText.lineHeight only when EmojiUtils.containsOnlyEmojis(text) is true.
> 
> Sorry I don't understand. Are you saying for emoji you want to set `onlyEmojisText.lineHeight`, and if false then what?

Then nothing is required, as `Text` component will set lineHeight to fontSizeNormalHeight default.

**Comment by mananjadhav** [comment] 2023-05-29 23:15
@cristipaval I think @kushu7's solution will work here. I did a quick test and it worked, but will have to test thoroughly for regression, which can be done during the PR.

**Comment by kushu7** [comment] 2023-05-30 06:16
hello, thank you for the assignment, PR is ready for initial review @mananjadhav @cristipaval @lschurr

**Comment by mananjadhav** [comment] 2023-05-30 06:20
@kushu7 when you say initial review, do you mean any work/item from the checklist is pending?

**Comment by kushu7** [comment] 2023-05-30 06:23
> @kushu7 when you say initial review, do you mean any work/item from the checklist is pending?

No, nothing is pending.
its my first time contributing to Expensify.

PR is ready for review.

**Comment by mananjadhav** [comment] 2023-05-30 06:32
Okay thanks for the PR @kushu7.

**Comment by kushu7** [comment] 2023-05-31 04:33
Hello guys, I submitted PR but CLA assistant is showing failed. Can someone re-run on my PR please? @mananjadhav @cristipaval @lschurr

**Comment by mananjadhav** [comment] 2023-05-31 05:08
Thanks for the ping @kushu7. @cristipaval will get it checked. No action needed from your end.

**Comment by laurenreidexpensify** [comment] 2023-06-05 09:59
@lschurr heads up for payment it looks like @pubudu-ranasinghe actually reported this issue on 22 May - see https://expensify.slack.com/archives/C049HHMV9SM/p1684775756347189 - which led to the creation of this https://github.com/Expensify/App/issues/20083, which is a dupe of this. Can we please compensate @pubudu-ranasinghe $250 for the bonus here too, as well as @priya-zha as this was our error. Thanks

**Comment by lschurr** [comment] 2023-06-08 21:35
@pubudu-ranasinghe @priya-zha @mananjadhav @kushu7 - can you apply for the job in Upwork? https://www.upwork.com/jobs/~014c149c7f2dfb4aae

**Comment by priya-zha** [comment] 2023-06-09 03:28
Submitted the proposal. Thanks.

**Comment by mananjadhav** [comment] 2023-06-09 13:27
@lschurr The job leads to me a login page, and then after logging in, it doesn't redirect to the job post. Can you please send an invite?

**Comment by lschurr** [comment] 2023-06-09 15:11
Hmm @mananjadhav try logging in first and then click the job link? https://www.upwork.com/jobs/~014c149c7f2dfb4aae 

Otherwise, can you send me your profile and I'll try inviting you

**Comment by mananjadhav** [comment] 2023-06-09 15:29
@lschurr https://www.upwork.com/freelancers/~01916123f547b928d6  For some reason my session times out every time with Upwork.

**Comment by mananjadhav** [comment] 2023-06-11 22:51
@lschurr Here's are the items from the checklist.

1. Offending PR https://github.com/Expensify/App/pull/18523
2. Commented on the PR https://github.com/Expensify/App/pull/18523/files#r1225946551
3. I don't think we need any changes in the checklist. This was an edge case which required only emojis to reproduce.
4. I think it makes sense to add regression test for this one, so that we don't leave out `only emojis` test during editing the chat. Test steps from the PR look good for the regression test.

**Comment by lschurr** [comment] 2023-06-12 18:02
@mananjadhav - I sent an invite to the job in Upwork.

@pubudu-ranasinghe please apply to the job in Upwork: https://www.upwork.com/jobs/~014c149c7f2dfb4aae

**Comment by mananjadhav** [comment] 2023-06-13 03:07
Applied @lschurr. Thank you!

**Comment by lschurr** [comment] 2023-06-13 17:22
Great, just need @pubudu-ranasinghe to accept the offer in Upwork.

I'll create a GH for a new regression test today.

**Comment by mananjadhav** [comment] 2023-06-13 17:28
@lschurr this issue is eligible for the timeline bonus. Can you please help with the same?

**Comment by lschurr** [comment] 2023-06-13 17:40
Done!

**Comment by mananjadhav** [comment] 2023-06-13 17:51
Thanks @lschurr for the prompt action!

**Comment by lschurr** [comment] 2023-06-14 15:34
Done: https://github.com/Expensify/Expensify/issues/291734

**Closed by lschurr** 2023-06-14 15:34 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
