### ISSUE TITLE
[$1000] Chat - Adding dot to edited link and non edited link creates different result

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#25532] opened 2023-08-19 16:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Send link with multiple slash separator eg: https://staging.new.expensify.com/get-assistance/WorkspaceGeneralSettings
3. Edit the link and add '.' (fullstop) in the end of link part and save
4. Observe the result
5. Again send similar or same multiple slash separated link
6. This time on edit, first add valid character in the end of the link part like letter or number
7. Again edit, remove the character added in step 6 and add '.' fullstop in place of it, observe that now message is displayed differently then step 4

## Expected Result:
App should display in similar format if we add character in edited link then in non edited link

## Actual Result:
 App displays link in different format if we add dot character in edited link then in non edited link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] Windows / Chrome

**Version Number:** 1.3.55-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0e6afa33-a1dc-4b96-8f47-a180847e443b

https://github.com/Expensify/App/assets/78819774/47bdc0bb-7ce5-4093-8693-6b1923ed7144

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant
 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691601704532849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e9f2df956de96c7</li>
        <li>Upwork Job ID: 1693728746118950912</li>
        <li>Last Price Increase: 2023-08-28</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26648942</li>
<li>ShogunFire | Contributor | 26648944</li>
<li>Dhanashree-Sawant | Reporter | 26648946</li>
</ul></li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-08-21 18:05
I found the root cause but I am not sure what is expected, I am not even sure if this is a bug.



When we transfrom the comment in html, we transform the markdown `[text](url)` to `<a href=url>text<a/>` here:

https://github.com/Expensify/expensify-common/blob/5ab0cf3280b3d8fb0c100c5eefe5337a24dc2768/lib/ExpensiMark.js#L70-L85

But when we add a dot at the end of the url it's not recognized as a url so this transformation doesn't happen.

Later we transfrom the links that are not already in `<a>` to `<a>` here:

https://github.com/Expensify/expensify-common/blob/5ab0cf3280b3d8fb0c100c5eefe5337a24dc2768/lib/ExpensiMark.js#L136C13-L155C15

So in our case we have `[url](url.) `that is tranfrom in this :
`[<a href=url>url</a>](<a href=url.>url.</a>)` . Note that the . has been added to the second href

The reason for the inconsistency is that if it looks like the user purpusefully wanted to removed a link, we remove it here;
https://github.com/Expensify/App/blob/64ecc7a21760f4d1e7356058f924fe8eb7023e88/src/libs/actions/Report.js#L1067-L1076

In the first case we pass from `url` to `url.`, so we remove the link from the text but we only remove one link because the second one has a dot in his href that's why the left part is white while the right part is blue.

In the second case we pass from `url1` to `url.` so we try to remove url1 but it doesn't exist so both links are kept


The weird part is that when we type http://google.com/. the dot is not in the href but if we add a ) after http://google.com/.) , the dot is in the href. I tested that on slack and they have the same behaviour but I still think it's the real bug
![image](https://github.com/Expensify/App/assets/19537677/563e386f-836a-46ae-8449-8f47631d2e9c)

**Comment by MitchExpensify** [comment] 2023-08-21 20:56
This seems to impact links when you send then first before editing. Lets make sure the proposal fixes this in general versus just when edited but I imagine it will

**Comment by ShogunFire** [comment] 2023-08-21 21:24
@MitchExpensify I actually think we have a general problem about escaping the comment before it arrives to the autolink rule, I explained it here: https://expensify.slack.com/archives/C01GTK53T8Q/p1692652863768869

**Comment by ShogunFire** [comment] 2023-08-21 22:09
## Proposal
[Updated](https://github.com/Expensify/App/issues/25532#issuecomment-1686805731)

I found the way we did for end parenthesis, we can do the same for dots maybe

**Comment by MitchExpensify** [comment] 2023-08-21 22:15
Got it @ShogunFire , cool. Whatever we do here should solve this in general.

**Comment by MitchExpensify** [comment] 2023-08-29 01:58
> https://github.com/Expensify/App/issues/25532#issuecomment-1688958901

@0xmiroslav bump

**Comment by MonilBhavsar** [comment] 2023-08-31 20:45
Thanks! The proposal looks good to me. I see we did it early for paranthesis, I tried with `;` and it does result in `[]()` form. I think this is case for all special characters?

**Comment by ShogunFire** [comment] 2023-08-31 21:34
It result in ` []() ` form every time the text in the `()` is not a valid link, but for ";" it is different than this issue since both links are removed (text is white), that's what I propose to do for dot too.

Right now this is the difference:

![Capture](https://github.com/Expensify/App/assets/19537677/7fa80923-e1c0-40a6-a3bf-3f409c6aa822)

**Comment by ShogunFire** [comment] 2023-09-01 12:42
Good find so from what I understand and tested that happens for every character that is a valid path url character but that can't be the last character. From looking at the regexp I think we have only those ones: `$*.+!(,=`

![image](https://github.com/Expensify/App/assets/19537677/2f4dda02-0948-4c46-be20-b636b9f22ac0)

**Comment by ShogunFire** [comment] 2023-09-01 12:47
There is also a special case for `"` that can currently be in the path but probably we will also remove it soon under some conditions as we did with end parenthesis, but this is a different issue https://github.com/Expensify/App/issues/24367

**Comment by MonilBhavsar** [comment] 2023-09-04 10:32
>  that happens for every characters that are valid path url characters but that can't be the last characters. From looking at the regexp I think we have only those ones: $*.+!(,=

Yes right! So are we going to remove all of those valid URL characters if they are at end? If so, could you please update the proposal to reflect that. cc @0xmiroslav

**Comment by ShogunFire** [comment] 2023-09-04 10:41
## Proposal
[Updated](https://github.com/Expensify/App/issues/25532#issuecomment-1686805731)

I added a line to say that we need to remove all those characters if they are at the end.

**Comment by MonilBhavsar** [comment] 2023-09-04 10:43
Thank you! @0xmiroslav could you please take a look once

**Comment by MitchExpensify** [comment] 2023-09-05 11:32
I believe @0xmiroslav is back in action - When do you think you can look at this isee @0xmiroslav ? Thanks

**Comment by ShogunFire** [comment] 2023-09-07 21:10
@0xmiroslav  I found the other issue while resolving this but I believe this is a different issue.

**Comment by MonilBhavsar** [comment] 2023-09-11 07:48
@0xmiroslav I think it is fine having separate issues since root causes and fixes are different.

**Comment by MitchExpensify** [comment] 2023-09-12 14:06
What are our next steps here @0xmiroslav ? Sounds like we are ready to hire @ShogunFire

**Comment by dhanashree-sawant** [comment] 2023-09-13 09:18
Hi @MitchExpensify, the following issue was raised on 19 August but melvin bot has provided me with 50$ offer, can you check once you are available?

**Comment by ShogunFire** [comment] 2023-09-13 16:00
Thanks @0xmiroslav @MonilBhavsar Not sure why you were not assigned but I did the PR here: https://github.com/Expensify/expensify-common/pull/575 tell me if I need to do the videos, I don't see it in the template

**Comment by MonilBhavsar** [comment] 2023-09-19 10:29
I reviewed and left a small comment. Looks good overall!

**Comment by ShogunFire** [comment] 2023-09-28 01:28
@MonilBhavsar There is some change and a question in the PR if you missed it

**Comment by MonilBhavsar** [comment] 2023-09-28 02:02
I commented on the PR, thanks!

**Comment by MitchExpensify** [comment] 2023-10-09 22:53
What do you need to help move this along at this point @0xmiroslav ?

**Comment by MonilBhavsar** [comment] 2023-10-25 13:03
The PR was merged. Is there a regression and is issue back again? 🤔 cc @0xmiroslav

**Comment by MitchExpensify** [comment] 2023-11-07 00:22
*Payment summary*:

$250 - @dhanashree-sawant reporter
$500 (50% 9 day delay penalty) - @ShogunFire C 
$500 (50% 9 day delay penalty) - @0xmiroslav C+

**Comment by MitchExpensify** [comment] 2023-11-07 00:25
Invites sent for payment! https://www.upwork.com/jobs/~011e9f2df956de96c7

**Comment by dhanashree-sawant** [comment] 2023-11-07 05:13
Thanks @MitchExpensify, I have accepted the offer.

**Comment by MitchExpensify** [comment] 2023-11-07 23:31
Paid @dhanashree-sawant @ShogunFire !

Have you accepted the offer @0xmiroslav ?

**Comment by MitchExpensify** [comment] 2023-11-09 19:43
Paid, @0xmiroslav !  Do we need a new regression test here to close this out? I don't see the automated BZ step comment 👀

**Closed** 2023-11-13 01:55 UTC
Labels: Reviewing, Daily, Internal, Bug
