### ISSUE TITLE
Web Safari - VBA - User cannot manually input dates in calendar on Mac Safari

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11152] opened 2022-09-20 21:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Access staging.new.expensify.com
2. Sign into a valid account
3. Tap Profile > Workspace > Connect to bank
4. Proceed with VBA flow until you reach the "Company information" step
5. Scroll down to "Incorporation Date" and click on each date input field

## Expected Result:
User expects to be able to manually input a date, similar to the behaviour in Google Chrome

## Actual Result:
It is impossible for the user to manually input a date, every time the user manually selects an input field they are pushed back to the "Calendar". This forces the user to scroll through years and years of calendars to find the correct date and is extremely time consuming.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web - Safari

**Version Number:** v1.2.3-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/191365174-07dba8c7-4488-423d-b750-780c3af32002.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PauloGasparSv** [comment] 2022-09-21 13:03
Hey @kavimuru!

The behaviour in Safari and Chrome really is very different! Reproduced the issue on staging, here is a video comparison on how it works on Chrome (left) and Safari (right):

https://user-images.githubusercontent.com/6564265/191507964-45a0ecbe-9e0e-49f5-a1c0-fcb6796136c1.mov

But this is just the default behaviour of the `<input type="date">` on Safari! So **I don't think it should be viewed as a problem** despite the fact the user has to scroll because it **starts at the current date** so that should minimize scrolling as much as possible.

The user can still type in the date on Safari pressing tab like I do on the video (tbh I think is unlikely to happen) or choose the date from the Datepicker (which will prob happen but I think that's ok).

Since this doesn't block the user and the date can still be selected and typed as I mentioned, and also since this is the default behaviour of each browser for the date field, I'm closing this one!
But please feel free to re-open if you disagree!

**Closed by PauloGasparSv** 2022-09-21 13:03 UTC
Labels: Engineering, Daily
