### ISSUE TITLE
[HOLD for payment 2024-08-02] [$250] Video - Change in playback speed is not reflected in thread report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42519] opened 2024-05-23 12:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to a report
2. Send a video
3. Reply in a thread to the video
4. Navigate back to the main report
5. Change playback speed
6. Navigate to the thread report
7. Click on 'Three dots' > 'Playback speed'

## Expected Result:
Changes in Playback speed from the main report should be reflected in the thread report

## Actual Result:
Changes in playback speed from the main report is not reflected in the thread report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/836fb63a-25a5-4c49-a0fc-fd6f7a29fa84

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa9734a896a98cbf</li>
        <li>Upwork Job ID: 1793619475924013056</li>
        <li>Last Price Increase: 2024-06-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 102822043</li>
<li>tienifr | Contributor | 102822045</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @situchan</details>

**Comment by lanitochka17** [comment] 2024-05-23 12:16
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-05-23 12:16
@Julesssss  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Julesssss** [comment] 2024-05-23 12:26
Thanks. 

This should not block deploy IMO. Removing the label.

**Comment by mallenexpensify** [comment] 2024-05-24 17:57
@situchan , 👀 on the proposal above plz

**Comment by situchan** [comment] 2024-05-27 09:10
Proposals are in review

**Comment by situchan** [comment] 2024-05-27 19:57
@tienifr @jainilparikh thanks for the proposals.
Please link offending PR in the root cause. This was deploy blocker.

**Comment by situchan** [comment] 2024-05-28 04:20
@jainilparikh I don't mean that this **is** deploy blocker but **was**, which means that happened on staging but not on production.

**Comment by situchan** [comment] 2024-05-28 16:45
@jainilparikh the bug reached production after yesterday's deploy. So it's expected to happen on latest prod v1.4.75
Not happened on v1.4.74

**Comment by situchan** [comment] 2024-05-30 21:02
@jainilparikh thanks for the updated proposal. The root cause is still not correct. You marked https://github.com/Expensify/App/pull/42046 as offending PR but this issue was created before that PR was [merged](https://github.com/Expensify/App/pull/42046#event-12947360302).

**Comment by Julesssss** [comment] 2024-06-03 15:55
Not overdue. Discussions ongoing

**Comment by Julesssss** [comment] 2024-06-03 15:56
Not overdue. Discussions ongoing

**Comment by situchan** [comment] 2024-06-04 20:30
@jainilparikh please hide or delete old proposals. I will provide feedback soon.

**Comment by situchan** [comment] 2024-06-06 18:06
@jainilparikh bump ^

**Comment by situchan** [comment] 2024-06-07 02:23
^

**Comment by Julesssss** [comment] 2024-06-10 09:49
Hey @situchan could you please take a look at [this proposal](https://github.com/Expensify/App/issues/42519#issuecomment-2143431227) when you have a chance

**Comment by situchan** [comment] 2024-06-12 06:20
I am not able to reproduce on latest staging v1.4.82-0
@jainilparikh @tienifr can you please confirm?

**Comment by mallenexpensify** [comment] 2024-06-12 16:24
Pausing for a quick sec... the bug is that, in the thread, the video playback speed shows as the same in the main chat but the video isn't actually playing at that speed.  Is that correct?  ie. I change the speed in the main chat to 2 and when I open the thread it shows 2 but plays at 1.

**Comment by situchan** [comment] 2024-06-12 16:43
> Pausing for a quick sec... the bug is that, in the thread, the video playback speed shows as the same in the main chat but the video isn't actually playing at that speed. Is that correct? ie. I change the speed in the main chat to 2 and when I open the thread it shows 2 but plays at 1.

Good catch! Indeed this bug still happens

**Comment by situchan** [comment] 2024-06-13 18:36
> the bug is that, in the thread, the video playback speed shows as the same in the main chat but the video isn't actually playing at that speed. Is that correct? i.e. I change the speed in the main chat to 2 and when I open the thread it shows 2 but plays at 1.

Please update proposals to explain the root cause of ^

**Comment by mallenexpensify** [comment] 2024-06-17 16:33
@situchan , 👀 above plz.  

> the video playback speed shows as the same in the main chat but the video isn't actually playing at that speed.

Is there anotehr bug here besides this one? If so, what is it? (sorry, I thought it was a few different bugs while testing, now I'm a lil confused).

**Comment by situchan** [comment] 2024-06-17 18:17
proposals are in review

**Comment by Julesssss** [comment] 2024-06-18 09:25
> Is there anotehr bug here besides this one? If so, what is it?

As far as I am concerned, no. The [bug](https://github.com/Expensify/App/issues/42519#issuecomment-2163168981) is reproducable and we are awaiting a proposalto be selected. Please someone correct me if I am wrong.

**Comment by situchan** [comment] 2024-06-20 18:01
updating today

**Comment by situchan** [comment] 2024-06-20 21:43
@jainilparikh your solution doesn't work for me in some cases.
@tienifr's [proposal](https://github.com/Expensify/App/issues/42519#issuecomment-2127095900) looks good and tests well. And they proposed first.
🎀👀🎀 C+ reviewed

**Comment by situchan** [comment] 2024-06-25 06:37
> @jainilparikh your solution doesn't work for me in some cases.

@jainilparikh here's that case:


https://github.com/Expensify/App/assets/108292595/eaf466ee-d52b-4393-90ce-8f8a33bb4d5b

As stated in our [contributing guideline](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md):

> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

@tienifr's initial RCA was correct. Linking the offending PR is just bonus point.

I'd say that both of you provided correct RCA and proper solution and picked up first working proposal.

**Comment by situchan** [comment] 2024-07-18 18:17
PR is in review

**Comment by Julesssss** [comment] 2024-07-26 09:03
It seems that QA noticed the issue not fixed for Android, lets hold payment for now. @tienifr could you take a look please?

**Comment by mallenexpensify** [comment] 2024-08-14 21:39
In the PR I'm not seeing that it was deployed to production. 
- https://github.com/Expensify/App/pull/46800#issuecomment-2289860313

@situchan @tienifr , any idea what might be going on? I want to update the title to reflect the correct payment date

**Comment by mallenexpensify** [comment] 2024-08-17 00:05
@situchan @tienifr 👀 on the comment above plz so I can get you paid (assuming it's needed)

**Comment by situchan** [comment] 2024-08-19 05:33
There was bug on that deploy. Melvin didn't post deploy comment on all PRs in [this checklist](https://github.com/Expensify/App/issues/47219).
cc: @Beamanator

**Comment by Beamanator** [comment] 2024-08-19 19:19
Agreed 👍 I posted in the PR about it being deployed to prod here - https://github.com/Expensify/App/pull/46800#issuecomment-2289860313

**Comment by mallenexpensify** [comment] 2024-08-20 23:55
d;oh, sorry, I should have seen that comment.  
Contributor: @tienifr owed $250 via NewDot 
Contributor+: @situchan paid $250 via NewDot. 

@situchan plz complete the BZ checklist above? Thx

**Comment by situchan** [comment] 2024-08-21 15:27
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41055
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41055/files#r1725293900
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A


### Regression Test Steps
1. Send a video to any chat
2. Reply the video in thread
3. Navigate to parent report
4. Change playback speed
5. Navigate to thread
6. Open playback speed menu
7. Verify thread's playback speed is the same with parent's

**Comment by mallenexpensify** [comment] 2024-08-26 14:56
Thanks @situchan 
Test Case GH created 
- https://github.com/Expensify/Expensify/issues/423309

**Closed by mallenexpensify** 2024-08-26 14:56 UTC
Labels: Reviewing, External, Engineering, Weekly, Awaiting Payment, Bug
