### ISSUE TITLE
mWeb/Chrome - Split Bill - Page stuck in transfer from Final Confirmation page to Group DM

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29191] opened 2023-10-10 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
1. Open staging.new.expensify.com
2. Navigate to FAB> Request money> Manual
3. Enter amount and select few users to Split Bill
4. On the final confirmation page tap Split button

## Expected Result:
Transfer from Final confirmation page to Group DM should be smooth

## Actual Result:
When User create Split Bill report - page stuck for a moment when transfer from Final Confirmation page to Group DM

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/c6fcbe25-c72c-405f-9f6a-595d91c10e15

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-10-10 20:25
I can't reproduce this. It's working fine for me on Android mobile web. 

https://github.com/Expensify/App/assets/54866469/67fe8ffd-ea03-4920-adc4-297d409bb98d

**Comment by joekaufmanexpensify** [comment] 2023-10-10 20:25
Closing as this isn't consistently reproducible!

**Closed by joekaufmanexpensify** 2023-10-10 20:25 UTC
Labels: Daily, Bug
