### ISSUE TITLE
[HOLD for payment 2024-12-07] [$250] RBR is shown on paid report previews

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#52037] opened 2024-11-05 13:23 UTC
I see a RBR in the workspace chat but not in the expense previews in it  There are indeed violations in the expenses though as shown in the expense page. but they should not show the RBR in the workspace chat, since it is already paid.

![image](https://github.com/user-attachments/assets/86465679-a8ec-4635-8fcf-93fdafc7971a)
![image](https://github.com/user-attachments/assets/f23fe101-448d-4d69-adb4-590f1b027438)
![image](https://github.com/user-attachments/assets/fb82946e-8672-4209-87d8-93bacc3d264a)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854179900043130166</li>
        <li>Upwork Job ID: 1854179900043130166</li>
        <li>Last Price Increase: 2024-11-20</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 105021252</li>
<li>FitseTLT | Contributor | 105021254</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by iwiznia** [comment] 2024-11-05 14:12
> We show the RBR without settled check in workplace chat

You can see in my first screenshot that the settled check is shown in the workspace chat report preview

**Comment by iwiznia** [comment] 2024-11-05 14:30
Ah ok, that's not correct as that would mean we never show RBR when settled, which is wrong.

**Comment by FitseTLT** [comment] 2024-11-05 14:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN - RBR stays for paid report

### What is the root cause of that problem?
In all MoneyRequestPreview, MoneyReportView and LHN RBR we are showing RBR whenever there is a report or transaction violations without checking if the report is settled one
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/ReportPreview.tsx#L168-L170
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L112
https://github.com/Expensify/App/blob/e60b8210a1f5a2471d8aa9d84d0e461774b791d6/src/components/LHNOptionsList/OptionRowLHNData.tsx#L40
### What changes do you think we should make in order to solve the problem?

We should only display RBR when violations exist if the iouReport is not settled (or not approved if we choose to do so).
Therefore, in all the cases listed above we need to add a condition of `!ReportUtils.isSettled(` for both transaction and report violations. We can centralize the code by creating new functions to add these condition or we can update all `TransactionUtils.hasViolation`, `ReportUtils.hasReportViolations` and `ReportUtils.hasViolations` to check for `!isSettled` of the linked iou report.
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-11-05 14:36
@iwiznia We had this issue [here](https://github.com/Expensify/App/issues/48400#issuecomment-2325264753) and closed without fixing it, so re-commented the proposal here too.

**Comment by jliexpensify** [comment] 2024-11-06 01:59
Thanks @FitseTLT - waiting on @iwiznia to review your comment.

**Comment by dexterlegrand** [comment] 2024-11-06 19:06
I will modify the RBR logic to include a conditional check on the expense’s payment status and then update the logic so that if an expense is marked as paid, the RBR indicator is suppressed across all views, including the workspace chat.
This can be achieved by adding a `paymentStatus` validation in the RBR component or middleware responsible for handling expense flags. For instance, ensure that the RBR check only applies when `paymentStatus !== 'PAID'`.
And I can implement a centralized function or service that determines when to display the RBR flag, standardizing its behavior across different parts of the application (workspace chat, expense previews, and expense page).
This service can be a function named like `shouldDisplayRBR`, which evaluates criteria such as `isPaid`, `hasPolicyViolation`, and any other relevant flags. All parts of the UI that display the RBR can then call this centralized function, ensuring consistency.
If the workspace chat updates asynchronously or in real-time, it is important to ensure that any change in the expense’s status triggers an update in the workspace chat as well. In that case, I need to use websockets to keep the RBR status in sync with the expense's current state. 
And I will review the rendering conditions for RBR flags in each part of the UI. In my experience, many systems experiences inconsistencies due to scattered conditions across components. So I can refactor the RBR rendering logic to leverage a single source of truth if necessary.
By implementing these changes, I can make the RBR indicator behaves consistently and aligns with the expected functionality.

**Comment by ikevin127** [comment] 2024-11-11 22:10
We had a similar issue here which was closed as NAB:
- https://github.com/Expensify/App/issues/48400

the consensus there was that it is expected to still have RBR show because of existing violations, see https://github.com/Expensify/App/issues/48400#issuecomment-2367773018:

> - The red circle on showing on the report preview is working as intended, because the report has violations and we show that no matter what the state of the report is.
> - After paying, the red circle should remain in the report preview, for the same reason as in the first bullet
> - After clearing the cache, the report preview isn't showing the red circle, and after clicking on the preview, the transaction previews aren't showing the red circle. These are bugs because they should be showing for the same reason as in the first bullet

The https://github.com/Expensify/App/issues/48400#issuecomment-2390337662 that the issue was closed with:

> From this https://github.com/Expensify/App/issues/48400#issuecomment-2367773018, seems part of the behavior is expected. Closing it out for now, but we can re-open if it's reported again as an issue

In case this issue is a dupe of that then I think we're good to close it as NAB - but otherwise if I'm missing something and this one is different then I think I'll have to start reviewing the proposals ? Please let me know!

cc @jliexpensify @iwiznia

**Comment by jliexpensify** [comment] 2024-11-14 02:08
@iwiznia thoughts on [this](https://github.com/Expensify/App/issues/52037#issuecomment-2469171616)? I agree that the red dots are confusing, but also can understand @cead22's point here:

>The red circle on showing on the report preview is working as intended, because the report has violations and we show that no matter what the state of the report is.

**Comment by ikevin127** [comment] 2024-11-14 09:46
Not overdue, waiting on input regarding https://github.com/Expensify/App/issues/52037#issuecomment-2469171616 before moving forward with the issue.

**Comment by iwiznia** [comment] 2024-11-14 17:13
Oh @JmillsExpensify was going to post a summary of a discussion we had summarizing how this should work.

**Comment by ikevin127** [comment] 2024-11-18 10:45
Not overdue, still waiting on input regarding https://github.com/Expensify/App/issues/52037#issuecomment-2469171616 before moving forward with the issue.

**Comment by JmillsExpensify** [comment] 2024-11-20 15:29
@iwiznia I still have this one on my list. Should I post the summary in this issue or create a new one?

**Comment by iwiznia** [comment] 2024-11-20 16:50
Here sounds good to me

**Comment by ikevin127** [comment] 2024-11-20 19:33
Awaiting on summary to be posted coming from https://github.com/Expensify/App/issues/52037#issuecomment-2488894910 so we can move forward with the issue.

**Comment by JmillsExpensify** [comment] 2024-11-20 21:47
Ok I'll prioritize that now.

**Comment by JmillsExpensify** [comment] 2024-11-20 22:33
I think this is where we landed. 

### Terms
**RBR** - Exclusively refers to reports that are marked as unread and are visible in the LHN. RBRed rows in the LHN carry a red dot and are also always pinned. 
**Red dot** - Refers to a pattern of using a red circle incon – on expenses, reports, in settings, etc. Red dots disappear when either an `X` has been clicked, an issue with an expense has been resolved, or an expense report has been paid. 
**Red text** - Red words that appears in the transaction thread, next to whatever field has broken an amount (e.g. `Missing category` or `Receipt required`). 
**Workspace chat** - `policyExpenseChat`
**Preview component** - The "boxes" or "cards" that appear for reports or transactions. Clicking a preview component shows the report or transaction details. 

### Logic for RBR and red dots

**Submitters**
 - RBR for their workspace chat when any expense report (thread) contains expenses that break a workspace rule/violation.
   - Note: Once a submitter can no longer make edits (even if they didn't resolve any rules/violations), then their workspace chat is no longer RBRed.
 - Report threads or transaction threads are not RBRed for the submitter (I can't think of a case where they would be at least)
 - Red dots appear on expense report and transaction preview components as long as violations/rules have been broken and the report is not `reimbursed` or `closed`.
 - Red violation/rule text always appear in the transaction thread, no matter the state of the report it's on
 
 **Approvers and admins**
 - The workspace chat is never RBRed.
 - Submitted reports (and any transactions) are not RBRed.
 - Red dots appear on expense report and transaction preview components as long as violations/rules have been broken and the report is not `reimbursed` or `closed`.
 - Red violation/rule text always appear in the transaction thread, no matter the state of the report it is on.

**Comment by FitseTLT** [comment] 2024-11-20 23:16
Most of the changes align with current code so [Updated](https://github.com/Expensify/App/issues/52037#issuecomment-2457341349) proposal to include the missing checks 👍

**Comment by ikevin127** [comment] 2024-11-21 00:32
I was able to reproduce the issue following these steps:

> [!tip]
> 1. Submit two failing scan expenses to another account (you have access to), this can be done by adding a picture that it's not an actual receipt such that the scan would fail and the expenses Amount is $0 -> violation asking to input Amount.
> 2. Navigate to one of the failed scan expenses and input the Amount -> which would fix the violation of the expense.
> 3. Login into the other account and pay the expenses via `Pay elsewhere` for both expenses (including the one with pending violation).
> 4. Back on the expenses submitter side, in the report with the other account where the groupped expenses can be seen, notice that RBR is showing whlist if clicked on the preview and seeing the expenses separately, no RBR can be seen.

@JmillsExpensify @iwiznia If any of you think that I'm missing a certain flow like WS related expenses, please let me know the steps and will make sure to double check that the selected proposed solution is covering the fix for that flow as well.

##

@FitseTLT Any specific reason for adding the second check here:

https://github.com/Expensify/App/blob/2d2555b173b47c0bce0b1c16b275f1f98639664c/src/components/ReportActionItem/ReportPreview.tsx#L515

instead of here ?

https://github.com/Expensify/App/blob/056d6541d875378e0c2d2b6add5609cb9f49532f/src/components/ReportActionItem/ReportPreview.tsx#L365

If not, I'd say let's add it there as a way to centralize the `shouldShowRBR` variable at the component level instead of keeping it separate and adding `!iouSettled` only for the RBR icon, as `shouldShowRBR` is also used below to display the GBR indicator.

##

> I see a RBR in the workspace chat but not in the expense previews in it There are indeed violations in the expenses though as shown in the expense page. but they should not show the RBR in the workspace chat, since it is already paid.

Assuming the **Expected result** of the issue is to not show the RBR on expense group if the expenses are paid (settled) and given the latest [specifications](https://github.com/Expensify/App/issues/52037#issuecomment-2489671728) are reinforcing that, let's go with @FitseTLT's [proposal](https://github.com/Expensify/App/issues/52037#issuecomment-2457341349) as the RCA is correct and the solution fixes the issue.

🎀👀🎀 C+ reviewed

**Comment by JmillsExpensify** [comment] 2024-11-21 09:49
@ikevin127 that sounds good to me. In terms of testing, it'd also be easy to manually create an expense and then trigger one of the standard violations that get set when the policy is created ($2k individual expense, $25 receipt required amount, etc.).

**Comment by ikevin127** [comment] 2024-11-21 22:18
cc @grgia for visibility

**Comment by grgia** [comment] 2024-11-22 13:16
Looks good, assigning!

**Comment by JmillsExpensify** [comment] 2024-11-22 21:03
Going to assign myself as BZ in case follow-on discussion comes up

**Comment by ikevin127** [comment] 2024-11-25 20:19
cc @grgia for visibility as we're awaiting PR review

**Comment by ikevin127** [comment] 2024-11-30 22:03
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production
  - [ ] 2b. Reported on staging (deploy blocker)
  - [ ] 2c. Reported on both staging and production
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by ikevin127** [comment] 2024-12-09 04:40
cc @JmillsExpensify payment overdue, for visibility

**Comment by JmillsExpensify** [comment] 2024-12-09 11:04
Payment summary:

 - Contributor: $250 @FitseTLT via Upwork
 - Reviewer: $250 @ikevin127 via Upwork

**Comment by JmillsExpensify** [comment] 2024-12-09 11:07
All contributors paid via Upwork and regression test created. Closing this issue.

**Closed by JmillsExpensify** 2024-12-09 11:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
