### ISSUE TITLE
[HOLD for payment 2023-10-12] [$500]  Chat - Space is not added after an emoji is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26709] opened 2023-09-04 19:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/24614
## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Open emoji picker
4. Select an emoji
5. Add another emoji

## Expected Result:
Space is added after an emoji is selected

## Actual Result:
Space is not added after an emoji is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/977c5f88-82a3-4853-b69b-1d57f36710bf

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9f65ce9e5e54e44</li>
        <li>Upwork Job ID: 1699517068377264128</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26895645</li>
<li>Krishna2323 | Contributor | 26895646</li>
</ul></li>
    </ul>
</details>

**Comment by napster125** [comment] 2023-09-04 22:50
I can't reproduce it.

**Comment by joelbettner** [comment] 2023-09-05 02:18
I also cannot reproduce. I've tried to reproduce on desktop, mobile and web.

**Comment by kavimuru** [comment] 2023-09-05 12:34
@joelbettner Reproducible only in Android app.

**Comment by mountiny** [comment] 2023-09-05 14:28
Thanks not  a blocker

**Comment by napster125** [comment] 2023-09-05 14:29
@kavimuru I can't reproduce on Android native.

**Comment by johncschuster** [comment] 2023-09-05 19:35
@joelbettner are we good to close this one since it seems we can't reproduce it?

**Comment by joelbettner** [comment] 2023-09-06 00:19
@lanitochka17 are you still able to reproduce this? If not, let's go ahead and close, otherwise, @johncschuster let's open it for an external contributor to work on.

**Comment by lanitochka17** [comment] 2023-09-06 13:29
Issue reproducible on the latest version (v1.3.64-0)
Samsung Galaxy Note 10+ / Android 12

https://github.com/Expensify/App/assets/78819774/171c2f3d-f13a-4534-8560-e0b552d90bd3

**Comment by b4s36t4** [comment] 2023-09-06 20:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Space is not added after an emoji is selected 
### What is the root cause of that problem?
We're adding space after clicking the emoji, the issue is that we're moving the selection cursor the point later to the space.


We're calculating the selection position based on the text (which is before adding the space).

Here https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L263-L267 is the code that is causing the issue.
### What changes do you think we should make in order to solve the problem?

We should update `text.length` to `updatedText.length` to move the cursor to after space.

### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-09-06 20:38
Demo for Proposal https://github.com/Expensify/App/issues/26709#issuecomment-1709072559


https://github.com/Expensify/App/assets/59088937/e04df66e-1459-4f79-a76f-65e43f2d2e8a

**Comment by jjcoffee** [comment] 2023-09-07 15:09
Happy to go with @b4s36t4's [proposal](https://github.com/Expensify/App/issues/26709#issuecomment-1709072559) here. RCA looks correct and the solution seems straightforward!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by situchan** [comment] 2023-09-10 16:12
I don't think the root cause is correct. It should explain why this happens only on android. This works well on any other platforms.

**Comment by situchan** [comment] 2023-09-10 16:15
Also, this was deploy blocker, which means worked before.
So the recent PR which caused this regression should be identified. This is also needed for BZ checklist.

**Comment by jjcoffee** [comment] 2023-09-11 08:42
@b4s36t4 Per @situchan's [comment](https://github.com/Expensify/App/issues/26709#issuecomment-1712852457), are you able to provide more detail in your RCA regarding why this behaviour only happens on Android?

**Comment by b4s36t4** [comment] 2023-09-12 20:50
@jjcoffee Sorry for the delay. https://github.com/Expensify/App/issues/26709#issuecomment-1709072559 I have updated my proposal. Please review thanks.

**Comment by johncschuster** [comment] 2023-09-13 14:39
What do you think of the above proposal, @jjcoffee?

**Comment by jjcoffee** [comment] 2023-09-13 15:39
@b4s36t4 Thanks for updating your proposal, but I'd need a bit more detail on why you think that passing the `selection` prop (or not) is the root cause. How is it related to this specific issue?

@Krishna2323 Thanks for your proposal! Testing on Chrome desktop I get the emoji passed as a string rather than array, can you confirm where/how you're seeing that behaviour? Also side-note, your `Option 1` is the same as @b4s36t4's original proposal. I think I'm still good with that proposal, I think we're just missing a clearer RCA for why it works as a solution.

**Comment by b4s36t4** [comment] 2023-09-13 15:45
@jjcoffee simply to put we're only tracking selection of text for suggestion purposes I think. But because as mentioned in my first RCA

> selection doesn't have the `updatedText` length.

selection is moving before the space. So if we remove the `selection` prop input will handle the selection(cursor) automatically by the text we're inserting (with space) so that cursor won't be before space.

Let me know if you understand this point or I can explain a bit clearer.

**Comment by jjcoffee** [comment] 2023-09-18 11:39
@b4s36t4 We can't remove the `selection` prop:

https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/components/Composer/index.ios.js#L110

I'm not sure I fully follow your explanatory [comment](https://github.com/Expensify/App/issues/26709#issuecomment-1717887625). Is your point that we exclude the `selection` prop on other platforms, so this block of code your original fix proposed to modify would never run on those platforms?

https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L263-L266

**Comment by b4s36t4** [comment] 2023-09-18 11:47
I stand with my first proposal updating the selection length with `updatedText` which gives the correct selection with the updated content. https://github.com/Expensify/App/issues/26709#issuecomment-1709072559

**Why it doesn't only work with Android**

because we have different behaviour handled for different platforms for `iOS` we removed `selection` props which makes it uncontrolled input means.. input will handle the cursor selection itself (so if I add a emoji ios will handle the work of moving cursor itself).

For web we manually handle the selection based on the value added to input. more on here
https://github.com/Expensify/App/blob/954c66ded309b1a11f87424b77b9a451ff338010/src/components/Composer/index.js#L206

We have a state for selection in web.

So to put it in clear perspective we only have a controlled state for selection andriod which is the RCA for this issue. Either we update the selection or we simply remove the selection prop fully.

cc: @jjcoffee hope you have understand what I'm trying to say.

**Comment by b4s36t4** [comment] 2023-09-18 11:51
> We can't remove the selection prop

I tried and checked it is working as expected. So it's not a problem at this moment may cause regressions depends on many factors of checking though.

This issue also happens with Edit message as well which is the same RCA is have proposed at first.

**Comment by jjcoffee** [comment] 2023-09-18 12:04
@Krishna2323 Your [proposal's](https://github.com/Expensify/App/issues/26709#issuecomment-1717081347) RCA highlights a native behaviour which would apply to all native platforms, whereas this issue is for Android only.

@b4s36t4 Okay I think I'm good with your original proposal. The RCA is that we only have a controlled state for selection on Android, which according to [this comment](https://github.com/Expensify/App/blob/5b4dee82a3634d73b9543474c5f298f1153460f9/src/components/Composer/index.ios.js#L110), we are doing on purpose. So the correct solution is to fix the incorrect `setSelection` logic as in your original proposal, as other platforms simply insert the text with the space. Can you revert your [proposal](https://github.com/Expensify/App/issues/26709#issuecomment-1709072559) to the original solution?

@joelbettner Can you assign @b4s36t4 if you agree with the above?

**Comment by b4s36t4** [comment] 2023-09-18 12:12
Changed my proposal (revert to the initial one)

**Comment by b4s36t4** [comment] 2023-09-18 14:03
I don't think RCA is not correct, as stated above it only happens with android because of the selection. 

My RC is 100% because weather you spread or don't the values coming to the `replaceSelectionWithText` is same but there's a small difference which I need to debug.

Spreading is the not the issue. Also my proposal is also solving the other mentioned issue.

**Comment by jjcoffee** [comment] 2023-09-18 16:34
Okay so having a deeper look into this has convinced me that @Krishna2323 has the right RCA in their [proposal](https://github.com/Expensify/App/issues/26709#issuecomment-1717081347). I had missed that this was a regression from [this PR](https://github.com/Expensify/App/pull/24614) where a `useSingleExecution` hook was added and used for the emoji picker. The root cause clearly lies there, and removing that [change](https://github.com/Expensify/App/blob/d494433a80ff82f588e3888a8da2c527848843e9/src/components/EmojiPicker/EmojiPickerMenu/index.native.js#L155) fixes the issue.

I can see that on Android an an array containing the emoji comes through to `replaceSelectionWithText`, so switching to using `updatedText` here:

https://github.com/Expensify/App/blob/1223e1e6d98d2bfc4daac70fd3de898ae90b94b7/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L260-L266

only superficially fixes the issue as the template literal in `updatedText` turns that array into a string. I've asked on the [offending PR](https://github.com/Expensify/App/pull/24614/files/7d33ab7d2ff41e5dace5b503a91ee37f55e55669#r1328982873) if there's any reason for not spreading there, just in case there's something I'm missing. So hold on assigning this please @joelbettner - and sorry for all the back and forth!

**Comment by johncschuster** [comment] 2023-09-20 21:55
@jjcoffee what are your thoughts on Melv's question? Do you feel good about the proposals we have available?

**Comment by jjcoffee** [comment] 2023-09-21 09:21
I think we can just move ahead with @Krishna2323's [proposal](https://github.com/Expensify/App/issues/26709#issuecomment-1717081347) - I was waiting for a reply on the PR that caused the regression, but I think we can handle that in testing once the PR is raised. cc @joelbettner

**Comment by johncschuster** [comment] 2023-09-27 00:16
Not overdue. I've just assigned the issue!

**Comment by jjcoffee** [comment] 2023-10-05 08:07
Just noting this one was C+ [approved](https://github.com/Expensify/App/pull/28302#pullrequestreview-1650670450) within 3 WD, and [merged](https://github.com/Expensify/App/pull/28302#pullrequestreview-1654091443) without any changes requested later (due to engineer delay), so I think this one is still due the urgency bonus.

**Comment by jjcoffee** [comment] 2023-10-05 08:14
**Regression Test Proposal**

1. Go to any chat
2. Open the emoji picker
3. Select any emoji
4. Verify that the emoji is inserted with a single space following it

Do we agree 👍 or 👎

**Comment by joelbettner** [comment] 2023-10-11 22:14
@johncschuster has the payment been finished for this?

What do we need to do to get this issue closed?

**Comment by johncschuster** [comment] 2023-10-18 17:01
Payment has been issued!

**Closed** 2023-10-18 17:01 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
