### ISSUE TITLE
Search-Expense details updated are not shown immediately

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#42254] opened 2024-05-16 09:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch app
2. Tap fab -- submit expense
3. Create a expense with an user
4. Navigate to lhn
5. Tap profile -- troubleshoot -- new search
6. Tap on the expense
7. In IOU details page, change amount
8. Note in search page, amount not updated
9. Tap on the expense
10. Enter merchant and note in search page, merchant also not updated
11. Tap chat icon and from profile -- troubleshoot -- new search revisit page
12. Note now updated amount and merchant is shown

## Expected Result:
In search page, expense details updated must be shown immediately.

## Actual Result:
In search page, expense details updated are not shown immediately, shown only while revisiting page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/3f6144b9-708e-4dfa-b9e7-58131e2e54bb

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by izarutskaya** [comment] 2024-05-16 09:19
@dylanexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-05-16 09:20
We think this issue might be related to the #vip-vsb.

**Comment by youssef-lr** [comment] 2024-05-17 13:25
can we check again if this is reproducible in prod?

**Comment by kavimuru** [comment] 2024-05-17 13:48
@youssef-lr we don't have "testing preference" in production. So, we can't check it.

![image](https://github.com/Expensify/App/assets/43996225/94dcb7d5-7136-4d2d-afe9-73055baca5ea)

**Comment by dylanexpensify** [comment] 2024-05-17 15:45
@youssef-lr checking in on this, need anything from me so far?

**Comment by youssef-lr** [comment] 2024-05-17 16:34
Nothing yet @dylanexpensify, thanks! I'm trying to reproduce this now.

**Comment by youssef-lr** [comment] 2024-05-17 16:36
Demoting this given that this only affect the new search page which is only accessible from staging

**Comment by dylanexpensify** [comment] 2024-05-21 20:02
sounds good!

**Comment by youssef-lr** [comment] 2024-05-29 00:33
Not overdue.

**Comment by dylanexpensify** [comment] 2024-05-29 06:34
@abdulrahuman5196 to review!

**Comment by abdulrahuman5196** [comment] 2024-06-04 19:48
Hi, Sorry for the delay. I will review this first thing in the morning.

**Comment by abdulrahuman5196** [comment] 2024-06-06 15:39
checking now

**Comment by abdulrahuman5196** [comment] 2024-06-06 16:22
@dominictb 

>In TransactionListItemRow, use useOnyx to get the latest value by item.transactionID, and use those values in priority, if there're fields that don't exist in the Onyx transaction like from, to, use the search result values for them (they cannot be updated anyway so no issue)


This seems to be a costly operation to fetch transaction for each row item, instead can we fetch it as a whole and update the data before sending it to all the row items?

**Comment by youssef-lr** [comment] 2024-06-12 17:39
>But this might lead to the whole list rendering when only 1 row data changes, although we can mitigate it by memoization.

If you memoize the whole list this can still happen no?

**Comment by youssef-lr** [comment] 2024-06-12 17:46
Not overdue melvin

**Comment by dylanexpensify** [comment] 2024-06-17 19:34
@youssef-lr anything needed here?

**Comment by abdulrahuman5196** [comment] 2024-06-20 16:05
> > instead can we fetch it as a whole and update the data before sending it to all the row items?
> 
> @abdulrahuman5196 Of course we can, we can simply get it in batch in the list and pass down to the rows.
> 
> But this might lead to the whole list rendering when only 1 row data changes, although we can mitigate it by memoization.

@dominictb Seems good. Can you update the proposal with the relevant information on how you would do it as an alternate solution? So that we can review the proposal as a whole again

**Comment by dylanexpensify** [comment] 2024-06-21 10:00
Pending @dominictb to update proposal

**Comment by abdulrahuman5196** [comment] 2024-06-24 18:51
Expecting proposal update by tomorrow

**Comment by dylanexpensify** [comment] 2024-06-26 09:24
@dominictb let's get it posted today! 🙌

**Comment by abdulrahuman5196** [comment] 2024-07-08 07:46
Need to re-test this

**Comment by abdulrahuman5196** [comment] 2024-07-24 08:20
@youssef-lr / @dylanexpensify We can close this issue. Issue not reproducible.


https://github.com/user-attachments/assets/1e38fa8f-ed12-459e-b526-9af7f75bc401

**Comment by abdulrahuman5196** [comment] 2024-08-01 15:27
@dylanexpensify / @youssef-lr We can close this issue - https://github.com/Expensify/App/issues/42254#issuecomment-2247198288

**Closed** 2024-08-01 16:59 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
