### ISSUE TITLE
[$500] Web - Requested Money (RHN) Details Unavailable for Editing in Offline Mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26748] opened 2023-09-05 10:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to User A's account.
2. Create a workspace and invite User B.
3. Open another browser and log in with User B's account.
4. Open the policy expense chat.
5. Navigate to the "Request money" section.
6. Enter an amount and request it.
7. Go back to User A’s account.
8. Open the policy expense chat where userB sent a message.
9. Click on the requested money (do not click again to open its detail)
10. Now, go to Settings > Preferences.
11. Turn on “Force offline” and go back.
12. Click again on the requested money to open its details.
13. Click on any fields.

## Expected Result:
RHN details should open when clicking on requested money detail fields in offline mode

## Actual Result:
Requested Money (RHN) Details Unavailable for Editing in Offline Mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.63-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/2157656c-9523-4cde-9ea5-abb0c67eb9a7

https://github.com/Expensify/App/assets/115492554/c354a466-f506-42c6-8c6f-33b959d3461b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazhussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693447865209099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c72c5b9a2b5bf971</li>
        <li>Upwork Job ID: 1700098728344993792</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26630334</li>
</ul></li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-09-06 09:57
Very weird - I have not been able to reproduce this one. @ayazhussain79 please could you confirm the reproduction steps, and try to reproduce again? 


https://github.com/Expensify/App/assets/5802477/76464a31-07d1-4e6f-b554-529424d9f0c0

**Comment by conorpendergrast** [comment] 2023-09-08 10:26
Nice, I was able to reproduce this on both OSX Safari and OSX desktop app. Checking for correct behaviour now

**Comment by conorpendergrast** [comment] 2023-09-08 10:31
[Posted to Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1694169022238889) and tagged you there @ayazhussain79!

**Comment by ayazhussain79** [comment] 2023-09-08 10:32
@conorpendergrast ok Thank you

**Comment by conorpendergrast** [comment] 2023-09-08 10:48
Via Slack ([external](https://expensify.slack.com/archives/C01GTK53T8Q/p1694169022238889), [internal](https://expensify.slack.com/archives/C03U7DCU4/p1694169069455289)), we agree that this is a bug. This flow should follow the pattern A. That will allow editing, looks like it was successful (no feedback) and then when they are online it queues up to post the change

**Comment by conorpendergrast** [comment] 2023-09-08 12:43
As a correction to the earlier message, this should be [pattern B](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#b---optimistic-with-feedback-pattern)

**Comment by conorpendergrast** [comment] 2023-09-11 08:22
I'm on parental leave; re-assigning! This has been triaged and is waiting for proposals.

**Comment by burczu** [comment] 2023-09-12 11:43
I've just reviewed [the proposal](https://github.com/Expensify/App/issues/26748#issuecomment-1711561680) from @tienifr and it does fix the issue so I think we can proceed with it.

@tienifr One question about your additional fix for `canEdit` - the differences between these two places is that the `canEditMoneyRequest` method does not check for `!isDeleted` flag as it is done in the other place. Are you sure switching to use the method in both places and omitting this check won't break anything?

🎀 👀 🎀 C+ reviewed

**Comment by tjferriss** [comment] 2023-09-29 07:29
@burczu can you please apply to the job on Upworks? https://www.upwork.com/jobs/~01c72c5b9a2b5bf971

**Comment by burczu** [comment] 2023-09-29 07:30
@tjferriss I'm not eligible for payment here because I'm a contractor from Callstack.

**Comment by tjferriss** [comment] 2023-09-29 07:31
I'm manually adding the instructions: 

The solution for this issue has been 🚀 deployed to production 🚀 in version 1.3.65-7 and is now subject to a 7-day regression period 📆. Here is the list of pull requests that resolve this issue:

https://github.com/Expensify/App/pull/27285
If no regressions arise, payment will be issued on 2023-09-15. 🎊

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.

- [ ]  External issue reporter @ayazhussain79 $250
- [ ]  Contributor that fixed the issue @tienifr $750
- [ ]  Contributor+ that helped on the issue and/or PR - @burczu NA Callstack

For reference, here are some details about the assignees on this issue:

As a reminder, here are the bonuses/penalties that should be applied for any External issue:

Merged PR within 3 business days of assignment - 50% bonus
Merged PR more than 9 business days after assignment - 50% penalty

**Comment by tjferriss** [comment] 2023-09-29 07:32
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ]  @burczu The PR that introduced the bug has been identified. Link to the PR:
- [ ]  @burczu The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ]  @burczu A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ]  @burczu Determine if we should create a regression test for this bug.
- [ ]  @burczu If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
- [ ]  @burczu Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by burczu** [comment] 2023-10-10 12:26
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]   @burczu The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/25429
* [ ]   @burczu The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/25429#discussion_r1352355788
* [x]   @burczu A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Didn't find.
* [x]   @burczu Determine if we should create a regression test for this bug.
* [x]   @burczu If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
* [x]   @burczu Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by tjferriss** [comment] 2023-10-11 04:37
The payments have been sent via Upworks.

**Closed by tjferriss** 2023-10-11 04:37 UTC
Labels: Reviewing, External, Weekly, Bug
