### ISSUE TITLE
[$1000] The cancel button shows a blue outline though pressing enter calls the Delete event.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21756] opened 2023-06-27 21:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App and resize the window until we can see the single page layout on the web
2. Go to any chat and send any message
3. Press the up key to edit the message
4. Clear the message, and press enter
5. It will open the delete comment confirmation modal, now observe the Cancel button
## Expected Result: 
The cancel button should not have the blue outline
## Actual Result: 
The cancel button has a blue outline that confuses the user as it looks like pressing enter will call the cancel event, but we call the delete event

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0c0c3fc7-d694-47eb-8e61-7e5cf48315cc

https://github.com/Expensify/App/assets/43996225/4fba328f-7f56-40bc-a817-16cb2e017f4e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jayeshmangwani 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687776192493149

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8ff36fc089147d7</li>
        <li>Upwork Job ID: 1674082110672396288</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by lealobanov** [comment] 2023-06-28 02:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In the delete comment confirmation modal, the cancel button has a blue outline that is confusing to the user. When pressing enter the Delete button is called instead.

### What is the root cause of that problem?

```
{props.shouldShowCancelButton && (
      <Button
          style={[styles.mt3, styles.noSelect]}
          onPress={props.onCancel}
          text={props.cancelText || props.translate('common.no')}
      />
  )}
```

The style styles.noSelect is not being applied correctly:
```
 noSelect: {
        boxShadow: 'none',
        outline: 'none',
    },
```

### What changes do you think we should make in order to solve the problem?

Modifying CSS properties on this class (or creating a new class) to remove button border completely.

```
 noSelect: {
        boxShadow: 'none',
        outline: 'none',
        border: 'none',
    },
```



### What alternative solutions did you explore? (Optional)

**Comment by LiaKim07** [comment] 2023-06-28 07:35
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
In the delete comment confirmation modal, the cancel button has a blue outline that is confusing to the user. When pressing enter the Delete button is called instead.

### What is the root cause of that problem?
When the cancel button is shown the following styles are applied:

![image](https://github.com/Expensify/App/assets/93604038/5160d8eb-5f1f-4f75-9cce-1dfd0e36eb1c)

The style styles.noSelect is not being applied correctly:

 noSelect: {
        boxShadow: 'none',
        outline: 'none',
    },
### What changes do you think we should make in order to solve the problem?
Modifying CSS properties on this class (or creating a new class) to remove button border completely.

button:focus-visible {box-shadow: none; }
### What alternative solutions did you explore? (Optional)
N?A

**Comment by Santhosh-Sellavel** [comment] 2023-06-28 16:01
AFAIK Accessibility issues are not the focus right now, cc: @puneetlath

**Comment by puneetlath** [comment] 2023-06-28 16:04
Ahhh right. Because this specifically is about an accessibility feature. Thanks for reminding me @Santhosh-Sellavel. Closing!

**Closed by puneetlath** 2023-06-28 16:04 UTC
Labels: External, Daily, Help Wanted, Bug
