### ISSUE TITLE
[HOLD for Payment 2024-05-29][$125] [Held requests] Approval popup for a report with hold expense has `X` Close option it.

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41252] opened 2024-04-29 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.67-2
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714419087794969

## Action Performed:
1. Create a couple of expenses (e.g. Submit expense)
2. Once your report has more than one expense, click on the report
3. Choose one of the expenses on the report
4. In the transaction thread, tap the three vertical dots and hold an expense
5. In the report, click approve or pay
6. See the partial pay modal, asking if you want to pay everything or just what’s not on hold
## Expected Result:
The modal should not have an X close option in the top right hand corner. 
## Actual Result:
The modal has an X close option in the top right hand corner. 
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [X] Android: Native
- [X] Android: mWeb Chrome
- [X] iOS: Native
- [X] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [X] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/b5cc216c-6fed-4b2e-8600-ceed1b944c88

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc4b880c2fe9c645</li>
        <li>Upwork Job ID: 1785221935801417728</li>
        <li>Last Price Increase: 2024-05-08</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by neonbhai** [comment] 2024-04-29 21:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Approval popup for a report with hold expense have X in it.

### What is the root cause of that problem?
We render the close button in `DecisionModal without check for screensize
https://github.com/Expensify/App/blob/49db1492b770adc57301c78026dd4790d4e6bb01/src/components/DecisionModal.tsx#L63-L75

### What changes do you think we should make in order to solve the problem?
We will add logic to only render the close button if the modal is presented on a small screen. 
We will use  `isSmallScreenWidth` for the check

**Comment by ikevin127** [comment] 2024-05-01 21:18
♻️ Reviewing proposals.

**Comment by ikevin127** [comment] 2024-05-01 22:39
**Expected result:**
> The modal should not have an X close option in the top right hand corner.

Given the expected result of this issue, can we get a 2nd opinion from the @Expensify/design team confirming the expected result change ? Including how this should look on both wide and narrow layout devices.

I want to confirm if we want the `X` (Close) button completely gone from both wide and narrow layout devices so I can move forward with selecting one of the proposals based on the confirmation of the expected result. Thank you!

**Comment by shawnborton** [comment] 2024-05-02 01:10
Are we sure this isn't expected behavior? I think this is how our alert modals work. And given that you have no other way to exit the modal, this seems right. cc @Expensify/design @trjExpensify @JmillsExpensify for a second opinion though. 

Though one bug I am spotting - looks like we are using the wrong button sizes for this, shouldn't they be 52px tall (large buttons)?

**Comment by trjExpensify** [comment] 2024-05-02 01:16
Doesn't look like it: 

<img width="640" alt="image" src="https://github.com/Expensify/App/assets/16232057/be7d33cb-ce97-4796-ae5e-6df1ab347c14">

You can click outside of the modal to cancel it as well.

**Comment by dubielzyk-expensify** [comment] 2024-05-02 03:29
Yeah, I prefer it without the X. Most have a way of closing it via the button anyways. So I think we should remove the X

**Comment by ikevin127** [comment] 2024-05-02 05:12
Thanks @Expensify/design for chiming in!

> [!note]
> I checked and the `DecisionModal` is only used **once** within the `ProcessMoneyReportHoldMenu` component.

Therefore, the consensus so far is that we should completely remove the `X` (Close) button from the `DecisionModal` for both wide and narrow layout devices, since click / tap outside the modal is enough to close it.

Do we agree 👍 or 👎.

**Comment by shawnborton** [comment] 2024-05-02 12:11
Sounds like that's the plan, yup. No more close "x" in our modals!

**Comment by shawnborton** [comment] 2024-05-02 12:12
@trjExpensify those are good examples but I guess they always include some kind of cancel/close button as a wider button. In the Hold case, you don't have a cancel/close option - you get two buttons and you need to pick one of them. But that being said, you can easily click outside of the modal or hit escape, so I think it's fine to omit the close icon.

**Comment by ikevin127** [comment] 2024-05-02 16:19
Based on the latest discussion, we concluded [here](https://github.com/Expensify/App/issues/41252#issuecomment-2089594745) that we should completely remove the `X` (Close) button from the `DecisionModal`.

Given the context, @Krishna2323's [proposal](https://github.com/Expensify/App/issues/41252#issuecomment-2083661978) looks good to me. The root cause was identified first, and they were also first to suggest removing the `X` button in their solution (based on edits timeline).

🎀👀🎀 C+ reviewed

**Comment by laurenreidexpensify** [comment] 2024-05-03 13:02
@cristipaval if offline til Tues 7 May for Orthodox Easter so will review when he's back

**Comment by laurenreidexpensify** [comment] 2024-05-07 07:21
@cristipaval bump for review today pls thanks!

**Comment by cristipaval** [comment] 2024-05-07 11:43
I'm good with @Krishna2323 solution. But this issue is a super, super simple one, and I'm thinking of making it a 125$. Do we all agree? 👀

**Comment by laurenreidexpensify** [comment] 2024-05-10 07:15
@Krishna2323 is there an ETA for the draft PR thanks

**Comment by ikevin127** [comment] 2024-05-23 00:22
⚠️ **Automation failed**: This was deployed to **production** today [here](https://github.com/Expensify/App/pull/41975#issuecomment-2125963109), therefore should be **[HOLD for Payment 2024-05-29]** and have `Awaiting Payment` label.

cc @laurenreidexpensify @cristipaval

**Comment by laurenreidexpensify** [comment] 2024-05-29 11:00
Payment Summary:

- C+ @Krishna2323 $125 issued in upwork 
- Contributor @ikevin127 $125 issued in upwork

**Closed by laurenreidexpensify** 2024-05-29 11:00 UTC
Labels: Reviewing, External, Daily, Bug
