### ISSUE TITLE
[HOLD for #16296][$1000]  pronouns search breaks when we reload on pronouns search page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20095] opened 2023-06-02 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

- Login to NewExpensify on web at www.staging.expensify.com 
- Go to Settings > Profile > Pronouns Page.
- Search and select a pronoun if you don't have one
- You'll be redirected to the Profile Page > click Pronoun again
- Search for another pronoun but do not select it
- Refresh browser
- You'll see the pronoun you've previously selected after the page load
- Search and Select a different pronoun
- You'll be redirected to the Profile Page.
- Click on the Pronouns menu item again.
- You'll notice that this time, the chosen pronoun is not prefilled in the search box, which should be the expected behaviour.

## Expected Result: 
Pronouns search page should display current selection when opened
## Actual Result: 
Pronouns search page displays blank result with blank search if we search anything, reload, select any result and reopen the search page.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [X] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6bb96ae9-d984-4ce8-929e-1e4455802584

https://github.com/Expensify/App/assets/43996225/d281b5a7-8977-41c0-a6a9-7ab3e189aa4f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685609323316469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c81d6b609195757b</li>
        <li>Upwork Job ID: 1665772405170659328</li>
        <li>Last Price Increase: 2023-06-12</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2023-06-02 23:15
this is really difficult to reproduce - I can't get it to happen consistently with the above steps... It sees like just a bug with the loading or something?

**Comment by priyeshshah11** [comment] 2023-06-05 17:37
@rushatgabhane & @Beamanator I have fixed this bug in the Pronouns page migration here https://github.com/Expensify/App/pull/20178

**Comment by Christinadobrzyn** [comment] 2023-06-06 18:11
Oh nice! @priyeshshah11 So I think that means we can close this job/GH favour of payment on https://github.com/Expensify/App/issues/16296

Correct?

**Comment by priyeshshah11** [comment] 2023-06-07 00:06
@dhanashree-sawant I believe yes and this should also be eligible for the fixing bonus too but that's for @Christinadobrzyn to decide.

**Comment by Christinadobrzyn** [comment] 2023-06-07 00:55
Yes @dhanashree-sawant - thank you for reaching out about the reporting bonus! I'll reach out to the team about it!

**Comment by Christinadobrzyn** [comment] 2023-06-08 16:47
Hi @dhanashree-sawant and @Prince-Mendiratta - I'd like to compensate you both for reporting/helping with testing this issue. 

I'll follow the PR https://github.com/Expensify/App/issues/16296 to make sure this issue is resolved and pay you afterwards for your help with this one! 

I sent an invitation to this job in Upwork - https://www.upwork.com/jobs/~01c81d6b609195757b

**Comment by dhanashree-sawant** [comment] 2023-06-08 17:29
Thanks @Christinadobrzyn, I have accepted the offer.

**Comment by Christinadobrzyn** [comment] 2023-06-12 22:48
Sorry about https://github.com/Expensify/App/issues/20095#issuecomment-1587624753 - reoved the Help Wanted label - following https://github.com/Expensify/App/issues/16296

**Comment by Christinadobrzyn** [comment] 2023-06-20 22:34
following https://github.com/Expensify/App/issues/16296

**Comment by Beamanator** [comment] 2023-07-03 10:49
PR from ^ issue is in Prod - can we re-test and hopefully close this out?

**Comment by dhanashree-sawant** [comment] 2023-07-03 15:25
Hi @Christinadobrzyn, in case if it is closing, can you approve the job on upwork?

**Comment by priyeshshah11** [comment] 2023-07-03 15:55
@Christinadobrzyn could you please also confirm if I am eligible for the fixing bonus on this issue? 🙂

**Comment by Christinadobrzyn** [comment] 2023-07-03 22:23
Testing again - This looks to be resolved! 

@dhanashree-sawant and @priyeshshah11  can you test and confirm?

@priyeshshah11 you are eligible for the speed bonus per this comment - https://github.com/Expensify/App/issues/16296#issuecomment-1600694741 were you not paid that extra 50%?

**Comment by dhanashree-sawant** [comment] 2023-07-04 02:49
Hi @Christinadobrzyn, yes now it is working correct. Seems to be resolved.

**Comment by priyeshshah11** [comment] 2023-07-04 08:18
> @priyeshshah11 you are eligible for the speed bonus per this comment - [#16296 (comment)](https://github.com/Expensify/App/issues/16296#issuecomment-1600694741) were you not paid that extra 50%?

@Christinadobrzyn No I did not & I don't think I am even eligible for that 50% bonus but what I was referring to was the compensation for fixing #20095.

**Comment by Christinadobrzyn** [comment] 2023-07-05 21:17
@priyeshshah11 from what I can see in the Upwork job https://www.upwork.com/jobs/~010517ed943d1f3420, you were already paid for https://github.com/Expensify/App/issues/16296. If there was an issue with that payment or if you have questions about being paid for reporting, can you please comment in this other GH?

**Comment by Christinadobrzyn** [comment] 2023-07-05 21:21
Paying out this GH based on my comment here - https://github.com/Expensify/App/issues/20095#issuecomment-1583017674

@Prince-Mendiratta 
@dhanashree-sawant

**Comment by mountiny** [comment] 2023-07-08 23:10
@Christinadobrzyn i believe we should pay @priyeshshah11 here for this fix too as his pr resolved this bug while also migrated to the functional component which was paid in the other issue.

I believe that would be $1000 for the pr to them.

Let me know if anything if this works 🙇

**Comment by Christinadobrzyn** [comment] 2023-07-10 21:17
Awesome, sent an offer to a new Upwork job - 

Internal job - https://www.upwork.com/ab/applicants/1678512838515896320/job-details
External job - https://www.upwork.com/jobs/~01ec86bf1d98921bf1

@priyeshshah11 Let me know when you've accepted the job and I'll pay it out!

**Comment by mountiny** [comment] 2023-07-10 21:36
Yep C+ should be paid the same as the contributor.

**Comment by Christinadobrzyn** [comment] 2023-07-10 22:09
Invited @aimane-chnaif also to the Upwork job. The job is these links https://github.com/Expensify/App/issues/20095#issuecomment-1629744482

I'm very confused as I thought we pay in the Upwork job related to the fix so that is this job https://github.com/Expensify/App/issues/16296#issuecomment-1627548073

Since @aimane-chnaif and @priyeshshah11 aren't assigned to this GH. I'm confused I pay @rushatgabhane as they are assigned to this job?

**Comment by priyeshshah11** [comment] 2023-07-11 00:24
> Awesome, sent an offer to a new Upwork job -
> 
> Internal job - https://www.upwork.com/ab/applicants/1678512838515896320/job-details External job - https://www.upwork.com/jobs/~01ec86bf1d98921bf1
> 
> @priyeshshah11 Let me know when you've accepted the job and I'll pay it out!

@Christinadobrzyn Accepted, thanks 😊

**Comment by Christinadobrzyn** [comment] 2023-07-11 23:43
Awesome! I paid @aimane-chnaif and @priyeshshah11 $1000 for the fix of https://github.com/Expensify/App/issues/16296#issuecomment-1600694741

I think this is good? Let me know if anything else needs to happen! Thanks

**Closed** 2023-07-12 13:48 UTC
Labels: External, Daily, Bug
