### ISSUE TITLE
[$1000] Login - Can't log in due to never receiving the magic code

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19036] opened 2023-05-16 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Enter the email [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)
in input field
3. Press Continue
4. Go to mail and find received magic code for login

## Expected Result:
Magic code comes and you can login with it.
The same behavior for [applausetester+ihchat3@applause.expensifail.com](mailto:applausetester+ihchat3@applause.expensifail.com)

## Actual Result:
Can't log in to a special account, the magic code doesn't come

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.14.9

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com)

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/701b3644-5862-4fd1-b095-e122a2b38276

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e963858b42095b41</li>
        <li>Upwork Job ID: 1664777818226454528</li>
        <li>Last Price Increase: 2023-06-02</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-05-18 01:20
@kbecciv can you reproduce this? Because I don't have this problem and cannot reproduce given the steps involve your login.

**Comment by kevinksullivan** [comment] 2023-05-18 01:20
Going to keep this with you for now, but also going to OOO, so I will assign someone else. But I still think we need this to be reproduced.

**Comment by bfitzexpensify** [comment] 2023-05-22 08:42
@kbecciv bump on https://github.com/Expensify/App/issues/19036#issuecomment-1552278760

**Comment by bfitzexpensify** [comment] 2023-05-25 07:41
@kbecciv is this still reproducable? I'm not able to reproduce it myself, but I'm also uncertain on the designation of a 'special' account

**Comment by kbecciv** [comment] 2023-05-26 14:02
@bfitzexpensify @kevinksullivan The issue is still exists, please check the video. 
I did not receive the Magic code for this account [applausetester+ihchat4@applause.expensifail.com](mailto:applausetester+ihchat4@applause.expensifail.com). Thank you

https://github.com/Expensify/App/assets/93399543/6bdd56b6-718e-43d7-bd4c-d14867c32529

**Comment by kevinksullivan** [comment] 2023-05-26 18:55
taking to slack

https://expensify.slack.com/archives/C049HHMV9SM/p1685127332921049

**Comment by kevinksullivan** [comment] 2023-05-26 18:56
Also sorry for dropping this on ya @bfitzexpensify , I didn't see the update in the process. I'll take it back.

**Comment by kevinksullivan** [comment] 2023-05-31 20:38
Still discussing in the slack thread

**Comment by kevinksullivan** [comment] 2023-06-02 23:35
Reproduced by these emails as well:

[achavezutest.101022@gmail.com](mailto:achavezutest.101022@gmail.com)
[applausetester+1108chaves@applause.expensifail.com](mailto:applausetester+1108chaves@applause.expensifail.com)
[applausetester+1208chavez@applause.expensifail.com](mailto:applausetester+1208chavez@applause.expensifail.com)

So I am going to keep this moving.

**Comment by PauloGasparSv** [comment] 2023-06-05 12:37
I think this may be internal, will investigate a bit further later today. 

I'll see if I can find the logs for [this attempt ](https://github.com/Expensify/App/issues/19036#issuecomment-1564442056) to understand what happened

**Comment by kevinksullivan** [comment] 2023-06-06 15:53
Posted to slack to discuss further

https://expensify.slack.com/archives/C049HHMV9SM/p1686066797527599?thread_ts=1685127332.921049&cid=C049HHMV9SM

**Comment by PauloGasparSv** [comment] 2023-06-06 18:33
I investigated this further [here](https://expensify.slack.com/archives/C049HHMV9SM/p1686069178604799?thread_ts=1685127332.921049&cid=C049HHMV9SM) and also tested and compared [logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%227d32b5766e8b4ed1-GRU%22%20AND%20timestamp%3A%5B2023-06-06T00%3A00%20TO%202023-06-07T23%3A59%5D) of signing-in with `paulo@expensifail.com` (since it's an account that's not @expensify.com but it's on the passwordLess beta).

I can't find any errors in the logs and they indicate the magicCode was always sent successfully:


![image](https://github.com/Expensify/App/assets/6564265/db62d9d5-e063-4c53-bf43-278eb346fda1)
 
![image](https://github.com/Expensify/App/assets/6564265/0d216554-d275-423a-bafa-b058832779de)

@kbecciv can you please check if those magicCode emails were sent but flagged as SPAM or similar in your email inbox? Can you also please make a new attempt to sign-in to one of those faulty accounts so new logs are generated?

**Comment by PauloGasparSv** [comment] 2023-06-06 19:59
The discussion continued [here](https://expensify.slack.com/archives/C049HHMV9SM/p1685127332921049), these magicCodes are not in any SPAM folder.

I'm not sure how to investigate this further so asked the team for help [here](https://expensify.slack.com/archives/C03TQ48KC/p1686081526345099).

**Comment by PauloGasparSv** [comment] 2023-06-06 21:28
We got some help from the team and tested this further [until all accounts received the Magic Code](https://expensify.slack.com/archives/C049HHMV9SM/p1686084953545429?thread_ts=1685127332.921049&cid=C049HHMV9SM)!

@kbecciv please LMK if you find steps that reproduce this bug as [mentioned here](https://expensify.slack.com/archives/C049HHMV9SM/p1686085155601599?thread_ts=1685127332.921049&cid=C049HHMV9SM) or if we should close this out.

**Comment by PauloGasparSv** [comment] 2023-06-07 13:21
I'm sorry @kbecciv! I should have tagged @kavimuru in that message 🤦‍♂️

**Comment by PauloGasparSv** [comment] 2023-06-08 15:29
Closing this, let's re-open [if the issue happens again](https://expensify.slack.com/archives/C049HHMV9SM/p1686085155601599?thread_ts=1685127332.921049&cid=C049HHMV9SM) : )

**Closed by PauloGasparSv** 2023-06-08 15:29 UTC
Labels: Daily, Internal, Bug
