### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Android - Timezone-Instead of Asia/Kolkata, America/Los Angeles time zone displayed

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49014] opened 2024-09-11 18:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.32-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4949281
**Issue reported by:** Applause Internal Team

## Action Performed:
Keep location enabled in your device
1. Login with new account
2. Tap profile icon - profile -- timezone

## Expected Result:
Incorrect time zone displayed.

## Actual Result:
Instead of Asia/Kolkata, America/Los Angeles time zone displayed.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6b280be2-3884-41a1-8f0c-1928dba75eaa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835786081971713587</li>
        <li>Upwork Job ID: 1835786081971713587</li>
        <li>Last Price Increase: 2024-10-07</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 104308342</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by IuliiaHerets** [comment] 2024-09-11 18:07
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-09-13 17:12
Hm, I can't repro this on the browserstack. Asking someone with an Android device to give it a try.

**Comment by slafortune** [comment] 2024-09-13 18:04
I can reproduce this in CST - 
![image](https://github.com/user-attachments/assets/808f84c5-b01a-4adf-8ec5-047295100d42)

**Comment by trjExpensify** [comment] 2024-09-16 21:01
Thanks, @slafortune! Moving it on. 👍

**Comment by huult** [comment] 2024-09-17 07:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Timezone-Instead of Asia/Kolkata, America/Los Angeles time zone displayed

### What is the root cause of that problem?

When executing the `Onyx` connection with `key: ONYXKEYS.PERSONAL_DETAILS_LIST`, the data for `ONYXKEYS.PERSONAL_DETAILS_LIST` has not been added yet So`value` returns empty object, causing `timezone` to return an [empty object](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L149), and the [personal details](https://github.com/Expensify/App/blob/main/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L156) do not update the timezone

https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L149

https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L154-L160

<img width="867" alt="Screenshot 2024-09-17 at 14 13 18" src="https://github.com/user-attachments/assets/c1fc1875-c04d-403e-8e82-2208e48eb901">


### What changes do you think we should make in order to solve the problem?

This issue only occurs with newly created accounts where the default value automatically determines the location. To resolve it, we can simply skip checking `selected` and `currentTimezone`, as shown in the following code:
```diff
// .src/libs/Navigation/AppNavigator/AuthScreens.tsx#L154
-         if (!isEmptyObject(currentTimezone) && timezone?.automatic && timezone?.selected !== currentTimezone) {
+.       if (!isEmptyObject(currentTimezone) && (isEmptyObject(timezone) || (timezone.automatic && timezone.selected !== currentTimezone))) {
```
<summary>
<details>POC

https://github.com/user-attachments/assets/9543d155-dabd-4b09-858b-75659ee9cf37

</details>
</summary>

**Comment by mkzie2** [comment] 2024-09-18 10:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Instead of Asia/Kolkata, America/Los Angeles time zone displayed.

### What is the root cause of that problem?
- This issue occurs when we create a new account. After creating a new account, this callback
https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L144
is called a few times.

1. 1st time, ```value: {}```, ```timezone: undefined```, it set ```timezone``` to ```{}``` in:
https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L149
and then return.


2. 2nd time, 
```value: {
    "1234567": {
        "accountID": 1234567,
        "timezone": {
            "automatic": true,
            "selected": "Asia/Kolkata"
        },
    }
}
```
and 

```timezone: {}``` so it will early return in:
https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L146
and there is no API to update the timezone is triggered.
### What changes do you think we should make in order to solve the problem?
- This this condition:
https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L145
we should check ```!isEmptyObject(timezone)``` instead of ```timezone```.

### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment] 2024-09-22 07:25
This is fairly straightforward so we can move forward with @huult's [proposal](https://github.com/Expensify/App/issues/49014#issuecomment-2354747303).

🎀👀🎀 C+ reviewed.

**Comment by mkzie2** [comment] 2024-09-22 07:45
@akinwale I tested your selected solution but the bug is still appeared. Did I miss something? With that solution, the code is early returned in: https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L146 if timezone is {}.

**Comment by akinwale** [comment] 2024-09-22 07:47
> @akinwale I tested your selected solution but the bug is still appeared. Did I miss something? With that solution, the code is early returned in:
> 
> https://github.com/Expensify/App/blob/539327dc2d0585624e5e0b990ca0d79f4e66e81b/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L146
> 
> if timezone is {}.

I'll have another look at this.

**Comment by huult** [comment] 2024-09-22 08:56
@akinwale, Thank you for reviewing my proposal.

The solution to this issue is to check whether the `timeZone` object is empty or not. I will test more during the PR phase, optimize the code as necessary.

**Comment by mkzie2** [comment] 2024-09-23 08:17
@akinwale Is [this](https://github.com/Expensify/App/issues/49014#issuecomment-2365711313) still your final decision, right?

**Comment by akinwale** [comment] 2024-09-23 08:43
> @akinwale Is [this](https://github.com/Expensify/App/issues/49014#issuecomment-2365711313) still your final decision, right?

No, I will run some tests and then post an update afterwards. Thanks for bringing it up.

**Comment by huult** [comment] 2024-09-23 08:46
@mkzie2 , the decision by @akinwale  is correct. My proposal provides the right solution to resolve this issue, and it was submitted first. I believe my proposal works correctly. However, if there are any bugs, we can check them during the PR phase since this is just a proposal aimed at resolving the issue. 

Additionally, if your solution works well without checking whether timeZone is empty, feel free to show it to @akinwale. Your solution is similar to mine, However, you’ve adjusted the condition, and we can check it during the PR phase if it’s suitable. I believe they are essentially the same, and I can also optimize this code in other ways.

cc @dangrous

**Comment by akinwale** [comment] 2024-09-23 08:49
> @mkzie2 , the decision by @akinwale is correct. My proposal provides the right solution to resolve this issue, and it was submitted first. I believe my proposal works correctly. However, if there are any bugs, we can check them during the PR phase since this is just a proposal aimed at resolving the issue.
> 

If the solution does not correctly solve the problem and there is an alternative proposal, then I would have to evaluate both to determine the correct one, regardless of which was posted first, hence why I would have to test both approaches.

**Comment by dangrous** [comment] 2024-09-24 19:11
@akinwale how are we looking here? Have you had the chance to re-review the proposals? I saw the ping [here](https://github.com/Expensify/App/issues/49014#issuecomment-2365711929) but it looks like you were going to take a closer look before confirming. Let me know if that's an incorrect assumption though!

**Comment by trjExpensify** [comment] 2024-09-26 23:00
@akinwale can you get to this please? Thanks!

**Comment by trjExpensify** [comment] 2024-09-30 21:35
We've had proposals since Sept 17th and they haven't been reviewed. @akinwale if you can't review this tomorrow, please bring it up in the C+ channel so we can reassign.

**Comment by akinwale** [comment] 2024-10-01 14:58
Apologies for the delay. I'll test both proposals and then provide an update.

**Comment by trjExpensify** [comment] 2024-10-02 00:00
Thanks, what's your ETA on that?

**Comment by akinwale** [comment] 2024-10-02 13:21
I am testing right now. Having some issues with the Android build but I should be able to get that resolved soon.

**Comment by dangrous** [comment] 2024-10-02 14:14
Looks like there was an issue with the Android build on `main` - if you're still having trouble, try pulling again? https://expensify.slack.com/archives/C01GTK53T8Q/p1727855716697299

**Comment by akinwale** [comment] 2024-10-03 06:54
I was able to build successfully after pulling the latest main. Upon testing, while the initial selected proposal actually fixes the problem, it causes a regression with the onboarding process for new users where the profile is not properly initialised and the initial "What do you want to use Expensify for?" wizard is skipped.

@mkzie2's proposed solution does not fix the problem at all.

@huult and @mkzie2 can update their proposals with proper fixes and whoever gets the correct solution first could get selected, but ultimately, we're waiting for a correct proposal on this one.

cc: @dangrous

**Comment by akinwale** [comment] 2024-10-03 06:57
> Hm, I can't repro this on the browserstack. Asking someone with an Android device to give it a try.

@trjExpensify To easily reproduce this, you'd need to use a fresh install (or clear the storage from app settings), and then log in to the app with a new user account.

**Comment by huult** [comment] 2024-10-03 07:29
@akinwale , Could you please provide the steps to reproduce your issue? I attempted to bypass the onboarding by removing the HTML related to the onboarding and proceeded directly to the profile page, and my approach still worked.

**Comment by akinwale** [comment] 2024-10-03 08:09
@mkzie2 Are you testing your change with latest main on the Android native platform?

**Comment by mkzie2** [comment] 2024-10-03 08:38
> @mkzie2 Are you testing your change with latest main on the Android native platform?

I tested and here is the evidence:

https://github.com/user-attachments/assets/0d184365-6cb3-47cc-9919-6cff0d2dea2f

**Comment by huult** [comment] 2024-10-03 10:32
## [Proposal Updated](https://github.com/Expensify/App/issues/49014#issuecomment-2354747303)

- Change the solution to resolve this issue
- Update POC

@akinwale , can you check again? Thank you.

**Comment by trjExpensify** [comment] 2024-10-03 10:36
>@trjExpensify To easily reproduce this, you'd need to use a fresh install (or clear the storage from app settings), and then log in to the app with a new user account.

I don't have a physical Android device, but beside the point, I was able to get someone else on the BZ team with one to repro.

**Comment by mvtglobally** [comment] 2024-10-05 03:08
Issue not reproducible during KI retests. (First week)

**Comment by huult** [comment] 2024-10-05 03:27
It's still happening on v9.0.45-2
<summary><details>POC

https://github.com/user-attachments/assets/23137c38-a717-4135-8675-9ea94d83e973

</details></summary>

**Comment by akinwale** [comment] 2024-10-05 16:33
@mkzie2 I tested with the wrong condition (missed the `!` operator).

We can proceed with @mkzie2's [proposal](https://github.com/Expensify/App/issues/49014#issuecomment-2358100010) here.

cc: @dangrous

**Comment by dangrous** [comment] 2024-10-07 19:05
sounds good!

**Comment by dangrous** [comment] 2024-10-09 15:32
How are we looking on the pr @mkzie2 ?

**Comment by akinwale** [comment] 2024-10-14 14:48
> @akinwale do you think you'll have time to review today?

Yes, I'll get this later today.

**Comment by akinwale** [comment] 2024-10-25 15:21
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify
2. Log in with a new account
3. Finish the onboarding steps
4. Navigate to Settings > Profile
5. Verify that the correct timezone based on the device's settings is displayed

Do we agree 👍 or 👎?

**Comment by trjExpensify** [comment] 2024-10-25 19:09
>Not a regression.

Can you expand on that a bit, please? It's certainly not expected that the timezone of the app is PST on sign-up. We have a timeZone account NVP that's set, and has been for years.

**Comment by akinwale** [comment] 2024-10-28 13:57
> > Not a regression.
> 
> Can you expand on that a bit, please? It's certainly not expected that the timezone of the app is PST on sign-up. We have a timeZone account NVP that's set, and has been for years.

The timezone being an empty object was never accounted for in the original implementation, so that led to this issue where it falls back to the default which is PST.

https://github.com/Expensify/App/blob/9f977340394a510adaf8b40c31ba7cc0eb09a9ca/src/CONST.ts#L1268

**Comment by trjExpensify** [comment] 2024-10-29 02:08
Hm, okay. I'm not wholly convinced this isn't a regression from somewhere later than the implementation of the timeZone profile setting (i.e some "personal details" onyx updates or something), but probably not worth investing in further. 

Payment summary as follows: 

- $250 to @akinwale for the C+ review (paid!)
- $250 to @mkzie2 for the fix (offer sent!)

**Comment by trjExpensify** [comment] 2024-10-29 21:45
Paid, closing!

**Closed by trjExpensify** 2024-10-29 21:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
