### ISSUE TITLE
[$500] IOU - Keyboard comes out from right to left on participant screen

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37257] opened 2024-02-27 02:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**  1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app and log in
2. Tap the FAB > Request money
3. Select any option
4. Enter the amount if it is a manual request
5. Proceed to the participant screen

## Expected Result:
The keyboard comes out from bottom to top

## Actual Result:
The keyboard comes out from the right to the left. In other areas, for example, in search or start chat it appears from bottom to top

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8257933e-92ac-4023-b802-77af057ce786

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f111bd2927acf29</li>
        <li>Upwork Job ID: 1762307582490816512</li>
        <li>Last Price Increase: 2024-02-27</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-27 02:44
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by youssef-lr** [comment] 2024-02-27 03:16
I think it might be coming from [here](https://github.com/Expensify/App/pull/29991), cc @mountiny @hannojg

**Comment by bi-kash** [comment] 2024-02-27 03:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The current issue revolves around the animation of the keyboard, which is currently sliding in from the right instead of the desired bottom sliding motion.

### What is the root cause of that problem?
The root cause of the problem lies in the existing animation code located in src/libs/Navigation/AppNavigator/modalStackNavigatorOptions/index.native.ts. The animation property is set to 'slide_from_right', causing the keyboard to slide in from the right.

```javascript
const defaultSubRouteOptions: NativeStackNavigationOptions = {
    headerShown: false,
    animation: 'slide_from_right',
};
```

### What changes do you think we should make in order to solve the problem?
To rectify the issue, a correction in the animation property is needed. The animation should be adjusted to 'slide_from_bottom' to ensure the keyboard slides in from the bottom.
```javascript
const defaultSubRouteOptions: NativeStackNavigationOptions = {
    headerShown: false,
    animation: 'slide_from_bottom',
};
```

### What alternative solutions did you explore? (Optional)
NA

**Comment by youssef-lr** [comment] 2024-02-27 03:39
Thanks for the proposal, let's wait to hear from @hannojg if this is intended or not. I think this can be fixed by the original author as it's not technically a bug, just a choice we made.

**Comment by godofoutcasts94** [comment] 2024-02-27 10:19
I don't think it is a bug, it is more like a preference.

**Comment by puneetlath** [comment] 2024-02-27 19:41
>Thanks for the proposal, let's wait to hear from @hannojg if this is intended or not. I think this can be fixed by the original author as it's not technically a bug, just a choice we made.

Going to remove the deploy blocker label, given this comment.

**Comment by MonilBhavsar** [comment] 2024-02-28 07:20
Yes, This is resolved now. So closing

**Closed by MonilBhavsar** 2024-02-28 07:20 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted
