### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Expense - System message for report submission is not copied when copied to clipboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32285] opened 2023-11-30 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6.2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32157
## Action Performed:
Precondition:
- User is an employee of a Collect workspace
1. Log in to ND as the employee
2. Go to the workspace chat > + > Request money
3. Create a manual request
4. Click on the expense preview > Submit
5. Click on the header subtitle to return to workspace main chat
6. Click on the expense preview
7. Right click on the 'report submission' message > Copy to clipboard
8. Paste it in the composer

## Expected Result:
The system message for 'report submission' is copied

## Actual Result:
The system message for 'report submission' is not copied

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/991e8277-c601-4b03-a785-cc326a7fcebe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dc72215454974184</li>
        <li>Upwork Job ID: 1730286719439400960</li>
        <li>Last Price Increase: 2023-11-30</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 27951200</li>
<li>bernhardoj | Contributor | 27951201</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by FitseTLT** [comment] 2023-11-30 18:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Expense - System message for report submission is not copied when copied to clipboard

### What is the root cause of that problem?
We are not handling the sumission report action case in here
https://github.com/Expensify/App/blob/a7460f7f81c9999cf20964e67b6f9029dc18a51f/src/pages/home/report/ContextMenu/ContextMenuActions.js#L263-L264
### What changes do you think we should make in order to solve the problem?

We need to add to here
https://github.com/Expensify/App/blob/a7460f7f81c9999cf20964e67b6f9029dc18a51f/src/pages/home/report/ContextMenu/ContextMenuActions.js#L284-L287
this
```
else if (reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.SUBMITTED) {
                    Clipboard.setString(lodashGet(reportAction, 'message.0.text', ''));
                }
```
### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2023-11-30 18:49
Just checked 

@FitseTLT [proposal](https://github.com/Expensify/App/issues/32285#issuecomment-1834323310) works correctly. I think we should go with this.

🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2023-12-01 03:39
Please ignore my previous comment

The issue is open for proposals again.

**Comment by shubham1206agra** [comment] 2023-12-01 03:44
@FitseTLT You are kind of right. But need more changes to work actually.

<img width="866" alt="Screenshot 2023-12-01 at 9 13 29 AM" src="https://github.com/Expensify/App/assets/58412969/493c112a-39c5-4a15-92e9-9b8a4b616679">

You may need to modify according to this reportAction

**Comment by shubham1206agra** [comment] 2023-12-01 14:59
> Any way to get access to/part of Collect Workspace?

Ask this on slack when you are assigned

**Comment by lakchote** [comment] 2023-12-19 05:28
@shubham1206agra please complete the bugzero checklist thanks!

**Comment by shubham1206agra** [comment] 2023-12-19 09:50
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28947
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28947#issuecomment-1862441403
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as it was edge case from backend
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by shubham1206agra** [comment] 2024-01-08 12:46
@lakchote Bump

**Comment by shubham1206agra** [comment] 2024-01-15 08:31
@laurenreidexpensify Can you process payment here please?

**Comment by laurenreidexpensify** [comment] 2024-01-15 11:50
Payment Summary: 

Contributor $500 paid in Upwork @bernhardoj 
C+ $500 paid in Upwork @shubham1206agra

**Closed by laurenreidexpensify** 2024-01-15 11:50 UTC
Labels: External, Daily, Awaiting Payment, Bug
