### ISSUE TITLE
[HOLD for payment 2024-10-30] [$250] 2nd-level+ Non-admin approver should NOT be able to Submit draft reports on behalf of their submitters

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#48778] opened 2024-09-09 10:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** [logs-2024-09-13 16_55_08.340.txt](https://github.com/user-attachments/files/16997254/logs-2024-09-13.16_55_08.340.txt)
**Expensify/Expensify Issue URL:**
**Issue reported by:** @saracouto 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1725864497268339

## Action Performed:
1. Create a workspace
2. Invite a submitter and 2 approvers (both NON-ADMINS)
3. Enable approvals setting Submitter -> `submitsTo` approver 1 -> `forwardsTo` approver 2
4. Enable Delay submissions
5. Create an expense as the submitter
6. As the approver 1, submit & approve the report
7. As the approver 2, navigate to the submitter's workspace chat

## Expected Result:
As a second-level+ **non-admin** approver, you **should NOT** see the 'submit' button. 

## Actual Result:
As a non-admin approver, you see the 'submit' button. When you tap/click it, you get an error.

## Workaround:
There is no workaround.

## Platforms:
All

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833163296746944359</li>
        <li>Upwork Job ID: 1833163296746944359</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Reviewer | 104458910</li>
<li>cretadn22 | Contributor | 104458913</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @greg-schroeder</details>

**Comment by NJ-2020** [comment] 2024-09-09 11:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Non-admin approver shouldn't see the Submit option for submitters
### What is the root cause of that problem?
Right here
https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/components/ReportActionItem/ReportPreview.tsx#L187
We show the submit button if the expense is open and the reimbursable spend is not equal to zero and doesn't have any violation message
### What changes do you think we should make in order to solve the problem?
We can check if the `iouReport.ownerAccountID` is equal to currentAccountID then we will show the submit button

### What alternative solutions did you explore? (Optional)

**Comment by ChavdaSachin** [comment] 2024-09-09 12:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Submit button is enabled for non-admin approver to submit expanse on behalf of member

### What is the root cause of that problem?
- When checking condition, whether submit button should be disabled [here](https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/components/MoneyReportHeader.tsx#L133), `ReportUtils.isAllowedToSubmitDraftExpenseReport` function is used to check permissions.
https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/libs/ReportUtils.ts#L7380-L7385
- So this function allows all approver(includes admin and owner) to submit on behalf of employee.

### What changes do you think we should make in order to solve the problem?
- disable submit button for `non-admin non-policyOwner approver`
- Include a new function `isAdminOwnerOrReportOwner`(similar to [isAdminOwnerApproverOrReportOwner](https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/libs/ReportUtils.ts#L7449) under `ReportUtils.ts` to check whether user is `reportOwner` or `policyAdmin` or `policyOwner`.
```js
function isAdminOwnerOrReportOwner(report: OnyxEntry<Report>, policy: OnyxEntry<Policy>): boolean {
    return PolicyUtils.isPolicyAdmin(policy) || PolicyUtils.isPolicyOwner(policy, currentUserAccountID ?? -1) || isReportOwner(report);
}
```
- Replace `isAllowedToApproveExpenseReport` with `isAdminOwnerOrReportOwner` and remove redundant line.
```js
function isAllowedToSubmitDraftExpenseReport(report: OnyxEntry<Report>): boolean {
    const policy = getPolicy(report?.policyID);

    return isAdminOwnerOrReportOwner(report, policy);
}
```
https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/libs/ReportUtils.ts#L7380-L7385
<details><summary><h2>Result</h2></summary>
<img width="437" alt="Screenshot 2024-09-09 at 5 45 47 PM" src="https://github.com/user-attachments/assets/89700970-1c1e-4923-90f8-eaefe82b09b4">
<img width="1678" alt="Screenshot 2024-09-09 at 5 45 39 PM" src="https://github.com/user-attachments/assets/9c78690b-8a22-4ea1-b414-fe116a34cb9b">
</details>

### What alternative solutions did you explore? (Optional)

**Comment by Beamanator** [comment] 2024-09-09 15:19
Assigning `External` for a C+ to help with this one 🙏

**Comment by ChavdaSachin** [comment] 2024-09-09 16:40
## Proposal
[updated](https://github.com/Expensify/App/issues/48778#issuecomment-2337986753)
Added alternate solution.

**Comment by NJ-2020** [comment] 2024-09-10 10:15
### [Proposal Updated](https://github.com/Expensify/App/issues/48778#issuecomment-2337880165)

**Comment by greg-schroeder** [comment] 2024-09-12 18:23
@Beamanator @garrettmknight where do you think we've landed here - should we still hold on proposals?

**Comment by Beamanator** [comment] 2024-09-12 20:58
Good question, looks like garrett might be looking into creating new issues / updating existing issues for the agreed upon solution - see https://expensify.slack.com/archives/C06ML6X0W9L/p1725978630280069?thread_ts=1725864497.268339&cid=C06ML6X0W9L

**Comment by garrettmknight** [comment] 2024-09-13 17:05
I've updated the OP with the new expected behavior. This is back open for proposals.

**Comment by garrettmknight** [comment] 2024-09-13 17:06
I've also added logs to the OP.

**Comment by aldo-expensify** [comment] 2024-09-13 17:22
> As a non-admin approver, you see the 'submit' button. When you tap/click it, you get an error.

We think this is the error: https://github.com/Expensify/Expensify/issues/428170. This feels like something we have to fix in the backend so it is allowed and doesn't throw an error.

**Comment by ChavdaSachin** [comment] 2024-09-13 17:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Approver to submit on behalf owner produces error

### What is the root cause of that problem?
- We are not handling the approver case https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/libs/actions/IOU.ts#L7161-L7176

### What changes do you think we should make in order to solve the problem?
- Add additional case for approver 
```js
    const approverAccountID = policy?.role === CONST.POLICY.ROLE.AUDITOR ? currentUserPersonalDetails?.accountID : undefined;
```
and pass this here
```js
    const optimisticSubmittedReportAction = ReportUtils.buildOptimisticSubmittedReportAction(expenseReport?.total ?? 0, expenseReport.currency ?? '', expenseReport.reportID, adminAccountID ?? approverAccountID);
```
https://github.com/Expensify/App/blob/498d45cc55bae4dde9f85036c75d5a421e0469e9/src/libs/actions/IOU.ts#L7173
And do some variable renaming afterwards.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Beamanator** [comment] 2024-09-13 18:16
this will probably have a bit of internal and a bit of external stuff

**Comment by greg-schroeder** [comment] 2024-09-16 10:10
Okay, so we're into proposal review still

**Comment by Beamanator** [comment] 2024-09-16 22:01
Goood question @greg-schroeder , can you tell if the `Submit` button shows for all approvers of a report?

**Comment by greg-schroeder** [comment] 2024-09-19 01:19
Hmm. It's actually a bit difficult to test all cases of this, but I think it does show for all approvers from what I can see in my test account

**Comment by garrettmknight** [comment] 2024-09-19 19:12
@Beamanator `Submit` has been showing for first and second-level approvers for me.

**Comment by Beamanator** [comment] 2024-09-20 21:40
Groovy, so still the possible external component could be: If first and second-level approvers click Submit offline, what happens

**Comment by greg-schroeder** [comment] 2024-09-23 17:46
Okay, understood

**Comment by greg-schroeder** [comment] 2024-09-25 19:16
This is still awaiting someone to take it on I believe

**Comment by Beamanator** [comment] 2024-09-26 01:18
Ok so what I'm seeing so far is this... Say we have Submitter -> Approver A -> Approver B.
1. When Approver A submits, everything works fine 👍  (all the way through reimbursing)
2. ^ Same when an admin submits
3. When Approver B tries to submit...
    1. Offline everything seems to work well -> So I think we can remove `External` here 👍 
    2. Online, we throw an exception... This is because we CURRENTLY only allow admins or current approvers to "force submit"

**Comment by Beamanator** [comment] 2024-09-26 01:25
cc @garrettmknight ^ So it looks like if we want to keep NewDot consistent with OldDot, the only change we'd have to make is: _For non-admin, non-manager approvers (a.k.a. for second-level approvers & up who aren't admins), HIDE `Submit` button from NewDot

**Comment by greg-schroeder** [comment] 2024-09-30 10:06
@garrettmknight What do you think about the above?

**Comment by greg-schroeder** [comment] 2024-10-02 19:15
gentle bump @garrettmknight!

**Comment by Beamanator** [comment] 2024-10-07 18:50
@cretadn22 true, but isn't that already allowed right now? The creator of the money request = the submitter, who definitely **should** currently be able to submit

**Comment by Beamanator** [comment] 2024-10-08 14:40
Yeah i think @garrettmknight was OOO, should be coming back in the next day or two

**Comment by garrettmknight** [comment] 2024-10-08 21:17
Sorry for the wait here - I'd agree that all we really need to do is to ensure the Submit button shows and works for the submitter, first approver and workspace admins. Said differently, we want to hide it for second-level and above submitters, but it's probably easier to focus on who should be able to see the button imo.

**Comment by Beamanator** [comment] 2024-10-08 21:20
No prob at all, thanks for confirming!

And just b/c i'm super picky, I have to ask: you're ok if we do "hide it [the submit button] for second-level and above submitters **THAT ARE NOT ADMINS**" right?

B/c technically right now, in OldDot, all admins are able to submit, I believe (even second-level and above)

**Comment by Beamanator** [comment] 2024-10-08 21:24
Amazalicious, thank you sir 🙏

**Comment by Beamanator** [comment] 2024-10-08 21:28
Ok so @ikevin127 I thinkkkkk we're 100% good to go externally here, can you confirm & if you agree, see if any existing proposals satisfy the new requirements? I'm happy to help answer any questions if you've got any! :D

**Comment by ikevin127** [comment] 2024-10-08 21:46
@Beamanator Thanks! I noticed all previous proposals were set as `Outdated` (retracted), so given the new requirements discussed above, we're open for new proposals that satisfy the requirements.

cc @cretadn22 @nyomanjyotisa @NJ-2020 If still interested 🥇

**Comment by Beamanator** [comment] 2024-10-08 21:50
Love it 👍  And if we don't get updated proposals by EOD, tomorrow I'll probably add `Help Wanted` back 👍

**Comment by ikevin127** [comment] 2024-10-09 01:36
If what I've been able to put together from the **new requirements** is the following:
1. The roles which **should see** the `Submit` button are:
- `Workspace Owner`
- `Workspace Admin(s)`
- `Submitter` (aka Report Owner)
- `First Approver`
2. The `Second Approver` should **NOT** see the `Submit` button anymore.

... then @nyomanjyotisa's [proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401026662) looks good to me. The RCA is correct, the proposed solution fixes the issue.

**Here's a video showing how it works with the fix:**

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/10c0f490-18bb-4618-b91f-8d8b570a2a61

</details>

**Note**: I know there's a lot of roles to keep in mind but, the only difference that one should notice is that the `Second Approver` does **NOT** see the `Submit` button anymore, which currently happens on staging after the expense is submitted.

^ Related to the staging behaviour, I noticed that if we logout and login again, we won't even see the report details in the report preview anymore, just a blank report preview saying `[workspaceName] owes:` 🤔 (see staging video below)

**Here's a video showing how things look and behave on staging vs dev (with this fix):**

<details>
<summary>Videos</summary>

| Staging | Dev (with this fix) |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/6ffa97dc-ec62-4156-902f-37415fd20b03"> | <video src="https://github.com/user-attachments/assets/a5639cf7-0734-4cd4-89d2-6c2733529180"> |

</details>

> [!caution]
> If any of the looks / behaviours shown in the videos above are off or I misuderstood the issue's expected result or anything else, please feel free to correct me or hold on assignment.

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-10-09 07:10
@Beamanator HOLD on assignment here, I want to review the other proposal as well - since the expected result is not clearly stated in the issue's description, and given that I had to gather the new requirements from the latest posts, I think it's worth looking into this again as I might've missed some parts of the logic that I was not aware about.

**Comment by ChavdaSachin** [comment] 2024-10-09 07:16
@ikevin127 we have quite a few flaws in the approval workflow which might affect us here. And we might need to decide expected behaviour for those cases. I will explain everything in the followup comment by EOD.

**Comment by Beamanator** [comment] 2024-10-09 20:00
@ikevin127 @garrettmknight I updated the OP to what I believe is the new expected result

**Comment by ikevin127** [comment] 2024-10-09 20:20
♻️ Reviewing...

**Comment by ChavdaSachin** [comment] 2024-10-09 21:25
Sorry I did not get time to prepare a detailed comment but let me state issues which I found in short.

1. Workflow - employees->approver 1-> approver 2.
- When approver creates IOU req, submit button is visible for approver 2 but it returns an error when approver 2 tries too submit on behalf of approver 1.
2. Workflow- employees->approver, workflow 2 - approver -> Boss.
- in this case when employee creates and *submits* expanse, approver still had submit button even though expanse is submitted, and Boss had approve button visible at the same time. (Boss account was policy owner)

cc. @ikevin127.

**Comment by ikevin127** [comment] 2024-10-09 22:20
@Beamanator Thanks for updating the issue's description - that cleared up things and helped a lot 👊 and because of the update I was able to reproduce the issue:

<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/e39e65b2-956c-482c-90a6-6ade65e365ea

</details>

##

Going back to the [first proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401026662) that I reviewed and proposed for assignment yesterday, unfortunately, after the issue's description was updated - the fix **does not work** because the `Submit` button is still displayed for the `Second approver`.

Same thing happens with the [second proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401202249)'s solution: the `Submit` button is still displayed for the `Second approver`.

**Both solutions result looks like in the video posted above (reproducing the issue).**

##

**Given this, we're still open for proposals!**

> [!note]
> For ease of testing, I recommend interested contributors to attach a test branch to their proposal because I don't want to mistakenly apply the solutions and create even more confusion.

**Comment by Beamanator** [comment] 2024-10-09 23:06
Thanks @ikevin127 ! Adding `Help Wanted` back 👍

**Comment by ChavdaSachin** [comment] 2024-10-11 18:39
I have an additional doubt here.
For workflow - employee - approver1 - approver2

Should we show the submit button to approver2 when approver1 has draft expanse?

**Comment by ikevin127** [comment] 2024-10-11 19:05
♻️ Will review again today.

**Comment by ikevin127** [comment] 2024-10-11 21:43
I reviewed @cretadn22's [proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401202249) again with the addition of the test branch from https://github.com/Expensify/App/issues/48778#issuecomment-2403882180 and it does work, hiding the `Submit` button from the **2nd-level + non-admin approver** as per the issue's expected result.

**To clear up the difference from staging vs the fix (once applied):**

| Staging | Proposed Fix |
| ------------- | ------------- |
| <img width="450" alt="staging" src="https://github.com/user-attachments/assets/506e04a0-528c-4bdb-b762-421937a4b76b"> | <img width="450" alt="proposal-2" src="https://github.com/user-attachments/assets/7ec298c6-853b-418d-a0e8-4a8105c52686"> |

The reason why I said none of the proposals work in https://github.com/Expensify/App/issues/48778#issuecomment-2403528791 is because I confused the `Submit` button with the `Approve` button. I edited the comment to correct my confusion 👍 

If I understand correctly, the **2nd-level + non-admin approver** should be able to see the `Approve` button **AFTER** the expense was already `Submit`ted, it's just that we don't want to allow them to actually `Submit` the expense, hence why we're hiding.

##

Given this, I'd say let's go with @cretadn22's [proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401202249) as the RCA is correct & complete and the solution is also complete, covering the case of the `MoneyReportHeader` which the first [proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401026662) didn't cover (this would've led to regression).

🎀👀🎀 C+ reviewed

**Comment by ikevin127** [comment] 2024-10-14 20:05
:recycle: **Update**: I was messaged by @cretadn22 on Slack regarding some further clarifications on the issue / fix, which I suggested them post the same questions here, before we move on with assignment because they are worried that there's more to this issue than meets the eye (expected result).

cc @Beamanator @AndrewGable

**Comment by Beamanator** [comment] 2024-10-17 07:33
Unassigning @AndrewGable cuz I am handling 😬 👍 

@ikevin127 thanks so much for your thorough updates as always - but @cretadn22 i'm not sure exactly what your further clarifications / questions are at this point - @ikevin127 you analysis [here](https://github.com/Expensify/App/issues/48778#issuecomment-2408158235) makes a lot of sense to me so it sounds like we're ready to hire @cretadn22 but what are the extra questions?

**Comment by ikevin127** [comment] 2024-10-17 07:36
@cretadn22 Mind posting the same thing you sent me via Slack so we're all on the same page regarding your worries ?

**Comment by Beamanator** [comment] 2024-10-17 07:56
That all looks good and makes sense 👍 
- One clarification point about: `Approver-2 called be D`
    1. If D is not an admin, I agree that D should NOT be able to submit the report
    2. If D is an admin, they should be able to submit

And to be clear, as far as I know for "Who can approve", it works as you explained currently, right? In this issue I believe we'll only **need** to update "make sure 2nd-level+ Non-admin approvers cannot submit the report"

**Comment by Beamanator** [comment] 2024-10-17 08:06
Perfect, then I think we're good to move forward here 👍

**Comment by ikevin127** [comment] 2024-10-17 08:08
Awesome, thanks!

In this case I think we're good to move forward and assign **cretadn22** based on the sorted clarifications above and my previous review of their proposal.

Thanks @Beamanator 🚀

**Comment by ikevin127** [comment] 2024-10-17 22:13
**For context, I'll repost here what I just posted on the PR review https://github.com/Expensify/App/pull/51012#issuecomment-2420560276:**

##

> ⚠️ The code looks clean, but I found the following issues while testing the functionality (see below).

##

Given the following workflow:

<img width="678" alt="ws-workflow" src="https://github.com/user-attachments/assets/8eb3ba5b-2f31-40eb-abfc-bdb994e3c25e">

Once the submitter (John Krakauer) posts a new expense, this is how it looks on their side:
- the first one I pressed the Submit button
- the second one I did not Submit yet

<img width="837" alt="submitter" src="https://github.com/user-attachments/assets/1b37debf-e468-4eae-b0c6-879a0b882ff2">

This is how things look on the 1st Approver's side (K3vin Brian):

<img width="833" alt="1st-approver" src="https://github.com/user-attachments/assets/c2593962-ca93-4270-9cc8-05c865b6e9bb">

This is how things look on the 2nd Approver's side (kevin.bader96+2@gmail.com):

<img width="910" alt="2nd-approver" src="https://github.com/user-attachments/assets/bffe5d2b-54c5-4394-93ef-5bc942bd26cc">

## ⚠️ The issues are as follows

**NOTE:** The pictures above and issues mentioned below are were reproduced on an existing workspace already setup and used before.

1. Only the submitter (John Krakauer) is able to actually `Submit` the expense, approver 1 and 2 while they both see the `Submit` button, if pressed -> they get BE error.
2. Once the submitter pressed `Submit` and submitted the expenses, 1st approver doesn't see any buttons on the expense and 2nd approver will see the `Approve` button.
3. Once the 2nd approver pressed `Approve`, the 1st approver will see the `Approve` button which allows them to approve as well.

### What happens if we test exactly the same flow with exactly the same workflow member setup ?

1. The approver roles are reversed, meaning that in this case the 1st approver will see the `Approve` button once the submitter pressed `Submit` after they posted the expense.
2. If the 1st approver will press `Approve` on the first expense which was submitted by the submitter, then the `Approve` button will show up on the 2nd approver's side.
3. For the second expense on which the submitter did not press `Submit` yet, both approvers see the `Submit` button which should not be the case for the 2nd (as per this fix).
4. If 2nd approver will press the `Submit` button, they will get BE error, not being able to submit.
5. If 1st approver will press the `Submit` button, they are able to submit and now they will have the possibility to `Approve`.
6. If 1st approver will press `Approve` -> 2nd approver will be able to approve as well.

## Summary

Looks like regardless of being on an already setup and previously used WS , or on a freshly setup WS with exactly the same workflow setup -> in both cases there are issues with the flow as described above.

cc @Beamanator for context

**Comment by ikevin127** [comment] 2024-10-18 02:41
♻️ Not related to this issue directly, I just got assigned to review a new issue which is in the same ballpark (`Approver` related) and I thought that people that have some context on this one might be interested in coming up with a proposal:

[[$250] Approver - On deleting add approval workflow, the 2nd approver in default workspace is removed](https://github.com/Expensify/App/issues/50923)

cc @ChavdaSachin @nyomanjyotisa @NJ-2020

**Comment by Beamanator** [comment] 2024-10-18 16:08
Thanks so much for linking that related issue & for discussing what's happening in the PR 👍 

So far I believe I agree with you - that the 2nd approver SHOULD NOT be see or be able to submit the report for the submitter (assuming they're not an admin)

I am not 100% sure if you are also reporting a different error about approving, it looked like you're not reporting a bug there, just describing the flow you tested

**Comment by ikevin127** [comment] 2024-10-18 21:33
Thanks! I retested again after sync w/ main and the tests is passing now:

https://github.com/user-attachments/assets/748cb6e7-9e4c-45e4-8f98-a1c45aaa716e

I left a request in the PR regarding moving forward and being able to Approve it as currently we have a blocker related to the PR Author Checklist.

**Comment by ikevin127** [comment] 2024-10-28 23:19
* [x]  [@ikevin127] The PR that introduced the bug has been identified. Link to the PR: **N/A**.

Wasn't able to pinpoint to a specific PR to have caused this because the `shouldShowSubmitButton` variable simply did not include the logic for our issue's case which was detailed in selected [proposal](https://github.com/Expensify/App/issues/48778#issuecomment-2401202249).

* [x]  [@ikevin127] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**.
* [x]  [@ikevin127] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**.
* [x]  [@ikevin127] Determine if we should create a regression test for this bug.
* [x]  [@ikevin127] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

### Regression Test Proposal

1. Create a workspace.
2. Invite a submitter and 2 approvers (both NON-ADMINS).
3. Enable approvals setting Submitter -> submitsTo approver 1 -> forwardsTo approver 2.
4. Enable Delay submissions.
5. Create an expense as the submitter.
6. As the approver 1, submit and approve the report.
7. As the approver 2, navigate to the submitter's workspace chat.
8. See that the second-level (non-admin) approver should NOT see the `Submit` button.

Do we agree 👍 or 👎.

**Comment by ikevin127** [comment] 2024-10-31 00:55
cc @greg-schroeder

**Comment by greg-schroeder** [comment] 2024-11-01 17:21
Processing

**Closed** 2024-11-01 20:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
