### ISSUE TITLE
[$1000] Web - Assign Task - The emoti icons do not work in chat for task

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24644] opened 2023-08-16 20:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click Assign Task in FAB.
2. Add a new task.
3. Mark the task as done.
4. You will get the chat 'completed task <task name>'
5. Click emoti icons on 'completed task <task name>'

## Expected Result:
The emoti icons should work.

## Actual Result:
The emoti icons do not work.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/bc268304-37dc-43ff-9e9b-bc9b360efa0e

https://github.com/Expensify/App/assets/115492554/7d2a0531-df1a-46fc-ac18-8123ac7ababd

https://github.com/Expensify/App/assets/115492554/fcafca6d-d555-4b36-9091-ee5406a1acd1

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Oleksandr-Pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690987850797129

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01121b95215b1e98f4</li>
        <li>Upwork Job ID: 1691914725035556864</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-08-16 20:46
I can reproduce - In the parent thread I'm able to react but not in the completed task thread

**Comment by pradeepmdk** [comment] 2023-08-17 01:37
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Assign Task - The emoti icons do not work in chat for task
### What is the root cause of that problem?
whenever task completed or reopened `childReportID` is have. so that its getting childReportID instead of ReportID
https://github.com/tienifr/App/blob/5b37315863b28edcdd5e16b63c29012a222a575b/src/libs/ReportUtils.js#L2268
here 
this pr added this
https://github.com/Expensify/App/pull/20574/files
### What changes do you think we should make in order to solve the problem?
https://github.com/tienifr/App/blob/5b37315863b28edcdd5e16b63c29012a222a575b/src/libs/ReportUtils.js?#L2269
```javascript
function getOriginalReportID(reportID, reportAction) {
    return isThreadFirstChat(reportAction, reportID) && ![CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED, CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED, CONST.REPORT.ACTIONS.TYPE.TASKREOPENED].includes(reportAction.actionName) ? lodashGet(allReports, [`${ONYXKEYS.COLLECTION.REPORT}${reportID}`, 'parentReportID']) : reportID;
}
``` 

for completely removing the emoji
https://github.com/tienifr/App/blob/5b37315863b28edcdd5e16b63c29012a222a575b/src/pages/home/report/ContextMenu/ContextMenuActions.js?#L45
```
                shouldShow: (type, reportAction) => type === CONTEXT_MENU_TYPES.REPORT_ACTION && _.has(reportAction, 'message') && !ReportActionUtils.isMessageDeleted(reportAction) && ![CONST.REPORT.ACTIONS.TYPE.TASKCOMPLETED, CONST.REPORT.ACTIONS.TYPE.TASKCANCELLED, CONST.REPORT.ACTIONS.TYPE.TASKREOPENED].includes(reportAction.actionName),


```

**Comment by ArekChr** [comment] 2023-08-18 10:53
I think we can react with emoji on system messages. There is a similar case regarding changing the request date for request money.

<img width="558" alt="image" src="https://github.com/Expensify/App/assets/24796318/ed8712cb-0f76-4601-9af8-c75f3d59d1a7">

**Comment by ArekChr** [comment] 2023-08-18 11:20
Let's address the backend issue directly on the server side rather than attempting a frontend workaround. @adelekennedy, I believe this issue should remain internal. @stitesExpensify, could you review this when you're available?

**Comment by adelekennedy** [comment] 2023-08-18 21:42
works for me - I'm going to remove the external labels and add the engineering auto assigner

**Comment by Julesssss** [comment] 2023-08-20 20:11
_FYI I am OOO this week. Feel free to reassign in the meantime, or I will be back on Monday 28th_

**Comment by adelekennedy** [comment] 2023-08-23 14:41
pending Jules returning

**Comment by Julesssss** [comment] 2023-08-29 09:33
I'm back now, but there's no way I can prioritise this in the next month FYI.

**Comment by Julesssss** [comment] 2023-08-30 12:39
Same as above

**Comment by adelekennedy** [comment] 2023-08-30 15:22
This is a low priority issue, @ArekChr should we try the frontend workaround to get this moving faster? I think the only other option is to deprioritize this until Jules is able to tackle that backend - that means delays in payments. Final alternate solution - this isn't a functional problem, it's a polish, we could clos eto free up engineering time

**Comment by Julesssss** [comment] 2023-08-30 15:32
I think it's best to hold the issue, as the front-end changes (if any) might not become clear until after the backend changes have been made.

**Comment by adelekennedy** [comment] 2023-08-30 15:38
I'm moving this to monthly and removing the bug label so we don't get pings on this

**Comment by paultsimura** [comment] 2023-09-20 14:02
Following [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1692812499109599), is this task not on hold anymore?

**Comment by Julesssss** [comment] 2023-09-21 01:36
I don't think this is occurring anymore: 

<img width="703" alt="Screenshot 2023-09-21 at 09 35 27" src="https://github.com/Expensify/App/assets/10736861/bd83f803-bb03-45ea-b65e-d26908908022">

**Comment by Julesssss** [comment] 2023-09-21 03:03
I guess I'm not convinced we **need** to allow emojis on these actions.

**Comment by Julesssss** [comment] 2023-09-21 03:20
Okay, I see the point. It's going to be very hard to prioritise the backend fix anytime soon though. 

I'd suggest we close it and revisit once we're less focused on wave projects. What do you think @adelekennedy ?

**Comment by adelekennedy** [comment] 2023-09-21 03:53
That works for me - what will remind us to re-open this though?

**Closed** 2023-09-21 03:54 UTC
Labels: Engineering, Monthly, Internal

**Comment by Julesssss** [comment] 2023-09-21 06:13
Good point... I sent you a calendar event for Q1 next year :)
