### ISSUE TITLE
[Awaiting C+ payment] [HOLD for payment 2023-09-15] [$500] [Distance]  App crashes while creating Distance Request money

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26953] opened 2023-09-07 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch app
2. Tap Fab
3. Tap request money
4. Tap Start and select an address
5. Tap Finish and select an address
6. Tap next
7. Select a Workspace
8. Tap Request money

## Expected Result:
The Distance request money IOU must be created and app must not crash

## Actual Result:
When user taps Request money while creating distance IOU, the app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/59577d72-9e61-4abc-a60a-487b09af40dc

[logs.txt](https://github.com/Expensify/App/files/12548660/logs.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010718c221b9fa6a11</li>
        <li>Upwork Job ID: 1699763897270476800</li>
        <li>Last Price Increase: 2023-09-07</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26545543</li>
</ul></li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-07 12:36
I can't reproduce it.

**Comment by mountiny** [comment] 2023-09-07 12:38
I have reproduced on my iphone in staging

**Comment by lanitochka17** [comment] 2023-09-07 12:43
Issue reproducible on Build 1.3.65-3
Iphone 14 Pro Max/ios16.6

https://github.com/Expensify/App/assets/78819774/d5cd8dca-563e-4959-94c2-3fb65b056416

Not repro in Production
Iphone 14 Pro Max/ios16.6

https://github.com/Expensify/App/assets/78819774/14899036-d85b-4dc1-9dcc-f23bf4bc39c0

**Comment by trjExpensify** [comment] 2023-09-07 12:51
I can also repro this on iOS native staging app `1.3.65-3`

**Comment by trjExpensify** [comment] 2023-09-07 13:06
Have we identified the PR from the deploy checklist that's the root cause of this one? Is it this? https://github.com/Expensify/App/pull/26704

**Comment by danieldoglas** [comment] 2023-09-07 13:22
Interesting, why did it work on the testing videos [here](https://github.com/Expensify/App/pull/26704#issuecomment-1707077392)?

**Comment by mountiny** [comment] 2023-09-07 13:24
Seems like @tienifr is the closest to the root cause as its number and not null as mentioned in @akinwale proposal

Can you @tienifr raise the pr now with urgency so we can cp it?

**Comment by danieldoglas** [comment] 2023-09-07 13:26
@tienifr Will working with your proposal remove the receipt image for distances that was added? https://github.com/Expensify/App/pull/26704

**Comment by b4s36t4** [comment] 2023-09-07 13:32
It seems we've touched too much related to images on native devices, I have seen around 3-4 bugs related to this just these 2 days all are reporting just crashing the app. Not even a warning or error. I feel we're lacking something when merging distance request related PRs.

**Comment by danieldoglas** [comment] 2023-09-18 09:14
not overdue, awaiting payment

**Comment by trjExpensify** [comment] 2023-09-18 10:09
Okay, the regression came from an internal PR, so no deductions. Confirming payments due as: 

$750 to @tienifr for the bug fix & #urgency bonus 
$750 to @eVoloshchak for the C+ review & #urgency bonus 

If someone would like to confirm, then I'll send the offers and settle up!

**Comment by trjExpensify** [comment] 2023-09-19 11:13
Bump on the confo guys!

**Comment by danieldoglas** [comment] 2023-09-20 00:37
@trjExpensify sounds good to me.

**Comment by trjExpensify** [comment] 2023-09-20 07:16
Cool, settled up with @tienifr. Awaiting payment confirmation from @eVoloshchak!

**Comment by eVoloshchak** [comment] 2023-09-20 11:00
@trjExpensify, requested the payment via NewDot!

**Comment by trjExpensify** [comment] 2023-09-20 11:04
Perfect, closing!

**Closed by trjExpensify** 2023-09-20 11:04 UTC
Labels: External, Engineering, Weekly, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2023-09-21 10:06
$750 payment for @eVoloshchak approved based on BZ summary.
