### ISSUE TITLE
[$500] Web- Emoji search does not work when searching emoji using letters not from start of word

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28032] opened 2023-09-22 16:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Click on emoji to open emoji picker
4. Search for 'water', search should include 'watermelon' emoji
5. Erase the search term and search for 'melon', now result does not have 'watermelon' emoji
6. Similarly search for 'nut' and observe that app does not display 'doughnut'
7. Try similarly on slack and slack displays the results right

## Expected Result:
App should display emojis in result if we search by terms of emoji which are part of emoji text but emoji text does not begin with that term

## Actual Result:
App does not display emojis in result if we search by terms of emoji which are part of emoji text but emoji text does not begin with that term

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/07e5511c-c99f-41db-a51a-fb88b6df2cb4

https://github.com/Expensify/App/assets/93399543/3a1446e1-afc2-4180-ac0c-cb1a4188fc91

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695224513815769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f1ac8e63f683a64</li>
        <li>Upwork Job ID: 1705252918225764352</li>
        <li>Last Price Increase: 2023-09-22</li>
    </ul>
</details>

**Comment by leeoniya** [comment] 2023-09-23 14:46
also https://github.com/leeoniya/uFuzzy

**Comment by s77rt** [comment] 2023-09-23 21:35
This is not a bug but a feature request. Based on https://github.com/Expensify/App/issues/12189 I think we should just close this one. cc @roryabraham @stitesExpensify

**Comment by leeoniya** [comment] 2023-09-23 23:30
> This is not a bug but a feature request.

i find this reponse to be pretty comical. this is absolutely a bug unless users are expected to know what every one of 2500 emojis starts with, which is ridiculous on the face of it. for "melon" not to return "watermelon" is the definition of broken design, even if it isnt strictly a bug in the actual code.

**Comment by puneetlath** [comment] 2023-09-24 06:05
I agree with @ZhenjaHorbach and @s77rt  that this doesn't meet the definition of a bug. 

There are many ways in which emoji search could be improved, no doubt. I think everyone agrees that some form of fuzzy-search would be better than what we have today. But we live in a world of trade-offs, the biggest trade-off being where to focus our time. We have an effectively infinite amount of work (2200 open issues in the repo) and right now things that are actually broken, performance, and the existing product roadmap are our priority. 

There will come a time when this is worth doing, but I don't think now is that time. I'm going to go ahead and close this issue, but feel free to keep the discussion going if you disagree.

**Closed by puneetlath** 2023-09-24 06:05 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by leeoniya** [comment] 2023-09-24 16:51
> But we live in a world of trade-offs, the biggest trade-off being where to focus our time.

that's a totally reasonable justification for not working on it. moreso than saying this is a feature request.
