### ISSUE TITLE
[$250] Android – Account settings – Date of birth years list flicks if select any year some times

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47384] opened 2024-08-14 06:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.20-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Open Account settings
4. Tap on Profile and open Date of birth
5. Tap on year and select any year
6. Tap on year again and select any year
7. Repeat the last step sometimes

## Expected Result:
Date of birth years list not flicks

## Actual Result:
Date of birth years list flicks

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/837775c3-8cc8-43c8-b126-b5e62d6d1abe

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbcdf988965774c4</li>
        <li>Upwork Job ID: 1823768879808755531</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by IuliiaHerets** [comment] 2024-08-14 06:52
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-14 06:53
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by nkdengineer** [comment] 2024-08-14 10:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date of birth years list flicks

### What is the root cause of that problem?
The problem is the keyboard isn't dismissed before we close the year picker modal then the submit button flicks

https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/components/DatePicker/CalendarPicker/YearPickerModal.tsx#L76
### What changes do you think we should make in order to solve the problem?
We should dismiss the keyboard before we select the year and we also need to wrap the select logic here in `InteractionManager.runAfterInteractions` to ensure the year picker modal is closed after the keyboard is hidden

```
onSelectRow={(option) => {
    Keyboard.dismiss();
    InteractionManager.runAfterInteractions(() => {
        onYearChange?.(option.value);
    });
}}
```
https://github.com/Expensify/App/blob/29fb6bba4cdff75247ee52154359c6925a2390c9/src/components/DatePicker/CalendarPicker/YearPickerModal.tsx#L76

OPTIONAL: Since this bug only happens for the touch device, we can only use `InteractionManager.runAfterInteractions` if `DeviceCapabilities.canUseTouchScreen` is `true` to deny the delay on other platforms

### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-08-14 17:09
I'm not sure I see the flicker but the years do not load - is that what we mean by flicker? 

I don't think we should fix the flickering because it's not consistent and seems very minor but I'll add a C+ to just double-check if they think we should fix the year loading to see if that resolves the flickering. 

https://github.com/user-attachments/assets/97775178-5ec8-4fe8-8aaf-06e050675228

**Comment by Christinadobrzyn** [comment] 2024-08-14 17:10
@getusha can you double-check if you think the flickering = the years not loading or if you're seeing a flicker that's different?

**Comment by Christinadobrzyn** [comment] 2024-08-16 16:33
hey @getusha, can you take a peek at this and give your thoughts - if there's more we need to know from the team or if the flickering makes sense to you? 

If that's true can you review this [proposal](https://github.com/Expensify/App/issues/47384#issuecomment-2288442989)?

**Comment by Christinadobrzyn** [comment] 2024-08-19 21:03
Hi @getusha can you provide an update when you have a moment? TY!

**Comment by Christinadobrzyn** [comment] 2024-08-19 21:03
Hi @getusha can you provide an update when you have a moment? TY!

**Comment by getusha** [comment] 2024-08-20 07:08
>can you double-check if you think the flickering = the years not loading or if you're seeing a flicker that's different?

No, i don't think so

I managed to notice the flicker (the list kind of distorts for a fraction of a second and returns back) when closing the page, but it's pretty hard to notice. we can close this issue.

https://github.com/user-attachments/assets/52cbddac-ca12-4b5e-9224-fa6a646b5e36

**Comment by nkdengineer** [comment] 2024-08-20 07:22
@getusha The bug here you should select a year, and then you can see the keyboard is always hidden after we go back to the previous page


https://github.com/user-attachments/assets/3ff8e979-b1cf-479b-9c65-62f1886d70ce

**Comment by getusha** [comment] 2024-08-20 07:44
>and then you can see the keyboard is always hidden after we go back to the previous page

It's not what the issue description states but are you sating we need to keep the keyboard open when we go back to that page?

**Comment by nkdengineer** [comment] 2024-08-20 07:54
>Tap on year and select any year
Tap on year again and select any year

@getusha It's mentioned here

**Comment by getusha** [comment] 2024-08-20 07:56
>@getusha It's mentioned here

That's part of the steps to reproduce the flicker, am i missing something?

**Comment by nkdengineer** [comment] 2024-08-20 14:24
> That's part of the steps to reproduce the flicker, am i missing something?

<img width="495" alt="Screenshot 2024-08-20 at 21 23 59" src="https://github.com/user-attachments/assets/23bd5ddb-22bc-4894-9b87-b1fb5968e6c2">

@getusha Yes this is the reproduce steps, you also can see it at the end of the video in OP.

**Comment by Christinadobrzyn** [comment] 2024-08-20 22:25
Update for Melvin - I think we're reviewing proposals. @getusha @nkdengineer let me know if I can help with anything!

**Comment by getusha** [comment] 2024-08-22 02:57
>@getusha Yes this is the reproduce steps, you also can see it at the end of the video in OP.

And the issue is a barely noticeable flicker, right?

**Comment by nkdengineer** [comment] 2024-08-22 03:38
> And the issue is a barely noticeable flicker, right?

We can see the keyboard is not closed before we close the year list modal which makes the flicker bug.

**Comment by getusha** [comment] 2024-08-25 21:16
>We can see the keyboard is not closed before we close the year list modal which makes the flicker bug.

Yes, but it's about the significance. it doesn't seem to affect any flow.

**Comment by nkdengineer** [comment] 2024-08-26 03:03
> Yes, but it's about the significance. it doesn't seem to affect any flow.

@getusha Yes, it's a UI issue. We also use the same solution in other places like [here](https://github.com/Expensify/App/blob/f58439cfb116abd338dae880088a26725794108e/src/pages/iou/request/step/IOURequestStepCurrency.tsx#L60) to prevent this UI issue.

**Comment by Christinadobrzyn** [comment] 2024-08-28 16:07
Hi @getusha just checking in on this to see if we've decided on a proposal or can you provide an update?

**Comment by getusha** [comment] 2024-08-28 16:09
@Christinadobrzyn I feel like this is not worth fixing, i don't see how this affects the flow. it's just a minor UI flicker.

**Closed** 2024-08-28 18:37 UTC
Labels: External, Daily, Help Wanted, Bug
