### ISSUE TITLE
[HOLD for payment 2023-06-13] [$1000] Magic link fails to sign in on a fresh session

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19214] opened 2023-05-18 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Start login process to generate a magic link email
2. Open the magic link in the email in a fresh session (e.g. in incognito), or copy/paste it into an incognito window
3. Click the "sign in here" link
4. See a sign-in error

## Expected Result: 
You should be able to sign in successfully

## Actual Result: 
Magic code expired message shows

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/35e59bfa-bfe6-4827-9b17-6eacf2b40778

<img width="960" alt="1" src="https://github.com/Expensify/App/assets/43996225/431307ce-2dd3-4344-8b65-e2eecee25b00">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @jjcoffee
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684250997259549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012148c4a8a95d1ed1</li>
        <li>Upwork Job ID: 1660495514646405120</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-18 21:04
Proposal from @jjcoffee 
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The sign in link doesn't work if the magic link is opened in a fresh session or on a different device.
### What is the root cause of that problem?
In the ValidateLoginPage component we check first if the current user has the necessary permissions to use passwordless logins (via the betas prop) here:
https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L66-L69
However, when we load the magic link in a fresh session we don't have any value for the betas prop as the user is not initialised or validated (this normally happens via BeginSignIn, which returns the available betas for the requested user).
This means we always assume the user doesn't have passwordless login permissions and so we always call ValidateLogin instead, which still requires a password to complete the login.
The "sign in here" link calls signInWithValidateCode directly:
https://github.com/Expensify/App/blob/main/src/components/ValidateCode/ValidateCodeModal.js#L42
But we've already used the code for ValidateLogin so it's been expired on the BE.
### What changes do you think we should make in order to solve the problem?
I'm unsure if any users don't have access to passwordless logins anymore, but assuming we still need the check, we can check that the credentials.login is available before checking for permissions (as fresh sessions won't have this value).
So we move this line to the top:
https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L73
and update this:
https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L66-L69
to:
if (login && !Permissions.canUsePasswordlessLogins(this.props.betas)) {
We also need to update this line:
https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L74
To allow for an additional AUTO_AUTH_STATE:
if (!login && isSignedIn && (cachedAutoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN || cachedAutoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN)) {
### What alternative solutions did you explore? (Optional)
We could also remove the "sign in here" text here:
https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/components/ValidateCode/ValidateCodeModal.js#L58-L63
in the case of not having the passwordless login permission. Or we could change the link so that it navigates to the password entry page.
These options seem a bit pointless as I assume we've either already or are nearly there with rolling out passwordless to everyone.

**Comment by adelekennedy** [comment] 2023-05-22 03:47
@jliexpensify I got assigned this after I was ooo already 😬 I'll stay assigned to pick it back up on Monday!

**Comment by jliexpensify** [comment] 2023-05-22 03:49
All good @adelekennedy - I can take this one.

**Comment by jliexpensify** [comment] 2023-05-22 03:56
I've tested on v1.3.16-6 and I can't log in after pasting the link in an incognito window. Video here:

Uploading 2023-05-22_13-53-21.mp4…

**Comment by jjcoffee** [comment] 2023-05-22 10:25
Reposting my proposal from above, updated slightly as the behaviour has changed a bit in the meantime. Now you get redirected to the password-based login instead of the magic code displaying with a "sign in here" link.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The sign in link doesn't work if the magic link is opened in a fresh session or on a different device.

### What is the root cause of that problem?
In the `ValidateLoginPage` component we check first if the current user has the necessary permissions to use passwordless logins (via the `betas` prop) here:

https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L66-L69

However, when we load the magic link in a fresh session we don't have any value for the `betas` prop as the user is not initialised or validated (this normally happens via `BeginSignIn`, which returns the available `betas` for the requested user). 

This means we always assume the user doesn't have passwordless login permissions and so we always call `ValidateLogin` instead, which still requires a password to complete the login.

The "sign in here" link calls `signInWithValidateCode` directly:

https://github.com/Expensify/App/blob/main/src/components/ValidateCode/ValidateCodeModal.js#L42

But we've already used the code for `ValidateLogin` so it's been expired on the BE.

### What changes do you think we should make in order to solve the problem?
I'm unsure if the passwordless rollout is fully complete by now, but assuming we still need the check for passwordless permissions, we can check that the `credentials.login` is available before checking for permissions (as fresh sessions won't have this value).

So we move this line to the top:

https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L73

and update this:

https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L66-L69

to:

`if (login && !Permissions.canUsePasswordlessLogins(this.props.betas)) {`

We also need to update this line:

https://github.com/Expensify/App/blob/07f17683fff5fee79fdb836aedb3d633d03726e3/src/pages/ValidateLoginPage/index.website.js#L74

To allow for an additional `AUTO_AUTH_STATE`:

`if (!login && isSignedIn && (cachedAutoAuthState === CONST.AUTO_AUTH_STATE.SIGNING_IN || cachedAutoAuthState === CONST.AUTO_AUTH_STATE.JUST_SIGNED_IN)) {`

As this is the auth state that is returned after the `SigninUserWithLink` API request completes.

I'm unsure if the BE will run a permissions check for the sign in call, but if it does return any error we could handle that and perform the original `ValidateLogin` call for users without the passwordless login permission.

### What alternative solutions did you explore? (Optional)
If there is an API call we could use that allows to check for a user's validity and permissions using only the account ID (like `BeginSignIn` but without an email), we could run that on page load if `credentials.login` is not available.

**Comment by abdulrahuman5196** [comment] 2023-05-22 18:21
@jjcoffee Seems there are answers in your slack thread. Kindly update the proposal if required and update here(even if no update is required on proposal) so that we can review it.

**Comment by jjcoffee** [comment] 2023-05-23 09:55
@abdulrahuman5196 I have updated my [proposal](https://github.com/Expensify/App/issues/19214#issuecomment-1556965831) for now, based on the feedback from Slack. I would ideally would need access to a user account without passwordless login permission so that I can test fully what happens (I've also asked for this on slack). Will update once that's done!

**Comment by jjcoffee** [comment] 2023-05-23 18:22
@abdulrahuman5196 Okay the conclusion from [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1684852286616699?thread_ts=1684834376.409219&cid=C01GTK53T8Q) seems to be that we can assume no more passwords going forwards, so I don't think we need to deal with someone without passwordless permission opening a magic link (verification link in their case) in an incognito tab (as would be the case here). I've updated my [proposal](https://github.com/Expensify/App/issues/19214#issuecomment-1556965831) to this effect.

**Comment by abdulrahuman5196** [comment] 2023-05-24 16:40
@hayata-suenaga  This proposal needs a dive deep and testing to review it. Will try to complete in one day time.

**Comment by hayata-suenaga** [comment] 2023-05-26 22:26
kindly dumping @abdulrahuman5196

**Comment by abdulrahuman5196** [comment] 2023-05-27 10:34
@jjcoffee 's proposal here https://github.com/Expensify/App/issues/19214#issuecomment-1556965831 is good. I tested exclusively and seems to be working fine.

🎀👀🎀
C+ Reviewed

cc: @hayata-suenaga

**Comment by hayata-suenaga** [comment] 2023-05-29 23:17
assigning @jjcoffee

**Comment by jliexpensify** [comment] 2023-05-30 00:34
Invited @jjcoffee and @abdulrahuman5196 .

**Comment by jjcoffee** [comment] 2023-05-30 09:40
Accepted, thanks! 

PR coming today.

**Comment by jjcoffee** [comment] 2023-05-30 14:37
@abdulrahuman5196 [PR](https://github.com/Expensify/App/pull/19819) is ready for review. Cheers!

**Comment by jliexpensify** [comment] 2023-06-08 04:38
Thanks @abdulrahuman5196 . @hayata-suenaga all good with that checklist and regression test?

**Comment by hayata-suenaga** [comment] 2023-06-12 01:49
@jliexpensify yes all look good to me! 👍

**Comment by jjcoffee** [comment] 2023-06-12 11:20
@jliexpensify I wonder if this one might still be due the timeliness bonus as I think it was mainly the delay getting the engineer review that pushed it over the 3WD. Timeline was:

- [assigned](https://github.com/Expensify/App/issues/19214#issuecomment-1567590449) 30/5 01:17 
- [PR](https://github.com/Expensify/App/pull/19819) raised 30/5 16:39 
- C+ [approved](https://github.com/Expensify/App/pull/19819#pullrequestreview-1456176332) 1/6 21:32 (**3WD**)
- Engineer [approved](https://github.com/Expensify/App/pull/19819#pullrequestreview-1451469386) - 4/6 15:10
- [Merged](https://github.com/Expensify/App/pull/19819#event-9438325973) 5/6 23:04

Thanks for considering!

**Comment by jliexpensify** [comment] 2023-06-13 07:02
@jjcoffee my understanding is that we pay a bonus based on the PR submission to merge timeline. So there's about a 5-6 day period for this one, which means no bonus is paid out. 

Going back in the PR, I notice that @abdulrahuman5196 did ping Hayata for a review but since there are a few revisions, I can't pinpoint the length of time it took Hayata to review.

@hayata-suenaga since you're the assigned engineer, what are your thoughts? Do you think you were delayed in reviewing this? Were you OOO during that time that caused a delay? Thanks!

**Comment by hayata-suenaga** [comment] 2023-06-13 20:23
@abdulrahuman5196 thank you for your info. I agree with you. The comment edit was not a blocker.

it's your final call @jliexpensify 🙇

**Comment by jliexpensify** [comment] 2023-06-13 22:48
![image](https://github.com/Expensify/App/assets/30815269/220784fc-1472-4bb2-9290-9908d60a4180)

Awesome, thanks for that context, it's really helpful - and I agree, since it's just outside of the bonus period and it'd could be merged without resolving Hayata's suggestion, I'm happy to pay out the bonus.

- @jjcoffee : $1500
- @abdulrahuman5196 : $1500

**Comment by jliexpensify** [comment] 2023-06-14 03:33
Ok everyone hired, once accepted I'll pay!

**Comment by abdulrahuman5196** [comment] 2023-06-14 04:35
@jliexpensify accepted the offer

**Comment by jjcoffee** [comment] 2023-06-14 08:51
@jliexpensify Thanks for considering the extra context, much appreciated! Offer accepted too.

**Comment by jliexpensify** [comment] 2023-06-14 22:51
Paid, thanks gents!

**Closed by jliexpensify** 2023-06-14 22:51 UTC
Labels: External, Daily, Awaiting Payment, Bug
