### ISSUE TITLE
Subscription size - Offline indicator show ups on RHP on web layout

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43795] opened 2024-06-15 17:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.84-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/43328
## Action Performed:
1. Go to staging.new.expensify.com/settings/subscription/subscription-size
2. Go offline

## Expected Result:
Offline indicator will not show up on RHP on web layout

## Actual Result:
Offline indicator shows up on RHP on web layout

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0700c7ff-dc2c-4ad3-9731-bcc4debdd5e3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-15 17:07
@arosiclair  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by neonbhai** [comment] 2024-06-15 17:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Subscription size - Offline indicator show ups on RHP on web layout

### What is the root cause of that problem?
We have not disabled the offine indicator in wide screens for the ScreenWrapper here:
https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/settings/Subscription/SubscriptionSize/index.tsx#L46

### What changes do you think we should make in order to solve the problem?
We should pass the prop `shouldShowOfflineIndicatorInWideScreen` as `false` [here](https://github.com/Expensify/App/blob/75c104bfe009ef937bcd129a35bb5a2e52f4339d/src/pages/settings/Subscription/SubscriptionSize/index.tsx#L46-L52)

```jsx
<ScreenWrapper
    ...
    shouldShowOfflineIndicatorInWideScreen={false}
>
```

**Comment by neonbhai** [comment] 2024-06-15 18:16
@cretadn22 proposal was updated before your comment 😄 

<Details><Summary>Timestamp 1</Summary>
<img width="587" alt="Screenshot 2024-06-15 at 11 39 41 PM" src="https://github.com/Expensify/App/assets/64629613/8a1abd67-19b7-409a-94ce-e956585f2b92">
y>

</Details>

<Details><Summary>Timestamp 2</Summary>
<img width="587" alt="Screenshot 2024-06-15 at 11 40 05 PM" src="https://github.com/Expensify/App/assets/64629613/a766f39f-fb91-4df9-b64e-20a808342bf5">

</Details>

Please submit complete proposals! you have missed the first field. You may also leave out the reminders at the end of the proposal template, that's just for you to remember.

**Comment by mountiny** [comment] 2024-06-16 21:42
@bernhardoj @tylerkaraszewski @thesahindia this is coming from https://github.com/Expensify/App/pull/43328

demoting as this feature is not available to normal users yet

**Comment by mountiny** [comment] 2024-06-16 21:43
cc @MitchExpensify @fabioh8010

**Comment by bernhardoj** [comment] 2024-06-17 03:24
@mountiny https://github.com/Expensify/App/pull/43328 doesn't cause this issue.

**Comment by arosiclair** [comment] 2024-06-17 15:16
I think this should be fixed by [this PR](https://github.com/Expensify/App/pull/43740)?

**Comment by mountiny** [comment] 2024-06-17 15:25
Thanks for noting! I assumed from the issue description that it was that pr

@bernhardoj can you confirm if your pr that Andrew linked resolves this issue?

**Comment by bernhardoj** [comment] 2024-06-17 15:33
Yes, it does resolve the issue because `shouldShowOfflineIndicatorInWideScreen` now won't have an effect in RHP, but I think we can still accept the proposal here to remove the `shouldShowOfflineIndicatorInWideScreen` from the subscription size RHP page (because it's not needed there) and to shows the offline indicator that is missing for the subscription settings central pane screen (SubscriptionSettingsPage.tsx).

**Closed** 2024-06-19 23:32 UTC
Labels: Engineering, Daily
