### ISSUE TITLE
[$1000] can’t check off a task when it is “done”

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19298] opened 2023-05-19 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Assign a task to user A 
2. Log in as user B and "Mark as done" for the assigned task
3. Login as user A and check off the task 
## Expected Result:
Able to check off
## Actual Result:
Not able to check off
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/b3bbcb33-8959-4151-8ac3-411aee3b999c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @joaniew 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684311858049629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b784d341e4d6cdf</li>
        <li>Upwork Job ID: 1660594272412274688</li>
        <li>Last Price Increase: 2023-05-22</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-05-22 10:31
Reproduced

**Comment by kushu7** [comment] 2023-05-22 12:04
Its a BE issue. when we reopen task
action `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${parentReportID}` throwing error. thats why action is not getting updated.
<img width="940" alt="Screenshot 2023-05-22 at 5 32 03 PM" src="https://github.com/Expensify/App/assets/31707153/47193325-be0c-4608-a88a-b8fc7423cc3b">

**Comment by Santhosh-Sellavel** [comment] 2023-05-22 22:16
I'm unassigning due to limited availability. Can you a assign new C+ here by re-applying the external label here, thanks!

Also @robertjchen Not sure but seems like a backend issue from a couple of comments above. Please check that before moving forward

cc: @bfitzexpensify

**Comment by bfitzexpensify** [comment] 2023-05-24 11:29
@robertjchen before I assign a new C+, do you want to take a look at https://github.com/Expensify/App/issues/19298#issuecomment-1557383554 and confirm if this is a back-end or front-end issue?

**Comment by bfitzexpensify** [comment] 2023-05-29 07:26
@aimane-chnaif @robertjchen thoughts on @hoangzinh's [comment](https://github.com/Expensify/App/issues/19298#issuecomment-1561290330)?

**Comment by bfitzexpensify** [comment] 2023-05-31 07:50
bump @aimane-chnaif @robertjchen

**Comment by robertjchen** [comment] 2023-05-31 12:34
I think the core issue around inconsistent state should be resolved rather than the FE workaround. The backend should do as described here https://github.com/Expensify/App/issues/19298#issuecomment-1557383554 🤔

**Comment by bfitzexpensify** [comment] 2023-06-01 11:20
Cool, I agree with the general idea of solving the core issue rather than using a workaround. Let's keep this `internal`

**Comment by robertjchen** [comment] 2023-06-05 13:34
I think I found the source of the issue on the backend. Draft PR linked and testing out the fix 👍

**Comment by robertjchen** [comment] 2023-06-06 17:10
Ran into some problems testing locally, going to revisit tomorrow to see if I can get it to work, hopefully will have the PR ready by EOW.

**Comment by robertjchen** [comment] 2023-06-09 12:51
Still testing things out locally

**Comment by robertjchen** [comment] 2023-06-13 16:48
Top priority today 👀

**Comment by robertjchen** [comment] 2023-06-14 08:36
Fix confirmed, working on finalizing the PR/screenshots, etc. 👍

**Comment by robertjchen** [comment] 2023-06-19 06:56
The fix is currently on staging

**Comment by bfitzexpensify** [comment] 2023-06-28 08:24
@robertjchen looks like this is on prod now (https://github.com/Expensify/Web-Expensify/pull/37714#issuecomment-1601887889) - we good to close this out?

**Comment by robertjchen** [comment] 2023-06-28 08:50
Yep, we're all set here!

**Closed by robertjchen** 2023-06-28 08:50 UTC
Labels: Reviewing, Daily, Internal, Bug
