### ISSUE TITLE
[$250] Android - Netsuite - Under invoice item, " created one for me " option is auto selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46714] opened 2024-08-02 12:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4798370
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Have netsuite connected workspace
1. Launch app
2. Tap profile icon -- workspaces -- workspace
3. Tap accounting - export- invoice item

## Expected Result:
There shouldn't be any item checked under invoice item

## Actual Result:
Under invoice item, " created one for me " option is auto selected and displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/1d0f4c71-86d6-473a-b75b-342a3dffbed4

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdb946f7e8c06815</li>
        <li>Upwork Job ID: 1823117077048429994</li>
        <li>Last Price Increase: 2024-08-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by lanitochka17** [comment] 2024-08-02 12:27
We think that this bug might be related to #vip-vsp

**Comment by lanitochka17** [comment] 2024-08-02 12:27
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by alexpensify** [comment] 2024-08-05 23:17
I was assigned on Friday and will review it this week.

**Comment by alexpensify** [comment] 2024-08-08 22:00
No update yet

**Comment by alexpensify** [comment] 2024-08-12 21:59
Waiting for proposals here

**Comment by jayeshmangwani** [comment] 2024-08-13 13:45
I believe the default value was added intentionally, but let me get a second opinion from @shubham1206agra since they were the ones who added the default value for the invoice item in this PR https://github.com/Expensify/App/pull/46201

**Comment by jayeshmangwani** [comment] 2024-08-16 09:04
@alexpensify Default option is intentional, not a bug. 
We can close this issue. Please refer to the https://github.com/Expensify/App/issues/46714#issuecomment-2286391158

**Comment by alexpensify** [comment] 2024-08-16 15:08
Thank you for the feedback, closing!

**Closed by alexpensify** 2024-08-16 15:08 UTC
Labels: External, Daily, Help Wanted, Bug
