### ISSUE TITLE
Web - Blank page is displayed when assigning a task to secondary contact

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22055] opened 2023-07-02 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Click on FAB
2. Go to Assing task
3. Write a title and click next
4. Go to Assignee and enter a Secondary contact of other users. Notice that the secondary contact is auto-selected on Share Somewhere.
5. Click on confirm task.

## Expected Result:
The task is assigned to the primary(Default) contact.

## Actual Result:
A blank page is displayed.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ae3cdab6-1a1e-4f9e-acae-a5dc929bfe8c

https://github.com/Expensify/App/assets/93399543/777e3e63-ffd7-403a-927c-17e1661a7129

**Expensify/Expensify Issue URL:**
**Issue reported by:** @daveSeife
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688186078166629

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017262927021ec2cb4</li>
        <li>Upwork Job ID: 1678420616163860480</li>
        <li>Last Price Increase: 2023-08-09</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2023-07-04 15:28
Getting to this tomorrow

**Comment by muttmuure** [comment] 2023-07-10 15:06
OK I'm in

**Comment by muttmuure** [comment] 2023-07-10 15:06
reproduced

**Comment by muttmuure** [comment] 2023-07-10 15:07
It's possible that this has an internal component but let's see what C+ says

**Comment by muttmuure** [comment] 2023-07-13 11:04
Doubled price

**Comment by kmwamasali** [comment] 2023-07-13 12:09
@muttmuure do I need a high traffic account to reproduce this.
When I attempt to replicate, I get a no contact found.
I also noticed  I don't have the create new room option on clicking the FAB.
Kindly advise on how to proceed with testing, video attached
[Screencast from 13-07-23 14:33:22.webm](https://github.com/Expensify/App/assets/13502241/3b0bc571-f00a-43ac-9f1d-312c8a0759a6)

**Comment by syedsaqib12** [comment] 2023-07-13 13:11
Please re-state the problem that we are trying to solve in this issue.

>  Wrong assigning issue, you have to assign task new contact method person but task add to default email person.

What is the root cause of that problem?

> The root of the problem is in the assigning task file which is wrong.

What changes do you think we should make in order to solve the problem?

> First I will debug the code then review the code or function to assigning task, most probably change the final value of assign task email is to updated not the default one.

  
What alternative solutions did you explore? (Optional)**

**Comment by syedsaqib12** [comment] 2023-07-13 13:18
Contributor details
Your Expensify account email: snsaqib777@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016644659663cd2561

**Comment by ShogunFire** [comment] 2023-07-13 14:24
I don't reproduce

**Comment by snwork89** [comment] 2023-07-13 16:12
While assinging task, passing secondary contact method giving error from BE as per below ss , i think first need to check BE regarding this issue.
![image](https://github.com/Expensify/App/assets/100206710/9400b35f-020b-47c8-b476-cbac9b8c678c)

![image](https://github.com/Expensify/App/assets/100206710/404eae60-e47e-40ca-8f90-e7f2dcd5ae19)

**Comment by ShogunFire** [comment] 2023-07-13 20:21
Ah sorry I was talking about assigning to my own secondary contact, is this a different issue ?

**Comment by ShogunFire** [comment] 2023-07-13 20:29
And yes I agree we need BE changes

**Comment by muttmuure** [comment] 2023-07-26 06:54
Catching up from ooo

**Comment by Parshvi16** [comment] 2023-07-31 14:28
is this not external anymore? @muttmuure 
why is upwork price doubled if this is not external anymore?

**Comment by muttmuure** [comment] 2023-07-31 14:33
It's internal because there are BE changes

**Comment by muttmuure** [comment] 2023-07-31 14:34
Maybe I've missed a rule about price doubling when it's internal

**Comment by muttmuure** [comment] 2023-08-09 19:28
posted here: https://expensify.slack.com/archives/C01GTK53T8Q/p1691609320827829

**Comment by thienlnam** [comment] 2023-08-09 19:35
> Maybe I've missed a rule about price doubling when it's internal

We don't double or do any payouts (except reporter) if it's an internal issue

Also, this bug looks like it might have the same RCA as https://github.com/Expensify/Expensify/issues/294203, so let's hold on that and see if we can still reproduce after

**Comment by muttmuure** [comment] 2023-08-22 17:06
Held

**Comment by thienlnam** [comment] 2023-08-22 23:14
Linked issue is resolved - let's see if this is still reproducible and if we need to handle or not

**Comment by muttmuure** [comment] 2023-08-31 17:31
Will test this when I get time

**Comment by muttmuure** [comment] 2023-09-19 11:47
Tested and this isn't reproducible for me anymore

**Closed by muttmuure** 2023-09-19 11:47 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
