### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500] Preferences -  Shows blue color in Bottom Safearea when going offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26425] opened 2023-08-31 19:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go offline
2. Go to settings -> Go to preferences
3. See bottom Safearea

## Expected Result:
 It should be same as other Safearea color

## Actual Result:
 Shows blue color for bottom Safearea

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/dba99477-593e-4fcb-93f8-447d594ad4d0

https://github.com/Expensify/App/assets/78819774/62e764e1-7f36-45a9-9c60-c7fcdd9aedfc

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @DinalJivani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692734918701659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe0ede226690a3a8</li>
        <li>Upwork Job ID: 1697674109513048064</li>
        <li>Last Price Increase: 2023-09-15</li>
    </ul>
</details>

**Comment by CortneyOfstad** [comment] 2023-09-01 18:13
Was able to recreate very easily, so going to get eyes on this.

**Comment by studentofcoding** [comment] 2023-09-01 20:09
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Preferences - Shows blue color in Bottom Safearea when going offline

## What is the root cause of that problem?

The Root Cause of this problem is on the Long Mobile screen (e.g. iPhone 13), the `OfflineIndicator` is not really at the bottom, thus the blue background from `IllustratedHeaderPageLayout` appears

## What changes do you think we should make in order to solve the problem?

What we need are 

1. Add a Long Mobile Screen as `isSmallScreenWidthLongHeight` on 

https://github.com/Expensify/App/blob/a6a05722631a016ec502611f663b8d1d7ae38d3e/src/components/withWindowDimensions.js#L67-L70

2. Add styles of `offlineIndicatorMobileLong` on styles.js
```
offlineIndicatorMobileLong: {
        paddingLeft: 25,
        paddingTop: 5,
        paddingBottom: 25,
        marginBottom: -25,
},
```

3. Use `isSmallScreenWidthLongHeight` on [OfflineIndicator](https://github.com/Expensify/App/blob/a6a05722631a016ec502611f663b8d1d7ae38d3e/src/components/OfflineIndicator.js#L41) component condition and use `offlineIndicatorMobileLong` if `isSmallScreenWidthLongHeight` true

## Result

* **After**
<img width="469" alt="Screenshot 2023-09-02 at 03 06 22" src="https://github.com/Expensify/App/assets/20473526/5d703527-e70d-42d0-9617-a562e152b484">

* **Before**
<img width="469" alt="Screenshot 2023-09-02 at 03 02 13" src="https://github.com/Expensify/App/assets/20473526/3d509098-d7f5-4e9d-bac5-48ff3684e172">


## What alternative solutions did you explore? (Optional)

None

cc: @sobitneupane @CortneyOfstad

**Comment by studentofcoding** [comment] 2023-09-01 20:25
Contributor details
Your Expensify account email: [yonathanevan@gmail.com](mailto:yonathanevan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca6ccb72fa9cc678

**Comment by studentofcoding** [comment] 2023-09-01 20:26
Contributor details
Your Expensify account email: yonathanevan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca6ccb72fa9cc678

**Comment by CortneyOfstad** [comment] 2023-09-05 15:03
@sobitneupane Thoughts on the proposal above? TIA!

**Comment by sobitneupane** [comment] 2023-09-06 10:39
Thanks for the proposal @studentofcoding 

This issue was probably caused by change introduced by [this PR](https://github.com/Expensify/App/pull/21852). I am quite sceptical about the use of negative margin. Is there any other way to avoid the blue background?

**Comment by studentofcoding** [comment] 2023-09-06 11:37
Let me dig into more alternatives, follow up if we can achieve this without a negative margin @sobitneupane


**Additional note:** Apparently we have this problem all across `IllustratedHeaderPageLayout` pages (such as WorkSpaceList, Teacher), and with the solution above, we're fixing it also

| Page | Before | After |
| ---- | ---- | ---- |
| Teacher | ![teacher](https://github.com/Expensify/App/assets/20473526/de53a97c-2273-4645-8a58-44b1818bb349) | ![teacher_after](https://github.com/Expensify/App/assets/20473526/e636f0ff-7295-425b-b7c5-e48d5da90e1b) |
| Workspace | ![workspace](https://github.com/Expensify/App/assets/20473526/e724feda-c771-4e14-9fd5-93f74315b80f) | ![workspace_after](https://github.com/Expensify/App/assets/20473526/bc8312ac-4700-4904-b5ee-a343a0f8e62b) |

**Comment by studentofcoding** [comment] 2023-09-06 13:21
Oke, so on more digging, I'm pretty sure that [the pr](https://github.com/Expensify/App/pull/21852) did not introduce the problem as It didn't change any global style (related to `OfflineIndicator`, `IllustratedHeaderPageLayout`, or `SafeArea`)
<img width="1552" alt="Screenshot 2023-09-06 at 19 47 10" src="https://github.com/Expensify/App/assets/20473526/41c9c0f3-59fc-467e-9173-e64fe0ae4273">

After looking at the same problem across `IllustratedHeaderPageLayout` like my comment [above](https://github.com/Expensify/App/issues/26425#issuecomment-1708175683), this validates as a Global Styling problem specifically on `OfflineIndicator` not layering correctly on `SafeArea` specifically on iPhone bigger than iPhoneX size. as we have here

https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/components/SafeArea/index.ios.js#L6-L15 

* **1st Alternative** is to manage it via SafeArea on ios

But this will add additional variables and checks as right now it only manages iPhoneX size via `styles.iPhoneXSafeArea` in which I don't see any problem with it

https://github.com/Expensify/App/blob/57b76067cd3d7b59e84c4a387d11ad33e6a97d05/src/styles/styles.js#L3180-L3183

* **2nd Alternative** that is a simpler way to handle this is
Change `offlineIndicatorMobile` styles to 
```
offlineIndicatorMobile: {
        paddingLeft: 20,
        paddingTop: 5,
        paddingBottom: 30,
        marginBottom: 0 - 25,
},
```

* **3rd Alternative** to handle it via introducing `isSmallScreenWidthLongHeight` variable on `withWindowDimensions.js` and making the styles of `offlineMobile` changes based on that with absolute position, but It'll change several files (styles.js, variables.ts, OfflineIndicator.js, and withWindowDimensions.js).

Based on the option above, I prefer option 2 as it's only managed on `offlineIndicatorMobile` which already on `SE & iPhone14 Pro screen`, thus limit the potential of regression later on

What do you think @sobitneupane

**Comment by studentofcoding** [comment] 2023-09-07 05:35
## Optimal Solution

I found the optimal approach for this, We essentially using 3rd Alternative above, but we add the condition on `ScreenWrapper` `<SafeAreaConsumer>` to add the paddingBottom:0 instead of passing the paddingBottom

Here is the complete solution of it:

1.   On `src/styles/variables.ts` we add `mobileResponsiveWidthBreakpointLongHeight: 800,` after `mobileResponsiveWidthBreakpoint: 800,` to handle a longer screen (iPhone 14).

 
https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/styles/variables.ts#L78

2.  On `src/components/withWindowDimensions.js` we then add `const isSmallScreenWidthLongHeight = isSmallScreenWidth && windowDimension.windowHeight > variables.mobileResponsiveWidthBreakpointLongHeight;` to make it true on longer mobile screen

https://github.com/Expensify/App/blob/d60c13e7437ec9d367a51ed75c39d8214599a09d/src/components/withWindowDimensions.js#L65-L70

Add `isSmallScreenWidthLongHeight: PropTypes.bool.isRequired,` into `windowDimensionsPropTypes`

Also, include `isSmallScreenWidthLongHeight` into the `<WindowDimensionsContext.Provider`
```
<WindowDimensionsContext.Provider
      value={{
             windowHeight: windowDimension.windowHeight + getWindowHeightAdjustment(insets),
             windowWidth: windowDimension.windowWidth,
             isExtraSmallScreenWidth,
             isSmallScreenWidth,
             isSmallScreenWidthLongHeight,
             isMediumScreenWidth,
             isLargeScreenWidth,
     }}
>
     {props.children}
</WindowDimensionsContext.Provider>
```

3.  Next on `src/components/ScreenWrapper/index.js` we add the condition of this to make the `paddingBottom:0` when `isSmallScreenWidthLongHeight` true
```
// Check if it's on Small Screen width but with Long Height (like iPhone 14) & is offline
if (this.props.isSmallScreenWidthLongHeight && this.props.network.isOffline) {
    paddingStyle.paddingBottom = this.props.isSmallScreenWidthLongHeight ? 0 : paddingBottom;
}
```

4.  On `src/styles/styles.js` Add styles of `offlineIndicatorMobileLongHeight` to handle `isSmallScreenWidthLongHeight` styles later on `OfflineIndicator`
```
const propTypes = {
    /** Information about the network */
    network: networkPropTypes.isRequired,

    /** Optional styles for container element that will override the default styling for the offline indicator */
    // eslint-disable-next-line react/forbid-prop-types
    containerStyles: PropTypes.arrayOf(PropTypes.object),

    /** Is the window width narrow, like on a mobile device */
    isSmallScreenWidth: PropTypes.bool.isRequired,

    /** Is the window Height long, like on a mobile device newest iPhone  */
    isSmallScreenWidthLongHeight: PropTypes.bool.isRequired,

    ...withLocalizePropTypes,
};

offlineIndicatorMobileLongHeight: {
        paddingLeft: 20,
        paddingTop: 5,
        paddingBottom: 25,
},
```

5.  Lastly `src/components/OfflineIndicator.js` add the condition to `setStyles` to handle `isSmallScreenWidthLongHeight` as well, init `isSmallScreenWidthLongHeight: PropTypes.bool.isRequired,` into `propTypes`, and pass it into `View` after ` props.isSmallScreenWidth`
```
const setStyles = (containerStyles, isSmallScreenWidth, isSmallScreenWidthLongHeight) => {
    if (containerStyles.length) {
        return containerStyles;
    }
    if (isSmallScreenWidthLongHeight) {
        return styles.offlineIndicatorMobileLongHeight;
    }
    return isSmallScreenWidth ? styles.offlineIndicatorMobile : styles.offlineIndicator;
};

return (
        <View style={[setStyles(props.containerStyles, props.isSmallScreenWidth, props.isSmallScreenWidthLongHeight), styles.flexRow, styles.alignItemsCenter, ...StyleUtils.parseStyleAsArray(props.style)]}>
            <Icon
                src={Expensicons.OfflineCloud}
                width={variables.iconSizeSmall}
                height={variables.iconSizeSmall}
            />
            <Text style={[styles.ml3, styles.chatItemComposeSecondaryRowSubText]}>{props.translate('common.youAppearToBeOffline')}</Text>
        </View>
    );
```

With these 5 changes, we will get rid of Blue Color in bottom safe @sobitneupane 

## Result
https://github.com/Expensify/App/assets/20473526/8aa450e9-486e-4c59-9e2f-bae0b665072e

**Comment by CortneyOfstad** [comment] 2023-09-08 15:45
@sobitneupane any thoughts ^^^ — TIA!

**Comment by studentofcoding** [comment] 2023-09-11 04:02
How is it @sobitneupane, if all align, I can push the PR today 😁

**Comment by sobitneupane** [comment] 2023-09-13 07:31
Thanks for the update @studentofcoding. But I don't think we are using paddingBottom in SafeArea for OfflineIndicator only. It might have other use cases as well.

**Comment by studentofcoding** [comment] 2023-09-13 07:40
Yes @sobitneupane  we use paddingBottom on ScreenWrapper, that's why the Root Cause are on paddingBottom specifically on ** IllustratedHeaderPageLayout** and with above solution I've tested and it work as expected with no side effect on another screen

But if we want to limit the coverage we can simple use negative marginBottom like I've shared [here](https://github.com/Expensify/App/issues/26425#issuecomment-1703268801)

**Comment by CortneyOfstad** [comment] 2023-09-15 13:32
@sobitneupane Any thoughts on the comment [here](https://github.com/Expensify/App/issues/26425#issuecomment-1717108712)?

**Comment by sobitneupane** [comment] 2023-09-18 08:16
Thanks for the update.

[Initial Proposal ](https://github.com/Expensify/App/issues/26425#issuecomment-1703268801) from @studentofcoding looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by studentofcoding** [comment] 2023-09-18 09:41
Thanks for assigning @nkuoch @sobitneupane 

I already applied for the job @CortneyOfstad https://www.upwork.com/ab/proposals/1703705673352904705?success

And the PR will be ready today ;)

**Comment by DinalJivani** [comment] 2023-09-18 10:01
@nkuoch @sobitneupane 
I didn't received Upwork invite automatically, Can you please send me the offer?

**Comment by studentofcoding** [comment] 2023-09-18 14:23
The PR is created @nkuoch @sobitneupane, please kindly check, thanks!

**Comment by studentofcoding** [comment] 2023-09-19 07:04
Also, I've applied to Upwork but, still not accepted, could you help @CortneyOfstad ?
<img width="1552" alt="Screenshot 2023-09-19 at 14 03 27" src="https://github.com/Expensify/App/assets/20473526/accd104e-6606-4d35-9094-febc1835dc22">

**Comment by studentofcoding** [comment] 2023-09-19 14:56
Hey @nkuoch @sobitneupane, please kindly check the PR, thanks!

**Comment by CortneyOfstad** [comment] 2023-09-19 15:08
@studentofcoding hired in Upwork! 👍

**Comment by DinalJivani** [comment] 2023-09-20 09:19
> @nkuoch @sobitneupane I didn't received Upwork invite automatically, Can you please send me the offer?
cc: @CortneyOfstad

**Comment by CortneyOfstad** [comment] 2023-10-03 14:40
@DinalJivani and @studentofcoding — please let me know as soon as you accept the proposals/contracts in Upwork so I can get those paid to you ASAP. Thanks for your patience, as I was OoO yesterday 👍

**Comment by studentofcoding** [comment] 2023-10-03 14:45
> @DinalJivani and @studentofcoding — please let me know as soon as you accept the proposals/contracts in Upwork so I can get those paid to you ASAP. Thanks for your patience, as I was OoO yesterday 👍 

For me I already accepted the old Contract and I think we can proceed on there @CortneyOfstad 

Also it's on 50% urgency bonuses

**Comment by DinalJivani** [comment] 2023-10-03 14:50
> @DinalJivani and @studentofcoding — please let me know as soon as you accept the proposals/contracts in Upwork so I can get those paid to you ASAP. Thanks for your patience, as I was OoO yesterday 👍

@CortneyOfstad accepted the offer but
Reporting bonus will be 250 instead of 50.

**Comment by CortneyOfstad** [comment] 2023-10-03 15:09
@DinalJivani At the time the reporting took place, our new pricing system was installed, which indicates that it is $50 instead of $250 👍

**Comment by CortneyOfstad** [comment] 2023-10-03 15:13
@studentofcoding payment completed and no worries — we apply the bonus at the time of payment 👍

**Comment by CortneyOfstad** [comment] 2023-10-03 15:14
@DinalJivani payment completed as well 👍

**Comment by CortneyOfstad** [comment] 2023-10-03 15:14
@sobitneupane any updates on the checklist? TIA!

**Comment by DinalJivani** [comment] 2023-10-03 15:17
> @DinalJivani At the time the reporting took place, our new pricing system was installed, which indicates that it is $50 instead of $250 👍

Yes, sorry I just noticed issue was opened on Sept 1st. 
please ignore above message. Thanks 
@CortneyOfstad

**Comment by DinalJivani** [comment] 2023-10-04 08:31
@CortneyOfstad 
According to [this message](https://expensify.slack.com/archives/C01GTK53T8Q/p1695107975438049?thread_ts=1694444733.848299&cid=C01GTK53T8Q) I think we have to check the Slack reporting date not GH date.



![272511269-29c8c4c2-11fe-49a9-bf6a-fa919918f2e3](https://github.com/Expensify/App/assets/58871336/a29ec826-2342-4dfb-837d-b4f0c46258ae)

**Comment by CortneyOfstad** [comment] 2023-10-04 14:48
@DinalJivani Checking with the team on this — will follow up as soon as I hear back 👍

**Comment by CortneyOfstad** [comment] 2023-10-04 16:34
Confirmed with the team that the Slack date would work here, so I sent a proposal for the additional funds in Upwork. Please let me know as soon as you accept — thank you!

**Comment by DinalJivani** [comment] 2023-10-04 16:37
Offer Accepted @CortneyOfstad 
Thanks for quick action

**Comment by CortneyOfstad** [comment] 2023-10-04 16:43
@sobitneupane any update on the checklist above? Thanks!

**Comment by sobitneupane** [comment] 2023-10-05 14:07
Sorry for the delay. I am running quite behind schedule. I will work on checklist by the weekend.

**Comment by sobitneupane** [comment] 2023-10-09 06:32
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/21852
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/21852#issuecomment-1752414019
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This should have caught in offline tests in the associated PR.
> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2023-10-09 06:33
**Regression Test Proposal**

1. Go offline
2. Go to settings -> Go to preferences
3. Verify that offline indicator is shown at the bottom and blue color padding is not present at the bottom.

Do we agree 👍 or 👎

**Comment by sobitneupane** [comment] 2023-10-09 08:47
https://github.com/Expensify/App/issues/26425#issuecomment-1733252425

Requested payment on newDot.

**Comment by JmillsExpensify** [comment] 2023-10-09 17:52
$750 payment approved for @sobitneupane based on this [BZ summary](https://github.com/Expensify/App/issues/26425#issuecomment-1733252425).

**Comment by CortneyOfstad** [comment] 2023-10-11 13:10
@nkuoch any thoughts on the regression test proposal [here](https://github.com/Expensify/App/issues/26425#issuecomment-1752416191)?

**Comment by CortneyOfstad** [comment] 2023-10-11 13:12
Perfect! I'll get that GH created now 👍

**Comment by CortneyOfstad** [comment] 2023-10-11 13:17
Checklist updated above with the regression test link. Closing! Thanks all!

**Closed by CortneyOfstad** 2023-10-11 13:17 UTC
Labels: External, Daily, Awaiting Payment, Bug
