### ISSUE TITLE
[$500] Chat – New message button appears when create IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38848] opened 2024-03-22 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4444284
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to account with a long conversation history
4. Send a message
5. Create IOU

## Expected Result:
New message button not appears on the top of the page when create IOU

## Actual Result:
New message button appears on the top of the page when create IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2e0b010a-6e58-4a3f-8192-12e9ad61964a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0133b550ad31059d52</li>
        <li>Upwork Job ID: 1772371228780400640</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-03-22 22:40
We think that this bug might be related to vip-vsp

**Comment by Pujan92** [comment] 2024-03-23 11:13
I am not sure but RequestMoney API onyx response for the report seems sending old time for `lastVisibleActionCreated` which could be the issue in below check.

https://github.com/Expensify/App/blob/665a8adfdb3239667270b5d23c12287894763d7d/src/pages/home/report/ReportActionsList.tsx#L191

https://github.com/Expensify/App/assets/14358475/67e8510b-f93b-4a27-8bbe-424a15166093

**Comment by yuwenmemon** [comment] 2024-03-25 19:58
Unable to reproduce on the latest `main`

**Comment by yuwenmemon** [comment] 2024-03-25 21:04
I can see this on staging with a different chat though...

**Comment by yuwenmemon** [comment] 2024-03-25 21:12
**However,** the New Message button is dissapearing after about 1 second or so - I can reproduce this pretty consistently so I'm not going to let this block the deploy and rather make this an External Daily Issue.

**Comment by cleverjam** [comment] 2024-03-26 01:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "New Messages" button is incorrectly displayed when creating an IOU.

### What is the root cause of that problem?

The check for `hasNewestReportAction` looks at the `lastVisibleActionCreated` property of the report to determine if the sorted actions include the most recent one. 

In other words, there is a date discrepancy between the report and the sorted actions and the following expression: `sortedReportActions[0].created) === report.lastVisibleActionCreated` never evaluates to `true` when an IOU is created.

### What changes do you think we should make in order to solve the problem?


1. Updating the "optimistic created report action" to include the report `lastVisibleActionCreated` data, instead of the relying on the current default argument: 
`function buildOptimisticCreatedReportAction(emailCreatingAction: string, created = DateUtils.getDBTime())`
2. Updating the `buildOptimisticMoneyRequestEntities` to use IOU's `lastVisibleActionCreated` if available.
3. Update the rest of the optimistic data to match this created time.

### What alternative solutions did you explore? (Optional)

I propose figuring out 

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by cleverjam** [comment] 2024-03-26 01:21
Contributor details
Your Expensify account email: lizjaime@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01da820ecc0ea8ff6f

**Comment by cleverjam** [comment] 2024-03-26 01:34
## Proposal
[Updated](https://github.com/Expensify/App/issues/38848?notification_referrer_id=NT_kwDOAMIe07M5OTY2MzM4Njk1OjEyNzIxODc1#issuecomment-2019213759)

**Comment by rushatgabhane** [comment] 2024-03-26 20:48
@cleverjam what would happen when a comment is deleted?

**Comment by cleverjam** [comment] 2024-03-26 22:10
@rushatgabhane the report's `lastVisibleActionCreated` property is already updated when a comment is deleted, this flow should not be affected by the change. 

This is the main reason I like this approach, vs creating a new report property, such as: `lastVisibleActionId` or something similar.

The date is already supported by all report actions and no further refactor is needed if we keep the current expectation of having the action's created date match the iou report's last action created value.

**Comment by cleverjam** [comment] 2024-04-02 21:33
@rushatgabhane do you have any other questions or concerns regarding my proposal?

**Comment by rushatgabhane** [comment] 2024-04-03 17:57
@yuwenmemon i like @cleverjam's [proposal](https://github.com/Expensify/App/issues/38848#issuecomment-2019213759)

**Comment by cleverjam** [comment] 2024-04-03 23:40
I should have a PR ready before the end of the week

**Comment by cleverjam** [comment] 2024-04-29 21:59
@puneetlath The PR was created: https://github.com/Expensify/App/pull/39665

There is some discrepancy I been discussing with @rushatgabhane in the PR, we think there might be some BE changes needed.

**Comment by lanitochka17** [comment] 2024-08-01 16:36
Issue is still reproducible on the latest build  9.0.15-5

https://github.com/user-attachments/assets/33b29e04-5bb6-45c0-87c7-7719355ba134

**Comment by cleverjam** [comment] 2024-08-06 19:02
I still have PR #39665 open but it has been so long I am not sure if I should close it and let someone else take a stab at this...

**Comment by puneetlath** [comment] 2024-08-08 18:42
@yuwenmemon what are your thoughts on how to move forward?

**Comment by yuwenmemon** [comment] 2024-08-14 20:38
Yeah this might be a more internal issue based on that PR. So let's close that PR and then switch this over to internal.

**Comment by puneetlath** [comment] 2024-10-06 13:42
@yuwenmemon given that we closed #vip-split and aren't focused on the IOU flow right now, I think we should just close this out for now. What do you think?

**Comment by yuwenmemon** [comment] 2024-10-07 20:35
Yeah sounds good

**Closed by yuwenmemon** 2024-10-07 20:35 UTC
Labels: Engineering, Monthly, Internal, Bug
