### ISSUE TITLE
ON HOLD FOR #36655 [$500] iphone 13 Pro - Workspace name is cutoff at the top

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36064] opened 2024-02-07 19:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 
**Reproducible in staging?:** happening with iphone 13 Pro 
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @AndrewGable 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707240198084589

## Action Performed:
1. Go to workspace
2. click on wrench to go to settings
## Expected Result:
Workspace name should appear without any cutoff
## Actual Result:
Workspace name is cutoff at the top
## Workaround:
visual
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![IMG_5652](https://github.com/Expensify/App/assets/38435837/39ff7109-e009-4234-bd67-873e7461a87a)

<img src=“https://github.com/Expensify/App/assets/38435837/39ff7109-e009-4234-bd67-873e7461a87a” width=“40%” height=“40%“>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190df84185c63613f</li>
        <li>Upwork Job ID: 1757800156429877248</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2024-02-14 16:12
I do not have an iphone 13 so i can't repro.

**Comment by zanyrenney** [comment] 2024-02-14 16:13
but adding external as Andrew tested/ confirmed this in chat.

**Comment by brandonhenry** [comment] 2024-02-14 20:42
Hello everyone! Hoping I can help out here as I saw this one on a job board.

# Proposed Solutions

**1. Adjust CSS Styling**: Modify styling for the workspace name container to ensure visually proper padding and margin settings. This will prevent the workspace name from being cut off at the top. For example:

```
.workspace-name-container {
    padding-top: 20px; /* Adjust this value based on actual testing */
    margin-top: 0;
}
```

**2. Safe Area View**: Utilize React Native's SafeAreaView component to ensure that the workspace name is rendered within the safe area boundaries of the iPhone 13 Pro's screen. This is particularly important for devices with notches or rounded corners.

```
import { SafeAreaView } from 'react-native';

const WorkspaceSettings = () => (
    <SafeAreaView>
        {/* Other components */}
        <Text className="workspace-name-container">{workspaceName}</Text>
        {/* Other components */}
    </SafeAreaView>
);
```

**Comment by brandonhenry** [comment] 2024-02-15 02:34
Contributor details
Your Expensify account email: itsbhenry@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01568e6425f3546d5f

**Comment by brandonhenry** [comment] 2024-02-15 02:36
Hello everyone! Hoping I can help out here as I saw this one on a job board.

# Proposed Solutions

**1. Adjust CSS Styling**: Modify styling for the workspace name container to ensure visually proper padding and margin settings. This will prevent the workspace name from being cut off at the top. For example:

```
.workspace-name-container {
    padding-top: 20px; /* Adjust this value based on actual testing */
    margin-top: 0;
}
```

**2. Safe Area View**: Utilize React Native's SafeAreaView component to ensure that the workspace name is rendered within the safe area boundaries of the iPhone 13 Pro's screen. This is particularly important for devices with notches or rounded corners.

```
import { SafeAreaView } from 'react-native';

const WorkspaceSettings = () => (
    <SafeAreaView>
        {/* Other components */}
        <Text className="workspace-name-container">{workspaceName}</Text>
        {/* Other components */}
    </SafeAreaView>
);
```

**Comment by zanyrenney** [comment] 2024-02-16 15:31
@parasharrajat what do you think of the proposal above?

**Comment by brandonhenry** [comment] 2024-02-19 08:56
@parasharrajat 
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The workspace name is cut off at the top when viewed in the settings view of the workspace on an iPhone 13 Pro. This issue affects the user experience by not displaying the full name of the workspace, which can be confusing and aesthetically unpleasing.

### What is the root cause of that problem?
The root cause of this problem is related to how the text inside of the Breadbrumbs component is styled. By default, it has a line-height of 23px. This is super close to it's font-size (22px). 

![image](https://github.com/Expensify/App/assets/15656774/b4e82800-0fa3-4b88-b9b0-72182a250c89)

`lineHeight` can render differently across different devices and platforms due to variations in font rendering and device pixel ratios. This can potentially lead to layout issues like text being cut off or misaligned - especially when the `line-height` is really close to `font-size`


### What changes do you think we should make in order to solve the problem?

The lineHeight should typically be greater than the fontSize to ensure adequate spacing for descenders and ascenders in the text, which are the parts of letters that extend below the baseline (like 'p', 'q', 'y') or above the x-height (like 'd', 'h', 'l').

1. Import the variables from @styles/variables.
2. Calculate the lineHeight based on the font size and desired ratio.
3. Apply the calculated lineHeight to the text styles.


Example:

```
const lineHeightRatio = 1.3; // factor that is safe line height area
const primaryFontSize = variables.fontSizeNormal; // used by https://github.com/Expensify/App/blob/5d45f0f6c86e97d4ae58ac167b6c162a610b817c/src/components/Text.tsx
const primaryLineHeight = primaryFontSize * lineHeightRatio;

// add extra styling to header text so line-height is properly calculated

{primaryBreadcrumb.type === CONST.BREADCRUMB_TYPE.ROOT ? (
    <View style={styles.breadcrumbLogo}>
        <Header
            title={
                <ImageSVG
                    contentFit="contain"
                    src={LogoComponent}
                    fill={theme.text}
                    width={variables.lhnLogoWidth}
                    height={variables.lhnLogoHeight}
                />
            }
            shouldShowEnvironmentBadge
        />
    </View>
) : (
    <Text
        numberOfLines={1}
        style={[
            styles.flexShrink1,
            styles.breadcrumb,
            styles.breadcrumbStrong,
            {lineHeight: primaryLineHeight}, // Apply calculated lineHeight
        ]}
    >
        {primaryBreadcrumb.text}
    </Text>
)}

```

**Original / Culprit**

https://github.com/Expensify/App/blob/d2259b5b869afb7495018e0e3e93040e70698239/src/components/Breadcrumbs.tsx#L58

**Comment by zanyrenney** [comment] 2024-02-21 15:27
bump @parasharrajat please review.

**Comment by agent3bood** [comment] 2024-02-27 07:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

iphone 13 Pro - Workspace name is cutoff at the top

### What is the root cause of that problem?

The breadcrumb component applies two styles to the text, `styles.breadcrumb, styles.breadcrumbStrong`, the second one sets the `fontSize` without setting the `fontHeight`.

https://github.com/Expensify/App/blob/e3e0b2db46a1d8fa2097ba8cf51b045b690d5c26/src/components/Breadcrumbs.tsx#L60

### What changes do you think we should make in order to solve the problem?

Add `fontHeight` to `styles.breadcrumbStrong`

### What alternative solutions did you explore? (Optional)

**Comment by agent3bood** [comment] 2024-02-27 13:31
@parasharrajat  sorry for the typo, is is `lineHeight` as shown in the code snippet.

**Comment by lanitochka17** [comment] 2024-03-01 17:09
Hello 
We found a similar issue  in Android and with emoji. Is this the same problem or a new one?
Thank you

![Screenshot_2024-03-01-21-59-41-177_com expensify chat-edit](https://github.com/Expensify/App/assets/78819774/c58f115c-605a-4ef8-9dd8-a83b504ad45e)

![viber_image_2024-03-01_12-01-54-336 (1)](https://github.com/Expensify/App/assets/78819774/f8c27706-2a9d-425e-b572-b31ed91a919b)

**Comment by zanyrenney** [comment] 2024-03-11 11:44
Still On HOLD for: https://github.com/Expensify/App/pull/36655 it is open, not yet merged and deployed.

**Comment by AndrewGable** [comment] 2024-03-11 18:11
It works for me on latest TestFlight 👍

**Closed by AndrewGable** 2024-03-11 18:11 UTC
Labels: External, Engineering, Daily, Needs Reproduction, Help Wanted, Bug
