### ISSUE TITLE
CRITICAL: [Actionable Whispers] [$250] Not found page on selecting categories from actionable whisper

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#40308] opened 2024-04-16 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Currently on dev
**Reproducible in staging?:** N/A
**Reproducible in production?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

Note: This occurs as part of a feature from this [PR](https://github.com/Expensify/App/pull/38709)

Break down in numbered steps
1. Create a workspace and add categories to it
2. Create a tracked expense to the self-DM
3. From the actionable whisper, categorize it

## Expected Result:
You should see a list of categories

## Actual Result:
Sometimes, you will see a not found page 

We're guessing this is because the categories for the workspace are not loaded yet. This may require a BE fix to load categories at other locations

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e41c6321097b3ff7</li>
        <li>Upwork Job ID: 1780290981003022336</li>
        <li>Last Price Increase: 2024-04-16</li>
    </ul>
</details>

**Comment by thienlnam** [comment] 2024-04-16 21:43
@shubham1206agra Do you happen to have consistent reproduction steps for this one?

**Comment by tgolen** [comment] 2024-04-16 22:01
I am not able to reproduce this one at all. I even went so far as deleting the `policyCategories_` collections out of Onyx and trying to categorize the transaction again. If the categories are not in Onyx, then the code makes an API request to `OpenDraftWorkspaceRequest` which returns all the categories.

Looking at the code, these are the cases where the not-found page could be happening:
- The transaction itself isn't found
- The report isn't found
- All the categories are disabled on the workspace

**Comment by tgolen** [comment] 2024-04-17 14:24
I'll leave this open for another day to wait and hear back from @shubham1206agra to see if they can still reproduce it. If not, I'll close this out.

**Comment by tgolen** [comment] 2024-04-17 14:43
Can you please upload a video of you reproducing it? Not that I don't believe you, I just want to be sure that we're both doing the same thing.

**Comment by tgolen** [comment] 2024-04-17 15:27
OK, thanks. That's really strange then. I even added a 6x slowdown to my CPU to ensure I was seeing the screen transition animation and I still couldn't get it to appear. Since you're able to reproduce it, can you debug it and submit a proposal here to fix it? 

If it does require a backend fix, I can help at that point.

**Comment by rushatgabhane** [comment] 2024-04-18 16:43
let me try too

**Comment by quinthar** [comment] 2024-04-21 22:53
Hm, so @shubham1206agra is still able to reproduce, but nobody else?

**Comment by kadiealexander** [comment] 2024-04-22 05:20
I'm not able to reproduce this on the latest version (v1.4.63-16)

**Comment by tgolen** [comment] 2024-04-22 15:59
There must be some very specific way to reproduce it that the rest of us aren't able to trigger. I think this issue can be closed until there are more clear reproduction steps. Note: the reproduction steps should start with a brand new account in order to ensure that everyone is starting from the same place.

**Closed by tgolen** 2024-04-22 15:59 UTC
Labels: Daily, Internal, Bug
