### ISSUE TITLE
[$500] mWeb/Android - Compose box -While editing comment adding emoji moves cursor to left

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30690] opened 2023-11-01 12:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Send a message
4. Long press on the message sent and select edit comment
5. Tap emoji picker
6. Select an emoji

## Expected Result:
While editing comment adding emoji must not move the cursor to the left.

## Actual Result:
While editing comment adding emoji moves cursor to the left.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/71629ff8-fa88-451c-b92c-02f17a63c881

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01941393c4215c6da9</li>
        <li>Upwork Job ID: 1719695805389557760</li>
        <li>Last Price Increase: 2023-11-01</li>
    </ul>
</details>

**Comment by rakshitjain13** [comment] 2023-11-01 14:42
Dupe of https://github.com/Expensify/App/issues/28563

**Comment by sophiepintoraetz** [comment] 2023-11-01 20:11
Agreed.

**Closed by sophiepintoraetz** 2023-11-01 20:11 UTC
Labels: External, Daily, Help Wanted, Bug
