### ISSUE TITLE
[HOLD for payment 2022-10-05] [$250] Keyboard type is wrong for email address - Reported by @gadhiyamanan

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10889] opened 2022-09-08 04:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > profile> add email address
2. Tap on email address
3. Check keyboard

## Expected Result:
it should be email-address pad

## Actual Result:
open default keyboard

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android
- Mobile Web

**Version Number:** 1.1.96-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://user-images.githubusercontent.com/43995119/189037381-83e2e217-c901-43ce-906d-01920127b064.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661349488843219

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by gadhiyamanan** [comment] 2022-09-08 05:06
**Proposal**

Replace `getEmailKeyboardType()` with `undefined`

https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/pages/settings/AddSecondaryLoginPage.js#L125-L126

**Comment by dhairyasenjaliya** [comment] 2022-09-08 05:11
**Proposal**

- We need to add a new keyboard type as `email-address` in the below file

<img width="850" alt="Screenshot 2022-09-08 at 10 39 36 AM" src="https://user-images.githubusercontent.com/47522946/189039234-d6fa7730-f9cb-4042-aaa8-0b661f094e7a.png">

https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/CONST.js#L453-L458

- Replace type in the email field with `CONST.KEYBOARD_TYPE.EMAIL_ADDRESS` instead of undefined  

https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/pages/settings/AddSecondaryLoginPage.js#L125-L126

**Results**

<img src=https://user-images.githubusercontent.com/47522946/189039393-3b11f42c-a25a-4aab-a9c3-01ce77bbfc83.png  width=50%>

**Comment by varshamb** [comment] 2022-09-08 09:14
### Proposal
Replace `getEmailKeyboardType()`.

https://github.com/Expensify/App/blob/14a5fc39c69347692bbe2efe19e07297075b6455/src/pages/settings/AddSecondaryLoginPage.js#L125-L126

**Comment by Puneet-here** [comment] 2022-09-08 09:22
### Proposal

We need use getEmailKeyboardType() instead of undefined here

https://github.com/Expensify/App/blob/14a5fc39c69347692bbe2efe19e07297075b6455/src/pages/settings/AddSecondaryLoginPage.js#L126

We still have to keep it conditional because this component is also getting used for phone number

**Comment by thesahindia** [comment] 2022-09-08 09:33
I think we should close this issue for now as this page is going to get refactored and also this isn't something really important. If the issue stays after the refactor we can reopen.

cc @Luke9389 (Saw your comment about the same on a different issue)

**Comment by gadhiyamanan** [comment] 2022-09-08 10:21
> change keyboard type in below file from default to email-address(because of mWeb) then it will also resolve wrong keyboardtype in login page for mWeb

still need to solve the wrong keyboardtype in login page for mWeb as i mentioned [above](https://github.com/Expensify/App/issues/10889#issuecomment-1240225807)

**Comment by Luke9389** [comment] 2022-09-08 11:02
@thesahindia the refactors we're doing are only effecting the API endpoints. This looks like a purely front end change, so we can move forward with it. 

@dhairyasenjaliya, I notice that you've left the 👎 reaction on another contributor's proposal. Please note that this does not influence our decision whatsoever. Also, it's odd to 👎 a proposal that's the same as your own. What is the purpose of that?

**Comment by dhairyasenjaliya** [comment] 2022-09-08 11:16
hello @Luke9389 the simple reason behind was  

- The first proposal of the @gadhiyamanan  was to Replace getEmailKeyboardType() with undefined

<img width="1361" alt="Screenshot 2022-09-08 at 10 50 27 AM" src="https://user-images.githubusercontent.com/47522946/189043806-88876af0-0ffe-4645-92ee-a4afb30eadbc.png">

- I was having the better idea to replace it with an actual email-address keyboard here https://github.com/Expensify/App/issues/10889#issuecomment-1240228567

- But after my proposal, @gadhiyamanan just edited their proposal same as my proposal 
<img width="1042" alt="Screenshot 2022-09-08 at 10 50 33 AM" src="https://user-images.githubusercontent.com/47522946/189044177-41c8204e-4ab2-42a1-9c0f-487410d0792a.png">

**Comment by gadhiyamanan** [comment] 2022-09-08 12:06
@dhairyasenjaliya after found that in mweb it's not working properly so i am trying to update proposal meanwhile you have just posted a proposal. I think that's why there is confusion.

**Comment by Luke9389** [comment] 2022-09-08 12:09
I see. Thank you for the explanation @dhairyasenjaliya. 

@gadhiyamanan, in the future please post a new proposal instead of editing an existing one. For this issue we will consider @dhairyasenjaliya's proposal as occurring before yours.

**Comment by gadhiyamanan** [comment] 2022-09-08 12:17
@Luke9389 thank you for suggestions, i proposed two solution and the second one is different and it was first proposed by me.

@dhairyasenjaliya apologies for the confusion

**Comment by dhairyasenjaliya** [comment] 2022-09-08 15:44
@Luke9389 thank you for checking out, and also can we have any reviewer assigned here seems like no one assigned here

**Comment by Luke9389** [comment] 2022-09-13 16:46
@dhairyasenjaliya the reason there isn't a CM or C+ member assigned is that this issue didn't have the `External` label yet.

@dhairyasenjaliya @gadhiyamanan Both of you should note that if an issue does not have an `External` label, there is no guarantee it will be posted as an available job (so you may be wasting your time submitting proposals).

**Comment by Christinadobrzyn** [comment] 2022-09-14 04:57
Job posted in Upwork 

Internal posting - https://www.upwork.com/ab/applicants/1569913059586658304/job-details
External posting - https://www.upwork.com/jobs/~018c98f3d998843f9f

**Comment by mananjadhav** [comment] 2022-09-14 07:45
Got assigned today. Went through the whole conversation. Thanks @Luke9389 for clearing up the conflict.

@dhairyasenjaliya's proposal [here](https://github.com/Expensify/App/issues/10889#issuecomment-1240228567) looks good. 

I would personally recommend not to change anything on the login page as of now. With SecondaryLogin page, we already know the type before hand so it makes sense to update it here.

**Comment by varshamb** [comment] 2022-09-14 09:32
@mananjadhav Have gone through my proposal also.

**Comment by mananjadhav** [comment] 2022-09-14 09:45
@varshamb I did go through your proposal [here](https://github.com/Expensify/App/issues/10889#issuecomment-1240448525). Problem with `getEmailKeyboardType` function right now is that it sends `default`. 

But ideally we would want to use `email-address`, so that `@` and `.` shows up on the keyboard. [Here's](https://lefkowitz.me/visual-guide-to-react-native-textinput-keyboardtype-options/) the visual representation between different keyboard types for everyone's reference.

Hence, I did not go ahead with your proposal.

**Comment by Luke9389** [comment] 2022-09-14 22:18
Ok @dhairyasenjaliya you've got the 🟢 Green Light 🟢 to make a PR. Thanks!

**Comment by dhairyasenjaliya** [comment] 2022-09-15 05:34
> @dhairyasenjaliya the reason there isn't a CM or C+ member assigned is that this issue didn't have the `External` label yet.
> 
> @dhairyasenjaliya @gadhiyamanan Both of you should note that if an issue does not have an `External` label, there is no guarantee it will be posted as an available job (so you may be wasting your time submitting proposals).


TBH @Luke9389 even I'm not a fan of posting a proposal before it gets an `external` tag, but from the past couple of weeks I noticed a trend whereby an issue receives a proposal without an `External` label on it

**Comment by dhairyasenjaliya** [comment] 2022-09-15 05:34
> Ok @dhairyasenjaliya you've got the 🟢 Green Light 🟢 to make a PR. Thanks!

Alright PR comming soon

**Comment by dhairyasenjaliya** [comment] 2022-09-16 07:09
hello @mananjadhav PR ready for review

**Comment by Christinadobrzyn** [comment] 2022-09-16 07:47
Sorry for the delay on hiring!

Hired @mananjadhav as the C+
Hired @dhairyasenjaliya as the contributor
Hired @gadhiyamanan as the reporter

Internal job for my tracking/payment here - https://www.upwork.com/ab/applicants/1569913059586658304/job-details

**Comment by mananjadhav** [comment] 2022-09-16 07:56
> hello @mananjadhav PR ready for review

I'll close this by today/tomorrow.

**Comment by Luke9389** [comment] 2022-09-26 21:31
What's the latest y'all?

**Comment by mananjadhav** [comment] 2022-09-27 02:26
@Luke9389 We just merged the PR few hours back.

**Comment by Luke9389** [comment] 2022-09-27 20:53
Oh ha 😄 thanks!

**Comment by Christinadobrzyn** [comment] 2022-10-05 07:28
Looks like no regressions on the [PR](https://github.com/Expensify/App/pull/11046) so paying this out and closing. 

$250 @mananjadhav as the C+
$250 @dhairyasenjaliya as the contributor
$250 @gadhiyamanan as the reporter

**Closed by Christinadobrzyn** 2022-10-05 07:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment
