### ISSUE TITLE
[HOLD for payment 2024-07-24]  Search - Grouped expenses show User submits to User instead of to Workspace

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45013] opened 2024-07-08 20:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-4
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify app.
2. Create a new workspace.
3. Go to workspace chat.
4. Submit two expenses.
5. Go to Search.
6. Go to Shared (important).

## Expected Result:
The grouped expenses will show that user submits to the workspace.

## Actual Result:
The grouped expenses shows that user submits to the same user.
On web layout, it displays correctly, which is user submits to the workspace.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/487d3cb7-b702-4783-ad54-6f9807b429fa

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by izarutskaya** [comment] 2024-07-08 20:53
@alexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-08 20:54
We think this issue might be related to the #collect project.

**Comment by izarutskaya** [comment] 2024-07-08 20:54
Production
![IMG_4735](https://github.com/Expensify/App/assets/115492554/316d7c7c-0643-4b41-be94-d8132a1fa7a4)

**Comment by AndrewGable** [comment] 2024-07-08 21:00
@luacmartins - Just wanted to confirm that the expected steps are correct on this one: we want to show the user or workspace being submitted to on the grouped UI?

**Comment by luacmartins** [comment] 2024-07-08 22:10
We should be showing the workspace as submitted to

**Comment by luacmartins** [comment] 2024-07-08 22:13
I'm pretty sure this comes from [this PR](https://github.com/Expensify/App/pull/44658). @c3024 @brunovjk could you please take a look?

**Comment by c3024** [comment] 2024-07-09 11:22
`transactionItem` has a `reportType` field to check if the transaction is an expense. `reportItem` does not have it. I think ideally backend should send `reportType` for `reportItem` as well.

We can just use type of one of the transactions' `reportType` also to check if it is an expense report without any changes on backend.

**Comment by AndrewGable** [comment] 2024-07-09 14:35
@c3024 @luacmartins - Should we revert the PR and make the changes to the backend and update the original PR?

**Comment by luacmartins** [comment] 2024-07-09 18:30
I have some draft PRs up, I'll finish them once I'm done with a call. Meanwhile, we can demote this to NAB since part of the fix is in Auth.

**Comment by luacmartins** [comment] 2024-07-15 16:37
@alexpensify for clarify, there's no payment due on this issue. It'll be handled in https://github.com/Expensify/App/issues/44093

**Comment by alexpensify** [comment] 2024-07-15 18:38
Noted, thank you for that update!

**Comment by brunovjk** [comment] 2024-07-22 12:05
Hello @luacmartins :D I was about to fill out the `BugZero Checklist`, I'm confused, does this issue count as a regression for this [PR](https://github.com/Expensify/App/pull/44658)? Thanks.

**Comment by luacmartins** [comment] 2024-07-22 18:21
I don't think so, they had different root causes.

**Comment by brunovjk** [comment] 2024-07-24 15:16
* [x]  [@brunovjk] The PR that introduced the bug has been identified. Link to the PR: **N/A**
* [x]  [@brunovjk] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
* [x]  [@brunovjk] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
* [x]  [@brunovjk] Determine if we should create a regression test for this bug. **Yes**
* [x]  [@brunovjk] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. * Since _there's no payment due on this issue. It'll be handled in [44093](https://github.com/Expensify/App/issues/44093)_, the regression test can [be the same](https://github.com/Expensify/App/issues/44093#issuecomment-2245005463).

**Comment by alexpensify** [comment] 2024-07-24 23:39
Based on this update: https://github.com/Expensify/App/issues/45013#issuecomment-2228931662, there is no required payment action. Closing!

**Closed by alexpensify** 2024-07-24 23:39 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
