### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] Use AND logical operator instead of OR when searching with multiple strings

### ISSUE THREAD

**Issue by sakluger** [Expensify/App#21627] opened 2023-06-26 19:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed

1. Log into NewDot in any platform
2. Click the magnifying glass at the top of the LHN to search
3. Type the names of two users (i.e. "sasha daniel") and observe the search results

## Expected Result:

If I search "sasha daniel", I expect to see a list of chats where both Sasha and Daniel are members.

## Actual Result:

Currently, if I search "sasha daniel", search returns a list of any chats with either Sasha or Daniel.

## Workaround:
N/A

## Urgency & context

The current behavior is making it impossible for Expensify Guides (setup specialists) to find specific `#admins` rooms based on the policy name, which makes it way harder fro them to do their jobs in NewDot.

This is one of the changes that was planned in our "Online Search on Expensify Chat" project ([design doc](https://docs.google.com/document/d/1gvRkOXO4HoIl2QRJCo9lYvO_EasmTZpU4mc0-WR5JPg/edit)). Given the urgency around Guides, we're fixing it now separately from that project.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a5aa75c9c3dbcd67</li>
        <li>Upwork Job ID: 1673419822590115840</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-06-26 19:57
cc @danieldoglas @vitHoracek since you two are leading the main NewDot Search project.

**Comment by francoisl** [comment] 2023-06-29 18:58
The search logic is not on the backend yet, we can make this external.

**Comment by mountiny** [comment] 2023-06-29 19:57
@francoisl we will be implementing this change as part of the Search project, that is on hold for Comment linking. Not sure if we should implement this now separately cc @gedu

**Comment by francoisl** [comment] 2023-06-29 20:32
My understanding from the issue's description is that we don't want to wait until Comment Linking and the Search project are implemented — for this specific change

> This is one of the changes that was planned in our "Online Search on Expensify Chat" project ([design doc](https://docs.google.com/document/d/1gvRkOXO4HoIl2QRJCo9lYvO_EasmTZpU4mc0-WR5JPg/edit)). Given the urgency around Guides, we're fixing it now separately from that project.

Is that right @sakluger?

**Comment by mountiny** [comment] 2023-06-29 21:02
Ah thanks for raising, i have just checked this on my phone without furher context. In that case, i think we should give this to @gedu as he already planned the work in the design doc.

**Comment by francoisl** [comment] 2023-06-29 22:51
Sounds good to me.  @gedu I don't mean to impose this on you – are you ok with taking this issue on your plate?

**Comment by francoisl** [comment] 2023-06-30 17:54
Hi @Nodebrute, sorry for the confusion here.

It sounds like this _might_ be done internally if @gedu can take the issue, but at first glance it looks like your proposal would work, so in the interest of getting this done quickly, I'd be open to going with it. I'm just not sure if the change on the `searchWords` line could possibly cause regressions so I'm going to do a bit more research first. Also @fedirjh - curious for your thoughts here.

In the meantime, I'm temporarily going to remove the `Help Wanted` label so we don't get more proposals.

**Comment by gedu** [comment] 2023-07-04 06:42
Hey, Edu here, I've been working on the Design Documentation and this is one of the Search items to tackle, so you can assign this to me.

**Comment by gedu** [comment] 2023-07-04 06:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Use AND logical operator instead of OR when searching with multiple strings

### What is the root cause of that problem?
When using search, there is a validation function to check if a user should be added into the result list, called `isSearchStringMatch` from `OptionListUtils`. One of its parameters, **searchText** is a string with all the ways to find that particular user. example:  
```
ded eded eduardo.graciano@callstack.com eduardograciano@callstack.com ded eded owes CA$101.66 
```
or for groups 
```
lab.ques+1@callstack.com labques+1@callstack.com Ale HG Traffic ale.boo+hgtraffic@callstack.com aleboo+hgtraffic@callstack.com random.foo+20@callstack.com randomfoo+20@callstack.com random 
```

So if we have these users `Edu, Vit and Silva` and we have a group with them, when we query using "Edu Vit Silva" we have as **searchValues** `[“Edu Vit Silva”, “Edu”, “Vit”, “Silva”]`  but the string "Edu Vit Silva" won’t appear on any “searchText” as a single word.

### What changes do you think we should make in order to solve the problem?
Avoid adding the main query into the words to check, I will split the words and add them into a “Set”, getting just `["Edu", "Vit", "Silva"]`, and using the `forEach` from the Set to avoid extra parsing and mapping.
In addition, I will start removing the usage of “underscore” (_) functions

**Comment by mountiny** [comment] 2023-07-06 01:49
I am not assigned to this issue but 👍 to the proposal as co author of the search doc 😄 

@fedirjh @francoisl what do you think of the proposal, any concerns or can @gedu go ahead?

**Comment by francoisl** [comment] 2023-07-06 18:02
Works for me, let's go ahead with that.

**Comment by gedu** [comment] 2023-07-07 14:05
@francoisl PR created: https://github.com/Expensify/App/pull/22411

**Comment by kevinksullivan** [comment] 2023-07-10 17:05
@gedu can you apply to the upwork job?

https://www.upwork.com/jobs/~01a5aa75c9c3dbcd67

**Comment by danieldoglas** [comment] 2023-07-10 17:25
@kevinksullivan we don't pay Callstack through Upwork, so I don't think that job is needed!

**Comment by kevinksullivan** [comment] 2023-07-10 17:55
ahh my bad, I didn't realize @gedu was from callstack 👍

**Comment by francoisl** [comment] 2023-07-20 18:01
@fedirjh can you fill out the checklist above please? Other than that, this is ready for payments and closing.

**Comment by francoisl** [comment] 2023-07-20 18:53
I was thinking we can at least add regression tests? It doesn't have to be complicated - something along the lines of:

1. Make sure you have a group with 2 people, or create one
2. Open the search view, type the first (or last name) of each person, like `Bob Alice`
3. Make sure the chat with those 2 people is in the results list

**Comment by francoisl** [comment] 2023-07-20 20:00
LGTM 👍

**Comment by francoisl** [comment] 2023-07-21 18:36
@kevinksullivan - I created the internal regression test issue for ya [here](https://github.com/Expensify/Expensify/issues/301962), we just need to make the payments now.

**Comment by kevinksullivan** [comment] 2023-07-24 17:58
Ah nice thanks @francoisl . Handling payments now.

**Comment by kevinksullivan** [comment] 2023-07-24 17:59
Paid but upwork won't let me cancel the job right now 🙃 . @fedirjh I'll set a reminder to close that out. 

<img width="1376" alt="image" src="https://github.com/Expensify/App/assets/22508290/fa52a500-20c4-4368-b08a-9845f2c15bca">

**Closed by kevinksullivan** 2023-07-24 17:58 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
