### ISSUE TITLE
[HOLD for payment 2024-03-26] [$250] [Simplified Collect][More Features] Optimistically set defaults for Workflows if feature is disabled

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#38250] opened 2024-03-13 18:49 UTC
Coming from [this PR](https://github.com/Expensify/App/pull/37441), we need to optimistically set the default values for the workspace if the workflows feature is disabled, i.e.

- Scheduled Submit (Delayed Submission) off (harvesting.enabled = false)
- No approvals (Submit & close) - approval mode OPTIONAL
- Reimbursement choice - reimburseNo

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by nkdengineer** [comment] 2024-03-14 09:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Optimistically set defaults for Workflows if feature is disabled
### What is the root cause of that problem?
- In [here](https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/Policy.ts#L3367), when turning off the policy workflow, we do not has optimistic data for the related keys, for example, ```approvalMode```, ```areWorkflowsEnabled```, ```autoReporting```, ```harvesting.enabled```, ```reimbursement.choice.reimbursementChoice```, ...
### What changes do you think we should make in order to solve the problem?
- We need to set the above optimistic data once we turn off policy workflow.
```
 const optimisticDataWhenDisabled = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.POLICY}${policyID}`,
            value: {
                approvalMode: CONST.POLICY.APPROVAL_MODE.OPTIONAL,
                autoReporting: false,
                harvesting: {
                    enabled: false,
                },
                reimbursement: {choice: {reimbursementChoice: CONST.POLICY.REIMBURSEMENT_CHOICES.REIMBURSEMENT_NO}},
                reimbursementChoice: CONST.POLICY.REIMBURSEMENT_CHOICES.REIMBURSEMENT_NO,
            },
        },
    ];
```
- Then add the above optimistic data to the optimisticData in [here](https://github.com/Expensify/App/blob/b7a230ea75dbc4294f061c7627a24679e346641e/src/libs/actions/Policy.ts#L3367) if ```enabled: false```

### What alternative solutions did you explore? (Optional)
- NA

**Comment by nkdengineer** [comment] 2024-03-15 11:38
@luacmartins Can a contributor work on this issue? I can open the PR in a day. Thanks

**Comment by mountiny** [comment] 2024-03-15 11:59
@nkdengineer its a straightforward change, I will export this for $250

**Comment by mountiny** [comment] 2024-03-15 12:00
No C+ review will be required

@nkdengineer please raise the Pr

**Comment by nkdengineer** [comment] 2024-03-16 04:28
@luacmartins PR https://github.com/Expensify/App/pull/38432 is ready to review

**Comment by mountiny** [comment] 2024-03-16 23:45
PR merged, thanks for a quick work

@bfitzexpensify this will be $250 to @nkdengineer, no C+ this time

**Comment by luacmartins** [comment] 2024-04-01 16:26
I think we can skip the checklist since this feature was still in development when the bug was repoerted.

**Comment by luacmartins** [comment] 2024-04-01 16:27
Just pending payment.

**Comment by bfitzexpensify** [comment] 2024-04-01 23:32
Sweet - @nkdengineer, can you apply here? https://www.upwork.com/jobs/~0132d6d738f448da5d

**Comment by mountiny** [comment] 2024-04-09 23:59
@nkdengineer Is this completed?

**Comment by bfitzexpensify** [comment] 2024-04-12 13:34
Bump @nkdengineer - can you apply to the Upwork [job](https://www.upwork.com/jobs/~0132d6d738f448da5d) so we can finalise payment?

**Comment by bfitzexpensify** [comment] 2024-04-15 14:33
Bumping in Slack

**Comment by bfitzexpensify** [comment] 2024-04-15 15:08
Payment complete, closing this one out.

**Closed by bfitzexpensify** 2024-04-15 15:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
