### ISSUE TITLE
[HOLD for payment 2022-07-15] [$250] Changing workspace image showing green outline - reported by @jayeshmangwani

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#9246] opened 2022-05-31 04:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. navigate to workspace
2. press workspace image
3. change workspace image
4. navigate back to the settings page

## Expected Result:
There should not be the green outline or clear avatar borders

## Actual Result:
Changing workspace image showing green outline

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.69-2
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-05-31 at 12 45 26 AM](https://user-images.githubusercontent.com/43995119/171094666-1b72b2f0-e467-4772-b71c-e4a92e0586ae.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @jayeshmangwani
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1651677456148549

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-06-07 14:12
Upwork job here: https://www.upwork.com/jobs/~0169fe02cfd2563df8. We're open for proposals.

**Comment by JoshuaM1995** [comment] 2022-06-08 01:12
# Proposal

This issue is caused by `styles.popoverMenuIconEmphasized` containing a green background color on the `InitialSettingsPage` component.

I propose to change it to use the `popoverMenuIcon` style instead.

https://github.com/Expensify/App/blob/784d5384ae0abe772fea8c129733f081c384d423/src/pages/settings/InitialSettingsPage.js#L142

### Before proposed change:
![CleanShot 2022-06-07 at 19 08 24](https://user-images.githubusercontent.com/26679919/172509694-5352229c-ab8f-401a-b5b6-6ace5b4e89ea.png)

### After proposed change:
![CleanShot 2022-06-07 at 19 09 46](https://user-images.githubusercontent.com/26679919/172509822-f619ab53-3448-41ad-a45c-7990c22bf123.png)

**Comment by rushatgabhane** [comment] 2022-06-08 18:20
@JoshuaM1995 that'd break the existing default workspace avatars.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/29673073/172688883-6b12f6bc-845d-4920-a7e2-bbc64512accc.png">

**Comment by JoshuaM1995** [comment] 2022-06-08 20:41
@rushatgabhane fair point. What do you think about this?

When the `policy.avatarURL` is defined, use the `popoverMenuIcon` styles, and when it's not defined use the `popoverMenuIconEmphasized` style?

**Comment by rushatgabhane** [comment] 2022-06-10 19:39
@JoshuaM1995 can you think of a simpler solution?

**Comment by JoshuaM1995** [comment] 2022-06-10 19:51
@rushatgabhane Yes, you're right. I just checked `MenuItem.js` and it already has the `popoverMenuIcon` styles applied, so it would be redundant to apply them a second time.

https://github.com/Expensify/App/blob/784d5384ae0abe772fea8c129733f081c384d423/src/components/MenuItem.js#L67

My updated proposal is to apply the `popoverMenuIconEmphasized` style when the `policy.avatarURL` is not defined, and not apply any styles when it is defined, so it uses the default `popoverMenuIcon` styles from the `MenuItem` component.

**Comment by rushatgabhane** [comment] 2022-06-13 12:46
@NikkiWines I recommend @JoshuaM1995's [proposal](https://github.com/Expensify/App/issues/9246#issuecomment-1152682069).

When `policy.avatarURL` is defined, no iconStyles will be applied here.
https://github.com/Expensify/App/blob/784d5384ae0abe772fea8c129733f081c384d423/src/pages/settings/InitialSettingsPage.js#L142

🎀 👀 🎀 C+ reviewed

**Comment by NikkiWines** [comment] 2022-06-13 16:18
Yep, looks good! @JmillsExpensify could you please hire @JoshuaM1995 for this issue, thank you!

**Comment by JoshuaM1995** [comment] 2022-06-14 00:09
Hello, @JmillsExpensify.

I applied through Upwork just now.

**Comment by rushatgabhane** [comment] 2022-06-20 11:51
@JoshuaM1995 how's the PR looking? Please feel free to ask questions

**Comment by JmillsExpensify** [comment] 2022-06-20 14:19
Hired both @JoshuaM1995 and @rushatgabhane via Upwork and I've also assigned @JoshuaM1995 to this issue for clarity. Thanks all!

**Comment by JoshuaM1995** [comment] 2022-06-20 19:19
@rushatgabhane It's looking good. I'm going to test it tonight then submit it for code review if everything goes well.

**Comment by JoshuaM1995** [comment] 2022-06-21 06:05
@rushatgabhane I've created the PR here: https://github.com/Expensify/App/pull/9507

**Comment by rushatgabhane** [comment] 2022-06-29 04:34
@JoshuaM1995 congrats on your first PR to Expensify/App!

**Comment by JmillsExpensify** [comment] 2022-07-04 17:36
Yes congrats! I'm just coming back from OOO and I noticed that we're still waiting to push this PR to production. I'm assuming that's because the entire production deploy is being help up on blocking dependencies, is that right?

**Comment by rushatgabhane** [comment] 2022-07-05 01:30
@JmillsExpensify yeah, we had a nasty/tricky blocker. It's all good now

**Comment by JmillsExpensify** [comment] 2022-07-06 22:58
Ok thanks! I don't see that the related PR has hit production yet though. Is that right?

**Comment by JmillsExpensify** [comment] 2022-07-12 16:42
Almost through the regression period following the production deploy last week.

**Comment by NikkiWines** [comment] 2022-07-15 01:43
Looks like it's been 7 days and we can now issue payment to @JoshuaM1995! 🎊

**Comment by NikkiWines** [comment] 2022-07-19 03:17
@JmillsExpensify did we issue payment for this issue? Can we close this out?

**Comment by jayeshmangwani** [comment] 2022-07-19 03:43
Reporting bonus is due 
cc : @JmillsExpensify @NikkiWines

**Comment by JmillsExpensify** [comment] 2022-07-19 03:54
On it! Standby, I'll be back with an update shortly.

**Comment by JmillsExpensify** [comment] 2022-07-19 03:59
Contract for @rushatgabhane and @JoshuaM1995 has been paid out and closed. 

@jayeshmangwani please apply here for reporting bonus: https://www.upwork.com/jobs/~015526d4145f0768a6.

**Comment by jayeshmangwani** [comment] 2022-07-19 04:10
@JmillsExpensify applied to this job, Thanks!

**Comment by JmillsExpensify** [comment] 2022-07-19 04:26
Offer sent!

**Comment by JmillsExpensify** [comment] 2022-07-19 04:31
Alright, thanks everyone! All contributors should be paid. Please reach out via Slack or add a comment here if something is off and we'll get you settled. Thanks so much!

**Closed by JmillsExpensify** 2022-07-19 04:31 UTC
Labels: Exported, External, Engineering, Daily, Improvement, Awaiting Payment
