### ISSUE TITLE
LHN- Previously grayed chats in LHN have their accounts grayed in attendees list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#14560] opened 2023-01-25 18:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Go offline
3. Create Split Bill with several accounts you didn't have messages with
4. Grayed chats are created and visible in LHN
5. While still offline click FAB > Split Bill
6. Input amount and proceed to attendees page

## Expected Result:
No any accounts should be grayed out on attendees page

## Actual Result:
Previously grayed chats in LHN have their accounts grayed in attendees list

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.2.59.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/214651921-1d2faa71-c0ae-4387-a346-889827af77c3.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a657b2f21b30feb1</li>
        <li>Upwork Job ID: 1620494456348491776</li>
        <li>Last Price Increase: 2023-01-31</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-01-26 19:50
@kbecciv just to confirm - is this only occurring on MacOS / Chrome / Safari?

**Comment by kbecciv** [comment] 2023-01-27 04:04
@NicMendonca issue is occurring in all environments.

**Comment by NicMendonca** [comment] 2023-01-27 12:40
@kbecciv I can't seem to reproduce this: 

![image](https://user-images.githubusercontent.com/24947345/215089348-352f30e7-062c-417b-ab2a-db5a8d2ed33e.png)

![image](https://user-images.githubusercontent.com/24947345/215089364-3fe98305-9514-4278-b356-6cb99e527aae.png)

**Comment by NicMendonca** [comment] 2023-01-30 22:37
@kbecciv bump!

**Comment by kbecciv** [comment] 2023-01-31 13:18
@NicMendonca Checking, update you shortly

**Comment by kbecciv** [comment] 2023-01-31 14:49
@NicMendonca QA team is able to reproduce this issue with latest build 1.2.62.1


https://user-images.githubusercontent.com/93399543/215793010-f8d64457-23a2-4db0-83c0-f9d52b50c3c6.mp4

**Comment by NicMendonca** [comment] 2023-01-31 18:48
@kbecciv thank you!

![image](https://user-images.githubusercontent.com/24947345/215854209-15cb7f7d-3c2f-4aad-927c-e4166a3715b8.png)

![image](https://user-images.githubusercontent.com/24947345/215854236-8162c02e-4efa-4313-811b-22af2a33b4cd.png)

![image](https://user-images.githubusercontent.com/24947345/215854248-0f5a1a7b-a9d9-4fee-a7b6-ab260e42434c.png)


Looks like you can still split with the "greyed" attendees, but agree its a bug that they are grey

**Comment by tienifr** [comment] 2023-01-31 18:50
# Proposal
## Problem
Because we create new chats offline, these reports will be marked `pendingAction === add`. And then `OfflineWithFeedback` Component will check if an option has `pendingAction !== null`, this option will be grayed
## Solution
I suggest that we should add a new prop (shouldRemovePendingAction) for `getSection` function in Expensify/App/src/libs/OptionsListUtils.js 

And then we will pass `shouldRemovePendingAction === true` when we need to remove pendingAction and don't want to gray out report that has pendingAction

```diff
diff --git a/src/libs/OptionsListUtils.js b/src/libs/OptionsListUtils.js
index d88d1292a..b51d5a179 100644
--- a/src/libs/OptionsListUtils.js
+++ b/src/libs/OptionsListUtils.js
@@ -446,6 +446,7 @@ function getOptions(reports, personalDetails, {
     showChatPreviewLine = false,
     sortPersonalDetailsByAlphaAsc = true,
     forcePolicyNamePreview = false,
+    shouldRemovePendingAction = false,
 }) {
     let recentReportOptions = [];
     let personalDetailsOptions = [];
@@ -614,6 +615,24 @@ function getOptions(reports, personalDetails, {
         }], ['asc']);
     }
 
+    if (shouldRemovePendingAction) {
+        if (personalDetailsOptions && personalDetailsOptions.length > 0) {
+            personalDetailsOptions = _.map(personalDetailsOptions, option => ({
+                ...option, pendingAction: null,
+            }));
+        }
+        if (recentReportOptions && recentReportOptions.length > 0) {
+            recentReportOptions = _.map(recentReportOptions, option => ({
+                ...option, pendingAction: null,
+            }));
+        }
+        if (userToInvite && userToInvite.length > 0) {
+            userToInvite = _.map(userToInvite, option => ({
+                ...option, pendingAction: null,
+            }));
+        }
+    }
+
     return {
         personalDetails: personalDetailsOptions,
         recentReports: recentReportOptions,
@@ -709,6 +728,8 @@ function getNewChatOptions(
         includePersonalDetails: true,
         maxRecentReportsToShow: 5,
         excludeLogins,
+        shouldRemovePendingAction: true,
+
     });
 }
 

```

## Result 

https://user-images.githubusercontent.com/113963320/215273043-80932cc1-e3a5-4881-8a6e-e2632834a2ae.mp4

**Comment by bernhardoj** [comment] 2023-02-01 03:12
### **Proposal**

I think it's expected https://github.com/Expensify/App/pull/12150. If we want to change the behavior, then we can just remove the pending action for `createOption`.

```diff
diff --git a/src/libs/OptionsListUtils.js b/src/libs/OptionsListUtils.js
index d88d1292a..ebe2cfdb0 100644
--- a/src/libs/OptionsListUtils.js
+++ b/src/libs/OptionsListUtils.js
@@ -309,7 +309,7 @@ function createOption(logins, personalDetails, report, reportActions = {}, {
         result.shouldShowSubscript = result.isPolicyExpenseChat && !report.isOwnPolicyExpenseChat && !result.isArchivedRoom;
         result.allReportErrors = getAllReportErrors(report, reportActions);
         result.brickRoadIndicator = !_.isEmpty(result.allReportErrors) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : '';
-        result.pendingAction = report.pendingFields ? (report.pendingFields.addWorkspaceRoom || report.pendingFields.createChat) : null;
+        result.pendingAction = report.pendingFields ? report.pendingFields.addWorkspaceRoom : null;
         result.ownerEmail = report.ownerEmail;
         result.reportID = report.reportID;
         result.isUnread = ReportUtils.isUnread(report);
```

or remove it completely.

**Comment by tienifr** [comment] 2023-02-01 03:45
# Proposal

## Solution 2
We add a field `shouldRemovePendingAction` in `OptionRow` component to decide whether we should pass pendingAction in `OfflineWithFeedback` component


```diff

diff --git a/src/components/OptionRow.js b/src/components/OptionRow.js
index e25b0b807..166ebc964 100644
--- a/src/components/OptionRow.js
+++ b/src/components/OptionRow.js
@@ -59,6 +59,7 @@ const propTypes = {
 
     style: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.object), PropTypes.object]),
 
+    shouldRemovePendingAction: PropTypes.bool,
     ...withLocalizePropTypes,
 };
 
@@ -73,6 +74,8 @@ const defaultProps = {
     optionIsFocused: false,
     style: null,
     shouldHaveOptionSeparator: false,
+    shouldRemovePendingAction: false,
+
 };
 
 const OptionRow = (props) => {
@@ -104,7 +107,7 @@ const OptionRow = (props) => {
 
     return (
         <OfflineWithFeedback
-            pendingAction={props.option.pendingAction}
+            pendingAction={props.shouldRemovePendingAction ? null : props.option.pendingAction}
             errors={props.option.allReportErrors}
             shouldShowErrorMessages={false}
         >

```

and we will pass `shouldRemovePendingAction === true ` in IOUParticipantsRequest.js and IOUParticipantsSplit.js

```diff
diff --git a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js b/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
index 0b29c1df1..5b43261c5 100755
--- a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
+++ b/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsRequest.js
@@ -134,6 +134,7 @@ class IOUParticipantsRequest extends Component {
         );
         return (
             <OptionsSelector
+                shouldRemovePendingAction
                 sections={this.getSections()}
                 value={this.state.searchTerm}
                 onSelectRow={this.addSingleParticipant}
diff --git a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js b/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
index 7da28e971..698580d02 100755
--- a/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
+++ b/src/pages/iou/steps/IOUParticipantsPage/IOUParticipantsSplit.js
@@ -217,6 +217,7 @@ class IOUParticipantsSplit extends Component {
                             {this.props.translate('common.to')}
                         </Text>
                         <OptionsSelector
+                            shouldRemovePendingAction
                             canSelectMultipleOptions
                             sections={sections}
                             selectedOptions={this.props.participants}
```

**Comment by Beamanator** [comment] 2023-02-02 13:37
@rushatgabhane are you available to review the proposals here? :D

**Comment by s77rt** [comment] 2023-02-04 21:33
### Proposal
```diff
diff --git a/src/components/LHNOptionsList/OptionRowLHN.js b/src/components/LHNOptionsList/OptionRowLHN.js
index c57d51d29e..bda0ef7ef1 100644
--- a/src/components/LHNOptionsList/OptionRowLHN.js
+++ b/src/components/LHNOptionsList/OptionRowLHN.js
@@ -102,6 +102,7 @@ const OptionRowLHN = (props) => {
             pendingAction={optionItem.pendingAction}
             errors={optionItem.allReportErrors}
             shouldShowErrorMessages={false}
+            shouldApplyPendingOpacityWhenOffline={false}
         >
             <Hoverable>
                 {hovered => (
diff --git a/src/components/OfflineWithFeedback.js b/src/components/OfflineWithFeedback.js
index e80618ce0a..9613affdd9 100644
--- a/src/components/OfflineWithFeedback.js
+++ b/src/components/OfflineWithFeedback.js
@@ -31,6 +31,9 @@ const propTypes = {
     /** Whether we should show the error messages */
     shouldShowErrorMessages: PropTypes.bool,
 
+    /** Whether we should apply pending opacity when offline */
+    shouldApplyPendingOpacityWhenOffline: PropTypes.bool,
+
     /** A function to run when the X button next to the error is clicked */
     onClose: PropTypes.func,
 
@@ -56,6 +59,7 @@ const defaultProps = {
     pendingAction: null,
     errors: null,
     shouldShowErrorMessages: true,
+    shouldApplyPendingOpacityWhenOffline: true,
     onClose: () => {},
     style: [],
     contentContainerStyle: [],
@@ -85,7 +89,7 @@ const OfflineWithFeedback = (props) => {
     const isOfflinePendingAction = props.network.isOffline && props.pendingAction;
     const isUpdateOrDeleteError = hasErrors && (props.pendingAction === 'delete' || props.pendingAction === 'update');
     const isAddError = hasErrors && props.pendingAction === 'add';
-    const needsOpacity = (isOfflinePendingAction && !isUpdateOrDeleteError) || isAddError;
+    const needsOpacity = (isOfflinePendingAction && props.shouldApplyPendingOpacityWhenOffline && !isUpdateOrDeleteError) || isAddError;
     const needsStrikeThrough = props.network.isOffline && props.pendingAction === 'delete';
     const hideChildren = !props.network.isOffline && props.pendingAction === 'delete' && !hasErrors;
     let children = props.children;
diff --git a/src/components/OptionRow.js b/src/components/OptionRow.js
index f31def0582..31372682f9 100644
--- a/src/components/OptionRow.js
+++ b/src/components/OptionRow.js
@@ -143,6 +143,7 @@ class OptionRow extends Component {
                 pendingAction={this.props.option.pendingAction}
                 errors={this.props.option.allReportErrors}
                 shouldShowErrorMessages={false}
+                shouldApplyPendingOpacityWhenOffline={false}
             >
                 <Hoverable
                     containerStyles={[
```

### RCA
When we create a new chat it's created with `pendingAction: add`.
In options list we use `<OfflineWithFeedback />` where we have a condition `needsOpacity` that applies opacity if we have a pending action and we are offline. That's the case here.

https://github.com/Expensify/App/blob/6a787ca3dc5c1087b08f8034b260ab303b9b3d83/src/components/OfflineWithFeedback.js#L88

The fix is to add a new prop to `OfflineWithFeedback` where we can opt out of this feature. In my proposal the new added prop is `shouldApplyPendingOpacityWhenOffline` which is passed with `false` for LHN Options and Report Options (the ones used on IOU split/request/etc.)

**Comment by Beamanator** [comment] 2023-02-06 08:25
Ooh great find @rushatgabhane - I bet this is a case of not updating `TestRail`.

@kbecciv Can you please let us know which TestRail cases were violated which led you to create this issue?

Also @neil-marcellini I know your PR was merged a while back so sorry to drag you back into this, but:

> Looks like you can still split with the "greyed" attendees, but agree its a bug that they are grey

Is it expected that users can split bills with accounts that haven't "officially" been created yet? I assume yes, which means we just need to add a few new testrail cases for Offline UI?

**Comment by Beamanator** [comment] 2023-02-07 11:50
Def makes sense @neil-marcellini 👍  Now I see that the regression steps were supposed to be created via the final point here: https://github.com/Expensify/App/issues/13586#issuecomment-1369938879

So I think we can just purely close this out 👍

**Comment by neil-marcellini** [comment] 2023-02-07 17:47
Let's close this out. https://github.com/Expensify/App/issues/13586 is the issue that needs to be completed.

**Closed by neil-marcellini** 2023-02-07 17:47 UTC
Labels: Engineering, Daily, Bug
