### ISSUE TITLE
[$250] Attachement - Console log error appears when sending an attachment

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46060] opened 2024-07-23 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45366
## Action Performed:
1. Go to the staging app
2. Open Console
3. Copy any image to your clipboard
4. Open any report
5. Paste the image to the composer input by Ctrl+V
6. Press the 'Enter' key to send the message
7. Observe the console tab while the action is being performed

## Expected Result:
No console error will show up

## Actual Result:
Console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/67d79d34-228e-4473-83dd-eb2a3153c6e4

[logs (2).txt](https://github.com/user-attachments/files/16352344/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0108693be973624c6a</li>
        <li>Upwork Job ID: 1816579481007178354</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-07-23 17:25
We think that this bug might be related to #vip-vsp

**Comment by johncschuster** [comment] 2024-07-25 21:00
I have reproduced this


https://github.com/user-attachments/assets/7e81e76f-d392-40d7-9836-44e496e25a3f

**Comment by trjExpensify** [comment] 2024-07-26 01:18
This is a chat attachment bug, better suited for #vip-vsb.

**Comment by johncschuster** [comment] 2024-07-29 21:58
@Pujan92 can you take a look? It's not clear to me if this can be resolved by an external contributor or if it has to be resolved internally, and that will help me decide if we're going to prioritize this.

**Comment by Pujan92** [comment] 2024-07-30 11:12
@johncschuster We can let it open for the external contributors as I see some error in Onyx saving.

<img width="1436" alt="Screenshot 2024-07-30 at 16 34 13" src="https://github.com/user-attachments/assets/64d74ead-9b75-4dbf-9517-9e1c65965cb1">

**Comment by johncschuster** [comment] 2024-08-01 20:43
@Pujan92 I'm confused by your last comment. Can you clarify that for me? Do you feel this can be resolved by an external contributor, or do you feel we will need to take this internal?

**Comment by Pujan92** [comment] 2024-08-02 09:19
@johncschuster It seems more like a front-end issue only, so we can keep this open for external contributors.

**Comment by johncschuster** [comment] 2024-08-05 21:24
> It seems more like a front-end issue only, so we can keep this open for external contributors.

Got it! Thanks for clarifying that! In that case, let's see if we can drum up some proposals!

**Comment by johncschuster** [comment] 2024-08-05 21:25
bump for melv

**Comment by johncschuster** [comment] 2024-08-05 21:26
bump for melv

**Comment by Pujan92** [comment] 2024-08-07 11:11
Thanks @ardent-dev.

@johncschuster I am also not able to reproduce this now, can you plz confirm?

**Comment by johncschuster** [comment] 2024-08-09 21:35
@Pujan92

> I am also not able to reproduce this now, can you plz confirm?

Sure! I've just asked for a retest. If the issue isn't reproducible, let's close the issue.

**Comment by johncschuster** [comment] 2024-08-14 14:35
Ok! I'm going to go ahead and close this one then. Thanks for the retest!

**Closed by johncschuster** 2024-08-14 14:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug, retest-weekly
