### ISSUE TITLE
Dev: Web - Assign Task -"Hmm.. it's not here ..." message is shown when assigning task to the new unknown user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21047] opened 2023-06-19 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Click to FAB + button
3. Click to  Assign task
4. Enter title
5. Click to next button
6. For assignee - search any new unknown user
7. Click to  Confirm task

## Expected Result:
You should be able to assign a task to the user

## Actual Result:
"Hmm.. it's not here ..." message is shown when assigning task to the new unknown user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.26-1

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/344846dc-a8f7-4c9e-81e5-8958d0b33e7a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686414530209619

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nitin-kukreti** [comment] 2023-06-19 16:31
I my system their is no option for assign task showing up

**Comment by Christinadobrzyn** [comment] 2023-06-20 20:32
I can reproduce but asking the reporter what they think we should see instead of the "Hmm... it's not here" message - https://expensify.slack.com/archives/C049HHMV9SM/p1687293058124669?thread_ts=1686414530.209619&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-06-21 20:00
Asking if this issue will be fixed with - https://github.com/Expensify/App/issues/21162

**Comment by marcochavezf** [comment] 2023-06-21 20:31
Hi @Christinadobrzyn, ah nope, it won't be fixed with the other PR. I tested real-quick locally, and we're throwing an error for the `CreateTask` command. So we're erroring here in the server on purpose, but we're not handling that error on the client-side. I think we'd need to discuss if we should update how we're giving the feedback to the user (which will be a frontend change) or if we'd need to handle this case for non-existing users

<img width="1434" alt="Screenshot 2023-06-21 at 14 25 04" src="https://github.com/Expensify/App/assets/6829422/b5400e00-7866-4b97-9b96-0dfae79ba557">

cc @jasperhuangg (since I think you could have more context about this issue)

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:12
@jasperhuangg do you have any thoughts on this? Or I can reach out to the BZ team? Not sure what's best!

**Comment by thienlnam** [comment] 2023-06-23 23:14
Pretty sure we resolved this in another App PR a while ago. Closing but feel free to re-open if we are experiencing this again

**Closed by thienlnam** 2023-06-23 23:14 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by jasperhuangg** [comment] 2023-06-23 23:20
Ah yup, I think we resolved this a while back. Thanks for checking!

**Comment by narzullome** [comment] 2023-06-23 23:20
Pretty sure we resolved this in another App PR a while ago @thienlnam  do u mean it was dupe ?

**Comment by thienlnam** [comment] 2023-06-23 23:21
Yup!

**Comment by narzullome** [comment] 2023-06-23 23:28
sorry do u mean on  21162 if not can u share the link of that
