### ISSUE TITLE
CRITICAL: [$500]  Suppress "joined the room" message when posting

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33000] opened 2023-12-13 18:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mallenexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1702490502156779

## Action Performed:
1. Create a private room in account A and invite B as a member
2. Send a message in the room
3. Login as B and reply in thread
4. Open the thread as admin A

## Expected Result:
Only the message sent by the member appears in the thread

## Actual Result:
"Joined room" shows in message and LHN

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (10)](https://github.com/Expensify/App/assets/38435837/37236b6c-1e1f-46d6-92c6-a8c75859341d)

![image (9)](https://github.com/Expensify/App/assets/38435837/9e61535b-1d9b-49cf-a67f-5b8242ddd9bd)

![Snip - (5) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/e3b6ccd6-38ae-40e9-9a62-e8988b854209)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0184383803c0c6bc11</li>
        <li>Upwork Job ID: 1735011184779403264</li>
        <li>Last Price Increase: 2023-12-20</li>
    </ul>
</details>

**Comment by AmjedNazzal** [comment] 2023-12-13 22:50
This is BE issue, the BE is returning `"lastMessageText": "joined the room"` even though the api command is just `AddComment`

**Comment by getusha** [comment] 2023-12-18 12:35
Looks like this is a backend issue, @youssef-lr

**Comment by mallenexpensify** [comment] 2023-12-19 04:39
Reckon this is part of #vip-vsb since it doesn't involve expenses.  Wanna post there to check @NicMendonca?

**Comment by youssef-lr** [comment] 2023-12-21 04:38
Yeah this is a backend issue, I think we realized this during a recent test and we will be fixing it. I also think this is part of #vip-vsb @mallenexpensify.

**Comment by mallenexpensify** [comment] 2023-12-23 18:29
@marcochavezf , any chance you're working on this?
Posted in #vip-vsb https://expensify.slack.com/archives/C066HJM2CAZ/p1703356044998519

Was also wondering if this is related, but I think that's wishful thinking
[Unexpected Whisper Message Displayed in NewDot #admins Room](https://github.com/Expensify/App/issues/32074#top)

**Comment by quinthar** [comment] 2023-12-25 19:43
This isn't limited to threads; this is the case for every room.  Can we please update this issue with a new description:

**Problem:**
Every room of every type has a membership.  When you join a room, we notify everyone that you've joined.  This is helpful to know who is "lurking" in the room and listening.  However, when you join a room as a byproduct of posting, this is redundant -- it's already obvious you are there by the mere fact that you posted.

**Solution:**
Suppress the "X has joined" message when posting, as it's unnecessary.  Continue sending "X as joined" when explicitly clicking the "join" button.  This likely involves two changes:

1. Update the client to not optimistically add the join message when you post
2. Verify the client *does* optimistically add the join message when you click `Join`
3. Update the back end to *not* send the join message when someone posts

**Comment by youssef-lr** [comment] 2023-12-26 21:27
I'm focusing on Wave7 and a #vip-split, can we get this reassigned please to someone from the #vsb team?

**Comment by quinthar** [comment] 2023-12-28 00:30
Optimistically assigning to @blimpich

**Comment by quinthar** [comment] 2023-12-28 21:27
FYI, be aware of https://github.com/Expensify/App/issues/33574, but this issue feels like its own thing and is also good.

**Comment by quinthar** [comment] 2023-12-28 22:04
Actually thinking more on this, this situation cannot happen.  If we're only showing `joined` messages when someone is added who cannot freely join by themselves, there's no way someone who can't freely join would be previewing the room before posting anyway.  So closing this as I don't think this scenario can happen with the new rules.

**Comment by mallenexpensify** [comment] 2024-01-03 00:20
I'm still experiencing the issue where `Joined the room` is showing when I comment on a thread in a private room
<img width="810" alt="image" src="https://github.com/Expensify/App/assets/22508304/8c3d06de-b275-455e-892d-ffc46c785d17">

I don't think the reproduction steps are as particular as outlined in the OP. I think it's 
- Comment in a thread on a chat in a private room
- Observer "Joined the room" appears above your comment in the thread.

**Comment by mallenexpensify** [comment] 2024-01-03 00:31
Also seeing
- https://github.com/Expensify/App/issues/33000#issuecomment-1869097958

so.. I think we're likely/hopefully covered there for the update.

**Comment by quinthar** [comment] 2024-01-03 06:07
Reopening because of that.  @mallenexpensify Can you investigate?

**Comment by mallenexpensify** [comment] 2024-01-04 23:58
Investigating
https://expensify.slack.com/archives/C01GTK53T8Q/p1704412457069799

@NicMendonca I'll take over as BZ

**Comment by mallenexpensify** [comment] 2024-01-10 02:01
This got fixed by @jasperhuangg !
https://github.com/Expensify/Auth/pull/9586

**Closed by mallenexpensify** 2024-01-10 02:01 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
