### ISSUE TITLE
Android - Workspace -Tapping on user with "owner" tag doesn't shows "transfer owner" option

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50913] opened 2024-10-16 14:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V. 9.0.49-0
**Reproducible in staging?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
Pre-condition: As admin, invite a user to workspace and set him as admin

1. Launch app
2. Login as user who has been invited and set as admin
3. Tap profile icon -- workspaces-- workspace
4. Tap members
5. Tap on user with owner tag

## Expected Result:
Tapping on user with "owner" tag must show "transfer owner" option.

## Actual Result:
Tapping on user with "owner" tag doesn't shows "transfer owner" option.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/25a4b346-ba0f-4734-9b09-11455d063b85

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-16 14:24
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shahinyan11** [comment] 2024-10-16 14:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - Workspace -Tapping on user with "owner" tag doesn't shows "transfer owner" option
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/afe5258d925e0ac82f353e429a3fe0e91837b086/src/pages/workspace/members/WorkspaceMemberDetailsPage.tsx#L244C41-L244C72)  wi display the `transfer owner` when the `shouldRenderTransferOwnerButton` function returns `true`. And the function returns `true` for web platform  but for native platform it check if `FUND_LIST` is not empty in Onyx

### What changes do you think we should make in order to solve the problem?
There is not any description why the `shouldRenderTransferOwnerButton` returns true for web but for android it check `FUND_LIST`. And I think we can return `true` also for native platforms

### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-10-16 15:09
Might be expected according to https://github.com/Expensify/App/pull/49411#issuecomment-2377715665

**Comment by bfitzexpensify** [comment] 2024-10-17 15:26
@FitseTLT is correct - app store reasons mean we can't do this, so it's not a bug. Closing this out.

**Closed by bfitzexpensify** 2024-10-17 15:26 UTC
Labels: Daily, Bug
