### ISSUE TITLE
[$1000] Android/Chrome - The Settings tab doesn't have the closing or opening transition effect

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22047] opened 2023-07-02 02:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1- Click at the user avatar to open settings tab
2- Click at the back arrow icon
## Expected Result:
The Settings tab should has a transition effect when opening or closing it.
## Actual Result: 
On Android (Chrome), the Settings tab is opening and closing immediately without any transition effect

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/80b85062-f5eb-4c0c-b093-21dbeb6c8404

https://github.com/Expensify/App/assets/43996225/6a27e993-6f59-4693-873f-178517c0bab1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mejed-alkoutaini
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688133788679469

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c2c23a7ccc73529d</li>
        <li>Upwork Job ID: 1675662089700921344</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-07-03 00:00
Unsure if this is an issue, digging in here: https://expensify.slack.com/archives/C049HHMV9SM/p1688133788679469

**Comment by mkarkachov** [comment] 2023-07-03 16:13
I can't reproduce this bug on my Android phone (Android 13). Tab is animated correct.

**Comment by jliexpensify** [comment] 2023-07-03 22:12
@mkarkachov the only place you can repro it is on Android Chrome. Are you using the app?

@waterim I'll assign you.

**Comment by jliexpensify** [comment] 2023-07-04 04:16
@mejed-alkoutaini can you share your Upworks profile?

**Comment by mejed-alkoutaini** [comment] 2023-07-04 11:24
Contributor details
Your Expensify account email: majedkot0@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fd6d1871acf14d4b

@jliexpensify

**Comment by waterim** [comment] 2023-07-07 00:14
I have a question regarding 2 videos which are attached to this issue.
On the first one I can see the correct animation but on the second one there are no animations.
What is a difference between these 2 devices?

**Comment by jliexpensify** [comment] 2023-07-09 22:52
Hi @waterim - in my own testing, I found that this can only be reproduced [via Android Chrome](https://github.com/Expensify/App/issues/22047#issuecomment-1617016926) (i.e. there's no transition).

Whereas in the Android App, I see the transition.

**Comment by waterim** [comment] 2023-07-10 09:07
@jliexpensify Yes, in native apps I can see transition too, but in web(Android and IOS) transition as on the first video, Its laggy but I can see that. 

Can you please provide my additional information, what is a difference between 2 videos attached to this issue?

**Comment by jliexpensify** [comment] 2023-07-10 09:19
Hi @waterim I'm not sure what additional information you're looking for? On my side, I can see a difference in the behaviours (video 1 shows a transition, video 2 does not). 

I'm going to ask @mejed-alkoutaini to jump in and answer your question but we did discuss the bug [in this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688133788679469). If you haven't read it, it might help with some additional insight!

**Comment by waterim** [comment] 2023-07-10 09:35
@jliexpensify Yes, I mean the first video Android Chrome and the second one Android Chrome, on the first I can see transition, but on the second I can't see, and the question what is a difference between these two devices

**Comment by jliexpensify** [comment] 2023-07-10 09:59
The video with the transition should be from the Android app. The one without the transition is on Chrome (on an Andorid device). It's a subtle difference, but it is there!

**Comment by mejed-alkoutaini** [comment] 2023-07-10 12:57
@waterim @jliexpensify The 2nd video from Chrome (Android device) is provided by me, not sure about the 1st video I think it's provided by @kavimuru, even tho this issue still happens on Android Chrome

**Comment by waterim** [comment] 2023-07-10 12:58
@jliexpensify But these two attached videos both from Android Chrome(not an app). 
And I can't reporoduce it from Android Chrome device as well. 

Here is video how it looks from my side:

https://github.com/Expensify/App/assets/39777589/6d1d20d8-a643-47e7-bdff-77da3baf4440

**Comment by jliexpensify** [comment] 2023-07-11 01:31
Got it, sorry @waterim for the confusion: usually with these GH's the first video is the video that's made by the bug reporter, and then the 2nd video is proof that it can be replicated by the QA team.

I'm on v1.3.39-3 on Android Chrome and here's what I see:

https://github.com/Expensify/App/assets/30815269/e5d0b218-d0a8-4bb1-9119-46ec6e672d81

Honestly, comparing it to the App, the difference is so minimal. Maybe the app has slightly more of a transition? I feel like it's not really a bug anymore with v39, and certainly not as prominent as it used to be.

@mejed-alkoutaini keen to get your thoughts. You'll be paid out the reporting bonus either way, but I think we can close this.

**Comment by jliexpensify** [comment] 2023-07-11 02:12
@mejed-alkoutaini I can't seem to find you on Upworks, can you apply here? https://www.upwork.com/jobs/~01c2c23a7ccc73529d

**Comment by mejed-alkoutaini** [comment] 2023-07-11 08:03
@jliexpensify Thanks! I just applied

**Comment by waterim** [comment] 2023-07-11 17:31
@jliexpensify We have same transition for all platforms, it just weird that someone can reproduce and someone cant

**Comment by jliexpensify** [comment] 2023-07-11 23:12
@mejed-alkoutaini do you mind changing your Upworks name to mat h your name in GH? I think this will make it easier for our team to find you in the future.

@waterim like I mentioned, the difference is so subtle now - I doubt the vast majority of people will even notice. I do think it was more prominent a few versions ago, but something seems to have resolved this, so after I pay Mejed, I'll be closing this one!

**Comment by jliexpensify** [comment] 2023-07-11 23:26
Paid Mejed and closed job.

**Closed by jliexpensify** 2023-07-11 23:26 UTC
Labels: External, Daily, Bug
