### ISSUE TITLE
LHN - List of user's conversation is not displayed in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#8709] opened 2022-04-20 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/[](javascript:)
2. Log in with applause or gmail account (applausetester+0901abb@applause.expensifail.com)

## Expected Result:
List of user's conversation is displayed in LHN

## Actual Result:
List of user's conversation is not displayed in LHN

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web (android Chrome)

**Version Number:** 1.1.56.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com/Feya86Katya

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![LHN](https://user-images.githubusercontent.com/93399543/164326989-5805e9b3-7173-472c-86c6-7d00b0fdce61.png)

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2022-04-20 21:57
Adding Deploy blocker even through this is repro in PROD, as this is currently blocking multiple TCs in regression and PR validations.

**Comment by cead22** [comment] 2022-04-20 23:38
I can't reproduce this one, and I don't think it should be a blocker if it's happening in production

**Comment by roryabraham** [comment] 2022-04-20 23:49
Not sure, but I have a hunch this _might_ be related to https://github.com/Expensify/Expensify/issues/207357

**Comment by cead22** [comment] 2022-04-21 00:07
Good context on this [slack discussion](https://expensify.slack.com/archives/C03TQ48KC/p1650499108317219?thread_ts=1650495338.934079&cid=C03TQ48KC)

**Comment by cead22** [comment] 2022-04-21 00:47
We found the issue and it's the same as this one https://github.com/Expensify/Expensify/issues/207357#issuecomment-1104588045 -- check out that comment for an explanation of the bug and the reproduction steps. Assigning @flodnv since he's assigned on the dupe issue and also in a time zone ahead of PT

**Comment by mvtglobally** [comment] 2022-04-21 01:36
@cead22 @roryabraham, thanks for looking into it. Most of our testers are unable to use their regular accounts, so we are running PRs and regression on new accounts to avoid this issue. However, I believe it should be definitely looked at as many users with multiple treads/activities will not be able to use the app properly due to this issue.

**Comment by flodnv** [comment] 2022-04-21 15:36
This should be fixed now

**Closed by flodnv** 2022-04-21 15:36 UTC
Labels: Reviewing, Engineering, Daily, Improvement
