### ISSUE TITLE
[$250] Secondary contact - Technical message is displayed when clicking unlink button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47293] opened 2024-08-13 05:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.19-9
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** natnael.expensify+3@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Click on Account Settings > Profile > Contact methods > Add secondary contact method and DON'T VERIFY it
2. Logout > Enter the secondary login email address
3. Click on 'Unlink' button

## Expected Result:
Link sent message should be displayed

## Actual Result:
`unlinkLoginForm.linkSent` is displayed

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/dd513db6-3115-4cbf-83e7-d4b1c123c39e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01804377f1573ea50d</li>
        <li>Upwork Job ID: 1823344270082051171</li>
        <li>Last Price Increase: 2024-08-13</li>
<li>Automatic offers: </li>
<ul>
<li>etCoderDysto | Contributor | 103559320</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by IuliiaHerets** [comment] 2024-08-13 05:21
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-13 05:21
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by etCoderDysto** [comment] 2024-08-13 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Technical message is displayed when clicking unlink button
### What is the root cause of that problem?
Here we pass a key (`unlinkLoginForm.linkSent`)  to translation content to `DotIndicatorMessage`
https://github.com/Expensify/App/blob/88ad9c709fc95520520150b7f6f6692c45057267/src/pages/signin/UnlinkLoginForm.tsx#L58-L62

Here we are displaying a key to translation content that is located in en.ts and es.ts rather than fetching the translation content from en.ts and es.ts
https://github.com/Expensify/App/blob/de8c7aff0599212afd2875ee0c7cbea3aca40144/src/components/DotIndicatorMessage.tsx#L84-L89

### What changes do you think we should make in order to solve the problem?
We should call `transalte` method with `account.message` [here](https://github.com/Expensify/App/blob/88ad9c709fc95520520150b7f6f6692c45057267/src/pages/signin/UnlinkLoginForm.tsx#L58-L62)
```
messages={{0: translate(account.message)}}
```
### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2024-08-13 05:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Secondary contact - Technical message is displayed when clicking unlink button

### What is the root cause of that problem?
When we click on unlink button we call - `Session.requestUnlinkValidationLink()`

We build success data here - 
https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/libs/actions/Session/index.ts#L787-L825

We directly use `unlinkLoginForm.linkSent` (which is key) instead of using the message related to that key.

https://github.com/Expensify/App/blob/420c2a13cc176dca5adf8dcc8132ef5f8ff678f7/src/languages/en.ts#L1581-L1587

### What changes do you think we should make in order to solve the problem?
We should use the message instead of key.

We can use something like - `Localize.translateLocal()` for that.

We should for other actions related to unlink

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2024-08-14 17:23
Will review the proposals by tomorrow. I was OOO.

**Comment by mananjadhav** [comment] 2024-08-16 18:23
@etCoderDysto's [proposal](https://github.com/Expensify/App/issues/47293#issuecomment-2285370066) looks good to me. 

🎀 👀 🎀 C+ reviewed

**Comment by etCoderDysto** [comment] 2024-08-19 18:45
PR will be ready for review today

**Comment by etCoderDysto** [comment] 2024-08-20 11:05
@mananjadhav [PR](https://github.com/Expensify/App/pull/47703) is ready for review

**Comment by mananjadhav** [comment] 2024-09-04 17:15
@bfitzexpensify This should be ready for payout as I can see it's deployed to production last week. We don't have an offending PR as we never added the fix for this I cannot pinpoint when it should've been added.

I also don't think we need a regression test for this one.

**Comment by etCoderDysto** [comment] 2024-09-06 06:14
@bfitzexpensify I think this issue is ready for payout. Automation is failing here. It has been more than 7 days since PR was deployed to prod

**Comment by etCoderDysto** [comment] 2024-09-06 15:37
@bfitzexpensify I have accepted the offer. Thanks!

**Comment by etCoderDysto** [comment] 2024-09-06 17:57
@bfitzexpensify I think I have accepted a duplicate offer. One received [here](https://github.com/Expensify/App/issues/47293#issuecomment-2294128277), and the other received [here](https://github.com/Expensify/App/issues/47293#issuecomment-2334294479). Should I end the contract sent [here](https://github.com/Expensify/App/issues/47293#issuecomment-2294128277)?

**Closed** 2024-09-07 06:26 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by garrettmknight** [comment] 2024-09-11 19:18
$250 approved for @mananjadhav
