### ISSUE TITLE
[$1000] Text composer's height changes when entering a character in the newline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12938] opened 2022-11-22 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Go to any Chat
3. Add text on 1st line > hit Enter > Add 1 character on 2nd line

## Expected Result:
Composer's height should not change when you're already on the new line

## Actual Result:
Composer's height changes when entering a character

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Android

**Version Number:** 1.2.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/203395359-ff1bce23-751f-477f-983a-39f6d1ef5b5e.mp4

https://user-images.githubusercontent.com/43996225/203395454-0362944b-c310-452f-b9b1-3822d998e120.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @daraksha-dk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1668980261976209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~010a4a43ef8e21dabf
- Upwork Job ID: 1595202630956036096

**Comment by kadiealexander** [comment] 2022-11-22 22:35
Helped @jliexpensify reproduce this one on a Asus ROG 3 with Android 12:

https://user-images.githubusercontent.com/59587260/203435059-b865f287-17cd-4266-89b7-18b841793312.mp4

**Comment by jliexpensify** [comment] 2022-11-22 22:49
Thanks @kadiealexander for the second set of eyes! I wasn't seeing this behaviour consistently on my Android device so really good to get your video.

**Comment by kadiealexander** [comment] 2022-11-22 22:52
All good! Don't forget [Conor's checklist](https://expensify.slack.com/archives/C01GTK53T8Q/p1669058720156079?thread_ts=1669058205.220089&cid=C01GTK53T8Q) :)

**Comment by jliexpensify** [comment] 2022-11-22 23:06
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you’re unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by smrutiparida** [comment] 2022-11-23 10:36
The TextInput component is returning the contentSize as 40 for with a letter and 38.666667 for just newline. And the TextInput height is set accordingly. In the attached video you can see the nativeEvent.contentSize.height value.

https://user-images.githubusercontent.com/5945400/203525294-b7852e5d-574d-4d10-9173-cc5c4aae098d.mov

**Comment by mollfpr** [comment] 2022-11-23 17:46
Thanks for the proposal @smrutiparida! 

Could you be more specific about where the changes need to be put? Also, it will be great if you attach a video of the result.

**Comment by s77rt** [comment] 2022-11-23 20:36
This is one of the oldest issues of react-native https://github.com/facebook/react-native/issues/4977
The issue is that the `lineHeight` prop is very buggy, initially it won't be set at all, then it will be set if you type a char. If you have an empty line the prop won't be applied.

I can't think of a clean solution except for hacks and wrokarounds e.g. set the `height` to `numberOfLines * styleLineHeight` but the `numberOfLines` is based on the computed lineHeight which is not accurate, so this will only work as long as the diff is small.

**Comment by fedirjh** [comment] 2022-11-23 22:56
I think this issue is related to fontFamily , Android set a different line height for empty lines , this is a similar issue reported before https://github.com/facebook/react-native/issues/29232
The issue can be resolved by changing the `fontFamily` but I think this is not an option here . You can test with different fontFamily eg `Segoe UI Emoji`

**Comment by iwiznia** [comment] 2022-11-25 12:35
Ah yes, that react native issue is exactly the same as this one.
So, I think we want a fix on RN and not a hack that solves this in our app, especially since the effect is barely noticeable

**Comment by furkanuzundev** [comment] 2022-11-25 18:47
# Proposal

Somehow, ` flexdirection:row ` into `styles.textInputComposeSpacing` is **breaking something** on input.
When i remove **row** styling, the input is centering into view.Because of we have `alignSelf: 'center'` into `styles.textInputCompose`.Actually i'm not sure to need that.Why are we centering input?

### Workaround 

```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 55fbb693c7..b467a10878 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1408,7 +1408,7 @@ const styles = {
         paddingHorizontal: 8,
         paddingTop: 0,
         paddingBottom: 0,
-        alignSelf: 'center',
+        // alignSelf: 'center',
         textAlignVertical: 'center',
     }, 0),
 
@@ -1426,7 +1426,7 @@ const styles = {
     // composer padding should not be modified unless thoroughly tested against the cases in this PR: #12669
     textInputComposeSpacing: {
         paddingVertical: 5,
-        ...flex.flexRow,
+        // ...flex.flexRow,
         flex: 1,
     },
```

### Screenshots


 

 



https://user-images.githubusercontent.com/30953070/204041146-45e0e3d8-7d68-41e5-a8e1-ed3b5aad8d83.mov

**Comment by mollfpr** [comment] 2022-11-27 15:27
@furkanuzundev The changes that you mention are related to https://github.com/Expensify/App/issues/10202, so removing that line will make that issue resurface again. It will work if you have a solution for this issue https://github.com/Expensify/App/issues/10202.


@iwiznia @luacmartins @jliexpensify Do we agree to close this out?

**Comment by furkanuzundev** [comment] 2022-11-27 22:03
# Proposal

Okay @mollfpr , let's look at another way into problem then.

Android and iOS has different flex behaviour.When we make this changes into `styles.js`,It looks perfectly in both sides but this issue is still occuring.
So, i think we need to give flex for specific Android platform.It's best best stable style that i found.

### Workspace

```diff
diff --git a/src/pages/home/report/ReportActionCompose.js b/src/pages/home/report/ReportActionCompose.js
index 2335864f91..32b26ea234 100644
--- a/src/pages/home/report/ReportActionCompose.js
+++ b/src/pages/home/report/ReportActionCompose.js
@@ -4,6 +4,7 @@ import {
     View,
     TouchableOpacity,
     InteractionManager,
+    Platform,
 } from 'react-native';
 import _ from 'underscore';
 import lodashGet from 'lodash/get';
@@ -661,7 +662,7 @@ class ReportActionCompose extends React.Component {
                                             displayFileInModal(file);
                                             this.setState({isDraggingOver: false});
                                         }}
-                                        style={[styles.textInputCompose, this.props.isComposerFullSize ? styles.textInputFullCompose : styles.flex4]}
+                                        style={[styles.textInputCompose, this.props.isComposerFullSize ? styles.textInputFullCompose : Platform.select({android: styles.flex4})]}
                                         maxLines={this.state.maxLines}
                                         onFocus={() => this.setIsFocused(true)}
                                         onBlur={() => this.setIsFocused(false)}
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 55fbb693c7..00a77342a0 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1408,7 +1408,7 @@ const styles = {
         paddingHorizontal: 8,
         paddingTop: 0,
         paddingBottom: 0,
-        alignSelf: 'center',
+       // alignSelf: 'center',
         textAlignVertical: 'center',
     }, 0),
 
@@ -1426,8 +1426,9 @@ const styles = {
     // composer padding should not be modified unless thoroughly tested against the cases in this PR: #12669
     textInputComposeSpacing: {
         paddingVertical: 5,
-        ...flex.flexRow,
+       // ...flex.flexRow,
         flex: 1,
+        justifyContent: 'center',
     },
 
     chatItemSubmitButton: {
```

### Screenshots

https://user-images.githubusercontent.com/30953070/204161950-ac891d45-abe9-4911-bfd9-de3aa8eae42d.mov

**Comment by s77rt** [comment] 2022-11-27 22:09
@furkanuzundev I don't think you see the problem here.
Entering a new line should increase the text box height (you should be able to see both lines)
Entering a char in the new line should not increase the text box height

In your videos, entering a new line keep the text box at the same height which is undesirable.

**Comment by furkanuzundev** [comment] 2022-11-27 22:10
@s77rt you're correct.I will look at it again.

**Comment by furkanuzundev** [comment] 2022-11-28 21:19
# Proposal
After a long research, I came to the conclusion that the problem is definitely in the **font file itself.**

In the content of the font file, when the `lineGap` properties are a number other than `0`, the input causes jumping while adjusting itself according to the font. Because the `height` of the input does not increase arithmetically due to the `gap difference.`

If we want a definitive and temporary solution, we should handle it from within the font file.(https://martinadamko.medium.com/consistent-font-line-height-rendering-42068cc2957d). But it seems that we are getting the original files of the fonts from the server.

My current solution is to separate the emojiFont, the font we currently use, for android and ios. `Segoe UI Emoji, Noto Color Emoji` fonts are not added for iOS. (I don't know why). That's why it doesn't recognize the font when I call it in a single index.

### Workaround

```diff
--- a/src/styles/fontFamily/emoji/index.native.js
+++ /dev/null
@@ -1,3 +0,0 @@
-const emojiFont = 'GTAmericaExp-Regular';
-
-export default emojiFont;

+++ a/src/styles/fontFamily/emoji/index.ios.js
+++ /dev/null
@@ -1,3 +0,0 @@
+const emojiFont = 'GTAmericaExp-Regular';
+
+export default emojiFont;

+++ a/src/styles/fontFamily/emoji/index.android.js
+++ /dev/null
@@ -1,3 +0,0 @@
+const emojiFont = 'GTAmericaExp-Regular, Segoe UI Emoji, Noto Color Emoji';
+
+export default emojiFont;
```

## Screenshots

### iOS

https://user-images.githubusercontent.com/30953070/204382748-46f16400-8627-4aac-8cae-e4576adfc1df.mov

### Android

https://user-images.githubusercontent.com/30953070/204382786-570051b3-c471-45bf-b745-daecfab38964.mov

**Comment by LibanWasTaken** [comment] 2022-11-29 04:25
### Proposal
A simple trick, or maybe a temporary solution, would be to shrink the line height a little bit in the styles. The text box's height won't increase itself, but the texts on the first line are displaced a little, which is less noticeable than what it was before.

https://user-images.githubusercontent.com/85487896/204438583-f5a544da-dd05-4244-bdfb-549829e5589b.mp4

**Comment by mollfpr** [comment] 2022-11-29 08:01
Will review the proposal tonight!

Meanwhile, can we decide whether we accept a solution in our app or a fix in the RN? 
@luacmartins @iwiznia @jliexpensify

**Comment by luacmartins** [comment] 2022-11-29 16:36
The issues seems to come from RN, so I think that we should try to fix it there first instead of implementing a workaround in our App

**Comment by iwiznia** [comment] 2022-11-30 13:15
> Meanwhile, can we decide whether we accept a solution in our app or a fix in the RN?

https://github.com/Expensify/App/issues/12938#issuecomment-1327421486

**Comment by mollfpr** [comment] 2022-11-30 19:23
Thanks @luacmartins @iwiznia

Waiting for proposals to fix the RN!

**Comment by furkanuzundev** [comment] 2022-11-30 19:52
Since the problem is caused by the font itself, the 2 best options we can solve on the RN side are to increase the line height(like @LibanWasTaken proposal https://github.com/Expensify/App/issues/12938#issuecomment-1330060536 ) or use different fonts for android and iOS platform.(like my proposal https://github.com/Expensify/App/issues/12938#issuecomment-1329776254 )

I think it's a debatable topic.

**Comment by fedirjh** [comment] 2022-12-04 20:28
> I think this issue is related to fontFamily , Android set a different line height for empty lines , this is a similar issue reported before [facebook/react-native#29232](https://github.com/facebook/react-native/issues/29232)
> The issue can be resolved by changing the `fontFamily` but I think this is not an option here . You can test with different fontFamily eg `Segoe UI Emoji`

@mollfpr I think this bug got fixed with the new fontFamily update , issue not reproducible , this should be closed

**Comment by mollfpr** [comment] 2022-12-05 00:17
Thanks @fedirjh I’ll check!

**Comment by mollfpr** [comment] 2022-12-05 14:43
@luacmartins @jliexpensify This issue is not reproducible.

https://user-images.githubusercontent.com/25520267/205664809-d64aca9f-006e-4ee9-b750-aeacbbd8f026.mov

@kavimuru Could you recheck this issue? Thanks!

**Comment by LibanWasTaken** [comment] 2022-12-05 16:17
> 

I was able to reproduce it on my device; _Samsung M20 - **Android** 10_

It seems that the main differentiator is the `lineHeight: variables.lineHeightXLarge,` which does decrease the jump in my case but not completely.

(Also FSR my keyboard overlaps the composer, could be a personal bug)

https://user-images.githubusercontent.com/85487896/205686130-c1cf051b-cf9f-4dd2-a636-a28b0400f423.mp4

**Comment by luacmartins** [comment] 2022-12-05 21:50
@LibanWasTaken what version of App are you on?

**Comment by LibanWasTaken** [comment] 2022-12-06 04:56
> I couldn't reproduce either. @LibanWasTaken what version of App are you on?

I was on **1.2.36-1**. I've upgraded the app to _**1.2.36-2**_ but still got the same results

**Comment by luacmartins** [comment] 2022-12-06 17:24
I couldn't reproduce this on the latest app version on a Galaxy S22, Galaxy S20, Galaxy M52 and Pixel 6 and other contributors [can't reproduce](https://expensify.slack.com/archives/C01GTK53T8Q/p1670344561057439) it either. I'll close this issue since this either got fixed or is reproduced on very specific devices. 

Please reopen if you feel like we should look into this further.

**Comment by daraksha-dk** [comment] 2022-12-12 13:42
I reported this issue and I think it's eligible for the reporting compensation.
cc @luacmartins @jliexpensify

**Comment by jliexpensify** [comment] 2022-12-12 21:58
Hired @daraksha-dk , once you accept I'll be able to pay. Cheers!

**Comment by jliexpensify** [comment] 2022-12-13 22:51
Paid, and job closed in Upworks.

**Closed by jliexpensify** 2022-12-13 22:51 UTC
Labels: External, Daily, Help Wanted, Bug
