### ISSUE TITLE
[Tracking] [Performance] Margelo/Expensify - Performance Improvements

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#10962] opened 2022-09-13 12:53 UTC
**Top Priorities** 
- https://github.com/Expensify/App/issues/10793 - @Szymon20000 @roryabraham  
- https://github.com/Expensify/App/issues/11711 @hannojg @AndrewGable 
- https://github.com/Expensify/App/issues/10894
- https://github.com/necolas/react-native-web/issues/1019
- https://github.com/Expensify/App/issues/11321 @Beamanator @hannojg 

**Other high-value items**
- https://github.com/Expensify/App/issues/8236
- https://github.com/Expensify/App/issues/9809
- https://github.com/Expensify/App/issues/10414
- And a [bunch of crashes](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+NOT+hold+in%3Atitle+label%3ABug+Crash+in%3Atitle+sort%3Acreated-asc+) we haven’t resolved yet.
- https://github.com/Expensify/App/issues/11997

**Done**
- https://github.com/Expensify/App/issues/10789 - @szymon20000
- https://github.com/Expensify/App/pull/10800
- https://github.com/Expensify/App/pull/10860
- https://github.com/Expensify/App/issues/10794 - @Szymon20000 @aldo-expensify 
- https://github.com/Expensify/App/pull/11185 - @Szymon20000

**Comment by Szymon20000** [comment] 2022-09-14 07:47
I would add: 
- CI Tests (reassure, startup time)
- SideBarLinks
- HeaderView Doesn't use onyx context context (I think it's also the case with SideBarLinks) It means onyx will send them another copy od personalDetails as far as I know

**Comment by trjExpensify** [comment] 2022-09-14 11:19
Awesome. Added those. Presumably they don't have issues to link yet, right? Outside of SideBarLinks, as @tgolen is working on PRs for that.  

P.S - I can co-assign you this tracker now that you've commented. GH wasn't allowing me to do that yesterday.

**Comment by roryabraham** [comment] 2022-09-26 21:23
> Upgrade RN fork to 0.70

Finished this last week

**Comment by roryabraham** [comment] 2022-09-26 21:24
@tgolen @Szymon20000 I know a lot of progress has been made on the LHN improvements, is there more to do here or should we check that off?

**Comment by tgolen** [comment] 2022-09-26 21:51
I have a bunch of random cleanup items, but I feel pretty confident to check it off for now.

**Comment by roryabraham** [comment] 2022-10-06 17:41
Update:

- https://github.com/Expensify/App/issues/10794 is done
- The value of https://github.com/Expensify/App/issues/10793 is in question/unclear. I think we'll likely want to continue investigating this, but there's a lot of context in [this thread](https://expensify.slack.com/archives/C035J5C9FAP/p1664522847768359)
- https://github.com/Expensify/App/pull/11327 progress seems to have stalled, waiting for a summary of the CI stability issues from @hannojg 
- `Replace _.merge function with faster alternative` – [PR](https://github.com/Expensify/react-native-onyx/pull/186) merged yesterday and published to npm in `react-native-onyx@1.0.19`. However, we need to bump the Onyx version in App to see this change take effect.
- `Open and close the same chat again and again on Android native and it will gradually slow down for no reason` – Last we heard, this was [no longer reproducible](https://expensify.slack.com/archives/C035J5C9FAP/p1664387333060729), so I'm checking it off.
- `HeaderView Doesn't use onyx context context (I think it's also the case with SideBarLinks) It means onyx will send them another copy of personalDetails as far as I know` - nobody is assigned to this one, but there have been a few investigations into more low-level Onyx improvements, particularly by @marcaaron. I like the idea of trying to dynamically generate Onyx contexts within `withOnyx` so that we can use the context API for all subscribers universally.

**Comment by marcaaron** [comment] 2022-10-06 20:56
@roryabraham In my [PR to start using the modern "drawer" navigator](https://github.com/Expensify/App/pull/11550) I refactor the `HeaderView` a little so that the props are already available and passed via the `ReportScreen` - just minimizes a connection or two. I think a context based solution would be interesting though but had trouble thinking of how it would work.

**Comment by roryabraham** [comment] 2022-10-06 21:31
> In my https://github.com/Expensify/App/pull/11550 I refactor the HeaderView a little so that the props are already available and passed via the ReportScreen - just minimizes a connection or two.

Yeah, we could probably extract that change out of the drawer PR because it's not directly related AFAICT?

**Comment by marcaaron** [comment] 2022-10-06 21:42
Could do that yep

**Comment by hannojg** [comment] 2022-10-08 16:07
I'd add this PR as well:

https://github.com/Expensify/App/pull/11684

The reason for investigation was this described issue: https://expensify.slack.com/archives/C035J5C9FAP/p1664523169910029?thread_ts=1664522847.768359&cid=C035J5C9FAP

**Comment by roryabraham** [comment] 2022-10-18 00:48
Put up [this PR](https://github.com/Expensify/App/pull/11945) to glean the performance benefits from recent upgrades made in Onyx.

**Comment by roryabraham** [comment] 2022-10-20 00:02
Removing https://github.com/Expensify/App/issues/4656 and instead replacing it with https://github.com/Expensify/App/issues/11997, which will provide us with clear metrics that we can point to when we want to know if we need to improve. The deliverables there are more clear and should help align us on how to make performance improvements.

**Comment by JmillsExpensify** [comment] 2022-10-25 11:21
Added the issue for the comment box freezing the app following quick typing.

**Comment by roryabraham** [comment] 2022-10-31 16:21
- https://github.com/Expensify/App/issues/10792 – on HOLD
- https://github.com/Expensify/App/issues/10793 – @Szymon20000 will be meeting with the SQLite team sometime this week to investigate potential inefficiencies in the underlying SQLite implementation of quick-sqlite
- https://github.com/Expensify/App/issues/11711 – @AndrewGable and @hannojg could probably say more, but my summary is that the original E2E performance test suite worked well locally, but due to use of emulators in CI machines, was too variable/unreliable to be useful. Emulators had unpredictable and substantial variance in performance. Even with the larger GitHub Actions runners, performance of emulators was unreliable. Now @AndrewGable is working on setting up AWS Device Farm w/ real cloud devices to run E2E performance tests and @hannojg is migrating the test suite to Appium to interface with AWS Device Farm. Please correct me if any of that was inaccurate.
- https://github.com/Expensify/App/issues/11997 – No update really. We would need an internal infra volunteer to migrate graphs.expensify.com to make it public, so it's possible we'll use some other service to create a separate set of public graphs. Maybe host w/ GitHub Pages for simplicity
- https://github.com/Expensify/App/issues/8503 – We've been making steady progress on this. It's also worth noting that some [recent benchmarks](https://github.com/reactwg/react-native-new-architecture/discussions/85) have raised some concerns about the performance of Fabric. The only example I've seen of a Fabric-enabled app is rn-tester, and it's palpably faster and more responsive with Fabric enabled. We will have to see if that's really the case for our app. We'll still do this migration at some point, but it's possible that more work is required in the upstream to get better performance "out of the box" on Fabric. Long-term, when React 18 is enabled in react-native-web, that should open up new opportunities for better performance as well, and we won't be able to do that w/o Fabric enabled.
- https://github.com/Expensify/App/issues/11321 – [This PR](https://github.com/Expensify/App/pull/11684) has been in review for 3 weeks, let's work to get that one merged this week!

**Comment by roryabraham** [comment] 2022-11-08 17:30
- https://github.com/Expensify/App/issues/10793 – latest discussion with @Szymon20000 [here](https://expensify.slack.com/archives/C035J5C9FAP/p1667503389141599)
- https://github.com/Expensify/App/issues/8503 – progress here seems stalled. Maybe we should pass this off so that @hannojg can focus on:
    - https://github.com/Expensify/App/issues/11711
    - https://github.com/Expensify/App/issues/11321
    - https://github.com/Expensify/App/issues/11997
- Let's see if we can get [@thomas-coldwell](https://github.com/thomas-coldwell) engaged in:
    - https://github.com/Expensify/App/issues/10894
    - https://github.com/Expensify/App/issues/10792
 
For https://github.com/necolas/react-native-web/issues/1019, maybe we can get @kidroca working on that piece?

Also @janicduplessis can we work on upstreaming the bidirectional scrolling features in FlatList?

**Comment by JmillsExpensify** [comment] 2022-11-15 03:59
Most of what's written above is still valid this week. I also also linked the tracking issue for [KeyboardAvoidingView](https://github.com/Expensify/App/issues/10273), as we have about 9 bugs there that have gone stale over the last week.

**Comment by roryabraham** [comment] 2022-11-16 19:56
- @janicduplessis has been making progress getting VirtualizedList code merged upstream
- @Szymon20000 has been mostly focused on https://github.com/Expensify/App/issues/10793, reviews underway
- @hannojg has a few open PRs up for performance improvements, but the Fabric upgrade has been passed off

**Comment by roryabraham** [comment] 2022-11-28 19:42
Removing https://github.com/Expensify/App/issues/8503 because it's being handled by SWM now

**Comment by roryabraham** [comment] 2022-11-28 19:44
Removing https://github.com/Expensify/App/issues/10273 because it was primarily done by @tgolen, not Margelo

**Comment by roryabraham** [comment] 2022-11-28 19:47
Chatted with @JmillsExpensify – this issue is prettymuch serving the same purpose as Margelo's [regular slack updates](https://expensify.slack.com/archives/C035J5C9FAP/p1669654769867739) here. Rather than maintaining these multiple sources of truth, I'm actually going to just close this issue for now.

**Closed by roryabraham** 2022-11-28 19:47 UTC
Labels: Weekly, Bug
