### ISSUE TITLE
[$1000] Web - Hitting Enter while login loading calls API again.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23428] opened 2023-07-23 18:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Login Form
2. Simulate slow network to observe the behaviour
3. Type one mail and hit enter
4. Change the mail speed & hit enter while previous login is loading.
5. Observe two API calls are going with two mail, also observe OTP form is also changes with the two different mail once OTP has been sent.

## Expected Result:
We shouldn't allow API Call or changing email while loading.

## Actual Result:
User is able to change the email as well as API calls are also going multiple time.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-26
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8f5546b0-9537-41f4-b976-292be651f21d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689948859928519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01490293c7802bf825</li>
        <li>Upwork Job ID: 1683899063524028416</li>
        <li>Last Price Increase: 2023-08-01</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 25903420</li>
<li>b4s36t4 | Reporter | 25903423</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-07-23 18:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hitting Enter while login loading calls API again.
### What is the root cause of that problem?

RCA for this issue is here https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/signin/LoginForm.js#L185-L203.

For the `TextInput` we're never giving any disabled state so that it is listening for keyboard events which means whenever we hit `Enter` it calls `handleKeyDown` event which calls `submit` function.

Because of this whenever we hit enter API call is happening again. 

### What changes do you think we should make in order to solve the problem?

We should handle `disabled` state for the `TextInput` while `login` is going.

```jsx
disabled={props.account.isLoading && props.account.loadingForm === CONST.FORMS.LOGIN_FORM}
```


### What alternative solutions did you explore? (Optional)
NA

**Comment by CortneyOfstad** [comment] 2023-07-26 14:42
@eVoloshchak Thoughts on the proposal above?

**Comment by CortneyOfstad** [comment] 2023-07-28 16:06
Bump @eVoloshchak ^^^

**Comment by joh42** [comment] 2023-07-28 17:04
# Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is possible to submit the login form more than once while it is loading.
### What is the root cause of that problem?
We do not prevent the login form from being submitted more than once.
### What changes do you think we should make in order to solve the problem?
I suggest that we add a condition to `validateAndSubmitForm`, checking if a submission is already in progress, and if so returning. Likely looking something like:
```
const isLoading = props.account.isLoading && props.account.loadingForm === CONST.FORMS.LOGIN_FORM;
if (isLoading) {
    return;
}
```

In my opinion this should be added to both the [LoginForm](https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/signin/LoginForm.js) and the [ValidateCodeForm](https://github.com/Expensify/App/blob/a97ca9b2092c56e7d237e13e56a649cf08993090/src/pages/signin/ValidateCodeForm/BaseValidateCodeForm.js)
### What alternative solutions did you explore? (Optional)

**Comment by saalimzafar** [comment] 2023-07-30 21:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Hitting Enter while login  calls API again.
### What is the root cause of that problem?
In LoginForm.js file
const [formError, setFormError] = useState(false);
The setFormError is always false because of this
### What changes do you think we should make in order to solve the problem?
const [formError, setFormError] = useState(null);
### What alternative solutions did you explore? (Optional)
NA

**Comment by CortneyOfstad** [comment] 2023-07-31 13:25
@eVoloshchak thoughts on the proposals above? ^^^^

**Comment by b4s36t4** [comment] 2023-07-31 13:38
@CortneyOfstad maybe he's not available?

**Comment by eVoloshchak** [comment] 2023-08-01 16:24
@b4s36t4's [proposal](https://github.com/Expensify/App/issues/23428#issuecomment-1646921122) looks good to me

I don't think we should put the early return in `validateAndSubmitForm`, there would be no indication to the user that the network request is in progress/button isn't active. While setting disabled prop to false achieves exactly that

🎀👀🎀 C+ reviewed!

**Comment by CortneyOfstad** [comment] 2023-08-01 20:04
Heading OoO until 8/14 so reassigning BZ to keep an eye on it while I'm out 👍

**Comment by pecanoro** [comment] 2023-08-02 11:12
Did any of you try to reproduce this? I have been trying and it does not call the API multiple times with the reproduction steps in the description...

**Comment by pecanoro** [comment] 2023-08-02 11:13
@CortneyOfstad Just checking in if you follow the steps [here](https://github.com/Expensify/App/issues/23428#issuecomment-1646920949)?

**Comment by b4s36t4** [comment] 2023-08-02 12:42
[Screencast from 02-08-23 06:05:54 PM IST.webm](https://github.com/Expensify/App/assets/59088937/36c335a7-7711-4b25-a986-3e34a0a40774)

@pecanoro it is still re-producable. To re-produce this network should low so that you'll have time to click on the input and type a new email.

Steps to create a slow simulation network.
1. Open Network tab in devtools, follow the image.
![image](https://github.com/Expensify/App/assets/59088937/6224dad1-9929-40ad-b7c4-68279a93b3db)

2. Click on Custom, give it network a speed, maybe 10kb/s? and set latency high maybe `10000` should work.

Now try the steps I have said above or see the attached video here. I re-produced it latest version `new.expensify.com`.

**Comment by pecanoro** [comment] 2023-08-02 12:48
@b4s36t4 You forgot an important detail in your reproduction steps, that you have to type a new email in order to trigger this 😄

**Comment by b4s36t4** [comment] 2023-08-02 12:52
ohh sorry, thanks for assigning.

**Comment by b4s36t4** [comment] 2023-08-03 17:11
@eVoloshchak @pecanoro Raised PR, Thanks.!

**Comment by joh42** [comment] 2023-08-13 11:02
FYI @eVoloshchak @pecanoro I just realized that this issue seems to be a dupe of https://github.com/Expensify/App/issues/22087

That issue was created before this one, but a proposal was selected here before one was selected in that issue. The PR for that issue has already been merged however https://github.com/Expensify/App/pull/24352

Tagging C+ and the internal engineer who are assigned to that issue @situchan @luacmartins

**Comment by situchan** [comment] 2023-08-13 12:37
The solution approved here will change the current behavior while logging in - text is not editable which raised [this concern](https://github.com/Expensify/App/pull/24122#issuecomment-1667924778).
So I think better to leave as is now, which means close PR.

**Comment by b4s36t4** [comment] 2023-08-13 12:40
@situchan that's a minor issue but enabling the input won't be a good UX. And I feel there is perfect RCA in that issue as well as mine(80%) is only correct from my side. 

Everybody's RCA is just we're not restricting the onsubmit while loading etc which is not a good RCA I feel. Even mine is not that good :)

**Comment by situchan** [comment] 2023-08-13 12:44
> that's a minor issue but enabling the input won't be a good UX

If so, we should apply this to all forms which involve loading button for consistency, not only login.

**Comment by b4s36t4** [comment] 2023-08-13 12:48
I have found the right RCA for the issue which is causing the API call again. here's the RCA.

https://reactnative.dev/docs/textinput#onsubmitediting As per the documentation `onPress` function get's called whenever we hit Enter.

https://github.com/Expensify/App/blob/dd0d98fa6868bba60e81bfdf66e5cdf7d2adaa37/src/components/Button/index.js#L175-L190 this snippet here is the issue.

For the first instance (no loading) `this.props.onPress` which will get's called so there's no bubbling which prevents calling `onSubmitEditing` callback. But since we're returning the event we're creating event bubbling which is the reason for calling `onSubmitEditing` callback and that's causing the multiple API calls.

For the solution all we have to do is `e.preventDefault()` inside the listener which does not create any further issues.

**Comment by situchan** [comment] 2023-08-13 12:53
@b4s36t4 did you check `validateSubmitShortcut`? FYI: https://github.com/Expensify/App/issues/22087#issuecomment-1645311815.

**Comment by b4s36t4** [comment] 2023-08-13 12:54
Ohh sorry missed it.

**Comment by pecanoro** [comment] 2023-08-15 13:59
This is unfortunate, I think we can just close the PR since it has been resolved. 

@CortneyOfstad  Can you start a thread internally in Slack to see which amounts are due for the work done?

**Comment by CortneyOfstad** [comment] 2023-08-16 14:17
@pecanoro Asked in #Bug-Zero [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1692195422285459) 👍

**Comment by CortneyOfstad** [comment] 2023-08-23 15:04
Alright, it was decided that because this was a duplicate, a change would be made to the pay. 

- The reporter does not receive payment, as this was a duplicate and therefore, already reported by someone else first.
- The Contributor and C+ did work on this, despite work also being done on the original GH, so it was decided by our team to pay out 75% of the bounty. This would be **$750**

@pecanoro are we ready to do they payment or is there anything that we need to wait for? TIA!

**Comment by pecanoro** [comment] 2023-08-25 00:32
@CortneyOfstad We are ready to go!

**Comment by CortneyOfstad** [comment] 2023-08-28 11:39
@b4s36t4 has been paid the $750 as the contributor 👍 

@eVoloshchak I've sent over the contract in Upwork — let me know as soon as you accept so I can get that paid and we can close this out 👍 

Thanks!

**Comment by eVoloshchak** [comment] 2023-08-28 17:39
@CortneyOfstad, thanks!
Requested the payment via NewDot instead

**Comment by JmillsExpensify** [comment] 2023-08-30 04:36
Reviewed the details for @eVoloshchak. $750 approved for payment based on the BZ summary.

**Comment by pecanoro** [comment] 2023-09-04 14:28
I am going to close it since it seems it was paid, if there are outstanding payments, please let us know!

**Closed by pecanoro** 2023-09-04 14:28 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
