### ISSUE TITLE
[$500] Not seeing Pay with PayPal.me while sending money reported by @thesahindia 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12292] opened 2022-10-31 01:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login with account A
2. Go to settings > Payments > Add payment method
3. Click on PayPal.me > Add Paypal account
4. Open another browser > Login with account B
5. Click on fab menu > Send money > Add amount
6. Select account A and proceed
7. Verify that you aren't seeing the Pay with PayPal.me option

## Expected Result:
You should see Pay with PayPal.me option

## Actual Result:
Pay with PayPal.me option doesn't show up

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.21-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198913924-35d19024-cdcf-4414-82b1-f80cf2fed8e8.mov

https://user-images.githubusercontent.com/43996225/198913931-320a2873-d6d4-4db0-9912-24219c49957d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @thesahindia 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667080931413899

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-11-01 15:11
Issue is reproducible. Thanks for the clear testing steps. 

![Screenshot 2022-11-01 at 09 10 41](https://user-images.githubusercontent.com/1127863/199267217-6c54cae4-74f3-44b0-b4f0-4bc47c80dd8d.png)

**Comment by marcochavezf** [comment] 2022-11-01 17:36
Yeah, the Paypal data is saved locally in Onyx so the issue should be in the NewDot codebase. I also believe that could be related to the latest refactors.

**Comment by JmillsExpensify** [comment] 2022-11-01 17:52
Ok cool! cc @vitHoracek did we introduce a regression with `PayIOU`?

**Comment by JmillsExpensify** [comment] 2022-11-01 17:52
In the meantime, I think this is important to fix so I'm raised the starting price to $500. Upwork job is here: https://www.upwork.com/jobs/~013ae3656e861b31b5.

**Comment by mountiny** [comment] 2022-11-01 20:45
@JmillsExpensify we haven't merged anything App/Web for payIOU yet so it must be coming from some other changes.

**Comment by JmillsExpensify** [comment] 2022-11-01 23:00
Thanks for the confirmation!

**Comment by JmillsExpensify** [comment] 2022-11-03 03:56
Still waiting for proposals.

**Comment by drkcod3** [comment] 2022-11-03 07:50
@JmillsExpensify

I am really excited for having come across your proposal. I will give this my utmost effort and want to get started right away. I have downloaded the source code and followed the instructions of the *README* file. All I got is a blank white screen after the page takes ages to load.

I would like some help running the code locally on my machine for the sake of saving time and doing some troubleshooting.

**Comment by mountiny** [comment] 2022-11-03 09:02
@drkcod3 Hello! Glad to see you around! For help related to running the App, it is definitely best to reach out in the Slack channel. If you are not member of the channel yet, please follow these guidelines: https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#asking-questions and also I recommend to familiarize yourself with that entire doc as it describes how to contribute to this repository.

Let us know if you need any more help here. I am sure that your issues will be resolved quickly in the Slack channel!

**Comment by drkcod3** [comment] 2022-11-05 12:23
Bump. I haven't been invited to the slack channel to get help fixing basic babel issues so I can get to fixing this issue. 

@laurenreidexpensify takes ages to reply :)

**Comment by ronhillel** [comment] 2022-11-05 21:12
Where I can see the backend requests requirements and documentation?

**Comment by drkcod3** [comment] 2022-11-06 10:47
I did manage to get a dirty temporary fix. I do believe there is a cleaner way of handling these errors. Perhaps the babel config? I would like some enlightenment rather than messing around with configuration files especially webpack and babel :) 

https://stackoverflow.com/a/74335051/20431420

![image](https://user-images.githubusercontent.com/96230190/200166384-6fe34732-83c4-4158-970e-2d0e94ab0146.png)

**Comment by AndreasBBS** [comment] 2022-11-06 18:18
@drkcod3 From what I've been able to investigate it looks to me that `API.write('AddPaypalMeAddress', ...)` is not adding the PayPal address to the users PersonalDetails. The App tries to fetch the PayPal address from the PersonalDetails object but the value for the key `payPalMeAddress` is always coming up as empty string.
How can I see the API code and run my own local API?
If I hardcode the `payPalMeAddress` in PersonalDetails `_.map` function the button appears and redirects to the hardcoded PayPal address.

**Comment by mananjadhav** [comment] 2022-11-07 06:25
@marcochavezf @JmillsExpensify I think this is a duplicate of https://github.com/Expensify/App/issues/12291. I recommend we close this one out.

@kavimuru Can you confirm?

Both the issues are related payment methods refresh.

**Comment by thesahindia** [comment] 2022-11-07 07:08
It's not a dupe. Are you seeing the Pay with PayPal option after refresh when following the steps in this issue?

**Comment by JmillsExpensify** [comment] 2022-11-08 05:55
Hmm, yeah I think this might be a dupe. Based on the reproduction steps in the linked issue, the paypal/payment option is not seen after a refresh.

**Comment by mountiny** [comment] 2022-11-08 11:12
Let me put this one on hold for https://github.com/Expensify/App/issues/12291, I think they are similar enough and proposal was accepted there, we can retest this after that PR is merged.

**Comment by AndreasBBS** [comment] 2022-11-08 14:35
@mobilify I just tested the changes proposed in #12291 and it I didn't find that it affects this particular bug. It seems to fix the bug in #12291 correctly but not this one. The PayPal information for the Modal on #12291 comes from ONYXKEYS.COLLECTION.REPORT_IOUS (iouReport). In this Modal the PayPal information is fetched from ONYXKEYS.PERSONAL_DETAILS (personalDetails).

In #12291 the information was correctly added to Onyx, it was just a matter of how the component fetched that info when rendering. In this case the information is not there, even if you refresh it does not get fixed. And as I mentioned above:

> @mountiny From what I've been able to investigate it looks to me that `API.write('AddPaypalMeAddress', ...)` is not adding the PayPal address to the users PersonalDetails. The App tries to fetch the PayPal address from the PersonalDetails object but the value for the key `payPalMeAddress` is always coming up as empty string. How can I see the API code and run my own local API? If I hardcode the `payPalMeAddress` in PersonalDetails `_.map` function the button appears and redirects to the hardcoded PayPal address.

if you hardcode the PayPal address into the personalDetails array, the PayPal option shows up as intended.

This to say, I don't think this two issues are related, applying the solution of the other issue doesn't seem to affect this one. I still believe my assessment is correct. I don't know how I could demonstrate the fix though because I cannot affect the implementation of API.write('AppPaypalMeAddress', ...) to make it add the PayPal address into the users PersonalDetails.

**Comment by mountiny** [comment] 2022-11-08 16:11
@AndreasBBS Thanks fro the write up.

I will look into this internally once I get time for this to confirm what is going on with the API. A quick look I did just now shows we should be adding the paypal me address to the personal details so there must be some gremlins. Gonna update the issue here later.

**Comment by JmillsExpensify** [comment] 2022-11-08 17:15
Great write-up @AndreasBBS. Thank you! I like @vitHoracek's plan, let's investigate the API layer and then come back to align on the appropriate fix (might be in more than one repo).

**Comment by mountiny** [comment] 2022-11-11 09:24
Will try to look into this today

**Comment by mountiny** [comment] 2022-11-11 16:32
Testing locally I think this needs to be internal. We have changed how the paypal address is saved and I guess something does not line up with where/how the data is saved and then it is not retrieved correctly.

**Comment by mountiny** [comment] 2022-11-11 16:32
Removing the hold. @marcochavezf would you have some time/ willingness to look into this next week?

**Comment by JmillsExpensify** [comment] 2022-11-11 19:15
Thanks for circling back on this one @vitHoracek. @marcochavezf let me know if next week isn't realistic and I can try to find someone else to look into it.

**Comment by marcochavezf** [comment] 2022-11-12 01:30
Sure, I'm going to give it a shot next week

**Comment by mountiny** [comment] 2022-11-14 23:05
Actually if you have not started, I will snatch this Bug since I have already did some investigation into this, it only makes sense (unless you have done some progress already @marcochavezf)

I will have to focus on one internal thing tomorrow but if time will allow I will continue investigating where this is breaking.

**Comment by marcochavezf** [comment] 2022-11-15 08:13
Hey @mountiny! Oh yeah I already did a bit of investigation and seems we're saving the PayPal address in the Onyx key `nvp_paypalMeAddress`, and I think we should retrieve it [here](https://github.com/Expensify/App/blob/376c3327bdc58e0fb15ff31fa7ebba819a680206/src/components/IOUConfirmationList.js#L304). I still need to do some testing, but if you think it's a different route you can take it :)

**Comment by mountiny** [comment] 2022-11-15 09:13
@marcochavezf Nice, I dont have any specific idea about this solution, I think I remember there might have been a new NVP we were saving this into at some point (_I think_) so just would be good to look into the usage between the payment list and the payPalMeAddress in personalDetails to make sure the concept we have now makes sense. 

I will unassign and leave this for ya since you already started 🙌

**Comment by JmillsExpensify** [comment] 2022-11-17 05:31
@marcochavezf circling back to confirm that you're on this issue this week?

**Comment by marcochavezf** [comment] 2022-11-17 22:00
>@marcochavezf circling back to confirm that you're on this issue this week?

Yup, I already created a PR, today I'm going to test it out and add the screenshots

**Comment by marcochavezf** [comment] 2022-11-18 05:03
After testing further, I realized the root issue exists in the backend. I created this [PR](https://github.com/Expensify/Web-Expensify/pull/35618) to fix it.

Related to the initial [PR](https://github.com/Expensify/App/pull/12845), we can close it since it doesn't fix the root issue, although I think we should remove the `ONYXKEYS.PAYPAL` in favor of `NVP_PAYPAL_ME_ADDRESS` since it's redundant in the code and could cause confusion and/or issues in the future. cc @mountiny

**Comment by mountiny** [comment] 2022-11-18 06:59
I definitely agree to come back to the previous simpler nvp, that made more sense imho even before. Thought there must be something wrong in the api, great work Marco!

Gonna review the prs, i would double check what was the reason why the new nvp shape was introduced so there is no hidden sideeffect down the line of reverting this change

**Comment by JmillsExpensify** [comment] 2022-11-18 08:02
Great work @marcochavezf @mountiny! This is also a reminder for me that we'll need to hire the issue reporter as well as C+ if they are involved in a review. I'll still hold on that part until the PR is merged and roles on this issue are clearer.

**Comment by AndreasBBS** [comment] 2022-11-18 19:28
@mountiny @mananjadhav @JmillsExpensify Good to see that my investigation bore fruit and that you're going ahead with my proposal to fix it from the backend. If you need something where I can lend a hand, let me know. Unfortunately, I don't have access to the backend code, otherwise I would have fixed it myself and spared your time. Great work everybody!

**Comment by mountiny** [comment] 2022-11-21 15:06
> Unfortunately, I don't have access to the backend code, otherwise I would have fixed it myself and spared your time. Great work everybody!

No problem, thank you very much for poking around!

We have increased the bounty for starting bugs to $1000 now! We would love if you could help us clean up our issues list, here you can find those without [accepted proposals yet](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22+NOT+hold+in%3Atitle+label%3ABug)!

**Comment by JmillsExpensify** [comment] 2022-11-22 06:18
Note for when this is merged: No C+ reviewed the linked PRs.

**Comment by JmillsExpensify** [comment] 2022-11-27 02:52
Just checked the linked PR and it's merged, right @marcochavezf? If so, I guess the GH automation failed here. 

@thesahindia can you apply to the Upwork job for reporting? https://www.upwork.com/jobs/~013ae3656e861b31b5

At that point we should be good to close this one out?

**Comment by thesahindia** [comment] 2022-11-27 07:02
Applied, thanks!

**Comment by JmillsExpensify** [comment] 2022-11-27 20:39
Great, offer sent! 

Also I just realized that while the Web PR is merged, the [App PR](https://github.com/Expensify/App/pull/12845) is still outstanding. False alarm on that front, this issue should remain open until that's done.

**Comment by mountiny** [comment] 2022-11-28 10:40
> I guess the GH automation failed here.

The PR was Web PR and by internal employee so at the moment it is not expected to comment I believe.

**Comment by marcochavezf** [comment] 2022-11-28 20:37
>The PR was Web PR and by internal employee so at the moment it is not expected to comment I believe.

Yeah the fix was in Web PR and it was already deployed to [production](https://github.com/Expensify/Web-Expensify/pull/35618#issuecomment-1323729058), so we can consider this one as done.

> the https://github.com/Expensify/App/pull/12845 is still outstanding

I'm going to close the other App PR atm to avoid confusion. There's a pending [cleanup](https://expensify.slack.com/archives/C01GTK53T8Q/p1669135155097129?thread_ts=1669028275.471049&cid=C01GTK53T8Q) for the Paypal address nvp (I still want to investigate if there's an advantage of using `paypal` Onyx key instead of `nvp_paypalMeAddress`), but since it's not a problem at the moment, I think it's better to address it after WAQ.

**Comment by JmillsExpensify** [comment] 2022-11-29 18:57
Ok gotcha. So @thesahindia has been paid out for reporting and the PR review was internal, so I'll close out the issue.

**Comment by JmillsExpensify** [comment] 2022-11-29 18:58
> There's a pending [cleanup](https://expensify.slack.com/archives/C01GTK53T8Q/p1669135155097129?thread_ts=1669028275.471049&cid=C01GTK53T8Q) for the Paypal address nvp (I still want to investigate if there's an advantage of using paypal Onyx key instead of nvp_paypalMeAddress), but since it's not a problem at the moment, I think it's better to address it after WAQ.

Do we have a GH issue for this yet? If not, we're going to forget so I recommend creating one and putting [HOLD WAQ] in the title.

**Closed by JmillsExpensify** 2022-11-29 18:58 UTC
Labels: Reviewing, Daily, Internal, Bug
