### ISSUE TITLE
mWeb - VBA -  Address suggestion not displayed for company info

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#5724] opened 2021-10-08 03:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when executing the PR #5643 
## Action Performed:
1. Launch the URL and login
2. Click get started in workspace to add bank account
3. In the company information page enter random number in the company address field(42 in this case)

## Expected Result:
Address suggestion displayed
## Actual Result:
No address suggestion displayed
## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- Mobile Web

**Version Number:** 1.1.7.0
**Reproducible in staging?:** yes
**Reproducible in production?:** Feature not available
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img src="https://user-images.githubusercontent.com/43996225/136494528-56af17d8-94e4-42a4-bad6-f1e03396f91f.png" width="40%"> <img src="https://user-images.githubusercontent.com/43996225/136494538-ddfd8d58-8b11-41d1-87ca-be6e871e6fca.png" width="40%">

https://user-images.githubusercontent.com/43996225/136494560-31780125-3bb2-4e19-92d3-40cb8bd72f91.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Jag96** [comment] 2021-10-08 03:47
@Luke9389 any ideas on this one?

**Comment by Luke9389** [comment] 2021-10-08 17:49
Hmm, this should be addressed by [this PR](https://github.com/Expensify/Web-Expensify/pull/32076#issuecomment-938068404) which is on staging. I wonder if this is sending the request to the production API. 

Let's wait for that PR I just linked to hit production to see if this fixes itself.

**Comment by Luke9389** [comment] 2021-10-08 19:18
Resolved that the above suggestion is indeed the cause of the issue here: https://expensify.slack.com/archives/C07J32337/p1633718444462700

**Closed** 2021-10-08 19:30 UTC
Labels: DeployBlockerCash, Engineering, Hourly
