### ISSUE TITLE
[$500] IOU - Incorrect total amount shown when deleting money request in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26054] opened 2023-08-28 01:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Turn offline mode on
3. Click on the plus sign and select "Request Money".
4. Enter the desired amount and email address for the money request
5. Open IOU report details and edit the amount to a smaller amount than the one in step 4
6. Click on the three dots and delete the request
7. Go back to IOU report and observe that the difference of the two amounts entered is shown in total rather than 0

## Expected Result:
0 should be shown in total amount

## Actual Result:
A difference of the initial amount and edited amount is shown as total

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/28aed690-313d-4168-b6e0-7067a454bac1

https://github.com/Expensify/App/assets/78819774/0b17ffac-11db-4864-84dd-ce2b6069b0ed

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692445455325269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0140d719da85b979b3</li>
        <li>Upwork Job ID: 1697022453349801984</li>
        <li>Last Price Increase: 2023-08-30</li>
    </ul>
</details>

**Comment by adelekennedy** [comment] 2023-08-30 23:04
🐛 let's make it external

**Comment by im-adithya** [comment] 2023-08-31 03:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect total amounts shown after editing invoices

### What is the root cause of that problem?
Logic is missing in IOU due to which the total amount of `iouReport` is not changing

### What changes do you think we should make in order to solve the problem?
Add the required code [here](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L980) to fill step 3

### What alternative solutions did you explore? (Optional)
--

## Working Demo (Implemented already, waiting for assignment)
https://github.com/Expensify/App/assets/64399555/ccee5984-4107-4801-8b9e-fff4a673f4c3

**Comment by mananjadhav** [comment] 2023-09-01 05:53
@im-adithya Can you please explain/share some details on how are you planning to get the total? Which objects/properties will you use to update?

**Comment by im-adithya** [comment] 2023-09-01 06:14
Hey @mananjadhav, I first added this utils function in [IOUUtils.js](https://github.com/Expensify/App/blob/main/src/libs/IOUUtils.js)
```js
function editIOUTotal(iouReport, initialTransaction, updatedTransaction, isExpenseReport = false) {
  if (initialTransaction.currency !== updatedTransaction.currency) {
    return iouReport;
  }

  const initialAmount = TransactionUtils.getAmount(initialTransaction, false);
  const updatedAmount = TransactionUtils.getAmount(updatedTransaction, false);

  // Make a copy so we don't mutate the original object
  const iouReportUpdate = {...iouReport};

  iouReportUpdate.total += !isExpenseReport ? -initialAmount : initialAmount;
  iouReportUpdate.total += !isExpenseReport ? updatedAmount : -updatedAmount;

  iouReportUpdate.hasOutstandingIOU = iouReportUpdate.total !== 0;

  return iouReportUpdate;
}
```
And then used this to fill [step 3](https://github.com/Expensify/App/blob/main/src/libs/actions/IOU.js#L980) mentioned above to update the IOUReport and then also updated the message "xxx owes $yyy " using the `reportPreviewAction` (fetched from `getReportPreviewAction` using `iouReport.chatReportID`)

And finally update the optimistic, success and failure data which are used while making the API call.

That fixed the issue (both while request amounts from others (+) and while requesting in own workspace (-)) as in the demo.

Let me know if there are any changes, happy to tweak the solution as per the requirement!

**Comment by im-adithya** [comment] 2023-09-01 06:24
Also, this error also persists in online mode too, not just offline!

Would like to request if the bounty can be raised as this is more critical than [tooltips issue](https://github.com/Expensify/App/issues/26002) (an example) 🙏

**Comment by im-adithya** [comment] 2023-09-01 13:29
Yes we can do both, I had the initialTransaction and updatedTransaction readily available in the above lines from Step 1 and 2 respectively so I thought of using them to keep it uniform like it's used here:
https://github.com/Expensify/App/blob/12a6f87f69e32c4861decdddb2624ede940258cc/src/libs/actions/IOU.js#L1114

Just to give more context on how the utils function is going to be used:
```js
const updatedIOUReport = IOUUtils.editIOUTotal(iouReport, transaction, updatedTransaction, isFromExpenseReport);
```

Initial Tx:
https://github.com/Expensify/App/blob/12a6f87f69e32c4861decdddb2624ede940258cc/src/libs/actions/IOU.js#L973

> Also what does updatedTransaction mean?

updated Tx:
https://github.com/Expensify/App/blob/12a6f87f69e32c4861decdddb2624ede940258cc/src/libs/actions/IOU.js#L979

and then we move forward to edit the message:
```js
    const reportPreviewAction = ReportActionsUtils.getReportPreviewAction(iouReport.chatReportID, iouReport.reportID);
    const updatedReportPreviewAction = {...reportPreviewAction};
    const messageText = Localize.translateLocal('iou.payerOwesAmount', {
        payer: updatedIOUReport.managerEmail,
        amount: CurrencyUtils.convertToDisplayString(updatedIOUReport.total, updatedIOUReport.currency),
    });
    updatedReportPreviewAction.message[0].text = messageText;
    updatedReportPreviewAction.message[0].html = messageText;
```

and then finally add `updatedIOUReport` and `updatedReportPreviewAction` in the optimistic data and `reportPreviewAction` in failure data (others are already there in success and failure data)

**Comment by im-adithya** [comment] 2023-09-01 13:32
> I think it is a fair price, but I will still leave this for the internal team to decide.

That definitely is a fair price individually, just wanted to bring up the comparison based on issue criticality/difficulty.

**Comment by mananjadhav** [comment] 2023-09-01 13:41
@im-adithya's [proposal](https://github.com/Expensify/App/issues/26054#issuecomment-1702222167) looks good to me.

🎀 👀 🎀 C+ reviewed.

**Comment by mananjadhav** [comment] 2023-09-01 13:42
> Would like to request if the bounty can be raised as this is more critical than

And @adelekennedy @yuwenmemon your thoughts on [this comment](https://github.com/Expensify/App/issues/26054#issuecomment-1702231313).

**Comment by mananjadhav** [comment] 2023-09-01 14:05
@im-adithya please don’t create the PR until you’re officially assigned the issue here on GH.

**Comment by im-adithya** [comment] 2023-09-01 14:07
Whoops sorry didn't know that! What to do now? Should I close it?

**Comment by mananjadhav** [comment] 2023-09-04 16:29
Let's wait for @yuwenmemon to review and assign you the issue.

**Comment by yuwenmemon** [comment] 2023-09-05 18:36
Yep, sorry for the delay I was out for a US holiday!

(also sorry for the label spam I clicked the wrong button 🤦

**Comment by im-adithya** [comment] 2023-09-06 05:00
@mananjadhav not opening a new PR as there's #26486 already

**Comment by mananjadhav** [comment] 2023-09-17 16:34
@yuwenmemon @adelekennedy The fix was merged with another [PR](https://github.com/Expensify/App/pull/25498), while I was OOO and this one got delayed.

IMO, @im-adithya is eligible for the full compensation on this one.

**Comment by yuwenmemon** [comment] 2023-09-19 02:05
Sounds good, thanks for letting us know @mananjadhav - I guess we'll just close this out then @adelekennedy?

**Closed** 2023-09-19 02:38 UTC
Labels: Reviewing, External, Weekly, Bug

**Comment by SofoniasN** [comment] 2023-09-19 03:46
@adelekennedy @mananjadhav Hey guys even though this was fixed by another PR, as it was a legitimate bug shouldnt i be eligible for reporter bonus?

**Comment by mananjadhav** [comment] 2023-09-19 14:57
@adelekennedy did you get to see my comment regarding compensation for @im-adithya?

**Comment by adelekennedy** [comment] 2023-09-20 05:45
Yes! 

### Payouts due:

Issue Reporter: $250 @SofoniasN (as this was a legit bug) Upwork
Contributor: $500 @im-adithya Upwork
Contributor+: $500 @mananjadhav (proposal reviews) NewDot

Eligible for 50% #urgency bonus? **N**

Upwork job is [here]().

**Comment by mananjadhav** [comment] 2023-09-20 05:47
Thanks @adelekennedy.

**Comment by adelekennedy** [comment] 2023-09-20 05:55
@SofoniasN @im-adithya will you apply [here](https://www.upwork.com/jobs/~0140d719da85b979b3)

**Comment by im-adithya** [comment] 2023-09-20 06:03
Thanks @adelekennedy, however it says `Only invited users can find, view and apply to the job`

**Comment by SofoniasN** [comment] 2023-09-20 11:47
Hey @adelekennedy since the upwork job link is private, i couldnt apply.

**Comment by JmillsExpensify** [comment] 2023-09-21 09:21
$500 payment approved for @mananjadhav based on BZ summary.

**Comment by adelekennedy** [comment] 2023-09-21 11:08
@SofoniasN @im-adithya I swear this is this Upwork bug when we re-use postings, try [this link?](https://www.upwork.com/jobs/~0140d719da85b979b3)

**Comment by im-adithya** [comment] 2023-09-21 11:09
Now it says `Access denied. This job is private. Only freelancers invited by client can view this job.`

**Comment by adelekennedy** [comment] 2023-09-21 11:12
I have refreshed it again - edited it and republished. If this doesn't work I will open a new job:https://www.upwork.com/jobs/~0140d719da85b979b3

**Comment by SofoniasN** [comment] 2023-09-21 11:13
Same here it still says private![Screenshot_2023-09-21-14-12-52-471.jpg](https://github.com/Expensify/App/assets/85386553/6e2dda13-2cd0-47f4-918e-f321bf2765dd)

**Comment by adelekennedy** [comment] 2023-09-21 11:15
Then this is an Upwork bug as I see it's public on my end 💀 I'm going to close this one and open a new one

**Comment by adelekennedy** [comment] 2023-09-21 11:17
🤞 @SofoniasN @im-adithya - I closed the original and created a [new job ](https://www.upwork.com/jobs/~015495e97bad8fe0d3)

**Comment by im-adithya** [comment] 2023-09-21 11:24
Done now! Thanks again @adelekennedy!

**Comment by SofoniasN** [comment] 2023-09-21 12:09
@adelekennedy works now. Offer accepted!

**Comment by adelekennedy** [comment] 2023-09-21 12:12
hired!

**Comment by SofoniasN** [comment] 2023-09-22 04:32
@adelekennedy offer accepted. Thank you!
