### ISSUE TITLE
[HOLD 296932][$1000]  Task - Mark as Done button is unavailable for the Policy admin user

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23407] opened 2023-07-22 19:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22851
## Action Performed:
1. Open Expensify as User A.
2. Go to any room.
3. Click on 'Assign Task,' fill in the task details, and share it in the room.
4. Open Expensify as Policy admin user , who is not the assignee, assignor
5. Try to use Mark as Done button

## Expected Result:
Policy admin user should be able to change Task's title, description and mark as done

## Actual Result:
The Policy admin user can' use Mark as done button (the button is greyed out) while it's possible to change Task's fields and set Checkbox

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/40a0f8f6-4c00-4e39-9d23-7e6595d69e9f

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01efe1be768b7b85bc</li>
        <li>Upwork Job ID: 1683545187614375936</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by KrAbhas** [comment] 2023-07-22 20:00
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Mark as Done button is unavailable for the Policy admin user

### What is the root cause of that problem?
In `TaskHeaderActionButton.js` only `Task.isTaskAssigneeOrTaskOwner(props.report, props.session.accountID)` is being check for enabling the button.

### What changes do you think we should make in order to solve the problem?
We should add a check for `isPolicyAdminUser` as well for keeping the button enabled.

### What alternative solutions did you explore? (Optional)
NA

**Comment by BhuvaneshPatil** [comment] 2023-07-22 22:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - Mark as Done button is unavailable for the Policy admin user

### What is the root cause of that problem?
We have added the check for disabling the `Button` in `TaskHeaderActionButton`

https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/components/TaskHeaderActionButton.js#L49

It restricts the button only enabled to task assignee and task creator, that's why 

### What changes do you think we should make in order to solve the problem?
We shall modify the check to disable button, we shall add another condition - enable if current user is policy admin or not.
Similar to what we have done here - 
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/components/ReportActionItem/TaskView.js#L54

the final condition here is - 
```
isDisabled={ReportUtils.isCanceledTaskReport(props.report) || !(PolicyUtils.isPolicyAdmin(policy) || Task.isTaskAssigneeOrTaskOwner(props.report, props.currentUserPersonalDetails.accountID))}
```

While the above two proposals mention the same root cause, and solution partially. Because there is no method `isPolicyAdminUser`. We have used above logic (in `TaskView`) to enable editing(perform actions) the task.


### What alternative solutions did you explore? (Optional)

**Comment by BhuvaneshPatil** [comment] 2023-07-24 19:49
@parasharrajat 
https://github.com/Expensify/App/issues/21579#issuecomment-1613759614

please have a look at this comment. I have raised a similar issue before.

**Comment by kevinksullivan** [comment] 2023-07-28 23:02
@parasharrajat meaning we should put this on hold for now?

**Comment by thienlnam** [comment] 2023-07-31 16:38
Yes let's please hold this issue - I have yet to make the corresponding App changes once I'm done with the back-end changes

**Comment by kevinksullivan** [comment] 2023-08-01 19:22
In other words we should close @thienlnam ?

**Comment by thienlnam** [comment] 2023-08-01 19:23
Yeah we can close this, basically a dupe

**Comment by kevinksullivan** [comment] 2023-08-01 19:54
sounds good

**Closed by kevinksullivan** 2023-08-01 19:54 UTC
Labels: Daily, Internal, Bug
