### ISSUE TITLE
[$500] Assign task - Completed/reopened task message is not copied in offline mode

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27558] opened 2023-09-15 19:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Turn offline mode on
3. Go to any chat with a task
4. Check or uncheck the completed check box
5. Long press the notifier message that appeared based on your action in step 5 and click on copy to clipboard
6. Go to composer and try pasting it, observe that the content can not be pasted

## Expected Result:
Content should be pasted

## Actual Result:
A copied to clipboard confirmation is shown but content is not pasted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-5

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/0e087dbc-f30c-4ba1-8bef-35f40261c447

https://github.com/Expensify/App/assets/115492554/dae8db87-522c-42ba-ad7c-787ba2398e94

**Expensify/Expensify Issue URL:**

**Issue reported by:** @sofoniasN

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693283250856049

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b56cf7afa052e5c6</li>
        <li>Upwork Job ID: 1702762921800577024</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-09-15 21:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy and paste is not working over the web.

### What is the root cause of that problem?
https://necolas.github.io/react-native-web/docs/clipboard/

This plugin is not properly supported over the web.

### What changes do you think we should make in order to solve the problem?
Update package with the one supporting both react native and web. e.g. use navigator.clipboard api over the web and use clipboard plugin for apps.

### What alternative solutions did you explore? (Optional)
clipboard.js supports the web

**Comment by ewanmellor** [comment] 2023-09-15 21:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Copy-and-paste through the context menu is broken for "completed task" and "reopened task" notifications.

### What is the root cause of that problem?

In `BaseReportActionContextMenu`, `type="REPORT_ACTION"` but `reportAction={}`. In `ContextMenuActions` this results in `shouldShow` returning true but the `onPress` handler does nothing.

The root cause assessment from @ayazalavi is incorrect.

### What changes do you think we should make in order to solve the problem?

1. Change the `ContextMenuAction` to handle the case where the action is unknown (the button should not be on the action toolbar if it won't do anything).
2. Pass the notification details through in this case, so that the message can be correctly copied.

**Comment by ewanmellor** [comment] 2023-09-15 21:09
Contributor details
Your Expensify account email: expensify@ewanmellor.org
Upwork Profile Link: https://www.upwork.com/freelancers/~01db74ce3e7227751d

**Comment by jliexpensify** [comment] 2023-09-16 00:46
Unassigning myself as Maddy was the first B0 member assigned.

**Comment by ayazalavi** [comment] 2023-09-16 13:48
@everyone Can you guys paste videos showing your solution working in android mobile web? I am pretty sure docs clearly says react-native-web clipboard is having issues over the web.

**Comment by jjcoffee** [comment] 2023-09-20 13:29
Can't repro this on latest main, I believe it was fixed in https://github.com/Expensify/App/pull/27119.

**Comment by SofoniasN** [comment] 2023-09-22 04:45
Hey @maddylewis as this was a legitimate bug, i think i should be eligible for reporter bonus even if it was fixed by another PR. TIA

**Comment by maddylewis** [comment] 2023-10-02 13:59
kk, i'll issue $50 reporting bonus to @SofoniasN, but this was fixed via https://github.com/Expensify/App/pull/27119. I'll close once payment is processed to the reporter.

**Comment by maddylewis** [comment] 2023-10-02 14:04
offer sent

**Comment by SofoniasN** [comment] 2023-10-02 15:06
Offer accepted

**Comment by maddylewis** [comment] 2023-10-04 20:49
paid!

**Closed by maddylewis** 2023-10-04 20:49 UTC
Labels: External, Daily, Help Wanted, Bug
