### ISSUE TITLE
[$500] IOS - Chat animation appear in black color for a moment when opening app

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33894] opened 2024-01-03 19:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Dot app
2. Background the app
3. Open New Dot app again

## Expected Result:
There should be no visual issues when open and reopen the app

## Actual Result:
Application background is deformed.
Chat animation appear in black color for a moment when opening app

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/725262aa-66bb-441d-a220-cfd6ae846c84)

https://github.com/Expensify/App/assets/93399543/3f2e3398-d2d5-43f1-95b2-ca251b6bc26e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dac69aea47e33988</li>
        <li>Upwork Job ID: 1742622078533795840</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-04 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The chat background image shows as a dark mode when reopening the app. This only happens if we select the device theme.

### What is the root cause of that problem?
This is a known old issue in [RN](https://www.github.com/facebook/react-native/issues/28525). The background image will show either the dark or light variant depending on the system theme.
https://github.com/Expensify/App/blob/3b424bba3dfd691990755ecec3be5eae1125abf9/src/components/ThemeIllustrationsProvider.tsx#L10-L16
https://github.com/Expensify/App/blob/d4c3e63956e9c14838592172c7e0e8596b0814cf/src/hooks/useThemePreference.ts#L12-L21

However, the system theme value is updated multiple times when putting the app in the background. 
<img width="202" alt="image" src="https://github.com/Expensify/App/assets/50919443/e1c238d1-0b45-4abf-8146-e7c3898cb5fb">

One of the [comments](https://www.github.com/facebook/react-native/issues/28525#issuecomment-907805294) from the linked issue mentions that when we put the app in the background, iOS is trying to take a snapshot of the app on both theme modes, so the system theme is updated multiple times.

If we reopen the app while the system mode is updated to dark mode, we will see the dark image background.

### What changes do you think we should make in order to solve the problem?

We can explore the workaround in the linked issue.

First option is to ignore the system theme changes if we are in the background.
```
const [isForeground, setIsForeground] = useState<Boolean>(true);

useEffect(() => {
    AppState.addEventListener('change', (state) => {
        setIsForeground(state === 'active');
    });
}, []);

useEffect(() => {
    ...
    if (!isForeground) return;
    if (theme === CONST.THEME.SYSTEM) {
        setThemePreference(systemTheme ?? CONST.THEME.FALLBACK);
    } else {
        setThemePreference(theme);
    }
}, [preferredThemeFromStorage, systemTheme, isForeground]);
```

### What alternative solutions did you explore? (Optional)
The second option is to debounce the the changes.
```
const setThemePreference = useDebounce(
    useCallback(_setThemePreference, []),
    200,
    {leading: false, trailing: true},
)
```

**Comment by situchan** [comment] 2024-01-08 16:24
I am not sure what the bug is exactly.
@bernhardoj would you elaborate?

**Comment by bernhardoj** [comment] 2024-01-09 03:29
The bug is the app switch between dark/light mode when you put it in the background and reopen it as shown in the video (0:21 - 0:22).

**Comment by mvtglobally** [comment] 2024-01-18 22:24
Issue not reproducible during KI retests. (First week)

**Comment by situchan** [comment] 2024-01-23 21:35
@kevinksullivan bump on https://github.com/Expensify/App/issues/33894#issuecomment-1887653372

**Comment by mvtglobally** [comment] 2024-01-30 04:54
Issue not reproducible during KI retests. (Second week)

**Comment by situchan** [comment] 2024-02-01 13:08
> @kevinksullivan bump on [#33894 (comment)](https://github.com/Expensify/App/issues/33894#issuecomment-1887653372)

^

**Comment by situchan** [comment] 2024-02-12 16:05
Not overdue

**Comment by situchan** [comment] 2024-02-19 15:28
^

**Comment by kevinksullivan** [comment] 2024-02-22 18:28
Sorry, missed closing this. No longer reproducible so I'm closing

**Closed by kevinksullivan** 2024-02-22 18:28 UTC
Labels: Daily, Internal, Overdue, Bug
