### ISSUE TITLE
[HOLD for payment 2024-11-29] [HOLD for payment 2024-11-20] [HOLD for payment 2024-11-13] [$250] Add a step that collects the magic code when adding a VBBA

### ISSUE THREAD

**Issue by trjExpensify** [Expensify/App#51166] opened 2024-10-21 09:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.51-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Applicable on all platforms
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @trjExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C07HPDRELLD/p1729255848407089?thread_ts=1729042472.964519&cid=C07HPDRELLD

## Action Performed:
1. Go to expensify.com > sign-up > choose "1-9" to be redirected to NewDot 
2. Complete the onboarding modal steps to have a workspace created.
3. Go to Settings > Workspaces > Click into the workspace created
4. Go to More features > Enable workflows 
5. Go to Workflows > Make or track payments > Connect bank account

## Expected Result:
**This is a feature request.** 

1. Neither the "Connect online with Plaid" or "Connect manually" option rows are greyed out 
2. There isn't a "Hold up! We need you to..." error message.
3. When clicking either of the option rows in 1 above, we send a magic code email to the user, and show this validate your account page to collect it:

<img width="219" alt="image" src="https://github.com/user-attachments/assets/545c0290-ff66-4e17-aa8f-fea8f72e2ec2">

## Actual Result:
1. Both option rows are greyed out 
2. There's an error message on the page which we've since deprecated elsewhere in favour of a better experience to fire off and collect a magic code. 

<img width="376" alt="image" src="https://github.com/user-attachments/assets/bd7eec8f-9cd7-4066-8c83-00fb694b879f">

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

In-line above. 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

CC: @shawnborton @mountiny 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021848301297798537201</li>
        <li>Upwork Job ID: 1848301297798537201</li>
        <li>Last Price Increase: 2024-10-21</li>
<li>Automatic offers: </li>
<ul>
<li>shahinyan11 | Contributor | 104639697</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by shahinyan11** [comment] 2024-10-21 10:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a step that collects the magic code when adding a VBBA
### What is the root cause of that problem?
New feature. Currently we have another implementation
### What changes do you think we should make in order to solve the problem?
1. Remove [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L167C21-L167C72) line
2. Use the logic of [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/components/ValidateAccountMessage.tsx#L44C30-L52C22) callback in [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L158C33-L158C40) and [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L142C33-L142C40) callbacks 

### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-21 10:51
## Proposal
[Updated](https://github.com/Expensify/App/issues/51166#issuecomment-2426241932)

**Comment by shahinyan11** [comment] 2024-10-21 10:53
## Proposal
[Updated](https://github.com/Expensify/App/issues/51166#issuecomment-2426241932)

**Comment by trjExpensify** [comment] 2024-10-21 13:16
CC: @mountiny for eyes on this as I believe you've been involved in other flows that introduced it.

Looking at the POC video, it overall looks good. My only question is whether we should continue them on in the flow rather than dropping them back on the same page where they have to click the button again. @shawnborton, whatcha' think?

**Comment by shawnborton** [comment] 2024-10-21 13:17
I would say continue them down the path rather than bring them back to the prior step. Thoughts?

**Comment by shahinyan11** [comment] 2024-10-21 16:03
Edited by **proposal-police**: This proposal was **edited** at 2024-10-21 10:18:29 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a step that collects the magic code when adding a VBBA
### What is the root cause of that problem?
New feature. Currently we have another implementation
### What changes do you think we should make in order to solve the problem?
1. Add one more optional param for `SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute`. E.g `bankAccountSubStep`.  To do that update [this](https://github.com/Expensify/App/blob/b176976a5e57367ffd5ecb6286421907f725ce0b/src/ROUTES.ts#L156C71-L156C158) code to below
```
getRoute: (backTo?: string, bankAccountSubStep?: string) => getUrlWithBackToParam(`settings/wallet/verify?bankAccountSubStep=${bankAccountSubStep}`, backTo)}
```
2. Add bellow function in [BankAccountStep](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L92) component
```
const validateAccount = useCallback((bankAccountSubStep: string)=>{
    User.requestValidateCodeAction()
    Navigation.navigate(ROUTES.SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute(Navigation.getActiveRoute(), bankAccountSubStep));
}, [])
```
3. Remove [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L167C21-L167C72) line
4. Remove following check `!account?.validated` for disabling `MenuItem` components. See [here](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L141C64-L141C84) and [here](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L157C43-L157C62)
5. Update [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L158C33-L158C40) callback to below
```
() => {
    if (!!isPlaidDisabled) {
        return;
    }
    if (!account?.validated) {
        validateAccount(CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID)
        return;
    }
    removeExistingBankAccountDetails();
    BankAccounts.openPlaidView();
}
```
6.  and [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L142C33-L142C40) callbacks 
```
() => {
    if (!account?.validated) {
        validateAccount(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL)
        return;
    }
    removeExistingBankAccountDetails();
    BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL);
}
```
7. Update this [useEffect](https://github.com/Expensify/App/blob/b176976a5e57367ffd5ecb6286421907f725ce0b/src/pages/settings/Wallet/VerifyAccountPage.tsx#L53) to below below code in this line
```
if(bankAccountSubStep === CONST.BANK_ACCOUNT.SUBSTEP.MANUAL){
    BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL);
}else if (bankAccountSubStep === CONST.BANK_ACCOUNT.SUBSTEP.PLAID){
    BankAccounts.openPlaidView();
}
```

8. OPTIONAL. If the options should be grayed out but clickable we can add new `shouldGreyOut` prop to `MenuItem` to component. And update this conditional style  like below
```
( shouldGreyOut || (shouldGreyOutWhenDisabled && disabled) )  && styles.buttonOpacityDisabled,
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-10-21 16:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Add a step that collects the magic code when adding a VBBA
### What is the root cause of that problem?
New feature. Currently we have another implementation
### What changes do you think we should make in order to solve the problem?
1. Add one more optional param for `SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute`. E.g `bankAccountSubStep`.  To do that update [this](https://github.com/Expensify/App/blob/b176976a5e57367ffd5ecb6286421907f725ce0b/src/ROUTES.ts#L156C71-L156C158) code to below
```
getRoute: (backTo?: string, bankAccountSubStep?: string) => getUrlWithBackToParam(`settings/wallet/verify?bankAccountSubStep=${bankAccountSubStep}`, backTo)}
```
2. Add bellow function in [BankAccountStep](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L92) component
```
const validateAccount = useCallback((bankAccountSubStep: string)=>{
    User.requestValidateCodeAction()
    Navigation.navigate(ROUTES.SETTINGS_WALLET_VERIFY_ACCOUNT.getRoute(Navigation.getActiveRoute(), bankAccountSubStep));
}, [])
```
3. Remove [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L167C21-L167C72) line
4. Remove following check `!account?.validated` for disabling `MenuItem` components. See [here](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L141C64-L141C84) and [here](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L157C43-L157C62)
5. Update [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L158C33-L158C40) callback to below
```
() => {
    if (!!isPlaidDisabled) {
        return;
    }
    if (!account?.validated) {
        validateAccount(CONST.BANK_ACCOUNT.SETUP_TYPE.PLAID)
        return;
    }
    removeExistingBankAccountDetails();
    BankAccounts.openPlaidView();
}
```
6.  and [this](https://github.com/Expensify/App/blob/8ca4576f77efd6b5312309702feaeb0b49fab17e/src/pages/ReimbursementAccount/BankAccountStep.tsx#L142C33-L142C40) callbacks 
```
() => {
    if (!account?.validated) {
        validateAccount(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL)
        return;
    }
    removeExistingBankAccountDetails();
    BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL);
}
```
7. Update this [useEffect](https://github.com/Expensify/App/blob/b176976a5e57367ffd5ecb6286421907f725ce0b/src/pages/settings/Wallet/VerifyAccountPage.tsx#L53) to below below code in this line
```
if(bankAccountSubStep === CONST.BANK_ACCOUNT.SUBSTEP.MANUAL){
    BankAccounts.setBankAccountSubStep(CONST.BANK_ACCOUNT.SETUP_TYPE.MANUAL);
}else if (bankAccountSubStep === CONST.BANK_ACCOUNT.SUBSTEP.PLAID){
    BankAccounts.openPlaidView();
}
```

8. OPTIONAL. If the options should be grayed out but clickable we can add new `shouldGreyOut` prop to `MenuItem` to component. And update this conditional style  like below
```
( shouldGreyOut || (shouldGreyOutWhenDisabled && disabled) )  && styles.buttonOpacityDisabled,
```
### What alternative solutions did you explore? (Optional)

**Comment by trjExpensify** [comment] 2024-10-22 07:59
> I would say continue them down the path rather than bring them back to the prior step. Thoughts?

Agreed, I think that's best. 

@Pujan92 can you prioritise the proposal reviews today, please? Thanks!

**Comment by mountiny** [comment] 2024-10-22 10:08
Asking in Slack if we could reassign to the C+ who are familiar with this flow https://expensify.slack.com/archives/C02NK2DQWUX/p1729591653444039

**Comment by hungvu193** [comment] 2024-10-22 13:23
Thanks for proposals everyone. Please update your proposal to reuse our existing component called: ValidateCodeActionModal

Here’s example: https://github.com/Expensify/App/pull/49445

**Comment by shahinyan11** [comment] 2024-10-22 21:08
## Proposal
[Updated](https://github.com/Expensify/App/issues/51166#issuecomment-2427102709). Update the proposal to use `ValidateCodeActionModal`

**Comment by hungvu193** [comment] 2024-10-24 03:04
Reviewing today!

**Comment by hungvu193** [comment] 2024-10-24 16:42
Thanks for the proposals, everyone! We shouldn't allow users to continue the VBBA flow if they entered the wrong magic code. @shahinyan11 's [proposal here](https://github.com/Expensify/App/issues/51166#issuecomment-2427102709) looks good to me as it is the only proposal that handles both cases (valid and invalid magic code).
🎀 👀 🎀  C+ reviewed

**Comment by hungvu193** [comment] 2024-10-29 02:09
little bump @mountiny

**Comment by mountiny** [comment] 2024-10-29 07:54
Go ahead @shahinyan11

**Comment by shahinyan11** [comment] 2024-10-30 07:25
PR will be ready today

**Comment by trjExpensify** [comment] 2024-11-01 11:42
@shahinyan11 @hungvu193 I see the linked PR has merged, but the `Verify` button has floated to the top it seems reviewing the video here: https://github.com/Expensify/App/pull/51718#issuecomment-2451555738

It should be at the bottom like so: 

<img width="955" alt="image" src="https://github.com/user-attachments/assets/9cd7bc3c-2069-4d5f-99fa-8b2b53df6f50">

Can we fix that, please? (CC: @Expensify/design).

While we're here though, @anmurali noticed that the 2FA flow has that old error message in use: 

<img width="374" alt="image" src="https://github.com/user-attachments/assets/adcbfd5b-21bb-4d85-8b20-7acd6d80e16e">

So perhaps what we can do in a new PR is: 

- Add the `ValidateCodeActionModal` step to the 2FA flow to kill that existing message
- Fix the `Verify` button position. 

Happy to then pay $500 for this issue in its entirety.

**Comment by mountiny** [comment] 2024-11-01 11:46
forgot about the button position, you are right. this should be a quick fix, though @shahinyan11 @hungvu193, could you do that in one PR and then look into the 2FA section in another one for increased bounty?

**Comment by hungvu193** [comment] 2024-11-01 11:59
> forgot about the button position, you are right. this should be a quick fix, though @shahinyan11 @hungvu193, could you do that in one PR and then look into the 2FA section in another one for increased bounty?

Agreed

**Comment by shahinyan11** [comment] 2024-11-01 12:31
I started working on both and will share two PRs here.

**Comment by shahinyan11** [comment] 2024-11-01 12:45
@trjExpensify @mountiny Is the behavior in the video expected ?

https://github.com/user-attachments/assets/021279c1-560d-4440-9015-d9b045904e5a

**Comment by dannymcclain** [comment] 2024-11-01 13:01
@shahinyan11 The error should show just above the button instead of below it. Pretty sure Youssef ran into this in another spot and it was as simple as passing some prop to that error message or something simple like that. (Trying to avoid pinging him but we definitely can.)

**Comment by shahinyan11** [comment] 2024-11-01 14:14
@trjExpensify @mountiny Can I start working on 2FA ?

**Comment by trjExpensify** [comment] 2024-11-01 14:17
>The error should show just above the button instead of below it.

Agreed, that's just the standard forms error pattern to follow.

**Comment by trjExpensify** [comment] 2024-11-01 14:17
>@trjExpensify @mountiny Can I start working on 2FA ?

yeah, go for it.

**Comment by shahinyan11** [comment] 2024-11-01 14:19
> > @trjExpensify @mountiny Can I start working on 2FA ?
> 
> yeah, go for it.

Shouldn't a new issue be added for this to mention it in PR?

**Comment by trjExpensify** [comment] 2024-11-01 15:04
Yeah, I think it's fine to just use this one for ease. Please tag design in your PR though to take a look. 👍

**Comment by hungvu193** [comment] 2024-11-03 14:16
@shahinyan11 Can you combine your 2 PRs into one? I don't think we need 2 PRs.

**Comment by shahinyan11** [comment] 2024-11-04 12:43
I have created two PR-s following to this [comment](https://github.com/Expensify/App/issues/51166#issuecomment-2451745727)

**Comment by mountiny** [comment] 2024-11-04 23:13
@hungvu193 lets try to complete the review tomorrow

**Comment by shahinyan11** [comment] 2024-11-06 11:53
Hi @trjExpensify . I think we have one more place where `ValidateCodeActionModal` should be added

![Screenshot 2024-11-06 at 15 35 09](https://github.com/user-attachments/assets/78eeb6a3-ba39-40d7-a651-f0af84cde18e)

**Comment by shawnborton** [comment] 2024-11-06 15:13
Yeah agree... rather than showing it disabled, let's show it enabled and just have it launch the validate screen right?

**Comment by trjExpensify** [comment] 2024-11-06 17:15
> Yeah agree... rather than showing it disabled, let's show it enabled and just have it launch the validate screen right?

Yep! 

> Can I work on this with increased bounty?

Yep!

**Comment by shahinyan11** [comment] 2024-11-06 17:47
@trjExpensify Should I work on it as part of this issue ?

**Comment by shahinyan11** [comment] 2024-11-07 12:22
Hi @trjExpensify. I tried to add `ValidateCodeActionModal` in `Invoices` page but they are not suitable with each other 

![Screenshot 2024-11-07 at 14 11 44](https://github.com/user-attachments/assets/029f4131-5f46-4576-809d-a3b0f34f0554)

We should use another approach here. For example update [this](https://github.com/Expensify/App/blob/59c7a2e3e7d292ecf4a2f0c596d4618e1c221437/src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx#L167)  implementation as follows `BankAccounts.openPersonalBankAccountSetupView(undefined, isUserValidated)` . But there will also be some other changes needed

**Comment by mountiny** [comment] 2024-11-07 12:36
@shahinyan11 Can you write it down in a formal proposal please so we can look into what is needed? thanks!

**Comment by shahinyan11** [comment] 2024-11-07 14:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Always enable the `Add bank account` button in `WorkspaceInvoicesPage`  and display a `ValidateCodeActionModal ` modal when clicked for unverified users.
### What is the root cause of that problem?
New feature
### What changes do you think we should make in order to solve the problem?
Since `WorkspaceInvoicesPage` is the central pan screen, displaying `ValidateCodeActionModal` in it does not look as expected. The `ValidateCodeActionModal` should be opened in `RHP` screen.  And since we are currently using the [BankAccounts.openPersonalBankAccountSetupView](https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx#L167) method  and it already has an implementation of linked unverified users internally, I suggest  using it with bellow updates.

1. Remove this [line](https://github.com/Expensify/App/blob/eff7bffb673fb4c2f1d89b1c53a9bc1e6a799c1b/src/pages/settings/Wallet/PaymentMethodList.tsx#L368) to keep the button always enabled
2. Add bellow line in  [WorkspaceInvoiceVBASection](https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx#L34C10-L34C36) component
```
const [isUserValidated] = useOnyx(ONYXKEYS.USER, {selector: (user) => !!user?.validated});
```
3.  Update this [line](https://github.com/Expensify/App/blob/27b4786cceb9f44fad1f065b06ee56dc046a9716/src/pages/workspace/invoices/WorkspaceInvoiceVBASection.tsx#L167) in `WorkspaceInvoiceVBASection` component  to bellow 
```
BankAccounts.openPersonalBankAccountSetupView(undefined, isUserValidated);
```

4. Update [this](https://github.com/Expensify/App/blob/eff7bffb673fb4c2f1d89b1c53a9bc1e6a799c1b/src/pages/settings/Wallet/VerifyAccountPage.tsx#L60C1-L64C10) code to bellow since I think current implementation is not logical. Especially that we always `ROUTES.SETTINGS_WALLET`  even if `navigateBackTo` exists
```
if (!isUserValidated) {
    Navigation.goBack();
} else if (navigateBackTo) {
    Navigation.navigate(navigateBackTo);
}
```
### What alternative solutions did you explore? (Optional)

**Comment by hungvu193** [comment] 2024-11-07 15:45
Your proposal looks promising. I'll take a closer look tomorrow.

**Comment by hungvu193** [comment] 2024-11-08 09:04
@shahinyan11  Changes are looking good to me except the last step (Step 4), [this condition here](https://github.com/Expensify/App/blob/eff7bffb673fb4c2f1d89b1c53a9bc1e6a799c1b/src/pages/settings/Wallet/VerifyAccountPage.tsx#L60C1-L64C10) fixed a [DB](https://github.com/Expensify/App/issues/51276). Can you confirm that new condition won't break the existing flow?

**Comment by mountiny** [comment] 2024-11-08 16:22
Noting that the previous PR had a regression https://github.com/Expensify/App/issues/52045 so the reward should be partially taken down

**Comment by shahinyan11** [comment] 2024-11-08 20:16
> @shahinyan11 Changes are looking good to me except the last step (Step 4), [this condition here](https://github.com/Expensify/App/blob/eff7bffb673fb4c2f1d89b1c53a9bc1e6a799c1b/src/pages/settings/Wallet/VerifyAccountPage.tsx#L60C1-L64C10) fixed a [DB](https://github.com/Expensify/App/issues/51276). Can you confirm that new condition won't break the existing flow?

@hungvu193 I have tested and it works correct , But please test also yourself to verify

**Comment by hungvu193** [comment] 2024-11-09 06:38
OK, [your proposal](https://github.com/Expensify/App/issues/51166#issuecomment-2462367361) LGTM. Let's also add the testcase I mentioned above in your PR once you get approved from @mountiny.

**Comment by anmurali** [comment] 2024-11-11 17:09
@trjExpensify did we add this to the 2FA flow? 
![image](https://github.com/user-attachments/assets/614561f9-0cdd-45f3-84aa-119e92b70c4c)

**Comment by trjExpensify** [comment] 2024-11-11 17:14
Not yet, @hungvu193 is going to work on it though as part of this issue.

**Comment by hungvu193** [comment] 2024-11-12 04:00
I think we added it already.

https://github.com/user-attachments/assets/d8822f4f-451d-42e3-a8f3-325f6e5a5104

**Comment by hungvu193** [comment] 2024-11-12 07:13
Draft PR for adding ValidateActionCodeModal for `Invoices` page is [here](https://github.com/Expensify/App/pull/52356). I found some edge cases so I still need to work on it a little bit more 😄

**Comment by mountiny** [comment] 2024-11-12 11:21
@getusha do you want to be a c+ for the prs from @hungvu193 ?

**Comment by garrettmknight** [comment] 2024-12-02 18:04
@mountiny do we already have a regression test for this?

**Comment by mountiny** [comment] 2024-12-03 12:32
No, I do not think we have a test for this specific flow @hungvu193 @getusha could you complete the checklist here and propose a test to add please? thanks!

**Comment by getusha** [comment] 2024-12-04 13:23
> No, I do not think we have a test for this specific flow @hungvu193 @getusha could you complete the checklist here and propose a test to add please? thanks!

On it, thanks

**Comment by hungvu193** [comment] 2024-12-09 07:38
What's the payment summary for this one? I think we created 3 PRs for this issue.

**Comment by mountiny** [comment] 2024-12-09 08:36
@hungvu193 can you please list them out for simplicity?

@getusha can you then complete the regression tests for these prs please?

**Comment by getusha** [comment] 2024-12-09 09:36
**Regression Test Proposal**

**Invoices**
1. Sign in with an email that haven't been used to create an account and complete the onboarding
2. Create a new workspace
3. Go to More features > Enable workflows
4. Go to Invoices page and press Add bank account.
5. Verify that you're navigated to VerifyAccountPage and received a magic code to your email
6. Enter the code from the email
7. Verify you can continue the VBBA flow.

**Workflows**
1. Sign in with an email that haven't been used to create an account and complete the onboarding
2. Create a new workspace
3. Go to More features > Enable workflows
4.  Go to Workflows > Make or track payments > Connect bank account
5. Connect via Plaid
6. Verify that you're navigated to `Validate your account` page and received a magic code to your email
7. Navigate back and press Connect manually
8. Verify that you're navigated to `Validate your account` page and received a magic code to your email
9.  Enter the code from the email
10. Verify you can continue the VBBA flow.

**2FA Authentication**

1. Sign in with an email that haven't been used to create an account and complete the onboarding
2. Go to Settings > Security > Two-factor authentication
3. Verify that you're navigated to `Validate your account` page and received a magic code to your email
4. Enter the code from the email
5. Verify that you're navigated to `Two-factor authentication` page

Do we agree 👍 or 👎

**Comment by mountiny** [comment] 2024-12-09 10:32
@hungvu193 $750
@shahinyan11 $500
@getusha $250

is the summary

**Comment by garrettmknight** [comment] 2024-12-12 11:24
$750 approved for @hungvu193

**Closed** 2024-12-13 15:39 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
