### ISSUE TITLE
[Pay when ntdiary is setup for NewDot payments][$500] Multilevel tag - Tag name in RHP is not the same as the tag being clicked on

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#37783] opened 2024-03-05 19:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.47-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an employee of Collect workspace.
- The Collect workspace has dependant multilevel tag set up. (details [here ](https://expensify.slack.com/archives/C02NK2DQWUX/p1707942109760059?thread_ts=1707934406.857209&cid=C02NK2DQWUX)for how to setup)
- The multilevel tag is as follow:
First level: State
Second level: Region
1. Go to workspace chat.
2. Create a manual request with first and second level of tag.
3. Go to request details page.
4. Click the first level tag (State).
5. Click the second level tag (Region).

**Multi Level tag**
[Dependent - Multi Level tags NEW.csv](https://github.com/Expensify/App/files/14500433/Dependent.-.Multi.Level.tags.NEW.csv)

## Expected Result:
When the respective level tag is opened, the RHP will show the correct tag name (Step 4 and 5).

## Actual Result:
In Step 4, when opening RHP for first level tag (State), the tag name is the second level tag (Region).
In Step 5, when opening RHP for second level tag (Region), the tag name is the second level tag (State).

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/5037216d-6b46-4ca5-a108-24baaa5050b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fff45536696176bf</li>
        <li>Upwork Job ID: 1765168266617380864</li>
        <li>Last Price Increase: 2024-03-10</li>
<li>Automatic offers: </li>
<ul>
<li>ntdiary | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-03-05 19:40
@mallenexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kbecciv** [comment] 2024-03-05 19:41
We think that this bug might be related to #wave6-collect-submitters
CC @greg-schroeder

**Comment by mallenexpensify** [comment] 2024-03-06 00:14
@ntdiary can you help me here? I just spent ~20 mins trying to get the account setup to test. 
1. On a collect plan, on expensify.com, I invited my test account 
<img width="1102" alt="image" src="https://github.com/Expensify/App/assets/22508304/e0702fa4-5046-4893-a35c-3f1bf9479ee7">

2. On staging.new.expensify.com I'm logged in with my test account
<img width="1127" alt="image" src="https://github.com/Expensify/App/assets/22508304/daaca2fa-7484-45a2-80cd-268d0edeb22a">

3. I don't see the workspace in LHN as an option
<img width="502" alt="image" src="https://github.com/Expensify/App/assets/22508304/2f64a420-6947-40f6-bb23-f9eaad01ada1">

Anything you know of that I'm doing wrong?

**Comment by mallenexpensify** [comment] 2024-03-07 15:48
> I guess you forgot the [step 2](https://expensify.slack.com/archives/C02NK2DQWUX/p1707942109760059?thread_ts=1707934406.857209&cid=C02NK2DQWUX) (i.e., executing the js code)

Likely, thanks @ntdiary, are you able to reproduce? If so, do you think this can be external?

**Comment by mallenexpensify** [comment] 2024-03-10 23:21
Thx @ntdiary , added `External`

**Comment by NikkiWines** [comment] 2024-03-16 02:57
Sorry for the delay! Missed the assignment on this one. 

> @tienifr, Which field does tag id refer to? Is it something like these keys of Object (City/Region/State)? 😂
> Yes, it's the tag "key" and will be unique amongst tags, we use that naming in some places like [here](https://github.com/Expensify/App/blob/767bb3c0ffb5e47c559bd062b64678fa8538027c/src/libs/ModifiedExpenseMessage.ts#L197) (policyTagKey)

I'm not sure we should be ordering by those keys, especially since we already have the `orderWeight` attribute associated with the tags to indicate a relative order for the tags 🤔 Why not use that existing attribute?

**Comment by mountiny** [comment] 2024-03-18 13:19
I have demoted the linked issue as not a blocker. I will let Nikki handle the assigment here as there was a bit of discussion here already

**Comment by NikkiWines** [comment] 2024-03-19 05:47
Thanks for clarifying, @tienifr - I saw @ntdiary had approved the proposal. 

In Expensify Classic, the tag key that's core to your solution isn't necessarily unique, which is why I wasn't sure the solution was the best fit. On New Expensify, we do seem to strip out any duplicate tag keys (even if the sub-tags are distinct; not sure if that was by design or an oversight)

(Expense on Expensify Classic) 
<img width="400" alt="" src="https://github.com/Expensify/App/assets/16747822/468a4040-2085-4c8b-8938-c381e6aeb8af">

(Expense on New Expensify) 
<img width="300" alt="" src="https://github.com/Expensify/App/assets/16747822/724d6b1f-f04f-4c9a-86b0-c283c38f96ef">

We know that `orderWeight` will be unique (and it will also reflect the order in which the user wants to display the tags, though that's not super really important here) and (as you mentioned above) we already use it to sort the tagList. Because of that, I think ideally we'd use that as the id instead of relying on the `tagIndex`, which - as you identified - is unreliable. That'd be tricky to unwind though, given all the places we use the `tagIndex` currently, unfortunately.

However, assuming the tag key remains a unique identifier, your solution will work well, so it's a good option.

cc: @yuwen since you were involved in [this issue](https://github.com/Expensify/App/issues/33983) that introduced multiple tag levels to New Expensify and might have some perspective here.

**Comment by NikkiWines** [comment] 2024-03-20 20:38
Cool, chatted with @yuwenmemon some more about this, and looks like it's not particularly intentional that the tagList is being de-duped based on the top-level tag name. Also, ideally, we'd like to maintain the order of tags instead of sorting them alphabetically (which would be a byproduct of using the tag key to sort). So, let's use `orderWeight` to sort the tags whenever possible 🙇

**Comment by NikkiWines** [comment] 2024-03-23 02:47
Ah, yep - thanks for clarifying on the alphabetizing bit @tienifr, you're right.

However, since the current tag data formatting in Onyx isn't ideal (given we should be able to have tags with the same top-level name ) I still think we should go with using the `orderWeight` here to sort the tags. There's a decent chance we'll need to update how tags are stored to allow duplicate top-level tag names with distinct sub-tags in the future.

**Comment by NikkiWines** [comment] 2024-03-25 19:01
Perfect, looks good. Thanks @tienifr!

**Comment by mallenexpensify** [comment] 2024-04-19 23:43
[PR hit staging two days ago ](https://github.com/Expensify/App/pull/38988#issuecomment-2062991638)

**Comment by mallenexpensify** [comment] 2024-05-15 00:55
Eeeps, that damn `Reviewing` label wasn't removed and this didn't have 'awaiting payment', updated title AND it didn't go overdue. grrrrr......

Contributor: @tienifr paid $500 via Upwork
Contributor+: @ntdiary owed $500 via NewDot (he's in process of getting his account dialed in)

**Comment by mallenexpensify** [comment] 2024-05-15 00:56
@ntdiary can you update the BZ checklist plz?

**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@] Determine if we should create a regression test for this bug.
- [ ] [@] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@BZ] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by mallenexpensify** [comment] 2024-05-24 21:43
From [above](https://github.com/Expensify/App/issues/37783#issuecomment-2111393541)
> Contributor+: @ntdiary owed $500 via NewDot (he's in process of getting his account dialed in)

@ntdiary should be setup for NewDot payment now or very, very soon, so I'm going to close this and they can request payment once they're dialed in.

**Closed by mallenexpensify** 2024-05-24 21:43 UTC
Labels: External, Daily, Internal, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-06-07 03:47
$500 approved for @ntdiary
