### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Workspace  – Unable to save edited WS name using Enter key in newly created WS.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36923] opened 2024-02-20 16:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4327666
**Email or phone of affected tester (no customers):** applausetester+jp_e_category@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login with account that has at least 1 WS already created
3. Click on "choose Workspace" icon in top left 
4. Create a new WS by hitting "+" 
5. Edit WS name
6. Press Enter key to save the edited WS name

## Expected Result:
Edited WS name is saved

## Actual Result:
Nothing happens

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/47e2a6f1-d54f-4d7b-8bc9-3d60eee74e4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109e93e51a9b4c9ed</li>
        <li>Upwork Job ID: 1760135649726885888</li>
        <li>Last Price Increase: 2024-02-21</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2024-02-21 00:55
Can't reproduce on v1.4.43-5

https://github.com/Expensify/App/assets/59587260/e971405d-b6bc-4a43-90cb-0426398d5993

**Comment by mvtglobally** [comment] 2024-02-21 01:43
Unable to repro as well. Checking with reporter 

https://github.com/Expensify/App/assets/43995119/a182a9a3-b6fe-4349-8414-49471cf0aaeb

**Comment by mvtglobally** [comment] 2024-02-21 01:47
Able to reproduce. 
Issue is repro ONLY if you already have a WS created. If you are creating 1st one its not repro 

https://github.com/Expensify/App/assets/43995119/93c843db-14dd-43bf-a3d8-75556379216e

**Comment by kadiealexander** [comment] 2024-02-21 02:45
Still unable to repro:

https://github.com/Expensify/App/assets/59587260/4adfff4f-cef9-4930-be4f-32609ac7d730

**Comment by kadiealexander** [comment] 2024-02-21 02:50
Ah wait, I clicked the wrong "create a workspace" button. Was able to repro this.

**Comment by bernhardoj** [comment] 2024-02-21 03:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The enter key to save the workspace name doesn't work after creating a new workspace from the switcher page.

### What is the root cause of that problem?
Summary: The ENTER key is captured by another page.

When we press the new workspace from the switcher page, we will be navigated to the newly created workspace page (profile).
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/pages/WorkspaceSwitcherPage.tsx#L220-L222

We never pop the switcher page out from the nav stack, so it still exists on the stack. The workspace switcher page uses `OptionsSelector` to show the list which has its own ENTER key shortcut. We already disable the shortcut if the screen goes out of focus.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L124-L131

But we have another condition to subscribe it back.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L116-L122

`disableEnterShortcut` is set based on `focusin` and `focusout` listener. 
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L269-L280

When we press the new workspace button, `focusin` is triggered with the new workspace button as the active element. At this time, `disableEnterShortcut` is `true`. When the newly created workspace profile page opens, `focusout` is called, making `disableEnterShortcut` becomes `false`. Because `disableEnterShortcut` is `false`, the ENTER shortcut key is re-registered even though the screen is not focused anymore.

This only happens when you have at least 1 workspace because if you have none, the options selector won't be rendered.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/pages/WorkspaceSwitcherPage.tsx#L237-L238

### What changes do you think we should make in order to solve the problem?

We have an unsubs code for the `focusin` and `focusout`, but we never use it.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L290-L296

Unsubs them when the screen is out of focus.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L124-L131

```
if (this.props.isFocused) {
} else {
    this.unSubscribeActiveElement()
}
```

### What alternative solutions did you explore? (Optional)
Only do the subscription if `isFocused` is true.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/components/OptionsSelector/BaseOptionsSelector.js#L116-L122

OR

Pop the switcher page when creating a new workspace.
https://github.com/Expensify/App/blob/69890892b85c5352bfd9460f848aed5b8f989c9c/src/pages/WorkspaceSwitcherPage.tsx#L220-L222

I think we should do this regardless of the solution selected.

**Comment by getusha** [comment] 2024-02-21 18:05
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/36923#issuecomment-1955814703) (Main solution) looks good to me.  works well.
🎀 👀 🎀 C+ Reviewed!

**Comment by bernhardoj** [comment] 2024-02-22 05:46
PR is ready

cc: @getusha

**Comment by kadiealexander** [comment] 2024-03-12 03:32
@getusha don't forget the checklist!

**Comment by getusha** [comment] 2024-03-12 18:53
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x]  [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32464
- [x]  [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32464/files#r1521968148
- [x]  [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/a
- [x] [@getusha] Determine if we should create a regression test for this bug. **Yes**
- [x]  [@getusha] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Open workspace switcher page
2. Create new workspace (+ icon)
3. Open workspace profile page
4. Press on the workspace name
5. Edit the name
6. Press `enter/return`
7. Verify the name is saved and the page is closed

Do we agree 👍 or 👎

**Comment by kadiealexander** [comment] 2024-03-13 22:05
Payouts due:

- [ ] Contributor: $500 @bernhardoj
- [ ] Contributor+: $500 @getusha 

Upwork job is [here](https://www.upwork.com/jobs/~0109e93e51a9b4c9ed).

**Closed** 2024-03-13 22:06 UTC
Labels: External, Daily, Awaiting Payment, Bug
