### ISSUE TITLE
[$1000] Web - Reply in thread on messages in 'owes' or 'paid' money reports does not have 'From' link in header

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23492] opened 2023-07-24 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report and on any message, hover and click on reply in  thread
3. Observe in header, it displays 'From' link to parent thread
4. Request money from any user, in their report, open 'owes' report and add any message
5. Hover on message and click on reply in thread, observe that now it does not display 'From' link to parent thread in header

## Expected Result:
App should display 'From' link to parent thread in reply in thread report

## Actual Result:
 App does not display 'From' link to parent thread when we reply in thread to a message from 'owes' or 'paid' money reports

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/9627ba93-02ff-476b-b1b3-1515fdd663a3

https://github.com/Expensify/App/assets/93399543/296eb456-8aaa-4a20-a56c-334c5def16de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690170723345019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01de8189e72eaa3fa3</li>
        <li>Upwork Job ID: 1683899690476761088</li>
        <li>Last Price Increase: 2023-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 25913761</li>
<li>StevenKKC | Contributor | 25913762</li>
<li>dhanashree-sawant | Reporter | 25913764</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-24 17:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Reply in thread on messages in 'owes' or 'paid' money reports does not have 'From' link in header.

### What is the root cause of that problem?
`From` link is displayed by `parentNavigationSubtitle` in `HeaderView`.
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/pages/home/HeaderView.js#L93
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/pages/home/HeaderView.js#L192-L208

But `ReportUtils.getParentNavigationSubtitle` returns empty string for iou report and money request report.
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/libs/ReportUtils.js#L1251-L1262
https://github.com/Expensify/App/blob/ff54c9e3775c3c9bd7f08baaba1c7cbb8e715467/src/libs/ReportUtils.js#L1197-L1219

So the report does not have `From` link in header.

### What changes do you think we should make in order to solve the problem?
We can return report name for iou report and money request report.
```js
    if (isIOUReport(report)) {
        return {
-           rootReportName: lodashGet(report, 'displayName', ''),
+           rootReportName: getReportName(report),
        };
    }
    if (isMoneyRequestReport(report)) {
        return {
-           rootReportName: lodashGet(report, 'displayName', ''),
+           rootReportName: getReportName(report),
            workspaceName: isIOUReport(report) ? CONST.POLICY.OWNER_EMAIL_FAKE : getPolicyName(report, true),
        };
    }
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by StevenKKC** [comment] 2023-07-27 15:03
@fedirjh Thanks for your reply. Please check https://github.com/Expensify/App/issues/23348#issuecomment-1645431086. I think this comment can fully explain why `report` doesn't have `displayName`.

**Comment by StevenKKC** [comment] 2023-07-27 16:01
@fedirjh This issue is that Reply in thread report does not have link in header, and thread report use `HeaderView` component.

**Comment by StevenKKC** [comment] 2023-07-27 16:56
@fedirjh Please check the video.

https://github.com/Expensify/App/assets/131836113/3bf32524-2615-4008-85b5-f09597606dac

I think this issue is that in thread report does not have 'From' link.
Have I missed anything?

**Comment by StevenKKC** [comment] 2023-07-27 17:07
@fedirjh 

https://github.com/Expensify/App/assets/131836113/f38e7c90-c133-4b59-9b36-a987d02cf22e

I mean that this issue is that app does not display 'From' link in reply in thread report header as described in expected result.
But I think we should display 'From' link for money request reports.

**Comment by CortneyOfstad** [comment] 2023-07-27 18:05
Thanks @fedirjh!

**Comment by CortneyOfstad** [comment] 2023-08-01 20:07
I'm heading OoO until 8/14, so reassigning BZ to keep an eye on things 👍

**Comment by joekaufmanexpensify** [comment] 2023-08-01 20:10
@bondydaa thoughts on the proposal here when you have a sec?

**Comment by joekaufmanexpensify** [comment] 2023-08-02 16:46
Pending input from Bondy

**Comment by bondydaa** [comment] 2023-08-02 23:09
I also see the method we plan to update is used here https://github.com/Expensify/App/blob/cf4e837f8c6bc348c31103b415b19b45d4a8eb35/src/components/AvatarWithDisplayName.js#L56

so be sure to also test that it doesn't add any regressions where `AvatarWithDisplayName` is used please.

**Comment by StevenKKC** [comment] 2023-08-03 14:34
@fedirjh 
PR https://github.com/Expensify/App/pull/24113 is ready for review.

**Comment by CortneyOfstad** [comment] 2023-08-16 14:19
@fedirjh @bondydaa bump on PR review above 👍

**Comment by joekaufmanexpensify** [comment] 2023-08-16 14:27
Great, ty!

**Comment by StevenKKC** [comment] 2023-08-30 17:34
@CortneyOfstad This was deployed on production 7 days back but the title wasn't updated. Could you please take a look at this?

**Comment by CortneyOfstad** [comment] 2023-09-01 15:00
@bondydaa Any ideas with that? ^^^ I have no idea why the title didn't change 🤔

**Comment by bondydaa** [comment] 2023-09-01 16:26
🤷 probably just a network blip with GH or something. I know there were some issues recently with delayed webhooks.

**Comment by StevenKKC** [comment] 2023-09-07 06:02
@CortneyOfstad Any update here?

**Comment by CortneyOfstad** [comment] 2023-09-07 13:50
@bondydaa Is there a way we can manually update it, or will that mess the webhooks up? I just don't want to change something and have it cause a bigger problem lol

**Comment by StevenKKC** [comment] 2023-09-13 12:21
@CortneyOfstad The PR was deployed to production on August 23 and has not yet paid out. Could you please pay out?

**Comment by CortneyOfstad** [comment] 2023-09-13 12:32
Just paid out the following:

@dhanashree-sawant — $250 for reporting
@fedirjh — $1000 as C+
@StevenKKC — $1000 as Contributor

Creating the regression test GH now and will close this once they are linked 👍

**Comment by CortneyOfstad** [comment] 2023-09-13 12:35
Regression proposal found [here](https://github.com/Expensify/Expensify/issues/316420) — Closing! Thanks all!

**Comment by StevenKKC** [comment] 2023-09-13 12:50
@CortneyOfstad I think this qualifies for time bonus, because merge was delayed by @bondydaa.
@fedirjh Can you confirm this?

**Comment by CortneyOfstad** [comment] 2023-09-13 21:41
Bump @bondydaa and @fedirjh — Can we confirm if the above is true?

**Comment by StevenKKC** [comment] 2023-09-20 15:07
Friendly bump @bondydaa

**Comment by bondydaa** [comment] 2023-09-20 18:00
sorry for the delay here

> Is there a way we can manually update it, or will that mess the webhooks up?

Yeah i think just adding it to the title is fine in the future.

> I think this qualifies for time bonus, because merge was delayed by @bondydaa.

retaking a look (in the future anyone can do this as well, doesn't need to be blocked by the engineer)

Assigned on 8/2/2023 
<img width="952" alt="image" src="https://github.com/Expensify/App/assets/4073354/10b0aa24-3c46-481f-9700-2c4392619d63">

Looks like last commit was on 8/11/2023
<img width="1034" alt="image" src="https://github.com/Expensify/App/assets/4073354/f159449f-e8d0-4dc0-8d0a-52b1e0526368">

Approved by c+ on 8/13/2023
<img width="1031" alt="image" src="https://github.com/Expensify/App/assets/4073354/77b0a3bc-24d2-4d7a-a11b-2b242eb48d53">

Then merged on 8/17/2023
<img width="992" alt="image" src="https://github.com/Expensify/App/assets/4073354/f4ee9c95-5501-48c6-bef2-089f23398be6">

**Comment by StevenKKC** [comment] 2023-09-20 18:30
@bondydaa 

This PR was approved originally by C+ on 8/4/2023.
![Screenshot 2023-09-20 140548](https://github.com/Expensify/App/assets/131836113/e00fcc15-d86a-479e-b2f0-89d4de83cc7b)

But you mentioned the last commit which fixed the warning.
![Screenshot 2023-09-20 140634](https://github.com/Expensify/App/assets/131836113/67ba3d14-b315-4e05-a87e-2a431aac26c1)

And you confirmed that we should revert the last commit on 8/9/2023.
![Screenshot 2023-09-20 140715](https://github.com/Expensify/App/assets/131836113/ec06356a-4288-4e9f-9ee9-b3d79bb7adb3)

**Comment by bondydaa** [comment] 2023-09-20 20:14
I'm not sure the first approval matters here since changes needed to be pushed (via revert) and then re-approved. 

I think internal delays in merging only really matter if/when there aren't other commits that need to be pushed - at least that was my understanding.

**Comment by bondydaa** [comment] 2023-09-20 20:17
i've asked internally as well to double check here

**Comment by CortneyOfstad** [comment] 2023-10-03 14:01
@bondydaa any updates? I just realized the comment above doesn't have a link. Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-05 13:03
Bump @bondydaa ^^^

**Comment by CortneyOfstad** [comment] 2023-10-18 18:42
@bondydaa bump again on the above ^^^

**Comment by CortneyOfstad** [comment] 2023-10-18 19:47
Heading OoO until Oct. 25 — reassigning BZ to have someone keep an eye on this while I'm gone 👍

**Comment by bondydaa** [comment] 2023-10-24 21:33
sorry this is where I'd asked internally https://expensify.slack.com/archives/C01SKUP7QR0/p1695240928500889

as stated before since changes were requested and needed this doesn't qualify for a bonus. closing it out.

**Closed by bondydaa** 2023-10-24 21:33 UTC
Labels: Reviewing, External, Daily, Bug
