### ISSUE TITLE
[$250] Distance - Inconsistency in showing unit in preview and transaction thread after updating unit

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43588] opened 2024-06-12 16:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4621218
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Distance rates is enabled
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Submit two distance expenses (if there is no other unsettled expense)
4. Go to workspace settings
5. Go to Distance rates > Settings > Unit
6. Select a different unit
7. Go to transaction thread
8. Note that the new unit is applied in Distance and Rate rows in transaction thread
9. Note that the transaction thread header shows the previous unit
10. Go to expense report

## Expected Result:
There should be consistency in showing updated distance unit in transaction thread and preview in expense report

## Actual Result:
In Step 8, thenew unit is applied in Distance and Rate rows in transaction thread
In Step 9, transaction thread header shows the previous unit
In Step 10, the expense preview also shows the previous unit

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/13b219ba-256a-4c71-8c0d-d151e518a672

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c60d0efed5e27db</li>
        <li>Upwork Job ID: 1801098418852168279</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by lanitochka17** [comment] 2024-06-12 16:27
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 16:27
We think that this bug might be related to #wave-collect - Release 1

**Comment by jliexpensify** [comment] 2024-06-13 03:43
@lanitochka17 is this only happening on Chrome?

**Comment by nkdengineer** [comment] 2024-06-13 11:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 8, thenew unit is applied in Distance and Rate rows in transaction thread
In Step 9, transaction thread header shows the previous unit
In Step 10, the expense preview also shows the previous unit
### What is the root cause of that problem?
1. When we enable P2P distance, we display the distance text with the current unit of the WS.

https://github.com/Expensify/App/blob/fb323f66e731cfc402417f41a45bb42d6b887435/src/components/ReportActionItem/MoneyRequestView.tsx#L192

2. Meanwhile, the description text in money request preview is the `merchant` of the transaction and the unit is the unit at the time we create or edit this distance not the current unit of the WS

https://github.com/Expensify/App/blob/fb323f66e731cfc402417f41a45bb42d6b887435/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L88
### What changes do you think we should make in order to solve the problem?
Both distance display in transaction thread report and money request preview are wrong. The one has wrong distance value with current unit, the other has wrong unit. For two cases, we should display the distance with the current unit of the WS and the convert distance value with this unit. 

https://github.com/Expensify/App/blob/fb323f66e731cfc402417f41a45bb42d6b887435/src/components/ReportActionItem/MoneyRequestView.tsx#L192

https://github.com/Expensify/App/blob/fb323f66e731cfc402417f41a45bb42d6b887435/src/components/ReportActionItem/MoneyRequestPreview/MoneyRequestPreviewContent.tsx#L88

To do that we can create a util to get the display distance of the distance request. In this function, we will get the unit of transaction via the merchant of the `transaction`, get the current unit of the WS via policy, get the distance value via `transaction`. And then we will convert the distance value to the current unit of the WS and then return the display distance text with the converted distance value and the current unit of the WS
### What alternative solutions did you explore? (Optional)

**Comment by lanitochka17** [comment] 2024-06-13 19:33
@jliexpensify Reproducible in all environment.

**Comment by s77rt** [comment] 2024-06-14 02:06
I was not able to reproduce this. The money request info stayed the same (with old unit) which I think is the correct behaviour otherwise the amount will have to change. @nkdengineer Is this still reproducible for you?

**Comment by nkdengineer** [comment] 2024-06-14 02:08
@s77rt I can reproduce this issue. Are you enable the P2PDistance beta, it's required to reproduce this bug.

**Comment by s77rt** [comment] 2024-06-14 17:12
@nkdengineer I was able to reproduce after enabling the beta 👍 I think we should hold this on https://github.com/Expensify/App/issues/36987 cc @jliexpensify

**Comment by jliexpensify** [comment] 2024-06-17 00:04
Thanks, have adjusted the issue!

**Comment by s77rt** [comment] 2024-07-10 22:28
Still on hold

**Comment by s77rt** [comment] 2024-08-09 14:50
Bug is still reproducible. Let's remove the hold @trjExpensify 


https://github.com/user-attachments/assets/e8f735bd-4810-4c20-93e8-c28955e2cdc9

**Comment by s77rt** [comment] 2024-08-09 14:52
@nkdengineer Can you please double check your proposal and update it if necessary

**Comment by nkdengineer** [comment] 2024-08-09 15:12
@s77rt Checked my proposal again and it's ready for review.

**Comment by jliexpensify** [comment] 2024-08-10 04:05
@s77rt removed the hold in the title

**Comment by s77rt** [comment] 2024-08-10 16:29
@nkdengineer 

> For two cases, we should display the distance with the current unit of the WS and the convert distance value with this unit.


For consistency with the regular distance requests, we should keep showing the rate that the money request was created with. Can you update your proposal based on that?

**Comment by nkdengineer** [comment] 2024-08-12 08:15
> For consistency with the regular distance requests, we should keep showing the rate that the money request was created with. Can you update your proposal based on that?

@s77rt I updated my alternative [solution](https://github.com/Expensify/App/issues/43588#issuecomment-2165396582) with this expect.

**Comment by s77rt** [comment] 2024-08-12 20:42
@nkdengineer I noticed that if we change the rate value, the distance request will get invalidated. I assume we want the same behaviour when changing the unit.

**Comment by s77rt** [comment] 2024-08-12 20:42
🎀 👀 🎀 For Slack discussion

**Comment by s77rt** [comment] 2024-08-12 20:44
[Slack discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1723495439676929)

**Comment by s77rt** [comment] 2024-08-16 16:26
We may hold on https://github.com/Expensify/App/pull/47136

**Comment by neil-marcellini** [comment] 2024-08-16 17:03
Hey @stitesExpensify, I hope you don't mind me taking this over. @paultsimura [brought this to my attention](https://expensify.slack.com/archives/C01GTK53T8Q/p1723826810145699?thread_ts=1723655900.906359&cid=C01GTK53T8Q) and we discussed that it would be best to store the unit of the request in the transaction data, like @nkdengineer also suggested.

My plan is to make the change to start storing the unit, then write a custom query to set that data retro-actively on all existing distance expenses, and then update the frontend to use the unit from that location. I'm going to check with the team now to see if they think that's worthwhile, otherwise we'll be stuck parsing it from the merchant.

**Comment by s77rt** [comment] 2024-08-19 18:14
@neil-marcellini Let's hold on https://github.com/Expensify/App/pull/47136

**Comment by s77rt** [comment] 2024-08-22 17:12
Not overdue. @neil-marcellini Can we put this on hold?

**Comment by jliexpensify** [comment] 2024-08-23 01:56
Done, @neil-marcellini can adjust the issue if he likes!

**Comment by neil-marcellini** [comment] 2024-09-04 18:24
I don't think we want this on HOLD actually. We need to do [this plan](https://github.com/Expensify/App/issues/43588#issuecomment-2293853715) for the backend, or something similar.

**Comment by neil-marcellini** [comment] 2024-09-04 18:42
I [asked about the plan](https://expensify.slack.com/archives/C03TQ48KC/p1725475275250749) internally, so after I get some feedback I'll make the change. I'm leaning towards parsing the rate unit from the merchant string since it's much easier.

**Comment by neil-marcellini** [comment] 2024-09-12 21:53
Setting a reminder to work on this tomorrow.

**Comment by neil-marcellini** [comment] 2024-09-19 21:52
Sorry for the delay, higher priority things came up. I thought about this a lot today and played around in my dev environment. 

The rough plan is

1. Update all code which updates the distance to save the unit into `transaction.comment.customUnit.unit`
2. Run an operator script to to properly set the distance unit into the transaction for existing expenses

Here's what I'm currently thinking for how to do 2. I want to make sure that I have a solid plan for this first as it's the hardest part.

If we run across a NewDot distance expense where the merchant is invalid, we can find the appropriate unit by determining what the policy distance unit was at the time the appropriate unit for the quantity was last updated. The only way that happens, to my knowledge, is editing the distance expense in NewDot. We can figure out whenever the policy unit changes by looking at the reportActions with action `POLICYCHANGELOG_UPDATE_CUSTOM_UNIT`. I think we can figure out whenever the distance changed form NewDot by looking at the modified expense actions.

If it's not a NewDot distance expense, but the merchant is invalid, we would still like to set the appropriate unit for display in NewDot. I think we should also check the merchant for any text like mi, km, mile, kilometer. If the user manually edited the merchant to include a unit, use that. Otherwise use the original unit for the distance because it can't be edited any other way than from NewDot.

The next thing to figure out is exactly how I'm going to find what the distance unit was at the time the transaction distance unit was last calculated and updated.

My personal notes from today 9-19-24 have more context.

**Comment by neil-marcellini** [comment] 2024-09-20 20:27
I finalized the plan in a Slack canvas and [posted it](https://expensify.slack.com/archives/C03TQ48KC/p1726863887432759?thread_ts=1725475275.250749&cid=C03TQ48KC) for review by the team.

**Comment by neil-marcellini** [comment] 2024-09-30 19:34
The decision here is that we don't really care about fixing this for existing distance transactions, as there could be millions of those to update and given that the bug exists on OldDot and hasn't been seeming to bother people it's not really worth fixing historically.

I will work on PRs to start saving and using the transaction distance unit, and if it's unavailable we'll fallback to the current method 🤷‍♂️. I hope to get started sometime this week.

**Comment by neil-marcellini** [comment] 2024-09-30 23:12
Cool I got it saving for creating requests. I'll add tests for editing next, and then also any places where it's read in Web-E. For example I should test the exact steps of this issue, verifying the merchant is unchanged when the policy unit changes.

**Comment by jliexpensify** [comment] 2024-10-01 09:50
Just a heads up I'm OOO from 3rd to 14th, but I don't think anything is needed from me during this period. Feel free to reassign to another B0 if needed though!

**Comment by neil-marcellini** [comment] 2024-10-02 15:21
I got the bug fixed and working well with and without the beta. I still need to do some fixes for when the rate is updated, and I should check that this works for tracked distance expenses and splits too.

**Comment by neil-marcellini** [comment] 2024-10-07 14:45
I just realized that I also need to fix this for distance expenses created from Expensify classic. The current PRs only relate to New Expensify.

I think it's fine to make the update for the old and new platforms separately because the distanceUnit is currently not stored at all, so it's fine if new is storing it and old isn't for a little while. That will keep the PRs focused. I'm noting this so I don't forget to update for classic.

**Comment by neil-marcellini** [comment] 2024-10-15 20:37
I made a few more changes on the App PR from review feedback and I'm ready for another C+ review.

**Comment by neil-marcellini** [comment] 2024-10-25 18:51
@jliexpensify this is on prod now, next step is payment.

**Comment by jliexpensify** [comment] 2024-10-27 02:16
Is this correct?

- C+: @s77rt $250 (payment owed via New.Dot)

**Comment by s77rt** [comment] 2024-10-27 05:15
Yes 👍

**Comment by jliexpensify** [comment] 2024-10-27 21:26
Any checklist needed @s77rt?

**Comment by s77rt** [comment] 2024-10-28 08:23
@jliexpensify I don't think that's needed here given that this bug comes from a new feature that's still in beta. As for the regression test(s) they will be added at once https://github.com/Expensify/App/issues/23291 https://github.com/Expensify/Expensify/issues/437283

**Comment by jliexpensify** [comment] 2024-10-28 08:51
Awesome, thanks! I'll close this out but here is the linked [Payment Summary](https://github.com/Expensify/App/issues/43588#issuecomment-2439807411) for your payment @s77rt

**Closed by jliexpensify** 2024-10-28 08:51 UTC
Labels: Weekly, Internal, Bug

**Comment by JmillsExpensify** [comment] 2024-10-28 10:49
$250 approved for @s77rt
