### ISSUE TITLE
[Awaiting payment][$250] Taxes - When creating a Tax, the keyboard does not automatically appear in the "Name" menu

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41800] opened 2024-05-07 18:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.71-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4545979
**Email or phone of affected tester (no customers):** sustinov@applausemail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open New Expensify app
2. Create a WS
3. Navigate to the "More features" menu
4. Enable "Taxes"
5. Navigate to the "Taxes" menu
6. Tap on the "Add rate" button
7. Tap on the Name field

## Expected Result:
When creating a Tax, the keyboard should automatically appear in the "Name" menu

## Actual Result:
When creating a Tax, the keyboard does not automatically appear in the "Name" menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/fdb7069f-3d2c-4cd0-a8ee-f448a2bd4d9b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016fb7ed1a2ab55442</li>
        <li>Upwork Job ID: 1787997169242755072</li>
        <li>Last Price Increase: 2024-05-08</li>
<li>Automatic offers: </li>
<ul>
<li>jayeshmangwani | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by lanitochka17** [comment] 2024-05-07 18:43
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-07 18:43
We think that this bug might be related to #vip-vsp

**Comment by strepanier03** [comment] 2024-05-08 00:05
Easy to repro on Android Native, adding external.

**Comment by nkdengineer** [comment] 2024-05-08 03:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating a Tax, the keyboard does not automatically appear in the "Name" menu

### What is the root cause of that problem?
We pass `autoFocus` to the input of `TextPicker` so the input is focused but the keyboard doesn't appear

https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L97
### What changes do you think we should make in order to solve the problem?
We should use the ref to focus the `TextInput` whenever the text select modal is opened.

1. Create a ref 

```
const inputRef = useRef<BaseTextInputRef | null>(null);
```


2. Create a useEffect to focus the `TextInput` whenever the `TextSelectorModal` is opened

```
const prevIsVisible = usePrevious(isVisible);

const focus = () => {
    focusTimeoutRef.current = setTimeout(() => {
        inputRef.current?.focus();
        return () => {
            if (!focusTimeoutRef.current) {
                return;
            }
            clearTimeout(focusTimeoutRef.current);
        };
    }, CONST.ANIMATED_TRANSITION);
}

useEffect(() => {
    if (prevIsVisible || !isVisible) {
        return;
    }

    focus();

}, [prevIsVisible, isVisible])
```


### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-05-08 03:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When creating a Tax, the keyboard does not automatically appear in the "Name" menu

### What is the root cause of that problem?
We pass `autoFocus` to the input of `TextPicker` so the input is focused but the keyboard doesn't appear

https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L97
### What changes do you think we should make in order to solve the problem?
- We should remove all `autoFocus` prop that we passed to `TextPicker` to prevent this bug in other places
 
https://github.com/Expensify/App/blob/55c56bffbee8afd2fb5f5b2abfe30a92487bab52/src/pages/workspace/taxes/WorkspaceCreateTaxPage.tsx#L97

- We should use the ref to focus the `TextInput` whenever the text select modal is opened.

1. Create a ref 

```
const inputRef = useRef<BaseTextInputRef | null>(null);
```


2. Create a useEffect to focus the `TextInput` whenever the `TextSelectorModal` is opened

```
const prevIsVisible = usePrevious(isVisible);

const focus = () => {
    focusTimeoutRef.current = setTimeout(() => {
        inputRef.current?.focus();
        return () => {
            if (!focusTimeoutRef.current) {
                return;
            }
            clearTimeout(focusTimeoutRef.current);
        };
    }, CONST.ANIMATED_TRANSITION);
}

useEffect(() => {
    if (prevIsVisible || !isVisible) {
        return;
    }

    focus();

}, [prevIsVisible, isVisible])
```


### What alternative solutions did you explore? (Optional)

**Comment by jayeshmangwani** [comment] 2024-05-08 18:22
Thanks for the proposals @nkdengineer @Krishna2323; both approach will work in this case, but we can use the [useFocusEffect](https://github.com/Expensify/App/issues/41800#issuecomment-2099953103) approach. For consistency here, we are already using the same way on many pages.

@Krishna2323 's [Proposal](https://github.com/Expensify/App/issues/41800#issuecomment-2099953103) looks good to me

 🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-05-08 18:33
@jayeshmangwani I think using `useEffect` or `useFocusEffect` can be discussed in the PR phrase. The idea is the same and my proposal is first.

**Comment by jayeshmangwani** [comment] 2024-05-08 20:02
The idea may be similar @nkdengineer , but I chose the other proposal because we discussion around the autofocus prop and decided to use the [useFocusEffect](https://expensify.slack.com/archives/C01GTK53T8Q/p1694660990479979) hook.And You mentioned in the proposal that we should use the useEffect, but I'm sorry if you feel otherwise. I will let the internal engineer decide, I hope thats is ok 🙏

**Comment by nkdengineer** [comment] 2024-05-08 20:10
No problem. 
I think the `useEffect` is just an example detail with my idea and it can be discussed more in the PR.

Feel free with the decision from @MonilBhavsar

**Comment by MonilBhavsar** [comment] 2024-05-09 11:13
Since the other proposal completely mentioned the correct hook. It is fair to select it. Thanks for the proposal though!

**Comment by MonilBhavsar** [comment] 2024-06-05 18:13
The PR was deployed to production 2 weeks ago and there's no regression, so we need to pay @Krishna2323 and @jayeshmangwani(C+) cc @strepanier03 

--- 

Not sure why automation didn't work

**Comment by MonilBhavsar** [comment] 2024-06-05 18:14
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [ ] [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@strepanier03] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by jayeshmangwani** [comment] 2024-06-06 12:28
- [x]  [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/37967
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/37967/files#r1629432041
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A - we already have a section in the dc for the similar issues**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug.
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

## Regression Test Proposal

1. Open App -> Go to Settings -> Workspaces -> Create a WS
2. Navigate to the "More features" -> Enable "Taxes"
3. Navigate to the "Taxes" menu -> Add rate 
4. Tap on the Name field
5. Verify that input field is focused and keyboard appears automatically

Do we agree 👍 or 👎

**Comment by jayeshmangwani** [comment] 2024-06-06 12:37
@strepanier03 Is that possible to get payment through ND for this issue as now I am getting paid through it and cancel the Upwork offer? If not then no issues we can go with the Upwork offer.

**Comment by jayeshmangwani** [comment] 2024-06-10 19:44
Not Overdue! Issue is Awaiting payment
@strepanier03 Please check this [comment](https://github.com/Expensify/App/issues/41800#issuecomment-2152302896)

**Comment by strepanier03** [comment] 2024-06-11 02:52
Thanks all, I have been out of ht office and just got back in today. 

@jayeshmangwani - Sure thing! I'll cancel the contract in Upwork and make a payment summary post so you can do the manual request.

**Comment by strepanier03** [comment] 2024-06-11 02:58
@Krishna2323 - THe job in Upwork expired so I had to make a new one. I hired you for it and you should see an offer to accept. I'll check tomorrow to pay it.

**Comment by strepanier03** [comment] 2024-06-11 02:59
### Payment Summary

- $250 - @jayeshmangwani via Manual Requests
- $250 - @Krishna2323 via [Upwork](https://www.upwork.com/nx/wm/workroom/37520128/overview)

@JmillsExpensify - Payment request incoming.

**Comment by jayeshmangwani** [comment] 2024-06-11 07:13
Requested on ND

**Comment by JmillsExpensify** [comment] 2024-06-11 18:17
$250 approved for @jayeshmangwani

**Comment by strepanier03** [comment] 2024-06-11 22:07
I've paid @Krishna2323 and closed the contract as well. 

Thank you, everyone. Have a great week!

**Closed by strepanier03** 2024-06-11 22:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
