### ISSUE TITLE
[HOLD for payment 2023-01-30] [$1000] New Room - Capital letters is converted to lowercase when all caps is enable

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13676] opened 2022-12-16 23:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/13621

## Action Performed:
1. Launch the app
2. Log in with any account
3. Press the Green + button and select New Room
4. On the name field double tap on the shift ⬆️ so the all caps is enabled
5. Tap in different keys on the actual device keyboard

## Expected Result:
Capital letters is visible until an area outside of the field is tapped.  
~Capital letters is not visible and transaction is smooth when all caps is enabled~

## Actual Result:
Capital letter changes to lowercase. 
~Capital letters is visible and transaction isn't smooth when all caps is enable~

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.41.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/208208336-3d030071-dac0-47dc-ad3b-0fd3ff57e496.mp4

https://user-images.githubusercontent.com/93399543/208208339-eb7b2c71-1afe-4490-bc3d-ac7de8fff83f.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01773a5a2201587c50</li>
        <li>Upwork Job ID: 1612436167049437184</li>
        <li>Last Price Increase: 2023-01-09</li>
    </ul>
</details>

**Comment by Christinadobrzyn** [comment] 2022-12-19 03:03
This might be related - https://github.com/Expensify/App/issues/13463  @sketchydroide can I get your thoughts if this is the same issue (I see the PR merged so maybe it's not)?

It might also be related to this - https://github.com/Expensify/App/issues/13042 - maybe capital letters are considered a special character right now? @madmax330 can I get your thoughts?

**Comment by sketchydroide** [comment] 2022-12-19 12:08
It's not related, but I'm not sure if we can do something about it, this is mobile iOS and Android, the other one was Android only.
Yes it's related to the other one.
The issue is that we take the input of the user, and change it on the fly, so what happens is that the user still sees the text before we change it, giving it this weird jagged behaviour.
@madmax330 if you make changes on the other one it should in princible fix this one, but let us know if I'm wrong.

Either way @Christinadobrzyn I think this GH will be closed.

**Comment by Christinadobrzyn** [comment] 2022-12-21 02:00
Thanks @sketchydroide! We'll wait to hear from @madmax330 to see if he might have more info on this issue being resolved with https://github.com/Expensify/App/issues/13042

**Comment by Christinadobrzyn** [comment] 2022-12-22 12:07
I'm ooo so going to reassign

**Comment by mallenexpensify** [comment] 2022-12-23 23:28
Also waiting for feedback from @madmax330

**Comment by mallenexpensify** [comment] 2022-12-28 16:54
@madmax330 should be back from OOO today

**Comment by madmax330** [comment] 2022-12-29 06:17
I don't think my fix for the other issue will fix this. 
I think for this issue we should just convert the value to lowercase before we display it instead of displaying it then changing it.

**Comment by sketchydroide** [comment] 2022-12-29 09:50
is there a method for that? Atm we are using `onChange` that seems to be actinc after the change not before. I don't know enough about react

**Comment by madmax330** [comment] 2022-12-30 08:39
I think onChange should be fine. It's just that we should make sure the correct value is set before rendering it

**Comment by mallenexpensify** [comment] 2023-01-06 22:22
Assigning @madmax330 and @sketchydroide cuz otherwise they might not see.  Can you review the above and provide guidance? plzzzz

**Comment by madmax330** [comment] 2023-01-09 08:27
I think this issue can be external, we just need to figure out why the input is rendering incorrect characters and make sure it only renders if the characters are correct. That's what would remove the flickering effect. 
So the next step is for someone to investigate why it's rendering characters that we don't want and find a way to fix it

**Comment by sketchydroide** [comment] 2023-01-09 13:08
I'm fine with that

**Comment by Karim-30** [comment] 2023-01-09 13:41
### Proposal

I suggest letting the user write the name he wants and converting it `toLowerCase()` when submitting.

```diff

/**
diff --git a/src/libs/RoomNameInputUtils.js b/src/libs/RoomNameInputUtils.js
index 552209697..978613cf7 100644
--- a/src/libs/RoomNameInputUtils.js
+++ b/src/libs/RoomNameInputUtils.js
@@ -13,7 +13,7 @@ function modifyRoomName(roomName) {
         .replace(/ /g, '_')
         .replace(/[^a-zA-Z\\d_]/g, '')
         .substr(0, CONST.REPORT.MAX_ROOM_NAME_LENGTH)
-        .toLowerCase();
 
     return `${CONST.POLICY.ROOM_PREFIX}${modifiedRoomNameWithoutHash}`;
 }
diff --git a/src/pages/ReportSettingsPage.js b/src/pages/ReportSettingsPage.js
index 818e35786..244304aa2 100644
--- a/src/pages/ReportSettingsPage.js
+++ b/src/pages/ReportSettingsPage.js
@@ -92,29 +92,30 @@ class ReportSettingsPage extends Component {
             return;
         }
         Keyboard.dismiss();
-        Report.updatePolicyRoomName(this.props.report, this.state.newRoomName);
+        Report.updatePolicyRoomName(this.props.report, this.state.newRoomName.toLowerCase());
     }
 
     validate() {
         const errors = {};
+        const newRoomName = this.state.newRoomName.toLowerCase();
 
         // When the report name is not changed, skip the form submission. Added check here to keep the code clean
-        if (this.state.newRoomName === this.props.report.reportName) {
+        if (newRoomName === this.props.report.reportName) {
             return false;
         }
 
         // Show error if the room name already exists
-        if (ValidationUtils.isExistingRoomName(this.state.newRoomName, this.props.reports, this.props.report.policyID)) {
+        if (ValidationUtils.isExistingRoomName(newRoomName, this.props.reports, this.props.report.policyID)) {
             errors.newRoomName = this.props.translate('newRoomPage.roomAlreadyExistsError');
         }
 
         // We error if the user doesn't enter a room name or left blank
-        if (!this.state.newRoomName || this.state.newRoomName === CONST.POLICY.ROOM_PREFIX) {
+        if (!newRoomName || newRoomName === CONST.POLICY.ROOM_PREFIX) {
             errors.newRoomName = this.props.translate('newRoomPage.pleaseEnterRoomName');
         }
 
         // Certain names are reserved for default rooms and should not be used for policy rooms.
-        if (ValidationUtils.isReservedRoomName(this.state.newRoomName)) {
+        if (ValidationUtils.isReservedRoomName(newRoomName)) {
             errors.newRoomName = this.props.translate('newRoomPage.roomNameReservedError');
         }
 
diff --git a/src/pages/workspace/WorkspaceNewRoomPage.js b/src/pages/workspace/WorkspaceNewRoomPage.js
index 654e2ce8c..1b40cefa7 100644
--- a/src/pages/workspace/WorkspaceNewRoomPage.js
+++ b/src/pages/workspace/WorkspaceNewRoomPage.js
@@ -82,7 +82,7 @@ class WorkspaceNewRoomPage extends React.Component {
             return;
         }
         const policy = this.props.policies[`${ONYXKEYS.COLLECTION.POLICY}${this.state.policyID}`];
-        Report.addPolicyReport(policy, this.state.roomName, this.state.visibility);
+        Report.addPolicyReport(policy, this.state.roomName.toLowerCase(), this.state.visibility);
     }
 
     /**
@@ -90,19 +90,20 @@ class WorkspaceNewRoomPage extends React.Component {
      */
     validate() {
         const errors = {};
+        const roomName = this.state.roomName.toLowerCase();
 
         // We error if the user doesn't enter a room name or left blank
-        if (!this.state.roomName || this.state.roomName === CONST.POLICY.ROOM_PREFIX) {
+        if (!roomName || roomName === CONST.POLICY.ROOM_PREFIX) {
             errors.roomName = this.props.translate('newRoomPage.pleaseEnterRoomName');
         }
 
         // We error if the room name already exists.
-        if (ValidationUtils.isExistingRoomName(this.state.roomName, this.props.reports, this.state.policyID)) {
+        if (ValidationUtils.isExistingRoomName(roomName, this.props.reports, this.state.policyID)) {
             errors.roomName = this.props.translate('newRoomPage.roomAlreadyExistsError');
         }
 
         // Certain names are reserved for default rooms and should not be used for policy rooms.
-        if (ValidationUtils.isReservedRoomName(this.state.roomName)) {
+        if (ValidationUtils.isReservedRoomName(roomName)) {
             errors.roomName = this.props.translate('newRoomPage.roomNameReservedError');
         }
 

```


https://user-images.githubusercontent.com/51829206/208263721-0bd7f2b4-fb26-463e-8954-28902c00a0b4.mov

}

**Comment by Monster-0117** [comment] 2023-01-09 13:45
Hi. May I join this project?

**Comment by avdoseferovic** [comment] 2023-01-09 13:47
## Proposal
### Problem
This problem is a known issue in react native, and unforunately still not fixed. (https://github.com/facebook/react-native/issues/24585)
### Solution
We can use CSS to style the text input to lowercase and by doing so the flickering effect will dissapear.
``` diff
diff --git a/src/components/RoomNameInput/index.js b/src/components/RoomNameInput/index.js
index 0ecd55ce16..48897ed37f 100644
--- a/src/components/RoomNameInput/index.js
+++ b/src/components/RoomNameInput/index.js
@@ -5,6 +5,7 @@ import withLocalize from '../withLocalize';
 import TextInput from '../TextInput';
 import * as roomNameInputPropTypes from './roomNameInputPropTypes';
 import * as RoomNameInputUtils from '../../libs/RoomNameInputUtils';
+import styles from '../../styles/styles';

 class RoomNameInput extends Component {
     constructor(props) {
@@ -61,6 +62,7 @@ class RoomNameInput extends Component {
         return (
             <TextInput
                 ref={this.props.forwardedRef}
+                style={[styles.textLowercase]}
                 disabled={this.props.disabled}
                 label={this.props.translate('newRoomPage.roomName')}
                 prefixCharacter={CONST.POLICY.ROOM_PREFIX}
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 39dfe8695b..42a4526344 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -294,6 +294,10 @@ const styles = {
         textTransform: 'uppercase',
     },

+    textLowercase: {
+        textTransform: 'lowercase',
+    },
+
:
```

**Comment by Monster-0117** [comment] 2023-01-09 13:54
Hi, Thanks for your message. In my opinion, you can change text to lower
case when change letter in textarea. I am looking forward to hear from you.
Thanks

**Comment by hungvu193** [comment] 2023-01-09 15:42
<b>Proposal</b>
So we change the text to lower case and space into `-` in onChange function, so it will look like in the video in this issue.
I think we can avoid that by removing the `toLowerCase()` inside `modifyRoomName` function.
Since we already have the validation for Room Name. Here's the result:

https://user-images.githubusercontent.com/16502320/211347760-13202508-db8e-4263-bd84-841d47bca719.mov

**Comment by jatinsonijs** [comment] 2023-01-09 16:19
@hungvu193 With toLowerCase remove, we also have to change validation message to clarify to user only lower letters are allowed. as currently its showing room name can contains only letters... which mean both upper and lower. It should say room name can contains only lower letters and...

**Comment by hungvu193** [comment] 2023-01-09 16:22
> @hungvu193 With toLowerCase remove, we also have to change validation message to clarify to user only lower letters are allowed. as currently its showing room name can contains only letters... which mean both upper and lower. It should say room name can contains only lower letters and...

Yep, I believe we need to change the validation message too.

**Comment by dviecas** [comment] 2023-01-09 19:32
**Proposal:**
The root cause of the issue here is that the `props.value` of the `TextView` is changed by both the user and the `onChangeText(modifiedRoomName)` - hence the short window where we can see the user's entered uppercase letter.

The simplest solution here would be to use a separate variable holding the state of the `value` field, which would be  modified and displayed instead of the `props.value` property. All of the related functionality would work the same way as before (for ex. the  Form component would get the same`RoomNameInput.value`), however there would be only a single visual refresh displaying the final (modified) value and excluding the one user originally entered.

**Comment by mallenexpensify** [comment] 2023-01-09 23:02
@thesahindia can you please review the proposals above? Thanks. 

@sketchydroide @madmax330 , do either of you _want_ to stay assigned? If not I'll remove you both and add the `Engineering` label to auto-assign

**Comment by thesahindia** [comment] 2023-01-09 23:20
I think we need to decide the expected result first. From the discussion above I am guessing the character should be lowercase when it gets added to the input.

**Comment by Puneet-here** [comment] 2023-01-10 16:03
### Proposal

From the thread it looks like we will be moving with an error message when user uses uppercase characters

Add the below function in https://github.com/Expensify/App/blob/main/src/libs/ValidationUtils.js
```js
function doesContainsUpperCase(value) {
    return value !== value.toLowerCase();
}
```
We can also use regex (let me know )

Add another else if statement in validate function 
```js
else if (ValidationUtils.doesContainsUpperCase(values.roomName)) {
            errors.roomName = this.props.translate('newRoomPage.roomNameContainsUpperCaseChar');
}
```
https://github.com/Expensify/App/blob/a18c9f09553fda631e9ccaddd4e148008edb26ab/src/pages/workspace/WorkspaceNewRoomPage.js#L81
we want the same behaviour at room settings page so we need to add a check here
```js
else if (ValidationUtils.doesContainsUpperCase(values.newRoomName)) {
            errors.newRoomName = this.props.translate('newRoomPage.roomNameContainsUpperCaseChar');
        }
```
https://github.com/Expensify/App/blob/a18c9f09553fda631e9ccaddd4e148008edb26ab/src/pages/ReportSettingsPage.js#L85

Remove the line below 

https://github.com/Expensify/App/blob/c8f3606207d8e4361254db2f3b929e95555a852a/src/libs/RoomNameInputUtils.js#L14



We will need the error copy and translation

**Comment by jatinsonijs** [comment] 2023-01-10 16:25
From the [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1673301333840109) it is decided instead of changing text on type give validation error to user on blur.

**Proposal**

We have to remove toLowerCase and also have to change text so that it can show correct message like only lower letters are allowed. Optionally we can also remove hyphen adding on space to make it consistence.

```diff
diff --git a/src/languages/en.js b/src/languages/en.js
index f3035298a2..4fefae5a2b 100755
--- a/src/languages/en.js
+++ b/src/languages/en.js
@@ -1035,7 +1035,7 @@ export default {
         createRoom: 'Create Room',
         roomAlreadyExistsError: 'A room with this name already exists',
         roomNameReservedError: 'A room on this workspace already uses this name',
-        roomNameInvalidError: 'Room names can only contain letters, numbers and hyphens',
+        roomNameInvalidError: 'Room names can only contain lower letters, numbers and hyphens',
         pleaseEnterRoomName: 'Please enter a room name',
         pleaseSelectWorkspace: 'Please select a workspace',
         renamedRoomAction: ({oldName, newName}) => ` renamed this room from ${oldName} to ${newName}`,
diff --git a/src/libs/RoomNameInputUtils.js b/src/libs/RoomNameInputUtils.js
index 6c2ee31775..4a6898d06e 100644
--- a/src/libs/RoomNameInputUtils.js
+++ b/src/libs/RoomNameInputUtils.js
@@ -10,8 +10,7 @@ import CONST from '../CONST';
  */
 function modifyRoomName(roomName) {
     const modifiedRoomNameWithoutHash = roomName
-        .replace(/ /g, '-')
-        .toLowerCase();
+        .replace(/ /g, '-');
 
     return `${CONST.POLICY.ROOM_PREFIX}${modifiedRoomNameWithoutHash}`;
 }

```
<img width="365" alt="Screenshot 2023-01-10 at 9 53 51 PM" src="https://user-images.githubusercontent.com/114683042/211606307-367f7906-e22a-46a7-a2b7-e830f1e14c0d.png">

**Comment by trjExpensify** [comment] 2023-01-10 21:04
Nice, pleased we aligned on a path forward!

>Optionally we can also remove hyphen adding on space to make it consistence. (For this we have to further refine validation message to make it more clear like space are not allowed).

That isn't in scope of this bug IMO, so let's not add scope creep to the PR. 👍

**Comment by thesahindia** [comment] 2023-01-10 21:41
There are two proposals. @Puneet-here suggested to display a new specific error message to inform the user that capital letters aren't allowed. @jatinsonijs suggested that we change our existing message which is "Room names can only contain letters, numbers and hyphens" to "Room names can only contain lower letters, numbers and hyphens"
Which one is better? I guess changing our existing message?

**Comment by mallenexpensify** [comment] 2023-01-10 22:21
I'm a bit confused here.  Is the OP correct and up to date? 
>Expected Result:
Capital letters is not visible and transaction is smooth when all caps is enabled

@trjExpensify , is the desired outcome, to maintain consistency across platforms, to **show** the capital letters (and other characters that aren't allowed) then only show the error message after someone has tapped `Create Room`?

**Comment by trjExpensify** [comment] 2023-01-11 01:14
>I'm a bit confused here. Is the OP correct and up to date?

Nah, it's not accurate based on our discussion in the thread today - so it needs updating. 

>to show the capital letters (and other characters that aren't allowed)

Yes, capital letters should show, just like other special characters we don't allow do. 

>then only show the error message after someone has tapped Create Room?

Show the error message when the room name field loses focus (i.e "onBlur") which is the forms error pattern. Meaning, when you click out of the field and it loses focus the error message would appear if the field contains capital letters. Try it in product, type a room name containing a bunch of special characters we don't support and then click outside of the field. 

 > @jatinsonijs suggested that we change our existing message which is "Room names can only contain letters, numbers and hyphens" to "Room names can only contain lower letters, numbers and hyphens"
Which one is better? I guess changing our existing message?

Yes, updating our existing message for the field validation is better IMO. Copy suggestion I put in thread is: 

`Room names can only include lowercase letters, numbers and hyphens`

**Comment by hungvu193** [comment] 2023-01-11 02:22
> js suggested that we change our existing message which is "Room names can only contain letters, numbers and hyphens" to "Room names can only contain lower letters, numbers and hyphens"
> Which one is better? I guess changing our existing me

Isn't that my proposal?
I thought I already mentioned that we also need to update the validation message here, so I didn't update it on my proposal


> > @hungvu193 With toLowerCase remove, we also have to change validation message to clarify to user only lower letters are allowed. as currently its showing room name can contains only letters... which mean both upper and lower. It should say room name can contains only lower letters and...
> 

> Yep, I believe we need to change the validation message too.

**Comment by thesahindia** [comment] 2023-01-11 04:34
@hungvu19 and @jatinsonijs suggested the same [solution](https://github.com/Expensify/App/issues/13676#issuecomment-1377523596). @hungvu193's [proposal](https://github.com/Expensify/App/issues/13676#issuecomment-1375825114) didn't mention changing the validation message it was [pointed out](https://github.com/Expensify/App/issues/13676#issuecomment-1375897390) by @jatinsonijs. 

@sketchydroide, for the final call.

🎀👀🎀 C+ reviewed

**Comment by thesahindia** [comment] 2023-01-11 04:35
@hungvu193, remember that the proposal should be complete and shouldn't be in multiple comments and you need to link the code in your proposal.

**Comment by hungvu193** [comment] 2023-01-11 04:40
@thesahindia I already implemented code in my proposal, and the purpose of fixing the issue is that finding the root cause and fix the root cause right?
Isn't that contributor can suggest multiple proposals and the key of this fixing this issue was removing the `toLowerCase() inside modifyRoomName function`?.
I don't add it into my first proposal because I thought that it's somethings inevitable when we decided to remove the animation by validating it when submit isn't it?

**Comment by jatinsonijs** [comment] 2023-01-11 04:47
@hungvu193 I think we are not fixing root cause for this issue. Bcz original issue is transaction isn't smooth when all caps is enable. So we are instead of fixing it we are removing this functionality. I have posted solution based on slack thread discussion. So overall final solution contains your and my suggestion.

**Comment by hungvu193** [comment] 2023-01-11 04:55
Nope, @jatinsonijs .
The discussion is about how we decide to fix this issue.
<img width="397" alt="Screen Shot 2023-01-11 at 11 54 19" src="https://user-images.githubusercontent.com/16502320/211720799-34740f5e-d039-4f55-be10-6591f9b4111d.png">
Personally, I don't want to argue but this time I can't agree with the reviewer, that's not fair.

**Comment by dinhhien2006** [comment] 2023-01-11 06:21
I agreed that we should go with @hungvu193 proposal.

**Comment by thesahindia** [comment] 2023-01-11 09:19
@hungvu193, I think you are getting confused with two different things. 

1. I haven't chosen @jatinsonijs's proposal over yours. Both proposals are same but your didn't mention changing the error message in your proposal and @jatinsonijs pointed out that, I am not sure if this is a significant thing so I left the decision to @sketchydroide. Makes sense?

2.[ This comment](https://github.com/Expensify/App/issues/13676#issuecomment-1378230312) was a suggestion for future proposals and I am not saying your proposal is invalid because you didn't link the code. We expect the contributor to link the code because it's easy to just look in the proposal and understand what it's doing.
> I think we can avoid that by removing the toLowerCase() inside modifyRoomName function.

You can't expect that c+ and engineer would know where `xyz` code is what's it's doing. 

and yeah you can propose multiple solutions but the solution should be in a single comment. It saves us some time.

**Comment by mallenexpensify** [comment] 2023-01-11 18:17
> when you click out of the field and it loses focus the error message would appear if the field contains capital letters. Try it in product, type a room name containing a bunch of special characters we don't support and then click outside of the field.

I see two versions of this happening
1. When I first type special characters, there is no error message until I click out of the field. 
2. After the error shows, if I delete the special characters and type a lowercase letter, the error message goes away.  If I then type a special character after the lowercase letter, the error **immediately** pops up, I don't have to wait to click outside of the field for the error message to show. 

I propose that we #2 should be how this is handled because #1 isn't efficient or best UX.  I'm unsure why this wouldn't be the same for other fields and error messages either.   Is #2 the proposed _fix_ for this?

**Comment by jatinsonijs** [comment] 2023-01-12 05:00
@mallenexpensify it is already like this. In our app we have form validation in this way until input untouched we are not showing validation error which is the most common behaviour of forms. Once user press outside form mark as touched and we are showing validation error on user type if anything not correct.

Only option 2 is good for room input as it fit well in this case. But its not fit well for every type of Input like Account Number, Email etc..
Like if we choose only option 2 - user start typing their email address it will immediately show validation error (invalid email) but user know he is going to type his complete email address. So here better to show error when user press outside or submit button.

**Comment by trjExpensify** [comment] 2023-01-12 12:01
Oh hm, that's interesting @mallenexpensify. Why are we doing that? I'm advocating to follow the [Forms guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/FORMS.md#validate-on-blur-and-submit) such that we are consistent throughout the app, avoiding a one-off decision for a specific form. 

@luacmartins as you spearheaded forms, can you chime in on what Matt is seeing [here](https://github.com/Expensify/App/issues/13676#issuecomment-1379299751). Why does the error message throw when the field is still in focus the second time? I don't see that behaviour documented as intended.

**Comment by luacmartins** [comment] 2023-01-12 16:15
@trjExpensify @mallenexpensify the guidelines are indeed missing the onChange validation behavior. Nice catch! Both #1 and #2 are expected - initially, the input should only be validated once blurred, but after the user has "touched" that input we should also validate onChange. 

I'll update the guidelines to add that bit of information.

**Comment by luacmartins** [comment] 2023-01-12 16:25
I don't think we need to change form behavior here. I think in that case we should add a hint to the input saying that capital letters, special chars, etc are not allowed and then let the current form validation pattern handle the rest.

**Comment by thesahindia** [comment] 2023-01-12 16:30
@sketchydroide, please look into https://github.com/Expensify/App/issues/13676#issuecomment-1378229848. 

> I think in that case we should add a hint to the input saying that capital letters, special chars, etc are not allowed

This can be handled in the PR.

**Comment by trjExpensify** [comment] 2023-01-12 16:30
>initially, the input should only be validated once blurred, but after the user has "touched" that input we should also validate onChange.

@luacmartins why isn't this consistent across all Forms in /App? 😕

**Comment by luacmartins** [comment] 2023-01-12 16:32
@trjExpensify all pages that use Form have this behavior. Is there a specific case using Form that does not?

**Comment by trjExpensify** [comment] 2023-01-12 17:27
Ah, I thought the name field on the debit card form for example wasn't working that way - but it's actually a valid name with a bunch of special characters if it begins with a letter it seems. 😅 

Cool, that's settled then! We're just waiting on @sketchydroide to approve as per [this comment](https://github.com/Expensify/App/issues/13676#issuecomment-1378229848)? 

>I'll update the guidelines to add that bit of information.

Thanks!

**Comment by mallenexpensify** [comment] 2023-01-12 23:13
Thanks for the patience and feedback everyone. I'm new to form guidelines.  I wasn't proposing we go rogue with this one box, it just didn't make sense to me why we'd let someone _do something_ if we know it won't be accepted.

**Comment by trjExpensify** [comment] 2023-01-13 00:01
Sahweet. @mallenexpensify do you want to update the OP? I think we're good to go here.

**Comment by trjExpensify** [comment] 2023-01-13 00:02
@luacmartins I'm going to take the `reviewing` label off for your guidelines updates.

**Comment by luacmartins** [comment] 2023-01-13 00:02
@mallenexpensify all good! I think the idea is that we give the user a chance to initially fully edit the input, maybe they made a mistake and can correct it before seeing a jarring error message. That's different than validating onChange after the user has touched and was done editing that input.

**Comment by mallenexpensify** [comment] 2023-01-13 20:12
Updated title to
> [$1000] New Room - Capital letters is converted to lowercase when all caps is enable

OP to 
## Expected Result:
Capital letters is visible until an area outside of the field is tapped.  
~Capital letters is not visible and transaction is smooth when all caps is enabled~

## Actual Result:
Capital letter changes to lowercase. 
~Capital letters is visible and transaction isn't smooth when all caps is enable~

If that's not correct, please update again.

**Comment by mallenexpensify** [comment] 2023-01-16 18:08
Awaiting proposals

**Comment by s77rt** [comment] 2023-01-16 21:40
@mallenexpensify 
> Capital letters is visible until an area outside of the field is tapped.

What would happen after an area outside of the field is tapped? Convert the capital letters to lower case?

**Comment by mallenexpensify** [comment] 2023-01-16 22:24
> What would happen after an area outside of the field is tapped?

- The error message would show 
- The capital letters would continue to show
- Once the characters that are causing the error message are removed the error message will stop showing. 

This is my understanding @s77rt

**Comment by thesahindia** [comment] 2023-01-17 16:14
Not sure why melvin added Reviewing label. @mallenexpensify let's remove it.

**Comment by thesahindia** [comment] 2023-01-17 16:15
We are just waiting for @sketchydroide's decision on https://github.com/Expensify/App/issues/13676#issuecomment-1378229848

**Comment by mallenexpensify** [comment] 2023-01-17 23:10
Removed the `Reviewing` label, @sketchydroide please review https://github.com/Expensify/App/issues/13676#issuecomment-1378229848

**Comment by sketchydroide** [comment] 2023-01-18 12:06
I think I'm going with @jatinsonijs for doing the solution.
He changes the error message and show the code changes that @hungvu193 while having a similar/same solution did not (at least I did not find one while combing through the posts).

**Comment by jatinsonijs** [comment] 2023-01-18 13:04
Thanks @sketchydroide, applied on Upwork.

@thesahindia Can you plz let me know from where I can confirm translation ?

**Comment by jatinsonijs** [comment] 2023-01-18 13:06
I'm using

Spanish:  Los nombres de las habitaciones solo pueden incluir letras minúsculas, números y guiones
English: Room names can only include lowercase letters, numbers and hyphens

Need confirmation

**Comment by sketchydroide** [comment] 2023-01-18 13:07
> Can you plz let me know from where I can confirm translation ?

I'll get that done for you, we normally ask in an internal slack channel where the native Spanish speakers can chime in.

**Comment by sketchydroide** [comment] 2023-01-18 13:10
I would say `Los nombres de las salas solo pueden contener letras minúsculas, números y guiones` is the correct one, but will check, `habitaciones` is really about where people live in.

**Comment by jatinsonijs** [comment] 2023-01-18 13:14
Ok @sketchydroide waiting for your confirmation, I have converted English to Spanish with google translate may be its incorrect.

**Comment by sketchydroide** [comment] 2023-01-18 13:20
No worries, yeah, the translation from Google is not completly incorrect, it's one of those context changes translations things

**Comment by sketchydroide** [comment] 2023-01-18 13:29
ok got a confirmation to `Los nombres de las salas solo pueden contener minúsculas, números y guiones` for the Spanish

**Comment by jatinsonijs** [comment] 2023-01-18 13:33
Ok @sketchydroide English string suggested here  https://github.com/Expensify/App/issues/13676#issuecomment-1378110620

I'm going to add these. will submit PR within 1 hour

**Comment by jatinsonijs** [comment] 2023-01-18 13:41
@sketchydroide - PR checklist any non-english text was added/modified, I verified the translation was requested/reviewed in #expensify-open-source and it was approved by an internal Expensify engineer. Link to Slack message:

can you plz give me confirmation on slack channel I'll add link in PR checklist.

**Comment by jatinsonijs** [comment] 2023-01-18 14:24
[PR](https://github.com/Expensify/App/pull/14383) is ready for review

cc @thesahindia

**Comment by mallenexpensify** [comment] 2023-01-19 01:59
Hired @jatinsonijs, thanks for the quick PR. 
@thesahindia can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01773a5a2201587c50

**Comment by thesahindia** [comment] 2023-01-19 08:01
Accepted!

**Comment by mallenexpensify** [comment] 2023-02-02 23:17
Testrail GH created https://github.com/Expensify/Expensify/issues/260050  

@thesahindia @sketchydroide @madmax330 can you review and take action on the top 3 in the checklist plz, then we can close  https://github.com/Expensify/App/issues/13676#issuecomment-1400733709

**Comment by mallenexpensify** [comment] 2023-02-04 00:49
K, I checked them off then.  @thesahindia are C+ able to check off boxes? Can't remember

**Closed by mallenexpensify** 2023-02-04 00:49 UTC
Labels: Reviewing, External, Weekly, Awaiting Payment, Bug
