### ISSUE TITLE
Badge is shown though there is no outstanding IOU for a chat of a High Traffic account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12850] opened 2022-11-17 23:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with HT account
3. Select any user in LHN

## Expected Result:
Chat conversation should be loaded

## Actual Result:
Chat conversation is not loading for High Traffic account

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

All the platforms

**Version Number:** 1.2.29.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**Email or phone of affected tester (no customers):** applausetester+0901abb@applause.expensifail.com

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/202582002-ed6a5912-1462-421c-88e0-46649fa47b4d.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

## Upwork Automation - Do Not Edit
- Upwork Job URL: https://www.upwork.com/jobs/~01f9455eddfbef1f61
- Upwork Job ID: 1593580920123850752

**Comment by markarmanus** [comment] 2022-11-18 14:02
@rushatgabhane is it possible to get the login details for the account, to reproduce the issue ?

**Comment by chrispader** [comment] 2022-11-22 14:45
I will have a look at this!

**Comment by cristipaval** [comment] 2022-11-22 20:27
Looking forward to your proposal, @chrispader!

**Comment by aldo-expensify** [comment] 2022-11-23 21:18
@kbecciv how can I get the password for applausetester+0901abb@applause.expensifail.com for testing?

**Comment by kbecciv** [comment] 2022-11-23 21:18
Feya86Katya

**Comment by aldo-expensify** [comment] 2022-11-23 23:34
I failed to reproduce in Android, I can open the conversation with "hello" (email: applausetester+033122abb@applause.expensifail.com reportID: 92050010).

I think these are the logs of OpenReport:

[76bbc8a03b7eff88-SJC](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2276bbc8a03b7eff88-SJC%22)+AND+timestamp:[2022-11-17T21:08:12.924Z+TO+2022-11-17T23:08:12.924Z]&index=logs_expensify-019558)
[76bbc89d0ea5ff88-SJC](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2276bbc89d0ea5ff88-SJC%22)+AND+timestamp:[2022-11-17T21:08:12.390Z+TO+2022-11-17T23:08:12.390Z]&index=logs_expensify-019558)

There are some errors that look bad, but it may be nothing as well

<img width="509" alt="image" src="https://user-images.githubusercontent.com/87341702/203663019-44bd5cf2-ba23-4dea-8bb9-6f2d7731cf40.png">

========================

I noticed that if you open the chat with applausetester+1217abb@applause.expensifail.com (reportID: 85684318), it stays blank and the request to OpenReport returns an error:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/87341702/203663507-56f79303-53d8-4df2-a4b9-40c3bedcc936.png">


It is also not possible to clear the error from the UI. This seems to be a bug with that particular report so it looks like a different issue.

**Comment by NicMendonca** [comment] 2022-11-25 18:44
^ updated the price as I missed that earlier - sorry!

**Comment by aldo-expensify** [comment] 2022-11-25 19:49
@kbecciv is this still reproducible? the chat that didn't load was with the account with name "hello", right?

**Comment by kbecciv** [comment] 2022-11-25 20:01
@aldo-expensify Let me check with latest build

**Comment by kbecciv** [comment] 2022-11-25 20:06
@aldo-expensify The account with name "hello" is loaded, but details page is empty. Tested build version is 1.2.31.8

https://user-images.githubusercontent.com/93399543/204050754-0c17a789-a014-4db9-958f-e0142c91599b.mp4

**Comment by aldo-expensify** [comment] 2022-11-25 20:27
> @aldo-expensify The account with name "hello" is loaded, but details page is empty. Tested build version is 1.2.31.8
> 
>  Screen_Recording_20221125-150323_New.Expensify.mp4

It looks like you are tapping in the green badge showing the amount owed. I see that this is normal behaviour:


https://user-images.githubusercontent.com/87341702/204052339-725b359d-bd6c-4229-9a1c-4710db3d1124.mov



If you tap in the name/email, it should take you the personal details

**Comment by mountiny** [comment] 2022-11-28 08:52
@aldo-expensify I think there should be details about the report actions though (XYZ requested $0.11 from you)

**Comment by mountiny** [comment] 2022-11-28 09:05
I think the issue is that it should not be showing the badge: 
<img width="966" alt="image" src="https://user-images.githubusercontent.com/36083550/204235604-76a9fe2c-113e-4cf1-a3de-ddec5df26fee.png">


There is this error in the console which applies to this IOU report, I think this must be related, there are request in the report but total is definitely not $0.11

I am afraid this must be internal cc @NicMendonca 

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/36083550/204237171-0f7e40ac-4849-4307-8af9-1f43f8172d26.png">

**Comment by aldo-expensify** [comment] 2022-11-28 18:48
Ohh, good catch @mountiny, agreed

**Comment by mountiny** [comment] 2022-11-29 16:46
> Do you guys want to work on it? I can investigate it based on your findings, just making sure I'm not spending effort on the same thing as you.

At the moment I have my plate full, but feel free to tag me for a review.

What I would recommend tho is to look at this Web PR https://github.com/Expensify/Web-Expensify/pull/35588 and its associated App PR https://github.com/Expensify/App/pull/12759 which might also remove this console error. 

Also we should update the issue body and title based on the finding here https://github.com/Expensify/App/issues/12850#issuecomment-1327867977 as at the mooment that is misleading the original issue seems to not occur anymore.

**Comment by aldo-expensify** [comment] 2022-11-29 18:46
> At the moment I have my plate full, but feel free to tag me for a review.

Same! feel free to work on it

**Comment by mountiny** [comment] 2022-11-30 10:44
It also might be something weird in database for this specific chat/ account so if we would be able to find some more specific reproduction steps for general high traffic account or normal account that would be great!

**Comment by cristipaval** [comment] 2022-12-09 09:59
@kbecciv Did this error occur to any other reports in any other account? I am wondering if it could be abug with this particular report.

**Comment by cristipaval** [comment] 2022-12-12 18:11
Thanks!

**Comment by kbecciv** [comment] 2022-12-12 18:52
Issue is not reproduced for two others HT accounts. 

https://user-images.githubusercontent.com/93399543/207129877-ef72db2d-aaf5-4657-8367-611b0e506864.mp4


https://user-images.githubusercontent.com/93399543/207129896-b4294e93-d899-4cae-9aa6-5d5af69b378e.mp4

**Comment by cristipaval** [comment] 2022-12-12 20:39
Sorry for the confusion @kbecciv ! [Here](https://github.com/Expensify/App/issues/12850#issuecomment-1328748392) we realised that the issue is that the badge should not be shown for that specific report, and that's the reason why the details about the report actions are not listed (XYZ requested $0.11 from you). Could you check if this is reproducible? I could reproduce it for any other report.

**Comment by kbecciv** [comment] 2022-12-13 16:15
Checking

**Comment by kbecciv** [comment] 2022-12-13 16:21
@chrispader Yes, the details about the report actions are not listed for two of my accounts (hello and  applausetester+1217abb@applause.expensifail.com), and chat is not loading for applausetester+1217abb@applause.expensifail.com as well.
Please attached the video, build 1.2.38.5

https://user-images.githubusercontent.com/93399543/207387242-411a644e-34e6-4920-8790-64eddcc20b95.mp4

**Comment by cristipaval** [comment] 2022-12-15 22:54
ok, to clarify. Looks like we have 2 issues here (I can reproduce both of them on your account) but I cant reproduce with other accounts/reports)
1. Chat with applausetester+1217abb@applause.expensifail.com does not load.
2. IOU details are not listed for chats with _applausetester+1217abb@applause.expensifail.com_ and _hello_

According to the comments we have above, we started by trying to fix the first issue, but then we ended hunting the second bug.

**Comment by cristipaval** [comment] 2022-12-15 22:57
I just spent some time investigating the first issue and I found that when the user navigates to the chat with applausetester+1217abb@applause.expensifail.com, the App does not fire the `OpenReport` api command. I am going to investigate a bit more to see why this doesn't happen.

**Comment by trjExpensify** [comment] 2022-12-16 14:28
@cristipaval I think this is because the account applausetester+1217abb@applause.expensifail.com has been closed when there were outstanding IOUs to settle: 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/16232057/208114927-7a0a9f1d-2623-4c7c-91fb-5844942cbe86.png">

Seems like we're running into this in a few places. As far as I can tell, the case you've come across is the same as the first one I highlight [here](https://github.com/Expensify/App/issues/13634#issuecomment-1353900222).

We're supposed to be canceling/declining any IOUTransactions when a user goes to close their account after these two PRs ([Auth](https://github.com/Expensify/Auth/pull/7228)/[Web](https://github.com/Expensify/Web-Expensify/pull/35453)). But in the case of when the **closed account user is owed** something doesn't seem to be working as expected.

If you agree with my hunch, I think we need to probably consolidate these issues and clean it up. 

1. Figure out why when a member closes their account we don't reject the outstanding IOUTransactions in both cases (they are owed money / they owe money)
2. Actually surface that's going to happen to the user, so they are aware of the consequences of closing their account before they do
3. The above two items get us into a cleaner spot, then we should more broadly consider how DMs with closed accounts should work. I.e why aren't they archived, just like rooms? Why can you still request money from someone who's actively closed their account, and further why do you still get email summaries when the NotifyOfflineUsersAboutActivity job runs when you've closed your account? 

For item 2, I created [this issue](https://github.com/Expensify/App/issues/13416). In fact, I created it for 1 as well, as I didn't know this kinda' partially worked, but seemingly only in the _closed account owes money_ state. It's currently assigned to @deetergp, but he hasn't started working on it and I'm sure he wouldn't mind if you wanted to lead the charge on it. 

For item 3, I outlined it in [this issue](https://github.com/Expensify/App/issues/13426) and popped it on hold for WAQ.

**Comment by cristipaval** [comment] 2022-12-19 18:29
Hey @trjExpensify ! Thanks a lot for your comment! 
I think you are right and as you also mentioned [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463692571549) this has the same root cause as the other issues linked by you. I am happy to jump on your proposed approach.

**Comment by trjExpensify** [comment] 2022-12-20 11:41
>One thing I am still wondering is: Could be possible that the item 1 from my comment https://github.com/Expensify/App/issues/12850#issuecomment-1353816868 is occurring due to the same issue? I mean because the account was closed while having outstanding IOUs?

Yeah, it's probably likely, but a good one to test once we fix the logic to make sure we are canceling outstanding IOU transactions in the case where you're owed money when you close your account (like we are when you owe money which works without issue). 👍

**Comment by cristipaval** [comment] 2022-12-22 15:07
I looked at the code which cancels the IOU transactions when closing an account. The thing that caught my eye is that the IOU transaction is canceled only if the user is the manager of that report (see code [here](https://github.com/Expensify/Web-Expensify/blob/a336408add6e52d88005d70e6be2e4d3b3fc5e34/lib/UserAPI.php#L1541-L1543)). I am going to ask for help on Slack as I need to understand what is a report manager (I guess it's a role with some permissions on the report) and what kind of transactions we have on a report. I want to better understand the impact of my changes.

**Comment by cristipaval** [comment] 2022-12-22 21:34
@trjExpensify I tested more having your hunch on my mind and I could reproduce the other issue as well (chat does not load). What I can tell is that it happens when the close account operation fails due to multiple possible exceptions. By canceling all outstanding IOUs we narrow down the possible exceptions that could be thrown.

**Comment by marcaaron** [comment] 2023-01-02 17:52
>we should more broadly consider how DMs with closed accounts should work. I.e why aren't they archived, just like rooms? Why can you still request money from someone who's actively closed their account, and further why do you still get email summaries when the NotifyOfflineUsersAboutActivity job runs when you've closed your account?

IIRC it has always been a built-in feature of chat reports that they would never get closed. I think that initially stemmed from the support requirement where people who have closed their accounts may still need to interact with Concierge. And my _guess_ would be we just extended that out to all chat reports.

**Comment by cristipaval** [comment] 2023-01-12 20:44
I don't know why Melvin didn't close this one. [PR](https://github.com/Expensify/Web-Expensify/pull/35903) is in production.

**Closed by cristipaval** 2023-01-12 20:44 UTC
Labels: Reviewing, Daily, Internal, Bug
