### ISSUE TITLE
[$500] [CRITICAL] Backwards Compatibility: Scheduled Submit is not working on the `NewDot Test Workspace - Contractors`

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35298] opened 2024-01-29 06:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706287561831329

## Action Performed:
1. Set up auto submit (daily) for the expense reports in the OD 
2. Create an expense report on the workspace chat `NewDot Test Workspace - Contractors`
## Expected Result:
Should get submitted as per the auto schedule option selected
## Actual Result:
Not submitted automatically
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [X] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0171e9448ec33f398b</li>
        <li>Upwork Job ID: 1752724328754946048</li>
        <li>Last Price Increase: 2024-01-31</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2024-01-31 19:42
Starting leave so re-assigning!

**Comment by mallenexpensify** [comment] 2024-02-02 01:52
@danieldoglas , this needs to be internal... right?

**Comment by danieldoglas** [comment] 2024-02-02 14:57
Yep, it does. I think it will fit into #wave5 or #wave6 since it's related to submitting receipts

**Comment by mallenexpensify** [comment] 2024-02-03 00:56
Thanks @danieldoglas , added to Wave 5 and commented in that room 
https://expensify.slack.com/archives/C05DWUDHVK7/p1706921786138959

**Comment by mallenexpensify** [comment] 2024-02-07 00:08
bumping to weekly since it was applied a status on the Wave5 project

**Comment by greg-schroeder** [comment] 2024-02-20 06:34
I think this is actually a Critical bug as it means OldDot scheduled submit settings aren't being respected in NewDot. Is this reproducible @mallenexpensify @ntdiary?

**Comment by greg-schroeder** [comment] 2024-02-20 09:01
All right I'll ask QA to check

**Comment by puneetlath** [comment] 2024-02-20 20:56
Closing based on: https://expensify.slack.com/archives/C02MW39LT9N/p1708453407651559

**Closed by puneetlath** 2024-02-20 20:56 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Help Wanted, Bug, retest-weekly
