### ISSUE TITLE
[$250] Tooltip - Search tooltip overlaps workspace name and chats

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35739] opened 2024-02-02 23:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.36-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Hover over Search input field

## Expected Result:
Search tooltip should no overlaps other sections

## Actual Result:
Search tooltip overlaps workspace name and chats

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6365389_1706912074926!image](https://github.com/Expensify/App/assets/78819774/9e1fcc4c-6bbd-41d8-a02a-15dd45772606)

https://github.com/Expensify/App/assets/78819774/3ccfd1d4-31b4-4222-bb00-bd9bc0b12aa5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0100ed7c59c5352067</li>
        <li>Upwork Job ID: 1753585052733321216</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-02 23:18
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by jeremy-croff** [comment] 2024-02-03 03:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search input has a tooltip that overlaps workspace name

### What is the root cause of that problem?
A tooltip is used in the wrong manner. Tooltips should not be on interactive elements like this search input, it's a bad design practice and might have been added accidentally. The tooltip will show each time you try to search. Inputs have placeholder text to give contexts, and that's what should be relied on.

### What changes do you think we should make in order to solve the problem?
Remove the tooltip from the search bar all together.

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-02-05 12:24
Not a blocker, tiny issue

Actually curious if this is an issue we have to solve, seems like really minor thing for me and the tooltip will always have to overlap something.

@dannymcclain what do you think, should we close this?

**Comment by dannymcclain** [comment] 2024-02-05 14:08
@mountiny Definitely think we should close this. This looks to be working exactly as expected/intended. By their nature/design, tooltips should sit "above" everything—that's the whole point. Since they're temporary (only showing on hover), I don't think we care what they're overlapping while they're open.

**Comment by jeremy-croff** [comment] 2024-02-05 15:07
> @mountiny Definitely think we should close this. This looks to be working exactly as expected/intended. By their nature/design, tooltips should sit "above" everything—that's the whole point. Since they're temporary (only showing on hover), I don't think we care what they're overlapping while they're open.

What are your thoughts of my proposal of this tooltip being a complete redudancy? The placeholder text of the search already gives the contextual information. No need to show the tooltip everytime you search.

**Comment by dannymcclain** [comment] 2024-02-05 16:07
That's a good point—it doesn't seem totally necessary. @Expensify/design - any thoughts on this?

**Comment by shawnborton** [comment] 2024-02-05 17:08
Yeah that makes sense to me, the tooltip is supposed to add additional information that otherwise isn't viewable on the particular piece of UI. It does seem totally redundant in this case. 

That being said though, having a tooltip overlap something else on the screen is definitely not a bug either. So I'm not even sure how this was reported as a bug in the first place. But I do tend to agree, we can just remove it.

**Comment by mountiny** [comment] 2024-02-05 18:56
I think its quite common to have the tooltips kinda everywhere (even if they might be redundant) so I will choose to do nothing on this one and close it

Thank you for chiming in and please comment if you strongly disagree

**Closed by mountiny** 2024-02-05 18:56 UTC
Labels: External, Engineering, Daily, Design, Help Wanted
