### ISSUE TITLE
[$1000] mWeb - On long pressing the email, it gets hidden

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21814] opened 2023-06-28 15:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND
2. Go to any chat
3. Write an email
4. Long press on the email

## Expected Result:
 Email is visible while long pressing

## Actual Result:
It gets covered with something

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Chrome
- [ ] MacOS / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/76769439-c099-4438-be48-4ef29bfeaca6

https://github.com/Expensify/App/assets/93399543/ff72c316-80c7-41dc-86ab-cfd6f35c2bc4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @aman-atg
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687865157005019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb32c4e83f4bd1d0</li>
        <li>Upwork Job ID: 1674340170292715520</li>
        <li>Last Price Increase: 2023-06-29</li>
    </ul>
</details>

**Comment by cubuspl42** [comment] 2023-06-28 17:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

On iOS, on Chrome and Firefox (maybe all browsers using the WebKit web view), when the user long-presses a link, confusing drag-and-drop interaction starts, effectively covering the link.

### What is the root cause of that problem?

The long-press behavior for links on the WebKit web view seems to be inconsistent with that in the actual Safari browser.

### What changes do you think we should make in order to solve the problem?

We can add a `-webkit-user-drag: none` style for `AnchorForCommentsOnly` on Web. This disables the unexpected drag-and-drop interaction on non-Safari iOS browsers.

```js
export default {
    userDragNone: {
        WebkitUserDrag: 'none',
    },
};
```

```js
function AnchorRenderer(props) {
    // ...
    
    return (
        <AnchorForCommentsOnly
            // ...
            style={{...props.style, ...parentStyle, ...styles.textUnderlinePositionUnder, ...styles.textDecorationSkipInkNone, ...styles.userDragNone}}
            // ...
        >
            <TNodeChildrenRenderer tnode={props.tnode} />
        </AnchorForCommentsOnly>
    );
}
```

**Comment by conorpendergrast** [comment] 2023-06-29 08:51
Yep, got the same effect: 

<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/5802477/249721455-6a8ddacd-e7d2-4cd9-b0ea-8c773da7da51.jpeg" width="300" />

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 20:32
Actually, it's not hiding it becomes a draggable element, if you start dragging the element we could see that email

https://github.com/Expensify/App/assets/85645967/0d82f942-1c85-4535-8b56-427203356fa2

@conorpendergrast This could be a useful feature too on Desktop/Web as well. See I'm dragging and dropping email in notepad here. There could be another case that we are unaware of, are we sure want to disable this?

https://github.com/Expensify/App/assets/85645967/f078658a-488e-45e2-8040-e5aa79a134cf

**Comment by Santhosh-Sellavel** [comment] 2023-06-29 21:00
I think Maybe do-nothing is fine for this now.

**Comment by cubuspl42** [comment] 2023-06-30 04:00
> I think Maybe do-nothing is fine for this now.

Why? Because it is still a bug, isn't it?

**Comment by conorpendergrast** [comment] 2023-06-30 15:43
Great point, thanks for showing why that box appears. On mobile (at least on iOS) that seems to have no value, as you haven't can't actually "do" anything when you drag-and-drop.

I do see the use on OSX, but you can get the same effect through right-click > **Copy email to clipboard**.

So it seems like it has minimal value, but changing that would be a feature request rather than a bug. I agree that it isn't a bug (it's working as-designed).

Closing as not a bug

**Closed by conorpendergrast** 2023-06-30 15:43 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by cubuspl42** [comment] 2023-07-03 11:47
@conorpendergrast I'm surprised by the call to call this "working as intended" to the point that I'll ensure that we're on the same page.

In Expensify, including the mWeb, we have a **custom**  interaction for a long-press on a link. It's to display a context drawer with a "Copy URL to clipboard" button.

This is the intended behavior triggered by the long-press gesture on a link (the "google.com" link is being long-pressed):

https://github.com/Expensify/App/assets/2590174/29c88f4b-3ff8-4029-9d92-a8c5e4179a8d

The behavior we're discussing in this issue is when (on non-Safari iOS browsers, like Chrome or Firefox) **two different interactions** are being triggered by the long-press gesture:
- the native drag-and-drop interaction (bonus problem: confusing styling which makes it look like a black rounded rectangle)
- the custom interaction of showing the bottom context drawer

Is this the "working as-designed" behavior?
