### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Web - Right click popup is stuck on search page open

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27244] opened 2023-09-12 12:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Right click on any message to open popup
4. Click on 'Add reaction' in popup
5. Again right click on same message to again open popup
6. Click CTRL+K/ CMD+K and observe that popup is stuck and displayed along with search page

## Expected Result:
App should close the right click popup before opening search page

## Actual Result:
App does not close right click popup before opening search page if we follow specified steps

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.68.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/90b63b32-85ac-43ca-bcbf-e002fe92ac78

https://github.com/Expensify/App/assets/93399543/e757868c-be68-4f9f-841c-215cb6c4b40b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694190244716599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012411f85dfeed7435</li>
        <li>Upwork Job ID: 1701568949405835264</li>
        <li>Last Price Increase: 2023-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 27108241</li>
<li>tsa321 | Contributor | 27108242</li>
<li>dhanashree-sawant | Reporter | 27108243</li>
</ul></li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-12 12:47
It seems to be expected behavior.

**Comment by paultsimura** [comment] 2023-09-12 15:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If the context menu on ReportItem was opened after the EmojiPicker, the cmd+k (open search) doesn't close the context menu modal.

### What is the root cause of that problem?


### What changes do you think we should make in order to solve the problem?
In `ReportActionContextMenu.showContextMenu`:

https://github.com/Expensify/App/blob/017c714cfafeccdd63a687870a8613bfcd053fa3/src/pages/home/report/ContextMenu/ReportActionContextMenu.js#L52-L94

Along with `hideContextMenu()`, we should also call:

```js
EmojiPickerAction.hideEmojiPicker(false);
```

### What alternative solutions did you explore? (Optional)

**Comment by mollfpr** [comment] 2023-09-12 15:08
>in PopoverWithMeasuredContent there is not click outside function.Therefore, whenever you click outside it stays there.

@nahid633 I don't understand this, and why this issue is only reproduced after the second right-click?

**Comment by paultsimura** [comment] 2023-09-12 15:14
@mollfpr I've just updated [my proposal](https://github.com/Expensify/App/issues/27244#issuecomment-1715898219) with all the related videos, so now it's the final version, sorry for a couple of edits.

**Comment by mollfpr** [comment] 2023-09-12 15:14
@paultsimura It seems you have the correct RCA. Could you elaborate on the proposed solution and why calling the hideEmojiPicker will fix the issue?

**Comment by paultsimura** [comment] 2023-09-12 15:31
@mollfpr sure. This will eliminate the race condition – by calling `EmojiPickerAction.hideEmojiPicker(false)` we are explicitly calling the `setIsOpen(false)` on EmojiPicker's `PopoverContextProvider` before opening the ContextMenu popover.

So now the flow is correct:
1. Close EmojiPicker
2. Open ContextMenu


https://github.com/Expensify/App/assets/12595293/209bb89c-3152-47c8-ae1c-d8fd2ff9f088

**Comment by mollfpr** [comment] 2023-09-12 15:36
@Pluto0104 Why is that?

**Comment by Pluto0104** [comment] 2023-09-12 15:39
@mollfpr I'm looking for the best solution. of course, @paultsimura's solution might handle this issue. could you please give me some time?

**Comment by Pluto0104** [comment] 2023-09-13 03:30
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
After opening a left-click popup, if we open a right-click popup, the right-click popup gets stuck when we open RHP or the Keyboard Shortcut Modal using a keyboard shortcut.
### What is the root cause of that problem?
The root cause is that various popovers, such as `ReportActionItemContextMenu` and `FloatingActionButtonAndPopover`, create a race condition.

We set a keyboard shortcut listener in this code snippet:
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/libs/Navigation/AppNavigator/AuthScreens.js#L162-L195

We close opened modals here:
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/libs/Navigation/AppNavigator/AuthScreens.js#L171

This function closes the modal using the registered `closeModal` function:
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/libs/actions/Modal.js#L22-L33

We set the function using the `setCloseModal` function here:
https://github.com/Expensify/App/blob/2d5bea5b58079506337d21d2ba94a3e295882f94/src/components/PopoverWithoutOverlay/index.js#L28-L41

When a race condition occurs, as shown in this video, the app triggers the old modal close finally. In this case, we would invoke `setCloseModal` with `null`, so we can't close the modal using the keyboard shortcut.

https://github.com/Expensify/App/assets/136573674/960b81df-b6a3-4bef-b15e-312c6844619e


### What changes do you think we should make in order to solve the problem?
I suggest changing the Modal action as follows:
```js
let isOpenedBeforeCloseModal = false;

function setCloseModal(onClose) {
    if (onClose) {
        isOpenedBeforeCloseModal = !!closeModal;
        closeModal = onClose;
    } else if (isOpenedBeforeCloseModal) {
        isOpenedBeforeCloseModal = false;
    } else {
        closeModal = onClose;
    }
}
```
This function should work properly in normal cases and only work differently in the case of race conditions, as shown in this video:

https://github.com/Expensify/App/assets/136573674/47c3157f-ca96-49b5-b571-243eb95a4703


### What alternative solutions did you explore? (Optional)
Alternatively, we can add keyboard shortcut keys to this listener. Currently, `PopoverProvider` handles only the Escape key.
https://github.com/Expensify/App/blob/5f668c669a501a94caebbb434a656580e3bcfb24/src/components/PopoverProvider/index.js#L63-L74

### Result

https://github.com/Expensify/App/assets/136573674/981fe058-274d-4e99-a73d-d866a771cc68

**Comment by Pluto0104** [comment] 2023-09-13 10:46
@mollfpr could you please review ⬆️ ?

**Comment by mollfpr** [comment] 2023-09-13 12:21
@paultsimura This issue isn't specific to the emoji picker. You can also reproduce it by opening the FAB menu.


https://github.com/Expensify/App/assets/25520267/d5891493-954b-4eb9-bc2a-c0343ce62819


---

>After opening a left-click popup, if we open a right-click popup, the right-click popup gets stuck when we open RHP or the Keyboard Shortcut Modal using a keyboard shortcut.

@Pluto0104 I am trying to understand the race condition here between the left-click and right-click? Why does that happen? Why it's not stuck on the opposite?

**Comment by Pluto0104** [comment] 2023-09-13 12:31
@mollfpr I'm just curious about that 😄, but it seems that the `FloatingActionButtonAndPopover` opens after the `ReportActionItemContextMenu` is closed. I think the `ReportActionItemContextMenu` is simpler in terms of state management and component structure, so it appears to be faster. Therefore, I believe the opposite one is not as structured.

**Comment by mollfpr** [comment] 2023-09-13 17:18
@Pluto0104, we should find the correct answer for that before moving forward.

**Comment by paultsimura** [comment] 2023-09-13 21:03
## Proposal

Updated proposal https://github.com/Expensify/App/issues/27244#issuecomment-1715898219

@mollfpr I can provide more details on why the race condition happens, if needed.

**Comment by Pluto0104** [comment] 2023-09-14 14:20
@mollfpr, I believe I have identified the correct root cause, so I have updated my proposal. 😄 Please review it again.

**Comment by Pluto0104** [comment] 2023-09-15 02:42
@mollfpr, I believe I have identified the correct root cause, so I have updated [my proposal](https://github.com/Expensify/App/issues/27244#issuecomment-1716887009). 😄 Please review it again.

**Comment by mollfpr** [comment] 2023-09-15 04:24
@paultsimura I think we can't remove that, it's already asked by @Pluto0104 [here](https://github.com/Expensify/App/pull/3931/files#r1325206698)

@Pluto0104 Where the hooks be placed? Every time there's a new shortcut, should we add the hooks to that key?

**Comment by Pluto0104** [comment] 2023-09-15 15:03
@mollfpr

> Where the hooks be placed?

The hooks are placed in [PopoverProvider/index.js](https://github.com/Expensify/App/blob/main/src/components/PopoverProvider/index.js). We're implementing the logic to close the popover in that file.

> Every time there's a new shortcut, should we add the hooks to that key?

Yes.

**Comment by mollfpr** [comment] 2023-09-15 16:18
>Every time there's a new shortcut, should we add the hooks to that key?

@Pluto0104 We can't do this. The fix should be done once and for all.

**Comment by Pluto0104** [comment] 2023-09-15 16:21
Umm, what about my alternative solution?

**Comment by mollfpr** [comment] 2023-09-15 16:23
>However, my proposed solution offers greater consistency compared to this alternative. Additionally, I'm uncertain whether this alternative might lead to a regression or not.

@Pluto0104 I don't understand the point of the code and you can't make sure if it's regression-free.

**Comment by Pluto0104** [comment] 2023-09-15 16:28
@mollfpr Haha, yeah. I couldn't be absolutely certain about that, but I've tested it numerous times, and I haven't encountered any regressions. So, I'm inclined to believe it's a good solution. However, I'm also considering that we might want to avoid making changes to high-frequency reusable components.

**Comment by Pluto0104** [comment] 2023-09-15 16:35
The purpose of the code is to bypass setting to null when a race condition occurs. As I explained in my root cause analysis, in that scenario, the call stack might be "close, close, null". In normal cases, it would be "close, null, close". So, with this solution, I aimed to prevent such situations. If onClose isn't reset to null, it allows us to close the modal using a keyboard shortcut. @mollfpr if you have any questions, please feel free to reach out me.

**Comment by paultsimura** [comment] 2023-09-16 10:42
## Proposal

Updated proposal https://github.com/Expensify/App/issues/27244#issuecomment-1715898219

FYI: @mollfpr

**Comment by Pluto0104** [comment] 2023-09-26 16:28
no, @aimane-chnaif we can stile reproduce this issue. please follow such steps:
1. Click FAB
2. Click Right-click on ReportActionItem to open the context menu.
3. Hit the Keyboard shortcuts.

**Comment by Pluto0104** [comment] 2023-09-28 06:39
> @Pluto0104 We can't do this. The fix should be done once and for all.

@mollfpr We can do that at once. I updated [my main solution.](https://github.com/Expensify/App/issues/27244#issuecomment-1716887009) could you please check it?

**Comment by kevinksullivan** [comment] 2023-09-29 08:12
Closing unless this is reproducible

**Comment by paultsimura** [comment] 2023-09-29 08:16
@kevinksullivan it's very much reproducible in production:

https://www.loom.com/share/4dc0a7639eb943348558b22097424af9?sid=699fac38-fb22-4ad2-b211-5aa2f2a75e24

**Comment by kevinksullivan** [comment] 2023-09-29 08:23
Thanks. Waiting on @mollfpr then

**Comment by mollfpr** [comment] 2023-10-02 16:04
@tsa321 I see you have a different RCA in your proposal. Why does this issue only reproduce on the opening of a popover with a left click (e.g. FAB) and then right-click on a report action to open the context menu?

**Comment by kevinksullivan** [comment] 2023-10-03 22:41
Still reviewing proposals

**Comment by mollfpr** [comment] 2023-10-04 15:57
@tsa321 With your solution, we don't need `Modal.setCloseModal` at the end of the function?

https://github.com/Expensify/App/blob/ab821e5a62121123752440fc2faf31bf0403b487/src/components/PopoverWithoutOverlay/index.js#L41-L45

**Comment by mollfpr** [comment] 2023-10-04 16:24
I think the [proposal](https://github.com/Expensify/App/issues/27244#issuecomment-1737048920) from @tsa321 looks good to me, fixing the root cause of the race condition, and the result seems promising.

🎀 👀 🎀 C+ reviewed!

**Comment by paultsimura** [comment] 2023-10-04 16:27
This was a tough one. Good luck @tsa321 💪🏽

**Comment by mollfpr** [comment] 2023-10-09 18:11
Friendly bump @cead22

**Comment by kevinksullivan** [comment] 2023-10-31 14:41
Paid @dhanashree-sawant and @tsa321 . @mollfpr sent you an offer since the other job wasn't letting me pay. Lmk when you accept!

**Comment by mollfpr** [comment] 2023-11-01 09:37
> The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/19011

> The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/19011/files#r1378575720

> A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be enough.

> Determine if we should create a regression test for this bug.
>If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

For macOS Chrome / Desktop:

1. Open any report
2. Click the FAB button, then right-click report action, then Open the search page with cmd + k
3. Notice no popover/context menu is being stuck, and the search page is opened
4. Click emoji picker -> right-click report action -> cmd + k
5. Notice no popover/context menu is being stuck, and search page is opened
6. Right-click context menu -> choose emoji picker inside context menu -> cmd + k
7. Notice no popover/context menu is being stuck, and search page is opened
8. Click the Fab button -> right-click on LHN -> cmd + k
9. Notice no popover/context menu is being stuck, and search page is opened
10. Click any button that triggers popover / context menu with other different combinations -> cmd + k
11. Notice there is no popover/context menu being stuck, and search page is opened

For mobile:

1. Click the emoji picker, fab button, long press report action, and other actions to trigger popover or context menu
2. Verify the components function properly when opening and closing the context menu.

**Comment by cead22** [comment] 2023-11-06 19:22
@mollfpr thanks for identifying the offending PR and commenting on it

> > A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
> 
> The regression step should be enough.

@mollfpr which regression test exactly? And should we discuss this in the open source slack channel?

**Comment by cead22** [comment] 2023-11-06 19:23
@mollfpr thanks for identifying the offending PR and commenting on it

> The regression step should be enough.

Agreed, crossing off this item from the checklist as well, thanks!

**Comment by kevinksullivan** [comment] 2023-11-07 22:17
Payment summary:
- Reporter: @dhanashree-sawant $50
- Contributor: @tsa321 $500
- C+: @mollfpr $500

**Closed** 2023-11-07 22:18 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-12-28 22:14
$500 payment approved for @mollfpr based on comment above.
