### ISSUE TITLE
[READY FOR PAYMENT][$250] Workspace - Blank background displayed when redirected from desktop to connect bank

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44929] opened 2024-07-05 18:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+shch1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/44517
## Action Performed:
1. Sign into a valid account in the desktop app
2. Go to Workspace > Workflow > Connect Bank account
3. In the connect bank account page click on the link please click here to complete this process in a browser.
4. Verify that: User expects to be redirected to the Safari browser and logged into the same account that was signed in on Desktop

## Expected Result:
Workspace chat should be displayed when redirected from desktop to connect bank

## Actual Result:
Blank background displayed when redirected from desktop to connect bank

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5a4b2dfe-eb1a-4474-90cd-704d38b14b62

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010505fec65584f108</li>
        <li>Upwork Job ID: 1810894967577795738</li>
        <li>Last Price Increase: 2024-07-17</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 103162940</li>
<li>dominictb | Contributor | 103162941</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-07-10 04:32
I think this is technically #wave-collect since it's the VBBA flow. Opening up to external.

**Comment by eh2077** [comment] 2024-07-10 14:53
@dominictb Thanks for your proposal! 

The following condition is true
https://github.com/Expensify/App/blob/83be857a0db2dfd3e3f8ba241a5742898fee3462/src/libs/actions/App.ts#L424
if and only if clicking connect bank from desktop right?
https://github.com/Expensify/App/blob/83be857a0db2dfd3e3f8ba241a5742898fee3462/src/pages/ReimbursementAccount/BankAccountStep.tsx#L137

If so, then I think it'll be safe to fix it by removing `Navigation.goBack();` here
https://github.com/Expensify/App/blob/83be857a0db2dfd3e3f8ba241a5742898fee3462/src/libs/actions/App.ts#L428-L429

**Comment by eh2077** [comment] 2024-07-11 14:34
> It works by my side. What about you?

@dominictb However, it doesn’t work on my end


https://github.com/Expensify/App/assets/117511920/f4c0c22f-e530-4365-81eb-2abbed275c15

**Comment by eh2077** [comment] 2024-07-12 13:12
@dominictb I opened the link from dev desktop. How to let it open dev domain on browser?

**Comment by eh2077** [comment] 2024-07-17 03:16
Not overdue waiting for @thienlnam 's review

**Comment by thienlnam** [comment] 2024-08-01 18:02
Yeah, looks like the automation did not work here

**Comment by thienlnam** [comment] 2024-08-07 01:02
@eh2077 Can you complete the regression test here so we can close this out?

**Comment by JmillsExpensify** [comment] 2024-08-07 14:27
Payment summary:

 - Contributor: @dominictb $250 
 - Reviewer: @eh2077 $250

**Comment by JmillsExpensify** [comment] 2024-08-07 14:28
Contributor paid via Upwork. @eh2077 mind completing the checklist so that I can process your payment as well?

**Comment by eh2077** [comment] 2024-08-07 14:59
### Checklist

- [x] [@eh2077] The PR that introduced the bug has been identified. Link to the PR: I can't find the PR caused this bug. Though this bug was found during test PR https://github.com/Expensify/App/pull/44517, but the root cause has been there for quite a while. 
- [x] [@eh2077] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@eh2077] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@eh2077] Determine if we should create a regression test for this bug. Yes, it's related to bank setting though this is an edge case.

### Regression test

1. Sign into a valid account in the desktop app
2. Go to Workspace > Workflow > Connect Bank account
3. In the connect bank account page click on the link please click here to complete this process in a browser.
4. At this point, user expects to be redirected to the Safari browser and logged into the same account that was signed in on Desktop
5. Verify that: Workspace chat should be displayed when redirected from desktop to connect bank, instead of a blank background page

**Comment by JmillsExpensify** [comment] 2024-08-08 00:25
Contributor paid and regression test created. Closing.

**Closed by JmillsExpensify** 2024-08-08 00:25 UTC
Labels: External, Weekly, Awaiting Payment, Bug
