### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [HOLD for payment 2023-10-20] [HOLD for payment 2023-10-20] [$500] Workspace - WS invite page keeps loading in offline if no members present

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27776] opened 2023-09-19 12:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: 2 WS created, one with members and other without members
1. Go to https://staging.new.expensify.com/
2. Tap profile
3. Tap preferences
4. Toggle on forced offline
5. Navigate to LHN
6. Tap profile icon
7. Tap workspaces
8. Tap a workspace with no members
9. Tap members
10. Navigate to workspaces and tap workspace with members
11. Tap members

## Expected Result:
Workspace invite page, in offline, if members are present or not must be displayed properly without loading

## Actual Result:
Workspace invite page displayed properly in offline if members are present. But, the workspace invite page keeps loading in offline if no members are present

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/101837a5-1cdd-4c54-85b9-46fafa8d135a

https://github.com/Expensify/App/assets/78819774/ef8cf6e8-8589-4e05-ae99-7094cd74a8d2

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Intenral Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01441465708e1a51d6</li>
        <li>Upwork Job ID: 1704376130566787072</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 27017314</li>
</ul></li>
    </ul>
</details>

**Comment by nebiyuelias1** [comment] 2023-09-20 07:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loading skeleton is shown for an empty workspace in offline mode. 
### What is the root cause of that problem?
The root cause is that inside the **BaseSelectionList** component we have the following ternary operation:
```
{flattenedSections.allOptions.length === 0 && showLoadingPlaceholder ? (
                            <OptionsListSkeletonView shouldAnimate />
                        ) : (
                            <>
```
If the list size is 0 (in this case it is) and if **showLoadingPlaceHolder** is set to true, we show the loading skeletons. I'm not sure why we show the skeleton when the list size is 0.
### What changes do you think we should make in order to solve the problem?
In order to solve this problem, we can pass the right value for the boolean prop(**showLoadingPlaceHolder**) in the **WorkspaceMembersPage.js** file to the **SelectionList** component:
![image](https://github.com/Expensify/App/assets/25957442/576bd0d9-fe96-4f27-bce8-5b7e9a14672a)
We need to make sure the prop is set to true in case the app is in offline mode.
### What alternative solutions did you explore? (Optional)
I was thinking of modifying the logic inside the **BaseSelectionList** component but modifying the **BaseSelectionList** component might affect other parts of the app.

**Comment by DylanDylann** [comment] 2023-09-21 08:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - WS invite page keeps loading in offline if no members present

### What is the root cause of that problem?
Because we are offline, we can't load `policyMembers`. It causes `policyMembers` will be empty and skeleton view is displayed

### What changes do you think we should make in order to solve the problem?
We should add a condition to check if the user offline and data is not loaded before, we will display "Can't get data in offline. Go online to see members". From UX perspective, I see It help the user understand which problem and what they need to do 
### What alternative solutions did you explore? (Optional)
We also load all policy data right after the user logs in

**Comment by kadiealexander** [comment] 2023-09-25 07:11
@robertKozik please don't forget to check thee proposals, thanks!

**Comment by robertKozik** [comment] 2023-09-25 08:49
Thank you all for your proposals @DylanDylann @dukenv0307 @nebiyuelias1! I think we should go with the @nebiyuelias1 solution, as it's simple and we have other indications of offline state of the app.
@dukenv0307 - I don't think  displaying only ourselves by default is correct, it would make an impression that something happen with other users, so they don't show up
@DylanDylann - In my opinion the `You appear to be offline` footer should be sufficient to indicate the cause of the problem

selected proposal: https://github.com/Expensify/App/issues/27776#issuecomment-1727097820

🎀 👀 🎀 C+ reviewed

**Comment by robertKozik** [comment] 2023-09-25 09:22
It seems to be the scenario where the user doesn't have access to the members page in the current session. In other cases (when it was loaded before going offline), it would display the cached participants list and the user would be able to, for example, remove them. In your proposed solution, we wouldn't have that capability. In my opinion, this might conflict with the `offline first` principle.

**Comment by nebiyuelias1** [comment] 2023-09-25 09:29
> It seems to be the scenario where the user doesn't have access to the members page in the current session. In other cases (when it was loaded before going offline), it would display the cached participants list and the user would be able to, for example, remove them. In your proposed solution, we wouldn't have that capability. In my opinion, this might conflict with the `offline first` principle.

So what's your suggestion @robertKozik ?

**Comment by robertKozik** [comment] 2023-09-25 09:44
@nebiyuelias1 I was referring to the @DylanDylann comment, only described why I think displaying the offline information rather than list is in my opinion not correct

@DylanDylann Yeah let's wait for additional input from CME as well

**Comment by shawnborton** [comment] 2023-09-25 11:16
I think we:
- Wouldn't show the Select All checkbox if there is nothing to select
- We should use the pattern where we show some small text under the search input to let users know why there are no results/members displaying on this page. Something like "You must be online in order to view members of this workspace" or something like that

cc @Expensify/design for visibility

**Comment by DylanDylann** [comment] 2023-09-25 11:36
@robertKozik 
I [updated proposal](https://github.com/Expensify/App/issues/27776#issuecomment-1729072175) with a bit change as [expected here](https://github.com/Expensify/App/issues/27776#issuecomment-1733462236)

**Comment by MariaHCD** [comment] 2023-09-28 01:33
Agreed with @shawnborton's recommendations. @robertKozik what do you think?

**Comment by DylanDylann** [comment] 2023-10-02 09:01
@robertKozik Gentle bump, What do think about my [updated proposal](https://github.com/Expensify/App/issues/27776#issuecomment-1729072175) with new expect

**Comment by robertKozik** [comment] 2023-10-02 09:20
@DylanDylann I don't think your proposal completely covers the expected behaviour from [here](https://github.com/Expensify/App/issues/27776#issuecomment-1733462236). Hiding whole view will result in hiding the search input as well which is against the pattern described above.  I think we need to step into the SelectionList and tweak it there

**Comment by robertKozik** [comment] 2023-10-02 10:45
Few things more @DylanDylann :
1. I don't think we should remove the two buttons when offline. We support inviting and removing members while offline
2. Maybe I missed it but I don't see the part where your solution disables `select all` checkbox when there is nothing to select

**Comment by DylanDylann** [comment] 2023-10-02 12:15
@robertKozik 
> I don't think we should remove the two buttons when offline. We support inviting and removing members while offline

[Updated proposal](https://github.com/Expensify/App/issues/27776#issuecomment-1729072175)

> Maybe I missed it but I don't see the part where your solution disables select all checkbox when there is nothing to select

https://github.com/Expensify/App/blob/bba600a3f8a339f293e3a74b1e80398cb4e8bc67/src/components/SelectionList/BaseSelectionList.js#L376-L386

When headerMessage is true, the select all button will be hide

**Comment by nebiyuelias1** [comment] 2023-10-02 14:10
> @robertKozik
> 
> > I don't think we should remove the two buttons when offline. We support inviting and removing members while offline
> 
> [Updated proposal](https://github.com/Expensify/App/issues/27776#issuecomment-1729072175)
> 
> > Maybe I missed it but I don't see the part where your solution disables select all checkbox when there is nothing to select
> 
> https://github.com/Expensify/App/blob/bba600a3f8a339f293e3a74b1e80398cb4e8bc67/src/components/SelectionList/BaseSelectionList.js#L376-L386
> 
> When headerMessage is true, the select all button will be hide

But what about showing the members that are loaded?

**Comment by DylanDylann** [comment] 2023-10-04 02:44
@nebiyuelias1 I am not sure what you mean, Could you help to post a video or explain in detail your thought? Many thanks

**Comment by nebiyuelias1** [comment] 2023-10-04 02:48
> @nebiyuelias1 I am not sure what you mean, Could you help to post a video or explain in detail your thought? Many thanks

I meant to say, have you considered the case where you show the list of members of a workspace.

**Comment by DylanDylann** [comment] 2023-10-04 02:49
@nebiyuelias1 Let's see the condition
```
 const isOfflineAndNotGetDataYet = _.isEmpty(props.policyMembers) && props.network.isOffline

```

**_.isEmpty(props.policyMembers)** condition will make sure that there are no available member

**Comment by DylanDylann** [comment] 2023-10-04 03:24
@robertKozik Gentle Bump, ICYMI please help to check [this comment](https://github.com/Expensify/App/issues/27776#issuecomment-1742907631)

**Comment by robertKozik** [comment] 2023-10-04 08:49
Thank you for updating the [proposal](https://github.com/Expensify/App/issues/27776#issuecomment-1729072175) @DylanDylann. I think it now covers the expected behaviour from [here](https://github.com/Expensify/App/issues/27776#issuecomment-1733462236) and for now it's the only proposal which covers it in full.
@MariaHCD I think we can assign to @DylanDylann and see the proposal in action, it looks promising and it's the only one which took under consideration the @shawnborton recomendations

**Comment by MariaHCD** [comment] 2023-10-04 12:15
Thanks, sounds good to me, @robertKozik! @DylanDylann's proposal looks complete to me too.

**Comment by DylanDylann** [comment] 2023-10-05 08:10
@MariaHCD @Expensify/design Could you help to confirm the copy translation "You must be online in order to view members of this workspace". So I can raise a correct PR

**Comment by DylanDylann** [comment] 2023-10-05 08:11
@kadiealexander This issue also need be held while waiting copy translation

**Comment by DylanDylann** [comment] 2023-10-05 09:15
@robertKozik this [PR](https://github.com/Expensify/App/pull/28897) ready for review

**Comment by tjferriss** [comment] 2023-10-05 21:18
I'm asking for clarity on whether we should include a period for sentences like this ([discussion here](https://expensify.slack.com/archives/C03SSAQG5/p1696540650351729)). Otherwise, it looks great to me.

**Comment by tjferriss** [comment] 2023-10-06 16:33
I clarified that we do in fact want to use a period in cases like this. So the copy should read as follows:

>You must be online in order to view members of this workspace.

I also updated [the SO on product copy](https://stackoverflowteams.com/c/expensify/questions/7025) to clarify this stance.

**Comment by DylanDylann** [comment] 2023-10-06 16:46
@tjferriss Just a note, this is current copy: 
English: You must be online in order to view members of this workspace
Spanish: Debes estar en línea para poder ver los miembros de este espacio de trabajo

**Comment by tjferriss** [comment] 2023-10-06 20:15
Those look good to me. We just need to add a period to both. Am I misunderstanding the request?

**Comment by MariaHCD** [comment] 2023-10-09 07:03
Asking for a confirmation on the Spanish translation here: https://expensify.slack.com/archives/C21FRDWCV/p1696833255149549

**Comment by MariaHCD** [comment] 2023-10-10 06:19
@DylanDylann, the Spanish translation is 👍🏼

**Comment by DylanDylann** [comment] 2023-10-10 06:47
@MariaHCD Thanks so much. Could you help to review this PR https://github.com/Expensify/App/pull/28897 ?

**Comment by DylanDylann** [comment] 2023-10-10 15:50
The PR lasts a long time because we need to wait for copy translation confirmation. Are we eligible for bonus timeline in this issue?

**Comment by MariaHCD** [comment] 2023-10-23 12:05
Not overdue, I believe we just need the BZ checklist

**Comment by robertKozik** [comment] 2023-10-23 12:24
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **I cannot determine exact PR as it was freshly discovered edge-case rather than implementation problem**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **Yes, I think we should create the regression test for this as this issue can lead to problems with workspaces flows**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
> **1. Tap profile**
> **2. Tap preferences**
> **3. Toggle on forced offline**
> **4. Navigate to LHN**
> **5. Tap profile icon**
> **6. Tap workspaces**
> **9. Navigate to workspaces and tap workspace with members**
> **10. Tap members**
> **11. Verify that members page is not in loading state**

**Closed** 2023-10-24 04:05 UTC
Labels: External, Daily, Waiting for copy, Awaiting Payment, Bug
