### ISSUE TITLE
[HOLD for payment 2023-09-21] [$1000] Web -  Flawed Attachment Visibility: Flagged “hidden” Attachments still visible from attachment modal

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22915] opened 2023-07-14 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. From User A, Initiate a chat with User B
2. From user A, send some attachments (atleast 2 or 3)
3. From user B, flag any attachment with moderation as “hidden” like bullying
4. From user A, click on an attachment to open attachment modal
5. Click on the left or right button if exist to see all attachment
6. Verify that the attachment that is flagged above and supposed to be “hidden” still appears

## Expected Result:
When an attachment is flagged and marked as not visible, users should be restricted from seeing it

## Actual Result:
Both Users were able to see it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6780ad6a-d6ff-4ff4-9b3e-4d537dad9ce9

https://github.com/Expensify/App/assets/93399543/d9890c06-309f-4a0e-91ce-bc78211cafa8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689289028489799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014153535e195ba609</li>
        <li>Upwork Job ID: 1681657037569265664</li>
        <li>Last Price Increase: 2023-08-08</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 26121902</li>
<li>bernhardoj | Contributor | 26121905</li>
<li>avi-shek-jha | Reporter | 26121906</li>
</ul></li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment] 2023-07-24 22:49
Good point. I agree with that.

**Comment by JmillsExpensify** [comment] 2023-08-02 20:45
Looks like we should now re-test and take this issue off hold.

**Comment by shawnborton** [comment] 2023-08-10 12:48
That makes sense to me.

**Comment by amyevans** [comment] 2023-08-14 23:05
Proposal looks good, thanks!

**Comment by JmillsExpensify** [comment] 2023-09-25 22:36
@fedirjh Thanks for kicking off the BZ checklist. That means it's time for me to circle back with a payment summary:

 - Issue reporter: @avi-shek-jha $250
 - Contributor: @bernhardoj $1,000
 - Contributor+: @fedirjh $1,000

**Comment by JmillsExpensify** [comment] 2023-09-25 22:39
Offers sent to all contributors.

**Comment by avi-shek-jha** [comment] 2023-09-25 23:29
> Offers sent to all contributors.

Offer Accepted. Thank You.

**Comment by amyevans** [comment] 2023-10-03 23:59
Friendly bump @JmillsExpensify on https://github.com/Expensify/App/issues/22915#issuecomment-1734635242

**Comment by JmillsExpensify** [comment] 2023-10-07 21:01
Paid out issue reporter and contributor. Just send another offer to you @fedirjh.

**Comment by JmillsExpensify** [comment] 2023-10-07 21:31
All paid out! Regression test was also added so I'm closing this issue.

**Closed by JmillsExpensify** 2023-10-07 21:31 UTC
Labels: External, Daily, Awaiting Payment, Bug
