### ISSUE TITLE
[$1000] Inconsistency bug - App does not dynamically translate 'No activity yet' in search (works fine after revisit and dynamically updates in LHN)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21537] opened 2023-06-25 17:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app (device 1) and login with user A
2. Open another device (device 2) and login with user A
3. Open search in device 1
4. From device 2, change language from english to spanish
5. In device 1 observe that 'No activity yet' is not updated in Spanish in search but it is updated in LHN and other terms too are updated dynamically in search and reports

## Expected Result:
App should dynamically update 'No activity yet' in search to Spanish on language change

## Actual Result:
App does not dynamically update 'No activity yet' in search to Spanish on language change

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/18d509f1-7e54-4a25-b2ec-c222e83f9faf

https://github.com/Expensify/App/assets/93399543/5ed2df32-6cc3-4923-ba41-77d295933c52

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687199616837069

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c556dc52d6e81d71</li>
        <li>Upwork Job ID: 1673861548329369600</li>
        <li>Last Price Increase: 2023-06-28</li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-06-25 18:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency bug - App does not dynamically translate 'No activity yet' in search

### What is the root cause of that problem?
For the SearchPage we are not updating options when the preferredLocale gets updated and that is the reason for this issue.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/SearchPage.js#L72-L75

### What changes do you think we should make in order to solve the problem?
Add preferredLocale condition here in `componentDidUpdate` for early return if the preferredLocale isn't gets changed otherwise it should call `updateOptions`.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/pages/SearchPage.js#L72-L75
```
&& this.props.preferredLocale === prevProps.preferredLocale
```
OR
```
_.isEqual(this.props.preferredLocale, prevProps.preferredLocale)
```

**Comment by trjExpensify** [comment] 2023-06-26 17:15
Hm, this sounds like a similar root cause as [this one](https://github.com/Expensify/App/issues/20613#issuecomment-1596937086) and [this one](https://github.com/Expensify/App/issues/20633). @abdulrahuman5196 can you offer an opinion on that?

**Comment by abdulrahuman5196** [comment] 2023-06-26 18:58
@trjExpensify. No, It seems both are different actually for this case atleast. Here we are having the data but not translating properly. Other bugs are kind of case where the text shown itself is wrong regardless of the language choosen.

For eg: We only show this 'No activity yet' in search page for money requests. There can be cases where 'No activiy yet' is shown wrongly instead of a user text message which is a different issue. But this issue is only concerned about translation.

While checking on this bug I also ended up reviewing this proposal by @Pujan92 unintentionally https://github.com/Expensify/App/issues/21537#issuecomment-1606198194, the proposal is working and make sense for this issue.
If possible and if this bug is planed to go external, can I be assigned C+?

**Comment by trjExpensify** [comment] 2023-06-28 01:10
Okay got it, thanks for confirming and explaining that. Assigning you as the C+. If you're happy with @Pujan92's proposal green light it and someone from our side will get assigned for a secondary. 👍

**Comment by abdulrahuman5196** [comment] 2023-06-28 18:45
@tienifr Thank you for the proposal, but I don't think i would be aligning with the proposal here since, it is not just `No activity yet` will be sent, but it could also have text messages so it would not be wise to say we can only send the translation key and translate while rendering the item. 
And I don't think the re-computation is super heavy, and we are not going to be doing it during every render, it is only going to be done during the locale changes which shouldn't be high numbers comparing the renders.

**Comment by abdulrahuman5196** [comment] 2023-06-28 18:47
@Pujan92 's proposal here https://github.com/Expensify/App/issues/21537#issuecomment-1606198194 looks good and works well.

🎀👀🎀
C+ Reviewed

🎀 👀 🎀 C+ reviewed

cc: @trjExpensify

**Comment by abdulrahuman5196** [comment] 2023-06-28 18:47
@youssef-lr  The C+ reviewed comment is here - https://github.com/Expensify/App/issues/21537#issuecomment-1611910874

**Comment by abdulrahuman5196** [comment] 2023-06-29 07:47
@tienifr 

>can you share some examples of the text messages that might show in this case? I don't find any in the getHeaderMessage method.


https://github.com/Expensify/App/assets/46707890/11ad932a-c3ed-4833-97e6-5a7536966658

>if there's no such case of user-generated text messages, do you agree that https://github.com/Expensify/App/issues/21537#issuecomment-1610462579 is better both in terms of code design and performance?

Even still I would question this. I don't think we are optimizing some super intensive task into a super light weight solution. The functionality is already light weight and the accepted proposal is also not going to increase it to super intensive task.

>thttps://github.com/Expensify/App/issues/19449#issuecomment-1561043031's another similar case where we're conflating the text message and the system message in the chat here, for which it's also universally agreed to use the translationKey as the best design.

I don't think both are similar. Even in the PR of the linked issue, you are actually translating with the translationKey and providing the translated value to the UI to render, it is not like render place is translating. The same is currently working in this case already, only issue here is its **not re-rendering on locale change from other device.** 

**So I would still go with the current accepted solution.**

**Comment by trjExpensify** [comment] 2023-07-03 10:41
@youssef-lr thoughts on this one, please? Let's keep it moving! :)

**Comment by Christinadobrzyn** [comment] 2023-07-05 19:52
Hey @abdulrahuman5196 - will this job resolve the issue reported here https://github.com/Expensify/App/issues/22051

**Comment by trjExpensify** [comment] 2023-07-05 22:23
Bump @youssef-lr https://github.com/Expensify/App/issues/21537#issuecomment-1617890672

**Comment by abdulrahuman5196** [comment] 2023-07-06 10:35
>@abdulrahuman5196 I think the above you shared is not the header message (or Expensify-defined message) that we're addressing 😅, in that case no translation will take place.

We are actually not addressing the header message here, It is this other issue (https://github.com/Expensify/App/issues/22051). Header message is just predefined message for which passing a translation key could be a fine proposal if it will only have predefined keys. (Not sure on it since i haven't checked on it that much)

Here we are trying to address the row item subtitle issue of "No activity yet", it can have both predefined keys and user added text message, so we would end up keeping 2 fields in the modal, like translationKey(Incase of predefined text like "No activity Found") and actualText(Like "Hi") and we will pass this information from SearchPage class down the hierarchy till the OptionRow class where we would create a check like `actualText || localize(translationKey)`. This seems be an intensive fix for this particular issue in hand.

**Comment by abdulrahuman5196** [comment] 2023-07-06 12:37
>No, we don't have to do this, as long as we do the translation right before displaying the text, we should be good. We can add it to getSections.

@tienifr I don't understand this. Can you explain with code pointers and how you would achieve the same without the mentioned drawback?

**Comment by abdulrahuman5196** [comment] 2023-07-08 08:25
@tienifr Got it.
Seems valid implementation and less intensive.
But another question on the same, how would you do the same for text which has both translated and non translated content? Like for example this , It is `${payer} debe ${amount}` because this information is only available currently on re-compute and we can't just pass a single key to solve this?

<img width="386" alt="Screenshot 2023-07-08 at 1 49 10 PM" src="https://github.com/Expensify/App/assets/46707890/dfa59d82-8f9a-41cc-ae8b-2a607127ab89">

**Comment by abdulrahuman5196** [comment] 2023-07-10 16:23
@tienifr Can you add the implementation to your original proposal? I agree your solution is also a valid solution. But I still think its a overkill for this issue. Anyways I would let the internal engineer take the final call.

**Comment by abdulrahuman5196** [comment] 2023-07-10 16:28
@youssef-lr We have been waiting for your review? Could you kindly check on this? Thanks

C+ comment is here - https://github.com/Expensify/App/issues/21537#issuecomment-1611910874

It approves the proposal here https://github.com/Expensify/App/issues/21537#issuecomment-1606198194 by @Pujan92 which is a straightforward fix enough to fix this issue.

But @tienifr  also provides a another valid solution here https://github.com/Expensify/App/issues/21537#issuecomment-1610462579 but i think its a overkill for this issue. 

But would let you made the final call on the same.

**Comment by youssef-lr** [comment] 2023-07-12 20:21
Catching up now!

**Comment by youssef-lr** [comment] 2023-07-14 22:32
@abdulrahuman5196 I think @tienifr is valid and has an added benefit of improving separation of concerns, as well as:

>Thus we don't have to generate the options again when display-related things like locale change.

I agree that changing the language should not trigger `updateOptions`. However, I'm not a fan of of the naming `alternateTextMessage` but we can figure it out during the PR.

**Comment by abdulrahuman5196** [comment] 2023-07-15 19:51
Thank you for confirming @youssef-lr 👍  . Kindly let me know when the PR is ready @tienifr

**Comment by trjExpensify** [comment] 2023-07-17 18:10
PR is in review now, Melv. 👍

**Comment by trjExpensify** [comment] 2023-07-25 13:43
@tienifr looking for you to fix the lint errors! :)

**Comment by abdulrahuman5196** [comment] 2023-08-01 20:31
Still in review. Will close out by morning

**Comment by trjExpensify** [comment] 2023-08-07 10:50
PR is awaiting a review from @youssef-lr! :)

**Comment by trjExpensify** [comment] 2023-08-14 10:24
Bump on the review, @youssef-lr. Also @tienifr there are conflicts now to resolve :)

**Comment by trjExpensify** [comment] 2023-08-30 16:32
@youssef-lr can you review that PR please?

**Comment by youssef-lr** [comment] 2023-08-30 20:27
Reviewing!

**Comment by trjExpensify** [comment] 2023-09-25 11:18
@tienifr there are conflicts to resolve on the PR. @youssef-lr can we get this one through your review, please?

**Comment by youssef-lr** [comment] 2023-09-26 09:39
On it today!

**Comment by youssef-lr** [comment] 2023-10-03 13:18
bumped @tienifr, I'm worried some parts of the code are a bit complex and we're sacrificing readability to fix a minor bug.

**Comment by trjExpensify** [comment] 2023-10-16 18:01
How's this PR looking?

**Comment by trjExpensify** [comment] 2023-10-30 12:03
The PR is still in review, but it has conflicts to resolve now @tienifr.

**Comment by trjExpensify** [comment] 2023-11-09 00:11
Commented in the PR, still has conflicts.

**Comment by abdulrahuman5196** [comment] 2023-11-17 14:03
@youssef-lr Could you kindly check on this? The PR is pending for weeks actually?

**Comment by trjExpensify** [comment] 2024-01-03 12:03
Hey @tienifr @youssef-lr what's going on here? The [PR](https://github.com/Expensify/App/pull/22987) has been open since July, we now have conflicts again. Thanks!

**Comment by trjExpensify** [comment] 2024-01-24 12:22
As discussed in the [open-source thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1705437300843999), we're going to close this issue. We've hit an impasse with the PR not going anywhere, and overall this is pretty minor.

**Comment by abdulrahuman5196** [comment] 2024-01-28 15:13
> @trjExpensify Should I and @abdulrahuman5196 get paid? We spent a lot of time to create/review the PR. Thanks

+1 on this.

**Comment by trjExpensify** [comment] 2024-02-07 01:02
Oh, sorry guys. This fell into the abyss after the close. Let me reopen as we discuss. 

- The PR was opened mid-July 2023
- The last time the PR had commits was early November 2023. 
- It sat dormant until the end of Jan 2024 when we decided to close it. 

I think the months of inactivity on this issue isn't a great showing, and we should be mindful to approach the issues we take on with #urgency and #focus. We've closed "abandoned" PRs for inactivity of way less time than this one historically, so I'm curious what you both as tenured members of the community think is fair compensation and a reflection of the timeline on this issue?

**Comment by trjExpensify** [comment] 2024-02-08 23:48
Cool, thanks for your input. I'm happy to pay out $250 (50% the current rate) for the work so far. 

>if considerable work was done on the issue and transferred or moved due to internal circumstances.

I will add on this that I don't think it was transferred elsewhere due to internal drivers, but the focus on this issue likely dropped off for other things. So let's just be careful to address that going forward all round. 

Sound good?

**Comment by abdulrahuman5196** [comment] 2024-02-14 07:35
Hi @trjExpensify , Sorry I missed this. Yes. I am fine the callout.

**Comment by trjExpensify** [comment] 2024-02-14 13:12
Cool, offers have been sent to you both.

**Comment by abdulrahuman5196** [comment] 2024-02-14 18:39
Thank you @trjExpensify . Accepted the offer.

**Comment by trjExpensify** [comment] 2024-02-14 22:00
@abdulrahuman5196 paid!

**Comment by trjExpensify** [comment] 2024-02-23 18:08
@tienifr paid, closing!

**Closed by trjExpensify** 2024-02-23 18:08 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
