### ISSUE TITLE
Desktop - Glitch occurs when ESC is pressed after "2FA is now disabled" Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21084] opened 2023-06-19 21:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
NOTE : to REPRODUCE ,  previously added 2FA  should be removed and new should be setup.
1. Go to settings -> Security
If there is 2FA is enabled already, remove it .
2. go to add 2FA -> copy code and add auth code from the  external authenticator app.
3.  ON 2FA is now enabled, click got it.
4. Now disable 2FA, Confirm
5. Now it shows the page "2FA is now disabled"
6. Then, Press ESC and notice the glitch.

## Expected Result:
While pressing ESC from 2FA is now disabled page, Desktop app should work smoothly like webapp.

## Actual Result:
Glitch occurs when ESC is pressed after "2FA is now disabled" Page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-2

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c63b95b5-2687-47ac-b945-017842c9b03b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ashimsharma10

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686669393128099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ashimsharma10** [comment] 2023-06-20 09:20
@laurenreidexpensify can u notice the page ( on right hand side )  responds differently after pressing ESC, form the video above?
Please see 00:25 on above video.

**Comment by laurenreidexpensify** [comment] 2023-06-22 12:56
@ashimsharma10 are you saying the issue is that you have pressed Esc, but the 2FA panel on the RHN still displays briefly before returning to the chat?

**Comment by ashimsharma10** [comment] 2023-06-23 06:57
@laurenreidexpensify Yes, I would say RHN displays page transitions in an unusual way. 
Such doesn't occur on other pages.

**Comment by ashimsharma10** [comment] 2023-06-24 05:08
@laurenreidexpensify any updates? Have you reproduced?

**Comment by laurenreidexpensify** [comment] 2023-06-26 12:25
@ashimsharma10 I just followed the steps on production and couldn't reproduce. Was this reproducible only on staging for you or on prod too?

**Comment by ashimsharma10** [comment] 2023-06-26 13:23
@laurenreidexpensify i can't reproduce on both staging and prod. seems it doesn't occur on new version !

**Comment by laurenreidexpensify** [comment] 2023-06-27 07:28
@ashimsharma10 thanks for checking! Gonna close this one :)

**Closed by laurenreidexpensify** 2023-06-27 07:28 UTC
Labels: Daily, Needs Reproduction, Bug
