### ISSUE TITLE
[HOLD for payment 2023-12-15] [$500] Workspace - the blue focus is not prioritized over the application highlight

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31635] opened 2023-11-21 15:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
1. Go to settings > Workspace > Members
2. Click on existing workspace
3. Members > Invite
4. Click on 'Tab' key to bring the blue focus from accessibility
5. Notice that the lists are focused(Blue focused)
6. Move the blue Focus using the 'Tab' key to focus on the users
7. Click Enter
Notice that clicking enter selects the user that the app highlight is on. It does not select the User focused with the blue marker

## Expected Result:
the blue focus is prioritized when clicking enter rather than the application highlight

## Actual Result:
The blue focus is not prioritized over the application highlight

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/947bef55-bdb7-4972-ab15-584e440f9b9c

![Bug6285482_1700572695311!image](https://github.com/Expensify/App/assets/78819774/7eb86982-7f87-4dd7-9844-38c48e29277b)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @laurenreidexpensify</details>

**Comment by erquhart** [comment] 2023-11-21 17:01
I don't disagree with a quick patch for this particular case, but up/down handling and tab key handling are totally separate right now, and that's a major flaw. Both appearance and controls of tab key and arrow key navigation should be identical. This is not limited to this view, it's a general issue.

If we try to fix this one small bug at a time the end result is unlikely to be cohesive or forward moving.

**Comment by DylanDylann** [comment] 2023-11-21 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
-  Workspace - the blue focus is not prioritized over the application highlight

### What is the root cause of that problem?
- In [BaseSelectionList](https://github.com/Expensify/App/blob/main/src/components/SelectionList/BaseSelectionList.js), we can create the state ```[isFocusedIndexByTab, setIsFocusedIndexByTab]``` to keep track whether we are focusing on any row by using tab key or not
- Then update:
https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/components/SelectionList/BaseSelectionList.js#L300
to:
```
<BaseListItem onFocus={()=>setIsFocusedIndexByTab(true)} onBlur={()=>setIsFocusedIndexByTab(false)} ... />
```
- Then disable the onEnter callback by updating:
https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/components/SelectionList/BaseSelectionList.js#L358-L363
to:
````diff
    useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ENTER, selectFocusedOption, {
        captureOnInputs: true,
        shouldBubble: () => !flattenedSections.allOptions[focusedIndex],
        shouldStopPropagation,
+      isActive: !disableKeyboardShortcuts && !disableEnterShortcut && isFocused && isFocusedIndexByTab,
    });
````
### What alternative solutions did you explore? (Optional)

**Comment by erquhart** [comment] 2023-11-22 18:36
Just adding for clarity, in case it isn't clear, using the keyboard instead of the mouse in this list is broken, does not work. This isn't specific to folks with special accessibility needs.

**Comment by laurenreidexpensify** [comment] 2023-11-27 10:20
@thesahindia I agree but if there's a proposal that works here I think it's fine to fix it, if none of these suggestions work then we can consider closing

**Comment by laurenreidexpensify** [comment] 2023-12-14 12:02
Payment due tomorrow

**Comment by laurenreidexpensify** [comment] 2023-12-18 10:01
Payment Summary:

- Contributor $500 @tienifr - offer sent in Upwork
- C+ review $500 @thesahindia please send a manual request

**Comment by laurenreidexpensify** [comment] 2023-12-18 10:02
@thesahindia pls update checklist thanks

**Comment by laurenreidexpensify** [comment] 2023-12-20 14:17
Waiting for checklist to be completed

**Comment by mountiny** [comment] 2023-12-26 11:30
I think we do not need the new regression test for this

**Closed** 2023-12-29 09:09 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-01-14 09:12
$500 payment approved for @thesahindia based on [this comment](https://github.com/Expensify/App/issues/31635#issuecomment-1859985881).
