### ISSUE TITLE
[$1000] Not able to upload svg image on chat but works well on profile picture

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19499] opened 2023-05-23 22:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to staging dot on web chrome
2. First try to upload any svg image on profile picture and notice that it works well
3. But now try to upload the same svg on chat composer and notice that it loads but doesn't upload and throws an error

## Expected Result:
Able to upload svg image on chat in a similar way how it works well on the profile picture
## Actual Result:
Not able to upload svg image on chat but works well on profile picture

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/33691d28-6172-40da-99a0-3c21cee4aa52

https://github.com/Expensify/App/assets/43996225/e19b2925-aa36-435d-90f4-2976e231a5e5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1684685097227669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01840b20615262c1d1</li>
        <li>Upwork Job ID: 1661470294263726080</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by AyoubMoujane** [comment] 2023-05-26 14:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Unable to upload an `svg` image in chat even though it's possible to upload an `svg` to update the profile picture of the user.

### What is the root cause of that problem?

The API commands used for the two actions are different:
    - To update the profile picture: the command used is `UpdateUserAvatar`
    - To add an attachment to the chat: the command used is `AddAttachment`

The failure response of the API for `AddAttachment` looks like this:

![Screenshot 2023-05-26 at 16 30 42](https://github.com/Expensify/App/assets/50808670/c11c178f-a8ed-48cb-a9b6-517e65a5222b)

### What changes do you think we should make in order to solve the problem?

Check the two API commands implementation and figure out if it makes sense to take part of the logic used to process the svg image from `UpdateUserAvatar` and share it with `AddAttachment` command.

### What alternative solutions did you explore? (Optional)

Convert the svg image into a png client-side using a library but I think this logic should be handled on the backend

**Comment by AyoubMoujane** [comment] 2023-05-26 14:52
Contributor details
Your Expensify account email: moujane.ayoub@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0126293d99c814e8f5

**Comment by abekkala** [comment] 2023-05-26 19:31
@thesahindia will review proposals as they come in

**Comment by c3024** [comment] 2023-05-29 04:58
## Proposal
### Please re-state the problem that we are trying to solve in this issue.

SVGs can be uploaded and submitted at profile photo but submitting at comments returns an error.

### What is the root cause of that problem?
[Lines 318 to 322 of App/src/components/AvatarCropModal/AvatarCropModal.js](
https://github.com/Expensify/App/blob/414dc106d707a326094f7227c9dc91597596cd0c/src/components/AvatarCropModal/AvatarCropModal.js#LL318C1-L322C65)

```
        // Svg images are converted to a png blob to preserve transparency, so we need to update the
        // image name and type accordingly.
        const isSvg = props.imageType.includes('image/svg');
        const imageName = isSvg ? 'fileName.png' : props.imageName;
        const imageType = isSvg ? 'image/png' : props.imageType;

```
This SVG conversion to PNG is missing in the `addAttachment` here.
[Lines 863 to 871 of App/sec/pages/home/report/ReportActionCompose.js](https://github.com/Expensify/App/blob/414dc106d707a326094f7227c9dc91597596cd0c/src/pages/home/report/ReportActionCompose.js#LL863C1-L871C6)
```
    addAttachment(file) {
        // Since we're submitting the form here which should clear the composer
        // We don't really care about saving the draft the user was typing
        // We need to make sure an empty draft gets saved instead
        this.debouncedSaveReportComment.cancel();
        const comment = this.prepareCommentAndResetComposer();
        Report.addAttachment(this.props.reportID, file, comment);
        this.setTextInputShouldClear(false);
    }
```
### What changes do you think we should make in order to solve the problem?
Check is the file is SVG and convert it to PNG in `addAttachment` with the logic used in `AvatarCropModal.js`. However, this would show png on the recipient end.

### What other solutions did you explore?
1. I think server side logic is preventing SVG images. It should be changed to prevent this error.
2. Convert PNG to SVG again on client with a JS library but this would not be the exact same SVG sent by sender.

**Comment by Gonals** [comment] 2023-05-29 13:30
I'll take a closer look tomorrow!

**Comment by Gonals** [comment] 2023-05-30 10:17
This seems to be working fine now both in staging and dev! Closing

**Comment by priya-zha** [comment] 2023-05-30 10:23
@Gonals I'm still able to reproduce with SVG images. I have tried the below svg images.
![vote (1)](https://github.com/Expensify/App/assets/34065075/6e0afbd2-2682-4ddf-95d2-445bbdd4aed4)
![sample_1280×853](https://github.com/Expensify/App/assets/34065075/70fa884f-a17e-4694-a058-c30c458eb758)
![1677239475mouse-rat](https://github.com/Expensify/App/assets/34065075/71a27ec2-55fd-4172-804a-68fcfc76d1ef)

**Comment by Gonals** [comment] 2023-05-30 10:50
You are right. Not sure why it worked with the one I had.

**Comment by Gonals** [comment] 2023-05-30 11:29
SVG is not supported by `getImageSize` in PHP, so the only way to have it behave as an image (with its preview and whatnot) would be to change the format.

I think that, for attachment purposes, it'd be better to keep the file intact, displaying them as a link, like we do for documents or other files, instead of displaying the preview

**Comment by abekkala** [comment] 2023-06-09 15:51
@Gonals how would you like to proceed here? should we keep this open for proposals (and possibly increase price?)

**Comment by abekkala** [comment] 2023-06-14 18:49
@Gonals is there any update on the internal fix for this one?

**Comment by abekkala** [comment] 2023-06-21 17:10
Oh! does this one require a payout? I see that the merged PR has gone to production but I'm not seeing any of the auto-updates irt payments??

**Comment by abekkala** [comment] 2023-06-26 20:04
[$250] Payment to @priya-zha

**Comment by abekkala** [comment] 2023-06-28 14:37
@priya-zha upwork contract offer sent: Payment Issue for E/App #19499 - Expensify

**Comment by abekkala** [comment] 2023-06-28 14:50
payment made and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-06-28 14:51
Confirmed with @Gonals:  Internal fix and Internal PR review - no other payments needed

**Closed by abekkala** 2023-06-28 14:50 UTC
Labels: Reviewing, Daily, Internal, Bug
