### ISSUE TITLE
[$500] Thread - Title in thread is not shown when leaving and revisiting thread offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32659] opened 2023-12-07 13:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/32331
## Action Performed:
1. Send a message and create a reply in thread
2. Go offline
3. Click three-dot menu and leave the thread
4. Click on the n replies

## Expected Result:
Parent message title shows in the thread header

## Actual Result:
Thread header shows skeleton loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/4e3f30ae-f638-4e67-a9fc-cd9209639cfd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0106a4cab3b7676301</li>
        <li>Upwork Job ID: 1732754476237701120</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2023-12-07 13:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Title in thread is not shown when leaving and revisiting thread offline

### What is the root cause of that problem?
The report action (the message we have replied in thread) has no `childReportID` when we reply in thread.
### What changes do you think we should make in order to solve the problem?

We should give childReportID optimistically in `Report.navigateToAndOpenChildReport` for the report action
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2023-12-07 14:55
@tienifr But there is a related bug as I explained in my proposal 👍

**Comment by conorpendergrast** [comment] 2023-12-11 12:30
Yeah as this is a dupe of https://github.com/Expensify/App/issues/32519, I'll close it out. If there's another bug, let's get that created as a separate issue!

**Closed by conorpendergrast** 2023-12-11 12:30 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
