### ISSUE TITLE
Web - Error is changing even writing same thing on Legal name

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26026] opened 2023-08-27 10:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website > Settings > Profile > Personal details > Legal name
2. First time, leave blank by keyboard and It gives "This field is required." error
3. Second time, leave blank by saved messages table and It gives "Name can only include letters" error

## Expected Result:
 It should give same error when writing same thing on Legal name

## Actual Result:
Error is changing even writing same thing on Legal name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-0
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (33) (1).webm](https://github.com/Expensify/App/assets/93399543/227a8acb-1d05-4b53-b417-3238c65e3829)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @mahmudjontoraqulov
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692250806801279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2023-08-28 13:29
Unable to reproduce this using auto-fill on my chrome browser. Closing as this isn't reproducible!

**Closed by joekaufmanexpensify** 2023-08-28 13:29 UTC
Labels: Daily, Needs Reproduction, Bug
