### ISSUE TITLE
[HOLD for #46611][$500] App displays 'Most recent' for some time after login and also does not change background color when value is changed

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28184] opened 2023-09-25 19:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings->preferences->priority mode
3. Copy the URL and change value to '#focus'
4. Logout and paste the URL
5. Login and observe that for some time, value is displayed as 'Most Recent' and once it changes to '#focus', background is still highlighted for 'Most Recent'

## Expected Result:
App should display correct priority mode on login and also maintain background highlight over correct value

## Actual Result:
App displays 'Most Recent' as selected value even though '#focus' is current selected priority mode on login and also maintain background highlight is maintained on 'Most Recent' even when value is rectified

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c12086ff-1153-4917-b467-d2ceec44abc5

https://github.com/Expensify/App/assets/43996225/29a5e891-d61d-4d6b-86ff-9ca90ef28d50

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693324854860599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017588740c0155fa37</li>
        <li>Upwork Job ID: 1706385608822575104</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by lcsvcn** [comment] 2023-09-25 19:14
# Proposal
## Please re-state the problem that we are trying to solve in this issue
App displays 'Most recent' for some time after login and also does not change background color when value is changed
## What is the root cause of that problem?
The root cause of the problem is that we currently doesn't display a loading while app data is still being fetched, that way user can interact with select list before the data is fetched from ybackend.
My proposal is to add a loading screen.
## What changes do you think we should make in order to solve the problem?
I recommend adding a `FullScreenLoading` component, similar to the LegalNamePage.js:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/LegalNamePage.js#L80
At:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Preferences/PriorityModePage.js#L24-L26
We change to this:
``` javascript
const defaultProps = {
    isLoading: true,
    priorityMode: CONST.PRIORITY_MODE.DEFAULT,
};
```
At: https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Preferences/PriorityModePage.js#L55-L59
We change to this:
``` javascript
    {props.isLoading ? (
                <FullscreenLoadingIndicator />
            ) : (
                <SelectionList
                    sections={[{data: priorityModes}]}
                    onSelectRow={updateMode}
                    initiallyFocusedOptionKey={_.find(priorityModes, (mode) => mode.isSelected).keyForList}
                />
            )}
```
At:
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Preferences/PriorityModePage.js#L70-L74
We change to this:
``` javascript
withOnyx({
        isLoading: {
            key: ONYXKEYS.IS_LOADING_APP,
        },
        priorityMode: {
            key: ONYXKEYS.NVP_PRIORITY_MODE,
        },
    }),
```
## What alternative solutions did you explore? (Optional)
N/A

**Comment by kadiealexander** [comment] 2023-09-28 04:16
@fedirjh any thoughts on the proposals here?

**Comment by lcsvcn** [comment] 2023-09-28 14:24
@fedirjh why the solution I proposed doesn't make sense to you? 

The solution I proposed is how it is done across all other sections of the app, l think it is more recommended because fix the issue to not show information before we fetch the right info from the back-end, and it will keep it consistent on how it is done across the whole app.

Address page:
https://github.com/Expensify/App/issues/27814#issuecomment-1739324832

Display Name page:
https://github.com/Expensify/App/issues/28077#issuecomment-1735956156

**Comment by lcsvcn** [comment] 2023-10-02 14:21
@fedirjh what is OP?

**Comment by kadiealexander** [comment] 2023-10-06 03:19
> @kadiealexander What is the expected result when we initially open the priority mode preference page?
> 
> Should we display the default data until the server data is synced?
> Should we display a loading indicator until the data is ready?
> 
> I am leaning toward the second option as it will prevent the interaction while the data is loading.
> 

@fedirjh Agreed, I don't think we should show default data and have it be interactable if it's possibly going to change after it loads.

**Comment by flodnv** [comment] 2023-10-09 10:30
@hungvu193 Can you please link to what makes you say this?

**Comment by flodnv** [comment] 2023-10-09 10:32
>Hmm wait isn't that a selected proposal should have both correct RCA and solution?

No, I am referring to your last message in the conversation -- this one -- what makes you think this?

**Comment by situchan** [comment] 2023-10-09 10:35
@hungvu193 remind me that issue please

**Comment by situchan** [comment] 2023-10-09 10:52
> The root cause of the problem is that we currently don't display a loading while app data is still being fetched, that way the user can interact with the select list before the data is fetched from the backend.
My proposal is to add a loading screen.

This seems more like "solution" than "root cause"

**Comment by kadiealexander** [comment] 2023-10-13 05:01
Not overdue.

**Comment by flodnv** [comment] 2023-10-16 12:21
So what do we do here @fedirjh ?

**Comment by flodnv** [comment] 2023-10-17 14:05
Thank you for the summary. Re-reading the issue from the beginning I have these thoughts:
1. @lcsvcn about [your proposal](https://github.com/Expensify/App/issues/28184#issuecomment-1734321715), won't the same problem exist in all other Right Hand Panes that make an API call whilst something else is loading...? 


Can someone clarify for me why the optimistic data is not working in this case? If the API call is optimistic and we don't wait for the response before showing the expected result, then this bug would not exist, right?

**Comment by lcsvcn** [comment] 2023-10-17 14:28
@flodnv Yes, not to all, but in any right panel that allow user to interact with UI and edit options before data has finish loaded from the API, allowing concurrency to happen in some scenarios.

I currently reported other parts of that app that I was able to reproduce the same issue I reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1695655428909709), like this issue:

https://github.com/Expensify/App/issues/29179

As I explained here, we currently have two different bugs in the same component, so we may want to address this in two separated issues to solve the component behavior and avoid compromising UX in bad networking conditions.

> @hungvu193 well, I agree with you about the RCA in this issue, but if you take a look into the conversations (on slack too) there are two issues in the same component:
> 
> 1. App should display correct priority mode on login and also maintain background highlight over correct value
> 2. No loading indication when loading App displays 'Most recent' causing in bug in slower networks
> 
> If you take a look into the attached the Slack conversation for the issue that I have reported, at the time they classify it as a duplicated, so I sent my proposal here. So after some discussion, an Expensify Engineer reviewed it to see if they would open two separated issues or fixes both with one issue. Seems like they opted to fix it with one single implementation.
> 
> So maybe just to be clear, we could open a new issue on GitHub with the report I have created and close this one, when the other bug is fixed we can mention it here, since it would be fixed automatically by the loading implementation. Just a suggestion, because right now there are two bugs in same component.

**Comment by flodnv** [comment] 2023-10-17 18:25
>However the highlight background still stayed at PRIORITY_MODE.DEFAULT, the initiallyFocusedOptionKey was only calculated once in our first render because it's a state.

Hmm, but if we made this optimistic, and save it in Onyx (before the API call returns), then this problem would not exist, right...?

**Comment by flodnv** [comment] 2023-10-23 12:59
@fedirjh @hungvu193 I'm sorry, I'm having trouble following why optimistic data is not fixing this problem. Can you walk me through step by step as to why the optimistic data is not fixing this problem?

**Comment by flodnv** [comment] 2023-10-23 16:33
Got it, thanks. So that's why we think that some sort of loading indicator would at least let the user know that something is happening, and then won't be taken by surprise about this sudden unexpected change of data?

**Comment by flodnv** [comment] 2023-10-23 17:31
Okay, thanks for all the details. This is tangentially related to another problem I've been raising internally, so I will get back to that one whilst including these details, and then get back here with the outcome. I'll be in touch soon!

**Comment by kadiealexander** [comment] 2023-11-07 06:48
@flodnv any update on the outcome?

**Comment by flodnv** [comment] 2023-11-07 14:09
Finally got the time to post here: https://expensify.slack.com/archives/C04JD99283A/p1699366137184659?thread_ts=1696374112.724199&cid=C04JD99283A

**Comment by flodnv** [comment] 2023-11-14 14:37
Posted in #expensify-open-source here: https://expensify.slack.com/archives/C01GTK53T8Q/p1699972596342559

**Comment by flodnv** [comment] 2023-11-23 17:07
For now this is on HOLD for that proposal, which is being looked at here: https://expensify.slack.com/archives/C05RECHFBEW/p1700683134147369?thread_ts=1700580012.446519&cid=C05RECHFBEW

**Comment by kadiealexander** [comment] 2023-12-05 05:32
Still on hold.

**Comment by flodnv** [comment] 2023-12-15 13:05
I asked here if there's another GH we can follow: https://expensify.slack.com/archives/C05RECHFBEW/p1702645490391279?thread_ts=1700580012.446519&cid=C05RECHFBEW

**Comment by kadiealexander** [comment] 2024-01-08 06:12
Still on hold.

**Comment by flodnv** [comment] 2024-02-12 17:15
Internal planning issue is here: https://github.com/Expensify/Expensify/issues/350373

**Comment by flodnv** [comment] 2024-03-14 20:35
Internal issue may be picked up in the next couple of months with some luck.

**Comment by flodnv** [comment] 2024-04-15 18:32
Still on hold, not a priority at this time.

**Comment by kadiealexander** [comment] 2024-05-21 06:37
Same as above.

**Comment by kadiealexander** [comment] 2024-05-21 06:38
Same as above.

**Comment by kadiealexander** [comment] 2024-06-24 07:57
Still on hold.

**Comment by kadiealexander** [comment] 2024-07-26 04:37
Same as above.

**Comment by kadiealexander** [comment] 2024-08-27 06:25
@flodnv can we close this?

**Comment by dhanashree-sawant** [comment] 2024-08-27 06:34
Hi @kadiealexander, @flodnv is this issue eligible for reporting bonus?

**Comment by flodnv** [comment] 2024-09-03 12:42
This is now on hold for https://github.com/Expensify/App/issues/46611

**Comment by kadiealexander** [comment] 2024-10-07 01:31
Still on hold.

**Comment by flodnv** [comment] 2024-11-11 16:03
Still holding for https://github.com/Expensify/App/issues/46611, we're getting closer.

**Comment by kadiealexander** [comment] 2024-11-12 20:46
@flodnv should we close based on [this](https://expensify.slack.com/archives/C01GTK53T8Q/p1731433085334419)?

**Closed** 2024-11-12 21:51 UTC
Labels: Engineering, Monthly, Internal, Bug
