### ISSUE TITLE
Bug: In safari, Emoji box become blank if we Scroll fast reported by @Tushu17 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11972] opened 2022-10-18 21:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open Website in safari browser
2. Go to chat
3. Open emoji box
4. Scroll fast using mouse scroller/Track pad.

## Expected Result:
It shouldn't become blank.

## Actual Result:
Emoji box become blank if we scroll fast.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web - Safari / Mac

**Version Number:** 1.2.17-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/196544372-36ae70f0-b62e-4659-9ade-4613c851de9b.mov
https://user-images.githubusercontent.com/43996225/196544425-878ed2ec-654a-4558-9f58-cabf9a2d0536.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @Tushu17 

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666124266872599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ntrepanier** [comment] 2022-10-19 16:39
Reassigning since I'm swamped from vacation and I'm ooo to drive home for the next couple of days.

**Comment by MitchExpensify** [comment] 2022-10-19 22:31
I am unable to reproduce this - Closing

**Closed by MitchExpensify** 2022-10-19 22:31 UTC
Labels: Daily, Bug
