### ISSUE TITLE
Split Bill -  Incorrect back button functionality doesn't allow to cancel Split Bill in the group

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20743] opened 2023-06-14 11:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to NewDot
2. Create a group with 2+ people
3. Use the FAB button to create a split within this new group
4. Input amount and click next
5. Try to exit Split Bill flow by clicking back buttons

## Expected Result:
User can exit Split Bill flow

## Actual Result:
User is blocked within Split Bill flow

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.4

**Reproducible in staging?:** yes

**Reproducible in production?:**yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7a66adae-f046-4071-a108-14cfbb4216eb

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-14 13:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split Bill - Incorrect back button functionality doesn't allow to cancel Split Bill in the group
### What is the root cause of that problem?
Here when navigate to prev step 
https://github.com/Expensify/App/blob/20f6ae7dab6cee8c537e491e64ece59163e209af/src/pages/iou/MoneyRequestModal.js#L207-L219

we call 
```
     setPreviousStepIndex(currentStepIndex); 
     setCurrentStepIndex(currentStepIndex - 1); 
```     
so if we in step 1 the result will be

```
     previousStepIndex = 1; 
     setCurrentStepIndex = 0; 
```  
This is cause infinite loop
### What changes do you think we should make in order to solve the problem?
```
     setPreviousStepIndex(currentStepIndex - 2);  <<<<<<<<<<<<<
     setCurrentStepIndex(currentStepIndex - 1); 
```     
### What alternative solutions did you explore? (Optional)

**Comment by bernhardoj** [comment] 2023-06-14 13:48
We are refactoring money request page [here](https://github.com/Expensify/App/pull/17964) and it's a dupe of https://github.com/Expensify/App/issues/17637

**Comment by johncschuster** [comment] 2023-06-20 14:48
@bernhardoj Thanks for calling out that this is a duplicate! I didn't think to use the keywords, "infinite loop" to locate a previously created issue.

Would you say we can close this issue then?

**Comment by bernhardoj** [comment] 2023-06-20 15:40
Yes, I think we can close this one

**Comment by johncschuster** [comment] 2023-06-21 14:42
Thanks! Doing it.

**Closed by johncschuster** 2023-06-21 14:42 UTC
Labels: Daily, Bug
