### ISSUE TITLE
[$1000] Web - Money request - Amount, Description and Date fields have hover over effect, but you cannot actually click or interact into the fields

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19774] opened 2023-05-29 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any money report
2. Observe the hover effect and cursor type on hovering over the mentioned fields

## Expected Result:
They should maintain consistency of hover logic in the app and if they are shown as clickable then they should be clickable otherwise they should not be clickable

## Actual Result:
Amount, Description and Date field have hover on and are clickable but no effect

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c4ea92dd-05d5-4a30-a2ff-f22c2c3fbbad

https://github.com/Expensify/App/assets/93399543/9592df22-72ec-4c0b-8bf5-276d996d864a

**Expensify/Expensify Issue URL:**

**Issue reported by:** @chiragxarora

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685039560029969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e8c3cb679c12ee42</li>
        <li>Upwork Job ID: 1666193040896868352</li>
        <li>Last Price Increase: 2023-06-06</li>
    </ul>
</details>

**Comment by sethraj14** [comment] 2023-05-29 21:12
##Proposal
#Please re-state the problem that we are trying to solve in this issue.
Hover effect over amount description and date in money report section

#What is the root cause of that problem?
We are not sending `interactive` prop to  `MenuItemWithTopDescription` in this file - `MoneyRequestHeader.js`.

#What changes do you think we should make in order to solve the problem?
Sending interactive false will disable the hover effect.

What alternative solutions did you explore? (Optional)

**Comment by sethraj14** [comment] 2023-06-01 21:10
@michaelhaxhiu Can you please review the [proposal](https://github.com/Expensify/App/issues/19774#issuecomment-1567522080).

**Comment by michaelhaxhiu** [comment] 2023-06-02 19:56
I think this may be a dupe _almost_, or at least resolvable in one PR. cc @allroundexperts

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:15
Closing this GH, let's handle this in 1 GH since it's already ongoing and a PR is up.

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:15
https://github.com/Expensify/App/issues/19341#issuecomment-1574264262

**Comment by michaelhaxhiu** [comment] 2023-06-02 20:36
JK undoing everything, I realizing an oversight

**Comment by sethraj14** [comment] 2023-06-02 21:11
@michaelhaxhiu Can I pick this one up, you can review my proposal [here](https://github.com/Expensify/App/issues/19774#issuecomment-1567522080), I am trying to contribute for the first time here.

**Comment by michaelhaxhiu** [comment] 2023-06-02 22:32
We will review proposals on a first come first serve basis.

**Comment by sethraj14** [comment] 2023-06-02 22:49
> We will review proposals on a first come first serve basis.

Yeah, I have the first proposal for this [here](https://github.com/Expensify/App/issues/19774#issuecomment-1567522080).

**Comment by michaelhaxhiu** [comment] 2023-06-06 21:19
Could've sworn the `External` label was added earlier, my fault!

**Comment by trjExpensify** [comment] 2023-06-06 21:30
This is only temporary while @alex-mechler and @marcaaron work on the ability to edit the request detail fields. After which they are clickable/tappable. 

I think we do nothing here. One thing we will want to make sure is that when the request is settled, the amount and date fields are no longer editable. An expense's description can be changed on a `reimbursed` report. 

CC: @mountiny @luacmartins @Julesssss

**Comment by alex-mechler** [comment] 2023-06-06 21:36
I agree, I think we do nothing here since we are actively working on fixing it

**Comment by michaelhaxhiu** [comment] 2023-06-06 22:03
Thanks for chiming in! That's perfect. 

I'll close this GH and pay out the bug bonus.

**Comment by trjExpensify** [comment] 2023-06-06 22:21
>I'll close this GH and pay out the bug bonus.

I don't think it's a bug, it's intentional in a half-implemented state.

**Comment by michaelhaxhiu** [comment] 2023-06-06 22:39
Ah so this was a planned method of implementation. Understood.

**Closed by michaelhaxhiu** 2023-06-06 22:39 UTC
Labels: External, Daily, Bug

**Comment by Julesssss** [comment] 2023-06-07 08:56
Nice, thanks for spotting Tom.

**Comment by chiragxarora** [comment] 2023-06-09 06:01
Sorry for chiming in late, was not really active for past week.
What I see from the above conversation is that fields in request reports are editable intentionally (which makes sense as per your reasoning of providing ability to edit those until the request is settled).
But my initial bug report on slack was not confined just for request report but it was for any money report. I see the similar behavior on send money report and I wonder if those are editable too (even when the money is paid and there's nothing to change after that).

https://github.com/Expensify/App/assets/54641656/0ea74644-1108-41b5-9850-a22416d84fcf

Here's the original bug report on slack by me, the title here is slightly changed
<img width="737" alt="image" src="https://github.com/Expensify/App/assets/54641656/8d150a1c-3a52-48a4-86a7-d89a04b543b7">

**Comment by trjExpensify** [comment] 2023-06-09 11:50
Request/send money have the same report type under the hood (`iou`). In the case of send money, the `iou` report the request gets added to is just in the `reimbursed` state upon creation basically.

So in that case, the `amount` and `date` fields would not be editable, but the `description` field can be in that report state. 

I still think that logic is coming with @marcaaron @alex-mechler PRs to introduce editing.

**Comment by chiragxarora** [comment] 2023-06-13 08:49
So does this count as a bug report? Provided Amount and Date fields are editable when they should not be?
@trjExpensify

**Comment by trjExpensify** [comment] 2023-06-13 13:20
Nope, because it's a new feature that's half-way through development.
