### ISSUE TITLE
[HOLD for payment 2024-05-08] [$250] HIGH: [Polish] Revert the `Message Concierge for help with setup` message

### ISSUE THREAD

**Issue by quinthar** [Expensify/App#41184] opened 2024-04-28 23:54 UTC
Problem:
===
We are working on "Stage 1/2 onboarding", which embeds training into the app for new users.  One part of the design is to assign "tasks" to the user for onboarding steps.  At one point we had talked about creating a new "Expensify" user to assign these tasks to you, and we will still do that in the future to A/B test the effectiveness of a new Expensify user, versus using Concierge.  And when we do that we will make those tasks "read only" -- and encourage you to talk to Concierge about onboarding.  [This is the PR that added it.](https://github.com/Expensify/App/pull/40010)  However, now Concierge is assigning them to you -- so this message is very confusing.  Even worse, it's showing on the wrong chat (ie, in a public room):

![Image](https://github.com/Expensify/App/assets/575186/7e69c3bc-578c-409f-a321-8917ff71b566)

Solution:
===
Let's just revert this message entirely and we can add it later when we are ready to show it. /cc @dubielzyk-expensify @anmurali 

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe3f4f4e21a87651</li>
        <li>Upwork Job ID: 1784733661373624320</li>
        <li>Last Price Increase: 2024-04-28</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 0</li>
<li>neonbhai | Contributor | 0</li>
<li>shubham1206agra | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by neonbhai** [comment] 2024-04-29 05:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Revert the Message Concierge for help with setup message

### What is the root cause of that problem?
We display the footer message here:
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L144

### What changes do you think we should make in order to solve the problem?
We can remove this line to make sure this footer does not show up anywhere for now:
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L144

**Comment by Nodebrute** [comment] 2024-04-29 05:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Revert the Message Concierge for help with setup message
### What is the root cause of that problem?
This message was added in this PR https://github.com/Expensify/App/pull/40010
### What changes do you think we should make in order to solve the problem?

Remove `|| !canWriteInReport` from this line
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L136

Remove this line
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L144

Remove these lines too 
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L85
https://github.com/Expensify/App/blob/d47413da94d8931cc33103a2273ee02790687df8/src/pages/home/report/ReportFooter.tsx#L24
### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-04-29 10:34
@ishpaul777 @neonbhai @Nodebrute rather than reverting, could you please propose a change that would keep the banner for "system" type chats but not for the public chats

Ideally i think we can just update the logic to show this concierge banner only when the Sign up public chat does not show (and the write permissions are missing)

**Comment by neonbhai** [comment] 2024-04-29 10:42
Proposal [updated](https://github.com/Expensify/App/issues/41184#issuecomment-2081895295)

@mountiny @ishpaul777

**Comment by mountiny** [comment] 2024-04-29 10:57
Can you also check for announce chat and make sure we dont show this banner there either. 

We can update the logic to temporarily only show this banner at "system" type chat reports.

Who can please implement that?

**Comment by mountiny** [comment] 2024-04-29 10:59
@neonbhai looks good but to be on a safe side, lets only show this for system chat report to also catch any other cases like announce chat report

**Comment by mountiny** [comment] 2024-04-29 11:00
Please go ahead with the PR to only show the banner for system type chat reports

**Comment by neonbhai** [comment] 2024-04-29 11:19
@mountiny hi, by system type chat report do you mean the Concierge chat?
As we don't have an explicit chat type of system [(ref)](https://github.com/Expensify/App/blob/30bfabc7559318bf64c888a735c338656680933e/src/CONST.ts#L50-L59)

**Comment by strepanier03** [comment] 2024-05-08 23:50
Automation didn't kick this back to Daily. Will do that now and review.

**Comment by strepanier03** [comment] 2024-05-08 23:52
Just confirming, based on the PR it looks like @shubham1206agra took over reviewer right away and @ishpaul777 is NOT owed payment? If that's incorrect please let me know.

**Comment by strepanier03** [comment] 2024-05-08 23:57
### Payment Summary

- @neonbhai $250 via Upwork ([offer](https://www.upwork.com/nx/wm/workroom/37140000/overview)) - paid
- @shubham1206agra $250 via Upwork ([offer](https://www.upwork.com/nx/wm/offer/102227420)) - pending acceptance

**Comment by strepanier03** [comment] 2024-05-08 23:57
Will check in tomorrow.

**Comment by strepanier03** [comment] 2024-05-09 23:25
Contract was accepted so I finished paying it out and closed it. 

Everything is all set here, thanks!

**Closed by strepanier03** 2024-05-09 23:25 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
