### ISSUE TITLE
[HOLD for payment 2024-03-26] [$500] BA - Not able to add Regions BA, modal redirects to initial Bank account page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38069] opened 2024-03-11 18:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.50-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Unable to check
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4413762
**Email or phone of affected tester (no customers):** applausetester+vd_mweb031124@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Pre-requisite: user must be logged in on mWeb/Safari (iPhone) and must have created a Workspace.

1. Go to Workspace > Bank account.
2. Select Connect online with Plaid.
3. Select Regions bank and use the testing credentials.

## Expected Result:
The page to confirm the account should be displayed.

## Actual Result:
The modal redirects to the initial add bank account page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5dc83ec7-74ff-4f7f-886c-c99a656f869c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a531e07d9e5f1c52</li>
        <li>Upwork Job ID: 1767269083257348096</li>
        <li>Last Price Increase: 2024-03-11</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-11 18:04
@chiragsalian I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by dylanexpensify** [comment] 2024-03-11 18:46
commented [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1710182633757369?thread_ts=1709923251.115559&cid=C03UK30EA1Z)

**Comment by chiragsalian** [comment] 2024-03-11 19:19
I'm pretty sure this is external since it's happening only on mWeb. Assigning external label.

**Comment by abzokhattab** [comment] 2024-03-11 23:09
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not able to add Regions BA, modal redirects to initial Bank account page
### What is the root cause of that problem?
 
The `BankAccountStep` reinitializes the bank connection if the following condition is true:
https://github.com/Expensify/App/blob/1a9ceb775cd5c52a74405722689e0a1f38bfb3e9/src/pages/ReimbursementAccount/BankAccountStep.js#L80

so in case of mWeb for some reason the `receivedRedirectURI` is not `null` as in other platforms which causes it to reinitialize the bank connect
### What changes do you think we should make in order to solve the problem?

we can move the `receivedRedirectURI` outside of the component the same as we are doing in the `BankInfo` component here: 
https://github.com/Expensify/App/blob/d0b0c93b93d7fc95d468ffaeeece9515ca7d2181/src/pages/ReimbursementAccount/BankInfo/BankInfo.tsx#L46-L57

this way we will have a consistent behaviour in both components which ensures that the bank connect works in `mWeb`

**Comment by abzokhattab** [comment] 2024-03-12 01:47
Does that mean its not occurring on production? As far as i can see we were not able to test it on prod

**Comment by abzokhattab** [comment] 2024-03-12 02:00
Thanks, honestly I am not able to find it i just checked the differences between staging and production and I see that all the changes are not related to the bank setup.

https://github.com/Expensify/App/compare/production...staging

let me know if you are able to find any

**Comment by abzokhattab** [comment] 2024-03-12 02:15
Yes, the issue is reproducible on both:


Uploading Screen Recording 2024-03-12 at 4.07.45 AM.mov…

https://github.com/Expensify/App/assets/59809993/e332d60c-dd1b-4bce-b771-da4c75abbf8a

**Comment by chiragsalian** [comment] 2024-03-12 06:06
Proposal LGTM. Feel free to create the PR for this @abzokhattab.
Try to prioritize this since we'll have to try to get it reviewed/merged and CP'd soon since the issue is a blocker.

**Comment by luacmartins** [comment] 2024-03-12 18:23
We're demoting this to NAB since we could reproduce the same issue on this [adboc build](https://github.com/Expensify/App/pull/37316#issuecomment-1979489080) that was deployed to prod 5 days ago. We think this is a Plaid issue on their sandbox API.

**Comment by bernhardoj** [comment] 2024-03-13 05:13
Most likely related to https://github.com/Expensify/App/issues/32356

**Comment by bernhardoj** [comment] 2024-03-13 06:04
I already have a proposal [there](https://github.com/Expensify/App/issues/32356#issuecomment-1836289901)

**Comment by dylanexpensify** [comment] 2024-03-13 10:31
Moving along!

**Comment by bernhardoj** [comment] 2024-03-13 11:23
@shubham1206agra I don't know if it's the same issue or not because, in https://github.com/Expensify/App/issues/32356, the connect option page is shown for a few seconds before showing the correct step, 

but in the OP video, looks like the correct step is never shown and I can't reproduce that.

You can test it here: https://github.com/bernhardoj/Expensify/tree/fix/plaid-reopening-on-rerender

**Comment by luacmartins** [comment] 2024-03-14 16:27
That sounds good to me, but I'll let @chiragsalian handle this since he's the assigned engineer on this issue

**Comment by chiragsalian** [comment] 2024-03-14 16:54
Yup that sounds good to me. Feel free to create a PR @bernhardoj.

**Comment by dylanexpensify** [comment] 2024-03-20 10:57
Payment coming up!

**Comment by dylanexpensify** [comment] 2024-03-27 08:16
paying out today!

**Comment by dylanexpensify** [comment] 2024-04-09 13:33
Payment summary:
- Contributor: @bernhardoj $500
- Contributor+: @shubham1206agra $500

Please apply/request!

**Comment by dylanexpensify** [comment] 2024-04-09 13:34
@bernhardoj please accept offer when ready and I'll pay it out!

**Comment by bernhardoj** [comment] 2024-04-09 13:40
@dylanexpensify the offer is broken.
<img width="747" alt="image" src="https://github.com/Expensify/App/assets/50919443/d5af69f0-5fd5-4f29-b51b-3990f92a2243">

**Comment by dylanexpensify** [comment] 2024-04-15 12:35
@bernhardoj sent an invite to apply!

**Comment by bernhardoj** [comment] 2024-04-15 12:50
@dylanexpensify applied

**Comment by dylanexpensify** [comment] 2024-04-15 12:57
@bernhardoj sent!

**Comment by dylanexpensify** [comment] 2024-04-15 13:04
done!

**Comment by luacmartins** [comment] 2024-04-23 15:53
@dylanexpensify seems like we missed paying @shubham1206agra

**Comment by dylanexpensify** [comment] 2024-04-29 10:21
Ayy, on it!

**Comment by dylanexpensify** [comment] 2024-04-29 10:23
@shubham1206agra invited you to apply 😄

**Comment by dylanexpensify** [comment] 2024-04-30 13:44
@shubham1206agra offer sent!

**Comment by dylanexpensify** [comment] 2024-05-07 08:23
paying now!

**Closed** 2024-05-07 08:24 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
