### ISSUE TITLE
[HOLD for payment 2024-06-05] [$250] Group chat - Inconsistency with highlight of group admin row by cursor, up & down and Tab key

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#41570] opened 2024-05-03 10:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.70-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a group chat.
3. Click on the tap header > Members.
4. Navigate through member list by keyboard up and down key.
5. Note that admin cannot be navigated with up and down key and is not highlighted.
6. Click on the admin.
7. Click back button.
8. Note that admin is highlighted.
9. Now navigate through member list with Tab key.

## Expected Result:
There should be consistency in whether group admin row can be highlighted.

## Actual Result:
In Step 4, group admin cannot be selected and highlighted by keyboard up and down key.
In Step 7, when clicking on the group admin with cursor, the group admin is selected and highlighted.
In Step 9, with Tab key, group admin can be selected and highlighted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/9514b9db-16f3-46a8-bed9-080ac3daa111

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012cce511dc289f3d0</li>
        <li>Upwork Job ID: 1786399061346992128</li>
        <li>Last Price Increase: 2024-05-03</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by izarutskaya** [comment] 2024-05-03 10:46
We think this issue might be related to the #vip-vsb.

**Comment by bernhardoj** [comment] 2024-05-03 12:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We can highlight the admin member in group participants page with Tab key or when clicking it to open the detail and go back.

### What is the root cause of that problem?
In group member/participant, the checkbox will be disabled if it's the current user, which means the item itself is still enabled, only the checkbox is disabled.
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/pages/ReportParticipantsPage.tsx#L94

So, we can use TAB key to focus on the item, and `isItemFocused` will be true because it's not disabled.
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/components/SelectionList/BaseSelectionList.tsx#L341-L342

But we can't focus on it with the arrow key because it's included in the disabledOptionsIndexes.
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/components/SelectionList/BaseSelectionList.tsx#L134-L136
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/components/SelectionList/BaseSelectionList.tsx#L230-L233

### What changes do you think we should make in order to solve the problem?

If the expectation is to allow the user to focus on the item that only has a checkbox disabled with the arrow key, then we can either
1. Filter out the disabled indexes that have the disabled checkbox value as true.
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/components/SelectionList/BaseSelectionList.tsx#L233
```
disabledIndexes: flattenedSections.disabledOptionsIndexes.filter((index) => !flattenedSections.allOptions[index].isDisabledCheckbox),
```
2. Or create a new disabled indexes array (disabledArrowKeyOptionsIndexes) for the arrow key that doesn't contain the checkbox disabled item.
```
if (!!section.isDisabled || item.isDisabled || item.isDisabledCheckbox) {
    disabledOptionsIndexes.push(disabledIndex);
    if (!item.isDisabledCheckbox) {
        disabledArrowKeyOptionsIndexes.push(disabledIndex);
    }
}
```

We need to keep the `disabledOptionsIndexes` as is, otherwise, the select all button will be enabled even if the only member left is the admin.

If the expectation is to prevent the disabled checkbox item from being focused/highlighted, then we need to add it to the disabled condition here.
https://github.com/Expensify/App/blob/0f39e4370ccd84ccf7e1647b42cb505a69a2e9a3/src/components/SelectionList/BaseSelectionList.tsx#L341-L342

```
const isItemFocused = (!isDisabled && !item.isDisabledCheckbox) && ...
```

but it will still be able to have the blue outline focus (when we use TAB) because the pressable is not disabled.
<img width="376" alt="image" src="https://github.com/Expensify/App/assets/50919443/94d7aef8-7c1d-41e3-bf07-550d2b53bbdb">

**Comment by Santhosh-Sellavel** [comment] 2024-05-06 17:00
Asked for volunteers to pick this up [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1715014831077069)

**Comment by Santhosh-Sellavel** [comment] 2024-05-06 17:03
Unassigned myself due to less bandwidth

**Comment by DylanDylann** [comment] 2024-05-06 17:05
I will take over this one as C+

**Comment by puneetlath** [comment] 2024-05-06 17:39
Putting the `Help Wanted` label back on. @DylanDylann is taking the C+ role, so we're still looking for a contributor.

**Comment by DylanDylann** [comment] 2024-05-07 15:21
Before evaluating proposals, we need to confirm the expectation first with @Expensify/design 

1. Let's see the tab key behavior, when clicking the tab key we will focus on the member border 


<img width="1135" alt="Screenshot 2024-05-07 at 22 13 23" src="https://github.com/Expensify/App/assets/141406735/64c8b40c-00f0-46ad-9d93-76018c40f519">

In here, If we click enter, the detail member will open
On the other hand, If we click the tab key one more time, the checkbox will be focused
<img width="1122" alt="Screenshot 2024-05-07 at 22 13 06" src="https://github.com/Expensify/App/assets/141406735/00eb1030-bb5d-4d45-9444-c6132f997dde">
Here, if we click enter, the checkbox will be selected

IMO, the current behavior is correct 

2. Let's see the up/down behavior, when clicking the down/up key we will focus on the member border 

<img width="1135" alt="Screenshot 2024-05-07 at 22 13 23" src="https://github.com/Expensify/App/assets/141406735/64c8b40c-00f0-46ad-9d93-76018c40f519">

Here, If we click enter, the detail member will open. If we click the down/up key one more time, the App will focus on the next member border (If the next member border is admin, we will skip it and go to the next item)

https://github.com/Expensify/App/assets/141406735/1844219c-bb62-4a53-8bdb-9f0b661cb7e1


IMO, with the current behavior, when clicking up/down key we shouldn't skip the admin member

**Comment by dannymcclain** [comment] 2024-05-07 16:01
>IMO, with the current behavior, when clicking up/down key we shouldn't skip the admin member because we allow user to open the detail page of the admin

I agree with this. I would expect to be able to arrow through the list and hit enter to open each member's profile.

**Comment by DylanDylann** [comment] 2024-05-09 10:04
@Krishna2323 Your proposal will make the select all button break
@dragnoir When we pass an empty array to disabledIndexes, we miss the disabled item (`section.isDisabled || item.isDisabled`)
I like @bernhardoj's [solution 2](https://github.com/Expensify/App/issues/41570#issuecomment-2092901175)

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-05-10 09:28
PR is ready

cc: @DylanDylann

**Comment by DylanDylann** [comment] 2024-06-05 04:32
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal

**Prerequisite: Create a new group chat**

1. Open the group chat
2. Press the header to open the detail and press Members
3. Use arrow key/down to navigate between the list
4. Verify it can highlight the admin member.


Do we agree 👍 or 👎

**Comment by puneetlath** [comment] 2024-06-05 13:53
Issue for regression test: https://github.com/Expensify/Expensify/issues/402260

Everyone has been paid. Thanks y'all!

**Closed by puneetlath** 2024-06-05 13:53 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
