### ISSUE TITLE
Chat - New Message Notification Persists After Message is Deleted

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20861] opened 2023-06-15 20:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Write a new message and mark it as unread.
3. Delete the new message and observe that the new message notification still persists.

## Expected Result:
The new message notification should disappear when the new message is deleted.

## Actual Result:
The new message notification persists even after the new message is deleted.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27.7

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture (69) (1).webm](https://github.com/Expensify/App/assets/93399543/c71a9430-89bb-481f-a5bb-adc36853715e)

https://github.com/Expensify/App/assets/93399543/2560b6bf-a6a5-40e3-b253-441be95d9b1d

**Expensify/Expensify Issue URL:**

**Issue reported by:** @tewodrosGirmaA

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686234925322769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by DanutGavrus** [comment] 2023-06-15 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Message Notification Persists After Message is Deleted

### What is the root cause of that problem?
Right now, if `newMarkerReportActionID` is not empty, then we show the `FloatingMessageCounter`:
https://github.com/Expensify/App/blob/205899fe2db8e848e732d9ab6ba7ea34c3dfd413/src/pages/home/report/ReportActionsView.js#L342-L345
Right now, inside `componentDidUpdate`, when a message is deleted, we set `newMarkerReportActionID` to the new value if there are other unread messages:
https://github.com/Expensify/App/blob/205899fe2db8e848e732d9ab6ba7ea34c3dfd413/src/pages/home/report/ReportActionsView.js#L212-L218
The problem is that, after user deletes the last unread message, `newMarkerReportActionID` is not set to `''`, keeping the old value set above.

### What changes do you think we should make in order to solve the problem?
We should add this under the above check:
```js
if (!_.isEmpty(this.state.newMarkerReportActionID) && !ReportUtils.isUnread(this.props.report) && prevProps.reportActions.length > this.props.reportActions.length) {
    this.setState({
        newMarkerReportActionID: ''
    });
}
```
`!_.isEmpty(this.state.newMarkerReportActionID)` is for optimization, to prevent multiple `setState` calls when `newMarkerReportActionID` was already cleared.
<details>
<summary>Video with the result:</summary>
<video src="https://github.com/Expensify/App/assets/56603839/22d6bdf7-1071-4af4-9328-566ab1cf7b86"/>
</details>

**Comment by StevenKKC** [comment] 2023-06-15 20:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New message notification remains after a message marked as unread has been deleted.

### What is the root cause of that problem?
New message notification is displayed by `newMarkerReportActionID` in `ReportActionsView.js`.
When delete a message is deleted, `newMarkerReportActionID` is updated by the following code.

However, since the message was previously marked as unread, `ReportUtils.isUnread(this.props.report)` returns `false`, so `newMarkerReportActionID` is not updated and new message notification remains.

### What changes do you think we should make in order to solve the problem?
We should remove `ReportUtils.isUnread(this.props.report)` condition as described below.
Since the number of actions has decreased, the message has been deleted and we should update `newMarkerReportActionID`.
```
if (prevProps.reportActions.length > this.props.reportActions.length) {
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by sakluger** [comment] 2023-06-20 02:46
I was able to reproduce this, but the "New" bar only stayed for about half a second before disappearing. I wasn't able to reproduce so that the new bar stayed any longer than that. Still, I think this is a bug, the New bar should be removed at the same time as the comment is deleted.

**Comment by sakluger** [comment] 2023-06-20 02:51
What I saw (where it only stays for a second) is a duplicate of https://github.com/Expensify/App/issues/20759. But I also was able to reproduce where you scroll up and it shows the "New Messages" pill. I'm going to ask in the other issue to see if they have the same root cause or if they are different.

**Comment by DanutGavrus** [comment] 2023-06-20 11:47
@sakluger This one fixes this issue and also the other [issue](https://github.com/Expensify/App/issues/20759) from their root cause:

## New Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Message Notification Persists After Message is Deleted. & Web - Thread - When deleting the last unread message, the "New" marker briefly appears for a second before disappearing.

### What is the root cause of that problem?
1. In `ReportActionsView.js` we handle the **state** of `newMarkerReportActionID`.
2. `ReportActionsView.js` renders both `FloatingMessageCounter` component.
2.1. `FloatingMessageCounter` handles the **New Messages** pill and receives the `newMarkerReportActionID` as a prop.
3. The problem is that `newMarkerReportActionID` is not cleared after the network call finishes deleting the message, thus keeping the old value and showing the **New Messages** pill indefinitely.  

### What changes do you think we should make in order to solve the problem?
We should clear the `newMarkerReportActionID` after deleting the last unread message.

To do this, we need to add this logic inside `ReportActionsView.js` in `componentDidUpdate`:
```js
        if (this.props.reportActions[0].pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
            const reportActionsWithoutPendingOne = this.props.reportActions;
            reportActionsWithoutPendingOne.shift();
            this.setState({
                newMarkerReportActionID: ReportUtils.getNewMarkerReportActionID(this.props.report, reportActionsWithoutPendingOne),
            });
        }
```  

This way, after deleting the last message `ReportUtils.getNewMarkerReportActionID` will return `''`, clearing the **New Messages** pill.

**Comment by sakluger** [comment] 2023-06-20 22:59
Still discussing in the other issue whether we should solve together or separately.

**Comment by ahmedGaber93** [comment] 2023-06-21 09:27
> Actual Result : The new message notification persists even after the new message is deleted.

Can't reproduce with me, it just has a delay for second, but it removed. Did I miss something?



https://github.com/Expensify/App/assets/41129870/6af03e62-0f0d-4f27-81f6-cc5aea326e97

**Comment by tewodrosGirmaA** [comment] 2023-06-21 09:40
Hi, @ahmedGaber93, to reproduce the issue, please follow these steps:
1. Write 5 to 7 messages.
2. Mark the last message as unread.
3. Scroll up and observe that the "New message" header pops up.
4. Delete the last message.
5. Scroll down again and notice that the "New message" notification still persists, even though the message has been deleted, Thank you

**Comment by tewodrosGirmaA** [comment] 2023-06-21 09:50
Contributor details
My Expensify account email: israeltesema45@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0142af0eda23e59363

**Comment by sakluger** [comment] 2023-06-23 00:22
Still holding on discussion in the other issue - seems like they both may stem from the same root cause, and if so, we'll close this one as a duplicate.

**Comment by sakluger** [comment] 2023-06-27 00:35
Closing as a duplicate of https://github.com/Expensify/App/issues/20759. Since that other one was reported first, we will only be paying a reporting bonus for that report as well.

**Closed by sakluger** 2023-06-27 00:35 UTC
Labels: Daily, Overdue, Bug

**Comment by tewodrosGirmaA** [comment] 2023-06-27 04:00
Hello,@sakluger I would like to clarify that my concern is not about the brief notification that appeared at the top of the message and disappeared after a few seconds. My concern is regarding the "New message" notification that appears below the header and lasts for about 12-15 seconds. The previous report mentioned a small notification that appeared briefly after deleting a message, but I am referring to a different notification. If this is not a bug, then please disregard my report and close the issue. Thank you. To understand my point please refer below video.

**Comment by tewodrosGirmaA** [comment] 2023-06-27 04:16
Good Morning @sakluger [screen-capture (65).webm](https://github.com/Expensify/App/assets/118253010/c58b96e4-83fc-4ba7-9d60-a11844a7f4ab)

**Comment by tewodrosGirmaA** [comment] 2023-06-27 04:20
steps                                    Write 5 to 7 messages.
Mark the last message as unread.
Scroll up and observe that the "New message" header pops up.
Delete the last message.
Scroll down again and notice that the "New message" notification still persists, even though the message has been deleted, Thank you

**Comment by tewodrosGirmaA** [comment] 2023-06-27 12:02
I am not sure, but I hope @sakluger can explain it.
