### ISSUE TITLE
[HOLD for payment 2024-12-03] [Search v1.2] Android - Expense - Unexpected error when submitting expense to same WS after paying another

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52368] opened 2024-11-12 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.60-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5204723&group_by=cases:section_id&group_order=asc&group_id=319502
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on the FAB and select "Submit Expense"
3. Complete the expense creation process and send the expense to any workspace.
4. Tap on "Search" on the bottom of the screen.
5. Tap on "Outstanding"
6. Tap on "Pay" on the preview of the just created expense.
5. Tap on the FAB and select "Submit Expense"
6. Complete the expense creation flow and send the expense to the same workspace of the just paid expense.
7. Tap on "All"
8. Open the report of the two workspace expenses.
9. Verify the new expense was created properly and is displayed on search section.

## Expected Result:
The user should be able to create a new expense and send it to the same workspace of the just paid one, and this new expense should be displayed properly on "Search" section.

## Actual Result:
When the user pay an expense via "Pay" button on expense preview on search, create another one and send it to the same workspace, an "Unexpected error" is displayed and the new expense is not created.
Issue can be reproduced only with Gmail accounts.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/04415850-a5d8-4487-8940-e1aaef9291af
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by joekaufmanexpensify** [comment] 2024-11-12 15:33
I can't reproduce this on my gmail.com account. Works fine for me. I see the issue title says Android, but multiple platforms are selected, so I tested on web. 

https://github.com/user-attachments/assets/bd52d4b4-695b-4ea6-8008-1b5594c5c945

**Comment by francoisl** [comment] 2024-11-12 18:51
I can repro – it's worth noting that it only seems to happen with distance expenses. Going to check logs.

**Comment by francoisl** [comment] 2024-11-12 20:15
Looks like this is fixed on main, there's probably something that's been merged we just need to CP 👀

**Comment by francoisl** [comment] 2024-11-12 22:37
Ok I think I finally figured out exactly why it's happening and why I couldn't repro consistently. I think it's a backend issue – when you pay an expense from the Search page, the command `PayMoneyRequestOnSearch` doesn't update the status of the IOU report in Onyx, so when you try to create another expense, the client tries to create it on the same report as the previous one because it thinks it's still open, but in the backend the report is actually reimbursed.

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/91eec97b-691a-45cc-8169-ade3645d16f8">
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/ac3c6be8-8b55-44fa-841c-3694a2c7c2bc">

**Comment by luacmartins** [comment] 2024-11-12 22:41
@francoisl I'm reverting my PR which allows paying expenses on Search. I can take over this issue to fix it in the v2 of my PR if you'd like

**Comment by luacmartins** [comment] 2024-11-12 22:41
>x, so when you try to create another expense, the client tries to create it on the same report as the previous one because it thinks it's still open

AFAIK the backend should handle this and just update the client.

**Comment by francoisl** [comment] 2024-11-12 22:41
Ok yeah, works for me if you don't mind. Thanks!

**Comment by francoisl** [comment] 2024-11-12 22:43
> AFAIK the backend should handle this and just update the client.

Yeah that's what I was starting to look into - Auth only generates a `snapshot_` update in this case ([ref](https://github.com/Expensify/Auth/blob/0232aac39e8f8388de5d8e203bf58d572e111198/auth/command/PayMoneyRequestOnSearch.cpp#L120)) - not super familiar with that feature so I wasn't sure if it's on purpose.

**Comment by Beamanator** [comment] 2024-11-13 07:40
Thaaaaaaanks for getting this figured out gents 🙏

**Comment by luacmartins** [comment] 2024-11-13 20:20
@joekaufmanexpensify I'm just keeping this open so I can track it in v2 of my PR that got reverted. I'll unassign you since we'll track that in the main issue.

**Comment by joekaufmanexpensify** [comment] 2024-11-13 20:28
Got it. TY!

**Comment by luacmartins** [comment] 2024-11-19 16:54
I put up a fix for this and we'll retest once the App PR is merged

**Comment by luacmartins** [comment] 2024-11-27 22:54
This is done

**Closed by luacmartins** 2024-11-27 22:54 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug
