### ISSUE TITLE
Inconsistency in email font size when hovering over email and photo in group members section

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20982] opened 2023-06-18 13:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and split a bill by selecting "Split Bill"
2. Enter amount
3. Select two random emails
4. Select split
5. Click on the report
6. Hover over the email and then over the photo. When hovering over the email, the font size is displayed boldly, while when hovering over the photo, the font size is displayed lightly.

## Expected Result: 
When hovering over the email and photo, the email should have a consistent font size.
## Actual Result: 
When hovering over the email and photo, the tooltip shows different email font sizes.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-6
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687020595022329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kevinksullivan** [comment] 2023-06-19 15:04
I am unable to reproduce this on v1.3.28-3

<img width="787" alt="image" src="https://github.com/Expensify/App/assets/22508290/c0e78a7d-40da-4f1d-baad-111714fbe45c">

<img width="794" alt="image" src="https://github.com/Expensify/App/assets/22508290/3246e9a4-263e-4cd5-8048-bbae6396618e">


Taking to slack to get clarity on whether this is still an issue.

**Comment by tewodrosGirmaA** [comment] 2023-06-19 15:37
Hi @kevinksullivan  , this issue happened on staging v1.3.29-2

**Comment by srikarparsi** [comment] 2023-06-19 17:01
Hi @kavimuru, I am also unable to reproduce this issue on staging or dev. Will close it out but please reopen if necessary

https://github.com/Expensify/App/assets/48188732/84b03f7a-938c-45f2-a359-cab6c237b0b1

https://github.com/Expensify/App/assets/48188732/943264cc-7483-4cb2-aca4-f039dfb3ceb6

**Comment by kavimuru** [comment] 2023-06-19 17:30
@srikarparsi I am also not able to reproduce in the latest version.

**Comment by tewodrosGirmaA** [comment] 2023-06-19 17:34
yes The above bug reproduced on 1.3.29-0, in latest version(1.3.29-2) I am also not able to reproduce

**Comment by tewodrosGirmaA** [comment] 2023-06-19 17:50
[screen-capture (25).webm](https://github.com/Expensify/App/assets/118253010/3975f138-5c47-47ae-972f-674f8932d549)
Hey @srikarparsi, can you check this situation? Go to the plus sign > split bill > add desired number and click "next" > click on the profile to see the details > hover over the split bill members' email and photo to observe the difference. The email text is bold, while the photo text is lighter             ....since the root couse is semilar , in above I reproduced in group memebers , now this happen on split bill memebers.    Thank you

**Comment by kevinksullivan** [comment] 2023-06-20 13:26
Discussed further in slack and it is a different issue specific to split bill, as @tewodrosGirmaA  mentioned. Here's how they differ:

**Staging**
- Hovering over avatar and email show unbold / bold text

[screen-capture (25).webm](https://github.com/Expensify/App/assets/22508290/b2a5d4ba-992a-485d-acab-9480f1766373)


**Production**
- Only hovering over avatar shows text

<img width="1422" alt="image" src="https://github.com/Expensify/App/assets/22508290/d162b968-de9c-4119-a07c-05d9a71bba90">

**Comment by srikarparsi** [comment] 2023-06-22 18:48
Will close it out as the split bill members page is consistent with the group members page (both the avatar and the name are bold on hover and can be clicked on to visit profile). @kevinksullivan please reopen though if you feel we should look into it.

**Closed by srikarparsi** 2023-06-22 18:48 UTC
Labels: Engineering, Hourly, Bug
