### ISSUE TITLE
[HOLD for payment 2024-08-19] [$250] Update the Wallets page to put bank accounts at top 

### ISSUE THREAD

**Issue by danielrvidal** [Expensify/App#46242] opened 2024-07-25 22:39 UTC
Problem: Users are trying to setup their reimbursement accounts and running into confusion. They actually are setting up the reimbursement account successfully, but then find the Wallets page where there is a big green `Enable Wallet` button above their `Bank accounts` section. On top of that, they are trying to enable their wallet and then run into confusing errors setting up their wallet, which are expected because we haven't cleaned up the wallet flow, nor error messages ([background](https://expensify.slack.com/archives/C041MSTR8J1/p1721943101714229?thread_ts=1721343923.634099&cid=C041MSTR8J1))
![image](https://github.com/user-attachments/assets/a21b67f5-751b-45d0-82bb-106656076248)

Solution: Put `Bank accounts` above `Expensify Wallet` and emphasize bank accounts more. 
1. Let's put the Bank accounts section/enablement above the Expensify wallet section
2. Let's add an image as part of bank accounts to the Bank accounts section
3. Update the text for each section to be:

Bank accounts
```
[Bank accounts image]

*Bank accounts*
Adding a bank account allows you to get paid back for expenses you submit to a workspace.

[+ Add bank account]
```

Wallet 
```
*Send and receive money with friends*
Enable your wallet to send and receive money with friends. 

Balance
$X.XX

[:wallet: Enable wallet]
```
You'll notice a different title and we've emphasized the big green button for the wallet. 

Here is a screenshot of the updated page @shawnborton mocked up. We updated the copy a bit so please use the copy above. He will get you the image we're going to use for the bank accounts section.
![image](https://github.com/user-attachments/assets/a8f00661-bc23-4a85-b4ee-5cc826e36cff)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbcb038228b4c6a0</li>
        <li>Upwork Job ID: 1816609222716969047</li>
        <li>Last Price Increase: 2024-07-25</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 103283186</li>
<li>Krishna2323 | Contributor | 103283188</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by shawnborton** [comment] 2024-07-26 07:40
It would use the same design, we just need some updated copy for that which shouldn't be a huge deal.

**Comment by neil-marcellini** [comment] 2024-07-26 17:53
I'm going to go with @Krishna2323's proposal because it was first, and his edits based on other proposals were minimal. I'm sure all of your are very capable of handling this kind of work, and the proposals don't need to be super detailed, so it seems most fair to go with the person that posted first.

**Comment by danielrvidal** [comment] 2024-08-09 22:50
It was merged to staging yesterday so it should be done soon.

**Comment by alexpensify** [comment] 2024-08-19 21:00
Payouts due: 2024-08-19

- [X] Contributor: $250 @paultsimura 
- [X] Contributor+: $250 @Krishna2323 

Upwork job is [here](https://www.upwork.com/jobs/~01dbcb038228b4c6a0).


I've completed the payment process via Upwork and will close this issue for now. Later this week, I'll create the regression test request.

**Closed by alexpensify** 2024-08-19 21:00 UTC
Labels: External, Daily, Awaiting Payment
