### ISSUE TITLE
Web – The down arrow for the "new message" notification is positioned on the left side in comparison to the placement of other buttons

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26711] opened 2023-09-04 19:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Mark any message as unread and scroll to the top to make the "New Message" notification appear within a button. Take note that the arrow inside the button is on the left side.
3. Proceed to the "request money" section and locate the "See More" button. Observe that the down arrow is on the right side.
4. Navigate to the "request money" chat and notice that in the header, the down arrow next to "Pay Elsewhere" is on the right side.

## Expected Result:
Consistency should be maintained in the placement of arrows, either on the left or the right side.

## Actual Result:
An inconsistency is observed. In the "New Message" notification, the arrow is positioned on the left side, unlike in other sections where it is on the right side.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.63.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/77d9e985-0fdd-4cbe-aff3-a54827e390ec

https://github.com/Expensify/App/assets/93399543/7f2f2f76-6821-4f03-8f43-2bc0d9e75389

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693465851943509

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alphaboss1104** [comment] 2023-09-04 22:57
This is Dupe of  #26670

**Comment by sophiepintoraetz** [comment] 2023-09-05 02:38
Agreed.

**Closed by sophiepintoraetz** 2023-09-05 02:38 UTC
Labels: Daily, Bug
