### ISSUE TITLE
[HOLD /react-native-live-markdown#366] [$250] IOU - one character descriptions are not saved

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40799] opened 2024-04-23 13:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/40176
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB > Submit expense > Manual
3. Input an amount
4. Select a user
5. Click on "Description"
6. Insert one character letter without any spaces afterwards and should be any character except numbers (e.g "A" or "B")
7. Click on Save

## Expected Result:
One character letter should be saved

## Expected Result:
One character letter is not saved as a Description but works fine with one digit numbers and 2 character letters. In order to save the description user has to insert whitespace by tapping on space after the character and hit save

## Actual Result:
Unknown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/01e026d1-a804-40c0-948e-bdd163f798c0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160ab7a88d7f75bcd</li>
        <li>Upwork Job ID: 1782806229081673728</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-04-23 13:51
@sakluger  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-23 13:52
We think that this bug might be related to #vip-vsp

**Comment by climax0916** [comment] 2024-04-23 19:42
I couldn't reproduce this issue either.
I think that issue is related to the encoding, so the one character wasn't recognized as finished.
I am not sure about it.

**Comment by proverbed** [comment] 2024-04-24 09:39
Same here, unable to reproduce locally, or on `staging`

**Comment by sakluger** [comment] 2024-04-24 22:45
It seems like some people are having trouble reproducing the issue. @charles-liang were you able to reproduce the behavior? If so, did you do anything that wasn't outlined in the reproduction steps above?

**Comment by sobitneupane** [comment] 2024-04-25 09:29
Thanks for the proposal and reproduction steps @charles-liang. I was able to reproduce the issue with single character.

Can you please add more details in your RCA? Why does the setValue function only receives part of the input?

> "When the onBlur event triggers, the text value is 'g1', but the setValue function only receives 'g'."

**Comment by sobitneupane** [comment] 2024-04-26 08:07
> If isMarkdownEnabled must be set to true, I found the root cause in react-native-live-markdown.

Great finding @charles-liang 

In that case I am pretty sure, the issue lies on Composer as well. So, setting `isMarkdownEnabled` to false is not an option. What's your proposal for the solution?

**Comment by sobitneupane** [comment] 2024-04-30 08:41
@charles-liang Proposal is not updated. Also, please consider https://github.com/Expensify/App/issues/40799#issuecomment-2082129912 in your solution.
<img width="845" alt="Screenshot 2024-04-30 at 14 24 46" src="https://github.com/Expensify/App/assets/25876548/a4e1f01a-f512-4795-b9b4-40989549553a">

**Comment by sakluger** [comment] 2024-05-02 01:00
@sobitneupane thoughts on the updated proposals?

**Comment by sobitneupane** [comment] 2024-05-02 09:58
Thanks for the update @charles-liang 

Your latest proposal looks good to me. @BartoszGrajdek Can you please give [this proposal](https://github.com/Expensify/App/issues/40799#issuecomment-2075206243) a look? The proposal is suggesting to make changes in `react-native-live-markdown` repo to solve this issue. Related to [these](https://github.com/Expensify/react-native-live-markdown/pull/210/files) changes

**Comment by sakluger** [comment] 2024-05-03 15:41
I tagged @BartoszGrajdek in Slack to request his review.

**Comment by mvtglobally** [comment] 2024-05-06 19:55
Issue not reproducible during KI retests. (First week)

**Comment by BartoszGrajdek** [comment] 2024-05-07 09:33
Hi, sorry I was OOO I'll take a look at it today 👀

**Comment by sakluger** [comment] 2024-05-07 15:07
Thanks @BartoszGrajdek!

**Comment by BartoszGrajdek** [comment] 2024-05-08 10:43
The proposed solution seems fine as long as it doesn't break how diacritics work. 

We're planning to introduce a better long-term solution, but that's something we'll do later down the road once some of the bigger-size refactors are done.

**Comment by sobitneupane** [comment] 2024-05-08 14:35
Thanks @BartoszGrajdek 

[Proposal](https://github.com/Expensify/App/issues/40799#issuecomment-2075206243) from @charles-liang looks good.

🎀 👀 🎀 C+ reviewed

**Comment by sakluger** [comment] 2024-05-10 21:25
PR is being worked on here: https://github.com/Expensify/react-native-live-markdown/pull/343

**Comment by sakluger** [comment] 2024-05-16 21:50
@twisterdotcom assigning you while I'm OOO through May 31. The latest is that the PR is being worked on here: https://github.com/Expensify/react-native-live-markdown/pull/343.

**Comment by sobitneupane** [comment] 2024-05-27 07:43
The PR is being reviewed.

**Comment by blimpich** [comment] 2024-05-28 18:10
@charles-liang what is the status of the PR? Still coming along?

**Comment by blimpich** [comment] 2024-05-31 16:50
@sobitneupane any update since your [last comment](https://github.com/Expensify/react-native-live-markdown/pull/343#issuecomment-2136906740)? Have you had a chance to review the PR?

**Comment by sakluger** [comment] 2024-06-03 23:11
I'm back - thanks @twisterdotcom for watching, I'll unassign you now.

@sobitneupane what is the latest?

**Comment by BartoszGrajdek** [comment] 2024-06-05 09:26
Hi! I have a question regarding this issue - is this only happening on mWeb?

**Comment by sobitneupane** [comment] 2024-06-05 09:27
@BartoszGrajdek I could reproduce it only in mWeb/Chrome

**Comment by BartoszGrajdek** [comment] 2024-06-05 09:44
Good, I know that your problems are likely related to the composition event types. We're thinking about disabling the composition handling on mWeb due to multiple bugs that are related to it. Can you check if the bug is still appearing using [this version of the library](https://github.com/Expensify/react-native-live-markdown/pull/366)?

**Comment by sobitneupane** [comment] 2024-06-05 09:47
I am pretty sure [it](https://github.com/Expensify/react-native-live-markdown/pull/366) should solve the issue. I will let you know after testing it. 

cc: @charles-liang

**Comment by sobitneupane** [comment] 2024-06-06 07:28
I tested https://github.com/Expensify/react-native-live-markdown/pull/366 PR and the issue will not be reproducible with the changes introduced by the PR.

**Comment by sakluger** [comment] 2024-06-07 20:45
Added the hold, but leaving as daily since that PR was merged and we just need to wait for the app version to be bumped.

**Comment by sobitneupane** [comment] 2024-06-14 07:05
> are we good to retest yet? Or do we still need to wait for the version of RNLM to be bumped?

I am no longer reproduce the issue in staging.

**Comment by sakluger** [comment] 2024-06-14 17:28
Nice! I will go ahead and close. I don't think any payment is due here, but please bring up in Slack if you disagree.

**Closed by sakluger** 2024-06-14 17:28 UTC
Labels: Reviewing, External, Daily, Bug
