### ISSUE TITLE
[$250] Android/IOS - Chat - App is crashed after tap on avatar for non-existing account 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9182] opened 2022-05-26 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app
2. Log in with any account
3. Select Search
4. Type any non-existing account 
5. Tap on Avatar for non-existing account 

## Expected Result:
App is not crashed after tap on avatar for non-existing account 

## Actual Result:
App is crashed after tap on avatar for non-existing account 

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.1.67.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/170509814-78bbcca8-473c-4916-8111-380425cf1963.mp4

https://user-images.githubusercontent.com/93399543/170509821-d80591c9-6de2-4175-8f2f-e99b10bad8dd.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** @adeel0202 Applause - Internal Team
 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1649374016010969

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by danieldoglas** [comment] 2022-05-26 19:08
Confirmed it is a bug and it's not on API.

**Comment by bfitzexpensify** [comment] 2022-05-27 00:51
Upwork job [here](https://www.upwork.com/jobs/~017aa6057e39108206)

**Comment by imran-ranglerz** [comment] 2022-05-27 01:10
we can handle this exception by using ? mark . as you say the account is not exist so the code surly pick the data and it did not find data so we can use ? mark.
if we did not have data of non existing account we will not face crash any more with ? mark

**Comment by adeel0202** [comment] 2022-05-27 06:07
I reported this bug 2 months ago but its ticket wasn't created. The thread is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1649374016010969).

**Comment by mollfpr** [comment] 2022-05-27 11:48
## Proposal

### Why?
The error showing up because there's no `personalDetails` data with the report id from `DetailsPage` component. `personalDetails` is come from Onyx, it needs to be fetched first and it fetches from `ReportActionsView` loaded.
https://github.com/Expensify/App/blob/3e52b9a549add24c84670fd7db46836db5a8025b/src/pages/home/report/ReportActionsView.js#L130-L132

The problem is there's a different time between Web and iOS/Android when loading the `report` data. I attach a screenshot of the different `report` data showing up on `ReportScreen` component and `ReportActionsView` component.
`ReportActionsView${this.props.report.reportID}` this value is show on `componentDidMount` and `ReportScreen${this.props.report.reportID}` is show inside `render()` function.

On Web, the `report` data is loaded after `ReportActionsView` component so it will fetch the `personalDetails` data with `Report.fetchChatReportsByIDs([this.props.reportID], true);`.

<img width="604" alt="Screen Shot 2022-05-27 at 18 23 10" src="https://user-images.githubusercontent.com/25520267/170691739-74ab4f35-6e40-489b-bb31-e4ff1bc1a4e7.png">

On the iOS/Android, the `report` data come in first before the `ReportActionsView` component is loaded. So it will not fetch the `personalDetails` data cause the condition is not `true` `if (!this.props.report.reportID)`.

<img width="321" alt="Screen Shot 2022-05-27 at 18 22 17" src="https://user-images.githubusercontent.com/25520267/170691747-e5350bf8-5e8b-4367-b8b4-c6b10c5b6231.png">

---

### How?
So we need to fetch the `personalDetails` data for the report id to be able to show the user detail data. https://github.com/Expensify/App/blob/3e52b9a549add24c84670fd7db46836db5a8025b/src/pages/home/report/ReportActionsView.js#L130-L132
We can extend the condition to check if the `personalDetails` data is provided or not to run the `Report.fetchChatReportsByIDs` function.
```js
        if (!this.props.report.reportID || !this.props.personalDetails[this.props.report.reportID]) {
            Report.fetchChatReportsByIDs([this.props.reportID], true);
        }
```

---

### Result


https://user-images.githubusercontent.com/25520267/170693307-9da18a05-9412-489e-b834-de1b418e0239.mov


https://user-images.githubusercontent.com/25520267/170693335-4ac9bd89-dec0-423b-a376-d629d40583bf.mov

**Comment by dhruv-silicon** [comment] 2022-05-30 12:24
We have checked the source code and tried to run the app.

We have identified that the non-existing account, it is not able to get the below example data:

`{"avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_8.png", "avatarHighResolution": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_8.png", "displayName": "sd@yopmail.com", "firstName": "", "lastName": "", "login": "sd@yopmail.com", "payPalMeAddress": "", "phoneNumber": "", "pronouns": "", "timezone": {"automatic": true, "selected": "America/Los_Angeles"}}`

That data you are getting from the DetailsPage.js file:

```
const details = props.personalDetails[props.route.params.login];
const isSMSLogin = Str.isSMSLogin(details.login);
const shouldShowLocalTime = !ReportUtils.hasExpensifyEmails([details.login]);
let pronouns = details.pronouns;
```

Also, we are facing this issue for the one time only, for the second time onwards, we are not getting any crashes.

Thanks & Regards.

https://user-images.githubusercontent.com/70027845/170991647-43586077-6dee-4ee6-9030-b00cd4d9e557.mov

**Comment by mananjadhav** [comment] 2022-06-02 21:09
Went through the proposals @aldo-expensify.

@mollfpr's proposal looks good to go ahead. 

@imran-ranglerz Adding `?` might not make sense as it would still not load the data. The goal is not to just avoid the crash but also to ensure the UX is consistent. @dhruv-silicon Agreed, and if you see that's precisely what @mollfpr pointed out. Once we have the data, then the next run will work just fine.

🎀 👀 🎀
C+ reviewed

**Comment by thesahindia** [comment] 2022-06-05 09:02
I think it's a dupe of https://github.com/Expensify/App/issues/8545
cc: @aldo-expensify @mananjadhav

**Comment by aldo-expensify** [comment] 2022-06-07 03:26
> Went through the proposals @aldo-expensify.

Thanks @mananjadhav 

> I think it's a dupe of https://github.com/Expensify/App/issues/8545

@thesahindia they look similar indeed, I'll have a look

**Comment by aldo-expensify** [comment] 2022-06-07 04:35
I'm failing to reproduce https://github.com/Expensify/App/issues/8545 locally, but I can reproduce this one and @mollfpr indeed seems to fix it.

I understand that the problem happens here because we have two (or more?) chained API calls:
1. `CreateChatReport` to create the chat
2. `PersonalDetails_GetForEmails` to get the personal details

You can reproduce this also in web if you quickly click the avatar before `PersonalDetails_GetForEmails` is resolved.

I'm thinking that [this same reasoning](https://github.com/Expensify/App/issues/8545#issuecomment-1145195642) may apply to this case. If `CreateChatReport` returned the personal details, we wouldn't need to chain more API calls, and I think this is what we are aiming for. Sounds correct @marcaaron ?

**Comment by aldo-expensify** [comment] 2022-06-09 22:16
@kbecciv it is the same problem.

I retested the proposed solution and added a `sleep(10)` in the PHP API code to make it easier to reproduce. The proposed solution doesn't fix the problem if the request `PersonalDetails_GetForEmails` takes too long. The same thing happens for existing and non-existing accounts.

**Comment by aldo-expensify** [comment] 2022-06-09 22:20
@mollfpr would this commit https://github.com/Expensify/App/commit/dbd8656b8ae33597d4afe6bd0fd874a344b4aa4a represent the changes of your proposed solution?

**Comment by aldo-expensify** [comment] 2022-06-09 22:42
Taking this internally as the proposed solution doesn't work well, and I think a better approach is to just show a loading indicator while the personal details are not available:

PR up: https://github.com/Expensify/App/pull/9385

I'm changing this to `Daily` because it crashes the app and it doesn't look too hard for it to happen.

**Comment by aldo-expensify** [comment] 2022-06-10 02:25
After digging more and testing in Android, I realized that what I was proposing [here](https://github.com/Expensify/App/pull/9385/commits/07e0997471145662bc0302d38e88e3f108128f2a) (just adding a spinner) doesn't fix it for Android/IOS.

There are two different problems that end up with the same crash. I mistakenly though they were the same.

- **Problem 1** (this GH issue): only happens in Android/IOS and is not related to tapping fast on the avatar. It happens **always** with accounts that doesn't exist.
- **Problem 2** ([here](https://github.com/Expensify/App/issues/9182#issuecomment-1151157054)): the app crashes if you tap too fast in the other users avatar, before the request `PersonalDetails_GetForEmails` finishes.

@mollfpr [proposed solution](https://github.com/Expensify/App/issues/9182#issuecomment-1139544946) indeed fixes the **Problem 1**, but the crash can still happen if you click the avatar fast enough before the request `PersonalDetails_GetForEmails` finishes.

On the other hand, what I was proposing (just add a spinner) solves **Problem 2**. My fix without @mollfpr solution causes the spinner to appear and spin forever in Android/IOS.

Having said that, I'll put everything together in this PR: https://github.com/Expensify/App/pull/9385, and @mollfpr should still be compensated because we are using his solution.

**Comment by aldo-expensify** [comment] 2022-06-22 19:44
Melvin, PR is in review.

**Comment by bfitzexpensify** [comment] 2022-06-27 12:33
Not overdue, in review

**Comment by aldo-expensify** [comment] 2022-07-06 22:07
No overdue, the [PR](https://github.com/Expensify/App/pull/9385) was merged, but has not been deployed yet.

**Comment by mvtglobally** [comment] 2022-07-12 04:36
Issue not reproducible during KI retests. (First week)

**Comment by aldo-expensify** [comment] 2022-07-18 19:55
No overdue. The PR has been deployed to production

**Comment by mvtglobally** [comment] 2022-07-19 03:25
Issue not reproducible during KI retests. (Second week)

**Comment by bfitzexpensify** [comment] 2022-07-20 19:20
OK, reposting the Upwork job [here](https://www.upwork.com/jobs/~0146a44b345763bccc), priced at $250 for the following contributors:

@adeel0202 (reporting)
@mollfpr (proposal was used in internal solution)
@mananjadhav (C+ review of proposal) 

Please apply and I will pay out once that's done - thanks!

**Comment by bfitzexpensify** [comment] 2022-07-22 14:53
All contracts paid out and ended - thanks for the work here everyone!

**Closed by bfitzexpensify** 2022-07-22 14:53 UTC
Labels: Reviewing, Exported, Engineering, Daily, Improvement, Internal
