### ISSUE TITLE
Chat - New chat isn't showing in the LHN nor in the search

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38367] opened 2024-03-15 02:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** applause internal team
**Slack conversation:**

## Action Performed:
1. Log in with a new Gmail account
2. Log in with the same account on a secondary device
3. On a secondary device, start a chat with an existing member
4. On the main device, navigate to the LHN and open the search
## Expected Result:
The chat should be available.

## Actual Result:
New chat started from a secondary device isn't showing in the LHN nor in the search. It only appears if you reinstall the app.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/a33b383d-c7a5-4462-b8a8-3edd952e5ab6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Beamanator** [comment] 2024-03-15 09:33
@robertjchen just checking, why was this NAB? Was it not reproducible in latest staging?

**Comment by Beamanator** [comment] 2024-03-15 09:55
I mentioned [here](https://expensify.slack.com/archives/C03TQ48KC/p1710495287385139) that i couldn't reproduce on latest staging so i think we're good to call this NAB 👍

**Comment by lschurr** [comment] 2024-03-18 18:28
Anything needed from BZ on this one?

**Comment by robertjchen** [comment] 2024-03-19 05:49
Nope, I think we can close this one out 👍

**Closed by robertjchen** 2024-03-19 05:49 UTC
Labels: Engineering, Weekly, Bug
