### ISSUE TITLE
[HOLD for payment 2023-07-05] [$1000] Web - Chat - Mention list doesn't display when enter special key: '_-+=|\;`~ before:

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20401] opened 2023-06-07 18:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Enter special key and @he (ex: _@he or `@he or ~@he)

## Expected Result:
The mention suggestion display

## Actual Result:
The mention suggestion doesn't display

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24.4

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-05-31 at 17 31 14 (1)](https://github.com/Expensify/App/assets/93399543/9b60effc-e9c3-4628-9b2e-ea3a44ac9096)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dukenv0307

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685529049518369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018585a2ed09409031</li>
        <li>Upwork Job ID: 1666822250965151744</li>
        <li>Last Price Increase: 2023-06-22</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2023-06-07 18:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
### What is the root cause of that problem?
In this PR: https://github.com/Expensify/App/pull/19004 we don’t add some special keys ’_-=|\;`~  in the SPECIAL_CHAR_OR_EMOJI and MENTION_REPLACER regex
### What changes do you think we should make in order to solve the problem?
Add _-=|\;`~ key to both SPECIAL_CHAR_OR_EMOJI and MENTION_REPLACER regex (don’t add + key because this key maybe exist in email)
### What alternative solutions did you explore? (Optional)

**Comment by sonialiap** [comment] 2023-06-08 14:59
Reproducible 👍

**Comment by sonialiap** [comment] 2023-06-12 12:09
@abdulrahuman5196 we have a couple of proposals for this one already, have you had a chance to review them. Do either of them look good to start working on a solution?

**Comment by abdulrahuman5196** [comment] 2023-06-12 13:52
yes will do today

**Comment by abdulrahuman5196** [comment] 2023-06-14 20:16
@PauloGasparSv @sonialiap Ping on the above

**Comment by PauloGasparSv** [comment] 2023-06-19 14:30
Oh, I just realized that @sonialiap is OOO until EOW

IMO **this doesn't really need to be discussed further** and we should just **Do Nothing** because there is no real reason for the expected results.

**Comment by abdulrahuman5196** [comment] 2023-06-19 15:11
@PauloGasparSv  I agree on this. Should we check with someone/slack? Or go ahead and close this out as a feature request?

**Comment by sonialiap** [comment] 2023-06-20 15:48
Out of curiosity, tested on Whatsapp. Mentions list pops up if you type `@`. I tested in a group chat with people, let's call them `@friendOne` and `@friendTwo`. So symbol followed by @, ex: `~@`

<img width="433" alt="image" src="https://github.com/Expensify/App/assets/17131195/bf79ba49-4155-4c3d-bc19-48366b488922">

Header | Whatsapp | Expensify
-- | -- | --
_ | no | no
| - | yes | no
| + | yes | no
= | yes | no
\| | yes | no
\ | yes | no
; | yes | no
` | yes | no
~ | yes | no
@ | no | no

**Comment by sonialiap** [comment] 2023-06-20 16:05
When you enter the special character followed by @ mentions don't come up, however, if you enter the user's full email and send the message, the mention works.

Since the mention works, I think the list should come up while you're typing. Otherwise it's missleading. I may think that because the mention list doesn't come up when I type `+@sonia@expensifail.com` the person won't be tagged when I send the message, but they are. 

I would change the behavior to show the mention list for the special characters 

<img width="357" alt="image" src="https://github.com/Expensify/App/assets/17131195/b93aec86-9a04-49a5-a8ea-5c566894af48">

**Comment by PauloGasparSv** [comment] 2023-06-21 22:59
> @PauloGasparSv I agree with the new concern by @sonialiap here https://github.com/Expensify/App/issues/20401#issuecomment-1599089991

I also agree, great catch @sonialiap!

> I think we can support the characters similar to whatsapp mentioned by @sonialiap here https://github.com/Expensify/App/issues/20401#issuecomment-1599057145 actually. What are your thoughts @PauloGasparSv

Makes sense, I think we are closer to how WhatsApp works than Slack.
Since we also support `_` (as seen in [Sonia's test](https://github.com/Expensify/App/issues/20401#issuecomment-1599089991)) let's include it too.

**Comment by PauloGasparSv** [comment] 2023-06-22 13:43
> 1. Should we add ' character to the above list

Was about to say yes but after searching a bit let's not add it! I'll explain better in the next item!

> 2. If we allow mention after + character. Because the + character could appear in some emails like dukenv0307+12@gmail.com, It maybe makes a complicated change in the code base to work well

Oh yes that makes sense, we'll also have that problem for `_` and any other special character that is accepted in a valid email.


I did a quick search and it looks like email addresses allow a bunch of special characters (`!#$%&'*+-/=?^_{|}~` and \`)
To avoid reworking this logic (I don't think this is worth the refactoring) how about we choose a smaller set of special characters to allow like: 

`,` `/` `\` `?` `"` `{` `}` `[` `]` `(` `)` `&` `^` `%` `$` `#` `<` `>` `!` `*` `=` \` `;`

We already accept [some of these](https://github.com/Expensify/App/blob/main/src/CONST.js#L1154) including some that are allowed in emails like `!` but I really that's ok because these special characters are not that common and the worst thing that can happen is someone failing to mention someone which is not a big deal IMO.

I think we should not add/accept these special characters because they are allowed in emails and pretty commong:
`_` `+` `-` `@` `~` `|` 


What do you think @dukenv0307 @abdulrahuman5196 @sonialiap ?

**Comment by PauloGasparSv** [comment] 2023-06-22 14:11
>  @PauloGasparSv So will we add/accept these characters \ ' ; `

Yes to:  `\` `;` \`
No to: `'` 

So the list of accepted should be the following IMO:
`,` `/` `\` `?` `"` `{` `}` `[` `]` `(` `)` `&` `^` `%` `$` `#` `<` `>` `!` `*` `=` \` `;`

And let's not add these characters there were discussed here at some point:
`_` `+` `-` `@` `~` `|` `'`

**Comment by abdulrahuman5196** [comment] 2023-06-22 18:25
@PauloGasparSv  I agree we should add a lower subset of character which don't clash with existing experiences. Even if people want to add more we can do it in future if required.

**Comment by abdulrahuman5196** [comment] 2023-06-23 10:53
@dukenv0307 's proposal here https://github.com/Expensify/App/issues/20401#issuecomment-1581863638 looks good and works well.

We can add characters based on @PauloGasparSv 's comment here https://github.com/Expensify/App/issues/20401#issuecomment-1602713834

🎀👀🎀
C+ Reviewed

cc: @PauloGasparSv

**Comment by PauloGasparSv** [comment] 2023-06-23 16:13
Nice, thks for all the help on defining the scope of this change @abdulrahuman5196 and @dukenv0307! 

Assigning @dukenv0307 here

**Comment by abdulrahuman5196** [comment] 2023-06-29 10:41
BZ checklist

>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. The characters in discussion was not previously added.

>Determine if we should create a regression test for this bug.
If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

No. This is a minor case and wouldn't we beneficial to add a regression test.

**Comment by sonialiap** [comment] 2023-07-05 14:07
@dukenv0307 offer sent for report + fix (+bonus)
@abdulrahuman5196 offer sent for review (+bonus)

**Comment by abdulrahuman5196** [comment] 2023-07-05 15:34
@sonialiap accepted the offer

**Closed** 2023-07-06 10:40 UTC
Labels: External, Daily, Awaiting Payment, Bug
