### ISSUE TITLE
[$250]  Task – Task creator avatar appears briefly on top of chat when create task with non-existing

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#47151] opened 2024-08-09 10:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4836876
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Click on FAB and Assign task
4. Enter title
5. Click on Assignee and select non-existing user
6. Click on Confirm the task

## Expected Result:
Task assignee avatar present on the top of the chat

## Actual Result:
Task creator avatar appears briefly on the top of the chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/212c8fde-cbf0-46cd-a5bf-381897c72441

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016ea999111b3bbb3c</li>
        <li>Upwork Job ID: 1822945464965222378</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by izarutskaya** [comment] 2024-08-09 10:42
We think this issue might be related to the  #vip-vsb

**Comment by bfitzexpensify** [comment] 2024-08-12 10:37
Minor bug. Will send external to see if it's easy to resolve, but I think this is the type of thing we could also close.

**Comment by jacobkim9881** [comment] 2024-08-15 01:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When assigning a task to a non-existent user, the user's avatar briefly flicks.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/1eef411e1d9e85145f160ee5610bb9cc9a8c04d7/src/libs/ReportUtils.ts#L2163-L2171

Because at the above function, there are 2 icons for the non-existent user while creating a chat report. 2 icons are created because the newly added account has an account ID as optimistic one and the other ID from BE API. Till the optimistic account ID is deleted, there are 3 accounts(admin, optimistic ID, the other ID from BE API). After the optimistic account ID deleted, `getIcons` function executed at this condition below,

https://github.com/Expensify/App/blob/1eef411e1d9e85145f160ee5610bb9cc9a8c04d7/src/libs/ReportUtils.ts#L2343-L2352

### What changes do you think we should make in order to solve the problem?
We can keep the icon from flickering by filtering the optimistic ID while creating a new chat report. The optimistic ID(1) and the other ID(2) from BE API have the same name,

```js
0 {id: 18064077, source: "https://d1wpcgnaa73g0y.cloudfront.net/ADMIN.jpeg", type: "avatar", name: "admin", fallbackIcon: ""}
1 {id: 18139679, source: "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_24.png", type: "avatar", name: "same@abc.com", fallbackIcon: ""}
2 {id: 1457118634, source: function, type: "avatar", name: "same@abc.com", fallbackIcon: ""}
```

We can add a condition at `getIcons` function and return icons for members,


```js
if (report.lastActionType === 'CREATED' && hasSamename(report)) {

  return getIconsForParticipants();
}

```

Then only a member icon will be got when assigning a task for creating a new chat with the member.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by c3024** [comment] 2024-08-15 12:52
@jacobkim9881 

Backend send the report participants correctly. So, I think we should check why the merging of the sent participants into existing report participants duly removing the optimistic participant details is not happening correctly.

**Comment by c3024** [comment] 2024-08-20 11:33
>2 ID(both for one member ID) are merged into one report

Then in my opinion, this should be fixed.

Merging incorrectly and then filtering by checking if names are same is a workaround and we should avoid it.

**Comment by jacobkim9881** [comment] 2024-08-20 14:43
> 2 ID(both for one member ID) are merged into one report
This process is merging of Onyx from BE response. Then the merging should be able to edited to filter by checking ID.

**Comment by c3024** [comment] 2024-08-20 14:59
Then could you check where this should be fixed in `react-native-onyx`?

**Comment by c3024** [comment] 2024-08-21 07:55
Given that it is recommended to update the backend response and `successData` successively, one after the other, as shown [here](https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/OnyxUpdates.ts#L34-L43), we cannot avoid the brief, intermittent presence of both optimistic and non-optimistic (backend returned) IDs among the participants.

Since we already use a pattern of omitting the optimistic ID [here](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L2046-L2054), as shown by @dominictb, we can apply the same approach here.

The RCA and fix suggested [here](https://github.com/Expensify/App/issues/47151#issuecomment-2299259101) by @dominictb look good to me!

🎀 👀 🎀 C+ Reviewed

**Comment by marcaaron** [comment] 2024-08-21 19:09
>However, this is 2 onyx operations so there's a (small) gap that we could see both the optimistic account ID and non-optimistic account ID exist in the report.participants

Hmm this sounds like something we could maybe fix by changing the behavior of how these updates are applied? Like it sounds like you are saying because we briefly set the personal details to 'null' and then apply the correct ones after it leads to this problem.

But the personal details is just one object - so if we applied these updates at the same time the problem would not happen? Or no?

**Comment by marcaaron** [comment] 2024-08-21 19:11
The solution we applied there looks like a hack to me kind of. Also what will be shown instead? Please post a video of the UX so we can see what this flow looks like with the change applied. Is there some empty space where an avatar should be?

**Comment by c3024** [comment] 2024-08-22 02:13
> We briefly set the personal details to 'null' and then apply the correct ones, leading to this problem.

Actually, it's the other way around. Here's the flow:

1. A task is created, and the `participants` field in the report contains the optimistic assignee ID and the current user ID.
2. The backend returns a response with the report containing the `participants` field with the non-optimistic (real) assignee ID and the current user ID. This is then merged into Onyx.

   https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/OnyxUpdates.ts#L37

   Now, the `participants` field has three participants. The logic here:

   https://github.com/Expensify/App/blob/ddec3e733a677324dd7885afade5907c16a402d2/src/libs/ReportUtils.ts#L2351-L2359

   checks if it's a one-on-one chat by excluding the current user ID and checking the number of participants in the report:

   https://github.com/Expensify/App/blob/ddec3e733a677324dd7885afade5907c16a402d2/src/libs/ReportUtils.ts#L1599-L1613

   When there are three participants in the report, this check fails. As a result, the current user ID is not excluded, and all three avatars are briefly shown.
3. Then, the `successData`:

   https://github.com/Expensify/App/blob/ddec3e733a677324dd7885afade5907c16a402d2/src/libs/ReportUtils.ts#L6780

   is merged into Onyx:

   https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/OnyxUpdates.ts#L38-L42

   This removes the optimistic assignee ID, and only one avatar is shown correctly because the one-on-one chat check now succeeds.

> This sounds better IMO, but might not be valuable enough to spend time on right now.

I agree. I think, generally and not just in this specific case, that unless the `successData` is a large object that would be prohibitive to send over the network, it might be better to merge the `successData` on the backend and include it in the response, where practicable.

@dominictb correct me if I am wrong.

**Comment by marcaaron** [comment] 2024-08-22 19:48
Ok, got it, thanks for the explanation @c3024. 

It still sounds like a possible "root cause" is that we are not merging together these two updates, but merging in the server data first then the `successData` at some delay? If we were to say, collapse the server data + `successData` into one single update first then this "flash" of inaccurate stuff would not happen?

>it might be better to merge the successData on the backend and include it in the response, where practicable

Hmm I think perhaps the server should just be responsible for the part of `successData` that might cause a problem like this - but not all the `successData` in a general sense since issues like this are rare.

Given how our system works and applies updates the current behavior makes sense. There is no differentiation between optimistic and actual data. But exposing that detail to the frontend might not be the answer to me. So, I'd think we'd either:

1. Have the client pass the `optimisticAccountID` and then have the server set it to `null` in the same update (and really anytime a "real" accountID is created we should also be doing this in the server)

OR

2. Collapse the updates together and merge once so there isn't a "flash" of inaccurate stuff.

OR 

3. A longer term fix where `accountID` can be client generated.

Honestly, since everything ends up looking how it should look I'm not sure if we should be doing the proposed solution. Going to ask what the internal team thinks about this one.

**Comment by kaushiktd** [comment] 2024-08-23 04:19
@marcaaron, when I pulled the code, the steps you mentioned didn’t work as expected. The assigned task isn't showing up in the top menu.
[screen-capture.webm](https://github.com/user-attachments/assets/00949c8b-7942-47bc-a2f0-84498b32ef86)

**Comment by c3024** [comment] 2024-08-23 07:18
@marcaaron 

> It still sounds like a possible "root cause" is that we are not merging together these two updates, but merging in the server data first, then the `successData` with some delay?

Yes, that is the root cause. As I mentioned [here](https://github.com/Expensify/App/issues/47151#issuecomment-2301389227):

> Given that it is recommended to update the backend response and `successData` successively, one after the other, as shown [here](https://github.com/Expensify/App/blob/685bb4c7bbaa2ef332896de5cace193edb9c6a51/src/libs/actions/OnyxUpdates.ts#L34-L43),

the comment suggests merging response data and `successData` successively. I did not dig deeper into why it is required. I assumed it must be something important and felt that the frontend hack was acceptable since it had already been used [elsewhere](https://github.com/Expensify/App/blob/main/src/libs/ReportUtils.ts#L2046-L2054).

All three solutions you suggested are indeed more ideal than filtering the optimistic ID on the frontend.

> Honestly, since everything ends up looking how it should, I'm not sure if we should be implementing the proposed solution.

Yes, the three avatars appear for a very brief time, and sometimes it happens so quickly that it’s not perceptible at all. We can leave this as it is and close this issue. Perhaps this brainstorming will be useful if we encounter a situation where the gap between updates actually causes a significant UI/UX issue.

**Comment by c3024** [comment] 2024-08-23 11:29
>if we apply successData and serverData simultaneously , the optimistic data clean up could happen first before the BE-returned data kick in, and that could lead to situation in the participant list:

>The optimistic participant record disappears
Then after that, BE-returned participant record appears.

I did not mean that we can apply them simultaneously. I understand that we should have the backend response before doing anything with `successData`. I meant that I have not checked the difficulties of merging the (successful) response data and success data together first and then merging this merged object into Onyx.

**Comment by jacobkim9881** [comment] 2024-08-23 13:38
> Then could you check where this should be fixed in react-native-onyx?
@c3024 Let me know you if I found a solution.

**Comment by jacobkim9881** [comment] 2024-08-23 13:41
Exactly the report having the issuable merging was made just after "GetMissingOnyxMessages" request. Here is the process when after creating a task:

1. Optimistic ID on the optimistic report as there is other report having real ID from BE
2. Log: 
```js
[Debug] [info] [OnyxUpdateManager] Applying update type: https with lastUpdateID: 1295849174 - {"command":"GetMissingOnyxMessages"} – ""
[Debug] [info] [Onyx] merge called for key: OnyxUpdatesLastUpdateIDAppliedToClient hasChanged: true - "" – ""
[Debug] [info] [Onyx] set called for key: nvp_quickActionGlobalCreate properties: action,chatReportID,isFirstQuickAction,targetAccountID hasChanged: true - "" – ""
[Debug] [info] [Onyx] set called for key: userMetadata properties: accountID,email,freeTrial,planType,role,tryNewDotDismissed hasChanged: false - "" – ""
[Debug] [info] [Onyx] merge called for key: personalDetailsList properties: 17907433,18187017 hasChanged: true - "" – ""
```

3. The report has optimistic ID and real ID from BE.

**Comment by marcaaron** [comment] 2024-08-23 19:01
Can someone maybe explain why there is a delay for some users and other times not? This seems to point even further to a problem at some lower level with Onyx. My expectation is that even if we are applying the server data followed by the `successData` that this would not be a noticeable event. 

Anyways, I think this pretty low priority. Maybe we should just close it out @bfitzexpensify ?

**Comment by marcaaron** [comment] 2024-08-23 19:02
Actually I'm going to close and if there is enough compelling evidence to point to we can reopen.

**Closed by marcaaron** 2024-08-23 19:02 UTC
Labels: External, Daily, Help Wanted, Bug
