### ISSUE TITLE
[$250] Workspace chats are not pinned for migrated admins

### ISSUE THREAD

**Issue by flaviadefaria** [Expensify/App#53794] opened 2024-12-09 20:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** NA
**Reproducible in staging?:**  Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** NA
**If this was caught during regression testing, add the test name, ID and link from TestRail:** NA
**Email or phone of affected tester (no customers):** flavia.usertesting+migrationuser1@gmail.com
**Logs:** NA
**Expensify/Expensify Issue URL:** NA
**Issue reported by:** @flaviadefaria 
**Slack conversation** (hyperlinked to channel name): https://expensify.slack.com/archives/C07NMDKEFMH/p1733515001305989

## Action Performed:
1. Create 2 control workspaces in Classic
2. Migrate the user
3. Sign in after the user has been migrated

## Expected Result:
The migrated user should have both workspaces pinned

## Actual Result:
No workspace is pinned

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/bc677321-ec45-47b8-9ee4-e7d17bf98d43">

## Workaround:
NA

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866225851939728623</li>
        <li>Upwork Job ID: 1866225851939728623</li>
        <li>Last Price Increase: 2024-12-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @MonilBhavsar</details>

**Comment by Shahidullah-Muffakir** [comment] 2024-12-09 20:58
Same as https://github.com/Expensify/App/issues/53788

**Comment by flaviadefaria** [comment] 2024-12-09 21:02
@Shahidullah-Muffakir the issue you linked doesn't have the Concierge chat pinned this one refers to the workspace chats, so I'm not sure they are the same unless the root cause is the same.

**Comment by Shahidullah-Muffakir** [comment] 2024-12-09 21:04
> @Shahidullah-Muffakir the issue you linked doesn't have the Concierge chat pinned this one refers to the workspace chats, so I'm not sure they are the same unless the root cause is the same.

Yes, I believe the root cause is the same

**Comment by flaviadefaria** [comment] 2024-12-09 21:06
Got it. I'll let other chime in!

**Comment by ijmalik** [comment] 2024-12-10 10:25
Hi @flaviadefaria,

I am currently unable to reproduce the exact issue you described. To help us better understand and resolve it, could you please create a detailed video demonstrating the entire workflow? Specifically, include the process of creating two control workspaces in Classic mode.

**Comment by flaviadefaria** [comment] 2024-12-10 15:16
Hey @ijmalik I made this an internal issue as it will be easier to reproduce given it might be related to the migration we've ran.

**Comment by MonilBhavsar** [comment] 2024-12-11 10:31
Looks like this is something we didn't implement and not a bug. Working on PR

**Comment by MonilBhavsar** [comment] 2024-12-11 14:13
I followed these steps and noticed we don't even create workspace chats, if we don't have any reports on oldDot

1. Create 2 control workspaces in Classic
2. Migrate the user
3. Sign in after the user has been migrated

I think we also need to fix this case @flaviadefaria

**Comment by MonilBhavsar** [comment] 2024-12-11 15:02
I have got a draft up. Moved this^ conversation to thread https://expensify.slack.com/archives/C07NMDKEFMH/p1733929300535859?thread_ts=1733515001.305989&cid=C07NMDKEFMH

**Comment by Christinadobrzyn** [comment] 2024-12-11 17:15
Just a heads up that I'm going to be ooo Dec 12 - 13th. Back on Monday 16th. I'm not going to assign this to a BZ teammate but if anything is urgent, please reach out to the team for a volunteer.

**Comment by MonilBhavsar** [comment] 2024-12-12 13:58
Submitted PR for review

**Comment by Christinadobrzyn** [comment] 2024-12-16 15:50
Monitoring PR - https://github.com/Expensify/Auth/pull/13505

**Comment by Christinadobrzyn** [comment] 2024-12-16 15:52
looks like the PR is merged - I'm not quite sure how to test this - @MonilBhavsar would you be able to test?

**Comment by alitoshmatov** [comment] 2024-12-16 18:37
Unnassigning since I was not involved in PR review

**Comment by Christinadobrzyn** [comment] 2024-12-17 21:27
Looks like PR is in production so I think we can close this! @MonilBhavsar let me know if I'm missing something!

**Closed by Christinadobrzyn** 2024-12-17 21:27 UTC
Labels: Reviewing, Daily, Internal, Bug
