### ISSUE TITLE
Status - Inconsistent behavior when closing status RHP

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35729] opened 2024-02-02 21:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v.1.4-36.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User has a custom status.
1. Go to staging.new.expensify.com.
2. On home page, click on status icon on the user avatar.
3. Click outside the status RHP.
4. Return to main chat.
5. Click on status icon.
6. Click back button on the RHP.

## Expected Result:
There should be consistent behavior when closing status RHP when clicking outside the RHP and clicking back button on RHP.

## Actual Result:
In Step 6, when clicking back button on the status RHP, it closes both profile page and also status RHP.
On Android app, the back button on status page redirects user to the home page, while the device back navigation on status page reveals the profile page underneath.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/29ab854d-92fe-43f8-bfcc-ece20ac0fc8e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-02-02 21:36
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-03 06:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the status page back button takes the user back to the report screen.

### What is the root cause of that problem?
If we press the overlay, it simply calls goBack which will close the status page.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/AppNavigator/Navigators/RightModalNavigator.tsx#L28-L34

But if we press the status page back button, it will pop all screens (shouldPopToTop is true)
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/settings/Profile/CustomStatus/StatusPage.js#L73
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/libs/Navigation/Navigation.ts#L177-L183

and only happens if we press the status icon.
https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/sidebar/AvatarWithOptionalStatus.js#L38-L39

### What changes do you think we should make in order to solve the problem?

I think the pop to top logic is not relevant anymore for status page after the navigation change because the setting page always open, so we can update the go back code in status page to simply call `goBack`.

**Comment by mountiny** [comment] 2024-02-05 11:55
Demoting this issue from deploy blocker, this was kinda known before the merge and related to goBack functionality.

@adamgrzybowski Could you please look into the proposal from @bernhardoj to see whether we should go with it or wait for the more generic goBack fix ? Thanks!

**Comment by hayata-suenaga** [comment] 2024-02-05 17:17
The general back issues are tracked in [this issue](https://github.com/Expensify/App/issues/35626)

**Comment by mountiny** [comment] 2024-02-08 18:21
Making this weekly given its part of a bigger scheme

**Comment by adamgrzybowski** [comment] 2024-02-09 11:19
Probably mentioned somewhere but it should be fixed by this [PR](https://github.com/Expensify/App/pull/36050)

**Comment by hayata-suenaga** [comment] 2024-03-04 19:07
> Probably mentioned somewhere but it should be fixed by this https://github.com/Expensify/App/pull/36050

https://github.com/Expensify/App/assets/98560306/cffda3ee-5538-4bf5-af9e-02a8cbc4f8f7

confirmed the issue was fixed on production. closing the issue

**Closed by hayata-suenaga** 2024-03-04 19:07 UTC
Labels: Reviewing, Engineering, Monthly
