### ISSUE TITLE
[$500] Address– Address is cut off on Personal details page when add Address line 2

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34670] opened 2024-01-17 21:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.26-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Home address page
2. Search for a UK address, e.g 158 Torquay Rd, Paignton, Devon
3. Select the suggested address under UK
4. Verify the fields get populated accordingly
5. Save the new address
6. Navigate back to Addresses page
7. Add value (ggggggggggggggggggggggggggggf) into Address line 2 and hit Save button

## Expected Result:
Address field on Personal details page should not be cut-off

## Actual Result:
Address is cut off on Personal details page when add Address line 2

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![Bug6345675_1705518638852!Capture2](https://github.com/Expensify/App/assets/78819774/1228b0e6-d88c-4dda-b595-c322bfc16eb1)

https://github.com/Expensify/App/assets/78819774/6ef50626-1c12-4b29-b02d-7a14749bb854

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164e2537cc6e5df1e</li>
        <li>Upwork Job ID: 1747725563329376256</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by ikevin127** [comment] 2024-01-17 21:08
# Proposal

## Please re-state the problem that we are trying to solve in this issue

Address is cut off on Personal details page when add Address line 2.

## What is the root cause of that problem?

This happens when address line 2 is a long string without spaces, since the `MenuItemWithTopDescription`'s component numberOfLinesTitle is 1 by default.

## What changes do you think we should make in order to solve the problem?

Change `MenuItemWithTopDescription`'s component numberOfLinesTitle to 2.

**Comment by aswin-s** [comment] 2024-01-17 22:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Address field in personal details page not taking available width

### What is the root cause of that problem?

The issue is similar to #25561. The MenuItem component has a flexShrink1 which causes the Address field to not take up the entire available width.

https://github.com/Expensify/App/blob/4b7b8f2480866200c64a8b614a1f485c0112aa11/src/components/MenuItem.tsx#L304



### What changes do you think we should make in order to solve the problem?


Fix is similar to what is done for the DOB filed in https://github.com/Expensify/App/pull/25593. Add `titleStyle={[styles.flex1]}` to `privatePersonalDetails.address` field in PersonalDetailsInitialsPage

https://github.com/Expensify/App/blob/4b7b8f2480866200c64a8b614a1f485c0112aa11/src/pages/settings/Profile/PersonalDetails/PersonalDetailsInitialPage.js#L93-L98

```tsx
<MenuItemWithTopDescription
    title={PersonalDetailsUtils.getFormattedAddress(props.privatePersonalDetails)}
    description={props.translate('privatePersonalDetails.address')}
    shouldShowRightIcon
    // Add title style
    titleStyle={[styles.flex1]}
    onPress={() => Navigation.navigate(ROUTES.SETTINGS_PERSONAL_DETAILS_ADDRESS)}
/>
```

**Result**

![Screenshot_1705529169](https://github.com/Expensify/App/assets/6880914/c3a23744-d116-4f33-9ba3-9969846fab76)

### What alternative solutions did you explore? (Optional)

None

**Comment by ikevin127** [comment] 2024-01-18 01:03
## Updated [proposal](https://github.com/Expensify/App/issues/34670#issuecomment-1896708746)
- added more details to the RCA and also added alternative solution w/ screenshot

**Comment by sakluger** [comment] 2024-01-23 23:17
I'm asking in Slack (https://expensify.slack.com/archives/C066HJM2CAZ/p1706051813981559) if we should prioritize fixing this bug, as it seems like it may be a rare edge case and doesn't impact users too badly.

**Comment by sobitneupane** [comment] 2024-01-24 02:18
I will be able to review the issue only in the weekend. Please re-assign the issue in case of urgency.

**Comment by sakluger** [comment] 2024-01-29 18:50
No response yet from the team, I asked again if we want to fix this bug. @sobitneupane I removed you for now, I can re-add a C+ depending on what the team decides.

**Comment by mvtglobally** [comment] 2024-01-30 04:58
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2024-01-30 16:57
The team agrees that this is a major edge case - I'm not sure if there would ever be a single-word entry that long on the second address line. Closing.

**Closed by sakluger** 2024-01-30 16:57 UTC
Labels: External, Daily, Bug
