### ISSUE TITLE
Chat - Message sent offline change positions between each other once back online

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13310] opened 2022-12-03 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/12626

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Open any chat
3. Go offline
4. Input several multi-word messages
5. Go back online

## Expected Result:
Messages should stay at the same place

## Actual Result:
Message sent offline change positions between each other once back online

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platform:

Where is this issue occurring?

- Web
- Android
- mWeb

**Version Number:** 1.2.36.0

**Reproducible in staging?:** Yes 
 
**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/205449896-041475f1-748a-43d7-9a49-adca7648dbe1.mp4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment] 2022-12-06 00:51
Not convinced this is something we need to fix. As long as the app ends up in the state the user expects. cc @roryabraham because you started a similar conversation about this in Slack already (even though I'm pretty sure we have different opinions on this). Maybe we can HOLD this until there is a consensus.

**Comment by tienifr** [comment] 2022-12-06 07:49
# Proposal

## Problem

In https://github.com/Expensify/App/blob/36a009b899c58ffefb8ed034534761e73cc6a1d8/src/pages/home/report/ReportActionsView.js#L254

we're re-sorting the reports by `created`. Unfortunately, the `created` in optimistic data is different from that one on BE side => when user backs online the `created` changes the reports order.

## Solution

I think we should fix both on FE and BE sides.

https://github.com/Expensify/App/blob/36a009b899c58ffefb8ed034534761e73cc6a1d8/src/libs/actions/Report.js#L432-L440
I'll add `created` as the parameter and on BE side will use this instead of creating the new one

```diff
        file,
+        created: file? attachmentAction.created:reportCommentAction.created
    };

```

**Comment by zanyrenney** [comment] 2022-12-06 11:21
Will wait for @roryabraham input here about the prioritisation of fixing this after @marcaaron comment.

**Comment by roryabraham** [comment] 2022-12-06 20:15
I agree we need internal consensus here. The slack conversation is [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1669857400316029). I think the only consensus we've got so far is that:

- we can punt this and treat it like a new feature instead of a bug. So mark as `New Feature` and put on HOLD for WAQ for now.
- if we _do_ decide that we should fix this, we can use a batching solution that sends all optimistically created reportActions in a single request (probably with `ReconnectApp`)
- This needs to be an internal issue

Thanks for the proposal @tienifr, but we want to treat the database `created` time as the canonical one, because that more closely relates to the actual order in which messages were sent.

**Comment by zanyrenney** [comment] 2022-12-16 12:31
This is on hold, not overdue. @roryabraham as you've removed the bug label, I assume I should not be assigned to this anymore and when this is picked back up as a new feature, the engineer working on it will self-assign. please lmk!

**Comment by zanyrenney** [comment] 2022-12-19 16:37
https://expensify.slack.com/archives/C01SKUP7QR0/p1671467869541089

**Comment by zanyrenney** [comment] 2022-12-19 20:53
clearing my assignment out for this!

**Comment by roryabraham** [comment] 2023-01-18 01:08
This no longer needs to be on HOLD, but we still need to further discuss whether this is a new feature worth implementing.

**Comment by neil-marcellini** [comment] 2023-03-16 20:50
@roryabraham you fixed this recently correct? Would you please link the PR and close the issue?

**Comment by roryabraham** [comment] 2023-03-23 07:07
https://github.com/Expensify/App/pull/15942

Closing this out as a dupe of https://github.com/Expensify/App/issues/13250

**Closed by roryabraham** 2023-03-23 07:07 UTC
Labels: Monthly, Internal, Planning, NewFeature
