### ISSUE TITLE
VBA - Content is changing the color when tap on it in Additional information Page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9354] opened 2022-06-08 13:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Tap on avator - Settings - Preferences 
3. Unable the Staging Server toggle
4. Go to Workspace - Connect Bank account
5. Use credentials: user_good/pass_good
6. In Additional Information page tap on any content.

## Expected Result:
Content is not changing the color when tap on it in Additional information Page\

## Actual Result:
Content is changing the color when tap on it in Additional information Page

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.71.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/172629694-ca60701f-3efb-467d-bfb7-6dc18a2d4027.mp4

**Expensify/Expensify Issue URL:**
 
**Issue reported by:** Applause - Exploratory

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-06-10 15:59
Yes though this can be external I will fix it myself to get used to the codebase. Thanks

**Comment by techievivek** [comment] 2022-06-13 08:11
Not overdue looking into it today.

**Comment by techievivek** [comment] 2022-06-13 09:53
I did get the reason why it is changing the colour and that is because the checkbox is implemented [on top](https://github.com/Expensify/App/blob/6bac9af7294877114f8bf9532ff7b8c46146c90d/src/components/CheckboxWithLabel.js#L82) of `TouchableOpacity` component from the [react-native ](https://reactnative.dev/docs/touchableopacity) so one way to fix this is to use the property the `activeOpacity` and set it to `1` and that way it will not decrease the opacity or we can switch to `TouchableWithoutFeedback` component.

And this is the behaviour of the checkbox throughout our app so don't if we need to change this. Here is another example.

https://user-images.githubusercontent.com/35863227/173328134-f49ad6bc-bfb5-480a-b847-edfd25dab879.mp4

Lets tag @shawnborton and see what he has to say.

**Comment by shawnborton** [comment] 2022-06-13 12:39
Just curious @kbecciv was this a bug reported in the #expensify-open-source room? I'd love to catch up on the discussion around it. If not, we should bring these items into the room for discussion before moving forward with solutions in GitHub. 

That being said... I don't feel strongly about this one. I can see where given that this reuses TouchableOpacity, we'd just keep the current behavior as it is for consistency.

**Comment by techievivek** [comment] 2022-06-15 06:08
Started a conversation on [slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1655272356939959) please feel free to jump in.

**Comment by techievivek** [comment] 2022-06-15 13:51
Closing this as this is an expected behaviour of the CheckboxWithLabel component.

**Closed by techievivek** 2022-06-15 13:51 UTC
Labels: Reviewing, External, Engineering, Daily, Improvement
