### ISSUE TITLE
Wallet -  `Auth CreateFund returned an error` appears when adding debit card

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32126] opened 2023-11-28 14:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31133

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any Expensifail account
3. Go to Settings -> Wallet -> Add bank account -> Debit card
4. Fill form with correct data
5. Save the card data

## Expected Result:
The debit card is added without any errors

## Actual Result:
`Auth CreateFund returned an error` appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (29)](https://github.com/Expensify/App/assets/93399543/08495e1f-57bd-42d8-99f3-25f2794dd97c)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-11-28 14:27
Error in production 

![image (30)](https://github.com/Expensify/App/assets/93399543/f5425872-ee2a-4941-a085-a71af669d890)

**Comment by AndrewGable** [comment] 2023-11-28 19:22
Removing deploy blocker label as it's happening in production.

**Comment by srikarparsi** [comment] 2023-12-06 09:51
looked into the code, believe it's an error with stripe because of the status code, will make more progress tomorrow.

**Comment by srikarparsi** [comment] 2023-12-14 08:16
Had finals last week and this week but just finished them up. I'm OOO on Friday for graduation but will add this to my list of things to investigate tomorrow and will leave an update.

**Comment by srikarparsi** [comment] 2023-12-20 08:07
Still looking into this, it's a Stripe error but I'm not able to find what changes could be causing this. I'll probably ask for help if I can't find an explanation tomorrow.

**Comment by srikarparsi** [comment] 2023-12-26 23:55
Working limited hours because of Christmas/New Year, will leave an update towards the beginning of next week

**Comment by srikarparsi** [comment] 2024-01-03 06:48
Will take a look at this today

**Comment by srikarparsi** [comment] 2024-01-08 22:55
Looks like the same as this issue [here](https://github.com/Expensify/Expensify/issues/230476). Tested it out with the 4242 test Stripe card and I'm getting the "Auth CreateFund returned an error" but when I try it with an actual debit card, it works. I see a [PR](https://github.com/Expensify/Expensify/issues/237181) was created here to help Applause QA these flows without using an actual debit card. @marcochavezf, do you know if this issue is related to those changes?

**Comment by marcochavezf** [comment] 2024-01-09 01:05
Hmm the Bancorp sandbox token was updated a few weeks ago https://github.com/Expensify/Expensify/issues/296548#issuecomment-1810030541 and it should work but it's weird that we're getting this error, can you check the logs to see if there are more errors/messages to understand a bit more what's happening?

**Comment by srikarparsi** [comment] 2024-01-17 08:18
Ah got it! Will look into this tomorrow :)

**Comment by srikarparsi** [comment] 2024-01-31 03:09
Logs [here](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2284d2126999f6872f-ORD%22)+AND+timestamp:[2024-01-29T13:20:37.697Z+TO+2024-01-29T15:20:37.697Z]&index=logs_expensify-026510), investigating

**Comment by srikarparsi** [comment] 2024-02-07 06:12
Hey @marcochavezf! I'm not too familiar with these error messages but I just tested and checked the [logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%22851965be7c8db11b-ATL%22)+AND+timestamp:[2024-02-07T04:57:48.238Z+TO+2024-02-07T06:57:48.238Z]&index=logs_expensify-026680) and it seems like the token might've expired.

<img width="1358" alt="image" src="https://github.com/Expensify/App/assets/48188732/ad67d932-5be9-4d45-8a69-7e25741803ef">

If this is the case, should we just ask Bancorp for a new token?

**Comment by srikarparsi** [comment] 2024-02-14 06:05
Hey @marcochavezf! Friendly bump on the above question

**Comment by marcochavezf** [comment] 2024-02-14 19:16
Oh sorry to the missing ping. Yeah, we should ask them for a new token if it's expired. There should a GH created automatically every 3 months I think to request a new token. Let me find it

**Comment by marcochavezf** [comment] 2024-02-14 19:38
These are the issues to request a new token https://github.com/Expensify/Expensify/issues?q=is%3Aissue+%22Rotate+Bancorp+RFT+API+Sandbox+token%22+, and this is the last one https://github.com/Expensify/Expensify/issues/296548. Could you look for the expiry date? The last time it was working was on Dec 21, 2023 but it probably already expired

**Comment by srikarparsi** [comment] 2024-02-15 02:27
Got it, so I believe the next issue will be created on February 28th. So would next steps since the token already expired be to create one of these issues, assign it to myself, and rotate the token?

**Comment by srikarparsi** [comment] 2024-02-27 23:54
Hey @marcochavezf! Friendly bump on the above question :)

**Comment by marcochavezf** [comment] 2024-02-29 01:26
Yup, if we confirmed that token is expired then it will be time to contact Bancorp for another token. IIRC in another GH issue, Bancorp mentioned that another company/contact will be in charge of rotating the token. I think @deetergp has more info about it

**Comment by deetergp** [comment] 2024-02-29 17:35
The next issue wasn't going to run until May, but it looks like we need it to run sooner. I retried the job and it generated the issue and assigned it to @francoisl [here](https://github.com/Expensify/Expensify/issues/374234). Outside of that, the only real information I have is that dealing with Bancorp/Tabapay is a bit like pulling teeth. They are slow to respond and need to be bumped daily till you get what you need from them. 😬

**Comment by srikarparsi** [comment] 2024-03-20 04:56
Still seems to be failing. Logs [here](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228673125b8f674c0d-MIA%22%20AND%20timestamp%3A%5B2024-03-20T00%3A00%20TO%202024-03-21T23%3A59%5D). The [isDebitCard](https://github.com/Expensify/Auth/blob/7092c3bab19d351479244a1feea5bf7d406233d0/auth/command/CreateFund.cpp#L282) check is failing which means the Bancorp response doesn't have the "card" property. The Bancorp token seems to be rotated above but I'll check more on this tomorrow, maybe the response format might've changed for testing cards?

**Comment by srikarparsi** [comment] 2024-05-15 06:01
No update still

**Comment by srikarparsi** [comment] 2024-06-17 22:46
Looks like this is no longer reproducible with this [debit test card](https://docs.stripe.com/testing). Closing this out

**Comment by izarutskaya** [comment] 2024-06-28 08:53
Issue is still reproducible 
Build 9.0.3-1

https://github.com/Expensify/App/assets/115492554/75d0c0c8-a21f-40fd-8bee-d6debc198381

**Comment by srikarparsi** [comment] 2024-07-23 04:31
Hey, do you think you could try again with this card number: 4000056655665556. It's still working for me.

**Closed by srikarparsi** 2024-07-23 04:31 UTC
Labels: Engineering, Monthly

**Comment by Casian-P** [comment] 2025-02-25 13:08
Hello @srikarparsi , 

I have this user, https://www.expensify.com/concierge/#/chat/19255866, who is encountering the same error. Should I open a new GH, or can we investigate it here?
