### ISSUE TITLE
[$125] Markdown - Markdown is not rendered if there is a space after a triple backtick

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45088] opened 2024-07-09 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** .0.5-8
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4700427
**Email or phone of affected tester (no customers):** dave0123seife+stest@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to any conversation
2. Send a message with a triple back tick with the following format
```
test
```
3. Important step: Make sure there is a space after the top backtick.

## Expected Result:
Markdown is rendered

## Actual Result:
Markdown is not rendered if there is a space after a triple backtick

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e823e85f-17d6-4970-bb21-d5689220145d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0177eb2919e6316787</li>
        <li>Upwork Job ID: 1811456787683573189</li>
        <li>Last Price Increase: 2024-08-19</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 103254066</li>
<li>devguest07 | Contributor | 103254071</li>
<li>tsa321 | Contributor | 103602722</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @akinwale</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @devguest07</details>

**Comment by lanitochka17** [comment] 2024-07-09 15:09
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-09 15:09
We think that this bug might be related to #vip-vsp

**Comment by jacobkim9881** [comment] 2024-07-09 18:17
Small change can fix the issue at https://github.com/Expensify/react-native-live-markdown

**Comment by tsa321** [comment] 2024-07-10 10:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Markdown is not rendered if there is a space after a triple backtick


### What is the root cause of that problem?

In here:

https://github.com/Expensify/expensify-common/blob/5373eff291c28766607e3bc9491822aa1381cdf4/lib/ExpensiMark.ts#L132

We don't consider whitespace(s) after the three backtick

### What changes do you think we should make in order to solve the problem?

We could modify the regex into:

```javascript
regex: /(&#x60;&#x60;&#x60;\s*?(?:\r\n|\n))((?:\s*?(?!(?:\r\n|\n)?&#x60;&#x60;&#x60;(?!&#x60;))[\S])+\s*?(?:\r\n|\n))\s*(&#x60;&#x60;&#x60;)/g,

```

**Comment by greg-schroeder** [comment] 2024-07-16 22:18
@akinwale is up next on reviewing proposals!

**Comment by akinwale** [comment] 2024-07-19 22:14
Reviewing proposals today.

**Comment by akinwale** [comment] 2024-07-19 22:19
The solution in @devguest07's [proposal](https://github.com/Expensify/App/issues/45088#issuecomment-2220114282) is the best approach here.

@ShridharGoel I don't see a point of trimming whitespace characters and that could introduce a bug, if the whitespace characters were intentionally added by the user.

🎀👀🎀 C+ reviewed.

**Comment by AndrewGable** [comment] 2024-07-22 06:06
@devguest07 @akinwale - Do we have existing tests that will verify this change will not break anything? Can we update the tests with this new case?

**Comment by greg-schroeder** [comment] 2024-07-22 12:22
Not overdue, trying to decide whether we're ready to move forward with @devguest07's proposal

**Comment by greg-schroeder** [comment] 2024-07-25 11:13
Next up is PR from @devguest07

**Comment by greg-schroeder** [comment] 2024-07-31 15:06
Any update here @devguest07?

**Comment by AndrewGable** [comment] 2024-08-09 19:44
What's the latest here?

**Comment by greg-schroeder** [comment] 2024-08-13 16:11
bump @devguest07

**Comment by mountiny** [comment] 2024-08-19 11:39
Unassigning the contributor for lack of urgency on the solution. 

@akinwale open to other proposals

**Comment by akinwale** [comment] 2024-08-20 05:54
@tsa321 Can you run the unit tests after applying your proposed solution to make sure everything passes? You would also need to add tests for the updates if your proposal is selected as previously [indicated](https://github.com/Expensify/App/issues/45088#issuecomment-2242158869).

**Comment by akinwale** [comment] 2024-08-20 13:03
@AndrewGable We can reassign this to @tsa321 based on the [proposed solution](https://github.com/Expensify/App/issues/45088#issuecomment-2220080942).

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment] 2024-08-21 05:50
@tsa321 The OP in the PR you created does not follow the PR author checklist template. You would need to close the PR and create a new one which follows the template.

**Comment by greg-schroeder** [comment] 2024-09-09 06:23
PR is still in review

**Comment by greg-schroeder** [comment] 2024-09-17 00:53
PR is merged. Awaiting deploy to staging -> prod

**Comment by greg-schroeder** [comment] 2024-09-23 03:01
Same as above

**Comment by akinwale** [comment] 2024-09-23 13:42
@greg-schroeder The PR was actually deployed to production as part of [this checklist](https://github.com/Expensify/App/issues/48791) on [2029-09-11](https://github.com/Expensify/App/issues/48791#issuecomment-2342359302) but automation did not pick this up. The payment due date is 2029-09-18.

**Comment by greg-schroeder** [comment] 2024-09-27 19:34
Oh, word, automation failure. I'll take care of this today

**Comment by greg-schroeder** [comment] 2024-09-27 19:36
Payment summary:

Contributor: @tsa321 - $125 - To be paid via Upwork
C+: @akinwale - $125 - To be paid via Upwork

**Comment by greg-schroeder** [comment] 2024-09-27 19:40
Paid!

**Closed by greg-schroeder** 2024-09-27 19:40 UTC
Labels: External, Weekly, Awaiting Payment, Bug
