### ISSUE TITLE
[$500] Expense Details - Childs of "Test" are not displayed in the list in the "[parent]: [child]" format

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30869] opened 2023-11-03 18:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. As the employee in NewDot - navigate to the workspace chat
2. Start a request and reach the categories list
3. Select the parent category "Test"
4. Click on the category field

## Expected Result:
Verify the "Test" category is pinned to the top and the childs of "Test" are displayed in the list in the "[parent]: [child]" format

## Actual Result:
Childs of "Test" are not in the "[parent]: [child]" format

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a20843b7-5724-42ee-927c-d9c23a84621d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112401f8801038eff</li>
        <li>Upwork Job ID: 1720504583534825472</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by wlegolas** [comment] 2023-11-03 22:27
Hi @lanitochka17 just to check if I understood the problem.

In the step "**2. Start a request and reach the categories list**", the list of Categories should be shown with the hierarchy, for example:

![image](https://github.com/Expensify/App/assets/698363/b2a18b41-5cac-46a9-b38d-e390fc0e365e)

But if I select the parent "**Travel**", and execute the step "**4. Click on the category field**", should I see the categories not as a tree, but just with the `[parent]: [child]` format, for example:

![image](https://github.com/Expensify/App/assets/698363/9eeaad5a-c79b-4bff-bc7a-192ed71185f3)

Is the image below the expected result when selecting a parent?

**Comment by wlegolas** [comment] 2023-11-05 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense Details - Childs of "Test" are not displayed in the list in the "[parent]: [child]" format

### What is the root cause of that problem?

In the `CategoryPicker` component there is the memorized value `sections` with the Category option tree to be shown, this memoized `sections` value is generated using the method `getFilteredOptions` from `OptionsListUtils`.

https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/components/CategoryPicker/index.js#L34-L52

To generate the Category option tree is used the sequence of methods from the `OptionsListUtils`: `getFilteredOptions` -> `getOptions` -> `getCategoryListSections` -> `getCategoryOptionTree`

The method `getCategoryOptionTree` is responsible to generate the Category option tree. This method has a second parameter `isOneLine` that changes the way the Category tree is formatted, when the parameter `isOneLine` is `true`, the result for the Category tree will be in the format "**[parent]: [child]**", but the current implementation doesn't use this second parameter.

https://github.com/Expensify/App/blob/846a4b74ef81fa17ecaed4af8bfe22ad2eeeb8c8/src/libs/OptionsListUtils.js#L893-L899

When there is a selected Category this information was not used when calling the `getCategoryOptionTree` method to generate the tree in one line.

### What changes do you think we should make in order to solve the problem?

We should change the method `getCategoryListSections` in the `OptionsListUtils` when generating the Category tree using the `getCategoryOptionTree` method, send the value `true` in the second parameter `isOneLine` if there is selection, otherwise `false`.

For example,

```
const filteredCategories = _.filter(enabledCategories, (category) => !_.includes(selectedOptionNames, category.name));

categorySections.push({
    // "All" section when items amount more than the threshold
    title: Localize.translateLocal('common.all'),
    shouldShow: true,
    indexOffset,
    data: getCategoryOptionTree(filteredCategories, !_.isEmpty(selectedOptions)), // Here is the change
});

return categorySections;

```

### What alternative solutions did you explore? (Optional)

N/A

**POC**

https://github.com/Expensify/App/assets/698363/662d5132-d72a-4c77-a1ed-601012fc818f

**Comment by waterim** [comment] 2023-11-07 19:04
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by rezkiy37** [comment] 2023-11-08 10:35
Guys, there is not any bug here. It is expected that when there are >=8 categories, the app shows subcategories like the hierarchy. So, I think we can close the issue.

cc @lanitochka17, @waterim, @wlegolas, @amyevans and @puneetlath.

**Comment by mountiny** [comment] 2023-11-08 14:02
I think that makes sense to me!

**Closed by mountiny** 2023-11-08 14:02 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
