### ISSUE TITLE
[HOLD for payment 2024-02-14] [$500] [Wave 5] [ECard Settings] App crashes when pressing back button when activating physical expensify card

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#34875] opened 2024-01-22 12:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705661461207919

## Action Performed:
Prerequisites:

- Have a physical card to activate
- Alternatively (if on dev) you can add this effect to WalletPage.js to create a mock card:

1. Navigate to the WalletPage
2. Navigate to Expensify Card
3. Click the Activate physical card button
4. The native keyboard is necessary for reproduction but it will be closed by default, to enable it you have to manually focus some digit of the activation code (e.g. the 4th one), that should toggle the native keyboard
5. Once the native keyboard is toggled, dismiss it by pressing anywhere on the screen
6. Once it’s dismissed press the < button on the screen keyboard (the custom one)

## Expected Result:
App should not crash

## Actual Result:
App crashed

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4febea3f9721613</li>
        <li>Upwork Job ID: 1749410465588416512</li>
        <li>Last Price Increase: 2024-01-26</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 28131636</li>
<li>akinwale | Contributor | 28131637</li>
</ul></li>
    </ul>
</details>

**Comment by akinwale** [comment] 2024-01-22 13:25
## Proposal
[Updated](https://github.com/Expensify/App/issues/34875#issuecomment-1903974209)

**Comment by akinwale** [comment] 2024-01-22 13:29
## Proposal
[Updated](https://github.com/Expensify/App/issues/34875#issuecomment-1903974209)

**Comment by situchan** [comment] 2024-01-22 13:30
Seems like the same root cause as https://github.com/Expensify/App/issues/18874

**Comment by akinwale** [comment] 2024-01-22 13:59
> Seems like the same root cause as #18874

Yeah, looks like it. However, the underlying cause of that issue was fixed. This is triggered due to expected user action.

**Comment by situchan** [comment] 2024-01-24 14:07
Seems like no C+ is assigned here. I can take this if needed.

**Comment by DylanDylann** [comment] 2024-01-29 16:49
@akinwale Could you reproduce this issue? I can't reproduce anymore 
https://github.com/Expensify/App/assets/141406735/07c92e12-b662-4aee-bd2b-a5f7668db9c7

**Comment by akinwale** [comment] 2024-01-29 17:02
> @akinwale Could you reproduce this issue? I can't reproduce anymore
> 

You need to press the Backspace button on the number pad to reproduce, not the back navigation button.

**Comment by DylanDylann** [comment] 2024-01-29 17:15
<img width="308" alt="Screenshot 2024-01-30 at 00 15 14" src="https://github.com/Expensify/App/assets/141406735/d90f631d-ee3c-46eb-9972-07043981bc91">

@akinwale  Could you help to point out `Backspace button on the number pad`

**Comment by DylanDylann** [comment] 2024-01-30 09:40
Backspace only be triggered if the input is empty and the App is focusing on the first position.

@akinwale Solution 1 looks good to me 

🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-01-30 09:40
@akinwale  In the PR phrase, could you also find out other places that also use the number pad? And verify that similar bugs also be fixed.

**Comment by grgia** [comment] 2024-01-30 23:56
All yours @akinwale!

**Comment by akinwale** [comment] 2024-01-31 06:36
@DylanDylann My [PR](https://github.com/Expensify/App/pull/35454) is ready for review.

**Comment by DylanDylann** [comment] 2024-02-14 14:53
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@DylanDylann] The PR that introduced the bug has been identified. Link to the PR: **NA**
 [@DylanDylann] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **NA**
 [@DylanDylann] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **NA**
 [@DylanDylann] Determine if we should create a regression test for this bug. **Yes**
 [@DylanDylann] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


Regression Test Proposal
1. Launch the Expensify app.
2. Navigate to the Wallet page.
3. Click or tap on the Activate physical card button.
4. Dismiss the soft keyboard that is shown so that the magic code input loses focus. (The soft keyboard showing up and getting dismissed is a required step for the test).
5. Press the Backspace button at the bottom right of the BNP.
6. Verify that the app does not crash.
Do we agree 👍 or 👎

**Comment by greg-schroeder** [comment] 2024-02-14 23:42
Paid, filed regression test, closing

**Closed by greg-schroeder** 2024-02-14 23:42 UTC
Labels: External, Daily, Needs Reproduction, Awaiting Payment, Bug
