### ISSUE TITLE
[HOLD for payment 2024-02-05] [$500] Workspace IOU - Inconsistent LHN avatars and IOU shows unavailable workspace for deleted workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28187] opened 2023-09-25 19:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27833
## Action Performed:
1. Go to staging.new.expensify.com
2. Create a workspace
3. Go to the workspace chat
4. Request money from the workspace chat
5. Delete the workspace
6. Open the IOU from the deleted workspace

## Expected Result:
- The avatar for the workspace IOU should be consistent
- In the IOU report of the deleted workspace, it will show the actual workspace name and avatar for the workspace in the chat header and LHN

## Actual Result:
- Before opening the IOU report after deleting the workspace, it just shows the workspace avatar. After opening the IOU report, it changes to stacked avatars involving the workspace and the workspace member
- In the IOU report of the deleted workspace, 'Unavailable workspace' is displayed for the workspace name and avatar, while it still shows the actual workspace name and avatar in the workspace chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.74-0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ef4ed166-c252-4d07-84eb-57e9cd43aead

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01429a4f26ef87b71d</li>
        <li>Upwork Job ID: 1706603196198379520</li>
        <li>Last Price Increase: 2023-11-21</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 27843980</li>
<li>situchan | Contributor | 28092374</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @robertKozik</details>

**Comment by garrettmknight** [comment] 2023-09-26 09:34
Reproduced - opening up.

**Comment by garrettmknight** [comment] 2023-10-05 18:47
Got it - I'll take internal, thanks!

**Comment by MariaHCD** [comment] 2023-10-06 15:29
Working on a backend fix: https://github.com/Expensify/Auth/pull/8874

**Comment by MariaHCD** [comment] 2023-10-06 15:43
@robertKozik I've got a backend fix for passing the oldPolicyName and the avatars look to be correct for the IOU report now. However, the `(archived)` is no longer showing in the LHN for the IOU report. Is this something that needs to be handled in the frontend?

See below the `Test Workspace` has been archived but the report title in the LHN for the IOU doesn't include `(archived)`

<img width="976" alt="Screenshot 2023-10-06 at 7 41 19 PM" src="https://github.com/Expensify/App/assets/12268372/7de366b1-0dfb-4c59-8ee2-c8610ac1f33d">

**Comment by robertKozik** [comment] 2023-10-06 19:54
Let me dive into it...

**Comment by MariaHCD** [comment] 2023-10-09 11:44
Backend fix is out for review: https://github.com/Expensify/Auth/pull/8874

@robertKozik let me know what you find!

**Comment by MariaHCD** [comment] 2023-10-11 12:09
Backend fix was deployed to production. So the workspace name and avatars should be displayed correctly now.

The last thing we need is to understand why `(archived)` is no longer showing in the LHN for the IOU report.

**Comment by robertKozik** [comment] 2023-10-11 13:23
From my understanding the problem lies on where we are concatenating the ` (archived)` part to the policy name. When creating the name of the IOU we are getting the policy name via `ReportUtils.getPolicyName` function which isn't checking the archive status of the policy.

If my suspicion are correct it's purely frontend related, and until now it was covered with `Unavailable workspace` name

**Comment by MariaHCD** [comment] 2023-10-16 10:12
Cool, so looks like we need a frontend fix for showing ` (archived)` for IOU reports that are part of a deleted workspace.

**Comment by MariaHCD** [comment] 2023-10-18 12:39
I think we are open to proposals for the frontend fix for showing ` (archived)` in the LHN for IOU reports that are part of a deleted workspace

**Comment by MariaHCD** [comment] 2023-10-23 12:15
Oh, interesting, thanks, @bernhardoj. So basically you're saying the BE isn't actually archiving the chat reports? 🤔 I'll have to relook into this, then

**Comment by MariaHCD** [comment] 2023-10-25 14:44
I think we aren't archiving IOU reports when the underlying workspace is deleted. I believe we are only archiving the policy expense chats and the policy rooms: https://github.com/Expensify/Auth/pull/7927

@jasperhuangg can you confirm?

**Comment by MariaHCD** [comment] 2023-10-31 12:20
Confirming what the expected outcome is for Workspace IOUs in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1698754831118739

**Comment by MariaHCD** [comment] 2023-10-31 13:01
Okay, from the [slack conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1698754831118739): expense reports should not be archived if the workspace is deleted, users can still continue to comment on those financial transactions.

I believe we'll need to update the App logic to exclude optimistically archiving expense reports.

**Comment by jasperhuangg** [comment] 2023-11-01 18:43
> I think we aren't archiving IOU reports when the underlying workspace is deleted. I believe we are only archiving the policy expense chats and the policy rooms: [Expensify/Auth#7927](https://github.com/Expensify/Auth/pull/7927)
> 
> @jasperhuangg can you confirm?

yes that is correct!

**Comment by MariaHCD** [comment] 2023-11-02 07:05
Thanks, all. Sounds like we can close this in favor of https://github.com/Expensify/App/issues/29049

**Comment by MariaHCD** [comment] 2023-11-14 08:15
Reopening this issue because the conclusion from the [other issue](https://github.com/Expensify/App/issues/29049#issuecomment-1808387155) is that task reports should be archived. However, expense reports should not be archived when the workspace is deleted. 

So let's go ahead and ensure that expense reports are not optimistically archived on the frontend.

@robertKozik what do you think of @bernhardoj's [proposal](https://github.com/Expensify/App/issues/28187#issuecomment-1787404913)?

**Comment by garrettmknight** [comment] 2023-11-20 17:10
@robertKozik can you take a look at @bernhardoj's [proposal](https://github.com/Expensify/App/issues/28187#issuecomment-1787404913)?

**Comment by robertKozik** [comment] 2023-11-20 22:14
Hi, proposal from @bernhardoj looks good, it's pretty straight forward and should work - only archivechat rooms and policy expense chats

**Comment by MariaHCD** [comment] 2023-11-27 07:02
Apologies for the delay, I was OOO unexpectedly last week. @bernhardoj's proposal looks good to me too.

**Comment by situchan** [comment] 2023-12-20 14:58
@robertKozik is not in C+ team now.
I can review if @robertKozik wants to take over.

**Comment by bernhardoj** [comment] 2024-01-08 12:33
@MariaHCD @garrettmknight hi, the review has been stale for some weeks, maybe we should reassign the C+ to @situchan?

**Comment by MariaHCD** [comment] 2024-01-10 10:18
@situchan do you have the bandwidth to do the C+ review of the PR?

**Comment by situchan** [comment] 2024-01-10 10:19
@MariaHCD yes

**Comment by garrettmknight** [comment] 2024-02-05 16:36
Paid out.

@situchan please complete the checklist when you get a chance so we can close.

**Comment by garrettmknight** [comment] 2024-02-14 16:14
QA in, closing.

**Closed by garrettmknight** 2024-02-14 16:14 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug
