### ISSUE TITLE
Room & Task - Text cursor is at the beginning of text when opening room description

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48051] opened 2024-08-27 06:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.25-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to a room.
3. Click on the room header.
4. Click Description.
5. Add a description and save it.
6. Click on the description field.

## Expected Result:
The text cursor will be at the end of the text.

## Actual Result:
The text cursor is at the beginning of the text.

This issue also happens in task description.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d3c85606-5ca3-432f-83af-4b2bd552e370

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment] 2024-08-27 15:47
I'm demoting this as it doesn't seem worthy of blocking the deploy.

**Comment by Skalakid** [comment] 2024-08-28 08:23
@puneetlath @IuliiaHerets I can't reproduce this issue on the latest staging:


https://github.com/user-attachments/assets/dd72e5cf-296f-4a22-933e-0263b9e3115e

**Comment by IuliiaHerets** [comment] 2024-08-28 09:58
@Skalakid I can't reproduce on the latest build too

https://github.com/user-attachments/assets/13feb494-a2da-4fb8-8706-c2f99076eaf7

**Comment by IuliiaHerets** [comment] 2024-09-10 11:55
@Skalakid  The issue was reverted, QA team again can repro it, build  - v9.0.31-12

https://github.com/user-attachments/assets/6c9c6618-bde0-401c-98c2-a4a54d081a3d

**Comment by Skalakid** [comment] 2024-09-11 09:44
I can also reproduce it again. After testing the issue will be fixed by [this PR](https://github.com/Expensify/react-native-live-markdown/pull/470) inside the `react-native-live-markdown` library. Inside this PR I changed the way how often and in what way the input structure elements are being updated. Thanks to that the cursor position issue when component just loads are being fixed. [Here](https://github.com/Expensify/App/pull/48626) we are bumping the library version in E/App

**Comment by Skalakid** [comment] 2024-09-16 11:26
Hey, the [PR](https://github.com/Expensify/App/pull/48626) with the bump has been merged and I can't reproduce this issue now. Can you please verify this on your side, please? 

https://github.com/user-attachments/assets/fc60b4fd-7633-46f7-8b11-5af4b3d7d0b9

**Comment by dylanexpensify** [comment] 2024-09-18 10:17
@IuliiaHerets can you confirm?

**Comment by IuliiaHerets** [comment] 2024-09-18 12:10
@dylanexpensify Issue not reproducible now


https://github.com/user-attachments/assets/edf2d54a-0da5-4e24-8c45-777335938f2f

**Closed** 2024-09-25 10:38 UTC
Labels: Engineering, Daily, Overdue, Bug
