### ISSUE TITLE
[HOLD for payment 2024-01-09] [$500] IOU - Edited amount for a paid request does not revert to initial amount after closing error message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31622] opened 2023-11-21 12:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.1-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. [User A] Request money from User B.
3. [User A] Open IOU details page > Click Amount.
4. [User B] Pay the request.
5. [User A] Enter a new amount and save it.
6. [User A] Close the error message.

## Expected Result:
The amount in IOU details page should revert to the original amount after closing the error message.

## Actual Result:
The amount in IOU details page does not revert to the original amount after closing the error message. It only reverts after refreshing the app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5965ccbb-5690-4eae-a520-ab2d5e918e45

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01674cdc2bbfceb3e4</li>
        <li>Upwork Job ID: 1726944311277539328</li>
        <li>Last Price Increase: 2023-12-05</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 28036430</li>
</ul></li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-11-21 13:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Edited amount for a paid request does not revert to initial amount after closing error message

### What is the root cause of that problem?
When User B paid the request money, We don't have any logic to dismiss edit amount modal in the User A
### What changes do you think we should make in order to solve the problem?
I suggest we should add a condition to check if isSettled is true, we will dismiss amount edit modal or display not found page

### What alternative solutions did you explore? (Optional)

**Comment by sobitneupane** [comment] 2023-11-29 09:07
Thanks for the proposal @bernhardoj.

Can you please help me understand later part of your proposal. After we revert `set` to `merge`, what issue will we face and how your proposal will solve the issue?

**Comment by slafortune** [comment] 2023-12-06 21:24
@sobitneupane can you please update this?

**Comment by slafortune** [comment] 2024-01-10 17:52
Whoops!  I got it Greg!

**Comment by slafortune** [comment] 2024-01-10 17:53
@sobitneupane can you complete the checklist?

**Comment by slafortune** [comment] 2024-01-12 18:42
Offer sent @sobitneupane can you please accept that as well as complete the above checklist?

**Comment by sobitneupane** [comment] 2024-01-16 06:19
Sorry for the delay @slafortune. I am running quite busy. I will try to get to it before weekend.

**Comment by slafortune** [comment] 2024-01-16 14:59
Thanks for the update @sobitneupane , I'll make sure to come back to this on Monday.

**Comment by slafortune** [comment] 2024-01-18 18:29
coming back to this Monday.

**Comment by slafortune** [comment] 2024-01-22 16:01
@sobitneupane will you be able to get this off your plate in the next day or two?

**Comment by sobitneupane** [comment] 2024-02-01 15:42
I will complete the checklist by EOD.

**Comment by sobitneupane** [comment] 2024-02-02 08:29
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/27609

> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/27609/files#r1475723305
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:


> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

Yes.
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment] 2024-02-02 08:31
**Regression Test Proposal**

1. Request money from user B
2. Press the IOU preview twice to open the IOU detail
3. Press the Amount field to open the edit amount page
4. From user B, pay the request
5. Back to user A, edit the amount to any amount
6. Verify you will get an error message
7. Verify the amount is reverted to the paid amount

Do we agree 👍 or 👎

**Comment by slafortune** [comment] 2024-02-02 18:58
- [ ] @bernhardoj paid $500 via [Upworks](https://www.upwork.com/nx/wm/workroom/35712062/overview)
- [ ] @sobitneupane is **due** $500 via NewDot

**Closed by slafortune** 2024-02-02 18:58 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-02-14 22:41
$500 approved for @sobitneupane based on summary above.
