### ISSUE TITLE
autosuggest makes the cursor go out of screen on description field in split bill

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22527] opened 2023-07-09 05:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
## Action Performed:

1. Open the app
2. Click on plus and click on split bill
3. Enter any amount and click next
4. Select any users and click next
5. Click of description
6. Type in few words until very small space is left from right and type in any letters to trigger keyboard autosuggest for a big word
7. Click on the autosuggest and observe that cursor goes out of screen and only after we type something again, cursor and last word is visible fully

Note: This is also reproducible on other free text fields as well like: Assign task, display name, workspace name.
Note: Not reproducible on all Android devices, a selection of those reproducible or not are [here](https://github.com/Expensify/App/issues/22527#issuecomment-1638211209).

## Expected Result: 
App should scroll to the end cursor position when we click on any keyboards suggested word near the end on line
## Actual Result: 
App does not scroll to the end cursor position when we click on any keyboards suggested word near the end on line making the cursor go out of screen

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/33bd57e4-78fd-40f6-bd20-8865a5c7de93

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688574338491659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-07-10 11:16
Hm, I can't seem to reproduce this using browserstack on Pixel 7 `v1.3.38-4`. Asking in [the thread](https://expensify.slack.com/archives/C049HHMV9SM/p1688987775367499?thread_ts=1688574338.491659&cid=C049HHMV9SM). 

https://github.com/Expensify/App/assets/16232057/0fa39391-1859-4acb-8607-71edcefc9f87

**Comment by trjExpensify** [comment] 2023-07-12 10:39
Okay, so Applause can't repro this using a Realme6 device. @dhanashree-sawant tested on Xiaomi Mi 11x and redmi note 10 pro. I'm asking whether we have other devices to try and whether this is only on the split bill description field and not other free text fields throughout app?

**Comment by trjExpensify** [comment] 2023-07-17 14:00
So far it's pretty split in terms of which devices we can or can't reproduce on:

**Reproducible:** 
- SG galaxy A50
- Xiaomi Mi 11x
- Redmi note 10 pro

**Not reproducible:** 
- Pixel 5 / 13
- Pixel 7 (browserstack)
- Realme6

It seems to be device specific, which starts to get pretty tricky, so I'm a bit conflicted as to whether we continue on this. CC: @Julesssss for a second opinion on Android issues like this. 

Asked about my outstanding question as to whether it's split bill description field specific or not [here](https://expensify.slack.com/archives/C049HHMV9SM/p1689602096294099?thread_ts=1688574338.491659&cid=C049HHMV9SM).

**Comment by Julesssss** [comment] 2023-07-17 14:11
> SG galaxy A50
> Xiaomi Mi 11x
> Redmi note 10 pro

Custom Android ROMs (Samsung, Ziaomi, ect) are notorious for having UI bugs. I say we ignore it

**Comment by trjExpensify** [comment] 2023-07-17 17:32
Okay cool, that works for me. I updated the OP to include some of the findings to determine this was device specific, and not solely limited to the split bill description field. Closing!

**Closed by trjExpensify** 2023-07-17 17:32 UTC
Labels: Daily, Needs Reproduction, Bug
