### ISSUE TITLE
[$250] [Mentions] Empty expense details and broken report when user is invited to combined report

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48396] opened 2024-09-02 08:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.27-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** Exp https://expensify.testrail.io/index.php?/tests/view/4907185
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause Internal Team 

## Action Performed:
1. Go to staging.new.expensify.com
2. [User A] Submit an expense to User B (make sure User B has no unsettled expense with User A)
3. [User A] Click on the expense preview in the main chat to go to combined report.
4. [User A] Send a user mention containing User C
5. [User A] Click Invite from the whisper message
6. [User C] Open the invited expense report

## Expected Result:
- Expense details will be shown without issue.
- Report will not appear broken.

## Actual Result:
- Expense details are empty when the report is opened for the first time. It only shows the details after refreshing the report.
- Report appears broken with the duplicate details above the report.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b0e92856-5540-4911-9b2e-f8ac88043791

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021831652271737365741</li>
        <li>Upwork Job ID: 1831652271737365741</li>
        <li>Last Price Increase: 2024-09-26</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-02 08:55
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by trjExpensify** [comment] 2024-09-05 11:14
I don't get the glitch screen when repro'ing this, but I do see empty details in the one expense iouReport for the invited user, so it does seem broken: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/31400e26-16f2-4f47-949f-e3f60b02909d">

**Comment by trjExpensify** [comment] 2024-09-05 11:15
CC'ing @puneetlath for visibility as a mentions invite bug.

**Comment by jacobkim9881** [comment] 2024-09-12 16:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When invited to open expense preview, the report preview is broken.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/52c0ccb5ab623a1056ecc8be569e0925cdfd07f5/src/pages/home/report/ReportActionsView.tsx#L162-L164
`lastAction` is false in the issue. When the user C invited, the user got this report action as a last action within report actions: 

```js
{
    "originalMessage": {
        "resolution": "invited"
    }
}

```

`lastAction` selects the invite resolution and the condition for checking create action passes the `lastAction`. As a result fake create report action is made and there are 2 report actions with `actionName` "CREATED" type :
```js
//this the fake one
{
    "reportActionID": "2366733686483205217",
    "message": [
        {
            "type": "TEXT",
            "style": "strong",
            "text": "18284767"
        },
        {
            "type": "TEXT",
            "style": "normal",
            "text": " created this report"
        }
    ],
    "pendingAction": null,
    "actionName": "CREATED",
    "created": "2024-09-12 13:19:39.701",
    "actorAccountID": 18269034,
    "person": [
        {
            "type": "TEXT",
            "style": "strong",
            "text": "assa"
        }
    ]
} 
// And original one: 
{
    "reportActionID": "1609068092870573138",
    "message": [
        {
            "type": "TEXT",
            "style": "strong",
            "text": "cvj (jacobkim9881+65@gmail.com)"
        },
        {
            "type": "TEXT",
            "style": "normal",
            "text": " created this report"
        }
    ],
    "actionName": "CREATED",
    "created": "2024-09-11 14:53:15.735",
    "person": [
        {
            "type": "TEXT",
            "style": "strong",
            "text": "jacobkim9881+65@gmail.com"
        }
    ]
}

```

The reason fake report action with "CREATED" is for showing expense preview till having report actions from openReport API : 

https://github.com/Expensify/App/blob/52c0ccb5ab623a1056ecc8be569e0925cdfd07f5/src/pages/home/report/ReportActionsView.tsx#L152

As there are 2 "CREATED" report actions, there 2 components that have 2 same background and same amount form so CSS is broken for 2 components too. 

### What changes do you think we should make in order to solve the problem?
We can show better expense preview by defining `lastAction`. We should check `lastAction` is invited message or not : 

```js
const isInvitedMsg = isLastActionInvited ? true : false
```

If it is invited one then we edit `lastAction` and pass it into the condition :

```js

const editedLastAction = isInvitedMsg ? allReportActions[allReportActions.length - 2] : lastAction;

if(!ReportActionsUtils.isCreatedAction(editedLastAction)) {

...

```

Then whenever report actions is shown at report screen that have a report action "invited" resolution, second last action will be chosen. It will not create fake report action. 

### What alternative solutions did you explore? (Optional)
N/A

**Comment by jacobkim9881** [comment] 2024-09-12 16:25
Hi, @fedirjh,  I was trying to solve the issue. Can I upload a proposal?

**Comment by trjExpensify** [comment] 2024-09-16 21:00
@burczu did you work on this already? If not, perhaps we have @fedirjh look at [this proposal](https://github.com/Expensify/App/issues/48396#issuecomment-2346739168) first to see if that's good to approve and move on to a PR.

**Comment by burczu** [comment] 2024-09-17 07:30
@trjExpensify I've started doing some research here already and from what I see till now, there is a discrepancy between `OpenReport` API call when we first open the invited expense report and after we refresh the page:

https://github.com/user-attachments/assets/89f80470-e19d-43b4-973b-86752b1a59bf

As we can see, when we open the report for the first time, there is no Onyx data for the `transactions_` key, but it appears after the page refresh. When we check the payload for both `OpenReport` API calls, they look pretty much the same:

First call:

![Screenshot 2024-09-16 at 14 21 24](https://github.com/user-attachments/assets/baaf2888-b359-4c22-8f84-9dbe48f2ab1b)

Call after refresh:

![Screenshot 2024-09-16 at 14 22 37](https://github.com/user-attachments/assets/f114d390-7f33-4a51-b2b4-b615ef66600e)

The only difference is that in the later call, there is `clientLastReadTime` field added.

So, right now I suspect that this may be a backend issue, that should be reviewed by someone from the BE team... @fedirjh - what do you think?

**Comment by trjExpensify** [comment] 2024-09-17 15:03
Cool, thanks! @fedirjh let us know and if it's maybe BE related, let's get someone assigned to take a look.

**Comment by trjExpensify** [comment] 2024-09-18 18:47
Okay got it, @puneetlath does that sound right to you? Figured you'd have the context here.

**Comment by jacobkim9881** [comment] 2024-09-19 08:25
## Proposal
[Updated](https://github.com/Expensify/App/issues/48396#issuecomment-2346739168)

**Comment by puneetlath** [comment] 2024-09-22 19:37
Sounds reasonable to me. So basically the problem is that we are sending data related to a whisper message, to a user other than the on the that received the whisper message. Is that right? 

Also, this sounds very similar to [this issue](https://expensify.slack.com/archives/C05LX9D6E07/p1726701466939139?thread_ts=1725651893.019599&cid=C05LX9D6E07) we're discussing in NewDot quality. Where a single-transaction report appears blank the first time it is opened. And it seems to have something to do with the transactions_ data not being sent on the first OpenReport.

**Comment by trjExpensify** [comment] 2024-09-23 15:56
Ah, so maybe we should hold on https://github.com/Expensify/App/issues/48752?

**Comment by puneetlath** [comment] 2024-09-23 18:18
It's not super clear to me whether it's the same issue. [This comment](https://github.com/Expensify/App/issues/48396#issuecomment-2354757509) made me think it was but [this comment](https://github.com/Expensify/App/issues/48396#issuecomment-2358700714) sounds like it's not. @fedirjh @burczu what do you think?

**Comment by jacobkim9881** [comment] 2024-09-24 09:58
Hi, @fedirjh. If you haven't read my proposal could you review mine? I have 2 solutions from front end.

**Comment by trjExpensify** [comment] 2024-09-26 22:59
Okay, so this needs to go `internal` then correct?

**Comment by trjExpensify** [comment] 2024-09-30 21:31
Cool moved `Internal`. @puneetlath don't suppose you'd fancy this one?

**Comment by trjExpensify** [comment] 2024-10-04 17:48
Puneet, when you're back... I'm in two minds about this one. On the one hand, it's a @mentions chat bug. On the other hand, it's a bug with mentioning users in expenses which people could run into and then have a shit experience. So I'm kinda' wondering if we move this one to #f1 convert as it's an "invite" mechanism too really, so somewhat of a viral action. Otherwise, I'd put it in the #expense channel when consolidated.

**Comment by trjExpensify** [comment] 2024-10-10 18:01
Chatted to Puneet, moving to #quality.

**Comment by trjExpensify** [comment] 2024-10-14 23:49
@mountiny do you not have a hot picks section of the GH project for #quality, or how are you collecting them otherwise?

**Comment by muttmuure** [comment] 2024-10-15 16:50
@kacper-mikolajczak are you still working on this one?  https://github.com/Expensify/App/issues/48752

**Comment by muttmuure** [comment] 2024-10-15 16:50
They seem similar

**Comment by kacper-mikolajczak** [comment] 2024-10-15 18:20
> @kacper-mikolajczak are you still working on this one?

Answered in second issue 👍

**Comment by mountiny** [comment] 2024-10-16 09:01
@trjExpensify yep there is a hot picks view now https://github.com/orgs/Expensify/projects/71/views/4 you can add the hot picks label

**Comment by dangrous** [comment] 2024-10-16 17:59
Catching up on this now that I'm assigned. So after reading, it looks like two things:

1. The empty expense. This will be handled in https://github.com/Expensify/App/issues/48752, so we don't have to focus on it here.
2. The broken report. This is being caused when we're sending an onyxupdate for a whisper to an account that was not whispered to. 

My next step is to try to reproduce locally, and then figure out how to fix on the backend.

**Comment by dangrous** [comment] 2024-10-17 21:14
Okay so I'm able to reproduce this, but only by searching it in Search and opening it first in the right hand panel. That seems like the same thing though.

<img width="974" alt="Screenshot 2024-10-17 at 16 56 08" src="https://github.com/user-attachments/assets/33426c70-559f-48f4-85ae-ebae45c17609">

Working on figuring it out

**Comment by dangrous** [comment] 2024-10-17 21:31
Okay so it's something wrong with [this query](https://github.com/Expensify/Auth/blob/609b232c9cda358847ffc5104caa6b20e81d6f2d/auth/command/GetOnyxUpdates.cpp#L58-L71) which is returning the updates. EITHER the query needs to not return whispers OR the whisper update is not correctly stored/created.

It seems like the original actionable mention whispers are being sent to the Account channel, rather than the Report channel, but the resolutions are being sent to the Report, which is why the query is picking them up. I think we need to shift this so they go to the Account instead, and therefore would only go to the person who is actioning them.

**Comment by dangrous** [comment] 2024-10-17 21:47
Okay found out the issue, and probably the fix, just syncing with the PR author who introduced the change to make sure I'm not missing anything. https://github.com/Expensify/Auth/pull/11466#issuecomment-2420660405

**Comment by trjExpensify** [comment] 2024-10-22 17:27
I'm seeing `Unavailable workspace` as the invited member (and the expense details are blank still, but I understand you said that's being worked on somewhere else): 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/d26d9c94-ddf0-4e85-81a8-8db378e7606d">

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/93b04143-7f38-4510-8e6f-0321e6313f6c">

Interestingly, the transaction details aren't blank in search: 

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/49a9f5ad-06a8-4204-b1c1-343d677a78d2">

**Comment by dangrous** [comment] 2024-10-23 14:13
hm, i'm pretty sure that "unavailable workspace" is unrelated to this particular bug, so maybe should be reported separately? And yeah the details should hopefully be being dealt with [here](https://github.com/Expensify/App/issues/48752). Can you share your repro steps with them? Looks like @deetergp's having some issues reproducing.

**Comment by trjExpensify** [comment] 2024-10-23 14:33
>hm, i'm pretty sure that "unavailable workspace" is unrelated to this particular bug

What do you think is the cause of it? It looks like when the mentioned member is invited to the report, we aren't sharing the reportTitle with them properly or something. 

>And yeah the details should hopefully be being dealt with https://github.com/Expensify/App/issues/48752. Can you share your repro steps with them? Looks like @deetergp's having some issues reproducing.

Commented on that issue.

**Comment by dangrous** [comment] 2024-10-23 16:07
Okay so it looks like mentioning a user on a workspace expense report doesn't actually invite them to the workspace (which might be intentional?). Normally, if the report doesn't have a specific title (which in this case it doesn't), we build it dynamically out of `[workspace] owes [amount]`. But since the user doesn't have access to the policy, they can't get the details of the policy, including the name. 

So, next question - do we **want** to add users to the policy if they're mentioned and invited on a report? I think this is also why the invited user can't actually add comments or anything.

**Comment by dangrous** [comment] 2024-10-29 15:10
Okay so based on Slack, I think we can close this out and create a new issue for `Unavailable workspace` - does that sound right to you?

I don't believe payment is needed here, is that correct?

**Comment by trjExpensify** [comment] 2024-10-30 02:58
>I think we can close this out and create a new issue for Unavailable workspace - does that sound right to you? 

Sounds good! 

>I don't believe payment is needed here, is that correct?

Yep. Backend only.

**Comment by dangrous** [comment] 2024-10-30 15:58
Made https://github.com/Expensify/App/issues/51749 - closing this!

**Closed by dangrous** 2024-10-30 15:58 UTC
Labels: Reviewing, Daily, Weekly, Internal, Bug, AutoAssignerNewDotQuality
