### ISSUE TITLE
[Search v1] - Workspace expense shows fallback avatar in To field after deleting workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43586] opened 2024-06-12 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4623013
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Submit an expense in the workspace chat
3. Go to Search
4. Note that the transaction shows the workspace avatar
5. Delete the workspace
6. Go to Account settings > Troubleshoot > Clear cache and restart > Reset and refresh (or just log out and log in again)
7. Go to Search

## Expected Result:
The transaction in the archived workspace chat will show workspace avatar in Search

## Actual Result:
The transaction in the archived workspace chat shows fallback avatar in Search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/11167520-9abf-470e-8b99-4901fc25b44f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-12 16:00
@alexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 16:01
We think that this bug might be related to #wave-collect - Release 1

**Comment by alexpensify** [comment] 2024-06-17 22:25
I'm going to test more tomorrow.

**Comment by alexpensify** [comment] 2024-06-18 19:26
@dannymcclain - I need Design feedback here. Should we show the workspace or fallback avatar? Also, I'm not sure if we store the avatar after the Workspace is closed. Thanks for the feedback!

**Comment by dannymcclain** [comment] 2024-06-18 19:55
I think it's ok to show the fallback if we don't store the avatar after the workspace is closed. But do we really not show the name? Shouldn't we show something like `Danny's Donuts (Archived) or `Danny's Donuts (Deleted)` or `Deleted Workspace` or _something_?

Also, I think the fallback workspace avatars are supposed to have the little building icon instead of the user icon. At least that's what I see in Figma. 
![CleanShot 2024-06-18 at 14 54 59@2x](https://github.com/Expensify/App/assets/7516624/c68db7d8-abe9-489a-9617-21e44a1dbf31)

**Comment by alexpensify** [comment] 2024-06-20 19:17
Oh, good call out on the name change. Let me review more then and I'll follow up here.

**Comment by dannymcclain** [comment] 2024-06-24 16:14
Any updates here? @shawnborton also [posted about this in Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1719219016510539). It looks like we still show the avatar and workspace name in the Expense View after a workspace has been deleted/archived—I feel like we should do the same thing on the search page.

**Comment by luacmartins** [comment] 2024-06-26 19:27
This seems internal to me. Gonna add the label and look for volunteers

**Comment by dannymcclain** [comment] 2024-06-26 19:30
But it's not overdue though... right?

**Comment by luacmartins** [comment] 2024-06-26 19:36
Not sure why it said I added that label lol

**Comment by alexpensify** [comment] 2024-06-28 17:57
We need an internal volunteer here

**Comment by alexpensify** [comment] 2024-06-28 21:53
## Heads up, I will be offline until Monday, July 8, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by dannymcclain** [comment] 2024-07-01 13:22
Not overdue Melv.

**Comment by dannymcclain** [comment] 2024-07-03 19:23
I believe we're still waiting on an internal volunteer.

**Comment by alexpensify** [comment] 2024-07-04 23:19
Yep, we need a volunteer here.

**Comment by dannymcclain** [comment] 2024-07-08 13:55
Same as before Melv.

**Comment by alexpensify** [comment] 2024-07-10 17:35
No update, still a Hot Pick.

**Comment by alexpensify** [comment] 2024-07-12 22:41
Hot Pick

**Comment by dannymcclain** [comment] 2024-07-15 16:14
☝️ Melv

**Comment by alexpensify** [comment] 2024-07-17 23:11
Still a Hot Pick

**Comment by alexpensify** [comment] 2024-07-19 23:17
Hot Pick

**Comment by dannymcclain** [comment] 2024-07-22 14:48
🤫 Shhh Melvin. It is still a hot pick.

**Comment by alexpensify** [comment] 2024-07-22 19:30
Moving to Weekly since there are other priority GHs right now.

**Comment by alexpensify** [comment] 2024-07-29 18:58
Hot Pick, no update

**Comment by alexpensify** [comment] 2024-08-05 21:03
Hot Pick

**Comment by JmillsExpensify** [comment] 2024-08-12 17:25
Highlighting in hot picks this week.

**Comment by alexpensify** [comment] 2024-08-12 21:33
Thanks, Jason!

**Comment by alexpensify** [comment] 2024-08-21 21:32
Still a hot pick here

**Comment by mvtglobally** [comment] 2024-08-23 12:03
Issue not reproducible during KI retests. (First week)

**Comment by luacmartins** [comment] 2024-08-23 14:06
This has been fixed. Closing.

**Closed by luacmartins** 2024-08-23 14:06 UTC
Labels: Weekly, Internal, Design, Bug, Hot Pick

**Comment by alexpensify** [comment] 2024-08-26 15:23
Thanks for the update! 

## Next Steps

Let's keep this one closed. 

## Heads up, I will be offline until Tuesday, September 3, 2024, and will not actively watch over this GitHub during that period. 

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!
