### ISSUE TITLE
[HOLD for payment 2023-09-27] [$500] Android - Emoji search box isn't autofocused

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27047] opened 2023-09-08 17:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat report
2. Click on emoji symbol
3. Notice that the search box isn't in focus.

## Expected Result:
Emoji search field should be autofocused

## Actual Result:
 Emoji search box isn't autofocused 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/6542eba6-3a19-4e70-90e4-e607c022dea4

https://github.com/Expensify/App/assets/93399543/f83a39d0-65ad-4d19-8947-406d499a15bf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ashimsharma10
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693843563361019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0142e9d617cdfc3cba</li>
        <li>Upwork Job ID: 1700199497560686592</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26650249</li>
<li>ashimsharma10 | Reporter | 26650253</li>
</ul></li>
    </ul>
</details>

**Comment by ashimsharma10** [comment] 2023-09-08 17:56
@ginsuma it happens only in android. Not in other platforms tho

**Comment by s-alves10** [comment] 2023-09-08 18:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Emoji search input isn't auto focused in android native

### What is the root cause of that problem?

As you can see below, we focus search input on `modalShow` event
https://github.com/Expensify/App/blob/069d246cf9d6fbc1ac622b62884fac8d927ee1d8/src/components/EmojiPicker/EmojiPicker.js#L172C38-L172C38
### What changes do you think we should make in order to solve the problem?


<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2023-09-13 10:01
Not sure why it duped the assignment for Bug manager, removing SOnia!

**Comment by zanyrenney** [comment] 2023-09-13 10:02
Thanks @s-alves10 and @narefyev91 for the review!

**Comment by Julesssss** [comment] 2023-09-26 07:05
> @ginsuma it happens only in android and mweb Android. Not in other platforms ( haven't checked on iOS) tho. And is inconsistent

Yeah this was intentional. We should have kept this behavior for native mobile and mWeb as losing ~40% of the keyboard is incredibly annoying if you're just trying to select a common emoji.

**Comment by zanyrenney** [comment] 2023-09-29 03:53
hey @s-alves10 please accept the offer for payout.

**Comment by zanyrenney** [comment] 2023-09-29 04:06
**Payments summary**

@narefyev91 does not require payment (Contractor) - N/A
@s-alves10 requires payment [offer](https://www.upwork.com/nx/wm/offer/26650249) (Contributor)
@ashimsharma10 requires payment [offer](https://www.upwork.com/nx/wm/offer/26650253) (Reporter) - PAID $50.

**Comment by s-alves10** [comment] 2023-09-29 05:19
Offer accepted

**Comment by zanyrenney** [comment] 2023-09-29 09:05
All participants who can be paid through Upwork have been. @narefyev91 please request your payment via ND. CLosing!

**Closed by zanyrenney** 2023-09-29 09:05 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by s-alves10** [comment] 2023-09-29 09:29
@zanyrenney 

This issue was merged in 3 days.
