### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] [HIGH] [Instant Submit] for Collect: Allow `Request Money` from expense reports on paid, instant submit workspaces

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#35814] opened 2024-02-05 13:50 UTC
Related to https://github.com/Expensify/Expensify/issues/334111
- Bugs found via testing steps found in [this doc](https://docs.google.com/document/d/1Z5D8I8kG4PNM9G1UAfsKeEHQKecj5mVplCuwSc6HbJM/edit)

# Flow:

## Pre-testing steps

1. Create a new collect policy on OldDot and; 
    1. Enable scheduled submit with a frequency of `Instant` (this should happen by default with Expensify accounts, or accounts on `paidPolicyInstantSubmit` beta)
    1. Invite an additional user to the policy to play the member role in these testing flows
1. Run the script stated [here](https://stackoverflowteams.com/c/expensify/questions/17518/17519) (in OldDot, when the workspace Settings page is open) to enable the policy for workspace creation for a paid plan.
    ```
    p = Policy.getCurrent();
    p.policy.isPolicyExpenseChatEnabled = "true";
    p.save();
    ```

## Test steps

1. In OldDot: As submitter, create a report
2. In NewDot: As submitter, open policy expense chat -> expense report
3. Click `+` Actions (next to `ReportActionCompose` - not the global create `+` green button)
4. Verify you see "Request Money"
5. Click Request Money, make a request, and make sure it works correctly

Currently we're blocked on 4 ^ - the "Request money" option does not show, I see:

![Screenshot 2024-02-05 at 3 50 10 PM](https://github.com/Expensify/App/assets/3885503/ade8278e-ad23-4259-b5f8-c23bfc2ee88e)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017a306e71b6f19bb2</li>
        <li>Upwork Job ID: 1754502730371850240</li>
        <li>Last Price Increase: 2024-02-19</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 0</li>
<li>rojiphil | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2024-02-08 08:16
No takers, I wonder why? This seemed pretty simple to fix, maybe the setup is too time consuming? It shouldn't be, but maybe it looks complicated?

**Comment by rojiphil** [comment] 2024-02-08 08:56
How do we set `Scheduled Submit` to `Instant`? I do not see that option 
![Screenshot 2024-02-07 at 9 15 34 PM](https://github.com/Expensify/App/assets/3004659/ec5bd241-e0dc-4463-bea7-09a74951780a)

Also, the issue title in OP mentions `paid`. 
Does this mean we want to request money on paid expense reports?
As I understand, we do not request money on paid reports. Instead, we generate a new one. Or do I miss something here?

**Comment by Beamanator** [comment] 2024-02-08 14:48
Good question @rojiphil - you need to be on the `paidPolicyInstantSubmit` beta - you can DM me in Slack (or NewDot) and I'll add you to the beta :D

**Comment by Beamanator** [comment] 2024-02-09 15:46
So this issue is making it also work for submitted reports on paid policies

**Comment by Beamanator** [comment] 2024-02-13 08:12
Still open

**Comment by Beamanator** [comment] 2024-02-17 06:11
Thanks @rojiphil for reproducing!

> I understand that the reports are instantly submitted in this case.

Correct

> But I also wonder if this is intentional as we do not allow Request money on submitted reports.

**Comment by rojiphil** [comment] 2024-02-17 07:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We need to allow adding new expenses(money requests) into the existing expense report even when after `submit` is performed.

### What is the root cause of that problem?

This is an improvement

### What changes do you think we should make in order to solve the problem?

Allow `Request money` menu option from within Expense Report. 
For this, we can modify `canRequestMoney` [here](https://github.com/Expensify/App/blob/91ea9792fe54b795115106965b2682dd1ef36847/src/libs/ReportUtils.ts#L4245) to also allow `Submitted` state and status like this:

`            return isDraftExpenseReport(report) || isProcessingReport(report);`

Additionally, when we request money from within the expense report, we also need to make changes such that the money request is generated for the current expense report. 

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-02-17 08:50
> However now, since reports are instantly submitted, we want submitters to be able to keep adding money requests to that report - because otherwise we'd only ever be able to have 1 expense / money request per report, see what i'm saying?

@Beamanator Got it
And, I think we may want to delete `submitted` reports as well
What do you think?

**Comment by Victor-Nyagudi** [comment] 2024-02-18 12:30
I'd like to be added to the `paidPolicyInstantSubmit` beta too, please, @Beamanator.

**Comment by Beamanator** [comment] 2024-02-19 07:40
@Victor-Nyagudi sure thing! Please DM me in slack with the email you'd like to be added to the beta 👍

**Comment by Beamanator** [comment] 2024-02-19 17:34
@Ollyws - Good question - yes agreed we should only allow `Request money` for submitted reports when the policy is on `instant submit` reporting frequency 👍

**Comment by rojiphil** [comment] 2024-02-19 17:51
> Correct me if I'm wrong but wouldn't your proposal enable `Request Money` for all reporting frequencies?

Yes. That's correct. I did not consider this aspect in the proposal. 
We need to additionally use `isInstantSubmitEnabled` along with `isProcessingReport`. I have updated the proposal to include this too.

**Comment by Beamanator** [comment] 2024-02-20 08:13
Using NewFeature label to get a bugzero team member for eventual payment 🙏

**Comment by alexpensify** [comment] 2024-02-21 00:53
Noted!

**Comment by rojiphil** [comment] 2024-02-21 06:17
@Ollyws
[PR](https://github.com/Expensify/App/pull/36997) is ready for review

**Comment by alexpensify** [comment] 2024-02-27 22:55
Weekly Update: Looks like @Beamanator is reviewing feedback.

**Comment by Beamanator** [comment] 2024-02-28 09:01
PR merged 👍

**Comment by alexpensify** [comment] 2024-03-08 00:16
I updated the payment summary here with the amounts: 

https://github.com/Expensify/App/issues/35814#issuecomment-1972139468

Upwork Job: https://www.upwork.com/jobs/~017a306e71b6f19bb2

--- 

Everyone has been paid in Upwork; the only action is to confirm the regression test.

**Comment by alexpensify** [comment] 2024-03-11 14:32
Not overdue, the only action is inputting the regression test.

**Comment by alexpensify** [comment] 2024-03-13 21:25
Still on my list to input the regression test.

**Comment by alexpensify** [comment] 2024-03-18 23:00
I'll be working on the regression test tomorrow.

**Comment by alexpensify** [comment] 2024-03-19 19:06
Closing - the regression test has been created for this one

**Closed by alexpensify** 2024-03-19 19:06 UTC
Labels: External, Daily, NewFeature, Awaiting Payment
