### ISSUE TITLE
[HOLD for payment 2024-02-07] [$500] [MEDIUM] Tags: Selected tag in Parent: Child format shows up multiple times in the search result list

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32203] opened 2023-11-29 17:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/31775

## Action Performed:
Precondition:
- The workspace has multiple tags in Parent: Child format added on OD.
- The workspace has more than 8 tags.

1. Log in to ND as employee.
2. Go to the workspace chat > + > Request money.
3. Create a manual request with a tag in Parent: Child format.
4. Click on the expense preview twice to open expense details page.
5. Click on Tag.
6. Search for the selected tag in the search field.

## Expected Result:
The selected tag will not show up multiple times.

## Actual Result:
The selected tag shows up multiple times.
This issue only happens with tags in Parent: Child format.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/35da36d6-5833-4581-9b37-6bc785b451a5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e80f76d4f90d5b88</li>
        <li>Upwork Job ID: 1729913749207519232</li>
        <li>Last Price Increase: 2023-11-29</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 28065674</li>
<li>jjcoffee | Contributor | 28116028</li>
</ul></li>
    </ul>
</details>

**Comment by ZhenjaHorbach** [comment] 2023-11-29 17:28
@FitseTLT 

It looks like a regression
Or not
But obviously on your part)

**Comment by FitseTLT** [comment] 2023-11-29 17:34
Yep regression
We need to remove escaping slashes here too from policyTags 
https://github.com/Expensify/App/blob/70813dbf3e2f73a73e52f880312bc198b39f4dec/src/components/TagPicker/index.js#L46-L47

**Comment by barros001** [comment] 2023-11-30 12:04
How does one add tags to a workspace? I can go to OldDot but I can only add tags to my personal workspace and I can't really find it on NewDot.

**Comment by barros001** [comment] 2023-11-30 17:38
I think this is better fixed on the backend.

In general if you're getting data from a BE and you need to modify it for presentation purposes, you do not really modify the data itself, you only modify it when presenting it on the screen. The reason for this is that the backend will send you "Test\: Child" tag, and if you modify the data and use it throughout the front end, when you send it back to the BE, you will send it as "Test: Child". We don't want to send data to BE that's different than what the BE gave to you. It's the same concept when you need to display the user input back on an HTML page. You don't escape it when you read the data, you only escape when you're rendering it. Otherwise you might end up saving/sending to BE the escaped version of the input, which is wrong.

Also, there seem to be some of inconsistencies. The API that returns all tags for a given Policy will add the `\` to the names, but the `openReport` api (`transaction.tag`) will not. I would expect all tags coming from the backend to have `\` added to the names.

Fixing the backend so that slashes are not added in the first place is the proper way to fix it IMO.

**Comment by FitseTLT** [comment] 2023-11-30 17:44
I know it is best to fix it on BE @barros001 but it is not and it is decided it should be treated in FE that's why we worked on it maybe to treat the case where the user's have already created `Parent: child` format tags. But @jjcoffee the perfect solution to this case is use our `migrateOnyx` isn't it? if not I will try to fix this regression and also create a solution to my ability to avoid future regression. What do u think?

**Comment by FitseTLT** [comment] 2023-12-04 20:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selected tag in Parent: Child format shows up multiple times in the search result list

### What is the root cause of that problem?
The root cause is 
https://github.com/Expensify/App/blob/e0d34b803aed6316fb9804a51ad5caf24f415cbf/src/components/TagPicker/index.js#L46-L47
the filter here doesn't work as intended because `policyTagList` contains the uncleaned tags (from backslashes) while the selected tag is the cleaned tag so it is not filtered out and one from the `policyTagList` and one for the selected appear in the search result.
### What changes do you think we should make in order to solve the problem?

We should clean policy tags in `PolicyUtils.getTagList` like this 
`function getTagList(policyTags: OnyxCollection<PolicyTags>, tagKey: string) {
    if (Object.keys(policyTags ?? {})?.length === 0) {
        return {};
    }

    const policyTagKey = tagKey ?? Object.keys(policyTags ?? {})[0];
    const tags = cloneDeep(policyTags?.[policyTagKey]?.tags ?? {});

    // This is to remove unnecessary escaping backslash in tag name sent from backend for "Parent: Child" type of tags.
    Object.keys(tags).forEach((key) => {
        const cleanedTagName = tags[key]?.name?.replace(/\\{1,2}:/g, ':');
        if (cleanedTagName) {
            tags[key].name = cleanedTagName;
        }
    });

    return tags;
}

`
### What alternative solutions did you explore? (Optional)

**Comment by jjcoffee** [comment] 2023-12-05 14:59
Okay so by moving the cleanup to `PolicyUtils.getTagList`, we're ensuring that anywhere we get the tags, they'll always be the cleaned ones. That sounds good to me!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by flodnv** [comment] 2023-12-05 16:49
@amyevans seems like you worked on tags recently, mind taking a look please?

**Comment by jjcoffee** [comment] 2023-12-06 08:40
Hmm actually unable to repro on latest main now. @FitseTLT Are you able to double check?

**Comment by FitseTLT** [comment] 2023-12-06 08:42
@jjcoffee you might be tricked and trying it on the create new request flow but it only exists on updating a request tag from the request preview 👍 I made the same mistake BTW

**Comment by jjcoffee** [comment] 2023-12-06 08:44
No, that's where I'm trying and I'm not seeing any duplication now (I was previously able to replicate).

**Comment by FitseTLT** [comment] 2023-12-06 09:07
@jjcoffee this [pr](https://github.com/Expensify/App/pull/32337) is changing tag options construction (to indented one) and as a result fixing this bug. But don't u still think we need to merge my pr because we still having the duplicate sent to the `getTagsOptions` but only the way it is working now is removing the duplicate. I still think we should continue with my pr as it might prevent future bugs 👍

**Comment by FitseTLT** [comment] 2023-12-07 12:54
@amyevans Let me make it easy for you. Because of the RCA I explained in my [proposal](https://github.com/Expensify/App/issues/32203#issuecomment-1839436293) at the moment this current issue was created duplicate search results were being displayed for selected tag in search. But this [pr](https://github.com/Expensify/App/pull/32337) introduced the indention hierarchial display of parent: child tags and on the process kind of solved the current issue of duplicate search results. But what I am saying is because the [pr](https://github.com/Expensify/App/pull/32365) I created to fix this regression changes the place we clean the unnecessary backslash the server is sending from tags (like "parent\:child") to a more centralized proper place `PolicyUtils.getTagList` that will prevent future bugs that might occur regarding parent:child tags. Therefore, I recommend to still proceed with the merge of my pr.

**Comment by amyevans** [comment] 2023-12-08 16:17
Brought up the recent tags display change for internal discussion [here](https://expensify.slack.com/archives/C02MW39LT9N/p1702051493931239), I think we should undo this change because it is inconsistent with OldDot tags, but I want to get wider consensus. I'll report back once we have a decision.

**Comment by amyevans** [comment] 2023-12-08 18:18
Alright we're going to move forward with a revert, tracking that here: https://github.com/Expensify/App/issues/32735

So I'll put this issue on hold for that.

I also am seeing that with the change in https://github.com/Expensify/App/issues/30734, the tag we're sending to the server does not have colons escaped. So we'll need to fix that too since that's how OldDot sends it and we need to maintain compatibility between the two. TBD if that is better tracked in its own issue, just noting here so that I don't forget.

**Comment by greg-schroeder** [comment] 2023-12-11 10:00
On hold still

**Comment by greg-schroeder** [comment] 2023-12-19 03:13
Called this out in the Weekly Update re: Wave 6, trying to get aligned on what we're doing with these tag issues related to the recent revert

**Comment by amyevans** [comment] 2023-12-19 22:29
Since the revert is merged and on staging, we can remove the `[HOLD]` here and proceed.

Heads up that I am headed OOO through 1/2 as of this evening. I'll try to check in occasionally to answer questions or review the PR, but my response times might be slower than normal.

**Comment by FitseTLT** [comment] 2023-12-20 13:08
[PR](https://github.com/Expensify/App/pull/32365) ready and updated

**Comment by jjcoffee** [comment] 2023-12-21 09:48
> the tag we're sending to the server does not have colons escaped. So we'll need to fix that too since that's how OldDot sends it and we need to maintain compatibility between the two

@amyevans Just to confirm, are we expecting to handle this in the new PR?

**Comment by greg-schroeder** [comment] 2023-12-31 10:32
Assigned @jjcoffee to PR for review

**Comment by jjcoffee** [comment] 2024-01-02 10:38
Just waiting for @amyevans feedback on [this](https://github.com/Expensify/App/issues/32203#issuecomment-1865959671).

**Comment by amyevans** [comment] 2024-01-02 21:36
> @amyevans Just to confirm, are we expecting to handle this in the new PR?

Yes, ideally we could handle that in this PR as well. Please let me know if this is a problem.

And apologies for the delayed response, I'm back from the holidays now!

**Comment by jjcoffee** [comment] 2024-01-03 11:01
@FitseTLT Any thoughts on how feasible it is to handle [this](https://github.com/Expensify/App/issues/32203#issuecomment-1865959671) in your PR?

**Comment by greg-schroeder** [comment] 2024-01-06 00:42
bump on the above @FitseTLT

**Comment by greg-schroeder** [comment] 2024-01-08 20:24
Bump!

**Comment by FitseTLT** [comment] 2024-01-08 20:38
Will handle tomorrow

**Comment by amyevans** [comment] 2024-01-10 22:39
@FitseTLT bump 😄

**Comment by FitseTLT** [comment] 2024-01-11 21:10
@amyevans underscore and lodash `escape` functions do not escape colons I guess you are expecting a manual regex replacement if that is the case should I replace `:` to `\:` or double slash `\\:`??

**Comment by amyevans** [comment] 2024-01-11 22:27
Well currently we've got `tag.name.replace(/\\{1,2}:/g, ':')`, rather than modifying the data that is both displayed to the user in the UI as well as the data that is sent to the API on select, can we leave the underlying name received from the backend unmodified, and only run the replace on the value displayed to the user in the UI? (Am I explaining that in a way that makes sense?)

**Comment by amyevans** [comment] 2024-01-15 17:16
@FitseTLT how's it coming along? What's a reasonable ETA for an updated PR?

**Comment by FitseTLT** [comment] 2024-01-15 17:19
Will update and notify today. Sorry for the delay. 🙏

**Comment by amyevans** [comment] 2024-01-17 19:28
Bump @FitseTLT. If you don't have bandwidth please let me know and we can look to reassign!

**Comment by FitseTLT** [comment] 2024-01-18 13:25
Sorry for the delay guys and Thx for your patience! @jjcoffee PR ready for review

**Comment by jjcoffee** [comment] 2024-01-18 16:40
Perfect, thank you - I'll review tomorrow!

**Comment by greg-schroeder** [comment] 2024-01-22 16:52
This isn't overdue Melvin

**Comment by amyevans** [comment] 2024-01-22 19:02
Apologies for the noise @fedirjh (and others) - wanted to get the correct labels back onto this since I think it affects some of the automation triggers.

**Comment by FitseTLT** [comment] 2024-01-24 12:52
@amyevans @jjcoffee take a 👀 on https://github.com/Expensify/App/issues/30734#issuecomment-1906233860
Looks like SplitBillDetailsPage uses the old confimation list component
https://github.com/Expensify/App/blob/74f11635afab513d3c7cf12b70c286b4f3cd4d74/src/pages/iou/SplitBillDetailsPage.js#L124-L126
I thought it became totally obsolete (replaced by `MoneyTemporaryForRefactorRequestConfirmationList`) that's why I didn't add the cleanup there and I think it will be removed soon but what should we do for now should I raise a quick pr adding the clean up there to ???

**Comment by jjcoffee** [comment] 2024-01-24 13:01
@FitseTLT I'd vote for just adding the cleanup since it's a simple missed case.

**Comment by FitseTLT** [comment] 2024-01-24 13:03
Will raise it now 👍 Is the vids on all platforms still necessary ??

**Comment by amyevans** [comment] 2024-01-24 17:35
Thanks @FitseTLT! At least one platform video, please

**Comment by FitseTLT** [comment] 2024-01-24 17:51
Added Android mWeb videos.

**Comment by jjcoffee** [comment] 2024-02-05 12:43
- The PR that introduced the bug has been identified. Link to the PR: **N/A - behaviour has always been there**
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- Determine if we should create a regression test for this bug. **Yes**
- If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Regression Test Proposal**

1. Create some hierarchial tags for a workspace in the form of "Parent: Child" in oldDot.
2. Go to that workspace's chat on newDot and tap the + in the composer to request money
3. Choose manual and enter any amount and proceed to confirmation page
4. Click Show more and then Tag
5. Search for a hierarchical tag and verify that each tag only displays once in the results.
6. Verify also that the hierarchical tags you have created in (1) appear as "Parent: Child" without any slashes before the colon.
7. Select a hierarchical tag and verify that it displays correctly on the confirmation page, as well as after you submit the request on the request details page.

Do we agree 👍 or 👎

**Comment by greg-schroeder** [comment] 2024-02-06 22:35
Okay ... so this is a super confusing saga related to this. From what I can tell:

- This issue stemmed from a regression from #30734.
- PR 1 for this issue: https://github.com/Expensify/App/pull/32365
- PR 2 for this issue: https://github.com/Expensify/App/pull/35054
- Based on Upwork records, both @jjcoffee and @FitseTLT were paid $500 in #30734

I don't think a regression penalty was actually applied from what I can tell, so based on everything here I don't think we will issue additional payments for this issue, as it's fixing multiple regressions with the same C/C+ involved, who were already paid the full price of the original.

**Comment by greg-schroeder** [comment] 2024-02-06 22:36
filed regression test!

**Comment by jjcoffee** [comment] 2024-02-07 10:07
@greg-schroeder I haven't received any payments on #30734. Since that issue was closed in favour of this one, I just ended the Upwork contract for it, maybe that's where the confusion stems from?

![image](https://github.com/Expensify/App/assets/27287420/0ff93d1e-05be-4850-92e9-f688afd99d30)

**Comment by greg-schroeder** [comment] 2024-02-08 07:14
Hmm. When I looked at this

**Comment by greg-schroeder** [comment] 2024-02-08 07:17
Ah. Well. It shows paid for @FitseTLT:

![image](https://github.com/Expensify/App/assets/29386373/731578ad-cca0-4180-92f7-498de3818f93)

However, you're right, it just shows as `Accepted` for you. That's my bad, I just assumed both had been paid especially given the comments in the linked issue

**Comment by greg-schroeder** [comment] 2024-02-08 07:18
I generated a new offer @jjcoffee - I'll pay ASAP once you accept, sorry about that!

**Closed by greg-schroeder** 2024-02-08 07:18 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug

**Comment by jjcoffee** [comment] 2024-02-08 11:46
@greg-schroeder Haha oh I understand the confusion then, no worries at all! Offer accepted, thanks for looking into it!

**Comment by jjcoffee** [comment] 2024-02-12 15:21
@greg-schroeder Friendly bump to complete the payout on the offer :bow:

**Comment by greg-schroeder** [comment] 2024-02-13 10:11
done, sorry
