### ISSUE TITLE
[HOLD for payment 2024-07-22] [$500] Distance - Search list displays old searched results in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30123] opened 2023-10-21 16:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.88-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go offline
3. Click on FAB> Request money> Distance tab
4. Select Start point
5. Enter any letter into search field

## Expected Result:
Search result should update according to entered letter

## Actual Result:
Search list displays old searched results in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>Windows: Chrome </summary>

 

https://github.com/Expensify/App/assets/78819774/7a45a7ba-2f20-41fc-a547-20c8ad1ed097

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a86156cf627cbc84</li>
        <li>Upwork Job ID: 1715774289180717056</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>cooldev900 | Contributor | 27794398</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by cooldev900** [comment] 2023-10-21 23:07
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
GooglePlacesAutocomplete shows old selected results in offline mode.
### What is the root cause of that problem?
The route cause is that if the app turns to offline state, requestUrl.url becomes null and it couldn't send location filter request to google API. 

https://github.com/Expensify/App/blob/6031f3e3aeaff16749ecc435da8e0ee38053ba7f/src/components/AddressSearch/index.js#L400

https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/ef107387c6846924423b832a242eee83cb07eed4/GooglePlacesAutocomplete.js#L158
```
const [url, setUrl] = useState(getRequestUrl(props.requestUrl));
```
https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/ef107387c6846924423b832a242eee83cb07eed4/GooglePlacesAutocomplete.js#L508-L511
```
 const _request = (text) => {
    _abortRequests();
    if (!url) {
      return;
```

https://github.com/FaridSafi/react-native-google-places-autocomplete/blob/ef107387c6846924423b832a242eee83cb07eed4/GooglePlacesAutocomplete.js#L88-L125
```
  const buildRowsFromResults = useCallback(
    (results, text) => {
      let res = [];
      const shouldDisplayPredefinedPlaces = text
        ? results.length === 0 && text.length === 0
        : results.length === 0;
      if (
        shouldDisplayPredefinedPlaces ||
        props.predefinedPlacesAlwaysVisible === true
      ) {
        res = [
          ...props.predefinedPlaces.filter(
            (place) => place?.description.length,
          ),
        ];

        if (props.currentLocation === true && hasNavigator()) {
          res.unshift({
            description: props.currentLocationLabel,
            isCurrentLocation: true,
          });
        }
      }

      res = res.map((place) => ({
        ...place,
        isPredefinedPlace: true,
      }));

      return [...res, ...results];
    },
    [
      props.currentLocation,
      props.currentLocationLabel,
      props.predefinedPlaces,
      props.predefinedPlacesAlwaysVisible,
    ],
  );
```


And then even if we change the input value, the request won't will be run in request function so dataSource state value doesn't change.
As a result, GooglePlaceAutocomplete compoment shows old search result.

And if we don't search anything and it turns to offline, the predefined places shows in GooglePlaceAutocomplete.

### What changes do you think we should make in order to solve the problem?
We save old selected values and predefined values into temporary state and return filtered result depedning search text so that user can select in offline state.

```const [tempSearchedValue, setTempsearchedValue] = useState([])

  useEffect(() => {
    if (!url) {
      const offlineDataSource = buildRowsFromResults(dataSource)
      setTempsearchedValue(offlineDataSource)
      setDataSource(offlineDataSource)
    } else {
      setTempsearchedValue([])
    }

  }, [url])

  const _request = (text) => {
    _abortRequests();
    if (!url) {
      if (tempSearchedValue.length > 0) setDataSource(offlineDataSource.fiter(value => value.description.toLocaleLowerCase.includes(text.toLocaleLowerCase())))
      return;
    }
```

### What alternative solutions did you explore? (Optional)

We can create a function to save old searched data and predefined places to temporary state in GooglePlacesAutocomplete.js and call it in parent component whenever network state is changed, in this case AddressSearch.js.

**Comment by shubham1206agra** [comment] 2023-10-22 04:00
@cooldev900 This has not been merged yet
https://github.com/Expensify/App/pull/29045

Can you send the video with your solution?

**Comment by shubham1206agra** [comment] 2023-10-22 04:03
If this is an upstream bug, @FaridSafi might help you with this

**Comment by cooldev900** [comment] 2023-10-22 12:41
I will upload the video.

**Comment by cooldev900** [comment] 2023-10-22 13:52
[ice_video_20231022-084232.webm](https://github.com/Expensify/App/assets/13826499/cd0dc235-8825-46cb-a216-1e2a7db4133e)

```
const filteredPredefinedPlaces = useMemo(() => {
        if (!props.network.isOffline || !searchValue) return props.predefinedPlaces
        return props.predefinedPlaces.filter(value => value?.description.toLocaleLowerCase().includes(searchValue.toLocaleLowerCase()))
    }, [
        props.network.isOffline, props.predefinedPlaces, searchValue
    ])

    return (
        /*
         * The GooglePlacesAutocomplete component uses a VirtualizedList internally,
         * and VirtualizedLists cannot be directly nested within other VirtualizedLists of the same orientation.
         * To work around this, we wrap the GooglePlacesAutocomplete component with a horizontal ScrollView
         * that has scrolling disabled and would otherwise not be needed
         */
        <>
            <ScrollView
                horizontal
                contentContainerStyle={styles.flex1}
                scrollEnabled={false}
                // keyboardShouldPersistTaps="always" is required for Android native,
                // otherwise tapping on a result doesn't do anything. More information
                // here: https://github.com/FaridSafi/react-native-google-places-autocomplete#use-inside-a-scrollview-or-flatlist
                keyboardShouldPersistTaps="always"
            >
                <View
                    style={styles.w100}
                    ref={containerRef}
                >
                    <GooglePlacesAutocomplete
                        disableScroll
                        fetchDetails
                        suppressDefaultStyles
                        enablePoweredByContainer={false}
                        predefinedPlaces={filteredPredefinedPlaces}
```

@shubham1206agra @FaridSafi
As a alternative, I showed only how to search predefined places in SearchAddress.js component in offline mode.
I can fix it successfully with @FaridSafi by modifying react-native-google-places-autocomplete.

**Comment by mallenexpensify** [comment] 2023-10-25 13:37
@eVoloshchak , can you please review the above proposal?

**Comment by eVoloshchak** [comment] 2023-10-30 11:32
@cooldev900, thank you for the [proposal](https://github.com/Expensify/App/issues/30123#issuecomment-1773942379)!

There are two ways we could go with this:
1. Implement the approach @cooldev900 is proposing, which is to save the search results we got when online and use them while offline
2. Disable the ability to create a Distance money request while offline 

The problem with the first approach is that we'll be saving only a fraction of places (only those that the user has searched for earlier), so while offline this won't be very useful. Additionally, there will be no clear indication that the search is "restricted" while offline, it will essentially half-work, which is worse than not working at all imo

@mallenexpensify, what do you think?

**Comment by mallenexpensify** [comment] 2023-10-30 22:58
I'm unsure, can you create a post in #expensify-open-source (since #expensify-bugs is being deprecated for External) and tag me in it?  I'll cross-post in the internal distance room.  Thx

**Comment by mallenexpensify** [comment] 2023-11-03 23:10
@eVoloshchak can you create the #expensify-open-source post then drop the link in here?  Thx

**Comment by mallenexpensify** [comment] 2023-11-06 19:43
@eVoloshchak 👀 above plz

**Comment by eVoloshchak** [comment] 2023-11-06 21:15
Started a thread on [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1699305310544239)

**Comment by mallenexpensify** [comment] 2023-11-10 23:27
Thanks for posting @eVoloshchak , if anyone's interested in working on this issue, please review [the chat in #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1699305310544239)

Looking back at the OP
> ## Expected Result:
Search result should update according to entered letter
>
>## Actual Result:
Search list displays old searched results in offline mode

I think we've kinda derailed this convo into discussing what the best flow is.  (which kinda makes sense cuz we want to have an understanding of how everything works).

So... do we want to show results that include the first letter that's typed or just stick with the list of most recent. I'm unsure how much it _matters_ if a user is only able to view the 20 most-recent locations.

**Comment by eVoloshchak** [comment] 2023-11-12 18:26
> do we want to show results that include the first letter that's typed

I think that would be better. It is indeed very minor, but won't be hard to implement, while being useful in some cases

**Comment by cooldev900** [comment] 2023-11-13 03:40
I update my [proposal](https://github.com/Expensify/App/issues/30123#issuecomment-1773942379) following slack discussion.

One problem here is how to handle certain characters like 'Ålesund' when filtering places while offline.
While offline, we can handle certain amout of special characters in frontend but there is no way to convert it through an online service.
Is it possible to add an additional field in the backend to place data for easy filtering? Or is it ok to ignore special characters in filtering places?

[screen-capture (3).webm](https://github.com/Expensify/App/assets/13826499/b0427306-6fa0-49f1-996f-6b7e376c08e3)

**Comment by mallenexpensify** [comment] 2023-11-21 23:34
@eVoloshchak can we move forward with @cooldev900 's proposal above? If not, please provide feedback, thx

**Comment by eVoloshchak** [comment] 2023-11-22 20:10
Yes, let's proceed with @cooldev900's [proposal](https://github.com/Expensify/App/issues/30123#issuecomment-1773942379)
> Or is it ok to ignore special characters in filtering places?

It is ok and I think we already do that for a search in a country picker, I'd be good to re-use this logic (we can work this out on the PR stage)

🎀👀🎀 C+ reviewed!

**Comment by chiragsalian** [comment] 2023-11-23 00:24
proposal LGTM, feel free to create the PR @cooldev900

**Comment by cooldev900** [comment] 2023-11-24 12:54
@lakchote 
Here is the [PR](https://github.com/Expensify/App/pull/31821).

**Comment by neil-marcellini** [comment] 2023-12-01 18:13
Taking over the issue from Chirag as he [authorized here](https://github.com/Expensify/App/pull/31821#issuecomment-1834565580).

**Comment by neil-marcellini** [comment] 2023-12-18 15:06
The latest C+ [comment on the PR](https://github.com/Expensify/App/pull/31821#issuecomment-1859319885) requested some design changes, and this is a new feature, so would you please review the PR from a design perspective?

**Comment by neil-marcellini** [comment] 2023-12-28 20:33
❗ 🔥 Heads up, I'm going to be OOO working 0% from 1/1-1/12/24. I'll be back on 1/15/24. I'm planning to work 50% tomorrow 12/29. Please feel free to un-assign, re-assign, whatever. When I return I'll pick back up whatever I can and do my best to GSD in order of priority. I will also post all of my assigned issues in #engineering-chat in Slack to try to recruit volunteers.

**Comment by neil-marcellini** [comment] 2024-01-17 19:47
The PR has kind of stalled out waiting for one last bug fix, so as I [said in a comment there](https://github.com/Expensify/App/pull/31821#issuecomment-1896555722), I'm going to ask if someone from Callstack can pick it up and bring it over the finish line.

**Comment by neil-marcellini** [comment] 2024-01-17 19:50
Posted on Slack [here](https://expensify.slack.com/archives/C03UK30EA1Z/p1705521005181509) asking for a Callstack person to take it over.

**Comment by pac-guerreiro** [comment] 2024-01-18 16:55
I am Pedro Guerreiro from Callstack - expert contributor group. I’d like to work on this job!

**Comment by neil-marcellini** [comment] 2024-02-24 03:25
How's it going @pac-guerreiro? What can we do to speed this up?

**Comment by mallenexpensify** [comment] 2024-02-27 21:40
> @eVoloshchak Aaaand it should be working now on all platforms! 😅 😅

[From yesterday,](https://github.com/Expensify/App/pull/35045#issuecomment-1965332407) can you review again @eVoloshchak ? Thx

**Comment by pac-guerreiro** [comment] 2024-02-27 23:17
@neil-marcellini Sorry I missed your comment 😅 It should be done by now, just need another review 😄

**Comment by neil-marcellini** [comment] 2024-04-05 18:49
Let's keep this at a weekly cadence. The PR is coming along and it feels like it's finally close.

**Comment by mallenexpensify** [comment] 2024-04-17 15:25
Added to #wave-collect and set Status as Release 1, since that's what's listed on the roadmap doc

**Comment by mallenexpensify** [comment] 2024-05-30 17:15
- https://github.com/Expensify/App/pull/35045

Looks like it's being reverted.

**Comment by neil-marcellini** [comment] 2024-05-31 01:29
@eVoloshchak @pac-guerreiro the PR was reverted, so we need to try again. When can you have another PR up?

**Comment by pac-guerreiro** [comment] 2024-06-01 14:35
@neil-marcellini I can provide one early next week 😄

**Comment by neil-marcellini** [comment] 2024-06-03 23:12
Thanks for the PR @pac-guerreiro. Would you please list out each of the problems that were found when the PR went live and had to be reverted, along with how you're fixing them in the new PR?

It will make it easier to review and make sure that we're not going to repeat the same mistakes.

**Comment by pac-guerreiro** [comment] 2024-06-04 22:42
@neil-marcellini these are the issues that mentioned my previous PR:

1. https://github.com/Expensify/App/issues/42758
- This behaviour was agreed in the previous PR in order to maintain a friendly UX, but if there's the need to change this behaviour, please let me know! cc @arosiclair 

2. https://github.com/Expensify/App/issues/42767
- I applied a fix for this which should restore the previous working UI/UX in all forms

3. https://github.com/Expensify/App/issues/42768
- Same fix as above

**Comment by mallenexpensify** [comment] 2024-06-12 00:26
Contributor+: @eVoloshchak due $500 via NewDot.  

@eVoloshchak plz complete the BZ checklist above.

**Comment by neil-marcellini** [comment] 2024-06-12 16:11
@mallenexpensify there we regressions so I think the payment summary is inaccurate. We're still working on [re-doing the PR](https://github.com/Expensify/App/pull/43011#top)

**Comment by eVoloshchak** [comment] 2024-06-18 15:10
https://github.com/Expensify/App/pull/43011 is close to being merged

**Comment by mallenexpensify** [comment] 2024-06-21 21:12
@eVoloshchak 👀 on the PR, I think it's awaiting testing from ya

**Comment by eVoloshchak** [comment] 2024-06-26 20:45
Not overdue, PR is close to being merged

**Comment by neil-marcellini** [comment] 2024-07-09 19:43
@mallenexpensify the PR was merged so this is awaiting payment now. Looks like the automation failed, would you please handle it manually?

**Comment by mallenexpensify** [comment] 2024-07-11 23:25
Contributor+: @eVoloshchak due $500 via NewDot

With many changes for offline distance bugs, do we want a new test case for this?  I'm unsure

cc @paultsimura  since it's an offline distance issue.

**Comment by mallenexpensify** [comment] 2024-07-22 22:48
@eVoloshchak plz complete the BZ checklist above.

**Comment by eVoloshchak** [comment] 2024-07-24 07:59
- The PR that introduced the bug has been identified. Link to the PR: N/A, this functionality wasn't implemented initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this was already discussed in https://expensify.slack.com/archives/C01GTK53T8Q/p1716990791744559

**Regression Test Proposal**


1. Click on FAB> Submit Expense > Distance tab
2. Select different locations several times to populate the predefined places list
3. Turn off the internet connection
4. Select Start point
5. Start typing into the search field, verify the list is updated according to the search query

**Do we agree 👍 or 👎**

**Comment by mallenexpensify** [comment] 2024-07-26 21:53
Contributor: @ paid $ via Upwork
Contributor+: @eVoloshchak due $500 via NewDot

Test case 
- https://github.com/Expensify/Expensify/issues/415742

Thanks all!

**Closed by mallenexpensify** 2024-07-26 21:53 UTC
Labels: External, Engineering, Daily, NewFeature, Design, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-08-06 23:56
$500 approved for @eVoloshchak
