### ISSUE TITLE
Invoices - Unable to send invoice if the company info is entered in Invoices settings first

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51872] opened 2024-11-01 16:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.56-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh2410006@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace
3. Go to workspace settings > More features
4. Enable Invoices
5. Go to Invoices
6. Add the following information:
Company name - Expensify
Company address - https://staging.new.expensify.com/
7. Go to FAB > Send invoice
8. Send an invoice from the workspace created in Step 2
9. Note that error is shown and the invoice cannot be sent
10. Create another workspace
11. Go to workspace settings and enable Invoices in More features
12. Go to FAB > Send invoice
13. Send an invoice from the new workspace created in Step 10, then add the same company info in Step 6 after the confirmation page

## Expected Result:
User should be able to send invoice when the company name and address are saved in Invoices settings (Step 1 to 9)

## Actual Result:
Error shows up and invoice is not sent when the company name and address are saved in Invoices settings. (Step 1 to 9)
When the same company info is entered when sending info (Step 13), the invoice is sent successfully

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/6e47decf-75e4-44f3-8856-4138684873d1

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2024-11-04 11:38
Downgrading this. It's a [brand new ](https://github.com/Expensify/App/issues/45176)feature. 

@madmax330 @danieldoglas, if you disagree, let me know. I unsubscribed so please tag me.

**Comment by rezkiy37** [comment] 2024-11-05 11:07
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue. Moreover, I am the author of https://github.com/Expensify/App/pull/50571 and consider this as a regression issue.

**Comment by rezkiy37** [comment] 2024-11-05 14:29
That looks like a backend bug as well because happens only with newly created workspaces but not with legacy ones. It relates to https://github.com/Expensify/App/issues/51871 since the backend does not set the company name and website values. Also, the failure data is not used due to the server response. 

<details><summary>Details</summary>
<p>

<img width="1411" alt="Screenshot 2024-11-05 at 13 06 03" src="https://github.com/user-attachments/assets/0bce186a-f3e9-4860-8213-f17bbecc5ce9">
<img width="1294" alt="Screenshot 2024-11-05 at 13 06 23" src="https://github.com/user-attachments/assets/4a93fc00-2158-46ef-98e2-5ce6aa57245c">

</p>
</details> 



cc @madmax330

**Comment by madmax330** [comment] 2024-11-11 18:06
Pr is up

**Comment by madmax330** [comment] 2024-11-19 17:57
This should be fixed now, can we double check?

**Comment by rezkiy37** [comment] 2024-11-20 11:42
The bug has been fixed. It works properly with legacy and newly created workspaces.

<details><summary>Video</summary>
<p>

https://github.com/user-attachments/assets/4b23663e-6b16-4ae8-b4fc-6291c98ab5e3


</p>
</details> 

cc @madmax330

**Comment by madmax330** [comment] 2024-11-20 12:02
Cool, closing

**Closed by madmax330** 2024-11-20 12:02 UTC
Labels: Reviewing, Engineering, Daily, Bug
