### ISSUE TITLE
Random letters and spaces appears in web for the flag and `NEW` emojis added in android

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13928] opened 2023-01-02 16:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app on android app
2. Open Any report
3. Open EmojiPicker, first insert any flag emoji and then insert NEW emoji, again insert flag emoji (use the default Gboard emojis)

## Expected Result: 
Emojis should look normal on android app as well as on windows brower

## Actual Result: 
Emojis are having spaces and letters inserted randomly in between and flags are not visible on windows web app

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Windows/ Chrome (display of emojis is wrong on windows)

**Version Number:** 1.2.46-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/210255853-43a8375b-6bf6-4ff6-a434-80df7ff9adf8.mp4

![image](https://user-images.githubusercontent.com/43996225/210255963-6089cb58-ee0b-498d-bb2a-258f7a90b7c0.png)
<img width="954" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/210255984-ee752ec8-4271-4f69-b4a9-1344e334e3e6.png">

<img src="https://user-images.githubusercontent.com/43996225/210256057-e0600f37-bf11-44ec-bbd9-fb63bd162ede.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree_sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1672487497156249

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by MonilBhavsar** [comment] 2023-01-19 14:16
I tried but couldn't reproduce the issue

https://user-images.githubusercontent.com/32012005/213464804-4c2fa9d2-4a98-4f33-a4a3-170803fffdaa.mp4


@kavimuru could you please test again and see if issue is reproducible, or I am missing something

**Comment by michaelhaxhiu** [comment] 2023-01-19 16:51
Let's ask for help reproducing from the report too from @dhanashree_sawant. Posted in slack

**Comment by michaelhaxhiu** [comment] 2023-01-19 17:04
Seems reproducible still! https://expensify.slack.com/archives/C049HHMV9SM/p1674147148715629?thread_ts=1672487497.156249&cid=C049HHMV9SM

**Comment by michaelhaxhiu** [comment] 2023-01-19 17:11
These should be a candidate for external I think if we agree on proceeding, @MonilBhavsar

**Comment by kavimuru** [comment] 2023-01-19 18:02
@michaelhaxhiu Still able to reproduce. Need to add flag emojis from the device emoji in android app and it looks weird in web

https://user-images.githubusercontent.com/43996225/213524145-220bb7b8-657b-44a4-83cf-b2af0c2a3a99.mp4

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/43996225/213524212-14f16dc6-0b41-42fc-b657-35bc167c0238.png">

**Comment by MonilBhavsar** [comment] 2023-01-20 08:51
> These should be a candidate for external I think if we agree on proceeding, @MonilBhavsar

I would say, we first make sure it is reproducible and steps are clear. It was not reproducible on simulator, or may be I was missing something. @techievivek is helping to test on physical android device

**Comment by techievivek** [comment] 2023-01-20 09:44
On Android, It does seem to render empty spaces randomly. Which feels like a bug to me.

<img src="https://user-images.githubusercontent.com/35863227/213664649-767cdc31-28ac-446a-bdb8-6cb01ff14056.jpeg" height="500" width="250"/>

<img src="https://user-images.githubusercontent.com/35863227/213664677-49ef37e9-f967-42a8-bbfd-12b44112fdb7.jpeg" height="500" width="250"/>

**Comment by MonilBhavsar** [comment] 2023-01-20 09:47
Thanks for testing, but still we're not able to reproduce the issue where random characters and spaces appears instead of emojis. It could be android version specific issue @kavimuru what android version is this?

**Comment by kavimuru** [comment] 2023-01-25 15:46
@MonilBhavsar My android is Galaxy S10 / android  11.0

**Comment by michaelhaxhiu** [comment] 2023-02-01 00:49
This has lulled a little bit and it's partly because I'm not able to reproduce (and nor is Monil). How can we best proceed here when some people can reproduce and others cannot reproduce?

**Comment by michaelhaxhiu** [comment] 2023-02-01 00:50
Posted [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1675212588612489)

**Comment by techievivek** [comment] 2023-02-01 06:57
Unable to reproduce this again on my Oneplus 7T(Android 11) phone.

<img width="1226" alt="Screenshot 2023-02-01 at 12 26 05 PM" src="https://user-images.githubusercontent.com/35863227/215972838-5dd9c3f2-617c-4430-a617-5352f84dbafc.png">
![rn_image_picker_lib_temp_61bc1a57-fa79-420c-ab82-d2ad408e2ba0 jpg](https://user-images.githubusercontent.com/35863227/215972998-ba147b16-e320-4c29-b2b0-1c29d5f20197.jpeg)

**Comment by mountiny** [comment] 2023-02-01 09:59
@MonilBhavsar @michaelhaxhiu this is Windows problem, we saw it in some other bugs as well, Windows does not support the flag emojis so it cannot be rendered well, I would expect the Android issue is the same just with some Android versions not having the same standard for flags.

I recommend to close this issue.

**Comment by michaelhaxhiu** [comment] 2023-02-01 11:54
Thanks for the input @mountiny + @techievivek, very helpful. Closing for now 🙏 

(and wtf Windows, get with the times...) 

<img width=300 src=https://user-images.githubusercontent.com/13206896/216035721-26984c6d-af13-49c0-b8ec-6c699d5c541a.png>

**Closed by michaelhaxhiu** 2023-02-01 11:54 UTC
Labels: Weekly, Bug
