### ISSUE TITLE
[$1000]  App does not display current value on opening date of birth page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23328] opened 2023-07-21 03:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings
3. Open profile
4. Open personal details
5. Open date of birth
6. Reload the page
7. Change year and click save
8. Again open date of birth and observe that app still displays changed year value instead of currently selected value
## Expected Result: 
App should display currently selected value in calendar whenever we open date of birth page
## Actual Result:
 If we reload on date of birth page, change year, save and revisit then app displays changed year value instead of currently selected value

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5d9f4fd4-c333-4506-833c-f1b8ccce58d9

https://github.com/Expensify/App/assets/43996225/b7e07cc0-4a88-47f2-b7cf-1cd6012ee050

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689775123559269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010b252a0c8b8f0528</li>
        <li>Upwork Job ID: 1683848000545353728</li>
        <li>Last Price Increase: 2023-07-25</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-07-24 17:58
Checking what the process is for regression bugs and if we would reopen that intitial issue.

**Comment by zanyrenney** [comment] 2023-07-25 12:14
reproduced. but getting Yowza big file error.

**Comment by zanyrenney** [comment] 2023-07-25 12:14
adding external.

**Comment by zanyrenney** [comment] 2023-07-28 14:18
hey @Santhosh-Sellavel are you able to review those proposals above please?

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 14:28
Sorry somehow missed it

Will do today,

**Comment by Santhosh-Sellavel** [comment] 2023-07-28 23:12
@mountiny What's expected now recently [refactored](https://github.com/Expensify/App/pull/21792) the Date picker

When the year alone is changed the date is not updated correctly.

Consider the first-time user who selects day first, the year is set wrongly and can not change the year alone. We are not showing any errors/hints to the user that the date should be selected to set correctly.

https://github.com/Expensify/App/assets/85645967/deccf8a4-ed63-45ff-b118-61f2b31f4a60

**Comment by mountiny** [comment] 2023-07-31 10:11
@Santhosh-Sellavel This is expected behaviour, the date should be "selected" only by choosing the specific day, until that happens the year and month should not change what is "selected"

**Comment by zanyrenney** [comment] 2023-07-31 11:10
Closing due to expected behaviour as date refactor.

**Closed by zanyrenney** 2023-07-31 11:10 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by mountiny** [comment] 2023-07-31 13:14
@c3024 thanks for raising these concerns. We have lots of discussions about the design of the date picker and this is where we landed aware of these shortcomings its the best we can do achieving cross platform approach and matching the style and pattens of our forms (Save button/ push to page)

If you feel strongly about this, feel free to start a discussion/ feature proposal in Slack to change this
