### ISSUE TITLE
[Awaiting Payment 29th May] [$500] Wrong message appears when the Expensify site is going down

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37565] opened 2024-02-29 19:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @flodnv 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1709063517335079

## Action Performed:
1. Open any chat or go to sign in page when the site is down

## Expected Result:
When the site is down we should show: `We might have a problem. Check out status.expensify.com.`

## Actual Result:
`You appear to be offline` appears confusing the user that they have a network problem when really it's the site. 

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/38435837/20b6ccf3-109a-4276-a9e4-6e8d202ca2af)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ed912188740cf497</li>
        <li>Upwork Job ID: 1764575263440932864</li>
        <li>Last Price Increase: 2024-04-24</li>
    </ul>
</details>

**Comment by godofoutcasts94** [comment] 2024-02-29 20:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wrong message appears when the Expensify site is going down
### What is the root cause of that problem?
The root cause of the problem is here:

https://github.com/Expensify/App/blob/6065c4ed2f9e53438fa726effca52fb274598e72/src/languages/en.ts#L267

 we are displaying text i.e. `You appear to be offline`.
### What changes do you think we should make in order to solve the problem?

Instead, we should replace the text with `It seems like we're having trouble connecting to Expensify`. 
### What alternative solutions did you explore? (Optional)
N/A

### Result 

<img width="343" alt="Screenshot 2024-03-01 at 2 03 51 AM" src="https://github.com/Expensify/App/assets/158435970/c3a432d6-fdc6-4ed7-9ec8-b52cd8730f08">

**Comment by NickTooker** [comment] 2024-02-29 22:31
How about:

>We might have a problem. Check out [status.expensify.com](http://status.expensify.com/).

**Comment by NickTooker** [comment] 2024-03-01 20:31
This is the approved copy @neonbhai. 

>We might have a problem. Check out [status.expensify.com](http://status.expensify.com/).

**Comment by godofoutcasts94** [comment] 2024-03-01 20:35
Are the proposals being reviewed now? @NickTooker

**Comment by trjExpensify** [comment] 2024-03-04 08:54
Sounds like we have the copy, adding `External` to get a C+ assigned.

**Comment by trjExpensify** [comment] 2024-03-04 08:57
We haven't implemented this feature previously, so adding `New feature` label. I've also updated the OP with the expected results copy.

**Comment by godofoutcasts94** [comment] 2024-03-04 09:23
Updated [Proposal](https://github.com/Expensify/App/issues/37565#issuecomment-1971919415) @trjExpensify

**Comment by cubuspl42** [comment] 2024-03-04 09:31
@godofoutcasts94 Interesting, but I don't think we're looking for something this complex

**Comment by cubuspl42** [comment] 2024-03-04 09:31
I approve the proposal by @neonbhai 

C+ reviewed 🎀 👀 🎀

**Comment by godofoutcasts94** [comment] 2024-03-04 10:26
Hey @trjExpensify I think the component `OfflineIndicator.tsx` only deals with the situation when the user is offline i.e. it uses `useNetwork` to just show that if the device is offline or not and w.r.t it will display the message. So I believe that it won't be able to distinguish between Expensify Being Down or the user being offline.

**Comment by trjExpensify** [comment] 2024-03-04 10:41
Cool, so that's not what we want is it, @flodnv? When someone is offline or experiencing local network difficulties "You appear to be offline" is accurate. When our site is down, showing "You appear to be offline" is not accurate, and that's what we're looking to improve here somehow.

**Comment by godofoutcasts94** [comment] 2024-03-04 11:04
> Cool, so that's not what we want is it, @flodnv? When someone is offline or experiencing local network difficulties "You appear to be offline" is accurate. When our site is down, showing "You appear to be offline" is not accurate, and that's what we're looking to improve here somehow.

Hey! What if we make some changes in `useNetwork` hook like this :

```
type NetworkStatus = {
  isSiteDown: boolean; 
};

export default function useNetwork(): NetworkStatus { 

  const [isSiteDown, setIsSiteDown] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      fetch('https://status.expensify.com/')
        .then(res => {
          if (!res.ok) {
            setIsSiteDown(true);
          } else {
            setIsSiteDown(false);
          }
        })
        .catch(() => {
          setIsSiteDown(true);
        });
    }, 10000);

    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (isSiteDown) {
      console.log('We might have a problem. Check out status.expensify.com.');
    }
  }, [isSiteDown]);

  return { isSiteDown };
}
```
The above code is just for reference.

**Comment by cubuspl42** [comment] 2024-03-05 09:58
I'm sorry, I misunderstood the problem.

**Comment by cubuspl42** [comment] 2024-03-05 10:08
I asked on Slack ([in the original bug thread](https://expensify.slack.com/archives/C049HHMV9SM/p1709633265473119?thread_ts=1709063517.335079&cid=C049HHMV9SM) whether we could redefine this issue to just fixing the problem where we "blame" the user for being offline when they are indeed online, without adding any new copies.

**Comment by trjExpensify** [comment] 2024-03-07 11:42
Bumped @flodnv in thread as it was his idea. :)

**Comment by cubuspl42** [comment] 2024-03-08 08:42
It seems that we're likely continue with the original plan (i.e. handling offline and site-is-down separately).

**Comment by cubuspl42** [comment] 2024-03-08 09:14
@tienifr 

Your proposal looks polished and well-thought-out. It makes it clear how you want to solve the problem on the network level, but I'm unsure about the technical part.

I think that the most natural way forward would be to make the code in `NetworkConnection` double-channelled.

One channel for our backend endpoint, one channel for external endpoint. We could manage two flags, `isBackendAvailable` and `isExternalEndpointAvailable`

From these flags, we could conclude (in pseudocode):

```
if isBackendAvailable -> all good
else if isExternalEndpointAvailable -> site's down
else -> you are offline
```

**Problem:**

The [react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/src/index.ts) library is exteremely globals-based. You can't cleanly create two plain-JavaScript instances (`State`s). There's a hook-based API, but we'd prefer a pure JavaScript API in my opinion.

@rayane-djouah

You suggested to use an "isolated" hook-based instance alongside the global instance. It could work, but I really don't feel that hooks are the way to go here.

**Comment by godofoutcasts94** [comment] 2024-03-08 10:18
How about this [comment](https://github.com/Expensify/App/issues/37565#issuecomment-1976325669) @cubuspl42 ??

**Comment by godofoutcasts94** [comment] 2024-03-11 09:01
Hey @cubuspl42! How about my [idea](https://github.com/Expensify/App/issues/37565#issuecomment-1976325669)?

**Comment by cubuspl42** [comment] 2024-03-11 09:02
@rayane-djouah 

> the `useNetInfoInstance()` [hook](https://www.npmjs.com/package/@react-native-community/netinfo#usenetinfoinstance) by default will use native reachability checks, and on platforms which do not [...]

As I understand it, NetInfo **in general** behaves like you described. I just don't think that using any hooks (and the NetInfo-provided hook specifically) is a good idea in the scope of this issue, as in my opinion we're looking for a app-scoped solution that would cleanly fit into the current Expensify code (`NetworkConnection` class in specific).

**Comment by cubuspl42** [comment] 2024-03-11 09:10
@godofoutcasts94 

Sorry, I missed this. Please phrase solutions in the form of proposals in the future, as it makes the process easier.

Honestly, I'd like to touch `useNetwork` as little as possible. It's a hook with a lot of uses, I would presume that often multiple instances of this hook are mounted at the same time. I wouldn't like to do any periodic check on the component scope. Currently, I tend toward a solution put into `NetworkConnection.ts`. I thin we should do everything analogically to what we do now, but...

- fix the logical error of using the backend endpoint for determining `isOffline`
- add new logic (but analogical!) for determining a new boolean Onyx property like `isBackendUnavailable`

**Comment by godofoutcasts94** [comment] 2024-03-11 09:13
> @godofoutcasts94 
> 
> 
> 
> Sorry, I missed this. Please phrase solutions in the form of proposals in the future, as it makes the process easier.
> 
> 
> 
> Honestly, I'd like to touch `useNetwork` as little as possible. It's a hook with a lot of uses, and I presume that multiple instances of this hook are often mounted at the same time. I wouldn't like to do any periodic checks on the component level. Currently, I tend toward a solution put into `NetworkConnection.ts`. I think we should do everything analogically to what we do now, but...
> 
> 
> 
> - fix the logical error of using the backend endpoint for determining `isOffline`
> 
> - add new logic (but analogical!) for determining a new boolean Onyx property like `isBackendUnavailable`

Okay @cubuspl42 thanks for updating

**Comment by cubuspl42** [comment] 2024-03-11 10:34
[NetInfoConfiguration](https://www.npmjs.com/package/@react-native-community/netinfo#netinfoconfiguration)

> `reachabilityUrl`
> 
> The URL to call to test if the internet is reachable. Only used on platforms which do not supply internet reachability natively or if useNativeReachability is false.

Doesn't this invalidate your assumptions?

**Comment by godofoutcasts94** [comment] 2024-03-11 12:07
Updated [Proposal](https://github.com/Expensify/App/issues/37565#issuecomment-1976325669). Please review it @cubuspl42

**Comment by cubuspl42** [comment] 2024-03-12 09:31
@tienifr 

> I see what you mean.
> do you have any other concern if we do it the the other way around?

Likely not, I would encourage you to update your proposal so I can review its final shape.

**Comment by godofoutcasts94** [comment] 2024-03-12 10:35
Updated [proposal](https://github.com/Expensify/App/issues/37565#issuecomment-1971919415) @cubuspl42

**Comment by cubuspl42** [comment] 2024-03-13 09:16
@godofoutcasts94 

>  In NetInfo.addEventListener i.e. here :

Do I understand correctly that you sketched a solution that checks for the backend availability only at the moment when the `NetInfo`-reported Internet availability goes from offline to online or the other way around?

**Comment by cubuspl42** [comment] 2024-03-13 09:20
I approve the proposal by @tienifr.

> This is to make sure if the back-end is unavailable, then the user comes offline, when they come online, we should not show back-end is down

This is a good observation of a potential problem. We should ensure to cover this case, either using the exact suggested approach or something else that comes to us during the PR implementation.

C+ reviewed 🎀 👀 🎀

**Comment by trjExpensify** [comment] 2024-03-18 10:54
PR is in draft, Melv.

**Comment by cubuspl42** [comment] 2024-04-02 08:10
I'm finishing the review

**Comment by mallenexpensify** [comment] 2024-04-24 00:35
@DylanDylann reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks. PR is here:
- https://github.com/Expensify/App/pull/38377

**Comment by DylanDylann** [comment] 2024-04-24 02:07
Thanks. reviewing today

**Comment by trjExpensify** [comment] 2024-05-01 21:01
I've assigned you to the PR @DylanDylann. @tienifr there are conflicts here.

**Comment by trjExpensify** [comment] 2024-05-16 18:51
Hit staging yesterday melv, chill.

**Comment by flodnv** [comment] 2024-05-21 20:31
I did notice the change working last week 😅 👍 🙇

**Comment by mvtglobally** [comment] 2024-05-22 04:30
Issue not reproducible during KI retests. (First week)

**Comment by trjExpensify** [comment] 2024-05-28 15:51
Payment summary for tomorrow as follows:

- $500 to @tienifr for the implementation
- $500 to @DylanDylann for the C+ review

**Comment by mvtglobally** [comment] 2024-05-30 01:34
Issue not reproducible during KI retests. (Second week)

**Comment by trjExpensify** [comment] 2024-05-30 01:52
Offers sent!

**Comment by trjExpensify** [comment] 2024-05-30 12:33
Paid, @tienifr! @DylanDylann, I think you need to accept? 🤔

**Comment by DylanDylann** [comment] 2024-05-31 17:24
@trjExpensify Accepted! Thanks

**Comment by trjExpensify** [comment] 2024-05-31 18:22
Paid!

**Closed by trjExpensify** 2024-05-31 18:22 UTC
Labels: External, Daily, NewFeature, Waiting for copy, Awaiting Payment
