### ISSUE TITLE
[$500] Expense - Total amount disappears or changes to number briefly when a new scan request is created

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34507] opened 2024-01-15 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Create a new workspace
2. Go to the workspace chat
3. Create a scan request
4. Wait in the main chat for the scanning to complete
5. After the scanning is complete, create another scan request
6. Repeat Step 4 and 5 one more time. (maybe need more tries if the amount in expense preview does not disappear or change to something else)
7. Create a new workspace (so that the new workspace name is appended with number 2)
8. Repeat Step 2 - 5 two or three times

## Expected Result:
The total amount in the expense preview in the main chat will not disappear or change when scan request is created

## Actual Result:
After creating scan request a few times, the total amount in the expense preview disappears or changes to just a number.
It is discovered that when the workspace name is not appended with a number (like the very first workspace), the total amount will disappear briefly when a scan request is created
When the workspace name has a number, like Applause Workspace 2 or 3, the total amount will change to the workspace number briefly when a new scan request is created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![296312069-0db6675b-8433-468a-b16f-badd8a20e307](https://github.com/Expensify/App/assets/78819774/fb066efe-7a7f-4920-a944-5d4559aeab00)

https://github.com/Expensify/App/assets/78819774/ec3e0206-7333-4e33-9bb4-be6c6269633a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01518f15bfe90e0e4a</li>
        <li>Upwork Job ID: 1746912280039006208</li>
        <li>Last Price Increase: 2024-01-15</li>
    </ul>
</details>

**Comment by abzokhattab** [comment] 2024-01-15 16:54
not reproducible on my account, are you still able to reproduce it ?

**Comment by abekkala** [comment] 2024-01-17 18:20
not able to reproduce. Closing

**Closed by abekkala** 2024-01-17 18:20 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
