### ISSUE TITLE
[$250] Group chat – Group avatar photo changes to default after relogin

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44083] opened 2024-06-20 14:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.86-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_1@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Create a group and upload avatar photo
4. Log out
5. Log in with the same account and find a group in LHN

## Expected Result:
Group chat is with photo avatar

## Actual Result:
Group avatar photo changes to default after relogin. Photo appears when open the group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e6375188-73b4-4204-b52c-dff6decf0c7a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011b1f3bc6eeb8016f</li>
        <li>Upwork Job ID: 1803874883740630335</li>
        <li>Last Price Increase: 2024-06-20</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-06-20 14:41
@greg-schroeder  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by devalirzayev** [comment] 2024-06-21 10:32
The cause of this issue is server/back-end side. `api/OpenApp` endpoint does not return `avatarUrl` for groups. From my understanding we don't have an access to server-side.

**Comment by devalirzayev** [comment] 2024-06-21 11:03
> The cause of this issue is server/back-end side. `api/OpenApp` endpoint does not return `avatarUrl` for groups. From my understanding we don't have an access to server-side.

@suneox as I have stated this is backend bug. Needs internal reviewing.

Please see screenshot. Selected report (which is group chat) has `avatarUrl` and returns when opened (`OpenReport` endpoint) but in `OpenApp` endpoint it does not.

![image](https://github.com/Expensify/App/assets/62056172/61c8c2d6-ae8b-4f86-aaf5-33139a3c622c)

**Comment by greg-schroeder** [comment] 2024-06-25 00:51
Okay so this is going to require an internal engineer, will set as Hot Pick as root cause was determined

**Comment by greg-schroeder** [comment] 2024-06-25 01:11
go away Melvin

**Comment by greg-schroeder** [comment] 2024-06-25 01:11
Go away Melvin

**Comment by greg-schroeder** [comment] 2024-07-08 12:48
Still waiting for an internal engineer to pick this up

**Comment by greg-schroeder** [comment] 2024-07-16 22:14
Same as above

**Comment by greg-schroeder** [comment] 2024-08-06 13:30
Same as above

**Comment by greg-schroeder** [comment] 2024-08-14 10:35
Same as above

**Comment by greg-schroeder** [comment] 2024-08-27 05:29
Still waiting for an internal engineer to take on

**Comment by greg-schroeder** [comment] 2024-09-05 04:14
Same as above

**Comment by yuwenmemon** [comment] 2024-09-05 06:08
I'm not able to reproduce this on dev or prod - has anyone been able to?
![Screenshot 2024-09-04 at 11 03 49 PM](https://github.com/user-attachments/assets/288ae2fd-6251-4654-950d-623be64a1a89)
![Screenshot 2024-09-04 at 11 04 36 PM](https://github.com/user-attachments/assets/c75f71e4-a3fb-408b-87bb-8651ba5327f3)
![Screenshot 2024-09-04 at 11 04 33 PM](https://github.com/user-attachments/assets/40933512-acd8-420e-9a5d-a1ead402225e)
assets/4072be9f-0561-4ef2-bf57-a242fe2c164e)
![Screenshot 2024-09-04 at 11 06 16 PM](https://github.com/user-attachments/assets/a24e2612-00e0-4062-a558-8ed5825d8c8c)

**Comment by yuwenmemon** [comment] 2024-09-05 06:13
In fact, I see the avatarUrl for the Group in the OpenApp response when retesting this:
![Screenshot 2024-09-04 at 11 11 54 PM](https://github.com/user-attachments/assets/1dbc3223-ea9f-4c1f-9588-cc03f99eb44e)

So I'm going to call this fixed and close it out.

**Closed by yuwenmemon** 2024-09-05 06:13 UTC
Labels: Weekly, Internal, Bug
