### ISSUE TITLE
[$1000]  The text "Chat report" is temporarily displayed in the Task title position

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20063] opened 2023-06-02 15:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Go to "Assign Task" section
3. Enter the task title and click on the "Next" button
4. Click on "Assignee" and select a user
5. Click on "Confirm task"
## Expected Result: 
The text "Chat report" should not be displayed in the Task title position
## Actual Result: 
After creating a task, the text "Chat report" is temporarily displayed in the Task title position

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.22
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fe002cd4-8139-4d16-a687-8073a39e783c

https://github.com/Expensify/App/assets/43996225/43835219-9e49-42bd-bd24-0bfe3ada1d46

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685134842254209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018549030b7de49763</li>
        <li>Upwork Job ID: 1664669801894019072</li>
        <li>Last Price Increase: 2023-06-16</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-06-02 19:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text "Chat report" is temporarily displayed in the Task title position

### What is the root cause of that problem?
I think there are two issues here
1. In `ReportScreen` component `fetchReportIfNeeded` is not preventing unnecessary call for api
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/ReportScreen.js#L195-L212
this is because `this.props.report.reportID` is not the same as `getReportID(this.props.route)` for a short time, thus resulting on calling `Report.openReport` function

2. This is weird, and I am not sure why it is happening. When we call `Report.openReport` `lodashGet(allReports, [reportID])` is not able to find existing report based on `reportID` Even if it exists, I logged everything in the console and made sure I am not hallucinating.  It is happening just one time when we create task report.
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/libs/actions/Report.js#L342
### What changes do you think we should make in order to solve the problem?
We should remove `this.props.report.reportID === getReportID(this.props.route)` from here
https://github.com/Expensify/App/blob/fc30ddc7a6877b3c690fe2ccdb8275403e019c54/src/pages/home/ReportScreen.js#L207

Since we might have `reportID` which indicates we have report data locally but `reportID` and id in route may not match

### What alternative solutions did you explore? (Optional)

**Comment by kushu7** [comment] 2023-06-02 19:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The text "Chat report" is temporarily displayed in the Task title position.

### What is the root cause of that problem?
We are creating a new task and navigating to report page. problem is that `optimisticData` data doesn't get set to onyx within time-frame i guess. each time i got report `undefined` after navigating to report after creating task.
https://github.com/Expensify/App/blob/f494977b841cda8118043c81711cf2f323b604c1/src/libs/actions/Task.js#L155-L170
We get report undefined in that case. we use fallback `REPORT.DEFAULT_REPORT_NAME` as title.
https://github.com/Expensify/App/blob/65d9ceb6f5fd6d8b02b8ddc7a5071768d7dbe1c9/src/libs/actions/Report.js#LL327C15-L327C15
### What changes do you think we should make in order to solve the problem?
We can solve it by using `setTimeout` of 10ms while navigating to report page. it will solve our problem.
https://github.com/Expensify/App/blob/f494977b841cda8118043c81711cf2f323b604c1/src/libs/actions/Task.js#L170
we can move this into `setTimeout`
```js
 setTimeout(()=>{
        Navigation.navigate(ROUTES.getReportRoute(optimisticTaskReport.reportID));
    },10)
```
It will not create any performance issue.


### What alternative solutions did you explore? (Optional)
None

**Comment by MrJithil** [comment] 2023-06-04 10:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
While user create a new task, the `Chat Report` title showing as the task title for  short time.

### What is the root cause of that problem?
The `openReport` function calling `lodashGet` with a default value of `CONST.REPORT.DEFAULT_REPORT_NAME` which is `Chat Report` to create `optimisticReportData`.

Once the Create Task api calls completed, the new data will be updated.

### What changes do you think we should make in order to solve the problem?

Some small modification to the `openReport` action of `Report.js`. 

If we can modify the `openReport` as below to accept the `reportName`, this problem will be solved. 
```
function openReport(reportID, ...., reportName = CONST.REPORT.DEFAULT_REPORT_NAME) {
```
Since we are setting the `CONST.REPORT.DEFAULT_REPORT_NAME` to the `reportName` as a default value, it will not break the existing functionality.

Please note, if needed, we can wrap the params of `openReport` in an object `openReportParams` and de-structure it if there is a concerns of adding more params .

### What alternative solutions did you explore? (Optional)

**Comment by flaviadefaria** [comment] 2023-06-05 14:10
@mananjadhav any thoughts on the proposals above?

**Comment by mananjadhav** [comment] 2023-06-07 08:54
Please allow me a day to review. I am unwell and would be offline most of the day.

**Comment by mananjadhav** [comment] 2023-06-09 16:04
Reviewing the proposals. I need to verify the condition once, and then will decide which proposal to use.

We definitely don’t want to use setTimeout, and I am sure removing the reportId === condition could cause regressions.

**Comment by MrJithil** [comment] 2023-06-12 05:53
@mananjadhav I just investigated this case on my local machine again, I was also not able to reproduce it. While comparing to the proposal I made against the current source code, I can see thi issue has been fixed by the PR https://github.com/Expensify/App/pull/20335

So, this is not an issue anymore. 

The other issue you mentioned is a different case. I guess, there are tickets opened for fixing the over height already in many places. Not sure completely.

**Comment by mananjadhav** [comment] 2023-06-14 20:10
@kavimuru @techievivek  did you get a chance to look at this [comment](https://github.com/Expensify/App/issues/20063#issuecomment-1584955094)?

**Comment by techievivek** [comment] 2023-06-19 04:11
@mananjadhav 
> @kavimuru @techievivek did you get a chance to look at this https://github.com/Expensify/App/issues/20063#issuecomment-1584955094?

Taking a look, sorry I missed the ping.

**Comment by techievivek** [comment] 2023-06-19 05:12
I am unable to reproduce this, @kavimuru Can you please try reproducing this?

**Comment by flaviadefaria** [comment] 2023-06-19 15:20
It seems like this has been fixed as mentioned [here](https://github.com/Expensify/App/issues/20063#issuecomment-1586628518) so let's go ahead and close this.

**Closed by flaviadefaria** 2023-06-19 15:20 UTC
Labels: External, Daily, Help Wanted, Bug
