### ISSUE TITLE
Search - No "Show x of y" at the end of Search list

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36033] opened 2024-02-07 15:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-38.0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is logged into account that has more than 500 contacts
1. Go to staging.new.expensify.com
2. Click on the search bar
3. Scroll to the end of the list

## Expected Result:
The Search list will show the first 500 contacts, and the rest will be hidden with "Show x of y" button

## Actual Result:
The Search list displays all the contacts in one list without "Show x of y" button

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ba4955ff-49a4-4b36-9977-5a5c0baedebd

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-07 15:32
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by rlinoz** [comment] 2024-02-07 17:00
I think this might be intended behavior, asking on slack

**Comment by Julesssss** [comment] 2024-02-08 11:19
Not a blocker. Removing the label to unblock the deploy and our big VSB-VIP announcement.

**Comment by cristipaval** [comment] 2024-02-08 11:40
Let's hold this one on https://github.com/Expensify/App/issues/36121

**Comment by rlinoz** [comment] 2024-02-12 12:35
@cristipaval maybe we can close this one in favor of the #36121 ?

**Comment by cristipaval** [comment] 2024-02-12 14:25
yes I think we could close it 👍

**Comment by rlinoz** [comment] 2024-02-12 18:36
Great, closing because https://github.com/Expensify/App/issues/36033#issuecomment-1938598949

**Closed by rlinoz** 2024-02-12 18:36 UTC
Labels: Engineering, Daily
