### ISSUE TITLE
[HOLD for payment 2024-06-11] App crashes due to trying to access accountIdToName prop in epensimark on an undefined variable

### ISSUE THREAD

**Issue by iwiznia** [Expensify/App#42161] opened 2024-05-14 15:47 UTC
Context https://expensify.slack.com/archives/C04878MDF34/p1715699038416249

![image](https://github.com/Expensify/App/assets/521248/c69b1bb8-248c-4a69-8020-f3daafc36396)

![image](https://github.com/Expensify/App/assets/521248/4bcaa659-aa9a-47d3-87cf-a73896f4d9c1)

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by war-in** [comment] 2024-05-14 15:48
Hi, I'm Marcin from Software Mansion and I would like to work on this

**Comment by twisterdotcom** [comment] 2024-05-14 23:24
Doesn't look like I'm needed here as no C+ reviewed these PRs, but LMK if anybody needs paying.

**Comment by ahmedGaber93** [comment] 2024-05-14 23:45
@robertKozik @war-in I think we still have a type error as [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.js#L494) we use `accountIdToName` with `Id`, but its type [here](https://github.com/Expensify/expensify-common/blob/18fa764be9d68f72b48d238dcc20f2b0ca8f1147/lib/ExpensiMark.d.ts#L39) defines as `accountIDToName` with `ID`

**Comment by robertKozik** [comment] 2024-05-15 09:35
Yeah you're right, there is typo in the types. I'll spin up the PR soon

**Comment by MonilBhavsar** [comment] 2024-05-31 16:27
We've reverted PR https://github.com/Expensify/App/pull/42176 that updated expensify-common version in the App, because it caused multiple crashes.

The crash will happen again if we update expensify-common version in the App for some reason. Can anyone please fix the issue from root cause i.e. in expensify-common please. Thanks!

**Comment by twisterdotcom** [comment] 2024-05-31 16:38
Who is responsible for this now @iwiznia or @war-in - or should we take this `External` for some help?

**Comment by iwiznia** [comment] 2024-05-31 21:30
@war-in said they would work on it and I assigned them.

**Comment by twisterdotcom** [comment] 2024-06-03 08:59
Nice, okay @war-in let us know if you need any help here.

**Comment by war-in** [comment] 2024-06-03 13:03
@iwiznia @twisterdotcom I've found what the bug is. [This PR](https://github.com/Expensify/expensify-common/pull/696) introduced `Log` to `expensify-common` (ExpensiMark.js) and it turned out it doesn't work on mobile (jquery is not present there).
To quick-fix it we can change `Log.alert` to `console.warn` as the information provided by the Logger won't be helpful until [my PR](https://github.com/Expensify/App/pull/40565) enabling editing mentions is merged. 

Please share your thoughts 🙏

**Comment by iwiznia** [comment] 2024-06-03 16:38
> nd it turned out it doesn't work on mobile (jquery is not present there).

I don't get this. What part of `Log.alert` uses jquery?

**Comment by war-in** [comment] 2024-06-03 16:44
Based on this error I found the [line](https://github.com/Expensify/expensify-common/blob/5002fbf08655a81015e5af12bbf0a8cd4c700637/lib/Network.jsx#L108) which uses jquery. Network is used by `Log.alert`


https://github.com/Expensify/App/assets/61014013/94917028-8c17-4186-8bf1-607114ae5d7b

**Comment by iwiznia** [comment] 2024-06-03 16:47
Hmmmm why is it using that? We call `Log.alert` in app already. I think the OG PR imported the wrong log library. It imported `Log.jsx` and should've imported `Logger.jsx`?

**Comment by blazejkustra** [comment] 2024-06-03 16:47
I think the callstack looks like this:
```
$.ajax(...);
Network.post(...)
API.performPOSTRequest(...)
API.logToServer(...)
Logger.serverLoggingCallback(...)
Logger.logToServer(...)
Logger.add(...)
Log.alert(...)
```

Where `serverLoggingCallback` in this case is defined in `lib/Log.jsx`:
```ts
function serverLoggingCallback(logger, params) {
    return API(Network('/api/')).logToServer(params);
}

export default new Logger({
    serverLoggingCallback,
    clientLoggingCallback,
    isDebug: isWindowAvailable() ? window.DEBUG : false,
});
```

**Comment by iwiznia** [comment] 2024-06-03 16:48
The `Log` we use in App is defined [here](https://github.com/Expensify/App/blob/49657feb7626948e1be843c62c209414c81dc4fc/src/libs/Log.ts#L67) 🤔

**Comment by blazejkustra** [comment] 2024-06-03 16:49
The `Log` in `expensify-common` uses `Logger`:
```ts
export default new Logger({
    serverLoggingCallback,
    clientLoggingCallback,
    isDebug: isWindowAvailable() ? window.DEBUG : false,
});
```

**Comment by blazejkustra** [comment] 2024-06-03 16:53
Looking at the code `serverLoggingCallback` won't work on mobile because it is using `jquery`, and `clientLoggingCallback` doesn't really differ from using console.warn as suggested [here](https://github.com/Expensify/expensify-common/pull/711) 🤔

**Comment by ikevin127** [comment] 2024-06-04 18:17
1st PR for this was reverted.

**Comment by sonialiap** [comment] 2024-06-10 11:20
I can't access a chat with a client, possible same issue https://github.com/Expensify/Expensify/issues/403390

**Comment by iwiznia** [comment] 2024-06-10 11:37
@war-in @blazejkustra we are missing re-updating the version of expensify commons the App uses, no?

**Comment by war-in** [comment] 2024-06-10 13:23
Afaik @blazejkustra updated the `expensify-common` in this [PR](https://github.com/Expensify/App/pull/42387). It includes a fix for this bug. 
And I'm almost finished with the mentions editing PR [here](https://github.com/Expensify/App/pull/40565)

**Comment by twisterdotcom** [comment] 2024-06-11 16:46
Okay, Is this ready for payment yet or not? Does it even _need_ payment? Perhaps only for @ikevin127 somewhere?

**Comment by ikevin127** [comment] 2024-06-11 17:40
@twisterdotcom I reviewed the initial PR as C+ but it was reverted in https://github.com/Expensify/App/pull/42914, therefore no payment is due here and the hold for payment can be removed.

Not sure if I'm still needed as reviewer for PR number 2 🤔

**Comment by sonialiap** [comment] 2024-06-13 11:18
I was able to load the chat today without issue 😁 thank you for the fix!

**Comment by twisterdotcom** [comment] 2024-06-13 12:37
Looks like it was internally reviewed. Okay, closing this then.

**Closed by twisterdotcom** 2024-06-13 12:37 UTC
Labels: Daily, Awaiting Payment, Bug
