### ISSUE TITLE
[DUPE, PAY SYED] [Distance] - Distance amount is displayed in the manual request money section

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26979] opened 2023-09-07 18:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click the "+" icon.
2. Select "Request money" and then choose "distance."
3. Choose the starting and finishing points.
4. Proceed by clicking the "Next" button.
5. Navigate back and check the manual request money section

## Expected Result:
The Distance amount should not be visible in the manual request money section

## Actual Result:
The Distance amount is also displayed in the manual request money section.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65.6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/66f2a3ef-dfb6-492f-acb0-184362c0815a

https://github.com/Expensify/App/assets/93399543/3857c562-467c-430b-a33e-ab79d42f9c8a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693768556147929

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-09-07 19:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Distance amount is displayed in the manual request page

### What is the root cause of that problem?

When tapping the tab button, we reset the money request info
https://github.com/Expensify/App/blob/5fbee526e285eab93721a95fa6a05ea3fdbf946c/src/pages/iou/MoneyRequestSelectorPage.js#L66

So the amount is set back to 0 and the [MoneyRequestAmountForm](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestAmountForm.js) receives the updated amount value(0).

The problem is here
https://github.com/Expensify/App/blob/5fbee526e285eab93721a95fa6a05ea3fdbf946c/src/pages/iou/steps/MoneyRequestAmountForm.js#L102-L114

When `!amount` is true, we don't update the `currentAmount`.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to update the `currentAmount` when amount is 0 as well.
Remove the `!amount` condition above and update the `amountAsStringForState` as below
```
    useEffect(() => {
        if (!currency) {
            return;
        }
        const amountAsStringForState = amount ? CurrencyUtils.convertToFrontendAmount(amount).toString() : '';
        ...
    }, [amount]);
```

This works as expected
<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by akinwale** [comment] 2023-09-07 19:49
This is a duplicate of https://github.com/Expensify/App/issues/26945.

**Comment by ayazhussain79** [comment] 2023-09-07 20:40
Can anyone confirm which issue was reported first? I reported this one on September 4th, and what about the #26944 issue?

**Comment by jliexpensify** [comment] 2023-09-07 22:41
Hi @ayazhussain79 the other bug was reported by Applause's Internal QA process. I'm happy to close this issue as the dupe and pay you the $50 in Upworks.

**Comment by jliexpensify** [comment] 2023-09-07 22:41
@s-alves10 - since this issue will be closed, if you haven't already, please post your proposal in https://github.com/Expensify/App/issues/26945

**Comment by jliexpensify** [comment] 2023-09-07 22:46
Payment Summary:

- Bug Reporter: @ayazhussain79 $50

[Upworks job](https://www.upwork.com/jobs/~01b9272b85032acfcc)

**Comment by ayazhussain79** [comment] 2023-09-08 06:32
@jliexpensify Ok offer accepted. Thank you

**Comment by jliexpensify** [comment] 2023-09-10 11:50
Paid and job removed.

**Closed by jliexpensify** 2023-09-10 11:50 UTC
Labels: Daily, Bug
