### ISSUE TITLE
[$500] Dev: Web - Hides the RHP on press CTRL+K

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27621] opened 2023-09-17 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press CTRL+shift +K
2. press  CTRL+K
3. Press CTRL+shift +K

## Expected Result:
It should show new chat option

## Actual Result:
Hides the RHP

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.70.5
**Reproducible in staging?:** n
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/b16f7f7a-f7ee-4628-977d-1f19f86167e8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694841534399289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a4c71c5218b98275</li>
        <li>Upwork Job ID: 1703449242421612544</li>
        <li>Last Price Increase: 2023-09-17</li>
    </ul>
</details>

**Comment by Pluto0104** [comment] 2023-09-17 19:17
I can't reproduce it.

**Comment by PiyushChandra17** [comment] 2023-09-17 19:43
@Pluto0104 same here

**Comment by lschurr** [comment] 2023-09-18 00:40
@situchan are you able to reproduce this?

**Comment by situchan** [comment] 2023-09-18 00:42
> @situchan are you able to reproduce this?

No, I also [asked](https://expensify.slack.com/archives/C049HHMV9SM/p1694981099180269?thread_ts=1694841534.399289&cid=C049HHMV9SM) @gadhiyamanan on slack

**Comment by lschurr** [comment] 2023-09-21 00:24
Any update @situchan? Should we close this?

**Comment by situchan** [comment] 2023-09-21 01:11
Let's close

**Closed** 2023-09-21 02:06 UTC
Labels: External, Daily, Help Wanted
