### ISSUE TITLE
[Awaiting checklist completion] [$500] Request money - Calendar is showing the wrong date

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31416] opened 2023-11-16 02:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to + > Request money > Manual
3. Enter an amount and click Next
4. Select a participant and proceed to the next page
5. Click Show more
6. Click Date

## Expected Result:
The calendar is accurate

## Actual Result:
The calendar is inaccurate. The dates are one day ahead. The week on the calendar starts from Monday to Sunday instead of Sunday to Saturday

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

![cal](https://github.com/Expensify/App/assets/78819774/45e0fd6e-889c-410b-97c7-4a36ccdaa246)

https://github.com/Expensify/App/assets/78819774/de8ffb1a-718c-4b33-a8ae-48330f5f4f5e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0135c08e4c75c14697</li>
        <li>Upwork Job ID: 1724983985857425408</li>
        <li>Last Price Increase: 2023-11-16</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 27749707</li>
<li>barros001 | Contributor | 27749708</li>
</ul></li>
    </ul>
</details>

**Comment by barros001** [comment] 2023-11-16 03:10
😶‍🌫️## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Calendar / DatePicker weekdays header is off, ahead by one day.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/5e01376b6648410c95bcaf0ee487d6e8cde259b2/src/libs/DateUtils.ts#L148-L151

Code assumes week starts on Monday when it actually starts on Sunday.

### What changes do you think we should make in order to solve the problem?

```js
    const startOfCurrentWeek = startOfWeek(new Date(), {weekStartsOn: 0}); // Assuming Sunday is the start of the week
    const endOfCurrentWeek = endOfWeek(new Date(), {weekStartsOn: 0}); // Assuming Sunday is the start of the week
```

Update the start of the week to Sunday.



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by barros001** [comment] 2023-11-16 03:20
😶‍🌫️## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Calendar / DatePicker weekdays header is off, ahead by one day.

### What is the root cause of that problem?

https://github.com/Expensify/App/blob/5e01376b6648410c95bcaf0ee487d6e8cde259b2/src/libs/DateUtils.ts#L148-L151

Code assumes week starts on Monday when it actually starts on Sunday.

### What changes do you think we should make in order to solve the problem?

```js
    const startOfCurrentWeek = startOfWeek(new Date(), {weekStartsOn: 0}); // Assuming Sunday is the start of the week
    const endOfCurrentWeek = endOfWeek(new Date(), {weekStartsOn: 0}); // Assuming Sunday is the start of the week
```

Update the start of the week to Sunday.



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by techdevelopers08** [comment] 2023-11-16 06:30
I will review the date calculation logic in your code and will ensure that the dates are being calculated accurately. If the dates are consistently one day ahead, there might be an offset in your date calculations.
Verify that your application is handling time zones correctly. Inconsistencies in time zone handling can lead to date discrepancies. I I I will ensure that the server and client are configured to use the same time zone.
If you're using any third-party calendar libraries, make sure they are up to date
Steps:
step 1 -> we have to find calendarView in project 
step 2 -> In calendarView we have to set US locale (US locale start from Sunday to Saturday ) because in android device Calendar depends on Locale and in your case may be locale working automatically according to location

**Comment by techdevelopers08** [comment] 2023-11-16 06:45
Contributor details
Your Expensify account email: mailto:gagan.khatter@techangouts.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a2fb06a184aba281

**Comment by barros001** [comment] 2023-11-16 11:52
## Proposal

[Updated](https://github.com/Expensify/App/issues/31416#issuecomment-1813728665)

Added more details

**Comment by techdevelopers08** [comment] 2023-11-17 06:59
I updated the details [here](https://github.com/Expensify/App/issues/31416#issuecomment-1813863018)

**Comment by twisterdotcom** [comment] 2023-11-20 09:20
@techdevelopers08 please complete the task here: https://github.com/Expensify/App/issues/31416#issuecomment-1813863018

@0xmiroslav let us know if any of these proposals are good to go today please.

**Comment by techdevelopers08** [comment] 2023-11-20 09:39
@twisterdotcom I've updated my contribution details already [here](https://github.com/Expensify/App/issues/31416#issuecomment-1813862982). Please update me if I missed anything.

**Comment by twisterdotcom** [comment] 2023-11-20 10:29
@techdevelopers08 you must post it as a single comment on its own for our automation to remember it.

**Comment by techdevelopers08** [comment] 2023-11-20 10:38
Contributor details
Your Expensify account email: ajay@techangouts.com
Upwork Profile Link: https://www.upwork.com/freelancers/ajaychaudhary11

**Comment by MonilBhavsar** [comment] 2023-11-20 12:12
Sounds good, let's fall back to Monday as default following the ISO convention - 

`The International Organization for Standardization (ISO) also follows this convention in its standard ISO 8601, where Monday is considered the first day of the week.`

**Comment by barros001** [comment] 2023-11-20 14:25
@tienifr why create a method instead of updating the numbers in the code below?

``` js
  // Add null values for days before the first day of the month
    for (let i = 1; i < getDay(firstDayOfMonth); i++) { // changed starting value for I to 1
        currentWeek.push(null);
    }

        // Start a new row when the current week is full
        if (getDay(currentDate) === 0) { // changed to 0
            matrix.push(currentWeek);
            currentWeek = [];
        }
```

Instead of hard coding, we set a couple of constants: `startOfTheWeek = 1; endOfTheWeek = 0;`and use them accordingly:

``` js
  // Add null values for days before the first day of the month
    for (let i = startOfTheWeek; i < getDay(firstDayOfMonth); i++) { // changed starting value for I to 1
        currentWeek.push(null);
    }

        // Start a new row when the current week is full
        if (getDay(currentDate) === endOfTheWeek) { // changed to 0
            matrix.push(currentWeek);
            currentWeek = [];
        }
```

we can put these constants at the top of the file and that would make it more obvious for devs what’s happening here. 

Just my thoughts.

**Comment by barros001** [comment] 2023-11-20 16:47
I disagree.  IMO, the `getDayWithWeekStartsOn` is hard to understand. It modifies the standard behavior (0 is no longer Sunday) of a function and that could lead to confusion down the line. Having a separate configuration constant (hardcoded for now, but could be made dynamic down the line if needed) more explicitly communicates the intention of the code for people coming back to it later on.

But anyways, it looks like the decision to hardcode it to Monday has been made (my original proposal, before edits, said we should use Sunday, as I'm US based and that's when my week starts and the matrix started on Sunday as well. I edited once I realized Europe and other places start on Monday). I'll let @0xmiroslav and the rest of the team decide if the contributor should be re-assigned or not. If it's decided that it should, I'm fine with the decision and I'll accept it as being the best for the project.

**Comment by barros001** [comment] 2023-11-23 16:47
@0xmiroslav there has been more [discussion on slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1700754871079609?thread_ts=1700483443.288289&cid=C01GTK53T8Q) about this and we're moving forward with Monday. The raised [PR](https://github.com/Expensify/App/pull/31641) stands and we're good for review.

**Comment by barros001** [comment] 2023-12-01 20:25
@0xmiroslav just wanted to check if you had a chance to review the PR.

**Comment by barros001** [comment] 2023-12-01 20:31
master merged

**Comment by barros001** [comment] 2023-12-12 11:15
@0xmiroslav just checking again on this.

**Comment by barros001** [comment] 2023-12-19 09:42
@0xmiroslav do you think you can review the PR this week? This issue is pretty important IMO and we should try and get this pushed out quickly.

cc: @MonilBhavsar @twisterdotcom

**Comment by twisterdotcom** [comment] 2024-01-05 15:29
Payment Summary:

- @barros001 paid $500 [here](https://www.upwork.com/nx/wm/offer/27749708) (Contributor)
- @0xmiroslav paid $500 [here]](https://www.upwork.com/nx/wm/offer/27749707) (Reviewer)

Awaiting checklist completion from @0xmiroslav now.

**Comment by twisterdotcom** [comment] 2024-01-11 22:01
Refund of $250 from @barros001 [here](https://www.upwork.com/nx/wm/give-refund/f/contracts/35503230/give-refund?refundRequestUid=1745566088518770688).

Payment of $250 for @tienifr [here](https://www.upwork.com/nx/wm/offer/100400688).

**Closed by twisterdotcom** 2024-01-11 22:01 UTC
Labels: External, Weekly, Bug

**Comment by twisterdotcom** [comment] 2024-01-12 11:26
Apologies @barros001 I am going off the comment you 👍 in Slack here about agreeing to split: https://expensify.slack.com/archives/C01GTK53T8Q/p1700757642008119?thread_ts=1700483443.288289&cid=C01GTK53T8Q
<img width="1268" alt="image" src="https://github.com/Expensify/App/assets/9133401/569b69d6-a5eb-4649-aeb5-54d301874b1c">

If it's a better middle ground, we can also not process the $250 refund and just pay out $250 for @tienifr.

**Comment by twisterdotcom** [comment] 2024-01-15 09:33
Okay, I'm happy for you to reject the refund request.
