### ISSUE TITLE
Some letters are partially obscured within the padding area of the signup page, and the margin above and below the error is inconsistent.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18691] opened 2023-05-09 22:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the "Staging New Expensify" website.
2. Observe that certain letters are not fully visible due to being within the padding area.
3. Notice that the margin above and below the error message is not consistent.

## Expected Result: 
No letters should be hidden within the padding area, and the margin should be consistent.
## Actual Result: 
Some letters are partially obscured within the padding area, and the margin of the signup page is inconsistent.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![2](https://github.com/Expensify/App/assets/43996225/3b9c5175-652b-438b-87ef-d2a4546137db)
![1](https://github.com/Expensify/App/assets/43996225/590c2c8a-5feb-4187-a90c-864d51bdd79b)
<img width="955" alt="Untitled" src="https://github.com/Expensify/App/assets/43996225/3591a0f1-7892-4308-933e-655832fa9c62">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683659309153179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-05-10 05:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Some letters are partially obscured within the padding area of the signup page, and the margin above and below the error is inconsistent. 
### What is the root cause of that problem?
<img width="785" alt="Screenshot 2023-05-10 at 10 29 23 AM" src="https://github.com/Expensify/App/assets/59907218/f74ede22-82a5-482a-8231-bcf95dbb5c82">
<img width="930" alt="Screenshot 2023-05-10 at 10 29 57 AM" src="https://github.com/Expensify/App/assets/59907218/9dfc4fde-5fd1-412c-9242-c44e45f30ebd">

As you can see parent element has max width of 375px and 40px padding, when we subtract padding for child element there is 295px left, but it is set to have max width of 300px. This issue is also present in magic code screen.

There is a margin in wrapper of error message
<img width="1027" alt="Screenshot 2023-05-10 at 10 51 23 AM" src="https://github.com/Expensify/App/assets/59907218/6969fe25-e949-4ac9-a4e1-a4ab6924ac06"> 


### What changes do you think we should make in order to solve the problem?
We should either set parent to have 380px or child element to be 295px, I think parent should be fixed to match child elements requirements.

Regarding the margin, I think it is intentional as removing margin would also impact button styles, since button and error message have the same wrapper.
https://github.com/Expensify/App/blob/c12f968bccf2d889f0c4431618e03034b81a387c/src/pages/signin/LoginForm.js#L204

1. One thing we can do about this is that, we can extract error message outside of button and use regular button there, instead of component which contains both error message and button.
2. Or we can put server message error into input error message
### What alternative solutions did you explore? (Optional)

**Comment by muttmuure** [comment] 2023-05-11 18:50
I don't agree that this is unexpected.

**Closed by muttmuure** 2023-05-11 18:50 UTC
Labels: Daily, Bug
