### ISSUE TITLE
[$1000] Web - Assign task - The task description is not displayed properly with a long string.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24628] opened 2023-08-16 15:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new task or go to an existing task.
2. Click on description.
3. Add a long string.

## Expected Result:
The task description should be displayed properly.

## Actual Result:
The task description is not displayed properly.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.54-11

**Reproducible in staging?:** Y

**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8461c289-0d99-4c1c-b6e4-d9f88f751900

https://github.com/Expensify/App/assets/115492554/21987f95-677d-4422-bcb8-cd46b6c89d0f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Oleksandr Pantsyr

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690998431581659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bb30af303fe418de</li>
        <li>Upwork Job ID: 1691854159560179712</li>
        <li>Last Price Increase: 2023-08-16</li>
    </ul>
</details>

**Comment by akamefi202** [comment] 2023-08-16 18:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The task description is not displayed properly with a very long string.

### What is the root cause of that problem?
We already have word-break property.
https://github.com/Expensify/App/blob/bfe5c21588042958926a1bcb22239635e8b379fb/src/styles/styles.js#L3515-L3518

I think this happens because of too long text. This problem occurs when the user inputs more than 50000 characters.

### What changes do you think we should make in order to solve the problem?
It's unlikely to enter this long text for users, so I think we should add `maxLength` prop to description input.
https://github.com/Expensify/App/blob/ae6dd7e6f4284248865e5fb4a9ae4241b4ea5daa/src/pages/tasks/TaskDescriptionPage.js#L66-L70

For example, `maxLength={CONST.MAX_COMMENT_LENGTH}`.
Or we can add a particular constant value for description input.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by mollfpr** [comment] 2023-08-18 16:58
Thanks @dhairyasenjaliya 👍

@izarutskaya  I think we can close this. This issue will resolved on https://github.com/Expensify/App/issues/18647.

**Comment by mollfpr** [comment] 2023-08-18 17:39
> This is the issue in task description, not name.

@oleksandr-pantsyr It's already listed in the OP issue.

![Screenshot 2023-08-19 at 00 39 20](https://github.com/Expensify/App/assets/25520267/6c7f2a74-4442-4ef7-9a93-eebf321988e3)

**Comment by mollfpr** [comment] 2023-08-21 14:15
Thanks @oleksandr-pantsyr 

I agree adding the max length will not fix the root cause, but we don't have any satisfactory proposal to fix the root cause. The moment https://github.com/Expensify/App/issues/18647 is merged, the issue will be hard to reproduce, except you already have the task with this issue.

Also, the user will not often put a description of 50k chars in one word.

**Comment by slafortune** [comment] 2023-08-22 19:27
I agree with you @mollfpr, I think a string of 50K anywhere is not likely.

**Closed by slafortune** 2023-08-22 19:27 UTC
Labels: External, Daily, Help Wanted, Bug
