### ISSUE TITLE
PRs already deployed to production included on staging checklist, PRs incorrectly commented on

### ISSUE THREAD

**Issue by jasperhuangg** [Expensify/App#23368] opened 2023-07-21 20:25 UTC
As a result of this actions run: https://github.com/Expensify/App/actions/runs/5625378789

A few PRs that were already deployed to production were commented on as "deployed to staging" (e.g. https://github.com/Expensify/App/pull/23085)

<img width="944" alt="Screenshot 2023-07-21 at 1 23 55 PM" src="https://github.com/Expensify/App/assets/31285285/7ab2b425-aa7c-4740-b8dc-2465caf21318">

I also saw a PR that was reverted was commented on as "deployed to staging" incorrectly.

All of these PRs were duplicated in the new staging deploy checklist that was generated.

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ae2cbe68255df19f</li>
        <li>Upwork Job ID: 1685051183088631808</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by stephanieelliott** [comment] 2023-07-24 20:41
@jasperhuangg this seems like something we would need to fix internally, yeah?

**Comment by Beamanator** [comment] 2023-08-02 07:36
FYI this happened again today
- New checklist for the day: https://github.com/Expensify/App/issues/24028
- Yesterday's checklist: https://github.com/Expensify/App/issues/23945

Discussed a bit in slack [here](https://expensify.slack.com/archives/C07J32337/p1690960880900909) on how to organize those PRs from previous checklists that are already deployed to production

**Comment by roryabraham** [comment] 2023-08-07 16:35
Closing this as a dupe of https://github.com/Expensify/App/issues/4379

**Closed by roryabraham** 2023-08-07 16:35 UTC
Labels: Engineering, Weekly, Improvement, Internal, Overdue
