### ISSUE TITLE
[$250] mWeb - Self DM - Self DM with track expense on mark as unread is not shown in bold in LHN

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53838] opened 2024-12-10 11:15 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.73-6
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N
**Email or phone of affected tester (no customers):** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Open self dm with no conversation
3. Create a track expense
4. Navigate to LHN
5. Long press self dm and select mark as unread
6. Note self dm not shown in bold
7. Tap fab --new workspace
8. Open workspace chat
9. Create a track expense
10. Navigate to LHN and mark as unread the chat
11. Note workspace chat shown in bold.

## Expected Result:
Self DM with track expense on mark as unread must be shown in bold in LHN.

## Actual Result:
Self DM with track expense on mark as unread is not shown in bold in LHN.

## Workaround:
Unknown

## Platforms:
- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5819115b-ba49-4dc9-a36c-1a2ec9d09bd9

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021866482645091110325</li>
        <li>Upwork Job ID: 1866482645091110325</li>
        <li>Last Price Increase: 2024-12-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @paultsimura</details>

**Comment by Tony-MK** [comment] 2024-12-10 14:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Self DM - Self DM with track expense on mark as unread is not shown in bold in LHN

### What is the root cause of that problem?

When executing the `markCommentAsUnread` function, the created time of the action track expense is used as the new `lastReadTime` instead of the report action which is last visible.

https://github.com/Expensify/App/blob/3982ed03ff644e7a723e8d4131535a2cceb9488d/src/libs/actions/Report.ts#L1359-L1368

https://github.com/Expensify/App/blob/3982ed03ff644e7a723e8d4131535a2cceb9488d/src/libs/actions/Report.ts#L1372-L1379

However, the `isUnread` function uses the report's `lastVisibleActionCreated` value which is unchanged, and compares itto  `lastReadTime` which is greater than the `lastVisibleActionCreated`.

https://github.com/Expensify/App/blob/3982ed03ff644e7a723e8d4131535a2cceb9488d/src/libs/ReportUtils.ts#L6275-L6280

### What changes do you think we should make in order to solve the problem?


Filter out actionable track expenses just like whisper actions.

https://github.com/Expensify/App/blob/3982ed03ff644e7a723e8d4131535a2cceb9488d/src/libs/actions/Report.ts#L1364

```
(!(ReportActionsUtils.isWhisperAction(current) || ReportActionsUtils.isActionableTrackExpense(current)) || current.actionName === CONST.REPORT.ACTIONS.TYPE.ACTIONABLE_MENTION_WHISPER)
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


We should test the `markCommentAsUnread` function by creating a variety of test reports that have actionable whisper actions.

### What alternative solutions did you explore? (Optional)

Set the report's `lastVisibleActionCreated` optimistically to the newly created report action.

**Comment by dangrous** [comment] 2024-12-12 20:54
Okay I have a potential BE fix for this up, but I realized I need one clarification @paultsimura - with the existing code, why does marking the chat as unread, even with additional messages after the whisper, add the green line above the whisper? Is that a BE thing that I can fix here too?

Updating the `lastVisibleActionCreated` makes the LHN bold on mark as unread, but the green line still appears above the whisper, even when there are more messages below.

Thanks!

**Comment by dangrous** [comment] 2024-12-13 16:28
Okay cool, that feels like sort of weird behavior to me but if that's how we have it then we can stick to that for now.

I'll push the backend change up for review today and we can go from there.

**Comment by dangrous** [comment] 2024-12-16 17:27
Backend is merged, not yet deployed.

**Comment by dangrous** [comment] 2024-12-17 18:41
Okay, now it's deployed. Do we need any FE changes? (And can we retest please?) thanks!

**Comment by dangrous** [comment] 2024-12-18 19:44
Okay I just tested on staging and it seems to work.

I did notice another issue that is related but not super important probably? As @paultsimura called out [here](https://github.com/Expensify/App/issues/53838#issuecomment-2540007001), mark as unread marks the last message that hasn't been sent by you. Which means you **can't mark a self-DM as unread UNLESS it has a track expense whisper in it**. I still find this weird, but if we decide to fix it it'll be out of scope of this issue.

I'm going to close this, if anyone disagrees - or if we need payment or anything - let me know!

**Closed by dangrous** 2024-12-18 19:44 UTC
Labels: Reviewing, External, Daily, Help Wanted, Bug
