### ISSUE TITLE
Update Header Link Style

### ISSUE THREAD

**Issue by grgia** [Expensify/App#22641] opened 2023-07-11 14:09 UTC
![image](https://github.com/Expensify/App/assets/38015950/6450af3d-8c10-4c89-9f59-9d9c3b229710)

Requirements:
- Entire line is clickable
- On hover, the blue text will use the link hover color and we will use the pointer mouse on web

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c43c444f0847d77</li>
        <li>Upwork Job ID: 1678768484952473600</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by grgia** [comment] 2023-07-19 11:18
@shawnborton just double checking here, should only the blue portion be clickable, or the entire line?

**Comment by shawnborton** [comment] 2023-07-19 12:06
I'd say the entire line. I also wonder if we want to have some :hover feedback here? Like in the very least, the blue part can use our link hover color.

**Comment by JmillsExpensify** [comment] 2023-08-03 04:57
Would love to get started on this one now that we merged the avatars PR.

**Comment by JmillsExpensify** [comment] 2023-08-03 05:04
![Image](https://github.com/Expensify/App/assets/1127863/7d0834cb-be8c-43d4-84d7-89ba04086aa6)

Also while I'm on the subject, I just want to make sure we're updating the second line, such that only the parentReport is hyperlinked. This is what we currently have in the app.

**Comment by shawnborton** [comment] 2023-08-03 10:02
I think that's where we ended up. As I've said before, I don't feel strongly. I don't mind one entire clean blue link line underneath.

**Comment by JmillsExpensify** [comment] 2023-08-08 16:06
Ah gotcha. I didn't realize that's where we ended. I think it's a much given that `Expensify Contributors` isn't actually something that you can click and navigate to. Like the only thing you can navigate to is the workspace chat, which for the admin is named `Manan Jadhav` in this specific case.

**Comment by trjExpensify** [comment] 2023-08-10 16:33
Oh, is this not working on expenseReports? 😕 

<img width="612" alt="image" src="https://github.com/Expensify/App/assets/16232057/f59fc159-3e73-4bcd-bf99-265f05e604df">

**Comment by trjExpensify** [comment] 2023-08-10 16:40
Sorry, maybe I'm confused by the issue. I think only the parent chat should be in blue and I agree with some hover feedback.

**Comment by JmillsExpensify** [comment] 2023-08-10 16:43
Cool, I think I'm in the same place. I think it's a little confusing to make the entire sub-header blue, because it's actually referencing like two distinct things: the parentReport and the workspace chat. As a result, I think we should just make the parentReport blue, keeping the rest grey.

**Comment by JmillsExpensify** [comment] 2023-08-15 21:35
Following up on that last comment, can we update how `expense` reports work, basically making them consistent with `IOU` reports?

**Comment by JmillsExpensify** [comment] 2023-08-22 00:25
I actually think this is fixed now and should be closed? I also see that a week after I posted my screenshot above a linked PR was merged and deployed, so yeah I think this is done now. @grgia Do you mind confirming and closing this issue?

<img width="459" alt="Screenshot 2023-08-21 at 17 24 04" src="https://github.com/Expensify/App/assets/1127863/616e964a-8a5c-4c22-87a0-64fd95b0bb31">

**Comment by JmillsExpensify** [comment] 2023-08-23 20:29
All linked PRs are merged and I can't reproduce so I'm closing this out. Someone please re-open if anything remains.

**Closed by JmillsExpensify** 2023-08-23 20:29 UTC
Labels: Reviewing, Weekly, Internal
