### ISSUE TITLE
[$1000] App does not retain focus on click on 'From user' in header (works fine on back click)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23427] opened 2023-07-23 17:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report that has message on which there is reply in thread
3. Click on 'Reply' to open reply in thread report
4. Focus on compose box
5. Click on back in header and observe that app retains focus to compose box on main thread too
6. Again click on 'Reply' to open reply in thread report
7. Focus on compose box
8. Click on 'From username' in header and observe that app does not retain focus on main thread
## Expected Result: 
On click on 'From username' in header, app should retain focus on main thread if it has focus on reply in thread report ~OR similar to android app, app should lose focus to main thread on click on back from reply in thread report~
## Actual Result: 
On click on 'From username' in header, app does not retain focus on main thread even if it has focus on reply in thread report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/13418d7d-c8cd-4d81-982c-e5d46f29e88e

https://github.com/Expensify/App/assets/43996225/19217975-587c-43c8-a326-77aebc5f47c5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690040993418759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013e09a1bff5ef2e65</li>
        <li>Upwork Job ID: 1684557916720082944</li>
        <li>Last Price Increase: 2023-07-27</li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-07-24 00:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

There is an inconsistency: when we go to a thread and press go back button it opens the keyboard whereas when we press From user it doesn't.

I think mweb and android/ios should have the same behaviour which is: not focusing the input


### What is the root cause of that problem?

The reason the input is focused when we press go gack button is because in ReportActionCompose we have withNavigationFocus here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/home/report/ReportActionCompose.js#L1290

And it changes the state isFocused


### What changes do you think we should make in order to solve the problem?

In the update method of ReportActionCompose, when we focus the input "ourself" here:
https://github.com/Expensify/App/blob/cd851d0fbd901c70a32220472104ffc887639f2a/src/pages/home/report/ReportActionCompose.js#L277-L279

we can add a condition to only do it if this.shouldFocusInputOnScreenFocus is true

Result:


### What alternative solutions did you explore? (Optional)

**Comment by michaelhaxhiu** [comment] 2023-07-27 13:26
Trying to reproduce this 1 right now

**Comment by michaelhaxhiu** [comment] 2023-07-27 13:34
reproduced on my android 👍

**Comment by michaelhaxhiu** [comment] 2023-07-27 13:35
Updated the Expected Result to clarify we should keep focus in both scenarios (tap header vs back arrow)

**Comment by ShogunFire** [comment] 2023-07-27 13:43
@michaelhaxhiu Are you sure this is the expected behaviour ? It seems currently we purpusefully don't give focus to the input on mobile for UX reasons. That's why we have a variable this.shouldFocusInputOnScreenFocus

**Comment by s77rt** [comment] 2023-07-28 00:57
@michaelhaxhiu I think @ShogunFire is right here. We do not auto focus the composer in small screen devices because the keyboard may be annoying.

FWIW we had some slack threads about this, e.g. (may not be the most recent) https://expensify.slack.com/archives/C01GTK53T8Q/p1617201995245400 where the idea (currently implemented) was to optimise reports for reading - do not show the keyboard automatically.

**Comment by michaelhaxhiu** [comment] 2023-07-31 13:24
Oh wow, interesting! Thank you both for the additional input. I didn't realize it was intentionally designated in the code, and more so was leaning toward "fix it" because it felt inconsistent in the moment. I suppose what you say makes sense, I'll close this 1.

**Closed by michaelhaxhiu** 2023-07-31 13:24 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug

**Comment by ShogunFire** [comment] 2023-07-31 13:29
Hello @michaelhaxhiu, sorry ahah but I am not sure we should close it. I think the bug was that the input is focused when we press the go back button. What do you think ?
