### ISSUE TITLE
[$1000] Send button still display when attaching corrupt pdf file

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#25546] opened 2023-08-20 17:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Clicking plus button
3. Clicking Add Attachment
4. Select corrupt pdf file
We can use this website to create corrupt pdf file: https://corrupt-a-file.net/#google_vignette
## Expected Result: 
Send button should be hidden
## Actual Result: 
Send button still display when attaching corrupt pdf file
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.55-2 
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ba16d4c5-7a44-4543-9761-ea880efda451

https://github.com/Expensify/App/assets/43996225/8843e38d-ba3b-4512-b406-eaf072aa35bb

[02-Hadoop_ecosystem_issue (1).pdf](https://github.com/Expensify/App/files/12388809/02-Hadoop_ecosystem_issue.1.pdf)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691399819422609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014fc6c60f208ce790</li>
        <li>Upwork Job ID: 1694722486814593024</li>
        <li>Last Price Increase: 2023-08-31</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Contributor | 26517486</li>
<li>dukenv0307 | Reporter | 26517488</li>
</ul></li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-08-20 17:59
## Proposal
Proposal from @dukenv0307
### Please re-state the problem that we are trying to solve in this issue.
Send button still displays when attaching a corrupt pdf file
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/e555022ef97cec4ddbc39283c0d537d6366a2a49/src/components/AttachmentModal.js#L362
We always display send button without checking if the pdf file is valid or not
### What changes do you think we should make in order to solve the problem?
We can check if a PDF file is valid on the PDFView Component based on the onLoadError props of the Document Component
https://github.com/Expensify/App/blob/e555022ef97cec4ddbc39283c0d537d6366a2a49/src/components/PDFView/index.js#L131
So, I suggest we can introduce a new state called isError in AttachmentModal and pass setIsError to PDFView. In PDFView, we call setIsError(true) in onLoadSuccess and setIsError(false) in onLoadSuccess
And in AttachmentModal we don’t display send button (or disable send button) when isError is true
This is the code change for testing: https://github.com/Expensify/App/pull/24201

**Comment by getusha** [comment] 2023-08-21 08:21
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The send button still shows up when trying to attach a broken PDF file.

### What is the root cause of that problem?
The send button will always be enabled even if the file is corrupt or not.
### What changes do you think we should make in order to solve the problem?


We should add a prop called `onLoadError` to pass it to `PDFView` and when it triggers we will disable the send button using `updateConfirmButtonVisibility`

https://github.com/Expensify/App/blob/03cf0b14f82a41db004dfee27799e3cea1608ee5/src/components/AttachmentModal.js#L288-L300

```js
 onLoadError={() => updateConfirmButtonVisibility(true)}
```

### What alternative solutions did you explore? (Optional)

**Comment by anmurali** [comment] 2023-08-24 14:44
<img width="769" alt="image" src="https://github.com/Expensify/App/assets/14225673/8d1b3632-d087-4b8b-80ed-3e9a966473fc">

It errors out on `Send` but does allow you to Send.

**Comment by vasundhara0504** [comment] 2023-08-24 17:15
Contributor Details
Your Expensify Account Detail - rajevasundharaotario@gmail.com
Upwork Profile Link - https://www.upwork.com/freelancers/~01225d5ca3e7927e60/

Hi There,

So here is my technical response in order to resolve the issue as per my understanding.
**The send button still displays when attaching corrupt PDF file #25546**
After reviewing the GitHub video, I think, The component we are using to load the pdf, must be giving a callback error after it shows the failed to load message, Once we get a callback error, we can store the “pdfError” boolean value in the redux store and then we can use this boolean value on send button click functionality whether to perform action or not, also we can give the send button disable prop with  "pdfError" value stored in redux, so we can use the pdfError value to enable or disable the send button.
Also, I have reviewed the Contributor Guidelines as well, and I'm okay with it. If my proposal is accepted, then eventually I will take less than 6 days to complete the task.

Regards,
Vasundhara raje

**Comment by anmurali** [comment] 2023-08-30 02:14
@0xmiroslav can you please review the proposals here?

**Comment by anmurali** [comment] 2023-09-06 01:33
I assigned it to you @aimane-chnaif

**Comment by youssef-lr** [comment] 2023-09-06 12:08
@aimane-chnaif I'm not sure if this is worth fixing in the backend, in the rare case where someone wants to share a corrupted file they can get around this by just zipping the file then uploading it. 

I also don't think this issue is worth fixing IMO, the PDF loading locally could fail for some reason (other than the file being corrupt) but the backend can still process the file.

 I can see in the PDF library we're using there are two error callback, `onLoadError` and `onSourceError`. I'm just worried this could have a regression in the future where the file isn't corrupt but the loading fails for some reason and we prevent the user from uploading it. What do you think @aimane-chnaif?

**Comment by youssef-lr** [comment] 2023-09-06 12:13
Also the reason why the backend throws an error is because we actually process PDF files and create thumbnails that xe return back, if there was no processing involved we'd just return the link.

**Comment by anmurali** [comment] 2023-09-13 03:40
@youssef-lr @aimane-chnaif - what do y'all wanna do here?

**Comment by youssef-lr** [comment] 2023-09-13 04:15
I'm voting to close this one as it has a pretty minor impact on user experience, I'm not sure dedicating engineering time to fix this in the backend is worth it right now IMO. So basically it fails to load in the frontend if it's detected as corrupt in the frontend, but it doesn't hurt to give it another chance to be processed in the backend.

**Comment by youssef-lr** [comment] 2023-09-13 04:37
>Or just close this and still allow uploading corrupted file and get error from backend?

Yeah I think we'll go with this. Thanks everyone!

**Closed by youssef-lr** 2023-09-13 04:37 UTC
Labels: External, Daily, Bug
