### ISSUE TITLE
[HOLD for payment 2024-02-26] Reimbursements - Error message is not left aligned to other items

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#36436] opened 2024-02-13 20:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41-2
**Reproducible in staging?:** y
**Reproducible in production?:** n (new feature)
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open workspace settings page
2. Click on 'Reimbursements'
3. Click on 'Rate'
4. Click on 'Rate' again
5. Reset the value to '0'
6. Click 'Save'

## Expected Result:
Error message should be left aligned with back & save button

## Actual Result:
Error message is not left aligned with back & save button

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![Bug6378591_1707855590103!Screenshot_2024-02-13_at_5 34 00_in_the_afternoon](https://github.com/Expensify/App/assets/43996225/2a40d357-8f01-42ab-8a56-7795c0893757)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Habtamu-Asefa** [comment] 2024-02-13 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The form validation error message is out of alignment, not left aligned.

### What is the root cause of that problem?
The form validation error message has zero padding and margin. Therefore, it is attached to the left side of the screen.

### What changes do you think we should make in order to solve the problem?
Adding left padding like the other items, and making it align with them.
                 {!!errorText && (
                    <FormHelpMessage
                        style={[styles.pAbsolute, styles.b0, styles.mb0, styles.w100]}
                        isError
                        message={errorText}
                    />
                )}

### What alternative solutions did you explore? (Optional)
Tried adding a left margin but that is working only for the web.

**Comment by Beamanator** [comment] 2024-02-14 13:24
@ZhenjaHorbach Agreed it looks like this came from https://github.com/Expensify/App/pull/34849 - @shubham1206agra can you look into fixing this?

**Comment by hayata-suenaga** [comment] 2024-02-14 16:36
being fixed in [this PR](https://github.com/Expensify/App/pull/36497)

**Comment by thienlnam** [comment] 2024-02-14 23:21
Removing the blocker 
https://github.com/Expensify/App/pull/36549#issuecomment-1944982700

**Comment by kevinksullivan** [comment] 2024-02-22 18:48
Payment summary: 
- Contributor review: @allroundexperts $250

**Closed** 2024-02-22 18:47 UTC
Labels: Engineering, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-03-01 23:57
$250 approved for @allroundexperts based on summary above.
