### ISSUE TITLE
Workspace - Workspace chat member list does not remove user when user has left the chat

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40417] opened 2024-04-18 10:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to staging.new.expensify.com
2. Create a new workspace.
3. Go to workspace chat.
4. Mention User B.
5. Invite User B from the whisper.
6. Send a message to the workspace chat.
7. As User B, go to workspace chat.
8. As User B, leave the workspace chat.
9. As User A, click on the chat header > Members.

## Expected Result:
User B will be removed from the workspace chat member list.

## Actual Result:
User B is not removed from the workspace chat member list, even though User B has left the workspace chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/d1b97f85-89d1-4cea-914b-5bc1434e085e

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019627df30080310e8</li>
        <li>Upwork Job ID: 1783472042234789888</li>
        <li>Last Price Increase: 2024-04-25</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-04-18 10:19
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 10:19
We think this issue might be related to the #collect project.

**Comment by NikkiWines** [comment] 2024-04-18 12:57
Possibly tied to https://github.com/Expensify/App/pull/35671/

**Comment by NikkiWines** [comment] 2024-04-18 16:47
I think this is a blocker, so re-adding the label

**Comment by NikkiWines** [comment] 2024-04-18 16:48
Possibly tied to https://github.com/Expensify/App/pull/35671 cc: @MonilBhavsar @rezkiy37

**Comment by thienlnam** [comment] 2024-04-18 21:26
Yeah I agree, this doesn't look like it needs to be a blocker

**Comment by NikkiWines** [comment] 2024-04-18 23:45
Cool, removing the label then and dropping priority

**Comment by MonilBhavsar** [comment] 2024-04-19 06:06
From a brief look, this looks like backend issue to me

**Comment by rezkiy37** [comment] 2024-04-19 09:56
Hey! High-priority tasks currently occupy me.

**Comment by NikkiWines** [comment] 2024-04-23 12:19
re-assigning to @MonilBhavsar per our discussion as he has context 🙇

**Comment by MonilBhavsar** [comment] 2024-04-25 12:23
Looking into this now

**Comment by rezkiy37** [comment] 2024-04-26 13:49
Hey!
I just wanted to let you know about my vacation for next week. I will be back on 06.05.2024. Meanwhile, I asked @waterim to help with this issue. 
See you soon!

**Comment by MonilBhavsar** [comment] 2024-04-26 14:04
PR is in review

**Comment by ikevin127** [comment] 2024-04-26 14:12
Will I be needed for review here ? 🙂

**Comment by isabelastisser** [comment] 2024-05-03 19:24
Hey,@ikevin12, can you please provide an update? Thanks!

**Comment by ikevin127** [comment] 2024-05-03 19:28
@isabelastisser I was told in https://github.com/Expensify/App/issues/40417#issuecomment-2079479561 that my help as a reviewer is not needed here since this is a server side issue and PR which I don't have access to review.

**Comment by isabelastisser** [comment] 2024-05-03 19:39
My bad, @MonilBhavsar, is there an update? Thanks!

**Comment by MonilBhavsar** [comment] 2024-05-06 09:26
Regression test issue created https://github.com/Expensify/Expensify/issues/393485
... and closing

**Closed by MonilBhavsar** 2024-05-06 09:26 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
