### ISSUE TITLE
[HOLD for payment 2024-01-11] [$500]  IOU - Can't download receipt image

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33474] opened 2023-12-22 00:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15.1
**Reproducible in staging?:**  Y
**Reproducible in production?:**  Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Navigate to a workspace chat
3. Go offline
4. Do a scan IOU
5. Download the image

## Expected Result:
I should be able to download it

## Actual Result:
Can't download the receipt image

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5d116036-7648-453d-952e-ce43cb0752e8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by namhihi237** [comment] 2023-12-22 00:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Can not download receipt when offline
### What is the root cause of that problem?
When we offline the image doest not upload to S3 show the source file is local but we have isAuthTokenRequired is true, so the URL has a `encryptedSourceUrl`. That is wrong

We do not return the `isLocalFile` here so isAuthTokenRequired is true.
https://github.com/Expensify/App/blob/659f509b7e1093252d7c2ea14d0082ee78dd6503/src/libs/ReceiptUtils.ts#L45-L49
### What changes do you think we should make in order to solve the problem?
We shouldupdate
```
const isLocalFile = path.startsWith('blob:') || path.startsWith('file:');
return {thumbnail: null, image: path, isLocalFile };
```

### What alternative solutions did you explore? (Optional)

**Comment by bfitzexpensify** [comment] 2023-12-25 00:57
@shubham1206agra what do you think of @namhihi237's proposal? Is this a fairly simple change? I think it would be ideal for this to work, but this feels like a fairly unusual flow for someone to follow

**Comment by shubham1206agra** [comment] 2023-12-26 04:40
> @shubham1206agra what do you think of @namhihi237's proposal? Is this a fairly simple change? I think it would be ideal for this to work, but this feels like a fairly unusual flow for someone to follow

Actually, it can be quite common for someone to follow this route. Example is what if I clicked the image of a receipt, and I just want a copy of the image in my local storage too. Then this flow can be followed

**Comment by shubham1206agra** [comment] 2023-12-26 04:53
@namhihi237's proposal looks good to me.

🎀👀🎀 C+ reviewed

**Comment by sakluger** [comment] 2024-01-11 20:04
Sent offers via Upwork. @shubham1206agra could you please complete the BZ checklist?

**Comment by namhihi237** [comment] 2024-01-11 21:33
@sakluger accepted

**Comment by sakluger** [comment] 2024-01-11 23:47
Thanks @namhihi237! I completed your payment.

**Comment by shubham1206agra** [comment] 2024-01-12 12:16
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30747
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30747/files#r1450354884
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as this is an edge case missed by ttps://github.com/Expensify/App/pull/30747
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by shubham1206agra** [comment] 2024-01-12 12:17
@sakluger Checklist done

**Comment by sakluger** [comment] 2024-01-13 00:23
Thank you! All paid out 👍

**Closed by sakluger** 2024-01-13 00:23 UTC
Labels: External, Daily, Awaiting Payment, Bug
