### ISSUE TITLE
[Hold] on #29199 [$500] Chat - The composer isn't focused if you choose "Manage my team's expenses"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#37897] opened 2024-03-07 14:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Found when validating PR :** https://github.com/Expensify/App/pull/37652

**Version Number:** 1.4.48.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in with a new account
2. Tap on "Manage my team's expenses"
3. Tap on the "No" button

## Expected Result:
It should be focused and the keyboard should be visible.

## Actual Result:
The composer isn't focused if you choose "Manage my team's expenses"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/243282b4-3d46-4f85-b151-ae883f8ba62a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01406f3d8e31f8e03b</li>
        <li>Upwork Job ID: 1767135944339693568</li>
        <li>Last Price Increase: 2024-03-18</li>
    </ul>
</details>

**Comment by izarutskaya** [comment] 2024-03-07 14:56
@laurenreidexpensify I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by ShridharGoel** [comment] 2024-03-07 15:52
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The composer isn't focused if "Manage my team's expenses" is selected.

### What is the root cause of that problem?
Below is the auto-focus logic in `ComposerWithSuggestions`
```
const shouldAutoFocus =
        !modal?.isVisible && isFocused && (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentReportAction))) && shouldShowComposeInput;
```
shouldFocusInputOnScreenFocus is false for native apps.

### What changes do you think we should make in order to solve the problem?
Change `shouldFocusInputOnScreenFocus` to true for native apps.

**Comment by ShridharGoel** [comment] 2024-03-07 15:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The composer isn't focused if "Manage my team's expenses" is selected.

### What is the root cause of that problem?
Below is the auto-focus logic in `ComposerWithSuggestions`
```
const shouldAutoFocus =
        !modal?.isVisible && isFocused && (shouldFocusInputOnScreenFocus || (isEmptyChat && !ReportActionsUtils.isTransactionThread(parentReportAction))) && shouldShowComposeInput;
```
shouldFocusInputOnScreenFocus is false for native apps.

### What changes do you think we should make in order to solve the problem?
Change `shouldFocusInputOnScreenFocus` to true for native apps.

**Comment by laurenreidexpensify** [comment] 2024-03-11 10:30
This feels like a low priority bug - not sure if it fits under any roadmap project specifically tho

**Comment by FitseTLT** [comment] 2024-03-11 10:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - The composer isn't focused if you choose "Manage my team's expenses"

### What is the root cause of that problem?
The auto-focus is disabled in natives intentionally for better UX experience unless we are opening an empty chat here
https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L270-L272
But the way we calculate empty chat is if report actions is empty which is wrong empty chats have at least one `CREATED` type report action 
https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/pages/home/ReportScreen.js#L265-L266
### What changes do you think we should make in order to solve the problem?

Change it to
```
    const isEmptyChat = useMemo(() => _.size(reportActions) === 1, [reportActions]);

```
or also we can use the logic we are using here
https://github.com/Expensify/App/blob/77375e86525257fcd7ccd9f813f9c6dc7d125f4b/src/libs/ReportUtils.ts#L4130-L4131
### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2024-03-14 10:39
@fedirjh bump for review

**Comment by laurenreidexpensify** [comment] 2024-03-26 10:33
Still held on #29199

**Comment by laurenreidexpensify** [comment] 2024-04-02 11:52
[Hold] on https://github.com/Expensify/App/issues/29199

**Comment by laurenreidexpensify** [comment] 2024-04-02 12:43
I"m going to close this one out as it will be covered in #29199

**Closed by laurenreidexpensify** 2024-04-02 12:43 UTC
Labels: External, Weekly, Help Wanted, Bug
