### ISSUE TITLE
[HOLD for payment 2024-05-20] [$500] IOU - Disabled tag is greyed in list but disabled category is shown bold in list.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36485] opened 2024-02-14 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314177
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app as employee
2. Tap on employee workspace chat
3. Create a manual request by entering tag, category and all necessary field
4. In admin account, disable the tag and category used to create above expense
5. In employee account, in Workspace chat, open the newly created request to open details page.
6. Note missing tag and category in red displayed
7. Tap on tag and note disabled tag is greyed in the drop down list
8. Tap on category and note disabled category is in bold in the drop down list

## Expected Result:
Both disabled tag and category should be disabled in same manner.

## Actual Result:
Disabled tag is greyed in list but disabled category is shown bold in list.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/c391172a-2673-46e0-bb33-cccd8ea20b8b

https://github.com/Expensify/App/assets/93399543/f7de93aa-430c-4c9f-a809-53b56c0b4b2e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0153013ee28976211a</li>
        <li>Upwork Job ID: 1757771565108477952</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 0</li>
<li>Krishna2323 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-14 14:20
We think that this bug might be related #vip-bills
CC @davidcardoza

**Comment by alitoshmatov** [comment] 2024-02-21 05:28
@Krishna2323 Thank you for your proposal. I do agree that this is very similar to tags page and we can have the same approach on fixing the issue.

**Comment by alitoshmatov** [comment] 2024-02-21 05:31
@FitseTLT Thank you for your proposal, I don't think your solution is correct. Even if we set enabled there the `selectCategory` is overwritten on category page. Here is a screenshot when I tried your solution:
<img width="566" alt="Screenshot 2024-02-21 at 10 26 00" src="https://github.com/Expensify/App/assets/59907218/ee34f756-9342-403c-8e19-4c55fb9e1145">

**Comment by alitoshmatov** [comment] 2024-02-21 05:31
We can go with @Krishna2323 's [proposal](https://github.com/Expensify/App/issues/36485#issuecomment-1943884263)

C+ reviewed 🎀 👀 🎀

**Comment by dangrous** [comment] 2024-02-21 16:04
Makes sense!

**Comment by dangrous** [comment] 2024-02-21 16:06
well I'm not sure why the automation isn't firing but let's move forward with @Krishna2323 and we can handle that afterwards.

**Comment by kbecciv** [comment] 2024-02-22 20:42
@dangrous Sorry about that, will be more careful next time.

**Comment by sakluger** [comment] 2024-02-26 20:29
Hey @Krishna2323, were you able to finish the PR? Do you have a draft PR you could link?

**Comment by dangrous** [comment] 2024-03-23 15:40
Yeah I think that makes sense - @sakluger what do you think? Since there were some changes to our base components and design during the course of this issue, it's now a bit bigger than initially planned (it was just copying the behavior of tags over to categories but now we're updating both)

**Comment by mallenexpensify** [comment] 2024-03-28 23:03
@Krishna2323 , if the internal engineers thinks an increased bounty makes sense then we can do that.  Our normal process is discuss the compensation amount once the PR is merged because we'll know the amount of work then.  Is that alright? ( @alitoshmatov will also be asked to provide feedback to since they're directly involved)

**Comment by alitoshmatov** [comment] 2024-03-29 05:55
Agreed, @Krishna2323 please move forward with the PR, our current priority is PR. Once it is merged we can discuss payment issue

**Comment by mallenexpensify** [comment] 2024-04-23 22:03
@alitoshmatov plz review[ the PR](https://github.com/Expensify/App/pull/37397). 
This issue is lagging, please prioritize getting this wrapped up. Per[ CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#:~:text=Daily%20updates%20on,original%20contract%20terminated.)
> Daily updates on weekdays are highly recommended. If you know you won’t be able to provide updates within 48 hours, please comment on the PR or issue stating how long you plan to be out so that we may plan accordingly. We understand everyone needs a little vacation here and there. Any issue that doesn't receive an update for 5 days (including weekend days) may be considered abandoned and the original contract terminated.

**Comment by alitoshmatov** [comment] 2024-04-24 05:18
Working on it

**Comment by mallenexpensify** [comment] 2024-04-26 00:02
@Krishna2323 plz reply in the PR https://github.com/Expensify/App/pull/37397#issuecomment-2074061292

**Comment by mallenexpensify** [comment] 2024-05-09 18:39
Regression from this issue/PR is [here](https://github.com/Expensify/App/issues/41890)

**Comment by puneetlath** [comment] 2024-05-21 19:08
@Krishna2323 has been paid. 

@alitoshmatov bump on the checklist.

**Comment by alitoshmatov** [comment] 2024-05-21 20:00
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/27518
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/27518/files#r1608871281
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: no need
- Determine if we should create a regression test for this bug. Yes

1. As workspace employee create money request with category and tag
2. As workspace admin disable selected category and tag in step 1 in old dot
3. As employee open money request in step 1 and go to categories/tag
4. Selected category/tag should be greyed out, but you can still click on it to unselect
5. After selecting new category/tag or unselecting them, it should disappear

Do we agree 👍 or 👎

**Comment by mallenexpensify** [comment] 2024-05-22 23:53
I happened to be subscribed here so I created the TR GH
- https://github.com/Expensify/Expensify/issues/398711

Looks payments are still pending, so leaving open.

**Comment by puneetlath** [comment] 2024-05-23 19:08
Oh, thanks @mallenexpensify!

@alitoshmatov has been paid. Thanks everyone!

**Closed by puneetlath** 2024-05-23 19:08 UTC
Labels: External, Daily, Awaiting Payment, Bug
