### ISSUE TITLE
[HOLD for payment 2023-11-13] [HOLD for payment 2023-11-09] Unread message - When delete unread message green line blinks and goes to the next message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30696] opened 2023-11-01 13:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.94-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to conversation with messages history
3. Mark any message in the middle of the conv history as Unread
4. Delete the same message

## Expected Result:
Green line for the unread message should disappear when delete the message

## Actual Result:
When delete unread message green line blinks and goes to the next message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e6da5fd6-bec2-4d50-8ec3-858df872f99d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by grgia** [comment] 2023-11-01 15:50
Maybe related:
https://github.com/Expensify/App/pull/29860/

**Comment by situchan** [comment] 2023-11-01 16:11
@roksanaz please check this

**Comment by Beamanator** [comment] 2023-11-02 08:36
It looks like this is still happening on staging, even after https://github.com/Expensify/App/pull/30712

**Comment by Beamanator** [comment] 2023-11-02 08:40
This feels like such an edge case, it doesn't make much sense to me to have this block deploy

**Comment by roksanaz** [comment] 2023-11-02 13:17
@situchan I've tested carefully and I can confirm that [my PR](https://github.com/Expensify/App/pull/29860) didn't cause this issue. However, when I checked out [my branch](https://github.com/roksanaz/App/tree/27456-green-line) which didn't have latest changes from main, I've noticed that this behavior wasn't present at that point. I investigated a little bit and when I deleted changes from [this PR](https://github.com/Expensify/App/pull/30485) the green line disappeared after deleting the message marked unread, although the floating button still appeared (when I scrolled up after deleting the unread message). I attach a video to show you what I mean:

https://github.com/Expensify/App/assets/44186263/969d1691-9011-4aab-bd4b-72d08c603e0e

**Comment by situchan** [comment] 2023-11-02 13:24
@roksanaz you mean https://github.com/Expensify/App/pull/30485 caused this blinking issue?

**Comment by s-alves10** [comment] 2023-11-02 17:40
@situchan @MonilBhavsar 

I've found the root cause of this issue. The main issue is in weird logic of the following code
https://github.com/Expensify/App/blob/9cecdfa1439a03a943d6c776e00eaaac3f4cb58c/src/pages/home/report/ReportActionsList.js#L324-L330

- Why can't we set `currentUnreadMarker` if that is not a null. I think this is wrong. `currentUnreadMarker` should be able to change when it's not a null
- During the iteration, `currentUnreadMarker` can be changed and the iteration would be started again because the dependency changes. This forces re-render
- We have redundant dependencies below. All other dependencies except `shouldDisplayNewMarker` are already `shouldDisplayNewMarker`'s dependencies. No needs to add here
https://github.com/Expensify/App/blob/9cecdfa1439a03a943d6c776e00eaaac3f4cb58c/src/pages/home/report/ReportActionsList.js#L335

In order to fix this issue, I updated 
https://github.com/Expensify/App/blob/9cecdfa1439a03a943d6c776e00eaaac3f4cb58c/src/pages/home/report/ReportActionsList.js#L300-L335

to
```
    const shouldDisplayNewMarker = useCallback(
        (unreadMarker, reportAction, index) => {
            let shouldDisplay = false;
            if (!currentUnreadMarker) {
                const nextMessage = sortedReportActions[index + 1];
                const isCurrentMessageUnread = isMessageUnread(reportAction, report.lastReadTime);
                shouldDisplay = isCurrentMessageUnread && (!nextMessage || !isMessageUnread(nextMessage, report.lastReadTime));
                if (!messageManuallyMarkedUnread) {
                    shouldDisplay = shouldDisplay && reportAction.actorAccountID !== Report.getCurrentUserAccountID();
                }
            } else {
                shouldDisplay = reportAction.reportActionID === unreadMarker;
            }
            return shouldDisplay;
        },
        [report.lastReadTime, sortedReportActions, messageManuallyMarkedUnread],
    );

    useEffect(() => {
        // Iterate through the report actions and set appropriate unread marker.
        // This is to avoid a warning of:
        // Cannot update a component (ReportActionsList) while rendering a different component (CellRenderer).
        let unreadMarker = null;
        _.each(sortedReportActions, (reportAction, index) => {
            if (!shouldDisplayNewMarker(unreadMarker, reportAction, index)) {
                return;
            }
            unreadMarker = reportAction.reportActionID;
        });
        setCurrentUnreadMarker(unreadMarker);
    }, [shouldDisplayNewMarker]);
```

And I think we should fix the issue mentioned https://github.com/Expensify/App/pull/30485#issuecomment-1784859939

cc @roksanaz

**Comment by s-alves10** [comment] 2023-11-03 06:52
I'm curious why the below line of code is needed
https://github.com/Expensify/App/blob/9cecdfa1439a03a943d6c776e00eaaac3f4cb58c/src/pages/home/report/ReportActionsList.js#L149

Looking at the comment, this state(`messageManuallyMarkedUnread`) looks like no longer needed.

I am expecting C+ team's feedback. Thank you in advance

**Comment by roksanaz** [comment] 2023-11-03 10:17
> @roksanaz you mean #30485 caused this blinking issue?

@situchan When I commented out the changes from #30485, the green line disappeared, so that's my guess. But it might be more complicated, I didn't investigate it thoroughly.

**Comment by situchan** [comment] 2023-11-03 13:45
@roksanaz yes, I confirmed after that question and commented on that issue.
That's why @s-alves10 (author of that PR) proposed fix above.

**Comment by maddylewis** [comment] 2023-11-08 18:25
@grgia - can you confirm if any payment is required for this one? I'm not seeing a contributor/C+ assigned to this issue.

**Comment by maddylewis** [comment] 2023-11-10 20:58
asked here - https://expensify.slack.com/archives/C01SKUP7QR0/p1699649879381729

**Comment by maddylewis** [comment] 2023-11-13 15:04
hey @jliexpensify - i dropped BZ team so I'm going to un-assign myself from this issue. I've asked if there's any payment required for this one [here](https://github.com/Expensify/App/issues/30696#issuecomment-1806421959), but there might not be any action required by a BZ team member. 

i would bump that slack thread just to be certain, but this might have been resolved on a separate issue?

**Comment by jliexpensify** [comment] 2023-11-14 21:38
Confirmed the payment [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1699956259490819?thread_ts=1699649879.381729&cid=C01SKUP7QR0). Going to close this as Payment is being handled in https://github.com/Expensify/App/issues/27456

**Closed by jliexpensify** 2023-11-14 21:38 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
