### ISSUE TITLE
[Payment due 8-26][$250] Web - Onboarding - "welcome-video:1 DOMException" console error if an app is opened before video

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47162] opened 2024-08-09 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.18-7 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open Chrome console
3. Open Microsoft Word or Outlook and put in in the background
4. Log in with a new Gmail account
5. Choose "Something else" on the onboarding modal
6. Input anything for "First name"
7. Click on the "Continue" button and quickly open Microsoft Word
8. Switch back to Expensify

## Expected Result:
There shouldn't be any console errors.

## Actual Result:
"welcome-video:1 Uncaught (in promise) DOMException" console error if an app is opened before video

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/21f017bb-38c9-4895-a895-6a82d4848a25

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01285e52202504c005</li>
        <li>Upwork Job ID: 1822020298300148127</li>
        <li>Last Price Increase: 2024-08-09</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-09 13:11
We think that this bug might be related to #wave-collect - Release 1

**Comment by IuliiaHerets** [comment] 2024-08-09 13:11
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment] 2024-08-09 15:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The play() request was interrupted because video-only background media was paused to save power error is logged in the console when opening the onboarding video while the tab is not active.

### What is the root cause of that problem?
The onboarding video is auto-played and when the tab isn't active, the play request throws an error. The video will start play when we go back to the tab.

### What changes do you think we should make in order to solve the problem?

We can ignore the error by catching the play promise error here (.catch),
https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/components/VideoPlayerContexts/PlaybackContext.tsx#L37

OR

We can prevent the video to play if the tab is not active, and play it once the tab become active again.
1. In [playVideo](https://github.com/Expensify/App/blob/db669c4d45ec14c849fc5f84af06e3d8564e58b9/src/components/VideoPlayerContexts/PlaybackContext.tsx#L31), if the tab is not active, then return early and save a ref to indicate that there is a pending play.
```
if (!Visibility.isVisible()) {
    isPlayPendingRef.current = true;
    return;
}
```
2. Create a new visibility change listener which will play the pending play request once the tab is active/visible.
```
useEffect(() => {
    const unsubscribeVisibilityListener = Visibility.onVisibilityChange(() => {
        if (!Visibility.isVisible() || !isPlayPendingRef.current) {
            return;
        }
        playVideo();
        isPlayPendingRef.current = false;
    });
    return unsubscribeVisibilityListener;
}, []);
```

**Comment by Christinadobrzyn** [comment] 2024-08-09 21:21
I'm not getting the same console error. I'm seeing this one: 

<img width="553" alt="image" src="https://github.com/user-attachments/assets/edad5dd2-9d48-40b5-9c50-cdd78e0698da">

But since @bernhardoj can reproduce it, we'll keep it going.

**Comment by bernhardoj** [comment] 2024-08-12 09:47
The PR is ready

cc: @aimane-chnaif

**Comment by Christinadobrzyn** [comment] 2024-08-13 19:52
Monitoring PR - https://github.com/Expensify/App/pull/47217

**Comment by Christinadobrzyn** [comment] 2024-08-20 20:55
Looks like it was deployed to prod yesterday so adding a payment date to the Subject

**Comment by Christinadobrzyn** [comment] 2024-08-27 21:00
Looks like the payment notification didn't send. 

Payouts due:

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @aimane-chnaif 

Are you both paid via NewDot? Do we need a regression test for this?

**Comment by bernhardoj** [comment] 2024-08-28 03:12
@Christinadobrzyn I'd like to be paid in ND.

Requested in ND.

**Comment by JmillsExpensify** [comment] 2024-08-28 17:33
$250 approved for @bernhardoj

**Comment by Christinadobrzyn** [comment] 2024-08-28 18:53
@aimane-chnaif should you be paid for this? If yes, can you please accept this [Upwork offer](https://github.com/Expensify/App/issues/47162#issuecomment-2313531979) or let me know if you're paid through NewDot?

**Comment by Christinadobrzyn** [comment] 2024-08-28 18:54
@aimane-chnaif can you accept the upwork offer? thanks! https://github.com/Expensify/App/issues/47162#issuecomment-2313531979

**Comment by Christinadobrzyn** [comment] 2024-08-30 20:10
Dmd @aimane-chnaif  about the upwork offer

**Comment by Christinadobrzyn** [comment] 2024-09-03 16:51
I'm going to be ooo 9/4-9/11. 

I'll assign a BZ teammate to pay this [Upwork offer](https://github.com/Expensify/App/issues/47162#issuecomment-2313531979) when @aimane-chnaif accepts it.

**Comment by Christinadobrzyn** [comment] 2024-09-03 19:31
Thanks @aimane-chnaif - I paid you in upwork based on this [payment summary](https://github.com/Expensify/App/issues/47162#issuecomment-2313531979). Closing!

**Closed by Christinadobrzyn** 2024-09-03 19:31 UTC
Labels: Reviewing, External, Daily, Bug
