### ISSUE TITLE
Android - IOU - Nothing happens when you select corrupted jpg file in SmartScan/no error message

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#38389] opened 2024-03-15 11:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.52-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Start the Request money > "Scan" receipt flow
2. Upload corrupted .jpg file

## Expected Result:
There's should be a brief modal for "Scan in progress"

## Actual Result:
Nothing happens when you select corrupted jpg file in SmartScan
No error message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/c5a7a872-dcf1-494a-8ce2-72fc9287ea71

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-03-15 11:48
@isabelastisser I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by shahinyan11** [comment] 2024-03-15 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - IOU - Nothing happens when you select corrupted jpg file in SmartScan/no error message
### What is the root cause of that problem?
We call the [validateAndCompleteAttachmentSelection](https://github.com/Expensify/App/blob/15124d7f01f3c81878a4df2207a0fb704f2b34c3/src/components/AttachmentPicker/index.native.js#L274C28-L274C66) function inside the `success` callback of `RNImage.getSize`. And if `getSize` failsб the `validateAndCompleteAttachmentSelection` is not called .
### What changes do you think we should make in order to solve the problem?
1. Move [this](https://github.com/Expensify/App/blob/15124d7f01f3c81878a4df2207a0fb704f2b34c3/src/components/AttachmentPicker/index.native.js#L274C21-L274C77) line outside of `RNImage.getSize`
```
RNImage.getSize(fileData.fileCopyUri || fileData.uri, (width, height) => {
    fileData.width = width;
    fileData.height = height;
});

return validateAndCompleteAttachmentSelection(fileData);
```
2. Update [this](https://github.com/Expensify/App/blob/15124d7f01f3c81878a4df2207a0fb704f2b34c3/src/components/AttachmentPicker/index.native.js#L240C17-L240C64) condition with below
```
if (fileData.width === -1  || fileData.height === -1 || !fileData.width || !fileData.height ) {
```
### What alternative solutions did you explore? (Optional)

**Comment by shahinyan11** [comment] 2024-03-15 17:33
## Proposal
[Updated](https://github.com/Expensify/App/issues/38389#issuecomment-1999995682). A change has been added to resolve the issue for the `Web` as well.

**Comment by isabelastisser** [comment] 2024-03-19 20:07
Thanks for the heads, @paultsimura! Closing.

**Closed by isabelastisser** 2024-03-19 20:07 UTC
Labels: External, Daily, Help Wanted, Bug
