### ISSUE TITLE
Report previews don’t seem to get updated when you open a workspace chat. 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#35295] opened 2024-01-29 04:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.32-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1706277477200979

## Action Performed:
1. create a expense report as a employee
2. Be offline as a admin
3. Submit report as a member
4. Check the LHN and report preview
## Expected Result:
Report preview and LHN should get updated as "submitted"
## Actual Result:
Not updated until the user clicking on the report
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/30adb168-d0f8-4c2e-9398-cc401967f3d2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01957dcd6d62f41121</li>
        <li>Upwork Job ID: 1752017420030140416</li>
        <li>Last Price Increase: 2024-01-29</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-01-29 04:07
@vit tagging you as per [here](https://expensify.slack.com/archives/C049HHMV9SM/p1706278344679689?thread_ts=1706277477.200979&cid=C049HHMV9SM)

**Comment by mountiny** [comment] 2024-01-29 16:39
I think we can make this a hot pick, I already got some wave issues to get through, I might pick it up if nobody else will in the mean time

**Comment by twisterdotcom** [comment] 2024-01-29 16:49
Does it need to be internal?

**Comment by mountiny** [comment] 2024-01-29 17:14
I would say yes!

**Comment by twisterdotcom** [comment] 2024-02-01 16:07
A hot HOT pick

**Comment by marcochavezf** [comment] 2024-02-05 17:13
Commented [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1707152625051929?thread_ts=1706804366.090959&cid=C02NZ2HGJAZ) a possible cause of why we're not sending the updated report actions when the workspace chat is opened. I will continue with the investigation today.

**Comment by marcochavezf** [comment] 2024-02-07 23:32
I can't reproduce this one. Probably it's fixed with the latest changes. I'm going to apply the `retest-weekly` label.

**Comment by garrettmknight** [comment] 2024-02-08 14:12
Just encountered it on MacOS version v1.4.35-7 with a scheduled submit report. I think you could probably repro using these instructions:
1. Create expense on Collect workspace with Scheduled Submit enabled to daily
2. Scan receipt in workspace chat
3. Wait a day
4. Report will scheduled submit
5. Report preview will not update until you click into it

<img width="1001" alt="Screenshot 2024-02-08 at 2 12 01 PM" src="https://github.com/Expensify/App/assets/1529980/07591635-8e47-473e-8019-05e7b59026e5">

**Comment by marcochavezf** [comment] 2024-02-12 17:23
I think this error is related to this bugbot I'm hunting https://github.com/Expensify/Expensify/issues/366360, with the added logs I will work on a fix today

**Comment by marcochavezf** [comment] 2024-02-13 20:31
Created another [PR](https://github.com/Expensify/Auth/pull/9930) to log more data for the SubmitReport bugbot, which could also be related.

**Comment by marcochavezf** [comment] 2024-02-15 16:53
Probably also related to this [one](https://github.com/Expensify/App/issues/36541)

**Comment by twisterdotcom** [comment] 2024-02-19 12:03
@marcochavezf is working on it Melv.

**Comment by marcochavezf** [comment] 2024-02-19 23:24
Fixing SSDos locally https://expensify.slack.com/archives/C03TQ48KC/p1708384890886629 to try to reproduce it

**Comment by marcochavezf** [comment] 2024-02-21 00:39
I submitted a request via SSDos locally and got the correct preview:

<img width="864" alt="Screenshot 2024-02-20 at 6 38 21 p m" src="https://github.com/Expensify/App/assets/6829422/936f9d9d-dfb1-4453-b555-1c69d3481ed1">

**Comment by marcochavezf** [comment] 2024-02-21 17:23
Waiting to be re-tested per `retest-weekly` label

**Comment by twisterdotcom** [comment] 2024-02-26 10:48
Waiting for retests

**Comment by mvtglobally** [comment] 2024-02-27 16:13
Issue is reproducible during KI retests.

**Comment by marcochavezf** [comment] 2024-02-27 17:30
Hi @mvtglobally just to be sure about the reproducible issue, in the video from the OP the report preview is updated with the Settlement button for the admin after they came back from offline, and I think that's expected because otherwise the `Submit` button should appear indicating the report hasn't been submitted, no?

**Comment by marcochavezf** [comment] 2024-02-28 17:23
I followed the steps from the OP and I'm not really sure what's missing here. The report preview and LHN are updated:

https://github.com/Expensify/App/assets/6829422/385a006d-15cd-4281-8db1-e0b58a5dff23

https://github.com/Expensify/App/assets/6829422/6e3032e5-fa1d-49ad-bbc5-ae02b32c6d4e

From the expected behavior in the OP we mention:

> Report preview and LHN should get updated as "submitted"

But we're updating the report preview with the Settlement button (we show either Pay or Approve depending on the policy settings), and in the LHN we show "{policy} owes {amount}" not submitted.

**Comment by marcochavezf** [comment] 2024-03-01 19:16
Discussed [here](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1709236481460719?thread_ts=1709087964.400169&cid=C02NZ2HGJAZ) about closing it since instructions for expected output are not clear and the report preview issue hasn't happened lately. We can re-open or create another issue if another similar problem occurs.

**Closed by marcochavezf** 2024-03-01 19:16 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
