### ISSUE TITLE
Android - Never-ending loading circle appears above one of images

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18794] opened 2023-05-11 19:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/18485

## Action Performed:
1. Login to NewDot
2. Open any chat
3. Upload images with width less than 40 pixels
4. Upload a couple more images

## Expected Result:
Images should be well displayed in chat

## Actual Result:
Never-ending loading circle appears above one of images

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.13.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/542a7309-56af-4ef1-8598-5759f1be1138

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by hellohublot** [comment] 2023-05-12 08:10
maybe same root cause as #16046

**Comment by Christinadobrzyn** [comment] 2023-05-12 16:45
Agree @hellohublot - reached out in https://github.com/Expensify/App/issues/16046 to see if these are the same.

**Comment by Christinadobrzyn** [comment] 2023-05-15 20:45
Confirmed - This is the same root cause as https://github.com/Expensify/App/issues/16046#issuecomment-1546028232 - closing this without action.

**Closed by Christinadobrzyn** 2023-05-15 20:45 UTC
Labels: Daily, Overdue, Bug
