### ISSUE TITLE
[HOLD for Payment 2024-10-04][$250] [Search v2.3] - Default name in name field displays user/report ID instead of user/report name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#49739] opened 2024-09-25 19:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh230901@applause.expensifail.com
**Issue reported by:**  Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search
3. Click Filters
4. Click To
5. Select a user and save it
6. Click Save search
7. Click 3-dot menu next to the saved search
8. Click Rename

## Expected Result:
The default name in search name field will display user name instead of user ID

## Actual Result:
The default name in search name field displays user ID instead of user name
The same goes for report ID when In filter is used for chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/46155072-abba-4447-97c0-5a1d14b90a23

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839048305434680628</li>
        <li>Upwork Job ID: 1839048305434680628</li>
        <li>Last Price Increase: 2024-09-25</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Reviewer | 104132486</li>
<li>Nodebrute | Contributor | 104132487</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rayane-djouah</details>

**Comment by lanitochka17** [comment] 2024-09-25 19:48
We think that this bug might be related to #wave-control

**Comment by stitesExpensify** [comment] 2024-09-26 20:04
Tested 🟢 
<img width="1728" alt="2024-09-26_13-44-10" src="https://github.com/user-attachments/assets/6ca3aacf-6c99-4513-bab4-6d08db9caaf6">

**Comment by luacmartins** [comment] 2024-09-30 12:53
This is no longer a blocker since it was already fixed on the previous checklist

**Comment by kadiealexander** [comment] 2024-10-07 00:39
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@rayane-djouah] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@rayane-djouah] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@rayane-djouah] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@rayane-djouah] Determine if we should create a regression test for this bug.
- [ ] [@rayane-djouah] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@kadiealexander] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by kadiealexander** [comment] 2024-10-07 00:41
Payouts due:

- [ ] Contributor: $250 @Nodebrute 
- [ ] Contributor+: $250 @rayane-djouah 

Upwork job is [here](https://www.upwork.com/jobs/~021839048305434680628).

**Comment by luacmartins** [comment] 2024-10-09 17:21
We'll add tests as part of the project wrap uo

**Closed** 2024-10-14 05:45 UTC
Labels: Reviewing, External, Engineering, Daily, Awaiting Payment, Bug
