### ISSUE TITLE
Android - Chat - Composer with edited message opens again after saving changes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43751] opened 2024-06-14 10:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  https://expensify.testrail.io/index.php?/tests/view/4631009https://expensify.testrail.io/index.php?/tests/view/4631009
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the app and log in with an account that has a lot of chats
2. Open a report that already has some messages
3. Send a message
4. Long tap > Edit comment
5. Change the comment to anything else
6. Save the changes
7. Create a thread
8. Open the tread and edit the parent message

## Expected Result:
Composer with with edited message closes, and changes are saved

## Actual Result:
The composer with edited message opens up again after saving changes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/93d0c637-9cc1-443f-b577-fa32f0fd39e6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-14 10:47
@garrettmknight  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-14 10:47
We think that this bug might be related to #vip-vsp

**Comment by garrettmknight** [comment] 2024-06-17 14:32
Can't reproduce on 1.4.84-2. Closing.

**Closed by garrettmknight** 2024-06-17 14:32 UTC
Labels: Daily, Overdue, Bug
