### ISSUE TITLE
[Payment 2024-10-07] [$250] Android-Chat-The top of emojis are cut off on applying quote markdown

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47899] opened 2024-08-23 06:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.24
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4884616
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Laugh app
2. Tap on a chat
3. Enter > 😁😄😃😡😡
4. Send the message

## Expected Result:
The top of emojis must not be cut off on applying quote markdown.

## Actual Result:
The top of emojis are cut off on applying quote markdown.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3dc2e163-b5a8-499f-b433-04421ae787e7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01550e0f7b3eac50c6</li>
        <li>Upwork Job ID: 1829238843117327522</li>
        <li>Last Price Increase: 2024-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Reviewer | 103831336</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment] 2024-08-23 06:14
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by strepanier03** [comment] 2024-08-29 19:25
Easy to reproduce with any combo of emoji.

**Comment by shawnborton** [comment] 2024-09-05 12:15
I think we'd follow the same styles that regular messages have. So whatever we do for normal emoji-only messages, we'd do here for blockquotes as well.

**Comment by aldo-expensify** [comment] 2024-10-01 18:27
> @aldo-expensify Is this one ready for payment?

I think it should be cc @strepanier03

**Comment by strepanier03** [comment] 2024-10-07 17:42
Looks like automation failed, handling this now.

**Comment by strepanier03** [comment] 2024-10-07 17:47
@daledah - It doesn't look like you applied for the job as requested [here](https://github.com/Expensify/App/issues/47899#issuecomment-2332027263). Can you do that so I can pay you or can you link your Upwork profile so I can find you to hire you?

----

@hoangzinh - I've paid and closed your contract in Upwork, thanks!

**Comment by strepanier03** [comment] 2024-10-08 21:28
@daledah - I had to make a new job since the original one is closed now, but I've hired you to the new job. 

I'll keep an eye out for your acceptance so I can pay it and close this.

**Comment by strepanier03** [comment] 2024-10-09 03:48
Thanks @daledah - I've paid and closed the contract. Have a great rest of the week 👋

**Closed by strepanier03** 2024-10-09 03:48 UTC
Labels: External, Daily, Awaiting Payment, Bug
