### ISSUE TITLE
[HOLD for payment 2023-10-23][$500] Distance IOU - Save button inifinetly loading when opened from distance

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#28971] opened 2023-10-06 00:09 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Navigate to a workspace chat
3. Tap "+" > Request money
4. Select "Distance" and create a money request
5. Navigate to the money request detail screen
6. Tap "Distance"
7. Without making any changes, tap the "Save" button

## Expected Result:
User is navigated back to the money request detail screen

## Actual Result:
The "Save" button is infinitely loading

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-3

**Reproducible in staging?:** Yes

**Reproducible in production?:** No, when Distance is opened in production, it navigates to the merchant screen

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/7ef59922-df5f-4762-b017-07d27a00bff1

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011d07e671b703f4b0</li>
        <li>Upwork Job ID: 1710417168605065216</li>
        <li>Last Price Increase: 2023-10-06</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27066246</li>
</ul></li>
    </ul>
</details>

**Comment by Beamanator** [comment] 2023-10-06 06:24
console error when following the steps in staging:

> [Onyx] An error occurred while applying merge for key: transactions_1383468151344720381, Error: TypeError: Cannot read properties of null (reading 'pendingFields')

**Comment by Beamanator** [comment] 2023-10-06 06:30
It seems like the backend is sending undefined updates or something

<img width="1143" alt="Screenshot 2023-10-05 at 1 28 49 PM" src="https://github.com/Expensify/App/assets/3885503/c0182786-2ba0-4f78-aee8-56ef43f5813c">

**Comment by Beamanator** [comment] 2023-10-06 06:52
Fix is up, asking for volunteers to review

**Comment by s-alves10** [comment] 2023-10-06 07:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In edit distance money request, save button shows infinite loading when saving without change

### What is the root cause of that problem?

We don't check change status of waypoint inputs when saving. And the backend returns onyx merge data `null` for the transaction for the `UpdateDistanceRequest` API if there is no change.

We set the `isLoading` to true optimistically and set to true when API call is finished
https://github.com/Expensify/App/blob/779a1e5b5ee19ac2b8e54d047507f90db01df689/src/libs/actions/IOU.js#L754

Onyx merging with `null` failed and can't merge `successData` and `failureData` and so `isLoading` remains true
This is the root cause

### What changes do you think we should make in order to solve the problem?

We can fix this in frontend or backend, but I suggest to update both the frontend and backend
1. Backend should not return onyx merge `null` in any case
2. Frontend should not call the API if waypoints data are not changed. We can go back simply if there is no change


### What alternative solutions did you explore? (Optional)

**Comment by Beamanator** [comment] 2023-10-06 07:26
Looks like this bug exists on prod too :'(


https://github.com/Expensify/App/assets/3885503/965e3390-82e4-4c43-9b91-9c7cb569aaba

**Comment by Beamanator** [comment] 2023-10-06 07:29
Not a deploy blocker, though [the backend fix](https://github.com/Expensify/Web-Expensify/pull/39100) was merged.

Going to see if any internal eng working on distance requests wants to deal with this

**Comment by redpanda-bit** [comment] 2023-10-06 16:16
Is the backend not supposed to return `value: null` for onyx merge updates?

**Comment by neil-marcellini** [comment] 2023-10-06 22:10
I like the [proposal](https://github.com/Expensify/App/issues/28971#issuecomment-1750084309) from @s-alves10 so I hired him to implement it now.

**Comment by s-alves10** [comment] 2023-10-07 09:59
@burczu @neil-marcellini 

PR is ready for review https://github.com/Expensify/App/pull/29047

**Comment by petriyamamoto** [comment] 2023-10-16 01:37
qw

**Comment by Beamanator** [comment] 2023-10-23 09:44
looks like this is ready for payment, not overdue

**Comment by lschurr** [comment] 2023-10-23 16:03
@s-alves10 could you work on [the checklist](https://github.com/Expensify/App/issues/28971#issuecomment-1765319649)?

**Comment by lschurr** [comment] 2023-10-23 16:08
Could you also accept the offer in Upwork @s-alves10 - https://www.upwork.com/nx/wm/offer/27066246

**Comment by s-alves10** [comment] 2023-10-23 16:14
@lschurr 

I think C+ member would work on checklist. Should I work on that?

Anyway, offer accepted, thanks

**Comment by s-alves10** [comment] 2023-10-23 18:33
Regression Test Proposal

1. Open ND and log in with any account
2. Go to a workspace chat
3. Tap "+" button and select "Request money"
4. Select "Distance" tab and create a money request with any waypoints
5. Navigate to the money request detail page
6. Tap "Distance"
7. Tap "Save" button without any changes
8. Verify that user is navigated back to the money request detail page
9. Tap "Distance" again and make some changes to the waypoints
10. Tap "Save" button
11. Verify that the waypoints data are saved and navigated to the money request detail page

Do we agree 👍 or 👎

**Comment by lschurr** [comment] 2023-10-23 20:46
Payment summary:

- Bug reporter: Applause (no payment)
- Contributor: @s-alves10 $750
- Contributor+: Internal (no payment)

**Comment by lschurr** [comment] 2023-10-23 20:48
All done. Closing!

**Closed by lschurr** 2023-10-23 20:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
