### ISSUE TITLE
[$500] Workspace Members - Deleted Workspace members appears for some moment again for special account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27717] opened 2023-09-18 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with [applausetester+ihchat4_1809_2@applause.expensifail.com](mailto:applausetester+ihchat4_1809_2@applause.expensifail.com)
account
3. Go to Settings -> Workspaces -> Open any Workspace
4. Go to Members -> Invite -> Add several members -> Delete all members

## Expected Result:
Deleted WS members NOT appears

## Actual Result:
Deleted WS members appears for some moment again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.71-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/aca5376e-a54c-4a97-b385-72c3c5997d07

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012a49d9c0dbb8e449</li>
        <li>Upwork Job ID: 1705059616732712960</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-09-22 03:20
Confirmed this is a bug.

**Comment by sakluger** [comment] 2023-09-29 04:33
Still no proposals, if we haven't gotten any by Monday, I'll ask our expert contributors if they'd like to work on it.

**Comment by sakluger** [comment] 2023-10-02 20:22
Asked Callstack for volunteers to work on this: https://expensify.slack.com/archives/C03UK30EA1Z/p1696278141992759

**Comment by arthurmfgtab** [comment] 2023-10-04 03:52
Hey, @sakluger, I'm Arthur from Callstack - expert contributor group - and I would like to take a look at this issue.

**Comment by sakluger** [comment] 2023-10-05 01:43
Thanks @arthurmfgtab! Could you please review the issue and put together a proposal that @thesahindia could review?

**Comment by mvtglobally** [comment] 2023-10-05 03:02
Issue not reproducible during KI retests. (First week)

**Comment by sakluger** [comment] 2023-10-05 05:57
@mvtglobally just to confirm, deleted workspace members no longer re-appear on our latest build?

**Comment by arthurmfgtab** [comment] 2023-10-10 09:25
@mvtglobally can you confirm if this is fixed on the latest build? I'm also not able to reproduce this 🤔

**Comment by mvtglobally** [comment] 2023-10-12 03:42
Issue not reproducible during KI retests. (Second week)

**Comment by sakluger** [comment] 2023-10-12 06:30
Alrighty, seems like this is not reproduceable. Thanks @arthurmfgtab for stepping up to help, but looks like we can close this one!

**Closed by sakluger** 2023-10-12 06:30 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
