### ISSUE TITLE
[$250] Desktop - Log in - Unable to log in via browser pop-up "Open New Expensify"

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45245] opened 2024-07-11 10:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Launch New Expensify desktop app.
2. Log out if logged in.
3. Log in to ND on browser.
4. Refresh ND on browser.
5. Click Open New Expensify on the pop-up.

## Expected Result:
New Expensify desktop app will be logged in.

## Actual Result:
New Expensify desktop app is still not logged in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ac3e7fb3-ddcf-4de5-9d4e-7bb1a6d44c4d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01df3b8c2e08677d11</li>
        <li>Upwork Job ID: 1811708185386013955</li>
        <li>Last Price Increase: 2024-07-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @hungvu193</details>

**Comment by izarutskaya** [comment] 2024-07-11 10:44
@bfFYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-07-11 10:45
We think this issue might be related to the  #vip-vsb

**Comment by danieldoglas** [comment] 2024-07-12 10:15
Not a web deploy blocker

**Comment by Julesssss** [comment] 2024-07-12 10:24
Asking for a retest, it sounds similar to our other redirect bugs.

**Comment by hungvu193** [comment] 2024-07-14 07:50
I can't reproduce on latest main

**Comment by wasxxm** [comment] 2024-07-14 21:25
I am not able to reproduce the issue. The desktop app gets logged in.

**Comment by kavimuru** [comment] 2024-07-14 22:08
Bug is not reproducible anymore.

https://github.com/user-attachments/assets/886137ae-21e4-4ef4-afff-6c56ea4c2c1a

**Comment by Julesssss** [comment] 2024-07-15 09:05
Closing as no longer reproducable

**Closed by Julesssss** 2024-07-15 09:05 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
