### ISSUE TITLE
[$750] Chat - Additional menu opens if you log in to a new account that was previously added to the WS

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24132] opened 2023-08-03 22:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS -> Invite any non-existing account
4. Log out
5. Login with new account from step 3

## Expected Result:
The additional menu NOT opens automatically in the WS chat

## Actual Result:
The additional menu opens automatically in the WS chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.50.0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6152297_0408](https://github.com/Expensify/App/assets/78819774/f038fa1a-a58c-415b-a025-03f289d55df1)

https://github.com/Expensify/App/assets/78819774/c6c95daa-cb2a-4c33-9672-ba84332fdaca

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0116c08afc99f4ba25</li>
        <li>Upwork Job ID: 1697194166944210944</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-08-07 20:05
@lanitochka17 I am unable to reproduce this

**Comment by NicMendonca** [comment] 2023-08-07 20:07
This is what I see when I log in: 

<img width="1239" alt="image" src="https://github.com/Expensify/App/assets/24947345/1b89bd3d-44eb-4c74-839a-57502f4b4f4e">

**Comment by NicMendonca** [comment] 2023-08-10 14:57
closing since I am unable to repro

**Comment by lanitochka17** [comment] 2023-08-30 18:38
Issue reproducible on Build 1.3.59-4

https://github.com/Expensify/App/assets/78819774/3af9e0bd-1381-425e-b4af-56fb261a76a1

![image](https://github.com/Expensify/App/assets/78819774/27f0a294-78d0-4391-a68a-e2efbd626111)

**Comment by NicMendonca** [comment] 2023-08-31 19:01
@lanitochka17 tips please? I cannot reproduce this...........

**Comment by NicMendonca** [comment] 2023-09-11 12:48
bumped to $750

**Comment by mvtglobally** [comment] 2023-09-13 17:21
Issue not reproducible during KI retests. (First week)

**Comment by NicMendonca** [comment] 2023-09-13 21:41
> Issue not reproducible during KI retests. (First week)

😅 I am going to close this for now

**Closed by NicMendonca** 2023-09-13 21:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
