### ISSUE TITLE
[$500] Web - Searching for rooms for the first time without hashtags does not work. 

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#34475] opened 2024-01-13 16:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @justinpersaud 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1705002380962489

## Action Performed:
1. Create a room with workspace visibility as account A
2. Invite user B
3. Login as user B
4. Search for the room created in step 1 without hashtag
## Expected Result:
Room is able to find
## Actual Result:
It does not show the result
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3f2aaa04-9c35-42c3-b70c-0256b6487203

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015f0d8aaddbf938d1</li>
        <li>Upwork Job ID: 1747032811175395328</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2024-01-15 23:08
Hoping/guessing this can be External. @getusha , comment if you disagree.  Thx

**Comment by abzokhattab** [comment] 2024-01-15 23:14
I see in the attached video that the room is already found as the third result when typing "big", what is the problem here? @justinpersaud

**Comment by shubham1206agra** [comment] 2024-01-16 08:18
## Proposal
### Please re-state the problem that we are trying to solve in this issue

Searching for rooms for the first time without hashtags does not work

### What is the root cause of that problem?

This happens because we have provided full room name with `#`, which might make the search different from anticipated.

Function call

`OptionsListUtils.getSearchText(report, reportName, participantPersonalDetailList, result.isChatRoom || result.isPolicyExpenseChat, result.isThread);`

### What changes do you think we should make in order to solve the problem?

We can add a stripped version of title in searchText here (similarly in other places too)

https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/OptionsListUtils.js#L332

We can use similar approach to https://github.com/Expensify/App/blob/8e2fb675389bb84deee4b8e001a536252883e72f/src/libs/OptionsListUtils.js#L320

The motivation behind this is https://github.com/Expensify/App/issues/33029 will perform similar stripping before doing sorting on the display name. So its natural to add a stripped version in search text. We will also keep the original version in case user tries to search with stripped symbols.


### What alternative solutions did you explore? (Optional)

**Comment by shubham1206agra** [comment] 2024-01-16 08:19
@mallenexpensify Can you add this to `#vip-vsb`, and maybe same priority as https://github.com/Expensify/App/issues/33029?

**Comment by getusha** [comment] 2024-01-22 12:03
@shubham1206agra I am not able to reproduce this on staging.

<img width="1394" alt="Screenshot 2024-01-22 at 3 02 40 PM" src="https://github.com/Expensify/App/assets/75031127/64337782-e0f8-448a-8027-b14370346454">

**Comment by muttmuure** [comment] 2024-01-22 16:20
The bug seems to be a little inconsistent

**Comment by muttmuure** [comment] 2024-01-22 16:21
I can only reproduce if I search for a room I haven't returned in search in that session yet (but I know exists and I am a member of it)

**Comment by getusha** [comment] 2024-01-23 21:13
Still trying to reproduce this, will try to provide an update by tomorrow.

**Comment by justinpersaud** [comment] 2024-01-24 14:52
What @muttmuure described is exactly what the issue is. It only happens if you haven't found the room or searched for it before.

**Comment by allroundexperts** [comment] 2024-01-24 16:04
I can try to reproduce this today.

**Comment by roryabraham** [comment] 2024-01-24 19:57
slack context: https://expensify.slack.com/archives/C02NK2DQWUX/p1706108522357449

**Comment by allroundexperts** [comment] 2024-01-24 22:17
Okay. I was able to reproduce this.

https://github.com/Expensify/App/assets/30054992/19a0f157-189a-4c84-a8bd-54eb60652885

@shubham1206agra Thanks for your proposal. I think your RCA is not very clear. Do you mind explaining why it works some times but not other?

**Comment by roryabraham** [comment] 2024-01-24 23:52
Great, going to make @allroundexperts the C+ here

**Comment by allroundexperts** [comment] 2024-01-29 20:47
I guess @shubham1206agra is busy with other issues. Still looking for better proposals here.

**Comment by mvtglobally** [comment] 2024-01-30 04:48
Issue not reproducible during KI retests. (First week)

**Comment by quinthar** [comment] 2024-02-01 04:51
If we can't reproduce, can we close this?

**Comment by mallenexpensify** [comment] 2024-02-02 02:08
I _think_ it might still be repro, asking in #social for a few room names I haven't already visited

**Comment by muttmuure** [comment] 2024-02-05 18:42
I can still reproduce this. I can't remember the last time I searched for this room, but I did it now:

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/8359c04d-6013-425a-9c7e-c901a02f4b0d">

Then after searching for it once, I searched again and it worked: 

<img width="1512" alt="image" src="https://github.com/Expensify/App/assets/46995600/c002d786-eaca-42a1-811c-113a6d76cb9d">

I remember we made some changes to `OptionList` where we were limiting the number of chats returned by search, and [we added a debounce](https://github.com/Expensify/App/pull/33347).

It's just a theory, but I wonder if the debounce before querying the full list is engaged AFTER the initial input, and then if you search again we are actually querying from your "full" list. This would make sense in terms of the expected behavior here, because we can all retrieve a result that we have searched for recently.

**Comment by muttmuure** [comment] 2024-02-05 18:50
asked about this here: https://expensify.slack.com/archives/C03UK30EA1Z/p1707158970024939

**Comment by waterim** [comment] 2024-02-06 10:42
Hello, Im Artem from Callstack and would like to help with this issue!

**Comment by mallenexpensify** [comment] 2024-02-06 23:17
Thanks @waterim , assigned!

**Comment by mallenexpensify** [comment] 2024-02-07 17:38
Thanks @waterim , I'm unsure if I'm able to reproduce either.  
@muttmuure can you try to search for this without the # and see if it shows?
<img width="236" alt="image" src="https://github.com/Expensify/App/assets/22508304/136703fc-dcfe-40ad-b886-b625fb042641">


Also.. can you create a new test room on the `Expensify Chat` workspace and drop in the name here and I can try to search too.  If neither of us can reproduce, we can likely close this

**Comment by mallenexpensify** [comment] 2024-02-08 22:24
Gonna close this, just tested again with a room I'm 99% I've never searched for or visited and it showed in search, so I think it might have _magically_ been fixed. 

https://github.com/Expensify/App/assets/22508304/37657259-8fc9-4879-89ff-c39f039cea99

**Closed by mallenexpensify** 2024-02-08 22:24 UTC
Labels: External, Engineering, Daily, Bug
