### ISSUE TITLE
Payment - Adding payment method for first time shows a console warning

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21302] opened 2023-06-22 11:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to settings
3. Click on payment methods.
4. Click on Add Payment Method.

## Expected Result:
No Console Warning Should Be Displayed

## Actual Result:
 Console Warning Is Displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.28-0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Simulator Screen Shot - iPhone 13 Pro - 2023-06-21 at 04 24 04](https://github.com/Expensify/App/assets/93399543/66f2e18f-0179-472f-be52-b56ba256bfc9)

https://github.com/Expensify/App/assets/93399543/1aa888be-b6e0-4e2d-be4f-99c9643b64bd

**Expensify/Expensify Issue URL:**

**Issue reported by:** @syedsaroshfarrukhdot 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686778963750789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by ahmedGaber93** [comment] 2023-06-22 11:15
Duplicate https://github.com/Expensify/App/issues/20688, but it closed there.
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Console error on add payment method popup in payments
```
Warning: Failed prop type: The prop `anchorPosition.horizontal` is marked as required in `PopoverWithMeasuredContent`, but its value is `undefined`.
    at PopoverWithMeasuredContent
```    
### What is the root cause of that problem?
After click on add payment method, we show menu list to select the new payment method [here](https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L416-L424).

This menu is based on `PopoverWithMeasuredContent` which require props to specific the position that the menu need it.
https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/components/PopoverWithMeasuredContent.js#L19-L22

We use `lib/getClickedTargetLocation` to get the click position on web only and return default values in native because the popover will be bottom mounted.
https://github.com/Expensify/App/blob/1af8b3bda2fe75ab1bc939071e5dd80d7b548ec5/src/libs/getClickedTargetLocation/index.native.js#L1-L11
the issue is the values above doesn't have the x and y values, so it returns as undefined on native mobile.
https://github.com/Expensify/App/blob/cb522f3a60b5aec645d2824297e0c38168895504/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L159-L160
### What changes do you think we should make in order to solve the problem?
edit [getClickedTargetLocation](https://github.com/Expensify/App/blob/1af8b3bda2fe75ab1bc939071e5dd80d7b548ec5/src/libs/getClickedTargetLocation/index.native.js) to return the same object in the web.
```javascript
{
  "x": 0,
  "y": 0,
  "width": 0,
  "height": 0,
  "top": 0,
  "right": 0,
  "bottom": 0,
  "left": 0
}
```
or only add x and y.

### What alternative solutions did you explore? (Optional)

**Comment by laurenreidexpensify** [comment] 2023-06-22 12:51
Agree that this is only a bug on dev and not user facing so we don't need to fix. Closing

**Closed by laurenreidexpensify** 2023-06-22 12:51 UTC
Labels: Daily, Needs Reproduction, Bug
