### ISSUE TITLE
[$500] [CRITICAL] [UX Reliability] SelfDM report name changes to first-name, Expensify

### ISSUE THREAD

**Issue by mountiny** [Expensify/App#43641] opened 2024-06-13 09:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:** https://expensify.slack.com/archives/C036QM0SLJK/p1718107098829729?thread_ts=1718018633.472059&cid=C036QM0SLJK

## Action Performed:
Break down in numbered steps

1. I signed up.
1. I went through onboarding.
1. I tracked an expense
1. I ended up submitting to someone else
1. You can see my selfDM show up as at Daniel, Expensify at 2:44 and 3:38

## Expected Result:
Describe what you think should've happened

The report name of the selfDM should be: `Users name (you)`

## Actual Result:
Describe what actually happened

The name is Daniel, Expensify

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

https://github.com/Expensify/App/assets/36083550/aab48a0c-a727-44e3-913f-5e3fd79534d8

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c45c4ee733bcb895</li>
        <li>Upwork Job ID: 1801180736227336193</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @thienlnam</details>

**Comment by truph01** [comment] 2024-06-13 09:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SelfDM report name changes to first-name, Expensify

### What is the root cause of that problem?
After the user submit an expense to someone else, the Concierge user will be added to the `participants` list of the Self DM report, so the report name changes to "Username, Expensify"

### What changes do you think we should make in order to solve the problem?

We should exclude the Concierge users when getting the participantAccountIDs list of that report [here](https://github.com/Expensify/App/blob/e9799d9b577ed32ce95118981e268a12ade5d0b3/src/libs/ReportUtils.ts#L1846).

-> Check the report to see is it self-DM, if true, filter out the `CONST.ACCOUNT_ID.CONCIERGE` from the participant list

### What alternative solutions did you explore? (Optional)
NA

**Comment by truph01** [comment] 2024-06-13 09:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
SelfDM report name changes to first-name, Expensify

### What is the root cause of that problem?
After the user tracks expense, the Concierge user will be added to the `participants` list of the Self DM report, so the report name changes to "Username, Expensify"

### What changes do you think we should make in order to solve the problem?

We should exclude the Concierge users when getting the participantAccountIDs list of that report [here](https://github.com/Expensify/App/blob/fc6d67eb366ad79267bff6ac9ef62ccdf4713f9f/src/pages/home/HeaderView.tsx#L99).

-> Check the report to see is it self-DM, if true, filter out the `CONST.ACCOUNT_ID.CONCIERGE` from the participant list

That will fix the report header case, same fix is needed in other locations such as `getParticipantAccountIDs`

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-06-13 10:40
But the report name is sometimes correct isnt it? 

Cc @thienlnam for vis

**Comment by truph01** [comment] 2024-06-13 11:47
@mountiny Only after "Track expense", the back-end returns Expensify as a participant. I guess it's because we're showing this, with Concierge as the actor 
<img width="371" alt="Screenshot 2024-06-13 at 6 46 20 PM" src="https://github.com/Expensify/App/assets/170341821/70c83450-d042-4d8a-b078-ae801f58b282">

Before that, the report name is correct.

**Comment by abzokhattab** [comment] 2024-06-13 13:18
I think this is more of a backend issue. Filtering the participants list needs to be done in multiple locations on the frontend, so it's best to fix it from the backend.

**Comment by thienlnam** [comment] 2024-06-13 21:37
Agree we should handle this in the BE - I guess it's technically correct, but the self-DM should always just show as Name (self)

**Comment by abzokhattab** [comment] 2024-06-13 22:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Self dm report name changes to username , Expensify
### What is the root cause of that problem?
 
After submitting the tracked expense, the backend returns the CONCIERGE ID in the returned participants list, causing the frontend to render the report name as user, Expensify here: https://github.com/Expensify/App/blob/f13c27e883f6dfe9b4154b6f1d337f20775acaa2/src/pages/home/HeaderView.tsx#L95-L104
### What changes do you think we should make in order to solve the problem?
We should check if the current report is a self DM, then make the report name as Name (you) without checking other participants in the participants list. To do that, we need to change this condition:

https://github.com/Expensify/App/blob/f13c27e883f6dfe9b4154b6f1d337f20775acaa2/src/pages/home/HeaderView.tsx#L97-L100 
to: 

```js
 const participants = Object.keys(report?.participants ?? {})
        .map(Number)
        .filter((accountID) => (!isSelfDM && (accountID !== session?.accountID || (!isOneOnOneChat && !isSystemChat))) || (isSelfDM && accountID === session?.accountID))
        .slice(0, 5);
```
 
and make the same change in other similar utilizations.



### alternatively 


Instead of making this change everywhere, we can just modify the `getDisplayNamesWithTooltips` function since it already takes the `isSelfDM` argument. We can use this argument to check if it is `true`, then return the self DM report.

To achieve that, we need to add a new variable inside the function that would only return the self DM if the self DM is true:


```js
   ....
    const filteredPersonalDetailsListArray = shouldAddCurrentUserPostfix
        ? [personalDetailsListArray.find((user) => user?.accountID === currentUserAccountID)] 
        : personalDetailsListArray;

    return filteredPersonalDetailsListArray.map ..........
```

**Comment by abzokhattab** [comment] 2024-06-13 22:42
>  Agree we should handle this in the BE - I guess it's technically correct, but the self-DM should always just show as Name (self)

 a very good point as well, the self dm should always return the self dm title regardless of how many participants the backend is returning.. i added a proposal tackling this point, in case we deicded to go in this direction.

**Comment by abzokhattab** [comment] 2024-06-14 12:27
> I think the proposal is incomplete @abzokhattab. There are many places where getDisplayNamesWithTooltips is used. Targeting that to solve this issue will create more issues.

 that's is the idea .. tackling it in all places with one change .. do have a case where this will cause a regression?

**Comment by truph01** [comment] 2024-06-14 13:26
@parasharrajat I updated my alternative solution to clarify it, I think it's the best way to fix this issue. The root cause here is the way we get the `participants`, not the way we get `displayNamesWithTooltips`. The `getDisplayNamesWithTooltips` should only does what it does which is to format personalDetails into a list of display name with tooltip content, it should not be involved in any participant setting logic.

At the same time, fixing in `getDisplayNamesWithTooltips` still means the participants list of the report being used everywhere else are still wrong, like [here](https://github.com/Expensify/App/blob/fc6d67eb366ad79267bff6ac9ef62ccdf4713f9f/src/pages/home/HeaderView.tsx#L101). So it's not the root cause to fix IMO.

Let me know what you think.

**Comment by truph01** [comment] 2024-06-14 13:30
> The participants retrieving logic is fragmented and duplicated across many places (examples are [one](https://github.com/Expensify/App/blob/fc6d67eb366ad79267bff6ac9ef62ccdf4713f9f/src/pages/home/HeaderView.tsx#L97-L100), [two](https://github.com/Expensify/App/blob/main/src/components/ReportWelcomeText.tsx#L44-L46), [three](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L262-L264), ..), this change will hep consolidate them

@parasharrajat By the way, my solution will fix at least another bug/inconsistency. It's the inconsistency between [this](https://github.com/Expensify/App/blob/main/src/components/ReportWelcomeText.tsx#L44-L46) and [this](https://github.com/Expensify/App/blob/main/src/libs/SidebarUtils.ts#L262-L264)

(one returns the `participants` based on `isSystemChat` condition, the other doesn't. This also happens because we're pasting the participants-retrieving logic everywhere and when we update the logic, we forget to update all places.

**Comment by abzokhattab** [comment] 2024-06-14 14:30
Okay then i modified the main solution to solve the issue globally...  also notice that we need to fix the issue everywhere (LHN and startChat and other options selector)  not only the header view .. so i think the main solution will be fine

**Comment by mountiny** [comment] 2024-06-14 14:49
Maybe it would be better to fix this in the backend solely. @thienlnam would you be interested in taking this over given the context in this domain?

**Comment by thienlnam** [comment] 2024-06-14 15:43
Yeah, I can do take this one

**Comment by joekaufmanexpensify** [comment] 2024-06-14 19:33
As an fyi, I am going on OOO until 2024-06-25. Adding another BZ assignee in the interim until then. Likely won't be much for you to do since we just found an internal volunteer for this issue, but adding just in case. 

I will take this over once I'm back!

**Comment by laurenreidexpensify** [comment] 2024-06-17 08:18
Not overdue @thienlnam is going to get this moving

**Comment by laurenreidexpensify** [comment] 2024-06-19 17:49
Looks like there is a PR in draft 👍

**Comment by thienlnam** [comment] 2024-06-19 23:14
PR in review now

**Comment by laurenreidexpensify** [comment] 2024-06-20 13:33
@joekaufmanexpensify I'm unassigning cos of parental leave, but given a PR is in review and you're back on Tues, am not re-assigning to someone else, as that is a bit overzealous!

**Comment by joekaufmanexpensify** [comment] 2024-06-24 13:30
Makes sense. TY!

**Comment by joekaufmanexpensify** [comment] 2024-06-24 13:31
@thienlnam I see the auth PR was deployed. Is there anything else needed before we close this?

**Comment by thienlnam** [comment] 2024-06-24 17:36
Should be fixed now!

**Closed by thienlnam** 2024-06-24 17:36 UTC
Labels: Reviewing, Weekly, Internal, Bug, AutoAssignerNewDotQuality
