### ISSUE TITLE
[HOLD for payment 2023-08-02] [$250] Migrate ReportSettingsPage.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16250] opened 2023-03-20 08:52 UTC
### Filenames
- [ ] [src/pages/ReportSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReportSettingsPage.js)
    - **type:** `React.Component`
    - **has state values:** false
    - **has refs:** false
    - **has context:** false
    - **lifecycle methods:** none

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01248a2f79831e8cf8</li>
        <li>Upwork Job ID: 1678837689196437504</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-06-06 11:11
I'd love to work on this.

**Comment by payal-lathidadiya** [comment] 2023-07-04 18:21
I'm interested to work on this

**Comment by alpeshl** [comment] 2023-07-05 12:53
Can I work on this?

**Comment by olexyt** [comment] 2023-07-07 14:56
I can work on this issue.

**Comment by alexxxwork** [comment] 2023-07-11 18:46
I would love to work on this issue

**Comment by payal-lathidadiya** [comment] 2023-07-11 18:47
dibs?

**Comment by alpeshl** [comment] 2023-07-11 18:47
Can I work on this?

**Comment by yh-0218** [comment] 2023-07-11 18:48
I can work on this task. Thanks.

**Comment by disha-np** [comment] 2023-07-11 18:49
I'd like to work on this

**Comment by crazy-coding** [comment] 2023-07-11 18:49
I'd love to work on this.

**Comment by kmwamasali** [comment] 2023-07-11 18:50
would like to work on this

**Comment by mejed-alkoutaini** [comment] 2023-07-11 18:54
I'm able to work on this if needed!

**Comment by vadymbokatov** [comment] 2023-07-11 18:54
I'd love to work on this issue

**Comment by KrAbhas** [comment] 2023-07-11 19:00
I would like to work on this

**Comment by vdem0115** [comment] 2023-07-11 19:00
I can work on this

**Comment by Talha345** [comment] 2023-07-11 19:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

We are trying to refactor `ReportSettingsPage.js` from a class component to a function component.

### What is the root cause of that problem?

N/A

### What changes do you think we should make in order to solve the problem?

We should understand the existing class component and re-write it using functional syntax. Class states and lifecycle methods should be updated to use hooks (useState, useEffect) and references to props should be converted to prop arguments.

Finally, the references to the component should be updated and testing should be done to make sure everything is working correctly.

### What alternative solutions did you explore? (Optional)

N/A

**Comment by AnshuAgarwal24** [comment] 2023-07-11 19:53
dibs?

**Comment by AnshuAgarwal24** [comment] 2023-07-11 19:58
Contributor details
Your Expensify account email: <anshu.ragarwal24@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~016dc1c534e8bf37fc>

**Comment by AnshuAgarwal24** [comment] 2023-07-11 20:00
Contributor details
Your Expensify account email: <anshu.ragarwal24@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/~016dc1c534e8bf37fc?viewMode=1>

**Comment by AnshuAgarwal24** [comment] 2023-07-11 20:02
Contributor details
Your Expensify account email: anshu.ragarwal24@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016dc1c534e8bf37fc

**Comment by vadymbokatov** [comment] 2023-07-11 20:03
Contributor details
Your Expensify account email: vadymbakatovdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01eb98dceed660ed38

**Comment by AnshuAgarwal24** [comment] 2023-07-11 20:05
Contributor details
Your Expensify account email: anshu.ragarwal24@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016dc1c534e8bf37fc

**Comment by AnshuAgarwal24** [comment] 2023-07-11 20:15
dibs?

**Comment by ishpaul777** [comment] 2023-07-11 20:52
I would like to work on this..

**Comment by to-ai** [comment] 2023-07-11 21:18
I am able to work on this task.

**Comment by mkhutornyi** [comment] 2023-07-11 21:31
I'd like to work on this.

**Comment by jagdisharma** [comment] 2023-07-11 22:15
Hi,
For updating the class component to a functional component, we have to convert class states and lifecycle methods to use hooks for eg: useState, useEffect and props should be converted to prop arguments.
and then the HTML part needs to be updated based on the state and props we are using.
Thanks

**Comment by galaxydeve** [comment] 2023-07-11 22:25
Contributor details
Your Expensify account email: [galaxyaio@hotmail.com](mailto:galaxyaio@hotmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/haiquanhuang
JSS 100% Top Rated Plus React.js expert here.
I can handle this task and really want to start working on Expensify from this task.

**Comment by galaxydeve** [comment] 2023-07-11 22:26
JSS 100% Top Rated Plus React.js expert here.
I can handle this task and really want to start working on Expensify from this task.

**Comment by galaxydeve** [comment] 2023-07-11 22:29
Contributor details
Your Expensify account email: [galaxyaio96@gmail.com](mailto:galaxyaio96@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/haiquanhuang

**Comment by jagdisharma** [comment] 2023-07-11 22:31
Contributor details
Your Expensify account email: jagdishcsharma29@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01f2508fe30bf11bf4

**Comment by PhantomOz** [comment] 2023-07-11 23:15
> ## Class Component Migration
> ### Filenames
> * [ ]  [src/pages/ReportSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReportSettingsPage.js)
>   
>   * **type:** `React.Component`
>   * **has state values:** false
>   * **has refs:** false
>   * **has context:** false
>   * **lifecycle methods:** none
> 
> ### Task
> * We currently have some class components in our codebase that we would like to refactor to a function component.
> * Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
> * If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
> * Test for any regressions and verify that there are no breaking changes
> 
> Upwork Automation - Do Not Edit

This file does not exist on the repo

**Comment by PhantomOz** [comment] 2023-07-11 23:26
> ## Class Component Migration
> ### Filenames
> * [ ]  [src/pages/ReportSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReportSettingsPage.js)
>   
>   * **type:** `React.Component`
>   * **has state values:** false
>   * **has refs:** false
>   * **has context:** false
>   * **lifecycle methods:** none
> 
> ### Task
> * We currently have some class components in our codebase that we would like to refactor to a function component.
> * Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
> * If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
> * Test for any regressions and verify that there are no breaking changes
> 
> Upwork Automation - Do Not Edit

> ## Class Component Migration
> ### Filenames
> * [ ]  [src/pages/ReportSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReportSettingsPage.js)
>   
>   * **type:** `React.Component`
>   * **has state values:** false
>   * **has refs:** false
>   * **has context:** false
>   * **lifecycle methods:** none
> 
> ### Task
> * We currently have some class components in our codebase that we would like to refactor to a function component.
> * Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
> * If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
> * Test for any regressions and verify that there are no breaking changes
> 
> Upwork Automation - Do Not Edit

Contributor details
Your Expensify account email: favourdoit@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~013350e6310806b468?viewMode=1

**Comment by PhantomOz** [comment] 2023-07-11 23:45
> ## Class Component Migration
> ### Filenames
> * [ ]  [src/pages/ReportSettingsPage.js](https://github.com/Expensify/App/blob/main/src/pages/ReportSettingsPage.js)
>   
>   * **type:** `React.Component`
>   * **has state values:** false
>   * **has refs:** false
>   * **has context:** false
>   * **lifecycle methods:** none
> 
> ### Task
> * We currently have some class components in our codebase that we would like to refactor to a function component.
> * Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
> * If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
> * Test for any regressions and verify that there are no breaking changes
> 
> Upwork Automation - Do Not Edit

This page Returns a 404 error

**Comment by BhuvaneshPatil** [comment] 2023-07-12 03:31
I would like to work on this issue

**Comment by avijeetpandey** [comment] 2023-07-12 12:27
Contributor details
Your Expensify account email: avijeetpandey25@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/avijeetpandey

**Comment by disha-np** [comment] 2023-07-12 16:58
Hi @fedirjh looks like duplicate assignment to @alexxxwork 

@rayane-djouah is assigned here https://github.com/Expensify/App/issues/16172#issuecomment-1632048507
@alexxxwork is assigned here https://github.com/Expensify/App/issues/16191#issuecomment-1632645174
@payal-lathidadiya is assigned here https://github.com/Expensify/App/issues/16194#issuecomment-1632658995

I'm next on the list. can this be assigned to me?

**Comment by disha-np** [comment] 2023-07-12 17:22
> > looks like duplicate assignment to @alexxxwork
> 
> The other assignment is the duplicate one.

Awh! I see. You're correct. This was reviewed earlier.

But It seems @alexxxwork already onboarded on that migration ticket https://github.com/Expensify/App/issues/16191#issuecomment-1632910211

should this be assigned to other contributor?

I can pick this

**Comment by kmwamasali** [comment] 2023-07-13 05:37
would like to work on this

**Comment by imtiazpy** [comment] 2023-07-13 06:50
### The issue: Class Component Complexity
The class component [ReportSettingsPage](https://github.com/Expensify/App/blob/main/src/pages/settings/Report/ReportSettingsPage.js) has a high complexity due to the presence of several class methods and the usage of external dependencies. This complexity can make the code harder to understand, maintain, and test. Additionally, the class component relies on higher-order components (HOCs) like `withLocalize`, `withReportOrNotFound`, and `withOnyx`, which can add additional layers of abstraction.

### The Solution: Functional Component with Hooks
To address this issue, I will convert the class component into a functional component using React hooks. Hooks allow us to manage state, handle side effects, and reuse logic in a more concise and readable manner. By leveraging hooks, you can simplify the code structure, reduce the complexity, and improve the maintainability of the component.

### Technical Explanation of Changes:
Here are the technical changes I'll make when converting the class component into a functional component:
1. Functional Component Declaration:
I will replace the class declaration with a regular function declaration.

2. Remove Class Methods:
I will convert the class methods (shouldDisableRename and shouldDisableWelcomeMessage) into regular JavaScript functions within the functional component. These functions can be placed directly inside the component.

3. Replace this.props with Function Parameters:
In the functional component, accessing the props by directly receiving them as function parameters is possible. So I will replace this.props with the appropriate function parameters throughout the component.

4. Update Imports:
I will update the imports to reflect any changes in the dependency paths or the imports required for the functional component implementation.

5. Return JSX:
Instead of the render() method, returning the JSX code directly within the functional component to render the UI is possible.

By making these changes, I'll convert the class component into a functional component. This approach simplifies the code structure, improves readability, and enhances maintainability. It also eliminates the need for HOCs, resulting in a more straightforward and concise implementation.

**Comment by imtiazpy** [comment] 2023-07-13 07:00
Contributor details
Your Expensify account email: ahmedimtiaz561@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01838636f6b962f97a

**Comment by deetergp** [comment] 2023-07-14 20:22
@NicMendonca @fedirjh I am going to be going OOO till Monday July 24th. If you need engineering import before then, feel free to remove me and re-apply the label to reassign it.

**Comment by alexxxwork** [comment] 2023-07-15 07:28
The [PR](https://github.com/Expensify/App/pull/22927) is ready

**Comment by alexxxwork** [comment] 2023-07-24 20:47
@MelvinBot the PR is merged

**Comment by NicMendonca** [comment] 2023-08-03 18:43
- reporter: NONE
- Contributor: @alexxxwork - $1500
- C+: @fedirjh - $1500

**Comment by NicMendonca** [comment] 2023-08-03 18:46
@fedirjh why? 😅 Where did we agree that?

**Comment by NicMendonca** [comment] 2023-08-03 18:55
okay - updated this to $250: https://github.com/Expensify/App/issues/16250#issuecomment-1664460291

**Closed** 2023-08-03 18:56 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment

**Comment by alexxxwork** [comment] 2023-08-03 19:26
@NicMendonca I was assigned to this issue on jul 15 and the PR was ready the same day. It was reviewed and approved by C+ on jul 18 and we were waiting for @deetergp to approve changes but they were OO for that week (from 17 to 23 jul). While this PR hadn't been merged there were to other PRs changing this component so I've updated the code twice to include changes. Could this issue be eligible for speed bonus taking in account the details above?

**Comment by NicMendonca** [comment] 2023-08-03 21:57
@alexxxwork thanks for following up! We've agreed internally that it's 250$ flat payment for all functional components migration and they are not eligbile for speed bonus.

**Comment by alexxxwork** [comment] 2023-08-04 01:25
@NicMendonca Thanks for clarification!
