### ISSUE TITLE
[HOLD for payment 2024-02-07] [ECARD TRANSACTIONS] We're showing the total amount in the pay button, which includes non-reimbursable expenses, rather than the reimbursable total

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#34618] opened 2024-01-16 22:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue reported by:** @kevinksullivan 
**Slack conversation:** https://expensify.slack.com/archives/C05DWUDHVK7/p1705442308576449

## Action Performed:
1. Create a free workspace and set it as your default
2. Incur a charge on an Expensify Card
3. Add a manual request
4. Tap into the report containing both expenses

## Expected Result:
The pay button should only include the reimbursable total

## Actual Result:
The pay button includes both the reimbursable and non-reimbursable total

![image](https://github.com/Expensify/App/assets/22508290/69e7d608-f937-40c4-a5be-d62b9fb73207)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010be8d278766b8dcd</li>
        <li>Upwork Job ID: 1748128883556716544</li>
        <li>Last Price Increase: 2024-01-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by grgia** [comment] 2024-01-19 00:11
# Notes for internal employee

For some context see [this PR ](https://github.com/Expensify/App/pull/30820) where I discussed how report.total does include the non-reimbursable amount.

Therefore, I think we can fix this by doing the equivalent of this:


```
diff --git a/src/libs/ReportUtils.ts b/src/libs/ReportUtils.ts
index e653d79a74..b310fe79a3 100644
--- a/src/libs/ReportUtils.ts
+++ b/src/libs/ReportUtils.ts
@@ -1705,28 +1705,6 @@ function hasNonReimbursableTransactions(iouReportID: string | undefined): boolea
diff --git a/src/libs/ReportUtils.ts b/src/libs/ReportUtils.ts
index e653d79a74..b310fe79a3 100644
--- a/src/libs/ReportUtils.ts
+++ b/src/libs/ReportUtils.ts
@@ -1705,28 +1705,6 @@ function hasNonReimbursableTransactions(iouReportID: string | undefined): boolea
     return transactions.filter((transaction) => transaction.reimbursable === false).length > 0;
 }

-function getMoneyRequestReimbursableTotal(report: OnyxEntry<Report>, allReportsDict: OnyxCollection<Report> = null): number {
-    const allAvailableReports = allReportsDict ?? allReports;
-    let moneyRequestReport: OnyxEntry<Report> | undefined;
-    if (isMoneyRequestReport(report)) {
-        moneyRequestReport = report;
-    }
-    if (allAvailableReports && report?.iouReportID) {
-        moneyRequestReport = allAvailableReports[`${ONYXKEYS.COLLECTION.REPORT}${report.iouReportID}`];
-    }
-    if (moneyRequestReport) {
-        const total = moneyRequestReport?.total ?? 0;
-
-        if (total !== 0) {
-            // There is a possibility that if the Expense report has a negative total.
-            // This is because there are instances where you can get a credit back on your card,
-            // or you enter a negative expense to “offset” future expenses
-            return isExpenseReport(moneyRequestReport) ? total * -1 : Math.abs(total);
-        }
-    }
-    return 0;
-}
-
 function getMoneyRequestSpendBreakdown(report: OnyxEntry<Report>, allReportsDict: OnyxCollection<Report> = null): SpendBreakdown {
     const allAvailableReports = allReportsDict ?? allReports;
     let moneyRequestReport;
@@ -1764,6 +1742,11 @@ function getMoneyRequestSpendBreakdown(report: OnyxEntry<Report>, allReportsDict
     };
 }

+function getMoneyRequestReimbursableTotal(report: OnyxEntry<Report>, allReportsDict: OnyxCollection<Report> = null): number {
+    return getMoneyRequestSpendBreakdown(report, allReportsDict).reimbursableSpend;
+}
+
+
 /**
  * Get the title for a policy expense chat which depends on the role of the policy member seeing this report
  */
(END)
```

but I am labelling as internal as I want to be sure that the amount that the user is charged is correct as well

**Comment by grgia** [comment] 2024-01-19 00:31
May have the same root cause as https://github.com/Expensify/App/issues/34626

**Comment by luacmartins** [comment] 2024-01-19 00:33
I can work on this one if it's available

**Comment by luacmartins** [comment] 2024-01-19 00:34
Talked to @grgia and I'll take this one!

**Comment by CortneyOfstad** [comment] 2024-01-22 15:46
Thanks @luacmartins!

**Comment by luacmartins** [comment] 2024-01-22 18:53
Looking into this now

**Comment by luacmartins** [comment] 2024-01-22 19:15
PR [here](https://github.com/Expensify/App/pull/34909/files)

**Comment by CortneyOfstad** [comment] 2024-02-07 16:37
@luacmartins is a regression test needed for this? Thanks!

**Comment by luacmartins** [comment] 2024-02-07 16:55
I think we're ok without it. It's already covered in the regression tests will add as part of this project.

**Comment by luacmartins** [comment] 2024-02-07 16:55
Have we paid @rushatgabhane for their PR review? If so, we're good to close.

**Comment by CortneyOfstad** [comment] 2024-02-07 17:00
@luacmartins — I don't see @rushatgabhane assigned here. Is there a link to the PR somewhere?

**Comment by luacmartins** [comment] 2024-02-07 17:42
Yes, this was the PR - https://github.com/Expensify/App/pull/34909

**Comment by CortneyOfstad** [comment] 2024-02-07 18:12
Perfect and for the payment — $500 correct @luacmartins? I'm thinking so, but just wanted a gut check. Thanks!

**Comment by luacmartins** [comment] 2024-02-07 18:49
Yes!

**Comment by CortneyOfstad** [comment] 2024-02-07 18:50
Perfect! @rushatgabhane below is the payment summary request for you!

## Payment Summary

@rushatgabhane (reviewer) — to be paid $500 via NewDot

**Comment by CortneyOfstad** [comment] 2024-02-07 19:19
(not going to close this until the payment is accepted in NewDot 👍 )

**Comment by CortneyOfstad** [comment] 2024-02-09 14:52
@rushatgabhane have you requested payment in NewDot?

**Comment by CortneyOfstad** [comment] 2024-02-12 14:04
Bump @rushatgabhane ^^^ thanks!

**Comment by rushatgabhane** [comment] 2024-02-12 14:54
@CortneyOfstad thanks so much! Requested here - https://staging.new.expensify.com/w/9132779747441AFB/r/2019214606958814

**Closed** 2024-02-14 14:54 UTC
Labels: Daily, Internal, Awaiting Payment, Bug
