### ISSUE TITLE
 Header is missing in nee chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22482] opened 2023-07-08 16:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on “+” icon
2. Enter random email and start chat
## Expected Result: 
Header should be available
## Actual Result: 
Header is missing on new chat
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** need reproduction
**Reproducible in production?:** need reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/33fafa6f-e9e1-45b1-80c1-51305c8b25aa

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688743536423849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-07-10 20:39
I'm also not able to reproduce - closing this one

**Closed by adelekennedy** 2023-07-10 20:39 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug

**Comment by niravkakadiya25** [comment] 2023-07-11 03:35
@adelekennedy i think this is only for fresh user

I am still able to reproduce it

**Comment by niravkakadiya25** [comment] 2023-07-11 03:35
https://github.com/Expensify/App/assets/100456857/f3ef5b1b-76de-4881-b9b6-cda3cc433780

**Comment by niravkakadiya25** [comment] 2023-07-11 03:37
One more expensify user have same issue and reported in slack as well @adelekennedy @kavimuru 

https://expensify.slack.com/archives/C049HHMV9SM/p1688936177762519
