### ISSUE TITLE
[HOLD for payment 2023-07-26] [$1000] Attachments not shown for sender, stuck at 'Uploading attachment...'

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#22750] opened 2023-07-12 14:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Open any chat (group or 1:1)
- Add an image attachment
- `Uploading attachment...` should show temporarily

## Expected Result:
- After upload, other users should see the attachment 
- After upload, the uploader should  image attachment should show 

## Actual Result:
- After upload, other users can see the attachment ✅ 
- After upload, the uploader cannot see the image attachment ('Uploading attachment...' is still shown) ❌ 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [?] iOS / native
- [?] iOS / Safari
- [?] MacOS / Chrome / Safari
- [?] MacOS / Desktop

**Version Number:** `1.3.39-5` and `1.3.38-7`
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**Issue reported by:** Me
**Slack conversation:** N/A

**Uploader (jules) sees:**
<img width="1083" alt="Screenshot 2023-07-12 at 14 51 29" src="https://github.com/Expensify/App/assets/10736861/b82b1e8b-cfa4-4cf5-b202-28712561529d">

**Other user sees:**
<img width="814" alt="image (5)" src="https://github.com/Expensify/App/assets/10736861/2b0fbc2d-dcc2-4970-919f-efdeb8cd648d">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019a63d2e48d9abd42</li>
        <li>Upwork Job ID: 1679142267668922368</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by Julesssss** [comment] 2023-07-12 14:55
FFS. Not again. Going back to Conor as he was the original assignee

**Comment by roryabraham** [comment] 2023-07-13 18:38
My mistake, good find @Pujan92

**Comment by Pujan92** [comment] 2023-07-13 19:18
@rushatgabhane [PR](https://github.com/Expensify/App/pull/22836) is ready for review!

**Comment by sakluger** [comment] 2023-07-21 02:14
Hey @conorpendergrast - @gadhiyamanan reported a similar issue (https://github.com/Expensify/App/issues/22762) 6-7 hours before this GH issue was created, and the PR here ended up fixing the issue he reported. I think that we should pay @gadhiyamanan the reporting bonus since he reportedthe issue first. Could you please send him an offer on this job for $250?

**Comment by conorpendergrast** [comment] 2023-07-21 12:38
Sent! I'll pat that alongside everything else in this issue

**Comment by conorpendergrast** [comment] 2023-07-28 10:34
Ok, it's two days past payday, sorry! Here's what I'm going to do: 

- [ ] External issue reporter - @gadhiyamanan: $250
- [ ] Contributor that fixed the issue: @Pujan92: $1000 + 50% urgency bonus
- [ ] Contributor+ that helped on the issue and/or PR : @rushatgabhane: $1000 + 50% urgency bonus (via NewDot)
- [ ] Bonus appies? YES, adding 50% for the C and C+
[Upwork job is here](https://www.upwork.com/jobs/~019a63d2e48d9abd42)

**Comment by conorpendergrast** [comment] 2023-07-28 10:38
@rushatgabhane Final step is [the checklist](https://github.com/Expensify/App/issues/22750#issuecomment-1642501621), please! Then I'll do a regression test (if necessary) and I'll close this out

**Comment by conorpendergrast** [comment] 2023-07-31 14:34
@rushatgabhane Bump on [the checklist please](https://github.com/Expensify/App/issues/22750#issuecomment-1642501621). I'll be able to close this out after that!

**Comment by rushatgabhane** [comment] 2023-08-02 16:32
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by conorpendergrast** [comment] 2023-08-02 18:56
Woo, thanks!

**Closed by conorpendergrast** 2023-08-02 18:56 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-04 04:17
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.
