### ISSUE TITLE
Round off issue for currency like ALL, AFN when requesting or sending money with 0.5 decimal

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14845] opened 2023-02-06 01:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any report
3. Request money/send money in the chat with 0.5 decimal eg. 100.5, 210.5
4. Observe the amount after clicking next
5. Observe the amount in message generated by the request

## Expected Result:
Both the amount should be equal i.e. round off amount after first step in request/send money and round off amount in message generated after the request should be equal

## Actual Result:
Round off amount after first step displays the amount as rounded up and round off amount in message displays the amount as rounded down eg. if requested 100.5, it will display 101 in next step and 100 in message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.2.65-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/216864479-b5c6a58d-fd8f-4158-b9cb-5055b088278b.mp4

https://user-images.githubusercontent.com/43996225/216864496-9eb28f82-3eda-414c-96d3-e6c7fba5f651.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1675436047423269

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by laurenreidexpensify** [comment] 2023-02-06 13:02
I think this might be by design cos the currencies in question very seldom use the .5 decimal cos they are hyperinflated. 

Gonna check in #expensif-bugs

**Comment by laurenreidexpensify** [comment] 2023-02-06 13:11
Commented with some notes on original thread, I don't think this is a bug.

**Comment by laurenreidexpensify** [comment] 2023-02-06 14:04
I am going to close this one, as it's an edge case and seldom encountered.

**Closed by laurenreidexpensify** 2023-02-06 14:04 UTC
Labels: Daily, Bug
