### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] Web - Reply counter disappears after clicking on the check box on the task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26389] opened 2023-08-31 12:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. plus sign>Assign Task
2. Add Title, Assignee and share somewhere, and confirm Tasks
4. Go to the parent thread
5. Click on the check box

## Expected Result:
The reply counter should not disappear

## Actual Result:
The reply counter disappears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.60.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[screen-capture - 2023-08-24T123320.039.webm](https://github.com/Expensify/App/assets/93399543/f2012815-d2bd-4976-bef3-94ed333148c8)

https://github.com/Expensify/App/assets/93399543/89bf45cf-815f-4867-a6b2-a78674173009

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosGirmaA
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692904283106239

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016418eafb045c8586</li>
        <li>Upwork Job ID: 1697597155228475392</li>
        <li>Last Price Increase: 2023-09-01</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26548264</li>
<li>dukenv0307 | Contributor | 26548265</li>
<li>tewodrosGirmaA | Reporter | 26548266</li>
</ul></li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-08-31 19:41
###  Seems to be a back end issue as the reply count works in `Workspace Chat` but not in `#admin`.

<img width="1440" alt="Screenshot 2023-09-01 at 1 07 35 AM" src="https://github.com/Expensify/App/assets/78416198/0266b4bc-0cb4-4b07-ab39-519e98cfadb6">
<img width="1440" alt="Screenshot 2023-09-01 at 1 07 42 AM" src="https://github.com/Expensify/App/assets/78416198/67d4862b-ad9f-46ae-946c-f0954794a46d">

### Another thing whenever completing a task from `#admin` room the response return's this:
 
<img width="937" alt="Screenshot 2023-09-01 at 1 08 50 AM" src="https://github.com/Expensify/App/assets/78416198/659495a3-3457-4112-b992-40eac9da550d">

**Comment by conorpendergrast** [comment] 2023-09-01 13:09
Seems like a back-end based on the comments so far. Curious for @jjcoffee's take, and if you agree I'll set this as internal!

**Comment by conorpendergrast** [comment] 2023-09-04 16:30
Setting this as internal because this appears to be a backend issue. Correct me if I'm wrong, please!

**Comment by jjcoffee** [comment] 2023-09-04 16:57
Yup definitely seems BE! If you try and repeat the steps whilst offline, the count is correct until you come back online and `OpenReport` completes.

**Comment by jeet-dhandha** [comment] 2023-09-04 20:21
Is there a compensation for finding the root cause ? 🤔

**Comment by arosiclair** [comment] 2023-09-05 19:31
@dukenv0307 is correct we're only counting `ADDCOMMENT` report actions. It was changed in [this Auth PR](https://github.com/Expensify/Auth/pull/8528) two weeks ago. So we need to update the optimistic data to match.

@jjcoffee can you re-review his proposal?

**Comment by jjcoffee** [comment] 2023-09-06 16:09
Sorry higher priority reviews got in the way today, will re(review) tomorrow!

**Comment by jjcoffee** [comment] 2023-09-07 11:34
Happy to go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/26389#issuecomment-1701484427). Their RCA is correct (apologies for misunderstanding on the initial pass!) and the solution is valid as there's no longer any need to increase the thread count (which is all `ReportUtils.getOptimisticDataForParentReportAction` does).

:ribbon::eyes::ribbon: C+ reviewed

**Comment by conorpendergrast** [comment] 2023-09-11 11:53
@lschurr I'm on parental leave; re-assigning! This has been triaged and the PR looks like it's ready to be merged now that the freeze 🧊 is over

**Comment by lschurr** [comment] 2023-09-18 02:37
@jjcoffee could you review [the checklist](https://github.com/Expensify/App/issues/26389#issuecomment-1717185357) for this one?

**Comment by jjcoffee** [comment] 2023-09-18 11:51
- [x] The PR that introduced the bug has been identified. Link to the PR: **N/A - BE change**
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- [x] Determine if we should create a regression test for this bug. **No entirely due to BE change**
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by lschurr** [comment] 2023-09-20 02:13
Payment summary:

Bug reporter: @tewodrosGirmaA $50
Contributor: @dukenv0307 $750
Contributor+: @tewodrosGirmaA $750

All paid in Upwork

**Comment by lschurr** [comment] 2023-09-20 02:13
This is complete.

**Closed by lschurr** 2023-09-20 02:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
