### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] mentioning a user from a different domain with same "front part" of the email address as logged in account causes the mention render as you

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#38074] opened 2024-03-11 18:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.50-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1710094172947319

## Action Performed:
1. Have same front part of the email address in 2 different domain (applausetester+mn1003@applause.expensifail.com and applausetester+mn1003@applause2fa.expensifail.com)
2. Sign in as applausetester+mn1003@applause.expensifail.com
3. Go to any chat and mention applausetester+mn1003@applause2fa.expensifail.com

## Expected Result:
mentioned user shouldn't be highlighted in green

## Actual Result:
mentioned user  highlighted in green to incorrectly render as the logged in account

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Screen Shot 2024-03-11 at 2 20 43 PM](https://github.com/Expensify/App/assets/38435837/55c6caef-29fb-411a-85d4-8e59b28cfbbe)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c23b4f231f3691d1</li>
        <li>Upwork Job ID: 1767259879670747136</li>
        <li>Last Price Increase: 2024-03-11</li>
    </ul>
</details>

**Comment by garatkarr** [comment] 2024-03-11 19:34
Could not reproduce this using two emails with the same "front part" of the email. My email addresses did not have a sub-domain name like the report does and I have no way to create an email with a sub-domain.

**Comment by jeremy-croff** [comment] 2024-03-12 00:08
I am able to reproduce with creating an account in old expensify since it doesn't require email verification.
I created jeremycroff@sub1.gmail.com
Anytime I tag @jeremycroff@anything.com it shows the shortened part followed by the remainder.

This is how we are saving it:
![Screenshot 2024-03-11 at 6 2
![Screenshot 2024-03-11 at 6 55 29 PM](https://github.com/Expensify/App/assets/157416545/d6cb32d7-9e46-4901-9bdf-de10cafa9c7e)
4 36 PM](https://github.com/Expensify/App/assets/157416545/2913319e-013b-480e-86bd-4abd252d6ed9)

However it's a regression from: https://github.com/Expensify/App/pull/36697 which was deployed to prod 5 days ago. Should we still propose @situchan? 

The code is naively saying if the first part + current user email exists in contact list then it's a short text we need to expand.
But we should also compare if the second part the users' email does not equal the last part.

**Comment by jeremy-croff** [comment] 2024-03-12 00:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
We show a different user as being us when the last part of the domain is similar 

### What is the root cause of that problem?
We do not consider if the email domain is different when expanding the short-mentions from here: https://github.com/Expensify/App/pull/36697/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR2669 and will expand it, before considering the last part of the email that could be different.

### What changes do you think we should make in order to solve the problem?
We can extract any email from the text with existing methods
`const emailDomain = Str.extractEmailDomain(text ?? '');`

We can include this to check if we should "expand" the short-mention:
in https://github.com/Expensify/App/pull/36697/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b
9a30d2aecd8811dbR2666 we can return the match early if emailDomain !== currentUserPrivateDomain and not expand it

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2024-03-12 01:17
If it's a regression, it should go to @tienifr and @allroundexperts

**Comment by jliexpensify** [comment] 2024-03-12 01:18
@situchan let me know if @jeremy-croff is correct and I can get this assigned to them

**Comment by hayes102** [comment] 2024-03-12 01:19
is this still open to proposals ? i think its a regression yes and i have a proposal, should i wait?

**Comment by jliexpensify** [comment] 2024-03-19 22:40
I am OOO from the 21st to 31st of March, but I don't think this needs reassigning, as it's a regression and no payment is needed. Please let me know if I am incorrect though!

**Comment by jliexpensify** [comment] 2024-03-31 22:24
As per my comment [here](https://github.com/Expensify/App/issues/38074#issuecomment-2008283766), I don't think payment is needed but lmk if I am wrong!

@allroundexperts any need for a checklist?

**Comment by jliexpensify** [comment] 2024-04-05 09:41
Bump @allroundexperts - any checklist needed here?

**Comment by jliexpensify** [comment] 2024-04-07 22:59
This is a [regression](https://github.com/Expensify/App/issues/38074#issuecomment-2008283766) from [another PR](https://github.com/Expensify/App/issues/38074#issuecomment-1989673092) so no payment needed.

**Closed by jliexpensify** 2024-04-07 22:59 UTC
Labels: External, Weekly, Awaiting Payment, Bug
