### ISSUE TITLE
[Due payment][$250] Netsuite - "Reuse existing connection" is an option when there is no existing workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46680] opened 2024-08-01 17:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.15-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:**  Applause - Internal Team

## Action Performed:
Precondition
An already signed-in account with a workspace connected to NetSuite integration
1. Sign out of the account with the workspace connected to NetSuite integration (Important)
2. Sign in with a new account
3. Navigate to settings > Workspace > Create new Workspace
4. Navigate to more features > Enable accounting
5. Go to Accounting > Connect to NetSuite
6. Upgrade the workspace to Control > Navigate back to Accounting > Click on "Connect" next to NetSuite
7. Here notice that two options appear "Create new connection" and "Reuse existing connection"
8. Click on "Reuse existing connection" > The workspace from the signed-out account appears > Click on the workspace

## Expected Result:
Step 7. There will be no option for "Reuse existing connection" since there is no existing workspace connected to NetSuite in the account

## Actual Result:
Step 7. "Reuse existing connection" is an option even if there is no existing workspace
Step 8. When clicking on the workspace from the signed-out account, Infinite loading is displayed and there is no way to cancel it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/f88e3707-56fa-472a-b316-c2d0c44e9019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b773ba1a34cd80ac</li>
        <li>Upwork Job ID: 1823791114589945944</li>
        <li>Last Price Increase: 2024-08-14</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment] 2024-08-01 17:44
@kadiealexander  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-01 17:45
We think that this bug might be related to #wave-control

**Comment by kadiealexander** [comment] 2024-08-06 06:31
Not overdue, looking for someone internal to pick it up.

**Comment by kadiealexander** [comment] 2024-08-09 03:35
@yuwenmemon @mananjadhav is this on your radar at all?

**Comment by kadiealexander** [comment] 2024-08-14 05:28
@yuwenmemon @mananjadhav bump!

**Comment by mananjadhav** [comment] 2024-08-14 06:02
Sorry I was OOO past few days. I'll take a look at this one.

**Comment by mananjadhav** [comment] 2024-08-16 19:33
Thanks for the proposal @daledah. But I think we clear all the keys on Signout.

I didn't get time to take a look at this. I will check this on the weekend.

**Comment by kadiealexander** [comment] 2024-08-19 08:04
@mananjadhav any updates?

**Comment by mananjadhav** [comment] 2024-08-20 15:01
I tried this and I couldn't reproduce this. 

@daledah I am still not convinced as the policies need be explicitly cleared out on sign out.  This is especially when you see a new workspace option. @lanitochka17 are you getting the same option for Sage Intacct? the code for reuse existing connection is the same.

I still need help with the reproduction here.

**Comment by mananjadhav** [comment] 2024-08-20 18:17
Was just coming back to this. Yeah I think it makes sense to clear `allPolicies`. @yuwenmemon I think @daledah's proposal would work. Can we make this external assign them and I can review?

🎀 👀 🎀

**Comment by mananjadhav** [comment] 2024-09-08 20:47
@yuwenmemon I think this is deployed on production right? I can see the linked deploy checklist is completed.

**Comment by yuwenmemon** [comment] 2024-09-09 17:49
Yep @kadiealexander can we process payment and then close this out?

**Comment by garrettmknight** [comment] 2024-09-11 19:20
$250 approved for @mananjadhav

**Comment by garrettmknight** [comment] 2024-09-11 19:21
@mananjadhav can you complete the checklist when you get a chance?
@kadiealexander please post the payment summary if this is ready to go!

**Comment by kadiealexander** [comment] 2024-09-24 08:24
Payouts due:

- [ ] Contributor: $250 @daledah via Upwork
- [ ] Contributor+: $250 @mananjadhav via Manual Requests

Upwork job is [here](https://www.upwork.com/jobs/~021838494275526358784).

**Comment by garrettmknight** [comment] 2024-09-26 15:35
$250 approved for @mananjadhav

**Comment by kadiealexander** [comment] 2024-10-15 02:18
@daledah I've sent you a contract.

**Closed** 2024-10-15 05:43 UTC
Labels: Reviewing, External, Daily, Bug
