### ISSUE TITLE
Changing the default bank account doesn't work

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40054] opened 2024-04-10 23:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.62-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danieldoglas 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712731362765859

## Action Performed:

1. You need to have 2 bank accounts in the app
2. Go to Settings > Wallet
3. Click on the context menu for the account that is not the default, and click on `Make Default Payment method`

## Expected Result:  
The new account should be the default one

## Actual Result:  
The new account appears to be the default one in the app, but if you look on old dot, the old account is still the default one

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e8808051-3f93-4f8f-9014-6d69a1dd490c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joekaufmanexpensify** [comment] 2024-04-11 14:49
Per [this](https://expensify.slack.com/archives/C03U7DCU4/p1704189082087789), dupe of https://github.com/Expensify/Expensify/issues/299712

**Comment by joekaufmanexpensify** [comment] 2024-04-11 14:49
Closing!

**Closed by joekaufmanexpensify** 2024-04-11 14:49 UTC
Labels: Daily, Bug
