### ISSUE TITLE
Android - The checkmark icon is overlapping with another icon.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20976] opened 2023-06-17 20:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to ND as User A
2. Go to the chat with User B
3. Click on the "+" icon > select "Request Money"
4. Request any amount
5. Login as User B and click on "Pay elsewhere"
6. For User A, the checkmark is overlapping

## Expected Result:
The checkmark is not overlapping with anything

## Actual Result:
It is overlapping with another icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.27.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d82201c1-874e-4b4a-8932-0c63d6b4d4aa

https://github.com/Expensify/App/assets/93399543/2e56b48d-13f5-4222-afed-5b7dd5b12590

**Expensify/Expensify Issue URL:**

**Issue reported by:** @aman-atg

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686418362730859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by eh2077** [comment] 2023-06-18 04:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Does not open site on click of name in URL preview.

### What is the root cause of that problem?

The root cause of this issue is that the title of URL preview is wrapped in `Text`, see

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L113

Which is not link to the url.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can use `TextLink` to wrap the title of link preview by changing 

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L112

to

```react
<TextLink
    fontSize={variables.fontSizeNormal}
    style={styles.pv2}
    color={colors.blueLinkPreview}
    href={url}
>
    {title}
</TextLink>
```

### What alternative solutions did you explore? (Optional)

N/A

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Does not open site on click of name in URL preview.

### What is the root cause of that problem?

The root cause of this issue is that the title of URL preview is wrapped in `Text`, see

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L113

Which is not link to the url.

### What changes do you think we should make in order to solve the problem?

To fix this issue, we can use `TextLink` to wrap the title of link preview by changing 

https://github.com/Expensify/App/blob/b20f917f35ca4a2337a667489d2e3a018ae11909/src/pages/home/report/LinkPreviewer.js#L106-L112

to

```react
<TextLink
    fontSize={variables.fontSizeNormal}
    style={styles.pv2}
    color={colors.blueLinkPreview}
    href={url}
>
    {title}
</TextLink>
```

### What alternative solutions did you explore? (Optional)

N/A

**Comment by eh2077** [comment] 2023-06-18 04:28
This is dupe of 20976

**Comment by JmillsExpensify** [comment] 2023-06-21 04:58
Agreed, we're also refactoring this entire flow so closing for that reason as well.

**Closed by JmillsExpensify** 2023-06-21 04:58 UTC
Labels: Daily, Overdue, Bug
