### ISSUE TITLE
[Hold #44262] [$250] Chat-Quote Markdown without space is applied as a quote in sent chat but not in compose box

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43323] opened 2024-06-07 21:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-14
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to any chat
2. Type >hey (There shouldn't be a space between ">" and "hey")
3. In a second line type > hey (with a space between ">" and "hey")
4. In a third line line type > hey (with two spaces between ">" and "hey")
5. Send the message

## Expected Result:
The first line shouldn't be rendered as a quote markdown. It should be rendered as '>hey'

## Actual Result:
The first line without space is rendered as a quote.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/cdf96210-0c8c-4597-b57e-6eaff629a161

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01352a9a30d580bacb</li>
        <li>Upwork Job ID: 1800195684107077831</li>
        <li>Last Price Increase: 2024-06-17</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by kavimuru** [comment] 2024-06-07 21:54
@trjExpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-06-07 21:54
We think this bug might be related to #vip-vsb

**Comment by trjExpensify** [comment] 2024-06-10 15:57
Can repro, moving `External`.

**Comment by sobitneupane** [comment] 2024-06-12 08:06
@devguest07 Thanks for your proposal.

> We should maintain examples like `> test`, `>>> test`, `> > >test`, etc.
> (!/[a-zA-Z]/.test(charAfterGt)

I understand that we need to consider hierarchal quotes but won't  it causes inconsistency when the character is not an alphabet. For example `>12`, `>>`, `>&` and so on.

**Comment by sobitneupane** [comment] 2024-06-13 06:16
> Sure, I can adjust the charAfterGt in my proposal to fit all those cases.

@devguest07 Can you please update your proposal to reflect the changes required?

**Comment by badeggg** [comment] 2024-06-17 03:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Inconsistency of display for same comment in composer box and chat history. Specifically:
```
>a
> b
> c
```

### What is the root cause of that problem?
Regex [`/^(?:&gt;)+ +(?! )(?![^<]*(?:<\/pre>|<\/code>))([^\v\n\r]+)/gm`](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L262) is causing this condition [`if (match !== null)`](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L967) to true for comment:
```
>a
> b
> c
```
And condition [`Str.startsWith(textSplitted[i], '&gt;')`](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L980) is causing `>a` appended to `textToFormat` for further quote handling.

Which is not identical for same comment text in composer box. In composer box, `>a` is not regarded as quote.

### What changes do you think we should make in order to solve the problem?
We can either let composer box recognize `>a` as quote, or let chat history do not recognize `>a` as quote. Based on [this comment](https://github.com/Expensify/App/issues/42082#issuecomment-2163822468) of @dannymcclain, I think the design team prefer the former one(recognize `>a` as quote).

**To achieve former behavior**, we should change [regex](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L262C21-L262C98) from:
```js
const regex = /^(?:&gt;)+ +(?! )(?![^<]*(?:<\/pre>|<\/code>))([^\v\n\r]+)/gm;
```
to
```js
const regex = /^(?:&gt;)+ *(?! )(?![^<]*(?:<\/pre>|<\/code>))([^\v\n\r]+)/gm;
```
, from matching '1 or more' spaces to matching '0 or more' spaces.

Similar change should be applied to [this regex](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L265) too.

**To achieve later behavior**, we should change [`'&gt;'`](https://github.com/Expensify/expensify-common/blob/c6d1c00652f016532e33ad47c98244538247890b/lib/ExpensiMark.js#L980) to:
```js
'&gt; '
```
, matching one space after `&gt;`

### What alternative solutions did you explore? (Optional)
N/A

**Comment by sobitneupane** [comment] 2024-06-17 08:52
This issue might be in the scope of https://github.com/Expensify/App/issues/42082. Asked [here](https://github.com/Expensify/App/issues/42082#issuecomment-2172722760)

**Comment by sobitneupane** [comment] 2024-06-18 06:46
@trjExpensify Let's hold this issue as it will probably be covered by https://github.com/Expensify/App/issues/42082

**Comment by BrtqKr** [comment] 2024-06-18 10:52
Probably the same as I mentioned [here](https://github.com/Expensify/App/issues/42082#issuecomment-2175797371). I'll let you know if it's not

**Comment by trjExpensify** [comment] 2024-06-18 14:52
Put it on hold!

**Comment by BrtqKr** [comment] 2024-06-18 22:04
Ok, unline the second issue it's unrelated, but it looks like a regex swap, so I can switch it in that PR I've mentioned

**Comment by trjExpensify** [comment] 2024-06-19 12:54
Great! Let's link that PR to this issue as well then. :)

**Comment by trjExpensify** [comment] 2024-06-21 18:20
I think we might be good here?

**Comment by trjExpensify** [comment] 2024-06-24 09:42
@BrtqKr confirming this issue can be closed?

**Comment by BrtqKr** [comment] 2024-06-24 13:38
@trjExpensify it still has to be enabled, but after [this thing ](https://github.com/Expensify/App/pull/44262) yes

**Comment by trjExpensify** [comment] 2024-06-25 15:48
Okay great, I'm going to update the issue number we're held on.

**Comment by trjExpensify** [comment] 2024-07-19 18:44
Deployed to prod three days ago: https://github.com/Expensify/App/pull/44262#issuecomment-2232051831

So we can close this.

**Closed by trjExpensify** 2024-07-19 18:44 UTC
Labels: Reviewing, External, Monthly, Help Wanted, Bug
