### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000]  Unintended Drop to Upload Feature Triggered When Holding Links

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24043] opened 2023-08-02 09:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat.
2. Write a link and hold the link by right-clicking and moving it.
3. Notice that the "Drop to Upload" feature appears.
## Expected Result: 
The "Drop to Upload" feature should not be triggered when holding links.
## Actual Result: 
After writing a link and holding it by right-clicking and moving it, the "Drop to Upload" feature is unexpectedly triggered.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/fab0ce68-007d-43f7-8644-92630a0cf50d

https://github.com/Expensify/App/assets/43996225/ebfa4fe1-cb70-4b87-ab26-748b8f50b397

**Expensify/Expensify Issue URL:**
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690911489720949
https://expensify.slack.com/archives/C049HHMV9SM/p1690887772771919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016dae7b2ac425d362</li>
        <li>Upwork Job ID: 1686831554804891648</li>
        <li>Last Price Increase: 2023-08-02</li>
<li>Automatic offers: </li>
<ul>
<li>samh-nl | Contributor | 25976718</li>
</ul></li>
    </ul>
</details>

**Comment by robertKozik** [comment] 2023-08-05 16:09
Hi! Thank you all for your proposals. As I checked them, it looks like both of them provide the same root cause of the problem and solution for it. Thus, I would opt for selecting the quicker contributor, which would be @samh-nl.

Beforehand, I want to address the proposal editing by @samh-nl. After checking it, I believe the original proposal, which was posted about an hour before the second one, was sufficient to get assigned.

Selected proposal: [Proposal](https://github.com/Expensify/App/issues/24043#issuecomment-1661910070)
author of proposal: @samh-nl 

🎀 👀 🎀 C+ reviewed

**Comment by maddylewis** [comment] 2023-08-06 19:23
### Overview of who is working on this one:
- C+ = @robertKozik 
- Contributor = @samh-nl 
- Reporter = @huzaifa-99 (https://github.com/Expensify/App/issues/24043#issuecomment-1665534540)

**Comment by maddylewis** [comment] 2023-08-06 19:26
hiya @puneetlath - i am OOO until ~Aug 20. 

overview:
- @samh-nl has been hired / they're working on the PR for this fix now
- if the PR is merged before I return, you'll want to issue the corresponding payments

**Comment by robertKozik** [comment] 2023-08-23 12:27
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: **The latest PR changing the "faulty" code was the migration to drag'n'drop hook, but after further investigation I think that It wasn't introduced there, it was rather unconsidered case from back then.**
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **N/A**
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. **I don't think it's needed there, it's purely visual issue**
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **N/A**

**Comment by maddylewis** [comment] 2023-08-29 20:29
okay, i gotcha, so the PR could've potentially been merged on Aug 10 but @mountiny was OOO so it was merged on the 15 - https://github.com/Expensify/App/pull/24211#pullrequestreview-1579101955

sure, i will include the bonus in that case - thanks for letting me know!

**Comment by maddylewis** [comment] 2023-08-29 20:38
@robertKozik - for some reason you weren't hired automatically in Upwork. can you link me to your Upwork profile when you have a sec? thanks!

**Comment by robertKozik** [comment] 2023-08-29 21:34
@maddylewis Actually I'm from the external agency (Software Mansion) so I'm not eligible for payment 😅

**Comment by maddylewis** [comment] 2023-08-30 16:44
@robertKozik -ahhhh thank you. i will one day get everyone straight!

**Closed** 2023-08-30 16:46 UTC
Labels: External, Daily, Awaiting Payment, Bug
