### ISSUE TITLE
Track expense-Deleting track expense displays expensify message for a second & in LHN

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40421] opened 2024-04-18 11:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab-- track expense
3. Enter an amount and tap next
4. Tap track expense
5. Tap on newly created expense
6. Tap on 3dots on top right and delete it

## Expected Result:
While deleting track expense, expensify message must not be shown in Track expense page for a second or in LHN

## Actual Result:
While deleting track expense expensify message is shown for a second and disappears. LHN also shows expensify message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/6efba76e-5c58-42e7-a980-a535d189bc02

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-18 11:05
@stephanieelliott I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-04-18 11:05
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-04-18 11:06
Production 


https://github.com/Expensify/App/assets/115492554/9b3de85e-c02b-4c3f-ab0b-77eb2d32e0d0

**Comment by stephanieelliott** [comment] 2024-04-18 13:08
I don't think this needs to be a deploy blocker since it's just a flicker of a message, everything else functions as intended. Adjusting labels.

**Comment by stephanieelliott** [comment] 2024-04-18 13:11
@izarutskaya looking at the video, I'm not sure where the unintended behavior is (probably bc I am unclear what the `Expensify message` is) -- can you let me know the timestamps in the video where it is occurring?

**Comment by thienlnam** [comment] 2024-04-18 23:48
Ah, I think this is referencing how we see the actionable whisper for a moment before it disappears. The time it shows until it is gone is pretty short so I think we can close this

**Closed** 2024-04-23 03:52 UTC
Labels: Engineering, Daily, Overdue, Bug
