### ISSUE TITLE
[HOLD for payment 2023-11-13] Android - Bank - After opening calendar for incorporation date day that comes before is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30871] opened 2023-11-03 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30845
## Action Performed:
1. Open the app
2. Navigate to any Workspace > Bank Account
3. Complete the bank connection flow until step 2 "Incorporation date"
4. Tap "Incorporation date" and select a date, e.g. 01/01/1980
5. Open the calendar again

## Expected Result:
The previously chosen date "01/01/1980" is still selected

## Actual Result:
The day that comes before is selected (12/31/1979)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e65152bc-d64d-495e-b32b-a2997cda77aa

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tgolen** [comment] 2023-11-03 18:47
@allroundexperts Do you think this has anything to do with some of the changes you've made related to https://github.com/Expensify/App/pull/30845 ?

**Comment by erquhart** [comment] 2023-11-03 19:30
@tgolen @allroundexperts the `new Date()` is still in use as an ISO string parser in a few places, Android DatePicker is one of them: https://github.com/Expensify/App/blob/aa30ef2ea44279637eebb2517b4e08ce88f90e7b/src/components/DatePicker/index.android.js#L64

**Comment by tgolen** [comment] 2023-11-06 16:09
I'm pining @allroundexperts in Slack. If no response, I'll try running `git bisect` to identify the root cause for sure and either fix it or revert it.

**Comment by erquhart** [comment] 2023-11-06 16:26
@tgolen have you looked at #30792? Known active regression, root cause is there.

**Comment by erquhart** [comment] 2023-11-06 16:32
@allroundexperts opened #30845 to fix #30792.

Here he applied the fix I'm talking about, but it still needs to be applied to line 64, per my comment above, to fix this issue: https://github.com/Expensify/App/pull/30845/files#diff-2a19098ae1f788eb0b65b80d103e4a5d53f159bffdfd1bf8d042de5e83f7e7b9R42

**Comment by tgolen** [comment] 2023-11-06 16:35
OK, thanks for spelling that out a little more clearly to me. Ah, and here is @allroundexperts now! Thanks for working on this and I'll assign this issue to @allroundexperts.

**Comment by bfitzexpensify** [comment] 2023-11-13 19:00
I'd like to clarify the relationship between the solution in this issue and the solution for https://github.com/Expensify/App/issues/30792. It sounds like they had the same root cause, but there are separate PRs to fix the two issues. Are they closely enough aligned to consider them as one solution?

**Comment by erquhart** [comment] 2023-11-13 19:03
@bfitzexpensify they are exactly the same issue. `new Date()` was used instead of `parseISO()` in a lot of places. #30792 was fixed by updating a few of those instances, this issue was fixed by updating a few more. There are still others.

**Comment by tgolen** [comment] 2023-11-15 14:39
@bfitzexpensify I think this is ready to be paid out?

**Comment by situchan** [comment] 2023-11-15 14:40
I think I am only the one for payment here. Other contributors' payments are being handled in https://github.com/Expensify/App/issues/30792.

**Comment by bfitzexpensify** [comment] 2023-11-15 14:54
Thanks for confirming @erquhart. And yes, the other payments + BZ checklist will happen in https://github.com/Expensify/App/issues/30792, so the only action here is payment for @situchan — the offer has been sent.

**Comment by bfitzexpensify** [comment] 2023-11-15 17:57
OK, payment complete, closing this one out.

**Closed by bfitzexpensify** 2023-11-15 17:57 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
