### ISSUE TITLE
[$250] Unable to create a chat when offline from search page reported by @Puneet-here 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12378] opened 2022-11-02 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Go offline
2.Click on search icon and search a new user
3.Click on it

## Expected Result: 
New chat should get created

## Actual Result: 
Nothing happens

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.22-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/199559900-daa3cde2-7488-4707-8862-10e4782adab1.mp4

https://user-images.githubusercontent.com/43996225/199559949-253807d7-1c10-4088-8ce6-70df5b8948fd.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Puneet-here 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1667381591063639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alexpensify** [comment] 2022-11-03 23:31
Assigning over to engineering for another set of eyes, I was unable to replicate. 

![image](https://user-images.githubusercontent.com/8107070/199854308-e771528e-909b-428f-989c-2ce0e7c7c75b.png)

![image](https://user-images.githubusercontent.com/8107070/199854325-a95a2a64-e6db-4fd2-8655-6847f8c18918.png)

**Comment by puneetlath** [comment] 2022-11-04 14:30
@alexpensify a couple of things: 

1. As a member of the BugZero team, you'll want to keep any `Bug` labeled issues assigned to you, even if you're assigning someone else to help out with the issue. Bug issues that get assigned to you are your responsibility from open to close. 
2. Were you testing on staging? When I just tried this on staging I was able to replicate the issue.

**Comment by alexpensify** [comment] 2022-11-04 15:21
Noted for the future! 

Regarding if I was on staging for this test, here are my Preferences in New Dot on the mobile application: 

![image](https://user-images.githubusercontent.com/8107070/200011428-f2859e46-78bf-4c5e-8f1c-bcefebf8945d.png)

At this point, do I move to the next step and create a job? It looks like you were able to replicate it.

**Comment by alexpensify** [comment] 2022-11-04 23:06
I've not been able to replicate but have assigned `External` for another round of testing before creating the job. Thanks!

**Comment by dangrous** [comment] 2022-11-07 22:30
I'm also not able to replicate, on prod or staging... Happy to try other steps if @puneetlath you have additional thoughts

**Comment by puneetlath** [comment] 2022-11-08 14:36
Let's close if no one can replicate. @Puneet-here if you're still able to replicate it, feel free to reopen and share how you are replicating. Thanks!

**Closed by puneetlath** 2022-11-08 14:36 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug

**Comment by Puneet-here** [comment] 2022-11-10 20:15
@puneetlath, I am still able to reproduce. This is only reproducible when you search a user by going to the search page using the search icon. If you create a new chat using new chat options it works.

**Comment by puneetlath** [comment] 2022-11-16 18:16
I think you're right. Thanks for finding that. 

And in general, we really appreciate the bug reports @Puneet-here! Keep em coming! 🙏🏾
