### ISSUE TITLE
[HOLD for payment 2024-02-01] [$500] Bug: description instead of merchant being used for expense room titles

### ISSUE THREAD

**Issue by dylanexpensify** [Expensify/App#34029] opened 2024-01-05 15:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.15-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @shawnborton 
**Slack conversation:** https://expensify.slack.com/archives/C03U7DCU4/p1704382128969099

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click on an Expense that has the merchant field populated
3. Add a description to the expense

## Expected Result:
The description is saved and room title doesn't change

## Actual Result:
The expense room title changes to use the description instead of the merchant

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![CleanShot 2024-01-04 at 16 27 50@2x](https://github.com/Expensify/App/assets/60117248/81d9c029-6f84-4878-89c9-05aedf87afa1)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f555a808f6be075d</li>
        <li>Upwork Job ID: 1737996800572018688</li>
        <li>Last Price Increase: 2024-01-05</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 28091153</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-05 15:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?

We are using this function for building the Transaction Report title:

https://github.com/Expensify/App/blob/9b7485161b2964099984794f2e5528a28ec64800/src/libs/ReportUtils.ts#L1987-L2015

### What changes do you think we should make in order to solve the problem?
We should use the merchant if present instead of comment:

```js
    return Localize.translateLocal(ReportActionsUtils.isSentMoneyReportAction(reportAction) ? 'iou.threadSentMoneyReportName' : 'iou.threadRequestReportName', {
        formattedAmount: CurrencyUtils.convertToDisplayString(transactionDetails?.amount ?? 0, transactionDetails?.currency, TransactionUtils.isDistanceRequest(transaction)) ?? '',
        comment: transactionDetails?.merchant ?? transactionDetails?.comment ?? '',
    });
```



### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-05 15:46
## Proposal
Updated proposal https://github.com/Expensify/App/issues/34029#issuecomment-1878849394

**Comment by sobitneupane** [comment] 2024-01-09 10:48
@dylanexpensify @shawnborton Just to clarify, are we aiming to display the merchant if it's available, and if not, show the description?

Pseudocode:
```
If merchant:
  $1.30 request for ${merchant}
else if description:
  $1.30 request for ${description}
else:
  $1.30 request
```

**Comment by shawnborton** [comment] 2024-01-09 10:48
Yup, that's my understanding. 

cc @trjExpensify @JmillsExpensify

**Comment by sobitneupane** [comment] 2024-01-09 10:59
@dukenv0307 

> If we only want this behavior in the room title, we can pass in a flag to getReportName to control it

Where else do we use this pattern except room title? Can you please add more details.

**Comment by sobitneupane** [comment] 2024-01-09 11:04
@paultsimura 

> If we want to prioritize the merchant for every transaction, not just the ones that belong to the Expense report,

What other transaction(other than that of Expense report) are we talking about in the alternative solution? And how will they be affected if we go with alternative solution.

**Comment by paultsimura** [comment] 2024-01-09 11:09
> What other transaction(other than that of Expense report) are we talking about in the alternative solution?

The IOU (1:1 and split) transactions of any type.
The reason why I initially thought we'd like to prioritize merchant only for the Expense transactions (the ones requested from a workspace) is because recently there were a lot of changes to make merchant required only for Expense requests, not IOU ones. Plus, the issue title says "**expense** room titles".

>  How will they be affected if we go with alternative solution

We will show the merchant if it's present. Otherwise – show the description. For any transaction, regardless of its type (1:1, split, expense (workspace)).

**Comment by dylanexpensify** [comment] 2024-01-09 12:12
Nice! @sobitneupane to review!

**Comment by trjExpensify** [comment] 2024-01-09 12:15
>Yup, that's my understanding.
>
>cc @trjExpensify @JmillsExpensify

Yep, agreed. Merchant > Category > Blank!

**Comment by sobitneupane** [comment] 2024-01-09 12:44
Thanks for the proposal @paultsimura and @dukenv0307

Both of the proposals are very similar. Looking at the edit history, both the proposals where incomplete when initially posted. Please try to post a complete proposal.

Approach followed in both proposals is same (from the initial proposal) and implementation is not much different.

I think it's good idea to make use of existing function. Let's go with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/34029#issuecomment-1878848052) (it was initially posted proposal with correct RCA and approach). Let's solve the issue in `isMerchantMissing` if any.

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment] 2024-01-10 20:13
Nice! @sobitneupane let's get it!

**Comment by dylanexpensify** [comment] 2024-01-17 09:34
bump @sobitneupane

**Comment by sobitneupane** [comment] 2024-01-18 11:44
I am reviewing the PR.

**Comment by dylanexpensify** [comment] 2024-01-23 13:21
How's this going @sobitneupane

**Comment by sobitneupane** [comment] 2024-01-24 02:14
PR merged. Waiting for it to display in production.

**Comment by dylanexpensify** [comment] 2024-01-29 11:51
payment coming up!

**Comment by dylanexpensify** [comment] 2024-02-07 10:37
bump @sobitneupane

**Comment by sobitneupane** [comment] 2024-02-07 13:39
@dylanexpensify I am not sure if reviewer checklist is valid here. The code was introduced first by this https://github.com/Expensify/App/pull/34216 PR as per the need back then. I think it is more of a feature request than bug.

**Closed** 2024-02-12 14:20 UTC
Labels: External, Daily, Task, Overdue, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-02-14 22:34
$500 approved for @sobitneupane based on [this summary](https://github.com/Expensify/App/issues/34029#issuecomment-1926955203).
