### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] `OpenPublicProfilePage` API not called as soon as avatar is clicked

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36610] opened 2024-02-15 16:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @puneetlath 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708010767314729
 
## Action Performed:
1. Go to a room chat
2. Click on the user avatar
## Expected Result:
the OpenPublicProfilePage API should get called as soon as you open the profile page.
## Actual Result:
it isn't getting called until you click on the avatar. This means that the profile data isn't getting loaded when you open the profile, even though it should be.
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/893345a8-b620-4be0-8aae-c7227d9e12f2

https://github.com/Expensify/App/assets/38435837/5e7994ba-9229-45eb-8ce0-fd1202f3e107

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eff48078e4b5dadf</li>
        <li>Upwork Job ID: 1758172876106809344</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
</ul></li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-02-15 17:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
OpenPublicProfilePage API not called as soon as avatar is clicked

### What is the root cause of that problem?
The api is called if there is no avatar here
https://github.com/Expensify/App/blob/1c0d126ffb34e1fd103c9f6067b76af688638d47/src/pages/ProfilePage.js#L141-L142
### What changes do you think we should make in order to solve the problem?

Change it to 
```
        if (ValidationUtils.isValidAccountRoute(accountID)) {

```
### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2024-02-15 17:07
As avatar url is already available in personal details list I think it should not make a call to `OpenPublicProfilePage`, similar case I have mentioned [here](https://github.com/Expensify/App/issues/36577#issuecomment-1946544760) (update `??` to `||`)

https://github.com/Expensify/App/blob/2fe384c5a2279d65f083d828f825dc9368a3f2ef/src/pages/settings/Profile/ProfileAvatar.tsx#L31

**Comment by puneetlath** [comment] 2024-02-16 16:20
@codinggeek2023 could you clarify what you mean? 

The bug is that when you open a profile we aren't calling the `OpenPublicProfilePage` API. We're only calling it when you click on the avatar. This is happening whether you are an anon user or you are signed in. And no matter what user's profile you are attempting to view (from my testing).

**Comment by ikevin127** [comment] 2024-02-16 19:22
> As avatar url is already available in personal details list I think it should not make a call to OpenPublicProfilePage, similar case I have mentioned here (update ?? to ||).

Your proposed solution would break the avatar functionality in case the avatar is changed from another device because if we apply the solution that would mean the `OpenPublicProfilePage` won't be called anymore when `avatarURL` changes.

More context / video example here https://github.com/Expensify/App/issues/36577#issuecomment-1948520398.

**Comment by kmbcook** [comment] 2024-02-17 00:31
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
OpenPublicProfilePage API not called as soon as profile page is opened.

### What is the root cause of that problem?
See
- pages/ProfilePage.js
- libs/actions/PersonalDetails.ts

OpenPublicProfilePage api call made in PersonalDetails.openPublicProfilePage.

ProfilePage receives personal details in props, normally. If so, hasMinimumDetails is set to true, which prevents openPublicProfilePage from being called.

### What changes do you think we should make in order to solve the problem?
ProfilePage calls openPublicProfilePage regardless of value of hasMinimumDetails.

**Comment by cubuspl42** [comment] 2024-02-19 09:10
@FitseTLT Could you elaborate on the root cause analysis? Are we discussing a corner case? Is the current (old) `hasMinimumDetails` logic working in any circumstances? You suggest adding two checks in the new proposed condition: `details.avatar` and `details.login`. When is one of these non-empty when the other is empty, and vice versa?

**Comment by kmbcook** [comment] 2024-02-19 15:50
@cubuspl42 the issue itself is about the API call not being made, not about personal details not being current. Is there some reason the issue was written the way it was, some reason why the API call MUST be made when the profile page is opened?

**Comment by puneetlath** [comment] 2024-02-19 17:30
I think we should use `hasMinimumDetails` in order to decide whether to show the blocking view. But no matter what we should call the API when opening the page so that we ensure we get the most up-to-date details.

**Comment by cubuspl42** [comment] 2024-02-21 08:51
In such a case, I believe we should go with @kmbcook

C+ reviewed 🎀 👀 🎀

**Comment by FitseTLT** [comment] 2024-02-21 09:20
@cubuspl42 @puneetlath By the way, calling the api unconditionally was the first version of my proposal and then I realized that the `hasMinimumDetails` condition was there to minimize unnecessary call to the api and I still agree with that. Any changes in personal details data gets pushed automatically (I have checked it)

https://github.com/Expensify/App/assets/38649957/2918255a-134a-46df-abd3-90cc8b0b6e46


 I don't think we should call the api everytime the page is opened. The only problem with the current code is assuming data is ready when the avatar exists so we should ensure other props are available too like `login` (`pronouns` etc). WDYT guys?

**Comment by puneetlath** [comment] 2024-02-21 16:50
There are scenarios where personal details don't get pushed from the back-end (e.g with public room users you don't know). So I think it makes sense to call the API when we open the page, just like we call the OpenReport API every time you open a chat. 

I think hasMinimumDetails is a badly-named variable and was always only meant to determine whether we should show the loading indicator or not. Something like shoudlShowLoadingIndicator makes more sense to me.

**Comment by kmbcook** [comment] 2024-02-22 22:20
I'm planning to have a PR ready tomorrow.

**Comment by kmbcook** [comment] 2024-02-24 05:11
Sorry, I'm going to need another day. The code changes are ready, but this is my first time navigating the reporting and testing requirements and I'm struggling. One of my challenges is to get video which shows that the API call is made on each of the platforms. I've done that for four of the six so far, at least clunky video. I'm yet not sure how I'm going to do it for Mac Desktop.

**Comment by puneetlath** [comment] 2024-02-25 21:38
You can toggle dev tools in the Mac Desktop app. It's in the "view" section of the toolbar.

**Comment by greg-schroeder** [comment] 2024-03-02 00:35
C+ review complete, next up is @stitesExpensify to review

**Comment by stitesExpensify** [comment] 2024-03-04 20:09
merged

**Comment by kmbcook** [comment] 2024-03-08 18:04
> @cubuspl42 the issue itself is about the API call not being made, not about personal details not being current. Is there some reason the issue was written the way it was, some reason why the API call MUST be made when the profile page is opened?

Given that this issue requires the API call to be made, are these two issues mutually exclusive (this one and https://github.com/Expensify/App/issues/37986)?

**Comment by cubuspl42** [comment] 2024-03-11 09:29
@kmbcook Not necessarily... It's a X -> Y -> Z situation. We solved problem X, and the solution uncovered a performance problem Y. Problem Y likely existed before, but it's easier to observe now.

The problem Y is likely solvable. The question is whether we handle it as a separate problem or say that it was our fault that we didn't solve X and Y in one go. 

Of course, I prefer the first interpretation.

**Comment by greg-schroeder** [comment] 2024-03-13 21:02
@stitesExpensify what do you think about the above re: regression?

**Comment by greg-schroeder** [comment] 2024-03-13 23:50
@kmbcook can you please follow the steps [here](https://github.com/Expensify/App/issues/36610#issuecomment-1960017257) so I can pay you?

**Comment by stitesExpensify** [comment] 2024-03-13 23:50
I think we go with "not a regression". While this did technically cause the problem, the actual issue already existed, and we did not ask for the lag to be fixed here on the issue, or during testing on the PR.

**Comment by greg-schroeder** [comment] 2024-03-13 23:54
offer sent to @kmbcook for $500
@cubuspl42 paid $500

next up is @cubuspl42 is [the checklist](https://github.com/Expensify/App/issues/36610#issuecomment-1981864476)!

**Comment by kmbcook** [comment] 2024-03-14 00:52
> @kmbcook can you please accept the offer I sent you so I can pay you? thanks!

Done

**Comment by cubuspl42** [comment] 2024-03-14 08:55
- The PR that introduced the bug has been identified. Link to the PR:
    -  This is a kind of new feature fixing an undesirable behavior in the edge cases
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
    - N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
    - No need for additional discussion
- Determine if we should create a regression test for this bug.
    - Up to the QA team
- If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
    - User A and User B don't have any previous interactions
    - User A enters a public room.
    - User B enters the same public room
    - User B posts a message.
    - User B changes their Display Name.
    - Verify that, from User A's perspective, the Display Name of User B in their message is not updated automatically
      - If it updates on its own, it can mean that  these users have previous interactions
    - User A clicks/taps on the avatar of User B, which leads to their profile
    - Verify that User A's view of the profile page of User B refreshes, presenting the new Display Name

**Comment by anmurali** [comment] 2024-03-18 23:41
Added the regression test. @greg-schroeder - have you paid @kmbcook ? If yes, can you please close this issue? I wasn't sure if that last payment had gone out yet.

**Comment by greg-schroeder** [comment] 2024-03-25 11:25
Yup! All done, closing.

**Closed by greg-schroeder** 2024-03-25 11:25 UTC
Labels: Daily, Internal, Overdue, Awaiting Payment, Bug
