### ISSUE TITLE
[$500] Clicking on room name while loading crashes the app

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36271] opened 2024-02-09 16:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.39-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1707493474003029

## Action Performed:
1.Go offline
2.Open a workspace
3.go to announce room
4.make sure the loading skeleton is shown
5.Press on the room header

## Expected Result:
Opens details page
## Actual Result:
App crashes

## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/e8cc9d0c-d132-4dc0-8e05-17912c2bb810

![Screen Shot 2024-02-09 at 11 23 15 AM](https://github.com/Expensify/App/assets/38435837/b9e38bd7-cbb6-4e2f-b7cd-3cf80d150d30)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cd42193c8752a37e</li>
        <li>Upwork Job ID: 1755996151032115200</li>
        <li>Last Price Increase: 2024-02-09</li>
    </ul>
</details>

**Comment by Natan-Asrat** [comment] 2024-02-09 17:01
i have solved this problem countless times in my own android app so i know the solution

**Comment by Natan-Asrat** [comment] 2024-02-09 17:16
Contributor details 
Your Expensify account email: natsceo@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014ae4361b802854c6

**Comment by Pujan92** [comment] 2024-02-09 17:25
I think it is fixed [here](https://github.com/Expensify/App/pull/35153/files#diff-409b0e2fb439856e9897b808014031ce244a427d116ed30f37a2e0117599adc4R245)

**Comment by ikevin127** [comment] 2024-02-09 17:30
Regression from issue https://github.com/Expensify/App/issues/25195 , PR https://github.com/Expensify/App/pull/35153 (merged 2h ago).

**Comment by situchan** [comment] 2024-02-09 17:34
> Regression from issue #25195 , PR #35153 (merged 2h ago).

@ikevin127 you mean fixed by #25195?
Seems like that PR fixed crash, not caused crash

**Comment by situchan** [comment] 2024-02-09 17:34
@ZhenjaHorbach if you find the case of report being undefined or null, we can continue this issue.
Otherwise can be closed.

**Comment by Pujan92** [comment] 2024-02-09 17:34
Regression seems to be from https://github.com/Expensify/App/pull/34150 and https://github.com/Expensify/App/issues/25195 fixed the crash.

**Comment by situchan** [comment] 2024-02-09 17:48
yes, Onyx values are optional and agree that we should use optional chaining everywhere.

**Comment by situchan** [comment] 2024-02-12 14:54
https://github.com/Expensify/App/pull/35153 hit staging.
Now crash doesn't happen on staging.

**Comment by situchan** [comment] 2024-02-12 14:55
@ZhenjaHorbach thoughts on https://github.com/Expensify/App/issues/36271#issuecomment-1936320722?

**Comment by situchan** [comment] 2024-02-12 15:05
ok @dylanexpensify let's close as fixed

**Closed** 2024-02-13 20:09 UTC
Labels: External, Daily, Help Wanted, Bug
