### ISSUE TITLE
[$1000] Web - Click on backdrop when selecting a country does not close RHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23852] opened 2023-07-29 11:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to Settings -> Profile -> Personal details -> Home address -> Country
2. Click on backdrop

## Expected Result:
App should close RHN

## Actual Result:
App navigates back to Address page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c78fe676-cab5-47ed-ab21-75b9b340b8fb

https://github.com/Expensify/App/assets/93399543/75df2989-027a-499e-8d3f-c1eb28808790

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690556741155419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0180aa2c16d38d50fd</li>
        <li>Upwork Job ID: 1693666992465907712</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-07-29 12:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue is that when a user opens the country picker from Settings -> Profile -> Personal details -> Home address -> Country and then clicks on the backdrop, the app doesn't close the Right Hand Navigation (RHN) as expected. Instead, it navigates back to the Address page.

### What is the root cause of that problem?
The root cause of the issue is how the country picker modal is designed. It is unique in that, unlike other stack pages, it is not a standalone page and opens a new modal on top of the current page. Therefore, when the backdrop is clicked, it dismisses the country picker but doesn't close the RHN.

### What changes do you think we should make in order to solve the problem?
One solution could be to adjust the behavior of the hidePickerModal function to also dismiss the modal upon closing the country picker. This could be done by adding Navigation.dismissModal() to the hidePickerModal function.

Alternatively, we could refactor the country picker to be a standalone page, which would make the behavior consistent with other pages in the app.

A third approach could be to use a different component altogether for the CountryPage that handles closing the RHN when the backdrop is clicked.

**Comment by puneetlath** [comment] 2023-07-31 19:20
@WoLewicki do you agree it's the same root cause as https://github.com/Expensify/App/issues/23725 and if so, will it be handled by your PR there?

**Comment by skydragon1115** [comment] 2023-07-31 23:52
@WoLewicki I found the reason. This is the same root cause as #23725.

**Comment by puneetlath** [comment] 2023-08-08 20:47
Hmm, yes I see what you mean @WoLewicki. However, I don't think this is the desired behavior. Everything in the right-hand-pane should feel like it's happening in the same modal, so I think clicking out of it should always close the entire modal.

**Comment by puneetlath** [comment] 2023-08-15 22:38
So @WoLewicki where does that leave us. Should we open this up for proposals or is this something that's actively being worked on elsewhere?

**Comment by puneetlath** [comment] 2023-08-21 16:50
Going to go ahead and open it up for proposals.

**Comment by lewis-n** [comment] 2023-08-23 10:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When navigating to Settings -> Profile -> Personal Details -> Home Address -> Country and clicking the backdrop, the navigation pane does not close. Instead, it returns to the "Home Address" section.

### What is the root cause of that problem?
Clicking the "Country" menu item triggers a country selector modal, this opens atop the existing navigation pane. Clicking the backdrop closes only the modal, leaving the navigation pane open.

### What changes do you think we should make in order to solve the problem?
I propose replacing the country selector modal component with a dedicated page, 'CountrySelectPage.js'. This method has already been implemented, for example, in timezone selection. The 'TimezoneSelectPage.js' is used to display the selector (Settings -> Profile -> Timezone -> select).

The component can be refactored to its own page, and the route can be added to the stack navigator to allow navigation to the page.

### What alternative solutions did you explore? (Optional)
#### 1. Using React-Navigator with the Existing Component
Adding a link to the CountrySelector component (with the `<Modal>` wrapper removed) to the stack navigator and navigating to it upon selecting the country selector menu item. This approach still causes a a change of URL due to the use of react-navigator, and so moving the selector to its own page would likely be a more consistent solution.

#### 2. Redesigning the Country Selection Component
An entire redesign of the country selection component would eliminate the need for a modal or new page. However, this would not be consistent with the way in which selection is handled elsewhere.

**Comment by lewis-n** [comment] 2023-08-23 11:08
Contributor details
Your Expensify account email: halfway.last.0j@icloud.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0143a14b076508275d

**Comment by burczu** [comment] 2023-08-24 10:01
I think we should proceed with [the proposal](https://github.com/Expensify/App/issues/23852#issuecomment-1656723924) from @ygshbht - although it does not fix the root cause it fixes this particular issue (the root cause will be addressed in https://github.com/Expensify/App/issues/23725 I guess)

[The proposal](https://github.com/Expensify/App/issues/23852#issuecomment-1689738305) from @lewis-n is not entirely bad but, as I understand, we already had these modals implemented as separate pages and we gave up on this idea - [comment](https://github.com/Expensify/App/issues/23725#issuecomment-1680922513))

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-08-24 10:08
Not overdue

**Comment by WoLewicki** [comment] 2023-08-31 12:17
Sorry for the late response, I agree with @burczu 🚀

**Comment by puneetlath** [comment] 2023-08-31 19:52
Just realized Andrew is OOO. Going ahead and assigning @ygshbht. Let's do it 💪🏾

**Comment by ygshbht** [comment] 2023-08-31 22:38
@burczu The [PR](https://github.com/Expensify/App/pull/26443) is ready for review!

**Comment by puneetlath** [comment] 2023-09-01 18:34
We decided to go the page route, which is being handled in [this issue](https://github.com/Expensify/App/issues/23725#issuecomment-1702949910). But we need to make payments for the work here. @ygshbht @hoangzinh can you please apply to the Upwork job? It looks like it didn't auto-hire you.

**Comment by ygshbht** [comment] 2023-09-01 18:43
@puneetlath Applied!

**Comment by puneetlath** [comment] 2023-09-05 20:31
All paid. Thanks y'all.

**Closed by puneetlath** 2023-09-05 20:31 UTC
Labels: Reviewing, Weekly, Internal, Bug
