### ISSUE TITLE
[$500] Request money - Parent / child category is case sensitive

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32125] opened 2023-11-28 14:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition : Admin invited a member to the control or collect policy
1. Create a parent category as "test" or "TEST"
2. Create sub categories as "Test:Test1" and "Test:Test2"
3. Go to member account and go to workspace chat created in precondition
4. Request money and go to category field
5. Scroll down to the parent child category lists

## Expected Result:
"Test" parent category should be selectable irrespective of case

## Actual Result:
Not selectable it is disabled

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/19e9df67-3a38-4ee5-ab92-cb292bd11829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d446f2173534e11</li>
        <li>Upwork Job ID: 1729505682370691072</li>
        <li>Last Price Increase: 2023-11-28</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-11-29 01:27
Interesting, I think this is how it works on OldDot today: 

<img width="533" alt="image" src="https://github.com/Expensify/App/assets/16232057/bd43e042-4106-4c6b-9b53-2f6faa88d25b">
<img width="1018" alt="image" src="https://github.com/Expensify/App/assets/16232057/fcda733b-4102-4010-a23e-a6ba7206f8b0">

I think this might be intentional, unless it's a bug in both places, but @joekaufmanexpensify & @puneetlath can chime in having worked on this. 

- If you don't want the "parent" category to be selectable in the category list, then you don't enter the standalone value in the category editor. 
- If you enter the parent category as a standalone value in the category editor, it'll be selectable in the category list.

Are those accurate statements?

**Comment by joekaufmanexpensify** [comment] 2023-11-29 18:32
Yep to both statements. This is intentional and not a bug. This gives more customization options to companies, as some may want the parent to be selectable, and some not. 

If case sensitivity was impacting the ability to select a category that would not seem expected to me. But based on my read here, it seems like the report is actually just related to the parent being selectable based on whether it's enabled as a standalone category, rather than anything case sensitivity-related. If that's the case, we can close!

**Comment by trjExpensify** [comment] 2023-11-30 18:12
Oh yeah, kinda' interesting that having `TEST` as a category you then have the `Test` label above the nested values as shown [here](https://github.com/Expensify/App/issues/32125#issuecomment-1831046585).

.. but if you have `Test` as a category then you don't have the little label: 

<img width="512" alt="image" src="https://github.com/Expensify/App/assets/16232057/4bbc4daa-4e8f-4f42-81ce-25664bf73d17">
<img width="1008" alt="image" src="https://github.com/Expensify/App/assets/16232057/bd504c14-812f-4177-a213-1177c46af413">

**Comment by joekaufmanexpensify** [comment] 2023-12-01 16:41
Ah, yeah. That is interesting. We could change that, but I am not convinced that is really a bug. If someone is using caps in one place, in all likelihood they are going to use caps in all, and vice versa. 

I'm thinking the logic has probably worked this way on OldDot since the beginning of time, and if it hasn't come up, feels fine to me to leave as is.

**Comment by trjExpensify** [comment] 2023-12-04 11:41
Cool, sounds good to me. Closing this out then! :)

**Closed by trjExpensify** 2023-12-04 11:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
