### ISSUE TITLE
QBO - Changing to other option does not save for the first time

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49372] opened 2024-09-18 09:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.37-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validation PR:** https://github.com/Expensify/App/pull/48277
**Email or phone of affected tester (no customers):** dave0123seife@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Prerequisite: Your workspace needs to connect with QBO.

1. Go to Workspace -> Accounting
2. Go to Export -> Export invoice to
3. Choose another account

## Expected Result:
Chosen option saves

## Actual Result:
When changing option for the first time Chosen option returns back to the initial option.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/e1e4a21c-cba3-47ac-841b-2c83e7495d4f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @aldo-expensify</details>

**Comment by izarutskaya** [comment] 2024-09-18 09:30
I added 2 labels because I am not sure what I need to use. The behavior with `Use Staging Server` disabled is different when running in production and staging with `Use Staging Server` enabled. Check my video please

https://github.com/user-attachments/assets/de976eb3-e323-4eb3-b80e-3045c3dbc866

**Comment by grgia** [comment] 2024-09-18 09:59
Potentially related to https://github.com/Expensify/App/pull/48277

**Comment by dangrous** [comment] 2024-09-18 14:05
Hm yeah it's on prod... And I just double checked the new code from your PR, it's effectively no different from the old code. @aldo-expensify do you think this might be the sync issue we're dealing with separately? Like the initial sync hasn't yet completed?

**Comment by dangrous** [comment] 2024-09-18 14:17
yeah i think this is the sync issue - I just tried on my own staging account, the first time i switched the setting (right after connecting) it switched back, but then i just tried it again after waiting a few seconds, and it worked.

@izarutskaya can you confirm if changing the setting - after waiting at least 10 seconds or so after connecting QBO - does work as intended? If so, I think we can close this and handle the syncing separately.

**Comment by zfurtak** [comment] 2024-09-18 15:04
@dangrous if you need any frontend work for it, I can help 😊

**Comment by grgia** [comment] 2024-09-18 15:44
@dangrous the bug is specific to the first time

**Comment by grgia** [comment] 2024-09-18 15:55
testing again now

**Comment by grgia** [comment] 2024-09-18 15:59
<img width="515" alt="image" src="https://github.com/user-attachments/assets/b60b1260-f811-4959-9ad6-74e5b167d390">
I made a new workspace and waited 10 min but no avail the 1st time
Seems the  funky update is coming from this `getMissingONYXUpdates` call @dangrous

**Comment by grgia** [comment] 2024-09-18 16:01
Right after I call 

`UpdateQuickbooksOnlineReceivableAccount`

```
{
    "jsonCode": 200,
    "requestID": "8c528932cdf5bd9d-LHR",
    "onyxData": [
        {
            "key": "policy_96C3808269C266A8",
            "onyxMethod": "merge",
            "value": {
                "connections": {
                    "quickbooksOnline": {
                        "config": {
                            "receivableAccount": {
                                "currency": "USD",
                                "glCode": "",
                                "id": "1150040001",
                                "name": "Testing New Dot"
                            }
                        }
                    }
                }
            }
        }
    ],
    "previousUpdateID": 1920887604,
    "lastUpdateID": 1920893835
}
```

I see a call to `GetMissingOnyxMessages`

```
        {
            "key": "policy_96C3808269C266A8",
            "onyxMethod": "merge",
            "value": {
                "connections": {
                    "quickbooksOnline": {
                        "config": {
                            "receivableAccount": {
                                "currency": "USD",
                                "glCode": "",
                                "id": "53",
                                "name": "Accounts Receivable"
                            }
                        }
                    }
                }
            }
        },

```

**Comment by grgia** [comment] 2024-09-18 16:07
Demoting as an app blocker since it's an erroneous onyx update

**Comment by grgia** [comment] 2024-09-18 16:57
Triaged but I'm already working on a wave-collect issue, unassigning

**Comment by aldo-expensify** [comment] 2024-09-18 19:46
I'll try to fix this

**Comment by trjExpensify** [comment] 2024-09-25 11:35
Why did Melv put this to `Monthly`? Changing it back.

**Comment by aldo-expensify** [comment] 2024-09-28 00:46
I'm having problems reproducing this in either dev or staging:


https://github.com/user-attachments/assets/7eabf7a6-170c-40dc-9dec-9012c19c90ab

From reading the thread above, it sounds like there may be some race condition where not all the updates containing the initial connection have arrived and we change the setting. This results in an old onyx update changing the setting back. Would be nice to be able to reproduce this more consistently.

I have problems with the pusher updates in dev, they are very flakey or they simply don't arrive at all.. which is making it though for me to debug/reproduce.

**Comment by aldo-expensify** [comment] 2024-09-28 00:49
As @grgia mentioned, there is a call to `GetMissingOnyxMessages` (two really in my case) that happen after the connection is stablished without me taking any extra action:

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/c6d25983-f812-4691-8963-b302d754a61e">


Maybe I can investigate what is triggering these `GetMissingOnyxMessages` requests and try to prevent that.

**Comment by aldo-expensify** [comment] 2024-10-02 01:18
Was OOO yesterday, I'll try to get back to this on Wednesday or Thursday

**Comment by aldo-expensify** [comment] 2024-10-05 01:09
haven't have time yet 😬 , I'll try again next week.

**Comment by aldo-expensify** [comment] 2024-10-08 02:20
Didn't have time today.

**Comment by aldo-expensify** [comment] 2024-10-11 20:16
I'm getting back to this after lunch

**Comment by aldo-expensify** [comment] 2024-10-12 00:16
So.. when I was preparing to work on this, I destroyed my VM by mistake and now I have been struggling with certificates for hours and I still can't get past it. I'll continue on this on Tuesday.

**Comment by mananjadhav** [comment] 2024-10-15 17:13
Does this need help?

**Comment by aldo-expensify** [comment] 2024-10-15 18:16
> Does this need help?

Not for now, I plan to get back to this today

**Comment by mananjadhav** [comment] 2024-10-15 19:04
I haven't checked it yet. I can try to take a look from FE side.

**Comment by aldo-expensify** [comment] 2024-10-16 01:53
Now I have my dev env fully working again. From testing I can see that the IS code call several times `SavePolicy` during import and during sync. Each call to `SavePolicy` will save some onyx updates to the database that are later processed by the job `www-prod/SendFetchableOnyxUpdates` that pushes them to the clients.

Considering this, I guess it is expected that the onyx updates will arrived in any order since:
- The jobs `www-prod/SendFetchableOnyxUpdates` are not executed in order, and
- The pushed events not necessarily arrive in order because of the network (specially if they come from different jobs).

This makes it very likely that some calls to `GetMissingOnyxUpdates` will happen because of the bad order.

**Comment by aldo-expensify** [comment] 2024-10-19 01:24
No updates, I've been focusing on this other QBO quality issue: https://github.com/Expensify/App/issues/49371 which has a more clear solution.

**Comment by aldo-expensify** [comment] 2024-10-21 19:24
Holding on https://github.com/Expensify/App/issues/49371 before continuing in case the fix there helps with this too.

**Comment by aldo-expensify** [comment] 2024-10-25 01:00
Still waiting for the [PR](https://github.com/Expensify/App/pull/51110) to be reviewed...

**Comment by aldo-expensify** [comment] 2024-10-29 01:38
https://github.com/Expensify/App/pull/51110 was merged, I'll get back on testing this asap

**Comment by muttmuure** [comment] 2024-10-29 16:10
Great!

**Comment by aldo-expensify** [comment] 2024-11-02 00:48
So I have been working today on this, and I have manage to reproduce it a few times, but is hard... most of the time you don't  have enough time to go to the setting and change it. I have tried with slow connections and it doesn't make it easier.

I'll be also OOO next week, so considering that and the above, I'll lower the priority to `Weekly` because I don't think this can happen easily for a real user.

Having said that, I think I have an idea of how to fix this in the Integration-Server. The current behaviour is:

1. We import the data from QBO
2. Call the command `Policy_Connection_Set` to store it
3. Pick default configs using the data read in step 1
4. Call the command `Policy_Connection_Set` to store the default configs

I think I can change this to:

1. We import the data from QBO
2. Pick default configs using the data read in step 1
3. Call the command `Policy_Connection_Set` to store the imported data and the default configs

If we do a single `Policy_Connection_Set` call, it won't be possible that the frontend receives the imported data in a separate update from the one containing the default configs.

**Comment by aldo-expensify** [comment] 2024-11-02 01:04
PR up: https://github.com/Expensify/Integration-Server/pull/8184

**Comment by aldo-expensify** [comment] 2024-11-13 03:02
Closing this, the backend PR was deployed last week: https://github.com/Expensify/Integration-Server/pull/8184

**Closed by aldo-expensify** 2024-11-13 03:02 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug

**Comment by trjExpensify** [comment] 2024-11-14 02:25
Thanks for sticking with this one, Aldo.
