### ISSUE TITLE
[$500] Web - Request Money - An error message is displayed in an incorrect position compared to other sections of the application.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27151] opened 2023-09-11 13:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click FAB (Plus sign).
2. Select the "Request Money" option from the menu.
3. Select the "Scan" option.
4. Click the “Choose File” button.
5. Select any file.
6. Select any User
7. Click the "Save" button.
8. In a chat thread, click "Reply in Thread."
9. Modify the date to any other value, and observe that the error message appears before the arrow next to "Amount" and "Merchant."

## Expected Result:
In whole app, error is displayed below the respective input fields, with the indicator dot consistently positioned to the left of the error message.

## Actual Result:
Currently, the error message appears before the arrow and the indicator dot is positioned to the right of the error message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.67.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d7954238-f663-4c75-8b60-b86d6866adea

https://github.com/Expensify/App/assets/93399543/d43f65da-d005-4650-b6b9-fb488f1b1456

**Expensify/Expensify Issue URL:**
**Issue reported by:** @usmantariq96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694063310377739

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9c5a54742be6544</li>
        <li>Upwork Job ID: 1701230833602445312</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-09-11 14:14
I don't think this is a bug, maybe expected behaviour.

**Comment by AmjedNazzal** [comment] 2023-09-11 17:48
"In whole app, error is displayed below the respective input fields, with the indicator dot consistently positioned to the left of the error message." these are not input fields though, they are pressable components that open the stack navigator so I don't understand the issue here.

**Comment by s77rt** [comment] 2023-09-11 18:45
@shawnborton Do you think this is a bug or intended? The red dot is at the right and the error is before it, should it be that way or the other way around? (check the last seconds of the second video)

**Comment by sahilbhosale63** [comment] 2023-09-12 16:47
Yesterday, I saw this issue in Upwork job posting. I downloaded the source and ran the web app but I'm facing the `You appear to be offline` issue frequently while I am using the app. Due this I'm not able to debug the issue correctly. Can any one please guide me here?

**Comment by shawnborton** [comment] 2023-09-12 19:42
Oh yeah this does seem odd, @JmillsExpensify @trjExpensify why wouldn't we be showing the error message directly under the push row label here?

**Comment by shawnborton** [comment] 2023-09-12 19:43
This is the offending screenshot: 
<img width="485" alt="image" src="https://github.com/Expensify/App/assets/2319350/ec588c15-86b2-4d44-8d8a-713c29d27378">

**Comment by shawnborton** [comment] 2023-09-12 19:44
Also, is this a bug or is this a regression from somewhere? It feels like a regression to me, and we should have the original PR author fix this.

**Comment by trjExpensify** [comment] 2023-09-12 20:31
Yeah, I already reported this to @Gonals who's in the process of fixing it via [this issue](https://github.com/Expensify/App/issues/26832). This can be closed, @zanyrenney!

**Comment by s77rt** [comment] 2023-09-14 20:51
Not overdue. Looks like this will be handled in https://github.com/Expensify/App/issues/26832.

**Comment by zanyrenney** [comment] 2023-09-18 09:00
As this is handled via https://github.com/Expensify/App/issues/26832 I am closing!

**Closed by zanyrenney** 2023-09-18 09:00 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
