### ISSUE TITLE
[$500] iOS - Login - Paste menu does not point to the correct field on magic code page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32241] opened 2023-11-30 00:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.7
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Enter any email to try to log in
3. Copy the magic code
3. Try to paste the magic code on any field that is not the first one

## Expected Result:
The paste menu should point to the field the user is trying to paste the code

## Actual Result:
The paste menu does not point to the correct field, is always pointing to the first field of the magic code

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/ea400a7c-dc68-4447-9814-ad271c63686b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-11-30 06:55
This looks like a regression of the PR https://github.com/Expensify/App/issues/32241

**Comment by s-alves10** [comment] 2023-11-30 06:57
Oh, yes. Sorry. https://github.com/Expensify/App/pull/28711

**Comment by kosmydel** [comment] 2023-11-30 08:17
Hey, I'm from SWM and I'm currently responsible for this issue. 

It looks like it was a conscious decision to leave it like this. It was [discussed](https://github.com/Expensify/App/issues/18244#issuecomment-1648118198) and approved [here](https://github.com/Expensify/App/issues/18244#issuecomment-1652327533).

**Comment by mountiny** [comment] 2023-11-30 11:59
Yeah I dont think this is a blocker, tested this and you can just fine paste it in if you focus on the first number

Assigning Santosh and Kuba in the meantime if we decide this needs to be fixed or not

**Comment by dangrous** [comment] 2023-11-30 14:11
Yeah I think we're okay with this. If we CAN find a solution that would be neat, but I think it's not a bug, just a shift from before.

**Comment by NikkiWines** [comment] 2023-12-04 23:52
Unassigning @kosmydel since we determined this wasn't a regression from the previously mentioned PR and we're opening up this issue for proposals

**Comment by joekaufmanexpensify** [comment] 2023-12-05 15:52
I kinda think we should do nothing about this and close the issue. We auto-focus to the first field of the magic code after the user submits their email and moves to the magic code page. 

I don't think it will be common for someone to actively then choose to click on a different one of the 6 fields and try to paste the code there. If they do, pasting the code beginning with where they focused doesn't seem wrong to me. 

In an ideal world, it'd be cool if pasting the code to any one of the 6 fields auto adjusts the code into the correct place. But that doesn't seem like a bug fix IMO, it seems like a new feature. And not one that really feels like a priority. Personally, I think it makes sense to leave as is, and reevaluate if any actual customers run into an issue with this.

**Comment by joekaufmanexpensify** [comment] 2023-12-05 20:14
Closing. LMK if anyone disagrees!

**Closed by joekaufmanexpensify** 2023-12-05 20:14 UTC
Labels: Engineering, Daily, Help Wanted, Bug
