### ISSUE TITLE
[$500] Room - Unable to scroll up to the top in public room as anonymous user

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#34980] opened 2024-01-23 17:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4228454
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal team
**Slack conversation:**

## Action Performed:
Precondition: user created a public room and added multiple messages
1. Navigate to the public room via a link, e.g. https://staging.new.expensify.com/r/5408450846930023
2. Scroll up to the very beginning

## Expected Result:
User can scroll to the beginning of the chat history

## Actual Result:
Flickering loading animation displayed, anonymous user is unable to scroll up to the beginning

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ed1d3d0a-94b0-4bde-8aa3-ec9e72bd930b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015a97f638ac603602</li>
        <li>Upwork Job ID: 1749853750439735296</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-23 17:58
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by joekaufmanexpensify** [comment] 2024-01-23 23:16
I can't reproduce this on web. Going to try on mobile

**Comment by joekaufmanexpensify** [comment] 2024-01-23 23:19
Okay, I can reproduce on mobile web: 

https://github.com/Expensify/App/assets/54866469/e9025df8-e5d9-4290-ac2b-e3d98eac8866

**Comment by joekaufmanexpensify** [comment] 2024-01-23 23:19
Agreed this feels like a #vip-vsb issue.

**Comment by s-alves10** [comment] 2024-01-24 07:45
This issue looks like a backend issue. `GetOlderActions` API returns the following error
![image](https://github.com/Expensify/App/assets/126839717/f94bd92f-4311-4c6c-b572-dcddde609977)

**Comment by joekaufmanexpensify** [comment] 2024-01-25 16:03
Got it. @mananjadhav ,do you agree?

**Comment by mananjadhav** [comment] 2024-01-29 00:45
Yeah looks like @s-alves10 is correct.

**Comment by joekaufmanexpensify** [comment] 2024-02-02 16:42
Same

**Comment by joekaufmanexpensify** [comment] 2024-02-05 14:33
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-02-06 14:41
Same

**Comment by joekaufmanexpensify** [comment] 2024-02-07 14:11
Going to look for some more volunteers internally

**Comment by joekaufmanexpensify** [comment] 2024-02-09 20:05
Interesting. It does seem similar. I am not able to reproduce in #social though. I just tried.

**Comment by joekaufmanexpensify** [comment] 2024-02-19 14:59
Pending prioritization in the project

**Comment by isagoico** [comment] 2024-02-19 19:35
We were able to reproduce this issue during testing for this request - https://expensify.slack.com/archives/C9YU7BX5M/p1708359665549809

https://github.com/Expensify/App/assets/44479856/eb0eb87e-8e90-4525-a4e9-29e6861ce202

https://github.com/Expensify/App/assets/44479856/a75aa6e1-e536-44dd-9976-ac8f2c264eca

**Comment by mallenexpensify** [comment] 2024-02-19 20:05
@joekaufmanexpensify @mananjadhav can you also try to reproduce in https://new.expensify.com/r/6776919265133947 
If you're able to reproduce, please post here. @joekaufmanexpensify , if you're able to , please share in #vip-vsb to see if the `Low` prioritization is still accurate.

**Comment by mallenexpensify** [comment] 2024-02-21 01:32
Posted in #vip-vsb cuz it's likely a priority with #exfy-roadmap
https://expensify.slack.com/archives/C066HJM2CAZ/p1708478107200569
also posted in #engineering 

Bumped to `Daily` and added `Hot Pick`

**Comment by joekaufmanexpensify** [comment] 2024-02-21 15:22
Sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-02-23 16:18
Still looking for internal volunteer

**Comment by joekaufmanexpensify** [comment] 2024-02-26 15:29
Not overdue

**Comment by joekaufmanexpensify** [comment] 2024-02-27 14:39
Waiting for engineer to grab

**Comment by mvtglobally** [comment] 2024-02-27 15:49
Issue not reproducible during KI retests. (First week)

**Comment by joekaufmanexpensify** [comment] 2024-02-28 15:52
Got it. I will retest!

**Comment by joekaufmanexpensify** [comment] 2024-03-01 17:10
Will retest this afternoon

**Comment by kbecciv** [comment] 2024-03-05 16:47
QA team is able to reproduce the issue in build 1.4.47.0, OP is updated with reproduction steps.

https://github.com/Expensify/App/assets/93399543/55f76ec9-9025-4df0-940f-6c46899a65cb

**Comment by joekaufmanexpensify** [comment] 2024-03-06 16:08
Got it. I will try and reproduce!

**Comment by joekaufmanexpensify** [comment] 2024-03-06 22:04
I think this new report is a bit different than the original one. The original report here didn't really involve the skeleton UI. he new report seems like a dupe of https://github.com/Expensify/App/issues/37661 . Closing as we're working on fixing the loading/scrolling of public rooms without showing the skeleton UI there!

**Closed by joekaufmanexpensify** 2024-03-06 22:04 UTC
Labels: Engineering, Daily, Internal, Bug, Hot Pick
