### ISSUE TITLE
[Hold for payment 11-01-24] [$500] Mobile keyboard displays on Choose SSO  or MagicCode page

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32715] opened 2023-12-08 13:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.10-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @NikkiWines 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701992002045759

## Action Performed:
1. Navigate to the Sign In page
2. Enter the email of an account with SAML enabled but not required
3. Confirm you're navigated to a view that gives you the option to sign in with SSO or with a magic code

## Expected Result: 
The view is displayed without the mobile keyboard

## Actual Result: 
The view is displayed with the mobile keyboard covering half of the page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/167b3e9b-586a-4f6f-be67-cc2873f5f830

https://github.com/Expensify/App/assets/38435837/9d5fca66-168c-4caf-81ba-366a44bf9437

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017b7b2c3804491f9a</li>
        <li>Upwork Job ID: 1734632332835643392</li>
        <li>Last Price Increase: 2023-12-12</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 28064572</li>
<li>mkhutornyi | Contributor | 28064573</li>
</ul></li>
    </ul>
</details>

**Comment by miljakljajic** [comment] 2023-12-12 13:48
Bumped the thread to see if we could apply the external label

**Comment by yh-0218** [comment] 2023-12-12 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Keyboard doesn't dismiss on Choose SSO or MagicCode page after login with email
### What is the root cause of that problem?
We don't have any function to hide keyboard on `SignInPageInner`
### What changes do you think we should make in order to solve the problem?
We can add this to `SignInPageInner`
```
   const {isKeyboardShown} = useKeyboardState();
   // This view doesn't have a field for user input, so dismiss the device keyboard if shown
   useEffect(() => {
        if (!isKeyboardShown) {
            return;
        }
        Keyboard.dismiss();
    }, [isKeyboardShown]);
```
### What alternative solutions did you explore? (Optional)

**Comment by ebcabaybay** [comment] 2023-12-13 10:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Choose SSO or MagicCode page, keyboard is not dismissed and occupies most of the screen

### What is the root cause of that problem?
Keyboard is shown on LoginForm and continues to be visible when Choose SSO or MagicCode page is already showing

### What changes do you think we should make in order to solve the problem?
Dismiss the keyboard when ChooseSSOOrMagicCode is shown. This can be done in with Keyboard.dismiss() inside a useEffect in ChooseSSOOrMagicCode.js

**Comment by ebcabaybay** [comment] 2023-12-13 10:43
Contributor details
Your Expensify account email: ebcayabyab01@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01b5609f8c899e9d6d

**Comment by aldo-expensify** [comment] 2023-12-18 15:03
> ChooseSSOORMagicCode component mount
Same!

**Comment by aldo-expensify** [comment] 2023-12-21 15:02
@mkhutornyi when can we expected a PR?

**Comment by miljakljajic** [comment] 2024-01-08 14:20
Deployed to staging 4 days ago - I'll update the issue title, seems like something is wrong with the automation

**Comment by miljakljajic** [comment] 2024-01-22 12:03
@Ollyws the upwork offer expired without being accepted. Please accept the new offer so we can get you paid

**Comment by miljakljajic** [comment] 2024-01-24 15:04
paid, closing

**Closed by miljakljajic** 2024-01-24 15:04 UTC
Labels: Reviewing, External, Weekly, Bug
