### ISSUE TITLE
[HOLD for payment 2023-11-02] [$500] LHN - Changed date appears for second in LHN

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29198] opened 2023-10-10 14:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696920625003389

## Action Performed:
1. Go to chat with userB
2. Click on + icon and request money
3. Go to transaction thread
4. Change the date
5. Verify the useB's LHN

## Expected Result:
It should not show changed date message in LHN

## Actual Result:
Changed date appears for second in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/6105f983-4396-4db0-a6d9-bf76fe365579

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/ef7a14fe-6231-4843-9187-964c8f71adc8

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/fd7933f4-f876-4465-9143-bfd799293535

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/c6701638-7047-490e-8ba3-1d570afd4998

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/92cc8ffb-659e-4137-ab59-523d6866716e

https://github.com/Expensify/App/assets/93399543/915e725f-f050-40ab-bda1-6d9d838949c7

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/af81c819-2ce4-43d4-99d5-9f4df37b73f1

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b78bee9a21a448bf</li>
        <li>Upwork Job ID: 1711752378465558528</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27184925</li>
<li>gadhiyamanan | Reporter | 27184926</li>
<li>tsa321 | Contributor | 27299831</li>
</ul></li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-10-11 00:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After user A modifies date of the money request, user B sees "modified date" message in LHN for a moment.

### What is the root cause of that problem?
Pusher sends partial data of the transaction thread to the User B, so as a result, the LHN Data optionItem is build with incomplete data about the report (it has no `notificationPreference`, which is used for hiding the transaction threads from LHN unless they are opened at the moment)


### What changes do you think we should make in order to solve the problem?

We are already early returning in case the `optionItem` is falsy. Since `optionItem.type` is set as `report.type`, it will always be defined when `report` data is present:

https://github.com/Expensify/App/blob/e21370b9d018e5a5a552233c155bfc8e79de364d/src/libs/SidebarUtils.js#L409

We should also check if `optionItem` doesn't have broken Report data. And if the data is broken, early return `null` here:

https://github.com/Expensify/App/blob/1998fa35e7bcc217ca29757efb7a9fd364346988/src/components/LHNOptionsList/OptionRowLHN.js#L87-L89

```diff
-   if (!optionItem) {
+   if (!optionItem || !optionItem.type) {
        return null;
    }
```

Or using lodash:
```js
if (!lodashGet(optionItem, 'type')) {
    return null;
}
```

### What alternative solutions did you explore? (Optional)

**Comment by ashuvssut** [comment] 2023-10-11 00:15
Hi @paultsimura 

How did you add this nice code block?
![image](https://github.com/Expensify/App/assets/60546840/2f6e1c64-6709-497e-aa46-3c50e7b2a176)

What is the markdown syntax?

**Comment by redpanda-bit** [comment] 2023-10-11 02:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Change of date is displayed briefly and then goes away.

### What is the root cause of that problem?
Same root cause analysis as the other proposals. – report with partial data is received from backend (missing `notificationPreference: 'hidden'`) .

<img width="468" alt="Screen Shot 2023-10-10 at 10 08 31 PM" src="https://github.com/Expensify/App/assets/25206487/a81b7013-1894-47e1-8b6a-395d34ced786">

– adding the picture so it shows I also did the analysis, just took too long.

### What changes do you think we should make in order to solve the problem?

This should be fixed in the backend in order to address the root cause. There should be a single source of truth to show/hide the list item which `notificationPreference` appears to be:

https://github.com/Expensify/App/blob/ff2dca93a11fe6b0b1a1dacda23139db68979af6/src/components/LHNOptionsList/OptionRowLHN.js#L91

I think it should remain that way. And if the backend does not have access to the notificationPreference right away, it should send `notificationPreference: 'hidden'` which is better than missing the attribute.

**Comment by abekkala** [comment] 2023-10-11 18:40
@sobitneupane looks like we already received a few proposals to review! 🎉

**Comment by sobitneupane** [comment] 2023-10-12 08:50
I kind of agree with @redpanda-bit. We expect the report to have `notificationPreference`. But @redpanda-bit the message appears in LHN only for short time. What's the reason for that? Do we get the updated data later on? Which function is responsible for that? `isHidden` is not the only way to determine weather a report should be in the optionlist or not. We have other checks as well which shows that we do expect partial data.

**Comment by redpanda-bit** [comment] 2023-10-12 19:58
What @tsa321 said ^. From my point of view the pusher event should send `notificationPreference` or maybe something like `isHidden`. This would avoid having to check for another attribute in the frontend – unless the role of that other attribute (e.g., report.reportName, report.type, etc...) in fully understood.

**Comment by sobitneupane** [comment] 2023-10-13 18:00
@abekkala I will be unavailable next week. Therefore, I am unassigning myself from the issue. Please feel free to assign it to another C+.

**Comment by situchan** [comment] 2023-10-13 18:19
I am interested in reviewing this

**Comment by abekkala** [comment] 2023-10-13 18:28
@situchan can you review the proposals?

**Comment by situchan** [comment] 2023-10-13 19:02
@paultsimura thanks for the proposal. The root cause is correct. Can you also elaborate the reason why disappears from LHN after a second?

**Comment by paultsimura** [comment] 2023-10-13 22:23
Thanks @situchan, this broken option disappears quickly because right after we receive the partial data from Pusher, we handle it with the `Report.handleReportChanged` Onyx collection callback:

https://github.com/Expensify/App/blob/12010774a74ed73e6f85a8c4329c723e2ec0ce8a/src/libs/actions/Report.js#L1009-L1012

Since this report is partial and contains no `reportName`, we execute this line of code:

https://github.com/Expensify/App/blob/12010774a74ed73e6f85a8c4329c723e2ec0ce8a/src/libs/actions/Report.js#L1002-L1006

On the `ReconnectToReport` API call, we receive the full Report data, which now contains the desired `"notificationPreference": "hidden"`, and this leads to hiding this faulty option:

```json
{
            "onyxMethod": "merge",
            "key": "report_8493073986538438",
            "value": {
                "reportID": "8493073986538438",
                "reportName": "Chat Report",
                "type": "chat",
                "chatType": "",
                "ownerEmail": "__fake__",
                "ownerAccountID": 0,
                "managerEmail": "__fake__",
                "managerID": 0,
                "policyID": "56CF23241EA3DE0C",
                "participantAccountIDs": [
                    15881060,
                    15877835
                ],
                "isPinned": false,
                "lastReadTime": null,
                "lastMentionedTime": null,
                "lastReadSequenceNumber": 0,
                "lastVisibleActionCreated": "2023-10-13 22:13:43.367",
                "lastVisibleActionLastModified": "2023-10-13 22:13:43.367",
                "lastMessageText": "paultsimura+ws8@gmail.com",
                "lastActorAccountID": 15877835,
                "notificationPreference": "hidden",
                "welcomeMessage": "",
                "stateNum": 0,
                "statusNum": 0,
                "oldPolicyName": "",
                "visibility": null,
                "isOwnPolicyExpenseChat": false,
                "lastMessageHtml": "paultsimura+ws8@gmail.com",
                "iouReportID": null,
                "hasOutstandingIOU": false,
                "policyName": null,
                "hasParentAccess": true,
                "parentReportID": "601258001830251",
                "parentReportActionID": "1343420941804528390",
                "writeCapability": "all",
                "description": null,
                "isDeletedParentAction": null,
                "total": 0,
                "currency": "USD",
                "submitterPayPalMeAddress": "",
                "chatReportID": "601258001830251",
                "isWaitingOnBankAccount": false
            }
        }
```

**Comment by abekkala** [comment] 2023-10-16 18:01
@situchan can you address your response from @paultsimura

**Comment by situchan** [comment] 2023-10-16 18:20
@paultsimura there's already `shouldReportBeInOptionList` check whether to show/hide report in LHN.

**Comment by paultsimura** [comment] 2023-10-16 18:47
@situchan you're right. Moved my suggested check inside this function.

**Comment by abekkala** [comment] 2023-10-19 14:51
@situchan can you review please?

**Comment by amyevans** [comment] 2023-10-23 15:40
Not overdue, @tsa321 will be submitting a PR

**Comment by abekkala** [comment] 2023-10-30 17:31
PAYMENTS ON NOV 02

@gadhiyamanan requires payment [offer](https://www.upwork.com/nx/wm/offer/27184926) (Reporter)
@tsa321 requires payment [offer](https://www.upwork.com/nx/wm/offer/27299831) (Contributor)

**Comment by abekkala** [comment] 2023-10-30 17:33
PAYMENTS ON NOV 02

- @gadhiyamanan [$50] [offer](https://www.upwork.com/nx/wm/offer/27184926) (Reporter)
- @tsa321 [$500 + $250 Bonus] [offer](https://www.upwork.com/nx/wm/offer/27299831) (Contributor)
- @situchan requires payment [$500 + $250 Bonus]  [offer](https://www.upwork.com/nx/wm/offer/27184925) (Contributor)

@situchan can you complete the checklist above?

**Comment by abekkala** [comment] 2023-11-02 17:12
@gadhiyamanan [$50] payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-11-02 17:13
@tsa321 [$500 + $250 Bonus] payment sent and contract ended - thank you! 🎉

**Comment by abekkala** [comment] 2023-11-02 17:14
@situchan can you complete the checklist above before I process payment?

**Comment by situchan** [comment] 2023-11-02 18:10
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/11226
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/11226/files#r1380599365
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug. We have automated test cases whether to show report in options list. I think that's enough for regression test
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by abekkala** [comment] 2023-11-03 17:32
@situchan [$500 + $250 Bonus] payment sent and contract ended - thank you! 🎉

**Closed by abekkala** 2023-11-03 17:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
