### ISSUE TITLE
[HOLD] [$1000] Dev: Android - Console error on select "Here" in concierge message

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23116] opened 2023-07-18 18:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click "+" button
2. Create public room
3. Send any message
4. Wait for concierge message
5. Click on "here" (text with blu color and underline)

## Expected Result:
here should not be have any console error

## Actual Result:
There is console error on click of "here" in concierge message.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev: 1.3.42-7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/27115d44-53d1-42bc-acd8-760411e5edd0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689671219791719

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f6a18c8162ea9d4b</li>
        <li>Upwork Job ID: 1685971113153757184</li>
        <li>Last Price Increase: 2023-07-31</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-18 22:18
Reproducible:

https://github.com/Expensify/App/assets/78416198/bf8c79d6-6e29-4982-ad7d-5831c338b828

**Comment by jeet-dhandha** [comment] 2023-07-18 22:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Problem is that we are getting a Promise error when we press on `here` in the conierge message, which basically redirects to Display Name page.

### What is the root cause of that problem?
- The root cause of the problem is that we are getting `/settings/profile/display-name` url in `AnchorForCommentsOnly/index.native.js` file.
- So when opening the url using `Linking.openURL(props.href)`. It throws error as there's no domain attached.

### What changes do you think we should make in order to solve the problem?
- What we can do is that we can add change the onPress function such that it calls Navigation.navigate() function with the url as a parameter.
- This will redirect to the Display Name page.
<details>
<summary>Code Changes</summary>

- Previously
```js
const onPress = () => (_.isFunction(props.onPress) ? props.onPress() : Linking.openURL(props.href));
```

- Updated 
```js
const onPress = () => {
    if (_.isFunction(props.onPress)) {
        return props.onPress();
    } else if (props.href && props.href.startsWith('/')) {
        return Navigation.navigate(props.href);
    }
    Linking.openURL(props.href);
};
```
</details>

- We might need to handle back navigation as well from display name page as currently it will take us to Profile > then settings > then the chat report screen.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by zanyrenney** [comment] 2023-07-19 16:16
asked in slack as this is one for the dev environment https://expensify.slack.com/archives/C049HHMV9SM/p1689783369475699?thread_ts=1689671822.535099&cid=C049HHMV9SM

**Comment by zanyrenney** [comment] 2023-07-24 16:08
assigning eng as I can't reproduce on Dev.

**Comment by zanyrenney** [comment] 2023-07-24 16:09
Ugh! i did not mean to add the overdue label, so removing that!

**Comment by zanyrenney** [comment] 2023-07-24 16:10
@johnmlee101 please could you help with reproducing this on dev - we said [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1689959460610739?thread_ts=1689959411.301019&cid=C01SKUP7QR0) to ask engineers with these kind of bugs. thank you!

**Comment by zanyrenney** [comment] 2023-07-27 11:25
bump @johnmlee101 please could you get to this one when you have a moment?

**Comment by jeet-dhandha** [comment] 2023-07-27 11:33
Reproduce steps for Android:
1. login into any new account.
2. Remove the display name - first name and last name from profile.
3. Now create a public room without any members and send any message.
4. You should get a `here` message, press on it and verify that you get an error and nothing happens. 

Expected:
1. User should have been navigated to Profile name page.

**Comment by johnmlee101** [comment] 2023-07-27 16:29
Yep reproduced 
<img width="436" alt="image" src="https://github.com/Expensify/App/assets/5258036/6ff4aff8-c141-4aa5-aca9-a38ada03a652">

**Comment by zanyrenney** [comment] 2023-07-31 11:10
Thanks @johnmlee101 - assigning external.

**Comment by s77rt** [comment] 2023-08-01 07:14
@zanyrenney  I think we can hold this on https://github.com/Expensify/App/issues/21207. The link sent by Concierge should be fixed to be an absolute url.

cc @youssef-lr

**Comment by zanyrenney** [comment] 2023-08-01 17:11
Thanks!

**Comment by zanyrenney** [comment] 2023-08-01 17:12
@youssef-lr i'm going OOO, seeing as this is on hold, i won't assign a bug buddy, if this needs movement whilst I am away though, please feel free to reapply label. Thanks!

**Comment by johnmlee101** [comment] 2023-08-04 21:37
Still on hold, I believe

**Comment by zanyrenney** [comment] 2023-08-07 16:34
Still on hold for https://github.com/Expensify/App/issues/21207

**Comment by s77rt** [comment] 2023-08-09 21:54
Still on hold

**Comment by s77rt** [comment] 2023-08-13 01:50
Same ^

**Comment by zanyrenney** [comment] 2023-08-21 11:02
Still on hold!

**Comment by zanyrenney** [comment] 2023-08-21 11:02
changing to weekly whilst this is on hold.

**Comment by jeet-dhandha** [comment] 2023-09-21 19:50
@zanyrenney The [#21207](https://github.com/Expensify/App/issues/21207) issue is closed so can we remove the hold ?

**Comment by s77rt** [comment] 2023-09-23 23:12
@sakluger Related to https://github.com/Expensify/App/issues/21207. Should we close this one as well? I don't see a better solution than fixing the url that Concierge is sending.

**Comment by zanyrenney** [comment] 2023-10-25 13:36
We should close this one as well!

**Closed by zanyrenney** 2023-10-25 13:36 UTC
Labels: External, Engineering, Monthly, Needs Reproduction, Help Wanted, Overdue, Bug
