### ISSUE TITLE
[$1000] Visiting time zone select page on login displays selected timezone as los angeles for few seconds

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23940] opened 2023-07-31 17:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. If logged in then log out
3. Visit following URL (timezone select URL, can be copied from settings->profile->Timezone->Timezone) : https://staging.new.expensify.com/settings/profile/timezone/select
4. Login and observe that app displays 'America/Los_Angeles' selected for few seconds before switching to currently selected value
## Expected Result: 
App should display currently selected value when we visit timezone select page
## Actual Result: 
App displays 'America/Los_Angeles' selected for few seconds when we visit timezone select page on login

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.47-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/eec79203-8cbc-482b-95cf-fc35e37d7641

https://github.com/Expensify/App/assets/43996225/409eceaa-7908-4804-bbdc-363b5447e960

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690710434957949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014bd05f26e0205708</li>
        <li>Upwork Job ID: 1686104319549071360</li>
        <li>Last Price Increase: 2023-08-21</li>
    </ul>
</details>

**Comment by conorpendergrast** [comment] 2023-07-31 19:59
Hmm, ok, I guess that's a bug. 

@dukenv0307 It looks like America/Los_Angeles is still highlighted in the list under your solution too, by the way!

**Comment by b4s36t4** [comment] 2023-07-31 21:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Visiting time zone select page on login displays selected timezone as los angeles for few seconds
### What is the root cause of that problem?

RCA for this issue is in this function https://github.com/Expensify/App/blob/9294e9eacd53ba2ba805c6e33f18c796ccc3306d/src/pages/settings/Profile/TimezoneSelectPage.js#L90 which will return default timezone if there is not timezone available in `currentUserPersonalDetails` object which could be empty in case of a new login.

Also the `initiallyFocusedOptionKey` being selected to default timezone due to code here https://github.com/Expensify/App/blob/9294e9eacd53ba2ba805c6e33f18c796ccc3306d/src/pages/settings/Profile/TimezoneSelectPage.js#L33 and here https://github.com/Expensify/App/blob/9294e9eacd53ba2ba805c6e33f18c796ccc3306d/src/pages/settings/Profile/TimezoneSelectPage.js#L45.

### What changes do you think we should make in order to solve the problem?

Use `FullscreenLoadingIndicator` till we get `timezone` property in `currentUserPersonDetails` object using conditional rendering having variable maybe `shouldShowOptions` inside the `render` function like below.

```jsx
        const shouldShowOptions = !_.isEmpty(_.get(this.props.currentUserPersonalDetails, 'timezone'));
```

This fixes the issue showing default timezone in the input field, but the issue is that focused option is still default timezone (los-angeles)

As I mentioned RCA for this point, even if we have the updated props it a while to update `selected` timezone to state by then component would render and focus on the default option (los-angeles).

To Prevent that we should calculate the `selected` timezone and pass it here to `initiallyFocusedOptionKey` prop's values like below.

```jsx
    // This ensures instant update with accurate and according to the `currentPersonalDetails` object
    const selectedTimezone = _.get(this.getUserTimezone(this.props.currentUserPersonalDetails), 'selected');
    return (
    
        <SelectionListRadio
        {/* {...otherProps} */}
        initiallyFocusedOptionKey={_.get(_.filter(this.state.timezoneOptions, (tz) => tz.text === selectedTimezone)[0], 'keyForList')}
        />
    )
```

### What alternative solutions did you explore? (Optional)
NA

##Result

https://github.com/Expensify/App/assets/59088937/7d8abe73-f3df-416a-b37e-a42f41ec5361

**Comment by DomingosDev** [comment] 2023-07-31 22:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The issue occurs in the 'getUserTimezone' function of the file src/pages/settings/Profile/TimezoneSelectPage.js. It defaults to returning the timezone America/Los Angeles.


### What is the root cause of that problem?
In the presented scenario, we still don't have the Timezone data in the props.currentUserPersonalDetails object. The received value is "America/Los Angeles," which causes the rendering of text and select components to occur with different values at two different moments.

The first time, in the constructor, we obtain "America/Los Angeles." After that, in 'componentDidUpdate,' the sequence is "America/Los Angeles" and later the real value "America/Sao Paulo" in my case.


### What changes do you think we should make in order to solve the problem?
My proposal is to add a control property to identify when the user's timezone data has been loaded. Let's call it "isUserTimezoneLoaded" for the sake of readability and maintainability.

To achieve this, we need to add the following line of code to the constructor and componentDidUpdate methods:

```javascript
this.isUserTimezoneLoaded = !!this.props.currentUserPersonalDetails?.timezone;
```

For a better user experience, I have chosen to add the FullscreenLoadingIndicator component, conditioned to the value 'false' in this.isUserTimezoneLoaded. To do this, you will need to include the dependencies FullscreenLoadingIndicator and styles.

Tested use cases:
- New user accessing the route directly (not logged in)
- New user navigating through the menu (logged in)
- Existing user navigating through the menu (logged in)
- Existing user accessing the route directly (not logged in)

**Comment by DomingosDev** [comment] 2023-07-31 22:02
Contributor details
Your Expensify account email: domingos.dev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01c56cf7aff2950515

**Comment by LovelyDev829** [comment] 2023-08-01 00:42
Contributor details
Your Expensify account email: lovelydeveloper829@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01002e948943eeb864

**Comment by DanutGavrus** [comment] 2023-08-02 09:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Visiting time zone select page on login displays selected timezone as los angeles for few seconds

### What is the root cause of that problem?
1. In `TimezoneSelectPage`, we get `this.timezone = this.getUserTimezone(props.currentUserPersonalDetails)`, then we set the state of `timezoneInputText` to `this.timezone.selected`. 
2. `this.getUserTimezone` returns the `CONST.DEFAULT_TIME_ZONE` which is `DEFAULT_TIME_ZONE: {automatic: true, selected: 'America/Los_Angeles'}`

### What changes do you think we should make in order to solve the problem?
Replace `selected: 'America/Los_Angeles'` with `selected: ''` in the `DEFAULT_TIME_ZONE` & conditionally return the `SelectionListRadio` component with `initiallyFocusedOptionKey` when available.

https://github.com/Expensify/App/assets/56603839/d4992098-bac8-4bf0-a854-30b1ed371ffa

**Comment by conorpendergrast** [comment] 2023-08-08 10:02
@abdulrahuman5196 Hi - four proposals here to review please!

**Comment by conorpendergrast** [comment] 2023-08-11 12:32
Bumped @abdulrahuman5196 [via Slack](https://expensify.slack.com/archives/C02NK2DQWUX/p1691756009285729) for these reviews

**Comment by rushatgabhane** [comment] 2023-08-11 13:56
instead of waiting on server's response for timezone, why don't we default to the user's current location (from their IP)

Full screen blocking until we have the timezone seems unnecessary to me. Because in most cases, the timezone  will be same as their IP address' timezone

**Comment by b4s36t4** [comment] 2023-08-11 19:27
@rushatgabhane What if user changes the timezone? they don't want the timezone based on their IP (sometimes ip info might be wrong?) and they change the timezone... then this issue still comes right?

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:20
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-13 09:29
@conorpendergrast 
We would need to confirm on the expected behaviour here.

Basically everyones rootcause is correct. When we login, we won't have users timezone immediately and we show a default timezone and when we get proper data from the APIs we update the display with the appropriate timezone.

What do we want to do inbetween time of login and the time of API response having proper timezone?

Should we show a loading indicator? Or do we show something else?

**Comment by abdulrahuman5196** [comment] 2023-08-23 15:57
@conorpendergrast Can we check this https://github.com/Expensify/App/issues/23940#issuecomment-1676296775 and https://github.com/Expensify/App/issues/23940#issuecomment-1676681884

**Comment by abdulrahuman5196** [comment] 2023-08-28 12:07
@conorpendergrast Bump on the above

**Comment by conorpendergrast** [comment] 2023-08-31 16:15
Oh wow, I'm sorry, I missed those questions for so, so long. I'll bring those for discussion internally!

**Comment by conorpendergrast** [comment] 2023-09-04 12:51
I've [posted to #expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q/p1693831808348539), sorry again for the delay there! In that I've recommend we: 

- show a skeleton UI until we have received the user’s timezone setting (automatically set or manually set) and timezone
- Where automatic timezone is the user preference, at that point I recommend we keep the current behaviour of showing the timezones as inactive options

**Comment by conorpendergrast** [comment] 2023-09-05 10:19
No disagreement (and a small amount of agreement) on that proposal so far

**Comment by conorpendergrast** [comment] 2023-09-11 11:25
@dylanexpensify Hey! I posted about a path forward [above](https://github.com/Expensify/App/issues/23940#issuecomment-1705220944), so the next step is to take that, get agreement, and then move this along. Thank you!

**Comment by abdulrahuman5196** [comment] 2023-09-11 15:10
There hasn't been much movement in slack yet @dylanexpensify

**Comment by dylanexpensify** [comment] 2023-09-19 09:33
@abdulrahuman5196 bumped for more thoughts, then we can move forward if not!

**Comment by dylanexpensify** [comment] 2023-09-21 14:41
[Posted internal for urgency](https://expensify.slack.com/archives/C03U7DCU4/p1695307242907519)

**Comment by dylanexpensify** [comment] 2023-09-25 10:49
We decided this is a minor edge case polish, closing

**Closed by dylanexpensify** 2023-09-25 10:49 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
