### ISSUE TITLE
[$250]  Wallet - After adding Debit Card user is directed to /home url and white blank page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39929] opened 2024-04-09 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4480375
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisite: A bank account is added previously
1. Log in with a expensifail account
2. Navigate to Settings; Wallet
3. Click on "Add bank account"
4. Click on the "Debit Card" option
5. Enter any debit card number from this list Sandbox Cards
6. For the rest of the fields you enter any random valid data
7. Click on Save
8. Click Back arrow on Additional Details

## Expected Result:
User is directed to the url "[https://staging.new.expensify.com/settings/wallet"](https://staging.new.expensify.com/settings/wallet%22)
and see the wallet page

## Actual Result:
User is directed to the url "[https://staging.new.expensify.com/home"](https://staging.new.expensify.com/home%22)
instead of "[https://staging.new.expensify.com/settings/wallet"](https://staging.new.expensify.com/settings/wallet%22)
and see a blank white page after blinking a milisecond wallet page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c814386f-febb-4c25-a4df-baf6f8aab176

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1f26018d8ecba15</li>
        <li>Upwork Job ID: 1778889569395892224</li>
        <li>Last Price Increase: 2024-04-12</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-09 13:17
@johncschuster  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by godofoutcasts94** [comment] 2024-04-09 14:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Wallet - After adding Debit Card user is directed to /home url and white blank page
### What is the root cause of that problem?
I think here : 
https://github.com/Expensify/App/blob/a7b8d77e1c425cc009da87025a0b056d4cbd6362/src/pages/settings/Wallet/AddDebitCardPage.tsx#L130
we are just using `goBack` 
### What changes do you think we should make in order to solve the problem?

Instead we should use `ROUTES.SETTINGS_WALLET` to go back to `Wallet Page`, when we click on `Save` and `Back arrow on Additional Details`
### What alternative solutions did you explore? (Optional)
Additionally, i think here :
https://github.com/Expensify/App/blob/a7b8d77e1c425cc009da87025a0b056d4cbd6362/src/pages/EnablePayments/AdditionalDetailsStep.tsx#L136
we have defined it to be null, rather we need to add routing it back to `SETTINGS_WALLET`

**Comment by bernhardoj** [comment] 2024-04-09 16:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After adding a debit card, the user is shown a LHN with an empty/blank central page screen.

### What is the root cause of that problem?
After adding a debit card page, we call `PaymentMethods.continueSetup()`
https://github.com/Expensify/App/blob/8e7575a97bb797da95a3a869240bc3b15fd1f995/src/pages/settings/Wallet/AddDebitCardPage.tsx#L82

In `PaymentMethods.continueSetup()`, we call `Navigation.goBack` with a fallback route and the fallback route value is defaulted to `ROUTES.HOME`. `ROUTES.HOME` refers to the LHN.
https://github.com/Expensify/App/blob/efa7d16313b92b8b11184f76e62bd12c89257a5b/src/libs/actions/PaymentMethods.ts#L35

Because the add debit card page is the only RHP page, the fallback route will be used, so the add debit card page is replaced with `ROUTES.HOME`, that's why we see the LHN with an empty/blank central page screen.

### What changes do you think we should make in order to solve the problem?

We should remove the default fallback route and make it optional.
https://github.com/Expensify/App/blob/efa7d16313b92b8b11184f76e62bd12c89257a5b/src/libs/actions/PaymentMethods.ts#L33

This way, after adding a debit card page, the page behind the RHP will still be the settings page.

This is consistent with what we did in this [PR](https://github.com/Expensify/App/pull/36050) which is removing ROUTES.HOME from fallback route.

**Comment by bernhardoj** [comment] 2024-04-17 05:36
PR is ready

cc: @dukenv0307

**Comment by hayata-suenaga** [comment] 2024-05-10 22:44
[The PR was deployed to production three weeks ago](https://github.com/Expensify/App/pull/40333#issuecomment-2069792737). I don't know why Melvin didn't remove the reviewing label.

**Comment by johncschuster** [comment] 2024-05-13 20:46
Oh wow, thanks for calling that out, @hayata-suenaga. I'll get payment taken care of now.

**Comment by johncschuster** [comment] 2024-05-13 20:48
I've issued payment 🎉 . Thanks for your patience, everyone!

**Comment by hayata-suenaga** [comment] 2024-05-13 21:54
closing the issue now. Please feel free to re-open the issue if the payments haven't received 😄

**Closed by hayata-suenaga** 2024-05-13 21:54 UTC
Labels: External, Daily, Bug
