### ISSUE TITLE
Dev - Infinite spinner while closing account [reported by Varsha]

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13400] opened 2022-12-07 16:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to new
2. go to Settings - Security - Close account
3. observe the Spinner on Close account button

## Expected Result: 
Infinite spinner should not be displayed

## Actual Result: 
Infinite spinner while closing account

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.36-2
**Reproducible in staging?:** Needs reproduction (Seems happening only in DEV)
**Reproducible in production?:** Needs reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
https://user-images.githubusercontent.com/43996225/206235125-3f48bc96-1a81-4d1e-a0b9-2fcbd452e1c8.mov
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @varshamb 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670346549403099

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2022-12-07 20:06
I'm not being able to reproduce this in staging/web or any platform/dev. I'm going to ask a bit more in the slack thread.

**Comment by aldo-expensify** [comment] 2022-12-08 22:39
We rely on the Pusher events clearing the Onyx data after a successful `CloseAccount` request, I'm guessing that the reporting user may be somehow missing these updates sent through pusher:

https://github.com/Expensify/App/blob/46f8297c62f448180cfc79b8968f9383f1d9e12b/src/libs/actions/User.js#L72-L89

**Comment by aldo-expensify** [comment] 2022-12-09 01:53
@Beamanator since you worked on the [refactor](https://github.com/Expensify/App/pull/9635) of `CloseAccount`, do you see why this could be happening?

I'm inclined to just closing the issue because I think this is rare case where the user is missing the pusher events (that's my theory at least). An easy fix could be to clear the Onyx data also on `successData`, but that would mean that we are not trusting the Pusher which our application heavily relies on.

**Comment by aldo-expensify** [comment] 2022-12-09 21:21
This has been resolved, Cloudflare was blocking the request `api/command=AuthenticatePusher` which ended up causing the Pusher not to work.

@sonialiap Can you handle the reporting compensation for @varshamb 🙏

**Comment by aldo-expensify** [comment] 2022-12-09 21:23
Internal PR that fixed the issue: https://github.com/Expensify/Terraform/pull/616

**Comment by sonialiap** [comment] 2022-12-12 12:27
@varshamb could you please apply for this job https://www.upwork.com/jobs/~01e2831fb3d87a6543

**Comment by sonialiap** [comment] 2022-12-22 18:12
Upwork proposal sent

**Comment by sonialiap** [comment] 2022-12-30 10:39
waiting for  @varshamb to approve offer so that I can issue payment 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/17131195/210061362-14024dd5-2b9a-4646-aa4d-cf126e09c2bf.png">

**Comment by sonialiap** [comment] 2023-01-02 21:29
Payment issued and contract ended, closing

**Closed by sonialiap** 2023-01-02 21:29 UTC
Labels: Reviewing, Daily, Internal, Bug
