### ISSUE TITLE
[$500] Task message preview when copied is not copying exact content

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#27072] opened 2023-09-08 21:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. GO to any chat
2. - create a task
3. - from the parent chat (where task was created), hover and copy to clipboard
4. - another variant is assign someone to task and then copy the task

## Expected Result:
 the content copied should be as it is.
for assigned task, in preview it shows email but it doesn't in copied content
## Actual Result:
Copied content is different than what it looks like,
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/c5aace67-8aeb-4869-bef3-4a63d89122d7

https://github.com/Expensify/App/assets/38435837/8247efc7-e1b7-4b2c-9fd0-6e6a94e3cdd9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @BhuvaneshPatil
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693362042758229

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015b94ed2d509c9a78</li>
        <li>Upwork Job ID: 1700261641929674752</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by zukilover** [comment] 2023-09-08 23:27
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Copied task message is different than what it looks like.

### What is the root cause of that problem?
`ContextMenuActions` is only copying from the original message of the report action:
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/pages/home/report/ContextMenu/ContextMenuActions.js#L188-L190

While in task preview, it is formatted to also include task assignee:
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/components/ReportActionItem/TaskPreview.js#L73-L74

### What changes do you think we should make in order to solve the problem?
Add consistent copyable content by including task assignee in the ContextMenuActions, e.g.:
```
             const message = _.last(lodashGet(reportAction, 'message', [{}]));
            const originalMessage = _.get(reportAction, 'originalMessage', {});
            const taskAssigneeAccountID = reportAction.childManagerAccountID;
            const [assigneeLogin] = PersonalDetailsUtils.getPersonalDetailsByIDs([taskAssigneeAccountID]);
            const taskAssignee = assigneeLogin?.login || assigneeLogin?.displayName;
            const formattedTaskMessage = taskAssignee ? `Created a task: ${taskAssignee} ${reportAction.childReportName}` : lodashGet(message, 'html', '')
            const messageHtml = isTaskAction ? lodashGet(originalMessage, 'html', '') : formattedTaskMessage;
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by BhuvaneshPatil** [comment] 2023-09-09 03:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assigned task title doesn't update when copying after changing it, furthermore even if we copy the task without assignee it gives us text like - `Created a task: <task name>`

### What is the root cause of that problem?
We use content from `messageHtml` variable that is being set like this - 
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/pages/home/report/ContextMenu/ContextMenuActions.js#L190
and it looks like this - 
<img width="247" alt="Screenshot 2023-09-05 at 6 38 16 PM" src="https://github.com/Expensify/App/assets/27822551/6f12e2e9-8e81-4faa-a218-2b3af3c88f81">



But while rendering the created task report action we use this logic
https://github.com/Expensify/App/blob/b95c1dd22474fb48929e78a102c1121c1e6e4360/src/components/ReportActionItem/TaskPreview.js#L74

That's the reason why we are not seeing exact content

### What changes do you think we should make in order to solve the problem?
To solve this issue we need to get the html same as we render in `TaskPreview`.


- For `TaskPreview` we need to make few changes in order to get what we see there(in ReportActionItem), we need to have check if the action is for task creation.
We can add the method in `ReportActionUtils`
```js
function isCreatedTaskReportAction(reportAction) {
    return reportAction.actionName === CONST.REPORT.ACTIONS.TYPE.ADDCOMMENT && _.has(reportAction.originalMessage, 'taskReportID');
}
```

we can store this value and have a special check for it. To get the content for copying we need similar logic here -
https://github.com/Expensify/App/blob/7f13cdd9f5ade3aed50827084aa49b5e3a6496e1/src/components/ReportActionItem/TaskPreview.js#L73
We can add a function for that in `ReportActionUtils` and `ReportUtils`
```js
if (isCreatedTaskReportAction) {
                    const taskReport = ReportUtils.getReport(ReportActionUtils.getTaskReportIDFromReportActionPreview(reportAction));
                    const text = parser.htmlToText(ReportUtils.getTaskPreviewMessage(taskReport, reportAction));
                    Clipboard.setString(text);
}
```

`getTaskReportIDFromReportActionPreview` is for getting reportID for task and `getTaskPreviewMessage` for getting the message for task preview.
PS - I have implemented both the mentioned methods but it will make proposal lengthy, I can share that if reviewer asks for it.

### What alternative solutions did you explore? (Optional)

**Comment by Tony-MK** [comment] 2023-09-09 03:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task message preview when copied is not copying exact content

### What is the root cause of that problem?

The file ContextMenuActions.js posses the code for the copy button. When the copy button is pressed and , the copy button `onPress` handler calls the `setHtml` method on the clipboard with `messageHtml` as the agrument. If the report is a task text, the `messageHtml` is set as `"originalMessage"` value from `reportAction`. The `"originalMessage"` value from `reportAction` is the task title and formatted as `"Created a task: {{Task Title}}"`. 


However, the task title is displayed byt `TaskPreview` component and it does not use the `"originalMessage"` value from `reportAction` but it creates a task title string from `props.taskReport.reportName || props.action.childReportName` and if available, `taskAssginee`.



### What changes do you think we should make in order to solve the problem?


Since the `messageHtml` is not formated according to the html form the `TaskPreview` component, I believe we need to format it according to how it is formatted in the task preview. Therefore, we should move these lines to a function in ReportUtils file called something like `getHtmlforTaskPreview` and substitute the function in `TaskPreview.js`.
 
`
const htmlForTaskPreview = ReportUtils.getHtmlforTaskPreview();
`

Then use the function in `ContextMenu.js` get the html preview of the report action is create task.

`
const mesageHTML = isTaskAction ? (ReportUtils.isCreatedTask(reportAction) ? ReportUtils.getHtmlforTaskPreview() : lodashGet(originalMessage, 'html', '') )  : lodashGet(message, 'html', ''); 
`
### What alternative solutions did you explore? (Optional)

Simply the set the `messageHtml` variable as the `reportAction.childReportName` value instead of `"orginalMessage"`, if the action is create task. This will only copy the task title but will not copy a name of the assginee duser if present.

`
const mesageHTML = isTaskAction ? (ReportUtils.isCreatedTask(reportAction) ? lodashGet(reportAction, "childReportName", ' ') : lodashGet(originalMessage, 'html', '') )  : lodashGet(message, 'html', ''); 
`

**Comment by pecanoro** [comment] 2023-09-12 04:14
Closing, this is a regression from this PR https://github.com/Expensify/App/pull/24630 and already reported.

**Closed by pecanoro** 2023-09-12 04:14 UTC
Labels: External, Daily, Help Wanted, Bug
