### ISSUE TITLE
[$1000] App displays last image even when we preview first image on android chrome

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#24248] opened 2023-08-08 02:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in android chrome
2. Open any report
3. Send 3-4 images
4. Open first image in preview and scroll to last image
5. Click on mobile back and again open first image
6. Again click on mobile back and open first image and now see that app displays last image instead of first image on which we clicked

## Expected Result:
 App should display correct image in preview on android chrome

## Actual Result:
App displays last image even after clicking first image when we send multiple messages, open first image, scroll to last image, close   and open first image and repeat few times
Platforms: android chrome

## Workaround:
unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.49-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 

https://github.com/Expensify/App/assets/43995119/52e9c6ee-5431-4d73-82d1-980461c075ea

https://github.com/Expensify/App/assets/43995119/5d7f5a53-2e0d-4b4a-b5d2-bd0213750f5a

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690957918828549 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b2f93e5871d2c7e0</li>
        <li>Upwork Job ID: 1690365249301753856</li>
        <li>Last Price Increase: 2023-08-12</li>
    </ul>
</details>

**Comment by abdulrahuman5196** [comment] 2023-08-13 08:49
No proposal yet

**Comment by suneox** [comment] 2023-08-17 01:07
The root cause same with issue #23546 not only safari, [in my proposal](https://github.com/Expensify/App/issues/23546#issuecomment-1681058859) have described

**Comment by sonialiap** [comment] 2023-08-18 09:35
Closing out as dupe of https://github.com/Expensify/App/issues/23546

**Closed by sonialiap** 2023-08-18 09:35 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
