### ISSUE TITLE
[$250] Chat - Thread page reloads when user entering it first time after leaving

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#45966] opened 2024-07-22 21:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10-6
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/45921
## Action Performed:
1. Open any chat
2. Send a message
3. Right click on the message > Reply in thread
4. Send a reply in thread
5. Click on the chat header
6. Click Leave
7. Enter the thread again

## Expected Result:
Thread page opens without reloading

## Actual Result:
Thread page reloads after entering thread for the first time after leaving. If user navigates to parent chat and entering thread again, no reload page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/0d27d9b6-b774-487d-9bb6-378e5d8d3d4f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018152ed9583469041</li>
        <li>Upwork Job ID: 1815513755284322155</li>
        <li>Last Price Increase: 2024-07-29</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by lanitochka17** [comment] 2024-07-22 21:04
We think that this bug might be related to #vip-vsp

**Comment by francoisl** [comment] 2024-07-22 21:22
The same thing is happening to me on production - it's not a full page reload per se, just the thread data loading. Not sure it's even a bug tbh.
There's also something weird happening, when I send a message, my profile picture disappears (visible at the end of the video), but that's unrelated to this issue.

https://github.com/user-attachments/assets/e9cecfa0-1ba2-4b25-8483-cde953b1377c

**Comment by chiragsalian** [comment] 2024-07-22 22:26
Cool yup doesn't look like a blocker. I'll demote and apply external label for contributors to investigate.

**Comment by tsa321** [comment] 2024-07-23 00:29
same as https://github.com/Expensify/App/issues/45834

**Comment by devmadhavvv** [comment] 2024-07-23 05:12
Contributor details
Your Expensify account email: madhavmishra28@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0161f3ad9d848f9056?mp_source=share

**Comment by huult** [comment] 2024-07-30 18:25
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Thread page reloads when user entering it first time after leaving

### What is the root cause of that problem?

This issue looks like a backend issue, as described in this [comment](https://github.com/Expensify/App/issues/45834#issuecomment-2241497615)

<img width="1705" alt="Screenshot 2024-07-31 at 01 17 32" src="https://github.com/user-attachments/assets/d4d8e80b-768f-4e2b-91fb-13926f90f23f">

So when `GetMissingOnyxMessages` is called,`reportOnyx` will return undefined, and Skeleton will be displayed, causing it to go to the previous page

https://github.com/Expensify/App/blob/837dad5abb3ba364efa175fc6bd7ac2d52816ecc/src/pages/home/ReportScreen.tsx#L146

The logic handles going to the previous page when `reportOnyx` is undefined.

https://github.com/Expensify/App/blob/837dad5abb3ba364efa175fc6bd7ac2d52816ecc/src/pages/home/ReportScreen.tsx#L585-L614

The logic handles showing the Skeleton when reportOnyx is undefined.

https://github.com/Expensify/App/blob/837dad5abb3ba364efa175fc6bd7ac2d52816ecc/src/pages/home/ReportScreen.tsx#L423

### What changes do you think we should make in order to solve the problem?

Update the GetMissingOnyxMessages API to retrieve the existing value.

### What alternative solutions did you explore? (Optional)

**Comment by chiragsalian** [comment] 2024-07-31 22:46
ah yup looks like it. Thanks for that, it does look like a dupe. Closing out this issue in favor of the other one.

**Closed by chiragsalian** 2024-07-31 22:46 UTC
Labels: External, Engineering, Daily, Help Wanted
