### ISSUE TITLE
[$500] Bank account - Ongoing BA setup shows Connect online instead of Continue setup in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31030] opened 2023-11-07 20:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.96-5
**Reproducible in staging?:** Y
**Reproducible in production?:** N/A, cannot check bank account on production
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to Settings > Workspaces > any workspace
3. Go to Bank account > Connect manually
4. Proceed until the final step (Test transactions)
5. Close the setup
6. Go offline
7. Go to Settings > Workspaces > any workspace > Go to Bank account

## Expected Result:
The Bank account page shows Continue with setup and Start over options

## Actual Result:
The Bank account page shows Connect online with Plaid and Connect manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8d211952-7d6a-4d3d-9dec-4d728e096d9d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018f1012ebf2275e7d</li>
        <li>Upwork Job ID: 1721991376582500352</li>
        <li>Last Price Increase: 2023-12-01</li>
    </ul>
</details>

**Comment by situchan** [comment] 2023-11-10 13:59
Dupe of https://github.com/Expensify/App/issues/26631

**Comment by adelekennedy** [comment] 2023-11-10 17:45
Closing this

**Comment by laurenreidexpensify** [comment] 2023-12-01 11:50
@adelekennedy @abdulrahuman5196 after discussion in https://github.com/Expensify/App/issues/26631 let's reopen this and keep these as two separate issues

**Comment by abdulrahuman5196** [comment] 2023-12-04 19:23
Got it. Will check the proposals in my morning.

**Comment by abdulrahuman5196** [comment] 2023-12-06 18:07
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-12-06 18:59
I gone through the proposals at a glance and the linked issue. I would need more time to analyse. Will update here once done.

**Comment by adelekennedy** [comment] 2023-12-11 16:26
@abdulrahuman5196 thans for the update - do you have an eta on when you'll be able to review?

**Comment by abdulrahuman5196** [comment] 2023-12-12 18:02
I will provide an update by tomorrow.

**Comment by adelekennedy** [comment] 2023-12-15 14:25
@abdulrahuman5196 Should we close this? This isn't directly linked to any of our wave or vip projects at the moment and this is an annoying but ultimately small issue imo

**Comment by abdulrahuman5196** [comment] 2023-12-18 07:58
@adelekennedy I am not sure about priority, might be small issue with little complex fix as per current proposals.

Could you kindly check internal if we should proceed on this?

**Comment by adelekennedy** [comment] 2023-12-18 13:22
closing this one

**Closed by adelekennedy** 2023-12-18 13:22 UTC
Labels: Daily, Internal, Bug
