### ISSUE TITLE
[$1000] Web -Task - Empty description is displayed even when description is set in task

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23294] opened 2023-07-20 18:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click plus and click on assign task
3. Write any title and description and click next
4. Select any assignee and any user to share somewhere and click confirm task
5. In task report, click on plus and click assign task
6. Write any title, keep description empty and click next
7. Close the right hand menu and now click on current report description and observe that even though task has description, it is displayed as empty

## Expected Result:
App should display currently set description when we click on description in any task report

## Actual Result:
App displays empty description when we click on plus and assign task from task report, set title, keep description empty, click on next, close the right hand menu and click on description

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/957d7826-794e-456b-990c-7cbab4d65447

https://github.com/Expensify/App/assets/93399543/ac4c7fe7-b794-445d-a009-172801afe5d9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689841710414669

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010cf7591e3ba247f3</li>
        <li>Upwork Job ID: 1683549848105144320</li>
        <li>Last Price Increase: 2023-07-24</li>
    </ul>
</details>

**Comment by BhuvaneshPatil** [comment] 2023-07-20 18:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Empty description is displayed even when description is set in task

### What is the root cause of that problem?
In `TaskDescriptionPage` component, we are getting task from Onyx.
https://github.com/Expensify/App/blob/e87f2eb32587d29d8b6423fcadc8fe862c73be2d/src/pages/tasks/NewTaskDescriptionPage.js#L94-L104

And when we create new task (partially) as shown in video, the task value is changed and thus when we try to get that value from onyx, we get empty value - 

<img width="342" alt="Screenshot 2023-07-20 at 3 19 37 PM" src="https://github.com/Expensify/App/assets/27822551/fa647c55-b71f-4498-a155-d0bda8dc36b5">


### What changes do you think we should make in order to solve the problem?

Above logic of getting task from onyx works well when we are creating a new task, but for that we use `NewTaskDescriptionPage`.
In this case instead of getting the `task` from onyx, we will get `report`. As we have `reportID` from route, we can use it to fetch the report on `TaskDescriptionPage` and use the value of description from the report.

we can get report fro onyx following way - 

```
report: {
    key: ({route}) => `${ONYXKEYS.COLLECTION.REPORT}${route.params.reportID}`,
},
```


and for `TextInput` we can set the `defaultValue`

```
defaultValue={(props.report && props.report.description) || ''}
```

Similar to this we have done in - `TaskTitlePage`

### What alternative solutions did you explore? (Optional)

**Comment by dhanashree-sawant** [comment] 2023-07-20 18:59
Hi @dhairyasenjaliya, I think they have cross checked that first, kindly check the slack conversation once.

**Comment by BhuvaneshPatil** [comment] 2023-07-21 05:58
The root cause for bug is different for both the issues.

**Comment by BhuvaneshPatil** [comment] 2023-07-21 06:41
This issue solves the problem occurring in #22078 , and the selected [proposal](https://github.com/Expensify/App/issues/22078#issuecomment-1645010647) for that came after this bug, so this bug should fix the #22078

**Comment by isabelastisser** [comment] 2023-07-24 18:23
Not overdue!

**Comment by isabelastisser** [comment] 2023-07-24 18:25
Asking for guidance in Slack:

https://expensify.slack.com/archives/C049HHMV9SM/p1690223105956899?thread_ts=1689841710.414669&cid=C049HHMV9SM

**Comment by sobitneupane** [comment] 2023-07-26 09:21
@isabelastisser I was unable to reproduce the issue. Is this still reproducible on your end?

**Comment by BhuvaneshPatil** [comment] 2023-07-26 09:56
> Though root cause is different, this will be part of solution in #22078 to avoid #23210.

@sobitneupane I think it was solved here.

**Comment by isabelastisser** [comment] 2023-07-26 15:51
Thanks @sobitneupane!

- I will issue the payment in Upwork now and close this issue.

Payment: @dhanashree-sawant $250 - issue reporter.

**Closed by isabelastisser** 2023-07-26 15:51 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by dhanashree-sawant** [comment] 2023-07-26 15:57
Thanks @isabelastisser, I have accepted the offer.
