### ISSUE TITLE
Chat - Content is not loading after network return  if the App starts while offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#12574] opened 2022-11-08 22:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Kill the App (dismiss App's card)
2. Turn network off
3. Start the App
4. Check content in different chats ( will be infinite loading)
5. Turn network on
6. Check content in all chats again (will be infinite loading as well)

## Expected Result:
The user should see the content in chats (that he visited before) when starting offline

## Actual Result:
Content is not loading after network return  if the App starts while offline

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.25.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/200689379-ef0a0284-3967-46d0-a362-afed31eafda8.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by JmillsExpensify** [comment] 2022-11-10 17:52
@muttmuure This one has come up in a couple of contexts. Let's triage this and get the process started.

**Comment by fedirjh** [comment] 2022-11-13 21:08
we have to update  `IS_LOADING_INITIAL_APP_DATA` in reconnectApp

https://github.com/Expensify/App/blob/0d653cad15c32150c302ac12dc0acdbca1ece18b/src/libs/actions/App.js#L162-L180
```diff
function reconnectApp() { 
    API.write('ReconnectApp', {policyIDListExcludingWorkspacesCreatedOffline}, { 
        optimisticData: [ 
            { 
                onyxMethod: CONST.ONYX.METHOD.MERGE, 
                key: ONYXKEYS.IS_LOADING_REPORT_DATA, 
                value: true, 
            }, 
+            { 
+                onyxMethod: CONST.ONYX.METHOD.MERGE, 
+                key: ONYXKEYS.IS_LOADING_INITIAL_APP_DATA, 
+                value: true, 
+            }, 
        ], 
        successData: [ 
            { 
                onyxMethod: CONST.ONYX.METHOD.MERGE, 
                key: ONYXKEYS.IS_LOADING_REPORT_DATA, 
                value: false, 
            }, 
+            { 
+                onyxMethod: CONST.ONYX.METHOD.MERGE, 
+                key: ONYXKEYS.IS_LOADING_INITIAL_APP_DATA, 
+                value: false, 
+            }, 
        ], 
        failureData: [ 
            { 
                onyxMethod: CONST.ONYX.METHOD.MERGE, 
                key: ONYXKEYS.IS_LOADING_REPORT_DATA, 
                value: false, 
            }, 
+            { 
+                onyxMethod: CONST.ONYX.METHOD.MERGE, 
+                key: ONYXKEYS.IS_LOADING_INITIAL_APP_DATA, 
+                value: false, 
+            }, 
        ], 
    }); 
}
```

**Comment by mountiny** [comment] 2022-11-14 16:12
cc @marcaaron I think this is mentioning your PR, what do you think of the proposal, as you might have more insight into this.

**Comment by marcaaron** [comment] 2022-11-14 19:39
I think we should just revert my [PR here](https://github.com/Expensify/App/pull/12169). It's more important for the offline behavior to work than the new marker behavior to work. My solution to fix it was flawed and should be reverted.

**Comment by amyevans** [comment] 2022-11-14 20:00
Yeah, agreed that the new marker behavior is less important, thanks @marcaaron!

**Comment by Tushu17** [comment] 2022-11-15 16:29
I had reported an issue [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667941642843519) as a regression related to skeleton ui and it got resolved by the PR([link](https://github.com/Expensify/App/pull/12722)) of this issue. so I believe I am eligible for the reporting bonus.
I had reported the issue at (2:37) and this issue was created at (3:56) it wasn't a dupe.
cc- @muttmuure

**Comment by muttmuure** [comment] 2022-11-22 13:02
@Tushu17 the first report is here from Carlos - https://expensify.slack.com/archives/C01GTK53T8Q/p1667839756928309 - so this doesn't seem eligible for the reporting bonus this time.

I'm going to close out. 

Let me know if you disagree!

**Comment by Tushu17** [comment] 2022-11-22 13:55
> the first report is here from Carlos - https://expensify.slack.com/archives/C01GTK53T8Q/p1667839756928309 

Hi, @muttmuure  that wasn't a bug you can see the convo [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667840173309119?thread_ts=1667839756.928309&cid=C01GTK53T8Q),  it was marked as "not a bug" because it was just a dev build problem.

**Comment by mananjadhav** [comment] 2022-11-22 15:40
@muttmuure this is eligible for C+ review of internal PR. Can you please help with the same ? 

cc - @marcaaron

**Comment by JmillsExpensify** [comment] 2022-11-28 14:23
@muttmuure Can you issue payment for @mananjadhav. Thanks!

**Comment by mananjadhav** [comment] 2022-11-29 13:50
@muttmuure Quick bump on this, can you help with the payout?

**Comment by JmillsExpensify** [comment] 2022-11-29 18:07
@mananjadhav can you apply here please? https://www.upwork.com/jobs/~011aef35eb61fef46b

**Comment by Tushu17** [comment] 2022-11-29 18:11
> Hi, @muttmuure that wasn't a bug you can see the convo [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667840173309119?thread_ts=1667839756.928309&cid=C01GTK53T8Q), it was marked as "not a bug" because it was just a dev build problem.

@JmillsExpensify, I'm also eligible for reporting bonus.

**Comment by mananjadhav** [comment] 2022-11-29 18:16
Thanks @JmillsExpensify for the help here. All done for my side.

**Comment by JmillsExpensify** [comment] 2022-11-29 18:17
@Tushu17 Same link above should work for you.

**Comment by mananjadhav** [comment] 2022-11-29 18:18
@JmillsExpensify Wrong comment. The paid out comment was for another issue. I am unable to apply to this job. It says `Only invited users can find, view and apply to the job`

**Comment by JmillsExpensify** [comment] 2022-11-29 18:23
Just invited you. Upwork is being difficult 😄

**Comment by mananjadhav** [comment] 2022-11-29 18:31
Haha! Applied @JmillsExpensify

**Comment by JmillsExpensify** [comment] 2022-11-29 18:33
Offers just sent to both C and C+

**Comment by JmillsExpensify** [comment] 2022-11-29 18:40
Everyone should be handled now. Regression test also already exists, so I think we're done here. Closing!

**Closed by JmillsExpensify** 2022-11-29 18:40 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug
