### ISSUE TITLE
[NEW FEATURE] load avatars as participants are selected in send money, split, and request flows, rather than after the expense is created

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#31163] opened 2023-11-10 00:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:** https://github.com/Expensify/Expensify/issues/328013
**Issue reported by:** Internal
**Slack conversation:** [here](
Originally discussed this one here for more context

https://expensify.slack.com/archives/C05RECHFBEW/p1697588513404599) and [here](https://expensify.slack.com/archives/C05RECHFBEW/p1699388014386859)

## Action Performed:

1. Open global create > Request money
2.Select "split" with two users you have no chat history with have not interacted with before 
3. Continue to the confirmation screen, note the avatars
4. Split the bill

## Expected Result:
This is NOT the design today, but oner would expect to see the user's avatar on this screen, especially given they are potentially paying someone and will want to confirm it's the right person. 

## Actual Result:
The avatar images are random (screen 1), and then they update after the split is initiated (screen 2)
![image](https://github.com/Expensify/App/assets/22508290/55f807c1-5cb4-4e71-8a88-fd94ec5a4f67)

![image](https://github.com/Expensify/App/assets/22508290/c541acd4-d6b2-41de-8992-66b3a94f830d)

This design is not ideal for a few important reasons:

1. If I used this with real people (like on venmo), I frequently use their photo to increase my own confidence that I'm sending this to the right person. This design doesn't allow for that
2. It looks buggy when everything updates seconds later. Also does not inspire confidence when I'm trying to send real money to people.

## Platforms:
All

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014c2bf2629cdceb8c</li>
        <li>Upwork Job ID: 1722768866278567936</li>
        <li>Last Price Increase: 2023-11-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @grgia</details>

**Comment by abekkala** [comment] 2023-11-13 16:40
@kevinksullivan with the Internal label applied does that mean you'll be the one submitting the PR for this? 
Or do you want me to apply the `Engineering` label to get this assigned to someone?

**Comment by kevinksullivan** [comment] 2023-11-14 00:27
>with the Internal label applied does that mean you'll be the one submitting the PR for this? Or do you want me to apply the Engineering label to get this assigned to someone?

I wish, but no I will not be submitting the PR 😄 . Let's add that label here, sorry I figured the `internal` label alone would do the trick.

**Comment by grgia** [comment] 2023-11-16 11:42
@kevinksullivan I think we can make this external- is there a reason it's internal? I can look into this if so

**Comment by grgia** [comment] 2023-11-20 14:25
@kevinksullivan bump on the above

**Comment by grgia** [comment] 2023-11-21 14:16
@kevinksullivan I've been thinking about this one and it does make sense to see the avatar, though through emails- it seems like it would be easy to use this feature or search as a way to discover the account of a specific person. 

At what point do a user's personal details get added to your account? Do both parties have to interact with each other or do I need to DM someone?

**Comment by abekkala** [comment] 2023-11-22 21:36
I'm heading out for the Thanksgiving holiday and will be back to look at this bright and early Monday morning.

**Comment by grgia** [comment] 2023-11-27 12:02
still waiting on some background on this issue, moving to weekly since its not associated with a wave

**Comment by kevinksullivan** [comment] 2023-11-27 22:57
>At what point do a user's personal details get added to your account? Do both parties have to interact with each other or do I need to DM someone?

Asking about that logic here

https://stackoverflowteams.com/c/expensify/questions/17966

**Comment by grgia** [comment] 2023-12-06 11:33
cc @puneetlath would you mind taking a look at this issue as it related to hidden personal details and let me know what you think the logic change might be here?

**Comment by puneetlath** [comment] 2023-12-06 17:33
Hmm, I don't think this has anything to do with the "hidden" stuff. Because avatar is a field that we will return whether or not you know someone. I'm guessing we just haven't called the API yet when you hit this screen: 
<img width="381" alt="image" src="https://github.com/Expensify/App/assets/1371996/b053bf43-3423-4744-b4cb-7a6aab7a9c3d">

So we haven't had their real avatars returned from the server. Or if we are calling the API, then we just need to include the personal details in the API response.

**Comment by kevinksullivan** [comment] 2023-12-12 01:49
From the original convo it also sounded like what @puneetlath is saying @grgia 

>So we haven't had their real avatars returned from the server.

**Comment by grgia** [comment] 2023-12-13 16:36
okay, so we need to return personal details when we open the split screen? @puneetlath

**Comment by puneetlath** [comment] 2023-12-13 16:45
Yes, that sounds right. 

Just FYI @grgia you should feel free to un-assign yourself from this if you are actively working on Wave stuff. We shouldn't be auto-assigning out VIP work (cc @kevinksullivan)

**Comment by grgia** [comment] 2023-12-13 17:23
gotcha, going to unassign for now then @puneetlath @kevinksullivan

**Comment by abekkala** [comment] 2023-12-18 14:39
@kevinksullivan is this part of a wave in which it would get linked to a specific project?

**Comment by kevinksullivan** [comment] 2023-12-20 01:12
This is related to #vip-split-p2p-chat-groups

**Comment by abekkala** [comment] 2024-01-11 19:23
Not overdue.

**Comment by tgolen** [comment] 2024-01-18 20:16
I just tried it out and couldn't reproduce this problem (maybe it's fixed?). Here is what I did:

1. Sign into Account A and upload a custom avatar
2. Sign into Account B
3. Click on global create > request money > manual > next
4. On the participant page, I searched for Account A
5. I verified that their custom avatar showed in the results

If you can still reproduce it, please provider accurate reproduction steps and reopen this.

**Closed by tgolen** 2024-01-18 20:16 UTC
Labels: Engineering, Weekly, Internal, Hot Pick
