### ISSUE TITLE
[$250] Onfido terms fonts in the verify identity page are not legit (Get Onfido to use our fonts)

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44570] opened 2024-06-27 20:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2.4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:**
https://expensify.slack.com/archives/C049HHMV9SM/p1719491934827009
## Action Performed:
1. Open app in dark mode
2. Go to workspace
3. Connect to a bank
4. Enter the manual credentials
5. Proceed to verify identity page
## Expected Result:
The terms page should be easily legible
## Actual Result:
The fonts and colours are difficult to read
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![SCR-20240627-lswi](https://github.com/Expensify/App/assets/38435837/e4bf38b8-7de3-451e-88ba-df90885c1e93)
![Snip - (4) New Expensify - Google Chrome (2)](https://github.com/Expensify/App/assets/38435837/8632f7cd-678e-4562-9715-6c579d1419a9)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0162040e800bb2d883</li>
        <li>Upwork Job ID: 1808367008542862770</li>
        <li>Last Price Increase: 2024-07-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by JmillsExpensify** [comment] 2024-07-03 05:07
Opening up to the community.

**Comment by samilabud** [comment] 2024-07-05 19:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onfido terms fonts in the verify identity page are not legit

### What is the root cause of that problem?
The link font color does not have the right contrast for the background color ([link to test](https://webaim.org/resources/linkcontrastchecker/?fcolor=051C09&bcolor=E7ECE9)):

<img width="820" alt="image" src="https://github.com/Expensify/App/assets/5216036/915067ef-f9a3-4805-b909-f9b456089392">


### What changes do you think we should make in order to solve the problem?
This data is loaded using an iframe and this does not use the Expensify styles, so we must modify this using javascript to alter the CSS, so we should use the link color like #D1D1FF ([contrast test link])(https://webaim.org/resources/linkcontrastchecker/?fcolor=051C09&bcolor=E7ECE9). Also, we can use a font family like 'san-serif and a font weight of 200;

Example:

https://github.com/Expensify/App/assets/5216036/b4912b51-4ac2-4b72-bb83-0335766dff98

**Comment by sobitneupane** [comment] 2024-07-08 04:34
Waiting for proposal

**Comment by MrMuzyk** [comment] 2024-07-10 10:40
I am Michał from Callstack - expert contributor group. I’d like to work on this job.

Can you provide some more info on expected result? How should it look like? At the moment we're providing set of styles in order to achieve this custom Onfido look so there is room to change some things

https://github.com/Expensify/App/blob/987c96511b7e05fec05cbe4a34dbd2674082f626/src/components/Onfido/BaseOnfidoWeb.tsx#L25-L66

**Comment by sobitneupane** [comment] 2024-07-11 07:00
I believe we would want it to use fonts like existing pages in RHP. For example: Settings > Save the World > I am a teacher

<img width="1440" alt="Screenshot 2024-07-11 at 12 42 45" src="https://github.com/Expensify/App/assets/25876548/7770f337-e465-4863-a804-3102d781af8f">

**Comment by MrMuzyk** [comment] 2024-07-11 10:51
Ok, I'm looking for a cause for this weird look. We're passing custom fontStyles so in theory it should be working but for some reason it isn't.

**Comment by MrMuzyk** [comment] 2024-07-11 14:01
What I've found so far is that few months ago we've upgraded to v14 of Onfido from v13 and this seems to cause the trouble.

I've reverted back to v13 locally to confirm that and passed font seems to be working fine.
 
<img width="1467" alt="onfidov13" src="https://github.com/Expensify/App/assets/23487612/82f8bd97-86c0-46e6-af70-ea63b669c9b3">

Currently we're on version 14.15.0. I've tried upgrading it to the latest one (14.30.0) but the issue persists. 

I'm beginning to think that this is an issue on the sdk side and we can't really do anything about it apart from changing it to one of the fonts they officially support that will resemble our own one ([list on the bottom](https://github.com/onfido/onfido-sdk-ui/blob/master/UI_CUSTOMIZATION.md)).

I will look into a bit more and try to find a workaround for this.

**Comment by MrMuzyk** [comment] 2024-07-12 12:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Fonts are looking suspicious and do not match rest of the app on Onfido screen

### What is the root cause of that problem?

There weren't any changes on our end when it comes to fonts used in Onfido iframe so after investigating that everything looks fine on our end I've started looking for the cause on the package side. 

When onfido-sdk-ui package was upgraded to v14 the fonts stopped working. I've confirmed that by downgrading to v13 (see screenshot). After lowering version it simply started working again.

<img width="1467" alt="onfidov13" src="https://github.com/user-attachments/assets/8df9fe85-5bc7-429e-9e78-dbbf32c2cb82">

I'm suspecting that this is something that is broken on the Onfido package side so definitve root cause isn't known. What happens is that the font we're providing is not being detected so it defaults to some serif font causing this look reported in the issue. Why it is not being picked up - I don't know. There is no `Issues` tab in onfido-sdk-ui github repository so I can't even tell if this is something that other people are struggling with.


### What changes do you think we should make in order to solve the problem?


Custom font provided by us via customUI prop when initializing Onfido is not being picked up by iframe so font defaults to some serif one. We can comment out  (and leave a comment why is that) `fontFamilyTitle`,  `fontFamilySubtitle` and `fontFamilyBody` styles inside customUI object so it uses default Onfido font which looks much nicer. In the meantime we can report the issue to Onfido and wait for them to fix it (if it's actually on them). Below screenshot how it looks with default Onfido font.

<img width="1255" alt="onfido-default-font" src="https://github.com/user-attachments/assets/e4bacbd5-aed0-4d6e-9729-d4815cfbe83a">


### What alternative solutions did you explore? (Optional)

I've tried upgrading package from 14.15.0 (current version in app) to latest one (14.30.0) but the issue persists.

There is also an option to change the font to one of the google fonts they support. I've tried one of them and it worked. This is the [list](https://github.com/onfido/onfido-sdk-ui/blob/master/UI_CUSTOMIZATION.md) of them

**Comment by sobitneupane** [comment] 2024-07-15 08:55
> we can report the issue to Onfido and wait for them to fix it (if it's actually on them).

@MrMuzyk I believe this is the best approach. First, let's inform them about the issue. If they respond quickly and decide to fix it, we can wait.

**Comment by MrMuzyk** [comment] 2024-07-15 09:13
>First, let's inform them about the issue.

Should I do this?

Instructions are here on the bottom of the README.md - https://github.com/onfido/onfido-sdk-ui

**Comment by sobitneupane** [comment] 2024-07-16 07:21
@MrMuzyk I will request internal engineer to confirm the next step.

[This](https://github.com/Expensify/App/issues/44570#issuecomment-2225438542) is the proposal from @MrMuzyk . The issue probably lies in onfido-sdk-ui repo. [My suggestion](https://github.com/Expensify/App/issues/44570#issuecomment-2228004650) is to first inform them about the issue. 

🎀 👀 🎀 C+ reviewed

**Comment by roryabraham** [comment] 2024-07-16 20:38
Agree we should first inform them about the issue, but frankly I haven't had any good experiences working with Onfido. https://github.com/onfido/react-native-sdk/pull/115 has been open for more than a year without getting reviewed, despite the fact that we pay for Onfido and opened multiple support tickets asking for them to review it.

In the meantime, we should start working on a patch for onfido-sdk-ui to fix the regression in v14, and submit an upstream PR with the fix.

**Comment by MrMuzyk** [comment] 2024-07-17 07:09
Onfido-sdk-ui pakcage doesn't expose it's code publicly so I don't think we can fix it in our own.

**Comment by roryabraham** [comment] 2024-07-17 09:14
thanks for clarifyin @MrMuzyk. Interesting that they have a [public repo](https://github.com/onfido/onfido-sdk-ui) but not public source code...

so then I agree in the short-term that the font from [this screenshot](https://github.com/Expensify/App/issues/44570#issuecomment-2225438542) would be better than the one from the issue description. Let's make that change, then also create an issue in the repo.

**Comment by MrMuzyk** [comment] 2024-07-17 09:26
I can change the font but unfortunately I can't create an issue in their repo reporting that - they have no `Issues` tab so it's not possible. The only reporting option that they have is to do it via email or their support - https://github.com/onfido/onfido-sdk-ui?tab=readme-ov-file#support

**Comment by roryabraham** [comment] 2024-07-17 09:33
ok, I can do that but it might have to be next week.

**Comment by twisterdotcom** [comment] 2024-07-17 09:37
I will reach out to Onfido about this.

**Comment by MrMuzyk** [comment] 2024-07-17 09:42
Awesome, I will open a PR shortly

**Comment by twisterdotcom** [comment] 2024-07-17 10:07
<img width="831" alt="image" src="https://github.com/user-attachments/assets/40a5c8e7-44ad-4061-a4d3-2daeeb8cf484">

**Comment by roryabraham** [comment] 2024-07-17 17:20
Thanks @twisterdotcom 🙇🏼

**Comment by sobitneupane** [comment] 2024-07-29 08:56
https://github.com/Expensify/App/pull/45587 deployed to production last week.

**Comment by twisterdotcom** [comment] 2024-07-29 20:48
5 days ago: https://github.com/Expensify/App/pull/45587#issuecomment-2249280347

**Comment by twisterdotcom** [comment] 2024-07-29 20:49
Payment Summary:

- @MrMuzyk does not require payment (Contractor)
- @sobitneupane paid $250 via Manual Requests (C+)

**Comment by garrettmknight** [comment] 2024-09-02 17:40
$250 approved for @sobitneupane based on[ this summary.](https://github.com/Expensify/App/issues/44570#issuecomment-2256923637)

**Comment by shawnborton** [comment] 2024-09-12 08:08
Do we have any idea on when they would have a fix for this on their side? Just wondering if we have plans to follow up and undo our hotfix here when the time is right. Thanks!

**Comment by twisterdotcom** [comment] 2024-09-12 09:47
Just looking back through my emails and found this actually from about a month ago - they cc'd contributors@ so it hit a filter in my inbox, apologies:

> Starting with v14, the control of what fonts to use has moved to our side hence why you can’t use your own custom fonts.
> Could you please provide us with a list of the fonts that you require so that we can request our engineering team to add them.

I guess I could send them the names and font files and we could see if they can add them?

**Comment by twisterdotcom** [comment] 2024-09-12 12:25
I have asked.

**Comment by twisterdotcom** [comment] 2024-09-12 12:59
>Hi Ted,
> 
> Could you please share the fonts so we can share them with our engineering team. We can guarantee that we support Google fonts but for other fonts we will need to confirm how to provide them for you.
> 
> Best Regards,
> Onfido Support

**Comment by twisterdotcom** [comment] 2024-09-12 12:59
Just reopening for me to track. @shawnborton can you point me to the font files and I'll share them?

**Comment by twisterdotcom** [comment] 2024-09-12 13:00
Not overdue, just reooened.

**Comment by shawnborton** [comment] 2024-09-12 13:08
I would just tell them that we use custom .woff files for web and .ttf files for the native apps and see what they say? Give that we're open source, you could show them this: https://github.com/Expensify/App/tree/main/assets/fonts

**Comment by twisterdotcom** [comment] 2024-10-01 14:06
<img width="938" alt="image" src="https://github.com/user-attachments/assets/28b5da45-31c8-4cf4-a900-09ea934126e1">

How much do you like our fonts?

**Comment by twisterdotcom** [comment] 2024-10-02 09:40
Will leave this until @shawnborton gets back, but my take on this is that we probably don't care about paying $10k, or even negotiating to get our fonts used here when there are likely fonts they have available that are _close enough_ available in google fonts: https://fonts.google.com/.

I'd say we should:

1. Push back, confirming this was previously supported and then removed without notice
2. If they still don't come down a lot (say to $500/$1000), we just agree to use another Google font instead of whatever Onfido's default is.
3. Maybe look at the Onfido API again instead: https://docs.google.com/document/d/1UN_Hei2aWtsUiAh1WLAQOHtV3CWHqmSB1uzNkwHAm2E/edit#heading=h.ns12dr1f35rx (although the downsides were maintenance and the lack of videos).

**Comment by roryabraham** [comment] 2024-10-04 23:26
Going on parental leave and gotta hand this off. It's not clear to me whether we'll need internal engineering help so not going to reassign for now

**Comment by shawnborton** [comment] 2024-10-14 19:23
@twisterdotcom I think the path you laid out above sounds great to me.

**Comment by twisterdotcom** [comment] 2024-10-15 14:00
Okay, waiting for them to come back:
<img width="797" alt="image" src="https://github.com/user-attachments/assets/276fe1f3-38b7-40d3-b413-a48fdd0effb5">

**Comment by twisterdotcom** [comment] 2024-10-31 14:33
Okay, they're gonna allow custom fonts again next year!

> Hello Ted,
> 
> Hope you’re doing well. Apologies for the late response again and here’s what I got from my engineering and Product team:
> 
> Custom Fonts: We will re-introduce the mechanics to allow for URL-based selection and loading of fonts in v14 of our SDK:
> 
> We will do it as part of our standard dev process, and we’ll not ask for financial contribution
> We do not have a specific timeline for this but hope to address it before the end of the year. Anything sooner will require a formal CURE case(internal process to prioritise) as we will need to descope work.
> We will provide an overview of the mechanics to use the feature when we get closer.
> 
> React-Native Fabric: We are not able to commit to revamping our RN SDK as this work doesn’t align with Onfido current priorities. Onfido will be revisiting our React Native and Flutter SDKs later next year once our current core SDKs (iOS and Android) have been rewritten/ rebuilt.

I asked them to just let me know when and we can create an issue then.

**Closed by twisterdotcom** 2024-10-31 14:33 UTC
Labels: External, Weekly, Help Wanted, Bug
