### ISSUE TITLE
Payments - I accept the Expensify Terms of Service and state are not clickable

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42767] opened 2024-05-29 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.77-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4581183
**Email or phone of affected tester (no customers):** dave0123seife+test29@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to Settings > Wallet
2. Click on "Add payment method"
3. Click on the "Debit Card" option
4. Notice that I accept the Expensify Terms of Service and state are not clickable on the Debit card fields

## Expected Result:
I accept the Expensify Terms of Service and state are clickable

## Actual Result:
I accept the Expensify Terms of Service and State are not clickable

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/832b341f-1f1d-4c1e-bfd1-d0d888fe03b7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-05-29 14:48
@luacmartins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-05-29 15:11
This seems to share the same root cause as https://github.com/Expensify/App/issues/42768

**Comment by luacmartins** [comment] 2024-05-29 16:30
I wonder why we even have that prop. We could have just reused `submitButtonStyles`

**Comment by luacmartins** [comment] 2024-05-29 16:33
@ShridharGoel according to your RCA this issue has been present for a while? So does that mean it's not a blocker?

**Comment by luacmartins** [comment] 2024-05-29 16:33
@ShridharGoel I think we should just remove the prop and use `submitButtonStyles` when needed to pass the flex style

**Comment by luacmartins** [comment] 2024-05-29 16:36
Ah ok, makes sense. @ShridharGoel let's resolve this issue too - https://github.com/Expensify/App/issues/42768

**Comment by arosiclair** [comment] 2024-05-29 17:05
Hmm if these bugs are introduced by https://github.com/Expensify/App/pull/35045 then the authors should fix it (cc @pac-guerreiro). We already agreed to revert the PR [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1716990791744559).

**Comment by luacmartins** [comment] 2024-05-29 22:57
This is fixed by the revert. Closing.

**Closed by luacmartins** 2024-05-29 22:57 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
