### ISSUE TITLE
[Hold for payment 12-14-2023][$1000] Mention options are not displayed on focus if we cancel add attachment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22447] opened 2023-07-07 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Type @ to trigger mention options
4. Click on plus and click on add attachment
5. Click on cancel and observe that focus is still in compose box but mention options are not displayed
## Expected Result: 
App should display mention options (for eligible text) when focus is on compose box
## Actual Result: 
App does not display mention options when we click on add attachment and cancel it even though focus is on compose box

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.38-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/55caf109-d827-4d16-ad72-efc7d9d1ad72

https://github.com/Expensify/App/assets/43996225/51d66663-8121-4729-ad2d-ec18baa1d8be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688751437804389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b41000cdf4fb45bb</li>
        <li>Upwork Job ID: 1677463484044013568</li>
        <li>Last Price Increase: 2023-11-14</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27685494</li>
<li>dhanashree-sawant | Reporter | 27685495</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-07-08 09:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Mention suggestions are not shown on focus if we cancel adding attachment.

### What is the root cause of that problem?

Mention suggestions are calculated in `onSelectionChange` event handler. If a user opens the file picker, selects a file, and closes the modal, then the composer input gets focused by the below code.
https://github.com/Expensify/App/blob/60f48175c9e3342ef192d878218820e5ed5a76cd/src/pages/home/report/ReportActionCompose.js#L268-L270

When `focus()` is called on blurred input, `onSelectionChange` is called and suggestions are recalculated.

But if the user cancels the file picker, `modal.isVisible` doesn't change and so `focus()` isn't called.

This is the root cause

### What changes do you think we should make in order to solve the problem?

This isn't specific to mentions. The same problem exists for emojis. We need to fix both.

If we recalculate the suggestions `onFocus`, suggestions would be calculated multiple times. So We need to recalculate the suggestions when file picker is cancelled.

Introduce a new instance variable isFilePickerOpened with initial value false

```
        this.isFilePickerOpened = false;
```

Set this value to true when openPicker is called
```
        this.isFilePickerOpened = true;
```

Set this value to false when modal is hide(AttachmentModal's modalHide props).

Change the onFocus of the composer(this.isFilePickerOpened = true when cancelled)
```
        onFocus={() => {
            if (this.isFilePickerOpened) {
                this.isFilePickerOpened = false;
                this.shouldBlockEmojiCalc = false;
                this.shouldBlockMentionCalc = false;
                this.calculateEmojiSuggestion();
                this.calculateMentionSuggestion();
            }
            this.setIsFocused(true);
        }}
```

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/a61089ad-fa1f-45df-b486-3b986f63dfc9


</details>

### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-07-10 16:05
@parasharrajat could you review these proposals?

**Comment by lschurr** [comment] 2023-07-14 20:26
Any update @parasharrajat?

**Comment by lschurr** [comment] 2023-07-17 15:23
Bump @parasharrajat

**Comment by b4s36t4** [comment] 2023-07-17 20:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Mention options are not displayed on focus if we cancel add attachment

### What is the root cause of that problem?

RCA for this issue relies on this block of code.
https://github.com/Expensify/App/blob/3e3a5238923df705ef4ab5d8cda039a1a1e3fcec/src/pages/home/report/ReportActionCompose.js#L1099C1-L1102

After setting this we're calling the file picker and in background the input is getting focused even then we're not getting solutions cause of the not updating the values.

### What changes do you think we should make in order to solve the problem?

We should handle the values gracefully only to show the suggestions after closing the file picker/AttachmentModal.

We have to refactor this code into a function which will update the values to false
https://github.com/Expensify/App/blob/3e3a5238923df705ef4ab5d8cda039a1a1e3fcec/src/pages/home/report/ReportActionCompose.js#L1104-L1106
like below

```jsx
openPicker({
    onPicked: (_file) => {
        this.shouldBlockMentionCalc = false;
        this.shouldBlockEmojiCalc = false;
        // Re-calculate the suggestions.
        this.calculateMentionSuggestion();
        this.calculateEmojiSuggestion();
        displayFileInModal(_file);
        },
    });
```

Even after adding this the problem won't be solved cause if we cancel the file picker it won't show suggestions to fix that we have to add an eventListener into the AttachMentPicker Component.

https://github.com/Expensify/App/blob/9004c3968fcde7f46a473db871b4dd6ab2f3effc/src/components/AttachmentPicker/index.js#L60
Here we call a new function maybe `addCancelListener` which listens for `cancel` event and update the function accordingly to re-enable the suggestions.

```jsx
const addCancelListener = () => {
        fileInput.current.addEventListener(
            'cancel',
            () => {
                onPicked.current(null);
            },
            {once: true},
        );
    };
```

Making these 3 changes should solve the issue.


## Result

[ib.webm](https://github.com/Expensify/App/assets/59088937/faec0315-a1bd-4464-946c-8c98b269f1f4)

### What alternative solutions did you explore? (Optional)
NA

**Comment by b4s36t4** [comment] 2023-07-19 12:58
@parasharrajat any update on the proposals?

**Comment by lschurr** [comment] 2023-07-21 16:28
Bump @parasharrajat

**Comment by lschurr** [comment] 2023-07-24 15:11
Bumping again. Are you able to review proposals @parasharrajat?

**Comment by lschurr** [comment] 2023-07-26 20:24
Hi @parasharrajat - are you able to finish up the review here?

**Comment by s-alves10** [comment] 2023-07-27 00:13
## Proposal
[Updated](https://github.com/Expensify/App/issues/22447#issuecomment-1627015611)

**Comment by b4s36t4** [comment] 2023-07-27 06:15
@parasharrajat here's the spec for cancel event -> https://html.spec.whatwg.org/#event-cancel
And for point 1 you said above. 
If you observe carefully this is how the flow is
Click + icon -> composer loose focus -> Click Add attachment -> Compose get's focus -> file selctor opens -> select a file -> Composer loose focus -> Attachment Modal open -> close/send the attachment -> composer get's focus.

Due to this composer having the focus and cancelling the file doesn't do anything because `onChange` event is not triggered from input if we don't select any file the values which we set before opening the picker are not updating until we do any state update. 

And the calculation functions are needed because of same RCA that composer getting focus when popup is opened while the composer calculations are off.

Also I don't seen any problem here because `onPicked` is callback which is called when we select a file, I think we can update the code like below

```jsx
if (_file === null) {
 this.shouldBlockMentionCalc = false;
 this.shouldBlockEmojiCalc = false;
  this.calculateEmojiSuggestion();
this.calculateMentionSuggestion();
 return;
}
```

here null will come in-case of clicking cancel on file picker, On close of attachment modal mentions are coming no need to do anything.

**Comment by b4s36t4** [comment] 2023-07-27 13:22
it won't show @parasharrajat , I think the issue is only with not showing mentions after input popup is closed. I tried the positivie flow means open a file and closed the modal it's showing the suggestions.

**Comment by b4s36t4** [comment] 2023-07-27 13:26
@parasharrajat here's the result, checked the both flows from my end.
https://github.com/Expensify/App/assets/59088937/37fe5901-e8fc-4fdc-88a7-3be323401009

**Comment by s-alves10** [comment] 2023-07-27 13:32
@parasharrajat 

Did you check my [proposal](https://github.com/Expensify/App/issues/22447#issuecomment-1627015611)?

**Comment by b4s36t4** [comment] 2023-07-27 17:57
@parasharrajat any update on the proposals? need to update the solution or any issue?

**Comment by lschurr** [comment] 2023-08-02 20:27
@parasharrajat do you agree we should put this on hold?

**Comment by lschurr** [comment] 2023-08-14 15:13
On hold.

**Comment by lschurr** [comment] 2023-09-01 14:33
On hold.

**Comment by lschurr** [comment] 2023-09-11 15:21
On hold.

**Comment by lschurr** [comment] 2023-09-21 00:17
On hold.

**Comment by lschurr** [comment] 2023-10-02 12:03
On hold.

**Comment by dhanashree-sawant** [comment] 2023-10-09 11:26
Hi @lschurr, @parasharrajat the mentioned issue is closed, should we again put it off hold? still reproducible

**Comment by lschurr** [comment] 2023-10-10 15:44
@parasharrajat should you double check? Should we take this one off hold?

**Comment by s-alves10** [comment] 2023-10-16 15:12
I can't reproduce this any more

**Comment by s-alves10** [comment] 2023-10-16 15:27
@b4s36t4 

Can you upload the video?

**Comment by b4s36t4** [comment] 2023-10-16 15:59
https://github.com/Expensify/App/assets/59088937/952fa0bd-2d96-49a6-b670-c9599d2eb76a

**Comment by s-alves10** [comment] 2023-10-18 12:48
## Proposal
[Updated](https://github.com/Expensify/App/issues/22447#issuecomment-1627015611)

**Comment by lschurr** [comment] 2023-10-18 15:19
@parasharrajat can you review?

**Comment by lschurr** [comment] 2023-10-23 15:19
Bump @parasharrajat

**Comment by b4s36t4** [comment] 2023-10-23 18:07
@parasharrajat been stuck with few other urgent issues, will update by tmrw.

**Comment by b4s36t4** [comment] 2023-10-24 17:38
@parasharrajat @lschurr @s-alves10 can anyone of you guys was able to repro this?! I Just tried and was not able.

> it's not only happening for mentions, but still reproducible with emoji suggestions.

**Comment by b4s36t4** [comment] 2023-10-24 17:39
If the mentions issues was not able to repro, we should change the title and op, I'm ready with my proposal to fix the new issue :)

**Comment by b4s36t4** [comment] 2023-10-25 09:22
@parasharrajat I'm saying the bug is not reproducible which is not showing mentions when clicking on cancel of file model. But happens with Emoji suggestions. 

I want to verify the bug once again weather it's reproducible or not.

**Comment by s-alves10** [comment] 2023-10-25 10:20
@parasharrajat 

[My proposal](https://github.com/Expensify/App/issues/22447#issuecomment-1627015611) works fine for emoji as well

**Comment by lschurr** [comment] 2023-10-27 16:38
@parasharrajat could you review?

**Comment by lschurr** [comment] 2023-10-30 15:14
Bump @parasharrajat

**Comment by b4s36t4** [comment] 2023-10-30 16:43
@parasharrajat I have updated my proposal, why it only happens with emojis and not with mentions and the solution to update it. Please review it, thanks :)

**Comment by b4s36t4** [comment] 2023-10-30 16:46
https://github.com/Expensify/App/issues/22447#issuecomment-1638850867

**Comment by s-alves10** [comment] 2023-10-30 17:41
@parasharrajat 

I think this issue is for web and desktop as described in [issue description](https://github.com/Expensify/App/issues/22447#issue-1794251954)

**Comment by mvtglobally** [comment] 2023-11-02 03:32
Issue not reproducible during KI retests. (First week)

**Comment by lschurr** [comment] 2023-11-02 04:57
@s-alves10 what's the latest here? It seems like the original issue is not reproducible. Should we close this GH?

**Comment by s-alves10** [comment] 2023-11-02 05:05
@lschurr 

The original issue is for mention suggestions, but it's working now. Now the issue is emoji suggestions. When cancelling attach, emoji suggestions are not displayed

**Comment by b4s36t4** [comment] 2023-11-02 13:41
@parasharrajat as per the required changes, we could just copy the existing `useEffect` that being used in `MentionSuggestions` into the `MentionEmojis` file. 

About the other issue where it's showing mentions for a bit, I need to debug it more or we can directly fix it when raising PR for the main issue.

**Comment by s-alves10** [comment] 2023-11-02 15:54
@parasharrajat 

Did you check my proposal? My proposal solves the issue you mentioned [here](https://github.com/Expensify/App/issues/22447#issuecomment-1790710349) as well

**Comment by lschurr** [comment] 2023-11-06 16:37
Any update here @parasharrajat?

**Comment by lschurr** [comment] 2023-11-09 16:47
Bump @parasharrajat

**Comment by lschurr** [comment] 2023-11-13 06:21
Bumped in Slack - https://expensify.slack.com/archives/C01GTK53T8Q/p1699856506999869

**Comment by lschurr** [comment] 2023-11-14 20:18
Posted for Call Stack - https://expensify.slack.com/archives/C03UK30EA1Z/p1699992980732989

**Comment by aldo-expensify** [comment] 2023-11-15 18:06
thanks for the thorough investigation @parasharrajat!

**Comment by dhanashree-sawant** [comment] 2023-11-16 06:10
Hi @aldo-expensify, @lschurr melvin bot has provided me with 50$ offer but the issue is raised before 30 August. Whenever you are available, can you modify that to 250?

**Comment by s-alves10** [comment] 2023-11-16 07:52
@parasharrajat 

PR is ready for review https://github.com/Expensify/App/pull/31421

**Comment by mvtglobally** [comment] 2023-11-18 04:34
Issue not reproducible during KI retests. (Third week)

**Comment by lschurr** [comment] 2023-12-14 16:06
Payment summary:

- Bug reporter: @dhanashree-sawant $250
- Contributor: @s-alves10 $1000
- Contributor+: @parasharrajat $1000

**Comment by lschurr** [comment] 2023-12-14 16:07
I'm getting an error in Upwork when I try modifying the offer to @dhanashree-sawant - Could you accept the offer and I'll add the correct amount?

**Comment by dhanashree-sawant** [comment] 2023-12-14 16:09
Sure, I have accepted the offer.

**Comment by lschurr** [comment] 2023-12-14 16:55
Great, payments are complete in Upwork. @parasharrajat you can request payment in Newdot.

**Closed** 2023-12-14 16:55 UTC
Labels: External, Engineering, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-04-03 03:05
$1,000 approved for @parasharrajat
