### ISSUE TITLE
[$250] [HOLD for payment 2024-08-14] Sage - "It's not here" error when clicking on the "Reconciliation account" link

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#46963] opened 2024-08-07 12:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.17-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/46400
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app
2. Log in with a new expensifail account
3. Click on FAB - New workspace
4. Enable "Accounting" and "Expensify Card" in the "More features" page.
5. Navigate to "Accounting"
6. Connect to Sage Intacct and upgrade the workspace to Control when asked
7. Wait for the sync to finish
8. Click on "Card reconciliation"
9. Enable "Continuous Reconciliation"
10. Click on the "Expensify Card settlement account" link
11. Click on the "Reconciliation account" link

## Expected Result:
I should be redirected to the page.
## Actual Result:
"It's not here" error when clicking on the "Reconciliation account" link.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/0c52eb89-7906-463d-bb91-f8bcd79f0d1c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0131ac7035a283d784</li>
        <li>Upwork Job ID: 1822986584397052060</li>
        <li>Last Price Increase: 2024-08-12</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-07 12:43
We think that this bug might be related to #wave-control

**Comment by trjExpensify** [comment] 2024-08-07 13:12
@mountiny @MariaHCD this is still in development, right?

**Comment by mountiny** [comment] 2024-08-07 13:29
@trjExpensify yeah this is still in development, although I dont think the page behind beta as far as I can see

The problem seems to be that the last link leads to quickbooks integration instead of sage.

**Comment by koko57** [comment] 2024-08-07 13:32
looks like dupe of https://github.com/Expensify/App/issues/46108

as you can see we have a proper URL in the browser bar - we are navigated to the correct page but as the reconciliation is not enabled AccessOrNotFoundWrapper renders NotFound page. The link that navigates to this page should not be visible though, it was made visible for testing purposes. It will all work when we have reconciliation setting connected to BE

**Comment by mountiny** [comment] 2024-08-07 13:36
> as you can see we have a proper URL in the browser bar - we are navigated to the correct page but as the reconciliation is not enabled AccessOrNotFoundWrapper renders NotFound page

@koko57 I think it navigated to quickbooks/account page which is not correct, is it? 

Either way, lets fix the deploy blocker by hiding the Card reconciliation button with the workspace feeds beta as we need to test this first

**Comment by trjExpensify** [comment] 2024-08-07 13:41
Yeah, I don't think the `Card reconciliation` button shouldn't be visible unless you've enabled the `Expensify Card` feature right? 🤔

**Comment by koko57** [comment] 2024-08-07 13:51
@trjExpensify but in the video and test steps Expensify Card is enabled - so I guess the betas were enabled here, but I will check ofc if the button is visible when Expensify Card is enabled

**Comment by trjExpensify** [comment] 2024-08-07 13:58
Yeah, I tested it on a random gmail account not on the `workspaceFeeds` beta. We still show the `Card reconciliation` tab in the accounting integration settings.. 

https://github.com/user-attachments/assets/e0f547a6-54f6-4455-ab21-7ee0c2ae6aed

**Comment by mountiny** [comment] 2024-08-07 14:16
> We still show the Card reconciliation tab in the accounting integration settings..

Yep there is no beta check for the button right now, we need to add that to resolve this blocker

**Comment by joekaufmanexpensify** [comment] 2024-08-07 14:24
Seems like we're well on our way to fixing this, but LMK if there is anything I can help with!

**Comment by koko57** [comment] 2024-08-07 15:17
PR ready for review: https://github.com/Expensify/App/pull/46978

**Comment by mountiny** [comment] 2024-08-09 09:02
$250 to @allgandalf for a quick help

**Comment by joekaufmanexpensify** [comment] 2024-08-12 13:20
All good, corrected

**Comment by joekaufmanexpensify** [comment] 2024-08-12 13:24
Ah, yeah fair point. This one is still in active development, so agree we prob don't need to add an ad-hoc test.

**Comment by joekaufmanexpensify** [comment] 2024-08-12 13:25
@allgandalf offer sent for $250!

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:52
@allgandalf $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:53
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-08-14 12:53
All set here, thanks everyone!

**Closed by joekaufmanexpensify** 2024-08-14 12:53 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
