### ISSUE TITLE
Workspace - From category GL code page, tapping back button directs to `Hhm not here` page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49048] opened 2024-09-12 09:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap fab -- new workspace
3. Tap categories
4. Tap on a category
5. Tap GL code
6. Tap app back button

## Expected Result:
From GL code page, tapping back button must not direct to hhm not here page.

## Actual Result:
From category GL code page, tapping back button directs to hhm not here page.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/74987dc5-3886-410c-9daf-34f700d3500c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by nkdengineer** [comment] 2024-09-12 09:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
From category GL code page, tapping back button directs to hhm not here page.

### What is the root cause of that problem?

We have `backTo = WORKSPACE_CATEGORY_GL_CODE` and will navigate when handle press button back [here](https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L61-L65) and we will navigate to `WORKSPACE_CATEGORY_GL_CODE` => page not found


https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L61-L65

### What changes do you think we should make in order to solve the problem?


Add `isControlPolicy(policy)` to this `condition`(https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L122-L125)

```
        if (backTo && isControlPolicy(policy)) {
            Navigation.goBack(ROUTES.SETTINGS_CATEGORIES_ROOT.getRoute(policyID, backTo));
            return;
        }
```

https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L61-L65

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-09-12 09:49
[updated proposal](https://github.com/Expensify/App/issues/49048#issuecomment-2345755757)

**Comment by ChavdaSachin** [comment] 2024-09-12 10:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- From GL code page, tapping back button must not direct to hmm not here page.

### What is the root cause of that problem?
- When policy is not `controlPolicy` we  redirect app to `workspaceUpgrade` page 
https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L195-L201
- here we are passing wrong fallback route
https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L200

### What changes do you think we should make in order to solve the problem?
- change fallback route
```js
ROUTES.WORKSPACE_CATEGORY_SETTINGS.getRoute(policyID, policyCategory.name),
```
https://github.com/Expensify/App/blob/57e1313096e1bbc969592bb33c55fe9b4eedf6d6/src/pages/workspace/categories/CategorySettingsPage.tsx#L200
- so app will navigate to category page when clicking back button from upgrade page.
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

<!---
ATTN: Contributor+

You are the first line of defense in making sure every proposal has a clear and easily understood problem with a "root cause". Do not approve any proposals that lack a satisfying explanation to the first two prompts. It is CRITICALLY important that we understand the root cause at a minimum even if the solution doesn't directly address it. When we avoid this step, we can end up solving the wrong problems entirely or just writing hacks and workarounds.

Instructions for how to review a proposal:

**Comment by MariaHCD** [comment] 2024-09-12 13:00
I think this will be fixed in this PR: https://github.com/Expensify/App/pull/49076

**Comment by MariaHCD** [comment] 2024-09-12 13:04
Nice, thanks for confirming, @rayane-djouah! 

(I was just about to ask in the Slack thread but you were faster! 🚀 )

**Comment by rlinoz** [comment] 2024-09-12 16:13
This is fixed on staging

**Comment by luacmartins** [comment] 2024-09-12 16:13
No payments due since this was a regression. Closing.

**Closed by luacmartins** 2024-09-12 16:13 UTC
Labels: Reviewing, Engineering, Hourly, Bug
