### ISSUE TITLE
[$250] [Bug] - Second message disappear when typing second message quickly after sending 1st one reported by @puneetlath.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11490] opened 2022-10-01 00:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. send a message
2. immediately start typing another
3. after a second, everything I’m typing goes away (notice how the I disappears in the second message).  
If you're having difficulties reproducing, try other chats, specifically ones that have a shit-ton of messages. I (@mallenexpensify ) can replicate in Version 1.2.12-0 by attempting a couple times in different chats, feel free to test me with too mallen@expensify.com.   

## Expected Result:
No disappearing of the message

## Actual Result:
after a second, everything I’m typing goes away (notice how the I disappears in the second message)

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Desktop App

**Version Number:** Version 1.2.12-0
**Reproducible in staging?:** yes
**Reproducible in production?:** yes
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @puneetlath  
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664559360112699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

https://user-images.githubusercontent.com/43996225/193375849-020b480a-e22b-44f6-a64d-c818d1b04030.mp4
https://user-images.githubusercontent.com/43996225/193375850-4b10d3f7-94d1-4235-bff8-d37687a9f7bf.mov

**Comment by Puneet-here** [comment] 2022-10-01 05:10
@kavimuru, a lil misunderstanding here. It's reported by @puneetlath.

**Comment by tienifr** [comment] 2022-10-07 09:08
# Proposal

## Problem
Originally, reportID is string.
When we add comment or add attachment, the result is returned from API updated the reportID as number.

That make `this.props.report.reportID === prevProps.report.reportID` is false and then trigger function `this.updateComment(this.props.comment);`. At that time, `this.props.comment` is empty as default
=> text typed in compose box disappears

https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportActionCompose.js#L182-L187

## Solution

We'll use this.props.reportID instead of this.props.report.reportID because reportID is converted to string  when we pass to `ReportActionCompose`

https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportFooter.js#L94-L100

In https://github.com/Expensify/App/blob/f710d78315fba055625278a1f7e20f9db6d08014/src/pages/home/report/ReportActionCompose.js#L182-L187

```diff
-        if (this.props.report.reportID === prevProps.report.reportID) {
+        if (this.props.reportID === prevProps.reportID) {

```


https://user-images.githubusercontent.com/113963320/194517161-0d7ef83f-a55a-4d82-884e-e2fbedaa8871.mov

**Comment by mananjadhav** [comment] 2022-10-07 09:53
I have some issues that were recently assigned and I won't get to this sooner. Can we please assign another C+?

@Expensify/contributor-plus

**Comment by trjExpensify** [comment] 2022-10-07 12:44
@youssef-lr - you're actively working on a PR for this, right? If so, can we assign this to you and replace it with an `Internal` label..

**Comment by youssef-lr** [comment] 2022-10-07 12:46
@trjExpensify PR ready!

**Comment by trjExpensify** [comment] 2022-10-07 12:50
Woop! Discussed [in thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1665146740022159?thread_ts=1665142548.340259&cid=C01GTK53T8Q), assigning to @youssef-lr and marking as `Internal`.

**Comment by youssef-lr** [comment] 2022-10-07 14:48
@trjExpensify server-side [fix](https://github.com/Expensify/Web-Expensify/pull/35072) deployed to staging and I can confirm I can longer reproduce this.

**Comment by mallenexpensify** [comment] 2022-10-08 00:15
Thanks for the quick fix @youssef-lr !!!

**Comment by youssef-lr** [comment] 2022-10-18 11:51
This has been fixed. Closing!

**Comment by mallenexpensify** [comment] 2022-10-18 17:15
hehe, it was an issue where Puneet, a contributor, was initially inc. as the reporter but Puneet, who works here, was the one who posted the bug.  Closing

**Comment by mallenexpensify** [comment] 2022-10-18 17:19
@youssef-lr this is an edge case issue where the `External` label was added then removed. While the job was `Help Wanted`, @tienifr submitted[ the proposal above](https://github.com/Expensify/App/issues/11490#issuecomment-1271327026).   Since they weren't hired they're technically not due compensation but, if you referenced their code when working on your fix, we should compensate them.  Did you?

**Comment by youssef-lr** [comment] 2022-10-18 17:22
@mallenexpensify this was fixed in Web-E. We didn't end up changing code in App.

**Comment by mallenexpensify** [comment] 2022-10-18 17:24
Thanks @youssef-lr !  Thanks @tienifr for submitting the proposal as well. closing... again.

**Closed by mallenexpensify** 2022-10-18 17:24 UTC
Labels: Reviewing, Engineering, Daily, Internal
