### ISSUE TITLE
[$500]  IOU - User is brought to main chat and duplicate error in report when paying same request twice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33822] opened 2024-01-01 18:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2 
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User A owes User B money
1. Log in as User A on two devices
2. On the first device, go to IOU report page and disconnect network
3. Pay the amount
4. On the second device, without disconnecting network, pay the request
5. On the first device, reconnect network
6. Click on the IOU preview

## Expected Result:
In Step 5, user will remain on the IOU report
In Step 6, the error message will not appear twice

## Actual Result:
In Step 5, user is redirected to the main chat after reconnecting network
In Step 6, the error message is duplicated -
"'Unexpected error, please try again later. An unexpected error occurred. Please try again.'

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c86e9141-4194-46b3-8118-226c9f2bd9f6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b20888f83f6a41ed</li>
        <li>Upwork Job ID: 1741889910953496576</li>
        <li>Last Price Increase: 2024-01-22</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 28121718</li>
<li>dukenv0307 | Contributor | 28121719</li>
</ul></li>
    </ul>
</details>

**Comment by aim-salam** [comment] 2024-01-02 03:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

IOU - User is brought to main chat and duplicate error in report when paying same request twice

### What is the root cause of that problem?

`failureData` array at line 2852 have pre-item

https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/libs/actions/IOU.js#L2852-L2862



### What changes do you think we should make in order to solve the problem?

Eliminate pre-item in `failureData` array

```js
    const failureData = [
     
    ];
```


### What alternative solutions did you explore? (Optional)

**Comment by jacobkim9881** [comment] 2024-01-07 17:37
To my endpoint, in step 5, a user(me) remains on the IOU report but the bug is reproducible on step 6.

**Comment by jacobkim9881** [comment] 2024-01-09 06:35
I wonder two errors should not be shown on report screen?

**Comment by jacobkim9881** [comment] 2024-01-09 22:38
So there are 2 errors. One is IOU error and the other unexpected error from backend. These could occur in each case. But it looks same.

**Comment by aim-salam** [comment] 2024-01-10 01:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

When the `first device` offline and try to pay, 
`Report preview action` try to load locally, but it's failure and this condition happen

https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/libs/actions/IOU.js#L2886-L2894

So, there is 2 errors in `failureData`

### What changes do you think we should make in order to solve the problem?

Show only default item on `failureData`

https://github.com/Expensify/App/blob/fe49e4f7fb9677a5834b53cb776f79fb20f893ce/src/components/DotIndicatorMessage.tsx#L73-L101

```diff
+       const message = uniqueMessages[0]
```

```diff
-             
+                    {isReceiptError(message) ? (
                        <PressableWithoutFeedback
                            accessibilityLabel={Localize.translateLocal('iou.error.saveFileMessage')}
-                         
                            accessibilityRole={CONST.ACCESSIBILITY_ROLE.LINK}
                            onPress={() => {
                                fileDownload(message.source, message.filename);
                            }}
                        >
                            <Text
-                             
                                style={styles.offlineFeedback.text}
                            >
                                <Text style={[StyleUtils.getDotIndicatorTextStyles(isErrorMessage)]}>{Localize.translateLocal('iou.error.receiptFailureMessage')}</Text>
                                <Text style={[StyleUtils.getDotIndicatorTextStyles(isErrorMessage), styles.link]}>{Localize.translateLocal('iou.error.saveFileMessage')}</Text>
                                <Text style={[StyleUtils.getDotIndicatorTextStyles(isErrorMessage)]}>{Localize.translateLocal('iou.error.loseFileMessage')}</Text>
                            </Text>
                        </PressableWithoutFeedback>
                    ) : (
                        <Text
                            // eslint-disable-next-line react/no-array-index-key
-
                            style={[StyleUtils.getDotIndicatorTextStyles(isErrorMessage), textStyles]}
                        >
                            {message}
                        </Text>
                    ),
+                  }
-                )}


```

### What alternative solutions did you explore? (Optional)

**Comment by jacobkim9881** [comment] 2024-01-10 07:21
I agree that single error shows from same reason. But as I know the other error occurs for unknown reason from backend. And IOU error only in IOU cases explain general issue. IOU error can't be distinguished from the unknown error for now.

**Comment by anmurali** [comment] 2024-01-12 18:13
@0xmiroslav bumping you for review of the above comments/ revised proposal.

**Comment by jacobkim9881** [comment] 2024-01-15 18:19
Showing one error by filtering could be a solution. As @dukenv0307 said, there are 2 errors. IOU error explaining looks more like general error but it is money request error. But what if there other errors occurred and it shows single error?

**Comment by jacobkim9881** [comment] 2024-01-15 18:21
From backend the unexpected error can be fixed somehow then there is no issue. But it is not a solution from FE.

**Comment by anmurali** [comment] 2024-01-16 20:17
@0xmiroslav - I cannot reproduce 
>In Step 5, user is redirected to the main chat after reconnecting network

So let's ignore that for the time being

>In Step 6, the error message is duplicated -
>"'Unexpected error, please try again later. An unexpected error occurred. Please try again.'

I also do not get this error message. But instead, I get two messages when I reconnect network
<img width="332" alt="image" src="https://github.com/Expensify/App/assets/14225673/045d1506-d594-4318-81e4-21ed7e38a139">

The second message is wrong. That's the one we need to troubleshoot. If this is a backend issue, let me know.

**Comment by mallenexpensify** [comment] 2024-01-24 03:36
@akinwale reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by akinwale** [comment] 2024-01-24 06:34
Taking over as C+ here.

![Screenshot 2024-01-24 at 07 34 36](https://github.com/Expensify/App/assets/4160319/4ff3a171-965f-46e8-91df-b8c0bad04299)

@anmurali I was able to reproduce, but I got the repeated error messages as in the OP. It looks like the two messages in your test are different however, so that could probably be treated as a separate unrelated issue. What do you think?

**Comment by akinwale** [comment] 2024-01-24 06:44
It makes sense to display the latest error message in this instance if there happen to be multiple, so we can move forward with @dukenv0307's [proposal](https://github.com/Expensify/App/issues/33822#issuecomment-1873757700).

🎀👀🎀 C+ reviewed.

**Comment by rlinoz** [comment] 2024-01-24 19:26
I really can't reproduce this issue, neither in staging or dev...

Am I missing something @akinwale?

https://github.com/Expensify/App/assets/5201282/8118fb79-2d37-410b-99f6-f701d2f630ca

**Comment by akinwale** [comment] 2024-01-24 19:36
> I really can't reproduce this issue, neither in staging or dev...
> 
> Am I missing something @akinwale?
> 

After forcing offline, settle the IOU (pay elsewhere) on the session that was forced offline, and then settle on the other online session before putting the offline session back online.

**Comment by rlinoz** [comment] 2024-01-24 19:43
Oh I missed the part of needing 2 devices, thanks

**Comment by rlinoz** [comment] 2024-01-25 15:48
Since this looks like a problem of how we are displaying error messages and not really about requiring 2 devices I think this one is worth fixing.

I am assigning @dukenv0307 then, thanks!

**Comment by akinwale** [comment] 2024-02-12 11:09
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Login to Expensify as user A on two devices
2. Send a money request from user B to user A
3. On the first device, go offline
4. Settle the request from user B on the offline device
5. On the second device, settle the request from user B without going offline
6. On the first device, go online
7. Verify that the message is not duplicated when the error message appears on the request.

Do we agree 👍 or 👎?

**Comment by rlinoz** [comment] 2024-02-15 14:14
Honestly I think this is not an impactful bug, and needing "two" devices with the same account makes it tricky to test, so I think we can skip adding regression tests.

**Comment by anmurali** [comment] 2024-02-16 15:48
Works for me. @akinwale and @dukenv0307 have been paid.

**Closed by anmurali** 2024-02-16 15:48 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
