### ISSUE TITLE
[$1000] When switching chats in the app, the previous chat is briefly shown before the current selected chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14390] opened 2023-01-18 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the app
2. Open any chat
3. Switch to another chat

## Expected Result:
We should not see the previous chat in the header

## Actual Result:
The previous chat is briefly shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native

**Version Number:** 1.2.55-0
**Reproducible in staging?:** Y (1.2.54-2)
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213253710-e6209530-2540-442e-83f4-7b2d64e305bd.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @marcaaron 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673994602292949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014dc46ae9b9cf434f</li>
        <li>Upwork Job ID: 1615832741511102464</li>
        <li>Last Price Increase: 2023-01-18</li>
    </ul>
</details>

**Comment by priyeshshah11** [comment] 2023-01-18 22:10
The video doesn't clearly show the bug, I think the only issue here is the avatar changing that's due to it taking time to load.  @jliexpensify Can you please confirm whether that's the issue here?

**Comment by jliexpensify** [comment] 2023-01-18 23:23
The issue was reported by multiple people [as having the previous chat show in the header when selecting a new chat](https://expensify.slack.com/archives/C049HHMV9SM/p1673994602292949).

However, after downloading the newest update, I'm not seeing this behaviour anymore:

https://user-images.githubusercontent.com/30815269/213316512-8af80534-31aa-4a29-9fbf-a0378b596935.MP4

@kavimuru can you check this?

**Comment by marcaaron** [comment] 2023-01-19 01:31
Reproducible this morning for me on iOS but not anymore. Either it was fixed or could be related to some API weirdness.

**Comment by jliexpensify** [comment] 2023-01-19 02:00
Thanks for confirming Marc! Based off what I'm also seeing, I think it's probably now fixed by the latest version and this GH can be closed.

@kavimuru please re-open if you've downloaded the latest version and am still seeing this issue.

**Closed by jliexpensify** 2023-01-19 02:00 UTC
Labels: External, Daily, Help Wanted, Bug
