### ISSUE TITLE
[$500] [HOLD for payment 2023-12-20]  IOU - An employee cannot cancel a selected category when creating an IOU

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32872] opened 2023-12-11 22:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**  Applause - Internal Team
**Slack conversation:**

## Action Performed:
Preconditions:
In OldDot under admin, create a group policy, enable categories and add multiple categories, add an employee to the policy.
1. Open New Expensify app
2. Log in to the employee's account
3. Tap on the green plus button (FAB)
4. Select Request money
5. Select any currency and amount
6. Click next
7. Choose a group policy room
8. Click on "Show more"
9. In the category section, select any category
10. Navigate to the categories section again and click on the selected category marked with a green checkmark

## Expected Result:
Employee must be able to override the selected category when creating an IOU

## Actual Result:
An employee cannot cancel a selected category when creating an IOU

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e2cfcdfd-752c-4486-bc47-8d13fb518950

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a8ca6c08fbc8290c</li>
        <li>Upwork Job ID: 1743060606199652352</li>
        <li>Last Price Increase: 2024-01-05</li>
    </ul>
</details>

**Comment by luacmartins** [comment] 2023-12-12 00:37
Proposal looks good. Gonna assign @mkhutornyi to the issue

**Comment by shubham1206agra** [comment] 2023-12-12 04:42
Please assign me here as C+

**Comment by Julesssss** [comment] 2023-12-12 10:34
Cherry-picked to staging

**Comment by shubham1206agra** [comment] 2023-12-20 14:53
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28618
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28618/files#r1432817280
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as we have caught this in deploy testing
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@luacmartins] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by deetergp** [comment] 2023-12-27 07:41
Did this get paid out?

**Comment by shubham1206agra** [comment] 2023-12-27 08:54
Nope

**Comment by deetergp** [comment] 2024-01-03 06:19
@mallenexpensify I added you because I wasn't sure which label kicks off the BZ auto assigner 😅

**Comment by mallenexpensify** [comment] 2024-01-05 00:28
@shubham1206agra @mkhutornyi can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01a8ca6c08fbc8290c

**Comment by shubham1206agra** [comment] 2024-01-05 04:31
Done

**Comment by luacmartins** [comment] 2024-01-08 16:25
Just pending payment

**Comment by mallenexpensify** [comment] 2024-01-09 01:33
Contributor: @mkhutornyi paid $500 via Upwork
Contributor+: @shubham1206agra paid $500 via Upwork.  

> If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

@shubham1206agra is there any reason we **wouldn't** want to create a regression test for this?

**Comment by shubham1206agra** [comment] 2024-01-09 03:14
@mallenexpensify This is a deploy blocker and the applause already has this test in their flow already

**Closed** 2024-01-10 01:20 UTC
Labels: External, Engineering, Daily, Help Wanted, Awaiting Payment, Bug
