### ISSUE TITLE
[HOLD for payment 2023-07-28] [$1000] No text limit in add new contact method textfield

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22201] opened 2023-07-04 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings -> Click on profile
2. Click Contact method -> Add new Contact method
3. Add long text in Email/phone textfield

## Expected Result: 
Add new contact method textfield should have some char limit
## Actual Result: 
No char limit in Add new contact method textfield

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.36-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8a9a618b-d1f9-4bf0-a690-28e17edabb54

https://github.com/Expensify/App/assets/43996225/302b0dc2-bd86-4a40-bd44-4d901d81b303

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688394545525479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01925c45eb3e97f2e8</li>
        <li>Upwork Job ID: 1678677725763600384</li>
        <li>Last Price Increase: 2023-07-11</li>
    </ul>
</details>

**Comment by jeet-dhandha** [comment] 2023-07-04 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- No character limit in Contact Method Input field.

### What is the root cause of that problem?
- The limit is not handled in the first place. Many inputs will need to be updated.

### What changes do you think we should make in order to solve the problem?
- We will need to update all the login/contact input fields to handle the limit. Like one from login form, close account page, etc.
- Globally email limit is set to 320 max. 

```
In addition to restrictions on syntax, there is a length limit on email addresses. That limit is a maximum of 64 characters (octets) in the « local part » (before the « @ ») and a maximum of 255 characters (octets) in the domain part (after the « @ ») for a total length of 320 characters. Systems that handle email should be prepared to process addresses which are that long, even though they are rarely encountered
```
(ref: [what-is-the-maximum-size-of-an-mail-address](https://www.mindbaz.com/en/email-deliverability/what-is-the-maximum-size-of-an-mail-address/#%253A~%253Atext%253DThe%2520domain%2520address%253A%2520255%2520characters%2526text%253DThat%2527s%2520it%252C%2520you%2520now%2520know%252Clength%2520of%2520an%2520email%2520address%2521))

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by laurenreidexpensify** [comment] 2023-07-05 07:13
@dhairyasenjaliya is this being covered in #18647 ?

**Comment by laurenreidexpensify** [comment] 2023-07-10 14:59
@dhairyasenjaliya bump^^

**Comment by therowf** [comment] 2023-07-11 15:19
### Please re-state the problem that we are trying to solve in this issue.

- Text limit for "add new contact method"

### What is the root cause of that problem?

- There is no logic set to check input limit in valid function.

### What changes do you think we should make in order to solve the problem?

1. The "CONST.js" : We have to add a constant with NEW_CONTACT_MAX_LENGTH.

2. The "NewContactMethodPage.js" : After line 108 we can specify logic to check before and after @ part for the email or phone length and bind it to NEW_CONTACT_MAX_LENGTH that we specified earlier.

3. The "language/en.js" file: On line 455 we could add a new error message "textLimitExceeded" to show the limit exceeded alert to user.

**Comment by mananjadhav** [comment] 2023-07-11 16:49
Looks like a simple fix, and all the proposals mention the similar solution. I think @samh-nl's proposal [here](https://github.com/Expensify/App/issues/22201#issuecomment-1620547228) looks good.

🎀 👀 🎀  C+ Reviewed.

**Comment by MonilBhavsar** [comment] 2023-07-12 12:04
Looks good. Couple of clarifying questions - 
1. What will be the value of maxLength we'll be using? Is there any where else in the app, we're using for logins?
2. Looks like we're maxing maxLength prop. Are we also going to double check maxLength in validate function?

**Comment by mananjadhav** [comment] 2023-07-12 16:48
@MonilBhavsar 

1. I think `maxLength` should be 254 as that's the valid email address max length.
2. Yes it should be both max length and validate method both.

**Comment by MonilBhavsar** [comment] 2023-07-13 09:46
> @MonilBhavsar
> 
> 1. I think `maxLength` should be 254 as that's the valid email address max length.
> 2. Yes it should be both max length and validate method both.

Sounds good 👍 
Looks like we're not using maxLenght for login input anywhere. Not in Loginform.js, or anywhere else, correct?
I think while we're here, we should fix for all forms

**Comment by MonilBhavsar** [comment] 2023-07-13 09:51
> For consistency, this change could be applied to other locations where the login/contact information is supplied.

@samh-nl could you please help to list other locations where you plan to validate login

**Comment by MonilBhavsar** [comment] 2023-07-17 08:46
Awaiting reply or complete proposal here

**Comment by mananjadhav** [comment] 2023-07-17 19:29
Thanks for the list @samh-nl. I think we should only restrict to Login and Contact for the time being. what do you think @MonilBhavsar ?

**Comment by MonilBhavsar** [comment] 2023-07-18 10:31
Thanks for listing them!
Yes, I agree that for now, we should only limit in LoginForm and ContactForm.

**Comment by MonilBhavsar** [comment] 2023-07-18 10:32
> Is there an added benefit to implementing both a maxLength and adding it to validation? The validation error would presumably never be triggered.

Hmm, not really

**Comment by MonilBhavsar** [comment] 2023-07-18 10:37
Yes, we can keep one check. No worries

**Comment by DinalJivani** [comment] 2023-07-18 10:42
Contributor details
Your Expensify account email: koodosdev@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a356bfeda21bbb61

**Comment by DinalJivani** [comment] 2023-07-18 10:48
@laurenreidexpensify 
Applied on [Upwork job](https://www.upwork.com/jobs/~01925c45eb3e97f2e8).

**Comment by MonilBhavsar** [comment] 2023-07-19 07:41
PR is merged!
Thanks all for the quick work! 🚀

**Comment by laurenreidexpensify** [comment] 2023-07-28 13:46
Payment Summary -  

-  External issue reporter @DinalJivani - $250 paid in Upwork
-  Contributor that fixed the issue - @samh-nl - $1000 + $500 3day bonus paid in Upwork
-  Contributor+ that helped on the issue and/or PR - @mananjadhav $1000 + $500 3day bonus to be paid in newdot

**Comment by laurenreidexpensify** [comment] 2023-07-28 13:47
@mananjadhav bump on regression steps above, thanks!

**Comment by mananjadhav** [comment] 2023-07-28 13:48
@laurenreidexpensify Thanks for the bump. The steps from the Tests steps of the PR are good for the regression test. I think we should add regression steps for this one as we're setting a max length and we should be aware when we remove/update this.

I wouldn't treat this as a bug, as it's not added since the beginning. This could be like a small feature request, and hence no other action needed here.

**Comment by mananjadhav** [comment] 2023-07-30 20:21
@laurenreidexpensify Are we done with the payout here? If yes we can close this one out.

**Comment by laurenreidexpensify** [comment] 2023-07-31 09:59
@mananjadhav thanks - I've added the QA test request so we can close now

**Comment by DinalJivani** [comment] 2023-07-31 10:05
I have received the offer but [payment is pending](https://www.upwork.com/nx/wm/workroom/34348295/overview)
@laurenreidexpensify

**Comment by DinalJivani** [comment] 2023-08-07 21:43
^^bump @laurenreidexpensify

**Comment by DinalJivani** [comment] 2023-08-19 12:15
^^bump @laurenreidexpensify

**Comment by DinalJivani** [comment] 2023-08-22 11:45
^^bump @laurenreidexpensify

**Comment by laurenreidexpensify** [comment] 2023-08-23 07:57
Reviewed and issued payment to Dinal

**Closed by laurenreidexpensify** 2023-08-23 07:57 UTC
Labels: External, Daily, Awaiting Payment, Bug
