### ISSUE TITLE
[HOLD for payment 2023-10-13] [$500] Chat - Strikethrough link isn't parsed correctly on link with URL that contains tilde

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27329] opened 2023-09-13 11:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat
2. Send this message "~ [Example Link]([https://example.com?example= ~ ex)~ ](https://example.com/?example= ~ ex) ~)"
3. Examine how the text parsed

## Expected Result:
The tilde should be parsed as styling character, and the strikethrough should be applied (like underscore and italicized link that behave like that, so this could be categorized as inconsistency issue as well)

## Actual Result:
The tilde isn't parsed and the message isn't styled as expected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.69-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/1b84a61a-9963-4e1e-b97e-12017f267e74

https://github.com/Expensify/App/assets/115492554/ffeb0549-bc4f-4718-b4b6-01406ca007d4

**Expensify/Expensify Issue URL:**

**Issue reported by:** @kerupuksambel

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694320083877809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0193c33b549a6d01ac</li>
        <li>Upwork Job ID: 1701921122476535808</li>
        <li>Last Price Increase: 2023-09-20</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 26877283</li>
<li>kerupuksambel | Reporter | 26877284</li>
</ul></li>
    </ul>
</details>

**Comment by sahilbhosale63** [comment] 2023-09-13 14:59
Hi @izarutskaya 
I just now saw this issue in Upwork job posting and I wanted to contribute to this issue. I downloaded the source and ran the web app on local but I'm facing the "You appear to be offline" issue frequently while I am using the app. Due this I'm not able to debug the issue correctly. I have stable internet but still I'm facing this issue. Can you please guide me here?

**Comment by astrohunter62** [comment] 2023-09-15 03:34
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The strikethrough link does not parse correctly when the URL contains a tilde.
### What is the root cause of that problem?
In expensify-common library, the link with URL that contains tilde is not handled correctly.
### What changes do you think we should make in order to solve the problem?
If it is possible to modify the module, add a regular expression to the `modifyTextForUrlLinks` function in `node_modules/expensify-common/lib/ExpensiMark.js``.
For example:
```
        ...
        return replacedText.replace(/~(.*?)~|~/g, '<del>$1</del>');
       ...
```
Alternatively, we can add a regular expression to `getParsedComment()` in `src/lib/ReportUtils.js`.
For example:
```
function applyStrikethrough(html) {
    return html.replace(/~(.*?)~|~/g, '<del>$1</del>');
}
function getParsedComment(text) {
    const parser = new ExpensiMark();
    return text.length < CONST.MAX_MARKUP_LENGTH ? applyStrikethrough(parser.replace(text)) : _.escape(text);
}
```
Result:

https://github.com/Expensify/App/assets/136574831/93aaa175-51c9-4eb0-ae43-3b9ea937e7bd

**Comment by Antasel** [comment] 2023-09-15 07:37
# Proposal
### Please re-state the problem that we are trying to solve in this issue
The current strikethrough markdown is not applied if url contains tilde.
This kind of issue also happens with bold markdown.

### What is the root cause of that problem?
Current regex patterns of strikethrough and bold rule are not covering this issue case.

### What changes do you think we should make in order to solve the problem?
We need to fix regex pattern on [strikethrough](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L213), also [bold](https://github.com/Expensify/expensify-common/blob/main/lib/ExpensiMark.js#L208) rules.

As following:
```
            {
                name: 'bold',
                regex: /\B\*((?![\s\*])[\s\S]*?[^\s\*])\*\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
                replacement: (match, g1) => (g1.includes('<pre>') || this.containsNonPairTag(g1) ? match : `<strong>${g1}</strong>`),
            },
            {
                name: 'strikethrough',
                regex: /\B~((?![\s~])[\s\S]*?[^\s~])~\B(?![^<]*(<\/pre>|<\/code>|<\/a>))/g,
                replacement: (match, g1) => (this.containsNonPairTag(g1) ? match : `<del>${g1}</del>`),
            },
```

and we can add test cases.
```
testString = '~test.com/test=~123~';
resultString = '<del><a href=\"https://test.com/test=~123\" target=\"_blank\" rel=\"noreferrer noopener\">test.com/test=~123</a></del>'

testString = '*test.com/test=*123*';
resultString = '<strong><a href=\"https://test.com/test=*123\" target=\"_blank\" rel=\"noreferrer noopener\">test.com/test=*123</a></strong>'
```

The solution does not make other test cases failed.

**Comment by greg-schroeder** [comment] 2023-09-18 10:57
awaiting proposal review

**Comment by robertKozik** [comment] 2023-09-20 16:07
Sorry for keeping you waiting. Going to review the proposals now

**Comment by robertKozik** [comment] 2023-09-21 12:30
Hi all @Antasel @astrohunter62 @ZhenjaHorbach! Thank you all for your proposals. Yes, we can do the PR to `expensify-common` I believe. All of you pointed out correct root cause and propose changing the regex in `expensify-common`. That's why I believe we should select the first contributor to propose this - @ZhenjaHorbach.

Selected Proposals: https://github.com/Expensify/App/issues/27329#issuecomment-1718210386
Contributor: @ZhenjaHorbach

**Comment by greg-schroeder** [comment] 2023-09-25 07:33
@robertKozik can you make sure to use the proper formatting to assign an engineer?

**Comment by greg-schroeder** [comment] 2023-09-25 07:34
🎀 👀 🎀 C+ reviewed!

**Comment by robertKozik** [comment] 2023-09-25 09:25
Ohhh sorry, I've missed that 🙇🏼 

🎀 👀 🎀 C+ reviewed

**Comment by greg-schroeder** [comment] 2023-09-29 06:07
[PR](https://github.com/Expensify/expensify-common/pull/581) is on the review stage

**Comment by Beamanator** [comment] 2023-10-02 10:02
PR merged today!

**Comment by Beamanator** [comment] 2023-10-02 13:31
Not a stupid question! But yes, you can see in `package.json` of this project that our `expensify-common` package points to the latest commit in the `expensify-common` repo, and since we just merged an update there, you'll have to also update package.json & i believe package-lock.json as well - you can see recent PRs that update that line to see examples 👍

**Comment by greg-schroeder** [comment] 2023-10-12 17:52
This is ready for payment tomorrow unless any regressions pop up

**Comment by robertKozik** [comment] 2023-10-12 20:15
> * [X]  [@robertKozik] The PR that introduced the bug has been identified. Link to the PR: It's not a regression from the PR, it's new edge-case which was not covered yet
> * [X]  [@robertKozik] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
> * [X]  [@robertKozik] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
> * [X]  [@robertKozik] Determine if we should create a regression test for this bug. I think we don't need it, we have new unit tests for such a cases inside `expensify-common` repo
> * [X]  [@robertKozik] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A

**Comment by Beamanator** [comment] 2023-10-16 11:54
I believe this is ready for payment 👍

**Closed** 2023-10-16 14:37 UTC
Labels: External, Daily, Awaiting Payment, Bug
