### ISSUE TITLE
Distance tax - Tax rate and tax reclaimable on rows are not grayed out when edited offline

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43174] opened 2024-06-06 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-1
**Reproducible in staging?:** y
**Reproducible in production?:** no new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Tax is enabled.
- Distance rates are enabled.
- Track tax in DIstance rates is enabled.

1. Go to staging.new.expensify.com
2. Go to workspace settings.
3. Go to Distance rates.
4. Go offline.
5. Tap on any rate.
6. Edit "Tax rate" and "Tax reclaimable on".

## Expected Result:
"Tax rate" and "Tax reclaimable on" will gray out when edited offline.

## Actual Result:
"Tax rate" and "Tax reclaimable on" are not grayed out when edited offline.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
https://github.com/Expensify/App/assets/38435837/51fb23a0-9e50-4259-af53-063547110f0a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment] 2024-06-06 14:21
@sakluger FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-06 14:21
We think that this bug might be related to #wave-collect - Release 1

**Comment by MonilBhavsar** [comment] 2024-06-06 14:59
cc @nkdengineer @eVoloshchak

**Comment by MonilBhavsar** [comment] 2024-06-06 15:00
This is offline bug and related to UI, not blocking the workflow. So we can demote it from blocker. But let's fix it as a regression

**Comment by carlosmiceli** [comment] 2024-06-06 15:02
@MonilBhavsar What do you mean by fixing as a regression? First time hearing about it 😅

**Comment by MonilBhavsar** [comment] 2024-06-06 15:06
Since the regression is coming from https://github.com/Expensify/App/pull/42141. We can have PR authors to fix the bug
 https://stackoverflowteams.com/c/expensify/questions/8513

**Comment by carlosmiceli** [comment] 2024-06-06 15:15
Ah, got it, thanks @MonilBhavsar !

**Comment by carlosmiceli** [comment] 2024-06-06 15:24
@MonilBhavsar should I assign this also to the original PR author? Or would that trigger another payment that doesn't correspond here?

**Comment by MonilBhavsar** [comment] 2024-06-06 15:42
Yes, you will be able to assign contributor and c+ once they comment here

**Comment by nkdengineer** [comment] 2024-06-07 03:00
I'll raise PR soon to fix this regression

**Comment by sakluger** [comment] 2024-06-18 18:01
Hey @nkdengineer - what's the status on a fix for this regression?

**Comment by nkdengineer** [comment] 2024-06-18 18:06
The PR is merged and deployed to production.

**Comment by carlosmiceli** [comment] 2024-06-19 23:33
@luacmartins Can we close this?

**Comment by luacmartins** [comment] 2024-06-19 23:51
Yes, we'll process payment as part of the original issue and https://github.com/Expensify/App/issues/43241

**Closed by luacmartins** 2024-06-19 23:51 UTC
Labels: Engineering, Weekly, Bug
