### ISSUE TITLE
[$500] Redundant message appears when submitting the reports

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33851] opened 2024-01-02 20:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.20-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1704055337012369

## Action Performed:
1. Create control workspace in OD as account A
2. Invite account B to the workspace as a member
3. Submit a report as account B in the workspace created in step 1 in OD
4. Check the expense report in ND as account B

## Expected Result:
Only one message should appear

## Actual Result:
Redundant message appears

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (6)](https://github.com/Expensify/App/assets/38435837/679cfce9-707d-4bd8-b7cf-07f15491df89)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fadea3ed5f3bcce4</li>
        <li>Upwork Job ID: 1742279719217627136</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-02 20:22
Dupe of https://github.com/Expensify/App/issues/33445

**Comment by garrettmknight** [comment] 2024-01-05 18:41
Agreed

**Closed by garrettmknight** 2024-01-05 18:41 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
