### ISSUE TITLE
[$1000] Mention suggestion doesn’t display when enter @/// and move the cursor right after the @

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19027] opened 2023-05-16 15:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open app
2. enter @///
3. move the cursor right after the
4. Observe that mention suggestion doesn’t display
5. enter :smile///
6. move the cursor right after the :smile
7. Observe that emoji suggestion still display

## Expected Result:
mention suggestion should display

## Actual Result:
 mention suggestion doesn’t display

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.14-9
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/677788c1-31c8-4b62-9c5d-20297a79e45a

https://github.com/Expensify/App/assets/43996225/12369565-ed70-4435-993b-c586169e53d0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684140024205999

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019af0d7bfd0f1be7b</li>
        <li>Upwork Job ID: 1658653892424806400</li>
        <li>Last Price Increase: 2023-05-17</li>
    </ul>
</details>

**Comment by sakluger** [comment] 2023-05-17 02:01
I reproduce this bug, and after discussion in Slack, we decided this is worth fixing for consistent behavior.

**Comment by dukenv0307** [comment] 2023-05-17 02:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
We are getting `commentAfterAtSignWithMentionRemoved` variable by using this regex
https://github.com/Expensify/App/blob/811c0f36fba4953af008e6643349d95c949627e4/src/CONST.js#L1086

We only break by new line, white space and emoji (emoji is added in the regex by [this issue](https://github.com/Expensify/App/issues/18867)) 

So that when click @/// , no matter where the selection is, we still use /// to find the matched suggestion list
### What changes do you think we should make in order to solve the problem?
1. We can update the regex to match some special characters
In this issue, we can update regex to: `^@[^\n\r\/]*?(?=$|\s|\/)` to allow break by `/`
The similar bug also happens with other characters like `?"{}()[]&^%$#<>!*`  If we want to fix it, we also update regex like above 
2. We can update all logic to get mentioned selection (based on sign index and selection instead of last word)
Could you see this thread for more detail?
https://expensify.slack.com/archives/C049HHMV9SM/p1684257493085169?thread_ts=1683827263.524849&cid=C049HHMV9SM

### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment] 2023-05-17 18:37
I think we can resolve this in a single PR here: https://github.com/Expensify/App/issues/18867#issuecomment-1551863070.

We can pay out for the report, but let's not update the regex twice in two separate PR's if we don't need to.

**Comment by dukenv0307** [comment] 2023-05-17 18:45
@twisterdotcom Could you check [this thread](https://expensify.slack.com/archives/C049HHMV9SM/p1684257493085169?thread_ts=1683827263.524849&cid=C049HHMV9SM) first?

**Comment by sakluger** [comment] 2023-05-18 19:01
Everything can be resolved in that same PR, but according to [this comment](https://github.com/Expensify/App/issues/18867#issuecomment-1551863070), the regex will need to be updated to fix this one as well, so we should still pay for this report. I'll leave this issue open to track that.

**Comment by sakluger** [comment] 2023-05-21 20:01
I sent an offer to @dukenv0307 for the report.

I removed the Help Wanted label since that one PR will fix both, but I'm going to leave this issue open until the PR is merged & deployed so that we can verify it works as expected.

**Comment by sakluger** [comment] 2023-05-27 23:49
The other issue is deployed and this contract is paid, gonna close this one out.

**Closed by sakluger** 2023-05-27 23:49 UTC
Labels: External, Weekly, Bug
