### ISSUE TITLE
[HOLD for payment 2023-09-18] [$1000] Both English & Spanish Emoji are present while making  default language spanish

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25735] opened 2023-08-22 23:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Case 1:While making English as default language
1.login to app
2.go to settings
3. click on Preferences
4. choose language English
5. go to  any chat composer
6. Type  :fuego  and clear
7. type :fire
8. In this case, you don't see any result while searching with spanish emoji name
Case 2:While making Spanish as default language
1.login to app
2.go to settings
3. click on Preferences
4. choose language Spanish
5. go to  any chat composer
6. Type  :fuego  and clear
7. type :fire
8. In this case, you see result while searching with spanish emoji  as well as english emoji
## Expected Result:
While making spanish as a default language,  english emoji should be hidden
## Actual Result:
While making spanish as a default language, both spanish & english emoji should are shown
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.56-14
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/62c32e98-959a-4f1b-b275-54d8ec986aa3

https://github.com/Expensify/App/assets/38435837/d4aeedce-25dc-4d0a-ba87-00ca99f66984

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692012294848209

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0192922d7d2b8409c8</li>
        <li>Upwork Job ID: 1694408125906583552</li>
        <li>Last Price Increase: 2023-08-30</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26437177</li>
<li>Thanos30 | Contributor | 26437178</li>
<li>lincolnb17 | Reporter | 26437179</li>
</ul></li>
    </ul>
</details>

**Comment by Thanos30** [comment] 2023-08-23 01:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When in Spanish language, we get suggestion for English emojis too.

### What is the root cause of that problem?

The root cause of the problem is on `EmojiTrie.js` file.

On line 22, we have: `const names = isDefaultLocale ? [name] : [...new Set([name, item.name])];`
, which adds both the spanish name and the english name on the list.

Later on, we are also including english keywords to work on Spanish emojis, but this won't add the english emojis in the suggestions, it will only use the english keywords to find Spanish emojis.


### What changes do you think we should make in order to solve the problem?
In order not to show the English emojis, we just need to alter the code to be like this:

`const names = isDefaultLocale ? [name] : [_.get(langEmojis, [item.code, 'name'])];`

This will only add the Spanish version of the emojis

### What alternative solutions did you explore? (Optional)
## Personally Preferred Solution

I believe that it is okay for people to be able to use the english names to find emojis, as they are widely used.

Based on that, I suggest that we allow the english name search for the suggestions, but we should only show the Spanish version on the suggestions. 

e.x User types :fire , but he will see :fuego: on the suggestions.

In case you agree with me on that, then we should modify the `createTier` function to be like that:

```
function createTrie(lang = CONST.LOCALES.DEFAULT) {
    const trie = new Trie();
    const langEmojis = localeEmojis[lang];
    const isDefaultLocale = lang === CONST.LOCALES.DEFAULT;

    _.forEach(emojis, (item) => {
        if (item.header) {
            return;
        }

        const englishName = item.name;
        const spanishName = _.get(langEmojis, [item.code, 'name'], englishName);
        
        // Add the actual name of the emoji for the current language
        const node = trie.search(spanishName);
        if (!node) {
            trie.add(spanishName, {code: item.code, types: item.types, name: spanishName, suggestions: []});
        } else {
            trie.update(spanishName, {code: item.code, types: item.types, name: spanishName, suggestions: node.metaData.suggestions});
        }

        // Add the English name and keywords as suggestions but always reference the Spanish name
        if (!isDefaultLocale) {
            const englishNode = trie.search(englishName);
            if (!englishNode) {
                trie.add(englishName, {suggestions: [{code: item.code, types: item.types, name: spanishName}]});
            } else {
                trie.update(englishName, {
                    ...englishNode.metaData,
                    suggestions: [...englishNode.metaData.suggestions, {code: item.code, types: item.types, name: spanishName}],
                });
            }

            const keywords = _.get(langEmojis, [item.code, 'keywords'], []);
            for (let j = 0; j < keywords.length; j++) {
                const keywordNode = trie.search(keywords[j]);
                if (!keywordNode) {
                    trie.add(keywords[j], {suggestions: [{code: item.code, types: item.types, name: spanishName}]});
                } else {
                    trie.update(keywords[j], {
                        ...keywordNode.metaData,
                        suggestions: [...keywordNode.metaData.suggestions, {code: item.code, types: item.types, name: spanishName}],
                    });
                }
            }
        }
    });

    return trie;
}
```

This way, we will have the english name suggestions, but will only reference the Spanish one!

**Comment by studentofcoding** [comment] 2023-08-23 20:17
What's the expected result on English language @m-natarajan @CortneyOfstad ? Will it show both English Emoji & Spanish or only English? Thanks

**Comment by CortneyOfstad** [comment] 2023-08-23 20:23
@studentofcoding the expected result is that if English is set as the default, then the emojis would be listed in English (Spanish = Spanish), **not** having both available when one language is set as the preference over the other 👍

**Comment by yassinedrissi87** [comment] 2023-08-24 00:28
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
[Both English & Spanish Emoji are present while making default language spanish]
**What is the root cause of that problem?**
the createTrie in the Emojitrie.js does not make the difference between the spanish and the english.
**What changes do you think we should make in order to solve the problem?** 
I think that the best solution is to add a new property called "lang" in the object before insert it in the trie.
and we can later use this property in rendering result wherever we want like in EmojiSuggestions component we can do :

```javascript
return (
        <AutoCompleteSuggestions
          

>   suggestions={props.emojis.filter(item =>{
> 
>                 if(Object.hasOwn(item, 'lang')){
>                     return item;
> 
>                 }
> 
>                 
>             })}

            renderSuggestionMenuItem={renderSuggestionMenuItem}
            keyExtractor={keyExtractor}
            highlightedSuggestionIndex={props.highlightedEmojiIndex}
            onSelect={props.onSelect}
            isSuggestionPickerLarge={props.isEmojiPickerLarge}
            shouldIncludeReportRecipientLocalTimeHeight={props.shouldIncludeReportRecipientLocalTimeHeight}
            accessibilityLabelExtractor={keyExtractor}
        />
    );
``` 
```javascript
function createTrie(lang = CONST.LOCALES.DEFAULT) {
    const trie = new Trie();
    const langEmojis = localeEmojis[lang];
    const isDefaultLocale = lang === CONST.LOCALES.DEFAULT;

    _.forEach(emojis, (item) => {
        if (item.header) {
            return;
        }

        const name = isDefaultLocale ? item.name : _.get(langEmojis, [item.code, 'name']);
        const names = isDefaultLocale ? [name] : [...new Set([name, item.name])];
        _.forEach(names, (nm) => {
            const node = trie.search(nm);
            if (!node) {

>                 trie.add(nm, {lang: lang,code: item.code, types: item.types, name: nm, suggestions: []});


            } else {

>                 trie.update(nm, {lang: lang,code: item.code, types: item.types, name: nm, suggestions: node.metaData.suggestions});


            }
        });

        const keywords = _.get(langEmojis, [item.code, 'keywords'], []).concat(isDefaultLocale ? [] : _.get(localeEmojis, [CONST.LOCALES.DEFAULT, item.code, 'keywords'], []));
        for (let j = 0; j < keywords.length; j++) {
            const keywordNode = trie.search(keywords[j]);
            if (!keywordNode) {

>                 trie.add(keywords[j], {suggestions: [{lang: lang,code: item.code, types: item.types, name}]});


            } else {
                trie.update(keywords[j], {
                    ...keywordNode.metaData,

>                     suggestions: [...keywordNode.metaData.suggestions, {lang: lang,code: item.code, types: item.types, name}],


                });
            }
        }
    });

    return trie;
}
```

**Comment by s-alves10** [comment] 2023-08-24 01:56
This is an intentional behavior. Please check https://github.com/Expensify/App/issues/16086#issuecomment-1595369534

cc @0xmiroslav @stitesExpensify @iwiznia

**Comment by yassinedrissi87** [comment] 2023-08-24 02:08
> This is an intentional behavior. Please check [#16086 (comment)](https://github.com/Expensify/App/issues/16086#issuecomment-1595369534)
> 
> cc @0xmiroslav @stitesExpensify @iwiznia

I can use the logic of my solution to filter the rendering of the emojis as required when the user switch between the language

**Comment by jjcoffee** [comment] 2023-08-24 07:21
@CortneyOfstad This is a feature, not a bug :smile: It was intentionally added in [this PR](https://github.com/Expensify/App/pull/20828) as @s-alves10 points out.

**Comment by Thanos30** [comment] 2023-08-24 09:57
@jjcoffee @CortneyOfstad @s-alves10 I do agree that users should be able to use the english words to search for emojis, but showing all emojis in both versions is kinda strange.

In my 2nd solution on my proposal, a Spanish user can search for :fire , and he will see the :fuego: emoji, which I believe is a better approach on that, not to have duplicate emojis on the suggestions.

**Comment by lincolnb17** [comment] 2023-08-24 10:04
@Thanos30  exactly, i also felt the same

**Comment by jjcoffee** [comment] 2023-08-24 10:13
@Thanos30 Hmm can you show an example where duplicate emojis show? That would be more of an issue if that's the case.

**Comment by Thanos30** [comment] 2023-08-24 10:14
@jjcoffee Sure, a small example would be here:
<img width="1101" alt="image" src="https://github.com/Expensify/App/assets/32620770/69fe2d4c-7e05-44ad-a790-a0ca4b32dbdc">

**Comment by jjcoffee** [comment] 2023-08-24 11:16
@Thanos30 Thanks! That does seem like unexpected behaviour. Any chance you have a couple more examples? 

I might need to field some opinions on Slack for expected behaviour here, as I'm not sure searching in English and displaying the Spanish result will always feel intuitive.

@m-natarajan Could you update the issue results section to the following:

## Expected Result:
When the language is set to Spanish, searching in English should not result in duplicate emoji listings

## Actual Result:
When the language is set to Spanish, searching in English results in duplicate emoji listings

**Comment by Thanos30** [comment] 2023-08-24 11:22
@jjcoffee I do understand, indeed this won't be that visible in most cases. But, as per my proposal, we could still keep the ability to search using english names, but display only the default language results. I personally think it's the smoothest approach, but let me know what you think!

Thanks!

**Comment by jjcoffee** [comment] 2023-08-24 11:34
Asked [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692876804755169).

**Comment by jjcoffee** [comment] 2023-08-24 12:51
Okay, pretty strong response [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1692876804755169) all in favour of `Searching in English simply displays the Spanish result (Search: ":bomb", Result displayed: ":bomba")`, as in @Thanos30's [proposal](https://github.com/Expensify/App/issues/25735#issuecomment-1689144965) (alternative solution).

@Thanos30 As a rule we normally don't accept code diffs in proposals. Could you add some more detail to your proposal about your approach for the alt solution (what you're changing (links to files/line refs help) and why). Thanks!

**Comment by Thanos30** [comment] 2023-08-24 13:41
@jjcoffee Updated my proposal to focus only on the crucial parts of the change, also added an extra change I noticed. Thank you for your patience 🙏

**Comment by jjcoffee** [comment] 2023-08-25 12:18
@Thanos30 Thanks for the update and good catch with the immediate replacement! 

Looking at your proposal again, I'm not sure if your RCA covers the behaviour we're now looking at (with language set to Spanish, searching in English can result in duplicate emoji listings). So we're still missing out on the "why" this issue is happening. Do you think you could clarify that section?

**Comment by Thanos30** [comment] 2023-08-25 12:19
@jjcoffee Of course, let me update the proposal for that part!

**Comment by Thanos30** [comment] 2023-08-25 12:22
@jjcoffee edited the proposal and tagged you on the part that explains how both language names are suggested.

**Comment by CortneyOfstad** [comment] 2023-08-28 12:32
@jjcoffee Bump on the comments above from @Thanos30 — TIA!

**Comment by jjcoffee** [comment] 2023-08-28 15:28
@Thanos30 Thanks for the updated [proposal](https://github.com/Expensify/App/issues/25735#issuecomment-1689144965)! And sorry to go on about this, but I'm still struggling a bit to relate your solution to your RCA :smile:  

In your RCA you appear to be saying the root cause is down to adding two Trie nodes (one for each language) here:

https://github.com/Expensify/App/blob/c7bdc81a3e30bd380a942c980e16f0891d0db4a6/src/libs/EmojiTrie.js#L21-L22

But in your solution you're also adding a node for each language (but just setting the `name` to the locale language name). To me this suggests that the RCA is actually that we're not setting the `name` in the added nodes appropriate to the locale?

If that's the case, I'm unsure why we need so many changes as in your solution, since we can just update `nm` to `name` here:

https://github.com/Expensify/App/blob/c7bdc81a3e30bd380a942c980e16f0891d0db4a6/src/libs/EmojiTrie.js#L25-L29

which should reference the locale's name from here:

https://github.com/Expensify/App/blob/c7bdc81a3e30bd380a942c980e16f0891d0db4a6/src/libs/EmojiTrie.js#L21

Or is there an additional part of your proposed solution that I've missed? If that's the case, it would be great if you could break that down in your solution. Adding this sort of extra detail and breaking your proposed solution into smaller steps helps us C+s understand and review proposals faster, and hopefully helps you to avoid mistakes as you understand your solution better :slightly_smiling_face:

**Comment by Thanos30** [comment] 2023-08-28 15:55
@jjcoffee No worries, I totally understand that, and thank you for the feedback!

So basically, on the current code, on the `names` variable, we pass a set containing both the English and the Spanish name of the emoji when the preferred language is set to Spanish.

After that, our Trie object contains both versions of the emoji.

In my solution, I first add the preferred language versions of the emojis.

After that, I check if the preferred language is not the default one (English), and if that's the case, I add to our Trie object the english version of the emojis but using the Spanish name.

The core difference is that, instead of passing a Set of both names differently, we pass both but with the `preferredLanguageName`.

What you said is absolutely right! But if we replace `nm` with `name`, this will only pass the Spanish emojis and not the English ones when the preferred language is Spanish.

What I do is basically keeping both language names, and if our language is not English, I add both references in our Trie, but with the preferred language name.

**Comment by Thanos30** [comment] 2023-08-28 16:08
@jjcoffee Actually, you are right, sorry, didn't sleep very well 😄 . We can replace the `nm` with `name`, but only inside the object on the `name` property! Let me try that and update you!

**Comment by jjcoffee** [comment] 2023-08-29 11:45
@Thanos30 Thanks for the explanation!

From what you're saying you are still adding an extra Trie node for the default language (English), but the key is to add the locale language's (Spanish) name as a suggestion. This works because in `suggestEmojis` (in `EmojiUtils`) we check the `suggestion`'s `name` against any existing matches before adding it as a suggestion for display. 

https://github.com/Expensify/App/blob/3f9f1e6e2ce91468a536755f8d5830a2f77d7eaa/src/libs/EmojiUtils.js#L381

Currently we add an English Trie node with the suggestion's name in English, which won't match the equivalent Spanish emoji, so it gets added as a separate match. Of course changing the suggestion's name to the Spanish one then prevents this.

It would be great if you update your [proposal](https://github.com/Expensify/App/issues/25735#issuecomment-1689144965)'s RCA and solution to clarify this area, so it's easy for others to understand at a glance, without having to read all the comments!

**Comment by jjcoffee** [comment] 2023-08-29 11:45
One final concern is that searching a keyword that's English-only, like `:comic` doesn't return any results when I test your code. I think you're missing adding the English keywords? We can deal with that on the PR, as I think it would rely on the same/similar general solution.

**Comment by jjcoffee** [comment] 2023-08-29 11:50
No worries, thanks for your patience! And yes, I don't think we want to modify any behaviour that was introduced in the original PR that introduced English-language search (except of course to get rid of duplicate results).

**Comment by Thanos30** [comment] 2023-08-29 11:52
Got it, let me adjust the proposal and give a quick try on adding the English keywords!

**Comment by Thanos30** [comment] 2023-08-29 12:03
@jjcoffee Now I remember why I removed the english keywords. Here's an example of why I did it:
<img width="1099" alt="image" src="https://github.com/Expensify/App/assets/32620770/6af82b2a-fa74-4954-b5c3-5250494b6189">

I didn't like the fact that typing `:fire` when in Spanish language shows the firetruck first instead of the fire emoji.

This is happening because in Spanish, the firetruck is `camion de bomberos`, which comes before `fuego` alphabetically.

What do you think about that?

**Comment by Thanos30** [comment] 2023-08-29 12:23
@jjcoffee Yes, because the english emoji is there. If what we are typing matches an emoji code, it will of course show that first. But in our case, since we are removing the english emojis to avoid duplicates, it will simply work based on suggestions and not the name itself.

**Comment by jjcoffee** [comment] 2023-08-29 15:22
@Thanos30 If I understand you correctly that sounds more like a workaround. If we wanted to add support for new languages, we'd have to re-add suggestions every time.

**Comment by Thanos30** [comment] 2023-08-29 16:03
@jjcoffee Another idea that came to mind is to, instead of adding the english version as a `suggestion`, maybe create a new property called `translation`, and pass the english name there.

We will add the translation to the `matchings` when suggesting emojis on `EmojiUtils.js`, before we check the suggestion keywords. That way, the emoji suggestions will first have the correct emoji if we are in Spanish but actually match the name of it in english.

This will fix the issue, and I think it's a smooth approach. What do you think?

**Comment by Thanos30** [comment] 2023-08-30 15:58
Sure thing @jjcoffee , no worries!

**Comment by Thanos30** [comment] 2023-08-30 19:38
@jjcoffee Went ahead and cleared my proposal to remove useless information and stay on point. I also figured the solution for our latest notice about the place of the suggestion. Please re-review the proposal when you are available.

Thanks 🙏

**Comment by Thanos30** [comment] 2023-08-31 15:31
@jjcoffee Noted about linking my proposal!

About your comment, you are right, since it is being added at the beginning, it will remain there regardless of the position of the code-block.

I just liked it better there, as it is a conditional addition when a user selects a language other than english.

If you prefer that codeblock to go above the keywords additions, we could do that!

Thank you for the review and your patience throughout this, I really appreciate it 🙏

**Comment by jjcoffee** [comment] 2023-08-31 15:36
@0xmiroslav we're aware that it's intentional to be able to search in English whilst locale is set to Spanish. The issue is that it results in duplicate suggestions:

![image](https://github.com/Expensify/App/assets/27287420/92a485da-7b3b-44d7-a29b-96b19ab77af4)

**Comment by lincolnb17** [comment] 2023-08-31 17:49
@johnmlee101, @CortneyOfstad Hi, I have one  question. since, this issue was created before August 30th , so contributers & bug reporter  are paid according to the old pay scale , right?
source: https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649

**Comment by jjcoffee** [comment] 2023-09-01 15:21
@Thanos30 Don't forget to let us know when you expect to be able to raise the PR (no rush, it's just helpful for everyone to know!).

**Comment by CortneyOfstad** [comment] 2023-09-01 15:41
> @johnmlee101, @CortneyOfstad Hi, I have one question. since, this issue was created before August 30th , so contributers & bug reporter are paid according to the old pay scale , right?
source: https://expensify.slack.com/archives/C01GTK53T8Q/p1693424078129649

I _believe so_ but @johnmlee101 can you confirm?

**Comment by Thanos30** [comment] 2023-09-01 18:00
@CortneyOfstad @jjcoffee Sorry for the delay, had some trouble running the android app to test. PR is ready for review!

Thanks 🙏

**Comment by lincolnb17** [comment] 2023-09-02 08:02
@johnmlee101 @CortneyOfstad this issue was created  a week before 30 Aug, but melvin bot is sending $50 offer in upwork, can you please this check issue?

**Comment by jjcoffee** [comment] 2023-09-04 15:17
@Thanos30 Thanks, and no worries - Android is giving everyone trouble these days :sweat_smile: I'll review the PR as a priority tomorrow!

**Comment by johnmlee101** [comment] 2023-09-04 16:08
I think we can go with the old payments system since this was started beforehand

**Comment by CortneyOfstad** [comment] 2023-09-08 15:13
@jjcoffee just checking to see if there was an update on the PR review? TIA!

**Comment by jjcoffee** [comment] 2023-09-08 15:16
@CortneyOfstad Just waiting for the internal engineer to review the [PR](https://github.com/Expensify/App/pull/26507)!

**Comment by Thanos30** [comment] 2023-09-08 15:34
@jjcoffee Ay, I know, thanks 🙏

**Comment by Thanos30** [comment] 2023-09-11 10:49
@jjcoffee PR got merged without any further change requests after all. Since we had it complete within the 3 days period, are we eligible for the bonus if everything goes well?

Thank you all 🙏

**Comment by CortneyOfstad** [comment] 2023-09-18 20:02
@Thanos30 this is not eligible for the bonus at this time, but standard payment is being made now 👍

**Comment by CortneyOfstad** [comment] 2023-09-18 20:06
Payments are completed. Closing!

**Closed by CortneyOfstad** 2023-09-18 20:06 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Thanos30** [comment] 2023-09-18 20:20
Okay @CortneyOfstad , Thank you 🙏
