### ISSUE TITLE
[Pending Payment] [$250] Web/Desktop -  Workspace settings side menu does not open after creating workspace

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#10665] opened 2022-08-29 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging and login
2. Create Workspace

## Expected Result:
Workspace should be created and side menu Workspace settings should be open.

## Actual Result:
Workspace is created but side menu Workspace settings isn't open. Only popup appeared.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** v1.1.93-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 
<img width="1304" alt="Bug5709463_WS" src="https://user-images.githubusercontent.com/43996225/187255086-1d94dfa1-3532-4efb-9da0-88ab651394d2.png">

https://user-images.githubusercontent.com/43996225/187255078-68e71a02-fefb-40ab-8230-da88ac36776a.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by joelbettner** [comment] 2022-08-30 13:46
I think we can make this an external.

**Comment by jayeshmangwani** [comment] 2022-08-30 15:06
### Proposal

we need to pass the array in this Promise.all in create function

https://github.com/Expensify/App/blob/22a0cba7aaeaa786f04a63a5ad74c650c4c35001/src/libs/actions/Policy.js#L136-L144

```diff
+return Promise.all([
  Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY}${response.policyID}`, {
      id: response.policyID,
      type: response.policy.type,
      name: response.policy.name,
      role: CONST.POLICY.ROLE.ADMIN,
      outputCurrency: response.policy.outputCurrency,
  }),
  Onyx.merge(`${ONYXKEYS.COLLECTION.POLICY_MEMBER_LIST}${response.policyID}`, getSimplifiedEmployeeList(response.policy.employeeList)),
+]);
```

https://user-images.githubusercontent.com/35371050/187472584-ecb8ab39-900e-466d-bf3a-71098464f82c.mov

**Comment by trjExpensify** [comment] 2022-08-30 15:24
Adding yah back for CM, @NicMendonca.

**Comment by NicMendonca** [comment] 2022-08-30 16:41
job post: https://www.upwork.com/jobs/~0166853faf8e443072

**Comment by Beamanator** [comment] 2022-08-31 07:06
@parasharrajat good find, it makes sense to keep this one open and close the other - also since this issue was created first (barely). 

This is a regression from the PR you mentioned but that PR was created by an internal employee and it didn't make it to Production, so I don't think there's much to do there except get it fixed in this issue - what do you think?

**Comment by jayeshmangwani** [comment] 2022-08-31 12:43
this change is added in this [PR](https://github.com/Expensify/App/pull/10718) and it merged 2 hours ago to the main branch.

cc: @rushatgabhane @Beamanator

**Comment by Beamanator** [comment] 2022-08-31 12:57
Oh nice thanks for the link @jayeshmangwani 👍 Looks like it's on Staging already

**Comment by jasperhuangg** [comment] 2022-08-31 13:34
my b guys, I never saw this issue and was assigned that other issue as demolitions so decided to fix it super quick.

**Comment by jayeshmangwani** [comment] 2022-08-31 15:30
> Oh nice thanks for the link @jayeshmangwani 👍 Looks like it's on Staging already

I have a doubt here, am I eligible or not for the payment in this scenario?
cc: @rushatgabhane @Beamanator

**Comment by Beamanator** [comment] 2022-09-02 08:13
@jayeshmangwani good question, I'm running this by some internal team members, will get back to you soon 👍

**Comment by Beamanator** [comment] 2022-09-02 14:30
Discussed internally ([here](https://expensify.slack.com/archives/C01SKUP7QR0/p1662106391577299)) and we are happy to pay you for your time looking into this solution, adding your proposal, and getting selected (even though the fix was completed internally).

@NicMendonca would you please pay @jayeshmangwani and close this out? :)

**Comment by jayeshmangwani** [comment] 2022-09-06 09:02
@Beamanator Thanks for the update,

@NicMendonca I have applied at Upwork.

**Comment by NicMendonca** [comment] 2022-09-07 14:07
^ Reopening so I can better track this via K2

@jayeshmangwani Can you please accept the offer in Upwork when you get the chance? Thanks!

**Comment by jayeshmangwani** [comment] 2022-09-07 14:09
@NicMendonca offer accepted 🚀

**Comment by NicMendonca** [comment] 2022-09-07 14:12
paid!

**Closed by NicMendonca** 2022-09-07 14:12 UTC
Labels: Exported, External, Engineering, Weekly
