### ISSUE TITLE
[HOLD for payment 2024-12-09] [HOLD for payment 2024-12-07] Search - Read message shown in bold in search router result

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53289] opened 2024-11-28 21:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.66-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** testpayment935+695@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Prerequisite - User A send a message to user B
Steps
1. {User B} Navigate to https://staging.new.expensify.com/

2. {User B} Notice a new message is bold in LHN and Search router
3. {User B} Navigate to the message so that the message can be read
4. {User B} Notice LHN is not bold any more
5. {User B} Navigate to Search router

## Expected Result:
As the Message is already read the Search router result should not be bold

## Actual Result:
Read message shown in bold in search router result

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/da533cae-f814-4ed5-aefa-9a3041cbc367

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by aldo-expensify** [comment] 2024-11-29 01:26
Besides the chat name (participant name) being bolded, the last message is missing:

<img width="546" alt="image" src="https://github.com/user-attachments/assets/8d9ac7b7-f97b-4507-b8e5-2609b08576b0">

and instead we show the email.

This has very likely the same root cause as https://github.com/Expensify/App/issues/53291

**Comment by aldo-expensify** [comment] 2024-11-29 01:35
I think https://github.com/Expensify/App/pull/53293#discussion_r1862818438 fixes this

**Comment by aldo-expensify** [comment] 2024-11-29 01:45
Made the PR ready for review: https://github.com/Expensify/App/pull/53293

**Comment by mountiny** [comment] 2024-11-29 17:24
@aldo-expensify this is apparently still not fixed based on qa testing here https://github.com/Expensify/App/pull/53293#issuecomment-2508062917

**Comment by aldo-expensify** [comment] 2024-11-29 18:32
> @aldo-expensify this is apparently still not fixed based on qa testing here https://github.com/Expensify/App/pull/53293#issuecomment-2508062917

😢 , will try to reproduce

**Comment by aldo-expensify** [comment] 2024-11-29 19:56
btw, I'm still trying to fix my dev env because Auth started crashing.... I reproduced in staging, but I haven't been able to work with my vm yet :(

**Comment by aldo-expensify** [comment] 2024-11-29 20:42
hmm, I think this is fixed in `main`, but not in staging. Staging ended up in a not so great state when we CP'd https://github.com/Expensify/App/pull/53293 because we are missing the changes from https://github.com/Expensify/App/pull/53056:

<img width="672" alt="image" src="https://github.com/user-attachments/assets/b5150c2f-ed7a-4491-b31c-ee0745e72dcc">

I'm not sure about what to do here... I doubt we want to CP: https://github.com/Expensify/App/pull/53056 since it is a big PR, or is that fine? @mountiny  do you have some thoughts about this? 😬 🙇

**Comment by aldo-expensify** [comment] 2024-11-29 20:44
Maybe we can ignore this and deploy https://github.com/Expensify/App/pull/53056 normally on its time since the bold/no bod doesn't sound like a big issue to me

**Comment by mountiny** [comment] 2024-11-30 09:57
@aldo-expensify Yes I think we can treat this as non-blocker, its minor issue and we can let the refactor go through normal process to catch any regressions on that. Thanks for digging 🙌

**Comment by kadiealexander** [comment] 2024-12-09 03:04
No payment due.

**Closed** 2024-12-09 23:59 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
