### ISSUE TITLE
[HOLD for payment 2024-04-15] [$125] Change the order of items in the global create

### ISSUE THREAD

**Issue by thienlnam** [Expensify/App#38950] opened 2024-03-25 17:55 UTC
https://expensify.slack.com/archives/C066HJM2CAZ/p1711236684276869

Currently:
![image](https://github.com/Expensify/App/assets/30609178/92524bc7-2110-4bd2-8a94-09c909b18222)

Should be:
Start chat
Track expense
Request money (soon to be Submit expense)
Send money (soon to be Pay someone)
Assign task
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01935b1cfdaa846be8</li>
        <li>Upwork Job ID: 1773048936208711680</li>
        <li>Last Price Increase: 2024-03-27</li>
<li>Automatic offers: </li>
<ul>
<li>akinwale | Reviewer | 0</li>
<li>ShridharGoel | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by Habtamu-Asefa** [comment] 2024-03-25 19:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Changing the the order to the new order of items in the global create

### What is the root cause of that problem?
New order of items in the global create

The current ordering is like this: 
https://github.com/Expensify/App/blob/a5189c448fe86ed50b2a80cdc2eebf7daad0b748/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.js#L160-L233

### What changes do you think we should make in order to solve the problem?

We have to change the ordering on FloatingActionButtonAndPopover.js (If Save the world is intentionally left from the list)
![Screenshot from 2024-03-25 22-48-23](https://github.com/Expensify/App/assets/77902437/ef119a33-5769-4495-b011-449945e85540)

menuItems={[

  {
      icon: Expensicons.ChatBubble,
      text: translate('sidebarScreen.fabNewChat'),
      onSelected: () => interceptAnonymousUser(() => Navigation.navigate(ROUTES.NEW)),
  },
  ...(canUseTrackExpense
      ? [
          {
              icon: Expensicons.DocumentPlus,
              text: translate('iou.trackExpense'),
              onSelected: () =>
                  interceptAnonymousUser(() =>
                      IOU.startMoneyRequest(
                          CONST.IOU.TYPE.TRACK_EXPENSE,
                          // When starting to create a track expense from the global FAB, we need to retrieve selfDM reportID.
                          // If it doesn't exist, we generate a random optimistic reportID and use it for all of the routes in the creation flow.
                          ReportUtils.findSelfDMReportID() || ReportUtils.generateReportID(),
                      ),
                  ),
          },
      ]
      : []),
  {
      icon: Expensicons.MoneyCircle,
      text: translate('iou.requestMoney'),
      onSelected: () =>
          interceptAnonymousUser(() =>
              IOU.startMoneyRequest(
                  CONST.IOU.TYPE.REQUEST,
                  // When starting to create a money request from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                  // for all of the routes in the creation flow.
                  ReportUtils.generateReportID(),
              ),
          ),
  },
  {
      icon: Expensicons.Send,
      text: translate('iou.sendMoney'),
      onSelected: () =>
          interceptAnonymousUser(() =>
              IOU.startMoneyRequest(
                  CONST.IOU.TYPE.SEND,
                  // When starting to create a send money request from the global FAB, there is not an existing report yet. A random optimistic reportID is generated and used
                  // for all of the routes in the creation flow.
                  ReportUtils.generateReportID(),
              ),
          ),
  },
  {
      icon: Expensicons.Task,
      text: translate('newTaskPage.assignTask'),
      onSelected: () => interceptAnonymousUser(() => Task.clearOutTaskInfoAndNavigate()),
  },
  ...(!props.isLoading && !Policy.hasActiveChatEnabledPolicies(props.allPolicies)
      ? [
            {
                displayInDefaultIconColor: true,
                contentFit: 'contain',
                icon: Expensicons.NewWorkspace,
                iconWidth: 46,
                iconHeight: 40,
                text: translate('workspace.new.newWorkspace'),
                description: translate('workspace.new.getTheExpensifyCardAndMore'),
                onSelected: () => interceptAnonymousUser(() => App.createWorkspaceWithPolicyDraftAndNavigateToIt()),
            },
        ]
      : []),
]}

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2024-03-27 18:06
Yup, was confirming this change but going to make external now

**Comment by thienlnam** [comment] 2024-03-27 20:10
Yeah, that will be removed at a future date

**Comment by akinwale** [comment] 2024-03-28 08:38
This is pretty straightforward. We can move forward with @ShridharGoel's [proposal](https://github.com/Expensify/App/issues/38950#issuecomment-2018609031).

🎀👀🎀 C+ reviewed.

**Comment by akinwale** [comment] 2024-03-29 08:48
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] Android: Native
    - [x] Android: mWeb Chrome
    - [x] iOS: Native
    - [x] iOS: mWeb Safari
    - [x] MacOS: Chrome / Safari
    - [x] MacOS: Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that the left part of a conditional rendering a React component is a boolean and NOT a string, e.g. `myBool && <MyComponent />`.
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product is localized by adding it to `src/languages/*` files and using the [translation method](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60)
    - [x] I verified all numbers, amounts, dates and phone numbers shown in the product are using the [localization methods](https://github.com/Expensify/App/blob/4bd99402cebdf4d7394e0d1f260879ea238197eb/src/components/withLocalize.js#L60-L68)
    - [x] I verified any copy / text that was added to the app is grammatically correct in English. It adheres to proper capitalization guidelines (note: only the first word of header/labels should be capitalized), and is either coming verbatim from figma or has been approved by marketing (in order to get marketing approval, ask the Bug Zero team member to add the Waiting for copy label to the issue)
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If any new file was added I verified that:
    - [x] The file has a description of what it does and/or why is needed at the top of the file if the code is not self explanatory
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/utils/index.ts) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(theme.componentBG`)
- [x] If the PR modifies code that runs when editing or sending messages, I tested and verified there is no unexpected behavior for all supported markdown - URLs, single line code, code blocks, quotes, headings, bold, strikethrough, and italic.
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.
- [x] If the PR modifies the UI (e.g. new buttons, new UI components, changing the padding/spacing/sizing, moving components, etc) or modifies the form input styles:
    - [x] I verified that all the inputs inside a form are aligned with each other.
    - [x] I added `Design` label and/or tagged `@Expensify/design` so the design team can review the changes.
- [x] If a new page is added, I verified it's using the `ScrollView` component to make it scrollable when more elements are added to the page.
- [x] If the `main` branch was merged into this PR after a review, I tested again and verified the outcome was still expected according to the `Test` steps.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

![39204-android-native](https://github.com/Expensify/App/assets/4160319/7189c629-2ad3-4216-be73-29efdcffd2dd)

</details>

<details>
<summary>Android: mWeb Chrome</summary>

![39204-android-chrome](https://github.com/Expensify/App/assets/4160319/c46340b3-1021-47c2-ae9f-b45ddd3fa66b)

</details>

<details>
<summary>iOS: Native</summary>

![39204-ios-native](https://github.com/Expensify/App/assets/4160319/bb246742-52ec-4ff1-ba1d-e0979985a780)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

![39204-ios-safari](https://github.com/Expensify/App/assets/4160319/118d59a6-8fcb-4038-b0af-5c56a273562d)

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![39204-web](https://github.com/Expensify/App/assets/4160319/249201f2-a687-4e95-bcf0-aac9b696f21f)

</details>

<details>
<summary>MacOS: Desktop</summary>

![39204-desktop](https://github.com/Expensify/App/assets/4160319/941ba132-90d5-4fbb-b071-3a306f54446a)

</details>

**Comment by isabelastisser** [comment] 2024-04-15 18:29
All set in Upwork. Closing!

**Closed by isabelastisser** 2024-04-15 18:29 UTC
Labels: External, Engineering, Daily, Awaiting Payment
