### ISSUE TITLE
[HOLD for payment 2024-06-28] [$500] [QAB] Add a tooltip to the Quick Action Button if it is being displayed for the first time.

### ISSUE THREAD

**Issue by Gonals** [Expensify/App#38054] opened 2024-03-11 15:04 UTC
HELD on https://github.com/Expensify/App/issues/38050

As described in [this section of the design doc](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#bookmark=id.tp2y09tua26j), we want to display a tooltip the first time the QAB is set:

From the design doc:
**High-level**
The first time global create is opened with the quick action button present, an “educational tooltip” is visible to help explain and draw attention to it:

![image](https://github.com/Expensify/App/assets/16232057/ec2d818c-c1c1-48d6-b03f-70bc776f8195)

**Detailed**
The Tooltip
<img width="306" alt="image" src="https://github.com/Expensify/App/assets/16232057/c7dba775-07f2-42de-8b71-a23310acd1f2">

- For the tooltip, we will leverage our existing [tooltip component](https://github.com/Expensify/App/tree/main/src/components/Tooltip):
- We will update MenuItem to receive an optional tooltipContent parameter. When populated, the tooltip will be shown.
- If populated, we will pass the content to <Tooltip> via the renderTooltipContent parameter like we do here or here.
- The content will be a simple View, styled with the green background, and the text shown in the mockup.
-  We will pass the content when adding the QAB menuItem [here](https://docs.google.com/document/d/1Fa-sKBcROi1fjpZnHMUZ3J6Q96yXCEfU-ex14e_wdns/edit#bookmark=id.gb6m9qyccl20) if isFirstQuickAction is set.
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018ff6f76c5f734cc9</li>
        <li>Upwork Job ID: 1767204991949152256</li>
        <li>Last Price Increase: 2024-06-28</li>
<li>Automatic offers: </li>
<ul>
<li>cubuspl42 | Reviewer | 0</li>
<li>tienifr | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom</details>

**Comment by redcrystalll** [comment] 2024-03-11 18:19
To integrate the provided Tooltip component with the functionality described in the design document, you'll need to modify it to accept the renderTooltipContent prop for custom tooltip content and conditionally render it based on the shouldRender prop. Here's how you can modify the Tooltip component:

ToolTip Code:
import React from 'react';
import BaseTooltip from './BaseTooltip'; // Import the base tooltip component
import type { TooltipExtendedProps } from './types';

function Tooltip({ shouldRender = true, children, renderTooltipContent, ...props }: TooltipExtendedProps) {
    if (!shouldRender || !renderTooltipContent) {
        return children;
    }

    return (
        <BaseTooltip {...props}>
            {children}
            {renderTooltipContent()}
        </BaseTooltip>
    );
}

Tooltip.displayName = 'Tooltip';

export default Tooltip;


Usage of ToolTip:
import React from 'react';
import Tooltip from './Tooltip'; // Assuming you've named the modified tooltip component 'Tooltip'

function MyComponent() {
    const tooltipContent = () => (
        <div style={{ backgroundColor: 'green' }}>
            {/* Custom content for the tooltip */}
            This is a tooltip content.
        </div>
    );

    return (
        <div>
            <Tooltip shouldRender={true} renderTooltipContent={tooltipContent}>
                {/* Content to be wrapped by the tooltip */}
                <button>Hover over me</button>
            </Tooltip>
        </div>
    );
}

export default MyComponent;

**Comment by twisterdotcom** [comment] 2024-03-25 10:15
Still HELD.

**Comment by trjExpensify** [comment] 2024-03-25 20:41
#38050 has merged (not yet deployed), but I think we can start reviewing the proposals here. :)

**Comment by cubuspl42** [comment] 2024-03-26 08:33
There's one proposal by @tienifr. The plan sounds good in my opinion.

@tienifr 

Would you give it a quick look, checking whether your proposed solution is up-to-date after the merge of https://github.com/Expensify/App/issues/38050?

**Comment by cubuspl42** [comment] 2024-03-27 09:32
I approve the proposal by @tienifr

C+ reviewed 🎀 👀 🎀

**Comment by pecanoro** [comment] 2024-03-27 14:25
Sounds good, assigning @tienifr

**Comment by pecanoro** [comment] 2024-03-28 16:28
@Gonals Maybe you should post here the section of the doc since I think we don't grant access to entire docs unless an NDA is signed.

**Comment by Gonals** [comment] 2024-04-02 09:41
That's the section of the doc 😁.

I have added the related High level section too, for more context, but it doesn't really add much more.

**Comment by trjExpensify** [comment] 2024-04-02 11:16
Popping this on daily until a PR is up and linked to state otherwise. 👍

**Comment by trjExpensify** [comment] 2024-04-02 11:17
@tienifr does the OP now clarify your question. If not, can you ask here?

**Comment by trjExpensify** [comment] 2024-04-04 23:37
Just a heads up @tienifr that I made some minor copy changes in the mocks in the OP. 👍

**Comment by twisterdotcom** [comment] 2024-04-08 11:31
Is there a draft PR going here @tienifr?

**Comment by trjExpensify** [comment] 2024-04-08 22:40
Yeah, @tienifr can we get an ETA for this PR, please?

**Comment by trjExpensify** [comment] 2024-04-09 08:39
Amazing, thanks for confirming! ❤️

**Comment by trjExpensify** [comment] 2024-04-10 13:42
@tienifr do you have that PR up? Thanks!

**Comment by cubuspl42** [comment] 2024-04-17 09:25
@trjExpensify @tienifr 

Sorry for asking this late, but I think it's important...

> Also as per OP, the tooltip should be shown immediately once the shortcut item appears, not just on hover

For the educational tooltips we're discussing, do we want to show them on hover **at all** (on the desktop Web)?

**Comment by trjExpensify** [comment] 2024-04-17 09:48
That isn't a requirement for desktop/web, no. The idea is that the educational tooltip popover is visible when they open the create menu for the first time with a quick action button, and that's it really. CC: @dubielzyk-expensify

**Comment by Gonals** [comment] 2024-04-17 09:49
> @trjExpensify @tienifr
> 
> Sorry for asking this late, but I think it's important...
> 
> > Also as per OP, the tooltip should be shown immediately once the shortcut item appears, not just on hover
> 
> For the educational tooltips we're discussing, do we want to show them on hover **at all** (on the desktop Web)?

Nope. For our current needs, we do not need any on hover behavior

**Comment by dubielzyk-expensify** [comment] 2024-04-17 09:57
Agree with what, Tom said 👍

**Comment by cubuspl42** [comment] 2024-04-17 10:41
Thanks. It's quite important, as the existing `Tooltip` component is full of web-specific hover-specific code, which assumes the tooltip target (element the tooltip is pointing at) can be moving and resizing when the tooltip is displayed, while here, as I understand we want something cross-platform (including iOS / Android Native!) with relaxed requirements about dynamicity of the tooltip target.

We'll resume the technical discussion with @tienifr [on the PR thread](https://github.com/Expensify/App/pull/40066#discussion_r1568546316).

**Comment by dubielzyk-expensify** [comment] 2024-04-17 10:56
Yeah this is essentially a educational tooltip. Not tied to a user event but rather something we'd put up and point to a new thing we launched or similar. It should disappear on any event done by the user and it's position should still be able to be specified precisely. 

Here's a few examples from other apps:
![CleanShot 2024-04-17 at 20 55 25@2x](https://github.com/Expensify/App/assets/145416827/ef1b5219-b935-46b1-8f60-988814cb0495)

Though we don't have a X button as ours will like mentioned auto-disappear on any interaction done by the user.

**Comment by mallenexpensify** [comment] 2024-04-24 00:32
@eVoloshchak reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks. PR needs attention
- https://github.com/Expensify/App/pull/40066

**Comment by pecanoro** [comment] 2024-05-02 10:54
PR still under review

**Comment by eVoloshchak** [comment] 2024-05-13 12:22
Not overdue, [PR](https://github.com/Expensify/App/pull/40066) is still under review

**Comment by eVoloshchak** [comment] 2024-05-21 14:26
Not overdue, work is being done in https://github.com/Expensify/App/pull/40066

**Comment by eVoloshchak** [comment] 2024-05-29 21:33
Not overdue, work is being done in https://github.com/Expensify/App/pull/40066

**Comment by eVoloshchak** [comment] 2024-06-10 17:16
Not overdue, work is being done in https://github.com/Expensify/App/pull/40066

**Comment by twisterdotcom** [comment] 2024-06-20 13:26
Staging 14 hours ago Melv. Calm it down.

**Comment by twisterdotcom** [comment] 2024-06-28 09:46
Payment Summary:

- @eVoloshchak paid $250 through NewDot Manual Requests
- @tienifr paid $250 [here](https://www.upwork.com/nx/wm/offer/102911962) (Contributor)

**Comment by twisterdotcom** [comment] 2024-06-28 09:46
I don't think we need regression steps for this new feature.

**Comment by twisterdotcom** [comment] 2024-06-28 12:51
Ahh, thanks. updated: https://www.upwork.com/nx/wm/offer/102913747

**Comment by twisterdotcom** [comment] 2024-06-28 14:00
Paid

**Comment by JmillsExpensify** [comment] 2024-07-02 19:00
$500 approved for @eVoloshchak

**Comment by JmillsExpensify** [comment] 2024-07-09 17:22
Thanks! $500 approved for @tienifr

**Comment by mallenexpensify** [comment] 2024-07-10 00:51
Sorry @tienifr and @JmillsExpensify , you're gonna hate me.. 
@tienifr you were assigned on March 27 and I have your eligibility date as 2024-04-06, so we need to pay you via Upwork for this job.  (Internal details in [this SO ](https://stackoverflowteams.com/c/expensify/questions/7582/7583#7583:~:text=View%20the%20list%20of%20contributors%20who%20are%20paid%20via%20NewDot)and in this [pinned chat in #bug-zero](https://expensify.slack.com/archives/C01SKUP7QR0/p1719363450392939)) 

@tienifr can you please cancel your request for this job via NewDot payments , and accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01d37506ff0c4d2ad6

**Comment by mallenexpensify** [comment] 2024-07-11 23:53
@tienifr , I made a note on the below issue to not be paid to balance this out
- https://github.com/Expensify/App/issues/36778#issuecomment-2224131113

can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~01d37506ff0c4d2ad6

**Comment by mallenexpensify** [comment] 2024-07-15 21:15
Contributor: @tienifr paid $500 via Upwork (also paid via NewDot, which will balanced out by [this issue ](https://github.com/Expensify/App/issues/36778#issuecomment-2224131113)not being paid) 

@cubuspl42 are you due payment? I see you reviewed the PR but don't see a ✔️ next to your name in the upper right corner here
https://github.com/Expensify/App/pull/40066#pullrequestreview-1996304064

**Comment by twisterdotcom** [comment] 2024-07-17 20:24
@cubuspl42 I see hasn't responded yet. Can we close and just reopen if needed?

**Closed** 2024-07-19 00:18 UTC
Labels: External, Engineering, Weekly, NewFeature, Awaiting Payment

**Comment by cubuspl42** [comment] 2024-07-21 10:01
Sorry for the late response. No payment is needed.
