### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] App crashes after changing default contact method

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19611] opened 2023-05-25 14:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

Precondition: You should have an account with more than one contact methods set up and should have a money request threads

## Action Performed:

1. Go to settings > Profile > Contact method
2. Change the current default contact method
3. Open an IOU thread from the LHN
4. Click on the IOU card to open the thread
5. Go to settings > Profile > Contact method
6. Change the current default contact method to the previous one

## Expected Result:
App should not crash
## Actual Result:
App crashes

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.18-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c60daab5-6c59-4064-adc1-dcfbcb5bb1a2

https://github.com/Expensify/App/assets/43996225/0730e23b-bc81-4657-a655-fd9dcae8b4a8

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684833850028879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015600b3c5d6d8f7f3</li>
        <li>Upwork Job ID: 1661995758902030336</li>
        <li>Last Price Increase: 2023-05-26</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-25 17:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after changing default contact method 
### What is the root cause of that problem?
When user change the default contact methods, even the reportRecipient is undefined,  `shouldShowReportRecipientLocalTime` return true. 
<img width="547" alt="Screen Shot 2023-05-25 at 22 53 57" src="https://github.com/Expensify/App/assets/16502320/ccbd7a03-d1f3-44a0-acd3-0d0e864b2284">
The problem came from here:
https://github.com/Expensify/App/blob/0f33e2c22bb3670e7c47d78f2f3c604f3af29ca3/src/libs/ReportUtils.js#L620-L634
and here:
 https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/pages/home/report/ReportActionCompose.js#L906-L908
When user change their default contact method, `sessionEmail` get updated to new contact method email, mean while `this.props.currentUserPersonalDetails.login` is still the old email.
<img width="553" alt="Screen Shot 2023-05-26 at 00 31 13" src="https://github.com/Expensify/App/assets/16502320/481d0365-b3a2-4064-87df-4d10d7fd6b41">
Because of that, when user changed their contact methods, in some case even the `reportRecipient` inside `ReportActionCompose` was undefined, `shouldShowReportRecipientLocalTime` is true, which make `ParticipantLocalTime` rendered, it will lead to crash since we don't have a safe way to get value:
https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/pages/home/report/ParticipantLocalTime.js#L56
### What changes do you think we should make in order to solve the problem?

We should use the same email for to calculate the `reportParticipants` inside `ReportActionCompomse` and `canShowReportRecipientLocalTime`. Let say that we should use `sessionEmail`.
```javascript
// Report Action Compose
 const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), this.props.sessionEmail);
```
We also should use lodashGet to get user name inside `ParticipantLocalTime`
```javascript
const reportRecipientDisplayName = lodashGet(this.props, "participant.firstName") || lodashGet(this.props, "participant.displayName")
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by hungvu193** [comment] 2023-05-25 17:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes after changing default contact method 
### What is the root cause of that problem?
When user change the default contact methods, even the reportRecipient is undefined,  `shouldShowReportRecipientLocalTime` return true. 
<img width="547" alt="Screen Shot 2023-05-25 at 22 53 57" src="https://github.com/Expensify/App/assets/16502320/ccbd7a03-d1f3-44a0-acd3-0d0e864b2284">
The problem came from here:
https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/libs/ReportUtils.js#L622
and here:
 https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/pages/home/report/ReportActionCompose.js#L906-L908

We are using difference email variable between `ReportActionCompose` and `canShowReportRecipientLocalTime`. When user changeed their default contact method, `sessionEmail` got updated to new contact method email, mean while `this.props.currentUserPersonalDetails.login` was still the old email.
<img width="553" alt="Screen Shot 2023-05-26 at 00 31 13" src="https://github.com/Expensify/App/assets/16502320/481d0365-b3a2-4064-87df-4d10d7fd6b41">
Because of that, when user changed their contact methods, in some case even the `reportRecipient` inside `ReportActionCompose` was undefined and `shouldShowReportRecipientLocalTime` is true, which make `ParticipantLocalTime` rendered, it will lead to crash since we don't have a safe way to get value:
https://github.com/Expensify/App/blob/63f314c054d82ad0ee5e59ec5349d9b35d656bea/src/pages/home/report/ParticipantLocalTime.js#L56
### What changes do you think we should make in order to solve the problem?

We should use the same email for to calculate the `reportParticipants` inside `ReportActionCompomse` and `canShowReportRecipientLocalTime`. Let say that we should use `sessionEmail`.
```javascript
// Report Action Compose
 const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), this.props.sessionEmail);
```
We also should use lodashGet to get user name inside `ParticipantLocalTime`
```javascript
const reportRecipientDisplayName = lodashGet(this.props, "participant.firstName") || lodashGet(this.props, "participant.displayName")
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by greg-schroeder** [comment] 2023-05-26 07:04
Reviewing

**Comment by greg-schroeder** [comment] 2023-05-26 07:15
Hmm - I reproduced the crash just by changing the default contact method alone. @Natnael-Guchima @kavimuru - are the IOU steps required for reproduction?

**Comment by greg-schroeder** [comment] 2023-05-26 07:23
Hey look at that, @allroundexperts you're a C+ now! Dope. :) Lemme know what you think about @hungvu193's proposal above

**Comment by hungvu193** [comment] 2023-05-26 11:47
> @hungvu193 Thanks for your proposal. Your RCA seems correct but I think the proposed solution isn't catering the root cause that you defined. It's just hiding the fact that `this.props.currentUserPersonalDetails.login` does not update when the contact method changes. I'm more interested in finding why `this.props.currentUserPersonalDetails.login` doesn't update when changing the default contact method and fixing it. Although, once fixed, I agree that we should use the same email variable at both places.

@allroundexperts Thanks for your feedback. Yeah, problem came from the way we set our optimisticData when we changed default contact methods.
```javascript
    const optimisticData = [
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.SESSION,
            value: {
                email: newDefaultContactMethod,
            },
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.LOGIN_LIST,
            value: {
                [newDefaultContactMethod]: {
                    pendingFields: {
                        defaultLogin: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
                    },
                    errorFields: {
                        defaultLogin: null,
                    },
                },
            },
        },
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: ONYXKEYS.PERSONAL_DETAILS,
            value: {
                [newDefaultContactMethod]: {
                    ...myPersonalDetails,
                    login: newDefaultContactMethod,
                    displayName: PersonalDetails.getDisplayName(newDefaultContactMethod, myPersonalDetails),
                },
                [oldDefaultContactMethod]: null,
            },
        },
    ];
```
As we can see the optimisticData, we updated the session email first that will trigger the `withCurrentUserPersonalDetails`HOC.
https://github.com/Expensify/App/blob/ec9bc04108992ff400b3fb86d8a31091d727310e/src/components/withCurrentUserPersonalDetails.js#L39-L41
While the email session is new email, the new contact methods email detail is added to the `ONYXKEYS.PERSONAL_DETAILS` yet, that will make 2 email from `ReportActionCompose` and  `canShowReportRecipientLocalTime` have difference values as I said.

**Comment by hungvu193** [comment] 2023-05-26 11:55
@allroundexperts  Sure, I updated my proposal https://github.com/Expensify/App/issues/19611#issuecomment-1563277027

**Comment by hungvu193** [comment] 2023-05-26 14:07
We can go to any report, that no need to be thread and log the value of `props.personalDetails[currentUserEmail]` inside `WithCurrentUserPersonalDetails` while changing contact method, we'll always see the value of it turned into `undefined` first (as I explained in my proposal). Anyway, the `currentUserPersonalDetails` is not really needed for the ReportActionCompose, we should use one email variable for both place (ReportActionCompose and inside canShowReportRecipientLocalTime).

https://github.com/Expensify/App/assets/16502320/319693aa-c9f4-4595-8125-ae0fec912714


https://github.com/Expensify/App/assets/16502320/22fbf480-447e-4583-8391-5e06e1065c5a

**Comment by dukenv0307** [comment] 2023-05-29 11:35
> Although, once fixed, I agree that we should use the same email variable at both places.

@allroundexperts @hungvu193  Hi, just wanna weigh in here. I don't think "same email" fixes the root cause since if you apply "same email" in both places, it will still crash. The part of @hungvu193 that makes it not crash is the `lodashGet` usage, which might hide the issue rather than fixing it.

Hope this helps 👍

**Comment by dukenv0307** [comment] 2023-05-29 11:55
@allroundexperts yes I did.

Since this is due to the update to `session.email` in Onyx happen before the `personalDetails` update, causing the `personalDetails[session.email]` record to be undefined, what I think is a good fix for the root cause is to reorder the Onyx update such that `personalDetails` is updated first and `personalDetails[session.email]` will always has correct result (never undefined).

Current:
- Update session.email
- Update personalDetails with new key `session.email`

After fix:
- Update personalDetails with new key of the to-be `session.email`
- Update `session.email` (at this time the `personalDetails` is already updated, so there'll be no crash)
- Optional - We can even make it more non-disruptive by ensuring that the old `email` key in `personalDetails` is only removed after the `session.email` is updated, at this step

I tested and it works well, if @allroundexperts thinks this is a promising approach that we can explore, I'm happy to create a proposal for it.

**Comment by dukenv0307** [comment] 2023-05-29 12:31
ok so I was testing it according to the original suggestion from @hungvu193 's proposal and it still crashes. I tested it by replacing [this line](https://github.com/allroundexperts/Expensify/blob/12d2f3c89de6c0271ae90760de816e198d3e9025/src/pages/home/report/ReportActionCompose.js#L906)
with 
```
const reportParticipants = _.without(lodashGet(this.props.report, 'participants', []), this.props.session.email);
```

@allroundexperts  Your changes [here](https://github.com/Expensify/App/issues/19611#issuecomment-1567043347) does make the crash go away but it's due to another coincidence:
1. [This line](https://github.com/Expensify/App/blob/0c44fedc3223b4ad1c6d87c0507a2808e8aa55af/src/libs/ReportUtils.js#L620) is supposed to exclude the current user from the list of `participants`
2. Since the `email` passed in will become `undefined` for some time when changing the default contact method, the logic in 1 will not work as intended and it will include the current user in the list of `participants` 😅
3. Then the `reportRecipient` [here](https://github.com/Expensify/App/blob/0c44fedc3223b4ad1c6d87c0507a2808e8aa55af/src/libs/ReportUtils.js#L623) becomes undefined because the current user doesn't yet exist in the `personalDetails`, making the `canShowReportRecipientLocalTime` false and thus avoiding the crash

The above can easily be verified by adding some logs to the `canShowReportRecipientLocalTime` function, so I can say it "accidentally" avoids the crash by making the function not working correctly (see 2) rather than fixing the root cause which is to make sure the `session.email` and `currentUserPersonalDetails.login` always consistent with each other.

With that said, @allroundexperts would you be interested in a potential solution [here](https://github.com/Expensify/App/issues/19611#issuecomment-1567039269), that can make `session.email` and `currentUserPersonalDetails.login` always consistent?

**Comment by hungvu193** [comment] 2023-05-29 12:44
Wait, why the email is sometimes indefined since it's always added in iptimistic data?? Can you explain?

**Comment by dukenv0307** [comment] 2023-05-29 15:50
The outline of the solution is [here](https://github.com/Expensify/App/issues/19611#issuecomment-1567039269), I'll post a full proposal tomorrow after in-depth testing!

**Comment by hungvu193** [comment] 2023-05-30 11:33
> We need to reorder the optimisticData here
> 
> https://github.com/Expensify/App/blob/8afd126ec4443a983f9bd9eb922461c3eab31a58/src/libs/actions/User.js#L773
> 
> so that the `ONYXKEYS.PERSONAL_DETAILS` update comes first, before the `ONYXKEYS.SESSION` update. This will make sure that once `session.email` is updated, the `personalDetails` already contains the key for `session.email` and `personalDetails[session.email]` never undefined.

This didn't work, `personalDetails` is updated, and also the `oldDefaultContactMethod` is set to null. This still lead to undefined value.
<img width="577" alt="Screenshot 2023-05-30 at 18 33 08" src="https://github.com/Expensify/App/assets/16502320/a73390c5-aadd-4fbd-ba8b-a23902d16286">


The alternative broke the Onyx Merge method, which is originally batched.
```
Calls to Onyx.merge() are batched so that any calls performed in a single tick will stack in a queue and get applied in the order they were called. Note: Onyx.set() calls do not work this way so use caution when mixing
```

**Comment by greg-schroeder** [comment] 2023-05-30 11:59
Just to make sure I'm clear here @allroundexperts - are we still going with @hungvu193's proposal or are we still in the process of evaluating the right approach?

**Comment by greg-schroeder** [comment] 2023-05-30 18:34
@NikkiWines thoughts on the above?

**Comment by NikkiWines** [comment] 2023-05-31 01:43
Sorry, didn't get to this today but will review first thing tomorrow 🙇

**Comment by NikkiWines** [comment] 2023-06-01 01:48
Sorry for the delay here, I agree with @allroundexperts. @hungvu193's proposal makes sense and I agree we shouldn't rely on re-ordering the onyx updates to resolve this issue.

**Comment by greg-schroeder** [comment] 2023-06-05 15:25
This PR is merged

**Comment by greg-schroeder** [comment] 2023-06-12 16:19
Offers sent to @allroundexperts, @hungvu193, @Natnael-Guchima

**Comment by Natnael-Guchima** [comment] 2023-06-12 16:21
I have accepted the offer. Thanks, @greg-schroeder.

**Comment by greg-schroeder** [comment] 2023-06-14 14:21
Friendly bump on the checklist! :)

**Comment by greg-schroeder** [comment] 2023-06-18 18:34
Sounds good. Created regression test issue.

**Closed by greg-schroeder** 2023-06-18 18:34 UTC
Labels: External, Daily, Bug
