### ISSUE TITLE
[$250] Address - Country field reverts to the previous selection after selecting a new state

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44957] opened 2024-07-08 13:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Profile
3. Click Address
4. Click Country
5. Select a country
6. Enter a US address and select any US address
7. Click State
8. Select a different state

## Expected Result:
The country field will not revert to the previous selection after selecting a new state

## Actual Result:
The country field reverts to the previous selection after selecting a new state

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/18e3987e-6633-4cc7-85d8-b865ca69a7fc

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114854c60bfc7069c</li>
        <li>Upwork Job ID: 1810317607567373547</li>
        <li>Last Price Increase: 2024-07-08</li>
<li>Automatic offers: </li>
<ul>
<li>hoangzinh | Contributor | 103031606</li>
<li>nkdengineer | Contributor | 103032506</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>

**Comment by lanitochka17** [comment] 2024-07-08 13:17
@lakchote  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-07-08 13:17
We think that this bug might be related to #vip-vsp

**Comment by Julesssss** [comment] 2024-07-08 13:22
I see no obvious cause in our [checklist](https://github.com/Expensify/App/issues/44947) so far...

**Comment by lakchote** [comment] 2024-07-08 14:13
I found the culprit, it's https://github.com/Expensify/App/pull/43348

cc @mountiny

**Comment by lakchote** [comment] 2024-07-08 14:22
I've talked with @mountiny on the matter, refactoring was difficult to undertake, as such we should try to find the issue and fix. Which is why I've made it `External`.

**Comment by nkdengineer** [comment] 2024-07-08 15:06
@lakchote @mountiny  I'm happy to raise PR asap if assigned

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The country field reverts to the previous selection after selecting a new state

### What is the root cause of that problem?
In https://github.com/Expensify/App/blob/e7a46a5382291582e5b8816c9cab508fadcec6cf/src/components/StateSelector.tsx#L92, we use `getActiveRoute`, not `getActiveRouteWithoutParams` like in CountrySelector https://github.com/Expensify/App/blob/e7a46a5382291582e5b8816c9cab508fadcec6cf/src/components/CountrySelector.tsx#L78

So the param of the old country left over in the route param is still used, and the country gets updated to the old value.

### What changes do you think we should make in order to solve the problem?

In StateSelector here https://github.com/Expensify/App/blob/e7a46a5382291582e5b8816c9cab508fadcec6cf/src/components/StateSelector.tsx#L92, use `getActiveRouteWithoutParams` like in CountrySelector https://github.com/Expensify/App/blob/e7a46a5382291582e5b8816c9cab508fadcec6cf/src/components/CountrySelector.tsx#L78

### What alternative solutions did you explore? (Optional)

**Comment by Julesssss** [comment] 2024-07-08 15:16
Jumping in to speed up the deploy fixes. 

Thank you @nkdengineer, please go ahead with this fix.

**Comment by nkdengineer** [comment] 2024-07-08 15:22
Working on it

**Comment by nkdengineer** [comment] 2024-07-08 15:38
@Julesssss this [PR](https://github.com/Expensify/App/pull/44981) is ready for review

**Comment by Julesssss** [comment] 2024-07-08 16:01
Thanks. @hoangzinh I have assigned you

**Comment by mountiny** [comment] 2024-07-08 21:07
This was CPed so removed the label

**Comment by mountiny** [comment] 2024-07-09 21:26
@nkdengineer We had to revert your change here https://github.com/Expensify/App/pull/45121 as as it led to worse [blocker](https://github.com/Expensify/App/issues/45060).

Lets find a proper solution for this issue and make sure https://github.com/Expensify/App/issues/45060 is not brought back. cc @mateuuszzzzz can help maybe

**Comment by mountiny** [comment] 2024-07-10 15:02
@nkdengineer lets try to identify the root cause as @s77rt highlighted it seems like we are still not clear on that

**Comment by zfurtak** [comment] 2024-07-15 13:28
hi there 😊 after investigation, me and @mateuuszzzzz came to a conclusion that the problem here is connected to navigation. 🤔
Function `getActiveRoute()` was returning wrong path (with previously selected country) and the result was being passed to `backTo` param.
I made a [PR with a fix for that problem](https://github.com/Expensify/App/pull/45394). 👩🏽‍💻

**Comment by mountiny** [comment] 2024-07-20 00:13
Thank you! PR merged

**Comment by mvtglobally** [comment] 2024-08-03 04:08
Issue not reproducible during KI retests. (First week)

**Comment by puneetlath** [comment] 2024-08-05 15:22
@mountiny can you help me understand what needs to happen here. I see that both @s77rt and @hoangzinh reviewed [this PR](https://github.com/Expensify/App/pull/45394). Do they both need to be paid?

**Comment by s77rt** [comment] 2024-08-05 17:04
@puneetlath Only @hoangzinh is due payment

**Comment by puneetlath** [comment] 2024-08-05 17:11
Got it! @hoangzinh has been paid. 

@mountiny is @nkdengineer due any payment here?

**Comment by puneetlath** [comment] 2024-08-06 15:03
Ok going to go ahead and close this out then. Thanks everyone!

**Closed by puneetlath** 2024-08-06 15:03 UTC
Labels: Reviewing, External, Engineering, Weekly, Help Wanted, Bug

**Comment by mountiny** [comment] 2024-08-08 00:57
Thanks for handling
