### ISSUE TITLE
[PAID] [$1000] Web- Attachment - Up and down arrow key does not work for scrolling PDF file.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#10824] opened 2022-09-05 17:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensifail.com
2. Log in with expensifail account
3. Select any user
4. Click the plus button to the left of the message input, and select "Add attachment"
5. Select a password-protected PDF
6. Verify that the password form appears
7. Enter the password and Click Confirm
8. Use up and down key for scrolling the issue

## Expected Result:
Up and down arrow key works for scrolling PDF file.

## Actual Result:
Up and down arrow key does not work for scrolling PDF file.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.97.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/188494383-1249d286-81b6-4436-b652-5000fb8c5768.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-09-07 14:28
Yeah, I was able to reproduce this, it happens mostly when previewing the attachment before sending it.

**Comment by JmillsExpensify** [comment] 2022-09-12 19:04
Missed this in the end of offshore shuffle. Posting now.

**Comment by JmillsExpensify** [comment] 2022-09-12 19:06
Upwork job created here: https://www.upwork.com/jobs/~0135398a55eee993ef. We're open for proposals.

**Comment by andrewlor** [comment] 2022-09-15 00:43
# Proposal

## Problem
The scrollable pdf container is not focusable because `tabIndex=-1` by default. In order to scroll using the arrow keys, you have to click the container first.

## Solution
In order to programatically focus the pdf container, we'll add a ref. Then in the callback for successfully loading the pdf, set the `tabIndex=0` and call `.focus()`.
https://github.com/Expensify/App/blob/ddd34f8945d7cd74b03373b38bac6e9634d9de34/src/components/PDFView/index.js#L48-L54
```diff
    onDocumentLoadSuccess({numPages}) {
        this.setState({
            numPages,
            shouldRequestPassword: false,
            isPasswordInvalid: false,
        });

+       this.pdfContainer.tabIndex = 0;
+       this.pdfContainer.focus();
    }
```
https://github.com/Expensify/App/blob/ddd34f8945d7cd74b03373b38bac6e9634d9de34/src/components/PDFView/index.js#L120-L156
```diff
                <View
                    style={pdfContainerStyle}
                    onLayout={event => this.setState({windowWidth: event.nativeEvent.layout.width})}
+                   ref={node => this.pdfContainer = node}
                >
```

## Result

https://user-images.githubusercontent.com/8475244/190286395-f4d69d80-8503-48e5-b2c9-74a627e4168d.mp4

**Comment by Santhosh-Sellavel** [comment] 2022-09-19 15:00
Reviewing this now!

**Comment by Santhosh-Sellavel** [comment] 2022-09-19 15:18
@andrewlor

When you open a pdf that is already received, after clicking on it we are able to scroll using the up/arrow. But why isn't working while sending alone?

Can you check on that, we don't want to auto set focus.

**Comment by andrewlor** [comment] 2022-09-20 20:38
@Santhosh-Sellavel

Interesting findings: I believe you're only unable to scroll a new PDF if you have opened an existing PDF sent in the chat. So it may have to do with the fact that there are multiple PDFView components rendered.

Before I was not actually recreating the bug, I just misunderstood and thought we wanted to avoid the extra click before scrolling with arrow keys.

As you can see in this video:
1. If there is no existing PDF in the chat, I can scroll while uploading a new PDF
2. If there is an existing PDF in the chat, but I haven't opened it, I can still scroll while uploading a new PDF
3. However if I open an existing PDF in the chat and scroll it, can't scroll while uploading a new PDF

https://user-images.githubusercontent.com/8475244/191359431-2400d7f4-2d64-45b4-b0db-2da8e34b31e3.mp4

I'll continue looking into this and come back with an updated proposal.

**Comment by Santhosh-Sellavel** [comment] 2022-09-21 19:31
Yeah Sounds good! @andrewlor

**Comment by andrewlor** [comment] 2022-09-21 20:03
@Santhosh-Sellavel What do you think about setting the tabindex, but not auto focusing? This seems to solve the issue as you can see below, I'm just setting `tabIndex = -1` manually in the console on the scrollable div wrapping the pdf document.

https://user-images.githubusercontent.com/8475244/191598371-6d906744-af62-40b8-b3b8-a4cbd70905d8.mp4

This behaviour can be explained here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
> A negative value (usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation, but could be focused with JavaScript or visually by clicking with the mouse.

So my updated proposal's code change would be:
https://github.com/Expensify/App/blob/ddd34f8945d7cd74b03373b38bac6e9634d9de34/src/components/PDFView/index.js#L48-L54
```diff
    onDocumentLoadSuccess({numPages}) {
        this.setState({
            numPages,
            shouldRequestPassword: false,
            isPasswordInvalid: false,
        });

+       this.pdfContainer.tabIndex = -1;
    }
```
https://github.com/Expensify/App/blob/ddd34f8945d7cd74b03373b38bac6e9634d9de34/src/components/PDFView/index.js#L120-L156
```diff
                <View
                    style={pdfContainerStyle}
                    onLayout={event => this.setState({windowWidth: event.nativeEvent.layout.width})}
+                   ref={node => this.pdfContainer = node}
                >
```

**Comment by JmillsExpensify** [comment] 2022-09-26 13:58
@Santhosh-Sellavel Checking in. Will you be able to review Andrew's proposal above in the coming days?

**Comment by Santhosh-Sellavel** [comment] 2022-09-28 19:58
Sorry for the delay @andrewlor 

But this kind of sound's like a workaround

**Comment by JmillsExpensify** [comment] 2022-10-03 17:35
Given that we're still waiting for an approved proposal, I'm going to double the price of this issue.

**Comment by JmillsExpensify** [comment] 2022-10-03 17:38
[Posted](https://expensify.slack.com/archives/C01GTK53T8Q/p1664818705006809) in Slack for visibility as well.

**Comment by JmillsExpensify** [comment] 2022-10-05 23:06
Still waiting for proposals.

**Comment by neil-marcellini** [comment] 2022-10-11 16:06
Waiting for proposals. Let's look into why "you're only unable to scroll a new PDF if you have opened an existing PDF sent in the chat" as @andrewlor mentioned here https://github.com/Expensify/App/issues/10824#issuecomment-1252886009.

**Comment by JmillsExpensify** [comment] 2022-10-12 14:59
Sounds great. In the meantime, I'm going to double the price of the issue.

**Comment by JmillsExpensify** [comment] 2022-10-14 03:19
Still waiting on proposals

**Comment by mollfpr** [comment] 2022-10-15 08:40
### Proposal

**RCA**

**Comment by mollfpr** [comment] 2022-10-15 09:37
### Proposal

**RCA**

https://user-images.githubusercontent.com/25520267/195977800-a22c31a9-abb6-44f6-8d5b-626fc90f0fea.mov

After closing the attachment modal from the report chat, something is setting the `tabindex` of `<body>` to `-1`.




https://user-images.githubusercontent.com/25520267/195978131-e97a899f-d142-4f9c-8f66-0416b37f6267.mov

As you can see here, with the `tabindex=-1` on the `<body>` trying to scroll the pdf with the arrow key makes the focus move to the button. But after I remove the `tabindex=-1` from the `<body>` tag and try to scroll the pdf file with the arrow key, it's working.

---

Some things still not clear to me is:
1. What setting the `tabindex=-1` to the `<body>` tag
2. Why is the scroll of pdf  report chat still working

The answer for number 1 might be from `react-native-web`. `react-native-modal` is using native `Modal` from RN, so the `Modal` component for the web must come from RNW. Also, RNW doing a lot of things to handle the accessibility and have the modal focus trap on the modal logic.

**Solution**
My solution is to remove the `tabindex=-1` from the `<body>` after the modal is hidden. 
```diff
diff --git a/src/components/Modal/index.js b/src/components/Modal/index.js
index add8feef0..4b95080f9 100644
--- a/src/components/Modal/index.js
+++ b/src/components/Modal/index.js
@@ -42,6 +42,12 @@ class Modal extends Component {
                 ref={el => this.baseModalRef = el}
                 // eslint-disable-next-line react/jsx-props-no-spreading
                 {...this.props}
+                onModalHide={() => {
+                    setTimeout(() => {
+                        document.querySelector('body').removeAttribute('tabindex');
+                    });
+                    this.props.onModalHide();
+                }}
             >
                 {this.props.children}
             </BaseModal>
```

**Result**

https://user-images.githubusercontent.com/25520267/195979601-99cae183-59d8-4efc-a475-f266fa4b105a.mov

**Comment by neil-marcellini** [comment] 2022-10-17 18:09
I think we probably want a solution without `setTimeout`. Let's not use a workaround fix.

**Comment by Santhosh-Sellavel** [comment] 2022-10-17 18:09
We should start with this?
> What setting the tabindex=-1 to the <body> tag

We don't prefer proposals with setTimeout.

**Comment by Santhosh-Sellavel** [comment] 2022-10-17 18:10
@neil-marcellini I was typing the same! 😃

**Comment by mollfpr** [comment] 2022-10-18 09:08
### Proposal

> What setting the tabindex=-1 to the tag

I found the answer to this. Is set from RNW on `UIManager.focus` from `ModalFocusTrap`. The comment about setting `tabindex=-1` is:
```
// A tabIndex of -1 allows element to be programmatically focused but
      // prevents keyboard focus, so we don't want to set the value on elements
      // that support keyboard focus by default.
```

Also on Firefox when we open second time the uploaded PDF and try to scroll with the arrow key, we need to click twice to make it work. 

https://user-images.githubusercontent.com/25520267/196378126-47aaefa5-6922-47ce-b29f-44c147735251.mov

https://github.com/Expensify/react-native-web/blob/154f2cc6096372b451fa4c9ebff2ad24710f70ec/packages/react-native-web/src/exports/UIManager/index.js#L60

https://github.com/Expensify/react-native-web/blob/154f2cc6096372b451fa4c9ebff2ad24710f70ec/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L144-L156

We also not seeing the `tabindex=-1` to `<body>` when closing the send attachment modal mostly because the `lastFocusedElementOutsideTrap` value is the composer input.  The `UIManager.focus` will skip `node.setAttribute('tabIndex', '-1')` because `INPUT` is on the exceptional list.
```
var focusableElements = {
  A: true,
  INPUT: true,
  SELECT: true,
  TEXTAREA: true,
};
```

On the other hand, when we try open the attachment from the chat list, the `lastFocusedElementOutsideTrap` is `<body>` so that's why at the end the `tabindex=-1` to `<body>`.

> Why is the scroll of pdf report chat still working

On the uploaded PDF, there's no button inside the modal so when we use the arrow key, the focus stays on the `<body>`. While on the upload modal view there's a button `Confirm` and when we use the arrow key, the focus is moved to the button.


**Solution**
Couple of things we can do to solve this:
1. Removing the `tabindex` from `<body>` when the modal is open
```diff
diff --git a/src/components/AttachmentModal.js b/src/components/AttachmentModal.js
index bac249e87..6876c2faf 100755
--- a/src/components/AttachmentModal.js
+++ b/src/components/AttachmentModal.js
@@ -90,6 +90,13 @@ class AttachmentModal extends PureComponent {
         this.updateConfirmButtonVisibility = this.updateConfirmButtonVisibility.bind(this);
     }
 
+    componentDidUpdate(prevProps, prevState) {
+        if (prevState.isModalOpen === this.state.isModalOpen || !this.state.isModalOpen) {
+            return;
+        }
+        document.body.removeAttribute('tabindex');
+    }
+
     /**
      * If our attachment is a PDF, return the unswipeable Modal type.
      * @param {String} sourceUrl
```

2. Updating our RNW fork and adding `BODY` to `focusableElements` on the RNW `UIManager` function. In this way, it will skip adding the `tabindex=-1` to `<body>` on `ModalFocusTrap`.
https://github.com/Expensify/react-native-web/blob/154f2cc6096372b451fa4c9ebff2ad24710f70ec/packages/react-native-web/src/exports/UIManager/index.js#L36-L41
```diff
var focusableElements = {
  A: true,
  INPUT: true,
  SELECT: true,
  TEXTAREA: true,
+  BODY: true
};
```


### Result
**Solution 1**

https://user-images.githubusercontent.com/25520267/196384733-fadae50d-178a-4502-b7c6-2b22ae8e70dd.mov

**Solution 2**


https://user-images.githubusercontent.com/25520267/196387598-3a97eac4-2dea-4efc-8bb5-026f396a444b.mov

**Comment by neil-marcellini** [comment] 2022-10-19 23:33
@Santhosh-Sellavel what do you think of the proposal above?

**Comment by neil-marcellini** [comment] 2022-10-24 18:53
@Santhosh-Sellavel Bump

**Comment by Santhosh-Sellavel** [comment] 2022-10-25 20:26
@neil-marcellini 
Solution 2 looks good to me, but I am open to your thoughts also on this one!

**Comment by JmillsExpensify** [comment] 2022-10-26 17:01
Ok @neil-marcellini @Santhosh-Sellavel - let's close the loop on this one. Looks like we're going with @mollfpr's proposal above? If so, let's assign the Contributor to this issue and I'll hire via Upwork.

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 17:53
Sorry, @JmillsExpensify @neil-marcellini I would like to dig further on this one, ignore my comment [here](https://github.com/Expensify/App/issues/10824#issuecomment-1291096980) for now.

**Comment by neil-marcellini** [comment] 2022-10-26 18:24
Also, let's make sure we're all on the same page about the bug we are trying to solve. As I understand it this is the problem.
## Action Performed:
Sign into NewDot with any account
Select a chat with any user
Click the plus button to the left of the message input, and select "Add attachment"
Select a PDF
Click send
After the PDF uploads, click to open it
Close it (notice that `tabIndex=-1` on the body html element)
Click the plus button to the left of the message input, and select "Add attachment"
Select a PDF
Click on it
Click the down arrow key to scroll the PDF down

## Expected Result:
The PDF scrolls down

## Actual Result:
The PDF does not scroll down


https://user-images.githubusercontent.com/26260477/198105956-3d1910b6-82dc-4ca0-8b1e-4f34344f29b9.mov

**Comment by mollfpr** [comment] 2022-10-26 18:36
@neil-marcellini I think we can't. We used `PressableWithoutFocus` which blurs the element before calling the `onPress` and the blurs set the last focus to `<body>`.

We could replace `PressableWithoutFocus` with regular `Pressable` but I'm afraid it will create [regression](https://github.com/Expensify/App/issues/7596).

**Comment by mollfpr** [comment] 2022-10-26 18:40
Another thing we can do is set `<body>` to have `tabindex="0"`. It will prevent setting the element `tabindex="1"`.
https://github.com/Expensify/react-native-web/blob/154f2cc6096372b451fa4c9ebff2ad24710f70ec/packages/react-native-web/src/exports/UIManager/index.js#L52-L62

**Comment by neil-marcellini** [comment] 2022-10-31 20:56
Hey @mollfpr @Santhosh-Sellavel I'm having a hard time figuring out what the best way forward is here.

I don't want to go for solution 1 above because I think that the tabIndex should be -1 on the body so that the focus is trapped in the modal. For solution 2, I don't think the body should be keyboard focusable.

Could you please give me a breakdown of how the focus is working through each of these steps? Also, when we click the PDF in step 10 why is it not focused?

> 1. Sign into NewDot with any account
> 2. Select a chat with any user
> 3. Click the plus button to the left of the message input, and select "Add attachment"
> 4. Select a PDF
> 5. Click send
> 6. After the PDF uploads, click to open it
> 7. Close it (notice that `tabIndex=-1` on the body html element)
> 8. Click the plus button to the left of the message input, and select "Add attachment"
> 9. Select a PDF
> 10. Click on it
> 11. Click the down arrow key to scroll the PDF down

**Comment by mollfpr** [comment] 2022-11-01 07:55
>Could you please give me a breakdown of how the focus is working through each of these steps? Also, when we click the PDF in step 10 why is it not focused?

Sure!

- From steps 1 to 5 there's no tab index set to the `<body>` tag.
- In step 6, we used `PressableWithoutFocus` for the handle user pressed on the attachment report. So when the user clicks the attachment, it will blur first then open the modal. When blurring the last focused element trapped is `<body>`.
- In step 7, from step 6 the last focused element trapped is `<body>` the `UIManager.focus` will set `tabindex=-1` to the `<body>`.
- In steps 8 to 11, the tab index of `<body>` is already `-1`.
- In step 10, the focus element is the modal wrapper. But if we try to send the attachment before the tab index is set to `-1` to `<body>` tag, the focus element when clicking on the document is the `<body>`
- In step 11, when we use the arrow key, the focus is moved to the confirm button where it should be focused on the `<body>` or to the parent element that has `tabindex="0"`

I also notice that the `tabindex=-1` in the `<body>` tag behaves differently on different browsers when clicking on the element and scrolling with the arrow key. 

On Chrome and Safari, after focusing on another element (download button) then clicking the pdf and pressing the arrow key, it will scroll the document.

On Firefox, after focusing on another element (download button) and then clicking the pdf and pressing the arrow key, it will not scroll the document, instead, we need to click again on the document and the scroll with the arrow key will work.

https://user-images.githubusercontent.com/25520267/199179802-2bd918f6-f34c-47dc-aac1-aaaf19a3db9f.mov

**Comment by mollfpr** [comment] 2022-11-01 07:55
### Proposal
Another solution I suggest is adding `focusable` props to the `View` wrapper of the `PDFDocument` element. So we can use the keyboard navigation on pdf content.

```diff
diff --git a/src/components/PDFView/index.js b/src/components/PDFView/index.js
index b4c9079ca..137c87b70 100644
--- a/src/components/PDFView/index.js
+++ b/src/components/PDFView/index.js
@@ -114,14 +114,15 @@ class PDFView extends Component {
         // If we're requesting a password then we need to hide - but still render -
         // the PDF component.
         const pdfContainerStyle = this.state.shouldRequestPassword
-            ? [styles.PDFView, this.props.style, styles.invisible]
-            : [styles.PDFView, this.props.style];
+            ? [styles.PDFView, styles.noSelect, this.props.style, styles.invisible]
+            : [styles.PDFView, styles.noSelect, this.props.style];
 
         return (
             <View style={outerContainerStyle}>
                 <View
                     style={pdfContainerStyle}
                     onLayout={event => this.setState({windowWidth: event.nativeEvent.layout.width})}
+                    focusable
                 >
                     <Document
                         loading={<FullScreenLoadingIndicator />}
```

**Chrome**

https://user-images.githubusercontent.com/25520267/199183893-87a7ded9-dc87-42a9-81ab-d29de377c18d.mp4



**Safari**

https://user-images.githubusercontent.com/25520267/199185586-292c22ee-5114-4894-a045-7b330713ffb0.mov



**Firefox**

https://user-images.githubusercontent.com/25520267/199182051-149fc78d-1537-4b3a-8759-bd8516e0def6.mov

cc @neil-marcellini @Santhosh-Sellavel

**Comment by neil-marcellini** [comment] 2022-11-01 16:11
Awesome @mollfpr, thanks for detailing those steps. I like your proposal outline here https://github.com/Expensify/App/issues/10824#issuecomment-1298176088. It fixes the issue in a simple way that makes sense; the PDF container should be focusable. I also noticed that keyboard navigation via the tab button works well with this solution, which is important for accessibility.

What do you think about that proposal @Santhosh-Sellavel?


https://user-images.githubusercontent.com/26260477/199281317-a8336b74-bc45-4b77-86ab-ab1dde75c053.mov

**Comment by JmillsExpensify** [comment] 2022-11-01 18:27
Awesome, as soon as @Santhosh-Sellavel is good with this direction, we can get @mollfpr assigned and hire via Upwork. I'm re-posting the job here since it's far up in the scroll and the previous link expired. https://www.upwork.com/jobs/~015f8ae228449711e2

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 19:11
Looks good, If I am understanding correctly.

After the proposal, the pdf Container is now focusable using tab navigation. Either after focusing on the pdf view using Tab or Tap/click, it will scrollable using the up & down arrow right?

@neil-marcellini @mollfpr

**Comment by mollfpr** [comment] 2022-11-02 00:45
That’s correct @Santhosh-Sellavel

**Comment by mollfpr** [comment] 2022-11-02 18:14
@JmillsExpensify Applied to the Upwork, thanks!

**Comment by JmillsExpensify** [comment] 2022-11-02 19:09
Thanks hired! cc @Santhosh-Sellavel job is here for you as well: https://www.upwork.com/jobs/~015f8ae228449711e2.

**Comment by JmillsExpensify** [comment] 2022-11-06 20:24
@mollfpr I wanted to circle back on this issue and get better clarity when you expect the linked PR to be ready for review?

**Comment by Santhosh-Sellavel** [comment] 2022-11-06 22:16
@JmillsExpensify Seems PR is ready for Review. I'll review it.

Also applied for the job, thanks!!

**Comment by JmillsExpensify** [comment] 2022-11-11 04:24
I'll have to circle back to this one tomorrow. I'm finishing my day.

**Comment by sobitneupane** [comment] 2022-11-14 13:56
Probably, [fix](https://github.com/Expensify/App/pull/12391) of this issue is causing [this regression](https://expensify.slack.com/archives/C049HHMV9SM/p1668433791785489)

cc: @neil-marcellini @Santhosh-Sellavel

**Comment by mollfpr** [comment] 2022-11-14 14:13
Per this [comment](https://github.com/Expensify/App/issues/10824#issuecomment-1298770921) I agree the PDF container should be focusable so the user can scroll through the PDF with their arrow key. But maybe we should leave the outline style there to give the user vision that they focus on the PDF file?

**Comment by JmillsExpensify** [comment] 2022-11-14 15:40
I commented in the linked PR, but in order to have a discussion in Slack, I love to see a summary of the following from any of @mollfpr, @sobitneupane and/or @neil-marcellini. Basically,

 - Overview of the bug. Feel free to link to a comprehensive summary if one already exists. 
 - Root cause of the issue. What was the specific line that introduced the regression?
 - And finally, what could we do to ensure that this doesn't happen again. 

Thanks all!

**Comment by mollfpr** [comment] 2022-11-14 15:56
I'll start, feel free to add more context @sobitneupane @neil-marcellini.

> Overview of the bug. Feel free to link to a comprehensive summary if one already exists

https://expensify.slack.com/archives/C049HHMV9SM/p1668433791785489


> Root cause of the issue. What was the specific line that introduced the regression?

We add a new focusable to the PDF container element and remove the outline style but it seems to make the focus lost after a specific tab. https://github.com/Expensify/App/blob/e09d22847b476e9a5bc864e4722aa3e5dd4d50ac/src/components/PDFView/index.js#L123 

> And finally, what could we do to ensure that this doesn't happen again

I think we should have more abroad discussion when the issue related to the tab navigation, so the others will know and agree to the changes.

**Comment by JmillsExpensify** [comment] 2022-11-14 16:12
Ok that's super helpful. I'm happy to kick off a discussion in #expensify-bugs as BZ, though I think it'd be more productive if one of you get this kicked off, as you are closer to the code and the actual root cause. We're actually discussing this change moving forward, so that more people can participate in the discussion.

**Comment by neil-marcellini** [comment] 2022-11-14 17:03
Posted in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1668445374450239).

**Comment by JmillsExpensify** [comment] 2022-11-15 17:02
Alright, so circling back on the discussion in Slack, I think I should:

 - Create a fresh issue for adding a new QA test to TestRail
 - Start by building off the original QA and incorporating the root cause issue
 - CC everyone in this testing issue to ensure we're appropriately covering cases moving forward

Does that sound right?

**Comment by JmillsExpensify** [comment] 2022-11-18 09:39
Lots going on in the open source world right now and the priority of this issue has slipped for me. I'll work on closing the loop as soon as I can, at the latest when the regression period ends.

**Comment by JmillsExpensify** [comment] 2022-11-22 06:33
Circling back to pay out contributors. I still need to dig into the regression test, but let me first quickly issue payments since no regressions have arisen.

**Comment by JmillsExpensify** [comment] 2022-11-22 06:46
Yes, we've discussed this regression above as well.

**Comment by mvtglobally** [comment] 2022-11-22 20:44
Issue not reproducible during KI retests. (Second week)

**Comment by Santhosh-Sellavel** [comment] 2022-11-24 16:57
not overdue

**Comment by JmillsExpensify** [comment] 2022-11-26 19:04
Closing the loop on this today. Apologies again for the delay on the regression tests!

**Comment by JmillsExpensify** [comment] 2022-11-29 04:57
Alrighty, closing the loop. I created/linked the regression test. @neil-marcellini would you mind taking a look in the linked issue? I've added the up/down navigation to one of the existing tests, though we've since decided that tab navigation isn't officially supported, so I didn't add anything around that case. Closing the issue now that the regression test is added.

**Closed by JmillsExpensify** 2022-11-29 04:57 UTC
Labels: External, Engineering, Daily, Improvement, Overdue, Awaiting Payment, Bug

**Comment by sobitneupane** [comment] 2022-11-29 06:40
@JmillsExpensify Am I eligible for payment for reporting the [regression](https://github.com/Expensify/App/issues/10824#issuecomment-1313751312)?

**Comment by JmillsExpensify** [comment] 2022-11-29 06:48
While we don''t consider these bugs moving forward, as TAB is an accessibility feature we haven't built, yes I think that's fair game for a reporting bonus. Upwork job is here: https://www.upwork.com/jobs/~018a6911f84f687773.

**Comment by sobitneupane** [comment] 2022-11-29 06:51
@JmillsExpensify Proposal submitted.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:56
Offer sent.

**Comment by JmillsExpensify** [comment] 2022-11-29 06:58
You're all set. Paid out!

**Comment by dhairyasenjaliya** [comment] 2022-11-29 07:15
@JmillsExpensify regarding these accessibility bugs I have reported similar 2 bugs/regression #12058 is related to this bug on the same component, am I eligible for reporting those?

https://github.com/Expensify/App/issues/12058
https://github.com/Expensify/App/issues/12010

**Comment by JmillsExpensify** [comment] 2022-11-29 18:47
Please take that question to open source in Slack. However for clarity we only compensate for merged PRs. This specific issue was reported by our regression testing partner.
