### ISSUE TITLE
[$500] Login - Two messages are being displayed simultaneously

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31640] opened 2023-11-21 15:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in with any account
3. Go to Setting - Security - Close account
4. After account close - click on phone or email field
5. Click outside the field

## Expected Result:
One error message should be display

## Actual Result:
Two messages are being displayed simultaneously

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image (25)](https://github.com/Expensify/App/assets/93399543/dc71b6ff-f91f-4ce6-bb4c-f71078b54cbc)

https://github.com/Expensify/App/assets/93399543/9119c629-f032-4078-96e9-b7bba9250c26

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0188dc38b237965891</li>
        <li>Upwork Job ID: 1726992865077514240</li>
        <li>Last Price Increase: 2023-11-21</li>
    </ul>
</details>

**Comment by rojiphil** [comment] 2023-11-21 17:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Post account closure, whenever there is a validation of input in sign-in page, only one of the messages should be displayed. Here, I think it should show the validation error and the account closure message should be closed as the user is attempting to enter a new email address.

### What is the root cause of that problem?

In [here](https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/pages/signin/LoginForm/BaseLoginForm.js#L174C1-L177C10), we clear the account closure message on form submission. However, when validation of input occurs [here](https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/pages/signin/LoginForm/BaseLoginForm.js#L114), we are not clearing the account closure message. This looks to be the root cause.

### What changes do you think we should make in order to solve the problem?

Whenever there is a validation of input occurring [here](https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/pages/signin/LoginForm/BaseLoginForm.js#L114), we can clear the account closure message like this [here](https://github.com/Expensify/App/blob/51781a7e04cace5620adc1910b7f39a8e5bfd327/src/pages/signin/LoginForm/BaseLoginForm.js#L114)

            // If account was closed and there is a trigger for validation of input value, we clear it here
            if (!_.isEmpty(props.closeAccount.success)) {
                CloseAccount.setDefaultData();
            }

### What alternative solutions did you explore? (Optional)

**Comment by Mouhamed-B** [comment] 2023-11-21 17:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The form is showing an error before submission, and since the user just closed an account, two messages are being displayed simultaneously.

### What is the root cause of that problem?
Form errors display before submission, which may be intended. However, there should not be independent conditions to show the messages, as they are displayed in the same place.

### What changes do you think we should make in order to solve the problem?
The logic have to handle replacing the displayed message when needed. And maybe wait for submission to display form errors.

### What alternative solutions did you explore? (Optional)

**Comment by Mouhamed-B** [comment] 2023-11-21 18:02
Contributor details
Your Expensify account email: qwertz92@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01992770c7b7b384cf

**Comment by dwitidibyajyoti** [comment] 2023-11-21 18:47
Your Expensify account email: [dwitidibyajyoti@gmail.com](mailto:dwitidibyajyoti@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~01582d00c5c3aa8d42

**Comment by dwitidibyajyoti** [comment] 2023-11-21 18:51
Contributor details
Your Expensify account email: dwitidibyajyoti@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01582d00c5c3aa8d42

**Comment by garrettmknight** [comment] 2023-11-21 19:50
I don't think the 'Account closed successfully' is an error, it's a status message so I wouldn't necessarily expect it to go away in favor of another message. I also think this is a really edge use case so I'm going to close.

**Closed by garrettmknight** 2023-11-21 19:50 UTC
Labels: External, Daily, Help Wanted, Bug
