### ISSUE TITLE
[$1000] There is a wrong link in the manage your bills

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#25962] opened 2023-08-25 17:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the website
2. Settings > Workspaces
3. click any workspace from the list
4. click bills
5. Observe the text under managing your bills
## Expected Result:
There should be a valid link in which the recipients will be sent and a "copy to clipboard" button
## Actual Result:
Ask your vendors to forward their invoices to [example.com@expensify.cash](mailto:example.com@expensify.cash) and we'll scan them for you to pay.
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-3
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/38435837/c89078ec-4d80-442f-8a88-8d7079120d1c

![Window - (3) New Expensify - Google Chrome](https://github.com/Expensify/App/assets/38435837/3c3dfd0b-fb40-47e8-bd44-987a3b0c969b)

**Expensify/Expensify Issue URL:**
**Issue reported by:**  @misgana96
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692087374120429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014aec13bc46c67f6b</li>
        <li>Upwork Job ID: 1696167080456757248</li>
        <li>Last Price Increase: 2023-09-11</li>
    </ul>
</details>

**Comment by Al-nitak-external** [comment] 2023-08-28 14:59
user.isFromPublicDomain  is evaluating to true thats why the [example.com@expensify.cash] text is shown and the copy to clip board button is not rendered

**Comment by b4s36t4** [comment] 2023-08-28 15:16
@maddylewis What is the expected behaviour here? When we click on `View All bills` we should take the user to dev expensify? or what? can you please put a valid URL here for our reference?

**Comment by Al-nitak-external** [comment] 2023-08-28 15:23
Contributor details
Your Expensify account email: abdelrahmanalbiruni@hotmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/albiruni

**Comment by talhajavedmukhtar** [comment] 2023-08-28 16:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking on bills from within Settings > Workspaces > Worskspace-Name should show the user a relevant email address along the lines of (<user's-email-domain>@expensify.cash) within a Copy-to-Clipboard interface.

### What is the root cause of that problem?
#### Basic: 
For all users whose email addresses contain a public domain (like gmail.com; yahoo.com; publicCompanyWebsite.com; etc), the email text is hard-coded to 1) be "example.com@expensify.cash" instead of a domain specific email address and 2) to lead to the discussion forum, instead of being within a Copy-to-Clipboard component.
#### Detailed Conjecture: 
I believe this part was hard-coded by a developer "to be dealt with later", because making the correct resolution for addresses like marc@yahoo.com requires some thought/discussion. Should it be yahoo.com@expensify.cash OR yahoo@expensify.cash OR .... The first option breaks the email format while the second leaves room for clashes in cases like "@abc.com vs @abc.edu".

### What changes do you think we should make in order to solve the problem?

We need to make a well-thought-out resolver function/class here that resolves to an appropriate "bill receiving" email address against all possible user email addresses. For example marc@lemon.edu and ahmed@lemon.edu should resolve into something like lemon-edu@expensify.cash OR lemon@expensify.cash; whichever is architecturally most convenient for Expensify. We need to be mindful of clashes, etc while designing this resolver.

**Comment by talhajavedmukhtar** [comment] 2023-08-28 16:41
Contributor details
Your Expensify account email: talha_jav@rocketmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~014b6101992aa81143

**Comment by AbubakerShekhani** [comment] 2023-08-28 17:03
> 📣 @AbubakerShekhani! 📣 Hey, it seems we don’t have your contributor details yet! You'll only have to do this once, and this is how we'll hire you on Upwork. Please follow these steps:
> 
> 1. Get the email address used to login to your Expensify account. If you don't already have an Expensify account, create one [here](https://new.expensify.com/). If you have multiple accounts (e.g. one for testing), please use your main account email.
> 2. Get the link to your Upwork profile. It's necessary because we only pay via Upwork. You can access it by logging in, and then clicking on your name. It'll look like [this](https://www.upwork.com/freelancers/~01ca8ad8ce36b9eceb). If you don't already have an account, sign up for one [here](https://www.upwork.com/nx/signup/?dest=home).
> 3. Copy the format below and paste it in a comment on this issue. Replace the placeholder text with your actual details.
>    ![Screen Shot 2022-11-16 at 4 42 54 PM](https://user-images.githubusercontent.com/30609178/231263719-a8a3b7d3-36a0-4d7f-8ad4-cebe1f560fa4.png)
>    Format:
> 
> ```
> Contributor details
> Your Expensify account email: <REPLACE EMAIL HERE>
> Upwork Profile Link: <REPLACE LINK HERE>
> ```

Contributor details
Your Expensify account email: abubakershekhani@yahoo.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d5969bc1374cc80e

**Comment by maddylewis** [comment] 2023-08-30 19:15
@allroundexperts - lmk if you have availability to review the proposals for this one! if not, I'll reach out to another C+ to get started. ty!

**Comment by sourcecodedeveloper** [comment] 2023-09-04 15:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When logging in from a public domain account i.e company account and navigate to workspaces and click Bills, the text shows hardcoded email address  "example.com@expensify.cash" clicking on it takes the user to document explaining how to pay company bills in expensify.

### What is the root cause of that problem?
The root cause of the problem is for email accounts that are termed as company accounts by the back-end are shown hardcoded link.

```
<Text>
    {props.translate('workspace.bills.askYourVendorsBeforeEmail')}
    {props.user.isFromPublicDomain ? (
        <TextLink onPress={() => Link.openExternalLink('https://community.expensify.com/discussion/7500/how-to-pay-your-company-bills-in-expensify/')}>
            example.com@expensify.cash
        </TextLink>
    ) : (
        <CopyTextToClipboard
            text={`${emailDomain}@expensify.cash`}
            textStyles={[styles.textBlue]}
        />
    )}
    <Text>{props.translate('workspace.bills.askYourVendorsAfterEmail')}</Text>
</Text>
```

### What changes do you think we should make in order to solve the problem?
Instead of showing hardcoded link for those accounts that are termed as company accounts i.e public domains by the back-end, the text can be changed to better guide the user.
 Suggested solution screenshot attached.
![publicdomain](https://github.com/Expensify/App/assets/141340971/7e51069e-79fe-4fca-ab24-5b24a0971d0f)

For email accounts that are termed not to be company accounts i.e not public domain by the back-end, the text is shown correctly with the appropriate email address and copy to clipboard button. screenshot attached.

![notpublicdomain](https://github.com/Expensify/App/assets/141340971/80bbb045-e243-4651-83bf-65bc6d16baaa)


### What alternative solutions did you explore? (Optional)
The back-end decides on which account is termed to be public domain. Based on that if isFromPublicDomain is true, then based on existing logic the user is logged in from company account and should be shown the guide on how to pay company bills in expensify. 
If the back-end decides the account logged in is not from public domain i.e not company, then the user is shown the below text 
"Ask your vendors to forward their invoices to ...  and we'll scan them for you to pay."

**Comment by maddylewis** [comment] 2023-09-08 20:29
just seeing this - ill follow up to confirm the expected behavior.

**Comment by maddylewis** [comment] 2023-09-12 22:24
alright, sorry for the delay here. 

>Ask your vendors to forward their invoices to [example.com@expensify.cash](mailto:example.com@expensify.cash) and we'll scan them for you to pay.

This is expected behavior. That's the instruction to have vendor bills forwarded to someone's Expensify account. 

> When we click on View All bills we should take the user to dev expensify? or what? can you please put a valid URL here for our reference?

When clicking "View all bills" you should be taken to OldDot > the reports page > and filter bills. I don't have any bills in this account which is why 0 reports show:

https://github.com/Expensify/App/assets/38016013/16f308b6-4a20-4ea9-8551-15e7f63d87f7

<img width="1330" alt="image" src="https://github.com/Expensify/App/assets/38016013/87bd1170-64a3-45f4-80e9-9858f093644a">

that said, i think this is actually working as expected and any changes to this behavior would touch OldDot / should be considered a new feature request.

**Comment by maddylewis** [comment] 2023-09-12 23:09
@allroundexperts - based on those details, what do you think? i think we can actually close this one but would love your input.

**Comment by misgana96** [comment] 2023-09-13 01:34
Ask your vendors to forward their invoices to example.com@expensify.cash and we'll scan them for you to pay.

@maddylewis But when clicking the link it goes to external page which is a blog. Is it expected?

**Comment by misgana96** [comment] 2023-09-13 12:03
[Screencast from 13-09-2023  3:01:45 ከሰዓት.webm](https://github.com/Expensify/App/assets/48551032/cd6ac789-8f41-4c0c-b688-d39b3d1d7dbf)

**Comment by maddylewis** [comment] 2023-09-13 13:27
> But when clicking the link it goes to external page which is a blog. 

Will you tell me exactly what you are clicking that takes you to the community page? but, yes, that's our resource on paying bills in expensify, so that's expected.

**Comment by misgana96** [comment] 2023-09-13 18:36
> > But when clicking the link it goes to external page which is a blog.
> 
> Will you tell me exactly what you are clicking that takes you to the community page? but, yes, that's our resource on paying bills in expensify, so that's expected.

Action Performed: 
2. Open the website(https://new.expensify.com/)
3. Settings > Workspaces
4. click any workspace from the list
5. click bills
6. Click the link from Ask your vendors to forward their invoices to [example.com@expensify.cash](mailto:example.com@expensify.cash) and we'll scan them for you to pay.

**Comment by misgana96** [comment] 2023-09-13 18:40
https://github.com/Expensify/App/assets/48551032/9f61fba3-2da0-432e-b356-3118aaa9d2c6

**Comment by maddylewis** [comment] 2023-09-13 18:54
Okay, so you're clicking the example email address/the text above it and that's what takes you to the help doc. The only thing I would suggest updating is the hyperlink. 

> Ask your vendors to forward their invoices to exampledomain@expenisfy.cash and we'll scan them for you to pay. More details on this feature are [here](LINK). 

Or

> [Ask your vendors to forward their invoices to exampledomain@expenisfy.cash and we'll scan them for you to pay](LINK).

**Comment by misgana96** [comment] 2023-09-13 18:56
> Okay, so you're clicking the example email address/the text above it and that's what takes you to the help doc. The only thing I would suggest updating is the hyperlink.
> 
> > Ask your vendors to forward their invoices to [exampledomain@expenisfy.cash](mailto:exampledomain@expenisfy.cash) and we'll scan them for you to pay. More details on this feature are [here](LINK).
> 
> Or
> 
> > [Ask your vendors to forward their invoices to exampledomain@expenisfy.cash and we'll scan them for you to pay](LINK).

I feel the same thing. The only thing to do is just update the hyperlink

**Comment by sourcecodedeveloper** [comment] 2023-09-13 19:55
@allroundexperts Updated [proposal](https://github.com/Expensify/App/issues/25962#issuecomment-1705454387) by the way I was first to suggest changing the hyperlink text.

**Comment by AbubakerShekhani** [comment] 2023-09-14 20:59
> I would agree that @sourcecodedeveloper was first to suggest changing the hyperlink text in there [proposal](https://github.com/Expensify/App/issues/25962#issuecomment-1705454387). As such, let's

Sorry, this is not the case.

@allroundexperts  I was the first one to suggest that the link is fine and the text needs to be changed. 

@maddylewis @MelvinBot

**Comment by AbubakerShekhani** [comment] 2023-09-14 21:08
> Thanks for pointing out @AbubakerShekhani. I just checked again and it seems like I missed your proposal due to the long conversation happening here. You indeed suggested this first.
> 
> Let's go with @AbubakerShekhani's [proposal](https://github.com/Expensify/App/issues/25962#issuecomment-1696037592).
> 
> 🎀 👀 🎀 C+ reviewed

Thank you for the prompt response. 
Please let me know if it needs any further steps from my end.

**Comment by maddylewis** [comment] 2023-09-15 18:29
tbh, i don't think we should update this. the community post that is linked to the existing text is going to be outdated in the next few weeks after the [Community to HelpDot migration](https://github.com/Expensify/App/issues/27150) is complete. 

we'll be mass-updating a ton of in-product links then, and i think we can just hold off on this one until then.

**Comment by maddylewis** [comment] 2023-09-18 18:15
closing since we'll be mass updating links in the next couple of weeks.

**Closed by maddylewis** 2023-09-18 18:15 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
