### ISSUE TITLE
LHN - "Mark as Unread" Button Disabled for Attachments Offline

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#40099] opened 2024-04-11 10:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1, Go to any chat and send an attachment.
2, Make it offline, then hover over and click the three dots. Notice that the "Mark as Unread" button disappears.
3, However, observe that it appears when right-clicking on the attachment and in the LHN.

## Expected Result:
The "Mark as Unread" button should appear offline when hovering over and clicking "more" on the attachment, similar to when right-clicking on the attachment and in the LHN.

## Actual Result:
The "Mark as Unread" button is not available offline when hovering over and clicking "more" on the attachment, unlike when right-clicking on the attachment and in the LHN.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/0f501a13-da18-435b-ad06-d89a28cda749

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by izarutskaya** [comment] 2024-04-11 10:40
We think this issue might be related to the #collect project.

**Comment by c3024** [comment] 2024-04-11 11:06
The download button is removed and the `Mark as Unread` moved to the quick shortcut menu. Not a bug.

**Comment by c3024** [comment] 2024-04-11 11:17
@brkdavis are these `offline` screenshots?

**Comment by brkdavis** [comment] 2024-04-11 11:22
> @brkdavis are these `offline` screenshots?

@c3024 : sorry for that. I was in airplane, but WiFi was still on. So they are online mode screenshots.

**Comment by alexpensify** [comment] 2024-04-12 23:22
I'll test this one on Monday.

**Comment by brkdavis** [comment] 2024-04-13 21:24
> ## Screenshots/Videos
>  Bug6445707_1712829773817.Screen_Recording_2024-04-10_at_8.00.01_PM.mp4 

@izarutskaya : i see from your video that when you open chrome developer console, "Mark as unread" is moved to shortcut menu (last icon next to reply) rather than in context menu. I don't think this is a bug to be fixed. 

![image](https://github.com/Expensify/App/assets/166563016/39cc6c9f-c86e-4f75-936b-b0d5f4b2f46d)

Is the issue that it should not move to shortcut menu when screen size changes? If so, I can look in that direction.

**Comment by alexpensify** [comment] 2024-04-16 00:39
Still on my testing list

**Comment by izarutskaya** [comment] 2024-04-17 19:12
@brkdavis Not reproducible now. The download button is removed and the Mark as Unread moved to the quick shortcut menu when offline
Build  v1.4.62-13

https://github.com/Expensify/App/assets/115492554/21228cee-663e-4a3e-af95-dfec360a881b

**Comment by alexpensify** [comment] 2024-04-17 21:26
Ok, based on this latest update, I'm going to close this GH.

**Closed by alexpensify** 2024-04-17 21:26 UTC
Labels: Daily, Bug
