### ISSUE TITLE
 The app crashes when user clicking on the avatar of Workspace

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31078] opened 2023-11-08 21:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.97.0 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify
2. Log in with appluase account
3. Select #applause.expensifail.com
4. Open Details
5. Click on avatar 
6. Close and click on avatar again

## Expected Result:
The app doesn't crash when I click on the avatar of Workspace

## Actual Result:
The app crashes when I click on the avatar of Workspace

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native - is not ready
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/93399543/5f5c3fb2-c0d0-4357-85fc-84d0516f6c34

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2023-11-08 22:19
Not reproducible on production

https://github.com/Expensify/App/assets/93399543/0b543219-37f0-4ccd-9b41-395b7485d4ef

**Comment by marcochavezf** [comment] 2023-11-08 22:42
App is not loading locally on the latest main branch:

<img width="1068" alt="Screenshot 2023-11-08 at 4 41 42 p m" src="https://github.com/Expensify/App/assets/6829422/0cf9354a-28c6-4865-8759-f1e0db5dcf30">

I assume it's related to the issue reported [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1699481790879639)

**Comment by abzokhattab** [comment] 2023-11-08 22:44
@marcochavezf  Not related .. check this thread https://expensify.slack.com/archives/C01GTK53T8Q/p1698686381655959

**Comment by marcochavezf** [comment] 2023-11-08 22:47
Oh thanks @abzokhattab, I already did that a while ago, probably something messed up my configuration. I will try again those steps

**Comment by marcochavezf** [comment] 2023-11-08 22:55
Yup, trying again the configuration steps solved the webpack issue.

**Comment by marcochavezf** [comment] 2023-11-08 22:56
> is this repro. only with appluase account ??

I cannot reproduce it locally 🤔 

https://github.com/Expensify/App/assets/6829422/d9c646ec-2346-43a6-8304-680893efa9e2

**Comment by marcochavezf** [comment] 2023-11-08 23:35
Probably it was fixed by another PR, the only issue is the avatar's position but it's already reported [here](https://github.com/Expensify/App/issues/31080)

**Comment by marcochavezf** [comment] 2023-11-09 16:20
Closing it out since it's not reproducible locally. But feel free to re-open if it's reproducible after releasing the new version in staging

**Closed by marcochavezf** 2023-11-09 16:20 UTC
Labels: DeployBlockerCash, Engineering, Hourly
