### ISSUE TITLE
LHN shows "alternateText" even if it's flagedd and hidden

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21711] opened 2023-06-27 17:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Send a message from account A to account B
2. From account B hover over the message and click on "Reply in thread"
4. Go back to the original report and flag the message from account A as Intimidation or Bullying
5. Switch between reports and notice the alternate text in the LHN
## Expected Result: 
The message from account A should no longer show in LHN as it's potentially offensive.
## Actual Result: 
The flagged and hidden message still shows in LHN

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.33-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/19d387da-4aa4-4bc9-9b33-7467837f0c0c

https://github.com/Expensify/App/assets/43996225/a2fa15b9-c782-4187-9dea-9406b796e8de

**Expensify/Expensify Issue URL:**
**Issue reported by:** @AmjedNazzal 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687614422193979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2023-06-27 17:31
## Proposal
AmjedNazzal on GH
### Please re-state the problem that we are trying to solve in this issue.
LHN shows "alternateText" even if it's flagedd and hidden
### What is the root cause of that problem?
The issue is that in OptionsListUtils.getLastMessageTextForReport and ReportActionUtils.shouldReportActionBeVisible we are only watching for MODERATOR_DECISION_PENDING_REMOVE and not watching for MODERATOR_DECISION_PENDING_HIDE and so when a message is hidden but not deleted we still push it through to the LHN as "alternateText";
### What changes do you think we should make in order to solve the problem?
We need to add MODERATOR_DECISION_PENDING_HIDE to both functions in their if statement.
```javascript
if (lodashGet(lastNonWhisper, 'message[0].moderationDecisions[0].decision') === CONST.MODERATION.MODERATOR_DECISION_PENDING_REMOVE || lodashGet(lastNonWhisper, 'message[0].moderationDecisions[0].decision') === CONST.MODERATION.MODERATOR_DECISION_PENDING_HIDE) {
```
We also need to account for the return of "\__fake__" in SideBarUtils in case the hidden message is in a thread where also the parent report message is hidden, this way it would return "No Activity Yet".
```javascript
/**
else {
    result.alternateText = lastMessageTextFromReport.length > 0 && lastMessageTextFromReport !== '__fake__' ? lastMessageText : Localize.translate(preferredLocale, 'report.noActivityYet');
```
### What alternative solutions did you explore? (Optional)
### Result
https://github.com/Expensify/App/assets/74202751/e34a27af-98a9-4768-a3ab-0cf220b8ef1c

**Comment by anmurali** [comment] 2023-06-28 14:58
We are discussing the expected behavior [here](https://github.com/Expensify/App/issues/21497) so I will close this as a dupe

**Closed by anmurali** 2023-06-28 14:58 UTC
Labels: Daily, Bug
