### ISSUE TITLE
[hold for payment 2024-08-26] [$250] Submit expense - Not here page displayed in the background after a refresh

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46774] opened 2024-08-03 20:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** bezawitgebremichael+11223344@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Click on FAB
3. Click on start chat
4. Refresh the page
5. Observe everything works as normal
6. Click on FAB
7. Click on submit expense
8. Refresh the page

## Expected Result:
Everything should work as normal just as it is on step 5

## Actual Result:
Not here page gets displayed in the background when submit expense page is open on the right and user refreshes the page which is a different behavior that doesn't happen when other right hand pages are open

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/de7e7e38-32c3-4cb2-af2d-c6d2fa6b54d0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a60ec1cb3ed7a96b</li>
        <li>Upwork Job ID: 1820825832663945809</li>
        <li>Last Price Increase: 2024-08-06</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103466921</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by lanitochka17** [comment] 2024-08-03 20:07
@joekaufmanexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-03 20:07
We think that this bug might be related to #vip-vsp

**Comment by nkdengineer** [comment] 2024-08-05 07:04
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not here page gets displayed in the background when submit expense page is open on the right and user refreshes the page which is a different behavior that doesn't happen when other right hand pages are open

### What is the root cause of that problem?
When we submit an expense from FAB, the `reportID` is random but we call `OpenReport` API here and then a invalid report is stored in Onyx.

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69

Then the report screen with invalid `reportID` is added here when we open a RHP screen

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L154-L156

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L187

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/libs/Navigation/linkTo/index.ts#L135-L141
### What changes do you think we should make in order to solve the problem?
1. OPTIONAL: We should prevent calling the `OpenReport` API in the create flow

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/pages/iou/request/step/withWritableReportOrNotFound.tsx#L69


2. We should safely check whether the `reportID` exists or not here since some not found reports can be stored in Onyx

```
if (ReportConnection.getAllReports()?.[`${ONYXKEYS.COLLECTION.REPORT}${reportID}`]?.reportID) {
    return {name: SCREENS.REPORT, params: {reportID}};
}
```
https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L154-L156

3. We can add the money request screen `SCREENS.MONEY_REQUEST.CREATE` here

https://github.com/Expensify/App/blob/2eb65f8a666d0337ff6fd0d2ea0e7669b9d6aa6e/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L24
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-08-06 14:14
>@joekaufmanexpensify this is simlar to https://github.com/Expensify/App/issues/46713 and my proposal can fix it too, but RCA a little bit different

Got it. If we can fix all of the various cases in one issue, that feels ideal IMO

**Comment by joekaufmanexpensify** [comment] 2024-08-07 13:04
Pending proposal review

**Comment by joekaufmanexpensify** [comment] 2024-08-08 13:26
@sobitneupane mind taking a look here?

**Comment by sobitneupane** [comment] 2024-08-09 08:45
Thanks for the proposal everyone.

@nkdengineer Regarding the changes you have proposed, 

> OPTIONAL: We should prevent calling the OpenReport API in the create flow

It was added by [this PR](https://github.com/Expensify/App/pull/31529/). Won't removing it cause regression?

The third change you proposed has already been implemented in the latest main branch.

**Comment by sobitneupane** [comment] 2024-08-09 08:51
Thanks for your proposal @tsa321 

We cannot implement the change you suggested. In some scenarios, when opening the app through a deep link, it's necessary to open the report in the background. For instance, if we're currently viewing a report at `/r/abc` and attempt to open a deep link like `/create/submit/start/1/cde/manual`, the report `cde` needs to be opened in the background.

**Comment by sobitneupane** [comment] 2024-08-09 09:32
Thanks for the update 

[Proposal](https://github.com/Expensify/App/issues/46774#issuecomment-2268326185) from @nkdengineer looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by nkdengineer** [comment] 2024-08-09 16:22
> If your last action, for example, is submitting expense report A, then opening report B and clicking QAB, report A does not open; it stays on report B. Based on this, it is not necessary to open the report with the reportID(cde) in /create/submit/start/1/cde/manual in background. Therefore, the assertion that report A must open in the background is incorrect.

Just a note about this case: When we submit expenses to report A and then open report B, if we click on the QAB report B still appears. If we refresh the page, the report A is displayed as expected since we access the deep link has `reportID` as report A.

**Comment by joekaufmanexpensify** [comment] 2024-08-12 13:19
PR in review

**Comment by joekaufmanexpensify** [comment] 2024-08-19 14:17
PR merged and on staging

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:13
Hmm, automation did not work here. This went out to prod on the 19th, so is actually due today. Will tackle payment in the next day or so!

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:41
Payments here are:

- $250 to @nkdengineer for PR via Upwork. 
- $250 to @sobitneupane for C+ via NewDot.

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:41
All set to issue payment!

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:42
@nkdengineer $250 sent and contract ended

**Comment by joekaufmanexpensify** [comment] 2024-08-26 21:42
Closing as only thing left here is for @sobitneupane to request payment via NewDot!

**Closed by joekaufmanexpensify** 2024-08-26 21:42 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by garrettmknight** [comment] 2024-09-02 17:43
$250 approved for @sobitneupane
