### ISSUE TITLE
[HOLD for payment 2024-10-29] Remove tooltip from bottom navigation bar

### ISSUE THREAD

**Issue by dubielzyk-expensify** [Expensify/App#50129] opened 2024-10-03 05:28 UTC
## Problem

Now that we've added labels to the bottom navigation bar the tooltips that appear on hover are redundant as they repeat the same words as the label

![CleanShot 2024-10-03 at 15 27 23](https://github.com/user-attachments/assets/2cacf5ac-5f10-4881-b3ab-a49a72e474f8)

## Solution

Remove the tooltips on the bottom navigation bar

cc @Expensify/design 

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by ChavdaSachin** [comment] 2024-10-03 13:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Remove tooltip from bottom navigation bar

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?
We are using a total of 4 tooltips for navigation bar, simply remove those tooltip
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L113
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L139
https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/pages/home/sidebar/BottomTabAvatar.tsx#L71
And forth tooltip is optional to remove since it does not follow the reason why we are removing tooltips
> ## Problem
> Now that we've added labels to the bottom navigation bar the tooltips that appear on hover are redundant as they repeat the same words as the label

https://github.com/Expensify/App/blob/e61ee7fbe60acc12879b9d5cc6ef92c4a0b98caa/src/components/FloatingActionButton.tsx#L102

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by dylanexpensify** [comment] 2024-10-07 12:22
@tylerkaraszewski bump on this when you can! 🙇‍♂️

**Comment by tylerkaraszewski** [comment] 2024-10-07 22:44
I think we should remove all four tooltips if we're removing the first three.

**Comment by dannymcclain** [comment] 2024-10-08 13:49
Definitely want to hear @dubielzyk-expensify's opinion. I could be persuaded either way. On the one hand, I think we usually try to have tooltips on unlabeled buttons for clarity—on the other, the big green plus feels pretty obvious and intuitive (and the current tooltip `Create` isn't super helpful IMO).

**Comment by dubielzyk-expensify** [comment] 2024-10-08 23:15
I think we should remove it for all four. It feels weird to have it on just the green (+) button.

**Comment by Nodebrute** [comment] 2024-10-14 14:28
@tylerkaraszewski waiting for assignment.

**Comment by Nodebrute** [comment] 2024-10-15 22:41
Pr will be ready for review in few hours.

**Comment by dylanexpensify** [comment] 2024-10-18 12:51
Hey @bfitzexpensify! I'm heading out on parental leave so reassigning this! TY! 🙇‍♂️

**Comment by bfitzexpensify** [comment] 2024-10-29 13:10
@ZhenjaHorbach requires payment (Needs manual offer from BZ) - ✅ 
@Nodebrute requires payment (Needs manual offer from BZ) - offer sent

**Comment by Nodebrute** [comment] 2024-10-29 19:04
> @Nodebrute requires payment (Needs manual offer from BZ) - offer sent

@bfitzexpensify I didn't receive an offer.

**Comment by bfitzexpensify** [comment] 2024-10-30 14:43
I've sent another offer @Nodebrute - mind checking if that one came through?

**Comment by bfitzexpensify** [comment] 2024-10-31 12:20
Payments complete, closing this one out.

**Closed by bfitzexpensify** 2024-10-31 12:20 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment, Bug
