### ISSUE TITLE
[HOLD for payment 2023-06-02] Reactions menu in android app has close icon while no other menu has close icon

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18916] opened 2023-05-14 13:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. On mobile app open a group chat
2. Send a message and add an emoji from multiple accounts
3. Press and hold the emoji to open the details 
4. There is an 'x' in the upper right corner of the window to close the details

## Expected results: 

The mobile apps have an 'x' to close the details window and the web apps do not. 

mobile app: 
![image](https://github.com/Expensify/App/assets/51066321/5db14192-4370-4e67-b8a5-b085e3fdabe6)

Web app:

<img width="548" alt="image" src="https://github.com/Expensify/App/assets/51066321/1eb7562e-ce49-4ce1-96e2-7b154566db09">

## Actual results: 

close icon is present

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.313.3
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/f0f80a8c-1a5f-445c-acc4-6fdfa02f1436

https://github.com/Expensify/App/assets/43996225/a0405140-dcc8-4674-b78b-e6425066714c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683976391377529

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019046d76e789f23dd</li>
        <li>Upwork Job ID: 1659266103240200192</li>
        <li>Last Price Increase: 2023-05-18</li>
    </ul>
</details>

**Comment by kavimuru** [comment] 2023-05-14 13:08
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Reactions List menu in small screen has a close icon while no other menu in app has a close icon
### What is the root cause of that problem?
In the reaction list's header, for the small screen we have added a close button in the below file
https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReactionList/HeaderReactionList.js#L29-L49
This is adding the additional close button which is inconsistent with all the other menus in the app.
### What changes do you think we should make in order to solve the problem?
We don't need this button so we simply have to remove this piece of code and modify the header view as follows
```js
const HeaderReactionList = (props) => (
    <View style={[styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter, styles.emojiReactionListHeader, !props.isSmallScreenWidth && styles.pt4]}>
        <View style={styles.flexRow}>
            <View style={[styles.emojiReactionListHeaderBubble, StyleUtils.getEmojiReactionBubbleStyle(false, props.hasUserReacted)]}>
                <Text style={[styles.miniQuickEmojiReactionText, StyleUtils.getEmojiReactionBubbleTextStyle(true)]}>{props.emojiCodes.join('')}</Text>
                <Text style={[styles.reactionCounterText, StyleUtils.getEmojiReactionCounterTextStyle(props.hasUserReacted)]}>{props.emojiCount}</Text>
            </View>
            <Text style={styles.reactionListHeaderText}>{`:${props.emojiName}:`}</Text>
        </View>
    </View>
);
```
Now we don't have that button in the header
<details>
  <summary>Results</summary>
</details>
### What alternative solutions did you explore? (Optional)
None

**Comment by chiragxarora** [comment] 2023-05-14 13:10
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Reactions List menu in small screen has a close icon while no other menu in app has a close icon


### What is the root cause of that problem?

In the reaction list's header, for the small screen we have added a close button in the below file

https://github.com/Expensify/App/blob/293f23b57be2bca3f3eb0af903d5e0c2894cb36a/src/pages/home/report/ReactionList/HeaderReactionList.js#L29-L49

This is adding the additional close button which is inconsistent with all the other menus in the app.

### What changes do you think we should make in order to solve the problem?

We don't need this button so we simply have to remove this piece of code and modify the header view as follows

```js
const HeaderReactionList = (props) => (
    <View style={[styles.flexRow, styles.justifyContentBetween, styles.alignItemsCenter, styles.emojiReactionListHeader, !props.isSmallScreenWidth && styles.pt4]}>
        <View style={styles.flexRow}>
            <View style={[styles.emojiReactionListHeaderBubble, StyleUtils.getEmojiReactionBubbleStyle(false, props.hasUserReacted)]}>
                <Text style={[styles.miniQuickEmojiReactionText, StyleUtils.getEmojiReactionBubbleTextStyle(true)]}>{props.emojiCodes.join('')}</Text>
                <Text style={[styles.reactionCounterText, StyleUtils.getEmojiReactionCounterTextStyle(props.hasUserReacted)]}>{props.emojiCount}</Text>
            </View>
            <Text style={styles.reactionListHeaderText}>{`:${props.emojiName}:`}</Text>
        </View>
    </View>
);
```
Now we don't have that button in the header

<details>
  <summary>Results</summary>

https://github.com/Expensify/App/assets/54641656/5f53f94e-1671-49ae-8711-1038923b136e



</details>

### What alternative solutions did you explore? (Optional)
None

**Comment by chiragxarora** [comment] 2023-05-15 21:07
![Screenshot_2023-05-14-18-18-06-395_com.whatsapp.jpg](https://github.com/Expensify/App/assets/54641656/76d4812d-2218-4437-aade-7374797fb72e)

![Screenshot_2023-05-14-18-16-55-318_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/7f5c2ec6-e869-4eee-8f84-8646db6f7bd3)

![Screenshot_2023-05-14-18-17-10-516_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/d17d7913-44b8-416d-9831-b666d5317fa4)

![Screenshot_2023-05-12-18-42-21-237_com.upwork.android.apps.main.jpg](https://github.com/Expensify/App/assets/54641656/cae327c9-630b-4081-90e1-11585d088b7c)

![Screenshot_2023-05-14-18-17-14-883_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/a0f23fe4-c70e-4652-bf64-3b6ad9ce554f)

![Screenshot_2023-05-14-18-16-49-615_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/259738fc-a532-43a2-a96e-d8802eb790bb)

Looks inconsistent to me

**Comment by chiragxarora** [comment] 2023-05-15 21:08
Looks Inconsistent to me![Uploading Screenshot_2023-05-14-18-18-06-395_com.whatsapp.jpg …]()

![Screenshot_2023-05-14-18-17-10-516_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/52a58850-3991-435d-a860-708f1343a43f)

![Screenshot_2023-05-14-18-16-49-615_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/1cfaaffa-ea98-4646-b7e9-d8a2675a479e)

![Screenshot_2023-05-14-18-17-14-883_com.expensify.chat.jpg](https://github.com/Expensify/App/assets/54641656/c7639aea-f5a7-46e3-aa59-dfb789d1a814)

**Comment by Christinadobrzyn** [comment] 2023-05-15 21:49
Asking for some help with reproducing in Slack - https://expensify.slack.com/archives/C049HHMV9SM/p1684187348579009?thread_ts=1683976391.377529&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2023-05-17 17:24
I updated the OP so it's more clear, I think this is expected but getting an engineer to review it just in case.

**Comment by Christinadobrzyn** [comment] 2023-05-18 18:35
we're going to move forward with a fix to remove the 'x' based on a [convo](https://expensify.slack.com/archives/C03TME82F/p1684355453883439) with design

**Comment by chiragxarora** [comment] 2023-05-18 20:06
<img width="219" alt="image" src="https://github.com/Expensify/App/assets/54641656/57a48d77-6e33-4102-8229-4b2fef48a286">
does this require some changes in private repositories or something?

**Comment by Christinadobrzyn** [comment] 2023-05-18 21:15
It looks like we're going to fix this internal but we'll pay you for reporting it @chiragxarora!

**Comment by chiragxarora** [comment] 2023-05-18 21:44
Okayy cool

**Comment by Christinadobrzyn** [comment] 2023-05-22 21:30
Looks like we're working on the PR right @srikarparsi? I wonder if this can be moved from `daily` to `weekly`?

**Comment by srikarparsi** [comment] 2023-05-22 21:36
HI! Yes, It isn't urgent so I'll move it to weekly but I should get a fix out today.

**Comment by Santhosh-Sellavel** [comment] 2023-05-24 17:23
@mountiny Not sure why I was not auto-assigned for reviewed here

**Comment by mountiny** [comment] 2023-05-25 12:11
I think it seems the issue was incorrectly linked and Carlos edited it after it was merged bu I cannot confirm as it does not show when the edit happened
<img width="711" alt="image" src="https://github.com/Expensify/App/assets/36083550/17a952c9-20c7-45bb-9a16-37927e314c67">

**Comment by Christinadobrzyn** [comment] 2023-05-26 20:56
@srikarparsi @rushatgabhane Do you think we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2023-06-02 20:43
Ready for payment - Upwork job posting here - https://www.upwork.com/jobs/~019046d76e789f23dd

@rushatgabhane & @chiragxarora can you please accept my Upwork request?

@rushatgabhane do you think we need a regression test for this?

**Comment by Christinadobrzyn** [comment] 2023-06-02 22:45
Hey @rushatgabhane it's so difficult to find users in Upwork, instead can you please have Satish G. apply to the Upwork job https://www.upwork.com/jobs/~019046d76e789f23dd 

Thanks!

**Comment by Christinadobrzyn** [comment] 2023-06-05 17:57
Paid @chiragxarora in Upwork

I'll try to find Satish G in Upwork again and invite him to this.

**Comment by srikarparsi** [comment] 2023-06-07 08:08
Thanks @Christinadobrzyn! I think we can just close it out since it's just removing an "x" button. I'm closing it now but please reopen if there's anything I missed

**Closed by srikarparsi** 2023-06-07 08:08 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
