### ISSUE TITLE
[HOLD for payment 2023-08-28] [$1000] Requests are editable after being paid or deleted

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24578] opened 2023-08-15 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Navigate to the "Request Money" section.
3. Input a specific amount and send the request.
4. Open the IOU (I Owe You) details.
5. Send a message
6. Now delete the IOU
7. After deleting click on "Amount" filed

1. Log in to "UserA's" account.
2. Open the chat with "UserB."
3. Navigate to the "Request Money" section.
4. Enter a specific amount and send the request.
5. Click on the IOU to open its detail.
6. Click on the amount field.
7. Open another browser and log in to "UserB's" account.
8. Open the chat with "UserA" and click "Pay elsewhere."
9. Return to "UserA's" account and edit the IOU amount.

## Expected Result:
When request is deleted the transaction header should disappear.

When request is paid the transaction header fields should be disabled

## Actual Result:
App crashes when clicking on Amount filed after deleting IOU or user can click on edit field on paid requests.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/dc8c16c8-1467-4ce3-9625-19e9b5bf38cf

https://github.com/Expensify/App/assets/115492554/8c570bda-4178-42f3-aed0-3389179834c0

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ayazHussain79

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692037499896279

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0152f0c75c34484d87</li>
        <li>Upwork Job ID: 1691453667712995328</li>
        <li>Last Price Increase: 2023-08-15</li>
<li>Automatic offers: </li>
<ul>
<li>Ollyws | Reviewer | 26133365</li>
<li>dukenv0307 | Contributor | 26133367</li>
</ul></li>
    </ul>
</details>

**Comment by mountiny** [comment] 2023-08-15 14:07
This is a deploy blocker, but I am surprised that the transaction details are there when the request is deleted, we should make the buttons disabled in such case.

**Comment by Julesssss** [comment] 2023-08-15 14:11
Personally I don't think this should block the deploy as delete is a new-ish feature and trying to edit the amount of a deleted IOU is not a common flow. But we need to fix it for sure.

**Comment by mountiny** [comment] 2023-08-15 14:12
Yeah I would also err on a side of not blocking but fixing with urgency

**Comment by mountiny** [comment] 2023-08-15 14:16
I can take this one over as I have worked on the feature.

**Comment by BhuvaneshPatil** [comment] 2023-08-15 14:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
`transaction` is empty object when we delete the request.
<img width="569" alt="Screenshot 2023-08-15 at 7 36 41 PM" src="https://github.com/Expensify/App/assets/27822551/9389b897-1f6c-4eb2-a22b-023dcf1991fe">



### What changes do you think we should make in order to solve the problem?
Solution for that is - 
Check if deleted - 
```js    
const isDelete = ReportActionsUtils.isDeletedParentAction(parentReportAction);
```
change `canEdit`- 
```js
 const canEdit = !isSettled && (isAdmin || isRequestor) && !isDelete;
```

 - Button shall be disabled.

But there can be case when user can access through URL - `http://localhost:8082/r/338092812286798/edit/amount`
- To handle this we shall wrap early return the page.
```js
if(_.isEmpty(transaction)) return;
```
We can also show `FullPageNotFoundView` instead of return.


### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2023-08-15 14:18
@dukenv0307 I think we should just make the transaction button disabled. and remove the caret to the side to make sure its not clickable.

I lso thin kwe should add the `deleted` message to the `let description`

**Comment by mountiny** [comment] 2023-08-15 14:18
I am going to go ahead with @dukenv0307 as they were the fastest and I think their solution is close.

**Comment by mountiny** [comment] 2023-08-15 14:22
@dukenv0307 I think we need to add some useEffects to make sure the state is updated correctly, when you navigate out of the report and back then you cannot edit the request, right?

**Comment by mountiny** [comment] 2023-08-15 14:22
Lets consolidate on this issue I will update the issue body

**Comment by mountiny** [comment] 2023-08-15 14:23
<img width="834" alt="image" src="https://github.com/Expensify/App/assets/36083550/aec28e87-a73f-40de-87c0-ae3db93c368b">

correct so once paid and you go out of the report and back its showing correctly

**Comment by mountiny** [comment] 2023-08-15 15:35
Responded in slack

**Comment by mountiny** [comment] 2023-08-16 15:47
Merged 🎉

**Comment by maddylewis** [comment] 2023-08-30 16:49
### Payments
- [ ] Reporting bonus: @ayazhussain79 ($250 - Upwork)
- [ ] Contributor: @dukenv0307 ($1500 - Upwork)
- [ ] C+: @Ollyws ($1500 - Upwork)
______
eligible for urgency bonus -  https://github.com/Expensify/App/issues/24578#issuecomment-1680767012

**Comment by maddylewis** [comment] 2023-08-30 16:57
offers sent to @ayazhussain79 / @Ollyws

**Comment by ayazhussain79** [comment] 2023-08-30 17:15
@maddylewis offer accepted, Thank you

**Comment by mountiny** [comment] 2023-09-04 10:34
Everyone paid, closing thanks

**Closed by mountiny** 2023-09-04 10:34 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
