### ISSUE TITLE
DEV: On small screen sizes if you don’t switch chats, new chats won’t mark as unread in the LHN

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19206] opened 2023-05-18 18:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open a chat with an account on a small screen size
2. Send a message from that other account
3. Use the arrow button to move back to the navigation view (i.e. you can’t see the chat anymore)
4. Send another message from that other account

## Expected Result:
Message should appear in the appropriate chat in the navigation, and be marked as unread
## Actual Result:
Message appears in the appropriate chat in the navigation, but is not marked as unread

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/8897f861-5e2f-4ecf-b779-5fef36eaf198

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dangrous 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684247684295779

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2023-05-26 05:11
I'm not fully understanding the steps so I can't reproduce the issue. I'm going to close this until better reproduction steps are provided.

**Closed by tjferriss** 2023-05-26 05:11 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
