### ISSUE TITLE
Web - Unable to verify 2FA after Closing account and re-login

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23622] opened 2023-07-26 10:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
PRECONDITION: Account has 2FA enabled
1. Login to the account A that has 2FA enabled
2. Go to Settings >> Security and Close the account
3. Login back with account A
4. Enter magic code
5. Enter 2FA code

## Expected Result:
1. Since the account is closed, 2FA setting should be cleared too
2. If NOT 1, then user should be able to use verify 2FA code

## Actual Result:
App keep saying 2FA code is invalid

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/1bd9cb81-0bdc-474d-9375-c1efa0e01b18

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690223897230289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by adelekennedy** [comment] 2023-07-28 03:43
Also cannot reproduce - I get the same error as @kbecciv, starting a conversation in the thread on what we expect, will take to the larger channel if we're unsure

**Comment by tranvantoan-qn** [comment] 2023-07-28 04:04
As discussed in the Slack channel, there are a few points we need to confirm.
- Whether or not users will be able to re-login after closing their accounts:
  - The system email states that users can re-login after closing their accounts. 
  - I have personally closed and re-opened my account multiple times without any issues.
- Why the error that @adelekennedy  and @kbecciv  are experiencing is not happening for all accounts? We need to investigate why these two users are experiencing this error and determine if there is a broader issue.

![IMG_4423](https://github.com/Expensify/App/assets/10254571/e35002a4-d876-4363-b6e3-24bc8510d550)

**Comment by adelekennedy** [comment] 2023-08-01 05:05
double checking expected behavior - the bug is slightly different than what the contributor reported

**Comment by adelekennedy** [comment] 2023-08-09 05:26
can't repro bit did uncover a new bug

**Closed by adelekennedy** 2023-08-09 05:26 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by tranvantoan-qn** [comment] 2023-08-09 05:31
@adelekennedy 
I'm curious if the team has established the expected behaviour in this case: **whether or not the user will be able to re-login** - as I did

(and whether a bug reporting bonus will be applied :D)

**Comment by adelekennedy** [comment] 2023-08-09 05:38
Not in this case as we were unable to reproduce.

**Comment by tranvantoan-qn** [comment] 2023-08-09 05:44
It's OK, 
Could you please share the expected behavior that the team agreed upon? The issue is still occurring for me, so I will try to determine the reason why this is behaving differently between your account and mine. There might be 2 different issues

**Comment by tranvantoan-qn** [comment] 2023-08-09 07:49
@adelekennedy 
I apologize for tagging you again 🙇, However, I'm personally committed to making sure we thoroughly address the potential issue by identifying its root cause.

Could you kindly visit the **OLD DOT** at https://www.expensify.com/ and log in using the email address you were having trouble with? (_this somehow un-block verification for that account_)
After that, attempt to log in again using the same email address on the NEW DOT. You should be able to successfully log in once more. 😄

It appears my assumption was correct - this may indeed be an email domain-related issue.
