### ISSUE TITLE
[$1000] Connect bank account - Can't clicking Almost done! offline, You appear to be offline appears immediately

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#19863] opened 2023-05-30 22:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19491

## Action Performed:
1. Open the App
2. Login with any account
3. Go to Settings -> Workspaces -> Open any WS( or create it) -> Start to add bank account in workspace
4. Exit in the middle of the flow (after page 'Company Information' or 'Personal Information')
5. Return to the flow again > Settings > Workspaces > Connect bank account
6. Go offline
7. Select Start Over on the page 'Almost done!'

## Expected Result:
Can click on Almost done!' button

## Actual Result:
Can't click "Almost done!" because "You appear to be offline" page appears immediately

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.20.3

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
https://platform.applause.com/services/links/v1/external/a58be4d7fa68595db1b63c14705666451446b82047759026017b6fa5e61df927

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017eec9f8b3dc353a2</li>
        <li>Upwork Job ID: 1664156526133538816</li>
        <li>Last Price Increase: 2023-06-01</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-06-01 06:26
Reproduced on iOS:

https://github.com/Expensify/App/assets/59587260/e2ac3967-31a3-469b-9dbe-228053c45208

**Comment by bondydaa** [comment] 2023-06-05 17:16
Hmm this might be related to https://github.com/Expensify/App/pull/19491

cc @HezekielT @mananjadhav though I'm not if that PR is the cause of it. Since the screenshots seem to show the same behavior... 

Though maybe this is also expected and uses Pattern D - Full Page Blocking UI? https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md#d---full-page-blocking-ui-pattern

**Comment by bondydaa** [comment] 2023-06-05 21:40
closing in favor of https://github.com/Expensify/App/issues/18990

**Closed by bondydaa** 2023-06-05 21:40 UTC
Labels: External, Daily, Help Wanted, Bug
