### ISSUE TITLE
[$250] CRITICAL: [UX RELIABILITY] We are making reports with an RBR unread on the LHN even if it is Paid

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#42604] opened 2024-05-24 16:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @danielrvidal 
**Slack conversation:**

## Action Performed:
Break down in numbered steps

1. Create a report on New Expensify
1. Tag an expense on the report
1. Mark it as Paid
1. Disable the department that you added

## Expected Result:
Describe what you think should've happened

The expense remains coded with that tag, since it was technically "approved"

## Actual Result:
Describe what actually happened

It reappears in the LHN as an unread chat

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

Mark it as read

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01faedcd7c24547a88</li>
        <li>Upwork Job ID: 1794177977549811712</li>
        <li>Last Price Increase: 2024-05-25</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 102506974</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by rezkiy37** [comment] 2024-05-27 08:58
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-05-27 15:05
I've tried to reproduce the bug a few times. Fortunately, I was not able to do it. I tested with a couple of expenses. I disabled a tag for one and deleted it for two. I am attaching a video, please let me know if I missed something 🙂 

<details><summary>Details</summary>
<p>


https://github.com/Expensify/App/assets/57314631/87208311-474f-41d7-aba7-7d3bdf4f13ec



</p>
</details>

**Comment by mountiny** [comment] 2024-05-29 09:05
Waiting to hear from QA if they can reproduce or not

**Comment by kavimuru** [comment] 2024-05-30 22:55
@mountiny not able to reproduce.

https://github.com/Expensify/App/assets/43996225/f5348475-5363-427f-a0e3-31261b3b2fe4

**Comment by mountiny** [comment] 2024-05-30 23:00
Thank you, lets close this for now and we can reopen if we can repro

**Closed by mountiny** 2024-05-30 23:00 UTC
Labels: External, Daily, Overdue, Bug, retest-weekly
