### ISSUE TITLE
Payments - Different error message appears when adding same bank account again

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13849] opened 2022-12-28 00:13 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11837

## Action Performed:
1. Go to Settings > Payment > Add Payment Method > Bank Account
2. Add a test Plaid account (e.g. Chase with credentials user_good / pass_good / blank OTP)
3. Make sure you see the success page saying that the account was added
4. Repeat the same flow and try to add the same bank account again

## Expected Result:
When you're redirected back to Expensify, make sure you get the Sorry, no bank account is available

## Actual Result:
Could not find any bank accounts that you haven't already added message appears

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.44.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/209738523-2737c900-0fea-49f3-9f7f-49633b0d6b6e.mp4

![Screen Shot 2022-12-27 at 5 07 30 PM](https://user-images.githubusercontent.com/93399543/209738537-5122addd-51ea-4d8e-beb7-748197f70626.png)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcochavezf** [comment] 2022-12-28 00:51
It seems the message is the expected one, asking for clarification here https://github.com/Expensify/App/pull/11837#issuecomment-1366289182

**Comment by srikarparsi** [comment] 2022-12-28 18:07
Hey @marcochavezf, yes this is the expected error message - we modified it to use the error message from Web E since it was more specific. I'm trying to find the flow in test rail to modify it but couldn't find anything related to closing an account. @kbecciv would you be able to modify the expected behavior in test rail to the actual result for this flow?

**Comment by kbecciv** [comment] 2022-12-29 14:52
@srikarparsi Let me check the TestRail steps first, since this was coming from PR.

**Comment by kbecciv** [comment] 2022-12-29 16:01
Tagging for the updates @mvtglobally

**Comment by srikarparsi** [comment] 2022-12-29 18:49
Ohh sorry, I thought this was coming from Test Rail but am following now. I just updated the PR to have the right QA steps. I'm not sure if this flow is in Test Rail but it would be great if you could update the expected result if it is :)

**Comment by marcochavezf** [comment] 2022-12-30 23:03
Cool, since this is the expected error message I think we can close this issue out cc @mallenexpensify

**Comment by mallenexpensify** [comment] 2022-12-30 23:13
Agreed, I think the below is what we want
> Could not find any bank accounts that you haven't already added message appears

**Closed by mallenexpensify** 2022-12-30 23:13 UTC
Labels: Daily, Overdue, Bug
