### ISSUE TITLE
Inconsistent formatting on multi-line text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13727] opened 2022-12-20 15:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed :
1. Open [staging.new.expensify.com](http://staging.new.expensify.com/)
2. Open a chat and send this :
```
*this is
bold text*
```
3. Open a chat and send this :
```
~this is
strikethrough text~
```
## Expected Result :
 Either both of them should be consistently formatted correctly (bold and strike-through) or the formatting should be omitted consistently for both of them
## Actual Result : 
The bold text isn't formatted (the text isn't bold and the asterisk still existed), while the strikethrough text formatted correctly

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] Windows OS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.42-0
**Reproducible in staging?:** y
**Reproducible in production?:**y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/208710343-a4f1f635-d7f2-4057-b680-2a2ff3aff91c.mp4

https://user-images.githubusercontent.com/43996225/208710365-3d3c4b39-c0a1-4070-80f0-cd482593eb03.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kerupuksambel
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1670486437536859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by srikarparsi** [comment] 2022-12-20 18:32
hey @michaelhaxhiu, I can work on this! It seems like a bug but let me know though if you think that's it's expected behaviour.

**Comment by michaelhaxhiu** [comment] 2022-12-20 20:06
Hmm it's sure _inconsistent_, but looking into whether this is a WAQ style bug or not.

**Comment by srikarparsi** [comment] 2022-12-26 03:57
Messaged [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1672026779294369) since hax is ooo this week

**Comment by srikarparsi** [comment] 2022-12-28 19:37
Was waiting on confirmation about this being a WAQ issue. Will try to get a pr out by the end of this week if it is.

**Comment by srikarparsi** [comment] 2023-01-02 21:10
hey @michaelhaxhiu! I'm taking a leave from expensify to finish up classes this semester and wasn't able to get to this issue. Do you think you could reassign this to another engineer?

**Comment by michaelhaxhiu** [comment] 2023-01-03 13:38
Ya sure thing @srikarparsi !

**Comment by michaelhaxhiu** [comment] 2023-01-03 13:46
https://expensify.slack.com/archives/C03TQ48KC/p1672753238528269

**Comment by michaelhaxhiu** [comment] 2023-01-03 14:00
If no volunteers, then I'll post this in the WN weekly thread with #engineers, in case someone needs an issue to work on.

**Comment by neil-marcellini** [comment] 2023-01-04 23:31
Here's a draft expensify-commen PR https://github.com/Expensify/expensify-common/pull/486. Next I'll put up an App PR with some test steps.

**Comment by neil-marcellini** [comment] 2023-01-05 02:40
While testing on App I realized that I also need to support converting the html back into markdown so that it's visible when editing your comment. I also found that it didn't work for multi-line strikethrough. I believe I have now fixed both multiline strikethrough and bold markdown comments.

Both PRs are now ready for review and here's the App PR https://github.com/Expensify/App/pull/14009.

**Comment by neil-marcellini** [comment] 2023-01-09 19:27
The App PR was deployed to production as noted here https://github.com/Expensify/App/pull/14009#issuecomment-1376037264.

Here's the checklist since our automation is broken.
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@neil-marcellini] The PR that introduced the bug has been identified. Link to the PR:
N/A this bug was missed during the initial implementation.
- [x] [@neil-marcellini] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
N/A
- [x] [@neil-marcellini] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
I don't think we need to update the PR checklist since it was missed during the initial implementation.
- [ ] [@michaelhaxhiu] A [regression test](https://expensify.testrail.io/index.php?/dashboard) has been added or updated so that the same bug will not reach production again. Link to the GH issue for creating the test here:
I'm not sure that we need a regression test since I added an automated test for this in the expensify-common repository where the mark down is handled.

**Comment by neil-marcellini** [comment] 2023-01-09 19:41
I reported the bug zero checklist automation issue in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1673293270929349).

**Comment by iwiznia** [comment] 2023-01-09 19:50
I think we missed paying the reporter of the issue, @kerupuksambel, no?

**Comment by neil-marcellini** [comment] 2023-01-09 19:53
Ah woops, I always forget that. Yes let's get the reporter paid please @michaelhaxhiu 🙏 .

**Comment by neil-marcellini** [comment] 2023-01-09 19:55
We should add that step to the bug zero checklist.

**Comment by michaelhaxhiu** [comment] 2023-01-10 15:13
Working on this now... we need to compensate @aimane-chnaif for C+ work and @kerupuksambel for bug reporting

**Comment by michaelhaxhiu** [comment] 2023-01-10 15:46
Bug reporting bonus - https://www.upwork.com/jobs/~01fc330fff2a148dea

C+ review - https://www.upwork.com/jobs/~01f8989251a01deea7

**Comment by michaelhaxhiu** [comment] 2023-01-18 18:00
Hmm @thesahindia I noticed you helped review this PR https://github.com/Expensify/App/pull/14009.

Should we be compensating $1000 for that C+ review (in addition to the C+ review on https://github.com/Expensify/expensify-common/pull/486)?

**Comment by michaelhaxhiu** [comment] 2023-01-19 16:28
I'm conflicted. I think technically speaking, we owe @thesahindia the payment for C+ review based on the terms and the job he completed. While this may have been easy to complete for @thesahindia, they didn't do anything wrong.

I'm just going to pay this out so we can move on.

**Comment by michaelhaxhiu** [comment] 2023-01-19 16:37
Invited Sahil to the job

**Comment by neil-marcellini** [comment] 2023-01-19 17:13
👍

**Comment by michaelhaxhiu** [comment] 2023-01-19 17:40
paid, closing.

**Closed by michaelhaxhiu** 2023-01-19 17:40 UTC
Labels: Reviewing, Engineering, Daily, Bug

**Comment by greg-schroeder** [comment] 2023-02-01 21:08
Looks like a potential regression here: https://github.com/Expensify/App/issues/14675 - did you want to work on this one @neil-marcellini or should I send it to `External`?
