### ISSUE TITLE
mWeb - Chat - Keyboard stays open in details page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19691] opened 2023-05-26 19:28 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19428

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Open group > send message > react with 2 or more accounts
4. Hover over the members in the list
5. Click on the user
6. Notice it should open the user detail page

## Expected Result:
The keyboard collapses when you go to the details page

## Actual Result:
Keyboard stays open in details page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** ew feature

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/e840decd40039193643fd7e4d4ff03d875118d416c86dfb1beda4c7d773a8779

https://platform.applause.com/services/links/v1/external/bba2d198b3761a3e16ff1e2bd872ff6519a6850d0db02e615edaab641688f571

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5bed8070cd317b5</li>
        <li>Upwork Job ID: 1672335678406971392</li>
        <li>Last Price Increase: 2023-06-23</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-05-26 19:48
@kbecciv as it stands right now, I cannot reproduce this based on the steps included above. The keyboard is closing for me when I do this. However, the steps above were not 100% clear to me, and it's difficult to validate whether the exact actions I took are correct, because there is no video on the bug report. 

https://github.com/Expensify/App/assets/54866469/bc5c5d8d-6fcc-4afd-8c54-fd937b2d6694

**Comment by joekaufmanexpensify** [comment] 2023-05-26 19:51
I'm going to assign this back to you for now, and close it. If the video I posted above is not what you intended with the above reproduction steps, could you please add a video showing the exact actions you took to encounter this issue? 

Then, please re-open the issue. If you re-open it between 2023-05-27 - 2023-06-06, please remove and re-add the bug label so someone else is assigned, as I'll be OOO then. Then, please assign me as an additional assignee too. 

Otherwise, feel free to just re-assign me. Thanks!

**Comment by kbecciv** [comment] 2023-06-01 12:51
@joekaufmanexpensify Checking with QA team, will update you shortly

**Comment by kbecciv** [comment] 2023-06-01 13:28
Issue is reproductible in build 1.3.22.0

https://github.com/Expensify/App/assets/93399543/a8a63629-6370-4344-a8a7-1dc4f018571f


![Screenshot_2023-06-01-16-02-34-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Expensify/App/assets/93399543/bd7a3a7c-64e5-4a31-a99f-b5011a0ef379)

**Comment by joekaufmanexpensify** [comment] 2023-06-23 21:35
@kbecciv Thanks for retesting this! The video was super helpful to to see the specific steps you were taking. I tested these specific steps on my end again now on V1.3.31-1 and cannot reproduce this. The keyboard is closing automatically for me when I take the action outlined above (you can see it for a second, but the momentary flicker of it closing doesn't feel like a bug to me, as it is closing automatically, and that's just the loading animation). 


https://github.com/Expensify/App/assets/54866469/db7642ef-bf46-41c8-add1-0ea0badd55d8


Going to close this one for now, as I'm unable to reproduce this with the updated steps.

**Closed by joekaufmanexpensify** 2023-06-23 21:35 UTC
Labels: Engineering, Daily, Internal, Bug
