### ISSUE TITLE
[HOLD for payment 2023-11-07] [$500] iOS: "Connect online with Plaid" popup is opened repeatedly after resuming the app.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27616] opened 2023-09-17 12:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to account settings >> Workspace.
2. Click on the workspace to view its settings.
3. Click on Cards or Reimbursements settings.
4. Select "Connect bank account" >> "Connect online with Plaid."
5. Swipe down from the top of the device's screen to view notifications.
6. Swipe up to hide notifications. 
7. Observe that the "Connect online with Plaid" popup opens again.

## Expected Result:
 "Connect online with Plaid" popup is opened only once
## Actual Result:
Connect online with Plaid popup is opened repeatedly
NOTE : Can be reproduced with the steps 5. Put app to background and  Resume app from background
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2d4fa16f-65eb-4d6f-a686-75eeadf7dc20

https://github.com/Expensify/App/assets/43996225/67f4a1c3-8ac2-4e82-8040-e7371b993059

https://github.com/Expensify/App/assets/43996225/80752677-a6d1-4f90-b579-09cd17632cbd

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694619647610939

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b7bfe22feb2b9545</li>
        <li>Upwork Job ID: 1703386549654556672</li>
        <li>Last Price Increase: 2023-09-17</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 26773159</li>
<li>tranvantoan-qn | Reporter | 26773161</li>
<li>pradeepmdk | Contributor | 27260708</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment] 2023-09-17 14:38
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
iOS: "Connect online with Plaid" popup is opened repeatedly after resuming the app

### What is the root cause of that problem?
when notification open apps going to background mode. so when the notification closed app again active and reconnect api triggering 

https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L352
when reconnect api calling `isLoadingReportData` false and true 
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L416 component is unmount and mount. so that popup is opening again 


### What changes do you think we should make in order to solve the problem?

here we need add one more 
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L352
based on this event https://plaid.com/docs/link/react-native/#onevent so that when modal is opened we can ignore here. we can store this event on onyx and we can check here 

and here no unmount handle we can dismiss the link on unmount
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/components/PlaidLink/index.native.js#L26

and we should call this api only `BankAccounts.openPlaidBankLogin`  `PLAID_LINK_TOKEN` not found.

**Comment by PiyushChandra17** [comment] 2023-09-18 00:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
iOS - Connect online with Plaid popup is opened repeatedly

### What is the root cause of that problem?
`PlaidLink` is not getting dismissed when the components unmount, Hence leads to memory leakage so we need to cleanup this component.

https://github.com/Expensify/App/blob/be0d9f4d85057e803783d9188fcbbed815866ab6/src/components/PlaidLink/index.native.js#L13-L28

and when we swipe down to view notifications, the app gets into background mode and when we swipe up the app activates again resulting in multiple pop overs

https://github.com/Expensify/App/blob/be0d9f4d85057e803783d9188fcbbed815866ab6/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L352


### What changes do you think we should make in order to solve the problem?
We need to apply following changes:
- Update `react-native-plaid-link-sdk` to the latest version
- import dismissLink from `react-native-plaid-link-sdk`
- update useEffect, add a clean up function and call dismissLink there

```
useEffect(() => {
        openLink({
            tokenConfig: {
                token: props.token,
            },
            onSuccess: ({publicToken, metadata}) => {
                props.onSuccess({publicToken, metadata});
            },
            onExit: (exitError, metadata) => {
                Log.info('[PlaidLink] Exit: ', false, {exitError, metadata});
                props.onExit();
            },
        });

        return () => {
            dismissLink()
        }

        // We generally do not need to include the token as a dependency here as it is only provided once via props and should not change
        // eslint-disable-next-line react-hooks/exhaustive-deps
        
    }, []);

```

### What alternative solutions did you explore? (Optional)
NA

### Result:

https://github.com/Expensify/App/assets/47579287/eac9eff8-6cbc-497a-b68f-fe4cf73bae58

**Comment by pradeepmdk** [comment] 2023-09-19 15:30
@ntdiary can you check my proposal https://github.com/Expensify/App/issues/27616#issuecomment-1722491760

we can check the plaid event so that we can know modal is open or not

**Comment by situchan** [comment] 2023-09-20 08:59
I can take this over based on @ntdiary's [request](https://expensify.slack.com/archives/C02NK2DQWUX/p1695199846239609)

**Comment by CortneyOfstad** [comment] 2023-09-22 12:34
@adelekennedy There is a known issue with the external label double-assigning, so going to remove you 👍

**Comment by CortneyOfstad** [comment] 2023-09-25 13:57
@situchan just checking where we're at with this — TIA!

**Comment by CortneyOfstad** [comment] 2023-09-29 11:48
@situchan any update on this?

**Comment by situchan** [comment] 2023-09-29 12:00
I'd like to confirm the expected behavior here.
When app goes to background, should we
- close plaid popup
- or keep it open and don't open another popup when reconnect (app becomes active again)?

**Comment by CortneyOfstad** [comment] 2023-10-03 16:33
@danieldoglas can you confirm the expected behavior for this? Question was posted [here](https://github.com/Expensify/App/issues/27616#issuecomment-1740774831) — TIA!

**Comment by danieldoglas** [comment] 2023-10-04 00:41
I think we should leave it open. Let's say the user needs to go to another app to get information they need to fill on Plaid, if the user goes back and the popup closed, that would be a bad experience. 

I do think we should somehow confirm how long the user was outside the app - I'm not sure what would happen on a long inactive time with the plaid popup open.

**Comment by CortneyOfstad** [comment] 2023-10-05 18:22
> Let's say the user needs to go to another app to get information they need to fill on Plaid

I didn't even think of that — excellent point

> I do think we should somehow confirm how long the user was outside the app

Is there a way for us to confirm this in some capacity? Or set a default option (i.e. any time after 2 minutes, lets say, the popup closes)?

**Comment by pradeepmdk** [comment] 2023-10-06 06:13
> I do think we should somehow confirm how long the user was outside the app - I'm not sure what would happen on a long inactive time with the plaid popup open.

I tested using this demo after 10 - 15 minutes still able to proceed next step

https://plaid.com/demo/

**Comment by danieldoglas** [comment] 2023-10-06 13:34
> Is there a way for us to confirm this in some capacity? Or set a default option (i.e. any time after 2 minutes, lets say, the popup closes)?

I think that we should let plaid decide that, and if we show an error the user should be able to close the popup and start again.

**Comment by danieldoglas** [comment] 2023-10-06 13:34
@CortneyOfstad I'll unassign myself from this issue since I'll be OOO for the next 2 weeks. Can you please add the engineering label again? Thanks!

**Comment by tgolen** [comment] 2023-10-09 15:19
I read through the issue and most of the proposals and I'm still not totally sure what solution we need or what functionality we desire to have. It sounds to me like this is the behavior we want:

- When the user opens the plaid modal, backgrounds the app, foregrounds the app, the plaid modal should remain open from before and we should not open a new modal.

If we all agree on that, then I think the proposals should be rewritten with that approach in mind. Most of the proposals right now seem to be about making sure the modal in closed when the component is unmounted (but it's not clear to me if this unmounting happens when the app is backgrounded or not). So, there might be a couple of pieces to this:

1. Keep the modal open while the app is backgrounded
2. Don't open a new modal when the app is foregrounded
3. Properly ensure the modal is closed and unmounted properly when it should be (ie. when the user closes the modal or when the modal closes at the end of the bank account flow).

I think I'd like to see a proposal that addresses those three points. Do you agree @situchan?

**Comment by situchan** [comment] 2023-10-09 15:25
Agree. Still waiting for solid proposal

**Comment by tgolen** [comment] 2023-10-09 21:36
Thank you @pradeepmdk. Am I correct in assuming that Onyx is used in the proposal so that the event data is not lost when the app is backgrounded?

**Comment by pradeepmdk** [comment] 2023-10-10 04:11
@tgolen we are getting event and store to onyx in the app background also.

https://github.com/Expensify/App/assets/16595846/09c6dbdf-8adb-4e0e-a2fe-c34995a9712e


https://github.com/Expensify/App/assets/16595846/f0644b0d-9565-461b-ab1a-c328f2f95cba


![Screenshot 2023-10-10 at 9 31 07 AM](https://github.com/Expensify/App/assets/16595846/7e7f4b86-eac5-4e89-ac61-c419a7d8785d)
@tgolen i need some clarfication here when plaid popup is loading mode there is no event. once loading the end then event start triggering. 

Option 1: so on loading screen time apps open from background it will close the modal and open it again. 

Options2: we can put mauallay OPEN event in the onyx here.
https://github.com/Expensify/App/blob/c77814fd5e643cba78e8c8294370d78f633a59c5/src/components/PlaidLink/index.native.js#L12

**Comment by tgolen** [comment] 2023-10-10 13:28
I think option 2 sounds fine as long as there is a code comment explaining
why that is necessary to do.

**Comment by pradeepmdk** [comment] 2023-10-10 14:00
@tgolen
> Why that is necessary to do.
 
as said here
> I need some clarification here when the plaid popup is loading mode there is no event. once loading the end the event starts triggering.

if the loading time app goes background and comes back again means we don't have any event data so the component will be destroyed and created again at the time the plaid popup modal is closed and opened again so we need to catch up on this case.
Note: On slow internet, it will take more time so as the time user goes back and forth popup will open and close again and again.

**Comment by tgolen** [comment] 2023-10-10 18:46
OK, sorry. I don't think I'm following you. Are you asking me something specifically, and if so, can you please clarify what you are asking?

**Comment by pradeepmdk** [comment] 2023-10-11 03:22
@tgolen Sorry that is my mistake, I already got the answer. https://github.com/Expensify/App/issues/27616#issuecomment-1755430832

and I updated the Proposal  @tgolen @situchan

**Comment by tgolen** [comment] 2023-10-11 15:18
Thank you! I think the proposal looks good. There are a few code issues I see, but that can be handled in the PR. @situchan are you fine with [this proposal](https://github.com/Expensify/App/issues/27616#issuecomment-1722491760)?

**Comment by tgolen** [comment] 2023-10-12 14:16
bump @situchan

**Comment by situchan** [comment] 2023-10-12 14:17
I will confirm today

**Comment by situchan** [comment] 2023-10-16 12:20
updating today, been focusing on deploy blocker issues

**Comment by pradeepmdk** [comment] 2023-10-16 15:41
@tgolen this issue fixed in internal PR?

**Comment by situchan** [comment] 2023-10-16 15:42
reviewing this right now

**Comment by situchan** [comment] 2023-10-16 16:34
Personally I think [this proposal](https://github.com/Expensify/App/issues/27616#issuecomment-1723526862) is better.
It doesn't require new Onyx key and already uses the existing value (`achData.subStep`) in `REIMBURSEMENT_ACCOUNT`.

**Comment by situchan** [comment] 2023-10-16 16:55
@tgolen ok I follow you. Let's go with new onyx key solution.

**Comment by tgolen** [comment] 2023-10-18 14:45
@pradeepmdk your proposal is accepted and you have the 🟢 to create a PR for it.

**Comment by situchan** [comment] 2023-10-18 14:46
@tgolen can you please unassign & reassign @pradeepmdk so that upwork automation works?

**Comment by pradeepmdk** [comment] 2023-10-18 14:49
Thanks @situchan  @tgolen . i am working on it

**Comment by CortneyOfstad** [comment] 2023-10-18 20:05
Heading OoO until Oct. 25, so reassigning BZ to keep an eye on things while I am gone 👍

**Comment by pradeepmdk** [comment] 2023-10-19 00:25
@situchan  PR is ready for review

**Comment by CortneyOfstad** [comment] 2023-10-25 17:40
I'm back from OoO @stephanieelliott so I can take this back over — thanks for keeping an eye on things while I was out!

@situchan bump on the PR review above

**Comment by situchan** [comment] 2023-10-25 17:43
I already reviewed. PR is waiting for final approval from @tgolen

**Comment by CortneyOfstad** [comment] 2023-10-31 14:40
@tgolen any update on the PR review? Thanks!

**Comment by situchan** [comment] 2023-10-31 14:43
> @tgolen any update on the PR review? Thanks!

merged and hit staging. GH will be updated upon next deploy

**Comment by CortneyOfstad** [comment] 2023-11-07 15:47
## Payment Breakdown

-  External issue reporter — paid @tranvantoan-qn $50 via Upwork as reporter
-  Contributor that fixed the issue — paid @pradeepmdk $500 via Upwork as Contributor
-  Contributor+ that helped on the issue and/or PR — paid @situchan $500 via Upwork as C+

Contracts have been ended in Upwork, so just need the checklist to be completed @situchan 👍

**Comment by situchan** [comment] 2023-11-07 15:54
I think this is eligible for bonus.
Contributor [assigned](https://github.com/Expensify/App/issues/27616#issuecomment-1768632118) on Oct 18
PR is ready for final review on Oct 20
Merged on Oct 27 but @tgolen was [OOO](https://github.com/Expensify/App/pull/29927#pullrequestreview-1701970183) for 1 week

**Comment by situchan** [comment] 2023-11-07 16:05
No PR caused this regression. The bug existed always from the beginning.

### Regression Test Proposal

1. Go to Settings > Workspaces > select workspace > Cards
2. Click "Connect bank account" > "Connect online with Plaid"
3. Verify that plaid popup shows
4. Swipe down from the top of the device's screen to view notifications.
5. Swipe up to hide notifications.
6. Verify that current plaid popup keeps open and another plaid popup doesn't show

**Comment by CortneyOfstad** [comment] 2023-11-07 16:16
> I think this is eligible for bonus.
> Contributor https://github.com/Expensify/App/issues/27616#issuecomment-1768632118 on Oct 18
> PR is ready for final review on Oct 20
> Merged on Oct 27 but @tgolen was https://github.com/Expensify/App/pull/29927#pullrequestreview-1701970183 for 1 week

@tgolen does that sound correct?

**Comment by CortneyOfstad** [comment] 2023-11-10 18:38
Bump @tgolen on the question above ^^^ thanks!

**Comment by tgolen** [comment] 2023-11-13 15:43
Yeah, that looks correct 👍

**Comment by CortneyOfstad** [comment] 2023-11-13 16:43
Thanks for the confirmation @tgolen!

@pradeepmdk @situchan — I sent you both bonus proposals in Upwork — please let me know once you accept and I can get those paid ASAP. Thanks!

**Comment by pradeepmdk** [comment] 2023-11-13 16:45
@CortneyOfstad i accepted the offer

**Comment by CortneyOfstad** [comment] 2023-11-13 23:39
Payments have been made successfully for the bonus amounts, so working on creating the regression test now 👍

**Comment by CortneyOfstad** [comment] 2023-11-13 23:42
Regression test created here — https://github.com/Expensify/Expensify/issues/336141. 

Closing as everything has been completed – thanks everyone!

**Closed by CortneyOfstad** 2023-11-13 23:42 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
