### ISSUE TITLE
Div: Payments -  Console error "Too many requests" appears when adding payment via Option Bank account 

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20392] opened 2023-06-07 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings / Payments
2. Add Payment method , chose Bank account
3. Click to Continue
4. Select any bank in my case Capital one
5. Solve CAPTCHA
6. Authenticate with the selected bank / Click to Continue

## Expected Result:
Console error does not appear when adding payment via Option Bank account 

## Actual Result:
Console error "Too many requests" appears when adding payment via Option Bank account 

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** n/a

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![photo_2023-06-03 18 03 54](https://github.com/Expensify/App/assets/93399543/432a7edc-ca10-4c1a-865f-44611c786d89)

https://github.com/Expensify/App/assets/93399543/d7e3a872-01cf-4b91-8a55-59e10a97464b

**Expensify/Expensify Issue URL:**

**Issue reported by:** @narzullome

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685797370122009

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-07 18:38
Duplicate https://github.com/Expensify/App/issues/16497

**Comment by narzullome** [comment] 2023-06-07 18:46
@alitoshmatov #16497 is about too many request #20392 here about console error

**Comment by muttmuure** [comment] 2023-06-13 01:07
The problem with the issue is that the console error is not specific. 

When creating a bug report with a console error, please ensure you are adding the exact console error so we can verify a fix is in place.

**Comment by muttmuure** [comment] 2023-06-13 18:57
I can't reproduce this specific console error, so I am going to add the needs reproduction label in case it comes up again in future.

**Closed by muttmuure** 2023-06-13 18:57 UTC
Labels: Daily, Needs Reproduction, Bug
