### ISSUE TITLE
[$250] iOS - Reset password - User can not see Error message when resetting password incorrectly

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#8440] opened 2022-04-01 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the New Expensify App
2. Sign into any valid account
3. Tap on the "Profile" icon on the top left
4. Tap on "Security"
5. Tap on "Change Password""
6. Enter an incorrect password in the "Current Password" field
7. Enter a correct Password that follows the requirement in "New Password" field
8. Tap on green "Save" button

## Expected Result:
The user expects to receive an error message relating to the current password being written incorrectly.

## Actual Result:
When the user taps "Save", nothing happens, the user can't see an error message. The error message will only be visible if the user scrolls down on the page

## Workaround:
Visual

## Platform:

Where is this issue occurring?

- iOS - Occurs in small screen devices. Able to reproduce in iPhone 8 and iPhone XR

**Version Number:** 1.1.49-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y 

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/161289519-3ab9bdd4-ba0c-4a03-8cd1-3309a49948b6.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2022-04-04 07:47
Internal: https://www.upwork.com/ab/applicants/1510886591673495552/job-details
External: https://www.upwork.com/jobs/~017dc0eab60756e368

**Comment by dharmik** [comment] 2022-04-04 13:08
Proposal:
Cause: Because of screen height is less and keyboard is open so we have multiple suggestion for this to resolved
Proposal 1) Once we have any issue in Current password or New password from API side we can hide that keyboard
Proposal 2) If we have any error come so we can make it scroll to bottom so that error message can be visible in all devices.

```diff
-import {View, ScrollView} from 'react-native';
+import {View, ScrollView, Keyboard} from 'react-native';
```

```diff
+componentDidUpdate () {
+        if(!_.isEmpty(this.props.account.error)){
+           Keyboard.dismiss() ====> Proposal 1
+           this.scrollRef.scrollToEnd() ====> Proposal 2 
+      }
+    }
```

```diff
<ScrollView
    style={styles.flex1}
    contentContainerStyle={styles.p5}
+   ref={ref => (this.scrollRef = ref)}
```

**Comment by parasharrajat** [comment] 2022-04-04 15:11
@kavimuru I can't see the opened keyboard in the video. Is there an active keyboard when this issue occurs?

**Comment by dharmik** [comment] 2022-04-10 15:49
@parasharrajat I confirmed, while we record screen from iPhone's record tool, keyboard is not visible in video.

CC @kavimuru

**Comment by parasharrajat** [comment] 2022-04-11 09:21
Ok. Thanks, @dharmik. I am not sure which of your suggestions should we go with. This totally depends on the design of the form. There is nothing good or bad here. @NikkiWines What do you think?

**Comment by NikkiWines** [comment] 2022-04-11 23:21
Hmm, I'm not sure this is still an issue? Tested on my device (iPhone 12 mini)  v1.1.54 and it looks like we now replace the `New password must be different` text with the error message: 

Also tested on an iPhone 8 sim (mWeb) to confirm

**iPhone 12 Mini**

https://user-images.githubusercontent.com/16747822/162847721-33c06ac1-4138-4cab-bc13-1e3dc6c05bf5.mov


**iPhone 8**

https://user-images.githubusercontent.com/16747822/162848689-f6fed681-3060-40b7-83ea-c1aa9139e434.mp4

**Comment by dylanexpensify** [comment] 2022-04-19 08:34
@parasharrajat @NikkiWines is this still an issue? If so, I can double price!

**Comment by parasharrajat** [comment] 2022-04-19 08:48
Seems like not anymore but I will test it when I am feeling better.

**Comment by NikkiWines** [comment] 2022-04-19 16:17
Yeah, I don't think this is an issue - my tests above show that the error message should be already visible no matter the screen size

**Comment by dharmik** [comment] 2022-04-19 16:57
@NikkiWines Issue it there. Can you please check video. It's iPhone 8.

CC @parasharrajat @dylanexpensify 

https://user-images.githubusercontent.com/1510175/164055940-a449371c-6571-4388-ad11-4d0c2345da02.mov

**Comment by NikkiWines** [comment] 2022-04-19 17:42
We could put that error message under the `Current password` field instead of that at bottom of the view. We could also be consistent and outline the field in red as we do for other errors.

**Comment by parasharrajat** [comment] 2022-04-19 17:45
I agree, Field should has red outline for the case.

**Comment by dharmik** [comment] 2022-04-19 18:14
@parasharrajat You mean to say like if I enter current password wrong and new will be valid highlight red border line, so in this case from API side we need some flag, which indicate us there is an issue from currentpassword. 

**Response from API:**
`{"UUID": "*********", "code": 666, "data": [], "htmlMessage": "", "jsonCode": 401, "message": "Your password changes could not be saved because the old password entered is incorrect.", "requestID": "6fe790be6a0b31b7-SJC", "title": "Changes could not be saved: Incorrect password", "type": "Expensify\\Libs\\Error\\ExpError"}`

We can check with Error message which is from response: `Your password changes could not be saved because the old password entered is incorrect.` 

What's your thought on above or do we need to modify from API side?

@parasharrajat @NikkiWines

**Comment by parasharrajat** [comment] 2022-04-19 18:16
You can use the jsonCode for that purpose.

**Comment by dharmik** [comment] 2022-04-19 19:45
Proposal: @parasharrajat @NikkiWines 

Changes: 

1. Field should have a red outline
2. We could put that error message under the `Current password`

Path: src/pages/settings/PasswordPage.js

```diff
                                 value={this.state.currentPassword}
                                 onChangeText={text => this.clearErrorAndSetValue('currentPassword', text)}
                                 returnKeyType="done"
-                                hasError={this.state.errors.currentPassword}
+                               hasError={this.state.errors.currentPassword || this.props.account.errorCode === 401}
-                                errorText={this.getErrorText('currentPassword')}
+                                errorText={this.getErrorText('currentPassword') || (!_.isEmpty(this.props.account.error) && this.props.account.errorCode === 401 && this.props.account.error)}
                                 onSubmitEditing={this.submit}
                             />
                         </View>
                         <View style={styles.mb6}>
                             <TextInput
                                 label={`${this.props.translate('passwordPage.newPassword')}*`}


-                        {_.every(this.state.errors, error => !error) && !_.isEmpty(this.props.account.error) && (
+                        {_.every(this.state.errors, error => !error) && !_.isEmpty(this.props.account.error) && this.props.account.errorCode !== 401 && (

```

Path: src/libs/actions/Session/index.js
```diff
 function clearAccountMessages() {
-    Onyx.merge(ONYXKEYS.ACCOUNT, {error: '', success: ''});
+    Onyx.merge(ONYXKEYS.ACCOUNT, {error: '', errorCode: 0, success: ''});
 }

```
Path: src/libs/actions/User.js

```diff
             if (response.jsonCode !== 200) {
                 const error = lodashGet(response, 'message', 'Unable to change password. Please try again.');
-                Onyx.merge(ONYXKEYS.ACCOUNT, {error});
+                const errorCode = lodashGet(response, 'jsonCode', 0);
+                Onyx.merge(ONYXKEYS.ACCOUNT, {error, errorCode});

```
Video:
https://user-images.githubusercontent.com/1510175/164083153-4837878e-2a58-4a39-81cd-ef0dcd271bd5.mov

**Comment by parasharrajat** [comment] 2022-04-19 21:09
Sorry, I don't like the proposal. Direct use of error codes in the component is prohibited. Also, are you following the Form guidelines? a server error should be shown above the button. But I am not sure if we need to do that for this issue.

**Comment by dharmik** [comment] 2022-04-19 21:13
If we have to display server error above button so we have check this proposal

https://github.com/Expensify/App/issues/8440#issuecomment-1087534048

@parasharrajat

**Comment by NikkiWines** [comment] 2022-04-19 21:22
Accounting for only that error also means will run into the same issue for other potential errors, like if the user is being throttled... 

I think we could either: 

1. Always remove the password hint when an error appears but keep the error message local to the text field they come from (if applicable) 
2. Always show errors in place of the password hint and highlight the appropriate box as necessary. 
3. Maybe show the non-password specific errors up top or something? 

I kind of prefer option 2, but we should consult @Expensify/design on this whatever path we choose: 

It would look something like this:  
| Default State | Current Password Error | New Password Error | Non Specific Error
| ------------- | ------------- | ------------- | ------------- |
| ![Screen Shot 2022-04-19 at 14 01 10](https://user-images.githubusercontent.com/16747822/164099974-cfd54808-22f8-49f5-a4a8-b71572de3ff4.png) | ![Screen Shot 2022-04-19 at 14 16 10](https://user-images.githubusercontent.com/16747822/164103820-7e88ab6e-fd32-4408-876b-6b5e24e2752c.png) | ![Screen Shot 2022-04-19 at 14 20 09](https://user-images.githubusercontent.com/16747822/164103895-93d6934f-82f9-4fb1-989f-e9d4a4f53f23.png) | ![Screen Shot 2022-04-19 at 13 59 47](https://user-images.githubusercontent.com/16747822/164101052-56deb3e4-e605-4fbc-a100-40c3a32b7220.png) |

**Comment by megankelso** [comment] 2022-04-19 22:21
thanks for laying these out! I agree with your recommendation

**Comment by parasharrajat** [comment] 2022-04-22 18:10
@dharmik Take a look at the new Room page for error management. Can we try to follow the same pattern as much as possible?

**Comment by dharmik** [comment] 2022-04-22 18:13
@parasharrajat can you please elaborate what is room page?

**Comment by parasharrajat** [comment] 2022-04-22 18:14
My Bad, this one https://github.com/Expensify/App/blob/main/src/pages/workspace/WorkspaceNewRoomPage.js

**Comment by dharmik** [comment] 2022-04-22 20:36
@parasharrajat Will check but I have one question like do we need to take it with this bug task, I guess it must be with refactor task.

**Comment by parasharrajat** [comment] 2022-04-22 22:10
I am not asking to do the whole refactor of the component instead follow the right pattern to show the error. We can try to do minimal alike changes. It is not about bugs or tasks but the code. Any code changes should follow the best current guidelines. Pattern change over time but it does not mean that we will refactor the whole working code. Refactoring is done when we touch that specific code during some bug/task.


Let me know if you get some ideas otherwise, I can help you find the best course through your proposals.

**Comment by dharmik** [comment] 2022-04-25 19:05
@parasharrajat As I saw for internal validation approach for both files are same. But there is no validation message which we display from API call in **WorkspaceNewRoomPage.js** we just display a top alert.

In **PasswordPage.js** we have to display error message as per API response and need to display inline.

Can you please share your suggestion, that help me a lot.

**Comment by parasharrajat** [comment] 2022-04-26 17:45
I will share some tomorrow. Not on high priority.

**Comment by parasharrajat** [comment] 2022-04-29 15:37
Ok, I looked at the code and it seems that this page needs a full refactor to follow the new form styles. For this particular issue, I am fine with taking the minimalistic approach. 

So @dharmik 's latest [proposal](https://github.com/Expensify/App/issues/8440#issuecomment-1104441168) would be fine. We can do the cleanup on the PR. 

cc: @NikkiWines 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by NikkiWines** [comment] 2022-04-29 22:39
I think the core of the proposal is good but that we could improve things by changing how we're storing errors in `PasswordPage.js`. Then we wouldn't even need to update `actions/User.js` or `Session/index.js`.

I suggest something like this (all in `PasswordPage.js`)

1. Add `componentDidUpdate()` function so that we update the UI when there is an error in `this.props.account.error`
```diff 
+    componentDidUpdate(prevProps) {
+        if (prevProps.account.error === this.props.account.error) {
+            return;
+        }
+
+        const incorrectCurrentPassword = this.props.account.error === 'Your password changes could not be saved because the old password entered is incorrect.';
+
+        // eslint-disable-next-line react/no-did-update-set-state
+        this.setState({errors: [{type: incorrectCurrentPassword ? 'currentPassword' : '', message: this.props.account.error}]});
+    }
```

2. Change errors storage in `validate()`
```diff
     validate() {
-        const errors = {};
+        const errors = [];
 
         if (!this.state.currentPassword) {
-            errors.currentPassword = true;
+            errors.push({type: 'currentPassword', message: this.props.translate('passwordPage.errors.currentPassword')});
         }
 
         if (!this.state.newPassword || !ValidationUtils.isValidPassword(this.state.newPassword)) {
-            errors.newPassword = true;
+            errors.push({type: 'newPassword', message: this.props.translate('passwordPage.errors.newPassword')});
         }
 
         if (this.state.currentPassword && this.state.newPassword && _.isEqual(this.state.currentPassword, this.state.newPassword)) {
-            errors.newPasswordSameAsOld = true;
+            errors.push({type: 'newPassword', message: this.props.translate('passwordPage.errors.newPasswordSameAsOld')});
         }
 
         this.setState({errors});
     }
```
3. Update how we clear errors in `clearErrorsAndSetValue()`
```diff
+    clearErrorAndSetValue(type, text) {
-    clearErrorAndSetValue(field, value, additionalErrorsToClear) {

+        const errors = _.isEmpty(this.state.errors) ? [] : _.chain(this.state.errors)
+            .reject(error => error.type === type)
+            .reject(error => error.type === '')
+            .value();
-        const errorsToReset = {
-            [field]: false,
-        };
-        if (additionalErrorsToClear) {
-            _.each(additionalErrorsToClear, (errorFlag) => {
-                errorsToReset[errorFlag] = false;
-            });
-        }

+        Session.clearAccountMessages();
 
-        this.setState(prevState => ({
-            [field]: value,
-            errors: {...prevState.errors, ...errorsToReset},
+        this.setState(() => ({
+            [type]: text,
+            errors,
         }));
     }
```
4. Update the UI so we display the error message in place of the passwordHint and outline the correct text box in red depending on the error type. This is fairly straightforward so I won't include a diff for it. 

Curious to your thoughts, happy to go with something else if you all feel this is a bigger change than what we want to implement.

**Comment by dharmik** [comment] 2022-05-02 04:05
@NikkiWines I think it's not good approach to check with error string which came from API. As per my knowledge this message will not change in future but who knows so we don't need to relay on it. If it change from API so it breaks.

``` diff
+  const incorrectCurrentPassword = this.props.account.error === 'Your password changes could not be saved because the old password entered is incorrect.';
```

May be I am wrong but this issue we can resolve it straight forward  [https://github.com/Expensify/App/issues/8440#issuecomment-1104441168](https://github.com/Expensify/App/issues/8440#issuecomment-1104441168) for me your suggestion looks complex [https://github.com/Expensify/App/issues/8440#issuecomment-1113842861](https://github.com/Expensify/App/issues/8440#issuecomment-1113842861)
But yes again may be I am wrong.

@parasharrajat Please share your suggestion on it.

**Comment by parasharrajat** [comment] 2022-05-02 13:08
I think the existing code for `validate` matches with other pages on the app so I would vote to keep that same.

**Comment by NikkiWines** [comment] 2022-05-03 18:08
Ok cool, it's definitely a larger change/refactor of how we validate the passwords, so I'm fine with @dharmik's proposal then👍 @dylanexpensify could you hire them for this job, please?

**Comment by dylanexpensify** [comment] 2022-05-04 09:48
On it!

**Comment by dylanexpensify** [comment] 2022-05-04 09:49
New postings since they expired.

Internal: https://www.upwork.com/ab/applicants/1521788921028734976/job-details
External: https://www.upwork.com/jobs/~0134ffabfdbf32f0ba

cc @dharmik @parasharrajat for applying!

**Comment by dharmik** [comment] 2022-05-05 05:08
@parasharrajat @NikkiWines Raised PR: https://github.com/Expensify/App/pull/8875

**Comment by dylanexpensify** [comment] 2022-05-06 10:33
I'm heading on parental leave so reassigning! Thank you to whoever gets assigned this! ❤️

**Comment by dharmik** [comment] 2022-05-10 19:14
@laurenreidexpensify Task is not yet assign me on upwork

**Comment by dharmik** [comment] 2022-05-11 18:10
@laurenreidexpensify Are you planning to create new upwork project?

**Comment by NikkiWines** [comment] 2022-05-12 16:46
@dharmik I've pinged @laurenreidexpensify about this, sorry about the delay

**Comment by laurenreidexpensify** [comment] 2022-05-13 13:30
Sorry I was AFK at a conference this week - actioning now

**Comment by laurenreidexpensify** [comment] 2022-05-13 13:33
Done

**Comment by dharmik** [comment] 2022-05-13 13:35
Thanks @laurenreidexpensify PR raised and verified by parasharrajat.
CC @NikkiWines

**Comment by laurenreidexpensify** [comment] 2022-05-25 10:45
Pr waiting on review from C+ and Expensify

**Comment by NikkiWines** [comment] 2022-06-17 18:54
We haven't seen much action on this and with our impending API refactors we'll be modifying this logic - I think maybe we can close this out for now and re-assess after N7? cc: @robertjchen @MonilBhavsar since this is tied to the Authenticate API refactor.

**Comment by robertjchen** [comment] 2022-06-22 02:07
Agreed, our upcoming refactors should address this or at least make this moot. Closing this out for now.

**Comment by dharmik** [comment] 2022-06-22 02:19
@robertjchen I already spent effort on this ticket and already raised PR and task already assign to me on upwork.

Can you help now what action have to apply on it.

**Comment by robertjchen** [comment] 2022-06-22 02:23
Ah apologies- I didn't have the full context here. I'll followup on next steps and keep you posted 🤔

**Comment by laurenreidexpensify** [comment] 2022-06-29 15:14
Paid and closing :)

**Closed by laurenreidexpensify** 2022-06-29 15:14 UTC
Labels: Reviewing, Exported, External, Engineering, Weekly
