### ISSUE TITLE
[HOLD for payment 2024-04-05] [$500] Avatar of user who sent message disappears after deleting comment

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#38830] opened 2024-03-22 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0 
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**  N/A
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
and log in as user A
2. In incognito log in as user B
3. As user A, open the chat with user B and send a message
4. As user B, send two messages
5. As user B, delete the last sent message

## Expected Result:
The avatar of user B is still displayed next to the sent message

## Actual Result:
The avatar of user B disappears after deleting a message

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/2be5c4d8-56ac-4678-abe9-b8cdfa6f1c44

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010d8a4fbe15a51d30</li>
        <li>Upwork Job ID: 1771294914072977408</li>
        <li>Last Price Increase: 2024-03-22</li>
<li>Automatic offers: </li>
<ul>
<li>Pujan92 | Reviewer | 0</li>
<li>gijoe0295 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by kavimuru** [comment] 2024-03-22 19:40
@bondydaa FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-03-22 19:40
We think this bug might be related to #vip-vsb

**Comment by bondydaa** [comment] 2024-03-22 21:28
👀 looking into this

**Comment by bondydaa** [comment] 2024-03-22 21:37
I'm sus of this PR https://github.com/Expensify/App/pull/36747, reverting locally and testing.

**Comment by bondydaa** [comment] 2024-03-22 21:41
🚫 nope nevermind still reproducible

**Comment by bondydaa** [comment] 2024-03-22 21:56
heh was probably the big comment linking PR https://github.com/Expensify/App/pull/30269/ then 😅  but i don't know that we're going to revert that. 

I'm going to add external b/c I think the existing proposal makes sense, i'm a little confused how this works without anything checking for if the comment is deleted or not (ie: this should probably happen on production as well but 🤷).

**Comment by Pujan92** [comment] 2024-03-23 03:05
Thanks for the proposal @gijoe0295. Yes, it seems to be a regression from https://github.com/Expensify/App/pull/30269.

> Before that PR, we [filtered out report actions by `shouldReportActionBeVisible`](https://github.com/margelo/expensify-app-fork/blob/300645e15a17b26ae8476fcb7670c2b31cdb6b79/src/libs/ReportActionsUtils.ts#L446-L452) which also filtered deleted actions. But after that, we [retrieved all report actions](https://github.com/Expensify/App/blob/665a8adfdb3239667270b5d23c12287894763d7d/src/pages/home/ReportScreen.tsx#L674).

I do not fully agree with the RCA as earlier also we retrieved all actions in `ReportScreen`, we have just renamed the props there. Or maybe I misunderstood your RCA which you can help me to correct. 
Issue seems to be inconsistent data passed to the `InvertedFlatList` and `renderItem` 's `isConsecutiveActionMadeByPreviousActor` condition. As with that PR [here](https://github.com/Expensify/App/pull/30269/files#diff-42d45a343b031265784f22ea27e4502b3c1968e492b1fc83154414b584d59217R605) we are passing `sortedVisibleReportActions` to the `InvertedFlatList`, same(`sortedVisibleReportActions` instead of `sortedReportActions`) we need to pass to `isConsecutiveActionMadeByPreviousActor` .
https://github.com/Expensify/App/blob/32a4d9f8aa933495dd15e5720b2c5bc82e1ffd6f/src/pages/home/report/ReportActionsList.tsx#L521


>We should use [sortedVisibleReportActions](https://github.com/Expensify/App/blob/665a8adfdb3239667270b5d23c12287894763d7d/src/pages/home/report/ReportActionsList.tsx#L180) as a param for isConsecutiveActionMadeByPreviousActor

@gijoe0295 Your solution looks correct to me. cc: @bondydaa 

🎀👀🎀 C+ reviewed

**Comment by Pujan92** [comment] 2024-03-23 10:08
> @Pujan92 You can compare `getSortedReportActionsForDisplay` [before](https://github.com/margelo/expensify-app-fork/blob/300645e15a17b26ae8476fcb7670c2b31cdb6b79/src/libs/ReportActionsUtils.ts#L446-L452) and [after](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/libs/ReportActionsUtils.ts#L577-L585) the PR to see. Note that after the PR, we [enabled `shouldIncludeInvisibleActions`](https://github.com/Expensify/App/blob/191d9326cd6cdbdc76d24ddf09f8a2f5fe6295ec/src/pages/home/ReportScreen.tsx#L678) in `ReportScreen`.

Ah, I see. Thanks @gijoe0295. So earlier from `ReportScreen` we are passing only visible actions but after this PR it is passing all report actions. Whereas in the `ReportActionsList` we created the `sortedVisibleReportActions`  and passed it to the `InvertedFlatList` but missed updating the `isConsecutiveActionMadeByPreviousActor` argument for `displayAsGroup` prop.

**Comment by bondydaa** [comment] 2024-03-25 15:16
Great thank you for the discussion and helping get to the bottom of all that 🙇.

I think we should still block the deploy for this one since it is pretty bad to have a message from a different user end up getting shown as if it was from the wrong user.

**Comment by bondydaa** [comment] 2024-03-25 19:06
merged the PR, requesting a CP now.

**Comment by bondydaa** [comment] 2024-03-25 20:28
@kavimuru can you retest this and confirm it's fixed, CP should have been completed about 40 minutes ago so should be ready on staging.

**Comment by yuwenmemon** [comment] 2024-03-25 22:33
Can confirm this does not happen on staging anymore. Removing the blocker label

**Comment by bondydaa** [comment] 2024-04-15 18:04
@anmurali will handle payment

**Comment by Pujan92** [comment] 2024-04-15 18:31
**BugZero Checklist**: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [X] [@Pujan92] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/30269
- [X] [@Pujan92] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/30269/files#r1566259198
 - [X] [@Pujan92] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: NA
 - [X] [@Pujan92] Determine if we should create a regression test for this bug. **Yes**
 - [X] [@Pujan92] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.
 
### Regression Test Steps

1. Send consecutive messages from User A to User B and vice-versa
2. Delete any of the message
3. Verify that the senders info shows correctly with the messages

Do you agree 👍 or 👎 ?

**Comment by anmurali** [comment] 2024-04-23 09:34
Paid and added regression test.

**Closed by anmurali** 2024-04-23 09:34 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
