### ISSUE TITLE
[HOLD for payment 2024-01-25] [$250] Scan - Message for Merchant requirement disappears after entering amount for failed scanning

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33876] opened 2024-01-03 16:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.21-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to 1:1 DM > + Request money > Scan.
2. Create a scan request with a receipt that will fail the scanning.
3. When the scanning fails, navigate to request details page.
4. Click Amount and enter an amount.

## Expected Result:
Error message for merchant will not disappear because the merchant is not entered yet.

## Actual Result:
The error message for empty merchant disappears after entering amount.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/525cae4b-7a8f-4291-a98e-ead5ffd87f88

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164ff788c4c52bbb1</li>
        <li>Upwork Job ID: 1742581879623811072</li>
        <li>Last Price Increase: 2024-01-10</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 28092728</li>
<li>namhihi237 | Contributor | 28092729</li>
</ul></li>
    </ul>
</details>

**Comment by namhihi237** [comment] 2024-01-03 16:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Error message for merchant will not disappear because the merchant is not entered yet.
### What is the root cause of that problem?
In here when we add the amount the function will be return false, so the error on merchant disappear
```js
function hasMissingSmartscanFields(transaction: OnyxEntry<Transaction>): boolean {
    return Boolean(transaction && hasReceipt(transaction) && !isDistanceRequest(transaction) && !isReceiptBeingScanned(transaction) && areRequiredFieldsEmpty(transaction));
}
```
In here the `isMerchantMissing` is true but isFromExpenseReport is false with chat 1-1.
https://github.com/Expensify/App/blob/273fa79f28d083ac69603dd633af6e030cc30ed2/src/libs/TransactionUtils.ts#L156-L161
### What changes do you think we should make in order to solve the problem?
I think we should update
```js
    const isFromExpenseReport = parentReport?.type === CONST.REPORT.TYPE.EXPENSE  || parentReport?.type === 'iou'
```
### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-03 16:40
As per https://github.com/Expensify/App/issues/33786#issuecomment-1872379010, the merchant is not required on the 1:1 requests with receipts. So I'd say this is an expected behavior.

@mountiny could you please confirm/correct?

**Comment by paultsimura** [comment] 2024-01-03 16:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The merchant error is shown even if the merchant is not required on failed scan.

### What is the root cause of that problem?

We calculate the `hasErrors` value here using `TransactionUtils.hasMissingSmartscanFields`, which checks for missing amount, date, and merchant (if the merchant is required):

https://github.com/Expensify/App/blob/3c58a05d2b18aaed14b5af6ed7a7d4be769a47df/src/components/ReportActionItem/MoneyRequestView.js#L169-L173

However, when showing the merchant error, we check only `hasErrors`  (which comes from the missing amount) and the empty merchant, without checking if the merchant is required:

https://github.com/Expensify/App/blob/3c58a05d2b18aaed14b5af6ed7a7d4be769a47df/src/components/ReportActionItem/MoneyRequestView.js#L241-L250

### What changes do you think we should make in order to solve the problem?
We should introduce another variable, e.g.:

```js
val isMerchantRequired: TransactionUtils.isMerchantRequired(transaction);
```

And use it as well to determine whether to show the merchant error:

```js
                 <OfflineWithFeedback pendingAction={lodashGet(transaction, 'pendingFields.merchant') || lodashGet(transaction, 'pendingAction')}>
                        <MenuItemWithTopDescription
                            description={translate('common.merchant')}
                            title={isEmptyMerchant ? '' : transactionMerchant}
                            interactive={canEdit}
                            shouldShowRightIcon={canEdit}
                            titleStyle={styles.flex1}
                            onPress={() => Navigation.navigate(ROUTES.EDIT_REQUEST.getRoute(report.reportID, CONST.EDIT_REQUEST_FIELD.MERCHANT))}
                            brickRoadIndicator={hasErrors && isEmptyMerchant && isMerchantRequired ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : ''}
                            error={hasErrors && isEmptyMerchant && isMerchantRequired ? translate('common.error.enterMerchant') : ''}
                        />
                    </OfflineWithFeedback>
```

### What alternative solutions did you explore? (Optional)

**Comment by rrrshtt** [comment] 2024-01-03 17:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message disappears in fields that were not touched.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b3f1456b2c4c997acf273041578a22855f944804/src/components/ReportActionItem/MoneyRequestView.js#L169-173
Here, we check on every re-render that we have error.

### What changes do you think we should make in order to solve the problem?
We can simply check if this request has errors the first time we enter it, put `hasError` in a state, and change it only in `useEffect`. It seems like the transaction is completely refreshed on the backend, which is why we don't get an error after the first saving.

### What alternative solutions did you explore? (Optional)

**Comment by mountiny** [comment] 2024-01-04 15:03
Correct this should not be requried, I will keep this until I confirm

**Comment by mountiny** [comment] 2024-01-04 15:05
The merchant should not be showing as required in the IOU case I think

**Comment by shubham1206agra** [comment] 2024-01-05 06:27
@mountiny Should I go ahead and select @paultsimura's proposal in this case?

**Comment by DylanDylann** [comment] 2024-01-05 09:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The error message for empty merchant disappears after entering amount.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/6fad557b600c658a06368697a791ff1acc7488d5/src/components/ReportActionItem/MoneyRequestView.js#L287-L288

Currently, the `merchant` field is required in all cases

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/6fad557b600c658a06368697a791ff1acc7488d5/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L316
We should apply the same condition like we did in the confirmation page, the merchant field is required only if  `isPolicyExpenseChat && !isScanRequest`

https://github.com/Expensify/App/blob/6fad557b600c658a06368697a791ff1acc7488d5/src/components/ReportActionItem/MoneyRequestView.js#L287-L288

update to 
```
    const isScanRequest = TransactionUtils.isScanRequest(transaction);
```
```
brickRoadIndicator={hasViolations('merchant') || (hasErrors && isPolicyExpenseChat && !isScanRequest && isEmptyMerchant) ? CONST.BRICK_ROAD_INDICATOR_STATUS.ERROR : ''}
error={hasErrors && isPolicyExpenseChat && !isScanRequest && isEmptyMerchant ? translate('common.error.enterMerchant') : ''}

```

### What alternative solutions did you explore? (Optional)
NA

**Comment by mountiny** [comment] 2024-01-05 14:22
Still confirming

**Comment by mountiny** [comment] 2024-01-08 23:36
Getting to conclussion in slack but I think for the IOU case we can close this

**Comment by paultsimura** [comment] 2024-01-08 23:41
> for the IOU case we can close this

@mountiny if we do nothing here, the issue would be that we'll show the "Missing merchant" error for the IOU, while the merchant isn't actually required. I described more RCA details in [my proposal](https://github.com/Expensify/App/issues/33876#issuecomment-1875683213), might giving it a look just for the context?

**Comment by mountiny** [comment] 2024-01-10 14:43
I am really not sure if it was @namhihi237 or @paultsimura with the correct solution first because of the edits. 

I think @paultsimura is assigned to couple issues now so might be better to have @namhihi237 work on this one, what is your availability?

**Comment by namhihi237** [comment] 2024-01-10 14:45
Yeah i am available now

**Comment by mountiny** [comment] 2024-01-10 14:45
@namhihi237 is $250 ok? I think the scope has changed here and the actual change is rather simple

**Comment by paultsimura** [comment] 2024-01-10 14:55
@mountiny the original proposal of @namhihi237 was to revert https://github.com/Expensify/App/issues/33786 (which is far from the truth).
It was changed to the current view only on Jan 4, while mine was posted on Jan 3, and the edits were mostly cosmetic (still all of them were made on Jan 3).

<img width="627" alt="image" src="https://github.com/Expensify/App/assets/12595293/46124b0f-5bb0-4f58-a9c4-95d4b641f44f">

I'm assigned to a couple of issues, but most of them are waiting to be merged by Engineers or reviewed by C+ 😞

**Comment by shubham1206agra** [comment] 2024-01-10 15:01
Ouch, classical case of https://expensify.slack.com/archives/C01GTK53T8Q/p1703083893742679

**Comment by mountiny** [comment] 2024-01-10 18:15
Yep the edits are confusing, sorry for this, I am sure you will land many other issues though

**Comment by NicMendonca** [comment] 2024-01-29 21:30
@shubham1206agra  can you accept the offer please?

**Comment by NicMendonca** [comment] 2024-01-29 21:30
@namhihi237 you've been paid!

**Comment by shubham1206agra** [comment] 2024-01-30 06:22
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@shubham1206agra] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/33850
* [x]  [@shubham1206agra] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/33850#issuecomment-1916154480
* [x]  [@shubham1206agra] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Not Required
* [x]  [@shubham1206agra] Determine if we should create a regression test for this bug. No as the steps should be present in general flow itself.
* [x]  [@shubham1206agra] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@NicMendonca] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Closed** 2024-01-30 14:10 UTC
Labels: External, Weekly, Awaiting Payment, Bug
