### ISSUE TITLE
[HOLD for payment 2023-12-28] [$500] Thread - Admin lands in [Delete message] after login when employee subscribes to welcome message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30644] opened 2023-10-31 15:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-1
**Reproducible in staging?:** Y
**Reproducible in production?:**N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/27994
## Action Performed:
1. [Admin] Invite employee to a workspace
2. [Admin] Log out
3. [Employee] Open the workspace chat > right-click on the welcome message > Subscribe to thread
4. [Admin] Log in

## Expected Result:
Admin lands on valid chat report

## Actual Result:
Admin is redirected to [Delete message] from the welcome message thread. Sometimes 'welcome message' thread. opens without [Deleted message]

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/0e5c4cba-9bc3-4b16-b762-58aa0f9cadcb

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01853efb86b5ca79a2</li>
        <li>Upwork Job ID: 1721684595387928576</li>
        <li>Last Price Increase: 2023-11-07</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27759906</li>
<li>tienifr | Contributor | 27759907</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @srikarparsi</details>

**Comment by Beamanator** [comment] 2023-10-31 21:12
In [this thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1698767693383489), @chiragsalian and @AndrewGable and I agreed this is a pretty weird edge case, so NAB - also ccing @srikarparsi since this most likely came from https://github.com/Expensify/App/pull/27994

**Comment by srikarparsi** [comment] 2023-11-07 00:22
Hey this is reproducible and I believe this and I believe this can be a frontend fix so I'm making this external

**Comment by NicMendonca** [comment] 2023-11-10 14:13
@aimane-chnaif can you please check out this proposal ^^

**Comment by NicMendonca** [comment] 2023-11-13 13:58
@aimane-chnaif bumped you [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1699883915568249)!

**Comment by srikarparsi** [comment] 2023-11-21 00:13
Cool, looks good to me as well. Let's do this for `reply in thread` as well as you've suggested :)

**Comment by srikarparsi** [comment] 2023-11-27 04:32
I think we should keep "Unsubscribe from thread" Otherwise there is no way to remove that thread from the LHN right?

**Comment by NicMendonca** [comment] 2023-12-28 18:44
@aimane-chnaif @tienifr you've both been paid!


@aimane-chnaif bump on the BZ checklist!

**Comment by NicMendonca** [comment] 2024-01-02 17:12
@srikarparsi bump! https://github.com/Expensify/App/issues/30644#issuecomment-1871413138

**Comment by srikarparsi** [comment] 2024-01-05 22:05
Left a comment [here](https://expensify.slack.com/archives/C03U7DCU4/p1704492310895289?thread_ts=1700169906.231609&cid=C03U7DCU4) to confirm.

**Comment by srikarparsi** [comment] 2024-01-08 22:35
Still waiting on a response, will touch back on the thread tomorrow.

**Comment by s77rt** [comment] 2024-01-13 12:31
@srikarparsi 

> I think we should keep "Unsubscribe from thread" Otherwise there is no way to remove that thread from the LHN right?

I think we should have removed it. There should be no more cases where you'd be able to subscribe to a whisper message in the first place.

(Coming from https://github.com/Expensify/App/issues/34428)

**Comment by srikarparsi** [comment] 2024-01-16 06:40
Hm, okay, I'll respond in this issue [here](https://github.com/Expensify/App/issues/34428)

**Comment by srikarparsi** [comment] 2024-01-22 05:52
Not overdue, bumped [here](https://expensify.slack.com/archives/C03U7DCU4/p1705902736958519?thread_ts=1700169906.231609&cid=C03U7DCU4)

**Comment by NicMendonca** [comment] 2024-01-31 15:58
I am going on leave so have to re-assign this. 

Both contributors have just been paid. We're just waiting on feedback from @srikarparsi on expected behaviour for a regression test

**Comment by srikarparsi** [comment] 2024-02-07 05:42
Yup! That seems like the case, @conorpendergrast in that case I believe we can pay out @aimane-chnaif and @tienifr for the PR

**Comment by conorpendergrast** [comment] 2024-02-07 09:56
Well then, today I will pay out based on [this comment](https://github.com/Expensify/App/issues/30644#issuecomment-1865487740). Thank you for confirming @srikarparsi!

**Comment by conorpendergrast** [comment] 2024-02-07 09:59
Contracts ended. I think we still need the C+ checklist, in particular for regression tests now that we have confirmed the expected behaviour

**Comment by conorpendergrast** [comment] 2024-02-07 21:12
Regression test created: https://github.com/Expensify/Expensify/issues/367771

All done, thanks everyone

**Closed by conorpendergrast** 2024-02-07 21:12 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
