### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] Emoji Picker don't hide when composer is hide

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20765] opened 2023-06-14 18:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Action Performed:
1. Login with user A --> create new workspace--> invite user B
2. Open announce room of above workspace --> detail chat --> settting --> who can post --> choose All member
3. Login with user B on another device --> Open announce chat of above workspace --> open emoji picker
4. On user A choose who can post --> admin only

## Expected Result:
 Emoji Picker should be hide like main composer

## Actual Result:
Emoji Picker don't hide

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/526d4bfe-96fd-47dc-83b5-18364d0f62f0

https://github.com/Expensify/App/assets/93399543/35c485ca-611f-429b-baec-13406affe9fa

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dukenv0307

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686211761685699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012f927fc251d62d87</li>
        <li>Upwork Job ID: 1669121681673699328</li>
        <li>Last Price Increase: 2023-06-21</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment] 2023-06-14 18:05
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a room permissions are changed (who can post) and the members have `EmojiPicker` open then it is not closed automatically like `ReportActionCompose`.
### What is the root cause of that problem?
We hide the `ReportActionCompose` component when a room is archived, permissions are changed or there are errors.
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/report/ReportFooter.js#L63-L64
But `EmojiPicker` is not rendered conditionally in `ReportScreen` -
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/ReportScreen.js#L352
I tested and the same issue also happens when workspace is archived or there are errors.
### What changes do you think we should make in order to solve the problem?

We should use the same conditions while rendering `EmojiPicker` -
```javascript
const isAllowedToComment = ReportUtils.isAllowedToComment(props.report);
const hideComposer = isArchivedRoom || !_.isEmpty(props.errors) || !isAllowedToComment;
```
But to keep the code DRY we should make a new utility function in `ReportUtils` and reuse it in both places - `ReportFooter` and `ReportScreen`.
### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-06-14 18:13
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When a room permissions are changed (who can post) and the members have `EmojiPicker` open then it is not closed automatically like `ReportActionCompose`.
### What is the root cause of that problem?
We hide the `ReportActionCompose` component when a room is archived, permissions are changed or there are errors.
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/report/ReportFooter.js#L63-L64
But `EmojiPicker` is not rendered conditionally in `ReportScreen` -
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/ReportScreen.js#L352
I tested and the same issue also happens when workspace is archived or there are errors.
### What changes do you think we should make in order to solve the problem?

We should use the same conditions while rendering `EmojiPicker` -
```javascript
const isAllowedToComment = ReportUtils.isAllowedToComment(props.report);
const hideComposer = isArchivedRoom || !_.isEmpty(props.errors) || !isAllowedToComment;
```
But to keep the code DRY we should make a new utility function in `ReportUtils` and reuse it in both places - `ReportFooter` and `ReportScreen`.
### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-06-14 18:19
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
When room permissions are changed (from all members can post to only admins) and the members have `EmojiPicker` open then it is not closed automatically like `ReportActionCompose`.
### What is the root cause of that problem?
We hide the `ReportActionCompose` component when a room is archived, permissions are changed or there are errors.
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/report/ReportFooter.js#L63-L64
But `EmojiPicker` is not rendered conditionally in `ReportScreen` -
https://github.com/Expensify/App/blob/24945f2a8b7607e45d56d75bde6bb0bf772a39ce/src/pages/home/ReportScreen.js#L352
I tested and the same issue also happens when workspace is archived or there are errors.
### What changes do you think we should make in order to solve the problem?

We should use the same conditions while rendering `EmojiPicker` -
```javascript
const isAllowedToComment = ReportUtils.isAllowedToComment(props.report);
const hideComposer = isArchivedRoom || !_.isEmpty(props.errors) || !isAllowedToComment;
```
But to keep the code DRY we should make a new utility function in `ReportUtils` and reuse it in both places - `ReportFooter` and `ReportScreen`.
### What alternative solutions did you explore? (Optional)
NA

**Comment by spcheema** [comment] 2023-06-15 02:24
# Proposed solution 

### Please re-state the problem that we are trying to solve in this issue.
Emoji Picker should be hide like main composer
 

**What is the root cause of that problem?**

Emoji picker is not wrapped inside conditions like `<ReportActionCompose` on `ReportFooter.js`

https://github.com/spcheema/expensify-app/blob/main/src/pages/home/report/ReportFooter.js#L82



**What changes do you think we should make in order to solve the problem?**

Following changes are to hide Emoji picker 

* Add utility method to check if a given report is composable.
```javascript
/**
 * Returns true if a given report is eligible for composable actions like comment, reply or reactions
 * @param {Object} report
 * @returns {Boolean}
 */
function isComposableReport(report) {
    return !isArchivedRoom(report) && isAllowedToComment(report);
}

```
* Render `EmojiPicker` is a given report is not archived or writeable by given user on file `ReportScreen.js`
https://github.com/spcheema/expensify-app/blob/main/src/pages/home/ReportScreen.js#L352
```javascript

    { ReportUtils.isComposableReport(this.props.report) && (
        <EmojiPicker ref={EmojiPickerAction.emojiPickerRef} />
    )}
    
```

* Update `ReportFooter` function to use utility method on file `ReportFooter.js`

```javascript

function ReportFooter(props) {
    const chatFooterStyles = {...styles.chatFooter, minHeight: !props.isOffline ? CONST.CHAT_FOOTER_MIN_HEIGHT : 0};
    const isArchivedRoom = ReportUtils.isArchivedRoom(props.report);
    const hideComposer = !ReportUtils.isComposableReport(props.report);

    // ... rest of the code
}

```
 
### What alternative solutions did you explore? (Optional)
NA

**Comment by Nikhil-Vats** [comment] 2023-06-15 03:05
@spcheema I have already written in my proposal that I would use a utility function in ReportUtils for doing this to follow DRY.

You have posted the code diff of the same which is not a new approach but exactly same as my proposal.

**Comment by spcheema** [comment] 2023-06-15 03:20
@Nikhil-Vats I spend my time finding the solution and posted it here.

Not sure why it's hurting you. You have written that and I did use that method not sure why you are here to do useless argue.

**Comment by Nikhil-Vats** [comment] 2023-06-15 04:22
Hey @spcheema, it is mentioned in the [contribution guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job).
> Note: Before submitting a proposal on an issue, be sure to read any other existing proposals. ALL NEW PROPOSALS MUST BE DIFFERENT FROM EXISTING PROPOSALS. The difference should be important, meaningful or considerable.

**Comment by spcheema** [comment] 2023-06-15 04:24
@Nikhil-Vats if there is room one can make different proposal. Right?

**Comment by spcheema** [comment] 2023-06-15 04:27
I believe my proposal is different because it has got complete POC where you just talk about things can be done without any POC/testing

**Comment by arielgreen** [comment] 2023-06-16 02:48
Reassigning, team change

**Comment by bfitzexpensify** [comment] 2023-06-16 07:27
@thesahindia few prposals for you to review when you get a chance!

**Comment by Nikhil-Vats** [comment] 2023-06-16 12:19
I don't think users should be able to edit their messages or open emoji menu in edit message composer when permission is changed to admins only.  It doesn't make sense logically. We should remove edit composer in [ReportActionItem](https://github.com/Expensify/App/blob/bd0e843621dda8ad1fb31595f0f923a9d9447cf8/src/pages/home/report/ReportActionItem.js#L105) the same way we are removing the main composer using the new utility function.

**Comment by Nikhil-Vats** [comment] 2023-06-16 12:42
Sure @thesahindia. Started a discussion [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686919337180109).

**Comment by bfitzexpensify** [comment] 2023-06-20 07:26
I also agree with your suggestion @Nikhil-Vats - let's move forward with also disabling the ability to edit comments.

**Comment by Nikhil-Vats** [comment] 2023-06-20 08:02
We have the following actions for messages right now -

<img width="1063" alt="image" src="https://github.com/Expensify/App/assets/31413407/64d52c6b-9cc4-48e3-bd15-1f1bbe2200f8">

We should remove -
1. Edit comment
2. Delete comment

I am not sure about reply in thread but I think emoji reactions are fine maybe. We can ask for more opinions on slack thread.

@bfitzexpensify @thesahindia @Beamanator

**Comment by Beamanator** [comment] 2023-06-20 09:45
@dukenv0307 @Nikhil-Vats can we continue the convo in slack until we have a resolution please?

**Comment by bfitzexpensify** [comment] 2023-06-21 05:40
OK, looks like we've reached a consensus in Slack, all we'll want to do here is ensure the emoji picker via composing a new message is hidden when the permissions are changed. Nothing else needs to be adjusted.

**Comment by bfitzexpensify** [comment] 2023-06-29 13:19
Just noting here I'm going to consider this eligible for the #urgency bonus. It missed by a whisker (30 minutes) and that mostly came down to timezone differences.

**Comment by bfitzexpensify** [comment] 2023-07-06 09:05
Offers sent out @thesahindia @dukenv0307 

@thesahindia, please complete the BZ checklist when you get a chance - thanks!

**Comment by bfitzexpensify** [comment] 2023-07-10 13:52
Thanks @thesahindia - proposed the test steps in https://github.com/Expensify/Expensify/issues/298637. 

So, we're all done here! Thanks everyone

**Closed by bfitzexpensify** 2023-07-10 13:52 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-24 05:29
@bfitzexpensify Can you please provide a payment summary on this issue so that I can issue payment via NewDot? Thanks!

**Comment by bfitzexpensify** [comment] 2023-08-24 07:54
Payment summary: 

C+: @thesahindia - $1500 (C+ review & urgency bonus). To be paid via manual request 
Contributor: @dukenv0307 - reporting + contributor work + urgency bonus. $1750 paid via Upwork

**Comment by JmillsExpensify** [comment] 2023-08-30 04:15
Reviewed the details for @thesahindia. $1,500 approved for payment via NewDot based on BZ summary above.
