### ISSUE TITLE
[$500] Emojis - "No results found" message appears when select "Hand" from keyboard suggestion

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#31780] opened 2023-11-23 11:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Open New Expensify app
2. Open any conversation
3. Navigate to emoji picker
4. Type "hand" into search bar
5. Choose emoji from keyboard suggestion

## Expected Result:
Selected emoji should be applied and not error messages should appear

## Actual Result:
"No results found" message appears when select "Hand" from keyboard suggestion

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/5857c889-495f-489b-8814-b49deffe0dcc

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01018ef056ade09956</li>
        <li>Upwork Job ID: 1727652489576235008</li>
        <li>Last Price Increase: 2023-12-07</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2023-11-23 11:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
In the EmojiPickerMenu, we do not support search by an actual emoji, only by the text:

https://github.com/Expensify/App/blob/03a9fe09d8d736b5fc268e885a5f56b878846074/src/components/EmojiPicker/EmojiPickerMenu/index.js#L167-L189

### What changes do you think we should make in order to solve the problem?

We should check if the `searchTerm` is an emoji. If yes – look for an emoji with the exact match instead of an emoji suggestion by text.



### What alternative solutions did you explore? (Optional)

**Comment by ta106** [comment] 2023-11-23 11:49
Proposal
Please re-state the problem that we are trying to solve in this issue.
When searching by an actual emoji, the EmojiPicker doesn't suggest an emoji with an exact match.

What is the root cause of that problem?

In the EmojiPickerMenu, we don't catch if an emoji is selected

What changes do you think we should make in order to solve the problem?

We should check if the searchTerm is an emoji, we should make it the selected emoji to be pushed

**Comment by yh-0218** [comment] 2023-11-23 13:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we search using an emoji we don't realize that it is the one that should be selected.
### What is the root cause of that problem?
Because we didn't handle emoji search when input emoji.
https://github.com/Expensify/App/blob/0cca90ab9aa7fd9467ef45ca35c4d0ad3c3334ae/src/components/EmojiPicker/EmojiPickerMenu/index.native.js#L84
and
https://github.com/Expensify/App/blob/0cca90ab9aa7fd9467ef45ca35c4d0ad3c3334ae/src/components/EmojiPicker/EmojiPickerMenu/index.js#L181
### What changes do you think we should make in order to solve the problem?
We need to handle like this.
```
const convertedSearchTerm  = EmojiUtils.findEmojiByCode(normalizedSearchTerm)
        ? EmojiUtils.getEmojiName(EmojiUtils.findEmojiByCode(normalizedSearchTerm))
        :normalizedSearchTerm
        
const newFilteredEmojiList = EmojiUtils.suggestEmojis(`:${convertedSearchTerm}`, preferredLocale, emojis.current.length);
```
### What alternative solutions did you explore? (Optional)


https://github.com/Expensify/App/assets/65789015/813be777-08ed-4b5e-b4e1-59742e8643a2

**Comment by yh-0218** [comment] 2023-11-23 13:29
This is a Emojis suggesting Modal.

**Comment by twisterdotcom** [comment] 2023-11-23 16:51
Man this is super niche. @burczu any of these proposals good? Going to downgrade to Weekly though.

**Comment by DylanDylann** [comment] 2023-11-23 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- Emojis - "No results found" message appears when select "Hand" from keyboard suggestion
### What is the root cause of that problem?
- In the [EmojiPickerMenu](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js), we do not support search if the emoji code is typed.
### What changes do you think we should make in order to solve the problem?
- **In other application, like slack, skype**, if we type the emoji code to the search input, it will convert to emoji name. For example, if we type the thumb-up emoji :+1:, it will display as ```:+1:```.

- We can do the same in our app, by updating:
https://github.com/Expensify/App/blob/8b5306468bc9660124bad97df6142f19354649f0/src/components/EmojiPicker/EmojiPickerMenu/index.js#L167
to:
````diff
+    const [searchTermValue, setSearchTermValue] = useState('');

const filterEmojis = _.throttle((searchTerm) => {
+        let originalSearchTerm = searchTerm;
+        const listCharacters = originalSearchTerm.split('');
+        forEach(listCharacters, (character) => {
+            if (EmojiUtils.containsOnlyEmojis(character)) {
+                const emojiName = EmojiUtils.findEmojiByCode(character)?.name;
+                if (emojiName) {
+                    originalSearchTerm = originalSearchTerm.replaceAll(character, `:${emojiName}:`);
+                }
+            }
        });
...
+     setSearchTermValue(originalSearchTerm);
...

    }, throttleTime);
````

### What alternative solutions did you explore? (Optional)

### Result

[Screencast from 24-11-2023 00:55:29.webm](https://github.com/Expensify/App/assets/141406735/f1260620-7f04-4f39-9321-819ea51eb8c9)

**Comment by burczu** [comment] 2023-12-04 11:15
@twisterdotcom I like the most the proposal from @paultsimura but I agree it's very niche and I'm not sure if we should fix this. I've checked on Slack and it works the same as in Expensify App - please see the video below:

https://github.com/Expensify/App/assets/7771498/2056ab00-5f87-42df-92cc-3975ecb20964

**Comment by DylanDylann** [comment] 2023-12-04 11:21
@burczu In slack, if we copy the emoji from native app, it will be:
[Screencast from 04-12-2023 18:20:37.webm](https://github.com/Expensify/App/assets/141406735/a6483bd0-fdb7-4e48-b8b4-679d6b1b4be5)

**Comment by burczu** [comment] 2023-12-04 11:40
Yes, but I still don't think it's worth fixing - on native devices users will use emoji pickers embedded in the screen keyboard, not our custom emoji picker; on desktop they will use keyboard to search for emoji because if the copy the emoji from somewhere else, why would they search it in the emoji picker if they can just paste it in the editor input?

**Comment by DylanDylann** [comment] 2023-12-04 11:48
@burczu Yeah. It's just my opinion. 
> if they can copy emoji from somewhere else, why would they search it in the emoji picker if they can just paste it in the editor input?

- In slack, if we paste the emoji to the search input and then remove any characters, we can search the related emojis. Just for reference

[Screencast from 04-12-2023 18:46:03.webm](https://github.com/Expensify/App/assets/141406735/c71a2bc5-c550-4fd3-883c-38214ed22811)

**Comment by twisterdotcom** [comment] 2023-12-05 17:45
Look, I think the benefit of having a great open source codebase is that we can fix anything, no matter how small. There's no time restriction on this one, but if we have a fix that can make our cross platform app work consistently, I think it's fine for us to "fix" it.

**Comment by paultsimura** [comment] 2023-12-05 18:01
If this is worth fixing, I don't see any benefit in complicating things with the way we copy-paste the emojis in the emoji search bar instead of using the direct emoji matching.
From my user experience, it did happen sometimes that I was trying to look for an emoji in the emoji picker, entered the (half-)name, and tapped the autocompletion – when the emoji is inserted into the picker search bar, I would expect an easy way to "transfer" it from the emoji picker into the composer – and in this case, the 1:1 match is the way to go IMHO.

**Comment by situchan** [comment] 2023-12-05 18:03
I remember this was closed as not bug. Finding GH

**Comment by paultsimura** [comment] 2023-12-05 18:19
> Dupe of #24399

With all due respect, this issue is different as it has nothing to do with the copy-paste behavior of the emojis within the app – it's only related to the EmojiPicker's search logic.

**Comment by burczu** [comment] 2023-12-14 08:51
@DylanDylann I like what we discussed above - is it reflected in your proposal already?

**Comment by DylanDylann** [comment] 2023-12-14 08:54
@burczu  
> I like what we discussed above

Which discussion are you mentioning?

**Comment by burczu** [comment] 2023-12-14 08:56
@DylanDylann Like, [here](https://github.com/Expensify/App/issues/31780#issuecomment-1838443393) and [here](https://github.com/Expensify/App/issues/31780#issuecomment-1838471851)

**Comment by twisterdotcom** [comment] 2023-12-14 09:37
Hmm https://github.com/Expensify/App/issues/24399 does have some interesting discussion about the complexity of the fix vs the likelihood for real users encountering this.

Things are moving fast here at Expensify HQ and we are moving towards a world where [only real world reported bugs will be fixed](https://expensify.slack.com/archives/C01GTK53T8Q/p1702496349813859), so I'm here to retract [my previous viewpoint](https://github.com/Expensify/App/issues/31780#issuecomment-1841308655) and say that I think given this is so unlikely to affect a real world user, we should close and perhaps when we come back to fixing every little thing, we'll do this then.

@burczu and @DylanDylann and everybody else, I definitely appreciate the discussion on this.

**Closed by twisterdotcom** 2023-12-14 09:37 UTC
Labels: External, Daily, Help Wanted, Bug
