### ISSUE TITLE
[$500] IOU – Scan request "Only visible to Employee" is visible to Admin when the receipt is scanning

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36159] opened 2024-02-08 16:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+jpcategory@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Login as Employee of a Collect workspace
3. Navigate to the workspace chat
4. Create 2 Scan money requests and 1 manual money request
5. Login as WS Admin and navigate to the workspace chat with the employee
6. Relogin as WS Admin and navigate to the workspace chat with the employee

## Expected Result:
Expense request is not displayed because the receipts are still in scan process

## Actual Result:
Scan requests "Only visible to Employee" is visible to Admin after relogin

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b8b7ff56-2d8c-4b1b-8b8f-a7aa5c06f169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112e9f153aa10a4af</li>
        <li>Upwork Job ID: 1755624061477240832</li>
        <li>Last Price Increase: 2024-02-08</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-08 16:06
We think that this bug might be related to #wave5 
CC @greg-schroeder

**Comment by rojiphil** [comment] 2024-02-08 18:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Scan request "Only visible to Employee" is visible to Admin when the receipt was generated by Employee and the receipt scanning is not completed yet.

### What is the root cause of that problem?

[Here](https://github.com/Expensify/App/blob/e30989663188effdd4806d2b5f7dac0ded93f648/src/libs/ReportActionsUtils.ts#L350), we filter the report actions to find out the ones that must be displayed. However, we do not filter out whisper messages which are not whispered to the current user. This is the root cause. 

### What changes do you think we should make in order to solve the problem?

We can add a helper function `isCurrentUserWhisperParticipant` to find out if a whisper action was whispered to the current user like this:

```
function isCurrentUserWhisperParticipant(reportAction: OnyxEntry<ReportAction>): boolean {
    const whisperedToAccountIDs = reportAction?.whisperedToAccountIDs ?? [];
    return whisperedToAccountIDs.length > 0 && whisperedToAccountIDs.findIndex((accountID) => accountID === currentUserAccountID) !== -1;
}
```

Now, we can filter out the whisper messages if it was not whispered to the current user [here](https://github.com/Expensify/App/blob/e30989663188effdd4806d2b5f7dac0ded93f648/src/libs/ReportActionsUtils.ts#L376) like this:

    if(isWhisperAction(reportAction) && !isCurrentUserWhisperParticipant(reportAction)) {
        return false;
    }

Additionally, we also have to make changes to the Report Preview.

### What alternative solutions did you explore? (Optional)

Alternatively, the BE can decide to not send whisper messages to the current user in FE if he is not whispered to.

**Comment by allroundexperts** [comment] 2024-02-09 00:29
Although I'm not sure, but there might be whispers which are meant for several people. Can an internal engineer please confirm if this needs to be fixed from the frontend? 🎀 👀 🎀

**Comment by Beamanator** [comment] 2024-02-09 08:55
Gooood question - I assumed whispers were always for 1 person at a time, but this seems intentional - can anyone reproduce & look at the whisperToAccountIDs in Onyx?

**Comment by rojiphil** [comment] 2024-02-09 09:41
> can anyone reproduce & look at the whisperToAccountIDs in Onyx?

`whisperToAccountIDs`is an array in Onyx as shown below. So, whispers can be meant for several people. 

But, I think if the whisper was meant for the current user, I would expect the current user's account id to be also present in `whisperedToAccountIDs`. And, if it is not present, I am not sure why we would want to display the whisper.

Also, if possible, BE can decide not to send it to FE. But, maybe it is sent because the current user is the admin.  

![Screenshot 2024-02-09 at 2 59 27 PM](https://github.com/Expensify/App/assets/3004659/71d86b14-abd4-42d8-8723-bbe759ce4140)

**Comment by Beamanator** [comment] 2024-02-13 08:28
I brought this up in slack [here](https://expensify.slack.com/archives/C02MW39LT9N/p1707468883926809) (sorry it's an internal chat) and we decided this is fine for now, so we will be closing this out - thanks for everyone who looked into this 🙏 

@lanitochka17 can you please let us know if there's a test case that fails in this flow so that we can update it to pass? 🙏

**Comment by anmurali** [comment] 2024-02-16 15:16
I am removing the Bug label since it is not a bug.

**Comment by anmurali** [comment] 2024-02-16 15:17
@lanitochka17 can you update this issue with the test case?

**Comment by mvtglobally** [comment] 2024-02-21 02:31
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-02-27 15:48
Issue not reproducible during KI retests. (Second week)

**Closed** 2024-02-27 20:09 UTC
Labels: External, Daily, Help Wanted, Overdue
