### ISSUE TITLE
[Hold on #41619] Onboarding - Onboarding tasks assigned to current user disappears after a few sec

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#44834] opened 2024-07-04 14:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
Issue found when validating #43927
**Version Number:** 9.0.4-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Sign in as a new user
3. Select manage your business on the onboarding flow
4. Finish the onboarding flow

## Expected Result:
The tasks get assigned to the current user

## Actual Result:
The tasks become shown as being assigned to the current user at first then disappear

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/b4dc26a2-e822-4735-9959-648f81fc6ac2

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kavimuru** [comment] 2024-07-04 14:07
@garrettmknight FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-07-04 14:07
We think this bug might be related to #vip-vsb

**Comment by garrettmknight** [comment] 2024-07-04 16:18
Reproduced - it looks like the tasks are actually unassigned too. I wouldn't hold the deploy based on this, but we should definitely fix.

**Comment by garrettmknight** [comment] 2024-07-04 16:25
Checking in on Guided Setup thread [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720110166849139?thread_ts=1719848025.072179&cid=C036QM0SLJK).

**Comment by garrettmknight** [comment] 2024-07-04 17:06
Actually, this looks planned in that case. Closing.

**Closed by garrettmknight** 2024-07-04 17:06 UTC
Labels: Engineering, Daily, Bug
