### ISSUE TITLE
[$1000] Clicking outside of the comment text won’t unselect the highlighted text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14402] opened 2023-01-18 22:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open web
2. Go to any chat
3. Highlight range of text
4. Click on empty space on the left

## Expected Result:
The text selected range should be reset / unselected

## Actual Result:
The text selection range stays highlighted

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.2.56-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213311766-6a5e0f3a-7cb3-4698-a7c7-262615ead9b3.mp4

https://user-images.githubusercontent.com/43996225/213311780-24f14878-74ea-4174-bdcd-41d9768bd67e.mov

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674068409564519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e5387a24edfdca63</li>
        <li>Upwork Job ID: 1616243842386743296</li>
        <li>Last Price Increase: 2023-01-20</li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-01-20 05:37
### Proposal

```diff --git a/src/App.js b/src/App.js
index 581012838..b13c27a4c 100644
--- a/src/App.js
+++ b/src/App.js
@@ -16,6 +16,7 @@ import SafeArea from './components/SafeArea';
 import * as Environment from './libs/Environment/Environment';
 import {WindowDimensionsProvider} from './components/withWindowDimensions';
 import {KeyboardStateProvider} from './components/withKeyboardState';
+import DomUtils from "./libs/DomUtils";

 // For easier debugging and development, when we are in web we expose Onyx to the window, so you can more easily set data into Onyx
 if (window && Environment.isDevelopment()) {
@@ -31,8 +32,17 @@ LogBox.ignoreLogs([

 const fill = {flex: 1};

+/**
+ * We want to reset highlighted text range when user clicks outside of the text
+ * More details here: https://github.com/Expensify/App/issues/14402
+ * @param {Event} event
+ */
+const handleOnMouseDown = (event)=>{
+    DomUtils.removeSelectionRange(event)
+}
+
 const App = () => (
-    <GestureHandlerRootView style={fill}>
+    <GestureHandlerRootView onMouseDown={handleOnMouseDown} style={fill}>
         <ComposeProviders
             components={[
                 OnyxProvider,
```


```diff --git a/src/libs/DomUtils/index.js b/src/libs/DomUtils/index.js
index 4e58ea3a0..e5ba103cb 100644
--- a/src/libs/DomUtils/index.js
+++ b/src/libs/DomUtils/index.js
@@ -2,6 +2,12 @@ function blurActiveElement() {
     document.activeElement.blur();
 }

+function removeSelectionRange(e) {
+    if(e.buttons !== 0) return;
+    document.getSelection().removeAllRanges()
+}
+
 export default {
     blurActiveElement,
+    removeSelectionRange
 };
```

```diff --git a/src/libs/DomUtils/index.native.js b/src/libs/DomUtils/index.native.js
index 0e796bc40..9fdab5f52 100644
--- a/src/libs/DomUtils/index.native.js
+++ b/src/libs/DomUtils/index.native.js
@@ -1,5 +1,7 @@
 function blurActiveElement() {}
+function removeSelectionRange() {}

 export default {
     blurActiveElement,
+    removeSelectionRange
 };
```

### Result:

https://user-images.githubusercontent.com/75031127/213624487-8ad143bb-bb0e-4038-96d7-c8bfb70b107c.mov


By utilizing the `onMouseDown` event, we can implement a function to remove the selected range whenever the user initiates a click action on highlighted text, effectively deselecting it.

there are multiple ways that we can implement my solution in
1. using `onMouseDown` on GestureHandlerRootView (strongly recommended)
2. using event listener `document.addEventListener("mousedown")`
3. using inline event `document.onmousedown = ()=>{}`

We can use all of these with the same output but i strongly recommend using `onMouseDown` on GestureHandlerRootView.

It is strongly recommended to utilize the `onMouseDown` event within the GestureHandlerRootView, as it provides improved functionality and efficient output.

**Comment by richard-here** [comment] 2023-01-20 14:54
Content.
- Root Cause
- Initial Solutions with Drawbacks
- Proposal (Final Solution)

### Root Cause
In the case explained in the issue above, the selected portion of text is still highlighted (i.e. selected) although elements outside the text are clicked. There are two screen recordings:
1. the first case shows clicking outside the message box (e.g. the chatroom)
2. the second case shows clicking inside the message box beside the chat message inside the message box.

In the first case, the exact reason for the text still being highlighted is unknown. However, I suspect it has something to do with this explanation: https://developer.mozilla.org/en-US/docs/Web/API/Selection#behavior_of_selection_api_in_terms_of_editing_host_focus_changes. I'm assuming it is similar to the behavior of how text is still highlighted when we click on images or buttons in regular HTML. What this means is that there might be a need of altering possibly a lot of components in the already created components.

In the second case, the exact reason for the text still being highlighted is exactly because of the same exact behavior of how text is still highlighted when we click on images or buttons in regular HTML. This is because the message box itself is a Pressable component.

### Initial Solutions with Drawbacks
#### Solution 1
Create a global `mousedown` event with a handler of removing selection using `window.getSelection().removeAllRanges()`. This doesn't work as well as expected because it causes not able to drag and drop the highlighted text. Furthermore, as it removes selection range on `mousedown`, typing on the `textarea` is also not possible because the cursor is immediately removed after `mousedown` on the `textarea`.

#### Solution 2
Let the sent text consume the press event, then make the Pressable message box to also have a handler in `onPressOut`  to `window.getSelection().removeAllRanges()`. This works well, but the function of `removeAllRanges` must be used on other components that also make the text deselected, which means having to keep track which components need to have this handler. This is tedious and error-prone.

### Proposal
In light of the previous solutions with drawbacks, I am proposing to create a wrapper for the text component. The wrapper will contain a handler for outside clicks deselecting text. This way, the selectable text component is standalone and the functionality of removing text selection is connected to the selectable text itself.

**Comment by cead22** [comment] 2023-01-20 21:10
@getusha @richard-here thank you both for the proposals, and @richard-here thanks for the explanation. Correct me if I'm wrong but it sounds like the text should be deselected whenever we click outside of it, and so long as we're not clicking a Pressable component, is that right, or is it more nuanced than that?

In the example below, that seems to work well when I click on someone's avatar, but not so much when I click the X to close the dialog -- which is inside a Pressable component, or the semi-transparent overlay, which is also inside a Pressable component.
![](http://g.recordit.co/EAPAsRIPKm.gif)

That said, it looks like GH isn't very consistent with this either
![](http://g.recordit.co/EJXoko4C5O.gif)

I think we probably want to define what we want our behavior to be before writing up the solution -- though one valid approach is to "deselect when you click/tap a non-Pressable component outside of the selected element"

**Comment by getusha** [comment] 2023-01-20 21:35
@cead22 interesting! but you can check that behavior doesn't exist on safari, so it shouldn't concern us?

https://user-images.githubusercontent.com/75031127/213809110-df795d01-d0ee-4904-983b-608f31d8aaba.mov

**Comment by cead22** [comment] 2023-01-20 21:37
It doesn't look consistent in Safari either, check this out ![](http://g.recordit.co/xUiyNkEvbO.gif)

**Comment by getusha** [comment] 2023-01-20 21:43
@cead22 i see, it's pretty inconsistent, FWIW keeping it focused on Pressable press?

**Comment by s77rt** [comment] 2023-01-20 23:43
### Proposal
```diff
diff --git a/src/styles/styles.js b/src/styles/styles.js
index 71fed02015..cf29954d03 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -1238,10 +1238,10 @@ const styles = {
         overflow: 'hidden',
 
         // Starting version 6.3.2 @react-navigation/drawer adds "user-select: none;" to its container.
-        // We add user-select-auto to the inner component to prevent incorrect triple-click text selection.
-        // For further explanation see - https://github.com/Expensify/App/pull/12730/files#r1022883823
-        userSelect: 'auto',
-        WebkitUserSelect: 'auto',
+        // We add "user-select: text;" to the inner component to prevent incorrect triple-click text selection.
+        // For further explanation see - https://github.com/Expensify/App/pull/12730/files#r1022883823 and https://github.com/Expensify/App/issues/14402
+        userSelect: 'text',
+        WebkitUserSelect: 'text',
     },
 
     appContentHeader: {
```

### RCA
Browsers deselect the current text only if the mouse down target is an element that can be selected (`user-select` is not `none`).

If you look into the source code you will see one of the main wrapper is using `user-select: none` this style is causing the issue but it's not from our App. It's from `react-navigation` and I think it's actually from `react-gesture-handler` which `react-navigation` uses.

The thing is apparently we are aware of this as I have seen some comments confirming this, and to cover that issue we used `user-select: auto` on that main wrapper children, thus it's applied in our `appContent` style rule.

The problem is that using `user-select: auto` is not really doing it's job as you'd expect based on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select):

> Note: user-select is not an inherited property, though the initial auto value makes it behave like it is inherited most of the time. WebKit/Chromium-based browsers do implement the property as inherited, which violates the behavior described in the spec, and this will bring some issues. Until now, Chromium has chosen to [fix the issues](https://chromium.googlesource.com/chromium/src/+/b01af0b296ecb855aac95c4ed335d188e6eac2de) to make the final behavior meet the specifications.

I think the best we can do and the easiest fix is to use `user-select: text` instead of `user-select: auto`.

### Results

https://user-images.githubusercontent.com/16493223/213824184-e25d04c1-2bd0-4bfa-9326-d75cc2538e24.mp4

**Comment by richard-here** [comment] 2023-01-21 03:54
> @getusha @richard-here thank you both for the proposals, and @richard-here thanks for the explanation. Correct me if I'm wrong but it sounds like the text should be deselected whenever we click outside of it, and so long as we're not clicking a Pressable component, is that right, or is it more nuanced than that?
> 
> In the example below, that seems to work well when I click on someone's avatar, but not so much when I click the X to close the dialog -- which is inside a Pressable component, or the semi-transparent overlay, which is also inside a Pressable component. ![](https://camo.githubusercontent.com/ff5afff4cb8a875e757e3b81fcd84b6fde5033d4587f5a166852ff1409b6b1cd/687474703a2f2f672e7265636f726469742e636f2f45415041735249504b6d2e676966) [ ](https://camo.githubusercontent.com/ff5afff4cb8a875e757e3b81fcd84b6fde5033d4587f5a166852ff1409b6b1cd/687474703a2f2f672e7265636f726469742e636f2f45415041735249504b6d2e676966) ![687474703a2f2f672e7265636f726469742e636f2f45415041735249504b6d2e676966](https://camo.githubusercontent.com/ff5afff4cb8a875e757e3b81fcd84b6fde5033d4587f5a166852ff1409b6b1cd/687474703a2f2f672e7265636f726469742e636f2f45415041735249504b6d2e676966) [ ](https://camo.githubusercontent.com/ff5afff4cb8a875e757e3b81fcd84b6fde5033d4587f5a166852ff1409b6b1cd/687474703a2f2f672e7265636f726469742e636f2f45415041735249504b6d2e676966)
> 
> That said, it looks like GH isn't very consistent with this either ![](https://camo.githubusercontent.com/1eb976e6d7de76a26e49e52f701f1bc12e19664fd9773f1cecdb713dcdc8bbd6/687474703a2f2f672e7265636f726469742e636f2f454a586f6b6f3443354f2e676966) [ ](https://camo.githubusercontent.com/1eb976e6d7de76a26e49e52f701f1bc12e19664fd9773f1cecdb713dcdc8bbd6/687474703a2f2f672e7265636f726469742e636f2f454a586f6b6f3443354f2e676966) ![687474703a2f2f672e7265636f726469742e636f2f454a586f6b6f3443354f2e676966](https://camo.githubusercontent.com/1eb976e6d7de76a26e49e52f701f1bc12e19664fd9773f1cecdb713dcdc8bbd6/687474703a2f2f672e7265636f726469742e636f2f454a586f6b6f3443354f2e676966) [ ](https://camo.githubusercontent.com/1eb976e6d7de76a26e49e52f701f1bc12e19664fd9773f1cecdb713dcdc8bbd6/687474703a2f2f672e7265636f726469742e636f2f454a586f6b6f3443354f2e676966)
> 
> I think we probably want to define what we want our behavior to be before writing up the solution -- though one valid approach is to "deselect when you click/tap a non-Pressable component outside of the selected element"
> 
> I'm going raise this in #expensify-open-source

### Additional Explanation on Root Case

I have been doing further reading because it is interesting and I want to shed some light regarding the root cause. Here is what I have found.
- This behavior is related to the Selection API. You can read what MDN specifies about it [here](https://developer.mozilla.org/en-US/docs/Web/API/Selection) and what W3 specifies about it [here](https://w3c.github.io/selection-api/#selection-interface).
- In the MDN API explanation, a `Selection` is defined as the following.
  > A Selection object represents the range of text selected by the user or the current position of the caret.
  
  Besides that, it is important to note that W3 defines that there must be only one unique `Selection` object in a document. This is mentioned in MDN's Selection API as well, quoted below.
  > As the [Selection API specification notes](https://www.w3.org/TR/selection-api/#h_note_15), the Selection API was initially created by Netscape and allowed multiple ranges (for instance, to allow the user to select a column from a table). However, browsers other than Gecko did not implement multiple ranges, and the specification also requires the selection to always have a single range.
  
  As can be seen, it seems that initially, there can be multiple ranges in a `Selection`, but as of now, there can only be a single range or caret for the `Selection` object. A more detailed explanation is available in W3 [here](https://w3c.github.io/selection-api/#definition). Basically, it defines what a `Selection` is supposed to be. To paraphrase it, it's basically a singleton unique object that can be empty (when nothing is selected or no caret) or that it can be a single range.
  
  Now all this explains the inconsistency in GH that you mentioned. It is actually **not inconsistent**. It is working as expected. When you are clicking the hyperlink or any clickable components, the selection **does not disappear or the range is still the same**. However, when you clicked a component on GH that immediately focuses on a text input field, the `Selection`'s range is now actually the caret in the input field, and as there can only be one range or caret for the `Selection` object, the previous range is naturally no longer selected. Instead, the `Selection` object (you can get this by using `window.getSelection()`) will now be of type `Caret`, which means that there is a `Selection` object, but it is collapsed, i.e. no range is selected, but caret is placed on some text (read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Selection/type)). This explains the Github behavior you sent in the video. Let's move on to the next behavior.
  
- After clicking on someone's avatar, then closing the dialog by clicking on the X button, the `Selection` range is no longer the text selected before closing the dialog. However, when opening the dialog (i.e. clicking on someone's avatar), the selection range stays the same. This is also **expected and consistent with the behavior I mentioned**. This is because the `Selection` becomes of type `Caret` and the `anchorNode` is now the text input field in the app to send messages. I reckon this has something to do with the app focusing on the text field immediately (for UX purposes probably) when the page opens. Let me send a video that shows this.
  https://user-images.githubusercontent.com/44660981/213841571-f5488a43-a265-44b2-bc3e-d58c84367e24.mp4
  
- After investigating more from W3, I have finally been able to find an explanation in regards to why `Selection` is not collapsed into type `Caret` when clicking on clickable components (in regular HTML or in the app). It is because those clickable components are not selectable, and according to W3 specs, once a `Selection` is not empty, the user agent must not set the `Selection` as empty anymore. That is why the selected range stays the same when clicking on unselectable components. 
  > The user agent must not make a [selection](https://w3c.github.io/selection-api/#dfn-selection) [empty](https://w3c.github.io/selection-api/#dfn-empty) if it was not already [empty](https://w3c.github.io/selection-api/#dfn-empty) in response to any user actions (e.g. clicking on a non-editable region).

This explains the root cause of the behavior we are seeing.

### Better Proposal
As mentioned here: https://github.com/Expensify/App/issues/14402#issuecomment-1399014043, altering the window's behavior on click is hack-ish. I think the best way to make it not hack-ish (i.e. altering the default browser's behavior when clicking), we should instead make all text components selectable in the whole app. However, this means that `Text` in the React Native component without the `selectable={true}` property will still be able to be selected even without the `selectable={true}` property. To make a component selectable, we can use the CSS property `user-select` and set its value to `text`.  Unfortunately, there is a parent element with `user-select: none` and this is inherited by the children using `user-select: auto`. This inheritance mechanism of children components using `user-select: auto` is explained in MDN as well.
> The used value of auto is determined as follows:
On the ::before and ::after pseudo elements, the used value is none
If the element is an editable element, the used value is contain
Otherwise, if the used value of user-select on the parent of this element is all, the used value is all
Otherwise, if the used value of user-select on the parent of this element is none, the used value is none
Otherwise, the used value is text

What we can do is to make the value of the parent's `user-select` to text. This way, the children will inherit the used value of `text`, making the text components selectable. With this, clicking on anywhere should collapse the existing range and make the `Selection` type of `Caret` to another text node.

**Comment by getusha** [comment] 2023-01-21 22:00
@rushatgabhane the root cause is very complicated and wired and i tried to understand it fully and i present it as follows 😅 

There was an issue https://github.com/Expensify/App/issues/7462 `Long press on image doesn't open the context menu` reported by you. 
* in order to fix that this PR was raised https://github.com/Expensify/App/pull/8018, in that PR `LongPressGestureHandler` was added for the web too even though it's not needed since we have `contextmenu` event listener to open the context menu.  **(introduced this issue for the first time)**
* * then this PR introduced a great regression here https://github.com/Expensify/App/issues/8311 , 
* * * and this PR also introduced https://github.com/Expensify/App/issues/14301#issuecomment-1399233891 https://github.com/Expensify/App/issues/14301#issuecomment-1396453523
* I think we should Hold [that](https://github.com/Expensify/App/issues/14301) until this gets fixed (seems related to me)

I just wanted to comment this Just help prevent future issues related to this, because this looks related

# Proposal

```diff --git a/src/components/PressableWithSecondaryInteraction/index.js b/src/components/PressableWithSecondary
Interaction/index.js
index 7b971e7268..3881125e95 100644
--- a/src/components/PressableWithSecondaryInteraction/index.js
+++ b/src/components/PressableWithSecondaryInteraction/index.js
@@ -43,7 +43,7 @@ class PressableWithSecondaryInteraction extends Component {
         // On Web, Text does not support LongPress events thus manage inline mode with styling instead of using Text.
         return (
             <Pressable
-                style={this.props.inline && styles.dInline}
+                style={[this.props.inline && styles.dInline, styles.userSelectText]}
                 onPressIn={this.props.onPressIn}
                 onLongPress={(e) => {
                     if (DeviceCapabilities.hasHoverSupport()) {
```

### Result

https://user-images.githubusercontent.com/75031127/213888490-92981194-90ed-41c0-8092-a72fb100be11.mov

**Comment by cead22** [comment] 2023-01-24 18:23
Still discussing here https://expensify.slack.com/archives/C01GTK53T8Q/p1674580475813759?thread_ts=1674249705.438009&cid=C01GTK53T8Q, but I'm proposing we close this issue

**Comment by cead22** [comment] 2023-01-26 17:54
Closing per slack discussion

**Closed by cead22** 2023-01-26 17:54 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
