### ISSUE TITLE
[HOLD for payment 2024-07-10] [PAY 07-04] [$250]  iOS - Expense - App flickers when opening submit flow and transitioning between expense report

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#44419] opened 2024-06-26 00:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** n/a
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app.
2. Go to any chat.
3. Tap + > Submit expense > Manual
4. Submit a manual expense.
5. Tap on the expense preview.

## Expected Result:
App will not flicker when opening submit expense flow and transitioning between expense report.

## Actual Result:
 App flickers when opening submit expense flow and transitioning between expense report.
App also flickers slightly when opening settings page such as Security and Workspaces (second video).

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/8bee4145-462e-4bde-a0d8-7d88c3136954

https://github.com/Expensify/App/assets/38435837/e977e61f-2b56-401e-bf14-0d7505254273

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010bb448fc4956fbb5</li>
        <li>Upwork Job ID: 1806056166413374093</li>
        <li>Last Price Increase: 2024-06-26</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 102902152</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by m-natarajan** [comment] 2024-06-26 00:43
@marcaaron FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment] 2024-06-26 00:43
We think that this bug might be related to #wave-collect - Release 1

**Comment by marcaaron** [comment] 2024-06-26 22:07
Still very flashy stuff happening on staging. Looks bad :/

**Comment by mountiny** [comment] 2024-06-27 09:34
@WojtekBoman Is looking into this one I believe https://expensify.slack.com/archives/C049HHMV9SM/p1719476944356269?thread_ts=1719475873.244049&cid=C049HHMV9SM

**Comment by Christinadobrzyn** [comment] 2024-06-27 14:27
Hi there - this looks similar - https://github.com/Expensify/App/issues/44498

Can we tell if they have the same root cause?

**Comment by mountiny** [comment] 2024-06-27 15:36
Confirmed this is fixed by this PR https://github.com/Expensify/App/pull/44544

**Comment by mountiny** [comment] 2024-06-27 15:36
Assigning @ZhenjaHorbach as they are handling the checklist

**Comment by mountiny** [comment] 2024-06-27 17:02
This is now fixed in staging 🎉  No more flickering
https://github.com/Expensify/App/assets/36083550/e62c01b4-1c9b-4379-a6cc-fdcddb686c2d


$250 to @ZhenjaHorbach once the time comes

**Comment by bfitzexpensify** [comment] 2024-07-10 18:58
Regression steps proposed. Payment complete. Closing this one out.

**Closed by bfitzexpensify** 2024-07-10 18:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
