### ISSUE TITLE
[HOLD for payment 2023-07-20] [$1000] IOU - Amount shows different in the LHN for VND currency 

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19792] opened 2023-05-30 02:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Set the currency to VND
2. Request money from someone
3. Review the chat LHN
4. The amount owed and the amount in the “settled up message” message are different

## Expected Result: 
The amount should be correct in the LHN
## Actual Result: 
The amount is showing incorrect in the LHN
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop
 
**Version Number:** 1.3.20-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/2c121d2c-495e-4675-aaa1-989358be7ac8

https://github.com/Expensify/App/assets/43996225/b37ffabb-8b11-44fc-918c-12153d33a050

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685114883184729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e171bfeae38ffb7</li>
        <li>Upwork Job ID: 1663714770365747200</li>
        <li>Last Price Increase: 2023-06-24</li>
    </ul>
</details>

**Comment by alitoshmatov** [comment] 2023-05-30 06:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
IOU - Amount shows different in the LHN for VND currency 
### What is the root cause of that problem?
Here we are assuming that every currency has currency unit of `100` and hard coding it
https://github.com/Expensify/App/blob/c34f871a0ec9982ed3d4ca8765535ddea2ba10a8/src/libs/ReportUtils.js#L1231
Which is wrong for several currencies, for example: `VND, VUV, XAF, XOF...`

And when we are converting amount to the smallest unit we are using this 
https://github.com/Expensify/App/blob/62761e5c1e18c47841eaab390f9b87511a98945f/src/libs/CurrencyUtils.js#L87-L91

https://github.com/Expensify/App/blob/62761e5c1e18c47841eaab390f9b87511a98945f/src/libs/CurrencyUtils.js#L41-L43

### What changes do you think we should make in order to solve the problem?
We should use the same approach in both places. We should use `getCurrencyUnit` function to get currency unit and the divide amount rather than dividing it to 100

### What alternative solutions did you explore? (Optional)

**Comment by alitoshmatov** [comment] 2023-05-30 06:53
This issue is reproducable on this currencies
<img width="1440" alt="Screenshot 2023-05-30 at 11 52 53 AM" src="https://github.com/Expensify/App/assets/59907218/6cce04b8-732e-4b30-994e-19cafc6d55e5">

**Comment by maddylewis** [comment] 2023-06-01 15:32
hiya - @thesahindia - what do you think about this proposal? https://github.com/Expensify/App/issues/19792#issuecomment-1567863538

**Comment by namhihi237** [comment] 2023-06-02 05:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The amount should be correct in the LHN
### What is the root cause of that problem?
There are 2 things that make this happen:
The first: The formula to calculate the amount here is not correct, we should calculate it in `currencyUnit`.
https://github.com/Expensify/App/blob/37644c56d22e15928e94de859a529b9c7e9688e1/src/libs/ReportUtils.js#L1255
The second:
After requestMoney send => data report from LHN will get from onyx first and after response return it will be applied `successData`.  But now the data from BE return incorrect.
### What changes do you think we should make in order to solve the problem?
That means here we have 2 issues that need to be fixed:
1. Use get currentUtil to calculate the amount:
```
const currencyUnit = CurrencyUtils.getCurrencyUnit(currency);
const amount = NumberFormatUtils.format(preferredLocale, total / currencyUnit, { style: 'currency', currency });
```
2. Fix the logic calculation amount from BE same as above.

Result:
I will offline first see the data correct and after online device => apply data from BE => incorrect

https://github.com/Expensify/App/assets/39086067/9dad0151-4dd6-4efd-8d2d-8fa0f52f27f1


### What alternative solutions did you explore? (Optional)
N/A

**Comment by alitoshmatov** [comment] 2023-06-02 06:31
@thesahindia Looks like as @namhihi237 pointed out, backend also has this issue here.
But if you switch to offline mode it will work as expected
https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/libs/ReportUtils.js#L1255
Replacing this line with 
```javascript
const amount = NumberFormatUtils.format(preferredLocale, total / CurrencyUtils.getCurrencyUnit(currency), {style: 'currency', currency});
``` 
is solving this issue.

Also following code might have the same issue since dividing by 100 won't suit all currencies
https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/libs/actions/IOU.js#L809-L811

**Comment by alitoshmatov** [comment] 2023-06-02 13:09
@thesahindia It should be solved in both, frontend and backend. Also we have one more similar issue here in frontend

https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/libs/actions/IOU.js#L809-L811

**Comment by tylerkaraszewski** [comment] 2023-06-09 19:21
We'll need an external contributor for the App change.

I will work on the backend change.

**Comment by maddylewis** [comment] 2023-06-13 18:25
@thesahindia - do any of the existing proposals on this issue work? if not, let me know and i will reach out to callstack/sfw to see if they can assist.

**Comment by maddylewis** [comment] 2023-06-14 00:21
hiya @MitchExpensify - i am OOO until June 20. 

i've bumped @thesahindia for an update on where we are with proposals for this one but haven't heard back quite yet. if we don't hear from them by tomorrow, i would suggest creating a thread in exp-open-source and seeing where that lands us. 

i will snag this one back from you once i return - thanks!

**Comment by MitchExpensify** [comment] 2023-06-14 20:54
Where are those backend changes being worked in @thesahindia ?

**Comment by MitchExpensify** [comment] 2023-06-19 22:02
friendly bump @tylerkaraszewski as it seems like you are covering the necessary backend changes 👍

**Comment by maddylewis** [comment] 2023-06-20 15:25
thanks @MitchExpensify! i can snag this one back from ya :)

**Comment by tylerkaraszewski** [comment] 2023-06-23 16:48
Sorry, I let this fall through the cracks I will look at this now.

**Comment by tylerkaraszewski** [comment] 2023-06-23 18:03
> Set the currency to VND

What do I actually need to do to do this? I need to set up a payment method and change the currency? How do I do that in dev?

**Comment by tylerkaraszewski** [comment] 2023-06-23 19:07
Is this the correct response I need to fix? In the onyxData from the response to requestMoney? It looks like this is where this appears.

<img width="1624" alt="Screenshot 2023-06-23 at 12 06 08" src="https://github.com/Expensify/App/assets/705000/fccd6176-87c5-4500-a7da-9f3864140831">

**Comment by tylerkaraszewski** [comment] 2023-06-23 19:33
Ok, I think this line is the issue (yes, I realize this is internal): https://github.com/Expensify/Web-Expensify/blob/31b3e02ae36c81e44d2237b31267dbf7543ea72b/lib/Report/Action/IOU.php#L45

**Comment by tylerkaraszewski** [comment] 2023-06-23 19:41
This link ha a list of currencies and their number of decimals used:
https://en.wikipedia.org/wiki/ISO_4217

**Comment by tylerkaraszewski** [comment] 2023-06-23 21:13
Backend PR has been created.

**Comment by maddylewis** [comment] 2023-06-26 13:44
@thesahindia - the backend PR was created. let me know if you have an update on your side - thanks!

**Comment by tylerkaraszewski** [comment] 2023-06-28 19:52
Backend PR has been deployed to staging, it should be possible to work on the front end change.

**Comment by tylerkaraszewski** [comment] 2023-06-30 16:47
@maddylewis - I am leaving today on sabbatical. Can you please remove and re-apply the `Engineering` label to select a new engineer to finish this issue? Thanks!

**Comment by maddylewis** [comment] 2023-06-30 19:29
hiya @MariaHCD - added you to this issue based off of Tyler's comment here - https://github.com/Expensify/App/issues/19792#issuecomment-1614914948

**Comment by MariaHCD** [comment] 2023-07-03 07:19
Okay, looks like the next step is to get the frontend fix for this. @thesahindia, what are your thoughts on the existing proposals?

**Comment by alitoshmatov** [comment] 2023-07-04 06:17
@thesahindia did you also consider my [proposal](https://github.com/Expensify/App/issues/19792#issuecomment-1567863538) since I was the first one to point out correct root cause and solution, one thing my proposal lacking is pointing out the need of backend changes but I think it was going to be discovered easily. But still, I am not arguing on your decision, just want to make everything clear and get some feedback.

What do you think about this problem, where I mentioned early in our discussion
> Also following code might have the same issue since dividing by 100 won't suit all currencies
https://github.com/Expensify/App/blob/d8b1d84c2f4a583ac2a863899c11bb5baff04ade/src/libs/actions/IOU.js#L809-L811

**Comment by maddylewis** [comment] 2023-07-05 13:10
assigned @namhihi237 based off of this comment - https://github.com/Expensify/App/issues/19792#issuecomment-1619237176

**Comment by MariaHCD** [comment] 2023-07-13 07:48
The PR was deployed to production two days ago: https://github.com/Expensify/App/pull/22281#issuecomment-1629893226

Not sure why this one didn't get the automatic posts.

**Comment by MariaHCD** [comment] 2023-07-13 07:50
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@thesahindia] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@thesahindia] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@thesahindia] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@thesahindia] Determine if we should create a regression test for this bug.
- [ ] [@thesahindia] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@maddylewis] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by maddylewis** [comment] 2023-07-21 17:04
#### payments:
- [ ] [namhihi237](https://github.com/namhihi237) - $250 (reporting bonus)
- [ ] [namhihi237](https://github.com/namhihi237) - $1000 (contributor)
- [ ] @thesahindia - $1000 (paid via NewDot)

**Comment by maddylewis** [comment] 2023-07-21 17:09
@namhihi237 - will you link me to your Upwork profile? thank ya!

**Comment by maddylewis** [comment] 2023-07-21 17:20
Paid @namhihi237 the $1500 contributor fee + $250 reporting bonus :)

**Closed** 2023-07-21 17:21 UTC
Labels: Reviewing, Engineering, Daily, Internal, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 21:38
$1,500 payment approved for @thesahindia based on BZ summary.
