### ISSUE TITLE
 Distance - Distance request creation is looped

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31191] opened 2023-11-10 17:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30920
## Action Performed:
1. Navigate to staging.new.expensify.com
2. Go to + > Request money > Distance
3. Enter address for Start and Finish point
4. Click Next

## Expected Result:
User is able to proceed to workspace selection page

## Actual Result:
User is redirected back to the address page. The process is looped

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/186becef-38cb-491a-af10-8a0aa41801ea

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @marcochavezf</details>

**Comment by paultsimura** [comment] 2023-11-10 18:24
This looks like a regression from https://github.com/Expensify/App/pull/28866

https://github.com/Expensify/App/blob/31ec9334a3cc15e4b469856e794f04b57eb7e93a/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L64-L66

An empty transaction is passed into this component now from `withOnyx`. Debug data:

<img width="678" alt="image" src="https://github.com/Expensify/App/assets/12595293/cd6617f9-e7ff-40c2-b164-a4249e32c8de">

**Comment by garrettmknight** [comment] 2023-11-10 18:44
Reproduced

**Comment by marcochavezf** [comment] 2023-11-10 19:07
Also reproduced the error locally, checking

**Comment by marcochavezf** [comment] 2023-11-10 19:11
> This looks like a regression from #28866
> 
> https://github.com/Expensify/App/blob/31ec9334a3cc15e4b469856e794f04b57eb7e93a/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L64-L66
> 
> An empty transaction is passed into this component now from `withOnyx`. Debug data:
> 
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/12595293/282148628-cd6617f9-e7ff-40c2-b164-a4249e32c8de.png">

Seems the latest `withOnyx` changes in the linked PR are returning the `transaction` object as empty

**Comment by marcochavezf** [comment] 2023-11-10 19:59
Phew, there are quite changes in Onyx and it's a bit hard to track where exactly this was introduced. I'm leaning towards reverting the offending PR then we can figure out what introduced this regression.

**Comment by puneetlath** [comment] 2023-11-10 19:59
Maybe we can start a slack thread and bring Tim into the discussion to see if he can help.

**Comment by marcochavezf** [comment] 2023-11-10 20:17
Sounds good, posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1699647454971439?thread_ts=1699638071.509049&cid=C01GTK53T8Q)

**Comment by situchan** [comment] 2023-11-10 20:34
The root cause was already explained [here](https://github.com/Expensify/App/pull/28866#discussion_r1388514971).
So this is 2nd unexpected behavior. We really need to fix this in Onyx repo.
cc: @tgolen

**Comment by marcochavezf** [comment] 2023-11-10 23:16
Also we're sending the all the reports instead of a report in [NewDistanceRequestPage](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/pages/iou/NewDistanceRequestPage.js):

<img width="561" alt="Screenshot 2023-11-10 at 5 12 07 p m" src="https://github.com/Expensify/App/assets/6829422/57cc2a59-0166-4d74-ba65-ce9a006233c2">

**Comment by situchan** [comment] 2023-11-10 23:23
> Also we're sending the all the reports instead of a report in [NewDistanceRequestPage](https://github.com/Expensify/App/blob/e87d35d8af177df33c4fdfbf221ead732efec310/src/pages/iou/NewDistanceRequestPage.js):
> 
> <img alt="Screenshot 2023-11-10 at 5 12 07 p m" width="561" src="https://user-images.githubusercontent.com/6829422/282197418-57cc2a59-0166-4d74-ba65-ce9a006233c2.png">

That seems like pre-existed bug.
That will happen when `lodashGet(route, 'params.reportID')` is empty string

**Comment by dylanexpensify** [comment] 2023-11-13 15:08
bump @garrettmknight @marcochavezf  this is def a bug/deploy blocker!

**Comment by situchan** [comment] 2023-11-13 15:09
This is fixed on staging. We can close the issue

**Comment by marcochavezf** [comment] 2023-11-13 18:49
PR was CP to staging and confirmed the distance request issue is fixed

https://github.com/Expensify/App/assets/6829422/beaea5e5-1b98-4759-854b-a5f247be0bfe

**Closed by marcochavezf** 2023-11-13 18:49 UTC
Labels: Reviewing, DeployBlockerCash, Engineering, Weekly, Bug
