### ISSUE TITLE
[$500] Web - Room - Secondary contact with @expensify.anon domain is added when signing in via public room

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27524] opened 2023-09-15 13:05 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Navigate to a public room URL in incognito mode.
3. Click Sign in on the banner at the bottom.
4. Go to Settings > Profile > Contact methods.

## Expected Result:
No secondary contact will be added.

## Actual Result:
There is a secondary contact method with domain @expensify.anon added.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.70-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/70b70467-a3e6-47ec-b4bb-10a72ae8bb3b

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0191e4bcc050c735be</li>
        <li>Upwork Job ID: 1702704188228055040</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-09-19 23:21
@0xmiroslav kindly verify it is backend related bug.

**Comment by ayazalavi** [comment] 2023-09-22 18:17
@0xmiroslav can you guide me how would you like to deal with this issue e.g. filter by specific domain name like expensify.anon is okay solution in front of you? Please let me know your thoughts on this.

**Comment by ayazalavi** [comment] 2023-09-22 18:35
@0xmiroslav Thanks for clarification.  What do you meant by `signin through anonymous user,`?

**Comment by ayazalavi** [comment] 2023-09-22 18:39
Bu t i signed in through registered user.

**Comment by ayazalavi** [comment] 2023-09-23 09:27
@0xmiroslav are you guys handling it in the backend otherwise I can put my proposal here.

**Comment by ayazalavi** [comment] 2023-09-25 06:18
> > @0xmiroslav Thanks for clarification. What do you meant by `signin through anonymous user,`?
> 
> <img alt="Screenshot 2023-09-22 at 8 37 15 PM" width="1504" src="https://user-images.githubusercontent.com/97473779/270028804-eb0fc100-5aa1-467c-93f7-3be7766dc81b.png">

so does this mean this email did not existed earlier?

**Comment by ayazalavi** [comment] 2023-09-25 06:22
> @ayazalavi please check how anonymous user flow works in the app

please share documentation link detailing anonymous user flow.

**Comment by ayazalavi** [comment] 2023-09-25 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
As an anonymous user when person login then extra information is getting added contact section of the user's profile

### What is the root cause of that problem?
The root cause of the problem occurs when signing in as an anonymous user, where an authToken and pusherID are being passed to the SigninUser API call. This leads to the server adding an extra email to the user's contacts.

### What changes do you think we should make in order to solve the problem?
We need to ensure that before sign-in call is made auth data should be cleared. To achieve this, we should add something like the following code block just before [this line](https://github.com/Expensify/App/blob/38030f88f885b13f9ca89fcaea31492061f602cf/src/pages/signin/LoginForm/BaseLoginForm.js#L156):

if (Session.isAnonymousUser()) {
    updateSessionAuthTokens(null, null);
    NetworkStore.setAuthToken(null);
}

This code will reset the authToken before the sign-in process begins.

Additionally, we should make sure that the sign-in modal remains open in the case of a non-anonymous user attempting to sign in through the modal instead of redirecting to home page.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ayazalavi** [comment] 2023-09-26 04:14
@0xmiroslav do you think my proposal is enough to fix the bug?

**Comment by kevinksullivan** [comment] 2023-09-27 03:49
@0xmiroslav checking in on this

**Comment by kevinksullivan** [comment] 2023-10-03 22:10
@0xmiroslav can you elaborate on what you're asking about? I can weigh in on bug or feature if you explain or link me to what you're referring to.

**Comment by ayazalavi** [comment] 2023-10-12 13:16
### Proposal
[Updated](https://github.com/Expensify/App/issues/27524#issuecomment-1733743679)

**Comment by ayazalavi** [comment] 2023-10-12 13:18
@0xmiroslav, please take a look at my proposal. I can swiftly implement a utility function that filters emails based on criteria, such as a regex pattern, before displaying them. I'll be able to share a pull request within 2 hours.

**Comment by ayazalavi** [comment] 2023-10-13 11:52
@0xmiroslav can you check my updated proposal. It is addressing problem quite clearly and providing a fix as well.

**Comment by ayazalavi** [comment] 2023-10-13 11:57
Yes we can do that as well. Need to write up custom handler for achieving this. This handler will check for anonymous login and ignore any addition to secondary contacts with specific pattern.

**Comment by ayazalavi** [comment] 2023-10-13 11:59
I think it is better to filter them out during display, that will keep it simpler and remove unnecessary emails using regex simultaneously.

**Comment by ayazalavi** [comment] 2023-10-13 12:01
> Why can't we prevent adding those emails to Onyx after login?

We can prevent that but in such case we need to make sure request for signin removes anonymous user details.

**Comment by ayazalavi** [comment] 2023-10-13 12:02
i.e signin in as normally user does from homepage. We need to clear anonymous user session data for this purpose.

**Comment by ayazalavi** [comment] 2023-10-13 13:37
> I think we should fix in backend if it's really bug

@0xmiroslav, there is no need for backend changes, as we can filter out emails either before or after adding them to Onyx. We can also remove unnecessary emails using the DeleteContact API, so I believe this can be managed on the frontend. What is your suggested approach? I am ready to implement the changes as per your recommendations and can generate a pull request in the next 2-3 hours.

**Comment by ayazalavi** [comment] 2023-10-16 05:58
@0xmiroslav any updates?

**Comment by ayazalavi** [comment] 2023-10-16 16:43
@0xmiroslav, I have updated my proposal that can help resolve this issue. Kindly take a look and let me know your thoughts. I am open to your suggestions for updating the proposal. https://github.com/Expensify/App/issues/27524#issuecomment-1733743679

**Comment by kevinksullivan** [comment] 2023-10-17 16:16
@0xmiroslav bumping this. Should this be internal?

**Comment by youssef-lr** [comment] 2023-10-17 16:52
I think this should be internal, filtering out the email in the frontend does not solve the actual bug where we're adding a non-existant email as a secondary contact method. cc @marcochavezf what do you think?

**Comment by ayazalavi** [comment] 2023-10-17 17:33
@youssef-lr, yes, ideally, this issue needs to be addressed to prevent redundant emails from being added. However, implementing backend changes might be complex, especially since I've noticed that new emails are being created for anonymous users. Modifying this entire functionality could be quite complicated. As an alternative, we can either keep Onyx clear from redundant emails or filter them before displaying them. A single line of code might suffice to resolve this issue.

**Comment by ayazalavi** [comment] 2023-10-18 11:39
@marcochavezf can you provide your input about comments above?

**Comment by youssef-lr** [comment] 2023-10-23 22:26
Not a priority right now, will get to this later this week.

**Comment by marcochavezf** [comment] 2023-10-24 00:28
Oh interesting, when a user "claims" an anonymous account, we create a new one and gets merged into the anonymous one and I think a side effect is that we're converting it into a secondary account. This should be a definitely a backend issue.

**Comment by marcochavezf** [comment] 2023-10-24 00:29
@youssef-lr if you want, you can assign this issue to me

**Comment by kevinksullivan** [comment] 2023-10-27 03:02
Feel free to assign me back if you need BZ here

**Comment by ayazalavi** [comment] 2023-10-27 03:46
@kevinksullivan are you considering my proposal?

**Comment by youssef-lr** [comment] 2023-10-28 11:48
@ayazalavi we'll be fixing this in the backend. @marcochavezf assigned you the issue, thanks!

**Comment by marcochavezf** [comment] 2023-10-30 19:29
No update

**Comment by marcochavezf** [comment] 2023-11-02 18:59
No update

**Comment by marcochavezf** [comment] 2023-11-06 20:13
No update

**Comment by marcochavezf** [comment] 2023-11-08 16:28
Moving this to weekly atm, swamped with other dailies

**Comment by marcochavezf** [comment] 2023-11-20 19:51
No update

**Comment by marcochavezf** [comment] 2023-11-30 17:05
No update

**Comment by marcochavezf** [comment] 2023-12-11 19:32
No update

**Comment by marcochavezf** [comment] 2023-12-20 19:13
No update, focused on wave bugs

**Comment by marcochavezf** [comment] 2023-12-29 19:13
No update

**Comment by marcochavezf** [comment] 2024-01-09 01:09
Focused on wave issues, no update

**Comment by marcochavezf** [comment] 2024-01-17 19:13
Focused on wave issues, no update

**Comment by mallenexpensify** [comment] 2024-01-24 03:50
@aimane-chnaif reassigning, please take over as C+. If you don't have bandwidth, unassign yourself. Thanks

**Comment by mallenexpensify** [comment] 2024-01-27 18:04
@kevinksullivan re-adding you as BZ to help align this with a project and help move it forward (assuming we want).

**Comment by marcochavezf** [comment] 2024-02-05 19:15
Hi @kevinksullivan, do you think this issue should be part of a wave or a VIP project?

**Comment by marcochavezf** [comment] 2024-02-14 16:24
I realized this can be part of vip-vsp, since this can impact the users from `#new-expensify-feedback`, I will move it there but meanwhile I'm prioritizing wave work

**Comment by kevinksullivan** [comment] 2024-02-21 22:59
Sorry for missing this @marcochavezf , but huh, that is very weird. I think this should be considered in vip-vsb. Have you posted about it there?

**Comment by marcochavezf** [comment] 2024-03-01 19:52
Working on this one today

**Comment by marcochavezf** [comment] 2024-03-07 23:25
Working on it in draft PR

**Comment by marcochavezf** [comment] 2024-03-18 18:21
[PR](https://github.com/Expensify/Auth/pull/10144) to hide secondary anonymous accounts in review. We still need to remove the secondary accounts for the new and existing accounts, but that will be addressed as a follow-up.

**Comment by kevinksullivan** [comment] 2024-03-19 22:00
Moving to VSB since this is public room related.

**Comment by marcochavezf** [comment] 2024-04-01 19:52
The PR to hide the anonymous logins was merged and deployed to production, so we can close this one. However, there's still a pending clean-up that doesn't impact users, and that will be addressed as a [follow-up PR](https://github.com/Expensify/Auth/pull/10129).

**Comment by marcochavezf** [comment] 2024-04-11 00:32
Focused on wave issues first

**Comment by marcochavezf** [comment] 2024-04-22 18:01
No update, working on a hold request bug and the awareness campaign

**Comment by kevinksullivan** [comment] 2024-04-30 22:42
@marcochavezf just for reference, would you mind linking the issues you're prioritizing over this one? That way if you're just on a bunch of wave issues perhaps we find someone else. Thanks!

**Comment by marcochavezf** [comment] 2024-04-30 23:08
Sure, these are the issues I was referring to:
- https://github.com/Expensify/Expensify/issues/378314
- https://github.com/Expensify/Expensify/issues/383789

Along with these new ones:
- https://github.com/Expensify/App/issues/41180
- https://github.com/Expensify/App/issues/40664

Also, from a user perspective the issue is [fixed](https://github.com/Expensify/App/issues/27524#issuecomment-2030451212) and we'd just need to complete the [clean-up PR](https://github.com/Expensify/Auth/pull/10129) (which is a bit complex and probably it will require considerable engineering time).

**Comment by marcochavezf** [comment] 2024-04-30 23:10
I will apply the retest label to ensure QA is passing here

**Comment by marcochavezf** [comment] 2024-05-07 02:12
[Pending clean-up](https://github.com/Expensify/Auth/pull/10129) ready for review

**Comment by mvtglobally** [comment] 2024-05-13 14:19
Issue not reproducible during KI retests. (First week)

**Comment by marcochavezf** [comment] 2024-05-19 15:54
Clean-up was already merged and deployed, closing it out

**Closed by marcochavezf** 2024-05-19 15:54 UTC
Labels: Reviewing, Engineering, Weekly, Internal, Bug, retest-weekly
