### ISSUE TITLE
[$250] Transfer Owner - Back navigation loop occurs after refreshing page on transfer owner success

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39503] opened 2024-04-03 14:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User is an admin of a collect workspace where the owner is someone else
1. Navigate to staging.new.expensify.com
2. Go to workspace page and open the collect workspace
3. Open members page
4. Click on the owner
5. Click on "Transfer owner"
6. When the success page loads refresh the page
7. Click on the back icon at the top left corner of the RHP
8. Keep clicking on the back icon

## Expected Result:
The RHP should close and user should be back to the members page

## Actual Result:
A loop of back navigation occurs and user can't close the RHP by using the back icon

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c668005d-5a4f-44d7-ac0e-855c195c687e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0112ee6df4d50d20d5</li>
        <li>Upwork Job ID: 1777811351787634688</li>
        <li>Last Price Increase: 2024-04-16</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-03 14:32
@MitchExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-04-03 14:32
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-04-03 15:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing back from workspace member detail after change owner success will navigate the user back to the success page, only after refresh. 

### What is the root cause of that problem?
When we press the back button, it will call a `navigate` function.
https://github.com/Expensify/App/blob/7177173f4b686a32bfcb94f07f0541b2f865f31b/src/pages/workspace/members/WorkspaceOwnerChangeSuccessPage.tsx#L26-L29

This works fine when we go to the page in a normal flow because the nav stack will be,
[ws member detail, owner change check, owner change success]

so navigating to ws member detail will bring the user to the first stack item.
[ws member detail]

But if the user refresh while in owner change success, the nav stack will be,
[owner change success]

and navigating to ws member detail will add it to the stack
[owner change success, ws member detail]

So, pressing back will bring the user back to owner change success and infinitely looped.

This happen in owner change check and owner change error page too.
### What changes do you think we should make in order to solve the problem?

Pop the current page first before doing the navigation.
```
Navigation.goBack();
Navigation.navigate(ROUTES.WORKSPACE_MEMBER_DETAILS.getRoute(policyID, accountID));
```

This is what we did for invite message too.
https://github.com/Expensify/App/blob/7177173f4b686a32bfcb94f07f0541b2f865f31b/src/pages/workspace/WorkspaceInviteMessagePage.tsx#L98-L100

We need to fix this in owner change check and owner change error page too.

### What alternative solutions did you explore? (Optional)
Use go back and force the fall back, but not ideal.

```
Navigation.goBack(ROUTES.WORKSPACE_MEMBER_DETAILS.getRoute(policyID, accountID), true);
```

**Comment by MitchExpensify** [comment] 2024-04-04 03:44
> We think that this bug might be related to #wave-collect - Release 1

Agree!

**Comment by MitchExpensify** [comment] 2024-04-08 21:59
This is not reproducible on v1.4.60-13, closing

**Comment by bernhardoj** [comment] 2024-04-09 04:25
@MitchExpensify hi, it's still reproducible. Do you refresh the page when you are in the success page?

https://github.com/Expensify/App/assets/50919443/aeb37a5e-89f7-4a30-aaef-0fde69baaf8b

**Comment by MitchExpensify** [comment] 2024-04-09 21:30
That did the trick @bernhardoj !

**Comment by eh2077** [comment] 2024-04-12 13:47
> User is an admin of a collect workspace where the owner is someone else

Can someone tell me how to change owner to someone else? I tried to create a collect workspace in olddot and run 
```js
if (Url.getCurrentPageName()!="policy" ){ alert('Only run this snippet from a policy editor!'); } else { var p = Policy.getCurrent(); p.policy.isPolicyExpenseChatEnabled = "true"; p.save().done(function(){$.jGrowl('Workspace chat creation enabled!')}); }
```
In olddot, I don't see an `owner` role in the add person page
<img width="492" alt="image" src="https://github.com/Expensify/App/assets/117511920/7e5b8d2e-c179-4696-82a9-a5fc55e32715">

**Comment by eh2077** [comment] 2024-04-13 02:15
> User is an admin of a collect workspace where the owner is someone else

@lanitochka17 May I know how to setup this precondition?

**Comment by eh2077** [comment] 2024-04-15 08:57
> > User is an admin of a collect workspace where the owner is someone else
> 
> @lanitochka17 May I know how to setup this precondition?

@lanitochka17 Friendly bump! I was asked to add payment card to transfer owner. Is there a card available for test?

<img width="1439" alt="image" src="https://github.com/Expensify/App/assets/117511920/f7b39a22-5621-462f-b0d9-a00857a6ec64">

**Comment by MitchExpensify** [comment] 2024-04-15 20:07
> User is an admin of a collect workspace where the owner is someone else

Invite anyone to a Collect Workspace via the members tab and update their role to Admin by clicking their row:

<img width="1192" alt="image" src="https://github.com/Expensify/App/assets/36425901/fd382451-85f6-45da-9aaf-f3bb46f2c5ab">

**Comment by eh2077** [comment] 2024-04-16 06:13
Ok, I can reproduce this when refresh the error page

https://github.com/Expensify/App/assets/117511920/fcc4f445-c54f-463e-8f26-656716f0c77a

**Comment by eh2077** [comment] 2024-04-16 06:31
@bernhardoj 's [proposal](https://github.com/Expensify/App/issues/39503#issuecomment-2034945288) looks good to me. Calling `Navigation.goBack();` before `Navigation.navigate` to pop the page from navigation history should be the right solution for this kind of issue. I also agree we should fix similar pages together. 

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-04-18 06:40
PR is ready

cc: @eh2077

**Comment by skmanoj322** [comment] 2024-04-18 10:14
> > > User is an admin of a collect workspace where the owner is someone else
> > 
> > 
> > @lanitochka17 May I know how to setup this precondition?
> 
> @lanitochka17 Friendly bump! I was asked to add payment card to transfer owner. Is there a card available for test?
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/117511920/322417791-f7b39a22-5621-462f-b0d9-a00857a6ec64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzIwNjEsIm5iZiI6MTcxMzQzMTc2MSwicGF0aCI6Ii8xMTc1MTE5MjAvMzIyNDE3NzkxLWY3YjM5YTIyLTU2MjEtNDYyZi1iMGQ5LWEwMDg1N2E2ZWM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwOTE2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWRmM2NiNmU4MTMwZDBkMWJlNTBmZTAyMzc1MmUxNzE3MDcwODJhMjY5MWY5YzBmNWMxYzM4ODZlYjFmNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gFO-cFwGb_KlRXara8uK_Bn33kpdYG8Ua-HRo5CtUAE">
> Using this test card num `4242 4242 4242 4242` ends up in an error page
> 
> <img alt="image" width="1438" src="https://private-user-images.githubusercontent.com/117511920/322421017-febb1984-d39a-4b4b-92fb-a968d43c2f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzIwNjEsIm5iZiI6MTcxMzQzMTc2MSwicGF0aCI6Ii8xMTc1MTE5MjAvMzIyNDIxMDE3LWZlYmIxOTg0LWQzOWEtNGI0Yi05MmZiLWE5NjhkNDNjMmY3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwOTE2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGVjZDU4YmEyNTE0NWRlMTgxZDg0NmMxM2RlZWMwN2IxODdkOTY5OTE2N2M4MWEyYjExNzBjMTViYTQ1OWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sMtdLB5ofvKj07L3sKihlAf8CZn1e8-_GFR4ctCUviY">
 
may i know how you were able to reproduce it i am facing the same dump?

**Comment by MitchExpensify** [comment] 2024-05-06 20:34
**Payment summary**:

$250 C+ @eh2077 
$250 C @bernhardoj

**Comment by MitchExpensify** [comment] 2024-05-06 20:38
Paid and contracts ended

**Closed by MitchExpensify** 2024-05-06 20:38 UTC
Labels: Reviewing, External, Weekly, Bug
