### ISSUE TITLE
[HOLD for payment 2024-10-24] [$250] Forward delete moves cursor location after deleting a character

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#48797] opened 2024-09-09 16:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.31-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @tgolen 
**Slack conversation:** https://expensify.slack.com/archives/C05LX9D6E07/p1725900088874679

## Action Performed:
1. Initiate a DM with any user
2. Compose a message
3. Place the cursor in the middle of the composed message
4. Press the `Delete` button on the keyboard
## Expected Result:
Pressing the delete key should delete characters after the cursor, then the cursor should remain in its current opsition.
## Actual Result:
~Pressing the delete key is deleting characters before the cursor~ After deleting the character after the cursor (expected), the cursor advances one character to the left (unexpected). 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6c40d39f-7823-4358-ba55-4e246b4e23f6

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834326245043110651</li>
        <li>Upwork Job ID: 1834326245043110651</li>
        <li>Last Price Increase: 2024-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Reviewer | 103988646</li>
<li>QichenZhu | Contributor | 103988649</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify / @jliexpensify</details>

**Comment by BreakTos** [comment] 2024-09-09 16:59
Can this issue be assigned to me ? Looks like something i can contribute to

**Comment by BreakTos** [comment] 2024-09-09 17:05
Contributor details
Your Expensify account email: parthseth2004@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0158b590a3a6ca253f

**Comment by Shahidullah-Muffakir** [comment] 2024-09-09 17:20
In the video shared, the **Delete** key is erasing characters to the **right of the cursor**, which I also tested and found to be true. I believe this is the expected behavior.
As the Backspace key is meant to delete characters to the left of the cursor, while the Delete key should erase characters to the right. Given this, it seems like the Delete key is working as it should.

**Comment by tylerkaraszewski** [comment] 2024-09-09 21:54
The video is recorded on windows, not MacOS.

**Comment by muttmuure** [comment] 2024-09-10 17:54
I'm not sure we've established that this is unexpected behavior here

**Comment by rafecolton** [comment] 2024-09-12 01:28
The bug description is incorrect. It is not deleting the character before the cursor, which would be unexpected for forward delete. It is deleting the character after (expected), but then advancing the cursor one position to the left (unexpected). The cursor should stay where it is. Reported [here](https://expensify.slack.com/archives/C049HHMV9SM/p1726086229422149) for macOS too.

**Comment by rafecolton** [comment] 2024-09-12 01:31
Happy to take over this issue @youssef-lr, I will be joining the NewDot Quality and ECM chores very soon.

**Comment by rafecolton** [comment] 2024-09-12 20:18
Per conversation [here](https://expensify.slack.com/archives/C05LX9D6E07/p1726168282752879), I'm taking this over and will solicit proposal for it. I'll also update the OP to correctly state the bug. Not sure if this should be a NewDot Quality issue or not, so discussing that in that thread.

**Comment by QichenZhu** [comment] 2024-09-13 06:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The caret is in the wrong position after deleting a character with the Delete key in Composer.

### What is the root cause of that problem?
The line below from the live markdown library calculates the new caret position:

https://github.com/Expensify/react-native-live-markdown/blob/0f8f21cb4e7379d8a20111f6023d274536ad5c1e/src/MarkdownTextInput.web.tsx#L297
```TSX
const newCursorPosition = Math.max(Math.max(contentSelection.current.end, 0) + (parsedText.length - previousText.length), 0);
```

In the case of this issue, `parsedText.length - previousText.length` equals -1, which moves the caret one character backward before the selection end.

This behavior is correct when deleting backward or deleting forward with at least one character selected but incorrect when deleting forward with no characters selected.

### What changes do you think we should make in order to solve the problem?
Calculate the new caret position as below:

```TSX
const newCursorPosition = (inputType === 'deleteContentForward' && contentSelection.current.start === contentSelection.current.end)
    ? Math.max(contentSelection.current.start, 0) // Don't move the caret when deleting forward with no characters selected.
    : Math.max(Math.max(contentSelection.current.end, 0) + (parsedText.length - previousText.length), 0);
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by rafecolton** [comment] 2024-09-14 22:57
I do the CME chore so not sure why Jules was assigned. Maybe the response to the C+ reviewed message looks at the team instead of the chore. I'll check it out.

**Comment by rafecolton** [comment] 2024-09-16 17:44
Was just looking at it. It looks great, and it worked when I tested it locally. Assigning them now.

**Comment by QichenZhu** [comment] 2024-09-17 05:40
@ishpaul777 [PR](https://github.com/Expensify/react-native-live-markdown/pull/496) is up for review by `react-native-live-markdown` maintainers.

cc: @rafecolton

**Comment by rafecolton** [comment] 2024-09-18 23:34
@Skalakid will you add the `$ <issue link>` to the body of your PR so this issue gets tested as part of that change.

**Comment by rafecolton** [comment] 2024-09-18 23:35
Not overdue Melvin

**Comment by rafecolton** [comment] 2024-09-18 23:41
Confirmed @Skalakid's PR includes this fix, so now we'll wait for that to be merged and deployed.

**Comment by mallenexpensify** [comment] 2024-09-19 00:50
When I hold down the `fn` key and tap `delete` to remove text in front of the cursor, it doesn't work. Will that bug be fixed here too?

**Comment by rafecolton** [comment] 2024-09-19 03:08
Do you have a video @mallenexpensify? I bet if you take a closer look, you'll see it does work and just doesn't _look_ like it worked because it moves the cursor position afterwards.

**Comment by mallenexpensify** [comment] 2024-09-19 21:51
You bug might also be a part of _mine_.   The functionality of `fn+delete` def isn't working correctly, which you might be able to see in the vid.  
https://github.com/user-attachments/assets/50315d7c-f4e8-4ad5-836c-11b99d19b021

**Comment by rafecolton** [comment] 2024-09-19 21:59
@mallenexpensify in your video, the functionality _is_ working correctly. If you look closely, you are in fact deleting the character to the right of the cursor. This is exactly the same as the bug that is being fixed here.

**Comment by muttmuure** [comment] 2024-09-30 15:31
I'm not 100% sure this is a quality bug, but it is nearly fixed anyway, so I'm going to remove it from the project to focus the scope there.

**Comment by rafecolton** [comment] 2024-09-30 17:21
Sounds good, thanks Matt

**Comment by rafecolton** [comment] 2024-09-30 19:23
Not overdue. PR was recently merged, waiting for this change to be deployed.

**Comment by mallenexpensify** [comment] 2024-10-01 22:24
@jliexpensify you can assign to me for payment, if needed. 

When you post payment summaries, can you use the below format? For auditing purposes we need to know where someone is being paid (Upwork vs NewDot) and also if they're due/owed funds are 'paid'. Thx

**Comment by jliexpensify** [comment] 2024-10-01 22:26
Will do in the future, thanks @mallenexpensify!

**Comment by mallenexpensify** [comment] 2024-10-18 22:50
whoohooo... it's fixed!! Thx

**Comment by jliexpensify** [comment] 2024-10-23 09:39
Hi @ishpaul777 - do we need a checklist here?

**Comment by rafecolton** [comment] 2024-10-23 18:23
Sounds great, thank you! Definitely agree we need one while we were waiting for the fix to get merged, the issue actually got worse somehow

**Comment by jliexpensify** [comment] 2024-10-24 02:40
Payment Summary

- C: @QichenZhu owed $250 via Upwork
- C+: @ishpaul777 owed $250 via Upwork

[Upwork job](https://www.upwork.com/jobs/~021834326245043110651)

**Comment by jliexpensify** [comment] 2024-10-24 02:54
Payment Summary

- C: @QichenZhu owed $250 via Upwork
- C+: @ishpaul777 owed $250 via Upwork

[New Upworks Job](https://www.upwork.com/jobs/~021849282864645257398) - the other one closed automatically so please accept my offers here, thanks!

**Comment by jliexpensify** [comment] 2024-10-25 02:14
Paid and job closed!

**Closed by jliexpensify** 2024-10-25 02:14 UTC
Labels: External, Daily, Awaiting Payment, Bug, AutoAssignerNewDotQuality
