### ISSUE TITLE
Workspace - "Closed this report" briefly displayed when opening deleted WS chat first time

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52698] opened 2024-11-18 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.63-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Tap on "Settings" on the bottom of the screen.
3. Tap on "Workspaces"
4. Tap on the three dots icon on any workspace and delete it.
5. Return to LHN.
6. Open the just deleted workspace chat.
7. Verify that no new messages can be sent on chat and that no "Closed this report" message is displayed.
8. Open the #Admins room of the deleted workspace.
9. Return to LHN and verify that the chat didn´t disappear.

## Expected Result:
When opening a deleted workspace chat, no "Closed this report" message should be displayed and the #Admins room should remain on LHN when opened.

## Actual Result:
When a deleted workspace chat is opened for the first time, a "Closed this report" message is displayed for some seconds, and when #Admins room of that workspace is opened, it disappears from LHN and reappears when app is reopened.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Bug6667894_1731932425301!e4a55557-48fb-4276-ad9f-a62b22c15f2d](https://github.com/user-attachments/assets/846d6ca4-c430-4e0c-9fd0-2665ff141e21)

https://github.com/user-attachments/assets/72d5baa9-26df-486c-8319-f640e2c92f2d

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-11-18 13:44
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - "Closed this report" briefly displayed when opening deleted WS chat first time

### What is the root cause of that problem?
We already hide `closed this report` report actions here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L193
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/libs/ReportActionsUtils.ts#L653
But we haven't applied the condition to check if the report action is visible for mostRecentReportAction in report screen here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/ReportScreen.tsx#L704-L709
### What changes do you think we should make in order to solve the problem?

We should apply the same logic we use to filter out invisible report actions in [ReportActionsList](https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L193) for mostRecentAction in ReportScreen
```
const isVisible =
        !!mostRecentReportAction &&
        (isOffline ||
            ReportActionsUtils.isDeletedParentAction(mostRecentReportAction) ||
            mostRecentReportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ||
            mostRecentReportAction.errors) &&
        ReportActionsUtils.shouldReportActionBeVisible(mostRecentReportAction, mostRecentReportAction.reportActionID);
    const shouldShowMostRecentReportAction =
        !!mostRecentReportAction &&
        !isSingleExpenseReport &&
        !isSingleInvoiceReport &&
        !ReportActionsUtils.isActionOfType(mostRecentReportAction, CONST.REPORT.ACTIONS.TYPE.CREATED) &&
        !ReportActionsUtils.isDeletedAction(mostRecentReportAction) &&
        isVisible;
```
We can obviously create a util function to re-use it in both instance to make it DRY
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-11-18 13:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - "Closed this report" briefly displayed when opening deleted WS chat first time

### What is the root cause of that problem?
We already hide `closed this report` report actions here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L193
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/libs/ReportActionsUtils.ts#L653
But we haven't applied the condition to check if the report action is visible for mostRecentReportAction in report screen here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/ReportScreen.tsx#L704-L709
### What changes do you think we should make in order to solve the problem?

We should apply the same logic we use to filter out invisible report actions in [ReportActionsList](https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L190-L193) for mostRecentAction in ReportScreen as we want only to show most recent action if it is going to be visible inside report action list.
```
const isVisible =
        !!mostRecentReportAction &&
        (isOffline ||
            ReportActionsUtils.isDeletedParentAction(mostRecentReportAction) ||
            mostRecentReportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ||
            mostRecentReportAction.errors) &&
        ReportActionsUtils.shouldReportActionBeVisible(mostRecentReportAction, mostRecentReportAction.reportActionID);
    const shouldShowMostRecentReportAction =
        !!mostRecentReportAction &&
        !isSingleExpenseReport &&
        !isSingleInvoiceReport &&
        !ReportActionsUtils.isActionOfType(mostRecentReportAction, CONST.REPORT.ACTIONS.TYPE.CREATED) &&
        !ReportActionsUtils.isDeletedAction(mostRecentReportAction) &&
        isVisible;
```
We can obviously create a util function to re-use it in both instance to make it DRY
We can also remove `isDeletedAction` check as the check already exists in `shouldReportActionBeVisible`
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-11-18 13:58
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace - "Closed this report" briefly displayed when opening deleted WS chat first time

### What is the root cause of that problem?
We already hide `closed this report` report actions here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L193
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/libs/ReportActionsUtils.ts#L653
But we haven't applied the condition to check if the report action is visible for mostRecentReportAction in report screen here
https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/ReportScreen.tsx#L704-L709
hence it appears briefly via ReportScreen for `shouldShowSkeleton` case and disappears when ReportActionList is displayed as it filters it out.

### What changes do you think we should make in order to solve the problem?

We should apply the same logic we use to filter out invisible report actions in [ReportActionsList](https://github.com/Expensify/App/blob/63c8dd2bb44deb2d62e223530fa0d734f1cfba5c/src/pages/home/report/ReportActionsList.tsx#L190-L193) for mostRecentAction in ReportScreen as we want only to show most recent action if it is going to be visible inside report action list.
```
const isVisible =
        !!mostRecentReportAction &&
        (isOffline ||
            ReportActionsUtils.isDeletedParentAction(mostRecentReportAction) ||
            mostRecentReportAction.pendingAction !== CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE ||
            mostRecentReportAction.errors) &&
        ReportActionsUtils.shouldReportActionBeVisible(mostRecentReportAction, mostRecentReportAction.reportActionID);
    const shouldShowMostRecentReportAction =
        !!mostRecentReportAction &&
        !isSingleExpenseReport &&
        !isSingleInvoiceReport &&
        !ReportActionsUtils.isActionOfType(mostRecentReportAction, CONST.REPORT.ACTIONS.TYPE.CREATED) &&
        !ReportActionsUtils.isDeletedAction(mostRecentReportAction) &&
        isVisible;
```
We can obviously create a util function to re-use it in both instance to make it DRY
We can also remove `isDeletedAction` check as the check already exists in `shouldReportActionBeVisible`
### What alternative solutions did you explore? (Optional)

**Comment by FitseTLT** [comment] 2024-11-18 13:59
To easily reproduce it you can Troubleshoot > clear cache and immediately open the archive expense chat 👍

**Comment by joekaufmanexpensify** [comment] 2024-11-19 00:48
I don't really think this is worth prioritizing right now. I am dubious that this has really any customer impact as it's just when the skeleton UI is displayed and then goes away (for deleted workspaces only). Let's see if this has any actual customer impact before changing this.

**Closed by joekaufmanexpensify** 2024-11-19 00:48 UTC
Labels: Daily, Bug
