### ISSUE TITLE
[$250] Dev - Unable to build the Desktop app  - Reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10890] opened 2022-09-08 04:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Just try to build Desktop App, and see it's not possible.

## Expected Result:
You should be able to build the Desktop app anytime.

## Actual Result:
Unable to build the Desktop app . PR responsible. https://github.com/Expensify/App/pull/10436

## Workaround:
> n/a, unknown 

## Platform:
>Where is this issue occurring?
- Desktop App

**Version Number:** latest
**Reproducible in staging?:** N
**Reproducible in production?:** N
**Upwork job URL:** https://www.upwork.com/jobs/~01dcb93c38c4a2c67d
**Issue reported by:** @parasharrajat 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661361515615089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by michaelhaxhiu** [comment] 2022-09-14 10:30
This seems like a regression, right? Since this used to work, but a new change broke it?

If so, let's make sure we kick off an RCA

**Comment by iwiznia** [comment] 2022-09-15 12:43
> Unable to build the Desktop app . PR responsible. #10436

hmmm interesting, what's in that PR that broke desktop app?

**Comment by michaelhaxhiu** [comment] 2022-09-15 13:08
Exported to upwork - https://www.upwork.com/jobs/~01dcb93c38c4a2c67d

**Comment by railway17** [comment] 2022-09-15 13:31
Does this issue need a proposal?
Actually, it is resolved in the latest main branch, but not working in the previous [PR](https://github.com/Expensify/App/pull/10436) 🤔

**Comment by michaelhaxhiu** [comment] 2022-09-19 17:59
Paid.

**Closed by michaelhaxhiu** 2022-09-19 17:59 UTC
Labels: Exported, External, Engineering, Weekly, Help Wanted
