### ISSUE TITLE
IOU Report item flickers (while showing a Pay button momentarily) when we cancel one of the transactions.

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13258] opened 2022-12-02 01:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat with say User A
2. Request money multiple times with different amounts (idea is to have atleast a few transactions)
3. You should see the IOU report item, User A owes you
4. Open the details page and cancel one of the request for money transactions
5. Observe the IOU report item.
6. It flickers with a different amount momentarily showing the Pay button, and then shows a the correct amount again.

## Expected Result:
 IOU report item shouldn't flicker, and the updated amount should show up instantaneously.

## Actual Result:
 IOU report item flickers with Pay button showing temporarily

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.33-1
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/205193625-4d0467f8-8337-442d-834b-c51bacab7b0b.MP4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @mananjadhav 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1669716624236259

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2022-12-02 11:52
@techievivek @youssef-lr @mountiny, this is a dupe of https://github.com/Expensify/App/issues/12781, right? 

Going to close it out, but let me know if I missed something.

**Closed by trjExpensify** 2022-12-02 11:52 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by techievivek** [comment] 2022-12-02 13:32
I am pretty sure @youssef-lr fixed this one. Not sure why this is happening again. @youssef-lr any idea?

**Comment by youssef-lr** [comment] 2022-12-02 13:48
Yes the fix got deployed to in v1.2.32-2 while this was tested in 1.2.32-1.
