### ISSUE TITLE
[HOLD for payment 2024-04-09] [$500]  Mark down - Live preview for code block with strikethrough is incorrect

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37533] opened 2024-02-29 17:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch New Expensify app
2. Go to any chat
3. Type ~```Code```~
4. Note that live mark down preview
5. Send the text

## Expected Result:
The live mark down preview for ~```Code```~ should correctly show the actual mark down

## Actual Result:
The live mark down preview for ~```Code```~ is incorrect. It shows that the strikethrough is applied, when strikethrough does not work with code block in the sent text

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/dd57a2e1-3d63-4a0a-b56a-b6e08b4be49b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012e80f0cbfad42ad6</li>
        <li>Upwork Job ID: 1763259471765831680</li>
        <li>Last Price Increase: 2024-02-29</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-29 17:32
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-02-29 17:32
@puneetlath  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by puneetlath** [comment] 2024-02-29 18:18
@brandonhenry live markdown is only on mobile right now, FYI. I'm able to reproduce it there.

**Comment by bernhardoj** [comment] 2024-03-01 08:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The live markdown shows a preview of a strikethrough + code fence markdown, but when sent, the strikethrough is not applied.

### What is the root cause of that problem?
One of the differences between the live markdown and the sent markdown is that the [live markdown set `shouldKeepRawInput` to `true`](https://github.com/Expensify/react-native-live-markdown/blob/831826d07bb7855e8f080ca3d27cbd4a502db056/parser/index.ts#L18-L20).

In ExpensiMark rule, strikethrough won't be converted to HTML if it includes a `<pre>` (codefence) tag.
https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L294-L298

However, if `shouldKeepRawInput` is enabled, it will convert codefence to `<pre data-code-raw ...>` which fails the condition above
https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L46-L50

### What changes do you think we should make in order to solve the problem?

I'm pretty sure we want to keep the old behavior, that is to prevent strikethrough being converted to HTML when it contains a codefence.
<img width="112" alt="image" src="https://github.com/Expensify/App/assets/50919443/317d18c9-d5a3-49d3-8770-66fb26480ee0">

To fix it, instead of checking whether it includes the opening tag (i.e., `<pre>`), we can check whether it includes the closing tag (i.e., `</pre>`) as we did for `h1` [here](https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L619).

We need to apply the fix to all occurrences (bold, strikethrough, italic, link)

### What alternative solutions did you explore? (Optional)
1. Use a regex to check whether it contains pre tag that optionally has an attribute (we can take the codefence regex [here](https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L410)).
2. Allow strikethrough (italic, bold, and link) + codefence by removing the [`<pre>` tag checking](https://github.com/Expensify/expensify-common/blob/77d0b150ba6bfbe7a64b3c3e30b65592b2e58c4a/lib/ExpensiMark.js#L297)

**Comment by allroundexperts** [comment] 2024-03-05 19:19
Reviewing today.

**Comment by allroundexperts** [comment] 2024-03-06 15:28
Thanks for the proposal @brandonhenry. I think you missed to include italics / links in your proposal which in my opinion should be removed as well. Also, I think for consistency, we should follow the pattern already established in the `h1` parsing.

As such, I think @bernhardoj's [proposal](https://github.com/Expensify/App/issues/37533#issuecomment-1972735577) looks better to me.

🎀 👀 🎀 C+ reviewed

**Comment by puneetlath** [comment] 2024-03-12 22:01
Sounds good 👍🏾

**Comment by bernhardoj** [comment] 2024-03-13 07:58
The expensify-common PR is [here](https://github.com/Expensify/expensify-common/pull/663)

cc: @allroundexperts

**Comment by allroundexperts** [comment] 2024-03-14 19:07
I am reviewing this Melv

**Comment by bernhardoj** [comment] 2024-03-20 09:47
Copying the comment from the PR to here for visibility.

> Is the next step to open an App PR to apply this expensify-common update?

@puneetlath @allroundexperts we would need to update the `expensify-common` version in `react-native-live-markdown`, but I think it would make sense to have the same version of `expensify-common` in App too.

`react-native-live-markdown` already has the [latest version of expensify-common](https://github.com/Expensify/react-native-live-markdown/blob/fb85ea4282d8fe331aca8bb805a183d631cd9331/parser/package.json#L23) (`dc8ea98`), except our recently merged commit (`9e47e1f`). I think we need a help from SWM team to update the package as `react-native-live-markdown` latest version is `0.1.28` and if we update it, that would be `0.1.29` which is 24 patch version apart from the current version in the App (`0.1.5`).

I see that this [issue](https://github.com/Expensify/App/issues/36227) will update the `react-native-live-markdown` to the latest version, but I don't see the App PR yet (@robertKozik cmiiw). I think we can hold for that issue or ask them to include our `expensify-common` update to `react-native-live-markdown`.

**Comment by bernhardoj** [comment] 2024-03-26 03:28
Thanks @shubham1206agra. I see that https://github.com/Expensify/App/pull/38152 bumps `react-native-live-markdown` to a higher version which includes our fix too. Let's hold for that instead.

@puneetlath @allroundexperts

**Comment by puneetlath** [comment] 2024-03-27 20:22
Looks like that was merged. Can you test that everything is working as expected with our changes in this issue?

**Comment by bernhardoj** [comment] 2024-03-28 03:50
Here is the retesting result, all works fine (as the live markdown is now available on Web, I have included the web result too):

<details>
<summary>Android</summary>

https://github.com/Expensify/App/assets/50919443/8786f34d-83a7-4497-b720-02d2e3d7cad3


</details>

<details>
<summary>iOS</summary>

https://github.com/Expensify/App/assets/50919443/1828db93-72f8-420f-b1a5-8e3a78333cc6


</details>

<details>
<summary>Android mWeb</summary>

https://github.com/Expensify/App/assets/50919443/d97d3aa6-fe84-42b0-b92d-24ddae0c9a02


</details>

<details>
<summary>iOS mWeb</summary>

https://github.com/Expensify/App/assets/50919443/5c9ea072-627b-4a47-94c6-2e2d8adb2b9a


</details>

<details>
<summary>Desktop</summary>

https://github.com/Expensify/App/assets/50919443/740985fe-38d6-4a8e-a974-fb8028279337


</details>

<details>
<summary>Web</summary>

https://github.com/Expensify/App/assets/50919443/81744ba4-ce99-46b9-8449-b7d1f70e43a8


</details>

**Comment by puneetlath** [comment] 2024-03-28 15:54
Ok great! So we can pay according to when that PR goes to production.

**Comment by puneetlath** [comment] 2024-04-08 23:05
Payment summary: 
- C - $500 - @bernhardoj - to be paid via Upwork
- C+ - $500 - @allroundexperts - to be paid via NewDot

@bernhardoj can you please accept the Upwork offer? https://www.upwork.com/nx/wm/offer/101349515

**Comment by puneetlath** [comment] 2024-04-09 13:33
@bernhardoj has been paid. @allroundexperts please request on NewDot. 

Thanks everyone!

**Closed by puneetlath** 2024-04-09 13:33 UTC
Labels: Reviewing, External, Daily, Bug

**Comment by JmillsExpensify** [comment] 2024-05-03 18:20
$500 approved for @allroundexperts
