### ISSUE TITLE
Incositancy: Description does not accept multiline in the IOU report page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26277] opened 2023-08-30 12:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open any chat.
2. Click the (+) icon > click request money.
3. On description input write something long with line breaks.
Notice that description input accept multlines and line break.
4. Click on Save> Request Money
5. Go to the Money Request thread and Click on the description to edit
Notice that description input does not accept multlines and line break.

## Expected Result:
description input accepts multiline and line breaks when editing

## Actual Result:
description input does not accept multlines and line breaks.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/c5e1c136-26f5-4f4b-9217-fe7330b9e09b

https://github.com/Expensify/App/assets/115492554/5bf947b9-8f97-467c-988c-af5d798641fe

**Expensify/Expensify Issue URL:**

**Issue reported by:** @daveSeife

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693373161444729

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pradeepmdk** [comment] 2023-08-30 12:31
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Description does not accept multiline in the IOU report page
### What is the root cause of that problem?

currently multiline not added 
### What changes do you think we should make in order to solve the problem?

https://github.com/Expensify/App/blob/6e17b64be0e571773bed42446346045c659640d6/src/pages/EditRequestDescriptionPage.js#L45
 here need add
```
 autoGrowHeight
                        containerStyles={[styles.autoGrowHeightMultilineInput]}
```

**Comment by arosiclair** [comment] 2023-08-30 13:08
> Not blocker. Let's close this as dupe of #25494 Context: [#25494 (comment)](https://github.com/Expensify/App/issues/25494#issuecomment-1686306527)

Agreed. Closing out

**Closed** 2023-08-30 13:08 UTC
Labels: Engineering, Hourly, Bug
