### ISSUE TITLE
DEV: After deleting request money on Workspace, navigate to Concierge

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24123] opened 2023-08-03 17:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Pre-condition: Have a workspace
1. Click FAB => Request money
2.  Input amount => Next
3. Select workspace = request
4. Click on request money message
5. Hover on cash message => delete
6. Observe navigate to the previous report and then navigate to Concierge
## Expected Result: 
Observe navigate to the previous report the same with request money for user
## Actual Result: 
navigate to the previous report and then navigate to Concierge

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev
**Reproducible in staging?:** dev
**Reproducible in production?:** dev
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/88cf1529-d7ab-4a7a-8a82-b45be4d94c7f

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691028842094869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mvtglobally** [comment] 2023-08-03 17:38
potentially related to https://github.com/Expensify/App/issues/20908

**Comment by hayata-suenaga** [comment] 2023-08-03 17:44
As @mvtglobally pointed out, this is an existing bug that is being fixed in https://github.com/Expensify/App/issues/20908

Removing deploy blocker label and will keep track of this issue in the issue mentioned above

**Comment by hayata-suenaga** [comment] 2023-08-03 17:47
actually changing the priority to monthly as the above issue where the cause is being fix has a monthly label (the fix needs a change in a library we rely on, and changing a library takes a time)

**Comment by sakluger** [comment] 2023-09-05 19:07
Looks like the HOLD issue was fixed by another issue. @hayata-suenaga what does that mean for this issue?

**Comment by hayata-suenaga** [comment] 2023-09-05 20:11
@sakluger thank you for letting me know about it

I tested the bug reproduction flow and confirmed that the issue was fixed by [this PR](https://github.com/Expensify/App/pull/24165).

@sakluger could you check if we need payment to the bug reporter and then close the issue 🙇 

https://github.com/Expensify/App/assets/98560306/0f51456a-2530-4d16-80e8-0f01af68e4bc

**Comment by sakluger** [comment] 2023-09-11 18:49
Thanks @hayata-suenaga!

All the issues linked to that PR were reported in June, and this issue was reported on Aug 2, so I don't think we need to pay for this bug report.

**Closed by sakluger** 2023-09-11 18:49 UTC
Labels: Engineering, Daily, Overdue, Bug
