### ISSUE TITLE
[$500] Login - Infinite loading when login via Abracadabra page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37351] opened 2024-02-27 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4343102
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Log out of NewDot and request a new magic link
2. Navigate to email and locate the magic link - change to staging if needed
3. Open an new tab and navigate to the staging link
4. Verify the "Abracadabra, you're logged in" page is displayed
5. Navigate to the original tab

## Expected Result:
User should be logged in and there should be no long loading

## Actual Result:
Infinite loading when login via Abracadabra page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/835fb527-9f5e-4973-a48d-02232abe5513

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by yuwenmemon** [comment] 2024-02-27 21:27
I believe this was just due to the site slows we had just now. I'm not able to reproduce this anymore.

**Comment by lanitochka17** [comment] 2024-03-01 17:23
Hello
This issue is stil reproducible on the latest build 1.4.46-0


https://github.com/Expensify/App/assets/78819774/cb41e274-a214-49f0-b003-8590e6f3d75f

**Comment by yuwenmemon** [comment] 2024-03-01 20:24
Damn you're right. Very odd - looking into this now.

**Comment by yuwenmemon** [comment] 2024-03-01 20:26
Hmmm... I can't seem to reliably reproduce

**Comment by yuwenmemon** [comment] 2024-03-01 20:34
I notice we don't make any calls to OpenApp when we do encounter this though
![Screenshot 2024-03-01 at 12 31 50 PM](https://github.com/Expensify/App/assets/4741899/11cc92ed-5fce-48f6-b2ee-ad774dc2bca3)

**Comment by yuwenmemon** [comment] 2024-03-01 21:16
Okay, after some sleuthing looks like this is the PR that introduced the bug: https://github.com/Expensify/App/pull/36852

**Comment by yuwenmemon** [comment] 2024-03-01 21:38
I _feel_ like the problem is that we're calling [`findLastAccessedReport`](https://github.com/Expensify/App/blob/c186109101584d65152f576c87c124d53b44c16a/src/libs/ReportUtils.ts#L1021-L1030) before any reports are loaded: 

https://github.com/Expensify/App/assets/4741899/f93ffaba-84b1-44ef-86e4-98da3061d4bc

**Comment by bernhardoj** [comment] 2024-03-02 02:10
The OpenApp API is added to the SequentialQueue but never processed.

<img width="605" alt="image" src="https://github.com/Expensify/App/assets/50919443/c39727b0-880a-4293-a00c-25e4d7f95a94">

> I feel like the problem is that we're calling [findLastAccessedReport](https://github.com/Expensify/App/blob/c186109101584d65152f576c87c124d53b44c16a/src/libs/ReportUtils.ts#L1021-L1030) before any reports are loaded:

I'm not sure if this is the problem as this has happened for a long time. If `findLastAccessedReport` doesn't find anything, it will just be ignored and will be recalculated once the reports are ready.
https://github.com/Expensify/App/blob/af68510ad375bc99679908ce26dafead3a8b3dc1/src/libs/Navigation/AppNavigator/ReportScreenIDSetter.ts#L78-L95

**Comment by bernhardoj** [comment] 2024-03-02 02:20
@yuwenmemon I can reproduce this even after reverting https://github.com/Expensify/App/pull/36852

**Comment by yuwenmemon** [comment] 2024-03-04 20:47
@bernhardoj Yeah but also at the same time the behavior is working properly when checking out the commit before your PR was merged - so I feel like there's _some_ connection 🤔 

Working: https://github.com/Expensify/App/commit/dce04be3446b7ceb7d6dd6bd231c1db8e6210ab6
Non-Working: https://github.com/Expensify/App/commit/3601df81c87e08fb1a6c22b44ced152c24af37a4

**Comment by damadoko** [comment] 2024-03-05 00:03
I can't reproduce. It throw error immediately when back from Abracadabra tab. Maybe bumped `react-native-onyx@2.0.10` cause it.
<img width="383" alt="Screenshot 2024-03-05 at 07 02 40" src="https://github.com/Expensify/App/assets/57703073/a94e2e62-53f7-43df-9b1c-0413e0bb4ceb">
Not sure if above bug have tracked in GH issue.

**Comment by bernhardoj** [comment] 2024-03-05 12:10
Hmm, it works fine when I checkout https://github.com/Expensify/App/commit/3601df81c87e08fb1a6c22b44ced152c24af37a4.

From my investigation, this happened when we [changed the OpenApp method from READ to WRITE](ttps://github.com/Expensify/App/pull/37062).

First tab: sign in page
Second tab: magic code page

When we open the magic code page, the first tab becomes inactive. A WRITE request uses SequentialQueue and if it's not the active tab, the request will be ignored.
https://github.com/Expensify/App/blob/a8ece907ce2b027d27025ef7bd2242998dff7890/src/libs/Network/SequentialQueue.ts#L111-L115

That's why the OpenApp request is never processed on the first tab, though it's successfully processed on the second tab.

**Comment by bernhardoj** [comment] 2024-03-05 12:11
The weird thing is, even though the app data is available, 
<img width="569" alt="image" src="https://github.com/Expensify/App/assets/50919443/d4590c59-50c5-49f8-ad5a-e5a2214330d7">

the sidebar screen on the first tab report list has empty collection. It's like the API onyx data for report collection is not reflected on the first tab,
<img width="215" alt="image" src="https://github.com/Expensify/App/assets/50919443/b931afee-cf8b-4437-b30d-d329bfe875a7">

and I was correct. Currently, onyx is only able to synchronize the data between tabs if it's a SET, MERGE, and CLEAR.
https://github.com/Expensify/react-native-onyx/blob/69b2d5973b4aef19ce783440df55dedb30d4efd2/lib/storage/InstanceSync/index.web.ts#L43-L48

But merging a report collection uses MERGE_COLLECTION that either calls `multiSet`/`multiMerge`. So, to fix this, we should add a sync case for both `multiSet` and `multiMerge`.

Let me know if I should post a proposal.

**Comment by yuwenmemon** [comment] 2024-03-12 19:52
Ah nice @bernhardoj that makes sense to me.

**Comment by bernhardoj** [comment] 2024-03-13 11:01
@yuwenmemon there is currently another problem where the response from OpenApp is completely discarded because it's considered as an old data.

When we login with magic code link, we receive a pusher updates to set the user preferred locale before the OpenApp request completes. This will trigger a reconnect request.
https://github.com/Expensify/App/blob/f52bb0239f4f9aa6666a95d7140937e439760f35/src/libs/actions/OnyxUpdateManager.ts#L71-L76

The ReconnectApp `lastUpdateID` is then set as the `lastUpdateIDAppliedToClient`. When the OpenApp completes, the `lastUpdateID` has the same value as `lastUpdateIDAppliedToClient`.

Even though ReconnectApp is called, it doesn't give all of our report, hence we see many missings report.
<img width="384" alt="image" src="https://github.com/Expensify/App/assets/50919443/9aad1604-2588-42c3-9abb-2fc1135cbe60">

I can always reproduce this when using magic code link, but only once when sign in normally by typing the magic code.

Also, looks like this only happens on staging, but not on prod. On prod, there is no pusher updates to set the user preferred locale.

**Comment by yuwenmemon** [comment] 2024-03-13 18:33
Interesting @bernhardoj is that independent of your solution with syncing multiSet and multiMerge? Let's at least get that fix out there to tackle the first problem. Then we can move onto the next.

**Comment by bernhardoj** [comment] 2024-03-14 02:45
@yuwenmemon it's a different issue but since the OpenApp response is completely discarded, we can't see the effect of my fix.

**Comment by yuwenmemon** [comment] 2024-03-25 23:03
@bernhardoj Let's at least get your fix up and then we can create another follow up issue to take a look at the other problem.

**Comment by bernhardoj** [comment] 2024-03-26 11:51
@yuwenmemon I can avoid the other issue by using my other account. The onyx PR is up: https://github.com/Expensify/react-native-onyx/pull/521

cc: @Ollyws

**Comment by bernhardoj** [comment] 2024-03-28 06:17
So, the next step is to update the Onyx in App, but currently, the Onyx version pointing to a hotfix branch (hotfix-2.0.10)
https://github.com/Expensify/App/blob/e14ac0899097d4a014b3cf3b7f461d51fb177392/package.json#L148

and our fix is in Onyx 2.0.24, 14 versions apart.

How should we proceed?

**Comment by yuwenmemon** [comment] 2024-03-28 06:22
Hmmm... maybe we can ask in [#expensify-open-source](https://expensify.enterprise.slack.com/archives/C01GTK53T8Q)
?

**Comment by bernhardoj** [comment] 2024-03-28 07:36
Posted [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1711611386393649)

**Comment by bernhardoj** [comment] 2024-03-28 09:10
There is an App PR [here](https://github.com/Expensify/App/pull/38114) that bumps the Onyx version to 2.0.23, can we hold for that?

**Comment by yuwenmemon** [comment] 2024-04-05 23:36
Heads up I'll be OOO next week so if we need another engineer to merge anything for this feel free to ping in #expensify-open-source @Ollyws

**Comment by bernhardoj** [comment] 2024-04-06 13:49
https://github.com/Expensify/App/pull/38114 is merged, I have raised the PR to bump it to 2.0.24

cc: @Ollyws

**Comment by JmillsExpensify** [comment] 2024-05-19 17:57
Payment summary:

 - Contributor: @bernhardoj $500
 - Contributor+: @Ollyws $500

Separately, @Ollyws what are your thoughts on regression tests?

**Comment by JmillsExpensify** [comment] 2024-05-19 18:02
Offers sent out via Upwork.

**Comment by JmillsExpensify** [comment] 2024-05-20 17:11
Contributor contract paid.

**Comment by JmillsExpensify** [comment] 2024-06-01 16:45
@Ollyws Quick follow-up on [this question](https://github.com/Expensify/App/issues/37351#issuecomment-2119314271) when you get a chance.

**Comment by JmillsExpensify** [comment] 2024-06-04 05:37
Sounds good to me. I asked a colleague to confirm the payment summary before I approve payment.

**Comment by laurenreidexpensify** [comment] 2024-06-04 10:49
Payment summary:

Contributor: @bernhardoj $500 paid via upwork 
Contributor+: @Ollyws $500 paid via ND

**Closed** 2024-08-23 18:28 UTC
Labels: Reviewing, External, Engineering, Monthly, Bug
