### ISSUE TITLE
[$250] Distance - "Error loading messages" appears after dismissing invalid distance error

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42518] opened 2024-05-23 11:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.75-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

**Issue found when executing PR** https://github.com/Expensify/App/pull/41481
## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled request
3. Go offline
4. Submit a distance expense with invalid addresses
5. Go online
6. Click on the distance preview
7. Dismiss the error message
8. Click on the header subtitle to return to the main chat
9. Scroll down

## Expected Result:
There will be no "There was an error loading more messages." in the main chat

## Actual Result:
"There was an error loading more messages." error shows up in the main chat after dismissing the error

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1b49ecdf-a7d1-40ef-a05d-be02ebd93b22

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013c3c05166994ac09</li>
        <li>Upwork Job ID: 1795874267241521152</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @ishpaul777</details>

**Comment by lanitochka17** [comment] 2024-05-23 11:58
@JmillsExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-05-23 11:59
We think that this bug might be related to #wave-collect - Release 1

**Comment by JmillsExpensify** [comment] 2024-05-29 17:45
Opening up to the community since we have a proposal.

**Comment by goldenbear101** [comment] 2024-06-05 22:06
### **Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Error message "There was an error loading more messages" is visible even when there is no error in the chat flow (The error is in the MoneyRequestView).

**What is the root cause of that problem?**
I think there is a bug where the error message from the `MoneyRequestView` propagates to the chat view, causing the "Error loading messages" error to display after dismissing an invalid distance error.

**What changes do you think we should make in order to solve the problem?**
The suggested fix involves making sure that when the error modal in `MoneyRequestView` is dismissed, the state indicating an error in loading messages is reset.

The state `hasLoadingNewerReportActionsError` should be reset to false in Onyx when the error modal is dismissed in `MoneyRequestView`.

Steps to fix:
1, I will check how the state `hasLoadingNewerReportActionsError` is managed in `MoneyRequestView` and ChatView.
2, Modify `MoneyRequestView` to reset the error state by ensuring that dismissing the error modal triggers an update to reset `hasLoadingNewerReportActionsError` in Onyx.
3, Update the `MoneyRequestView` component, find where the error modal is dismissed and add code to reset the `hasLoadingNewerReportActionsError` state in Onyx.
4, Make sure the Onyx key `hasLoadingNewerReportActionsError` is correctly defined and can be updated from the `MoneyRequestView`.

Implementation:
1, Finding the dismiss error modal code in `MoneyRequestView`:

```
// Assuming the error modal dismissal is handled in a function like this:
dismissErrorModal() {
    this.setState({ showErrorModal: false });

    // Add code to reset the error state in Onyx
    Onyx.merge(ONYXKEYS.REPORT_HAS_LOADING_NEWER_REPORT_ACTIONS_ERROR, false);
}
```
2, Ensure Onyx Key is Defined:

Verify that ONYXKEYS.REPORT_HAS_LOADING_NEWER_REPORT_ACTIONS_ERROR is properly defined in your Onyx keys:

```
// ONYXKEYS.js
const ONYXKEYS = {
    ...
    REPORT_HAS_LOADING_NEWER_REPORT_ACTIONS_ERROR: 'hasLoadingNewerReportActionsError',
    ...
};
export default ONYXKEYS;
```
3, Handle State Reset in Onyx:

Make sure the state is properly updated in Onyx when merging:

`Onyx.merge(ONYXKEYS.REPORT_HAS_LOADING_NEWER_REPORT_ACTIONS_ERROR, false);
`
**What alternative solutions did you explore? (Optional)**

This approach is to make sure that the state indicating an error in loading messages is properly reset, to avoid the propagation of the error to the chat view.

**Comment by NJ-2020** [comment] 2024-06-10 11:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Error loading messages" appears after dismissing an invalid distance error

### What is the root cause of that problem?
The backend will show an error because of the invalid address so it won't create the report including the report ID in the backend, but we still keep the ONYX data so when we click the subheader link, we pass the parent report ID and thread report id (which doesn't exist because backend error) to getNewerActions function
https://github.com/Expensify/App/blob/66cd70716217b91c927d5267f7672b1d080ac17f/src/pages/home/report/ReportActionsView.tsx#L225

### What changes do you think we should make in order to solve the problem?
We can check if the report ID exists in the backend, or we can delete the ONYX data when the backend goes wrong on a specific case
### What alternative solutions did you explore? (Optional)

**Comment by NJ-2020** [comment] 2024-06-10 23:50
## Proposal
[Updated](https://github.com/Expensify/App/issues/42518#issuecomment-2158089167)

**Comment by allroundexperts** [comment] 2024-06-12 09:59
Jumping in today as promised on channel. It seems like that we need to fix this on the backend. Backend seems to be returning `hasLoadingNewerReportActionsError` as `true`.

**Comment by NJ-2020** [comment] 2024-06-12 10:25
I also think that the issue is in the backend.  So, does it mean that there is no point in fixing the frontend side as per my proposal?

**Comment by JmillsExpensify** [comment] 2024-06-19 05:14
Assigned!

**Comment by JmillsExpensify** [comment] 2024-06-26 03:59
Awaiting PR

**Comment by JmillsExpensify** [comment] 2024-07-03 05:04
Same

**Comment by JmillsExpensify** [comment] 2024-07-10 04:24
Looks like the same

**Comment by JmillsExpensify** [comment] 2024-07-16 23:21
@allroundexperts I'm sure you have a decent amount going on, and this isn't the highest priority. That said, any update on when you plan to make time for this one?

**Comment by allroundexperts** [comment] 2024-07-17 12:38
> @allroundexperts I'm sure you have a decent amount going on, and this isn't the highest priority. That said, any update on when you plan to make time for this one?

@JmillsExpensify This needs to be fixed from the backend. I'm not sure if I can be of any help with that.

**Comment by JmillsExpensify** [comment] 2024-08-14 11:38
Waiting on an internal fix.

**Comment by JmillsExpensify** [comment] 2024-08-28 12:41
Still waiting on internal

**Comment by trjExpensify** [comment] 2024-09-03 22:57
Ah, so @JmillsExpensify do you need a volunteer here or is someone on it? If so, let's make sure it goes in `Hot picks` to surface it.

**Comment by JmillsExpensify** [comment] 2024-09-11 14:26
Done! Added to hot picks.

**Comment by JmillsExpensify** [comment] 2024-09-25 17:19
Still in hot picks

**Comment by tgolen** [comment] 2024-09-30 20:50
I can work on this, but I need some help getting a little more crisp on just what the expected problem is on the backend. I see this:

> Backend seems to be returning hasLoadingNewerReportActionsError as true.

but `hasLoadingNewerReportActionsError` doesn't seem to come from the backend anywhere. I can find no reference to it. Should I be looking for something else? Are you sure this comes from the backend? Is it maybe inserted into Onyx as `true` due to this `failureData`? 

https://github.com/Expensify/App/blob/e8b7582bb68218358d5402e039def8f618899957/src/libs/actions/Report.ts#L1191

If it is, can you help me understand what needs to happen differently?

**Comment by trjExpensify** [comment] 2024-10-01 15:45
@allroundexperts can you get back to Tim on the above, please?

**Comment by allroundexperts** [comment] 2024-10-01 20:33
@tgolen I was assuming that it comes from the backend. If it does not (and you can confirm that), then [flipping the flag](https://github.com/Expensify/App/issues/42518#issuecomment-2131373176) as suggested by @jainilparikh  should work fine. I'll test this out and get back.

**Comment by trjExpensify** [comment] 2024-10-04 19:47
Okay cool, so what are our next steps here? Proceed with @jainilparikh's proposal?

**Comment by allroundexperts** [comment] 2024-10-07 07:02
@trjExpensify I just tested this again, and am unable to reproduce it. Can you please check as well?

**Comment by trjExpensify** [comment] 2024-10-07 10:29
Can do! It looks like we now actually delete the whole thing if it was created offline with invalid waypoints: 

https://github.com/user-attachments/assets/fd1a1d9a-b535-4ab7-a604-edee0a509434

Seems like it was fixed as part of this issue: https://github.com/Expensify/App/issues/42950#top

Closing!

**Closed by trjExpensify** 2024-10-07 10:29 UTC
Labels: Weekly, Internal, Bug
