### ISSUE TITLE
[HOLD for payment 2024-06-28] [HOLD for payment 2024-06-24] [$250] Android - Scan - Pay elsewhere greyed on submitting expense with currency other than local

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#41445] opened 2024-05-01 19:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4534392
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Workspace set in local currency and submission frequency set to manual
1. Launch app
2. Open Workspace chat
3. Create an expense with local currency
4. Tap submit and pay elsewhere
5. Note paid without any issue
6. Create an expense with currency other than local currency
7. Tap submit
8. Note pay elsewhere button greyed out
9. After tapping greyed out pay elsewhere button few times user able to pay

## Expected Result:
In workspace, expense created with currency other than local currency when submitted, greyed out pay elsewhere button must not be displayed

## Actual Result:
In workspace, expense created with currency other than local currency when submitted, greyed out pay elsewhere button displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/2b2fe875-9b30-4d93-a673-0cf5543f311f

https://github.com/Expensify/App/assets/78819774/ce0183d7-9121-49cd-a40f-e4ff3c847943

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0198922fe1d95a1791</li>
        <li>Upwork Job ID: 1786776812730265600</li>
        <li>Last Price Increase: 2024-06-01</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak / @Christinadobrzyn</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify / @Christinadobrzyn</details>

**Comment by lanitochka17** [comment] 2024-05-01 19:53
@bfitzexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by shreykul** [comment] 2024-05-05 18:42
**Please re-state the problem that we are trying to solve in this issue.**

In the workspace, expenses created with currency other than local currency when submitted, the pay elsewhere button is disabled while it should not be disabled as mentioned above.

**What is the root cause of that problem?**

There is a condition written in the code which checks if the local currency matches the selected currency and if they don't match then the SettlementButton is being shown as disabled.

**What changes do you think we should make to solve the problem?**

We can remove the condition from the code which can display the button as enabled even if the currency doesn't match.

**Comment by shreykul** [comment] 2024-05-05 18:45
Contributor details
Your Expensify account email: shreykulshrestha33@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d56d7360118cadc8

**Comment by shreykul** [comment] 2024-05-06 03:44
Hi @rayane-djouah , Please check if the proposal is okay now...?

**Comment by shreykul** [comment] 2024-05-11 18:10
@rayane-djouah Sorry, I didn't get the time to read the mentioned issue fully. I'll make sure to update you tomorrow about this issue clearly.

**Comment by shreykul** [comment] 2024-05-11 20:01
@rayane-djouah, I've gone through #35062, and it appears that when submitting expenses with currencies other than the local one, the "pay elsewhere" option is being greyed out. This occurs because the currency is first converted to the local currency before enabling the option. The button remains disabled until the converted currency is fetched through the backend.

A similar issue was encountered before, and the solution was to inform the user to wait while the currency is being converted, rather than simply showing the button as disabled. The currency condition cannot be removed because it affects payment calculations when the user is offline, as mentioned in #35062.

To address this, we can implement a toast notification to inform the user why the button is disabled.

**Comment by dubielzyk-expensify** [comment] 2024-05-12 23:29
After reading the thread and issue I feel like there's a few solutions to this. Ultimately we want the user to wait until the conversion is done and by putting it as disabled it looks like an action is not possible, which isn't the case, it's more that the user needs to wait until they can press the button. 

Here's the three solutions I've come up with (though I'm sure there's more):
1) Changing the label of the button while it's converting to `Converting...` or something similar
2) Replacing the button for a spinner while the conversion is done, then replacing it back to a button
3) Adding a new `loading state` in our button component that allows for a spinner inside the button while an action is performed (this might be handy for other things in the future too).

![CleanShot 2024-05-13 at 09 28 32@2x](https://github.com/Expensify/App/assets/145416827/aeae1499-020f-452c-aa47-1eb43b991029)

Keen to hear what @Expensify/design thinks here. I'm okay with all though `option 3` could be useful elsewhere. I've found that a loading state on buttons are handy on other areas of the app where a network request is happening or you tap a button waiting for something but instead of showing a separate loading state you can just change the button state. Open to other solutions too though.

**Comment by dubielzyk-expensify** [comment] 2024-05-13 05:02
Oh are we? Awesome find @rayane-djouah!

If so, then that's my vote, but let's hear from @shawnborton and @dannymcclain first.

**Comment by shawnborton** [comment] 2024-05-13 12:39
I can get down with that (third option above), that makes sense to me.

**Comment by dannymcclain** [comment] 2024-05-13 13:45
Yup I'm down for option 3 as well. And we definitely already have that pattern elsewhere in the app, so that's cool! You should be able to see it in Storybook (although Storybook isn't working for me anymore...)

**Comment by dubielzyk-expensify** [comment] 2024-05-13 23:22
> So, I think that when we click on the submit button offline it should become disabled, and when online it should shows a loading state, and when we get response from backend, we should display the Settlement button.

That seems right to me, but keen to hear what @Expensify/design and @trjExpensify thinks about this

**Comment by shreykul** [comment] 2024-05-16 16:39
@rayane-djouah please check if the proposal is ok and sorry for the late response.

**Comment by shreykul** [comment] 2024-05-17 15:46
@rayane-djouah I'm unable to log in to the app whenever I try to click on previous chats it just shows something went wrong.

**Comment by shreykul** [comment] 2024-05-17 23:21
@rayane-djouah, I tried doing that too but I'll check once again.

**Comment by bfitzexpensify** [comment] 2024-05-28 21:03
@shreykul any luck getting in?

**Comment by bfitzexpensify** [comment] 2024-05-30 17:03
Adding a second BZ team member to keep an eye on this while I'm OOO until June 11th. 

Current status: waiting on proposals. Since this is 4 weeks old, we might want to consider doubling this bounty.

**Comment by Christinadobrzyn** [comment] 2024-05-31 03:56
Asking SWM if they might be able to grab this - https://expensify.slack.com/archives/C04878MDF34/p1717127772013379

**Comment by kosmydel** [comment] 2024-06-03 13:49
The PR is ready for review cc @rayane-djouah

**Comment by Christinadobrzyn** [comment] 2024-06-05 07:48
Update for Melvbot - monitoring - https://github.com/Expensify/App/pull/42981

**Comment by Christinadobrzyn** [comment] 2024-06-06 06:41
Thanks for the heads up @rayane-djouah! I am going to assign another C+ to keep this PR moving!

**Comment by Christinadobrzyn** [comment] 2024-06-11 06:05
Gonna move this to weekly since the [PR](https://github.com/Expensify/App/pull/42981) is reviewing

**Comment by Christinadobrzyn** [comment] 2024-06-13 01:53
Just a heads up - I'm going to be ooo until June 24th. I'm not going to assign anyone new since @bfitzexpensify is on this!

**Comment by kosmydel** [comment] 2024-06-13 17:31
Hey, the PR has been approved by C+, but the internal hasn't been assigned.

**Comment by Beamanator** [comment] 2024-06-14 07:55
Hmm seems I didn't get assigned to this issue via "C+ approving a proposal" - so maybe that's why i didn't get assigned to review the PR 🤔  anyway, will do today!

**Comment by Christinadobrzyn** [comment] 2024-06-25 17:59
Payouts due:

- Contributor+: $250 @eVoloshchak (thorough NewDot)

@eVoloshchak let us know if you think a regression test is needed for this

**Comment by Christinadobrzyn** [comment] 2024-06-28 20:15
This is ready for NewDot payment based on this payment summary - https://github.com/Expensify/App/issues/41445#issuecomment-2197411374

@eVoloshchak let me know about a regression test!

**Comment by eVoloshchak** [comment] 2024-07-02 17:33
- The PR that introduced the bug has been identified. Link to the PR: N/A, the behavior wasn't implemented initially
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: additional discussion isn't needed, the bug is very minor

**Regression Test Proposal**

1. Go to workspace, press + next to the Composer and "Track expense".
2. Change the currency to a different one than the default one.
3. Typ in an amount and press "Next" -> "Track expense".
4. Veirfy that the settlement button that a loading spinner is shown.
5. Go offline and repeat step 3.
6. Verify that the settlement button is disabled.
7. Go online again and repeat step 3.

**Do we agree 👍 or 👎**

**Comment by Christinadobrzyn** [comment] 2024-07-02 17:39
Thanks @eVoloshchak! Regression test is here - https://github.com/Expensify/Expensify/issues/409726

NewDot payment summary here - https://github.com/Expensify/App/issues/41445#issuecomment-2197411374

Closing as complete!

**Closed by Christinadobrzyn** 2024-07-02 17:39 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-02 18:35
$250 approved for @eVoloshchak based on summary above.
