### ISSUE TITLE
Track tax - Track tax switch does not appear grayed out when enabled/disabled offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43318] opened 2024-06-07 19:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80-14
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Distance rates and Taxes are enabled
1. Go to staging.new.expensify.com
2. Go to workspace settings > Distance rates
3. Go offline
4. Click Settings
5. Enable or disable Track tax switch

## Expected Result:
Track tax switch will appear grayed out when enabled/disabled offline

## Actual Result:
Track tax switch does not appear grayed out when enabled/disabled offline

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a29950f8-f741-4b95-99e4-6915360a2d2b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-06-07 19:46
@srikarparsi  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-07 19:46
We think that this bug might be related to #vip-vsp

**Comment by srikarparsi** [comment] 2024-06-07 19:48
I believe this is related to this [feature](https://github.com/Expensify/App/pull/42141)

**Comment by srikarparsi** [comment] 2024-06-07 19:59
@nkdengineer @eVoloshchak are you available to take a look at this?

**Comment by luacmartins** [comment] 2024-06-07 20:18
I think we can demote this to NAB and let the contributors work on a fix.

**Comment by b4s36t4** [comment] 2024-06-07 20:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Track tax - Track tax switch does not appear grayed out when enabled/disabled offline
### What is the root cause of that problem?

We're not using any styles for the offline state in the `Track Tax` setting page like we do at the same palces.

### What changes do you think we should make in order to solve the problem?

We just need to provide the offline state of the `OfflineFeedback` component here https://github.com/Expensify/App/blob/d22eacf4ec925a79337ab469c41ac5db638ed5f8/src/pages/workspace/distanceRates/PolicyDistanceRatesSettingsPage.tsx#L125 in this line

```js
<OfflineWithFeedback errorRowStyles={styles.mh5} pendingAction={isPendingAction}>
```

We track `isPendingAction` with `useMemo` like as follows

```jsx
  const isPendingAction = useMemo(() => {
        if(!policy){
            return null
        }
        return policy.pendingFields?.["customUnits"]
    },[policy])
```

Which tracks the `pendingFeilds` state from the onyx which updates according to the Offline UX.



### What alternative solutions did you explore? (Optional)
NA

**Comment by srikarparsi** [comment] 2024-06-10 08:23
Let's wait on @nkdengineer @eVoloshchak since they were the [PR](https://github.com/Expensify/App/pull/42141) authors.

**Comment by nkdengineer** [comment] 2024-06-10 09:36
@eVoloshchak please check this [PR](https://github.com/Expensify/App/pull/43347)

**Comment by Pujan92** [comment] 2024-06-10 13:44
@srikarparsi I got assigned to the [PR](https://github.com/Expensify/App/pull/43347), Can you plz request review from @eVoloshchak and remove me. Or let me know if I need to review that.

**Comment by srikarparsi** [comment] 2024-06-10 17:21
Yes, thank you for letting me know

**Comment by srikarparsi** [comment] 2024-09-10 19:48
Thought we might need to still pay for this issue but it looks like this was a regression caused by this [PR](https://github.com/Expensify/App/pull/42141). Since the authors are the same for the original PR and this [fix](https://github.com/Expensify/App/pull/43347), I don't think there's anything left to do for this issue so closing out. But please let me know if I need to re-open @nkdengineer @eVoloshchak

**Closed by srikarparsi** 2024-09-10 19:48 UTC
Labels: Reviewing, Engineering, Daily, Bug
