### ISSUE TITLE
[$250] mWeb  - Profile - The selected timezone is not displayed when revisiting the page after sending a message.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43728] opened 2024-06-13 20:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap profile icon -- profile-- timezone
3. Toggle off automatic determine your location
4. Select Europe/London
5. Navigate to LHN
6. Open a report
7. Send a message
8. Navigate to LHN
9. Tap profile icon -  profile - timezone

## Expected Result:
The selected timezone should be displayed when revisiting the page after sending a message.

## Actual Result:
The selected timezone is not displayed when revisiting the page after sending a message.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/be29bde5-fef5-44ef-830b-dcbb21dd2fea

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0124f99fd8ba1319b0</li>
        <li>Upwork Job ID: 1802877137212918706</li>
        <li>Last Price Increase: 2024-06-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @aimane-chnaif</details>

**Comment by kbecciv** [comment] 2024-06-13 20:08
We think that this bug might be related to #vip-vsb

**Comment by kbecciv** [comment] 2024-06-13 20:08
@johncschuster FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by robertoyoc** [comment] 2024-06-20 17:45
## Proposal

Fix logic updating timezone when a comment is added

### Please re-state the problem that we are trying to solve in this issue.
When adding a comment after disabling automatic timezone selection the timezone is incorrectly being updated to automatic timezone.

### What is the root cause of that problem?
Comments in code indicate that we want to update the timezone if user has automatic timezone selected and it has passed more than 5 minutes since the last comment to update the timezone but that validation is being applying to both, with automatic timezone and without automatic timezone, causing the issue.
https://github.com/Expensify/App/blob/ff1ccf6de0289fcb02263d672ec3f300f795a9f4/src/libs/actions/Report.ts#L588-L598

### What changes do you think we should make in order to solve the problem?
Fix the logic to validate if the user has selected automatic timezone, also store the time that the user added last comment and use it to compare the 5 minute logic for timezone update.

### What alternative solutions did you explore? (Optional)

We can also remove this logic and validate timezone selection onPageLoad instead of checking every time a user adds a new comment. Most applications don't notice the timezone has changed until they reload and I think is a valid approach of solving this.

**Comment by robertoyoc** [comment] 2024-06-20 17:46
@aimane-chnaif Added proposal above if you can review, thanks 👍

**Comment by robertoyoc** [comment] 2024-06-20 23:15
@aimane-chnaif you are right, had a little bit problems understanding the issue but I've noticed the problem is in the Backend.

When calling https://dev.new.expensify.com:8082/api/AddComment?
with:
![CleanShot 2024-06-20 at 17 13 09@2x](https://github.com/Expensify/App/assets/16704638/0a62b4a2-5a51-4937-b13e-cb9d58aec0b0)

The response has an onyx merge update with `personalDetailsList` key and automatic timezone as you can see in the screenshot above.

![CleanShot 2024-06-20 at 17 14 42@2x](https://github.com/Expensify/App/assets/16704638/e1fdd452-f727-4e51-9c6c-5e9ed3a8160f)

The app is just applying what the BE is returning. 
Assume nothing to do on FE side here.

**Comment by Gajendra-Gupta** [comment] 2024-06-21 11:53
Contributor details
Your Expensify account email: [gajendra.gupta.indore@gmail.com](mailto:gajendra.gupta.indore@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 11:54
Contributor details
Your Expensify account email: [gajendra.gupta.indore@gmail.com](mailto:gajendra.gupta.indore@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 12:01
Contributor details
Your Expensify account email: [gajendra.gupta.indore@gmail.com](mailto:gajendra.gupta.indore@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 12:17
Contributor details
Your Expensify account email: [gajendra.gupta.indore@gmail.com](mailto:gajendra.gupta.indore@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 12:18
Contributor details
Your Expensify account email: [gajendra.gupta.indore@gmail.com](mailto:gajendra.gupta.indore@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 12:25
Contributor details
Your Expensify account email: gajendra.gupta.indore@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/gajendrag

**Comment by Gajendra-Gupta** [comment] 2024-06-21 12:42
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**
Profile - The selected timezone is not displayed when revisiting the page after sending a message.

**What is the root cause of that problem?**
https://dev.new.expensify.com:8082/api/AddComment
After toggle time zone disable my time zone is {automatic: false, selected: "Asia/Kolkata"} but always getting 
wrong timezone 
timezone: {automatic: true, selected: "America/Los_Angeles"} 
in  
key: "personalDetailsList"
 after sending message to other by addComment API.
**What changes do you think we should make in order to solve the problem?**
 AddComment API should return correct time zone.

**What alternative solutions did you explore? (Optional)**

**Comment by Gajendra-Gupta** [comment] 2024-06-21 13:52
@aimane-chnaif  Added proposal above if you can review, thanks

**Comment by sonialiap** [comment] 2024-06-24 14:49
Is this a dupe of https://github.com/Expensify/App/issues/43032?

**Comment by iwiznia** [comment] 2024-06-24 14:51
It certainly does. Closing in favor of https://github.com/Expensify/App/issues/43032

**Closed by iwiznia** 2024-06-24 14:51 UTC
Labels: External, Daily, Help Wanted, Bug
