### ISSUE TITLE
[WAITING ON #40059][$250] Conversation - Deleted message reappears when reopening the conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39521] opened 2024-04-03 16:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website.
2. Tap on the chat icon.
3. Open any conversation.
4. Long press on any sent message.
5. Tap on "Delete Comment"
6. Tap on "Delete"
7. Tap on the arrow on the top left corner.
8. Tap on the same conversation again.
9. Check if the deleted message is still displayed or was succesfully deleted

## Expected Result:
Deleted message shouldn´t reappear after closing and reopening the conversation

## Actual Result:
Deleted message reappears on the chat after closing it and reopening it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/db29eeac-dd1a-4553-a22f-9d636cd2b7c8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011225f8750b0176de</li>
        <li>Upwork Job ID: 1777801993580064768</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by shahinyan11** [comment] 2024-04-03 17:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Conversation - Deleted message reappears when reopening the conversation
### What is the root cause of that problem?
[Here](https://github.com/Expensify/App/blob/7cdb17b44294707c30d394afe7099c4ed84b8381/src/libs/actions/Report.ts#L1259C17-L1264C160) remove `DeleteComment` from `persistedRequests` and prevent sending request to the server
### What changes do you think we should make in order to solve the problem?
Remove `WRITE_COMMANDS.DELETE_COMMENT` from [this](https://github.com/Expensify/App/blob/7cdb17b44294707c30d394afe7099c4ed84b8381/src/libs/actions/Report.ts#L1262C28-L1262C147) array 
### What alternative solutions did you explore? (Optional)

**Comment by Nghondzweni** [comment] 2024-04-10 09:58
Contributor details
Your Expensify account email: trnghondzweni@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01d6ad2a62c32371cb

**Comment by nkdengineer** [comment] 2024-04-10 10:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleted message reappears on the chat after closing it and reopening it

### What is the root cause of that problem?
In [here](https://github.com/Expensify/App/blob/0995d40b43d91749260a1d490dfebc5433f3e0fb/src/libs/actions/Report.ts#L1245), we always include the current command in the list of conflicting commands, if the report action is not a parent report action.

The intention here was that if the report action is an optimistic one, and we delete the report action, it will clear all the commands related to that report action. The "optimistic" report action was never created so we don't have to create the report action, neither do we need to delete that report action. All we need to do in that case is to clear all the commands (listed [here](https://github.com/Expensify/App/blob/0995d40b43d91749260a1d490dfebc5433f3e0fb/src/libs/actions/Report.ts#L1240)) and also clear the report action in Onyx.

But the problem here is that the report action in our case is not optimistic, it's an already-created report action. We're still omitting the DELETE_COMMENT command for this report action, leading to it not being deleted.

### What changes do you think we should make in order to solve the problem?

We can update [this](https://github.com/Expensify/App/blob/0995d40b43d91749260a1d490dfebc5433f3e0fb/src/libs/actions/Report.ts#L1245) to
```
shouldIncludeCurrentRequest: !isDeletedParentAction && reportAction.isOptimisticAction,
```
So it will not include the current delete command in the "conflicting commands" list if the report action is not optimistic.

### What alternative solutions did you explore? (Optional)
NA

**Comment by johncschuster** [comment] 2024-04-12 20:56
@ishpaul777 can you review the above proposals?

**Comment by johncschuster** [comment] 2024-04-16 20:56
Thanks for the update, @ishpaul777! @MelvinBot, this isn't overdue. We're waiting on #40059 to get merged.

**Comment by mvtglobally** [comment] 2024-04-18 15:56
Issue not reproducible during KI retests. (First week)

**Comment by johncschuster** [comment] 2024-04-26 22:26
Sorry I missed this, @ishpaul777! I'll ask for a retest on this.

**Comment by mvtglobally** [comment] 2024-05-01 14:01
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-05-06 19:52
Issue not reproducible during KI retests. (Third week) Good to close?

**Closed** 2024-05-09 21:07 UTC
Labels: External, Daily, Help Wanted, Bug, retest-weekly
