### ISSUE TITLE
[HOLD for payment 2023-07-24] [$1000] When paying an IOU with a gold wallet, the paid message says undefined

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21535] opened 2023-06-25 17:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Request IOU
2. Pay with Gold wallet

## Expected Result:
`Paid $xx.xx` message should appear
## Actual Result:
When paying an IOU with a gold wallet, the paid message says undefined while being queued for sending, but then the undefined messages goes away after it sends to the server and gets confirmation.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction (requires gold wallet)
**Reproducible in production?:** needs reprouduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (3)](https://github.com/Expensify/App/assets/43996225/a733994d-aa72-4ce9-bcca-4ad37a9eff38)
![image (2)](https://github.com/Expensify/App/assets/43996225/4b60bcb2-3737-4eb8-a226-82b1e34b4782)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687306420746519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d73e757c9e96d8c0</li>
        <li>Upwork Job ID: 1673808192147783680</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by jliexpensify** [comment] 2023-06-25 21:51
I can't repro this as a Gold Wallet requires a SSN ([reference here](https://stackoverflowteams.com/c/expensify/questions/10305)). Going to reassign to someone in the USA.

**Comment by jliexpensify** [comment] 2023-06-25 21:53
Sorry for all the reassigns! @puneetlath it looks like you need a SSN for a Gold Wallet ([comment](https://github.com/Expensify/App/issues/21535#issuecomment-1606273691)) so I was reassigning to someone in the USA to replicate.

**Comment by jjcoffee** [comment] 2023-06-27 12:46
It is also possible to replicate this without having wallet access with a little hack to force the `paymentMethodType` in the `optimisticData` to `CONST.IOU.PAYMENT_TYPE.EXPENSIFY`.

https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/libs/actions/IOU.js#L1105

https://github.com/Expensify/App/assets/27287420/cb7c2958-69d4-4161-bdf2-c19c209184d7

**Comment by jjcoffee** [comment] 2023-06-27 12:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Paying with Gold wallet shouldn't result in an "undefined" message.

### What is the root cause of that problem?
We are generating the message to display after making a payment here:

https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/libs/ReportUtils.js#L1346-L1347

The `paymentMethodMessage` we're using there comes from here:

https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/libs/ReportUtils.js#L1321-L1333

Note that the `paymentMethodMessage` is not defined for any other `PAYMENT_TYPE` and the default case does nothing.

### What changes do you think we should make in order to solve the problem?
Since we're always outputting the `paymentMethodMessage` in the IOU message, we need to initialise it as an empty string, so that for any payment methods cases not handled, we just won't display anything. So update to: `let paymentMethodMessage = '';`.

Optionally, we can also add another message for the `EXPENSIFY` `PAYMENT_TYPE`, e.g.:

```
case CONST.IOU.PAYMENT_TYPE.EXPENSIFY:
	paymentMethodMessage = ' using Expensify Wallet';
	break;
```

**Comment by puneetlath** [comment] 2023-06-27 21:40
Hm, yes it seems like we should have a case for each of the [payment types](https://github.com/Expensify/App/blob/f955e4e010192810c78b44703751f907165e342d/src/CONST.js#L1029-L1033). Also, should we be translating these messages?

**Comment by jjcoffee** [comment] 2023-06-30 09:33
Updated [proposal](https://github.com/Expensify/App/issues/21535#issuecomment-1609433896) to make it a bit more generic, so that we don't have to add a new case every time a payment method is added.

It looks like a lot of these IOU messages are not currently being translated, I've asked [on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1688116075418599) about it.

**Comment by jjcoffee** [comment] 2023-06-30 10:16
Regarding translations, if we optimistically set the translation it would just get replaced by English-language strings from the BE. Within the IOU report this "paid $xx using..." string is just a normal text message, so I don't think we can apply a translation in the same way as we now do in the `ReportPreview` component (via `getReportPreviewMessage`). So I think it's not worth doing until BE returns translated strings.

**Comment by puneetlath** [comment] 2023-06-30 14:57
Got it! That makes sense.

**Comment by puneetlath** [comment] 2023-07-03 17:45
@rushatgabhane thoughts on the proposal?

**Comment by puneetlath** [comment] 2023-07-05 15:47
@rushatgabhane bump on the proposal review.

**Comment by puneetlath** [comment] 2023-07-07 18:36
@rushatgabhane can you provide an ETA on when you'll be able to review the proposal?

**Comment by Julesssss** [comment] 2023-07-10 11:17
Hey @puneetlath, I assume you were assigned as for the non-engineer role?

**Comment by jjcoffee** [comment] 2023-07-10 12:10
PR coming today!

**Comment by puneetlath** [comment] 2023-07-11 18:24
@rushatgabhane bump! Have you had a chance to review?

**Comment by mountiny** [comment] 2023-07-17 17:08
@puneetlath @Julesssss @rushatgabhane @jjcoffee Want to raise that this PR was not implemented exactly as we would wish, when paying expense report, the payment type is `ACH` but we would like the message to say `using Expensify`. 

Normally this would be regression to decrease the price but this is behind the policyExpenseChat beta so I think its fair to say you could not easily catch this, but still noting.

**Comment by puneetlath** [comment] 2023-07-24 15:33
>@puneetlath @Julesssss @rushatgabhane @jjcoffee Want to raise that this PR was not implemented exactly as we would wish, when paying expense report, the payment type is ACH but we would like the message to say using Expensify.

>Normally this would be regression to decrease the price but this is behind the policyExpenseChat beta so I think its fair to say you could not easily catch this, but still noting.

Ah interesting, thanks for letting us know. Is there a way we could have known this? Or something we could do differently to make it possible to know? Perhaps a question for @rushatgabhane as he does the checklist. 

Which by the way, @rushatgabhane friendly reminder on the checklist 😄. 

Paid @jjcoffee $1500.

**Comment by rushatgabhane** [comment] 2023-08-02 07:55
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2023-08-02 09:08
Manual request on new dot https://staging.new.expensify.com/r/5683927164360461

**Comment by puneetlath** [comment] 2023-08-03 22:32
Payment summary: 

- Issue reporter: n/a
- Contributor: @jjcoffee $1500 (paid via Upwork)
- C+: @rushatgabhane $1500 (due via NewDot)

@JmillsExpensify assigning you to handle C+ payment.

**Comment by JmillsExpensify** [comment] 2023-08-04 04:11
Reviewed details for @rushatgabhane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by puneetlath** [comment] 2023-08-08 22:25
All done here!

**Closed by puneetlath** 2023-08-08 22:25 UTC
Labels: External, Weekly, Awaiting Payment, Bug
