### ISSUE TITLE
[HOLD for payment 2024-01-18] LHN - Tooltip Appears After FAB Opens and Displays the List When Hovering Over the FAB Icon

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34183] opened 2024-01-09 20:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.23-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1, Sign in to the staging environment of Expensify
2, Click on the Floating Action Button (FAB)
3, Hover over the FAB again; the tooltip continues to be displayed

## Expected Result:
The tooltip should not appear after the modal opens

## Actual Result:
Even after the modal opens, the tooltip persists when hovering over the FAB

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/63013550-531f-479d-8a16-76aa0e2c58fe

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2024-01-09 20:37
This is a regression of this PR https://github.com/Expensify/App/pull/33247

**Comment by s-alves10** [comment] 2024-01-09 20:40
Both https://github.com/Expensify/App/issues/34185 and this issue are related to the TS migration PR https://github.com/Expensify/App/pull/33247

**Comment by roryabraham** [comment] 2024-01-09 21:47
[Fix](https://github.com/Expensify/App/pull/34188) is being CP'd to staging, cheers to @situchan for the quick fix

**Comment by roryabraham** [comment] 2024-01-19 17:37
Whoops, looks like we just need to issue payment to @situchan for the PR (no C+)

**Comment by roryabraham** [comment] 2024-01-19 17:39
Damn, the Upwork job isn't getting auto-created. @adelekennedy can you please issue payment of $500 to @situchan then close this out?

**Comment by adelekennedy** [comment] 2024-01-19 17:55
Upwork is having some trouble but I think I was able to extend you a contract @situchan

**Comment by adelekennedy** [comment] 2024-01-19 19:08
payment made!

**Closed by adelekennedy** 2024-01-19 19:08 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
