### ISSUE TITLE
Hybrid - Android - Copilot - User logged as copilot is able to switch to Expensify Classic.

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#53812] opened 2024-12-10 08:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.73-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Yes, reproducible on both
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52103
**Email or phone of affected tester (no customers):** ibellicotest+83@gmail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the Expensify app.
2. Log in with an account that is a Copilot.
3. Tap on "Settings"
4. Scroll down and tap on "Switch to Expensify Classic"
5. Verify that a "Not so fast" message is displayed and that you are not able to switch to Expensify Classic.

## Expected Result:
User logged as a copilot, shouldn´t be able to switch to Expensify Classic.

## Actual Result:
User logged as a copilot is able to switch to Expensify Classic and the "Not so fast" message is not displayed.

## Workaround:
Unknown

## Platforms:
- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/47e7f9aa-b211-4eba-9072-26d88d53ad49

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by c3024** [comment] 2024-12-10 09:19
I wonder why it is failing on standalone app. This should not fail on standalone app, unless standalone app too [returns](url) `true` for `NativeModules.HybridAppModule`?

**Comment by ChavdaSachin** [comment] 2024-12-10 11:06
I checked android-standalone, but it is working as expected.
My guess is that tester might have marked standalone by mistake.

**Comment by IuliiaHerets** [comment] 2024-12-10 13:33
@ChavdaSachin I asked the tester to recheck. I'll be back soon with an answer

**Comment by IuliiaHerets** [comment] 2024-12-10 14:47
@ChavdaSachin Yes, you are right. Issue happens only on the hybrid app. Sorry for confusing

**Comment by sonialiap** [comment] 2024-12-12 11:32
posted in [slack](https://expensify.slack.com/archives/C07NMDKEFMH/p1734003102699799) for an internal engineer

**Comment by Julesssss** [comment] 2024-12-12 14:37
It should be a simple HybridApp change, but sorry, I can't commit to this. Ignore my brief assignment

**Comment by sonialiap** [comment] 2024-12-12 16:23
In a [slack discussion](https://expensify.slack.com/archives/C07NMDKEFMH/p1734003102699799) it was agreed that we're ultimately moving towards allowing Copilot to take all actions so this is maybe not yet expected, but not a bug that we need to fix. Since it's not necessary to fix, closing

**Closed by sonialiap** 2024-12-12 16:23 UTC
Labels: Daily, Internal, Bug, Hot Pick

**Comment by Julesssss** [comment] 2024-12-16 10:09
Agree this isn't necessary.
