### ISSUE TITLE
[$250] Quick action doesn't work for split bill

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#48162] opened 2024-08-28 11:09 UTC
I'm unable to use the quick action to split another scanned receipt within a group.I also can't appear to create a second split from within the group chat... did we remove this feature accidentally or on purpose? I can't reproduce on web
___

**Version Number:** `9.0.25-10`
**Reproducible in staging?:** yes
**Reproducible in production?:** not sure, I can't install the prod app as I am on beta channel
**Logs:** see below
**Slack conversation:**

## Action Performed:

- Scan a receipt and split with two other users successfully
- Press '+'' button. then 'Split receipt' quick action  

## Expected Result:
- I should land at the Create expense (scan receipt) page/tab

## Actual Result:
I see 'Hmm... it's not here'

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

![Screenshot_20240828-115529](https://github.com/user-attachments/assets/0abbea23-2aab-4336-b882-69e653867783)
![Screenshot_20240828-115547](https://github.com/user-attachments/assets/a63bd959-d011-4146-9e43-987f9ff6060d)
![Screenshot_20240828-115553](https://github.com/user-attachments/assets/7465be79-2ae2-4fcd-9680-fc00eef039ac)

**Logs:**

[logs-2024-08-28 10_56_53.650.txt](https://github.com/user-attachments/files/16782416/logs-2024-08-28.10_56_53.650.txt)
[onyx-state.txt](https://github.com/user-attachments/files/16782417/onyx-state.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d9662abcf3d7aa85</li>
        <li>Upwork Job ID: 1828751766139835493</li>
        <li>Last Price Increase: 2024-08-28</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by bikramiter** [comment] 2024-08-28 13:02
I couldn't reproduce this on Android Native emulator.

**Comment by joekaufmanexpensify** [comment] 2024-08-28 14:59
I also can't reproduce on a later version than Jules (`9.0.25-11`). 

https://github.com/user-attachments/assets/ca997525-1fbe-4813-a35b-0db531189e2e

**Comment by joekaufmanexpensify** [comment] 2024-08-28 15:00
@Julesssss are you still able to consistently reproduce this? Seems to be working fine for me.

**Comment by joekaufmanexpensify** [comment] 2024-08-29 13:14
Pending input from @Julesssss

**Comment by Julesssss** [comment] 2024-08-29 13:48
Yeah, I can still reproduce. It is perhaps due to some unique configuration in my account. I'll keep the issue open but reduce the priority for now.

**Comment by joekaufmanexpensify** [comment] 2024-08-29 13:59
Got it, sounds good!

**Comment by joekaufmanexpensify** [comment] 2024-09-09 13:26
Same

**Comment by trjExpensify** [comment] 2024-09-10 01:17
The `Split expense` quick action flow isn't a focus of #wave-collect, so I'm moving it to #vip-split.

**Comment by Julesssss** [comment] 2024-09-12 08:18
Not able to reproduce currently. Perhaps we ask QA for a retest and then close?

**Comment by joekaufmanexpensify** [comment] 2024-09-12 21:36
Just tested again on Android, and not reproducible for me still! Closing.

**Closed by joekaufmanexpensify** 2024-09-12 21:36 UTC
Labels: Engineering, Weekly, Bug, retest-weekly
