### ISSUE TITLE
[$8000] Enabling #focus mode on desktop and then open up mobile app weird chats are showing

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14256] opened 2023-01-12 22:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Enable #focus mode on desktop 
2. Open the mobile app iOS
3. Some random chat is showing without any chat history
4. There is a chat with Chronos and click on it

## Expected Result:
Chat opens clicking on "Chronos" and no random chat is showing

## Actual Result:
 leads  to the “Uh-oh, something went wrong” page

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] iOS / native
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction
**Reproducible in production?:** Needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

<img src="https://user-images.githubusercontent.com/43996225/212197252-30401405-095d-41e8-a0c5-13f92015c95d.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/212197754-f3029a65-67a4-46af-bd4a-275a24a183e9.png" width="40%" height="40%">

<img src="https://user-images.githubusercontent.com/43996225/212197756-dca497aa-31ee-46eb-850f-20fb9d5f16d1.png" width="40%" height="40%">

**Expensify/Expensify Issue URL:**

**Issue reported by:** @shawnborton 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1673514891748389

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01be9d2b0cf76a0afe</li>
        <li>Upwork Job ID: 1614997927246245888</li>
        <li>Last Price Increase: 2023-02-06</li>
    </ul>
</details>

**Comment by shawnborton** [comment] 2023-01-13 09:06
@kavimuru can you also create a separate issue and tag @marcaaron regarding the Expensify logo appearing too close to the bottom of the page? Thanks!

**Comment by CortneyOfstad** [comment] 2023-01-16 14:47
I'm having trouble recreating this, so getting #engineering eyes on this.

**Comment by JmillsExpensify** [comment] 2023-01-18 03:38
Did you get to the bottom of this? It's happening to a couple of people. Also mind linking the #engineering-chat thread?

**Comment by CortneyOfstad** [comment] 2023-01-18 14:01
Didn't realize the External label didn't get some assignees on this 🤦 Will attempt again right now and see if I can get it to happen on my side and get the External label re-applied!

**Comment by CortneyOfstad** [comment] 2023-01-18 14:03
Had to quit and re-start my app on my phone to recreate (finally). Getting eyes on this ASAP.

**Comment by JmillsExpensify** [comment] 2023-01-18 16:43
Great, thanks for keeping this one moving.

**Comment by stitesExpensify** [comment] 2023-01-20 22:56
Not overdue, this is open to contributors

**Comment by s77rt** [comment] 2023-01-21 17:06
I can't reproduce. I don't see any Chronos chat. I think don't have that enabled at all even though I overwrote the `canUseChronos` permission. Asking on slack to get more info...

**Comment by stitesExpensify** [comment] 2023-01-23 16:48
I don't think this is related directly to Chronos, that is just and example of a chat that was pinned

**Comment by stitesExpensify** [comment] 2023-01-23 17:11
I understand that, but to my knowledge the chronos chat is no different than any other chat. The reproduction instructions could say "There is a chat with Brandon and click on it" and it would be the same thing.

**Comment by eh2077** [comment] 2023-02-07 14:18
**Proposal**



**RCA** 

Currently, when translating html `h1` tag to markdown, we simply wrap it with a leading and a trailing line break. If we send a single line header `# heading` message and edit it, the markdown text will display in 3 lines. If we edit the heading text and save it, the leading line break of markdown will be translated into an extra html  `<br />`. That's why we see an extra top line break after saving the edited heading.

**Solution**

To fix this issue, I think we should only add necessary leading or trailing line break when we translate `h1` to markdown. We only need to add line break if there's no-empty content before or after the heading. We can improve the regex expression to translate html `h1` to markdown. From 

https://github.com/Expensify/expensify-common/blob/668be7533215fc8d683d658da839361664320965/lib/ExpensiMark.js#L232-L233

to

```javascript
regex: /([\s\S]*?)\s*<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\2>(?![^<]*(<\/pre>|<\/code>))\s*([\s\S]*)/gi,
replacement: (match, g1, g2, g3, g4, g5) => `${g1}${g1 && '\n'}# ${g3}${g5 && '\n'}${g5}`,
```

**Comment by shawnborton** [comment] 2023-02-07 14:25
Yeah, part of me thinks we can just close this out and see if it comes back again. I just did a quick test and I can't reproduce, so I will close out for now.

**Closed by shawnborton** 2023-02-07 14:25 UTC
Labels: External, Weekly, Improvement, Help Wanted, Bug

**Comment by JmillsExpensify** [comment] 2023-02-07 17:06
Cool, thanks!

**Comment by eh2077** [comment] 2023-02-08 03:01
**Proposal**



**RCA** 

Currently, when translating html `h1` tag to markdown, we simply wrap it with a leading and a trailing line break. If we send a single line header `# heading` message and edit it, the markdown text will display in 3 lines. If we edit the heading text and save it, the leading line break of markdown will be translated into an extra html  `<br />`. That's why we see an extra top line break after saving the edited heading.

**Solution**

To fix this issue, I think we should only add necessary leading or trailing line break when we translate `h1` to markdown. We only need to add line break if there's no-empty content before or after the heading. We can improve the regex expression to translate html `h1` to markdown. From 

https://github.com/Expensify/expensify-common/blob/668be7533215fc8d683d658da839361664320965/lib/ExpensiMark.js#L232-L233

to

```javascript
regex: /([\s\S]*?)\s*<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\2>(?![^<]*(<\/pre>|<\/code>))\s*([\s\S]*)/gi,
replacement: (match, g1, g2, g3, g4, g5) => `${g1}${g1 && '\n'}# ${g3}${g5 && '\n'}${g5}`,
```

**Comment by eh2077** [comment] 2023-02-08 03:02
**Proposal**



**RCA** 

Currently, when translating html `h1` tag to markdown, we simply wrap it with a leading and a trailing line break. If we send a single line header `# heading` message and edit it, the markdown text will display in 3 lines. If we edit the heading text and save it, the leading line break of markdown will be translated into an extra html  `<br />`. That's why we see an extra top line break after saving the edited heading.

**Solution**

To fix this issue, I think we should only add necessary leading or trailing line break when we translate `h1` to markdown. We only need to add line break if there's no-empty content before or after the heading. We can improve the regex expression to translate html `h1` to markdown. From 

https://github.com/Expensify/expensify-common/blob/668be7533215fc8d683d658da839361664320965/lib/ExpensiMark.js#L232-L233

to

```javascript
regex: /([\s\S]*?)\s*<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\2>(?![^<]*(<\/pre>|<\/code>))\s*([\s\S]*)/gi,
replacement: (match, g1, g2, g3, g4, g5) => `${g1}${g1 && '\n'}# ${g3}${g5 && '\n'}${g5}`,
```
