### ISSUE TITLE
[$250] Comment not deleted when delete button in red and hit enter key

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#42645] opened 2024-05-27 15:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.76-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia  
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1716823498553919

## Action Performed:
1. Go to staging.new.expensify.com and login
2. Send a message to anyone
3. Edit the message by right clicking
4. Delete the message and press "Enter"
5. Press "Enter" again
## Expected Result:
Message/comment deleted
## Actual Result:
Message/comment is not deleted because the focus is on the `cancel` button (even though delete is in red)
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

https://github.com/Expensify/App/assets/38435837/ab09a4e9-a12d-4d66-943b-4e1affbb40c7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b70ac798adfe8d66</li>
        <li>Upwork Job ID: 1795470513005948928</li>
        <li>Last Price Increase: 2024-05-28</li>
<li>Automatic offers: </li>
<ul>
<li>bernhardoj | Contributor | 102543808</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sobitneupane</details>

**Comment by bernhardoj** [comment] 2024-05-28 07:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing the Enter key when opening the delete confirmation modal doesn't delete the comment/message.

### What is the root cause of that problem?
When the delete confirmation modal is shown, the focus trap from the rn-web Modal focuses on the Cancel button, so pressing Enter will press the Cancel button. We set `pressOnEnter` shortcut to the Delete button, but it will be disabled if the current focus is focused on an element with an accessibility role, except text.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/components/Button/index.tsx#L131

Now, the question is why the cancel button is focused first when we open the confirmation modal. In the confirmation modal, there are 3 focusable elements, the overlay, delete button, and cancel button. The logic of the focus trap is [here](https://github.com/necolas/react-native-web/blob/54c14d64dabd175e8055e1dc92e9196c821f9b7d/packages/react-native-web/src/exports/Modal/ModalFocusTrap.js#L86-L140). It will focus on the first focusable element first and keep the focus when tabbing within the focus trapped element.

Here is how it behaves in this GH test case. First, it will focus on the first focusable descendant of the modal, in our case, it's the modal overlay. The modal overlay is saved as the last focused element. At this point, the edit composer is blurred. If the edit composer is blurred, it will set SHOULD_SHOW_COMPOSE_INPUT to true.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionItemMessageEdit.tsx#L427

SHOULD_SHOW_COMPOSE_INPUT hides the main composer when an edit composer is focused, on small screens only. Besides the SHOULD_SHOW_COMPOSE_INPUT controls the main composer visibility, it also controls the autoFocus behavior.
https://github.com/Expensify/App/blob/2514f2988eb26858d30fa501c0040b1f8fc2e239/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions/ComposerWithSuggestions.tsx#L288-L289

Because SHOULD_SHOW_COMPOSE_INPUT is now true, autoFocus now becomes true too. Before, it was false because an edit composer was focused which set SHOULD_SHOW_COMPOSE_INPUT to false.

Now, here's the problem. autoFocus is supposed to work only once when the text input is mounted. However, the live markdown input will focus on the input every time the autoFocus is changed to true.
https://github.com/Expensify/react-native-live-markdown/blob/main/src/MarkdownTextInput.web.tsx#L584-L588

The input focus then triggers the focus trap logic again which first focuses on the first focusable descendant, that is the overlay. Then it checks whether the last (prev) focused element is the same as the current focused element. If it's the same, it will start focusing on the last focusable descendant element.

In our case, the last focused element is the overlay and the first focusable descendant is also the overlay, so the focus trap will focus on the last focusable descendant element, that is the cancel button.

### What changes do you think we should make in order to solve the problem?

We can:
1. Update the autoFocus condition to only consider the SHOULD_SHOW_COMPOSE_INPUT value for the small screen, 
2. Don't change the SHOULD_SHOW_COMPOSE_INPUT to true when the edit composer is blurred by the confirmation modal

but I would like to address the root cause of the issue, that is the input gets focused every time autoFocus is changed which doesn't happen with the react native TextInput.

To fix the issue, we should remove autoFocus from the effect deps here
https://github.com/Expensify/react-native-live-markdown/blob/377ab57fa02c598b624eb91e4faf4fd2693596a2/src/MarkdownTextInput.web.tsx#L584-L588

This way, it will work as pointed out by the comment, that is to auto-focus only when the component is mounted, not when autoFocus is changed.

This happens after this react native live markdown [PR](https://github.com/Expensify/react-native-live-markdown/pull/261) which adds the react hooks eslint rule and adds the autoFocus as the deps to fix the lint, but we shouldn't do that for autoFocus case.

This will also fix an issue where the main composer is focused every time the edit composer is blurred.

https://github.com/Expensify/App/assets/50919443/2773f351-bb92-41fd-a3c5-ee5830febb2d

After this change, the overlay will be the one that is focused when opening the confirmation modal, which is what happens with other confirmation modals. Pressing Enter on the overlay will trigger the `pressOnEnter` shortcut because the overlay doesn't have any role.

**Comment by sobitneupane** [comment] 2024-05-31 06:54
Thanks for the proposal everyone.

[Proposal](https://github.com/Expensify/App/issues/42645#issuecomment-2134579694) from @bernhardoj looks good to me.

🎀👀🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-06-01 02:06
The live markdown PR is [here](https://github.com/Expensify/react-native-live-markdown/pull/362)

**Comment by bernhardoj** [comment] 2024-06-03 10:12
The live markdown PR is merged and released in 0.7.78, but we can't update it yet because [0.7.76 caused a regression](https://github.com/Expensify/App/pull/42843), so we need to wait for a new version that fixes the issue.

**Comment by garrettmknight** [comment] 2024-06-03 17:54
Holding on https://github.com/Expensify/App/issues/42766

**Comment by garrettmknight** [comment] 2024-06-07 16:01
Still holding on https://github.com/Expensify/App/issues/42766

**Comment by sobitneupane** [comment] 2024-06-10 14:50
@bernhardoj The react-native-live-markdown version in bumped. Can you please retest and verify that the issue is resolved.

**Comment by bernhardoj** [comment] 2024-06-10 15:16
Tested on staging and i'ts fixed.

https://github.com/Expensify/App/assets/50919443/efc6bd02-6348-4003-bfc6-a1a578f2abee

**Comment by blimpich** [comment] 2024-06-10 16:28
Sweet! @sobitneupane does this mean we can finish with pay out for this issue and close it?

cc: @garrettmknight

**Comment by garrettmknight** [comment] 2024-06-11 08:41
Nice one!

**Payment Summary**
- Contributor: @bernhardoj $250 paid via upwork
- Reviewer: @sobitneupane $250

@sobitneupane is any of the checklist necessary on this one?

**Comment by sobitneupane** [comment] 2024-06-11 08:44
**Regression Test Proposal**

1. Send a message to anyone
2. Edit the message by right clicking
3. Remove all the texts from the message and press enter
4. Verify that the Delete Comment Modal pops up
5. Press Enter
6. Verify that the comment is deleted.

Do we agree 👍 or 👎

**Comment by garrettmknight** [comment] 2024-06-11 10:48
Dropping to weekly for you to request @sobitneupane

**Comment by garrettmknight** [comment] 2024-06-19 19:01
Just awating the reqeust

**Comment by garrettmknight** [comment] 2024-07-01 15:45
Still awaiting payment request

**Comment by garrettmknight** [comment] 2024-07-17 13:48
Still awaiting the payment request

**Comment by garrettmknight** [comment] 2024-07-23 16:42
Still awaiting the payment request

**Comment by garrettmknight** [comment] 2024-07-23 16:42
@sobitneupane I'm gonna close this one, but submit the payment request when you get a chance.

**Closed by garrettmknight** 2024-07-23 16:42 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-29 22:30
$250 approved for @sobitneupane
