### ISSUE TITLE
[HOLD for payment 2023-10-23] [HOLD for payment 2023-10-23] [$1000]  Workspace - App crashes when entering Bank account page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26958] opened 2023-09-07 13:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch New Expensify app.
2. Create a new workspace.
3. Go to Bank account > Update to USD.
5. Click Connect online with Plaid.
6. Return to previous page using device back navigation.
7. Click Connect manually.
8. Return to previous page using device back navigation.
9. In workspace page, click Bank account.

## Expected Result:
App does not crash

## Actual Result:
App crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.65-2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ba47c128-56dc-4065-a3b6-354c88692c48

[logs2.txt](https://github.com/Expensify/App/files/12549370/logs2.txt)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d23926d190e45c2e</li>
        <li>Upwork Job ID: 1700058465699299328</li>
        <li>Last Price Increase: 2023-09-24</li>
    </ul>
</details>

**Comment by laurenreidexpensify** [comment] 2023-09-12 10:06
@thesahindia bump for review thanks

**Comment by laurenreidexpensify** [comment] 2023-09-18 17:28
@thesahindia bump ^^

**Comment by lanitochka17** [comment] 2023-09-21 14:59
@thesahindia Still crashing v1.3.72-8


https://github.com/Expensify/App/assets/78819774/a3b1c99d-9898-47d1-a07f-16e691d12c25

**Comment by laurenreidexpensify** [comment] 2023-09-24 23:57
Doubled bounty

**Comment by pradeepmdk** [comment] 2023-09-25 01:44
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
App crashes when entering Bank account page

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d63ea05f6d1eb7ae00bebafed7aaebf35203e7d7/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L352
when we use the native back button it redirects the workspace menu and again goes to the bank account its directly redirect to substep. so at the time its  `OpenReimbursementAccountPage` again calling and remount the `BankAccountManualStep` component.
 
https://github.com/Expensify/App/blob/d63ea05f6d1eb7ae00bebafed7aaebf35203e7d7/src/components/TextInput/BaseTextInput.js#L66-L77
here when `shouldDelayFocus` we are doing early return. so unmount code L60-L67 is useless here.
### What changes do you think we should make in order to solve the problem?
```javascript
 let focusTimeout;
        if (props.shouldDelayFocus) {
            console.log("input.current", input.current.focus, focusTimeout)
            focusTimeout = setTimeout(() => {
                console.log("input.current1", input.current)
                input.current.focus()
            }, CONST.ANIMATED_TRANSITION);
            
        } else {
            input.current.focus();
        }

        return () => {
            if (!focusTimeout) {
                return;
            }
            clearTimeout(focusTimeout);
        };
```

**Comment by laurenreidexpensify** [comment] 2023-09-27 07:51
@thesahindia what ya think about the proposal above?

**Comment by laurenreidexpensify** [comment] 2023-10-03 09:18
@thesahindia @NikkiWines ^^

**Comment by NikkiWines** [comment] 2023-10-05 06:30
@thesahindia any further thoughts on @bernhardoj's comments? Their proposal looks good to me and was also the first proposal posted

**Comment by laurenreidexpensify** [comment] 2023-10-09 09:10
@NikkiWines @thesahindia ^^ what we thinking next?

**Comment by NikkiWines** [comment] 2023-10-11 14:13
Hmm, ok - I see what you're saying @thesahindia, but given both proposals work for this issue and @bernhardoj's proposal was first I think we should go with theirs. 

I do agree that should generally aim to be more future-proof by doing things like putting the cleanup function at the end, but I don't think we currently have a firm rule about that and the proposal shouldn't be excluded on that basis.

**Comment by laurenreidexpensify** [comment] 2023-10-24 10:56
Payment Summary: 

-  External issue reporter- Applause N/A 
-  Contributor that fixed the issue - @bernhardoj $1000, payment issued in Upwork
-  Contributor+ that helped on the issue and/or PR @thesahindia $1000, please request payment in newdot

**Comment by laurenreidexpensify** [comment] 2023-10-25 09:49
@thesahindia bump for checklist steps so we can close this one out!

**Comment by laurenreidexpensify** [comment] 2023-10-27 15:23
@thesahindia bump for checklist thanks

**Comment by laurenreidexpensify** [comment] 2023-10-30 11:50
@thesahindia bump to get this one closed thanks

**Closed** 2023-10-31 11:22 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-01 20:05
$1,500 payment approved for @thesahindia based on [this summary](https://github.com/Expensify/App/issues/26958#issuecomment-1776982830).
