### ISSUE TITLE
[$500] Manager/Admin submit is still broken

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#33632] opened 2023-12-26 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.17.1 
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1703613770534809

## Action Performed:
1. Create a Collect policy on OldDot, with weekly scheduled submit enabled
2. Invite user A as an employee. Invite user B as a “manager” for submit/approve.
3. Have user A create an expense/report on NewDot (do not submit anything)
4. Log in as user B on NewDot, find the workspace chat for user A
5. Open the workspace chat for user A, click into the open report
6. As user B, click the Submit button
## Expected Result: 
The report is submitted and made available for approval

##Actual Result: 
The report is not actually submitted, though a system message for “submitted” is generated on each click.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/3f66da70-ea42-4e6f-bac5-0e6dede1737c

https://github.com/Expensify/App/assets/38435837/e963ccac-4854-476a-bff3-254e0f8c97f6

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c524ace1cc08829a</li>
        <li>Upwork Job ID: 1739776048543444992</li>
        <li>Last Price Increase: 2024-01-09</li>
    </ul>
</details>

**Comment by rrrshtt** [comment] 2023-12-26 22:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The submit button for managers is broken; it always returns to the pending status.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/c7639e8be8148308157a6b38173c5068c6d33fc9/src/libs/actions/IOU.js#L3030C61-L3030
There is a problem in this line within the `submitReport` function. We are sending the "pending" status.

### What changes do you think we should make in order to solve the problem?
We need to check and change all statuses to the correct one.

### What alternative solutions did you explore? (Optional)

**Comment by Pujan92** [comment] 2023-12-28 19:56
@JmillsExpensify Do approver/admin can submit the report behalf of the employee? Currently backend is responding with the permission error.
```
"title": "Cannot complete action",
"message": "You do not have the permission to do the requested action.",
```

**Comment by JmillsExpensify** [comment] 2024-01-03 04:33
Yes, this should be an internal issue. cc @mountiny I think this issue should be relabeled and assigned to you.

**Comment by Beamanator** [comment] 2024-01-03 16:49
I think we should bring this to wave6 to be assigned, yeah?

I also have this similar bug report here: https://expensify.slack.com/archives/C049HHMV9SM/p1703801786632339

Should we handle that here too or in a new issue?

**Comment by mountiny** [comment] 2024-01-04 15:08
Yep I think this will be handled with the changes I am already working on so assigning myself

**Comment by mountiny** [comment] 2024-01-10 19:09
Will check if this is going to be resolved

**Comment by mountiny** [comment] 2024-01-11 11:12
Looking into this today

**Comment by mountiny** [comment] 2024-01-12 00:34
Just tested submitting as the approver/ admin and it worked

<img width="1115" alt="image" src="https://github.com/Expensify/App/assets/36083550/301d38e5-557c-4a88-b8a2-11a09fe099c4">

Going to close but if we can run into this again with reproduction we can reopen

**Closed by mountiny** 2024-01-12 00:34 UTC
Labels: External, Daily, Help Wanted, Bug
