### ISSUE TITLE
LHN - Chat with a workspace member disappears if it only contains a task

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50402] opened 2024-10-08 12:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.46-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/50281
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Log in with any account with a workspace
2. Navigate to Workspace settings - Members
3. Invite any Gmail account
4. Navigate back to the LHN
5. Click on FAB - Start chat
6. Input the account invited in step 3 and click on it
7. Navigate to Composer + button - Assign task
8. Set any title and click on "Next"
9. Click on "Assignee" and set it to the workspace member
10. Click on the "Confirm task" button
11. Click on any other LHN chat

## Expected Result:
Chat should be visible in the LHN.

## Actual Result:
Chat with a workspace member disappears if it only contains a task. It doesn't affect non-workspace accounts.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/c960bfb9-6675-48be-8534-d64c256954b2

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-10-08 12:10
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by mkzie2** [comment] 2024-10-09 02:36
dupe of https://github.com/Expensify/App/issues/50478

**Comment by VictoriaExpensify** [comment] 2024-10-09 07:38
Closing this out in favour of https://github.com/Expensify/App/issues/50478

**Closed by VictoriaExpensify** 2024-10-09 07:38 UTC
Labels: Daily, Bug
