### ISSUE TITLE
[HOLD for payment 2024-10-25] [$250] Room - After rejoining room, notification settings changed to immediately

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48694] opened 2024-09-06 10:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.30-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Via fab, create a room
3. Tap header -- settings
4. Note notifications is set "daily"
5. Tap leave and now tap header -- settings
6. Now note notifications field missing
7. Now send a message and join the room
8. Tap header--settings

## Expected Result:
After rejoining room, notification settings must not change to immediately.

## Actual Result:
After rejoining room, notification settings changed to immediately.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/66acf499-c486-4176-aa5e-193f369b3917

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021833657980074790757</li>
        <li>Upwork Job ID: 1833657980074790757</li>
        <li>Last Price Increase: 2024-10-02</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 104297840</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by IuliiaHerets** [comment] 2024-09-06 10:17
@strepanier03  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by wildan-m** [comment] 2024-09-24 09:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Upon reentering the room, notification settings were changed to immediate.

### What is the root cause of that problem?

We are always override the notification to `ALWAYS` when report not empty and current notification preference is hidden

https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/libs/actions/Report.ts#L551-L562

### What changes do you think we should make in order to solve the problem?

The change is intended to fix the issue of chats disappearing when creating a chat with an unknown user while offline.

https://github.com/Expensify/App/pull/47450

When the PR was created, the `addComment` API did not return notificationPreference, so the PR attempted to fill it from the front end. This is detailed in the author's alternative proposal. https://github.com/Expensify/App/issues/44829#issuecomment-2239928681

The `addComment` API now includes notification preference from the backend. We can revert the unnecessary changes in the PR, particularly the ones related to `successData`.

https://github.com/Expensify/App/blob/1c39bd2bd896a573373b7ab357edc42e6ea48246/src/libs/actions/Report.ts#L551-L562

### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment] 2024-09-24 09:10
[Proposal Updated](https://github.com/Expensify/App/issues/48694#issuecomment-2370700067)

- mention joinRoom adjustment if required

**Comment by wildan-m** [comment] 2024-09-24 19:26
@shubham1206agra looks like the root cause not from your PR. @fedirjh Have you reviewed my proposal? https://github.com/Expensify/App/issues/48694#issuecomment-2370700067

**Comment by wildan-m** [comment] 2024-10-01 03:56
> Your proposal does not solve the problem correctly. Again, I will run the fix here.

@shubham1206agra have you tested it?

In my test, it correctly set the notification preferences according to the server response.

https://github.com/user-attachments/assets/f572bccf-cbc4-4469-9446-b145a1b2f4ad

**Comment by lakchote** [comment] 2024-10-07 07:20
@shubham1206agra's proposal LGTM.

**Comment by lakchote** [comment] 2024-10-11 05:52
@shubham1206agra any update for the PR?

**Comment by strepanier03** [comment] 2024-10-25 19:18
@shubham1206agra @fedirjh - I'm going to be off for the day very soon but I'll check in this weekend to see if the checklist is complete. Once it is I'll do that payment summary.

**Comment by lakchote** [comment] 2024-10-28 08:29
@shubham1206agra @fedirjh please complete the checklist, thanks!

**Comment by strepanier03** [comment] 2024-10-28 17:04
### Payment Summary

- [ ] $250 - @fedirjh via Manual Requests in New Expensify
- [ ] @shubham1206agra requires payment via Upwork but offer is pending still [automatic offer](https://www.upwork.com/nx/wm/offer/104297840) (Contributor)

**Comment by strepanier03** [comment] 2024-10-28 17:05
@shubham1206agra I'll check back in later today to see if you accepted the offer in Upwork. 

@fedirjh - please feel free to request payment in New Expensify. I see your checklist responses and have created the reg test GH.

**Comment by strepanier03** [comment] 2024-10-29 03:41
All right, I paid out the UPwork job, thanks for accepting @shubham1206agra. 

All that let's is @fedirjh to request in New Expensify so I'm closing this GH as completed.

**Closed by strepanier03** 2024-10-29 03:41 UTC
Labels: External, Daily, Monthly, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-10 12:17
$250 approved for @fedirjh
