### ISSUE TITLE
[HOLD for payment 2024-04-05] [$1000] Chat - The keyboard is overlapping with the composer

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35380] opened 2024-01-30 11:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Open a chat
2. Open the native keyboard emoji picker

## Expected Result:
It shouldn't overlap.

## Actual Result:
The keyboard is overlapping with the composer.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

<img src="https://github.com/Expensify/App/assets/43996225/8b0f67b7-1be8-4f4d-877f-1826b0d5deb0" width="40%" height="40%">

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014446080d93df8ee7</li>
        <li>Upwork Job ID: 1752288736160931840</li>
        <li>Last Price Increase: 2024-03-20</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 0</li>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by eeleuch** [comment] 2024-01-30 12:36
This can be fixed using height: "100smv" on the big container of this page
https://css-tricks.com/the-large-small-and-dynamic-viewports/

**Comment by eeleuch** [comment] 2024-01-30 12:37
Contributor details
Your Expensify account email: ely.369@outlook.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01237276f354a158ce

**Comment by situchan** [comment] 2024-02-02 12:54
@eeleuch please read through our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Thanks

**Comment by jeremy-croff** [comment] 2024-02-13 23:25
I can only reproduce this on emulators, when we show and hide the keyboard there.

**Comment by situchan** [comment] 2024-02-19 15:34
Still looking for proposals

**Comment by mallenexpensify** [comment] 2024-02-21 01:45
Bumped to $1000 to get more 👀

**Comment by bernhardoj** [comment] 2024-02-21 08:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The keyboard covers a little bit of the composer. The header is also hidden.

### What is the root cause of that problem?
On iOS mWeb, when we focus on an input, the screen will scroll to make sure the input is visible to the user. The report header will be visible thanks to `withViewportOffsetTop`.

The value from `withViewportOffsetTop` will be applied to the report screen margin top.
https://github.com/Expensify/App/blob/8d60f6737931cd3df8cecb6ddf68007a140fc04d/src/pages/home/ReportScreen.js#L603

https://github.com/Expensify/App/assets/50919443/9f087675-d3fc-4bab-be74-ad2820e85d9a

When we open the keyboard native emoji picker, the keyboard height becomes bigger, so the composer input is covered a bit because we never resize the report screen height.

_`withViewportOffsetTop` is first added in https://github.com/Expensify/App/pull/9031_

### What changes do you think we should make in order to solve the problem?

Instead of using `withViewportOffsetTop`, we can set `shouldEnableMaxHeight` to true for the report screen wrapper.
```
shouldEnableMaxHeight={isTopMostReportId}
```

`shouldEnableMaxHeight` is the existing logic we have to resize a screen to the available visual viewport.

Before:

https://github.com/Expensify/App/assets/50919443/4666017d-96c9-4957-9dc4-6427f9919309


After:

https://github.com/Expensify/App/assets/50919443/335587de-114f-4bf7-b411-3676708d5ac9

_you can see that the composer is hidden briefly after the header is shown and it's coming from https://github.com/Expensify/App/pull/34254_

**Comment by situchan** [comment] 2024-02-23 20:41
Latest proposals are in review

**Comment by situchan** [comment] 2024-02-26 16:48
@suneox thanks for the proposal. Do you mind sharing test branch?

**Comment by situchan** [comment] 2024-02-27 13:37
@bernhardoj your solution is not general. This also happens on other places of the app, i.e. https://github.com/Expensify/App/issues/35403


@suneox please check this weird behavior. Even worse than before fix.


https://github.com/Expensify/App/assets/108292595/3b25fe06-5e76-404b-b4f3-32a09f43c90d

**Comment by situchan** [comment] 2024-02-27 13:58
yes, this includes https://github.com/Expensify/App/issues/35403 because it was closed as same root cause

**Comment by bernhardoj** [comment] 2024-02-27 15:51
https://github.com/Expensify/App/issues/35403 has a different root cause. The emoji list height is bigger than expected, pushing down the skin tone list. The emoji list max height is calcluated based on this logic, where it subtracted the `windowHeight` with some variable amount that depends on `isRenderingShortcutRow`.
https://github.com/Expensify/App/blob/174a0324028fcfcb1df7e82124a76ec9d805179e/src/styles/utils/index.ts#L858-L864

The util function is being used here:
https://github.com/Expensify/App/blob/174a0324028fcfcb1df7e82124a76ec9d805179e/src/components/EmojiPicker/EmojiPickerMenu/useEmojiPickerMenu.js#L27

`isRenderingShortcutRow` will be true if the emoji is filtered (when searching), but it should be the opposite. When the emoji is filtered, the emoji shortcut row is not rendered.

**Comment by bernhardoj** [comment] 2024-03-04 15:01
@situchan [here](https://github.com/bernhardoj/Expensify/tree/fix/35380-keyboard-overlap-with-composer) is the branch

**Comment by joekaufmanexpensify** [comment] 2024-03-05 21:54
@mallenexpensify @situchan is [this case](https://github.com/Expensify/App/issues/35403) drastically different than the one being worked on in this issue? The behavior is similar, so it feels easiest to just handle then in one issue, especially since this one is already paying out $1k. LMK your thoughts.

**Comment by mallenexpensify** [comment] 2024-03-06 00:22
I'm unsure if they're directly related @joekaufmanexpensify , what do you think @situchan ? 
For this issue, the overlap is the top, on the other the part that's cut off is at the bottom.  

I know Safari can be a _tricky_ browser, we were dropping a lot of [safari-only bugs into this tracking GH.](https://github.com/Expensify/App/issues/23088) It's a 👻 town there though.

**Comment by mallenexpensify** [comment] 2024-03-10 21:25
@situchan 👀 on the above comment plz?

**Comment by mallenexpensify** [comment] 2024-03-13 01:08
Thanks @suneox .  @situchan 👀 on the above plz

**Comment by situchan** [comment] 2024-03-13 16:05
reviewing...

**Comment by mallenexpensify** [comment] 2024-03-14 21:52
@situchan it's been over a week since you've provide a meaningful update. If you're unable to review this by EOD tomorrow, can you ask in #contributor-plus for another C+. IF there's no reply, I will reassign.  Thx

**Comment by situchan** [comment] 2024-03-15 13:52
@suneox I know you fixed lots of mSafari tricky issues in the past.
While your proposal being solid, I personally like @bernhardoj's solution of using `shouldEnableMaxHeight` deprecating existing `viewportOffsetTop`. And it's already widely used in other pages.
I haven't found issue yet.
@suneox are you able to find any issue or regression in this approach?

**Comment by situchan** [comment] 2024-03-15 13:56
> Hi @mallenexpensify i'm sure this issue is a different root cause with https://github.com/Expensify/App/issues/35403 and i also agree with you the Safari browser is a tricky browser, and we still wait @situchan confirm for https://github.com/Expensify/App/issues/35403

Regarding this matter, I agree two issues have different root cause but please check https://github.com/Expensify/App/issues/35403#issuecomment-1979702408.
We can fix both issues here but suggest to separate into 2 PRs for each for the sake of regression-free.

**Comment by situchan** [comment] 2024-03-15 14:45
Thanks for the explanation.
👍 to your main solution.
Let's just wait for @mallenexpensify to provide feedback on https://github.com/Expensify/App/issues/35380#issuecomment-1999722199 how to handle 2 issues.

**Comment by mallenexpensify** [comment] 2024-03-15 21:39
Re: https://github.com/Expensify/App/issues/35380#issuecomment-1999722199

@situchan , can you approve a proposal then ask the internal engineer what they think? 
We've done it both ways, fixing one bug with multiple PRs and also making separate PRs.  I'm unsure exactly what the difference is for when do one over the other.  And.. same for this issue .  Thx

**Comment by situchan** [comment] 2024-03-18 21:18
Not overdue

**Comment by situchan** [comment] 2024-03-20 16:02
I recommend @suneox's [main solution](https://github.com/Expensify/App/issues/35380#issuecomment-1960078129).
🎀 👀 🎀 C+ reviewed

**Comment by situchan** [comment] 2024-03-20 16:02
@iwiznia please also check https://github.com/Expensify/App/issues/35380#issuecomment-1999722199. Thanks

**Comment by situchan** [comment] 2024-03-20 17:30
> I am fine if we want to do 2 PRs for this same issue, but whoever fixes this issue should fix both cases as it seems to me they are very closely related.

sure. @suneox will fix both cases.

**Comment by situchan** [comment] 2024-03-20 17:31
> @suneox mains solution looks good, but will it apply to all platforms when it is only needed in one?

The solution is only applied to iOS safari

**Comment by iwiznia** [comment] 2024-03-20 17:32
> The solution is only applied to iOS safari

Oh ok, did not see it in the code that's why I asked.

**Comment by iwiznia** [comment] 2024-03-20 18:40
hmmmm honestly not sure which one is best, @situchan what do you think?

**Comment by situchan** [comment] 2024-03-20 18:45
I haven't tested that other issue yet considering this as next PR.
`update popoverInnerContainer maxHeight style to 100%` this solution looks good in theory.

Actually, I think we can fix in one PR as no conflict between solutions.

**Comment by sobitneupane** [comment] 2024-03-29 09:29
https://github.com/Expensify/App/issues/39061 is regression from this issue @situchan Can you please review https://github.com/Expensify/App/pull/39209 PR.

**Comment by mallenexpensify** [comment] 2024-04-05 21:20
Holding on payment due to the regression.  @situchan is out so @sobitneupane will be reviewing [the PR](https://github.com/Expensify/App/pull/39209)

**Comment by mallenexpensify** [comment] 2024-04-17 02:51
Sobit, the PR hit production 6 days ago, are you due payment here?  If so, is it $250 or $500?  I think it's $500 cuz the price reduction went into April 4 and your comment above is from March 29.

**Comment by sobitneupane** [comment] 2024-04-17 07:17
@mallenexpensify Yup. I also think It should be $500.

**Comment by mallenexpensify** [comment] 2024-04-18 20:41
Contributor: @suneox paid $1000 via Upwork
Contributor+: @situchan paid $500 via Upwork (50% reduction due to regression)
Contributor+: @sobitneupane owed $500 via NewDot (PR review to fix regression cuz @situchan was OOO). 

TestRail GH created - https://github.com/Expensify/Expensify/issues/389037

Gonna close, @situchan , when you're back from OOO, please finish the checklist.  Thx

**Closed by mallenexpensify** 2024-04-18 20:41 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
