### ISSUE TITLE
[$500] Web - On login with concierge, different chat is displayed before redirecting to concierge

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34826] opened 2024-01-19 18:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.28.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open the app
2. Logout if logged in
3. Visit concierge link eg: https://staging.new.expensify.com/concierge

## Expected Result:
App should display concierge page on login with concierge link

## Actual Result:
App displays different chat first before redirecting to concierge page on login with concierge link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/bfff8d55-ca95-4c61-9fc9-285293eb0f77

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195e9beababa0e60d</li>
        <li>Upwork Job ID: 1748405126262292480</li>
        <li>Last Price Increase: 2024-01-19</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2024-01-20 03:22
Dupe of https://github.com/Expensify/App/issues/34755

**Comment by s77rt** [comment] 2024-01-20 19:05
@puneetlath Please close this as a dupe

**Comment by s77rt** [comment] 2024-01-25 18:28
To be closed

**Closed** 2024-01-26 14:55 UTC
Labels: External, Daily, Help Wanted, Bug
