### ISSUE TITLE
[HOLD for payment 2023-10-18] [$1000] Certain country flags are not searchable when searching them in Spanish language

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23429] opened 2023-07-23 18:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a chat.
2. Type the names of countries in Spanish such as "finlandia" "Irlanda" and "Zimbabue"
3. Notice that these countries' flags will not be displayed in the search results
4. Perform the same search using English language
5. Observe that the flags are displayed in the search results
## Expected Result: 
All country flags should be searchable when searching them in the Spanish language
## Actual Result: 
Some country flags are not searchable in Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/ca679cbe-c55b-4f9e-82de-2137488a5183

https://github.com/Expensify/App/assets/43996225/30b9913d-b1ce-4334-9aad-308105a126e0

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690047690830869?thread_ts=1690047031.939139&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c6613ed33b9ba66</li>
        <li>Upwork Job ID: 1683859438447579136</li>
        <li>Last Price Increase: 2023-08-22</li>
<li>Automatic offers: </li>
<ul>
<li>aimane-chnaif | Reviewer | 27283763</li>
</ul></li>
    </ul>
</details>

**Comment by ShogunFire** [comment] 2023-07-23 23:00
All the smileys are in english, for example we write :smile: not :sonrisa: I don't think it's a bug

**Comment by puneetlath** [comment] 2023-07-24 15:40
This is more of a feature request than a bug. We get the emoji names from an external source, so I don't think there's anything that needs to be done here. I'm going to go ahead and close, but feel free to to chime in if you disagree.

**Comment by ayazhussain79** [comment] 2023-07-24 15:48
@puneetlath its the regression if this [PR](https://github.com/Expensify/App/pull/20828)

**Comment by puneetlath** [comment] 2023-07-24 15:51
@ayazhussain79 you are saying that you were able to search for spanish language flags before that PR?

**Comment by ShogunFire** [comment] 2023-07-24 15:58
I tried the same thing as you @Nodebrute  but for me it wasn't working, at least for Irlanda, maybe it's a special case because Ireland is a keyword of gb

**Comment by ShogunFire** [comment] 2023-07-24 16:10
What happens if you type Irland, aren't both showing ? I don't remember exactly what went wrong, maybe it was just the fact that in english you have gb showing in the options whereas in spanish you don't

**Comment by puneetlath** [comment] 2023-07-24 20:17
>the spanish language keywords were added in that PR but for all flags they added the word 'Bandera' instead of country's spanish name

I believe I saw in that PR that they got the spanish emoji names from an external source. Does that source have different names for the country flag emojis?

**Comment by puneetlath** [comment] 2023-07-25 15:18
Great, thanks for helping me understand that. Reopening!

**Comment by puneetlath** [comment] 2023-07-27 21:29
@aimane-chnaif thoughts on the proposals?

**Comment by puneetlath** [comment] 2023-07-31 17:40
@aimane-chnaif bump!

**Comment by puneetlath** [comment] 2023-08-02 21:32
@aimane-chnaif bump, could you take a look at the existing proposals?

**Comment by puneetlath** [comment] 2023-08-07 18:48
@aimane-chnaif friendly bump.

**Comment by puneetlath** [comment] 2023-08-10 18:57
@aimane-chnaif bump again.

**Comment by kosmydel** [comment] 2023-08-22 13:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is impossible to look up the flag by typing in a other language than English.

### What is the root cause of that problem?
Firstly, let mi present shortly how emojis work. To send an emoji we can use a _shortcode_. Those shortcodes depend on the currently selected language:
- User can always use the name from the `common.js` file (independent from the selected language, it is used by default, i.g. `giraffe`),
- **or** if the selected language is **different** from the default one, the name of currently selected language (in this case its spanish, i.g. `cara_jirafa`).

https://github.com/Expensify/App/blob/3892292b42c7f974566c20b6e520dfba32cd8f16/src/libs/EmojiTrie.js#L21-L22

The problem is with flags, where the names in Spanish translations use different shortcodes.

Currently, we are using a Slack's shortcodes, that is i.g. `:bandera-pl:`. Here is how Discord and GitHub handles it:
// Screen of the emojis shortcodes from https://emojiterra.com/es/bandera-polonia/

That saying, user currently can use the Spanish translation, but it is `:bandera-pl:` instead of the expected `:polonia:`.

### What changes do you think we should make in order to solve the problem?
If we want to use language-specific shortcodes, we can change those in the `es.js` files.

<table>
<tr>
    <td></td>
    <td> Currently </td> <td> Option 1 </td> <td> Option 2 </td>
</tr>
<tr>
<td></td>
</tr>
<tr>
<td></td>
<td>

```javascript
'🇵🇱': {
    name: 'bandera-pl',
    keywords: ['Bandera'],
},
```

</td>
<td>

```javascript
'🇵🇱': {
    name: 'polonia',
    keywords: ['bandera'],
},
```
</td>
<td>

```javascript
'🇵🇱': {
    name: 'bandera-pl',
    keywords: ['bandera', 'polonia'],
},
```
</td>
</tr>
<tr>
<td>
User can use names:
</td>
<td>
poland, bandera-pl

<img width="250" alt="Screenshot 2023-08-22 at 15 46 10" src="https://github.com/Expensify/App/assets/104823336/466fefda-d540-497f-8926-bad1a045b868">
<img width="163" alt="Screenshot 2023-08-22 at 15 47 15" src="https://github.com/Expensify/App/assets/104823336/e55e6660-38b8-4d86-8940-79a5a11a1f5d">

</td>
<td>
poland, polonia
<img width="164" alt="Screenshot 2023-08-22 at 15 48 41" src="https://github.com/Expensify/App/assets/104823336/9a062a2c-36bb-4b59-b79e-81db2bc292db">

<img width="164" alt="Screenshot 2023-08-22 at 15 48 23" src="https://github.com/Expensify/App/assets/104823336/0e5d4517-d71f-4bec-a820-954ae29545b5">

</td>
<td>
poland, bandera-pl
<img width="211" alt="Screenshot 2023-08-22 at 15 49 22" src="https://github.com/Expensify/App/assets/104823336/406ed533-5cc3-4d5e-b9bf-05e0ed302930">

</td>
</tr>
<tr>
<td>
User can look up using:
</td>
<td>
poland, bandera-pl, Bandera
</td>
<td>
poland, polonia, bandera
</td>
<td>
poland, bandera, polonia
</td>
</tr>
<tr>
<td>
Changes:
</td>
<td>
---
</td>
<td>
We can additionaly look up and use 'polonia'
</td>
<td>
We can additionaly look up 'polonia'
</td>
</tr>
</table>

Depending on the decision, we can use either option.



### What alternative solutions did you explore? (Optional)
Two options are in the above table.


☝️

**Comment by kosmydel** [comment] 2023-08-22 13:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It is impossible to look up the flag by typing in a other language than English.

### What is the root cause of that problem?
Firstly, let mi present shortly how emojis work. To send an emoji we can use a _shortcode_. Those shortcodes depend on the currently selected language:
- User can always use the name from the `common.js` file (independent from the selected language, it is used by default, i.g. `giraffe`),
- **or** if the selected language is **different** from the default one, the name of currently selected language (in this case its spanish, i.g. `cara_jirafa`).

https://github.com/Expensify/App/blob/3892292b42c7f974566c20b6e520dfba32cd8f16/src/libs/EmojiTrie.js#L21-L22

The problem is with flags, where the names in Spanish translations use different shortcodes.

Currently, we are using a Slack's shortcodes, that is i.g. `:bandera-pl:`. Here is how Discord and GitHub handles it:
// Screen of the emojis shortcodes from https://emojiterra.com/es/bandera-polonia/

That saying, user currently can use the Spanish translation, but it is `:bandera-pl:` instead of the expected `:polonia:`.

### What changes do you think we should make in order to solve the problem?
If we want to use language-specific shortcodes, we can change those in the `es.js` files.

<table>
<tr>
    <td></td>
    <td> Currently </td> <td> Option 1 </td> <td> Option 2 </td>
</tr>
<tr>
<td></td>
<td>

```javascript
'🇵🇱': {
    name: 'bandera-pl',
    keywords: ['Bandera'],
},
```

</td>
<td>

```javascript
'🇵🇱': {
    name: 'polonia',
    keywords: ['bandera'],
},
```
</td>
<td>

```javascript
'🇵🇱': {
    name: 'bandera-pl',
    keywords: ['bandera', 'polonia'],
},
```
</td>
</tr>
<tr>
<td>Examples:</td>
<td>
<img width="250" alt="Screenshot 2023-08-22 at 15 46 10" src="https://github.com/Expensify/App/assets/104823336/466fefda-d540-497f-8926-bad1a045b868">
<img width="163" alt="Screenshot 2023-08-22 at 15 47 15" src="https://github.com/Expensify/App/assets/104823336/e55e6660-38b8-4d86-8940-79a5a11a1f5d">
</td>
<td>
<img width="164" alt="Screenshot 2023-08-22 at 15 48 41" src="https://github.com/Expensify/App/assets/104823336/9a062a2c-36bb-4b59-b79e-81db2bc292db">

<img width="164" alt="Screenshot 2023-08-22 at 15 48 23" src="https://github.com/Expensify/App/assets/104823336/0e5d4517-d71f-4bec-a820-954ae29545b5">
</td>
<td>
<img width="211" alt="Screenshot 2023-08-22 at 15 49 22" src="https://github.com/Expensify/App/assets/104823336/406ed533-5cc3-4d5e-b9bf-05e0ed302930">
<img width="163" alt="Screenshot 2023-08-22 at 15 47 15" src="https://github.com/Expensify/App/assets/104823336/e55e6660-38b8-4d86-8940-79a5a11a1f5d">
<img width="250" alt="Screenshot 2023-08-22 at 15 46 10" src="https://github.com/Expensify/App/assets/104823336/466fefda-d540-497f-8926-bad1a045b868">
</td>
</td>
</tr>
<tr>
<td>
User can use names:
</td>
<td>
poland, bandera-pl

</td>
<td>
poland, polonia

</td>
<td>
poland, bandera-pl

</td>
</tr>
<tr>
<td>
User can look up using:
</td>
<td>
poland, bandera-pl, bandera
</td>
<td>
poland, polonia, bandera
</td>
<td>
poland, bandera-pl, bandera, polonia
</td>
</tr>
<tr>
<td>
Changes:
</td>
<td>
---
</td>
<td>
We can additionaly look up and use 'polonia'
</td>
<td>
We can additionaly look up 'polonia'
</td>
</tr>
</table>

**Needed actions:**
1. Make a decision, which option should we chose from the above table ☝️
2. We can download those translations using previously used [webpage](https://emojiterra.com/es/bandera-polonia/) or from other, similar [page](https://emojibase.dev/api/emojibase) (from this one we can download JSON).
3. Write a short Python/JavaScript code to merge those translations to the `es.js` file.

### What alternative solutions did you explore? (Optional)
Two options are in the above table.☝️

**Comment by puneetlath** [comment] 2023-08-22 18:05
@aimane-chnaif thoughts on the proposal?

**Comment by puneetlath** [comment] 2023-08-25 15:59
@aimane-chnaif friendly bump.

**Comment by kosmydel** [comment] 2023-08-25 17:21
> However, I was thinking of reusing languages > allCountries to be consistent with countries search on other pages.

@aimane-chnaif 
Good point. Using `allCountries` for consistency will be much better. 

Can I ask for the assignment?

**Comment by puneetlath** [comment] 2023-08-25 17:29
I also like option 1.

**Comment by kosmydel** [comment] 2023-08-25 19:27
> > Good point. Using `allCountries` for consistency will be much better.
> 
> So how to implement this?

In my proposal, I wrote:

> Write a short Python/JavaScript code to merge those translations to the es.js file.

Since this is one-time work, I think that it would work.  I updated[ my proposal](https://github.com/Expensify/App/issues/23429#issuecomment-1688235116) with detailed steps.
cc @aimane-chnaif 

<details>
<summary>
Additional steps
</summary>
I would write a short Python (or JS) script:

1. Load the `allCountries` JSON from the `es.js`. (mapping two letter code -> full name) 
2. Load the `emojis/es.js` JSON.
3. Match the 2 letter codes from `allCountries` with `emojis.js`. Look for the `bandera-` prefix in the emoji name. If matched, replace it with the name from `allCountries` in lowercase with spaces replaced with `_`.
5. Save to the results (a modified `emojis/es.js` file) or print the result to the console and manually change it.

Example mapping:
```javascript
// es.js -> allCountries:
PL: 'Polonia', 

// emojis/es.js
'🇵🇱': {
    name: 'bandera-pl',     // Find all `bandera-` prefixes, and replace `name` with the above `PL` -> `polonia` matching.
    keywords: ['Bandera'],
},

// Output:
'🇵🇱': {
    name: 'polonia',
    keywords: ['bandera'],
},
```
<details/>

**Comment by kosmydel** [comment] 2023-08-25 20:10
I've prepared a draft of the script, works well:
<img width="1071" alt="Screenshot 2023-08-25 at 22 09 32" src="https://github.com/Expensify/App/assets/104823336/73f00810-e821-4428-8876-72edd179179d">

**Comment by kosmydel** [comment] 2023-08-29 08:47
> @kosmydel `bandera-xx` should also be searchable when app language is set to Spanish

Sure, I can adjust the script. 

> > Using allCountries for consistency will be much better
> 
> I don't see this implementation in the proposal

It’s described under “How I would merge those translations?” section. 

I will update you more in 2/3 hours as I'm going on a break.

**Comment by kosmydel** [comment] 2023-08-29 10:42
@aimane-chnaif 
I've updated the script, so it is possible to search for `bandera-xx`. 

<details>
<summary>
Here are the results
</summary>

Note: Terminal doesn't render emojis
![Screenshot 2023-08-29 at 12 40 51](https://github.com/Expensify/App/assets/104823336/85b7bd18-390c-4978-aaed-303293ab3501)
</details>

I've also slightly updated my proposal.

**Comment by puneetlath** [comment] 2023-09-04 13:45
@kosmydel when do you expect to have the PR ready for review?

**Comment by kosmydel** [comment] 2023-09-04 13:51
Hey @puneetlath
Sorry for the delay. I had to prioritize [another feature](https://github.com/Expensify/App/pull/26307).

I've just started working on it. I prepared the code and I have to test it and prepare videos & docs. I should finish it by tomorrow.

**Comment by puneetlath** [comment] 2023-09-04 13:52
Sounds good, thanks!

**Comment by kosmydel** [comment] 2023-09-05 07:42
The PR is ready for the review.
cc @puneetlath @aimane-chnaif

**Comment by puneetlath** [comment] 2023-09-28 10:53
How's this one going @aimane-chnaif @kosmydel?

**Comment by puneetlath** [comment] 2023-10-01 03:26
Got it. @kosmydel mind merging main into your branch so that we can take this across the finish line? Thanks!

**Comment by kosmydel** [comment] 2023-10-03 15:57
Hey, I was OOO last week, and I am catching up with my issues (which might be slow, because in October I work part-time in Expensify). 
I merged it yesterday (and again today).

**Comment by puneetlath** [comment] 2023-10-16 19:35
@aimane-chnaif friendly reminder about the checklist so that we can pay on wednesday.

**Comment by puneetlath** [comment] 2023-10-19 15:38
@aimane-chnaif bump on the checklist so we can pay and close this out! 😄

**Comment by puneetlath** [comment] 2023-10-19 19:34
Thanks @aimane-chnaif. Please accept the upwork offer. 

@ayazhussain79 looks like you need to apply to the job. Let me know when you have.

**Comment by puneetlath** [comment] 2023-10-23 14:11
@ayazhussain79 I sent you an offer here: https://www.upwork.com/nx/wm/offer/27330296

**Comment by puneetlath** [comment] 2023-10-23 17:45
kk all paid. Thanks everyone!

**Closed by puneetlath** 2023-10-23 17:45 UTC
Labels: External, Daily, Awaiting Payment, Bug
