### ISSUE TITLE
Unable to invite a new user to the workspace #admin room via mention

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40956] opened 2024-04-25 03:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.65-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713995226150959

## Action Performed:
1. Open any workspace admin room
2. Mention any user to invite
## Expected Result:
System message appears with the option to invite and do nothing
## Actual Result:
No option to invite. Able to invite to other rooms by mentioning
## Workaround:
unknonw
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f55a6618-cd84-4f5d-9952-a58bcd5a8020

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by anmurali** [comment] 2024-04-30 18:13
I believe this is by design. All admins on a workspace are automatically members of the #admins room and anyone else cannot be invited.

**Comment by twisterdotcom** [comment] 2024-04-30 21:20
@anmurali we agreed here this should be a feature: https://expensify.slack.com/archives/C03U7DCU4/p1713991481225909?thread_ts=1713968604.674249&cid=C03U7DCU4

**Comment by anmurali** [comment] 2024-05-15 01:54
Just confirming this in vip-vsb as not many people engaged in that thread @twisterdotcom

**Comment by anmurali** [comment] 2024-06-05 02:41
Based on [this](https://expensify.slack.com/archives/CC7NECV4L/p1717525527830119), I think we should close this. Doesn't feel critical.

**Closed by anmurali** 2024-06-05 02:41 UTC
Labels: Weekly, NewFeature, Overdue
