### ISSUE TITLE
[$500] Android - Workspace-Contacts email id is truncated and not shown to full available space.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#30827] opened 2023-11-03 09:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces
4.Tap on a Workspace which has members
5.Tap Members

## Expected Result:
In Workspace members page, all contacts email id should be shown to full available space.

## Actual Result:
In Workspace members page, contacts email id is truncated and not shown to full available space.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![Bug6261872_1698996957547!IMG_20231103_125942](https://github.com/Expensify/App/assets/115492554/5dde939b-7761-474b-880d-7ad69b316e7f)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017dcc53012001c374</li>
        <li>Upwork Job ID: 1720369916206796800</li>
        <li>Last Price Increase: 2023-11-03</li>
    </ul>
</details>

**Comment by erquhart** [comment] 2023-11-03 15:01
Duplicate of https://github.com/Expensify/App/issues/30023 also.

**Comment by MitchExpensify** [comment] 2023-11-05 23:19
Dupe - closing

**Closed by MitchExpensify** 2023-11-05 23:19 UTC
Labels: External, Daily, Help Wanted, Bug
