### ISSUE TITLE
Incorrect page is showing even there is error in bank connect flow

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#24371] opened 2023-08-10 13:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Start connect bank flow, do everything till step 3 fine, Save and continue.
2. Close the modal & open the flow again by click `Continue with the step`.
3. Observe you're landed and Step 3 which is correct, now navigate back to 2nd step and do type random invalid email which returns backend error.https://hahjajhahjahja.assssss.a.s.s.ss.a.s.ssssssass.asssshja.chjahjahahjhjajhha.hjahjahjahjahjahjahja.hahjahjjahjahjaahjahjhja.hjahjahjahjaahjahj.hjahjahjahjahjaahjahj.hjahjahjahjaahj.hjajhahjaajhahjahjahjahjahjahjahjahjahjahjaahjahjaasshjsjhshjsh/jshjshj.chjahjshjshjshjshjshj.hjahjahshjshjshjshjshjshjshjshjshjs.ahjshjshjshjshjshjshjs.hjahjahjs[hjshjshjshjshjshjshjhjshjshjshjshjshjshjshjshjshjshjhjshjshjahj.com/](http://hjshjshjshjshjshjshjhjshjshjshjshjshjshjshjshjshjshjhjshjshjahj.com/)
4. Observe that data save failed & you're stuck at step.
5. Close the modal & restart the flow again by click `Continue Over step` and observe it takes to step 3 instead of step 2
## Expected Result: 
Flow should be take us to the correct step if any failed validations there when updating.
## Actual Result: 
Taking to the wrong page even having wrong details.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.53-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/d1a26291-0954-41c1-a0ec-6e067cf1a086

https://github.com/Expensify/App/assets/43996225/e03af070-bd5c-4333-99f4-b464e74ffda1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @b4s36t4
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690924062828829

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01cf0cacf8a882b35c</li>
        <li>Upwork Job ID: 1690903425450983424</li>
        <li>Last Price Increase: 2023-08-28</li>
    </ul>
</details>

**Comment by daordonez11** [comment] 2023-08-10 15:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
An incorrect step is shown in ReimbursementAccountPage when continue is pressed and there was an error in a different step

### What is the root cause of that problem?
To show the current step the method `fetchData` is called and the step is calculated using `achData.currentStep`. Since this variable is not changing when there is an error it just shows the "last" step that was worked in this case Requestor step instead of Company, where it fails.

### What changes do you think we should make in order to solve the problem?
When there is an issue in the validation or in the submit of the form in `CompanyStep` or basically in any step of the configuration we should reset `achData.currentStep` to the step that failed

### What alternative solutions did you explore? (Optional)

**Comment by b4s36t4** [comment] 2023-08-11 06:32
@hungvu193 i think this is valid because the issue you mentioned does have validation in front end itself but the validation error is coming here if from backend.

**Comment by jliexpensify** [comment] 2023-08-11 10:57
Hi @b4s36t4 - I'm not an engineer but can you explain to me the difference between what @hungvu193 has shared and this issue? Specifically the front-end vs back-end - if the other issues have been closed, why would this one (which seems to be a similar issue) be considered a bug? Thanks!

**Comment by daordonez11** [comment] 2023-08-11 15:15
@jliexpensify basically in the steps of the ticket mentioned what is discussed is about the information that is in the form but they say that since it hasn't been validated there is nothing to do. The difference with this ticket is that here it is validated, it does fail when you try to save and continue(Step 4), hence, the server should be able to store the "failed" step. That is the difference between both tickets. So probably this might be half internal because achData is stored in the server but since we know in the front-end something failed in the form the server should update that as well.

cc @hungvu193 Let me know if I missed something else

**Comment by jliexpensify** [comment] 2023-08-14 01:51
Ok, awesome - thanks @daordonez11! @allroundexperts could you review this [comment](https://github.com/Expensify/App/issues/24371#issuecomment-1674954232) and share your thoughts on whether this needs to be brought internally? It sounds like it could go either way. Thanks!

**Comment by jliexpensify** [comment] 2023-08-21 00:21
Bump @allroundexperts !

**Comment by jliexpensify** [comment] 2023-08-25 02:14
Bumping @allroundexperts for an update!

**Comment by jliexpensify** [comment] 2023-08-27 23:51
Sure thing, asking here: https://expensify.slack.com/archives/C01SKUP7QR0/p1693180274656689

**Comment by daordonez11** [comment] 2023-08-28 04:24
You are right! @allroundexperts If there is already a way of knowing from backend that a step failed it is about updating the step in `achData.currentStep` for it to work in the frontend. If there is not, the only required step from the frontend would be to call a backend service to notify which step failed to update it in the achData. Since there is no current service for it I still think it has to be fixed internally. After my code review the form error is handled in the frontend so I think in the end it is a mix of both things front and backend.

**Comment by jliexpensify** [comment] 2023-08-29 22:25
Hi @grgia ! [It looks like this might be an Internal fix](https://github.com/Expensify/App/issues/24371#issuecomment-1694752157) - could you share your thoughts? Thanks!

**Comment by grgia** [comment] 2023-09-01 13:04
@jliexpensify I'd agree with this assessment

> When there is an issue in the validation or in the submit of the form in CompanyStep or basically in any step of the configuration we should reset achData.currentStep to the step that failed.

**Comment by jliexpensify** [comment] 2023-09-05 00:29
Not overdue! This is now an Internal issue.

**Comment by jliexpensify** [comment] 2023-09-12 00:30
Not overdue, @grgia should we change this to Weekly or Monthly since it's now internal?

**Comment by grgia** [comment] 2023-09-14 10:23
Adding weekly label

**Comment by jliexpensify** [comment] 2023-09-25 04:10
Not overdue

**Comment by jliexpensify** [comment] 2023-10-04 07:06
Not overdue

**Comment by jliexpensify** [comment] 2023-10-16 00:13
Not overdue!

**Comment by jliexpensify** [comment] 2023-10-25 03:05
Not overdue - @grgia should this be a Monthly?

**Comment by grgia** [comment] 2023-11-02 14:16
Yes, making monthly for now

**Comment by jliexpensify** [comment] 2023-11-13 04:17
Not overdue, removed the `Weekly` label

**Comment by jliexpensify** [comment] 2023-12-15 00:14
Not overdue

**Comment by grgia** [comment] 2024-01-17 00:04
not prioritizing currently

**Comment by jliexpensify** [comment] 2024-02-19 23:24
Not overdue!

**Comment by jliexpensify** [comment] 2024-03-15 03:01
Hi @grgia - this came up in my list of issues to assign to a Project/VIP: I can't work out where it fits in. Hoping you can help?

**Comment by jliexpensify** [comment] 2024-03-19 22:49
Heya @grgia - just bumping this one! 

p.s. I'm OOO from 21st to 31st March

**Comment by jliexpensify** [comment] 2024-04-02 09:18
Alrighty, chatted to @grgia via DM and since this is internal and very low priority, we're going to close it for focus on roadmap issues. Thanks!

**Comment by b4s36t4** [comment] 2024-04-02 10:58
@jliexpensify Wouldn't I qualify for the reporting bonus?

**Comment by jliexpensify** [comment] 2024-04-02 22:24
Hi @b4s36t4 thanks for the bump, I'll re-open this and get you paid for $250.

**Comment by jliexpensify** [comment] 2024-04-02 22:28
@b4s36t4 invited you [here](https://www.upwork.com/jobs/~0139e381d87dd152e5)

**Comment by b4s36t4** [comment] 2024-04-02 23:07
Done, thanks!

**Comment by jliexpensify** [comment] 2024-04-02 23:13
Job removed.

**Closed by jliexpensify** 2024-04-02 23:13 UTC
Labels: Engineering, Monthly, Internal, Bug
