### ISSUE TITLE
[$250] mWeb/Safari - Chat - There is a " New messages" badge after deleting a comment while offline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11772] opened 2022-10-12 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/

2. Login with any account
3. Navigate a any conversation
4. Disable the internet connection in the device
5. Tap and hold to view the action menu
6. Tap on the Trash icon to delete the message

## Expected Result:
The text comment still shows with a strike-through indicating it is pending deletion

## Actual Result:
There are messages " New messages" at the top of the screen after deleting a comment while offline.

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Mobile Web - Safari

**Version Number:** 1.2.13-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195430105-2f75caa7-6b6b-4ad2-98c6-d6266d3a202e.mp4

<img src="https://user-images.githubusercontent.com/43996225/195430110-4cd2a7c7-463a-4aa2-9084-708a60923834.jpg" width="40%" height="40%">

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause internal team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by pecanoro** [comment] 2022-10-13 20:07
Oh, this is an interesting bug, a combination of offline first and the new message indicator at the same time haha I was able to reproduce so adding external. 

cc/ @marcaaron

**Comment by marcaaron** [comment] 2022-10-13 20:32
@pecanoro :oh-nothing: the deleting comment while offline flows [can get pretty weird](https://github.com/Expensify/Expensify/issues/228189) and we struggled with them a bit while implemented the Unread Indicators doc 😞 

I would like to make sure this issue is a little clearer though...

>Go to URL https://staging.new.expensify.com/
>Login with any account
>Navigate a any conversation
>Disable the internet connection in the device
>Tap and hold to view the action menu
>Tap on the Trash icon to delete the message

- Is the conversation we are navigating to one that has unread messages?

It seems like from the video that the conversation was already "read".

- Is the message that we are deleting the only unread message?

Also seems like no, but hard to tell.

**Comment by pecanoro** [comment] 2022-10-13 20:53
> Is the conversation we are navigating to one that has unread messages?
Nope, all messages were read before going offline and deleting the message

> Is the message that we are deleting the only unread message?
There is no line showing the last unread message, it just shows the new messages banner. I am assuming that yes, it jumps to the last deleted message.

**Comment by tsa321** [comment] 2022-10-16 00:07
Maybe  all unread indicator errors should be on hold, because Roryabraham will implement new algorithm for unread indicator. Here is slack conversation:

https://expensify.slack.com/archives/C01GTK53T8Q/p1665794707786899

**Comment by AndrewGable** [comment] 2022-10-17 19:42
Awaiting proposals!

**Comment by mvtglobally** [comment] 2022-10-18 11:30
Issue not reproducible during KI retests. (First week)

**Comment by AndrewGable** [comment] 2022-10-21 16:21
If we cannot reproduce, we might want to close, thoughts @isabelastisser ?

**Comment by isabelastisser** [comment] 2022-10-23 01:20
Yes, closing this now.

**Closed by isabelastisser** 2022-10-23 01:20 UTC
Labels: External, Engineering, Daily, Improvement, Help Wanted, Bug
