### ISSUE TITLE
[C+ Checklist Needs Completion] [$500] Inconsistency bug: "Assign task" appear in modal of "+" actions button in thread of flagging

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26229] opened 2023-08-29 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to a new conversation with User B
2. User A sends a message to User B
3. User B selects User A's "Flag Offensive" message -> choose any reason
4. User B replies in thread with Concierge
5. Click "+" button -> it shows "add attachment"
6. Click on any other chat and click back with the Concierge thread

## Expected Result:
User should not be able to assign a task for Concierge.

## Actual Result:
User can assign task in Concierge thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.58-0

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/9446a956-04b5-46e0-b0dc-d78033ca341b

https://github.com/Expensify/App/assets/115492554/909f0e2e-7b02-45e3-b5c5-dbd6e5888b8f

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Le Thi Thu Thuy

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692696877160359

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197b4de7da68bcca2</li>
        <li>Upwork Job ID: 1697572011388342272</li>
        <li>Last Price Increase: 2023-09-08</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Reviewer | 26681642</li>
<li>Pujan92 | Contributor | 26681644</li>
</ul></li>
    </ul>
</details>

**Comment by Pujan92** [comment] 2023-08-29 17:01
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Assign task option enabled for concierge thread chat

### What is the root cause of that problem?
Currently, we do not have a condition for checking the id with concierge or expensify id's.
https://github.com/Expensify/App/blob/9398754f3add40d84c9c84c23b79f3abb6165fa2/src/pages/home/report/ReportActionCompose/AttachmentPickerWithMenuItems.js#L151

### What changes do you think we should make in order to solve the problem?
We can check the weather `participantAccountIDs` contains the CONCIERGE id or we can also consider any expensify id(needs to confirm)
```
const hasIncludedCONCIERGE = _.contains(report.participantAccountIDs, CONST.ACCOUNT_ID.CONCIERGE);
```
and add condition `|| hasIncludedCONCIERGE` for displaying the assign task option.

**Comment by greg-schroeder** [comment] 2023-09-01 11:28
Awaiting proposal review, not overdue

**Comment by Santhosh-Sellavel** [comment] 2023-09-01 18:26
@greg-schroeder 

Less Bandwidth. So unassigning to move this forward as it has proposals already. Assign a new C+ Reapplying `external` label, Thanks!

**Comment by greg-schroeder** [comment] 2023-09-04 12:15
Okay, I will find a new C+

**Comment by jjcoffee** [comment] 2023-09-05 14:56
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-09-06 15:36
Currently none of the proposals address why Assign task only shows after navigating away from the Concierge thread. Care to add that @Pujan92 @Charan-hs?

**Comment by jjcoffee** [comment] 2023-09-06 16:08
@Pujan92 See the issue description's repro steps as well as the videos - only "Add attachment" shows as an option before navigating away from the thread and back. Or has the behaviour changed?

**Comment by Pujan92** [comment] 2023-09-06 17:21
Yes, sometimes it happens and at first glance it seems to be due to optimistic data. But as soon as OpenReport api responds for the thread it allows to show Assign task option. I will still dig more and try to find tomorrow. Thanks!

**Comment by jjcoffee** [comment] 2023-09-11 15:08
Reviewing tomorrow!

**Comment by jjcoffee** [comment] 2023-09-12 14:10
Hmm so from what @Pujan92 is saying in [this comment](https://github.com/Expensify/App/issues/26229#issuecomment-1711658606), threads contain both users as participants, whereas DMs only contain the user you're DMing with. This looks like a regression from [this PR](https://github.com/Expensify/App/pull/24019), as we filter `participantAccountIDs` to remove the current user's account in the first line, but then check length against the unfiltered `participantAccountIDs`.

https://github.com/Expensify/App/blob/0a7aabdd7b089224fbcb3a4cb5905db3e7962d37/src/libs/ReportUtils.js#L483-L486

**Comment by greg-schroeder** [comment] 2023-09-12 14:19
Got it. Awaiting new proposals then!

**Comment by Pujan92** [comment] 2023-09-14 10:33
Thanks @jjcoffee, I have updated my proposal which suggests to correct condition. 

I don't think it is a regression from the mentioned PR bcoz earlier also we were checking `lodashGet(this.props.report, 'participantAccountIDs', []).length === 1` [here](https://github.com/Expensify/App/pull/24019/files#diff-7fa482b2895f4e36a2a3ad8233496489c6de1256a8c992524e2fc072aaba43f8L455-L458)

**Comment by jjcoffee** [comment] 2023-09-14 14:41
@Pujan92 Yeah maybe not technically a regression but it definitely seems like a missed case if they introduced excluding the current user in `reportParticipants`, but then don't continue to use it (I can't think of any other reason for excluding the current user other than chats with multiple users + concierge!).

https://github.com/Expensify/App/blob/8650a9c54ff76025aca25fc2e58df602c829007f/src/libs/ReportUtils.js#L485-L488

All that being said, I think we can now go with @Pujan92's updated [proposal](https://github.com/Expensify/App/issues/26229#issuecomment-1697826231) as the RCA and solution LGTM!

:ribbon::eyes::ribbon: C+ reviewed

**Comment by greg-schroeder** [comment] 2023-09-14 21:16
pinged reporter for upwork profile details

**Comment by thuyle04** [comment] 2023-09-15 00:28
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by Pujan92** [comment] 2023-09-15 19:06
@jjcoffee [PR](https://github.com/Expensify/App/pull/27552) is ready for review!

**Comment by greg-schroeder** [comment] 2023-09-29 05:56
Issue Participants:

Issue reported by: @thuyle04
Contributor: @Pujan92 
C+: @jjcoffee 

Was this issue merged in time to be eligible for the speed bonus? yes
Were their any regressions? no

Payment summary:

Reporter: $50
Contributor: $750
C+: $750

**Comment by greg-schroeder** [comment] 2023-09-29 05:59
@jjcoffee and @Pujan92 paid - Offer sent to @thuyle04

**Comment by greg-schroeder** [comment] 2023-09-29 05:59
@jjcoffee please complete the [checklist](https://github.com/Expensify/App/issues/26229#issuecomment-1731398423) and we'll close this out!

**Comment by jjcoffee** [comment] 2023-09-29 08:39
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/24019
 - The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/24019#issuecomment-1740520844
 - A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A** - just needed more thorough testing.
 - Determine if we should create a regression test for this bug. **No** - low impact.
 - If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by jjcoffee** [comment] 2023-09-29 08:39
@greg-schroeder Checklist complete!

**Comment by cristipaval** [comment] 2023-10-06 11:43
> @jjcoffee and @Pujan92 paid - Offer sent to @thuyle04

Is @thuyle04 paid already? Can we close the issue?

**Comment by cristipaval** [comment] 2023-10-09 21:30
👀

**Comment by thuyle04** [comment] 2023-10-12 02:39
Contributor details
Your Expensify account email: thuy.lethithu@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by greg-schroeder** [comment] 2023-10-12 16:54
Wow, sorry, for some reason it wasn't showing in my upwork UI - I went through and had to pay it directly

**Comment by greg-schroeder** [comment] 2023-10-12 16:54
Taking care of checklist and closing

**Closed** 2023-10-12 16:55 UTC
Labels: External, Daily, Awaiting Payment, Bug
