### ISSUE TITLE
[$1000] Green dot is not removed from LHN when deleting mention

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18848] opened 2023-05-12 16:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Sign in with account A
2. Mention account B from the tab where account A is signed in
3. Switch to the tab where account B is signed in
4. Verify that green dot is displayed on LHN
5. Switch to the tab where account A is signed in
6. Delete the mention
7. Switch to the tab where account B is signed in

## Expected Result: 
Green dot should be removed from LHN
## Actual Result: 
Green dot is not removed even if the mention is deleted

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.13.0
**Reproducible in staging?:** y
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cd0814a0-58f7-44d3-a2fc-5e734300a8c2

https://github.com/Expensify/App/assets/43996225/3eae00b6-a8a5-4eca-970d-8419bdd81969

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Natnael-Guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683803752921809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bab306d114847c77</li>
        <li>Upwork Job ID: 1657154854501494784</li>
        <li>Last Price Increase: 2023-05-12</li>
    </ul>
</details>

**Comment by trjExpensify** [comment] 2023-05-12 22:44
Yup, I can reproduce this on the latest staging and on desktop as well. After deleting the message containing a mention, the green dot persists in the chat. Moving on external. 

CC: @puneetlath

**Comment by trjExpensify** [comment] 2023-05-12 22:47
Heads up, the root cause might be interlinked with the `you` persisting: https://github.com/Expensify/App/issues/18850

**Comment by puneetlath** [comment] 2023-05-13 00:28
This is actually a back-end thing and a case we decided not to support out of the gates.

**Comment by trjExpensify** [comment] 2023-05-13 14:41
Cool, so it needs to come `internal` then, yeah? Do you want to add this issue to some kind of project tracker or is it on your radar somewhere else?

**Comment by puneetlath** [comment] 2023-05-13 21:00
We actually specifically decided not to support editing/deleting considerations for now ([link to convo](https://expensify.slack.com/archives/C01GTK53T8Q/p1682538498480489)). In the next iteration of mentions, we _may_ decide to support it, but that'll be discussed in the design doc. I'm going to go ahead and close this, but feel free to reopen if you disagree!

**Closed by puneetlath** 2023-05-13 21:00 UTC
Labels: External, Daily, Help Wanted, Bug
