### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000] Web - Group user avatar icons re-arrange

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23364] opened 2023-07-21 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to make a new group
2. Select a few group members
3. The new group gets created
4. Profile avatar of users gets re-arranged after few seconds

## Expected Result:
Group members avatars should not re-arrange or flicker

## Actual Result:
Group members avatars re-arranging

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.43-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/11130225-2db6-4457-af6b-64de777022d7

https://github.com/Expensify/App/assets/93399543/d86870d3-ee72-4dbc-924e-d237001d9c8c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @himanshuragi456
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689902556688759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014473a252a569df0c</li>
        <li>Upwork Job ID: 1684209321111580672</li>
        <li>Last Price Increase: 2023-07-26</li>
<li>Automatic offers: </li>
<ul>
<li>honnamkuan | Contributor | 26162998</li>
</ul></li>
    </ul>
</details>

**Comment by ojasjadhav2** [comment] 2023-07-22 03:26
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Group user avatar icons are re-arranging after a few seconds

### What is the root cause of that problem?

Initially, when a group is created the order/arrangement of Icons is in the same order as the user has selected the members in.
The reason being, the Icons are stored in State in this initial order only.
But, when the API returns a response, this order/arrangement is updated to whatever comes in API response.

### What changes do you think we should make in order to solve the problem?

here `icons` is fetched using State data, and later using API response data
https://github.com/Expensify/App/blob/e87ba560c931bbdec9e79f95178ccab1ceee057c/src/pages/home/report/ReportActionItemCreated.js#L53C2-L56C2

We can store the `icons` in a `useMemo` with an empty dependency array.
This will store the initial arrangement of `icons` which was fetched using State data in the cache, and when API response data hits, no update/re-arrangement will happen.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ojasjadhav2** [comment] 2023-07-22 03:32
Contributor details
Your Expensify account email: ojasjadhav456@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cafdb2439c9ee36f

**Comment by ben-macpherson** [comment] 2023-07-26 17:17
It seems to me sortedParticipantDetails uses the .sort method incorrectly. Subtracting strings will always result in NaN causing the order to remain the same. I propose an alternative sort that will work correctly.

**Comment by ben-macpherson** [comment] 2023-07-26 17:20
Contributor details
Your Expensify account email: ben@benmacpherson.dev
Upwork Profile Link: https://www.upwork.com/freelancers/~014c2e3563b80ff02e

**Comment by lschurr** [comment] 2023-07-27 15:27
@mananjadhav could you review the proposals here?

**Comment by akamefi202** [comment] 2023-07-27 22:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
User avatars of the group are being rearranged a few seconds after group creation.

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/e87ba560c931bbdec9e79f95178ccab1ceee057c/src/libs/ReportUtils.js#L768
The frontend sorts group users itself after group creation. But the order is updated by response data from backend after few seconds.

### What changes do you think we should make in order to solve the problem?
The frontend need to sort group users by using the same sorting method as the backend. We need to contact an internal member and figure out the correct sorting method of backend.

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2023-07-28 20:37
Thanks for the proposals folks. I can see more than one proposals have the correct RCA. But I am going to take some help here to identify the expected ordering.

🎀 👀 🎀 C+ reviewed.

**Comment by lschurr** [comment] 2023-07-31 14:25
@grgia are you able to take a looksie at this one?

**Comment by lschurr** [comment] 2023-08-02 17:27
@mananjadhav could you start a Slack conversation to determine the expected behavior?

**Comment by grgia** [comment] 2023-08-03 14:44
apologies for the delay, @mananjadhav couldn't we just sort the optimistic data the same way?

**Comment by mananjadhav** [comment] 2023-08-06 17:57
> couldn't we just sort the optimistic data the same way

@grgia  Can you elaborate what you mean by same way?

**Comment by lschurr** [comment] 2023-08-08 21:09
Bump @grgia :)

**Comment by mananjadhav** [comment] 2023-08-10 03:59
@lschurr @grgia is OOO this week, can we reassign another engineer here please?

**Comment by lschurr** [comment] 2023-08-11 16:21
@cead22 tagging a new engineer since Georgia is OOO

**Comment by lschurr** [comment] 2023-08-14 15:13
@mananjadhav what do we need from Eng on this one?

**Comment by mananjadhav** [comment] 2023-08-14 15:26
What order do we use in the backend to sort? Because if we are trying to match that we will have to know the sort order.

**Comment by lschurr** [comment] 2023-08-14 18:49
Thanks! @cead22 could you take a look at this with us?

**Comment by cead22** [comment] 2023-08-15 01:28
Yes, sorry, I'll review tomorrow!

**Comment by mananjadhav** [comment] 2023-08-16 04:48
Thanks for the comment @cead22. Based on this, yeah I agree @honnamkuan's proposal is good here.

🎀 👀 🎀 C+ reviewed.

**Comment by lschurr** [comment] 2023-09-28 09:23
@mananjadhav could you work on the checklist for this one?

**Comment by lschurr** [comment] 2023-10-02 11:53
@mananjadhav - bump on the checklist [here](https://github.com/Expensify/App/issues/23364#issuecomment-1733284511).

**Comment by lschurr** [comment] 2023-10-02 11:54
Could you add your Upwork profile here @himanshuragi456? I can invite you to the job.

**Comment by lschurr** [comment] 2023-10-02 12:45
Payment summary:

- Bug reporter: @himanshuragi456 @250
- Contributor: @honnamkuan $1000
- Contributor+: @mananjadhav $1000

**Comment by mananjadhav** [comment] 2023-10-02 14:07
@lschurr I don't think we have an offending PR here as the we only worked on the improving the sort order.  But I do think we need a regression test suite here.


**Regression Test**
1. Open the app
2. Click on FAB > New Group
3. Create a new group with several members
4. Validate that when group get created, the member avatars are sorted by their display name / login, and then accountId (if two accounts have the same displayName) 
5. Also ensure that the avatars does not get rearranged and remain in the same position.

wdyt @lschurr @cead22 ?

**Comment by lschurr** [comment] 2023-10-02 14:27
Great, I've requested the regression test be added. Closing this one out.

**Closed by lschurr** 2023-10-02 14:27 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:55
$1,000 payment approved for @mananjadhav based on BZ summary.
