### ISSUE TITLE
[Workspace Feeds] [$50] Change `Cards & Domains` tab to `Domains` in settings

### ISSUE THREAD

**Issue by kevinksullivan** [Expensify/App#45021] opened 2024-07-08 22:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Reproducible in staging?:** Y
**Reproducible in production?:** Y

**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1720038761870689

## Action Performed:
1. Sign up on NewDot
2. Create a workspace
3. Navigate to settings

## Expected Result:
`Cards & Domains` tab should just say `Domains`, since cards will  be supported in NewDot within the workspace. 

## Actual Result:
The tab says `Cards & Domains`. 

## Screenshots/Videos

<img width="387" alt="image" src="https://github.com/Expensify/App/assets/22508290/c554ce13-93ba-4dcd-af6c-dcfeac5c3093">

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b56ebd1169d98c19</li>
        <li>Upwork Job ID: 1816676250720638908</li>
        <li>Last Price Increase: 2024-08-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @DylanDylann</details>

**Comment by kevinksullivan** [comment] 2024-07-08 22:54
also discussing [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720479238044789)

**Comment by kevinksullivan** [comment] 2024-07-08 22:54
No UI changes need so I will take @dubielzyk-expensify off of this.

**Comment by mountiny** [comment] 2024-07-22 21:18
all good Melvin

**Comment by kevinksullivan** [comment] 2024-07-26 03:26
Moving forward, since we are weeks out and we're seeing a bit of confusion among new signups trying to import cards.

**Comment by nkdengineer** [comment] 2024-07-26 03:29
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tab says Cards & Domains.

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

Just change the translation and key here https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/languages/en.ts#L618, and whereever we use it

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-26 03:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The tab says Cards & Domains.

### What is the root cause of that problem?
New feature

### What changes do you think we should make in order to solve the problem?

We can add a new translation key just for `Domains`, then use it in [here](https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/home/sidebar/AllSettingsScreen.tsx#L68). Meanwhile in InitialSettingsPage [here](https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/settings/InitialSettingsPage.tsx#L197), it can stay as `Cards & Domains` with existing translation key

> Once workspace feeds is live

If this means it should show `Domains` only if there's active workspace, otherwise still shows `Cards & Domains`, then we can make the translation key [here](https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/home/sidebar/AllSettingsScreen.tsx#L68) conditional based on if there's any active workspace or not, the check for this can be found in [here](https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/pages/home/sidebar/SidebarScreen/FloatingActionButtonAndPopover.tsx#L464) (`Policy.hasActiveChatEnabledPolicies(allPolicies)`)

### What alternative solutions did you explore? (Optional)
Update the translation key and value here to `Domains` https://github.com/Expensify/App/blob/0559307e0b0fb0d08d454b68a21adf8b984a9553/src/languages/en.ts#L618, and update the key whereever we use it

**Comment by nkdengineer** [comment] 2024-07-26 03:38
> Once workspace feeds is live
> If this means it should show Domains only if there's active workspace, otherwise still shows Cards & Domains

@kevinksullivan Could you clarify on this point? Thanks

**Comment by nkdengineer** [comment] 2024-07-26 03:47
[Proposal updated](https://github.com/Expensify/App/issues/45021#issuecomment-2251899140) to clarify some points

**Comment by kevinksullivan** [comment] 2024-07-26 14:44
> Could you clarify on this point, is the understanding correct? Thanks

@nkdengineer updated OP, since we are doing this now and not waiting for the feature I mentioned.

**Comment by nkdengineer** [comment] 2024-07-26 17:27
> If this means it should show `Domains` only if there's active workspace

[Proposal updated](https://github.com/Expensify/App/issues/45021#issuecomment-2251899140) to remove above optional part because it was confirmed [here](https://github.com/Expensify/App/issues/45021#issuecomment-2252923268) that we do not need it.

**Comment by DylanDylann** [comment] 2024-07-29 08:29
The solution is straightforward. Let's go with @nkdengineer's [proposal](https://github.com/Expensify/App/issues/45021#issuecomment-2251899140) because they go first. I am curious about [AllSettingsScreen](https://github.com/Expensify/App/blob/7af1d37ce797797b1c842f5415a70a78ce041486/src/pages/home/sidebar/AllSettingsScreen.tsx#L68) because I don't see we use this component in anywhere. @nkdengineer Could you help to verify that?


🎀 👀 🎀 C+ reviewed

**Comment by DylanDylann** [comment] 2024-07-29 08:31
@chiragsalian it seems @mountiny will take care of this issue as mentioned [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720523854887879?thread_ts=1720479238.044789&cid=C036QM0SLJK)

**Comment by DylanDylann** [comment] 2024-07-29 08:58
@ShridharGoel Thanks for your reminder. But I think it is so minor, we can handle detail in the PR phase

**Comment by nkdengineer** [comment] 2024-07-29 14:27
@ShridharGoel To be fair, I clearly noted that

> If this means it should show Domains only if there's active workspace

That means it's an optional part of my proposal and will only be applied if the understanding is correct. I also acknowledged that my understanding might not be correct, that's why I put it as an optional part, the main solution still stands. This is a very straight forward issue so I think we don't need to discuss further here, my initial proposal already has all the details needed to get it done.

cc @DylanDylann

**Comment by DylanDylann** [comment] 2024-08-01 09:50
@chiragsalian Bump on your assignment

**Comment by DylanDylann** [comment] 2024-08-01 09:56
@nkdengineer 
> I am curious about [AllSettingsScreen](https://github.com/Expensify/App/blob/7af1d37ce797797b1c842f5415a70a78ce041486/src/pages/home/sidebar/AllSettingsScreen.tsx#L68) because I don't see we use this component in anywhere. @nkdengineer Could you help to verify that?

Wdyt about this point?

**Comment by nkdengineer** [comment] 2024-08-01 17:16
@DylanDylann Yes we indeed don't seem to use that component. It looks like a legacy component, I think we should update it too for consistency, but that's optional.

**Comment by nkdengineer** [comment] 2024-08-01 17:17
Kind bump @chiragsalian for assignment (C+ review comment is [here](https://github.com/Expensify/App/issues/45021#issuecomment-2255320886)). Thx!

**Comment by chiragsalian** [comment] 2024-08-01 20:59
oh sorry i got a bit confused. I thought the reason @mountiny assigned to himself was to tackle it internally since it was a small copy change. I'll ask in slack [here](https://expensify.slack.com/archives/C036QM0SLJK/p1720523854887879?thread_ts=1720479238.044789&cid=C036QM0SLJK) if he's going to work on it or not.

**Comment by mountiny** [comment] 2024-08-03 12:20
Yeah sorry for the confusion, I have asked @kevinksullivan if this is ready to be worked on but I dont think we are ready to remove the `Cards` part yet. 

I wanted to tackle this on my own as its not really a change worth external job and a payout due to its triviality

**Comment by nkdengineer** [comment] 2024-08-05 12:04
@mountiny The issue was made `External` and `Help Wanted` so contributors spent time working on it (and there's [C+ approved proposal](https://github.com/Expensify/App/issues/45021#issuecomment-2255320886)). So we'd appreciate if it remains as `External` 🙏

**Comment by isabelastisser** [comment] 2024-08-05 14:49
Not overdue.

**Comment by anmurali** [comment] 2024-08-06 02:41
Not overdue.

**Comment by DylanDylann** [comment] 2024-08-08 03:11
@mountiny @kevinksullivan Any update here?

**Comment by mountiny** [comment] 2024-08-08 10:41
I dont think we want to make this change yet

**Comment by mountiny** [comment] 2024-08-08 10:42
@nkdengineer I can keep it external but for lower bounty as its trivial

**Comment by trjExpensify** [comment] 2024-08-08 21:22
I agree this should hold on the workspace feeds rollout.

**Comment by JmillsExpensify** [comment] 2024-08-08 22:10
Wait what? Can we please prioritize this? We're confusing lots of users who are looking for personal card import. I don't think this has anything to do with whether workspace feeds are ready or not.

**Comment by JmillsExpensify** [comment] 2024-08-08 22:11
Said differently, I think we should make this change now. `Cards and Domains` is inaccurate so we should fix this ASAP. The feature someone is accessing is domains/domain control. Let's make that clear and change this to `Domains` now, not later.

**Comment by trjExpensify** [comment] 2024-08-08 22:32
>We're confusing lots of users who are looking for personal card import.

Are they? I just know this convo came up on the topic of (coming soon) workspace feed card features in the workspace. At which point, it's confusing to point to card management elsewhere with "Cards & Domains". Until then, we don't have any visibility for card settings. 

Not passionate, we're talking a week or so until we take it out of beta.

**Comment by JmillsExpensify** [comment] 2024-08-08 22:35
Right, but I saying that we don't have card functionality on NewDot either way. Again, looking at Fullstory sessions, this is consistently a point of confusion. People click this button and immediately come back and start clicking somewhere else.

**Comment by mountiny** [comment] 2024-08-08 22:35
Created a draft for this, just simple copy changes https://github.com/Expensify/App/pull/47119

**Comment by JmillsExpensify** [comment] 2024-08-08 22:36
So I don't think this is a solution to anything in particular, so I think we should remove it. Whether or not we have workspace feeds doesn't change anything for me. You still need to create a workspace and then go to More Features to find company feeds regardless.

**Comment by trjExpensify** [comment] 2024-08-08 22:52
>They are looking for something that we don't have in my opinion, which is personal card import.

Alright, or they're just early exploring the features and not ready to connect cards yet. 

>Created a draft for this, just simple copy changes https://github.com/Expensify/App/pull/47119

Ship it 👍

**Comment by mountiny** [comment] 2024-08-08 23:04
Shipped

@nkdengineer sorry this was just quick fix

**Comment by mountiny** [comment] 2024-08-08 23:05
@shawnborton wanted to ask if we should also update the icon for the Domains now that we only link to domains and no cards

<img width="377" alt="image" src="https://github.com/user-attachments/assets/e1b7c778-8df3-4e50-b94e-15b01b63d23b">

**Comment by dubielzyk-expensify** [comment] 2024-08-08 23:31
I like the idea of using the globe icon only here, but I'll let Mr Borton have the call. 
![image](https://github.com/user-attachments/assets/ed9f1a08-859b-4c2e-97a0-125ece8add40)

**Comment by JmillsExpensify** [comment] 2024-08-08 23:36
Agree with the global icon only, though I don't have approval power over Mr. Borton.

**Comment by mountiny** [comment] 2024-08-08 23:52
I can use the Globe icon, I am not Borton though so I am worried to see what might happen

**Comment by mountiny** [comment] 2024-08-08 23:56
<img width="383" alt="image" src="https://github.com/user-attachments/assets/3b024817-6f04-4e7c-92b0-aee085bbd0d6">

**Comment by JmillsExpensify** [comment] 2024-08-09 00:08
Maybe we push the button and if Mr Borton is mad tomorrow we can re-assess.

**Comment by trjExpensify** [comment] 2024-08-09 00:28
See ya'll in detention!

**Comment by shawnborton** [comment] 2024-08-09 11:44
Hi there, Mr. Borton here, and I like where you all landed. Class dismissed.

**Comment by mountiny** [comment] 2024-08-13 15:12
All good to be closed here

**Closed by mountiny** 2024-08-13 15:12 UTC
Labels: Reviewing, External, Weekly, NewFeature, Design, Bug

**Comment by DylanDylann** [comment] 2024-10-01 06:37
@anmurali @mountiny It seems we missed to process payment on this issue

**Comment by mountiny** [comment] 2024-10-02 12:13
@DylanDylann, can you please remind for what the payment is? I only see internal PR with internal review

**Comment by DylanDylann** [comment] 2024-10-02 15:10
@mountiny Ahh, I noticed these comments. Please help to review again 😄 Sorry If I misunderstand your means
- https://github.com/Expensify/App/issues/45021#issuecomment-2268911688
- https://github.com/Expensify/App/issues/45021#issuecomment-2275508478

**Comment by mountiny** [comment] 2024-10-02 16:04
I think this was one line copy change and there was no pr either. sorry that there was miscommunication about if this should be external or not, but I think we should just move ahead for this one as it was not complex task
