### ISSUE TITLE
Android - Room - Creating room offline,infinite loading appears until get online

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37360] opened 2024-02-27 22:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.44-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR ** https://github.com/Expensify/App/pull/34742
## Action Performed:
Prerequisites: Make sure you're a member of a workspace or create one first, Device is Offline
1. On homepage, press ( + ) button and select Start chat
2. Select Room tab
3. Fill the necessary data and then press Create room below
4. Verify if the room was created with the data that you filled on the previous step

## Expected Result:
Room is created

## Actual Result:
Infinite loading appears in blank page (unless getting online again)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3a6a38c1-f40e-434e-929d-0923d556e930

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-27 22:32
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by lanitochka17** [comment] 2024-02-27 22:32
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-02-28 19:51
Thanks! I reached out to @arosiclair in the other GH - https://github.com/Expensify/App/issues/25188 about this to see how to fix it.

**Comment by arosiclair** [comment] 2024-02-28 22:25
I think this bug is unrelated to that PR. Looks like the issue is also already on production:

> Reproducible in production?: Y

**Comment by situchan** [comment] 2024-02-28 22:27
@lanitochka17 can you please retest on latest staging?
This might have been related to Onyx change which was reverted and CP'ed

**Comment by Christinadobrzyn** [comment] 2024-02-29 23:12
asking QA to retest here - https://expensify.slack.com/archives/C9YU7BX5M/p1709233204280349

They can't reproduce so let's close this as done.

**Closed by Christinadobrzyn** 2024-02-29 23:12 UTC
Labels: Daily, Bug

**Comment by lanitochka17** [comment] 2024-03-07 18:15
Issue is not reproducible on the latest build 1.4.48-0


https://github.com/Expensify/App/assets/78819774/6cec4bcc-628c-46bf-abc9-daee793c746d
