### ISSUE TITLE
Web - 'Edit' Button in Paypal account name is not highlighted when the cursor comes near to it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23196] opened 2023-07-19 20:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to settings > Payments
2. Click existing pay pal account name
3. Observe the section appearing with two options "Edit" and "Delete"

## Expected Result:
The 'Edit' button should be highlighted when the cursor comes near to it

## Actual Result:
The 'Edit' button is not highlighted when the cursor comes near to it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.42-21
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/238029bf-76ba-4c46-9298-9000b84d19c6

https://github.com/Expensify/App/assets/93399543/94b33f51-099f-468c-998e-4b2cccb7722e

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Yokabdk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689713081865409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Yokabdk** [comment] 2023-07-20 13:30
@duken0307 @hungvu193 The issue #22658 is only about cancel button for Bank account modal, and for Delete workspace and Remove members. This issue is about the 'Edit' Button. You can see the discussion for better clarification.

**Comment by DanutGavrus** [comment] 2023-07-24 10:37
This Proposal comes from my [alternative solution](https://github.com/Expensify/App/issues/22658#issuecomment-1631246684) on *July 11* on another issue.  

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - 'Edit' Button in Paypal account name is not highlighted when the cursor comes near to it

### What is the root cause of that problem?
The 'Edit' button does not have a *default* style, so it gets no style applied.

### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/82669ae1201f3778986ee26209fb80878f166cbd/src/pages/settings/Payments/PaymentsPage/BasePaymentsPage.js#L453-L469
We should update the first button to:
```js
<Button 
   onPress={this.navigateToAddPaypalRoute} 
   style={[styles.mb4]} 
   text={this.props.translate('common.edit')}
   default
/> 
```
This will work after [this PR](https://github.com/Expensify/App/pull/23464) gets merged, or I could handle this issue as part of that PR too (@Yokabdk).

**Comment by zanyrenney** [comment] 2023-07-24 16:13
Very similar issue - https://github.com/Expensify/App/issues/22658#issuecomment-1648212252 i suspect that issue might fix this one, asked @conorpendergrast for his thoughts as the BZ assignee.

**Comment by zanyrenney** [comment] 2023-07-26 11:36
> We can put that in the PR for compliment since we only need one line code.

CLosing in favour of that earlier issue where this can be tackled.

**Closed by zanyrenney** 2023-07-26 11:36 UTC
Labels: Daily, Bug

**Comment by Yokabdk** [comment] 2023-08-11 21:57
@zanyrenney is this issue has still payment for contributing? I got confused because of melvin-bot's awaiting payment reminder.

**Comment by DanutGavrus** [comment] 2023-08-12 08:00
@Yokabdk For context: this issue was found while fixing https://github.com/Expensify/App/issues/22658, and we have fixed it in the same PR https://github.com/Expensify/App/pull/23464. The payment for the other issue was made.  

I don't know if the guides would imply any payment for reporting/fixing this one, thinking @zanyrenney knows better!
