### ISSUE TITLE
[$250] Chat - Unavailable workspace is displayed on chat header when go to chat while logged out

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47736] opened 2024-08-20 17:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.22-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4874559&group_by=cases:section_id&group_id=229066&group_order=asc
**Email or phone of affected tester (no customers):** gocemate+a1028@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Copy the link of a conversation
2. Log out of the app
3. Navigate to the conversation URL
4. Log in
5. Verify you're redirected to the correct conversation after login
6. Take a look at chat header

## Expected Result:
Unavailable workspace should not be displayed on chat header

## Actual Result:
Unavailable workspace is displayed on chat header when go to chat while logged out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/d5e767cf-6367-4522-b54f-781097eaa531

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01050a994b56365205</li>
        <li>Upwork Job ID: 1828594928061815307</li>
        <li>Last Price Increase: 2024-09-04</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @shubham1206agra</details>

**Comment by lanitochka17** [comment] 2024-08-20 17:57
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-20 17:58
We think that this bug might be related to #vip-vsp

**Comment by stephanieelliott** [comment] 2024-08-28 00:46
I see a lot of bug bug reports but they are either related to focus mode or slow API response. This seems like neither so adding the labels for this to be worked on.

**Comment by nkdengineer** [comment] 2024-08-28 07:57
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unavailable workspace is displayed on chat header when go to chat while logged out

### What is the root cause of that problem?
Sometimes when the user only has a personal policy, the policy data may be available after the report data. Let's see the image below that I logged the `report` data, and `allPolicies` data via `useOnyx` in `HeaderView`

<img width="1512" alt="Screenshot 2024-08-28 at 14 47 46" src="https://github.com/user-attachments/assets/3f68cad7-8cb9-4601-ab24-b549b85f716d">

Then the `policyName` is `Unavailable workspace` briefly
https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/pages/home/HeaderView.tsx#L85

https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/ReportUtils.ts#L746-L748

That leads `renderAdditionalText` being displayed

https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/pages/home/HeaderView.tsx#L114

After the policy data is available, an empty string is returned [here](https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/ReportUtils.ts#L756) and it disappears


### What changes do you think we should make in order to solve the problem?
For this case, let us return `noPolicyFound` because if `returnEmptyIfNotFound` is `true` we always want to display the empty string for the not found policy.

https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/ReportUtils.ts#L746-L749

Or for the DM the `policyID` is `_FAKE_`, we can return early `noPolicyFound` or `empty` if `policyID` is `fake`
### What alternative solutions did you explore? (Optional)

**Comment by stephanieelliott** [comment] 2024-08-30 01:46
Hey @shubham1206agra can you review this proposal?

**Comment by CyberAndrii** [comment] 2024-08-30 07:32
I think this is a duplicate of https://github.com/Expensify/App/issues/44480

**Comment by marcaaron** [comment] 2024-09-04 00:05
>Thanks for the heads up, but I feel @nkdengineer solution is better.

They linked to an issue. Is it a duplicate or not?

**Comment by marcaaron** [comment] 2024-09-04 02:07
Can you please share your opinion with everyone involved in that other issue and see what they say? It's not great to let a separate ticket fix the same bug in a different way. Let's communicate our intentions first.

**Closed** 2024-09-09 22:34 UTC
Labels: External, Daily, Help Wanted, Bug
