### ISSUE TITLE
LHN - The deleted task content shown on LHN for 1:1 Conversation

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#51024] opened 2024-10-17 14:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.50-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5092553
**Email or phone of affected tester (no customers):**  testpayment935+60@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition: User A create task in the group and assign for user who is not a member of the group
Steps
1. Navigate to http://www.staging.new.expensify.com/
2. As assignee user, navigate to the task and take a look on LHN of 1:1 conversation with the task creator
3. Open the task details, Click on the header and delete the task

## Expected Result:
Deleted task shown in both task detail and LHN on both the task and 1:1 Conversation

## Actual Result:
The deleted task content shown on LHN for 1:1 Conversation rather than Deleted task message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/7fc09e6f-80bc-44ae-bf8a-6bb620c208b8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by FitseTLT** [comment] 2024-10-17 16:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - The deleted task content shown on LHN for 1:1 Conversation

### What is the root cause of that problem?
We are returning the task created message here without checking the status of the task here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/OptionsListUtils.ts#L617-L618
### What changes do you think we should make in order to solve the problem?

We should return deleted task copy for deleted task as we do in [taskPreview](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/ReportActionItem/TaskPreview.tsx#L89)
```
 else if (ReportActionUtils.isCreatedTaskReportAction(lastReportAction)) {
        const taskReportID = ReportActionUtils.isAddCommentAction(lastReportAction) ? ReportActionUtils.getOriginalMessage(lastReportAction)?.taskReportID?.toString() ?? '-1' : '-1';
        lastMessageTextFromReport = ReportUtils.isCanceledTaskReport(ReportUtils.getReport(taskReportID), lastReportAction)
            ? Localize.translateLocal('parentReportAction.deletedTask')
            : TaskUtils.getTaskCreatedMessage(lastReportAction);
    
```
### What alternative solutions did you explore? (Optional)
We can take the logic to `getTaskCreatedMessage` function.

**Comment by FitseTLT** [comment] 2024-10-17 17:02
Edited by **proposal-police**: This proposal was **edited** at 2024-10-17 17:01:26 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - The deleted task content shown on LHN for 1:1 Conversation

### What is the root cause of that problem?
We are returning the task created message here without checking the status of the task here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/OptionsListUtils.ts#L617-L618
### What changes do you think we should make in order to solve the problem?

We should return deleted task copy for deleted task as we do in [taskPreview](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/ReportActionItem/TaskPreview.tsx#L89)
```
 else if (ReportActionUtils.isCreatedTaskReportAction(lastReportAction)) {
        const taskReportID = ReportActionUtils.isAddCommentAction(lastReportAction) ? ReportActionUtils.getOriginalMessage(lastReportAction)?.taskReportID?.toString() ?? '-1' : '-1';
        lastMessageTextFromReport = ReportUtils.isCanceledTaskReport(ReportUtils.getReport(taskReportID), lastReportAction)
            ? Localize.translateLocal('parentReportAction.deletedTask')
            : TaskUtils.getTaskCreatedMessage(lastReportAction);
    
```
### What alternative solutions did you explore? (Optional)
We can take the logic to `getTaskCreatedMessage` function.
```
function getTaskCreatedMessage(reportAction: OnyxEntry<ReportAction>) {
    const taskReportID = reportAction?.childReportID ?? '-1';
    const taskTitle = getTaskTitle(taskReportID, reportAction?.childReportName);

    if (isCanceledTaskReport(getReport(taskReportID), reportAction)) {
        return Localize.translateLocal('parentReportAction.deletedTask');
    }
```

**Comment by FitseTLT** [comment] 2024-10-17 17:09
Edited by **proposal-police**: This proposal was **edited** at 2024-10-17 17:01:26 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - The deleted task content shown on LHN for 1:1 Conversation

### What is the root cause of that problem?
We are returning the task created message here without checking the status of the task here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/OptionsListUtils.ts#L617-L618
### What changes do you think we should make in order to solve the problem?

We should return deleted task copy for deleted task as we do in [taskPreview](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/ReportActionItem/TaskPreview.tsx#L89) in `getTaskCreatedMessage`
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/TaskUtils.ts#L54-L56
```
function getTaskCreatedMessage(reportAction: OnyxEntry<ReportAction>) {
    const taskReportID = reportAction?.childReportID ?? '-1';
    const taskTitle = getTaskTitle(taskReportID, reportAction?.childReportName);

    if (isCanceledTaskReport(getReport(taskReportID), reportAction)) {
        return Localize.translateLocal('parentReportAction.deletedTask');
    }
```
### What alternative solutions did you explore? (Optional)
We can take the logic to `getTaskCreatedMessage` function.

**Comment by FitseTLT** [comment] 2024-10-17 17:10
Edited by **proposal-police**: This proposal was **edited** at 2024-10-17 17:01:26 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
LHN - The deleted task content shown on LHN for 1:1 Conversation

### What is the root cause of that problem?
We are returning the task created message here without checking the status of the task here
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/OptionsListUtils.ts#L617-L618
### What changes do you think we should make in order to solve the problem?

We should return deleted task copy for deleted task as we do in [taskPreview](https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/components/ReportActionItem/TaskPreview.tsx#L89) in `getTaskCreatedMessage`
https://github.com/Expensify/App/blob/4a25c36e50b58ef9e5ba8b63cf32132f95a0b005/src/libs/TaskUtils.ts#L54-L56
```
function getTaskCreatedMessage(reportAction: OnyxEntry<ReportAction>) {
    const taskReportID = reportAction?.childReportID ?? '-1';
    const taskTitle = getTaskTitle(taskReportID, reportAction?.childReportName);

    if (isCanceledTaskReport(getReport(taskReportID), reportAction)) {
        return Localize.translateLocal('parentReportAction.deletedTask');
    }
```
### What alternative solutions did you explore? (Optional)

**Comment by joekaufmanexpensify** [comment] 2024-10-17 21:47
Hmm, this is a very niche flow. I don't think it's going to be common that tasks are assigned within a group chat to someone not in the group chat and then deleted. Even then, I would argue there is minimal impact to this. Closing, as I don't think this is something we should be prioritizing changing.

**Closed by joekaufmanexpensify** 2024-10-17 21:47 UTC
Labels: Daily, Bug
