### ISSUE TITLE
[HOLD for payment 2024-12-25] [$250] Distance-Distance field is stuck on pending... and no error shown when updating of waypoints fails

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52248] opened 2024-11-08 10:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Email or phone of affected tester (no customers):** applausetester+kh271000023@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit a distance expense with two waypoints.
4. Go to transaction thread.
5. Go offline.
6. Click Distance.
7. Edit the distance by swapping the position and save it.

## Expected Result:
The distance field will change to "Pending" when editing the distance by swapping in offline mode.

## Actual Result:
The distance field does not show "Pending" when editing the distance by swapping in offline mode.
It shows the same amount but it is grayed out.

## Workaround:
Unknown

## Platforms:

- [x] Android: Standalone
- [x] Android: HybridApp
- [x] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/26a527a5-7a85-4335-811c-6df2fa838894

  </details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021854958931528313891</li>
        <li>Upwork Job ID: 1854958931528313891</li>
        <li>Last Price Increase: 2024-11-22</li>
<li>Automatic offers: </li>
<ul>
<li>FitseTLT | Contributor | 105096400</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by FitseTLT** [comment] 2024-11-08 11:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Distance-Distance field does not show Pending when editing distance by swapping in offline mode

### What is the root cause of that problem?
We are not resetting `comment.customUnit.quantity` in updateWaypoints
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/Transaction.ts#L323-L324
### What changes do you think we should make in order to solve the problem?

We should reset it same as we are doing in saveWaypoints here
https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/Transaction.ts#L90-L93
```
            customUnit: {
                quantity: null,
            },
```
### What alternative solutions did you explore? (Optional)

**Comment by ikevin127** [comment] 2024-11-08 22:43
# Proposal

### Please re-state the problem that we are trying to solve in this issue

The distance field does not show "Pending" when editing the distance by swapping in offline mode.

### What is the root cause of that problem?

The [`getDistanceForDisplay`](https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/DistanceRequestUtils.ts#L173C10-L195) function is responsible for returning either the actual distance or `Pending...` depending on the arguments passed, the key one in our case for showing `Pending...` being `hasRoute`.

 [This](https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/components/ReportActionItem/MoneyRequestView.tsx#L202-L206) is where the function is called and the `hasRoute` is passed. This is what the `hasRoute` function checks:

https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/libs/TransactionUtils/index.ts#L694-L696

In our case the first condition always passes because in [`updateWaypoints`](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/Transaction.ts#L321) we set `geometry.coordinates` to `null`, resulting in `!!transaction?.routes?.route0?.geometry?.coordinates` passing because `coordinates` object exists with `null` value.

The reason why the second condition passes as well is because the `!!transaction?.comment?.customUnit?.quantity` check returns `true` as well since we do have `quantity` calculated already from the current transaction route and when we update it while online we don't reset the parent object as we should.

### What changes do you think we should make in order to solve the problem?

In [`updateWaypoints`](https://github.com/Expensify/App/blob/8a83e2baa1c7ce7ee2c31103574937c0484854be/src/libs/actions/Transaction.ts#L321) set `customUnit` object to `null` since its always [populated](https://i.epvpimg.com/eR6raab.png) by BE upon returning online.

```ts
function updateWaypoints(transactionID: string, waypoints: WaypointCollection, isDraft = false): Promise<void | void[]> {
    return Onyx.merge(`${isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {
        comment: {
            waypoints,
            customUnit: null, // <- Add this line
        },
...
```

##

This change will also account for the following case of distance expense confirmation while offline:

<details>
<summary>Distance Cofirmation Change - Offline</summary>

https://github.com/user-attachments/assets/953fd245-8fbd-4708-8baa-919cfcbebfa7

</details>

##

### Solution result

<details>
<summary>MacOS: Chrome</summary>

https://github.com/user-attachments/assets/0dc013ee-840f-4b9a-9670-a63ba1166f96

</details>

**Comment by ikevin127** [comment] 2024-11-10 11:10
@hoangzinh Thanks for the feedback, however, regarding your decision, quoting from the [proposal template (code)](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md?plain=1):

> ATTN: Contributor+
>
> You are the first line of defense in making sure every proposal has a clear and easily understood problem with a "root cause". Do not approve any proposals that lack a satisfying explanation to the first two prompts. It is CRITICALLY important that we understand the root cause at a minimum even if the solution doesn't directly address it. When we avoid this step, we can end up solving the wrong problems entirely or just writing hacks and workarounds.
> ...
> 3. Choose the first proposal that has a reasonable answer to all the required questions.

I thought we cannot hire a contributor who's proposal's RCA is not clear enough, in this case I'd expect the proposal that provided a clear RCA and working solution to be assigned.

My bad, I didn't know that there are exceptions to those rules. I'll make sure to avoid issues reviewed by you in the future since I usually post proposals with those rules in mind 👍

**Comment by FitseTLT** [comment] 2024-11-10 14:49
I think this issue has pretty clear RCA that's why I put a concise proposal.
It's pretty clear updateWaypoints is called on drag
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/pages/iou/request/step/IOURequestStepDistance.tsx#L519
and the obsolete customUnit data should be cleared and that is what we do for saveWaypoints which I mentioned in my proposal (that's why the problem doesn't occur if we change or add a waypoint from IOURequestStepWaypoint)
I would have made the review's job easier if I put more detail, I'm sorry about that 🙏 , but I thought it was pretty straightforward.

**Comment by FitseTLT** [comment] 2024-11-11 16:55
@hoangzinh Updated

**Comment by FitseTLT** [comment] 2024-11-11 17:01
There is more data in `customUnit` than we need to clear 
https://github.com/Expensify/App/blob/533aed65143e5bb47b9692952995be81368eed7b/src/types/onyx/Transaction.ts#L89-L94
We can't be clearing `customUnitRateID`, for instance.

**Comment by ikevin127** [comment] 2024-11-11 22:27
@hoangzinh It doesn't matter anymore since I just noticed that the same code suggested in the first proposal's solution was just merged in PR:
- https://github.com/Expensify/App/pull/52197

```diff
return Onyx.merge(`${isDraft ? ONYXKEYS.COLLECTION.TRANSACTION_DRAFT : ONYXKEYS.COLLECTION.TRANSACTION}${transactionID}`, {
    comment: {
        waypoints,
+       customUnit: {
+           quantity: null,
+       },
    },
```

which means our issue is not reproducible anymore on dev and soon won't be reproducible on staging either once the PR will be deployed.

**Comment by bfitzexpensify** [comment] 2024-11-15 13:01
Let's fix it!

**Comment by ikevin127** [comment] 2024-11-15 23:39
@hoangzinh @bfitzexpensify This one is complicated, I looked into it for a few hours but I wasn't able to come up with a fix. Maybe we can raise the bounty to get more eyes on the issue and even update the description for clarity.

**Comment by FitseTLT** [comment] 2024-11-25 21:03
@hoangzinh [Updated](https://github.com/Expensify/App/issues/52248#issuecomment-2492563418)

https://github.com/user-attachments/assets/028b6006-6073-41a4-89c5-732cac971e6b

**Comment by FitseTLT** [comment] 2024-11-26 12:15
> @FitseTLT can you share screenshot of `transaction?.errorFields`? Why it's `routes` (not `route`) in this case? And is there any regression bugs if we change it to `routes`? I just double-checked and found that we still reference to `route` recently, for example: #51944

Yes Thanks @hoangzinh  you are right looks like the backend sets `errorFields.route` on bad waypoints entered.
Ok now we have two options 
1. if you agree on the error showing below the map as my latest results we can add `errorFields.waypoints` case in addition to `errorFields.route` here
https://github.com/Expensify/App/blob/8c4661d85b0cfae50b6ab985a20d17c7fcad79f1/src/components/ReportActionItem/MoneyRequestView.tsx#L388
and also we will clear it waypoint error here 
https://github.com/Expensify/App/blob/8c4661d85b0cfae50b6ab985a20d17c7fcad79f1/src/libs/actions/Transaction.ts#L461
2. or we can omit showing error message and just revert the values only on failureData
WDYT

**Comment by FitseTLT** [comment] 2024-11-26 16:09
> Do you mind to share recordings of option 1 & 2? @FitseTLT

@hoangzinh Option 1 will be exactly as [here](https://github.com/Expensify/App/issues/52248#issuecomment-2499027719) and option 2 will only revert the value without showing error.

**Comment by FitseTLT** [comment] 2024-11-27 12:59
@hoangzinh [Done](https://github.com/Expensify/App/issues/52248#issuecomment-2492563418)

**Comment by FitseTLT** [comment] 2024-11-27 13:38
@bfitzexpensify please change the title of the issue to `Distance-Distance field is stuck on pending... and no error shown when updating of waypoints fails`

**Comment by mvtglobally** [comment] 2024-11-29 04:24
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-12-25 14:28
Payment summary:

@FitseTLT paid $250 for contributor work via Upwork ✅ 
@hoangzinh due $250 via NewDot manual request

**Closed by bfitzexpensify** 2024-12-25 14:28 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-12-30 15:44
$250 approved for @hoangzinh
