### ISSUE TITLE
[$250] Room - Pasting long text in description not scrolled to bottom & cursor shown at middle.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45885] opened 2024-07-22 10:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.10
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Go to https://staging.new.expensify.com/home
2. Tap on any room chat (#admin)
3. Paste any long text in compose box and note user scrolled to end showing cursor at end.
4. Tap on header
5. Tap room description
6. Paste the same long text in description field and note user not scrolled to end and cursor not shown at end.
7. Tap private notes
8. Paste the same long text in Private Notes field and note user scrolled to end and cursor shown at end.

## Expected Result:
Pasting long text in description must scrolled to bottom & cursor must be shown at end.

## Actual Result:
Pasting long text in description not scrolled to bottom & cursor is shown in middle of text instead of end.

This happens in task description and in other description field across the app.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/5a995426-49ea-4adc-ae42-a15bccdc1c97

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fba32c1ac87d746</li>
        <li>Upwork Job ID: 1818439983332130443</li>
        <li>Last Price Increase: 2024-09-18</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mollfpr</details>

**Comment by mallenexpensify** [comment] 2024-07-22 21:26
Checking a couple other cursor-related issues
- https://github.com/Expensify/App/issues/42216
- https://github.com/Expensify/App/issues/44259

**Comment by kpadmanabhan** [comment] 2024-07-26 15:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pasting long text in description not placing cursor at end of text 

### What is the root cause of that problem?
Cursor positon is not corrected while pasting text similar to Composer text field. 


### What changes do you think we should make in order to solve the problem?
`useHtmlPaste`  hook to be used in description text field similar to composer and notes text fields

### What alternative solutions did you explore? (Optional)
N.A.

**Comment by kpadmanabhan** [comment] 2024-07-30 10:39
@mallenexpensify : I would like to work on this issue, based on previous work in this area. Please assign this to me.

**Comment by mallenexpensify** [comment] 2024-07-31 00:14
@mollfpr can you review @kpadmanabhan proposal above and the issues I linked above too?
https://github.com/Expensify/App/issues/45885#issuecomment-2243843578

**Comment by mollfpr** [comment] 2024-07-31 14:31
I agree that the @kpadmanabhan solution is the same as the @abzokhattab proposal. It seems using `useHtmlPaste` is fixing the issue, but can we seek a universal solution so it can fix the issue in another place?

**Comment by kpadmanabhan** [comment] 2024-07-31 15:42
@abzokhattab : didnt notice your proposal earlier. sorry for that.

@mollfpr : according to me `useHtmlPaste` itself is a universal solution as it is the central handling for all paste actions for the control passed in. We can add this by default to any text input, unless it is unsubscribed explicitly.

**Comment by mollfpr** [comment] 2024-08-05 19:19
>according to me useHtmlPaste itself is a universal solution as it is the central handling for all paste actions for the control passed in. We can add this by default to any text input, unless it is unsubscribed explicitly.

I mean a solution that can be fixed without applying `useHtmlPaste` every time we want the multiline input.

**Comment by kpadmanabhan** [comment] 2024-08-06 02:25
> I mean a solution that can be fixed without applying `useHtmlPaste` every time we want the multiline input.

An option here is to create `useHtmlPaste` as a global hook for all components that accepts pasting of content from clipboard. An approach similar to https://medium.com/swlh/decouple-your-logic-from-ui-by-creating-your-own-react-hooks-d291fd2d60dc

This will make sure that we handle the paste by default for all components unless we explicitly disable that.

**Comment by mollfpr** [comment] 2024-08-07 05:59
I was thinking that the `useHtmlPaste` could be used in `InputWrapper` instead reapply it in another component that uses `InputWrapper`, because I see that the issue only appears on multiline input with `InputWrapper`.

@kpadmanabhan Could you update your proposal based on your last comment? Thanks!

**Comment by mollfpr** [comment] 2024-08-07 07:19
I am still able to reproduce the issue on web chrome.

**Comment by mollfpr** [comment] 2024-08-07 07:47
>Thanks ... i removed the autoGrowHeight, maxAutoGrowHeightfrom the room description page to see whether this happens when the multiline is only enabled and the same issue is happening it doesn't move the index focus to the last char

So it might be the issue-only case for `InputWrapper`?

**Comment by mollfpr** [comment] 2024-08-14 20:39
@abzokhattab Could you explain why the issue is with `isMarkdownEnabled`?

**Comment by mallenexpensify** [comment] 2024-08-19 23:40
@abzokhattab can you reply to @mollfpr 's comment above? Thx.
> Could you explain why the issue is with `isMarkdownEnabled` ?

**Comment by mallenexpensify** [comment] 2024-08-26 21:23
@mollfpr , 👀 on the above proposal from @dominictb ?

**Comment by mollfpr** [comment] 2024-08-28 17:08
Reviewing 👀

**Comment by mollfpr** [comment] 2024-08-29 17:33
Sorry for the delay 🙏

It's a great explanation for RCA from @dominictb!

>Please note that we have a new refactor PR for web markdown https://github.com/Expensify/react-native-live-markdown/pull/394. I tried to test out the solution with the new version of react-native-live-markdown but it doesn't seem to work, so we might need to provide a patch in E/App before the new version of react-native-live-markdown is deemed stable.

Regarding the above comment, what patch we should add to make your solution work?

**Comment by mollfpr** [comment] 2024-09-05 18:44
Not overdue, still open for proposals!

**Comment by mvtglobally** [comment] 2024-09-09 04:08
Issue not reproducible during KI retests. (First week)

**Comment by mallenexpensify** [comment] 2024-09-11 00:37
@mollfpr and @dominictb , regarding the post from QA not being able to reproduce, can you both attempt reproduction and share your results? If you're able to, please provide vid or screenshots.

**Comment by mollfpr** [comment] 2024-09-11 13:53
I am still able to reproduce the issue, it's only reproducible with long text paragraphs and doesn't have a break-line space at the end of the paragraph. The same things happen for Safari.


https://github.com/user-attachments/assets/fb21d21f-a34d-4060-a392-7f744321ce36

@dominictb Is there a reason we using `scrollIntoView ` from the element interface and replacing our own logic?

**Comment by Skalakid** [comment] 2024-09-12 08:16
@dominictb I'm not sure if bringing back the old solution is a good idea. One of the goals of our refactor was to get rid of scrolling into view by calculating pixels. We wanted to simplify it and use the new structure elements as a base for new approach. We've missed the case when the content of the element is too long, but for sure we can fix this issue by modifying the current solution. My idea for it is to detect if the cursor is outside the view, and just launch `node.element.scrollIntoView(false)` or `node.element.scrollIntoView({block: "bottom"})` to scroll to it

**Comment by mvtglobally** [comment] 2024-09-13 16:37
Issue not reproducible during KI retests. (Second week)

**Comment by joekaufmanexpensify** [comment] 2024-09-16 13:31
Going to try reproducing this today, as it sounds like it may no longer be reproducible?

**Comment by Skalakid** [comment] 2024-09-20 11:02
Hello, I decided to investigate this issue more inside the library since I have more capacity. To fix this issue and overall scrolling into view logic, we have to make some bigger logic changes inside the library. First of all, we don't need to scrollIntoView on every input change or event. We can do it only on the actions that were totally replaced by our custom implementation, like: `onPaste` and `onFocus` and `value` prop changes. The rest of the actions can use the default browser's scroll logic. Thanks to that, Live Markdown Input works and feels more like normal RN TextInput.

After that, we can update our `scrollIntoView` function, so whenever the cursor isn't visible inside the input window, it scrolls to the position of the cursor range. Something like this:

```js
 const selection = window.getSelection();
    if (selection && selection.rangeCount > 0) {
      const range = selection.getRangeAt(0);
      const caretRect = range.getBoundingClientRect();
      const targetRect = target.getBoundingClientRect();

      // In case the caret is below the visible input area, scroll to the cursor position
      if (caretRect.top + caretRect.height > targetRect.top + targetRect.height) {
        targetElement.scrollTop = caretRect.top + caretRect.height - targetRect.top - targetRect.height + target.scrollTop;
      }
    }
```

**Comment by Skalakid** [comment] 2024-09-20 14:10
Here is the PR with the fix inside the `react-native-live-markdown` library: https://github.com/Expensify/react-native-live-markdown/pull/502

**Comment by mvtglobally** [comment] 2024-09-21 04:24
Issue not reproducible during KI retests. (Third week)

**Comment by mallenexpensify** [comment] 2024-09-24 21:57
@Skalakid is working on so I add them as an assignee

**Comment by Skalakid** [comment] 2024-10-04 05:00
Hello, the PR with the bump was reverted. Here I'm bumping the library again

**Comment by mvtglobally** [comment] 2024-10-05 03:07
Issue not reproducible during KI retests. (Fourth week)

**Comment by mallenexpensify** [comment] 2024-10-12 00:15
@Skalakid can you provide an update? Wondering if this is _worth_ fixing, def an edge case bug that's not going to affect many/anyone.

**Comment by Skalakid** [comment] 2024-10-14 07:16
Hello, the [PR with the fix](https://github.com/Expensify/App/pull/50047#issuecomment-2407809682) has been merged so the issue should be fixed now

**Comment by mollfpr** [comment] 2024-11-01 16:30
@mallenexpensify I can't repro the issue anymore. I think we can close this.

**Comment by mallenexpensify** [comment] 2024-11-05 00:00
Thanks @mollfpr , closing.  Comment/reopen if anyone disagrees.

**Closed by mallenexpensify** 2024-11-05 00:00 UTC
Labels: External, Weekly, Bug
