### ISSUE TITLE
[HOLD for payment 2023-10-10] [HOLD for payment 2023-10-09] [$1000] Web - Request money - Request confirmation link automatically changes request money currency to USD

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#24393] opened 2023-08-10 21:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Precondition: Your default currency should not be USD when you click on request money

1. Open the app
2. Click on plus and click on request money
3. Enter any amount and continue, select any user and continue
4. Copy the URL, link should look like: https://staging.new.expensify.com/request/new/confirmation/
5. Logout and paste the URL
6. Login and observe that now currency is changed to USD even though your default currency is different and was not changed during last request

## Expected Result:
App should display default currency of user in request money when we open confirmation link on login

## Actual Result:
App displays USD as currency in request money when we open confirmation link on login

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.53-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/90c074b5-884d-4beb-ad6c-259a6cd499c7

https://github.com/Expensify/App/assets/115492554/bdcc45e8-8bf5-4761-9999-ce541bb0903c

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Dhanashree-Sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691057407426539

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aad4c8cddaf2f5c5</li>
        <li>Upwork Job ID: 1691154081471135744</li>
        <li>Last Price Increase: 2023-08-21</li>
<li>Automatic offers: </li>
<ul>
<li>tienifr | Contributor | 26271380</li>
</ul></li>
    </ul>
</details>

**Comment by ygshbht** [comment] 2023-08-10 23:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Upon refreshing the Request Money confirmation link, the displayed currency defaults to USD regardless of the user's set default currency.

### What is the root cause of that problem?
The default currency for IOUs is USD. When the user initiates the Request Money flow, the currency is updated based on the user's personalDetails when the resetMoneyRequestInfo function is invoked. However, when the user refreshes the page, the personal details have not yet been set and the function responsible for updating this, which is triggered by FAB -> Request Money, isn't called. As a result, the app falls back to the default IOU currency, USD.

### What changes do you think we should make in order to solve the problem?
1. UseEffect Approach: In the component responsible for the Request Money confirmation link, use a useEffect hook to call resetMoneyRequestInfo when the component mounts. This ensures that even if the page is refreshed, the correct default currency is always displayed.

### What alternative solutions did you explore? (Optional)
2. Global Approach: A more global solution would be to invoke the resetMoneyRequestInfo function at a higher-level component that mounts when the user logs in and once the personalDetails have been received. This ensures that the default currency is always in sync whenever the user logs in.
3. URL Storage: Store the currency in the URL itself. This means that regardless of any refreshing or subsequent navigation, the currency remains persistent as it's directly encoded in the URL.
Example URL: https://staging.new.expensify.com/request/new/confirmation/?currency=INR
4. Modify Reset Conditions: Update the shouldReset condition in the NewRequestAmountPage to account for situations where the page might be refreshed, ensuring the correct currency is displayed.

**Comment by sonialiap** [comment] 2023-08-14 18:25
I think the issue is slightly different. The issue is that https://staging.new.expensify.com/request/new/confirmation/ defaults to USD instead of using the profile's selected currency. Here are the steps:

1. Log into an account and set the currency to something not USD (ex: EUR)
2. Click on the FAB > Request Money
3. Confirm the OUI screen shows the default currency (ex: EUR). Exit IOU set up without saving
4. Click on https://staging.new.expensify.com/request/new/confirmation/
5. Confirm that the OUI screen shows USD instead of your default currency

**Comment by ygshbht** [comment] 2023-08-15 07:35
@tienifr nicely elaborates the third point I mentioned
`Global Approach: A more global solution would be to invoke the resetMoneyRequestInfo/ currency change function at a higher-level component that mounts when the user logs in and once the currentUserPersonalDetails have been received. This ensures that the default currency is always in sync whenever the user logs in.`

However, the issue with this approach is that we still see the `$` for some time after page refresh. We need to combine this approach with the URL approach to provide a more robust solution 

https://github.com/Expensify/App/assets/65986357/936c9c0a-4f5e-4473-bbdc-d1653746315d


https://github.com/ygshbht/App/commit/a653b5f714ef12f9a773405348dca1d28a111272

**Comment by ygshbht** [comment] 2023-08-21 20:33
> Thanks for your proposal @ygshbht. I think your main solution would require us to use the logic in every component as highlighted by @tienifr. The alternate solution you mentioned [here](https://github.com/Expensify/App/issues/24393#issuecomment-1678534732) I think is too generic and is completely missing the implementation detail.
> 
> I don't think your 4th solution would work because a user might not add the currency as a query parameter to the url. In that case, we should default to the users default currency which again would be undefined for some time.
> 
> @tienifr Your proposal has all the necessary implementation details. I think we should show a loader until the currency loads.
> 
> @tienifr's [proposal](https://github.com/Expensify/App/issues/24393#issuecomment-1678442687) looks good to me.
> 
> 🎀 👀 🎀 C+ reviewed

That's a very wise decision indeed.
 
I'd like to add some clarifications.

> I don't think your 4th solution would work because a user might not add the currency as a query parameter to the url. In that case, we should default to the users default currency which again would be undefined for some time.

User manually editing the URL is not specific to this issue. They can do that for any URL at their own risk. However, if they navigate using the URL provided by the app, they won't face the isssue. We can only fix what's in our control.

> I think your main solution would require us to use the logic in every component as highlighted by @tienifr. The alternate solution you mentioned https://github.com/Expensify/App/issues/24393#issuecomment-1678534732 I think is too generic and is completely missing the implementation detail.

Yes, it is missing the implementation details. I said we need to "invoke the resetMoneyRequestInfo/ currency change function at a higher-level component that mounts when the user logs in and once the currentUserPersonalDetails have been received" and @tienifr provided the code for it. If @tienifr 's proposal is selected because he focused on one solution and provided the code for it and my other solution of URL editing, even though better for end user, increases code complexity by making changes to several files, the decision won't be wrong indeed.

**Comment by ygshbht** [comment] 2023-08-21 20:54
> @ygshbht You don't need to include every tiny detail but at the same time, you shouldn't propose an alternate solution this abstract.
> 
> I'd leave the final call to @cristipaval!

While i agree that I had not figured out where exactly to reset the IOU after app loads and @tienifr shows the appropriate place where that should be done, i wouldn't say that makes my solution "abstract". It is a very straigtforward and specific solution that only misses adding the code of calling the function at the appropriate place. 

> Global Approach: A more global solution would be to invoke the resetMoneyRequestInfo/ currency change function at a higher-level component that mounts when the user logs in and once the currentUserPersonalDetails have been received. This ensures that the default currency is always in sync whenever the user logs in.

**Comment by cristipaval** [comment] 2023-08-22 20:35
Hmm.. Melvin messed up above, I think it's because you @allroundexperts were not assigned at the time when you picked up the solution.

**Comment by cristipaval** [comment] 2023-08-22 20:35
@tienifr you're all set to open the PR.

**Comment by cristipaval** [comment] 2023-09-18 12:03
The PR is still being reviewed by the C+.

**Comment by situchan** [comment] 2023-09-27 09:02
[PR](https://github.com/Expensify/App/pull/25786) fixing this caused regression - https://github.com/Expensify/App/issues/28280

**Comment by sonialiap** [comment] 2023-10-13 12:09
@situchan to clarify [this comment](https://github.com/Expensify/App/issues/24393#issuecomment-1736998168), did #24393 cause a regression? or is #24393 fixing a regression of the issue you linked?

**Comment by situchan** [comment] 2023-10-13 12:13
#24393 caused #28280

**Comment by sonialiap** [comment] 2023-10-15 04:54
@allroundexperts review, no bonus because of regression = $1000 - please request in NewDot
@tienifr fix, no bonus because of regression = $1000 - paid ✔️ 
@dhanashree-sawant report = $250 - paid ✔️

**Comment by sonialiap** [comment] 2023-10-17 13:58
@allroundexperts please complete the checklist :)

**Comment by sonialiap** [comment] 2023-10-17 13:59
I'm OOO Oct 16-23. Adding leave buddy

Status: waiting for Sibtain to complete the checklist

**Comment by sonialiap** [comment] 2023-10-23 10:58
Back from OOO

Thanks for completing the checklist!

Ah, you're right. I tried looking up regression policy in the [SO](https://stackoverflowteams.com/c/expensify/questions/8590) but either I was looking at an old post or missed this bit. I'll check with the team on what to do in this case since I've already made the payments.

<img width="1067" alt="image" src="https://github.com/Expensify/App/assets/17131195/97950793-8e6c-4d25-b0b0-d3f50b75054b">

**Comment by sonialiap** [comment] 2023-10-23 14:53
I've submitted a refund request to @tienifr and updated the amounts in comment https://github.com/Expensify/App/issues/24393#issuecomment-1763271923

**Comment by sonialiap** [comment] 2023-10-23 15:43
@allroundexperts please make a request in ND for $500

**Comment by JmillsExpensify** [comment] 2023-10-24 17:01
$500 payment approved for @allroundexperts based on comment above.

**Comment by cristipaval** [comment] 2023-10-27 14:47
Are we good to close this one, @sonialiap?

**Comment by sonialiap** [comment] 2023-10-30 13:24
The last remaining step is following up on the refund. But I can sort that out with the issue being closed. Closing

**Closed by sonialiap** 2023-10-30 13:24 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
