### ISSUE TITLE
Web -Chat -Unable to scroll large text in expanded compose box with large text

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11885] opened 2022-10-15 13:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Navigate to any chat
4. Add large text
5. Make a field extension

## Expected Result:
Large texts must be scrolled in the extension field

## Actual Result:
Unable to scroll large text in open format in compose box

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
- Desktop
- 
**Version Number:** 1.2.16-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/195990204-a436b684-e487-46fe-842c-efc534c70745.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** Applause internal team
**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by techievivek** [comment] 2022-10-18 07:29
This indeed is a problem. Once we expand the compose box, we can no longer scroll.

**Comment by techievivek** [comment] 2022-10-20 06:50
Passing it to external contributors to have a look. My guess is it is some styling issue.

**Comment by thesahindia** [comment] 2022-10-20 07:03
Will be fixed by https://github.com/Expensify/App/pull/11608

**Comment by techievivek** [comment] 2022-10-20 07:14
I am keeping it on HOLD because I can see that the PR above will fix this issue. Sorry for the pings.

**Comment by techievivek** [comment] 2022-10-24 07:06
https://github.com/Expensify/App/issues/11885#issuecomment-1285042615 We already have a fix for it so once it is deployed we will be good to close this issue.

**Comment by mvtglobally** [comment] 2022-10-24 18:41
Issue not reproducible during KI retests. (First week)

**Comment by techievivek** [comment] 2022-10-26 08:37
Not overdue. We have put it on hold because we have already fixed this [here](https://github.com/Expensify/App/pull/11608).

**Comment by techievivek** [comment] 2022-10-31 08:09
Not overdue.

**Comment by techievivek** [comment] 2022-10-31 17:56
Not overdue, the issue is on hold as we have a fix [here](https://github.com/Expensify/App/pull/11608).

**Comment by JmillsExpensify** [comment] 2022-11-01 04:41
We should assign someone from Bug Zero to test this one now that https://github.com/Expensify/App/issues/11437 is merged.

**Comment by mvtglobally** [comment] 2022-11-03 03:18
Issue not reproducible during KI retests. (Second week)

**Comment by JmillsExpensify** [comment] 2022-11-03 04:26
@techievivek I think we're good to close this issue now, right?

**Comment by techievivek** [comment] 2022-11-03 04:48
Yep, We are safe to close this now.

**Closed by techievivek** 2022-11-03 04:48 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
