### ISSUE TITLE
[HOLD for payment 2023-07-12] [$1000] Name of member does not update in invite member workspaces when change name

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21325] opened 2023-06-22 16:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login account A and B on 2 devices
2. A create workspace => Click member => invite
3. A input email B
4. Tick B
5. B open setting => profile => display name
6. Change display name
7. In A it is observed that B's name does not change
## Expected Result: 
B's name in the invite screen must update when B changes name
## Actual Result: 
B's name does not change

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/a33e72cb-b244-4daf-9d50-fdda894ac4b4

https://github.com/Expensify/App/assets/43996225/32ac9099-f2e4-472a-9193-2e1e217275fc

**Expensify/Expensify Issue URL:**
**Issue reported by:** @namhihi237
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686839643612879

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e0f66ef0caecefb</li>
        <li>Upwork Job ID: 1673363798457892864</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by narefyev91** [comment] 2023-06-27 07:58
Really rare case - and not sure that many users will make such tests - but anyway - proposal from @s-alves10 looks good to me https://github.com/Expensify/App/issues/21325#issuecomment-1603037699. In all other places we directly working with personal details from onyx - but here options are not connected to it. In my view we should add logic inside componentDidUpdate to track possible changes from onyx and updated selectedOptions.
🎀 👀 🎀 C+ reviewed

**Comment by flodnv** [comment] 2023-06-27 14:07
>In my view we should add logic inside componentDidUpdate to track possible changes from onyx and updated selectedOptions.

👍

**Comment by s-alves10** [comment] 2023-06-27 16:59
@narefyev91 
[PR](https://github.com/Expensify/App/pull/21700) is ready for review

**Comment by flodnv** [comment] 2023-07-03 13:13
I disagree with Melvin. The delay was caused by me being ooo, the PR was ready to merge well before 2 business days had elapsed. This is eligible for the bonus @trjExpensify.

**Comment by trjExpensify** [comment] 2023-07-03 13:54
Yeah, makes sense. I tend to go with the date the C+ approved their PR _providing there aren't further changes requested_. :)

**Comment by trjExpensify** [comment] 2023-07-12 10:12
👋 can we address the checklist please @narefyev91 to proceed with payments here? Thanks!

**Comment by narefyev91** [comment] 2023-07-12 11:10
- The PR that introduced the bug has been identified. Link to the PR - that was not coming from any PR that really introduced a bug - such edge case we not even count in code
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment - no comments
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion - no discussions
- Determine if we should create a regression test for this bug - already have them in QA section

**Comment by trjExpensify** [comment] 2023-07-12 11:23
>Determine if we should create a regression test for this bug - already have them in QA section

Cool, so here we're looking to determine whether a regression test should be created for this issue or not. I think we agree we shouldn't given the precise timing required to run into this bug. With that, I'll proceed to offers and closing this out. 

@s-alves10 @namhihi237, I've sent you both offers [here](https://www.upwork.com/jobs/~015e0f66ef0caecefb).

**Comment by trjExpensify** [comment] 2023-07-12 12:11
Settled up with you both, closing. Thanks!

**Closed by trjExpensify** 2023-07-12 12:11 UTC
Labels: External, Daily, Awaiting Payment, Bug
