### ISSUE TITLE
[$1000] Typing inserts text to main composer and thread report composer when a popover menu is open

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26082] opened 2023-08-28 13:14 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open chat & Send message
2. Hover over the sent message > click on 'Reply in thread' > write & send message
3. Navigate back to the main report where you have sent the message
4. Right click on the message
5. Start typing
6. Open the thread report
## Expected Result: 
Text should only be entered to the main report composer
## Actual Result: 
Text is inserted to the main report and the thread report composer too

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0957f29c-a33d-4c79-bfec-05094505f4f1

https://github.com/Expensify/App/assets/43996225/5460876c-e1a9-4804-9ae1-484b1665c250

**Expensify/Expensify Issue URL:**
**Issue reported by:** @natnael-guchima
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692988650725609

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014345451dc41a8cce</li>
        <li>Upwork Job ID: 1696239303676784640</li>
        <li>Last Price Increase: 2023-09-04</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-08-28 19:14
Moving forward!

**Comment by b4s36t4** [comment] 2023-08-28 19:17
@kevinksullivan I think there are multiple duplicates for these kind of issue. I think you can close this. Reference communication https://expensify.slack.com/archives/C01GTK53T8Q/p1693211004204119

**Comment by kevinksullivan** [comment] 2023-08-28 19:25
Got it, thanks @b4s36t4

**Comment by Natnael-Guchima** [comment] 2023-08-28 19:32
@kevinksullivan you might want to look at @mountiny's  comment on slack: 
[Kavi Could we create a GH for this one with priority? quite odd bug we should squash fast haha](https://expensify.slack.com/archives/C049HHMV9SM/p1693228214155599?thread_ts=1692988650.725609&cid=C049HHMV9SM). Think this is a high priority bug.

**Comment by b4s36t4** [comment] 2023-08-28 19:49
@Natnael-Guchima this is a critical bug, but there are duplicate bugs which are almost all to similar to this bug. You can refer to the communication of above thread.

**Comment by b4s36t4** [comment] 2023-08-28 19:53
@kevinksullivan I think what @Natnael-Guchima said is right, althugh 80% of issue is dupe, 20% is having different context which rightly should be solved. Sorry again^^.

**Comment by Natnael-Guchima** [comment] 2023-08-28 19:55
I checked the slack conversation you have shared, if I am not wrong most them reports talk about that text is entered to composer when user types while a modal or popover is opened. This issue is way more weird. Text is entered to multiple reports at a single time when you follow the reproduction step. But the text should be entered to only the main report where focus is applied when writing.

**Comment by b4s36t4** [comment] 2023-08-28 19:56
Yes @Natnael-Guchima Sorry for misunderstanding.

**Comment by Natnael-Guchima** [comment] 2023-08-28 19:57
No problem at all @b4s36t4 👍

**Comment by b4s36t4** [comment] 2023-08-28 21:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Typing inserts text to main composer and thread report composer when a popover menu is open
### What is the root cause of that problem?
The way we add listeners is causing the issue.

If we see the dependencies of `useEffect` which add event listeners to focus the input are many(deep level). But one of them is causing issue with the listeners (mount & unmount)

https://github.com/Expensify/App/blob/1139e7ca891e3b0b84d6773ef82152adf3083ed4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L337-L346.

Here we have a dependency `isFocused` which will update to `false` whenever we move out from a report. So this updated causes `setUpComposeFocusManager` to update which is causes `useEffect` to add the event listeners.
### What changes do you think we should make in order to solve the problem?
We should only event listeners if we're focused on the navigation.

https://github.com/Expensify/App/blob/1139e7ca891e3b0b84d6773ef82152adf3083ed4/src/pages/home/report/ReportActionCompose/ComposerWithSuggestions.js#L397 here we should add a condition to return.

```jsx
if(!isFocused) return;
```


### What alternative solutions did you explore? (Optional)
NA

## Result

https://github.com/Expensify/App/assets/59088937/c10f1c8d-0570-4434-aad1-1ee99128c835

**Comment by b4s36t4** [comment] 2023-08-28 21:05
@kevinksullivan Please re-open the issue. I'm sorry for the wrong info :)

**Comment by mountiny** [comment] 2023-08-29 09:18
@rushatgabhane can you please triage this one? Thanks

**Comment by kevinksullivan** [comment] 2023-09-13 02:57
Waiting on @joelbettner here

**Comment by joelbettner** [comment] 2023-09-19 17:04
@rushatgabhane I think we should go with @bernhardoj's proposal as it covers more of our bases.

**Comment by kevinksullivan** [comment] 2023-09-21 06:39
@rushatgabhane what do you think?

**Comment by mvtglobally** [comment] 2023-09-28 03:18
Issue not reproducible during KI retests. (First week)

**Comment by kevinksullivan** [comment] 2023-09-29 08:29
Closing unless we can reproduce

**Closed by kevinksullivan** 2023-09-29 08:29 UTC
Labels: Engineering, Daily, Internal, Overdue, Bug
