### ISSUE TITLE
[$250] IOU - Unable to add amount to scan failed IOU

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#40116] opened 2024-04-11 14:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.62-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Issue reported by:** Applause - Internal Team 

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in.
3. Go to the workspace policy expense chat
4. Create a new scan request that will be fail
5. Wait until the scan fails
6. Edit the amount and save

## Expected Result:
Able to add amount to scan failed IOU

## Actual Result:
Unable to add amount to scan failed IOU

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/782c9d16-8f75-481d-985c-c74751013b66

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011e95672f893bbb72</li>
        <li>Upwork Job ID: 1778436945764769792</li>
        <li>Last Price Increase: 2024-04-11</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-11 14:16
We think that this bug might be related to #wave-collect - Release 1

**Comment by kbecciv** [comment] 2024-04-11 14:17
@bfitzexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by james-tindal** [comment] 2024-04-13 12:49
I tried scanning an image with no text in it and it's still pending 40 hours later.
Photo of a receipt is pending after 5 minutes.

**Comment by sufyan-siddiqui** [comment] 2024-04-15 19:53
I tried adding an expense that fails on scan. However, after failing I am not seeing any option to add the amount to the expense, like shown in the video. Is the option to change the amount removed altogether or am I doing anything wrong reproducing the issue?

**Video**

https://github.com/Expensify/App/assets/54620116/619099f0-2f2a-482d-a63f-6154d791c7fa

**Comment by james-tindal** [comment] 2024-04-16 18:18
Tried again. Scan failed. No problem editing amount and merchant. Can't reproduce.

**Comment by bfitzexpensify** [comment] 2024-04-16 21:32
Thanks @james-tindal. Marking this as 'internal' for our team to work on given the nature of the problem

**Comment by bfitzexpensify** [comment] 2024-04-16 22:38
Commenting to satisfy melvin-bot

**Comment by trjExpensify** [comment] 2024-04-18 02:26
@james-tindal just to confirm, was that in track expense or request money? @bfitzexpensify did you check out the logs for that requestID yet?

**Comment by james-tindal** [comment] 2024-04-18 10:10
It was in "request money". Looks like "request money" has been renamed to "submit expense" in staging. Whatever the UI ends up calling it, currently receipt scanning in selfDM / Your Space (track expense) never completes and never allows input to the Amount field.
<img width="65" alt="image" src="https://github.com/Expensify/App/assets/10291002/1e523125-c6fb-4094-a4b5-7f8f9a611f97">

"Request money", now "submit expense", does complete the scan after a couple of minutes, and allows the user to input an Amount. Generally this works fine, but occasionally the server responds with repeated 500 errors on every input attempt.
<img width="80" alt="image" src="https://github.com/Expensify/App/assets/10291002/4e141703-b664-487f-97d7-2a36e231f441">

**Comment by trjExpensify** [comment] 2024-04-18 14:41
Cool, thanks! These are internal links, so sorry in advance. 

[Logs](https://www.expensify.com/_devportal/tools/logSearch/#sort=asc&size=10000&query=request_id%3A%228756c7961c32dd73-LHR%22%20AND%20timestamp%3A%5B2024-04-11T00%3A00%20TO%202024-04-19T23%3A59%5D) for requestID: `8756c7961c32dd73-LHR`

```
Caught unexpected exception: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0) in command UpdateMoneyRequestAmountAndCurrency
Throwing exception with message: 'vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)' from N/A:0
Unhandled exception typename: std::out_of_range, command: UpdateMoneyRequestAmountAndCurrency
```
... which looks like @MonilBhavsar _might_ have fixed yesterday with [this PR](https://github.com/Expensify/Auth/pull/10558), but maybe he can confirm. :)

**Comment by MonilBhavsar** [comment] 2024-04-18 14:49
Yes, `std::out_of_range` exception is fixed now

**Comment by james-tindal** [comment] 2024-04-19 08:09
The scan that was showing the bug in my account has been working normally since yesterday.

**Comment by kbecciv** [comment] 2024-04-19 15:01
Issue is no longer reproduced! 

https://github.com/Expensify/App/assets/93399543/91d1a161-8ae1-449f-9673-11c2164d28c0

**Closed** 2024-04-19 15:02 UTC
Labels: Daily, Internal, Help Wanted, Overdue, Bug
