### ISSUE TITLE
[HOLD for payment 2023-08-03] [HOLD for payment 2023-08-02] [$500]  DEV: Web - Unable to paste copied text into emoji search box

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23502] opened 2023-07-24 19:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Right click any text > Copy
3. Open Emoji picker
4. Click on emoji search text box
5. Attempt to paste copied text into the emoji search text input

## Expected Result:
Text pasted into emoji search text input successfully

## Actual Result:
Emoji search text remains empty after text paste attempt

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev v1.3.44-0
**Reproducible in staging?:** no
**Reproducible in production?:** no 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/385cf3b5-8f7e-42dc-b028-55966b4052be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @honnamkuan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1690183117515199

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014a88b8b12d4216db</li>
        <li>Upwork Job ID: 1683594984549310464</li>
        2023-07-24<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>honnamkuan | Reporter | 25727250</li>
</ul></li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-07-24 21:30
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Unable to paste copied text into emoji search box.

### What is the root cause of that problem?
In `EmojiPickerMenu`, there is no `paste` handler, only have `keydown` handler and `mousemove` handler.
https://github.com/Expensify/App/blob/a906877fed01ddfc32066493ba176c0863b437ab/src/components/EmojiPicker/EmojiPickerMenu/index.js#L149-L201

So user is unable to paste text into emoji search box.
### What changes do you think we should make in order to solve the problem?
We can add `paste` handler in `EmojiPickerMenu`.
```js
    this.pasteHandler = (event) => {
        const text = (event.clipboardData || window.clipboardData).getData('text');
        this.searchInput.value += text;
    }
```
And remove handler in `cleanupEventHandlers`.
```js
    document.removeEventListener('keydown', this.pasteHandler);
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by daordonez11** [comment] 2023-07-24 21:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Copy paste does not work in the EmojiPickerMenu component

### What is the root cause of that problem?
Due to recent changes in the `Composer` component `handlePaste `method now begins with the `event.preventDefault` method:

https://github.com/Expensify/App/blob/a906877fed01ddfc32066493ba176c0863b437ab/src/components/Composer/index.js#L309-L323

This makes it work for the parent/first mounted component but preventing default behavior ends up in preventing other handlers/inputs to work as expected. Hence the expected native handler of the input does nothing.

### What changes do you think we should make in order to solve the problem?

As it was before move `event.preventDefault()` after the validations so it is indeed prevented only if the logic does apply to the current composer, something like this:

```js
 handlePaste(event) {
        const isVisible = this.props.checkComposerVisibility();
        const isFocused = this.textInput.isFocused();

        if (!(isVisible || isFocused)) {
            return;
        }

        if (this.textInput.id !== event.target.id) {
            return;
        }
        event.preventDefault();
```

Video of solution working:

[23470 solution working.webm](https://github.com/Expensify/App/assets/13544910/0deb6960-4f67-4c41-baea-552754389178)


### What alternative solutions did you explore? (Optional)
Create a new handler in the component but is just not tackling it in the root.
PS: I think this might be a regression of [23135](https://github.com/Expensify/App/pull/23135) @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 21:51
@robertKozik check this out https://github.com/Expensify/App/issues/23502#issuecomment-1648661810!

**Comment by mountiny** [comment] 2023-07-24 21:52
Stepping in here as this would be unfortunate regression in staging. Assigning Santosh as the C+ here as they came from the PR with Robert who is now C+ as well.

@StevenKKC thank you for your quick proposal, I must admit I think that @daordonez11 proposal which implements the fix in Composer itself. I will make the reward half here with no urgency bonus given this is a regression but Robert most likely is not online to work on this at this time. Also let's do no reward for C+ given this was a regression from the previous PR. I hope thats understandable.

@daordonez11 would you be able to create the PR and ensure that pasting works correctly with multiple composers open? ie with edit mode you can have multiple composers.

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 21:54
Okay, @mountiny that makes sense!

**Comment by daordonez11** [comment] 2023-07-24 22:02
For sure @mountiny  will definitely have a PR ready by my EOD so you guys can give it a check to avoid the regression in staging. Which probably happens in more scenarios.

cc @Santhosh-Sellavel

**Comment by Santhosh-Sellavel** [comment] 2023-07-24 22:05
@daordonez11 Please test this more carefully, let's make sure we are breaking anything here, thanks!

**Comment by daordonez11** [comment] 2023-07-24 23:35
So 2 things I'm currently checking 
1. Correct composer is indeed selected, but in the edition message the text cursor appears before the text, validating a solution
2. the validation of `this.textInput.id !== event.target.id` does nothing since some elements don't have an HTML id so since both are HTML elements I would recommend changing it to `this.textInput !== event.target` to make it work as expected. 

As soon as I finish validating 1 will provide the PR the rest is working as expected in all platforms / missing iOS will access a mac later tonight :D 

cc @Santhosh-Sellavel @mountiny @robertKozik

**Comment by daordonez11** [comment] 2023-07-25 01:14
Yup just saw 1 was a regression and Aldo just created the revert: https://github.com/Expensify/App/pull/23518
Also, will include 2 since the other validation is practically doing nothing. Creating the PR for validation tomorrow!

**Comment by daordonez11** [comment] 2023-07-25 04:56
Hey guys PR ready https://github.com/Expensify/App/pull/23525 , currently getting http error 429 so couldn't continue testing. Tomorrow I will finish all tests and videos.
I was able to test android, web and mweb but only recorded web and started getting the error. Let me know if any of you guys know how to fix it!

![image](https://github.com/Expensify/App/assets/13544910/83f56022-db0d-47c7-b97e-51c125a582bc)

cc @Santhosh-Sellavel @mountiny

**Comment by daordonez11** [comment] 2023-07-25 06:19
Note: Finished all tests on my PC tomorrow I will mount the mac environment to test in iOS Native but I think everything should work as expected.
cc @mountiny @Santhosh-Sellavel

**Comment by adelekennedy** [comment] 2023-08-04 00:07
@mountiny & company it looks like you just need the payment summary and upwork payment from me here?

**Comment by mountiny** [comment] 2023-08-06 18:43
@adelekennedy correct

**Comment by Santhosh-Sellavel** [comment] 2023-08-06 18:59
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [x]  [@Santhosh-Sellavel] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/23135
* [x]  [@Santhosh-Sellavel] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/23135/files#r1272797697
* [x]  [@Santhosh-Sellavel] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Should have been caught while reviewing. 
* [x]  [@Santhosh-Sellavel] Determine if we should create a regression test for this bug. N/A Just a basic expectation.
* [x]  [@Santhosh-Sellavel] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. N/A
* [x]  [@adelekennedy] Link the GH issue for creating/updating the regression test once the above steps have been agreed upon:

cc: @mountiny if differ on any let me know, thanks!

**Comment by adelekennedy** [comment] 2023-08-06 23:46
Payment Summary
@honnamkuan  - $250 for reporting bonus (paid via Upwork)
@daordonez11 - $500 for fix  (paid via Upwork)
@Santhosh-Sellavel  - $500 for fix (paid via NewDot)

**Closed** 2023-08-07 18:58 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by Santhosh-Sellavel** [comment] 2023-08-07 19:05
> Stepping in here as this would be unfortunate regression in staging. Assigning Santosh as the C+ here as they came from the PR with Robert who is now C+ as well.
> Also, let's do no reward for C+ given this was a regression from the previous PR. I hope thats understandable.

As agreed with [this](https://github.com/Expensify/App/issues/23502#issuecomment-1648677610) [here](https://github.com/Expensify/App/issues/23502#issuecomment-1648679241).

No due in payment for here, thanks!
