### ISSUE TITLE
App crashes and throws unexpected error while splitting bill after closing and reopening account with same email

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20303] opened 2023-06-06 20:16 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Log in to Account A and navigate to the plus sign at the bottom to request money from Account B.
2. Add the desired amount and click "Next."
3. Search for Account B and request the money.
4. Close Account A by navigating to the security settings and clicking on "Close Account" with your email.
5. Wait 10 seconds and reopen Account A.
6. Check that the last request is canceled and the balance is 0.00.
7. Navigate to the plus sign and select "Split Bill."
8. Add the desired amount and click "Next."
9. Select Account B to split the bill with.
## The expected result:- 
money should be successfully split between the two parties
## The actual result:- 
Unexpected error occurs while splitting the bill, even after closing and reopening the account with the same email

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.24-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
[screen-capture (51).webm](https://github.com/Expensify/App/assets/43996225/b4396423-c22b-4cf4-8585-d83fc8b25f67)

https://github.com/Expensify/App/assets/43996225/2ced1695-e988-49a2-8ab4-8af7a6d677c6

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tewodrosgirmaa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685643489148699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~012c0616fb4594d680</li>
        <li>Upwork Job ID: 1669290351620509696</li>
        <li>Last Price Increase: 2023-06-15</li>
    </ul>
</details>

**Comment by tewodrosGirmaA** [comment] 2023-06-07 08:55
Hi @conorpendergrast

**Comment by conorpendergrast** [comment] 2023-06-07 08:55
**Tested with:** 
20303a@conorpendergrast.com
20303b@conorpendergrast.com

Same again! Successfully able to split after closing and reopening 20303a@conorpendergrast.com

<img width="1167" alt="image" src="https://github.com/Expensify/App/assets/5802477/7d92565e-0f89-40e9-aaa2-43ba96b041e3">

**Comment by conorpendergrast** [comment] 2023-06-07 08:56
I also tested what it looks like in the video above, by closing 20303a@conorpendergrast.com, and then splitting the bill while signed in with 20303b@conorpendergrast.com (with 20303a@conorpendergrast.com still closed), but that still successfully split the bill. 

<img width="903" alt="image" src="https://github.com/Expensify/App/assets/5802477/e28daba4-d7f5-4f80-8fdf-c9e87cca7266">

**Comment by tewodrosGirmaA** [comment] 2023-06-07 09:00
Hi @conorpendergrast                                                                                                                                                                   
it is a long process and Did you  follow this step:-                                                                                                                    
Action Performed:
1. Log in to Account A and navigate to the plus sign at the bottom to request money from Account B.
2. Add the desired amount and click "Next."
3. Search for Account B and request the money.
4. Close Account A by navigating to the security settings and clicking on "Close Account" with your email.
5. Wait 10 seconds and reopen Account A.
6. Check that the last request is canceled and the balance is 0.00.
7. Navigate to the plus sign and select "Split Bill."
8. Add the desired amount and click "Next."
9. Select Account B to split the bill with.

**Comment by tewodrosGirmaA** [comment] 2023-06-07 09:03
![image](https://github.com/Expensify/App/assets/118253010/c76149e0-4409-4fd7-b368-8e65321de7da)

**Comment by conorpendergrast** [comment] 2023-06-07 09:04
Yes, I followed those exact steps twice, without any error at all

**Comment by tewodrosGirmaA** [comment] 2023-06-07 09:14
Based on the screenshot you shared, it seems that the initial request was not cancelled by the app as it should have been. However, I am unsure of the reason behind this issue

**Comment by conorpendergrast** [comment] 2023-06-09 19:20
@tewodrosGirmaA Huh, what makes it look like the initial request wasn't cancelled correctly?

**Comment by tewodrosGirmaA** [comment] 2023-06-09 19:44
Hi @conorpendergrast ![image](https://github.com/Expensify/App/assets/118253010/0e3a32fc-5ce7-4767-9aad-d4ade2ebcb24)

**Comment by conorpendergrast** [comment] 2023-06-12 13:28
@tewodrosGirmaA Ah, that was inside the IOU, not in the "main" chat between 20303a@conorpendergrast.com and 20303b@conorpendergrast.com: 

<img width="1071" alt="image" src="https://github.com/Expensify/App/assets/5802477/a93639b8-7503-406c-82d4-452ecc62b434">

**Comment by conorpendergrast** [comment] 2023-06-12 13:39
One last test:
20303c@conorpendergrast.com sent a request to 20303b@conorpendergrast.com


### After closing 20303c@conorpendergrast.com: 

<img width="984" alt="image" src="https://github.com/Expensify/App/assets/5802477/2d94b781-d083-49fe-a519-eb30f5349e13">

### And then sending a split bill from 20303c@conorpendergrast.com to 20303b@conorpendergrast.com: 

<img width="986" alt="image" src="https://github.com/Expensify/App/assets/5802477/f5ca15b4-8723-4338-b3d0-de2061473cc3">


So overall, seems like it all worked, weirdly

**Comment by tewodrosGirmaA** [comment] 2023-06-12 13:40
I see, now I understand, @conorpendergrast.  Thank you

**Comment by conorpendergrast** [comment] 2023-06-12 13:42
So you're still able to reproduce this correct @tewodrosGirmaA?

**Comment by tewodrosGirmaA** [comment] 2023-06-12 14:26
[screen-capture (85).webm](https://github.com/Expensify/App/assets/118253010/65edc012-3d28-42e8-be9b-febf7e16ca84)
Well, I've tried reproducing it and it's still giving me grief. It's like the app has a mind of its own and is determined to drive me crazy! 🤯

**Comment by conorpendergrast** [comment] 2023-06-15 10:23
Alright, I was able to find [internal logs](https://www.expensify.com/_devportal/tools/logSearch/#query=email%3A%22isaacashenafi23%40gmail.com%22%20AND%20blob%3A%22oops%22%20AND%20timestamp%3A%5B2023-06-12T00%3A00%20TO%202023-06-16T23%3A59%5D&index=_all) for isaacashenafi23@gmail.com that show this happening, so we're at least getting somewhere! 

Specifically, the error we're seeing is in [these internal logs](https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%227d62a421dbaf0df5-AMS%22)+AND+timestamp:[2023-06-12T13:04:07.707Z+TO+2023-06-12T15:04:07.707Z]&index=logs_expensify-022771), where what we're trying to do is: 

```
Processing 'PayMoneyRequest' for 'expensify.com' from '95.85.63.9' ~~ command: 'PayMoneyRequest' iouReportID: '206443401677525' chatReportID: '3747912660948463' reportActionID: '6789614094871891257' paymentMethodType: 'Elsewhere' appversion: '1.3.26-1' 
```
And the error we're getting back is: 

```
 Throw ExpException - d1cbd3c64a46b9acc503d06b59a1e863 ~~ message: '406 You can't pay another user's IOU' exceptionMessage: 'Auth PayMoneyRequest returned an error' exceptionFile: '/git/releases/expensify.com/3a24848/lib/Auth.php' exceptionLine: '124' exceptionCode: '406'
```

**Comment by conorpendergrast** [comment] 2023-06-15 10:26
It's not reproducible, and at least we have the answer for what the error is! (`406 You can't pay another user's IOU`). I'm going to move this Internal so we can work out some more details, and to confirm if we need to fix this internal or it can be fixed external. Thanks for persisting with me @tewodrosGirmaA!

**Comment by conorpendergrast** [comment] 2023-06-16 14:43
Oh yes, Internal didn't assign an engineer until today :)

**Comment by mountiny** [comment] 2023-06-19 09:37
There was one APi change recently which might help with this so I would wait and try to retest later in the week if this is still reproducible. It was overwriting the reportIDs to incorrect reportIDs which this might be similar to as the error signals that a wrong iou report has been passed to the PayMoneyRequest

**Comment by conorpendergrast** [comment] 2023-06-20 14:36
@mountiny Thanks! Do you have a link to that API change? I'll put this on hold for that being on production and then I'll re-test

**Comment by mountiny** [comment] 2023-06-20 16:33
This PR its in staging now. Lets wait for another deploy and we can retest again.

**Comment by mountiny** [comment] 2023-06-21 12:31
Forgot to paste the link, apologies https://github.com/Expensify/Web-Expensify/pull/37809

**Comment by conorpendergrast** [comment] 2023-06-22 13:54
Actually, given I was never able to reproduce this, @tewodrosGirmaA can you try reproducing again?

**Comment by tewodrosGirmaA** [comment] 2023-06-22 14:06
Hi @conorpendergrast, the bug I reported is not present in the new version. Thanks

**Comment by conorpendergrast** [comment] 2023-06-22 14:11
Offer sent https://www.upwork.com/nx/wm/offer/25168088

**Comment by tewodrosGirmaA** [comment] 2023-06-22 14:34
Thank you @conorpendergrast, I accepted the offer.

**Comment by conorpendergrast** [comment] 2023-06-22 19:35
Paid, contract ended. All done, and thanks again for your help with all of the testing steps @tewodrosGirmaA!

**Closed by conorpendergrast** 2023-06-22 19:35 UTC
Labels: Engineering, Daily, Internal, Needs Reproduction, Bug
