### ISSUE TITLE
[$250] Composer focus is lost if a new message is received while typing

### ISSUE THREAD

**Issue by isagoico** [Expensify/App#43351] opened 2024-06-10 11:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.81-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** NO

**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1718015667516489

## Action Performed:
Tip: To easily test this, log in with 2 accounts in different devices (e.g: Web & iOS)

1. As account A start typing something in the compose box
2. As account B, sent a message to A while they're typing

## Expected Result:
Compose box focus should remain while receiving a new message. 

## Actual Result:
Compose box focus is lost if the user is typing and a new message is received. 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native 
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/44479856/3c57afd8-a277-49f9-adfd-16bc63808dc6

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b0384bb7db3c3ab2</li>
        <li>Upwork Job ID: 1800145000444915700</li>
        <li>Last Price Increase: 2024-06-10</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Ollyws</details>

**Comment by mountiny** [comment] 2024-06-10 12:36
I dont think this is a backend bug

**Comment by SzymczakJ** [comment] 2024-06-10 14:21
Hey! I’m Jakub Szymczak from Software Mansion, an expert agency, and I’d like to work on this issue!

**Comment by mountiny** [comment] 2024-06-10 14:36
@SzymczakJ Reminder that this is a deploy blocker so please leave frequent updates on your findings for the fix as we will have to cherry pick the fix to staging today

**Comment by SzymczakJ** [comment] 2024-06-10 16:00
looks like this commit causes the bug: https://github.com/Expensify/App/commit/a1ed1abe70dcd303b78ffe75afd09d1b5d82ad8c. I'm continue working on this so maybe we won't have to revert this

**Comment by SzymczakJ** [comment] 2024-06-10 17:36
Let's not be hasty with reverting https://github.com/Expensify/App/pull/43083. I can reproduce bug on commit that merges https://github.com/Expensify/App/pull/43083 into main and I cannot reproduce this bug on the commit before, but reverting https://github.com/Expensify/App/pull/43083 doesn't fix the problem 😬, so I may be mistaken in some way and https://github.com/Expensify/App/pull/43083 isn't the real cause. I need some more time with this bug.

**Comment by luacmartins** [comment] 2024-06-10 18:12
Keep us updated @SzymczakJ

**Comment by luacmartins** [comment] 2024-06-10 21:35
This was fixed by this revert https://github.com/Expensify/App/pull/43431

**Comment by luacmartins** [comment] 2024-06-10 21:38
Fixed in staging. Closing.

**Closed by luacmartins** 2024-06-10 21:38 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Bug
