### ISSUE TITLE
Web - App gets stuck in edit mode and displays 'pre' html block around text while editing and deleting code block in offline mode

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21448] opened 2023-06-23 19:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Turn off your internet connection or trigger force offline
4. Send code block with any text in report
5. Edit the code block
6. Remove all the text, click enter to trigger delete popup and click enter again to trigger delete button (Note that it is important to use enter to trigger delete button)
7. Observe that app is now stuck in edit mode and we can't write anything in it or dismiss it
8. Revisit the report to see that now, app displays 'pre' html tag around the text in place of backticks

## Expected Result:
App should strikethrough the message when we try to delete message in offline mode

## Actual Result:
App is stuck in edit mode with no text and no way to close or add new text and it adds 'pre' html block in place of backticks in message on revisit if we send any code block, edit it, remove the content, press enter to trigger delete popup and press enter again to delete in offline mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31.2

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d9181598-9c40-4452-b417-8658b650e1e3

https://github.com/Expensify/App/assets/93399543/d5802f79-f596-4f83-b953-930be818010a

**Expensify/Expensify Issue URL:** 

**Issue reported by:**  @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686933486555979

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-23 21:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - App gets stuck in edit mode and displays 'pre' html block around text while editing and deleting code block in offline mode
### What is the root cause of that problem?

There are three main events in confirm modal, `onConfirm`, `onCancel`, `onModalHide`.
https://github.com/Expensify/App/blob/0adbf8397252f1b2e2e066fc51cb92462d8b23ac/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L325-L330
When confirm button is pressed `onConfirm` then `onModalHide` events happen. `onModalHide` event's callback change based on which event is called before it. 


Basically when enter is pressed to submit empty edit message when delete confirm modal opens the window focuses in backdrop of modal. And when enter is pressed to confirm delete, first it triggers delete button which is listening to keyboard, and also it triggers click action on backdrop since focus was here. When clicking on backdrop it triggers `onCancel` event.
https://github.com/Expensify/App/blob/9ba7cd33671f61c55e46bece2f358b4db9390642/src/components/Modal/BaseModal.js#L103-L108

 And this happens:
`onConfirm` -> `onCancel` -> `onModalHide` , the problem is that `onCancel` is being called in between of these two events and changes callback of `onModalHide` this both `onConfirm` and `onCancel` actions happen and edit input remains open.


### What changes do you think we should make in order to solve the problem?
We should prevent onClose event from getting triggered when modal is already closing by adding condition here
https://github.com/Expensify/App/blob/b8aeec0bcf2cac06d51129f287f932ba0421ed4e/src/components/ConfirmModal.js#L65
```javascript
            onClose={props.isVisible ? props.onCancel : () => {}}
``` 

Or we can add this condition for every place where `onClose` is called like here:
https://github.com/Expensify/App/blob/9ba7cd33671f61c55e46bece2f358b4db9390642/src/components/Modal/BaseModal.js#L103-L108

### What alternative solutions did you explore? (Optional)

**Comment by tjferriss** [comment] 2023-06-27 21:24
I'm not able to reproduce the bug. The message is struck through as expected.

<img width="1131" alt="Screenshot 2023-06-27 at 14 23 06" src="https://github.com/Expensify/App/assets/8292562/89c74cfb-115e-4c81-bc15-4ec7a47ca065">

**Closed by tjferriss** 2023-06-27 21:24 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
