### ISSUE TITLE
[$500]  Chat - Compose box is shown again after user is in edit mode and dismiss keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35179] opened 2024-01-25 19:39 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.32-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34404
## Action Performed:
Pre-requisite: user must be logged in and have sent a message to any chat
1. Go to a chat where you have sent a message
2. Tap and hold on the message
3. Select "Edit comment"
4. Tap on the box to edit the comment for the keyboard to appear
5. Tap "Done" button on the top right corner of the keyboard

## Expected Result:
tapping the "done" button on the keyboard should close the edited chat message and the keyboard should be dismissed

## Actual Result:
The compose box is shown again after the keyboard is dismissed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/bf07c8c7-4e96-4aed-9617-e83c2aa9b477

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ade0e4b570684292</li>
        <li>Upwork Job ID: 1750604363283750912</li>
        <li>Last Price Increase: 2024-02-08</li>
<li>Automatic offers: </li>
<ul>
<li>ishpaul777 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-01-25 19:40
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by Christinadobrzyn** [comment] 2024-01-26 16:39
oh yep, I can reproduce this, I wonder if this is a regression? I can't find any recently closed GHs that might be linked to this though. Adding External for C+ // team review

**Comment by Christinadobrzyn** [comment] 2024-01-29 19:06
I think we're waiting for proposals unless we can link this as a regression to another job

**Comment by Christinadobrzyn** [comment] 2024-01-30 17:42
@parasharrajat can you review this proposal to see if it will work? https://github.com/Expensify/App/issues/35179#issuecomment-1911836686

**Comment by Christinadobrzyn** [comment] 2024-01-31 20:18
Yep! I'll reach out to the team and get their thoughts on what we want here. I think this is a valid bug because the "done" button essentially doesn't respond or close the edited chat. 



https://github.com/Expensify/App/assets/51066321/f851a48b-68f6-4cd3-9e08-874b20b527ea

**Comment by lanitochka17** [comment] 2024-01-31 21:04
Issue found when executing PR https://github.com/Expensify/App/pull/34404

**Comment by Christinadobrzyn** [comment] 2024-02-03 00:03
Slack [convo](https://expensify.slack.com/archives/C066HJM2CAZ/p1706732856940989) with David- we DO want to fix this but it can be a low priority to #vip-vsb. 

@parasharrajat can you let me know if any proposals will work for this?

**Comment by Christinadobrzyn** [comment] 2024-02-03 00:40
Ah great question @ZhenjaHorbach! We would like the 'Done' button on the keyboard to close the edited message. I'll add that to the OP details.

**Comment by jeremy-croff** [comment] 2024-02-03 05:57
> Ah great question @ZhenjaHorbach!
> 
> We would like the 'Done' button on the keyboard to close the edited message and the keyboard should be dismissed. I'll add that to the OP details.

I don't have access to the slacks to read the convo but:

Tieing the 'Keyboard' done to a submit action only for edit is what you're going for?

The main composer doesn't behave this way, and the edit composer did not behave this way either before https://github.com/Expensify/App/issues/33466#issuecomment-1867223195 either.

If you tie the keyboard done button to the submit of edit, it will be non standard phone behavior.
It's just used to minimize the keyboard.

Examples: www.google.com, type something. Hit 'done' just dismisses keyboard
www.youtube.com, type something. hit 'done' just dismisses keyboard

**Comment by jeremy-croff** [comment] 2024-02-03 06:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The done button doesn't submit the edited message.

### What is the root cause of that problem?
There's no implementation of taking an action on 'Done'

### What changes do you think we should make in order to solve the problem?
We can leverage https://reactnative.dev/docs/textinput#onsubmitediting to catch the event when 'Done' is pressed, to trigger the 'publishDraft" method that actually saves the message. https://github.com/Expensify/App/blob/3ab4e6e12d9ff38e69493321f0d31f032481b373/src/pages/home/report/ReportActionItemMessageEdit.tsx#L409 Edit Component that we want to pass this new prop down from.


### What alternative solutions did you explore? (Optional)

**Comment by Christinadobrzyn** [comment] 2024-02-06 22:50
Hey @parasharrajat let me know if I can help with anything here - are we still troubleshooting the issues or reviewing proposals?

**Comment by Christinadobrzyn** [comment] 2024-02-08 23:16
Thanks @ishpaul777 can you provide an update when you are caught up? Thanks!

**Comment by jeremy-croff** [comment] 2024-02-09 14:52
> Thanks for your proposal @ZhenjaHorbach @jeremy-croff,
> 
> @ZhenjaHorbach Sorry but i dont think you solution is a reliable way, to detect the done button press and looks like a workaround.
> 
> @jeremy-croff do you mind providing a test video and working branch with the solution i dont find it working for me, maybe i am missing something?

I don't mind, but this can be expected at the end of my working day in approx 8 hours. Thanks!

**Comment by jeremy-croff** [comment] 2024-02-10 00:08
> Thanks for your proposal @ZhenjaHorbach @jeremy-croff,
> 
> @ZhenjaHorbach Sorry but i dont think you solution is a reliable way, to detect the done button press and looks like a workaround.
> 
> @jeremy-croff do you mind providing a test video and working branch with the solution i dont find it working for me, maybe i am missing something?

@ZhenjaHorbach's analysis so far seems correct.
https://github.com/Expensify/App/issues/35179#issuecomment-1911836686

The top Done button is not firing the onSubmitEdit event, unfortunately it only fires for the Done button as a submit function ( at the bottom of the keyboard ). No callback identified to listen to the keyboard done button. 

Alternatives I found to control the keyboard accessories like top 'Done' button: https://wix.github.io/react-native-ui-lib/docs/components/infra/KeyboardAccessoryView
But this is getting crazy because it's going against default IOS behavior. the done button is 100% intended to just hide keyboard.

**Comment by Christinadobrzyn** [comment] 2024-02-14 01:22
Ah okay, thanks for testing that @ishpaul777 - I agree this appears to be a default behaviour of iOS Safari. I think we should close this and do nothing for the sake of not creating unidentified regressions. Closing but feel free to let me know if you feel otherwise!

**Closed by Christinadobrzyn** 2024-02-14 01:22 UTC
Labels: External, Daily, Bug
