### ISSUE TITLE
Web - Chat - Emoji is entered twice when entering via Windows OS keyboard

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35339] opened 2024-01-29 23:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
 
**Version Number:** v1.4.33-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to any chat.
2. Open Windows OS emoji keyboard via Windows key + "."
3. Select any emoji.

## Expected Result:
Each selection enters emoji once.

## Actual Result:
Each selection enters emoji twice.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e6452c5c-d2a3-4d42-900a-cec4d117952c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by kbecciv** [comment] 2024-01-29 23:25
We think that this bug might be related to #vip-vsb
CC @quinthar

**Comment by jasperhuangg** [comment] 2024-01-30 00:05
Unfortunately I don't have a PC that can reproduce this issue–it seems relatively minor and not worth blocking deploy on.

**Comment by situchan** [comment] 2024-01-31 12:42
I have Windows and reproduced.
@aswin-s can you please check this? This came from #30955 

The root cause is that `onChangeText` is called twice. We should prevent 2nd call.

**Comment by aswin-s** [comment] 2024-01-31 12:53
@situchan. Sure I'll have a look at this.

**Comment by aswin-s** [comment] 2024-01-31 22:38
@situchan Here is what I found.

Seems like a quirk with Windows emoji picker. If we append any character to the emoji (whitespace in this case), it triggers a second onChange with the same emoji added again. Also this happens only when the emoji picker is set to stay open. If we change the setting to auto close, it doesn't happen any more. 

<img src="https://github.com/Expensify/App/assets/6880914/803d646b-2616-4dfa-a069-c31fa0aaf713" width="300"/>

Also a quick web search reveals some other apps like Discord, Youtube comments also facing same issue. Infact I could reproduce it myself in YouTube comments section.

One way to fix this would be to add a debounce to prevent the duplicate onChange event trigger. The wait time needs to be only as small as `1ms` to fix the issue without interfering with regular onChange events. 

```tsx
 const onChangeText = useCallback(
        (commentValue) => {
            const debounced = _.debounce(updateComment, 1, true)
            debounced(commentValue, true);
...
  }
}, [updateComment]);
```

If this sounds reasonable I'll raise a PR.

**Comment by situchan** [comment] 2024-02-01 04:29
I understand there's no straightforward solution but we can also open for better solutions.

**Comment by sophiepintoraetz** [comment] 2024-02-01 04:39
Adding the help label in case there are other thoughts but @flodnv and @mollfpr, do you have thoughts on @aswin-s's [solution](https://github.com/Expensify/App/issues/35339#issuecomment-1920104116), given you reviewed the [original PR](https://github.com/Expensify/App/issues/35339#issuecomment-1919033080)?

@situchan - do you have capacity to for me to assign you as C+?

**Comment by situchan** [comment] 2024-02-01 04:40
@sophiepintoraetz yes, sure

**Comment by conorpendergrast** [comment] 2024-02-02 11:47
I am not convinced that we should fix this; it's only affecting Windows which is not one of our supported platforms. I'll sense-check that via Slack and will come back to this

**Comment by conorpendergrast** [comment] 2024-02-02 13:50
Yeah, cool. Given we both agree, I am going to close this out as a do-nothing situation. Thanks for your thoughts @situchan

**Closed by conorpendergrast** 2024-02-02 13:50 UTC
Labels: Engineering, Daily, Bug
