### ISSUE TITLE
[Awaiting Payment][$1000] Web - URL preview not removed when editing a chat

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21191] opened 2023-06-21 11:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any chat
2. Send website URL (ex. google.com)
3. Observe the site preview thumbnail
4. Hover over message > click Edit Comment > write a message 
5. Observe the URL preview remains

## Expected Result:
The preview should be gone after editing the message

## Actual Result:
Preview is visible after editing the message 

## Workaround:
Uknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7a43b056-0bfb-4188-adc2-7b6e1ecbbbab

**Expensify/Expensify Issue URL:**

**Issue reported by:** @niravkakadiya25

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686727685589039

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0164e3fa7f55938949</li>
        <li>Upwork Job ID: 1671601917583003648</li>
        <li>Last Price Increase: 2023-07-28</li>
    </ul>
</details>

**Comment by StevenKKC** [comment] 2023-06-21 14:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
After editing the link to a simple message, the site preview does not disappear.

### What is the root cause of that problem?
The site preview for the link is displayed in the `LinkPreviewer`.

But after editing the link, the `linkMetadata` is not updated accordingly.
This is the main reason why the site preview does not disappear.

### What changes do you think we should make in order to solve the problem?
When we update the comment, we should delete `linkMetadata` in `editReportComment`.
```
    const optimisticReportActions = {
        [reportActionID]: {
            pendingAction: CONST.RED_BRICK_ROAD_PENDING_ACTION.UPDATE,
            message: [
                {
                    ...originalMessage,
                    isEdited: true,
                    html: htmlForNewComment,
                    text: reportComment,
                },
            ],
            linkMetadata: [],
        },
    };
```
### What alternative solutions did you explore? (Optional)
None.

**Comment by Christinadobrzyn** [comment] 2023-06-21 19:32
I can reproduce - adding External label

**Comment by Christinadobrzyn** [comment] 2023-06-23 23:11
@eVoloshchak can you review the proposals when you have a moment? Thank you!

**Comment by eVoloshchak** [comment] 2023-06-26 20:06
@StevenKKC's [proposal](https://github.com/Expensify/App/issues/21191#issuecomment-1600928191) looks good to me!
Both proposals are pretty similar and were posted very closely on terms of time, so let's proceed with the first proposal

🎀👀🎀 C+ reviewed!
cc: @Christinadobrzyn

**Comment by Christinadobrzyn** [comment] 2023-06-26 22:46
Hey @MonilBhavsar Can you give your thoughts on ^ https://github.com/Expensify/App/issues/21191#issuecomment-1608164762

**Comment by MonilBhavsar** [comment] 2023-06-29 07:05
Sorry for delay. Catching up from ooo...
@eVoloshchak I think I agree with @hungvu193 's comment here https://github.com/Expensify/App/issues/21191#issuecomment-1608535018
Could you please take a look

**Comment by StevenKKC** [comment] 2023-06-29 07:44
@MonilBhavsar @eVoloshchak 
@hungvu193 's proposal clear the linkMetadata if newComment doesn't have the urls.
If newComment have the urls, but is difference with original urls, this can't update preview.
I.E. if we edited message from `google.com` to `slack.com`, because the new comment have a url, @hungvu193 's proposal doesn't work.

I don't agree my proposal will cause another bug.
If we clear linkMetada when editing, `expandURLPreview` will generate preview again next time.
This is the best way that let `expandURLPreview` handle the rest work.
Adding additional checking maybe cause another bug.

**Comment by StevenKKC** [comment] 2023-06-29 09:07
@hungvu193 If we change google.com to simple message as described in this issue, then will appear simple message and google.com preview together until expandURLPreview returns?

**Comment by StevenKKC** [comment] 2023-06-29 10:27
```js
    // update the linkMetaData if newComment doesn't have the urls.
    if (_.isEmpty(urls)) {
        optimisticReportActions[reportActionID].linkMetadata = [];
    }
```
In your proposal, if we change google.com to slack.com, then does not clear `linkMetadata`, and will appear `slack.com` message and `google.com` preview together until `expandURLPreview` returns.
Furthermore if `expandURLPreview` fails, or in offline, then `google.com` preview will remains in screen.

**Comment by eVoloshchak** [comment] 2023-07-02 19:50
> If we always clear our message when editing, this will cause another bug when you edit your message from this link to similar link. IE you edited your message from google.com to google.com hello. So if we already had some urls in our message, let expandURLPreview handle the rest instead of clearing them.

@hungvu193, could you elaborate on this, please? 
I can't reproduce with the said proposal applied

https://github.com/Expensify/App/assets/9059945/dd29e1dd-87be-44cd-9cb8-abd0c5647fab

As a side note, we should wait for https://github.com/Expensify/App/issues/20832 to be fixed before fixing this issue, it makes testing this very limited

**Comment by StevenKKC** [comment] 2023-07-04 18:41
> Anyway, I don't think we should clear linkMetadata everytime, because if we already previewed google.com, then we edited comment to google.com 1, preview will be disappeared and never appeared again.

Preview will be fetched by `expandURLPreview` next time. Why never appear again?
![Annotation 2023-07-04 143922](https://github.com/Expensify/App/assets/131836113/62dcf3b6-1157-4fe7-89a5-fdf04b5a9108)

**Comment by MonilBhavsar** [comment] 2023-07-05 07:05
@eVoloshchak are good to approve a proposal here?

**Comment by MonilBhavsar** [comment] 2023-07-06 16:37
Thanks! Putting it on HOLD then

**Comment by StevenKKC** [comment] 2023-07-07 05:55
I think clear `linkMetadata` in `expandURLPreview` would be better.
```js
function expandURLPreview(reportID, reportActionID) {
    API.write(
        'ExpandURLPreview', {
            reportID,
            reportActionID,
        },
        {
            optimisticData: [
                {
                    onyxMethod: Onyx.METHOD.MERGE,
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${reportID}`,
                    value: {
                        [reportActionID]: {
                            linkMetadata: [],
                        },
                    }
                },
            ],
        }
    );
}
```

**Comment by MonilBhavsar** [comment] 2023-07-14 06:34
How? https://github.com/Expensify/App/issues/20832 is still on HOLD, no?

**Comment by MonilBhavsar** [comment] 2023-07-14 07:07
I am also seeing them lately. Would comment on the held issue to clarify

**Comment by Christinadobrzyn** [comment] 2023-07-14 19:36
I'm going to be ooo until August 31st so going to unassign and assign a new teammate. 

At this time, I think we're deciding if this should still be on hold? @MonilBhavsar and @hungvu193

**Comment by flaviadefaria** [comment] 2023-07-17 09:33
@MonilBhavsar can you clarify is this should be on hold or not? If yes, then I'll switch to weekly.

**Comment by eVoloshchak** [comment] 2023-07-17 09:34
@flaviadefaria, this is still on HOLD for https://github.com/Expensify/App/issues/20832 (which in turn is also on hold)

**Comment by StevenKKC** [comment] 2023-07-20 19:41
@eVoloshchak @MonilBhavsar 
I think we should consider following case.
If user A send a message 'google.com' to user B, user A and user B will both see the google preview.
Then, if user A edits a message to simple text or other link, user B will see the updated message, but the link preview will not be updated.

I updated [my proposal](https://github.com/Expensify/App/issues/21191#issuecomment-1600928191) by considering above case.

**Comment by MonilBhavsar** [comment] 2023-07-21 06:27
This is off hold now

**Comment by flaviadefaria** [comment] 2023-07-24 11:42
Now that this is off hold do we have a proposal to move forward with?

**Comment by eVoloshchak** [comment] 2023-07-25 18:13
Re-reviewing proposals tomorrow as a first priority

**Comment by eVoloshchak** [comment] 2023-07-31 08:05
Тot overdue, this needs an internal engineer, looks like it's the issue with the back end
@flaviadefaria, could you assign an engineer to this? Thanks

**Comment by flaviadefaria** [comment] 2023-07-31 08:17
@MonilBhavsar are you taking this on since you're assigned to the GH or should I re-apply the engineering label?

**Comment by MonilBhavsar** [comment] 2023-07-31 08:25
Yes, making it internal and taking a look

**Comment by MonilBhavsar** [comment] 2023-07-31 11:34
I have pushed a PR in internal repo. Thank you everyone for good discussion on this issue 🙇

**Comment by Christinadobrzyn** [comment] 2023-07-31 18:44
back from ooo - I'll take this back @flaviadefaria - thanks for handling it for me. 

@MonilBhavsar can we move this to weekly while the PR is under review?

**Comment by MonilBhavsar** [comment] 2023-08-01 06:26
PR is merged.
And since this was internal, we have one payment for issue reporter - @niravkakadiya25

---

And add regression tests for URL preview messages - 

1. Send a message with url - `expensify.com`
2. Verify link preview is displayed
3. Edit that message and remove the link - `expensify.com`
4. Ensure link preview is also removed
5. Send a message with two url's - `expensify.com` and `google.com`
6. Verify both link previews are displayed
7. Edit that message and remove one link - `google.com` and verify preview of that link is removed
8. Edit that message and remove another link too - `expensify.com` and verify preview of that link is removed
9. Send a message with url - `slack.com`
10. Edit that message to `expensify.com`
11. Verify link preview is also updated

**Comment by Christinadobrzyn** [comment] 2023-08-01 20:02
Sorry for all the labels, trying to get an Upwork job auto-created since the original one for this is closed now. Didn't work. 

Manually created a job in Upwork 
Internal job- https://www.upwork.com/ab/applicants/1686465413539557376/job-details
External job- https://www.upwork.com/jobs/~01300e05a1b86d26fc

@niravkakadiya25 - I sent you an offer for $250 as reporter - can you please accept so I can pay you?
@eVoloshchak are we paying you through NewExpensify? The payment will be $1000, correct?

Regression test here - https://github.com/Expensify/Expensify/issues/304725

**Comment by Christinadobrzyn** [comment] 2023-08-03 18:01
Per this comment https://github.com/Expensify/App/issues/21191#issuecomment-1659647275

Paid @niravkakadiya25 $250 as reporter

Closing this GH

**Closed by Christinadobrzyn** 2023-08-03 18:01 UTC
Labels: Engineering, Weekly, Internal, Awaiting Payment, Bug
