### ISSUE TITLE
[$1000] Workspace - Members list is shown as empty when removing invalid phone number account from workspace

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#24666] opened 2023-08-16 22:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace or open an existing one
2. Open the workspace & click on "Members"
3. Click on 'Invite' button
4. Search for an invalid phone number ([+2523234211](tel:+2523234211))
5. Select the user > click on "Next" > click on "Invite"
6. Select the user & click on the "Remove" button

## Expected Result:
 Only the invalid phone number account user should be removed

## Actual Result:
All members are **shown as** removed from the list (ie: Members list is shown as empty) until you refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [x] MacOS / Desktop

**Version Number:** 1.3.54.11

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/2c285f90-0153-4b55-af2a-68ca0c7eddd4

https://github.com/Expensify/App/assets/78819774/b67e9c89-5e06-4704-9100-efae0e03c597

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-Guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691436250535479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aaf61408c86eca7a</li>
        <li>Upwork Job ID: 1692098122236555264</li>
        <li>Last Price Increase: 2023-09-07</li>
    </ul>
</details>

**Comment by DylanDylann** [comment] 2023-08-17 04:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Admin is removed when removing invalid phone number account from workspace
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
We should disable checkbox of faulty users and even checkbox all if there are no other members
https://github.com/Expensify/App/blob/e043331def1babf5c70021a22043faed858f38d0/src/pages/workspace/WorkspaceMembersPage.js#L297
https://github.com/Expensify/App/blob/e043331def1babf5c70021a22043faed858f38d0/src/pages/workspace/WorkspaceMembersPage.js#L393
In 2 places, we should add `|| !_.isEmpty(item.errors)` to disable checkbox button if there is an error
### What alternative solutions did you explore? (Optional)

**Comment by conorpendergrast** [comment] 2023-08-17 08:53
I've tweaked the effect slightly, as the admin isn't actually removed from the workspace - the members list shows as empty. If you refresh, the members list is corrected.

**Comment by wardgbn** [comment] 2023-08-17 11:58
I was able to fix the issue on my local dev machine, is the issue still open or already assigned to someone else? because upwork job do not show hired for this issue
Thank you

**Comment by wardgbn** [comment] 2023-08-17 12:02
Contributor details
Your Expensify account email: wardgbn@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~018fbb1fdad17bd44e

**Comment by yh-0218** [comment] 2023-08-17 14:24
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Members list is shown as empty when removing invalid phone number account from workspace
### What is the root cause of that problem?
We call same function about error members.
### What changes do you think we should make in order to solve the problem?
We have to call different function when user have error.
https://github.com/Expensify/App/blob/9348d53a098216ce20e66ccd852c3f96a35ba687/src/pages/workspace/WorkspaceMembersPage.js#L186-L188
Add this code on L186
```
 _.each(selectedEmployees, item => {
            if (!_.isEmpty(props.policyMembers[item].errors)) {
                if (item.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
                    Policy.clearDeleteMemberError(props.route.params.policyID, item.accountID);
                } else {
                    Policy.clearAddMemberError(props.route.params.policyID, item.accountID);
                }
                const accountIDsToRemove = _.without(selectedEmployees, item.accountID);
            }
        })
```
### What alternative solutions did you explore? (Optional)

**Comment by wardgbn** [comment] 2023-08-17 14:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
when removing a selected invalid member from the workspace members list all members dissapeared from the list (non selected members are not actually removed and they are still there if you refresh)

### What is the root cause of that problem?
I think the problem is in the PHP API code and not Expensify App code, 
specifically:
`api?command=DeleteMembersFromWorkspace`
I traced what we send/recive from the api and how we update Onyx, incase of valid and invalid member we send the same request to the api, 
but in case of an invalid member the api return:
```
{
      "onyxMethod": "merge",
      "key": "policyMembers_C04F2575E0F91F8E",
      "value": []
},
```
While for valid member removal the api returns
```
  {
    "onyxMethod": "merge",
    "key": "policyMembers_C04F2575E0F91F8E",
    "value": {
      "15273587": null
    }
  },
```
merging empty array when remove invalid member is the root cause of that problem

### What changes do you think we should make in order to solve the problem?
I need access to the php API code and I will fix it there

### What alternative solutions did you explore? (Optional)
I can handle this specific case where we remove invalid member and the api return empty array by changing the array to the right form before saving the response in onyx, but I think it still better to fix it in the API code

**Comment by abdulrahuman5196** [comment] 2023-08-23 18:16
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-08-23 18:24
@conorpendergrast Curious question on the behaviour, Should we disable the checkbox for invalid entry? Because close will anyways remove it?

**Comment by conorpendergrast** [comment] 2023-08-31 16:17
@abdulrahuman5196 Sorry, for [this question](https://github.com/Expensify/App/issues/24666#issuecomment-1690434567), yes let's disable the checkbox for invalid entry

**Comment by conorpendergrast** [comment] 2023-09-04 13:08
Do we need anything else here to select and move forward with a proposal?

**Comment by conorpendergrast** [comment] 2023-09-08 13:05
@abdulrahuman5196 Bump on proposal reviews and selection please!

**Comment by wardgbn** [comment] 2023-09-09 08:50
@abdulrahuman5196 can you check my proposal? the issue is ineed in the backend php code 
https://github.com/Expensify/App/issues/24666#issuecomment-1682406036

**Comment by DylanDylann** [comment] 2023-09-11 11:12
@abdulrahuman5196 We just confirm the expected [here](https://github.com/Expensify/App/issues/24666#issuecomment-1701343822) Could you help to review the proposal?

**Comment by abdulrahuman5196** [comment] 2023-09-11 18:48
Reviewing now

**Comment by abdulrahuman5196** [comment] 2023-09-11 18:57
@DylanDylann 's proposal here https://github.com/Expensify/App/issues/24666#issuecomment-1681609387 first mentioned the behaviour of disabling the checkbox.

@DylanDylann But the `WorkspaceMembersPage` has drastically changed due to recent refractor, could you kindly update your proposal as per the latest functionality of `WorkspaceMembersPage`.

**Comment by DylanDylann** [comment] 2023-09-12 03:03
@abdulrahuman5196 [Updated proposal](https://github.com/Expensify/App/issues/24666#issuecomment-1681609387)

**Comment by mvtglobally** [comment] 2023-09-13 17:18
Issue not reproducible during KI retests. (First week)

**Comment by DylanDylann** [comment] 2023-09-14 03:51
@conorpendergrast @abdulrahuman5196  It seems that some recent changes from BE fixed this bug. But as you confirmed [here](https://github.com/Expensify/App/issues/24666#issuecomment-1701343822) we should disable the checkbox for invalid entry. If that this issue still be valid and need to fix

**Comment by zanyrenney** [comment] 2023-09-15 16:27
Can't reproduce this one.

**Comment by zanyrenney** [comment] 2023-09-15 16:27
I suspect bc the bug was fixed as explained above.

**Comment by zanyrenney** [comment] 2023-09-19 04:06
Closing as it seems like this was fixed elsewhere and I am unable to get any confirmation it is reproducible.

**Closed by zanyrenney** 2023-09-19 04:06 UTC
Labels: Daily, Internal, Bug
