### ISSUE TITLE
[HOLD for payment 2023-06-12] [$1000] Click on email link flashes and opens a new tab before opening desktop mail app

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19544] opened 2023-05-24 16:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open the Expensify app and go to a conversation that contains an email link.
2. Click on the email link and observe what happens.

## Expected result: 
The email link should open the desktop mail app directly without opening a new browser tab or flashing.
## Actual result: 
The email link flashes and opens a new browser tab, focus goes to the new opened tab, then closes that tab and returns to the chat page, while launching the desktop mail app.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17-3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/cddf2477-c224-47c2-9d3c-fa6fa2648c55

https://github.com/Expensify/App/assets/43996225/fe9e9014-8a68-4564-84a7-d7529af9044d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kalll
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684498388293319

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f17d183ca5255881</li>
        <li>Upwork Job ID: 1661428049144844288</li>
        <li>Last Price Increase: 2023-05-24</li>
    </ul>
</details>

**Comment by KALLL** [comment] 2023-05-24 17:58
How can I propose for this job? I have possible fix, for this issue.

**Comment by KALLL** [comment] 2023-05-24 18:05
Contributor details
Your Expensify account email: kaleabyalewdeg46@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0106280024a5a63c18

**Comment by KALLL** [comment] 2023-05-24 18:08
So, can I propose my possible fix here to get assigned to the task?

**Comment by Natnael-Guchima** [comment] 2023-05-24 18:15
@KALLL I think you should propose a solution here based on the proposal template. The sooner you propose the better it is to get hired. And for more try to go through the [contributer guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

**Comment by KALLL** [comment] 2023-05-24 18:19
Thank you!

**Comment by KALLL** [comment] 2023-05-24 19:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When you click email link in a conversation, it opens and closes a new tab before it launches the desktop mail app. This causes a flash which can affect user experience.
### What is the root cause of that problem?
on the email <a> link element, there is target="_blank" which obviously open new tab onclick
![image](https://github.com/Expensify/App/assets/34364253/73d1e4d0-b11d-4ca0-a315-55106b826e25)
### What changes do you think we should make in order to solve the problem?
Removing that attribute solved the problem as shown in the video below. The first email link which is bug@bug.com is unfixed(with bug) and solution@solution.com is with the fix and working right. 


https://github.com/Expensify/App/assets/34364253/d5825359-03d8-4a34-a491-e46a0ceca267


### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by AlexanderDmitriev** [comment] 2023-05-24 19:54
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Click on email link flashes and opens a new tab before opening desktop mail app

### What is the root cause of that problem?
We are using `react-native-render-html` module to render `html`. It is adding `target: '_blank'` inside `a` target automatically if the `a` tag doesn't include `target` attribute.
https://github.com/Expensify/App/blob/main/src/components/RenderHTML.js#L15-L23

### What changes do you think we should make in order to solve the problem?
Add `target: '_self'` if `a` tag includes `mailto:`

        <RenderHTMLSource
            contentWidth={windowWidth * 0.8}
            source={{
                html: props.html.match(/href="mailto:/)
                        ? props.html.replace(/href="mailto:/, 'target="_self" href="mailto:')
                        : props.html
            }}
        />

### Result
https://github.com/Expensify/App/assets/17315937/013e5fde-ba6b-4053-8ff3-dc9bd9222293

### What alternative solutions did you explore? (Optional)
N/A

**Comment by kushu7** [comment] 2023-05-24 20:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Click on email link flashes and opens a new tab before opening desktop mail app
### What is the root cause of that problem?
We set target to `_blank` as fallback when we don't provide target as prop in `AnchorRender.js`
https://github.com/Expensify/App/blob/6c5694a8f37f96c40300e878803b0ff42ed80c1f/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L97

new tab is opening because of `_blank` target.
### What changes do you think we should make in order to solve the problem?
We can set target to `_self` for emails.
We can do this by changing
https://github.com/Expensify/App/blob/6c5694a8f37f96c40300e878803b0ff42ed80c1f/src/components/HTMLEngineProvider/HTMLRenderers/AnchorRenderer.js#L26-L27

to 

```js
    const attrHref = htmlAttribs.href || '';
    const isEmailHref = /^mailto:/i.test(attrHref);
    const attrTarget = isEmailHref ? '_self' : htmlAttribs.target;
    const attrPath = lodashGet(Url.getURLObject(attrHref), 'path', '').replace('/', '');
```
and in render we can set target like this
`target={attrTarget || '_blank'}`

It will solve our flashing and new tab issue globally.


### What alternative solutions did you explore? (Optional)
None

**Comment by secDiamond** [comment] 2023-05-24 20:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
##### When clicking email link on conversation, it opens new browser and and flashing.
### What is the root cause of that problem?
![image](https://github.com/Expensify/App/assets/116525171/8bf0db8c-8903-4cc6-ad93-0f5ea9b037c4)

### What changes do you think we should make in order to solve the problem?
##### We should replace this tag.
![image](https://github.com/Expensify/App/assets/116525171/d902f7d2-207b-4567-9600-371b5ad34557)
##### as
`<Text style={{ color: 'blue' }} onPress={() => window.open(`mailto:${email}`, target)} > {email} </Text>`

**Comment by secDiamond** [comment] 2023-05-24 20:20
Contributor details
Your Expensify account email: hidevteam37@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0195ebdd0e3798a492

**Comment by lschurr** [comment] 2023-05-26 16:41
@eVoloshchak - could you review the proposals here?

**Comment by lschurr** [comment] 2023-05-29 15:47
Bump @eVoloshchak

**Comment by KALLL** [comment] 2023-05-29 18:04
Can this job be open to us (default contributors), as the problem is not complicated and the solution is straight forward? Please take a look to my(first) proposal https://github.com/Expensify/App/issues/19544#issuecomment-1561842854

**Comment by KALLL** [comment] 2023-05-29 18:07
@lschurr @kavimuru @eVoloshchak I humbly request the job to be open for us (default contributors), as the problem is not complicated and the solution is straight forward? Please take a look at my(first) proposal https://github.com/Expensify/App/issues/19544#issuecomment-1561842854

**Comment by neil-marcellini** [comment] 2023-05-30 16:22
I requested a new C+ in Slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1685463719918619).

**Comment by neil-marcellini** [comment] 2023-05-30 16:32
@0xmiroslav will review proposals soon.

**Comment by situchan** [comment] 2023-05-31 13:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Clicking email link opens new tab before opening mail app

### What is the root cause of that problem?
As explained in previous proposals, target is `_blank` and passed here:
https://github.com/Expensify/App/blob/efb1463625ba784999dce58dec0faa9163e33e0b/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L70

### What changes do you think we should make in order to solve the problem?
Override target to `_self` if email using the condition on this line:
https://github.com/Expensify/App/blob/efb1463625ba784999dce58dec0faa9163e33e0b/src/components/AnchorForCommentsOnly/BaseAnchorForCommentsOnly.js#L53

So pseudo code looks like this:
```
 target: isValidEmail ? '_self' : props.target, 
```

**Comment by neil-marcellini** [comment] 2023-05-31 18:14
Ha wow, I had to follow [this guide](https://www.indeed.com/career-advice/career-development/how-to-get-email-links-to-open-in-chrome) to allow Chrome to open mail links in gmail before I could test this. Otherwise nothing happened for me.  We might need to add that to the set up steps before testing. I do have the mail app on my mac but it didn't open. Maybe because I never use it?

Anyways, I also like @situchan's proposal and it tests well for me.

**Comment by lschurr** [comment] 2023-06-08 21:33
@KALLL @0xmiroslav @situchan - please apply to the job in Upwork - https://www.upwork.com/jobs/~01f17d183ca5255881

**Comment by lschurr** [comment] 2023-06-12 17:56
@0xmiroslav @situchan - please apply for the job in Upwork: https://www.upwork.com/jobs/~01f17d183ca5255881

Also, @0xmiroslav - do we need a regression test for this one?

**Comment by lschurr** [comment] 2023-06-13 15:59
These are all paid. Closing.

**Closed by lschurr** 2023-06-13 15:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
