### ISSUE TITLE
[HOLD for payment 2024-03-07] [$500] Web - Chat - After Ctrl+R(app reload), the attachment preview modal becomes blank when pressing CTRL+K

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#36604] opened 2024-02-15 16:18 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4316393
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
precondition: user has an existing chat with an attachment .
1. Navigate to app and log in.
2. Open any chat with an attachment
3. Click the attachment to open the preview modal
4. Press CTRL+K or CMD+K to open the search page
5. Dismiss the search page
6. Open another attachment preview in any chat
7. Reload the app (CTRL+R)
8. Press CTRL+K or CMD+K to open the search page

## Expected Result:
When the search page is opened , the conversation with the attachment is greyed out but visible on the backdrop

## Actual Result:
After reloading the app, the preview modal becomes blank.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/190dcc46-2b03-4274-93c9-15791d2326f3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017fb8d3967819dfb5</li>
        <li>Upwork Job ID: 1758163790823956480</li>
        <li>Last Price Increase: 2024-02-15</li>
<li>Automatic offers: </li>
<ul>
<li>mollfpr | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-02-15 16:18
We think that this bug might be related #vip-vsb
CC @quinthar

**Comment by bernhardoj** [comment] 2024-02-16 10:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When we reload the web while on the attachment previews and use search shortcut, the central screen is blank.

### What is the root cause of that problem?
When we reload the web, the nav stack only contains bottom tab navigator and the report attachments page. We have a custom router that modify the stack to includes neccessary route to the stack, but for report attachments, the `state` is undefined. I think the `state` won't be undefined only if it's a nested navigator.
https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/AppNavigator/createCustomStackNavigator/CustomRouter.ts#L33-L37

But even if we remove the early return, it still won't work correctly because `getAdaptedStateFromPath` returns undefined. `getAdaptedStateFromPath` is the one that decides what routes to include on the stack. For example, if there is a full screen navigator, we want to make sure there is a bottom tab navigator, central pane navigator (on large screen), and the full screen navigator itself.

https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L211-L238

In our case the bottom navigator is found on the stack, but `matchingCentralPaneRoute` is undefined because `topmostBottomTabRoute` and that is because the bottom navigator doesn't have a state.
https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/linkingConfig/getAdaptedStateFromPath.ts#L253-L268

https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/linkingConfig/getMatchingCentralPaneRouteForState.ts#L35-L36

https://github.com/Expensify/App/blob/e3331db018e826dc20bb34ad33b3fb77ee6e8fb8/src/libs/Navigation/getTopmostBottomTabRoute.ts#L6-L9

<img width="446" alt="image" src="https://github.com/Expensify/App/assets/50919443/e2ba3bec-eb3d-46f8-888e-0f58f4083e44">

The only case I can see the bottom navigator state is when I open `/home`.

### What changes do you think we should make in order to solve the problem?

Add a new case in `getAdaptedState` to handle report attachments.
```
const reportAttachmentsScreen = state.routes.find((route) => route.name === SCREENS.REPORT_ATTACHMENTS);
```

If report attachments is found on the stack, we want to make sure there is a report screen behind it.
```
if (reportAttachmentsScreen) {
    const routes = [];

    // bottom tab navigator
    const matchingBottomTabRoute = getMatchingBottomTabRouteForState(state);
    routes.push(createBottomTabNavigator(matchingBottomTabRoute, policyID));
    // maybe we can add it on large screen only
    routes.push(createCentralPaneNavigator({name: SCREENS.REPORT, params: {reportID: reportAttachmentsScreen.params?.reportID ?? ''}}));
    // attachments preview
    routes.push(reportAttachmentsScreen)

    return {
        adaptedState: getRoutesWithIndex(routes),
        metainfo,
    }
}
```

**Comment by mollfpr** [comment] 2024-02-16 19:45
@bernhardoj The proposal looks like and clear explanation of the root cause 👍

There is just one problem with the solution. After the search page opens, the navigation history seems of where I can't navigate back or forward to the previous search page.

https://github.com/Expensify/App/assets/25520267/58a1d806-8977-4553-9e5a-56cc346591c5

**Comment by bernhardoj** [comment] 2024-02-17 04:33
I don't really understand how the history is handled by rn-navigation, but looks like that's the common behavior when you refresh the page as shown below:

https://github.com/Expensify/App/assets/50919443/93bcb42e-370a-4ae7-b0b8-41e1cb543b98

**Comment by mollfpr** [comment] 2024-02-20 17:53
Yeah, that's the current behavior and we can skip it for now.

The [proposal](https://github.com/Expensify/App/issues/36604#issuecomment-1948080118) looks good to me!

🎀 👀 🎀 C+ reviewed!

**Comment by bernhardoj** [comment] 2024-02-23 09:41
PR is ready

cc: @mollfpr

**Comment by amyevans** [comment] 2024-03-11 14:44
@mollfpr could you complete the checklist please?

**Comment by mollfpr** [comment] 2024-03-12 11:08
>[@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
> [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I can't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

> [@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

Web/Desktop

1. Open any chat with an attachment (send one that doesn't exist)
2. Open the attachment
3. Refresh the web
4. Use the CMD/CTRL+K shortcut
5. Verify the search page is open, the attachment preview is closed, and a report screen is shown behind the overlay

Android/iOS/mWeb
You can't use the shortcut, so make sure the user can still access the attachment preview

**Comment by mollfpr** [comment] 2024-03-12 11:10
@JmillsExpensify Could you post the payment summary? Thank you!

**Comment by JmillsExpensify** [comment] 2024-03-18 14:41
Payment summary: 

 - Contributor: @bernhardoj $500 
 - Contributor+: @mollfpr $500

**Comment by JmillsExpensify** [comment] 2024-03-18 14:46
Released the payment for @bernhardoj. @laurenreidexpensify Could you please confirm the payment summary above before I approve for @mollfpr?

**Comment by JmillsExpensify** [comment] 2024-03-18 14:47
Actually scratch that. @trjExpensify Can you confirm the payment summary above so that I can release payment?

**Comment by trjExpensify** [comment] 2024-03-18 14:56
Payment summary [here](https://github.com/Expensify/App/issues/36604#issuecomment-2004105418) looks good!

**Comment by JmillsExpensify** [comment] 2024-03-18 14:56
Thank you! $500 approved for @mollfpr based on summary.

**Comment by JmillsExpensify** [comment] 2024-03-18 15:07
Regression test request created, so closing this issue.

**Closed by JmillsExpensify** 2024-03-18 15:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
