### ISSUE TITLE
IOS - New Group - User is get highlighted only at the end of email (dot com) after search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#11806] opened 2022-10-13 15:42 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/11673

## Action Performed:
1. Launch the app
2. Log in with your account
3. Select Fub menu
4. Select New Group
5. Type any user in search field
6. Select suggested user below

## Expected Result:
Email mast be fully allocated

## Actual Result:
User is get highlighted only at the end of email (dot com) after tap on it.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- iOS

**Version Number:** 1.2.14.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** any

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation
![IMG_5033 (1)](https://user-images.githubusercontent.com/93399543/195642871-4c806297-6db6-4b91-b6b6-722def6028c7.jpg)

https://user-images.githubusercontent.com/93399543/195642877-7eb98646-ed37-4e8b-8740-d7a9d116e44f.MP4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team\

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by youssef-lr** [comment] 2022-10-17 10:47
I wasn't able to reproduce this one on iOS. @kbecciv can you try again please?

**Comment by kbecciv** [comment] 2022-10-17 14:02
@youssef-lr Checking, will update you shortly

**Comment by mvtglobally** [comment] 2022-10-24 18:39
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2022-11-03 03:11
Issue not reproducible during KI retests. (Second week)

**Comment by youssef-lr** [comment] 2022-11-03 10:57
Will test again today.

**Comment by sophiepintoraetz** [comment] 2022-11-04 01:42
I've just tried this now and I'm unable to reproduce so going to close this issue.

https://user-images.githubusercontent.com/42940078/199867027-0256665c-d532-4862-8fec-7481b6caf157.mov

**Closed by sophiepintoraetz** 2022-11-04 01:42 UTC
Labels: Engineering, Daily, Needs Reproduction, Bug
