### ISSUE TITLE
[Pay $250 reporting bonus] Editing parent comment in the thread are not reflected until the thread is revisited

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19348] opened 2023-05-20 18:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open any chat
2. Send a message
3. Click on Reply in thread icon
4. Hover over the comment
5. Click on the Edit comment icon
6. Edit the comment
7. Click on the Save changes icon
8. Observe the changes are not reflected
9. Switch to some other chat
10. Go back to the thread
11. Observe the changes are reflected now

## Expected Result:
The edited comment is displayed immediately
## Actual Result:
The edited comment is not displayed until the thread is revisited

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.16.5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/e29b2492-03d5-4853-a3d5-c7b0ea5c172a

https://github.com/Expensify/App/assets/43996225/b7529fa8-63b6-4dc5-8a2d-455325e18024

**Expensify/Expensify Issue URL:**
**Issue reported by:** @adeel0202 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684355738069459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c4411ddc089f97a5</li>
        <li>Upwork Job ID: 1660794802839674880</li>
        <li>Last Price Increase: 2023-06-05</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-05-22 23:46
@allroundexperts - You'll still need to put your proposal for this fix on this GH once it moves to external. You won't be able to claim multiple GHs with a single proposal, everyone will get their fair chance at providing the best proposal to this problem.

**Comment by strepanier03** [comment] 2023-05-22 23:47
Easy to recreate, thanks for raising!

<img width="1434" alt="2023-05-22_16-47-14" src="https://github.com/Expensify/App/assets/10925636/f0376e49-5748-4f9f-8578-997c01a8e1dd">

**Comment by strepanier03** [comment] 2023-05-24 22:37
> My understanding was that we would merge this one into the other one since all of them have the same root cause. I'm more than happy to post the proposal here as well 😄

@allroundexperts - I'll double check on this, I could easily have missed something changing and I wouldn't want to hold up fixes unnecessarily.

**Comment by strepanier03** [comment] 2023-05-24 23:49
@Beamanator and @abdulrahuman5196 - Can you both check these other GHs (https://github.com/Expensify/App/issues/19352 and https://github.com/Expensify/App/issues/19348) and see if you agree that all three GHs have the same root cause?

If they have the same root cause then should we merge these three into one GH?

@allroundexperts has posted a proposal that solves all three in one.

Context [here](https://expensify.slack.com/archives/C01SKUP7QR0/p1684782807958219) for @Beamanator.

**Comment by Beamanator** [comment] 2023-05-25 11:09
It does look like both issues deal with modifications to the parent comment in the thread, so I could see how these could have the same root cause 👍 

However I think we would only "merge" the issues if they're the same issue... They seem very similar but may not be exactly the same issue.

If 1 PR fixes both issues I think the PR should get the reward for fixing both PRs, right @strepanier03 ?

**Comment by abdulrahuman5196** [comment] 2023-05-27 19:34
@allroundexperts 
Could you add more information on the root cause section. I am unable to fully understand the root cause you are mentioning.

>This causes an incomplete action (which does not have a timestamp and other properties and has message only) to be created in the thread report.

If there is only some incomplete/wrong action, how does the action gets updated to proper one when we switch back?

**Comment by abdulrahuman5196** [comment] 2023-05-30 08:01
Will re-review the proposals today

**Comment by abdulrahuman5196** [comment] 2023-06-01 23:14
@allroundexperts  Sorry for delay. The Root cause is correct I checked.
The solutions are also good. I will weight down the solutions and have testing from my end and come back with my thoughts.

**Comment by abdulrahuman5196** [comment] 2023-06-05 07:18
Reviewing again now

**Comment by abdulrahuman5196** [comment] 2023-06-05 08:02
Analysis on @allroundexperts proposal here

The root cause is correct and solution is also working as mentioned before. Upon dive deeping on solutions I noticed it not just edit comment is affected but also adding reactions is affected. And in the proposal @allroundexperts mentioned 3 ways to solve it. But each way has its own disadvantages and advantages.

Option 1: 

>We can replace [this](https://github.com/allroundexperts/Expensify/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/pages/home/report/ReportActionItemParentAction.js#L61-L62) with:
// parent report can be fetched from onyx storage using props.parentReportID prop
 report={props.parentReport}

As mentioned it causes thread replies to show up. Not just that since it considers the comment to be original parentReport comment and every action on that is considered same. For example if you create a draft comment of the thread comment, it is showing as draft in the original report as well. And if we mark as unread here only the parent report is marked as unread.

To solve these, we might end up doing checks where we don't want to use the parent report in these cases alone.


option 2:
>If above is not an option, then we can also pass the parent report id and parent report action to the editReportComment function [here](https://github.com/allroundexperts/Expensify/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/libs/actions/Report.js#L972-L973) IF thread title is being edited. This will ensure that edits are being done to the parent report instead of creating an incomplete action in the thread report. The editReportComment function is being called [here](https://github.com/allroundexperts/Expensify/blob/9e43cb7d811599ae67d1f31d78bac8327ce2061c/src/pages/home/report/ReportActionItemMessageEdit.js#L226-L227). We can check here if the report action is a thread parent. If it is, then we can pass parent params to the editReportComment function.

This would work, but the disadvantage is we would end up introducing the parentReportId and related logic in multiple components starting from the `ReportActionItemParentAction` hierarchy.

option 3: 
>In the editReportComment, we first have to check if the given originalReportAction is isThreadParent. We also have to get the parentReportId and parentReportActionId ie:

This will also work. But the disadvantage is we have to add similar logic to addEmojiReaction flow and any other if came in future.



Given the analysis, My preference is to go with option 3(alternate solution proposed in https://github.com/Expensify/App/issues/19348#issuecomment-1558728503) which is better compared to other approaches IMO.

But anyways all of the approaches are from a single proposal. I am approving the proposal and just we have to align on the option to choose.

🎀👀🎀
C+ Reviewed

cc: @Beamanator  Kindly check and share your thoughts as well

**Comment by Beamanator** [comment] 2023-06-06 20:38
@abdulrahuman5196 @allroundexperts thanks so much for the proposals & multiple solutions.

I think I agree with you that solution 3 sounds best, but I'd also love to hear @allroundexperts 's opinion on the analysis done above before we officially decide which solution to go with

**Comment by abdulrahuman5196** [comment] 2023-06-07 07:33
@allroundexperts 
The problem with first approach is, any action we do on that is directly reflected back in parent report(like a duplicate message shown on UI). We shouldn't do that for couple of cases like draft message, mark as unread(there can be others as well). For these cases, to avoid it reflecting on parent report then we have to add checks in ReportActionItem(or similar UI components) to find if the current action render is in thread or in parent report and make changes accordingly.

The third approach is actually the opposite of first, like we will only be doing the updates w.r.t parent report only on required functionality. For now, editing Comment and adding emoji. So if in future any new functionality comes with the same requirements we will do it in the utils function in the same way.

The best of the options we should choose based on cleaner approach and scalable. 
So I am still aligned with option 3 of the proposal since it seems more cleaner out of the other options.

**Comment by abdulrahuman5196** [comment] 2023-06-07 10:28
@allroundexperts i think there is misunderstanding. I am saying about thread title message only. 
Could you check this?
1) Make the solution 1 change.
2) Mark the thread first message(title message) as unread in the threaded report ui
3) it will make the parent chat itself unread.

Sameways
1) edit the thread first message in the thread report ui and keep it in draft state.
2) go to the parent chat report, the relevant msg in the parent would be also in draft state.

**Comment by abdulrahuman5196** [comment] 2023-06-07 10:42
@allroundexperts I don't think that what we would want. After editing completion it should reflect in parent report. 
But It's very odd if marking one in draft state automatically shows both places in draft state. And any mark as unread action will only reflect back to the parent report. 

cc @Beamanator

**Comment by strepanier03** [comment] 2023-06-07 19:33
@allroundexperts @abdulrahuman5196  - On [this](https://expensify.slack.com/archives/C049HHMV9SM/p1685199666223399) other bug report thread, there is a question of whether or not the solution for our GH will fix the issue in the thread. 

It looks like we're still discussing the best solution to our GH though so I'm not sure our fix will fix that other bug too. If either of you have any thoughts on the matter can you weigh in on the thread?

**Comment by abdulrahuman5196** [comment] 2023-06-08 18:25
@strepanier03  Commented on the thread, seems to be a different issue.

**Comment by abdulrahuman5196** [comment] 2023-06-08 18:25
@allroundexperts  any updates on the above discussion?

**Comment by strepanier03** [comment] 2023-06-08 21:59
Thank you @allroundexperts - I'll follow the thread and ping some people/teams directly if we don't get any responses.

**Comment by abdulrahuman5196** [comment] 2023-06-14 20:37
The thread is still ongoing

**Comment by abdulrahuman5196** [comment] 2023-06-15 14:22
@strepanier03 It seems there is an internal effort to solve issues revolving around thread edits and reactions. We should be able to close this issue - https://expensify.slack.com/archives/C01GTK53T8Q/p1686778600350519?thread_ts=1686259969.958099&cid=C01GTK53T8Q

https://github.com/Expensify/Expensify/issues/282991

cc: @chiragsalian

**Comment by strepanier03** [comment] 2023-06-15 20:27
Thank you @abdulrahuman5196! I believe we would still pay the reporting bonus for this as reporting these behaviors has influenced our discussions and moved things forward. 

I'll update this GH for that and get the reporting job up for @adeel0202.

**Comment by strepanier03** [comment] 2023-06-15 20:31
@adeel0202 - I have hired you for  reporting job in Upwork, please accept and I'll check in about paying later.

**Comment by strepanier03** [comment] 2023-06-15 23:43
@abekkala - We're just waiting for @adeel0202 to accept the job offer for the reporting bonus in Upwork and then we can pay and close the GH.

**Comment by abekkala** [comment] 2023-06-16 14:04
@adeel0202 payment sent and contract ended - thank you! 🎉

**Closed** 2023-06-16 14:06 UTC
Labels: External, Daily, Bug
