### ISSUE TITLE
IOU-Error "hhm its not here" displayed on refreshing split bill confirmation page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32934] opened 2023-12-12 16:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.11-13
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Click fab
3. Click request money ----Scan
4. Upload an image
5. Select 2 participants and Click split
6. Click add to split
7. Click browser refresh button

## Expected Result:
Error "hhm its not here" must not be displayed on refreshing split bill confirmation page

## Actual Result:
Error "hhm its not here" displayed on refreshing split bill confirmation page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] Windows: Chrome 
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3b654eee-6d84-4d11-8a47-4ad90d3b810f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment] 2023-12-12 16:50
Looking now

**Comment by luacmartins** [comment] 2023-12-12 17:18
I could not reproduce this on mWeb Safari nor MacOs chrome

**Comment by luacmartins** [comment] 2023-12-12 17:26
Just reproduced on dev MacOS Chrome. Gonna investigate

**Comment by luacmartins** [comment] 2023-12-12 17:32
This seems fixed in latest main. I think https://github.com/Expensify/App/pull/32849 fixed it.

**Closed** 2023-12-12 17:33 UTC
Labels: Engineering, Hourly
