### ISSUE TITLE
[$250] Distance - The route image is cropped in the IOU preview

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#40791] opened 2024-04-23 13:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4502640
**Issue reported by:** Applause - Internal Team

## Action Performed:
Prerequisites:
Create WS collect, invite an employee
1. Open https://staging.new.expensify.com/
2. Log in to the employee account
3. Navigate to a workspace room
4. Create a Distance IOU with any 2 waypoints
5. Navigate to Report Conversation

## Expected Result:
The route image must fit completely in the IOU preview

## Actual Result:
The route image is cropped in the IOU preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/12a79328-a8ad-46d9-8996-18e6eb6d6d10

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0160841ad69bf530a2</li>
        <li>Upwork Job ID: 1782777779723137024</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-04-23 13:10
@Gonals  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Gonals** [comment] 2024-04-23 14:26
@Pujan92, what do you think of @ra-md's proposal?

**Comment by Pujan92** [comment] 2024-04-23 14:35
@ra-md Object position top is added to fix issue https://github.com/Expensify/App/issues/34120.

@Gonals This seems to be a regression from https://github.com/Expensify/App/pull/35041 

cc: @dukenv0307

**Comment by Gonals** [comment] 2024-04-23 15:24
I think this may not be a blocker, since it just kinda moves an existing bug a few pixels 😆. What do you think, @mountiny?

**Comment by Beamanator** [comment] 2024-04-23 15:26
Aah this could be related to my Web-PDFs change where I centered receipts to the top - https://github.com/Expensify/Web-PDFs/pull/572

I also don't think this is a blocker

**Comment by neil-marcellini** [comment] 2024-04-23 15:30
The root cause is on the backend and already on prod so yeah, not a blocker. It would be great to fix soon though. It looks bad for distance requests.

**Comment by garrettmknight** [comment] 2024-04-24 09:25
Cool, closing this one in favor of the other then.

**Closed by garrettmknight** 2024-04-24 09:25 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
