### ISSUE TITLE
[HOLD for payment 2024-11-11] iOS - Hybrid app - Split - Cursor jumps in front of digit when deleting participant's amount

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50886] opened 2024-10-16 11:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.49.0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Open the app and log in
2. Navigate to the group chat
3. Tap + > Split expense
4. Enter the amount and proceed to the confirmation page
5. Delete the participant's amount by tapping the delete key
6. Select the other participant's amount by double tapping and remove it
7. Start entering a new amount

## Expected Result:
The cursor does not jump in front of the next digit

## Actual Result:
The cursor jumps in front of the next digit after removing the 1st digit before decimal point (step 5) or when removing the amount and entering one digit (steps 6-7)

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [x] iOS: Standalone
- [x] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/df304ee7-c117-44e3-933f-274b51942dab

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @Christinadobrzyn</details>

**Comment by IuliiaHerets** [comment] 2024-10-16 11:50
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment] 2024-10-17 05:26
yes, looks like the cursor jumps in front of the last digit when deleting and entering a new amount. Asking if this might be related to https://github.com/Expensify/App/issues/48869

**Comment by WojtekBoman** [comment] 2024-10-17 09:56
Hey @Christinadobrzyn, I've investigated this issue and to me the reason is the same like in this [one](https://github.com/Expensify/App/pull/42158). We have two methods to update selection in `MoneyRequestAmountInput`. There is a case when we update selection in `setNewAmount`, but we operate on a value that has been already updated in `onSelectionChange`. It can be fixed by blocking the update in `onSelectionChange` when calling `setNewAmount`. It has been already implemented for the Android platform (the variable `shouldIgnoreSelectionWhenUpdatedManually`). On the other hand maybe we should consider calling `setSelection` only from one method to make it more clear. Setting `shouldIgnoreSelectionWhenUpdatedManually` to `true` seems to work for iOS, but I realize there are a lot of issues with this component, so we should investigate this solution further to make sure other issues don't arise because of this.

**Comment by Christinadobrzyn** [comment] 2024-10-18 04:43
Hi @WojtekBoman! Thank you for your thorough investigation. It sounds like this should be treated as a separate issue and will require some pretty deep investigation. 

Would you want to take this job on after you're done with https://github.com/Expensify/App/issues/48869?

**Comment by WojtekBoman** [comment] 2024-10-18 10:32
I'll take care of that :) [This one](https://github.com/Expensify/App/issues/48869) is already finished, I wrote a request to close it

**Comment by Christinadobrzyn** [comment] 2024-10-22 03:38
Awesome! Thank you @WojtekBoman!

**Comment by Christinadobrzyn** [comment] 2024-10-29 06:27
PR in the works - https://github.com/Expensify/App/pull/51306

**Comment by Christinadobrzyn** [comment] 2024-11-12 02:23
This one seems a little strange as the [PR](https://github.com/Expensify/App/pull/40390#discussion_r1830954426) linked is from April - is there anything I should know about paying this? Were there regressions?

Payment summary is here - https://github.com/Expensify/App/issues/50886#issuecomment-2468384550 @rayane-djouah can you accept the Upwork offer?

**Comment by mountiny** [comment] 2024-11-12 12:26
I think we can pay for the review of https://github.com/Expensify/App/pull/51306 and close

**Comment by Christinadobrzyn** [comment] 2024-11-13 07:09
Thanks @mountiny and @rayane-djouah!

Regression test - https://github.com/Expensify/Expensify/issues/443775

Paid out based on this [payment summary ](https://github.com/Expensify/App/issues/50886#issuecomment-2468384550)

closing!

**Closed by Christinadobrzyn** 2024-11-13 07:09 UTC
Labels: Daily, Internal, Awaiting Payment, Bug, Hot Pick
