### ISSUE TITLE
[NEEDS REPRO] [$500] Timezone - The timezone toggles between the selected and automatically determined time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35422] opened 2024-01-30 18:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Login same user on two devices ( web and android)
2. From your Android device, go to Settings > Profile > Timezone.
3. Disable automatic Timezone
4. Choose random Timezone

## Expected Result:
Timezone section should be stable

## Actual Result:
The timezone toggles between the selected and automatically determined time

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cc986748-6127-4a76-941e-c4461f58eeac

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e72c7d1b774e8e84</li>
        <li>Upwork Job ID: 1752394312056856576</li>
        <li>Last Price Increase: 2024-02-13</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by sourcecodedeveloper** [comment] 2024-01-31 18:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Log user in two devices using account A. Toggle automatic timezone on device 1, the timezone on device 2 switches between timezone of device 1 and device 2.
### What is the root cause of that problem?

When calling openProfile in App.ts, the timezone data is updated if the timezone is set to automatic. 
https://github.com/Expensify/App/blob/8014b0218761dca1c6a7f2d75325e95094b465c3/src/libs/actions/App.ts#L419

The personalDetails object already has updated timezone data for when timezone is set to automatic or manual. The if condition block is not needed and can be removed.

### What changes do you think we should make in order to solve the problem?

The if condition block 
https://github.com/Expensify/App/blob/8014b0218761dca1c6a7f2d75325e95094b465c3/src/libs/actions/App.ts#L419
can be removed because the personalDetails parameter already has updated timezone data for automatic or manual timezone.

The newTimezoneData can be assigned the value of personalDetails.timezone ?? {}
https://github.com/Expensify/App/blob/8014b0218761dca1c6a7f2d75325e95094b465c3/src/libs/actions/App.ts#L417

```
newTimezoneData = personalDetails.timezone ?? {};
```

Both devices can run with seperate timezones.

### What alternative solutions did you explore? (Optional)

**Comment by jliexpensify** [comment] 2024-02-01 02:12
I'm testing this on v35 on Android (Pixel 3a) and Chrome (also v35) and I cannot repro.

@ishpaul777 @kbecciv can you both re-test? Thanks!

**Comment by jliexpensify** [comment] 2024-02-07 02:15
Hi, sorry @suneox - can you reproduce the actual timezone issue? We're not looking for proposals/ideas if we can't repro the issue in-app. Thanks!

**Comment by jliexpensify** [comment] 2024-02-10 04:46
Bump @suneox or @kbecciv  - are you able to reproduce teha actual timezone issue?

**Comment by jliexpensify** [comment] 2024-02-12 21:05
@suneox any luck reproducing? If not, going to close this. Thanks!

**Comment by situchan** [comment] 2024-02-14 19:51
Interested since this is similar to https://github.com/Expensify/App/issues/35650 I am reviewing

**Comment by situchan** [comment] 2024-02-15 18:55
This looks like edge case but still something to fix.
@jliexpensify do you think this fits into any wave?

**Comment by jliexpensify** [comment] 2024-02-15 21:26
Let me ask, thank you for pointing this out @situchan ! My initial thought is that we'd want to fix it, given it affects everyone on Android and Mac

**Comment by jliexpensify** [comment] 2024-02-16 22:50
@situchan @suneox - the consensus is:

1. We should properly reproduce this issue (it seems like I can't repro it on an Android, so maybe you two can truly on a physical device, if you have them)

2. This might go to #vip-vsb (unsure, I'll only surface this there once we can properly repro)

**Comment by jliexpensify** [comment] 2024-02-19 23:26
Ok, going to close this. No response from the Contributor and we can't repro properly.

**Comment by jliexpensify** [comment] 2024-02-19 23:27
@situchan please comment with some thoughts if you disagree/want this re-opened

**Closed by jliexpensify** 2024-02-19 23:26 UTC
Labels: External, Daily, Needs Reproduction, Overdue, Bug
