### ISSUE TITLE
[$250] Expensify - Inconsistency in onboarding tasks, editable in Concierge but not in Expensify

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44461] opened 2024-06-26 14:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A 
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Log in to New Expensify with new account
2. Proceed through the onboarding flow
3. Open the "Expensify" chat
4. Try to mark as completed or edit any task

## Expected Result:
Onboarding tasks should be consistent between Concierge and Expensify chats

## Actual Result:
Onboarding tasks can be edited and marked as completed in Concierge chat but are not editable in Expensify chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/1a818a6b-e619-45c8-93e2-a6deedaaaca7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5c0439898148af7</li>
        <li>Upwork Job ID: 1807840878576040624</li>
        <li>Last Price Increase: 2024-07-08</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @Julesssss</details>

**Comment by lanitochka17** [comment] 2024-06-26 14:11
@zanyrenney z FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-26 14:12
We think that this bug might be related to #vip-vsp

**Comment by zanyrenney** [comment] 2024-07-01 18:16
thanks! sorry for the delay.

**Comment by grogou** [comment] 2024-07-04 13:08
### Please re-state the problem that we are trying to solve in this issue.

Onboarding tasks can be edited and marked as completed in Concierge chat but are not editable in Expensify chat

### What is the root cause of that problem?

The problem is with the backend, so this issue is occurring on all platforms.
When a user finishes onboarding, the `completeOnboarding` function is called in the `completeEngagement` function
```js
const completeEngagement = useCallback(
        (values: FormOnyxValues<'onboardingPersonalDetailsForm'>) => {
            const firstName = values.firstName.trim();
            const lastName = values.lastName.trim();

            PersonalDetails.setDisplayName(firstName, lastName);

            if (!onboardingPurposeSelected) {
                return;
            }

            Report.completeOnboarding(
                onboardingPurposeSelected,
                CONST.ONBOARDING_MESSAGES[onboardingPurposeSelected],
                {
                    firstName,
                    lastName,
                },
                onboardingAdminsChatReportID ?? undefined,
                onboardingPolicyID,
            );
            // ....
}
```
The `targetChatReport` is selected based on `targetEmail` (`notifications@expensify.com` or `concierge@expensify.com`). Permissions are assigned to the report during its creation on the server side. If `targetChatReport` is associated with `concierge@expensify.com`, reports have `read` and `write` permissions, allowing them to be edited. However, when `targetChatReport` is associated with `notifications@expensify.com`, reports only have `read` permission, which limits editing in Expensify chat.
```js
function completeOnboarding(
    engagementChoice: OnboardingPurposeType,
    data: ValueOf<typeof CONST.ONBOARDING_MESSAGES>,
    {
        firstName,
        lastName,
    }: {
        firstName: string;
        lastName: string;
    },
    adminsChatReportID?: string,
    onboardingPolicyID?: string,
) {
    const isAccountIDOdd = AccountUtils.isAccountIDOddNumber(currentUserAccountID ?? 0);
    const targetEmail = isAccountIDOdd ? CONST.EMAIL.NOTIFICATIONS : CONST.EMAIL.CONCIERGE;

    const actorAccountID = PersonalDetailsUtils.getAccountIDsByLogins([targetEmail])[0];
    const targetChatReport = ReportUtils.getChatByParticipants([actorAccountID, currentUserAccountID]);
    const {reportID: targetChatReportID = '', policyID: targetChatPolicyID = ''} = targetChatReport ?? {};
    // ....
}
```

https://github.com/Expensify/App/assets/10712881/6e56da85-c5de-4799-8df0-70252886e658


### What changes do you think we should make in order to solve the problem?

The root cause of this problem is in the backend where report permissions are initially set. We can make an additional call to try to update the permissions, but this approach is not optimal. The correct permissions must be assigned during the server-side report generation phase.

**Comment by grogou** [comment] 2024-07-05 18:53
@suneox, it sometimes creates and sometimes does not. It comes from the backend. The hard part of this bug is to have Expensify chat after signup. I have created over 40 accounts to have this proposal done.

**Comment by grogou** [comment] 2024-07-05 19:40
https://github.com/Expensify/App/assets/10712881/1af86245-3f3d-48a2-beb1-8e2a04d9e528

**Comment by grogou** [comment] 2024-07-14 09:53
Hi @suneox,

Thank you for your review. I'm new here and was wondering if there are any rewards on Upwork.

Thanks!

**Comment by Julesssss** [comment] 2024-07-15 08:55
> Thank you for your review. I'm new here and was wondering if there are any rewards on Upwork.

Thanks for helping todebug the issue @grogou. We do tend to reward bug triage, but this won't happen until the bug is fixed internally. The next step for me is to assign out to someone with more knowledge of the onboarding task logic.

**Comment by grogou** [comment] 2024-07-15 09:01
Thank you @Julesssss for clarification!

**Comment by zanyrenney** [comment] 2024-07-25 08:33
Thanks for stepping in there @Julesssss

**Comment by zanyrenney** [comment] 2024-07-25 08:34
@Julesssss did you find the correct assignee for this?

**Comment by Julesssss** [comment] 2024-07-25 11:03
Actually I'm not sure that this is still occurring. I'm able to mark the task as completed. Let's see if QA are able to reproduce. 

<img width="617" alt="Screenshot 2024-07-25 at 12 02 38" src="https://github.com/user-attachments/assets/9cceba5e-2121-4360-bf31-f0959ce87cf2">

**Comment by zanyrenney** [comment] 2024-07-25 11:06
Hey @lanitochka17 please can you retest as per @Julesssss comment above? Cheers!

**Comment by lanitochka17** [comment] 2024-07-31 14:58
This issue is not reproducible anymore


https://github.com/user-attachments/assets/3ae1e444-a7ef-4900-b8f6-8ae920b81392

**Comment by Julesssss** [comment] 2024-08-01 10:41
Excellent, thank you

**Closed by Julesssss** 2024-08-01 10:41 UTC
Labels: Weekly, Internal, Bug, retest-weekly
