### ISSUE TITLE
[$1000] Date of birth year deep link does not change the year

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21261] opened 2023-06-21 20:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with user A
2. Open settings
3. Open profile
4. Open personal details
5. Open date of birth
6. Open year search
7. Select any year and copy the url
8. Logout and login with user B or login with user B in incognito
9. Visit link copied in step 7 and observe that app changes the year in year selection but does not change the year in textbox above
10. Change date and observe that app still considers old selected year and not the new year displayed in year selection

## Expected Result:
I think it's odd that we change the link from https://staging.new.expensify.com/settings/profile/personal-details/date-of-birth to https://staging.new.expensify.com/settings/profile/personal-details/date-of-birth?year=YYYY when you select a different year of birth (before saving). But we don't change the link at all when adjusting month or day of birth.

IMO, the ideal behavior here is to stop changing the link when you adjust year of birth before saving. And then make it so you can't deep link to change your year of birth at all. This isn't something an actual user will frequently/ever be doing.

## Actual Result:
App does not change the year in textbox above datepicker and also does not consider the new year on date selection if we visit modified year deep link

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.27-6

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/7aaaac3f-44f9-42cc-921f-6c7da06c8bc8

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686756962010819

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190aa89bc7487f806</li>
        <li>Upwork Job ID: 1671627605530898432</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by joekaufmanexpensify** [comment] 2023-06-21 21:13
I can reproduce this. Though, I think it's odd that we change the link from `https://staging.new.expensify.com/settings/profile/personal-details/date-of-birth` to `https://staging.new.expensify.com/settings/profile/personal-details/date-of-birth?year=YYYY` when you select a different year of birth (before saving). But we don't change the link at all when adjusting month or day of birth. 

IMO, the ideal behavior here is to stop changing the link when you adjust year of birth before saving. And then make it so you can't deep link to change your year of birth at all. This isn't something an actual user will frequently/ever be doing.

**Comment by jfquevedol21** [comment] 2023-06-21 23:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date of birth year deep link does not change the year

### What is the root cause of that problem?
`selectedYear` state variable in `CalendarPicker` component was not initialized by `year` param from `route` props

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/CalendarPicker/index.js#L20-L46

### What changes do you think we should make in order to solve the problem?
need to initialize `selectedYear` need to be initialized by `year` param from `route` props and call `onSelected` callback which is one of props.

        this.state = {
            currentDateView,
            selectedYear: props.selectedYear || currentSelection.get('year').toString(),
            selectedMonth: this.getNumberStringWithLeadingZero(currentSelection.get('month') + 1),
            selectedDay: this.getNumberStringWithLeadingZero(currentSelection.get('date')),
        };
        
        this.props.onSelected(this.getSelectedDateString());

### Result:

https://github.com/Expensify/App/assets/91210461/2f63782b-4c76-4352-96f8-e75cdd1cd5c3


### What alternative solutions did you explore? (Optional)
N/A

**Comment by wildan-m** [comment] 2023-06-22 10:11
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Date of birth year deep link does not change the year 

### What is the root cause of that problem?

We are replacing the `currentDateView` year but not replacing `currentSelection` year from the route

https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/components/CalendarPicker/index.js#L27-L29

### What changes do you think we should make in order to solve the problem?

We can replace the year from the very beginning when we init `currentSelection` variable

We can move this code before declaring `currentDateView`

https://github.com/Expensify/App/blob/9bef5074ae858e7efb0d757473409ef099dac309/src/components/CalendarPicker/index.js#L27-L29

And replace the code with

```
        if (props.selectedYear) {
            currentSelection.year(props.selectedYear);
        }
```

Final snippet:

```
    constructor(props) {
        super(props);
        let currentSelection = moment(props.value, CONST.DATE.MOMENT_FORMAT_STRING);
        if (props.selectedYear) {
            currentSelection.year(props.selectedYear);
        }

        let currentDateView = currentSelection.toDate();
        if (props.selectedMonth != null) {
            currentDateView = moment(currentDateView).set('month', props.selectedMonth).toDate();
        }

```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by joekaufmanexpensify** [comment] 2023-06-22 14:04
Next steps are to review proposals here

**Comment by jfquevedol2198** [comment] 2023-06-23 16:25
> ## Proposal
> ### Please re-state the problem that we are trying to solve in this issue.
> Date of birth year deep link does not change the year
> 
> ### What is the root cause of that problem?
> `selectedYear` state variable in `CalendarPicker` component was not initialized by `year` param from `route` props, so it was initialized by `dob`
> 
> https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/components/CalendarPicker/index.js#L20-L46
> 
> ### What changes do you think we should make in order to solve the problem?
> need to initialize `selectedYear` need to be initialized by `year` param from `route` props and call `onSelected` callback which is one of props.
> 
> ```
>     const currentSelection = moment(props.value, CONST.DATE.MOMENT_FORMAT_STRING);
>     let currentDateView = currentSelection.toDate();
> 
>     if (props.selectedYear) {
>         currentDateView = moment(currentDateView).set('year', props.selectedYear).toDate();
>     }
>     if (props.selectedMonth != null) {
>         currentDateView = moment(currentDateView).set('month', props.selectedMonth).toDate();
>     }
>     if (props.maxDate < currentDateView) {
>         currentDateView = props.maxDate;
>     } else if (props.minDate > currentDateView) {
>         currentDateView = props.minDate;
>     }
> 
>     this.state = {
>         currentDateView,
>         selectedYear: currentDateView.getFullYear().toString(),
>         selectedMonth: this.getNumberStringWithLeadingZero(currentDateView.getMonth() + 1),
>         selectedDay: this.getNumberStringWithLeadingZero(currentDateView.getDate()),
>     };
>     this.props.onSelected(this.getSelectedDateString());
> ```
> 
> ### Result:
>  Screen.Recording.2023-06-22.at.7.43.03.AM.mov 
> ### What alternative solutions did you explore? (Optional)
> N/A


I needed to close my previous github. This was my proposal and this is my new github.

**Comment by jfquevedol2198** [comment] 2023-06-26 04:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
`updateSelectedYear` callback that calls when select an year from `YearPickerPage component is adding `year` param in route.

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

### What is the root cause of that problem?
We need to add a function `onSelectYear` in `DateOfBirthPage` page component and store it in `EventEmitter`.
then, when select new year on `YearPickerPage` component, need to emit the stored function in `EventEmitter`

1. Switch `selectedYear` to state variable in `DateOfBirthPage` component, it will be initialized by `dobYear`

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L43

after change:

    const [selectedYear, setSelectedYear] = useState(dobYear);

2. Add EventEmitter module in `src/libs`

 ```
  const listenersMap = {};

  function addListener(eventName, listener) {
    listenersMap[eventName] = listenersMap[eventName] || [];
    listenersMap[eventName].push(listener);
  }

  function removeListener(eventName, listener) {
    const lis = listenersMap[eventName];
    if (!lis) return;

    for (let i = lis.length - 1; i >= 0; i--) {
      if (lis[i] === listener) {
        lis.splice(i, 1);
        break;
      }
    }
  }

  function removeAllListeners(eventName) {
    listenersMap[eventName] = [];
  }

  function emit(eventName, ...params) {
    const listeners = listenersMap[eventName];
    if (!listeners) return false;
    listeners.forEach(fnc => {
      fnc(...params);
    });
    return true;
  }

  export default {
    addListener,
    removeListener,
    removeAllListeners,
    emit,
  };
```
        

2. Add `onSelectYear` method in `DateOfBirthPage` component to get the new selected year from `YearPickerPage` and register `onSelectYear` method into `EventEmitter`.

```
    const onSelectYear = (year) => {
        setSelectedYear(year);
    }

    useEffect(() => {
        EventEmitter.addListener('onSelectYear', onSelectYear);
        return () => EventEmitter.removeListener('onSelectYear', onSelectYear);
    }, []);
```

3. Update `updateSelectedYear` method on `YearPickerPage` component .
original `updateSelectedYear` method:
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

after change:
```
    updateSelectedYear(selectedYear) {
        EventEmitter.emit('onSelectYear', `${selectedYear}`);
        Navigation.goBack();
    }
```

### Result

https://github.com/Expensify/App/assets/137529618/ef3669f8-a483-4239-bb0c-930f82effaa3

### What alternative solutions did you explore? (Optional)
N/A

**Comment by joekaufmanexpensify** [comment] 2023-06-26 18:48
Updated expected behavior in OP!

**Comment by joekaufmanexpensify** [comment] 2023-06-27 17:43
Pending review of new proposal

**Comment by jfquevedol2198** [comment] 2023-06-28 05:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Date of birth year deep link does not change the year

### What is the root cause of that problem?
`updateSelectedYear` callback that calls when select an year from `YearPickerPage` component is adding `year` param in route.

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

### What changes do you think we should make in order to solve the problem?
Add a callback to handle the new year selection in `DateOfBirthPage` component and create an action to be called to update the `selectedYear` state variable of `DateOfBirthPage` from `YearPickerPage` component.

1. Switch `selectedYear` to state variable in `DateOfBirthPage` component, it will be initialized by `dobYear`

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L43

after change:
```javascript
const [selectedYear, setSelectedYear] = useState(dobYear);
```

2. Add an action in `src/libs/actions/SelectYearAction`

 ```javascript
import React from 'react';

const onSelectYearRef = React.createRef();

function attachCallback(onSelectYear) {
  onSelectYearRef.current = onSelectYear;
}

function emitCallback(year) {
  if (!onSelectYearRef.current) return;
  onSelectYearRef.current(year);
}

export {attachCallback, emitCallback};
```

3. Add `onSelectYear` method in `DateOfBirthPage` component to get the new selected year from `YearPickerPage` and register `onSelectYear` in `SelectYearAction`

```javascript
    useEffect(() => {
        const onSelectYear = (year) => setSelectedYear(year);
        SelectYearAction.attachCallback(onSelectYear);
    }, [])
```

4. Update `updateSelectedYear` method on `YearPickerPage` component .
original `updateSelectedYear` method:
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

after change:
```javascript
    updateSelectedYear(selectedYear) {
        SelectYearAction.emitCallback(selectedYear);
        Navigation.goBack();
    }
```

<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/8879291f-5c0f-4dd9-824e-3b5e58306fdc

</details> 


### What alternative solutions did you explore? (Optional)
N/A

**Comment by jfquevedol2198** [comment] 2023-06-28 05:17
@allroundexperts
Thanks for checking my proposal
Here is my updated [proposal](https://github.com/Expensify/App/issues/21261#issuecomment-1610752289)

**Comment by joekaufmanexpensify** [comment] 2023-06-28 19:10
Pending review of updated proposals. We can hold off adjusting the bounty for now as we still have a proposal pending review.

**Comment by wildan-m** [comment] 2023-06-28 19:12
@allroundexperts @joekaufmanexpensify I think we should keep the pattern.

I remember that the current [currency selectors adopt the calendar pattern](https://github.com/Expensify/App/issues/18667#issuecomment-1543679214) to avoid using Onyx and resolve [this issue](https://github.com/Expensify/App/issues/18667).

If we change this calendar pattern then we should also change the currency selector to make it consistent.

In my opinion, the year query string is not too distracting to the user, as long as it works as expected.

**Comment by jfquevedol2198** [comment] 2023-06-29 05:44
@allroundexperts 
We can do same like in `DateOfBirthPage` for currency selection if we need same behaviour on currency selection.

**Comment by joekaufmanexpensify** [comment] 2023-06-29 20:41
Bumped in Slack [here. ](https://expensify.slack.com/archives/C01GTK53T8Q/p1688071239121839)

**Comment by joekaufmanexpensify** [comment] 2023-07-03 13:11
Sounds good! Pending review of proposals.

**Comment by joekaufmanexpensify** [comment] 2023-07-05 18:17
@allroundexperts could you please re-review the updated proposals when you have a chance?

**Comment by joekaufmanexpensify** [comment] 2023-07-06 16:18
Great, thanks!

**Comment by joekaufmanexpensify** [comment] 2023-07-07 16:54
Pending review of updated proposals.

**Comment by joekaufmanexpensify** [comment] 2023-07-10 18:34
Great, ty!

**Comment by jfquevedol2198** [comment] 2023-07-10 23:35
@allroundexperts You are right, if we have multiple Year selection fields, it won't work exactly.
I just updated it in the same [branch](https://github.com/jfquevedol2198/Expensify/commits/fernando2198).
React Ref can be turned into React Contexts if its better.

**Comment by jfquevedol2198** [comment] 2023-07-10 23:57
@allroundexperts here is the example with multiple Year selection on a page:

https://github.com/Expensify/App/assets/137529618/ecd8d0ac-2c46-4b5c-8ad0-c15a7525fe05

**Comment by jfquevedol2198** [comment] 2023-07-11 14:13
## [Updated Proposal]

### Please re-state the problem that we are trying to solve in this issue.
Date of birth year deep link does not change the year

### What is the root cause of that problem?
`updateSelectedYear` callback that calls when select an year from `YearPickerPage` component is adding `year` param in route.

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

### What changes do you think we should make in order to solve the problem?
Add a callback to handle the new year selection in `DateOfBirthPage` component and create an action to be called to update the `selectedYear` state variable of `DateOfBirthPage` from `YearPickerPage` component.

1. Switch `selectedYear` to state variable in `DateOfBirthPage` component, it will be initialized by `dobYear`

https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/settings/Profile/PersonalDetails/DateOfBirthPage.js#L43

after change:
```javascript
const [selectedYear, setSelectedYear] = useState(dobYear);
```

2. Add an action in `src/libs/actions/SelectYearAction`

 ```javascript
import React from 'react';

const onSelectYearRef = React.createRef();
const inputIdRef = React.createRef();

function set(onSelectYear) {
  onSelectYearRef.current = onSelectYear;
}

function emit(year) {
  if (!onSelectYearRef.current) return;
  onSelectYearRef.current(inputIdRef.current, year);
}

function updateInputID(inputID) {
  inputIdRef.current = inputID;
}

export {set, emit, updateInputID};
```

3. Add `onSelectYear` method in `DateOfBirthPage` component to get the new selected year from `YearPickerPage` and register `onSelectYear` in `SelectYearAction`

```javascript
    useEffect(() => {
        const onSelectYear = (inputId, year) => {
            if (inputId !== 'dob') return;
            setSelectedYear(year.toString());
        }
        SelectYearAction.set(onSelectYear);
    }, [])
```

4.  Update `CalendarPicker` component by adding `id` prop to identify which `DatePicker` is  selected for `YearSelection`, It will setup `inputID` by `id` prop `onYearPickerPressed` callback.

```javascript
const propTypes = {
    /** A string to identify calendar picker */
    id: PropTypes.string,
    ...
}

onYearPickerPressed() {
        SelectYearAction.updateInputID(this.props.id);
        ...
}
```

5. Update `updateSelectedYear` method on `YearPickerPage` component .
original `updateSelectedYear` method:
https://github.com/Expensify/App/blob/98bb603a89fe0323d503157961c7f4fbfe0db45b/src/pages/YearPickerPage.js#L66-L77

after change:
```javascript
    updateSelectedYear(selectedYear) {
        SelectYearAction.emit(selectedYear);
        Navigation.goBack();
    }
```

<details><summary>Result</summary>

https://github.com/Expensify/App/assets/137529618/8879291f-5c0f-4dd9-824e-3b5e58306fdc

</details> 


### What alternative solutions did you explore? (Optional)
N/A

**Comment by joekaufmanexpensify** [comment] 2023-07-11 19:53
Pending review of updated proposal

**Comment by joekaufmanexpensify** [comment] 2023-07-12 18:45
Sounds good, thanks!

**Comment by mountiny** [comment] 2023-07-12 20:28
I am curious is this still a bug after the Calendar refactor we did here https://github.com/Expensify/App/pull/21792?

**Comment by joekaufmanexpensify** [comment] 2023-07-13 18:28
Ah, yep good call. I just rechecked now, and it looks like this was fixed by that PR. We no longer specify the year in the link when you change the year of birth in the date picker. So I feel like we can go ahead and close this. Does that sound good to everyone?

**Closed** 2023-07-13 18:31 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
