### ISSUE TITLE
 mWeb - Assign Task Description field shows as multiline

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21433] opened 2023-06-23 17:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Press FAB and choose Assign Task
## Expected Result: 
Description field initially shows as a single line like in other platforms
## Actual Result: 
Description field initially shows as a multi line

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/0fe98825-7d89-45ea-86cd-d3322cae692e" width="40%" height="40%">

<img src="https://github.com/Expensify/App/assets/43996225/b3d94d29-1629-4501-987d-bf3243816531" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686997207642659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by greg-schroeder** [comment] 2023-06-23 22:05
Asking if this should be fixed separately from https://github.com/Expensify/App/issues/19135

**Comment by bernhardoj** [comment] 2023-06-24 04:30
@kavimuru Thanks for creating the issue, but we already have the same report (by applause) here https://github.com/Expensify/App/issues/21280. I have added a [comment](https://github.com/Expensify/App/issues/21280#issuecomment-1602335945) there to add me as the reporter. Maybe we can either add me to the reporter in that issue or close that in favor of this?

**Comment by manjesh-yadav** [comment] 2023-06-25 11:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The description field show multiline line in the safari 
### What is the root cause of that problem?

When we implement auto-grow text input, we use a hidden `<Text>` component to calculate the component's height to grow `<TextInput>` because the `<TextInput>` component doesn't support auto-grow.

We calculate height and width for input when React fired a `NativeEvent` called `onLayout` when our hidden  `<Text>` component rendered 

- The problem comes with Safari web browser (also in the Desktop application) when initially component is rendered with no value React is not able to fire `NativeEvent`
- And we are not able to calculate the height  of the hidden `<Text>`  component 
- Then our `<TextInput>` component render with max height CSS only


  





### What changes do you think we should make in order to solve the problem?

We just need a value in our hidden `<Text>` component  to fire `onLayout` event

It will work when we set a `placeholder` or if we have any `state value`, if we do not have a placeholder or state then just an **Empty string** will work, and later it will change with the `state value`

File: [App/src/components/TextInput/BaseTextInput.js](https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/components/TextInput/BaseTextInput.js#L374-L392)
```diff
-      {this.state.value || this.props.placeholder}
+    {this.state.value || this.props.placeholder || ' '}


```

**Comment by greg-schroeder** [comment] 2023-06-26 18:24
That issue was created first, so I'll close this as a duplicate.

**Comment by greg-schroeder** [comment] 2023-06-26 18:25
@bernhardoj i added you as the issue reporter on the other one as you reported it on June 17th

**Closed by greg-schroeder** 2023-06-26 18:24 UTC
Labels: Daily, Overdue, Bug

**Comment by bernhardoj** [comment] 2023-06-27 03:49
Sweet, thanks!
