### ISSUE TITLE
[Hold for payment] [$1000] Welcome Message Visibility Bug: User A Can See Welcome Message Intended for User B

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20990] opened 2023-06-18 15:27 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to web chrome and login with User A (mobile number as primary account) and create a Workspace
2. Now create a room with the same workspace in public mode (everyone)
3. Go to Room details > settings > welcome message > write message
4. Go to chat and write the message
5. Go to Room details >share code > copy code > send the code to User B
6. Open the room with User B and you will be able to see the welcome message which says “only visible to You (User B)”
7. Reply to the welcome message as User B
8. Reply to the chat room as User B
9. From User A, open the chat room and you will be able to see the welcome message intended for User B saying its 'ONLY visible to User B'
Expected Result: 
Message intended for User B should NOT be visible to User A (or “message ONLY visible to User B should be removed”)
Actual Result: 
Welcome message was visible to User A with a notation ‘only visible to User B’ 

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/3a4cd366-286c-413d-a483-6a2a0da3fa86

https://github.com/Expensify/App/assets/43996225/b8188c9e-773f-49d2-b15f-05f519cd39bb

**Expensify/Expensify Issue URL:**
**Issue reported by:** @avi-shek-jha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686355332887919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d954ce545b1fc7fc</li>
        <li>Upwork Job ID: 1670879410744987648</li>
        <li>Last Price Increase: 2023-06-26</li>
    </ul>
</details>

**Comment by NicMendonca** [comment] 2023-06-20 20:55
@aimane-chnaif bump on the above proposal ^^

**Comment by wildan-m** [comment] 2023-06-21 04:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In my opinion, this is expected behavior if the user is a workspace owner, so the owner can re-visit the welcome message chat thread from room chat.

I didn't see the chat message from a third account that is not a workspace owner.

The actual issue here is the text `Only visible to` doesn't mention anyone

<img width="238" alt="image" src="https://github.com/Expensify/App/assets/11847279/0f0b82f6-6713-4c30-b48f-25414e791337">

Please correct me if I'm mistaken.

### What is the root cause of that problem?

I've noticed that `props.personalDetails` always show an empty object in `ReportActionItem`. 

### What changes do you think we should make in order to solve the problem?

We can change it to `props.personalDetailsList` here

https://github.com/Expensify/App/blob/342d4fd84f3dda933c44a71b9e4d666d26b270c9/src/pages/home/report/ReportActionItem.js#L444

like what we did [here](https://github.com/Expensify/App/blob/342d4fd84f3dda933c44a71b9e4d666d26b270c9/src/pages/home/report/ReportActionItem.js#L380).

To make it make more sense, then we can add the workspace owner to the `whisperedTo` array, so the text will be `Only visible to you and newuser@email.com` it will require backend change to add the owner as `whisperedTo` item.

### What alternative solutions did you explore? (Optional)
N/A

**Comment by NicMendonca** [comment] 2023-06-23 19:33
@conorpendergrast I am going OOO until Wednesday. Can you watch this while I am away? I'll unassign you when I am back. Thank you!

**Comment by conorpendergrast** [comment] 2023-06-23 19:40
Of course! Toodles

**Comment by conorpendergrast** [comment] 2023-06-26 10:29
This is waiting for @aimane-chnaif 's review of the two proposals 👍

**Comment by conorpendergrast** [comment] 2023-06-27 09:53
@aimane-chnaif Hey! Would you like me to put this up for another C+ to review proposals?

**Comment by situchan** [comment] 2023-06-27 12:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When new member joins, welcome messages shows for workspace owner with wrong whisper title ("Only visible to").

### What is the root cause of that problem?
2 issues in `ReportActionItem` component:
- While doing `personalDetails` migration, we missed replacing `personalDetails` key with `personalDetailsList`
- When `whisperedToPersonalDetails` is empty (current user is not in `whisperedTo` list), no logic to hide message

### What changes do you think we should make in order to solve the problem?
- replace `personalDetails` key with `personalDetailsList` in all occurrences (propTypes, defaultProps and below line)
https://github.com/Expensify/App/blob/e5f00f86fb412702e9c212b5a88766a8ef7da611/src/pages/home/report/ReportActionItem.js#L444
- if isWhisper && whisperedToPersonalDetails is empty, early return null

### What alternative solutions did you explore? (Optional)

Solution 1: fix backend to not send whisper message to owner
Solution 2: fix backend to include owner email in `whisperedTo`

**Comment by pecanoro** [comment] 2023-06-27 14:33
This was fixed last week I think unless I missed something, let me try to reproduce it again. In any case, this should be a back-end fix as we should never send whispers to the unintended user.

**Comment by pecanoro** [comment] 2023-06-27 14:38
Ahh ok, I see the video now, this is a problem with threads. I bet that if the user signs out and signs in, they wouldn't see the thread. We need to stop sending pusher notifications when someone replies to a whisper or stop allowing threads on whispers altogether. It was probably missed because whispers were implemented before threads.

**Comment by pecanoro** [comment] 2023-06-27 14:44
Wait, one sec, who is seeing the whisper when it shouldn't? The owner should see the whisper for sure. Let me check the video again.

**Comment by pecanoro** [comment] 2023-06-27 14:45
>@pecanoro one more question: is there any case when one message whispered to multiple accounts?
I see whisperedTo is array so I believe that's possible case.

Not yet, in the future everyone will be able to send whispers, it's not a priority right now.

**Comment by pecanoro** [comment] 2023-06-27 14:48
Ahhh I saw the video again, this is totally expected, the welcome message is always sent from the owner account (expect for some Expensify workspaces). The only weird behavior that I see in the video is that after sending the welcome message to the user, the admin is not getting the pusher notification, but if that's the case, that would be different.

> But whisperedTo doesn't contain owner email.
Because the owner is the one sending it, whisperedTo is the people that what sent to. If the future userA will be able to send a whisper to userB and userA will be the owner of the action and userB will be in whisperedTo. The whisper should show to user A and user B.

**Comment by pecanoro** [comment] 2023-06-27 14:54
> ok so the only bug in frontend is no person indicating after Only visible to, right?

If it doesn't show, yes, that would be the bug. It's probably coming from the secure logins refactor. cc/ @Beamanator @puneetlath since we might have a bug with whispers according to the above message.

**Comment by pecanoro** [comment] 2023-06-27 14:56
> if joined member's login is [xxx@yyy.com](mailto:xxx@yyy.com). then owner should see Only visible to xxx@yyy.com instead of Only visible to you, right?

Exactly! Unless they have a display name, then it should show the display name

**Comment by pecanoro** [comment] 2023-06-27 14:57
@aimane-chnaif Either way, you are the one that identified that bug so I think you should report it and get the reporting bonus and then we should close this one as it's not a bug.

**Comment by pecanoro** [comment] 2023-06-27 15:07
Ok!! Up to you! We can fix it here, but that's the only thing we should fix and nothing else as we should still show the message to the workspace owner.

**Comment by pecanoro** [comment] 2023-06-28 17:41
I think this might get fixed here: https://github.com/Expensify/App/pull/21822

**Comment by robertjchen** [comment] 2023-06-29 17:06
Thanks for the discussion here! Given that this will be addressed in the https://github.com/Expensify/App/pull/21822 we should close this out. Are there any other actions we need to take here?

**Comment by pecanoro** [comment] 2023-06-29 17:07
You need to leave it open until we merge the PR to pay the reporting bonus or any review bonus

**Comment by robertjchen** [comment] 2023-06-29 17:11
Got it, thanks for the clarification! Since @pecanoro  did all the work here, I'll re-assign for credit! 🙇

**Comment by puneetlath** [comment] 2023-07-10 18:11
I believe this was fixed via https://github.com/Expensify/App/pull/21822 which was deployed to production 5 days ago. So @NicMendonca I think you just need to pay out the issue reporter and then this is good to go.

**Comment by tranvantoan-qn** [comment] 2023-07-11 11:59
FYI @puneetlath 
I just saw the issue again on staging, so it may not have been fixed or deployed yet. The dev team should probably recheck it.

![image](https://github.com/Expensify/App/assets/10254571/7fcf5949-2a2c-4d3c-9c42-95956e9a4f6b)

**Comment by tranvantoan-qn** [comment] 2023-07-11 14:15
@aimane-chnaif 
No - the **user A** - which is me is just a participant in this public room - **SNH** to be specific: 
https://staging.new.expensify.com/r/5303403427249671

**Comment by pecanoro** [comment] 2023-07-11 15:41
@tranvantoan-qn You need to provide some reproduction steps

**Comment by pecanoro** [comment] 2023-07-12 18:28
@NicMendonca Friendly reminder to pay the reporting bonus to @avi-shek-jha so we can close this 🙏

**Comment by pecanoro** [comment] 2023-07-12 18:40
Ahh you are right, @NicMendonca We also need to pay @aimane-chnaif for internal review!!

**Comment by NicMendonca** [comment] 2023-07-13 12:21
@avi-shek-jha @aimane-chnaif can you please apply to the job? https://www.upwork.com/jobs/~01d954ce545b1fc7fc

**Comment by avi-shek-jha** [comment] 2023-07-13 13:03
Thanks. Applied.

**Comment by NicMendonca** [comment] 2023-07-14 11:48
@aimane-chnaif sent you the offer

**Comment by NicMendonca** [comment] 2023-07-14 13:53
everyone has been paid! 🎉 thank all!

**Closed by NicMendonca** 2023-07-14 13:53 UTC
Labels: Reviewing, Daily, Internal, Bug
