### ISSUE TITLE
[HOLD for payment 2024-03-13] [$500] Search - Display names are bold regardless of unread state

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36075] opened 2024-02-07 20:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):** applausetester+0507gm@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
3. Click on the search bar

## Expected Result:

- Chats on the search page should display with their name bold when unread, and not bold otherwise, to match the chat list in the LHN
- Searching for a new chat should display the name in bold
- For the flow to start a new chat, or looking at a list of members, etc, use bold for the names

## Actual Result:
The display name of the chats is always bold, regardless of the unread state

## Workaround:
Ignore it

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

Staging

https://github.com/Expensify/App/assets/78819774/197cad8b-5d6b-47a1-a275-7953827a6b36

Production

https://github.com/Expensify/App/assets/26260477/c0f03ebf-3148-4f6d-a107-2000114a0f6f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e593cf467037a99c</li>
        <li>Upwork Job ID: 1757132725429215232</li>
        <li>Last Price Increase: 2024-02-12</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by shawnborton** [comment] 2024-02-07 21:48
Interesting, I wouldn't think this would be a blocker, it's been like this since we first created NewDot

**Comment by neil-marcellini** [comment] 2024-02-07 22:24
The display name is bold in search regardless of the unread status of that chat, so I don't understand why that's part of the test steps.

I think there is a small regression here, but it's very different than what's described in the current issue.


Here's the current behavior on prod
https://github.com/Expensify/App/assets/26260477/c0f03ebf-3148-4f6d-a107-2000114a0f6f


I will update the issue from what's currently described to something that's more clear.

Currently:
> ## Action Performed:
> 1. Navigate to staging.new.expensify.com
> 2. Click on any unread message
> 3. Click on other chat so the chat from step 2 is not bold anymore
> 4. Navigate to Search
> 
> ## Expected Result:
> Since the chat is open once the Display name of the sender should not be bold anymore
> 
> ## Actual Result:
> Display name remains bold in search when user open the conversation

New bug description:
## Action Performed:
1. Navigate to staging.new.expensify.com
3. Click on the search bar

## Expected Result:
The display name of the chats should **not** be bold

## Actual Result:
The display name of the chats is bold

Furthermore, this is a very minor regression, so I won't consider it a blocker.

**Comment by neil-marcellini** [comment] 2024-02-07 22:27
It would make more sense if the style of the chats on the search page matched the LHN. That's not the case on staging or prod. What do you think @shawnborton?

**Comment by bernhardoj** [comment] 2024-02-08 05:33
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The display name on the search page is bold.

### What is the root cause of that problem?
This happened after the search page used SelectionList (in https://github.com/Expensify/App/pull/35058). The selection list item has a bold style by default.
https://github.com/Expensify/App/blob/9f37d3e2c1264420773c886ae6171748e5d512b8/src/components/SelectionList/BaseListItem.tsx#L108

This can be seen on some page that already uses a selection list, such as the room member page.
<img width="383" alt="image" src="https://github.com/Expensify/App/assets/50919443/fc563366-8b3f-405f-af37-280663545186">

### What changes do you think we should make in order to solve the problem?

If we want to bold it only when the chat is unread, we can add a new attribute to the list item called `isBold` and only apply the bold style if isBold is not false.
```
item.isBold !== false && styles.sidebarLinkTextBold,
```

Then, we need to map the report array here to include `isBold` attribute
https://github.com/Expensify/App/blob/9f37d3e2c1264420773c886ae6171748e5d512b8/src/pages/SearchPage/index.js#L95

```
data: recentReports.map(report => ({...report, isBold: report.isUnread})),
```

### What alternative solutions did you explore? (Optional)
If we want to disable the bold for all items, we can add a new props to the SelectionList itself to disable the bold style.

Or if we don't want to bold a list item that is a user list item, then we can apply the bold style only if it's not a user list item.
`!isUserItem ? styles.sidebarLinkTextBold : null,`

**Comment by shawnborton** [comment] 2024-02-08 13:39
@trjExpensify or @JmillsExpensify or @Expensify/design do you have any context on this one?

As far as I know, results in the chat search list were **always** bold. And this is because that's our standard pattern for displaying this kind of information in a list. 

Then at some point, we made the workspace switcher use this bold or non-bold pattern depending on if there was unread messages or not. 

I think for the chat switcher, it does make sense that the chat matches how it would look in the LHN. So if the chat is unread, keep it bold. If the chat is read, make it not-bold. 

But for things like the flow to start a new chat, or looking at a list of members, etc - I think we should keep our current pattern and use bold for the names. 

Let me know if all of that makes sense!

**Comment by shawnborton** [comment] 2024-02-08 15:19
> Reason being is that it's kinda weird that a new chat with someone you've never chatted with would be bold (denoting it has unread messages).

Totally fair, but I think of that as something that actually doesn't exist in your LHN, and thus would just follow the standard list option patterns we have?

**Comment by shawnborton** [comment] 2024-02-08 20:16
Hmm but it wouldn't appear in your LHN like that. So I still think for the create case, we should mimic what we do for our generic list/option views where the title is bold. Because in your LHN, it actually looks something more like this (it has the preview line): 
![CleanShot 2024-02-08 at 15 16 01@2x](https://github.com/Expensify/App/assets/2319350/e4ed71a0-995d-4449-88e1-32107a7beef9)

**Comment by dubielzyk-expensify** [comment] 2024-02-08 23:31
I think because they're different contexts they don't have to follow the same pattern. I kinda lean towards bold for the reasons @shawnborton mentioned.

**Comment by neil-marcellini** [comment] 2024-02-12 19:58
Ok so it sounds like this is the desired behavior. I'm going to update the issue description and send it to be implemented externally.

- Chats on the search page should display with their name bold when unread, and not bold otherwise, to match the chat list in the LHN
- Searching for a new chat should display the name in bold
- For the flow to start a new chat, or looking at a list of members, etc, use bold for the names

**Comment by kmbcook** [comment] 2024-02-13 22:28
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Search - Display names are bold regardless of unread state

### What is the root cause of that problem?
See
- pages/SearchPage/index.js
- components/SelectionList/BaseSelectionList.tsx
- components/SelectionList/BaseListItem.tsx

SearchPage includes BaseSelectionList which defines renderItem function. That function returns BaseListItem. BaseListItem always includes the style styles.sidebarLinkTextBold.

### What changes do you think we should make in order to solve the problem?
See
- components/LHNOptionsList/OptionRowLHN.tsx

In BaseListItem, include a prop named something like alwaysBold and set it to true by default.

In BaseListItem, if alwaysBold is false, use the same logic as is used in OptionRowLHN to determine whether or not to use bold. That logic is found in definition of textUnreadStyle.

SearchPage is not the only component to include BaseSelectionList. Therefore, in BaseSelectionList also include an alwaysBold prop with default value of true and pass it to BaseListItem. In SearchPage, send alwaysBold={false} to BaseSelectionList.

**Comment by abdulrahuman5196** [comment] 2024-02-16 08:44
As per the implementation requirements here https://github.com/Expensify/App/issues/36075#issuecomment-1939464168 , @bernhardoj 's proposal here https://github.com/Expensify/App/issues/36075#issuecomment-1933392317 looks good and works well. It can be little modified to match all the requirements which we could take care in PR state and it is also the first proposal.

🎀 👀 🎀
C+ Reviewed

**Comment by dylanexpensify** [comment] 2024-02-20 09:41
@neil-marcellini mind confirming proposal is acceptable?

**Comment by abdulrahuman5196** [comment] 2024-02-22 13:27
@neil-marcellini Bump on this?

**Comment by dylanexpensify** [comment] 2024-02-26 11:15
DM'ing Neil!

**Comment by neil-marcellini** [comment] 2024-02-26 22:13
Sorry for the delay, looking now

**Comment by neil-marcellini** [comment] 2024-02-26 22:15
> As per the implementation requirements here [#36075 (comment)](https://github.com/Expensify/App/issues/36075#issuecomment-1939464168) , @bernhardoj 's proposal here [#36075 (comment)](https://github.com/Expensify/App/issues/36075#issuecomment-1933392317) looks good and works well. It can be little modified to match all the requirements which we could take care in PR state and it is also the first proposal.
> 
> 🎀 👀 🎀 C+ Reviewed

I agree, hiring!

**Comment by bernhardoj** [comment] 2024-02-27 14:42
PR is ready

cc: @abdulrahuman5196

**Comment by dylanexpensify** [comment] 2024-02-28 08:55
wooot!

**Comment by dylanexpensify** [comment] 2024-03-06 11:15
PR merged, pending payout after regression period

**Comment by bernhardoj** [comment] 2024-03-07 13:08
@youssef-lr before the PR, all items on the search page are in bold. Then, we agree to bold it only when the chat is unread. Personal details don't have an unread state, so they stay bold.

**Comment by youssef-lr** [comment] 2024-03-07 13:10
Ah okay, thanks for clarifying!

**Comment by dylanexpensify** [comment] 2024-03-13 10:34
payment today! @abdulrahuman5196 mind completing checklist

**Comment by dylanexpensify** [comment] 2024-03-19 09:58
bump @abdulrahuman5196 on checklist. Paying out now

**Comment by dylanexpensify** [comment] 2024-03-19 10:01
payments done! Will close after Abdul does checklist

**Comment by abdulrahuman5196** [comment] 2024-03-23 14:56
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Seems to be the case for sometime.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open search page
2) Verify the user display name is bold when you have unread chats
3) Search for a new user
4) Verify the user display name is bold

@dylanexpensify

**Closed** 2024-03-25 10:59 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug

**Comment by trjExpensify** [comment] 2024-03-25 12:32
👋 Is [this bug report](https://github.com/Expensify/App/issues/38704) from @iwiznia related to whatever we did to fix this issue?

**Comment by bernhardoj** [comment] 2024-03-25 14:36
What we do here is to bold the search page item when there are unread items. In https://github.com/Expensify/App/issues/38704, looks like it works correctly in search page, but not on the LHN (can't reproduce though).
