### ISSUE TITLE
[HOLD for payment 2023-10-27] [$500]  IOS- Receipt border radius is not round

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29230] opened 2023-10-10 20:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.80.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696931354301509

## Action Performed:
1. Go to any chat
2. Click on + icon and select request money option
3. Request money manually
4. Go to transaction thread
5. Click on three dots and add receipt
6. Go back to previous screen
7. Verify the receipt border radius

## Expected Result:
receipt border radius should be round

## Actual Result:
 receipt border radius not round

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

 

https://github.com/Expensify/App/assets/93399543/b19225b2-6ffa-4e78-9ba7-8101849e7043

![IMG_6671 (1)](https://github.com/Expensify/App/assets/93399543/e1384520-1ce2-450c-9242-d60d4fcef565)

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9f60635e933b6e7</li>
        <li>Upwork Job ID: 1711836727727636480</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>eh2077 | Contributor | 27239377</li>
<li>gadhiyamanan | Reporter | 27239379</li>
</ul></li>
    </ul>
</details>

**Comment by vadymbokatov** [comment] 2023-10-10 21:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt border radius is not round
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/b5445bd0da78132d602b2f3de36a19b1cf495fce/src/styles/styles.js#L3588-L3599
It seems that the value assigned to `borderTopLeftRadius` and `borderTopRightRadius` is not enough (which is 16 btw).
### What changes do you think we should make in order to solve the problem?
increase the `borderTopLeftRadius` and `borderTopRightRadius` value

**Comment by ikevin127** [comment] 2023-10-10 22:25
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Receipt border radius should be rounded.

## What is the root cause of that problem?
The problem comes from the fact that `ThumbnailImage` and `Image`  rendered components from within the `ReportActionItemImage.js` component do not have **borderRadius** styles applied:

https://github.com/Expensify/App/blob/11acdc2a4918859a3e1b8dfe23f10ad9a6f24218/src/components/ReportActionItem/ReportActionItemImage.js#L41-L53

This causes both receipt and receipt placeholder pictures to not have rounded borders since currently both only have `style={[styles.w100, styles.h100]}` styles applied.

## What changes do you think we should make in order to solve the problem?
Add `styles.reportContainerBorderRadius` to both rendered components which will match the same borderRadius as the card has, like so:

```diff
    const receiptImageComponent = thumbnail ? (
        <ThumbnailImage
            previewSourceURL={thumbnailSource}
-            style={[styles.w100, styles.h100]}
+            style={[styles.w100, styles.h100, styles.reportContainerBorderRadius]}
            isAuthTokenRequired
            shouldDynamicallyResize={false}
        />
    ) : (
        <Image
            source={{uri: image}}
 -         style={[styles.w100, styles.h100]}
+            style={[styles.w100, styles.h100, styles.reportContainerBorderRadius]}
        />
    );

```

## What alternative solutions did you explore? (Optional)
N/A

## Videos

<details>
<summary>iOS</summary>



https://github.com/Expensify/App/assets/56457735/806ab2e1-7d41-4409-9391-194463c778cb

</details>

**Comment by yh-0218** [comment] 2023-10-11 04:34
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Receipt border radius should be rounded.
### What is the root cause of that problem?
We don't have borderRadius to wrapper of `ReportActionItemImage`
### What changes do you think we should make in order to solve the problem?
We need to add borerRadius and overflow: hidden to wrapper.
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/components/ReportActionItem/ReportActionItemImages.js#L64
Need to add `reportActionItemImage`
```
        borderRadius: variables.componentBorderRadiusLarge - 4,
        overflow: 'hidden',
```
https://github.com/Expensify/App/blob/562f9d8ff66d1e90285df088fa785c9638aa3861/src/styles/styles.js#L3588
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2023-10-13 15:25
@allroundexperts could you review the proposals here?

**Comment by eh2077** [comment] 2023-10-13 15:48
I'm going to post a proposal to fix this issue.

**Comment by eh2077** [comment] 2023-10-14 06:59
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

 IOS- Receipt border radius is not round

### What is the root cause of that problem?

The root cause of issue is from RN lib. On iOS platform, border radius is not working when using transparent border color. 

See style of `reportActionItemImages`

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/styles/styles.ts#L3711-L3719

We can reproduce it using snack: https://snack.expo.dev/@eh2077/4c412a?platform=ios

iOS

https://github.com/Expensify/App/assets/117511920/a84a8a04-461f-4802-ac58-797c52eb5a49

I reported this issue to upstream RN repo, see https://github.com/facebook/react-native/issues/40969

It seems that the transparent or opacity border issue is tricky in RN, see also https://github.com/facebook/react-native/issues/39286

### What changes do you think we should make in order to solve the problem?

From the style of `reportActionItemImages`

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/styles/styles.ts#L3711-L3719

We're using `border-width: 4` and `border-color: 'transparent'` to introduce 4px space between image and the container.

We can use `margin: 4` to achieve the spacing we want instead of using `border-width` and `border-color`.

We can just replace

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/styles/styles.ts#L3713-L3714

with

```js
            margin: 4,
```

By doing so, we can get rid of the tricky inconsistent case of RN and solve the issue on iOS. Note we need to ensure the fix works for one or more than one receipts. See demo

https://github.com/Expensify/App/assets/117511920/7b9dd958-13f0-4c85-825a-5f127dd33b64

### What alternative solutions did you explore? (Optional)

N/A

**Comment by lschurr** [comment] 2023-10-26 05:46
Could you work on the checklist for this one @allroundexperts? Thanks!

**Comment by lschurr** [comment] 2023-10-26 05:47
Payment summary:

- Bug reporter: @gadhiyamanan $50
- Contributor: @eh2077 $750
- Contributor+: @allroundexperts $750

**Comment by lschurr** [comment] 2023-10-27 17:05
Payments made in Upwork for @eh2077 and @gadhiyamanan.

Bump @allroundexperts for the checklist :)

**Comment by lschurr** [comment] 2023-10-30 15:34
All set!

**Closed by lschurr** 2023-10-30 15:34 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-03 21:52
$750 payment approved for @allroundexperts based on BZ summary.
