### ISSUE TITLE
[HOLD for payment 2024-08-01] [$50] Search icon has no safe area around and its hard to tap

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#45198] opened 2024-07-10 18:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @mountiny 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1720613707699899

## Action Performed:
1. Launch the app
2. Tap the Search icon for the chat selector
## Expected Result:
The search icon tappable should be around the button anywhere
## Actual Result:
Search icon seems so have super small safe area around, you really need to tap exactly on the search icon to open 
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![image (12)](https://github.com/Expensify/App/assets/38435837/fb52bfb2-99fb-4b67-9490-3a0d654759a1)

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011f8d2de869135cc4</li>
        <li>Upwork Job ID: 1811159428371033529</li>
        <li>Last Price Increase: 2024-07-10</li>
<li>Automatic offers: </li>
<ul>
<li>rayane-djouah | Contributor | 103071138</li>
</ul></li>
    </ul>
</details>

**Comment by neonbhai** [comment] 2024-07-10 19:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Search icon seems so have super small safe area around, you really need to tap exactly on the search icon to open

### What is the root cause of that problem?
We don't have any padding around the Search icon, making the hitbox small.

### What changes do you think we should make in order to solve the problem?
We will add `styles.p1` to the button styles here, so the hitbox is bigger. 

https://github.com/Expensify/App/blob/98932a26522e75239b5c7b73fda519f84936f75c/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/TopBar.tsx#L62-L66

```jsx
style={[styles.flexRow, styles.mr2, styles.p1]}
```

### Result
<Details><Summary>Before</Summary>
Hitbox in red. Area is small and easy to miss
<img width="349" alt="Screenshot 2024-07-11 at 12 38 27 AM" src="https://github.com/Expensify/App/assets/64629613/637e366e-09ae-46a3-8132-efdd179a16fa">


</Details>


<Details><Summary>After</Summary>
Hitbox in red. Added breathing space
<img width="349" alt="Screenshot 2024-07-11 at 12 36 59 AM" src="https://github.com/Expensify/App/assets/64629613/2201f9cc-e236-4d38-b1b2-0f130f0f91c4">

Without hitbox highlight:


</Details>

**Comment by mountiny** [comment] 2024-07-10 22:03
I will make this external for $50 as its super easy

**Comment by mountiny** [comment] 2024-07-10 23:23
@Krishna2323 lets stick with $50 for now and see if there will be any reason to bump to $125.

**Comment by mountiny** [comment] 2024-07-10 23:41
44x44 is the apple standard minimum for the button so lets try to implement that please @Krishna2323 thanks!

**Comment by mountiny** [comment] 2024-07-12 15:40
> I think we can use shouldUseAutoHitSlop PressableWithFeedback's property for this

I think this sounds like a good idea

**Comment by mountiny** [comment] 2024-07-12 23:21
@Krishna2323 what is your eta for the PR? Thanks!

**Comment by anmurali** [comment] 2024-08-06 02:59
@rayane-djouah is paid
@Krishna2323 can you pls link me your Upwork profile?

**Comment by anmurali** [comment] 2024-08-14 02:13
@Krishna2323 offer is [here](https://www.upwork.com/nx/wm/offer/103516850)

**Comment by anmurali** [comment] 2024-08-26 23:59
This was paid a while back. Closing!

**Closed by anmurali** 2024-08-26 23:59 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
