### ISSUE TITLE
[HOLD for payment 2023-10-16] [$500]  Chat - App removes space from start for text below header text

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27445] opened 2023-09-14 14:19 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open any report
3. Send message with normal text in first line and some space before text in next line
4. Copy that text or edit and observe that space is preserved in second line which is correct
5. Now send message with header text (# in front) in first line and some space before text in next line
5. Copy that text or edit and observe that it removes the space before second line text

## Expected Result:
App should preserve space added before text in second or any other line except first line

## Actual Result:
App does not preserve space added before text in second or any other line if first line has header text (text with # in beginning)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/48092923-f4cd-4961-ad2b-3cb3fc86a02e

https://github.com/Expensify/App/assets/93399543/50fb7f16-52fd-4823-9ae6-f5b5db980a2d

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694453805196449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a29ca52e1304c30b</li>
        <li>Upwork Job ID: 1702326265887232000</li>
        <li>Last Price Increase: 2023-09-14</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 26744986</li>
<li>dhanashree-sawant | Reporter | 26744992</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by s-alves10** [comment] 2023-09-14 15:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

App removes spaces at the beginning of the line below header text

### What is the root cause of that problem?

We have html-to-markdown rule regarding heading [here](https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L284-L286)

```
        regex: /[^\S\r\n]*<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))[^\S\r\n]*/gi,
```
As you can see, we match space characters(and \r\n) before and after the heading tag. The result is shown below
![image](https://github.com/Expensify/App/assets/126839717/63823be9-b31f-467c-a685-9afbd1ef8719)

This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to match only the <h1>xxx</h1> part of the string
Removing `[^\S\r\n]*` from the start and end will preserve all space characters and newline characters before and after the heading string. So the new regex would be

```
        regex: /<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))/gi,
```

In case we don't want to preserve before the heading, we should keep `[^\S\r\n]*` at the beginning, but I don't think we need to  discard them.

<details>
    <summary>Result</summary>


</details>


### What alternative solutions did you explore? (Optional)

**Comment by jaylalakiya** [comment] 2023-09-15 03:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App removes spaces before line where previous line is header text. This problem is not only with selected platforms in issue description, but instead it persists on all the platforms.

### What is the root cause of that problem?
When the html is converted to markdown it removes trailing spaces after heading tag even if there is text after trailing spaces which causes this behaviour of removing leading spaces from next line

### What changes do you think we should make in order to solve the problem?
We should modify regex to not remove trailing spaces because trailing spaces are trimmed somewhere else.
Current regex: /[^\S\r\n]*<(h1)(?:"[^"]*"|'[^']*'|[^'">])*>(.*?)<\/\1>(?![^<]*(<\/pre>|<\/code>))[^\S\r\n]*/gi
We should remove trailing spaces regex [^\S\r\n]*

This is not a breaking change as it only removes trailing spaces and not leading spaces (see video attached below). Trailing spaces are trimmed [here](https://github.com/Expensify/expensify-common/blob/35bff866a8d345b460ea6256f0a0f0a8a7f81086/lib/ExpensiMark.js#L574) in case there is no text after spaces.

Result:
https://github.com/Expensify/App/assets/63226109/0982d02f-58f3-4213-a5ba-7b08393d1891

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-09-15 05:24
@parasharrajat 

Issue description [updated](https://github.com/Expensify/App/issues/27445#issuecomment-1719639362)

**Comment by jaylalakiya** [comment] 2023-09-18 04:27
@parasharrajat Please can you review this
[comment](https://github.com/Expensify/expensify-common/pull/576#issuecomment-1722629208)

**Comment by s-alves10** [comment] 2023-09-18 10:59
@parasharrajat 

> But Can you tell me if it does not break Expensify/expensify-common#531?

Yeah. Tests include them but my solution passed all of them

> I think we should trip whitespaces before the heading. it does not make sense to have spaces before heading.

We can keep `[^\S\r\n]*` before <h1>

**Comment by s-alves10** [comment] 2023-09-19 06:04
@parasharrajat 

[PR](https://github.com/Expensify/expensify-common/pull/577) is ready for review

**Comment by s-alves10** [comment] 2023-09-20 15:06
@parasharrajat 

May I ask who is responsible for reviewing the PR?

**Comment by marcaaron** [comment] 2023-09-25 05:07
What is the status on this one? I see you left some comments @parasharrajat but could not assign you to the review.

**Comment by anmurali** [comment] 2023-09-27 13:52
@parasharrajat what's the update here?

**Comment by marcaaron** [comment] 2023-10-02 20:58
PR has been merged now. So I think we are just waiting on an App PR to bump the version of `expensify-common`.

**Comment by s-alves10** [comment] 2023-10-05 23:03
PRs were merged without any changes.

**Comment by anmurali** [comment] 2023-10-24 21:47
- [ ] @parasharrajat $500 (Eligible for Manual Requests)
- [ ] @s-alves10 $500[offer](https://www.upwork.com/nx/wm/offer/26744986) (Contributor)
- [ ] @dhanashree-sawant $50 [offer](https://www.upwork.com/nx/wm/offer/26744992) (Reporter)

**Closed** 2023-11-01 03:50 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-04-01 21:01
$500 approved for @parasharrajat
