### ISSUE TITLE
[HOLD #37199][$500] Remove members out of a workspace are not crossed out in offline mode

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#37109] opened 2024-02-22 21:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.43-3
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @hoangzinh 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708519808525439

## Action Performed:

1. Go to Settings -> Workspace -> Open any WS -> Members
2. Invite several members
3. Turn off the internet connection
4. Remove WS members

## Expected Result:
Removed members should be strike out

## Actual Result:
Notice that members are disappearing instead of crossed out.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/13808d1d-d266-4010-b937-e97999501713

https://github.com/Expensify/App/assets/38435837/cc74e740-ceaf-4a2c-95f6-fc31108f76d7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016f83f55225363e92</li>
        <li>Upwork Job ID: 1760776518388736000</li>
        <li>Last Price Increase: 2024-02-22</li>
<li>Automatic offers: </li>
<ul>
<li>mkhutornyi | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by francoisl** [comment] 2024-02-22 21:46
I'm seeing something different now, there's a sort of placeholder div that remains. Still a bug nonetheless, going to check the current changes to see what caused this.

https://github.com/Expensify/App/assets/2229301/ee99cfb9-2494-4155-84a3-0571c2d4df4b

**Comment by francoisl** [comment] 2024-02-22 22:49
Yeah good catch, tested locally and it works well. Feel free to submit a PR plese @mkhutornyi.

**Comment by francoisl** [comment] 2024-02-22 23:30
Do you see a way to fix that regression? If you do, that's great and let's fix it too, otherwise we can put a comment in the PR to fix it later. Not a huge deal since that PR is not on staging yet.

**Comment by francoisl** [comment] 2024-02-22 23:33
Works for me.

**Comment by luacmartins** [comment] 2024-02-22 23:36
This is known https://github.com/Expensify/App/pull/37074#issuecomment-1959456354 and will be fixed when we update the remove functionality next

**Comment by luacmartins** [comment] 2024-02-23 18:34
Removing blocker label, since this is known.

**Comment by burczu** [comment] 2024-02-27 12:50
@mkhutornyi I've already addressed this issue in my PR regarding removing members on the members page, as stated in the mentioned comment: https://github.com/Expensify/App/pull/37199 - it's still in draft state but it will be published tomorrow.

**Comment by MitchExpensify** [comment] 2024-02-27 20:53
Should we close seeing as this is going to be fixed here https://github.com/Expensify/App/pull/37074#issuecomment-1959456354 and we don't have a universal solution identified yet - What do you think @parasharrajat ?

**Comment by burczu** [comment] 2024-02-28 09:40
> Ideally, can we fix this in `OfflineWithFeedback`? So that function as child would work with strikethrough. I'm concerned similar issue might happen in the future. This is already 2nd bug. 1st bug was #35702

Yeah - I'm working on this right now. Thanks for pointing this out.

**Comment by luacmartins** [comment] 2024-02-29 15:28
done

**Comment by MitchExpensify** [comment] 2024-04-01 15:40
Thanks @parasharrajat, let's close. I don't think any payment is due as nothing was ever merged but please let me know if anyone disagrees

**Closed** 2024-04-01 15:41 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
