### ISSUE TITLE
[$500] Android- IOU- Add stop point, Use your location shows error

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#29419] opened 2023-10-12 07:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

## Action Performed:
1. Launch app
2. Tap on any Workspace chat
3. Tap plus icon
4. Select Request money --- Distance
5. Enter start and finish way points
6. Tap Add stop point
7. Tap " Use your location "

## Expected Result:
Tapping " Use your location " must detect user's location.

## Actual Result:
Tapping " Use your location " Shows error message "we were unable to find your location".

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/App/assets/115492554/e423ef61-0488-4e9a-9fd3-8f983daf92d1

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dcea4f09880ba901</li>
        <li>Upwork Job ID: 1712370069682274304</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by akinwale** [comment] 2023-10-12 11:07
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On Android, when adding a stop, "Use your location" triggers an error.

### What is the root cause of that problem?
This is an intermittent error which occurs due to the location request failing due to a timeout which could be caused by a bad GPS signal. It can also be recreated by turning off the GPS signal in the Android emulator settings. 

The returned error data for this is:
```
{"ACTIVITY_NULL": 4, "PERMISSION_DENIED": 1, "POSITION_UNAVAILABLE": 2, "TIMEOUT": 3, "code": 3, "message": "Location request timed out"}
```

### What changes do you think we should make in order to solve the problem?
There are two things we can do to improve the experience in this case:
1. Increase the timeout for the `getCurrentPosition` call in the UserCurrentLocationButton component. We can set this to `30000` or any value that is determined to be reasonable.

https://github.com/Expensify/App/blob/9699988a0354e619b04d5b47c1b5b29936952c38/src/components/UserCurrentLocationButton.js#L71

2. Display a more descriptive or helpful error message if the error code is 3 which indicates that the request timed out.

### What alternative solutions did you explore? (Optional)
None.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 14:25
Not overdue. Going to triage today

**Comment by joekaufmanexpensify** [comment] 2023-10-16 22:01
I don't think this is a bug. As the proposal above mentions, this is because of a GPS issue. This is working for me. If there is a GPS issue, the error message we're displaying now provides sufficient direction to the user for next steps.

**Comment by joekaufmanexpensify** [comment] 2023-10-16 22:01
Closing!

**Closed by joekaufmanexpensify** 2023-10-16 22:01 UTC
Labels: External, Daily, Bug
