### ISSUE TITLE
[$250] Workspace chat - Approve button appears briefly Instead of pay.

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49281] opened 2024-09-16 16:37 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-7
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** biruknew45+973@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create a new workspace.
3. Submit an expense in the workspace chat.
4. Hold the submitted expense.
5. Create another workspace and submit an expense in that workspace chat.
6. Go to Settings > Troubleshoot > Clear Cache, then quickly return to the workspace chat from step 5.

## Expected Result:
After clearing the cache, the skeleton UI should appear, followed by the Pay button.

## Actual Result:
The "Approve" button briefly appears before quickly switching to the Pay button.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/6d744c01-a75f-48d5-b399-9703410db135

![Bug6605484_1726493428904!1](https://github.com/user-attachments/assets/9f1719de-22de-45d7-a0f6-1c7c0e7747aa)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021836562014848142699</li>
        <li>Upwork Job ID: 1836562014848142699</li>
        <li>Last Price Increase: 2024-09-19</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @danieldoglas</details>

**Comment by izarutskaya** [comment] 2024-09-16 16:38
We think this issue might be related to the #collect project.

**Comment by CyberAndrii** [comment] 2024-09-17 13:57
This is because the `OpenApp` request response is missing the `approverMode` property for the second workspace (unlike the first). This causes the `isSubmitAndClose` function to incorrectly return `false`.

https://github.com/Expensify/App/blob/2190f6279041ed8260752294d095bbdda76faebe/src/libs/actions/IOU.ts#L6918-L6921

After some delay `approverMode` will be set by the `OpenReport` request and the correct button will be displayed.

**Comment by danieldoglas** [comment] 2024-09-19 19:19
Yes, that was by design. We only return all the details for the default policy and a smaller version of the other ones. 

@strepanier03 Do you think this is a bug that requires fixing (the button changing after the report is loaded)? If yes, I can add `approverMode` to the other policies.

**Comment by danieldoglas** [comment] 2024-09-19 19:24
@paultsimura do we have a loading pattern for buttons anywhere else that you know of?

**Comment by danieldoglas** [comment] 2024-09-19 19:33
But that page is not accessible if we're offline, right?

**Comment by danieldoglas** [comment] 2024-09-19 20:28
I see, thanks!

@strepanier03 do you think we need to discuss this internally if we add the loading button?

**Comment by trjExpensify** [comment] 2024-09-20 00:49
Wouldn't that result in an infinite spinner offline in this case? I feel like adding `approverMode` is the better UX option, personally.

**Comment by danieldoglas** [comment] 2024-09-20 17:46
@marcaaron we were discussing sending the policy list to be processed in Auth yesterday - is that something you're going to do soon? If yes, do you wanna assign yourself from this issue? We'll need to include a new property (`approverMode`) when returning policy list on OpenApp.

**Comment by marcaaron** [comment] 2024-09-20 19:40
>is that something you're going to do soon?

Ah not really, it was just a suggestion - something we'd probably do whenever it's more of a priority to work on. 

I'd be open to looking into it as part of this ticket you'd rather pass it off. Checking the current implementation and it should be pretty straightforward to migrate this.

However, I don't think we have an `approverMode` property. Did we mean `approvalMode`?

>Create another workspace and submit an expense in that workspace chat.
>Go to Settings > Troubleshoot > Clear Cache, then quickly return to the workspace chat from step 5.

These test steps are very sus to me. What are we trying to achieve exactly? Is there a real bug that affects users? If so, how does it happen organically?

We don't necessarily have to move the whole `policySummaryList` to Auth to complete this ticket seems enough to add the `approvalMode` [here](https://github.com/Expensify/Auth/blob/c4f870cb163b822f138bb904831330d3223b5151/auth/lib/Policy.cpp#L533C1-L534C1) and [here](https://github.com/Expensify/Web-Expensify/blob/bcce3dd99344ef47b73ce92111ef985123724261/lib/AppInit.php#L86C1-L87C1). And I guess also keeping in mind that the more stuff we add to the policy summary the larger it gets. But this is a very simple value so it's probably OK.

**Comment by danieldoglas** [comment] 2024-09-20 21:11
@marcaaron I agree with you about just adding the new property. My question was more like - `if we're moving this to Auth, we can do it all together`. If we're not planning on doing that right now, I can add them in auth/php. Thanks for looking into it!

**Comment by danieldoglas** [comment] 2024-09-24 18:28
Removing help wanted and external since it's an internal change.

moving to weekly since it's not urgent.

**Comment by trjExpensify** [comment] 2024-09-25 01:09
Moved this into my list of internal bugs in core flows (i.e approving, submitting, paying etc) as we approach wrapping up #wave-collect.

**Comment by danieldoglas** [comment] 2024-10-01 18:40
moving to daily so I can address it this week

**Comment by danieldoglas** [comment] 2024-10-07 14:34
Both PRs were created and waiting for merge

**Comment by danieldoglas** [comment] 2024-10-09 19:04
Everything was deployed. Adding retest label

**Comment by mvtglobally** [comment] 2024-10-30 09:43
Issue not reproducible during KI retests. (Second week)

**Comment by danieldoglas** [comment] 2024-10-31 14:13
Yep, let's close it!

**Closed by danieldoglas** 2024-10-31 14:13 UTC
Labels: Reviewing, Weekly, Internal, Bug, retest-weekly
