### ISSUE TITLE
[HOLD for payment 2024-12-16] Web - Taxes - RBR shown on expense preview without any errors in the transaction thread

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52748] opened 2024-11-19 09:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.64-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/52309
**Email or phone of affected tester (no customers):** applausetester+nl797@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Create a workspace
3. Enable tax feature
4. Add a tax
5. Create an expense with the added tax on step 4

## Expected Result:
No RBR on the expense

## Actual Result:
RBR shown without any errors in the transaction thread

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
https://github.com/user-attachments/assets/916d1666-0801-4d23-877e-c989a4d93482
 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by JmillsExpensify** [comment] 2024-11-26 21:20
I actually forget if this is by design. @MonilBhavsar can you clarify?

**Comment by MonilBhavsar** [comment] 2024-11-27 05:31
https://github.com/Expensify/App/issues/41401#issuecomment-2094301452 https://github.com/Expensify/App/pull/41649#issuecomment-2109228051

Reading through these comments.

Looks like we no longer display taxRateChanged and taxAmountChanged notice violation because we have system messages and reviewer/approver can know if it has changed.
That sounds good!

If so, we need to stop sending these violations from server at all for newDot requests and not add any conditional logic on the client side. Also remove the code we have currently

**Comment by MonilBhavsar** [comment] 2024-12-10 05:09
no payment is due here. Closing

**Closed by MonilBhavsar** 2024-12-10 05:09 UTC
Labels: Weekly, Awaiting Payment, Bug
