### ISSUE TITLE
[$500] Deeplinking to distantce request money allows requesting 0 amount

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29401] opened 2023-10-12 00:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @lidiyakelay
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696946373513129

## Action Performed:
1. go to + FAB
2. Click on request money
3. click on distance tab
4. go to the url 'https://staging.new.expensify.com/request/new/distance' change distance to 'participants'
## Expected Result: 
the url redirects back
## Actual Result:
 url goes to participants allowing user to request  0  amount

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/190f7490-9915-45c2-b331-d3c2b0a19de2

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/e24bbd74-81fc-42c8-854f-866b427a247e

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/c376c944-6e0c-4af2-bd90-e51edeac747e

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b1f3e4d9495c91ca</li>
        <li>Upwork Job ID: 1712257041055375360</li>
        <li>Last Price Increase: 2023-10-12</li>
    </ul>
</details>

**Comment by graylewis** [comment] 2023-10-12 00:35
This seems related to this ongoing refactor: https://github.com/Expensify/App/issues/26538.

There's a pretty clear fix here: check if there are defined waypoints in the request and trigger goBack if there isn't. This was already attempted here: https://github.com/Expensify/App/pull/27826 
It failed because the waypoints weren't defined in the first frame. This could probably be fixed with a well-defined dependency array in useEffect.

 If it's still deemed worthwhile to attempt another patch while the refactor is ongoing, I'd be happy to write a proper proposal @maddylewis

**Comment by maddylewis** [comment] 2023-10-26 01:01
PR is open / still holding

**Comment by maddylewis** [comment] 2023-11-09 01:49
looks like this has since merged - https://github.com/Expensify/App/pull/28308

@mollfpr - when you have a chance, could you confirm if this bug is still reproducible? ty!

**Comment by DylanDylann** [comment] 2023-11-09 07:16
This issue is resolved. Let's close

**Comment by mollfpr** [comment] 2023-11-09 14:45
I confirmed this issue is solved.


https://github.com/Expensify/App/assets/25520267/9e14f6f8-f430-42fa-a29e-42567848ad68



We can close the issue now.

**Closed** 2023-11-10 19:48 UTC
Labels: Daily, Internal, Bug
