### ISSUE TITLE
[$500] mWeb - App crashes when sending a PDF for the first time on new account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36386] opened 2024-02-12 22:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4302138
**Email or phone of affected tester (no customers):** vdargentotest+mweb021224@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with a new account
3. Go to any DM chat
4. Try to send the PDF file

## Expected Result:
The user should be able to send the PDF at the first attempt without any problem

## Actual Result:
The app crashes after trying to send the PDF

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b4cd3994-cb0c-441b-af16-8ddbbf79601e

[log1.txt](https://github.com/Expensify/App/files/14251637/log1.txt)

![default-file-icon (11)](https://github.com/Expensify/App/assets/78819774/966f3d4f-f693-469a-9e3e-e6c39a276525)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ab0dc71921c0bbf3</li>
        <li>Upwork Job ID: 1757172768493191168</li>
        <li>Last Price Increase: 2024-02-19</li>
    </ul>
</details>

**Comment by isabelastisser** [comment] 2024-02-14 17:34
Waiting for proposals.

**Comment by c3024** [comment] 2024-02-15 07:47
Unable to reproduce this bug on `main`.

**Comment by c3024** [comment] 2024-02-18 12:13
It worked fine here. Could you check again? @lanitochka17 


https://github.com/Expensify/App/assets/102477862/c290c883-f450-43b5-a364-00b52123e978

**Comment by lanitochka17** [comment] 2024-02-19 18:01
Issue is still reproducible on the latest build 1.4.42-4


https://github.com/Expensify/App/assets/78819774/e6b9c8fa-1c7d-4499-9383-e0813a7822fc

**Comment by isabelastisser** [comment] 2024-02-20 03:11
Waiting for proposals!

**Comment by isabelastisser** [comment] 2024-02-22 16:23
Reviewing!

**Comment by isabelastisser** [comment] 2024-02-22 16:35
I can't reproduce this on staging on my app either. Closing!

**Closed by isabelastisser** 2024-02-22 16:35 UTC
Labels: External, Daily, Help Wanted, Bug
