### ISSUE TITLE
Message composer  upper line border covered by description box in task chat

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22043] opened 2023-07-02 02:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open staging new dot
2. Go to a a task chat
3. Make the description longer(two lines or more)
4. Click on the composer and observe that the composers upper border line is hidden by the description box + icon and select assign task

## Expected Result: 
All composers borders should be visible
## Actual Result: 
Composers upper border is hidden

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/0a27ea58-ba26-4e44-b5b2-d8cf572a0fbf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688128731327849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by sophiepintoraetz** [comment] 2023-07-03 03:58
Unable to reproduce - [have left a comment](https://expensify.slack.com/archives/C049HHMV9SM/p1688356680351849?thread_ts=1688128731.327849&cid=C049HHMV9SM) for the reporter to give clearer steps. Closing until then

**Closed** 2023-07-03 03:58 UTC
Labels: Daily, Needs Reproduction, Bug
