### ISSUE TITLE
[$250] Expenses - Deleting expense, leads user to inbox, but search icon keeps marked in green

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44161] opened 2024-06-21 13:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** bellicoignacio@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the https://staging.new.expensify.com/
website.
2. Tap on the search icon.
3. Open any expense.
4. Tap on the three dots icon.
5. Tap on "Delete Expense"
6. Tap on "Delete"
7. Tap on the arrow on the top left corner.
8. Check which category is the user redirected and which icon is marked at the bottom of the screen.
9. Tap on the search icon.
10. Check if any action is triggered.
11. Tap on the inbox icon.
12. Tap on the search icon again.

## Expected Result:
After deleting an expense, the user should be redirected to the search section again, and in case of being redirected to inbox section, the inbox icon should be marked in green.

## Actual Result:
After deleting an expense, the user is redirected to the inbox section, but it's the search icon the one that is marked in green, despite the user not being in that section.
To go back to the search section, the user has to tap on the inbox icon and after that, tap on the search icon again.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/fe756af1-396b-41ec-8c3a-5a38f349e136

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
![Bug6519124_1718865047455!71b10c03-44ce-4d65-96c6-0c11ce500927](https://github.com/Expensify/App/assets/115492554/e493325b-ac69-461b-b3e3-d7b36911d9d5)

</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b5ad166859e0b136</li>
        <li>Upwork Job ID: 1805196266971123586</li>
        <li>Last Price Increase: 2024-07-15</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @suneox</details>

**Comment by izarutskaya** [comment] 2024-06-21 13:57
We think this issue might be related to the #collect project.

**Comment by huult** [comment] 2024-06-24 16:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Deleting expense, leads user to inbox, but search icon keeps marked in green
### What is the root cause of that problem?
We force navigate to the report screen when deleting an expense in the Search stack, and fallback to the Report stack. When navigating back, we retain the option of CentralPaneNavigator in the Search stack.
### What changes do you think we should make in order to solve the problem?
We need to use popToTop to reset the state of the Report stack, as demonstrated in the code below:
```diff
const onBackButtonPress = useCallback(() => {
    if (isReportOpenInRHP) {
        Navigation.dismissModal();
        return;
    }
+   Navigation.setShouldPopAllStateOnUP();
    Navigation.goBack(undefined, false, true);
}, [isReportOpenInRHP]);
```
<details>
<summary>POC</summary>

https://github.com/Expensify/App/assets/20178761/695536eb-8dbe-4ff3-9f5a-610fa939b027


</detais
### What alternative solutions did you explore? (Optional)

**Comment by mvtglobally** [comment] 2024-07-03 14:38
Issue not reproducible during KI retests. (First week)

**Comment by bfitzexpensify** [comment] 2024-07-17 14:32
Asking QA to re-test

**Comment by mvtglobally** [comment] 2024-07-17 14:58
Issue not reproducible during KI retests. (Second week)

https://github.com/user-attachments/assets/e8ab0a1b-e5da-4148-b6d5-47d0cf3ac99f

**Comment by bfitzexpensify** [comment] 2024-07-17 17:48
Nice, closing

**Closed by bfitzexpensify** 2024-07-17 17:48 UTC
Labels: External, Daily, Help Wanted, Bug
