### ISSUE TITLE
[HOLD for payment 2023-11-07] [$500] Scan -  App displays 'Split' in title on back from scan request money request

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28751] opened 2023-10-03 21:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Click on plus and click request money->scan
3. Select any file
4. Observe now it displays 'Manual' in header, select any user
5. Click on back and observe that now it displays 'Split' in header even though there is no option to add other user to split

## Expected Result:
 App should not display 'Split' in header when coming back from scan request as we don't allow adding user for split in scan request

## Actual Result:
App displays 'Split' in header when coming back from scan request even though we don't allow adding user for split in scan request

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.77.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ba11ac46-fd7d-4fff-b140-61705ec3b51f

https://github.com/Expensify/App/assets/93399543/2a3bcc2f-7528-46e7-8d86-a723b5313369

https://github.com/Expensify/App/assets/93399543/00a95b85-4f98-4e9b-99b1-2a2246dd0ba5

https://github.com/Expensify/App/assets/93399543/0b9a48dc-886d-473f-b30b-2eb1a257ff0d

https://github.com/Expensify/App/assets/93399543/7232ee71-e30c-41d3-920a-e912dc9f143e

https://github.com/Expensify/App/assets/93399543/9669b6b8-ab02-48d4-a411-7d6fd3c116a6

https://github.com/Expensify/App/assets/93399543/5f9e8d4f-c20a-4521-9d08-fa72e32f1ec5

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1696334987842689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011c86077fd238d8d9</li>
        <li>Upwork Job ID: 1709312814973755392</li>
        <li>Last Price Increase: 2023-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 27263280</li>
<li>DylanDylann | Contributor | 27263283</li>
<li>dhanashree-sawant | Reporter | 27263284</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by vadymbokatov** [comment] 2023-10-03 21:28
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
title of page changes from manual to split on back from scan request money 
### What is the root cause of that problem?
the root cause of the problem is this condition: 
https://github.com/Expensify/App/blob/81a6a529756c1492ca9d0f5fcc67b6dd2196c56e/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L57-L64
on back from scan request money page the `iou.participants`. array is no longer empty so the condition is false and the title changes.
### What changes do you think we should make in order to solve the problem?
on back list of `iou.participants` should be set to empty again.

**Comment by DylanDylann** [comment] 2023-10-04 07:19
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. App displays 'Split' in title on back from **scan** request money 
2. App displays 'Split' in title on back from **manual** request money 

### What is the root cause of that problem?
Let's see the logic of header message
https://github.com/Expensify/App/blob/7f063c7b6487e037804e1d97c08a739071e67679/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L57-L63
In manual request and scan request, we are using `_.isEmpty(iou.participants)` as a condition for header message. It is incorrect


### What changes do you think we should make in order to solve the problem?
1. In Scan Request: There are no options to split the bill, the header title should be fixed
```
if (isScanRequest) {
            setHeaderTitle(translate('common.scan'));      // also can use translate('common.scan'). It depends on design team
            return;
}
```

2. In Manual request
https://github.com/Expensify/App/blob/7f063c7b6487e037804e1d97c08a739071e67679/src/pages/iou/steps/MoneyRequstParticipantsPage/MoneyRequestParticipantsPage.js#L63

We should update the condition like that 
```
        setHeaderTitle(isSplitRequest ? translate('iou.split') : translate('tabSelector.manual'));
``` 

### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2023-10-04 07:23
@shawnborton We are displaying "Manual" in the header message of Scan Request. Is it expected?
Note that: 
The header message is `Distance` in Distance Request
The header message is `Manual` in Manual Request
The header message is `Manual` in Scan Request --> my question here


https://github.com/Expensify/App/assets/141406735/4337be17-3826-4612-acd8-13f96f70b78a

**Comment by shawnborton** [comment] 2023-10-04 10:52
Hmmm @JmillsExpensify @trjExpensify thoughts on that one?

**Comment by trjExpensify** [comment] 2023-10-04 18:05
>The header message is Manual in Scan Request --> my question here

I think this should be `Scan`, not `Manual`.

**Comment by trjExpensify** [comment] 2023-10-04 18:08
Then wrt to when `Split` is in the header: 

- on the participants selector screen when you click `Split` on any of the rows to enter that multi-select flow
- on the `split` confirmation page thereafter

**Comment by DylanDylann** [comment] 2023-10-05 05:41
[UPdated proposal](https://github.com/Expensify/App/issues/28751#issuecomment-1746280710)

**Comment by trjExpensify** [comment] 2023-10-05 10:58
Hey @DylanDylann in your vid can you make sure to go through to the confirmation page in the `Scan` flow to ensure it's correct there as well? 

Also on this: 

>In Scan Request: There are no options to split the bill, the header title should be fixed

There will be an option to split the bill in scan receipts [real soon](https://github.com/Expensify/App/pull/28710), so let's not assume that isn't on the way. CC: @youssef-lr

**Comment by DylanDylann** [comment] 2023-10-05 13:55
@trjExpensify 

> Hey @DylanDylann in your vid can you make sure to go through to the confirmation page in the Scan flow to ensure it's correct there as well?

Yeah, updated video 


https://github.com/Expensify/App/assets/141406735/a107fc74-4398-4644-8eac-d91fb87e5a61

**Comment by trjExpensify** [comment] 2023-10-06 00:10
Huh, it might be because it's late, but why is it now blank in that vid? It should read `Scan`?

**Comment by trjExpensify** [comment] 2023-10-06 00:11
@fedirjh can you review these proposals please? Thanks!

**Comment by trjExpensify** [comment] 2023-10-09 15:21
Hm, interesting. So basically, in the instance of one person being tapped for a 1:1 request, when coming back to the participants page we remember the selection, and because a participant is selected, it's recognised as being in the `split` flow because that's the flow where you select participants. I also agree the `Add to split` green button is super confusing here when navigating back. 

https://github.com/Expensify/App/assets/16232057/ca5d5175-5331-48a2-8488-a556dda6b0de

>when going back from Confirmation with 1 participant, we can remove the participant.

I think I agree we should remove the participant in this case. I can understand not in the split case, because you might be going back to add someone else you forgot to the split. 

CC: @JmillsExpensify @shawnborton @dannymcclain here's another weird byproduct of this combined request/split participant selector thang. Curious for your take!

**Comment by shawnborton** [comment] 2023-10-09 15:45
Whoa yeah, that is weird. I don't think we should say split until more than one person is selected.

**Comment by dannymcclain** [comment] 2023-10-09 15:51
Agree - this seems super wacky to me. I think we're trying to do much behind the scenes when we should just let things be simple and explicit.

**Comment by trjExpensify** [comment] 2023-10-09 15:58
Yeah, I mean.. I think the real solution is not combining these flows really. You can hypothetically split with just one person, so I can see why the page header was transformed to "Split" after tapping the split button alongside one row. It just causes this weird thing when you don't do that but go back from the confirmation page and the participant is selected when you didn't go through the split flow.

**Comment by DylanDylann** [comment] 2023-10-09 17:16
@trjExpensify Could you help to update the expected in the OP?

**Comment by trjExpensify** [comment] 2023-10-09 17:41
Yeah, we're kinda' still discussing that.

**Comment by trjExpensify** [comment] 2023-10-10 23:05
@shawnborton @dannymcclain @JmillsExpensify anyone against this interim solution until we decide on separating these flows? 

>I think I agree we should remove the participant in this case. I can understand not in the split case, because you might be going back to add someone else you forgot to the split.

By not faux selecting the single participant when navigating back in the request from one person flow, we won't falsely show `Split` in the header and the `Add to group` button also wouldn't show.

**Comment by shawnborton** [comment] 2023-10-11 13:10
Ah, that makes sense to me

**Comment by dannymcclain** [comment] 2023-10-11 15:13
Yeah I think that makes sense to me too as an interim solution. It doesn't feel like the ideal end state for this but agree that it's probably the best path forward for now.

**Comment by DylanDylann** [comment] 2023-10-12 05:45
@trjExpensify @shawnborton @dannymcclain This is the result after applying [my proposal](https://github.com/Expensify/App/issues/28751#issuecomment-1746280710)

https://github.com/Expensify/App/assets/141406735/a137e31c-2f38-45f5-8a62-5e50f0daa867

Could you guys help to confirm? Thanks

cc @fedirjh

**Comment by shawnborton** [comment] 2023-10-12 13:03
That looks pretty good to me.

**Comment by dannymcclain** [comment] 2023-10-12 13:59
Yup I think this looks good too.

**Comment by trjExpensify** [comment] 2023-10-12 14:57
Same, looks good. Thanks! For good measure in testing the PR, can you go through the `Scan` tab flow as well to make sure that has been equally fixed?

**Comment by DylanDylann** [comment] 2023-10-12 16:18
@trjExpensify Oh yeah, in the previous discussion I forgot to update the title on the confirmation page. I updated 

https://github.com/Expensify/App/assets/141406735/4336f2c7-b7e2-4b88-8cc0-7af8d2400f05

**Comment by trjExpensify** [comment] 2023-10-16 12:10
@fedirjh can you review, please?

**Comment by trjExpensify** [comment] 2023-10-16 13:17
Yeah, if the participant wasn't selected in the first place (i.e by tapping "Split") then on navigating back the participant shouldn't be selected. Looks like @DylanDylann's proposal is aligned with that though: https://github.com/Expensify/App/issues/28751#issuecomment-1758947446

**Comment by trjExpensify** [comment] 2023-10-16 17:55
Okay, well @DylanDylann can maybe confirm, because this video shows the member not being selected when navigating back: https://github.com/Expensify/App/issues/28751#issuecomment-1759945190

**Comment by DylanDylann** [comment] 2023-10-17 04:16
@fedirjh @trjExpensify 
> I think the participant is still selected but it is not displayed as selected when we go back from a manual request 

It is correct. If we use the browser back/forward button, the old value will appear on the confirmation page. Let's see the video

https://github.com/Expensify/App/assets/141406735/450f74f2-a182-4333-a7f1-ee752c115f28

**Comment by DylanDylann** [comment] 2023-10-17 04:36
@fedirjh this is draft change https://github.com/Expensify/App/pull/29737

**Comment by trjExpensify** [comment] 2023-10-18 17:19
Wahoo! Let's get the PR going :)

**Comment by trjExpensify** [comment] 2023-11-10 18:01
Confirming payments as follows: 

$500 to @DylanDylann for the fix 
$500 to @fedirjh for C+ 
$50 to @dhanashree-sawant for the bug report

PR took more than 3 days, so #urgency bonus doesn't apply.

**Comment by trjExpensify** [comment] 2023-11-10 18:07
Thanks for those, @fedirjh! Created an issue for Applause.

**Comment by trjExpensify** [comment] 2023-11-10 18:13
Settled up with you all. Thanks!

**Closed by trjExpensify** 2023-11-10 18:13 UTC
Labels: External, Daily, Awaiting Payment, Bug
