### ISSUE TITLE
[$500] mWeb - Emoji skin tone selector is partially hidden when keyboard is in use

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#35403] opened 2024-01-30 14:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.33-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause- Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/34105

## Action Performed:
1. Go to any chat
2. Tap Emoji picker
3. Tap on the search field

## Expected Result:
Emoji skin tone selector is shown completely with no extra padding

## Actual Result:
Emoji skin tone selector is hidden partially and can't be selected clearly.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/a3355d73-ec3f-45fb-9a1d-7d1ab15cbf96

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d87fc1c0cabdcd5e</li>
        <li>Upwork Job ID: 1752334064101212160</li>
        <li>Last Price Increase: 2024-01-30</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-01-30 14:13
We think that this bug might be related to  #vip-vsb
CC @quinthar

**Comment by divyanshugarg36** [comment] 2024-01-30 14:20
## Proposal
Please re-state the problem that we are trying to solve in this issue.
mWeb - Emoji skin tone selector is partially hidden when keyboard is in use

## What is the root cause of that problem?
This looks like a CSS issue. Seems like the property used to align the viewport height of the emoji container is not working properly.

## What changes do you think we should make to solve the problem?
We can easily update the viewport property of the container responsible for the positioning of the emoji component. This will solve the issue

## What alternative solutions did you explore? (Optional)
Another method to solve this could be with the help of spacing properties in CSS we can calculate the height of the trimmed area and add that height to the container bottom.

**Comment by situchan** [comment] 2024-01-30 14:32
Same root cause as #35380

**Comment by joekaufmanexpensify** [comment] 2024-01-30 14:50
Sounds good. Closing as this is a dupe of that issue!

**Closed by joekaufmanexpensify** 2024-01-30 14:50 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by joekaufmanexpensify** [comment] 2024-03-05 21:55
Left my thoughts [here](https://github.com/Expensify/App/issues/35380). That other issue is already paying out $1k. I kinda feel like we should just handle both cases there since the behavior is quite similar.
