### ISSUE TITLE
Dev: Web - Magic code does not blur during sign in loading

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23009] opened 2023-07-17 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
. Go to login page, enter email and click Continue
2. Type quickly more than 6 digits in the magic code field
3. Once 6th digit is entered, signing in starts.
4. Then the magic input should blur till backend returns success or error.
5. See that while signing in started, the 7th digit onwards can still be typed into magic input.

## Expected Result:
Magic input should blur on entering 6th digit till backend sends its response

## Actual Result:
Describe what actually happened

## Workaround:
Magic input is not blurred

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** Dev 1.3.41-2
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/28eb1d8c-a1a9-4597-8bd9-521b34ad72cf

**Expensify/Expensify Issue U@c3024 
**Issue reported by:** @c3024
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689497435352449

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-07-18 22:57
Ah cool, thanks for that! 

This is a dupe of https://github.com/Expensify/App/issues/21293 & https://github.com/Expensify/App/issues/23087. Closing!

**Closed by trjExpensify** 2023-07-18 22:57 UTC
Labels: Daily, Needs Reproduction, Bug

**Comment by trjExpensify** [comment] 2023-07-21 00:12
Ah cool, fair. @garrettmknight want to pay out on the job linked to the issue that's open?
