### ISSUE TITLE
[HOLD for payment 2023-10-02] [$500]  Split bill - Here is no smooth animation for Paid by and Split with users on Split bill page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26376] opened 2023-08-31 10:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open website
2. Click on plus icon > Split bill >Enter sum > Choose user(s) and click on Next btn > Click on Paid by and Split with's user's username

## Expected Result:
There should be smooth animation for Paid by and Split with users on Split bill page

## Actual Result:
There is no smooth animation for Paid by and Split with users on Split bill page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.60-1

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/cbd05c35-c259-46a7-ab25-454f4e7ea770

https://github.com/Expensify/App/assets/115492554/8ba4bb01-89dc-45ca-b79a-28e4f99c1fff

**Expensify/Expensify Issue URL:**

**Issue reported by:** @mahmudjontoraqulov

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692713551555059

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0179ce98efccffa8c3</li>
        <li>Upwork Job ID: 1700175437224157184</li>
        <li>Last Price Increase: 2023-09-15</li>
<li>Automatic offers: </li>
<ul>
<li>b4s36t4 | Contributor | 26739682</li>
<li>mahmudjontoraqulov | Reporter | 26739683</li>
</ul></li>
    </ul>
</details>

**Comment by b4s36t4** [comment] 2023-08-31 11:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Split bill - Here is no smooth animation for Paid by and Split with users on Split bill page.
### What is the root cause of that problem?
The RCA for this issue lies here in this snippet

https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/pages/ProfilePage.js#L102-L106.

We're calling the `OpenPublicProfilePage` command API without any condition.

But we have multiple conditionals based on the `loading` start for the component.
This is how the current flow is

Click on Account -> Navigate to `ProfilePage` -> load variables related to component & Call the API -> `props.personalDetails` updated -> Again load the variable. 

This transition causing the modal to re-render two quickly causing the interruption with the transition.

We already have the loading indicator but it isn't working because of few cases which we're not considering when we're doing the api call.

https://github.com/Expensify/App/blob/96a0db1aa2e239530f926b9bf62951f3c3408918/src/pages/ProfilePage.js#L240

Here we're only showing loading state when there is no minimum details and loading state is true.

Although we have the loading state as true but we have minimum details for the particular user which is the reason we're not showing the loading.

### What changes do you think we should make in order to solve the problem?

We should move the `useEffect` to below lines and add the dependency of `hasMinimumDetails` and only call the API if we don't have minimum details.

```jsx

useEffect(() => {
    if (ValidationUtils.isValidAccountRoute(accountID) && !hasMinimumDetails) {
        PersonalDetails.openPublicProfilePage(accountID);
    }
}, [accountID, hasMinimumDetails]);

```

Doing this so ensures we're not causing the re-render unnecessarily and so the animation works perfectly.



### What alternative solutions did you explore? (Optional)
NA

### Result

https://github.com/Expensify/App/assets/59088937/b87d87ef-6468-4aa7-9c6d-6483c1b582b1

**PS: This is the smoothest transition I've encountered and fixed(on demo though) :xD**

**Comment by kevinksullivan** [comment] 2023-09-08 15:57
Moving forward 👍

**Comment by eVoloshchak** [comment] 2023-09-10 15:01
@b4s36t4's [proposal](https://github.com/Expensify/App/issues/26376#issuecomment-1700887279) looks good to me, I think we should proceed with it

> PS: This is the smoothest transition I've encountered and fixed(on demo though) :xD

does this mean some transitions can be _less smooth_ than others? 🤯

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2023-09-14 19:40
Not overdue, waiting on @neil-marcellini's opinion

**Comment by neil-marcellini** [comment] 2023-09-18 20:15
> @b4s36t4's [proposal](https://github.com/Expensify/App/issues/26376#issuecomment-1700887279) looks good to me,

I agree, hired.

**Comment by b4s36t4** [comment] 2023-09-20 17:54
@eVoloshchak Created PR here #27876

**Comment by eVoloshchak** [comment] 2023-10-02 14:08
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused it (not that I could pinpoint at least), that's the original implementation from https://github.com/Expensify/App/pull/20144
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: this is a simple visual bug, don't think an additional discussion is needed
- Determine if we should create a regression test for this bug. 
Is it easy to test for this bug? Yes
Is the bug related to an important user flow? Yes
Is it an impactful bug? No
The bug has near zero impact, just an animation that isn't smooth, I think a regression test isn't needed here

**Comment by eVoloshchak** [comment] 2023-10-02 14:08
> Based on my calculations, the pull request did not get merged within 3 working days of assignment. Please, check out my computations here:

I don't think that's correct, it was merged on a weekend, so it's definitely less than 3 business days

**Comment by kevinksullivan** [comment] 2023-10-03 22:49
Weird, the dates are totally off in that post v. the PR, which shows it was opened on Sept 20 and merged on Sept 21. Paying out bonus for this.

**Comment by kevinksullivan** [comment] 2023-10-03 22:50
@eVoloshchak offer sent, lmk when you accept! I will plan to pay bonus as well

**Comment by kevinksullivan** [comment] 2023-10-03 22:52
Paid @b4s36t4 and @MahmudjonToraqulov

**Comment by eVoloshchak** [comment] 2023-10-04 14:58
> Weird, the dates are totally off in that post v. the PR, which shows it was opened on Sept 20 and merged on Sept 21

@kevinksullivan, it's calculated from the moment a contributor is assigned to the job to the moment PR is merged. The dates are correct, but the calculation of days elapsed isn't

> offer sent, lmk when you accept! I will plan to pay bonus as well

Requested the payment via NewDot, thanks!

**Comment by JmillsExpensify** [comment] 2023-10-05 20:50
Can I get a payment summary on this issue?

**Comment by kevinksullivan** [comment] 2023-10-05 21:14
Payment summary:
- Reporter: @MahmudjonToraqulov $250
- Contirbutor: @b4s36t4 $750
- C+: @eVoloshchak $750 (paid in NewDot)

**Comment by JmillsExpensify** [comment] 2023-10-05 21:17
$750 payment approved for @eVoloshchak based on BZ summary.

**Closed** 2023-10-09 16:20 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
