### ISSUE TITLE
[HOLD for payment 2023-08-01] [$1000] Login - The FAB menu is not open when entering the correct magic code on second try

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22692] opened 2023-07-11 20:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to staging.new.expensify.com
2. On the login screen enter any email account and click Continue
3. Enter a incorrect magic code
4. Enter the correct magic code

## Expected Result:
The FAB menu in the LHN view should be opened

## Actual Result:
The FAB menu is not opened when entering the correct magic code on second try

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.39.5
 
**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/67104f6e-59a9-4822-8dae-20bd6d8617f9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7019e80367e460c</li>
        <li>Upwork Job ID: 1679099061757542400</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by getusha** [comment] 2023-07-12 05:13
I am not able to reproduce.

**Comment by JmillsExpensify** [comment] 2023-07-12 12:02
I would able to successfully reproduce using these reproduction steps. 

> Navigate to staging.new.expensify.com
> On the login screen enter a **any** email account and click Continue
> Enter an incorrect magic code
> Enter the correct magic code

**Comment by aliammar1995** [comment] 2023-07-12 14:09
I am not able to reproduce

**Comment by daanish-shaikh** [comment] 2023-07-13 07:58
### Proposal

### Please re-state the problem that we are trying to solve in this issue.
While logging in with a new user account, If the magic code is entered twice once with wrong code and then the right one, in the following case when the home page loads up, the fab menu doesn’t open automatically. 

### What is the root cause of that problem?
For the following case, In the src/libs/actions/Welcome.js file initially "isLoadingReportData" is true due to which when checkOnReady() is invoked on callback of NVP_IS_FIRST_TIME_NEW_EXPENSIFY_USER it return’s without invoking resolveIsReadyPromise() as at this state "isFirstTimeNewExpensifyUser" is true and "isLoadingReportData" is true which satisfies the return condition. After this when checkOnReady() is invoked on callback of IS_LOADING_REPORT_DATA, again it returns without invoking resolveIsReadyPromise() as at this state, value of "isFirstTimeNewExpensifyUser" is changed to false in show() and "isLoadingReportData" is false which again satisfies the return condition.

### What changes do you think we should make in order to solve the problem?
Add a if statement in show() function before changing value of "isFirstTimeNewExpensifyUser" to false, to check whether "isLoadingReportData" is false.
```
if (!isLoadingReportData) {
isFirstTimeNewExpensifyUser = false;
}
```

**Comment by JmillsExpensify** [comment] 2023-07-26 04:08
Summary of pay outs once we get to the end of the regression period. 

 - Issue reporter: N/A
 - Contributor: @tienifr $1,000 (no bonus)
 - Contributor+: @allroundexperts $1,000 (no bonus)

Upwork job [is here](https://www.upwork.com/jobs/~01a7019e80367e460c).

**Comment by JmillsExpensify** [comment] 2023-08-01 05:48
Ah yep, you are right. It looks like the automation failed but I checked the PR to confirm.

**Comment by JmillsExpensify** [comment] 2023-08-09 16:21
Circling back for payments. @tienifr has been paid via Upwork. @allroundexperts I'll check to see if you've submitted via NewDot, but if not, please do that and then I can close this issue once approved there. Last up, I agree on your point about not needing a regression.

**Comment by JmillsExpensify** [comment] 2023-08-10 04:05
Great thanks! This is approved for payment on NewDot so I'm closing this one.

**Closed by JmillsExpensify** 2023-08-10 04:05 UTC
Labels: External, Daily, Awaiting Payment, Bug
