### ISSUE TITLE
Reaction emoji - Unable to add reaction from + menu

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19687] opened 2023-05-26 18:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch the app and create a group chat
2. Open group > send message > react with 2 or more accounts
3. Click add reaction and select emoji
4. Select another emoji

## Expected Result:
Able to add reaction from + menu

## Actual Result:
Unable to add reaction from + menu

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/54d82501003ae4f62efce565d5a7ba30dbba412964522c94785189c35278f7fd

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment] 2023-05-26 19:53
Confirmed that this is fixed in `main` now and broken in `staging`
I'll request the CP for https://github.com/Expensify/App/pull/19659

**Comment by aldo-expensify** [comment] 2023-05-26 19:59
Verified that https://github.com/Expensify/App/pull/19659 does fix the problem.

I requested the cherry pick to staging.

**Comment by aldo-expensify** [comment] 2023-05-26 22:37
The CP will be done on Monday. No deploy to production is happening today anyway.

**Comment by luacmartins** [comment] 2023-05-29 15:53
PR CP'ed. Tested in staging and it seems to be working. Thanks for working on this! Closing.

**Closed by luacmartins** 2023-05-29 15:53 UTC
Labels: DeployBlockerCash, Engineering, Hourly, Overdue
