### ISSUE TITLE
[HOLD for Payment] [$50] [Search v2.3] - Default search name shows the report/user ID instead of report/user name

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49216] opened 2024-09-14 19:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Search > Chats.
3. Click Filters.
4. Click In.
5. Select a report > Save.
6. Click Save search.

## Expected Result:
Default search name will show the report name.

## Actual Result:
Default search name shows the report ID instead of report name.
Ths same goes for user ID when "From" filter is saved.

## Workaround:
Unknown
## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<img width="1440" alt="Bug6603220_1726299165075!Screenshot_2024-09-14_at_15 31 20" src="https://github.com/user-attachments/assets/56955c93-4435-4b8f-aea3-52a2e9ef15f5">

https://github.com/user-attachments/assets/d150f998-9d1b-4c9b-a994-14d355155147

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021835502366052877051</li>
        <li>Upwork Job ID: 1835502366052877051</li>
        <li>Last Price Increase: 2024-10-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jayeshmangwani</details>

**Comment by jaydamani** [comment] 2024-09-15 22:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

default search name shows ID instead of name

### What is the root cause of that problem?
when saving a search query, we use the raw query as name

https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/actions/Search.ts#L55

### What changes do you think we should make in order to solve the problem?


Use [getSearchHeaderTitle](https://github.com/Expensify/App/blob/0c618acc8b5a0b77eb27dfa049a18e3135c51c52/src/libs/SearchUtils.ts#L727) to get a more user friendly string. so the update code will be

```js
    const saveSearchName = name ?? SearchUtils.getSearchHeaderTitle(queryJSON, personalDetails, cardList, reports, taxRates) ?? '';
```

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by luacmartins** [comment] 2024-09-15 22:38
@lakchote will address this in a follow up since it came from [his PR](https://github.com/Expensify/App/pull/48566)

**Comment by luacmartins** [comment] 2024-09-16 02:14
@jaydamani are you available to work on a fix for this?

**Comment by jaydamani** [comment] 2024-09-16 02:29
@luacmartins yes, I can work on it now.

**Comment by luacmartins** [comment] 2024-09-16 02:56
I already put up a PR with a slightly different solution since we shouldn't update the actual saved search name (we wanna be able to dynamically get those if the display name changes, etc)

**Comment by jaydamani** [comment] 2024-09-16 03:19
@luacmartins That PR could break the rename functionality. If you rename a search, it would still show the query instead of the name.

My changes only affects when name provided by user is undefined
`const saveSearchName = name ?? SearchUtils.getSearchHeaderTitle(queryJSON, personalDetails, cardList, reports, taxRates) ?? '';`

Also, I think your PR partially implements proposal by @ishpaul777
Fully implementing it should fix the rename issue.

**Comment by luacmartins** [comment] 2024-09-16 03:39
Ah yes, I noticed that as well. I updated the PR and I agree that in the end the solution was quite similar to @ishpaul777's solution. I'll make sure that we compensate them for the solution.

**Comment by luacmartins** [comment] 2024-09-16 05:19
Fixed on staging

**Comment by jayeshmangwani** [comment] 2024-09-16 05:36
I haven't reviewed the PR; Unassigning myself from the issue

**Comment by luacmartins** [comment] 2024-09-26 02:13
This is done

**Comment by luacmartins** [comment] 2024-09-26 14:59
@sakluger could you please help pay $50 to @ishpaul777 since we used their solution? Thank you!

**Comment by sakluger** [comment] 2024-10-03 19:15
@ishpaul777 I sent you an offer here: https://www.upwork.com/nx/wm/offer/104254193

Please let me know once you've accepted the offer. Thanks!

**Comment by sakluger** [comment] 2024-10-03 20:07
Thanks, all paid!

**Closed by sakluger** 2024-10-03 20:07 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
