### ISSUE TITLE
PAY on 06/09 [$1000] Web- Share code- “Back” tooltip appears at LHN top corner on pressing back icon

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19727] opened 2023-05-28 20:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to "Settings."
2. Click on " Share code."
3. Click on Chevron left symbol to go back.
4. Observe that for a fraction of seconds tooltip naming Back” appears at top left corner of the page.

## Expected Result:
The “Back” tooltip should appear under the symbol only.

## Actual Result:
The “Back” tooltip appears under the Chevron left symbol and at top left corner of the page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.2

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/049e38e9-4fba-475e-b7b3-9d4ce50a73e0

https://github.com/Expensify/App/assets/93399543/bc7121f5-68c0-4f3b-9985-ce3a96a0ecb7

**Expensify/Expensify Issue URL:**

**Issue reported by:** @usmantariq96

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685001326516699

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01191d973327cf8ff7</li>
        <li>Upwork Job ID: 1663144989463973888</li>
        <li>Last Price Increase: 2023-05-29</li>
    </ul>
</details>

**Comment by bfitzexpensify** [comment] 2023-05-29 11:27
Reproduced.

**Comment by PauloGasparSv** [comment] 2023-05-29 12:32
@sobitneupane please LMK what you think of this [proposal](https://github.com/Expensify/App/issues/19727#issuecomment-1566541162), it looks good IMO!

**Comment by kamaljitSharma21** [comment] 2023-05-29 12:37
## Proposal

### Please re-state the problem that we are trying to solve in this issue. 

Web- Share code- “Back” tooltip appears at LHN top corner on pressing back icon

### What is the root cause of that problem?

In [showTooltip function](https://github.com/Expensify/App/blob/main/src/components/Tooltip/index.js#L65-L87) we are updating the state value of [isRendered and isVisible](https://github.com/Expensify/App/blob/main/src/components/Tooltip/index.js#L66-L70) to true but at the end of [hideTooltip](https://github.com/Expensify/App/blob/0c44fedc3223b4ad1c6d87c0507a2808e8aa55af/src/components/Tooltip/index.js#L109) we are just updating state value of isVisible to false. we also need to update the state value of isRendered to false.

### What changes do you think we should make in order to solve the problem?

We need to update the state values of isRendered variable to false in ``hideTooltip function`` 

Existing Code:
https://github.com/Expensify/App/blob/0c44fedc3223b4ad1c6d87c0507a2808e8aa55af/src/components/Tooltip/index.js#L109

Updated Code :

``
this.setState({isVisible: false, isRendered: false});
``
this will solve our problem

**Comment by kamaljitSharma21** [comment] 2023-05-29 12:41
@PauloGasparSv can you please check above given solution [^](https://github.com/Expensify/App/issues/19727#issuecomment-1567087034)

**Comment by sobitneupane** [comment] 2023-05-30 08:26
Thanks for the proposals.

[Proposal](https://github.com/Expensify/App/issues/19727#issuecomment-1567087034) from @kamaljitSharma21 looks good to me. 

🎀👀🎀 C+ Reviewed
cc: @PauloGasparSv

**Comment by kamaljitSharma21** [comment] 2023-05-30 15:51
@PauloGasparSv / @sobitneupane here is the PR ([#19826](https://github.com/Expensify/App/pull/19826))

**Comment by sobitneupane** [comment] 2023-06-06 08:09
PR was deployed to production on 2nd June.

<img width="990" alt="Screenshot 2023-06-06 at 13 53 47" src="https://github.com/Expensify/App/assets/25876548/91799ddd-9f52-475f-9b33-0f0ac5a8ff0e">

**Comment by PauloGasparSv** [comment] 2023-06-07 12:20
The P.R. was deployed to production as mentioned above! There should be 2 new comments here about the release and the bugZero checklist.

@bfitzexpensify I'm going to create those 2 comments manually here.

**Comment by PauloGasparSv** [comment] 2023-06-07 12:22
The solution for this issue has been :rocket: deployed to production :rocket: in version 1.3.22-1 and is now subject to a 7-day regression period :calendar:. Here is the list of pull requests that resolve this issue:

- https://github.com/Expensify/App/pull/19826


If no regressions arise, payment will be issued on 2023-06-09. :confetti_ball:

After the hold period is over and BZ checklist items are completed, please complete any of the applicable payments for this issue, and check them off once done.
- [ ] External issue reporter
- [ ] Contributor that fixed the issue
- [ ] Contributor+ that helped on the issue and/or PR

As a reminder, here are the bonuses/penalties that should be applied for any External issue:
- Merged PR within 3 business days of assignment - 50% **bonus**
- Merged PR more than 9 business days after assignment - 50% **penalty**

**Comment by PauloGasparSv** [comment] 2023-06-07 12:23
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@sobitneupane] Determine if we should create a regression test for this bug.
- [ ] [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@bfitzexpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by bfitzexpensify** [comment] 2023-06-08 06:28
Offers sent out

**Comment by usmantariq96** [comment] 2023-06-08 06:36
@bfitzexpensify offer accepted

**Comment by sobitneupane** [comment] 2023-06-09 07:31
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/18782
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

https://github.com/Expensify/App/pull/18782#issuecomment-1584104814
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The issue was very difficult to catch so i don't think it would be caught sooner by updating review checklist.

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

**Comment by bfitzexpensify** [comment] 2023-06-12 10:51
Agreed that we don't need a regression test here.

**Comment by bfitzexpensify** [comment] 2023-06-12 10:51
All contracts have been paid out and ended.

**Comment by bfitzexpensify** [comment] 2023-06-12 10:51
We're all done here - thanks everyone!

**Closed by bfitzexpensify** 2023-06-12 10:51 UTC
Labels: Reviewing, External, Daily, Bug
