### ISSUE TITLE
[$250] Thread- Edit Markup Briefly Dismissed When Replying in Thread

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#52876] opened 2024-11-21 10:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.65-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+tw434343535@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Navigate to chat and write a message.
2. Edit the message and reply to it in a thread.
3. Observe the edit markup briefly disappearing.

## Expected Result:
The edit markup should remain visible while replying.

## Actual Result:
The edit markup is momentarily dismissed when replying in the thread.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [x] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b8d47de1-cec6-48ee-a969-5573ca07f05a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021863715699861494592</li>
        <li>Upwork Job ID: 1863715699861494592</li>
        <li>Last Price Increase: 2024-12-02</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by strepanier03** [comment] 2024-12-02 22:43
Able to repro.

**Comment by linhvovan29546** [comment] 2024-12-05 04:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread- Edit Markup Briefly Dismissed When Replying in Thread
### What is the root cause of that problem?
When adding a comment, the `AddComment` API is called. However, the response from this API is missing the isEdited field inside `reportActions_<report_parent_action_id>`.
<details><summary>Refer to the attached image for details (the first image is the `OpenReport` API)</summary>
<img width="680" alt="Screenshot 2024-12-05 at 11 40 45 AM" src="https://github.com/user-attachments/assets/0fc64b2e-6b5d-4f72-891f-451380e954e0">
<img width="728" alt="Screenshot 2024-12-05 at 11 41 49 AM" src="https://github.com/user-attachments/assets/c7fbf051-a876-4eb0-93f4-b0a58c7160a1">

</details>

### What changes do you think we should make in order to solve the problem?
- We have two the way, either on the FE or backend BE:
  - FE:
In the [Report.ts](https://github.com/Expensify/App/blob/main/src/libs/actions/Report.ts) file, locate the [addAction](https://github.com/Expensify/App/blob/e25e3fa13b678cf733cd64ab734d73355fc726b8/src/libs/actions/Report.ts#L591) function. Modify the `successData` to add the `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}${ancestorReport.reportID}` key with the current parent report message. This will override the server response.
  - BE:
Update the AddComment API endpoint to include the `isEdited` field in the response message.
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
N/A

### What alternative solutions did you explore? (Optional)
N/A

**Comment by cristipaval** [comment] 2024-12-09 12:23
@muttmuure Could you please set the criticality for this issue?

**Comment by muttmuure** [comment] 2024-12-09 18:40
This seems very low value

**Comment by muttmuure** [comment] 2024-12-09 18:40
Let's close it

**Closed by muttmuure** 2024-12-09 18:40 UTC
Labels: Daily, Internal, Bug
