### ISSUE TITLE
LOW: [$500] Unread notification in fevicon does not update when the user is in another tab

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#32225] opened 2023-11-29 21:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5.3
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @iwiznia 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1701197419116139

## Action Performed:
1. Open staging.new.expensify.com and login
2. Open 2nd tab 
3. Send a message from another device
4. Observe the fevicon in tab 1 where account A logged in

## Expected Result:
Should update the fevicon notification count

## Actual Result:
Notification count updates only when clicking the tab 1

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/fb5dba30-8524-40f6-b636-b5d0fb1aa9b8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013669a17c30bfb662</li>
        <li>Upwork Job ID: 1729978850198351872</li>
        <li>Last Price Increase: 2023-12-06</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 28044342</li>
</ul></li>
    </ul>
</details>

**Comment by iwiznia** [comment] 2023-11-29 21:57
@Julesssss seems to think this was related to this change https://github.com/Expensify/App/pull/31295/files#diff-0812bc9a1458d29651dc472eddb66ec3c320b32473461e75d8dda4fbd6362523L12-R36
Thread here https://expensify.slack.com/archives/C01GTK53T8Q/p1701204065146149

@hurali97 can you take a look?

**Comment by vjurcutiu** [comment] 2023-11-29 22:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The favicon does not update when a message is received in another tab.

### What is the root cause of that problem?
In `updateUnread/index.website.js` we use a `setTimeout` function, which is no longer necessary after the change specified by @iwiznia. 

### What changes do you think we should make in order to solve the problem?
Remove the `setTimeout` function. 

### What alternative solutions did you explore? (Optional)

**Comment by iwiznia** [comment] 2023-11-29 22:44
I am confused, I see the setTimeout, is the setTimeout call never firing?

**Comment by vjurcutiu** [comment] 2023-11-29 23:21
I don't know exactly. I assumed that since InteractionManager returns a promise, setTimeout was no longer needed, and that fixed it.

**Comment by ZhenjaHorbach** [comment] 2023-11-29 23:43
I don't think they just added it)

https://github.com/Expensify/App/blob/7ede114255d65a5b1053d9aa0af976fa4401e233/src/libs/UnreadIndicatorUpdater/updateUnread/index.website.js#L15-L16

**Comment by adelekennedy** [comment] 2023-12-04 16:28
@hurali97 bump on the request above!

**Comment by mananjadhav** [comment] 2023-12-07 04:10
Apologies for the delay here. I was out sick few days. I don't think we should be removing the `setTimeout` and neither did the solution worked for me.

@tienifr's solution did work for me, but I am trying to understand was this something that stopped working recently and do we have a linked commit that caused this?  

I also noticed that the latest change was made by this [PR](https://github.com/Expensify/App/pull/30133) last week by @allroundexperts, but even after reverting that, the issue is still reproducible.

@iwiznia Are you aware if this was working previously and recently stopped working?

**Comment by hurali97** [comment] 2023-12-07 07:09
@tienifr If I understand correctly, the issue is resolved after [this PR](https://github.com/Expensify/App/pull/30133/files) but we don't know why the author removed `runAfterInteractions`, correct?

**Comment by iwiznia** [comment] 2023-12-07 18:26
> @iwiznia Are you aware if this was working previously and recently stopped working?

I don't know if this was working because I've been stuck between this bug and https://github.com/Expensify/App/issues/31276

**Comment by hurali97** [comment] 2023-12-08 08:33
Hey guys,

I want to help narrow down the issue. The code that's currently in main works perfectly for the following scenario.

Let's consider we have a user_A logged in window_A and we have another user_B logged in window_B. Now, user_A opens the chat of user_C and go to other tab in window_A. In that period, user_B sends a message to user_A and as a result, we see the unread indicator being updated in window_A, which is what we expect.

Now, let's consider everything is same, but user_A has now opened the chat of user_B and then he go to other tab in window_A. In that period, user_B sends a message to user_A and since, user_A has already kept the chat opened of user_B but that's not focused, we see that the code for unread indicator is being called but we don't see any update in UI, because user_A had the chat open of user_B initially.

The idea here is that there's some place else which is updating the `lastReadTime` or `lastVisibleActionCreated`, as a result of which code in `UnreadIndicatorUpdater.js` does execute but gets the same unread count. We can find that area and add a flag to update only when screen is focused, not when chat is focused.

Also, I have tested this with `InteractionManager` in place and the behaviour is the same, so I would suggest bringing it back if it's feasible. Also, we should check if the unread count is same, we shouldn't be calling the `updateUnread`. 


https://github.com/Expensify/App/assets/47336142/8fd18426-7098-4d1c-ae3e-e86c8ae3506c

**Comment by adelekennedy** [comment] 2023-12-11 19:04
@mananjadhav what are your thoughts on [this comment ](https://github.com/Expensify/App/issues/32225#issuecomment-1846765445)?

**Comment by mananjadhav** [comment] 2023-12-12 04:35
@adelekennedy I am working on limit capacity, can you please reassign this?

**Comment by situchan** [comment] 2023-12-12 05:03
I am interested in reviewing this

**Comment by allroundexperts** [comment] 2023-12-12 05:05
I can review it as well. Specially, since I've worked on this part of code in one of my PR.

**Comment by adelekennedy** [comment] 2023-12-12 16:02
@situchan assigned you (went by response order!)

**Comment by situchan** [comment] 2023-12-13 11:22
@tienifr your proposal is now deprecated as per latest codebase

**Comment by adelekennedy** [comment] 2023-12-15 14:16
@situchan thank you for stepping in for this one

**Comment by adelekennedy** [comment] 2023-12-19 21:22
@situchan what do we need to do to move this along? are their questions to be answered before a good proposal can be submitted or do we need to attract more proposals?

**Comment by situchan** [comment] 2023-12-19 21:31
We're waiting for more proposals based on latest codebase

**Comment by kaushiktd** [comment] 2023-12-28 12:38
### Please re-state the problem that we are trying to solve in this issue.
Unread notification in fevicon does not update when the user is in another tab

### What is the root cause of that problem?
The issue occurs because of stemming from the condition `if (onHoverOut && !isHovered)` triggering `onHoverOut` erroneously when `isHovered` becomes false. This condition needs a refinement to ensure that `onHoverOut` is only called when a hover event had previously occurred (`isHovered` was true), rather than simply when `isHovered` becomes false.

### What changes do you think we should make in order to solve the problem?  
https://github.com/Expensify/App/blob/main/src/components/Hoverable/index.tsx#L54

```
const [hasHovered, setHasHovered] = useState(false);

replace this code 
https://github.com/Expensify/App/blob/d565caa4c62ae23004ed2e4b13b7233259d75d2e/src/components/Hoverable/index.tsx#L133

   useEffect(() => {
       

        if (disabled) {
            return;
        }

        if (onHoverIn && isHovered) {
            return onHoverIn();
        }

        if (onHoverOut && !isHovered && hasHovered) {
            return onHoverOut();
        }
    }, [disabled, isHovered, onHoverIn, onHoverOut, hasHovered]);
```
In essence, `hasHovered` acts as a flag to determine whether a hover event has occurred at least once. If `hasHovered` is true and the current `isHovered` state becomes false, it will trigger the `onHoverOut()` callback, indicating that a hover-out event happened after a previous hover-in event. 

### Video:- 
https://drive.google.com/file/d/1g-GuLQ2uRzgD0PVTgOm8FgJ1WuD8QwDx/view?usp=sharing

**Comment by adelekennedy** [comment] 2024-01-15 16:39
@situchan one new proposal to review above

**Comment by situchan** [comment] 2024-01-15 16:57
@kaushiktd `Hoverable` is base component. Please do thorough testing to make sure there's no regression.

**Comment by kaushiktd** [comment] 2024-01-16 03:33
@situchan Yes I tested it and then only sent proposal. 🙂

**Comment by quinthar** [comment] 2024-01-22 00:31
Hi there, what's the status of this?  What's next, who's doing it, and when will it be done?

**Comment by adelekennedy** [comment] 2024-01-22 17:42
conversation started [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1705943464407329) on bringing on an agency or reassigning

**Comment by situchan** [comment] 2024-01-22 17:52
@kaushiktd your proposal is deprecated after https://github.com/Expensify/App/pull/33257. Can you please update proposal accordingly?

**Comment by kaushiktd** [comment] 2024-01-23 03:44
@situchan The new code seems to be fixing this issue. It is not reproducible on my end.

**Comment by adelekennedy** [comment] 2024-01-25 05:16
this seems like a great time to try the retest weekly label

**Comment by quinthar** [comment] 2024-02-05 00:08
@adelekennedy can you re-test to see if this is still the case?

**Comment by adelekennedy** [comment] 2024-02-05 17:03
can't reproduce - closing this

**Closed by adelekennedy** 2024-02-05 17:03 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug, retest-weekly
