### ISSUE TITLE
[HOLD FOR #25467] [$500]  Split Bill - Individual chats with each participant are not created in offline mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26491] opened 2023-09-01 15:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Disable the internet connection in the device
2. From the global create menu +, select Split bill
3. Go through the prompt and select three participants that don't have a existing group and 1:1 conversations, and submit the request

## Expected Result:
Besides group chat also individual chats with each participant should be created

## Actual Result:
Individual chats with each participant are not created

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.61-1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/cd073e44-d9e2-4258-befb-77b961e3b3c3

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0104022d629ccfb887</li>
        <li>Upwork Job ID: 1697679232695943168</li>
        <li>Last Price Increase: 2023-09-08</li>
    </ul>
</details>

**Comment by ayazalavi** [comment] 2023-09-01 21:02
Hi, I am trying to run the code in android emulator. Can anyone help me reproduce the bug?

**Comment by Rachit-pul** [comment] 2023-09-01 21:06
Proposal

**Please re-state the problem we are trying to solve**

When splitting a bill while in offline mode, Besides group chat, individual chats with each participant should be created as well. 

**What is the root cause of this problem?**

Assuming individual chats are created when online as mentioned in the problem statement. This can be due to 2 reasons-

1. There is a different logic which is executed in case of offline mode which does not have the create individual chats  functionality implemented.
2. In offline mode, individual chats are failing altogether.

In case this behaviour is also present in online mode, it narrows down to the first scenario and will be a straightforward fix.

**What changes do you think we should make in order to solve the problem?**

To begin, I would check the code for case#1 and test the creating individual chat functionality in offline mode. With these tests I would be sure about which scenario we face.

For 1, Simply adding the logic for creating individual chats would suffice. If individual chats fail to be created in offline mode we would need to take a deeper look to figure out if it is possible to create them. If yes, I will add that functionality.

Thanks!

Contributor details
Rachit Pulhani
https://www.upwork.com/freelancers/~01167d06dbad3ad324
rachit2510pulhani@gmail.com

**Comment by ayazalavi** [comment] 2023-09-01 21:10
Contributor details
Your Expensify account email: ayaz.alavi@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/ayaz?viewMode=1

**Comment by Rachit-pul** [comment] 2023-09-01 21:11
Contributor details
Your Expensify account email: rachit2510pulhani@gmail.com
Upwork Profile Link:
https://www.upwork.com/freelancers/~01167d06dbad3ad324

**Comment by ayazalavi** [comment] 2023-09-01 21:17
I dont have access to stackoverflow

**Comment by ayazalavi** [comment] 2023-09-01 21:32
<img width="972" alt="Screenshot 2023-09-02 at 2 07 39 AM" src="https://github.com/Expensify/App/assets/767439/8fa846e9-797a-46fb-a5ff-e4da013639eb">

I am getting this bug when trying to run the code

**Comment by jjcoffee** [comment] 2023-09-04 07:38
Hey @ayazalavi and welcome! :wave: Please ask questions that are not related to the issue on [Slack](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#slack-channels) - it helps to keep things readable here.

**Comment by ayazalavi** [comment] 2023-09-04 23:58
<img width="977" alt="Screenshot 2023-09-05 at 4 56 58 AM" src="https://github.com/Expensify/App/assets/767439/a4a41cb6-4728-4c6e-a507-bf59d6ad428c">
I am testing Mac OS / Chrome I am getting above results when I split between 3 accounts. 1 group chat and 3 separate chats are made.

**Comment by ayazalavi** [comment] 2023-09-05 00:31
let me attach video:
[https://www.dropbox.com/scl/fi/890scwql1yvmawhe1bt9j/Screen-Recording-2023-09-05-at-5.28.14-AM.mov?rlkey=fp56aae113d8tfkfjl80ijbkz&dl=0](url)

**Comment by jjcoffee** [comment] 2023-09-05 07:45
@ayazalavi Please see the "Expected result" section in the issue description.

> Besides group chat also individual chats with each participant should be created

@Rachit-pul Thanks for your proposal! As it stands the proposal needs more detail in both the RCA (where is the issue in the code and why is it an issue) and the solution (what part of the code would you change).

**Comment by CortneyOfstad** [comment] 2023-09-06 14:39
@jjcoffee ^^^ TIA!

**Comment by jjcoffee** [comment] 2023-09-06 15:32
@ayazalavi I'm unsure if your RCA is correct. How would you explain that the behaviour only occurs in offline mode? Your solution is also unworkable as that logic cannot be removed.

Side-note: please copy links to the relevant code blocks rather than adding screenshots. GitHub will automatically render it as a code preview, see [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet#linking-to-code) for more info.

Meanwhile, open to other proposals!

**Comment by ayazalavi** [comment] 2023-09-06 15:59
@jjcoffee thanks for the response. In offline mode chats doesnt have sufficient data and gets skipped at this clause. We may be able to put check if user is offline and does not hide chat in that case? this logic "Hide chats between two users that haven't been commented on from the LNH" does not work in offline mode ONLY.

**Comment by ayazalavi** [comment] 2023-09-06 21:28
isEmptyChat [here](https://github.com/Expensify/App/blob/1eafc7dff1cb609e72a97d6f1d1993a2bf22aaa6/src/libs/ReportUtils.js#L2847) should not be true since we are offline and chats will be empty in this case. In such scenario chats are not getting shown. If we just add simple check here to only evaluate `isEmptyChat` if user is online:
`    const isEmptyChat = !isNetworkOffline && !lastVisibleMessage.lastMessageText && !lastVisibleMessage.lastMessageTranslationKey;
`
this should fix the issue.

**Comment by ayazalavi** [comment] 2023-09-07 14:23
@jjcoffee please look at my updated proposal above. thanks

**Comment by jjcoffee** [comment] 2023-09-07 15:28
@ayazalavi Your RCA doesn't explain why the behaviour only happens whilst offline. If you're interested in digging deeper, it might help to read into the [offline-first patterns](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md) used in the app.

@CortneyOfstad do you reckon we can increase the bounty here to get some more proposals?

**Comment by ayazalavi** [comment] 2023-09-07 16:12
@jjcoffee, in offline mode action timestamps are not setting correctly (ONYXKEYS.COLLECTION.REPORT_ACTIONS). CREATED and REPORTPREVIEW have same timestamps resulting in chat getting skipped. When user gets offline than chats are synced with the server and timestamps gets updated so we again start seeing chat.

**Comment by ayazalavi** [comment] 2023-09-08 13:48
<img width="1197" alt="Screenshot 2023-09-08 at 6 38 48 PM" src="https://github.com/Expensify/App/assets/767439/49d97959-9bf6-4f27-8084-a7bce3ea239b">

Same logic that I found is getting handled in src > lib > ReportActionUtils. if the timetimestamps are same for CREATED and REPORTPREVIEW action than _.max will return CREATED since it is first item in actions array. 

[Here](https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/libs/SidebarUtils.js#L92) all reports with lastvisibleaction === CREATED is getting filtered out from [here](https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/libs/ReportActionsUtils.js#L405). Actual reason is that CREATED action is considered empty message. So basically logic where CREATED action is getting returned as last visible action due timestamps being equal is the actual fault.

**Comment by ayazalavi** [comment] 2023-09-08 13:53
> @ayazalavi Your RCA doesn't explain why the behaviour only happens whilst offline. If you're interested in digging deeper, it might help to read into the [offline-first patterns](https://github.com/Expensify/App/blob/main/contributingGuides/OFFLINE_UX.md) used in the app.
> 
> @CortneyOfstad do you reckon we can increase the bounty here to get some more proposals?

please look at my comments above. let me know if this makes sense.

**Comment by CortneyOfstad** [comment] 2023-09-08 15:55
@jjcoffee let's give it to early next week for the bump in case something pops up over the weekend 👍

**Comment by ayazalavi** [comment] 2023-09-08 19:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In offline mode when user selects Split Bill menu item and choose participants that are not in any group or private chat then private chats are not made.

### What is the root cause of that problem?

All chats with `lastvisibleaction === CREATED` is getting filtered out:
https://github.com/Expensify/App/blob/fc8adf99a11a41154ec276d44495485958e43a7d/src/libs/SidebarUtils.js#L92 
This reportsToDisplay is the array that has chats skipped. See method implementation at line 2817:
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportUtils.js#L2786-L2818
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportActionsUtils.js#L393-L415

Look at line 405-408 above. See CREATED action is returning empty message in line 405. So basically logic where CREATED action is getting returned as last visible action in line 394 is the actual issue. Why is this issue? The reason is below:


Now look at getLastVisibleAction callback
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/libs/ReportActionsUtils.js#L377-L386
Here _.max in line 385 is returning max action.created but IF timestamps of CREATED and REPORTSPREVIEW are same then CREATED action is getting returned in line 385 since underscorejs max's method return first element from array if see multiple max with same values which in turns make chat as empty as shown below:

https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/libs/ReportActionsUtils.js#L405-L409
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportUtils.js#L2818
https://github.com/Expensify/App/blob/b119f9ab54e7cc7272702e270693896b352b61e0/src/libs/ReportUtils.js#L2846-L2849

### What changes do you think we should make in order to solve the problem?
We need to update this method:
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/libs/ReportActionsUtils.js#L377-L386
and add condition to check CREATED is NOT getting returned because of timestamp equality since underscorejs max's method return first element from array if see multiple max with same values.

Logic is already implemented here:
https://github.com/Expensify/App/blob/5c138163049ef0f036d46c4359c51fcde673066f/src/libs/ReportActionsUtils.js#L193-L200
See how someone implemented sorting based on timestamps equality issue. We need to handle this issue in this bug as well.

Check solution video here
https://www.dropbox.com/scl/fi/u1ixnvjvom9iovvmtvqjc/Screen-Recording-2023-09-07-at-7.17.06-PM.mov?rlkey=sp87i4zamlyqrqwsxc5yweiym&dl=0

In above video I checked if other actions has same timestamp as CREATED and MUST return last value instead of first in case timestamps are equal since actions are already sorted as per requirement.

### What alternative solutions did you explore? (Optional)
When adding actions make sure to have CREATED timestamp to be least compared to further added actions for given report.

**Comment by ayazalavi** [comment] 2023-09-08 19:20
@CortneyOfstad @jjcoffee Look at my new proposal above.

**Comment by jjcoffee** [comment] 2023-09-11 12:14
@ayazalavi Thanks, that's better! Just a note, when you update your proposal you should edit your original proposal post and just make a "Proposal updated" comment linking to the original post.

So to summarise the RCA is that we don't really currently handle exactly equivalent timestamps (down to the millisecond) when getting the last visible action. In this case it results in the CREATED action coming through as the "last visible" action even though it's not. This incorrect handling would also apply to all types of messages, so it's worth applying a generic solution.

Your current solution re-implements part of `getSortedReportActions`, and I'm not sure why we wouldn't just use `getSortedReportActions` here which would allow us to avoid having to maintain two separate sorting methods?

**Comment by jjcoffee** [comment] 2023-09-12 07:46
@CortneyOfstad I think we need to hold this one on https://github.com/Expensify/App/issues/25467 - there are quite a lot of changes there to the code involved in the RCA here (I don't expect a fix there, it just makes sense to implement a solution after!).

**Comment by ayazalavi** [comment] 2023-09-12 08:18
@jjcoffee you just need to update 
`     
return _.max(visibleActions, (action) => moment.utc(action.created).valueOf()); 
`
to 
   ` 
return _.max(visibleActions, (action) => isCreatedAction(action) ? Number.MIN_VALUE : moment.utc(action.created).valueOf());
`

This should fix the issue. Look at video in this comment https://github.com/Expensify/App/issues/26491#issuecomment-1712120002

This will make sure CREATED action stays last when returning last visible action. This will fix the bug

**Comment by ayazalavi** [comment] 2023-09-13 18:52
### Proposal

[Updated](https://github.com/Expensify/App/issues/26491#issuecomment-1715230358)

**Comment by CortneyOfstad** [comment] 2023-09-14 17:58
> @CortneyOfstad I think we need to hold this one on https://github.com/Expensify/App/issues/25467 - there are quite a lot of changes there to the code involved in the RCA here (I don't expect a fix there, it just makes sense to implement a solution after!).

Sounds good @jjcoffee — I'll update the title to reflect that 👍

**Comment by CortneyOfstad** [comment] 2023-09-25 13:47
No update yet

**Comment by CortneyOfstad** [comment] 2023-10-04 12:16
No update yet

**Comment by CortneyOfstad** [comment] 2023-10-13 13:58
No update yet

**Comment by CortneyOfstad** [comment] 2023-10-18 18:59
@jjcoffee it appears that https://github.com/Expensify/App/issues/25467 has been closed. Anything we need to do on this side?

**Comment by CortneyOfstad** [comment] 2023-10-18 20:00
I'm heading OoO until Oct. 25, so reassigning BZ to keep an eye on things while I'm gone 👍

**Comment by jjcoffee** [comment] 2023-10-19 09:54
This can be removed off hold since that [PR](https://github.com/Expensify/App/pull/26447) has been merged.

**Comment by puneetlath** [comment] 2023-10-25 13:42
@jjcoffee should we remove the hold on this? Or is this now fixed?

**Comment by jjcoffee** [comment] 2023-10-26 08:48
@puneetlath Unable to repro on latest staging v1.3.91-6 so I think we're good to close!

**Comment by puneetlath** [comment] 2023-10-26 13:24
Great! Thanks @jjcoffee 😄

**Closed by puneetlath** 2023-10-26 13:24 UTC
Labels: External, Daily, Help Wanted, Bug
