### ISSUE TITLE
[$500] [HOLD for payment 2023-09-27] Android - Infinite loading after opening personal details page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27560] opened 2023-09-15 19:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on your avatar to open settings
2. Click on profile
2. Click on personal details
## Expected Result: 
Personal details page should be opened.
## Actual Result: 
Can't open personal details page and infinite loading spinner

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70-5
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/884093a2-0a52-452e-b8f8-dacbc6df231f

https://github.com/Expensify/App/assets/43996225/6494d1d5-76dd-4ae6-8992-70f64a5d6f42

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Ahmed-Abdella
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1694786719105809

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01dbd77bfba87b38dc</li>
        <li>Upwork Job ID: 1707718640343793664</li>
        <li>Last Price Increase: 2023-09-29</li>
    </ul>
</details>

**Comment by Li357** [comment] 2023-09-18 02:46
@mkhutornyi RCA looks reasonable, but is this limited to just Android (and if so, why)? I don't see any recent PRs Android-related that could've caused this regression. Investigating further now.

**Comment by Li357** [comment] 2023-09-18 05:42
Able to reproduce on Web as well via @mkhutornyi's repro steps. RCA is good and proposal looks good. Since this is a deploy blocker, unless we can raise a PR within the hour we might handle this internally.

**Comment by thienlnam** [comment] 2023-09-18 06:59
@mkhutornyi Please raise a PR so we can resolve this deploy blocker

**Comment by thienlnam** [comment] 2023-09-18 07:04
Going to assign you since @Li357 gave an initial approval

**Comment by CortneyOfstad** [comment] 2023-09-18 14:18
@Li357 ^^^ TIA!

**Comment by Ahmed-Abdella** [comment] 2023-09-19 11:00
@thienlnam @thienlnam Sorry, but why no reporting bonus paid here?

**Comment by thienlnam** [comment] 2023-09-20 04:29
Ah yeah this should be paid a reporting bonus

**Comment by CortneyOfstad** [comment] 2023-09-29 11:29
Sorry @eVoloshchak It shows that the external label was never applied to create the Upwork job. Removing your assignment as a C+ has already worked on this issue. 

Sorry for any hassle/confusion!

**Comment by CortneyOfstad** [comment] 2023-09-29 11:34
@Li357 I just want to confirm here that @mkhutornyi should get both the Contributor and C+ payment since they both proposed the fix and drafted the PR? Also, they should get the bonus for being within 3 days, correct? 

If so, that would be $500 for being the contributor + 50% bonus ($750); $500 for being C+ plus the 50% bonus ($750) — totaling $1,500. Does that appear to be correct?

@Ahmed-Abdella I have you down for the reporting bonus, so you are all set! Will be sending out the proposals in Upwork, once I have that above clarified 👍

**Comment by CortneyOfstad** [comment] 2023-10-05 18:03
@Li357 bump again

**Comment by Li357** [comment] 2023-10-06 04:50
Sorry about the delay! If I'm interpreting this [SO](https://stackoverflowteams.com/c/expensify/questions/8590/8591#8591) right, that should be correct.

**Comment by CortneyOfstad** [comment] 2023-10-06 14:14
Thanks @Li357!

@Ahmed-Abdella — can you link me your Upwork profile? I'm having trouble finding it and I want to make sure that I am sending the proposal to the correct individual. Thank you!

@mkhutornyi — same as above. I want to make sure I am sending the proposal to the correct individual as there are two "Mykhailo K." entries in Upwork. 

Thanks!

**Comment by Ahmed-Abdella** [comment] 2023-10-06 14:17
@CortneyOfstad Sure, here it is  https://www.upwork.com/freelancers/~014640fcd762b61d2f

**Comment by CortneyOfstad** [comment] 2023-10-06 14:25
> I am the one whom you just paid in https://github.com/Expensify/App/issues/26243 🙂

For some reason that one had your hiring profile listed automatically, but not this one 🤔 So weird! Thanks @mkhutornyi and send over the proposal!

@Ahmed-Abdella Also sent over your proposal! Let me know when these are accepted and I'll get them paid ASAP 👍

**Comment by Ahmed-Abdella** [comment] 2023-10-06 14:27
@CortneyOfstad I accepted the offer, Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-06 14:52
Both have been paid! 

@Li357 and @mkhutornyi where are we at with the checklist above? Thanks!

**Comment by CortneyOfstad** [comment] 2023-10-09 13:47
Regression Test GH created here — https://github.com/Expensify/Expensify/issues/324340

**Comment by CortneyOfstad** [comment] 2023-10-09 13:48
Thanks all! Closing!

**Closed by CortneyOfstad** 2023-10-09 13:48 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
