### ISSUE TITLE
Web - Chat - The strikethrough on heading messages deleted while offline is not aligned in Chrome

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20084] opened 2023-06-02 17:40 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app
2. Go to any chat
3. Send a heading message (`# Heading`)
4. Now switch to offline mode and delete the message
5. Notice the strikethrough is not aligned

## Expected Result:
The strikethrough aligned in the middle as seen on other platforms

## Actual Result:
The strikethrough is aligned to the bottom of the message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.22.0

**Reproducible in staging?:** n/a

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Web_Chrome](https://github.com/Expensify/App/assets/93399543/1f5816ba-e519-4ac6-8f88-c5b361059018)
![Desktop_MacOS](https://github.com/Expensify/App/assets/93399543/c028d986-f744-438d-bc6e-f65a4efbada9)

**Expensify/Expensify Issue URL:**

**Issue reported by:** pubudu-ranasinghe

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684775756347189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment] 2023-06-02 19:15
Duplicate of https://github.com/Expensify/App/issues/18658

**Comment by lschurr** [comment] 2023-06-05 14:15
Going to close this one since it's a dupe.

**Closed by lschurr** 2023-06-05 14:15 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
