### ISSUE TITLE
[$500] [Distance] - Android - The map zooms in to the selected location after zooming out

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27266] opened 2023-09-12 15:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open request money
2. change the tab to distance
3. Select start and/or finish locations
4. Zoom out the map

## Expected Result:
The map should stay on zoomed out position

## Actual Result:
The map zooms in everytime you try to zoom out

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.68-12

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/07f31623-fac0-49b9-b975-406433da29f3

https://github.com/Expensify/App/assets/115492554/7c01f3b6-9fa4-45e1-b624-44c25b471b57

**Expensify/Expensify Issue URL:**

**Issue reported by:** @jo-ui

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693973579700869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5f044f62202d3bf</li>
        <li>Upwork Job ID: 1701625571528986624</li>
        <li>Last Price Increase: 2023-09-19</li>
    </ul>
</details>

**Comment by dylanexpensify** [comment] 2023-09-13 13:07
@neil-marcellini assigning you as it's related to distance! LMK if you get any scan receipt bugs and I'll take em!

**Comment by ahmedGaber93** [comment] 2023-09-20 16:02
> Thanks for the proposal, the root cause seems to be missing some explanation, like why does this bug affects only android and not IOS as well ?

@fedirjh 
Yes, I agree about `isGestureActive` but not about iOS, I know the issue happened on android only,
But the infinite loop also happened in iOS.

Try log anything in `setMapIdle` then select the start point, you will see the infinite logs in console.


https://github.com/Expensify/App/assets/41129870/f1459408-9300-4986-a95c-75dc242998f4




#### why issue happened on android only while the infinite loop happend also in ios?
this because `isGestureActive` break the loop and not call `setIsIdle(true);`  after cleanup make it `false`, and I think if the code work as expected (without the infinite loop), we don't need `isGestureActive`,
because this part `if (e.gestures.isGestureActive) return;` is blocking nothing, calling  `setIsIdle(true);` while `isIdle` is already true should not trigger any state changes, but the cleanup I explain is changed `isIdle` to false and this should only happen on blur.

**Comment by neil-marcellini** [comment] 2023-09-22 02:26
@dylanexpensify would you please stay assigned for the BugZero role? Also I think we should close this because we're planning to make the map non-interactive while fixing this issue https://github.com/Expensify/App/issues/22716

Idk but maybe we want to pay the reporting bonus, since this was a legit bug.

**Comment by ahmedGaber93** [comment] 2023-09-22 02:42
> Also I think we should close this because we're planning to make the map non-interactive

@dylanexpensify 
Other than make the map non-interactive, the root cause of this issue need to fixed.
We have an infinite loop in native when we set the camera after adding the waypoint, see this video [here](https://github.com/Expensify/App/issues/27266#issuecomment-1728022348)

**Comment by neil-marcellini** [comment] 2023-09-22 02:57
@ahmedGaber93 would you please create a new bug report for that since it's a separate issue?

**Comment by ahmedGaber93** [comment] 2023-09-22 03:11
@neil-marcellini 
Hmm…, I think without map interaction, I can't approve the issue for QA team.
I explained The root cause to C+ @fedirjh, and it is accepted, but I can't report a bug with only technical details because QA team are not qualified for this.

**Comment by neil-marcellini** [comment] 2023-09-25 06:50
Please tag me in the bug report and I can create the issue for you @ahmedGaber93. Bump @dylanexpensify for payment.

**Comment by jo-ui** [comment] 2023-09-25 09:29
@dylanexpensify I've applied on upwork

**Comment by dylanexpensify** [comment] 2023-09-25 09:31
Offer sent @jo-ui!

**Comment by dylanexpensify** [comment] 2023-09-25 09:36
paid!

**Closed by dylanexpensify** 2023-09-25 09:36 UTC
Labels: External, Daily, Help Wanted, Bug
