### ISSUE TITLE
Web - No 'noindex' meta tag on storybook staging

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21954] opened 2023-06-30 14:10 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/21646
## Action Performed:
1. Go to https://staging.new.expensify.com/docs/iframe.html?id=components-form--server-error&viewMode=story
2. Open the JS console and click on Elements
3. Press CTRL+F and search for noindex

## Expected Result:
![Expected 1](https://github.com/Expensify/App/assets/78819774/bc1e2f56-9e35-4362-80ac-57dd5b633ba7)

## Actual Result:
![Expected 2](https://github.com/Expensify/App/assets/78819774/64a90819-2707-4dd6-bec2-778ad21cbf0b)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35.4

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/44488527-e82f-40e3-a0a9-4e0767cdb83d

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by PrashantMangukiya** [comment] 2023-06-30 14:46
## Proposal

Posting proposal early as per new [guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#propose-a-solution-for-the-job)

### Please re-state the problem that we are trying to solve in this issue.
No 'noindex' meta tag on storybook staging

### What is the root cause of that problem?
Meta index not added in .storybook/manager-head.html here:

https://github.com/Expensify/App/blob/0bbf3fccfce0994ddf4fd9e95fb33dd9edbd1868/.storybook/manager-head.html#L1-L3

### What changes do you think we should make in order to solve the problem?
We have to add meta index in manager-head.html as shown below:

```html
<link rel="icon" type="image/png" href="logo.png" />
<link rel="stylesheet" type="text/css" href="css/fonts.css" />
<link rel="stylesheet" type="text/css" href="index.css" />
<meta name="robots" content="noindex" /> // *** ADD THIS ***
```

### What alternative solutions did you explore? (Optional)
None

**Comment by dylanexpensify** [comment] 2023-07-03 08:49
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment] 2023-07-04 11:15
@lanitochka17 I'm not able to reproduce. No results showing when using the link provided, searching in elements, "noindex"

**Comment by dylanexpensify** [comment] 2023-07-07 08:40
closing, not able to repro

**Closed by dylanexpensify** 2023-07-07 08:40 UTC
Labels: Daily, Overdue, Bug
