### ISSUE TITLE
[HOLD for payment 2023-06-30] [$1000] Android - Share code - Copied link has NOT staging label

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19464] opened 2023-05-23 17:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/19249

## Action Performed:
1. Open the App
2. Login with any account
3. Go to settings > Share code
4. Click on "Copy URL to clipboard"
5. Go any chat.
6. Paste the link.
7. Verify that the url is treated as a link

## Expected Result:
Copied link has staging label

## Actual Result:
Copied link has NOT staging label

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** n/a

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/f2c90b9aef4ae82b8e2a172f074f90a3824b4b9a476747a628ef41eed4bafad8

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01015fed2b575db172</li>
        <li>Upwork Job ID: 1661856374223589376</li>
        <li>Last Price Increase: 2023-06-08</li>
    </ul>
</details>

**Comment by kevinksullivan** [comment] 2023-05-25 21:46
@kbecciv I don't see this issue when I try it, or at least I am not seeing different things in each account. I sent the link from staging on one account, and it didn't show staging in the URL. Then when I went to the recipient's account I also didn't see staging. 

<img width="289" alt="image" src="https://github.com/Expensify/App/assets/22508290/fc8ab975-2e2f-42e1-b28b-813b059e2257">


Is the issue that the URL is different in one view v. the other, or that it should showing staging in both URLs?

**Comment by kevinksullivan** [comment] 2023-05-25 22:06
got clarity in slack, moving on!

**Comment by shivansh9007** [comment] 2023-05-27 01:42
@kevinksullivan could you please share the insights that you got here, with steps to reproduce. I am not able to reproduce it.
Thanks!

**Comment by rojiphil** [comment] 2023-05-27 03:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Share Code - Copied link does not have staging label on Android devices when the app is run in debug mode.

### What is the root cause of that problem?

The root cause of the problem is that when the app is run in debug mode in android devices, the environment file is not properly set [here](https://github.com/Expensify/App/blob/main/android/app/build.gradle#LL58C5-L58C19) 

### What changes do you think we should make in order to solve the problem?

Replace the `envConfigfiles` for `debug` from `.env` to `.env.staging` [here](https://github.com/Expensify/App/blob/main/android/app/build.gradle#LL58C5-L58C19) 

`debug: ".env.staging",
`
Also, add the following line:

`apply from: project(":react-native-config").projectDir.getPath() + "/dotenv.gradle"`

### What alternative solutions did you explore? (Optional)

**Comment by mananjadhav** [comment] 2023-05-27 14:32
@rojiphil I think I agree with the .env file changes but I am not convinced if we should just change it to `.env.staging` for debug mode. The reason being, what if I am running a local build?

> apply from: project(":react-native-config").projectDir.getPath() + "/dotenv.gradle"

And what's the reasoning for changing the filepath from top to bottom?

**Comment by rojiphil** [comment] 2023-05-27 20:28
@mananjadhav Thanks for your feedback.

> And what's the reasoning for changing the filepath from top to bottom?

Adding at the top does not help in reading the config file whereas adding to the bottom helps. Attaching the build output for your reference.
![Capture](https://github.com/Expensify/App/assets/3004659/29f27801-454a-4285-8ef8-9c7b73ecdeb9)



> I think I agree with the .env file changes but I am not convinced if we should just change it to `.env.staging` for debug mode. The reason being, what if I am running a local build?

Not sure if I understood your comment correctly. Did you mean the local release build as shown [here](https://github.com/Expensify/App/blob/main/android/app/build.gradle#L59)?

**Comment by mananjadhav** [comment] 2023-05-29 23:13
Not the local release build, but local debug build will always use staging env? I don't think we would want that.

**Comment by thuyle04** [comment] 2023-05-30 09:28
@kbecciv I check this issue and see that:
- When I use file .env with content to be copied from .env.staging. This bug doesn't occur. Copied link has staging label.
![image](https://github.com/Expensify/App/assets/63705956/07f088a8-1c57-4fb3-9368-cf24fa10b6c6)

- When I use file .env with content to be copied from .env.production. This bug will occur.
![image](https://github.com/Expensify/App/assets/63705956/c513e03d-58fa-45d2-a92a-f2f867fec059)

So, I think that copied link has staging label only to be shown in staging environment.

**Comment by rojiphil** [comment] 2023-05-30 09:37
> Not the local release build, but local debug build will always use staging env? I don't think we would want that.

@mananjadhav We can set the local environment variable for config files and run the debug version with staging or production configuration file like this in package.json

```
    "android-staging": "scripts/set-pusher-suffix.sh && export ENVFILE=.env.staging && npx react-native run-android --port=8083",
    "android-production": "scripts/set-pusher-suffix.sh && export ENVFILE=.env.production && npx react-native run-android --port=8083",
```

I think, this would resolve the problem. Let me know if this is fine and I can update the proposal accordingly.

**Comment by mananjadhav** [comment] 2023-05-30 09:43
I am going to take an opinion from @alex-mechler if we're okay to update the package.json.

**Comment by thuyle04** [comment] 2023-05-30 10:06
Contributor details
MyeExpensify account email: thuy.le@antbuddy.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01fcd9ed589276332f

**Comment by alex-mechler** [comment] 2023-05-30 19:08
If updating the package.json solves the root cause of this, we are okay to change it

**Comment by alex-mechler** [comment] 2023-06-01 23:36
Still looking for / reviewing proposals

**Comment by rojiphil** [comment] 2023-06-02 01:50
@alex-mechler, @mananjadhav 
I thought, my [proposal here](https://github.com/Expensify/App/issues/19464#issuecomment-1565190797) along with  [this comment ](https://github.com/Expensify/App/issues/19464#issuecomment-1568116901) resolves the problem.
Or am I missing something here? Please let me know.

**Comment by alex-mechler** [comment] 2023-06-02 17:09
Oh, I had missed that, sorry about that! @mananjadhav Can you re-review proposals based on https://github.com/Expensify/App/issues/19464#issuecomment-1568938289

**Comment by alex-mechler** [comment] 2023-06-05 19:09
@mananjadhav Bump :)

**Comment by mananjadhav** [comment] 2023-06-06 05:36
@rojiphil @alex-mechler thanks for the patience here, but I think it wouldn't make sense to update package.json unless we've run out of all the options. I think it is straight forward right now to just run `npm run android`. I also don't think `android` command is the problem because when we run staging builds I am assuming we use `android-build` commands.

@alex-mechler ?

**Comment by rojiphil** [comment] 2023-06-06 06:10
@mananjadhav Ok. So, if we have to leave the `package.json` as it is and allow `npm run android` to use the staging environment, we can update the `.env` to `.env.staging` in `build.gradle` file. And, for use cases where there is a need to run a debug build with a production configuration file, we can also include the details in the relevant documentation. Would this be good enough?

**Comment by alex-mechler** [comment] 2023-06-06 19:23
> I also don't think android command is the problem because when we run staging builds I am assuming we use android-build commands.


We build with `fastlane android` for deploys 
https://github.com/Expensify/App/blob/bfdb3f10367441f3fc9e66fa995167c55e44c9ef/.github/workflows/platformDeploy.yml#L59-L70

**Comment by rojiphil** [comment] 2023-06-07 04:58
@mananjadhav @alex-mechler Let me try to summarize all the currently available options:

a) `npm run android`: 
Here, as proposed already, setting `.env.staging` in `build.gradle` will ensure that it will work with the staging environment. I think it makes sense to use a staging environment here as it is a debugging setup. **What are your thoughts?**

**Also, would there be any use case that would require us to test the debugging setup with the production environment?** 
And, even if we have to support testing the debugging setup with the production environment, we can use the following command: "android-production": "scripts/set-pusher-suffix.sh && export ENVFILE=.env.production && npx react-native run-android --port=8083". This can either be documented or added to package.json

b) `npm run android-build`: This is used to build a local release build via Fastlane. Currently, it uses a production environment for the local build.  Since it is meant to build a local build, I think, it should also be using a staging environment. **What are your thoughts here?**

Further, if we decide to add support for the other environment too, we can add an additional lane in `Fastfile` with `ENV["ENVFILE"]=` pointing to the correct environment.

c) For deployment purposes as mentioned [here](https://github.com/Expensify/App/issues/19464#issuecomment-1579324904)
I think, all deployments, whether it is beta or production, should point to the production environment only as it is done currently. For production deployment, there is no question about using it with a staging environment. But, then, **is there any use case that would demand the need for using beta deployments with a staging environment?**

d) **Any other points?**

As @MelvinBot suggested, I too agree that getting on to Slack will help us align faster on the above. Please let me know.

**Comment by kevinksullivan** [comment] 2023-06-09 04:11
@mananjadhav have you gotten a chance to review @rojiphil 's response?

**Comment by mananjadhav** [comment] 2023-06-11 21:40
I did review their comment, and at the second thought I think we should just **Do nothing** for this one.  I've started a slack thread [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1686519604828989)

**Comment by kevinksullivan** [comment] 2023-06-13 01:28
still chatting in that ^ slack thread

**Comment by rojiphil** [comment] 2023-06-14 04:59
As discussed on slack thread, working on updating the proposal based on `Environment.getEnvironment`

**Comment by rojiphil** [comment] 2023-06-14 13:03
@mananjadhav I have updated the [proposal](https://github.com/Expensify/App/issues/19464#issuecomment-1565190797). Kindly review.

**Comment by rojiphil** [comment] 2023-06-14 13:12
@mananjadhav Updated the [proposal](https://github.com/Expensify/App/issues/19464#issuecomment-1565190797)

**Comment by mananjadhav** [comment] 2023-06-14 17:53
@alex-mechler @rojiphil's updated proposal would work. @rojiphil I think in terms of code it would be better to take this out in a function. If a function already exists, we leverage that or add like a utils?

All yours.

**Comment by kevinksullivan** [comment] 2023-06-16 13:50
Offers sent @mananjadhav @rojiphil

**Comment by gadhiyamanan** [comment] 2023-06-16 13:53
@kevinksullivan you sent me an offer instead of @mananjadhav 😂

**Comment by kevinksullivan** [comment] 2023-06-16 14:50
well shoot 😅 , fixing that now

**Comment by rojiphil** [comment] 2023-06-16 15:22
@kevinksullivan, I have been assigned the work [here](https://github.com/Expensify/App/issues/19464#issuecomment-1591823014). Also, I had applied in upwork. 
Not sure what is the confusion here. 
Please clarify

**Comment by kevinksullivan** [comment] 2023-06-19 14:48
@rojiphil sorry for the confusion, I'm not sure what happened. I just sent another job offer. Let me know when you see/accept it.

**Comment by rojiphil** [comment] 2023-06-19 15:59
@kevinksullivan Saw the offer and accepted. Thanks.

**Comment by kevinksullivan** [comment] 2023-06-21 13:48
@flodnv added engineering label to have someone step in on the PR review for Alex.

https://github.com/Expensify/App/pull/21107

**Comment by kevinksullivan** [comment] 2023-06-22 22:29
Waiting 6 days for any regressions

**Comment by anmurali** [comment] 2023-07-01 19:38
Paid @mananjadhav  on New Dot

**Comment by rojiphil** [comment] 2023-07-02 01:20
@kevinksullivan  Gentle reminder as I am also awaiting payment.

**Comment by kevinksullivan** [comment] 2023-07-03 15:56
hi @mananjadhav can you finish out the steps above please? Thanks!

**Comment by kevinksullivan** [comment] 2023-07-03 16:02
@rojiphil sorry for the confusion here. A few weeks ago it seems I created another job for you but I'm not seeing it. Do you have an upwork job for this, and can you provide the link here? If not I'll just have to create another one.

**Comment by rojiphil** [comment] 2023-07-03 16:14
@kevinksullivan Here is the [link to the Upwork job](https://www.upwork.com/nx/wm/workroom/33952771/overview). 
I have also sent you a message on Upwork if that helps in tracking within Upwork.

**Comment by mananjadhav** [comment] 2023-07-03 17:45
Yes @kevinksullivan, I'll post an update tomorrow.

**Comment by kevinksullivan** [comment] 2023-07-03 20:24
Thanks @rojiphil , all set.

**Comment by rojiphil** [comment] 2023-07-04 05:11
Thanks @kevinksullivan @mananjadhav @AndrewGable @alex-mechler @MelvinBot. This was my first contribution to Expensify. Love the fairness, transparency, and process-oriented approach here.

**Comment by mananjadhav** [comment] 2023-07-04 05:22
Ohh that's good to hear @rojiphil. thanks for the patience on this one and appreciate your contribution. Welcome to the community. Looking forward to working with you more :)

**Comment by mananjadhav** [comment] 2023-07-04 20:36
In this [PR](https://github.com/hungvu193/App/commit/01e8334bf64fe2a57afaf4877494350c7a901eb9), we added a fixed variable `NEW_EXPENSIFY`, which isn't set based on the environment. I wouldn't treat this so much as bug as we were on the fence to even fix this. We fixed this for uniformity.

I don't think we need a regression test for this one. @flodnv @kevinksullivan wdyt?

**Comment by flodnv** [comment] 2023-07-05 11:01
Agreed

**Comment by kevinksullivan** [comment] 2023-07-06 16:38
yup, agree @mananjadhav

**Comment by kevinksullivan** [comment] 2023-07-06 16:39
Closing out!

**Closed by kevinksullivan** 2023-07-06 16:39 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
