### ISSUE TITLE
[HOLD for payment 2023-10-25] [$250] Workspace - Display name for #announce room members in details page is cut off

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#29321] opened 2023-10-11 14:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.81-4

**Reproducible in staging?:** Yes

**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

## Action Performed:
Precondition: User A and B do not have display name (display name is email).
1. Go to staging.new.expensify.com
2. [User A] Create a workspace and invite User B.
3. [User B] Go to #announce room and click on the room header

## Expected Result:
The display name for User A and B is not cut off

## Actual Result:
The display name for User A and B is cut off

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/78819774/669e9154-fd6a-4e45-90e8-9d58fa935bea

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013b93f9ecc21f556d</li>
        <li>Upwork Job ID: 1712142512040468480</li>
        <li>Last Price Increase: 2023-10-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 27149144</li>
<li>ginsuma | Contributor | 27217842</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by techievivek** [comment] 2023-10-11 16:14
@ginsuma 

> In this PR https://github.com/Expensify/App/pull/28200, we changed the condition to use the full title.
> Take it back to the old condition.

We don't want to take it back to the old condition because we want the setting option to be visible there.

**Comment by akinwale** [comment] 2023-10-11 16:17
> @ginsuma
> 
> > In this PR https://github.com/Expensify/App/pull/28200, we changed the condition to use the full title.
> > Take it back to the old condition.
> 
> We don't want to take it back to the old condition because we want the setting option to be visible there.

What's the expected behaviour here? Should it show the display names only if it's a group chat?

**Comment by techievivek** [comment] 2023-10-11 16:23
We want to display the full title.

> Should it show the display names only if it's a group chat?

For group chats let's truncate to show only first 2-3 members.

**Comment by techievivek** [comment] 2023-10-11 16:25
Also, going to remove the deploy blocker label since it's not worth holding the deploy for it.

**Comment by akinwale** [comment] 2023-10-11 18:07
## Proposal
[Updated](https://github.com/Expensify/App/issues/29321#issuecomment-1757924308)

**Comment by Santhosh-Sellavel** [comment] 2023-10-11 18:10
@alexpensify Can you assign a new C+ here by applying the external label again, low bandwidth so unassigning myself!

**Comment by alexpensify** [comment] 2023-10-11 20:23
Thank you for your feedback @Santhosh-Sellavel! I've asked for help here: https://expensify.slack.com/archives/C02NK2DQWUX/p1697055709578799

**Comment by alexpensify** [comment] 2023-10-11 20:34
@situchan will be helping out on the C+ side here. Thanks!

**Comment by situchan** [comment] 2023-10-11 20:59
@techievivek `shouldDisableSettings` was removed just to show Settings option always and this should not affect old logic of `shouldUseFullTitle` condition, correct? (https://github.com/Expensify/App/issues/29321#issuecomment-1758054316)

**Comment by techievivek** [comment] 2023-10-13 06:15
> shouldDisableSettings was removed just to show Settings option always and this should not affect old logic of shouldUseFullTitle condition, correct?

True, we just removed it to show the settings for all the reports.

**Comment by techievivek** [comment] 2023-10-13 06:15
CC @situchan

**Comment by techievivek** [comment] 2023-10-16 10:45
@situchan Can you please review the proposals above?

**Comment by situchan** [comment] 2023-10-16 10:47
Let's assign @ginsuma as the proposed solution meets the expected result

**Comment by alexpensify** [comment] 2023-10-26 22:29
Here is the payment summary: 

-  External issue reporter N/A 
-  Contributor that fixed the issue @ginsuma 
-  Contributor+ that helped on the issue and/or PR @situchan 

Upwork Job: 


*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: There is an urgency bonus here https://github.com/Expensify/App/issues/29321#issuecomment-1765585800

**Comment by alexpensify** [comment] 2023-10-26 22:32
@techievivek - can you please clarify if there was a discussion to edit the price here to $250? I was going to pay here but realized that this amount is not a normal one. I want to double-check if the urgency bonus applies here too. Thanks!

**Comment by situchan** [comment] 2023-10-27 07:27
Bonus might apply for low price issues as well.
ref: https://github.com/Expensify/App/issues/29639#issuecomment-1775710362

**Comment by techievivek** [comment] 2023-10-27 08:31
@situchan I updated the pricing to $250 because it was a straightforward change without much of to-and-fro, so I don't think we will include a bonus payment here since it's very likely that it will get merged in a single day. But I will bring this to team so they can also share their thoughts, I will update you once we reached a consensus, thanks.

**Comment by alexpensify** [comment] 2023-10-27 18:28
Thanks, I'm going to share $375 which includes the urgency bonus and the decreased amount agreed to here.

**Comment by alexpensify** [comment] 2023-10-27 18:35
Everyone has been paid in Upwork. 

@situchan can you please complete the checklist and we can close this GH? Thanks!

**Comment by situchan** [comment] 2023-10-27 19:02
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/28200
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/28200/files#r1355755359
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug.
- [x] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

This was caught by QA team, which means regression test already exists.

**Comment by alexpensify** [comment] 2023-10-27 19:05
Thank you, it's closing time here. Great work!

**Closed by alexpensify** 2023-10-27 19:05 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by alexpensify** [comment] 2023-10-30 03:47
@ginsuma - I think we are all set here. I checked and Upwork is showing the two transactions - $250 and $125.
