### ISSUE TITLE
[$500]  Group chat - Same number with country code and no country code can be added

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37537] opened 2024-02-29 17:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.45-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4354056
**Email or phone of affected tester (no customers):** gocemate@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to FAB> Start Chat
2. Enter phone number with no country code
3. Add this user to Group
4. Enter the same phone number with country code prefix
5. Add this user to Group
6. Create the group chat

## Expected Result:
There should be not allowed same phone number to be added twice

## Actual Result:
Same phone number with prefix and with no prefix as country code can be added when create group chat

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/90e0de04-9946-4d2a-b8b6-689445c6a541

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a201716597980b5f</li>
        <li>Upwork Job ID: 1765424009302786048</li>
        <li>Last Price Increase: 2024-03-13</li>
<li>Automatic offers: </li>
<ul>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-29 17:49
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by adelekennedy** [comment] 2024-03-04 20:10
agreed for VIP VSB - asking if this can be external and if this is the right project

**Comment by adelekennedy** [comment] 2024-03-06 17:06
I think we can make this external and slot it under vip-vsb

from @puneetlath 
>From looking at the video it doesn't look like we create dupe accounts in that scenario. It looks like it's just a client side issue where it acts like it's going to create two. But then only ends up creating one

**Comment by webbdays** [comment] 2024-03-07 18:00
Its not just with the phone numbers,
you can type any email address, add to group chat and then message.
No matter if that email address is associated with any account.

**Comment by adelekennedy** [comment] 2024-03-12 02:12
@aimane-chnaif for your thoughts on the proposal above and Puneet's comment [here](https://github.com/Expensify/App/issues/37537#issuecomment-1981370616)

**Comment by ijmalik** [comment] 2024-03-13 09:57
**Please re-state the problem that we are trying to solve in this issue.**
Redundant addition of phone numbers, with or without country code prefixes, occurs during group chat creation.

**What is the root cause of that problem?**
The root cause lies in inconsistent phone number formatting, leading to discrepancies when comparing them.

**What changes do you think we should make in order to solve the problem?**
src/languages/en.ts and src/languages/es.ts
![a1](https://github.com/Expensify/App/assets/2220885/71fd3c0f-7df0-4ce3-9e95-acf341985e35)

src/libs/OptionsListUtils.ts
![b](https://github.com/Expensify/App/assets/2220885/e15a99d5-84ae-4e89-a68f-f12d2d8bcff8)

src/pages/NewChatPage.tsx
![c1](https://github.com/Expensify/App/assets/2220885/185435b7-2f0c-47fb-99c8-7c78a872a0e3)


https://github.com/Expensify/App/assets/2220885/0c1626c6-3e1b-4aab-bb7c-0db53b9a5a00

**Comment by adelekennedy** [comment] 2024-03-13 18:55
@aimane-chnaif it looks like we have a few proposals to review - will you be able to check these this week or do we need to reassign?

**Comment by ijmalik** [comment] 2024-03-13 23:31
@aimane-chnaif 
I have updated the [proposal](https://github.com/Expensify/App/issues/37537#issuecomment-1993994567)

**Comment by mvtglobally** [comment] 2024-03-14 15:41
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment] 2024-03-20 03:41
Issue not reproducible during KI retests. (Second week)

**Closed** 2024-03-22 15:29 UTC
Labels: External, Daily, Bug

**Comment by iwiznia** [comment] 2024-03-22 16:24
I saw it, but I don't see the problem, in the end it created the chat with just one user, which is correct.
