### ISSUE TITLE
[$500] Chat - The composer jumps when editing a message

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36374] opened 2024-02-12 20:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Navigate to a chat with a lot of text messages
2. Edit the text closest to the composer

## Expected Result:
It shouldn't shake or jump

## Actual Result:
The composer jumps when editing a message - [see this video for an example](https://github.com/Expensify/App/issues/36374#issuecomment-1942945250)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f101889f-6e39-46c6-9ceb-9bcea89cd234

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011ebf704e63731d68</li>
        <li>Upwork Job ID: 1757147558004047872</li>
        <li>Last Price Increase: 2024-04-01</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-12 21:01
We (Applause) think this bug might be related to #vip-vsb

**Comment by jliexpensify** [comment] 2024-02-12 21:18
@ntdiary I got assigned a similar action (i.e. shaking occurs when tapping on something) here: https://github.com/Expensify/App/issues/34300

Do you think the root cause would be the same?

**Comment by jliexpensify** [comment] 2024-02-13 21:14
Than ks @ntdiary - going to reassign for now! @s77rt - [please see my question here](https://github.com/Expensify/App/issues/36374#issuecomment-1939600574)!

**Comment by s77rt** [comment] 2024-02-13 22:04
@jliexpensify No they seem different. This one is related to the main composer getting hidden which makes the editing composer change position (jump)

**Comment by jliexpensify** [comment] 2024-02-14 00:49
@m-natarajan you checked the `ios: native` box but your video seems to be iOS Safari (or another browser).

I also can't really reproduce this, @s77rt could this issue be related to how the keyboard pops up?

**Comment by s77rt** [comment] 2024-02-14 01:24
@jliexpensify No, it's only due to the fact that we are hiding the main composer so everything shift down including the edit composer


https://github.com/Expensify/App/assets/16493223/52a8a3e2-8790-4a9a-abdc-6fa04bcdc79e

| Before | After |
|--------|-------|
| <img width="558" alt="Screenshot 2024-02-14 at 2 21 01 AM" src="https://github.com/Expensify/App/assets/16493223/3a55f3de-ec72-45c2-9414-218cc550a5aa">       |    <img width="558" alt="Screenshot 2024-02-14 at 2 21 06 AM" src="https://github.com/Expensify/App/assets/16493223/87e5282a-3f6b-478b-b8e2-d2900316fb50">   |

**Comment by jliexpensify** [comment] 2024-02-14 02:35
Thanks for sharing that video @s77rt - I can see it a bit more clearly now. Is it something that is a pretty simple/straightforward fix?

**Comment by s77rt** [comment] 2024-02-14 03:08
@jliexpensify I didn't check in depth but I don't think fixing this would be straightforward.

**Comment by jliexpensify** [comment] 2024-02-14 03:10
Cool, lets wait for some proposals then - thanks!

**Comment by s77rt** [comment] 2024-02-16 21:20
Not overdue. Looking for proposals

**Comment by jliexpensify** [comment] 2024-02-19 23:20
Waiting for proposals!

**Comment by s77rt** [comment] 2024-02-22 22:22
Still looking for proposals

**Comment by s77rt** [comment] 2024-02-26 16:49
Still looking for proposals

**Comment by s77rt** [comment] 2024-02-29 21:14
Still looking for proposals

**Comment by s77rt** [comment] 2024-03-04 12:27
Same ^

**Comment by jliexpensify** [comment] 2024-03-05 02:41
@s77rt can you reproduce this one? I tried again and don't see the jump on Android. I wonder if this is just a mobile limitation with the keyboard pushing the edited sentence up and then down?

**Comment by s77rt** [comment] 2024-03-05 11:32
@jliexpensify The jump behaviour is more noticeable on mWeb. Though this seems a minor bug, do you think we should close the issue?

**Comment by jliexpensify** [comment] 2024-03-05 23:45
I think we should still keep it open, I'll post to the Open-Source channel since we haven't had any proposals yet!

**Comment by s77rt** [comment] 2024-03-11 19:08
Still looking for proposals. Should we make this `External` again?

**Comment by brunovjk** [comment] 2024-03-12 15:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The problem is the unexpected jump in the composer when editing messages in a chat with numerous text messages.

### What is the root cause of that problem?
The root cause is the dynamic hiding of the main composer when editing a message/comment:
https://github.com/Expensify/App/blob/4ac2dd7d391b53b5b8afc480cae61d8335da3209/src/pages/home/report/ReportActionItemMessageEdit.tsx#L428
https://github.com/Expensify/App/blob/4ac2dd7d391b53b5b8afc480cae61d8335da3209/src/pages/home/report/ReportFooter.tsx#L134
Leading to abrupt movements during message editing.


### What changes do you think we should make in order to solve the problem?
Implement a smooth animation for rendering and hiding the composer to ensure a seamless user experience. While I'm new here, I believe we need to coordinate with the design and UX teams to maintain consistency if we adopt this solution.

### What alternative solutions did you explore? (Optional)
Consider using the main composer when editing the last message instead of introducing the new composer and hide the main.

**Comment by s77rt** [comment] 2024-03-12 22:10
@brunovjk Thanks for the proposal. Your RCA makes sense. Regarding the suggested solution I'm not sure if animation would help much here. Were you able to work on a PoC? As for the alternative solution we don't want to use the main composer because we want to have the ability to edit multiple messages at the same time.

**Comment by jliexpensify** [comment] 2024-03-12 22:18
Made this one `External`, hopefully we get some more input!

**Comment by brunovjk** [comment] 2024-03-12 22:30
>  As for the alternative solution we don't want to use the main composer because we want to have the ability to edit multiple messages at the same time.

I see :D

> Were you able to work on a PoC?

Yes, I will post here soon.

**Comment by jeremy-croff** [comment] 2024-03-13 02:16
> @jliexpensify No, it's only due to the fact that we are hiding the main composer so everything shift down including the edit composer
> 
>  Screen.Recording.2024-02-14.at.2.13.26.AM.mov 
> Before	After
> <img alt="Screenshot 2024-02-14 at 2 21 01 AM" width="558" src="https://private-user-images.githubusercontent.com/16493223/304595270-3a55f3de-ec72-45c2-9414-218cc550a5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTYzNDAsIm5iZiI6MTcxMDI5NjA0MCwicGF0aCI6Ii8xNjQ5MzIyMy8zMDQ1OTUyNzAtM2E1NWYzZGUtZWM3Mi00NWMyLTk0MTQtMjE4Y2M1NTBhNWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNGE2YzhiNDY1MDI1ZWIwOGEyZjVmNmZiYzhlZjJkODc0M2ZiMTEzNzgyZDc4NGU4ZjUxODUzZWRjMDYzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POhkQ6uJjTk_cRxz4KM4HLCPTFcLbMp11Y_BgPARIMU">	<img alt="Screenshot 2024-02-14 at 2 21 06 AM" width="558" src="https://private-user-images.githubusercontent.com/16493223/304595292-87e5282a-3f6b-478b-b8e2-d2900316fb50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTYzNDAsIm5iZiI6MTcxMDI5NjA0MCwicGF0aCI6Ii8xNjQ5MzIyMy8zMDQ1OTUyOTItODdlNTI4MmEtM2Y2Yi00NzhiLWI4ZTItZDI5MDAzMTZmYjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjM5NmY5YWIwNmQxZTk1ZmYyMGJlZDcxODhmNjM5NzJkOWZkZGVjNmZiNGVmNDA5OWM3YmEzOTZhMDExZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GP_CSPJH3vOEW2NYA36tyBiRw_GodkvBhAFweml7KyQ">

In this video, would you want the keyboard to pop up?

**Comment by s77rt** [comment] 2024-03-13 12:32
@jeremy-croff I don't want the keyboard to pop up. That was a demonstration that the location of the edit input changes.

**Comment by brunovjk** [comment] 2024-03-13 18:20
> Were you able to work on a PoC? As for the alternative solution we don't want to use ...

Working on it. Thank you for the feedback.

**Comment by s77rt** [comment] 2024-03-14 14:32
@brandonhenry Thanks for the proposal. Your RCA is correct. Regarding the solution can you please attach a before and after videos for comparison?

**Comment by s77rt** [comment] 2024-03-14 15:12
@brandonhenry Thanks for the update. I'm not sure how is new behaviour better than what we have now. It kinda makes the app feel slower. cc @Expensify/design https://github.com/Expensify/App/issues/36374#issuecomment-1995705491

**Comment by brunovjk** [comment] 2024-03-14 15:13
@s77rt  I'm still working on this, and it looks like we have more problems that just animations won't solve. So far I see two things that cause these flicks.
1 - When start and finish the edit, there are times with 2 composers rendered and times with 0 composers. I wonder if there is a way to render composers synchronously, with a smooth transition or something.
2 - The first render of the `ReportActionItemMessageEdit composer` has 2 lines by default, and a moment later we calculate the number of lines correctly. We can ajust the default value of number of lines, still testing.

<details>
<summary>This video from the Performance tab shows it better:</summary>



https://github.com/Expensify/App/assets/95647348/e26e526a-9a2a-49e7-b105-ee2364be9fb6



</details>

I believe the cause of the problem is somewhat clear, but I am still working on solutions that do not cause regressions and make everything as smooth as possible, good animations take a little time to fine-tune. I will be back as soon as I have it. Any help/feedback is welcome.

**Comment by brunovjk** [comment] 2024-03-14 15:15
Maybe @brandonhenry and I can work together on these transition/animations? I saw what he did, I did the same here, it's really better, but I still see the list kinf of 'jumping'. Make senses?

**Comment by brunovjk** [comment] 2024-03-14 23:09
## Proposal
[Updated](https://github.com/Expensify/App/issues/36374#issuecomment-1991863603)

@s77rt  I believe we have some questions/issue here:
1. When rendering the `ReportActionItemMessageEdit composer`, we always start with two lines and then update the `numberOfLines` later, generating a small flick, more noticeable in messages with multiple lines.
2. Nonexistent transition/animation in Rendering/hiding of edit composer and main composer, generating flicks and jumps. We can try to align these transitions with `ONYXKEYS.SHOULD_SHOW_COMPOSE_INPUT`
3. Main composer appears even when we still have an edit composer open. Steps to reproduce in the proposal.

**Comment by s77rt** [comment] 2024-03-15 00:34
@brunovjk Thanks for the update. Good catch with the multiline issue. Can you please outline how we will fix that without PRs / code diffs?

**Comment by s77rt** [comment] 2024-03-15 00:37
@brunovjk 

> Main composer appears even when we still have an edit composer open. Steps to reproduce in the proposal.

That's expected since no edit composer is focused

**Comment by shawnborton** [comment] 2024-03-15 00:48
I'd be keen to find a solution that prevents any kind of jumping/movement. I can see where the animated approach feels nicer, but it doesn't feel like it really solves the issue.

**Comment by jeremy-croff** [comment] 2024-03-15 01:10
> I'd be keen to find a solution that prevents any kind of jumping/movement. I can see where the animated approach feels nicer, but it doesn't feel like it really solves the issue.

I reviewed the experience when the keyboard is open and it's much less jarring.

The primary reason for asking whether the keyboard should pop up here: https://github.com/Expensify/App/issues/36374#issuecomment-1993144489

Is because in native we do pop up the keyboard, and it's a smooth transition as both the keyboard pushes up, and the editable composer pushes towards it.

We could force a similar behavior for web, to open the keyboard. Especially cause in web the edit composer IS focused ( green ring ) but I'm surprised the keyboard diddn't pop up here.

However I would like some UX confirmation

**Comment by jeremy-croff** [comment] 2024-03-15 01:10
Native:

https://github.com/Expensify/App/assets/157416545/80bdb463-aa29-4a8b-9cc4-e951f6c235fe

**Comment by s77rt** [comment] 2024-03-15 01:40
@jeremy-croff Interesting! I thought the keyboard didn't show up just because I was on a simulator (hardware keyboard). I agree for consistency the keyboard should show up when editing a message.

**Comment by s77rt** [comment] 2024-03-15 01:42
The keyboard does not show up only on Safari. We had many similar bugs regarding focus. Safari won't open the keyboard unless it's a user action and within a limited time frame (I think it's 1sec).

**Comment by jeremy-croff** [comment] 2024-03-15 01:48
> The keyboard does not show up only on Safari. We had many similar bugs regarding focus. Safari won't open the keyboard unless it's a user action and within a limited time frame (I think it's 1sec).

I  confirmed also in IOS Chrome it doesn't pop up. 

On Android it does 👍

**Comment by brunovjk** [comment] 2024-03-15 12:06
> @brunovjk Thanks for the update. Good catch with the multiline issue. Can you please outline how we will fix that without PRs / code diffs?

@s77rt Thanks for the review. Thank you. Sure. We should calculate the `numberOfLines` from the [`draft`](https://github.com/Expensify/App/blob/2abedcdbbce61503498ef5a91c0eebe7496b60db/src/pages/home/report/ReportActionItemMessageEdit.tsx#L422) in `ReportActionItemMessageEdit` and then pass it as a [props](https://github.com/Expensify/App/blob/2abedcdbbce61503498ef5a91c0eebe7496b60db/src/components/Composer/index.tsx#L61) to the Composer Component.

**Comment by brunovjk** [comment] 2024-03-15 12:11
> @brunovjk
> 
> > Main composer appears even when we still have an edit composer open. Steps to reproduce in the proposal.
> 
> That's expected since no edit composer is focused

I understand, it makes sense, we need the main composer back when we are not focusing on anything, but doesn't that seem strange to you?
<details>
<summary>Strange behavior observed in the main composer when focusing and blurring edit composers.</summary>




https://github.com/Expensify/App/assets/95647348/06007af0-280a-46cc-9d2d-e189758d7984



</details>

I believe I can improve the logic how we deal with `ONYXKEYS.SHOULD_SHOW_COMPOSE_INPUT` when editing messages, this should mainly prevents any kind of jumping/movement. I'll be back when there's an update.

**Comment by s77rt** [comment] 2024-03-15 13:19
@brandonhenry The keyboard should open when editing a message. If we are going to add animation here we should take the keyboard animation into account. Animation is also a bandaide here. the optimal solution is to prevent the jump behaviour and not to just smooth it out.

**Comment by s77rt** [comment] 2024-03-15 13:26
@brunovjk

> We should calculate the numberOfLines from the [draft](https://github.com/Expensify/App/blob/2abedcdbbce61503498ef5a91c0eebe7496b60db/src/pages/home/report/ReportActionItemMessageEdit.tsx#L422)

Can you elaborate? How can we calculate the number of lines given a text input? Wouldn't we need to render the text first? (to measure its width)

> Strange behavior observed in the main composer when focusing and blurring edit composers.

That's actually a bug, we fixed that here https://github.com/Expensify/App/issues/23908 (Case 2) but looks like some recent change broke it. Let's not focus on that since it's a different bug.

**Comment by brunovjk** [comment] 2024-03-15 13:34
> How can we calculate the number of lines given a text input?

What do you think?
```
// ReportActionItemMessageEdit.tsx
...
    const numberOfLines = useMemo(() => {
        if (!draft) {
            return 1; // Return a default value if draft is empty
        }

        // Get the number of newline characters in the draft content
        const newlineCount = (draft.match(/\n/g) || []).length;

        // Add 1 to account for the last line
        const calculatedNumberOfLines = newlineCount + 1;
        return calculatedNumberOfLines;
    }, [draft]);
...
```

**Comment by s77rt** [comment] 2024-03-15 13:41
@brunovjk The text may wrap into multiple lines even if there is no LF char (`\n`).

**Comment by brunovjk** [comment] 2024-03-15 13:45
Hmm... I see, I have to dig further then. @s77rt do you have any idea?

**Comment by s77rt** [comment] 2024-03-15 21:22
@brunovjk 

> Hmm... I see, I have to dig further then. @s77rt do you have any idea?

Not really but I think we should work on the focus and animation issues first

**Comment by s77rt** [comment] 2024-03-15 21:27
@brandonhenry We don't want the main composer to show up when editing a message for two reasons:
1. Not to the confuse the user (can't tell where he is typing)
2. Get more space

| With main composer | Withoutmain composer |
|--------------------|----------------------|
|       <img width="409" alt="2022-05-18_14-02-07" src="https://github.com/Expensify/App/assets/16493223/db1908fd-2c73-485c-8303-55f509e907b5">            |          <img width="422" alt="2022-05-18_14-01-13" src="https://github.com/Expensify/App/assets/16493223/f6bc32a1-ab63-476e-b19c-8ad000574692">             |


> I noticed that the current behavior allows the main composer to be open simultaneously with the edit composer

As long as no edit composer is focused (the keyboard not visible) then the main composer is expected to be visible

**Comment by brunovjk** [comment] 2024-03-15 23:39
> Not really but I think we should work on the focus and animation issues first

Im on it :D

**Comment by brunovjk** [comment] 2024-03-15 23:43
> Not really but I think we should work on the focus and animation issues first

Im on it :D but I believe everything I listed so far is related to our flicking problem.

**Comment by brunovjk** [comment] 2024-03-15 23:44
> Not really but I think we should work on the focus and animation issues first

Im on it :D but I believe everything I listed so far is related to our flicking problem. I'll work on it this weekend and come back as soon as I have something.

**Comment by s77rt** [comment] 2024-03-18 16:31
Still looking for proposals

**Comment by jliexpensify** [comment] 2024-03-19 07:55
Hello @sakluger - I am headed OOO from the 21st to 31st March so have assigned you as a buddy here.

Summary:

- @s77rt is still awaiting suitable proposals

**Comment by mvtglobally** [comment] 2024-03-20 03:38
Issue not reproducible during KI retests. (First week)

**Comment by jliexpensify** [comment] 2024-03-20 05:01
@mvtglobally can you share a video please? Thanks!

**Comment by sakluger** [comment] 2024-03-20 23:07
Sounds like this may be fixed. Is anyone due payment? My assumption is no, @s77rt can you please confirm.

**Comment by s77rt** [comment] 2024-03-20 23:10
@sakluger If this is fixed already then no one would be due payment

**Comment by brunovjk** [comment] 2024-03-22 15:09
@s77rt I believe we've made significant progress in mitigating the 'shake or jump' issue by ensuring simultaneous rendering/hiding of the composer and text. I actually don't know how it was done, but it seems like that's what happened hehe.
However, a small 'shake or jump' persists due to the '2 lines' issue. I couldn't pinpoint the root cause, but it seems related to passing `numberOfLines=undefined` and `multiline=true` in the composer at [`ReportActionItemMessageEdit`](https://github.com/Expensify/App/blob/b9f3906f4d1edb5c294d0f929f397b7161c57200/src/pages/home/report/ReportActionItemMessageEdit.tsx#L408-L409). As calculating `numberOfLines` upfront remains challenging, setting `numberOfLines=1` has resolved the issue, but I wonder about potential regressions. 
I'm questioning the use of `0` as the default value in [`src/components/Composer/index.tsx`](https://github.com/Expensify/App/blob/b9f3906f4d1edb5c294d0f929f397b7161c57200/src/components/Composer/index.tsx#L61). Since I can't think of a scenario where `0` would be appropriate, changing it to `1` would also resolve the 'two-line composer issue'. Do you think this is worth fixing? If yes, here? Or should we create another issue?
Thank you for your time.

**Comment by s77rt** [comment] 2024-03-23 01:13
@brunovjk If the fix will only cover the case of 2 lines then it may not be worth it as it will only sound like a workaround (issue would still be reproducible where we have multiple lines)

**Comment by brunovjk** [comment] 2024-03-25 12:45
### Update:

@s77rt please take a look https://github.com/Expensify/App/pull/30964#issuecomment-1808403267:
_"We set the default value of `numberOfLines` in `ReportActionItemMessageEdit` composer to be `undefined`.
This is the same as not setting the `rows` property of `textarea`. If we don't set the `rows` property, textarea will have 2 `rows` by default."_

I didn't find any related issue. I'm still working on the function to calculate `numberOfLines` before render the composer.

**Comment by jliexpensify** [comment] 2024-03-31 23:43
Back, thanks Sasha - unassgning you!

**Comment by s77rt** [comment] 2024-04-05 01:52
Since the original bug does not seem to be reproducible anymore it makes sense to close this issue cc @jliexpensify

**Comment by s77rt** [comment] 2024-04-05 01:53
@brunovjk I don't think that issue is important enough given that bugs reports are limited but feel free to raise on Slack

**Closed** 2024-04-05 01:53 UTC
Labels: External, Engineering, Daily, Help Wanted, Bug
