### ISSUE TITLE
Attachment - File upload freezes when the application is reloaded

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31745] opened 2023-11-22 20:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.2-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Open New Expensify app
2. Disable the internet connection in the device
3. Navigate to any conversation and upload an attachment
4. Reload the app(CMD+R)
5. Enable the internet connection

## Expected Result:
If you upload a file offline and reload the app when you go online, the file should upload and appear in the conversation

## Actual Result:
When uploading a file in offline mode and reloading the application when going online, the file is not uploaded to the conversation and the upload freezes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4d9d437d-e7d3-4ef2-aa41-088bf6044d2a

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2023-11-22 20:28
Production:

https://github.com/Expensify/App/assets/78819774/b59e6827-1d32-4abe-bc61-0daf18e7d51e

**Comment by marcaaron** [comment] 2023-11-22 20:55
Checking this one now...

**Comment by marcaaron** [comment] 2023-11-22 20:56
>Open New Expensify app
>Disable the internet connection in the device
>Navigate to any conversation and upload an attachment
>Reload the app(CMD+R)

How does this work exactly if the network is disabled for Web?

**Comment by marcaaron** [comment] 2023-11-22 20:57
I can't repro on main web. Checking desktop.

**Comment by marcaaron** [comment] 2023-11-22 20:59
Unchecked the web platforms because refreshing the page while you are offline isn't really supported.

**Comment by marcaaron** [comment] 2023-11-22 21:01
Can't repro on Desktop. I think this should not be a deploy blocker so gonna check it off in any case. Unclear whether it is actually an issue that needs to be fixed so sending to BZ instead of blocking deploy.

**Comment by luacmartins** [comment] 2023-11-22 21:32
I have a feeling that this was caused by https://github.com/Expensify/App/pull/30425 which was reverted and CPed

**Comment by luacmartins** [comment] 2023-11-22 21:33
I think we can close this issue.

**Closed** 2023-11-22 21:42 UTC
Labels: Engineering, Daily, Bug
