### ISSUE TITLE
[$1000] Confirm Task menu item is cut off on touch

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18753] opened 2023-05-10 23:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Press the Global + (FAB) button
2. Select Assign Task
3. Complete the field and press Next
4. Press Assignee and select any user
5. Press down the Assignee/Share somewhere
6. Notice the menu is cut off

## Expected Result: 
The menu should stay fully visible
## Actual Result: 
The menu getting cut off

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.12
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/bfd3121d-d0ea-4f5d-985b-2be6b8c713f1

<img src="https://github.com/Expensify/App/assets/43996225/7ebb6aa5-3510-4530-a5ad-aa052d119dd6" width="40%" height="40%">

**Expensify/Expensify Issue URL:**
**Issue reported by:** @bernhardoj 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683727180608179

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a0d40385abc3107d</li>
        <li>Upwork Job ID: 1656605435245920256</li>
        <li>Last Price Increase: 2023-05-11</li>
    </ul>
</details>

**Comment by hungvu193** [comment] 2023-05-11 09:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Confirm Task menu item is cut off on touch
### What is the root cause of that problem?
We are fixing height for `TaskSelectorLink`,  but in difference devices for example my Pixel 6 emulator, the content of the `TaskSelectorLink` is overlap the height of 42, that's why when we long press the field the content is cut off.
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/styles/styles.js#L1687
### What changes do you think we should make in order to solve the problem?

Because we are allowing fontScale, that's bad idea to fix the height of a field, in order to fix this problem, we will need to remove the height of `TaskSelectorLink`. We can also replace the `TouchableOpacity` with `PressableWithFeedback` to prevent double click bugs (https://github.com/Expensify/App/pull/18122).
Since we don't limit the height of `TaskSelectorLink` we will also need to update the margin of it in here:
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/components/TaskSelectorLink.js#L54
and here:
https://github.com/Expensify/App/blob/1d951e6812a30376eaed21ee792c370626e82d89/src/pages/tasks/NewTaskPage.js#L162-L195

### What alternative solutions did you explore? (Optional)
None

**Comment by abdulrahuman5196** [comment] 2023-05-12 08:17
Thank you for the proposals. Will take a look into it in couple of hours

**Comment by cdanwards** [comment] 2023-05-12 13:10
@abdulrahuman5196 just a heads up, this visual bug is addressed in an iteration of the Tasks project here: https://github.com/Expensify/App/pull/18672/files#diff-8ab8ba45ab927f1430b8d1209d187e003a9cdfe476f809e4483ef64cdba253eb

**Comment by flaviadefaria** [comment] 2023-05-15 11:05
@stitesExpensify should you put this on hold and switch it to weekly?

**Comment by abdulrahuman5196** [comment] 2023-05-16 09:36
@flaviadefaria The PR is already merged. Will check if the issue is reproducible and update before EOD. We can take action based on that.

**Comment by abdulrahuman5196** [comment] 2023-05-16 14:31
I don't see this issue in main after the PR merge. I think we can close this issue.


https://github.com/Expensify/App/assets/46707890/1d60235c-d279-4dc0-96f6-dfc39af9a1aa

**Comment by flaviadefaria** [comment] 2023-05-17 08:54
Perfect so closing this!

**Closed by flaviadefaria** 2023-05-17 08:54 UTC
Labels: External, Daily, Help Wanted, Bug
