### ISSUE TITLE
[HOLD for payment 2023-10-30] [$500] Details - Comma appears before username in the detail page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#29453] opened 2023-10-12 14:47 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.83.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @ayazhussain79
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697040699753639

## Action Performed:
1. Navigate to Settings > Workspace > New workspace
2. Go to the workspace expense room
3. Send a message
4. Click on “Reply in thread”
5. Click on the thread header
6. Observe that a comma is displayed before the username

## Expected Result:
Comma should not be displayed before the username

## Actual Result:
Comma is shown before the username on the detail page.

## Workaround:
Unknown 

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/93399543/0622940e-1ad2-4c03-9c82-9a0468f7fbba

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/6ddbd2eb-fa4d-461d-b0fc-6d9251def2eb

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

 

https://github.com/Expensify/App/assets/93399543/83ba73fc-262f-4a84-984e-0a2e1ca4fcfd

https://github.com/Expensify/App/assets/93399543/a448e16d-e7ce-40db-a0ca-3c694c09c7d7

</details>

<details>
<summary>MacOS: Desktop</summary>

 

https://github.com/Expensify/App/assets/93399543/98e8749f-1551-4200-b989-8903d8583232

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014b6b128d6dc38a95</li>
        <li>Upwork Job ID: 1712480106690822144</li>
        <li>Last Price Increase: 2023-10-12</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 27265410</li>
</ul></li>
    </ul>
</details>

**Comment by c3024** [comment] 2023-10-12 14:47
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
_fake_  or empty string followed by comma and then then user is shown in display name for a thread created in workspace policy expense chat
### What is the root cause of that problem?
When we create a thread for the first time in a policy expense chat the backend adds a `participantID` '0' to the participants and this here 
https://github.com/Expensify/App/blob/633c94b9a4793230b06fd5a89cb1a5f7239c329a/src/pages/ReportDetailsPage.js#L146
fetched the details for accountID '0' as well which returns _fake_ or Hidden for the '0' accountID
### What changes do you think we should make in order to solve the problem?
1. We should fix the backend to not add '0' accountID as a participant
2. I think it is better if we return early here when accountID is '0' instead of adding details of it to personal details as an extra check. 
https://github.com/Expensify/App/blob/4df658462ecabe8679242ebe425e6e2f7699c880/src/libs/OptionsListUtils.js#L142-L148
```js
    _.each(accountIDs, (accountID) => {
        if (!accountID ) {         // or accountID === '0'
                 return;
        }
        const cleanAccountID = Number(accountID);
```
### What alternative solutions did you explore? (Optional)

**Comment by theTrozen77** [comment] 2023-10-14 11:35
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In the Details modal in the user name, we are seeing fake or comma before the actual user name content.

### What is the root cause of that problem?
We are getting a falsy value i.e. 0 in our case inside the `accountIDs` array passed into `getPersonalDetailsForAccountIDs` which gets looped further down the application inside `DisplayNamesWithToolTip` component to give us the above mentioned issue.

https://github.com/Expensify/App/blob/fe282b45cb13e01519282ccc023e5bfbd7714158/src/libs/OptionsListUtils.js#L142C1-L143C1

### What changes do you think we should make in order to solve the problem?
We need to clean the `accountIDs` array that is passed inside of `getPersonalDetailsForAccountIDs` so that it only contains Numbers and remove any falsy values.

Instead of checking or removing the falsy value inside of specific components, we should check and remove the falsy values inside of `getPersonalDetailsForAccountIDs`. 

```
function getPersonalDetailsForAccountIDs(accountIDs, personalDetails) {
    const personalDetailsForAccountIDs = {};
    if (!personalDetails) {
        return personalDetailsForAccountIDs;
    }

    here ---> accountIDs = _.compact(accountIDs)

    _.each(accountIDs, (accountID) => {
        const cleanAccountID = Number(accountID);
        let personalDetail = personalDetails[accountID];
        if (!personalDetail) {
            personalDetail = {
                avatar: UserUtils.getDefaultAvatar(cleanAccountID),
            };
        }

        if (cleanAccountID === CONST.ACCOUNT_ID.CONCIERGE) {
            personalDetail.avatar = CONST.CONCIERGE_ICON_URL;
        }

        personalDetail.accountID = cleanAccountID;
        personalDetailsForAccountIDs[cleanAccountID] = personalDetail;
    });
    return personalDetailsForAccountIDs;
}
```

I have added   `accountIDs = _.compact(accountIDs)` to make it consistent with the application coding structure and used it outside of  `_.each` .


### What alternative solutions did you explore? (Optional)

Alternate solution would be to remove it in the data that comes from the backend. But if it is not possible, this solution is well sufficient for the fix.

**Comment by theTrozen77** [comment] 2023-10-14 11:41
Contributor details
Your Expensify account email: prajwalpanta87@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~016a4ffa68a382833c

**Comment by sonialiap** [comment] 2023-10-17 11:52
@burczu what do you think of the proposals?

**Comment by sonialiap** [comment] 2023-10-17 11:53
I'm OOO Oct 16-23. Adding leave buddy

Status: looking for/choosing proposal

**Comment by burczu** [comment] 2023-10-18 08:43
I've just reviewed all the proposals and I think all of them identified the root cause correctly. Also, proposed solutions are quite similar (filtering out `accountID === 0` in `getPersonalDetailsForAccountIDs`) and I think the way how we do it is an implementation detail.

That's why I think we should choose [the proposal](https://github.com/Expensify/App/issues/29453#issuecomment-1759759585) from @c3024, because they was the first.

🎀 👀 🎀 C+ reviewed

**Comment by burczu** [comment] 2023-10-18 09:40
@saranshbalyan-1234 Returning in `each` loop ends the loop?! Can you please provide the link to the documentation of underscore that explains that? From what I know, returning in the `each` callback does not break the loop, it acts like `continue` not `break`.

**Comment by sonialiap** [comment] 2023-10-23 18:49
Back from OOO. Thanks for pushing this along, Bartek!

**Comment by sonialiap** [comment] 2023-10-30 11:12
@c3024 fix + bonus = $750 - paid ✔️ 
@ayazhussain79 report = $50 - offer sent

**Comment by ayazhussain79** [comment] 2023-10-30 14:07
@sonialiap offer accepted, Thank you

**Comment by sonialiap** [comment] 2023-10-31 09:17
@burczu please complete the [checklist](https://github.com/Expensify/App/issues/29453#issuecomment-1774424597) :)

**Comment by burczu** [comment] 2023-10-31 13:28
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

* [ ]  [@burczu] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/20473
* [ ]  [@burczu] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/20473#discussion_r1377582526
* [ ]  [@burczu] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **didn't find**
* [ ]  [@burczu] Determine if we should create a regression test for this bug. **I don't think this issues needs any regression tests - the bug wasn't impactful and didn't break any important App flow.**
* [ ]  [@burczu] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
* [ ]  [@sonialiap] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sonialiap** [comment] 2023-11-03 09:06
@burczu I'm not seeing the conclusion for the last point on the checklist, do you think we should do a regression test for this?

**Comment by burczu** [comment] 2023-11-06 07:42
@sonialiap As I wrote in my previous comment: 

> I don't think this issues needs any regression tests - the bug wasn't impactful and didn't break any important App flow.

**Comment by sonialiap** [comment] 2023-11-06 09:32
Thanks!

**Closed by sonialiap** 2023-11-06 09:32 UTC
Labels: External, Daily, Awaiting Payment, Bug
