### ISSUE TITLE
[Violations] -"Review required" and RBR does not appear immediately for "Over limit" error

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#37013] opened 2024-02-21 13:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
issue found when executing #33969
**Version Number:** 1.4.43-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Turn on the Violations beta (or use an expensifail account)
2. Go to OldDot and open or create a Control policy
3. Enable violations for the workspace in Settings > [Workspace] > Expenses
4. Make Expense Violations: true
5. Make Max Expense Amount: $10
6. Make tags required for the policy
7. Go to Settings > [Workspace] > Tags
8. Enable "People must tag expenses"
9. Add a tag
10. Go to the policy page
11. In the JS console with the policy open do:
p = Policy.getCurrent();
p.policy.isPolicyExpenseChatEnabled = "true";
p.save();
12. Invite a new user to the policy
13. Sign into that new user account in New Dot
14. Go through the money request flow, choosing the policy you just created and create an Over the Limit IOU with $20 and tag included.
15. After the IOU has been created click on the IOU preview to go to the report page
16. Observe the IOU preview component
17. Click on the Preview component to open the details thread and go back to the report page
## Expected Result:
RBR should be present on the IOU preview with a "Review required" violation the first time user navigates to the report page

## Actual Result:
RBR and "Review required" violation show up the second time user navigates to the report page after going back from the transaction detail thread. (i.e it doesn't show up the first time.)

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/befeae1e-4925-4048-ba83-3eb40c946a5f

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5c874f3a22433b7</li>
        <li>Upwork Job ID: 1762193509418659840</li>
        <li>Last Price Increase: 2024-02-26</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cead22</details>

**Comment by Tony-MK** [comment] 2024-02-24 01:12
# Notes

This should be an internal issue because while testing on the main, I noticed the policy expense limit is not saved in the onyx.

Furthermore, the response from the `requestMoney` endpoint does not contain `overLimit` as part of the `transactionViolations`.

Hence, once the `openReport` endpoint is called, it responds with `overLimit` as part of the `transactionViolations`.

Therefore, this bug needs to be considered an offline case as well.

Below is a screenshot of a similar issue of the receipt amount limit violation displaying `undefined`, which may be solved in the PR.

![Screenshot](https://github.com/Expensify/App/assets/22982173/e6b5bda0-bcf9-45d0-b214-31d326a95408)

**Comment by zanyrenney** [comment] 2024-02-26 18:45
seems like this is related to:
https://github.com/Expensify/App/issues/32571
https://github.com/Expensify/App/pull/33969

these are both part of wave 9.

**Comment by cead22** [comment] 2024-02-26 19:10
> Furthermore, the response from the `requestMoney` endpoint does not contain `overLimit` as part of the `transactionViolations`.

Yes, I think the fix will be in the back end to make RequestMoney push violations to clients. This something @luacmartins noticed recently, and I thought the flows would always go through OpenReport so I hadn't created an issue.

Let's use this one for that and make it internal

**Comment by luacmartins** [comment] 2024-02-26 20:46
@cead22 do you have a link to where we push that Onyx update in `requestMoney`? I couldn't find it in the code. Also I just tested in dev and I didn't get the pusher update nor the value in the http response

Uploading Screen Recording 2024-02-26 at 12.12.01 PM.mov…

**Comment by Tony-MK** [comment] 2024-02-27 01:54
To clarify https://github.com/Expensify/App/issues/37013#issuecomment-1962196593.

Only the `overLimit` violation is not sent in the `requestMoney` response. 

However, the rest of the violations are sent in the response as expected.

![HTTP](https://github.com/Expensify/App/assets/22982173/94a2e28b-02fc-4163-bbb2-4b5f5ee4fb70)

**Comment by cead22** [comment] 2024-02-27 18:15
Looking again, I think after testing and seeing RBR on the report and money request previews, I **expected** to see some code pushing violations, and I think I confused `TransactionUtils::structureTransactionsForOnyx` with violations

**Comment by cead22** [comment] 2024-02-27 18:17
@Tony-MK in your last screenshot, if we were returning violation data, you'd see an entry like `{key: "transactionViolations_1234567890",...}`, which isn't in there

**Comment by zanyrenney** [comment] 2024-02-29 19:01
any update on further progress here @Tony-MK @cead22 ?

**Comment by zanyrenney** [comment] 2024-03-04 18:10
@Tony-MK please can you clarify what you need to move ahead here? Do you need more information from Carlos? Or are you working on an alternative solution with the feedback that he has already given you.

**Comment by Tony-MK** [comment] 2024-03-05 16:13
Hi @zanyrenney, I'm a contributor.

This issue is best solved from the backend, but I was trying to help out Carlos with debugging.
 
Nevertheless, it persists, and we should wait for Carlos's update.

Thank you

**Comment by cead22** [comment] 2024-03-06 03:30
I tested sending transaction violations in RequestMoney and that seems to fix the issue, so I'll submit a PR tomorrow or find a volunteer to help me with it since I'm working on other roadmap issues

**Comment by Tony-MK** [comment] 2024-03-06 18:59
> find a volunteer to help me with it since I'm working on other roadmap issues

Hi @cead22, would you still like a volunteer to help me with the PR?

**Comment by cead22** [comment] 2024-03-06 19:22
@Tony-MK the PR will be on the backend. I need to discuss one detail of how I'm thinking of solving this with the team before we submit a fix

**Comment by Tony-MK** [comment] 2024-03-06 19:33
My bad, I thought you required help with fixing the `Receipt required over undefined` error issue.

![Screenshot](https://github.com/Expensify/App/assets/22982173/e6b5bda0-bcf9-45d0-b214-31d326a95408)

**Comment by cead22** [comment] 2024-03-06 20:52
@Tony-MK no worries. I think that's a different issue, right? Is it reproducible?

**Comment by Tony-MK** [comment] 2024-03-06 21:43
Yes, @cead22, it is reproducible on the latest main. 

It is a different issue since the backend sends the value of `receiptRequired` in the  `openReport` response.

![Screenshot 2024-03-07 at 00 38 29](https://github.com/Expensify/App/assets/22982173/4b334269-093e-43b3-9d0c-d9fda53ca697)

**Comment by cead22** [comment] 2024-03-06 22:27
Ah yes, but I think that happens because the backend isn't sending `data: {formattedLimit: "$10.00"}`, and instead is sending null

**Comment by Tony-MK** [comment] 2024-03-07 20:46
After checking OD, that is true.

Thanks

**Comment by cead22** [comment] 2024-03-09 00:09
I created an issue for the **Receipt required over undefined** violation, and started a slack discussion to figure out the solution for RequestMoney not returning violations

**Comment by zanyrenney** [comment] 2024-03-11 12:06
Nice, sounds good @cead22

**Comment by cead22** [comment] 2024-03-12 21:27
PR submitted

**Comment by cead22** [comment] 2024-03-20 22:33
Melvin, you crazy! PR is on staging

**Comment by zanyrenney** [comment] 2024-03-21 21:21
Just a note to say, I am OOO now until April 2nd, reassigning BZ team member to help while I am OOO in case we need payments in that time. Thanks!

**Comment by laurenreidexpensify** [comment] 2024-03-25 14:18
@cead22 just to follow here - is https://github.com/Expensify/Web-Expensify/pull/41248 the PR for this? Looks like that is on prod now, but was internal review cos it's on Expensify/Web so we can remove @akinwale here, as no payment due for C+ review?

**Comment by cead22** [comment] 2024-03-25 21:50
Correct 👍

**Comment by JmillsExpensify** [comment] 2024-03-26 03:24
If this is on production, can't we also close this issue?

**Comment by cead22** [comment] 2024-03-26 03:43
Yup!

**Closed by cead22** 2024-03-26 03:43 UTC
Labels: Reviewing, Daily, Internal, Bug
