### ISSUE TITLE
[HOLD for payment 2024-08-01] [$250] Settings - A new user can navigate away from the onboarding modal using an URL

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#45260] opened 2024-07-11 12:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.6-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Found when executing PR :** https://github.com/Expensify/App/pull/44536
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Open the app
2. Log in with a new Gmail user
3. Open https://staging.new.expensify.com/settings/profile
URL "in New Expensify"
4. Tap on the "<" button to navigate back

## Expected Result:
The onboarding modal should be showing when opening a different URL until the onboarding is completed.

## Actual Result:
A new user can navigate away from the onboarding modal using an URL. The onboarding can't be skipped as its shown again when navigating back from the opened page.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/1dde4238-d698-4c36-a02b-568d6da006c8

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a6951dbdae386a31</li>
        <li>Upwork Job ID: 1812979942020839461</li>
        <li>Last Price Increase: 2024-07-15</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 103158696</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @strepanier03</details>

**Comment by izarutskaya** [comment] 2024-07-11 12:24
We think this issue might be related to the #collect project.

**Comment by strepanier03** [comment] 2024-07-15 22:37
Able to repro this using a Pixel 6 pro on Native.

**Comment by nkdengineer** [comment] 2024-07-16 08:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
A new user can navigate away from the onboarding modal using an URL. The onboarding can't be skipped as its shown again when navigating back from the opened page.

### What is the root cause of that problem?
We have a `useEffect` to navigate to the onboarding flow if it's not complete but this only triggers when `isLoadingApp` is changed and `isLoadingApp` is only changed after `OpenApp` API is called. So when we open the deep link and we already login, we navigate to the deep link page.

https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.tsx#L62
### What changes do you think we should make in order to solve the problem?
For the web, when we access via deep link the page is reloaded and the `useEffect` is triggered and the bug doesn't happen.

https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar/index.tsx#L62

For natives, we have the logic to listen to the deep link [here](https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/Expensify.tsx#L205-L207). We can navigate to the onboarding flow in the `openReportFromDeepLink` function if it's not completed here

```
if (isAuthenticated) {
    Welcome.isOnboardingFlowCompleted({onNotCompleted: () => Navigation.navigate(ROUTES.ONBOARDING_ROOT)});
    return;
}
```
https://github.com/Expensify/App/blob/fb9ce79f891ef932c60c36617162f5e988e3313d/src/libs/actions/Report.ts#L2598-L2599

### What alternative solutions did you explore? (Optional)
NA

### Result



https://github.com/user-attachments/assets/a92b54ea-016a-4ceb-a8d8-5f335d9dca3e

**Comment by strepanier03** [comment] 2024-08-01 21:51
### Payment Summary

- $250 @Ollyws via New Expensify manual request
- $250 @nkdengineer via Upwork (paid)

**Comment by strepanier03** [comment] 2024-08-01 21:52
Working on reg test gh now.

**Comment by JmillsExpensify** [comment] 2024-08-01 21:56
$250 approved for @Ollyws

**Comment by strepanier03** [comment] 2024-08-01 21:56
Thanks all, this is paid and reg test is done, closing out!

**Closed by strepanier03** 2024-08-01 21:56 UTC
Labels: External, Daily, Awaiting Payment, Bug
