### ISSUE TITLE
[$250] Thread – Group chat opens when leave thread and reopen it

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#47586] opened 2024-08-16 19:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4865736
**Email or phone of affected tester (no customers):** applausetester+jp_e_category_2@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in
3. Navigate to any group chat
4. Send a message in the group chat
5. Open context menu and click on Reply in thread
6. Send a comment in the thread
7. Click on the header and Leave the thread
8. Verify you are redirected to group chat
9. Click on Reply to reopen the thread

## Expected Result:
Thread opens

## Actual Result:
Thread appears for a moment and redirect to group chat

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f9a3af3c-7c8c-4f4d-8c3b-0fe05bf3aa9a

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ce5b7018d6f6dd8e</li>
        <li>Upwork Job ID: 1825335787602372137</li>
        <li>Last Price Increase: 2024-08-19</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-08-16 19:09
We think that this bug might be related to #vip-vsb

**Comment by IuliiaHerets** [comment] 2024-08-16 19:09
@jliexpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by jliexpensify** [comment] 2024-08-19 00:53
Still looks to be happening on v9.0.21-3

**Comment by nkdengineer** [comment] 2024-08-19 04:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Thread appears for a moment and redirect to group chat

### What is the root cause of that problem?
After we leave a group chat thread and open it again, `GetMissingOnyxMessages` is called and returns the data that sets the thread report as null (see the image below).


<img width="1511" alt="Screenshot 2024-08-19 at 11 36 36" src="https://github.com/user-attachments/assets/f082625c-b322-41a0-ae4b-ba330a2e6ea0">

Then because the report is empty and this thread is also a group chat,  `isRemovalExpectedForReportType` is `true` and we will navigate back to parent report [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/home/ReportScreen.tsx#L606-L611)
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/home/ReportScreen.tsx#L581-L583



### What changes do you think we should make in order to solve the problem?
We should use `isRootGroupChat` check here that also covers the `isDeprecatedGroupDM` case and exclude the case the thread is a group chat 

```
const isRemovalExpectedForReportType = 
     isEmpty(report) && 
     (ReportUtils.isMoneyRequest(prevReport) || ReportUtils.isMoneyRequestReport(prevReport) || ReportUtils.isPolicyExpenseChat(prevReport) || ReportUtils.isRootGroupChat(prevReport)); 
```
https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/pages/home/ReportScreen.tsx#L581-L583

https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/libs/ReportUtils.ts#L6944-L6946
### What alternative solutions did you explore? (Optional)
NA

**Comment by wildan-m** [comment] 2024-08-19 08:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Opening a group chat occurs when leaving and reopening a thread.

### What is the root cause of that problem?

There is inconsistencies between FE and BE, while [FE only hide the notification preferences](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/libs/actions/Report.ts#L2811). But BE set the report to null.

### What changes do you think we should make in order to solve the problem?

If we want to handle it in BE then BE should sent the below code instead of setting report to null.

```
{
                          notificationPreference: CONST.REPORT.NOTIFICATION_PREFERENCE.HIDDEN,
                          participants: {
                              [currentUserAccountID]: {
                                  hidden: true,
                              },
                          },
                      }
```

if we want to resolve it in FE, we can remove `|| isChatThread` [here] (https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/libs/actions/Report.ts#L2811) and [here](https://github.com/Expensify/App/blob/62722e8bc636f1be2e2c9e8e980aac93b76804c9/src/libs/actions/Report.ts#L2834).

### What alternative solutions did you explore? (Optional)
N/A

**Comment by srikarparsi** [comment] 2024-08-27 05:20
The [backend fix](https://github.com/Expensify/Auth/pull/12122) took care of this, closing this out.

**Closed by srikarparsi** 2024-08-27 05:20 UTC
Labels: Daily, Internal, Overdue, Bug
