### ISSUE TITLE
[HOLD for payment 2024-04-05] [$125] App crashes when click on Category while creating Money request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36622] opened 2024-02-15 18:56 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
User is an employee of Collect workspace on Old Dot

Steps:
1. As Admin navigate to Old Dot> Add new category (&)> Disable category (&)> Disable "People must categorize expenses"
2. As Employee Sign out and login again
3. As employee Navigate to chat> +> Money request> Manual> Add Amount> Next> Click on Category

## Expected Result:
Employee should be able to navigate to Category and select item

## Actual Result:
App crashes when click on Category while creating Money request

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/f633ecb7-0328-48ac-852f-8b262ef2e16c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c8a1b900f7b1723d</li>
        <li>Upwork Job ID: 1758203550933430272</li>
        <li>Last Price Increase: 2024-03-06</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-02-15 18:56
We (applause) think this might be related to #wave6-collect-submitters
cc @greg-schroeder

**Comment by FitseTLT** [comment] 2024-02-15 19:08
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crashes when click on Category while creating Money request

### What is the root cause of that problem?
We are trying to access `enabled` prop of undefined here
https://github.com/Expensify/App/blob/1c0d126ffb34e1fd103c9f6067b76af688638d47/src/libs/OptionsListUtils.ts#L848-L849
### What changes do you think we should make in order to solve the problem?

Change it to
```
                    enabled: categories[name]?.enabled ?? false,

```
### What alternative solutions did you explore? (Optional)

**Comment by DylanDylann** [comment] 2024-02-15 19:48
Can't reproduce now although I can reproduce 30 minutes ago

**Comment by joekaufmanexpensify** [comment] 2024-02-15 21:31
Not reproducible for me either.

**Comment by joekaufmanexpensify** [comment] 2024-02-15 21:33
Closing as this isn't consistently reproducible!

**Comment by joekaufmanexpensify** [comment] 2024-02-16 13:34
Sure, I'll try and reproduce with those steps today.

**Comment by joekaufmanexpensify** [comment] 2024-02-16 15:00
@MonilBhavsar I just tried to reproduce with the steps you listed above, and it worked fine for me. No crash or issues.

**Comment by FitseTLT** [comment] 2024-03-01 15:01
@MonilBhavsar @joekaufmanexpensify Today I had time to check it and it is still reproducible (I easily reproduced it twice using steps in the vid); here is a video that shows it. Basically as U can see from the Vid the step is same as the OP except may be before disabling "People must categorize expenses" I open the category page it works and I disable it and get back then it crashes with same root cause as in my proposal

https://github.com/Expensify/App/assets/38649957/d6afe38c-6980-4ba7-a149-f538da1c336c

**Comment by MonilBhavsar** [comment] 2024-03-04 12:08
Can you please mention reproduction steps in order and include a category name, if any specific category name caused the crash?

**Comment by FitseTLT** [comment] 2024-03-04 12:17
Precondition : 

- User is an employee of Collect workspace on Old Dot
- "People must categorize expenses" is enabled



1. create a category with the text `&` in OD and disable the category
2. In ND come and sign out and sign in 
3. On the workspace chat FAB -> Request -> enter amount -> Select category 
4. now disable in OD "People must categorize expenses" 
5. Now in ND refresh the page and On the workspace chat FAB -> Request -> enter amount -> Select category 
6. It will crash

**Comment by MonilBhavsar** [comment] 2024-03-04 12:29
@joekaufmanexpensify i think the theory is correct. Do you mind confirming please

**Comment by joekaufmanexpensify** [comment] 2024-03-04 15:16
Yes, will do!

**Comment by joekaufmanexpensify** [comment] 2024-03-05 15:36
I can reproduce this. However, I don't think this is worth our investment of resources to do anything about this right now. The set of steps required to reproduce this above are not ones an actual customer is ever likely to take IMO. Further, if you change the steps in various minor ways, it no longer becomes reproducible. This is the edgest of edge cases. I think let's see if anyone actually ever experiences this before doing anything. 

Further, we plan to bring category management over to NewDot soon, which I imagine will fix this?

**Comment by joekaufmanexpensify** [comment] 2024-03-05 15:36
LMK if anyone disagrees.

**Comment by joekaufmanexpensify** [comment] 2024-03-05 15:43
I'm just not convinced this will ever come up. @MonilBhavsar do you think this will be fixed anyway when we bring category management over to NewDot? If so, then IMO there's no reason to do something now for something unlikely to ever be experienced by anyone.

**Comment by MonilBhavsar** [comment] 2024-03-06 19:27
@joekaufmanexpensify given this a crash. I think we should fix it. Agree it is a edge case, we can adjust bounty to 125 and get this fixed

**Comment by joekaufmanexpensify** [comment] 2024-03-06 19:36
Sounds good. Defer to you on that.

**Comment by joekaufmanexpensify** [comment] 2024-03-06 19:37
Let us know your proposals!

**Comment by MonilBhavsar** [comment] 2024-03-08 05:08
@FitseTLT do you want to update proposal?

**Comment by MonilBhavsar** [comment] 2024-03-11 08:47
@alitoshmatov can you please review, thanks!

**Comment by alitoshmatov** [comment] 2024-03-12 09:27
Working on it

**Comment by alitoshmatov** [comment] 2024-03-13 14:40
It was pretty hard to reproduce but finally I managed to do it. 

@FitseTLT 's [proposal](https://github.com/Expensify/App/issues/36622#issuecomment-1947005762) does solve this issue. We can implement it.

C+ reviewed 🎀 👀 🎀

**Comment by MonilBhavsar** [comment] 2024-03-15 08:28
> Just to confirm, we are aware of following case where & is encoded into html form &amp;, right?

Yes https://github.com/Expensify/App/issues/36473

**Comment by MonilBhavsar** [comment] 2024-03-15 08:29
@FitseTLT @alitoshmatov let's try to safely access categories properties at other places too 🙏

**Comment by FitseTLT** [comment] 2024-03-18 09:37
PR wil be up in 2 days

**Comment by joekaufmanexpensify** [comment] 2024-03-18 19:26
Great. TY!

**Comment by joekaufmanexpensify** [comment] 2024-03-18 19:30
Adding this to collect, since categories are a collect feature.

**Comment by joekaufmanexpensify** [comment] 2024-03-19 22:15
@FitseTLT still on track for PR?

**Comment by joekaufmanexpensify** [comment] 2024-03-20 20:56
Pending confirmation on PR

**Comment by FitseTLT** [comment] 2024-03-20 20:57
Sorry for the delay PR will be ready for review tomorrow

**Comment by joekaufmanexpensify** [comment] 2024-03-21 15:14
All good. TY!

**Comment by joekaufmanexpensify** [comment] 2024-04-01 15:07
@alitoshmatov could you please handle checklist so we can prep to issue payment?

**Comment by joekaufmanexpensify** [comment] 2024-04-04 20:18
bump @alitoshmatov for when you have a sec

**Comment by alitoshmatov** [comment] 2024-04-04 20:26
- The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/32470
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/32470/files#r1552383402
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No need
- Determine if we should create a regression test for this bug. No need

**Comment by joekaufmanexpensify** [comment] 2024-04-08 15:23
Old upwork job had closed, so opened new one: https://www.upwork.com/jobs/~01b6e231738f508b43

**Comment by joekaufmanexpensify** [comment] 2024-04-08 15:24
@alitoshmatov offer sent for $125!

**Comment by alitoshmatov** [comment] 2024-04-08 15:38
Accepted

**Comment by FitseTLT** [comment] 2024-04-08 15:57
Accepted

**Comment by joekaufmanexpensify** [comment] 2024-04-08 16:02
@alitoshmatov $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-04-08 16:02
@FitseTLT $125 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-04-08 16:02
upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-04-08 16:02
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-04-08 16:02 UTC
Labels: Engineering, Daily, Internal, Awaiting Payment, Bug
