### ISSUE TITLE
[HOLD for payment 2024-07-22] [$250] Tag - App crashes when saving 0 as custom tag name

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43773] opened 2024-06-14 13:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4631162
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace settings > Tags
3. Click Settings > Custom tag name
4. Enter 0 and save it

## Expected Result:
App will not crash

## Actual Result:
App crashes when saving 0 as custom tag name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/cde0b3b5-8921-4c2f-b121-832e001b4c73

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01aa311cffaf18adc9</li>
        <li>Upwork Job ID: 1802720126377724186</li>
        <li>Last Price Increase: 2024-06-24</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Reviewer | 102869898</li>
<li>bernhardoj | Contributor | 102869900</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @danieldoglas</details>

**Comment by lanitochka17** [comment] 2024-06-14 13:44
@slafortune  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-14 13:44
We think that this bug might be related to #wave-collect - Release 1

**Comment by bernhardoj** [comment] 2024-06-14 14:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
App crash when trying to save tag name as 0.

### What is the root cause of that problem?
When we save the tag name as 0, the BE responds with an invalid error. If it fails, we set an errors object to the policy tag list collection.
https://github.com/Expensify/App/blob/f0b635585aa32d32ba395f23d009218f3abfe29e/src/libs/actions/Policy/Tag.ts#L557-L563

So, it becomes:
```
{
errors: {...},
TagName: {...},
}
```

Then, it crashes in this line of code
https://github.com/Expensify/App/blob/f0b635585aa32d32ba395f23d009218f3abfe29e/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L36

The code gets the values of the object and then extracts the `tags` property from them. `TagName` has the `tags` property, but `errors` doesn't have the `tags` property because it's not a tag.

### What changes do you think we should make in order to solve the problem?

If we see the offline with feedback here,
https://github.com/Expensify/App/blob/f0b635585aa32d32ba395f23d009218f3abfe29e/src/pages/workspace/tags/WorkspaceTagsSettingsPage.tsx#L76-L78

we can see that the component expects the error property to be added inside the tag object, just like what we did with the pendingAction.
https://github.com/Expensify/App/blob/f0b635585aa32d32ba395f23d009218f3abfe29e/src/libs/actions/Policy/Tag.ts#L538

So, we need to update the failure data to

```
[newName]: null,
[oldName]: {
    ...oldPolicyTags,
    errors: ErrorUtils.getMicroSecondOnyxError('workspace.tags.genericFailureMessage'),
},
```

Last thing we need to do is to clear the error when pressing the offline with feedback close (X) button.

**Comment by kpadmanabhan** [comment] 2024-06-14 15:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Naming or renaming policy tag list setting with name as '0' crashes the app with failure. 

### What is the root cause of that problem?
Error in console.
`src\pages\workspace\tags\WorkspaceTagsSettingsPage.tsx`
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at eval (WorkspaceTagsSettingsPage.tsx:35:1)
    at Array.flatMap (<anonymous>)
    at WorkspaceTagsSettingsPage (WorkspaceTagsSettingsPage.tsx:33:138)
    at renderWithHooks (react-dom.development.js:16175:18)
    at updateFunctionComponent (react-dom.development.js:20382:20)
    at beginWork (react-dom.development.js:22425:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
```

App calls backend API `RenamePolicyTaglist` with valid `oldName` property and `newName` property as '0'. Backend responds back with error.
```
{
    "code": 666,
    "jsonCode": 402,
    "type": "Expensify\\Error\\InvalidParameterError",
    "UUID": "4456F600-4114-4B54-A7BD-4C3431656E18",
    "message": "Invalid input parameter",
    "title": "",
    "data": [],
    "htmlMessage": "",
    "onyxData": [],
    "requestID": "893aeca77e751c99-AMS"
}
```

While processing the response after converting `policyTags` to flatMap, which expects tag names inside it (instead of generic error that comes back from API), the code fails to fetch tags.

```
var hasEnabledOptions = OptionsListUtils.hasEnabledOptions(Object.values(policyTags !== null && policyTags !== void 0 ? policyTags : {}).flatMap(function (_ref2) {
    var tags = _ref2.tags;
    return Object.values(tags);
  }));
```

Code expects property `tags` inside the response. This works fine in case of a successful response as there is `tags` property inside `tagsListData` . But in case of errors, though response code is HTTP 200, `tags` property is completely missing.
As the code always assumes the presence of `tags` property, this fails in case of errors.

### What changes do you think we should make in order to solve the problem?
Assuming that we always get a successful response is incorrect. Frontend code must be able to handle error responses in a graceful way. 

Suggest following approaches for this

1. Check that `tags` property is not `undefined`. If that is missing, fallback for error response and fetch and display appropriate error as a red error text under tagList setting name field, based on the error message returned from backend. Display options for error need UI/UX input.
2. Alternatively, accept only valid tag names from frontend using regex. Also as the field is pre-populated with value Tag, do not allow changing the pre-populated text, instead forcefully accept only appending to this value. Need product input on this.


### What alternative solutions did you explore? (Optional)
Backend to return `tags` as empty property in API response and add `error` as a different property, rather than replacing `tags` property.

**Comment by danieldoglas** [comment] 2024-06-18 12:32
Interesting, checking this on our side before assigning - I'm not sure if we should allow 0 as a tag name.

**Comment by danieldoglas** [comment] 2024-06-19 22:16
We should allow 0 on our side. I'm working on a fix for that.

**Comment by bernhardoj** [comment] 2024-06-20 03:18
@danieldoglas I think we can fix the FE first to handle the errors properly, then fix the BE to allow 0, otherwise, the app will crash again every time there is an edit tag error. What do you think?

**Comment by kpadmanabhan** [comment] 2024-06-24 17:41
@danieldoglas / @ZhenjaHorbach : is someone working on this on FE? Or can we consider [this proposal](https://github.com/Expensify/App/issues/43773#issuecomment-2168253372)?

**Comment by kpadmanabhan** [comment] 2024-06-25 10:57
@ZhenjaHorbach : I agree that [this](https://github.com/Expensify/App/issues/43773#issuecomment-2188519456). `failureData` for `renamePolicyTag` must be fixed. I belive that in addition to this there needs to be safe response handling done in frontend.

**Comment by danieldoglas** [comment] 2024-06-25 12:27
I agree we need to fix the front end to deal with this as well.

**Comment by bernhardoj** [comment] 2024-06-25 13:28
PR is ready

cc: @ZhenjaHorbach

**Comment by danieldoglas** [comment] 2024-07-08 11:17
Backend changes implemented, waiting to be merged/deployed

**Comment by danieldoglas** [comment] 2024-07-12 15:47
This is kind of done?

@slafortune not sure why it didn't create the comments, the app part it's already in production!

**Comment by slafortune** [comment] 2024-07-12 17:56
Thanks for the heads up @danieldoglas - so are we just in the 7 day holding period for regressions? Which would be 7/17

<img width="831" alt="image" src="https://github.com/user-attachments/assets/a2258489-1b2e-47d0-9ff9-47a634579daa">

**Comment by slafortune** [comment] 2024-07-18 18:11
@ZhenjaHorbach - C+ Role -  has been paid $250 via UpWorks
@bernhardoj - Contributor Role - is due $250 via NewDot

**Closed by slafortune** 2024-07-18 18:11 UTC
Labels: External, Weekly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-07-19 02:21
$250 approved for @bernhardoj
