### ISSUE TITLE
[$250] [HOLD for payment 2024-06-20] [HOLD for payment 2024-06-18] [Search v1] Expense with tag in Parent: Child formay shows Parent\: Child in the list

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43364] opened 2024-06-10 12:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.81-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
Precondition:
- Workspace has enabled Tags.
- Workspace has a tag in Parent: Child format.

1. Go to staging.new.expensify.com
2. Go to workspace chat.
3. Submit an expense with tag in Parent: Child format.
4. Go to Search.
5. Look for the expense created in Step 4.

## Expected Result:
The expense will show tag in Parent: Child format.

## Actual Result:
The expense shows tag in Parent\: Child format.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/e7752a75-2758-46b0-a8dd-e508a6538590

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @puneetlath</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0149bba73f155a9d6c</li>
        <li>Upwork Job ID: 1801702973512124343</li>
        <li>Last Price Increase: 2024-06-14</li>
    </ul>
</details>

**Comment by m-natarajan** [comment] 2024-06-10 12:59
@joekaufmanexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by luacmartins** [comment] 2024-06-10 14:38
I can take this one since it's related to Search.

**Comment by luacmartins** [comment] 2024-06-10 14:39
@bernhardoj are you available to work on the PR now?

**Comment by bernhardoj** [comment] 2024-06-10 15:10
@luacmartins yes, I'm available.

**Comment by luacmartins** [comment] 2024-06-10 15:20
Nice! It's yours

**Comment by bernhardoj** [comment] 2024-06-10 15:37
@luacmartins PR is ready

**Comment by luacmartins** [comment] 2024-06-10 16:01
Merged and being CPed. Thanks!

**Comment by kbecciv** [comment] 2024-06-10 16:33
Issue is fixed after CPed
![bandicam 2024-06-11 00-31-29-243 (1)](https://github.com/Expensify/App/assets/93399543/1e8b794b-0a1b-4884-bdf1-56d50252232c)

**Comment by luacmartins** [comment] 2024-06-11 15:02
@joekaufmanexpensify yea, we need to pay @bernhardoj for the fix

**Comment by joekaufmanexpensify** [comment] 2024-06-14 19:44
I'm about to go OOO until 2024-06-24, so adding an additional BZ assignee here while I'm gone to handle BZ checklist and payment. If this is still open, I'll take it back once I return!

**Comment by joekaufmanexpensify** [comment] 2024-06-14 19:46
@luacmartins / @bernhardoj do we need to complete BZ checklist for this?

**Comment by joekaufmanexpensify** [comment] 2024-06-14 19:49
Only payment here is $250 to @bernhardoj for PR via Upwork. Offer sent!

**Comment by joekaufmanexpensify** [comment] 2024-06-14 19:49
I'm about to go OOO until 2024-06-24, so adding an additional BZ assignee here to watch this while I'm gone. If this is still open, I'll take it back once I return!

**Comment by bernhardoj** [comment] 2024-06-15 02:14
I can help the checklist

The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/41102

The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/41102/files#r1640596740

A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A

Determine if we should create a regression test for this bug. Since the QA caught it, there is probably already a regression test. If not, then we can use the OP test.

**Comment by joekaufmanexpensify** [comment] 2024-06-24 14:45
Back from OOO. Going to work through next steps today!

**Comment by joekaufmanexpensify** [comment] 2024-06-24 19:49
Checklist is all set

**Comment by joekaufmanexpensify** [comment] 2024-06-24 19:50
@bernhardoj $250 sent and contract ended!

**Comment by joekaufmanexpensify** [comment] 2024-06-24 19:50
Upwork job closed.

**Comment by joekaufmanexpensify** [comment] 2024-06-24 19:50
All set. Thanks everyone!

**Closed by joekaufmanexpensify** 2024-06-24 19:50 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
