### ISSUE TITLE
[HOLD for payment 2023-10-27] [$250] Migrate index.js to function component

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#16145] opened 2023-03-20 08:34 UTC
### Filenames
- [ ] [src/components/EmojiPicker/EmojiPickerMenu/index.js](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js)
    - **type:** `React.Component`
    - **has state values:** true
    - **has refs:** true
    - **has context:** false
    - **lifecycle methods:** `componentDidMount`,`componentWillUnmount`

### Task
- We currently have some class components in our codebase that we would like to refactor to a function component.
- Here's a link with some general advice on how to refactor a class component to a function component: https://react.dev/reference/react/Component#alternatives
- If you need additional guidance, please ask in [#expensify-open-source](https://expensify.slack.com/archives/C01GTK53T8Q)
- Test for any regressions and verify that there are no breaking changes

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eb40815378adee79</li>
        <li>Upwork Job ID: 1710087370262638592</li>
        <li>Last Price Increase: 2023-10-06</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @johncschuster</details>

**Comment by muxriddinmuqimov77** [comment] 2023-06-06 06:52
I'd like to work on this issue

**Comment by s-alves10** [comment] 2023-06-06 10:25
I'd love to work on this.

**Comment by vdem0115** [comment] 2023-07-07 13:33
I'd like to work on this issue

**Comment by ashuvssut** [comment] 2023-10-06 03:32
I will refactor this component like following:

1. Determine which logics can be separated out of `EmojiPickerMenu` component into separate components
2. Determine which logics could be refactored out of EmojiPickerMenu into separate customs hooks. (This is done only to separate logics which are very closely related into that separate custom hook.

**Comment by ashuvssut** [comment] 2023-10-06 03:41
Contributor details
Your Expensify account email: ashuvssut23@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0130db910fd00b9f05

**Comment by aim-salam** [comment] 2023-10-06 04:24
How do I know the issue is still open?

**Comment by kamicodaxe** [comment] 2023-10-06 04:58
Contributor details
Your Expensify account email: ruvice.kami@gmail.com
Upwork Profile Link: ruvice.kami@gmail.com

**Comment by vadymbokatov** [comment] 2023-10-06 05:03
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
this [component](src/pages/ReimbursementAccount/ReimbursementAccountPage.js)  is class based
### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
we should migrate to functional components.

### What alternative solutions did you explore? (Optional)

**Comment by olchet** [comment] 2023-10-06 09:54
Contributor details
Your Expensify account email: chetkum@protonmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01ca3117d2b055a0eb

**Comment by maxconnectAbhi** [comment] 2023-10-08 13:13
# Proposal

## Please re-state the problem that we are trying to solve in this issue
Migrate [index.js](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) to function component

## What is the root cause of that problem?
[index.js](https://github.com/Expensify/App/blob/main/src/components/EmojiPicker/EmojiPickerMenu/index.js) is a class component extends React.Component

## What changes do you think we should make in order to solve the problem?
1. Replace `state` with `useState` hook
2. Replace `componentDidMount`, `componentDidUpdate` & `componentWillUnmount` with `useEffect` hook
3. Replace `refs` with `useRef`
4. Remove `this` keyword from file.

## What alternative solutions did you explore? (Optional)
Update .js to .tsx

**Comment by marcaaron** [comment] 2023-10-10 18:31
@ashuvssut I like your proposal, but it's doing too much.

❌  Refactoring into separate components

No need to do this. We are just focused on the conversion to a function component

❌ Refactoring into Custom Hooks

Sounds like a premature optimization.

❌  Use TypeScript for props types and function parameter type(Also this renames file extension:-*.js into *.tsx)

We have a separate migration happening related to TS so this is more than we are asking for. Do not do it.

The rest sounds ok!

**Comment by marcaaron** [comment] 2023-10-10 18:34
>@Santhosh-Sellavel Please request via NewDot manual requests for the Reviewer role ($250)

I ended up reviewing this one. But could use your help on the PR Review.

**Comment by ashuvssut** [comment] 2023-10-11 02:41
The [PR](https://github.com/Expensify/App/pull/29241) is ready

**Comment by ashuvssut** [comment] 2023-10-30 07:43
Hi @Santhosh-Sellavel 

I havent received my payment for this contribution. Who should I reach out to?

Also, I saw in upwork that I haven't been hired yet for [the job](https://www.upwork.com/jobs/~01eb40815378adee79)

**Comment by ashuvssut** [comment] 2023-10-31 15:46
Hi @Santhosh-Sellavel @marcaaron 

I havent received my payment for this contribution. Who should I reach out to?

Also, I saw in upwork that I haven't been hired yet for the [job](https://www.upwork.com/jobs/~01eb40815378adee79)

I have a fully verified [upwork account](https://www.upwork.com/freelancers/~0130db910fd00b9f05)

**Comment by Santhosh-Sellavel** [comment] 2023-10-31 17:18
@marcaaron please assign a BZ here, thanks!

**Comment by ashuvssut** [comment] 2023-11-06 00:08
@johncschuster @marcaaron any update on the [payment issue?](https://github.com/Expensify/App/issues/16145#issuecomment-1787487827)

**Comment by ashuvssut** [comment] 2023-11-06 21:18
@johncschuster seems like [the Job](https://www.upwork.com/jobs/~01eb40815378adee79) has expired

![image](https://github.com/Expensify/App/assets/60546840/ee3d7d51-43d5-4f61-bda8-5aeb0a52e083)

**Comment by Santhosh-Sellavel** [comment] 2023-11-07 17:45
@johncschuster Bump for the above, also please leave a payment summary message!

**Comment by johncschuster** [comment] 2023-11-07 21:18
Thanks for the bump on the expired job! I'll get a manual one spun up.

**Comment by johncschuster** [comment] 2023-11-07 21:20
@ashuvssut can you please comment on the issue above so I can assign it to you? That should create the Upwork job.

**Comment by johncschuster** [comment] 2023-11-07 21:21
## Payment Summary:
@ashuvssut requires payment (will be paid via Upwork [here](https://github.com/Expensify/App/issues/31032)) - $250
@Santhosh-Sellavel does not require payment (Eligible for Manual Requests) - $250

**Closed** 2023-11-07 21:22 UTC
Labels: External, Engineering, Daily, Improvement, Awaiting Payment
