### ISSUE TITLE
[$250] Categorize - Email address can be selected which leads to infinite loading in Category page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#47583] opened 2024-08-16 18:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.21-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+kh050806@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to self DM
3. Click + > Track expense > Manual
4. Submit a track manual expense
5. Click Categorize it
6. Enter any email and select the user from the result

## Expected Result:
App should not show result for email address because categorizing is only for workspaces

## Actual Result:
App shows result for email address and Category page loads infinitely after selecting the user

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/a024c2ee-7d7e-4348-8af6-876ebdadde05

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fdcfeaf864ee2ecb</li>
        <li>Upwork Job ID: 1824591298084501941</li>
        <li>Last Price Increase: 2024-08-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @eVoloshchak</details>

**Comment by lanitochka17** [comment] 2024-08-16 18:24
@twisterdotcom  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-08-16 18:25
We think that this bug might be related to #vip-vsp

**Comment by FitseTLT** [comment] 2024-08-16 18:40
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 Email address can be selected which leads to infinite loading in Category page

### What is the root cause of that problem?
We are not passing `excludeUnknownUsers` to `OptionsListUtils.getFilteredOptions` when `action === CONST.IOU.ACTION.CATEGORIZE`
https://github.com/Expensify/App/blob/d4d5a2586910ff46147219ee3e98bb3e936f8037/src/pages/iou/request/MoneyRequestParticipantsSelector.tsx#L95-L96
### What changes do you think we should make in order to solve the problem?

We should pass `excludeUnknownUsers` to `OptionsListUtils.getFilteredOptions` when `action === CONST.IOU.ACTION.CATEGORIZE`
### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment] 2024-08-16 23:37
Yeah weird bug.

**Comment by visotecq** [comment] 2024-08-17 14:43
Proposal

As described issue, we landed to the root cause of the infinite loading on Category due to following -

1) Entering E-mail without assigned to any Workspace , makes infinite Loading on the Category Page.

Solution -

1) On Entering E-mail if no Workspace pops up in List then on Clicking E-mail ,  create a New Workspace with that E-mail then Navigate to Category .

**Comment by Amoralchik** [comment] 2024-08-18 00:07
@visotecq 
Please make sure you've read [Contributing to Expensify](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) and once you've understood everything, please format your [comment](https://github.com/Expensify/App/issues/47583#issuecomment-2294879261) according to the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) if you're interested in fixing this issue; otherwise, it won't be considered for review.

Additionally, to pass the bot verification, you need to submit a separate message rather than editing an existing one.

**Comment by twisterdotcom** [comment] 2024-08-20 22:00
@eVoloshchak we still waiting on a good proposal here?

**Comment by eVoloshchak** [comment] 2024-08-21 18:04
@FitseTLT's [proposal](https://github.com/Expensify/App/issues/47583#issuecomment-2293982814) looks good to me!

> Additionally we need to avoid invalid email or invalid phone header message for categorize by updating getHeaderMessage to have a new param shouldAvoidContactMessage (we will pass as true for action type categorize) and avoid invalid phone/email message inside getHeaderMessage

We can work out the specifics of this on the PR stage, but I think we could use [getHeaderMessageForNonUserList](https://github.com/Expensify/App/blob/6bd0782d3f1b88c47e493cbfedb31bc2c9ad5c20/src/libs/OptionsListUtils.ts#L2293) for this

🎀👀🎀 C+ reviewed!

**Comment by thienlnam** [comment] 2024-08-23 13:03
Yeah, I agree with that update

**Comment by twisterdotcom** [comment] 2024-11-15 10:52
Yeah, we should. Looks like absolutely no automation occurred here. Okay, let me figure out the payment summary.

**Closed** 2024-11-15 13:04 UTC
Labels: Reviewing, External, Monthly, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2024-11-21 10:59
$250 approved for @eVoloshchak
