### ISSUE TITLE
[HOLD for payment 2023-10-02] [$1000]  image loads on reesize window

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26071] opened 2023-08-28 11:48 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any image
3. resize window
## Expected Result: 
should not show loader on resize window
## Actual Result: 
loader appears on resize window

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6fa6350c-5d1d-4bf7-9c89-2693a2272ed6

https://github.com/Expensify/App/assets/43996225/f79f7775-6af1-40e5-9258-39ca83ac4aed

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692339507173639

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0123a04480c44d1baf</li>
        <li>Upwork Job ID: 1696572921150214144</li>
        <li>Last Price Increase: 2023-08-29</li>
<li>Automatic offers: </li>
<ul>
<li>gadhiyamanan | Reporter | 26456730</li>
</ul></li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-08-28 15:26
I don't understand. Why is the fact that it has to load when resizing a bug?

**Comment by puneetlath** [comment] 2023-08-28 15:48
I don't think this is a bug as I mentioned [here](https://github.com/Expensify/App/issues/26071#issuecomment-1695897758), so I'm going to go ahead and close. But feel free to comment if you disagree and we can keep discussing.

**Comment by tamdao** [comment] 2023-08-29 00:29
@puneetlath It's bug. You can take a look the code, it should only add style and not mount/unmount the component that mean kill the component and create new one. So, if you fix mount/unmount the component, the loading issue will be resolved because the image already loaded.

And another thing, because the logic mount/unmount the component it causes crash application like this

https://github.com/Expensify/App/assets/3086267/b73930ad-00cc-4aac-8b56-76c7f2c5530e

**Comment by puneetlath** [comment] 2023-08-29 17:15
Ok interesting. How do you suggest we solve it?

**Comment by saalimzafar** [comment] 2023-08-29 17:37
I guess the number of bugs reported on daily basis are too much to be thoroughly checked by the test engineers. 
I agree with you that it's not really a bug at least not in resizing but definitely in the whole process.
See the irony while you are wondering if it's a bug or not but the bug bounty gets decided.
And I have experienced that some test engineer who are assigned to create issues are not on same platform. Someone will say this is by design, other will consider it an issue.
I would request someone who is accountable to check test engineers knowledge about the tasks they are assigned and there's nothing wrong in being updated!!

**Comment by tamdao** [comment] 2023-08-30 00:37
@puneetlath @saalimzafar I found the root cause of the crash issue I mention above. This issue cause by `withWindowDimensions` function

https://github.com/Expensify/App/blob/2d29b58c38af36597f96934b170d8d10cc08d2c7/src/components/withWindowDimensions.js#L44-L62

In this logic you are listener the dimension change event and this event will call when the dimension change and re-render component and cause the issue (`Maximum update depth`) when user re-size window multiple time.

### What alternative solutions did you explore?
Update the logic to use lodash debounce like this

```js
const onDimensionChange = useCallback((newDimensions) => {
    const {window} = newDimensions;

    setWindowDimension({
        windowHeight: window.height,
        windowWidth: window.width,
    });
}, []);

const onDimensionChangeDebounce = useCallback(lodashDebounce(onDimensionChange, 300), []);

useEffect(() => {
    const dimensionsEventListener = Dimensions.addEventListener('change', onDimensionChangeDebounce);

    return () => {
        if (!dimensionsEventListener) {
            return;
        }
        dimensionsEventListener.remove();
    };
}, []);
```
I have tested and no longer see the crash issue

**Comment by tamdao** [comment] 2023-08-30 20:19
@puneetlath @saalimzafar I have updated my proposal to fix 2 issue
## Proposal
[Updated](https://github.com/Expensify/App/issues/26071#issuecomment-1695924915)

**Comment by kanno927** [comment] 2023-08-31 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
image loads on resize window

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/AttachmentModal.js#L362-L369
The AttachmentView component re-renders when the AttachmentModal size changes.
After re-rendering the AttachmentImageView as above, re-rendering the ImageView.
When the ImageView re-renders, a loading spinner is displayed while loading the image with its URL.
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ImageView/index.js#L32
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ImageView/index.js#L89-L99
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ImageView/index.js#L267

### What changes do you think we should make in order to solve the problem?
I think we should include a prop telling whether to show the loading spinner or not. To implement it, I change the ImageView to:
- Old
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ImageView/index.js#L31
https://github.com/Expensify/App/blob/c20c3870ee46d6788de554be27706e9898638904/src/components/ImageView/index.js#L267C13-L267C106
- New

```js
    function ImageView({isAuthTokenRequired, url, fileName, shouldShowSpinner})
    
    {isLoading && shouldShowSpinner && <FullscreenLoadingIndicator style={[styles.opacity1, styles.bgTransparent]} />}
```

**Comment by mananjadhav** [comment] 2023-09-01 13:51
@tamdao's [proposal](https://github.com/Expensify/App/issues/26071#issuecomment-1695924915) looks good. I am a bit concerned on debounce for withWindowsDimensions. I am wondering if this would cause any issue due to any incorrect dimenions.

**Comment by mananjadhav** [comment] 2023-09-01 13:51
🎀 👀 🎀 C+ reviewed.

**Comment by tamdao** [comment] 2023-09-01 14:59
@mananjadhav I have tested it and I see it works well. Because, the [debounce function](https://lodash.com/docs/4.17.15#debounce) just reduce number of call the resize function to re-render component when user resize fast

**Comment by tamdao** [comment] 2023-09-02 00:24
@mananjadhav @puneetlath PR is ready https://github.com/Expensify/App/pull/26543. Please help me review it. Thanks ❤️

**Comment by puneetlath** [comment] 2023-09-29 01:48
@mananjadhav friendly reminder on the checklist so we can pay this out in a couple days. Thanks!

**Comment by puneetlath** [comment] 2023-10-02 06:01
@mananjadhav another friendly bump on the checklist so that we can pay.

**Comment by gadhiyamanan** [comment] 2023-10-02 06:04
@puneetlath it is eligible for $250 for reporting bonus because it was logged before 30 Aug

![Screenshot 2023-10-02 at 11 33 18 AM](https://github.com/Expensify/App/assets/54790231/dfb232e9-68d7-4045-897b-686cbc408c35)

**Comment by puneetlath** [comment] 2023-10-02 16:01
Yes, I agree with you on that.

**Comment by tamdao** [comment] 2023-10-02 20:32
@puneetlath Accepted. Thanks

**Comment by puneetlath** [comment] 2023-10-03 04:03
Ok great. Just waiting for you to create a NewDot request @mananjadhav. Then we can close.

**Comment by mananjadhav** [comment] 2023-10-04 19:58
@puneetlath I've created the request, we can close this one out.

**Comment by puneetlath** [comment] 2023-10-05 12:23
Great, thanks everyone!

**Closed** 2023-10-05 12:23 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-10-05 20:58
$1,000 payment approved for @mananjadhav based on BZ summary.
