### ISSUE TITLE
[$500] Web - Payments - "default" option appears even if there is only one bank account

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32996] opened 2023-12-13 18:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.12.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Settings > Wallet
2. Delete all bank accounts if already exists
3. Add any bank account
4. Click on newly added bank account

## Expected Result:
Should show only delete option

## Actual Result:
Default and delete both option appears and after refresh it will show only delete option

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ca1a7680-1ca1-4ec8-bb2e-60a2f516e35e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d7b8a45ad9499a24</li>
        <li>Upwork Job ID: 1735007023728451584</li>
        <li>Last Price Increase: 2023-12-27</li>
    </ul>
</details>

**Comment by allstarsmen** [comment] 2023-12-15 09:26
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Web - Payments - "default" option appears even if there is only one bank account
 
### What is the root cause of that problem?
When adding the new bank account, its data is missing the property "isDefault". This leads to the button "Make default payment method" appearing.

The reason why the button "Make default payment method" disappears after reloading the Wallet page is the "PaymentMethods.openWalletPage()" returns the "bankAccountList" from the server and on the server they automatically add "isDefault:true" to the first bank account (if the list has only one bank account).
 
### What changes do you think we should make in order to solve the problem?

In [here](https://github.com/Expensify/App/blob/e81ed8f4c548d0c1675a6d696772a914d115c2b1/src/pages/settings/Wallet/WalletPage/WalletPage.js#L260C2-L262C12). We add **bankAccountList** as the dependency of the **useEffect**, so when the **bankAccountList** gets updated, we will get the new data from the server.

The final code will look like this:

![Screenshot 2023-12-15 at 15 46 42](https://github.com/Expensify/App/assets/497313/ebb13656-e9c4-4627-ba3d-f075b8ec7cb2)

### Result

https://github.com/Expensify/App/assets/497313/1cef2dde-f90f-4279-8d04-6548bb9e57a1

### What alternative solutions did you explore? (Optional)
No

**Comment by allstarsmen** [comment] 2023-12-18 08:08
I have updated [my proposal](https://github.com/Expensify/App/issues/32996#issuecomment-1857551717).

**Comment by JmillsExpensify** [comment] 2024-01-03 04:28
There you go @parasharrajat!

**Comment by blimpich** [comment] 2024-01-03 17:37
Acknowledging this. @parasharrajat I currently have very little bandwidth to investigate this. I can try to get to this when I am cleared up but I won't be able to look into this soon fyi.

**Comment by blimpich** [comment] 2024-01-11 21:10
Alright I looked into this. I like @allstarsmen's solution where we just add `bankAccountList` to the dependency list. I initially thought this should be a backend fix but after looking into this I think it's a better idea to fix it in the frontend.

There's complicated billing logic related to how default payments work that I don't want to touch, and in order to do this fix in the backend _correctly_ I would need to actually initiate more calls in the php layer, or make c++ layer needlessly more complicated for when we add a bank account. We are already getting the correct data from the backend when `bankAccountList` gets updated, and this costs us 0 new calls to the backend. So I think it would be a much safer and efficient move to just add that dependency and have the app smartly re-render.

@parasharrajat if you're okay with this then I think we should assign to @allstarsmen.

**Comment by blimpich** [comment] 2024-01-12 19:43
I will take a look again today, I admittedly didn't try out all solutions posted here locally, I simply saw that @allstarsmen's proposal worked when I tried it out.

**Comment by blimpich** [comment] 2024-01-13 00:47
I see I misunderstood the `useEffect` and how it would cause more calls to the backend. My bad. @tienifr your solution would work but the backend should be the ultimate source of truth so while we can deduce what should be the default payment on the frontend given enough evidence, I lean towards a solution that relies on `isDefault` being delivered to us from the backend.

I just spent some time today and found a way I think to do this in the backend. I'll pick it up.

**Comment by blimpich** [comment] 2024-01-17 17:18
Not overdue. I was OOO monday and then had to take a sick day yesterday. PR is out and received feedback. Will try to get to this today.

**Comment by blimpich** [comment] 2024-01-18 18:26
Internal PR was merged and just finished deploying.

**Closed** 2024-01-18 18:27 UTC
Labels: Engineering, Daily, Internal, Bug
