### ISSUE TITLE
[HOLD #31097 ] Chat - User taken to concierge chat page when start chat with same user from 2nd time onwards

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31216] opened 2023-11-10 22:11 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.98-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com
2. Tap '+' icon >> Start chat option
3. Enter email address & tap on the result displayed (Note: User taken to correct chat history page)
4. Tap back button to go back to LHN
5. Tap '+' icon >> Start chat option
6. Enter same email address used in step 3 & tap on the result displayed

## Expected Result:
User should be taken to correct user's conversation history page

## Actual Result:
User taken to concierge chat page when start chat with same user from 2nd time onwards
Note : Issue happens when start chat with a new non-existing account & users with previous chat history (2 different videos attached)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/f872f94d-597b-48c1-93dc-f43829bc9a07

https://github.com/Expensify/App/assets/78819774/6324b981-73e3-48d1-854b-de9f726e39db

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01ec45a3e6b8c6cadc</li>
        <li>Upwork Job ID: 1723101218860847104</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Contributor | 28105216</li>
</ul></li>
    </ul>
</details>

**Comment by mallenexpensify** [comment] 2023-11-10 23:04
Was able to reproduce, bizarre

**Comment by Tony-MK** [comment] 2023-11-11 05:14
While solving this bug, I checked for duplicates and found https://github.com/Expensify/App/issues/30062. I submitted a proposal on the other issue because I tested my prospal on it and it worked. Can please someone check if it is a duplicate?

**Comment by Tony-MK** [comment] 2023-11-11 05:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Secondary login chat after redirecting to primary login -redirects user to Concierge chat

### What is the root cause of that problem?

The `ReportScreen` has to re-render a minimum of two times because of `firstRenderRef`. Read the two snippets below from the [NavigationRoot.js](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/libs/Navigation/NavigationRoot.js) and [ReportScreen.js](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L301-L305) files to further illustrate the effects of the width of the screen.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/libs/Navigation/NavigationRoot.js#L62-L74

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L301-L305

Devices with large screen widths re-render one additional time, which allows `report.reportID` to become present, thus being able to produce the expected result. Here is a snippet to explain the possibilities of `report.reportID` being unavailable.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L238-L241

Finally, the root cause of the problem is that, in this specific case, devices with small screen widths only re-render twice because `report.reportID` is not present. This will make the logic below navigate the Concierge chat because, in this situation, `prevReport.parentReportID` doesn't have a value.

https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L307-L331

### What changes do you think we should make in order to solve the problem?

To produce the expected result accurately, we should try to re-render the page for small devices so they mimic the control flow of the larger devices. Therefore, adding an additional condition in this [`useEffect`](https://github.com/Expensify/App/blob/fcee2073f096ad60dd9f30c536342de7d3893282/src/pages/home/ReportScreen.js#L300) hook to force the function to run one more time for small devices should solve the problem. This will ensure that `report.reportID` is present to allow the fragile logic in the hook to perform as intended without changing it.

**Comment by getusha** [comment] 2023-11-13 16:43
@robertKozik I think we should hold this for https://github.com/Expensify/App/pull/31097 since we're likely to change some [parts](https://github.com/Expensify/App/pull/31097#issuecomment-1808502779) that relate to this issue.

**Comment by robertKozik** [comment] 2023-11-13 16:47
Thanks for heads up @getusha. @mallenexpensify can we put this issue until #31097 would be merged, per @getusha comment

**Comment by mallenexpensify** [comment] 2023-11-13 19:51
Thanks @getusha , put on hold pending the below, removed `Help Wanted` label too
- https://github.com/Expensify/App/pull/31097

**Comment by mallenexpensify** [comment] 2023-11-14 22:07
Yup!  Thanks @tienifr , not sure how that happened (it's wayyy more likely I forget to close an issue vs prematurely doing so)

**Comment by mallenexpensify** [comment] 2023-11-21 23:31
The issue this is held on is held on another issue, so it might be a bit, bumping to `Weekly` 
https://github.com/Expensify/App/issues/30868

**Comment by mallenexpensify** [comment] 2023-12-05 23:05
Still double held!

**Comment by mallenexpensify** [comment] 2023-12-20 01:21
Making a monthly cuz it's double held, this is the one that needs fixing first
- https://github.com/Expensify/App/pull/31424
then
- https://github.com/Expensify/App/pull/31097

**Comment by s77rt** [comment] 2024-01-16 23:59
Will take this as C+
@mallenexpensify Please assign me here

**Comment by mallenexpensify** [comment] 2024-01-17 02:33
Done @s77rt

**Comment by s77rt** [comment] 2024-02-05 23:13
The linked PRs are merged. The issue is no longer reproducible. We can close this cc @mallenexpensify

**Comment by mallenexpensify** [comment] 2024-02-06 23:12
Thanks @s77rt !

**Closed by mallenexpensify** 2024-02-06 23:12 UTC
Labels: External, Monthly, Bug
