### ISSUE TITLE
[HOLD for payment 2023-08-10] [$1000] Mweb - "Deleted message" chat appears in chat list for pinned deleted threads

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22950] opened 2023-07-15 18:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to staging new dot
2. Go to any chat and long press on any message within the chat
3. Click on reply in thread and send a message in thread
4. Pin the thread using the pin icon at top right corner
5. Now delete the parent message in the thread
6. Go back to parent message and click on thread
7. Now delete the child message in the thread
8. Go back to chat and observe the thread has been removed
9. Go to chat list and observe that the deleted thread can be found pinned as "Deleted message" chat

## Expected Result:
The deleted thread should also be removed

## Actual Result:
The deleted thread remains in the chat list even after parent and child messages are both deleted

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.41-1
**Reproducible in staging?:** y
**Reproducible in production?:**  y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/c1785bd6-2c66-404f-a63c-08112ea47bb9

https://github.com/Expensify/App/assets/93399543/fe96eaa4-e0fd-4b15-889b-c2dd726af8c3

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689361647727409

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01259a3effbfb36398</li>
        <li>Upwork Job ID: 1682395479803457536</li>
        2023-07-21<li>Automatic offers: </li>
<ul>
<li> |  | 0</li>
<li>hoangzinh | Contributor | 25765217</li>
<li>sofoniasN | Reporter | 25765220</li>
</ul></li>
    </ul>
</details>

**Comment by alexpensify** [comment] 2023-07-17 20:12
I was assigned over the weekend-- I will review it soon.

**Comment by alexpensify** [comment] 2023-07-19 21:56
@fedirjh and @MonilBhavsar - Could I get feedback here? I see that @hungvu193 worked on the fix for https://github.com/Expensify/App/issues/21103. That issue was focused on web. To confirm, that fix does not take into account Mweb say for Chrome on Android? I'm trying to confirm this one isn't a dupe before assigning the `external` label. Thanks!

**Comment by alexpensify** [comment] 2023-07-20 20:46
@fedirjh - thank you for putting me in a better direction! I'll wait for @dangrous or @mananjadhav feedback before assigning the `external` label.

**Comment by dangrous** [comment] 2023-07-21 14:12
> @alexpensify This issue doesn’t looks related to the PR @hungvu193 worked on. But I think this is a missed case from #21508 , cc @dangrous or @mananjadhav could you please add any feedbacks ?
> 
> * [If a deleted parent doesn't have a thread anymore, hide it #22690](https://github.com/Expensify/App/pull/22690)

Yep, I think this is a case we didn't think about when we changed the expected behavior in that issue. Not specifically a regression since I'm guessing this behavior would have happened before the change too. Should be a pretty easy fix though!

**Comment by alexpensify** [comment] 2023-07-21 14:22
Thank you @dangrous for the review. I'm going to mark this one as `external` to kick off the party and get it moving.

**Comment by alexpensify** [comment] 2023-07-21 19:44
@rushatgabhane - when you get a chance, please review the proposals. Thank you!

**Comment by alexpensify** [comment] 2023-07-23 16:10
No update, waiting on the proposals to be reviewed here.

**Comment by rushatgabhane** [comment] 2023-07-25 18:47
Umm, I'm thinking out loud about the expected behavior.
A report (pinned / unpinned) shouldn't be shown in LHN if it has no messages.

**Comment by rushatgabhane** [comment] 2023-07-25 18:55
> We can move the condition in those line

@hoangzinh sorry your proposal isn't clear to me. Instead of talking about what code to move where, could you please explain in simple words your proposed changes? Thanks

**Comment by rushatgabhane** [comment] 2023-07-25 22:50
> hide report thread in LHN if it doesn't have any comments regardless its pinned status

perfect, thanks!

**Comment by rushatgabhane** [comment] 2023-07-25 22:51
C+ reviewed https://github.com/Expensify/App/issues/22950#issuecomment-1645793420

🎀 👀 🎀

**Comment by mountiny** [comment] 2023-07-26 14:17
Thanks @hoangzinh assigned

**Comment by alexpensify** [comment] 2023-07-28 20:54
Thank you @hoangzinh for the update!

**Comment by alexpensify** [comment] 2023-08-01 00:36
@rushatgabhane - the PR is ready for review. If you can complete it, please reply. If no reply, tomorrow, I will be asking in the C+ room for someone to step in and reassign. Thank you!

**Comment by alexpensify** [comment] 2023-08-01 21:48
The PR was reviewed and approved! We are back on track. Thank you!

**Comment by alexpensify** [comment] 2023-08-05 00:22
I've confirmed that the hires are in Upwork and will complete the payment summary next as we get closer to the payment date. 

@rushatgabhane - when you get a chance, can you please complete the checklist before August 10? Thanks!

**Comment by alexpensify** [comment] 2023-08-08 22:00
@rushatgabhane - bumping again, we are approaching the pay period. Please complete the checklist to avoid payment delays. Thanks!

**Comment by rushatgabhane** [comment] 2023-08-10 10:05
WIP ⚠️ 

1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by alexpensify** [comment] 2023-08-10 23:11
Here is the payment summary: 

-  External issue reporter - @SofoniasN $250
-  Contributor that fixed the issue @hoangzinh $1000
-  Contributor+ that helped on the issue and/or PR @rushatgabhane $1000

Upwork Job: https://www.upwork.com/jobs/~01259a3effbfb36398

*If applicable, the bonuses will be applied on the final payment 

Extra Notes regarding payment: No urgency bonus here but I've completed the payments in Upwork for @SofoniasN and @hoangzinh 

--- 

@rushatgabhane it looks like the checklist is still WIP but please request a payment via chat when it's complete. Thanks!

**Comment by rushatgabhane** [comment] 2023-08-11 12:32
checklist done

manual request created - https://staging.new.expensify.com/r/750834249578109

**Comment by alexpensify** [comment] 2023-08-11 14:57
Thank you for the update! We are all set and I'm going to close this GH.

**Closed by alexpensify** 2023-08-11 14:57 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-16 03:22
Reviewed the details for @rushatgabhane. Approved for payment in NewDot based on BZ summary above.
