### ISSUE TITLE
[HOLD for payment 2024-05-06] [$500] Connect manually - Connect bank account page does not appear when kill app

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33047] opened 2023-12-14 09:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.12-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Go to Settings> Workspace> Bank Account> Connect manually
2. Kill the app and reopen
3. Go to Settings> Workspace> Bank Account

## Expected Result:
When tap on Bank account user should be navigated to Connect bank account page

## Actual Result:
Connect bank account page where user can select between "Connect online with Plate or "Connect manually" does not appear.
User directly navigates to Connect manually

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/a562d1d3-fc98-4366-86a9-862ce9d4a236

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f44da8781ffd87c4</li>
        <li>Upwork Job ID: 1735236084437544960</li>
        <li>Last Price Increase: 2024-03-28</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by shubham1206agra** [comment] 2023-12-14 11:00
@mountiny Please put this on hold till VBBA refactor

**Comment by shubham1206agra** [comment] 2023-12-18 02:39
Issue ON HOLD

**Comment by zanyrenney** [comment] 2023-12-20 17:47
Hold, moving to weekly.

**Comment by zanyrenney** [comment] 2024-01-05 14:36
on HOLD>

**Comment by zanyrenney** [comment] 2024-01-15 18:52
ON HOLD.

**Comment by zanyrenney** [comment] 2024-01-25 10:19
VBBA refactor isn't complete yet so still holding on this.

**Comment by zanyrenney** [comment] 2024-02-05 19:02
HOLD.

**Comment by zanyrenney** [comment] 2024-02-14 16:11
holding on VBA refactor project.

**Comment by zanyrenney** [comment] 2024-03-07 16:04
Off Hold

**Comment by bernhardoj** [comment] 2024-03-07 16:44
Updated my [proposal](https://github.com/Expensify/App/issues/33047#issuecomment-1855636784)

**Comment by zanyrenney** [comment] 2024-03-18 11:46
@shubham1206agra please can you re-review the proposal from @bernhardoj

**Comment by wildan-m** [comment] 2024-03-22 01:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Connect manually - Connect bank account page does not appear when kill app

### What is the root cause of that problem?

When forcefully closed, the `clearReimbursementAccount` activities [here](https://github.com/Expensify/App/blob/e6f64324c8efa20b32420901b083a063f4a4ceb6/src/pages/ReimbursementAccount/ReimbursementAccountPage.js#L281-L283) are not executed.

### What changes do you think we should make in order to solve the problem?
Re-initialize `ONYXKEYS.REIMBURSEMENT_ACCOUNT` on boot
Change [this code](https://github.com/Expensify/App/blob/7e4a4383a3b7474a15aaba210711a618cd897cbb/src/setup/index.ts#L33-L46) to:
```
import { reimbursementAccountDefaultProps } from '@pages/ReimbursementAccount/reimbursementAccountPropTypes';

.......
        initialKeyStates: {
            // Clear any loading and error messages so they do not appear on app startup
            [ONYXKEYS.SESSION]: {loading: false},
            [ONYXKEYS.ACCOUNT]: CONST.DEFAULT_ACCOUNT_DATA,
            [ONYXKEYS.NETWORK]: CONST.DEFAULT_NETWORK_DATA,
            [ONYXKEYS.IS_SIDEBAR_LOADED]: false,
            [ONYXKEYS.SHOULD_SHOW_COMPOSE_INPUT]: true,
            [ONYXKEYS.MODAL]: {
                isVisible: false,
                willAlertModalBecomeVisible: false,
            },
            // Always open the home route on app startup for native platforms by clearing the lastVisitedPath
            [ONYXKEYS.LAST_VISITED_PATH]: initializeLastVisitedPath(),
            // @ts-expect-error: ONYXKEYS.REIMBURSEMENT_ACCOUNT is conflicting with ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM
            [ONYXKEYS.REIMBURSEMENT_ACCOUNT]: reimbursementAccountDefaultProps,
        },
```

And add  `subStep: null` to [achData.subStep default props](https://github.com/Expensify/App/blob/7e4a4383a3b7474a15aaba210711a618cd897cbb/src/pages/ReimbursementAccount/reimbursementAccountPropTypes.js#L37-L39).
```
const reimbursementAccountDefaultProps = {
    achData: {
        state: BankAccount.STATE.SETUP,
        subStep: null,
    },
......
```


### What alternative solutions did you explore? (Optional)

**Comment by zanyrenney** [comment] 2024-04-02 14:26
I've been OOO. Now back :tada

**Comment by zanyrenney** [comment] 2024-04-02 14:26
@shubham1206agra what do you think of the proposals above?

**Comment by grgia** [comment] 2024-04-04 13:07
@shubham1206agra which issue shall we close?

**Comment by bernhardoj** [comment] 2024-04-04 17:29
PR is ready

cc: @shubham1206agra

**Comment by zanyrenney** [comment] 2024-05-08 11:44
payment summary

paid @bernhardoj $500 via upwork
@shubham1206agra never accepted the offer so having to send new payment offer:

**Comment by zanyrenney** [comment] 2024-05-08 11:44
https://www.upwork.com/nx/wm/offer/102216967 @shubham1206agra please accept ASAP for payout.

**Comment by zanyrenney** [comment] 2024-05-08 11:54
payment summary

paid @bernhardoj $500 via upwork
paid @shubham1206agra $500 via upwork

**Closed by zanyrenney** 2024-05-08 11:54 UTC
Labels: External, Daily, Awaiting Payment, Bug
