### ISSUE TITLE
[HOLD for payment 2023-11-01] [$500] Chat - Blank space appears with no preview or error message when corrupted file is sent

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27292] opened 2023-09-12 20:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat
3. Upload and send a corrupted file ([QA.pdf](https://github.com/Expensify/App/files/12641206/QA.pdf)) to the chat

## Expected Result:
'Uploading attachment...' is shown with error message that the attachment cannot be uploaded

## Actual Result:
Attachment is uploaded but blank space appears in the chat with no preview or error message
On Android app, it shows 'Failed to load PDF file' instead of blank space

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.68-15

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/396d9015-ade1-4447-b2b5-b34ebe4cfe8c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01665e174bbccf204b</li>
        <li>Upwork Job ID: 1703838822623637504</li>
        <li>Last Price Increase: 2023-10-16</li>
    </ul>
</details>

**Comment by maddylewis** [comment] 2023-09-14 19:02
> Upload and send a corrupted file (use the txt to pdf file attached) to the chat

@lanitochka17 - should i be testing this using a specific txt to pdf file?

**Comment by lanitochka17** [comment] 2023-09-16 16:49
@maddylewis Hello 
Tester used this file
[QA.pdf](https://github.com/Expensify/App/files/12641206/QA.pdf)

**Comment by maddylewis** [comment] 2023-09-18 18:24
thanks for confirming -- reviewing again now

**Comment by maddylewis** [comment] 2023-09-18 18:29
i can repro this 
<img width="465" alt="image" src="https://github.com/Expensify/App/assets/38016013/abbdc087-10c9-4435-b294-c5549b700dfc">

**Comment by abdel-h66** [comment] 2023-09-18 19:27
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Failed PDF preview displays an empty comment. 

### What is the root cause of that problem?
When a pdf file is corrupt, the preview won't be possible which is a normal behavior of `react-pdf` library. expect in the code we are handling both display cases for the PDF preview page that appears in the pop up and the other PDF preview that happens is shown in the comments. 

### What changes do you think we should make in order to solve the problem?
```
            const renderErrorMessage = () => {
                if(this.props.onPress) {
                    return <Text style={[styles.PDFErrorMessage]}>{this.props.translate('attachmentView.failedToLoadPDF')}</Text>
                } 
                return <Text style={[styles.textLabel, styles.textLarge]}>{this.props.translate('attachmentView.failedToLoadPDF')}</Text>
            }
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by b4s36t4** [comment] 2023-09-18 19:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Blank space appears with no preview or error message when corrupted file is sent
### What is the root cause of that problem?

We already have error handler which show the failed message on attachment modal but it's not showing here.

If a PDF is correct and valid backend send us the preview of the PDF as a image and we render that image.

https://github.com/Expensify/App/blob/bd6f8f74b51f398fafe6762f9f2293d3be0e0bc8/src/components/PDFView/index.js#L286

But due to the component rendering (PDFView) because backend is not sending any html preview image we're rendering the error message but it's not appearing because of styling issues.
### What changes do you think we should make in order to solve the problem?

We can use `onLoadError` from the `Document` component and set a flag to figure weather the loaded PDF is an error. If it's an error we can have some `minHeight` & `minWidth` which helps shows the rendered text.



### What alternative solutions did you explore? (Optional)
NA

<img width="1441" alt="Screenshot 2023-09-19 at 1 12 08 AM" src="https://github.com/Expensify/App/assets/59088937/52e05dc4-1d35-4aa4-971d-811498b805c5">

<img width="691" alt="Screenshot 2023-09-19 at 1 14 36 AM" src="https://github.com/Expensify/App/assets/59088937/ea187755-8fb1-483f-9927-b2f9a4c24a88">

We might need design review from expensify on how we want to show the error preview.

**Comment by eVoloshchak** [comment] 2023-09-21 11:39
@abdel-h66's proposal looks good to me!
`react-pdf__message` class is indeed at fault, we're correctly detecting that the document is invalid, but due to css class `Failed to load PDF file` is simply not visible.

> 'Uploading attachment...' is shown with error message that the attachment cannot be uploaded

Im not sure if we need to display a different message in this case, `Failed to load PDF file` might be more fitting. If you refresh the page, 'attachment cannot be uploaded' message would be misleading (since it was uploaded, the app just can't display it since it's corrupt). In addition to that, if you send this file to another user, they also should be presented with `Failed to load PDF file` message, since it was clearly uploaded successfully, but again, can't be displayed

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment] 2023-09-25 14:03
Not overdue, waiting for @joelbettner's review of https://github.com/Expensify/App/issues/27292#issuecomment-1729394574

**Comment by eVoloshchak** [comment] 2023-10-02 09:49
Not overdue, waiting for @joelbettner's review of https://github.com/Expensify/App/issues/27292#issuecomment-1729394574

**Comment by eVoloshchak** [comment] 2023-10-05 09:39
Not overdue, waiting for @joelbettner's review of https://github.com/Expensify/App/issues/27292#issuecomment-1729394574

**Comment by eVoloshchak** [comment] 2023-10-11 14:40
Not overdue, same as above https://github.com/Expensify/App/issues/27292#issuecomment-1748494425

**Comment by joelbettner** [comment] 2023-10-11 21:47
@eVoloshchak I think the proposal from @abdel-h66 looks good, and I agree with your comment about changing the copy to say `Failed to load PDF file`. I'll assign @abdel-h66. Sorry this has taken me so long to get to. The issue got lost in my long list of issues to review/fix, that is only ever growing.

**Comment by eVoloshchak** [comment] 2023-10-16 08:57
@abdel-h66, how's the PR moving along?

**Comment by abdel-h66** [comment] 2023-10-16 09:23
Hi @eVoloshchak I didn't receive any offer on upwork, shouldn't that be a requirement before opening it ?

**Comment by eVoloshchak** [comment] 2023-10-16 09:36
> shouldn't that be a requirement before opening it ?

No, as long as you're assigned to the job on GitHub - you can open a PR
Usually, the Upwork offer is sent automatically when you're assigned to the job, but in this case it didn't happen, I think due to this being over 4 weeks old (and thus internal)
But you'll receive an offer when it's time for payment to be made

**Comment by abdel-h66** [comment] 2023-10-16 09:40
oh, wow, really missed on this one then... I will raise the PR soon, It just needs recordings

**Comment by abdel-h66** [comment] 2023-10-16 17:04
PR ready @eVoloshchak ! :)

**Comment by eVoloshchak** [comment] 2023-10-19 17:38
This bug isn't present in native platforms, but while testing I discovered another bug that is specific to native platforms only
When uploading a corrupted PDF file, the whole screen becomes blank for a moment

https://github.com/Expensify/App/assets/9059945/0f2dd943-6986-464b-a205-0044abefe082

@joelbettner, should we handle this here or in a separate issue? This has a different root cause, but the bugs are related

**Comment by maddylewis** [comment] 2023-11-02 00:50
## Payments
- [ ] Contributor: @abdel-h66 ($250 paid via Upwork)
- [ ] C+: @eVoloshchak ($250 paid via NewDot)

Details I have - PR merged on Oct 23 / Contributor hired on Sep 21

**Comment by maddylewis** [comment] 2023-11-02 00:51
hey @abdel-h66 - will you link your Upwork profile? I need to invite you to the job, and can't locate you on Upwork. 

here is the job posting for reference - https://www.upwork.com/jobs/~0132e836fa8add0c70

**Comment by abdel-h66** [comment] 2023-11-02 09:13
Hey @maddylewis the calculations don't seem right to me, These are what I believe to be the correct ones. Please double-check and let me know :) thanks 

Assigned: **_October 11 at 11:47PM_** 
PR Merged: **_October 23 at 8:09PM_** 

And for my freelance profile it should be this 
https://www.upwork.com/freelancers/~01309bb28dda275941

**Comment by eVoloshchak** [comment] 2023-11-06 15:30
- The PR that introduced the bug has been identified. Link to the PR: N/A. The error handling was added in https://github.com/Expensify/App/pull/13409, but only for the case when the file has failed to load when viewing it in an attachment view (for instance, when offline). This particular case with a corrupt file is an edge case we didn't account for from the beginning, so it's more of a feature request
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: Don't think an additional discussion is needed, this is an isolated edge case

**Comment by eVoloshchak** [comment] 2023-11-06 15:35
> Details I have - PR merged on Oct 23 / Contributor hired on Sep 21

@maddylewis, this doesn't seem correct
Contributor was hired on [Oct 11](https://github.com/Expensify/App/issues/27292#issuecomment-1758593970)

**Comment by maddylewis** [comment] 2023-11-08 17:55
thanks for clarifying - updated payment amounts to $500

**Comment by maddylewis** [comment] 2023-11-08 18:03
offer sent @abdel-h66 !

**Comment by maddylewis** [comment] 2023-11-10 19:42
@abdel-h66 - could you accept the offer i sent you in Upwork so i can process payment/close this out? ty!

**Comment by maddylewis** [comment] 2023-11-13 14:54
paid - https://github.com/Expensify/App/issues/27292#issuecomment-1789889741

**Closed by maddylewis** 2023-11-13 14:54 UTC
Labels: External, Engineering, Daily, Internal, Help Wanted, Overdue, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-11-13 18:42
$500 payment approved for @eVoloshchak based on [this comment](https://github.com/Expensify/App/issues/27292#issuecomment-1789889741).
