### ISSUE TITLE
[HOLD for payment 2022-11-16] [$250]  URL address popup won’t show when hovered on terms/privacy links on about page reported by @huzaifa-99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12238] opened 2022-10-28 15:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/settings/about
2. Hover over the ‘terms of service’ and ‘privacy policy’ links on the bottom right corner of the screen.
3. The url address does not show up when hovered over links (it)

## Expected Result:
When hovered over a link, the url address should show up

## Actual Result:
The url address does not show up

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- Web
-Desktop

**Version Number:** 1.2.21-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198665157-5ecd59ed-4509-47e5-9304-8999a61ea982.mp4

https://user-images.githubusercontent.com/43996225/198665197-c495712a-f01c-44da-a6d6-153a89de15db.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666914137280919

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by huzaifa-99** [comment] 2022-10-31 16:03
Are external devs open to contribute? I understand the external label is not applied

**Comment by strepanier03** [comment] 2022-10-31 19:51
I am able to recreate this so sending to External.

**Comment by strepanier03** [comment] 2022-10-31 20:07
Upwork job created: https://www.upwork.com/ab/applicants/1587174307638718464/suggested

----

Job posting: https://www.upwork.com/jobs/~011918eba2b53da485

**Comment by jayeshmangwani** [comment] 2022-10-31 20:23
### Proposal


we need to wrap the terms URL and privacy URL in ToolTip at the about page, and if we want to apply the same hoverable on the login page then we need to wrap these 3 texts in ToolTip on the login page

1. privacy
2. terms
3. licenses


https://github.com/Expensify/App/blob/f656f08e0a5a88fae209dc7bbef5ef74ca8fa894/src/pages/settings/AboutPage/AboutPage.js#L119-L127

```diff
+<Tooltip text={CONST.TERMS_URL}>
<Text
    accessibilityRole="link"
    style={[styles.textMicroSupporting, styles.link]}
    onPress={() => Link.openExternalLink(CONST.TERMS_URL)}
>
    {props.translate(
        'initialSettingsPage.readTheTermsAndPrivacyPolicy.phrase2',
    )}
</Text>
+</Tooltip>
```

https://github.com/Expensify/App/blob/f656f08e0a5a88fae209dc7bbef5ef74ca8fa894/src/pages/settings/AboutPage/AboutPage.js#L133-L141
```diff
+<Tooltip text={CONST.PRIVACY_URL}>
<Text
    accessibilityRole="link"
    style={[styles.textMicroSupporting, styles.link]}
    onPress={() => Link.openExternalLink(CONST.PRIVACY_URL)}
>
    {props.translate(
        'initialSettingsPage.readTheTermsAndPrivacyPolicy.phrase4',
    )}



</Text>
+</Tooltip>
```

## Video after fix
https://user-images.githubusercontent.com/35371050/199103008-9eed86ca-3cf9-4506-84a2-662dee63b2f4.mov

**Comment by strepanier03** [comment] 2022-11-01 23:01
@eVoloshchak - Looks like we have a couple of proposals to review. I'll keep checking in daily while you review and decide which one we'll go with. Thank you!

**Comment by eVoloshchak** [comment] 2022-11-02 15:51
Which tooltip is expected to be shown?

1. Standart tooltip that is built-in into the browser
2. The pop-up [tooltip](https://github.com/Expensify/App/tree/main/src/components/Tooltip) we're showing for links in chat

**Comment by strepanier03** [comment] 2022-11-02 23:41
🤔 Great question, I'm not sure I know the answer for sure but I'll ask internally and see what I can find out.

**Comment by strepanier03** [comment] 2022-11-02 23:52
@Beamanator I'm having a hard time finding how we'd want to work this, can you weigh in on @eVoloshchak's question [here](https://github.com/Expensify/App/issues/12238#issuecomment-1300740244)?

**Comment by Beamanator** [comment] 2022-11-03 09:56
@eVoloshchak @strepanier03 my understanding is the bug report is just talking about the URL that the browser SHOULD show in the bottom-left of the window, when hovering over a URL. So I don't think we want a tooltip which usually shows near your cursor / mouse, but the URL that shows in the bottom-left of the browser - is that clear? If you look at the OP videos, you can see the difference between links when you're signed out & links on the About page

**Comment by eVoloshchak** [comment] 2022-11-03 12:58
@Beamanator, thanks, that makes sense!

In that case, @0xmiroslav's [proposal](https://github.com/Expensify/App/issues/12238#issuecomment-1297615577) looks good to me

🎀👀🎀 C+ reviewed

**Comment by Beamanator** [comment] 2022-11-03 15:30
Nice I like it too 👍

**Comment by strepanier03** [comment] 2022-11-03 22:11
@huzaifa-99, @0xmiroslav, and @eVoloshchak - Please apply for the Upwork job [here](https://www.upwork.com/jobs/~011918eba2b53da485). Thanks!

**Comment by huzaifa-99** [comment] 2022-11-03 22:44
@strepanier03 Applied, Thanks for the update

**Comment by michaelhaxhiu** [comment] 2022-11-03 23:32
Nice job pushing this one forward! I see the PR is submitted and ready for review by @Beamanator. Let's keep up the momentum.

**Comment by strepanier03** [comment] 2022-11-04 21:52
@0xmiroslav - Please let me know when you apply for the job and I'll go in and hire. 

I've accepted the applications from @huzaifa-99 and @eVoloshchak, thank you both!

**Comment by strepanier03** [comment] 2022-11-07 19:20
@eVoloshchak - Can you please complete the PR-related checklist items from above (checks 2-4)?

I am still waiting for TestRail access but once I have it I'll take care of check 1. 

Then I'll take care of checks 5-7 once it's time.

**Comment by strepanier03** [comment] 2022-11-08 23:19
@eVoloshchak - Just a friendly bump for an ETA on when you think the checklist items will be completed.

**Comment by eVoloshchak** [comment] 2022-11-09 13:17
Sorry, missed the original message
I'll take care of the checks `2-4`, ETA in 24h

**Comment by strepanier03** [comment] 2022-11-10 00:31
Sounds perfect, thank you for taking care of those. Feel free to post them in a new comment here and I'll happily add the links to the checklist message.

**Comment by eVoloshchak** [comment] 2022-11-10 13:00
The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/2926
`This has been existing since the creation of the AboutPage`

The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/2926#issuecomment-1310241315

A discussion in #contributor-plus has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: `not sure if that's applicable here, this issue existed since the page was created`

cc: @strepanier03

**Comment by parasharrajat** [comment] 2022-11-10 13:54
Again, this is not a bug or regression but a new feature. This never existed in th app.

We should make clear distinction between regressions and new features. If you are not sure please reach out to the public channel or ask the author whom you think added this.

**Comment by eVoloshchak** [comment] 2022-11-10 13:59
> We should make clear distinction between regressions and new features. If you are not sure please reach out to the public channel or ask the author whom you think added this.

Will do, thank you

**Comment by strepanier03** [comment] 2022-11-11 01:45
I am out of the office tomorrow. If there is an urgent need on this GH from a BugZero team member, please post in #expensify-open-source for assistance.

**Comment by strepanier03** [comment] 2022-11-11 01:45
Oops, didn't meant to close that, sorry!

**Comment by strepanier03** [comment] 2022-11-14 23:16
Will check back in on the 16th to issue payment.

@0xmiroslav - Please apply for the job [here](https://www.upwork.com/jobs/~011918eba2b53da485) @0xmiroslav and I'll let me know here or in Slack once you do. Cheers!

**Comment by strepanier03** [comment] 2022-11-17 01:46
Thank you @0xmiroslav - I'm going to confirm that, since I know it was only recently started and it'll be my first time with the bonus being applicable. I'll follow up here shortly.

**Comment by strepanier03** [comment] 2022-11-17 01:53
After reviewing the announcement [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1667607226305649) which took place on November 5, it says the new bonus structue applied to new PRs only. 

The PR you submitted is dated November 3, so a couple of days before the new process started. 

I won't be able to grant the bonus this time, I am sorry about that, but any PR created from November 5 onward will be eligible.

**Comment by strepanier03** [comment] 2022-11-17 01:56
I'll check in tomorrow morning when I log back on to see if you've accepted and I have the option to pay you. Thanks!

**Comment by strepanier03** [comment] 2022-11-18 01:07
Fantastic, this is all paid out and we're ready to close it down. 

Thank you @0xmiroslav, @eVoloshchak, @huzaifa-99, and @Beamanator for working on this one and getting it done. Cheers!

**Closed by strepanier03** 2022-11-18 01:07 UTC
Labels: External, Daily, Awaiting Payment, Bug
