### ISSUE TITLE
[$500] Expense - Preview shows 0 requests briefly when visiting workspace chat for the first time

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33949] opened 2024-01-04 12:46 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.21-4
**Reproducible in staging?:** y
**Reproducible in production?:* y*
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: There are a few manual requests and ongoing scanning requests in the workspace chat.
1. Send a message in another chat (for web and desktop app)
2. Log out.
3. Log in.
4. Go to the workspace chat.

## Expected Result:
The expense preview will show the number of requests.

## Actual Result:
The expense preview shows 0 requests briefly, while there is no issue with the number of scanning requests.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ce1c86c1-b810-4b80-a987-c9380cd8d8ed

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01eca5a466b3de3517</li>
        <li>Upwork Job ID: 1742890349435052032</li>
        <li>Last Price Increase: 2024-01-27</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-04 13:02
## Proposal

### Please re-state the problem that we are trying to solve in this issue.


### What is the root cause of that problem?
We are calculating the total number of requests using `reportPreviewAction.childMoneyRequestCount`, which is not loaded on the first render of the report preview, and defaults to 0:

https://github.com/Expensify/App/blob/8aec07c55df3f0fefc6bed76c991183cf6b97f7a/src/libs/ReportActionsUtils.ts#L626-L631

### What changes do you think we should make in order to solve the problem?

We can calculate the total count of requests using a similar approach to `numberOfScanningReceipts`:

```js
const numberOfRequests = TransactionUtils.getAllReportTransactions(props.iouReportID).length;
```

https://github.com/Expensify/App/blob/8ff900648e631403e164ce8a9ded798f7b6a8f37/src/components/ReportActionItem/ReportPreview.js#L146

### What alternative solutions did you explore? (Optional)

**Comment by rojiphil** [comment] 2024-01-04 16:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Expense - Preview shows 0 requests briefly when visiting workspace chat for the first time. We are trying to avoid showing this briefly.

### What is the root cause of that problem?

Briefly showing of `0` preview count is due to the fact that `openReport` takes time to update the `childMoneyRequestCount` of Report Preview Action. 

As per the discussion [here](https://github.com/Expensify/App/issues/32658#issuecomment-1871944100) cc @mountiny , to tackle performance problems, BE would want to send just enough data and FE would be used to display just that with little modifications. 

And I am not sure if relying on `transactions` count would be a good idea here as that would bring about external dependency even when the required `childMoneyRequestCount` is available within the Report Preview action. If for performance reason, BE does not send the `transactions` at some later point, we will again have the issue. 

To me, it looks like showing the preview subtitle even when `childMoneyRequestCount` is 0 is the cause of the problem as shown [here](https://github.com/Expensify/App/blob/5fedab802a07d672efc544839f90ba65513f5d44/src/components/ReportActionItem/ReportPreview.js#L311) 

### What changes do you think we should make in order to solve the problem?

We can prevent showing the preview subtitle if `childMoneyRequestCount` is 0 by replacing the condition [here](https://github.com/Expensify/App/blob/5fedab802a07d672efc544839f90ba65513f5d44/src/components/ReportActionItem/ReportPreview.js#L311) like this:

             {!isScanning && numberOfRequests > 0 && (numberOfRequests > 1 || hasReceipts) && (

### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment] 2024-01-09 12:31
Will be working on review today.

**Comment by abdulrahuman5196** [comment] 2024-01-11 15:25
The root cause mentioned by the contributors is correct, we don't have the `childMoneyRequestCount` and many other child information data. It is only got when `OpenReport` is successful. 
@sakluger Could you kindly check internally if this is intentional? If not most likely the fix is goes to be internal.

**Comment by sakluger** [comment] 2024-01-16 20:07
Checking internally on this now.

**Comment by sakluger** [comment] 2024-01-17 21:07
We do want to fix this! I've added to Wave 5 - Release 5, and I am changing the priority to weekly since it's polish, which is lower priority.

**Comment by rojiphil** [comment] 2024-01-18 04:57
Sorry for the delay in follow-up here.

**Comment by rojiphil** [comment] 2024-01-18 04:58
> The root cause mentioned by the contributors is correct, we don't have the childMoneyRequestCount and many other child information data. It is only got when OpenReport is successful.

@abdulrahuman5196 
My understanding of root cause is different as mentioned in my [proposal](https://github.com/Expensify/App/issues/33949#issuecomment-1877417856). 
I think showing the preview subtitle even when childMoneyRequestCount is 0 is the root cause. 
What do you think of this?

**Comment by rojiphil** [comment] 2024-01-18 05:00
> Could you kindly check internally if this is intentional? If not most likely the fix is goes to be internal.

@sakluger 
As mentioned in my [proposal](https://github.com/Expensify/App/issues/33949#issuecomment-1877417856), my understanding is that this is intentional as we are tackling performance problems by sending just enough data.
Also, here, the data is not required until the user navigates to the report which will trigger `openReport` to fetch all required data.
What are your thoughts on this?

**Comment by rojiphil** [comment] 2024-01-18 05:04
> If not most likely the fix is goes to be internal.

> We do want to fix this!

@abdulrahuman5196  @sakluger 
I think my proposal does fix this issue in the FE. 
But I am not sure how this can be fixed from BE.
Or am I missing something here?
Please let me know

**Comment by abdulrahuman5196** [comment] 2024-01-22 18:40
@rojiphil I agree on the points you have mentioned. But we need to confirm if we would be required to derive the data from other available fields or this is some bug in backend not sending data. If its the former we can work on FE fix and if its the later we will work on BE fix. But we should confirm on that first.

**Comment by abdulrahuman5196** [comment] 2024-01-22 18:41
@sakluger Could you kindly provide update if you have any? 
https://github.com/Expensify/App/issues/33949#issuecomment-1894434036

I don't have access to the mentioned slack chat?

**Comment by sakluger** [comment] 2024-01-25 17:40
We may need to hold one more day to find out if this is BE or can be done in the FE, sorry for the wait.

**Comment by sakluger** [comment] 2024-01-26 16:41
I threw the hot pick label so we can find an internal engineer to help.

**Comment by sakluger** [comment] 2024-01-26 19:07
I heard back from our engineers - We'd like this solved in the front end. Thanks for checking!

**Comment by abdulrahuman5196** [comment] 2024-01-29 10:10
Thank you for the confirmation. Will check on frontend fixes.

**Comment by abdulrahuman5196** [comment] 2024-01-31 12:00
Will be working on proposal review today.

**Comment by abdulrahuman5196** [comment] 2024-01-31 14:59
@sakluger I don't see this issue anymore. Could you kindly check on this?


https://github.com/Expensify/App/assets/46707890/2ddf30a2-c3f1-40a6-829c-320059a705cb

**Comment by abdulrahuman5196** [comment] 2024-02-05 13:50
@sakluger To check on this https://github.com/Expensify/App/issues/33949#issuecomment-1919278540

**Comment by neil-marcellini** [comment] 2024-02-05 22:16
I'm also not able to reproduce the bug, so I'm going to close this.


https://github.com/Expensify/App/assets/26260477/2e94a9e2-9718-4319-8fa1-7f0bb8ef837f

**Closed by neil-marcellini** 2024-02-05 22:16 UTC
Labels: Daily, Internal, Bug
