### ISSUE TITLE
[$500]  Distance - Request with empty distance can be created by changing the link to participant link

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33319] opened 2023-12-19 21:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat > + > Request money.
2. Go to Distance.
3. Change the link to [https://staging.new.expensify.com/create/request/participants/1/<workspacechat_ID>.](https://staging.new.expensify.com/create/request/participants/1/%3Cworkspacechat_ID%3E.)
4. Proceed with distance request creation

## Expected Result:
In Step 3, user will be redirected to Request money page
In Step 4, distance request cannot be created as the waypoints are empty

## Actual Result:
In Step 3, user lands on workspace selection page
In Step 4, distance request with empty waypoints can be created, but an error shows up after creating it

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/133c9d52-4d03-4158-a662-dca54b34fd1f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01af0bd38709b573a6</li>
        <li>Upwork Job ID: 1737229471030083584</li>
        <li>Last Price Increase: 2024-01-02</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment] 2023-12-19 22:21
## Proposal
from: @unicorndev-727
### Please re-state the problem that we are trying to solve in this issue.
Request with empty distance can be created by changing the link to participant link.
### What is the root cause of that problem?
The root cause is that we didn't validate the transaction in IOURequestStepParticipants.js depending on iouRequestType in transaction object. We only check the transaction if iouRequestType is 'scan' here.

```
useEffect(() => {
        IOUUtils.navigateToStartStepIfScanFileCannotBeRead(receiptFilename, receiptPath, () => {}, iouRequestType, iouType, transactionID, reportID);
    }, [receiptPath, receiptFilename, iouRequestType, iouType, transactionID, reportID]);
```
### What changes do you think we should make in order to solve the problem?
We need to check if the transaction is eligible to create MoneyRequest and if it is not eligible, we need to go back to RequestMoneyPage.
If the `iouRequestType` in transaction object is `distance`, we need to check the waypoints.
And if it is `manual`, we should check if the `amount` is not zero.
### What alternative solutions did you explore? (Optional)
  N/A

**Comment by cooldev900** [comment] 2023-12-19 22:49
## Proposal
from: @cooldev900
### Please re-state the problem that we are trying to solve in this issue.
Request with empty distance can be created by changing the link to participant link
### What is the root cause of that problem?
The root cause is that transaction is already created when we click distance tab in `MONEY_REQUEST_CREATE` page and we didn't consider visiting participant page by deeplink.
### What changes do you think we should make in order to solve the problem?
In my opinion, we need to check if the amount in transaction is zero and if it is, we should let the user return back to the `MONEY_REQUEST_CREATE` because we don't need to create MoneyRequest with zero amount.
### What alternative solutions did you explore?
N/A

**Comment by DylanDylann** [comment] 2023-12-20 03:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In Step 3, user lands on workspace selection page
In Step 4, distance request with empty waypoints can be created, but an error shows up after creating it

### What is the root cause of that problem?
In here, MoneyRequestParticipantsPage we don't have logic to go back to previous page if the waypoint is invalid 
### What changes do you think we should make in order to solve the problem?
https://github.com/Expensify/App/blob/52ecad401123dbeced531d63dc722aa92e84f537/src/pages/iou/request/step/IOURequestStepParticipants.js#L50

In here we should add logic to navigate back on the distance request and manual request:
- Distance request: navigate back if there is invalid waypoints 
-  Manual request: navigate back if amount is 0


```
useEffect(() => {
        if (iouRequestType === CONST.IOU.REQUEST_TYPE.DISTANCE) {

            const waypoints = lodashGet(transaction, 'comment.waypoints', {});
            const validatedWaypoints = TransactionUtils.getValidWaypoints(waypoints);
            const isInvalidWaypoint = lodashSize(validatedWaypoints) < 2;
            
            if (isInvalidWaypoint) {
                navigateBack();
            }
            return
        }

        if (iouRequestType === CONST.IOU.REQUEST_TYPE.MANUAL &&  lodashGet(transaction, 'amount', 0) === 0) {
            navigateBack() 
            return;
        }
        // Note that we can upload receipt on both manual request and scan request
        IOUUtils.navigateToStartStepIfScanFileCannotBeRead(receiptFilename, receiptPath, () => {}, iouRequestType, iouType, transactionID, reportID);
    }, [receiptPath, receiptFilename, iouRequestType, iouType, transactionID, reportID, transaction, navigateBack]);


```

### What alternative solutions did you explore? (Optional)
NA

**Comment by jacobkim9881** [comment] 2023-12-21 01:56
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
1. When entering selecting participants on URL just after requesting money by distance directly from a chat (not from FAB) the page didn’t go back to before page. This happen by scan or manual.
2. When confirming request money by distance without routes, it is confirmed without routes.
### What is the root cause of that problem?
1. 
There is no going to back page function when `isFromGlobalCreate` is `false` at `useEffect` [`src/pages/iou/request/step/IOURequestStepParticipants.js`](https://github.com/Expensify/App/blob/5715b544475c670475ddd09878846639d7e52aa8/src/pages/iou/request/step/IOURequestStepParticipants.js#L50). `transaction` onyx props has `isFromGlobalCreate`. 
```js
{
    ...
    "isFromGlobalCreate": false
}
```
 If just after requesting from chat, `isFromGlobalCreate` is `false` at selecting users page for request money. It is `true` from request money at FAB. 
2. There is no error message while confirming by distance when clicking confirming request button without routes at `confirm` callback [`src/components/MoneyTemporaryForRefactorRequestConfirmationList.js`](https://github.com/Expensify/App/blob/6797636de63a0d8c0aeb022d36f5db58ffc42057/src/components/MoneyTemporaryForRefactorRequestConfirmationList.js#L477C9-L477C9). It is because confirming by distance without routes is exceptional case.
### What changes do you think we should make in order to solve the problem?
1. Currently selecting users page for split money is only from FAB. So give a function going back if request is came from workplace(`isFromGlobalCreate` is `false`) at [`src/pages/iou/request/step/IOURequestStepParticipants.js`](https://github.com/Expensify/App/blob/5715b544475c670475ddd09878846639d7e52aa8/src/pages/iou/request/step/IOURequestStepParticipants.js#L50). There is `navigateToStartMoneyRequestStep` function for `IOUUtils` which can be used for this case. 

```js
    useEffect(() => {
///// below
        If(isFromGlobalCreate) {
        IOUUtils.navigateToStartMoneyRequestStep(iouRequestType, iouType, transactionID, reportID));
}
///// above
        IOUUtils.navigateToStartStepIfScanFileCannotBeRead(receiptFilename, receiptPath, () => {}, iouRequestType, iouType, transactionID, reportID);
    }, [receiptPath, receiptFilename, iouRequestType, iouType, transactionID, reportID]);
```

If new features for selecting uesrs for split except from FAB are added, then this feature should be edited if it is not from global create(FAB).


2. Give an error if clicking request button on confirming by distance without routes at `src/components/MoneyTemporaryForRefactorRequestConfirmationList.js`](https://github.com/Expensify/App/blob/5715b544475c670475ddd09878846639d7e52aa8/src/pages/iou/request/step/IOURequestStepParticipants.js#L50). 
```js
                if (isDistanceRequest && isDistanceRequestWithoutRoute) {
                    setFormError(‘iou.error.distanceRoutesRequired`);
                    return;
                }
```
Since it needs localized text, objects needed to be added at each language file at `src/languages/`.

### Alternatives
N/A

**Comment by NicMendonca** [comment] 2023-12-22 17:24
@c3024 proposals for you here!

**Comment by c3024** [comment] 2023-12-23 07:23
Asked here in an [earlier relevant discussion on Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1703316149255469?thread_ts=1692998235.169129&cid=C01GTK53T8Q) regarding why these conditions were removed.

**Comment by jacobkim9881** [comment] 2023-12-23 17:58
I read and get [the discussion](https://expensify.slack.com/archives/C01GTK53T8Q/p1703316149255469?thread_ts=1692998235.169129&cid=C01GTK53T8Q). If the first error could not be an error because each steps are separated by URL, should the second error be fixed still? Empty waypoint distance request on chat is an issue.

**Comment by unicorndev-727** [comment] 2023-12-26 16:02
@NicMendonca @c3024 
I added the [result video](https://github.com/Expensify/App/issues/33319#issuecomment-1863553095).

**Comment by NicMendonca** [comment] 2024-01-04 21:06
> Go to Distance.
> Change the link to [https://staging.new.expensify.com/create/request/participants/1/<workspacechat_ID>.](https://staging.new.expensify.com/create/request/participants/1/%3Cworkspacechat_ID%3E.)
> Proceed with distance request creation

Why would a end-user change the URL in a real life example? I am not sure in what use case this would occur in

**Comment by NicMendonca** [comment] 2024-01-04 21:08
@dylanexpensify what do you think of [this](https://github.com/Expensify/App/issues/33319#issuecomment-1877760209)? I don't see this is something an end-user would actually do!

**Comment by c3024** [comment] 2024-01-05 09:51
[Asked here] again on Slack about how we should go about this. 
cc: @cead22

**Comment by NicMendonca** [comment] 2024-01-05 20:26
@c3024 thanks your bringing that up in slack! Looks like the consensus is to `do nothing` so I am going to close this for now!

**Closed by NicMendonca** 2024-01-05 20:26 UTC
Labels: External, Daily, Help Wanted, Bug
