### ISSUE TITLE
[Hold] New Chat - Avatar image is displayed instead of the uploaded display picture.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20572] opened 2023-06-12 01:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to app
2. Click on FAB menu
3. Click on New Chat
4. Type email to search a user

## Expected Result:
Correct Display Image Should Be Displayed Instead Of Avatar For The First Time.

## Actual Result:
 Avatar Is Displayed Instead

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.26.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/83359c29-a84f-40f9-b3fb-57e1c445e3e7

https://github.com/Expensify/App/assets/93399543/3c38b9fc-4ae3-41fc-9803-8ba3cc52f955

**Expensify/Expensify Issue URL:**

**Issue reported by:** @syedsaroshfarrukhdot 

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686108168579789

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Umesh-Bhati** [comment] 2023-06-12 08:32
Here we can show the loader while fetching the user's data.

**Comment by Umesh-Bhati** [comment] 2023-06-12 08:40
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](url)
Upwork Profile Link: [https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1](url)

**Comment by Umesh-Bhati** [comment] 2023-06-12 09:59
ContiContributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:01
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:06
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati@gmail.com)
Upwork Profile Link: [https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1](https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1)

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:09
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](https://github.com/Expensify/App/issues/url)
Upwork Profile Link: [https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1](https://github.com/Expensify/App/issues/url)

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:12
> @Umesh-Bhati I saw you've been trying to save your information here. You need to make sure your email is registered with expensify. (new.staging.expensify or new.expensify.com).

it's registered with the same email id.

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:26
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati193@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:33
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati193@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:42
I don't know why this bot gives me an invalid message. my Expensify account is registered with the same email id that I am trying to save is this 👇 on https://new.expensify.com/
![image](https://github.com/Expensify/App/assets/89525544/0f4a34b3-9f5b-4e2e-baff-9f7638efd4b9)

**Comment by Umesh-Bhati** [comment] 2023-06-12 10:47
can i mention on expensify-bugs channel and here i am not able to find thiennam

**Comment by aliammar1995** [comment] 2023-06-12 16:10
Contributor details
Your Expensify account email: nowakwang0225@outlook.com
Upwork Profile Link: www.upwork.com/freelancers/~0112ce8c179ace5849

**Comment by aliammar1995** [comment] 2023-06-12 16:19
Please re-state the problem that we are trying to solve in this issue.
_Avatar image is displayed instead of the uploaded display picture._

What is the root cause of that problem?
When typing search term to find the user for first time, it does not come personal data from api. It is coming from date that is already stored.

What changes do you think we should make in order to solve the problem?
When the use type search term, it must call api to get personal data and store it.

updateOptionsWithSearchTerm(searchTerm = '') {
        const {recentReports, personalDetails, userToInvite} = OptionsListUtils.getNewChatOptions(
            this.props.reports,
            this.props.personalDetails,
            this.props.betas,
            searchTerm,
            [],
            this.props.isGroupChat ? this.excludedGroupEmails : [],
        );
        this.setState({
            searchTerm,
            userToInvite,
            recentReports,
            personalDetails,
        });
    }

What alternative solutions did you explore? (Optional)
At that time when the user update profile picture, the stored date might be updated  from api.

**Comment by JmillsExpensify** [comment] 2023-06-15 06:10
I'm nearly certain we've have several versions of this report, and they are all on hold for image improvements. @Beamanator @trjExpensify does that sound right?

**Comment by Beamanator** [comment] 2023-06-15 10:43
This one specifically should probably be on hold for the big Onyx Re-key PR that should get merged today

**Comment by trjExpensify** [comment] 2023-06-15 11:29
I don't think this is a caching issue is it? Also, maybe Alex you can unpack why the re-key will fix it?

**Comment by Umesh-Bhati** [comment] 2023-06-17 14:04
Contributor details
Your Expensify account email: [umeshbhati193@gmail.com](mailto:umeshbhati193@gmail.com)
Upwork Profile Link: https://www.upwork.com/freelancers/~018f1a33b14bc5e0a1

**Comment by JmillsExpensify** [comment] 2023-06-21 04:44
Putting this on hold and weekly in the meantime, though I'm still not clear how this relates to the re-key?

**Comment by Beamanator** [comment] 2023-06-21 07:55
Ohhhh interesting maybe this isn't due to the re-key, sorry 😅 

Is this only happening for "brand new" chats being created?

**Comment by trjExpensify** [comment] 2023-06-30 14:32
Yeah, if this is happening for brand new chats you're starting, I actually don't think this is a bug. We don't obtain the personal details until you confirm and open the chat. So all in all, I think you can close this Mills.

**Comment by JmillsExpensify** [comment] 2023-07-05 12:51
Cool, closing.

**Closed by JmillsExpensify** 2023-07-05 12:51 UTC
Labels: Weekly, Overdue, Bug
