### ISSUE TITLE
Suggestion list is hidden behind the IOU preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21915] opened 2023-06-29 21:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to any IOU chat that have preview header
2. Enter :smi and to open suggestion list

## Expected Result:
Suggestion list isn't hidden behind the IOU preview

## Actual Result:
Suggestion list is hidden behind the IOU preview

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.34.1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![Screenshot 2023-06-28 at 19 39 27 (2)](https://github.com/Expensify/App/assets/93399543/cf9a5c8f-b123-413c-8228-50e0f43fdac6)

https://github.com/Expensify/App/assets/93399543/5f2bbda2-7207-42ff-b198-61cff915cc66

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dukenv0307
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688010380484589

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Nikhil-Vats** [comment] 2023-06-29 21:57
dupe of https://github.com/Expensify/App/issues/21741 and will be resolved in #20844. See this [comment](https://github.com/Expensify/App/issues/21741#issuecomment-1610288009).

**Comment by kadiealexander** [comment] 2023-06-30 05:08
Agreed, this seems to be a dupe of https://github.com/Expensify/App/issues/21741. Closing.

**Closed by kadiealexander** 2023-06-30 05:08 UTC
Labels: Daily, Bug
