### ISSUE TITLE
Bug: New tag shouldn’t be there when New message is clicked reported by@chauchausoup

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11505] opened 2022-10-01 16:31 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to any chat
2. Click at Mark as Unread
3. Click on New Message button

## Expected Result:
 New tag shouldn’t be there when New message is clicked.

## Actual Result:
 New tag is there when New message is clicked.

## Workaround:
Unknown
## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.2.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193419030-a43032be-9f12-4bf9-8a06-364bc921b05d.mov

https://user-images.githubusercontent.com/43996225/193419060-3d763bf2-4c3c-4457-a29e-9d24c473aab0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @chauchausoup
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1664604182850369

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by tjferriss** [comment] 2022-10-04 22:43
Closing this out as this is actually an expected feature, not a bug.

**Closed by tjferriss** 2022-10-04 22:43 UTC
Labels: Daily, Overdue

**Comment by chauchausoup** [comment] 2022-10-13 03:53
@tjferriss shouldn,t the **new** tag and the associated green line be vanished once a user clicks on **New Message** button ?

**Comment by tjferriss** [comment] 2022-10-13 04:57
My mistake for not sharing the context. I should have brought this discussion back to the #expensify-open-source channel. I'm still working out this new process. Here is the discussion we had in a private channel on the feature.

<img width="366" alt="Screen Shot 2022-10-12 at 9 56 28 PM" src="https://user-images.githubusercontent.com/8292562/195505169-00140fb9-0991-4566-b65e-e7d1c26f4445.png">
