### ISSUE TITLE
Web - Some characters overlaps the red dot underlining in the "Display Name" Input field.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#22966] opened 2023-07-16 10:53 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open Safari in  full screen mode & login to app
2. Go to settings
3. Click  on Profile
4. Click on Display name
5. Type random characters which contain  "g" & "y"  in First Name & Last Name input field,  eg: fsfsfsyyyggfsfyygg
6. Observe that, letter "g" & "y" overlaps the red dotted underlining

## Expected Result:
Characters shouldn't overlaps the red dot underlining

## Actual Result:
 Letter "g" & "y" overlaps the red dotted underlining

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS/ Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.40-5
**Reproducible in staging?:** n/a
**Reproducible in production?:** n/a
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/ff7b01ea-4d30-4968-8472-d694eca1373a

![Screenshot 2023-07-15 at 12 27 39 PM](https://github.com/Expensify/App/assets/93399543/06d0d20d-e02d-4aec-81b6-1e51c7467539)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @lincolnb17
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689404784439189

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mehvash-Khan** [comment] 2023-07-16 14:52
I think the solution here might be to disable css property `autoCorrect` for fields `First name` and `Last name` in the code [here](https://github.com/Expensify/App/blob/7d4e370c95844ade8f7b9a8519025300627f8dd4/src/pages/settings/Profile/DisplayNamePage.js#L84-L94) and [here](https://github.com/Expensify/App/blob/7d4e370c95844ade8f7b9a8519025300627f8dd4/src/pages/settings/Profile/DisplayNamePage.js#L97-L106). But this would remove the red dotted lines entirely.

**Comment by mehvash-Khan** [comment] 2023-07-16 15:01
Contributor details
Your Expensify account email: mk1997khan@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e83985ab636b50c5

**Comment by Jahanzaib00** [comment] 2023-07-17 11:41
Proposal
Please re-state the problem that we are trying to solve in this issue.

Remove the issue of red-dotted line getting overlapped with letters 

What is the root cause of that problem?

The problem is due to letter 'g' and 'y' ending tails getting overlapped with the line

What changes do you think we should make in order to solve the problem?

Give a space between the line and the characters 

What alternative solutions did you explore? (Optional)

Move the letter 'g' and 'y' above a little using css so they don't overlap

**Comment by shawnborton** [comment] 2023-07-18 00:27
I commented in Slack but I kind of think we shouldn't worry about this, I have a feeling it's a native thing and not something we'd control anyways.

**Comment by trjExpensify** [comment] 2023-07-18 22:50
Cool, that works for me if you're happy. I agree it's not an "us" problem, you can see it elsewhere on like Github for example:

<img width="279" alt="image" src="https://github.com/Expensify/App/assets/16232057/581e814c-2176-46bd-a716-f82814926265">

Anyhow, closing then!

**Closed by trjExpensify** 2023-07-18 22:50 UTC
Labels: Daily, Needs Reproduction, Bug
