### ISSUE TITLE
[HOLD for payment 2024-06-03] [$250] Web -Split - Split amount is not selected when clicking or double clicking on the input

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#42207] opened 2024-05-15 19:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.74-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:

1. Go to https://42057.pr-testing.expensify.com/ - also reproducible in staging
2. Go to FAB > Split expense.
3. Enter amount and select participants.
4. On confirmation page, double click on the split amount input.

## Expected Result:
The value in the input will be selected.

## Actual Result:
The value in the input is not selected.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/1e86b080-983b-4287-86c5-3f5fd19a2741

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176e8fca3d0f13f91</li>
        <li>Upwork Job ID: 1790855337333891072</li>
        <li>Last Price Increase: 2024-05-15</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @JmillsExpensify</details>

**Comment by nkdengineer** [comment] 2024-05-15 21:17
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- The value in the input is not selected.

### What is the root cause of that problem?
- We are using ```shouldPreventDefaultFocusOnSelectRow: true```
### What changes do you think we should make in order to solve the problem?
- Should use ```shouldPreventDefaultFocusOnSelectRow: false``` in this case.

### What alternative solutions did you explore? (Optional)

- NA

**Comment by neil-marcellini** [comment] 2024-05-15 21:18
👀 taking a look now

**Comment by neil-marcellini** [comment] 2024-05-15 21:30
@nkdengineer thanks for the proposal! I set the prop to false on the MoneyRequestConfirmationList page and I see that it fixes the issue. I also see that it was added recently with this PR [feat: refactor MoneyRequestConfirmationList](https://github.com/Expensify/App/pull/40785#top). For a quick fix we could just revert that one.

Could you please explain a bit more about why it's ok to set it false?

It looks like we usually set that prop with this value `!DeviceCapabilities.canUseTouchScreen()`. I think we should probably do that.

**Comment by neil-marcellini** [comment] 2024-05-15 21:31
I'll assign you and you can get started on a PR @nkdengineer

**Comment by neil-marcellini** [comment] 2024-05-15 22:35
@nkdengineer are you around to work on this one? I started looking into it more, and I noticed a problem if we just set `shouldPreventDefaultFocusOnSelectRow` false in the MoneyRequestConfirmationList. Doing so causes the row to be highlighted after clicking on it and navigating back. The same behavior isn't present on production.

I'm going to ask if this should really be a blocker or not and for some other opinions in general.

**Comment by nkdengineer** [comment] 2024-05-15 22:53
I am checking it and investigating the issue you mentioned above

**Comment by neil-marcellini** [comment] 2024-05-15 23:04
@nkdengineer I think I found a fix for both issues. I'm going to put up a quick PR since we want this fixed before the next deploy.

**Comment by nkdengineer** [comment] 2024-05-15 23:05
@neil-marcellini I can create PR in next 10m

**Comment by nkdengineer** [comment] 2024-05-15 23:07
My solution with the issue [here](https://github.com/Expensify/App/issues/42207#issuecomment-2113594150) is in here[](https://github.com/Expensify/App/blob/8c7ec08d0eacd7e27791ff01b0e34b0fa3cb2597/src/components/SelectionList/BaseSelectionList.tsx#L338), adding a logic:
```
        const isFocusedOnScreen = useIsFocused()
        useEffect(()=>{
            if(!isFocusedOnScreen){
                setFocusedIndex(null)
            }
        }, [isFocusedOnScreen])
```

**Comment by neil-marcellini** [comment] 2024-05-15 23:09
Would you please update your original proposal with that new solution and explain why it works, as well as why it won't break anything else?

**Comment by nkdengineer** [comment] 2024-05-15 23:28
@neil-marcellini I update the proposal

**Comment by nkdengineer** [comment] 2024-05-15 23:44
@neil-marcellini When investigating the issue, I found that the bug "the row to be highlighted after clicking on it and navigating back" also appears when we "press on enter" to select the row instead of "Click"

**Comment by nkdengineer** [comment] 2024-05-16 00:45
@neil-marcellini  Actually, I find another solution that can fix all the issue is that, just need to add the below to [this](https://github.com/Expensify/App/blob/3a35c1ce9145be6dc69248c2cdb3d8046b71352c/src/components/MoneyRequestAmountInput.tsx#L287):
```
            onMouseDown={(event)=>event.stopPropagation()}
```

**Comment by neil-marcellini** [comment] 2024-05-16 00:59
@nkdengineer that seems like it could be a good approach. If you would like to put up an alternative to my PR, please go ahead and do so. If the C+ finds problems with mine we could go with your approach.

I'm going to move on to other things for the rest of the day but I'll check back tomorrow.

**Comment by nkdengineer** [comment] 2024-05-16 01:01
Should I raise the PR now or wait until "If the C+ finds problems with mine we"?

**Comment by nkdengineer** [comment] 2024-05-16 01:50
I opened the [PR](https://github.com/Expensify/App/pull/42237) based on comment [here](https://github.com/Expensify/App/issues/42207#issuecomment-2113716315)

**Comment by nkdengineer** [comment] 2024-05-16 02:10
Also, I updated [proposal](https://github.com/Expensify/App/issues/42207#issuecomment-2113471527) to match this [comment](https://github.com/Expensify/App/issues/42207#issuecomment-2113706131)

**Comment by Beamanator** [comment] 2024-05-16 11:33
PR was just CP'd to staging, I'll test

**Comment by Beamanator** [comment] 2024-05-16 12:09
Fixed on staging 👍

**Comment by neil-marcellini** [comment] 2024-05-16 17:24
@strepanier03 would you please handle payment? For some reason that automation didn't run to update the title.

**Comment by nkdengineer** [comment] 2024-05-22 07:57
@neil-marcellini Can you reassign me to this issue based once comment [here](https://github.com/Expensify/App/issues/42207#issuecomment-2113716315)

**Comment by nkdengineer** [comment] 2024-05-29 03:17
@neil-marcellini Can you assign me to this issue?

**Comment by rushatgabhane** [comment] 2024-05-30 21:58
1. The PR that introduced the bug has been identified. Link to the PR:

2. The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

3. A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

4. Determine if we should create a regression test for this bug.

5. If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again

**Comment by rushatgabhane** [comment] 2024-05-30 22:06
@strepanier03 could you please attach payment summary, thank you!

**Comment by JmillsExpensify** [comment] 2024-06-07 03:39
Reached out to @strepanier03 via DM

**Comment by strepanier03** [comment] 2024-06-11 21:15
### Payment Summary

- $250 - @rushatgabhane via Manual Requests

@JmillsExpensify - Request incoming!

**Comment by JmillsExpensify** [comment] 2024-06-11 21:59
$250 approved for @rushatgabhane

**Comment by nkdengineer** [comment] 2024-06-12 02:05
@neil-marcellini Can you help check the payment here? https://github.com/Expensify/App/issues/42207#issuecomment-2161610358? I was assigned to this job as well

**Comment by strepanier03** [comment] 2024-06-13 00:45
Weird, @nkdengineer - reviewing I agree you should have been in that summary. 

I'll whip up a job in Upwork for you and let you know when I send over the contract.

**Comment by strepanier03** [comment] 2024-06-13 00:50
@nkdengineer - Okay, I hired you to the job and will check to pay it again in the morning.

**Comment by strepanier03** [comment] 2024-06-19 02:21
Job paid and contract closed. Thanks all!

**Closed by strepanier03** 2024-06-19 02:21 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
