### ISSUE TITLE
[HOLD for payment 2023-06-02] [$1000] The emoji reaction number and the user who reached the emoji doesn't dynamically update on mweb chrome

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18554] opened 2023-05-07 17:33 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Go to mweb chrome and login with User A
2. Go to any chat with User B (make sure to login with User B on android )
3. From user A on mweb chrome, send a message to user B and react to that message. Long press on that emoji to see the emoji reaction number and the user who reacted it (Do not close the popup )
4. Now on android , from user B, react to the same message
5. On mweb chrome, notice that the emoji reaction number and the users who reacted to the message didn't update on the popup

## Expected Result:
The emoji reaction number and the user who reacted the emoji should dynamically be updated on mweb chrome if another user from android reacts to the same message
## Actual Result:
The emoji reaction number and the user who reached the emoji doesn't dynamically update on mweb chrome

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.11-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236693211-61e25967-608c-4f3d-a21e-ab32faf432b1.mp4

https://user-images.githubusercontent.com/43996225/236693221-9f1db8f6-2ead-4523-bbc9-d982ba3a34b9.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @priya-zha
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1683362031641569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0176132e26d24e7935</li>
        <li>Upwork Job ID: 1655664285267439616</li>
        <li>Last Price Increase: 2023-05-08</li>
    </ul>
</details>

**Comment by strepanier03** [comment] 2023-05-08 19:55
### Testing notes:

Tested on m/web Chrome on Pixel 6 Pro and NewExpensify app on Android Pixel 6 Pro, same device for both. 

I was unable to reproduce this behavior after multiple attempts using my real device. This may be because I am doing the testing on the same device 🤷‍♀️ but I don't know well enough to say for sure. The number of reactions and the users who reacted updated on m/web chrome as soon as I switched to that tab on my phone. 

When I use a combo of Browserstack for m/web Chrome on a Pixel 6 Pro and then Android on my phone, I still wasn't able to reproduce this.

**Comment by strepanier03** [comment] 2023-05-08 20:01
### New testing notes

I missed a step in the testing and after going back I am able to recreate this following the steps. The key is keeping the window with the number/who reacted information open.

<img width="520" alt="2023-05-08_12-59-04" src="https://user-images.githubusercontent.com/10925636/236921964-138df27d-fa41-4af8-b14c-b06b426134af.png">

**Comment by dukenv0307** [comment] 2023-05-09 10:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The emoji reaction number and the user who reached the emoji don't dynamically update 

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/ae4d11dc848debd846b173d120170eadbd6817c2/src/components/Reactions/ReportActionItemReactions.js#L78-L99
When only the user longPress reacted emoji we will pass the emoji's information to PopoverReactionList Component. If there are any updates after PopoverReactionList is displayed, onReactionListOpen function will not be triggered again so PopoverReactionList is not updated.

### What changes do you think we should make in order to solve the problem?
When the user longPress, in here
https://github.com/Expensify/App/blob/ae4d11dc848debd846b173d120170eadbd6817c2/src/components/Reactions/ReportActionItemReactions.js#L89-L99
We shouldn't pass the emoji's information, we should only pass reportActionID. And then here https://github.com/Expensify/App/blob/ae4d11dc848debd846b173d120170eadbd6817c2/src/pages/home/report/ReactionList/PopoverReactionList.js#L98
We will receive reportActionID and get the emoji's information from ONYX and setState with data from ONYX. And we will run showReactionList function when componentDidUpdate (it means that when the emoji's information is updated, this function we run again)

### What alternative solutions did you explore? (Optional)

**Comment by dukenv0307** [comment] 2023-05-10 09:45
@rushatgabhane [This PR](https://github.com/Expensify/App/pull/18701) is ready for review

**Comment by strepanier03** [comment] 2023-05-13 22:48
Bumped on PR.

**Comment by strepanier03** [comment] 2023-05-17 18:11
PR has been merged and is awaiting deploy to staging.

**Comment by strepanier03** [comment] 2023-05-19 17:19
Waiting on merge to prod, all good here.

**Comment by strepanier03** [comment] 2023-05-22 18:56
On staging and waiting Prod push, good here for now.

**Comment by strepanier03** [comment] 2023-06-01 20:16
@dukenv0307 and @rushatgabhane - I have hired you both for the Upwork job. Rushat, feel free to complete the checklist and I'll update it and make the reg test GH if required.

@priya-zha- I have created an Upwork job for the reporting payment [here](https://www.upwork.com/jobs/~01ed08c911c26a4e2e), can you apply or link me to your Upwork profile so I'm confident I'm hiring the right person.

**Comment by strepanier03** [comment] 2023-06-05 02:56
I'll check in tomorrow and take next steps once we have a checklist update.

**Comment by strepanier03** [comment] 2023-06-06 21:47
Friendly little bump on the checklist when you have bandwidth @rushatgabhane.

**Comment by strepanier03** [comment] 2023-06-09 22:10
@rushatgabhane any update on when you'll be able to wrap up the checklist?

**Comment by cristipaval** [comment] 2023-06-15 16:26
@strepanier03 @rushatgabhane

**Comment by strepanier03** [comment] 2023-06-15 23:41
@johncschuster - We are waiting for @rushatgabhane to accept the offer in Upwork and then we can it out. Payment details [here](https://github.com/Expensify/App/issues/18554#issuecomment-1563876115), but this is a straight $1000 payment without bonus applied.

@rushatgabhane feel free to ping here once you've accepted, thanks!

**Comment by cristipaval** [comment] 2023-06-19 20:49
@johncschuster is ooo today.

@rushatgabhane has to accept the offer in Upwork.

**Comment by johncschuster** [comment] 2023-06-20 15:53
@rushatgabhane, I see the offer is pending in Upwork. Can you accept that so we can take care of the payment for you?

Thanks!

**Comment by cristipaval** [comment] 2023-06-23 10:00
@rushatgabhane ?

**Comment by johncschuster** [comment] 2023-06-26 17:57
Of course! Thanks for the heads up, @rushatgabhane!

**Comment by johncschuster** [comment] 2023-07-18 18:39
Thanks for the heads up @rushatgabhane!

**Closed by johncschuster** 2023-07-18 18:39 UTC
Labels: External, Weekly, Overdue, Awaiting Payment, Bug
