### ISSUE TITLE
[C+ Checklist Needs Completion] [$2000] Desktop - Secondary login successfully unlinked isn't displayed on Desktop App

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19681] opened 2023-05-26 17:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Issue found when executing PR** https://github.com/Expensify/App/pull/18695

## Action Performed:
1. Add a secondary login account, and leave it unverified
2. Open new tab
3. Navigate to sign in page
4. Enter the unverified email address
5. Click on Unlink button
6. Open email account, click on 'the validation link here' to unlink the account

## Expected Result:
Verify 'Secondary login successfully unlinked' message is displayed

## Actual Result:
Error "It looks like there was an error with your validation link or it has expired" is displayed on Desktop App. Secondary login successfully unlinked isn't displayed on Desktop App

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.18.1

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://platform.applause.com/services/links/v1/external/f7afb6d068adfdbdde0f1d6ae5706bb5c712c83708c22ab676054146ec813281

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c02e30a7c9039200</li>
        <li>Upwork Job ID: 1663518060802252800</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment] 2023-05-30 09:22
Reviewing

**Comment by greg-schroeder** [comment] 2023-05-31 09:03
@Santhosh-Sellavel thoughts on the proposal [here](https://github.com/Expensify/App/issues/19681#issuecomment-1565023149)?

**Comment by Santhosh-Sellavel** [comment] 2023-05-31 16:38
@greg-schroeder No other proposals to review here.

**Comment by greg-schroeder** [comment] 2023-05-31 20:59
ok!

**Comment by thienlnam** [comment] 2023-06-06 21:56
Adding the label to test some upwork automation stuff

**Comment by francoisl** [comment] 2023-06-07 15:53
@hoangzinh I imagine your proposal is still on hold based on follow-up discussions in https://github.com/Expensify/App/issues/17724, is that right?

**Comment by Santhosh-Sellavel** [comment] 2023-06-09 20:15
Can we double this up or wait?

**Comment by greg-schroeder** [comment] 2023-06-12 15:08
Doubled bounty

**Comment by greg-schroeder** [comment] 2023-06-14 20:26
Still awaiting proposals. Will send this to CS/SWM soon if nothing comes.

**Comment by francoisl** [comment] 2023-06-16 18:13
Ok thanks, that makes sense to me! 
@Santhosh-Sellavel do you have anything to add or any questions about this proposal?

**Comment by Santhosh-Sellavel** [comment] 2023-06-16 18:22
Ah, I missed it will review it and let you know, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-16 21:01
I'm confused about the issue itself. Here is the attached video on the issue description. 
Check below. 

After clicking `unlink` first time why verify secondary account email was sent?

https://github.com/Expensify/App/assets/85645967/973aee8b-d003-4ae4-9673-fcad4a7663fa

**Comment by Santhosh-Sellavel** [comment] 2023-06-17 07:53
@hoangzinh  I too got the same email after clicking unlink. Can you send a video reproducing the issue?

**Comment by Santhosh-Sellavel** [comment] 2023-06-17 13:17
> Moreover, we can't even unlink atm even in Web. There is a report bug here https://expensify.slack.com/archives/C049HHMV9SM/p1686642802173109
> But the main issue of this GH issue is still there, the code is expired when open in Desktop so I think we can fix them separately.

Both should be fixed here. As it is the same issue.

**Comment by greg-schroeder** [comment] 2023-06-19 17:08
Thoughts on [this](https://github.com/Expensify/App/issues/19681#issuecomment-1595756525) @francoisl?

**Comment by francoisl** [comment] 2023-06-20 21:19
> Moreover, we can't even unlink atm even in Web. There is a report bug here [expensify.slack.com/archives/C049HHMV9SM/p1686642802173109](https://expensify.slack.com/archives/C049HHMV9SM/p1686642802173109)

Looking at that conversation leads to https://github.com/Expensify/App/issues/20676, which was closed last week (with a fix), so that part should work now. Let's confirm that unlinking is working as intended now and see if @hoangzinh's proposal would still work.

**Comment by francoisl** [comment] 2023-06-22 22:39
Ok yeah that makes sense. Were you able to test with your suggested change and confirm it fixes the `Secondary login successfully unlinked! was not found in the default language` error?

**Comment by greg-schroeder** [comment] 2023-06-26 18:21
Okay can we check the updated proposal from @hoangzinh @Santhosh-Sellavel ?

**Comment by francoisl** [comment] 2023-06-26 18:22
Ok cool, the [proposal](https://github.com/Expensify/App/issues/19681#issuecomment-1565023149) makes sense to me and I think we should go with that? Sound good to you too @Santhosh-Sellavel?

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 18:25
@francoisl 
Yeah looks good to me as well, let's go with them here, thanks!

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 18:25
Please make the issue external;

**Comment by Santhosh-Sellavel** [comment] 2023-06-26 18:28
Unassign @hoangzinh and reassign them

@francoisl or @greg-schroeder

**Comment by NikkiWines** [comment] 2023-06-27 19:23
Hmm, I don't think we should be prompting users to unlink their logins from the magic code view. Users should only be able to trigger that flow from the main sign-in view (after entering an unvalidated secondary login). For desktop, the flow should ideally behave like this: 

https://user-images.githubusercontent.com/16747822/233736212-ca1e7db3-92db-4caa-bc08-db8654e90b0b.mov

**Comment by francoisl** [comment] 2023-06-27 20:18
Hmm but the whole issue is with people that open the desktop app when they're prompted to do so on web. Are you suggesting we should instead _not_ show the native "Open New Expensify?" modal if you open an unlink URL?

**Comment by NikkiWines** [comment] 2023-06-27 23:22
> we should instead not show the native "Open New Expensify?" modal if you open an unlink URL?

Initially, that was the intended design, so I'm fine with that.

But if we want to maintain the deep linking into the desktop app, I don't think we need to display a prompt to the user to unlink their login, since presumably they were in the middle of doing that already. 

In that case, I think the simplest solution would be to show the standard loading icon in web and not the magic code view (with or without unlink prompt), since there's nowhere for the user to enter the validation code in this case and they're already directed to the desktop app when they click `Open in New Expensify`

**Comment by NikkiWines** [comment] 2023-06-27 23:40
That seems to be the same behavior we see for signing in if the user presses `Cancel` so I think it's ok for the same to occur in this case.

https://github.com/Expensify/App/assets/16747822/8d2e136c-4fe3-4207-a95a-2cb9e919c292

**Comment by NikkiWines** [comment] 2023-06-27 23:57
I believe the user should only see the `Abracadabra` page if they're automatically authenticated. For the case of signing in, I would think either the loading page or the magic link page would make the most sense if the action is cancelled after being prompted to open the desktop app (unless they somehow end up automatically authenticated elsewhere - in which case the abracadabra view would be the correct view to display )

In the case of unlinking a login, there isn't anywhere for the user to enter the magic code if we were to display it and they're not being authenticated into the app, so neither the magic code view nor the abracadabra view make sense (to me at least). 

Perhaps if they press `Cancel` we should fall back and attempt to unlink the login via web? In my opinion though I think it's fine to simply show the loading indicator and  have the user restart their process if they cancel things half way through. I'm definitely open to other options though!

**Comment by francoisl** [comment] 2023-06-28 23:40
Ok, thanks @NikkiWines for chiming in.

> I really love this redirect screen. But we removed it.

I think you're talking about https://github.com/Expensify/App/pull/17452/ ? I just noticed this PR as well. I agree it would have been great to be able to use this here. Speaking of which, I wonder if we need to put a hold on this issue until https://github.com/Expensify/App/pull/17452/ is merged, since it's going to change the deep linking logic quite a bit.

**Comment by greg-schroeder** [comment] 2023-06-30 07:27
Adjusting to `Weekly` to account for issue hold

**Comment by greg-schroeder** [comment] 2023-07-08 00:27
Still on hold

**Comment by greg-schroeder** [comment] 2023-07-17 16:14
Holding

**Comment by greg-schroeder** [comment] 2023-07-25 18:17
Removed hold and re-applying Daily cadence. I'll let the folks pinged in @hoangzinh's comment above weigh in on what we should do next.

**Comment by NikkiWines** [comment] 2023-07-25 22:19
Ran through this flow once more on dev just to refamiliarize myself 

Web seems to be broken - the login is unlinked but we don't successfully show that to the user

https://github.com/Expensify/App/assets/16747822/5e751ebf-6735-4a95-a399-5addc873e0f0

Desktop seems to work fine, though I'm not prompted to open the link in the desktop app :¯\_(ツ)_/¯

**Comment by NikkiWines** [comment] 2023-07-25 22:29
Ah ok nice. Well regardless of where this issue ends up we should definitely fix that. 

Just to clarify, is there an issue with desktop now that the unlinking flow works without the deeplink? @hoangzinh are you prompted to open the link in the desktop app when going through the unlink login flow?

**Comment by NikkiWines** [comment] 2023-07-25 23:00
> The only issue/concern is in desktop, it will still show "Unlink form" although it's unlinked successfully in web

Hmm, yeah I guess ideally it would also update to the login page + show the `Login successfully unlinked` though personally i think it's fine as is. 

 > Nope, I'm clarifying our expected results in this GH issue. Should we do like @NikkiWines suggested https://github.com/Expensify/App/issues/19681#issuecomment-1610365145 and @francoisl verified again here https://github.com/Expensify/App/issues/19681#issuecomment-1610157633
 
 Cool, thanks for double-checking. If the user were to see the `Open in New Expensify` prompt and then pressed `Cancel`, I think the behavior shown [here](https://github.com/Expensify/App/issues/19681#issuecomment-1610365145) would be fine (with just the loading page).

However, I'm not currently being prompted to open the link in the desktop app when going through this flow and I think the current behavior is fine too (unlinking in web, desktop retains old info) 
 
 @francoisl what do you think?

**Comment by francoisl** [comment] 2023-07-26 03:01
Yeah,  I'm still being prompted from staging. If I select the "Open <desktop>" option, the request is still being sent from the web app's tab, so eventually the desktop app shows an error (also the update takes forever to send from the backend right now, but... different issue):

<table>
<tr>
 <td>Opening desktop app when prompted
 <td>Not opening desktop app
<tr>
 <td><video src="https://github.com/Expensify/App/assets/2229301/1c522101-ebd8-4d04-84b4-b05ea4db2149" />
 <td><video src="https://github.com/Expensify/App/assets/2229301/9dced494-bcde-4f84-873d-25e55cb77883"/>
</table>

So in the end I think the easiest solution would be to prevent showing the `Open in New Expensify` prompt if you open an unlink URL. Is that what you were asking to confirm @hoangzinh?

**Comment by francoisl** [comment] 2023-07-26 23:47
Ok. For the sake of having a pull request that will match the proposed solution, do you mind updating your proposal then @hoangzinh please? Also, let's make sure it fixes the crash that Nikki got on web in https://github.com/Expensify/App/issues/19681#issuecomment-1650639867.

**Comment by greg-schroeder** [comment] 2023-07-31 12:55
Work continues on the PR, looks like @Santhosh-Sellavel is reviewing

**Comment by greg-schroeder** [comment] 2023-08-02 10:34
Last update: https://github.com/Expensify/App/pull/23738#issuecomment-1661307429

**Comment by greg-schroeder** [comment] 2023-08-16 02:06
Awaiting deploy to prod

**Comment by greg-schroeder** [comment] 2023-08-24 20:04
Okay so it looks like this one took a fair amount of time to be merged following the assignment: https://github.com/Expensify/App/issues/19681#issuecomment-1675471516

**Comment by Santhosh-Sellavel** [comment] 2023-08-24 20:40
Yeah, we had active discussions on deciding the outcome post-assigning and also the issue was on hold for some period.
So let's have the flat fee here, thanks!

**Comment by greg-schroeder** [comment] 2023-08-25 22:10
Offer made to @hoangzinh - you can request payment via NewDot @Santhosh-Sellavel. All that's left is the C+ checklist

**Comment by greg-schroeder** [comment] 2023-08-28 10:11
Awaiting checklist

**Comment by Santhosh-Sellavel** [comment] 2023-08-29 21:17
I think we can skip the checklist. IMO this is not a regression, we intentionally wanted all URLs to be deep links. Now we just disabled one here and also improved the unlink flow on the web & other platforms.

But we could add/update Tests though and test steps from PR look good to me.

Thoughts @francoisl?

**Comment by Santhosh-Sellavel** [comment] 2023-08-30 18:15
@greg-schroeder Can you post a payment summary message, thanks!

**Comment by greg-schroeder** [comment] 2023-08-30 20:17
Payment summary:

Contributor: $2000 (flat, no bonus/penalty)
C+: $2000 (flat, no bonus/penalty)

closing as checklist is complete as well. next up is @JmillsExpensify to confirm payment

**Closed by greg-schroeder** 2023-08-30 20:17 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-09-01 22:54
Reviewed the details for @Santhosh-Sellavel. $2,000 payment approved via NewDot based on BZ summary.
