### ISSUE TITLE
Android - Attachment-Unable to load protected PDF error appears when wrong password is entered

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#22919] opened 2023-07-14 20:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22565
## Action Performed:
1. Launch New Expensify app
2. Go to any chat and open protected PDF attachment
3. Tap introduce la contraseña (Enter the password)
4. Disconnect network
5. Enter incorrect password

## Expected Result:
Error message about incorrect password shows up

## Actual Result:
Error message 'Hubo un error al intentar cargar el pdf' (There was an error trying to load the pdf) about unable to load PDF shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.410

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/ab42cb97-af52-4742-81a3-d89782ba461a

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

**Comment by MitchExpensify** [comment] 2023-07-16 16:25
Same, I am unable to reproduce. What version did you try @hungvu193 ?

**Comment by MitchExpensify** [comment] 2023-07-16 16:42
Thank you!

**Comment by MitchExpensify** [comment] 2023-07-19 20:04
Closing until this has solid reproduction steps

**Closed by MitchExpensify** 2023-07-19 20:04 UTC
Labels: Daily, Needs Reproduction, Overdue, Bug
