### ISSUE TITLE
PAID [$250] [Bug] -  error message out of screen reported by @gadhiyamanan

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#11488] opened 2022-09-30 23:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. go to OldDot
2. create account
3. create free policy
4. click on it
5. go to workspace
6. connect bank account
7. Go to Workspace > connect bank account
8. check error message

## Expected Result:
error message should not be out of screen

## Actual Result:
error message out of screen

## Workaround:
unknown

## Platform:

Where is this issue occurring?

- iOS
- Android

**Version Number:** 1.2.10 - 0
**Reproducible in staging?:** Need reproduction
**Reproducible in production?:** Need reproduction
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/193369361-807d307f-97ba-4725-bf69-aded70568ec0.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @gadhiyamanan
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1661423805265769

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mnosov622** [comment] 2022-10-07 23:59
Hello @kavimuru !

Can you assign this issue to me, please ?

I would love to fix this bug.

**Comment by gadhiyamanan** [comment] 2022-10-08 04:03
**Proposal**

use `style={[styles.mutedTextLabel, styles.flex1]}` instead of `style={styles.mutedTextLabel}`
https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/pages/ReimbursementAccount/BankAccountStep.js#L253-L255

**Comment by gadhiyamanan** [comment] 2022-10-11 14:02
@kavimuru no one assigned here

**Comment by kavimuru** [comment] 2022-10-11 23:12
@mnosov622  I have assigned now. @gadhiyamanan I didn't assign as it needed a reproduction.

**Comment by mnosov622** [comment] 2022-10-11 23:12
Hi !

Thank you.

**Comment by kavimuru** [comment] 2022-10-11 23:13
@mnosov622 Needs a reproduction. I couldn't reproduce.

**Comment by mnosov622** [comment] 2022-10-11 23:16
Oh, okay

**Comment by tjferriss** [comment] 2022-10-21 22:27
I'm not able to reproduce as I don't have a simulator or a real business bank account to add in order to get this error message. @gadhiyamanan is reporting they can see still see the bug, so I'm going to pass this over to engineering.

**Comment by gadhiyamanan** [comment] 2022-10-22 05:09
revert condition in the below code to see an error 
https://github.com/Expensify/App/blob/70efb00eeb6e9617ecfa478e6348a252d4ac13f4/src/pages/ReimbursementAccount/BankAccountStep.js#L140-L149

![Simulator Screen Shot - iPhone 13 mini - 2022-10-22 at 10 30 20](https://user-images.githubusercontent.com/54790231/197320795-bee5a299-2ebb-4cd4-a580-23b036d3052a.jpg)

**Comment by deetergp** [comment] 2022-10-24 18:50
This is definitely something that can be addressed by one of our contributors.

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-25 01:38
**Proposal**

The issue that is causing text to move out of the screen is first Icon is being rapped in <Text> there is no need to do so.
https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/pages/ReimbursementAccount/BankAccountStep.js#L248-L257

In order to fix we need to remove Text tag from Icon and need to add styles.flexRow, styles.ml2, styles.flexWrap, styles.flex1 to style of the text being rendered

Code Fix Snippet:-
###  <View style={[styles.flexRow, styles.alignItemsCenter, styles.m4]}>
               <Icon src={Expensicons.Exclamation} fill={colors.red} />
              <Text style={[styles.mutedTextLabel,styles.flexRow, styles.ml2, styles.flexWrap, styles.flex1]}>
                        {props.translate('bankAccount.validateAccountError')}
                </Text>
 </View>


![Simulator Screen Shot - iPhone 13 Pro - 2022-10-25 at 06 36 05](https://user-images.githubusercontent.com/81307212/197661617-058a26ea-8ff1-40f5-b395-bbafe6f16bf3.png)

![Simulator Screen Shot - iPhone 8 - 2022-10-25 at 06 35 25](https://user-images.githubusercontent.com/81307212/197661589-670a9b2f-c8fe-4976-9a76-4eb412ad7975.png)

**Comment by Santhosh-Sellavel** [comment] 2022-10-25 21:40
@syedsaroshfarrukhdot Can you compare before/after changes in other platforms and ensure we don't break anything?

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-25 22:42
@Santhosh-Sellavel  Sure these are before/after changes in all platforms and I have ensured that anything doesn't break.

Desktop Before :- 

<img width="1209" alt="Desktop Before" src="https://user-images.githubusercontent.com/81307212/197894468-0d35bbe5-fd95-4d39-8d3f-911cfa013b51.png">

Desktop After :- 

<img width="1209" alt="Desktop After" src="https://user-images.githubusercontent.com/81307212/197894504-65c75439-2ef9-4b74-88ff-8a3d21212868.png">

Web Before :-

<img width="1427" alt="Web Before" src="https://user-images.githubusercontent.com/81307212/197894668-672da1e7-957a-454a-9b5a-211dfaa34439.png">

Web After :- 
<img width="1427" alt="Web After" src="https://user-images.githubusercontent.com/81307212/197894706-06f8e589-4408-489a-a396-1dd38fcdbac7.png">


IOS Before :-

![Ios Before](https://user-images.githubusercontent.com/81307212/197894606-d3ddeca2-e310-4f64-be02-53419b00634c.png)

IOS After :-

![Ios After](https://user-images.githubusercontent.com/81307212/197894636-86bfb585-c6ec-4d57-b86f-260a81fa95f9.png)

Android Before :- 

![AndroidBefore](https://user-images.githubusercontent.com/81307212/197894788-304d7c63-a4b0-4c4e-b34c-fa47f7f0a4ca.png)

Android After :- 
![Android After](https://user-images.githubusercontent.com/81307212/197895662-b6471d73-b31d-4bb5-904b-ee83baba18b9.png)


mWeb IOS Before :-

![mWebBeforeIOS](https://user-images.githubusercontent.com/81307212/197894899-96a10f1e-138d-46a7-9988-74f63444bfe4.png)

mWeb IOS After :-

![mWebAfterIOS](https://user-images.githubusercontent.com/81307212/197894972-8b349b71-5b46-486c-9394-ad6874e0927b.png)

mWeb Andoird Before :-

![mWebAndroidBefore](https://user-images.githubusercontent.com/81307212/197895141-c69d0564-9917-42a2-8150-260d9210e28a.jpeg)

mWeb Andoird After :-

![mWebAndroidAfter](https://user-images.githubusercontent.com/81307212/197895168-83860469-d9bb-4b8e-bb4e-fa5bf878c832.jpeg)

**Comment by gadhiyamanan** [comment] 2022-10-26 01:31
@Santhosh-Sellavel please check [proposal](https://github.com/Expensify/App/issues/11488#issuecomment-1272218423)

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 21:50
@gadhiyamanan can you please send screenshots before and after like above?

**Comment by Santhosh-Sellavel** [comment] 2022-10-26 21:53
@syedsaroshfarrukhdot seems off, something got affected on the web.
<img width="301" alt="Screenshot 2022-10-27 at 3 21 46 AM" src="https://user-images.githubusercontent.com/85645967/198145493-44b7f834-4fc3-42ab-adbb-e90f7b5d872d.png">
<img width="317" alt="Screenshot 2022-10-27 at 3 21 50 AM" src="https://user-images.githubusercontent.com/85645967/198145495-1a835666-1cad-4155-933c-115ce426c935.png">

Ideally, things should look as it was earlier on other platforms.

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-26 22:58
@Santhosh-Sellavel  To achieve things exactly on other platforms like before we need to pass styles.ml4 instead of styles.ml2 and it will be just like similar to all platforms and the problem will also be fixed

We can use this code snippet

Code Fix Snippet:-

### <View style={[styles.flexRow, styles.alignItemsCenter, styles.m4]}>
           <Icon src={Expensicons.Exclamation} fill={colors.red} />
          <Text style={[styles.mutedTextLabel,styles.flexRow, styles.ml4,styles.flexWrap, styles.flex1]}> 
                    {props.translate('bankAccount.validateAccountError')}
            </Text>

Desktop Before :-

<img width="1200" alt="Desktop Before" src="https://user-images.githubusercontent.com/81307212/198153591-1756968a-ab13-49aa-91e0-9fac818a3574.png">

Desktop After :-

<img width="1200" alt="Desktop After" src="https://user-images.githubusercontent.com/81307212/198153625-7ba801d0-14fd-4e52-ba2e-6fc5bd4b5e63.png">

Web Before :-

<img width="1437" alt="Web Before" src="https://user-images.githubusercontent.com/81307212/198153662-a3a603e2-c9c6-428c-ab08-f2685f707f90.png">

Web After :- 

<img width="1437" alt="Web After" src="https://user-images.githubusercontent.com/81307212/198153687-406735a0-5ce8-4d9e-8abd-589e8235ec20.png">

IOS Before :- 

<img width="408" alt="IOS Before" src="https://user-images.githubusercontent.com/81307212/198153720-cece2bbc-5fdf-43df-94dc-a32e749eaf27.png">

IOS After :-

<img width="408" alt="IOS After" src="https://user-images.githubusercontent.com/81307212/198153746-c9ce8b9b-6d68-4a7f-bb6d-fcce96181cbc.png">

Android Before :-

<img width="408" alt="Android Before" src="https://user-images.githubusercontent.com/81307212/198153790-d83aaa2b-eabd-4147-a6ce-54a184f399d2.png">

Android After :-  

<img width="408" alt="AndroidAfter" src="https://user-images.githubusercontent.com/81307212/198153827-73c02246-8923-4711-ab36-97282be82c24.png">

mWeb IOS Before :-

<img width="408" alt="mWebIOS Before" src="https://user-images.githubusercontent.com/81307212/198153913-eb1f3ab5-d728-4b26-9175-14f6ee792073.png">

mWeb IOS After :-

<img width="408" alt="mWeb Ios After" src="https://user-images.githubusercontent.com/81307212/198153946-0d671069-1884-44f9-828a-1d4178b9bce2.png">

mWeb Android Before :-

<img width="408" alt="mWeb Android Before" src="https://user-images.githubusercontent.com/81307212/198153977-52055eb6-902d-486c-9d4f-9905e20599c0.png">

mWeb Android After :-

<img width="408" alt="mWeb Android After" src="https://user-images.githubusercontent.com/81307212/198153998-6fdc4c4e-38fc-408d-8397-9581064b3181.png">

**Comment by Santhosh-Sellavel** [comment] 2022-10-27 18:53
> @Santhosh-Sellavel To achieve things exactly on other platforms like before we need to pass styles.ml4 instead of styles.ml2 and it will be just like similar to all platforms and the problem will also be fixed

Can you briefly explain why?

**Comment by syedsaroshfarrukhdot** [comment] 2022-10-27 19:14
Yes, this is because we are passing styles.mutedTextLabel and  styles.mr4 to <Text> tag in which <Icon> Is being wrapped as it seems not a good idea to wrap <Icon> with <Text> Tag and passing styles to it. 

https://github.com/Expensify/App/blob/159249bb82317fcd6bd06bc8d4f9127c300a9f9c/src/pages/ReimbursementAccount/BankAccountStep.js#L250-L252

So we need to style the `Text` tag below the `Icon` to match the `styles.mr4` when it was being wrapped in `Text` so we need to set `styles.ml4` to `Text`

### <View style={[styles.flexRow, styles.alignItemsCenter, styles.m4]}>
       <Icon src={Expensicons.Exclamation} fill={colors.red} />
       <Text style={[styles.mutedTextLabel,styles.flexRow, styles.ml4,styles.flexWrap, styles.flex1]}> 
                {props.translate('bankAccount.validateAccountError')}
       </Text>

**Comment by gadhiyamanan** [comment] 2022-10-28 02:03
please check the screenshots after the fix :

Web chrome : 
![Screenshot 2022-10-22 at 10 36 18 AM](https://user-images.githubusercontent.com/54790231/198276597-15e29c1d-7f5c-4019-a4d9-78b4ea5ebda4.png)

Web safari :
![Screenshot 2022-10-22 at 10 37 17 AM](https://user-images.githubusercontent.com/54790231/198276741-961ec00e-957c-4d68-a1fe-c580a3c0fe0e.png)

Desktop:
![Screenshot 2022-10-22 at 10 44 05 AM](https://user-images.githubusercontent.com/54790231/198276927-7f965fa0-39da-41be-bc00-649bf6d5cd81.png)

Android:
![Screenshot 2022-10-22 at 10 44 56 AM](https://user-images.githubusercontent.com/54790231/198277025-7230a0a0-0ca5-47a2-a501-aa5ad4c9e4fe.png)


IOS:
![Simulator Screen Shot - iPhone 13 mini - 2022-10-22 at 10 32 39](https://user-images.githubusercontent.com/54790231/198277315-7773447b-9452-4ad3-b444-dc9b514fab84.png)

mweb-chrome:
![Screenshot_2022-10-22-10-47-51-41](https://user-images.githubusercontent.com/54790231/198277174-f60c0612-bcd9-4d51-91d1-6c60b65b05e9.png)

mweb-safari:
![Simulator Screen Shot - iPhone 13 mini - 2022-10-22 at 10 41 05](https://user-images.githubusercontent.com/54790231/198277437-282378ff-9d6c-4735-b549-e8e9f2f05b8c.png)

**Comment by gadhiyamanan** [comment] 2022-10-28 08:38
[Proposal](https://github.com/Expensify/App/issues/11488#issuecomment-1272218423) works for me

**Comment by laurenreidexpensify** [comment] 2022-10-31 11:02
Not overdue

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 18:39
> [Proposal](https://github.com/Expensify/App/issues/11488#issuecomment-1272218423) works for me

Seems you have edited it recently. Please do not do that, always submit it as a new comment always.

**Comment by Santhosh-Sellavel** [comment] 2022-10-31 18:41
@gadhiyamanan Can you resubmit again to get it reviewed, 

Also briefly explain what causes the issues, and how your changes addressed the cause.

thanks!

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-01 06:16
> > @Santhosh-Sellavel To achieve things exactly on other platforms like before we need to pass styles.ml4 instead of styles.ml2 and it will be just like similar to all platforms and the problem will also be fixed
> 
> Thanks look good, Can you briefly explain why?

@Santhosh-Sellavel Please could you review my explanation as well https://github.com/Expensify/App/issues/11488#issuecomment-1293956691

**Comment by gadhiyamanan** [comment] 2022-11-01 10:05
**Updated Proposal**

We have to add `width` or `flex` to `<Text>` component to wrap content when Text is too long 
in our case `flex` is more suitable

Replace style={styles.mutedTextLabel} with style={[styles.mutedTextLabel, styles.flex1]} 
 
https://github.com/Expensify/App/blob/38b1d8477115094299d8584768fd4694170234a4/src/pages/ReimbursementAccount/BankAccountStep.js#L145-L147

**Comment by gadhiyamanan** [comment] 2022-11-01 10:10
> Seems you have edited it recently. Please do not do that, always submit it as a new comment always. 

Thanks for suggestion.
There is some code refactoring recently so i just updated line numers.

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 22:15
@nkuoch  Since you added this code block, why was Icon Wrapped inside a Text Component?
https://github.com/Expensify/App/blob/38b1d8477115094299d8584768fd4694170234a4/src/pages/ReimbursementAccount/BankAccountStep.js#L142-L144

**Comment by Santhosh-Sellavel** [comment] 2022-11-01 22:18
@marcochavezf 
I like @gadhiyamanan's proposal here https://github.com/Expensify/App/issues/11488#issuecomment-1298300219
It's simple and straightforward.

But @syedsaroshfarrukhdot proposal here makes us wonder why [this](https://github.com/Expensify/App/issues/11488#issuecomment-1299297956) was done.

**Comment by marcochavezf** [comment] 2022-11-02 19:01
Thanks @Santhosh-Sellavel for reviewing them.

>But @syedsaroshfarrukhdot proposal https://github.com/Expensify/App/issues/11488#issuecomment-1293956691 makes us wonder why https://github.com/Expensify/App/issues/11488#issuecomment-1299297956 was done.

Yeah, this comes from a big refactor, so I think it's a minor oversight that happened during the refactor.

I also like https://github.com/Expensify/App/issues/11488#issuecomment-1298300219, but also I like the idea of cleaning up the wrapped Icon. Would be possible to do a mix of both proposals (use `mutedTextLabel` and clean the wrapped Icon up)?

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-02 19:25
**Updated Proposal** 
@Santhosh-Sellavel  The improved code to fix both issues cleaning up the wrapped icon and overflowing text could be resolved by the below code snippet. 

                    <View style={[styles.flexRow, styles.alignItemsCenter, styles.m4]}>
                           <Icon src={Expensicons.Exclamation} fill={colors.red} />
                           <Text style={[styles.mutedTextLabel, styles.ml4 , styles.flex1]}>
                               {props.translate('bankAccount.validateAccountError')}
                           </Text>
                    </View>

@marcochavezf in the above code snippet we are cleaning wrapped icon and `Text`  is being  passed `mutedTextLabel` i don't think we need to pass `mutedTextLabel` to `Icon`

**Comment by gadhiyamanan** [comment] 2022-11-03 10:02
>I also like https://github.com/Expensify/App/issues/11488#issuecomment-1298300219, but also I like the idea of cleaning up the wrapped Icon.

in that case we can remove `<Text>` which wraps Icon  and add `styles.ml4` along with `styles.flex1`

 ```
          <View style={[styles.flexRow, styles.alignItemsCenter, styles.m4]}>
            <Icon src={Expensicons.Exclamation} fill={colors.red} />
            <Text style={[styles.mutedTextLabel, styles.ml4, styles.flex1]}>
              {props.translate('bankAccount.validateAccountError')}
            </Text>
          </View>
```

After fix : 
![Simulator Screen Shot - iPhone 13 mini - 2022-11-03 at 15 28 57](https://user-images.githubusercontent.com/54790231/199692770-ca96feb1-e930-46f6-bbdb-6a8f7d87d83c.jpg)

**Comment by nkuoch** [comment] 2022-11-03 15:21
> Yeah, this comes from a big refactor, so I think it's a minor oversight that happened during the refactor.

That must be it :)

**Comment by Santhosh-Sellavel** [comment] 2022-11-07 02:09
@marcochavezf 
@syedsaroshfarrukhdot [proposal](https://github.com/Expensify/App/issues/11488#issuecomment-1301110463) looks good!
C+ Reviewed 
🎀 👀 🎀

**Comment by marcochavezf** [comment] 2022-11-08 03:59
Thank you @Santhosh-Sellavel! assigning @syedsaroshfarrukhdot  🚀

**Comment by laurenreidexpensify** [comment] 2022-11-08 10:01
https://www.upwork.com/jobs/~0123c0031939c72d6a

**Comment by laurenreidexpensify** [comment] 2022-11-08 10:05
Offers sent in Upwork ✔️

**Comment by gadhiyamanan** [comment] 2022-11-08 10:07
@laurenreidexpensify applied

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-08 10:15
Thank you for assigning me. Just accepted the invite on Upwork will be making a PR ready in next few hours.

**Comment by mvtglobally** [comment] 2022-11-09 03:42
Issue not reproducible during KI retests. (First week)

**Comment by laurenreidexpensify** [comment] 2022-11-16 15:50
Yes sorry Copy Pasta 🍝 mistake 🤦‍♀️

**Comment by laurenreidexpensify** [comment] 2022-11-18 12:32
@Santhosh-Sellavel @gadhiyamanan @syedsaroshfarrukhdot payment has been sent in Upwork 👍

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-18 12:40
![Screenshot_2022-11-18-17-38-41-10_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/81307212/202707035-2c3e7ca0-0288-49c9-bffc-6a91c0f89390.jpg) just a curious question am I eligible for the 50% bonus for this issue ?

**Comment by laurenreidexpensify** [comment] 2022-11-18 15:04
LGTM @syedsaroshfarrukhdot, issued bonus 👍

**Comment by syedsaroshfarrukhdot** [comment] 2022-11-18 15:15
> LGTM @syedsaroshfarrukhdot, issued bonus 👍 

Thank You

**Comment by Santhosh-Sellavel** [comment] 2022-11-18 16:10
@laurenreidexpensify I didn't get paid!

**Comment by mvtglobally** [comment] 2022-11-22 21:14
Issue not reproducible during KI retests. (Third week)

**Comment by laurenreidexpensify** [comment] 2022-11-23 15:44
@Santhosh-Sellavel huge apols!! missed this-  paying now!

**Comment by laurenreidexpensify** [comment] 2022-11-23 16:09
Looking into adding this to TestRail here https://expensify.slack.com/archives/C021UBMAFCJ/p1669136987942179?thread_ts=1669136224.569399&cid=C021UBMAFCJ

**Comment by Santhosh-Sellavel** [comment] 2022-11-24 13:57
@laurenreidexpensify I received only $125 bonus, didn’t receive the payment $250 for the job!

**Comment by laurenreidexpensify** [comment] 2022-11-25 10:19
@Santhosh-Sellavel hug apols!!!! I have corrected this now.

**Closed** 2022-11-25 11:01 UTC
Labels: Reviewing, External, Engineering, Daily, Bug
