### ISSUE TITLE
Android native - Unable to modify login input details

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#18606] opened 2023-05-08 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Log out if already logged in.
2. Enter Any valid login
3. Tap on the empty area so the login field gets unfocused
4. Now Click Continue
5. Enter Magic code page appears
6. Now click Go back
7. Try to modify login details

## Expected Result:
Able to modify the login details
## Actual Result:
Unable to change the value, the Keyboard does not show up while tapping on the input field.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [] Android / Chrome
- [] iOS / native
- [] iOS / Safari
- [] MacOS / Chrome / Safari
- [] MacOS / Desktop

**Version Number:** 1.3.11.2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/43996225/236919721-fa36df74-7407-4588-9018-05daba91ec9c.mp4

https://user-images.githubusercontent.com/43996225/236919759-5ab2d4c4-1133-4ddf-9b4f-df093117c9f8.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Santhosh-Sellavel 
**Slack conversation:**  https://expensify.slack.com/archives/C049HHMV9SM/p1683484246745849

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-05-12 00:38
Can't reproduce this one on a Pixel 7 using browserstack: 

https://github.com/Expensify/App/assets/16232057/c04e5c59-6c5e-406d-a218-e69030d15221

Are the repro steps accurate, @Santhosh-Sellavel? Equally, can you reproduce on the latest?

**Comment by Santhosh-Sellavel** [comment] 2023-05-12 20:54
@trjExpensify 
 I can't reproduce it on the latest build if the issue occurs again. I'll leave a comment here.

**Comment by trjExpensify** [comment] 2023-05-12 22:52
Cool, sounds good. Closing!

**Closed by trjExpensify** 2023-05-12 22:52 UTC
Labels: Daily, Needs Reproduction, Bug
