### ISSUE TITLE
[HOLD for payment 2024-07-24] [$125] Transfer owner - "Continue" button is missing bottom margin

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44825] opened 2024-07-04 13:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/44712
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User is invited to a workspace.
- User is also promoted to admin.

1. Go to staging.new.expensify.com
2. Go to workspace settings > Members.
3. Click on the owner.
4. Click Transfer owner.

## Expected Result:
"Continue" button on "Duplicate subscription alert" page will have bottom margin.

## Actual Result:
"Continue" button on "Duplicate subscription alert" page does not have bottom margin.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/145f5a2c-da8c-406d-9041-598af038816d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01851c277cf7d0a07b</li>
        <li>Upwork Job ID: 1811060685379521358</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @miljakljajic</details>

**Comment by izarutskaya** [comment] 2024-07-04 13:13
We think this issue might be related to the #collect project.

**Comment by etCoderDysto** [comment] 2024-07-04 13:15
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Continue" button is missing bottom margin

### What is the root cause of that problem?
In `WorkspaceOwnerChangeCheck` we are not adding bottom margin to the `Button` component 
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L79-L83
### What changes do you think we should make in order to solve the problem?
1. Wrap the `Button` in `View` component 
2. Add `styles.pb5` to the `View` component 

```javascript
<View style={styles.pb5}>
                <Button...
```

### What alternative solutions did you explore? (Optional)

**Comment by etCoderDysto** [comment] 2024-07-04 13:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Continue" button is missing bottom margin

### What is the root cause of that problem?
In `WorkspaceOwnerChangeCheck` we are not adding bottom margin to the `Button` component 
https://github.com/Expensify/App/blob/83eb7e6ee5f8a86c4500deda3454763680dcd5cf/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L79-L83
### What changes do you think we should make in order to solve the problem?
1. Wrap the `Button` in `View` component 
2. Add `styles.pb5` to the `View` component 

```javascript
<View style={styles.pb5}>
                <Button...
```

### What alternative solutions did you explore? (Optional)

**Comment by nkdengineer** [comment] 2024-07-05 07:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Transfer owner - "Continue" button is missing bottom margin

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/74a6dbba2105ceba086f0387f50dcad573d4569f/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx#L79-L84

We don't add bottom margin to the button 
### What changes do you think we should make in order to solve the problem?
We implemented `FixedFooter` Component to align this bug on other pages

```
<FixedFooter style={[styles.mtAuto, styles.pt5]}>
                <Button
                    success
                    large
                    onPress={confirm}
                    text={displayTexts.buttonText}
                />
</FixedFooter>
```

### What alternative solutions did you explore? (Optional)

**Comment by divyeshgajera1** [comment] 2024-07-10 19:39
App/src/pages/workspace/members/WorkspaceOwnerChangeCheck.tsx

- Add wrapper view in this screen top of the button and add marginBottom  as per need

**Comment by mehedy201** [comment] 2024-07-10 20:12
``Please go to this WorkspaceMemberDetailsPage.tsx file. line no: 182 and 192 and try with this code. in style={[styles.mv5]}

**Comment by Daniel-Kline-1** [comment] 2024-07-10 20:37
There are a few things that I think could be causing the issue.  

It looks like there is an improperly written css value. I would want to look at styles.mtAuto and styles.pt5

A few things I will look for, 
- are you using flex? If so then how is it being used? Is the same flex being used on mobile and web? The code will run on 
every device, it wont crash. But mobile and web will interpret it just slightly differently

 - The "justify-content" value for the parent component, It looks like its currently set to "space-between". CSS properties are inherited from the parent components (maybe a flex value or grid property is being picked up)
 - 
-  The height of the FixedFooter component. If it's larger than the page, then the button will be lower

**Comment by Daniel-Kline-1** [comment] 2024-07-10 20:42
Contributor details
Your Expensify account email: klined49@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~0185ba2c752fddc2ff

**Comment by mehedy201** [comment] 2024-07-10 20:54
Contributor details
_______________
Mehedi Hasan (Full Stack Web Developer)

Your Expensify account email: m ***@***.***>***@***.***
Upwork Profile Link: https://www.upwork.com/freelancers/~0130f6d1f50aa998d6


Also If you want to implement style using a javascript object like this
style={styles.mv5}  Please go to your spacing.ts and type like this CSS.
please check the attachment. my node version 20.10.0 is why I am not
running your app locally. so please try it. I hope fix the issue.
[image: Screenshot 2024-07-11 024306.png]

**Comment by jayeshmangwani** [comment] 2024-07-10 21:55
This is a straightforward issue of missing padding at the bottom of the button/parent component. Although all the above proposals will work in this case, I prefer the first working solution. @etCoderDysto 's [Proposal](https://github.com/Expensify/App/issues/44825#issuecomment-2208969257) of adding a parent view to the button component and add padding bottom of the view looks good to me. We can go with their proposal.

🎀 👀 🎀 C+

**Comment by cristipaval** [comment] 2024-07-11 11:31
This is a super simple issue. I'll make it $125.

**Comment by etCoderDysto** [comment] 2024-07-11 11:41
I will raise a PR ASAP.

**Comment by etCoderDysto** [comment] 2024-07-12 10:12
@jayeshmangwani [PR](https://github.com/Expensify/App/pull/45329) is ready for review

**Comment by jayeshmangwani** [comment] 2024-07-17 19:44
- [x] [@jayeshmangwani] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42771
- [x]  [@jayeshmangwani] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42771#discussion_r1681634156
- [x]  [@jayeshmangwani] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/A**
- [x]  [@jayeshmangwani] Determine if we should create a regression test for this bug. **No**
- [x]  [@jayeshmangwani] If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again. **N/A**

**Comment by miljakljajic** [comment] 2024-07-24 10:00
Payment summary below 

@jayeshmangwani is owed 125 USD for their work reviewing this issue and PR

**Comment by miljakljajic** [comment] 2024-07-24 10:02
@etCoderDysto what is your upwork profile? It doesnt seem like you've applied to the job yet? https://www.upwork.com/ab/applicants/1811060685379521358/applicants?nav_dir=pop

**Comment by etCoderDysto** [comment] 2024-07-24 11:46
> https://www.upwork.com/jobs/~01851c277cf7d0a07b

I have applied to job now @miljakljajic.

**Comment by jayeshmangwani** [comment] 2024-07-25 04:56
Requested $125

**Comment by miljakljajic** [comment] 2024-07-25 17:18
thank you @etCoderDysto once you accept the offer I will pay it right away!

**Comment by etCoderDysto** [comment] 2024-07-25 17:35
I have accepted the offer. Thank you @miljakljajic

**Comment by miljakljajic** [comment] 2024-07-26 06:24
everyone paid, no tests required, closing out.

**Closed by miljakljajic** 2024-07-26 06:24 UTC
Labels: External, Daily, Awaiting Payment, Bug
