### ISSUE TITLE
[HOLD for payment 2023-08-10] [HOLD for payment 2023-08-08] Chat - Crash when deleting attachment from user B when user A has open attachment modal

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#23964] opened 2023-07-31 22:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/22543
## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with user A
3. On another device/incognito, login with user B
4. From user B send an attachment
5. From user A, click on the attachment to open attachment modal
6. From user B, delete this attachment

## Expected Result:
An attachment modal closed

## Actual Result:
App crashed for user A

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.48.0

**Reproducible in staging?:** Yes
 
**Reproducible in production?:** No

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/0772375e-6702-4f49-9f13-9eaed29881e9

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by railway17** [comment] 2023-08-01 02:12
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat - Crash when deleting attachment from user B when user A has open attachment modal

### What is the root cause of that problem?
While reportActions props variable is changed by onyx, it calls `createInitialState`  to initiate the AttachmentCarousel state in the AttachmentCarousel component.
When deleting the image, it also calls the `createInitialState` because it was defined in useEffect.
Inside of createInitialState, it calls `onNavigate` with `undefined` parameter which is defined in the parent component
The app crashs here.

### What changes do you think we should make in order to solve the problem?
To close the AttachmentModal at this moment, we need to update the `onNavigate` handler in `AttachmentModal.js` file
So, it can be updated like below
```
const onNavigate = useCallback(
        (attachment) => {
            if (!attachment) {
                closeModal()
            } else {
                setSource(attachment.source);
                setFile(attachment.file);
                setIsAuthTokenRequired(attachment.isAuthTokenRequired);
                onCarouselAttachmentChange(attachment);
            }
        },
        [onCarouselAttachmentChange, closeModal],
    );
```

### What alternative solutions did you explore? (Optional)
N/A

**Comment by Beamanator** [comment] 2023-08-01 09:56
Thanks for your investigation so far @railway17 - it looks like you're thinking the problem comes from `props.onNavigate(attachments[page]);` in `createInitialState`, right? Here? https://github.com/Expensify/App/blob/52b8ddc2a5edc1b2d2ddbde20b95779dbbdb6380/src/components/AttachmentCarousel/createInitialState.js#L57-L58

Let's try reproducing in production

**Comment by Beamanator** [comment] 2023-08-01 10:08
Couldn't reproduce on prod, could reproduce on staging only

**Comment by Beamanator** [comment] 2023-08-01 10:10
@railway17 I like your solution, how quickly can you get a PR up?

**Comment by railway17** [comment] 2023-08-01 10:10
> @railway17 I like your solution, how quickly can you get a PR up?

I can do it shortly

**Comment by Beamanator** [comment] 2023-08-01 10:12
OK thanks I'm exploring one other option at the moment

**Comment by railway17** [comment] 2023-08-01 10:13
> OK thanks I'm exploring one other option at the moment

In the meantime, do you want me to create a PR with my solution?

**Comment by Beamanator** [comment] 2023-08-01 10:21
@railway17 it looks like this PR actually caused the issue: https://github.com/Expensify/App/pull/22543

The reason is we started doing `Navigation.dismissModal` instead of throwing, so after dismissing the modal we continued on to `props.onNavigate` even though the page didn't exist anymore

I'm going to put up a PR with a solution that returns early instead of handling nonexistent `attachments`

**Comment by Beamanator** [comment] 2023-08-01 10:31
PR is up: https://github.com/Expensify/App/pull/23988

**Comment by Natnael-Guchima** [comment] 2023-08-01 10:50
@Beamanator @twisterdotcom I have reported this issue on July 29
[Slack](https://expensify.slack.com/archives/C049HHMV9SM/p1690627861170639?thread_ts=1690627861.170639&cid=C049HHMV9SM), [GH]( https://github.com/Expensify/App/issues/23896#issuecomment-1659539806). And this is to ask if I am eligible to be added here as original reporter.

**Comment by twisterdotcom** [comment] 2023-08-01 11:31
Was the original issue which fixed this https://github.com/Expensify/App/issues/22261 fixed by https://github.com/Expensify/App/pull/23143 (which is still in review)? That's the issue linked to the PR which caused the regression, which was filed before your bug report.

It seems like we were already aware of this at the time of the report, so I would not attribute you as the reporter here I'm afraid.

**Comment by rushatgabhane** [comment] 2023-08-01 15:24
PR merged. @twisterdotcom could you please assign this to me for C+

**Comment by Beamanator** [comment] 2023-08-01 15:39
Removing deploy blocker, this is fixed in staging now 👍

**Comment by Natnael-Guchima** [comment] 2023-08-01 17:12
@twisterdotcom Sorry, for asking a lot of questions 😁. If this issue was known on and documented on this pr https://github.com/Expensify/App/issues/22261 shouldn't this issue be reproducible on production too, since the PR is 2 weeks old? This issue was reproducible only on staging.

**Comment by twisterdotcom** [comment] 2023-08-09 15:08
@Natnael-Guchima sorry I missed your Q here. I don't quite follow it. I still think this was reported earlier than your report. If not, we are obviously happy to rectify but could you make it as easy as possible to follow that for me?

**Comment by twisterdotcom** [comment] 2023-08-09 15:12
Payment Summary for this issue:
No Bug reporter or Contributor[*](https://github.com/Expensify/App/issues/23964#issuecomment-1671593766)
@rushatgabhane will be paid via newDot $1000

**Closed by twisterdotcom** 2023-08-09 15:12 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug

**Comment by Natnael-Guchima** [comment] 2023-08-09 15:27
@twisterdotcom okay, I am going to try to make my argument clear. But no worries if you think the issue was known. 

Let's call the issue I reported 'report A' and the issue that claim to have a similar root cause with my report as 'report B'. 

* Report A was a depoly blocker when it was first reported. It was only reproducible only on staging and not reproducible on production. 


* At the time report A was reported, report B was two weeks old issue. And it was reproducible on staging and production too. 

My question was if report A and report B have similar root causes, shouldn't 'report A' as 'report B' be reproducible on staging and production by the time it was reported?

**Comment by JmillsExpensify** [comment] 2023-08-10 03:22
Reviewed the details for @rushatgabhane. $1k is approved for payment in NewDot.

**Comment by Natnael-Guchima** [comment] 2023-08-10 17:35
@twisterdotcom that makes sense. I won't be put off. It is really nice and rewarding to work here.  Thanks for bearing up with me 🙂
