### ISSUE TITLE
"Hmm, it's not here page" when trying to set a merchant name immediately after creating a request

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36707] opened 2024-02-16 16:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression  testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @joekaufmanexpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1708017708380219

## Action Performed:
1. Go to workspace chat
2. Request money by scanning a receipt
3. Immediately open the expense and try to edit the merchant / description

## Expected Result:
User is able to edit the exepense

## Actual Result:
"Hmm it's not here page"  is shown

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/ac333854-4840-41d4-ba32-c42ff30b2d40

https://github.com/Expensify/App/assets/38435837/fc10270a-793a-4ed0-abea-0b42d17c7e65

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Christinadobrzyn** [comment] 2024-02-16 17:22
might be related to - https://github.com/Expensify/App/issues/36574

**Comment by bfitzexpensify** [comment] 2024-02-19 06:42
Agreed @Christinadobrzyn, I think https://github.com/Expensify/App/pull/36179 should resolve this too. Subscribing, will re-test this once that's live.

**Comment by bfitzexpensify** [comment] 2024-02-20 05:39
https://github.com/Expensify/App/pull/36179 on staging - adding `retest-weekly` label

**Comment by bfitzexpensify** [comment] 2024-02-27 01:28
OK, https://github.com/Expensify/App/pull/36179 just hit prod - posted in #qa for this to be re-tested

**Comment by kbecciv** [comment] 2024-02-27 12:43
I'm unable to reproduce it on my end with build 1.4.44.1, doble check with original reporter - https://expensify.slack.com/archives/C049HHMV9SM/p1709037761497759?thread_ts=1708017708.380219&cid=C049HHMV9SM

https://github.com/Expensify/App/assets/93399543/d15392ca-34d8-4231-bdb7-18a4c014b475

**Comment by bfitzexpensify** [comment] 2024-02-28 07:16
Thanks! Makes sense that https://github.com/Expensify/App/pull/36179 solved this. Let's close this one out.

**Closed by bfitzexpensify** 2024-02-28 07:16 UTC
Labels: Daily, Bug, retest-weekly
