### ISSUE TITLE
[$250] Header - No unapprove option for first approver

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50292] opened 2024-10-05 15:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** biruknew45+1399@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace and enable workflow 
3. Set the delay submission to "Manual."
4. Add 3 members to the workspace:
- Employee
- Approver A (first approver)
- Approver B (second approver)
5. Configure the approval workflow:
- Employee submits to Approver A
- Approver B is the second approver
6. As the employee, submit an expense in the workspace chat
7. As Approver A, approver the expense
8. As approver A, click on the preview and then go to the header

## Expected Result:
The first approver should have the option to unapprove the expense, similar to the second approver

## Actual Result:
There is no option for the first approver to unapprove the expense in the header, but the second approver has

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/d8b5a7d2-e110-4df2-ba7a-a8fbbf8c0623

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843475137047948222</li>
        <li>Upwork Job ID: 1843475137047948222</li>
        <li>Last Price Increase: 2024-10-22</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment] 2024-10-05 15:59
@VictoriaExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by VictoriaExpensify** [comment] 2024-10-08 02:14
Yeah Approver A should have the ability to unapproved the expense, but I _think_ they should only have this option up until it is approved by Approver B -  believe that's how Classic logic works. Checking on this.

**Comment by truph01** [comment] 2024-10-08 08:50
@alitoshmatov Currently, if an expense is awaiting approval from approver B, and approver A attempts to unapprove the expense, the backend throws an error: 'Only managers and admins can unapprove.' 

I am not sure if the feature that "Allow approver A to unapprove" can be supported by BE, can you or any internal member confirm?

**Comment by alitoshmatov** [comment] 2024-10-15 15:11
@VictoriaExpensify Can we make sure expected behavior in OP is correct since backend does not support this logic right now as pointed out [here](https://github.com/Expensify/App/issues/50292#issuecomment-2399248460). If expected behavior indeed correct then we need internal engineer to implement this feature on backend

**Comment by VictoriaExpensify** [comment] 2024-10-24 02:32
Sorry, I lost visbility of this issue. I've just done some testing and I'm actually going to close this out, this behaviour mirrors the current behaviour in Classic and is "by design". Since this isn't a bug, I'm going ahead and closing

**Closed by VictoriaExpensify** 2024-10-24 02:32 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
