### ISSUE TITLE
[$500] Scan - "Only visible to you" does not automatically disappear when scanning is complete

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34392] opened 2024-01-11 20:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!

**Version Number:**  1.4.24-4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to workspace chat
2. Create a Scan request
3. Click on the expense preview to open expense report
4. Wait for the scanning to complete in the expense report page

## Expected Result:
When the scanning is complete, "Only visible to you" whisper message will automatically disappears

## Actual Result:
When the scanning is complete, "Only visible to you" whisper message does not automatically disappears. It disappears when the report page is revisited

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c9337585-7abe-4a90-a839-e23b9d5dddec

![Bug6339298_1705001790053!E_receipt_](https://github.com/Expensify/App/assets/78819774/1026b401-7dbf-4455-b7c2-39142d3a8ff2)

 
[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fc68fd7d820cf752</li>
        <li>Upwork Job ID: 1745545815292416000</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by FitseTLT** [comment] 2024-01-11 20:49
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Only visible to you" does not automatically disappear when scanning is complete

### What is the root cause of that problem?
It is because we have not considered whisperedAccountID on the memoizing of report
### What changes do you think we should make in order to solve the problem?

We should include the change of `action.whisperedToAccountIDs`
https://github.com/Expensify/App/blob/55746c78a6ef59d9ad636eda8c610023c3cd62ac/src/pages/home/report/ReportActionItem.js#L802-L803
### What alternative solutions did you explore? (Optional)

**Comment by lschurr** [comment] 2024-01-15 07:01
@getusha could you take a look at this proposal?

**Comment by getusha** [comment] 2024-01-15 07:08
Looks like a BE issue, lets get internal engineer to have a look on this. 🎀 👀 🎀

**Comment by arosiclair** [comment] 2024-01-15 14:58
Reached out to the wave5 team to take a look [here](https://expensify.slack.com/archives/C05DWUDHVK7/p1705330637516529). If nobody can, I'll take a look later.

**Comment by kevinksullivan** [comment] 2024-01-15 20:09
Going to close this out since the issue will be irrelevant once we move away from whisper messages in the near future. 

https://expensify.slack.com/archives/C05DWUDHVK7/p1705330637516529

**Closed** 2024-01-16 14:29 UTC
Labels: External, Daily, Help Wanted, Bug
