### ISSUE TITLE
[$1000] mWeb- IOU- Tapping on IOU created for new user with non-existing account shows error page

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#27078] opened 2023-09-09 09:54 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap new chat
4. Enter a new non-existing account and select it
5. Tap plus icon
6. Tap request money
7. Enter amount
8. Tap next
9. Tap request amount
10. Tap on IOU created to note error page

Another scenario:
1. Go to https://staging.new.expensify.com/
2. Tap Fab
3. Tap request money
4. Enter amount
5. Tap next
6. Enter a new non-existing account and select it
7. Tap request amount
8. Tap IOU created to note no error in IOU details page

## Expected Result:
Tapping on IOU created for new user with non-existing account should open a regular IOU page. 

## Actual Result:
If IOU is created, by creating a new chat(new user with non-existing account) and requesting money from conversation page, then IOU report page shows error.
Tapping on IOU created for new user with non-existing account shows error page.

If IOU is created, by tapping request money, and selecting new user with non-existing account, then IOU report page shows no error.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.66-3

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/e01a115c-7da1-4402-bc0d-24dcd9fccb0c

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause-Internal Team

**Slack conversation:** @

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014e457d1d0adbc753</li>
        <li>Upwork Job ID: 1701835471919316992</li>
        <li>Last Price Increase: 2023-09-28</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-09-13 05:45
Reproduced:

https://github.com/Expensify/App/assets/59587260/59c315a5-e6f0-42ee-accb-79872b4fb961

Just checking in Slack about the Expected Behaviour (we shouldn't show an error, but what should happen instead?)

**Comment by kadiealexander** [comment] 2023-09-18 04:03
Not overdue.

**Comment by kadiealexander** [comment] 2023-09-21 08:19
Not overdue!

**Comment by needpower** [comment] 2023-09-21 09:29
@sobitneupane @kadiealexander Can it be a backend issue? When I go to an IOU report page, API returns `403` code:
```
POST api?command=OpenReport
```
<img width="702" alt="image" src="https://github.com/Expensify/App/assets/9203524/ad41975c-f01c-4db6-8c45-b86f9851e751">

For the comparison, the same API endpoint on IOU report page for an _existing_ user:
```
POST api?command=OpenReport
```
<img width="854" alt="image" src="https://github.com/Expensify/App/assets/9203524/4d71b84d-8fd3-41b7-bbe5-f20c97cac802">

**Comment by kadiealexander** [comment] 2023-09-25 06:26
@sobitneupane any thoughts on the above?

**Comment by sobitneupane** [comment] 2023-09-27 04:39
@kadiealexander I was unable to replicate the issue. Is this still reproducible?

**Comment by kadiealexander** [comment] 2023-10-03 21:28
Also unable to reproduce, closing.

**Closed by kadiealexander** 2023-10-03 21:28 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
