### ISSUE TITLE
[Search v2.1] - There is a Join button in the paid invoice report when accessed from Search

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#49284] opened 2024-09-16 17:02 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.35-4
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User has received invoice.

1. Go to staging.new.expensify.com
2. Log in as invoice receiver.
3. Go to invoice room.
4. Pay the invoice
5. Go to Search > Invoices.
6. Click on the paid invoice.

## Expected Result:
There will not be a Join button in the report.

## Actual Result:
There is a Join button in the paid invoice report when accessed from Search.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b53e46c4-7e6c-4b4e-bb19-c01002ced227

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @luacmartins</details>

**Comment by MuaazArshad** [comment] 2024-09-16 17:43
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a Join button in the paid invoice report when accessed from Search
### What is the root cause of that problem?
We are not checking if the invoice is open or closed.
https://github.com/Expensify/App/blob/df070b7634c28017141ccb7582c0e1e58885c063/src/pages/home/HeaderView.tsx#L296
### What changes do you think we should make in order to solve the problem?
Adding a check for open or closed invoices will resolve the issue.
https://github.com/Expensify/App/blob/df070b7634c28017141ccb7582c0e1e58885c063/src/pages/home/HeaderView.tsx#L296
```
const isOpenInvoiceReport = ReportUtils.isOpenInvoiceReport(report);
```
and
```
{!isLoading && canJoin && shouldUseNarrowLayout && isOpenInvoiceReport && <View style={[styles.ph5, styles.pb2]}>{joinButton}</View>}
```

**Comment by luacmartins** [comment] 2024-09-19 00:34
I think this might be solved by this PR https://github.com/Expensify/App/pull/49241

**Comment by johncschuster** [comment] 2024-09-19 22:03
This is on hold for https://github.com/Expensify/App/pull/49241

**Comment by luacmartins** [comment] 2024-09-20 00:18
Hmm I tried testing this again, but for some reason the invoices are not showing up on the Search page at all. @johncschuster could you try the reproducible steps in the OP as well?

**Comment by luacmartins** [comment] 2024-09-20 00:42
Actually, I spot the issue in dev and put up a PR to fix it https://github.com/Expensify/Auth/pull/12561

**Comment by luacmartins** [comment] 2024-09-23 23:36
This is fixed.

**Closed by luacmartins** 2024-09-23 23:36 UTC
Labels: Reviewing, Daily, Bug
