### ISSUE TITLE
[$250] Pay someone - Console error shows up when changing payment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#43691] opened 2024-06-13 16:41 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.83-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Pay someone.
3. Enter amount in any currency except USD, select a user and pay them.
4. Go to FAB > Pay someone.
5. Enter amount in USD and select the same user.
6. On confirmation page, click on the dropdown.
7. Choose Pay elsewhere.

## Expected Result:
No console error will show up.

## Actual Result:
Console error shows up.
[Onyx] Warning: Trying to apply "merge" with non-array type to array type in the key "nvp_private_lastPaymentMethod"

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/694fc8d9-3f84-41a3-9a6d-f004c3a25eb5

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d201b1908116ec8e</li>
        <li>Upwork Job ID: 1801295301666346552</li>
        <li>Last Price Increase: 2024-06-13</li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-06-13 16:42
Issue have been raised in adhoc build  https://github.com/Expensify/App/pull/42772#issuecomment-2156785343

**Comment by kbecciv** [comment] 2024-06-13 16:43
We think that this bug might be related to #wave-collect - Release 1

**Comment by rlinoz** [comment] 2024-06-13 19:34
Trying to reproduce this

**Comment by rlinoz** [comment] 2024-06-13 21:27
I can reliably reproduce this and it doesn't seem to crash native.

**Comment by rlinoz** [comment] 2024-06-13 21:38
New incompatibility logs were added in Onyx v2.0.35 https://github.com/Expensify/react-native-onyx/pull/532, we went from 2.0.32 to 2.0.48 https://github.com/Expensify/App/pull/42772/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R158, so that is where it is coming from, the original problem is the backend sending the `nvp_private_lastPaymentMethod` as an array on `OpenApp`.

Looking at the changes from the PR that added the logs it doesn't look like it should crash, so we should be good

**Comment by mountiny** [comment] 2024-06-14 10:21
Also QA confirmed this is not causing crashes in native https://expensify.slack.com/archives/C9YU7BX5M/p1718297508327499

**Comment by rlinoz** [comment] 2024-06-17 14:48
Moving this to weekly for now, it should be fine since it is not crashing or disrupting functionality.

**Comment by rlinoz** [comment] 2024-06-26 19:49
I have an idea on how to fix this, there is a PR in progress.

**Closed** 2024-07-12 12:22 UTC
Labels: Reviewing, Engineering, Weekly, Internal
