### ISSUE TITLE
Web - LHN - The search button is very close to the avatar

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13071] opened 2022-11-27 19:20 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Log in with any account
3. Hover over the avatar icon in multiple places

## Expected Result:
The avatar icon and the search icon must be at a sufficient distance from each other.

## Actual Result:
The avatar icon and search icon are very close to each other.

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.32.1

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/204155344-e5112e74-3677-4ff9-b096-f6725464805a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s77rt** [comment] 2022-11-27 19:40
### Proposal
```diff
diff --git a/src/pages/home/sidebar/SidebarLinks.js b/src/pages/home/sidebar/SidebarLinks.js
index 85c6de2fb2..1842af3b5d 100644
--- a/src/pages/home/sidebar/SidebarLinks.js
+++ b/src/pages/home/sidebar/SidebarLinks.js
@@ -134,6 +134,7 @@ class SidebarLinks extends React.Component {
                 <View
                     style={[
                         styles.flexRow,
+                        styles.gap1,
                         styles.ph5,
                         styles.pv3,
                         styles.justifyContentBetween,
```

### Details
Added a gap on the flew row. I used gap1 because it was the only available, maybe another greater gap value would be better.
Also the padding of the search button should be lowed to keep the same visual view (same file, line 155).

**Comment by strepanier03** [comment] 2022-11-28 22:40
From this SO: https://stackoverflow.com/c/expensify/questions/14418
- [ ] **The "bug" is actually a bug**: 
- [ ] **The bug is not a duplicate report of an existing GH (close the GH and add any novel details to the original GH instead)**: 
- [ ] **The bug is reproducible, following the reproduction steps:**
- [ ] **If you’re unable to reproduce the bug, add the _Needs reproduction_ label. Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue.**: 
- [ ] **The GH template is filled out as fully as possible -- this means the GH body and title are clear (ie. could an external contributor understand it and work on it?):** 
- [ ] **The GH was created by an Expensify employee or a QA tester:** 
- [ ] **If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification:** 
- [ ] **If there's a link to Slack, check the discussion to see if we decided not to fix it:** 
- [ ] **Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label:**

**Comment by strepanier03** [comment] 2022-11-28 22:41
Working on this now.

**Comment by strepanier03** [comment] 2022-11-28 22:59
After a discussion in Slack [here](https://expensify.slack.com/archives/C049HHMV9SM/p1669675828277539), I'm going to close this GH to focus on bug issues. This is a polish/feature request and not something we're working on now. 

We can potentially circle back to this in the future when we're in a polish stage.

**Closed by strepanier03** 2022-11-28 22:59 UTC
Labels: Daily, Bug
