### ISSUE TITLE
[HOLD for payment 2024-07-10] [$250] [Track tax] Disabled tax rate can be selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43613] opened 2024-06-12 21:26 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4623265
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- Distance rates and Taxes are enabled
- Track tax is enabled
1. Go to staging.new.expensify.com
2. Go to workspace settings > Taxes
3. Disable a tax rate
4. Go to Distance rates
5. Click on any distance rate > Tax rate
6. Select the disabled tax rate from Step 3
7. Go to workspace chat and submit a distance expense
8. Go to transaction thread

## Expected Result:
In Step 6, app should prevent the disabled tax rate to be selected, which is the Old Dot behavior

## Actual Result:
In Step 6, app allows the disabled tax rate to be selected
After submitting distance expense, it shows the "Tax no longer valid" violation

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/3aaedfc9-697a-4ae1-9109-26f6396cffd0

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b142f41c7ec7f0fd</li>
        <li>Upwork Job ID: 1801464706663931905</li>
        <li>Last Price Increase: 2024-06-14</li>
<li>Automatic offers: </li>
<ul>
<li>hungvu193 | Reviewer | 102762156</li>
<li>Krishna2323 | Contributor | 102762157</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @twisterdotcom / @stephanieelliott</details>

**Comment by lanitochka17** [comment] 2024-06-12 21:26
@stephanieelliott  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment] 2024-06-12 21:27
We think that this bug might be related to #wave-collect - Release 2

**Comment by hungvu193** [comment] 2024-06-14 07:30
Thanks for proposals everyone. I like the idea of reusing `TaxPicker` and I don't think we should hide disabled tax rate if it's selected. Because of that, I'm aligned with @Krishna2323 's [proposal here](https://github.com/Expensify/App/issues/43613#issuecomment-2163975871).
🎀 👀 🎀  C+ reviewed

**Comment by amyevans** [comment] 2024-06-14 15:54
Since I'm headed out on leave after today, I won't be around to review the PR.

This looks like polish related to the Tax Track project, so I'm going to assign to you @MonilBhavsar 🙇

**Comment by MonilBhavsar** [comment] 2024-06-17 09:54
Yes, let's fix it in TaxPicker component

**Comment by hungvu193** [comment] 2024-06-19 06:57
@Krishna2323 Do you have any ETA for the PR?

**Comment by stephanieelliott** [comment] 2024-06-27 01:47
PR was merged to Main, should go to staging next deploy.

**Comment by stephanieelliott** [comment] 2024-07-03 07:47
Applying the New Feature label to get another BZ member on this while I am OOO til July 10. To catch you up on where we are @twisterdotcom, we have a PR, it was merged to main last week and should be deployed to staging soon: https://github.com/Expensify/App/pull/44046

Thanks for watching over this, I'll grab it back from you when I return!

**Comment by twisterdotcom** [comment] 2024-07-03 08:54
Easy peasy. I'm actually also out next week, so this will be pinged around a bit.

**Comment by stephanieelliott** [comment] 2024-07-10 19:01
Hey @hungvu193 can you complete the NZ checklist please?

**Comment by stephanieelliott** [comment] 2024-07-10 19:04
Summarizing payment on this issue: 

 - Contributor: @Krishna2323 $250 via Upwork PAID 
 - Contributor+: @hungvu193 $250 via Upwork PAID 
 
 Upwork job is here:  https://www.upwork.com/jobs/~01b142f41c7ec7f0fd

**Comment by hungvu193** [comment] 2024-07-11 04:18
- [x] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/42141
- [x] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: https://github.com/Expensify/App/pull/42141/files#r1673377848
- [x] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] Determine if we should create a regression test for this bug: No
This is new feature and was recently added so I don't think we need regression test for this one.

**Closed** 2024-07-11 22:20 UTC
Labels: External, Daily, Awaiting Payment, Bug
