### ISSUE TITLE
[HOLD for payment 2024-03-18] [$500] Public room - Sign-in modal is hidden behind welcome modal after selecting an option

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#35131] opened 2024-01-25 06:35 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-2
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
1. Log out if logged in.
2. Navigate to public room https://staging.new.expensify.com/r/2376199970894587

3. Select any option in the welcome message modal.
## Expected Result:
Welcome modal will dismiss and sign-in modal will appear after selecting an option.

## Actual Result:
The link changes to sign-in URL, but the welcome modal does not dismiss and the sign-in modal is hidden behind it.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/43996225/eb1acbbb-aa70-4234-81e9-bb7a4b5cd596

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bdb196958ade050b</li>
        <li>Upwork Job ID: 1752411868444123136</li>
        <li>Last Price Increase: 2024-02-27</li>
<li>Automatic offers: </li>
<ul>
<li>fedirjh | Reviewer | 0</li>
<li>dukenv0307 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kevinksullivan</details>

**Comment by s-alves10** [comment] 2024-01-25 08:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Sign-in modal is hidden behind welcome modal after selecting an option in public room

### What is the root cause of that problem?

We have recently introduced full screen engagement modal named [PurposeForUsingExpensifyModal](https://github.com/Expensify/App/blob/main/src/components/PurposeForUsingExpensifyModal.tsx)

We pass `onPress` handler to the [MenuItem](https://github.com/Expensify/App/blob/main/src/components/MenuItem.tsx) here
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/components/PurposeForUsingExpensifyModal.tsx#L123

When selecting an option, we redirect to the sign-in modal if the user is not signed in
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/components/MenuItem.tsx#L381
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/libs/actions/Session/index.ts#L134-L139

So menu item's `onPress` handler isn't executed at all.
This is the root cause

### What changes do you think we should make in order to solve the problem?

We can listen navigation state and hide the engagement modal if needed
We show this modal on mount here
https://github.com/Expensify/App/blob/0d0b0a8c9b073c30a9b54de15066789d17f7c718/src/components/PurposeForUsingExpensifyModal.tsx#L91-L101

We can add navigation listener here
```
    useEffect(() => {
        ~  ~  ~
        Welcome.show(routes, () => setIsModalOpen(true));
        return navigation.addListener('state', (event) => {
            const state = event.data.state;
            const route = state.routes[state.index];
            if (route.name === currentRoute.name) {
                return;
            }
            setIsModalOpen(false);
        });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
```

We compare the route's name to determine if we need to hide the modal in the above solution. We can use more optimized or suitable comparison

The solution works as expected

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/277fb14b-3d6a-4a87-9792-bf59e2485628


</details>

### What alternative solutions did you explore? (Optional)

**Comment by thienlnam** [comment] 2024-01-25 08:38
Interesting - will wait to let @stitesExpensify chime in. We'll definitely want to fix this soon, though I don't think this needs to block deploy. This relies on engaging with us from a public room and if you dismiss the screen you'll see the sign in screen

**Comment by stitesExpensify** [comment] 2024-01-25 18:26
@MitchExpensify what do you think the intended functionality should be here? I'm thinking that we don't show the engagement modal at all to anonymous users both before and after they sign in. Thoughts?

**Comment by MitchExpensify** [comment] 2024-01-28 03:07
> I'm thinking that we don't show the engagement modal at all to anonymous users both before and after they sign in. Thoughts?

For sure, yes! Lets not show the modal to anonymous users before they sign in

**Comment by mvtglobally** [comment] 2024-02-13 04:57
Issue not reproducible during KI retests. (First week)

**Comment by marcaaron** [comment] 2024-02-16 00:44
I closed it because QA reported it as not reproducible.

**Comment by marcaaron** [comment] 2024-02-16 03:14
Asking for re-test

**Comment by mvtglobally** [comment] 2024-02-16 03:48
Seeing Sign in modal now https://github.com/Expensify/App/assets/43995119/23f1ad8c-fde5-4435-8245-a96f6a97e551

**Comment by mvtglobally** [comment] 2024-02-16 04:14
and on Web
https://github.com/Expensify/App/assets/43995119/39deff4c-bb73-44ae-aa2e-42b38c7a1e96

**Comment by marcaaron** [comment] 2024-02-16 19:03
Cool I'll reopen then.

**Comment by kevinksullivan** [comment] 2024-02-22 19:13
Proposals still in review

**Comment by marcaaron** [comment] 2024-02-27 02:43
Heads up I just made this external again because I have higher priority issues that I need to work on and it seems like we are close to a solution. @fedirjh can you please address the comments above from @dukenv0307? Thanks everyone.

**Comment by godofoutcasts94** [comment] 2024-02-27 02:50
Is this issue open to proposals ?

**Comment by marcaaron** [comment] 2024-02-28 21:31
Bump @fedirjh

**Comment by marcaaron** [comment] 2024-02-29 01:53
It's a personal policy that gets returned. I am not familiar with how anonymous accounts work so it would be good to get @marcochavezf's opinion here.

I want to say that anonymous accounts can't really do much - like anything you'd need a personal policy for - you probably can't do, but there is probably some reason it is included that we are not seeing.

**Comment by marcochavezf** [comment] 2024-03-01 20:19
Every account is created with a personal policy, including anonymous accounts since they're regular accounts with some restrictions. What problem is causing the anonymous account's personal policy?

**Comment by marcaaron** [comment] 2024-03-04 18:16
The conversation about not sending the personal policy from the backend has confused everything a bit. If the end goal is that we don't want to show this modal for anonymous users then we can just check if they are an anonymous user and then don't show the modal. Assigning @dukenv0307.

**Comment by marcaaron** [comment] 2024-03-04 18:19
>Do not show engagement modal for anonymous users, we can update [here](https://github.com/Expensify/App/blob/19ca917fb83fed0c5b34e5fac83e98976bf095dd/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L49) to early return if Session.isAnonymousUser() is true

Let's just do this.

>or we can connect to the SESSION key to the BottomTabBar and use the session?.authTokenType to detect anonymous user, to make sure the block is rerun again when the session auth type changes.

What is the advantage of doing this? Let's do the first one I think.

>If we don't want to show the engagement modal even after the anonymous user logs in, we can make sure to set isFirstTimeNewExpensifyUser to true and send back from the back-end after the user signs in successfully. Or we can do this in client side (if the user is anonymous) when the user begins the sign in API request in optimisticData and successData.

👎  - I don't really understand what problem we are trying to solve. Let's fix "sign in modal is hidden behind welcome modal".

>If instead we want to show the engagement modal after the anonymous user logs in, we have to make sure to remove the policies of the anonymous user in successData after the the user signs in (or the back-end can clear it in Onyx data when returning response). So that [this logic](https://github.com/Expensify/App/blob/c5ca9a810b529cdc8b8fceb179e9cfc01061355a/src/libs/actions/Welcome.ts#L171) will work correctly, otherwise there'll be 2 policies (1 of the signed in user and 1 of the anonymous user) and the engagement modal will not show.

Again - not too sure what problem we are trying to solve. We agreed to not show them this modal.

**Comment by mvtglobally** [comment] 2024-03-05 04:50
Issue not reproducible during KI retests. (Second week)

**Comment by marcaaron** [comment] 2024-04-10 01:40
Bumping this one.

**Comment by kevinksullivan** [comment] 2024-04-11 20:51
Sorry for the delay here, all set.

**Closed by kevinksullivan** 2024-04-11 20:51 UTC
Labels: External, Engineering, Daily, Overdue, Awaiting Payment, Bug
