### ISSUE TITLE
[$500] IOU - In distance request confirmation page, location access permission box is shown.

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36491] opened 2024-02-14 14:32 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.41
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4314136
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre:condition: device location is off
1. Launch app
2. Tap on workspace chat
3. Tap plus icon --- request money---distance
4. Tap no, thanks and deny device location permission
5. Tap start
6. Tap use location
7. Tap no, thanks and deny device location permission
8. Tap cross button and close the device location denied message
9. Select a location from dropdown list
10. Tap finish
11. Perfom step 6-- step9
12. Tap add stop
13. Perfom step 6-- step9
14. Tap next

## Expected Result:
In distance request confirmation page, location access permission box must not be shown

## Actual Result:
In distance request confirmation page, location access permission box is shown

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a2cc00b7-a8a3-4998-a2ce-f7f198221b48

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01898dd3cbc3df8779</li>
        <li>Upwork Job ID: 1757774834158333952</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
<li>esh-g | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment] 2024-02-14 14:33
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by esh-g** [comment] 2024-02-14 14:40
# Proposal

## Root cause
The root cause is that we try to get the current position of the user for every render for `MapView` even if we don't need it in this `useEffect` here:
https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/components/MapView/MapView.tsx#L46

## Solution
We should only try to get the current location of the user if `shouldPanMapToCurrentLocation` is `true`
https://github.com/Expensify/App/blob/2e3840f2f94934b7937e9953133b32b1e3e81566/src/components/MapView/MapView.tsx#L68

**Comment by bernhardoj** [comment] 2024-02-14 16:14
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In distance confirmation page, a location permission dialog shows.

### What is the root cause of that problem?
The map view component has a `useFocusEffect` that will be triggered every time the page is focused.
https://github.com/Expensify/App/blob/9b7e31073f94c4c19ae9389402e28f1c6ff55d6e/src/components/MapView/MapView.tsx#L35-L46

It will call `getCurrentPosition` which will request the location permission. The map view is also placed on the confirmation page, so when we visit the confirmation page, the permission dialog will be shown (no need to perform the long step).

### What changes do you think we should make in order to solve the problem?

I think we don't need to get the current position anymore on the confirmation page, so we can introduce a new prop to ignore the `getCurrentPosition` call and set the current position from the `initialState`.

```
if (useInitialStatePosition) {
    setCurrentPosition({longitude: initialState.location[0], latitude: initialState.location[1]});
    return;
}
```

**Comment by s77rt** [comment] 2024-02-15 01:28
@esh-g Thanks for the proposal. Your RCA is about right. The solution looks good to me.

🎀 👀 🎀 C+ reviewed
[Link to proposal](https://github.com/Expensify/App/issues/36491#issuecomment-1943937917)

**Comment by s77rt** [comment] 2024-02-15 01:28
@bernhardoj Thanks for the proposal. Your RCA is about right. As for the solution, I don't think we need a new prop here

**Comment by chiragsalian** [comment] 2024-02-15 21:46
Proposal sounds good to me, feel free to create the PR @bernhardoj.

**Comment by esh-g** [comment] 2024-02-16 03:01
@chiragsalian I think @s77rt recommended my proposal instead... could you please double check your decision?

**Comment by esh-g** [comment] 2024-02-16 16:59
Gentle bump @chiragsalian @s77rt

**Comment by chiragsalian** [comment] 2024-02-16 18:02
Thanks for quickly bringing that to my attention. I've gone ahead and reassigned the issue to you @esh-g.

**Comment by esh-g** [comment] 2024-02-17 15:06
PR is here: https://github.com/Expensify/App/pull/36761
cc @s77rt

**Comment by kevinksullivan** [comment] 2024-02-21 23:03
PR merged! Waiting on deploy.

**Comment by chiragsalian** [comment] 2024-03-12 19:29
Oh true, its been live since feb 28th so this is past the 7 day regression period. I'm unsure why the GH title didn't change here. Might have been a bug.
I don't think anything is pending here. 
@kevinksullivan can you handle the payment and close out this issue.

**Comment by s77rt** [comment] 2024-04-05 19:24
This is due payment

**Comment by chiragsalian** [comment] 2024-04-09 22:16
Friendly bump @kevinksullivan, to handle payment.

**Comment by s77rt** [comment] 2024-06-06 20:39
Only Melvin got paid. This is still due payment

**Comment by chiragsalian** [comment] 2024-06-10 22:21
@kevinksullivan / @mallenexpensify, can one of you handle payment for @s77rt over here.

**Comment by mallenexpensify** [comment] 2024-06-11 02:15
Contributor: @esh-g  paid $500 via Upwork
Contributor+: @s77rt paid $500 via Upwork. 

 Sorry it took _forever_.  If you ever see a `Reviewing` label on an issue when it's awaiting payment, please comment and ask for it to be removed

**Closed** 2024-06-11 02:15 UTC
Labels: External, Monthly, Not a priority, Bug
