### ISSUE TITLE
Scan - Request shows empty thumbnail with "Scan in progress" when created and edited offline

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36155] opened 2024-02-08 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat
3. Go offline
4. Create a scan request
5. Go to request details page
6. Manually enter amount and merchant
7. Delete the receipt
8. Go online
9. Wait for the page to update
10. Go to expense report

## Expected Result:
The request will not display receipt thumbnail and "Scan in progress" as the receipt is removed and the details are manually added

## Actual Result:
The request displays empty thumbnail with "Scan in progress"

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c7643a0c-1634-42e8-8449-8e679730321d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by lanitochka17** [comment] 2024-02-08 15:09
We think that this bug might be related to #wave5
CC @dylanexpensify

**Comment by shahinyan11** [comment] 2024-02-08 15:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Scan - Request shows empty thumbnail with "Scan in progress" when created and edited offline
### What is the root cause of that problem?
The image is downloaded from the server . We are unable to display an image using a live URL in offline mode.
### What changes do you think we should make in order to solve the problem?
We should add a new feature to download images and save them locally for offline display.

### What alternative solutions did you explore? (Optional)
Use a default icon/image to display instead of the original image when the user is offline.

**Comment by paultsimura** [comment] 2024-02-08 15:38
This should be handled in https://github.com/Expensify/App/issues/34601

**Comment by zanyrenney** [comment] 2024-02-14 17:37
Closing as this is handled in the issue linked above: https://github.com/Expensify/App/issues/34601

**Closed by zanyrenney** 2024-02-14 17:37 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
