### ISSUE TITLE
[HOLD for payment 2024-01-15] [$500] #focus - Task assigned to self when cancelled and read is still displayed in LHN in focus mode

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#33315] opened 2023-12-19 21:38 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.14-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is in #focus mode
1. Go to 1:1 DM
2. Create a task and assign it to yourself
3. Open the task report
4. Click 3-dot menu > Cancel
5. Go to a different chat

## Expected Result:
The task will be removed from LHN because it is read and cancelled

## Actual Result:
The cancelled task is still in LHN despite in focus mode

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/e574e140-6d82-4345-a00b-ad98ca6cbe5f

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c072d4cdc2fc1985</li>
        <li>Upwork Job ID: 1737225810182053888</li>
        <li>Last Price Increase: 2023-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28072966</li>
<li>DylanDylann | Contributor | 28072967</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @anmurali</details>

**Comment by abzokhattab** [comment] 2023-12-19 22:22
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Cancelled tasks that are read before are not hidden in focus mode 


### What is the root cause of that problem?

we use this function to indicate report is an open task report assigned to current user then it should be shown  however we dont check if its cancelled.

https://github.com/Expensify/App/blob/e6557aec583bfe3654b9977ef92fd33073100d03/src/libs/ReportUtils.ts#L1575-L1577



 
### What changes do you think we should make in order to solve the problem?
add a check that the task is not archeived
```js 
/**
 * Checks if a report is an open task report assigned to current user.
 *
 * @param [parentReportAction] - The parent report action of the report (Used to check if the task has been canceled)
 */
function isWaitingForAssigneeToCompleteTask(report: OnyxEntry<Report>, parentReportAction: OnyxEntry<ReportAction> | EmptyObject = {}): boolean {
    return isTaskReport(report) && isReportManager(report) && isOpenTaskReport(report, parentReportAction) && !isArchivedRoom(report);
}

```

**Comment by DylanDylann** [comment] 2023-12-20 04:45
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The cancelled task is still in LHN despite in focus mode

### What is the root cause of that problem?
after cancelling task the pusher return taskReport.isDeletedParentAction === true . But we don't add this field in this function
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/libs/SidebarUtils.ts#L232

### What changes do you think we should make in order to solve the problem?
in this function
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/libs/SidebarUtils.ts#L232

we should return  `isDeletedParentAction`
```
    result.isDeletedParentAction = report.isDeletedParentAction;

```

We also need to do the same thing in the chat report selector here
https://github.com/Expensify/App/blob/7f7cfb318bdb073cbaf478843255c2d5f9423d12/src/pages/home/sidebar/SidebarLinksData.js#L170
should add
```
        isDeletedParentAction: report.isDeletedParentAction

```

My solution also resolves the bug mentioned [here](https://github.com/Expensify/App/issues/30798#issuecomment-1853461316)
cc @waterim 

### What alternative solutions did you explore? (Optional)


### Result



https://github.com/Expensify/App/assets/141406735/b955c9af-5f13-4131-a62f-aba9c87938bf

**Comment by waterim** [comment] 2023-12-20 15:30
I tested the proposal from @DylanDylann in [here](https://github.com/Expensify/App/issues/30798#issuecomment-1856018900) and it works fine!

**Comment by alitoshmatov** [comment] 2023-12-29 18:27
@abzokhattab Thank you for your proposal, I don't think your proposal correctly points out the root cause and tries to fix it with a workarounds. You are not showing why `parentReportAction` is not present in this specific case.

**Comment by alitoshmatov** [comment] 2023-12-29 18:33
@DylanDylann Thank you for your proposal. You have correct RCA. I do agree with you solution and it is straightforward. 
I think we should hold, since both of the issues seem to have same root cause and could be resolved by a single solution.

@DylanDylann 's [proposal](https://github.com/Expensify/App/issues/33315#issuecomment-1863837310) looks good. 

C+ reviewed 🎀 👀 🎀

**Comment by alitoshmatov** [comment] 2023-12-29 19:19
@abzokhattab We can assume that is expected behavior since new issue was created https://github.com/Expensify/App/issues/33477

**Comment by DylanDylann** [comment] 2024-01-02 08:07
@alitoshmatov The PR is ready for review: https://github.com/Expensify/App/pull/33828

**Comment by mountiny** [comment] 2024-01-10 19:25
was merged to production

**Comment by mountiny** [comment] 2024-01-10 19:26
$500 to @alitoshmatov and to @DylanDylann

**Comment by anmurali** [comment] 2024-01-22 22:57
@alitoshmatov and @DylanDylann are paid.

**Closed by anmurali** 2024-01-22 22:57 UTC
Labels: External, Daily, Overdue, Awaiting Payment, Bug
