### ISSUE TITLE
[HOLD for payment 2022-12-20] [$1000] [Feature] Update the chat UI to reflect drag-and-drop update ability

### ISSUE THREAD

**Issue by roryabraham** [Expensify/App#11823] opened 2022-10-13 20:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
Drag an image file over a chat

## Expected Result:
1. The cursor should change to be a green `+`
1. The UI of the chat should update to reflect that you can drop the file in there and it will be uploaded

## Actual Result:
1. The cursor changes to be a green `+` ✅ 
1. The UI of the chat does not update to reflect that you can drop the file in there and it will be uploaded ❌ 

## Workaround:
n/a – this is polish to make an existing feature more intuitive.

## Platform:
Where is this issue occurring?

- Web
- Desktop App

There is no concept of drag-and-drop on iOS, Android, mWeb, so this is a feature request for web and desktop only.

**Version Number:** 1.2.14-0
**Notes/Photos/Videos:** 

This is how the feature looks in slack:

![image](https://user-images.githubusercontent.com/47436092/195705074-591081c1-d99e-47ed-ad14-d64178dc3447.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1665684156253079

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by roryabraham** [comment] 2022-10-13 20:35
Bringing in @shawnborton for the mockups, then we can make this external.

**Comment by JmillsExpensify** [comment] 2022-10-13 22:20
I think this was mentioned in the Slack thread, but we should think about what happens if someone tried to drag and drop over the LHN. Do we block that entirely? Do we highlight the individual row that is hovered over? I agree with @roryabraham that the chat window itself should be very straightforward, especially since we don't have threads and a right-docked side modal for reports yet.

**Comment by Christinadobrzyn** [comment] 2022-10-14 04:20
User example of this behaviour - user is trying to drag & drop a doc for bank verification and it's creating an expense instead. https://github.com/Expensify/Expensify/issues/233722

**Comment by shawnborton** [comment] 2022-10-14 16:38
@JmillsExpensify for now I would suggest we just block the drag and drop action over the LHN, and only show feedback if the main chat pane is hovered. Will share screens shortly.

**Comment by shawnborton** [comment] 2022-10-14 16:52
Added a quick mock to the Slack thread, but here it is too:

![image](https://user-images.githubusercontent.com/2319350/195900474-454285c2-ca2f-4023-8133-602fc2d71d64.png)

**Comment by roryabraham** [comment] 2022-10-14 18:11
Cool, design LGTM let's get an upwork job created for this, then we can start accepting proposals.

**Comment by parasharrajat** [comment] 2022-10-14 18:18
Calling all proposals...lol

**Comment by roryabraham** [comment] 2022-10-14 18:37
> for now I would suggest we just block the drag and drop action over the LHN, and only show feedback if the main chat pane is hovered.

Quick clarification – I'm going to ask that we display the `no-drop` cursor style if you drag a file into the app anywhere where it's not allowed, which for now should include the whole LHN

**Comment by parasharrajat** [comment] 2022-10-14 18:51
And the report header as well. This is the default behavior of the browser. We are only listening for drop over report body and composer

**Comment by vladamx** [comment] 2022-10-16 01:11
**Proposal**

The idea is to detect if dragging over dropzone is active and to use React Portal to render the overlay in the drop view.

You can check the code in the diff below.
https://github.com/Expensify/App/compare/main...vladamx:App:vladamx-proposal-11823-drag-and-drop-overlay?expand=1

@parasharrajat 
This should get you a good idea on the strategy.

Details like adding the document icon from design, extracting the overlay to separate file etc ; will be a part of PR

**Outcome:**

Chrome/ Web

https://user-images.githubusercontent.com/11381171/196013232-a1da08b4-6c9d-4678-b723-6a89445fb042.mp4

Desktop

https://user-images.githubusercontent.com/11381171/196013221-59bc0681-7b0e-4abd-aa82-5dd4c2ed1252.mp4

**Comment by maddylewis** [comment] 2022-10-16 16:07
created job posting here - https://www.upwork.com/jobs/~0198538cbc40aff5b9

**Comment by parasharrajat** [comment] 2022-10-16 17:50
@vladnyk Why do we need to create a portal? Is it possibile to keep the drop UI in the `ReportScreen`?

Pasting code diff is not considered a good proposal. Please explain your changes in the proposal itself.

**Comment by vladamx** [comment] 2022-10-16 22:12
@parasharrajat

isDraggingOverState is inside ReportActionCompose and dragging listener is inside Composer. 

In order to not introduce shared state or change existing code architecture much, we create portal in order to mount the overlay inside View with id = CONST.REPORT.DROP_NATIVE_ID which is inside ReportScreen.

Please let me know if you need more details.

**Comment by parasharrajat** [comment] 2022-10-17 14:19
Could you please explain your changes here on the proposal? 

--- 
1. Technically, we should be able to listen to drop over on the ReportScreen and show the UI. 
2. Composer can continue listening to the drag-drop events and act as it is doing now.

**Comment by vladamx** [comment] 2022-10-17 15:26
Yes, but i am not sure why would you duplicate logic for detecting drop in Report Screen as well?

**Comment by parasharrajat** [comment] 2022-10-17 16:11
I don't think it will duplicate the logic. Reportscreen's task would be to show the UI and Composer's to handle the file. Listening to drop events is not duplicate work. 

> Could you please explain your changes here on the proposal?

But haven't reviewed your solution completely.

**Comment by vladamx** [comment] 2022-10-17 19:46
Okay. I will try to break it down.

First,in the Composer, we make adjustment in the dragging listener to not fire events for every child in the drop zone therefore creating needless events -> re-renders causing the overlay to blink. Additionally, we block drop outside the drop zone with none drop effect.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/11381171/196265363-c85b2de6-6841-4e6d-a88b-7493eac9f69d.png">

Next, in ReportActionCompose we use already existing isDraggingOver state to mount the DropZoneOverlay which is a portal to the View with id CONST.REPORT.DROP_NATIVE_ID which is  higher in the hierarchy in order to display upload Overlay which is just a view with absolute positioning and icon + text content

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/11381171/196268510-7accb6ec-ee3f-4a6d-9cbd-d93d073b64db.png">

Thats all there is to it.

The benefit of this approach is that we don't introduce new state and new re-renderings higher up in the hierarchy -> app stays performant.

Detecting drag in ReportScreen would require new isDraggingOver state and new ReportScreen re-renderings needlessly, plus repeated logic for detecting the drag.

**Comment by parasharrajat** [comment] 2022-10-17 20:34
> Additionally, we block drops outside the drop zone with no drop effect.

is this needed for this issue? I wouldn't mind leaving the default behavior for areas where we don't control the drag and drop. 

To prevent `dragEnter` and `dragleave` from firing multiple times, I will suggest, checking if the target which is being entered or left is `CONST.REPORT.DROP_NATIVE_ID` instead of the increment counter. is it guaranteed that `entered node === exit node`? 

We don't need the `isOriginComposer` anymore as the whole view being covered with the new UI now. 

I would leave the `preventDefault` limited to only necessary events.

the Dragging UI elements can be grouped into one component say `ReportDropUI` and used inside the reportActionCompose. 


Optionally, we can also refactor the whole drag-and-drop code and move that inside the new `ReportDropUI`.

**Comment by vladamx** [comment] 2022-10-17 22:16
> Is this needed for this issue? I wouldn't mind leaving the default behavior for areas where we don't control the drag and drop.

Its not needed per say, but i think its much better since default behaviour would just open the file in the new tab therefore leaving the context of the app, which is annoying IMO.

> I would leave the preventDefault limited to only necessary events.

This is connected to the drop_effect_none; so if we want that, we need to preventDefault at the beginning  of the listener. Otherwise, we can leave it like it was before

> We don't need the isOriginComposer anymore as the whole view being covered with the new UI now.

Agreed.

> the Dragging UI elements can be grouped into one component say ReportDropUI and used inside the reportActionCompose.

Agreed.

> To prevent dragEnter and dragleave from firing multiple times, I will suggest, checking if the target which is being entered or left is CONST.REPORT.DROP_NATIVE_ID instead of the increment counter. is it guaranteed that entered node === exit node?

The problem is exactly that you can't do this since CONST.REPORT.DROP_NATIVE_ID has multiple child views and for each child view drag enter and drag leave are generated causing a lot of needless events. There are various workarounds for this issue. I found the counter most intuitive.

**Comment by parasharrajat** [comment] 2022-10-18 11:11
> The problem is exactly that you can't do this since CONST.REPORT.DROP_NATIVE_ID has multiple child views and for each child view, drag_enter and drag_leave are generated causing a lot of needless events. There are various workarounds for this issue. I found the counter most intuitive.

I was suggesting that we check if the entered node is the same as `CONST.REPORT.DROP_NATIVE_ID`, only the call the `onDragenter` and so on for the leave event. That seems like a better approach to me. 

Can you please share something where I can read about the `counter` based approach?

**Comment by vladamx** [comment] 2022-10-18 13:10
> I was suggesting that we check if the entered node is the same as CONST.REPORT.DROP_NATIVE_ID, only the call the onDragenter and so on for the leave event. That seems like a better approach to me.

Yes, its cleaner but it does not work; For dragleave, you can not apply !== CONST.REPORT.DROP_NATIVE_ID because it will keep firing for child elements.

Related read for the discussion: 
https://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element

I checked, and it actually works on Firefox now as well.

Alternative approaches like pointer events none seems like an overkill.

**Comment by parasharrajat** [comment] 2022-10-18 13:12
Thanks for sharing. I will go though it and then decide.

**Comment by parasharrajat** [comment] 2022-10-19 16:56
Ok, I think we can proceed with the @vladamx's [proposal](https://github.com/Expensify/App/issues/11823#issuecomment-1279864525). 

cc: @roryabraham 

:ribbon: :eyes: :ribbon:  C+ reviewed

**Comment by parasharrajat** [comment] 2022-10-19 17:00
@shawnborton Could you please share the assets for the task and tell us what is the font size for the `Drop to upload` ?

**Comment by roryabraham** [comment] 2022-10-19 22:51
Okay, I'm a little concerned that the solution will not work cross-platform because of the use of `ReactDOM.createPortal`, but @vladamx has acknowledged that ensuring that there are no mobile regressions in the PR is part of the scope, so that resolves my concern.

**Comment by vladamx** [comment] 2022-10-20 14:10
PR should be up by Friday 21.10.2022

**Comment by vladamx** [comment] 2022-10-20 16:46
@parasharrajat 

I invested slightly more effort to come with a cleaner solution for drag detection.

The implementation is using state machine based approach to detect drags on drop zone. 

It also improves performance of existing dragging solution and only re-renders the composer when it is needed. No duplicate events.

https://github.com/Expensify/App/compare/main...vladamx:App:vladamx-proposal-11823-drag-and-drop-overlay?expand=1

**Comment by parasharrajat** [comment] 2022-10-20 17:03
Then, I would say just remove the drag-and-drop logic out of the composer. Now it seems like not related to anything of the composer.

**Comment by JmillsExpensify** [comment] 2022-10-20 17:42
I agree with @parasharrajat. Now it's the total area of the chat window, of which the composer is just one part.

**Comment by vladamx** [comment] 2022-10-20 21:06
@parasharrajat @JmillsExpensify 

Please guys, lets leave that state ehere it is now, its good performance wise.

I can move the logic in separate file but lets leave state in the composer.

**Comment by vladamx** [comment] 2022-10-21 14:42
PR is up https://github.com/Expensify/App/pull/12056

**Comment by roryabraham** [comment] 2022-10-31 16:48
Just reviewed the PR again. I think a budget adjustment might be in order. Overall I'm not super comfortable with our direct use of react-dom, and would like to see us switch to a cross-platform alternative

**Comment by vladamx** [comment] 2022-10-31 18:00
@roryabraham  On it.

**Comment by roryabraham** [comment] 2022-11-04 19:48
Thanks for your flexibility in making those changes, @vladamx. Let's keep pushing the PR forward, I just reviewed it again.

@maddylewis can we bump the budget for this up to $1000 plz?

**Comment by maddylewis** [comment] 2022-11-07 14:48
updated budget here - https://www.upwork.com/jobs/~0198538cbc40aff5b9

**Comment by parasharrajat** [comment] 2022-11-07 22:02
Reviewed today.

**Comment by maddylewis** [comment] 2022-11-16 13:52
how are things looking here? @parasharrajat - are you able to provide an update? ty!

**Comment by parasharrajat** [comment] 2022-11-16 14:01
PR is in review.

**Comment by roryabraham** [comment] 2022-11-22 09:37
PR is still in review, but looks like it's almost ready for merge.

**Comment by parasharrajat** [comment] 2022-11-28 11:20
PR is awaiting a story to be added.

**Comment by parasharrajat** [comment] 2022-12-01 14:03
We are giving the finish touches to the PR for the new theme. I guess it will be merged today.

**Comment by roryabraham** [comment] 2022-12-07 19:51
PR merged. I think the correct payout for this is:

- $1000 base
- Additional $250 for storybook stories: https://github.com/Expensify/App/pull/12056#issuecomment-1326726986
- Additional $500 that I'd like to authorize because the PR had a fair amount of scope creep, took a long time, and was working on shifting tides of the changing theme. @vladamx was flexible and persistent throughout the process, and I think that should be rewarded.

So $2000 total

**Comment by vladamx** [comment] 2022-12-07 19:54
@roryabraham That's fair, thank you!

**Comment by maddylewis** [comment] 2022-12-08 17:19
just noting here that i've seen this comment (https://github.com/Expensify/App/issues/11823#issuecomment-1341508864) and will get this paid out before EOW.

**Comment by maddylewis** [comment] 2022-12-08 17:36
@roryabraham - will you confirm if we're paying out $1750 to both the C and C+ on this one?

**Comment by francoisl** [comment] 2022-12-09 18:13
In addition, I wanted to confirm - what's the expected behavior if you try to drag and drop a file while the right-hand panel is open? 

The QA team opened [this issue](https://github.com/Expensify/App/issues/13458) but it kinda makes sense to me not to allow drag-and-dropping a file in this case (or that would mean you'd want to drag and drop in the RHP?)

https://user-images.githubusercontent.com/93399543/206595900-f1ae405f-f33f-4c90-a3c7-efaaf89528fc.mp4

**Comment by francoisl** [comment] 2022-12-09 18:45
Thanks, works for me and I agree with you here.

**Comment by maddylewis** [comment] 2022-12-12 00:46
im sorry for the delay on payment - will get this processed tomorrow.

**Comment by vladamx** [comment] 2022-12-12 23:40
@maddylewis i think we made a mistake with payment. I received 1750 + 1000 and i think i should receive only 1750 for this job

**Comment by maddylewis** [comment] 2022-12-13 14:00
uh oh! thanks for saying something @vladamx. is there a way in Upworks for you to reject the $1000 payment? i will also look into this on my end.

**Comment by maddylewis** [comment] 2022-12-13 14:03
@parasharrajat - will you confirm the payment you're expecting for this issue? thanks!

**Comment by vladamx** [comment] 2022-12-13 14:20
@maddylewis Hm, i don't seem to have that option. Maybe you can contact their support. Transactions are still in pending so they might be able to cancel $1000 transaction.

I can confirm that i received the payment for this issue.

**Comment by maddylewis** [comment] 2022-12-13 14:30
it sounds like i can request a refund. i will get on that. thanks again for letting me know, Vlad!

**Comment by vladamx** [comment] 2022-12-13 17:33
@maddylewis i edited a refund to be 1000.
You should receive 900. 100 is service fee

**Comment by mallenexpensify** [comment] 2022-12-26 17:05
Pretty sure this can be closed.  Reopen and/or comment if not

**Closed by mallenexpensify** 2022-12-26 17:05 UTC
Labels: Reviewing, External, Daily, NewFeature, Design, Awaiting Payment
