### ISSUE TITLE
[$500] IOU - On refreshing page, it displays only new currency & amount is not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35103] opened 2024-01-24 21:06 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.31-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4234954
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap fab---- Request money
3. Tap currency
4. Select a currency
5. Enter an amount
6. Refresh the page

## Expected Result:
On refreshing page, it must display default currency with no amount entered as new BNP page or it must show new currency selected with amount shown

## Actual Result:
On refreshing page, it displays only new currency & amount is not displayed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>  

https://github.com/Expensify/App/assets/78819774/4d5a0808-f20d-4603-b625-d23e37134085

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019467036fc994e587</li>
        <li>Upwork Job ID: 1750263866110803968</li>
        <li>Last Price Increase: 2024-01-24</li>
    </ul>
</details>

**Comment by samilabud** [comment] 2024-01-24 21:13
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 IOU - On refreshing page, it displays only new currency & amount is not displayed

### What is the root cause of that problem?
We are not persisting (In Onyx) the last selected currency.

### What changes do you think we should make in order to solve the problem?
We should add the last currency selected to our Onyx db, and checking for that when page load if not exist take the default currency.

**Comment by s-alves10** [comment] 2024-01-24 22:06
Is this a bug?

**Comment by conorpendergrast** [comment] 2024-01-25 14:18
[Checking behaviour via Slack](https://expensify.slack.com/archives/C03U7DCU4/p1706192219645679) (internal channel). [The regression test](https://expensify.testrail.io/index.php?/tests/view/4234954) doesn't suggest which behaviour is correct, so I'm not convinced that this is a bug (it may be a feature request!)

**Comment by conorpendergrast** [comment] 2024-01-29 11:24
I've bumped [my question in the internal Slack channel](https://expensify.slack.com/archives/C03U7DCU4/p1706192219645679)

**Comment by conorpendergrast** [comment] 2024-01-30 13:33
From Slack, it does seem like an advantage to persist the currency AND amount that was selected before a page refresh. However, I think that the regression test doesn't clearly show that this is what's expected. 

As a result, I think that this is a feature request, and I'm closing - it's not a core strategic change. If I'm wrong, comment!

**Closed by conorpendergrast** 2024-01-30 13:33 UTC
Labels: External, Weekly, NewFeature, Help Wanted, Bug
