### ISSUE TITLE
[$250] Android - Scan - In review duplicates, tapping "keep all" app crashes

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46711] opened 2024-08-02 12:01 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.16-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4801447
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Login as [applausetester+pendingreceipt@applause.expensifail.com](mailto:applausetester+pendingreceipt@applause.expensifail.com)
3. Tap on Do not delete - pending receipt chat
4. Create 2 scanned expense with same valid receipt so that scan will be successful
5. Tap on the preview
6. Open one of the expense
7. Tap review duplicates in header
8. Tap "keep all" in header

## Expected Result:
In review duplicates, tapping "keep all" app must not crash

## Actual Result:
In review duplicates, tapping "keep all" app crashes

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/92325e67-52fe-43e4-a553-35956b90dc17

[logs (2).txt](https://github.com/user-attachments/files/16470121/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017ea914a2c756b016</li>
        <li>Upwork Job ID: 1822889161149535059</li>
        <li>Last Price Increase: 2024-09-16</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alitoshmatov</details>

**Comment by lanitochka17** [comment] 2024-08-02 12:01
@RachCHopkins  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by RachCHopkins** [comment] 2024-08-07 00:36
Duplicate detection is part of #vip-control

**Comment by alitoshmatov** [comment] 2024-08-18 13:12
No proposals yet

**Comment by kubabutkiewicz** [comment] 2024-08-26 10:44
Hi! I am Jakub from Callstack - expert contributor group. I’d like to work on this job

**Comment by kubabutkiewicz** [comment] 2024-08-26 11:46
Hey @lanitochka17 are you able to share the receipt which you used when noticed the crash?

**Comment by lanitochka17** [comment] 2024-08-26 12:52
@kubabutkiewicz 
![Receipt Example](https://github.com/user-attachments/assets/ffceb383-d04f-42f8-ac72-ee4ddbd68de2)

**Comment by kubabutkiewicz** [comment] 2024-08-26 16:02
@lanitochka17 Are you able to reproduce that? I was trying but no luck

**Comment by kubabutkiewicz** [comment] 2024-08-27 09:17
Ok, I was able to reproduce that today

**Comment by kubabutkiewicz** [comment] 2024-08-27 13:49
I was able to reproduce that only once but I know what is a problem 
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In review duplicates, tapping "keep all" causing an app crash 
### What is the root cause of that problem?
In that function https://github.com/Expensify/App/blob/c2e7f400b13d813cc52ceb5ed9dfdbaf72dff905/src/libs/actions/Transaction.ts#L295-L391 we are creating an `currentTransactions` here 
https://github.com/Expensify/App/blob/c2e7f400b13d813cc52ceb5ed9dfdbaf72dff905/src/libs/actions/Transaction.ts#L297
and the problem occurs because this `currentTransactions` looked like that 
```
[
   {
      "amount":0,
      "bank":"",
      "billable":false,
      "cardID":0,
      "cardName":"Cash Expense",
      "cardNumber":"",
      "category":"",
      "comment":"",
      "created":"2024-08-27",
      "currency":"PLN",
      "filename":"w_d579b03466fbab547f0feb9ff9c95877491b3587.png",
      "hasEReceipt":false,
      "isLoading":false,
      "managedCard":false,
      "mcc":"",
      "merchant":"(none)",
      "modifiedAmount":-650,
      "modifiedCreated":"2023-09-28",
      "modifiedCurrency":"USD",
      "modifiedMCC":"",
      "modifiedMerchant":"Test",
      "originalAmount":0,
      "originalCurrency":"",
      "parentTransactionID":"",
      "pendingFields":{
         "merchant":"update"
      },
      "receipt":{
         "receiptID":987847661721264,
         "source":"https://www.expensify.com/receipts/w_d579b03466fbab547f0feb9ff9c95877491b3587.png",
         "state":"SCANCOMPLETE"
      },
      "reimbursable":true,
      "reportID":"5732908836376120",
      "status":"Posted",
      "tag":"",
      "taxAmount":0,
      "taxCode":"",
      "transactionID":"44320141500630305"
   },
   "undefined",
   "undefined",
   "undefined",
   "undefined"
]
```
so last 4 items were `undefined`  and then here https://github.com/Expensify/App/blob/c2e7f400b13d813cc52ceb5ed9dfdbaf72dff905/src/libs/actions/Transaction.ts#L298-L299 we are mapping through `currentTransactions` and because off those `undefined` the `reportID` and `transactionID` don't exists and it make a crash
### What changes do you think we should make in order to solve the problem?
We can use `TransactionUtils.getTransaction` method here https://github.com/Expensify/App/blob/c2e7f400b13d813cc52ceb5ed9dfdbaf72dff905/src/libs/actions/Transaction.ts#L297 so then the type of `currenctTransactions` will be `OnyxEntry<Transaction>[]` and we can use optional chaining in places where transaction can be undefined so it will look like that 
```
    const currentTransactions = transactionIDs.map((id) => TransactionUtils.getTransaction(id));
    const transactionsReportActions = currentTransactions.map((transaction) => ReportActionsUtils.getIOUActionForReportID(transaction?.reportID ?? '', transaction?.transactionID ?? ''));
    const isSubmitter = currentTransactions.every((transaction) => isCurrentUserSubmitter(transaction?.reportID ?? ''));
```
in that way the app will not crash


### What alternative solutions did you explore? (Optional)

**Comment by lanitochka17** [comment] 2024-08-28 13:21
Issue is not reproducible on the latest build  9.0.25-10

https://github.com/user-attachments/assets/f6a80722-c21a-425c-a94a-863c54611b70

**Comment by kubabutkiewicz** [comment] 2024-09-02 06:08
@alitoshmatov Can you check my [proposal](https://github.com/Expensify/App/issues/46711#issuecomment-2312619019) ?

**Comment by alitoshmatov** [comment] 2024-09-03 17:58
I can't access applause test account, and couldn't reproduce it myself following the OP instructions. So I think I cannot help you here. I will ask for help in C+ channel

**Comment by kubabutkiewicz** [comment] 2024-09-03 19:04
I was able to reproduce that on my own account

**Comment by RachCHopkins** [comment] 2024-09-09 01:56
Any joy @allgandalf?

**Comment by mvtglobally** [comment] 2024-09-09 04:11
Issue not reproducible during KI retests. (First week)

**Comment by RachCHopkins** [comment] 2024-09-10 05:34
@mvtglobally did you retest with a private domain?

**Comment by RachCHopkins** [comment] 2024-09-12 03:45
Looks like no one here can repro this. @alitoshmatov are you able to?

**Comment by alitoshmatov** [comment] 2024-09-12 21:27
@RachCHopkins No I am not able to reproduce this issue

**Comment by mvtglobally** [comment] 2024-09-13 16:39
Issue not reproducible during KI retests. (Second week)

**Comment by RachCHopkins** [comment] 2024-09-16 23:01
Ok, closing!

**Closed by RachCHopkins** 2024-09-16 23:01 UTC
Labels: External, Daily, Help Wanted, Overdue, Bug
