### ISSUE TITLE
[Awaiting Payment] [$250] [QBO] Open "Accounting" page can show "Hmm... it's not here"

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#41250] opened 2024-04-29 20:34 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Create Workspace
2. Go to "More Settings"
3. Make your connection extra slow using the dev tools
4. Enable "Accounting" for the first time
5. Quickly navigate to the new "Accounting" menu that appeared (before the request `EnablePolicyConnections` is resolved)

## Expected Result:

If the data is not ready, we should see a skeleton loader on the Connections card in the Accounting page, not "Hmm... it's not here" page

![image](https://github.com/Expensify/App/assets/145416827/a37508ae-32ce-4b0a-8bef-077f2f9a44e4)

## Actual Result:

"Hmm... it's not here" page is shown briefly

<img width="271" alt="image" src="https://github.com/Expensify/App/assets/87341702/a1b2f6c1-7768-4372-8fa7-f1af94d77e9e">

https://github.com/Expensify/App/assets/87341702/3d8da688-7166-4ced-b8e7-9a8f6e677ae8

## Workaround:

Wait for some time

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01270b3d16e231f2ad</li>
        <li>Upwork Job ID: 1785284479820603392</li>
        <li>Last Price Increase: 2024-05-07</li>
    </ul>
</details>

**Comment by aldo-expensify** [comment] 2024-04-29 20:34
cc @hayata-suenaga @trjExpensify

**Comment by trjExpensify** [comment] 2024-04-30 02:25
This can go external, right? I wonder if a skeleton loader is better than a spinner here. CC: @Expensify/design for thoughts before we move this on.

**Comment by aldo-expensify** [comment] 2024-04-30 02:26
> This can go external, right?

Very likely, I haven't investigated though. Maybe it is about optimistic data when we enable "Accounting"

**Comment by dubielzyk-expensify** [comment] 2024-04-30 02:47
I don't feel super strongly if we do spinner or skeleton loader. I'll let @dannymcclain or @shawnborton decide. 

**Spinner:**
![image](https://github.com/Expensify/App/assets/145416827/e47321fd-3ed4-4578-bbc5-e0d836d5efce)

**Skeleton:**
![Uploading image.png…]()

**Comment by shawnborton** [comment] 2024-04-30 12:09
I like the idea of the skeleton personally!

**Comment by trjExpensify** [comment] 2024-04-30 12:25
Samesies, I like the skelly!

**Comment by trjExpensify** [comment] 2024-04-30 12:26
> > This can go external, right?
> 
> Very likely, I haven't investigated though. Maybe it is about optimistic data when we enable "Accounting"

Sounds good, I'll move it on for now!

**Comment by trjExpensify** [comment] 2024-05-07 14:35
SOLD! 😂

**Comment by johncschuster** [comment] 2024-05-09 21:26
@narefyev91 how's this going?

**Comment by narefyev91** [comment] 2024-05-10 06:37
> @narefyev91 how's this going?

Today PR will be raised for review

**Comment by s77rt** [comment] 2024-05-13 08:58
I'm not able to reproduce this. Is this still reproducible? I'm guessing this was caused by a bug in Onyx and it's now fixed. The [optimistic data](https://github.com/Expensify/App/blob/90a5028863661d9a31283d0f3832f7b34d5b46cd/src/libs/actions/Policy.ts#L4083) looks good to me.

**Comment by hayata-suenaga** [comment] 2024-05-13 15:31
> I'm not able to reproduce this. Is this still reproducible? I'm guessing this was caused by a bug in Onyx and it's now fixed. The [optimistic data](https://github.com/Expensify/App/blob/90a5028863661d9a31283d0f3832f7b34d5b46cd/src/libs/actions/Policy.ts#L4083) looks good to me.

nice! I also don't know why the optimistic data didn't have an effect before. In that case, do we still need @narefyev91's PR? We don't have a situation where the loading screen implemented in the PR is actually displayed, right?

**Comment by narefyev91** [comment] 2024-05-13 15:38
@hayata-suenaga full page loading indicator will be shown - when we will be fetching possible connections. And with low connection user will see: 1) Card with default connections ex. Quickbooks online and Xero; 2) Full screen loading indicator; 3) again Card with fetched and default connections.
That's why the decision was made to not show full screen loading indicator - to prevent jumping content - but just show Connections card initially and skeleton during loading

**Comment by narefyev91** [comment] 2024-05-14 10:33
> @narefyev91 I'm not sure I see the problem, can you provide reproduction steps for that? As far as I can tell the PR seems only needed to switch from the full page loading indicator to the skeleton view

Yeah - this is the only change needs to make - just move away from full page loading indicator and use skeleton during fetching available options for connections

**Comment by trjExpensify** [comment] 2024-05-24 00:42
Is this still open for something? 🤔

**Comment by hayata-suenaga** [comment] 2024-05-29 06:12
@eVoloshchak, can you provide a summary of the latest on this issue? 🙇

**Comment by eVoloshchak** [comment] 2024-05-29 09:39
The issue is resolved, not sure if there are any outstanding payments for @s77rt and @narefyev91

**Comment by trjExpensify** [comment] 2024-05-29 12:45
Assigning @s77rt who's due payment for C+ review of the PR. @johncschuster can you action on that? Thanks!

**Comment by johncschuster** [comment] 2024-05-31 21:01
Looks like the PR was deployed about two weeks ago, so this should be clear for payment! 🎉

**Comment by s77rt** [comment] 2024-05-31 21:07
@johncschuster Accepted! Thanks!

**Comment by johncschuster** [comment] 2024-06-03 19:59
Payment has been issued! Thanks for your contributions!

**Closed** 2024-06-03 19:59 UTC
Labels: External, Daily, Awaiting Payment, Bug
