### ISSUE TITLE
Workspace name is not visible while requesting for money

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21494] opened 2023-06-24 15:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace
2. Invite a member to the workspace
3. Sign in as the member
4. Select the Workspace chat
5. Tap the + icon and select "Request money" > Enter any amount and tap next
## Expected Result:
 The workspace name should be visible.
## Actual Result: 
The workspace name is not visible.

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 
**Reproducible in staging?:** Needs reproduction 
**Reproducible in production?:** Needs reproduction 
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
![image (1)](https://github.com/Expensify/App/assets/43996225/f336954e-fb3e-4569-8943-ba3242f3a00a)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @therealsujitk
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686981470989959

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by dylanexpensify** [comment] 2023-06-27 10:13
Hmm cannot reproduce. @kavimuru can you confirm?

**Comment by therealsujitk** [comment] 2023-06-27 11:56
@dylanexpensify she was not able to reproduce it either, can you leave this open for sometime so I can try to come up with a more reliable way to reproduce this? Thanks!

If you prefer, we could also close this now and re-open it when I can reproduce this properly.

**Comment by kavimuru** [comment] 2023-06-27 16:57
@dylanexpensify I wasn't able to reproduce. So I created with `Needs reproduction` label.

**Comment by dylanexpensify** [comment] 2023-06-28 10:48
let's close and reopen once we have more accurate steps! Thanks all!

**Closed by dylanexpensify** 2023-06-28 10:48 UTC
Labels: Daily, Needs Reproduction, Bug
