### ISSUE TITLE
[$1000] Web- Announce room - Clicking on split bill IOU card after removing members behaves inconsistently

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19742] opened 2023-05-29 13:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Create a new workspace and add members
2. Split bill with all the members
3. Notice clicking on the IOU card in the #announce room opens the details panel
4. Remove all members from the workspace
5. Go back to the #announce room and click on the IOU card

## Expected Result:
The behavior should be the same before removing members and after removing, hence a new thread should not be created after members have been removed. And if the thread being created is an intended behavior then the message "[Deleted message]" should not appear before the thread gets created. The card in the newly created thread should also not remove the hover state when clicked.

## Actual Result:
A new thread will be created when clicking on the IOU card and at first the thread being created will show the message "[Deleted message]". After the thread have been created clicking on the card does nothing and it removes the hover state.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19.3

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/4819953f-4f43-4427-91a9-6875a5ac7652

https://github.com/Expensify/App/assets/93399543/c0dd3b8c-a91a-4261-90e5-dcb6877c0240

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Nathan-Mulugeta

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685001984533859

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0109384175d45c6600</li>
        <li>Upwork Job ID: 1666573454690783232</li>
        <li>Last Price Increase: 2023-06-14</li>
    </ul>
</details>

**Comment by puneetlath** [comment] 2023-06-03 01:16
I need to start a discussion to figure out what the ideal behavior should be for this. Will do that soon.

**Comment by puneetlath** [comment] 2023-06-12 13:38
@Santhosh-Sellavel I'll be OOO this week, so if you need Internal help moving this forward during that time please ask in #contributor-plus. Thanks!

**Comment by Beamanator** [comment] 2023-06-15 17:40
@tylerkaraszewski looks like you got auto-assigned then i accidentally removed you 😳

**Comment by trjExpensify** [comment] 2023-06-15 17:49
This bug report is old. The details page was a placeholder ahead of introducing the split confirmation screen. 

<img width="1143" alt="image" src="https://github.com/Expensify/App/assets/16232057/a2f27a13-ec78-4fa9-a100-c4761adfa79c">

I removed members and it remains the same, as intended. http://g.recordit.co/LWBlPIBciO.gif

Closing.

**Closed by trjExpensify** 2023-06-15 17:49 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by securitybeautystar** [comment] 2023-06-15 17:55
### **Solution:**
Maintain IOU Card Behavior Consistency:
The IOU card should maintain the same behavior regardless of the number of workspace members. This might involve adjusting the condition that triggers the creation of a new thread when the IOU card is clicked.

Handle Empty Threads:
The application should be adjusted so that "[Deleted message]" does not appear when creating an empty thread. This could be an issue with how the app handles empty threads or threads that lose all members.

Persistent Hover State:
The hover state of the IOU card should not be removed when clicked. It might be a CSS or JS issue that needs to be investigated.

Here's a general plan on how to approach these changes:

Identify the sections of the code that handle IOU card click events, thread creation, and hover states.
Investigate the conditions that lead to new thread creation on IOU card click. Adjust these conditions so the behavior stays consistent regardless of member count.
Adjust the code that handles thread creation to prevent the "[Deleted message]" text from appearing in newly created threads.
Debug and resolve the issue causing the hover state removal on the IOU card click event.

**Comment by Santhosh-Sellavel** [comment] 2023-06-15 18:11
Thanks for closing @trjExpensify and nothing is due.
