### ISSUE TITLE
[HOLD for payment 2024-01-22] [$500] mWeb - IOU- Text "Long email id owes" is displayed with extra spacing in IOU preview

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#33769] opened 2023-12-29 17:52 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.19-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Tap on 1:1 chat with long email id
3. Tap plus icon --- request money --- Manual
4. Enter an amount
5. Tap request

## Expected Result:
Text "Long email id owes" must not be displayed with extra spacing in IOU preview.

## Actual Result:
Text "Long email id owes" is displayed with extra spacing in IOU preview.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![image](https://github.com/Expensify/App/assets/93399543/02e3cd1f-1c6b-4478-bf46-b1e502f04606)

https://github.com/Expensify/App/assets/93399543/aced5a86-4928-4353-95dd-213155e7197c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b95b98369a189481</li>
        <li>Upwork Job ID: 1740792968326352896</li>
        <li>Last Price Increase: 2023-12-29</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 28081699</li>
<li>fedirjh | Contributor | 28081700</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @bfitzexpensify</details>

**Comment by situchan** [comment] 2023-12-29 18:01
Seems like regression from https://github.com/Expensify/App/pull/32818
cc: @rezkiy37 @fedirjh as still within regression period

**Comment by vikssevishnu** [comment] 2023-12-29 20:53
Is this still open or fix yet to be deployed ?

**Comment by aim-salam** [comment] 2023-12-29 21:47
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

lineHeight didnt specify in Text component, which React Native use default value.

### What changes do you think we should make in order to solve the problem?

Put lineHeight in the text

 `<Text style={[styles.textLabelSupporting, styles.mb1, getLineHeightStyle(variables.lineHeightXXLarge),{lineHeight:18}]}>{getPreviewMessage()}</Text>`

### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2023-12-30 14:16
@rezkiy37 @fedirjh Can you work on this one please since it's a regression from your [PR](https://github.com/Expensify/App/pull/32818).


cc @shawnborton since this is design related in case you have any inputs here

| BEFORE | NOW (BUG?) |
|--------|------------|
|   <img width="427" alt="Screenshot 2023-12-30 at 3 12 46 PM" src="https://github.com/Expensify/App/assets/16493223/c54a51fe-3931-4883-a5d3-9e7d8abf393e">     |   <img width="427" alt="Screenshot 2023-12-30 at 3 13 23 PM" src="https://github.com/Expensify/App/assets/16493223/fbcaacfc-16fd-4bda-86c6-195d37495c69">         |

**Comment by shawnborton** [comment] 2024-01-02 08:59
Agree that we should make the line height smaller to fix this one, cc @Expensify/design for visibility. 

That being said, is this a regression? As in, if it was working before and suddenly it broke, can we track down the offending PR and PR author?

**Comment by s77rt** [comment] 2024-01-02 14:06
@shawnborton Yes it's a regression from https://github.com/Expensify/App/pull/32818. The author seems [OOO](https://github.com/Expensify/App/issues/33769#issuecomment-1873363313).

**Comment by bfitzexpensify** [comment] 2024-01-04 19:33
I can't assign @rezkiy37 because he hasn't commented on the issue, but tagged him on Slack.

**Comment by aim-salam** [comment] 2024-01-08 00:08
Im new here and Im confuse. I though my proposal the only one here.
Same case like this issue https://github.com/Expensify/App/issues/33647

**Comment by rezkiy37** [comment] 2024-01-08 10:02
Hey, guys! I am back. Do you need any my help here? Looks like other guys fixed pretty similar issue here - https://github.com/Expensify/App/pull/33662. Is the bug still relevant?

**Comment by rezkiy37** [comment] 2024-01-08 10:43
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-01-08 14:12
I can confirm that the bug is still relevant. I am going to revert changes for this case.

**Comment by bfitzexpensify** [comment] 2024-01-08 15:43
Thanks @rezkiy37!

**Comment by s77rt** [comment] 2024-01-08 18:21
@aim-salam If a we find out that a bug is caused by a previous PR that is within the regression period (didn't pass 7 days after hitting production) then the PR author is assigned to fix that bug.

**Comment by aim-salam** [comment] 2024-01-08 23:07
@s77rt aaah I see. Thank you for the clarification.

**Comment by rezkiy37** [comment] 2024-01-09 15:03
The PR - https://github.com/Expensify/App/pull/34100 - is ready for review 🙂

**Comment by bfitzexpensify** [comment] 2024-01-23 17:57
@fedirjh looks like the Upwork offer is still awaiting your acceptance. Also a bump on the BZ checklist - thanks!

**Closed** 2024-01-25 19:19 UTC
Labels: External, Daily, Awaiting Payment, Bug
