### ISSUE TITLE
[HOLD for payment 2024-10-03] [$250] Wallet - Verify button does not show loading indicator after entering magic code

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49073] opened 2024-09-12 12:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.33-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue was found when executing this PR:** https://github.com/Expensify/App/pull/48953
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Account has a virtual card.

1. Go to staging.new.expensify.com
2. Go to Account settings > Wallet.
3. Click on the virtual card.
4. Click Reveal details.
5. Enter magic code.

## Expected Result:
Verity button will show loading indicator after entering magic code (log in and adding contact method behavior).

## Actual Result:
Verify button does not show loading indicator after entering magic code.

## Workaround:
Unknown

## Platforms:

- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/215fb897-3d33-4f5f-9220-c323b14780ce

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021834276399647422536</li>
        <li>Upwork Job ID: 1834276399647422536</li>
        <li>Last Price Increase: 2024-09-12</li>
    </ul>
</details>

**Comment by IuliiaHerets** [comment] 2024-09-12 12:30
@miljakljajic  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by getusha** [comment] 2024-09-16 06:04
Reviewing

**Comment by getusha** [comment] 2024-09-16 06:32
@daledah's [proposal](https://github.com/Expensify/App/issues/49073#issuecomment-2346268598) looks good to me and works well. they were the first to provide a working solution, other cases are something we could handle in the PR.

🎀 👀 🎀 C+ Reviewed.

**Comment by miljakljajic** [comment] 2024-09-20 15:08
I'm going out on parental leave, so I've assigned another BZ team member to take over when the issue is ready for payment. thank you @sakluger

**Comment by sakluger** [comment] 2024-09-23 16:45
I sent an offer to @daledah on Upwork https://www.upwork.com/nx/wm/offer/104091230.

The PR is merged, but not yet deployed.

**Comment by getusha** [comment] 2024-09-29 20:12
PR was deployed a couple of days ago, seems like automation failed https://github.com/Expensify/App/pull/49327#issuecomment-2379772551

**Comment by Julesssss** [comment] 2024-09-30 08:50
Can be paid in 4 days

**Comment by sakluger** [comment] 2024-09-30 14:51
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [ ] [@getusha] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@getusha] Determine if we should create a regression test for this bug.
- [ ] [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@sakluger] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sakluger** [comment] 2024-10-02 15:06
I'll pay this out tomorrow.

@getusha could you please handle the BZ checklist? Thanks!

**Comment by sakluger** [comment] 2024-10-02 15:38
Commenting for melvin.

**Comment by sakluger** [comment] 2024-10-03 20:24
Hey @daledah - somehow I accidentally closed the previous contract without paying it out, and now I can't reopen it. Sorry about that! I've sent you a new, duplicate offer: https://www.upwork.com/nx/wm/offer/104255119. Could you please let me know once you've accepted the new one?

@getusha could you please complete the BZ checklist?

**Comment by getusha** [comment] 2024-10-06 05:57
BugZero Checklist: The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

 [@getusha] The PR that introduced the bug has been identified. Link to the PR: https://github.com/Expensify/App/pull/48628
 [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: **we missed this during a feature implementation.**
 [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: **N/a**
 [@getusha] Determine if we should create a regression test for this bug. **No, it's a minor visual issue.**
 [@getusha] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. **n/a**

**Comment by sakluger** [comment] 2024-10-07 16:09
Thanks! @daledah I completed payment on the contract. @getusha, please. use the [payment summary](https://github.com/Expensify/App/issues/49073#issuecomment-2392008245) to request payment via NewDot.

**Closed by sakluger** 2024-10-07 16:09 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by garrettmknight** [comment] 2024-10-29 21:12
$250 approved for @getusha
