### ISSUE TITLE
Chat - After specific formatted message is sent, new messages appears above it

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#9438] opened 2022-06-14 01:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
and login with credentials
2. Open any chat and copy/paste specific formatted text from the "Additional Environment Info" field
3. Try to send another message
4. Repeat steps 2-3 if needed

## Additional information:
Architecture
[
](https://wiki2.org/en/File:Microsoft_Windows_95_architecture_svg
)
[_](https://wiki2.org/en/File:Microsoft_Windows_95_architecture_svg
)
Architectural diagram
Windows 95 was designed to be maximally compatible with existing [MS-DOS](https://wiki2.org/en/MS-DOS
)and 16-bit Windows programs and [device drivers](https://wiki2.org/en/Device_drivers
) while offering a more stable and better performing system.[[12]](https://wiki2.org/en/Windows_95#cite_note-pre-multi-12
)%5B%5B13%5D%5D(https://wiki2.org/en/Windows_95%23cite_note-w95-archi-13
) The Windows 95 architecture is an evolution of [Windows for Workgroups](https://wiki2.org/en/Windows_for_Workgroups
)' 386 enhanced mode.Configuration Manager (CONFIGMG)Responsible for implementing [Plug and Play](https://wiki2.org/en/Legacy_Plug_and_Play
) functionality; monitoring hardware configuration changes; detecting devices using bus enumerators_; and allocating [I/O ports](https://wiki2.org/en/I/O_port
), [IRQs](https://wiki2.org/en/Interrupt_request_
(PC_architecture)), [DMA channels](https://wiki2.org/en/DMA_channel
) and [memory](https://wiki2.org/en/Memory-mapped_I/O
) in a conflict-free fashion.[[14]](https://wiki2.org/en/Windows_95#cite_note-14
)Installable File System Manager (Input/Output Subsystem)Coordinates access to supported file systems. Windows 95 initially shipped with support for [FAT12](https://wiki2.org/en/FAT12
), [FAT16](https://wiki2.org/en/FAT16
), the [VFAT](https://wiki2.org/en/VFAT
) extension, [ISO 9660](https://wiki2.org/en/ISO_9660
) (CDFS), [Joliet](https://wiki2.org/en/Joliet_
(file_system)) and [network redirectors](https://wiki2.org/en/Network_redirector
), with later releases supporting [FAT32](https://wiki2.org/en/FAT32
).[[15]](https://wiki2.org/en/Windows_95#cite_note-15
)
## Expected Result:
All sent messages should be displayed in the correct order

## Actual Result:
Once specific formatted message is sent - all new sent messages appears below that message

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.76.2

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** yuriy.turbo+ch11@gmail.com/Aa111111

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/173473556-f2dbdc23-d937-4e22-9e2c-019d73676cf9.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by thienlnam** [comment] 2022-06-14 13:30
It seems to be stuck as an optimisticID, and does not refresh correctly with the correct reportActionID once it is sent

**Comment by thienlnam** [comment] 2022-06-14 13:53
I am pretty sure this can be external, would start investigation [here](https://github.com/Expensify/App/blob/0a33d883242c237a903cff5818c67341c7db966b/src/libs/actions/Report.js#L920-L1028)

**Comment by NicMendonca** [comment] 2022-06-14 21:17
Job post: https://www.upwork.com/jobs/~01f94e0e8015da8eeb

**Comment by allroundexperts** [comment] 2022-06-17 21:16
# Proposal

## Issue
There are two reasons which are causing this issue:
1. `Network.post` request in `Report_AddComment` function returns promise that never resolves. The network tab shows the request to be successful with 200 code but the promise never resolves. This happens for requests that go into the sequential queue. This causes the following code to never run as the promise never resolves:
https://github.com/Expensify/App/blob/main/src/libs/actions/Report.js#L1012

2. The API is not pushing the comment back to the client App. This can be clearly seen here:
https://user-images.githubusercontent.com/30054992/174401466-a0fd1c0c-59ed-436f-8897-2b173ebe0012.mp4
The websocket message does come back if the comment is plain text. But for the markdown text, the websocket does not return the comment back.

## Solution
The easiest solution is to fix the WS API so that it returns the comment for markdown types. If that is not possible (It should be really), then we can refactor the `Network.Post` request so that the promise resolves even in the sequential queue. IMO, the second suggestion is a separate fix which should have a separate bug.

**Comment by NicMendonca** [comment] 2022-06-20 12:35
@mananjadhav bump on the proposal review 👆

**Comment by mananjadhav** [comment] 2022-06-20 12:53
I am going to be reviewing @allroundexperts's comments today. But I can't find any specific proposal here which describe what changes will be made and where.

**Comment by allroundexperts** [comment] 2022-06-20 12:59
@mananjadhav Yes. WS is websockets. For other comments, the issue does not exist because the websocket response is being sent correctly.

**Comment by allroundexperts** [comment] 2022-06-20 20:11
@mananjadhav As confirmed in this chat:
https://expensify.slack.com/archives/C01GTK53T8Q/p1655499310036769
We need to not worry about the promise not resolving. Instead we need to fix the websocket api call that is failing.

**Comment by marcaaron** [comment] 2022-06-20 20:24
I would vote to take this internal. I'm not sure there is anything we can do in the client to investigate why the push data is failing to send...

https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%2271e735df3f68f4c4-SJC%22)+AND+timestamp:[2022-06-20T19:21:22.807Z+TO+2022-06-20T21:21:22.807Z]&index=logs_expensify-017295

**Comment by mvtglobally** [comment] 2022-06-27 14:13
potentially related issue https://github.com/Expensify/App/issues/9370

**Comment by tgolen** [comment] 2022-08-17 16:50
I am no longer able to reproduce this. You can see here how my messages sent after I pasted in the formatted message are showing at the bottom, where I would expect them to. (I pasted the comment after "2" and before "3").

![image](https://user-images.githubusercontent.com/1228807/185197303-2ab9c824-e11c-4e97-a4f2-a1eeb8b391d5.png)

**Closed by tgolen** 2022-08-17 16:50 UTC
Labels: Engineering, Monthly, Improvement, Internal
