### ISSUE TITLE
Web -  Inconsistent size of icons in App download links RHN.

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#23452] opened 2023-07-23 20:58 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app and login with any account.
2. Go to setting >> about >> app download links.
3. Notice the icon size in comparing with each other (especially iOS icon is very small).

## Expected Result:
The size of different icons should be consistent.

## Actual Result:
The size of different icons are not consistent with each other.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.43-7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image (2)](https://github.com/Expensify/App/assets/93399543/eee880f2-48f3-4c0a-88ab-de2cc261e100)

https://github.com/Expensify/App/assets/93399543/6f6df396-46fa-42a5-a589-b35c4b39791c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ahmedGaber93
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689975246241799

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by s-alves10** [comment] 2023-07-24 03:35
We might need to redesign the following svgs
[apple.svg](https://github.com/Expensify/App/blob/main/assets/images/apple.svg)
[android.svg](https://github.com/Expensify/App/blob/main/assets/images/android.svg)
[monitor.svg](https://github.com/Expensify/App/blob/main/assets/images/monitor.svg)

**Comment by himanshuragi456** [comment] 2023-07-24 03:39
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent size of Icons in App download links

### What is the root cause of that problem?

Even though the size of all related SVGs is similar 20*20, and the container size is 40*40, the problem lies in the internal code of the SVGs of apple.svg and monitor.svg.

- size of android is perfect
- size of apple is smaller than required
- size of monitor is larger than required

### What changes do you think we should make in order to solve the problem?

increase the size of apple.svg by using `transform` attribute in `<g>` tag
decrease the size of monitor.svg by using `transform` attribute in `<g>` tag

### What alternative solutions did you explore? (Optional)
N/A

**Comment by ojasjadhav2** [comment] 2023-07-24 03:50
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Inconsistent size of Icons in App download links

### What is the root cause of that problem?

Even though the size of all related SVGs is similar 20*20, and the container size is 40*40, the problem lies in the internal code of the SVGs of apple.svg and monitor.svg.

- size of android is perfect
- size of apple is smaller than required
- size of monitor is larger than required

### What changes do you think we should make in order to solve the problem?

increase the size of apple.svg by using `transform` attribute in `<g>` tag:

- add ` transform="scale(1.3)"` in internal `<g>` tag
- change `viewbox` from "0 0 20 20" to "4 3 20 20"
- in `<rect>` tag, give the following attributes `x="0"` `y="0"` `width="18"` `height="20"`

decrease the size of monitor.svg by adding a `<g>` tag using `transform` attribute in the `<g>` tag:

``` diff
<g transform="scale(0.95)">
(...path code here, as it is)
</g>
```

result:

<img width="382" alt="image" src="https://github.com/Expensify/App/assets/111270565/a6aafe2c-6106-4eec-8e73-334303d9ea3a">

### What alternative solutions did you explore? (Optional)
N/A

**Comment by JmillsExpensify** [comment] 2023-07-24 23:17
@shawnborton mind giving your take on this one?

**Comment by shawnborton** [comment] 2023-07-25 01:22
This is not a bug. All icons are built on a 20x20 grid, and then they sit within a 40x40 hit box. Let's close this.

**Closed by shawnborton** 2023-07-25 01:22 UTC
Labels: Daily, Bug

**Comment by JmillsExpensify** [comment] 2023-07-26 03:58
I agree with Shawn given that it's a standard size, and thus, changing the size will make it inconsistent.
