### ISSUE TITLE
[$250] [Group Chats] Selecting a user via Search creates a Group Chat incorrectly

### ISSUE THREAD

**Issue by marcaaron** [Expensify/App#39560] opened 2024-04-03 21:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @slafortune @amyevans 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1712159111998949

## Action Performed:

1. Navigate to Search page
2. Type partial email for user you already have Group DM with
3. Tap the row

## Expected Result:

1. Navigated to existing 1:1 DM with this user

## Actual Result:

1. A new Group Chat is getting created

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011a118694cb14efc8</li>
        <li>Upwork Job ID: 1775637141660168192</li>
        <li>Last Price Increase: 2024-04-04</li>
<li>Automatic offers: </li>
<ul>
<li>s77rt | Reviewer | 0</li>
<li>abzokhattab | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by marcaaron** [comment] 2024-04-03 21:34
We are not totally sure how to reproduce this. But it seems possibly related to the fact that Stevie has an incorrect value for `report.visibleChatMemberAccountIDs` and there is a known issue [here](https://github.com/Expensify/Expensify/issues/382702). So, I _suspect_ this could be related to an existing bug (I'm looking into the fix already).

**report data for correct chat in Amy's account:** Has correct `visibleChatMemberAccountIDs`

**report data for correct chat in Stevie's account:** Is identical (a.k.a. it is wrong and should be an array with Amy's `accountID`, but instead shows Stevie's `accountID`)

Still unsure why the frontend would be trying to create a Group Chat in that case. 

@s77rt might be able to figure it out since they have the most context and worked closely with us on this feature.

**Comment by s77rt** [comment] 2024-04-03 21:39
Will check this asap

**Comment by abzokhattab** [comment] 2024-04-04 04:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Selecting a user via search after creating a group chat creates a group instead of 1-1 DM
### What is the root cause of that problem?
 
The issue occurs because when creating a group we set the Draft group when navigating to the confirm group page and, dont clear the draft state after creating the group also the https://github.com/Expensify/App/blob/d4da2d7cadbe1c620c0c4b9c0760ac1775b64b9f/src/pages/NewChatPage.tsx#L198

### What changes do you think we should make in order to solve the problem?

Two possible solutions here:

1. - we need to call `clearDraft` after creating the optimistic data [here](https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L810-L821)
    - this way the draft state will be cleared when creating a group, however this is just a partial fix and wont fix the issue completely because if go to start/chat then select some contacts and click next and dismiss the modal and open the search and create a direct dm, the draft state will not be null in this case and [this condition](https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L809) will be true 
3. to fix the issue completely i suggest to use the draft state only in the startchat and confirm group page, this state should be used when opening a report is other areas. to do so we need to introduce a new optional boolean argument to the `navigateToAndOpenReport` function: `isFromStartNewChat` this value will be only `true` in the start chat and confirm group  pages[here](https://github.com/Expensify/App/blob/d4da2d7cadbe1c620c0c4b9c0760ac1775b64b9f/src/pages/NewChatPage.tsx#L188)  and [here](https://github.com/Expensify/App/blob/d4da2d7cadbe1c620c0c4b9c0760ac1775b64b9f/src/pages/NewChatPage.tsx#L187) 
- finally inside the `navigateToAndOpenReport` we should then use the `isFromStartNewChat` var [here](https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L804) :
 ```js
    if (!newGroupDraft || !isFromStartNewChat) {
```

- and [here](https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L810) to:

```js
        if (newGroupDraft && isFromStartNewChat) {
```


### alternatively 

another solution would be to call the cleardraft function on opening the search page same as we do with startchat here

https://github.com/Expensify/App/blob/be315d6cf336a448e330ccc752e395ccf2695629/src/libs/actions/Report.ts#L225-L228

**Comment by s77rt** [comment] 2024-04-04 05:13
@abzokhattab Thanks a lot for looking into this. Your RCA is correct. However for the solution I have something else in mind. I just realised that we don't need `newGroupDraft` in `navigateToAndOpenReport`.

**Comment by abzokhattab** [comment] 2024-04-04 05:25
after thinking about it more, yes i agree, we can just add `isGroup` parameter to the `navigateToAndOpenReport ` and this should be true in case the created report is a group report then we replace the  `newGroupDraft` conditions with the `isGroup`.

**Comment by s77rt** [comment] 2024-04-04 05:32
Oh sorry I thought I'm assigned here. Was going straight with a PR

**Comment by s77rt** [comment] 2024-04-04 05:32
Posting a proposal, a moment please

**Comment by mananjadhav** [comment] 2024-04-04 05:38
No worries. Just ensuring that we are on the same page.

**Comment by abzokhattab** [comment] 2024-04-04 05:38
added a [third proposal](https://github.com/Expensify/App/issues/39560#issuecomment-2036180610) incase my contribution will be counted 😂

**Comment by s77rt** [comment] 2024-04-04 05:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?
In [`navigateToAndOpenReport`](https://github.com/Expensify/App/blob/6fb92cf3095fa17758a9199267509b0eccd019fd/src/libs/actions/Report.ts#L797) the "isGroupChat" logic is based on the `newGroupDraft` value from onyx i.e. 

```
isGroupChat = newGroupDraft
```

We will be creating a group as long as there is a draft value

### What changes do you think we should make in order to solve the problem?
Don't rely on the presence of the draft value to deterimne if we are navigating to a group chat. Instead rely on the number of participants i.e.

```
isGroupChat = participantAccountIDs.length > 1
```

### What alternative solutions did you explore? (Optional)

None

**Comment by mananjadhav** [comment] 2024-04-04 05:53
Thanks for the proposal. It looks straightforward and reliable to use `participantAccountIds`. Quick question, do we need to update/clear anything on the Onyx value after the method?

🎀 👀 🎀 C+ reviewed.

**Comment by s77rt** [comment] 2024-04-04 05:53
We can keep relaying on the `newGroupDraft` but we will have to clear it every time we complete/discard a group creating process. It's better to avoid this as it's complex to detect when a group creating is discarded.

**Comment by abzokhattab** [comment] 2024-04-04 05:54
Just a quick note here, there's a an ongoing discussion that we might allow creating a group chat with only one participant here https://github.com/Expensify/App/issues/39317#issuecomment-2035679897 .. in this case using `participantAccountIDs.length > 1` will not work

**Comment by s77rt** [comment] 2024-04-04 05:54
The draft is cleared only when starting a new group. Same way with IOU. The IOU draft is only cleared only when starting a new IOU.

**Comment by s77rt** [comment] 2024-04-04 05:58
@abzokhattab That will still work because when creating a group chat even with one person the participantAccountIDs.length will be 2.

- On 1:1: participantAccountIDs will include only the other person's id
- On group chats: participantAccountIDs.length will include the other persons' ids and your id

**Comment by abzokhattab** [comment] 2024-04-04 06:01
> On group chats: participantAccountIDs.length will include the other persons' ids and your id

no I mean the group will contain only one participant which is the author in this case the length is 1.

**Comment by s77rt** [comment] 2024-04-04 06:13
Ah I see. Good point. However I'm feeling like this should be handled when the feature is implemented

**Comment by marcaaron** [comment] 2024-04-04 19:23
I was a bit confused by this proposal as the bug reported is that a Group Chat was created via the "Search" page and not the "New Chat" page. But sounds like we have definitely uncovered a way this could happen. Great investigation.

Confirming with @slafortune now to see if it's possible she took these steps.

@mananjadhav do you mind if we make @s77rt the C+ here and have @abzokhattab collaborate on the PR? I think that would be a fair way to handle this since both have different ideas on the solution. Let me know if it's any problem.

**Comment by marcaaron** [comment] 2024-04-04 19:26
Gonna assign everyone so we can make some progress, but let's collaborate in the PR since @s77rt already has it open.

**Comment by abzokhattab** [comment] 2024-04-04 19:32
Great, should we go with the approach mention [here](https://github.com/Expensify/App/issues/39560#issuecomment-2036245368) then what do you think @s77rt ?

**Comment by s77rt** [comment] 2024-04-04 20:37
@abzokhattab Let's do that change when it becomes needed (by that time we may have other options).

```js
isGroupChat = participantAccountIDs.includes(currentUserAccountID) 
```

An extreme edge case, what if the generated optimistic account id in `participantAccountIDs` happens to be your account id? (collusion)

**Comment by mananjadhav** [comment] 2024-04-04 20:54
> @mananjadhav do you mind if we make @s77rt the C+ here and have @abzokhattab collaborate on the PR? I think that would be a fair way to handle this since both have different ideas on the solution. Let me know if it's any problem.

Okay sure.

**Closed** 2024-06-28 18:32 UTC
Labels: Reviewing, External, Monthly, Needs Reproduction, Bug

**Comment by s77rt** [comment] 2024-06-28 23:00
This is closed already. Do we need to remove te `Reviewing` label here?
