### ISSUE TITLE
[HOLD for payment 2023-08-07] [$1000] Web - On clicking back from profile , again display name page is shown (only on public room)

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21211] opened 2023-06-21 14:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to staging dot on web chrome and login with User A
2. Create a new room in public mode and copy the URL of the room
3. Open an incognito window and paste the URL so that the room page opens up
4.Click on 'here' link and enter any name on the display name and click on save
5. After clicking save, you'll be navigated to the 'Profile' page. Click on back button and notice that it again opens up the display name page
6. If you follow the same steps on User A side, go to settings >profile > display name and try to change the display name and return back. You'll notice , it navigates you to the Settings page. Thus, there's inconsistency between the navigation flow in the public room and on a normal user's profile.

## Expected Result:
On clicking back from profile , settings page should have shown

## Actual Result:
On clicking back from profile , again display name page is shown (only on public room)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.26-4

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/d2f739d8-307f-4088-8afc-da8f226a7863

https://github.com/Expensify/App/assets/93399543/1bfccc45-68b4-42d0-a98d-45e9caf0cdec

**Expensify/Expensify Issue URL:**

**Issue reported by:** @priya-zha

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686742153793689

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c14d0a68460ff870</li>
        <li>Upwork Job ID: 1672241982856548352</li>
        <li>Last Price Increase: 2023-07-07</li>
    </ul>
</details>

**Comment by MitchExpensify** [comment] 2023-06-22 00:57
I'm heading out of office until Tuesday so reassigning and keeping myself on the too to pick it up when I get back

**Comment by priya-zha** [comment] 2023-06-22 09:32
The first part of the issue is not reproducible today since the whisper messages shown as the anonymous user was itself a bug and has been solved.

But the issue can be reproducible with a new logged in user as well. Just a minor change in action steps.

New Reproducible steps :

1. Go to staging dot on web chrome and login with User A
2. Create a public room and then copy the share URL and paste it into an incognito window as an anonymous user (make sure you aren't signed in before- very important step)
3. Click on the 'Sign-in" button and it navigates you to the login page . Please enter the credentials of a **new** user that you haven't used before (important step) as User B
4. Sign in to the new account and you'll be able to see the whisper message
5.Click on 'here' link and enter any name on the display name and click on save
6. After clicking save, you'll be navigated to the 'Profile' page. Click on back button and notice that it again opens up the display name page
7. If you follow the same steps on User A's side, go to settings >profile > display name and try to change the display name and return back. You'll notice , it navigates you to the Settings page. Thus, there's inconsistency between the navigation flow in the public room and on a normal user's profile

https://github.com/Expensify/App/assets/34065075/fbfa327c-4767-401f-bb62-38922c5872e2

**Comment by asadath1395** [comment] 2023-06-23 14:55
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On clicking back from profile , again display name page is shown (only on public room)

### What is the root cause of that problem?
The problem is we are using `Navigation.goBack` method which just goes one step back in the history stack. So here when user clicks on the here button shown in the whisper message, it takes the user to the `settings/profile/display-name` route, so once he is done with the edits, when he clicks on `Save` button he is taken back to the `Profile` page and when he clicks back again the `onBackButtonPress` gets executed which invokes `Navigation.goBack` which takes the user one step back in the history stack which is the `Display Name` page.
https://github.com/Expensify/App/blob/6183609c577f2310928bb4e8ee23b52f6dd28e00/src/pages/settings/Profile/ProfilePage.js#L85-L88

### What changes do you think we should make in order to solve the problem?
Inorder to make it consistent, we could add `true to the `Navigation` invocation i.e., `Navigation.goBack(ROUTES.SETTINGS, true)` which would enforce the user to the `Settings` screen which matches the original flow.

### What alternative solutions did you explore? (Optional)
Nothing explored yet

**Comment by ShogunFire** [comment] 2023-06-25 12:44
I have asked a question in slack because I think the navigation as a whole could be improved:
https://expensify.slack.com/archives/C01GTK53T8Q/p1687696996794659

**Comment by ShogunFire** [comment] 2023-06-25 13:51
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After we have been directly redirected to the Display Name page on public room and we save, the history is not right so when we go back on the profile page it shows us again the display page

### What is the root cause of that problem?

When we are directly redirected to the Display Name page, the stack/history doesn't contain the profile page.
When we save the display name, here: https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/actions/PersonalDetails.js#L170 
we use navigate  which by default has the following behaviour: 
If the page we navigate to is not in the stack it will push it on top of the stack.

So in our case, the profile page will be pushed on top of the Display Page in the stack. For that reason when we click the back button on the profile page it will go to the display page

### What changes do you think we should make in order to solve the problem?


We can use the option "UP" of navigate which will pop the current screen of the stack before navigating, that way the profile page will not be on top of the display page in the stack.
so instead of
`Navigation.navigate(ROUTES.SETTINGS_PROFILE);`
we can use:
`Navigation.navigate(ROUTES.SETTINGS_PROFILE, "UP");`

Result:

https://github.com/Expensify/App/assets/19537677/ce049ff9-52bf-4e4e-af1c-7a568f1fdd36



### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by bernhardoj** [comment] 2023-06-25 14:46
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
If we access the display name page by deeplink or directly access it through the browser URL and save the changes, it will navigate the user to the Profile page. Pressing back on the Profile page will bring the user back to the display name page.

### What is the root cause of that problem?
When we press Save on the display name page, we are doing a NAVIGATE action to the Profile page.
https://github.com/Expensify/App/blob/820fa93ad1e799c12d8b639b98018b5350ea17af/src/libs/actions/PersonalDetails.js#L170

In case we access the display name page by either deeplink or typing the path in the browser URL, the display name page will be the only one in the stack.
Screen stack: [Display name page]

Because the profile page does not exist in the stack, doing a NAVIGATE action to the profile page will push it into the stack.
Screen stack: [Display name page, Profile page]

So, when we press back on the profile page, it will bring the user back to the display name page.
### What changes do you think we should make in order to solve the problem?

Replace `Navigation.navigate` with `Navigation.goBack`. 

If the user access the display name page normally, `goBack` will just pop the current screen (Display name) and bring the user back to the profile page.
[Profile page, Display name] -> [Profile page]

If the user access the display name page by deeplink, `goBack` will use the fallback route and replace the current screen (Display name) with the fallback route (profile page)
[Display name] -> [Profile page]

_Looking into the PersonalDetails.js, looks like this issue happens on other pages too, such as Pronouns, DOB, and Address, I guess we can handle them all with the same solution? Also, this happens in Preferences sub-page too https://github.com/Expensify/App/issues/21409_

**Comment by WoLewicki** [comment] 2023-06-26 13:22
The proposal from @bernhardoj seems like the right way to go since we do it everywhere, so this bug seems like just a missed case by us. Would be nice to fix all the places where `navigate` is still called instead of `goBack` when we want the behavior similar to clicking the RHP `UP` button.

**Comment by ShogunFire** [comment] 2023-06-26 13:32
@WoLewicki I don't agree that this is a better solution. This is basically the same proposal as mine but with a few extra unecessary steps steps. In the goBack method we call navigate with the UP option.

**Comment by WoLewicki** [comment] 2023-06-26 14:29
Hmm are you sure the behavior is always the same? IIRC we only want the `UP` option when we deeplinked into the screen directly: https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/libs/Navigation/Navigation.js#L99, otherwise we should just pop the screen since we have the previous one on the stack already. That's why this extra `UP` logic was added.

**Comment by MitchExpensify** [comment] 2023-06-27 12:12
@parasharrajat whats is your take on the discussion so far and the most promising proposal?

**Comment by MitchExpensify** [comment] 2023-06-29 23:17
[Friendly bump](https://github.com/Expensify/App/issues/21211#issuecomment-1609377337) @parasharrajat

**Comment by MitchExpensify** [comment] 2023-07-03 21:25
Friendly bump @parasharrajat 👍

**Comment by MitchExpensify** [comment] 2023-07-10 19:06
Thoughts on  @bernhardoj 's proposal @AndrewGable ?

**Comment by MitchExpensify** [comment] 2023-07-12 20:56
Not overdue, Melvin

**Comment by mountiny** [comment] 2023-07-19 20:40
@parasharrajat I believe they should go to the Profile page same as clicking UP in product. This is however tricky becasue fo the browser history and I am not sure if we have found a good solution which works in general

**Comment by mountiny** [comment] 2023-07-20 20:21
Oh sorry I though that you were talking about going back sorry.

the browser forward is hard case we are not really supporting it well. I think it should go back to the pronouns page, that would make sense.

**Comment by WoLewicki** [comment] 2023-07-21 13:30
Yeah, it seems natural since you went back from it.

**Comment by MitchExpensify** [comment] 2023-08-01 18:25
Reminder added to cal to pay on 8/7 👍 

**Payment summary:**

Reporting @priya-zha: $250 to be issued via Upwork 
C @bernhardoj: $500 to be issued via Upwork
C+ @parasharrajat: $500 to be issued via NewDot

**Comment by MitchExpensify** [comment] 2023-08-06 13:29
Updated the [payment summary](siobhan wedding ) to remove the penalty. That seems fair to me @parasharrajat - Thanks for flagging!

**Comment by AndrewGable** [comment] 2023-08-08 20:20
Have we paid this one out? It's overdue according to the bots 🤖

**Comment by MitchExpensify** [comment] 2023-08-08 20:52
All offers have been sent and waiting on them to be accepted then we can close @AndrewGable :thumbsup: cc @priya-zha @bernhardoj 

Are you handling NewDot payment for @parasharrajat ? @AndrewGable ?

**Comment by AndrewGable** [comment] 2023-08-08 20:53
I am not handling payments 🙅

**Comment by MitchExpensify** [comment] 2023-08-14 19:24
Thanks @parasharrajat - Added request here https://github.com/Expensify/Expensify/issues/308114

Closing based on [this SO](https://stackoverflowteams.com/c/expensify/questions/16949)

**Comment by MitchExpensify** [comment] 2023-08-14 19:28
Everyone has been paid via Upwork and contracts ended

**Closed by MitchExpensify** 2023-08-14 19:28 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug

**Comment by JmillsExpensify** [comment] 2023-08-16 03:10
Reviewed the details for @parasharrajat. Approved for payment in NewDot based on the BZ summary above.
