### ISSUE TITLE
[$1000] [HOLD for payment 2023-07-14] Back button is not working on select a currency page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22130] opened 2023-07-03 18:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Click on FAB > Request money
2. Click on the currency
3. Click on the back button at the top
## Expected Result: 
Back button should take user back and it should work properly
## Actual Result: 
Back button is not working and console error occurs

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.36-1
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/c8fd650b-c24b-42db-89a0-7c3828d7488e

https://github.com/Expensify/App/assets/43996225/576efdf4-59dc-4f72-a2d4-b7e52e808c8b

**Expensify/Expensify Issue URL:**
**Issue reported by:** @nathan-mulugeta
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688408446305599

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01805773f0aa3fe2ec</li>
        <li>Upwork Job ID: 1679105288887033856</li>
        <li>Last Price Increase: 2023-07-12</li>
    </ul>
</details>

**Comment by dangrous** [comment] 2023-07-03 19:24
Ah it's this line - https://github.com/Expensify/App/blob/e7a17f8d7af114a596b4919c19815e5ac9a38c35/src/pages/iou/IOUCurrencySelection.js#L117 - `ROUTES.getIouRequestRoute()` doesn't actually exist. Need to figure out what it's supposed to do and fix it...

cc @Julesssss in case you know (since it's your PR)

**Comment by jeet-dhandha** [comment] 2023-07-03 19:33
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
- Navigation from IOU's Currency Selection screen to previous screen is not working on back button press.

### What is the root cause of that problem?
- `getIouRequestRoute` function does not exist in `ROUTES` object. Probably removed when we removed IOU's paths and replace with MONEY_REQUEST's paths.

### What changes do you think we should make in order to solve the problem?
- We can use `getMoneyRequestRoute` function instead of `getIouRequestRoute` function. And pass `ROUTES.IOU_REQUEST` as iouType.

File `src/pages/iou/IOUCurrencySelection.js` 

```diff
<HeaderWithBackButton
    title={translate('iOUCurrencySelection.selectCurrency')}
-    onBackButtonPress={() => Navigation.goBack(ROUTES.getIouRequestRoute(Navigation.getTopmostReportId()))}
+    onBackButtonPress={() => Navigation.goBack(ROUTES.getMoneyRequestRoute(ROUTES.IOU_REQUEST))}
/>
```

- We are not passing `reportID` as it will always navigate back to new money request.

### What alternative solutions did you explore? (Optional)
- N/A

**Comment by dangrous** [comment] 2023-07-03 19:54
@jeet-dhandha thanks for the suggestion! In this case, we actually DO need the reportID if we're requested money from inside an already existing money request, and the IOU type also changes depending on if it's a money request, bill split, etc.

You can check out the PR to see what we ended up going with!

**Comment by jeet-dhandha** [comment] 2023-07-04 05:17
Cool 👍 . Glad to be of Help.

**Comment by Julesssss** [comment] 2023-07-04 08:38
Fix PR is just awaiting a C+ review 👍

**Comment by Julesssss** [comment] 2023-07-04 13:14
Pr merged, now CPing

**Comment by dangrous** [comment] 2023-07-05 20:21
PR has been commented on.

I'm guessing we already have this as a regression test, but if not, it should be:

1. Click on FAB > Request money
2. Click on the currency
3. Click on the back button at the top
5. Back button should take user back and it should work properly

@Julesssss do you think we need a discussion in #expensify-bugs? I think it's just double checking any merge conflicts, which is generally the procedure, so I don't think we need anything new.

**Comment by dangrous** [comment] 2023-07-07 20:05
why did we get this checklist twice?

Answers copied here.

> PR has been commented on.
> 
> I'm guessing we already have this as a regression test, but if not, it should be:
> 
> 1. Click on FAB > Request money
> 2. Click on the currency
> 3. Click on the back button at the top
> 4. Back button should take user back and it should work properly
> 
> @Julesssss do you think we need a discussion in #expensify-bugs? I think it's just double checking any merge conflicts, which is generally the procedure, so I don't think we need anything new.

**Comment by Julesssss** [comment] 2023-07-10 10:27
> do you think we need a discussion in #expensify-bugs? I think it's just double checking any merge conflicts, which is generally the procedure, so I don't think we need anything new.

Nah I think we're good. This was raised by a regression test anyway.

**Comment by dangrous** [comment] 2023-07-10 15:29
Adding @abdulrahuman5196 so they can get paid for PR review when the time comes

**Comment by laurenreidexpensify** [comment] 2023-07-12 12:27
This has been on prod https://github.com/Expensify/App/pull/22135#issuecomment-1622166116 for 7 days, so I'm going to pay now

**Comment by laurenreidexpensify** [comment] 2023-07-12 12:28
@abdulrahuman5196 pls apply here in Upwork https://www.upwork.com/jobs/~01805773f0aa3fe2ec thanks

**Comment by Nathan-Mulugeta** [comment] 2023-07-12 12:42
Hey @laurenreidexpensify I also applied for the reporting bonus

**Comment by abdulrahuman5196** [comment] 2023-07-17 09:25
Not overdue.

@laurenreidexpensify Pending on the payment on this issue

**Comment by laurenreidexpensify** [comment] 2023-07-18 09:22
Apols @abdulrahuman5196 @Nathan-Mulugeta - offers now sent in Upwork

**Comment by abdulrahuman5196** [comment] 2023-07-18 09:32
@laurenreidexpensify  accepted the invite

**Comment by Nathan-Mulugeta** [comment] 2023-07-18 10:18
Accepted offer

**Comment by laurenreidexpensify** [comment] 2023-07-19 12:42
Payments issued, closing

**Closed by laurenreidexpensify** 2023-07-19 12:42 UTC
Labels: Engineering, Daily, Awaiting Payment, Bug
