### ISSUE TITLE
App crashed clicking on the notification

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#30643] opened 2023-10-31 15:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** needs reproduction
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @quinthar 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1698699280477699

## Action Performed:
1. Get a notification
2. Click on the notification

## Expected Result:
App should not crash

## Actual Result:
App crashed and refreshing didn't help. After sign out, infinite report open loops. 
(Attached onyx data as well)
## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

![image (4)](https://github.com/Expensify/App/assets/43996225/0c51e4ff-41bd-4b6a-9eb0-5c4ac756cf66)

![image (3)](https://github.com/Expensify/App/assets/43996225/70d46dcf-09fd-4298-80df-a08b76f5653c)

![image (2)](https://github.com/Expensify/App/assets/43996225/1a3d38a1-dd5c-4f38-b083-09d11229b9e1)

![image (1)](https://github.com/Expensify/App/assets/43996225/f454482a-6764-42d0-82ff-a287f48ae772)

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by trjExpensify** [comment] 2023-10-31 17:39
There's [this issue](https://github.com/Expensify/App/issues/28932) in the repo where the app crashes from a notification related to IOUs being the root cause. By reproducing that issue, I run into the same console error logged above: 

<img width="1511" alt="image" src="https://github.com/Expensify/App/assets/16232057/94e6acf4-21dc-4447-8c4c-c2b1d64f348f">

So with that, I'm reasonably chalking this up to being the same bug and closing in favour of the existing issue.

**Closed by trjExpensify** 2023-10-31 17:39 UTC
Labels: Daily, Bug
