### ISSUE TITLE
[$250] [HOLD for payment 2024-07-10] [Search v1] Description doesn't show if merchant is always empty

### ISSUE THREAD

**Issue by luacmartins** [Expensify/App#44180] opened 2024-06-21 19:50 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:
1. Track an expense and enter a description
2. Verify that the description doesn't show and we instead show an empty `Merchant` column

## Expected Result:
Description should show

## Actual Result:
Empty merchant column shows

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018090f57984a646e4</li>
        <li>Upwork Job ID: 1811525031241934419</li>
        <li>Last Price Increase: 2024-07-11</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @alexpensify</details>

**Comment by alexpensify** [comment] 2024-06-21 22:15
@luacmartins, it looks like you are working on the PR, and @dukenv0307 is reviewing it. Let me know if we need any other updates here. Thanks!

**Comment by Julesssss** [comment] 2024-06-26 09:37
Hi, we had a bug raised [here](https://github.com/Expensify/App/issues/44431) that I believe is an edge case when no merchant information is available. I don't think it should be a blocker, but please could you confirm that the expected behaviour is for ordering by description to be desired behaviour (and should be fixed). Thanks!

**Comment by alexpensify** [comment] 2024-06-28 18:01
Waiting for this one to go to production

**Comment by alexpensify** [comment] 2024-07-09 22:10
@dukenv0307—To prepare for the payment date, I think this notice is wrong: https://github.com/Expensify/App/issues/44180#issuecomment-2207070262. Please let me know if I need to send the offer via Upwork. Thanks!

**Comment by alexpensify** [comment] 2024-07-10 17:25
Payouts due:

- [ ] Contributor: N/A - Internal 
- [ ] Contributor+: $250 @dukenv0307 

Upwork job is TBD. Waiting to confirm this question: https://github.com/Expensify/App/issues/44180#issuecomment-2218816789

**Comment by alexpensify** [comment] 2024-07-11 22:24
I figured out that I need to complete the payment process in Upwork. I sent over an offer in Upwork. @dukenv0307, please accept and I can complete the payment process. Thanks! 

https://www.upwork.com/jobs/~018090f57984a646e4

**Comment by alexpensify** [comment] 2024-07-16 22:12
Closing - I've completed the payment process in Upwork. All set here.

**Closed by alexpensify** 2024-07-16 22:12 UTC
Labels: External, Daily, Internal, Help Wanted, Overdue, Awaiting Payment, Bug
