### ISSUE TITLE
[$500] New Chat - CMD+SHIFT+K opens New chat modal on the right instead of the left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34280] opened 2024-01-10 18:22 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.24-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Go to staging.new.expensify.com
2. Open Search modal by CMD+K
3. Close the Search modal
4. Open New chat by CMD+SHIFT+K

## Expected Result:
New chat modal appears on the right side

## Actual Result:
New chat modal appears on the right side

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d5cf8715-d562-41dc-bf2a-d73baf063062

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0172a47278cc12bbff</li>
        <li>Upwork Job ID: 1745149104446296064</li>
        <li>Last Price Increase: 2024-01-10</li>
    </ul>
</details>

**Comment by paultsimura** [comment] 2024-01-10 18:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "New chat" drawer opens on the right side

### What is the root cause of that problem?
This was never addressed before: only the Search screen was moved to the left.

### What changes do you think we should make in order to solve the problem?
We should make corresponding changes to move the `SCREENS.RIGHT_MODAL.NEW_CHAT` to `SCREENS.LEFT_MODAL`, similar to what we've done with the `SCREENS.LEFT_MODAL.SEARCH`

### What alternative solutions did you explore? (Optional)

**Comment by paultsimura** [comment] 2024-01-10 18:38
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "New chat" drawer opens on the right side.

### What is the root cause of that problem?
This seems like a new feature request, as it was never addressed before: only the Search screen was moved to the left.

### What changes do you think we should make in order to solve the problem?
We should make corresponding changes to move the `SCREENS.RIGHT_MODAL.NEW_CHAT` to `SCREENS.LEFT_MODAL`, similar to what we've done with the `SCREENS.LEFT_MODAL.SEARCH`.

In `LeftModalNavigator`, add this screen, and remove it from the `RightModalNavigator`:

```js
<Stack.Screen
    name={SCREENS.LEFT_MODAL.NEW_CHAT}
    component={ModalStackNavigators.NewChatModalStackNavigator}
/>
```

And a couple of other trivial changes. Reference: [this PR](https://github.com/Expensify/App/pull/33499/files).

Result:


https://github.com/Expensify/App/assets/12595293/1801ba76-4b94-4132-b0cf-54ece2d94429



### What alternative solutions did you explore? (Optional)

**Comment by ebcabaybay** [comment] 2024-01-10 18:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
New Chat modal appears on the right side but should be on the left

### What is the root cause of that problem?
New Chat modal is included in RightModalNavigator

### What changes do you think we should make in order to solve the problem?
Modify the following: src/SCREENS.ts, LeftModalNavigator.tsx, RightModalNavigator.tsx, linkingConfig.ts

- In src/SCREENS.ts, move NEW_CHAT from RIGHT_MODAL to LEFT_MODAL
- Move <Stack.Screen name={SCREENS.LEFT_MODAL.NEW_CHAT} component={ModalStackNavigators.NewChatModalStackNavigator}/>  from RightModalNavigator.tsx to LeftModalNavigator.tsx
- In linkingConfig.ts, move SCREENS.NEW_CHAT.ROOT from NAVIGATORS.RIGHT_MODAL_NAVIGATOR to NAVIGATORS.LEFT_MODAL_NAVIGATOR

**Comment by shubham1206agra** [comment] 2024-01-11 04:10
@paultsimura's [proposal](https://github.com/Expensify/App/issues/34280#issuecomment-1885412920) looks good.

🎀 👀 🎀 C+ reviewed

**Comment by shubham1206agra** [comment] 2024-01-11 04:29
@aimane-chnaif Thanks for pointing out.

**Comment by hayata-suenaga** [comment] 2024-01-11 17:41
This is actually expected behavior.

If you click the global create button (the button floating on the bottom) and then click "Start chat", you realize that the search page appears on the right hand size.

Thank you @aimane-chnaif for double checking this 🙇 

And thank you for everyone who provided proposals, but because this is not a bug, I'll close this issue. 🙇

**Closed by hayata-suenaga** 2024-01-11 17:41 UTC
Labels: External, Daily, Help Wanted, Bug

**Comment by mountiny** [comment] 2024-01-11 17:50
correct this is expected! Thanks everyone!
