### ISSUE TITLE
[HOLD for payment 2024-04-29][$250] Share log - Chat icon is highlighted in Settings after returning from share destination

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39926] opened 2024-04-09 12:57 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.61-0
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Settings > About > Troubleshoot.
3. Enable "Client side logging".
4. Click View console debug.
5. Click Share log.
6. Select any share destination.
7. Tap on the back button until app returns to Settings page.

## Expected Result:
When returning to Settings page, the profile icon should be highlighted.

## Actual Result:
When returning to Settings page, the chat icon is highlighted.
When clicking on profile icon, app reopens the same settings page.

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/ab35f6a6-8b9e-4f05-80a1-3b8326219d59

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bd717be733d9cef5</li>
        <li>Upwork Job ID: 1777700496702263296</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Reviewer | 0</li>
<li>bernhardoj | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-09 12:57
We think that this bug might be related to #wave-collect - Release 1

**Comment by amyevans** [comment] 2024-04-09 14:08
Not a blocker

**Comment by bernhardoj** [comment] 2024-04-09 17:31
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Chat icon of bottom tab bar is highlighted after sharing the client side logging to a chat. I can reproduce this on prod too.

### What is the root cause of that problem?
The chat icon will be highlighted if the `currentTabName` is HOME.

https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L88

`currentTabName` takes the topmost bottom tab navigator route name.

https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/libs/Navigation/AppNavigator/createCustomBottomTabNavigator/BottomTabBar.tsx#L66-L69

When we open settings, the bottom tab navigator will be:
[HOME, SETTINGS]

When we press "Share log" and select the chat, it will navigate to the report.
https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/pages/settings/AboutPage/ShareLogList/index.tsx#L17-L18

Report screen is a central pane, so when we do the navigation, it will find the match bottom tab for report screen and it's HOME (LHN).
https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/libs/Navigation/linkTo.ts#L160-L175

So, now we have 3 routes in the bottom tab navigator,
[HOME, SETTINGS, HOME]

When we press go back from the report screen, the bottom tab navigator stays unchanged. That's why we see the chat icon is highlighted.

On large screen (web), when you press the browser back button, both the report screen and the bottom tab route (HOME) is removed.

### What changes do you think we should make in order to solve the problem?

Don't push the extra bottom tab route if it's a narrow layout.
https://github.com/Expensify/App/blob/455dce42bb99bb1c0987249de341d9319316bbfe/src/libs/Navigation/linkTo.ts#L170-L175

```
if (!isNarrowLayout && ...) {
    // push bottom tab route
}
```

_we can consider dismissing the modal too_

**Comment by DylanDylann** [comment] 2024-04-10 07:12
@bernhardoj I agree with your RCA, It is correct. Could you help to detail your solution? 
1. Why should we do that?
2. Is there any effect to another feature?

**Comment by bernhardoj** [comment] 2024-04-10 07:26
> Why should we do that?

We don't need the extra bottom tab route on a small screen. On a large screen, we need to add it, otherwise, the user will see this:
<img width="1718" alt="image" src="https://github.com/Expensify/App/assets/50919443/cb3d311e-cc9e-4224-b0e3-97e8a11bdc3f">

> Is there any effect to another feature?

I think no.

**Comment by bernhardoj** [comment] 2024-04-10 15:50
Updated my [proposal](https://github.com/Expensify/App/issues/39926#issuecomment-2045747982).

**Comment by DylanDylann** [comment] 2024-04-12 09:09
@bernhardoj I am confused about your solution. Currently, `getTopmostBottomTabRoute` gets the last route in "BottomTabNavigator"

https://github.com/Expensify/App/blob/c7d692662d069ef8d9c756833767c47e1f7410a2/src/libs/Navigation/getTopmostBottomTabRoute.ts#L11

**Comment by DylanDylann** [comment] 2024-04-12 09:12
IMO, When going back from the report screen by clicking the back button. The bottom tab navigator should be updated to [HOME, SETTINGS]. What do you think about that?

**Comment by bernhardoj** [comment] 2024-04-12 13:39
> Currently, getTopmostBottomTabRoute gets the last route in "BottomTabNavigator"

It takes the last route from the found bottom tab navigator, but it takes the first route from the root navigator
<img width="877" alt="image" src="https://github.com/Expensify/App/assets/50919443/3b46b22f-0bbc-4068-8c05-1c25d49cfc3e">

> The bottom tab navigator should be updated to [HOME, SETTINGS]. What do you think about that?

Not sure, how do we know when to pop the bottom tab? We can't always pop it when pressing back from the report screen.

I think maybe removing the fallback route is the best we can do for now. We previously removed all ROUTES.HOME from fallback [here](https://github.com/Expensify/App/pull/36050).

**Comment by DylanDylann** [comment] 2024-04-15 08:53
@bernhardoj 

> It takes the last route from the found bottom tab navigator, but it takes the first route from the root navigator

Which is the last route that you mentioned? And also explain why should we do that

**Comment by bernhardoj** [comment] 2024-04-15 09:01
```
[
bottom tab navigator: [HOME, SETTINGS, HOME],
central pane navigator: [ABOUT],
]
```

If this is the root state, then the first route is `bottom tab navigator` and the last sub-route is HOME. We do that because we want to get the focused bottom tab route.

**Comment by DylanDylann** [comment] 2024-04-15 09:19
> If this is the root state, then the first route is bottom tab navigator and the last sub-route is HOME

@bernhardoj It seems it is the current logic. I am not sure I understand your mean, please help to detail your solution

**Comment by bernhardoj** [comment] 2024-04-15 09:27
I thought you are asking about the current logic, no?

> It takes the last route from the found bottom tab navigator, but it takes the first route from the root navigator

> Which is the last route that you mentioned? And also explain why should we do that

**Comment by DylanDylann** [comment] 2024-04-15 10:00
@bernhardoj in your proposal, you suggest that:

> We can update getTopmostBottomTabRoute so it takes the last found bottom tab navigator.

Please help to detail your solution

**Comment by bernhardoj** [comment] 2024-04-15 10:45
Updated my [proposal](https://github.com/Expensify/App/issues/39926#issuecomment-2045747982) to include the code.

**Comment by DylanDylann** [comment] 2024-04-16 07:56
@bernhardoj's proposal looks good to me

🎀 👀 🎀 C+ reviewed

**Comment by bernhardoj** [comment] 2024-04-17 04:58
PR is ready

cc: @DylanDylann

**Comment by alexpensify** [comment] 2024-04-17 21:31
## Heads up, I will be offline until Tuesday, April 23, 2024, and will not actively watch over this GitHub during that period.

If anything urgent is needed here, please ask for help in the #expensify-open-source Slack Room-- thanks!

**Comment by alexpensify** [comment] 2024-04-23 23:26
I checked in and it looks like this PR was merged yesterday. Now, let's wait for automation to kick in.

**Comment by amyevans** [comment] 2024-04-24 14:42
Hmm it was deployed to production already which is when the automation should post, so it seems like that failed. I'll update the title manually - due for payment 7 days after 4/22 so 4/29.

**Comment by alexpensify** [comment] 2024-04-26 21:10
Thanks! Noted for April 29.

**Comment by alexpensify** [comment] 2024-04-29 23:20
Payouts due: April 29, 2024

- [ ] Contributor: $250 @bernhardoj 
- [ ] Contributor+: $250 @DylanDylann 

Upwork job is [here](https://www.upwork.com/jobs/~01bd717be733d9cef5).

**Comment by alexpensify** [comment] 2024-04-29 23:33
Closing - the list above has been paid via Upwork.

**Closed by alexpensify** 2024-04-29 23:33 UTC
Labels: External, Engineering, Weekly, Awaiting Payment, Bug
