### ISSUE TITLE
[$500] IOU - LHN for IOU report shows the local currency when a different currency is requested

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31838] opened 2023-11-24 16:24 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.3.2
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to staging.new.expensify.com.
2. Go to 1:1 DM.
3. Click + > Request money.
4. Create a manual request using a different currency.
5. Click on the IOU preview to open IOU report.
Note that the amount for the IOU report in LHN shows the local currency instead of the requested currency.

## Expected Result:
The amount on the IOU report preview in LHN shows the requested currency.

## Actual Result:
The amount on the IOU report preview in LHN shows the local currency instead of the requested currency.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/cfa177d3-e14a-4c7e-b67a-1924a5ef9e71

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01043f00e7b200b13f</li>
        <li>Upwork Job ID: 1728104571576659968</li>
        <li>Last Price Increase: 2023-11-24</li>
<li>Automatic offers: </li>
<ul>
<li>s-alves10 | Contributor | 27819459</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-11-24 17:23
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

LHN for IOU report shows the local currency when a different currency is requested

### What is the root cause of that problem?

This is a regression of the PR https://github.com/Expensify/App/pull/31061

https://github.com/Expensify/App/blob/e355608a9e0ee107abe06f610031c80f74ed8fa8/src/libs/OptionsListUtils.js#L388
As you can see above, we used the currency of the iou report instead of the currency of original message

This is the root cause

### What changes do you think we should make in order to solve the problem?

Updating the above code to
```
        const formattedAmount = CurrencyUtils.convertToDisplayString(amount, reportAction.originalMessage.currency);
```
solves the issue

<details>
    <summary>Result</summary>



</details>

### What alternative solutions did you explore? (Optional)

**Comment by marcochavezf** [comment] 2023-11-24 17:53
Thanks @s-alves10, the proposal LGTM, let's do it

**Comment by JmillsExpensify** [comment] 2023-11-24 19:52
Draft PR linked above.

**Comment by s-alves10** [comment] 2023-11-24 20:05
PR is ready for review https://github.com/Expensify/App/pull/31855

**Comment by luacmartins** [comment] 2023-11-24 22:42
We CPed a revert. Gonna close this issue.

**Closed by luacmartins** 2023-11-24 22:42 UTC
Labels: Reviewing, External, Engineering, Weekly, Bug
