### ISSUE TITLE
[HOLD for payment 2023-06-21] [$1000] Web - Attachment - The attachments carousel repeats the same image if press the Next key after clicking on any attachment

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#19484] opened 2023-05-23 19:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App
2. Go to any Chat and send a few attachments (images, videos)
3. Press on any attachments, and now press the Right Arrow key from the keyboard. It will load the next attachment.
4. Now Press the Arrow left key from the keyboard to load the previous attachment.
5. Now click on anywhere on the attachment
6. Now Press either the Left Arrow or Right Arrow key again

## Expected Result:
It should load the next attachment in the carousel

## Actual Result:
It will load the same and the same attachment again

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.17.0

**Reproducible in staging?:** yes

**Reproducible in production?:** yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/a4fb5554-0db6-49f2-870a-b712929d931b

https://github.com/Expensify/App/assets/93399543/9c418dcf-77c2-49bd-9b8c-8561b9fecbdd

**Expensify/Expensify Issue URL:**

**Issue reported by:**  @jayeshmangwani

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1684419981493959?thread_ts=1684419948.108039&cid=C049HHMV9SM

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011bb3ee21de3f842b</li>
        <li>Upwork Job ID: 1661231781339181056</li>
        <li>Last Price Increase: 2023-05-31</li>
    </ul>
</details>

**Comment by kadiealexander** [comment] 2023-05-24 04:43
Reproduced! 

https://github.com/Expensify/App/assets/59587260/39c26ddb-10b2-4473-97d8-4ec03ce5f6aa

Observed the same experience on the desktop app.

**Comment by akinwale** [comment] 2023-05-24 04:47
The videos included do not match the issue description.

**Comment by bhrvarsani22** [comment] 2023-05-24 06:50
The video and Upwork requirement does not match.

**Comment by bhrvarsani22** [comment] 2023-05-24 06:55
The video and Upwork requirement does not match.

**Comment by tienifr** [comment] 2023-05-24 08:41
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
It will load the same and the same attachment again when we zoom an attachment and click `ArrowLeft`

### What is the root cause of that problem?
The root cause is that we have `AttachmentCarousel` as a horizontal `FlatList` here https://github.com/Expensify/App/blob/d70b7462cd698a50aa121310f69b815e9f7cc9fa/src/components/AttachmentCarousel/index.js#L340, when we focus on the list element and press `ArrowLeft`, by default the behavior of the horizontal list when pressing ArrowLeft will be to scroll to the left, which will scroll it to the last element (before the first element).

We already have our own `'ArrowLeft'` event listener here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/components/AttachmentCarousel/CarouselActions/index.js#LL19C3-L19C3 which will not cycle to the last element if currently we're on the first element. 

But it will still scroll due to default list behavior.

### What changes do you think we should make in order to solve the problem?


We need to add `e.preventDefault` here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/components/AttachmentCarousel/CarouselActions/index.js#L20 and here https://github.com/Expensify/App/blob/e9f6a373e70a75d49dda333233ff952ea65e7cb3/src/components/AttachmentCarousel/CarouselActions/index.js#L23 so that the list will follow our custom `ArrowLeft` and `ArrowRight` behavior rather than using the default behavior.

### What alternative solutions did you explore? (Optional)
NA

**Comment by kadiealexander** [comment] 2023-05-25 04:24
@bhrvarsani22 and @akinwale, the videos in the OP have been updated, please take another look.

**Comment by bhrvarsani22** [comment] 2023-05-25 05:11
Checking...

**Comment by kadiealexander** [comment] 2023-05-30 01:55
@aimane-chnaif any thoughts on the proposal here? https://github.com/Expensify/App/issues/19484#issuecomment-1560695631

**Comment by situchan** [comment] 2023-05-31 22:32
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
 The attachments carousel repeats the same image if press the Prev/Next key after focusing on it

### What is the root cause of that problem?
The default behavior of FlatList is applied. As scroll is horizontal, arrow left/right controls scroll position as default.

### What changes do you think we should make in order to solve the problem?
We can fully deprecate current `/CarouselActions/index.js` (document event listener) and use native code in `/CarouselActions/index.native.js` (our own keyboard shortcut handler) which already prevents default behavior (8th param in [subscribe](https://github.com/Expensify/App/blob/c68c84a4a0ddf58e22640d6b99d47a01557c2daf/src/libs/KeyboardShortcut/index.js#L118) function - default value is true)

**Comment by kadiealexander** [comment] 2023-06-02 04:56
@thienlnam any thoughts? :)

**Comment by thienlnam** [comment] 2023-06-05 15:25
Oh wow, sorry missed this when I came back from OOO - catching up on the convo now

**Comment by thienlnam** [comment] 2023-06-05 15:48
I agree we should remove platform specific code whenever we can - especially if native functionality can now handle it. I do like @situchan's proposal the best, can you please update it though to include the new elements from the conversation

**Comment by situchan** [comment] 2023-06-05 15:54
> especially if native functionality can now handle it

yes, attachment keyboard shortcuts is natively supported from #18407.
I see that in that PR, web component is refactored to functional component instead of deprecation.
Before going ahead, I'd like to get confirmation from @luacmartins if it was intentional to leave web code as is or just never thought of deprecation in favor of native code.

**Comment by luacmartins** [comment] 2023-06-05 17:32
@situchan sorry, could you clarify which specific web code and native code you are talking about?

**Comment by situchan** [comment] 2023-06-05 17:34
[/components/AttachmentCarousel/CarouselActions/index.js](https://github.com/Expensify/App/pull/18407/files#diff-f411594efbdec09ed8861ca9001e292e06d19e1e6347a6ab8d5258a3ff6d642b)
[/components/AttachmentCarousel/CarouselActions/index.native.js](https://github.com/Expensify/App/pull/18407/files#diff-467811f762980c8c35651906e8aced36923e28e55b585f16d7248644d748b400)

**Comment by luacmartins** [comment] 2023-06-05 19:06
hmm that's a good point. I think it was an oversight. AFAIK we should be using `KeyboardShortcut` for all platforms.

**Comment by thienlnam** [comment] 2023-06-05 19:33
Awesome, thanks!

**Comment by kadiealexander** [comment] 2023-06-19 07:39
@sakluger I'm going OOO so I'm reassigning this for payment. I've sent offers to @aimane-chnaif and @situchan, but I couldn't proactively find @jayeshmangwani on Upwork. You can find them all [here](https://www.upwork.com/ab/applicants/1661231781339181056/hired). 

@jayeshmangwani please apply on Upwork so we can issue your reporting bonus: [upwork.com/jobs/~011bb3ee21de3f842b](https://www.upwork.com/jobs/~011bb3ee21de3f842b)

**Comment by jayeshmangwani** [comment] 2023-06-19 07:49
@kadiealexander applied on Upwork

**Comment by sakluger** [comment] 2023-06-21 17:29
- @jayeshmangwani thanks for applying, I sent you a contract through Upwork.
- @situchan I sent you payment with bonus.
- @aimane-chnaif could you please complete the BZ checklist? Thanks!

**Comment by sakluger** [comment] 2023-06-21 20:17
Thanks! Those proposed steps look good to me. 👍 

All paid up, ready to close!

**Closed by sakluger** 2023-06-21 20:17 UTC
Labels: External, Daily, Awaiting Payment, Bug

**Comment by jayeshmangwani** [comment] 2023-06-23 06:23
@sakluger Can you please release Milestone at Upwork its showing In Progress to me
