### ISSUE TITLE
[$250] Chat – Inbox not uploaded when login to old accounts with a lot of chats and long history

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#46054] opened 2024-07-23 16:59 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.11-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Log in with [applausetester+jpcategory_1@applause.expensifail.com](mailto:applausetester+jpcategory_1@applause.expensifail.com)
or [applausetester+jp_e_category_1@applause.expensifail.com](mailto:applausetester+jp_e_category_1@applause.expensifail.com)

## Expected Result:
Inbox uploaded, chats open

## Actual Result:
Inbox not uploaded, LHN is empty, only Concierge chat opens after page refresh

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/user-attachments/assets/c5e138ef-03d5-4199-bc3a-e681dd7bd06f

[logs (2).txt](https://github.com/user-attachments/files/16352051/logs.2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016217549831ad6eee</li>
        <li>Upwork Job ID: 1818043406281563066</li>
        <li>Last Price Increase: 2024-09-09</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @allgandalf</details>

**Comment by strepanier03** [comment] 2024-07-29 21:51
I doublechecked and I don't have the ability to log in with either of those emails because I don't have access to those inboxes.

**Comment by rezkiy37** [comment] 2024-08-20 09:03
Hi, I’m Michael (Mykhailo) from Callstack and I would like to work on this issue.

**Comment by rezkiy37** [comment] 2024-08-20 11:16
Hi, I am Michael (Mykhailo) from Callstack, an expert agency and I can work on this issue.

**Comment by rezkiy37** [comment] 2024-08-20 12:03
Hey! @lanitochka17 Applause - Internal Team
I've tried to reproduce the bug on my accounts. They work properly now. So can you help me?

1. Please confirm if the **OpenApp** API request succeeds with many reports in `onyxData`.

<details><summary>Details</summary>


<img width="1010" alt="Screenshot 2024-08-20 at 13 54 40" src="https://github.com/user-attachments/assets/9c927990-2564-4f4d-a7b3-5c61752ddaa2">


</details> 


2. Please confirm if Onyx has applied the backend responses and if there are many reports. 

<details><summary>Details</summary>


<img width="1517" alt="Screenshot 2024-08-20 at 13 55 23" src="https://github.com/user-attachments/assets/aaa27b62-238a-485f-bbbf-c3ed2883b255">


</details> 

Also, I would ask you to gimme access to your accounts (_applausetester+jpcategory_1@applause.expensifail.com, applausetester+jp_e_category_1@applause.expensifail.com_). You can configure email sharing (_via **Groups Google**_) and allow my email (_mykhailo.kravchenko@callstack.com_) to receive emails for yours. Therefore I can log in and test on my side.

**Comment by rezkiy37** [comment] 2024-08-21 09:55
Waiting on an answer - https://github.com/Expensify/App/issues/46054#issuecomment-2298690534.

**Comment by rezkiy37** [comment] 2024-08-22 08:05
@lanitochka17 , bump https://github.com/Expensify/App/issues/46054#issuecomment-2298690534.

**Comment by mvtglobally** [comment] 2024-08-23 12:05
Issue not reproducible during KI retests. (First week)

**Comment by rezkiy37** [comment] 2024-08-28 15:16
I just tested on this account - applausetester+jpcategory_1@applause.expensifail.com. I don't have this bug on the latest main and production server. Please retest and then close the issue if it is not replicable.


https://github.com/user-attachments/assets/fdf2ba9a-f32c-4cc2-9fe1-98426c5d1323

<img width="1189" alt="Screenshot 2024-08-28 at 17 09 32" src="https://github.com/user-attachments/assets/76ffdec9-fcdc-487c-90e4-120ac5572424">

**Comment by rezkiy37** [comment] 2024-08-30 08:10
Who can help me to close the issue? 
cc @allgandalf @mvtglobally @lanitochka17

**Comment by rezkiy37** [comment] 2024-09-03 16:23
Hey!
I will be OOO from 04.09 (_afternoon_) till 09.09. I will continue to work on this one once I am back.

**Comment by rezkiy37** [comment] 2024-09-04 07:18
> @allgandalf: Oh just checked @strepanier03 are OoO until tuesday,

Bump 🙂

**Comment by mvtglobally** [comment] 2024-09-09 04:09
Issue not reproducible during KI retests. (Second week)

**Comment by rezkiy37** [comment] 2024-09-09 10:43
Can we close the issue?

**Comment by rezkiy37** [comment] 2024-09-12 09:02
@allgandalf @strepanier03 https://github.com/Expensify/App/issues/46054#issuecomment-2337770446

**Closed** 2024-09-12 15:32 UTC
Labels: External, Weekly, Help Wanted, Bug
