### ISSUE TITLE
[$500] Unable to mark system message unread in one transaction view

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#39407] opened 2024-04-02 14:36 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Set up a collect policy with workspace chats (if necessary. Instructions here: https://expensify.slack.com/archives/C01GTK53T8Q/p1710887185511369?thread_ts=1710886648.492359&cid=C01GTK53T8Q)
2. Go to staging.new.expensify.com
3. Go to workspace chat that has no unsettled requests.
4. Create a manual request.
5. Set the category on the request.
6. Right click the `set the category to "<category>".` message and select "Mark as unread".
7. Scroll up and click New messages button.
8. Send a message in the report.
9. Mark the second message as unread.
10. Mark the first message (Expensify) as unread.

## Expected Result:
The system message is marked as unread

## Actual Result:
The system message is not marked as unread

## Workaround:
n/a

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/7cc61188-f091-49d0-b185-5ee6c6db3c8c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01280f37ab9c88e291</li>
        <li>Upwork Job ID: 1775321731724582912</li>
        <li>Last Price Increase: 2024-04-17</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 0</li>
<li>nkdengineer | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by kbecciv** [comment] 2024-04-02 14:37
We think that this bug might be related to #wave-collect - Release 1

**Comment by amyevans** [comment] 2024-04-02 17:30
Production:


https://github.com/Expensify/App/assets/7277067/9859e465-f7f4-4d5c-bbe7-1c021730e529

**Comment by amyevans** [comment] 2024-04-02 20:36
Asked in Slack for some help [here](https://expensify.slack.com/archives/C03TQ48KC/p1712089084864309) and [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1712090040218899), not making a ton of progress diagnosing this one

**Comment by amyevans** [comment] 2024-04-03 00:39
(Opening this up for help from the community but will pick up personally investigating it more tomorrow)

**Comment by amyevans** [comment] 2024-04-03 01:04
One final thought for the night, I believe this is the new One Transaction Report view cc @NikkiWines, maybe you have a better sense of what's going on here?

**Comment by NikkiWines** [comment] 2024-04-03 02:02
Yep, likely related. Probably because [this logic](https://github.com/Expensify/App/blob/6abecc8b951b9b589f53a400727c36ae16bdf2ea/src/pages/home/report/ReportActionsList.tsx#L389-L398) (and `hasNewestReportAction`) wasn't updated when I added that view. I've noticed the scroll-down works fine with reportActions that occur on the report (e.g. commenting) but not with actions that occur on the expense (updating the merchant) 

I'll look into a fix but this wasn't accounted for in the initial PR we can maybe remove the blocker label for the moment since it's an easy work around for a one-expense report. What do you think?

**Comment by NikkiWines** [comment] 2024-04-03 02:12
Ooh actually, I think this might end up being resolved as a byproduct of implementing [this proposal](https://github.com/Expensify/App/issues/39420#issuecomment-2032718267) because it updates the logic in `getOriginalReportID` which we use in generating the unread indicator. I'd be curious to retest this once those changes are implemented

**Comment by amyevans** [comment] 2024-04-03 19:22
> I've noticed the scroll-down (and indicator display) works fine with reportActions that occur on the report (e.g. commenting) but not with actions that occur on the expense (updating the merchant)

Okay nice, this made it a lot easier to test locally than fumbling around with SmartScan. I was able to reproduce by just creating an expense and updating a field on it, as you said.

I retested following the merge of the fix you mentioned (https://github.com/Expensify/App/pull/39474), unfortunately the issue is still reproducible:

https://github.com/Expensify/App/assets/7277067/9a6fd5c4-8165-4592-9ec9-938937276f15

* Any expense level report action cannot be marked unread
* If the latest report action on the report is from the expense level, the `New messages` button does not scroll you down

**Comment by ArekChr** [comment] 2024-04-08 07:52
Hello, I am Arek from Callstack - expert contributor group. I’d like to work on this issue.

**Comment by ArekChr** [comment] 2024-04-09 07:56
I have tried to reproduce this bug many times but it seems it can no longer be reproduced, not sure if I missed something

**Comment by amyevans** [comment] 2024-04-09 16:11
Asked [here](https://expensify.slack.com/archives/C9YU7BX5M/p1712679050205209)

**Comment by kbecciv** [comment] 2024-04-09 16:50
The QA team is unable to verify the issue due to the absence of the Expensify message mentioned in the https://github.com/Expensify/App/issues/39937

**Comment by amyevans** [comment] 2024-04-12 16:59
I am still able to reproduce on staging following the modified steps (that don't depend on SmartScanning to repro). @ArekChr can you try the following?

1. Set up a collect policy with workspace chats (if necessary. Instructions here: https://expensify.slack.com/archives/C01GTK53T8Q/p1710887185511369?thread_ts=1710886648.492359&cid=C01GTK53T8Q)
2. Go to a workspace chat that has _no unsettled requests_.
3. Create a manual request.
4. Change the category on the request.
5. Right click the `set the category to "<category>".` message and select "Mark as unread".

Expected result:
The system message is marked as unread

Actual result:
The system message is not marked as unread

**Comment by ArekChr** [comment] 2024-04-16 08:07
@paultsimura Sorry for the delay. I'm currently highly focused on other stuff. Could you please assign me?

**Comment by amyevans** [comment] 2024-04-16 21:37
Updated the title and OP!

**Comment by nkdengineer** [comment] 2024-04-17 07:16
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The system message is not marked as unread

### What is the root cause of that problem?

When we mark as unread a system message in one transaction view, that is we are updating the lastReadTime of transaction thread report and we emit a event for the transaction thread report.

https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/libs/actions/Report.ts#L1079

So in one transaction view, we don't receive this event and then unread marker isn't updated.
https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/pages/home/report/ReportActionsList.tsx#L287
### What changes do you think we should make in order to solve the problem?
In `ReportActionsList`, we should subscribe the unreadAction event for transaction thread report and update the unread marker as we do here

```
const unreadActionSubscriptionForTransactionThread = DeviceEventEmitter.addListener(`unreadAction_${transactionThreadReport?.reportID}`, (newLastReadTime) => {
    resetUnreadMarker(newLastReadTime);
    setMessageManuallyMarkedUnread(new Date().getTime());
});

return () => {
    ...
    unreadActionSubscriptionForTransactionThread.remove();
}
```

https://github.com/Expensify/App/blob/21ee1a3772253538bba74b2bc655213dc7bdb68a/src/pages/home/report/ReportActionsList.tsx#L287-L289

OPTIONAL: We can also subscribe other event like `readNewestAction`, `deletedReportAction` as well if it needs.

### What alternative solutions did you explore? (Optional)
In `markAsUnread` function and other functions that emits these event, we can check if the report is one transaction thread, we will emit the event to the parent report of its.

### Result

https://github.com/Expensify/App/assets/161821005/72b6d5e5-115c-4264-9875-e56f422e9612

**Comment by nkdengineer** [comment] 2024-04-17 09:43
> @nkdengineer thanks for your proposal – it makes sense and fixes the "mark unread" issue, but still lacks the fix for the "New messages" button – it does nothing on click. Could you please update the proposal to cover it as well?

Thanks for your feedback. About `New message` button, the problem is here. If the one transaction view has only report action of transaction thread report. `hasNewestReportAction` is always `false`


https://github.com/Expensify/App/blob/314f2d3070ff7d6535f37582c82373bbaaac3d38/src/pages/home/report/ReportActionsList.tsx#L199.

And then it does nothing because we navigate to the report and call `openReport` API in this case


https://github.com/Expensify/App/blob/314f2d3070ff7d6535f37582c82373bbaaac3d38/src/pages/home/report/ReportActionsList.tsx#L388-L392

We should update `hasNewestReportAction` like this 

```
const hasNewestReportAction = (sortedReportActions?.[0].created === report.lastVisibleActionCreated) || (sortedReportActions?.[0].created === transactionThreadReport?.lastVisibleActionCreated);

```

https://github.com/Expensify/App/blob/314f2d3070ff7d6535f37582c82373bbaaac3d38/src/pages/home/report/ReportActionsList.tsx#L199.

Updated proposal https://github.com/Expensify/App/issues/39407#issuecomment-2060546638 to include this.

**Comment by kmbcook** [comment] 2024-04-17 15:50
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Unable to mark system message as unread in one transaction view.

### What is the root cause of that problem?
When the first IOU is created, of a group of IOUs shown in a report preview, the transaction report for that IOU is obscured. Rather than viewing the actual transaction report, the user views the IOU report. When there is more than one IOU in the IOU report the user chooses which IOU to view. After clicking on the desired IOU the user is able to view the transaction report for that IOU. In this case there is only one IOU in the IOU report. What the user sees looks like a transaction report for the one and only IOU, but the user is actually viewing the IOU report itself. The transaction report is obscured.

In this situation any comments the user makes are attached to the IOU report, not the transaction report. When the user changes the category, the system generates a message and that message is attached to the transaction report, rather than to the IOU report.

When the user marks the system message as unread the transaction report is marked as unread, but that report is obscured. The IOU report is not marked as unread.

### What changes do you think we should make in order to solve the problem?
In this situation it is not a good idea to attach any comments, made by the user or by the system, to the IOU report since from the users perspective the comments are expected to be attached to the transaction report since what the user sees looks exactly like a transaction report (a report of the details of the transaction).

If the user makes a comment or changes the category, change the view to match that when there is more than one IOU in the IOU report. This will solve the problem.

**Comment by kmbcook** [comment] 2024-04-17 15:57
@paultsimura I noticed the thumbs down reaction. I'm not sure why the quick rejection. Did you notice that if the user makes a comment, and then later makes another money request, that from the user's perspective the comment disappears from the transaction report? (It doesn't actually disappear, it can be seen in the IOU report.)

**Comment by kmbcook** [comment] 2024-04-17 16:18
@paultsimura I added to my proposal to explain how the desired UI design can be preserved.

**Comment by kmbcook** [comment] 2024-04-17 18:20
Here is my comment in the open source channel: https://expensify.slack.com/archives/C01GTK53T8Q/p1713375493419829

**Comment by nkdengineer** [comment] 2024-04-17 18:42
> The formatting of the proposal in the end is broken;

1. Fixed this now

> Marking the system message with your solution only adds the green line in the report, but doesn't mark it as unread in the LHN (the report title doesn't become bold).

2. To fix this, we can get `transactionThreadReport` in `LHNOptionsList` and pass it to `OptionRowLHNData` and then pass this to `getOptionData` here.

https://github.com/Expensify/App/blob/b35d35739a6cf9c4b011605a5bd629920e7b066e/src/libs/SidebarUtils.ts#L186

With this change we will update the unread condition here to 

```
result.isUnread = (ReportUtils.isUnread(report) && !!report.lastActorAccountID) || (transactionThreadReport.isUnread(report) && !!transactionThreadReport.lastActorAccountID); 

```

https://github.com/Expensify/App/blob/b35d35739a6cf9c4b011605a5bd629920e7b066e/src/libs/SidebarUtils.ts#L270

We can also pass `transactionThreadReportID` to `ContextMenuAction` payload and when we mark the report as read we will call `Report.readNewestAction(transactionThreadReportID)` as well if it's present.

https://github.com/Expensify/App/blob/b35d35739a6cf9c4b011605a5bd629920e7b066e/src/pages/home/report/ContextMenu/ContextMenuActions.tsx#L277?

> The "New button" fix is not complete – I guess we need to call Report.readNewestAction for the transactionThreadReport?.reportID if it's present – this can be seen if you pin both the 1-transaction report and the corresponding transaction thread:

You're correct, we also should call `Report.readNewestAction` for this report in `scrollToBottomAndMarkReportAsRead` function if it's present


Updated proposal https://github.com/Expensify/App/issues/39407#issuecomment-2060546638.

**Comment by kmbcook** [comment] 2024-04-18 14:53
Expanded my proposal with more detail.

**Comment by kmbcook** [comment] 2024-04-19 15:09
@paultsimura OK, but can't that particular aspect of the design be improved?

**Comment by kmbcook** [comment] 2024-04-19 15:26
Thank you

**Comment by sonialiap** [comment] 2024-04-22 10:07
@nkdengineer you've been assigned to this issue. Looking forward to your PR 😊

**Comment by nkdengineer** [comment] 2024-04-22 10:23
@paultsimura The PR is [here](https://github.com/Expensify/App/pull/40676).

**Comment by mountiny** [comment] 2024-04-26 14:11
@amyevans @paultsimura @nkdengineer We ended up reverting this PR because it caused a regression https://github.com/Expensify/App/issues/41088 where the combined report was showing as unread forever. We might need to find a backend fix for this as the `lastReadTime` of the combined report is not being updated when we add comments to the transaction thread

**Comment by sonialiap** [comment] 2024-05-02 13:32
@slafortune I'm OOO 2024-05-03 to 2024-05-06 so adding a BZ buddy to issue payment if I'm out when it becomes due

**Comment by amyevans** [comment] 2024-05-02 13:40
This one got reverted, we need to revisit

**Comment by nkdengineer** [comment] 2024-05-02 15:33
I will raise another PR soon.

**Comment by nkdengineer** [comment] 2024-05-03 05:47
@NikkiWines We need a backend fix here to update `lastReadTime` of transaction thread report correctly since when we edit money request now, BE returns `lastReadTime` of transaction thread report is always less than `lastVisibleActionCreated` that causing this bug https://github.com/Expensify/App/issues/41088 while reviewing my PR

<img width="1512" alt="Screenshot 2024-05-03 at 12 44 00" src="https://github.com/Expensify/App/assets/161821005/44e56d11-ed37-4846-a208-38a333108c93">

cc @amyevans

**Comment by amyevans** [comment] 2024-05-17 13:38
Nikki and I have chatted, we're both aware it needs a backend fix, just both a little swamped at the moment 😅. Sorry y'all. But one of us can hopefully get to it in maaaybe the next week?

**Comment by nkdengineer** [comment] 2024-06-04 02:39
@amyevans @NikkiWines Any update here.

**Comment by NikkiWines** [comment] 2024-06-06 04:48
Unfortunately, no - we've got some competing priorities currently, and this is a fairly esoteric bug for a user to encounter so it's not as high of a priority at this time.

**Comment by amyevans** [comment] 2024-06-14 22:06
Apologies as I should have probably done this a month ago when my bandwidth was looking low, but I'm unassigning from this GH since I'm out on extended leave after today.

Hopefully another internal engineer will be able to pick it up and help get it over the line, but as Nikki pointed out it is unfortunately not high priority on our roadmap so it may take a bit.

**Comment by sonialiap** [comment] 2024-06-21 08:42
Adding retest label since this has been open for over a month so that QA can retest to confirm if this is still an issue 🙏

**Comment by sonialiap** [comment] 2024-07-02 13:27
Asked for a retest in [slack](https://expensify.slack.com/archives/C9YU7BX5M/p1719926816757189)

**Comment by kavimuru** [comment] 2024-07-02 14:40
@sonialiap still reproduced.

https://github.com/Expensify/App/assets/43996225/810304e8-348f-4611-97a7-60e81ca9890b

**Comment by sonialiap** [comment] 2024-07-02 14:41
Thanks Kavi!

**Comment by sonialiap** [comment] 2024-07-23 10:10
[checking if we should close](https://expensify.slack.com/archives/C066HJM2CAZ/p1721729395916419)

**Comment by sonialiap** [comment] 2024-07-23 11:00
confirmed that this is not a priority, closing for now

**Closed by sonialiap** 2024-07-23 11:00 UTC
Labels: Engineering, Weekly, Internal, Bug

**Comment by nkdengineer** [comment] 2024-08-06 07:21
@sonialiap Should we be eligible for compensation here since we spent effort on the [PR](https://github.com/Expensify/App/pull/41555), the change is almost done, and we are only waiting for the BE change, thanks. We have the same case [here](https://github.com/Expensify/App/issues/39529#issuecomment-2217384202).

**Comment by sonialiap** [comment] 2024-08-08 11:45
Payment summary:
- @paultsimura $500 - paid in upwork
- @nkdengineer $500 - paid in upwork
