### ISSUE TITLE
iOS - More features - Word is too close to the page border

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#48565] opened 2024-09-04 15:00 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.29-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh010901@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
Precondition:
- Device used is iPhone 15 Pro Max.
- Device font size is third smallest font.

1. Launch New Expensify app.
2. Go to workspace settings > More features.

## Expected Result:
"Each" in More features introduction sentence will not be too close to the page border.

## Actual Result:
"Each" in More features introduction sentence is too close to the page border.

This issue is also reproducible on iPhone 14 with the second smallest font size (screenshot attached).

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
![Bug6592730_1725445557531!15_Pro_Max_font_size](https://github.com/user-attachments/assets/e31acd0a-a208-4af4-952d-aa77f5c036f3)
<img width="365" alt="Bug6592730_1725445557540!iPhone_15_Pro_Max_bug" src="https://github.com/user-attachments/assets/9412dd98-787e-4189-86b8-0b3fd640cd0a">
<img width="337" alt="Bug6592730_1725445557548!iPhone14__bug" src="https://github.com/user-attachments/assets/1b0dfd0a-d2b6-43cd-bd5a-6b067571a883">

https://github.com/user-attachments/assets/23ab1917-9df8-47d8-9253-d552861fbcb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @neil-marcellini</details>

**Comment by neil-marcellini** [comment] 2024-09-04 19:15
I agree this is not a blocker since it's a very small regression.

**Comment by RachCHopkins** [comment] 2024-09-16 03:01
@neil-marcellini automation is broken - does anyone here need to be paid, or can this be closed?

**Comment by RachCHopkins** [comment] 2024-10-08 04:28
Bump @neil-marcellini - is this closeable?

**Comment by neil-marcellini** [comment] 2024-10-10 18:38
Yeah the automation failed, but the PR fixing this is surely on production by now. No payment is needed because it was a follow up from the original PR that caused the regression https://github.com/Expensify/App/pull/48389. Closing!

**Closed by neil-marcellini** 2024-10-10 18:38 UTC
Labels: Reviewing, Engineering, Monthly, Bug
