### ISSUE TITLE
[HOLD for payment 2024-05-09] [$500] mWeb/Safari - Onfido - Button to take photo is hidden

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#37622] opened 2024-03-01 18:04 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.46-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4356746
**Email or phone of affected tester (no customers):**  applausetester+vd_mweb030124.2@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be logged in and have created a workspace
1. Go to Workspace > Bank account
2. Select Connect online, using Regions bank with the testing credentials
3. On Personal information, enter "First" and "Last" as first name and last name respectively
4. Enter any data on the other fields
5. On the double check page, confirm. It will take you to the Onfido page
6. Accept the terms and continue
7. Select Passport option
8. Verify the is no button to take the photo
9. Decrease the font size
10. Verify that as you decrease the font size, the button to take the photo is visible

## Expected Result:
The button to take the photo should be fully visible with the font size at 100%

## Actual Result:
The button to take the photo is hidden

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/8a9f43ae-a05b-4deb-a78c-8c227209c67d

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~017800134852beb09f</li>
        <li>Upwork Job ID: 1765006772911484928</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Contributor | 0</li>
<li>akinwale | Reviewer | 0</li>
<li>suneox | Contributor | 0</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @sonialiap</details>

**Comment by lanitochka17** [comment] 2024-03-01 18:05
@sonialiap  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by sonialiap** [comment] 2024-03-05 13:29
Asking about adding to [wave 7](https://expensify.slack.com/archives/C02NZ2HGJAZ/p1709645311585599) but looks to me like something we should update

**Comment by jsdev2547** [comment] 2024-03-05 17:18
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Onfido verify identity step - the camera button is hidden in mobile web.

### What is the root cause of that problem?
The header height under the back button icon is taking up 60px and pushing rest of the content under the screen.

![onfido-header](https://github.com/Expensify/App/assets/161593779/8cfbaf78-6b98-441d-a749-b5903a10ad4e)

### What changes do you think we should make in order to solve the problem?

The header height can be adjusted.

https://github.com/Expensify/App/blob/main/src/components/Onfido/index.css
Under .onfido-sdk-ui-Modal-inner add,
```
.onfido-sdk-ui-DocumentAuto-Overlay-wrapper {
grid-template-rows: 16px 0px 16px 1fr 32px minmax(100px, 100%) 18px !important;
}  
```

After adjusting the height,

![poc](https://github.com/Expensify/App/assets/161593779/b3bc3993-d703-483c-bb99-9a406695d23d)


### What alternative solutions did you explore? (Optional)

**Comment by s77rt** [comment] 2024-03-05 17:33
I'm not able to reproduce this on iOS simulator. I think this needs a real device. Will ask in Slack if any C+ can work on this

**Comment by s77rt** [comment] 2024-03-05 17:36
@situchan Will take this as C+

**Comment by situchan** [comment] 2024-03-05 17:51
reproduced

![IMG_0572](https://github.com/Expensify/App/assets/108292595/40491133-7129-473b-9e83-5b7d6f2f95bb)

2 issues here:
- camera view is not fully stretched (blank space at the bottom)
- capture button is cut

**Comment by sonialiap** [comment] 2024-03-11 12:44
@situchan looks like you may have volunteered to take this one. What do you think of the above proposals?

**Comment by situchan** [comment] 2024-03-13 22:38
reviewing proposals

**Comment by situchan** [comment] 2024-03-15 19:11
I am still testing provided solutions. Will update asap

**Comment by situchan** [comment] 2024-03-18 19:33
onfido-sdk-ui 14 migration was deployed to production.
@suneox anything blocking at the moment? Are they still planning to fix minor layout issues?

**Comment by situchan** [comment] 2024-03-22 08:59
@suneox bump ^

**Comment by situchan** [comment] 2024-03-25 02:03
I retested but onfido button is no longer hidden or cut.
updating 92% to 100% or @suneox's new solution makes UI look better but I think current version is also fine.

main:
<img width="415" alt="Screenshot 2024-03-25 at 8 01 30 AM" src="https://github.com/Expensify/App/assets/108292595/2859c7ef-8968-4cc3-ad7f-ecd24a3df774">

100%:
<img width="415" alt="Screenshot 2024-03-25 at 8 01 35 AM" src="https://github.com/Expensify/App/assets/108292595/7f510950-0f10-486d-8243-3c6cc213358d">

@suneox's solution:
<img width="415" alt="Screenshot 2024-03-25 at 8 01 38 AM" src="https://github.com/Expensify/App/assets/108292595/f263d607-444b-464a-b4e9-5aea6faa55df">

**Comment by situchan** [comment] 2024-03-25 02:03
@suneox please share 2 videos (before fix and after fix). And if reproduced, what is your iPhone model?

**Comment by mallenexpensify** [comment] 2024-04-01 16:33
@situchan is out OOO, reassigning a C+ via the auto-assigner for fairness.

**Comment by akinwale** [comment] 2024-04-03 07:43
Taking over as C+ here since I was auto-assigned. @suneox Based on https://github.com/Expensify/App/issues/37622#issuecomment-2017323622, were you able to resolve the error you were having with the bank account setup?

**Comment by sonialiap** [comment] 2024-04-09 13:38
@akinwale what do you think of @suneox 's update?

**Comment by akinwale** [comment] 2024-04-12 21:53
We can go with @suneox's [proposal](https://github.com/Expensify/App/issues/37622#issuecomment-1979059438) here.

🎀👀🎀 C+ reviewed.

**Comment by tgolen** [comment] 2024-04-17 19:03
# Daily Update
- This is just waiting on a PR. @suneox will that be coming soon?

### Next Steps
- @suneox Write a PR. Will that be coming soon?
- @tgolen and @akinwale review and merge the PR

#### ETA
- Merged by Friday, April 19

**Comment by sonialiap** [comment] 2024-05-09 22:02
Payment summary
- @akinwale reviewer $500 - paid ✔️ 
- @suneox contributor $500 - paid ✔️

**Comment by sonialiap** [comment] 2024-05-09 22:02
@akinwale please complete the [checklist](https://github.com/Expensify/App/issues/37622#issuecomment-2090436392)

**Comment by akinwale** [comment] 2024-05-10 06:47
> * [x]  [@akinwale] The PR that introduced the bug has been identified. Link to the PR:
> * [x]  [@akinwale] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
> * [x]  [@akinwale] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

This was a regression which occurred after updating the onfido-sdk to 14.15.0.

> * [x]  [@akinwale] Determine if we should create a regression test for this bug.
> * [x]  [@akinwale] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Regression Test Steps**
1. Launch Expensify.
2. Navigate to Workspaces > (Select a workspace or create a new workspace) > Bank account.
3. Enable the `Use Staging Server` option on the `Troubleshoot` screen.
4. Use the Connect manually option with the [demo credentials](https://expensify.slack.com/archives/C01GTK53T8Q/p1711049879962529)
5. On Personal information, enter any first name and last name, and fill in other data.
6. Click Confirm on the double-check pag to continue to the Onfido step.
7. On desktop web, verify that Onfido id displayed in the full remaining height.
8. Accept the terms and continue.
9. Select Passport option.
10. On mobile web, verify that the button to take a photo is visible.

Do we agree 👍 or 👎?

**Comment by akinwale** [comment] 2024-05-10 06:47
@sonialiap Done!

**Closed** 2024-05-10 19:04 UTC
Labels: External, Daily, Awaiting Payment, Bug
