### ISSUE TITLE
[REPORTING BONUS PAYMENT] [Hold Auth #8141] Web - Search - Two concierge chats and user's own account appears in search

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#20965] opened 2023-06-17 12:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to a new account
2. Click on search

## Expected Result:
Only one concierge chat should appear

## Actual Result:
Two concierge chats and user's own account appears in search

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29.0

**Reproducible in staging?:** yes

**Reproducible in production?:** no

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![image (67)](https://github.com/Expensify/App/assets/93399543/02c8f3ff-3f3c-4888-8a7d-eaa95a57460f)

![Screenshot 2023-06-17 at 1 16 21 PM](https://github.com/Expensify/App/assets/93399543/311c3cf9-33b0-4de7-b27a-d4174add8114)

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Puneet-here

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686987884987839

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01518684b253e81d9a</li>
        <li>Upwork Job ID: 1673118417921212416</li>
        <li>Last Price Increase: 2023-06-25</li>
    </ul>
</details>

**Comment by arosiclair** [comment] 2023-06-19 13:16
Not able to reproduce this in **v1.3.29-1**

<img width="1912" alt="Screenshot 2023-06-19 at 9 14 52 AM" src="https://github.com/Expensify/App/assets/6833644/84e2f607-e2b7-4092-9fcb-e7a27119f2f4">

@kbecciv can you try reproducing again?

**Comment by arosiclair** [comment] 2023-06-19 13:18
Nevermind I'm able to reproduce with a new @gmail.com account

**Comment by arosiclair** [comment] 2023-06-19 15:26
Alright the root cause of this seems to be an API issue. We build the options list using reports and personal details. We filter duplicates [here](https://github.com/Expensify/App/blob/b997868d39d758edbbbc9eb799bf18fab471e2f4/src/libs/OptionsListUtils.js#L722-L725) by login. However, the personal details for Concierge has no login for some reason so both the Concierge chat and personal detail are returned. I can confirm we're not returning the login for Concierge in `OpenApp`: 

<img width="610" alt="Screenshot 2023-06-19 at 11 10 48 AM" src="https://github.com/Expensify/App/assets/6833644/7c223579-d313-4df9-b40d-d08850a17c1a">

Other personal details are unaffected and have logins populated.

**Comment by luacmartins** [comment] 2023-06-19 20:59
This [Auth PR](https://github.com/Expensify/Auth/pull/8141) seems to fix the issue. Gonna remove the label and put this issue on hold for the Auth deploy. We should confirm it's fixed on staging once we deploy Auth.

**Comment by arosiclair** [comment] 2023-06-22 20:40
Auth PR is merged and this looks fixed on staging

![Screenshot 2023-06-22 at 4 39 25 PM](https://github.com/Expensify/App/assets/6833644/90dc5c44-ef7e-488b-93cd-25b38d4c2074)

**Comment by Puneet-here** [comment] 2023-06-23 08:14
@arosiclair, I think it should be eligible for the reporting compensation.

**Comment by arosiclair** [comment] 2023-06-23 13:28
@jliexpensify can you handle paying @Puneet-here for his report?

**Comment by jliexpensify** [comment] 2023-06-25 23:59
@fedirjh sorry, no need for C+, just sporting out payment. @Puneet-here - have invited you for the $250 payment.

**Comment by Puneet-here** [comment] 2023-06-26 18:50
@jliexpensify applied thank you.

**Comment by jliexpensify** [comment] 2023-06-26 23:51
No worries, once accepted I shall pay - cheers!

**Comment by jliexpensify** [comment] 2023-06-28 00:22
@Puneet-here - bumping for you to accept so I can pay you :)

**Comment by Puneet-here** [comment] 2023-06-29 20:33
@jliexpensify, I have accepted the offer

**Comment by jliexpensify** [comment] 2023-07-01 07:17
Paid and job closed!

**Closed by jliexpensify** 2023-07-01 07:17 UTC
Labels: External, Engineering, Daily, Overdue, Bug
