### ISSUE TITLE
[HOLD on #30438] [$500] Logging in with the workspace currency page shows "hmm its not found"

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#29646] opened 2023-10-16 00:17 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.84-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @abzokhattab
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1697311201107929

## Action Performed:
1. Go to settings > Workspaces
2. Select a workspace from the list or create a new one
4. Go Settings
5. Click on default currency and copy the current url.
6. Sign in again with the copied URL
## Expected Result: 
Not found page shouldn't display briefly.
## Actual Result: 
Not found page display briefly until the app loads

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/App/assets/38435837/b050e10a-442d-408b-a849-da925847b920

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/App/assets/38435837/b47661d3-314b-4bad-b3e1-e9f2142fe989

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/App/assets/38435837/7283ca29-1658-48fe-8d77-9bfb65eaf004

https://github.com/Expensify/App/assets/38435837/44aeda66-bb88-481c-84e6-565c4424511b

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a9f19acaa134409a</li>
        <li>Upwork Job ID: 1713710726656147456</li>
        <li>Last Price Increase: 2023-10-23</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by m-natarajan** [comment] 2023-10-16 00:18
## Proposal by @abzokhattab
### Please re-state the problem that we are trying to solve in this issue.
Not found page display briefly when we access the WorkspaceSettingsCurrencyPage via deep link
### What is the root cause of that problem?
The not found page is shown whenever the policy is empty
https://github.com/Expensify/App/blob/c559c5cfa2d95149bceb8c47fe5b135f3ac00589/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L82
In our case When we access it via deep link, the report needs to load from `openApp` API. So the not found page displays briefly before the `openApp` API is complete
### What changes do you think we should make in order to solve the problem?
we should use the `withPolicyAndFullscreenLoading` instead of the `withPolicy` hoc, as it will show the loader indicator till the data is ready
```js
withPolicyAndFullscreenLoading,
```
### POC
https://github.com/Expensify/App/assets/59809993/993221e5-c1f0-4e5d-b6b4-d6a14f89fd58

**Comment by yh-0218** [comment] 2023-10-16 13:05
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Logging in with the workspace currency page shows "hmm its not found"
### What is the root cause of that problem?
https://github.com/Expensify/App/blob/279ce1b6b0fbbfddea7735d90a120e934772da40/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L82
We didn't check `isLoadingReportData` value.
So during loading data(`isLoadingReportData = true`), we will see `Not Found`
### What changes do you think we should make in order to solve the problem?
1. Need to get `isLoadingReportData` value from `withOnyx`
```
isLoadingReportData: {
            key: ONYXKEYS.IS_LOADING_REPORT_DATA,
},
```
Add to here `isLoadingReportData` with `currencyList` 
https://github.com/Expensify/App/blob/279ce1b6b0fbbfddea7735d90a120e934772da40/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L112
2. set  `propTypes` and `defaultProps` for `isLoadingReportData`
```
const defaultProps = {
    personalDetails: {},
    betas: [],
+   isLoadingReportData: true,
    ...policyDefaultProps,
};
```
```
const propTypes = {
...
 +  isLoadingReportData: PropTypes.bool,
    ...policyPropTypes,
};
```
3. add `isLoadingReportData` as props value
```
function WorkspaceSettingsCurrencyPage({currencyList, policy, isLoadingReportData}) {
```
4. add `isLoadingReportData` to show `FullPageNotFoundView`
```
shouldShow={((_.isEmpty(policy) || !PolicyUtils.isPolicyAdmin(policy)) && !isLoadingReportData) || PolicyUtils.isPendingDeletePolicy(policy)}
```
https://github.com/Expensify/App/blob/279ce1b6b0fbbfddea7735d90a120e934772da40/src/pages/workspace/WorkspaceSettingsCurrencyPage.js#L82
### What alternative solutions did you explore? (Optional)

**Comment by twisterdotcom** [comment] 2023-10-19 12:39
@situchan any thoughts on these?

**Comment by situchan** [comment] 2023-10-24 11:58
"Not found" issue was fixed in https://github.com/Expensify/App/pull/29842 but this page still has issue.
So it's not automatically scrolled and highlighted on selected currency.
@twisterdotcom can this be fixed here? I think no one will create separate bug report for this.


https://github.com/Expensify/App/assets/108292595/c8a4a31d-ee23-40fd-a957-32ede67231e1

**Comment by abzokhattab** [comment] 2023-10-24 12:46
Hey @situchan 


the [accepted proposal](https://github.com/Expensify/App/issues/28402#issuecomment-1739616296) was updated to cover the currency page after this issue was open 

<img width="285" alt="image" src="https://github.com/Expensify/App/assets/59809993/12f981d5-76de-42e7-b98e-680fe17b6786">


<img width="590" alt="image" src="https://github.com/Expensify/App/assets/59809993/0cb88b16-4604-4bfb-8774-8187920a02c7">

is that allowed? 



The referenced issue was related to the invite page, not the currency page

> Please re-state the problem that we are trying to solve in this issue.
Accessing invite members link of a deleted workspace shows the invite page briefly before showing not found page

**Comment by situchan** [comment] 2023-10-24 12:49
@abzokhattab any reason for not allowing that?

**Comment by abzokhattab** [comment] 2023-10-24 13:02
I mean the mentioned problem/root cause is related to the invitation page `Accessing invite members link of a deleted workspace shows the invite page briefly before showing not found page` its not related to the currency page, they are two diff issues, and the proposal was updated after the current issue was added.

**Comment by twisterdotcom** [comment] 2023-10-26 16:33
@situchan yes, I still think we can bend it and fix it here. @abzokhattab I don't think there was anything malicious in updating the solution to later include other pages this would resolve for. It's extra detail.

**Comment by mvtglobally** [comment] 2023-10-27 00:48
Issue not reproducible during KI retests. (First week)

**Comment by abzokhattab** [comment] 2023-10-27 01:04
@twisterdotcom  Okay, i just wanted to defend my point of view, but no problem :D lets move forward.

**Comment by situchan** [comment] 2023-10-30 13:06
@mkhutornyi's [proposal](https://github.com/Expensify/App/issues/29646#issuecomment-1784717426) looks good to me.
I think it's better to show skeleton before fetching report and it's consistent with Report screen.
🎀 👀 🎀 C+ reviewed

**Comment by twisterdotcom** [comment] 2023-10-30 17:18
🖕 Melvin

**Comment by mvtglobally** [comment] 2023-11-02 03:32
Issue not reproducible during KI retests. (Second week)

**Comment by situchan** [comment] 2023-11-07 14:19
Still holding for https://github.com/Expensify/App/issues/29080

**Comment by flodnv** [comment] 2023-11-07 16:52
>Issue not reproducible during KI retests. (Second week)

I missed this... we can't repro this anymore?

**Comment by situchan** [comment] 2023-11-07 17:01
@flodnv Here's [context](https://github.com/Expensify/App/issues/29646#issuecomment-1777067820)
And confirmation: https://github.com/Expensify/App/issues/29646#issuecomment-1781464014

**Comment by twisterdotcom** [comment] 2023-11-07 21:37
Let's downgrade this given it's held.

**Comment by flodnv** [comment] 2023-11-22 20:02
Please reopen if it's still reproducible.

**Closed by flodnv** 2023-11-22 20:02 UTC
Labels: External, Weekly, Bug
