### ISSUE TITLE
[$500] mWeb - Compose Box - The magnifying glass moves up when words are highlighted

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30594] opened 2023-10-30 16:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.93-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/29434
## Action Performed:
1. Open https://staging.new.expensify.com/
2. Log in with an expensifail account
3. Open any chat and paste an RTL text in the compose box, for example " مثال "
4. Write any word in English, for example, "Hello."
5. Highlight the word "Hello" and move the selection cursor all the way to the left to fully highlight the word "مثال" at the same time

## Expected Result:
When English and Arabic words are highlighted at the same time, the magnifying glass should magnify the highlighted text and not move across the screen beyond the text

## Actual Result:
When English and Arabic words are highlighted at the same time, the magnifying glass moves upward

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
<details>
<summary>Android: Native</summary>

</details>

<details>
<summary>Android: mWeb Chrome</summary>

 

https://github.com/Expensify/App/assets/78819774/4fba87af-90c2-4f8b-b24b-82b1d4ddef99

</details>

<details>
<summary>iOS: Native</summary>

</details>

<details>
<summary>iOS: mWeb Safari</summary>

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

</details>

<details>
<summary>MacOS: Desktop</summary>

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015947874fc7315d53</li>
        <li>Upwork Job ID: 1721635785637269504</li>
        <li>Last Price Increase: 2023-11-20</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment] 2023-10-30 21:41
This is a weird one. I don't think we should block the deploy for it since most users don't type in RTL characters.

**Comment by srikarparsi** [comment] 2023-10-31 07:08
Hey @stephanieelliott! Going to un-assign myself for now and let this go the regular bug route since I believe it can be solved externally if it is reproducible and worth fixing.

**Comment by stephanieelliott** [comment] 2023-11-06 21:08
Adjusting labels to be fixed externally

**Comment by stephanieelliott** [comment] 2023-11-08 07:05
Reapplying the `Bug` label to get another BZ member on this while I am OOO til Nov 13. Thanks @NicMendonca,  I'll grab this back from you when I return!

**Comment by barttom** [comment] 2023-11-08 08:03
Hey! I'm Bartek from Callstack and I would work on this issue.

**Comment by barttom** [comment] 2023-11-08 08:14
I can't reproduce that. For me composer behaves other way:
* When I paste RTL text - the content is aligned to the right
* When I start typing after RTL text - the content is still aligned to the right which looks a proper way
* When I start typing previous RTL text - content is aligned to the left, looks a proper way

Is it connected to a particular device or Android version?
I've tested it on LG Velvet (LM-G900EM), android 13

cc: @NicMendonca @lanitochka17 


https://github.com/Expensify/App/assets/7682108/61eca274-b1a7-486b-98dd-660f3e1f9bf0

**Comment by barttom** [comment] 2023-11-09 12:55
Here is a mWeb recording
https://github.com/Expensify/App/assets/7682108/05466b91-d920-4e5e-bbc0-673b6796101e

**Comment by lanitochka17** [comment] 2023-11-10 15:10
I am not able to reproduce this issue on Samsung Galaxy A50/Android11


https://github.com/Expensify/App/assets/78819774/7e9a67bb-25f0-4557-a19f-9c931a415f9b

**Comment by barttom** [comment] 2023-11-13 07:07
@aimane-chnaif which device did You use to test it?

**Comment by stephanieelliott** [comment] 2023-11-13 15:34
Grabbing this issue back, thanks @NicMendonca!

**Comment by barttom** [comment] 2023-11-14 07:22
Thanks @aimane-chnaif!
I suspected that maybe this issue happened only to Samsung devices. However, I've checked that on Samsung s10 lite and still can't reproduce it. I tried pasting RTL text with and without space at beginning - always the same, proper result.
Any thoughts on how to reproduce that, every time? Maybe I've missed some details.

**Comment by barttom** [comment] 2023-11-14 08:03
still can't reproduce it. I wondering what is the detail that makes this issue happen.

https://github.com/Expensify/App/assets/7682108/e9640040-6ac7-4b39-a547-0bfc45a5cd21

**Comment by stephanieelliott** [comment] 2023-11-21 05:56
I can't reproduce this either, it seems like it is happening only in very specific scenarios. Given how edge case it is (must type arabic _and_ english characters, then highlight them), I think we should close this. If you disagree, feel free to reopen and start a discussion.

**Closed by stephanieelliott** 2023-11-21 05:56 UTC
Labels: External, Engineering, Daily, Help Wanted, Overdue, Bug
