### ISSUE TITLE
[HOLD for payment 2024-07-24] [$250]  Categorizing - Workspace member has option to edit categories, which leads to not here page

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#43623] opened 2024-06-12 23:43 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.82-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
Precondition:
- User is an invited member of a workspace.
- The workspace has disabled all the categories.

1. Go to staging.new.expensify.com
2. Go to FAB > Track expense.
3. Track a manual expense.
4. Click Categorize it from the actionable whisper.
5. Select the workspace that has disabled all the categories.
6. Click Edit categories.

## Expected Result:
In Step 6, there should be no option for workspace member to "edit categories". Also, because the member is not an admin, the empty categories page should say this for the title "{workspaceName} doesn't have any categories enabled", and this for the subtext "Categorize this expense by choosing a different workspace, or [ask your admin](link to member's policy expense chat) to enabled categories for this workspace". Lets swap out the Categories button with a "Got it" button which navigates back to the workspace selector.

Here is an example mockup, but we can probably use the existing illustration and only update the text on the page when the member is not an admin.

<img src=https://github.com/Expensify/App/assets/26260477/0ca79f7e-7ca1-4370-b7ca-e0c94e2743a6  width=300px>

Here is the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1718659318491659) where this was discussed.

## Actual Result:
In Step 6, there is an option for workspace member to "edit categories", which leads to not here page.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/43996225/abeb0194-ab33-48a9-b4b5-e4666ba4ad64

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01693c1a6724bab4ab</li>
        <li>Upwork Job ID: 1801197084944850945</li>
        <li>Last Price Increase: 2024-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>allgandalf | Reviewer | 102782628</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @adelekennedy</details>

**Comment by kavimuru** [comment] 2024-06-12 23:44
@laurenreidexpensify FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by kavimuru** [comment] 2024-06-12 23:44
We think this bug might be related to #vip-vsb

**Comment by nkdengineer** [comment] 2024-06-17 03:47
@allgandalf Other parts of our codebase also use this condition to check `isAdmin` like [here](https://github.com/Expensify/App/blob/df9689fc916301ccdda6334a53adf4726102bb56/src/components/ReportActionItem/MoneyRequestView.tsx#L152) and  [here](https://github.com/Expensify/App/blob/df9689fc916301ccdda6334a53adf4726102bb56/src/components/MoneyRequestHeader.tsx#L77)

```
const isAdmin = policy?.role === 'admin';
```

So my solution should be chosen because it is the first proposal with the correct RCA and solution. The use of the isPolicyAdmin function in the places mentioned above can be done in the PR phase.

**Comment by neil-marcellini** [comment] 2024-06-17 21:12
> Thanks for the proposal everyone!
> 
> @codinggeek2023 's [proposal](https://github.com/Expensify/App/issues/43623#issuecomment-2165421586) looks good to me.
> 
> Their RCA is correct and their solution is async with our codebase, we already use `isPolicyAdmin` util in reports [page](https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/ReportDetailsPage.tsx#L70) and workspace initial [page](https://github.com/Expensify/App/blob/bdb978990df4a8e173b9790a2fa75c2a0f1d6be3/src/pages/workspace/WorkspaceInitialPage.tsx#L147)
> 
> 🎀👀🎀 C+ reviewed


I like that proposal too, but I think we should go one step further and edit that empty categories page to have different text when a non-admin is viewing it. They don't have the ability to add categories so instead it should explain that the workspace doesn't have any enabled categories, and they should ask an admin to enable some categories or pick a different workspace.

Alternatively we could exclude workspaces without categories from the list, but then users might be confused about why it's missing, so I think it's better to show it. I will start a Slack discussion to make sure we're aligned on the expected behavior.

**Comment by neil-marcellini** [comment] 2024-06-18 16:45
Here is the [Slack thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1718659318491659) where we discussed and landed on a solution. I'm going to re-assign to Danny to give him credit, and since he also proposed some good copy I don't think we need a review from Cheryl, although she's certainly welcome to chime in. I'm going to update the issue description now.

**Comment by neil-marcellini** [comment] 2024-06-18 16:55
I'm actually going to go with the [proposal](https://github.com/Expensify/App/issues/43623#issuecomment-2165303496) from @daledah because it was posted first, makes sense, and he suggested a good alternate solution of editing the copy on the empty categories page. Please take a look at the updated expected results and raise a PR implementing those changes.

**Comment by laurenreidexpensify** [comment] 2024-06-20 14:35
hey @adelekennedy handing this one over for my parental leave K2 clear out. we're in the PR stage, so you'll mainly just be handling payments for this one. thanks!

**Comment by adelekennedy** [comment] 2024-07-25 03:51
Payouts due:

- [ ] Contributor: $250 @daledah (Upwork)
- [ ] Contributor+: $250 @allgandalf (Upwork)

**Comment by adelekennedy** [comment] 2024-07-25 03:54
@daledah will you share your upwork profile with me so I can extend an offer?

**Comment by adelekennedy** [comment] 2024-07-28 19:03
let me know @daledah I'll keep this issue open for now

**Comment by adelekennedy** [comment] 2024-07-31 17:43
thank you @daledah! Offer sent

**Comment by adelekennedy** [comment] 2024-07-31 17:43
https://www.upwork.com/nx/wm/client/contracts?contractStatus=pending&contactPerson=1004801002

**Comment by adelekennedy** [comment] 2024-08-01 22:26
@daledah bump to accept the offer!

**Comment by adelekennedy** [comment] 2024-08-02 19:37
payment made! Closing this

**Closed by adelekennedy** 2024-08-02 19:37 UTC
Labels: External, Daily, Design, Awaiting Payment, Bug
