### ISSUE TITLE
[$250] Track Expense - Hmm not here page & user not redirected to new WS chat on submitting expense

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#43096] opened 2024-06-05 10:55 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-79-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4594446&group_by=cases:section_id&group_order=asc&group_id=309130
**Email or phone of affected tester (no customers):** applausetester+ck0604@applause.expensifail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1. Log in to ND site with new account with no existing workspace
2. Submit a track expense in the self DM
3. Click on Share it with your accountant On the actionable whisper options of a track expense
4. Enter a merchant and create the expense (Note: Hmm.. not here page opens)
5. Click the back button (Note: Unexpected error & user not redirected to new WS chat)
6. Go to LHN & observe WS chat created with RBR
7. Select the new WS chat & observe the unexpected error displayed

## Expected Result:
Creating the expense with a merchant should move the transaction to the new workspace, with the correct details and category selected.

## Actual Result:
1. On step 4 - Hmm.. not here page displayed & user not redirected to new WS chat on submitting expense
2. On step 7 - Selecting new WS chat from LHN, display unexpected error in expense details

Note: Issue reproducible with gmail account as well

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/462fb01d-7205-46e3-9222-fc510e8e5eb7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bc423d2f81ec9e86</li>
        <li>Upwork Job ID: 1798364363939661338</li>
        <li>Last Price Increase: 2024-06-05</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @getusha</details>

**Comment by izarutskaya** [comment] 2024-06-05 10:56
@slafortune I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment] 2024-06-05 10:56
We think this issue might be related to the #vip-vsb.

**Comment by izarutskaya** [comment] 2024-06-05 10:57
Production 


https://github.com/Expensify/App/assets/115492554/be679098-eb6e-4859-be2b-d15b15036f68

**Comment by Gonals** [comment] 2024-06-05 14:44
> should move the transaction to the new workspace

@izarutskaya, what workspace would this be? There are none for this user, right?

**Comment by Gonals** [comment] 2024-06-05 14:49
@izarutskaya, I have not been able to reproduce this issue. This seems to work fine for me

**Comment by neil-marcellini** [comment] 2024-06-05 17:40
I also can't reproduce the issue. Closing.

**Closed by neil-marcellini** 2024-06-05 17:40 UTC
Labels: DeployBlockerCash, External, Engineering, Hourly, Help Wanted, Bug, DeployBlocker
