### ISSUE TITLE
[$2000] Some users and workspace rooms are  disappearing for a seconds while scrolling

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#20984] opened 2023-06-18 14:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1 Open the app
2 Scroll down and up

## Expected Result: 
should be always visible
## Actual Result: 
disappearing for a seconds while scrolling

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/06ad9dd9-f345-42d3-859c-2b2c26d50ebf

<img src="https://github.com/Expensify/App/assets/43996225/fb979316-bd4c-4a0a-b720-56d23f385753" width="40%" height="40%">

https://github.com/Expensify/App/assets/43996225/e2258973-8298-4a4c-b503-82a0a384d29c

**Expensify/Expensify Issue URL:**
**Issue reported by:** @narzullome
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686325097457949

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0166d6210806b78eaf</li>
        <li>Upwork Job ID: 1671197755942498304</li>
        <li>Last Price Increase: 2023-07-17</li>
    </ul>
</details>

**Comment by zanyrenney** [comment] 2023-06-20 16:52
huh, why did this go overdue! not overdue, just got triaged.

**Comment by LucioChavezFuentes** [comment] 2023-06-21 16:05
Ups.. made a mistake.  I am reformulating the proposal.

**Comment by LucioChavezFuentes** [comment] 2023-06-21 19:22
The proposal is Corrected and ready to be reviewed!

**Comment by zanyrenney** [comment] 2023-07-03 10:11
Oh so annoying! I reassigned another Bug0 team member but then when I assigned myself again, it removed them.

**Comment by zanyrenney** [comment] 2023-07-03 10:11
@aimane-chnaif please can you review the proposal above?

**Comment by zanyrenney** [comment] 2023-07-05 11:12
Bump @aimane-chnaif please can you review the proposal above?

**Comment by zanyrenney** [comment] 2023-07-10 10:49
Hey @LucioChavezFuentes bump on the above! Thanks!

**Comment by LucioChavezFuentes** [comment] 2023-07-10 13:12
@aimane-chnaif I have been analyzing deeper the problem and I conclude you are right. The problem is far more complex to be fixed by changing the Flatlist values. For now, I have no more ideas to add.

**Comment by zanyrenney** [comment] 2023-07-17 11:16
Increased the price and bumped the thread!

**Comment by kmwamasali** [comment] 2023-07-17 12:14
@aimane-chnaif @zanyrenney combining an increased `maxToRenderPerBatch` with `updateCellsBatchingPeriod` allows to optimize the performance. https://reactnative.dev/docs/optimizing-flatlist-configuration#updatecellsbatchingperiod
I can run measurement tests on this if it's an acceptable proposal

**Comment by zanyrenney** [comment] 2023-07-17 13:50
thanks @kmwamasali - @aimane-chnaif please let us know if that's a proposal you think will work.

**Comment by kmwamasali** [comment] 2023-07-17 15:47
@aimane-chnaif yes please, working on it

**Comment by zanyrenney** [comment] 2023-07-20 09:27
any update here @kmwamasali ? thanks!

**Comment by kmwamasali** [comment] 2023-07-20 09:33
@zanyrenney I run into a few hiccups setting up the profiler and testing devices but finally made headway and will have the update today

**Comment by kmwamasali** [comment] 2023-07-20 15:42
@zanyrenney @aimane-chnaif 
I'm uploading the raw profiling files here, will follow up with source maps that target only the scroll action, other actions taken for a more comprehensive comparison are listed below.
- Load app
- Click on chat
- Navigate back to homepage
- Scroll through list.

I used the following values in the updated file
`maxToRenderPerBatch`: **15**
`windowSize`: **10**
`updateCellsBatchingPeriod`: **50**

I attached both sampling profiler downloaded from a samsung a12
and using the hermes profiler on chrome tools

[Trace-20230720T18.zip](https://github.com/Expensify/App/files/12111512/Trace-20230720T18.zip)

[sampling-profiler-trace.zip](https://github.com/Expensify/App/files/12111515/sampling-profiler-trace.zip)

**Comment by zanyrenney** [comment] 2023-07-24 11:52
@aimane-chnaif please can you review the comments above and let us know what you think please?

**Comment by kmwamasali** [comment] 2023-07-24 19:43
@aimane-chnaif would it be advisable to post the question in the open source channel, or is the check for one of the internal / c+ contributors

**Comment by zanyrenney** [comment] 2023-07-27 12:21
https://expensify.slack.com/archives/C01GTK53T8Q/p1690460451772389 asked here!

**Comment by mczernek** [comment] 2023-07-27 13:09
FWIK if we want to keep FlatList here we cannot do much more than @LucioChavezFuentes proposed. It is really a matter of sacrificing initial performance for scrolling performance. Problem will still be there but more difficult to spot. There are two solutions that might fix it more fundamentally, at least on mobile devices.

- substitute FlatList with [FlashList](https://shopify.github.io/flash-list/) which seems to be more performant in most cases but have the same limitation still
- write those lists natively for Android and iOS using `RecyclerView` 🤖 and `UITableView` 🍏 - they are fundamentally different in principals when it comes to virtualisation and has proven to be much better than FlatList. They will never allow for an empty item to be displayed (unless you force them to) but it could happen that list will stop for a while while rendering next items. It is very unlikely when written correctly, though, and is very widely and successfully used across many native apps. There are some obvious disadvantages to this solution though:

1. Quite a bit of native code that has to be maintained
2. Sharing data between native and JS - it might easily overload bridge so some smart solution needs to be figured out here. Perhaps with New Architecture that would be easier?

If you feel like its worth the effort I can try and prepare (or anyone else using those ideas) Proposal or even Draft PRs to test it out and decide which direction to follow. Given this list is central to whole app I feel like it might be worth taking some longer routes here.

**Comment by kmwamasali** [comment] 2023-07-27 13:31
@aimane-chnaif @zanyrenney were the results of my proposal tested. Was it a speed issue for why it was not considered. Kindly share feedback on your process. Thank you

**Closed** 2023-07-27 16:14 UTC
Labels: Engineering, Daily, Internal, Bug
