### ISSUE TITLE
[$500] Android - BA - Tapping on connect BA, the page shown twice

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34970] opened 2024-01-23 15:23 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.30
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4211085
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Launch app
2. Tap profile icon
3. Tap Workspaces --- Workspace
4. Tap cards
5. Tap connect Bank account

## Expected Result:
Tapping on connect BA, must show connect BA page

## Actual Result:
Tapping on connect BA, shows connect BA page, then one moment page, again showing connect BA page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/67e89a2d-5d2f-431e-859d-9e065862014b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a7811d11e434a510</li>
        <li>Upwork Job ID: 1749815100796596224</li>
        <li>Last Price Increase: 2024-01-23</li>
    </ul>
</details>

**Comment by samilabud** [comment] 2024-01-23 15:53
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Android - BA - Tapping on connect BA, the page shown twice

### What is the root cause of that problem?
We are using a prop and a ref variable to show the loading indicator: 
https://github.com/Expensify/App/blob/c3f7bccc1050988c6352ea63fa00bf327761587a/src/pages/workspace/WorkspacePageWithSections.tsx#L137
When we get the section displayed we see the section before showing loading indicator and later when the reference indicate is loading we see the loading indicator based in reimbursementAccount and finally we get the section displayed.

### What changes do you think we should make in order to solve the problem?
We should take into consideration the isLoading var based in reimbursementAccount when Onyx var is fully loaded.

**Comment by ikevin127** [comment] 2024-01-23 18:41
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Tapping on Connect BA on Cards page, shows Connect BA page briefly, then One moment loading page, then it finally shows Connect BA page.

### What is the root cause of that problem?

There are 2 issues here, I'll address the main first then the second:

1. The root of the main issue addressed above in the 're-state the problem' block is that when the `ReimbursementAccountPage.js` is transitioned to from the Cards page by tapping the Connect BA button the `if` that renders the `ReimbursementAccountLoadingIndicator` component goes `false`- `true` - `false` and here are the variables and how they change:

<details>
<summary>Variables changing flow</summary>

```

isLoadingApp, account.isLoading, reimbursementAccount.isLoading, !plaidCurrentEvent
false false false false

!hasACHDataBeenLoaded, isLoading, shouldShowOfflineLoader, shouldReopenOnfido, !requestorStepRef.current
false false true true true

ReimbursementAccountLoadingIndicator is being rendered: false // - we see Connect BA page briefly

___

isLoadingApp, account.isLoading, reimbursementAccount.isLoading, !plaidCurrentEvent
false false true false

!hasACHDataBeenLoaded, isLoading, shouldShowOfflineLoader, shouldReopenOnfido, !requestorStepRef.current
false true true true true

ReimbursementAccountLoadingIndicator is being rendered: true // - we see the One moment loading page

___

isLoadingApp, account.isLoading, reimbursementAccount.isLoading, !plaidCurrentEvent
false false false false

!hasACHDataBeenLoaded, isLoading, shouldShowOfflineLoader, shouldReopenOnfido, !requestorStepRef.current
false false true true true

ReimbursementAccountLoadingIndicator is being rendered: false // - we finally land on the Connect BA page
```

What happens here is that initially `!hasACHDataBeenLoaded` is true because the data wasn't loaded and `isLoading` is false because `reimbursementAccount.isLoading` is false since the `BankAccounts.openReimbursementAccountPage` wasn't called yet and calling `BankAccounts.setReimbursementAccountLoading(true)` in the `fetchData` function to set reimbursementAccount.isLoading to true is also an async operation (not instant).

What happens next is `BankAccounts.openReimbursementAccountPage` is being called which sets reimbursementAccount.isLoading to true therefore making `isLoading` true, this shows the One moment loading page.

Then once the call is completed reimbursementAccount.isLoading then becomes false, making `isLoading` false.

2. There's another issue where once the whole thing mentioned above happens and we're on the Connect BA page, if we go back to the Cards page, this will be stuck on loading state indefinitely (FullScreenLoadingIndicator).

What happens here is that in the `WorkspacePageWithSections.tsx` component the following line: `const isLoading = reimbursementAccount?.isLoading ?? true;` makes it such that when reimbursementAccount?.isLoading is undefined, it defaults to true.

The if block that renders the `FullScreenLoadingIndicator` checks the following: `` but because the way we defined isLoading, when returning back to Cards page from Connect BA page, `reimbursementAccount?.isLoading` will will be `undefined` therefore isLoading will default to `true` causing the infinite loading screen on the Cards page.

</details>

### What changes do you think we should make in order to solve the problem?

Here are my solutions for both issues:

1. Inside the `fetchData` function within the `ReimbursementAccountPage.js` component, above the line where we call `BankAccounts.setReimbursementAccountLoading(true)`, we set a new loading state variable to `true` so that we have instant loading state when we call the function instead of the async onyx one we set.

Then write up the following useEffect in order to set the new loading state to false:

```javascript
    useEffect(() => {
        if (prevIsLoadingRe && !reimbursementAccount.isLoading) {
            return;
        }
        setLdng(false);
    }, [prevIsLoadingRe, reimbursementAccount.isLoading]);
```

this makes sure that the Connect BA page will only be showed when all requests are completed, showind the One moment loading page correctly - not on and off briefly.

2. For the second issue all we have to do is to correct the way the `isLoading` variable is defined within the `WorkspacePageWithSections.tsx` component like so: `const isLoading = Boolean(reimbursementAccount?.isLoading);`

This ensures that when we return to the Cards page from Connect BA page and `reimbursementAccount?.isLoading` is undefined, isLoading will be false and we won't be stuck on an infinite FullScreenLoadingIndicator.

**Comment by DylanDylann** [comment] 2024-01-23 19:08
@mountiny I think it should be hold for VBBA refactor

**Comment by ikevin127** [comment] 2024-01-23 19:25
@DylanDylann I would push for fixing this one asap, unless the VBBA refactor is **extremely close** to being merged.

Saying this since this is not only bad UX of Connect BA page showing twice but also the Cards page being stuck in loading state when navigating back from the Connect BA page.

**Comment by DylanDylann** [comment] 2024-01-23 19:29
@ikevin127 Yeah. Let's see what the internal team thinks. Because I see a lot of issue are holding for VBBA refactor as well

**Comment by mountiny** [comment] 2024-01-23 19:41
Thanks, putting this on hold, the users are not blocked to take actions

**Comment by conorpendergrast** [comment] 2024-01-29 16:47
Looks like this is the best overall project issue (in a private repo): https://github.com/Expensify/Expensify/issues/289050

**Comment by mountiny** [comment] 2024-02-19 16:11
This is no ton hold anymore, new bank account flow is implemented, can you check if this bug stays around?

**Comment by JmillsExpensify** [comment] 2024-02-21 01:38
Posted in #qa to get this re-tested.

**Comment by JmillsExpensify** [comment] 2024-02-21 02:15
QA confirmed that this isn't happening anymore, so I'm closing the issue.

**Closed by JmillsExpensify** 2024-02-21 02:15 UTC
Labels: Daily, Internal, Bug
