### ISSUE TITLE
[$500] Search and Send message components don't lose focus on enter after No results found

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#27897] opened 2023-09-20 21:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open search
3. type non existent term eg: fdjfns
4. Press enter, observe that focus is still retained on search
5. Similarly try on Send message from plus->send message and observe that focus is still retained on search
6. Try any any other search throughout the app like emoji picker, invite member search and observe that app loses focus on searching non existent term and enter click
## Expected Result: 
App should lose focus from search on searching non existent term and enter click on all searches throughout the app
## Actual Result: 
App does not lose focus from search on searching non existent term and enter click on search page and send message page

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.72-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/05f01f32-e288-46d5-88b9-55bfbffffb31

https://github.com/Expensify/App/assets/43996225/af8907b9-51fd-4bd7-b308-8b8b803636f2

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695034385254419

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01b939486f0e1a1917</li>
        <li>Upwork Job ID: 1704606680282849280</li>
        <li>Last Price Increase: 2023-09-20</li>
    </ul>
</details>

**Comment by salonikumawat28** [comment] 2023-09-20 21:44
Shouldn't this be the default behaviour to not lose focus?
Isn't it a bad UX to go out of focus when user is actively searching something?

**Comment by s-alves10** [comment] 2023-09-20 22:24
I don't think this is worth fixing

**Comment by sakluger** [comment] 2023-09-21 09:06
I agree that this is not a bug. Closing.

**Closed by sakluger** 2023-09-21 09:06 UTC
Labels: External, Daily, Help Wanted, Bug
