### ISSUE TITLE
[Image][Performance] Better caching for iOS images

### ISSUE THREAD

**Issue by Szymon20000** [Expensify/App#10792] opened 2022-09-02 11:30 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## What performance issue do we need to solve?
Better caching for iOS images

## What is the impact of this on end-users?
Previously seen avatars/assets will show up faster with suggested change.

## Proposed solution (if any)
Use FastImage for Avatars and images that are par of the messages. 
`Avatar.js` uses Image from react-native
react-native-render-html - that as far as I know is used for rendering attachment (among the other things) uses Image from 'react-native' if the change with avatars will give us good results it's worth to test patching that library as well. So that it uses fast-image.

## Platform:
Where is this issue occurring?

- [ ] Web
- [x] iOS
- [ ] Android
- [ ] Desktop App
- [ ] Mobile Web

**Version Number:**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Upwork URL:** https://www.upwork.com/jobs/~013a8690a2c460efd2

[View all open jobs on Upwork](https://www.upwork.com/ab/jobs/search/?q=Expensify%20React%20Native&sort=recency&user_location_match=2)

**Reported by:** @parasharrajat originally on [this issue](https://github.com/Expensify/App/issues/6527). 
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019ac837ee43fe141c</li>
        <li>Upwork Job ID: 1620162574495588352</li>
        <li>Last Price Increase: 2023-01-30</li>
    </ul>
</details>

**Comment by roryabraham** [comment] 2022-09-05 08:14
Switching this to weekly

**Comment by roryabraham** [comment] 2022-09-21 19:18
@Szymon20000 I saw you put up a draft PR but you weren't sure about the change because right now FastImage isn't compatible with Fabric. Overall I think we should prioritize Fabric compatibility over using FastImage.

Looking into FastImage some more, it seems like one of the main things it handles is persistent image caching. However, that functionality feels potentially in-scope for our persistent storage library Onyx. Going to add this issue to the image tracking issue [here](https://github.com/Expensify/App/issues/10894)

**Comment by roryabraham** [comment] 2022-09-30 06:55
Any new thoughts here @Szymon20000?

**Comment by mallenexpensify** [comment] 2022-10-22 01:04
Been a minute.... let's see... 
@roryabraham , should Alex Beaman be assigned to cuz he's leading
 [Tracking] [Polish] Image-related feature request and improvements #10894

If so, I reckon I should be too since I'm the the BugZero (BZ) team person for that tracking issue. 

Also... @roryabraham and/or @Szymon20000 , is this actively being worked on? If so, any update?

**Comment by roryabraham** [comment] 2022-10-22 01:12
> should Alex Beaman be assigned to cuz he's leading

Yes, I think so.

> Also... @roryabraham and/or @Szymon20000 , is this actively being worked on? If so, any update?

Definitely not by me – I don't think there's been any active development on this.

**Comment by roryabraham** [comment] 2022-10-22 01:13
Thanks @mallenexpensify

**Comment by Beamanator** [comment] 2022-10-31 15:04
Still on hold, but will get to this soon

**Comment by trjExpensify** [comment] 2022-11-09 12:41
On hold, Melv.

**Comment by Beamanator** [comment] 2022-11-10 14:19
No longer on hold since we can now accept auth tokens in the `header` of image requests!

**Comment by trjExpensify** [comment] 2022-11-10 19:02
Okay cool, so what's the game plan? Did @Szymon20000 have a draft PR for this that we're proceeding with now?

**Comment by thomas-coldwell** [comment] 2022-11-10 19:11
Hey @trjExpensify - I've just been combining the areas where @Szymon20000 setup fast image and adding in the auth token headers based on PoC PR from @Beamanator. I will create a PR for this and link it here 🙌

**Comment by Beamanator** [comment] 2022-11-10 19:21
I was working on responding and trying to find your GH handle @thomas-coldwell 😅 Seems like the standard `@` search doesn't let me find you easily somehow :'(

**Comment by trjExpensify** [comment] 2022-11-10 19:22
Oh, amazing! Okay cool, let's co-assign this issue to you then @thomas-coldwell. :)

**Comment by aldo-expensify** [comment] 2022-11-11 00:37
I got assigned as a reviewer to the [PR](https://github.com/Expensify/App/pull/12648), a few of questions:

- Should I care about the checks not passing for verified signature in the commits?
    <img width="400" alt="image" src="https://user-images.githubusercontent.com/87341702/201234901-2814a60b-5fe4-4428-b029-ca29b92214c2.png">
- Should we get a C+ to review this?
- Does the requirements for the PR author to test in every platform and provide pictures apply here?

**Comment by roryabraham** [comment] 2022-11-11 00:39
> Should I care about the checks not passing for verified signature in the commits?

The PR will not be mergeable without signed commits. @thomas-coldwell will have to retroactively sign those commits.

> Should we get a C+ to review this?

I think so, yes

> Does the requirements for the PR author to test in every platform and provide pictures apply here?

Yes, absolutely. The PR affects cross-platform components.

**Comment by JmillsExpensify** [comment] 2022-11-11 02:14
@trjExpensify Took the WAQ project off hold, yo.

**Comment by trjExpensify** [comment] 2022-11-14 12:02
>Should we get a C+ to review this?
>
> I think so, yes

Added the `External` label, replaced `Help Wanted` with `Reviewing` and added the assigned C+ to the PR for the review.

**Comment by Beamanator** [comment] 2022-11-14 18:53
@thesahindia mentioned he's going ooo [here](https://github.com/Expensify/App/pull/12648#issuecomment-1314123502) so trying to get new C+

**Comment by trjExpensify** [comment] 2022-11-14 22:19
Upwork job here for you for the C+ review, @mananjadhav: https://www.upwork.com/jobs/~013a8690a2c460efd2

**Comment by Beamanator** [comment] 2022-11-22 11:57
PR is coming along nicely, had lots of great reviews from @mananjadhav - looks like we should have this merged in a day or two tops 👍

**Comment by Beamanator** [comment] 2022-11-30 08:12
PR was merged, but caused a regression (https://github.com/Expensify/App/issues/13002) so it was reverted (https://github.com/Expensify/App/pull/13010). @thomas-coldwell mentioned he'll work on the new PR soon 👍

**Comment by Beamanator** [comment] 2022-12-05 12:34
PR is in draft mode, looking into fixing a bug upstream

**Comment by trjExpensify** [comment] 2022-12-08 17:23
@thomas-coldwell @Beamanator there's a [new PR here](https://github.com/Expensify/App/pull/13304) to link to this issue, right? How's that going?

**Comment by michaelhaxhiu** [comment] 2022-12-08 22:32
When you create a group chat with several users (e.g. 4 - 5 or more) and tap View Details (e.g. top pane), it seems that _sometimes_ the avatar pictures associated with individuals in the group chat will appear a few moments late. Is the PR here going to address that issue?

Alberto is a good example, which is the avatar/user in the 2nd row in my recording below. (_note: ignore the last user appearing in the DM as that's going to be fixed by expanding `initialNumToRender` to a great number via https://github.com/Expensify/App/issues/13259_)

https://user-images.githubusercontent.com/13206896/206577054-10106584-c41a-4248-9862-f109cc0266bf.MP4

**Comment by Beamanator** [comment] 2022-12-12 18:37
@michaelhaxhiu that's an interesting issue, have you only seen that on iOS and / or Android? If so, this PR mayyyy address that automatically will keep that in mind for sure

**Comment by Beamanator** [comment] 2022-12-15 14:21
Sry, thought about changing the priority to Weekly, decided against it 😅 

Discussing options for moving forward here: https://expensify.slack.com/archives/C01GTK53T8Q/p1671112210394559?thread_ts=1670868002.066289&cid=C01GTK53T8Q

**Comment by michaelhaxhiu** [comment] 2022-12-15 14:46
@Beamanator yep, it's only on iOS and Android.

**Comment by trjExpensify** [comment] 2022-12-15 22:28
PR for the upstream fix: https://github.com/DylanVann/react-native-fast-image/pull/953

**Comment by trjExpensify** [comment] 2022-12-19 17:46
Latest thread to [discuss the next steps](https://expensify.slack.com/archives/C01GTK53T8Q/p1671463595920689) on this one. I think the plan of action is: 

- Put this issue on `[Hold - upstream fix Fast Image #953]` as we await feedback on that upstream PR 
- Dec 22nd: Reach out, 1 week later 
- Dec 29th: Reach out, 2 weeks later
- Jan 5th: Fork the repo and fix it ourselves as we wait any longer

How does that sound?

**Comment by mallenexpensify** [comment] 2022-12-23 01:58
Bumped to weekly cuz on hold

**Comment by Beamanator** [comment] 2023-01-02 12:49
Hmm ok well I've been OOO for the week 1 & 2 updates so haven't reached out yet. It looks like there still hasn't been movement on the upstream PR (https://github.com/DylanVann/react-native-fast-image/pull/953) so I say we can try to reach out to see if the maintainer has time to look at the PR this week - and then if there's still no movement by EOW we fork & work on our own version

**Comment by Beamanator** [comment] 2023-01-02 13:05
Ok reached out, I'll post back here if I get a response

**Comment by mananjadhav** [comment] 2023-01-26 00:30
@Beamanator @mallenexpensify This might be ready for payout by tomorrow, so before we do that I want to clarify how do we handle the payment for this one. I reviewed two PRs for this issue:

1.  #12648 - Was reverted as it had a regression
2.  #13304 - Merged and deployed to production on Jan 20, 2023.

Both the PRs were extremely complex and tedious to review. @Beamanator had also mentioned about the pay bump for the first PR review [here](https://github.com/Expensify/App/issues/10792#issuecomment-1323853893)

and overall both the PR codes are a lot different. Can we please increase payout for this one to accommodate the complexity and number of PRs.

**Comment by mallenexpensify** [comment] 2023-01-27 22:37
@mananjadhav after internal discussion we believe that $4k, in total, is a fair amount, based on the complexity and also because of the regression.  Do you agree @mananjadhav ?   
@thomas-coldwell is with Margelo and his compensation is paid outside of our standard process.

**Comment by mananjadhav** [comment] 2023-01-28 02:17
> Do you agree @mananjadhav ?

Thanks @mallenexpensify. Agreed it is fair :)

**Comment by mananjadhav** [comment] 2023-01-30 20:18
@mallenexpensify Quick bump on this one.

**Comment by mallenexpensify** [comment] 2023-01-30 20:53
@mananjadhav can you please accept the job and reply here once you have? 
https://www.upwork.com/jobs/~019ac837ee43fe141c

**Comment by mananjadhav** [comment] 2023-01-30 21:01
Accepted @mallenexpensify

**Comment by mallenexpensify** [comment] 2023-01-31 21:27
@mananjadhav paid $4000. 

I'm guessing this doesn't need regression test steps added.  @Beamanator can you confirm? And close if so? Thx

**Comment by mallenexpensify** [comment] 2023-01-31 23:14
Thanks @parasharrajat , I missed it as I paid Manan on a different Upwork job. 
All set!

**Comment by Beamanator** [comment] 2023-02-01 16:39
@mallenexpensify good question, I believe you're right, I think we can close this out - also @trjExpensify it looks like you added the upstream PR link to the issue title, but I made this issue to track that PR here: https://github.com/Expensify/App/issues/14382

I think this is better so we can close out this very large issue, thoughts?

**Comment by trjExpensify** [comment] 2023-02-01 16:55
Ah yeah, totally. That was before we went the fork route. Make sense. We good to close this out then?

**Comment by Beamanator** [comment] 2023-02-01 17:25
Aah that makes sense. Ya I'm happy to let @mallenexpensify close it, not sure if all the payments are done

**Comment by mallenexpensify** [comment] 2023-02-01 17:56
All paid!

**Closed by mallenexpensify** 2023-02-01 17:56 UTC
Labels: Reviewing, External, Engineering, Weekly, Internal, Bug
