### ISSUE TITLE
[HOLD for payment 2023-07-06] [$1000] First message remains heighlighted on thread

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#19776] opened 2023-05-29 21:29 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. go to any chat
2. send any message
3. click on reply in thread option
4. go to thread and send any message
5. go to previous chat
6. click on same message and select reply in thread option
## Expected Result:
first message should not be highlighted
## Actual Result: 
first message highlights

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [x] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.19-6
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

<img src="https://github.com/Expensify/App/assets/43996225/ae9664a3-9c09-4cfb-9b32-709f6696eaa3" width="40%" height="40%">

https://github.com/Expensify/App/assets/43996225/70694b91-9eef-46e2-887e-1b6bbe1a2d9b

https://github.com/Expensify/App/assets/43996225/122d2daa-0936-4aa5-b20e-9331df72b3d9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @gadhiyamanan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1685076159930429

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01459c624ea436728a</li>
        <li>Upwork Job ID: 1663582287105273856</li>
        <li>Last Price Increase: 2023-06-20</li>
    </ul>
</details>

**Comment by bernhardoj** [comment] 2023-05-30 09:20
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
First message in thread is highlighted if we use Reply In Thread from (right-click) context menu.

### What is the root cause of that problem?
One of the reason the message is highlighted is when a context menu is active. Each message compare its action ID with the active action ID.
https://github.com/Expensify/App/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L111-L113

The active action ID will be cleared once we close the context menu.
https://github.com/Expensify/App/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L198-L202

One thing to keep in mind is that the thread first message action ID is the same as the thread parent action ID.
(thread parent action)
<img width="326" alt="image" src="https://github.com/Expensify/App/assets/50919443/33f1f4ab-1107-4602-b176-304c786abbea">
(thread first message action)
<img width="300" alt="image" src="https://github.com/Expensify/App/assets/50919443/502d7006-28c5-4f60-944b-1e4d55400e81">

The problem is, when we click Reply in thread, it will navigate us to the thread report before hiding the context menu.

https://github.com/Expensify/App/assets/50919443/c6a505ba-3840-424c-a3af-d2b6429b5369

Notice the context menu is late to hide.

This is because we are delaying the hiding (first param of `hideContextMenu`)
https://github.com/Expensify/App/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ContextMenu/ContextMenuActions.js#L119-L122

So, when we already navigated to the thread report, the first message mounted and think that the context menu is still active (well, technically it's but we should immediately close it before navigate to the thread report)
https://github.com/Expensify/App/blob/f0078298dbc9546cab847ff420eb375b07601c46/src/pages/home/report/ReportActionItem.js#L108-L109

### What changes do you think we should make in order to solve the problem?

1. We shouldn't delay to close/hide the context
2. If we are going to close/hide the context menu, i.e. `closePopover` is true, we should do the navigation after the hide completes.

Here is how it looks after both changes above:
```
if (closePopover) {
    hideContextMenu(false, () => {
        Report.navigateToAndOpenChildReport(lodashGet(reportAction, 'childReportID', '0'), reportAction, reportID);
        ReportActionComposeFocusManager.focus();
    });
} else {
    Report.navigateToAndOpenChildReport(lodashGet(reportAction, 'childReportID', '0'), reportAction, reportID);
}
```

### What alternative solutions did you explore? (Optional)
Add `reportID` check in `isActiveReportAction`.
```
return Boolean(actionID) && Boolean(reportID) && this.state.reportID === reportID && this.state.reportAction.reportActionID === actionID;
```
This works well, but I think we should still apply the main solution above and this one just as an additional improvement.

**Comment by puneetlath** [comment] 2023-06-02 21:14
@parasharrajat thoughts on the proposal?

**Comment by puneetlath** [comment] 2023-06-07 22:30
@parasharrajat thoughts on the proposals?

**Comment by bernhardoj** [comment] 2023-06-08 03:49
I believe the delay is used when we want to show some icon/text changes in the context menu before closing it, e.g. copy to clipboard, mark as unread.

https://github.com/Expensify/App/assets/50919443/ea066b84-97a6-46ff-ad03-029a88c710f8

**Comment by bernhardoj** [comment] 2023-06-08 06:56
The context menu will immediately close. The example we can see is in edit/delete message, flag message.
https://github.com/Expensify/App/blob/b8d45763b6d9dcf011ab66936df7eba85b80bc24/src/pages/home/report/ContextMenu/ReportActionContextMenu.js#L47-L68

**Comment by bernhardoj** [comment] 2023-06-08 12:39
> That is obvious

Indeed 😄.

We will just disable the delay for reply in thread, so no problem to the other menu. (notice the `shouldDelay` param in `hideContextMenu`. We will pass false for reply in thread)

**Comment by puneetlath** [comment] 2023-06-09 21:34
@sophiepintoraetz sorry I need to re-assign as I'm heading OOO for a week. Thanks for taking over!

**Comment by sophiepintoraetz** [comment] 2023-06-12 10:12
@maddylewis - I was baby-sitting this for Puneet but I'm headed OOO til 20 Jun, at which point Puneet should be back. I've reassigned him to keep track but I think Rajat is reviewing the proposal, so payments will be needed for:
- @gadhiyamanan (reporting - $250)
- @bernhardoj - contributor ($1000, plus maybe a bonus - I think Puneet needed to assign the job to [bernhardoj](https://github.com/bernhardoj) as well?)
- @parasharrajat  - c+ ($1000 plus maybe a bonus)

**Comment by maddylewis** [comment] 2023-06-14 00:19
just communicating that i am OOO until June 20. once we decide on a proposal, go ahead and post that update here. I'll follow up on this issue once i return - thanks!

**Comment by puneetlath** [comment] 2023-06-23 16:48
Sorry for the delay. @bernhardoj let's do it 💪🏾

**Comment by bernhardoj** [comment] 2023-06-24 07:08
PR is ready for review.

cc: @parasharrajat

**Comment by puneetlath** [comment] 2023-06-30 18:17
@gadhiyamanan @bernhardoj sent you both contracts. 

@parasharrajat I assume you'll request payment via Expensify? And also, friendly reminder about the checklist 😄

**Comment by puneetlath** [comment] 2023-07-05 15:56
@parasharrajat friendly reminder so that we can pay this out tomorrow!

**Comment by puneetlath** [comment] 2023-07-06 20:46
Thanks @parasharrajat. 

You'll be requesting payment via NewDot, is that right? 

@gadhiyamanan bump on accepting the Upwork offer.

**Comment by puneetlath** [comment] 2023-07-10 15:53
@gadhiyamanan and @bernhardoj have been paid. Just waiting for confirmation from @parasharrajat on whether they've requested payment in NewDot.

**Comment by anmurali** [comment] 2023-07-21 16:08
Approved 1500 based on https://github.com/Expensify/App/issues/19776#issuecomment-1609635699

**Comment by puneetlath** [comment] 2023-07-24 17:10
Great! Closing out.

**Closed by puneetlath** 2023-07-24 17:10 UTC
Labels: External, Engineering, Weekly, Overdue, Awaiting Payment, Bug
