### ISSUE TITLE
Hybrid - Android - App crashes on tapping "Domains" in settings page

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52998] opened 2024-11-23 13:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** V9. 0.66-0
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:** Y
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Launch app
2. Tap settings
3. Tap Domains

## Expected Result:
App must not crash on tapping "Domains" in settings page.

## Actual Result:
App crashes on tapping "Domains" in settings page.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [x] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos
[2311.txt](https://github.com/user-attachments/files/17879755/2311.txt)

https://github.com/user-attachments/assets/4ab0aeed-f476-4e55-9c63-89e9a0255f1e

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mountiny** [comment] 2024-11-25 14:15
I am not sure if this is hybrid app related, this button just opens the page in a browser

**Comment by youssef-lr** [comment] 2024-11-25 16:05
I couldn't reproduce this one in Browserstack @mountiny

**Comment by mountiny** [comment] 2024-11-25 16:17
This is the exception for this [case](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/022302da0d55dfb152b0c7d7d51a24a7?time=last-seven-days&types=crash&versions=9.0.66.2%20(509006602);9.0.66.3%20(509006603);9.0.66.0%20(509006600)&deviceCategories=Mobile:Xiaomi%EF%BF%BFM2101K7BI%E2%87%92Redmi%20Note%2010S&sessionEventKey=674167BD0361000148A69A5BF5D9DD2B_2018791896871282356)
```
Fatal Exception: com.facebook.react.common.JavascriptException: Error: TaskQueue: Error with task : [Pusher] instance not found. Pusher.subscribe()
            most likely has been called before Pusher.init(), js engine: hermes, stack:
anonymous@1:3789481
processNext@1:846927
_processUpdate@1:845633
anonymous@1:524029
_callTimer@1:522946
_callReactNativeMicrotasksPass@1:523147
callReactNativeMicrotasks@1:525099
__callReactNativeMicrotasks@1:217573
anonymous@1:215773
__guard@1:217447
flushedQueue@1:215684
callFunctionReturnFlushedQueue@1:215540

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
       at java.lang.Thread.run(Thread.java:1012)
        
```

**Comment by mountiny** [comment] 2024-11-26 20:19
I believe this might have been fixed now, feel free to ask for a retest and close

**Comment by CortneyOfstad** [comment] 2024-12-02 16:02
Sounds good — thanks Vit!

**Comment by CortneyOfstad** [comment] 2024-12-06 17:08
Still waiting for it to be retested, so not overdue!

**Comment by CortneyOfstad** [comment] 2024-12-09 18:18
Still waiting on testing!

**Comment by CortneyOfstad** [comment] 2024-12-11 18:25
Before this goes overdue — still waiting for it to be tested 😂

**Comment by CortneyOfstad** [comment] 2024-12-11 18:25
Going to also post in the room to see if we can get this moving

**Comment by CortneyOfstad** [comment] 2024-12-11 18:27
Posted in `#qa` here — https://expensify.enterprise.slack.com/archives/C9YU7BX5M/p1733941658006679

**Comment by mvtglobally** [comment] 2024-12-12 16:39
not repro 

https://github.com/user-attachments/assets/9b43ca75-fff5-4cd0-81ee-75f2b09e5d58

**Comment by mvtglobally** [comment] 2024-12-14 05:05
Issue not reproducible during KI retests. (First week)

**Comment by muttmuure** [comment] 2024-12-17 12:00
If this is no longer happening, let's close

**Closed** 2024-12-17 17:29 UTC
Labels: Engineering, Daily, Overdue, Bug, retest-weekly
