### ISSUE TITLE
[HOLD for payment 2023-10-10] [$500] Web -  Country and State fields are empty if accessed via deep link

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#27814] opened 2023-09-19 21:07 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open App -> Navigate to Settings -> Profile -> Personal Details -> Home address
2. Enter Address details > Save the updated address
3. Copy address URL (https://staging.new.expensify.com/settings/profile/personal-details/address)
4. Sign Out
5. Paste URL and hit enter
6. Login with your credentials
7. Home address page opens but "Country" and "State" values are missing

## Expected Result:
"Country" and "State/Province" values should be shown if saved by user

## Actual Result:
"Country" and "State/Province" values are missing given that user's saved the values

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.70.7
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/802e981e-ec50-4aab-871f-26e139ce1c59

https://github.com/Expensify/App/assets/93399543/c265482f-d78e-46cd-8a55-390ff5ff38be

**Expensify/Expensify Issue URL:**
**Issue reported by:** @ufumerfarooq
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695140296239169

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by saranshbalyan-1234** [comment] 2023-09-19 21:21
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
"Country" and "State/Province" values are missing while using deeplink
## What is the root cause of that problem?
https://github.com/Expensify/App/blob/f6efb269a587aa664ee2a94366bb9aeedcc4cae2/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L70
The address object is initially empty, which is causing the issue as we are not setting the state and country states once the address object is changed.
https://github.com/Expensify/App/blob/f6efb269a587aa664ee2a94366bb9aeedcc4cae2/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L73
https://github.com/Expensify/App/blob/f6efb269a587aa664ee2a94366bb9aeedcc4cae2/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L65
## What changes do you think we should make in order to solve the problem?
```javascript
    useEffect(() => {
      setState(address.state)
      setCurrentCountry(address.country)
    }, [address]);
    
``` 
Also we can move country state from
https://github.com/Expensify/App/blob/f6efb269a587aa664ee2a94366bb9aeedcc4cae2/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L65
to this
```javascript
    const [currentCountry, setCurrentCountry] = useState(PersonalDetails.getCountryISO(address.country));
``` 
### What alternative solutions did you explore? (Optional)
N/A

**Comment by lcsvcn** [comment] 2023-09-19 22:45
# Proposal
## Please re-state the problem that we are trying to solve in this issue
Country and State fields are empty if accessed via deep link 

## What is the root cause of that problem?
The issue arises from the fact that the address.state and address.country values are being fetched after the initial state initialization. This delay in fetching the values is due to the presence of an isLoading variable. Consequently, when the initial state is set, it is based on an empty JSON object because the actual values have not yet been retrieved. This results in incorrect initialization with empty values, which should ideally reflect the user's address information.


## What changes do you think we should make in order to solve the problem?

I recommend initializing all fields (such as state, country, firstStreet, and secondStreet) with empty values initially. Then, use the useEffect hook to update these fields only when the isLoadingPersonalDetails variable indicates that the data retrieval process has completed.

This approach simplifies the code and ensures that we always work with the most up-to-date values.

At `src/pages/settings/Profile/PersonalDetails/AddressPage.js`:
```
    const address = lodashGet(privatePersonalDetails, 'address') || {};
    const isLoadingPersonalDetails = lodashGet(privatePersonalDetails, 'isLoading', true);

    const [state, setState] = useState('');
    const [country, setCountry] = useState('');
    const [firstStreet, setFirstStreet] = useState('');
    const [secondStreet, setSecondStreet] = useState('');
    
    useEffect(() => {
       if(isLoadingPersonalDetails === true) { 
            return;
        }
        
        const street =  (address.street || '').split('\n');
        
        setState(address.state);
        setCountry(address.country);
        setFirstStreet(street[0]);
        setFirstStreet(street[1]);
    }, [address, isLoadingPersonalDetails]);

```

## What alternative solutions did you explore? (Optional)
N/A

**Comment by DylanDylann** [comment] 2023-09-20 08:42
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Country and State fields are empty if accessed via deep link

### What is the root cause of that problem?
Firstly, a small question: Why only country and State fields are empty?

https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L73
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L65


Let's see here, we only use useState for country and state field. After the default value of useState is updated, the state value is not updated. It causes this issue. **This is BUG 1**

We only use useState for country and state fields because we need to re-set 2 fields when changing country
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L119-L129

I think the city field also should be clear after changing country like state field. **This is BUG 2**

### What changes do you think we should make in order to solve the problem?
Firstly, we need to use useState for city field
```
const [city, setCity] = useState(address.city);
```
When country change we need to re-set city to empty like this
```
const handleAddressChange = (value, key) => {
        if (key !== 'country' && key !== 'state' && key !== 'city') {          // UPDATE HERE
            return;
        }
        if (key === 'country') {
            setCurrentCountry(value);
            setState('');
            setCity('');         // UPDATE HERE
            return;
        }
        setState(value);
        setCity(value);

    };

```
and then in here
https://github.com/Expensify/App/blob/70e9fa0a77aba91abd12d8d0023ce10e7bfe80a7/src/pages/settings/Profile/PersonalDetails/AddressPage.js#L211

we should use value instead of default value
```
value={city || ''}
```

After that, we need to update country, state, city when address change 
```
useEffect(() => {
        setState(address.state);
        setCity(address.city);
        setCurrentCountry(PersonalDetails.getCountryISO(address.country));
    }, [address])
```
### Result

https://github.com/Expensify/App/assets/141406735/a98097fe-22da-44aa-8e45-9e4acabcda5d

**Comment by Christinadobrzyn** [comment] 2023-09-20 18:53
This can be reproduced- @eVoloshchak let me know what you think of any of the provided proposals

**Comment by eVoloshchak** [comment] 2023-09-21 14:51
I think we should proceed with @saranshbalyan-1234's [proposal](https://github.com/Expensify/App/issues/27814#issuecomment-1726504409)

There are some additional suggestions from @lcsvcn and @DylanDylann that extend @saranshbalyan-1234's proposal, but I think the proposals aren't significantly different, @saranshbalyan-1234's proposal was the first to correctly identify the root cause and propose an appropriate fix

> When country change we need to re-set city to empty like this

@DylanDylann, I see where you're coming from, but I believe this is by design. We don't clear anything besides state when changing a country, it's not necessarily linear, you can populate all of the fields in any order

🎀👀🎀 C+ reviewed!

**Comment by saranshbalyan-1234** [comment] 2023-09-24 18:05
@techievivek  @eVoloshchak can you check, as this is not being updated.

**Comment by eVoloshchak** [comment] 2023-09-24 19:34
@saranshbalyan-1234, it will be updated on Monday I think

**Comment by saranshbalyan-1234** [comment] 2023-09-24 19:36
@eVoloshchak am I still eligible for bonus as internal member is taking time to review?

**Comment by eVoloshchak** [comment] 2023-09-24 19:38
> Payment timelines are based on the day and timestamp the contributor is assigned to the Github issue by an Expensify employee

You haven't been assigned to this job yet, so the countdown hasn't started

**Comment by Christinadobrzyn** [comment] 2023-09-26 17:34
Hey @techievivek can you check this proposal review to see if you're okay with us moving forward with assigning the job to @saranshbalyan-1234 https://github.com/Expensify/App/issues/27814#issuecomment-1729744730

**Comment by DylanDylann** [comment] 2023-09-28 08:13
@eVoloshchak In this PR, we apply logic to reset the city field when changing country. So please help to fix this bug with the city field in the PR phrase

**Comment by saranshbalyan-1234** [comment] 2023-09-28 09:13
hi @techievivek  this is first time i am pushing my code here, i am getting 
remote: Permission to Expensify/App.git denied to saranshbalyan-1234.
can you help?

**Comment by saranshbalyan-1234** [comment] 2023-09-28 10:08
PR will be raised by today.

**Comment by saranshbalyan-1234** [comment] 2023-09-28 14:16
@eVoloshchak  [PR](https://github.com/Expensify/App/pull/28393/files) is ready for review, please check

**Comment by saranshbalyan-1234** [comment] 2023-09-28 16:53
CLA issues now fixed and[ PR ](https://github.com/Expensify/App/pull/28404) is ready, please check

**Comment by saranshbalyan-1234** [comment] 2023-10-03 15:05
checked with web and ios safari, both are working fine

**Comment by ufumerfarooq** [comment] 2023-10-03 15:37
@saranshbalyan-1234 seems like "City" field is not populating

https://github.com/Expensify/App/assets/13478525/9c13449c-6c19-4a22-9e63-dd2134802553

**Comment by ufumerfarooq** [comment] 2023-10-03 15:49
@saranshbalyan-1234 yes, you are right.

**Comment by saranshbalyan-1234** [comment] 2023-10-03 15:50
do i need to fix this in my PR or the one who caused this regression will fix?

**Comment by ufumerfarooq** [comment] 2023-10-03 15:51
Don't know either, @eVoloshchak can guide you better

**Comment by saranshbalyan-1234** [comment] 2023-10-03 17:25
also, this PR i think is eligible for bonus, as PR is merged within 5 days, including weekends which means 3 business days.
Please check

**Comment by eVoloshchak** [comment] 2023-10-03 19:33
> do i need to fix this in my PR or the one who caused this regression will fix?

@saranshbalyan-1234, the PR that caused the regressing should fix this

**Comment by saranshbalyan-1234** [comment] 2023-10-03 19:35
> also, this PR i think is eligible for bonus, as PR is merged within 5 days, including weekends which means 3 business days. Please check

@eVoloshchak can you please check this, and tell if i am wrong

**Comment by eVoloshchak** [comment] 2023-10-03 19:46
Agree, according to my calculations this was merged in 46 hours (96 minus 48, since there were two weekend days)

**Comment by saranshbalyan-1234** [comment] 2023-10-03 20:39
Thanks for explaining :)

**Comment by Christinadobrzyn** [comment] 2023-10-10 19:28
Payouts due after we get the checklist done: 

Issue Reporter: $50 @ufumerfarooq (will be paid in Upwork)
Contributor: $500 + $250 bonus @saranshbalyan-1234 (please apply for the job in [Upwork](https://www.upwork.com/jobs/~010def5669f0fd1df5))
Contributor+: $500 + $250 bonus @eVoloshchak (paid outside Upwork

Eligible for 50% #urgency bonus? Y - based on https://github.com/Expensify/App/issues/27814#issuecomment-1745619576

Upwork job is [here](https://www.upwork.com/jobs/~010def5669f0fd1df5).

@eVoloshchak can you complete the [checklist](https://github.com/Expensify/App/issues/27814#issuecomment-1745236196) for us?

**Comment by ufumerfarooq** [comment] 2023-10-10 19:35
@Christinadobrzyn can you please guide me on how the payouts work for reporters?

**Comment by Christinadobrzyn** [comment] 2023-10-10 20:26
@ufumerfarooq Happy to clarify. We recently changed our payments:

- Any GHs created after Aug 30th - the reporter gets $50
- Any GHs created before Aug 30th - the reporter received $250 (old pricing and there are still some open GHs before Aug 30th)
- If a contributor is also the reporter, the contributor will be paid as the reporter and also as the contributor (so $50 + $500, etc).

**Comment by Christinadobrzyn** [comment] 2023-10-10 20:28
@saranshbalyan-1234 I think you'll see an offer now, I'll hire you for the $500 and include the $250 bonus (so the price will be $750 but the breakdown on the offer will be different).

**Comment by Christinadobrzyn** [comment] 2023-10-10 20:33
@eVoloshchak can you complete the https://github.com/Expensify/App/issues/27814#issuecomment-1745236196 for us? Thanks!

**Comment by eVoloshchak** [comment] 2023-10-12 14:40
- The PR that introduced the bug has been identified. Link to the PR: there isn't a PR that caused this bug, it was present in the initial implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, this is a case that was missed during the initial implementation. We already have a reviewer checklist item precisely for these types of bugs:  `If the PR modifies a component or page that can be accessed by a direct deeplink, I verified that the code functions as expected when the deeplink is used - from a logged in and logged out account.`

**Comment by JmillsExpensify** [comment] 2023-10-12 18:42
$750 payment approved for @eVoloshchak based on the BZ summary.

**Comment by Christinadobrzyn** [comment] 2023-10-12 20:43
regression test here - https://github.com/Expensify/Expensify/issues/325802

Payment is complete - based on - https://github.com/Expensify/App/issues/27814#issuecomment-1756094681

Closing!

**Closed by Christinadobrzyn** 2023-10-12 20:43 UTC
Labels: External, Daily, Awaiting Payment, Bug
