### ISSUE TITLE
[HOLD for payment 2024-10-14] [HOLD for payment 2024-10-11] [$250] Distance - Waypoints change to duplicate waypoints after drag and drop waypoints

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#50176] opened 2024-10-03 17:51 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.44-3
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5040727
**Email or phone of affected tester (no customers):** applausetester+pso@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to FAB > Submit expense > Distance
3. Enter three waypoints A - B - C
4. Drag waypoint B to waypoint C and now it becomes A - C - B
5. Drag waypoint C to waypoint B

## Expected Result:
The resulting waypoints will be A - B - C

## Actual Result:
The resulting waypoints become A - C - C

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/79143b56-f28a-4a7f-b534-2baadf09cc35

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021841915588250417056</li>
        <li>Upwork Job ID: 1841915588250417056</li>
        <li>Last Price Increase: 2024-10-03</li>
<li>Automatic offers: </li>
<ul>
<li>nkdengineer | Contributor | 104254910</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mananjadhav</details>

**Comment by lanitochka17** [comment] 2024-10-03 17:52
We think that this bug might be related to #wave-collect - Release 1

**Comment by Beamanator** [comment] 2024-10-03 18:58
This looks external b/c I'm seeing that the data sent to the backend (for `GetRouteForDraft` looks like it's incorrect / in the incorrect order), so it looooks like it's the front end's fault for sending the wrong data

**Comment by Beamanator** [comment] 2024-10-03 19:01
cc @bernhardoj in case you have ideas here

**Comment by Beamanator** [comment] 2024-10-03 19:07
After adding A, B, C, then moving C to B, I see 3 `GetRouteForDraft` calls which isn't great 🤔

**Comment by nkdengineer** [comment] 2024-10-03 20:06
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The resulting waypoints become A - C - C

### What is the root cause of that problem?
The problem is here when we drag and drop waypoints, the `emptyWaypointIndex` is `-1` but we still call `removeWaypoint `

https://github.com/Expensify/App/blob/e8c4faf0973716e1de9a9cbe4d47946edabb7c8c/src/pages/iou/request/step/IOURequestStepDistance.tsx#L389-L392

Then here the removed is not empty because we `splice(-1, 1)` which will remove the last waypoint
 
https://github.com/Expensify/App/blob/e8c4faf0973716e1de9a9cbe4d47946edabb7c8c/src/libs/actions/Transaction.ts#L141

So the `GetRouteForDraft` is often called because the waypoint is changed wrongly.

I noticed that the bug also happens in production but it's swift and only calls `GetRouteForDraft` one time maybe because these functions run very fast.

https://github.com/Expensify/App/blob/e8c4faf0973716e1de9a9cbe4d47946edabb7c8c/src/pages/iou/request/step/IOURequestStepDistance.tsx#L389-L392


https://github.com/user-attachments/assets/8b12a8f5-00dc-45a3-bb43-1b6be8688f06


### What changes do you think we should make in order to solve the problem?
We should return early here if the `currentIndex` is `-1` because that means there is no waypoint that needs to be removed


https://github.com/Expensify/App/blob/331613663b9b3ce10c5fff5e88355b445290fdb9/src/libs/actions/Transaction.ts#L134

Or we can prevent calling `removeWaypoint` if `emptyWaypointIndex` is `-1`
https://github.com/Expensify/App/blob/e8c4faf0973716e1de9a9cbe4d47946edabb7c8c/src/pages/iou/request/step/IOURequestStepDistance.tsx#L389-L392

### What alternative solutions did you explore? (Optional)

**Comment by jasperhuangg** [comment] 2024-10-03 20:07
@nkdengineer Thanks, can you get a fix up soon?

**Comment by nkdengineer** [comment] 2024-10-03 20:08
sure.

**Comment by jasperhuangg** [comment] 2024-10-03 20:14
@Nodebrute changing that will introduce a previous regression that was solved, thanks for commenting though!

**Comment by nkdengineer** [comment] 2024-10-03 20:23
@mananjadhav The PR is ready cc @jasperhuangg.

**Comment by Beamanator** [comment] 2024-10-03 21:47
@nkdengineer thanks for the PR, so you didn't figure out what change caused the full regression eh? I still think at least the 3-calls of `GetRouteForDraft` per waypoint change was a regression b/c on prod i only saw that command called once per change

**Comment by jasperhuangg** [comment] 2024-10-03 21:50
Ah hmm, it would be nice if we could also address the extra API calls in your PR @nkdengineer

**Comment by nkdengineer** [comment] 2024-10-03 21:52
@jasperhuangg With my PR, that will also fix the extra API calls let see the result video.

https://github.com/user-attachments/assets/aeb318ba-fab6-4ad0-b5c9-3907487dd031

**Comment by Beamanator** [comment] 2024-10-03 21:57
Swapping @allroundexperts in to test, as discussed in slack [here](https://expensify.slack.com/archives/C02NK2DQWUX/p1727992051878199)

**Comment by Beamanator** [comment] 2024-10-03 22:43
PR was merged, being CP'd now

**Comment by Beamanator** [comment] 2024-10-04 14:24
Looking good to me in staging!!

**Comment by OfstadC** [comment] 2024-10-14 18:58
## Payment Summary

- @allroundexperts - due $250 via manual New Expensify request
- @nkdengineer - paid $250 via Upwork

**Closed** 2024-10-14 18:58 UTC
Labels: External, Engineering, Daily, Awaiting Payment

**Comment by JmillsExpensify** [comment] 2024-12-30 11:47
$250 approved for @allroundexperts
