### ISSUE TITLE
Workspace - Nothing happens after pressing ESC key on workspace editor

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#49869] opened 2024-09-27 21:12 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.41-1
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** applausetester+kh2591@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to Account settings > Workspaces.
3. Click on any workspace.
4. Press ESC key.

## Expected Result:
App will return to Workspaces list.

## Actual Result:
Nothing happens after pressing ESC key on workspace editor.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by IuliiaHerets** [comment] 2024-09-27 21:13
We think that this bug might be related to #wave-collect - Release 1

**Comment by bondydaa** [comment] 2024-09-27 21:20
I don't think this needs to be a blocker and I'm not actually sure if that is a useful UX pattern to have.

**Comment by bondydaa** [comment] 2024-09-27 21:33
started a discussion here https://expensify.slack.com/archives/C03U7DCU4/p1727472828047069

**Comment by bernhardoj** [comment] 2024-09-28 05:00
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pressing ESC doesn't close RHP.

### What is the root cause of that problem?
The ESC shortcut is overridden by the SearchRouter shortcut here.
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/Search/SearchRouter/SearchRouter.tsx#L62-L65

The SearchRouter is added to the AuthScreens which is available app wide.
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L573

Because of that, the shortcut here to close RHP doesn't work anymore.
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L308-L320

This somehow happens after https://github.com/Expensify/App/pull/49185 where we migrate from withOnyx to useOnyx. Before migration, the SearchRouter shortcut is subscribed first, followed by the AuthScreen shortcut. The reason the SearchRouter shortcut still works is that we enable bubbling in the AuthScreen shortcut.

After the migration, the AuthScreen shortcut is subscribed first, followed by the SearchRouter shortcut. So, pressing ESC will trigger the SearchRouter shortcut.

Even though this happens after https://github.com/Expensify/App/pull/49185, I'd say the root cause is coming from the initial [PR](https://github.com/Expensify/App/pull/48785) that adds the SearchRouter.

### What changes do you think we should make in order to solve the problem?

In SearchRouter, only enable the shortcut when visible.
https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/Search/SearchRouter/SearchRouter.tsx#L62-L65

```
useKeyboardShortcut(CONST.KEYBOARD_SHORTCUTS.ESCAPE, () => {
    closeSearchRouter();
    clearUserQuery();
}, {isActive: isSearchRouterDisplayed});
```

https://github.com/Expensify/App/blob/71db3f19691069182447b6b1b9fff62ec93be86c/src/components/Search/SearchRouter/SearchRouter.tsx#L25
However, I noticed that we only clear the query when closing the modal using ESC, but the query state stays if we close it by simply clicking outside the modal. To solve this, instead of clearing the query inside the shortcut, we can clear it when the modal closes.
```
onModalHide={clearUserQuery}
```

**Comment by IuliiaHerets** [comment] 2024-09-28 21:44
@bondydaa @muttmuure This issue happens to all RHP

https://github.com/user-attachments/assets/f9939451-2d94-48c9-89ea-f884e95a9b3d

**Comment by bondydaa** [comment] 2024-09-30 16:03
looks like the offending PR was reverted here https://github.com/Expensify/App/pull/49185#issuecomment-2383267769 / https://github.com/Expensify/App/pull/49922

Looks @IuliiaHerets can you retest when you have a moment and confirm?

**Comment by bondydaa** [comment] 2024-10-02 19:22
just tested myself and see the esc key working as expected again on RHP and as described to go back from workspace settings. closing.

**Closed by bondydaa** 2024-10-02 19:22 UTC
Labels: Engineering, Daily, Overdue, Bug
