### ISSUE TITLE
 Error thrown when flagging a thread message in "admin only" room

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22384] opened 2023-07-06 22:03 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Login to new dot using account A" and create a workspace with another account "B" as a member and change the who can post setting to Admin only
2. Send a message to the announce room of the workspace created above using account A and long press the message and click on reply in a thread
3. Send another message in the thread
4. Login in to staging new dot using account B and go to the announce room of the above workspace and click on the thread
5. Flag the first message in the thread as assault
6. Observe that an "Auth createReportAction... Error is thrown"

 
## Expected Result: 
No error thrown
## Actual Result: 
"Auth createReportAction... error is  thrown

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.37-2
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/6842c23c-09d4-494a-a022-d5643f495e08

https://github.com/Expensify/App/assets/43996225/83ade4a4-fb97-42cf-9f1d-39ba30ba7def

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688584390757019

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jeet-dhandha** [comment] 2023-07-07 04:14
Dupe of https://github.com/Expensify/App/issues/22311

**Comment by joekaufmanexpensify** [comment] 2023-07-07 12:39
Ah yep. This is a dupe of that issue. The error returned is the exact same. Closing as we're fixing this in the other issue!

**Closed by joekaufmanexpensify** 2023-07-07 12:39 UTC
Labels: Daily, Bug
