### ISSUE TITLE
[Hold for payment - 2024-03-07] MEDIUM: Custom message sound not consistent on mobile

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#36579] opened 2024-02-15 13:21 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.42-0
**Reproducible in staging?:** Yes

## Action Performed:
- Send a message to a user signed in on mobile in three different app states: 
    - App Killed
    - App Open
    - App in background

## Expected Result:

- App Killed: Custom sound
- App Open: Custom sound
- App in background: Custom sound

## Actual Result:

- App Killed: Default notification sound
- App Open: Custom sound
- App in background: Default notification sound

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by Julesssss** [comment] 2024-02-15 13:42
I can also help with backend changes. As you mentioned we may need to start sending a reportType variable -- _though I also think we don't send IOU notifications currently_

**Comment by Julesssss** [comment] 2024-02-19 15:04
@kirillzyusko and I discussed. We can drop the message received sound on mobile apps as this is being handled by the OS push notification itself.

**Comment by Julesssss** [comment] 2024-02-22 13:54
Assigning @abdulrahuman5196 based on [this comment](https://expensify.slack.com/archives/C02NK2DQWUX/p1708607683163729)

**Comment by kirillzyusko** [comment] 2024-02-28 14:16
@Julesssss since the PR was merged - what should we do with that issue? Should we re-test and close it?

**Comment by Julesssss** [comment] 2024-02-28 15:45
Yeah, I'll try and find time tomorrow to do this. If you're able to verify iOS that would be very helpful.

**Comment by kirillzyusko** [comment] 2024-02-28 16:17
@Julesssss does the app publicly available or do I need to get the invite (to TestFlight, for example)? If everyone can test, then would you mind to share a link here? 👀 (sorry for being asking such simple questions, but it's a first time when I'm testing the app deployed to staging)

**Comment by Julesssss** [comment] 2024-02-29 09:33
No problem. You would need to get invited to Testflight to test staging, but the PR has already been [deployed to production](https://github.com/Expensify/App/pull/36807#issuecomment-1970129722), so you can use the play store app to verify 👍

**Comment by Julesssss** [comment] 2024-02-29 09:34
I'm going to close this issue as fixed, but let's discuss the other bugs on their respective issues.

**Comment by abdulrahuman5196** [comment] 2024-02-29 10:27
Hi, @Julesssss C+ payment processing would be pending on this issue. 

Kindly re-open the issue.

cc: @CortneyOfstad

**Comment by Julesssss** [comment] 2024-02-29 11:02
Awaiting C+ payment

**Comment by abdulrahuman5196** [comment] 2024-03-05 09:15
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Update to existing implementation

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open app on two devices (A - iOS, B - Android)
2) Send a message from device A to device B
3) Be sure that you hear a custom sound only when message is received (plain messages)
4) Send message from device B to device A
5) Be sure that you hear a custom sound only when message is received (plain messages)
6) Open app on two devices (any platforms, exclude iOS/Android platform)
7) Send a message from device A to device B
8) Be sure that sound can be heard

**Comment by Julesssss** [comment] 2024-03-05 09:46
We're still making changes to the push notification logic so this test will soon be outdated. We'll create one seperately once the changes are complete.

**Comment by CortneyOfstad** [comment] 2024-03-11 17:56
Sorry, was OoO last week — handling the payment now!

**Comment by CortneyOfstad** [comment] 2024-03-11 17:59
@Julesssss in regards to the comment [here](https://github.com/Expensify/App/issues/36579#issuecomment-1978349767), is a regression test needed here if there will be separate tests created after the logic is adjusted? Just trying to confirm — thank you!

**Comment by CortneyOfstad** [comment] 2024-03-11 18:07
@abdulrahuman5196 I sent you a job offer here — https://www.upwork.com/jobs/~01d297cc64a730c705

Not sure why the job did not post originally, but please let me know once you accept and I'll get that paid ASAP. Thanks!

**Comment by abdulrahuman5196** [comment] 2024-03-11 18:20
@CortneyOfstad  accepted the offer. Thank you

**Comment by CortneyOfstad** [comment] 2024-03-12 13:34
Perfect! This can be closed — thanks everyone!

**Closed by CortneyOfstad** 2024-03-12 13:34 UTC
Labels: Reviewing, Weekly, Bug
