### ISSUE TITLE
Android - Tag - On disabling region sub tags, "required" is shown

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#43272] opened 2024-06-07 12:44 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.80
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4602370
**Issue reported by:** Applause - Internal Team

## Action Performed:
Pre-condition: Have tag enabled in new dot and in old dot upload dependent tag
1. Launch app
2. Go to Workspace settings
3. Tap tag-- state-- California
4. Edit name and tap save
5. Wait few seconds and note hmm not here shown
6. Tap app back button
7. Note state field , " Required " tag shown beside
8. Tap region
9. Select both sub classes and disable tag
10. Tap app back button and note "region" field

## Expected Result:
After editing state sub tag hmm not here must not be shown. Since people must tag expense selected, "required" tag must be displayed beside "state" tag initially itself
After disabling region sub tags, "required" must not be shown beside region field

## Actual Result:
After editing state sub tag hmm not here shown and "required" tag displayed beside "state" tag
After disabling region sub tags, "required" is shown beside region field

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0e6cc143-a3c2-4686-a413-a789da955e85

https://github.com/Expensify/App/assets/78819774/ccc5dd80-0945-4d63-9bbb-095bead6be91

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by jliexpensify** [comment] 2024-06-11 04:22
Hi @amyevans @marcochavezf I think you're both working on Tags, right?

Is the issue here that `California56` isn't a real location, which is why it's throwing up a `required` error?

**Comment by marcochavezf** [comment] 2024-06-11 19:01
I'm not super familiar with tags, but I wonder why the page "hmm not here" page is shown? From the test steps looks like that's an expected behavior but probably it's causing the `required` error

**Comment by amyevans** [comment] 2024-06-11 19:41
I'm not able to reproduce the first bug:

https://github.com/Expensify/App/assets/7277067/c9a29918-e114-4cfa-9a59-cf8c99359f16

As for the second, I'm not quite sure what is going on. But I do know we don't support dependent tags in NewDot yet (slated for November release: https://github.com/Expensify/Expensify/issues/388722), so I suspect it might just be a side effect of that and producing unexpected behavior. For comparison, on OldDot I see this message:
![Screenshot 2024-06-11 at 3 36 53 PM](https://github.com/Expensify/App/assets/7277067/c86efe03-afb9-4c49-ad8c-746774595295)

**Comment by jliexpensify** [comment] 2024-06-11 22:42
Got it, thanks to both of you for checking this out! So it sounds like we can close this GH based off the fact that Tags in ND is still a work in progress?

**Comment by amyevans** [comment] 2024-06-12 16:23
Yeah I'm onboard with closing.

**Closed by amyevans** 2024-06-12 16:23 UTC
Labels: Daily, Bug
