### ISSUE TITLE
[$1000]  Nested task is not updating its parent when there is a change inside it(new message and new attachement)

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#23517] opened 2023-07-24 22:25 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open two chats
2. Assign a task to Account B
3. Using Account B go to the task
3. Inside the newly created task, create a new, nested, task
4. Send a message or attach a file inside the nested task
## Expected Result: 
Account B should be updated with the number of Reply
## Actual Result: 
Account B is not updated. It is only updated once you go inside the nested task and come back to the parent task

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.44-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

[nested task does not update the parent when there is a change(chat and upload).webm](https://github.com/Expensify/App/assets/43996225/3a883482-ba00-49ff-9b5f-5edc3887860f)

https://github.com/Expensify/App/assets/43996225/1854dbc9-5508-40ce-a8ca-acfb5377c013

**Expensify/Expensify Issue URL:**
**Issue reported by:** @kassahun-asefa
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1689576766600559

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01fe1104a67eb604e2</li>
        <li>Upwork Job ID: 1686513777080283136</li>
        <li>Last Price Increase: 2023-10-25</li>
    </ul>
</details>

**Comment by MayankVir** [comment] 2023-08-02 05:14
@kavimuru I would like to work on this issue. Will be sending you proposal shortly

**Comment by johncschuster** [comment] 2023-08-02 18:33
@MayankVir @kavimuru is not the one that will accept your proposal. @ArekChr will be reviewing and accepting proposals.

**Comment by akamefi202** [comment] 2023-08-03 08:43
I think this is backend issue.
When we add a comment or an attachment in child task page, Pusher of the back-end sends data to only subscribers of child task channel.
In above example video, user B didn't open the child task page so he didn't subscribed the child task channel of Pusher yet.
He only subscribed the parent task channel by opening the parent task page.
As a result, user B didn't receive updated data from Pusher and reply count in the parent task page isn't updated.

Pusher should send data to subscribers of parent task channel too.
So user B will receive updated data which contains new retry count and the parent task page will be updated with it.

**Comment by johncschuster** [comment] 2023-08-03 21:33
@ArekChr, what are your thoughts on @akamefi202's comment above? Do you agree that this is a backend issue? Do I need to take this `Internal`?

**Comment by ArekChr** [comment] 2023-08-04 11:09
@johncschuster @akamefi202 Currently, all child threads are correctly subscribed to in reports when the parent report is opened. I think what's missing here is a similar tracking mechanism for tasks. I'm still investigating this issue to determine whether it's a BE or FE issue.

**Comment by johncschuster** [comment] 2023-08-07 21:25
@ArekChr how's the investigation going? Also, can you help me understand what BE and FE means in your previous comment? I'm unfamiliar with those acronyms.

Thanks!

**Comment by ArekChr** [comment] 2023-08-08 10:35
Hey @johncschuster, I mean BE as "Backend." FE as "Frontend"

**Comment by johncschuster** [comment] 2023-08-08 21:01
Goooot it. Thanks for clarifying that!

**Comment by ArekChr** [comment] 2023-08-09 07:55
No updates on the investigation yet. @johncschuster, could you involve an internal backend engineer to help determine if this is a pushed backend issue?

**Comment by ShogunFire** [comment] 2023-08-09 12:55
I don't reproduce, maybe it's fixed ? 

https://github.com/Expensify/App/assets/19537677/ac1cb2cf-776f-46f6-a0aa-476fec79684b

**Comment by madmax330** [comment] 2023-08-09 16:35
cc @thienlnam another tasks one

**Comment by thienlnam** [comment] 2023-08-09 17:03
This is getting fixed as part of another issue (don't have the link right now though)

**Comment by Habtamu-Asefa** [comment] 2023-08-14 11:28
> This is getting fixed as part of another issue (don't have the link right now though)

would you share the link here when you get it?

**Comment by thienlnam** [comment] 2023-08-14 14:28
We already have a BE issue to return more parameters for unread indicator - I believe that same PR https://github.com/Expensify/Expensify/issues/307566 should also return more parameters related to this as well, let's re-evaluate when that related App PR is solved

**Comment by johncschuster** [comment] 2023-09-05 20:37
Looks like the PRs for #22299 are now live. Shall we pick this one back up?

**Comment by thienlnam** [comment] 2023-09-05 21:13
Yeah let's see if this is still reproducible after those changes

**Comment by ArekChr** [comment] 2023-09-14 10:04
@thienlnam Could you look into that?

**Comment by johncschuster** [comment] 2023-09-26 17:40
Bump, @thienlnam^^

**Comment by thienlnam** [comment] 2023-09-27 03:07
Haven't gotten around to this yet - though it should be the same as a task in the parent report. The replies should be updated the same way and I'm not sure why it would be different with a nested task. 

It might have to do with the way AddComment works within a nested task, hoping to get around to it later this week

**Comment by mvtglobally** [comment] 2023-10-05 03:07
Issue not reproducible during KI retests. (First week)

**Comment by thienlnam** [comment] 2023-10-05 07:25
We actually merged a PR that probably fixes this as part of a different bug https://github.com/Expensify/App/pull/28128

**Comment by kassahun-asefa** [comment] 2023-10-09 15:58
what about reporting bonus? since this reported first

**Comment by thienlnam** [comment] 2023-10-09 19:11
We can pay the reporting bonus here, and then close the issue cc @johncschuster

**Comment by mvtglobally** [comment] 2023-10-12 03:50
Issue not reproducible during KI retests. (Second week)

**Comment by kassahun-asefa** [comment] 2023-10-14 08:49
@thienlnam @johncschuster i haven't received my reporting bonus. There is a problem with my Upwork account. Can I receive my bonus through my brother's?

**Comment by thienlnam** [comment] 2023-10-16 18:27
For legal reasons we're only able to pay you directly. 

As a reminder, our CONTRIBUTING.md and Upwork's ToS make it clear that it the contributor's responsibility to have a verified account in order to get paid
* Our [CONTRIBUTING.md](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) which states "Please make sure your Upwork profile is fully verified before applying, otherwise you run the risk of not being paid."
* [Upwork's TOS](https://www.upwork.com/legal#enforcingTOUs) which states "If you break any of these rules, we can suspend your account and stop you from using Upwork"

**Comment by kassahun-asefa** [comment] 2023-10-16 19:44
Thank you for the reminder. @thienlnam

**Comment by thienlnam** [comment] 2023-10-18 17:48
Since the report was reported by @kassahun-asefa, and this is the associated Upwork account https://www.upwork.com/freelancers/~01e9c1bf271216783f that should be fine to pay - @johncschuster are you able to take care of the reporting payout here?

**Comment by johncschuster** [comment] 2023-10-20 11:12
Yep! I'll get payment issued today!

**Comment by kassahun-asefa** [comment] 2023-10-23 10:59
@johncschuster a kind reminder for bonus payment

**Comment by johncschuster** [comment] 2023-10-24 12:47
Ah, Upwork is being frustrating. I'm going to make a payment issue. Sorry for the delay.

**Comment by johncschuster** [comment] 2023-10-24 12:55
@kassahun-asefa I've just invited you to a new job on Upwork called `[$1000] Payment issue for #23517 #30249 - Expensify`. It should have the old reporting bonus amount since this was reported before the change.

Can you please confirm that and accept the job? Thank you!

**Comment by kassahun-asefa** [comment] 2023-10-24 13:06
@johncschuster Yes, it was reported before the change on the reporting bonus and I have just accepted the job.

**Comment by kassahun-asefa** [comment] 2023-10-26 05:00
@johncschuster would you issue payment? I have requested payment on the job you sent.

**Comment by johncschuster** [comment] 2023-10-26 19:38
Working on this now!

**Comment by johncschuster** [comment] 2023-10-26 19:39
Payment has been issued! Thanks for your patience @kassahun-asefa!

**Closed** 2023-10-26 19:39 UTC
Labels: External, Engineering, Daily, Weekly, Help Wanted, Bug

**Comment by kassahun-asefa** [comment] 2023-10-26 20:09
> Payment has been issued! Thanks for your patience @kassahun-asefa!

Received. Thank you.
