### ISSUE TITLE
[$500] The error message when adding New Contact Method using an email with a domain that restricts account creation is NOT consistent

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#28027] opened 2023-09-22 15:49 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Login to any account.
2. Go to Account settings >> Profile > Contact Method.
3. Add a new contact method using a NEW email with the domain "[applause.expensifail.com](http://applause.expensifail.com/)."
4. Observe the error message that says: "It looks like the company administrator for…"
5. Go to Workspace settings (create a new workspace if it does not exist) >> Invite the email used in step # 3. (There will be an error)
6. Repeat step # 3 and check the error.
7. Observe that now the message says: "The new login you are trying to add is already a secondary login of another account" -which is different from the message shown in # 4.
## Expected Result:
1. The error message when adding "New contact method" at step # 3 should be consistent.
2. It seems like a new account will be created when inviting a member at step 5, which conflicts with the error message when adding a "New contact method."
## Actual Result:
The error message when adding an email with a domain that restricts account creation is not consistent.
## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9e4a8138-a13e-4573-b484-b20ff72e7348

https://github.com/Expensify/App/assets/43996225/e257b7a2-5686-49fb-b3d9-dec86170b2f9

**Expensify/Expensify Issue URL:**
**Issue reported by:** @tranvantoan-qn
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1695053997602399

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ba52a402cb44145</li>
        <li>Upwork Job ID: 1705247863593766912</li>
        <li>Last Price Increase: 2023-10-13</li>
    </ul>
</details>

**Comment by s-alves10** [comment] 2023-09-22 16:13
This looks like a backend issue. We might need to check `AddMembersToWorkspace` API if it stores any information though it fails

**Comment by stephanieelliott** [comment] 2023-09-29 06:24
I'm not able to reproduce this -- adding a new [applause.expensifail.com](http://applause.expensifail.com/) contact method does not produce an error. Tried on both Chrome and Safari: 

Uploading 2023-09-29_14-22-45.mp4…

**Comment by tranvantoan-qn** [comment] 2023-09-29 07:27
@stephanieelliott It looks like there is an issue uploading your video so I couldn't check the step you did
But the issue is still happening 
![image](https://github.com/Expensify/App/assets/10254571/87f67185-3d76-422b-9a7e-1ccad19c2fb8)

**Comment by stephanieelliott** [comment] 2023-10-04 12:29
I’m still not able to repro this —I was able to repro error 1 by switching to a non-admin test account (which is an expected error), but am not able to repro error 2. The behavior I am seeing right now is expected — @kavimuru can you try reproducing the entire flow once more? 
 
Reason I'm testing this is because the test account could've in fact been been a secondary login for another account, in which case error 1 and error 2 would be expected. 

https://github.com/Expensify/App/assets/31225194/a0ea5534-0ff3-4e07-80f6-b03e90368a3a

**Comment by tranvantoan-qn** [comment] 2023-10-04 16:29
@stephanieelliott at `0:17` I think you need to click on the **Remove** button to _remove the error and that account_ - in order to be able to find and add that account again as a Workspace member at `0:29`

(FYI: Even if we fail to add an account as a contact method, we should still be able to search for it in Workspace search - so I think this can be considered as other issue)

**Comment by tranvantoan-qn** [comment] 2023-10-04 16:46
@stephanieelliott 
Please check this video, where I explained everything, then you will be able to reproduce it 
https://www.loom.com/share/1e1d9864191e44f0936fe0a53d53fd1d

**Comment by eVoloshchak** [comment] 2023-10-09 09:55
Can reproduce this using the steps from the issue description 

https://github.com/Expensify/App/assets/9059945/b21b2126-6901-42d2-9318-1b8194c91bee

Not overdue, awaiting proposals

**Comment by stephanieelliott** [comment] 2023-10-11 05:21
Still awaiting proposals

**Comment by eVoloshchak** [comment] 2023-10-16 08:59
Not overdue, waiting for proposals

**Comment by stephanieelliott** [comment] 2023-10-25 04:23
still waiting for proposals

**Comment by stephanieelliott** [comment] 2023-10-25 22:48
Just adding a note here that this feels edge case and somewhat low value to me. I'll leave it open for proposals, but I don't think it's worth pulling in an internal engineer away from more high value work to focus on.

**Comment by barttom** [comment] 2023-11-02 08:19
Hi! I'm Bartek from Callstack and would to work on this issue.

**Comment by stephanieelliott** [comment] 2023-11-06 21:04
Still waiting for proposals

**Comment by stephanieelliott** [comment] 2023-11-28 03:14
I still believe this is low value and somewhat edge case.  Given that we have not received any proposals to fix it I am going to go ahead and close this.

**Closed by stephanieelliott** 2023-11-28 03:14 UTC
Labels: Engineering, Weekly, Internal, Overdue, Bug
