### ISSUE TITLE
[HOLD for payment 2023-11-21] [$500] Wrong position of payment method dropdown menu

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#31069] opened 2023-11-08 16:45 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Dev only
**Reproducible in staging?:** DEV
**Reproducible in production?:** DEV
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @situchan 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1699446024052489

## Action Performed:
1. Open a report as account A
2. Send a Request money to Account B
3. Open the IOU detail

## Expected Result:
Pay with expensify button appears within the card

## Actual Result:
Pay with expensify button appears in the wrong position

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

![bug](https://github.com/Expensify/App/assets/38435837/dd5b6a4c-ace7-4c7b-aa82-174b78feb0bf)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c488f2cde0f92e3d</li>
        <li>Upwork Job ID: 1722899907570507776</li>
        <li>Last Price Increase: 2023-11-10</li>
<li>Automatic offers: </li>
<ul>
<li>getusha | Reviewer | 27606931</li>
<li>s-alves10 | Contributor | 27606933</li>
<li>situchan | Reporter | 27606934</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @conorpendergrast</details>

**Comment by s-alves10** [comment] 2023-11-09 01:36
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Popover menu of payment method dropdown button is shown at the wrong position

### What is the root cause of that problem?

We measure the anchor position of the popover menu below
https://github.com/Expensify/App/blob/3f2de5c41a1dffd53b0d6ddefbc675d5a27ad6f5/src/components/ButtonWithDropdownMenu.js#L91-L99

This works fine but it gives a wrong position inside the inverted flat list. In inverted `FlatList`, -1 of scale is applied and measureInWindow gives the scaled result(Refer https://reactnative.dev/docs/flatlist#inverted). This looks like come from the recent change of `react-native-web` in this PR

Scaled measurement returns: This is the root cause

### What changes do you think we should make in order to solve the problem?

We need to take this scaled result into consideration

1. Add the props named `shouldInvertMeasurement` with default value `false` to the [ButtonWithDropdownMenu](https://github.com/Expensify/App/blob/main/src/components/ButtonWithDropdownMenu.js) and [SettlementButton](https://github.com/Expensify/App/blob/main/src/components/SettlementButton.js) components
2. Update the above code to
```
caretButton.current.measureInWindow((x, y, w, h) => {
            const horizontal = x + w;
            const vertical = props.shouldInvertMeasurement ? windowHeight - y + 18 : y; // weird offset in inverted mode
            setPopoverAnchorPosition({
                horizontal,
                vertical: props.anchorAlignment.vertical === CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP
                    ? vertical + h + CONST.MODAL.POPOVER_MENU_PADDING // if vertical anchorAlignment is TOP, menu will open below the button and we need to add the height of button and padding
                    : vertical - CONST.MODAL.POPOVER_MENU_PADDING, // if it is BOTTOM, menu will open above the button so NO need to add height but DO subtract padding
            });
        });
```
3. Add `shouldInvertMeasurement` props with value `true` [here](https://github.com/Expensify/App/blob/3f2de5c41a1dffd53b0d6ddefbc675d5a27ad6f5/src/components/ReportActionItem/ReportPreview.js#L265) in `ReportPreview` component

This works as expected

<details>
    <summary>Result</summary>

![image](https://github.com/Expensify/App/assets/126839717/7e11f370-dd5c-4794-94cf-454bbc5bf7bd)

</details>

### What alternative solutions did you explore? (Optional)

**Comment by s-alves10** [comment] 2023-11-09 09:50
This is reproducible in staging, and not in production. Can be a deploy blocker

cc @m-natarajan @conorpendergrast

**Comment by situchan** [comment] 2023-11-09 14:59
@s-alves10 Scanning code in [RNW upgrade](https://github.com/necolas/react-native-web/pull/2377), I don't see any change in UIManager.

**Comment by situchan** [comment] 2023-11-09 15:01
> This works fine but it gives a wrong position inside the inverted flat list. In inverted FlatList, -1 of scale is applied and measureInWindow gives the scaled result

Why used to work before RNW upgrade?

**Comment by situchan** [comment] 2023-11-09 15:05
I am fine applying patch for now to fix deploy blocker but we should fix the real root cause for sure.
@getusha do you think this solution makes sense?
```diff
-        var _getRect2 = getRect(node),
+        var _getRect2 = node.getBoundingClientRect(),
```

**Comment by s-alves10** [comment] 2023-11-09 15:06
I debugged the RNW and `getRect` function in UIManager returns the wrong result for inverted FlatList. In the previous version, it works fine

**Comment by s-alves10** [comment] 2023-11-09 15:07
The `getBoundingClientRect` method returns the size of an element and its position relative to the viewport.

**Comment by getusha** [comment] 2023-11-09 15:16
@s-alves10 @situchan probably adding `shouldUseTargetLocation` prop to `PopoverWithMeasuredContent` will solve this issue because we added that for this kind of issue. i am not sure if it will be accurate might need a slight touch.

**Comment by situchan** [comment] 2023-11-09 15:22
@s-alves10 I see that `shouldUseTargetLocation` is added in emoji picker. Can you verify your patch will fix both issues without `shouldUseTargetLocation`?

**Comment by s-alves10** [comment] 2023-11-09 15:24
Sure

**Comment by s-alves10** [comment] 2023-11-09 15:57
@situchan 

I've verified that emoji picker and dropdown button works fine with the proposed patch

**Comment by situchan** [comment] 2023-11-09 15:58
@s-alves10's [proposal (main solution)](https://github.com/Expensify/App/issues/31069#issuecomment-1803025437) looks good to me.
🎀 👀 🎀 C+ reviewed

**Comment by getusha** [comment] 2023-11-09 16:01
@situchan I think we should also create upstream PR, but i feel like it might not be accepted.

**Comment by situchan** [comment] 2023-11-09 16:02
> @situchan I think we should also create upstream PR, but i feel like it might not be accepted.

But at least we can let author know.

**Comment by situchan** [comment] 2023-11-09 16:06
@arosiclair will decide whether to
- apply patch
- or use existing solution applied during RNW upgrade to fix emoji picker position

**Comment by getusha** [comment] 2023-11-09 16:08
@s-alves10 can you share how the popover will look like after applying the patch.

**Comment by s-alves10** [comment] 2023-11-09 16:12
@getusha 

Here are the screenshots

![image](https://github.com/Expensify/App/assets/126839717/94c7d9b6-c8ad-4904-8f65-85fe878cab07)
![image](https://github.com/Expensify/App/assets/126839717/338c366a-4790-4798-b9c4-1126e61521f5)
![image](https://github.com/Expensify/App/assets/126839717/f3479efc-7833-40fe-bc16-0544e4c133b4)
![image](https://github.com/Expensify/App/assets/126839717/0f8bf118-115a-491e-a8d7-eb8b16839d83)
![image](https://github.com/Expensify/App/assets/126839717/27a3d89c-676d-4f73-9e0e-27cfae25b55e)

cc @situchan

**Comment by arosiclair** [comment] 2023-11-09 17:54
Okay I've verified that this is reproducible on staging **v1.3.97-3** and not on prod **v1.3.95-9**:


<img width="400" src="https://github.com/Expensify/App/assets/6833644/00eb1ec7-f8e4-4655-a0f6-e61d68fb6ac4" />
<img width="400" src="https://github.com/Expensify/App/assets/6833644/67ce0490-c622-4a23-9907-e4f60e0ac2de" />

**Comment by arosiclair** [comment] 2023-11-09 18:03
@situchan you should wait for bugs to be reproducible on staging before reporting. QA and BZ's cannot reproduce anything that hasn't been deployed so this couldn't be properly marked as a deploy blocker from the beginning

**Comment by arosiclair** [comment] 2023-11-09 20:13
> or use existing solution applied during RNW upgrade to fix emoji picker position

@situchan can you expand on this? Are you referring to the workaround posted [here](https://github.com/necolas/react-native-web/issues/2589#issuecomment-1749486083)? If so can you or @s-alves10 draft a proposal for that in our app?

**Comment by situchan** [comment] 2023-11-09 20:29
> > or use existing solution applied during RNW upgrade to fix emoji picker position
> 
> @situchan can you expand on this? Are you referring to the workaround posted [here](https://github.com/necolas/react-native-web/issues/2589#issuecomment-1749486083)? If so can you or @s-alves10 draft a proposal for that in our app?

I meant https://github.com/Expensify/App/commit/02aa98104c0d9e9c3cf9dd510dc429967c93753f and https://github.com/Expensify/App/commit/05ad0e8a500ce903287badfad584151ae464d981 to fix popover position issues like https://github.com/Expensify/App/pull/24482#issuecomment-1795028121

**Comment by situchan** [comment] 2023-11-09 20:33
@ishpaul777 your solution doesn't fix the root cause and I am concerned same issue might happen in any other popovers we haven't found yet

**Comment by arosiclair** [comment] 2023-11-09 21:06
> I meant [02aa981](https://github.com/Expensify/App/commit/02aa98104c0d9e9c3cf9dd510dc429967c93753f) and [05ad0e8](https://github.com/Expensify/App/commit/05ad0e8a500ce903287badfad584151ae464d981) to fix popover position issues like [#24482 (comment)](https://github.com/Expensify/App/pull/24482#issuecomment-1795028121)

Thanks, that makes sense to me but I don't fully understand these changes and I see now that this is a regression from https://github.com/Expensify/App/pull/24482.

I'm going to assign @getusha since you implemented those changes and @mountiny and @roryabraham since you guys are the engineers that reviewed.

**Comment by mountiny** [comment] 2023-11-10 08:55
@s-alves10 can you raise a pr, i think that we should use the in App fix without patch which we use elsewhere already

**Comment by s-alves10** [comment] 2023-11-10 13:23
@mountiny @situchan @getusha 

PR is ready for review https://github.com/Expensify/App/pull/31184

**Comment by mountiny** [comment] 2023-11-10 15:07
Asking QA to confirm in staging, I am not in the beta so cant do it

**Comment by mountiny** [comment] 2023-11-10 15:19
QA passed

**Comment by conorpendergrast** [comment] 2023-11-23 20:34
Looks like this didn't get switched to Daily, and it's due payment!

**Comment by conorpendergrast** [comment] 2023-11-23 20:40
Payouts due:


- [ ] Issue Reporter: $50 @situchan requires payment [offer](https://www.upwork.com/nx/wm/offer/27606934)

- Contributor+: N/A @getusha - [regression](https://github.com/Expensify/App/issues/31069#issuecomment-1804685353)

- [ ] Contributor: $500 @s-alves10 requires payment [offer](https://www.upwork.com/nx/wm/offer/27606933)

Upwork job is [here](https://www.upwork.com/jobs/~01c488f2cde0f92e3d).

**Comment by situchan** [comment] 2023-11-23 20:41
I also reviewed PR

**Comment by conorpendergrast** [comment] 2023-11-23 20:45
@situchan thanks, I had missed that. Noting for my future self: I see you listed as a reviewer for [the PR that caused this regression](https://github.com/Expensify/App/pull/24482) but that's from comments made two days ago, so are not relevant to this issue and don't change payment

**Comment by conorpendergrast** [comment] 2023-11-23 20:47
@s-alves10 please accept [the offer](https://www.upwork.com/nx/wm/offer/27606933)!

**Comment by conorpendergrast** [comment] 2023-11-23 20:49
@getusha Can you do [the C+ checklist](https://github.com/Expensify/App/issues/31069#issuecomment-1811373783) too, please? Thank you!

**Comment by s-alves10** [comment] 2023-11-23 23:36
@conorpendergrast 

Offer accepted, thanks

**Comment by getusha** [comment] 2023-11-24 05:07
@s-alves10 any updates on the upstream PR & issue? i am sure we shouldn't be ignoring that.

**Comment by s-alves10** [comment] 2023-11-24 05:29
https://expensify.slack.com/archives/C01GTK53T8Q/p1700803705123509?thread_ts=1699611327.310029&cid=C01GTK53T8Q

**Comment by conorpendergrast** [comment] 2023-11-24 09:46
Paid! Just the C+ checklist now

**Comment by getusha** [comment] 2023-11-24 09:54
**BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:

- [x] [@getusha] The PR that introduced the bug has been identified. Link to the PR: **N/A this is a bug from `react-native-web` introduced after upgrading to latest release.**
- [x] [@getusha] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- [x] [@getusha] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: N/A
- [x] [@getusha] Determine if we should create a regression test for this bug.  ****No** this a minor bug and react-native-web issue.**
- [x] [@getusha] If we decide to create a [regression test] (https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

**Comment by conorpendergrast** [comment] 2023-11-24 09:56
Nice! All done, thank you everyone

**Closed by conorpendergrast** 2023-11-24 09:56 UTC
Labels: External, Engineering, Daily, Awaiting Payment, Bug
