### ISSUE TITLE
Scan - Combined report and transaction thread with RBR appear in LHN when there is one request

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#39411] opened 2024-04-02 15:08 UTC
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to workspace chat that has no unsettled receipt
3. Create a scan request with an invalid receipt
4. When the request fails, go to request details page

## Expected Result:
Since now app directly opens combined report when there is only one request, there will not be another transaction thread in LHN when the scanning fails

## Actual Result:
When the scanning fails, both combined report and transaction thread with RBR show up in LHN. Both lead to the same page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/0a48fb63-6e98-494b-a42b-917faac362e2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e7292ebefd2a9a62</li>
        <li>Upwork Job ID: 1778132061840297984</li>
        <li>Last Price Increase: 2024-04-10</li>
    </ul>
</details>

**Comment by muttmuure** [comment] 2024-04-10 18:15
Might be a Collect issue

**Comment by muttmuure** [comment] 2024-04-10 18:17
Asked in the Collect channel: https://expensify.slack.com/archives/C036QM0SLJK/p1712773027858609

**Comment by muttmuure** [comment] 2024-04-10 18:44
cc @NikkiWines since this seems to be something you're working on?

**Comment by NikkiWines** [comment] 2024-04-10 20:03
Yeah, this looks like a regression of the logic added [here](https://github.com/Expensify/App/pull/36934/files#diff-577fcc5f3a5e4930916ff310e61c38edfa093792fe3ab55b9a30d2aecd8811dbR4422-R4425). We should only be showing the expense report, not the associated transaction thread, in the LHN

**Comment by muttmuure** [comment] 2024-05-08 08:05
Still waiting for proposals

**Comment by muttmuure** [comment] 2024-05-21 19:16
Awaiting proposals

**Comment by muttmuure** [comment] 2024-06-05 19:16
Waiting for proposals

**Comment by muttmuure** [comment] 2024-06-12 10:10
Waiting for someone to pick this up

**Comment by muttmuure** [comment] 2024-07-08 13:33
Still polish

**Comment by trjExpensify** [comment] 2024-08-09 01:46
Can you retest this? I have a feeling it got fixed a little while back. CC: @luacmartins

**Comment by luacmartins** [comment] 2024-08-09 09:00
I agree, I think we fixed this already. Let's wait for retest results to close this issue though

**Comment by trjExpensify** [comment] 2024-08-09 18:35
Sounds good!

**Comment by c3024** [comment] 2024-08-14 12:57
Tested this.

https://github.com/user-attachments/assets/5201a071-e8ed-4205-b1a3-0f02ea07f639

Not reproducible anymore!

**Comment by luacmartins** [comment] 2024-08-14 15:23
Nice. Closing the issue as per the comment above.

**Closed by luacmartins** 2024-08-14 15:23 UTC
Labels: Weekly, Internal, Bug, retest-weekly
